### ISSUE TITLE
"Pattern Settings" menu item and local task label should be "Pattern settings".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1000]
The "s" should not be capitalized:

![pattern_settings_camel_cased](https://cloud.githubusercontent.com/assets/2423362/8142905/f1e3f0b8-11d3-11e5-9dd1-e3e614f25a16.png)

We shouldn't bother with the same issue for the "Pattern List" menu/label because it will most likely change to "List patterns" (#525).

**Comment by quicksketch** [comment]
Great! Tagging novice.

**Comment by Dinornis** [comment]
I think this issue is now obsolete and can be closed as the `URL alias patterns` admin pages and menu changed since this issue was filed.  Tagging as fixed.

**Comment by klonos** [comment]
Yep, this has been addressed in #1250.

>Tagging as fixed.

Thanx for helping with triaging those old issues @Dinornis 👍 In the issue queue in d.org we had "Closed (cannot reproduce)" and "Closed (outdated)" that we can use in such cases. I've added these for us too 😉

**Comment by Dinornis** [comment]
Thanks, the new tags will be useful.  Are there any guidelines for using any of the available tags?  I know, most are self explanatory, but it would be helpful for newcomers like me to avoid causing any problems.  I already made a few mistakes.

**Comment by klonos** [comment]
Sorry for the late reply @Dinornis. Still trying to catch up with the issue queue. You don't need to worry about tagging things with the "wrong" tag. I do that myself all the time and usually have @jenlampton jump in later and change tags/milestones accordingly. As you said, the tags are pretty self-explanatory, so I'd say go with your gut feeling.
