### ISSUE TITLE
Missing closing tag in core's layout.tpl.php

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1007]
In the header block we have an opening `div.section.clearfix`, but no closing `</div>`

**Comment by wesruv** [comment]
@quicksketch PR ready here: https://github.com/backdrop/backdrop/pull/954

**Comment by klonos** [comment]
Good catch @wesruv

**Comment by quicksketch** [comment]
Thanks for catching this. Could the PR be updated per feedback from https://github.com/backdrop/backdrop/pull/954#issuecomment-133644821?

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.1.x.
