### ISSUE TITLE
In Seven theme, html { display: table; } style is breaking stuff

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1008]
https://github.com/backdrop/backdrop/commit/69158bc2d1b9840a0035bae834bdb8f500fdd0c8#diff-0a893b196c3a6a8f21edb2446f58293dR1227

From the commit this comes from, it looks like it was added to get the nice install screen to vertically center. Unfortunately display: table is breaking CSS layout for me when the width constraint of the page needs to be firm.

Need to update display:table style to only apply to maintenance page.

**Comment by wesruv** [comment]
PR for fix here: https://github.com/backdrop/backdrop/pull/955

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.1.x.
