### ISSUE TITLE
Language prefix added twice in the link of the "Cancel" button in the "Add term" form.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1010]
The URL to access the form is for example `/admin/structure/taxonomy/tags/add` (for the default "Tags" vocabulary that we ship with core). The "Cancel" link/button at the bottom of the form is `/en/en/admin/structure/taxonomy`. Notice the double `/en` in the URL. It leads to a "Page not found page".

Steps to reproduce:
1. Add a second language to your installation (`/admin/config/regional/language/add`).
2. Go to the "Detection and selection" page (`/admin/config/regional/language/detection`) and enable the "URL" detection method.
3. Configure the "URL" detection method (``/admin/config/regional/language/detection/url`) to have a path prefix.
4. Go to the "Add term" page of the "Tags" vocabulary (`en/admin/structure/taxonomy/tags/add`) and notice the erroneous link for the "Cancel" button.

**Comment by Dinornis** [comment]
Must have been fixed already?  The `Cancel` link in 1.7.x-dev now points to `/en/admin/structure/taxonomy/tags`

**Comment by klonos** [comment]
Yep, this must have been fixed at some point (either that, or could have been a problem with my local). I cannot reproduce this any more, so closing...
