### ISSUE TITLE
body class 'page-node-N' in Drupal 7; how to do this in Backdrop?

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1011]
Apologies if this has been explained somewhere, but I haven't been able to find the answer. Drupal 7 adds various classes to the body tag, and one I have sometimes used is page-node-N where N is the node causing the page. This is useful, for example, to use a different background image for different nodes/pages. How can I do this in Backdrop? Do I have to use a different layout for each case? I have a site needing 7 different backgrounds.

Any advice please?

**Comment by quicksketch** [comment]
You can use hook_preprocess_page() either in your theme or in a module:

```php
function template_preprocess_page(&$variables) {
  $node = menu_get_object();
  if ($node) {
    $variables['classes'][] = 'page-node-' . $node->nid;
  }
```

**Comment by Graham-72** [comment]
@quicksketch Thanks. Great, just what I needed.

**Comment by quicksketch** [comment]
Yay, great. :smile:

**Comment by Graham-72** [comment]
I might say 'magic' but it's not, it's Backdrop!

**Comment by bd0bd** [comment]
I am sorry, I need the same (for changing width of l-content and l-sidebar of certain page). May be somebody could tell me what is the file's name where I need to place this code in:

function [my_theme]_preprocess_page(&$variables) {
  $node = menu_get_object();
  if ($node) {
    $variables['classes'][] = 'page-node-' . $node->nid;
  }
}

Thank you!

**Comment by Graham-72** [comment]
@bd0bd In my case I put it at the beginning of template.php in my theme folder.

**Comment by bd0bd** [comment]
Thank you!
Everything is working well.
I have placed the code in template.php file located at **/core/themes/bartik**

**Comment by Graham-72** [comment]
Good. But putting it in a theme in core means it wiĺl be overwritten when you next upgrade. Better I believe  to copy the whole theme to the separate themes folder. 

But great that you have it working. 
Graham 


Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by bd0bd** [comment]
Thank you! Yes, I know and remember about this matter.
