### ISSUE TITLE
Minor typo in 1.1.2 release notes.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1013]
https://github.com/backdrop/backdrop/releases/tag/1.1.2

> Backdrop CMS 1.1.2 brings patch-parity with Drupal 7.38, including all the bug fixes that were part of 7.36 and 3.37.

3.37 should be 7.37 instead.

**Comment by quicksketch** [comment]
Thanks! You're quite correct. Fixed!

**Comment by klonos** [comment]
Thanx. :+1:
