### ISSUE TITLE
[UX] Unexpected behaviour - disappearance from menu

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1014]
I am not sure whether this is incorrect behaviour but, for me, it was unexpected.

I devised a new content type and used it to create a page which I then added to my Primary Navigation.

But later, if I edited this node, it disappeared from my Primary Navigation.

This seems to be because when creating this new content type I had not enabled the menu settings option. But I would have thought that manually adding it as a link in the Primary Navigation should take precedence, and not be over-ridden by the absence of a menu setting on the node edit form. 

Anyway, it is no problem once you realise that menu settings must be enabled when creating a new content type.

Generally, I am loving working with Backdrop. Thanks everyone!

**Comment by quicksketch** [comment]
Thanks @Graham-72! Definitely sounds like a bug to me. Any menu item for a node should always stay in place if it was manually added.

**Comment by Dinornis** [comment]
@Graham-72 
I am trying to reproduce this with BD 1.5 and was not able to.  Perhaps it has been already fixed?

**Comment by laryn** [comment]
I just tried as well and the manually-added menu item does not disappear after editing the node, even with a new content type that does not (and never did) have menu settings enabled.

**Comment by Dinornis** [comment]
I will close this, we can reopen if necessary.

**Comment by Graham-72** [comment]
Looking at the date of my initial report, this must have been with BD 1.1.2 and much has changed since then. So it is almost certainly fixed now.
