### ISSUE TITLE
"Files displayed by default" checkbox should be in disabled state until the "Enable Display field" checkbox is checked.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1015]
The help text under that checkbox says: "This setting only has an effect if the display option is enabled.". So it makes sense to have it disabled while the "Enable Display field" checkbox is not checked.

![file_field-display_settings](https://cloud.githubusercontent.com/assets/2423362/8256329/c0fd9c2c-16e9-11e5-9ed6-e1d22a7b2e5d.png)

**Comment by BWPanda** [comment]
This has since been fixed: 
![Peek 2020-10-04 12-13](https://user-images.githubusercontent.com/2385329/95004734-192abb00-063b-11eb-8c84-b6ed1d5db231.gif)

**Comment by klonos** [comment]
FTR: this was fixed in #2023
