### ISSUE TITLE
[UX] Block visibility conditions: Improve the is/is-not setting for "Front page" condition.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1017]
Here's what the user gets:

![block_config-front_page_condition](https://cloud.githubusercontent.com/assets/2423362/8270392/998fafde-1821-11e5-984e-3c95327cda5e.png)

What I would like to see in general is the respective second-step config dialog for all options (front page/site language/user permission/user role/URL) to be shown in an JS/AJAX-y way without a second dialog reload, but that's probably another issue (edit: #1020).

WTF is this "Reverse (NOT)"? Lets change this to a radio button that clearly states what the conditions are:

() is front page
() is NOT front page

**Comment by quicksketch** [comment]
Good idea. We inherited this "NOT" terminology from porting Panels conditions.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/983 makes a start on this but would require us to provide an update hook. Perhaps we can keep the internal representation while only changing the display of the options.

**Comment by quicksketch** [comment]
New PR at https://github.com/backdrop/backdrop/pull/1043.

How does this look?

![screenshot17](https://cloud.githubusercontent.com/assets/100206/9833141/34b752aa-594a-11e5-8a76-541f6f2a1ef0.png)

**Comment by docwilmot** [comment]
> Perhaps we can keep the internal representation while only changing the display of the options.

Absolutely agreed. And the radio button labels are good; maybe "Any page except the frontpage" instead of "every"?

**Comment by quicksketch** [comment]
> And the radio button labels are good; maybe "Any page except the frontpage" instead of "every"?

Good point, I've make that small change in the PR.

**Comment by klonos** [comment]
:+1: Perfect!!

**Comment by klonos** [comment]
...perhaps add something like "Show when" in front of "Current path is". So, full thing should read "Show when current path is:"

**Comment by quicksketch** [comment]
> ...perhaps add something like "Show when" in front of "Current path is". So, full thing should read "Show when current path is:"

Yeah, I wasn't sure about adding a verb like "Show" onto the form for a condition. Conditions can be used for more things than just hiding or showing. For example, show/hide isn't the right verb when selecting the appropriate layout from multiple layouts at the same path. Rather than "show/hide this block if...", it's "select this layout if...". I hope it's not premature abstraction for terminology, but conditions already can be used for two different purposes.

**Comment by klonos** [comment]
Fair enough.

**Comment by quicksketch** [comment]
Great! Merged in https://github.com/backdrop/backdrop/pull/1043. As this is not strictly a bug fix, it will be in 1.2.0 only (and not 1.1.4).
