### ISSUE TITLE
Add a "Content type" visibility condition for blocks.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1018]
Here's the respective condition UI for D8:

![d8-block_config-content_type](https://cloud.githubusercontent.com/assets/2423362/8270452/2145603a-1823-11e5-9bd5-aacfa6505067.png)

We have no equivalent option:

![block_config-conditions](https://cloud.githubusercontent.com/assets/2423362/8270455/3abe09ae-1823-11e5-86db-821fb2a2b4d6.png)

**Comment by quicksketch** [comment]
This already exists but it only works if you're on a layout that has a "Node" context, e.g. overriding `node/%`. Unfortunately that means that you can't add a block in the default layout that selects by node type, but it's not that difficult to make a node/% layout when needing node-specific blocks. If upgrading from a D7 site, both a default and node/% layout are created if upgrading node-specific visibility blocks.

![node-type](https://cloud.githubusercontent.com/assets/100206/8293142/bde25ab0-18f0-11e5-8af9-a7c604ad6cf5.png)

**Comment by klonos** [comment]
Makes perfect sense. Thanx for the clarification Nate.
