### ISSUE TITLE
[UX] Block settings: Consider renaming "Conditions" fieldset to "Visibility" or "Visibility conditions".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1019]
D8 uses the term "Visibility" and since that setting controls whether a block is shown or not, I think it is more suitable. Even better would be "Visibility conditions" that leaves no room for doubt of what the fieldset holds, but I'm not sure if others have concerns with regards to the length of the label.

**Comment by quicksketch** [comment]
Sure, I'd be fine with either. "Visibility conditions" seems like a better one to me, the label length isn't an issue in this area I don't think.

**Comment by quicksketch** [comment]
This is great! I tried out the PR and I find this substantially less intimidating than just "Conditions" that are ambiguous about what they are making conditional. Merged into 1.x and 1.1.x.
