### ISSUE TITLE
[UX] Block configuration: "dirty" from flag fired even if user cancels adding a condition.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1022]
Steps to reproduce:
1. Edit any layout that has blocks.
2. Click the "configure" button for one of the blocks.
3. Expand the "Conditions" fieldset and click on "Add condition".
4. Select any condition (for example "Front page") and click on "Add condition".

Notice how the "dirty" from flag has been fired and there is a "The form has unsaved changes ..." message in the background.
1. Hit the "Cancel" button instead of the "Add condition".

Notice how you return to the layout config page with the condition not saved (you've hit the "cancel" button in step 5 previously), but the "The form has unsaved changes ..." message is still there.
1. Refresh the page and see the message is still there.
2. Hit the "cancel" button at the bottom of the page in order to remove the "dirty" form flag.

PS: This is one of the reasons why I think we should move all the steps required for adding a condition in the same dialogue form: #1020

**Comment by quicksketch** [comment]
The issue over in https://github.com/backdrop/backdrop-issues/issues/1020 and associated PR will solve this problem as a side-effect of the new implementation for adding conditions, as there won't be a separate dialog for configuring a condition any more, it'll be combined with the existing dialog for adding a condition. Let's close to consolidate issues.
