### ISSUE TITLE
Block conditions not displayed as a bullet list in the config block dialogue.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1023]
![block_conditions_not_displayed_as_list_in_modal](https://cloud.githubusercontent.com/assets/2423362/8270705/d4b397a0-1831-11e5-927c-6790a7b12349.png)

**Comment by klonos** [comment]
...and I think that the "+ Add condition" link/button should move above the list of conditions because that is the pattern used for all "+ Add xyz" links in the UI.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1189.
