### ISSUE TITLE
[UX] Move the list of conditions in the block config dialogue below the "+ Add condition" link/button.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1024]
![block_config-move_add_link_above_condition_list](https://cloud.githubusercontent.com/assets/2423362/8270723/d99a4042-1832-11e5-86c7-4828afb5093c.png)

---
PR by @hellomrcat: https://github.com/backdrop/backdrop/pull/976

**Comment by quicksketch** [comment]
Sounds good to me.

**Comment by klonos** [comment]
...same issue in the layout add (```/admin/structure/layouts/add```) page:

![layout_add-move_add_link_above_condition_list](https://cloud.githubusercontent.com/assets/2423362/8356625/da27f670-1b99-11e5-8791-434f8f202e0b.png)

**Comment by klonos** [comment]
Do we fix it in one go, or separate issue?

**Comment by quicksketch** [comment]
> Do we fix it in one go, or separate issue?

Let's do a new one. I merged in https://github.com/backdrop/backdrop/issues/976 that solves the conditions for blocks but not layouts.

**Comment by klonos** [comment]
>> Do we fix it in one go, or separate issue?

> Let's do a new one...

Done!
