### ISSUE TITLE
Backdrop and contrib download count.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1026]
[Getting the download count for your releases](https://help.github.com/articles/getting-the-download-count-for-your-releases/)

**Comment by docwilmot** [comment]
Incidentally, you can get the download count by just visiting the url in your browser. The download count is in there.

All releases: 

`https://api.github.com/repos/backdrop-contrib/<THE_PROJECT_NAME>/releases`

Single release:

`https://api.github.com/repos/backdrop-contrib/<THE_PROJECT_NAME>/releases/<RELEASE_ID>`

Latest release:

`https://api.github.com/repos/backdrop-contrib/<THE_PROJECT_NAME>/releases/latest`

Just found this out.

**Comment by quicksketch** [comment]
Yep, though unfortunately this is not a cumulative total. Each release that has an official packaged archive attached as an asset gets an individual download count, but there's not a total download count. Obviously we can add up all the release totals, but it's just a little more difficult to build this total.

**Comment by klonos** [comment]
Thanx @docwilmot! Does not work for Backdrop itself though (does, but no download count):

https://api.github.com/repos/backdrop/backdrop/releases

**Comment by BWPanda** [comment]
I don't see a question here, so assume this was just sharing of information. Will close this now.
