### ISSUE TITLE
backdrop_get_path() doesn't find layouts

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1027]
Also should find libraries, but bigger issue here: https://github.com/backdrop/backdrop-issues/issues/159

This should be major I think.

**Comment by docwilmot** [comment]
Note that a simple fix is to change line 969 of `backdrop_get_filename()` in `bootstrap.inc` from 
```
      elseif ($type == 'theme') {
```
to 
```
      elseif ($type == 'theme' || $type == 'layout') {
```

But this function checks, in order, a static variable, then the `system` table, then does a file read for projects by location and extension. So related of course is [Layouts not in 'system' table #996](https://github.com/backdrop/backdrop-issues/issues/996).

So to fix this issue should we do the simple fix or fix first #996?

**Comment by quicksketch** [comment]
Hm, I think the most efficient way of handling this would probably be to use the already-existing Layout cache that is stored in layout_get_layout_info(). So perhaps our check should be:

```php
if ($type === 'layout' && function_exists('layout_get_layout_info')) {
  if ($layout_info = layout_get_layout_info($name)) {
    $path = $layout_info['path']
  }
}
```

Note that because Layout module is a module (and not strictly required), adding a check to make sure the function exists might be necessary.

**Comment by docwilmot** [comment]
> Note that because Layout module is a module (and not strictly required)

Which als means layouts shouldnt be in `system` either, right?

**Comment by quicksketch** [comment]
> Which als means layouts shouldnt be in system either, right?

Right, I would think that would be the case. :)

**Comment by serundeputy** [comment]
`PR` passed the travis ... I need to do some code cleanup and rebase;

**Comment by serundeputy** [comment]
cleaned up the code; updated doc block to indicate layout support; rebased;

**Comment by quicksketch** [comment]
Created a change notice at https://api.backdropcms.org/node/43068.
