### ISSUE TITLE
Add the word "permissions" to block permission conditions list in dialog

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1030]
Currently permission-type conditions just say `User has "Flush caches"`. Should be `User has "Flush caches" permissions` or similar.

![blockpermconditions](https://cloud.githubusercontent.com/assets/1042283/8295590/d91fe50c-190b-11e5-8e9e-6d0bef92eab9.PNG)

**Comment by quicksketch** [comment]
:+1:

**Comment by quicksketch** [comment]
Great, thanks @hellomrcat! Merged in 1.x and 1.1.x.
