### ISSUE TITLE
The "(i.e. <br> and <p>)" example in text format configuration form is rendered funny in the "Filter processing order" section.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1031]
I've noticed this while going through https://github.com/backdrop/backdrop-issues/issues/101#issuecomment-114659010

![text_format_config-line_breaks](https://cloud.githubusercontent.com/assets/2423362/8319172/370617e2-1a4f-11e5-8e63-95e78f36c214.png)

**Comment by quicksketch** [comment]
Looks like we have an unnecessary check_plain() in there somewhere. I'll take a look at this.

**Comment by quicksketch** [comment]
Simple fix: https://github.com/backdrop/backdrop/pull/978

I couldn't find any reason why this check_plain() is necessary. The filter label is never user-defined, it only comes from code, so there's no risk in allowing HTML tags in this area.

**Comment by quicksketch** [comment]
Looks like I added the unnecessary escaping back when text formats were converted to config in #172. Doh!
