### ISSUE TITLE
[UX] Decrease textarea default size from 20 rows to 10

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1034]
When creating a new node, the default textarea size is unnusually large. From @docwilmot  https://github.com/backdrop/backdrop-issues/issues/736#issuecomment-100474068:

---

the default body field for add content is huge!! Its set at 20 rows, could we make it 10? Unless youre writing a PhD thesis in there, I think 10 would do. _Fullscreen_ shots follow:

See 20 rows(current):
![rows20](https://cloud.githubusercontent.com/assets/1042283/7550154/e8365f6a-f61c-11e4-9e54-ced83cd5a73d.PNG)

See 10 rows:
![rows10](https://cloud.githubusercontent.com/assets/1042283/7550158/fbaf01a0-f61c-11e4-9882-161ef265e0b7.PNG)

D8 for comparison  (9 rows):
![d8](https://cloud.githubusercontent.com/assets/1042283/7550161/0fbeb604-f61d-11e4-87b5-d4d8b4c878c9.PNG)

**Comment by klonos** [comment]
Yes, I think we should be fine with this change.

**Comment by quicksketch** [comment]
This is probably a novice task, adding tag. I think it's just a matter of reducing the defaults in the text area widget configuration.

**Comment by jenlampton** [comment]
One thing to note, this will not work anymore as soon as ckeditor gets into core as ckeditor does not respect the defined height of textareas.

**Comment by quicksketch** [comment]
> as soon as ckeditor gets into core as ckeditor does not respect the defined height of textareas.

It does now! https://github.com/backdrop/backdrop/blob/1.x-wysiwyg/core/modules/ckeditor/js/ckeditor.js#L21 :wink:

**Comment by klonos** [comment]
> It does now!

:+1:

**Comment by quicksketch** [comment]
Great, thanks! Merged into 1.x and 1.1.x.

**Comment by jenlampton** [comment]
<3
