### ISSUE TITLE
[UX] Token browser dialog: make token names clickable.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1037]
In order to expand the available token categories, one needs to click the triangle to the left of the name:

![token_browser_dialog-only_triangles_clickable](https://cloud.githubusercontent.com/assets/2423362/8390230/4f699b9e-1ccd-11e5-800d-86ecaa8deaab.png)

It is quite annoying to try clicking the name only to find that nothing happens. Plus, I believe that the triangle is too small a target for small screens like on mobile devices. Why not make the name clickable, or even the entire row?

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1871

**Comment by docwilmot** [comment]
:+1:

**Comment by quicksketch** [comment]
Thanks, seems like an obvious improvement we could make.

**Comment by MrHaroldA** [comment]
> Why not make the name clickable, or even the entire row?

Which is preferred?

**Comment by klonos** [comment]
I say lets try the name only. I think that it would provide enough clicking area.

**Comment by Dinornis** [comment]
👍

**Comment by klonos** [comment]
Hey, this was before I could file PRs 😄 ...trying to sneak this one in as a UX task 😈

**Comment by Al-Rozhkov** [comment]
I love this change! [Fitts's law](https://en.wikipedia.org/wiki/Fitts%27s_law) in action :smile:

**Comment by Dinornis** [comment]
Nice one, thanks.

**Comment by quicksketch** [comment]
Thanks everyone! Merged https://github.com/backdrop/backdrop/pull/1871 into 1.x and 1.6.x.

**Comment by klonos** [comment]
It's always good to see one of the oldies fixed 😄
