### ISSUE TITLE
[UX] Token browser dialog: "more" link wrapped below row for tokens that are nested too deep.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1038]
Same as #1029 / #741 but for the token browser dialog. The width in some cases like the _Content_ -> _Translation source node_ -> _Content type_ -> _Machine-readable name_ is too small and causes the "more" link to wrap in a second line:

![token_browser_dialog-width_too_small](https://cloud.githubusercontent.com/assets/2423362/8390281/c6e85b54-1ccf-11e5-8444-442752af7651.png)

**Comment by BWPanda** [comment]
Firstly I'll point out that the dialog is resizable, so you can always make it bigger yourself if it's too small. But secondly, I don't see a problem with increasing the default width and height a bit.

Here's a PR that changes the width/height from 600/500 to 800/600 respectively: https://github.com/backdrop/backdrop/pull/3345

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...code looks good, and it WFM 👍🏼 

PS: I have also tried playing around with the `autoResize` option for the modal dialog, but that a) doesn't work, and b) it disables the draggability of the dialog 👎🏼

**Comment by quicksketch** [comment]
Seems like a minimal harm issue and screen sizes have increased since Token module was introduced to core. Modal size is already fixed to 100% width on mobile.

Merged https://github.com/backdrop/backdrop/pull/3345 into 1.x and 1.24.x. Thanks @BWPanda and @klonos!
