### ISSUE TITLE
Backport Dialog API

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#104]
The WYSIWYG implementation in D8 is heavily dependent upon dialogs for uploading images, creating links, etc. The dialog API also can and should be used in our Views implementation, and in other places where it makes sense (confirmation forms, perhaps?)

The basics of the dialog system include a set of AJAX actions for opening and manipulating the dialog and special handling in the menu system for returning pages as dialogs if an HTTP header is set. We might change or forgo this level of integration with the menu system, as integration can also be accomplished by modifying the menu callbacks to support the dialog functionality directly.

Some related d.o issues:

[Add abstracted dialog to core](https://drupal.org/node/1667742)
[Add an ajax command which makes it easy to use the dialog API in complex cases](https://drupal.org/node/1870764)
[Convert Views to use the abstracted dialog modal](https://drupal.org/node/1851414)

@larowlan also wrote up an excellent summary of the API and functionality at http://previousnext.com.au/blog/understanding-drupal-8s-modal-api-and-dialog-controller.

**Comment by klonos** [comment]
This was part of #378
