### ISSUE TITLE
Add where hook is called to documentation in .api.php files?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1048]
Often it is nice to know, when debugging etc, where a hook gets called. If there is a simple way to do this please advise. But would it be reasonable to add a custom tag to label where a hook is called?
e.g in `system.api.php` (picked at random):

```
/**
 * Alter the element type information returned from modules.
 *
 * A module may implement this hook in order to alter the element type defaults
 * defined by a module.
 *
 * @param $type
 *   All element type defaults as collected by hook_element_info().
 *
 * @see hook_element_info()
 *
 * @calledin whatever_caller_function()  <========== NEW TAG!
 */
function hook_element_info_alter(&$type) {
  // Decrease the default size of textfields.
  if (isset($type['textfield']['#size'])) {
    $type['textfield']['#size'] = 40;
  }
}
```

**Comment by quicksketch** [comment]
This seems like a good idea to me, though unfortunately it would be a Backdrop-specific PHP tag. Usually we already try to use `@see` for this purpose (as is the case with your example), but `@see` is not limited to this purpose.

As for debugging, a backtrace will reveal where a hook has been invoked, but it can take some manual stepping back through the call stack to determine the calling function.

**Comment by docwilmot** [comment]
@see would do I guess, but it's not currently used for this particular purpose. 

If it is agreed to do this we'd need to put this in the docs as a standard and make a PR. Would be quite a chore though.

**Comment by quicksketch** [comment]
There's no harm at all in including `@see` references for hooks, I think it would be a great addition.

**Comment by MrHaroldA** [comment]
PhpStorm lists all modules that implement a hook here ;) Just put it in Drupal 8 mode, and it will show all places a hook is called, and which modules implement the hook: core and contrib.

**Comment by docwilmot** [comment]
Indeed, youre right, @MrHaroldA, thanks. And the API site also lists all invocations of hooks, except for the layout hooks, which is why I raised this issue in the first place, because I was searching for a layout hook invocation and didnt find it. Never realised that other hooks invocations were right there. 

Since this is easily accessible on from the API site, I dont think its necessary to pursue this any further right now, considering it is going to take a lot of work to start and to keep updated. 

Unless @quicksketch thinks this should go on, I guess we can close this, and open another issue on the API queue for why layout hooks invocations dont appear.

**Comment by quicksketch** [comment]
Sounds good to me. I imagine we may need to use `module_invoke()` to get picked up by API module, and I'm not sure that's used consistently.

**Comment by docwilmot** [comment]
> I imagine we may need to use module_invoke()
It seems the layout hooks are called in 
```
function _layout_get_all_info($data_type, $init = array()) {
...
    foreach (module_implements($data_type . '_info') as $module) {
```

where `$data_type` is 'renderer_info' or 'style_info' etc. So the `module_implements()` isnt picked up. 

So should probably just add the invocation as an `@see _layout_get_all_info()` just to those layouts.
