### ISSUE TITLE
Fatal error: Call to undefined function cache() in module.inc on line 159

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1050]
So I've upgraded my local AMP stack and when I browse to my test Backdrop installation, I am redirected to `http://localhost/backdrop/core/install.php` with this error:

```
Fatal error: Call to undefined function cache() in C:\www\backdrop\core\includes\module.inc on line 159
```

Any pointers before I install from scratch?

**Comment by serundeputy** [comment]
did you restore your DB after upgrading `AMP`; seems like this may have destroyed any DBs in `M` part of the stack.

Also make sure your `config_*` dirs are still in place.

Other than that; clear cache and run update.php

cheers.
~Geoff

**Comment by klonos** [comment]
Alright... back home on holiday with some time to spare again between trying to get as much as I can from my wife and daughter.

So:

- [x] ```config_*``` dirs in place and match the name listed in ```settings.php```
- [x] db is there with all the tables listed AFAICT
- [ ] trying to select any table in the db, throws ```#1932 - Table 'backdrop.[table_name]' doesn't exist in engine```

So I guess some corruption has occurred. I googled around for a solution also tried restoring my db files from a backup - no luck. Anyways, I'll try a few more things and then give up and start from scratch.

**Comment by serundeputy** [comment]
does your `settings.php` file have an incorrect `'#prefix' => 'backdrop'`?

**Comment by klonos** [comment]
> does your ```settings.php``` file have an incorrect ```'#prefix' => 'backdrop'```?

Nope: ```$database_prefix = '';``` the rest of the ```'prefix' =>``` entries in the "Advanced database settings" section are all commented out.

**Comment by klonos** [comment]
Anyways, not enough time to troubleshoot this any further, so closing. Decided to start from scratch. Now hit by #1072
