### ISSUE TITLE
[UX] Document theme_debug and set warnings where appropriate

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1052]
Ok... this was a 'we should have this' ticket, but apparently we do have it.

Now this is a 'we should document this' ticket.

@jenlampton @quicksketch is there a way I can help document this?

---

PRs by @findlabnet:
- ~~https://github.com/backdrop/backdrop/pull/1583~~
- https://github.com/backdrop/backdrop/pull/1699
- https://github.com/backdrop-contrib/devel/pull/28 (Merged, now in version 1.7.0 of Devel)

**Comment by wesruv** [comment]
OH MAN, WE HAVE IT! GLEEEEEE

**Comment by quicksketch** [comment]
I think we should document this in the developing themes documentation: https://api.backdropcms.org/node/41645

I've sent you an invite to the site so you can log-in.

**Comment by wesruv** [comment]
@quicksketch I didn't receive an e-mail so I went to the site and punched in my e-mail to "Reset Password". It said it sent an e-mail, but again no e-mail came through...

I'm checking the 'All Mail' filter in gmail, I doubt gmail's filtering it out entirely... thinking maybe the server isn't sending e-mail?

**Comment by quicksketch** [comment]
Oh dang. I'll take a look and see if I can get this sorted out.

**Comment by quicksketch** [comment]
It looks like the e-mails are indeed sending, but Gmail doesn't include it in the "All mail" filter, you'll need to check in the Spam directory itself to see the e-mails. I'm not sure why it's getting marked as spam. SPF records are set up correctly and reverse DNS seems to work, so it's odd that it's getting marked as spam.

**Comment by findlabnet** [comment]
A little hackish (but quick) solution for themers.
Add to the file THEME_NAME.info string:
```
settings[theme_debug] = true
```
And to the file theme-settings.php:
```php
$form['theme_debug'] = array(
  '#type' => 'checkbox',
  '#title' => t('Enable debug output.'),
  '#default_value' => config_get('system.core', 'theme_debug'),
  '#element_validate' => array('_theme_debug_settings'),
);

function _theme_debug_settings($element, &$form_state, $form) {
  config_set('system.core', 'theme_debug', $element['#value']);
}
```
Now, on theme settings form we have control for this system variable.

**Comment by quicksketch** [comment]
Ha, thanks @findlabnet, that's fairly clever. I'd like to see this option moved to Devel module for general use, although the audience of Devel isn't totally overlapped with your typical themer.

**Comment by jenlampton** [comment]
An interesting idea...  could we add this in core so that every theme would have this one single theme setting? I'm not sure how I'd feel if there was a per-theme UI for a global setting though. If that's what this does I'd vote for leaving the UI for it in devel module.

**Comment by findlabnet** [comment]
How about such solution:
sticked warning message on top of "Appearance" page when debug is enabled

![top](https://cloud.githubusercontent.com/assets/11479969/18002028/6b47fe3a-6b8e-11e6-8ccf-713ebc60ac61.png)

and a little form below to enable/disable theme debug system-wide.

![bottom](https://cloud.githubusercontent.com/assets/11479969/18002081/96ec89f2-6b8e-11e6-9ce5-ac0ac356cfbb.png)

Words "production environment" can be replaced with "live site" for more 'humanized'  perception.

**Comment by klonos** [comment]
> Instead of sticked warning message we can place information about it in "Status report".

I say we have it both on the site status page + on top of the Appearance page(s) as a warning message.

**Comment by findlabnet** [comment]
So, conclusion? Shall I PR this?

**Comment by jenlampton** [comment]
That would be great, thanks @findlabnet!  I'm not sure if we've agreed on this approach, but it sounds like we'll need 2 PRs, one for devel module and one for core.

PR for core that will affect how the site behaves if theme_debug is enabled:
* sets a warning message on any theme settings page
* sets a warning message in the status report

PR for [devel](https://github.com/backdrop-contrib/devel):
* adds a UI to enable / disable theme_debug

**Comment by findlabnet** [comment]
First iteration:
- https://github.com/backdrop/backdrop/pull/1583
- https://github.com/backdrop-contrib/devel/pull/28

**Comment by quicksketch** [comment]
Thanks @findlabnet! I merged https://github.com/backdrop-contrib/devel/pull/28 into Devel module and made a 1.7.0 release of that module.

I did a reroll of the core PR that removed the warnings from Installer module but left in place the ones on the theme listing and settings pages. If that passes all tests it's good for merging: https://github.com/backdrop/backdrop/pull/1699.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1699 into 1.x for 1.6.0.
