### ISSUE TITLE
Multisite documentation typo in README.md

### ISSUE THREAD

**Issue by PaulHoza** [backdrop/backdrop-issues#1054]
Under "Configuring sites.php" section, there's a single-character typo in the explanation of setting up the $sites array for multiple site directories:

```
$sites['example-a.com'] = 'example-a';
$sites['example-a.com'] = 'example-b';
```

The second line should read "$sites['example-b.com'] = 'example-b';"

**Comment by PaulHoza** [comment]
Well, there ya have it. I submitted my first PR... it's so very epic.

Sorry for the noise for a one-character documentation PR, but I'm also trying to get a handle on this process from all this.  I'll work on something more meaningful as soon as I can. :)

Please help me along here if I'm not doing all this correctly.  I feel a bit clunky (understatement) with the whole process of pushing to my own fork and doing my own PR, then doing the same process to PR to backdrop/backdrop, but I guess this is how I should be doing things from everything I'm reading.

...a little embarrassed by how much effort it took me to get this far. :/  Thanks for any help or encouragement for how to do this better if I got it wrong.

**Comment by quicksketch** [comment]
Hi @PaulHoza! You totally nailed it! Thanks for the PR, I've merged it into the 1.x and 1.1.x branches.

>  I feel a bit clunky (understatement) with the whole process of pushing to my own fork and doing my own PR, then doing the same process to PR to backdrop/backdrop, but I guess this is how I should be doing things from everything I'm reading.

It sounds like you did an extra step in there. You shouldn't need to file a PR against your own fork first. You did right by making a feature branch, then pushing that to your forked repository. Then within GitHub, you should be able to file a PR directly against the `backdrop/backdrop` repository.

Overall, great! Welcome and thank you for your help. We'd love to see more from you in the future. To help facilitate your maneuvering in the backdrop-issues repository, I've added you to the docs/organization team, which will allow you to label and assign issues.
