### ISSUE TITLE
New Apache 2.4 .htaccess for tmp and private files causes status report message

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1059]
Regression from #681: The new .htaccess protections for Apache 2.4 caused the status report page to always indicate that the .htaccess file for the Private and Temporary directories are always insecure on new site installations. This is because the patch adapted from https://www.drupal.org/node/1599774 actually *replaced* the entire contents of the .htaccess files, instead of appending or pre-pending. The contents of the private and temporary files directories are still secure, as all access is prevented, but the status report message is incorrect.

**Comment by serundeputy** [comment]
doh; thanks @quicksketch ;
