### ISSUE TITLE
Date api module faulty check on system date.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1064]
Part of META #1063 Travis reported syntax error, unexpected '[' in /home/travis/build/backdrop/backdrop/core/modules/date/date_api/date_api.module on line 1733.

**Comment by Graham-72** [comment]
Suggestions anyone please?
Parse error: syntax error, unexpected '[' in /home/travis/build/backdrop/backdrop/core/modules/date/date_api/date_api.module on line 1734

Why has https://github.com/Graham-72/backdrop/commit/6e2eef717d7b053eb173d5d8a63d17a4feaefa8f#diff-5a76874bca7e1bad9a3e4968e9ccc865 not solved this problem?
We now have
``
  if(is_array(system_date_format_load($type))){
    $format = system_date_format_load($type)['pattern'];
  }else{
    $format = system_date_format_load('medium')['pattern'];
  }
``
and this is in order to check that $type is a format listed in config system.date.json, otherwise use 'medium' as the default.

**Comment by Graham-72** [comment]
Travis is not liking my PHP use of if(is_array()) so will try using if(array_key_exists()) at line 1735.

**Comment by serundeputy** [comment]
`system_date_format_load($type)['pattern'];` use of this is php 5.4 or greater.
travis is using php 5.3 ; so you'll have to refactor this to use a temporary variable.
http://php.net/manual/en/language.types.array.php#example-102

hope that helps.
~Geoff

**Comment by Graham-72** [comment]
>>hope that helps

Thanks @serundeputy it certainly does.
I am modifying all such occurrences in date with commit https://github.com/Graham-72/backdrop/commit/26ef55557c655be141e0bf210b124f000651c664

**Comment by Graham-72** [comment]
Travis is now happy about this!

**Comment by Graham-72** [comment]
Mainly solved by commit https://github.com/Graham-72/backdrop/commit/26ef55557c655be141e0bf210b124f000651c664
then finally solved in Issue #1069
