### ISSUE TITLE
Date module test producing error report

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1065]
Ref. https://github.com/backdrop/backdrop-issues/issues/1063
Travis reports PHP Fatal error:  Class 'DateFieldBasic' not found in /home/travis/build/backdrop/backdrop/core/modules/date/tests/date_validation.test on line 6

**Comment by Graham-72** [comment]
Suggestions anyone please? I have got 'DateFieldBasic' => 'tests/date_field.test' in date_autoload_info() of date.module. Perhaps I should try it in date_api_autoload_info() instead?

**Comment by serundeputy** [comment]
Hi @Graham-72 ;

I think you should put 
```php
[DateFieldBasic]
name = Date Field Basic
description = Test basic date fields.
group = Date
file = date_field.test
```

into `date.tests.info`

here is a PR; if you merge this with your branch and then push it should re-queue the travis testing.

**Comment by Graham-72** [comment]
Thanks @serundeputy I have merged your PR.

A simple mistake by me! Shows how useful an extra pair of eyes can be.

But Travis is still very unhappy.

**Comment by docwilmot** [comment]
@Graham-72 can you add:
`require_once BACKDROP_ROOT . '/core/modules/date/tests/date_field.test';`
to the top of the following test files: 
- date_views_popup.test
- date.test
- date_timezone.test
- date_validation.test 

This should cause `DateFieldBasic` class to be included. 
And remove the `DateFieldBasic` class from `date.tests.info`. Apparently you can't use that to include abstract classes.

**Comment by Graham-72** [comment]
@docwilmot Thanks. Commit https://github.com/Graham-72/backdrop/commit/107ac78cac5e7351471ca21ac5a73a7e57ab3b31 has done this and DateFieldBasic is now included.
