### ISSUE TITLE
Date module - incorrect default date with pop-up widget.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1067]
Ref #1063 

When creating content and using the pop-up widget for a date field we get incorrect defaults appearing. It needs changing in date_popup.module.
(Image below includes some relevant line numbers in code, 420 and 523, for debugging purposes.)

![createstorydatepopuperror](https://cloud.githubusercontent.com/assets/10559274/8868234/5b90c392-31cd-11e5-92d2-8f6f69bea267.png)

**Comment by klonos** [comment]
The issue with the date and time fields both showing both date and time?

**Comment by Graham-72** [comment]
Yes, exactly that, and it causes a test to fail. I am working on producing a PR and have just been checking the Drupal module issue queue - a bit frightening because there is a lot there.

**Comment by Graham-72** [comment]
This was caused by the error in code in date_api.module relating to issue #1064, and was resolved by commit https://github.com/Graham-72/backdrop/commit/19b13cfa0998e5ec23e9dd1d5332048910747614.
