### ISSUE TITLE
Date module - attempt to edit field causes error

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1074]
Ref #1063 
Attempting to use 'EDIT' for a date field in the 'manage fields' column of the admin table of fields for a content type (see screenshot) produces an error report 'Theme hook "" not found.' 
This happens for widget types 'pop up calendar' and 'text field' but not 'select list'.

![annotate your screenshot 2015-07-30 20-29-38](https://cloud.githubusercontent.com/assets/10559274/8993139/e952d29c-36fa-11e5-9adf-e5272f12867c.png)

I am thinking the problem might lie around line 425 of date_admin.inc where we have this piece of code
``
$form['advanced']['text_parts'] = array(
  '#theme' => $widget['type'] == 'date_select' ? 'date_text_parts' : '',
);
``

**Comment by Graham-72** [comment]
I am not finding this problem when testing with a clean build today. However, I will not close the issue for the time being just in case it reappears.

**Comment by quicksketch** [comment]
I've been testing this PR for a few weeks now and in my work to consolidate all the different Date modules I have not run into this problem. Let's mark this fix.
