### ISSUE TITLE
Layouts: block (admin) title shown instead of block (viewable) title

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1078]
When configuring a block via a layout, the wrong title field is shown.

**Comment by Dinornis** [comment]
This has either been fixed or I do not understand the issue you describe.
When I try to replicate this in 1.5 the titles/labels are shown as I would expect.
The Admin label is shown in administrative interfaces and not shown to end-users. Managing blocks in layout is administrative task.

**Comment by jenlampton** [comment]
I think this has been fixed since the issue was opened. I remember the problem but am also unable to reproduce today. Thanks for checking on it :)
