### ISSUE TITLE
Backport: New HTML5 FAPI element: email

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#108]
We add the new HTML5 email element to system.module.

This patch can be backported directly from Drupal 8:

Drupal.org issue: http://drupal.org/node/1174620
Commit: http://drupalcode.org/project/drupal.git/commitdiff/2cc2aa2

**Comment by quicksketch** [comment]
Coming from https://github.com/backdrop-ops/api.backdropcms.org/issues/9, we don't have a change record yet for this set of changes. @juanolalla pointed out:

> Porting Email module, I found a fatal error due to the use of this function that no longer exist in form.inc. I didn't know the reason, and I used the Change Record search to locate it, but there weren't results for "element_validate_integer_positive".

> @quicksketch explained me later in IRC that it was replaced by https://api.backdropcms.org/api/backdrop/core!includes!form.inc/function/form_validate_number/1, and that I had to use $element = array('#type' => 'number', '#min' => 0, '#step' => 1) to validate it.

> I think we should add this info to the Change Records to allow developers finding easily the solution to this problem.

**Comment by docwilmot** [comment]
Was this an error? I cant see where element_validate_integer_positive() has anything to do with the new email element?

**Comment by quicksketch** [comment]
Sorry you're right @docwilmot, it should be https://github.com/backdrop/backdrop-issues/issues/230 that needs the change notice for the HTML5 number field.
