### ISSUE TITLE
Password strength description and indicator bar should convey their quality/strength by color.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1083]
Here's what we currently have for "poor" strength:

![backdrop-password_strength_poor_but_color_green](https://cloud.githubusercontent.com/assets/2423362/9035092/2195f18c-3a18-11e5-861e-fcd28ff341db.png)

Why is the indicator bar green in this case?

Here's what I'd like to see instead for the various strength levels:

![backdrop-password_strength_poor_red_color](https://cloud.githubusercontent.com/assets/2423362/9035120/52d3a820-3a18-11e5-8479-9a2243eedf07.png)
![backdrop-password_strength_fair_orange_color](https://cloud.githubusercontent.com/assets/2423362/9035124/5832314c-3a18-11e5-8144-267afb39dab3.png)
![backdrop-password_strength_good_green_color](https://cloud.githubusercontent.com/assets/2423362/9035129/609691b6-3a18-11e5-8848-8b7b585b7da5.png)
![backdrop-password_strength_excellent_green_color](https://cloud.githubusercontent.com/assets/2423362/9035131/6721d7b6-3a18-11e5-8772-4309a3f0ea63.png)

**Comment by klonos** [comment]
...notice in the last screenshot how the "no" for non-matching passwords has a very subtle brown color? Perhaps red is more suited here in order to draw the user attention?

**Comment by quicksketch** [comment]
I'd be down for these changes. D8 ultimately colourized their strength indicator as well. I think we already have all the classes in place to handle this already, this may just be a CSS change. Let's bundle together changing the "Passwords match: no" indicator to a brighter red in this issue as well.

**Comment by quicksketch** [comment]
I closed the PR at https://github.com/backdrop/backdrop/pull/1013 as it went a little too far in JS changes that shouldn't be needed. However it provided a great starting point. I'll file a replacement PR shortly to address this.

**Comment by quicksketch** [comment]
Gif of the changes in the new PR: https://github.com/backdrop/backdrop/pull/1041

![2015-09-11 21 27 04 972](https://cloud.githubusercontent.com/assets/100206/9829680/1ae94f14-58cc-11e5-88ee-e07cb9acd803.gif)

**Comment by quicksketch** [comment]
Sorry for the low quality GIF, the format really hurts the quality of text.

I merged in the PR. This will be in the 1.2.0 release.

**Comment by klonos** [comment]
Looks great! Thanx Nate.

**Comment by docwilmot** [comment]
Very nice!
