### ISSUE TITLE
PHP APC or APCu extension?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1084]
In some WAMPs [PECL :: Package :: APC](https://pecl.php.net/package/APC) is being replaced by [PECL :: Package :: APCu](https://pecl.php.net/package/APCu). From what I could gather from googling around, I found these references:

> APCu is the userdata component of the old APC, without the bytecode caching, because OpCache is now the standard bytecode caching for PHP, but doesn't provide userdata caching.

...and:

> - APC is opcode cache and data store
> - APCu is only data store
> - OPcache is only opcode cache
> 
> Since APC is older, at the moment you likely want OPcache as well as some data store, not necessarily APCu (although it is perfectly fine choice).

My question is where/how is that used in Backdrop and would APCu suffice in order to not throw this warning in the site status page:

![backdrop-site_status_page-apcu_instead_of_apc](https://cloud.githubusercontent.com/assets/2423362/9035478/8a7b36be-3a1b-11e5-94b5-10f12d132cca.png)

**Comment by quicksketch** [comment]
It appears that APCu works exactly the same as APC did in regards to file uploads. The settings are all named identically, as per https://github.com/krakjoe/apcu/pull/14. APCu is indeed still required to 

From the name of the source code, it also looks like the "official" name of the extension is still `apc`, so our check for `extension_loaded('apc')` should still work as well.

However, it looks like in PHP 5.4, PHP has native upload progress checking: https://www.drupal.org/node/1561866. We might be able to leverage this to prevent confusion for users running newer versions of PHP. On the other hand, I believe that installing upload progress or APCu still would work on newer installs. It appears the the built-in PHP handling is dependent upon starting a user session (which would disable caching in Backdrop), so there may still be reasons to encourage use of uploadprogress.

**Comment by klonos** [comment]
The above screenshot is from php 5.5 that of course includes the native upload progress checking, so there shouldn't be that warning in the first place. Right?

Perhaps implementing #719 would render this issue moot.

**Comment by quicksketch** [comment]
Ah, yes, thanks I hadn't realized we'd opened an issue for that already. Yes if https://github.com/backdrop/backdrop-issues/issues/719 is implemented, this issue would become moot, because we'd almost certainly just recommend enabling the built-in PHP upload progress.

**Comment by klonos** [comment]
> It appears the the built-in PHP handling is dependent upon starting a user session (which would disable caching in Backdrop), so there may still be reasons to encourage use of uploadprogress.

Just saw that. So should we in this case (php 5.4 or greater detected and no uploadprogress) suggest that if the uploadprogress php extension is installed and enabled, then there'd be some gain (performance or otherwise)?

**Comment by quicksketch** [comment]
Actually, now that I think about it, this could be okay if the session is
short-lived. We use sessions every time we us backdrop_set_message() for
anonymous users (which is common especially after submitting a form). So
ultimately, if you have a newer version of PHP, the built-in handling
should be sufficient. Unless we come up with some proven reason, I think
the default handling should be adequate.

**Comment by klonos** [comment]
I think that with #3211 implemented, we can close this.
