### ISSUE TITLE
[UX] be more descriptive about the "Roles" section in the text format config page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1086]
![backdrop-text_format_config-roles_what](https://cloud.githubusercontent.com/assets/2423362/9046696/dc72214a-3a6f-11e5-8d50-bc1bda1f185c.png)

I noticed this while reviewing @docwilmot's work in #1032. Sure, for all of us long-time users of Drupal this makes perfect sense, but we could at the very least use some help text here. Something along the lines of "Roles this text format is available to."

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1903 ("Roles allowed to use this text format")

**Comment by quicksketch** [comment]
I'm not sure. At least the description text suggested just restates the combination of the page title and the field label.

I tried to come up with something more additive, like "`Assign permission to use this format. Filter permissions may also be set from the <a href="!url">permissions page</a>`". But then I realized we wouldn't want to send the user off to the unwieldy permissions page right in the middle of a task to add a text format.

Overall, I think we're better off without a description here.

**Comment by jenlampton** [comment]
I agree that "Roles" as a label doesn't really help here. Yes, these are roles. Why do I need to choose one?

How about "Format will be available for the following roles:"

**Comment by sutibun** [comment]
Nitpicky just because I like questions better

"What following roles should this format be available to?"

**Comment by klonos** [comment]
Would it make more sense in general if we renamed "Roles" to "User groups" instead? ...just a thought.

**Comment by sutibun** [comment]
Linux comes to mind when I hear User groups. Let's see.

- "Format will be available for the following **roles**"
- "Format will be available for the following **group of users**"

It could work. Not sure if it's significantly better. Of course, I can't think of anything better at the top of my head

**Comment by Graham-72** [comment]
I am happy with roles. Sometimes I'm a web user, sometimes a web developer, sometimes admin. These are different roles.

I just had a look at groups on drupal.org and found this
> A Drupal user group for everyone in Gujarat & those organisers who want to invite this region to their events.

Not quite the same thing really.

**Comment by jenlampton** [comment]
Er, renaming user roles is getting a bit off topic :)

> Format will be available for the following roles

I like this, but I would like "Roles" to be the first word on the left, for those of us who don't like to read. Is there a way to make a sensible statement that starts with Roles and doesn't end with a preposition?

**Comment by Graham-72** [comment]
"Roles able to use this text format" ?

**Comment by klonos** [comment]
> I would like "Roles" to be the first word on the left, for those of us who don't like to read.

:+1:  but I'm thinking "allowed" instead of "able". So??:

"Roles allowed to use this text format:"

**Comment by Dinornis** [comment]
👍 for "Roles allowed to use this text format:"

**Comment by klonos** [comment]
...lets close another one of the oldies then 😄: https://github.com/backdrop/backdrop/pull/1903

![image](https://cloud.githubusercontent.com/assets/2423362/26271107/eae6b360-3d44-11e7-9f24-faca998739ec.png)

**Comment by klonos** [comment]
...pinging @quicksketch / @serundeputy for a PR when you get a chance 😉

**Comment by quicksketch** [comment]
Ding ding, I think we have a winner. Great idea just to update the label for the checkboxes rather than add a description. This looks great to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1903 into 1.x and 1.7.x. Thanks @Graham-72, @Dinornis, and @klonos!

**Comment by klonos** [comment]
Hey, assigning people to issues works! 😄 Thank you Nate 👍
