### ISSUE TITLE
Ship with a text format that includes a text editor.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1091]
Follow-up issue for #101...

We currently ship with the _Filtered HTML_, _Full HTML_ and _Plain text_ text formats but none of them includes a text editor. Should we ship an additional text format that includes one or should we update the _Filtered HTML_ and _Full HTML_ ones to have CKEditor enabled?

**Comment by MrHaroldA** [comment]
> update the Filtered HTML and Full HTML ones to have CKEditor enabled

That has my vote. Installing 5 text formats by default is way too much.

**Comment by klonos** [comment]
I didn't want the issue summary to be biased, but updating the existing formats is my preference too,

**Comment by quicksketch** [comment]
I also agree we should enable on the existing formats by default, or replace the existing ones with new ones. I added this to the meta at https://github.com/backdrop/backdrop-issues/issues/1087.

I believe @jenlampton has a preference on NOT enabling CKEditor on the Full HTML format. I would probably prefer to enable it on both out-of-box formats, as long as CKEditor doesn't mangle HTML pasted in as source-code, which may be tricky. I believe it will *always* strip `<script>` tags, preventing the Full HTML format from being used for things like ad-code.

**Comment by quicksketch** [comment]
Upon checking things, it appears we already have CKEditor enabled on the "Filtered HTML" format out of the box. So the basic request here is already "done" in that this is the default format for all users. So the question remains, should we enable it for Full HTML or rename the existing default formats?

**Comment by MrHaroldA** [comment]
What about renaming "Full HTML" to "Raw HTML"?

In our company, Full HTML is only avalable to the root user, and customers don't get access to that.

**Comment by Graham-72** [comment]
I would like to have two levels offering use of CKEditor to my clients e.g. 'WYSIWYG' (ex filtered HTML) and 'WYSIWYG plus' (ex Full HTML), the latter being for someone with a bit of extra training as a site administrator, and having a fuller set of editing icons. If the latter will allow me to use full HTML (i.e. Raw HTML) then that would be great. 

I have a slight preference for avoiding using technical terms like HTML or CKEditor in the names.

**Comment by docwilmot** [comment]
> rename the existing default formats?

I think as @Graham-72 says, now is a chance to make our terminology a bit more user friendly. Since there is now a core editor, users will not be directly exposed to the input format concept anymore, but just the editor. So how about 
- Simple editor
- Advanced editor
- No editor

On the primary question of whether we should enable it or not for Full HTML, I'd say yes.

**Comment by klonos** [comment]
Yes from me too on enabling the "rich" text editor on Full HTML. :+1: 

> I have a slight preference for avoiding using technical terms like HTML or CKEditor in the names.

Then "WYSIWYG" and "WYSIWYG plus" would be out of the question too I guess since that counts as "techy" lingo. Right?

Anyways, I believe that users are already familiar with the terms "plain text" and "HTML" from configuring the default compose/reply format in their mail clients. I personally use Thunderbird that has a simple "Compose messages in HTML format" checkbox setting + a few more options for sending:

![tb_compose_html_plain_text_options](https://cloud.githubusercontent.com/assets/2423362/9287402/236e799c-4356-11e5-9a8d-0c634769766e.png)

Now, Thunderbird seems to hold ~1% of [the market share](https://www.campaignmonitor.com/resources/will-it-work/email-clients), so might not be a great example but Outlook that has a good 20%+ also has similar settings using the same terms more or less:

![outlook_compose_html_plain_text_options](https://cloud.githubusercontent.com/assets/2423362/9287423/c5f50d56-4357-11e5-9e5b-41a65e289ca8.png)

Anyone with an iOS device to check for the 35%+ market share they hold should shed some light about it here.

So I think we should go with something like "plain text" (no WYSIWYG), "rich text" (simple things like bold/italics/underlined, text align, image, link etc) and "HTML" or "Full HTML" (basically everything).

**Comment by Graham-72** [comment]
I accept the points against using WYSIWYG but I am still a bit unhappy using HTML, particularly with the comparison with email.

If the average email user has any appreciation of the significance of the HTML setting, they will know that it allows fonts and images to appear, and in my experience 'rich text' in Outlook is something to be avoided because of incompatibility with other mail clients. 

On balance, I am now thinking that @docwilmot 's suggestion of 'simple' and 'advanced' might be the way to go. After all, both produce HTML, one allows a fuller repertoire.

**Comment by docwilmot** [comment]
> from configuring the default compose/reply format in their mail clients.

Seriously, @klonos? The average user has been there? :smile:

**Comment by klonos** [comment]
@docwilmot I seriously wouldn't know. I know I tinker *a lot* with almost every setting, but you are probably right that the average user might never mess with any settings at all.

**Comment by jenlampton** [comment]
If what is wanted is another editing option with "more icons" that is a completely different thing than another input format, which is a different set of filters, and will have content-entry and permission implications (possibly leading to a UX nightmare if we try to include that out of the box).

Adding "more icons" can be handled by modifying the single ckeditor configuration, just put all the extra icons into the drawer that's usually hidden, and leave it on the same format.

I'm going to propose a completely different approach: Since most people won't thoroughly understand input formats anyway, let's remove Full HTML from the default install. 

If you do have a use-case where you have high level admins who both understand HTML code and understand the security implications of disabling content filtering, then sure, but add that Full HTML format yourself. It is the easiest one to add afterall - since it needs no filters :)

**Comment by quicksketch** [comment]
> Adding "more icons" can be handled by modifying the single ckeditor configuration, just put all the extra icons into the drawer that's usually hidden, and leave it on the same format.

If we want to mimic WordPress this would be a good option. They have a "Kitchen Sink" plugin that just hides additional rows of buttons after the first one. This would be a neat plugin to add and entirely possible. If the Kitchen Sink plugin existed in the toolbar, it would just hide all subsequent rows after the one it is currently in.

> Since most people won't thoroughly understand input formats anyway, let's remove Full HTML from the default install. 

I actually like this idea as well. The option to select a format is baffling not only to anonymous users leaving a comment when they have to choose between "Plain text" and "Filtered HTML" (Jen is suggesting we remove that option as well in https://github.com/backdrop/backdrop-issues/issues/1186), but also to many first-time (or even experienced) users who have no idea what the difference is between any of the available formats. If we only shipped with configured one format, and plain text was hidden from the dropdown and only used as a true fallback, then most new users wouldn't see the text format selector at all (a good thing IMO).

**Comment by klonos** [comment]
Sounds reasonable. ...but if we are to remove a feature that some (even if a minority) expected to find available when moving from D7 to Backdrop, then that would result in bad UX.

I was thinking that perhaps it would be better if the text formats had an enabled/disabled status (same as views). This way:

- instead of removing the HTML format entirely, we simply disable it for the standard profile
- instead of having those users that need it re-create it from scratch, we provide a single-click solution to get it back.

**Comment by jenlampton** [comment]
The idea of enabled / disabled formats already exists, (since you cannot delete a format) so this is possible. But the amount of work required to add  a Full HTML format is so small (since it requires only a name, and no config) I'm not sure I see the point. One click vs two.

**Comment by klonos** [comment]
> I'm not sure I see the point. One click vs two.

It's not only one click. ...you have to also go to the admin UI in the text formats page in order to enable/setup one with a rich text editor. The point is to have one enabled by default and users don't have to go through the admin UI.

**Comment by jenlampton** [comment]
If we ship with only a single text format, that one would have a rich text editor on it. It would only be necessary to go to the Admin UI and mess with text formats if what you want is something else (enter HTML code, etc).

**Comment by mikemccaffrey** [comment]
+1 for having CKEditor enabled by default for the non-plain text formats 

+1 for only having only one text format enabled by default, but keeping the other two present and disabled

Since the CKEditor is already enabled by default for Filtered HTML, it seems like the original purpose of this issue has been fulfilled. Should we perhaps rename the issue, or close it and create a separate issue to explicitly discuss what text formats should be created and enabled by default?

**Comment by jenlampton** [comment]
> Should we perhaps rename the issue, or close it and create a separate issue to explicitly discuss what text formats should be created and enabled by default?

Yes, I think that sounds like a good idea. I'm sort-of loosing track of where we are on this issue anyway. Here's what I think we've decided:

1) Remove the FULL HTML format from the Standard install profile (thus affecting only new installs of Backdrop). See https://github.com/backdrop/backdrop-issues/issues/1519
2) Add a hidden "kitchen sink" of buttons to the Filtered HTML input format https://github.com/backdrop/backdrop-issues/issues/1520

If I've missed anything important from this issue, please create at will!

**Comment by klonos** [comment]
Sorry guys (and gals), but my time is very limited and it takes me long to chime in on issues/replies. You people have been doing things without me and I feel left out, but I know it's not your fault :smile: .

Anyways, reopening just to clarify what the intention was when I first filed this issue here: currently there is a "CKEditor is installed but not enabled on any formats." warning in the site status report. I would like this to go away in general, but at the very least it should not be there for new installations. In other words, I'd like us to have it so that there are less things to do in a fresh installation in order for people to have a "green" site status out of the box.

**Comment by klonos** [comment]
...if you insist to close this issue here because it got long, just let me know and I'll file a separate one.

**Comment by Graham-72** [comment]
I am confused now by what we have achieved. Under 'Formatting Options' I now only have 'Full HTML' and 'Filtered HTML'. What has happened to 'Plain Text' which as Admin I would expect to see? I would expect to be able to choose to modify source code without CKEditor intervening. Have I missed something, or a setting somewhere?

**Comment by klonos** [comment]
...I think that you may have spotted a bug (or a UX WTF if this was intentional). You see, the plain text format is a "Fallback format. Used if a role has access to no other formats." and also in its settings you see that "All roles for this text format must be enabled and cannot be changed."


The WTF here is that for added UX we enable a rich text editor when possible, but we do not account for the cases where a user *intentionally* wants to switch to plain text (instead of as a fallback *only*).

**Comment by gifad** [comment]
If you want to see / work on source code, just enable the "Source" button...
And install the CKEditor "Code Mirror" plugin, to have it syntax checked and coloured !

**Comment by Graham-72** [comment]
Yes, and I do use the source button, but I find I need to disable some filters to stop them modifying the HTML, so that is why I have added another (third) formatting option that I have called CKEditorUF. I am sure there is a better name.

**Comment by Dinornis** [comment]
I suggest to focus on making the defaults as simple as possible for new users. The flexibility of the core input format systems combined with the [Better Formats module](https://github.com/backdrop-contrib/better_formats) addresses most if not all of the other needs mentioned in this thread.

**Comment by klonos** [comment]
Lets recap what has been discussed here so to decide whether there is anything actionable in this issue here....

1. This issue was initially filed in order to add a rich text editor in at least one of the 3 text formats shipped with core. We now ship with CKEditor enabled for the *Filtered HTML* format (after 1.3.0 I believe), *but only in new installations*. People upgrading from older versions of Backdrop will still get an annoying warning in their status report to tell them that they have not assigned a text editor to any of their text formats. I think that this is a non-issue because most people that installed 1.3.0 will by now have enabled a text editor for at least one of their formats (assumption, yes, but a safe one I recon). So, is it worth to still worry about any of these things?

2. Reduce the text formats to 2 by removing the "Full HTML" text format (on new installations). I have started coming around to the idea that this is a good move.

3. Allow text formats to be enabled/disabled instead of removed. This is already implemented, we could disable the "Full HTML" text format in new installations instead of removing it (for point 2 above).

4. Rename the text formats that we ship with out of the box to not include terms like "HTML" in their name/label. I agree that we should do this. Especially if we reduce to 2 formats. Our "Plain text" format has "Convert URLs into links", which contradicts the filter name.

Any other things I've missed?

**Comment by klonos** [comment]
...worth noting that D8 has actually *added* a 4th text format:

![image](https://user-images.githubusercontent.com/2423362/27252590-96c6b77c-53a5-11e7-88d9-0355a2ec2abb.png)

**Comment by olafgrabienski** [comment]
> 3. Allow text formats to be enabled/disabled instead of removed. This is already implemented, we could disable the "Full HTML" text format in new installations instead of removing it

@klonos We shouldn't disable "Full HTML" in new installations at the moment because disabled formats can't be re-enabled, see issue [[UX] Text editors and formats: Allow re-enabling disabled formats](https://github.com/backdrop/backdrop-issues/issues/1575).

**Comment by jenlampton** [comment]
Right, what we really want to do never create it in the first place. We don't need it by default, and if people want to allow an insecure text format, it's easy to add that one like that since no filters are enabled. The only one we need at install time is "Filtered".

**Comment by olafgrabienski** [comment]
> it's easy to add [a Full HTML format] since no filters are enabled

Actually, there are a few enabled filters in Full HTML: *Convert URLs into links*, *Convert line breaks into HTML*, *Correct faulty and chopped off HTML*, and some image related ones. In my opinion, an already enabled *Correct faulty and chopped off HTML* filter is a pro Full HTML argument. Providing the format in core, we can guarantee that it is at least configured in a reasonable way by default. (I agree however to disable the format on new installations.)

**Comment by klonos** [comment]
As I explained, I personally do not feel strongly about whether we disable, keep as is or remove the "Full HTML" format altogether. There are pros and cons with every option. I have to say though that a) I find "Restricted HTML" (what D8 uses) less ambiguous than "Filtered HTML" and b) if we disable the filter, it would get it out of the way while at the same time allowing people to get it back with minimal effort.

**Comment by olafgrabienski** [comment]
> I find "Restricted HTML" (what D8 uses) less ambiguous than "Filtered HTML"

Right! I guess the equivalent of "Filtered HTML" in Drupal 8 isn't "Restricted" but "Basic HTML", but that's also an interesting option, reminds me on @docwilmot's suggestion "Simple" vs. "Advanced".

**Comment by jenlampton** [comment]
> Actually, there are a few enabled filters in Full HTML

Yes, and that is another bug. If you are typing in the HTML that you want your page to render, you certainly *don't* want your line breaks converted into P tags. I find this super frustrating as I like to type my HTML neatly, with indentation and line breaks so other people can read it. Being forced to turn it into one suuuuuuuuper ling line just to get it not to add extra P tags is a huge pain. I also hate it when I'm trying to embed a youtube video and the URL in the video embed is code is converted to a link. :( so many UX fails here...

Hey @klonos can we please create a new issue with a new title for whatever this is hoping to achieve? We already include a text-editor out of the box, so this issue should be closed.

**Comment by olafgrabienski** [comment]
> Actually, there are a few enabled filters in Full HTML
> 
> Yes, and that is another bug. If you are typing in the HTML that you want your page to render, you certainly don't want your line breaks converted into P tags (...)

I understand the frustration about unwanted tags but *some* filter may be useful, for instance *Correct faulty and chopped off HTML*. I can test and report if you want in an (upcoming?) issue to not provide the Full HTML format anymore.

That said, I'd suggest also to close *this* issue and open new ones if wanted.

**Comment by jenlampton** [comment]
I agree. I think we already have an issue for some of these. Let's close
this one and tag some of the others for upcoming releases.
