### ISSUE TITLE
Why is the "Plain text" text format shown with italics in the text formats list?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1092]
![plain_text_filter-italics](https://cloud.githubusercontent.com/assets/2423362/9080762/3f3b0276-3b9a-11e5-9937-132fc2c241db.png)

**Comment by jenlampton** [comment]
Because it's the default format (meaning all roles can use it).  I'm not sure why italics were chosen to indicate this.  Are you recommending we remove them?  I'd be okay with that.

**Comment by quicksketch** [comment]
If https://github.com/backdrop/backdrop-issues/issues/1186 is completed and Plain Text is hidden from the select list, the message should be updated to something more like:

> Fallback format. Used if a role has access to no other formats.

I also agree that the emphasis tag seems inappropriate. It's clear enough that we don't have a role called "All roles may use this format".

**Comment by jenlampton** [comment]
Okay, I'm removing the italics (backdrop_placeholder) and updating the text to  `Fallback format. Used if a role has access to no other formats.` over in https://github.com/backdrop/backdrop-issues/issues/1186.  

Closing this issue.
