### ISSUE TITLE
Update check error but update status ok.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1094]
Related to #664, anything wrong with that picture?:

![backdrop-update_status_ok_but_update_check_error](https://cloud.githubusercontent.com/assets/2423362/9081563/b915c49a-3ba0-11e5-8195-8d08fa031883.png)

Either the status needs to be green/ok and the update check problem play the role of some sort of note (we could have something like "last checked" there), or the update status needs to be something like "unknown" or "N/A".

**Comment by Dinornis** [comment]
I believe this does not apply anymore.  Closing as outdated.
