### ISSUE TITLE
Date module - incorrect date display

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1097]
Ref #1063
Using field display of type HTML date-time shows time difference twice.
![test page - localhost 2015-08-09 07-28-46](https://cloud.githubusercontent.com/assets/10559274/9153827/5c7c1862-3e69-11e5-9a86-eda28e5bfaca.png)

**Comment by Graham-72** [comment]
I have fixed this in date.theme by checking for use of html_datetime format (Y-m-d\TH:iO) and, if found, suppressing the addition of the separate timezone field.
Commit https://github.com/backdrop/backdrop/commit/d7397c9df5e5b9a53ace2ffc581dddf1d0f61a22

**Comment by quicksketch** [comment]
:+1: Confirmed this is no longer an issue.
