### ISSUE TITLE
Date module - date popup jQuery wvega option

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1098]
Ref #1063 
The contributed Date Module provides for the installation of an alternative jQuery timepicker 'wvega' which would be installed as a library.

Do we need this option if Date is in Core where we already have a jQuery timepicker? Is there any advantage to be gained from the wvega library?

**Comment by quicksketch** [comment]
I think that the jQuery UI plugin only does date picking? The wvega library is for time picking. So is there an overlap here?

**Comment by Graham-72** [comment]
Thanks @quicksketch for the clarification of my misunderstanding resulting from not yet seeing wvega working properly in my contrib module date_basic, so I need to investigate this. Is having a timepicker a desirable feature for date fields in core?

**Comment by Graham-72** [comment]
With https://github.com/Graham-72/backdrop/commit/da8d2a27322e034733466c4ce8bea824b11193ed I have removed the wvega timepicker option and attempted to fix the default timepicker.

I see no need to have the option to use the alternative timepicker and now think it is an unnecessary complication.

Unfortunately Travis has. failed the PR so I will find out what has now gone wrong

**Comment by Graham-72** [comment]
My mistake! I failed to include version number for Time Entry Library.
Trying to fix it with commit https://github.com/Graham-72/backdrop/commit/37aac529bf7c9c00b47745aa9711e8d95144f76a

**Comment by Graham-72** [comment]
Tests now pass. Default timepicker working. Wvega timepicker option removed, but it could be re-instated if needed.

**Comment by klonos** [comment]
Can you please take a look at my comments in the PR? Sorry I didn't have time to chime in earlier before you commit and close this issue.

**Comment by quicksketch** [comment]
@Graham-72 has fixed these issues. In my testing I also found that the 1.5.2 version was more compatible and required less integration. The links to the homepage have also been fixed in the current PRs. Great work on all this again @Graham-72!

I think this is the last of the meta at https://github.com/backdrop/backdrop-issues/issues/1063. All looks complete there to me.
