### ISSUE TITLE
[UX] Appearance page: Convert the multiple/separate "set default" links to a single drop-down select list and move it at the top of the page along with the admin theme selection section.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1104]
Instead of having all these "set default" links all over the place, we can simply have a single drop-down select list. This drop-down can be put in the same section with the admin theme (the section will need to be renamed to something like "Default and Administration themes").

...now that I think about it, the "Use the administration theme when editing or creating content" checkbox could also be converted to a drop-down select. The way it is currently, you can set the edit theme to either be the same as the front-end (checkbox not ticked) **or** same as admin theme (checkbox ticked). If we were to implement this, we'd allow users to select totally different front-end, admin **and** editing themes. Separate issue?

**Comment by jenlampton** [comment]
I think this could be tackled along with https://github.com/backdrop/backdrop-issues/issues/1103/ Closing as dupe.
