### ISSUE TITLE
[UX/TX] Provide a way to preview themes without enabling them or using them for something (default/admin/edit).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1106]
In #1104 I suggested that we also convert the "Use the administration theme when editing or creating content" checkbox to a totally separate setting (drop-down select) in order to provide an option for selecting a separate theme for editing content (other than the default or the admin theme).

What I would like to see implemented (somehow), is say a "preview" link next to the enable/disable links for each theme that will say point to a `http://my.site.com/admin/appearance/preview/[theme_name]` page showing how this theme looks in real life (as opposed to any outdated screenshot for example). Then, specific pages could be previewed using this theme say like this: `http://my.site.com/admin/appearance/preview/[theme_name]/node/1`

 What do you people think? Possible?

**Comment by klonos** [comment]
https://github.com/backdrop-contrib/styleguide in core perhaps?

**Comment by docwilmot** [comment]
Nice UX idea, but not sure about styleguide in core though. I mean if youre picking a theme still, youre probably still developing; why not just click 'enable and set default'? Its still one click! And you get to browse your whole site to see how it looks, not just one page. 
Im thinking maybe a preview system on  Backdrop.org may be more useful; that way you could have a couple pages designed for previewing,

**Comment by klonos** [comment]
> ...not sure about styleguide in core though.

This one in order to save theme developers the time/trouble of downloading and enabling a contrib module.

> ... why not just click 'enable and set default'? Its still one click! And you get to browse your whole site to see how it looks, not just one page.

Never thought of this that way. I filed this for use cases where people are re-designing their website or went online with one of the themes shipped with core and now want to upgrade to something new. If they use the 'enable and set default', they'd switch the site to the new theme for *everyone* before they've had the chance to test things and see if it works - not good.

> Im thinking maybe a preview system on Backdrop.org may be more useful...

Yes good idea, but if the whole preview feature was in core, then we could perhaps use that in order to provide the previews.

**Comment by klonos** [comment]
...we are adding an awesome preview system in #3186 that will allow people to browser their site with a specific theme selected.

Closing this issue.
