### ISSUE TITLE
[UX] Properly identify to the user whether they've gotten their username or password incorrect when logging in

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#111]
Problem/Motivation

When users are logging in and fail validation, they become frustrated in thinking they are getting their password incorrect when it's actually their user name. (Most commonly: they have tried to log in with thier e-mail address instead of their username, but see this issue for more on that.

Proposed resolution

Properly validate each field. If the username is incorrect, state that. Likewise, If the password is incorrect, state that.

Here are some validation functions that need to be checked
user_login_name_validate
user_login_authenticate_validate
user_login_final_validate

Related issue on d.o: https://drupal.org/node/2109299

**Comment by quicksketch** [comment]
This has been fixed in https://github.com/backdrop/backdrop/pull/940. Thanks @docwilmot!
