### ISSUE TITLE
Ignore vendor-specific directories when scanning for modules and templates

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1110]
This mirrors the Drupal issue at https://www.drupal.org/node/2329453.

Drupal recursively scans the front end vendor directories: node_modules and bower_components.

This causes a noticeable and significantly slower response time when front end developers do common tasks such as clearing the cache (#59) or when rebuilding the theme registry: drupal_find_theme_templates():

    drush cc all with node_modules in Drupal theme's root folder: 45 secs
    drush cc all without node_modules: 10 secs 

These front end developer tools are very common and highly used (even outside of Drupal).
NPM Stats (https://www.npmjs.com):

175,409 total packages
29,619,131 downloads in the last day
490,004,267 downloads in the last week
1,939,777,453 downloads in the last month
Bower Stats via NPM (https://www.npmjs.com/package/bower):

23,318 downloads in the last day
360,264 downloads in the last week
1,474,986 downloads in the last month
38,599 packages (http://bower.io/stats/)
Grunt Stats (https://www.npmjs.com/package/grunt)

19,102 downloads in the last day
318,143 downloads in the last week
1,290,279 downloads in the last month

All these tools are NodeJS oriented and use the node_modules folder, with the addition of the bower_components folder for Bower.

Due to the combined and shared nature of the node_modules folder, the average size of node_modules is roughly ~5,000-10,000 files. This can, on occasion, easily skyrocket to upwards of ~30,000-50,000 files depending on the size of the project and the node modules used.

Suffice it to say, this isn't some "small deal" Drupal can afford to simply ignore.

*Can't people just use a different directory other than node_modules?*
No. Node has already made it quite clear that they will never let this happen. Also, this would still be considered a "Drupalism" because front end developers new to Drupal wouldn't know about this issue.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/1021. This could be a nice performance improvement for users whose workflows include the use of npm, or really large themes that contain a lot of assets.

I also filed a matching patch for Drupal 7 over at https://www.drupal.org/node/2329453#comment-10247651. As this is likely to get some feedback in the Drupal queue, I'd like to see what response this patch has over there before merging it over here.

**Comment by jenlampton** [comment]
@quicksketch I'm wondering if you saw @markcarver's comment over at https://www.drupal.org/node/2329453#comment-10248909.

**Comment by quicksketch** [comment]
> I'm wondering if you saw @markcarver's comment

Yep. Doing both approaches wouldn't hurt. I've updated the PR to reflect the latest approach and added scss to the list of directories to be skipped.

**Comment by quicksketch** [comment]
I've merged the latest approach. We can improve upon it further if needed. I just ran across that Drupal issue while solving #1109 (files starting with a dot are ignored by file_scan_directory()). Now we have something both faster (this issue) and versatile (#1109).

**Comment by markcarver** [comment]
> added scss to the list of directories to be skipped

Oh, good idea. I would say that `less` should be added too just FYI

**Comment by quicksketch** [comment]
>  I would say that less should be added too just FYI

Thanks, I added this as well, after I realized that adding `config` had broken our scripted installs because the /core/modules/config/config.module file could not be found. :stuck_out_tongue: See 91a6eaef4821a4928ad1a1edaa1eac9c2f1d9fb4.
