### ISSUE TITLE
[UX] Remove leftover 'Preview' status from vertical tabs on content type form

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1111]
We removed the ability for nodes to have previews in Backdrop, but we didn't remove the vertical tab status for that old preview setting. See admin/structure/types/manage/article, for an example.
![screen shot 2015-08-22 at 12 17 20 am](https://cloud.githubusercontent.com/assets/397895/9422986/83f5b76e-4863-11e5-8499-56e7950d446b.png)

This 'Preview' text, and any javascript that was supposed to change it, should be removed from Backdrop.

**Comment by quicksketch** [comment]
Great, thanks @dboulet! Merged into 1.x and 1.2.x.
