### ISSUE TITLE
[UX] Promoted status in vertical tab does not match reality

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1112]
We updated the content type settings for Promoted and Sticky to be more intuitive and easier to get rid of, but we didn't update the javascript that updates the current 'status' shown in the vertical tab on the content type page. See admin/structure/types/manage/article, for an example.
![screen shot 2015-08-22 at 12 20 29 am](https://cloud.githubusercontent.com/assets/397895/9422998/e93f0ecc-4863-11e5-8680-a671346d826a.png)

Let's revisit the javascript that works in these vertical tabs and make sure it's accurate.

**Comment by Dinornis** [comment]
@jenlampton 
Looks like this issue has been fixed as of 1.5 and could be closed.

**Comment by jenlampton** [comment]
woot! :)
