### ISSUE TITLE
[UX] Disable display of author info & photo on basic pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1113]
Somehow the display of `author and date information` and `author picture ` ended up enabled on Basic pages when it's supposed to be disabled.  Let's correct this (by default) in the standard install profile.
![screen shot 2015-08-22 at 12 38 38 am](https://cloud.githubusercontent.com/assets/397895/9423041/2d40ecc8-4867-11e5-989c-015e8ca8bf71.png)

**Comment by quicksketch** [comment]
Sweet. Merged https://github.com/backdrop/backdrop/pull/1453 into 1.x and 1.4.x.
