### ISSUE TITLE
[UX] Integrate the Simple Password Reset module improvements into core

### ISSUE THREAD

**Issue by rszrama** [backdrop/backdrop-issues#1115]
I've seen on several projects how confusing the default password reset behavior in Drupal can be to new users. Fortunately, I discovered and helped fix up the Simple Password Reset module, and that (along with E-mail registration) is now a staple on every project I deliver. It reduces the number of page loads required to reset a password and removes a lot of cruft from the password reset form.

Not sure if you've had experience with the module, but if it seems reasonable to you, I'd be happy to patch Backdrop so the core password reset behavior matches this module's.

https://www.drupal.org/project/simple_pass_reset

**Comment by quicksketch** [comment]
I think we beat you to this one! Backdrop already implemented this in #140.

**Comment by rszrama** [comment]
Holy crap! I'm way late to the game. : )

Will close this out, then, and I can always review them for feature parity later. Nothing to see here...

**Comment by quicksketch** [comment]
:stuck_out_tongue_winking_eye:
