### ISSUE TITLE
[UX] Draggable fields appears broken

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1117]
We made the select lists prettier by adding a TON of whitespace inside all the boxes. However, we also use select element inside draggable tables.  The table rows now take up so much space vertically that elements from the top of the table cannot be dragged to the bottom of the table without scrolling.  

This means you need to pick up the elment you are trying to drag, take it half way, then put it down. Then scroll the page. Then pick it up again, and drag it the rest of the way.

I feel that this is a huge UX regression and I think we should decrease the amount of whitespace used in form elements - either site wide, or perhaps only in the admin theme, or perhaps only in draggable tables.

**Comment by jenlampton** [comment]
Here's a quick video I made demonstrating failure to drag fields: http://screencast.com/t/5ealufcD

**Comment by docwilmot** [comment]
I wouldnt say this is a problem with the form elements heights, but more a weakness of draggable rows which span more than screen height. The skinniest form elements would give the same issue if the table was taller than screen height. So making selects skinnier doesnt really solve this.

**Comment by jenlampton** [comment]
The bug is just made painfully obvious since we run into it right away (rather than not until we have a lot of fields)

**Comment by jenlampton** [comment]
Removing from 1.3.0 since we don't yet have a PR.

**Comment by BWPanda** [comment]
@jenlampton Is this still an issue? My browser scrolls down automatically when dragging fields towards the bottom of the window (tested by making my browser window really short)...

**Comment by jenlampton** [comment]
No, I think our more recent javascript updates fixed whatever was misbehaving. Works now for me too :)
