### ISSUE TITLE
[UX] Remove military time on default date formats

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1119]
One of the first things I do on every single Drupal / Backdrop site, is change the default date formats. Can we provide some intelligent defaults instead? Gripes follow
- Though military time is nice and nerdy, I don't think that's necessarily our majority use case. 
- Is the day of the week really necessary for the medium format?
- The short format should be shorter, kill the leading zeros and shorten year to 2 digits.

Current defaults:

```
long    Long Date           Tuesday, August 25, 2015 - 23:38    
medium  Medium Date         Tue, 08/25/2015 - 23:38 
short   Short Date          08/25/2015 - 23:38
```

Suggested defaults:

```
long    Long Date       Tuesday, August 25, 2015 - 11:50pm  
medium  Medium Date     Aug 25, 2015 - 11:50pm  
short   Short Date      8/25/15 - 11:50pm
```

**Comment by Graham-72** [comment]
I like this proposal.

But is there some way that we can link the short date format to the region? Because here in UK I would want it to be 25/8/15 as is our custom.

**Comment by MrHaroldA** [comment]
The proposed defaults also do not match any of the Dutch standards*, which are almost always d/m/Y. We also don't use a " - " separator, but rather a single space.

Localized defaults may be a good option, but that will be a long list.

*) Since the 90's we are bound to ISO8601, but nobody uses it.

**Comment by klonos** [comment]
> But is there some way that we can link the short date format to the region? Because here in UK I would want it to be 25/8/15 as is our custom.

:+1:

**Comment by sutibun** [comment]
Yes, please. Remove the military time.

Also, **would it be a good idea for Backdrop to do the leg work?** A lil' UX love. By which I mean:

When a user sets their time zone at 

http://www.example.com/admin/config/regional/settings

Backdrop will check what region they're at and select the best default format

- 25/8/15 for UK folks
- 08/25/2015 for US folks
- whatever other combos there are

It would not only make Backdrop more intelligent and but considerate. Less admin pain for builders.

Simply, it just works.

**Comment by docwilmot** [comment]
Can we add date format by country (https://en.wikipedia.org/wiki/Date_format_by_country) data to `standard.inc`?

**Comment by quicksketch** [comment]
> Can we add date format by country (https://en.wikipedia.org/wiki/Date_format_by_country) data to standard.inc?

Yes! I think this sounds like a great proposal. 

> Backdrop will check what region they're at and select the best default format automatically

I also think this a great idea for the installer and for the site settings. But how would this work for *individual users*? If user A  uses YYYY.MM.DD but user B uses MM/DD/YYYY, should this be accounted for based on their individual time zones? I'm not sure this is easily possible. Maybe we should just start with site-wide format and the automatic guessing based on timezone and work on per-user timezones later.

**Comment by jenlampton** [comment]
Since not all of this issue will be able to be completed by 1.3.0, I've created: Date formats by country: https://github.com/backdrop/backdrop-issues/issues/1521

**Comment by jenlampton** [comment]
PR now passing tests, ready for review: https://github.com/backdrop/backdrop/issues/1206

**Comment by quicksketch** [comment]
Super, thanks @jenlampton! Merged in https://github.com/backdrop/backdrop/pull/1206 into 1.x for 1.3.0. Let's pick up the task of smarter per-country defaults in https://github.com/backdrop/backdrop-issues/issues/1521.

**Comment by quicksketch** [comment]
This may be causing failing tests. I'm getting this on a fresh 1.x:

```
---- Date: Date Field (DateFieldTestCase) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      date_field.test    337 DateFieldTestCase->dateForm()      
    Node has been created
Fail      Other      date_field.test    339 DateFieldTestCase->dateForm()      
    Found the correct date for a date field using the date_select widget
    displayed using the short date format.
Fail      Other      date_field.test    347 DateFieldTestCase->dateForm()      
    Node has been created
Fail      Other      date_field.test    349 DateFieldTestCase->dateForm()      
    Found the correct date for a date field using the date_select widget
    displayed using the long date format.
Fail      Other      date_field.test    337 DateFieldTestCase->dateForm()      
    Node has been created
Fail      Other      date_field.test    339 DateFieldTestCase->dateForm()      
    Found the correct date for a datestamp field using the date_select widget
    displayed using the short date format.
Fail      Other      date_field.test    347 DateFieldTestCase->dateForm()      
    Node has been created
Fail      Other      date_field.test    349 DateFieldTestCase->dateForm()      
    Found the correct date for a datestamp field using the date_select widget
    displayed using the long date format.
Fail      Other      date_field.test    337 DateFieldTestCase->dateForm()      
    Node has been created
Fail      Other      date_field.test    339 DateFieldTestCase->dateForm()      
    Found the correct date for a datetime field using the date_select widget
    displayed using the short date format.
Fail      Other      date_field.test    347 DateFieldTestCase->dateForm()      
    Node has been created
Fail      Other      date_field.test    349 DateFieldTestCase->dateForm()      
    Found the correct date for a datetime field using the date_select widget
    displayed using the long date format.


---- Date: Date Field UI (DateUITestCase) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      date.test           38 DateUITestCase->testFieldUI()      
    Found the correct date for a date field using the date_select widget.
Fail      Other      date.test           38 DateUITestCase->testFieldUI()      
    Found the correct date for a date field using the date_select widget.
Fail      Other      date.test           38 DateUITestCase->testFieldUI()      
    Found the correct date for a date field using the date_select widget.
```

I'm working on fixing these over in https://github.com/backdrop/backdrop/pull/1212

**Comment by quicksketch** [comment]
Fixed again in https://github.com/backdrop/backdrop/pull/1212. Phew!

**Comment by quicksketch** [comment]
More test failures seem to have cropped up due to this. Completely bizarrely, it depends on the *time of day* in which the test was run whether it fails or not. Because Date module populates the current time into the default values. So in the morning this works and in the afternoon it fails.

Second PR filed here: https://github.com/backdrop/backdrop/pull/1219.

**Comment by mikemccaffrey** [comment]
> More test failures seem to have cropped up due to this. Completely bizarrely, it depends on the time of day in which the test was run whether it fails or not. Because Date module populates the current time into the default values. So in the morning this works and in the afternoon it fails.

That is hilarious. We may want to increase the test coverage.
