### ISSUE TITLE
[UX] don't say "resolution" when we mean "dimensions"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1121]
Let's change the text on Image fields that says "resolution" (WRONG) to say "size" (BETTER) instead.

omg this has bothered me for *so* long.... see https://www.drupal.org/node/1215730 and https://www.drupal.org/node/1215784

This will be a two part fix: 
1) this issue - fixes the User interface so people using Backdrop don't think we're idiots
2) #1122 - fixes the Developer experience so the code is consistent with User Interface

**Comment by quicksketch** [comment]
Thanks, merged into 1.x and 1.1.x. The issue at https://github.com/backdrop/backdrop-issues/issues/1122 still needs some work though.

**Comment by jenlampton** [comment]
merged!  guess I can close this? :)
