### ISSUE TITLE
[DX] Ensure code matches User Interface for image size limitations

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1122]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/1121

Let's change the text on Image fields that says "resolution" (WRONG) to say "size" (BETTER) instead.

omg this has bothered me for so long.... see https://www.drupal.org/node/1215730 and https://www.drupal.org/node/1215784

---
PR https://github.com/backdrop/backdrop/pull/1701

**Comment by quicksketch** [comment]
From https://github.com/backdrop/backdrop/issues/1028:

> This PR needs an update hook added. We'll need to loop through all bundles, find all config files containing image fields, and update all the keys. Could be a doozy!

I don't think this would actually be very bad. You can get all the field instances pretty easily with:

```php
$config_names = config_get_names_with_prefix('field.instance.');
foreach ($config_names as $config_name) {
  $config = config($config_name);
}
```

Then just check each $config for being an image widget and adjust the settings, then call $config->save().

**Comment by quicksketch** [comment]
Another thing, even though we've merged in https://github.com/backdrop/backdrop-issues/issues/1121, why did you use the word "size" when the original suggestion was the more accurate "dimensions"? The new Editor image upload uses dimensions as well, maybe we should use that for consistency?

**Comment by jenlampton** [comment]
yes, dimensions is better.  I don't know why I did that.

**Comment by jenlampton** [comment]
Pushed a new PR with an update hook.

**Comment by quicksketch** [comment]
I can't find the PR, it doesn't seem to be in the PR list or linked anywhere in this issue.

**Comment by quicksketch** [comment]
Thanks, the PR at https://github.com/backdrop/backdrop/pull/1701 has been updated. But it looks like it's failing tests.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1701 for 1.6.0. Even though this is a minor change, it's still a change that needs a notice. Let's get this documented before 1.6.0 is released.
