### ISSUE TITLE
Include contrib layouts in the available updates procedure.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1133]
Layouts also have versions and will need to be updated. We need to update our routines to check for that and the UI too.
- [ ] list them in `admin/reports/updates`
- [ ] also list not used ones and adjust the "Check for updates of disabled modules and themes" setting in `admin/reports/updates/settings`
- [ ] adjust the "Module and theme update status" message(s) in `admin/reports/status`
- [ ] ...

**Comment by docwilmot** [comment]
See PR https://github.com/backdrop/backdrop/pull/952. Waiting review.

**Comment by quicksketch** [comment]
Let's consolidate this with https://github.com/backdrop/backdrop-issues/issues/958.
