### ISSUE TITLE
Node delete limited to 35

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1136]
When trying to delete a whole batch of nodes, I find the system limits this to 35 at a time, irrespective of how many are displayed at admin find content.
I would like to be able to change this limit of 35 but where can I find it?

**Comment by quicksketch** [comment]
Hi @Graham-72! Thanks for the report.

I did a little digging for the number "35" and found that it's the default for the "action_recursion_limit" setting. This is intended to prevent (obviously) "recursive" calling of actions. But as the bulk delete form uses actions and it's being capped at 35, it wouldn't surprise me if this wasn't for recursive actions, but for all actions somehow. Could you try just increasing this limit in your active configuration directory's `system.core.json` file?

**Comment by quicksketch** [comment]
Ah, I think I found the issue, in `core/includes/actions.inc`, we increment the stack at the top:
```
  // $stack tracks the number of recursive calls.
  static $stack;
  $stack++;
```

But then we have a return function in the middle of that function, before the stack is reduced back down again:

```php
  if (function_exists($callback)) {
    return $callback($entity, $context);
  }
  else {
    trigger_error(t('The action "@action" could not be executed ...[snip])), E_USER_ERROR);
  }

  $stack--;
```

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1033 that should fix this. It moves the `return` down below the $stack reduction, which should make this recursion checking work as expected.

**Comment by Graham-72** [comment]
Thanks @quicksketch for this fix.
I am doing some testing of Feed Import module with a CSV file with 98 entries, and it was a bit laborious deleting them in batches after a test. Now I can delete all at once. :+1:

**Comment by quicksketch** [comment]
Excellent, thanks @Graham-72! The tests are currently failing on this which (I think) means that our previous tests were actually erroneous. I'll fix the tests and update the PR when I get a chance, but I think the fix itself is good.

**Comment by quicksketch** [comment]
New PR at https://github.com/backdrop/backdrop/pull/1033 should now pass tests. The fix was right but the test had an error in it.

**Comment by quicksketch** [comment]
Fixed in 1.x and 1.1.x.
