### ISSUE TITLE
Problem with Module Link in Backdrop 1.1.3 CMS

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#1139]
Dear developers,
I have a problem with the modules link and I downloaded it from GitHub and installed in Backdrop 1.1.3. How to add the "Link" field to the comments, and I know that I made it.

But when I use this field, any URL that I have entered will appear in the comment.

What could be? About a help, I am pleased. Thanks in advance.

![backdrop-cms-field-link](https://cloud.githubusercontent.com/assets/7885632/9626719/d430edf2-515f-11e5-9230-d58a30fc9a85.jpg)

**Comment by quicksketch** [comment]
> But when I use this field, any URL that I have entered will appear in the comment.

This is what should happen. If you mean you do *not* want the link to appear, then you can adjust how the link is displayed (or hide it) by visiting Structure > Content Types > Article (or whatever content type). Then once on that page, there is a tab for "Comment Display". On that page you can change the way link fields are displayed on comments.
