### ISSUE TITLE
[UX] Description text for image dimension settings unclear

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1142]
<h3 id="summary-problem-motivation">Problem/Motivation</h3>
When a user is uploading an image (where maximum dimensions have been set) the description text that appears is something like:
<code>
Images must be smaller than 2000x2000 pixels.
</code>
This string follows two other strings, the first about file size (if it was set) and the second about extension (if it was set) and both of these messages indicate that their upload will be rejected if they don't get it right. For image dimensions, however, their upload will not be rejected. Instead, the image will be resized.

We make this resizing action clear to administrators with the following text on the image field settings form:
<code>
If a larger image is uploaded, it will be resized to reflect the given width and height. 
</code>

We should also make this clear to those people entering the images, so they don't waste time and energy resizing images when the system can do that for them.

<h3 id="summary-proposed-resolution">Proposed resolution</h3>

I propose that we change the description text on the user-facing form as follows:
<code>
Images larger than 2000x2000 pixels will be scaled down.
</code>

The same change should *not* be made for minimums, since those files will be rejected.

Based on work from: https://www.drupal.org/node/2563403

**Comment by Graham-72** [comment]
:+1:

**Comment by klonos** [comment]
:+1:

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.1.x.
