### ISSUE TITLE
`backdrop_add_js()` doesn't load js when used in `hook_block_configure`

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1147]
`backdrop_add_js()` doesn't seem to load required js when used in `hook_block_configure`. I may be having a brain freeze, but I think I have checked.

**Comment by quicksketch** [comment]
This may be to do with the block configure forms being in dialogs, though I think that the addition of JS and CSS in dialogs is fully supported.

Could you try using `#attached` on your element and see if that has better luck?

$element['#attached']['js'][] = backdrop_get_path('module', 'my_module') . '/js/my-module.js';

**Comment by docwilmot** [comment]
This works as expected. Closing.
