### ISSUE TITLE
Webform "Full content" View mode does not work in a block?

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1148]
Hi! I am sorry if this is something of my fault but may be somebody could direct me to a right way :)

I try to show my Webform content in a block.
According to the instructions - "You may customize different view modes (other than the "Form only" mode)" - I have customized it to **Full content** but it does not work for me. After the block configuration is saved and the layout is saved too it switches  again to the **Form only** mode.

![webform_full_content_1](https://cloud.githubusercontent.com/assets/13515302/9697713/abcae0a4-53a1-11e5-8fda-ec006a0c860c.gif)

![webform_full_content_2](https://cloud.githubusercontent.com/assets/13515302/9697715/b3a7ab40-53a1-11e5-8ec4-66ae9678b252.gif)

![webform_full_content_3](https://cloud.githubusercontent.com/assets/13515302/9697716/b97de39a-53a1-11e5-8b24-e289ee5e3a31.gif)

**Comment by bd0bd** [comment]
I have tried to set up **Full content** mode for Webform block in Drupal 7 and it works ok.

**Comment by klonos** [comment]
@bd0bd: you need to file this under webform's issue queue, like you did for https://github.com/backdrop-contrib/webform/issues/10
