### ISSUE TITLE
Is the Layout module's context / visibility resolver reusable by other modules?

### ISSUE THREAD

**Issue by rszrama** [backdrop/backdrop-issues#1154]
Sorry, I was having a hard time last night figuring out exactly how the Layout module resolves the context / visibility conditions to figure out how to format page output. (Granted, relaxing at the beach and not bringing my code-sleuthery A-game.)

I was considering reusing the system for other context related things, such as "What store am I currently browsing?" whether it's based on URL or some other property of the user's session.

**Comment by docwilmot** [comment]
As far as I can tell, till @quicksketch comes on, this is checked in `layout_route_handler($router_item)` in `layout.module` where Backdrop checks if the user has access to the given path. Hope that helps, since I don't have a `code-sleuthery A-game` myself.

**Comment by BWPanda** [comment]
Closing this old issue. Please re-open if more information is needed.
