### ISSUE TITLE
layout_load_multiple_by_path() doesn't return Default Admin Layout for admin paths

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1162]
For example `layout_load_multiple_by_path(admin/content)` returns the Default Layout, which is wrong, it should be the Admin Layout. The culprit is in layout_load_multiple_by_path():
```
      if (path_is_admin($_GET['q'])) {   <<<<<--------- HERE!
        $layout_names[] = 'admin_default';
      }
      else {
        $layout_names[] = 'default';
      }
```
So the function returns 'default' except when called *from* an admin path. I'm not sure why `$_GET` was used here instead of `$path`?

**Comment by quicksketch** [comment]
Yep, I think you're spot-on here. I can't imagine why `$_GET['q']` would be used here instead.

**Comment by quicksketch** [comment]
Thanks, merged into 1.x and 1.1.x.
