### ISSUE TITLE
Automatically delete config on module uninstall?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1167]
When a module is uninstalled, should we automatically delete any config files associated with that module, or should it be up to the module to clean up after itself, much like we did with variables in Drupal?

**Comment by docwilmot** [comment]
[This already happens](https://github.com/backdrop/backdrop-issues/issues/403) if you have `hook_config_info()` set up.

**Comment by quicksketch** [comment]
I'd encountered this in Devel module a couple of times, but the reason is that Devel module doesn't have a hook_config_info()! So this is a devel specific problem it seems.

**Comment by quicksketch** [comment]
Yeah, confirmed this is a module-specific problem. I tested and fixed Devel in https://github.com/backdrop-contrib/devel/issues/10.
