### ISSUE TITLE
Social sharing module for current Backdrop CMS Version

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#1170]
Hello Developers,
I would like to know if there is a current module for social sharing ?? The module is suitable for the current Backdrop version and function. Thank you in advance.

**Comment by quicksketch** [comment]
I don't think there is yet. We have a port of https://github.com/backdrop-contrib/socialfield, which allows users to input their own social profile URLs. But we don't have one for sharing content of which I'm aware. It's a short job to port any module though. If there's one you like in particular and you're capable of [doing a port](https://api.backdropcms.org/converting-modules-from-drupal). If not, you could perhaps make a request. Several of the contrib developers have gotten very fast at porting modules.

**Comment by serundeputy** [comment]
there is:https://github.com/backdrop-contrib/sharethis but I've not tried this one

**Comment by AlexL777** [comment]
Ok, thank you very much, quicksketch and serundeputy,

I look at what I can still do. However, the module "ShareThis" not compatible with Backdrop 1.1.3. That appears to me in the back among modules.

Drupal modules to Backdrop modules I've never ported and it must view me. If it is not so hard, I can try me off.

**Comment by AlexL777** [comment]
I believe that porting the modules will be too hard for me. Therefore, I must see if I can even ask if the developers. I have since thought about Drupal 7 Module as "Pathauto" and this Backdrop module "share this".

**Comment by MrHaroldA** [comment]
Pathauto is already merged into Backdrop (#87). I personally don't like the Share This module; too much clutter and candy. I'd prefer the Service links module for social buttons.

https://www.drupal.org/project/service_links

**Comment by AlexL777** [comment]
OK, yes Service Links Module looks good and think that would be something for our Backdrop blog. I noticed today that there this week Backdrop 1.2 appears and perhaps later there are new modules or old to be updated.

ShareThis is with me namely Backdrop 1.1.3 incompatible. This shows me the system.

**Comment by biolithic** [comment]
Hi,
https://backdropcms.org/project/sharethis is now updated with the correct
versioning and working in basic testing for me.
Thanks for using!

**Comment by AlexL777** [comment]
Thank you, it works for me now. I have included the same buttons in the sidebar. That fits for me.

**Comment by serundeputy** [comment]
thanks @biolithic ! @AlexL777 glad it is working for you. 
I'm closing this one out.  It can be reopened or file a ticket directly in the `share this` queue if it is a `share this` issue: https://github.com/backdrop-contrib/sharethis
