### ISSUE TITLE
Include Date module in the Standard profile

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1171]
When we added Date module in #478, we didn't yet enable it in the Standard profile. It seems like it should be enabled by default on new sites.

**Comment by klonos** [comment]
Yes, indeed.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1053. Enabled Link module as well.

**Comment by klonos** [comment]
Thanx :+1:
