### ISSUE TITLE
Date fields should default to no value rather than "now"

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1172]
Followup to Date module in #478. When creating new Date fields, it defaults to the current date ("now"). Instead it should default to no date at all.

**Comment by serundeputy** [comment]
Fired up a `PR` here: https://github.com/backdrop/backdrop/pull/1056 , but I'm a little sad as I like the default of `now`, but I can still select it when I configure my fields.

**Comment by quicksketch** [comment]
Thanks @serundeputy. I ended up merging https://github.com/backdrop/backdrop/issues/1061.
