### ISSUE TITLE
HTML bug within 1 column layout?

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1179]
I have validated the page and it seems like a bag within 1 column layout?
There is no closing tag >/div< for >div class="section clearfix"<

```
<div class="layout--one-column layout">

  <header class="l-header" role="banner" aria-label="Site header"><div class="section clearfix">
  <div class="l-header-inner"><div class="block block-system-header">
```

2 column layout - everything is ok.

```
<div class="layout--two-column layout">

  <header class="l-header" role="banner" aria-label="Site header">
  <div class="l-header-inner"><div class="block block-system-header">
```

I do not know where-how to fix it.

**Comment by quicksketch** [comment]
This is a known issue in version 1.1.3 and has already been fixed in #1007. It will be fixed 1.1.4 and 1.2.0. Thanks!
