### ISSUE TITLE
[UX] Skip the field settings step when adding a new field if there are no settings

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1183]
This issue is somewhat related to https://github.com/backdrop/backdrop-issues/issues/779 (new field UI).

One step suggested in that issue is to eliminate the step between adding a new field and configuring the widget. This middle step is configuring of the field's database-settings. One immediate improvement we could make that affects Link and Email fields, is that these fields don't have any database settings at all, and so the user is taken to a page that just says "This field has no settings", right after they just added a field. Then they hit "Save field settings" and are taken to a bunch of settings for the widget. The typical end-user, it looks like we just lied to them there were no settings, but then showed them a bunch of settings on the next page.

Let's suppress this middle step if there's nothing there.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1057 into 1.x. A small but good improvement.

**Comment by klonos** [comment]
Thanx :+1:
