### ISSUE TITLE
backdropGet messes up urls in subdirectories on wamp

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1184]
At least I think its `backdropGet`. My local Backdrop on WAMPserver is installed in `http://localhost/backdrop/backdrop/`. Any time a test has a sequence like this:

```
    $disable_link = $this->xpath('...');
    $disable_url_parts = backdrop_parse_url(...);
    $this->backdropGet($disable_url_parts['path'], $disable_url_parts);
```

The resulting url is `/backdrop/backdrop/backdrop/backdrop/admin/structu....etc`. Note the four 'backdrop's. I have noticed this for a while but always thought I was doing something wrong. But its persistent. Debugging shows accurate returns for `$disable_link` and `$disable_url_parts` in this case, so I'm assuming the mangling happens at backdropGet.

Makes my tests fail locally, but pass on Travis.

**Comment by quicksketch** [comment]
Thanks, sounds like it would likely be a bug. Travis-CI runs Backdrop in the root of a web directory (as do I), so it's possible that this is a general problem across platforms and not Windows-specific at all.

**Comment by quicksketch** [comment]
To be clear, is this when tests are through the UI or run through the `run-tests.sh` script?

**Comment by docwilmot** [comment]
through the UI.

**Comment by docwilmot** [comment]
I've switched to subdomains instead, which solves this prblem, but wonder if https://github.com/backdrop/backdrop-issues/issues/2220#issuecomment-271938135 may be a fix for this. 
Closing, as no further report of this bug.
