### ISSUE TITLE
Minor Cleanup on Text formats before 1.2.0

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1185]
There are three major UX issues I want to have done before people start trying to use Backdrop 1.2 and get confused by the shiny new text editor
- [x] #1187 Remove filter tips that say you can enter HTML when you can't
- [ ] #1188 Remove the word "HTML" from the Filtered HTML format name

**Comment by quicksketch** [comment]
With https://github.com/backdrop/backdrop-issues/issues/1187 done and https://github.com/backdrop/backdrop-issues/issues/1188 not going to happen before 1.2.0, I think this should be closed. We don't really need a meta for this.

If you like, it might be a good idea to lump the ones that didn't make it into #1087.
