### ISSUE TITLE
[UX] Remove filter tips that say you can enter HTML when you can't

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1187]
Having filter tips that tell you which HTML tags can be entered (when you can't enter any) is terribly confusing.  Let's have the HTML filter check to see if the ckeditor is enabled on a text format before telling people HTML tags that are allowed.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1058 looks pretty good, but it's clearly a temporary hack that would only work for core and not any other editors. Still, this might not be a bad solution until #1089 gets implemented, hopefully in the 1.3.0 release.

**Comment by quicksketch** [comment]
Committed to 1.x: https://github.com/backdrop/backdrop/commit/0ad51c1f903b7ba9ce61ecb7a7ce41c75a4edd99.
