### ISSUE TITLE
Feeds or Charts head starts

### ISSUE THREAD

**Issue by biolithic** [backdrop/backdrop-issues#1192]
@quicksketch or anyone that is interested.
If you are looking for a head start on ports of Feeds or Charts modules, non-working versions of them are 

https://github.com/biolithic/charts
https://github.com/biolithic/backdrop_feeds
https://github.com/biolithic/backdrop_job_scheduler

I just had something come up and probably won't be able to spend the time to sit down and debug these to bring them to completion anytime soon.

Feeds depends on some CTools functions not in Backdrop and Charts silently fails when choosing the Views style (Grid, List, Charts, etc)

If you need these modules, you are more than welcome to fork and modify them.  If not, you can forget about this issue.  I just thought I would let people know where they are located incomplete.

Thanks!

**Comment by quicksketch** [comment]
Great, thanks! Maybe the backdrop contrib group would be a better place for this sort of announcement: https://github.com/backdrop-ops/contrib but I appreciate it nonetheless. Thanks!
