### ISSUE TITLE
Update documentation with new project page URLs

### ISSUE THREAD

**Issue by PaulHoza** [backdrop/backdrop-issues#1195]
The current documentation is riddled with references to drupal.org/project/example.. when referencing the original module.  However, many modules have been fully ported to Backdrop and readme references have been going to the Github pages (from what I've seen.)

Now that we have a live /project/ (and /themes, etc.) location for modules, I think we should start encouraging modules and core documentation to point users to the Backdrop project pages where relevant.

Incoming shortly is a PR with some of those updates for review.

**Comment by PaulHoza** [comment]
Hmm... well crud. I would /swear/ that I had found a few places in core where there were references to "drupal.org/project/.." that I thought we could change to use the new site URLs on backdropcms.org... but now I can't find them.

Sorry for the noise.  I'll leave this here in case anyone sees what I'm missing or otherwise has a reason to keep this open.

I do know there were several instances of this in contrib, so I'll just file separate PRs for each module/theme I found (which were a few in a quick search & usage last week.)

Oops.

**Comment by quicksketch** [comment]
Awesome, thanks @PaulHoza! Yeah we cleaned up some references just recently over in https://github.com/backdrop/backdrop-issues/issues/92. So maybe those were the ones you were seeing. We're pretty clean from drupal.org references other than those areas where it makes sense to keep them, but with 14 year of Drupal history, there are a lot of references to recreate on backdropcms.org.
