### ISSUE TITLE
[UX] Add an editor style sheet to each core theme

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1198]
I'm having a really hard time entering content into ckeditor. The font is really tiny, and the lack of line-height makes things really hard to read.  

Can we either undo the squashing of text that happens in ckeditor, or if this is some kind of system default, add a style sheet to make the first time impression of people working in the rich-text editor a little more pleasurable?

* [x] Add seven.base.css to the editor for the Seven theme
* [x] Add base.css to the editor for the Basis theme
* [x] Add a new editor style sheet to the Bartik theme

---
PR: https://github.com/backdrop/backdrop/pull/1921

**Comment by quicksketch** [comment]
There is already a stylesheet that is added within the editor: `ckeditor-iframe.css`. We can adjust these styles globally or on a per-theme basis.

**Comment by klonos** [comment]
I think per-theme would be more appropriate.

**Comment by jenlampton** [comment]
I agree with @klonos.  We should do some work here so that `what people see` in the editor isn't completely different than `what people get` when they save.  Updating issue to match title.

**Comment by klonos** [comment]
Yeah, this will ensure that we "promote" some type of best practice where the styles that are specific to the editor are in a separate style sheet for each theme. People can copy those from the core themes and edit away.

**Comment by jenlampton** [comment]
I pushed a new PR for this at https://github.com/backdrop/backdrop/issues/1921 that adds the two base style sheets into the editor for Basis and Seven, and I created a new separate style sheet for Bartik.

**Comment by quicksketch** [comment]
The PR looks great. Are the `base.css` and `seven.base.css` adequate for conveying all the styles we want from the Basis and Seven themes, respectively? I do really like the easy reuse of these stylesheets rather than duplicating everything as you had to do for Bartik.

**Comment by jenlampton** [comment]
> Are the base.css and seven.base.css adequate for conveying all the styles we want from the Basis and Seven themes, respectively?

I think so. There's not much we can do out of the box with the filtered HTML format other than use the base elements. Full HTML would allow the addition of any classes, but most of the classes defined in seven and basis are not for base elements anyway. In my testing it seemed sufficient.

**Comment by jenlampton** [comment]
This could use another tester: https://github.com/backdrop/backdrop/issues/1921

**Comment by quicksketch** [comment]
Looks great. Merged https://github.com/backdrop/backdrop/pull/1921 into 1.x for 1.8.0. Thanks @jenlampton for the PR and @tomgrandy for the review!
