### ISSUE TITLE
CKEditor and aggregate JS

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1202]
If I switch on aggregation of Javascript, CKEditor will not appear. What have I done wrong? Have I not seen somewhere a setting to exclude CKEditor from aggregation?

**Comment by quicksketch** [comment]
Thanks @Graham-72! This looks like a pretty serious issue. CKEditor seems to loose track of where it is installed when aggregation is turned on.

Considering the size of the CKEditor library and the fact that it is already compressed and aggregated itself, I think the best solution may be to just omit CKEditor from aggregation. I'll file a PR in a minute.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1066 that should fix this.
