### ISSUE TITLE
Fatal error when attempting to change a URL alias on a node

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1203]
I get the following error when attempting to change a URL alias:

```
Recoverable fatal error: Argument 1 passed to filter_entity_insert() must implement interface EntityInterface, instance of stdClass given in filter_entity_insert() (line 1506 of /backdrop/core/modules/filter/filter.module).
```
Steps to reproduce:
1) create a node (with no alias)
2) set up automatic aliasing for that node type
3) edit the node, check the box for an automatic alias, save
4) edit the node again, uncheck the box for an automatic alias, change the alias, save
5) error.

Interestingly, the alias is updated, and things appear to be fine in spite of the horrible scary error.

**Comment by quicksketch** [comment]
I tried reproducing this locally and couldn't find an issue. I think this is actually caused not by Path but by redirect module. 

I filed an issue and a PR over at https://github.com/backdrop-contrib/redirect/issues/16 that should fix this problem.
