### ISSUE TITLE
I tried to update to v1.2 only, but now I see the installer in the frontend - what to do

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#1205]
Hello Developers,
I screwed up and did my Backdrop blog update to the version 1.2 and have the complete version uploaded to the server. Now I see the installer in front and no blog.

Which file was the configuration file, where you had the database data in it? Can you save that? My database is still intact.

**Comment by MrHaroldA** [comment]
You've probably overwritten settings.php?

**Comment by Graham-72** [comment]
The really important lines in settings.php will be something like these:
at 14 and 15
`
$database = 'mysql://bduser:bdpass@localhost/bkdrop';

$database_prefix = '';
`
and at 194-195
`
$config_directories['active'] = 'files/config_ef2ad3e94f5c553ddd4a01907b63918f/active';

$config_directories['staging'] = 'files/config_ef2ad3e94f5c553ddd4a01907b63918f/staging';
`
Do you have anyhting like these?

**Comment by AlexL777** [comment]
Thank you both. Has helped me and now I have the the blog again. I just installed the new CKEditor and me, it is noticed that the tool "style" in the editor is not working. I show you here a screenshot.

Can you assure me that it is with you also like that? Thank you in advance.
![backdrop12-ckeditor-error](https://cloud.githubusercontent.com/assets/7885632/9900381/aad11994-5c60-11e5-9dfc-31dabf4088ed.jpg)

**Comment by AlexL777** [comment]
False alarm :) You have the Styles add, what I'm doing.

**Comment by quicksketch** [comment]
Yay, sounds like a mostly successful upgrade. There are step-by-step instructions at https://backdropcms.org/upgrade for doing upgrades.

Let's file new issues for problems you have after installation. Thanks for trying out 1.2.0 so quickly!
