### ISSUE TITLE
wrong version string

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1208]
my site says i'm running 1.3.x-dev
`boostrap.inc` says `define('BACKDROP_VERSION', '1.3.x-dev')`

**Comment by quicksketch** [comment]
> my site says i'm running 1.3.x-dev

If you're running the 1.x branch, that is now 1.3.x-dev, as 1.2.x has been split into a new branch for bug fixes only. And the new features will continue to into the 1.x branch (which will become 1.3.0).

**Comment by docwilmot** [comment]
Ahh. I see.

**Comment by klonos** [comment]
> If you're running the 1.x branch, that is now 1.3.x-dev, as 1.2.x has been split into a new branch for bug fixes only. And the new features will continue to into the 1.x branch (which will become 1.3.0).

I see the confusion here... in Drupal, the dev versions used to be [current_version]+dev (the new version was inserted in the version string only *after* a release was made) while the way we have it, it is [next_version]+dev.
