### ISSUE TITLE
CKEditor disappeared after installing Backdrop 1.2

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1210]
1. I have **completely** deleted  my site.
2. Uploaded the new version of Backdrop 1.2.
3. Replaced the **files** folder with my original **files** folder.
4. Replaced the **settings.php** with my original **settings.php** file.
5. Uploaded Webform module in the modules folder.
6. Uploaded my original Bartik in the **themes** folder.

And now there is no CKEditor although it is installed in the core and is activated.

Previously (in Backdrop 1.1.3) it was placed in the modules folder.

![editor](https://cloud.githubusercontent.com/assets/13515302/9912051/1cb81e66-5cae-11e5-8039-ec10f653f5ed.gif)

![editor2](https://cloud.githubusercontent.com/assets/13515302/9912055/22002c10-5cae-11e5-8ba8-45af119e7dbe.gif)

**Comment by MrHaroldA** [comment]
Did you run the installer, or have you used your old database with the new release? If so, did you run the update script? And are there any javascript errors in your browser?

**Comment by bd0bd** [comment]
Thank you @MrHaroldA

Yes, I have used my old database.
No any errors were.
Report - 100% is ok.

Right now I have reinstalled my original site - because I can see a lot of bugs reported here.

**Comment by quicksketch** [comment]
> Yes, I have used my old database. Status report - 100% is ok.

So besides replacing all the files, did you also run update.php? If status report is okay, then you probably did, but just checking. :smile:

Just enabling the CKEditor module does not immediately make the editor show up. You have to enable it on a text format. Visit `admin/config/content/formats/filtered_html` and turn on the CKEditor under the select list:

![selection_004](https://cloud.githubusercontent.com/assets/100206/9915316/aab8762e-5c73-11e5-9ddb-1a67db51d845.png)

**Comment by bd0bd** [comment]
@quicksketch, thank you!

I do not remember if I did update.php. Probably not.

I know about this option, but it was activated in my previous site and in the database it should remain the same I think?
Well, now I will try again to install it and then will report here.

**Comment by PaulHoza** [comment]
As a side note, do you think that option would be better to read "Rich Text
Editor" or similar? If this is a common issue for people (thinking they
upgraded and don't see the editor), maybe this turns out to be a place for
UX improvement?

It might be clearer to users than this, even if it's not as accurate.  (I
also do understand that users may eventually install other WYSIWYG
libraries, so maybe this wouldn't be a proper/future-proof change.)

**Comment by quicksketch** [comment]
@bd0bd, as we found yesterday when we upgraded BackdropCMS.org, also be sure that you enable these two filters on the text format:

![selection_005](https://cloud.githubusercontent.com/assets/100206/9915792/330954ce-5c76-11e5-8771-bafebfd378aa.png)

Enabling those will allow you to upload and align images from within CKEditor.

Though there is a bug where alignment in CKEditor is allowed but does not work when the alignment filter is disabled: https://github.com/backdrop/backdrop-issues/issues/1204

>  If this is a common issue for people (thinking they upgraded and don't see the editor), maybe this turns out to be a place for UX improvement?

We could also do a couple of things to help here:

- We didn't add a `configure = admin/config/content/formats` line into the .info file. Adding that would give users a "Configure" link from the modules page.
- We could make a message upon module enable, indicating where the module should be enabled. Although this works well when enabling a single module. I'm not a fan of this approach as it's redundant with the configure link and doesn't work well when you enable a lot of modules.
- We could add a `hook_requirements()` to CKEditor, that would alert the user if they have enabled CKEditor but not actually enabled it on any formats. @bd0bd checked this page for any errors, and if there had been a message there he would have figured out what was wrong right away.

**Comment by bd0bd** [comment]
@quicksketch, thank you!

Yes, the problem was because the editor was not enabled:
![aab8762e-5c73-11e5-9ddb-1a67db51d845](https://cloud.githubusercontent.com/assets/13515302/9916485/46c6913a-5cc5-11e5-8604-513caa158a01.png)
Now it is ok.

Special thanks for this option for image upload. Cool looking:
![image](https://cloud.githubusercontent.com/assets/13515302/9916524/7a3a47dc-5cc5-11e5-954f-2b8ffb434aeb.gif)

During the upgarade - /core/update.php - I got these things:
![upgrade-1](https://cloud.githubusercontent.com/assets/13515302/9916619/ed0eb9fa-5cc5-11e5-91ad-9159e1a67e03.gif)

![upgrade-2](https://cloud.githubusercontent.com/assets/13515302/9916626/f5592c3a-5cc5-11e5-9b8e-f512dcb0fec0.gif)

But after pressing on the button APPLY PENDING UPDATES everything was ok, Status report is 100% ok.

**Comment by klonos** [comment]
> As a side note, do you think that option would be better to read "Rich Text Editor" or similar?

CKeditor is the default that ships with core, but it is not the only rich text editor out there. When more WYSIWYG modules get ported, people might use these and having the drop-down state which is which by their actual name seems to me like the only reasonable way to have it.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/issues/1077 that does the following:

- Added a `configure[]` line to ckeditor.info to guide users to the text formats page.
- Added a hook_requirements() to CKEditor that displays the follow message:
![screenshot31](https://cloud.githubusercontent.com/assets/100206/9951996/005f6f56-5d8c-11e5-964e-9ab44c9809f9.png)
- And added a column to the list of formats to include the attached editor. I meant to include this in the original editor work, I'm not sure how it was left out:
![screenshot32](https://cloud.githubusercontent.com/assets/100206/9951999/175bb5d4-5d8c-11e5-83f2-899e49772d24.png)

**Comment by quicksketch** [comment]
Combined with @bd0bd successfully figuring out why this wasn't working. I think this issue is closed with the additions to help identify CKEditor's status.

**Comment by klonos** [comment]
> And added a column to the list of formats to include the attached editor.

Was about to file an issue for it. You beat me to it. Thanx.
