### ISSUE TITLE
Fields bug is not fixed if the image is floated right

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1211]
I have tried new Backdrop 1.2 and can see the bug I have written about 14 days ago is still there:
https://github.com/backdrop/backdrop-issues/issues/1140

Please, may you advice a right way to fix it?

Thank you!

**Comment by MrHaroldA** [comment]
Please do not open bugs to point to a bug that's open.

**Comment by bd0bd** [comment]
I try to find out how to fix it.
2 weeks is left and nobody care about it :)
