### ISSUE TITLE
Error when adding Webform block

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1213]
Error when adding Webform block:

![block](https://cloud.githubusercontent.com/assets/13515302/9919354/e7105db0-5cd4-11e5-955c-9fb94e4fecdb.gif)

![block2](https://cloud.githubusercontent.com/assets/13515302/9919360/edaef79e-5cd4-11e5-9b04-fa0c3c351e6b.gif)

**Comment by docwilmot** [comment]
Hi @bd0bd 
It is best if you report problems with a contrib module in that module's own issue queue so the developer maintaining the module becomes aware.
https://github.com/backdrop-contrib/webform/issues

**Comment by quicksketch** [comment]
Thanks @docwilmot. You're right that this should be handled in the Webform issue tracker, not here.

**Comment by bd0bd** [comment]
Sorry, ok!
