### ISSUE TITLE
Use +SymLinksIfOwnerMatch instead of +FollowSymLinks option in .htaccess (Installing Backdrop on shared hosting).

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1216]
I was finding it impossible to install Backdrop on Fasthosts, one of our large hosting services, and now I have found an answer at https://www.drupal.org/node/1269780

We need to be replacing +FollowSymLinks in ,htaccess with +SymLinksIfOwnerMatch

**Comment by klonos** [comment]
...title change to state the task and in order to match the d.org issue.

**Comment by PaulHoza** [comment]
I've had to make this change in .htaccess files for a long time.  This would be great to have official if the powers that be understand it all more than I do and think it's a Good Thing.  Much of what I've read on the subject points to it being a better setting.

I have to make this change to root .htaccess, but also to ./files/.htaccess to get D7 or Backdrop to work right.

**Comment by quicksketch** [comment]
Hi guys, this seems like an obvious improvement to me. the FollowSymLinks directive only makes a difference if you're using symlinks in the first place. Although it "common", I don't think most sites utilize symlinks within their files directory. Especially with Apache 2.2+ being dominant, switching this option seems like a no-brainer: http://w3techs.com/technologies/details/ws-apache/2/all

There's nearly no reason at all to include `FollowSymLinks` at all. Let's just replace it straight-up with `SymLinksIfOwnerMatch` (introduced in Apache 2.2).

**Comment by Graham-72** [comment]
Yes please, let's do it.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1078.

This is a change that has a marginal effect on performance, and only when using symlinks in the first place. Especially when compared to an expensive SQL query or the like, this is negligible. When compared to getting a 500 error and blocking the installation entirely, the minuscule performance decrease is well worth it.

Thanks @Graham-72 and @PaulHoza for confirming the commonality of this problem. I've been on either nginx or weak MAMP setups for so long it's unlikely I would run into this any time soon.

**Comment by quicksketch** [comment]
With no test issues, the recommendations here and on drupal.org; Travis and my own local running just fine with the new more-secure setting, this has been merged into 1.x and 1.2.x.
