### ISSUE TITLE
Error after theme change with Colihaut

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#1217]
Dear developers,

I set Backdrop 1.2 and have just after theme change in the backend this error message.

    The specified file temporary: // fileT0O7Tb Could not be copied Because The destination directory is not properly configured. This May Be Caused by a problem with file or directory permissions. More information is available in the system log.

It is said that the write permissions are missing in a file or directory, but in which exactly is it?

The theme change I made at this URL:

    /admin/appearance/settings/Colihaut

I use the Theme Colihaut and have Backdrop in the subdirectory:  /cms/backdrop/

**Comment by AlexL777** [comment]
Has just done. I have some directories assigned the write permission and then my green design from the Theme Colihaut could reappear.

**Comment by quicksketch** [comment]
> It is said that the write permissions are missing in a file or directory, but in which exactly is it?

The "destination" directory in this case was whatever directory you had configured to be your "temporary" directory. What directory this is depends on the setting Backdrop detected from PHP, or manually entered at `admin/config/media/file-system`. But it sounds like you have worked it out. :+1: 

Thanks again for filing all these issues. If this problem isn't solved yet, please reopen. Thanks!
