### ISSUE TITLE
Can not add class to Main page content block

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1218]
Can not add class to Main page content block:

![class1](https://cloud.githubusercontent.com/assets/13515302/9931746/14cebfea-5d47-11e5-803e-b1f57452b21d.gif)

![class2](https://cloud.githubusercontent.com/assets/13515302/9931751/2023fd1a-5d47-11e5-8acd-159e696955ce.gif)

**Comment by docwilmot** [comment]
Confirmed
The form works (I thought that's what @bd0bd meant, that it didnt work) but on view, custom block classes are not attached to the block at all.

**Comment by docwilmot** [comment]
But if you make it a dynamic block, the custom class appears. Is this intentional?

**Comment by quicksketch** [comment]
> But if you make it a dynamic block, the custom class appears. Is this intentional?

I think this may have been reported before. We do intentionally skip the printing of the wrapper on the system content block. There is a template in /core/modules/system/templates/block--system--main.tpl.php that specifically removed wrappers.

However, I feel like what we should do is make this template a little smarter and print a wrapper if custom classes have been attached. How would that sound?

**Comment by docwilmot** [comment]
Yes I think the user would expect to be able to add classes to main block, even if the UI didnt already suggest this was possible.

**Comment by bd0bd** [comment]
I have 1, 2 or 3 columns.
I need to add my own classes to both sidebars and, of cause, to the main body.
I understand that it is possible to solve my matters in different way but the best and most simple way - to have this possibility (adding class to the main block).

For example I have two columns on my page. I would like be able to easily change both columns width.
For main body column by adding class - **seven** and for sidebar - **five**.
Seven - width: 58.33333%;
Five  - width: 41.66667%

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1079 that allows the system block to have custom classes.

> For example I have two columns on my page. I would like be able to easily change both columns width.

Let's handle this issue separately. Adding classes to the regions would both be powerful and dangerous. In the mean time, I'd suggest making custom layouts by copying a layout from `/core/layouts` into `/layouts` and customizing it there.

**Comment by Graham-72** [comment]
>  I'd suggest making custom layouts by copying a layout from /core/layouts into /layouts and customizing it there

We need to compile an easy-to-follow tutorial from words of advice like this. I think this is now a matter of some urgency - or is it covered someplace?

**Comment by quicksketch** [comment]
> or is it covered someplace?

We have a good start by @docwilmot at https://api.backdropcms.org/layouts. Though this covers writing a layout from scratch rather than modifying an existing one.

**Comment by bd0bd** [comment]
>
Adding classes to the regions would both be powerful and dangerous. 

Does it mean there will not be an option to add class to the main body?

**Comment by quicksketch** [comment]
> Does it mean there will not be an option to add class to the main page content block I talk here about?

We can definitely add the option to support a class on the main content block. It's a bug that there is a field to enter a class but it doesn't do anything. The pull request at https://github.com/backdrop/backdrop/pull/1079 will fix it.

**Comment by Graham-72** [comment]
>We have a good start by @docwilmot at https://api.backdropcms.org/layouts. Though this covers writing a layout from scratch rather than modifying an existing one.

Yes, an excellent guide.
Where do we discuss and comment on documentation, and submit contributions? I would like to offer something about modifying layouts.

**Comment by bd0bd** [comment]
>
We can definitely add the option to support a class on the main content block. It's a bug that there is a field to enter a class but it doesn't do anything. The pull request at backdrop/backdrop#1079 will fix it.

I see now. Thank you! It would be good. Right now I am forced to directly edit layouts to add divs & classes to the main content block.

**Comment by quicksketch** [comment]
> Where do we discuss and comment on documentation, and submit contributions?

We haven't enable login on backdropcms.org or api.backdropcms.org (but that is a plan for the near future). However just send us an e-mail info@backdropcms.org and we'll get you invited. Issues for discussing changes to the API site are at https://github.com/backdrop-ops/api.backdropcms.org/issues

@bd0bd We'll get this into the next bug-fix release 1.2.2. Our schedule for bug-fix releases are "as-needed", so it may be a few weeks (or a month) before the next release. It depends. In the mean time you can manually apply the fix to your own installation of Backdrop by applying the patch from https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1079.diff

**Comment by klonos** [comment]
>> Where do we discuss and comment on documentation, and submit contributions?

> We haven't enable login on backdropcms.org or api.backdropcms.org (but that is a plan for the near future).

I think that down the line, we should have some sort of publishing workflow (using for example Rules, Workflow, State Machine etc.)?

**Comment by bd0bd** [comment]
>
We'll get this into the next bug-fix release 1.2.2. 

Thank you very much!

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1079.
