### ISSUE TITLE
Installed PureCSS theme but it does not appear on the Appearance page

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1219]
Installed PureCSS theme but it does not appear on the Appearance page.
But the theme was successfully uploaded to the **themes** folder.

![pure_css1](https://cloud.githubusercontent.com/assets/13515302/9933542/2c4869ac-5d54-11e5-8793-e5dde037ec13.gif)

![pure_css2](https://cloud.githubusercontent.com/assets/13515302/9933561/4cb658ca-5d54-11e5-975d-0c5abea5d750.gif)

![ftp](https://cloud.githubusercontent.com/assets/13515302/9933574/64e4ab40-5d54-11e5-8834-dbb561320fff.gif)

**Comment by biolithic** [comment]
Yea, I just tested it and it doesn't show up in 1.2 Backdrop CMS core
download.
It was working when I uploaded it to 1.1 -- let me see what went wrong.

Thanks for posting!

**Comment by docwilmot** [comment]
Hi @bd0bd 
It would still be best if you've found an issue specific to a particular module, theme, layout that please you post your query to the project's issue queue. In this case can you continue in the PureCSS issue queue please?
Thanks

**Comment by klonos** [comment]
> In this case can you continue in the PureCSS issue queue please?

...which is here: https://github.com/backdrop-contrib/pure_css/issues
