### ISSUE TITLE
Insert image pop-up does not show up in Maximize editor mode

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1221]
Insert image pop-up does not show up in Maximize editor mode.
But if we Minimize it then we can see the pop-up.

![maximize](https://cloud.githubusercontent.com/assets/13515302/9935268/5304b87a-5d5e-11e5-927a-a43c1e66bc68.gif)

**Comment by docwilmot** [comment]
Confirmed.
Its there but under the editor; doesnt show up unless you give it a z-index of 9995 or more. 
This is one for @quicksketch.

**Comment by quicksketch** [comment]
Hm, well as the z-index is set by CKEditor, the easiest solution sure would be to set the z-index of the dialog to exceed CKEditor.
