### ISSUE TITLE
[UX] Config page: Add subtle colors to config section?

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1224]
Just a quick idea I got from #1178. **How about applying some subtle but unique colors for each config section?** Your eyes will more easily associate a color to a section and you'll better orient yourself.

I don't mean coloring the whole page or anything like that. Here's a terrible but quick implementation of what I mean.

For example, when you're on the config page, you'll spot green associated with "Administration" (Yes, my pics don't match. I did it quick)

![config](https://cloud.githubusercontent.com/assets/14132746/9952572/ea12b9ae-5d9c-11e5-944f-2afc1295b53a.png)

Then, whenever you go to any page under "Administration" you'll see green as well. In time, you'll quickly know where you are simply from the colors. Ex: if you see light pink, you'll know you're under content authoring, gold and you're under Media.

![admin-bar](https://cloud.githubusercontent.com/assets/14132746/9952571/ea115dd4-5d9c-11e5-9f3f-5de737628ea5.png)

The colors should be subtle and calm so it doesn't overpower. Maybe pastel-like colors?

I don't know where exactly we can add the subtle color. My quick sketch simply added a border line under the section name. Maybe another alternative can be coloring the icon and the section name itself.

Anyway, throwing it out there.

**Comment by quicksketch** [comment]
Not sure about this. Although I've got a little design history, I think @dariusgarza's input here would be most appreciated, as the mastermind behind our current admin theme and branding.

A technical consideration of course: how would we make these colors and where would they be defined? Maybe just in the Seven theme? And if a module introduces a new section, then how would we colorize it?

**Comment by sutibun** [comment]
Maybe we can get the color palette by extracting them from a nice image we like.

Method 1: Extract from an image
---
Source image: https://www.flickr.com/photos/grafixer/6753753689/ (it's a Chinese dragon)

[Generated color palette](http://www.cssdrive.com/imagepalette/index.php): 
![palette](https://cloud.githubusercontent.com/assets/14132746/9953455/97070d82-5da6-11e5-90b4-1079a9fbd53a.png)

Method 2: Steal
---

Or, we can find [color palettes online](http://www.colourlovers.com/palette/3095205/❛_DRAGON_ICE_CREAM_❜) that we like.

Just an idea.

Too bad drop the dragon is black and white.

**Comment by klonos** [comment]
> Not sure about this.

Yeah, not sure about this either. Leaning towards nope. Sorry.

...but should give credit to this idea:

> In time, you'll quickly know where you are simply from the colors.

Which is more or less the idea behind the various "weights" of the icons used in [Rubik](https://www.drupal.org/project/rubik):

> **Calibrating icons to the task at hand**

> A particularly strong influence on the new icons in Rubik was an idea from [KDE Oxygen](http://www.oxygen-icons.org/) - to vary color saturation by the importance of the task presented to the user:

>> “Normal” colors … are used mostly for mimetypes, folders, system applications, and actions. Vibrant colors are more saturated and used to emphasize important action icons on a toolbar, for rich media mimetypes, for application icons and, generally speaking, used when there is need to focus the attention of the use on a particular element, helping the user to find his way by following a “subliminal” color language.

> While it may sound overly theoretical (I remember thinking this myself when reading the idea for the first time a few years ago), in practice it is spot on: imagine the chaos that would occur if your file and folder icons were as bold as the “Firefox” icon.

> ![drupal-themes-rubik-icon_categories](https://cloud.githubusercontent.com/assets/2423362/9962157/b0b34db0-5e67-11e5-8f14-dd0b3e99b1a3.png)

> Rubik applies this idea to Drupal and begins categorizing administrative pages into several groups:

>- Essential content management and system management pages
>- Build/task pages where you create or manipulate new site building structures
>- Informative pages like reports or logs
>- Configuration pages where users adjust settings

>The end result is a much more balanced set of icons where the most common and critical administrative tasks stand out visually from the rest.

**Comment by Dinornis** [comment]
Good suggestions, but probably best suited for a contrib theme.

**Comment by bd0bd** [comment]
I think it is not good idea to add colors to the admin theme.

The current one is very very nice - big thanks to @dariusgarza!

Well, I am kind of a website designer for about 20 years :smile:

**Comment by docwilmot** [comment]
OK that seems to be everyone against (including me). Closing.
