### ISSUE TITLE
Question: what is file name to edit menu css

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1226]
May be somebody would explain me:

Can not understand what is files name where I can eliminate these 2 divs around menu:

```
<div class="block block-system-main-menu block-menu">
<div class="block-content">

<ul class="menu clearfix"><li class="first leaf"> ...

</div>
</div>
```

What this is needed for in core/modules/system/templates/header.tpl.php

```
<?php if ($menu): ?>
<nav class="header-menu">
<?php print $menu; ?>
</nav>
<?php endif; ?>
```

if actually I do not have this menu in my header.

Thank you!

**Comment by quicksketch** [comment]
> Can not understand what is files name where I can eliminate these 2 divs around menu:

You actually do not need to modify any code in this case. You can configure the block and change its Style to "Dynamic". Then you can remove both the wrapper and the content wrapper DIVs:

![screenshot33](https://cloud.githubusercontent.com/assets/100206/9974412/d7403e06-5e4a-11e5-8af6-68a02ed3ad6c.png)

However, if you wanted to modify the standard block template, you can copy the `block.tpl.php` file from `/core/modules/layout/templates/block.tpl.php` to your theme's directory. Then clear your Backdrop caches under `admin/config/development/performance` for the new template to be picked up from your theme.

**Comment by bd0bd** [comment]
@quicksketch, thank you!
I did not new about this possibility and all these divs all over the site HTML were my headache.
cause I try to fully customize my HTML.

But a new problem arise after a dynamic block implementation - the navigation settings disappeared.
I will report it apart in a new issue.

But would be grateful if you could tell me what this menu block is needed/intended for:

      <?php if ($menu): ?>
      <nav class="header-menu">
      <?php print $menu; ?>
      </nav>
      <?php endif; ?>

**Comment by quicksketch** [comment]
> But would be grateful if you could tell me what this menu block is needed/intended for:

If you have enabled the display of a menu within the header block, then those lines print out the menu used in the header.

![selection_006](https://cloud.githubusercontent.com/assets/100206/9983873/515e4afa-5fc9-11e5-8314-cdc00c973731.png)

In the Bartik theme (the one used on new installations), this prints out the account login/logout menu:

![selection_006](https://cloud.githubusercontent.com/assets/100206/9983880/765f0b3c-5fc9-11e5-996d-b6da3f29a17a.png)

**Comment by bd0bd** [comment]
Yes, thank you!

**Comment by quicksketch** [comment]
Super, I fixed the second screenshot (I had linked the same one twice somehow). Cheers!
