### ISSUE TITLE
Navigation block's Contextual Links disappear after removing wrappers using "Dynamic" display style

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1227]
It is with Bd 1.1.3.
After switching to **Dynamic** style and ordering **No wrapper** for Wrapper and Content tags the navigation block's settings disappeared.

![nav1](https://cloud.githubusercontent.com/assets/13515302/9975905/4d50b9aa-5ed6-11e5-9ebe-9618537ae89c.gif)

![nav2](https://cloud.githubusercontent.com/assets/13515302/9975908/564e48f6-5ed6-11e5-8310-589877f9ab51.gif)

![nav3](https://cloud.githubusercontent.com/assets/13515302/9975909/5c82dd68-5ed6-11e5-902b-fd143ec49f1a.gif)

![nav4](https://cloud.githubusercontent.com/assets/13515302/9975912/65e6016e-5ed6-11e5-8d35-e5a30229d19d.gif)

**Comment by bd0bd** [comment]
Addition: but the settings are there on the Views pages - Article and Book.

**Comment by sutibun** [comment]
@bd0bd I have nothing to contribute here. Just wanted to point out, "yay, I'm starting a trend with the use of  'Bd' vs 'Backdrop'" ^\_\_^

**Comment by quicksketch** [comment]
Thanks @bd0bd for filing this issue. This could be a tricky one to fix. Without any wrappers, the contextual links have nothing on which to anchor themselves. They are probably still on the page, but without a wrapper they probably ended up all the way in the upper-right corner of the window instead of on the block.

**Comment by docwilmot** [comment]
Why do remove the wrappers on that block?

**Comment by bd0bd** [comment]
>
Why do remove the wrappers on that block?

If regarding me, this is because I do not need the wrapper with default classes.
I need wrapper with single class only - **row**:

    <div class=""row">
            <nav>
                <ul class="menu clearfix">
                    <li class="first leaf"><a href="/" title="">Home</a></li>
                    ...
                </ul>
            </nav>
    </div>

**Comment by BWPanda** [comment]
People should be free to change Backdrop's classes/markup as they desire, but they should also understand that doing so may break things. Closing as works as designed unless somebody objects.
