### ISSUE TITLE
In Dynamic block it adds unnecessary classes

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1228]
Bd 1.1.3
Default Layout

I do not know if it is a bug.
I need to get rid of default system divs & classes.
How I can understand from @quicksketch - https://github.com/backdrop/backdrop-issues/issues/1226 -  it could be achieved by using Dynamic styled blocks.
I have done this:

![dynamic1](https://cloud.githubusercontent.com/assets/13515302/9976568/ba106030-5ef0-11e5-9cf0-e2d3715c8a72.gif)

But additionally to my class - **row** it added two system classes - **block** & **block-block-1** in **Wrapper tag**:

```
 <footer class="l-footer">
 <div class="block block-block-1 row">
 <div class="copyright">
 <p>Copyright 2015 Company Name</p>
 </div>
 </div>
 </footer>
```

But I expected it to be like this:

```
 <footer class="l-footer">
 <div class="row">
 <div class="copyright">
 <p>Copyright 2015 Company Name</p>
 </div>
 </div>
 </footer>
```

How you can see **Content tag** is ok - no any system classes were added to my class - **copyright**.

Would be grateful if somebody would tell me where and how to block the system classes output in blocks **Wrapper tag**.

Thank you!

**Comment by bd0bd** [comment]
I think it is a bug when system class is added in dynamic block.
In my mind a dynamic block should be purely custom - without adding any system's classes.
I am not right?

**Comment by quicksketch** [comment]
>  In my mind dynamic blocks should be purely customized classes - without adding any system's classes.

We'd need to make this a feature rather than just removing the existing classes (for sites that have already started using the built-in classes). We might take the same approach as Views and just include a checkbox for "Include default classes" that can be unchecked. Let's make this a feature request.

**Comment by quicksketch** [comment]
> Would be grateful if somebody would tell me where and how to block the system classes output in blocks Wrapper tag.

In the mean time you can block these classes by adding a theme preprocess function your theme's template.php file. These functions modify the list of variables before they are sent to templates.

If you wanted to prevent these default classes on both normal and dynamic style blocks you'd need two preprocess functions because block.tpl.php and block-dynamic.tpl.php are separate templates:

```php
function mytheme_preprocess_block(&$variables) {
  mytheme_remove_default_classes($variables);
}
function mytheme_preprocess_block_dynamic(&$variables) {
  mytheme_remove_default_classes($variables);
}
mytheme_remove_default_classes(&$variables) {
  $block = $variables['block']
  $remove_classes = array('block', backdrop_html_class('block-' . $block->module . '-' . $block->delta));
  $variables['classes'] = array_diff($variables['classes'], $remove_classes);
}
```

Replace `mytheme` with the name of your theme (e.g. `bartik`).

**Comment by bd0bd** [comment]
>
We'd need to make this a feature rather than just removing the existing classes (for sites that have already started using the built-in classes).

I understand you.
Thank you!

>
In the mean time you can block these classes by adding a theme preprocess function your theme's template.php file. 

Cool. Thank you very much!

**Comment by bd0bd** [comment]
Something is wrong. I get this error:

Parse error: syntax error, unexpected '$remove_classes' (T_VARIABLE) in /themes/bartik/template.php on line 11

My template.php (in my **themes** folder, not in core's **themes**)

    <?php

	function bartik_preprocess_block(&$variables) {
	  bartik_remove_default_classes($variables);
	}
	function bartik_preprocess_block_dynamic(&$variables) {
	  bartik_remove_default_classes($variables);
	}
	function bartik_remove_default_classes(&$variables) {
	  $block = $variables['block']
	  $remove_classes = array('block', backdrop_html_class('block-' . $block->module . '-' . $block->delta));
	  $variables['classes'] = array_diff($variables['classes'], $remove_classes);
	}

	/**
	 * Implements hook_preprocess_maintenance_page().
	 */

**Comment by biolithic** [comment]
missing a semi-colon.  Should be this:

function bartik_remove_default_classes(&$variables) {
  $block = $variables['block'];

**Comment by bd0bd** [comment]
@biolithic, thank you very much! But I do not understand where this should be placed in :)

**Comment by bd0bd** [comment]
I see now :)

**Comment by bd0bd** [comment]
It does not help!

**Comment by quicksketch** [comment]
> OK! Everything is ok. It works!

Yay, great. Well this is an adequate work-around until we add this as a feature (if that should happen). I considered this when we first wrote Layout module, but whenever I was in doubt I left out the feature. We can always add things. Removing features is a lot more difficult.

**Comment by BWPanda** [comment]
How long should feature requests stay open without updates before we close them...? I'm going to guess 4+ years is plently of time. Closing, but feel free to reopen if you still want this feature, or if you're willing to work on implementing it.
