### ISSUE TITLE
Add BrowserStack and JetBrains sponsorships to our README.md

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1230]
We recently applied (and received) an Open Source license from [BrowserStack](http://www.browserstack.com), which allows testing of pretty much every platform and browser combination possible, including platforms that are particularly difficult to test: iOS, Android, Apple Safari, and various Internet Explorer versions.

In exchange, they request that we mention them on our project README.md. This is a fair exchange to gain such a useful tool, and it will help notify developers that they have access to this tool if they are a Backdrop contributor.

We also mention *every* week on the video calls the availability of PHPStorm licenses from JetBrains. Why don't we add this as well so that we can stop mentioning it every week. :smile:

**Comment by Graham-72** [comment]
I agree. I find PHPStorm invaluable even though I think I use just a fraction of its capabilities. I would very much like to use BrowserStack please.

**Comment by quicksketch** [comment]
How does this look?

https://github.com/backdrop/backdrop/pull/1080/files?short_path=04c6e90

**Comment by jenlampton** [comment]
I think saying "by developers" might be too exclusive.
```
Backdrop thanks the sponsorship of the following services and products which may be used by Backdrop contributors to build and improve the project:
```

**Comment by quicksketch** [comment]
Great, I fixed it a little to remove so many commas and be accurate that these companies are providing sponsorship *through* services and products:

> Thanks to the following companies for providing sponsorship through services and products, which may be used by Backdrop contributors to build and improve the project:

**Comment by jenlampton** [comment]
You can also remove that last comma :)
