### ISSUE TITLE
Clones in the editor's toolbar

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1232]
From Bd 1.1.3 to Bd 1.2.1.

3 clones in the bar.
It is only in Article Views pages.
All other pages - ok.

![edit](https://cloud.githubusercontent.com/assets/13515302/9980811/5cc6e416-5faf-11e5-8680-050dfa9dfaad.gif)

**Comment by quicksketch** [comment]
Huh, wow I wonder how that happened. So this only happens when editing an article content type, but not when editing a page content type?

**Comment by bd0bd** [comment]
Yes, this happens only if editing or adding a new Article content type.
All other pages - everything is ok.

**Comment by quicksketch** [comment]
Do you have any guesses as to when this started happening? Or under what conditions this can be reproduced?

**Comment by bd0bd** [comment]
Everything was ok with 1.1.3.
Then I have installed 1.2 and admin bar and editor disappeared (I have reported here this issue)/
Then I have reinstalled 1.1.3.
Then installed 1.2.1 and discovered this problem.
May be it has relation to Article Views - still there is this problem (can not cancel)

![1](https://cloud.githubusercontent.com/assets/13515302/9984971/80ac6b04-602b-11e5-9d12-066caacb377e.gif)

**Comment by bd0bd** [comment]
UPDATE: I was able to cancel it now. It works.

**Comment by bd0bd** [comment]
Well, this is not a problem for me. It is ok to have clones.

**Comment by bd0bd** [comment]
One more clone. In Webform pages:

![clone](https://cloud.githubusercontent.com/assets/13515302/10049251/652c1870-621f-11e5-8e04-640ad1270fe4.gif)

**Comment by quicksketch** [comment]
Thanks @bd0bd. I've figured out what the source of this problem is. It looks that if you have multiple text areas on the same page, then you end up with CKEditor getting bound to each editor once per text area. So if you have 3 textareas, then you end up with 3 sets of duplicate buttons.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/1084 that fixes this issue.

**Comment by quicksketch** [comment]
This fix will be in 1.2.2. Thanks for all these reports @bd0bd! They're helping make a better Backdrop. :smile:
