### ISSUE TITLE
Database is so BIG - how to clean it and prevent growing?

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1235]
Database is growing like a crazy.
It was about 10 mb and in few days it became 125 mb!
What we can delete in the database without fear to damage the site and prevent future growth?
Thank you!

Hm, it was 125 mb 2 hours ago and now it is 90 mb - fantastic. Do not understand.

**Comment by quicksketch** [comment]
>  It was about 10 mb and in few days it became 125 mb!

The most likely location for most of this size is in the cache_* tables, especially if you're noticing that the numbers go up and down over time. If you have the page cache turned on under `admin/config/development/performance` (which you should) then every page visited by an anonymous user is saved in the `cache_page` table.

Backdrop also stores a good amount of information in the `tempstore` table, which is temporary data kept for a period of time. For example if you're editing a Layout or View, a temporary copy of the in-progress changes are saved there until you click either the "Save" or "Cancel" buttons.

If you click the "Clear all caches" button on the performance page, it will truncate *all* the `cache_*` tables. You can also truncate the `tempstore` table if you want, but it will discard all in-progress forms on your site.

Both `cache_*` and the `tempstore` tables are automatically cleaned up after a period of time to remove cache entries that have become too stale.

**Comment by bd0bd** [comment]
Thank you very much!

**Comment by bd0bd** [comment]
@quicksketch,
I do not cache pages for anonymous users and I have clicked "Clear all caches" button.
Now my database is even bigger - over 200 mb.

May be **whatchdog** do clean up?

**Comment by quicksketch** [comment]
> May be whatchdog do clean up?

Yes the watchdog table can also be cleared at any time. You can also clear it manually by visiting `admin/reports/dblog` and clearing the log messages from the UI. If you're getting a lot of log messages, it's also a good idea to read through them and see if you can prevent the problems from being logged in the first place.

**Comment by bd0bd** [comment]
It does not help. Database is growing - 220 mb now.

**Comment by findlabnet** [comment]
You can check which table(s) growing in `'your_db_name'` with this simple query:
```sql
SELECT TABLE_NAME AS 'Table name',
round(((data_length + index_length) / 1024 / 1024), 2) AS Size_in_MB
FROM information_schema.TABLES 
WHERE table_schema = 'your_db_name'
ORDER BY Size_in_MB DESC
```
So you can know module(s) which produced this data.

**Comment by bd0bd** [comment]
@findlabnet, thank you!
I do not know how to do this check in phpMyAdmin.
I have manually found that search_index table has a lot of content and I have deleted all this content (not the table). Also I have deactivated the Search module (I do not have any search on the site).

**Comment by bd0bd** [comment]
Sorry for so big picture :)
Here we can see the database is not big - ok, may be 10 mb.
But actual size is about 170 mb - how it is possible? :)

![data](https://cloud.githubusercontent.com/assets/13515302/10120358/a1e4d976-64bf-11e5-9a6f-e0153eaca535.gif)

**Comment by findlabnet** [comment]
Seems like normal behavior of InnoDB (MySQL engine) with default settings. Can be caused insufficient size of RAM on server - not removed temporary tables, big indexes and so on. 
You can find some idea by searching "InnoDB not releasing disk space after deleting data".
Anyway, such researches is overload for this (already closed) issue.

**Comment by bd0bd** [comment]
@findlabnet, thank you very much for the advice!
I will try.
I apologize for the delay in answering.
