### ISSUE TITLE
Update .htaccess file to reflect more modern PHP features

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1236]
Our .htaccess file includes several lines that are largely irrelevant. Several PHP options have been deprecated in PHP 5.3 and removed in PHP 5.4 and higher, such as "register_globals" and "magic_quotes_gpc".

These options have been disabled on every host (literally) for the last decade because of how dangerous these options are. We should remove these irrelevant lines.

Additionally, a newer PHP option `max_input_vars` was introduced in PHP 5.3 but defaults to a value (1000) much to low for a complicated Backrop site.

Let's clean up all these values to reflect a more modern PHP setup (i.e. one that doesn't accommodate for PHP versions prior to 5.3).

**Comment by serundeputy** [comment]
`PR`: https://github.com/backdrop/backdrop/pull/1083

**Comment by serundeputy** [comment]
`PR` updated with the latest and greatest and a rebase ta boot;

**Comment by quicksketch** [comment]
Thanks! Merged in https://github.com/backdrop/backdrop/pull/1083.
