### ISSUE TITLE
CKEditor - align a table horizontally on the page

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1237]
I don't seem to be able to align a table horizontally on the page. Is this meant to be possible with CKEditor?

**Comment by quicksketch** [comment]
I'm not sure about this functionality; I'll have to check. Perhaps in the mean time, you'd just want all tables in your body content to center-align and could just globally do this with CSS?

**Comment by Graham-72** [comment]
It seems that CKEditor is adding align = “center” which works in the edit window and in IE but not in Firefox, Chrome or Safari.

So I am adding an optional class tableC with left and right margins 100%, as well as align = “center”.

Incidentally, it is so much easier to add custom styles in this core version of CKEditor - thanks.

**Comment by BWPanda** [comment]
Guessing this has been fixed now. Question has been answered in any case.
