### ISSUE TITLE
h2 does not apply in a block

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1239]
If I change title (in my text in editor) from **strong** into **h2** then after saving the block this title is getting back to **strong**. But it should be **h2**.

Editor: Full HTML

**Comment by quicksketch** [comment]
By default I don't think `<h2>` is allowed in the "Filtered HTML" format. If you'd like to make it allowed, then visit your text format configuration and add `<h2>` to the list of allowed tags:

e.g. at `admin/config/content/formats/filtered_html`:

![screenshot41](https://cloud.githubusercontent.com/assets/100206/10005961/706158bc-6077-11e5-8b47-5eeea87edc21.png)

> Editor: Full HTML

Hmm, that's odd. Full HTML shouldn't have any filtering on it at all. Though of course you can change this setting, so the filtering may have been turned on.

By default CKEditor isn't enabled on Full HTML. I'm guessing you've turned on the editor on this format.

**Comment by bd0bd** [comment]
Well, I have deleted the block and created a new one - everything is ok now.
I do not know why this problem was but may be because of the editor.
Thank you!

**Comment by quicksketch** [comment]
Super!
