### ISSUE TITLE
Applications for subsystem or core-module maintainership

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#124]
People who want to become subsystem or core-module maintainers for Backdrop CMS should apply here. 

Please state your personal goals for Backdrop, as well as the core module or sub-system you'd like to maintain.

Please note: serious applicants must have a proven track record of contributing to the project (pull requests) and be open to having a conversation about the application process.

**Comment by serundeputy** [comment]
ooh; pick me;

**Comment by jenlampton** [comment]
@serundeputy is there a specific subsystem you are interested in maintaining?

**Comment by serundeputy** [comment]
@jenlampton User module

**Comment by stpaultim** [comment]
Has the thinking on this changed. I don't recall hearing anything about about subsystem or core module maintainers in the last year. Do they exist or did this idea fall by the wayside (at least for now)?

**Comment by stpaultim** [comment]
FYI - I just raised this issue on the DEV call today and as expected, it sounds like this was put on hold mostly because we just don't seem to have the number of core contributors that would make this possible or even helpful. Maybe someday in the near future..... :-)

**Comment by BWPanda** [comment]
Will close for now then.
