### ISSUE TITLE
Speed up backdrop_find_theme_functions() by searching a filtered list of functions

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1240]
In [backdrop_find_theme_functions()](https://api.backdropcms.org/api/backdrop/core!includes!theme.inc/function/backdrop_find_theme_functions/1) we currently run `preg_grep()` on every theme function pattern against the full list of functions.

On a site I was working on recently, the site had about 6000 functions defined, but only about 30 of those were theme overrides that matched a pattern.

We could speed up the process of finding theme functions dramatically if we filtered the list of thousands of functions down to just those that applied within a theme before we ran `preg_grep()`. I'll file a PR shortly to demonstrate.

**Comment by quicksketch** [comment]
Really simple PR filed to https://github.com/backdrop/backdrop/pull/1081.

Before:
![screenshot43](https://cloud.githubusercontent.com/assets/100206/10007089/dd2ec580-607f-11e5-9f65-7fb42073adf4.png)

After:
![screenshot42](https://cloud.githubusercontent.com/assets/100206/10007096/e4f81c30-607f-11e5-9575-534759550f5f.png)

A 487x improvement in this case.

**Comment by dboulet** [comment]
> A 487x improvement in this case.

That’s a nice catch. Will you also file a similar patch for Drupal?

Just wondering, did you also try replacing the call to `function_exists()` within this function with  `in_array()` to see if that made a difference?

**Comment by quicksketch** [comment]
> That’s a nice catch. Will you also file a similar patch for Drupal?

There actually already was a patch for this particular issue that solved the problem differently. I submitted our version over to Drupal as well, as it appears that this approach is 9x faster than what they had come up with separately: https://www.drupal.org/node/2339447#comment-10354975

**Comment by quicksketch** [comment]
> Just wondering, did you also try replacing the call to function_exists() within this function with in_array() to see if that made a difference?

I hadn't tried this. Here's an XHProf diff on using `function_exists()` vs `in_array()`:

![screenshot46](https://cloud.githubusercontent.com/assets/100206/10008020/98176648-6087-11e5-8c09-b0525b1e4bf1.png)

So even though `in_array()` is checking against the much smaller array than the entire function list, `function_exists()` still wins.

**Comment by dboulet** [comment]
> So even though `in_array()` is checking against the much smaller array than the entire function list, `function_exists()` still wins.

That’s what I figured, but thought it was worth a try. The result is counter-intuitive, but makes sense since `function_exists()` is highly optimized in PHP. Great work, @quicksketch.

**Comment by klonos** [comment]
@quicksketch :clap:

**Comment by quicksketch** [comment]
Sweet, well lots of confirmations over in the drupal.org queue. So I've merged this into 1.x and 1.2.x.

**Comment by klonos** [comment]
> ...lots of confirmations over in the drupal.org queue.

Yes! ...noticed that too. Once again... :clap:
