### ISSUE TITLE
Replace views pagers with views_litepagers

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1245]
Views pagers tend to be a performance issue. Can we replace them with views_litepagers in core, or is there a downside to that?

https://www.drupal.org/project/views_litepager

**Comment by quicksketch** [comment]
Well the downside of lite pagers is that they're not the same as full pagers. They don't include the total number of pages or allow you to skip to an individual page number. They only have previous/next.

As an alternative, there is an issue to use a MySQL-only syntax to count the number of pages over in https://github.com/backdrop/backdrop-issues/issues/404. We could use this for both full and mini pagers I believe.

**Comment by jenlampton** [comment]
okay.  I like that approach, as long as we also fix views pagers along with normal pagers.  I'll add a note there.
