### ISSUE TITLE
Add a test to make sure that all core .info file contain "version = BACKDROP_VERSION"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1246]
This is sort of a follow-up to #1241 and I guess similar to #960...

I'm guessing that there will be other modules added in core in the future and while we did solve the specific case with CKEditor and Date, we need to ensure that this does not happen again.

**Comment by quicksketch** [comment]
Great idea. I updated @docwilmot's existing test to expand it to include a version check as well as the type check. PR at https://github.com/backdrop/backdrop/pull/1089.

Unsurprisingly, this also turned up a couple of test modules which had been missing a `version = BACKDROP_VERSION` string.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1089 with the new test.

**Comment by klonos** [comment]
Great! Thanx Nate. One of the things I like about Backdrop compared to Drupal is the response times in the issue queue. Backdrop = :heart:
