### ISSUE TITLE
[DX] Rename the .gitignore file and (optionally) ignore it

### ISSUE THREAD

**Issue by victorkane** [backdrop/backdrop-issues#126]
Just kind of asking before submitting this "crucial" pull request :)
Here's the thing: if I copy example.gitignore to .gitignore, the latter immediately shows up as an un-versioned file upon doing "git status".
There should at least be a line to comment out:

#.gitignore

Has this been discussed before?

Normally, a .gitignore file should be included in a repo if it exists. But this is a software installation repo, and the presence of example.gitignore is what's in the repo.

Another alternative would be just to change example.gitignore to .gitignore and comment everything out by default. After all, if GitHub is going to be the distribution point of concentration...

Interested in people's ideas

**Comment by quicksketch** [comment]
Looks like this was fixed a while back. @hellomrcat opened a new PR at https://github.com/backdrop/backdrop/pull/949, but I don't think the one minor change is necessary. Please reopen if there's anything we missed in these changes. Thanks!
