### ISSUE TITLE
[UX] Improve the "Find Content" admin page so it's more useful for writers (content > find content)

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1261]
The "Find content" admin page isn't very useful for managing content. You have one giant dump that looks clunky.

![find-content](https://cloud.githubusercontent.com/assets/14132746/10119597/d5f8f64e-645f-11e5-98e5-23031c5dec6a.png)

Theoretically, it fits the bill but, for me, I am always using the filters to get a view that to me should be the default. Here is what I have in mind:

![publish-drafts](https://cloud.githubusercontent.com/assets/14132746/10119598/da93e5ba-645f-11e5-8fa4-f8334c0be0cb.png)

Proposed changes
---

- [ ] **Rename "Name" column to "Author"**
    - When I first saw "Name", I had to stop and think for a second what that meant and referred to. Think "author" is easier to understand. Granted, this isn't a big deal but still a minor stumbling block.
- [ ] **Rename "Not published" status to "Draft"**
    - This I am not 100% if it makes sense as a default for everyone.
    - Not only is the word "Not published" long but I think normal users will better understand "Draft" since it's similar to when writing emails. It's either sent/published or a draft.
- [ ] **Separate published and draft/unpublished content to their own listings.**
    - By having a draft listings, I can easily see where I left off or what is being worked on by others.
    - In managing content, I am in two modes.
        1. *looking to view + revise past written content -* Because I do this often, it's annoying to see drafts and having to always filter by published.
        2. *finish up a draft -* Here content type really isn't important. Most of the time, I don't have a huge pile of drafts. I just want to see what I can wrap up and this is why a simple listing is fine. Think back to gmail and count how many you have (me, usually 20 max)
- [ ] **Use tabs that filters by content type as opposed to dropdowns**
    - This isn't shown in my mockup. Got the idea as I was writing
    - Why? The difference between one click and three clicks. Filtering using the dropdown menu/button takes too long when it can be achieved with a tab link that does the filtering. By tabs, I mean like the below image (ignore tabs names)
    
    ![tabs](https://cloud.githubusercontent.com/assets/14132746/10119883/5d1e9274-6469-11e5-8426-0fc607b637d1.png)
    - The first tab (and the default view) is to list all published content regardless of content type.
- [ ] **Add ability to filter by tags/categories**
    - Not shown in mockup. Hit me while writing this
    - Taxonomy is meant to classify and organize so it makes sense to have it here to manage content. However, I'm not sure if a dropdown or a search form is better. I'm leaning towards a search field for the term and a drop down to select taxonomy
- [ ] **Rename "Operations" to "Actions"**
    - I don't know about this but I'm gonna add it here because "actions" is shorter and seems like a simpler word.

**Comment by klonos** [comment]
> [ ] Rename "Name" column to "Author"

:+1: Makes perfect sense to me.

> [ ] Rename "Not published" status to "Draft"
> - This I am not 100% ...normal users will better understand "Draft" since it's similar to when writing emails...

Same feeling there, but leaning towards "draft" too.

> [ ] Separate published and draft/unpublished content to their own listings.

Hmm, not sure about this one. What I would like to see is consistency though:

- either the "Status" column renamed to "Published" and have it be "Yes"/"No"
- or the "Published" drop-down menu have "Status" as label and the entries be "Published"/"Draft"

I feel that "Status" is more flexible so that core provides "Published" and "Draft" out of the box, but these can be extended by various workflow contrib modules to support more statuses.

> [ ] Use tabs that filters by content type as opposed to dropdowns

Not sure either. This could get unwieldy and complex with more content types added and really ugly on small screens. What would be cool though is to replace the simple drop-down menu with something like [Better Select](https://www.drupal.org/project/betterselect):

![betterselect](https://cloud.githubusercontent.com/assets/2423362/10120981/09eba3d8-651a-11e5-98b5-80340da6ddf6.png)

...or [Chosen](https://www.drupal.org/project/chosen) / [Chosen: A jQuery Plugin by Harvest to Tame Unwieldy Select Boxes](https://harvesthq.github.io/chosen/) / [Select2](https://select2.github.io/examples.html):

![chosen-multiselect](https://cloud.githubusercontent.com/assets/2423362/10120991/9413cb08-651a-11e5-9549-1ff6caa8c6c9.png)

PS: we have an issue for Select2 BTW: #459

**Comment by sutibun** [comment]
> - [ ] Separate published and draft/unpublished content to their own listings.
>
> Hmm, not sure about this one. What I would like to see is consistency though:
>
> - either the "Status" column renamed to "Published" and have it be "Yes"/"No"
> - or the "Published" drop-down menu have "Status" as label and the entries be "Published"/"Draft"
>
> I feel that "Status" is more flexible so that core provides "Published" and "Draft" out of the box, but these can be extended by various workflow contrib modules to support more statuses.

I disagree (big surprise ^\_^) to either using drop down menus or a status column. From a purely logical point of view, what you're saying makes sense. In my not so humble opinion, though, this isn't realistic in terms of how normal writers & editors manage content. You are unnecessarily complicating the UI.

BMail: Mail using Backdrop's current content management practices
-----

The best way to show this is comparing this to an imaginary online email site called BMail, not too dissimilar to GMail where

- sent emails = published posts
- draft emails = draft/unpublished posts

Now let's say you are in GMail... er... BMail's archive page ("All Mail") which lists ALL your emails whether received, sent or draft emails. (a giant dump with filters like how it is in Bd) Now imagine the archive page was the only view you had to manage your email.

- Want to check your draft emails and finish the one you worked on last night? Sure, go through the drop-down menu and filter the giant list by "Drafts/Unpublished"
- Want to see the emails you've sent already? No problem. Mess with the drop down and filter by "sent"

At first, this doesn't seem bad. But imagine if you had to check your draft emails every day. Wouldn't messing with the filter controls be annoying? How painstaking would it be to have to always filter just to see received emails?

That is the current UI in Backdrop. Sure, you have form filters but they're not aligned with the way one tends to check email. There's a reason why there's a specific page for Sent and Draft emails. You wouldn't want to keep messing with the filters just to get a view that should be default.

Manage content v2.0
-----

> I feel that "Status" is more flexible so that core provides "Published" and "Draft" out of the box, but these **can be extended by various workflow contrib modules to support more statuses**.

Makes sense because you can have statuses like draft, reviewed, pending, and published. Didn't think about that. **That's why I think there should be a page for each status, published and unpublished/draft.** The admin bar can be modified like

- **Content**
  - Add content
  - *All Content*
  - *Published*
  - *Drafts*
  - Comments

If contrib modules want to extend, they can easily add their custom status to the list.

> This could get unwieldy and complex with more content types added and really ugly on small screens.

You're right. I didn't even think about small screens or more content types.

So, here is my latest version:

![manage-content](https://cloud.githubusercontent.com/assets/14132746/10174954/0257aff6-66b2-11e5-9ab1-683201f05b48.png)

- **Status Page links on top** for easy access. Want to see what drafts are in the works? Go to the Drafts page which lists only drafts. Want to edit past posts? No problems. There's a page listing published content. Want to see all the content? There's a link to the "All content" page.
- **Links on the side to filter by content types** Similar to GMail labels. One click filter because sometimes you already know the content type. Because the content type links are listed vertically instead of horizontally, it scales whether you have 5 content types or 10.
- **Form controls** for filtering the current listing by tags, searching by title and an action drop down. Actually, I like the forms you mentioned. Just imagine they're there on the mockup somehow. The thing to keep in mind is these kind of filters/dimensions (tag, title, etc) are uncommon so having drop-down and other forms is fine.

\*wipes forehead\* Ok... how's that? Better?
