### ISSUE TITLE
[UX] Put the views theme information suggestion code into a textarea

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1265]
It's much easier to copy and paste code when it's in a form field, because then you can triple click, or ctrl-A to select the whole thing.  Let's add the sample views template code in the views UI into textareas for ease-of-copy.

---
PR: https://github.com/backdrop/backdrop/pull/2569

**Comment by klonos** [comment]
What? Where?? Screenies please?

**Comment by quicksketch** [comment]
Huh, I didn't even know views had sample template code, but sure enough. If you click "Theme information" in a view (bottom right corner of the UI), then you can click on a template name and get the current output.

![screenshot53](https://cloud.githubusercontent.com/assets/100206/10124184/0e0310d6-650c-11e5-993d-67b80821324c.png)

![screenshot54](https://cloud.githubusercontent.com/assets/100206/10124185/10e7c9a4-650c-11e5-9447-996ff4872bd4.png)

This second dialog is where a textarea is being recommended. Let's make sure it's got a `readonly="readonly"` attribute set on it. We don't want users thinking they can modify the template directly in a textarea (which while neat would be a huge security concern, and a separate issue).

**Comment by docwilmot** [comment]
> Huh, I didn't even know views had sample template code, but sure enough.

At last! I knew something that @quicksketch didn't!

This is a great idea. How about we add one of those js "click this link/button to copy to clipboard" thingies as well?

**Comment by quicksketch** [comment]
> How about we add one of those js "click this link/button to copy to clipboard" thingies as well?

Unfortunately the only way to do this (afaik) is to use a Flash-based widget. Normal JavaScript doesn't have access to write to the clipboard.

**Comment by jenlampton** [comment]
Let's start with a text area and add all the fancy flash stuff in a follow-up :)  I use these sample code snippets all the time, and really wish they were in a text area (like the views exports are) for easy copy/paste :)

**Comment by Dinornis** [comment]
👎 no Flash stuff, please.

**Comment by jenlampton** [comment]
> Normal JavaScript doesn't have access to write to the clipboard. 

Really? How does GitHub do it?

<img width="543" alt="screen shot 2017-05-08 at 9 41 05 pm" src="https://cloud.githubusercontent.com/assets/397895/25835853/11c270da-3437-11e7-867f-5eb2177160d1.png">

**Comment by herbdool** [comment]
@jenlampton needs a small tweak. I've added a code change request.

**Comment by jenlampton** [comment]
Made the change, back to NR :)

**Comment by herbdool** [comment]
Looks good!

**Comment by klonos** [comment]
This looks good 👍 ...except on wider screens, because of the fixed cols of the text area leaves a white space to the right of the dialog:

![Screen Shot 2019-04-15 at 3 49 54 am](https://user-images.githubusercontent.com/2423362/56097082-4c532900-5f33-11e9-9399-284528daf010.png)

...but that is a problem with the dialogs: #2696 

This can get in with 1.12.6 I believe 🙂

**Comment by docwilmot** [comment]
> the fixed cols of the text area leaves a white space to the right of the dialog:

`style = width: 100%` instead of  columns would fix that i think.

**Comment by jenlampton** [comment]
The code is only 80 chars long, so I think the 82 char width is sufficient.
I'd prefer we make the modals less huge, if possible :) but maybe in
another issue!

**Comment by klonos** [comment]
> `style = width: 100%` instead of columns would fix that i think.

Yes it would.

> I'd prefer we make the modals less huge, if possible :) but maybe in another issue!

Yep, #2696

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2569 into 1.x an 1.12.x. Thanks @jenlampton, @klonos, @herbdool, and @docwilmot!
