### ISSUE TITLE
 Small typo in settings.php file

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#1266]
lines 191 and 192:
- $config_directories['active'] = '/home/myusername/config/active';
- $config_directories['staging'] = '/home/myusername/config/active';

I think the line 192 should be
- $config_directories['staging'] = '/home/myusername/config/**staging**';

**Comment by klonos** [comment]
Good catch @amilenkov

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1091. Thanks @saintlynn! And thanks @amilenkov for the report.
