### ISSUE TITLE
[UX] Prevent people from using a path alias that matches a known system path

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1269]
Over in https://github.com/backdrop/backdrop-issues/issues/1177#issuecomment-140437496 It looks like @bd0bd was able to create the path alias `node`. It occurs to me that doing such a thing could cause serious problems.  We should prevent people from providing path aliases that match known system paths, if we don't already do this.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop-issues/issues/1229
