### ISSUE TITLE
[DX] Use menu theme function to render the menu in the header block (not theme_links())

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1270]
We are currently using `theme_links` in the header block to render the menu, instead of `theme_menu_tree`. The menu_tree function takes into account the settings on each menu item, and adds classes like 'expanded' where needed, but theme_links does not.  In order to add these classes into theme_links, one needs to loop over each item, and then manually load the menu link, retrieve the relevant values, and add the classes where needed. 

Why not use the function that was meant for rendering menus, instead?

Related: https://github.com/backdrop/backdrop-issues/issues/1118

**Comment by quicksketch** [comment]
> Why not use the function that was meant for rendering menus, instead?

Because in the case of the header menu, we only support a single level of links rather than a tree, so items like `expanded` are excluded because it's not intended to be expanded.

However, I'm all for making the output more consistent with other menus. This seems like it may just have unintended side-effects with the current approach.

**Comment by docwilmot** [comment]
May be useful to have `theme_menu_tree` if/when we [include a dropdown menu in core](https://github.com/backdrop/backdrop-issues/issues/1457)?

**Comment by klonos** [comment]
...was about to mention #1457 too. Especially as a reply to this part:

> ...in the case of the header menu, we only support a single level of links rather than a tree...

**Comment by jenlampton** [comment]
> May be useful to have theme_menu_tree...

Not likely, as that only outputs a `UL` tag :(

The problem is that not only are we not providing a drop-down menu in core (yet), we're preventing contrib from using one too (my use case, exactly).  There's no harm in adding classes core doesn't use, but right now the only way to replace this menu in contrib is to render the whole menu a second time, since this rendering can't be prevented. If we were to render it with all those happy little classes the first time, that would be a performance win for everyone who needs a drop-down menu, and a developer-experience win for anyone who has to interact with the menu code on the theme layer :)

**Comment by jenlampton** [comment]
Looks like the 500 second timeout didn't happen again, so removing needs work tag. Unless there's something else that needs changing?

**Comment by quicksketch** [comment]
> The problem is that this approach prevents contrib from using a drop-down (my use case, exactly).

If contrib wanted to modify the menu in the header block, it would need to do so through other means, such as form altering the header block form and writing a different preprocess hook for the block.

> Plus, since we are planning on supporting nested menus in core, we'll be setting ourselves up for success in the future :D

The work at #845 and #1457 both will only affect menu blocks, not the header block. So while we may plan on support drop-down menus in the future, we're not going to put all that more elaborate support into the header block. If you need more than a single level of links, you have to use a menu block.

This issue may be misplaced overall. The header block is intended to have a limited, simplified menu inclusion. If you need a more elaborate menu, you must use a menu block.

**Comment by jenlampton** [comment]
> The header block is intended to have a limited, simplified menu inclusion.

Ah, this means it's supposed to have "Account menu" not any sort of Navigation, correct?

**Comment by jenlampton** [comment]
> If you need more than a single level of links, you have to use a menu block.

Closing this issue since drop-down menus are not supported in the header block.
