### ISSUE TITLE
[DX] Remove the advanced database settings from settings.php

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1271]
We currently have a *very* verbose set of documentation in settings.php related to configuring master/slave setups, multiple database, etc. Most sites only have a single database and don't need the advanced configuration at all. This verbose documentation also pushes down the very important config directory settings.

I'd love to delete all this documentation from our settings.php and move it all to handbook page on api.backdropcms.org.

Sort of related to https://github.com/backdrop/backdrop-issues/issues/1075.

**Comment by klonos** [comment]
> Most sites only have a single database and don't need the advanced configuration at all.

Usually, this is where you'd get me screaming "metrics!", but I'm with you on this one. Our target audience is not load-balanced, multi-database corporate site builders.

**Comment by dboulet** [comment]
I like this idea, too. Personally, I’ve never once used any of the advanced database options for any site.

**Comment by klonos** [comment]
> I’ve never once used any of the advanced database options for any site.

Same here.

**Comment by quicksketch** [comment]
Here's a start on advanced database configuration: https://api.backdropcms.org/database-configuration

It's been nice to start fresh and write accurate docs. It's also an opportunity to describe Backdrop-specific information, such as how to connect to non-MySQL databases (even though they're not supported by core) and how to use the BACKDROP_SETTINGS environement variable, which is what we're using for Pantheon's hosting.

**Comment by serundeputy** [comment]
cool; could we put a link to this (https://api.backdropcms.org/database-configuration) in the new stripped down settings.php?

**Comment by quicksketch** [comment]
Yep, that's what I was thinking!

**Comment by quicksketch** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/1094

**Comment by serundeputy** [comment]
haha; you're too quick; @quicksketch ; @saintlynn it is done;

**Comment by klonos** [comment]
> I’ve never once used any of the advanced database options for any site.

Same here.

**Comment by jenlampton** [comment]
omg yes. :+1:

**Comment by quicksketch** [comment]
Cool, merged in https://github.com/backdrop/backdrop/pull/1094 for the 1.3.0 release.

**Comment by klonos** [comment]
Thanx guys.
