### ISSUE TITLE
Downgrade "Unknown updates" to be notices instead of warnings

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1272]
Update module currently makes a big fuss about "Unknown" updates. This happens all the time for developers who are running the latest dev release of a module. Because these modules (and core) do not have a packaging time set in their .info files, they're displayed as "warning" items by Update module. This in turn sets a warning on the status report page.

We should downgrade this message to a notice so that we're not alerting administrators/developers over a completely normal situation. Screenshots coming soon.

**Comment by quicksketch** [comment]
Before:

![screenshot60](https://cloud.githubusercontent.com/assets/100206/10151784/5816929a-6608-11e5-8771-14bf43197440.png)
![screenshot61](https://cloud.githubusercontent.com/assets/100206/10151788/62aebf66-6608-11e5-822e-23298a0874b1.png)

What I'd like to see instead:
![screenshot59](https://cloud.githubusercontent.com/assets/100206/10151791/69db6ed8-6608-11e5-9d98-1e16176a7885.png)
![screenshot62](https://cloud.githubusercontent.com/assets/100206/10151822/c8de4bd0-6608-11e5-81e5-2b8374a27b80.png)

**Comment by klonos** [comment]
I'm guessing that this was filed in order to sort #1254. It looks fine to me as an interim solution, but long term we should implement #664

**Comment by quicksketch** [comment]
Thanks @klonos, I thought we had issues relating to this but I couldn't find https://github.com/backdrop/backdrop-issues/issues/664. I posted a follow-up there with the current situation.

Indeed this was filed to mitigate the displaying of errors when not enough information is available. We should only display errors/warnings when we know something is wrong, not when a developer is running a perfectly legitimate development (future) copy of the software.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1095. I expect Travis will fail, we should have tests that check the expected output.

**Comment by klonos** [comment]
> We should only display errors/warnings when we know something is wrong, not when a developer is running a perfectly legitimate development (future) copy of the software.

:+1:

**Comment by quicksketch** [comment]
Merged into 1.x for 1.3.0 so that our new notification icon pop up on every developer site.
