### ISSUE TITLE
[UX] Consider adding anchors in the vertical tabs.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1273]
...so that we can link to specific parts of the UI form documentation or help text.

**Comment by quicksketch** [comment]
Could you elaborate a little more? Is this for vertical tabs, or the normal tabs (local tasks) across the top of the page?

**Comment by quicksketch** [comment]
From #1274, it appears you mean Vertical Tabs. This is already supported:

```
        // If the current URL has a fragment and one of the tabs contains an
        // element that matches the URL fragment, activate that tab.
        if (window.location.hash && $(this).find(window.location.hash).length) {
          tab_focus = $(this).find(window.location.hash).closest('.vertical-tabs-pane');
        }
```

So basically you just include an anchor link to anything within the vertical tab you would like to have focused.

**Comment by klonos** [comment]
Yes, for the specific example (would solve #1274 in a "classy" way) I meant pointing to vertical tabs. I realize that (AFAIK) horizontal tabs (local tasks) have a URL of their own, so we don't need anchors in order to link/point to them ...unless of course we need to point to a specific section/fieldset of a very long admin form, in which case we'd having anchors in th various sections/fieldsets would help to that end.

So, yes, but by inspecting the page code I could not find any IDs assigned to the tabs. That's why I filed this issue here. They only have classes (```vertical-tab-item```, ```first```, ```last``` and ```vertical-tab-selected```). Or do we need to point to the respective fieldsets that do have IDs? I've tried for example linking to ```/admin/structure/types/manage/page#edit-comment```, but it doesn't work. How would you link to that specific tab?

**Comment by quicksketch** [comment]
> I've tried for example linking to /admin/structure/types/manage/page#edit-comment, but it doesn't work. How would you link to that specific tab?

I tried exactly this and it worked perfectly, selecting the comment settings tab and jumping down to the top of the vertical tabs element so it was visible. It worked for me in both Chrome and Firefox.

**Comment by klonos** [comment]
...you are right. Just tried again and it did work. Note sure what I was doing wrong. Sorry for the noise :disappointed:

**Comment by klonos** [comment]
...I realize this is long-closed, but FTR and for anyone searching how to do target vtabs with anchors, id's in vtabs are in the respective fieldset instead of the vtab itself 😉
