### ISSUE TITLE
[DX] Document Node passed into theme_username as 'account'.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1275]
Use case: I'm trying to override the `theme_username` function to display a user's name as "First Last" instead of as "Username". There are fields for first and last name on the user object, so as long as the user object is passed into `theme_username` I should be golden.

Unfortunately, on a node, instead of passing the user object into `theme_username`, a node is passed in as the 'account'. 

``` php
$variables['name'] = theme('username', array(
    'account' => $node,
    'link_attributes' => array('rel' => 'author'),
  ));
```

(See https://api.backdropcms.org/api/backdrop/core!modules!node!node.theme.inc/function/template_preprocess_node/1)

I found the same thing happening in Drupal 7:

``` php
$variables ['name'] = theme('username', array('account' => $node));
```

(see https://api.drupal.org/api/drupal/modules!node!node.module/function/template_preprocess_node/7) 

This was obviously a deliberate choice, but I wonder why. What does `theme_username` need to know about the node here? Wouldn't it be more valuable to pass in the user account as 'account'? 

Is this worth changing?

**Comment by quicksketch** [comment]
> What does theme_username need to know about the node here?

It only needs `$node->uid` and `$node->name`. It just so happens that the node object contains the same keys as a user account object, so for the purposes of `theme_username()`, it was enough (for the default implementation).

> Wouldn't it be more valuable to pass in the user account as 'account'? 

It would be more valuable for certain, but right now we're not loading user accounts when we're displaying nodes. This would definitely add some overhead.

I don't like passing in $node as though it were $account at all. However, I do think avoiding a full user load when (by default) we don't need any of that information is an optimization that is worth keeping.

**Comment by sentaidigital** [comment]
node.theme.inc isn't the only place it happens.  There are several places in the node module that pass in a $node or $revision object (`node_search_execute()`, `node_revision_overview()`), and other modules (search, comment, dblog) pass in objects fetched from a `db_select()` joined with the user table to get the name field.

>I don't like passing in $node as though it were $account at all. However, I do think avoiding a full user load when (by default) we don't need any of that information is an optimization that is worth keeping.

I concur passing $node as though it were $account is bad practice.  The `$account` that is passed in to `theme_username()` is sent to `theme_preprocess_username()`, which calls `user_format_name()`, which calls `backdrop_alter('user_format_name', $account)`, which means the code is lying to any module implementing `hook_user_format_name_alter()`.  Or would be, if the hook was documented anywhere.

However, there are more issues with `theme_username()`.  As mentioned in the comments of the [a.d.o documentation page](https://api.drupal.org/api/drupal/includes!theme.inc/function/theme_username/7), the function is documented to accept 'extra' and 'name' parameters, but `theme_preprocess_username()` overrides them without checking if the caller has already set them.

IMHO, fixing the documentation to include the hook and to say the account parameter is not _really_ a User object is the best immediate solution.

**Comment by BWPanda** [comment]
Sounds like this is ultimately some kind of a bug but needs documentation as an immediate solution.

**Comment by bugfolder** [comment]
It looks like `hook_user_format_name_alter` is now documented.

https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.api.php/function/hook_user_format_name_alter/1

But the documentation for `theme_username` https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.theme.inc/function/theme_username/1 still needs updating.

**Comment by bugfolder** [comment]
PR submitted for code review. Since it's documentation-only, testing shouldn't be needed.

**Comment by argiepiano** [comment]
This is true in d7 as well. Although the name of the variable seems to indicate that this should be a user account, in this particular case I believe passing the node is actually on purpose, rather than a bug.

**Comment by argiepiano** [comment]
Oops. I wrote the above before looking at the pr. Ignore my comment above

**Comment by argiepiano** [comment]
LGTM and RTBC.

**Comment by quicksketch** [comment]
Although it's not a comprehensive fix, I think this documentation update is valuable. Thanks @bugfolder and @argiepiano for addressing this old issue.
