### ISSUE TITLE
[UX] Move custom block list to admin/content/block

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1276]
Back when the blocks listing was a mix of system-provided blocks and custom blocks, and when that page was also used for block placement it may have made a little bit of sense that the block administration was under the "Structure" section.

Unfortunately, during user testing (for Drupal 7) it was proven that this does not jive with people's mental model. Custom blocks (where you type in your own words) were certainly, without a doubt, content.

Since we have separated the system-provided blocks from "custom blocks" in Backdrop, and what remains at admin/structure/block is now only what everyone identifies as content, we need to move this listing to admin/content/block.

**Comment by klonos** [comment]
I think that this makes perfect sense from an end-user perspective.

**Comment by mikemccaffrey** [comment]
I agree that the current placement of the menu under structure doesn't make sense since blocks are being treated as content and being stored in the database, and we should definitely do something to clarify this confusing situation.

However, I'm thinking we should actually go the opposite way, leave blocks under structure, and export them to configuration. Blocks don't actually do anything much themselves (as far as I know), and are exclusively placed using Layouts, which are definitely considered configuration.

**Comment by mikemccaffrey** [comment]
Or wait, are we actually planning on removing these custom blocks? https://github.com/backdrop/backdrop-issues/issues/1277#issuecomment-144249393

**Comment by mikemccaffrey** [comment]
I'm still feeling pretty confident that we should leave the current custom block management interface where it is under structure, and instead change the existing module to export its data to config files in #1428.

And then if we create fieldable content block entities in #100, that new module can just add its own menu item under the content section.

**Comment by jenlampton** [comment]
I disagree, there's nothing structural about the current blocks, so they don't belong under the structure part of the menu. Blocks are content (in the mind of our users) so we should put them under the content menu so they can find them. (They should also be on the "Add content" page, but that is another issue!)

**Comment by jenlampton** [comment]
Closing this issue as blocks will remain admin-only.

**Comment by quicksketch** [comment]
Closed per https://github.com/backdrop/backdrop-issues/issues/1428#issuecomment-168583219 for reference.
