### ISSUE TITLE
Rename "Blocks" to "Notes"

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1279]
This has been running in my mind recently but don't know if it makes sense. i.e. seen it through all the angles. So I wanna throw it out there to see what others think.

Given Blocks are now just text (plus images?) and will be filed under "admin > content > block" #1276, I was wondering if Notes might be a better name for Blocks. Notes seems something easier and more tangible for new users. 

When I hear blocks, I think of building blocks. Something you use to build on top of each other to make something bigger. Kind of like Legos. With the new changes, I don't know if this is a suitable mental model now that Blocks is content-related.

![blocks](https://cloud.githubusercontent.com/assets/14132746/10184596/459aedda-6704-11e5-9bbf-b6e1364ae7f7.png)

When I think of Notes, however, I think of sticky notes (er... post its) that you can write and draw on.

![sticky-notes](https://cloud.githubusercontent.com/assets/14132746/10184546/61899c2c-6703-11e5-840d-629ff6dac8ae.png)

The way I am visualizing is: "**You stick/pin _Notes_ (blocks) onto the _fridge_ (layout), and rearrange however you want.**"

I think pinning Notes onto Layouts is a better visual model to introduce new users to, no?

**Comment by quicksketch** [comment]
Hey @sutibun. I'm not sure about this. A "note" in my mind is what I would use within the "Notes" app on an iPhone (or Mac), the Keep app on an Android, or Microsoft OneNote. That is, a bullet list of things to remember or something I should do later. Obviously that's probably not part of most websites, but the terminology could end up causing users to stumble thinking that Backdrop had some sort of traditional Notes-like functionality. There are a lot of words reused in technology of course, but using the word "Notes" I think would be fraught with pre-existing expectations about what functionality they would provide.

**Comment by sutibun** [comment]
@quicksketch ah, didn't think about that.

**Comment by klonos** [comment]
> When I hear blocks, I think of building blocks. Something you use to build on top of each other to make something bigger. Kind of like Legos.

That's the whole point. People can use blocks (small chunks of functionality) to build something bigger (their website). I think we are good with "blocks".

**Comment by sutibun** [comment]
Ah kk. Gonna close ticket then. The mob has spoken :p
