### ISSUE TITLE
Allow Non-Region Layout UI regions

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1280]
I was considering [Move Layout Title Settings to a dialog](https://github.com/backdrop/backdrop-issues/issues/952) and thought that to get this done we have to make the page `$title` variable render a bit like a region in the layout UI, so that we can get a border and a dropbutton. But regions would automatically be open to have blocks in them, which wouldnt make sense, so we'd need some custom code to get this to work.  

But then I thought what if someone else wanted a similar thing later on then? Say there is a `$slider` variable in a layout which the developer wanted to show up in Layout UI, but also not be an area where blocks could be dragged to? Or a layout with any similar fixed area, which isnt a block region but we wanted to be represented in the Layout UI. Like the 'Page Title' now.

Why not make the fix for https://github.com/backdrop/backdrop-issues/issues/952 an API of sorts? An API to render template variables as pseudo-regions, with dropbuttons and settings, with their own CSS, but not accessible to dragging blocks.

What you think?

**Comment by quicksketch** [comment]
Sounds like a good idea to me. We'll need some way of making the title settings button show up, and I think it makes sense that this would be generic functionality rather than a one-off for the title settings.

**Comment by docwilmot** [comment]
Great; could use some ideas on implementation though. Was thinking maybe:
- add a new `hook_custom_layout_ui_region()` we could implement in layout (template) `.php` files.
- there allow 
  - a `region id` which matches the layout template variable, 
  - custom links to be added to the region's dropbutton, which either load a menu callback or a custom callback function, or the dropbutton options could be `$form` options that save to the layout (this would be necessary for the `page_title` options I think) or combinations of these ideas
  - region CSS just for that region?
  - region content?
- then call this hook in `LayoutRendererStandard::prepareRegions()` (or in `LayoutRendererEditor`) and add this as a new region to the `regions` array, probably with some additional key to mark it as a custom region.
- add more code to build the region, dropbuttons etc
- then dont mark such regions as `class="layout-editor-region-content"` so the drag and drop wont work. (Or make this an option if we want people to also be able to alter existing 'normal' regions as well.

Just thinking out loud.

**Comment by docwilmot** [comment]
Postponing this. Thinking more about it, don't see where this would really be very useful, and we probably don't want to be encouraging hardcoded layout regions either. If it becomes a requested feature in the future, can re-open.

**Comment by klonos** [comment]
>...If it becomes a requested feature in the future, can re-open.

Perhaps in the future the available blocks all sit in such a pseudo-region like that called "Available blocks" waiting to be dragged (instead of having to use the "add block" button that opens the dialog). Just a thought,
