### ISSUE TITLE
[UX] Replace "Node" with "Content" in Search Settings

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1282]
If you go to Search Settings ("admin > config > search > settings") under the "Active search modules" section, the word "Node" makes an appearance.

![search](https://cloud.githubusercontent.com/assets/14132746/10214112/a5185d5c-67da-11e5-815d-8334d76825f9.png)

Think it should be "Content".

**Comment by klonos** [comment]
Yeah, I think that we try to avoid using the word "node" in the UI. This must have slipped.

**Comment by sutibun** [comment]
Hope no one minds if I change the milestone to 1.3.0

**Comment by quicksketch** [comment]
@sutibun++

Agreed on this.

**Comment by jenlampton** [comment]
Well, this actually correct as-is since we are asking about the modules. The module's names are "Node" & "User", but I agree it would be better to list "Content" and "User accounts" as the things we'd like to search.

Can reframe the question too, so we don't ask about the modules, but instead the things we want indexed?

**Comment by jenlampton** [comment]
Thinking about this a little more, what each module provides is actually a separate page.  Search/node vs search/user, etc. So we're actually asking actually asking is: 
1) which search pages do you want to provide?  and
2) Which search page should we use by default?

How about this for better questions:
![screen shot 2015-11-05 at 3 37 55 pm](https://cloud.githubusercontent.com/assets/397895/10985109/3e476626-83d3-11e5-9d6d-3b9e38afce88.png)

**Comment by docwilmot** [comment]
Better

**Comment by jenlampton** [comment]
Bah, even though this page is controlling search pages, I don't think anyone who doesn't understand Backdrop/Drupal will put that together, so I think I prefer wording this around the search items.  What about this?
![screen shot 2015-11-05 at 3 47 01 pm](https://cloud.githubusercontent.com/assets/397895/10985255/98d65ef2-83d4-11e5-8f80-b818f58dacbe.png)

**Comment by jenlampton** [comment]
Also, as a follow-up: https://github.com/backdrop/backdrop-issues/issues/1330

**Comment by Graham-72** [comment]
>so I think I prefer wording this around the search items. What about this?

:+1: Much better wording;  I can now understand it without a great deal of thought.

**Comment by quicksketch** [comment]
Much better indeed!

```
Choose which search modules are active from the available modules.
```

:tableflip: What kind of description text was that? Much better now. Merged into 1.x for 1.3.0.

**Comment by sutibun** [comment]
Late to the party but how about

> What items do you want searchable on the site?

Also

... shouldn't the descriptive text come before the radio buttons (or any forms)? I've never seen this arrangement any where else. Seems like a Drupal way of things and, at least to me, **very** unusual.
