### ISSUE TITLE
[UX] Improve "Update action" in URL path settings page

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1286]
If you go to URL path setting page ("admin > config > search > path > patterns > settings") and scroll down to the "Update action" section, you will see the following

![update action](https://cloud.githubusercontent.com/assets/14132746/10215129/a700e2b0-67e4-11e5-992d-698347b9034e.png)

First, the explanation copy should come first not last.

Secondly, the explanation doesn't really explain. Explain better. I'm so confused here as to what is the best choice. Scared this might hurt my site in Google and/or have my visitors visit an old URL and see a 404 page.
- What are the implications of each choice?
- What is recommended? 
- Don't use "alias". Nobody gets it. Stick with using only "URL"

> Considering installing the Redirect module to get redirects when your aliases change.

The redirect module should also be part of backdrop, at least the ability to 301 redirect old aliases to new ones. Let's help our users rank well in search engines AND their site visitors avoid landing on 404 pages when they update the URL. It is avoidable.

From working with real users at a small NPO, they changed the URLs without knowing the impact. We should help novice users here... not simply suggest the answer.

**Comment by quicksketch** [comment]
>  I'm so confused here as to what is the best choice. 

This is the problem. The best choice is Redirect module, but it's not in core.

> The redirect module should also be part of backdrop, at least the ability to 301 redirect old aliases to new ones. 

Agreed.

**Comment by sutibun** [comment]
At the time, didn't realize there was already a ticket to get the redirect plugin into core

**Comment by klonos** [comment]
> Don't use "alias". Nobody gets it. Stick with using only "URL"

Would it make better sense to call these "friendly URLs" or "pretty URLs" or something instead? We cannot simply call them "URLs" because the sentence "Create a URL" would not be 100% accurate since a URL is actually created no matter what (```/node/1```) it's just not... well, not friendly or pretty.

**Comment by sutibun** [comment]
Hmm... to be honest... I don't fully understand alias. And that's kind of the problem.

I, and I figure like most people, do understand what a URL is but at a basic level: it's the webpage location/address you type on the browser. When you try to "create" to different types of URLs... well, it's no wonder it's hard to fully understand.

I'm not saying don't use alias URLs... I'm sure you need them to make Bd work but don't expose them to users. As far as users know, they're only dealing with **one** type URL.. the one that they know and understand.

That's what I mean by stick with using only URL. Introduce alias or some variant name and it's likely you've lost the user.

**Comment by klonos** [comment]
Yep, they are all URLs. It's just that the ones created by the system by default are in the form of ```http://your.site.url/?q=node/1```. If your server supports it and you enable the "Clean URLs" feature (under Configuration > Search and metadata > URL handling), you get URLs like ```http://your.site.url/node/1``` instead (no "ugly" ```?q=```) and now with pathauto and token in core, you can configure "aliases" which are additional URLs in the form of ```http://your.site.url/node/content-title-instead-of-vague-node-number```. It's those URLs I propose calling "friendly URLs" or "pretty URLs" or something that makes more sense than "aliases".

**Comment by klonos** [comment]
So just to clarify:

```http://your.site.url/?q=node/1``` <- system default
```http://your.site.url/node/1``` <- system default with "Clean URLs" enabled (if supported by the server)
```http://your.site.url/custom-title``` <- alias of ```/node/1```
```http://your.site.url/?q=custom-title``` <- alias of ```/node/1``` if "Clean URLs" disabled or not supported by the server

**Comment by klonos** [comment]
...so you have
- "system" or "default" URLs
- "friendly" or "pretty" or "custom" URLs
- "clean" URLs ...which is a form of either the system or the custom URLs that you can get if the server supports it.

**Comment by klonos** [comment]
By the way, in #940 we are trying to figure out the most optimal defaults for pathauto custom URLs. You might be interested in that.

**Comment by sutibun** [comment]
Paraphrasing what you just said
-------

> It's just that the ones created by the system by default are in the form of http://your.site.url/?q=node/1.

So, the URL format Bd starts with has **URL query parameters (?q=node/1)** The basic form.

> If your server supports it and you enable the "Clean URLs" feature, you get URLs like http://your.site.url/node/1 instead (no "ugly" ?q=)

So, if you have "Clean URL" enabled, you get **a slightly improved URL structure that strips the URL query string (node/1)** The "upgraded" form of the basic.

> now with pathauto and token in core, **you can configure "aliases"** which **are additional URLs** in the form of http://your.site.url/node/content-title-instead-of-vague-node-number or simply http://your.site.url/content-title-instead-of-vague-node-number (no /node part).

Since pathauto & token are in core, you reach the best in class: custom URLs. **You can fully customize the default URL structure to your heart's content because your custom URL will point to/reference the master/system/ugly URL** (/?q=node/1 or /node/1)

Possible conclusions?
-----

aah, think I sort of get it. I hope. You're good. Because I think visually, I tried to draw this out to see if I understand it. Is the below correct?

Basically, *Bd has a master URL for each content piece*. If you create a custom URL, (C & E in my diagram) what you're doing is creating a variation that simply points to the master URL. (A, B & D in my diagram) This variant is what Bd calls an alias.

![bd-custom-url](https://cloud.githubusercontent.com/assets/14132746/10272662/03c0b8fc-6ae9-11e5-8c61-2c974252c9fa.png)

If above diagram depicts things correct, let me see if I can make some assertions/questions:

1. **Knowing that path auto & tokens are now in core, would it be correct to say URL structures C and E are the two possible custom URL structure a Backdrop node can have?** (what decides that is if clean URL is supported & enabled)
2. Also, **does the fact that the [Backdrop requirements recommend Apache](https://backdropcms.org/requirements) mean that it's VERY likely that clean URLs will be enabled & supported?** (since Apache servers support clean URLs & clean URL is enabled by default)

Back to naming things
-----

Anyway, if all my above assertions aren't wrong, to simplify things can't we

- name the system/default URL (/?q=node/1 and /node/1) as the "master URL" and rename "alias" (/custom-title or /?q=node/custom-title) to something easier like "alternative" URL. 
  - It's much easier to think of master & alternative URLs for a node. I guess I had a hard time with "alias". I wonder if this will trip normal users like it did me. (other words that came up are variant, alternative, deviant,etc)
- or better yet, *don't even mention anything about a system default/master URL to the user*. In Wordpress, all they have is this:
    
    ![worpress-permalinks](https://cloud.githubusercontent.com/assets/14132746/10273068/407b2762-6af0-11e5-826b-149090f98e22.png)
    
    Maybe for the user, we can hide all the complexity (system default URL, clean URL, etc) and simplify it. In the node edit page, we can have two types of URLs as far as users are concerned. Main URLs and alternative/previous URLS. The latter is for redirects and the former for defining what is the canonical URL. (thought technically, the system default one is /?q=node/1) Below is quick mockup
    
    ![mainurl](https://cloud.githubusercontent.com/assets/14132746/10273493/f10846c2-6af6-11e5-9c6b-f0abf8f309d9.png)

I hope what I wrote makes some sense. Getting a lil' tired.

**Comment by quicksketch** [comment]
Thanks @sutibun, this issue really is turning into (mostly) "Put Redirect module in core". It would provide the "Old alternative URLs" ability you've described.

It's worth noting that Redirect also lets you manually add other redirects on the node form, which I've found useful. For example setting up redirects for common typos is useful, or to make really short URLs that redirect to the longer canonical one.

I also think you have a good point about the term "URL alias". That's a confusing term, and the description is even worse: "The alternative URL for this content". It's not an "alternative" at all, it's pretty much the only URL a user will ever see.

I'm not sure about "Main URL" however. "Primary URL"? "Content URL"? Hell, what about just calling it "URL"? Although now that I think about it, not all users would know for sure what a URL is in the first place.

We could help a little by prefixing the domain name to the field, e.g.

```
URL
http://example.com/[ blog/how-to-eat-cookies                   ]
```

Then the term "URL" will make sense. Without the prefix it's just the path portion of the URL.

**Comment by klonos** [comment]
> We could help a little by prefixing the domain name to the field

:+1:

**Comment by sutibun** [comment]
> It's worth noting that Redirect also lets you manually add other redirects on the node form, which I've found useful. For example setting up redirects for common typos is useful, or to make really short URLs that redirect to the longer canonical one.

I also use that a lot. It should be there in some shape.

> Hell, what about just calling it "URL"?

Yes, 100% on board with that! Let's not complicate this by creating our own custom terms.  Let's use what is generally used everywhere else.

> Although now that I think about it, not all users would know for sure what a URL is in the first place.

If a user doesn't understand what a URL is, at a minimum, s/he won't understand Bd or any other CMS. And, actually, that's not a huge problem with Bd because they can fall back on the default generated URL pattern set up by the site builder.

What we can also do is have a description like: "`A URL is the address you type in your browser to get to a webpage like http://www.cnn.com`" Maybe people will understand web address better?

> `URL  
> http://example.com/[ blog/how-to-eat-cookies]`

Plus, that too.

**Comment by klonos** [comment]
...now with Redirect in core, is there anything actionable here?

**Comment by klonos** [comment]
...actually, there are a few things that need fixing: I've opened a new issue: #1980

**Comment by klonos** [comment]
@sutibun I'm closing this issue here. If you still feel that there are things that need to be done that I am not addressing in the other issue, feel free to reopen.
