### ISSUE TITLE
[Coding standards/Policy, no patch] Officially adopt and comply with the same project naming policy (capitalization) as Drupal.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1289]
I wasn't sure whether to file this under core or contrib (because it effects both) or ops (because it is a policy matter). Anyways, here it is, after @jenlampton's suggestion over in https://github.com/backdrop-contrib/auto_nodetitle/pull/13#issuecomment-143655433

The same issue has been discussed and decided in d.org:

> **name (Required)**
> This displays the name of your module, which will appear on the Modules page. Since module names are proper names, it should be capitalized as a proper name (e.g., "Really Neat Widget", not "really neat widget" or "Really neat widget"), and it should be a human-readable name (not really_neat_widget). If your module name includes an acronym (CSS, WYSIWYG, UI, etc.) or a third-party trade name (jQuery, JavaScript), of course follow the standard capitalization for those.
> `name = Really Neat Widget`

(source: [Writing module .info files (Drupal 7.x)](https://www.drupal.org/node/542202#name))

The coding standard was actually decided in [Decide on coding standard for capitalization of module names [policy, no patch] [#1346158]](https://www.drupal.org/node/1346158).

Jen mentioned in the other issue...

> I don't think we really have a strong feeling on this one way or the other. If you feel strongly that we should adopt Proper Name Case like Drupal 8 did, then let's do it.

That is the thing though. Although this specific issue was filed under the D8 issue queue, its effect was for **all** projects, core and contrib, be they D6, D7 or D8 or even D9.

Also it is not a simple matter of strong feelings. Consider for example the documentation use-case and how these sentences change meaning depending on capitalization (module name is fictional):
1. "...use menu extra styles in order to achieve task x"
2. "...use **M**enu extra styles in order to achieve task x"
3. "...use **M**enu **E**xtra styles in order to achieve task x"
4. "...use **M**enu **E**xtra **S**tyles in order to achieve task x"

In the above...
1. "menu extra styles" is a feature (of core?)
2. "extra styles" is a feature of the _Menu_ module
3. "styles" is a feature of the _Menu Extra_ module
4. _Menu Extra Styles_ **is** the module

Do you see now why project names need to be capitalized? We need to clarify which part of the sentence is an actual thing.

[edit]: ...may I add here this sentence too:

"...use **M**enu **E**xtra **S**tyles in order to create menu extra styles"

...meaning "...use the **M**enu **E**xtra **S**tyles _module_ in order to create extra styles for your menus."

> Please open an issue against Backdrop Core so we can get those all fixed up (if they aren't already), and let's find somewhere to document it.

Tasks:
- [x] Decide on the policy (this issue here).
- [x] File an issue against core about core module names (once we make a decision on the previous task).
- [x] Write documentation about this.

**Comment by quicksketch** [comment]
I'm 100% in agreement about using Proper Names, instead of sentence casing.

**Comment by klonos** [comment]
Thanx. That was a rather long issue summary to write and was hoping that it will get the message across.

**Comment by klonos** [comment]
...so should I tick the first task as decided or am I being too hasty and we need to wait for discussion/more opinions on the matter?

**Comment by BWPanda** [comment]
I agree!

**Comment by BWPanda** [comment]
Hmm, seems [our documentation](https://api.backdropcms.org/modules) already has the same wording as D8 (see above). So are there code modules that don't adhere to this, or can we close this issue?

**Comment by klonos** [comment]
@BWPanda only a couple of our core modules were "violating" this standard, but we have fixed this in #3810 😉 ...I see Project submodule with this problem though:

<img width="405" alt="Screen Shot 2019-09-05 at 12 17 21 am" src="https://user-images.githubusercontent.com/2423362/64292228-8ff61000-cf72-11e9-8116-22fabca7906d.png">

I don't think that there is an easy way to control this in contrib-land, but as a member of the Bug Squad, I can be fixing these as I find them. I could use a policy link to point module maintainers to as reasoning.

**Comment by klonos** [comment]
...I have also ticked the "ile an issue against core ..." checkbox. Not sure what else is left to be done here.

**Comment by klonos** [comment]
...meh. Lets call this done, and reopen if more things to action come up 😅
