### ISSUE TITLE
Page titles of the pages for installing modules, themes and layouts all say "Install a project" while respective menu item is "Install module/theme/layout".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1291]
Found while testing #1288.

**Comment by sutibun** [comment]
Eyes like a hawk ...

**Comment by klonos** [comment]
:smile:

**Comment by quicksketch** [comment]
So to be clear, the title of the page at `/admin/modules/install` should be "Install module". Themes and layouts can each be installed at their respective paths I believe. We might just need to remove a call to `backdrop_set_title()` that's floating around on that page. Tagging this novice.

**Comment by klonos** [comment]
> So to be clear, the title of the page at ```/admin/modules/install``` should be "Install module".

Yep.

> Themes and layouts can each be installed at their respective paths I believe.

Yes, but their page titles also say "Install a project" (did not notice this until you mentioned it). They should be "Install a theme" and "Install a layout" respectively.

...changing issue title (and scope).

**Comment by klonos** [comment]
...sorry for the noise. Typos and trying to get the title to actually reflect the issue at hand. Too verbose.

**Comment by Dinornis** [comment]
Closing and marking as fixed.
