### ISSUE TITLE
[CKEditor] "URL not valid" when using relative paths for (local) images.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1292]
When trying to insert an image file into a text area CKEditor gives the option to upload a file or to enter a URL. I have not been able to add an image URL for a file that I know is on the server, and I get a warning saying the URL is not valid.
![imageurlproblem](https://cloud.githubusercontent.com/assets/10559274/10247832/a6440d86-6913-11e5-9f1b-68e0e14f2d83.png)

**Comment by docwilmot** [comment]
Curious: Try:
- without the leading slash
- without the underscores

**Comment by Graham-72** [comment]
>Try:

    without the leading slash
    without the underscores

Sadly no better, but I have now found it does work if I paste in the full URL like
http://www.browsersbookshop.com/files/pictures/CLsignature.png

So the hint "/example/image.jpg" is misleading?

**Comment by docwilmot** [comment]
Did you try one of those suggestions at a time? I mean 
`/backdrop/.../mediumIMG1290.JPG` (of course make sure there is actually a `mediumIMG1290.JPG` to upload).
OR `backdrop/.../medium_IMG_1290.JPG` 
And another `/backdrop/.../mediumIMG1290.jpg` (lowercase).
Sorry but guessing here as to what could be the issue with the URL. ie either the underscores, the path itself or the case.

**Comment by Graham-72** [comment]
Yes, tried them all, and on 3 different sites (though on the same server). Only the full URL works for me.

**Comment by docwilmot** [comment]
> So the hint "/example/image.jpg" is misleading?

Seems so. The validation calls `valid_url($value, TRUE)`, where the `TRUE` means an absolute URL.

**Comment by Graham-72** [comment]
Thanks for checking and confirming this. It had me puzzled/worried for a while.

**Comment by quicksketch** [comment]
Filed a PR at https://github.com/backdrop/backdrop/pull/1106. Turns out we already did the same thing for link URLs to allow relative or absolute paths, so I just applied the same change for image URLs.

**Comment by stephit** [comment]
I was just wondering what the status of this issue was. I noticed this today uploading an image. Hard-coding full image URLs can cause problems down the line if I ever decide to use a different URL for the website. It also can cause problems if you want to set up a test environment with a dummy URL prior to launching a site. Thank you!

**Comment by klonos** [comment]
@stephit: can you please try the fix from @quicksketch's PR. You can download it as a patch from here: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1106.patch

**Comment by quicksketch** [comment]
I've merged the PR at https://github.com/backdrop/backdrop/pull/1106. Relative URLs should now be allowed.
