### ISSUE TITLE
Favicon - The custom favicon path is invalid

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1295]
I would like to place favicon this way:

```
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
```

but:

![favicon](https://cloud.githubusercontent.com/assets/13515302/10262318/0b897286-69cc-11e5-9b43-7fe9c8fb0fc1.gif)

**Comment by Graham-72** [comment]
This made me curious so I have had a look at what Backdrop produces on one of my sites where  I uploaded an icon. It produces
`
<link rel="shortcut icon" href="http://www.mydomain.org.uk/files/favicon.ico" type="image/vnd.microsoft.icon" />
`
Apart from the mention of Microsoft is this not acceptable?

**Comment by bd0bd** [comment]
Hi @Graham-72! Thank you!

I need like this:

	<link rel="shortcut icon" href="http://domain.com/img/favicon.ico" />
	<link rel="icon" href="http://domain.com/img/favicon.ico" />
	<link rel="apple-touch-icon" href="http://domain.com/img/touch-icon-iphone.png">
	<link rel="apple-touch-icon" sizes="76x76" href="http://domain.com/img/touch-icon-ipad.png">
	<link rel="apple-touch-icon" sizes="120x120" href="http://domain.com/img/touch-icon-iphone-retina.png">
	<link rel="apple-touch-icon" sizes="152x152" href="http://domain.com/img/touch-icon-ipad-retina.png">

**Comment by Graham-72** [comment]
Hi @bd0bd 
I am curious as to why you need your shortcut icon to be in a directory /img rather than in the normal public filesystem.

**Comment by klonos** [comment]
Yeah, I know what @bd0bd is talking about and what he's trying to achieve. For Drupal, I used to use the [Responsive Favicons](https://www.drupal.org/project/responsive_favicons) module which generates all the necessary favicon tags. Before that, I use to use [Touch Icons](https://www.drupal.org/project/touch_icons), but that has a limited set of supported devices/platforms.

PS: ...another annoyance I was trying to get rid in Drupal was what the [Favicon](https://www.drupal.org/project/favicon) module corrects.

**Comment by bd0bd** [comment]
>
I am curious as to why you need your shortcut icon to be in a directory /img rather than in the normal public filesystem.

@Graham-72, no any special reason.
My reason - I would like to do it my way I did it before for many years.
To place favicon in the place I would like it to be placed in - this is normal way for me :)

**Comment by Graham-72** [comment]
Interesting.
@bd0bd if Responsive Favicons was available as a contributed module for Backdrop but not in core would you make use of it? I might look at porting it.

**Comment by bd0bd** [comment]
@Graham-72, thank you!
I do not enough clear understand what is "Responsive Favicons".
But I would prefer (not exactly sure WHY) to use 4 different presized images for favicons.

Personally I would much prefer if you could devote your time for Webform module issue I have mentioned before :) To make View mode: **Full content** option working.
Now I am forced to add extra blocks for Webform blocks if I need Webform block with a text above it.
Instead of 3 Webform blocks I have 6 blocks now.

**Comment by Graham-72** [comment]
It does look as though the Responsive Favicons module provides for the use of 4 (or more) images for favicons. I think maybe the title is misleading.

Regarding Webform, this is a complex project and I am not sure I could help - it needs @biolithic or @quicksketch perhaps.

**Comment by klonos** [comment]
> ...if Responsive Favicons was available as a contributed module for Backdrop but not in core would you make use of it? I might look at porting it.

I would use it! So, yes please.

**Comment by biolithic** [comment]
There exists https://github.com/backdrop-contrib/responsive_favicons if
anyone wants to test it out.

1) make files/favicons a folder on your site
2) go to http://realfavicongenerator.net/ and do what it says
3) install the module, go to the config screen and paste in the code from
above, also upload the zip file #2 gives you, check box
4) save, flush caches, update.php, run cron, etc...
5) see if the favicons are what you want!

I don't want to be the maintainer of this doing every last request, so if
someone would like to take over, that would be swell.
Take care!

**Comment by klonos** [comment]
> There exists https://github.com/backdrop-contrib/responsive_favicons if
anyone wants to test it out.

Thanx for porting this @biolithic

**Comment by sutibun** [comment]
Just tried the responsive favicon module and works nicely. Monkey likes it. Maybe we should have a similar feature natively in Bd under Appearance.
