### ISSUE TITLE
ckeditor goes away on android sIII

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1296]
`sIII` tested on real device.

<img width="1254" alt="screen shot 2015-10-03 at 12 27 53 pm" src="https://cloud.githubusercontent.com/assets/6763671/10263882/14c7f35a-69cb-11e5-8890-e67ae0a0d4cb.png">

javascript errors.  also on `sIV` tested through chrome toggle device.

**Comment by quicksketch** [comment]
JS errors on the page will stop any further JS from executing. Those JS errors aren't in core though. "frame_loader.js" looks like it's part of Evernote Chrome extension: https://discussion.evernote.com/topic/43327-archived-errors-on-chromium-console-devtool/

But you said you tried this on an actual device as well and it had errors?

**Comment by serundeputy** [comment]
i don't see errors but i Don't see ckeditor either

https://drive.google.com/file/d/0B3P_xIYZm_I_ZVF2TDU1LWZuMVU/view?usp=docslist_api

**Comment by Dinornis** [comment]
Is this still a problem?

**Comment by klonos** [comment]
...I'm going to go out on a limp here and close this ticket. Please feel free to reopen if this is still an issue @serundeputy 😄
