### ISSUE TITLE
Allow the "core" directory to be a symlink outside the web root (problems with install.php and update.php)

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1297]
Files install.php and update.php has 

```
chdir('..');
```

It works fine while backdrop downloaded to DOCUMENT ROOT.

When backdrop downloaded to another dir and then symlinked to docroot, we have an issue.

```
 /home/user/domains/mytest.site/core -> /home/user/github/core
```

chdir('..') will get you to:
 /home/user/github/ 
but not to 
 /home/user/domains/mytest.site/

On install phase it means that settings.php will be written to  /home/user/github/settings.php instead of 
/home/user/domains/mytest.site/settings.php
Files folder path will be 
/home/user/github/files 
instead of 
 /home/user/domains/mytest.site/files

When install finish, you will not be able to get to the site, because /home/user/domains/mytest.site/settings.php is not updated and it will redirect to core/install.php

And if you manually move (not copy) settings.php and files to DOCROOT, update script will fail to see mysql settings.

The quick solution is:

```
define('BACKDROP_ROOT', dirname(dirname($_SERVER['SCRIPT_FILENAME'])));
chdir(BACKDROP_ROOT);
```

Issue #311 probably related to this one.

**Comment by quicksketch** [comment]
This seems like a change that would be suitable for a PR. We'd probably want a code comment explaining why we used that approach rather than just the simpler `'..'`.

**Comment by Gormartsen** [comment]
I sent PR backdrop/backdrop#1310.

Also I updated SandBox scripts to use this patch while we did not push this changes to 1.x

First Sandbox was created with this changes: 
https://github.com/backdrop/backdrop/pull/1310#issuecomment-201748678

That's how DOCROOT looks like:
```
ls -lah ~/domains/1310.backdrop.backdrop.qa.backdropcms.org/
total 116K
drwxr-x--x  3 qa   qa   4.0K Mar 26 12:46 .
drwxr-xr-x 21 root root 4.0K Mar 26 12:46 ..
lrwxrwxrwx  1 qa   qa     46 Mar 26 12:46 core -> /home/qa/github/backdrop/backdrop/pr/1310/core
drwxrwxr-x  3 qa   qa   4.0K Mar 26 12:46 files
lrwxrwxrwx  1 qa   qa     51 Mar 26 12:46 .htaccess -> /home/qa/github/backdrop/backdrop/pr/1310/.htaccess
-rw-r--r--  1 qa   root  85K Mar 26 12:46 index.html
lrwxrwxrwx  1 qa   qa     51 Mar 26 12:46 index.php -> /home/qa/github/backdrop/backdrop/pr/1310/index.php
lrwxrwxrwx  1 qa   qa     49 Mar 26 12:46 layouts -> /home/qa/github/backdrop/backdrop/pr/1310/layouts
lrwxrwxrwx  1 qa   qa     49 Mar 26 12:46 modules -> /home/qa/github/backdrop/backdrop/pr/1310/modules
lrwxrwxrwx  1 qa   qa     50 Mar 26 12:46 profiles -> /home/qa/github/backdrop/backdrop/pr/1310/profiles
lrwxrwxrwx  1 qa   qa     51 Mar 26 12:46 README.md -> /home/qa/github/backdrop/backdrop/pr/1310/README.md
lrwxrwxrwx  1 qa   qa     52 Mar 26 12:46 robots.txt -> /home/qa/github/backdrop/backdrop/pr/1310/robots.txt
-rwxrwxr-x  1 qa   qa    15K Mar 26 12:46 settings.php
lrwxrwxrwx  1 qa   qa     47 Mar 26 12:46 sites -> /home/qa/github/backdrop/backdrop/pr/1310/sites
lrwxrwxrwx  1 qa   qa     48 Mar 26 12:46 themes -> /home/qa/github/backdrop/backdrop/pr/1310/themes
```

If PR get updated, it will not overwrite DOCROOT settings.php with database settings (I updated PR sync deploy to reset changes firs and apply new changes to avoid conflicts)

Sounds like a good solution for #346 as well.

**Comment by quicksketch** [comment]
Thanks for filing a PR Gor! Overall it looks good to me. Let's schedule this for 1.4.0. I can't see any way this could break existing sites, but better to be safe and at least make it part of the minor release rather than a bugfix item.

**Comment by Gormartsen** [comment]
Ok!

I also added patch to sandboxes.
So sandboxes get delivered with this changes already to avoid issue with settings.php reset when PR Get updated.

Regards,
Gor Martsen
@gormartsen

**Comment by quicksketch** [comment]
I merged this change manually to update the docblocks for clarity. The commit is 4a9c9a6. Thanks @Gormartsen for fixing!
