### ISSUE TITLE
[UX] Make the Node Edit page more user-friendly

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1299]
## Huge ugly problem

There's _something_ about the Drupal/Bd edit page that has always seemed wonky and completely uncomfortable to work on. **It looks the part but it's not good for content creators.** So much so that I simply opted to write on a text editor first and then copying/pasting.

I couldn't quite put my finger to the cause until [after debating a somewhat unrelated issue](https://github.com/backdrop/backdrop-issues/issues/1190#issuecomment-144136425) (monkey likes debates... er ... discussions because it makes for clearing/changing your stance and leads to unintended ideas) where it hit me.

Looking back now, it's kind of obvious. Monkey is a lil' designing monkey.

Look at your standard edit form page

![longtextarea](https://cloud.githubusercontent.com/assets/14132746/10349122/855056d2-6d02-11e5-86c9-6807102cf53f.png)

Particularly at the body text area and **notice how wide it is.** There is roughly 120 characters (including space) per line.

Why is that important?

[One](http://www.fonts.com/content/learning/fontology/level-2/text-typography/length-column-width)

> Column width affects readability because of the way our eyes read. Many people don’t realize that our eyes do not read character by character or even word by word. Rather, our eyes scan a line, pausing momentarily to record groups of three or four words. Studies have found that a reader can make three or four such pauses on a line before it becomes tiring.

[Two](http://www.thedesigncubicle.com/2008/12/10-common-typography-mistakes/)

> Reading many long lines of type causes eye fatigue. Readers are forced to moves their heads and eyes more often from one line to the next. Various sources I’ve researched state to keep lines of text under 50 – 60 characters long.

Designers tend to refer to the actual post content but it applies everywhere, even inside the text area form. (That earlier debate triggered that old lesson) My guess is the long width (lead? There's a typographical term I can't remember) makes writing in the Bd text editor unpleasant.

**Outside of the Drupal/Bd arena, where else have you seen the text area form stretching from one end of the screen to the other?** Even GitHub's text editor only takes the width of one column.
## The quick alternate solution

You could increase the font size in the text area form to decrease the number of characters per line. I suppose if you want to be practical, that is a legitimate route. There's nothing wrong with that really but you should know from past posts that the monkey always has a big vision.
## Bigger Solution v1.0

Here is my vision solving this readability issue along with organizing the whole edit page.

![node-edit](https://cloud.githubusercontent.com/assets/14132746/10348069/9151e76c-6cfc-11e5-93a7-96d38c5e410e.png)
### Explaining the proposed changes

From my point of view, there are three main components when it comes to creating/editing content.
#### 1. Content: Elements to craft content

This area deals with stuff a writer will be most familiar because its the content itself. You have
- post title
- post main copy
  - Because the edit page uses two columns, the text editor's width naturally shrinks and readability improves.
- post images
- tags (I am a lil' undecided whether taxonomy is such a high priority for a writer that it needs to be here and not the sidebar but, for now, let's go with it. I am already suggesting drastic changes)

These elements a content creator will immediately understand and need so it should be obvious where they are: i.e. front and center.
#### 2. Secondary options: Elements to look over before publishing

The sidebar is left for _secondary_ options that should be easily accessible.

I pretty much **brought up here the contents of "publishing options", "authoring info", "comment settings" and meshed them together** (grouped them under "essentials".) It's no longer in a hidden cave.

What makes more sense: isolating these usable options in hidden tabs that you have to click to reveal or exposing them up front to a writer together?

![tab](https://cloud.githubusercontent.com/assets/14132746/10356911/921f87ae-6d41-11e5-8811-eceafd75aa88.png)

In my opinion, these are frequently used options that should not be hidden in the vertical tabs (accordion?) especially when they don't take up much space and you can represent them simply.

To make it even easier, I organized these options so they read like a sentence "This was published by Mr. X today at 4pm"
- **published** (yes or no)
  - WHAT
  - Maybe this UI element isn't best but idea being its status should stand out so a user immediately knows if it's a draft or already published.
- **by X**
  - WHO
- **on yy/yy/yyyy**
  - WHEN
- **at zz:zz am/pm**
  - WHEN
- **"Sticky"**
  - I don't use this option but it's grouped here with the other publishing options
- **Turn on comments**
  - "Turn on" vs "enable". "Turn on" sounds softer to the ears/eyes.
  - If you need to turn off comments for _this_ post, it's within reach.
  - No need to dig into the tabs just to even see its status.
- **Flag**
  - If we represent [the flag as a star](https://github.com/backdrop/backdrop-issues/issues/1190#issuecomment-144136425), you'll notice I placed it next to the post title all the way on top. The star flag will be easily accessible and not get in the way of user's understanding. I think it looks nice there. Of course, we can always add the star flag here in the sidebar.
#### 3. Nitpicky details

Now I think the above elements are sensible options the majority of content creators will use frequently and thus should be most visible. **Any leftover options, however, belong at the bottom of the page** in a section I call nitpicky details. And that title should give away what I think of these options. Yes, these options are used but not often.
- **URL settings**
  - I was thinking of moving this out of the accordion and into the first section, maybe under the body section but then I began thinking there really isn't a huge need to change the URL often. At least, normal users won't. Most content creators won't change the post's URL frequently and instead rely on the URL pattern to generate it for them (if they're aware of URLs) For the few times you'd want to _tinker_ with the URL, you can scroll down and do your thing. But by keeping this tinkering option below, we don't overwhelm normal users unnecessarily.
- **menu setting**
  - To be honest, I never understood this setting in my years with Drupal/Bd. I still scratch my head with how the whole menu system works. So, I left it here.

**I also suggest this "Nit-picky details" section be collapsed by default.** The fewer the options a writer comes across, the less overwhelming it will feel. This is the ideal scenario I envision.
1. A new user hits "create post" and lands on the edit page.
2. She will write out content in the appropriate fields like title and body.
3. She will look over the publishing options in the sidebar, make any necessary changes if necessary, and then hit publish.

The most basic of options will be presented and the user won't wonder "what's an alias?", "what's a menu", etc. Overlooking the nitpicky details is fine and preferred.

The whole goal of this page is to get the writer to create content and move on. Not tinker or hit friction points that most likely won't apply to them. 80/20 rule.

Going with that thinking, I also suggest we get rid of using "alias" and stick with "URL". To differentiate between the canonical URL and aliases, we should use "Main URL" and "Alternate URLs". I hope I made some sense [while I struggled to understand and explain that here.](https://github.com/backdrop/backdrop-issues/issues/1286#issuecomment-145433701)

Note: There's a typo in mockup: It says "Mail" when it should say "Main"
### Conclusion

*wipes forehead*

Hesitated to write this up. I notice that short tickets tend to get worked on more often but I find sometimes you can't fully understand the small components in isolation without seeing the bigger picture and/or how they interact in context.

Anyway, monkey wanted to get this last big idea out just in case get waaaay busy starting next week. Unsure if will have same time to spend thinking and writing. Will try but we'll see. Plus, I think I am overwhelming you with my big ideas which maybe might not be practical at this point.

No worries. ^_^)b 

Hope this helps.

**Comment by klonos** [comment]
Hey, I have no time and need to :zzz: soon, so did not read this (rather lengthy - as the Monkey is accustomed to write) post thoroughly, but couldn't help but noticing a bit of a schizophrenic attitude there. What's up with the kitten hatred there? :stuck_out_tongue:

**Comment by sutibun** [comment]
Was gonna use "How to cook humans" but then ... you know, the human readers wouldn't like that. Plus, think nearly everyone dislikes kitties. Just imagine the incessant meowing...

I'm more of a visual monkey. I usually start with a big vision in my mind but it tends to be blurry. Find that trying to express a muddy idea and writing things out so others can understand brings clarity. In the process, discover flaws in thinking, better ways to achieve something, and generally refines idea.

I am not a great coder so the least I can do to help is think through the problems ahead of time so what I present has had some thought behind it. Just a lil' bit better than a first draft. Well, at least that's the plan. Plus, I am new here... don't think many will accept my silly ideas without explanations.

**Comment by Gormartsen** [comment]
@sutibun how about moving 'comments on/off' url and other small things to side bar as well?

Or find a way how to vertical tabs move to sidebar completely.
This way any module can add it's own functionality.

Btw. I am completely on the same page with you.
It's pretty hard to use node edit form.

**Comment by sutibun** [comment]
> Btw. I am completely on the same page with you. It's pretty hard to use node edit form.

Waaah, kinda forgot about this issue. Thought 'twas just me who had trouble with the edit page.

> how about moving 'comments on/off' url and other small things to side bar as well?

The comments on/off was already on the sidebar, along with the 'sticky' option. It's in the "Essentials" panel, below the date as a checkbox called "Turn on comments."

> Or find a way how to move vertical tabs to sidebar completely.

I could be wrong but I think the vertical tabs won't fit in the sidebar and if it does, its content will feel cramped.

Hmm... thinking it further, you may be right about moving the URL to the sidebar as well. It may be *just as bad* to "hide" that info under a vertical tab.

## Node edit page v2.0

Ok then... below is an updated mockup with your suggestions and other minor changes. I basically moved everything out of the vertical tabs.

![node-edit-2](https://cloud.githubusercontent.com/assets/14132746/10708569/22ba9ed2-79d3-11e5-8ac6-ddd58db8ae10.png)

### Quick explanation

Everything under the "Essentials" panel (eh.. prob bad name but let's roll with it for now) will hold info & options a creator needs at some point and it makes sense to display these options prominently and close together. You'll want to

- **know if a post is published or a draft right away**.
- **know who is the author** and have the ability to change it without digging into vertical tabs.
- **know when the post was published** and update it if necessary
- **know the web address (where) the post can be found** and easily update it if necessary. My minor concern with adding the URL on the sidebar is it might not display the full URL since the sidebar won't be wide.
- **make a post sticky.** You can quickly tick this on/off.
-  **enable/disable comments** In my opinion, having this visible is important. You won't worry about its status and for those posts you don't want to receive comments, you can easily turn it off. (Again, no need to dig into vertical tabs)

I also added a "Redirect" panel in the sidebar (assuming #905 goes into core) which will list URLs and offer [the ability to add new redirects](https://github.com/backdrop/backdrop-issues/issues/1286#issuecomment-149406423)

> It's worth noting that Redirect also lets you manually add other redirects on the node form, which I've found useful. For example setting up redirects for common typos is useful, or to make really short URLs that redirect to the longer canonical one.

I "moved" the menu settings also but as I mentioned before, I don't understand it but let's assume it fits nicely.

I still left the "Additional settings"/"nitpicky details"/"kitchen sink" as a row at the bottom. Since all the core options were moved to the sidebar, I am thinking that contrib module functionality can by default go in this section. My thinking is I don't want to overload new users with so many panels when they install new modules.

> This way any module can add it's own functionality.

How about Backdrop adding a feature that allows users to move the contrib module panels out of this section and anywhere they want. (probably using the built-in template system?)

Maybe I am being too conservative but I want to keep the interface simple for normal users. Adding too many options by default will detract from the main goal of the edit page, which is to create content.

Maybe there's a better way to achieve a good balance? Anyway, how's that?

**Comment by docwilmot** [comment]
A re-design of the `node/edit` page would be welcome by many I suspect. This could probably be relatively 'easy' to accomplish by having a new `node/%/edit` layout and moving some of that page's elements to blocks, and putting those blocks in a sidebar.

But 'easy' as it may be, I think a 1.3.0 tag is pretty ambitious. Can we make this a 1.x request please?

**Comment by sutibun** [comment]
Sure
