### ISSUE TITLE
Permissions : provide selective access to the content overview page.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1303]
I do not seem to be able to grant permission for an authenticated user to see a listing of all content of a particular type.

There is the permission to access the content overview page and see a listing of all content but I would like to be able to grant this on a per type of content basis. I can then have a type of user with permission to review and edit all content of one (or more) specified types.

**Comment by quicksketch** [comment]
The listing of content at `admin/content` is just a View. So couldn't you just set up another page at which the authenticated user could access content of a particular type? I do believe that because this path is under `admin/*`, the user needs to have the "access administration pages" permission.

**Comment by BWPanda** [comment]
No followup, so assume the question was sufficiently answered.
