### ISSUE TITLE
VIEWS_UI cancel button implemented via markup

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1305]
You can see code here
https://github.com/backdrop/backdrop/blob/1.x/core/modules/views_ui/views_ui.admin.inc#L445

**Comment by Gormartsen** [comment]
I added PR to fix it:
https://github.com/backdrop/backdrop/pull/1104

**Comment by quicksketch** [comment]
Looks like this failed tests. This bit seems a little unusual:

```
+  $path = 'admin/structure/views'
+  $options = backdrop_parse_url($path);
+  $options['attributes']['class'][] = 'form-cancel';
```

Why is $options set to the result of `backdrop_parse_url()`? Perhaps that's what's resulting in the Views testing breaking.

**Comment by Gormartsen** [comment]
I was using next code like example:
https://github.com/backdrop/backdrop/blob/1.x/core/modules/block/block.admin.inc#L116
https://github.com/backdrop/backdrop/blob/1.x/core/modules/taxonomy/taxonomy.admin.inc#L641

Just to keep up with "standard" for cancel button.

**Comment by Gormartsen** [comment]
Maybe we need to add next code:
```
 // Prepare cancel link.
  if (isset($_GET['destination'])) {
    $path = urldecode($_GET['destination']);
  }
  elseif (isset($_SERVER['HTTP_REFERER'])) {
    $path = urldecode($_SERVER['HTTP_REFERER']);
  }
  else{
    $path = 'admin/structure/views';
  }
```

**Comment by quicksketch** [comment]
Hm, yeah I think the parsing of the path may only be needed if working with a variable path (like $_GET['destination']), but it's strange that this would cause so many failures. There's probably an obvious cause if we apply the patch and try it out in the UI.

**Comment by Gormartsen** [comment]
I assume it's Travis issue.
See another pull request: 
https://github.com/backdrop/backdrop/pull/1103
Almost the same amount of failure.

**Comment by quicksketch** [comment]
Hm, the Apache log in Travis says that there is a parse error:
```
[Tue Oct 13 01:06:15 2015] [error] [client ::1] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Parse error:  syntax error, unexpected T_VARIABLE in /home/travis/build/backdrop/backdrop/core/modules/views_ui/views_ui.admin.inc on line 447
```

**Comment by Gormartsen** [comment]
@quicksketch Pardon. I had to review it by myself.  Thank you. 
I updated this line but it failed again.

Will double check my code on my box and update you here.

**Comment by Gormartsen** [comment]
@quicksketch I fixed this typo. But test failed again. I don't really understand why. Maybe I need to sleep first)

**Comment by Gormartsen** [comment]
All checks have passed for this PR. Ready to be merged.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/1104. Thanks @Gormartsen!
