### ISSUE TITLE
Backdrop Pattern Library/Interface Guidelines?

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1306]
I just heard Morten DK on a podcast mention the wish for a Pattern library, and I immediately thought about our desire for a UI/UX Standards Guide. A Front End (FE) Pattern Library could solve quite a few problems for us.
- Component Library (which is what Styleguide module is doing for Seven)
- UI/UX Standards that ride along with the components
- Backdrop Admin (Seven) FE Coding Standards
- Something Contrib Theme devs could work off of
- Code examples that module devs could use, if a component doesn't map directly to a theme function, or the like.

Right now we have the Styleguide, which is a start, but I'm thinking of something that is a bit beefier. Something along the lines of Pattern Lab. So if you quickly peruse these few pages, this is in the direction of what I'm thinking of:
http://demo.patternlab.io/patterns/00-atoms-06-buttons-00-buttons/00-atoms-06-buttons-00-buttons.html
http://demo.patternlab.io/patterns/02-organisms-02-comments-00-comment-thread/02-organisms-02-comments-00-comment-thread.html
http://demo.patternlab.io/?p=templates-blog

If you click on the gear in the top right you'll see Annotations, the Blog template has some good annotations. So in Patternlab, Annotations are secondary, for what I'm thinking of they'd be more integrated.

So I think this is a good idea, but it's kind of an undertaking. This could be something built into backdrop (as a contrib module, or theme), or it could be something more like Patternlab, where we have a backdrop-ops repo, and use a nice tool to help us build/maintain it.

I personally think it'd be cool if long term it was built into Backdrop (likely as contrib) and Backdrop can make Pattern Libraries off of the admin or the frontend, so devs that use Backdrop could show Pattern Libraries to a client.

**Comment by sutibun** [comment]
May be somewhat related ^^)

http://bradfrost.com/blog/post/atomic-web-design/

**Comment by quicksketch** [comment]
We had some early work on something similar to this in the #390. We used to mention it during the weekly calls while some work was happening on it, but we haven't seen any progress on it recently. Does that look like what you're suggesting?

**Comment by wesruv** [comment]
Basically I'm thinking if that had a baby with Patternlab. I want the 'this is how and why we use this widget' and code examples/docs.

**Comment by wesruv** [comment]
Since 'Component Libraries' are in right now, there's probably a Component Library builder that could make building this easier. I don't think Pattern Library is the right choice because it's 'Annotations' are tertiary, I think we want something with prominent annotations.

**Comment by jenlampton** [comment]
Drupal is working on something similar:
* https://www.drupal.org/node/2293627
* https://www.drupal.org/sandbox/jhodgdon/2600128
* https://www.drupal.org/docs/develop/user-interface-standards

**Comment by jenlampton** [comment]
@wesruv I think the tools we use should be 1) whatever's easiest for those creating this thing, but also 2) whatever's easiest for people who will continue to contribute. :)

**Comment by jenlampton** [comment]
a few related issues:

* Remove “Tabs” #464
* Use “Vertical tabs” in text formats UI?  #1032
* Decide where to put “Action links”  #2343

**Comment by jenlampton** [comment]
Hm, I found the original issue for this: https://github.com/backdrop/backdrop-issues/issues/390 Not sure if this should be separate. If what @wesruv wants is code, maybe we have both a pattern library and a human-interface-guidelines document?

**Comment by jenlampton** [comment]
I'm struggling to see how this issue is different from https://github.com/backdrop/backdrop-issues/issues/390 so I'm going to close this one and mark it as duplicate.
