### ISSUE TITLE
[UX] Prevent Views Page settings "Path" from being unnecessarily trimmed

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1309]
I noticed this while replying in https://github.com/backdrop-ops/contrib/issues/114

![backdrop-ops-contrib-issue114-view_display_as_tab-step6](https://cloud.githubusercontent.com/assets/2423362/10696726/3ea03c66-79f5-11e5-909b-ae4dc52abeaf.png)

---
~PR with PHP by @BWPanda https://github.com/backdrop/backdrop/pull/2847~
PR with added CSS by @jenlampton https://github.com/backdrop/backdrop/pull/2937

**Comment by klonos** [comment]
...there is enough horizontal space to fit the path - no need to trim.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/2847

**Comment by klonos** [comment]
Thanks @BWPanda 👍 simple one-liner fix for this oldie 😄 

...perhaps instead of completely removing the trim, increase it to something like `38` instead of `24`? ...saying `38` specifically, since I have tested this with `admin/content/node_here_is_a_long_path` as path in the PR sandbox, and it seems to be about enough:

<img width="389" alt="Screen Shot 2019-09-04 at 11 47 09 pm" src="https://user-images.githubusercontent.com/2423362/64290269-7bb01400-cf6e-11e9-9e2e-62b313c761cf.png">

...here's longer:

<img width="393" alt="Screen Shot 2019-09-04 at 11 50 18 pm" src="https://user-images.githubusercontent.com/2423362/64290544-f11be480-cf6e-11e9-9b9e-689f6c110887.png">

...and ridiculously longer:

<img width="436" alt="Screen Shot 2019-09-04 at 11 52 30 pm" src="https://user-images.githubusercontent.com/2423362/64290618-16a8ee00-cf6f-11e9-93cf-63684e652d23.png">

Now, putting my multilingual hat on, even with an increased trim, we could still run in situations where there is not enough horizontal space (because the word "Path" used in the label may be considerably longer in other languages), so perhaps use CSS `text-overflow: ellipsis;` instead? Here's how it would look (trimmed on-render/display, using CSS - and only if the path does not fit):

<img width="417" alt="Screen Shot 2019-09-05 at 12 06 39 am" src="https://user-images.githubusercontent.com/2423362/64291540-1873b100-cf71-11e9-9bef-987551d34f17.png">

So, add this CSS:
??? {
  width: 80%;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}

Note that `width: 100%;` also works, but makes the path link wrap under the "Path" label before it starts being trimmed, which I don't find particularly nice:

<img width="432" alt="Screen Shot 2019-09-05 at 12 09 25 am" src="https://user-images.githubusercontent.com/2423362/64291686-756f6700-cf71-11e9-9c09-b5d92ea2d0f1.png">

**Comment by BWPanda** [comment]
@klonos There doesn't seem to be an ideal width to use with the CSS solution that works for different screen sizes and possible translations... Is it worth trying to do that then?

**Comment by klonos** [comment]
@BWPanda 🤔 ...with the trim completely removed, really long paths are bleeding into the 3rd column in the Views UI, which is not good.

I will need to play around with the CSS a bit more, to see if we can achieve the desired result without compromising re width.

**Comment by jenlampton** [comment]
Would it a problem if the path dropped below it's label?
<img width="1225" alt="Screen Shot 2019-10-13 at 6 24 00 PM" src="https://user-images.githubusercontent.com/397895/66725429-ca12c700-ede6-11e9-9516-a63595d36797.png">

**Comment by laryn** [comment]
LGTM

![Screen Shot 2020-01-15 at 4 30 42 PM](https://user-images.githubusercontent.com/871421/72477084-6799e000-37b4-11ea-8468-f10d83056b8e.jpg)

![Screen Shot 2020-01-15 at 4 30 33 PM](https://user-images.githubusercontent.com/871421/72477092-6bc5fd80-37b4-11ea-9a2d-9c08c318b760.jpg)

![Screen Shot 2020-01-15 at 4 30 23 PM](https://user-images.githubusercontent.com/871421/72477112-741e3880-37b4-11ea-8ab2-f5013182e6a8.jpg)

**Comment by docwilmot** [comment]
Was going to code review this, but I dont think we should be dropping the text below its label. Never seen this done, and I dont like the look, and its unnecessary if we're already implementing the ellipsis.

**Comment by stpaultim** [comment]
I don't have strong feelings about this. But, I would agree with @docwilmot  that dropping the text below the label does look a little weird and only buys us a few characters. Is it worth it?

Again, I don't feel strongly. Just sharing my gut reaction when looking at the screenshots.

**Comment by jenlampton** [comment]
Okay, then we'll need to go back to an unreasonable CSS solution since we haven't yet found something that works for all screen sizes. Opening up for ideas!

**Comment by BWPanda** [comment]
Here's a new, simple PR that just uses CSS to break the path string when it would otherwise overflow its container: https://github.com/backdrop/backdrop/pull/3470

**Comment by BWPanda** [comment]
BTW, the inspiration for my latest PR was when I discovered that a `long-url-that-uses-hyphens` wraps automatically, whereas a `long_url_that_uses_underscores` doesn't.

**Comment by indigoxela** [comment]
Nice and lightweight approach, works for me:

![path-without-truncate](https://user-images.githubusercontent.com/842066/103475297-4b6bc600-4dac-11eb-85cc-4e7dcec9940e.png)

@BWPanda one small question: why did you also remove views_ui_truncate() from the menu setting link? Not that it causes any problem, but I thought this issue is only about the path setting.

**Comment by BWPanda** [comment]
@indigoxela I figured why leave that trimming there if we're removing the trimming from the path... Menu titles are even less likely to be long and will wrap easily due to likely having spaces in them, so I thought what's the point of trimming them at all.

**Comment by indigoxela** [comment]
> Menu titles are even less likely to be long and will wrap easily due to likely having spaces in them, so I thought what's the point of trimming them at all.

Makes sense :+1:

**Comment by indigoxela** [comment]
So, we have now two PRs with different approaches, one uses "text-overflow: ellipsis;" and uses the full available horizontal space for a single line, the other one breaks the line with `word-break: break-all;` but shows the full path.
Both switch from php to css handling.

Which one will be our winner? :smile:

**Comment by jenlampton** [comment]
I prefer @BWPanda's approach, so have closed my PR in favor of his. His is RTBC from me!

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/3470 into 1.x and 1.17.x.
