### ISSUE TITLE
[UX] Add ability to customize the path pattern on content type edit/create page

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1312]
The page where you create/edit a content type should ideally have all its configuration options there. A new user may not know that you can set a default path pattern for this content type since those options are in another page. ("/admin/config/search/path/patterns")

Issue #1145 reminded me how annoying it is to have to go elsewhere to customize the path pattern for a content type I just created.

![path-pattern](https://cloud.githubusercontent.com/assets/14132746/10712175/25ed0808-7a58-11e5-969a-cc7892990caf.png)

I suggest we add it under the publishing setting tab or we can also create a new vertical tab just for path pattern.

We should do the same with taxonomy too.

**Comment by serundeputy** [comment]
dupe?
https://github.com/backdrop/backdrop-issues/issues/899

**Comment by sutibun** [comment]
oh, no. I've been caught.

\*pulls up hoodie & runs away behind the dark alley\*

\*gone\*
