### ISSUE TITLE
Add a humans.txt

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1319]
Not really urgent, but nice to have feature: http://humanstxt.org

>**What is humans.txt?**
>It's an initiative for knowing the people behind a website. It's a TXT file that contains information about the different people who have contributed to building the website.

>**Why a TXT?**
>Because it's something simple and fast to create. Because it's **not intrusive with the code**. More often than not, the owners of the site don't like the authors signing it; they claim that doing so may make the site less efficient. By adding a txt file, you can prove your authorship (not your property) in an external, fast, easy and accessible way.

>**Where is it located?**
>**In the site root**. Just next to the ```robots.txt``` file. If possible, you can also add an author tag to the ```<head>``` of the site:
>```<link type="text/plain" rel="author" href="http://domain/humans.txt" />```

>**Why should I?**
>You don't have to if you don't want. The only aim of this initiative is to know who **the authors of the sites** we visit are.

>**Who should I mention?**
>Whoever you want to, provided they wish you to do so. You can mention the developer, the designer, the copywriter, the webmaster, the SEO, SEM or SMO...
>As you can see, the number of people who may take part of the creation of a site can be big, so the list is almost endless.

I think it would be fair to add the core contributors there. It would be a great addition to the "Powered by Backdrop" link.

**Comment by sutibun** [comment]
You just reminded me to add this to a website. ^\_^)

**Comment by klonos** [comment]
Maybe you should also start a monkeys.txt initiative/standard :stuck_out_tongue_winking_eye:

**Comment by sutibun** [comment]
\*whispers\* I'm a fraud. I'm actually a chimpanzee but don't tell anyone.

**Comment by klonos** [comment]
If you push for the humans.txt to be changed to primates.txt, then that should cover all :stuck_out_tongue:

**Comment by sutibun** [comment]
animals.txt would cover all ^\_-

**Comment by quicksketch** [comment]
I'm not sure about this. Adding another text file to the root is a step back from the attempts at simplifying the root structure that we did in Backdrop 1.0, when all other text files were simplified (README.md), removed/consolidated (INSTALL-*.txt), or moved into `/core` (LICENSE.txt).

Even now there are more than 50 contributors to Backdrop core; maintaining that list could be difficult in the future, especially with getting approval from contributors and whatever personal information we list (e.g. GitHub, BackdropCMS.org, or Twitter handles). I would say that we could just include a URL to backdropcms.org or GitHub there, but humans.txt seems like it's intended to literally list the humans that worked on the project.

**Comment by klonos** [comment]
Yeah, I understand. Not feeling too strong about this. Just an idea. Feel free to shoot it down.

**Comment by sutibun** [comment]
> I'm not sure about this. 

What he's **really** saying is he likes animal.txt better ^\_-

**Comment by docwilmot** [comment]
Consensus reached it seems. closing.
