### ISSUE TITLE
[UX] Update views exposed form in block help text.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1322]
The text explaining 'views exposed form in block' is left over from Drupal 7's block system, and should be updated for Backdrop.

Current:

`If set, any exposed widgets will not appear with this view. Instead, a block will be made available to the Backdrop block administration system, and the exposed form will appear there. Note that this block must be enabled manually, Views will not enable it for you.`

Proposed:

`If set, any exposed widgets will not appear with this view. Instead, a block will be made available to the Backdrop layouts system, and the exposed form will become available there. Note that this block must be placed manually, Views will not place it for you.`

<img width="2348" alt="screen shot 2017-05-11 at 10 32 13 pm" src="https://cloud.githubusercontent.com/assets/397895/25983464/cedb4534-3699-11e7-9982-70be550cffcf.png">

<img width="906" alt="screen shot 2017-05-11 at 10 33 29 pm" src="https://cloud.githubusercontent.com/assets/397895/25983475/e518e356-3699-11e7-82a2-d0c1697a9a37.png">

**Comment by Dinornis** [comment]
Is this still relevant?  Sorry, I could not find the interface where this text is used.

**Comment by jenlampton** [comment]
Thanks for looking at this issue @Dinornis, I've added some screenshots to the parent issue that should help you find the setting (and the text in question).

**Comment by aniketh-varma** [comment]
Hi, I would like to work on this issue. It would be really helpful if you can please tell me which file has to be referred for this. Thanks!

**Comment by argiepiano** [comment]
Thanks, @aniketh-varma. This is in `views_plugin_display.inc`. I hope this helps.

**Comment by stpaultim** [comment]
We have a PR for review. Thanks @aniketh-varma

**Comment by stpaultim** [comment]
Looks good to me. Thanks @aniketh-varma.

Does anyone want to add this to bugfix milestone.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4025 into 1.x and 1.21.x. Thanks @aniketh-varma for taking this on! And thanks to @stpaultim and @argiepiano for the reviewing!
