### ISSUE TITLE
Views exposed sort is not working.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1324]
To reproduce:

1) create a view
2) add at least one sort criteria
3) click on that sort criteria to edit it
3a) check the box for "Expose this sort to visitors, to allow them to change it"
4) Apply the change to the view
5) click on that sort criteria to see that the setting was not set.

It looks like there's some kind of ajax magic that's supposed to happen when exposing filters. It works on Drupal 7, but fails in Backdrop. Posting a video now to demonstrate. Here we go: http://screencast.com/t/cYmnGCvIA

**Comment by jenlampton** [comment]
It looks like there's some kind of ajax magic that's supposed to happen when exposing filters. It works on Drupal 7, but fails in Backdrop. Posting a video now to demonstrate. Here we go: http://screencast.com/t/cYmnGCvIA

**Comment by serundeputy** [comment]
if you disable javascript it works.
so as a workaround for now you can, in chrome:

* right click inspect element
* developer tools settings (fn + f1 (on da mac))
* click disable javascript
* configure your sort 

you must leave the inspect element open with this method of disabling js.

but seems like the culprit is js.

**Comment by jenlampton** [comment]
thanks @serundeputy I also found that if i remove the display:none from the button, I can get it working enough to save the view.

**Comment by laryn** [comment]
Just ran into this issue myself. Looks like the PR from 2016 is unrelated, right?

**Comment by stpaultim** [comment]
I just ran into this issue myself.

**Comment by klonos** [comment]
This is a serious feature regression to not have been sorted for so many years. I am setting a milestone so to keep it in our radar.

**Comment by jenlampton** [comment]
Perhaps related to https://github.com/backdrop/backdrop-issues/issues/1909? (There is a PR over there for testing!)

**Comment by jenlampton** [comment]
no PR here, removing milestone. Adding the milestone-candidate tag so it can get into the next bug-fix release as soon as we have a PR.

**Comment by stpaultim** [comment]
Just working on a site for survey.backdropcms.org and ran into this problem again. This would be a nice one to get fixed. As far as I can tell, it seems like we still don't know why this is happening.

**Comment by indigoxela** [comment]
Also confirmed this bug.

Getting that setting to behave like in Views in D7 isn't hard, the "#ajax" part was missing in function show_expose_button().

A [PR](https://github.com/backdrop/backdrop/pull/3513) is available for testing and review.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏 ...I haven't tested yet, but the code change looks good, and it is consistent with the respective code in the `else` that follows 👍 

Wondering why this `#ajax` part doesn't exist in the respective code for the 3.x and 8.x versions of Views. See:

- https://git.drupalcode.org/project/views/-/blob/7.x-3.x/handlers/views_handler_sort.inc#L119
- https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/views/src/Plugin/views/filter/FilterPluginBase.php#L495

**Comment by indigoxela** [comment]
> Wondering why this #ajax part doesn't exist in the respective code for the 3.x and 8.x versions of Views

The `#ajax` form item property exists only in Backdrop, see the [Form API page](https://api.backdropcms.org/form_api#ajax) for details.

I figured out what's missing by comparing the functioning views_handler_filter.inc with the broken views_handler_sort.inc in Backdrop.

**Comment by klonos** [comment]
Thanks @indigoxela ...I've now also tested using the steps provided in the issue summary by @jenlampton, and things work as expected 👍

**Comment by quicksketch** [comment]
Thanks so much @indigoxela for figuring this one out! So great to have some of these old yet very important issues fixed! I merged https://github.com/backdrop/backdrop/pull/3513 into 1.x and 1.18.x.
