### ISSUE TITLE
Deleting a view

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1325]
How do I delete a view that I have created but no longer need? Is there a menu option somewhere or should I just delete the configuration file from the active config files?

**Comment by serundeputy** [comment]
@Graham-72  Is this what you need?

<img width="1472" alt="screen shot 2015-11-03 at 5 48 46 pm" src="https://cloud.githubusercontent.com/assets/6763671/10924207/372fb0a4-8253-11e5-8355-1528c02cb3e7.png">

**Comment by Graham-72** [comment]
.Yes thanks. I was in a muddle because I cloned an admin view  and then found no delete option.

**Comment by Graham-72** [comment]
This is what confused me. I think the 'REVERT' option was what I needed for this clone of an admin view.
![untitled-2](https://cloud.githubusercontent.com/assets/10559274/10930956/25a96010-82bb-11e5-8d9c-3bd4af9360f3.png)

**Comment by quicksketch** [comment]
Ah, thanks @Graham-72! That's a tough bug to find! I bet when we clone an a default view provided by a module, we don't update it's "storage" value in the config file to indicate it's a user-created view, so it still thinks it's a default, module-provided view. If you use the "Revert" option, does it delete the view?

Internally, Revert and Delete use the same form, but Revert copies in a default version of the view from whatever module provided it.

**Comment by Graham-72** [comment]
Yes, it does delete it. Although from the on-screen comments "Reverting the view Clone of Admin Content will restore it to the original settings provided by the "node" module." and "The view Clone of Admin Content has been reverted to its defaults." one might expect, after editing a clone, to revert to the unmodified clone.

I have just discovered how useful it is to be able to clone and then adapt an admin view in order to show pre-selected types of content, also both published and all unpublished rather than just 'own unpublished'. I'm happy!

**Comment by klonos** [comment]
> I have just discovered how useful it is to be able to clone and then adapt an admin view in order to show pre-selected types of content, also both published and all unpublished rather than just 'own unpublished'. I'm happy!

That's the whole point of [Administration Views](https://www.drupal.org/project/admin_views) in core, a.k.a. #151

**Comment by Graham-72** [comment]
Respect!
