### ISSUE TITLE
Views " Show hierarchy in dropdown " not working.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1326]
When you select the option " Show hierarchy in dropdown " for a views exposed filter for something like a taxonomy term, you expect to see sub-items indented with `--` in the list of available options.

Currently, all the options are missing from the drop-down, and the only thing available is `- Any -`
![screen shot 2015-11-03 at 2 37 43 pm](https://cloud.githubusercontent.com/assets/397895/10923950/844a2416-8238-11e5-8cf7-1e9200a16003.png)
![screen shot 2015-11-03 at 2 38 36 pm](https://cloud.githubusercontent.com/assets/397895/10926492/c61508c0-824c-11e5-8931-24e6c64eebfd.png)

**Comment by Dinornis** [comment]
I believe this has been fixed.  Closing.

**Comment by klonos** [comment]
Yep, confirming fixed 👍
