### ISSUE TITLE
[UX] Allow custom.css for CKEditor

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#1328]
Allow the definition of a custom path for the CK editor rendering, so users could edit content in a bit more WYSWYG way.

**Comment by quicksketch** [comment]
You can do this already by specifying a CSS file in your theme's .info file, to attempt to match your front-end CSS and editor CSS.

In your theme .info file:
```
ckeditor_stylesheets[] = css/ckeditor.css
```

You can also use `hook_ckeditor_css_alter()` in your module or theme.

Docs for both: https://api.backdropcms.org/api/backdrop/core!modules!ckeditor!ckeditor.api.php/function/hook_ckeditor_css_alter/1

**Comment by jdanthinne** [comment]
So simple… thanks Nate.
