### ISSUE TITLE
Users in the search index are not properly re-indexed.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1329]
We're missing an implementation of hook_search_reset:

``` php
/**
 * Implements hook_search_reset().
 */
function user_search_reset() {
  db_update('search_dataset')
    ->fields(array('reindex' => REQUEST_TIME))
    ->condition('type', 'user')
    ->execute();
}
```

**Steps to reproduce:**
- create some users
- run cron to index your content
- check the database to confirm that user records are valid
- visit the search settings page and invalidate the index
- check the database to see if user records have been invalidated

Before the patch, the last step will reveal that the user records have not been invalidated, after the patch, they will.

**Comment by quicksketch** [comment]
This looks like a situation that needs tests.

I couldn't figure out how to even reproduce the problem to confirm this fixes it. Although a straight-forward fix, reproducing and confirming this problem isn't obvious.

**Comment by jenlampton** [comment]
Steps to reproduce are in the main issue.

**Comment by jenlampton** [comment]
I'm closing this issue because it looks like users are not in the search index at all. The user search page loads them with `user_load_multiple()` instead.
