### ISSUE TITLE
[UX] Rename the "Promoted to front page" factor in Search settings -> Content ranking to "Promoted".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1335]
Follow-up task for #1190 (should we decide to go forward with what is proposed in that issue).

No matter what we decide to go with in the end, if we do change the checkbox label, we should also change the respective factor in the _Content ranking_ section under `admin/config/search/settings`.

**Comment by sutibun** [comment]
^_^)b go for it since we're going with "promoted" as the doc said

**Comment by jenlampton** [comment]
I think this is actually part of https://github.com/backdrop/backdrop-issues/issues/1190 and we should do it in the same PR :)
