### ISSUE TITLE
[UX] Simplify and improve the "Search items" section under admin/config/search/settings

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1336]
Part of #1332...

Here's what this part of the UI looks like currently:

![backdrop-search_items-current_look](https://cloud.githubusercontent.com/assets/2423362/10997920/2ef9c728-84e5-11e5-8c58-560f207faa6a.png)

Notice how the same options presented in the _Available search items_ sub-section exist right below it in the _Default search_ sub-section? Unnecessary repeating of things if you ask me.

Here's how I propose we make it look like instead (basically the same idea as the way we set default theme):

![backdrop-search_items-proposed_mockup](https://cloud.githubusercontent.com/assets/2423362/10997976/a19fff22-84e5-11e5-9118-14f5089ebfd9.png)

So...
- Ditch the _Default search_ sub-section (keep the help text though - not sure how to adjust the wording).
- Bold the default search item and append a "(default search)" text to it.
- Add a "set default" link next to the rest of the available search items.

**Comment by klonos** [comment]
...how about "Only one search item can be set as default. This determines what appears at http://www.example.com/search."

**Comment by klonos** [comment]
...while at it, how about we replace the ```http://www.example.com/search.``` part with the actual path for the current site too and make it a link (opening in a new window/tab). That way people will be able to click and go to the search page to see what we are actually talking about.

**Comment by docwilmot** [comment]
> Add a "set default" link next to the rest of the available search items.

How about just **one** "Set default" link that opens a dialog? 

> ...while at it, how about we replace the http://www.example.com/search. part with the actual path..

Nice.

**Comment by klonos** [comment]
...here's version 2 of the mockup:

![backdrop-search_items-proposed_mockup](https://cloud.githubusercontent.com/assets/2423362/10998357/baa346b6-84e8-11e5-91b9-37cdbdf5f7bc.png)

- path to search URL converted to an actual link
- Fieldset label set to "Available search items"

**Comment by klonos** [comment]
> How about just **one** "Set default" link that opens a dialog?

Would not mind, but the way it works in the themes admin page, clicking the "Set default" link next to each theme actually does the thing + throws a nice "*[theme-name]* is now the default theme." message and it does it in a single click. Using a dialog would require 3 clicks instead (click on the "Set default" link -> select from the list (radio-set) of available search items -> click on the confirm button).

The one thing that bothers me though with the single-click solution is that it would reload the whole form and that might mean that any setting that the user has previously set (before they scroll down to the "Available search items" fieldset), would then be lost(??).

**Comment by sutibun** [comment]
How about a dropdown menu? Sort of like when you select the admin theme under "/admin/appearance"

**Comment by klonos** [comment]
Yeah, that could work I guess.

**Comment by klonos** [comment]
...another mockup with drop-down instead of radio set:

![backdrop-search_items-proposed_mockup](https://cloud.githubusercontent.com/assets/2423362/11013893/04f425e2-8574-11e5-89fb-6627f2a84885.png)

This would address the issue with the previous mockup ("set default" links next to each search item except the one currently set as default) of loosing form data if user clicks on the link. It would also work if the user wants to enable a search item and set it as default in one go. We'd simply have to list all search items in the drop-down menu (as opposed to only listing enabled ones). If the user selected a disabled item from the drop-down menu, then upon form submit we'd enable it for them.

**Pros**:
- 2 clicks instead of 3 (compared to using a dialog)
- enable search item and set as default in one go
- no form data loss (compared to using the "set default" links)
- less UI clutter than using a separate radio list for setting the default (especially as more search items become available)

**Cons**:
- 2 clicks instead of 1 (compared to using the "set default" links)
- more UI clutter than using "set default" links appended to each non-default search item

**Comment by klonos** [comment]
Closing this in favor of #3385, which proposes to use a UI pattern that we are using in the list where we manage available/default languages.
