### ISSUE TITLE
[UX] Improve adding blocks to layouts with drag & drop

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1339]
## Problem: How to add blocks to a layout?

When you want to add a block to a Bd layout ("/admin/structure/layouts/manage/X")
1. you're confronted with **multiple "add block" links** which makes everything look clunky like so:
   
   ![add-block](https://cloud.githubusercontent.com/assets/14132746/11018388/ea8af1ae-858c-11e5-9786-b78efc198a93.png)
2. Upon clicking it, you then have to scroll through many old blocks which is a jungle mess of **different types** of block (e.g. breadcrumbs, text blocks)
3. you **can only "load" blocks previously created**. To create new text blocks, you need to go elsewhere and then have to come back here.
## Solution: Introducing the Bd Ribbon for Layout builder

Now, I haven't fully fleshed out the details (lack of time) so I am throwing this out in its rough form to see if it's worth refining further.

Basically, what I suggest is we create a Bd "ribbon" (1) similar to the [Office ribbon](https://support.office.com/en-us/article/Use-the-Ribbon-instead-of-toolbars-and-menus-D946B26E-0C8C-402D-A0F7-C6EFA296B527) (though that wasn't the inspiration) where you have "icons" representing the different types of blocks you can add to a layout. (2)

![bdribbon](https://cloud.githubusercontent.com/assets/14132746/11018362/a585e772-858b-11e5-9272-749e1ea025a6.png)

At the moment, what I am thinking is you drag the text block icon, for example, and drop it wherever you want in the layout. The moment you've selected where it will be, a pop up appears offering the option to create a new block or select a previously created one. Something like so:

![create-block](https://cloud.githubusercontent.com/assets/14132746/11018489/b7d65b82-8590-11e5-8a3f-4bf23be6daf5.png)

Because we know what type of block the user dragged and dropped, it only makes sense to filter the list to show only those types of blocks. 
- if drag-and-drop text block type, list in pop up will show only previously created text blocks
- if drag-and-drop breadcrumb type, list in pop up will show only previously created breadcrumb blocks
- if drag-and-drop a search form, list in pop up will show only search form blocks

And to take into account for future expansion of new types of blocks, that's where the "ribbon" comes in. For now, we can distinguish between core and contrib built blocks but suppose later can better classify them better via the tabs for better organization and compactness.

Also, if you click the "create new X block" in the pop up, a new pop up appears going through the process of creating that type of block. (As opposed to loading a new page)

Anyway, the icons on the ribbon makes the layout builder appear more approachable.

Good, bad, meh?

**Comment by quicksketch** [comment]
I think there are some good ideas here, but I'm not sure about the return on investment. It would definitely *feel* more sophisticated, but it would also be more difficult to manage on small screens (though it would probably work well with touch-devices).

Things I like:
- You'd be able to position a block's order at the same time as adding it. Right now when you add a block it always is added to the bottom of a region.
- Visualization of types of blocks may help find things faster. It definitely would give the UI a modern, touch-friendly concept.

Downsides:
- If your layout was very tall, it may be difficult to drag from the top of the page to the bottom (which may be offscreen), especially on small devices. A "floating" palette may help, but then you're giving up more real-estate.
- We'd obviously need to make images for each different category of block that could be added.
- I didn't expect that we'd show a list of blocks after dragging in a block. Just from the (very good) mock-ups, I was surprised when you visualized a list dialog. I would think, "But I just dragged in a block! Why are you asking me which block I want?"

Maybe we'd want to keep the current "Add block" button concept and add the ribbon as an alternative? The two ideas are compatible with each other with only a little work.

In any case, I think added a category filter is a good idea. I think we have an issue for that already. We should have a drop down as Views does:

![selection_028](https://cloud.githubusercontent.com/assets/100206/11078241/80b0a84e-87b9-11e5-98ab-19c12ca4f00e.png)

As for adding a new custom text block, I think that will be mostly solved with #1099.

**Comment by sutibun** [comment]
Ah ok. I didn't even think about small screens.

Closing ticket then.
