### ISSUE TITLE
Modules not picked by Backdrop CMS website repository

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#1341]
Hi,
I'm the main maintainer of  addanother, custom_search, float_filter, login_destination, logintoboggan, menu_position, transliteration, views_load_more, and waypoints.
I've added the required *type=module* and *version=1.x-1.x.x*, and made releases on GitHub for each of them, but I can't see any of those module on the Backdrop official website. What am I doing wrong?

**Comment by serundeputy** [comment]
https://api.backdropcms.org/creating-official-contrib-releases

* go to your release https://github.com/backdrop-contrib/logintoboggan/releases/new?tag=1.x-1.0.2 and
* click edit
* add title and description 
* save 

see if that does the trick for you

**Comment by klonos** [comment]
Issue should be filed under https://github.com/backdrop-ops/contrib/issues

**Comment by jdanthinne** [comment]
@serundeputy :Thanks, I was just creating tags, not releases. Everything is working fine now.

**Comment by quicksketch** [comment]
Great, thanks @jdanthinne for porting and making those releases!

@serundeputy++

**Comment by jdanthinne** [comment]
You're welcome!
