### ISSUE TITLE
@file docblock for run-tests.sh

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1343]
If we put it at the top of the file with a @file indicator, it will show up at https://api.backdropcms.org/api/backdrop/core!scripts!run-tests.sh/1 (without having to click the "Show source" button).

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/1117

**Comment by quicksketch** [comment]
Looks good! I made a few suggestions at https://github.com/backdrop/backdrop/pull/1117/files.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/1117. Thanks!
