### ISSUE TITLE
PHP Notice: Undefined property: Node::$comment_count 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1346]
Somehow the property comment_count is not always being added correctly to nodes when they are loaded.

```
Notice: Undefined property: Node::$comment_count in backdrop/core/modules/comment/comment.module on line 728
```

here is the line of code:

``` php
if (($node->comment_count && user_access('access comments')) || user_access('administer comments')) {
...
  }
```

An easy solution to preventing this PHP notice would be to wrap this if statement in a `property_exists()` check, but I think the bigger issue is why is the property not being added?

In `comment_node_load` it looks like comment_count is in  fact only added when comments are not set to hidden, and in this case the error shows up when comments are set to hidden. Looks like the `property_exists()` check is the right way to go here.

**Comment by quicksketch** [comment]
Posted another feedback to the PR: https://github.com/backdrop/backdrop/pull/1118#discussion-diff-49271819

**Comment by jenlampton** [comment]
Updated as per latest feedback, and rebased: https://github.com/backdrop/backdrop/pull/1118

**Comment by quicksketch** [comment]
Merged into 1.x and 1.2.x. Thanks!
