### ISSUE TITLE
Views NO RESULTS BEHAVIOR does not work as intended

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1347]
Steps to reproduce:
1) create a view that will generate no results.
2) under NO RESULTS BEHAVIOR add Global: Text area
3) enter a title
4) enter content into the textarea using the Filtered HTML format.
5) Save the view and test.

Where is your empty text?

6) edit the view
7) change the format to Full HTML.
8) save the view.

Oh, there it is!

**Comment by klonos** [comment]
Works fine for me with "Filtered HTML" format:

![backdrop-issue1347](https://cloud.githubusercontent.com/assets/2423362/11093348/d7095ab8-88dd-11e5-9c3c-8d9350e96777.png)

**Comment by sutibun** [comment]
she made up a problem ^\_-

**Comment by serundeputy** [comment]
worked for me too; tried page display and block display;

@jenlampton perhaps export the view so we can look at the view config (gist); maybe the filters or something have more to do with it then the text format.

**Comment by quicksketch** [comment]
:see_no_evil: 

@jenlampton Could you give this another go?

**Comment by jenlampton** [comment]
yeah totally works now. Thanks for adding the label @Dinornis :)
