### ISSUE TITLE
Checkbox description should precede checkboxes.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1351]
I find it unhelpful that the description of a set of checkboxes appears after the checkboxes as shown below. Is this normal PHP form behaviour?

![simple access settings - www oliverweb net 2015-11-14 05-50-05](https://cloud.githubusercontent.com/assets/10559274/11162346/a34b8f7a-8a95-11e5-90b3-eb927d81356d.png)

**Comment by sutibun** [comment]
It should.

**Comment by klonos** [comment]
There are D7 contrib modules that address this issue, like https://www.drupal.org/project/fel, and this has been natively addressed in D8 core: https://www.drupal.org/project/drupal/issues/314385

We already have #1403, so I will go ahead and close this one here.
