### ISSUE TITLE
Google Cookie Choices

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1354]
http://www.cookiechoices.org/

I'm not 100% sure about this, but I feel that we should do something about it. It is a requirement by EU laws and people that build websites need to comply. Why not help them out of the box instead of having them go either get a contrib module (if one is created/ported) or build something custom in their theme? better site-builder experience? Here's what I had in mind:
- a default, simple message to be shown. Something like "This site uses cookies. By browsing our website, you agree to our use of cookies. [I-understand-link]". No need for explaining cookie usage - we can point to some online documentation (Wikipedia for example?).
- a separate module or an option (checkbox in site prefs)? ...in core? ...disabled by default?
- a way to customize the message text (similar to email templates).
- easily themable.

Thoughts?

**Comment by klonos** [comment]
Turns out there is a Drupal module for this: [EU Cookie Compliance](https://www.drupal.org/project/eu_cookie_compliance)

...anyone up for porting it (please)?

**Comment by klonos** [comment]
...not many people use it though: https://www.drupal.org/project/usage/eu_cookie_compliance

**Comment by Graham-72** [comment]
> ...anyone up for porting it (please)?

@klonos I have made a start but have hit a problem that requires me to learn a lot more about how Backdrop builds pages, and what to do without hook_page_build. See https://github.com/backdrop-ops/contrib/issues/118.

**Comment by biolithic** [comment]
Another thing to be mindful of is that:

if (module_exists('geoip') || module_exists('smart_ip') ||
function_exists('geoip_country_code_by_name') ){

Do these modules exist in Backdrop as well?

Some replacement options for build function could be:

hook_preprocess_page()
hook_init()

Anyways, good start!

**Comment by mikemccaffrey** [comment]
Personally, I feel like these cookie notices are meaningless, since nearly every single site uses cookies in one way or another to track their users, but the popups don't provide much additional insight for visitors into exactly how that tracking is being done and for what purpose. At some point this law is going to need to change.

Can we just stick to the contrib module solution started in backdrop-ops/contrib#118?

**Comment by Graham-72** [comment]
Whilst I share your sentiment, I cannot see our EU requirement changing for quite a while. Part of the requirement is that the site should provide information about the cookies that are in use so that visitors can get that additional insight, though I doubt that many bother.

**Comment by Graham-72** [comment]
A Christmas present for @klonos and all EU site builders - first release of EU Cookie Compliance module https://github.com/backdrop-contrib/eu-cookie-compliance/releases/tag/1.x-2.1.0

**Comment by klonos** [comment]
Thanx @Graham-72. Merry Xmas @everyone.

**Comment by BWPanda** [comment]
Shall we close this in favour of contrib options? I believe there are more available now...

**Comment by BWPanda** [comment]
No response for quite a while. Closing.
