### ISSUE TITLE
Views: 'Output this field as link' doesn't replace tokens in path

### ISSUE THREAD

**Issue by d26435** [backdrop/backdrop-issues#1356]
In a view the tokens in the path weren't getting replaced. I've created a pull request with a fix at: https://github.com/backdrop/backdrop/pull/1124

**Comment by quicksketch** [comment]
Thanks @d26435! I'll get this merged shortly.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.2.x. Thanks @d26435!
