### ISSUE TITLE
Block display of view can show page content

### ISSUE THREAD

**Issue by d26435** [backdrop/backdrop-issues#1357]
If a view has a page display and a block display, and they are displayed at the same time, the block view can display the page view instead of its own. I also get several PHP warnings:

```
Notice: Undefined property: view::$current_display in views_preprocess_layout() (line 566 of /Users/daniel/projects/backdrop/backdrop/core/modules/views/views.module).
Notice: Undefined index: in views_add_contextual_links() (line 766 of /Users/daniel/projects/backdrop/backdrop/core/modules/views/views.module).
Notice: Trying to get property of non-object in views_add_contextual_links() (line 766 of /Users/daniel/projects/backdrop/backdrop/core/modules/views/views.module).
```

The problem appears to have something to do with reusing the cached view from `views_get_view`. In the drupal 7 version, it used `clone_view` which seems to fix the problem.

There is no such problem with a page including two different block displays of the same view. Only for seeing a block and page display at the same time.

**Comment by quicksketch** [comment]
Thanks, great fix in https://github.com/backdrop/backdrop/issues/1125! Solves the problem and IMO better than the D7 version. Merged into 1.x and 1.2.x.
