### ISSUE TITLE
[UX] Link to the Layouts admin page from the Custom blocks admin page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1360]
@stephit, https://github.com/backdrop/backdrop-issues/issues/1359#issue-118069106

> Put a link in the Blocks menu (or at least on the Blocks page) that directs people to Layouts where they can add blocks. This may be redundant but for the average user used to Drupal it is very confusing at first.

@quicksketch, https://github.com/backdrop/backdrop-issues/issues/1359#issuecomment-158604336

> Great idea. Just a note at the top of the page would be adequate. Like: `Custom blocks may be reused throughout your site on different pages. To place a custom block, configure a layout from the Layouts configuration page.` (with a link on the last 3 words). Let's make a separate issue.

Here it is :wink:

**Comment by klonos** [comment]
...trivial, but this might cause confusion and could use some clarification: ```... To place a custom block, ...``` (where?).

**Comment by klonos** [comment]
I think I'll take a quick stab at this UX-related issue, trying to make a start at solving it.

For reference, here's what the UI looks like in D9/10:
![image](https://user-images.githubusercontent.com/2423362/211682133-92f5d10a-96a7-486d-a1e9-afde75c178e1.png)

- the "Block layout" primary tab provides an easy way to go to the block placement page
- there's also some help text at the top of the custom blocks management page that provides a link to the "Block layout" page

I don't think that it would be possible to provide a primary/horizontal tab in Backdrop, since the custom blocks section and the layout management section are separate in the admin menu (yet both under the "Structure" parent item). We could consider moving the custom blocks link under `Structure` -> `Layouts`, but that's a matter for a separate (longer too I imagine) discussion. Perhaps discuss this in #2118(?).

**Comment by klonos** [comment]
Here's a simple PR that gets the job done: https://github.com/backdrop/backdrop/pull/4305
![image](https://user-images.githubusercontent.com/2423362/211686155-21664152-f282-4fec-8ca9-73ae3fd09dc4.png)

The help text added is this:
> Custom blocks allow placing arbitrary text in layout regions. Blocks created here become available to be placed in any layout in the [Layouts]() page.

Some wordsmithing might be in order, so happy for any feedback.

**Comment by olafgrabienski** [comment]
> Some wordsmithing might be in order ...

If I understood correctly, the original suggestion was to indicate that it's also possible to *add* custom blocks on Layout pages (not only to place them). That's a tricky one, not sure how to say that in one sentence! Apart from that, I'd use the term "custom content" or something along those lines instead of "arbitrary text", as CKEditor allows to add text with images.

A small technical issue: The link to the Layout page leads to `example.com/admin/structure/admin/structure/layouts`.

**Comment by klonos** [comment]
Thanks for having a look @olafgrabienski 🙏🏼 ...I'll try to address those issues and will let everyone know when ready for another round of review/testing.

**Comment by bugfolder** [comment]
For that first line, how about just:

> These blocks are available to be placed in any layout in the [Layouts](https://github.com/backdrop/backdrop-issues/issues/1360) page.

**Comment by jenlampton** [comment]
> Custom blocks allow placing arbitrary text in layout regions. Blocks created here become available to be placed in any layout in the [Layouts](https://github.com/backdrop/backdrop-issues/issues/1360) page.

@klonos  for the text I would recommend:

`Blocks created here will be available to every layout on the Layouts page.` I don't think the first sentence adds much value.

**Comment by klonos** [comment]
Thanks @bugfolder and @jenlampton 🙏🏼 ...we can surely go with that, but what about what @olafgrabienski mentioned re the fact that reusable custom blocks can also be created directly from the Layouts page (in which case they will also be shown in the blocks listing page).

**Comment by bugfolder** [comment]
> what about what @olafgrabienski mentioned re the fact that reusable custom blocks can also be created directly from the Layouts page?

That was why I left out the "created here" phrasing:

> These blocks are available to be placed in any layout in the [Layouts](/admin/structure/layouts/list) page.

**Comment by klonos** [comment]
Thanks @bugfolder ...I went with your suggestion, since not mentioning "created here" is much better than omitting the fact that custom blocks can also be created elsewhere. Trying to accommodate both would make this help text unnecessarily wordy, and the simpler version gets the job done 😉 

@jenlampton @quicksketch would be great to get this in for 1.23.2 and 1.24.0.

**Comment by kiamlaluno** [comment]
(I thought it would be possible to add two milestones.)

**Comment by argiepiano** [comment]
@klonos, I'm not going to opine about wording (I'm not great at that, plus the people above have stronger opinions on that than I do). But I did add a comment about the way you return the new output. You are using `render()` before returning it. It's more efficient (and preferable) to return render arrays and let the Theming layer take care of the rendering. This also allows other modules to alter the output before it's rendered. 

Typically you want to delay the rendering of render arrays to the very end of the processes.

**Comment by klonos** [comment]
You are absolutely right @argiepiano ...fixed.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4305 into 1.x and 1.23.x. Thanks folks!
