### ISSUE TITLE
Upgrade jQuery UI to 1.11.4

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1363]
We are currently in [1.11.2](https://github.com/backdrop/backdrop/blob/1.x/core/misc/ui/jquery.ui.core.min.js)

[1.11.3 Changelog](https://jqueryui.com/changelog/1.11.3/)
[1.11.4 Changelog](https://jqueryui.com/changelog/1.11.4/)

**Comment by MrHaroldA** [comment]
Relates to #1362

**Comment by quicksketch** [comment]
Let's close in favor of https://github.com/backdrop/backdrop-issues/issues/1362.

**Comment by klonos** [comment]
This is for jQuery **UI** though. The other issue is about jQuery.
