### ISSUE TITLE
Add validation to prevent maximum value being less than minimum value

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#1366]
The core Number module has validation functions in `number_field_instance_settings_form()` to make sure maximum and minimum values are numbers. But there's nothing to stop the maximum value being set less than the minimum value...

I'm not sure if you could simply add another 'element_validate' function to the maximum field, or if you'd have to use a form-wide validation function instead since you'll need to get the value of the minimum field too to compare.

I noticed this in Drupal, but figured it'd have a better chance of being fixed here instead ;)

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2773

**Comment by klonos** [comment]
> I noticed this in Drupal, but figured it'd have a better chance of being fixed here instead ;)

:smiling_imp:

**Comment by klonos** [comment]
...long time no see BTW.

**Comment by klonos** [comment]
...just noticed that I made a couple of silly comments, but haven't actually commented on the issue itself. So, just wanted to say that your rationale seems very, ...well rational. :+1: to the idea and we hit two birds with one stone here since the check will at the same time ensure that the minimum value does not get greater than the maximum either :wink:

**Comment by BWPanda** [comment]
Thanks @klonos, I haven't been as active with Backdrop as I'd like to be lately, but hope to get back to it shortly. Now that D8 is out and I have absolutely no interest in learning it, I'll start looking at Backdrop as an upgrade from D7 for my clients in future.

**Comment by klonos** [comment]
Great news @BWPanda!! ...not for D8 :smiling_imp:

**Comment by sutibun** [comment]
"Say no to proposition D8"

( ^\_^)

**Comment by BWPanda** [comment]
Finally, a PR! :smiley: https://github.com/backdrop/backdrop/pull/2773

**Comment by BWPanda** [comment]
Considering people can currently enter maximum values that are smaller than minimum values, I'm labeling this a bug report.

**Comment by docwilmot** [comment]
Good catch, though belated. Need tests though?

**Comment by klonos** [comment]
RTBC 👍 ...I'll leave it core committers to add the `pr - needs automated tests` label if they see that as a requirement.

**Comment by quicksketch** [comment]
Hm, with validation on a single form and a low impact on anything else, this seems fine. Merged in https://github.com/backdrop/backdrop/pull/2773 into 1.x and 1.13.x.
