### ISSUE TITLE
[UX] Standardize layout for Configure module page

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1369]
Here is a quick idea that came to me some time ago though may be too vague/broad. Hope it makes sense. Here we go.
## The problem: Unorganized options give illusion that they all deserve equal attention

Some module configuration pages use a one column layout which poses subtle problems
1. they expose all possible configuration options at once, listed one after another. Because there is no clear hierarchy, the user naturally assumes all of the options are of equal importance so she has to go through every item and try to understand each one. However, not all options contained in a configuration page need to be highlighted and considered right away. This is problematic because it unnecessarily increases friction and possibly confuses the user. (user might get stuck on an option that they'll scratch their head but they won't know it's not necessary to get a module set up)
2. creates bad readability (ala #1299)
## Solution: Where it makes sense, use a two column layout

I suggest considering a two column layout (where appropriate) Here is a rough sketch

![setttings-layout](https://cloud.githubusercontent.com/assets/14132746/11413195/ee8148a8-93ab-11e5-9f9a-3d36d8f6db91.png)
- The left-most (and wider) column will be the place for config options that 80% of users will likely need to concern themselves with. i.e. What they need to tweak to get up and running.
- The right-most column will be for options that are either a lil' more advance or deemed "archaic". Maybe for the "the kitchen sink". Or can be covered with a smart default so normal users don't have to worry about them as much.

It's like when you look at a newspaper. The headline captures your attention and appears more important because it's larger than the body copy. Your eyes can rest there and you'll get the gist of the article without reading the smaller text. Same idea here.

Users will be trained in time to focus on the first column and that it's ok to not over think the second column and stick with defaults there.

What's great about this is 
- this layout will help new users blast through configuration pages and avoid getting stuck on options that in the end they don't really have to worry about too much. Less friction = better UX.
- the mobile version will bring the advance section below the basic settings. (meaning its of lesser importance)
- we don't lose the power of Bd... it's just safely tucked away. More importantly, we refine what we present to new users and thus improve the UX for newcomers to get on with their site building.
#### Example 1: Date & time

Let's assume #1284 is implemented for editing date and time formats:

> Alternatively, remove the textfield display and have a select list display all common display formats.

For the majority of users, all they need to see is the select list.

> Have an "advanced configuration" link below the select that allows you to use the archaic letters to build custom formats.

For power users who want further customization than what's provided, they'll go to the second column and enter the PHP formatting there.
### Example 2: Search settings

There is a discussion in #1321 over the "re-index site" button in the search settings page and how new users might be tempted to click on it. I'd argue that it's not simply because of the wording but its position. What's all the way on top users will naturally think is important and more likely click.

Not only that, I'd ask: is that button something 80% of normal users have to worry about such that it needs to be highlighted so prominently?

If we use the two column layout approach for this config page to better organize this so it's easier for users to distinguish importance, here is how I'd slice it.
- **Column 1: Of concern to 80% of normal users**
  - ACTIVE SEARCH MODULES. Why? They might want to exclude certain content types from appearing in search. Each site will be different.
  - CONTENT RANKING. Why? This is a personal preference. Users can "play" with this and see what they value most and influence what items rank better for their site. A preference of sorts.
- **Column 2: Of concern to a few 20% ("Advanced")**
  - INDEXING STATUS. Why here? Will most users need to worry about re-indexing or even click this button often?
  - INDEXING THROTTLE. Why here? Throttle… cron... will most people understand that? I am sure a smart default will cover most use cases.
  - INDEXING SETTINGS. Why here? Descriptive text reads "The default settings should be appropriate for the majority of sites." If that is so, then we don't need to highlight it as much. A perfect candidate of a setting we can de-emphasize.

Now you may argue over my choices as to what belongs in the first and second columns, but at least we are shifting the conversation into what to present to normal users and what are essential settings that most users must focus on.

Because there's "less" options to consider upfront, there's less for new users to trip on

> Wow, customizing search in backdrop was easy. I only had to decide what kinds of content I want to appear and what will influence an item to appear on top

vs

> What's re-indexing and cron? I don't know what is the best choice for them. I understand the other items, just not the rest. They sound confusing.

The latter gives the impression of complexity. The former… not so much. We should no longer dump all possible config options on users and hope they can figure it out. Yes, descriptive text and labels help but not as much compared to "subtracting"

Just an idea.

**Comment by mikemccaffrey** [comment]
Hey @sutibun, I definitely think you are on to something with making sure that advanced options are given less emphasis. However, couldn't the problem be solved more easily by just putting advanced options in a fieldgroup that is closed by default? Also, on smaller screens, wouldn't your two columns need to be collapsed into one, bringing us back to the same situation with them all being listed together?

However, I'm definitely with you on the search form being confusing. It is weird to go under configuration to take an administrative action like re-indexing the site. I think we'd be much better off actions like that to a dedicated action center page or menu, kinda like I was talking about in #1368.

**Comment by sutibun** [comment]
> Also, on smaller screens, wouldn't your two columns need to be collapsed into one, bringing us back to the same situation with them all being listed together?

True, didn't think about that. Maybe collapse the second column in the mobile view?

> However, couldn't the problem be solved more easily by just putting advanced options in a fieldgroup that is closed by default? 

That's another good viable option. (Maybe should thought of that)

After posted this, also thought we could extract the "advanced" options and put them in its own page/tab. That way you'd have the "basic" vs "advanced" tab.

Either or for me.

I'm not too stuck on the exact implementation here. **I'm more concern about fine tuning what we present to users in the configuration pages** so we don't overwhelm them. 

I don't think it's necessary to remove/delete "advanced" options (not that you're saying that) and turn Bd into a mule. Bd can be powerful but still easy to pick up.

**Comment by BWPanda** [comment]
I'm concerned that moving advanced settings from the bottom of a page (where they currently are) to the top of the right column would actually make them more prominent...

I agree with what @mikemccaffrey said regarding using collapsed fieldsets. Put advanced settings in their own 'Advanced' fieldset and collapse it by default. We already have that ability in core, so it's just a matter of making those changes where appropriate.

I'm going to close this issue, but feel free to open follow-ups for specific implementations as needed.
