### ISSUE TITLE
[DX] Happy Thanksgiving!

### ISSUE THREAD

**Issue by PaulHoza** [backdrop/backdrop-issues#1372]
Happy Thanksgiving to those of you for which that's a thing, given our global audience.

Thank you to all the people working on Backdrop and all the various things attached to the project.  I appreciate all the work and effort, as well as the very kind and helpful community around all this stuff.

Cheers.

**Comment by sutibun** [comment]
Happy Festivus to those of you for which that's a thing :p

\*waves\*

**Comment by biolithic** [comment]
Thanks to you, Mr Cat for your bug fixes and happy thanksgiving to all!

**Comment by PaulHoza** [comment]
I've been airing my grievances all morning, so I guess I'm wholly in the
spirit.

**Comment by klonos** [comment]
On a religious level, not a thing for me. But I do respect it as a tradition and even though we should be thankful for the things we receive and have been blessed with all through the year and not only on a single day, still thank you Drupal & Backdrop and all those behind Open Source in general.

**Comment by Graham-72** [comment]
Happy Thanksgiving to all of you celebrating. Over here our turkeys have to wait for Christmas, which I look forward to celebrating on both a family and a religious level. And after that I shall be celebrating my first full year working with the excellent and helpful Backdrop team.
