### ISSUE TITLE
[SR][D8] Port and merge Secure Permissions in core

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1382]
Another module that's merged in D8 core: https://www.drupal.org/project/secure_permissions

Part of #378

Note: In the recently released Drupal 8.0.0 I could not find where/how this feature was added. Anyone that knows, please shed some light?

**Comment by BWPanda** [comment]
I don't know... Doesn't seem like an 80% use-case to me. I say better left to contrib.

**Comment by klonos** [comment]
> https://www.drupal.org/node/2619344#comment-10586930

> The key feature of secure_permissions (managing permission in core) is now possible with CMI in D8 core, so I have no plan to update this project.

So I guess this was not added to D8 after all. Closing.
