### ISSUE TITLE
[UX] Node form Submit button text should include Published state

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1383]
Another module that's merged in D8 core: https://www.drupal.org/project/save_draft

Part of #378 and also #1388

### Drupal 8

This was introduced in D8.0, although the respective option is not a separate "Save as Draft" button, but a secondary "Save as unpublished" option in the default "Save and publish" drop-button:

![d8-save_as_draft](https://cloud.githubusercontent.com/assets/2423362/11456126/6d0379ee-96d1-11e5-9791-55450c0c8c3a.png)

In D8.4 they have ditched the drop-button, and have reverted to a set of a Save" button + a "Published" checkbox. This time the "Published" checkbox is exposed just above the "Save" button, "outside the publishing options section of the right sidebar:

![screen shot 2018-06-03 at 8 47 15 am](https://user-images.githubusercontent.com/2423362/40881703-db92058a-6710-11e8-97a0-b4743f2350be.png)

### Wordpress 4.9

Here's how things work in the current Wordpress version (4.9.6 at the time of writing) for regular and scheduled content:

![screen shot 2018-06-03 at 8 01 50 am](https://user-images.githubusercontent.com/2423362/40881217-9664d868-6704-11e8-975c-a2bcf6a3f1ed.png)

![screen shot 2018-06-03 at 8 02 08 am](https://user-images.githubusercontent.com/2423362/40881219-9b7c973c-6704-11e8-8139-1a52fcad0c0a.png)

The high-level goal of this issue here should be to add a "Save draft" button, and to make it so that the label of the submit button changes to "Schedule" when the content is to be scheduled.

We should not go into the various options available for drafts (as these require a more sophisticated workflows system in place). We should also not go into the "Preview" button (as this is to be handled in #3062), nor into the "Move to Trash" (#2498). Although I am not saying that these should be on our radar; just out of scope for this specific issue here.

### Acquia Lightning distribution

Acquia Lightning distro (a D8 distro focused on content author experience and easier workflows), has implemented [their own custom version of Workflow](https://www.drupal.org/project/lightning_workflow). v1 had this UI:

![image](https://user-images.githubusercontent.com/2423362/40869636-f637ce1a-6661-11e8-9106-0ab007b76ea8.png)

...which they have now changed to this in v2:

![image](https://user-images.githubusercontent.com/2423362/40869638-0b74d2fa-6662-11e8-8727-e0a123d2ac85.png)

**Comment by laryn** [comment]
@klonos https://github.com/backdrop-contrib/save_draft

**Comment by klonos** [comment]
Thanx @laryn 😉

**Comment by mikemccaffrey** [comment]
Wouldn't we need to add those drop buttons to core first?

**Comment by klonos** [comment]
We don't have to implement the saving as draft action as a drop button. It can simply be a secondary button.

**Comment by herbdool** [comment]
In Drupal 8.3 there's an experimental workflow module which has three default states of draft, published, and archived https://www.drupal.org/blog/moving-the-drupal-8-workflow-initiative-along it's basically workbench but now has full support of core.

I'm not sure if that's necessary for Backdrop but Save Draft would be a good start.

**Comment by herbdool** [comment]
Found some interesting threads on people trying to get this into Drupal 7 and 8, including people talking about the 80% use case which is what Backdrop is focused on. This thread goes back years!

https://www.drupal.org/node/1123696
https://www.drupal.org/node/282122

**Comment by herbdool** [comment]
I noticed that the Drupal 8 save buttons are situationally aware such that it takes into account if the node is already created or not and already published or not:

![save-dialog1](https://cloud.githubusercontent.com/assets/1071483/21827746/f565503a-d75a-11e6-8f2b-7aaff2d1525e.png)
![save-dialog2](https://cloud.githubusercontent.com/assets/1071483/21827745/f563cb52-d75a-11e6-96ff-404773adf1fa.png)

With Save Draft it shows something similar by default on all content types:
![selection_004](https://cloud.githubusercontent.com/assets/1071483/21827799/39df5f62-d75b-11e6-8d97-c43b4b08c15d.png)
![selection_005](https://cloud.githubusercontent.com/assets/1071483/21827800/39e23c96-d75b-11e6-9870-68e17c85d623.png)
![selection_006](https://cloud.githubusercontent.com/assets/1071483/21827801/39e30eaa-d75b-11e6-8754-f1bd96696e23.png)

I think there should also be a checkbox per content type so that someone can choose to have the more basic buttons if for a content type the "publish/draft" terminology doesn't work.

And also need to test this with revisions turned on/off. Maybe it's not an issue if it's just replicating what the Published checkbox is doing.

**Comment by quicksketch** [comment]
After substantial user feedback in D8, they've found that (surprise!) no one could find how to unpublish content. They've now removed the drop buttons and gone back to a simple checkbox:

![image](https://user-images.githubusercontent.com/100206/39371872-c1c40ce2-49f7-11e8-8ee2-264041b03268.png)

Considering Backdrop already puts the Published checkbox in the first vertical tab, it's already always visible and at the bottom of the form.

I'm not a fan of making multiple buttons at the bottom of the form, it requires too much thinking (though our default "blue" buttons help with that).

**Comment by klonos** [comment]
I have now renamed this issue, but still leaving it closed until the scope of #3157 is defined.

**Comment by klonos** [comment]
...reopening and renaming again: https://github.com/backdrop/backdrop-issues/issues/3157#issuecomment-394119482

**Comment by klonos** [comment]
...here how things work in the current Wordpress version for regular and scheduled content (4.9.6 at the time of writing):

![screen shot 2018-06-03 at 8 01 50 am](https://user-images.githubusercontent.com/2423362/40881217-9664d868-6704-11e8-975c-a2bcf6a3f1ed.png)

![screen shot 2018-06-03 at 8 02 08 am](https://user-images.githubusercontent.com/2423362/40881219-9b7c973c-6704-11e8-8139-1a52fcad0c0a.png)

The high-level goal of this issue here should be to add a "Save draft" button, and to make it so that the label of the submit button changes to "Schedule" when the content is to be scheduled.

We should not go into the various options available for drafts (as these require a more sophisticated workflows system in place). We should also not go into the "Preview" button (as this is to be handled in #3062), nor into the "Move to Trash" (#2498). Although I am not saying that these should be on our radar. Just out of scope for this specific issue here.

**Comment by klonos** [comment]
...I have also add some screenshots from the Acquia Lightning distro in the issues summary (copied over from https://github.com/backdrop/backdrop-issues/issues/3157#issuecomment-394051588)

**Comment by klonos** [comment]
...updated the issue summary to also mention that Drupal has ditched the drop-down submit button in 8.4.x

**Comment by opi** [comment]
Related to https://github.com/backdrop/backdrop-issues/issues/3122#issuecomment-394109366 (both talking about button label)

**Comment by klonos** [comment]
WP demo (notice how the respective drop-button label changes as I select publish/draft/schedule):

![wp demo - publish draft schedule](https://user-images.githubusercontent.com/2423362/42245424-1c303be4-7f5c-11e8-977c-e804e71d5177.gif)

...also very nice touches:

- the addition of timezone at the end of the time widget: #3184
- theme changes can be scheduled for publishing!!! 😲: #3185

**Comment by jenlampton** [comment]
Updating the title here because I'm always confused about the intent of this issue.

**Comment by jenlampton** [comment]
Actually, I'm going to close this issue in favor of https://github.com/backdrop/backdrop-issues/issues/3157. @klonos you said you'd had other plans for this issue - but to avoid confusion can you open a new one instead?
