### ISSUE TITLE
inline-images disappear after a while

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1385]
After 1 day the directory is empty. I loaded one image with the Editor.

Backdrop 1.2.2

**Comment by Graham-72** [comment]
I have been having a similar  - see #1373 . In my case it has been only when the image is the sole content of a custom block. All my other images in inline-images are fine. I think we need to add this to the meta for CKEditor #1087

**Comment by quicksketch** [comment]
Yeah probably a duplicate of https://github.com/backdrop/backdrop-issues/issues/1373. Thanks @Graham-72.
