### ISSUE TITLE
Question-Answer module - please advice

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1387]
Hi!

I need a simple module to publish questions-answers on a Hotline page.

A questioner submits a question and then it will be published on only after it is answered by the website admin.

Please advice :)

Thank you!

**Comment by docwilmot** [comment]
[This sounds like what you want](https://www.drupal.org/project/faq_ask)

And here's [a comparison oof question modules](https://www.drupal.org/node/778368)

If you could research these options, maybe someone can port that for you.

**Comment by biolithic** [comment]
A general way to do this would be:

Users can make a node of content type hotline, which remains unpublished
after they make it.
Users can't see unpublished nodes.
An admin can then answer the question, appending to the node, and publish
the node.
Then everyone can see the question and answer.

This is an untested idea however, and stronger ideas have probably made.

**Comment by quicksketch** [comment]
It sounds like @biolithic's suggestion would definitely be the simplest. To make that most effective, I'd suggest a field for "Question" and a field for "Answer", and then install Field Permissions module (https://github.com/backdrop-contrib/field_permissions) to only access to the "Answer" field for administrators.

Unfortunately Field Permissions doesn't have an official release yet, so it's not listed on backdropcms.org and may not be 100% stable. Though @docwilmot was the original porter, so maybe help isn't too far away. :wink:

**Comment by docwilmot** [comment]
Field Permissions is mostly passing tests now, except for a weird URL problem, which is the test's fault, not the module. So will release shortly I suspect.

But I beg to disagree, at least in principle, with `It sounds like @biolithic's suggestion would definitely be the simplest`. The simplest would be to have a module which does this instantly on install. Gluing together fields and permissions and node displays is likely to be the ideal for the 'Drupal (Backdrop) way' but not for the market we're targeting. At least not until we have a nice tutorial site with such 'recipes' available and explained clearly.

**Comment by bd0bd** [comment]
Hi! Thank you very much @docwilmot, @biolithic  and @quicksketch!

I will try @@biolithic's suggestion.

**Comment by biolithic** [comment]
I agree doc's comment about write a module but if module people are busy,
you can see what you can do with core Backdrop permissions and so forth.

**Comment by klonos** [comment]
...I think it's OK to close this one after this long. Feel free to reopen if things are still pending action.
