### ISSUE TITLE
Views exposed 'Search keys' filter not working as expected

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1390]
I have a view with an exposed 'Search keys' filter. 
- When 'lange' is typed into that filter, I get many results containing 'lange'. Perfect. :)
- When I try to narrow the search by changing the keys to 'lange boot' (I can see the word boot in the previous set of results, so I know it _should_ work) I get no results. Broken. :(
- Then when I add a 2-letter word like "RS" into my search keys ('lange boot RS') it works perfectly again, and I get the exact set of results I'd expect - the ones that match all three keys. :)

Why is this happening?  
1) When views determines this is a "simple" search then it simply searches the search_index table for the keys provided.  That works well when you are searching for a single term.

2) The above method fails when you have more than one word to search for (not sure why yet).

3) When views determines the search is not a "simple" one (like when you include a 2-letter word in your search, since that word is not in the search index) it then has to look in the search_dataset table instead. This works again because the problem in 2) above is avoided.

**Comment by jenlampton** [comment]
I'm also seeing this problem: https://www.drupal.org/node/1677692

**Comment by jenlampton** [comment]
So... I hacked the snot out of search module and everywhere there was a 'if not simple' check I added an 'OR TRUE' so that we'd still add the search_dataset table to the query.  Seems to be working so far...  will work on a more serious fix shortly.

**Comment by quicksketch** [comment]
Ha, thanks. Clearly this needs more work yet. I've closed https://github.com/backdrop/backdrop/pull/1293 until you (or someone else) gets a chance to work on a real fix.

**Comment by jenlampton** [comment]
I think this will be fixed with https://github.com/backdrop/backdrop-issues/issues/3685, I see there are some new changes in these particular files that seem to help!
