### ISSUE TITLE
user_role_permissions() is not very useful

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1392]
If you put in an array of roles as the parameter, the Drupal version returned

```
 an array indexed by role ID... Each value is an array whose keys are the permission strings for the given role ID.
```

Very nice. Backdrop's version simply prints a single unindexed array of all permission strings, not keyed by role, just a mishmash. Not nice.

I find myself having to do 

```
  $role_names = user_roles(FALSE, NULL, TRUE);

  foreach ($role_names as $key => $robject) {
    foreach ($robject->permissions as $perm) {
      $role_permissions[$key][$perm] = TRUE;
    }
  }
```

which is a bit tedious instead of a single function. Is there an alternative function which does same? 

I suppose by now it would be an API change to revert this though.

**Comment by quicksketch** [comment]
The Backdrop version does differ from the Drupal version, so you're right this needs a change record. I expected it to be part of https://github.com/backdrop/backdrop-issues/issues/177, but I seemed to have forgotten to include it there. Perhaps we should just update https://api.backdropcms.org/node/26870, as I'm pretty sure that change was part of the CMI update.

There aren't any replacements for the D7 behavior, though you could shorten your code with:
```
$role_permissions = array();
foreach ($account->roles as $role_name) {
  $role_permissions[$role_name] = user_role_permissions(array($role_name));
}
```

**Comment by docwilmot** [comment]
Duplicate!!
https://github.com/backdrop/backdrop-issues/issues/813
