### ISSUE TITLE
Unused Block IP addresses permission should be removed

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1394]
We have a permission for blocking IP addresses but where is it? I cannot find it. 
In D7 it is at /admin/config/people/ip-blocking. Here is a screenshot of Backdrop permission settings.
![permissions - browsers bookshop 2015-12-03 06-38-56](https://cloud.githubusercontent.com/assets/10559274/11553809/445b7436-998a-11e5-8218-78e567452c05.png)

---
PR: https://github.com/backdrop/backdrop/pull/2611

**Comment by klonos** [comment]
Not a reply to what you are asking, but I think we should implement #1169 and have these live under a Config -> Security page.

**Comment by klonos** [comment]
...according to https://www.drupal.org/documentation/modules/ban

> ... /admin/config/people/ban in Drupal 8, or /admin/config/people/ip-blocking in Drupal 7. In both cases, you can find the Ban page listed under Administration >> Configuration >> People.

Could not find it in Backdrop :question:

**Comment by quicksketch** [comment]
Whoa! Nice find @Graham-72! I don't know how we missed that. Banning IP Addresses is indeed not part of Backdrop core. We should remove that permission.

**Comment by Graham-72** [comment]
I was looking for it in the hope of using it. Never mind.

**Comment by quicksketch** [comment]
> I was looking for it in the hope of using it. Never mind.

Doh! Would make a great contrib module though.

**Comment by quicksketch** [comment]
I don't think this is documented, we need to make a change record for it.

**Comment by klonos** [comment]
I actually think that we should implement this as a feature. Both D8 and D7 include a ban IP feature. More on it here: [Ban an IP address](https://www.drupal.org/documentation/modules/ban)

I'll file a separate feature request issue and we can close either that or this one here depending on what we decide.

**Comment by klonos** [comment]
I have recently had to battle a case that caused the `cache_from` table in the db to be flooded. This triggered storage limit notifications, which required manual truncation of the table in order to bring the site back online.

This issue with cron apparently choking when trying to clean huge chunks of caches seems to be another long-standing, known issue with Drupal, so I have filed #3191 to dal with it, but banning malicious IPs could prevent this situation from happening in the first place. We should definitely bring back the ban IP feature in Backdrop core, and also automate it.

Can we please close this in favor of #1878?

**Comment by jenlampton** [comment]
This issue is closed, but I still see the problem permission in core. re-opening.

**Comment by jenlampton** [comment]
Filed a new PR to remove the confusing permission for now. https://github.com/backdrop/backdrop/pull/2611

We can add something similar back if/when we decide on which ban module to add to core.

**Comment by docwilmot** [comment]
RTBC

**Comment by BWPanda** [comment]
How do change records work? Can we merge the PR and leave this issue open for the CR thing, or have to do that before merging?

**Comment by docwilmot** [comment]
It doesnt doesnt do anything anyway, so it should affect zero sites. So we can document after merging

**Comment by BWPanda** [comment]
Thanks @jenlampton, @Graham-72, @klonos, @quicksketch & @docwilmot! Merged https://github.com/backdrop/backdrop/pull/2611 into 1.x and 1.15.x.

**Comment by BWPanda** [comment]
Oh, re-opening as still needs change record...

**Comment by jenlampton** [comment]
Added a change record, here: https://api.backdropcms.org/change-records/ip-address-blocking-removed-from-core
