### ISSUE TITLE
Remove type="text/javascript" from script tags

### ISSUE THREAD

**Issue by dboulet** [backdrop/backdrop-issues#1397]
In HTML5, the `type` attribute on the `<script>` element is optional, and as far as I know, no browsers require it. Since `text/javascript` is the default value for this attribute, we can save some bytes by removing it from script tags output by Backdrop.

**Comment by quicksketch** [comment]
Sounds like a good idea to me. FYI from 2010: http://stackoverflow.com/questions/4195427/is-the-type-attribute-necessary-for-script-tags

It seems unlikely that people would start building new sites that need to validate as HTML4 or XHTML 1.x, so I'd be for dropping the attribute.

**Comment by dboulet** [comment]
> It seems unlikely that people would start building new sites that need to validate as HTML4 or XHTML 1.x

Agreed, especially since Backdrop already uses the HTML5 doctype and, let’s face it, it’s almost 2016. Anyone absolutely needing to validate against ancient standards can revert these changes in custom code.

@quicksketch Would you also agree to dropping the CDATA wrapper for inline scripts?

**Comment by dboulet** [comment]
Opened new PR: https://github.com/backdrop/backdrop/pull/1135

**Comment by quicksketch** [comment]
> Would you also agree to dropping the CDATA wrapper for inline scripts?

Yes please.

I think the PR looks great @dboulet! Just a confirmation, does the new markup validate as it should against http://validator.w3.org? Even if we're leaving XHTML behind, it would be good to ensure that the new CDATA-less approach validates via HTML5.

**Comment by dboulet** [comment]
>  does the new markup validate as it should against http://validator.w3.org?

Yes, it does. It looks like the validator automatically switches to the Nu HTML Checker when it detects an HTML5 doctype. No warnings at all, even with the missing CDATA wrappers.

As a follow up to this issue, we can probably also remove the wrappers from inline CSS.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop-issues/issues/1429 into 1.x. This will be in 1.3.0.

**Comment by quicksketch** [comment]
Thanks for bringing us into the present @dboulet! I also love the cleaner and simpler HTML output. Less mess makes for happier front-enders.

**Comment by quicksketch** [comment]
Follow-up for style tags also now fixed at https://github.com/backdrop/backdrop-issues/issues/1429.
