### ISSUE TITLE
[DX] Better error handling when a config file read fails

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1400]
I was getting the following error:
```
ConfigStorageReadException: The configuration file "socialfield.settings" could not be read in ConfigFileStorage->read() (line 898 of /backdrop/core/includes/config.inc).
```

And I spent about 30 minutes debugging permissions, since the error said the file could not be *read*.  The actual problem was that the JSON in the file was not valid, so we should state that explicitly here instead.

How about something like:
```
The configuration file "socialfield.settings" is not properly formatted JSON
```

**Comment by biolithic** [comment]
I've seen this error message a lot (making modules, sometimes forgetting
the difference between PHP arrays and JSON), so I agree on this being a DX
issue.  However, maybe this should be just documented somewhere.  "If you
have this error, change this". Maybe there are instances where Backdrop
can't read the file?

For example, you also get bland JSON errors if something is wrong with an
API.  JSON errors are rarely explained anywhere on the internet -- "illegal
choice detected -- illegal character" for string too long.  "Illegal
invocation" and so forth.

**Comment by mikemccaffrey** [comment]
> Maybe there are instances where Backdrop can't read the file?

As I mentioned in the pull request at https://github.com/backdrop/backdrop/pull/1131, there is a seperate error thrown if file_get_contents() can't open the file, so this error message should just be displayed if there is an issue decoding the JSON, so it should be good as @jenlampton wrote it.

**Comment by quicksketch** [comment]
Thanks @mikemccaffrey! Merged into 1.x and 1.2.x.
