### ISSUE TITLE
Would the Flag module be a good candidate for core inclusion?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1408]
@quicksketch since you were one of the original authors of the Flag module, what's your take on this? Is it too much for core?

I was under the impression that it was one of the most popular contrib modules (maybe because it was one of the first I started using back when I started with Drupal), but I realize its [usage stats](https://www.drupal.org/project/usage/flag) are not that great. Which could possibly be because users have found other modules to get the job done. On the other hand, there does seem do be a whole ecosystem of contrib modules either extending it or offering support for it.

Anyways, I was wondering what its use might be now with boolean fields as an alternative to it and whether we'd benefit by including it in core. This thought comes to me from time to time, especially in issues like #1190 and #1407.

I would love to hear your thoughts on this.

**Comment by jenlampton** [comment]
My gut says no, as I don't use it on 80% (or more) of sites ii build. Let's watch usage statstics for Backdrop though, and re-evaluate in a year :)
