### ISSUE TITLE
mail.inc not accepting 'from' email addresses 

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1410]
I was having trouble with emails sent from Backdrop, with them always using my server's default email address.

The problem would seem to be in core/includes/mail.inc where we have
![editing backdrop-mail inc at 1 x graham-72-backdrop 2015-12-13 07-58-48](https://cloud.githubusercontent.com/assets/10559274/11766131/86d2cd5e-a16f-11e5-93d0-ba0bedefc126.png)

Substituting $site_mail with $from solves the problem.

**Comment by Graham-72** [comment]
I have made a PR for this https://github.com/backdrop/backdrop/pull/1134

**Comment by quicksketch** [comment]
Committed in 41c8f95 (1.2.x) and 9cf4c76 (1.x) thanks @Graham-72!

**Comment by quicksketch** [comment]
Also, I'll be happy to get e-mails from my site name instead of "Apache" as had been happening on one of my sites. I thought it was a server config issue. Nice find!
