### ISSUE TITLE
[UX] Rename "Unpublished" status to "Draft"

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1411]
"Unpublished" vs "Draft"? Is that even a question?

1. "Unpublished" is a long word.
2. Draft is shorter, clearer and more easily understood. You encounter the word as early as school
    
    > Teacher: Remember to write a draft of your essay.
    > Student: Can't I submit what I have?
    > Teacher: No. I'll know if you submitted your draft because I'll be bound to find lots of silly mistakes.

When you're still working on a piece of content, it is considered a "draft". Only when you are done polishing can you hit "publish".

**Comment by bd0bd** [comment]
I think "draft" is not correct word to use for.

Published is a right word.

**Comment by sutibun** [comment]
> Published is a right word.

You mean Unpublished?

**Comment by klonos** [comment]
...yeah, but on the other hand *unpublished* communicates the fact that the piece of content is saved and hidden from public view. *draft* does not necessarily convey that meaning.

I think there was a similar issue on d.org about the very same thing.

**Comment by klonos** [comment]
...actually it was [D7UX: "Save draft" and "Publish" buttons on node forms [#282122]](https://www.drupal.org/node/282122) that has been marked duplicate of [Support revisions in different states [#218755]](https://www.drupal.org/node/218755) (implemented in D8 - API change) and there's also [Support arbitrary workflow states [#1777388]](https://www.drupal.org/node/1777388) as a follow-up (currently postponed - initial for D9, now for D8.1.x).

**Comment by wesruv** [comment]
I would prefer not to use the word 'Draft' because I'd like to see us support "unpublished revisions" of a "published entity", and those are what I'd call a Draft.

It could cause some confusion if someone marks something 'Draft' (formerly known as Unpublished) so they can work on it not knowing it makes the page unviewable by the site's visitors.

That said, I'm not tied to the words Publish/Unpublish.

**Comment by jenlampton** [comment]
I'm also not 100% sure about this change. Published/Unpublished makes sense as a pair. What's the opposite of Draft?  Public? Public/Draft? What does WordPress call these states?

**Comment by serundeputy** [comment]
Yeah.

I think the `workbench` module defaults to draft because you can have a published version of a node and a work in progress draft at the same time.  It gets crazy and different clients have widely varying ideas of what these words and workflows should be.

Even with workbench I've had a lot of hoop jumping with `node_access` and who can see what and in what state.  It gets pretty complicated quickly.

That doesn't mean Backdrop CMS should not do `something`™ , but it will require some thought and planning IMO.

**Comment by klonos** [comment]
> What does WordPress call these states

Add new page...

(option to save as "draft"):
![wp-publish_settings-add_page](https://cloud.githubusercontent.com/assets/2423362/12070968/dd375bac-b0e6-11e5-837c-94c872ddae65.png)

(option to save as "pending review"):
![wp-publish_settings-add_page-save_as_pending_review](https://cloud.githubusercontent.com/assets/2423362/12070985/63ab8280-b0e7-11e5-8bb3-213aa45efe23.png)

Edit existing page:
![wp-publish_settings-edit_page](https://cloud.githubusercontent.com/assets/2423362/12070971/efb74dc8-b0e6-11e5-99d1-312e20b49a2f.png)

**Comment by sutibun** [comment]
- **Unpublish & Publish** - makes total "logical" sense. I'm not arguing against that but maybe it's because I come from WP but to me the word "Unpublished" sounds so inelegant. What I am saying, there's a better word... and one that makes an analogy to real world publishing.
- **Draft & Publish** - this combo takes a page from real word writing where you first write **drafts** (e.g. for a book) and when you are done and happy with the final version, you **publish** it.

I think the fact it's used on WP, with a large user base of "normal" users, and it poses no problems to them at least indicates people get the analogy and aren't wondering if draft means unpublished or not.

**Comment by wesruv** [comment]
Does Wordpress have 'Published pages' that have 'unpublished revisions'? Another way to phrase that: can you have edits that aren't live yet on a published page?

I think one thing Published/Unpublished makes clearer is when a node goes live, and then you want to take it down. Unpublished makes it clear what will happen, 'returning it to draft' doesn't communicate as clearly to me.

From the CMS' I've come from (home grown, Tridion, & Drupal w/ Workbench) it's been Published/Unpublished which refers to the node's state, and then Drafts which referred to unpublished revisions of a node that may published/unpublished.

But my experience is very 'enterprisy', so take it fwiw.

**Comment by Graham-72** [comment]
> can you have edits that aren't live yet on a published page

I hope we will be able to do this which seems to me to be almost essential for even the smallest team.

**Comment by quicksketch** [comment]
> Does Wordpress have 'Published pages' that have 'unpublished revisions'? Another way to phrase that: can you have edits that aren't live yet on a published page?

I don't believe so. Content only is a draft (or multiple drafts) until it is published the first time in WordPress. You can schedule posts to be published in the future if needed out-of-box. But I don't think it supports unpublished revisions to already-published content. It is probably possible with the right plugin.

**Comment by wesruv** [comment]
Monkey's advocate: If it's not confusing for them, maybe it's fine for us?

**Comment by sutibun** [comment]
> But my experience is very 'enterprisy', so take it fwiw.

\*opens mouth\* ( ^ o ^ ); yyy...you sir have just lost A LOT of street cred among the designer group here. hehehe. jk. What designer group? :p

Enterprise software is like the last refuge for unfriendly systems.

I only brought up the fact it's used by WP because it should help to calm a bit concerns that it might not convey content isn't publicly viewable.

> It **could cause some confusion** if someone marks something 'Draft' (formerly known as Unpublished) so they can work on it not knowing it makes the page unviewable by the site's visitors.
> ... or ....
> but on the other hand unpublished communicates the fact that the piece of content is saved and hidden from public view. **draft does not necessarily convey that meaning.**

But I could take this further (though I really don't like making these types of arguments) The leader with the huge marketshare (WP) uses the word "Draft" and, correct me if I am wrong since I'm going based off a screenshot I saw earlier, but now even our older "brother" Drupal 8 uses it, so it's becoming a "trend". I take that as a sign, and JUST a sign not the end all be all, of what others are slowly convening around. Will help a bit with CMS transitions too.

But to me, those are just the toppings. My main argument that I keep revolving around is the following

- Publish + Unpublish to me is inelegant partly because it's a cheap way to do the opposite... negating the same word with "Un" (along the lines of Save/Unsave)
- The Draft + Publish workflow plays on a recognizable mental model of nearly all users. Besides professional writing, **users encounter "Draft" every day in their email inbox.** Users know draft emails are work in progress that they have yet to send to the recipient (read:published)

By taking advantage of that familiar mental model, users can better follow along and it's **clearer** where users are in the editing process. ("I am working on my draft. When I am done, I will hit publish and it'll go live") That's why I think it's better.

No worries. If there's a lot of push back on this, I'll back down.

> From the CMS' I've come from (home grown, Tridion, & Drupal w/ Workbench) it's been Published/Unpublished which **refers to the node's state, and then Drafts which referred to unpublished revisions of a node that may published/unpublished.**

Hmm... that's not bad actually but I still think the simpler model of draft/publish will be better, imo. 

No worries. If there's a lot of push back on this, I'll back down. As they say, just a thought ^\_^

**Comment by wesruv** [comment]
Great thoughts!

For the record I'm cool with either way, I see merit on both sides :smile:

**Comment by jenlampton** [comment]
The problem I see is that I'm not sure we use the word `Unpublished` very many places in the UI since the published option is a checkbox. Anyone want to take a stab at `Draft` terminology and post a screenshot of what that might look like?

**Comment by sutibun** [comment]
Not always, I am just a monkey after all, but I generally **try to imagine what is the best solution without too much consideration to what we have now**. Otherwise we're never gonna get anywhere... in terms of good design/usability. We'll stick to simple iterations that doesn't move the "needle".

For the sake of argument, let's assume the majority of us agree that the Draft/Publish workflow is a great mental model for users to grasp and orient themselves. Wouldn't it then be better to modify the whole editing process on Bd to fit it?

> The problem I see is that I'm not sure we use the word Unpublished very many places in the UI since the published option is a checkbox.

True, but where it does appear it's sub-optimal. At the top of my head: Edit node and find content.

> Anyone want to take a stab at Draft terminology and post a screenshot of what that might look like?

Sure, but it won't be what you're expecting with me retrofitting it to the current way. Why? Because the current "Edit node" and "Manage content" pages are horribly designed.

My plan with this is to improve the process of editing and managing nodes.

- ["Find content"/"Manage content" page (screenshot here)](https://github.com/backdrop/backdrop-issues/issues/1261#issuecomment-144207138). Quick summary, what if we change the "Find content" page such that it takes cues from an email inbox. Similar to draft emails, one of the most used views/displays when managing content is having a list of draft content you're currently working. Having to use the current filter mechanism is cumbersome and provides friction to real writers who need quick access to content they're currently working. (PS: I seriously hate this when writing stuff on Drupal. Bad UX)
- ["Edit Node" page](https://github.com/backdrop/backdrop-issues/issues/1299#issuecomment-150751550). Take a quick look at how the whole edit page is organized on that link. Now, that's not the screenshot since I haven't updated it but now imagine [klono's wp screenshots](https://github.com/backdrop/backdrop-issues/issues/1411#issuecomment-168306320) there. You have customized buttons to save as a draft, etc. But you also have a drop down menu: draft or published" The benefit with the drop down is contrib modules can add their own custom states like "pending review", "Needs more work", etc. Something that some sites with an editorial staff might need.

Guess I just think holistically. This issue, at least to me, has implications elsewhere.

**Comment by Graham-72** [comment]
This may be wishful thinking but what I would like to see one day is something like the following states:

- 'Draft' - not yet ready / approved for publication
- 'Published' - live on the site
= 'Revision drafted' - co-existing with the published version
= 'Revised' - live on the site
= 'Unpublished' - no longer live, but not deleted.

**Comment by sutibun** [comment]
For one moment I don't want to consider UX and all that so I am gonna throw out an idea:

How about Bd has the native ability to add/modify node states? It can be like content types which comes with the default: post + page but you can add your own.

**Comment by sutibun** [comment]
Hmm… gonna close issue. Don't want to push it further.
