### ISSUE TITLE
[UX] Views UI Rethink

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1412]
I was going to try and make Views UI responsive, but the more I looked at it, the more I hated it. I decided to try this "design experiment" to see how it struck me and I think it's worth sharing.

I decided to take ALL of the options from the current UI and redo the form using UI patterns from the rest of the admin, rather than having this separate 'click on this link to launch an overlay' based UI. 

I don't think this is 'the answer', but for reworking the Views UI, something like this is a better starting point for a design than the current UI. The current UI has a lot of issues and I don't think there'll be much benefit in trying to fix what's there.

Main things that are bothering me that I think this is starting to address:
- Arbitrary separation of some settings into the 'Advanced' (third) column
- Burying simple binary choices inside of an overlay, e.g. Hide attachments in summary, hide contextual links, use ajax, etc.
- The way Filters, Sort, and Relationships are managed where rearranging, adding, and removing have weird UI choices that are nothing like the rest of our admin.
- Small text and UI
- VERY Beginner Unfriendly

So I wanted to get other's thoughts, is this a decent start reworking, grouping and untangling the ball of yarn, or not? 
Are there some things worth keeping in this version and some things worth keeping in the new version?

@jenlampton @quicksketch @dariusgarza 

![views rethink](https://cloud.githubusercontent.com/assets/5607236/11773123/3c4569a2-a1f3-11e5-87ab-4e80b8beda86.png)

**Comment by klonos** [comment]
@wesruv I won't go into details. In general I like what you've done, especially the UI that allows reordering without having to reload an overlay. Also the toggles for things that are simply on/off. :+1: 

Do you have any PR or patch that I can test?

**Comment by klonos** [comment]
...I don't understand why "Add Relationship" and "Add Contextual Filters" are checkboxes.

**Comment by docwilmot** [comment]
Simpler then the current views, yes, but I think it would still be a formidable encounter for a non-Drupal/Backdrop user. Would a wizard-type navigation be possible with this UI? 
How would you manage previews? 
In all honesty I prefer the VTab version proposed a few weeks ago; it hides the scary stuff nicely, yet makes it obvious where the scary stuff is for those brave enough to go there. This just puts it all out there.
https://github.com/backdrop/backdrop-issues/issues/1314 and I think there was another issue with a mockup, but cant find it.

**Comment by mikemccaffrey** [comment]
Hey @wesruv, I have been working on the same thing, and created issue https://github.com/backdrop/backdrop-issues/issues/1314. We should probably close one of them, but it probably doesn't matter which.

Have you written any of this into code, or is that merely a mockup?

**Comment by wesruv** [comment]
@mikemccaffrey just mockup. Just trying to wrap my head around this thing. Sorry I missed your ticket, I looked for one and didn't find it.

**Comment by wesruv** [comment]
> ...I don't understand why "Add Relationship" and "Add Contextual Filters" are checkboxes though.

@klonos Yeah, after sleeping on it I think I need to rethink what I was going for.

@docwilmot we still have the 'wizard' that helps you set up the view, which could probably use a facelift, but after this point I'm not sure how much we can do without requiring some reading. I think we could start helping a bit by providing links to docs on some of these things (like relationships, contextual filters, etc).

![image](https://cloud.githubusercontent.com/assets/5607236/11796444/5e0cfacc-a28a-11e5-96f7-97416150c27a.png)

**Comment by wesruv** [comment]
Going to close this out in favor of @mikemccaffrey's ticket https://github.com/backdrop/backdrop-issues/issues/1314

Thanks for the initial feedback, I'll plug away some more and see what Mike's been up to :P
