### ISSUE TITLE
User URL alias not applied to admin user out of the box.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1417]
Although the URL path alias pattern for users exists (set to `accounts/[user:name]` out of the box), the admin user does not have an alias created (`user/1`).

The alias is created successfully after a bulk generate (`accounts/admin`), but should be there out of the box.

**Comment by quicksketch** [comment]
Good call @klonos. This could be fixed by simply loading and then saving the UID 1 user after the the standard profile has run. That should create the alias. Or more efficiently we may simply be able to do the following in `standard.install`:

```php
$account = user_load(1);
path_save_automatic_entity_alias($path);
```

**Comment by BWPanda** [comment]
I can't recall exactly, but I believe even saving user 1's profile once the site was up-and-running still didn't create the alias and I had to use the bulk generate feature as @klonos mentioned...

**Comment by klonos** [comment]
Yeah, I confirm that editing the user 1 account does not update the URL alias. For other user accounts, the path alias is generated and updated properly. For admin, the URL alias is only updated *after* the bulk generate has run at least once.

Steps to reproduce:

1. After installation, rename the admin account to "administrator"
2. Check URL alias -> not created - still `/user/1`
3. Create a new user, say "test user"
4. Check URL aliases -> `/user/1` and `/accounts/test-user`
5. Rename the non-admin account, say to "test"
6. Check URL aliases -> `/user/1` and `/accounts/test`
7. Bulk generate user aliases.
8. Check URL aliases -> `/accounts/administrator` and `/accounts/test`
9. Rename the admin account, say "adminstr"
10. Check URL aliases -> `/accounts/administr` and `/accounts/test`

**Comment by BWPanda** [comment]
I looked into this, and found that this seems to be because User 1 has `$user->path['auto'] == FALSE` whereas other users have that set to `TRUE`. This seems to be set during User 1's setup on install here: https://api.backdropcms.org/api/backdrop/core%21modules%21path%21path.module/function/path_load_multiple_by_entities/1 (that's where `path['auto']` is set to `FALSE`. However I can't work out why other users are different, where that's set to `TRUE` for them...

Hope this helps someone else figure this out.

**Comment by klonos** [comment]
I guess that may be because the default path patterns have not yet been specified at the stage during the Standard install profile where we create user 1 and update its role etc. ...but that's just an assumption 🤷

**Comment by klonos** [comment]
I've filed a PR that fixes things by "manually" enabling pathauto during the Standard profile installation: https://github.com/backdrop/backdrop/pull/3241

I'll spend some more time to see if there may be a more "proper" solution, that doesn't need to happen on profile installation.

**Comment by klonos** [comment]
...I've also added an update hook, to fix user1 for existing sites if a) the Path module is enabled, b) only if a path pattern has been specified for user accounts, c) `path['auto']` has not already been set to `TRUE` for user1.

**Comment by klonos** [comment]
PR rebased, ready for 👀

**Comment by BWPanda** [comment]
PR works for me. Left a code review requesting a few changes for simplification.

**Comment by BWPanda** [comment]
All good, thanks @klonos!

**Comment by quicksketch** [comment]
Nice work @klonos! Thanks to both you and @BWPanda for fixing this and the related tests! I merged https://github.com/backdrop/backdrop/pull/3241 into 1.x and 1.20.x.
