### ISSUE TITLE
The jQuery plugin ui.tooltip is missing in system_library_info()

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1420]
Front-end development is not one of my biggest skills, but I tried to fire up jQuery's tooltip and failed.

Looking into system_library_info() I found out that all ui.\* plugins are listed, except for ui.tooltip.  core/misc/ui/jquery.ui.tooltip.min.js exists however.

Is ui.tooltip overlooked in the library information hook? Or is my lack of front-end knowledge causing this error? ;)

**Comment by quicksketch** [comment]
I think you're right. We probably just overlooked it when we updated jQuery UI to the latest version. The same thing happened in jQuery Update module in https://www.drupal.org/node/1974974.

Although I don't particularly like the tooltip library very much, we should add it to system_library_info() for consistency like the rest of the jQuery UI libraries.

**Comment by MrHaroldA** [comment]
Well, I'd like to create a patch/pull request, but I'm quite busy ...

Here's the additional code needed to enable the tooltip plugin in system_library_info().

```
  $libraries['ui.tooltip'] = array(
    'title' => 'jQuery UI: Tooltip',
    'website' => 'http://jqueryui.com/tooltip/',
    'version' => $libraries['ui']['version'],
    'js' => array(
      'core/misc/ui/jquery.ui.tooltip.min.js' => array(),
    ),
    'css' => array(
      'core/misc/ui/jquery.ui.tooltip.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'ui.widget'),
      array('system', 'ui.position'),
    ),
  );
```

**Comment by quicksketch** [comment]
Thanks for filing the PR @MrHaroldA! Merged in https://github.com/backdrop/backdrop/pull/1257. This will be in 1.3.3.
