### ISSUE TITLE
New Travis-CI Google Compute Engine servers timeout on test runs

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1422]
Last two PRs timed out about 47minutes without an error.

**Comment by quicksketch** [comment]
It looks like Travis moved from BlueBox to using Google Compute Engine, which is *much*, *much* slower. :frowning: 

Blog post is here: https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

It looks like for the time being, we may be able to opt-out of using GCE and go back to using the faster BlueBox servers. I'll file a PR to modify our `.travis.yml` to opt back into BlueBox. Seems like Travis has been having some widespread issues with GCE. Eventually we'll need to move to the new platform, but that's not scheduled until this summer.

**Comment by docwilmot** [comment]
Hilariously, the PR to make Travis stop failing due to timeouts, has timed out! :laughing:

**Comment by quicksketch** [comment]
> Hilariously, the PR to make Travis stop failing due to timeouts, has timed out! :laughing:

I LOL'd but honestly, this entirely situation is not very amusing. :stuck_out_tongue:

**Comment by quicksketch** [comment]
So it may be more difficult to switch to Blue Box than I thought. The docs at

**Comment by quicksketch** [comment]
Ah ha! Help has arrived:

https://github.com/travis-ci/travis-ci/issues/5262#issuecomment-165629882

We just need to set:

```
group: legacy
```

I'll refile in a minute.

**Comment by quicksketch** [comment]
That seems to work! Yay. We'll continue running on the legacy infrastructure at Blue Box until the new Ubuntu 14.04 images include the versions of PHP that we need. Apparently that will be in the "next update" according to https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by quicksketch** [comment]
Yay, merged in https://github.com/backdrop/backdrop/issues/1139. While trying to bring down execution times I found a great issue on disabling XDebug in Travis CI at https://github.com/travis-ci/travis-ci/issues/1697. The 5.3 test ran in 15 minutes and the PHP 7 test ran in a blazing (for us) 8 minutes! Awesome. https://travis-ci.org/backdrop/backdrop/builds/97586004

This might also have to do with everyone being moved off Blue Box and so no one is using the servers any more. But in any case, we can enjoy shortened test times for the time being.

**Comment by dboulet** [comment]
Great work, @quicksketch. :+1:

**Comment by docwilmot** [comment]
This is back again. Travis site says theyve moved everyone to GCE now.

**Comment by quicksketch** [comment]
> Travis site says theyve moved everyone to GCE now.

https://blog.travis-ci.com/2016-04-07-migration-update

Yeah, the GCE boxes seem dramatically slower. For example: https://travis-ci.org/backdrop/backdrop/jobs/126525993

The container-based images are supposed to be faster. It might be time to do research into if we can get Backdrop's test suite running on containers instead of the legacy platform.

**Comment by quicksketch** [comment]
So it looks like the container architecture still doesn't allow the enabling of Apache extensions (which we need to enable the "rewrite" module for .htaccess): https://github.com/travis-ci/travis-ci/issues/3519

However someone has come up with an alternative that runs Apache on port 8080 so it doesn't need sudo: https://gist.github.com/niels-nijens/548e0c4fe80c3c79ca30

I'll try adapting this to our .travis-ci.yml and see how it goes.

**Comment by quicksketch** [comment]
Looks like the PR at https://github.com/backdrop/backdrop/pull/1344 is now working to at least execute the tests. We'll see if it's any faster than the GCE infrastructure.

**Comment by quicksketch** [comment]
Okay well the PR to use containers seems like it's sort of worked: https://travis-ci.org/backdrop/backdrop/builds/126547216

PHP 5.3 passed (yay!) but took 58 minutes to execute. :frowning: Oddly the container infrastructure doesn't time out at 40 minutes like the legacy infrastructure did. So even though it's much, much slower, at least it will finish.

PHP 7 completed in 32 minutes, but with a few new failures I've not seen before.

As an alternative to using containers, I also am trying to use the "Trusty" image instead, which still allows `sudo`. However it's not very widely supported apparently, and it's still on Google Compute Engine anyway, so I doubt it would be much faster. Once we get the issues worked out with PHP 7, we'll probably have to settle for the container infrastructure for the time being.

**Comment by docwilmot** [comment]
Great news. whats with the `You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug` warning in the test results?

**Comment by quicksketch** [comment]
> whats with the You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug warning in the test results? 

Travis turns on XDebug by default, which has some performance slowdown. However we've already disabled it per https://docs.travis-ci.com/user/languages/php#Disabling-preinstalled-PHP-extensions, we just do it after the initial set up, which is where composer throws that error. I don't think we can get before it.

This bit disables XDebug:
```
  # Disable XDebug to speed up execution.
  - phpenv config-rm xdebug.ini
```

**Comment by quicksketch** [comment]
I'm trying to adjust the concurrency level to get a better build time. When we first started using Travis, I found that a concurrency of 12 was optimal. I ran three concurrent builds last night to see their overall times (PHP 5):

[4 thread build](https://travis-ci.org/backdrop/backdrop/builds/126603554): 1 hour, 12 min
[8 thread build](https://travis-ci.org/backdrop/backdrop/builds/126603401): 1 hour, 8 min
[12 thread build](https://travis-ci.org/backdrop/backdrop/jobs/126570024): 1 hour, 11 min

So it doesn't seem to make much difference here. They're all really slow. We're getting some new (consistent) failures in PHP 7, I'm not sure why that would be. It may be an issue with the version of PHP 7.

I'm going to evaluate some other CI providers (Semaphore CI, Circle CI) to see if we could get better results elsewhere.

**Comment by docwilmot** [comment]
I must say this is extremely strange to me. Why would a business (Travis CI) voluntarily adopt a process which slows productivity by 80%? Even if it's cheaper the loss of business should be a total disincentive. Doesn't make sense.

**Comment by quicksketch** [comment]
I have no doubt that GCE is a lot more economical and scalable. Most library-type projects only take a few minutes to run their tests, so the difference between 2 and 8 minutes might not be unacceptable. They might also be trying to push people into paying tiers(?) It would be worth reaching out to them to see if they have any insight into the dramatic difference in performance.

**Comment by quicksketch** [comment]
I wrote Travis-CI an email and received a response that the new GCE infrastructure doesn't use a RAM Disk for MySQL like the legacy one did. The responder quite helpfully provided a bit of YAML that we can add to restore the RAM Disk approach on the GCE architecture:

```
  # Create a RAM disk for MySQL to improve performance.
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo stop mysql
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo start mysql
```

However, as you can see in the above PR (https://github.com/backdrop/backdrop/issues/1349), this didn't help enough. PHP 5.3 still times out at 50 minutes only about half way through.

It looks like the container approach is our only solution on Travis currently. We'll just have to bear 1+ hour build times. :frowning:

I've been looking at [Semaphore CI](https://semaphoreci.com/) as an alternative, I haven't gotten it running correctly yet. I'm open to any other suggestions, no option looks real great at the moment.

**Comment by quicksketch** [comment]
I've been trying alternatives today:

[Semaphore CI](semaphoreci.com): Doesn't include GD or PHP-FPM in any of its PHP builds. Meaning you have to recompile it (+8 min runtime). Only a single version of PHP testable at a time. Not parrallelizable.
[Snap CI](snap-ci.com): Only a single version of PHP testable at a time. CentOS based, I haven't figured out how to get Apache wired to PHP. Might require manually installing PHP-FPM. Only a single version of PHP testable at a time.
[CodeShip](codeship.com): Doesn't support Apache (or other web servers). No sudo support. Unable to run tests.
[ContinuousPHP](continuousphp.com): Unable to run shell-script based tests (only PHPUnit or similar allowed). Did provide multiple PHP version testing though.

Terrible luck on all counts. As for Travis, I found that PHP 5 finishes (eventually) on the container infrastructure but PHP 7 gives up after 45 minutes. So right now we don't have any solution that works.

**Comment by quicksketch** [comment]
Yesterday and today I tried [Shippable](shippable.com). So far the best contender. Supports multiple build versions and parallelization. Unfortunately doesn't include PHP 5.3, but does do 5.4 - 7.0. Build times seem similar to Travis though. I couldn't get Apache (or nginx) wired up to PHP-FPM, though I have gotten pretty close:

https://github.com/quicksketch/backdrop/tree/1422/shippable
https://github.com/quicksketch/backdrop/tree/1422/shippable_nginx

Shippable might be a good interim solution. I think we'd want something faster, and we'd have to pay for parallel processing unless we can work something out with them. Overall a nice platform. I'll come back to try them again. I'm going to give [Probo CI](http://probo.ci/) a go next.

**Comment by rudiedirkx** [comment]
Shippable link in previous comment is wrong. Probably missing a scheme.

Pretty dangerous, or at least annoying, those different date formats across the world =)

**Comment by quicksketch** [comment]
Thanks, fixed all my links.

**Comment by quicksketch** [comment]
[Probo CI](http://probo.ci) is quite nice. It runs PHP 5.5, multiple versions (or even selecting a PHP version) does not seem possible currently. They are a very new service, so hopefully something like that is planned. The good news is they complete our entire build in *10 minutes*, which is by far the fastest I've tested. It also beats the old Travis infrastructure, which usually could do 15 minutes at its best for PHP 5. Probo was also thankfully easy to set up, made for PHP (specifically Drupal) projects, includes Apache by default, and has spin-ups in just a few seconds. They also provide "live sandboxes" as a side-benefit. Although we already have this set up thanks to @gormartsen, it's a nice ability to have as well.

Downsides: You have to login to see test results (or sandboxes), which might be a deal breaker. I believe that users would need access to the repository on which the tests were performed. It has some weird disk writing issue that random files won't write, breaking every test run. So while promising, Probo CI won't work for us in the immediate future it seems. I've sent their support team a request for help so we'll see what we hear back from them.

They are also built/supported by the Drupal shop Zivtech, with whom we are friends. We might be able to work out some kind of arrangement for Backdrop as well (if we can get it working suitably for our purposes).

**Comment by heddn** [comment]
I didn't see Circle CI in the list. Is that intentional? I haven't heard of most of these providers, so I'm far from an expert, but it seems consistently faster than Travis, and was easier to setup.

**Comment by quicksketch** [comment]
Circle CI is on my list to test! I actually have it set up, but I haven't written the YML file for that particular provider yet. They use `phpenv` so it should be similar to Travis. Unfortunately they also don't support build matrices, but everyone is an option at this point.

I reopened the PRs for Travis to try containers and the RAM disk approaches, but now with a "splitting" option that will spin up 4 builds for each version of PHP. In Gitter, @sentaidigital brought up a question of whether there was a "total runtime" limit or not. If there's not, we might be able to split up the execution of our tests into halves (or quarters) and test different sections of the tests on different builds.

**Comment by Gormartsen** [comment]
How about to run tests on dedicated VPS?

**Comment by quicksketch** [comment]
> How about to run tests on dedicated VPS?

If we could figure out parallel processing for different PHP versions, then I would be down with it. The most common solution to this is self-hosting Jenkins. A few providers like Shippable combine their SaaS interface with self-hosted servers. The Probo CI service is also open-source, so you can get the builder code at http://github.com/proboci.

We were/are using Travis because it was easy, free, and (previously) fast. It's still a good service but we're just having performance issues with it.

**Comment by Gormartsen** [comment]
We can add it to QA.

There are many small details to think about but it's doable.



Regards,
Gor Martsen
@gormartsen

**Comment by quicksketch** [comment]
I updated the RAM Disk PR at https://github.com/backdrop/backdrop/pull/1349. The splitting option is now in place. From our test runs, we now know that Travis limits us to 5 concurrent builds. So with each PHP version split into 3 parts, it will start 6 builds (3 for PHP 5.3 and 3 for PHP 7). This will definitely get us under the execution limit, while running at the best speed we can achieve on Travis (using the RAM Disk).

Long-term, I think we'll need a faster solution still. But this will limp us along until the release of 1.4 on May 15.

**Comment by quicksketch** [comment]
Sample build: https://travis-ci.org/backdrop/backdrop/builds/127333425

It completed in about 32 minutes from when the push was sent. But, it passed entirely (yay) and fit within the time limits easily. It's the middle of the peak build time according to http://status.travis-ci.com, so this should be as slow as it would go.

**Comment by sentaidigital** [comment]
While your build was running, I pushed up an extra commit to an already open PR.  It triggered a new Travis CI run, but using the old unsplit jobs.  Do I need to create a new PR to get the new config or wait for you to frob something?

**Comment by quicksketch** [comment]
>  It triggered a new Travis CI run, but using the old unsplit jobs. Do I need to create a new PR to get the new config or wait for you to frob something?

Yeah, this isn't merged into 1.x yet. We'd need to merge it first. Then you'd have to either merge or rebase with 1.x. I'm still chatting with Travis, I'll see what they say before merging this, but we should have it going today either way.

**Comment by suziejprince** [comment]
@quicksketch thanks for checking out [Snap CI](www.snap-ci.com). I'm the product manager for Snap and wanted to let you know that we have a [beta stack available that runs Ubuntu](https://docs.snap-ci.com/the-ci-environment/stacks/). We plan to add support for PHP. We'd love you to check it out when it's available.

**Comment by quicksketch** [comment]
Thanks @suziejprince, this has been a very educational experience. We'll probably be revisiting CI providers in the future.

**Comment by quicksketch** [comment]
With tests now passing consistently, let's close this issue. We'll revisit alternatives after the release May 15 if needed.
