### ISSUE TITLE
Image field instance default image not saved properly if default_images directory doesn't exist

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1424]
When adding a default image to an image field, things seemed to work fine. However, on further examination it seems that the image has been saved without the actual filename, and instead has the path of `files/default_images`. That should probably be a directory, rather than the image itself.

**Comment by mikemccaffrey** [comment]
Looking at image_field_update_field() in image.module, the $field['settings']['default_image'] always seems to be an empty string, even when the field has a default image or you are uploading a new one.

**Comment by mikemccaffrey** [comment]
It looks like all of this stuff was last touched by @quicksketch when converting all the fields to CMI in backdrop/backdrop-issues/issues/178, in this commit:
https://github.com/backdrop/backdrop/commit/3ab41c27beaf214a2902803a9fb27ed3636275dc

**Comment by mikemccaffrey** [comment]
Weird, it looks like default image is trying to be saved in two places. 

First in:

    /**
     * Element validation function for setting a default image.
     */
    function _image_field_default_image_validate($element, &$form_state) {
      // Save the file into the temporary directory.
      $file = file_save_upload(implode('_', $element['file']['#parents']), array('file_validate_is_image' => array()));

      if ($file) {
        // Move the file to the final location, and don't manage it in the database.
        // Because field configurations should not be tied to database auto-increment
        // IDs, we only track the URI.
        $uri = file_unmanaged_move($file->uri, $element['#default_scheme'] . '://default_images');

        // Delete the file entity record.
        file_delete($file->fid);
      }
      if (isset($element['remove']) && $element['remove']['#value']) {
        $uri = '';
      }

      if (isset($uri)) {
        backdrop_array_set_nested_value($form_state['values'], $element['#target'], $uri, TRUE);
      }
      else {
        backdrop_array_unset_nested_value($form_state['values'], $element['#target']);
      }
    }

And then in:

    /**
     * Implements hook_field_update_field().
     */
    function image_field_update_field($field, $prior_field, $has_data) {
      if ($field['type'] != 'image') {
        return;
      }

      $uri_new = $field['settings']['default_image'];
      $uri_old = $prior_field['settings']['default_image'];

      // Delete the old file if any.
      if ($uri_old && $uri_new != $uri_old) {
        file_unmanaged_delete($uri_old);
      }

      // If the upload destination changed, then move the file.
      if ($uri_new && (file_uri_scheme($uri_new) != $field['settings']['uri_scheme'])) {
        $directory = $field['settings']['uri_scheme'] . '://default_images/';
        file_prepare_directory($directory, FILE_CREATE_DIRECTORY);
        file_unmanaged_move($uri_new, $directory . basename($uri_new));
      }
    }

**Comment by quicksketch** [comment]
Doh! So does this mean you can only have one default image on a site?

There was definitely some modification in that code when we converted to CMI. The code comments cover why: we can't use an auto-increment FID in a CMI-file, because the file IDs would be different between environments.

**Comment by mikemccaffrey** [comment]
Okay, some further clarification: It is the default image for the field instance that is not working properly. The one that is down under the global settings works properly.

**Comment by mikemccaffrey** [comment]
Okay, I created a pull request (backdrop/backdrop/pull/1136) to do a check in _image_field_default_image_validate to ensure that the default_images directory was created before it tries to move a file into it. That seems to have solved the problem for me.

There are two outstanding questions though:
- Why did it work to add a default image to the global settings even though the directory wasn't created?
- Why is the default file moved in _image_field_default_image_validate(), but then image_field_update_field() and image_field_delete_instance() try to do it again?

**Comment by quicksketch** [comment]
> Why is the default file moved in _image_field_default_image_validate(), but then image_field_update_field() and image_field_delete_instance() try to do it again?

I think this is because the `_image_field_default_image_validate()` is shared between both insert and update. The update hook handles deleting the *previous* default image if present. It also only moves the image if you've changed the file scheme (e.g. from "public" to "private"), which will only be known for certain after the validation has passed. Even though it looks like there's overlap here, I think they're each doing separate things.

**Comment by mikemccaffrey** [comment]
> @quicksketch: Even though it looks like there's overlap here, I think they're each doing separate things.

Makes sense. In that case I think we could just add the directory check in the validate function (backdrop/backdrop#1136) and it will solve the problem for us.

**Comment by quicksketch** [comment]
Merged in the PR into 1.x and 1.2.x. Thanks @mikemccaffrey!
