### ISSUE TITLE
Use HTML5-style link and style tags

### ISSUE THREAD

**Issue by dboulet** [backdrop/backdrop-issues#1429]
As a follow-up to https://github.com/backdrop/backdrop-issues/issues/1397, when loading CSS, we should output `<link>` and `<style>` tags which conform to HTML5 standards, and no longer need them to validate against HTML4 or XHTML.

- `<link>` tags no longer require the `type` attribute.
- Contents of `<style>` tags no longer need to be wrapped in CDATA wrappers.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1160. Great job @dboulet!
