### ISSUE TITLE
[DX] Add field_info_field_map()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1437]
In porting the addressfield module, I ran into a problem where `field_info_field_map()` wasn't defined in Backdrop. It was added in Drupal 7.22 to optimize field memory usage.
See https://www.drupal.org/node/1915646

We should also include this in backdrop to make porting modules over from Drupal easier.  (adding DX tag for that reason)

---
~PR 1 by @daggerhart: https://github.com/backdrop/backdrop/pull/1876~
~PR 2 by @daggerhart: https://github.com/backdrop/backdrop/pull/1877~
~PR 3 by @daggerhart: https://github.com/backdrop/backdrop/pull/1878~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/2008

**Comment by jenlampton** [comment]
Related: https://github.com/backdrop-contrib/addressfield/issues/1

**Comment by quicksketch** [comment]
Reviewed at https://github.com/backdrop/backdrop/pull/1878#pullrequestreview-44707275, needs a little work.

I think the simplified approach is great for the time being. I'm somewhat skeptical of the reworked code that went into Drupal 7.22, seems like a lot of complexity for a small gain. So just adding this function for API compatibility seems like a good solution (whether temporary or permanent).

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2008 into 1.x only, as this is an API change (even if it's one for compatibility). With 1.9.0 coming out today I doubt that will upset anyone needing this in future porting.
