### ISSUE TITLE
Replace /node (frontpage) with a View

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#144]
Followup to [Views in Core](#40). We should convert /node to use a View, provided by node module. Currently Views provides a "frontpage" view that we can rename and move to Node module to perform this conversion. This should also replace the front page RSS feed (which is also provided by the view).

Relevant drupal.org issue: https://drupal.org/node/1806334

**Comment by MrHaroldA** [comment]
I've added a pull request that removes /node, and enables /frontpage upon installation.

The relevant tests were also updated to reflect the new path, and the config_set() could be removed from the installation profiles, as these are set when enabling the system module.

The empty text somewhat reflect's the old /node page, but could do with a little polish. But I guess that should be a different issue.

**Comment by klonos** [comment]
> I've also added a hook_update to set the frontpage to /frontpage, if it is set to the deprecated /node page callback.

Perhaps also a redirect should be put in place (from ```/node``` to ```/frontpage```) because people might be using the old path in menus or as a reference within pieces of content.

**Comment by MrHaroldA** [comment]
What if I'd change the view page callback to /node instead of /frontpage? That would probably fix a lot of the failing tests too.

**Comment by MrHaroldA** [comment]
I suck at rebasing; deleted and created a new branch with my patch that changes the path of the front page view to /node and removes the old page callback.

**Comment by MrHaroldA** [comment]
I just read in #151 that new views should be enabled in an update hook; have to look into that too.

**Comment by klonos** [comment]
Is this issue here still relevant in recent versions of Backdrop? I think that `/node` now redirects to the front page (`/`).

**Comment by serundeputy** [comment]
`/node` redirects to `<front>` if a custom frontpage is defined on the `/admin/config/system/site-information` page; IIRC otherwise `/node` is still used; so we could still make this a view.

I think there are also performance considerations in regards to having the front page be a view.
So, still relevant but perhaps a little more difficult then the title of the issue leads on.

**Comment by klonos** [comment]
Yeah, but we now have the "Home page" layout that has the "Promoted content" view added as a block in its "Content" region and '/node' redirects to '/'.

**Comment by serundeputy** [comment]
I missed that one. ;) sounds irrelevant then, but sounds like you know more about it than I.

**Comment by klonos** [comment]
Nah, I was just searching through old issues and this one randomly came up in the results. Seeing "/node" in the issue title reminded me of #2001.

**Comment by BWPanda** [comment]
Closing based on the above discussion.
