### ISSUE TITLE
Continuing this issue: #724, hook_image_default_styles() deprecated

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop/backdrop-issues#1450]
Original Issue: https://github.com/backdrop/backdrop-issues/issues/724
and from page: https://api.backdropcms.org/node/41661
(which should be updated to show a full example of how to "include"... don't know how to do that)

How can I "can simply include an image.style.[name].json config file"? I downloaded some modules and looked all over but can find no examples. Do I do a PHP include somewhere? in the .info file? in a .module > function? Please show a full example of how to do this.

**Comment by JugglingCoder** [comment]
I think I figured this out... its working, do not know if it is the correct way.
1.) "un-installed" my module (the module I'm working on)
2.) created a file named "image.style.<NAME OF STYLE>.json" with the image style info in it and put it in the "config" folder under the module.
3.) "re-installed" the module and the file was picked up.
4.) Now I can use this style in my code like...
$image = $node-><FIELD NAME>['und']['0']['uri'];
$image = theme('image_style', array('style_name' => '<NAME OF STYLE>', 'uri' => $image, 'alt' => 'test', 'title' => 'Dog', 'attributes' => array('class' => '','style' => 'max-width:100%;')));
5.) note that "uri" was "path" in D7... that threw me off for a couple hours... oh boy...

**Comment by docwilmot** [comment]
Hi @JugglingCoder (fantastic name by the way) you are quite correct that we need examples for such things. The API docs change records are meant to be just that: records of what changed, and not 'how-to' docs. 'How-to' docs should be separate ideally, and there should be links from the API docs to show you how to do 'simple' things like this. :smile: 

But we don't yet have 'Howtos' although I'm hopeful theyll show up someday. We started at https://github.com/backdrop-ops/backdropcms.org/issues/55 but haven't had any progress. Perhaps @jenlampton can chime in with a word on when we can expect a spot on B.org to put the Howtos.

So you're right, an example of how to 'simply' create a default config should be in there somewhere.

> note that "uri" was "path" in D7

Oops again, thats mentioned somewhere in the issue queue but should be a change record.

**Comment by quicksketch** [comment]
Hi @JugglingCoder! Glad you got this figured out. Image module itself provides an example of doing this. As you figured out, you just copy the Image Style JSON file from your active configuration into your module's `config` directory.

Note that you can also prevent the image style from being deleted (and enable reverting) by specifying
```
    "storage": 4,
```

In the `image.style.[foo].json` file. The "storage" property is not well standardized across different types of configuration. There is an issue for that at #1345.

Let's conslidate this issue with https://github.com/backdrop/backdrop-issues/issues/1469, which clearly states the goal

I updated https://api.backdropcms.org/node/41661 to clarify the change record.
