### ISSUE TITLE
[UX] Rename Image style column header from "Settings" to "Storage state"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1453]
I believe the "Settings" column is actually showing the current status of an image style. The values in the column are: Overridden / Custom / Default. These are not settings. 

I would be in favor of labeling this column "Storage state" since we are likely to have a global state for all config.  See https://github.com/backdrop/backdrop-issues/issues/1345

It looks like layouts also has a column heading for storage state, current label is "STATUS".  I propose we change this too to be consistent.

**Comment by quicksketch** [comment]
I'm not 100% certain about "Storage state", but I do think making these things consistent would be a good thing. So let's go with the current PR and evaluate any possible better terminology in the future.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1144.
