### ISSUE TITLE
Views UI: the menu items under the "add display" button are too big.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1455]
Here's how it looks in D7:

![d7-views-add_display_button_and_menu](https://cloud.githubusercontent.com/assets/2423362/12009144/8433b886-acc0-11e5-9e51-8fbac2eb8426.png)

...and here's how it looks in Backdrop:

![backdrop-views-add_menu_display](https://cloud.githubusercontent.com/assets/2423362/12009146/8dab386c-acc0-11e5-9d61-35bdab804c3c.png)

**Comment by klonos** [comment]
...if this was intentional or if the result is deemed to be useful because it increases the target area (better UX for mobile and finger tapping), then perhaps we should consider increasing the size of the buttons?

...perhaps also loose the rounded corners?

**Comment by BWPanda** [comment]
Closing as I believe this has been fixed. Feel free to re-open if I'm mistaken.

**Comment by klonos** [comment]
Yup, fixed indeed:

<img width="247" alt="Screen Shot 2019-08-02 at 6 53 04 am" src="https://user-images.githubusercontent.com/2423362/62343139-438e5f00-b4f2-11e9-96d8-6e94e1faef52.png">

...although I was not able to track the issue/commit that we did it in.

**Comment by BWPanda** [comment]
#magicelves
