### ISSUE TITLE
Idea: Provide code names for major Backdrop releases

### ISSUE THREAD

**Issue by sutibun** [backdrop/backdrop-issues#1458]
This isn't a critical thing but **I thought it be fun** if each Bd release would have a unique name along with the version number similar to [how Ubuntu does it](https://en.wikipedia.org/wiki/List_of_Ubuntu_releases#Naming_convention)
- Ubuntu 5.04 (Hoary Hedgehog)
- Ubuntu 4.10 (Warty Warthog)
- Ubuntu 5.10 (Breezy Badger)

So maybe we can have:  Bd 1.3 (Polished Dragon)

no?

**Comment by klonos** [comment]
Not a bad idea. Firefox used to have [code names for their nightlies based on famous parks around the world](https://wiki.mozilla.org/Firefox/Codenames) and OSX used to have code names based on [big cats](https://en.wikipedia.org/wiki/Big_cat) and now uses mountain/location names. Any idea on what we should base our code names on?

**Comment by klonos** [comment]
How about something from these lists:

https://en.wikipedia.org/wiki/List_of_dragons_in_popular_culture
https://en.wikipedia.org/wiki/List_of_dragons_in_mythology_and_folklore
https://en.wikipedia.org/wiki/List_of_dragons_in_literature

**Comment by klonos** [comment]
Some silly-looking/playful ones (like our Drop) https://www.howtotrainyourdragon.com/explore/dragons

**Comment by klonos** [comment]
...and of course:

http://lotr.wikia.com/wiki/Smaug
http://lotr.wikia.com/wiki/Dragons
http://lotr.wikia.com/wiki/Fire_drakes
http://lotr.wikia.com/wiki/Cold-drakes

**Comment by sutibun** [comment]
A dragon seems like a reptile… so maybe

- [reptiles](https://en.m.wikipedia.org/wiki/List_of_reptiles) or 
- maybe even [lizards](https://en.m.wikipedia.org/wiki/Lizard)

**Comment by sutibun** [comment]
Maybe we can have a release called ["puff he magic dragon"](http://www.imdb.com/title/tt0262711/)

**Comment by quicksketch** [comment]
I also like the idea of code names. I like Google's approach of a single word (KitKat, Lollipop, Marshmallow) more than Ubuntu's alliterative "adjective noun" approach. I remember when I first downloaded Ubuntu it gave me an option between a "raring" and "precise" version. I didn't want a raring operating system so I downloaded the precise one, not realizing that was the older version (12.04 vs 13.04).

I do like the alphabetical approach used both by Google and Ubuntu. Apple's naming convention of random cat or California locations doesn't give any sense of sequence.

> How about something from these lists:

I'd been suggesting using famous dragons to @jenlampton as well. But I have to wonder if there are enough dragons for every letter of the alphabet. They may also be difficult to remember for the less-known ones.

**Comment by klonos** [comment]
> ...But I have to wonder if there are enough dragons for every letter of the alphabet.

If not, then let's improvise!

> ...They may also be difficult to remember for the less-known ones.

The code names will be for the more geeky ones of us ...I'm sure we'll remember :wink:

**Comment by sutibun** [comment]
> But I have to wonder if there are enough dragons for every letter of the alphabet.

We can do dinosaurs afterwards. Everybody likes dinosaurs and they kinda look like dragons.

**Comment by BWPanda** [comment]
Is this likely to happen or should we close this issue?

**Comment by docwilmot** [comment]
I like this idea. It could probably happen now that youve brought it back up. Here's a list from [this page](https://thoughtcatalog.com/january-nelson/2018/06/dragon-names/):

- [ ] Abraxas
- [ ] Akhekhu
- [ ] Amphiptere
- [ ] Ananta
- [ ] Archion
- [ ] Abeloth
- [ ] Ancestialian
- [ ] Armorwing
- [ ] Anbraxas
- [ ] Ancalagon
- [ ] Apalala
- [ ] Apep
- [ ] Apophis
- [ ] Apsu
- [ ] Brinsop
- [ ] Blaze
- [ ] Bullet
- [ ] Blacksmith
- [ ] Bonescraper
- [ ] Crimson
- [ ] Cyndaquil
- [ ] Cloud
- [ ] Chrysophylax
- [ ] Drachenstein
- [ ] Dart
- [ ] Dratini
- [ ] Drago
- [ ] Drogon
- [ ] Deadheart
- [ ] Deathclaws
- [ ] Eingana
- [ ] Everest
- [ ] Ember
- [ ] Fafnir
- [ ] Froststorm
- [ ] Flurry
- [ ] Falkor
- [ ] Galeru
- [ ] Glaurung
- [ ] Gleep
- [ ] Haku
- [ ] Helios
- [ ] Hyperion
- [ ] Hatuibwari
- [ ] Illuyankas
- [ ] Jabberwock
- [ ] Jormungandr
- [ ] Julunggul
- [ ] Kalseru
- [ ] Ketu
- [ ] Knucker
- [ ] Ladon
- [ ] Luna
- [ ] Manasa
- [ ] Mirage
- [ ] Naga
- [ ] Ness
- [ ] Neptune
- [ ] Nightwing
- [ ] Nidhogg
- [ ] Nithhogr
- [ ] Norbert
- [ ] Nyre
- [ ] Nocturne
- [ ] Narith
- [ ] Norbert
- [ ] Quetzalcoatl
- [ ] Rahu
- [ ] Riptide
- [ ] Rhaegal
- [ ] Scatha
- [ ] Scylla
- [ ] Starblaze
- [ ] Snowfall
- [ ] Sirrush
- [ ] Smaug
- [ ] Spike
- [ ] Sandstorm
- [ ] Sting
- [ ] Smerg
- [ ] Smok
- [ ] Stoorworm
- [ ] Tarasque
- [ ] Tharion
- [ ] Toothless
- [ ] Tatsu
- [ ] Tiamat
- [ ] Typhon
- [ ] Uwibami
- [ ] Vasuki
- [ ] Viserion
- [ ] Venim
- [ ] Vipor
- [ ] Vermithrax
- [ ] Whiro
- [ ] Wyvern
- [ ] Xiuhcoatl
- [ ] Yam-nahar
- [ ] Yofune-Nushi
- [ ] Yong
- [ ] Zippleback
- [ ] Zu

If everyone clicks the ones they absolutely dont want (or maybe reverse that) then we could just go alphabetically from next release.

Just an idea, to get things moving

**Comment by BWPanda** [comment]
Thanks for the list @docwilmot!

I think you should clarify whether we're ticking ones we like or don't like (I'd suggest the former), otherwise different people might tick different things...

As for me, I think names should:

- Be easy to pronounce and spell (good example: Ember, bad example: Hatuibwari)
- Not be too 'dark' (e.g. Deadheart, Deathclaws)
- Not be names already associated with things in Backdrop (e.g. Drop, Tatsu)

**Comment by klonos** [comment]
> - Not be too 'dark' (e.g. Deadheart, Deathclaws)

I would add that our dragons should be friendly, like our lap-dragon, Drop. So for example the hostile Smaug (from the Hobbit) should not be included.

There's a list of the dragons from the "How To Train Your Dragon" franchise [here](https://dragons.fandom.com/wiki/List_of_Dragon_Species_from_How_To_Train_Your_Dragon). Some of these were cute (although their names not 😅).

**Comment by indigoxela** [comment]
> I would add that our dragons should be friendly

That would drastically reduce the list to mainly Asian dragons, I guess.
Dragons are at least shady characters in most cultures.

Btw, Wikipedia has several lists of dragons: https://en.wikipedia.org/wiki/List_of_dragons_in_mythology_and_folklore (note the "See also" section).

:dragon:

**Comment by BWPanda** [comment]
Again, not much interest here for another fee years running... I'm tempted to close this issue.

Furthermore, I recently saw a rant video about how Ubuntu's release names kinda mean you need to memorise what name is for what version, and that's hard and confusing, especially for new users. So I'd be in favour of *not* giving releases codenames. Additionally, I keep hearing people quote the mantra "Naming things is hard", so perhaps let's not give ourselves more work to do in that regard...

**Comment by bugfolder** [comment]
FWIW, I'm not crazy about giving releases codenames either. (Though perhaps I'm just sensitized from Apple Mac's non-alphabetical names: "Did 'Death Valley' come before or after 'Donner Lake'?").

**Comment by indigoxela** [comment]
I'm in favor of closing this issue. Backdrop has three minor releases per year - who would ever be able to find good names for all of them? :smile:

**Comment by BWPanda** [comment]
Agreed.
