### ISSUE TITLE
[UX] Allow users to set the number of values for fields to something more than 10 (but not "unlimited") through the UI.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1459]
![backdrop-field_settings-unlimited_number_of_values_as_an_option](https://cloud.githubusercontent.com/assets/2423362/12016678/035225bc-ada2-11e5-822c-e1912ddd3b89.png)

https://drupal.stackexchange.com/questions/33178/how-do-i-set-the-fixed-amount-of-values-to-11

**Comment by klonos** [comment]
...I knew I was following some related issues in d.org, I just couldn't find them when I was filing this issue. This is basically the same as https://www.drupal.org/node/680546 filed against D7.

The initial suggestion was to add increments of 10 till 100 to the drop-down menu (so 20, 30 etc):

https://www.drupal.org/files/issues/cck%20field%20multiple%20maximums%20expanded%20to%20100_1.jpg

...I cannot even be bothered to explain how wrong that would have been.

Then an new option "other" was added to the drop-down which when selected revealed an additional field where a custom value could be defined. Here's two screenshots from various implementations of the thing:

https://www.drupal.org/files/Screen%20Shot%202012-11-24%20at%2001.14.47.png

https://www.drupal.org/files/Screen%20Shot%202012-11-24%20at%2002.40.33.png

...and here's what has finally landed in D8 3 years ago (Nov. 2012):

![d8-limit_field_values](https://cloud.githubusercontent.com/assets/2423362/12020101/6685c844-adcc-11e5-8705-c1bb1c47e5a3.png)
![d8-unlimited_field_values](https://cloud.githubusercontent.com/assets/2423362/12020102/6689167a-adcc-11e5-9bc6-0f236349c74a.png)

The issue is still pending for D7. Let's please just fix another long-standing D6/7 annoyance in Backdrop.

**Comment by quicksketch** [comment]
Thanks @klonos, great suggestion.

It looks like the D8 patch that was committed was https://www.drupal.org/node/680546#comment-7211932. It doesn't look like there's any progress on a D7 backport.

**Comment by quicksketch** [comment]
Looks like this patch is easily portable to Backdrop, as we already have the HTML5 number element. I'll have a PR ready shortly.

**Comment by klonos** [comment]
Great news! Thanx for the prompt response.

**Comment by quicksketch** [comment]
Screenshots:

![selection_013](https://cloud.githubusercontent.com/assets/100206/12057070/29554982-aef2-11e5-98ba-7b3d2f605821.png)
![selection_014](https://cloud.githubusercontent.com/assets/100206/12057074/2c0ea358-aef2-11e5-9b61-8fbc2ec4085c.png)

PR: 
https://github.com/backdrop/backdrop/pull/1150

**Comment by klonos** [comment]
Nit-picking, but wouldn't it be better if there was a "to" between the drop-down and the number field? ...so that it would read "limited **to** x".

**Comment by quicksketch** [comment]
> Nit-picking, but wouldn't it be better if there was a "to" between the drop-down and the number field? ...so that it would read "limited to x".

Unfortunately from a translation standpoint, this means we'd need to custom theme this group of elements so that we could make the string `t('!limited to !count')`. Just using `t('to')` as a single word wouldn't make any sense in translation. Not sure if it's worth it.

**Comment by klonos** [comment]
Fair enough. Looks good to me.

**Comment by quicksketch** [comment]
Cool, merged for 1.3.0.

**Comment by klonos** [comment]
Thanx!

I pledge that once I have access/permissions to do so, I'll go through all our closed issues and create a "Small but long-lasting annoyances fixed" node in backdropcms.org to showcase (with side-by-side screenshots comparing D7 and Backdrop) all these small UI fixes here and there.
