### ISSUE TITLE
[D8] Convert "Recent content" block to a View 

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#146]
Followup to #40.
Relevant drupal.org issue: https://drupal.org/node/2020393

The new views block should contain:

- [x] All the same fields as the node module recent content block
- [x] Operations links moved into a drop-button column
- [x] a setting for how many items to display (for BC funcionality)
- [x] a new setting for content types to display based on https://github.com/backdrop/backdrop-issues/issues/4020

Advocate: @stpaultim

**Comment by quicksketch** [comment]
Postponing this to a release after 1.0.0. We can still convert this at any time in a minor release.

**Comment by quicksketch** [comment]
Thanks @docwilmot for the new PR! A few issues I found:

- There's an update hook for creating the new view (great!), but we also need the update hook to loop through all Layout configurations and replace any instances of the recent content block with the new view-based version.
- The PR currently deletes the entire Node block test, it'd be preferable to keep this test intact and just update it to work with the new markup provided by the View.
- The default view configuration should be provided by node.module, not Views, so it should be moved to /core/modules/node/config.

**Comment by docwilmot** [comment]
Thanks, will do.

**Comment by docwilmot** [comment]
> There's an update hook for creating the new view (great!), but we also need the update hook to loop through all Layout configurations and replace any instances of the recent content block with the new view-based version.

I can probably do this for upgrading a Backdrop site. (I think, but pointers would be welcome). But what to do about Drupal to Backdrop upgrades?

**Comment by quicksketch** [comment]
> But what to do about Drupal to Backdrop upgrades?

Blocks are already converted into Layouts in system_update_1025(), so there's no need to worry about Drupal 7 block positions. You can assume that all blocks are already placed directly in layouts.

> I can probably do this for upgrading a Backdrop site. (I think, but pointers would be welcome).

We could use a general install function for doing this task. The general approach is that you would load each layout config file (manually, using `config_get_names_with_prefix()`), then find each block that is the recent content block and replace the module/delta values with the new module (Views) and delta (the name of the view).

**Comment by Dinornis** [comment]
@docwilmot needs some imput from @quicksketch in the PR comments.

**Comment by jenlampton** [comment]
I created a new PR based on @docwilmot 's original, but added block configuration options for number of items per page, and added back the test for the number of items.

I also added a second commit that added an exposed filter (as block configuration) for node type, to address the request in https://github.com/backdrop/backdrop-issues/issues/4020

**Comment by klonos** [comment]
@jenlampton the PR sandbox is broken (leads to install.php). Can you please kick it?

I've left a couple of comments in the PR. Also:

- We need a "more" link on the block.
- For better UX, I would prefer the list of content types to be checkboxes instead of a select list - but I understand that this is an exposed views filter now, so this may need to be a follow-up.
- Y'all know how I feel about those nasty "leave blank to...", or "0 means all" settings 😓

**Comment by stpaultim** [comment]
I was looking for other feature requests that have PR's already and might be near completion. However, I have the same question I had for https://github.com/backdrop/backdrop-issues/issues/4576, is this backward compatible. This PR makes visual changes to a block that is likely already in use on many sites. Are we able to do that?

It seems to me that we can do the following:

1) Add this view to new or existing sites, as long as we keep the old block (or the appearance of the old block on existing sites). 
2) For existing sites, add this block but keep the old block and leave site builders with a choice
3) For new sites, add this view and block and hide the old block.

**Comment by stpaultim** [comment]
I'm considering working on this task, mostly because it looks like it might be relatively simple. 

I raised the issue in DEV meeting today. The consensus from @quicksketch  and @klonos was that if the block is visually different, we might be able to fix that. 

They also pointed out that this view seems very specific to administrative pages as it includes edit and delete links. In which case, it might be sufficient to make sure that it looks good in the seven theme and we might be able to disregard any changes in basis. 

It's my intent to create a new PR based upon the previous work of @jenlampton and @docwilmot, unless either of them want to work on this. We need a new PR to get a new sandbox and then I can test to if backwards compatibility is really an issue.

**Comment by stpaultim** [comment]
I took a stab at recreating this PR since the old ones are so out-of-date.

Here is what the new block looks like placed in bottom of front page.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/5146046b-48f4-412e-8a42-1550a9a952b2)

Compare this with the old block

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/7087acf8-a721-4cb0-92cc-8df3f01d317e)

**Comment by stpaultim** [comment]
I just wanted to get this far, to see if this is worth pursuing. 

This PR would make visible changes to the block. The question is whether or not these are important changes or cause backwards compatibility problems, given that this view seems to primarily be an admin view. 

See how this view looks to an unauthenticated user as core currently ships. It's hard to see, but there is an outline of where the edit and delete links would go if they were available to this user.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/43325acb-888f-4eb6-8bf3-99bf9af911b8)

The other possible compatibility problem would be that we've removed the old block with this PR. Assuming existing sites have the old block for admin purposes, can we do an update hook that would replace the old block with this one?

If we decide that this could work, but that it must look more like the original block. It's easy to move author below the node title and some of the other changes could possibly be themed to look like the old block.

What do folks think?

Is this possible?
Is it worth pursuing?
Or should this be a 2.x issue?

**Comment by klonos** [comment]
Thank you @stpaultim for getting this going again 🙏🏼 👍🏼 

> ... this view seems to primarily be an admin view.

I'm not sure that we can safely assume that that would be the case most of the times. It seems like a common use case for sites to use that block in a sidebar on their home page. On the other hand, that block had so many limitations as a regular block, that I believe most sites will have already replaced it with a views-generated one. Given the usage stats of the Views module, I believe that we're probably OK.

> ... can we do an update hook that would replace the old block with this one?

I think that we should.

> ...but that it must look more like the original block.

Yup. We may not be able to match the visual aspect or the generated HTML 100%, but I would like us to try to match the old HTML tags, ids and classes.

**Comment by stpaultim** [comment]
I still have reservations about the fact that this change could (theoritically) effect existings sites. I less concerned about this only because the previous implementation of the block is so poor, that I don't think it's used much, if at all.

Would it be possible for us to leave this block's functionality in place for sites that have already placed it, but hide it from the list of available blocks to be placed in the future. 

This would mean that:

1) We would create a new views block 
2) Hide the old block from the list of available blocks, so that no one has the opportunity to place it fresh on any site (old or new). 
3) If case anyone had placed this block, it would continue to function and appear exactly as it did in the past.

**Comment by stpaultim** [comment]
I did a couple more things to make it look like the original view.

1) Removed Labels
2) Used Rewrite Results to put "New" tag on same line as title.
3) Removed "By" from auther. It's nice, but does not match the old block.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/fa362af8-a775-49f2-b19b-57db6dea3346)

**Comment by klonos** [comment]
> EDIT: I've implemented all suggestions by @klonos in the updated PR.

Thanks, but not quite 😅 ...some things were missed. I've added further comments with code suggestions.

I'm not sure about removing all titles/labels 🤔 ...I would rather we kept the "by" at least (even if it doesn't match the old block). I would actually like us to add some value in the new block, and add the date of creation/publishing of each piece of content. So I would prefer the second line to be "by [AUTHOR], on [DATE]". I'll let others provide feedback on whether that's a nice idea or not.

My thinking for the suggestion above is that the old block provided very little value, and chances are that most sites would have used a proper, views-generated block instead. No reason to limit the usefulness that the new block will provide to new sites built on Backdrop for the sake of keeping things the way they used to be, especially for a block that chances are is not used much.

Anyway, I like where this is going, and thanks @stpaultim for getting this rolling again. We only need an update hook, and we should be good to go I think.

**Comment by stpaultim** [comment]
Latest version:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/0e974852-ec45-4dd3-b7f2-339746789816)

**Comment by stpaultim** [comment]
So, it seems that for the update hook in node.install, I will need to convert the views.views.recent_content.json file into a php array. Or do I have that wrong?

If so, is there a good tool that will do this work?

config file = https://github.com/stpaultim/backdrop/blob/146-Replace-Recent-Content-Block/core/modules/node/config/views.view.recent_content.json

Replace PHP array in:

https://github.com/stpaultim/backdrop/blob/146-Replace-Recent-Content-Block/core/modules/node/node.install 
function node_update_1023()

How do folks do this? Or am I going in wrong direction?

**Comment by argiepiano** [comment]
@stpaultim do you still need help with that last question? It looks like this is done correctly in your PR.

**Comment by stpaultim** [comment]
@argiepiano I do still need help. 

I originally rebased a PR from Jen Lampton that already has the code for the node.install file. Since then, I've made changes to the view. I was hoping to simply cut and paste the json from the view con'us. :-(

Truthfully, I'm not entirely certain why the install file can't simply load the config file.

**Comment by argiepiano** [comment]
I see. 

Yes, if the view has changed, you have to convert the JSON into a PHP array, and replace the current array in the install file.

This is fairly simple:

1. I assume you already have that fixed view in your test site.
2. Install devel
3. Run the following code in devel:

```php
$c = config('views.view.recent_content');
var_export($c->get());
```

This will output the array version of the json code. Simply copy the whole array from the output, and replace the old array in the install file.

**Comment by stpaultim** [comment]
@argiepiano This is exactly what I was looking for. Yes, I have a copy of the view. In fact, I've already updated the PR with the config file for the view, but I haven't updated the install file yet.

I'll try this ASAP.

**Comment by stpaultim** [comment]
FYI - I'm thinking of working on this for 1.29. If I can get the JSON file converted to PHP, I think the rest is pretty straight-forward and has been well discussed in the past. If anyone deems this too complicated for a last minute feature, I'd be ok delaying it. But, the pressure of deadline helps me focus, so I use that to work on this PR either way later today.

**Comment by stpaultim** [comment]
Looking through the history of this issue. These are all items that were raised at some point or another:

- [ ] we also need the update hook to loop through all Layout configurations and replace any instances of the recent content block with the new view-based version.
- [ ] The PR currently deletes the entire Node block test, it'd be preferable to keep this test intact and just update it to work with the new markup provided by the View.
- [ ] The default view configuration should be provided by node.module, not Views, so it should be moved to /core/modules/node/config.
- [ ] but added block configuration options for number of items per page,
- [ ] added back the test for the number of items.
- [ ] I also included a second commit that added an exposed filter (as block configuration) for node type, to address the request in https://github.com/backdrop/backdrop-issues/issues/4020. I'm also adding the feature request label to address that new feature.
- [ ] We need the "more" link on the block to have its text be "Show more content" (and it should also be checked as an option in the "Allow settings override" settings in the view).
- [ ] So I would prefer the second line to be "by [AUTHOR], on [DATE]"

**Comment by stpaultim** [comment]
One thing I have not tested yet and that NEEDS testing is updating an existing site that is using the old blocks.

**Comment by stpaultim** [comment]
The update for this is not working. I'm working on updating the PR right now.

**Comment by stpaultim** [comment]
I placed a recent content block on the home page of a site using the most recent dev branch of Backdrop CMS. I set it to show the 3 most recent posts.

![image](https://github.com/user-attachments/assets/2766833e-714e-4cf7-8078-675c50cd59c2)

I then upgraded the site to use this PR and this is what I got. Note, it's not updating the block settings for number of posts.

![image](https://github.com/user-attachments/assets/a87d56bd-f8e3-466e-a33b-1855d0408601)

**Comment by stpaultim** [comment]
Other than the issue raised in the previous issue, this seems to be working for me. I would really appreciate someone else taking a look, testing, and peeking at the code to check for problems.

@argiepiano Thanks for that tip back in https://github.com/backdrop/backdrop-issues/issues/146#issuecomment-1859048294. I finally got around to using it.

**Comment by quicksketch** [comment]
I did a code review in the PR: https://github.com/backdrop/backdrop/pull/4596

A few suggestions:

- Let's add `<div class="node-title">` and `<div class="node-author">` wrappers in the view configuration to match the previous markup.
- If we're going to include the date in the author information, it should IMO match the default "submitted by" format, which is `[node:created:medium] by [node:author]`.
- In the update hook, we should add a block class of `block-node-recent` to match the previous class. We do not need this same class when placing the block on new sites (users can add it if really desired when placing).
- There are still a number of code style issues caught by phpcs.
- Tests are not yet passing.

**Comment by stpaultim** [comment]
> In the update hook, we should add a block class of block-node-recent to match the previous class. We do not need this same class when placing the block on new sites (users can add it if really desired when placing).

How do I do this?

**Comment by stpaultim** [comment]
@quicksketch 

1 and 2 are done.

Not yet sure how to do 3. 

Looking at 4 and 5 now.

**Comment by quicksketch** [comment]
@stpaultim I pushed a commit to the PR that makes two change to the update hook:

- The "node_count" setting should now be carried over to the view block "items_per_page". You can confirm this by setting the number of nodes in the block before the update.
- The "node-recent-content" class is now added to existing blocks as part of the update hook.

**Comment by jenlampton** [comment]
I've tested the upgrade path, and the transition is pretty seamless. 
* the class `block-node-recent` remains on the block
* The classes `node-title` and `node-author` are applied on the same rows
* The number of items remains as a block setting
* Same actions are present
* The table styles remain the same (seems kinda broken, but unrelated to this issue)

The only significant difference is that before, where it had only the author name in the second line, it now has the author name as part of the `submitted by` information (see below). In general, I think this change is an improvement, and I think the improvement outweighs the fact that it's a change.

Before:
<img width="600" alt="Screenshot 2024-09-02 at 8 21 37 PM" src="https://github.com/user-attachments/assets/4bfa1e76-093c-459d-bef5-d360d2bb5971">
After:
<img width="604" alt="Screenshot 2024-09-02 at 8 22 37 PM" src="https://github.com/user-attachments/assets/219e863f-f78f-4110-80ce-29ea44917898">

Trivial nit: It's a little weird that the class applied to the submitted info is still `node-author` even though it's now submitted by information. I'd almost rather we use the submitted class instead, or also?  `<footer><p class="submitted">`.

"Submitted by" format is slightly different than it is on a node (by default)
- On a node: `Mon, 09/02/2024 - 8:18pm by root` -- not linked
- This block: `Mon, 09/02/2024 - 8:18pm by [root]()` -- linked

I also think having the author linked in this instance is valuable, and outweighs the fact that it doesn't match the node submitted by format exactly.

**Comment by jenlampton** [comment]
I just noticed something, we are missing the "More" link from D7. 

It looks like the views setting is there, but that setting only adds a link if there is both a Page and a Block display of the same view. Here, `recent_content` seems to be it's own view instead of a second display of `node_admin_content`, so that More link setting won't do anything.

**Comment by jenlampton** [comment]
I have done a code review, and I think everything looks good except for 
1) the missing `@deprecated` in `drupal.inc` and 
2) removing the more link settings from the new `recent_content` view.

**Comment by stpaultim** [comment]
I made an effort tonight to get this through. BUT, there are a couple of test failuers that I just can't figure out and I have to quit.

Also, because I was focused on tests, I never got to item #2 in the notes from @jenlampton - see previous comment. 

If anyone wants to help push this across the finish line. I would appreciate it. However, this feature has waited 29 releases. It's not the end of the world if it waits one more.

**Comment by jenlampton** [comment]
I worked on this, and @quicksketch also worked on this, but I dont think it's going to get there tonight. It is *really* close though!  thank you @stpaultim

**Comment by stpaultim** [comment]
> Postponing this to a release after 1.0.0. We can still convert this at any time in a minor release.

@quicksketch was very accurate when he said this would get into a release AFTER 1.01.
https://github.com/backdrop/backdrop-issues/issues/146#issuecomment-70041987

**Comment by quicksketch** [comment]
I'm taking another look at this to see if we can get the tests passing.

**Comment by quicksketch** [comment]
Tests correctly identified several issue with our upgrade path. I corrected the issues in the update hook and tests and we're now totally passing! :tada:

It's been a while since this was updated with 1.x, so I merged in the latest. This could use another round of reviewing.

**Comment by herbdool** [comment]
I've tested and reviewed. For the most part it looks ready. My only quibble is that it should have the "more" link. It doesn't need to be in the same view as Administer Content, but it can just have a custom link entered in "Link Display" to `admin/content`:

![2024-12-02 14 03 17 backdrop-contrib lndo site 4b1c16a03a03](https://github.com/user-attachments/assets/44cb3b5c-5c29-40fc-9b56-c6ac8461c0b8)

**Comment by stpaultim** [comment]
@herbdool Did you notice this comment by @jenlampton ?
https://github.com/backdrop/backdrop-issues/issues/146#issuecomment-2325549803

**Comment by stpaultim** [comment]
@herbdool I looked closer at your suggestion, which does replicate the current behavior. But, I'm not sure it's a good behavior and it might be better to drop the "more" link. 

This is how the view currently looks, before PR:

![image](https://github.com/user-attachments/assets/65f9e277-33ab-4b54-9087-c4c00041a181)

If you click on the "more" link, it takes you here (from a potentially front end view to a admin view):

![image](https://github.com/user-attachments/assets/3c2d96d4-bc90-40cb-b8cc-0c06f4e6310d)

While I understand the following:

1) This is primarily an admin view, given the edit and delete links.
2) The "more" link would probably not be visible to someone with admin access.

Isn't it a bit weird to have a link that displays in the front end theme taking as admin directly to the admin theme and interface. Do we do that anywhere else?

**Comment by stpaultim** [comment]
Just thinking a bit more about this. If I were placing this block on a site, I might want to add a "more" link for site editors. But, I think that if it's pointing to the admin content page, I would title the link differently. Something like "Admin content" or "More recent content (admin view)". 

I expect that "more" link to take me to a view page displaying on the front end theme.

**Comment by herbdool** [comment]
@stpaultim yes, I had seen Jen's comment. The way I see it, this issue about converting a block which has a link to `admin/content` by default. So we should replicate that. At least with the new block, it can expose the "more" link setting to the block so someone could disable it when editing the layout.

I'm doubtful that someone would have the old block visible on a front end theme. Particularly since the old block *always* displayed the link to the admin page.

**Comment by quicksketch** [comment]
> Isn't it a bit weird to have a link that displays in the front end theme taking an admin directly to the admin theme and interface. Do we do that anywhere else?

If this block were placed on `admin/dashboard` it would stay within the admin interface. That may have been this block's original purpose(?), using the D7 Dashboard module. We don't really know if this view would be places on the front end or back end. 

So I'm fine with adding the More link.

**Comment by stpaultim** [comment]
@herbdool and @quicksketch How does this look? (See about page in dev sandbox - I did nothing but place the block). 

![image](https://github.com/user-attachments/assets/15e4fe60-7601-4fb9-aa25-6ccd3060c477)

I did not test the upgrade path. Here is link to commit to see changes I made:
https://github.com/backdrop/backdrop/pull/4596/commits/b58ef3d1b0abc69a0f0d8fb72ce268885959c2ce

**Comment by quicksketch** [comment]
Showing the more link isn't a security problem, but it doesn't match normal Backdrop behavior. Perhaps we add the More link for consistency with the previous block but also file a follow-up to make the more link check access.

**Comment by herbdool** [comment]
@quicksketch sounds good. The follow-up would need to change Views I'm assuming.

**Comment by stpaultim** [comment]
@quicksketch and @herbdool - Just confirming that we will keep the "more" link as it is with a follow-up issue for views to check access for this link. 

PR has been updated and is ready for any additional testing, if necessary, and/or final code review.

**Comment by stpaultim** [comment]
Activity in this "Port Request" for "Read More Control" module. It doesn't look like this module does an access check, but it seems vaguely releated to the follow up issue for this PR.

https://github.com/backdrop-ops/contrib/issues/579

**Comment by herbdool** [comment]
@stpaultim that's correct: keep the "more" link and a follow-up to check access.

We should also expose the "more" link setting to the block in the "Allow settings override" link in the Block settings of the View.

![2024-12-03 23 46 07 pr4596-xzepgkxl3cmekggotvapkdahpg5om60q tugboatqa com bf232bb36cf7](https://github.com/user-attachments/assets/f400c0e0-937f-46ab-8502-30c4a99986ad)

**Comment by quicksketch** [comment]
Thanks @stpaultim for updating the PR! A note that links should be `admin/content` and not `/admin/content`. Backdrop will expand the URL to include the base path if there is no leading slash. I know it's gotten confusing because D8+ all now require the leading slash for paths.

Can you also add the more link functionality to the update hook?

**Comment by stpaultim** [comment]
@quicksketch I think I did add it to the install hook.
https://github.com/stpaultim/backdrop/commit/b58ef3d1b0abc69a0f0d8fb72ce268885959c2ce

I just haven't tested it yet. I'll try to get to it soon.

**Comment by quicksketch** [comment]
I tested and confirmed the update hook works.

- Before checking-out PR: Added "Recent Content" block to the `home` and `admin/dashboard` layouts (added twice to the dashboard).
- Set different number of items in each block.
- Ran update.php
- Confirmed all three instances were replaced, including the "More" link, and maintained the number of items value.

I got a little tripped up because the "More" link disappeared on my local because I only had 5 pieces of content. To match the previous behavior, we should enable the "use_more_always" setting by unchecking this box:

![image](https://github.com/user-attachments/assets/e7cb8bc4-64e4-4519-930c-1c9cb8a42ae4)

I pushed a commit to the PR to make that change.

This looks good and ready to me.

**Comment by herbdool** [comment]
@stpaultim @quicksketch and also I request we expose the "more link" setting to the block, as I mentioned above: 

> We should also expose the "more" link setting to the block in the "Allow settings override" link in the Block settings of the View.

**Comment by quicksketch** [comment]
Thanks @herbdool, sorry I overlooked that comment. I updated the PR with that change to allow the more link to be toggled in the block settings.

**Comment by stpaultim** [comment]
WFM!

I just tested the sandbox again. Tested the new option for "more" link and it works fine. Block works on about page and on dashboard.

**Comment by herbdool** [comment]
I think it's ready to be merged.

**Comment by argiepiano** [comment]
When this block is added on front pages that can be seen by anonymous, there is a weird-looking empty column:
<img width="358" alt="Screen Shot 2024-12-06 at 6 57 26 AM" src="https://github.com/user-attachments/assets/366da293-34df-4c7f-90cd-0841ceae7a73">


This is super easy to solve by going to Format > Settings, and selecting "Hide empty column". It seems like a logical and easy step that should be provided within this PR

<img width="1189" alt="Screen Shot 2024-12-06 at 6 59 13 AM" src="https://github.com/user-attachments/assets/9c28f858-0953-4b9e-a625-10fc888462b8">

Also, the dropbuttons in Basis create issues with width for narrow columns... but that's something that needs to be fixed on a different issue for BAsis specifically.

**Comment by quicksketch** [comment]
Thanks @argiepiano, great suggestion. We had that in place when they were separate Edit and Delete links but the setting didn't get updated when we switched to the drop button. The PR has been updated.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4596 into 1.x for 1.30.0! Finally! An ancient TODO item crossed off the list.

Thank you @docwilmot for the original PR and work, @stpaultim and @jenlampton for updated and iterated versions. And thank you @klonos, @herbdool, @argiepiano, and @Dinornis for the reviews!

**Comment by herbdool** [comment]
Woohoo! 🎈

**Comment by olafgrabienski** [comment]
Testing the 1.30 preview, I read this thread again. Is there already a follow-up to add an access check for the more link? See https://github.com/backdrop/backdrop-issues/issues/146#issuecomment-2515350186.

**Comment by herbdool** [comment]
Thanks for remembering. I don't think there is. Can you create one Olaf?

**Comment by stpaultim** [comment]
Issue created.
