### ISSUE TITLE
 #attached not working for textarea in hook_field_widget_form_alter().

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1464]
A library attached with `$element['#attached']['library'][]` does not show.
This is caused by the filter.module, `function filter_process_format($element)`, which erases any previous content (line 1135) : 
`$element['#attached'] = filter_get_attached($formats);` 
This is fixed by replacing this line by : 
`if (isset($element['#attached']))`
`$element['#attached'] = array_merge_recursive($element['#attached'], filter_get_attached($formats));`
`else`
`$element['#attached'] = filter_get_attached($formats);`

---

This issue was originally reported over in https://github.com/backdrop-ops/backdropcms.org/issues/148 by gifad.

**Comment by gifad** [comment]
I tried and submit a pull request ; https://github.com/backdrop/backdrop/pull/1157
but (this is my first ever pull request) something went wrong...

**Comment by quicksketch** [comment]
Looks great @gifad! Merged into 1.x and 1.2.x.
