### ISSUE TITLE
Convert the module and theme listing page to a view (a.k.a. views_system)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1466]
Big note: I'm not sure how relevant this will be with Project Browser in core, but it would be interesting to convert the output of the PB listing to a view. ...especially if we have views facets in core someday!

If this is accepted, it will be part of the #151 meta. I recall bringing this up somewhere sometime in the past, but I cannot remember it it was in the issue queue of Backdrop or Drupal.

Anyways, the idea here is to convert the module and theme listing pages to a view for the same reasons that we are aiming to convert other core listings to views: in order to empower admins with more flexibility when it comes to customizing these pages to suit their needs.

I vaguely remember someone shooting down this idea because of the technical limitations of implementing something like this (I think something along the lines of "modules and themes are not entities" or something). So, I was glad today to come across [Views System](https://www.drupal.org/project/views_system):

> The Views System module extends the Views module and allows to create customized lists (pages, blocks) of modules, themes, and theme engines that are or have been installed in Drupal's file system.

How cool is that!!

**Comment by quicksketch** [comment]
> Anyways, the idea here is to convert the module and theme listing pages to a view for the same reasons that we are aiming to convert other core listings to views: in order to empower admins with more flexibility when it comes to customizing these pages to suit their needs.

I'm not sure about this. Unlike other listings, modules and themes are fairly contained. There aren't any other tables for the `system` table to join on, as it doesn't share any keys with any other tables. What other fields could you add to these pages?

This suggestion also lends itself to extension, that if the themes and modules page were views, couldn't image styles, layouts, and even views lists themselves be views? They *could* with enough effort and abstraction, but I don't think there's a worthwhile trade-off there. The need to customize these pages is much lower than the content and user administrations pages, which vary based on the sort of site that you are building. The tasks of enabling modules and themes is the same regardless of the type of site you build.

**Comment by jenlampton** [comment]
Yeah, I don't think I see a compelling reason to make these views, especially since it would break things like our handy module page search box.  Let's get to the heart of the issue here and see if we can come up with a better solution for an actual problem. What is the use-case for having a view? What is the problem that might solve?

**Comment by BWPanda** [comment]
Closing this due to comments above and lack of interest to explore further.

**Comment by klonos** [comment]
Agreed 👍 ...adding the contrib tag for anyone interested in this in the future. Module to be ported would be https://www.drupal.org/project/views_system

**Comment by klonos** [comment]
For people reaching this issue in search of what can be done with Views when it comes to listing modules/themes etc. and with requests to implement the functionality of https://www.drupal.org/project/views_system into core, it seems that Views in Backdrop already allows this (see #5791), and it seems that we'll improve it to be able to do more (see #5820).
