### ISSUE TITLE
Update views api docs, remove any mention of adding files[] to .info files.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1467]
It looks like we inherited some documentation from Drupal 7 that is no longer correct for Backdrop CMS.  These old references to using `files[]` in info files need to be replaced with instructions on how to use `hook_autoload_info()`.

**Comment by quicksketch** [comment]
This might be a duplicate of https://github.com/backdrop/backdrop-issues/issues/712. Where are wee referencing `files[]` still? Could you provide a link?

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1146.
