### ISSUE TITLE
Remove hook_image_default_styles(). It won't work.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1469]
Looks like we left `hook_image_default_styles()` in the code, but it won't work anymore. We should remove it, and add a change record that states default image styles can be added by dropping the config file into your module's `/config/` directory instead.

**Comment by docwilmot** [comment]
Already a CR: https://github.com/backdrop/backdrop-issues/issues/724 but it could use some clarification. And the invocation is also gone.

Just remains to delete the entry from `image.api.php`

**Comment by quicksketch** [comment]
> Already a CR: #724 and https://api.backdropcms.org/node/41661 but it could use some clarification.

I updated the change record to clarify it a bit per https://github.com/backdrop/backdrop-issues/issues/1450

**Comment by jenlampton** [comment]
Fantastic :)

**Comment by laryn** [comment]
This hook is still referenced when searched for and no mention of the new method shows up:

 - https://docs.backdropcms.org/search/node/hook_image_default_styles
 - 
![hook_image_default_styles](https://user-images.githubusercontent.com/871421/162964385-e9927a51-86e8-4fee-aa7a-88f62d788466.png)

**Comment by argiepiano** [comment]
It seems like that documentation entry comes from the `examples` project, which is a contrib module but indexed as if it were core. Apparently that hook implementation was never removed by the maintainers of the `examples` module.

**Comment by laryn** [comment]
Thanks! I wonder if there's a way to have change records for a function show up in the search on the API site -- that seems like it would be helpful, but at least in this case I don't see the CR when I search for the function:

 - https://docs.backdropcms.org/search/node/hook_image_default_styles
 - https://docs.backdropcms.org/node/41661

**Comment by jenlampton** [comment]
> I wonder if there's a way to have change records for a function show up in the search on the API site 

that is how it works :) 

It looks like there isn't a change record:
https://docs.backdropcms.org/change-records?field_impacts_value=All&keys=hook_image_default_styles

Adding label.

**Comment by jenlampton** [comment]
Oh, duh. You actually included a link to the change record. Hm...

I've added the function name into the CR node title, and ran cron to update the index. That seems to have helped:
* https://docs.backdropcms.org/change-records?field_impacts_value=All&keys=hook_image_default_styles
* https://docs.backdropcms.org/search/node/hook_image_default_styles

**Comment by BWPanda** [comment]
Going to close this in favour of https://github.com/backdrop-contrib/examples/issues/24. If there are issues with things not showing up in the Docs search results, that's a separate issue for a separate queue.
