### ISSUE TITLE
[DX] put variable replacement types back in docblock for t().

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1471]
I miss being able to look up the t() function and find out what types of substitutions are available without having to also read about `format_string().`  Let's update the docblock and put them back.

**Comment by quicksketch** [comment]
Most Drupal/Backdrop devs may know about t() but only a small fraction know about format_string(). Save them the looking up sounds good to me.

Merged your PR into 1.x, so this will only show up after the release of 1.3.0.
