### ISSUE TITLE
Happy 2016 everybody!!!

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1474]
We are all trying our best to improve a thing that's freely available to those who need it and that means that we are doing our part to improve this world and make it a better place. One small thing at a time.

Thank you all guys. All the best to you and your loved ones.

**Comment by Graham-72** [comment]
Thanks @klonos , and to you and all the team.

**Comment by sutibun** [comment]
> We are all trying our best to improve a thing that's freely available to those who need it…

But I'm just here because I was promised a bonanza of bananas…

\*places arm around graham and klonos\* these guys are so hardcore they are still here even on the first day of 2016

*･゜ﾟ･*:.｡..｡.:*･'(*ﾟ▽ﾟ*)'･*:.｡. .｡.:*･゜ﾟ･*

**Comment by serundeputy** [comment]
:bow:

**Comment by sutibun** [comment]
Look everybody… \*points at seundeputy\*  we have a lurker… they're the worst kind… ^\_^) because you never know their motivation

**Comment by sutibun** [comment]
Let see what he does

 \*pokes with a stick\*

**Comment by serundeputy** [comment]
:stuck_out_tongue_winking_eye:

**Comment by sutibun** [comment]
Th…there's something wrong with his face. \*looks closer\* Oh no, he just forgot to shave.

Monkey must respond in kind (・ω・)ノ 

Hola. 你谁什么？

\*no movement\*

Oh wait, he won't understand that. Monkey so silly. Let's try again:

    Human $lurker = serundeputy;
    if($lurker.comesin("peace"))
    {
        $lurker.give(banana,$monkey);
    }
    else
        $lurker.hug($klonos) //he's weird too

**Comment by klonos** [comment]
:laughing: :laughing: :laughing: :laughing:

**Comment by sutibun** [comment]
hehehe didn't even realize he had a beard... just in case, didn't mean it that way

**Comment by quicksketch** [comment]
Yay! Here's looking forward to a great 2016. This year was epic for Backdrop and the future looks even more exciting. :smile:
