### ISSUE TITLE
[DX] provide a wrapper function config_clear()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1479]
In order to inset a variable in a config file, you need to load the file, clear the variable and then save the file. This can be tedious if you are simply trying to delete a single value. Let's add a handy wrapper function config_clear() that will do all that messiness for you.

before:

``` php
    $system_config = config('system.core');
    $system_config->clear('user_admin_role');
    $system_config->save();
```

after:

``` php
config_clear('system.core', 'user_admin_role');
```

**Comment by quicksketch** [comment]
Sounds good to me. This helps with discover-ability. Though like other procedural wrappers, this would be less efficient if you needed multiple clears/sets at the same time before doing a single save().

**Comment by mikemccaffrey** [comment]
Ever feel like we are endlessly swinging back and forth between procedural and object-oriented methodologies?

**Comment by klonos** [comment]
>...this would be less efficient if you needed multiple clears/sets at the same time before doing a single save().

...although not a coder, couldn't the second parameter passed to the function be an array of variables to be cleared? That would call a single ```save()```. Right?

Of course that implies that all the variables to be cleared reside in the same config file passed as the first parameter. Would there be another, smart way to be passing pairs of config files and parameters? I realize it gets a bit tricky because you'd need to define one config file to many variables. Don;t really know - just brainstorming.

**Comment by klonos** [comment]
...would something like this work:

```config_clear(('config.file.1', 'var_1', 'var_2', ...), ('config.file.2', 'var_a', 'var_b', ...), ...);```

**Comment by mikemccaffrey** [comment]
> ...although not a coder, couldn't the second parameter passed to the function be an array of variables to be cleared? 

I'm thinking that bundling config clears only makes sense if they are all part of the same file, so this should be enough abstraction:

```
config_clear('config.file', array('var_1', 'var_2', 'var_3', ...));
```

**Comment by Graham-72** [comment]
For proposed config_clear() see latest PR at https://github.com/backdrop/backdrop-issues/issues/2355

**Comment by jenlampton** [comment]
It looks like that issue is a dupe of this one, but since there's a PR over there, I'm closing this one instead.
