### ISSUE TITLE
API docs for update_variable_del() refer to Backdrop as 'Drupal 7'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1481]
The docblock above `update_variable_del()` currently says:

```
Use this during the Drupal 7 upgrade path instead of variable_del().
```

Let's change it to

```
Use this during the upgrade path instead of variable_del().
```

**Comment by klonos** [comment]
I took a look at the PR, but mentioning D7 in that context does make sense. Not sure.

**Comment by jenlampton** [comment]
Hm, I see, you read "Drupal 7 upgrade path" as "Upgrade FROM Drupal 7."  I read it as "Upgrade TO Drupal 7".

**Comment by Graham-72** [comment]
To avoid any ambiguity perhaps the wording should be 'Use this during the upgrade path from Drupal 7 instead of variable_del()?

**Comment by quicksketch** [comment]
I'm fine with the current PR. The more removals of the word "Drupal" the better, as it helps in regular find/replace routines if we have fewer of them. Merged in https://github.com/backdrop/backdrop/pull/1681 into 1.x and 1.5.x.
