### ISSUE TITLE
yet another case against missing page.tpl.php

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1483]
In Drupal 7, I use to show some pages in an iframe in a lightbox, with essentially the `#main-content`, no header, no sidebars,...
I do this by "suggesting" a custom page.tpl.php, which I can't achieve with Backdrop.
As a workaround, I use the following hack : 

```
function addon_preprocess_layout(&$variables) {
    if ((isset($_GET['template']) && $_GET['template'] == 'ajax')) {
        unset($variables['content']['header']); 
        unset($variables['content']['top']);
        unset($variables['content']['sidebar']);
        unset($variables['content']['footer']);
        admin_bar_suppress(TRUE);
    }
}
```

Is there a clean way to achieve this in Backdrop ?
I thought of dynamically specifying a specific layout, but could not find an API/hook to do that (if it's the right method...)

**Comment by mikemccaffrey** [comment]
Are those pages always displayed without headers and sidebars? If so, can you just specify a simplified layout for them through the Layout UI?

**Comment by gifad** [comment]
No, these are potentially any page...
Typical use case : 
clicking a thumbnail usually displays a lightbox with large picture of the object
in this case, it displays an article node, with description etc...
lightbox is used for consistency...
(it could be a ctools modal dialog...)

my question is "can you just specify a simplified layout" programmatically ?

FWIW, the drupal code is : 
`function addon_theme() {`
`  $theme = variable_get('theme_default');`
`  return array('page__ajax' => array(`
`    'render element' => 'page',`
`    'template' => "page-$theme--ajax"));`
`}`
`function addon_preprocess_page(&$vars) {`
`  if ((isset($_GET['template']) && $_GET['template'] == 'ajax')) {`
`      $vars['theme_hook_suggestions'][] = 'page__ajax';`
`  }`
`}`

**Comment by quicksketch** [comment]
> my question is "can you just specify a simplified layout" programmatically ?.

Backdrop's layout module will only fire if the requested page is made with an `Accept: text/html` header (or no Accept header at all). If you want to get just the body back with no sidebars (or any Layout manipulation at all) you can make an AJAX request with a different Accept header.

e.g.
```
$.ajax({
 url: '/node/1',
 accepts: { html: 'text/x-lightbox' },
 'dataType': 'html',
  'success': function(response) {
    console.log(response);
  }
});
```

The Accept type `'text/x-lightbox'` is just made up here. It can be anything except `text/html`, or one of Backdrop's special Accept headers, like `application/vnd.backdrop-ajax`.

Alternatively, you could do a hack in PHP that overrode the Accept header based on on a query string, as you have in your example. You'd need to do it in a hook_init() or other early page load:

```php
function my_module_init() {
  if ((isset($_GET['template']) && $_GET['template'] == 'ajax')) {
    $_SERVER['HTTP_ACCEPT'] = 'text/x-lightbox';
  }
}
```

But this second approach is a hack. If it's possible to modify your JS code to just set a different accept header, then that's the better approach to use.

To see how a layout is selected for a page, see the code in [layout_route_handler()](https://api.backdropcms.org/api/backdrop/core!modules!layout!layout.module/function/layout_route_handler/1). Essentially, if `backdrop_is_html()` fails to be TRUE, Layout module doesn't do anything at all and just the contents of the menu handler are returned, which it sounds like is what you're trying to accomplish.

**Comment by gifad** [comment]
Hmm, the `$.ajax()` sounds easy, but my popup windows open thru normal links, plus : 
`$link['attributes']['target'] = '_blank';`
`$link['attributes']['class'][] = 'fancyframe';`
`$link['attributes']['data-fancybox-type'] = "iframe";`
`$link['query'] = array('template' => 'ajax');`
and that's all, fancybox does the rest...

Now, specifying just `$link['attributes']['data-fancybox-type'] = "ajax";` works (with just some overflow issues), I'll explore this route...

FWIW, drupal fancybox module runs perfectly in backdrop with just `backdrop = 1.x` and `type = module` appended to fancybox.info ;-)

**Comment by gifad** [comment]
Well, the ajax route is not an option : In my test case, I am on a `node/%/edit` page, with some very custom field widgets, one of which has a button that opens another similar  `node/%/edit` page in the popup; As we are no more in a iframe, the various behaviors.attach/detach conflict, and the browser becomes quickly frozen... (CKEditor toolbar has `cke-panel` global iframes, etc...)

I'll stand with the OP `hook_preprocess_layout()` for now (which handles recursivity as long as there is screen space available), until an official `?layout=my_layout` query option lands...

**Comment by gifad** [comment]
FYI, the test case : 
![capture d ecran 2016-01-06 a 03 12 31](https://cloud.githubusercontent.com/assets/15943462/12133321/8ce471d0-b424-11e5-82ee-7e9e4c6c41b4.jpg)
yes, this is backdrop...

**Comment by gifad** [comment]
FWIW, to prevent php notice (visible only thru the watchdog report) with “some” themes (including bartik), replace in the OP snippet
`  unset($variables['content']['header']);`
by
`  $variables['content']['header'] = '';`

**Comment by klonos** [comment]
@gifad tip: you can wrap your multi-line code in ````````` (before the first line and after the last) instead of adding ```````'s in front and at the end on each and every line. :wink

**Comment by gifad** [comment]
I fortuitously came across `"menu_route_handler":` setting in `system.core.json` : this is the key to programmatically handle runtime selection of layout…

**Comment by quicksketch** [comment]
Closing this question, we can continue in [#1728].
