### ISSUE TITLE
Performance: Optimize calls to hook_block_info() on Layout configuration pages

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1484]
While working in system_block_info(), I found that the hook is called a dozen times when editing a Layout in the drag and drop blocks interface.

It looks like this is because the Block and BlockLegacy classes are directly calling `module_invoke($module, 'block_info')`. We could optimize this by using the static cache of block info stored in `layout_get_block_info()` instead.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.2.x.

**Comment by mikemccaffrey** [comment]
Good catch!
