### ISSUE TITLE
[UX] Remove URL path settings from Manage Fields tab

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1488]
When you go to the Manage Fields tab for a content type or other entity, you can rearrange the order of how items appear on the edit form, including required system fields such as Title. However, URL path settings also appear there, even though changing its weight has no affect on how things appear on the edit form, since it is actually displayed in one of the vertical tabs on the bottom of the form.

![screenshot-2016-01-06-14 47 00](https://cloud.githubusercontent.com/assets/1134098/12157240/400644a4-b485-11e5-80d8-8de427b07f56.png)

Can we please remove this pointless item? Perhaps, we can do it while looking at allowing title and body label changes on that same form in #1443?

**Comment by jenlampton** [comment]
I agree. None of the other things in vertical tabs have an implementation of `hook_fields_extra_fields` so it's weird that path does. Let's kill it!

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/1208. Merged into 1.x for 1.3.0.
