### ISSUE TITLE
Make a generic resize throttle using requestAnimationFrame/fallback

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1489]
In the [pull request to make tabs responsive in Seven](https://github.com/backdrop/backdrop/pull/1142#discussion_r48916659), there was a great suggestion of using the newer `requestAnimationFrame` function instead of using `setTimeout()` to throttle window.resize events. In my testing, the newer approach seemed much smoother. Let's evaluate making a custom resize event that uses `requestAnimationFrame()` if available and a `setTimeout()` approach as a fallback if not available.

Our current approach (see admin_bar.js and seven/script.js):
```
    // Resource friendly resize event
    var resizeTimeout;
    $(window).on('resize', function () {
      clearTimeout(resizeTimeout);
      resizeTimeout = setTimeout(handleResize, 50);
    });
```

Some good alternatives over at MDN: https://developer.mozilla.org/en-US/docs/Web/Events/resize#requestAnimationFrame_customEvent

**Comment by quicksketch** [comment]
One idea I like from the MDN examples is setting up a custom event that could be used instead of `$(window).on('resize');` We could set up our own event that is throttled and provides the fallback approach and then use it by binding to that event instead, such as `$(window).on('backdropResize')`. Thoughts?

cc: @wesruv

**Comment by wesruv** [comment]
Yeah, I noticed the tabs felt a lot more sluggish when we switched them. It'd be great to get this working!

**Comment by wesruv** [comment]
https://gist.github.com/paulirish/1579671

**Comment by quicksketch** [comment]
I fret about polyfills that directly set global JavaScript functions. It's never really quite the same thing. Sometimes there is more or less of the spec implemented, or a completely reasonable assumption about the browser's capabilities turns out to be incorrect because of a shimmed in function.

**Comment by wesruv** [comment]
Looking at adding this with the responsive dropdown menus to core (#1457), was thinking I'd just add what the mozilla docs have, not sure i can do any better.

Right now here's what I've got:
https://github.com/wesruv/backdrop/blob/41235a897fd2384939da79c1615d107025de5d90/core/misc/backdrop.js#L525-L581

**Comment by quicksketch** [comment]
That looks great to me! (Minor codestyle: add periods to comments.)

Could you file a PR and put this resize method to use? We have lots of places that need it:

- Responsive tabs (in Seven).
- Responsive vertical tabs.
- The admin bar.
- Dialog resizing/centering.

**Comment by wesruv** [comment]
@quicksketch https://github.com/backdrop/backdrop/pull/1435

I converted some of the window resize events in core, but some of them look bananas to me, so I left them.

**Comment by quicksketch** [comment]
This looks great @wesruv! Sorry I missed reviewing this because this issue wasn't tagged. You mentioned in the PR that it is holding up other work, is it going to be okay if this is only in 1.5.x and not in the current 1.4.x version? This is kind of a mix of a feature request because it adds a new API, but also a bug fix in that it drastically helps front-end performance when resizing.

I tested all of the situations covered in Firefox:

- Column hiding (permissions page)
- Seven tabs (manage fields page)
- Table header (permissions page)
- Admin bar

But I still need to check in a non-request-frame-friendly browser to check the fallback behavior.

**Comment by wesruv** [comment]
@quicksketch it'd cause a little bit of dupe work (which I was trying to avoid), but not the end of the world. I'll switch the things I'm working on to use good ole' timeout for now and we can update them later :smile:

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1435 manually, commit is https://github.com/backdrop/backdrop/commit/78d0f3815ba4e8a93459d4055f2bf8bc34a7a977. This is now in 1.x for 1.5.0 but *not* in 1.4.x. So any work in the contrib version of Basis either would only work with 1.x of Backdrop or needs a version/capability check for the time being.
