### ISSUE TITLE
Replace admin/people with a View

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#149]
This admin listing will be dependent upon #142.

Relevant drupal.org issue: https://drupal.org/node/1851086

**Comment by quicksketch** [comment]
PR is passing now! It took me a while to rework the test for the bulk operations, since VBO uses the row number and not the UID for its checkbox element names.

**Comment by klonos** [comment]
One more admin listing converted. Yeahee!!!
