### ISSUE TITLE
Layouts are not used in Internet Explorer 8

### ISSUE THREAD

**Issue by dboulet** [backdrop/backdrop-issues#1491]
I was testing my Backdrop site in Internet Explorer 8 today, and ran into what I initially thought was a very strange problem: the layouts that I had configured for the site were being completely ignored in this browser. By this, I mean that only the main content of the page was being displayed and the site header and footer were completely missing in the source code.

I figured that there must be something different in the request made to the server by IE8, and narrowed the problem down to Backdrop not properly recognizing the `Accept:` header sent by the browser.

The Layout module contains code which skips the loading of the layout for the current page if it thinks that the current page is not going to be returned as HTML. Unfortunately, the `Accept:` header sent by IE8 is not sufficient to trigger a return value of `TRUE` in `backdrop_is_html()`.

For reference, here is a typical `Accept:` header sent by IE8:

`image/jpeg, application/x-ms-application, image/gif, application/xaml+xml, image/pjpeg, application/x-ms-xbap, application/x-shockwave-flash, application/msword, */*`

I do understand that IE8 is, at this point, an ancient browser — and it’s likely that Backdrop will soon drop support for it completely — but I feel that this bug proves that the checking in  `backdrop_is_html()` is probably too strict, and should be relaxed. What if a future browser decides to use a different `Accept:` header which also produces this bug? The best way to be future-friendly is to be backwards-compatible. :wink:

**Comment by dboulet** [comment]
It appears that this issue affects more than just layouts — it will pop up basically anywhere that `backdrop_is_html()` is used. For example, the admin bar is not ever displayed in IE8.

@quicksketch, since you were the author of `backdrop_is_html()`, I’d appreciate your feedback here. I think that it would be safer to have the function search the `Accept:` header for signs that the request should NOT be returned as HTML, instead of searching for signs that it should be. Maybe the function could be more like this:

```php
function backdrop_is_html() {
  return (!backdrop_is_ajax() && empty($_SERVER['X_REQUESTED_WITH'])) || strpos($_SERVER['HTTP_ACCEPT'], 'text/html') === 0;
}
```

That way, when something goes wrong — like in this case with IE8 — it falls back to determining that the request is for HTML.

**Comment by klonos** [comment]
Sounds reasonable to me. Instead of checking if it is actually html, we check if it ain't anything else but html.

**Comment by quicksketch** [comment]
Very well spotted @dboulet! Sorry I missed your ping earlier. I think adjusting `backdrop_is_html()` would be a great fix. I'm not sure about having `backdrop_is_html()` call `backdrop_is_ajax()` however, seems as though that could get messy trying to have these functions call each other.

Agreed though, this should be more lenient than it currently is. I think if a browser ends with `*/*`, that should be considered an HTML response as well.

This issue could cause a very substantial bug if the IE8 request is cached and served to other browsers, as pointed out in https://github.com/backdrop/backdrop-issues/issues/1664.

**Comment by quicksketch** [comment]
An absolutely delightful summary of browsers and their different `Accept` headers for reference: http://www.newmediacampaigns.com/blog/browser-rest-http-accept-headers

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/1290 that fixes this by depending more heavily on `$_SERVER['HTTP_X_REQUESTED_WITH']`, which is used in all AJAX queries made by jQuery (and other libraries). Basically, if set but "text/html" is not specifically requested, then an HTML response is expected.

We will still need a more robust solution to handle this universally, but this will fix the immediate bug. We can continue in https://github.com/backdrop/backdrop-issues/issues/1664.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1290. Great find @dboulet. Thanks!

**Comment by dboulet** [comment]
That’s great, thanks @quicksketch. Does this also fix https://github.com/backdrop/backdrop-issues/issues/1727?

**Comment by quicksketch** [comment]
Yes it does! I'll close that also.
