### ISSUE TITLE
Remove user_user_operations() and check for other cruft code

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1492]
It looks like `user_user_operations()` is still in our codebase, in spite of `hook_user_operations()` being removed.  Let's remove it. We should also check and see if the callback functions are being used as part of the bulk operations to manage users.  If not, we should remove these as well.
* `user_user_operations_unblock`
* `user_user_operations_block`
* `user_multiple_role_edit`

**Comment by serundeputy** [comment]
patch: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1185.patch

Removed `user_user_operations()`, `user_user_operations_unblock`, `user_user_operations_block`, and `user_multiple_role_edit`.

`User` tests pass on local (travis is going now)

Manually tested bulk ops:
<img width="432" alt="screen shot 2016-01-09 at 1 34 30 pm" src="https://cloud.githubusercontent.com/assets/6763671/12217702/9d81c40c-b6d6-11e5-973c-6f557c70c729.png">


They are working.  Needs review.

**Comment by quicksketch** [comment]
Thanks @serundeputy! Merged into 1.x and 1.2.x.
