### ISSUE TITLE
[UX] Move user emails to separate admin page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1493]
Right now all the user emails are in vertical tabs at the bottom of the user account settings page. There are several things wrong with this from a UX perspective. First, it clutters the user account page. Second, people may want to view more than one email at a time, making vertical tabs the wrong UI tool for the job.

Proposed resolution:
* Create a new page at admin/config/people/emails and move all the emails here
* Remove vertical tabs and use collapsed (and collapsible) fieldsets.

**Comment by serundeputy** [comment]
Patch: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1184.patch

This moves the User E-mail configuration to its own form: `admin/config/people/emails`

Needs manual user testing to be set to `Reviewed and Tested by the Community`. (@jenlampton ?)

- [x] Travis passed.

**Comment by quicksketch** [comment]
This looks pretty good @serundeputy!

This might be an opportunity to change "e-mail" to "email" as mentioned in Gitter by @mikemccaffrey. We decided on the non-hyphen version in #1056. If we change this, we should update all instances of "e-mail" in this entire form.

The menu item `User E-mail settings` would become `User email settings` (lowercase e, as our menu items are sentence-cased).

Not sure about moving all this code to `user.emails.inc`. It seems like keeping it in `user.admin.inc` with the other admin pages would be just fine.

Lastly, just starting this page right off with a bunch of collapsed fieldsets was a bit overwhelming to me when I first loaded this page. Could we add a `$form['help]['#markup'] = '<p>' . t('Help text') . '</p>'` element at the top of this form and give it a description? e.g. `Use this form to customize the emails sent by your website. Each template may use tokens to populate special values such as a user account name or the password reset link.`

Suggested changes in a screenshot:
![selection_034](https://cloud.githubusercontent.com/assets/100206/12219014/1cb1189a-b6e6-11e5-9a9f-6063a0709260.png)

**Comment by serundeputy** [comment]
new patch link: 
* rebased
* Moved everything back into `user.admin.inc`
* Added context/help text to the top of the new form page
* Renamed page
* Renamed menu item

**Comment by serundeputy** [comment]
ahhrgh; I just noticed in your screenshot the help text for each fieldset has`e-mail` ... I'll update that to `email`.

**Comment by serundeputy** [comment]
updated and rebased changing fieldset help text from `e-mail` to `email`.

**Comment by quicksketch** [comment]
Looking great @serundeputy! Some additional feedback posted to the new PR https://github.com/backdrop/backdrop/pull/1184

**Comment by serundeputy** [comment]
thanks ; :bow: I'll fix those up tomorrow :smile:

**Comment by serundeputy** [comment]
patch: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1184.patch

* removed `token_cache_clear();`
* Updated language for form description no self referential
* Fixed user.test t'was looking for `e-mail` rather than `email`

- [x] Travis y tests

**Comment by quicksketch** [comment]
Could you remove this line:
```
 +    '#description' => 'Help text to give context to the User emails form.', 
```

On a `#markup` it won't do anything. If you wanted, it could be a code comment above the `$form['help']` element instead.

**Comment by serundeputy** [comment]
hupdated rebased;

**Comment by quicksketch** [comment]
Nice work @serundeputy! Merged into 1.x for 1.3.0.
