### ISSUE TITLE
HTTP request status: Fails

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1494]
I'm on a Windows/nginx environment and I've been getting this since like ever:

![backdrop-status_report-http_request_status_fails](https://cloud.githubusercontent.com/assets/2423362/12210455/3581e634-b6ae-11e5-902d-5fc31934d8db.png)

```
HTTP request status	Fails
Your system or network configuration does not allow Backdrop to access web pages,
resulting in reduced functionality. This could be due to your webserver configuration
or PHP settings, and should be resolved in order to download information about
available updates or use other network-dependent services. If you are certain that
Backdrop can access web pages but you are still seeing this message, you may add
$state['backdrop_http_request_fails'] = FALSE; to the bottom of your
settings.php file.
```

So far I've been ignoring it, but my OCD kicked in really hard this morning, so I thought to at the very least file an issue for it.

Core and contrib version checks work as I am able to get version updates, so I don't know why this error should be there. adding the ```$state``` line in ```settings.php``` is a work-around and not a real solution and frankly we should avoid asking users to manually mess with config files because it's error-prone.

I can help troubleshoot this so we can get to the bottom of it and provide an actual solution. Just let me know what I should change in core in order to add a debug message in the appropriate place so I can trace exactly what web pages is backdrop trying to access and why they seem to be blocked.

**Comment by klonos** [comment]
This gets more annoying now with #639 implemented. I constantly have an alert on my admin bar. ...and just to be clear, it's not the alert itself that bothers me - I want that specific issue to be eventually resolved so that my status bar is green.

**Comment by quicksketch** [comment]
Unsurprisingly this has also been discussed in the Drupal queues: https://www.drupal.org/node/965078

It looks like the solution they've arrived at (but not yet implemented) is to just log watchdog errors if an HTTP request fails, rather than trying to put this information in the site status report. That makes sense to me, especially as the status report check isn't accurate on all systems.

**Comment by quicksketch** [comment]
It looks like the D7 approach worked as was generally approved, but implementation and backporting to D7 was held up by D8 switching to use Guzzle. As such, the D7 patch was never applied. We don't have that issue here, so I'll file a PR for crossporting this and we can be rid of this error.

**Comment by quicksketch** [comment]
PR https://github.com/backdrop/backdrop/pull/1222

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1222 for 1.3.1.
