### ISSUE TITLE
SOS! https://backdropcms.org/modules

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1496]
https://backdropcms.org/modules
https://backdropcms.org/themes
https://backdropcms.org/layouts

![error](https://cloud.githubusercontent.com/assets/13515302/12214611/c260c068-b6ac-11e5-87f7-b397909a1613.gif)

**Comment by dboulet** [comment]
This should probably be moved over to https://github.com/backdrop-ops/backdropcms.org/issues.

**Comment by jenlampton** [comment]
1) thank you @bd0bd  for reporting the issue. We have disabled the module that was causing it and will dig deeper.

2) Yes @dboulet is correct, we should create an issue in the backdropcms.org queue to fix this :)
