### ISSUE TITLE
[UX] Pathauto follow-up: automatically target the appropriate field when entering tokens from the token browser.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1497]
There might be other places where this can be applicable, but I am initially filing this about the "Default URL pattern" field available under the "URL pattern" vtab in the content type create/edit form. Also note that I am testing with the changes from #899 applied.

Problem/STR:

1. Go to a content type edit form (```admin/structure/types/manage/article``` for example)
2. Scroll down and click the "URL pattern" vtab
3. **Without clicking on the "Default URL pattern" field**, click the "Browse available tokens." link
4. Click on any of the available tokens

...you get a "First click a text field into which the token should be inserted." message.

So the user now has to close the error message, close the token browser, click on the "Default URL pattern" field and repeat steps 3 and 4 to actually get a token in the field.

I have done some more testing and if after closing the error and token browser you select a field available in that form other than the "Default URL pattern" (the content type "Description" field for example), the token is entered there instead of the "Default URL pattern" one. The user might notice that, especially if they are on large screens where the description field can be within the view port but they most likely won't notice and will start repeating the token insertion thinking this does not work.

Can't we be smarter in situations like this? We should either auto-select the "Default URL pattern" field upon vtab selection (in this case it is the only field available anyways, but assuming that there will always be a single field is bad practice) or better yet make sure that when clicking the "Browse available tokens." link, some magic is done and the respective intended field is selected **before** the token browser dialog opens.

Another example where this fails:

1. In the same content type form, scroll down and click a field in a vtab **other than the "URL pattern" vtab** (the "Title field label" under the "Submission form settings" vtab for example
2. Then select the "URL pattern" vtab
3. **Without clicking on the "Default URL pattern" field**, click the "Browse available tokens." link
4. Click on any of the available tokens

...you get no error this time, but the token is inserted in the "Title field label" field (or whichever field you selected in step 1). In this case, the user will definitely not notice the insertion of the token, as the field it has been inserted into is hidden in a tab other than the active one.

We should also make sure that this behavior is not allowed.

...checking to see if this applies to other forms with field that support tokens and will update accordingly.

**Comment by docwilmot** [comment]
That can be a bit annoying yes. You actually dont need to close the token browser after you get the error message, you can click around while the browser is active. That way you can open one browser and insert tokens in multiple fields. 

We could link the browser to a particular field on opening it so that field gets focus immediately, but I suspect one issue with that is you still actually need to tell the browser *where* in that field you want the tokens inserted. Say you want `klonos/[node:nid]/stuff/[node:title]` you'd still need to click the appropriate spot.

As a solution we could use JS to disable the browser link, and change it to "Select a field to add tokens" or something like that unless an appropriate field has focus. How's that?

**Comment by klonos** [comment]
> You actually dont need to close the token browser after you get the error message, you can click around while the browser is active.

True. Although I'm not sure how well this would work on smaller screens where the dialog cannot be moved around out of the way in a manner where the field is visible/clickable while the browser is still within view (the dialog cannot be moved outside of the boundaries of the page).

> ...you still actually need to tell the browser *where* in that field you want the tokens inserted. Say you want ```klonos/[node:nid]/stuff/[node:title]``` you'd still need to click the appropriate spot.

Yes, and in the case where there is already pre-existing text in the field, we'd need to make sure that this text is not selected or else it will be overridden by the inserted token. I guess in this case we'd need to make sure that perhaps the cursor is placed at the end of any existing text so that new tokens are appended instead.

> As a solution we could use JS to disable the browser link, and change it to "Select a field to add tokens" or something like that unless an appropriate field has focus. How's that?

How about we duplicate the field in question at the top of the token browser (where we currently have the "Select a token to insert it into the current field." text)? This would work better in mobile/small screens I think. Upon submit we close the token browser and update the vale in the actual form. That will ensure that the field is within view as tokens are entered (user can also move the cursor around to where they need the token to be inserted) and we also make it clear where the tokens will land by having the browser title include the field label. The link could be something like "Use tokens" or "Advanced edit" or something.

**Comment by docwilmot** [comment]
> duplicate the field in question at the top of the token browser

Thought of that, but in a page with multiple fields and one browser link  like the `admin/config/search/path/patterns` page, that wouldnt work very well.

Couple other thoughts:
- what if there was only one token browser link at the top of the page, like one of the local actions links (the ones with the "+" signs), on any page with tokenized fields? 
- Or what if the links opened a drawer on the page bottom or side?

**Comment by klonos** [comment]
>Thought of that, but in a page with multiple fields and one browser link  like the `admin/config/search/path/patterns` page, that wouldnt work very well.

True again. We could provide a set of next/previous field buttons/links.

In all honesty, I see all the problems and I don't particularly like anything in specific from what we were able to come up so far. Let's brainstorm a bit longer and wait for input from others (@wesruv??).

**Comment by wesruv** [comment]
Thinking of this from a different direction, I don't really like the token browser as the default way of figuring out tokens. 

Is it plausible to do auto-complete when the user enters `[` in a field that takes tokens? Seems like it'd be a better default way to add tokens and the token browser can act more as a reference.

I haven't tested this functionality (didn't know it existed actually), I'll mess around and see if anything else comes to mind.

**Comment by docwilmot** [comment]
> do auto-complete when the user enters [ in a field that takes tokens

That would be brilliant. Hope it can be done.

**Comment by klonos** [comment]
The auto-complete would be a very cool way for Drupal/Backdrop-savvy people to quickly enter tokens. Newcomers would need to be told that ```[``` triggers the token auto-complete.

**Comment by klonos** [comment]
...I would much rather we moved the link for the token browser next to the respective field and have its text be something like "Use tokens..." or "Use dynamic values...". Then the token browser could include the field it was triggered from at the top (plus a set of next/previous navigation for forms where we have multiple fields that accept tokens - like the patterns admin page).

**Comment by klonos** [comment]
> plus a set of next/previous navigation f...

Like this:

![mobile_keyboard-prev_next_done](https://cloud.githubusercontent.com/assets/2423362/12241064/e52028e8-b8e4-11e5-9cf1-ad56935e4859.png)

**Comment by klonos** [comment]
There is another usability issue with this situation...

So, I was creating a custom content type and was editing its settings. After setting the title field label in the "Submission form settings" vtab, I moved to the "URL pattern" vtab, clicked on the "Browse available tokens" link and tried adding a token. I saw that the token was not added in the field and I remembered this issue here where the field is not auto-focused. So, I clicked on the field, then tried adding the token and of course this time it worked. It was only after I tried creating a node of that content type that I realized what my first click on the token browser had actually done:

![backdrop-token_browser-not_focusing_on_the_proper_field_might_add_token_in_unwanted_fields](https://cloud.githubusercontent.com/assets/2423362/16823703/51a6d48a-49a9-11e6-991e-31590db17dd6.png)

We should either fix this by making sure that the proper field is focused or at least change the static "Available tokens" modal title and/or the "Select a token to insert it into the current field." text to provide a hint as to where the token is going to be added...

If we could somehow detect which field is the currently focused one, we could change the text to "Select a token to insert it into the [focused_field_label] field." That text though is not very prominent. We could try making the `[focused_field_label]` part of it bold, or change the modal title to something along these lines: "Available tokens for the [focused_field_label] field."

The ideal solution of course would be to have it so that either clicking on the "URL pattern" vtab or clicking on the "Browse available tokens" link, focuses on the "Default URL pattern" field.

**Comment by serundeputy** [comment]
Adds js to focus the `input#edit-path-pattern` when adding/editing a content type on `/admin/structure/types/add` vertical tab `URL Pattern`.

`PR`: https://github.com/backdrop/backdrop/pull/1463

test server:
Website: http://1463.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: RLq5suZS

**Comment by klonos** [comment]
Works like a charm! Thanx once again @serundeputy

**Comment by quicksketch** [comment]
The functionality looks great but we could improve the implementation a bit. I posted some feedback to https://github.com/backdrop/backdrop/pull/1463/files#r72731782.

**Comment by serundeputy** [comment]
Thanks @quicksketch 
I've updated the `PR` based on the feedback.

**Comment by quicksketch** [comment]
Looks good to me! Merged https://github.com/backdrop/backdrop/pull/1463 into 1.x and 1.4.x for 1.4.4
