### ISSUE TITLE
[UX] Layouts - better terminology for configuration pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1503]
This is a spin off from https://github.com/backdrop/backdrop-issues/issues/771

Layout currently defines two paths for configuring a layout:

```
admin/structure/layouts/manage/%/edit
admin/structure/layouts/manage/%/settings
```

If we did this properly, we'd rename both of these menu items so that `Edit` became `Place blocks` (or something) and `Settings` became `Configure`. How about

```
admin/structure/layouts/manage/%/blocks
admin/structure/layouts/manage/%/configure
```

Then the tabs would look like:

![selection_035](https://cloud.githubusercontent.com/assets/100206/12219786/3b454b08-b706-11e5-88ff-c4691e00a371.png)

Thoughts?

- - -
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1445

**Comment by jenlampton** [comment]
I really like the idea of calling the main layout page "Blocks".  I think it will help new users tie all the pieces together :)  I also like renaming the settings page to configure :+1:

**Comment by docwilmot** [comment]
Actually, yes, that works.

**Comment by jenlampton** [comment]
I started on a PR for this but tests are currently failing...

**Comment by quicksketch** [comment]
We ran into a bit of an issue here in that "Blocks" becomes the primary drop button item on the list of layouts. That isn't an "action" and can be confusing on the list of Layouts:

![selection_044](https://cloud.githubusercontent.com/assets/100206/12368308/13277e82-bb9f-11e5-9127-3fd10f1759ec.png)

Though maybe we can just leave that "Configure" and link to the blocks page? Then the "Configure" tab doesn't make sense.

I think we should postpone this to the next release while we get this sorted out.

**Comment by jenlampton** [comment]
What about `Place blocks`?  That's the terminology Drupal 8 uses.

**Comment by klonos** [comment]
I wouldn't mind "Place blocks", but users can also move, remove (also show/hide once we get #1776 in) and configure blocks from that tab. So "Manage blocks" better?

**Comment by klonos** [comment]
...thought that if we have a "[Place|Mange] **blocks**" action, then we'd perhaps want to be more verbose about the rest of the actions by appending "layout" to them. Here's how it would look with both versions:

![backdrop-layout_admin_ui-mange_blocks_vs_other_layout_actions](https://cloud.githubusercontent.com/assets/2423362/15277755/175a77b4-1b50-11e6-82ce-feccaacd2df0.gif)

I'm not sure if being verbose clutters the UI though?

**Comment by biolithic** [comment]
thanks for the visual

**Comment by klonos** [comment]
> I'm not sure if being verbose clutters the UI though?

It seems that we do that in the Views UI, so I guess verbose is OK:

![backdrop-views_ui-verbose_dropbutton_actions](https://cloud.githubusercontent.com/assets/2423362/15277788/f510191a-1b50-11e6-922e-b96a91aad259.gif)

**Comment by jenlampton** [comment]
For some reason `Manage blocks` seems to imply editing each one on it's own - not placing them into a layout. Maybe that's because all the other places we `Manage` something it's that way. What about `Arrange blocks`?  That covers adding/removing/etc.

**Comment by quicksketch** [comment]
I like the verbose list just fine. The comparison to Views is a great one as well. Sometimes more verbose is better; we seem to be leaning that way in a lot of our menu items these days.

> For some reason `Manage blocks` seems to imply editing each one on it's own - not within the context of a layout.

In a way you are editing (or really "configuring") each one individually. I suppose if you went really verbose, it would be "Manage layout blocks". The text "Arrange blocks" doesn't indicate anything beyond positioning to me.

**Comment by jenlampton** [comment]
I'd be expecting to see the list from `admin/structure/block` at a manage blocks link , just like we manage content and manage users. This is something different, where we can put block-things together onto -layout-things.

**Comment by quicksketch** [comment]
Kicking this to 1.5.0. We had more important items this release and we're all out of time for 1.4.0.

**Comment by klonos** [comment]
> The text "Arrange blocks" doesn't indicate anything beyond positioning to me.

Same here.

> I suppose if you went really verbose, it would be "Manage layout blocks".

:+1: for being precise even if that means also being more verbose.

To tell you the truth, that was my first thought, but I avoided suggesting it because I thought that people would not like the verbosity. Then I started looking for other examples in the other parts of the admin UI and I hit the "Change View name/description" label. That made me think that if that got accepted, then why not allow "Manage layout blocks" too? But then I hesitated once more because we say "Manage fields" - not "Manage content type fields".

Anyways, I'm curious to see what others think now that we pushed this a few months back.

**Comment by jenlampton** [comment]
> Manage layout blocks

There's no difference between a "layout block" and a "block" so adding the word "layout" here doesn't help. In fact, it might actually make things even more confusing since people will wonder what the difference is between these new "layout blocks" and everywhere else where we call them "blocks". For the sake of consistency, I'd prefer not to change the noun here. 

Can we talk about the verb, though?  We aren't managing these blocks in the same way we are managing content, and users. In fact, there's a lot of "managing" that can't be done here. We can't filter, sort, or search, like we can on the content and user pages, and editing is only a secondary task (unlike on the other manage blocks page, at `admin/structure/block`.

The most important thing we do on these pages is position the blocks - it's a killer feature and one that's a bit different than all other "management of stuff" in Backdrop. If we don't like `Place blocks` or `Arrange blocks` can someone come up with another verb that adequately describes putting blocks into a specific location?

**Comment by jenlampton** [comment]
oOo I have an idea!  What if we used the word "Configure" twice? Like this: 
![configure2x](https://cloud.githubusercontent.com/assets/397895/16136083/95321a1c-33dc-11e6-98ef-b4b307abd3a3.png)

**Comment by klonos** [comment]
> There's no difference between a "layout block" and a "block" so adding the word "layout" here doesn't help...

I'm with you on that.

> About the verb: We aren't managing these blocks in the same way we are managing other things.

Also very good point.

> The most important thing we do on these pages is **position** the blocks...

Although this is *the* killer feature, it is not the only thing people are able to do in that page. This would be equally bad as for example calling the "Site information" page "Site name".

> oOo I have an idea! What if we used the word "Configure" twice? Like this: 

👍

**Comment by quicksketch** [comment]
Current PR isn't passing tests.

I'm not really sold on "Configure blocks" and "Configure layout". Seems like the same thing to me. I like "Layout settings" but it's not a verb like everything else. Perhaps "Configure blocks" and "Change layout settings"?

**Comment by jenlampton** [comment]
> "Change layout settings"?

No, the layout settings page is locaged at `admin/structure/layouts/settings` Let's not forget that this is a spin off from the issue that was called "Use edit and configure consistently." `Settings` needs to be changed to `Configure`.  

What's up for debate here is what to call the `Place blocks` page.

**Comment by jenlampton** [comment]
> Although this is the killer feature, it is not the only thing people are able to do in that page. This would be equally bad as for example calling the "Site information" page "Site name".

I'm not sure I agree with you here. I think it's far more important that people are able to find where to perform the most common tasks than fit is that they can find the edge-case tasks. And if we choose a name that prevents people from performing a common task easily just because we want to be inclusive, that's a UX fail.

Was I the only one who objected to `Manage blocks`?  If so, I'm tempted to just go with that so we can get this done :)  It's better than what we have now. Baby steps?

**Comment by klonos** [comment]
Well, we do have "manage" in the path which honestly sits better with me than just "place" (although I understand why "place blocks" might sell better).

I tried reading this thread from the start and to tell you the truth, even the initial screenshot with plain "Blocks" and "Settings" (without any verb) seems acceptable:

Structure > Layouts > [layout_name] > Blocks
Structure > Layouts > [layout_name] > Settings

**Comment by klonos** [comment]
...I just re-read everything and remembered that we are trying to replace "settings" with "configure". I also tried to see what's the current situation with the rest of the UI/menus and noticed that we use "configure" elsewhere, like with content types:

Structure > Content types > [content_type_name] > Configure
Structure > Content types > [content_type_name] > **Manage** fields/display

...and menus (although we use "edit" instead of "manage" there ...OCD kicking in again 😜 ):

Structure > Menus > [menu_name] > Configure menu
Structure > Menus > [menu_name] > **Edit** links

So, I say it's more consistent if we go with:

Structure > Layouts > [layout_name] > **Manage** blocks
Structure > Layouts > [layout_name] > Configure

**Comment by docwilmot** [comment]
As far as the tabs and links go I like
> Structure > Layouts > [layout_name] > Manage blocks
Structure > Layouts > [layout_name] > Configure layout

But re the place-blocks page: as noted in https://github.com/backdrop-ops/backdropcms.org/issues/55#issuecomment-226800377 I think when describing that page in documents, too many of our naming concepts are similar (manage block, configure block, layout setting, configure layout) and this is likely to be confusing, so I propose to not try to be too technically correct and call that page something unique that stands out, like "Layout designer" or "Layout Builder".

**Comment by klonos** [comment]
If we do go with a unique name, I think that Layout Builder is better because I think I've already filed an issue (can't find it at the moment and can't remember if it was against Drupal core) about a feature that would allow users to actually design layouts by drag and dropping regions that could be resized, renamed, aligned and moved around. That I think we'd call a Layout Designer.

**Comment by jenlampton** [comment]
We should be careful with both "layout builder" and "layout designer" as we
can't currently build or design layouts on that page. The design is set by
the layout template, as is the location of regions (build).

If we ever have a contributed project for building / designing in the UI
(like panels "builder" layout) this is going to be terribly confusing for
people.

Let's stick to verbs that reflect what we can currently do to blocks on
that UI: configure, place, manage, set up, rearrange, etc.

Long term, we're not going to be doing anything to the layout on this page
anyway (like designing/building) that would be done on the configure layout
page, or maybe a new page for that specific purpose.

**Comment by docwilmot** [comment]
TBH I looked at my last post earlier and also disagreed with myself.
I think for docs it may suffice to be verbose in the docs rather than in the UI and just say "go to the Manage blocks page for the XXX layout". Final vote:
> Structure > Layouts > [layout_name] > Manage blocks
Structure > Layouts > [layout_name] > Configure layout

**Comment by klonos** [comment]
> We should be careful with both "layout builder" and "layout designer" as we can't currently build or design layouts on that page....

> TBH I looked at my last post earlier and also disagreed with myself.

That's why I said "**If** we do go with a unique name..."

**Comment by BioALIEN** [comment]
I'm also in agreement with "Manage ..." and "Configure ...". These are technical terms that are widely used in various applications. "Place Blocks" just sits weird with me, and also when it comes to translating the string further down the line.

> Structure > Layouts > [layout_name] > Manage blocks
Structure > Layouts > [layout_name] > Configure layout

**Comment by jenlampton** [comment]
Since it sounds like there is consensus around `Manage blocks` and `Configure layout` I have pushed a new PR with those names. Testing now.

**Comment by jenlampton** [comment]
PR that should pass all tests now.

**Comment by quicksketch** [comment]
> Since it sounds like there is consensus around Manage blocks and Configure layout I have pushed a new PR with those names.

The current PR seems to use "Configure blocks" in places. And the drop button is for some reason overrunning the "Storage" column:

![screenshot from 2016-09-12 19-05-56](https://cloud.githubusercontent.com/assets/100206/18459149/fa92c562-791b-11e6-8b76-a5f516b5344a.png)

Although that drop button issue may have been pre-existing, we should fix that here as this is exposing a problem that previously did not surface to the UI.

**Comment by jenlampton** [comment]
> The current PR seems to use "Configure blocks" in places. 

Found it, fixed it.

> And the drop button is for some reason overrunning the "Storage" column

Ah, it looks like we expected drop-buttons to be much narrower than this. Since the are absolutely positioned, they won't push the table cells out large enough to enclose them. Adding some CSS to the layout admin to accommodate.

> we should fix that here as this is exposing a problem that previously did not surface to the UI.

Hm, were you hoping for a more general fix than just the layout UI?

**Comment by quicksketch** [comment]
> Hm, were you hoping for a more general fix than just the layout UI?

Just the layout UI is fine as long as we're not breaking drop buttons somewhere else.

**Comment by quicksketch** [comment]
The PR looks great. Merged https://github.com/backdrop/backdrop/pull/1445 into 1.x for 1.5.0.
