### ISSUE TITLE
Please provide hook_ckeditor_js_alter(), similar to hook_ckeditor_css_alter()

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1510]
I have javascript code, with attach/detach behaviors, that must be loaded and executed before CKEditor instance is loaded;
If CKEditor is executed in the legacy “iframe” mode, I have not found a way to achieve this.
As a workaround for a specific site, I can install the `divarea` plugin via a custom module to make CKEditor run in “inline” mode, but this is not an option for a standard contrib module.
So is it possible to provide a `hook_ckeditor_js_alter()` to solve the problem ?
Unless the question of the editor mode is debatable ?

**Comment by quicksketch** [comment]
> I have javascript code, with attach/detach behaviors, that must be loaded and executed before CKEditor instance is loaded;

Could you elaborate on what code you're trying to insert? Having an example will help to understand what solutions may be available.

>  So is it possible to provide a `hook_ckeditor_js_alter()` to solve the problem ?

We already have [`hook_ckeditor_settings_alter()`](https://api.backdropcms.org/api/backdrop/core!modules!ckeditor!ckeditor.api.php/function/hook_ckeditor_settings_alter/1). Would that work?

>  Unless the question of the editor mode is debatable ?

Switching to always use inline mode might be on the table. But it may introduce new issues, especially around the CSS that is loaded on the page. Once you get it working, it'd be great to hear how well it works.

**Comment by gifad** [comment]
[sorry for the delay, I'm 9 hours ahead of SF bay area time]
Well, this is going to be complicated...
First, this not a strict javascript issue (my script gets loaded and executes), so the request of hook_ckeditor_js_alter() is irrelevant, I should close this issue; but you asked me...
> "what code you're trying" : 

This is about captioned images : 
I want users to be able to specify the figure width, either in px or % (of the body width)
The caption may be long, but it must be constrained (wrapped) in the specified size
This should work in responsive environment, with image being wrapped in a picture element
Strict and absolute wysiwyg must be provided in CKEditor edit task
This works nicely if CKEditor is inline mode, as shown at : 
        http://p1347.phpnet.org/backdrop/l/3rgz8UIEd0Vd/node/24/edit
(urllogin module is amazing, BTW...)
In iframe mode, my javascript seems to do its job, but the final result is not good : the image inside the figure is not constrained the the figure width, as shown in 
![capture d ecran 2016-01-11 a 14 18 05-low](https://cloud.githubusercontent.com/assets/15943462/12235113/d74ff0b8-b871-11e5-9b3b-a0834db6dfba.jpg)
so this is rather a css issue...
Trying to debug this, and in reply to
> We already have hook_ckeditor_settings_alter(). Would that work?

[two hours later...] To make debug easier, I cloned my "CKEditor" format into a "iframed CKEditor"; did not succeed in playing with hook_ckeditor_settings_alter(), but succeeded in implementing : 
`function scald_image_ckeditor_plugins() {`
`  $plugins['divarea'] = array(`
`    'name' => 'divarea',`
`    'desc' => t('Divarea Plugin'),`
`    'path' =>  drupal_get_path('module', 'scald_image') . '/plugins/divarea',`
`    'buttons' => array(),`
`    'file' => 'plugin.js',`
`    'enabled callback' => 'scald_image_image_plugin_check',`
`  );`
`  return $plugins;`
`}`
`function scald_image_image_plugin_check($format) {`
`  return ($format->format != 'iframed_ckeditor');`
`}`
and finally fixed the issue with : 
`function scald_image_ckeditor_css_alter(array &$css, $format) {`
`  $css[] = /*base_path() .*/ 'core/misc/normalize.css';`
`  $css[] = backdrop_get_path('module', 'addon') . '/css/addon.css';`
`  $css[] = backdrop_get_path('module', 'scald_image') . '/scald_image.css';`
`}`
the addon.css supplies the mandatory : 
`img {`
`  height: auto;`
`  max-width: 100%;`
`}`
which should be in normalize.css, IMHO

So the issue may be marked as "works as designed, but with a bit of effort..."

**Comment by gifad** [comment]
Forgot to reply to 
> Switching to always use inline mode might be on the table

My opinion is there are now two kinds of sites : 

One is classic layout, information driven, bartik like, which in fact aims to provide paper magazine experience, specially for people who, like me, have been involved in the "Desktop publishing" revolution, some time ago; Here we want true wysiwyg, mode = divarea, backend === fronted
typically backdropcms.org

Second is "modern", money driven, layout (or lack of) suitable to smatphones, watches, or coffee machines, with aimed experience of scrolling powerpoint slides with full screen image, and very little text, the most important beeing "Click here to buy"; Here we want mode = iframe, and obviously backend theme != front end
typically, lullabot.com (no, I'm joking)

Backdrop market is in the middle, so I understand the question is not yet "on the table", but in the future, we should provide the choice

Finally, I think that as long as bartik or borg is the default theme, the default editing mode should be inline, with just an administrative layout just removing header and footer, but not sidebar(s)

**Comment by klonos** [comment]
@quicksketch 3 years later, is this still relevant?

**Comment by quicksketch** [comment]
Sorry this original answer kind of went unanswered, but it seems as though this was more of a support request than feature request. As the original reporter is no longer on GitHub we should close this out. Also interesting that with CKEditor 5, the editor is never within an iframe, which sounds like it might partially solve this request.
