### ISSUE TITLE
Make token insertion via token browser work with CKEditor

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1512]
Mentioned at https://github.com/backdrop/backdrop-issues/issues/1099#issuecomment-169459238;

> The content field of the block module uses filtered text and the wysiwyg, which I don't think would play well with tokens, right? Should we try to get it to do so? Should we perhaps think about adding a Token filter that is available to apply to text formats?

---
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/1775

**Comment by jackaponte** [comment]
This issue has been open for a while, and I understand if it's not high priority; that said, is there any other way to use tokens in custom blocks in the meantime? (Even help knowing where to _look_ for a list of available tokens would be great!

**Comment by docwilmot** [comment]
@jackaponte wish I could help but I don't understand CKEditor code TBH.
Added to CKEditor META at https://github.com/backdrop/backdrop-issues/issues/1087

**Comment by docwilmot** [comment]
Initial PR for consideration
- adds a token plugin and token icon to CKEditor. This opens the token browser in a modal dialog. The icon is borrowed and should be changed if this issue progresses.
- adds a new core token filter to allow selecting which textareas will have tokens read.

This is my attempt to figure out CKEditor and its mysterious JQuery magic. Hope its not too laughable.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1775 is pretty flippin' cool. It works and adds a working button to CKEditor, and tokens are inserted properly into the editor.

I set up a sample piece of content on the sandbox for testing and everything works:

http://1775.backdrop.backdrop.qa.backdropcms.org/posts/post-tokens

My take on this is that it's functionality that is both very powerful and very dangerous. Tokens have unfettered access to all sorts of data. Putting them into posts also means they end up getting cached, thus can expose data from one user to another when in the cache (e.g. a current user's private profile information could be cached and then shown to a different user). This functionality is so dangerous (and rather advanced), we probably wouldn't ship with a token filter enabled in any of the default text formats.

So for these reasons, I think this would make a much better contrib module than a feature in core. From reading over the code, it looks as though all of this functionality has the necessary APIs in place already and doesn't have any limitations that would prevent it from being a stand-alone module.

**Comment by Dinornis** [comment]
As much as I like what you did in this PR and the idea of short-codes in WordPress, I agree that this approach is too dangerous without including some options that would limit its use.

**Comment by jenlampton** [comment]
Sounds like this isn't a core candidate (yet) so removing the milestone for 1.7. If we want to add additional safety features and schedule it again, we can add the relevant milestone then.

**Comment by quicksketch** [comment]
I'm closing this one out as a better candidate for contrib. The code in the PR (https://github.com/backdrop/backdrop/pull/1775) is definitely portable as a starting point for any implementation.
