### ISSUE TITLE
[UX] Remove menu settings page and related unused functions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1514]
It looks like we missed a little cruft. 

[UX] We have a settings page located at `admin/structure/menu/settings` that currently does nothing.  We should remove that so that it's not so confusing to users.

[DX] We also have two functions that aren't used anymore, `menu_main_menu` and `menu_secondary_menu` related to these settings. Let's remove these as well.

**Comment by quicksketch** [comment]
The PR looks good. We need an update hook to delete the unused `menu.settings.json` file however.

**Comment by jenlampton** [comment]
Just pushed a new PR with an update hook.

**Comment by quicksketch** [comment]
Super! Merged into 1.x for 1.3.0.

Even though we've never used these two functions in Backdrop, we should make a change record indicating that they no longer exist.

**Comment by klonos** [comment]
reopen for change record or a separate issue?

**Comment by klonos** [comment]
Sorry for reopening. Just making sure we have that change record in place. Do we? If not, should I go ahead and file a separate issue to get it done or handle it here?

**Comment by docwilmot** [comment]
For change records we go ahead and close it but add a "change record" tag

**Comment by klonos** [comment]
My bad then. Just thought that closed issues slip under the radar. Perfectly fine is we check for the "needs change record" tag. Closing again. Sorry for the noise.

**Comment by BWPanda** [comment]
> Just thought that closed issues slip under the radar.

Looks like @klonos was correct. 7 years later and still no CR... I only came across this as I'm trying to remove the 'Needs - change record' label from old, closed issues.

Re-opening to address this.

**Comment by herbdool** [comment]
I feel like I win some kind of prize for the newest change record for the oldest issue: https://docs.backdropcms.org/change-records/removed-unused-menu-settings-page-for-setting-the-main-and-secondary-menus-and-related-functions-and-settings

**Comment by argiepiano** [comment]
It looks like a `&nbsp;` slipped through within the `<code>` tag in the CR...
