### ISSUE TITLE
Question about meta name="Generator" 

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1516]
Hi!

This code - <?php print backdrop_get_html_head(); ?> - in the page.tpl.php file displays  this on the all website pages:

    <meta name="Generator" content="Backdrop CMS 1 (http://backdropcms.org)" />

But I can not find where this meta is located.
I try to find it with help of Folder Find Text but can not.
The only place it is located at **/core/modules/system/tests/system.test** which has no relations with the actual code of my website pages.

Please help :)

Thank you!

**Comment by dboulet** [comment]
Hi @bd0bd, take a look at the `_backdrop_default_html_head()` function in `core/includes/common.inc`.

**Comment by quicksketch** [comment]
If you're looking at changing this value, you can do so in a custom module or theme with [`hook_html_head_alter()`](https://api.backdropcms.org/api/backdrop/core!modules!system!system.api.php/function/hook_html_head_alter/1).

**Comment by bd0bd** [comment]
@dboulet and @quicksketch, thank you very much!
May I remove this meta completely off?
Or this is obligatory to be there?

I need to customize my sourse code something like Zeldman's: view-source:http://happycog.com/

**Comment by dboulet** [comment]
Yes, it can be safely removed if you need it gone. Use code like the following:

```php
/**
 * Implements hook_html_head_alter().
 */
function themename_html_head_alter(&$elements) {
	// Remove the Generator tag.
	if (isset($elements['system_meta_generator'])) {
		unset($elements['system_meta_generator']);
	}
}
```

Replace `themename` in the function name with the name of your module or theme.

**Comment by bd0bd** [comment]
Thank you!

**Comment by quicksketch** [comment]
:+1: @dboulet! I think this is resolved. :smile:
