### ISSUE TITLE
[UX] Clarify admin bar links to module pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1518]
Current Admin bar: 
- Install module
- Modules
- Project browser
- Update
- Uninstall

Proposed Admin bar:
- List modules
- Install modules
- Uninstall modules
- Update modules

**Comment by klonos** [comment]
:+1: ...withe the exception of "Install modules" coming before "List modules" (alphabetical order).

**Comment by klonos** [comment]
...also, should we generalize to "project" instead of "module" where appropriate? It's funny that the "Install module" link leads to a "Install a project" page.

**Comment by mikemccaffrey** [comment]
> ...with the exception of "Install modules" coming before "List modules" (alphabetical order).

Sorry, but i think it would make far more sense to order menu items by the amount they are used, rather than alphabetical. 9 times out of ten, the user is going to want the module list, and that link should be the easiest to find.

**Comment by klonos** [comment]
> 9 times out of ten, the user is going to want the module list, and that link should be the easiest to find.

Users already have an easy way to get to the modules list. They can simply click on the top-level "Functionality" menu item. :wink:

**Comment by jenlampton** [comment]
> Users already have an easy way to get to the modules list. They can simply click on the top-level "Functionality" menu item. :wink:

Unfortunately, usability studies show that if you give people a drop-down menu, they don't click on the top items anymore. They follow them all the way down to the bottom. This is why we have links in the menu for things like "List" (which are often the same as their parents).

> It would make far more sense to order menu items by the amount they are used

This is what Drupal 7 tried to do when they rearranged all the menu items. In D6 they were all alphabetical. As it turned out, it doesn't scale. People always know that P comes between O and Q, but as you add more and more items to a list, the importance of two items gets harder and harder to determine, and people end up unable to find most things easily (even if they are the most important, and at the top!)  

However - for the modules drop-down, this is not likely to need to scale as there are very few contrib projects that add things here. I recommended the current order because it puts the most important item first. :)

I actually wondered about the location of all "Action links". But see https://github.com/backdrop/backdrop-issues/issues/1565 for more on that.

**Comment by jenlampton** [comment]
Looks like this issue was resolved with https://github.com/backdrop/backdrop-issues/issues/1399 being merged. closing.
