### ISSUE TITLE
[UX] Rename `User email settings` page to `Account emails`

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1525]
A follow up to https://github.com/backdrop/backdrop-issues/issues/1493 
We just noticed this page should maybe have a different name :)

**Comment by jenlampton** [comment]
Optimistically setting milestone?

**Comment by quicksketch** [comment]
Sure, no problem getting this in as long as our tests pass. :)

**Comment by quicksketch** [comment]
Super, merged in https://github.com/backdrop/backdrop/pull/1210.
