### ISSUE TITLE
EU Cookie Bar is not displayed - Backdrop 1.2.3

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1526]
Hello Developers,

can you help me? I am a German user of Backdrop CMS and need a EU Cookie Bar in the blog. Now I have installed the module with cookies and tried to adjust.

In the frontend but no Cookie Bar appears. I saw it with me just Google Chrome and of course I have previously deleted the cookies with Ccleaner.

How can it still be that nothing is displayed. I guess that is still the settings and to me it looks like. At least the upper part of the settings.

![backdrop-cms-eu-cookies](https://cloud.githubusercontent.com/assets/7885632/12354660/a9e3fa60-bb97-11e5-893b-d3475ae4d11d.jpg)

**Comment by Graham-72** [comment]
Hi @AlexL777 Have you tried deleting cookies once more and seeing if the pop-up reappears? Please let me know as an issue at the contrib module's repository at https://github.com/backdrop-contrib/eu-cookie-compliance if possible, and I will see if I can help some more if needed. I assume it is the module eu-cookie-compliance that you are trying to use.

**Comment by BWPanda** [comment]
Closing this in favour of using the module issue queue.
