### ISSUE TITLE
Base Meta Tags page does not exist

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1527]
Sorry I can not add this post in Backdrop's issues so I am doing it here.

Base Meta Tags page does not exist here:
https://backdropcms.org/project/base_meta
"This webpage has a redirect loop"

**Comment by findlabnet** [comment]
So, I too can't find off. site issue queue, but something wrong.
![301](https://cloud.githubusercontent.com/assets/11479969/12379446/c80c2418-bd63-11e5-8d4a-160f840a035d.png)

**Comment by jenlampton** [comment]
@bd0bd and @findlabnet the backdropcms.org issue queue is here:
https://github.com/backdrop-ops/backdropcms.org/issues

**Comment by jenlampton** [comment]
Base meta tags redirect fixed: https://backdropcms.org/project/base_meta
