### ISSUE TITLE
[UX] Remove the anonymous user count from admin bar. It doesn't work.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1530]
Since anonymous users no longer have sessions, the count of them in the admin bar will always show zero. Let's remove this since it doesn't provide any useful feedback to the user.

**Comment by quicksketch** [comment]
Small feedback posted to the issue.

I would call this a bug. We can fix it in 1.3.1 rather than holding up the release for it.

**Comment by jenlampton** [comment]
Sounds good to me, updated milestone!

**Comment by jenlampton** [comment]
Pushed a new PR with feedback addressed.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1214 for 1.3.1. Thanks!
