### ISSUE TITLE
DX - Flag hidden value in Stark theme's info file

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1532]
It took me 15 min of refreshing the themes page, clearing all caches, and staring blankly to figure out that since I had copied Stark's info file, it had a line that read:
```
hidden = TRUE
```

I'd like to add a comment above it or something. Flag it in the file so it's obvious.

**Comment by wesruv** [comment]
PR Here:
https://github.com/backdrop/backdrop/pull/1216

**Comment by quicksketch** [comment]
Doh!!

Merged in https://github.com/backdrop/backdrop/pull/1216. Thanks @wesruv! This will be in 1.3.1.
