### ISSUE TITLE
Explanation or submission guidelines text does not display on node form

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1534]
The `Explanation or submission guidelines` that can be entered when configuring a content type is never displayed. This is because for some reason this text was displayed in the `Help` block that we removed from Backdrop core.  We should make it display, without the help block.

**Comment by quicksketch** [comment]
There have been a lot of times when I've wanted a reusable element for adding help to the page. Something like `#theme = 'help'` or `#type = help`. We don't need to handle that here, but it would make our help more consistent when we need to add it directly to the page.

**Comment by quicksketch** [comment]
Duplicate of https://github.com/backdrop/backdrop-issues/issues/1804.
