### ISSUE TITLE
[UX] Remove the #states behavior from "Sticky", "Promote" and "Revision" options for content types.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1536]
When enabled, these settings use #states in order to allow setting the default:

![backdrop-content_type-sticky_promote_options-show_option_enabled](https://cloud.githubusercontent.com/assets/2423362/12371447/f33bb73e-bc87-11e5-9b8c-80d42008bcbb.png)

...when disabled/unchecked, the respective default options are hidden:

![backdrop-content_type-sticky_promote_options-hide_option_enabled](https://cloud.githubusercontent.com/assets/2423362/12371450/ff0c42ea-bc87-11e5-866c-6b8fa2361cb5.png)

We should remove the #states behavior and have the default options be shown/available. Like so:

![backdrop-content_type-sticky_promote_options-on_by_default_locked](https://cloud.githubusercontent.com/assets/2423362/12371492/4518c7f8-bc89-11e5-9c87-0673c40c1a79.png)

One could classify this as a bug, since admins are not given the option to have nodes of a certain content type be promoted and/or sticky by default *unless* they give the content creators the option to change this setting.

**Comment by klonos** [comment]
> One could classify this as a bug, since admins are not given the option to have nodes of a certain content type be promoted and/or sticky by default *unless* they give the content creators the option to change this setting.

...well, it turns out they can do that, but in order to do it, they have to first set the default and then disable the "Show option to..." checkbox. The UX WTF in this case is that a) although the respective setting is reflected in the vtab summary, the option is hidden and b) is you need to uncheck these checkboxes, you first need to enable the respective "Show option to..." checkbox, then disable the default, then uncheck the checkbox.

**Comment by klonos** [comment]
...same goes for revisions. Admins should be able to set revisions to be made and not allow users to change this setting.

**Comment by quicksketch** [comment]
Thanks @klonos, good points on all counts.

**Comment by quicksketch** [comment]
PR https://github.com/backdrop/backdrop/pull/1220.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1220 for 1.3.1.
