### ISSUE TITLE
You can not activate Permissions checkboxes

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1540]
Hello Developers,

I've got a question or a problem at the same time. It occurs to me at Backdrop 1.3.0, you can not activate the check boxes in the Permissions.

I show you here a screenshot. These little right located checkboxes must be activated? I wanted namely EU Cookie Bar in the frontend and there is an authorization. I can because nothing but activate.

Can you observe such a thing?

Thank you in advance.

![permissions-checkboxes-not-active](https://cloud.githubusercontent.com/assets/7885632/12371956/4884171e-bc46-11e5-8991-6dfac78eff52.jpg)

**Comment by Graham-72** [comment]
@AlexL777 will the checkbox respond when you tick it, that is, will it become ticked?
After this you must select 'Save Permissions' at the bottom of the page so that your change is saved in one of the config files, for example 'user.role.administrator.json' or 'user.role.anonymous.json'.

**Comment by AlexL777** [comment]
Yes, the checkbox can be clicked and when I save the page down, the tick is out in the checkbox again. But it is stored, how can I see it.

Probably it works that way. At first I thought, you have to see the active tick in a checkbox.

**Comment by Graham-72** [comment]
When you save the page, it should refresh and the tick should still be there.
Please tell me exactly which one you are ticking and I will try it here.

**Comment by AlexL777** [comment]
I want to tick "Display EU Cookie Compliance popup", but the tick removed repeatedly after saving.

That struck me until today. There are Permissions under /admin/config/people/permissions

Whether it works for you?!

**Comment by AlexL777** [comment]
This is for me the contents of user.role.anonymous.json and with the EU cookies I myself entered, but that does not seem to agree.

    {
    "_config_name": "user.role.anonymous",
    "name": "anonymous",
    "label": "Gast",
    "weight": "0",
    "permissions": [
        "access content",
        "access comments",
        "post comments",
        "edit own comments",
        "access site-wide contact form",
        "search content",
        "use advanced search",
        "subscribe to comments",
        "view disqus comments",
        "display disqus comments on profile",
        "toggle disqus comments",
        "access user profiles",
        "use text format werbeformat",
        "display eu cookies compliance popup"
    ]
}

How about the row of cookies because right?

**Comment by Graham-72** [comment]
That looks right. The file user.role.anonymous.json has an entry for each permission granted to an anonymous user. There is a similar but longer file for an administrator at user.role.administrator.json.

The other settings that you change are stored in a config file for the specific contributed module - look for eu_cookie_compliance.settings.json but beware of changing any entries, except via the configuration page.

**Comment by AlexL777** [comment]
Unfortunately, works for me this cookie modules not like I need it and I have now made me already known cookie solution https://silktide.com/tools/cookie-consent/download/. So it worked out and I wanted to display Cookie for guests.

But I saw the cookie bar only when I was logged in as admin. Otherwise enough for me so I can then use this other solution. I have incorporated the cookie code in the template.

Nevertheless, I thank you that you have consumed so much time for me !!

**Comment by Graham-72** [comment]
> I wanted to display Cookie for guests. But I saw the cookie bar only when I was logged in as admin

Well, thanks for trying it. I have not had this problem myself, provided permissions are set for it to be displayed to anonymous users. I think maybe this should be the default behaviour.

**Comment by AlexL777** [comment]
Yes, is not bad, because I now have a solution. Test for me it was more than worth it.

**Comment by quicksketch** [comment]
Thanks @Graham-72 for helping!

I'm going to close this issue as it seems like the immediate concern has been solved.

However, I am worried by the problem described by @AlexL777. If this comes up again, please reopen this issue or make a new issue.
