### ISSUE TITLE
ob_end_flush notices in log

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1541]
I  updated from 1.2.2 to 1.3.0. Now my log has lots of notices (1 for every click): 
ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in backdrop_page_footer() (line 2951 of /home/www/backdrop/core/includes/common.inc).

**Comment by gifad** [comment]
I have only 2 sites upgraded to 1.3 : one (A) does show the notices, and the other (B) does not...
(A) is php 5.3.3, in fast cgi mode
(B) is php 5.6.11 in "Apache 2.0 Handler"

on (A), replacing line 2951 `ob_end_flush();` with `@ob_end_flush();` works, to hide the issue...

**Comment by vtad** [comment]
I have php 5.5. I will do a fresh install hoping the Notice disappears.

**Comment by quicksketch** [comment]
Thanks @vtad and @gifad! The way the page is flushed is indeed different depending on whether PHP is running as PHP-FPM or not, which is probably why one of them has the issue and the other does not.

I was not aware that `ob_end_flush()` would throw an error if there was no buffer. For now, silencing it with `@` sounds okay, but we'll want to switch that to something that doesn't empty the output buffer if there's nothing in it.

Let's get this fixed before 1.3.1.

**Comment by quicksketch** [comment]
It looks like in my testing, this line can just be removed entirely. The output buffer is entirely cleared already on line 2935 when we call `ob_get_clean()`, so the further call to `ob_end_flush()` is unnecessary. I'll file a PR.

**Comment by quicksketch** [comment]
PR https://github.com/backdrop/backdrop/pull/1218

**Comment by quicksketch** [comment]
I've fixed this in https://github.com/backdrop/backdrop/pull/1218. We'll make a 1.3.1 release before the weekend is over to clear this up.
