### ISSUE TITLE
Text editor, anchor button ignored

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1542]
Backdrop 1.3.0
Putting the anchor button in the action tool bar is ignored. It disappears after saving. I had no problems putting/removing other buttons from the action toolbar

**Comment by Graham-72** [comment]
Yes, reported at https://github.com/backdrop/backdrop-issues/issues/1231. We must add it to meta 'CKEditor/WYSIWYG/Rich text editor followups' at https://github.com/backdrop/backdrop-issues/issues/1087.

**Comment by gifad** [comment]
@vtad : No, it is not ignored : it ***is*** in the saved settings - it unsticks just when you reopen the settings page...

**Comment by quicksketch** [comment]
Thanks all! Let's continue this over in the existing issue at https://github.com/backdrop/backdrop-issues/issues/1231.
