### ISSUE TITLE
Add Bulgarian transliteration overrides

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1544]
We received a support request via info@backdropcms.org today with the following information:

> There is an error in a transliteration, and it incorrectly transliterates
> some letters from the Bulgarian language.
> It is present both in the separate module transliteration and the new
> Backdrop version 1.3.0 where transliteration is included in the core.
> 
> For example, if you have a publication with the name in Bulgarian language
> "първа статия" ("first article") the system transliterates it as
> "prva-statya" - the letter "ъ" is missing. It does not transliterates "ъ"
> bit deletes it. "ъ" is very specific Bulgarian letter - it is user only in
> Bulgaria. It is phonetically similar to "a" and usually is transliterated by
> "a". But in this case it is deleted, not transliterated.
> 
> I've managed before to solve this by editing the file x04.php
> I've done this early in Drupal to create my own preferred transliteration of
> Bulgarian letters.
> 
> I'm sending you attached file - my version of the file x04.php that runs on
> Drupal and in several Backdrop installations, which I did last month.

The attached file I'll make as a PR shortly.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1221.

**Comment by amilenkov** [comment]
Bulgarian transliteration now works fine in Backdrop-1.3.2. Thank you!!!

**Comment by amilenkov** [comment]
Only one note: in file bg.php line 67
0x044D => 'e'
is unnecessary. This is for Russian letter (a.k.a. "э") . It is not used in Bulgarian. This is not an error - this line is not used in Bulgarian transliteration. This line can be deleted in next updates for simplicity.

**Comment by klonos** [comment]
@amilenkov :wink:
