### ISSUE TITLE
HTTP request status: "web server" instead of "webserver".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1545]
Minor nit on the text of this error message:

`... This could be due to your webserver configuration or PHP settings, ...`

...it should be _[web server](https://en.wikipedia.org/wiki/Web_server)_ (2 separate words). It comes up as an error in the auto-correct and the 2 separate words yield [337,000,000 google search results](https://www.google.com/search?q=web+server) vs the [16,500,000 of _webserver_](https://www.google.com/search?q=webserver). ...I know, more OCD, but I can't help it :smile:

**Comment by serundeputy** [comment]
https://github.com/backdrop/backdrop-issues/issues/1494

> As such, the D7 patch was never applied. We don't have that issue here, so I'll file a PR for crossporting this and we can be rid of this error.

I think #1494 makes #1545 (this) moot; close?

**Comment by quicksketch** [comment]
> I think #1494 makes #1545 (this) moot; close?

Yep!
