### ISSUE TITLE
Drag and drop broken on touch enabled laptops

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#1550]
The tabledrag functionality is broken for me when I try to reorder fields and such by dragging the handle with my mouse. It seems to be a problem that specifically affects chrome users with a touchscreen laptop. Dragging with the touchscreen actually works well, but it seems to assume that since I have a touchscreen I don't need to use the mouse.

It looks like this problem has been documented over in Drupal Land:
https://www.drupal.org/node/2177293

**Comment by mikemccaffrey** [comment]
Yup, tabledrag.js assumes that if the device has touch support, it doesn't need to bind the mouse events:

```
  if (self.touchSupport) {
    $(document).on('touchmove', function (event) { return self.dragRow(event.originalEvent.touches[0], self); });
    $(document).on('touchend', function (event) { return self.dropRow(event.originalEvent.touches[0], self); });
  }
  else {
    $(document).on('mousemove', function (event) { return self.dragRow(event, self); });
    $(document).on('mouseup', function (event) { return self.dropRow(event, self); });
  }
```

**Comment by quicksketch** [comment]
This will be in 1.3.2.
