### ISSUE TITLE
Are white spaces allowed in a module path ?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1552]
I've not read that this is forbidden, and it worked a couple of days, until I had random crashes (white screen, with non sense message in apache error log);
Well, not totally random, it seems to be related to cache flush after add/remove/modify views plugin, in the autoload phase. To bring the system back to life, running update.php was the only option.

If the parsing error is too hard to locate, it would be easier to warn the admin in the status report ?

Just FYI, the white space came from the macintosh extension "Make symbolic link", which creates a link stupidly named "target symlink" (and the target was my git local repo, so this is a real world example :stuck_out_tongue_closed_eyes:)
[Edit:] The concept of using a symbolic link is not relevant : no issue if all names are plain alphanumeric characters.
[Edit2:] a word could be placed in the `modules/README.txt` (I just read it) about this restriction...

**Comment by jenlampton** [comment]
@gifad yes, module names need to be a single word. 

Often times this is solved by placing underscores between separate words, for example, the on_the_web module. This is because there are no spaces allowed in function names. Since each function in a module is a hook - for instance `hook_config_info()` - and a hook is implemented by concatenating the name of the module to the name of the hook - for instance `on_the_web_config_info()` -  there's no way a module name can contain any spaces.

**Comment by gifad** [comment]
Thanks for the reply, @jenlampton, but my question was less basic : I'm talking about the full path - for instance : 
`/home/www/backdrop/modules/custom/backdrop-mediakit symlink/direct_upload`
No trouble with Drupal(7), but this breaks Backdrop autoload somewhere...

**Comment by jenlampton** [comment]
Thanks for the clarification @gifad.  I would imagine that spaces in directory names (or symlink names) would be problematic for any autoloader. I don't know why that would work in Drupal (and not in Backdrop) but I would recommend avoiding spaces in paths whenever possible.

The issue might come from the function `backdrop_get_path` or (`drupal_get_path`)
https://api.backdropcms.org/api/backdrop/core!includes!common.inc/function/backdrop_get_path/1

**Comment by gifad** [comment]
More clarifications : 
1-It works on Drupal7 (no autoload) (did not try Drupal8)
2- `backdrop_get_path()`and the whole module work fine, until you begin to play with a component relying on autoload
3- After the site have been repaired (running `update.php`), it works again...

**Comment by BWPanda** [comment]
Question has been answered, closing.
