### ISSUE TITLE
Text Editor, how to add a link to a picture?

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1553]
The only way I found, was to go change to source code (html) an then insert the link around the image.
Selecting the image allows the use of the Link button but the created link is not saved. Directly clicking the image greys out the Link button. Under ckeditor in drupal I simply click the picture and then use the link button.

**Comment by quicksketch** [comment]
Let's consolidate this issue with the feature request at #1586. You're right at this point there is no way to do it through the UI.
