### ISSUE TITLE
Bartik: use the main menu tab style for the primary tabs too.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1554]
Now with #842 implemented and the option to choose between rounded (legacy), square and no tabs, I think we should match the primary tabs to that. If not for the no tabs, at least for the square. It simply looks funny to have a modern/square main menu while the primary tabs are still old-school:

![backdrop-bartik-square_tabs_for_all_menus](https://cloud.githubusercontent.com/assets/2423362/12397874/170ced1c-be64-11e5-85dc-056ecf8ba15b.png)

If this suggestion is accepted, the fieldset label should also be changed from "Main menu tab style" to "Menu tab style".

PS: by the way, all my tests are with preexisting installations that sometimes go back to 1.0.0. Do we have it so that in new installations the default is square? I think we should if not.

**Comment by docwilmot** [comment]
Sorry, had all of that in my original PR. But as I noted at https://github.com/backdrop/backdrop/pull/1129#issuecomment-170320796 I messed up my commit process somehow, and wiped out a good chunk of stuff. I don't know if its worth trying to fix now since 1.4.0 is supposed to come with a new front-end theme?

**Comment by klonos** [comment]
...well, it tool me removing two css rules to achieve this (line 1097 in ```style.css```):

```
.tabs ul.primary li a {
  color: #000;
  background-color: #ededed;
  height: 1.8em;
  line-height: 1.9;
  display: block;
  font-size: 0.929em;
  float: left; /* not LTR */
  padding: 0 10px 3px;
  margin: 0;
  text-shadow: 0 1px 0 #fff;
  -moz-border-radius-topleft: 6px;
  border-top-left-radius: 6px;
  -moz-border-radius-topright: 6px;
  border-top-right-radius: 6px;
}
```

...well OK, 4 lines if you count the ```-moz``` variants.

**Comment by jenlampton** [comment]
I agree with @docwilmot.  I'd prefer if we focus on replacing Bartik with something more modern.  A new front-end theme is going in 1.4.0! Let's work on making that really slick, and leave Bartik in the past :)

**Comment by docwilmot** [comment]
On that note, may I suggest we start a discussion or another of the famous @klonos METAs for building the requirements for our new front end theme?

**Comment by jenlampton** [comment]
Yes please! :)

**Comment by klonos** [comment]
Are you guys expecting me to start one?

![mr_bean_hello](https://cloud.githubusercontent.com/assets/2423362/12448630/6fcdf64a-bfcb-11e5-873f-866cbcbcce30.jpg)
