### ISSUE TITLE
Views writes log to watchdog about files[]  - update for new autoloader

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1559]
I just found a note in my watchdog logging as follows:
`_views_create_handler - loading handler handler(handler type: filter) failed: class addressfield_views_handler_filter_administrative_area could not be loaded. Verify the class file has been registered in the corresponding .info-file (files[]).`

In Backdrop, these classes should instead be added via `hook_autoload_info` so this message should be corrected to match.

**Comment by BWPanda** [comment]
I just got bit by this bug. Spent ages wondering why my class wasn't loading even after adding it to my info file. Marking as a bug.

**Comment by bugfolder** [comment]
Me, too, just now. PR to follow.

**Comment by klonos** [comment]
Thanks @bugfolder ...I don't want to block getting this in, but as an added bonus perhaps we should add a link to https://docs.backdropcms.org/api/backdrop/1/search/hook_autoload_info in the message? If you decide that that's a good idea, then please set this back to "needs review", and I'll have another look.

**Comment by bugfolder** [comment]
Sure. Updated.

**Comment by klonos** [comment]
Thanks @bugfolder 👍🏼  ...back to RTBC.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3835 into 1.x and 1.20.x. Thanks @bugfolder, @jenlampton, and @klonos!
