### ISSUE TITLE
Add support for uploading Office Open XML file attachments (MS Office 2007+).

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1563]
Using Views Send to try and send a Word docx file attachment I hit a restriction that seems to be built in to the code of core\includes\file.inc

`
$extensions = 'jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp ';
`
Is this something we should be able to modify through admin?

**Comment by klonos** [comment]
> Is this something we should be able to modify through admin?

I think this would be useful. We already do this with image/file fields in content types, although the allowed extensions for file fields are pretty restrictive by default (only .txt).

**Comment by klonos** [comment]
...besides allowing extensions to be add/removed through the UI, we should update this default list to include [Office Open XML](https://en.wikipedia.org/wiki/Office_Open_XML) format files (.docx, .docm, .pptx, .pptm, .xlsx, .xlsm).

**Comment by MrHaroldA** [comment]
+1 on the open file formats.

**Comment by Graham-72** [comment]
This could perhaps be fixed with https://github.com/Graham-72/backdrop/pull/1

**Comment by Graham-72** [comment]
I believe I still need this because my clients like to upload docx files, so I manually added it to my download of v1.3.5 today.

**Comment by Graham-72** [comment]
@klonos How can I get this considered for v1.4 ?  It is a very small but significant commit.

**Comment by klonos** [comment]
...this might help :wink: 

If either @quicksketch or @jenlampton or our newly-added core committed @serundeputy decide that there is no time for this, they can and might indeed push this back, but it is worth the try to set the milestone in order to put this in their radar.

**Comment by klonos** [comment]
@Graham-72 I see that you have your PR against your own repo. I think it would help if you also filed the PR against the official backdrop repo. Small change so you can edit the file directly here: https://github.com/backdrop/backdrop/edit/1.x/core/includes/file.inc and then scroll at the bottom of the page and fill in the "Propose file change" form. That should do it. Remember to add "Issue #1563: Add support for uploading Office Open XML file attachments (MS Office 2007+)" as the PR title (we use the standard of `Issue #[github_issue_number]: [github_issue_title]`) and then add `Fixes https://github.com/backdrop/backdrop-issues/issues/1563` as the PR description so that the PR is automatically linked to this issue here :wink:

**Comment by klonos** [comment]
...once you've done that I can review it and set the issue tag to `pr - RTBC` and that should help even more :wink:

**Comment by Graham-72** [comment]
@klonos Thanks for this. I set out to do what you suggest but immediately got this response from Github
![editing backdrop-file inc at 1 x backdrop-backdrop 2016-05-02 09-18-44](https://cloud.githubusercontent.com/assets/10559274/14950279/6ef3ba8e-1048-11e6-9c66-28315c1186d4.png)
If this means what I think it means it would still use my repo - presumably another branch.
:worried:

**Comment by klonos** [comment]
Must be a matter of permissions. Unfortunately, I cannot help with that. @quicksketch / @jenlampton ??

**Comment by jenlampton** [comment]
I think the process should be like this:
1) create a fork of backdrop
2) create a new branch on that fork
3) make whatever edits are necessary
4) create a PR back to the original backdrop repo

So @Graham-72 I think creating a new branch on your repo is a necessary step. Can you try that, and then when you create the PR change the source to backdrop/backdrop?

**Comment by Graham-72** [comment]
@jenlampton @klonos Hopefully I have got this right now. Thanks for your patience with me. I will try and get it into my head that the base fork is where I want the change to be applied, and I must get it right first time.

**Comment by jenlampton** [comment]
> and I must get it right first time.

Ha!  I wouldn't expect that of anyone. Not even myself ;)

**Comment by serundeputy** [comment]
@Graham-72 I was testing this issue and for me just putting `docx` into the file field configuration (no patch or alteration to Backdrop code) did the trick: `/admin/structure/types/manage/one/fields/field_my_file`  that is for the field and content type I have, but if you replace `one` with the machine name of your content type and `field_my_file` with the machine name of your field you should be able to add the allowed extension of `docx`

![screen shot 2016-05-02 at 5 32 39 pm](https://cloud.githubusercontent.com/assets/6763671/14968667/fec3546a-108b-11e6-857d-fa98f49825a2.png)

but some reading seems to suggest that the allowed upload types can be server specific.  I am using Apache and here is on of the lines in `/private/etc/apache2/mime.types`:

```
784 application/vnd.openxmlformats-officedocument.wordprocessingml.document docx
```

so, I would think if your server does not have a similar line this could be preventing you from uploading `docx` or possibly other file types.

Could you provide more information about your server and/or local environment where you are trying to upload `docx` files?  I am starting to believe that this is not a Backdrop issue, but more facts should lead us down the correct path.


thanks,
~Geoff

**Comment by quicksketch** [comment]
>  so, I would think if your server does not have a similar line this could be preventing you from uploading docx or possibly other file types.

Backdrop includes its own mime type list to avoid server discrepancies, and our extension checking only checks the extension itself, not the mime type, so it should be fine. I think you're right that this can be "fixed" in the UI just by manually specifying "docx" (and others) in the allowed file extension list. It's only if the field is left blank that the default list will be used.

Agreed though that the Office 2007+ extensions should be included in the default list. I would consider this a bug fix and it should be allowed any time. So if this gets in before 1.4, it should be included in the 1.3.x branch as well.

**Comment by Graham-72** [comment]
@serundeputy thanks for investigating this. My server has the necessary settings for handling docx and it was just a problem with using Backdrop, more specifically with the Views Send module which provides for file attachments but at the moment has no provision for specifying the allowed file types, so is relying on the default list.

**Comment by serundeputy** [comment]
thanks @quicksketch and @Graham-72 

So, think what is left here is to file the `PR` against backdrop/backdrop `1.x` so we can have travis run the test suite. 

The only `PR` I see is against your repo: https://github.com/Graham-72/backdrop/commit/7da18d2d207baa77824b5eae024230f7651e5f99  am I missing the real `PR`?

**Comment by Graham-72** [comment]
@serundeputy Github is telling me that that PR is for basefork backdrop/backdrop and headfork Graham-72/backdrop - is that not right?

**Comment by serundeputy** [comment]
@Graham-72 that sounds right, but I don't see it here: https://github.com/backdrop/backdrop/pulls ... maybe we can find a common time to screenshare?

**Comment by Graham-72** [comment]
@serundeputy Well, I thought I had done all the right things, and I thought Github had accepted my PR, but I am now totally confused. Also I am away on holiday for the rest of this week so will get back to it next week. Thanks for offer of help.

**Comment by Graham-72** [comment]
@serundeputy I think I found what to do but in the process perhaps created a redundant commit.

**Comment by serundeputy** [comment]
Thanks @Graham-72 
Everything is looking good now; and all tests are passing!

@quicksketch there is no test for the new file extensions (`docx` for example), but are current tests only test for `.txt` and `.png`.  The files in `simpletest/files` include a handful of extensions like `.html`, `.txt`, `.png`, but no `.ppt`, `.docx` or even `.doc`.

I am fine with merging this as is without additional tests, but just want confirmation that @quicksketch  agrees.

**Comment by quicksketch** [comment]
Yep, I think this is fine as-is. :+1:

**Comment by serundeputy** [comment]
Thanks @Graham-72 this is merged into `1.x` and `1.3.x` and will ship w/ `1.3.6`.
