### ISSUE TITLE
Prevent Travis CI (or other tests) from reporting via update module

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1566]
I'm going to take a look at update module, and see if we can disable it during (all) tests.

**Comment by quicksketch** [comment]
The first PR at https://github.com/backdrop/backdrop/issues/1227 looks great! I adjusted it slightly to make it testable, and added tests. New PR at https://github.com/backdrop/backdrop/pull/1280.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1280. Thanks!

**Comment by quicksketch** [comment]
A note on removing Travis CI numbers from our current database on BackdropCMS.org. I checked for IP address blocks belonging to Travis, and this seems to get them all without any false positives:

```
DELETE FROM project_usage_raw WHERE hostname LIKE '173.247.%' OR hostname LIKE '199.182.%' OR hostname LIKE '199.91.%';
```

Obviously those are some large IP blocks, but I couldn't find any sites that used those blocks. You can get a general list of how many sites are running on each IP address by running the below query.

```
mysql> select hostname, COUNT(DISTINCT site_key) as count FROM project_usage_raw GROUP BY hostname ORDER BY count DESC;
+-----------------+-------+
| hostname        | count |
+-----------------+-------+
| 173.247.96.135  | 13146 |
| 199.182.120.15  | 12568 |
| 199.182.120.13  |  7431 |
| 173.247.96.147  |  7269 |
| 173.247.96.44   |   632 |
| 173.247.96.55   |   632 |
| 199.91.171.26   |   589 |
| 173.247.98.198  |   568 |
| 199.91.170.132  |   548 |
| 173.247.96.145  |   547 |
| 173.247.98.197  |   505 |
| 173.247.96.179  |   463 |
| 173.247.98.234  |   463 |
| 173.247.96.43   |   463 |
| 199.91.170.50   |   442 |
| 199.91.170.69   |   422 |
| 173.247.96.163  |   421 |
| 173.247.96.10   |   421 |
| 199.182.122.201 |   421 |
| 173.247.98.202  |   400 |
| 173.247.98.204  |   400 |
| 173.247.98.206  |   400 |
| 173.247.98.200  |   381 |
| 173.247.98.208  |   379 |
| 173.247.98.196  |   359 |
| 173.247.98.199  |   314 |
| 173.247.98.205  |   148 |
| 199.182.121.244 |    85 |
...
```


For the most part, there is only be one site per IP address, but multiple sites are common from one IP (e.g. Dreamhost, Pantheon sites, other shared hosts, Localhost environments, etc). However, you can see that a small set of IPs dwarf the others, those coming from Travis.
