### ISSUE TITLE
"Fatal error: Unsupported operand types in admin_bar.inc on line 68" when all Admin bar components unchecked.

### ISSUE THREAD

**Issue by xmacinfo** [backdrop/backdrop-issues#1569]
Backdrop 1.3.2

To test the Admin Bar components display, I unchecked all components and was shown a WSOD.  
/admin/config/administration/admin-bar

The config file “admin_bar.settings.json” displayed: 

``` json
{
    "_config_name": "admin_bar.settings",
    "margin_top": 1,
    "position_fixed": 1,
    "components": []
}
```

When I fixed that file to add the default components, the site came back with that remaining error message:

_Notice : Undefined index: menu dans admin_bar_output() (ligne 68 dans /home/xmacinfo/public_html/www.typofute/core/modules/admin_bar/admin_bar.inc)._

Please add some validation to the admin form to prevent saving the configuration when there are no component selected.

**Comment by klonos** [comment]
I confirmed this issue on 1.4.2, although instead of a WSOD, I got this fatal:

```
Fatal error: Unsupported operand types in
C:\www\core\modules\admin_bar\admin_bar.inc on line 68

Call Stack
#  Time    Memory   Function                            Location
1  0.0004  244560   {main}( )                           ...\index.php:0
2  0.0767  1457032  menu_execute_active_handler( )      ...\index.php:21
3  0.1851  2470872  backdrop_deliver_page( )            ...\menu.inc:554
4  0.1853  2476936  backdrop_deliver_html_page( )       ...\common.inc:2798
5  0.1859  2477976  backdrop_render_page( )             ...\common.inc:2899
6  0.1859  2488392  theme( )                            ...\common.inc:6226
7  0.1889  2501136  admin_bar_preprocess_page( )        ...\theme.inc:1110
8  0.1916  2508992  admin_bar_output( )                 ...\admin_bar.module:188
```

**Comment by klonos** [comment]
...if anyone is trying to recover out of this situation, here are the default values that you need to put in your `/files/config_[whatever]/active/admin_bar.settings.json` file:

```
{
    "_config_name": "admin_bar.settings",
    "margin_top": 1,
    "position_fixed": 0,
    "components": [
        "admin_bar.icon",
        "admin_bar.menu",
        "admin_bar.search",
        "admin_bar.users",
        "admin_bar.account"
    ]
}
```

Save the file, refresh page, clear caches just to be sure.

**Comment by klonos** [comment]
I am going to go ahead and close this old issue. I have tried the following in a fresh 1.11.2 installation:

1. Unticked all checkboxes under `/admin/config/administration/admin-bar` -> no WSOD 👍 
2. Used the breadcrumb to navigate to `/admin/config/development/performance`.
3. Cleared caches -> no errors 👍 
4. Navigated to the front page -> no errors 👍 
5. Navigated to `/admin/reports/dblog` -> no errors logged 👍 
6. Back to `/admin/config/administration/admin-bar`, I enabled all checkboxes unticked in step 1 above -> no errors 👍 
7. Cleared caches -> no errors 👍 
8. Checked the log -> no errors 👍
