### ISSUE TITLE
Page problem https://backdropcms.org/news/backdrop-1-3-0-released

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1570]
Sorry I do not know where and how to publish it in the right place so I do it here:

This page has a problem:
https://backdropcms.org/news/backdrop-1-3-0-released

My computer (Windows 7, Chrome) has a problem (glitch etc) with this page.

Additionally in my phone-tablet (Android 4.4?) in several time of viewing the page it turns me to this:
![screenshot_2016-01-23-22-50-48](https://cloud.githubusercontent.com/assets/13515302/12532459/d18e06fc-c225-11e5-9309-9d72db719f12.jpeg)

**Comment by dboulet** [comment]
@bd0bd Issues specific to backdropcms.org can be opened here: https://github.com/backdrop-ops/backdropcms.org/issues

**Comment by quicksketch** [comment]
Is this still happening? I haven't been able to reproduce it.

**Comment by bd0bd** [comment]
I am sorry for my long silence.
Yes, still it is.
It happens in about 30 seconds after viewing the page.
Yes, I can see the page but then it crashes in Android 4.4, Huawei Mediapad X1.
![screenshot](https://cloud.githubusercontent.com/assets/13515302/13342607/1dc33dc2-dc65-11e5-8841-adfb8b9c41b1.jpeg)

**Comment by bd0bd** [comment]
And this page **An approach to theming a site in Backdrop** disappeared https://backdropcms.org/news/approach-theming-site-backdrop

**Comment by Graham-72** [comment]
At the moment I can only see the full article it if I am logged in to backdropcms.org

**Comment by klonos** [comment]
I'm able to see both articles just fine in latest Chrome on Windows 8.1 x64 logged out and left both pages on for a couple of minutes. No crash or anything.

**Comment by bd0bd** [comment]
>No crash or anything

It crashes only this article https://backdropcms.org/news/backdrop-1-3-0-released in my Android 4.4, Huawei Mediapad X1. May be somebody can try it view in Android.

**Comment by Graham-72** [comment]
> At the moment I can only see the full article it if I am logged in to backdropcms.org

It is OK now when not logged in. Viewing with Firefox on Windows 7.

**Comment by findlabnet** [comment]
OK without log in. 
Linux 64-bit:
Firefox 44,
SeaMonkey 2.40 (Firefox 43.0),
Google Chrome 48.0.2564.116 .

**Comment by BWPanda** [comment]
Closing this old issue.
