### ISSUE TITLE
How to provide responsive drop-down menus ? type - answer

### ISSUE THREAD

**Issue by gifad** [backdrop/backdrop-issues#1577]
[Edit:] The original issue title was "Support request about themes/layouts/blocks etc..."

This is a follow-up to #1457 
> Provide responsive drop-down menus out of the box.

I understand that "out of the box" is not for today, and wish to implement a "responsive drop-down menu", preferably via a Bartik sub-theme.
I just need a very limited alteration of the output code, that can be expressed, in `git diff`language, by : 
```
 <div class="block block-system-main-menu block-menu">
   <div class="block-content">
+    <nav id="main-menu"  role="navigation">
+      <a class="nav-toggle" href="#">Navigation</a>
+      <div class="menu-navigation-container">
         <ul class="menu">
           <li class="first leaf active">
           ...
         </ul>
+      </div>
+    </nav>
   </div>
 </div>
```
(the rest is only additional js/css)
I'm not good at php debugging, and could not find where those five lines could be added;
Which function(s) / template(s) should be overriden ?

**Comment by gifad** [comment]
First answer, the code is issued in `core/modules/layout/plugins/renderers/layout_renderer_standard.inc`.
if I insert in `function renderBlock($block)` the following : 
```
if ($block->delta == 'main-menu') {
  $content['#prefix'] = '<nav id="my-main-menu">';
  $content['#suffix'] = '</nav><!-- my-main-menu -->';
}
```
I get the expected result.

Do I have to create a `class LayoutRendererResponsiveMenus extends LayoutRendererStandard` ?
How to tell Backdrop to use it ?

I'm afraid the answers are "learn to develop for Drupal 8", so this issue may be marked as critical...

**Comment by gifad** [comment]
To stay on the positive edge, is this patch acceptable for Backdrop 1.4 ?
```
diff --git a/core/modules/layout/plugins/renderers/layout_renderer_standard.inc b/core/modules/layout/plugins/renderers/layout_rende
index a4c5934..0682cc8 100644
--- a/core/modules/layout/plugins/renderers/layout_renderer_standard.inc
+++ b/core/modules/layout/plugins/renderers/layout_renderer_standard.inc
@@ -461,6 +461,17 @@ class LayoutRendererStandard {
         $content['#contextual_links']['layout'] = array('admin/structure/layouts/manage/' . $this->layout->name . '/modal', array($
       }
 
+      if ($block->delta == 'main-menu') {
+        $content['#prefix'] = '<nav id="main-menu"  role="navigation">
+<a class="nav-toggle" href="#">Navigation</a>
+<div class="menu-navigation-container">
+';
+        $content['#suffix'] = '</div>
+<div class="clear"></div>
+</nav><!-- end main-menu -->
+';
+      }
+
       $title = '';
       if ($block->settings['title_display'] !== LAYOUT_TITLE_NONE) {
         $title = $block->getTitle();
```
AFAIK, it would not disturb anything in the standard, non responsive, Backdrop (smiley)...
Is it worth to issue a pull request ?

**Comment by gifad** [comment]
Updated my demo site http://p1347.phpnet.org/backdrop/l/3rgz8UIEd0Vd/ if you mind check it out…

**Comment by quicksketch** [comment]
> and wish to implement a "responsive drop-down menu", preferably via a Bartik sub-theme.

To change the markup for a menu, you can override `theme_menu_tree()` in your theme. The Bartik theme already includes an override in its own `template.php` file. This is the same approach you would use in Drupal 7.

So the full solution for you would be to copy/paste this into your sub-theme's template.php file, and replace `[name_of_your_theme]`. You'll also need to clear your Backdrop caches after adding it:

```
/**
 * Overrides theme_menu_tree().
 */
function [name_of_your_theme]_menu_tree($variables) {
  $output = '';
  $output .= '<nav id="main-menu"  role="navigation">';
  $output .= '<a class="nav-toggle" href="#">Navigation</a>';
  $output .= '<div class="menu-navigation-container">'
  $output .=  '<ul class="menu clearfix">' . $variables['tree'] . '</ul>';
  $output .= '</div></nav>';
  return $output;
}
```

As this code is already intended to be overridden in themes, I don't think a core patch is necessary in this situation.

**Comment by gifad** [comment]
Thaks for the reply, @quicksketch, but this solution, which I tried first, does not work : 
1. theme_menu_tree is called for all menus, not only main-menu
2. theme_menu_tree is called for all and every root node of the tree, recursively bottom to top
and I need the patch only for the top node.
FYI, the $variables contains information strictly limited to the current sub-tree
I could live with that for a given site (testing that there is a link to t('Home') -> base_path(), but that's too bad...
I let you change the issue title again.

**Comment by gifad** [comment]
Since your solution does not work, I first tried the Drupal 8 way : 
- create a `class LayoutRendererResponsiveMenus extends LayoutRendererStandard` (easy, but I had to duplicate the whole render function)
- let backdrop use it (a bit tricky, since there is no alter available : I had to define my class as `$info['standard']` in the `hook_layout_renderer_info()`, and give me a weight > 60 to overwrite the standard one)

Not clean at all, so I reverted to the Drupal 7 way : 
```
/**
 * Preprocess menu_link to identify top level of main-menu
 */
function bartik_preprocess_menu_link(&$variables) {
  static $count = 0;
  if ($variables['theme_hook_original'] == 'menu_link__main_menu') {
    if ($count++ == 0) {
      $variables['element']['#attributes']['class'][] = 'top-level-main-menu';
    }
  }
}

/**
 * Theme main-menu to make it responsive easy
 */
function bartik_menu_tree__main_menu(&$variables) {
//return '<ul class="menu clearfix">' . $variables['tree'] . '</ul>';
  return (strpos($variables['tree'], 'top-level-main-menu') !== FALSE) ?
'<nav id="main-menu" class="media-kit-custom-menu" role="navigation">
<a class="nav-toggle" href="#">Navigation</a>
<div class="menu-navigation-container">
<ul class="menu top-level-main-menu clearfix">
' . $variables['tree'] . '
</ul>
</div>
<div class="clear"></div>
</nav><!-- end main-menu -->
'
 : '
<ul class="menu clearfix">
' . $variables['tree'] . '
</ul>
';
}
```
Note that it's not necessary to use a subtheme, you can put this code in any module...
I can publish the associated js and css if someone is interested, but you can easily grab it with firebug at http://p1347.phpnet.org/backdrop/l/3rgz8UIEd0Vd/

Enjoy !

**Comment by biolithic** [comment]
Nice!

**Comment by quicksketch** [comment]
Closing this issue as a question. I'm glad you figured it out @gifad!
