### ISSUE TITLE
Notice: Undefined index: identifier in views_plugin_display->is_identifier_unique()

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1578]
…(line 2743 of /home/www/backdrop/core/modules/views/plugins/views_plugin_display.inc).
I have this annoying notice from time to time, when working on views filters.
It's not specific to backdrop, I've seen it since drupal 7.0
AFAIK, no one has found the cause, but it can easyly be avoided by this patch : 

```
diff --git a/core/modules/views/plugins/views_plugin_display.inc b/core/modules/views/plugins/views_plugin_display.inc
index 07af046..341efd3 100755
--- a/core/modules/views/plugins/views_plugin_display.inc
+++ b/core/modules/views/plugins/views_plugin_display.inc
@@ -2735,12 +2735,12 @@ class views_plugin_display extends views_plugin {
       foreach ($this->get_handlers($type) as $key => $handler) {
         if ($handler->can_expose() && $handler->is_exposed()) {
           if ($handler->is_a_group()) {
-            if ($id != $key && $identifier == $handler->options['group_info']['identifier']) {
+            if ($id != $key && isset($handler->options['group_info']['identifier']) && $identifier == $handler->options['group_info']['identifier']) {
               return FALSE;
             }
           }
           else {
-            if ($id != $key && $identifier == $handler->options['expose']['identifier']) {
+            if ($id != $key && isset($handler->options['expose']['identifier']) && $identifier == $handler->options['expose']['identifier']) {
               return FALSE;
             }
           }
```

just add test for isset(), and return accordingly.

do you need a PR for this ?

---
outdated (?) PR: https://github.com/backdrop/backdrop/pull/1228
PR by @klonos: https://github.com/backdrop/backdrop/pull/2890

**Comment by quicksketch** [comment]
Thanks @gifad! I see you also posted the patch to the Drupal issue at https://www.drupal.org/node/1456836.

Yes a PR would be appreciated. :smile:

**Comment by gifad** [comment]
> Yes a PR would be appreciated. :smile:

I have a large PR pending from my backdrop repo, and I can't create a new fork...
How can I prepare a new PR ?
I suppose that this is done via branches, but isn't it too late ?
Can I completely start  over, and keep backdrop/backdrop#1226 alive ?

**Comment by serundeputy** [comment]
Hi @gifad 

> I suppose that this is done via branches, but isn't it too late ?

here is some documentation that I found really helpful.
https://backdropcms.org/develop/pull-requests

you also want to have your for track the backdrop/backdrop canonical repo:
http://serundrop.staffordtavern.com/backdropcms-core-repo

hope that helps.
~Geoff

**Comment by gifad** [comment]
Thanks a lot @serundeputy I'll study that; at least the written part : I can approximately read english, but Nate's youtube words are complete garbage to me...

**Comment by klonos** [comment]
> ...but Nate's youtube words are complete garbage to me

I understand that there is no bad intention here and it is a "lost in translation" case, but LOL :smile:

**Comment by gifad** [comment]
Issued PR at https://github.com/backdrop/backdrop/pull/1228

[Sorry for the word garbage : I know it only thru "garbage collector", which just means useless, or, in this case, just incomprehensible]

**Comment by Graham-72** [comment]
I was thinking about how we might express it and found this in Google
> BRITISHinformal
language that is impossible to understand; gibberish.
"instructions written in double Dutch"

but this is not really suitable for a multi-national project :smile:

**Comment by klonos** [comment]
This is part of #3723, which is part of the #3685 META. I have reviewed the PR provided here, and it seems to be adding another `isset()` check, which is not what's been committed in Views 7.x.

**Comment by quicksketch** [comment]
Sad to see that this lingered for over 3 years, but at least we finally got it in. I've merged https://github.com/backdrop/backdrop/pull/1228 into 1.x and 1.14.x. Thanks @gifad (who I think is now renamed @madeby?), @klonos, and @jenlampton.
