### ISSUE TITLE
Review and update README.md before launch

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#158]
Before we launch 1.0 we should review the README.md file to make sure all the information is accurate and up to date.

Also related: https://github.com/backdrop/backdrop-issues/issues/266

**Comment by jenlampton** [comment]
Filed a new PR with these suggestions, thanks @klonos for the thorough review!

**Comment by quicksketch** [comment]
Thanks! The changes all look good to me! I didn't know it was "GitHub". :P Now I do. :)
