### ISSUE TITLE
RSS feed icon assembled and cached, never printed.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1582]
I noticed that while adding an RSS feed display to a view, the RSS icon and link never appears on the page. I think this might be a residual left-over from removing the `<?php print $feed_icon; ?>` from the page template when we added layouts. 

In Drupal 7, the feed icons were retrieved in `template_preprocess_page` when the variable `feed_icons` was prepared: `$variables['feed_icons'] = drupal_get_feeds();`

In Backdrop, we removed this variable from the page template and preprocessor. Now there is nothing that calls `backdrop_get_feeds` (except the Drupal BC layer).

If we want to solve this problem by placing a block that contains the RSS icon, we may need to add that block as part of system module.

``` php
    case 'rss':
      $block['subject'] = NULL;
      $block['content'] = backdrop_get_feeds();
      break;
```

Additionally, we'll then have to explain what this generic RSS block is, and how it differs from the 'Syndicate' block. We may even want to replace the syndicate block (from node module) with this RSS feed icon block, so that we don't need to worry about the UX problem of having two blocks that add RSS links/icons. 

If that's what we end up doing, we could possibly update the Syndicate block in node module in Backdrop 1.x and move it to system module in 2.x.

---
 PR by @docwilmot at https://github.com/backdrop/backdrop/pull/2232

**Comment by docwilmot** [comment]
https://forum.backdropcms.org/forum/rss-feeding-visitors-not-available

**Comment by docwilmot** [comment]
Adding a milestone to this, since its showed up in the Forums. Right now we have no way of showing an icon on a Views feed that links to the RSS for that feed. Syndicate only shows nodes promoted to front page.

**Comment by jenlampton** [comment]
We'd removed `$feed_icon` from the page/layout template because we also had a block for it. If the `Syndicate` block only prints the feed icon for /node (and presumably taxonomy/term pages?) we should fix that. It might also help if we changed the name and description of the block to be more descriptive :)

**Comment by jenlampton** [comment]
I'm on board with this approach (adding a settings form to the syndicate block from node module) but I think we need some cleanup on the labels for options available. I'm finding these a little unclear.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/2232 looks good to me from the tech side. We need to add tests for this functionality so we don't accidentally break it again in the future.

**Comment by docwilmot** [comment]
Done

**Comment by jenlampton** [comment]
And..

> We need to add tests for this functionality so we don't accidentally break it again in the future.

**Comment by jenlampton** [comment]
Reviewing now... :)

**Comment by jenlampton** [comment]
The PR looks good to me. Tested, and I can see the icon showing, and linking to the appropriate RSS feed. @docwilmot I pushed a single commit to your branch that has the text change recommended by @opi. Feel free to revert that commit if you don't like it. 

It would be best to get another review / RTBC on this issue since I made the last change.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2232 into 1.x and 1.11.x. Thanks @docwilmot, @jenlampton, and @opi!
