### ISSUE TITLE
CKEditor - need to be able to add a link to an image.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1586]
.Please can we add this requirement to  [META] CKEditor/Rich text editor followups #1087.

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1870

**Comment by klonos** [comment]
Done :wink:

**Comment by serundeputy** [comment]
I can see that `core/modules/filter/filter.pages.inc` contains the form in the modal to add an image in a ckeditor enabled field.

I can add form fields to it, but i can not determine how it is putting the markup into the field it does not appear to happen in the submit handler.

So if someone knows how that happens take this and run or report back here and I'll dig back into it.

**Comment by laryn** [comment]
@serundeputy, I'm stabbing in the dark here admittedly, but since the link icon is active until an image is clicked on, I was searching through the Javascript to try to find a place where the button is explicitly disabled when an image was selected. Do these lines have any bearing here?

https://github.com/backdrop/backdrop/blob/1.x/core/modules/ckeditor/js/plugins/backdropimage/plugin.js#L37-L39

https://github.com/backdrop/backdrop/blob/1.x/core/modules/ckeditor/js/plugins/backdropimage/plugin.js#L238-L245

**Comment by quicksketch** [comment]
I've added a PR at https://github.com/backdrop/backdrop/pull/1870 that includes this ability. There have been a few issues related to this in the Drupal queue, I've combined them all in the latest PR including:

- [Issue #2626106](https://drupal.org/node/2626106) by Wim Leers, gceja, thpoul: The image button does not work unless width+height attributes are allowed, even though those are optional
- [Issue #2615852](https://drupal.org/node/2615852) by Wim Leers: Clean-up to our plugins that CKEditor >=4.5.5 enables
- [Issue #2268941](https://drupal.org/node/2268941) by Wim Leers, thpoul, yched, mlewand: Removing caption from a previously captioned image fails to remove the caption-related classes

I also found a new bug in the Drupal implementation of linking an image. I've made an issue for that and I'll be submitting our fix over there as well: [Issue #2876094 Linking an image creates an empty paragraph tag in CKEditor](https://www.drupal.org/node/2876094).

**Comment by Dinornis** [comment]
I am unable to insert image on the PR test site.  The Image button is not responding.

**Comment by quicksketch** [comment]
> I am unable to insert image on the PR test site. The Image button is not responding.

Thanks for testing @dinarcon! You are right! I broke the image button. :stuck_out_tongue_closed_eyes: 

I pushed an update and there is now a new demo site. Could you try that one?

**Comment by Dinornis** [comment]
Sorry, now the `Insert image` form comes up, I am able to upload an image but when I click the `Insert` button nothing happens.

**Comment by olafgrabienski** [comment]
> now the Insert image form comes up, I am able to upload an image but when I click the `Insert` button nothing happens.


Same here. (Chrome on Mac OS X)

**Comment by quicksketch** [comment]
Thanks for testing again. CKEditor can be finicky. I've updated the PR again and this time I think I've got everything working: https://github.com/backdrop/backdrop/pull/1870

**Comment by olafgrabienski** [comment]
Hm, still no luck, same as before :-/

**Comment by quicksketch** [comment]
That's strange. What browser/OS are you using? It appears to work fine for me in Firefox and Chrome in Ubuntu.

**Comment by olafgrabienski** [comment]
Hey, really strange, don't know what happened in the meantime, but not it works perfectly! See the test page http://1870.backdrop.backdrop.qa.backdropcms.org/about.

(Mac OS X + Chrome)

**Comment by jenlampton** [comment]
I [took this for a spin](http://1870.backdrop.backdrop.qa.backdropcms.org/posts/test-jen) and it works great!  Image linked up nicely, image dialog works as expected before and after, and link dialog works as expected.
 RTBC from me :)

**Comment by quicksketch** [comment]
> Hey, really strange, don't know what happened in the meantime, but now it works perfectly!

@jenlampton pointed out to me that even if I close/reopen the PR to get a new sandbox, the URL is the same, so you were probably getting a cached version of the JS file within CKEditor (which has its own JS loader). So it was probably a browser-cache issue.

This had been brought up as a bug previously, and being self-contained in CKEditor and unlikely to break outside functionality, I'm going to merge this into 1.x for 1.7.0.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1870 into 1.x for 1.7.0.
