### ISSUE TITLE
Taxonomy views filters do not work grouped

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1589]
I'm trying to implement a poor man's faceted search with views, but this does not work at all.
I'm getting tired to spend hours and nights to debug "core" code that has been tested only by robots.
I had first to fix : 
`$tree = taxonomy_get_tree($vocabulary->vid);`
(line 129 of core/modules/taxonomy/views/views_handler_filter_term_node_tid.inc).
This code has been ported to backdrop only in the cosmetic ("branding") aspect...

**Comment by gifad** [comment]
Technically, the sql generatid for `field_data_field_tags.field_tags_tid = '2'` comes from an array_keys() of the array of selectable values;
This array is expected to be keyed by term->tid, but it is not (we get the numeric 1 based indices, with '0' meaning "any")

**Comment by gifad** [comment]
I did not find the bug, but just a fix to make my view working : 
Add a override in `core/modules/taxonomy/views/views_handler_filter_term_node_tid.inc`
`class views_handler_filter_term_node_tid extends views_handler_filter_many_to_one`
…
```
  public function query() {
    if ($this->options['is_grouped']) {
      if ($this->options['group_info']['optional']) {
        foreach($this->value as $key => $value) {
          if ($value != 0) {
            $this->value[$key] = array_keys(($this->options['group_info']['group_items'][$key]['value']));
          }
        }
      }
      else {
        $key = $this->value[0];
        $this->value = array_keys(($this->options['group_info']['group_items'][$key]['value']));
      }
    }
    parent::query();
  }
```
Any one with some knowledge of the views internal can tell where `$this->value` gets populated ?

**Comment by BWPanda** [comment]
Closing old issue.
