### ISSUE TITLE
The configuration "block.custom.1" is not owned by any module.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1594]
It would appear as though our new config-based blocks can't be imported.

I get the following error when attempting to import a complete site export from 1.3.2:

```
Configuration sync failed. The following errors were reported:

    The configuration "block.custom.1" is not owned by any module. Try enabling the module that provides this configuration, then importing again.
```

And yes the Custom block module is enabled.

**Comment by BWPanda** [comment]
@jenlampton Are you still having this issue?

**Comment by jenlampton** [comment]
I'm not sure, I'll need to retest. Assigning to myself.

**Comment by jenlampton** [comment]
No, my custom blocks import now. Closing.
