### ISSUE TITLE
CKEditor links do not handle aliases

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1595]
If the user links a text fragment to "node/12", the resulting link has `href="node/12"`, which of course does not work.
The path module (URL aliases) is not to be suspected : elements rendered with the `l()` function are correctly expanded.
But does backdroplink take care of rendering anything ?

**Comment by BWPanda** [comment]
I just tested this and adding a link of `node/5` in CKEditor results in `href="/node/5"` which does work. So this has likely been fixed since the OP. Closing.

**Comment by indigoxela** [comment]
This [has been fixed](https://github.com/backdrop/backdrop-issues/issues/3083), but there's a [problem](https://github.com/backdrop/backdrop-issues/issues/4647) if the Link module is disabled.
