### ISSUE TITLE
Upgrade from Drupal 7 to Backdrop 1.3.2, Error after update.php

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1596]
Migration looks more or less ok, but I
got following Error in the log:
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes: ALTER TABLE {taxonomy_term_data} ADD INDEX `vocabulary_name` (`vocabulary`, `name`); Array ( ) in db_add_index() (Zeile 2947 von /home/www/backdrop/core/includes/database/database.inc).

**Comment by dboulet** [comment]
Hi @vtad, looks like this might be the same issue that @jenlampton reported in https://github.com/backdrop/backdrop-issues/issues/1588.

**Comment by vtad** [comment]
Changing the table to innodb solve the problem, thx.

**Comment by ericfg** [comment]
I just ran into this problem and was glad someone had figured out the fix. 
 ALTER TABLE taxonomy_term_data ENGINE = InnoDB; 
worked for me too
