### ISSUE TITLE
Support of responsive images ?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1597]
Backdrop claims to be responsive out of the box, but I could not find track of the support of the html5 `picture` element.
It's not even possible to specify the width of an image as a percentage of its container element...

Is there any plan for these features in core, or is it the contrib territory ?

**Comment by BWPanda** [comment]
I believe `picture` element support is in https://github.com/backdrop-contrib/picture, and you can define responsive images with 100% parent width using CSS.

If you'd like to see `picture` support in core, I'd suggest first getting it stable and ready in contrib, then we can open an issue for merging into core. Closing this issue in the meantime though.
