### ISSUE TITLE
Main column is not full width when sidebar is empty in two column layout

### ISSUE THREAD

**Issue by jeffam** [backdrop/backdrop-issues#1599]
I was just trying out v1.3.2 with the default two column layout. When there is no content in the sidebar, the main content column is still only 70% of the container width, but I would expect it to be 100%.

## Steps to reproduce

- Install 1.3.2
- Add some sample posts and promote them to the front page
- Stay logged in
- Visit front page

## What I see

- The main column remains at 70% width, and the space where the sidebar would be is empty. Since I'm logged in, the user login form that would normally appear in the sidebar is hidden, so there are no blocks in the sidebar.

## What I expected

I expected the main content column to expand to the full width of the page/container.

Pull request to come...

**Comment by docwilmot** [comment]
Apparently this is by design. See https://github.com/backdrop/backdrop-issues/issues/596. 

I made https://backdropcms.org/project/two_column_flexible because of that.

**Comment by jeffam** [comment]
@docwilmot - Thanks for the background info. I really did try to search for past issues, but apparently not well enough!

I can live with it being by design, and it's easy enough to use your flexible layout or create a custom one.
