### ISSUE TITLE
Text color in header is white causing text in text boxes to be 'hidden' like search block.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1605]
Text color in header is white causing text in text boxes to be 'hidden' like search block.

![screen shot 2016-02-06 at 8 47 10 am](https://cloud.githubusercontent.com/assets/6763671/12866969/ae77956e-ccae-11e5-8261-86aa52c8e6a7.png)

**Comment by quicksketch** [comment]
Small item of feedback in the PR: https://github.com/backdrop/backdrop/pull/1255#discussion-diff-53733707

Good point all in all, let's mark this as a bug.

**Comment by quicksketch** [comment]
Thanks merged in https://github.com/backdrop/backdrop/pull/1255!
