### ISSUE TITLE
Nate's Heil Microphone

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1607]
Sorry for off top :-)
Nate, please, may I ask you - what is the model of your microphone here?:
https://www.youtube.com/watch?list=PLE6f8hiqhhJkxM_4tCgz0pkRMuxanGP1J&v=lrPq_2uidU4
Do you use this mic boom:?
http://www.heilsound.com/amateur/products/booms-and-hardware/sb-2

I need to buy a microphone for a lawyer, who would communicate via Skype, make webinars, and record videos for media-advertising purposes.

May be something like Wes's microphone. Wes, may I ask you, what is this one?:

![wes](https://cloud.githubusercontent.com/assets/13515302/12928394/0ba944ca-cf8f-11e5-875f-e3615b3968ee.png)

Thank you!

**Comment by docwilmot** [comment]
Which reminds me, we need a discussion forum.

**Comment by BWPanda** [comment]
We have one now :-)
