### ISSUE TITLE
SA-CORE-2014-001 - Multiple vulnerabilities

### ISSUE THREAD

**Issue by greggles** [backdrop/backdrop-issues#161]
## Security fixes from [Drupal 7.26](https://drupal.org/drupal-7.26-release-notes)

The taxonomy one is probably still relevant.
The FormAPI one is only a problem depending on contributed and custom modules, so...your call what to do there.
### Access bypass (Taxonomy module - Moderately critical)

The Taxonomy module provides various listing pages which display content tagged with a particular taxonomy term. Custom or contributed modules may also provide similar lists. Under certain circumstances, unpublished content can appear on these pages and will be visible to users who should not have permission to see it.

This vulnerability is mitigated by the fact that it only occurs on Drupal 7 sites which upgraded from Drupal 6 or earlier.
### Security hardening (Form API - Not critical)

The form API provides a method for developers to submit forms programmatically using the function drupal_form_submit(). During programmatic form submissions, all access checks are deliberately bypassed, and any form element may be submitted regardless of the current user's access level.

This is normal and expected behavior for most uses of programmatic form submissions; however, there are cases where custom or contributed code may need to send data provided by the current (untrusted) user to drupal_form_submit() and therefore need to respect access control on the form.

To facilitate this, a new, optional $form_state['programmed_bypass_access_check'] element has been added to the Drupal 7 form API. If this is provided and set to FALSE, drupal_form_submit() will perform the normal form access checks against the current user while submitting the form, rather than bypassing them.

This change does not fix a security issue in Drupal core itself, but rather provides a method for custom or contributed code to fix security issues that would be difficult or impossible to fix otherwise.

For reference, here is the [notice on drupal.org](https://drupal.org/SA-CORE-2014-001)

**Comment by quicksketch** [comment]
Double-checked:

- [x] Access bypass (Taxonomy module - Moderately critical) (does not apply to us)
- [x] Security hardening (Form API - Not critical)
