### ISSUE TITLE
[UX] 'Auto Menu Settings' in core and add Pages to the main menu by default

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1610]
### Weekly update (19th Dec)

https://github.com/backdrop/backdrop/pull/2999 is RTBC, but more feedback/wording changes requested...

----

Drupal has long had this user-nightmare of lost pages. You made one, now where did it go? Yes, the experienced user knows about the content orphanage where all content is listed, but to a new user losing these pages can be traumatic. Backdrop now has this problem too.

If we placed basic pages into the primary navigation menu by default, then first-time users would be able to find their recently created content without needing to visit the content orphanage.

Experienced users could disable this behavior, or simply move pages on a case-by-case basis out of this menu.

## Proposed solution

* On the Page node form, check the box for "create menu item" by default.
* Add 2 per-content type settings: 1) create menu item by default, and 2) which menu.

---

Advocate for this issue: @BWPanda 

----

Original PR by @BWPanda: ~https://github.com/backdrop/backdrop/pull/2903~
Alternate PR by @jenlampton: ~https://github.com/backdrop/backdrop/pull/2951~
New PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2999

**Comment by pepperstreet** [comment]
Hello Jen, sounds good for a "page" content type. As long as it can be disabled in type's menu settings. 

What about the "Parent item" setting? Would it make sense to set a default, too? For instance I have a main menu which consists of different content types. The root or a certain parent-item is for general infos, another one for services, projects etc. This would require to add the new page to one of these parent-items. If there is a correct pre-selection, the user would not have to think about it. Possible?

---

BTW, may I ask a related question in this topic? 
I know this "add-to-menu" option from Drupal, but I always wondered how it might be used in a **multi-language** website. For instance a smaller product catalog. Let's say a client wants a tree-like menu structure for direct access to each product. Over time, only some products might be added or removed. This part should be very simple and easy for the end-user.
Does it make sense to create and use this auto-menu feature at all? Or is it better to create something like a views-block, maybe grouped by taxonomy terms? 

I guess, the "auto-add-to-menu" feature would require a duplicate menu structure for each language, right? As far as I can see, I would have to select this menu in the type settings. Or do I miss something...

**Comment by gifad** [comment]
To avoid loosing pages, there is a good technique, named binding.
And there is a module for that, named `book` (it provides "menu links")
Just my 2 cents…

**Comment by BWPanda** [comment]
Sounds like this is basically a request to have [Auto Menu Settings
](https://github.com/backdrop-contrib/auto_menu_settings) in core :wink: I agree, this would be a very handy inclusion to core.

Here's what it could give you on the content type form:
![image](https://user-images.githubusercontent.com/2385329/64454671-3c133480-d0f4-11e9-985e-c7aa8975c424.png)

And here's what the node form would look like afterwards:
![image](https://user-images.githubusercontent.com/2385329/64454807-94e2cd00-d0f4-11e9-8068-496cd39beb50.png)

**Comment by jenlampton** [comment]
Auto menu settings looks nice, but I don't know that we need *all* that functionality in core. All I was recommending was to check the box for "create menu item" by default on pages, and maybe add 2 per-content type settings: 1) create menu item by default, and 2) which menu.

**Comment by BWPanda** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/2903) that:

- Adds the ability to set the default value of a node's `Provide a menu link` per content type.
- Adds the ability to set the default value of a node's `Menu link title` per content type.
- Add the ability to use tokens in a node's `Menu link title`

Not sure if it's fully working yet as I thought I had some issues when building it, but maybe my sandbox site was messed up. In any case, testing and feedback welcome!

**Comment by BWPanda** [comment]
I'd like to be an [advocate](https://backdropcms.org/news/become-advocate-new-feature-backdrop-cms-1150) for this issue please.

**Comment by jenlampton** [comment]
I agree that this would be a great addition to core! I've also looked over the PR and the changes seem both straightforward and simple :)  I've removed the milestone-candidate label and added the milestone :)

Unfortunately, in the current PR the checkbox for `Provide a menu link` was not checked by default when I created a new Page node. All the other default settings (Which menu and Parent link) were set appropriately.

**Comment by BWPanda** [comment]
Looks like there's also some failing tests...

**Comment by jenlampton** [comment]
The test suite may have crashed. Pushing an updated PR might fix it.

**Comment by klonos** [comment]
I have tested this, and it is looking good. Thanks @BWPanda 👍 ...a couple of things:

- There should be some form validation, so that there is at least one menu selected from the "Available menus" list. I was able to enable the automatic creation of menu items, without having selected any menu; no errors, but no menu item created either. You can test this by enabling the auto-menu item option for the Post content type, which by default has no menu selected in its "Menu settings" vtab. In general, I'd prefer it if instead of allowing the user to submit the form, and then throw validation errors, we showed an inline warning. Saves users from unnecessary clicks, and page reloads 😉 

- The "Default menu link title" should be hidden while the "Provide a default menu link" checkbox is not selected.

- The "Provide a default menu link" checkbox should be disabled, until at least one checkbox in the "Available menus" list is ticked.

**Comment by BWPanda** [comment]
Thanks @klonos, I'll look into the validation.

I disagree about hiding the title when the checkbox is disabled though. Consider: you want to *allow* menu links for a content type (but not by default), so you don't tick the vox. If a node does get a link though, the menu title should match the node title, so you set the appropriate token. Now, authors just need to tick the box if they want a link, and the title is set already. Otherwise they'd have to enter the same token each time...

**Comment by BWPanda** [comment]
> Unfortunately, in the current PR the checkbox for Provide a menu link was not checked by default when I created a new Page node.

@jenlampton Latest PR fixes this. Still working on other stuff.

**Comment by klonos** [comment]
>  disagree about hiding the title when the checkbox is disabled though.

Right! 👍 ...I haven't thought of that I guess. I was just working on ??? before I reviewed your PR, and it seems that my mind was accustomed to the "Show option to ..." and their matching checkboxes that would set the default (in the "Publishing settings" vtab); so I was expecting this new checkbox to act as a "Show option to provide a menu link". ...oooh, I think I'm getting myself into another rabbit whole; I'll stop here 😅

**Comment by BWPanda** [comment]
Made a commit to try and fix tests, but they're still failing and I don't understand why... Assistance and maybe some guidance would be very much appreciated! :pray:

**Comment by BWPanda** [comment]
One of the failing tests revealed a possible bug... (I've copied this to the status update in the OP for the weekly meeting).

By default, Page nodes have menu items enabled and the menu item name is set to `[node:title]`. When you create a Page node called 'Test 1', the menu item is also named 'Page 1'. However if you edit the node and change the node title to 'Test 2' and save, the menu item name stays as 'Test 1'.
How do we allow for dynamic menu items whereby their name's change if the node title changes, but also allow people to set a custom menu item name without it changing whenever the node title changes...?

**Comment by jenlampton** [comment]
> However if you edit the node and change the node title to 'Test 2' and save, the menu item name stays as 'Test 1'.

I'm not sure this is a bug, it could be a feature. I often want a different menu title than the node title. Especially when the node title is reeeeealy long.

**Comment by BWPanda** [comment]
I've just seen how URL aliases address this problem, and I think I need to do something similar here:

![image](https://user-images.githubusercontent.com/2385329/67513706-0de9b400-f6a4-11e9-923e-452fa0a773d6.png)

So need to add a checkbox to select whether you want a node to use the default value from the content type, or set it manually.

**Comment by BWPanda** [comment]
@klonos (or anyone else wanting to take a stab at fixing the tests), feel free to revert the last few commits of my PR as they seem to have made things worse (89 failures vs. 2).

**Comment by jenlampton** [comment]
@BWPanda I'm not sure we should get into this in this PR. Can we create a follow up to change the behavior of Menu link text (or leave it to contrib?).

**Comment by BWPanda** [comment]
I disagree about it being in contrib. To me, if you set a content type to  have menu items based on the node title, it should be that way for all saves, not just the first one. Happy to move this to a followup, but I'd like to see it in core as per the same functionality as URL aliases.

**Comment by jenlampton** [comment]
Have you been dissatisfied with the current core menu handling?

I haven't.

**Comment by jenlampton** [comment]
> If a node does get a link though, the menu title should match the node title, so you set the appropriate token. Now, authors just need to tick the box if they want a link, and the title is set already. Otherwise they'd have to enter the same token each time...

This isn't the case. There's already javascript on the page that populates the menu link text field with the node title. 

Hm, I've just tested the latest PR and it seems we've lost this functionality. :(

**Comment by jenlampton** [comment]
I've created an alternate PR at https://github.com/backdrop/backdrop/pull/2951 that restores the previous functionality by removing the `Menu link title` default setting entirely. 

Having the actual node title appear in the `Menu link title` field is much easier to understand than seeing a cryptic `[node:title]` token. 

I prefer this current core behavior because the content authoring form is something that people will experience right away when testing Backdrop, and because it's something our least Backdrop-savvy users will need to use most often. 

I don't mind using tokens all over the back-end where admins and our more advanced Backdrop users will encounter them, but I don't like putting them on the content authoring form.

I've never needed the auto_menu_settings contrib module (so I probably don't fully understand the various use-cases for using tokens to generate menu link titles) but I'm pretty sure it's not needed on 80% of sites. If we can reach that 80% use-case by auto-populating the title (which we already do) I think that's probably good enough for the `Menu link title` field.

If we leave this bit out, it will be something the auto_menu_settings contrib module could still add, for those who need it :)

Bonus: It looks like the tests are passing on https://github.com/backdrop/backdrop/pull/2951!

**Comment by BWPanda** [comment]
Since the ability to specify a default menu title has been removed from this PR, my suggestion for a new checkbox allowing this to be turned on/off per node isn't relevant for core. I've therefore added this as an issue in Auto Menu Settings: https://github.com/backdrop-contrib/auto_menu_settings/issues/1

**Comment by jenlampton** [comment]
> Happy to move this to a followup, but I'd like to see it in core as per the same functionality as URL aliases.

> I've therefore added this as an issue in Auto Menu Settings: backdrop-contrib/auto_menu_settings#1

We might also want to create a core issue about default menu title if you feel it should be included. If this resolves quickly we'll have lots of time for the next issue :)

**Comment by BWPanda** [comment]
Since this'll be in contrib regardless, and since there's another issue I want to advocate for after this is done, I'll let someone else champion that if it's wanted in core.

**Comment by BWPanda** [comment]
Basic testing works for me.

**Comment by BWPanda** [comment]
Reviewed the code and left some comments re. unnecessary changes.

**Comment by BWPanda** [comment]
I've updated @jenlampton's PR by removing the unnecessary code. New PR here: https://github.com/backdrop/backdrop/pull/2999

**Comment by jenlampton** [comment]
Yay, thank you @BWPanda !

**Comment by jenlampton** [comment]
Works like a charm! RTBC.

**Comment by klonos** [comment]
I have proposed two changes in the PR:

- Change this:

    > Add a link into the menu for new content of this type

    to:

    > Create a menu link for content of this type, by default

- Change this:

    > Menus where this content may be placed

    to:

    > Menus where content of this type may be placed

**Comment by klonos** [comment]
> We might also want to create a core issue about default menu title if you feel it should be included.

Yes please. I would like to be able to support tokens for the menu titles; but can be follow-up.

Other things I consider nice to haves for this:

- Validation for the menu link title. I think that it should be made required, but I understand that there is a bug currently with required fields that are hidden via `#states` (we could solve that the same way as in #2731). How it works currently is that you can tick the "Provide a menu link" checkbox, and may leave the the "Menu link title" field empty. What happens is that there is no validation error during form submit; the menu item is simply not created (which is odd UX if not a bug/WTF).

- Ability to "lock" the menu creation and menu placement (same as we allow for the "Sticky" and "Promote" options).

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/2999 into 1.x for 1.15.0, thanks @BWPanda, @klonos, and @jenlampton for your work on this!

@klonos, I was not able to apply your suggestions to the description text from the PR. They looked good to me. Could you file a follow-up PR for the unapplied changes from https://github.com/backdrop/backdrop/pull/2999?

**Comment by jenlampton** [comment]
Created an issue so we don't loose our follow-ups
https://github.com/backdrop/backdrop-issues/issues/4251
