### ISSUE TITLE
CKEditor: the tooltip for the "remove link" button is "Link" (same as the "add link" button's tooltip).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1613]
![backdrop-ckeditor_toolbar_buttons-remove_link](https://cloud.githubusercontent.com/assets/2423362/13032604/64556d08-d34d-11e5-89c4-0d64992f7f71.png)

Is it a thing that we need to fix upstream or locally?

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1862.

**Comment by quicksketch** [comment]
This problem only affects the administrative configuration, not the toolbar when editing actual content. PR filed at https://github.com/backdrop/backdrop/pull/1862.

**Comment by Dinornis** [comment]
I checked the PR and can confirm that the Link and Unlink buttons now show the correct tooltip when editing content and when configuring CKEditor.

**Comment by quicksketch** [comment]
Thanks @Dinornis! Feel free to add the "pr - reviewed and tested by community" label after checking functionality.

I've merged https://github.com/backdrop/backdrop/pull/1862 into 1.x and 1.6.x.
