### ISSUE TITLE
Bartik: search block search button is considerably smaller than search box and vertically aligned to the top.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1614]
![backdrop-bartik_theme-search_button_small](https://cloud.githubusercontent.com/assets/2423362/13033947/a2f22460-d37b-11e5-8511-57b8f5ca7983.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2854

**Comment by BWPanda** [comment]
@klonos Is this still the case, or is it fixed now?

**Comment by klonos** [comment]
At some point we must have increased the height of the button, but it seems to still be off by 1px:

<img width="218" alt="Screen Shot 2019-09-07 at 3 03 40 am" src="https://user-images.githubusercontent.com/2423362/64466757-5234eb00-d11c-11e9-8644-4eb3f49983c7.png">

...its height is currently 25px, but it aligns perfectly if changed to 26px:

<img width="232" alt="Screen Shot 2019-09-07 at 3 17 38 am" src="https://user-images.githubusercontent.com/2423362/64467098-33375880-d11e-11e9-860b-7d898878804b.png">

PR up for review: https://github.com/backdrop/backdrop/pull/2854

**Comment by stpaultim** [comment]
Looks good to me.

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2854 into 1.x and 1.13.x.
