### ISSUE TITLE
Add ability to enable/disable certain layout templates (add a settings page for Layout module)

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1617]
This is on the Layout Followup Issues #345 list. I don't get it though. Isn't this what the list of icons on the `Add layout` and `Edit layout` forms are for?

**Comment by klonos** [comment]
Layout packages (the projects, as downloaded in a .zip) might include a single layout design (https://backdropcms.org/project/senjo) or multiple layout designs (think Radix). I can see the need for disabling some of them. Think of it as having the option to not enable all submodules that are shipped with the main project.

**Comment by docwilmot** [comment]
I understand this, but what's the point? The module page is needed to enable/disable modules because multiple modules can be enabled at once. The current UI allows *one* layout 'design' to be selected, the others are essentially 'disabled'. I dont see the point of a separate UI to disable the ones that youre not going to enable anyway.

**Comment by klonos** [comment]
I understand your confusion and I am not a big fan of this either.

**Comment by jenlampton** [comment]
I actually like this suggestion.  It's a feature that I made heavy use of with Panels. The use case is this:  You build a site using Radix layouts (or similar) and that layout project provides 30+ options.  You build the site, using maybe 4 of them, and you turn over admin control to your client. They are now able to build new pages using any of the 30 layout templates, but maybe they should really only be using those 4.  How to prevent this?  Disable the other 26 from appearing in the layouts UI!

**Comment by klonos** [comment]
How would that work UI-wise? Do you think perhaps having a separate "Layout templates" tab where people can enable/disable them using checkboxes a la modules admin page?

What would be the default when you install a new layout package that includes multiple templates? ...all enabled by default you think?

**Comment by jenlampton** [comment]
@klonos yes, all enabled by default I think. This should be an advanced/optional setting since it likely won't be needed by everyone.  I'm going to take a stab at this now since I need it for https://github.com/backdrop/backdrop-issues/issues/698#issuecomment-215520767

**Comment by docwilmot** [comment]
Just pushed an updated version with a confirm form if youre hiding templates that are already in use. Have at it @jenlampton.

**Comment by docwilmot** [comment]
P.s. I pushed this as soon as I saw your post so we weren't both working on the same thing, so it is a bit untested in this version.

**Comment by jenlampton** [comment]
@docwilmot this is fantastic, thank you. I had taken almost the same approach you had, but I decided to save excluded layouts instead of included so that new layotus would be enabled by default. I also didn't bother with the extra permission.  Since layout-building is already a fairly high-level admin task, I'm not sure it's really necessary. My patch ended up a little simpler, but I'd love to hear what you think.

**Comment by docwilmot** [comment]
From your comment above:
> you turn over admin control to your client. They are now able to build new pages using any of the 30 layout templates, but maybe they should really only be using those 4. Disabling the other 26 from appearing in the layouts UI would do it!

How do you do that without separate permissions?

Otherwise, I agree with the simplification.

**Comment by jenlampton** [comment]
> How do you do that without separate permissions?

With two separate UIs. One that allows which templates appear in the other. It's not a permissions issue as it is a user-interface cleanup task.

**Comment by jenlampton** [comment]
current PR has tests :)

**Comment by docwilmot** [comment]
> It's not a permissions issue as it is a user-interface cleanup task. One admin can have access to both UIs.

I feel that with the two UIs there is the expectation that there would be special access for each. Otherwise your new client admin to whom you just released the site can just go to `layout/settings` and enable at will, thus totally defeating the purpose. And I don't see how a new permission would hurt performance or complexity.

**Comment by jenlampton** [comment]
Fair enough. :)

**Comment by quicksketch** [comment]
Overall PR at https://github.com/backdrop/backdrop/issues/1346 looks great. I left some minor feedback. Could we get that PR rebased against 1.x so that the tests will run in their new split-mode so they will finish within the Travis CI timeout limit?

**Comment by quicksketch** [comment]
Is the Radix/additional layouts issue (https://github.com/backdrop/backdrop-issues/issues/698) dependent upon this PR?

**Comment by jenlampton** [comment]
@quicksketch no, but we should aim to get them both in for 1.4

**Comment by jenlampton** [comment]
Just pushed an updated PR here https://github.com/backdrop/backdrop/pull/1346

**Comment by quicksketch** [comment]
PR needs a little work, we have a new failing test on the current one.

**Comment by jenlampton** [comment]
Pushed a fix: backdrop/backdrop#1346

**Comment by quicksketch** [comment]
I added some more feedback to the PR at https://github.com/backdrop/backdrop/pull/1346.

**Comment by jenlampton** [comment]
Pushed a new PR addressing your feedback: https://github.com/backdrop/backdrop/pull/1346

**Comment by quicksketch** [comment]
I rerolled one more time to accommodate for latest changes in 1.x: https://github.com/backdrop/backdrop/issues/1388

**Comment by quicksketch** [comment]
And https://github.com/backdrop/backdrop/pull/1388 is merged! Great work @docwilmot and @jenlampton putting this together. Now the door is open to completing our new layouts in https://github.com/backdrop/backdrop-issues/issues/698!
