### ISSUE TITLE
Port the Panels "from block" title setting for layouts, allowing the title of a layout to be pulled from an individual block.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1618]
This is on the Layout Followup Issues #345 list.

**Comment by klonos** [comment]
:+1:

**Comment by klonos** [comment]
...perhaps also allow to set this from the block's side. A "Use this block's title as the page title." checkbox perhaps?

**Comment by docwilmot** [comment]
Added this functionality to the Page title PR for simplicity as this would be dependent on that PR otherwise.

**Comment by quicksketch** [comment]
> Added this functionality to the Page title PR for simplicity as this would be dependent on that PR otherwise.

To this issue then? https://github.com/backdrop/backdrop-issues/issues/952

Can we mark this issue duplicate?

**Comment by quicksketch** [comment]
Yeah I reviewed the issue in https://github.com/backdrop/backdrop-issues/issues/952, it includes this functionality as well. They will both go in together.
