### ISSUE TITLE
Development workflow. Branch for each issue.

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1620]
I just listened podcast and came up with idea how to make process much easier for collaboration .

I see next features and functionality:
- [x] automatically create branch for each new issue
- [x] automatically accept PR to issue branch 
- [x] automatically sync issue branch when 1.x branch get updated
- [ ] report to issue if there is issue to accept PR or sync with 1.x branch

It's all can be done via github API.

It can solve next problems:
- keep commit owners in git log
- apply extra patch to original PR by other developers
- allow few users to work on one issue much easier.

I can signup to implement it until end of February.

**Comment by klonos** [comment]
It will be easier for a broader audience to be able to test things and provide feedback/reviews. No need to patch in order to test (and then have to revert the patch). Simply download the whole branch (zip link provided by GitHub already for each branch) and test away. When finished either delete the whole thing (if you created a fresh installation) or simply overwrite with the current version of core.

:+1:  ...unless there's serious implications that I cannot thing of right now of course.

**Comment by klonos** [comment]
...meta-issues can have their own branch and sub-issues branch off of that. People can either test single issues or download the zip of the meta-issue branch and test the entire thing.

**Comment by Gormartsen** [comment]
Also it will help to track PR. 
when issue get closed, all related PR will be applied by accepting merge compatible or closed by rejecting conflict one.

**Comment by quicksketch** [comment]
Hm, thinking this over, in a more descriptive version:

- User A creates new issue (say issue `#1000`).
- Via the API, we automatically create a branch for development, e.g. `dev/1000` at `https://github.com/backdrop/backdrop/tree/dev/1000`.
  - How would we determine if a branch were necessary? Many issue are just questions or meta issues that don't have direct code.
- User B has work they want to implement, they file a PR against `dev/1000`.
- Via the API, the PR is detected and (if possible) automatically merges into `dev/1000`.
- User C could potentially add extra work by pulling from `dev/1000`, adding extra commits, then creating another PR against `dev/10001.
- Via the API, the second PR is detected and again automatically merged into `dev/1000`.
- When ready to merge, the committer would manually merge the branch `dev/1000` into `1.x`.

There could be a few minor issues with this:

- Should we deal with messy commits or revisions to the code prior to merging? If the original PR is dysfunctional, should we have that in the Git history?
- What do we do about completely different approaches to the same problem? If User C's approach is completely different from User B, it might be discouraging if the second developer's work just overwrote the first developer's in the same branch.

**Comment by quicksketch** [comment]
A possible solution to both these problems:

> How would we determine if a branch were necessary?
> What do we do about completely different approaches to the same problem?

We could have a key phrase that can be detected by posting a comment. e.g. "`@backdrop-ci Create branch`"

Then a branch would be automatically created for the current issue. Lullabot has done a similar thing for their [Tugboat](https://tugboat.qa/) platform. Anyone posts a comment on a PR with "`Test this please`" and it automatically builds a QA environment based on the PR.

---

Overall I think this is an interesting proposal. My primary concern with implementing it is deviating from GitHub standard practices. Or if there is a standard practice that is similar to this, let's try mimic already existing approaches.

Lastly, for simple and direct issues (typos, doc fixes, etc) this entire approach may be overkill. Should it be optional for simpler issues?

**Comment by klonos** [comment]
> We could have a key phrase that can be detected by posting a comment.

...or because the exact phrase might be hard to remember and error-prone, we could use a tag/label instead if possible?

**Comment by klonos** [comment]
> Lastly, for simple and direct issues (typos, doc fixes, etc) this entire approach may be overkill. Should it be optional for simpler issues?

Yep, the key-phrase or label should be good for that.

**Comment by klonos** [comment]
...sorry

**Comment by Gormartsen** [comment]
> we could use a tag/label instead if possible?

this one require access to labels

**Comment by quicksketch** [comment]
> we could use a tag/label instead if possible?

Hm, yeah that would work for one branch. If you wanted a second branch? Just remove and add the label again? Or would you expect that to tear-down the branch?

> this one require access to labels

Yeah, right now we assign access to everyone who participates access to issue labels. But you're right this could be a barrier for new contributors who haven't yet gotten access.

**Comment by Gormartsen** [comment]
> When ready to merge, the committer would manually merge the branch dev/1000 into 1.x

Or if user does not have access to merge to 1.x, ask to do so anyone who has.

> User B has work they want to implement, they file a PR against dev/1000.

We can pull travis CI status via [Status API](https://github.com/blog/1227-commit-status-api) from PR and merge only when tests passed. So user will be able to update PR before create another PR to fix failed tests. 
This will give us pease of mind that merging dev/1000 to 1.x will not brake anything.

> Overall I think this is an interesting proposal. My primary concern with implementing it is deviating from GitHub standard practices. Or if there is a standard practice that is similar to this, let's try mimic already existing approaches.

As far as I know, Github by itself use keywords to deploy [PR to production](https://github.com/blog/1241-deploying-at-github):
> The basic workflow goes like this:
Push changes to a branch
Wait for the build to pass on our CI server
Tell Hubot to deploy it
Verify that the changes work and fix any problems that come up
Merge the branch into master

The major difference here is that we have limited amount of users who has right to create a branch.

In my company I use next flow for development (private repo without ability to create a fork)

1. developer create branch issue-NNNN
2. commit to issue-NNNN branch a code to solve an issue
3. code style, tests, development deploy happen to issue-NNN.website to see the result after each commit to this branch
4. when issue fixed, developer issue PR to stage branch. another cycle of tests and stage deployment happen.
5. team lead double check results and if stage is good, issue PR to master branch
6. code get deployed to production

**Comment by Gormartsen** [comment]
> Hm, yeah that would work for one branch. If you wanted a second branch? Just remove and add the label again? Or would you expect that to tear-down the branch?

If we use keyword to trigger branch, we can attach username to branch name. Like dev/1000-quicksketch or simpler way dev/1000-0

When another user trigger keyword we create dev/1000-1 and etc.

This way if somebody propose different way to solve issue, we will have different branches.
It's more complicated but will give people ability to separate solutions  and we can compare two different solutions before put them to 1.x. 

But I think it's overkill at this stage. We do not have so much developers right now.
If we keep only one branch for issue, it will force people to communicate (over gitter!!) about issue and find common ground for solution.

**Comment by Gormartsen** [comment]
> My primary concern with implementing it is deviating from GitHub standard practices. Or if there is a standard practice that is similar to this, let's try mimic already existing approaches.

General git flow recommendations: http://nvie.com/posts/a-successful-git-branching-model/

Github flow is based on forking to make collaboration much simpler: https://github.com/blog/1557-github-flow-in-the-browser 
but how you mentioned in podcast , it's really hard to collaborate few people to work on one issue. They need to issue PR to his repo first.

It will look like:
- user A created PR from userA/backdrop fork and create PR NNN1
- user B want to add his own patch. He send PR ZZZ1 to userA/backdrop repo. 
- user A has to accept PR and commits from PRZZZ1 get attached to PR NNN1

And if user A is not available, user B can fork userA/backdrop to userB/backdrop (to keep commit ownership) and then add his own code and issue PR to backdrop/backdrop.

This way we has next issues:
- dead PR from userA who disappear for some reason
- userB is depending on userA to process commits to PR
- not user friendly flow between different forks
- if userB for some reason is not familiar with this flow, he can fail to keep commit ownership
- Merging with conflicts can become nightmare with rebase and cherry pick.

**Comment by quicksketch** [comment]
One more idea if we stick to labels: Make a label like "Automation - Create feature branch" (spit-balling here). When the new branch is created by our integration user (@backdrop-ci), it can simply edit the issue and remove the label. Then you can create as many branches as you want.

One thing I like about the label approach is that it adds discoverability. If a contributor saw such a label, they might Google it or look for docs as to what labels do what. Of course regardless of the approach, we can document it in the README.md file for the "backdrop-issues" repository.

**Comment by Gormartsen** [comment]
>  README.md file for the "backdrop-issues" repository.

How about to do the same flow for backdrop/backdrop ?

This way we give more flexibility to developers who does not have access to create branch under backdrop repo but want to provide some bug fixes or new features to core.

**Comment by Gormartsen** [comment]
Sorry, deleted previous message. 
The good part about implementing branch based flow for issues, that we can add it to backdrop-contrib repos as well. 

It will give a boost to contrib modules from not signed developers. 

And if we connect it to something like https://simplytest.me but for issue branches as well, we can have life preview for issues.

**Comment by klonos** [comment]
> And if we connect it to something like https://simplytest.me but for issue branches as well, we can have life preview for issues.

:+1: ...million!

**Comment by Gormartsen** [comment]
Yesterday github announced templates for PR and issues:
https://help.github.com/articles/helping-people-contribute-to-your-project/

It also help with contribution and I recommend to add it as well.

**Comment by quicksketch** [comment]
> Yesterday github announced templates for PR and issues:

Ooo! Nice, though I wish we didn't need to make files in the repository just for GitHub. Seems like they could just have that be a setting on the repository. :P Alas, GitHub. We'll want to update the packager to exclude these files if they are included, there's no reason for them to be in our downloadable packages.

**Comment by klonos** [comment]
> Creating an issue template for your repository

I remember that we've been struggling to get something like that working in d.org. The best we had was [Issue Summary Template standards](https://www.drupal.org/node/1155816) and we had to tell people to copy-paste it when creating a new issue. With GitHub we get it for free! We shouldn't be complaining @quicksketch

**Comment by klonos** [comment]
...is there anything left to be done here?

**Comment by BWPanda** [comment]
A few ideas here for changing the way people contribute to Backdrop. But since there's been no progress past the initial discussion, I'm going to go ahead and close this.
