### ISSUE TITLE
Deployment & drush

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1621]
I've created a module for myself for d7 to deploy different information from dev to production:
https://github.com/itpatrol/drupal_deploy/tree/7.x

The major focus here is automation. This module has to work via deploy scripts via ssh instead of admin panel.

For example if you updated menu on your dev site and want to deploy it on production you do:

```
drush dde menu --name=main-menu
```

And then you have Json file main-menu.menu.export

You just write to your deploy script

```
drush ddi menu --file=main-menu.menu.export
```

And on deploy phase menu structure will be updated!

The same things works for filters, blocks, node_types, variables, taxonomy, roles (with permissions )

Drupal 6 version is more advanced ( nodes, Cck, users!) and Drupal 7 is still dev, I am porting features as I need them.

What I think here is that we can not only port it to backdrop but make it core feature, when modules can provide import export hook to support deployment process!

Give me your opinion and if there is somebody to collaborate with, I will invest my time to this issue ( after I done with render cache)

**Comment by Gormartsen** [comment]
I am using this module on drupal.ru website with git.lc service.

Example script : https://github.com/DrupalRu/drupal.ru/blob/master/scripts/update/issue-371.sh
```sh
echo "Import taxonomy for ticket status"
drush ddi taxonomy --file=$GITLC_DEPLOY_DIR/data/ticket_status.taxonomy.export

echo "Import taxonomy for claim status"
drush ddi taxonomy --file=$GITLC_DEPLOY_DIR/data/claim_category.taxonomy.export

```

Deployment log:
http://git.lc/DrupalRu/drupal.ru/deploy/deploy-DrupalRu_drupal.ru_master-4129
```sh
Processing issue-371.sh
Import taxonomy for ticket status
Vocabulary Статус тикета imported		[ok]
Term В обработке imported				[ok]
Term Закрыто imported 					[ok]
Term Открыт imported					[ok]
Import taxonomy for claim status
Vocabulary Claim Category imported		[ok]
Term Нарушение законов imported			[ok]
Term Спам imported						[ok]
Term Темная материя imported			[ok]
Term Троллинг imported					[ok]
Term Флуд imported						[ok]
Term Хамское поведение imported			[ok]
```

**Comment by mikemccaffrey** [comment]
> What I think here is that we can not only port it to backdrop but make it core feature, when modules can provide import export hook to support deployment process!

That is kinda the point of the whole Configuration Management Initiative, which we've backported to Backdrop. All modules are saving their exportable settings out to .conf files which can be moved to the live site and imported.

Right now that process has some manual steps even if you check the config files into code, but (unless I am missing something) the only thing that we need to do to allow automation is to get backdrop-contrib/drush to support the new config management commands: http://drushcommands.com/drush-8x/config/

**Comment by Gormartsen** [comment]
@mikemccaffrey it is beyond configuration management. It's helps to authorize **content** delivery. 
Like: menu, nodes, comments, roles, permissions and etc.

**Comment by Gormartsen** [comment]
There is a quick example on Drupal 7.

Check this script out: https://github.com/DrupalRu/drupal.ru/blob/stage/scripts/install.drupalru.php

If you run it, you will get something like this: http://dev.drupal.ru

And it will have:
- all roles with permissions ready
- taxonomy for blog node type
- forum structure (http://dev.drupal.ru/forum)
- all custom node_types
- theme settings
- block settings
- variables settings

I agree, some of this things could be done with CM. I propose to go beyond it and make Backdrop ready to be deployed by single commit to github, without any extra clicks in admin menu or ssh.

**Comment by mikemccaffrey** [comment]
> @Gormartsen: it is beyond configuration management. It's helps to synchronize content delivery. 
Like: menu, nodes, comments, roles, permissions, taxonomy vocabularies and terms and etc.

Well, roles and permissions are currently being handled in contrib, and there seems to be consensus forming to make menus and vocabularies configuration as well.

> @Gormartsen: I propose to go beyond it and make Backdrop ready to be deployed by single commit to github, without any extra clicks in admin menu or ssh.

Well, once we get the drush commands working, we won't need to muck around in the admin menus anymore. I can't speak to how you are automating things after they are pushed to github, but would be interested in hearing more about your workflow.

As far as the larger idea of deploying content, there certainly is demand for that sort of functionality. However, since different people might have very different ideas of what that workflow would look like, it seems like we should try out some different possibilities in contrib before deciding on which approach to pull into core. Make sense?

**Comment by Gormartsen** [comment]
> Well, roles and permissions are currently being handled in contrib

Can you point me to this modules please?

>  make menus and vocabularies configuration as well.

that's nice!  

> I can't speak to how you are automating things after they are pushed to github, but would be interested in hearing more about your workflow.

My workflow process looks like this for Drupal 6, Drupal 7 with module [drupal_deploy](https://github.com/itpatrol/drupal_deploy/tree/7.x):

1. I have dev site where I am working on issue or feature request to add new node type with custom functionality.
 
1. When I done, I have 
 - module with node type definition, fields and custom functionality
 - module settings json file, that contain production ready settings (like token based email template)
 - node_type json file, contain general, comment, fields settings
 - taxonomy json, contain vocabulary and terms for production
 - menu json, with new menu structure to make new section available via main menu

or even more: website pages based on this node type created by text writer that contain blocks and nodes. Then I have few extra json files: node.json and blocks.json files.

2. I write a script for deploy system based on git.lc website. 

*git.lc uses github webhook to get notifications about commits to repo and push code to production via ssh automatically. Ask me if you need more details about it*
```
issue-NNN.sh
drush ddi node_types --file=nodetypes.jsonfile
drush ddi taxonomy --file=taxonomy.jsonfile
drush ddi variables --file=settings.jsonfile
drush ddi menu --file=menu.jsonfile
```

3. I push code to branch (PR or commit is does not matter). 

4. Git.lc delivery code to production server and call my issue-NNN.sh in docroot folder.

5. I check website, deploy log and tests results to make sure there is no issues after deploy.

It's actually simplified workflow, because I use stage branch and stage website to test deploy first. And when all is good on stage, I just create PR from stage to master and accept PR. 
Production website get updated with 0 clicks or SSH commands on my side.

Purely github usage and properly configured deploy.



> However, since different people might have very different ideas of what that workflow would look like, it seems like we should try out some different possibilities in contrib before deciding on which approach to pull into core. Make sense?

It is make sense. Maybe I did not uncover my idea at full range.
I am proposing to implement core driven deploy standard with HOOK API.
Let's say something like this:
```php
/**
 * Implements hook_deploy.
 */
function roles_deploy($op, $a1){
  switch($op){
   case 'config': 
    //return some config info
    break;
  case  'export':
   //export roles based on $a1
   return roles_export($a1)
  break;
  case  'import':
   //import roles based on $a1
   return roles_import($a1)
  break;
 }
}

function roles_export($options){
  // there is a logic to get current roles settings and create Array for report
  return $some = array(
 );
}

function roles_import($data){
  // there is a logic to store $data array in database
 );
}
....
```

When it's done on core modules, we can include drush command:

drush export MODULE_NAME --SOMEOPTIONS
drush import MODULE_NAME --file=EXPORTFILEPATH

or more detailed example:
drush export roles --name=administrator
drush import roles --file=administrator.export.json

And by doing it on core level to **each module** we will initiate core based deploy system that nobody else has yet. API and documentation will give a boost to new users who never get in touch with deploy before.

**Comment by mikemccaffrey** [comment]
> Well, roles and permissions are currently being handled in contrib

Whoops, meant to say config, not contrib.

**Comment by quicksketch** [comment]
> What I think here is that we can not only port it to backdrop but make it core feature, when modules can provide import export hook to support deployment process!

> Give me your opinion and if there is somebody to collaborate with, I will invest my time to this issue ( after I done with render cache)

It would be great if you could help move forward the Drush port, which still needs quite a bit of help: https://github.com/backdrop-contrib/drush

Most of the examples in the script can be handled by Config Management, but deploying content (like terms, nodes, users, etc) isn't yet handled by Backdrop. However, content deployment has a larger set of problems (unique ID conflicts, updating existing content, etc). For starters, I'd like to see this as a contrib project rather than attempting to make it directly part of core.

**Comment by Gormartsen** [comment]
@quicksketch thank you for feedback. 
I will see what I can do for drush (it's must have feature)

**Comment by jenlampton** [comment]
I would also love to see a cli for cmi - hopefully via drush - that could import individual config files (like roles, menus, etc) as well as sync the entire site. I wonder if something similar is underway for Drupal 8's cmi and drush?

**Comment by BWPanda** [comment]
Gonna close this old issue in favour of Drush issue queue and contrib module(s).
