### ISSUE TITLE
Views: Exposed filters: "Remember the last selection" option not working.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1626]
While helping @bd0bd in #1574, [he mentioned](https://github.com/backdrop/backdrop-issues/issues/1574#issuecomment-185374587) that the exposed filter for "Content: Language" did not remember last selection after navigating elsewhere and then back to the view. I was able to verify that.

**Comment by quicksketch** [comment]
Thanks, I've confirmed this issue as well.

**Comment by quicksketch** [comment]
I have a fix for this, I'll make a PR once I finish adding new tests.

**Comment by bd0bd** [comment]
Thank you!

**Comment by jenlampton** [comment]
:+1:

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1273 with new tests to double-check this functionality.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/1273. Thanks again @bd0bd.
