### ISSUE TITLE
Admin 'Add content' listing is using underscore not hyphen in links.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1627]
When a type of content has a machine name that includes underscores e.g. slideshow_demo_image the admin menu correctly uses links with hyphens in place of the underscores (e.g. ..../node/add/slideshow-demo-image). 

However, the 'Add content' listing uses the underscores and consequently the link does not work ( ...../node/add/slideshow_demo_image ) This is with theme 'Seven'.

**Comment by serundeputy** [comment]
`PR` https://github.com/backdrop/backdrop/pull/1259
patch: https://github.com/backdrop/backdrop/pull/1259.patch

- [x] travis happiness

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1259. Thanks @serundeputy and @Graham-72!
