### ISSUE TITLE
[UX] Better front page selection UI.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1628]
This is what we currently have in place:

![backdrop-front_page_settings](https://cloud.githubusercontent.com/assets/2423362/13154816/ee611c34-d6ce-11e5-9336-37fe57f9e114.png)

There's no need to show the current "Number of posts" section if the specific node/page option is selected. It just clutters the UI and might confuse new users making them think that this is an option that applies to the "default front page" selected above.

Here are some changes I propose:
- [ ] Make these options a set of radio buttons (label text might need more thought):
  
  ![backdrop-front_page_settings-radio_set_options-specify_page](https://cloud.githubusercontent.com/assets/2423362/13159363/7b3e927e-d6e5-11e5-887b-4e3bd47586ef.png)
- [ ] Add a page browser/selector:
  
  If the default of "Show a specific page" is selected, I'd like it to have a button/link next to the text field we already have in place that would allow users to change the selected node. I originally thought that a generic "Browse..." or  "Select page..." text would be more appropriate for this link, but once we implement #519 this field will already be populated by the default `hello-world` node. Hence the "Change front page".
  
  Anyways, having both a text field as well as a browse option, we still allow advanced users to type the URL, while at the same time offer an easier UI for new users.
  
  I'd like the page browser to open a dialog that would have the following options:
  - _Create a new front page_: This option would allow people to select a content type (Basic page by default) and create a new node. Upon save, the node would be set as front page "automagically" in the background and the user would be redirected to the front page settings where they started from (`admin/config/system/site-information`).
  - _Select existing content_: This option would allow people to search and select a specific, already created node (basically a variation/display of the "Admin content" view loaded in a dialog).
- [ ] Make the current "Number of posts on front page" section a "simplified" content listing generator (in the "backstage", this will actually be a "Front page" view).
  
  If the "Show a list of content excerpts" option is selected, instead of "locking" the user to using "posts", I'd like to see a drop-down button to allow the user to select their own content type (default set to either "Basic page" or "any" - lets discuss that). In the backend, this will be a "Front page" view (#144). We just expose here a filter for limiting the content type to display. ...and perhaps also pager options (in place of the current "Number of posts" drop-down)?

**Comment by klonos** [comment]
Thoughts??

**Comment by klonos** [comment]
...updated my mockup above to include hints about using content vs Views next to the radio options labels.

**Comment by klonos** [comment]
Notes:

- As for the "Show a list of content excerpts" label, Here's a definition of Views [from the source](https://www.drupal.org/node/2287909):

> **What is Views?**
>The views module allows administrators and site designers to create, manage, and display lists of content.

...so there you have it! We can keep it simple: "Show a list of content"

**Comment by docwilmot** [comment]
I like the idea of radio option. This changes #144 though: that issue conceived only one view which would be *the* front page view, but youre proposing that the front page view should be swappable. 
I would simplify:
The "Show a list of content" has an edit link to *the* front page view
The "Show a specific page" states-reveals an autocomplete textfield to select an existing node. The textfield also accepts a path or alias.

**Comment by klonos** [comment]
We can still have #144 offer a default *front page* **view**. Then also have #519 offer a default *front page* **node**. Finally this issue here is to improve the UI for selecting whether having a view or a node as front page. The ones we ship with core would be the defaults so users can have something to start playing with and that works out of the box no matter which option they choose.

Issues like #1042 can improve the out of the box experience no matter which specific choice is made as a front page: node or view.

Now, as to which we should have as the default option (the node or the view) ...lets discuss. Personally, I think that we should be taking it easy on the new users and not introduce them to views straight away (if they attempt to edit the *front page* view - if that's the default). Having a "Hello Word" page as the front page (#519) out of the box makes more sense to me.

Again, the goal (not of this issue here specifically, but in general) is to remove the current special-cased, non-page, "No content created yet" thing that we currently have as a front page.

**Comment by klonos** [comment]
...so to simplify:

#519: "Hello World!" **node** (to be used as front page)
#144: "Front page" **view** (as the alternative option)
#1628: (this issue here) The UI that allows selecting whether the front page should display a node or a view - uses the results of #519 and #144 as the defaults, but allows users to choose their own ones.
#1042: Provides the default layout for the front page (be it a view or a node that is rendered in the main content region) - perhaps uses #1152 too??

**Comment by quicksketch** [comment]
I think once people get familiar with Layouts, (and especially once #1042 is implemented), it's much more likely that a layout configuration is going to be used as the homepage rather than either a View or a Node. Then if you want to modify your homepage, you modify the layout configuration, rather than changing the path of the homepage to something else entirely.

So the radios for "Show a specific page (use content)" and "Show a list of content excerpts" don't include what will be the most likely scenario, which is "Use a layout". Though you could type in the layout path in the "show a specific page" option, but the "use content" part becomes misleading.

Tying together all the issues you've listed above:

- #1042: Provides a homepage layout.
- #1152: Hero image placed in homepage layout.
- #144: Instead of making a view *page* this could instead be simply a block. And then placed within the homepage layout.
- #519: The hello world node is simply the first node listed within the view.

So they actually all fit together, we'd implement all of them. I do think you're right that we would remove the "Number of posts" option (probably as part of #144). And if we gave users a front page layout they could edit, it'd be unlikely they'd ever need to change the homepage path at all, making this entire form less important.

**Comment by klonos** [comment]
Yep, minor details aside, I think that we're all on the same page with regards to direction. :+1: This will be a big improvement!

**Comment by BWPanda** [comment]
If/when https://github.com/backdrop/backdrop-issues/issues/3764 gets committed, that'll provide the 'page browser/selector' feature @klonos mentioned in the OP, assuming that's still desired with everything that's been discussed since then...

**Comment by klonos** [comment]
All of the linked issues from this one have now been fixed/closed, and various things are either moot or not-applicable any longer:

- > Make these options a set of radio buttons ... Add a page browser/selector...

  With #3764, this is less relevant now. The autocomplete allows people to select either a specific piece of content, or a views-generated page, or a layout page, or an arbitrary menu item:
  ![image](https://user-images.githubusercontent.com/2423362/147913205-68db803d-94e3-45dd-be9e-497419f45f03.png)
- > If Views module is disabled, the only option would be the specific node/page one.
  Views is always required/enabled in Backdrop (see https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/views.info#L9), so that's not a thing.

There may still be some valid ideas here (such as allowing people to create a home page with an easy link, and then redirect them here), but I'll file follow-ups if needed.

Closing this as outdated then.
