### ISSUE TITLE
[UX] Improve the text displayed when search returns no results.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1630]
@serundeputy in https://github.com/backdrop/backdrop/pull/1233#issuecomment-180766357

> I don't know what the policy is on this. Do we open a new issue to give people a chance to weigh in on the wording?
> 
> D8 Message
> 
> `You must include at least one keyword to match in the content. Keywords must be at least 3 characters, and punctuation is ignored.`
> 
> Either way I think we should get this in as it fixes a bug and then we can enhance later with better language. Unless better language is arrived at quickly.
> 
> New issue ... for transparency and allow others opportunity to see the proposed language?

@quicksketch:

> Yep, let's fix the bug and change text separately.

Here it is!

**Comment by serundeputy** [comment]
This can be fixed in the file `core/modules/search/search.extender.inc` on line `347`:

```php
form_set_error('keys', format_plural(config_get('search.settings', 'search_minimum_word_size'), 'You must include at least one positive keyword with 1 character or more.', 'You must include at least one positive keyword with @count characters or more.'));
```

this message has a singular and a plural form.

here is the plural form:
`You must include at least one keyword to match in the content. Keywords must be at least 3 characters, and punctuation is ignored.`

I think the singular form should be:
`You must include at least one keyword to match in the content. Keyword must be at least 1 character, and punctuation is ignored.`

thanks,
~Geoff

**Comment by MayankR** [comment]
This is my first time contributing to an open source project. I made the changes to text as suggested and added the pull request #1481. However some of the build tests fail. Can you please help me with it?

**Comment by serundeputy** [comment]
Hello @MayankR !
Thanks for contributing to Backdrop CMS and Open Source!

We added a test to make sure that this search was working.  The test just needs to be updated to look for the new help text you added in your `PR`.

The file is: `core/modules/search/tests/search.test` and it looks the the test is checking for that text on lines `606`, `609`, and `617`.

Update those tests and on your branch commit them and [rebase](https://backdropcms.org/develop/pull-requests) (see the rebase section if you need help with that).  Then force push your branch up to your fork of backdrop that will update the `PR`

Then everything should go green!  Then we can get this committed.

thanks again!
~Geoff

**Comment by quicksketch** [comment]
Test was updated and all is passing. Merged https://github.com/backdrop/backdrop/pull/1481 into 1.x for 1.5.0. Thanks!

And welcome @MayankR! We're very excited to have you contributing to Backdrop! You've done it now!

**Comment by MayankR** [comment]
Thanks a lot!
