### ISSUE TITLE
Site name h1 is replaced with div

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1633]
I use Radix Bartlett layout and Bartik theme.
And here is a small problem with Site name.
If I am on the Home page then it has h1:

```
    <h1 class="site-name">
      <a href="/" title="Home" rel="home"><span>Company Name</span></a>
    </h1>
```

But if I go to any other page then h1 is replaced with div:

```
    <div class="site-name">
      <a href="/" title="Home" rel="home"><span>Company Name</span></a>
    </div>
```

Could you tell me please how and where to fix it?
Thank you!

**Comment by Graham-72** [comment]
Have a look at header.tpl.php in core\modules\system\templates and you will see

```
  <?php if ($site_name): ?>
      <?php if (!$is_front): ?>
        <div class="site-name"><strong>
          <a href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>" rel="home"><span><?php print $site_name; ?></span></a>
        </strong></div>
      <?php else: /* Use h1 when the content title is empty */ ?>
        <h1 class="site-name">
          <a href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>" rel="home"><span><?php print $site_name; ?></span></a>
        </h1>
      <?php endif; ?>
    <?php endif; ?>
```

So it would seem to be treating the front page differently. Perhaps you should add your own version of header.tpl.php in your site's templates.

**Comment by bd0bd** [comment]
Thank you but I do not understand the reason - why this happens, what is the reason?
In my last site I have build with Backdrop 1.2 in September I do not remember this problem :)

**Comment by Graham-72** [comment]
I think perhaps you should look at the settings for the header block in your layout. It would look something like this, with a tick box for whether you want the site name to appear:

![homepage - browsers bookshop 2016-02-20 08-06-31](https://cloud.githubusercontent.com/assets/10559274/13195398/45470240-d7a9-11e5-82db-0ba0fe47037a.png)

**Comment by bd0bd** [comment]
@Graham-72, thank you very much! It is solved with your help. The reason was - STYLE SETTINGS was **Dynamic** (done by me) and not **Default**.

**Comment by klonos** [comment]
@bd0bd glad you sorted it out. Please remember to close the issues you solve.

**Comment by bd0bd** [comment]
Sorry, I did not knew about this.
I will do it in future.
