### ISSUE TITLE
Rename bulk operation for promoting content

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1639]
It looks like we missed a spot over in https://github.com/backdrop/backdrop-issues/issues/1190 The Bulk operations for promoting / demoting content still say : `Promote content to front page`  and `Remove content from front page`.

How about:
`Promote content`
`Remove promotion`

**Comment by quicksketch** [comment]
Sounds good to me. Merged in https://github.com/backdrop/backdrop/pull/1267.
