### ISSUE TITLE
new custom block does not remember block-template selection in UI.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1641]
Steps to reproduce:

1) add a new custom block to a layout
- Under "Style settings" set to `Dynamic`
- change the block wrapper to "no wrapper" and save the block.
- save the layout.

2) edit the layout, and configure the block.
- Under "Style settings" note the selection is `Default` and not `Dynamic`

**Comment by jenlampton** [comment]
As @quicksketch suggested, it looks like we forgot to call the parent class submit handler, thus not saving the style settings for these new blocks. Quick fix in PR.

**Comment by quicksketch** [comment]
The first PR was failing tests. New PR filed at https://github.com/backdrop/backdrop/pull/1271 that should address this by calling not only `parent::formSubmit()` but also `parent::form()` so all the expected elements and values are there.
