### ISSUE TITLE
Consider allowing HTML tags in titles?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1642]
I often have use-cases where I'd like to include html tags in titles. My use cases are specifically for block titles, but this might also extend to node titles, or term titles, or similar. In particular, I often want to add inline tags such as `<span>`,`<a>`, `<strong>`, and sometimes even  `<i>` tags (for use with font-awesome). I've also needed to include HTML entities, such as for a trademark or copyright symbol. None of this is currently possible, and I often wonder about the ramifications of allowing just a smidge more flexibility for these title fields.

I'd love to hear what others think (pros and cons) about allowing limited HTML tags in titles.

**Comment by serundeputy** [comment]
I've never understood why drupal didn't at least have a permission for admins to use html in titles.
I we accompany it with a permission then paranoid site admins can rope it off as they see fit.
:+1:

**Comment by klonos** [comment]
This reminded me of the need I have for a D7 website I'm thinking to convert to Backdrop where I use [Icon API](https://www.drupal.org/project/icon) to place icons in the menus. But it also supports adding icons to text areas (as a text filter), to blocks and to fields. So if the page title was an actual field (shamelessly promoting #1191), all we'd have to do is port that module over :wink: ...also shamelessly getting back to you @jenlampton for closing that issue:

>I think it's too early to know if we need a page_title module in core. Let's wait until 1) after it's ported and 2) after we have some usage statistics to see if it is worthwhile to 80% of sites running Backdrop. Closing this issue until then.

**Comment by klonos** [comment]
...also, now with fields as blocks in core (#1100), you could add the title field as a block and then use the block style settings to add wrapper/content tags.

**Comment by gifad** [comment]
To be complete, Backdrop core should implement `hook_field_extra_fields()` (the 'display' part) to allow hiding the actual title.. (I'm sure this has already been requested ?)

**Comment by bd0bd** [comment]
>to allow hiding the actual title.. (I'm sure this has already been requested ?)

Yes, I have asked about this before. I have this option in another CMS - you can make "do not show H1 title".

**Comment by markabur** [comment]
> I often have use-cases where I'd like to include html tags in titles.

Same here. In fact, I'm building a D7 site right now where we're using a "Formatted title" field on nodes. It's sort of an academic site where node titles mention publications that need to be italicized. The client likes to use bolding too in titles sometimes. For the actual node title we use Automatic Entity Label module to convert it to plain text. Works fine but it would be nicer without all the complexity.

**Comment by maxmeno** [comment]
I could have used HTML in titles quite a few times with Drupal.
My vote is yes.

**Comment by MrHaroldA** [comment]
I vote no. If you want to use HTML, add a text field (with Ckeditor), and hide the default title-field.

Titles with HTML in it (and images, bullits, etc) would really destroy things like the content overview, or even HTML page titles.

**Comment by Graham-72** [comment]
Although we can use CSS to hide a title or change its style, and we can modify a template to change where a title appears in relation to a menu for example, it would be helpful to be able to include HTML within a title in some circumstances, but I am worried by the possible repercussions mentioned by @MrHaroldA .

**Comment by bd0bd** [comment]
>Titles with HTML in it (and images, bullits, etc) would really destroy things like the content overview, or even HTML page titles.

There are many other ways to destroy almost anything we want to.
But this is a website's developer business and not Backdrop's developers :)
Why to limit me or any body else who would like to have this option?
May be it is better to give them a freedom?
Thank you!

**Comment by MrHaroldA** [comment]
> May be it is better to give them a freedom?

You have that freedom already: add an extra field which accepts HTML ... done. Please leave the plain text (administrative) title alone.

**Comment by quicksketch** [comment]
Having HTML in titles does have all sorts of repercussions, but it should be possible to manage this though the current hooks and preprocessing (though I haven't tried explicitly):

- White list certain HTML tags (either hard-coded or via configuration form).
- Use `hook_html_head()` to strip any present HTML from the `<head><title>` tag.
- Use `hook_preprocess_node()` to decode the specified tags in the `$title` variable (but stripping all others).
- Use `hook_preprocess_views_view_field()` to the decode the specified tags when displaying a title field in views.

It would definitely be complicated to get all the possible situations, but that's one of the reasons why I'd probably prefer to leave this to contrib in the first place.

> I've also needed to include HTML entities, such as for a trademark or copyright symbol. 

In these cases, you can just use the actual trademark or copyright symbols. Although as a web developer, typing an HTML entity might be considered normal, in all most all applications you wouldn't expect to type an HTML entity to get a ™ or © symbol. Recent OS's have also made finding and typing special symbols much easier (e.g. on an Windows, Android, or iOS device via the symbols keyboard). Though generally this is still an issue. Typing these characters is still difficult overall.

**Comment by klonos** [comment]
> ...you wouldn't expect to type an HTML entity to get a ™ or © symbol.

I'm with @quicksketch here. Content authors are usually pretty much lost in "complicated" UIs (that the rest of us find easy by the way - hence the quotes on the word). It would be simply crazy to ask or to expect them to remember and type the html equivalent of ™, © etc.

> Typing these characters is still difficult overall.

What I usually resort to in such cases is google "[trademark symbol](https://www.google.com/search?q=trademark+symbol)" or "[copyright symbol](https://www.google.com/search?q=copyright+symbol)". The search results bring up the definitions from wikipedia that include the characters and I then can simply select and copy-paste them wherever I need to.

**Comment by MrHaroldA** [comment]
I did have some issues with pasting 4-byte emoticons into a Drupal/Webform setup, which yielded in a fatal error because the database was set up to the default 3-byte UTF-8 collation. Haven't tried this in Backdrop yet.

**Comment by bd0bd** [comment]
>You have that freedom already: add an extra field which accepts HTML ... done. Please leave the plain text (administrative) title alone.

I am sorry, may be I have misunderstood.
I talk only about end user title and NOT about admin;s :)

**Comment by MrHaroldA** [comment]
> I talk only about end user title and NOT about admin's :)
Well, the person that has built your website can add such a field in minutes. Transforming a title attribute into an HTML version will take hours.

... and imagine the security implications of contrib modules suddenly get HTML (and javascript, etc) instead of plain text titles.

**Comment by bd0bd** [comment]
>Well, the person that has built your website

I can add it too.
I am already not complete dummy with Backdrop :)
And I am building websites myself since 1997 (or 1996).
But I do not see an option to hide the default H1 title.
In the CMS I have used before Backdrop I could hide default H1 (do not display it) title and write my own H1 title (with HTML tags like span etc) into the body (editors text area).

**Comment by MrHaroldA** [comment]
> But I do not see an option to hide the default H1 title.

1. Copy page.tpl.php to your theme folder
2. Remove the <h1> tag

**Comment by wesruv** [comment]
In the past to do this I've created a companion title field called 'Display Title', that allowed HTML that had an accompanying Title HTML text format. The only place I ever wanted to use this field is the full view mode template, everything else needs a non-HTML title field version.

Putting HTML in the actual title field causes issues in content listings, views, admin areas, and as Nate mentioned the title should show up in the `<head><title>`, which gets weird when you shove HTML in it :stuck_out_tongue: 

I feel like the title field is better off with no HTML.

I'm not saying we shouldn't offer the ability to put HTML in the `<h1>` of a page, just that I'm not a fan of having the existing title field have HTML in it and there isn't a non-HTML version.

**Comment by wesruv** [comment]
This feels a little 'contribby' to me, if nothing else as a poll to see how many people are actually doing this. It doesn't surprise me that us nerds that are participating in the project are, but I'm not sure it's a majority use case.

**Comment by jenlampton** [comment]
> This feels a little 'contribby' to me

me too :)

**Comment by klonos** [comment]
Perhaps for nodes, there should be a "Use content title as page title" checkbox that is on by default. This way, node titles would have the _option_ to be separate from what is printed in the `<head><title>` with the default being as it currently is.

**Comment by jenlampton** [comment]
That's still a contrib problem, and why we have page title module ;)

**Comment by klonos** [comment]
Yep, feels like contrib. If it proves to have great acceptance and considerable usage stats, then we can consider #933 for core.

**Comment by wesruv** [comment]
It'd be cool to have a "Fix in Contrib" label, so people who are interested in making modules but don't necessarily know what people might want can check out a list of things people have been asking about.

Just a thought :smile:

**Comment by klonos** [comment]
Good idea @wesruv! :+1:

**Comment by jenlampton** [comment]
Alrghty, sounds like we've reached a consensus then. Thanks for the feedback :)

**Comment by jenlampton** [comment]
@bd0bd  and @ghost see https://github.com/backdrop/backdrop-issues/issues/1950

**Comment by BWPanda** [comment]
For posterity, here's the Drupal module that would need to be ported: https://www.drupal.org/project/html_title
I may have need to do this soon, so if I get around to it, you'll be able to find the ported version here: https://github.com/backdrop-contrib/html_title
