### ISSUE TITLE
Custom block title in the "Add block" dialog is "Add a custom block" (should just be "Custom block").

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1643]
![backdrop-add_block_dialog-add_a_custom_block_instead_of_plain_custom_block](https://cloud.githubusercontent.com/assets/2423362/13212459/81599a2a-d995-11e5-9c2e-7b1c5c45035d.png)

**Comment by BWPanda** [comment]
This has since been fixed.

**Comment by klonos** [comment]
Yup 👍 ...FTR, it was fixed in #2241, with https://github.com/backdrop/backdrop/pull/1597
