### ISSUE TITLE
Double ?q= instead of / in site information field prefixes when site is configured to be multilingual.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1645]
While trying to test #1638 in order to help @bd0bd, I noticed this (I have a local dev environment on nginx and still haven't figured a way to enable clean URLs):

![backdrop-double_q_on_site_info_field_prefixes](https://cloud.githubusercontent.com/assets/2423362/13217381/23a6f582-d9b6-11e5-809e-e0b9b2db06a3.png)

So, I get `[domain]/?q=[language-code]?q=[field]` when it should be `[domain]/?q=[language-code]/[field]`

**Comment by klonos** [comment]
...the actual URL is rendered correctly with the ```/``` instead of the extra ```?q=``` by the way. I wasn't able to spot this before because I do testing and see admin pages in the English language (which be default has empty language prefix instead of "en" set in the "Determine the language from the URL (Path prefix or domain)." option of site language detection).

**Comment by gifad** [comment]
> haven't figured a way to enable clean URLs

see https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/ ?

**Comment by klonos** [comment]
Thanx @gifad . I have already tried that, but you see my config is a multi dev environment with multiple test sites under ```http://localhost```. So for example I have ```http://localhost/backdrop```, ```http://localhost/drupal7```, ```http://localhost/drupal8```, ```http://localhost/wordpress``` and even ```http://localhost/backdrop133```, ```http://localhost/backdrop13x```, ```http://localhost/backdrop1xx``` etc.

I can get it to work with a single virtual host directly under ```http://localhost``` following those instructions, but they do not work for *all* subfolders under the main ```www``` root (which are different dev sites in my situation). Trust me, I've tried hard and it's not as simple.

**Comment by klonos** [comment]
...anyways this issue here is about the actual UI text bug in situations where either intentionally or not, clean URLs are not enabled.

**Comment by gifad** [comment]
sorry to keep off topic, but did you try http://epiqo.com/en/feed/nginx-clean-urls-drupal-installed-various-sub-directories ?

**Comment by klonos** [comment]
Yep. Pretty much everything that comes up in google when you search "drupal nginx multiple"

**Comment by klonos** [comment]
I cannot reproduce this any more, so i will go ahead and close it as outdated.

Here's what I have tested:

1. Navigate to `/admin/config/urls/settings`
2. Disable the "Enable clean URLs" option
3. Navigate to `/?q=admin/config/system/site-information`
4. Scroll to the "FRONT PAGE" and "ERROR PAGES" sections

PS: noting that I am using apache now, so this might still be an issue with nginx.
