### ISSUE TITLE
Vanishing menu items?

### ISSUE THREAD

**Issue by maxmeno** [backdrop/backdrop-issues#1647]
1) Create a new content type, leaving "Menu settings" non enabled (it will probably go into Primary navigation, but I don't have a complete menu structure yet - it can wait, right?); save.

2) Create nodes with the new content type and manually add a menu item; save. Everything looks fine, menu is updated and works as expected.

3) Edit content, save: the corresponding menu item is gone.

Is this a bug or what?

**Comment by quicksketch** [comment]
Hi @maxmeno! Thanks for filing this issue. I didn't reproduce it immediately but when I make a menu item *manually* (as you said) at `admin/structure/menu/manage/main-menu` and then re-edit the node, you're right that the menu item disappears. Definitely a bug.

This issue probably originates somewhere in `menu_node_prepare()` or `menu_node_save()`, where we normally create menu items that are associated with nodes. My guess is that the menu item the is manually created is associated with the node, but when it's not shown on the node form, saving the node acts as though the menu settings were deleted, even though they were just absent from the node form.

**Comment by quicksketch** [comment]
Pull request filed at https://github.com/backdrop/backdrop/pull/1270. It's a simple fix of just making sure the lack of form elements on the node form doesn't result in the deletion of associated menu items.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/1270. This will be in 1.3.3.
