### ISSUE TITLE
Notice : Undefined property: stdClass::$langcode in locale_language_url_rewrite_url()

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1653]
full message : 
`Notice : Undefined property: stdClass::$langcode dans locale_language_url_rewrite_url() (ligne 436 dans /.../backdrop/core/includes/locale.inc).`

Just after enabling language and locale modules, default options, and import drupal-7.41.fr.po

The error occurs only when requiring "Flush all caches", and only from some (not all) content pages.

The offending line is 

```
  // We allow only enabled languages here.
  elseif (!isset($options['language']->langcode)) {
```

I can't provide more information : devel tools induces infinite loop, but at least I have a stack trace : 

```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in .../backdrop/modules/devel/devel.module on line 457
PHP Stack trace:, referer: http://macjf.local/backdrop/page/basic-page-upload
1. {main}() .../backdrop/index.php:0
2. backdrop_bootstrap() .../backdrop/index.php:20
3. _backdrop_bootstrap_full() .../backdrop/core/includes/bootstrap.inc:2579
4. backdrop_theme_initialize() .../backdrop/core/includes/common.inc:5606
5. backdrop_add_js() .../backdrop/core/includes/theme.inc:126
6. url() .../backdrop/core/includes/common.inc:4358
7. backdrop_alter() .../backdrop/core/includes/common.inc:2419
8. locale_url_outbound_alter() .../backdrop/core/includes/module.inc:1139
9. locale_language_url_rewrite_url() .../backdrop/core/modules/locale/locale.module:914
10. dpm() .../backdrop/core/includes/locale.inc:430
```

Then it loops, because dpm() calls backdrop_add_js(), which is the first suspect (calling url() before languages are initialized?)...

Note that, once the cache are reloaded, everything works OK, until the next flush (well, about 1 out of 5).

Now, I just disabled "Determine the language from the URL (Path prefix or domain).", and did not receive more notices...

[Side note : French translation states 4696/7090 (66.23%) - for the end user, that's pretty much everything except Layout stuff, "Text editors and formats", and, curiously, "User accounts")]

**Comment by quicksketch** [comment]
Thanks @gifad for filing this issue.

> The error occurs only when requiring "Flush all caches", and only from some (not all) content pages.

I tried reproducing this problem, but the number of unknowns is making it difficult to track down. I setup a multilingual site, imported the French .po, left on the default path-based domain detection, then tried flushing the caches a bunch of times on different pages, but I couldn't reproduce getting a notice. More information on this would be appreciated if it can be reproduced reliably.

**Comment by gifad** [comment]
Well, I've ~~localized~~ located the root of the issue : The Pathologic filter calls url() on every link, after parsing and reconstructing path, with a fully qualified 'options' argument rebuilt 'by hand'; the bug could be here, although the offending part of the language property is obtained from `language_url_split_prefix()`.
On my dev site, I have no kind of local prefix, everything is 'und'.
Does 'und' have a $langcode ?

Note that the bug persists if the site is switched back to engish default language

**Comment by gifad** [comment]
This is both a workaround (fix ?) and a investigating aid : 
```
diff --git a/core/includes/locale.inc b/core/includes/locale.inc
index ec01d0d..2ad9265 100755
--- a/core/includes/locale.inc
+++ b/core/includes/locale.inc
@@ -433,6 +433,11 @@ function locale_language_url_rewrite_url(&$path, &$options) {
     $options['language'] = $language_url;
   }
   // We allow only enabled languages here.
+  elseif (!isset($options['language']->langcode)) {
+  //ddebug_backtrace();
+    unset($options['language']);
+    return;
+  }
   elseif (!isset($languages[$options['language']->langcode])) {
     unset($options['language']);
     return;
```

**Comment by gifad** [comment]
Found it
Once again, Backdrop developpers showed their intellectual superiority by renaming language to langcode.
Bullshit, if you ask me.

**Comment by quicksketch** [comment]
> Once again, Backdrop developpers showed their intellectual superiority by renaming language to langcode.

I admit we made a mistake by using an early D8 version rather than the latest D7 at the time of the fork. We included all D8 commits up until Feb 29, 2012, which included some API changes like the switch from `language` to `langcode`. Some API changes we reverted (like `$GLOBALS['language']` was renamed to `$GLOBALS['language_interface']` in D8, then we put it back).

Anyway, I'm trying to say that we'll avoid such changes in the future. It was a side-effect of having gone with D8 instead of D7 as the initial forking point. I'm sorry it caused frustration, it's the sort of thing we're specifically trying to prevent.

**Comment by docwilmot** [comment]
> Once again, Backdrop developpers showed their intellectual superiority by renaming language to langcode.
Bullshit, if you ask me.

Rude, if you ask me.

**Comment by klonos** [comment]
> Rude, if you ask me.

Dito.

**Comment by gifad** [comment]
@docwilmot, @klonos : I spent most of the night searching this issue; It was 4am local time when I found it was not a bug, but a ***** - I took the time to buid and submit a PR to the Pathologic project to fix the issue, but I was too tired to find a better translation for *****
now you can choose : [*****](http://dictionary.reverso.net/french-english/connerie)

@quicksketch : thanks for understanding my mood
two side notes : 
- search core for ->language - I'm not sure they all apply to a User object - particularly $entity->language is suspect.
- about mood and words, it reminds me a blog post you probably read : http://jacine.net/post/101348015393/2-years-later-my-experience-as-a-drupal
context is totally different, but I'm sorry to feel that backdrop is already in the same state as drupal was 2 years ago : grab the "likes", and completely forget the end users
