### ISSUE TITLE
Notice: Undefined property: TaxonomyVocabulary::$vid in value_form()

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1657]
(line 129 of /home/www/backdrop/core/modules/taxonomy/views/views_handler_filter_term_node_tid.inc)
of backdrop 1.3.3

`$tree = taxonomy_get_tree($vocabulary->vid);` !!

**Comment by herbdool** [comment]
I think it may need to be `$vocabulary->machine_name` such as on line 124, but I haven't tried it. So:

`$tree = taxonomy_get_tree($vocabulary->machine_name);`

**Comment by BWPanda** [comment]
THis has since been fixed in https://github.com/backdrop/backdrop/commit/6a1ca18136870adca917f2787d8040ac2ccaa3fc

**Comment by klonos** [comment]
...as part of #2013
