### ISSUE TITLE
Use words, not numbers, for core layout names

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1658]
`1 column` should be `One column`, and `2 columns` should be `Two column`, and `3/3/4 columns` needs a better name :smile: 
Has always annoyed me.

**Comment by klonos** [comment]
Yes, but these are sorted alphabetically AFAICT. So you'd end up with:

Four column
One column
Three column
Two column

...that might be annoying to others (ahem ...myself).

**Comment by docwilmot** [comment]
We've changed default layouts, so closing.
