### ISSUE TITLE
Unable to pass attributes into theme_menu_tree.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1661]
Today I was unable to pass classes into `theme_menu_tree` in order to mark a menu as being a drop-down. This is because we have this function in core:

``` php
function template_preprocess_menu_tree(&$variables) {
  $variables['tree'] = $variables['tree']['#children'];
}
```

Here we are overwriting all the information we need (`tree`) with the contents of the child element, preventing anything else from being passed into the theme function.

Since we need to assure we don't break themes in the 1.x cycle, the proposed solution is as follows:
1) update `hook_theme` in common.inc:

``` php
    'menu_tree' => array(
      'render element' => 'element',
    ),
```

2) update the preprocess function to match.

``` php
function template_preprocess_menu_tree(&$variables) {
  $variables['tree'] = $variables['element']['#children'];
}
```

This will leave the `tree` varaible the same as it was before, but also allow additional information to be passed through via `element`.

**Comment by quicksketch** [comment]
I closed the PR at https://github.com/backdrop/backdrop-issues/issues/1661 because it contained a bunch of things not related to theme_menu_tree() as far as I could tell. Could you make a new one?

**Comment by jenlampton** [comment]
I think this is a non-issue now that we have the responsive menu in core. CLosing.
