### ISSUE TITLE
[UX] Do not "hide" notification badges on mobile.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1665]
This is a follow-up to #639...

This what people get on regular screen size:

![backdrop-notification_badge-admin_bar_normal](https://cloud.githubusercontent.com/assets/2423362/13382628/7a6a6658-decd-11e5-8b48-ee5f56914dbf.png)

...and this is what they get on mobile:

![backdrop-notification_badge-admin_bar_mobile](https://cloud.githubusercontent.com/assets/2423362/13382672/c8c95362-dece-11e5-82da-0fcaa1545524.png)

...site status appears perfectly fine. No notification badge or anything... until they expand the admin bar menu, only to find out that there are errors that require their attention that have been "hiding" buried away from their view:

![backdrop-notification_badge-admin_bar_mobile-expanded](https://cloud.githubusercontent.com/assets/2423362/13382686/11589cdc-decf-11e5-8b7e-7ec9a64e8a2f.png)

Can we please do either of these (or any other ideas?):

- duplicate the badge on the main admin bar area to the right of the "Admin bar" menu item *additionally* to having it next to the "Site status" menu item
- have the badge on the main admin bar and use JS to *move it* to the "Site status" menu item when the user expands the menu:

![cat-chasing-laser](https://cloud.githubusercontent.com/assets/2423362/13382692/43dd62aa-decf-11e5-82a4-3a3d98ad1c82.gif)

**Comment by klonos** [comment]
If we go with the laser-chasing cat idea, I think we should implement that for the regular-sized admin bar on wider screens.

Note: I claim the term "laser-chasing" as a personal trademark from here forth, used as a metaphor to describe similar UI implementations. Similar to "[bike-shading](https://en.wikipedia.org/wiki/Law_of_triviality)".

**Comment by gifad** [comment]
Thanks @klonos : you made me discover a security vulnerability in backdrop : it checks that "Access to update.php" is protected in `$GLOBALS['update_free_access']` (the drupal way) whereas it had relocated it in `$GLOBALS['settings']['update_free_access']`.
No more comment (for once)
Oh wait, the status indicator should be blinking, bouncing, or whatever, for a better UX

**Comment by klonos** [comment]
@gifad : please excuse m e for removing your comment. I see no other way to do this. I have made a local copy of your text and will restore it here once the issue is sorted. Please see my comment on the other issue you have opened for the reason why.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/1521 that moves our status indicator. FYI currently we don't show the alert next to "Site status" in the menu, it's only shown at the top level. So to reduce the scope of this request a bit, I just moved the indicator out of the menu and into the top level, where it now is displayed all the time regardless of the window size.

![screenshot from 2016-09-06 21-44-49](https://cloud.githubusercontent.com/assets/100206/18300124/36a2e1b8-747b-11e6-93ee-3e18167e53c0.png)
![screenshot from 2016-09-06 21-45-00](https://cloud.githubusercontent.com/assets/100206/18300125/3955021a-747b-11e6-8cbe-60db4eafcb75.png)

**Comment by quicksketch** [comment]
Can be tested at:

Website: http://1521.backdrop.backdrop.qa.backdropcms.org/admin/reports/status
Username: admin
Password: oWFPbUY2

Please don't actually run the database updates, or the indicator will go away. :wink:.

**Comment by jenlampton** [comment]
Can we also fix the latest 1.x in this PR? For me the status indicator is in a funny place: between `Configuration` and `Development` instead of to the right of `Reports`.
![screen shot 2016-09-06 at 11 38 39 pm](https://cloud.githubusercontent.com/assets/397895/18302212/49b58278-748b-11e6-800f-df11d7e08e6a.png)

**Comment by serundeputy** [comment]
This working as expected for me.  I tested in the sandbox and pulled down `git pull https://github.com/quicksketch/backdrop.git 1665/admin_bar_always_alert` locally against current `1.x` head.

@jenlampton I am not seeing what you are in the screenshot, but I also do not have a `Development` separate menu item.

From my perspective this is RTBC.  @jenlampton I think your court.
<img width="829" alt="screen shot 2016-09-08 at 6 45 28 pm" src="https://cloud.githubusercontent.com/assets/6763671/18369592/beabc730-75f4-11e6-8dfc-a0e6b3ae8014.png">

**Comment by jenlampton** [comment]
Well let's not worry about that here then. I'll poke around and make a new issue :) thanks for checking on it @serundeputy !

**Comment by serundeputy** [comment]
Thanks everyone!

This is merged into `1.x` and will ship with `1.5.0`.
