### ISSUE TITLE
[UX] Implement a Dashboard or Notification/Action Center feature.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1666]
This is a follow-up issue to #639...

Some really nice ideas were born and suggestions made about such a thing over in the parent issue. Since the main feature of that issue (notification badges for error messages) was implemented, and in order to close that issue, lets move the mockups from there and continue the discussion on that topic in this issue here.

**Comment by docwilmot** [comment]
Dupe https://github.com/backdrop/backdrop-issues/issues/495
