### ISSUE TITLE
[issue title removed]

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1667]
[comment removed]

@gifad : sorry about taking the liberty to do this. I still made a local copy of your comment and will restore it here once the issue is either sorted or deemed to not be a security issue. Please see my comment bellow on how we deal with security issues in Backdrop (it's the same policy in Drupal).

**Comment by klonos** [comment]
@gifad https://backdropcms.org/security :

> If you have discovered a security issue with Backdrop CMS, please contact the Backdrop Security Team directly at security@backdropcms.org. We manage security issues separately in a private repository until the issue has been resolved. Even if you're not sure if it's a security problem, please contact the security team before filing an issue, blogging, or tweeting about it.

**Comment by klonos** [comment]
I'm guessing this is already being handled internally, so OK to close. @quicksketch?
