### ISSUE TITLE
Secondary tabs translation

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1669]
Secondary tabs translation are not following user preference
Steps to reproduce : enable locale module, install and umport a foreign language, make it default language.
Set up detection / selection to only 'Follow the user's language preference.'
Now edit a user account, to speciy language as 'English'.
For this user, everything is back to english, except secondary tabs, as shown below
![capture d ecran 2016-02-29 a 20 09 56](https://cloud.githubusercontent.com/assets/15943462/13405996/7ff64980-df21-11e5-84f8-439e412002ef.jpg)

**Comment by gifad** [comment]
Well, the problem is no more reproducible, this seems to be a caching issue.
Not caching cleared by "Flush all caches", but the delay indicates this could be tempstore related…

**Comment by BWPanda** [comment]
Closing old issue.
