### ISSUE TITLE
Main tab on Reports page is displayed as “List Fields”

### ISSUE THREAD

**Issue by dboulet** [backdrop/backdrop-issues#1670]
I noticed on my site that the structure of the tabs on the Reports page were not displaying properly, the main tab is displayed as “List Fields”, with another tab next to it labelled “Used in Views”. I discovered that the “List Fields” report is provided by the Field UI module, while “Used in Views” is provided by the Views UI module. In my case, I have the Field UI module disabled, so the intended structure of the tabs gets broken because the parent page no longer exists.

![screen shot 2016-02-29 at 4 03 10 pm](https://cloud.githubusercontent.com/assets/208615/13410539/fb6d0cd0-defd-11e5-9976-c27f50f08dc1.png)

**Comment by serundeputy** [comment]
Thanks @dboulet 

I pulled down the patch: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1279.patch
and applied it.  It works as advertised.  

RTBC

**Comment by quicksketch** [comment]
Thanks @dboulet and @serundeputy!
