### ISSUE TITLE
Layouts: allow the path field to be multi-value

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1671]
I'm running into issues with layouts where I often wish I could have more than one set of path matches.  For example, I want the same layout on the page `user/login`, `user/password`, and `user/%/edit`.

If we could make the path field be an (optional) multi-value field then we wouldn't need to build three of the exact same layout, and update all three when a single change needs to be made.

**Comment by docwilmot** [comment]
Dupe https://github.com/backdrop/backdrop-issues/issues/1528

**Comment by klonos** [comment]
Right.
