### ISSUE TITLE
The 'operations' element is missing in the Form API Reference?

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1675]
While checking #1174 I saw the 'operations' form element type, but it's missing from the Form API Reference found at https://api.backdropcms.org/form_api

I specifically want to know if there's an option to backdrop_valid_path() all links in it; or if I should add that ;)

**Comment by BWPanda** [comment]
Thanks for reporting this @MrHaroldA! I've copied this issue to the API issue queue where we manage the Form API page: https://github.com/backdrop-ops/api.backdropcms.org/issues/103
