### ISSUE TITLE
Add the 'Multiple selects' widget to core?

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1676]
The Drupal module [Multiple Selects](https://www.drupal.org/project/multiple_selects) fixes the incomprehensible multi select widget found in Backdrop core.

The default widget lacks ordering your selection, and most importantly: less educated users don't understand how to select multiple items.

The Multiple Selects widget fixes this:
![multi_select](https://cloud.githubusercontent.com/assets/695291/13425960/bc27bb58-dfaa-11e5-9457-60b6db39232c.png)

Yes, it's perfectly portable from Drupal 7 to Backdrop, and yes, it could live in contrib. But this really ups usability of a very common widget.

Thoughts on adding this to backdrop core?

**Comment by klonos** [comment]
I like Multiple Selects and I have used it in some sites in the past, but when it comes to adding it in core I have better suggestions. Before I list these, I'd like to take some time to re-review these modules and see if any better alternatives have come to life.

My concerns are that any UI improvement that gets into core should be as user-friendly as possible and a major factor of that is reduction of required clicks to achieve things while the solutions should also work good on mobile/touch devices (no mouse or keyboard to ctrl+select elements).

@MrHaroldA I'd like to take this chance to point you to the related #1005

**Comment by markabur** [comment]
Does Multiple Selects restrict each option to only being added once? If not, it's not really doing the same thing. 

I agree that the default multiple-select widget is a pain to use, and I wouldn't want to expose my clients to it. Sometimes in the past that has meant installing Better Select module so that it turns into a set of checkboxes (which does prevent duplicate selections).

**Comment by docwilmot** [comment]
Also see [this issue requesting Select2](https://github.com/backdrop/backdrop-issues/issues/459). Beats Multiple Selects for me.

**Comment by MrHaroldA** [comment]
Select2 is interesting too! Maybe even far more interesting, since it can tackle a lot of widget types instead of only one ...

There's a recent [Drupal 7 module](https://www.drupal.org/project/select2) which might be easy to port?

**Comment by laryn** [comment]
Closing per the comments above. Reopen if I am wrong in this.
