### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'layout_condition_edit_form' not found or invalid function name in backdrop_retrieve_form() (line 850 of core/includes/form.inc).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1680]
I see this php error in my logs:

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function
'layout_condition_edit_form' not found or invalid function name in backdrop_retrieve_form()
(line 850 of C:\www\backdrop\core\includes\form.inc).
```

Location: http://localhost/backdrop/?q=system/ajax
Referrer: http://localhost/backdrop/?q=admin/structure/layouts/manage/default

**Comment by docwilmot** [comment]
Youre not still using the codebase from my faulty #1022 are you? That's missing `layout_condition_edit_form()`

**Comment by klonos** [comment]
You are right. These log entries are from back in Feb 22 when I was testing the PR. Sorry for the noise :smile:
