### ISSUE TITLE
[UX] Change the page title for the detailed view of a log entry to "Log entry details"...

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1684]
...or something that makes better sense. I know this is a very minor nit, but having it plain "Details" does not tell me anything by looking at the tab when I have multiple open in my browser.

I would even better like it if we were even more verbose and had the title include the log entry number. Like so: "Log entry 123 details"

...that would account for cases where one has multiple such entries pages opened in multiple tabs in their browser:

![backdrop-log_entry_pages_opened_in_multiple_browser_tabs-title_details_for_all_of_them](https://cloud.githubusercontent.com/assets/2423362/13480481/3d0aa1ee-e132-11e5-8367-e1cfec1cd84a.png)

**Comment by BWPanda** [comment]
Agreed. Here's a PR: https://github.com/backdrop/backdrop/pull/3062

**Comment by findlabnet** [comment]
'Log message #40759 details', or 'Details of log message #40759' looks better, isn't?

**Comment by herbdool** [comment]
Has relevant test failure.

**Comment by BWPanda** [comment]
PR updated, tests passing.

**Comment by klonos** [comment]
Is `'title'` in `hook_menu()` entries automatically being passed through `t()`? I think so, but I just want to make sure.

**Comment by indigoxela** [comment]
> Is 'title' in hook_menu() entries automatically being passed through t()?

Yes it is.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼  ...I should have checked myself really:

> - "title callback": Function to generate the title; defaults to t(). If you require only the raw string to be output, set this to FALSE.
> - "title arguments": Arguments to send to t() or your custom callback, with path component substitution as described above.

**Comment by klonos** [comment]
> 'Log message #40759 details', or 'Details of log message #40759' looks better, isn't? 

I think that `Log message #123 details` is better.

**Comment by BWPanda** [comment]
PR updated:

![image](https://user-images.githubusercontent.com/2385329/155818969-f9deb1e1-714a-4225-ad6d-a93da804f1f5.png)

**Comment by bugfolder** [comment]
Tested the PR.

Before:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/1f97bb8b-d94a-4e4f-8f10-fd9c2dcb1fc9)

After:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/3e65518d-41de-48eb-a54a-7a12e3b257a3)

WFM (and a nice improvement!). Code reviewed, LGTM.

**Comment by laryn** [comment]
Thanks @klonos for filing this all those years ago, @BWPanda for the fix, and  @bugfolder, @herbdool, @findlabnet, and @indigoxela for your review and inputs. Merged!
