### ISSUE TITLE
Is this the way drop down menu is supposed to work?

### ISSUE THREAD

**Issue by maxmeno** [backdrop/backdrop-issues#1685]
![dropdown](https://cloud.githubusercontent.com/assets/17048579/13490351/5d5aaa76-e12c-11e5-984d-db801c353b6d.png)

Latest BD. 
Primary navigation menu, Bartik theme, no CSS menu editing. 
When I click on one of the main items (ALL CAPITAL link):
1) all the children menu items show up on a second row, pushing the rest of the menu to the right (and I still have 3 or 4 entries to add on the results level)
2) the CSS _active_ state for the main page propagates to all the children items and stays the same even if I go to one of the results pages

**Comment by docwilmot** [comment]
@maxmeno Backdrop's main menu doesnt have a dropdown capability yet. There's an issue for that, hopefully by 1.4.0. For the main menu we recommend either you stick to single-level menus, or you can use the [Nice menus](https://github.com/backdrop-contrib/nice_menus) module from contrib.

**Comment by maxmeno** [comment]
Thanks a lot. 
Downloaded and installed nice_menus (with the usual _Cannot determine the type of project_).

One little glitch (potentially baffling for the average user…) with the module. I suspect that because of this,

`// Otherwise just set a title and move on.
  else {
    // Get the title from the DB since we don't have it in the $menu.
    //$result = db_query("SELECT title FROM {menu_custom} WHERE menu_name = :menu_name", array(':menu_name' => $menu_name))->fetchField();
    $title = 'test'; //check_plain($result);
  }`

I get a "**test**" on the top left corner of the menu `(<span class="nice-menu-hide-title">test</span>).`

How do I get rid of it? Just hide it with CSS?
I can't find a place to change/delete this not really useful menu title.

**Comment by docwilmot** [comment]
Thanks, will need to look at that. haven't updated that module in a very long time. And I should since it seems the only dropdown menu we've got.

**Comment by serundeputy** [comment]
Hi @maxmeno and @docwilmot 

>I get a "test" on the top left corner of the menu (<span class="nice-menu-hide-title">test</span>).

there is an issue:
https://github.com/backdrop-contrib/nice_menus/issues/1

and a patch for that:
https://patch-diff.githubusercontent.com/raw/backdrop-contrib/nice_menus/pull/2.patch

thanks,
~Geoff

**Comment by docwilmot** [comment]
Ahh, missed that. Merged. Thanks.

**Comment by docwilmot** [comment]
Also fixed the project type and created an official release, just so I dont forget.

**Comment by gifad** [comment]
> since it seems the only dropdown menu we've got.

[Cleanish](https://backdropcms.org/project/cleanish) theme has dropdown menus out of the box, with no 3rd party libraries…

**Comment by maxmeno** [comment]
Updated - test is gone. Thanks
One probably minor thing: the wheel to open the block from the page does not work. It shows when I hover on the menu items but it's gone if I try to reach it on the usual corner.

**Comment by quicksketch** [comment]
Thanks guys, it looks like the remaining issues are either in Nice Menus or the core issue to provide drop downs out of box in #1457. Let's close this unless there is an issue that is specific only to this.
