### ISSUE TITLE
Garbage collecting time and file system errors

### ISSUE THREAD

**Issue by maxmeno** [backdrop/backdrop-issues#1686]
A couple of days ago I tried updating **Pathologic** via 
/admin/modules/update
but it failed with the _not being able to identify the project_ warning, or something similar.
So I did a manual update, no problem.

Now, at every cron run I get this in the logs:

> Could not delete temporary file "temporary://pathologic.zip" during garbage collection

How can I get rid of it?

**Comment by serundeputy** [comment]
this is untested, but should be easy to try:

* go to: /admin/config/media/file-system 
  * locate your tmp directory
* go to the tmp directory and make a file called `pathlogic.zip`
* run cron
* see if that makes the garbage collector happy

just a guess :neutral_face:

**Comment by maxmeno** [comment]
temporary directory is indicated as
/tmp
but I can't find it on the server. Was I supposed to create it at installation?

When DB says _This directory should not be accessible over the web._ it means that it should be one level up _outside_ the website folder or just at the root?

I tried creating a tmp directory both ways, uploaded pathologic.zip, run cron but the file still there and the error message in the logs too.

**Comment by gifad** [comment]
If your provider is powered by apache, I'd suggest to define your temp directory as `files/tmp` (no leading /). Backdrop will create it, and insert a dedicated `.htaccess` which makes it _not be accessible over the web_.

**Comment by maxmeno** [comment]
it worked, thanks @gifad 
The zip file got zapped and the error message is gone. And now I know how to correctly config the temp directory….  ;-)
