### ISSUE TITLE
Some contextual link cog wheels disappear when you try to hover over them.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1689]
~~This was reported as a side-note by @maxmeno over at https://github.com/backdrop/backdrop-issues/issues/1685#issuecomment-192254025:~~

~~>... One probably minor thing: the wheel to open the block from the page does not work. It shows when I hover on the menu items but it's gone if I try to reach it on the usual corner.~~

...and I happened to notice it as well while trying to test @wesruv new front-end theme:

![backdrop-contextual_links_disappearing_on_hover](https://cloud.githubusercontent.com/assets/2423362/13539790/ae3be0a6-e2a6-11e5-8ce6-302de26e8990.gif)

For me it seems to occur when contextual links happen to overlap and it looks like a z-index issue. Also notice in the screencast above that the second cog wheel on the pair that seem to have the issue is always in a hover-over state while visible *and* it seems to vanish completely after a certain breakpoint.

@maxmeno is this the same thing as what you described in the other issue? Also, does it happen for you on every contextual link or only for some? If so, then do these links happen to overlap with other ones?

**Comment by maxmeno** [comment]
> @maxmeno is this the same thing as what you described in the other issue?

No, it's the first time I see this in BD

> Also, does it happen for you on every contextual link or only for some? 

Just for the menu block, after installing the new release of nice_menus - I'm sure the wheel for that block was working as expected, before

> If so, then do these links happen to overlap with other ones?

No, the behaviour is different from what I see in your animation. The wheel is visible when the mouse is on any menu item and disappears as soon as I move away from those. Moving the pointer around the corner area where it should be does not bring it back

**Comment by klonos** [comment]
Ah, ok then. Separate issue.

**Comment by klonos** [comment]
Nope, not at all. Closed.
