### ISSUE TITLE
Layout UI: Page title type drop-down label says "Block title type"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1692]
I'm sure I have mentioned this before in some other issue and I was under the impression that I had already filed an issue for it, but I can find anything right now. Anyways, here's the thing:

![backdrop-layout_edit_form-page_title_type_drop-down-wrong_label](https://cloud.githubusercontent.com/assets/2423362/13552972/9061cf48-e3cb-11e5-9bca-e04d4954e4c4.png)

**Comment by quicksketch** [comment]
Merged into 1.x for 1.4.0. We've already made 1.3.6 (the last 1.3.x release), so this won't be included in previous versions.
