### ISSUE TITLE
How to get the UUID of a custom stand-alone block without block_load().

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop/backdrop-issues#1693]
I have a module that makes a block.  The block has an image upload field. In hook_block_save I need to save the image `file_save` AND `file_usage_add`.  As per the Backdrop API, `file_usage_add` requires the $id of the object that is referencing the file.  In D7 I could use `block_load` to load and get the $id of the block, ie.:

```
$block = block_load('bs_block_funnel','bs_block_funnel_1');
file_usage_add($file, 'bs_block_funnel', 'block', $block->bid);
```

However... `block_load` is NOT in the Backdrop API docs so assuming... gone? (and not working in code)

I found `block_custom_block_load` but using this code:

`$block = block_custom_block_load('bs_block_funnel','bs_block_funnel_1');`

PHP is complaining there is no `$block->bid` reference... And... I can't `var_dump($block); die();` to see whats in it because its a modular window...

Is: `$block = block_custom_block_load('bs_block_funnel','bs_block_funnel_1');` the right way to load a custom block and... how to get the $id of this block.

**Comment by serundeputy** [comment]
There is no `bid` PHP is correct.
You can see the contents in your active config directory: `block.custom.bs_block_funnel.json`, but there is no `bid` there either as the custom blocks are now stored in json config.

Here is an example custom block json file:

```json
{
    "_config_name": "block.custom.fe",
    "delta": "fe",
    "info": "fe",
    "title": "",
    "body": {
        "value": "<p>k</p>\n",
        "format": "filtered_html"
    },
    "description": "A reusable custom block."
}
```
 if you put this statement:

```php
$block = block_custom_block_load('bs_block_funnel','bs_block_funnel_1');
```
into `template.php` you can then `var_dump` or `dpm` (for dpm you have to install [devel](https://github.com/backdrop-contrib/devel) module).

Unfortunately this information confirms what you are seeing, but does not solve your problem.

**Comment by JugglingCoder** [comment]
Thank you for your reply serundeputy.
I may be creating the module incorrectly as I have no config file in "/active" called "block.custom.bs_block_funnel.json" ( but I do have one called "bs_block_funnel.settings.json" for the module ).... and thanks for "if you put this statement in template.php" ... I should have thought of that:) pretty basic.
Anyways... it doesn't matter if I have a "block config" file because as you know... that file doesn't have an $id of the block (as shown above).
So... how is it possible to use an image upload field in a block if "file_usage_add" [ https://api.backdropcms.org/api/backdrop/core!includes!file.inc/function/file_usage_add/1 ] requires an $id of the block it is referencing when the block doesn't have an $id??

**Comment by jenlampton** [comment]
@JugglingCoder can you use the block's UUID instead? Does it need to be a numeric ID, or can iut be a long hash?

You might also look at how images are inserted via the editor, as I think this same `file_usage_add` problem was addressed there.

**Comment by BWPanda** [comment]
No further info, closing.
