### ISSUE TITLE
[UX] Reorder the filter widgets of the manage content view to be consistent with the columns.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1695]
This is basically the same as https://www.drupal.org/node/2001922 and part of #1694 

Here's a before/after screenshot:

![backdrop-manage_content_view-reorder_exposed_filer_widgets](https://cloud.githubusercontent.com/assets/2423362/13557313/44a8a870-e442-11e5-8441-20adb5d1d248.png)

**Comment by klonos** [comment]
...over in the d.org issue, some people suggested the following that we should perhaps consider:

- add an author autocomplete filter
- change the title search filed to be searching in the body as well

**Comment by klonos** [comment]
...the "Published" filter should perhaps change to "Status" and the options instead of yes/no, be published/unpublished/scheduled (to accommodate for #857).

**Comment by BWPanda** [comment]
Good idea! Here's a PR: https://github.com/backdrop/backdrop/pull/3351

**Comment by indigoxela** [comment]
Indeed, a good idea. This is what it looks like in the sandbox. (Note, the "New/updated content" checkbox didn't exist yet when this issue was opened.)

![content-view](https://user-images.githubusercontent.com/842066/95014624-5f3a4b80-0648-11eb-9a91-f3046004a317.png)

**Comment by stpaultim** [comment]
It looks like this is eligible for a Bug Fix milestone. So, I'm doing that. 
https://backdropcms.org/user-guide/adding-milestones-to-issues

**Comment by BWPanda** [comment]
@stpaultim What makes you say that?

**Comment by stpaultim** [comment]
> @stpaultim What makes you say that?

@BWPanda - I assume you mean my comment about the milestone. Nothing specific about this issue. But, to be honest - I don't always remember what the criteria are for marking an issue with a Milestone. So, my goals were:

1) To give folks a chance to correct me if I'm wrong. 
2) To share a link to the documentation for others (new people) that might not fully understand or remember the criteria for giving an issue a milestone. 

After the contribution day last week, I'm thinking more about new people and how to make things/processes as transparent and visible as possible to educate new contributors.

**Comment by BWPanda** [comment]
@stpaultim Yeah I often get mixed up with the milestone requirements. The link's handy though, thanks.
I think you're wrong, but I wanted to confirm your reasoning before saying anything :slightly_smiling_face: 

Bug fixes need the bug milestone label (this had the minor milestone label). Maybe what you could do is change the milestone labels, then see if someone else agrees and adds the bug milestone label themselves...

**Comment by stpaultim** [comment]
Sure, I can do that. I think that this could be a bugfix issue - as it's more of a task than it is a new feature. But, I also think it could wait until the next minor release if people feel better about that. I removed the milestone label and added both minor and bug milestone candidate labels. 

I would say that if a core committer thinks this qualifies as a bug fix / UX issue - we should milestone for that. But, if not - it can be milestoned for minor release if it has an advocate or if it is RTBC. (I don't care either way)

**Comment by indigoxela** [comment]
> I think that this could be a bugfix issue - as it's more of a task than it is a new feature.

If we declare this a task or bugfix, we can add it to the 1.17.2 milestone. "Feature request" doesn't seem accurate anyway.

**Comment by stpaultim** [comment]
Well, since I added the recent milestone candidate tag, I'll let someone else agree with that and give it the actual bug-fix milestone.

**Comment by quicksketch** [comment]
This wasn't in the 1.17.2 milestone yet but it looked great. Thanks everyone for the great suggestion and implementation. I've merged https://github.com/backdrop/backdrop/pull/3351 into 1.x and 1.17.x.

**Comment by klonos** [comment]
Thanks everyone 🙌 ...this is my favorite UX fix in this release. The content listing view is one of the most frequently-viewed pages by end users (content editors), if not THE most frequently-viewed.
