### ISSUE TITLE
Custom blocks copied from other layouts when creating a new one.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1697]
I just tried creating a new layout for testing purposes and noticed that in the main content area there was a custom block that I have created for the default front-end layout. Is this intentional? I consider it a bug because blocks should be carried over to new layouts only when cloning other ones.

**Comment by docwilmot** [comment]
Not-a-bug. New layouts clone Default.

**Comment by quicksketch** [comment]
Yep, it is intentional that all new layouts copy the blocks from the default one. That way blocks such as header and footer match on all new layouts and you don't have to add/re-configure them.

**Comment by klonos** [comment]
Fair enough. It's just that if I need to start with a clone of the default layout, then that'd be exactly what I'd do; use the clone action. If I click "add new", then I expect a "blank canvas". Not a biggie though.
