### ISSUE TITLE
Notification badge should be round, not egg-shaped

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1699]
...or is it just me:

![backdrop-notification_badge-egg-shapped](https://cloud.githubusercontent.com/assets/2423362/13558443/033c08de-e459-11e5-8009-a17753401c68.png)

---
PR from @serundeputy https://github.com/backdrop/backdrop/pull/1514

**Comment by serundeputy** [comment]
I can't tell if it is egg-shaped or if the number is just not vertically centered; :smiley:

**Comment by klonos** [comment]
Probably both.

**Comment by maxmeno** [comment]
I see an egg...

**Comment by gifad** [comment]
try
```
#admin-bar .admin-bar-alert .error-count {
    padding: 2px 6px;
}
```
instead of 3px 6px;
![capture d ecran 2016-03-08 a 13 44 09](https://cloud.githubusercontent.com/assets/15943462/13601975/010bc118-e534-11e5-8892-c751c3ea3f03.jpg)

**Comment by klonos** [comment]
So, it is an egg after all:

![backdrop-notification_badge-egg-shapped](https://cloud.githubusercontent.com/assets/2423362/13558443/033c08de-e459-11e5-8009-a17753401c68.png)
![capture d ecran 2016-03-08 a 13 44 09](https://cloud.githubusercontent.com/assets/15943462/13601975/010bc118-e534-11e5-8892-c751c3ea3f03.jpg)

@gifad thanx, I'll try that next time I get a notification.

**Comment by serundeputy** [comment]
One thing I noticed in manual testing is that when using `Basis` as the front end them it reverts to egg shaped, not so in `Bartik`.  I guess basis is overriding the `Admin bar` css?

So, if `Basis` goes in as default front end theme in `1.5.0` as it currently stands you'll see an egg notification on the front end, but not in admin theme `Seven`.

**Comment by jenlampton** [comment]
Basis should not be overriding admin bar CSS.  I'll add a note in https://github.com/backdrop/backdrop-issues/issues/1361

**Comment by jenlampton** [comment]
I gave this a test and it looks a lot better. Nice work! :)

**Comment by serundeputy** [comment]
This is merged into `1.4.x` and `1.x` and will ship in `1.4.5` and `1.5.0`.

Nice work everyone! thanks.

**Comment by quicksketch** [comment]
The latest code causes Admin Bar to be pushed down a little below the menu items for me, as shown:

![screenshot from 2016-09-10 22-36-50](https://cloud.githubusercontent.com/assets/100206/18415430/17fec34c-77a7-11e6-8e23-f2b6ff3dcd06.png)

See the slim black line below "Development"?

I added a negative margin to the element to keep the additional padding from pushing down the bar, and made the circle badge a little larger. I realize that Linux fonts are a little different than the Mac ones most of us are using, so I may need additional confirmation it looks okay on other environments.

PR: https://github.com/backdrop/backdrop/pull/1534

**Comment by quicksketch** [comment]
Here it is after PR (Mac, Firefox):
![screenshot from 2016-09-11 14-43-42](https://cloud.githubusercontent.com/assets/100206/18420720/328b65f8-782e-11e6-9a25-958721c204bb.png)

**Comment by klonos** [comment]
PR looks good on Win Firefox and Chrome 👍

**Comment by jenlampton** [comment]
Also looks good on Mac FF, Chrome, Safari and Opera. Marking as RTBC.

**Comment by quicksketch** [comment]
Great, pulled the follow-up https://github.com/backdrop/backdrop/pull/1534 into 1.x and 1.4.x.
