### ISSUE TITLE
[UX] Do not redirect to layout list page upon layout save.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1705]
This has been brought up [here](https://github.com/backdrop/backdrop/pull/1234#issuecomment-195110101):

>> @klonos: BTW, I think that we should reevaluate returning to the layout list page upon save - I think that we should have that same behavior as in views where upon save, you are still in the view edit form ...different issue though.

> @jenlampton: I've been thinking the same thing. Is there already an issue for this? If not, can you please create one?

---
~~PR from @klonos at https://github.com/backdrop/backdrop/pull/1540~~
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1553

**Comment by klonos** [comment]
@quicksketch please do not freak out for setting this to 1.5.0. I think that this is a major annoyance that would be gold to be fixed soon. Besides, when I filed that issue back in March, I couldn't do PRs 😄 ...and this seems like a one-liner fix to me. PR coming up...

**Comment by klonos** [comment]
...sorry for the title change. Seems that views redirects back to the views list upon discarding changes (and I think it makes sense that way.).

**Comment by klonos** [comment]
Some tests are failing and I can't figure out what to do. Pointers please?

**Comment by jenlampton** [comment]
okay, taking a look.

**Comment by jenlampton** [comment]
Some of these tests were just expecting to be redirected to admin/structure/layouts. All we have to do is add `$this->backdropGet('admin/structure/layouts');` and they sail smoothly!  doing that now...

**Comment by quicksketch** [comment]
This looks excellent, great job @klonos and @jenlampton. Merged https://github.com/backdrop/backdrop/pull/1553 into 1.x for 1.5.0.

**Comment by klonos** [comment]
> @klonos when you file a PR in the future (or, until we get our bot updated to do this for us) can you add a link to the PR in the first issue in the thread? ...

Yes ma'am. I'll be doing this from now on. And a big thank you for driving this home 👍
