### ISSUE TITLE
[UX] Change contextual menu to top left corner instead of top right

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#1707]
If we changed the contextual gear to be in the top right, we'd reduce the occurrence of [hover issues obscuring contextual menu](https://github.com/backdrop-contrib/basis/issues/7) by A LOT.

Top right corner makes a little more sense visually, but weight against the how unreliable the top right corner can be in web layout and how reliable the top left corner is... I think it'd be wiser to make the switch.

**Comment by quicksketch** [comment]
Sounds good to me. The cog wheel in the top left corner is more likely to interfere/cover other elements as well (such as a block title). The top right corner is also the current pattern in core and having the default theme be consistent with the current pattern would require less thinking for existing Backdrop/Drupal users.

**Comment by quicksketch** [comment]
Sorry I thought this was the Basis theme issue queue. But this is against core? Both Seven and Bartik display the cog wheel for contextual menus in the upper right already. Is the suggestion here to change the default CSS rather than to add the necessary CSS to Basis to make it be in the top right?

**Comment by wesruv** [comment]
Oops, I got it switched. I think it should be in the top left.

**Comment by olafgrabienski** [comment]
Any progression here? When I tested Basis today, I noted also the Contextual Menu Link Issues.

**Comment by wesruv** [comment]
Going to get this in after the release. Code is written, but I want plenty of time for people to test this.

**Comment by bugfolder** [comment]
if we were to do this, it would cause problems with core changes in https://github.com/backdrop/backdrop-issues/issues/5273, which assume top-right.

**Comment by quicksketch** [comment]
I merged in the PR from #5273, which I think largely solves this problem by readjusting the contextual menu cogs if needed. It even handles if there's not enough vertical space by pushing the cog links to the left/right if needed. I think maybe we close this issue which hasn't seen much attention in years, and open a new one if we want further changes to the new behavior of contextual links.
