### ISSUE TITLE
Selecting Language

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1710]
Hi!

Please look at the picture.

When we want to add a new page then by default the Language is **\- None -**.
Well, it is unclear - should I leave it as it is (- None -) or should I select **English** if default and source language (then would be translated to other languages) is English?

Thank you!

![aaa](https://cloud.githubusercontent.com/assets/13515302/13724371/4742707e-e894-11e5-9992-a13e9681e02c.png)

**Comment by klonos** [comment]
Leave it to "none" if you do not intent to translate this specific piece of content. If you do so, then the only options you get after saving that node is to view and to edit it:

![backdrop-node_actions-no_lang](https://cloud.githubusercontent.com/assets/2423362/13726099/7f474026-e90c-11e5-8b1e-18461af61ff6.png)

If you need to translate it, then select a language. If you do so, the you get view, edit and translate:

![backdrop-node_actions-en_lang](https://cloud.githubusercontent.com/assets/2423362/13726100/881557a6-e90c-11e5-932d-bbcf2fae2c8f.png)

You can always edit a page you have created as "none" and switch it to what ever language you want. Then, you will get the "translate" option. So no need to define language until you decide if the page needs to be translated or not.

**Comment by bd0bd** [comment]
@klonos, thank you very much! I have understood you!
