### ISSUE TITLE
Experimental modules (and perhaps themes) in core?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1713]
Drupal 8 has introduced this interesting concept of [experimental modules](https://www.drupal.org/core/experimental) that ship with core and are disabled by default:

![d8-experimental_modules_in_core](https://cloud.githubusercontent.com/assets/2423362/13727611/04c9a7c6-e94d-11e5-84e2-0d2e7764f759.png)

I personally think that this is a really cool thing! We don't have to keep downloading and applying patches or from master branches of separate projects (with no actual releases yet) for features we mean to introduce just to test. Also, because these would be disabled by default, only those seeking for them would enable them. So not much risk there, plus we can get metrics on usage (once we implement that) before including them officially in core.

We could have used this in 1.0.x trough 1.2.x for CKEditor for example in order to get feedback and we can use it now with the new front-end theme that we are putting together.

Thoughts?

PS: somehow related to #378 but not really I think.

**Comment by klonos** [comment]
...we can have it so that their fieldset is collapsed by default and/or perhaps other indicators like red text for the fieldset title or what have you.

**Comment by jenlampton** [comment]
I'm personally against this idea. Though it works for Drupal's principles, it's against Backdrop's.

**We're only putting things in core that will benefit 80% of sites**.  Anything experimental, by definition, shouldn't be in core. If it's a new feature like Big Pipe, it should be introduced (and proven) in contrib first. If it's a usability improvement like inline form errors, it should be applied directly to all of core. 

**We care more about end-users than contrib devs, and more about contrib devs than core devs**. Adding too many more modules will clutter the modules page and be confusing for the first-time user. Providing more than one way to do the same thing will also be confusing all users. Providing two different sets of code for contrib to integrate will be more work for contrib devs. We need to carefully weigh these things against the assumed benefits (making life easier on core testers/developers?) and decide what is more important for our community.

**Comment by docwilmot** [comment]
Agreed @jenlampton

**Comment by klonos** [comment]
Agreed. Closing.

**Comment by klonos** [comment]
...this could be handled in a less "intrusive" way in #3193
