### ISSUE TITLE
"Show all columns" links shown momentarily when collapsing/expanding module category fieldsets.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1714]
I know... nitpicking and most likely we can actually do nothing about it, but filing this issue just in case:

![backdrop-module_category_fieldset-show_all_columns_link_displayed_momentarily](https://cloud.githubusercontent.com/assets/2423362/13727654/f1ade04c-e94e-11e5-9863-0159a4a30f9e.gif)

**Comment by edcaracas** [comment]
Is this bug still open?
I was unable to reproduce the issue on current version.
![Screen Shot 2020-03-04 at 21 47 30](https://user-images.githubusercontent.com/6628306/75946132-d107a800-5e61-11ea-83e7-1dd97cf8152c.png)

**Comment by klonos** [comment]
Yeah, been a few years since; so lets call this one outdated.
