### ISSUE TITLE
Can not edit Views name/description

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1717]
# I have added a new Views - Article.

Then I was going to edit it but it is impossible and I do not understand why?
In my previous website I can edit it - no any problems arise there.

And I think the idea is not good to use **Change** instead of **Edit** (in previous Backdrop version there was Edit). **Edit** is more familiar word in the cases like this one.

![aaa](https://cloud.githubusercontent.com/assets/13515302/13731343/6f5d34a2-e977-11e5-8815-680b7b283d76.png)

**Comment by jenlampton** [comment]
Thanks @bd0bd you just found a bug!

**Comment by bd0bd** [comment]
Hm, how it is possible if there was no any bug before ... :smile:

**Comment by jenlampton** [comment]
*whistles innocently* I likely caused this one as part of https://github.com/backdrop/backdrop/pull/1181.  Sorry, I'll fix it!

**Comment by bd0bd** [comment]
Thank you!
Would be good if you would post here how I could fix it myself.
Thank you!

**Comment by jenlampton** [comment]
The fix is to change line 245 in `views_ui.admin.inc` from
```php
        'href' => "admin/structure/views/nojs/edit-details/$view->name",
```
to
```php
        'href' => "admin/structure/views/nojs/config-details/$view->name",
```

**Comment by bd0bd** [comment]
Thank you! I have fixed it and everything is ok now.

But this is line number 1245 :smile:

**Comment by quicksketch** [comment]
Thanks @bd0bd and @jenlampton! I've merged the fix from https://github.com/backdrop/backdrop/issues/1288.
