### ISSUE TITLE
[UX] Make active vertical tabs more distinctive.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1718]
Before/after:

![backdrop-active_vtab-before](https://cloud.githubusercontent.com/assets/2423362/13731540/dbc77fce-e9bf-11e5-9ac9-808153c367e2.png)
![backdrop-active_vtab-after](https://cloud.githubusercontent.com/assets/2423362/13731539/dbc4171c-e9bf-11e5-8c7f-cfa1bbc552db.png)

Will give a PR a shot...

**Comment by jenlampton** [comment]
:+1:

**Comment by klonos** [comment]
Did you guys notice I'm filing PRs now?

![yes_i_know_suspenders](https://cloud.githubusercontent.com/assets/2423362/13731744/a978b506-e9c4-11e5-9c57-52574a4707bc.jpg)

**Comment by klonos** [comment]
...but I'm a total n00b. How do you make amendments to your PR if you need to add/remove changes?

**Comment by klonos** [comment]
....ahh, yes. Tags/labels. Need to get used to using those too. Thanx @jenlampton :smile: :+1:

**Comment by jenlampton** [comment]
> Did you guys notice I'm filing PRs now?

YES!!!!  congrats, you are now a core developer! 

> How do you make amendments to your PR if you need to add/remove changes?

You can add things to the previous commit with `git commit --amend` and then you will need to force-push to overwrite your branch `git push origin branchname -f`

**Comment by klonos** [comment]
> YES!!!! congrats, you are now a core developer! 

Naaaah, lets start with core themer for now and lets see how my php turns out.

> You can add things to the previous commit with `git commit --amend` and then you will need to force-push to overwrite your branch `git push origin branchname -f`

How about if you are a total/lame n00b and use the GitHub web interface to edit files?

**Comment by jenlampton** [comment]
> Naaaah, lets start with core themer for now and lets see how my php turns out.

Themers are developers too.  We don't discriminate here. You write code. You are a developer!!!

> How about if you are a total/lame n00b and use the GitHub web interface to edit files?

Can you copy/fork your current PR to make a new one, and then close the first?

**Comment by klonos** [comment]
> You write code. You are a developer!!!

Ooh, stawp it now
![stawpitnow](https://cloud.githubusercontent.com/assets/2423362/13731880/8f1328fa-e9c8-11e5-97eb-09addae954d5.gif)

**Comment by klonos** [comment]
> Can you copy/fork your current PR to make a new one, and then close the first?

Yep. done so already. Thanx.

**Comment by quicksketch** [comment]
So great!! Thanks @klonos!

Merged in https://github.com/backdrop/backdrop/commit/746a181f2d0db4eeff046023bdc05a554b90a5d5.

**Comment by quicksketch** [comment]
Technically this is a feature request and not just a bug, but I got excited and merged it in for the next bugfix release, 1.3.4. I don't think anyone will mind.

**Comment by klonos** [comment]
Technically. I made a :hankey: tsk tsk tsk: https://github.com/backdrop/backdrop/pull/1295
