### ISSUE TITLE
[META] [UX] Make sure the Backdrop admin UI works in RTL locales.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1719]
While playing around with some UI enhancements, I realized a few places where our RTL does not work as it should. These are quite a few places and I'm sure more will come up, so this is the place to keep track of it.

List with separate issues coming up...
- [ ] ...

**Comment by jenlampton** [comment]
:+1:

**Comment by klonos** [comment]
I have found that there are so many places in Seven that have RTL issues, that trying to maintain a list of them in a single place would not be productive. I think that it's OK to close this issue here, since we are already using `RTL` in the titles of the respective issues.

There are 3 ways that I can think of that would help knock these issues down:

- Engage members of our community that speak/use RTL languages so that they contribute more. They don't have to code or submit PRs; filing GitHub issues with screenshots would be great help. To that end, kudos to @shabibalm for all the RTL-related issues they've filed + the suggestions for fixes 👍 

- If already active members of the community have the energy/capacity, they should try switching (some of) their test/dev environments to RTL permanently. Using the admin UI in RTL all the time really helps catch these problems. You can achieve permanent RTL by:
    1. enabling the Language core module
    2. adding an RTL language such as Arabic or Hebrew
    3. making that language the default

    ...**this will retain the English language in the UI**, but switch the phrases/paragraphs to RTL. So you will still be able to navigate 😉

- When reviewing code, watch for left/right padding/margin and float declarations in CSS. If these exist for the regular LTR CSS, then there should be RTL counterparts.

- When testing PRs, switch the sandbox to RTL using the steps mentioned above ^^
