### ISSUE TITLE
Footer: Contextual link text bleeds out of the contextual link pop-down.

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1720]
![footer](https://cloud.githubusercontent.com/assets/13515302/13814902/5ad1d6fe-eb99-11e5-86a2-4dc8b98a9f5b.png)

**Comment by klonos** [comment]
The offending CSS rule is https://github.com/backdrop/backdrop/blob/1.x/core/themes/bartik/css/style.css#L996. When removed, the contextual text is kept within the wrapper:

Might give a PR a try. Hold on...

**Comment by klonos** [comment]
I ended up using a more specific rule in ` core/modules/contextual/css/contextual.css` that negates the offending rule in `/core/themes/bartik/css/style.css`. I think it's more appropriate that way.

**Comment by quicksketch** [comment]
Thanks @bd0bd for reporting and @klonos(!) for fixing! Merged in https://github.com/backdrop/backdrop/pull/1289. This will be in 1.3.4.

**Comment by klonos** [comment]
Yay! My first actual core commit!!! :tada:
