### ISSUE TITLE
backdrop_is_html() does not recognize X-Requested-With HTTP header.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1727]
If a client script issues a regular `$.ajax()`, or `$.getJSON()`, `backdrop_is_html()` fails to recognize X-Requested-With, because it checks `$_SERVER['X_REQUESTED_WITH']` instead of `$_SERVER['HTTP_X_REQUESTED_WITH']`.
This is in bootstrap.inc, line ~3810

The first effect is to insert/append an unexpected full rendered layout in/to the response (see `layout_route_handler()`), which is hardly accepted by the client script...

BTW, this explains why some contrib modules ported from drupal had to add a `backdrop_exit();` after a `backdrop_json_output();`, for instance.

**Comment by quicksketch** [comment]
Thanks @gifad! This was fixed as part of https://github.com/backdrop/backdrop/pull/1290.

> BTW, this explains why some contrib modules ported from drupal had to add a backdrop_exit(); after a backdrop_json_output();, for instance.

Oh great! Yay two problems solved at once. Please reopen if this problem still seems to be an issue with the latest code. This will be in 1.3.4.
