### ISSUE TITLE
notification icon re-appears on cache-clear, disappears when visiting status report

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1730]
steps to reproduce: 

1) disable update status module
2) make sure you are on backdrop 1.3.3
3) visit your home page
4) clear all caches - confirm notification icon appears
5) visit status report page - confirm notification icon disappears
6) visit home page
7) clear all caches again - confirm notification icon appears again

**Comment by jenlampton** [comment]
This may have been specific to only my site, but what happened was that the schema version for comment module was set to -1 in the system table for some reason, even though the module was enabled (status = 1).  Setting the schema version to 1000 and running updates (bringing it up to 1003) solved the issue for me.

**Comment by klonos** [comment]
Yeah, Tried the steps to reproduce (by "disable update status module" I take it you meant the Update Manager, right?), but I couldn't. Perhaps as you said it was in your specific site.

**Comment by dboulet** [comment]
I’ve noticed this as well. The icon will be displayed, but after I click on it, there are no errors in the report and the icon disappears. Still not sure exactly how to reproduce it.

**Comment by BWPanda** [comment]
Closing this old issue, but if it still happens feel free to re-open.
