### ISSUE TITLE
Unable to override template for specific menu block in theme

### ISSUE THREAD

**Issue by dboulet** [backdrop/backdrop-issues#1732]
In an effort to override the template used for the main menu block in my theme, I named my template `block--system--main-menu.tpl.php`. I can’t get Backdrop to actually use this template.

As far as I can tell, this is a bug. When the menu block is rendered, the theme hook which is called contains the block delta, which itself contains a hyphen. In my case the hook is `block__system__main-menu`. This will not match any theme implementations, since all hooks listed in the registry have their hyphens converted to underscores in `backdrop_find_theme_templates()`.

Can anyone else confirm that this is a bug, and that I’m not doing anything wrong?

**Comment by gifad** [comment]
PR [#1294](https://github.com/backdrop/backdrop/pull/1294/commits/7abb2b22f5cb05b5c53e9cb74dd4c0ff99824c4c) above to normalize block name with underscore.

**Comment by dboulet** [comment]
Thanks @gifad, I was contemplating the same fix.

**Comment by quicksketch** [comment]
Excellent! Merged in https://github.com/backdrop/backdrop/pull/1294. Thanks @gifad!
