### ISSUE TITLE
[UX] Views UI: Style Settings: the 'Use default' option for the Wrapper HTML element drop-down is too vague.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1735]
When I see this wrapper option 'Use default' I have no idea what the default is. Is it selectable somewhere? I would like it to be DIV unless I choose differently.

![viewsdefault](https://cloud.githubusercontent.com/assets/10559274/13945263/cbd1afbe-f003-11e5-9042-8e937abf86d7.png)

**Comment by BWPanda** [comment]
The default HTML elements for the field, label and wrapper HTML come from the Views' template file `views-view-fields.tpl.php` (in your View click 'Theme: Information', then 'Row Style Output'). You'll see:

```php
<?php print $field->wrapper_prefix; ?>
  <?php print $field->label_html; ?>
  <?php print $field->content; ?>
<?php print $field->wrapper_suffix; ?>
```

These are generated in [template_preprocess_views_view_fields](https://api.backdropcms.org/api/backdrop/core%21modules%21views%21templates%21views.theme.inc/function/template_preprocess_views_view_fields/1), but not in a way that's easy to determine.

The wrapper HTML, for example, comes from `$object->inline_html`, e.g.:

```php
$object->wrapper_prefix = '<' . $object->inline_html;
if ($class) {
  $object->wrapper_prefix .= ' class="' . $class . '"';
}
$object->wrapper_prefix .= '>';
$object->wrapper_suffix = '</' . $object->inline_html . '>';
```

`$object->inline_html` in turn comes from `$object->handler->element_wrapper_type(TRUE, TRUE)` which is still not easy to tell what the default value is: [views_handler_field::element_wrapper_type](https://api.backdropcms.org/api/backdrop/core%21modules%21views%21handlers%21views_handler_field.inc/function/views_handler_field%3A%3Aelement_wrapper_type/1)

So not sure how best to address this...

As for the comment "I would like it to be DIV unless I choose differently", that can be done relatively easily by overriding the `template_preprocess_views_view_fields` function and replacing empty HTML with the element of your choice.

Considering the age of this issue, I'm going to close this and hope this is enough documentation to help anyone else with this question. If it's not, feel free to re-open, preferably with a suggestion of what to do to address it :wink:
