### ISSUE TITLE
Notice: Undefined index: HTTP_ACCEPT in backdrop_is_html()

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#1736]
After update to ver. 1.3.4 I've been getting such notices :
Notice: Undefined index: HTTP_ACCEPT in backdrop_is_html() (line 3814 of .../core/includes/bootstrap.inc).
This has something like platform sniffing.
So, changes in checking this variable was not so correct, and adding something like `isset($_SERVER['HTTP_ACCEPT']` can help avoid this.

**Comment by dboulet** [comment]
There is already check for `empty($_SERVER['HTTP_ACCEPT'])` in `backdrop_is_html()`, but it probably needs to be moved to the beginning of the line, so that it’s the first condition checked.

Like this:

```php
function backdrop_is_html() {
  return empty($_SERVER['HTTP_ACCEPT']) || strpos($_SERVER['HTTP_ACCEPT'], 'text/html') === 0 || empty($_SERVER['HTTP_X_REQUESTED_WITH']);
}
```

**Comment by findlabnet** [comment]
@dboulet thanks, this fix was tested by wild robots - all fine.
[PR #1309](https://github.com/backdrop/backdrop/pull/1309) was issued.

**Comment by quicksketch** [comment]
Thanks @findlabnet! The PR looks great. I've merged it https://github.com/backdrop/backdrop/pull/1309. This will be in 1.3.5.
