### ISSUE TITLE
Call to undefined function _date_views_fields()

### ISSUE THREAD

**Issue by sentaidigital** [backdrop/backdrop-issues#1738]
`date_view_fields()` in the core Date module tries to load a file from the old date_views module, and then can't find the `_date_views_fields()` function.

**Comment by klonos** [comment]
Good catch @sentaidigital :+1:

**Comment by sentaidigital** [comment]
IIRC, I ran into this trying to port the date_ical module.

**Comment by sentaidigital** [comment]
PR needs a test case.

**Comment by sentaidigital** [comment]
Added a test case.

**Comment by quicksketch** [comment]
Thanks @sentaidigital for the PR! I've merged https://github.com/backdrop/backdrop/issues/1347 and this is now in 1.x and 1.3.x.
