### ISSUE TITLE
[UX] CKEditor: Enhance the process of adding links by offering a suggestion/auto-complete solution.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1741]
There might be other solutions out there, but I was thinking about something like the [Linkit](https://www.drupal.org/project/linkit) contrib module:

![linkit-drupal-8](https://cloud.githubusercontent.com/assets/2423362/14024270/869535ca-f23c-11e5-81dd-a524379e0349.png)

**Comment by klonos** [comment]
...here's an animated screencast of how it works:

![linkit](https://cloud.githubusercontent.com/assets/2423362/14024950/d3b8546a-f23f-11e5-8801-f66d20c5727d.gif)

**Comment by klonos** [comment]
Related I believe: #1301

**Comment by dboulet** [comment]
WordPress has a feature like this built-in, and it’s really useful. Related: https://github.com/backdrop/backdrop-issues/issues/1388.

**Comment by klonos** [comment]
+1 reason to implement this then.

**Comment by Graham-72** [comment]
:+1:

**Comment by klonos** [comment]
...I believe it is implemented as a CKEditor plugin or something. Could be wrong.

**Comment by BWPanda** [comment]
Is this a duplicate of https://github.com/backdrop/backdrop-issues/issues/1206?

**Comment by klonos** [comment]
Yes it is.
