### ISSUE TITLE
Custom/managed publishing options.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1742]
This is related to issues like #1190 and #1475 and I think we kinda mentioned it a couple of times here and there. The point is that there is not a single-size-fits-all solution and we should provide site builders with the means to customize these options in order to fit their case.
#1475 is a meta-issue and it sorta focuses on the UI side of things. This issue here is about the underlying cogs that make things work though and it doesn't quite fit the UX spectrum (so not tagging as such)...

So, the idea is to:
- allow the default, out-of-the-box publishing options/flags to be renamed
- allow adding/removing publishing options

**Comment by klonos** [comment]
...turns out there is a contrib module that does this: [Custom Publishing Options](https://www.drupal.org/project/custom_pub)

>This module allows you to create custom publishing options for nodes. It allows you to add to the default options of Publish, Promote to Front Page, and Sticky. It also ingrates with views to allow you add as a field, sort and filter by, your custom options.

> ...A simple use case for this module would be creating an 'Archive' publish option on nodes. This would add an 'archive' property to the node under the Publishing options. Setting the node as Archived would allow you to then create sections with Views, and filter by nodes that have a status of Archive. Now that content is marked 'Archived', which you can use in Views or Solr to demote it from search relevancy but still have it available to users instead of unpublishing it, which removes it from the site entirely and makes it inaccessible.

>Now that you can integrate with Rules, you could do a number of things with Custom Publish Options, like create your own publishing/editing workflows, mark content to be deleted, or other ideas to fit your needs.

I think that this is a perfect fit for our needs:

![custom_pub](https://cloud.githubusercontent.com/assets/2423362/14025951/964b94de-f244-11e5-9b31-1c29ff560d9a.png)

**Comment by klonos** [comment]
This is actually the same as (or very similar to) [Support arbitrary workflow states [#1777388]](https://www.drupal.org/node/1777388) I guess. Perhaps a "light-weight" version of it.

**Comment by klonos** [comment]
I gave it a go and the UI is very simple and intuitive...

Adding a custom publishing option:

![drupal-custom_pub-add](https://cloud.githubusercontent.com/assets/2423362/14026434/f7de631e-f246-11e5-8b9b-639f9aa5730b.png)

Manage custom publishing options:

![drupal-custom_pub-manage](https://cloud.githubusercontent.com/assets/2423362/14026454/0a9a2844-f247-11e5-8609-d6c92a979eac.png)

What I would like to see implemented in our version would be to:

- [ ] include the default, out-of-the-box states in this list. This would be "Sticky" and "Promote" currently. In the future perhaps we deem it necessary to ship core with more such options.

- [ ] convert the "Published status" radio set in the "Publishing settings" vtab on the content type edit form to a checkbox set (Published / Publish posts by default). This will bring it in tandem with the rest of the publishing options.

- [ ] be able to reorder all these options and that order to be reflected in the node edit "Publishing options" tab.

- [ ] add a description field for each publishing option that will be shown in the UI (like the "Sticky posts may be shown at the top of listings.")

- [ ] a "Manage publishing settings for [content_type]" link (shown to people with right permissions) in the node edit "Publishing options" tab that would lead to the "Publishing settings" vtab of the respective content type edit form.

- [ ] a "Available publishing options" link on the "Publishing settings" vtab of each content type that would open a modal with a checkbox list with all publishing options. This would allow site builders to quickly add/remove publishing options to the current content type. 

- [ ] a "Add new publishing option" link on the before-mentioned "Available publishing options" modal that would allow adding a more publishing options without leaving the content type edit form.

**Comment by jenlampton** [comment]
Considering that most sites don't even use revisions, I don't think adding more revision features to core is an 80% use-case. it sounds like there's already a great solution in contrib!

**Comment by klonos** [comment]
Right. And given there has been no interest/activity in this issue for 6 years, let's go ahead and close this.

FTR, the module seems to have been ported to Backdrop contrib about 6 years ago, but is now unmaintained, and there's no official release: https://github.com/backdrop-contrib/custom_pub ...I like this module, so I am considering to adopt it 🙂
