### ISSUE TITLE
[UX] Include which layout template is in use on the layouts admin listing.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1749]
On the layouts admin listing at `admin/structure/layouts` it would really benefit users to be able to see which layout-template is being used for each item. Then we wouldn't need to click into each layout, then click again into settings to figure it out.

**Comment by klonos** [comment]
Either a duplicate of #1028 or we can convert that to a meta-issue and this can be a sub-issue of it.

@docwilmot has made some progress in https://github.com/backdrop/backdrop/pull/979

**Comment by jenlampton** [comment]
oops. agreed! :) thank you.
