### ISSUE TITLE
[UX] saving user account settings should redirect to the user-view page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1750]
When you save a node you are redirected to the node view page, it's a little jaring that when you save a user account, you remain on the account settings page.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/issues/1302 needs to update tests.

**Comment by jenlampton** [comment]
Tests now passing!

**Comment by serundeputy** [comment]
Thanks Jen!

Works as advertised.
Tested manually
```
git checkout -b jenlampton-1750-user-save-view 1.x
git pull https://github.com/jenlampton/backdrop.git 1750-user-save-view
```

Marking as RTBC.

**Comment by quicksketch** [comment]
Looks good to me. :shipit:

**Comment by serundeputy** [comment]
Thanks @jenlampton this is merged into `1.x` and `1.3.x`.  I will ship with `1.3.6`.

thanks!
