### ISSUE TITLE
Views filter: When I select dropdown and use autocomplete and click the save button - nothing happens the first time

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1751]
From gitter.im @drupal8Todd 

I'm working on my Beginning Backdrop book and ran into an issue with the latest release last night. Anyone else experiencing the behavior of adding a Views filter and using the dropdown option? When I select dropdown and use autocomplete and click the save button - nothing happens the first time. I click a second time and it saves the filter but doesn't take me to the configuration screen for that filter, but does add it. When I click on the filter to configure it there's a long list of errors:

```
Warning: Parameter 3 to views_ui_build_form_state() expected to be a reference, value given in views_ui_ajax_form() (line 2854 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Undefined index: form_key in views_ui_build_form_path() (line 2731 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Undefined index: view in views_ui_build_form_path() (line 2733 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Trying to get property of non-object in views_ui_build_form_path() (line 2733 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Undefined index: form_key in views_ui_build_form_path() (line 2734 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Undefined index: display_id in views_ui_build_form_path() (line 2734 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Undefined index: args in views_ui_build_form_path() (line 2735 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Warning: Invalid argument supplied for foreach() in views_ui_build_form_path() (line 2735 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Undefined index: form_id in views_ui_ajax_form() (line 2860 of /Applications/MAMP/htdocs/backdrop/core/modules/views_ui/views_ui.admin.inc).
Notice: Undefined index: in backdrop_retrieve_form() (line 806 of /Applications/MAMP/htdocs/backdrop/core/includes/form.inc).
Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in backdrop_retrieve_form() (line 850 of /Applications/MAMP/htdocs/backdrop/core/includes/form.inc).
Notice: Undefined property: TaxonomyVocabulary::$vid in views_handler_filter_term_node_tid->value_form() (line 129 of /Applications/MAMP/htdocs/backdrop/core/modules/taxonomy/views/views_handler_filter_term_node_tid.inc).
```

I'm using a clean copy of the latest version with no contrib modules.

**Comment by serundeputy** [comment]
Hi @drupal8todd.

I was unable to replicate the issue.  Here are the steps I took:

* Add a new view
  * /admin/structure/views/add
* Page view
  * click `Continue & Configure`
* Add a filter
  * Content: Has taxonomy term
  * Click `Add and Configure Filter Criteria`
  * Click the radio button `Dropdown` for the `Selection type`
  * Click `Apply And Continue`
  * Left the Operator as `Is one of`
  * Select a few terms
  * Click the `Apply (All Displays)`
* Save the view
  * no errors for me
* Visit the view URL 
  * Everything is working

Is there something different in my steps that I'm missing compared to what you are
doing?  Trying to replicate the problem so that we can get to solving it :)

thanks for the report!

**Comment by goldmantx** [comment]
So I did some additional troubleshooting with Todd in the course of reviewing his book and I think the key is when you choose Dropdown AND check "Show hierarchy in dropdown". I think checking that box is the key bc I do not get the error if I don't check that box. Hope that helps!

**Comment by serundeputy** [comment]
Thanks @goldmantx following those steps did produce an error:

```php
Notice: Undefined property: TaxonomyVocabulary::$vid in views_handler_filter_term_node_tid->value_form() (line 129 of /Users/geoff/sites/backdrop/core/modules/taxonomy/views/views_handler_filter_term_node_tid.inc).
Notice: Undefined property: TaxonomyVocabulary::$vid in views_handler_filter_term_node_tid->value_form() (line 129 of /Users/geoff/sites/backdrop/core/modules/taxonomy/views/views_handler_filter_term_node_tid.inc).
```

Documenting here for future debugging.

screenie:
![screen shot 2016-04-12 at 1 53 55 pm](https://cloud.githubusercontent.com/assets/6763671/14470186/1684c2ae-00b6-11e6-8db6-9400d5a74de3.png)

thanks!
~Geoff

**Comment by Drupal8Todd** [comment]
That is the issue... Todd

**Comment by BWPanda** [comment]
I cannot replicate this. I believe it was fixed in: https://github.com/backdrop/backdrop/commit/6a1ca18136870adca917f2787d8040ac2ccaa3fc
