### ISSUE TITLE
Add check for local settings file

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop/backdrop-issues#1752]
As mentioned in issue #346, people seem to want a way to have local settings that don't interfere with settings.php and become erroneously committed in a PR. 

A proposed solution would be to include a file exists check in settings.php for settings.local.php and add settings.*.php to the .gitignore file.

**Comment by alexfinnarn** [comment]
I don't know if the PR is what is desired, but I think the file can be a great way to document what you might want to do during local development for people who don't know that certain settings even exist. When looking at the D8 local settings file, I see a lot of suggestions you might want to do, and I'm sure a lot of people starting out developing a D8 site find this information useful. 

In short, the file could be a learning tool as well as a tool used by a lot of people for local development.

**Comment by quicksketch** [comment]
Hi @alexfinnarn! Thanks for opening this issue and filing the PR. I know @jenlampton has some thoughts on this issue, perhaps she can weigh in here. I see the usefulness but personally I'm a bit ambivalent.

One thing that is a sticking point for me in the current approach is the `example.settings.local.php`. Including items that would be useful in there could quickly become redundant with the documentation in `settings.php`. My preference (for starters) is to include the snippet in `settings.php` but forgo having an example file for the time being. If we'd like more examples, we can link off to api.backdropcms.org, as we did when we simplified the database connection information.

**Comment by quicksketch** [comment]
@alexfinnarn Do you think you could take another look at this to simplify the PR?

@jenlampton Would be great if you could weigh in here as well.

All other opinions welcome. :smile:

**Comment by jenlampton** [comment]
Hi @alexfinnarn! I do this on **all** my sites b/c it makes life so much easier when you don't need to worry about accidentally committing db creds to vcs.  👍 

I think I'm in agreement with @quicksketch about excluding the local example file. The documentation block in settings.php looks great, and that should be a good enough starting point for most devs. We want to be careful not to overwhelm people with too much information, but if we did want to write that up I think a good place for it is on api.backdropcms.org.

**Comment by jenlampton** [comment]
I just pushed a new PR w/o the example file, and with a slightly-less verbose docblock in settings.php.

**Comment by quicksketch** [comment]
Oops, @jenlampton you included your DB credentials in the PR. :wink: https://github.com/backdrop/backdrop/pull/1332/files#r60835875

**Comment by jenlampton** [comment]
BWAHAHAHAHAHA

**Comment by jenlampton** [comment]
fixed :)

**Comment by alexfinnarn** [comment]
so this is all ready to go? Good jorb!

**Comment by serundeputy** [comment]
This is great!  
Thanks @alexfinnarn and @jenlampton ; merged into `1.x` and `1.3.x` this will ship with Backdrop 1.3.6 and 1.4.
