### ISSUE TITLE
One-time login links broken by new password reset forms

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1754]
In Drupal 7 with Drush, it was possible to log into site by hitting `http://example.com/user/reset/1/1458949065/QPdbt0XPh7E4nQE_wZmKcRBKlhOOOuj-xHbXWzS3kcQ/login` (note the trailing `/login` part of the path).

We reworked the way password resets functioned in #1115, making it so that a user had to change their password in order to log in. But this affected the drush functionality that allowed a user to log in _without changing their password_. We should restore this previous functionality.

**Comment by serundeputy** [comment]
I pulled this down and tested locally:

```
git checkout -b quicksketch-1754/onetime_login 1.x
git pull https://github.com/quicksketch/backdrop.git 1754/onetime_login
```
Ran `drush uli` logged into site without having to change password.
Works as advertised.  Marking as reviewed.

**Comment by serundeputy** [comment]
Thanks @quicksketch this works great; merged into `1.x` and `1.3.x`.  This will ship with `1.3.6`

Thanks!
