### ISSUE TITLE
Add deprecation doxygen tags to all deprecated (Drupal) functions.

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1760]
Currently, not all deprecated (drupal_*) functions have a doxygen description, nor a @deprecated tag. This allows devs to keep using deprecated functions without any notices at all. Editors like PhpStorm mark the use of deprecated functions and if I'm correct, you could even configure php itself to display these deprecation notices.

Ideally, all functions in drupal.inc should be described in a similar way to this:

```
/**
 * One-liner to describe this function.
 *
 * @deprecated since 1.0
 * @see backdrop_replacement_function()
 */
```

This is a daunting and cumbersome task, not to mention boring. And I'm already working on it ;)

**Comment by MrHaroldA** [comment]
174 function one-liners to go ...

**Comment by docwilmot** [comment]
A noble task indeed. Just so you dont have to redo, should it not be `deprecated since 1.0.0`?
And checking also for other (non-Drupal.inc) deprecated functions?

**Comment by MrHaroldA** [comment]
1.0 > 1.0.0 could be done with a simple search/replace. Automated copy/pasting function one-liners is likely not worth the effort.

145 function one-liners to go ;) I'll leave deprecated functions outside of drupal.inc for you guys! ;)

**Comment by mikemccaffrey** [comment]
Thanks for tackling this @MrHaroldA!

**Comment by quicksketch** [comment]
Thanks @MrHaroldA! This will be great. PHPStorm automatically notifies usage of any `@deprecated` functions, so this could be a big help to IDE users.

Agreed on the format. It should indeed be `@deprecated since 1.0.0`, as we've had situations where we've replaced/deprecated functions in bugfix releases when security or bugs are involved.

**Comment by MrHaroldA** [comment]
> It should indeed be @deprecated since 1.0.0

Let's make that a new issue, which will follow this one soon.

**Comment by MrHaroldA** [comment]
I probably don't have any time to create a pull request today, so if anybody feels the urge: http://dl.sait.nl/deprecation_notices.patch

**Comment by MrHaroldA** [comment]
I do want the credits though!!! :sweat:

**Comment by quicksketch** [comment]
Thanks! We had a change to `drupal_alter()`in #1767, so I had to manually merge the PR. This has now been merged (along with the follow-up at https://github.com/backdrop/backdrop-issues/issues/1766). Thanks @MrHaroldA!

**Comment by MrHaroldA** [comment]
You're welcome! ;)
