### ISSUE TITLE
drupal_path_alias_whitelist_rebuild() should return an (empty) array

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1761]
To prevent notices on ported code, drupal_path_alias_whitelist_rebuild() should return an array instead of the empty return it has currently.

All other invalid return values have been fixed in #1766, and the function descriptions were added in #1760.

**Comment by MrHaroldA** [comment]
This function should return an array: https://api.drupal.org/api/drupal/includes!path.inc/function/drupal_path_alias_whitelist_rebuild/7

**Comment by MrHaroldA** [comment]
Here's the patch based on #1760: http://dl.sait.nl/1761_correct_returns.patch

**Comment by jenlampton** [comment]
Thanks for this @MrHaroldA. Would you like to take a stab at generating a pull request for us?

**Comment by MrHaroldA** [comment]
I believe @quicksketch fixed this in #1766, except for the empty array that drupal_path_alias_whitelist_rebuild() should return.

I'll PR that single issue here.

**Comment by MrHaroldA** [comment]
It would be cool if 1.4.0 could have this fix too to be able to say that the Drupal compatibility layer is 100% correct ;)

**Comment by quicksketch** [comment]
Thanks @MrHaroldA! Merged into 1.x and 1.3.x. Great small fix!
