### ISSUE TITLE
simple_access throws notice

### ISSUE THREAD

**Issue by ronalddevos** [backdrop/backdrop-issues#1763]
Did a fresh install of backdrop, installed simple_access.
Created a page and got:
Notice: Undefined property: Node::$simple_access in simple_access_form() (line 501 of /var/www/html/vve/modules/simple_access/simple_access.module).

**Comment by Graham-72** [comment]
@ronalddevos Thanks for reporting this but it almost certainly an issue in the contrib module and best reported there at https://github.com/backdrop-contrib/simple_access/issues where I already have some open issues that I am tackling as time permits. Now I have this report from you it will move higher up my list of jobs to do :smile:
