### ISSUE TITLE
Theme problem

### ISSUE THREAD

**Issue by ronalddevos** [backdrop/backdrop-issues#1765]
Did a clean install of Backdrop, downloaded the 'ZURB Foundation 6' theme, enabled and set as default.
Went to ZURB Foundation 6 settings and got:
Notice: Undefined index: pure_css in theme_get_setting() (line 1444 of /var/www/html/core/includes/theme.inc).

**Comment by MrHaroldA** [comment]
Is this a Backdrop issue, or a ZURB issue?

**Comment by ronalddevos** [comment]
I have no idea, as I am completely new to backdrop.
I did try a couple of other themes and they did not throw the error, so I  ASSUME it is ZURB….

Ronald de Vos

**Comment by klonos** [comment]
@ronalddevos already reported in that theme's issue queue: https://github.com/backdrop-contrib/zurb_foundation_6/issues/1
