### ISSUE TITLE
Change all deprecation tags from 1.0 to 1.0.0.

### ISSUE THREAD

**Issue by MrHaroldA** [backdrop/backdrop-issues#1766]
The deprecation tags in drupal.inc are all written as '1.0', instead of the initial '1.0.0' Backdrop release.

This depends on #1760, as that issue adds a lot of deprecation tags.

**Comment by MrHaroldA** [comment]
Here's the patch based on #1760: http://dl.sait.nl/1766_1.0_1.0.0.patch

**Comment by quicksketch** [comment]
I manually applied the patch and applied it to 1.x in https://github.com/backdrop/backdrop/commit/5376cc5cde97f435267c6a615b2a10737faef8a4. Thanks @MrHaroldA!
