### ISSUE TITLE
drupal_alter() compatibility layer missing $context3 argument.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1767]
I understand that the `$context3`argument is deprecated both in drupal and in backdrop, and of course usage of `backdrop_alter` is to be preferred over `drupal_alter`, **_but..._**

When porting drupal geocoder module, I spent 10 minutes to reimplement the CTools plugins system, but I spent 2 hours to understand why an `if (isset(…` did not work !

And no, I don't do find/replace drupal > backdrop in early stage of porting, as it makes virtually impossible to "find differences" between original and ported version.

PR at [#1314](https://github.com/backdrop/backdrop/pull/1314)

**Comment by MrHaroldA** [comment]
This PR will fail after #1760 is committed; and visa-versa.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1314, as this is a bug fix. I'll see about resolving the conflict in https://github.com/backdrop/backdrop-issues/issues/1760.

**Comment by quicksketch** [comment]
> I understand that the $context3argument is deprecated both in drupal and in backdrop, and of course usage of backdrop_alter is to be preferred over drupal_alter, but...

Hi @gifad, thanks for making this issue. I think $context3 may have been removed prior to our fork from Drupal 8. Sorry again for the completely unnecessary frustration. :frowning: Merged in https://github.com/backdrop/backdrop/pull/1314, thanks for making that!
