### ISSUE TITLE
Dropdown menu like the admin menu

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1769]
I am sorry for this dummy question: is it possible to make a user website menu like the admin menu with core options? Or should I install [**nice_menus**](https://github.com/backdrop-contrib/nice_menus) module?

![menu](https://cloud.githubusercontent.com/assets/13515302/14166869/b0be4ae8-f71f-11e5-86fc-a5508de5cdce.png)

**Comment by quicksketch** [comment]
Hi @bd0bd! Yes, at this point you should try Nice Menus. We have an open feature request for this in core at #1457. Please continue any discussion over there. Thanks!

**Comment by bd0bd** [comment]
Thank you!
