### ISSUE TITLE
The "Operations" column table header is not properly aligned.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1782]
@Graham-72 noticed this incidentally on the custom blocks page in https://github.com/backdrop/backdrop-issues/issues/1776#issuecomment-204879365 but this happens in other admin pages too. The fact that the header is left-aligned while the action drop buttons are right-aligned makes it worse. Especially in cases where the table has only 2 columns. The effect is more obvious on wide screens. Here are some examples:

/admin/structure/layouts
/admin/structure/menu/list
/admin/config/content/formats

more obvious:

/admin/content/book/list
/admin/config/media/image-styles
/admin/structure/block
/admin/structure/taxonomy/list
/admin/structure/taxonomy/tags

not obvious at all:

/admin/structure/views

**Comment by BWPanda** [comment]
I believe this has since been fixed, as drop-buttons are no longer right-aligned:

![image](https://user-images.githubusercontent.com/2385329/105019953-ce726900-5a9a-11eb-8a4a-59d25886e6f9.png)

Will close this, but feel free to re-open if I'm mistaken and there's still a problem here.
