### ISSUE TITLE
"page not found" log entries with "system/transliterate" message when adding a view.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1783]
Location: `http://backdrop.local/system/transliterate/&replace=-`
Referrer: `http://backdrop.local/en/admin/structure/views/add`

**Comment by BWPanda** [comment]
I tried to replicate this but couldn't. Can you provide STR @klonos, or is this fixed now?

**Comment by klonos** [comment]
I can't reproduce this either now. Must have been fixed sometime between 2016 and now 😅
