### ISSUE TITLE
Views: Table format: defining multiple field sort criteria and also a default table sort produces unwanted results.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1784]
I am trying to create a view that replicates the default "Recent log messages" page provided by core using https://backdropcms.org/project/views_watchdog with the intention to improve it with exposed filters and see if it's worth pursuing #1302 

Here is the thing... I have initially added the `Watchdog:Timestamp` field provided by views_watchdog and configured it to be the replacement of what we have as the "Date" column in the "Recent log messages" page (set its label to "Date", selected the short format for date etc). I have added the same field as a sort criterion. This worked fine, but there are cases where some event log entries happen at the very exact time (to the second) and this causes them to be listed in a seemingly random order when compared to the "Recent log messages" page. So, I have added a second sort filter in the view based on the `Watchdog:WID` field. This way, events with the exact same timestamp get sorted by their `wid`. Perfect so far...

In the "Recent log messages" page, the table has the "Type", "Date" and "User" columns sortable, with "Date" being the default sort. When I try to do that using the views format settings dialog (having set the format to "table"), then the sort is applied, but the secondary sort I have defined in the view "Sort criteria" section (`Watchdog:WID`) is ignored. So, I get the same seemingly random order of the log entries as before adding the Watchdog:WID as a secondary sort.

Pointers please? Am I doing something wrong, or is this a Views limitation?

**Comment by klonos** [comment]
...in order to better explain what I'm trying to achieve and what I mean by "unwanted results" or "seemingly random order", I'm thinking of filing a dummy PR (that includes the views_watchdog module) so that I can (ab)use our PR sandbox feature. I mean well though. I promise :smiling_imp: 

I will do that once I have some time.

**Comment by docwilmot** [comment]
Idont know about this module but maybe if you can increase the granularity of the date field this might help? 

> I'm thinking of filing a dummy PR ... so that I can (ab)use our PR sandbox feature.

I'd say this would be introducing a bad precedent then.

**Comment by klonos** [comment]
@docwilmot granularity was set to seconds from the beginning. There is no higher I can set.

> I'd say this would be introducing a bad precedent then.

Fair enough. I'll refrain from doing it then. My intention was to use our QA server as an equivalent of simplytest.me in order to fire up instances of Backdrop (+some contrib modules) that showcase issues or features or proposals for change. That's all. But I see what you mean.

Would posting a view export be good? ...this way you can see at which point I'm at and perhaps make suggestions. It's just that with an actual sandbox, it'd be so much easier to show you what I've done so far + what does not work. Anyways, let me know.

**Comment by docwilmot** [comment]
Perhaps create an actual live test site on your own server?

**Comment by BWPanda** [comment]
Closing old issue. Reopen if still relevant.
