### ISSUE TITLE
Remove "My account" and "Log out"

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1785]
Please, how to remove this duplicate when admin is loged in?

![default](https://cloud.githubusercontent.com/assets/13515302/14233226/5e7ec9b6-f9cb-11e5-967f-dcaf89af17e2.png)

**Comment by serundeputy** [comment]
@bd0bd 

https://www.youtube.com/watch?v=x1nfaCbRDxg&feature=youtu.be

**Comment by bd0bd** [comment]
Thank you!
