### ISSUE TITLE
View page - to limit summary content length

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1786]
Please, how to limit length of post or article summary?

Yes, I know that I can fill in the summary window but this is extra work.
I would like to fill in only the body.

Thank you!

**Comment by klonos** [comment]
Edit the Article content type. Go to its "Manage display" tab. There, you will see two secondary tabs (they look like buttons). Click the "Teaser" one. Then make sure that the body field is set to "Summary or trimmed" (should be by default). Finally click on the configure button:

![backdrop-article-manage_display-configure_body_field_summary](https://cloud.githubusercontent.com/assets/2423362/14236495/4130c460-fa5a-11e5-87c8-d2d305af1339.png)

...that will get you into edit mode and you should be able to change the default limit of 600 characters:

![backdrop-article-manage_display-body_field_summary-trim-limit](https://cloud.githubusercontent.com/assets/2423362/14236496/41339e92-fa5a-11e5-918b-e9b641ab40ea.png)

**Comment by bd0bd** [comment]
Thank you! But it was not necessary to show me in these details :smile: 
It would be very clear for me if you gave me only this link: /admin/structure/types/manage/post/display/teaser

**Comment by klonos** [comment]
You're welcome.

> not necessary to show me in these details.

Yes, but that's how I am. Besides, these issues are here for others to find answers and they might need the extra guidance :wink:
