### ISSUE TITLE
View: remove "Log in or register to post comments"

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1787]
Sorry, I can not find in the View settings where is located this option.
I would like to remove "Log in or register to post comments".

I know only one way to remove it - directly in the file.
And I would not like to use CSS to hide **comment-forbidden** class.

**Comment by klonos** [comment]
Hi @bd0bd what are you trying to do? Is this a view of comments? Can you describe the view in a few more details please?

**Comment by bd0bd** [comment]
Hi @klonos!

I do not need it here:

![fdgrtfge](https://cloud.githubusercontent.com/assets/13515302/14236390/4f2159dc-fa1d-11e5-980e-7f30d614493a.png)

**Comment by klonos** [comment]
I do not have an answer/solution for you yet, but there are some d.org articles about this problem:

[How to remove "Log in to post comments"](https://www.drupal.org/node/1346784)
[Remove "login to post comments" prompt from Story pages](https://www.drupal.org/node/170065)
[Usability: Configurable comment link on teasers [#169938]](https://www.drupal.org/node/169938) (issue that was filed against D6, but was pushed to D7 and then to D8 - still active/unsolved)

**Comment by klonos** [comment]
Hold on. I'm working on something...

**Comment by bd0bd** [comment]
Thank you, but I do know how to remove it:
**.comment-forbidden {display: none!important}**
This is not very right way.

I had an idea this can be removed via View. Now?

**Comment by klonos** [comment]
This was not possible with Drupal 7 core and is not currently possible with Backdrop core either. For D7, there is the [Remove links from teasers](https://www.drupal.org/project/removeaddnewcommentteaserlink) module and its successor [Fix teaserlinks](https://www.drupal.org/project/fixteaserlinks). I'm looking to port that to Backdrop and then you can use it.

The way these modules work is that once enabled, the remove those links. If you want the links back, you need to disable the module (there is no setting). Eventually, I hope to add a UI with settings and perhaps make these per content type. Will see how it goes.

**Comment by bd0bd** [comment]
Thank you!
To have a module to remove this link (it is very minor detail)- this a noncence in my opinion :smile: 
I think this option should be in core in view or in page type settings.

**Comment by bd0bd** [comment]
May be it is better to add **Do not show the link** option to this module?
https://github.com/backdrop-contrib/views_system

**Comment by gifad** [comment]
> I think this option should be in core in view or in page type settings.

100% agree, but problem is _content-type manage display_ is managed by the Field API, and the title, links, etc... are not fields, just "_Node module elements_"

I ported the drupal `pseudo_field` module, which allows to expose the minimal Visible/Hidden choice, but I found no way to implement a formatter, which would expose the settings we are after.

I had to rely on an external settings page;

![capture d ecran 2016-04-04 a 17 40 45](https://cloud.githubusercontent.com/assets/15943462/14253602/70bb9ffc-fa8c-11e5-8405-8c3dc4be2cc6.jpg)

@quicksketch : would a feature request to allow formatters on extra fields make sense ?

**Comment by klonos** [comment]
Would setting a custom title through the layout options work?:

![backdrop-layout_edit_form-page_title_type_drop-down-wrong_label](https://cloud.githubusercontent.com/assets/2423362/13552972/9061cf48-e3cb-11e5-9bca-e04d4954e4c4.png)

PS: I know that the drop-down label is wrong, but I've already filed #1692 for it.

**Comment by klonos** [comment]
...never mind. I just tested it and it doesn't work. That setting changes only the actual title of the page, but the " | [site-name]" part is still appended to it.

**Comment by gifad** [comment]
I was hesitating to suggest to handle this at the theme level (as this is brillantly done by [AdaptativeTheme](https://www.drupal.org/project/adaptivetheme) in drupal), but thanks klonos to remind us that in backdrop, the Layout thing has the absolute power.
Too bad.

**Comment by klonos** [comment]
...sorry. I moved my last two comments in #1790 because that's where I initially intended to post a reply (too many browser tabs open got me confused).

**Comment by gifad** [comment]
About extra fields, on the orthodox side of our religion, God does not want : [Revaluate the concept of 'extra fields'](https://www.drupal.org/node/1954188#comment-7760463).

**Comment by klonos** [comment]
> ...on the orthodox side of our religion, God does not want...

:laughing: I like your metaphors @gifad

**Comment by abacus44** [comment]
Yes I know this is much irritating seeing so many comments with links after your post so remove it.
Use [important info](url="http://rbxgenerator.com") here.

**Comment by klonos** [comment]
@bd0bd can you please test https://backdropcms.org/project/fixteaserlinks and see if it does what you are asking?

...there are a few issues with the project packaging and the release node text in backdropcms.org, but the module should work just fine. The module is a direct port from D7, so the defaults are to hide comment links but leave the "Read more" link intact without any options in the UI. I plan to add a configuration page in a next release.

...remember to clear caches after installing and enabling the module and to report any issues over in https://github.com/backdrop-contrib/fixteaserlinks/issues

**Comment by juliagreen** [comment]
Hi.
Thank you you very much for share this information.It's very helpful for me good work  and keep going to 
sharing information.[New hairstyle for women](http://www.cutegirlshairstyles.com/)

**Comment by AshleyLuke** [comment]
The issues resolve really helpful to all of them to tell about banding centers of America adjustments. Online  review is says clearly to all them to catch http://www.peakdissertation.co.uk/ and so much useful to them.

**Comment by umam12** [comment]
![image](https://cloud.githubusercontent.com/assets/22318874/18666667/f0fce822-7ee1-11e6-990c-45fd717a5174.png)
![image](https://cloud.githubusercontent.com/assets/22318874/18666673/f9077a0a-7ee1-11e6-9ca6-a26a8aada318.png)

**Comment by umam12** [comment]
t fine. The module is a direct port from D7, so the defaults are to hide comment links but leave the "Read more" link intact withou http://bit.ly/2bgLGS7

**Comment by umam12** [comment]
<a href="http://goo.gl/TLJKhQ">contoh konstruksi baja wf</a>

**Comment by umam12** [comment]
www.latahza.com

**Comment by sharry778** [comment]
I wish i could help but i haven't got any clue what you guys on about 
you can look for some good [leather hand bags ](www.dtaces.com)

**Comment by leophire** [comment]
Ah... As all knows that 2016 is almost gone and 2017 is coming and also new trends are here so update yourself with new <a href="http://leophire.com">Technology Trends</a> of 2017.

**Comment by Minicodec** [comment]
check out the best <a href="http://www.minicodec.com">system updates</a> 
It's all you need.

**Comment by asmashak** [comment]
hey out standing image you people did great discussion i like this kind of informative discussions for fashion visit at [Online Nighties](http://www.nighties.pk) Thanks

**Comment by nngdtn32i** [comment]
If you create your own module you may be able to get rid of it using hook_link_alter (& $ links, $ node, $ comment = NULL). I have not tried it yet, but I'm pretty sure it would work. It could be an excess of tho. [PMP Braindumps](https://www.braindumps4it.com/braindumps-PMP.html)

**Comment by tayzac** [comment]
good work thanks

**Comment by keyatahmina666** [comment]
If you want to buy a new update mobile you can observe our product.Here every apps  is well decorated.For better information visit our site https://www.artdex.com

**Comment by billliam** [comment]
Want to pass PMP exam in first attempt? Pass your PMI exam with [PMP brainDumps](https://www.braindumps4it.com/braindumps-PMP.html) Questions Answrs of Braindumps4it. Your PMI success is guaranteed with our 100% money back guarantee.

**Comment by olafgrabienski** [comment]
^ Looks like spam.

**Comment by bd0bd** [comment]
I think it is not authorized outdoor advertising.

**Comment by klonos** [comment]
Deleted.

**Comment by rosyethan13** [comment]
HPE0-Y53 HP HPE Master ASE is latest exam of hp. Now you can get testified dumps of HPE0-Y53 exam from exams4help. Download a complete sett of [HPE0-Y53 Real Exam Questions Answers](http://www.exams4help.com/HPE0-Y53-pdf-dumps.html) with 100% passing guarantee.

**Comment by gxwdtbdhl** [comment]
MrCerts provides valid Microsoft 70-413 exam dumps that are verified by expert IT professionals. We have Designing and Implementing a Server Infrastructure 70-413 real exam questions of MCSE Server Infrastructure with verified answers that can be of great help for students looking for Designing and Implementing a Server Infrastructure questions answers. Get best preparation study material for 70-413 with [70-413 practice test question dumps](https://www.mrcerts.com/70-413-test.html) from MrCerts. Here you get latest and best microsoft 70-413 braindumps questions answers with passing assurance.

**Comment by olafgrabienski** [comment]
> MrCerts provides valid Microsoft 70-413 exam dumps that are verified by expert IT professionals ...

Spam comment, deleted.

**Comment by breasdtk5** [comment]
Show my dear friend today. Yok. This means that the talking phase was 10 days - slightly shorter than I would like. Last time around I used the progesterone cream to lengthen the pulp, and I'll try it again. I am taking ibuprofen (which I usually avoid tack because it can interfere with the transplant) and drink plenty of coffee with caffeine today. I'm Cramby, Moody, and a little disappointed. On the bright side, I'm having real sessions which means I can keep trying. [70-243 VCE](https://www.vcetests.com/70-243-vce.html) I did not know how long breastfeeding would squeeze my fertility, so I was blessed that I got to start tack again in 4 months after giving birth.

**Comment by olafgrabienski** [comment]
> Show my dear friend today. Yok. This means that the talking phase was 10 days

Deleted another spam comment.

**Comment by lewisschmiidt** [comment]
[url=http://www.amjadtrader.com/]Hdpe Fitting[/url]

**Comment by lewisschmiidt** [comment]
<a href="http://www.amjadtrader.com/">Hdpe Fitting</a>

**Comment by laryn** [comment]
> Hdpe Fitting

Deleted x2

**Comment by CedricMontgomery** [comment]
<a href="http://www.youtube.com">annonymous</a>

**Comment by olafgrabienski** [comment]
> annonymous

Going to remove this post by @CedricMontgomery which simply links to the Youtube main page.

**Comment by ukhelpnumber90** [comment]
Hi I am   Olivia and have been going through your website for a long time. it contains [lot of information](http://www.ukhelpnumber.com/canon-printer-support-uk.php) on various topics. There is a presence of lot of sources   but the knowledge gained from your site is very instrumental.

**Comment by olafgrabienski** [comment]
> Hi I am Olivia and have been going through your website for a long time. it contains lot of information on various topics. There is a presence of lot of sources but the knowledge gained from your site is very instrumental.

Going to delete the comment, it contains a spam link.

**Comment by MichaleGotthardt** [comment]
I am glad to read this blog.
<a href="www.markzucker.com">Facebook</a>

**Comment by findlabnet** [comment]
> I am glad to read this blog.
Facebook

For some reason this specific issue is so popular for spammers ;-)

**Comment by jiuer7845** [comment]
http://www.yeezysupply.us.com/
http://www.jordan11winlike82.us.com/ Jordan 11 Win Like 82
http://www.nikeoutletstoreonlineshopping.us/ Nike Outlet Store
http://www.kyrieirvingjersey.us/
http://www.nike-outlet-store.us/ Nike Outlet Store
http://www.yeezyboost-350.org.uk/ Yeezy
http://www.yeezyboost-350.org.uk/ Yeezy
http://www.yeezybluetint.com/
http://www.monclerjacketsuk.uk.com/ Moncler UK
http://www.nikefactoryoutletonlinestore.us/
http://www.yeezyboost350.us.com/ Yeezy Boost 350
http://www.yeezyboost350.us.com/ Yeezy Boost 350 V2
http://www.cheapnba-jerseys.us/
http://www.balenciaga.me.uk/
http://www.birkenstocks.me.uk/ Birkenstock
http://www.oakleyoutlet.net.co/ Oakley Outlet
http://www.nikenbajerseys.us/
http://www.balenciagauk.org.uk/
http://www.birkenstocks.com.co/
http://www.nike--outlet.us/ Nike Outlet Online
http://www.nike-clearance.us// nike clearance
http://www.offwhitejordan1.com/ Off White Jordan 1
http://www.nikeairmax.us/ Nike Air Max
http://www.yeezyboost350.us.com/ Yeezy Boost 350
http://www.balenciagatriples.org.uk/
http://www.nflshopofficialonlinestore.us/
http://www.nike-airmax270.us/
http://www.airmax97.us/ Air Max 97
http://www.salomons.me.uk/
http://www.cheapnflsjerseys.us/
http://www.jordan12bordeaux.us.us/ jordan 12 bordeaux
http://www.yeezy-shoes.us.com/ Yeezys
http://www.nike--shoes.us/ Nike Shoes
http://www.nikeoutletonlinestoreshopping.us.com/
http://www.cs7boots1.com/
http://www.nike--outlet.us/ Nike Outlet
http://www.max2017.us/ Air Max 2017
http://www.moncler-jackets.uk/ Moncler Jackets
http://www.balenciagatrainers.org.uk/
http://www.birkenstock-sandals.us.com/
http://www.yeezyboost350v2.com/ Yeezy Boost 350 V2
http://www.salomonspeedcross4.org.uk/
http://www.nflsjerseys.us/
http://www.jordan12.us/ Jordan 12
http://www.adidasyeezyshoes.org.uk/
http://www.winlike82.us/ Win Like 82
http://www.jordan11winlike82.us/ Jordan 11 Win Like 82
http://www.nike-air.org.uk/
http://www.jordan4.us/ jordan 4
http://www.nike-clearance.us/ Nike Clearance
http://www.basketball-jersey.us/
http://www.moncler-jackets.uk/ Moncler UK
http://www.yeezy-shoes.me.uk/
http://www.chinacheapnfljerseys.us/
http://www.air-max270.us/
http://www.yeezy.com.co/ Yeezy
http://www.max270.us/
http://www.nikeoutletonlineshopping.us/ Nike Outlet Store Online Shoping
http://www.birkenstock.me.uk/ Birkenstock Shoes
http://www.jordan12ovo.us/ jordan 12 ovo
http://www.nikeshoesformen.us/
http://www.max2017.us/ Nike Air Max 2017
http://www.salomon-shoes.org.uk/
http://www.nike-air.me.uk/
http://www.vapor-max.org.uk/
http://www.birkenstocksandalsuk.me.uk/
http://www.nikevapormax.org.uk/

**Comment by findlabnet** [comment]
This show is going on!

**Comment by olafgrabienski** [comment]
> I faced the same issue before. Sometimes this setting is controlled through template permissions instead of View settings, similar to adjustments used in the [MYAARPMedicare login portal] for secure account access.

Spam comment – deleted.
