### ISSUE TITLE
[DX][UX] Views: Allow exporting/importing single view config from the views UI.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1788]
As per issue title, lets add an "Export view" option in the `views-display-top` div drop button of each view as well as an "Export" option for each view in the views list under `/admin/structure/views`.

This could open a modal with the code where the user could either just select and copy (we could have the text pre-selected) and/or perhaps have a "Save to file" button.

**Comment by klonos** [comment]
...would be useful to also have a "+ Import view code" button next to the "+ Add view" one that opens a modal with a text field where one could paste the exported code of a view.

**Comment by klonos** [comment]
Views 3.x for D7 has the import/export feature built-in:

![d7-views-import_view](https://cloud.githubusercontent.com/assets/2423362/14235991/e9579d08-fa50-11e5-8490-7ea8db895bd6.png)
![d7-views-list-export_view](https://cloud.githubusercontent.com/assets/2423362/14235992/e9592d80-fa50-11e5-814e-3c2d29ac2811.png)
![d7-views-view-export_view](https://cloud.githubusercontent.com/assets/2423362/14235993/e95cbe0a-fa50-11e5-9241-e7a891841587.png)

...but I guess we forked from the version that got into D8 that must have for some reason left this feature out.

**Comment by klonos** [comment]
I initially filed this [in the wrong queue](https://github.com/backdrop-ops/backdropcms.org/issues/217). @docwilmot replied:

> because it is currently done with CMI.

Agreed. I have never actually used CMI, so I didn't think of that. But it is less discoverable:

Configuration -> Development -> Configuration management -> Single Import/Export  -> Export -> select "Views" from the "Configuration group" drop-down -> select the view in question from the "Configuration name" drop-down

...that's like 7 clicks!

So, in the spirit of "put things where people expect to find them" (™/© to @jenlampton), can we please also have the drop button options as well?

**Comment by Graham-72** [comment]
Yes please.

**Comment by gifad** [comment]
> in the spirit of

yeah, but when something is "free", don't forget to ask "Where does the money come from ?"
CMI is a major component of "free" sofware business model…

For the rest of us, CMI is a pain, the most painfull is to manage and keep in sync two backup sets (content and config)

**Comment by klonos** [comment]
@gifad I have absolutely no idea how what you said is related to this issue. ??

**Comment by sentaidigital** [comment]
Ack!  Yes, we need to put the export back.  I copy/paste the exported version from there for hook_views_default_views().   Like the Redirect module, I tend to implement that hook like this:

```php
<?php
/**
 * Implements hook_views_default_views().
 */
function redirect_views_default_views() {
  $views = array();
  $files = file_scan_directory(backdrop_get_path('module', 'redirect') . '/views', '/\.view$/');
  foreach ($files as $path => $file) {
    require $path;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}
```

And then create one PHP file for each of the views that I manage in code.  The CMI export is not in PHP code format, which makes it unsuitable for this workflow.

**Comment by jenlampton** [comment]
@sentaidigital in Backdrop we usually just copy the created config file from `/active` into a `mymodule/config` to provide a default. There are some good examples of this in core, take a look at the admin/content listing for a reference.

**Comment by sentaidigital** [comment]
Does that mean hook_views_default_views is deprecated?

**Comment by jenlampton** [comment]
@sentaidigital There is no `hook_views_default_views` in Backdrop, it's been removed. It does look like we need to update our documentation.

**Comment by quicksketch** [comment]
I'm not entirely sure this feature is necessary. We already have the ability to export a single view under the config management page:

![selection_125](https://cloud.githubusercontent.com/assets/100206/14971214/0f9fb9e2-1085-11e6-8692-311e1a752ed9.png)

And you can import from that same area. Seems like we should keep all the exporting/importing in the same place? Either that or we should start adding import/export in every UI: node types, image styles, etc.

**Comment by sentaidigital** [comment]
It would be there for DX reasons.  I've become quite accustomed to working on a view and then exporting it from the view editor, copy/paste into a .view.inc file, git diff, git commit.  I'm sure I'm not the only one.  If I'm fresh to the world of Backdrop, spend an hour or two working on a complex view, go to export and find the link missing... well, there would be some colorful metaphors.

On a site with dozens of views, the contextual nature of an in-editor export link beats searching for it in a long select list hands down.

The export interface does not have to be the same Views import/export that D7 has.  It would be acceptable for the export link to go to the Single Import/Export page as long as the form is pre-populated and the results shown.

If we're going to remove a feature, we should make it obvious what the replacement is.

**Comment by jenlampton** [comment]
> The export interface does not have to be the same Views import/export that D7 has. It would be acceptable for the export link to go to the Single Import/Export page as long as the form is pre-populated and the results shown.

I love this idea!  @sentaidigital do you think you can try your hand at a pull request?

**Comment by sentaidigital** [comment]
backdrop/backdrop#1353

**Comment by klonos** [comment]
@quicksketch 

> I'm not entirely sure this feature is necessary. We already have the ability to export a single view under the config management page:

> ...And you can import from that same area. Seems like we should keep all the exporting/importing in the same place? Either that or we should start adding import/export in every UI: node types, image styles, etc.

...as I said back in https://github.com/backdrop/backdrop-issues/issues/1788#issuecomment-205102560 :

> ...it is less discoverable:

>Configuration -> Development -> Configuration management -> Single Import/Export -> Export -> select "Views" from the "Configuration group" drop-down -> select the view in question from the "Configuration name" drop-down

>...**that's like 7 clicks!**

...besides the "too many clicks" factor and the fact that users were used to having this feature available in a place where they expect it to also be present in Backdrop (@sentaidigital), there is also the matter of disruption of task procedures (again @sentaidigital as an example). A user needs to accomplish a task that is related to Views, but because it is also related to CMI, we ask them to leave the views admin area and navigate to the CMI admin area.

I realize that one can have a separate browser tab open to the config import/export page, but that means that you have to click back and forth between tabs. We use modals whenever we want to avoid that.

> It would be acceptable for the export link to go to the Single Import/Export page as long as the form is pre-populated and the results shown.

I like this idea too. BUT we can take this a step further and make it a generic thing that can be reused throughout the UI (for node types, image styles, etc as @quicksketch mentioned). Keeping it in a modal would ensure non-disruptive use of the feature while users are using a specific section of the admin UI. Keeping the current UI in place would accommodate users that have a workflow of heading there for all their config import/export needs anyways plus it would be the home of importing/exporting the *entire* config.

**Comment by klonos** [comment]
...my point is this:

If we implemented this so that the export link goes to the import/export page from a specific view and has the drop-down menu for config group already set to "Views" and the config name set to the view to be exported, then what is the point of having these as options there when the all the user wanted to achieve in the first place was to export the specific view. The alternative of the modal would in fact be the very same import/export page with those drop-down menus already pre-populated, but hidden from the user and the focus on the code field text that the user wants to copy.

**Comment by jenlampton** [comment]
All valid points @klonos .  I would be open to doing both.  
1) Short-term / quick-fix: link to the page we already have. 
2) Then, long-term/better-fix: improve by creating a system-wide interface that can be used to export any config file from the context in which it was created. The later could even be developed as a separate module "config exporter" or something.

**Comment by klonos** [comment]
> 1) Short-term / quick-fix: link to the page we already have. 

:+1: of course. But, as I already commented on the PR, can we please have it so that the import/export page opens in a new tab?

**Comment by klonos** [comment]
...issue title edit so that it is easier to find it when people use either one of the specific bracketed tags.

**Comment by jenlampton** [comment]
ditto :)

**Comment by klonos** [comment]
Beautiful minds :smile:

**Comment by quicksketch** [comment]
Nice one @sentaidigital!

PR at https://github.com/backdrop/backdrop/pull/1353 needs a little work to check permissions before showing the link.

**Comment by quicksketch** [comment]
Merged into 1.x for the 1.4.0 release thanks @sentaidigital!

**Comment by klonos** [comment]
Thanx!
