### ISSUE TITLE
[UX] Site information page: Do not replace path aliases with node IDs for 404/403 error pages.

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1789]
1. I have created 404 page with URL **404** in **/node/add/page**.
2. In **/admin/config/system/site-information** I have done 404 link.
3. After I have pressed on the button it says _The configuration options have been saved._ but it was not saved - the link is old **node/11**.

![1](https://cloud.githubusercontent.com/assets/13515302/14252896/fc3a3b7e-fa91-11e5-9ac5-0cb848d55f3e.png)

![2](https://cloud.githubusercontent.com/assets/13515302/14252908/02eadce4-fa92-11e5-9f7d-ca28c098cfaf.png)

**Comment by serundeputy** [comment]
Hi @bd0bd 

It saves.  It just turns the field into the internal backdrop path.  So, `node/11` is your 404 page.

If you visit: yoursite.com/someurlthatdoesntexist you should get your `node/11` page (your new 404 page).

It is confusing, but drupal does this too; perhaps we can improve it and have the form display the path alias if one exists.

**Comment by gifad** [comment]
> perhaps we can improve ...

Please display exactly what is saved in the db (or config);
because, if the alias changes…

what is debatable is : save (and display) the alias, or save (and display) the canonical URL ?

**Comment by klonos** [comment]
I think that this used to happen with the front page setting as well but we fixed it at some point. I agree that it is confusing and we should use the pathauto aliases. Lets change this to a feature request then...

**Comment by serundeputy** [comment]
It happens on menus too: admin/structure/menu/manage/main-menu

don't know if that is a separate issue or not though.  You enter a path and on save it saves the internal path of `node/nid`.

**Comment by klonos** [comment]
> Please display exactly what is saved in the db (or config);
> because, if the alias changes…

I understand your concerns, but how I believe this works (or if I'm wrong how it *should* work) for the front page field is that we read the db/config setting (which most likely is a node ID), but if that node has a path alas, then we show that in the field instead of `node/[nid]`. If we don't do that already, then that's how we should IMO.

**Comment by bd0bd** [comment]
>It saves. It just turns the field into the internal backdrop path. So, node/11 is your 404 page.

I know this but I talk about other thing - it does not save 404 link in the field like it is in front page field - if I fill in **home** then it will be **home** and not node, node/1 or something else :smile:

**Comment by serundeputy** [comment]
`PR` https://github.com/backdrop/backdrop/pull/1319
patch: https://github.com/backdrop/backdrop/pull/1319.patch

backdrop-ci test link: 
Website: http://1319.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: kxb6bkx4

**Comment by klonos** [comment]
@serundeputy very prompt! :ninja: ...left some feedback in the PR.

**Comment by gifad** [comment]
There may be permissions issues here : permission to create/edit alias should allow to indirectly edit site informations !
additionally, `admin/config/search/path/patterns/settings` > _Update action_ is not very explicit…

**Comment by serundeputy** [comment]
updated `PR` applied fix to 404 and 403, prevented `#default_value` from `admin/config/system/site-information` when no custom 404 or 403 exists.

**Comment by klonos** [comment]
Perfect! Thank you @serundeputy

**Comment by serundeputy** [comment]
This is updated with tests.
PR: https://github.com/backdrop/backdrop/pull/1319

**Comment by quicksketch** [comment]
Thanks @serundeputy! Merged https://github.com/backdrop/backdrop/pull/1319 for 1.4.0. Great job!
