### ISSUE TITLE
Installed core 1.3.4 but it says it is 1.3.x-dev

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1791]
Installed core 1.3.4 but it says it is 1.3.x-dev

RECOMMENDED VERSION
1.3.4 

What is wrong with me?

Thank you!

**Comment by herbdool** [comment]
Did you use the version linked on the front page? https://backdropcms.org/ Or did you get it from github? If on github make sure you choose the right tag before downloading the zip.

**Comment by bd0bd** [comment]
From github.
Download ZIP button.

**Comment by herbdool** [comment]
You want the easiest solution? Go to https://backdropcms.org/ and click the download button.

A more complicated solution: go to https://github.com/backdrop/backdrop, click on Branch dropdown, change to tag = 1.3.4 and then click download Zip. You were using the master branch and not one of the releases. If this is all over your head, just stick with the easy solution.

**Comment by bd0bd** [comment]
>You want the easiest solution? Go to https://backdropcms.org/ and click the download button.

Sure I know this. This is not the case. This is not what I want or need.

Thank you! Now I understand and can see what do you mean when talking about the tag.
