### ISSUE TITLE
Custom teaser field do not move to the top

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1792]
Content type - Article.

Teaser.
custom

Custom field with name **Published** at the top and field **Body** at the bottom:

But on the Article view page the field **Published** is below the **Body** (summary):

Title
**Body
Published**

In the prev version 1.3.2 or even older (do not remember) it displays in correct order:

Title
**Published
Body**

**Comment by gifad** [comment]
> Content type - Article.

> Article view page

`admin/structure/types/manage/article/fields` governs the layout of the `node/%/edit` page.

The `node/%` page layout is defined at `admin/structure/types/manage/article/display` and it can be different.

Please click at _`Show row weights`_ at the top right of both forms to point out any anormal _Weight_ values…

**Comment by bd0bd** [comment]
Thank you!
Solved.
But should not weight automatically changed if we move it up or down?

**Comment by gifad** [comment]
>  I do not understand.

I'm not sure `tabledrag.js` itself understands ~~why it works~~ the weight values : it handles rows as a whole, weights will be recomputed by the server when the form is submitted — it just shows an asterisk if the row moved…

**Comment by bd0bd** [comment]
I was VERY careful when doing it.
I did it several times before posting here my question.
I always remember to SAVE after changes done - I am not a dummy :smile: 
There was this glitch but then disappeared. 

Ok, thank you!

**Comment by klonos** [comment]
I think we can close this now.
