### ISSUE TITLE
[UX] Menu items: Do not replace the menu item path alias with the respective node ID.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1793]
This feature request is filed so we can apply the same technique as in #1789, but for menu items instead of the 404/403 error pages in the site info page: in the db/config we save the `nid`, but we show the respective path alias (if there is one) on the menu item edit form. This way, even if the path alias is changed (from the node edit form for example), the change is reflected in the path field shown in the menu edit form.

@serundeputy up for it?

**Comment by serundeputy** [comment]
@quicksketch another `PR` that did not fire travis tests; https://github.com/backdrop/backdrop/pull/1320

**Comment by quicksketch** [comment]
Weird that the tests did not start. We need a new test for this case as well, it would be great to get this completed to match the 403/404 pages which now support this.

**Comment by quicksketch** [comment]
New PR filed at https://github.com/backdrop/backdrop/issues/1390 that adds new tests.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1390 for 1.4.0! Second to last PR. Only https://github.com/backdrop/backdrop-issues/issues/698 left.
