### ISSUE TITLE
[UX] Add distinct `<code>` tag display in Seven theme

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1794]
I doubt this is a problem anywhere else, but in the Installer Browser PR, the project details dialogs displaying any `<code>` or `<pre>` tags, the only markup is a monospaced font; it is difficult to see any difference. Should we have some other styling? Background color? Padding? Border? I could make this specific to that dialog, but thought I should mention in case a broader solution would be best.

Now as is:
![codetag](https://cloud.githubusercontent.com/assets/1042283/14283866/ebce8aa2-fb12-11e5-8420-3b70e5398326.PNG)

See with light gray and a padding:
![codegray](https://cloud.githubusercontent.com/assets/1042283/14283948/58cc4eaa-fb13-11e5-80f7-9b55fb2e82df.PNG)

**Comment by klonos** [comment]
:+1:

**Comment by docwilmot** [comment]
@wesruv any thoughts on this?

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3501

Before:
![image](https://user-images.githubusercontent.com/2385329/105025157-11373f80-5aa1-11eb-9767-bc35f605e765.png)

After:
![image](https://user-images.githubusercontent.com/2385329/105025268-37f57600-5aa1-11eb-982d-41e1bb61e487.png)

**Comment by klonos** [comment]
![image](https://user-images.githubusercontent.com/2423362/105152649-1e3f4780-5b10-11eb-867b-5eedbe94bd38.png)

Looking good 👍

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3501 into 1.x and 1.18.x. Thanks for pushing this to the finish line @BWPanda and @klonos!
