### ISSUE TITLE
Seven theme's task-check.png should have transparent background

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1795]
Its white. It shouldnt be. The other images all OK.

**Comment by klonos** [comment]
Can you give an example of where it's being used please?

**Comment by docwilmot** [comment]
Project Browser :smile:

**Comment by klonos** [comment]
:laughing: :laughing: *where* in the PB? ...besides, shouldn't we instead replace it with the tick available in one of the `ui-icons-*.png` files for consistency? That one:

![ui-icons-222222-256x240](https://cloud.githubusercontent.com/assets/2423362/14300379/782c0f54-fbd3-11e5-9659-d9e47e1e5b1c.png)

Replacing all of these with icon font equivalents is a task to be done after #364 is in.

**Comment by docwilmot** [comment]
There's also `core/misc/watchdog-ok.png` which is transparent.

**Comment by klonos** [comment]
That one too :+1:

**Comment by docwilmot** [comment]
@wesruv any thought on this?

**Comment by klonos** [comment]
...as discussed during our last dev meetings, there's nothing wrong with over-tagging and assigning people to issues. They can unassign themselves or assign to another person 😉

**Comment by jenlampton** [comment]
Tagging for 1.8 since we are doing some icon cleanup and could consider this issue as well.
