### ISSUE TITLE
"Formatting options" string is not translatable

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop/backdrop-issues#1796]
I can't translate "Formatting options" string under Ckeditor.

![formatting-options](https://cloud.githubusercontent.com/assets/16973264/14383057/8b5290e0-fda3-11e5-8972-c84fb175d078.png)

Looks like it is not wrapped with t() in core Filter module.

**Comment by quicksketch** [comment]
Thanks @Al-Rozhkov for filing this issue and @fmann for fixing this! Merged into 1.x for 1.3.5 which should be out tomorrow.
