### ISSUE TITLE
by by :)

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1797]
May be I am mistaken but I think this is Jennifer's bug :smile: 

![byby](https://cloud.githubusercontent.com/assets/13515302/14512724/489067a0-01ea-11e6-8320-332aa57d7208.png)

**Comment by klonos** [comment]
I noticed this as well a few weeks ago. Don't know why I did not report it though.

...anyways, @bd0bd this queue here is for Backdrop CMS (the software). Any issues about backdropcms.org (the website) should be reported [here](https://github.com/backdrop-ops/backdropcms.org/issues).
