### ISSUE TITLE
[UX] Link module: Max length of title field should disappear when 'No title' is selected

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1798]
When you are adding a link field, there is the option to specify how you would like to handle the `Link Title`.  One of the options is `No title`.  When this option is selected, the checkbox for `Use field label for title label` is automatically hidden using #states, but the textfield for `Max length of title field` is not.

We should hide this option as well.

**Comment by klonos** [comment]
:+1: good catch @jenlampton

**Comment by serundeputy** [comment]
hidden with #states.
Patch: https://github.com/backdrop/backdrop/pull/1324.patch

Website: http://1324.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: gE9kEBvV

**Comment by klonos** [comment]
:+1: ...just a failing test that needs fixing.

**Comment by serundeputy** [comment]
it passed on php7; i suspect a false positive

**Comment by klonos** [comment]
RTBC then :smile:

**Comment by quicksketch** [comment]
Thanks @serundeputy! Merged in https://github.com/backdrop/backdrop/pull/1324 for tomorrow's 1.3.5.
