### ISSUE TITLE
page-title + page-subtitle

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1807]
Hi!

I have added a new field - Subtitle.

![3](https://cloud.githubusercontent.com/assets/13515302/14697118/bcc7b2aa-0789-11e6-9b20-72fd79bb98e7.png)

I would like this field be added to page title:

      <div class="l-container">
      <main class="l-content" role="main">
      <a id="main-content"></a>
                    
      <h1 class="page-title">Title</h1>
      <h2 class="page-subtitle">Subtitle</h2>
      
      ...

How I can understand I should make special template (layout) and add this field to.
But I do not know what sort of code it should be for Subtitle field:

        <?php if ($title): ?>
        <h1 class="page-title">
        <?php print $title; ?>
        </h1>
         <h2 class="page-subtitle">
         ------  ??? --------
         </h2>
        <?php endif; ?>

Please help?

**Comment by jenlampton** [comment]
Hm, a clever option would be to sneak the sub-title into the $title_suffix variable, as this approach would work for all layouts. See the title section from the layout template file:

```
      <?php print render($title_prefix); ?>
      <?php if ($title): ?>
        <h1 class="page-title"><?php print $title; ?></h1>
      <?php endif; ?>
      <?php print render($title_suffix); ?>
```

in `template_preprocess_layout()` you could do something like this...
```php
function themename_preprocess_layout(&$variables) {
  // Note: you could also check $context here...
  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
    $node = node_load(arg(1));
    $lang = $node->langcode;

    if (property_exists($node, 'field_subtitle') && !empty($node->field_subtitle[$lang][0]['value'])) {
      $variables['title_suffix'] .= '<h2>' . check_plain($node->field_subtitle[$lang][0]['value']) . '</h2>';
    }
  }
}
```

Note, I have not tested this code!  It should be close, but you may need to tweak things a bit.

**Comment by bd0bd** [comment]
@jenlampton, thank you!

Subtitle is added in wrong place (in **article** tag) and without **h2** tags:

         <div class="l-container">
    <main class="l-content" role="main">
      <a id="main-content"></a>
                    <h1 class="page-title">
          Title       </h1>
            
            <article id="node-22" class="node node-teammate view-mode-full clearfix" role="article">

     <div class="content clearfix">
    <div class="field field-name-field-subtitle field-type-text field-label-hidden"><div class="field-    items"><div class="field-item even">Subtitle</div></div></div>  </div>

Correctly:

         <div class="l-container">
    <main class="l-content" role="main">
      <a id="main-content"></a>
                    <h1 class="page-title">
          Title       </h1>
          <h2>Subtitle</h2>
            
            <article id="node-22" class="node node-teammate view-mode-full clearfix" role="article">
       ....

**Comment by jenlampton** [comment]
You'll need to update the field display settings to not show the field in the article if you only want it to appear once on the page.

**Comment by bd0bd** [comment]
Sorry, I do not see this option:

![1](https://cloud.githubusercontent.com/assets/13515302/14731582/b709226e-085a-11e6-9fe1-ccbbb5433233.png)

How it seems to me this code does not work at all:

     	function themename_preprocess_layout(&$variables) {
	  // Note: you could also check $context here...
	  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;

		if (property_exists($node, 'field_subtitle') && !empty($node->field_subtitle[$lang][0]['value'])) {
		  $variables['title_suffix'] .= '<h2>' . check_plain($node->field_subtitle[$lang][0]['value']) . '</h2>';
		}
	  }
	}

**Comment by jenlampton** [comment]
Under "format" select "Hidden" or you can drag the field (using the arrows on the left) down under the heading "Hidden".

**Comment by bd0bd** [comment]
But I do not need to hide it.
I need this subtitle displayed.
If I hide it then there is nothing! :smile:

**Comment by jenlampton** [comment]
> If I hide it then there is nothing!

Now there is nothing, but once you get the preprocess function there will be something!  If you don't hide it there will be two somethings ;)

**Comment by bd0bd** [comment]
Thank you!

Now after changing theme name to "bartik" I have this error:

Fatal error: Cannot redeclare bartik_preprocess_layout() (previously declared in /home/www/domain.com/themes/bartik/template.php:34) in /home/www/domain.com/core/modules/layout/layout.theme.inc on line 157

**Comment by bd0bd** [comment]
I place your code in file **layout.theme.inc**
/core/modules/layout

**Comment by jenlampton** [comment]
I was recommending that you put in your own theme, but it will need some coding skills to get it working. You'll need to print out $variables and make sure you have them all named correctly as you go. 

If writing the preprocess code is turning out to be too much for you, @quicksketch recommended that you could use the Layouts UI to place a block for the subtitle field somewhere near the page title. You won't get exactly the markup you want, but it might be close enough.

**Comment by bd0bd** [comment]
Thank you!

>to place a block for the subtitle field

This is not what I need. I have many pages with subtitles and then would need to make too many blocks.

Your offered solution is exactly what is needed. I need to add suffix.

I will ask how to add it on another forum. Thank you!

**Comment by jenlampton** [comment]
> I have many pages with subtitles and then would need to make too many blocks.

One block will work for all pages...  I don't understand.

**Comment by bd0bd** [comment]
>One block will work for all pages... 

Each Subtitle has custom content.
I would need to add 20 blocks for 20 different subtitles.
But anyway this is not good variant.

Good and right is your initial suggestion to add suffix. Thank you!

**Comment by jenlampton** [comment]
> Each Subtitle has its own (custom) content.

Yes, that's how fields work.

> I would need to add 20 blocks for 20 different subtitles.

No no,  not a custom block. A FIELD block.
* Add one field to your node (field_subtitle).  
* then add a single block for field_subtitle to all pages.

**Comment by bd0bd** [comment]
Field is added two days ago but it displays in wrong place.

>then add a single block for field_subtitle to your layout.

How. This was my initial question:

>How I can understand I should make special template (layout) and add this field to.
But I do not know what sort of code it should be for Subtitle field

**Comment by bd0bd** [comment]
<?php if ($title): ?>
    <h1 class="page-title">
    <?php print $title; ?>
    </h1>
     <h2 class="page-subtitle">
     ------  ??? --------
     </h2>
    <?php endif; ?>

**Comment by jenlampton** [comment]
Here, I made you a video :) http://screencast.com/t/44Z3PbD4l

**Comment by bd0bd** [comment]
@jenlampton, thank you very much for your help!
But this is not what I try to achieve :smile:

I would like to place a code in the template file.
The same as it is done with the title code:

		<?php if ($title): ?>
		<h1 class="page-title">
		<?php print $title; ?>
		</h1>
		<h2 class="page-subtitle">
		------  ??? --------
		</h2>
		<?php endif; ?>	

Your initial suggestion is a right one.

Or, I hope, there is a code I can directly put in <?php if ($title): ?> and Subtitle will be displayed on the user page.

**Comment by jenlampton** [comment]
I'm sorry, I can't really help you with custom code since it is specific to your site, your fields, your layouts, and your theme. 

If my first suggestion of title suffix is appealing to you, then that's probably the way to go.  If you would rather use another variable, that's also possible, as you can add that in preprocess in just the same way. You will need to print out the new variable in EVERY layout template though, so I don't recommend that approach. 

Good luck!

**Comment by bd0bd** [comment]
Thank you very much!

**Comment by bd0bd** [comment]
The variant offered in this video has no any difference from a regular variant.
It prints the subtitle (subtitle_field) in a wrong place - inside **article** tag.

I talk about adding it to page-title h1 tag.

Thank you @jenlampton.

May be somebody will tell me what is wrong with the code offered by you in initial post.

**Comment by jenlampton** [comment]
The code needs to be adapted to your site, the only one who knows that information is you, I'm afraid :)

**Comment by bd0bd** [comment]
I understand you. It could be adapted in much more short time than you have spent writing and talking to me :smile.

I will ask on the Drupal forum.

**Comment by gifad** [comment]
@jenlampton : `$variables['title_suffix']` is supposed to be a renderable array, not a plain string !
this code works, yet is does not care of other modules using title suffix…
```
function custom_bartik_preprocess_layout(&$variables) {
  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
    $node = node_load(arg(1));
    $lang = $node->langcode;
    $field_name = 'field_subtitle';

    if (property_exists($node, $field_name) && !empty($node->{$field_name}[$lang][0]['value'])) {
      $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h2>';
    }
  }
}
```

**Comment by bd0bd** [comment]
@gifad, thank you! Could you tell me please what is wrong with this construction in file **template.php**?:

	/**
	 * Prepares variables for layout template files.
	 *
	 * @see layout.tpl.php
	 */
	function bartik_preprocess_layout(&$variables) {
	  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if (property_exists($node, $field_name) && !empty($node->{$field_name}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h2>';
		}
	  }
	}
	 
	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
	}

	/**
	 * Overrides theme_menu_tree().
	 */

**Comment by jenlampton** [comment]
You can't have two functions with the same name, so put the code from the
new one into the old one. Also make sure you are using the correct field
name.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by bd0bd** [comment]
Thank you! But how do I know where it starts and where is the end of the code?

**Comment by jenlampton** [comment]
The } marks the end.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by bd0bd** [comment]
Does not work:

	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
		if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if (property_exists($node, $field_name) && !empty($node->{$field_name}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h2>';
		}
	  }
	}

If I changed field name to **field_subtitle** but anyway does not work:

	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
		if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if (property_exists($node, $field_subtitle) && !empty($node->{$field_subtitle}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_subtitle}[$lang][0]['value']) . '</h2>';
		}
	  }
	}

**Comment by bd0bd** [comment]
>Also make sure you are using the correct field name.

It is correct: **field_subtitle**

**Comment by jenlampton** [comment]
depending on the field type, `$node->{$field_subtitle}[$lang][0]['value']` might not be correct  Can you print out the field to double check?

Add this line below `$field_name = 'field_subtitle';` and see what you get.
```php
debug($node->{$field_subtitle}[$lang][0);
```

**Comment by bd0bd** [comment]
Field type is **Text (short)**

---------

**Fatal error: Cannot access empty property in /home/www/domain.com/themes/bartik/template.php on line 43**

Code:

	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
		if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';
		debug($node->{$field_subtitle}[$lang][0]);

		if (property_exists($node, $field_subtitle) && !empty($node->{$field_subtitle}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_subtitle}[$lang][0]['value']) . '</h2>';
		}
	  }
	}

**Comment by bd0bd** [comment]
If I use this:

	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
		if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if (property_exists($node, $field_subtitle) && !empty($node->{$field_subtitle}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_subtitle}[$lang][0]['value']) . '</h2>';
		}
	  }
	}

... then I get this error:

Notice: Undefined variable: field_subtitle in bartik_preprocess_layout() (line 44 of /home/www/domain.com/themes/bartik/template.php).

**Comment by gifad** [comment]
you should use either `property_exists($node, 'field_subtitle')` or `property_exists($node, $field_name)`, not `property_exists($node, $field_subtitle)`

**Comment by bd0bd** [comment]
I have changed and again the error:

Parse error: syntax error, unexpected 'property_exists' (T_STRING), expecting '(' in /home/www/domain.com/themes/bartik/template.php on line 44

	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
		if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if property_exists($node, 'field_subtitle') && !empty($node->{$field_subtitle}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_subtitle}[$lang][0]['value']) . '</h2>';
		}
	  }
	}

**Comment by bd0bd** [comment]
![1](https://cloud.githubusercontent.com/assets/13515302/14764911/f158d166-09d2-11e6-82e4-4552eae4d11a.png)

**Comment by jenlampton** [comment]
Looks like you deleted a parenthasis before `property_exists`.  It should be like this:
```php
if (property_exists($node, 'field_subtitle') && !empty($node->{$field_subtitle}[$lang][0]['value'])) {
```

**Comment by bd0bd** [comment]
I try different variants. Your one does not work too:

	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
		if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if (property_exists($node, $field_name) && !empty($node->{$field_name}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h2>';
		}
	  }
	}

**Comment by bd0bd** [comment]
>Looks like you deleted a parenthesis before property_exists

I did not.
I just copied the code given by @gifad :smile:

**Comment by jenlampton** [comment]
> I just copied the code given by @gifad

You certainly did, @gifad did not give you an if statement.  You accidentally deleted the `(` when you pasted in the new property exists function.

You'll need to work through all the error messages one at a time. Google the error messages with "PHP" to find out what's wrong, and then fix it.

If it's still not working when all the errors are gone, then print the variables out (variables are the things starting with $) using that `debug` function to make sure you have them all set correctly. Then just iterate until it starts working.

**Comment by bd0bd** [comment]
@jahaimon, thank you!

>the code below works, yet it does not care of other modules using title suffix…

@gifad, can you give me please your working code? Exactly how it is in your file **template.php** file.

Thank you!

**Comment by gifad** [comment]
@bd0bd : all code snippets I posted were copy/paste from live code, just after it had been tested.
Here is the actual code I'm using right now (with bartik theme)
```
/**
 * Prepares variables for layout template files.
 *
 * @see layout.tpl.php
 */
function bartik_preprocess_layout(&$variables) {
  if ($variables['content']['header']) {
    $tab_class = theme_get_setting('main_menu_tabs');
    $variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
  }
  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
    $node = node_load(arg(1));
    $lang = $node->langcode;
    $field_name = 'field_subtitle';

    if (property_exists($node, $field_name) && !empty($node->{$field_name}[$lang][0]['value'])) {
      $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h2>';
    }
  }
}

/**
 * Overrides theme_menu_tree().
 */
function bartik_menu_tree($variables) {
```
Perhaps it's worth noting that I'm using a core supplied layout (the 3/3/4 columns 'bartik' layout);
Don't believe that any theme work with any layout…

Also, you coud insert or replace
```
    "theme_debug": true,
```
in your config file : files/config_aa…zz/active/system.core.json
to assert which templates are actually used

**Comment by bd0bd** [comment]
@gifad, thank you!

No, it does not work. Nothing happens at all. The subtitle does not show up.

**BD 1.3.5**

I have placed 'true' ("theme_debug": true,) but I do not understand - what this is about and how to use it and why.
But I have only 1 layout - Default Layout.

If I place **debug($node->{$field_subtitle}[$lang][0]);** as was advised by @jenlampton 

	  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';
		debug($node->{$field_subtitle}[$lang][0]);
then I have error:

Fatal error: Cannot access empty property in /home/www/domain.com/themes/bartik/template.php on line 43

**Comment by Graham-72** [comment]
@bd0bd Please remind me - which layout setting are you using for your Default Layout? 1 column, 2 columns or 3/3/4 columns?

**Comment by gifad** [comment]
@bd0bd : 

1 - again : 
> you should use either `property_exists($node, 'field_subtitle')` or `property_exists($node, $field_name)`, not `property_exists($node, $field_subtitle)`.

2 - debug error : it actually means that, for this node, the `field_subtitle` is empty.

3 - theme debug adds HTML comments in the page
something like : 
```
  <body class="page logged-in node-type-article">
<!-- THEME DEBUG -->
<!-- CALL: theme('layout__three_three_four_column') -->
<!-- FILE NAME SUGGESTIONS:
   x layout--three-three-four-column.tpl.php
   * layout.tpl.php
-->
<!-- BEGIN OUTPUT from 'core/layouts/three_three_four_column/layout--three-three-four-column.tpl.php' -->
<div class="layout--three-three-four-column layout layout-two-sidebars">
```
so you can be sure of which template is actually used, and verify that it handles `$title_suffix` the same way as jen did show in her 1st reply.

**Comment by bd0bd** [comment]
@Graham-72 
2 column flipped

**Comment by bd0bd** [comment]
>you should use either 

I use the code you have gave me here.

	/**
	 * Prepares variables for layout template files.
	 *
	 * @see layout.tpl.php
	 */
	function bartik_preprocess_layout(&$variables) {
	  if ($variables['content']['header']) {
		$tab_class = theme_get_setting('main_menu_tabs');
		$variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
	  }
	  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
		$node = node_load(arg(1));
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if (property_exists($node, $field_name) && !empty($node->{$field_name}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h2>' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h2>';
		}
	  }
	}

	/**
	 * Overrides theme_menu_tree().
	 */
	function bartik_menu_tree($variables) {

**Comment by bd0bd** [comment]
I have used the layout you have used - 3/3/4 columns

**Comment by bd0bd** [comment]
I have tried all 4 layouts.

**Comment by gifad** [comment]
Sorry for the silly question, but are you sure you are on a node/## page ?
I myself have been confused for a moment, because I was actually on the home page, which looks very similar to the last edited page...

BTW, here is some code to show the subtitle in the teasers : 
```
function bartik_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'teaser') {
    $node = $variables['node'];
    $lang = $node->langcode;
    $field_name = 'field_subtitle';

    if (!empty($node->{$field_name}[$lang][0]['value'])) {
      $variables['title_suffix']['#markup'] = '<h3 class="page-subtitle">' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h3>';
    }
  }
}
```
to insert in the same core/themes/bartik/template.php

Note the subtle difference between the page title (in the layout template), and the node title (in the node template)

**Comment by bd0bd** [comment]
@gifad 
I do not understand you.
You have gave me a working code, right?
I use it.
But now you tell me:

>you should use either property_exists($node, 'field_subtitle') or property_exists($node, $field_name), not property_exists($node, $field_subtitle).

I am messed up. Your code is not working code?

**Comment by bd0bd** [comment]
>Sorry for the silly question, but are you sure you are on a node/## page ?

Sorry for my silly answer - what does it mean?

I have added a new page type - Teammates.

**Comment by bd0bd** [comment]
This does not work too

	function bartik_preprocess_node(&$variables) {
	  if ($variables['view_mode'] == 'teaser') {
		$node = $variables['node'];
		$lang = $node->langcode;
		$field_name = 'field_subtitle';

		if (!empty($node->{$field_name}[$lang][0]['value'])) {
		  $variables['title_suffix']['#markup'] = '<h3 class="page-subtitle">' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h3>';
		}
	  }
	}

**Comment by gifad** [comment]
I'm sorry, I've simplified a bit my code : I removed the ``property_exists()``call, because it's implied in the ``!empty()``call, so it's useless…
And yes, as always, it's a copy/paste from my live code.

About my confusion, I was looking at `http://domain.com/` instead of `http://domain.com/node/36`…

and yes, this is real : 
![capture d ecran 2016-04-24 a 15 06 39](https://cloud.githubusercontent.com/assets/15943462/14767780/66c67538-0a2e-11e6-95df-2fd2809dad2d.jpg)
![capture d ecran 2016-04-24 a 15 09 36](https://cloud.githubusercontent.com/assets/15943462/14767792/a43c13fa-0a2e-11e6-83d0-7ea836165ac0.jpg)

**Comment by gifad** [comment]
forgot the (new) home page
![capture d ecran 2016-04-24 a 15 12 42](https://cloud.githubusercontent.com/assets/15943462/14767802/2ec685f0-0a2f-11e6-82b5-7ebf7e0c00a0.jpg)

**Comment by bd0bd** [comment]
I have found the problem.
Please look at this issue https://github.com/backdrop/backdrop-issues/issues/1817

**Comment by quicksketch** [comment]
Closing per solution in https://github.com/backdrop/backdrop-issues/issues/1817.
