### ISSUE TITLE
Adding HTML to page body.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1808]
Is there a way I can use HTML code in the body of a page? Perhaps because I have CKeditor activated something is preventing me from doing this, even with Plain Text format.

I apologise if this is something that has already been answered but I think we have reached the point where we need some library of how-to-do-it tips.

**Comment by gifad** [comment]
Just define a text editor format (name it `Plain HTML`) where `Text editor` set to `-- None --`.
Be sure to define the same set of filters as your usual format, so they will be interchangeable…

**Comment by jenlampton** [comment]
@Graham-72 the plain text format will, by definition, not allow any HTML.

In order to type HTML into the form you'll need to 
* use the Edit Source button in the ckeditor toolbar (assuming you have it enabled)
* change a text format without the editor (use Full HTML or add a new one)

**Comment by Graham-72** [comment]
Got it! But will I remember next time? Thanks @gifad @jenlampton

**Comment by docwilmot** [comment]
> I think we have reached the point where we need some library of how-to-do-it tips.

Agreed. If you recall, we threatened to start this [here](https://github.com/backdrop-ops/backdropcms.org/issues/55) but all got diverted into other things. I think that post-1.4.0 thats where my focus will be, if project browser gets in.

**Comment by jenlampton** [comment]
It will get in!  *runs off to review it again* 
...but, yes.  We need more supporty-type things. I was just looking at the WP.org Support forums, and was thinking that perhaps we could set up a curated set like they have.  A forum-y type place might work well for tips like this.  That along with the curated documentation that's in the works would be a real win for backdrop, methinks.

**Comment by Graham-72** [comment]
:+1:  though I had to Google the term 'curated documentation' and then the first thing it came up with was a Wordpress theme :sob:
