### ISSUE TITLE
Main menu unnecessarily checks access on hidden links

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1810]
Whenever the main menu is shown (every front-end page of the site by default), access is checked on every link in the menu to determine if it should be shown or not.

This functionality is expected, but what is surprising is that the main menu contains dozens of "hidden" links, on which ~~access is checked~~ processing is done every page load. Doing a query in MySQL shows these items:

```
mysql> select * from menu_links where menu_name = 'main-menu`;
+-----------+------+------+------------------------------+
| menu_name | mlid | plid | link_path                    |
+-----------+------+------+------------------------------+
| main-menu |   20 |    0 | comment/reply/%              |
| main-menu |   22 |    0 | filter/tips/%                |
| main-menu |  142 |    0 | search                       |
| main-menu |  145 |    0 | taxonomy/term/%              |
| main-menu |  211 |    0 | <front>                      |
| main-menu |  394 |    0 | node/%                       |
| main-menu |    3 |    0 | comment/%                    |
| main-menu |   21 |    3 | comment/%/approve            |
| main-menu |   23 |    3 | comment/%/delete             |
| main-menu |   24 |    3 | comment/%/edit               |
| main-menu |   25 |    3 | comment/%/view               |
| main-menu |  264 |    3 | comment/%/devel              |
| main-menu |  143 |  142 | search/node                  |
| main-menu |  144 |  142 | search/user                  |
| main-menu |  146 |  143 | search/node/%                |
| main-menu |  150 |  144 | search/user/%                |
| main-menu |  153 |  145 | taxonomy/term/%/delete       |
| main-menu |  154 |  145 | taxonomy/term/%/edit         |
| main-menu |  155 |  145 | taxonomy/term/%/view         |
| main-menu |  273 |  145 | taxonomy/term/%/devel        |
| main-menu |  275 |  264 | comment/%/devel/load         |
| main-menu |  278 |  264 | comment/%/devel/render       |
| main-menu |  281 |  273 | taxonomy/term/%/devel/load   |
| main-menu |  282 |  273 | taxonomy/term/%/devel/render |
| main-menu |  396 |  394 | node/%/delete                |
| main-menu |  397 |  394 | node/%/devel                 |
| main-menu |  398 |  394 | node/%/edit                  |
| main-menu |  402 |  394 | node/%/view                  |
| main-menu |  401 |  394 | node/%/revisions             |
| main-menu |  403 |  397 | node/%/devel/load            |
| main-menu |  404 |  397 | node/%/devel/render          |
| main-menu |  405 |  401 | node/%/revisions/%/delete    |
| main-menu |  406 |  401 | node/%/revisions/%/revert    |
| main-menu |  407 |  401 | node/%/revisions/%/view      |
+-----------+------+------+------------------------------+
34 rows in set (0.00 sec)
```

Although `menu_build_tree()` caches the SELECT statement from the database, `menu_tree_check_access()` is called on each item every page load.

The cause of this is that menu items default to saving items into the main menu, even if they contain wildcards like `node/%`, which can't be shown in the menu anyway. It's also odd that sub-menu items like `search/node` have their access checked, when at most `search` would ever be shown.

What I'd like propose is that instead of defaulting items to `main-menu` in `hook_menu()`, we make a new separate menu that is used just for internal link tracking. This menu can't actually be shown as a block, but it may be used to keep track of hierarchical relationships such as menu local tasks and actions. This keeps our functionality unchanged while saving the main menu block from needing to load and check access on these items that will never be shown in the first place.

**Comment by quicksketch** [comment]
Here's what _should_ be in the main menu by default out of the box:

```
mysql> select * from menu_links where menu_name = 'main-menu';
+-----------+------+------+-----------+-------------+------------+
| menu_name | mlid | plid | link_path | router_path | link_title |
+-----------+------+------+-----------+-------------+------------+
| main-menu |  142 |    0 | search    | search      | Search     |
| main-menu |  211 |    0 | <front>   |             | Home       |
+-----------+------+------+-----------+-------------+------------+
2 rows in set (0.00 sec)
```

That change would save us a few menu access checks and about 30 `_menu_link_translate()` calls.

I found that dynamic menu item paths such as `node/%` aren't actually checked for access, but there is still a fair amount of processing spent attempting to "translate" wildcard paths into a non-wildcard path. It's still going to be the case that these items aren't ever going to be displayed in the main menu block.

I'll file a PR and see what Travis says about this suggestion.

**Comment by biolithic** [comment]
ha ha, nice!

**Comment by quicksketch** [comment]
Some test failures on the first attempt, not surprising considering this would be a technical API change. If you want your menu links to be in the `main-menu` by default, you now have to specify `$item['menu_name'] = 'main-menu'` in `hook_menu()`. As a matter of my past experience with contrib and custom modules, you almost never want to make a menu item in the primary navigation when a module is installed. Even as "suggested item" such as search provides is questionable, and something we should evaluate.

Updated the PR to specify the main-menu in the necessary test module's `hook_menu()`. https://github.com/backdrop/backdrop/pull/1330

**Comment by quicksketch** [comment]
Merged inhttps://github.com/backdrop/backdrop/pull/1330 for 1.4.0 now that tests are passing. We need to make a change record for this item yet.

**Comment by quicksketch** [comment]
We introduced a problem here that the admin menu ends up being affected. Somehow the menu links for menus themselves end at the top level.

PR filed at https://github.com/backdrop/backdrop/pull/1391.

**Comment by jenlampton** [comment]
That PR does the trick for me, upgrades now proceeding with no lost admin menu items.

**Comment by quicksketch** [comment]
Great! Merged the fix.

**Comment by docwilmot** [comment]
Is this what you were seeing? Still getting this. Existing site, updated to latest code.

![menu](https://cloud.githubusercontent.com/assets/1042283/15295293/cb604614-1b5d-11e6-99f2-d37a281e8bf8.PNG)

**Comment by quicksketch** [comment]
Thanks @docwilmot! Yes that was exactly the problem that should have been solved! I believe this problem can be remedied by visiting the Administration menu (`admin/structure/menu/manage/management`) and deleting the incorrect top-level items. This will then automatically recreate the menu items, which can then be reverted to their original positions.

> Existing site, updated to latest code.

As this was only fixed yesterday, do you know if you had already been running the latest code? Is it possible you ran the update prior to it having been fixed?

**Comment by quicksketch** [comment]
While reviewing this a second time, I found that the `LIKE` query checking for wildcards has another issue in that it's not properly escaping the `%` character.

```
  db_query("DELETE FROM {menu_links} WHERE link_path LIKE '%/%%%' AND module = 'system' AND menu_name = 'main-menu'");
```

This is supposed to be checking for paths that have a wildcard in them, such as `node/%`. But it instead is only checking for paths that have any slash in them, so `node/1` would match, for example.

However, this will only affect a particular situation:

- Only menu items defined via `hook_menu()` in a module will be affected that are of type NORMAL_MENU_ITEM.
- Only menu items containing a slash will be affected.
- Only menu items that were not under "admin/" or had not specified a `menu_name` key.

The menu items will automatically be recreated, but they will be assigned to the "internal" menu and not show up in the main-menu. They will also loose any custom weight that has been set.

**Comment by docwilmot** [comment]
yes very likely. I ran update a couple of times after trying to figure out a strange issue with local tests. No worry.

**Comment by quicksketch** [comment]
> yes very likely.

Sweet, well I'll test again just to be sure. On the bright side we found another bug that we might not have noticed.

Follow-up PR filed at https://github.com/backdrop/backdrop/pull/1393.

**Comment by quicksketch** [comment]
Tested an upgrade from 1.3.0 to 1.4.0, menu items are all correct in the Admin Bar. It's actually fine even without this PR, unless you have a menu link that meets all the above requirements, in which case that one link may disappear.

So merged in https://github.com/backdrop/backdrop/pull/1393, to solve the lingering issue found here. Thanks @docwilmot!

**Comment by BWPanda** [comment]
CR added in https://github.com/backdrop/backdrop-issues/issues/4797
