### ISSUE TITLE
Status badge on admin bar not shown on first page load.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1813]
So, cron run, it detected a new security release and it warned me right after the first page load via the regular message:

![no_badge_on_admin_bar](https://cloud.githubusercontent.com/assets/2423362/14758140/125bfb5c-093f-11e6-856f-c690fdf92cb0.png)

...but as you can see there was no badge about that in the admin bar.

Refreshing the page revealed the badge, so this happens _only_ on first page load after there is a warning. The error message is fired, the badge is not.

**Comment by BWPanda** [comment]
Is this still happening with the latest version?

**Comment by klonos** [comment]
Nope, I have not seen this happen in years now, and no other person has reported it.

**Comment by klonos** [comment]
...I quickly confirmed that this is no longer happening:

- cloned and setup a fresh Backdrop site on my local
- before running the installer, I have changed the definition of `'BACKDROP_VERSION'` in bootstrap.inc to `'1.13.2'`.
- run the installer -> soon as the site span up, both the error and the badge were shown 👍
