### ISSUE TITLE
Page title suffix does not show up if any language is selected

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1817]
Well, after a lot of talking - https://github.com/backdrop/backdrop-issues/issues/1807 - I have detected the problem.

**This happens if any language is selected:**

![2](https://cloud.githubusercontent.com/assets/13515302/14768140/ec79940e-0a41-11e6-89a0-83def1a877ce.png)

**If none is selected then page title suffix is printed out:**

![111](https://cloud.githubusercontent.com/assets/13515302/14768161/a065c1c2-0a42-11e6-9eb3-6031bf0561a8.png)

**Comment by bd0bd** [comment]
May be somebody could tell me how to fix this?
Is it a bug or my mistake?

**Comment by bd0bd** [comment]
Why nobody of developers talk about this issue https://github.com/backdrop/backdrop-issues/issues/1806 - it seems is a bug.

**Comment by gifad** [comment]
> Why nobody of developers talk

Most core developpers are located at GMT-7, and that's sunday morning…

> it seems is a bug

Fortunately, it's our (@jenlampton and I) bug : in a language aware environment, the correct way of referencing fields is to use the right function : `field_get_items()`.

This code works, then : 
(I kept he wrong code, commented, for reference)
```
function bartik_preprocess_layout(&$variables) {
  if ($variables['content']['header']) {
    $tab_class = theme_get_setting('main_menu_tabs');
    $variables['content']['header'] = '<div class="l-header-inner ' . $tab_class . '">' . $variables['content']['header'] . '</div>';
  }
  if (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
    $node = node_load(arg(1));
//- $lang = $node->langcode;
    $field_name = 'field_subtitle';

    $fields = field_get_items('node', $node, $field_name); //+

//- if (!empty($node->{$field_name}[$lang][0]['value'])) {
    if (!empty($fields[0]['value'])) { //+
//-   $variables['title_suffix']['#markup'] = '<h2 class="page-subtitle">' . check_plain($node->{$field_name}[$lang][0]['value']) . '</h2>';
      $variables['title_suffix']['#markup'] = '<h2 class="page-subtitle">' . check_plain($fields[0]['value']) . '</h2>'; #+
    }
  }
```

**Comment by bd0bd** [comment]
@gifad, thank you very much for your help!

Now it works!

BTW - would be good to correct this code. At the end there is no '}'

**Comment by gifad** [comment]
Fixed typo, thanks — and good luck in your translation trail

**Comment by bd0bd** [comment]
@gifad, thank you! :smile:
