### ISSUE TITLE
Avoid multiple HTML heading level 1 (h1) at front-page

### ISSUE THREAD

**Issue by ItangSanjana** [backdrop/backdrop-issues#1820]
If front page has a title which is wrapped in heading level 1 (h1), the site name also wrapped  in heading level 1. I heard that this is not good. But I do not know...

**Comment by bd0bd** [comment]
>I heard that this is not good.

Now days it is good, very good.
You can have even 10 h1 tags on a page - it is ok.

**Comment by ItangSanjana** [comment]
Ow ok than...
