### ISSUE TITLE
Restore node_operations().

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1823]
`hook_node_operations()` has been removed, and more importantly, `node_node_operations()`.

is there a replacement method to call `node_mass_update()` (which is still alive) in a batch process, other than a view ?

**Comment by quicksketch** [comment]
> is there a replacement method to call node_mass_update() (which is still alive) in a batch process, other than a view ?

`node_mass_update()` starts a batch operation, so you can call it from any form submit handler if you would like to use it still. e.g.

```
function my_form($form, $form_state) {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update nodes');
  );
}
function my_form_submit(&$form, &$form_state) {
  $nodes = node_load_multiple(array(1, 2, 3));
  $updates = array(
    'published' => 1,
  );
  node_mass_update($nodes);
}
```

This should work fine even without `hook_node_operations()` as it isn't used within `node_mass_update()`.

**Comment by gifad** [comment]
Thanks for the reply, but I do not “would like to use it still" !

To show this form, [bulk_media_upload](https://github.com/Graham-72/bulk_media_upload) uses `foreach (module_invoke_all('node_operations') …`

I thought it was a better method than harcoding everything like in your example…
![capture d ecran 2016-04-25 a 21 53 32](https://cloud.githubusercontent.com/assets/15943462/14797151/6da66972-0b31-11e6-8fc4-5d51b1bb3bb4.jpg)

FYI, this screenshot is with this PR applied, and the Select2 and Custom Publishing Options contrib modules.

**Comment by quicksketch** [comment]
> To show this form, bulk_media_upload uses foreach (module_invoke_all('node_operations') …

Ah, so what you want to do is provide bulk operations. In that case you want to start using the Actions system. In Drupal 7 there were 3 action systems: one for bulk editing comments, one for nodes, and then the actions used for triggers. In Backdrop these were all combined into the single actions system.

There is *not* yet a batch function for this system, though you could make one by creating a function similar to `node_mass_update()`. For starters though, you can probably skip using a batch unless you're processing hundreds of items at the same time. In which case your form would look something like this:

```php
function my_module_form() {
    // Get all available actions.
    $actions = actions_get_info();
    // Only allow actions that are valid for this entity type.
    if ($action_info['type'] == 'node') {
      $options[$action_name] = $action_info['label'];
    }
    $form['action'] = array(
      '#type' => 'select',
      '#options' => $options,
      '#empty_option' => '- ' . t('Choose an action') . ' -',
    );

     // Rest of form for selecting items....
}
function my_module_form_submit() {
      $action_name = $form_state['values']['action'];
      $action_info = actions_get_info($form_state['values']['action']);
      $count = 0;

      // Filter only selected checkboxes.
      $selected = array_filter($form_state['values'][$this->options['id']]);
      if (!empty($selected)) {
        $entities = entity_load('node', $selected);
        $context = array();
        foreach ($entities as $entity) {
          actions_execute($action_name, $entity, $context);
          $count++;
        }

        // Redirect the user the same as we would for $form_state['redirect'].
        if (isset($context['redirect'])) {
          actions_redirect($context['redirect']);
        }
      }
  }
}
```

**Comment by gifad** [comment]
Thanks, @quicksketch, but again it's not `my_module`, it's [bulk_media_upload](https://github.com/backdrop-contrib/bulk_media_upload), for which I would not like to commit : 
```
diff --git a/bulk_media_upload.summary.inc b/bulk_media_upload.summary.inc
index 1aa9c4e..7fc1bbc 100644
--- a/bulk_media_upload.summary.inc
+++ b/bulk_media_upload.summary.inc
@@ -249,3 +249,49 @@ function bulk_media_upload_summary_node_multiple_delete_confirm_submit($form, &$
   }
   $form_state['redirect'] = 'admin/content/media/bulk_upload/summary';
 }
+
+/**
+ * Implements hook_node_operations().
+ */
+function bulk_media_upload_node_operations() {
+  if (function_exists(node_node_operations)) {
+    return array();
+  }
+  $operations = array(
+    'publish' => array(
+      'label' => t('Publish selected content'),
+      'callback' => 'node_mass_update',
+      'callback arguments' => array('updates' => array('status' => NODE_PUBLISHED)),
+    ),
+    'unpublish' => array(
+      'label' => t('Unpublish selected content'),
+      'callback' => 'node_mass_update',
+      'callback arguments' => array('updates' => array('status' => NODE_NOT_PUBLISHED)),
+    ),
+    'promote' => array(
+      'label' => t('Promote selected content to front page'),
+      'callback' => 'node_mass_update',
+      'callback arguments' => array('updates' => array('status' => NODE_PUBLISHED, 'promote' => NODE_PROMOTED)),
+    ),
+    'demote' => array(
+      'label' => t('Demote selected content from front page'),
+      'callback' => 'node_mass_update',
+      'callback arguments' => array('updates' => array('promote' => NODE_NOT_PROMOTED)),
+    ),
+    'sticky' => array(
+      'label' => t('Make selected content sticky'),
+      'callback' => 'node_mass_update',
+      'callback arguments' => array('updates' => array('status' => NODE_PUBLISHED, 'sticky' => NODE_STICKY)),
+    ),
+    'unsticky' => array(
+      'label' => t('Make selected content not sticky'),
+      'callback' => 'node_mass_update',
+      'callback arguments' => array('updates' => array('sticky' => NODE_NOT_STICKY)),
+    ),
+    'delete' => array(
+      'label' => t('Delete selected content'),
+      'callback' => NULL,
+    ),
+  );
+  return $operations;
+}
```
without either patch, I would get : 
![capture d ecran 2016-04-26 a 01 07 30](https://cloud.githubusercontent.com/assets/15943462/14801669/70e50868-0b4b-11e6-80fb-776a291e8e5d.jpg)
instead of https://github.com/backdrop/backdrop-issues/issues/1823#issuecomment-214503901

Of course, I would prefer the core patch, which could be usefull to others.

But if you consider this is obsolete or whatever, please explicitly "Close (won't fix)", so I can fix the issue the other way.

**Comment by quicksketch** [comment]
Ah, okay man sorry I'm hitting all around the question. Yes, Bulk Media Upload should be updated to use `hook_action_info()` instead of `hook_node_operations()`. We won't be adding the old hooks back again, they've been combined into a single hook instead of a different one for each type of data.

**Comment by gifad** [comment]
Ok, now it's clear.
For the next issue, please don't waste your time to teach me programming : I tagged 'feature request', not 'support request' .

BTW, I won't submit an issue for "Restore `entity_type_supports()`, I'll just : 
```
diff --git a/bulk_media_upload.admin.inc b/bulk_media_upload.admin.inc
index a728cd0..d55a437 100644
--- a/bulk_media_upload.admin.inc
+++ b/bulk_media_upload.admin.inc
@@ -15,8 +15,15 @@ function bulk_media_upload_admin($form, &$form_state) {
   $options = array();
 
   foreach ($entity_types as $entity_type => $entity_info) {
-    if ($entity_info['fieldable'] && entity_type_supports($entity_type, 'save')) {
-      $types[$entity_type] = $entity_info['label'];
+    if ($entity_info['fieldable']) {
+      // check entity_type supports 'save'
+      if (isset($entity_info['controller class'])) {
+        $class = $entity_info['controller class'];
+        $methods = get_class_methods ($class);
+        if (in_array('save', $methods)) {
+          $types[$entity_type] = $entity_info['label'];
+        }
+      }
     }
   }
 ```
:smirk:
