### ISSUE TITLE
Layout default region not actually set to `content` by default.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1825]
It looks like all the layouts in core had a default region defined, but it's supposed to be optional. However, excluding that option from a layout template file throws a PHP notice:

```
Notice: Undefined index: default region in backdrop/core/modules/layout/plugins/renderers/layout_renderer_standard.inc on line 565
```

**Comment by quicksketch** [comment]
Thanks, merged into 1.x and 1.3.x in https://github.com/backdrop/backdrop/pull/1348.
