### ISSUE TITLE
entity_create() doesn't create viable node objects

### ISSUE THREAD

**Issue by sentaidigital** [backdrop/backdrop-issues#1827]
A site builder can set default settings for nodes in admin/structure/types/manage/[content-type], such as published, promoted, and comments enabled and expects them to be applied whenever a new node of that type is created, for example through node/add/post.

As a module developer, I would also expect those settings to be applied when programmatically creating a node via `entity_create('node', ...)` unless I override them, either through the `$values` array passed to `entity_create()` or directly on the new object.  However, `node_object_prepare()` is never called on programmatically created objects, leaving the defaults to not published, not promoted, etc, regardless of the settings in admin/structure/types/manage.  

In the case where the UID of the new node is not set, then `$node->save()` will fail with the error "Integrity constraint violation: 1048 Column 'last_comment_uid' cannot be null."

This is not the case for User or other entities.  There is no such thing as `user_object_prepare()` or `comment_object_prepare()`.

I think the right answer is to call `node_object_prepare()` from `Node::__construct()`, but if there is a better place, I'm all ears.  I do not think it should be the responsibility of every contributed module developer trying to create nodes in code to call `node_object_prepare()`.

The attached archive includes a bare-bones sample module demonstrating the issue.

[mymodule.zip](https://github.com/backdrop/backdrop-issues/files/244214/mymodule.zip)

**Comment by quicksketch** [comment]
Great write-up @sentaidigital. I totally agree on all counts. One thing that might be an issue (not sure) is that node_object_prepare() is intended to be used on the node form. Some modules populate values in the $node object that differ from the form element values used in the node form.

It's also likely this will have some performance impact. Previously there wouldn't have been any defaults populated into the node object, and now we'll be asking every module for defaults. We'll want to optimize our implementations of `hook_node_prepare()` to minimize any performance impact on pages that are going to be loading/creating a lot of nodes.

**Comment by sentaidigital** [comment]
Creating a lot of brand new nodes is not a big deal.  There are few pieces of code that do it in any volume, and the more nodes they create, the more likely they are to use the batch API.

The problem is loading existing nodes, as you point out, will now call `hook_node_prepare()`, which amounts to an API change.  And a pretty significant one, not just in terms of performance cost, but also the semantic meaning of "prepare."  No doubt, there are modules that rely on the fact `hook_node_prepare()` is called from `node_object_prepare()` and not during`node_load()`.

So, `Node::__construct()` is clearly _not_ the place to call it.

**Comment by quicksketch** [comment]
We could also simply determine if the node were new or not, as existing nodes will be loaded from a database row, and prepopulated with a NID to start. So possibly we might populate the defaults on new nodes but not when an NID is passed in. However, preparing should be it's own separate method, e.g. `$node->prepare()`, which could also be called from the constructor, for new nodes only. Doesn't seem very clean to me though, I don't like the inconsistency that it would only be called on new nodes, but for the purposes of working with our current APIs, it would fit right in.

**Comment by klonos** [comment]
Is this still an issue?

**Comment by BWPanda** [comment]
Guess not. Will close due to lack of interest/feedback.

**Comment by docwilmot** [comment]
This seems to be back? https://forum.backdropcms.org/forum/error-creating-simple-node-comments

**Comment by kiamlaluno** [comment]
`node_object_prepare()` has the pro of allowing modules to initialize a node that is created, but it also initialize some properties without verifying they have been set. It should be probably called before setting the entity property with values taken from `$values`.

As a side note, I would extend `hook_node_prepare()` to any entity. I think it would make sense to allow module to initialize an entity when it's created.
