### ISSUE TITLE
[UX] Fix font-weight for labels inside fieldsets in Seven theme

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1828]
In https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/css/system.theme.css#L103 we set the font to bold for labels, but in https://github.com/backdrop/backdrop/blob/1.x/core/themes/seven/css/style.css#L780 we override it with normal.

This causes the following:
- forms without any fieldsets get bold labels for all fields
- forms with _all fields_ wrapped in fieldsets get normal labels for all fields
- forms with _some_ of their fields wrapped in fieldsets get a mix of both bold and normal labels

Was this intentional? If yes, what is the reasoning?

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2911

**Comment by klonos** [comment]
...as an example use case, in https://github.com/backdrop-contrib/devel/issues/4 we are trying to get a "Enable theme debug" checkbox within a "Core system devel settings" fieldset:

![backdrop-seven-font_weight_overridden_for_labels_inside_fieldsets](https://cloud.githubusercontent.com/assets/2423362/15093950/977cd162-14d9-11e6-9c4b-132c9bf8a155.png)

...there is also a series of options for setting the Watchdog severity levels and as you can see its label is not set to bold as it should.

**Comment by klonos** [comment]
I believe that the intention of the change to normal font was to make the fieldset **legends** (`.fieldset-legend`) have normal font; whereas we have made `fieldset label` normal instead.

Here's a side-by-side screenshot that shows what the problem is (left is how things should be - right is current situation):

![screencapture-1610-lndo-site-444-admin-structure-types-manage-post-fields-field-image-edit-2019-09-29-09_29_35](https://user-images.githubusercontent.com/2423362/65823588-7491d280-e29c-11e9-85d3-e6f5b67c8dc9.png)

**Comment by stpaultim** [comment]
This looks good to me and seems to be working as expected in the sandbox. I'll mark as works for me.

**Comment by quicksketch** [comment]
Agreed this is a good candidate for 1.14.1 (or next bugfix if it doesn't get into that release).

**Comment by quicksketch** [comment]
Thanks! I've merged https://github.com/backdrop/backdrop/pull/2911 into 1.x and 1.14.x.

**Comment by klonos** [comment]
Thanks you so much @quicksketch 👍 ...this has been annoying me like forever!
