### ISSUE TITLE
Remove mention of `hook_views_default_views()` from docs

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1830]
In the docblock for `hook_views_api` we mention `hook_views_default_views()` but that function does not exist in backdrop. I recommend we change 

```
This is required for your module to have its include files loaded; for example, when implementing hook_views_default_views().
```

to 

```
This is required for your module to have its include files loaded.
```

Also, we should add a change record to help new Backdrop developers transition from using `hook_views_default_views` to config.

Releveant page on api site: https://api.backdropcms.org/api/backdrop/core!modules!views!views.api.php/function/hook_views_api/1

**Comment by BWPanda** [comment]
Since this change was part of adding Views to core way back when, I've updated this Change Record re. `hook_views_default_views()` instead of creating a new one: https://docs.backdropcms.org/change-records/views-added-to-core

**Comment by BWPanda** [comment]
I also made a PR to change the documentation of `hook_views_api()` as above. Since it's just a comment change I've goneahead and merged it into 1.x: https://github.com/backdrop/backdrop/pull/4340

Thanks for bringing this up @jenlampton! And sorry for the delay!
