### ISSUE TITLE
Web shop solution

### ISSUE THREAD

**Issue by thamas** [backdrop/backdrop-issues#1831]
We are planning a new project where Backdrop seems to be a good fit. Expect one thing: later (not in the current project) the client plans to add web shop functionality to the site. 

I found just simple cart module for Backdrop which may not be the ideal solution.

Do you have any other information, suggestion? Is there any plan to an ecommerce solution for Backdrop? Or any supported e-commerce service (which is available in Hungary)?

**Comment by biolithic** [comment]
Hi Tamás,
Thank you for your interest in Backdrop!  We are currently working very
hard on version 1.4 due in 10-12 days, plus existing work on Drupal
support.  Also, Drupalcon is coming up very soon for some people in
Backdrop.
Currently, there are:

https://github.com/backdrop-contrib/simple_paypal_donate
https://github.com/backdrop-contrib/basic_cart

After features are in for version 1.4, expect
https://github.com/biolithic/basic_cart_plus to have time to be worked on
and a demo put up.  It is built on Paypal, Braintree and Stripe.  You must
look at whether any of those services are supported in your country.  You
are welcomed to hire me to complete/configure a version to your needs after
this week.  It may be too simple for you at the moment.

There is always Commerce Kickstart for D7 but it may be too heavy for you.

There also exists https://github.com/codewombat/backshop/issues/1 but
development is stalled on that and I don't know anything about it.  You may
finish it (?) or hire Commerce Guys to finish it.

That is what I know as only a Backdrop community member.

**Comment by klonos** [comment]
Hey @thamas, you might be interested in [this comment](https://github.com/backdrop-ops/contrib/issues/34#issuecomment-216664916) by @richie-harris-smc :wink:

**Comment by biolithic** [comment]
Yea, just saw that!

**Comment by quicksketch** [comment]
> Is there any plan to an ecommerce solution for Backdrop? Or any supported e-commerce service (which is available in Hungary)?

In addition to the Backdrop solutions @biolithic listed so far, I'd personally encourage you to avoid self-hosting any kind of ecommerce, especially handling any credit card data yourself. I've had good past experiences with Shopify, which seems to operate in Hungary: https://www.shopify.com/payment-gateways/hungary

I plan on eventually porting my [Recurly module](https://www.drupal.org/project/recurly) to Backdrop eventually, but that's really best for recurring payments rather than a store.

**Comment by thamas** [comment]
Thank you all for the comments! I'll check your suggestions! 

@biolithic I've used Basic cart with Drupal 7 earlier, but it made headaches for me because it is based on features and which made it's customization harder for us.

@quicksketch Handling credit card data is not in the list of the goals but to be able to shell "things" is. And I think the best solution (best UX) is when the webshop and the cms are not two different system. That's why we used Commerce with Drupal 7 in in earlier projects.

**Comment by robertgarrigos** [comment]
I wonder: how is this question? I'm building a simple shop and planning to use this payment gateway (https://github.com/CommerceRedsys/sermepa) to create a module for backdrop (I already wrote a payment gateway for drupal 6, years ago). Have things moved since May 2016??. It seems the best bet would be to use basic cart to implement the gateway.

**Comment by docwilmot** [comment]
I ported Payment module a while back. Haven't released yet as I was hoping for some feedback. 
https://github.com/backdrop-contrib/payment
Thinking though should probably release as alpha if I want feedback.

**Comment by BWPanda** [comment]
Seems there are quite a few options for Backdrop now, including [Ubercart](https://github.com/backdrop-contrib/ubercart). So will close this question as 'answered'.

**Comment by klonos** [comment]
For anyone else coming here in the future, may I also add that you can look for relevant posts in our forum: https://forum.backdropcms.org

Some existing posts at the time of writing include:

https://forum.backdropcms.org/forum/e-commerce-solutions-backdropcms
https://forum.backdropcms.org/forum/cart-basic
