### ISSUE TITLE
Improve tests speed by reusing setUp structure for each test

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1835]
I am looking how to properly reuse setUp without creating conflict and have fresh setup for each test.
Task could be assigned to me.

**Comment by klonos** [comment]
Just tried assigning the issue to you but the autocomplete field does not have you GitHub handle available (??).

**Comment by klonos** [comment]
![backdrop-github-cannot_assing_issue_to_gor](https://cloud.githubusercontent.com/assets/2423362/15065356/2f00a664-13a2-11e6-8d8a-4a866d742bbd.png)

**Comment by Gormartsen** [comment]
@klonos tnx. I assume it's because I am not a part of backdrop/backdrop-issue team

**Comment by klonos** [comment]
@Gormartsen you are absolutely right.

**Comment by Gormartsen** [comment]
Summary from PR:

- .travis.yml
  - added xcache to php 5.3 tests (4 min less by each job)
  - concurrency changed to 2, because TRAVIS instance is powered by 2 CPU.
  - option `--cache` enabled by default
- tests
  - moved `field_cache_clear` to  field_test.install. There is no need to call 'field_cache_clear' after each test.
  - if installation profile cache exists, database and config get copied from cache
- run-test.sh
  - option `--cache` turn on installation profile database and config cache.
  - option `--clean` is cleaning installation profile database and config cache.
  - BACKDROP_ROOT  fixed to avoid issues when core folder linked to other directory.

As a result - tests are running almost 2x times faster.

**Comment by klonos** [comment]
> As a result - tests are running almost 2x times faster.

That's all we need to know. Yay!! Thanx @Gormartsen :clap:

**Comment by quicksketch** [comment]
This is awesome @Gormartsen! Test time is indeed cut in half. Great job!

I filed a new PR at https://github.com/backdrop/backdrop/pull/1366 that does a bit of clean up on the `BackdropWebTestCase` class. I made a change to it to use `$this->fileDirectoryName` in `prepareEnvironment()` so that we don't need to override that same method in your new class. I also did some clean up on the class that I'd been wanted to do for a while, fixing all the PHP inspections in PHPStorm.

Tests seem to be passing. I'll merge in the new version shortly.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1366. We have a random fail happening pretty frequently. I've picked back up at https://github.com/backdrop/backdrop-issues/issues/1478#issuecomment-218927947 to fix that issue.

**Comment by LionsAd** [comment]
@Gormartsen This is a really awesome patch! Congratulations!

The idea not to use a DUMP, but instead to CREATE table LIKE X and INSERT INTO is great!

**Comment by Gormartsen** [comment]
@quicksketch thank you for cleaning code. 

@LionsAd create table is still slow even on SSD disks. If you noticed, I added ALTER table to cache prepare phaze . MyISAM is faster for drop create table. A huge performance boost are coming from moving MySQL data dir to memory. (Like /dev/shm)
