### ISSUE TITLE
File system settings: Default download method options: remove period from input labels.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1838]
The options are "Public local files served by the webserver." and "Private local files served by Backdrop.". AFAIK, we do not use periods at the end of checkbox/radio labels elsewhere (and if we do, we shouldn't).

PR coming up...

**Comment by quicksketch** [comment]
Thanks @klonos! Let's update the documentation examples as well in hook_stream_wrappers().

**Comment by klonos** [comment]
PR updated! ...switching back to "needs review".

**Comment by quicksketch** [comment]
Merged for 1.4.0 in https://github.com/backdrop/backdrop/pull/1358. Thanks @klonos!
