### ISSUE TITLE
Add icons to the Admin Bar

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1841]
Follow-up for #364 and part of #1839...

We should add icons to the Admin Bar. This will make Backdrop both more usable, and more beautiful. 

Current Admin Bar:
<img width="1428" alt="screen shot 2019-01-06 at 4 16 47 pm" src="https://user-images.githubusercontent.com/397895/50743574-82636d00-11ce-11e9-8acc-1f86d7b829e7.png">

Admin Bar with proposed icons:
<img width="1407" alt="screen shot 2019-01-10 at 3 43 44 pm" src="https://user-images.githubusercontent.com/397895/51004204-89e88600-14ee-11e9-87cf-746b564e9872.png">

I didn't like the Content icon (pencil) being right next to the Home icon (house). So I added the word "Home" next to the house icon.

I also only included them on the top-level links, and only on desktop (when we're sure there's enough room for them)

The one part of the PR that could use work is the addition of the classes. I'm currently adding a class to every link based on it's URL. It might be smarter to only add classes where they are needed (top-level only) and maybe name them something different? I liked these names because the paths will never change, where something like mlid could be different on every site.

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2456

**Comment by jenlampton** [comment]
@klonos I'm stealing this issue, and re-purposing it to simply add icons into admin bar. 

I don't see a reason to add an admin UI in core, that can be added in contrib. We'll just do this (and get it as close to "right" as possible) so most people won't need to worry about changing it.

**Comment by jenlampton** [comment]
Previous comment from @klonos (so it won't be lost!) follows:

We should allow icons to be used in menus. For Drupal, the [Icon API](https://www.drupal.org/project/icon) module includes the icon_menu submodule that allows:

![drupal-contrib-icon_menu](https://cloud.githubusercontent.com/assets/2423362/15094454/f41089ce-14e7-11e6-9225-b34f1a1d0638.png)
1. **Selecting an icon** (from whatever font is provided by the Icon API). Perhaps we should implement it as an auto-complete search field instead of a huge drop-down though.
2. **Selecting to position the icon before or after the menu item title**. Perhaps we should also allow replacing the menu item title with the icon as 3rd option. Use case for that: the home icon on the admin bar.
   
   If we allow breakpoints to come into play perhaps we could even switch to an icon-only version of the admin bar for mobile/screens (top-level items only) like the vertical admin menu bar in WordPress:
   
   ![wp-admin_menu-collapse_to_icons_only](https://cloud.githubusercontent.com/assets/2423362/15094446/a6030ff4-14e7-11e6-8fc9-f8c9100ea70d.png)
3. Render the icon in breadcrumbs or not.
4. Choose to wrap the title in an element tag or not (div or span - 4a) and also define classes for it (4b).

**Comment by TeamTriplo** [comment]
Looks great! I like it.

**Comment by klonos** [comment]
Thanks so much @jenlampton 🙏 ...looks awesome 👍 ❤️

Comments:

I cannot reproduce this now, but when I first logged in the PR sandbox, the home menu item had only text and no icon. Clearing caches fixed things. Anyway...

1. I was slightly skeptical about the use of the path as class, but I now think that it is perfectly OK, because we will be able to differentiate possible same labels in different menu items.

  An alternative to consider though would be to use a series of classes per path segment, so we could avoid long classes (like a single `.admin-config-development-configuration-sync-diff` class), plus we would be able to do this:

  `.admin.config`
  `.admin.config.development`
  `.admin.config.development.configuration`
  `.admin.config.development.configuration.sync`
  `.admin.config.development.configuration.sync.diff`

2. There is no CSS class being added to last/deepest children menu items.

3. We should use similar filenames for the icons as in https://github.com/backdrop/backdrop/tree/1.x/core/themes/seven/images (specifying color, size, and fontawesome.com name).

4. The CSS in the PR repeats things like `background-size: 16px;` and `padding-left: 29px;` for all icons. Can we please add these in a generic selector?

3. The current icon for the user counter looks dated. We should replace it with https://fontawesome.com/icons/user-friends

4. We should add https://fontawesome.com/icons/sign-out-alt or https://fontawesome.com/icons/door-open as an icon for the "Log out" menu item.

5. Replace the single-person icon for "User accounts" with https://fontawesome.com/icons/users

6. Use the single-person icon for the user profile menu item. Alternatives: https://fontawesome.com/icons/address-card or https://fontawesome.com/icons/user-circle (I personally like the later).

7. I like the "control panel" icon that WordPress uses for their "Settings" menu. Perhaps use https://fontawesome.com/icons/sliders-h, but rotate it 90° to be vertical.

8. I don't mind the paintbrush for the "Appearance" menu, but perhaps https://fontawesome.com/icons/palette would make more sense now that we have improved color.module support (the palette color "wells" resemble the new round color selector fields we now use 😄).

9. WordPress uses https://fontawesome.com/icons/plug for the plugins/modules menu item. Not to say that the puzzle piece is not cool; I personally like both equally.

10. I don't like the icon used for "Structure" (I like the one they use in Drupal better; but still not even remotely ideal). I wish that fontawesome.com had something like a blueprint icon (like https://www.flaticon.com/free-icon/blueprint_182657), but the only possible alternative I could find was https://fontawesome.com/icons/pencil-ruler 🤔

**Comment by stpaultim** [comment]
In terms of feedback on specific icons, I would have been fine with them the way they are in the PR. After reading @klonos feedback, I thought I'd chime in:

1) Content = Pencil is great
2) User accounts = is good. Multi person icon is better
3) Appearance = I like the paint brush. I do not think the Palette would be an improvement.
4) Functionality = Puzzle Piece works for me, but I see a persuasive argument in favor of the plug (users seem to get the concept of plugins more than modules, thanks to Wordpress). 
5) Structure = I like the current PR icon better than the suggested alternatives
6) Configuration = Current icon in PR is easily understood and commonly used.
7) Reports = Boring but effective
8) User Counter = I agree that this icon is dated and could use a refresh, suggested alternative is much better and fits in better with other icons.
9) Logout = I like the door better than the other option suggested.

It's not clear to me where @klonos wants to use "control panel" icon. 
I would approve of the PR as it is. I only offer these opinions in case more opinions are helpful.

**Comment by klonos** [comment]
...I also just noticed this now:

>I also only included them on the top-level links, and only on desktop (when we're sure there's enough room for them)

I think we should be fine to use the icons on mobile too. The admin bar collapses to a single "Admin bar" drop-down menu with a single top-level item, so I don't see any reason why not have icons in the second+ level items.

**Comment by jenlampton** [comment]
> I don't see any reason why not have icons in the second+ level items.

One reason not to is that choosing icons is hard (as we found here!) and adding them to the top level seemed like the most-win for the least-pain :) I did think about adding an icon to the one top-level link on mobile "Admin bar" but I couldn't decide what icon :(

> 1 I was slightly skeptical about the use of the path as class, but I now think that it is perfectly OK

good :)

> 2. There is no CSS class being added to last/deepest children menu items.

good :) they should only be on the top-most links.

> 3. We should use similar filenames

Since I put these icons in `/core/misc` I copied the file names of the other icons in there (I did use the font-awesome name though). All icons in there (starting with `icon-`) are white and 64px.

> 4. The CSS in the PR repeats things like background-size: 16px; and padding-left: 29px; for all icons. Can we please add these in a generic selector?

The `background-size` declaration needs to come after the `background` declaration, so the only thing we'd be saving is moving the `padding-left: 29px;` which seemed not worth-it to me.

> 5. The current icon for the user counter looks dated. We should replace it with fontawesome.com/icons/user-friends

Done.

> 6. We should add fontawesome.com/icons/sign-out-alt or fontawesome.com/icons/door-open as an icon for the "Log out" menu item.

I prefer 'sign-out' so I've used that instead. what do you think?

> 7. Replace the single-person icon for "User accounts" with fontawesome.com/icons/users

done.

> 8. Use the user-circle icon for the user profile menu item.

Done.

> 9. Perhaps use fontawesome.com/icons/sliders-h, but rotate it 90° to be vertical.

For what? Also, this is getting too crazy...

> 10. I don't mind the paintbrush for the "Appearance" menu, but perhaps fontawesome.com/icons/palette would make more sense ..

I also prefer this because it doesn't look as much like the pencil we're using for `Content`

> 11. WordPress uses fontawesome.com/icons/plug for the plugins/modules menu item.

I tried the plug, but prefer the puzzle piece. 
<img width="960" alt="screen shot 2019-01-09 at 6 17 59 pm" src="https://user-images.githubusercontent.com/397895/50941753-f86c0c00-143a-11e9-8c0b-fe05333c442d.png">

> 12 > I don't like the icon used for "Structure"

It was also my least favorite, but I couldn't find anything better either. I dislike `pencil-ruler` because it's also too much like the pencil we use for Content.

**Comment by klonos** [comment]
Thanks @jenlampton ...I love this ❤️!!

>> 2. There is no CSS class being added to last/deepest children menu items.
>good :) they should only be on the top-most links.

During my testing, I have discovered that they are also being added to the children items ...just not the deepest ones.

>>3. We should use similar filenames
>Done. Also moved these guys to admin-bar module.

Thanks. You know me and my OCDs 😜 ...moving them to the admin bar module seems a correct move 👍. I was thinking that if we were to add the icons used in `/admin/config` in the respective "Configuration" menu in admin bar, then we'd need to place them there too (but that's TBD and a follow-up).

>>6. We should add fontawesome.com/icons/sign-out-alt or fontawesome.com/icons/door-open as an icon for the "Log out" menu item.
>I prefer 'sign-out' so I've used that instead. what do you think?

Don't have a specific preference. ...although an open door might be interpreted as both log in and log out, so perhaps better with the "sign out" icon. It also has the name for it 😉

>> 9. Perhaps use fontawesome.com/icons/sliders-h, but rotate it 90° to be vertical.
>For what? Also, this is getting too crazy...

For the "Configuration" menu. Similar to what WordPress is using for its "Settings" menu.

> I tried the plug (see below) but prefer the puzzle piece so I left it.

All good 👍 ...was just mentioning alternatives.

>It was also my least favorite. I dislike `pencil-ruler` because it's also too much like the pencil we use for Content. I ended up going with `sort-amount-down`, which I prefer:

Yeah, neither is ideal. Lets go with that unless someone has a better alternative. Perhaps something more fitting will be added in the fontawsome list in the future.

Everything looks beautiful now ...we needed some "bling" for our bday release 😄

The PR sandbox showed no icons this time. Clearing caches once showed all icons except for the home icon ...a second cache clear showed that too.

Noting that there is left padding added to all menu items, including the non-top-level ones. Handy if we are to add icons to them in the future (which I think we should), but not if we are not to do that ever.

**Comment by klonos** [comment]
...thanks for posting those screenshots btw, and thanks for adding an icon for the "Development" menu. I think that:

a) we should use that icon for the "Development" section in `/admin/config` instead of the wrench we are currently using.

b) that "Development" top-level menu is actually a bug 😅...it only shows up when devel.module is installed and enabled, and I think it should be merged with the menu item under "Configuration". We should either have one "Development" item in the top level, or one under "Configuration".

**Comment by stpaultim** [comment]
I just logged into sandbox and the icons were visible immediately. But, I seem to recall needing to clear the cache the very first time I tried this PR 3 days ago. I'm not too worried about this. 

Looks wonderful. I give my stamp of approval, but given that I have not looked at the code, I'm not going to change the status.

**Comment by opi** [comment]
Loving this ! Add a minor a11y concern in PR review.

But I can't resist the bikeshedding: The "page' icon for report can be nice in replacement for content's "pencil". And then have a"info circle" for report.

**Comment by jenlampton** [comment]
> And then have a"info circle" or a "graph" icon (like D8) for reports.

Yes, this is better!  Added and pushed :) 

> The "page' icon for reports can be nice in replacement for content's "pencil".

Hm, I know @quicksketch and I both preferred the pencil. Leaving that one unless we get some more feedback that `file` is better there than `pencil`.

**Comment by quicksketch** [comment]
I like pencil for now. If we ever have an "Edit this page" button in the toolbar, we'll want to use the pencil for that instead. But I think we can make that adjustment if/when that happens.

**Comment by opi** [comment]
agreed. let's stop the bikeshedding ;) I'd rather focus on the accessibility issue

**Comment by quicksketch** [comment]
Also there are some concerns around mobile display... it would be nice to have icons show up on mobile for the first level items. But that could be a follow-up. Thoughts?

**Comment by opi** [comment]
Mobile display can be fixed: https://i.imgur.com/Sf5wxRh.png ; 

As `.top-level` class is added by JS only on "desktop view", we need to get rid of it in icon CSS rules. 
Replace
```
#admin-bar #admin-bar-menu.top-level .dropdown li > a { /* padding stuff */ }
[dir="rtl"] #admin-bar #admin-bar-menu.top-level .dropdown li > a { /* padding stuff */}

#admin-bar-menu.top-level li > a.admin-XXX { /* icon definition */}
```
with
```
#admin-bar #admin-bar-menu > li > .dropdown > li > a {/* padding stuff */ } // only first level

#admin-bar-menu.top-level li > a.admin-XXX { /* icon definition */ }
```

One may appreciate a padding-left for 2nd level item on desktop.

**Comment by jenlampton** [comment]
accessibility issue fixed, working on this now! :)

**Comment by klonos** [comment]
>I just logged into sandbox and the icons were visible immediately. But, I seem to recall needing to clear the cache the very first time I tried this PR 3 days ago. >I'm not too worried about this.

That's because if there is another person that happens to log in on a fresh sandbox, and they clear caches, then there is no need for anyone else logging in after them to clear caches 😉

...

- The "Admin bar" menu item goes pink on mobile 😆
- The icons "jump" a couple of pixels left/right when the admin bar is hovered on.

Other than that RTBC 👍

**Comment by jenlampton** [comment]
> The "Admin bar" menu item goes pink on mobile 😆

Darn my debug code...  Fixed now!

> The icons "jump" a couple of pixels left/right when the admin bar is hovered on

That's what I get for trying to be clever...  fixed and code simplified.

**Comment by klonos** [comment]
I have left one comment in the PR re coding standards (a missing space, plus another suggestion.

I think address those plus the missing gray background on hover for "Home" that @opi mentioned and we're RTBC 👍

One minor suggestion: why limit the adding of classes to only the top-level menu items? If we added them to all, we'd be making it easier for people to add icons via their custom themes, plus would be one less conditional in the code 😉

PS: is everybody seeing a "blink" of the admin menu upon page load, or is it just me? ...although pre-existing issue; not related to this PR.

PPS: there is this strange behavior of the "Home" menu where it lingers for a second or two after hover-out. Also preexisting issue: #466

**Comment by jenlampton** [comment]
> The "Home" link does not have a grey background on hover. Sub-links ave strange hover behavior too.

Fixed.

> This Home link and the right ones (user, logout) could use some padding to have more space around.

All the links at the top should have the same padding. I added some padding to the whole bar so it's not quite so squished up against the edges of the browser. 

> I have left one comment in the PR re coding standards

Fixed. 

> One minor suggestion: why limit the adding of classes to only the top-level menu items?

Because that's the only place core is adding icons :)

> If we added them to all, we'd be making it easier for people to add icons via their custom themes

Custom admin themes are pretty rare, and even then, a custom admin theme may prefer to add their own classes. This is not an 80% use-case. 

> plus would be one less conditional in the code 😉

Yes, but it would be a whole lot more muck in the markup! 😉

**Comment by klonos** [comment]
>>The "Home" link does not have a grey background on hover. Sub-links ave strange hover behavior too.
>
>Fixed.

Indeed, but it so happens that the home menu does not get `active-trail`, so doesn't get a gray background when in the home page. Although that is a preexisting issue, perhaps we should fix it here. Last detail and I'd call it RTBC 😄

**Comment by jenlampton** [comment]
> the home menu does not get `active-trail`

I had the same thought, but then decided against it. That class is only added to the menu items. Nothing on the right hand side gets it either. I think if we wanted to extend that functionality to different parts of the admin-bar, that should be a separate issue.

**Comment by klonos** [comment]
Sure, separate issue is fine. RTBC then 😉

**Comment by jenlampton** [comment]
> some have a padding of 29px, and some of 27px ; I think everything is much cleaner with a common 29px padding.

Ah, I don't think that was intentional. After viewing them both, I liked the ones at 27px better, so I split the difference and made them all consistently 28px! :) PR updated.

**Comment by klonos** [comment]
Ah yes, golden line in the middle 😄 ...although I still see 27px and 29px in the PR. Did you perhaps forget to push @jenlampton ??

**Comment by jenlampton** [comment]
Yep. Pushed now :)

**Comment by quicksketch** [comment]
I incorporated @opi's last suggestions and merged in https://github.com/backdrop/backdrop/pull/2456. I left some notes there on how this could have been done differently, but I think this is suitable in any case as it's implemented now. Thanks @jenlampton, @klonos, @opi, and @stpaultim for putting this together!

**Comment by klonos** [comment]
> I left some notes there on how this could have been done differently

...and I filed a follow-up so that this does not get lost in time 😉
