### ISSUE TITLE
[UX] Menu position rules.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1843]
This is sort of a follow-up to #768...

In that issue, we removed the default setting of adding articles/posts to a menu. The reasoning behind that move was 100% legitimate as in most cases important pieces of content that deserve prominent places in the main navigation menu are pages (while articles are used for blog-posty things).

Since it was only the default option that we changed and not the ability to place articles in a menu, people that still need to place articles in menus can do that for single pieces of content. Also, if some want this to be the default for their site, they can change the setting in the content type level.

What we are not accounting for though is the use case that the [Menu Position](https://www.drupal.org/project/menu_position) module covers for Drupal:

> Often times site builders want certain types of content to appear in a specific position in the navigational menu. The simplest solution, adding all of that content individually to the menu system, has performance and usability issues. (Imagine hundreds of menu items added to one spot in the menu.)
> 
> This module allows for the creation of rules that will dynamically add the current page into the menu system at the requested spots.

Particularly interesting is the feature that adds a piece of content to the breadcrumb and menu trail (without actually adding all nodes of that type to the menu):

![menu_position](https://cloud.githubusercontent.com/assets/2423362/15094600/aa07a268-14ec-11e6-92dc-4620d0520248.png)

So, say you have a view of articles under `/articles` and that view page also has a menu item in the primary navigation. With vanilla Drupal/Backdrop, even if you generate the URLs for those articles to be in the form of `articles/[node:title]`, they still do not get an active trail and the view page menu item does not get its `active-trail` and `active` classes.

Do you think that this is a thing worth handling in core or not?

**Comment by BWPanda** [comment]
I personally think this should be left to contributed and let people choose their own breadcrumb setup.

**Comment by klonos** [comment]
Yeah, with #1610 getting into 1.15 + contrib like https://github.com/backdrop-contrib/easy_breadcrumb this is now moot. Let's close, and reopen if more people require this OOTB and/or cannot find a solution in contrib.
