### ISSUE TITLE
[UX] Allow linking menu items to existing content via auto-complete and browse.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1846]
This is part of #434...

The goal is to allow menu items to be created and instead of requiring a path to be entered in a text field as a target, have the path be auto-completed in the text field as the user types. We can support content, user, file and views paths, indicating what each auto-complete result is.

If the user wants to search for content by other means (like creation date or author instead of title), we could have a "browse" button next to the auto-complete that opens a views-based dialog with various exposed filters.

**Comment by BWPanda** [comment]
Ooh, yes please! I really want this functionality. It'll match what we already have for the link feature in CKEditor (though that could benefit from some of these suggestions too I think).

**Comment by klonos** [comment]
This is now included in 1.6.0 (see #3764)
