### ISSUE TITLE
[UX] Project Installer module not enabled by default.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1847]
Follow-up to #1399...

@klonos

> > The Project Installer module is not enabled by default out of the box. Intentional?

@quicksketch 

> Yeah, this is an item that I think we may want to handle in a follow-up. We definitely want it installed by default, but since Installer is dependent upon Update module, it would require that the user leave-checked the box for "Check for Updates". I'd like to make this instead be a checkbox for "Send anonymous site information when checking for updates" (or something), and ALWAYS leave update.module (and installer.module) enabled on new installs.

**Comment by klonos** [comment]
> I'd like to make this instead be a checkbox for "Send anonymous site information when checking for updates" (or something), and ALWAYS leave update.module (and installer.module) enabled on new installs.

:+1: sounds reasonable.

**Comment by klonos** [comment]
@docwilmot 

>> it would require that the user leave-checked the box for "Check for Updates"

> I think we could leave the checkbox as is. Let's make it so that that checkbox enables only the cron-triggered automatic checking. (this is after all what it implies). Update can still be enabled even if the checkbox is not checked, allowing the project checking API to be always on, and allowing Installer to use it. 

...or that :wink:

**Comment by klonos** [comment]
I think that this is an important UX bug, so perhaps address it in 1.5.2?

**Comment by quicksketch** [comment]
Looks like this actually was resolved in #1399. In all sites recently at least Installer module has been enabled for me out of box, as is expected. Please reopen if I'm mistaken.
