### ISSUE TITLE
[UX] Admin bar: empty `class=""` attribute left behind when the `active-search-item` class is removed.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1849]
Notice how there is a `class=""` left behind while the `active-search-item` class is added to the currently hovered-over item:

![backdrop-admin_bar-empty_left-over-class](https://cloud.githubusercontent.com/assets/2423362/15148315/fec5a490-1707-11e6-9e56-a1d077ebfbda.gif)

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/2931~~
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2932

**Comment by BWPanda** [comment]
I'm not 100% sure, but I suspect there's no easy fix for this, as it's all automatic with Javascript... Also it should affect anything and is only temporary for that page, right?

**Comment by klonos** [comment]
Not that my JS-fu has improved since 2016 ...perhaps googling skills? 😅 https://css-tricks.com/forums/topic/remove-empty-class-from-dom

So I thought I might take a crack at it: https://github.com/backdrop/backdrop/pull/2931 (untested - most likely doesn't work 😅)

**Comment by BWPanda** [comment]
Ah, nice! :smile:

**Comment by klonos** [comment]
Not nice ...doesn't work 😓

**Comment by BWPanda** [comment]
[PR](https://github.com/backdrop/backdrop/pull/2932) inspired by @indigoxela's suggestion.

**Comment by BWPanda** [comment]
I wouldn't call this a bug, since it doesn't do anything wrong/bad... But I'll wait til someone else agrees with me before removing tag.

**Comment by klonos** [comment]
Thanks @BWPanda and @indigoxela 👍 ...PR is much simpler and works.

**Comment by quicksketch** [comment]
The PR looks nice and simple. Though it doesn't look like it is very efficient. I'm not sure how fast the selector for `.find('[class=""]')` is. We could tidy this function a bit as well. I posted suggestions to the PR: https://github.com/backdrop/backdrop/pull/2932#pullrequestreview-301067740

**Comment by BWPanda** [comment]
I updated my PR based on @quicksketch's suggestions.

**Comment by klonos** [comment]
@BWPanda please see my comment in the PR: https://github.com/backdrop/backdrop/pull/2932/files#r475796625

**Comment by jenlampton** [comment]
Since it looks like this change doesn't effect anything, I'm changing it from a bug-fix to a task.

**Comment by quicksketch** [comment]
I tested out https://github.com/backdrop/backdrop/pull/2932 again and it works great. Thanks @BWPanda for making those code adjustments. Merged into 1.x and 1.17.x. Thanks!
