### ISSUE TITLE
Error when reordering view displays

### ISSUE THREAD

**Issue by jackaponte** [backdrop/backdrop-issues#1851]
Using Backdrop v1.3.5. If I click the "Reorder Displays" option in a view, I see a series of errors, one set of this pair of errors for each display in my view:

`Notice: Undefined property: views_display::$position in views_ui_reorder_displays_form() (line 2946 of /var/www/dev/woolman/core/modules/views_ui/views_ui.admin.inc).`
`Notice: Undefined property: views_display::$position in views_ui_reorder_displays_form() (line 2947 of /var/www/dev/woolman/core/modules/views_ui/views_ui.admin.inc).`

If I attempt to reorder the displays, it has no effect before or after saving the view. An additional error does appear in the site logs:

`Warning: uasort(): Array was modified by the user comparison function in views_ui_reorder_displays_form_submit() (line 3034 of /var/www/dev/woolman/core/modules/views_ui/views_ui.admin.inc).`

Let me know if I can provide more information to help track this down further!

**Comment by quicksketch** [comment]
Thanks @ItangSanjana for making a PR! I left some feedback in https://github.com/backdrop/backdrop/pull/1398. A test to cover reordering would also be great.

**Comment by ItangSanjana** [comment]
Sorry I screwed up with the git flow :( It is now here: https://github.com/backdrop/backdrop/pull/1410

**Comment by quicksketch** [comment]
No problem @ItangSanjana! Thanks for making a PR in the first place. I'd like to get a test on reordering displays to ensure it continues to work in the future. This is a simple fix and it would be great to prevent such a mistake again.

**Comment by ItangSanjana** [comment]
Awesome :+1:

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1451 that includes tests for 1.4.3.
