### ISSUE TITLE
Is 'project_browser' required in the backdrop_merged_modules() function in module.inc?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1854]
With adding the Project Browser in core (#1399 Yay!), we've included 'project_browser' in the list of project names in the `backdrop_merged_modules()` function because this was also a contrib project (https://github.com/backdrop-contrib/project_browser), but...

1. the contrib project had no actual releases.
2. the name that we finally chose to go with for the module in core is installer.module, so different from the contrib module name.

So, my point is (although I guess it does not hurt having that line there), do we actually need that entry in module.inc??

**Comment by klonos** [comment]
...it must have been there since the initial PRs when we started merging the contrib project.

**Comment by quicksketch** [comment]
We probably don't need it in there. Modules that have been merged into core are no longer possible to enable in the UI. But other than that, the `backdrop_merged_modules()` function doesn't do much. I don't think it'd do any harm to leave it in there.

**Comment by klonos** [comment]
> Modules that have been merged into core are no longer possible to enable in the UI.

Then I guess it's good that we have it there. That way, people will not be able to enable the Project Browser module even if they somehow missed the fact that it's been merged to core. Even if they download a copy of the project through the "download zip" button that GitHub provides, they won't be able to do something with it unless they are using a version of Backdrop earlier than 1.4.0.

Thanx for taking the time to reply Nate :wink:
