### ISSUE TITLE
Menus cannot be deleted

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1856]
I've created a new menu, and am now trying to delete it again, but cannot find where to delete it. There's no 'delete' option in the Operations drop-down on /admin/structure/menu page, and no Delete button on the menu's Configure page...

I can see a Delete option in the Admin bar, so it's possible to delete the menu, but it's not appearing anywhere else.

**Comment by quicksketch** [comment]
Thanks @ItangSanjana and @BWPanda! I'll try out the PR and see if it fixes the problem.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1368 for 1.x and 1.3.x. Thanks!
