### ISSUE TITLE
Project Browser doesn't reset current page on search

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#1857]
If you're idly browsing the list of modules with Project Browser, go a few pages in, and then decide to search for something, the search results will show "Showing 1 to 4 of 4.  No results found."  That's because the `page=n` in the query is still present from the earlier idle browsing.

To reproduce:
- Go to admin/modules/install?page=4
- Search for "date"

**Comment by quicksketch** [comment]
Thanks @jlfranklin! Great find. It'd be great to fix this before 1.4.0.

**Comment by quicksketch** [comment]
This is a minor bug, but as a flagship feature of 1.4.0, it would be great to fix it ASAP. Anyone want to take it on? I think this issue is simple enough to warrant being "novice".

**Comment by docwilmot** [comment]
Sorry, on the beach today. Wife's birthday. So no Backdrop till late evening at best. If this is still here when I'm back, well will tackle it.

**Comment by klonos** [comment]
@docwilmot have fun at the beach and happy bday to the Mrs. Backdrop can wait for real life.

**Comment by sentaidigital** [comment]
Tried @docwilmot's patch here.  Works perfectly.

**Comment by quicksketch** [comment]
> The "Clear" button doesn't reset the page... which isn't broken as it just shows different modules from whatever page you happen to be on, but is an odd bit of UX.

Yeah I found the same thing reviewing the code: https://github.com/backdrop/backdrop/pull/1387#discussion-diff-63307391

I think the page query string should be reset when either the "Search" or "Clear" button is used.

**Comment by docwilmot** [comment]
Excuse the delay. Hopefully fixed in time.

**Comment by quicksketch** [comment]
New PR works great. Thanks @docwilmot! Merged for 1.4.0. :smile:
