### ISSUE TITLE
WSOD and funny page rendering when upgrading to 1.3.6/1.4.0

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1859]
https://github.com/backdrop/backdrop/commit/f5374add6ef51ef013c163fc3be7ebf63c25d519

https://github.com/backdrop/backdrop/commit/a3d798edacf656197c1dd18b94944a68e2243e23

I get a WSOD in the front page, an unthemed version of the "access denied" page in `/admin`:

![backdrop-issue1859-admin](https://cloud.githubusercontent.com/assets/2423362/15263358/b4c9fa74-19ac-11e6-8410-9976c7ef26a1.png)

...and an unthemed, half-rendered login screen (`/user`) with no fields, just the "Log in" page title and the local task tabs:

![backdrop-issue1859-user](https://cloud.githubusercontent.com/assets/2423362/15263364/bd4ad57e-19ac-11e6-9004-abd6f1a9db6f.png)

**Comment by klonos** [comment]
I tried reverting one commit at a time and, luckily enough, reverting to the previous to last fixes the issue. So the offender is https://github.com/backdrop/backdrop/pull/1356 from #1300

**Comment by klonos** [comment]
...after all the latest commits between https://github.com/backdrop/backdrop/commit/f5374add6ef51ef013c163fc3be7ebf63c25d519 and https://github.com/backdrop/backdrop/commit/8220e311e28ca8b7c3d9cf490a0d93b436d210f1 , there was some improvement: the front page WSOD no has the admin bar rendered, so I was able to clear cashes and everything seems to be working fine now.

Leaving this issue here open in case we deem necessary to do something like force a cache clear or whatever upon update. Otherwise, feel free to close.

**Comment by quicksketch** [comment]
Thanks @klonos! I've tried upgrading from 1.3.5 to 1.4.0 and encountered some similar site-brokeness, but everything was fine after running update.php (which is needed for several changes).

**Comment by klonos** [comment]
What follows might be unrelated/separate issues because previously I was on a local dev on Windows, but here goes...

Live site running 1.3.5 on Linux -> upgrade first to 1.3.6 and from the front page all is seemingly OK -> go to `/admin/reports/status`:

```
    Warning: filectime(): stat failed for core/layouts/one_column/one_column.info in _update_process_info_list() (line 179 of /var/www/core136/modules/update/update.compare.inc).
    Warning: filectime(): stat failed for core/layouts/two_column/two_column.info in _update_process_info_list() (line 179 of /var/www/core136/modules/update/update.compare.inc).
    Warning: filectime(): stat failed for core/layouts/two_column_flipped/two_column_flipped.info in _update_process_info_list() (line 179 of /var/www/core136/modules/update/update.compare.inc).
    Warning: filectime(): stat failed for core/layouts/three_three_four_column/three_three_four_column.info in _update_process_info_list() (line 179 of /var/www/core136/modules/update/update.compare.inc).
```

Clear caches -> repeated series of these two warnings:

```
    Warning: include_once(/var/www/core/modules/update/update.theme.inc): failed to open stream: No such file or directory in _theme_process_registry() (line 571 of /var/www/core136/includes/theme.inc).
    Warning: include_once(): Failed opening '/var/www/core/modules/update/update.theme.inc' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in _theme_process_registry() (line 571 of /var/www/core136/includes/theme.inc).
```

These were obviously because `/core` was a symlink to `/core136` that actually holds the 1.3.6 files, but nevertheless should work I believe. @Gormartsen was working on a related issue(?).

Anyways, removed the symlink, renamed `/core136` to `/core` -> WSOD. Replaced 1.3.6 `/core` with 1.3.5 `/core` -> WSOD. Replaced 1.3.5 `/core` with 1.4.0 `/core` -> series of errors/warnings that are too long to paste here -> cache clear -> Magic!!! -> go to site status report page -> no updates pending (???) -> flush caches -> WSOD -> go to home page -> all OK -> go to site status page again -> all OK -> run cron -> OK -> flash caches -> WSOD 

**WTF?!?**

**Comment by klonos** [comment]
... -> truncate all cache* tables -> front page OK -> status page OK -> flush caches -> WSOD

Any pointers?

**Comment by docwilmot** [comment]
run updates?

**Comment by klonos** [comment]
> run updates?

Nope, but site status reports db is up to date. When manually running the update.php, once I hit the "Continue" button, there's this error:

```
Fatal error: require_once(): Failed opening required '/var/www/core140/modules/views/includes/handlers.inc' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/website/core/includes/bootstrap.inc on line 3644
```

My `/core` folder is not symlinked to `/core140` anymore and I have emptied all cache* tables, but as you can see, the error points to the old path.

**Comment by klonos** [comment]
...forgetting the linux site with the symlinked `/core` folders for a while to get back to my Windows local dev. Upgrading to 1.4.0:

```
    Notice: Undefined index: default region in LayoutRendererStandard->ensurePageContentBlock() (line 561 of C:\www\core\modules\layout\plugins\renderers\layout_renderer_standard.inc).
    Notice: Undefined index: regions in LayoutRendererStandard->prepareRegions() (line 284 of C:\www\core\modules\layout\plugins\renderers\layout_renderer_standard.inc).
    Warning: Invalid argument supplied for foreach() in LayoutRendererStandard->prepareRegions() (line 284 of C:\www\core\modules\layout\plugins\renderers\layout_renderer_standard.inc).
```

**Comment by klonos** [comment]
...refreshing the page adds the following to the error list:

```
Notice: Undefined index: header in bartik_preprocess_layout() (line 35 of C:\www\core\themes\bartik\template.php).
Notice: Undefined index: header in include() (line 28 of C:\www\core\modules\layout\templates\layout.tpl.php).
Notice: Undefined index: top in include() (line 34 of C:\www\core\modules\layout\templates\layout.tpl.php).
Notice: Undefined index: content in include() (line 64 of C:\www\core\modules\layout\templates\layout.tpl.php).
Notice: Undefined index: footer in include() (line 68 of C:\www\core\modules\layout\templates\layout.tpl.php).
```

**Comment by klonos** [comment]
...trying to access update.php throws an "access denied" page along with these (notice the mix of back and forward slashes in some of the paths):

```
    Warning: include(C:\www/core/layouts/two_column/layout--two-column.tpl.php): failed to open stream: No such file or directory in theme_render_template() (line 1497 of C:\www\core\includes\theme.inc).
    Warning: include(): Failed opening 'C:\www/core/layouts/two_column/layout--two-column.tpl.php' for inclusion (include_path='.;C:\WPN-XM\bin\php\pear') in theme_render_template() (line 1497 of C:\www\core\includes\theme.inc).
```

**Comment by klonos** [comment]
...I had a a light bulb moment about this one:

```
Fatal error: require_once(): Failed opening required '/var/www/core140/modules/views/includes/handlers.inc' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/core/includes/bootstrap.inc on line 3644
```

What I did is to place 2 copies of the `/core` folder with the second one being `/core140`. So I got past the update.php fatal. But I got a disappointing "No pending updates." (?) Shouldn't there be updates from 1.3.5 to 1.4.0?

**Comment by klonos** [comment]
...and I finally used the latest dev and the db updates finally showed up:

6 pending updates:
- system module
  - 1051 - Notify administrators if a non-core version of Redirect module is present.
  - 1052 - Disable project browser if it previously existed on the site.
  - 1053 - Remove unnecessary items from the "main-menu" menu.
  - 1054 - Changes the key in layout config files from 'layout' to 'layout_template'.
  - 1055 - Create the new layout settings configuration file.
- update module
  - 1002 - Enable static caching for update settings configuration file.

**Comment by klonos** [comment]
...but:

```
    Notice: Undefined index: update_success in update_results_page() (line 205 of /var/www/core/update.php).
    Warning: array_pop() expects parameter 1 to be array, boolean given in update_results_page() (line 210 of /var/www/core/update.php).
```

> The update process was aborted prematurely while running update # in .module. All errors have been logged. You may need to check the watchdog database table manually.

"while running update # in .module." ???

**Comment by klonos** [comment]
...in the watchdog log there's a lot of notices (let me know if you think that they would help and I'll upload them here), and a few warnings:

```
Warning: array_pop() expects parameter 1 to be array, boolean given in update_results_page() (line 210 of /var/www/core/update.php).
Warning: Invalid argument supplied for foreach() in LayoutRendererStandard->prepareRegions() (line 284 of /var/www/core/modules/layout/plugins/renderers/layout_renderer_standard.inc).
```

**Comment by klonos** [comment]
...anyways. I hope that all this is useful in some way. Perhaps all those errors actually mean something to you guys and maybe something that needs to be fixed has surfaced. Let me know if anyone needs more info about anything.

**Comment by Gormartsen** [comment]
@klonos is your Linux box php7 with mod_php config and opcache enabled?
Do you still can reproduce situation?

If yes, to both - try to restart Apache and check if issue is here.

If yes only to reproduce, can you share access via ssh? I will help to boil issue down with linked core.

**Comment by klonos** [comment]
php 5.6.11 on Ubuntu 15.10 - no opcache. Restarting apache does not help.

**Comment by Gormartsen** [comment]
@klonos then it is not an opcache or xcache or apc issue (sometimes they act as described). 

I can try to help to find the source of the wrong path to file when symlinked core if you can write me a ssh access.

**Comment by klonos** [comment]
I will need to ask permission from the site owner and get back to you. But after I have now upgraded to the latest 1.4.x-dev and run the db updates, the issue is gone.

I will try upgrading my local dev to the latest 1.4.x-dev too and see if this fixes the original problems that made me file this issue here in the first place.

**Comment by Gormartsen** [comment]
Hm, maybe some core patches for symlinked core folder did not get to release archive.
You can check it by comparing update.php file for this lines:

https://github.com/backdrop/backdrop/blob/1.x/core/update.php#L24
```php
define('BACKDROP_ROOT', dirname(dirname($_SERVER['SCRIPT_FILENAME'])));
// Change the directory to the Backdrop root.
chdir(BACKDROP_ROOT);
```

**Comment by Gormartsen** [comment]
Nope, it should be there: 
https://github.com/backdrop/backdrop/blob/1.4.0/core/update.php#L24

**Comment by Gormartsen** [comment]
O! 1.3.6 does not have this fix:
https://github.com/backdrop/backdrop/blob/1.3.6/core/update.php#L23

So symlinked core under 1.3.6 will give you error on update.php

**Comment by klonos** [comment]
Well, it was the same basic solution more or less with my local Windows dev:

Upgrade to latest 1.4.0-dev (replace `/core`)
-> "Manually" empty all cache* tables directly from the db...
-> Navigate to front page -> most likely will still throw a WSOD or errors
-> Refresh page -> a few errors (https://github.com/backdrop/backdrop-issues/issues/1859#issuecomment-219649915), but rest of the page loads
-> Either go to site status and from there run the db update script, or go directly to `/update.php`
-> Run updates

I got only 3 pending db updates this time (compared to the 6 I got in the linux box in https://github.com/backdrop/backdrop-issues/issues/1859#issuecomment-219661351):

3 pending updates
- system module
  -  1053 - Remove unnecessary items from the "main-menu" menu.
  -  1054 - Changes the key in layout config files from 'layout' to 'layout_template'.
  -  1055 - Create the new layout settings configuration file.

No update errors this time.

The difference between the local dev and the live site (different installations - not dev/stage pair) besides the obvious one (operating system), was that my local was incrementally upgraded to 1.3.6 prior to 1.4.0 and some of the increments were dev versions while the live site was a 1.3.5 that was directly upgraded to 1.4.0. Also, the live linux site initially had the symlinked `/core` folder.

Hope this helps others in the future.

**Comment by klonos** [comment]
So, fresh 1.3.5 upgrading straight to 1.4.2 (skipping 1.3.7) ->

1. Replace 1.3.5 `/core` with 1.4.2 `/core` -> page refresh ->

  ```
    Notice: Undefined index: default region in LayoutRendererStandard->ensurePageContentBlock() (line 561 of C:\www\modules\layout\plugins\renderers\layout_renderer_standard.inc).
    Notice: Undefined index: regions in LayoutRendererStandard->prepareRegions() (line 284 of C:\www\modules\layout\plugins\renderers\layout_renderer_standard.inc).
    Warning: Invalid argument supplied for foreach() in LayoutRendererStandard->prepareRegions() (line 284 of C:\www\modules\layout\plugins\renderers\layout_renderer_standard.inc).
    Warning: filectime(): stat failed for core/layouts/one_column/one_column.info in _update_process_info_list() (line 179 of C:\www\modules\update\update.compare.inc).
    Warning: filectime(): stat failed for core/layouts/two_column/two_column.info in _update_process_info_list() (line 179 of C:\www\modules\update\update.compare.inc).
    Warning: filectime(): stat failed for core/layouts/two_column_flipped/two_column_flipped.info in _update_process_info_list() (line 179 of C:\www\modules\update\update.compare.inc).
    Warning: filectime(): stat failed for core/layouts/three_three_four_column/three_three_four_column.info in _update_process_info_list() (line 179 of C:\www\modules\update\update.compare.inc).
  ```

  Setting the "Undefined index" notices about regions aside, notice how the `filectime(): stat failed` warnings mention paths with forward slashes while the files reported is in back slashes (this is a Windows environment)? Just thinking out loud here.

1. Page refresh again -> 4 extra "Undefined index" notices added to the top of the other errors:

  ```
  Notice: Undefined index: header in include() (line 28 of C:\www\modules\layout\templates\layout.tpl.php).
  Notice: Undefined index: top in include() (line 34 of C:\www\modules\layout\templates\layout.tpl.php).
  Notice: Undefined index: content in include() (line 64 of C:\www\modules\layout\templates\layout.tpl.php).
  Notice: Undefined index: footer in include() (line 68 of C:\www\modules\layout\templates\layout.tpl.php).
  ```

1. At least the admin bar is rendered, so clear caches -> the first set of errors goes away, the last 4 remain, the site status page is rendered.

1. Run db updates -> all good

1. Return to the site status page -> all green, messages gone.

Not too much drama for Drupal/Backdrop experts, but **scary UX for newcomers**.

**Comment by klonos** [comment]
Did fresh 1.3.7 to 1.4.2 upgrade and everything (errors/rendering issues) was identical to the fresh 1.3.5 to 1.4.2 procedure. I'm calling this a quits. Do not have any more time/energy or ides.

Closing the issue. Please reopen if you have a similar experience.
