### ISSUE TITLE
Issue with core/modules/simpletest/tests/https.php when core folder is linked

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1862]
This code need to be replaced

```
// Change current directory to the Backdrop root.
chdir('../../../..');
define('BACKDROP_ROOT', getcwd());
```

Similar to core/install.php

**Comment by Gormartsen** [comment]
backdrop/backdrop#1374 Fix issues with SimpleTestFunctionalTest as well when core folder get linked.

**Comment by quicksketch** [comment]
This is the same idea we used in https://github.com/backdrop/backdrop-issues/issues/1297. The fix looks good to me and tests are still passing.

Merged into 1.x. I committed this to 1.3.x but then realized the other issue we only merged the similar fix into 1.x. As such I reverted the commit on 1.3.x.

Thanks @Gormartsen!
