### ISSUE TITLE
Huge gap between the region title and the dropbutton.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1863]
@quicksketch mentioned in https://github.com/backdrop/backdrop-issues/issues/370#issuecomment-219158585:

> The CSS fixes in https://github.com/backdrop/backdrop-issues/issues/785 help but we still have a number of problems. The issue at https://github.com/backdrop/backdrop-issues/issues/1300 revealed a bug in our dropbuttons:
> 
> ![selection_138](https://cloud.githubusercontent.com/assets/100206/15261821/276ef00e-1924-11e6-95e6-40315500890e.png)
> 
> A huge gap between the region title and the dropbutton. It would be great to revisit this again and see if we could solve this problem.

**Comment by klonos** [comment]
@quicksketch there is a legitimate reason why that gap is there...

The latest master is broken (#1859) and the PR is closed (thus the PR sandbox has been destroyed), so I cannot provide a screenshot, but from what I recall the "Configure region" option that was added to the dropbutton is too wide and if the space between the region title and the dropbutton is not adjusted (https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/css/layout.admin.css#L113), then when one clicks the down arrow, the expanded dropbutton menu overlaps hit the region title.

The only alternative the way I see it is to align the region dropbutton to the far right like we do with the block dropbuttons. Minor UX- on wide screens where the user will have to move mouse a bigger distance.

**Comment by klonos** [comment]
> The only alternative the way I see it...

...well not the *only* alternative. We could also:

- place the "Configure region" as the first/default option of the dropbutton. That way we have the dropbutton be in its max width to begin with and so we can align it without the gap that accounts for the width increase when the dropbutton is expanded. But major UX- IYAM since adding blocks is the most commonly used action for regions.

- since we have only two options, we could split them to separate links instead of a dropbutton. Not sure about the UX repercussions though.

**Comment by klonos** [comment]
> The latest master is broken (#1859) and the PR is closed (thus the PR sandbox has been destroyed), so I cannot provide a screenshot...

That's what I was talking about:

![backdrop-layouts-region_dropbutton_expanded-no_gap_from_region_title](https://cloud.githubusercontent.com/assets/2423362/15268169/6abb04b0-1a19-11e6-9b86-b59697c05484.png)

...that's when the added width comes in handy: once the dropbutton is expanded.

**Comment by klonos** [comment]
...my proposal allows text to wrap in the action `<li>` and reduces the width of the dropbutton wrapper to the point where it makes the "Configure region" action wrap and have about the same width as the "Add block" action:

![backdrop-issue1863-pull1372-wrap_dropbutton_text_to_remove_gap](https://cloud.githubusercontent.com/assets/2423362/15268339/5f7d9e5a-1a1e-11e6-9690-b175ebc1cea4.png)

**Comment by quicksketch** [comment]
What about if we just made the button always wide? Ideally this would be automatic based on the button contents, but for Layouts we could set a min-width like such:
![selection_139](https://cloud.githubusercontent.com/assets/100206/15278358/79e4dc46-1acc-11e6-9db6-5be599fd7312.png)
![selection_140](https://cloud.githubusercontent.com/assets/100206/15278359/7c189fc0-1acc-11e6-9275-50933714fd47.png)

**Comment by sentaidigital** [comment]
That could be a lot of empty space if the first item is short and one of the other menu items is long.  I know this isn't the best example, but imagine if "Clone View" were the first and "Change View Name/Description" were one of the hidden items?

![views_menu](https://cloud.githubusercontent.com/assets/481531/15279943/481c8a2a-1af8-11e6-8cb2-0f18e7f3d6d4.png)

A more valid example is the Add button for Views Filter Criteria.

![views_add](https://cloud.githubusercontent.com/assets/481531/15279975/976fd8ca-1af8-11e6-8a51-72ddd976499e.png)

I think a float:right is a better answer.  The blocks do that already, so doing the same for regions will be consistent with other uses of the drop widget, and put the controls for a region and all a region's blocks close to each other.

**Comment by quicksketch** [comment]
We also could just let the button cover up the region name, as it was before I noted it in https://github.com/backdrop/backdrop-issues/issues/1300:

![selection_069](https://cloud.githubusercontent.com/assets/100206/13206770/fbce3e0a-d8b9-11e5-92ed-55d667d038ac.png)

> I think a float:right is a better answer.

This would definitely simplify things. Though I prefer the button near the region name so I know exactly what region I'm adding the block to. It's a visual strain for me to track all the way across the page on a full-width region.

**Comment by quicksketch** [comment]
We can move this to 1.4.1 without any problem I think. I'm still just not certain which is the best solution. We've got options we can implement, it's just a matter of preference.

**Comment by quicksketch** [comment]
For now I've just set the width of the button back to what it had been previously (140px). This is essentially @klonos's fix but excluding the text wrapping. I'm leaving this open for further discussion.

**Comment by jenlampton** [comment]
This should also be further resolved in https://github.com/backdrop/backdrop-issues/issues/1935. Closing this issue for now, but please re-open if that other issue doesn't solve the problem sufficiently.
