### ISSUE TITLE
Correct commit 746a181: vertical-tabs.css color applied to the wrong css rules.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1864]
My PR, my bad. I have accidentally put the `#000` color in the `border-[left|right]-width` rules:

https://github.com/backdrop/backdrop/blob/1.x/core/themes/seven/css/vertical-tabs.css#L159

and 

backdrop/vertical-tabs.css at 1.x · backdrop/backdrop
https://github.com/backdrop/backdrop/blob/1.x/core/themes/seven/css/vertical-tabs.css#L166

PR coming up...

**Comment by klonos** [comment]
...my PR basically changes this (D8 blue color scheme):

![backdrop-issue1864-pull1373-blue](https://cloud.githubusercontent.com/assets/2423362/15268673/12f8fd66-1a2a-11e6-84c3-9d200cd35b9e.png)

...to this (Backdrop black color scheme):

![backdrop-issue1864-pull1373-black](https://cloud.githubusercontent.com/assets/2423362/15268672/12f556c0-1a2a-11e6-86c4-9699b87f6217.png)

**Comment by klonos** [comment]
...basically, let me know if you think that it looks better with all vtab labels black instead of blue and I'll update my PR:

![backdrop-issue1864-all_black](https://cloud.githubusercontent.com/assets/2423362/15268700/fba6c5f2-1a2a-11e6-96be-1ef6828945f7.png)

**Comment by klonos** [comment]
@wesruv should probably take a quick look at this, but I know he's busy today :wedding: :ring: :bride_with_veil:  :smile:

**Comment by quicksketch** [comment]
I actually like the blue border on the left side. It matches the color of all other links on the page as well as the "Save" button, so I don't think it's necessarily "D8" styling. I think it was intentional, but agreed, @wesruv and probably @dariusgarza should take a look at this, as the original implementor and designer (respectively).

With the 1.4.0 deadline tomorrow, let's punt on this change. Although if you wanted to just remove the unneeded styles that aren't actually working (and so don't affect the design), then that would still be great.

**Comment by klonos** [comment]
The intention was to change to black in order to match the black backdrop logo (and marketing in general) and to also match the change to black that was done for Bartik in #842, but I agree that we can fix this in a later 1.4.x ...I mean if we decide to fix it in the first place.

Anyhow, lets wait for feedback from @wesruv and/or @dariusgarza before filing a PR then.

Note to self: file a follow-up to apply a similar effect on the mobile version of the vtabs (accordion).

**Comment by quicksketch** [comment]
Great, I'll move this to 1.x-future so I can focus on the 1.4.0 milestone for release. Thanks!

**Comment by klonos** [comment]
...this includes a code bug/discrepancy that needs to be fixed, so lets move to 1.4.1 now that the milestone is available :smile:

**Comment by wesruv** [comment]
I agree with Nate about the blue, it's our accent color in the seven theme, and I think it's better in this instance.

**Comment by klonos** [comment]
Thanx for taking the time to chime in @wesruv ...closed previous PR, filed new one with only the fix of removing the color from the width css rule.

**Comment by klonos** [comment]
Random test failure (exception in UserAdminSettingsEmailFormTest on php 5.3), but that's unrelated to the css change I made. So, I guess this is otherwise good to go.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1444 for 1.4.3, thanks @klonos!

**Comment by quicksketch** [comment]
> Random test failure (exception in UserAdminSettingsEmailFormTest on php 5.3), but that's unrelated to the css change I made. So, I guess this is otherwise good to go.

We put in additional debugging information to catch this particular error, this will now be fixed in future PRs thanks to https://github.com/backdrop/backdrop/pull/1450.
