### ISSUE TITLE
[UX][META] Consider flushing menu caches after certain changes are made.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1867]
I'm not sure if we can do selective cache clearing (as in only menu caches or only _specific_ menu caches), but there are some cases for example where changes are not immediately reflected in the admin bar and than might cause UX WTFs. ~~I only found one such case, but~~ lets start by making a list and sorting one thing at a time...
- [x] Adding/deleting/renaming fields does not update/remove the respective menu items under Structure -> Content types #2279
- [x] Renaming/deleting a vocabulary does not update/remove the respective menu items under Structure -> Taxonomy #2285

**Comment by quicksketch** [comment]
We can accommodate this in two wasys: Have Taxonomy module clear the menu cache after renaming a vocabulary, or have Admin Bar listen via `hook_taxonomy_vocabulary_update()`. Right now Admin Bar is mostly responsible for determining when it should clear for other core modules.

**Comment by klonos** [comment]
Looks like @mikemccaffrey has discovered another one in #2279 ...adding that to the list.

**Comment by klonos** [comment]
...lets close this meta. We have been filing separate tickets for such problems as needed.
