### ISSUE TITLE
Add a comment in /core/modules/layout/layout.admin.inc about the use of empty '$row[] = '';'.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1870]
https://github.com/backdrop/backdrop/pull/1385#discussion-diff-63300758

```
@@ -29,11 +29,15 @@ function layout_list_page() {
...
+      $row[] = array('data' => t('Default layouts (used on all paths without a specific layout)'));
+      $row[] = '';
+      $row[] = '';
```

@klonos:
> Perhaps silly question: what are these empty rows used for?

@docwilmot:
> Its to mitigate the problem you found at https://github.com/backdrop/backdrop/pull/1341#issuecomment-215006463 with the responsiveness of the title rows. I found that the mechanism for hiding columns based on priority tags in the header (eg `priority-low`) was negated by having `colspan` set on the row, and there is no way I could find to resize those rows with CSS as there is no CSS version of `colspan`. So instead, dont have one row that spans 3 columns, just have 3 colums, two of which are empty. The alternative is to resize with JS, but I thought this was simpler.

**Comment by quicksketch** [comment]
Fixes in https://github.com/backdrop/backdrop/commit/595830657cf67d53025680687e132ef21f233b2a.
