### ISSUE TITLE
Remove "type = module" from redirect.tests.info

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1871]
I'm getting a bunch of errors and I cant test.

`( ! ) WARNING: ILLEGAL STRING OFFSET 'FILE PATH' IN C:\WAMP64\WWW\BACKDROP\CORE\MODULES\SIMPLETEST\SIMPLETEST.MODULE ON LINE 331`
`( ! ) WARNING: ILLEGAL STRING OFFSET 'GROUP' IN C:\WAMP64\WWW\BACKDROP\CORE\MODULES\SIMPLETEST\SIMPLETEST.MODULE ON LINE 341`

**Comment by docwilmot** [comment]
Well, maybe not, but I found an old copy of rediret contrib in my modules folder that was causing the issue. This may however be related to the fact that `redirect.test.info` has a `type = module` in it.

**Comment by docwilmot** [comment]
Change the title so this can be the bugfix issue. Dont know how it could have messed up the testing page, but it seems to be related.

**Comment by quicksketch** [comment]
Thanks! Fixed in https://github.com/backdrop/backdrop/commit/6d1018ea29b36f89a8ca0cdeea8b6fe1dafd20cc.
