### ISSUE TITLE
Fix typos in the 1.4.0 release notes.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1872]
What a race!! We all did great with this release :+1: I'm really proud of us :smile: 

A few typos that need to be fixed in the [1.4.0 release](https://github.com/backdrop/backdrop/releases/tag/1.4.0) text:

>...includes several major ~~new~~ and exciting new features!
...
> ...allows redirects to be created ~~to~~ manually between paths...

**Comment by quicksketch** [comment]
Thanks fixed!
