### ISSUE TITLE
Upgrade procedure - Delete "Core" folder? 

### ISSUE THREAD

**Issue by maxmeno** [backdrop/backdrop-issues#1873]
I think not so long ago we talked about NOT suggesting to delete the whole Core folder during an upgrade. The https://backdropcms.org/upgrade page suggests to backup the database and the config_* directory, but wouldn't be safer to just RENAME the whole Core folder instead of deleting it, and deleting it only after a successful upgrade?

Also, the 1-to-8 steps could probably be reordered - #6 ( log-in as an administrator ) should be before #3 and #4. (If anything goes wrong with #5, logging in could be a problem….)

**Comment by quicksketch** [comment]
Thanks @maxmeno! Great suggestions. We have a few editors that might be able to make these adjustments, @docwilmot, @klonos, or @jenlampton?

**Comment by jenlampton** [comment]
How's this? https://backdropcms.org/upgrade

**Comment by serundeputy** [comment]
@jenlampton 

> How's this? https://backdropcms.org/upgrade

I think that is a great improvement!

I would maybe™ alter this line:

> Make a backup of the "config_*" directory (located in your files directory unless otherwise specified).

from `config_*` to `conf_{config_hash}` similar to `config_8163354cb2fae81f701e06f448a0bfe8` where the `_8163354cb2fae81f701e06f448a0bfe8` will be unique to your site.

The point is in this case `*` is not a wild card like any directory matching that pattern there is just one `config_{config_hash}` directory per site that has the sites `staging` and `production` config directories.

As I write this it occurs to me that the instructions here How's this? https://backdropcms.org/upgrade should be the `tl;dr` set and there could be a more comprehensive how to to it with git/locals, how to do it on Pantheon, etc.

**Comment by klonos** [comment]
> wouldn't be safer to just RENAME the whole Core folder instead of deleting it, and deleting it only after a successful upgrade?

I *always* do that. I rename old versions by appending their version of core to the dir name and I also tent to keep a couple of copies back for testing purposes. So I end up with `/core` (current), `/core134`, `/core135`, `/core136` etc. I used to also do the same for current (so `/core140`) and have `/core` be a symlink that I could then conveniently point to which ever directory/version I want. ...but that has recently caused pain (https://github.com/backdrop/backdrop-issues/issues/1859#issuecomment-219598804).

**Comment by maxmeno** [comment]
@serundeputy

> from config_* to conf_{config_hash}

I could be baffling for the casual user, the * is commonly understood even by Windows-only types...

The new page version looks good to me

**Comment by jenlampton** [comment]
> from config_* to conf_{config_hash}

Why don't we just use words instead?  something like ... `Make a backup of the config directory (it's located within the 'files' directory and begins with 'config_` unless otherwise specified in the settings.php file).`

**Comment by serundeputy** [comment]
> Why don't we just use words instead? something like ... Make a backup of the config directory (it's located within the 'files' directory and begins with 'config_' unless otherwise specified in the settings.php file).

Yes! 👍

**Comment by klonos** [comment]
:+1: from me too.

**Comment by maxmeno** [comment]
sounds perfect.
I'm closing this, since @jenlampton already added the final touch to https://backdropcms.org/upgrade
