### ISSUE TITLE
[UX] Views UI: Improve the modal title and help text for the "Block name" modal

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1885]
Related to #1880...

Basically, I don't like the modal title the way it is now on the Views UI end. I think that when users see the word "description", they expect fields with long chunks of text like help texts (example: the content type descriptions like "Use <em>articles</em> for time-sensitive content like news, press releases or blog posts."). What we are asking for here is a short text instead.

Because "Block admin **title**" might mislead people that speed-read and miss the word "admin" there, and so would "Block admin **name**" (people might confuse it with the **machine** name), I think that we should change it to "Block admin **label**" instead. We use the term "admin **label**" in custom blocks too and it makes more sense:

![backdrop-add_custom_block_form](https://cloud.githubusercontent.com/assets/2423362/15342104/44ce1494-1cd6-11e6-97d7-58a5994eb40d.png)

...also replace the help text with the one we use in custom blocks:

> Used in administrative interfaces and not shown to end-users.

This is less specific and would account for cases where we use the block label in other parts of the admin UI besides the layouts "Add block" modals.

Current status:

![backdrop-views_ui-block_name_modal](https://cloud.githubusercontent.com/assets/2423362/15342464/bc9de722-1cd8-11e6-923e-c7cb1a8a9d0b.png)

Suggested mockup:

![backdrop-views_ui-block_admin_label_modal](https://cloud.githubusercontent.com/assets/2423362/15342465/bca9402c-1cd8-11e6-87c7-cedbd95e2b82.png)

PR coming up...

**Comment by quicksketch** [comment]
This looks good to me. :+1:
