### ISSUE TITLE
[UX] *Always* include the "View: [view_name]: [block_display_name]" as the default admin label for blocks provided by views.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1889]
Steps to reproduce:
1. Create view generating content and call it "Content" (I'm feeling very creative today :smile: )
2. Add a block display for the view -> default display name is "Block"
3. Add another block display in the same view -> default display name is "Block 2"
4. Save the view.
5. Head to the layout admin UI and edit any layout.
6. Click the button to add a block in any region.
7. In the "Search" field type "view" (to filter the available blocks to only those provided by views) ->
   
   ![backdrop-layout_ui-add_block-views_1st_block_display_name_not_appended_to_default_block_admin_title](https://cloud.githubusercontent.com/assets/2423362/15344865/913b14f0-1ced-11e6-9475-8c9629b110a1.png)
   
   Notice how **the default views block display name** "Block" **is not appended to the block admin label**...
8. Rename one of the block displays to "Pages" and the other to "Posts"
9. Save the view.
10. Head to the layout admin UI (or refresh page if already there) and edit any layout.
11. Click the button to add a block in any region.
12. In the "Search" field type "view" (to filter the available blocks to only those provided by views) ->
    
    ![backdrop-layout_ui-add_block-all_views_block_display_names_appended_to_default_block_admin_titles](https://cloud.githubusercontent.com/assets/2423362/15344871/a13b785e-1ced-11e6-9fce-62a0326b2f70.png)
    
    The display name is appended to the block admin label **after the display was renamed**.

We should always make sure that the default block display name is "View: `[view_name]`: `[block_display_name]`" and specifically that the `[block_display_name]` part is not omitted.

**Comment by quicksketch** [comment]
I personally prefer the word "Block" being left off by default, it seems superfluous if there is only a single block display...

But I don't like the inconsistency when there are multiple blocks available in the same view. And I probably wouldn't like it if a view that had multiple blocks was next to a view that didn't...

So in the end I agree with you here. Let's just always include the full name.

**Comment by klonos** [comment]
> I personally prefer the word "Block" being left off by default, it seems superfluous if there is only a single block display...

There you have it then. We can check whether a view has more than one block and if so, only then append the display name to the block label. But is that worth the complexity? ...plus the inconsistency thing that you also mentioned.

Anyways, the bug here is not the UI inconsistency itself. That is rather the result in the specific use case I used. The bug is that when a view block is created, it is shown in the block browser as "View: `[view_name]`" but when you rename it, it is shown as "View: `[view_name]`: `[block_display_name]`". Steps to reproduce:

1. Create a view with a block display
2. Head to the layout admin UI and edit any layout.
3. Click the button to add a block in any region.
4. In the "Search" field type "view" (to filter the available blocks to only those provided by views) -> the block provided by the view created in step 1 above is shown as "View: `[view_name]`"
5. Head back to the view and rename the block display (remember to save the view)
6. Head back the layout admin UI and edit any layout.
7. Click the button to add a block in any region.
8. In the "Search" field type "view" (to filter the available blocks to only those provided by views) -> the same block (provided by the view created in step 1 above and renamed in step 5) is shown as "View: `[view_name]`: `[block_display_name]`" now

Hope that is clearer now :wink:

**Comment by klonos** [comment]
Not 100% sure if the rename is the only thing that triggers the addition of the block display name to the label. It could be editing other settings of the view or the display. It could be rearranging the displays.

**Comment by BWPanda** [comment]
If I've understood this issue correctly, then I think this [PR](https://github.com/backdrop/backdrop/pull/2774) should fix it...

**Comment by bugfolder** [comment]
FWIW, I, too, think being consistent (always showing the block name, even for a single block) is preferable. So I agree with this PR's approach.

Unfortunately, it's now in conflict. @BWPanda, are you available to update the PR?

**Comment by klonos** [comment]
Filed a fresh PR off of Peter's: https://github.com/backdrop/backdrop/pull/4577

Nothing changed other than rebasing and fixing conflicts.

**Comment by stpaultim** [comment]
I think this is a good change. 

However, I found a possible problem with the PR. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/24f08e3d-ebdb-4946-8ac3-b65b26a771d1)

It seems the block UI for layouts can't handle an apostrophe, even though the views UI can and even though it displays fine on the layout page.

**Comment by herbdool** [comment]
@stpaultim the issue you found exists even without this PR, so I think this PR is ready.

**Comment by quicksketch** [comment]
There's a failing test caused by this change:

```
Status    Group      Filename          Line    Function                            
------------------------------------------------------------------------------------------------------------------------
Fail      Browser    views_layout.test 119     testViewsLayouts()                                                      
    Link View: Layout Context Test (User account) does not exist on
    http://localhost/admin/structure/layouts/manage/test_context_layout/add-block/editor/content
```

**Comment by quicksketch** [comment]
I pushed a tiny fix to the tests that should get this passing.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4577 into 1.x and 1.26.x. Thanks folks!
