### ISSUE TITLE
'Execute PHP' block doesn't work

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1891]
Before I found the [Blockify](https://backdropcms.org/project/blockify) module I thought I'd have to output my site's slogan in a block using PHP code. So I found and added the 'Execute PHP' block to my layout, only to find it doesn't do anything - no way to add PHP code. My first thought was that I need to enabled the PHP Filter module, but there isn't any. Then I checked contrib, and none there either...

![firefox_screenshot_2016-05-18t06-03-25 625z](https://cloud.githubusercontent.com/assets/2385329/15348952/22ef73b8-1d12-11e6-9981-8fd0ebe18d07.png)

Regardless, the 'Execute PHP' block in core doesn't work. Should it be removed or fixed?

**Comment by quicksketch** [comment]
I don't think there is an Execute PHP block in Backdrop. We removed it prior to 1.0 being released. See https://github.com/backdrop/backdrop-issues/issues/19. So I'm not sure where this block would be coming from, I don't think there was a port even for Backdrop.

**Comment by BWPanda** [comment]
Huh, ok...

Sorry, my bad. It's Devel's block which adds a textarea where you can add PHP code when the block is rendered.
