### ISSUE TITLE
Rich text editor and release 1.4.0

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1892]
What is the status of CKEditor in our latest release?
I am having difficulty with adding images because the upload image does not seem to be working even though I have the option 'enable image uploads' ticked?
I have tried a new installation and I now have no idea how to set up Backdrop to do this. What am I missing?

**Comment by quicksketch** [comment]
Hi @Graham-72, I just tried it as well. I reproduced a problem by doing the following:

- Install Backdrop 1.4.0.
- Create a Post.
- Click the "Image" button on the body field.
- Dialog opens. Upload an image.
- Click Save.
- Nothing happens. The image is not inserted.

Is this what you are seeing as well?

**Comment by Graham-72** [comment]
@quicksketch Yes, exactly that. Also, I was wondering whether I needed to provide the folder 'inline-images' to make it work, but that made no difference.

**Comment by quicksketch** [comment]
I think this is related to the upload support for direct-from-camera uploads. Apparently we (I) introduced a JS error when uploading files. I'll make a PR to fix this. Thanks for reporting the issue @Graham-72!

**Comment by Graham-72** [comment]
@quicksketch Thanks.

**Comment by quicksketch** [comment]
This should fix it: https://github.com/backdrop/backdrop/pull/1403

A debugging line affects all fields that have auto-uploading enabled, so this could affect normal file fields as well. Removing the line seems to fix the problem.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/issues/1403. I'll be making a 1.4.1 release tomorrow with the fix. Thanks @Graham-72!
