### ISSUE TITLE
[UX] Remove "new" from any "Add new X" page titles.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1893]
In #399 we removed the "new" part of "Add new X" menu items in the admin bar. We have a few left-overs in some page titles:
- [x] "Add new block" in `/admin/structure/block/add`
- [x] "Add new comment" in `/comment/reply/*`
- [x] "Add new content" in `/node/add`
- [x] in `/admin/structure/types/add`
- [x] "Add new view" in `/admin/structure/views/add`
- [ ] ...

**Comment by klonos** [comment]
I think I got them all.

**Comment by quicksketch** [comment]
Thanks! Looks great and tests pass. Merged into 1.x for 1.4.1.

**Comment by klonos** [comment]
Thank you!
