### ISSUE TITLE
[UX] Views UI: Improve or remove the .views-display-help text.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1896]
That is the text that is shown above the view edit form:

>Modify the display(s) of your view below or add new displays.

Suggestion to change it to:

>Modify existing displays of your view or add new ones.

**Comment by klonos** [comment]
This was a simply UI text change and yet there were errors with Travis. Some help please?

**Comment by quicksketch** [comment]
Sounds good to me.

I restarted the failing tests. The "random" fails happen a lot more frequently since the Travis-CI server switch. We still have an issue tracking them at #1478.

**Comment by klonos** [comment]
Thanx @quicksketch

**Comment by Bojhan** [comment]
Do you need any of this text at all? :)

**Comment by quicksketch** [comment]
> Do you need any of this text at all? :)

Fair point... what do you think about just dropping the text entirely @klonos?

**Comment by klonos** [comment]
I thought I replied to this about a week ago, but must have forgotten to submit...

I do not need that text. And certainly you guys don't either ...but we've been using Drupal for years. The Views UI is not an easy one for newcomers though and we need to consider them. I was thinking that in the site configuration or in each user's account settings, we could have a "Show help text" checkbox that is on by default (or a "Hide help text" that is off by default). That should cover our case: advanced users that value saving UI space over having help/tips available.

**Comment by Bojhan** [comment]
I doubt this particular text even helps new people. It just says that this is an edit screen and to press "add" for a new one. That shouldn't require explaining. Explaining the concept should be done on the overview page. 

For checkboxes I think limi.net/checkboxes-that-kill/ is still worth a read :)

**Comment by klonos** [comment]
OK, I personally do not mind which way we choose to go, so here's a second PR.

https://github.com/backdrop/backdrop/pull/1437 : removes the text entirely.
https://github.com/backdrop/backdrop/pull/1406 : changes the text to make a bit more sense by not repeating the word "display".

**Comment by klonos** [comment]
...small UI fix that could go in in 1.4.3

**Comment by quicksketch** [comment]
I went with door number 1. Merged https://github.com/backdrop/backdrop/pull/1437 (remove entirely) for 1.4.3. Thanks @klonos!

**Comment by klonos** [comment]
😉
