### ISSUE TITLE
No warning in the site status report about the contrib Project Browser being present.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1898]
I thought we had warnings displayed when a contrib project was merged into core but was also detected as installed after upgrading core to the version that includes it. This did not happen for me in 1.4.0 or 1.4.1. I realized that PB contrib was still installed when I happened to browse the list of modules. There was a warning there, but not on the site status page.

Any body else noticed this?

**Comment by quicksketch** [comment]
I don't think we gave Project Browser the same level of treatment as we did for Redirect, Link, Email, and other modules that have been merged into core. For each of those, we made both an update hook and an entry in hook_requirements() to show an error on the status report page.

It may have been the fault of the last-week rush, but even re-evaluating it now I don't think we would have added all of that for Project Browser anyway, as it never had a real release and doesn't seriously conflict with the core Project Installer module.

**Comment by klonos** [comment]
Fair enough then.
