### ISSUE TITLE
How to install modules?

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1903]
I have upgraded from 1.35 and do not see the option to add modules and themes

![aaa](https://cloud.githubusercontent.com/assets/13515302/15401713/6cca678a-1df9-11e6-8879-9c81d1d67431.png)

**Comment by ItangSanjana** [comment]
Install Project Installer module first? CMIIW

**Comment by bd0bd** [comment]
I am not kidding.

What happened? Why it has disapeared?

**Comment by bd0bd** [comment]
Thank you very much for advice!

But why the module was deactivated?
I have upgraded many times within many months and never this happened.

**Comment by Gormartsen** [comment]
@bd0bd just for the record.
You run update.php and it is 1.4.x version.

Is it correct?

**Comment by MrHaroldA** [comment]
Did you manually enable the 'Project installer' module?

![image](https://cloud.githubusercontent.com/assets/695291/15405405/fb5457f6-1e01-11e6-85e8-95facba23764.png)

**Comment by bd0bd** [comment]
@Gormartsen ,  I do not know.
I always replace the core folder.
Everrything was ok beforre.

@MrHaroldA , now I know. But I do not remember I did it before in previouse BD versions. It was enabled by default, no?

**Comment by Gormartsen** [comment]
@bd0bd it is new module that allow you install modules and themes without download them manually into modules or themes folder

**Comment by klonos** [comment]
dupe of #1847
