### ISSUE TITLE
Warning: file_get_contents(core/modules/user/user.permissions.js): failed to open stream

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1904]
Environment: php 5.5, backdrop 1.4.2
**Flushing all the caches and then**
saving a change for an **Text field** (for example changing the helptext  for the Page type -> 
http://opi.vtadtest.de/admin/structure/types/manage/page/fields)  I get

> Warning: file_get_contents(core/modules/user/user.permissions.js): failed to open stream: No such file or directory in _locale_parse_js_file() (Zeile 567 von /home/www/backdrop/core/includes/locale.inc).
> 
> Warning: file_get_contents(core/modules/user/user.permissions.js): failed to open stream: No such file or directory in backdrop_build_js_cache() (Zeile 5291 von /home/www/backdrop/core/includes/common.inc).

Repeating without cache flush works ok.

**Comment by quicksketch** [comment]
Hi @vtad! Thanks for the bug report. It looks like what is happening is `core/modules/user/user.permissions.js` is trying to be added, but that file doesn't exist there. `user.permissions.js` is under a `js/` sub-directory.

So there must be a place where the path without `js/` is being used. I did a search through the code base, and all places where that file is added, it has the correct path. Perhaps a contrib module is causing this problem? Do you have a module like field_permissions.module installed? I think it may be the source of the problem based on this code:

https://github.com/backdrop-contrib/field_permissions/blob/1.x/field_permissions.admin.inc#L289

**Comment by vtad** [comment]
I had field permissions installed. I am going to do a fresh install of 1.4.2 in order to see if the problem is still there. Closing this issue  until then.
