### ISSUE TITLE
Images not uploaded automatically

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1907]
As far as I can see from the issue queue and the lack of an 'Upload' button next to image fields, Backdrop automatically uploads images when they're selected (cool!).

But, it doesn't appear to be working... I have an image field and I can browse and select an image, but nothing happens after that. I can click Save to save the node and the image is there (uploaded), but as I have an 'alt' field with my image, I expect to be able to see that (and a thumbnail of the uploaded image) before I save the node. Is this a bug or intended functionality?

**Comment by BWPanda** [comment]
Marking as a bug until someone informs me otherwise.

**Comment by quicksketch** [comment]
Hi @BWPanda! This was a bug in 1.4.0, you can solve it by upgrading to 1.4.2. It should have been fixed in https://github.com/backdrop/backdrop-issues/issues/1892. Could you confirm?

**Comment by BWPanda** [comment]
Ah ok. Sorry about that. Will upgrade and test and report back if there are further issues.
