### ISSUE TITLE
Improve update experience

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1911]
I would like to propose that improving the update experience should become another objective for 1.5.

Ideally, I would like it to be able to happen automatically as with Wordpress, but at least it is something we should be able to delegate to a knowledgeable client.

As an example of something I find confusing with our current situation, here is a screenshot of what I was faced with this morning:
![backdropupdateprocessscreenshot](https://cloud.githubusercontent.com/assets/10559274/15419672/a70894e2-1e5f-11e6-9cbf-3215e16e9b0e.png)

**Comment by Gormartsen** [comment]
:+1: to add update process to 1.5

We could add option backup restore !

**Comment by quicksketch** [comment]
So some issues here aren't caused by core, some are:

- The first message is output when a module specifies `hook_update_last_removed()` and the current "schema_version" in the system table isn't past this number.
- The second message is coming from Backup and Migrate module. Maybe we could just remove it?
- The third message is caused by the first message's situation resulting in the updates being impossible.

So the only issue for core here is to resolve the double messaging between "No pending updates" message, which is inaccurate.

**Comment by Graham-72** [comment]
@quicksketch thanks for the explanation. Is there some easy wasy to find out which contrib module is causing the first message?

**Comment by klonos** [comment]
> Is there some easy wasy to find out which contrib module is causing the first message?

The message says that some pending updates were not applied. I would try running update.php again (manually) to see it that lists the still pending updates. Each update says which module it is for.

**Comment by Graham-72** [comment]
> try running update.php again

I have now tried this but it just produces exactly the same screen and no logs showing updates that have not been done. Perhaps I will have to look through the system table and check schema version records.

**Comment by Bojhan** [comment]
Just wondering - what is keeping us from going down the Wordpress path? Is our kernel not decoupled enough?

**Comment by docwilmot** [comment]
> Just wondering - what is keeping us from going down the Wordpress path? Is our kernel not decoupled enough?

No you've go me wondering too: whats the Wordpress path?

**Comment by klonos** [comment]
> Now you've got me wondering too: whats the Wordpress path?

I believe that @Bojhan is referring to the one-click "upgrade" buttons that take care of fetching, unpacking and upgrading of WP core and addons.

**Comment by klonos** [comment]
![wp-plugins-one-click_upgrade](https://cloud.githubusercontent.com/assets/2423362/15539756/96a5e804-22c7-11e6-88b4-bc7d94559c6b.gif)

**Comment by klonos** [comment]
...there is even a bulk action for it:

![wp-plugins-update_bulk_action](https://cloud.githubusercontent.com/assets/2423362/15539819/f51bb210-22c7-11e6-8f2d-a4504eae0ac3.png)

**Comment by Graham-72** [comment]
I have a couple of Wordpress sites on my server and from time to time they update automatically, sending me an email to say they have done so. In their particular case this suits me just fine.

**Comment by klonos** [comment]
I wonder if this issue should be closed as outdated now @Graham-72 (and others). Between 2016 and now, we have implemented #3105 and #3271 and we have things like #1992 and #414 in our roadmap.

If we could have the specific modules and their respective before/after versions that caused the mess as shown in the screenshot in the initial report, then perhaps we could work something out to improve the situation. Without some steps to reproduce, it makes it hard 😓

**Comment by Graham-72** [comment]
I'm happy to close this issue as things are a lot better now and we have #2018 for automatic updating.
