### ISSUE TITLE
Admin bar not extending across the top of my screen.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#1917]
On my sites now updated with 1.4.2 the admin bar appears as before - across the top of the screen with drop-down sub-menus.

On a fresh build the admin bar is down the left hand side with sub-menus floating out to the right. Is there some setting I have missed? Has anyone else experienced this?

**Comment by quicksketch** [comment]
That's odd, we didn't change the admin bar appearance at all and it should act the same as before. Could you post a screenshot of what you're seeing?

**Comment by Graham-72** [comment]
@quicksketch here is a cropped piece of the screenshot. It is doing this in both Firefox and Chrome, and replacing with a fresh copy of core has made no difference. Maybe something outside of core is corrupted. I will try a complete fresh install and see if this happens again. Presumably something is missing in CSS, or overwritten somewhere.
![adminmenu](https://cloud.githubusercontent.com/assets/10559274/15480077/77f04ba0-211b-11e6-8567-7bbe32f63f58.jpg)

**Comment by Graham-72** [comment]
I have not yet found the root cause of this. I have made a fresh installation of 1.4.2 and it works as it should. By comparison, it seems that in the faulty installation the class 'dropdown' is not being replaced with 'top-level' by admin_bar.js and I am now wondering why this should be.

**Comment by docwilmot** [comment]
This sounds like a contrib project messing with your menu, but you said fresh build. Strange.

**Comment by klonos** [comment]
This looks like the admin bar has shifted to mobile version. That alone would be normal-ish (are you on mobile/tablet?), but there's also the 2nd+ level items that have moved as top-level ones that I cannot explain. Here's what the admin bar looks on narrow viewports for reference:

![backdrop-admin_bar-mobile](https://cloud.githubusercontent.com/assets/2423362/15523984/d7753a12-2261-11e6-8269-f3cf2a6d9a03.png)

**Comment by Graham-72** [comment]
I have tried uninstalling then re-installing admin bar and there is no change.
If I copy the data base into a new Backdrop installation the problem reappears in the new site. The database originated from a D7 site that I am trying to convert to Backdrop. I now need to find out which tables in the database might contain settings that cause this problem. Why is the javascript not replacing the class 'dropdown' with 'top-level'?

**Comment by Graham-72** [comment]
I can now see what has happened, though I don't yet know why. There are 10 items in the  Management menu that are appearing in its top level rather than in their correct place, something that has happened when importing the data from the D7 version. So now, in Backdrop, admin_bar.js is calculating the menuWidth value to be greater than the availableWidth and so is not expanding the menu horizontally.

**Comment by Graham-72** [comment]
I am closing this issue for now, but need to watch out for this in the future when converting D7 sites to Backdrop.
