### ISSUE TITLE
[DX] Provide a mechanism for menu callbacks to JSON only

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1924]
Relate to #1736 somehow.

I am working on JSON api and noticed that even if I use my own delivery callback, there is layout response back.

The issue in backdrop_is_html. Layout module believe that it's html based on next login:

```
empty($_SERVER['HTTP_ACCEPT']) || strpos($_SERVER['HTTP_ACCEPT'], 'text/html') === 0 || empty($_SERVER['HTTP_X_REQUESTED_WITH']);
```

will send PR shortly.

**Comment by quicksketch** [comment]
Hi @Gormartsen, thanks for opening this issue. So the problem we encountered in #1736 is that IE8 doesn't send 'text/html' in its Accept header (but it does include one). This resulted in all pages served to IE8 to not receive a layout, because Backdrop thought it wasn't an HTML page.

I think we need to fix this in two different ways. The first would fix this particular problem you encountered:

- Modify `layout_route_handler()` to detect if a different `delivery_callback` is set. If so, do not wrap it in a layout.
- Change our detection mechanisms to avoid using the `Accept` header entirely, as it is inconsistent between different browsers and also causes issues with the page cache (both the internal Backdrop page cache and reverse proxies like Akamai and Varnish).

Let's handle the first approach here and the second approach in https://github.com/backdrop/backdrop-issues/issues/1664.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/1430 that I'd like Travis to take a go at testing. It stops the use of `backdrop_is_html()` entirely in `layout_route_handler()`.

**Comment by Gormartsen** [comment]
@quicksketch thank you to catching it up. I did not have time to finish up my PR backdrop/backdrop#1414 .

Looks like I took a wrong approach. It was working for my website but broke many tests.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1430 into 1.x for 1.5.0. This does have a small chance of affecting existing code, but probably only in positive ways. Even though this is a bug fix, the change was required to fix the behavior of `backdrop_is_html()`, which was unreliable. So for now this is going into 1.x only. 1.5.0 isn't very far away.

**Comment by quicksketch** [comment]
Ah, this caused AJAX requests in some situations to break, specifically Batch Operations, see https://github.com/backdrop/backdrop-issues/issues/2113. Back to the drawing board on this one. The commit has been reverted.

**Comment by quicksketch** [comment]
Okay I made a new PR at https://github.com/backdrop/backdrop/pull/1518 that is less aggressive and simply provides a mechanism for menu callbacks that render JSON to not be affected by the Layout module's attempts to wrap content.

For many existing menu items, we had been doing this:

```
$data = array('foo' => 'bar');
backdrop_json_output($data);
backdrop_exit();
```

And the menu callback didn't return anything at all. This is not good for a couple of reasons:

- We don't know whether the menu item is going to return JSON or HTML until after it has been called.
- The menu callback is printing to the page directly and returns NULL. This makes determining the actual output difficult or impossible.
- The developer needs to determine whether to call `exit()` or not, or `backdrop_exit()`. Forcing the ending of the execution of the page could leave cleanup tasks undone.

So the solution for pages that return JSON now is to specify a delivery callback in hook_menu():

```php
$items['user/autocomplete'] = array(
  'title' => 'User autocomplete',
  'page callback' => 'user_autocomplete',
  'delivery callback' => 'backdrop_json_deliver', // <- New line.
  'access callback' => 'user_access',
  'access arguments' => array('access user profiles'),
  'type' => MENU_CALLBACK,
  'file' => 'user.pages.inc',
);
```

And then in the menu callback, it now just returns the data to be printed as JSON as it's data structure.

```
$data = array('foo' => 'bar');
return $data;
```

Layout module for its part will immediately ignore any page that has a `delivery callback` specified in `hook_menu()`. Previously it depended on `backdrop_is_html()` which is unreliable, now it determines whether it should wrap content based on the delivery callback.

**Comment by quicksketch** [comment]
I think this one is ready for merge, but if we get another set of eyes on it that would great.

**Comment by quicksketch** [comment]
Let's merge this so we can weed out any lingering issues prior to release. Merged again for 1.x and 1.5.0.
