### ISSUE TITLE
1.4.2 Regression: Layout UI: no "dirty form" messages when editing/(re)moving blocks.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1925]
...it could be because of the new layouts in core.

**Comment by Dinornis** [comment]
Marking this as duplicate of https://github.com/backdrop/backdrop-issues/issues/1722

**Comment by klonos** [comment]
Thank you once again @Dinornis ...forgetting my own issues ...signs of premature dementia perhaps 😆
