### ISSUE TITLE
Layouts: empty .dropbutton-* <divs> in the last <td>s of .layout-group <tr>s

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1931]
The last `<td>`s of the `.layout-group` `<tr>`s render like so even if there are no contents (action dropbutton):

``` html
<td>
  <div class="dropbutton-wrapper dropbutton-processed">
    <div class="dropbutton-widget"></div>
  </div>
</td>
```

Lets put a conditional to render them as empty `<td>`s instead for a bit cleaner markup.

While at it, perhaps also make the 1st `<td>`s of these rows ("Path and layout" column) span in the rest of the two `<td>`s ("Visibility conditions" and "Storage state"). It will keep the "Default layouts ..." text in a single row in wide enough screens which will slightly reduce the page height (less scrolling).

Before:
![backdrop-issue1931-before-layout_group_row_title_in_one_cell](https://cloud.githubusercontent.com/assets/2423362/15564369/d07b9bf4-2354-11e6-9e32-4af7ee2c1e12.png)

After:
![backdrop-issue1931-after-layout_group_row_title_in_three_cells](https://cloud.githubusercontent.com/assets/2423362/15564368/d07754f4-2354-11e6-835e-ad17af4a312c.png)

I will give a PR a go...

**Comment by klonos** [comment]
The first commit in my PR (https://github.com/backdrop/backdrop/pull/1416/commits/6456c0bafdaa463b52b9b4f03c7db6ae1be98e27) simply removes the empty `.dropbutton-*` `<div>`s by checking if there are actually any `$operations['#links']`. Not sure if there is a better way?

In the second commit (https://github.com/backdrop/backdrop/pull/1416/commits/9dff5a9cc790761fda46084abe5dd2ed792af0bd), I tried to remove the hack we've put in place in order for the columns to get the proper `priority-low` class for responsiveness, but I've hit a wall. It's not the same rendering issue that @docwilmot has hit, as in my PR sandbox the rows do not bleed outside the table borders to the right. My issue is that the last cells in these rows (the ones containing the dropbuttons) get a `priority-low` class and thus get completely hidden when switching to mobile.

**Comment by quicksketch** [comment]
I cherry-picked out the first commit into 1.x and 1.4.x that solves the original issue. We can try to solve the table-cell issue separately, that might take a more substantial effort. Thanks @klonos!

> While at it, perhaps also...

Slippery slope that one! :wink:
