### ISSUE TITLE
Replace all instances of "http://backdropcms.org" with their respective "https://" URL.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1934]
...as per issue title.

**Comment by klonos** [comment]
...updated a few page titles and replaced some URLs with their respective shorter ones while at it.

**Comment by quicksketch** [comment]
This looks great! Thanks @klonos! Merged https://github.com/backdrop/backdrop/issues/1418 into 1.x.

**Comment by klonos** [comment]
:+1:
