### ISSUE TITLE
[UX] Layout UI: Allow blocks to be disabled/hidden instead of removed.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1936]
This was the initial goal of #1776 as filed by @Graham-72:

>  Is there a way I could suspend publication of a block i.e. unpublish it as one can for a node?
> 
> I have a small block that provides a special notice to site visitors and appears in three or more layouts. It would be useful to be able to suspend it when not needed then republish it later with different text.

@docwilmot has provided two contrib modules that provide intended functionality:
- https://github.com/backdrop-contrib/block_scheduler adds a "Datetime" visibility condition for blocks
- https://github.com/backdrop-contrib/block_disabler adds an extra option on the block dropbutton to enable/disable

**Comment by klonos** [comment]
A simple set of Hide/Show actions added to the ones available in the block dropbuttons would suffice I believe:

![backdrop-layouts-show_hide_actions_for_blocks](https://cloud.githubusercontent.com/assets/2423362/15268830/6a2a2aba-1a2f-11e6-9817-a8cd208d49ab.gif)

**Comment by Graham-72** [comment]
This would be excellent, thank you.

**Comment by maxmeno** [comment]
> Is there a way I could suspend publication of a block i.e. unpublish it as one can for a node?

+1
That's a feature that I would use often. One case: I have a "next races" block that I need to publish when the race docs are scheduled to be available and unpublish as soon as the event is done. The `publish/unpublish on a specific date and time` function would be great.

An "**empty page and else cache**" function would be needed too for this to work, if a specific publish/unpublish time is required.

**Comment by klonos** [comment]
@maxmeno the feature of scheduling publishing/unpublishing (#1776) has been turned down for inclusion in core. @docwilmot said he'll put all the code he's got so far for that in a contrib module and let us know. Point is this issue here is to simply add a "manual" on/off switch for blocks.

**Comment by maxmeno** [comment]
> Point is this issue here is to simply add a "manual" on/off switch for blocks

uh - ok. But I'm a bit confused. In BD is currently not possible to _unpublish / re-publish later_ a block like I do everyday in Drupal?

**Comment by Graham-72** [comment]
But exactly how do you do this in Drupal? Is there a module for this?

**Comment by maxmeno** [comment]
Not that I'm aware of. I either remove the block from the region it was assigned to, letting it go into the `inactive` block group, or work with the visibility option, choosing `only show on the following pages` and leaving the field empty. 
All manual work

**Comment by klonos** [comment]
> @docwilmot said he'll put all the code he's got so far for that in a contrib module and let us know.

https://github.com/backdrop-contrib/block_scheduler/releases/tag/1.x-1.0.0 :wink:

**Comment by klonos** [comment]
https://github.com/backdrop-contrib/block_disabler

Thanx again @docwilmot 😉

**Comment by BWPanda** [comment]
Perhaps this issue should now be focused on merging 'block_disabler' into core...?

**Comment by philsward** [comment]
I would agree to this @BWPanda. Layouts is a hybrid approach to D7 Panels, and panels had this baked in. I use it all the time for Panel panes (I rarely use d7 blocks because they are too 1 dimensional).

I would think it should be no different with blocks and layouts.

**Comment by stpaultim** [comment]
I want to mention these two other issues. I guess that this one is about an admin interface to disable or hide blocks, where the other two are about [accordion blocks](https://github.com/backdrop/backdrop-issues/issues/3995) or [dismissable blocks](https://github.com/backdrop/backdrop-issues/issues/3996).

**Comment by stpaultim** [comment]
This issue is getting some traction in our feature request survey - https://forum.backdropcms.org/feature-requests

This has lead to discussion about merging the Block Disabler module into core. 
https://github.com/backdrop-contrib/block_disabler

**Comment by docwilmot** [comment]
PR up. We could debate the correct word to describe block status: "disabled" vs "hidden"?

**Comment by stpaultim** [comment]
> We could debate the correct word to describe block status: "disabled" vs "hidden"?

I haven't thought about it too much, but I think disabled sounds right.

I tried to break the PR without success. It seems to work and do what I expect of it. 

![image](https://user-images.githubusercontent.com/3144571/163095131-561e5690-1667-4cf0-ab94-c20567e810bb.png)

Should the "Configure" option stay active, even if the block is disabled and shaded? (I'm not sure, just wondering out loud.) Do we have an equivalent UI somewhere else to look at? Maybe filters on text formats?

![image](https://user-images.githubusercontent.com/3144571/163095509-19faee77-7971-4ca9-8e84-a070733d3e94.png)

Maybe this is a good example:

![image](https://user-images.githubusercontent.com/3144571/163095630-59f79e28-4c36-45a7-9192-b7b50b379942.png)

Thanks @docwilmot for working on this issue.

**Comment by docwilmot** [comment]
Good examples above, thanks. 👍 
The standard seems to be to use a fainter text-color, whereas I used opacity. Easy fix, will do later.

**Comment by docwilmot** [comment]
Done.

**Comment by stpaultim** [comment]
Love it! Works great.

![image](https://user-images.githubusercontent.com/3144571/163261130-6b4c0af8-be84-4d1a-b788-15d6d16c5f4e.png)

I would love to have one more person look at this before marking it "Works for me."

**Comment by indigoxela** [comment]
That's all great, but I do have an A11Y concern: the text contrast is nowhere near to comply with requirements.

**Comment by docwilmot** [comment]
We should also have an upgrade path for the contrib module right?

**Comment by stpaultim** [comment]
This issue was discussed in the meeting today. @quicksketch seemed to suggest that an upgrade path may not be necessary for several reasons, including the fact that this contrib module only has 6 installs. 

It looks like the contrast has been changed. It is now on par with other disabled elements in the UI. I would recommend that any additional changes in this regard be in a follow-up issue that looks at similar elements that might also need improvement (if they do)?

**Comment by stpaultim** [comment]
Can we get one more person to test this and give it a "Works for me." (If you think its ready)

**Comment by bugfolder** [comment]
First test: add a custom block to the content region of the Home page. After filling in the details of block, the Configure Blocks page shows the usual warning:

<img width="1179" alt="warning" src="https://user-images.githubusercontent.com/29214084/163581426-d65d5ee2-1703-47c2-bf78-530b0effe321.png">

I save, the new block appears. Now for the test: go back to the Configure Blocks page, choose "Disable" for the block.

There's no warning at the top of the page. Was this change applied immediately? No, it's still present on the Home page. I click "Save Layout" on the Configure Blocks page, now it disappears from the Home page.

So I think this feature needs to show the warning message at the top of the Configure Blocks page like any other change to the Blocks would do.

Ditto for re-enabling the block.

**Comment by docwilmot** [comment]
> So I think this feature needs to show the warning message at the top of the Configure Blocks page like any other change to the Blocks would do.

We dont do the message for moving blocks around either. I think there's an issue. Done nonetheless.

**Comment by bugfolder** [comment]
> We don't do the message for moving blocks around either.

By golly, you're right. Agreed that it's an issue (not this one). Meanwhile, this one works for me (both enabling and disabling).

**Comment by docwilmot** [comment]
Does this get a milestone now? I'm advocating if needed.

**Comment by herbdool** [comment]
Works well for me. Just recommended small change. @docwilmot

**Comment by stpaultim** [comment]
@docwilmot - It looks like you updated the PR. Is this one ready for code review again?

**Comment by docwilmot** [comment]
Aye

**Comment by quicksketch** [comment]
Looks great @docwilmot! I code reviewed and found only one line that might be improved: a small improvement to the `t()` call: https://github.com/backdrop/backdrop/pull/4044#pullrequestreview-951261682

**Comment by docwilmot** [comment]
Thanks @quicksketch, change made, back to needs review.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4044 into 1.x for 1.22.0! :tada:

Thanks so much @docwilmot, @bugfolder,  @herbdool, @klonos, @stpaultim, @olafgrabienski, and @indigoxela for the work to bring this feature to life! This is a great improvement for site builders to allow them to easily show/hide a block without removing its configuration. The UI is also excellent and intuitive. Great work!
