### ISSUE TITLE
filter.pages.inc duplcate doc block for `filter_format_editor_image_form` and `filter_format_editor_link_form`.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#1943]
While digging into #1586 I found this which caused me some confusion.

In `filter.pages.inc` this function doc block occurs twice:

```php
/**
 * Form callback: Display a form for inserting/editing a link.
 */
```

on line `27` and on line `80` I'm thinking on line 80 it should be:

```php
/**
 * Form callback: Display a form for inserting/editing an image.
 */
```

**Comment by quicksketch** [comment]
Great, thanks @serundeputy! Merged https://github.com/backdrop/backdrop/issues/1425 for 1.4.3.
