### ISSUE TITLE
Title Module Alternative Strategies

### ISSUE THREAD

**Issue by thejimbirch** [backdrop/backdrop-issues#1944]
Hi,

I've always used the Title module to turn the title of a node into a field for easier theme-ing in different entity view modes.  Since no one has ported that module over, I was wondering what alternatives strategies you all are using instead of the Title module.

Thanks!
Jim

**Comment by herbdool** [comment]
Good question. I just took a look if Layout allowed title to be inserted into the regions, something I'd do with Panels in Drupal 7. I don't see it even though I see all the other fields. So seems like porting Title module might be a good option here.

**Comment by herbdool** [comment]
As mentioned in #933 @thejimbirch you could also in a pinch add a Views Block of the title, add nid contextual filter, override field styles and add that to the Layout.

**Comment by thejimbirch** [comment]
It seems ctools adds the entity title as a block in D7 and D8, which seems a lot heavier to me than making Title a field, but I am not a coder...

Thanks for your suggestion on the views block.  Sounds like that would do the trick in a pinch.

Is there a place to request features/maybe post a bounty for getting a module ported?

**Comment by thejimbirch** [comment]
and thanks so much for your response @herbdool !

**Comment by serundeputy** [comment]
>Is there a place to request features/maybe post a bounty for getting a module ported?

i take bounties!  perhaps backdrop-ops?  or here for this (title field) issue is probably fine.

**Comment by thejimbirch** [comment]
Emailed you @serundeputy 
Thanks!

**Comment by serundeputy** [comment]
@thejimbirch 
Initial port is here: https://github.com/backdrop-contrib/title

I'm sure there will be bugs, but begin testing and file bug reports here: https://github.com/backdrop-contrib/title/issues

thanks,
~Geoff

**Comment by klonos** [comment]
Thanx @serundeputy

**Comment by olafgrabienski** [comment]
For anyone still interested in *Title Module Alternative Strategies*: [[UX] Make page title into it's own block ...](https://github.com/backdrop/backdrop-issues/issues/1704) was introduced in Backdrop 1.7.0, which means that the node title can be placed into a Layout region now.

**Comment by thejimbirch** [comment]
Looks like this issue should be closed then as there is now a Title module port, and the overall problem is now solved a different way in core.

**Comment by quicksketch** [comment]
Additional solution for anyone that runs across this issue... I created a contrib module that allows the title field to be positioned within the content area, in-between other fields, on a per display mode level. It might work for people looking for a lightweight solution to moving the title field: https://github.com/backdrop-contrib/title_display
