### ISSUE TITLE
Enable Git.lc/Zen.ci for testing

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#1947]
We are currently using @Gormartsen's Git.lc service for providing live sandboxes. We are considering expanding use of that service to also be our test-runner. Various alternative test runner services are being compared over in https://github.com/backdrop/backdrop-issues/issues/1906. Let's use this issue to discuss the Git.lc option specifically.

(Note, Git.lc is in the process of being renamed to zen.ci, so they may be referenced interchangeably.)

Reasons why we may want to use Git.lc:
- Preliminary test run times have been very fast. Less than 8 minutes from the time the PR is filed. (Travis CI currently takes about 20 minutes if no other tests are running)
- No caps on concurrent runs. (Travis CI currently caps us at 5)
- Consolidating on Git.lc opens up more opportunities for further automatic PR enhancements, such as automatic code review.
- We have @Gormartsen's help improving the service and accommodating Backdrop's needs.

Reasons why not:
- If Git.lc goes down, we will be stranded without a test server. Reliability isn't fully proven.

**Comment by quicksketch** [comment]
@Gormartsen in https://github.com/backdrop/backdrop-issues/issues/1906#issuecomment-222170444:

> @quicksketch Let me know if you are ok with proposed changes and ready to enable it.
I agree that we can keep travis as a backup testing.

> Somebody mentioned that for code sprint events tests speed is very important.
I have a few ideas how to enable Sprint Mode to PR.

> We can utilize 16 core CPU and have special settings for misc/zen-ci/run_tests.php script to run in 16 (or even 20) concurrency mode.

> It will speed up php53 tests up to 4 minutes in total + setup environment time. It will be like ~4-5 minutes since PR posted.

> php7 is already under 5 minutes in total. Actual tests takes 3-4 minutes. There is no need to run it on more that 8 core CPU platform. If we start it on 16 core CPU it will low down total time from 5 minutes to 3-4 minutes. It's cute a small benefit.

**Comment by Gormartsen** [comment]
@quicksketch I am around in gitter if any question appear.

> If Git.lc goes down, we will be stranded without a test server. Reliability isn't fully proven.

I believe travis config should stay on. It will be our backup then.

**Comment by quicksketch** [comment]
> I believe travis config should stay on. It will be our backup then. 

Yep, definitely while we're evaluating we'll keep both running. Thanks @Gormartsen!

**Comment by quicksketch** [comment]
Cleaned up PR filed at https://github.com/backdrop/backdrop/pull/1429.

**Comment by Gormartsen** [comment]
I closed original PR backdrop/backdrop#1413

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/pull/1429 so we now have the necessary scripts in place.

Now we just need to merge https://github.com/backdrop-ops/backdropcms.org/pull/247.

**Comment by quicksketch** [comment]
I merged and deployed https://github.com/backdrop-ops/backdropcms.org/pull/247, so this should now be active on new PRs. Is there anything else we need to do?

**Comment by Gormartsen** [comment]
@quicksketch that's it. It's already working in https://github.com/backdrop/backdrop/pull/1430

**Comment by Gormartsen** [comment]
@quicksketch I see that summary report failed. It did not report summary. 
I am checking it

**Comment by quicksketch** [comment]
Woo! Yep it's going all right. A few items of feedback:

![selection_001](https://cloud.githubusercontent.com/assets/100206/15689891/dad274e4-2735-11e6-9a5b-2809ad83aae2.jpg)

Could we make these messages a little more appropriate? e.g.

- Instead of "in full swing": "Testing in progress"
- Instead of "I get job satisfaction": Say the action that was performed like "Sandbox site ready." or "Sandbox site removed".

Now that tests are done, here's what we get:

![selection_155](https://cloud.githubusercontent.com/assets/100206/15690024/613d7920-2736-11e6-9e6e-9a3a7bea1b58.png)

- "1 test failed" :+1: Nice, helpful feedback!
- The passing tests just say "I get job satisfaction". Could it be "All tests passed!"?
- We've been working to reduce random failures, but they are still happening (as is the case in this one). Is it possible to restart a test?

From our test run at http://git.lc/backdrop/backdrop/test/test-php70-backdrop_backdrop_1430-6845

> Test run duration: 3 min 6 sec

:open_mouth: :rocket:

**Comment by quicksketch** [comment]
One more thing as a "feature request", I very commonly keep Travis CI windows open as the tests are running to see the progress as it happens. It would be great if the report pages would auto-refresh as new messages come in, though that's just nice-to-have.

Speaking of feature requests, where should we communicate bugs/features to you? It seems like a dedicated issue tracker is necessary, it doesn't seem right that we would track everything here in the Backdrop queue (though we will for issues that overlap and affect Backdrop too).

**Comment by Gormartsen** [comment]
> Instead of "in full swing": "Testing in progress"

For some reason RESTfull API request failed. It had to setup testing in progress .

> Instead of "I get job satisfaction": Say the action that was performed like "Sandbox site ready." or "Sandbox site removed".

TODO

> "1 test failed" 👍 Nice, helpful feedback!
The passing tests just say "I get job satisfaction". Could it be "All tests passed!"?

this part actually need to be replaced by API request from sandbox. Something like `XXX tests passed` or `XXXX test failed` Right now it reported that a full script failed (exit 1) due a RESTfull api FAIL. Working on it.

> We've been working to reduce random failures, but they are still happening (as is the case in this one). Is it possible to restart a test?

TODO. aprx few days to delivery this feature.

>  It would be great if the report pages would auto-refresh as new messages come in, though that's just nice-to-have.

TODO. Aprx few weeks. I am focusing to make all features work stable and release a website by itself. Then I will start to add AJAX like features.

> Speaking of feature requests, where should we communicate bugs/features to you? 

I created https://github.com/Zen-CI/issues recently. Need to fill up a readme :P

**Comment by Gormartsen** [comment]
Status update fixed (see https://github.com/backdrop/backdrop/pull/1409)

When run-test.php started (gitlc/test/php70/pr-1409):
<img width="713" alt="screen shot 2016-05-31 at 5 25 32 pm" src="https://cloud.githubusercontent.com/assets/5018896/15691174/540f1140-2755-11e6-8f25-6ac128e1d23f.png">

When tests finished:
<img width="710" alt="screen shot 2016-05-31 at 5 29 36 pm" src="https://cloud.githubusercontent.com/assets/5018896/15691175/59855a08-2755-11e6-97d0-792a2d14c3bf.png">

When you go to status report: http://git.lc/backdrop/backdrop/test/test-php70-backdrop_backdrop_1409-6848
You can see some logs at the top of the page to save some time.

**Comment by Gormartsen** [comment]
There is also a page: http://git.lc/backdrop/backdrop to track latest tests and deploys:

<img width="591" alt="screen shot 2016-05-31 at 5 35 37 pm" src="https://cloud.githubusercontent.com/assets/5018896/15691357/2780f228-2756-11e6-9e15-994d1f5da942.png">

**Comment by Gormartsen** [comment]
screen with success passed tests:

<img width="717" alt="screen shot 2016-05-31 at 7 06 01 pm" src="https://cloud.githubusercontent.com/assets/5018896/15693375/c94c84b2-2762-11e6-8ef2-b5761403ee42.png">

`549 tests passed`  Probably more correct to say `549 test cases passed` because it's amount of classes with tests. In total we have more than 10k tests

**Comment by quicksketch** [comment]
Nice, yeah # of tests passed is a good improvement.

I got this error on my most recent close/open of a PR at https://github.com/backdrop/backdrop/pull/1430:

> gitlc/test/php53/pr-1430 — Testing instance failed. Restart process. 

The log is at http://git.lc/backdrop/backdrop/test/test-php53-backdrop_backdrop_1430-6857. Looks like the server rebooted mid-test. Just bad timing?

**Comment by quicksketch** [comment]
Oh, it actually restarted itself! That's nice! The message should perhaps be "Restart _in_ progress." (a statement) rather than "Restart process." (a command).

**Comment by Gormartsen** [comment]
@quicksketch I am utilizing google cloud preemptible instances (they are much cheaper). They could be stopped by google any time. If it happens, ZenCI restart test again.

> Restart in progress.

thank you! fix applied.

**Comment by Gormartsen** [comment]
@quicksketch I think we can close this issue :)

**Comment by quicksketch** [comment]
Sure, I can file follow up issues at https://github.com/Zen-CI/issues if needed.

**Comment by quicksketch** [comment]
Travis CI has now been disabled on our repository. ZenCI has been working (and improving) for months now and is consistently better and faster than Travis.
