### ISSUE TITLE
How to get site name/slogan toggle status?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#1955]
In Drupal you could use `theme_get_setting('toggle_name')` to find out whether the site name was displayed or not. In Backdrop, this is set in the header block, and there can be different settings on different pages (e.g. a frontpage layout with the site name shown and a default layout (for all other pages) with it hidden).

I can't work out how to get this setting now...

**Comment by quicksketch** [comment]
There is no global location for this setting. Even within a layout, you could place the header block twice, so the settings might be different between the two blocks. If you want to check for a particular layout, it's a bit of a hassle but possible:

```php
$layout = layout_load('default');
$slogan_enabled = FALSE;
foreach ($layout->content as $block) {
  if ($block->module === 'system' && $block->delta === 'header') {
    $slogan_enabled = $block->settings['block_settings']['site_slogan'];
  }
}
```

**Comment by quicksketch** [comment]
Sorry this question was a long time ago and didn't get answered very promptly. I'm going to close it in case you figured it out in the mean time. Please reopen if you have further questions on this.

**Comment by klonos** [comment]
@BWPanda care to throw in an example snippet?

**Comment by BWPanda** [comment]
Sure, so in my themes I like to output the site name and slogan, even if they're hidden (I think Zen theme did this originally). In my theme's `template.php` I have this:

```php
/**
 * Implements hook_preprocess_header().
 *
 * Always output the site name and slogan, but hide them if they're toggled off
 * (the actual hiding happens in header.tpl.php).
 */
function [MYTHEME]_preprocess_header(&$variables) {
  // Get booleans for the name/slogan toggle status.
  $variables['hide_site_name'] = empty($variables['site_name']);
  $variables['hide_site_slogan'] = empty($variables['site_slogan']);

  // Populate the name/slogan variables again for output regardless.
  $variables['site_name'] = filter_xss(config_get('system.core', 'site_name'));
  $variables['site_slogan'] = filter_xss(config_get('system.core', 'site_slogan'));
}
```

So I first get the toggle status of each (whether or not it's been ticked to show in the Header Block), then I get the values of each from config. As an added bonus, I use `filter_xss()` to [allow HTML in the site name and slogan fields](https://github.com/backdrop/backdrop-issues/issues/2050) (e.g. for breaking the slogan over two lines, etc.).

Then, in an overridden `header.tpl.php` I have the following:

```php
<?php if ($site_name || $site_slogan): ?>
  <div class="name-and-slogan<?php if ($hide_site_name && $hide_site_slogan) print ' element-invisible'; ?>">
    <?php if ($site_name): ?>
      <div class="site-name<?php if ($hide_site_name) print ' element-invisible'; ?>">
        <a href="<?php print $front_page; ?>" title="<?php print t('Home'); ?>">
          <?php print $site_name; ?>
        </a>
      </div>
    <?php endif; ?>

    <?php if ($site_slogan): ?>
      <div class="site-slogan<?php if ($hide_site_slogan) print ' element-invisible'; ?>">
        <?php print $site_slogan; ?>
      </div>
    <?php endif; ?>
  </div>
<?php endif; ?>
```

For each of those, I add the (core) class `element-invisible` if they've been hidden from the block. That way, they're still output in the source but hidden visually.

Hope that all makes sense and maybe helps someone...
