### ISSUE TITLE
[UX] Columns in wrong order on date formats page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1956]
The first column should be the label, second should be machine name.
![screen shot 2016-06-03 at 3 20 50 pm](https://cloud.githubusercontent.com/assets/397895/15794306/b03eed78-299e-11e6-85e8-d927ba9c809a.png)

**Comment by klonos** [comment]
...all tests are green besides this (random?) error in php7 about config sync which is totally unrelated to the simple changes I made.

**Comment by quicksketch** [comment]
Great, thanks @klonos! Merged for 1.4.3.
