### ISSUE TITLE
Installer. Not informative error message

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1958]
When I tried to use installer I received message

> Failed to install one project.

But I had to go to resent log messages to see: 

> There was an error while installing Bootstrap lite. Permissions are not set up properly.

I thinks it will be better to display this message right next after Failed to install to help people understand what is wrong and what need to be done to fix it.

**Comment by Steve-A-Orr** [comment]
From the project home page, clicked the "Spin up on Pantheon" button and successfully installed site. Then, attempted to use the "Add to installation queue" module feature--got this problem immediately (having to look at log report for actual error). One would think that an automatic installation process would take care of permissions for a good "out-of-the-box" experience. 

Seems like this problem hasn't been resolved yet.

**Comment by Steve-A-Orr** [comment]
Found the source of my problem...it was a Pantheon issue. Gave detailed solution in other issue.  #2581  

Let's hope that Pantheon-specific documentation can be created to assist those who are unfamiliar with that hosting environment and are using it to spin up a quick introductory site.

**Comment by Dinornis** [comment]
Closing in favour for https://github.com/backdrop/backdrop-issues/issues/2581
Hope that's okay.
