### ISSUE TITLE
Installer. Failure to install module even if manager should be capable to install

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1959]
Right here:
https://github.com/backdrop/backdrop/blob/1.x/core/modules/installer/installer.manager.inc#L455

``` php
    // If the owner of the last directory we extracted is the same as the
    // owner of our configuration directory where we're trying to install the
    // code, there's no need to prompt for FTP/SSH credentials. Instead, we
    // instantiate a FileTransferLocal and invoke installer_authorize_run_update()
    // directly.
    if (fileowner($project_real_location) == fileowner(conf_path())) {
....
```

and here:
https://github.com/backdrop/backdrop/blob/1.x/core/modules/installer/installer.manager.inc#L897

``` php
 if (fileowner($project_real_location) == fileowner(conf_path())) {
    module_load_include('inc', 'installer', 'installer.authorize');
    $filetransfer = new FileTransferLocal(BACKDROP_ROOT);
...
```

We are checking if config directory and downloaded project file has the same owner.

It could be different but still we can have access to change config via web request and install module due a GROUP permissions.

I am using next approach for permissions:
- all backdrop files include config has user:group  644 (755 for directories) 
- only files directory (include config) (and for installer modules and themes) has permissions 775 
- I run web server with anotheruser:group permissions. In this case, if there is a php execution vulnerability, there is no chance to change core files for hacker. Yes he can do changes to config (sadly) and with installer to contrib modules, but not to the core. It helps to prevent a lot of bad activity by hacker even if there is a  php execution vulnerability.

I install backdrop via SSH with scripts/install.sh script. SO config directory has user:group after installation.

But if I use installer in this case - it will fail with 

> Permissions are not set up properly

I am not sure if we need to fix that. I understand that it's special case, when config directory has different owner . I just want to notice that group permissions are allowing to install module, but installer does not count it.

**Comment by daggerhart** [comment]
Bump.

Just had a long debug-discussion on gitter about this exact issue.

@robertgarrigos was working in ubuntu where the fileowner for tmp directory didn't match the backdrop fileowner, but his filegroup matched.

I was looking at osx where the fileowners matched, but the filegroup don't.

Perhaps we check for both things with an or statement to allow for the most compatibility?

```
  if (fileowner($project_realpath) == fileowner(conf_path()) || filegroup($project_realpath) == filegroup(conf_path())) {
```

**Comment by robertgarrigos** [comment]
I was trying this PR (https://github.com/backdrop/backdrop/pull/1891) with no luck.

I was checking this with my install and it doesn't work either. I use /tmp as temp directory (ubuntu 16.04, default install). It is owned by root:root. Backdrop doesn't complain when configuring file system, but it does when installing modules thru UI. So I changed file filegroup of /tmp to www-data, the same filegroup I have for all my files in my backdrop install (to mathc what this PR has changed) and doesn't work either. Anyway: does this function have anything to do with installing thru UI?

**Comment by robertgarrigos** [comment]
Sorry, I was wrong. The PR actually resolves my problem. I got confused with the line numbers. This issue mention where changes could be: L455 and L897. The PR only fixes L897 but I tried the fix on L455, which didn't fix it. Apply the changed on L897 does fix it.

**Comment by daggerhart** [comment]
Awesome, glad it worked out, I was a little concerned there for a moment. Marked as "tested by the community"... not positive if that is correct usage of the tag.. @klonos ?

**Comment by quicksketch** [comment]
Thanks @daggerhart for the PR! Merged https://github.com/backdrop/backdrop/pull/1891 into 1.x and 1.7.x.

I think we could expand this to be a bit smarter, because it's not guaranteed that the "group" of a user will have write access. But it's also true that sometimes even the owner itself might not have write access (though that is uncommon). In most situations, both the user and group can write, and even if it can't, you get an error after it attempts to do the installation.

But this change is an improvement and increases the number of situations where the Installer will work.
