### ISSUE TITLE
run_tests.sh --directory option. Contrib tests

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#1967]
To run tests for contrib module we will need to specify a module directory.

I added option --directory to scan for *.test files and run tests for found classes.

I use simpletest_test_get_all() to filter classes from *.test files to run only available test classes.

PR https://github.com/backdrop/backdrop/pull/1443

**Comment by quicksketch** [comment]
This was actually merged already and included in the 1.4.4 release. Looks like I forgot to close it.

Thanks again @Gormartsen! PR https://github.com/backdrop/backdrop/pull/1443 merged into 1.x and 1.4.x.
