### ISSUE TITLE
Expanded fieldsets: add more space between fieldset-legend and fieldset-wrapper

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1971]
I've noticed this in the views dialogs (while filing #1968), but we could be having the same issue elsewhere as well:

![backdrop-fieldset_wrapper_too_close_to-fieldset_legent](https://cloud.githubusercontent.com/assets/2423362/16007848/10f2d942-31b8-11e6-9392-89d5d66bc3a0.gif)

**Comment by Dinornis** [comment]
I don't know which of the CSS files would be the correct one to edit without breaking anything, but adding `padding-top:1em;` to `html.js fieldset.collapsible div.fieldset-wrapper` in `admin_bar.css` does the trick.

**Comment by serundeputy** [comment]
Thanks @klonos! this was fixed in https://github.com/backdrop/backdrop-issues/issues/2467
