### ISSUE TITLE
Editor disappears when AJAX runs on node form

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#1975]
Original issue:
- enable book module
- create a book
- when creating content scroll to the "Book outline" vertical tab, select a book from the select list
- when the AJAX runs, CKEditor disappears leaving raw HTML

But noticed this is a general problem with AJAX on the node form; same happens if you click "Add another item" for an unlimited field.

Someone **really** needs to get on with #1087.

**Comment by Graham-72** [comment]
gifad (https://www.drupal.org/u/gifad) has kindly sent me a message to say that there is a bug fix for this at https://www.drupal.org/node/2691101

He had previously reported this issue at https://github.com/backdrop/backdrop-issues/issues/1564

**Comment by docwilmot** [comment]
Thanks
