### ISSUE TITLE
The list of URL redirects has checkboxes, but no bulk operations (only search/filtering).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1978]
`/admin/config/search/redirect`

I think we should add bulk delete as a bulk operation. Perhaps also bulk update.

**Comment by klonos** [comment]
[Bulk updating Pathauto aliases - Using Views Bulk Operations](https://www.drupal.org/node/1326928)

**Comment by Al-Rozhkov** [comment]
![url-redirects](https://cloud.githubusercontent.com/assets/16973264/25533085/792197a0-2c40-11e7-81f0-10cd41dc0a3d.jpg)

Looks like it's done. Should we close this one?

**Comment by docwilmot** [comment]
done
