### ISSUE TITLE
Redirect 301 for view page

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1983]
For any page we can do redirect in the menu tab (Add URL redirect to this node).

But how to do this for views?
I do not see the same option in the Configure view.

Thank you!

**Comment by klonos** [comment]
For that (and any other path that does not provide a redirect option), you can "manually" create a redirect under Configuration > Search and metadata > URL redirects > Add redirect (`/admin/config/search/redirect/add`)

**Comment by bd0bd** [comment]
Thank you very much!
This is what I need :smile:
