### ISSUE TITLE
SOS! Database from 50 MB raised up to 170 MB

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#1984]
Database from 50 MB raised up to 170 MB after I have upgraded from BD 1.3 to BD 1.4.2.

What I can delete in the Database?

Thank you!

**Comment by bd0bd** [comment]
I have deleted **tempstore** - it it ok?
It was about 90 MB.

**Comment by BWPanda** [comment]
Closing old issue. Reopen if still relevant.
