### ISSUE TITLE
[UX] Rename instances of "database update(s)" to "system update(s)"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1986]
We do CMI config file updates too, which are not db updates. Proper would be "Database and config updates", but too verbose. I think "system" encompasses both db and config, so I think that we should go with that unless there are better suggestions.

**Comment by klonos** [comment]
I can try a PR once we decide on the name.

**Comment by klonos** [comment]
This was recently brought up by @laryn in Zulip, during the preparation of the 1.22.0 release: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Release.20Day/near/282444669

> Also, is this term "database updates" potentially a misnomer at this point?
> e.g. an update hook that only affects CMI

...

> I found an update hook here: https://github.com/backdrop/backdrop-issues/issues/336
> Which prompted the question above since it's a CMI update (not a database update) but will still trigger the red warning, right?

**Comment by indigoxela** [comment]
I'm supporting this! And if it were only that I don't have to :roll_eyes: on every Backdrop update with CMI-only changes.

I'm not sure if I can help much with wording, though. ("System updates" seems a little weird to me.)

**Comment by klonos** [comment]
Here's an initial PR for this: https://github.com/backdrop/backdrop/pull/4203

I have changed things to "system updates" for now, but happy to change it to anything better we may come up with.

I have left 3 instances of "database update" in `cor/modules/system/system.api.php`, since these were legitimately referring specifically to database schema updates.

**Comment by laryn** [comment]
I can't think of anything better than "system updates" at the moment (and "system updates" is better than "database updates").

**Comment by argiepiano** [comment]
The issue with System Updates is that we already have a page called System Updates that takes care of downloading core and contrib when there are updates. This may create confusion.

<img width="1249" alt="Screen Shot 2022-12-13 at 8 05 34 AM" src="https://user-images.githubusercontent.com/9938978/207369446-06e128bc-d427-46fd-a5a5-d8c5330e8e27.png">

**Comment by laryn** [comment]
Good point about that existing page!

I'd still like to try to clarify the name if possible. Would "internal updates" work?

**Comment by olafgrabienski** [comment]
I agree that System updates might be confusing. Even if it is a bit lengthy, I'd prefer something like "Database / config updates", depending on the context, e.g.:

- Database or configuration update
- Database and configuration updates

**Comment by argiepiano** [comment]
How about something like "Update tasks"?  So: 
- "Run update tasks" on my second screenshot above 
- And then use (in this screenshot)
  - "Backdrop update tasks"
  - "Use this utility to update your database and configurations whenever you install a new version of Backdrop CMS or one of the site's modules."
  - 
<img width="581" alt="Screen Shot 2022-12-13 at 8 17 51 AM" src="https://user-images.githubusercontent.com/9938978/207372345-74f276b8-8b49-46e1-af03-f302847d306b.png">

**Comment by indigoxela** [comment]
> How about something like "Update tasks"?

Hey, this could just be the solution. :+1: I'd vote for "Update tasks".

**Comment by laryn** [comment]
I like that too.

**Comment by olafgrabienski** [comment]
Indeed, "Update tasks" sounds good!

> Use this utility to update your database and configurations ...

Maybe better "your database and your configuration files"? (IIRC, database updates can also be related to configuration. If that's true, config *files* would be a more clear differentation.)

**Comment by kiamlaluno** [comment]
I would rather call them *updates*, if *system updates* can create confusion with the existing page.

**Comment by bugfolder** [comment]
"Database/config updates" nicely and concisely describes what's happening. True that many admins won't know or care about the distinction, but for some it might even be a bit educational.

**Comment by argiepiano** [comment]
> "Database/config updates" 

I'm fine with that too.

**Comment by yorkshire-pudding** [comment]
I'm fine with any suggestion here. I have a slight preference for "Database/config updates"

**Comment by jenlampton** [comment]
> So, after doing "System Updates" (downloaded the updates), we will be prompt to "Run system updates" again?

I think using the same terminology for these things makes a lot of sense, actually. Using the installer module we install the module (download the code) before we install the module (turn it on and run any datayabse+config changes). 

> Database/config updates

If we do decide to go with this alternative, I think it needs to be full and complete words, like  `Database and configuration updates`. 

> "System updates" are the core, module, theme, and layout template updates
> "Database/config updates" are exactly what their name implies (as self-explanatory a it can get)

These things are step 1 and step 2 of the same process. If "Database/config updates" won't ever be done without also doing "System updates" why don't we just call them by the same name?  

It might be better to refer to each step of the process as follows:
- "System updates"
  - Code+file updates
  - Database/config updates

I've done a code review and marked this issue RTBC (it currently uses "System updates"), but if we need more time to discuss terminology, we should remove either that or "works for me" so it doesn't get merged :)

**Comment by quicksketch** [comment]
I'm moving this back to review as it seems like several people expressed concerns about using the term "System Updates" (which is what https://github.com/backdrop/backdrop/pull/4203 uses).

I think "System Updates" is better than "Database Updates", but the above feedback is valid. I'm leaning towards merging this as-is. If someone else agrees that this is fine as-is; please move this back to RTBC then I'll merge it.

**Comment by klonos** [comment]
With #5630 landing in 1.28.1, we've now changed "database updates" to "site updates"! 🎉 ...I'll double-check if there's anything useful in the comments above. or in the PR that we need to consider, and will then close this.

**Comment by klonos** [comment]
I've filed #6644 as a follow-up. Closing.
