### ISSUE TITLE
printmpdf is in github, but not in the Backdrop Module list - Why?

### ISSUE THREAD

**Issue by vtad** [backdrop/backdrop-issues#1988]
How are modules from github included/transfered in the project module list?

**Comment by Gormartsen** [comment]
hi @vtad !

We had issue recently with release processing.

Please trigger new release and module will be properly packaged and released on backdropcms.org

After it get released, you will be able to find it via installer.

**Comment by klonos** [comment]
@Gormartsen I see  that @vtad made a new release, but it did not solve the issue. In fact, we seem to still be having the issue where there is no release.zip file created, only source code .zip & .tar.gz (https://github.com/backdrop-ops/backdropcms.org/issues/264) ...is the temporary workaround that @quicksketch drafted live in production?

**Comment by Gormartsen** [comment]
@klonos It should be. I remember he wrote that he put it in a place and it was working.

Looks like there is still issue with that.

@quicksketch when you have a chance, please check it again.

I am available for you to test and put new changes for project_github when you can.

Right now I think we need to find all releases that did not get packed and listed properly and force them to repack.

I am around in gitter just in case.

@vtad I am sorry that you have to experience this issue. It is recent changes with github that broke our project release processing and looks like a temporary solution does not work.
I already made changes to project module, they should be live anytime soon to recovery project release process.

**Comment by quicksketch** [comment]
I'm working on fixing our packager again this week. We had a temporary fix in place but it doesn't appear to work consistently. I'll repush all projects that had failed packages once the fix is up.

**Comment by klonos** [comment]
...just to make sure that this remains on your radar.

**Comment by jenlampton** [comment]
I'm pretty sure this is fixed, we haven't had an issue with the packager for a while. Closing (but please re-open if there is still an issue!)
