### ISSUE TITLE
Regions that are side-by-side should have the same height, independently of contained blocks.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1990]
Not sure if this is a feature request or a bug report. It's been bothering me for a while, but never filed an issue for it till now. Here's what I mean:

![backdrop-layout-regions-different_heights](https://cloud.githubusercontent.com/assets/2423362/16432801/37bc8f50-3dca-11e6-82ae-3f4848cc76a2.png)

In my custom front-end themes in D7, I used to use https://www.drupal.org/project/equalheights ...especially when I wanted the main content to be of equal height as the sidebars.

Here's how things would look instead:

![backdrop-layout-regions-equal_heights](https://cloud.githubusercontent.com/assets/2423362/16432878/aaa16694-3dca-11e6-85e4-96126df0899d.png)

I personally feel that it's much better visually.

---
PR by @BWPanda (using CSS `flex`): https://github.com/backdrop/backdrop/pull/2763

**Comment by klonos** [comment]
...a couple of things to note here:

- this is not only for the Layout UI. It should be applied to the front-end theme too if possible or have an option for it in the region settings perhaps.

- the heights should be made equal as long as the regions are side-by-side (as the issue title suggests). When we hit the breakpoint where the sidebars wrap below the main content and are stacked on top of each other, equal heights do not make sense any more.

**Comment by BWPanda** [comment]
I kind of like how the Layouts UI looks with equal-height columns, but I'm wondering about putting the JS in core just for this...

As for the front-end, I think this should be up to individual layouts/themes to implement themselves if they want it.

**Comment by BWPanda** [comment]
Marking as FR as I don't see that this is a bug.

**Comment by indigoxela** [comment]
I'd like to suggest a lightweight css-only alternative for setting equal height: flex

Details:
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by oadaeh** [comment]
Yeah, it seems to me this could be a CSS only fix, but I'm not the person to ask how to. :)

**Comment by BWPanda** [comment]
I like @indigoxela's suggestion about using CSS Flex. We're actually already using it in the Layouts UI:

![layours-flex](https://user-images.githubusercontent.com/2385329/60384772-c43ce400-9a8a-11e9-8427-74ed45e7339a.png)

`.row` has `display: flex;` which makes the two `.l-halves-region`'s equal heights. Unfortunately `.layout-editor-region` is where the white background is set, and children don't inherit the height of their parents. So if we can re-work that a bit then that's a simple fix that doesn't require additional JS libraries and uses what we already have.

**Comment by BWPanda** [comment]
Made a [PR](https://github.com/backdrop/backdrop/pull/2763) that makes regions/columns in the Layouts UI equal heights.

**Comment by klonos** [comment]
Thanks @BWPanda 👍 ...I have left a comment in the PR to fix a coding standards issue with an inline comment. Once that's fixed, this is RTBC 😉 

...this does not change any specific user-facing theme; only the CSS of the Layout module, so I see it as a UX task - not a new feature. Adding milestone candidate for next bug release.

**Comment by BWPanda** [comment]
@klonos PR updated, thanks!

**Comment by klonos** [comment]
Thanks @BWPanda 👍 RTBC.

**Comment by klonos** [comment]
...for clarity, the UX issue here is that if for example you have a really long sidebar region with many blocks, and you want to move the very last block to an adjacent region (which does not have the same height), then the drop zone for that region may be outside the browser viewport. In such cases, you need to scroll and drag at the same time, which is tedious.

With this fix, the adjacent region is right next to the block to be dragged and dropped, so easier -> UX+.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2763 into 1.x and 1.13.x.

This is a great and simple fix nice job @BWPanda and @indigoxela! And thanks @klonos for bringing up this issue and providing all the valuable feedback!
