### ISSUE TITLE
Consider adding a JS library in core to use as a generic solution when various elements need to have equal height.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1991]
There are at least two places where we could use something like that currently:
- [ ] Layouts UI: layout template labels that are too long (contrib layout packages mainly) and cause the template tiles to have different heights in the layouts settings page (`/admin/structure/layouts/settings`), the individual layout settings pages (`/admin/structure/layouts/manage/%/settings`) and the layout add page (`/admin/structure/layouts/add`) (#1972).
- [ ] Layout UI: region divs in the Manage blocks page of each layout (`/admin/structure/layouts/manage/%`) have different heights depending on the amount of blocks placed in them (#1990).

Candidate libraries:

https://github.com/liabru/jquery-match-height
http://www.cssnewbie.com/equalheights-jquery-plugin
???

**Comment by indigoxela** [comment]
Things like that get accomplished with pure CSS, using either `display: flex` or `display: grid`. Nowadays there's no need for a fully blown js library anymore. I think, it's time to close this outdated issue.
