### ISSUE TITLE
Allow site builders to disable the /node path

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#2001]
As discussed in our 30 June 2016 Developer meeting.  Often when building a site the homepage becomes something other than /node, but for many sites that path is still accessible via the path `/node` and is often neglected and unformatted.

Currently the only way to remove that path is with `hook_menu_alter` which means you would have to write code.
- One option would be to be to add logic to the form `admin/config/system/site-information` and if the user is setting that to something other than `/node` implement `hook_menu_alter` to shut off the `/node` path.
- Otherwise we could provide a check box on that form to allow the `/node` path or not.

I think I prefer the first method, but would like to see what others have to say about it?  As the first method does not tell the user that they are disabling the `/node` page when they change the default homepage.

What do people think?

thanks,
~Geoff

**Comment by docwilmot** [comment]
Can anyone think of a reason why you'd want to keep /node?

**Comment by klonos** [comment]
Nope, no reason I can think off of the top of my head. 1st option seems more reasonable to me.

An alternative I can think of is redirect `/node` to front page (instead of shutting off completely via `hook_menu_alter`), but then we need to think what will happen if people disable the Redirect module.

Also, what will happen if one sets something else to that path (like a view page for example)?

**Comment by Graham-72** [comment]
I prefer to have a specific node as the home page and so /node seems to give 'No front page content has been created yet.' I would rather it redirected to my chosen home page.

**Comment by serundeputy** [comment]
`PR` https://github.com/backdrop/backdrop/issues/1458 
test site: Website: http://1458.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: 782zNioN

**Comment by serundeputy** [comment]
I think we need a `cache_clear_all()` in `system.admin.inc` in `system_site_information_settings_submit` otherwise manual cache clear is required after setting new front page and visiting `/node`

**Comment by serundeputy** [comment]
Addressed @klonos code review suggestions.

Added `backdrop_flush_all_caches()` to `system_site_information_settings_submit` to allow the front page redirect to take place.

Updated `system.test` to be aware of the redirect.

Added `NodeFrontPageCallback` to `node.test` to test the toggling of the callback for the `/node` path depending on whether a custom frontpage is set on `admin/config/system/site-information` or not.

**Comment by klonos** [comment]
Works as expected when replacing the default home page with a custom one, but if that node is deleted, then it 404s. Not a problem of this PR here, but trying to kick the tires as much as I can.

**Comment by quicksketch** [comment]
> Works as expected when replacing the default home page with a custom one, but if that node is deleted, then it 404s. Not a problem of this PR here, but trying to kick the tires as much as I can.

Yeah, separate issue, this would happen with any path that is deleted. I'm not sure reverting back to `/node` would be a good solution in such a case anyway, though it'd probably be better than a 404 on the homepage... not sure. Separate issue.

I left a bunch of feedback in the PR https://github.com/backdrop/backdrop/pull/1458.

I love this approach, so simple to just only enable this functionality if `/node` is the front page in the first place, and will work great with future-proofing for the new homepage layout.

**Comment by jenlampton** [comment]
Related: https://github.com/backdrop/backdrop-issues/issues/2114

**Comment by serundeputy** [comment]
I've refactored the solution into the current `node_page_default` callback and addressed the feedback on the `PR`.  Rebased and pushed back up.

I think we are in good shape :) .

**Comment by quicksketch** [comment]
Excellent! I've merged https://github.com/backdrop/backdrop/pull/1458 for 1.5.0.

Note that https://github.com/backdrop/backdrop-issues/issues/1042 (front page layout) will definitely need updating as these new tests will likely fail with that layout in place.
