### ISSUE TITLE
Update copyright date

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2009]
Seems like quite a minor thing to open an issue about, but I happened to notice the Copyright date in the README only went through 2014. Gor suggested opening an issue to go with the PR:
- https://github.com/backdrop/backdrop/pull/1457#issuecomment-230660974
- https://github.com/backdrop/backdrop/pull/1457/commits/97bc68dc501174a13977697de659867bc9525b37

**Comment by serundeputy** [comment]
Thanks @laryn good find!

This is merged into `1.4.x` and `1.x` and will ship with `1.4.4`!

Great work!
