### ISSUE TITLE
Views field templates not working?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2011]
Here's what I did:
- chose a core view - Admin content
- created a template `views-view-field--node-admin-content--title.tpl.php` and put it into my theme folder. the content of the field templates are all the same thing: `<?php print $output; ?>`
- 'rescan template files' in views UI (got a AJAX error but refresh page worked)
- views says this template is now in use
- but no changes in that file affect the display of the view

Also (how this started and was discovered):
- added a views template override in a `hook_theme` in module
- views says this template is now in use
- but viewing the display gives an error "undefined variable ... $output..."
- also got a consistent error with any views template with this method, not just the field templates, but dont recall the error, and away from Backdrop now.

**Comment by serundeputy** [comment]
This seems to be working for me.

![screen shot 2016-07-07 at 7 25 11 pm](https://cloud.githubusercontent.com/assets/6763671/16673041/a3699234-4478-11e6-97ae-65d3683d0776.png)

silly question 
> created a template views-view-field--node-admin-content--title.tpl.php and put it into my theme folder. the content of the field templates are all the same thing: <?php print $output; ?>

Did you put this in the `seven` theme templates folder or `bartik`?  It would need to be in `seven` for the path `admin/content`

~Geoff

**Comment by docwilmot** [comment]
- yes, i was using bartik, so fail
- and i was using `original hook` in `hook_theme` instead of `base hook`.
