### ISSUE TITLE
Remove the trailing dot from the "Browse available tokens." link.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2016]
This is a really minor thing, but has always bothered me. We do not have periods in other action-style links (like the "+Add xyz" links or the dropbutton actions) or button labels. If anything, this should be an ellipsis (because it opens a dialog).

I say lets just remove it. PR upcoming...

**Comment by quicksketch** [comment]
Sure, possibly making it a button might not be a bad idea in the future. But for our current situations, you're right that removing it makes the most sense.

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop/backdrop/pull/1462 into 1.x and 1.4.x.
