### ISSUE TITLE
[UX] Use #states to show/hide the "Files displayed by default" option for fields of type file.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2023]
Before:

![backdrop-issue2023](https://cloud.githubusercontent.com/assets/2423362/16925820/557d7528-4d69-11e6-9988-c8362dcae17a.gif)

After:

![backdrop-issue2023-pr1465](https://cloud.githubusercontent.com/assets/2423362/16925733/ec34693c-4d68-11e6-97de-d0a650cbf54f.gif)

**Comment by quicksketch** [comment]
> This setting only has an effect if the display option is enabled.

What a great candidate for `#states`.

Merged https://github.com/backdrop/backdrop/pull/1465 into 1.x and 1.4.x. Thanks @klonos!
