### ISSUE TITLE
Default path pattern incorrectly updated when new node types are created.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2026]
When creating a new content type, the field for `Default URL pattern` should contain the value provided for 'Default URL pattern' on the path patterns page (or none, if left empty).  In config, this is saved as `node_pattern`.

However, when the page for a new content type is saved, the value entered needs to be saved as `node_TYPE_pattern`. Instead, a new value is being added for `node__pattern`, since the type was not known when the form was generated.

**Comment by serundeputy** [comment]
Is this the same as https://github.com/backdrop/backdrop-issues/issues/2022 ?

**Comment by jenlampton** [comment]
yes, looks like it.
