### ISSUE TITLE
Different pages for logined and unlogined visitors

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2030]
Hi!

Please, how to make it like GitHub website?

If we are **not** logined then we see this page:
![a](https://cloud.githubusercontent.com/assets/13515302/17163389/81b6ff6a-53c7-11e6-8e8d-eaf765e3a1e7.png)

And if we **are** logined then we see this one at the same URL — https://github.com:
![b](https://cloud.githubusercontent.com/assets/13515302/17163405/a12c2776-53c7-11e6-829c-134e79e92a22.png)

Thank you!

**Comment by BWPanda** [comment]
Going to close this old issue, but for the benefit of anyone who comes across this, you may be able to create two different layouts with the same path (untested) but with different visibility conditions: role anonymous and role authenticated...

**Comment by stpaultim** [comment]
@BWPanda - That is my best guess as well. I don't know if it's two different layouts (can two different layouts have the same path?), but even one layout but all of content is conditional on role. You could have two different versions of a single layout that are completely different based upon role (I think). 

Or you could create a custom template with conditions based upon role.

**Comment by klonos** [comment]
Yes, I would either go with single layout, with role-based visibility conditions for different blocks; or separate layouts, with role-based visibility conditions 👍
