### ISSUE TITLE
Quick registration

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2031]
Hi!

I need quick registration — a person would press the button REGISTER and he/she is registered and loged in.
User name (or digital ID) and password are automatically created and displayed to the user (your ID is **123456**; your password is **ghhgfh56hdsG**_).

If this is too difficult to do then how to delete the two fields — E-mail address and Confirm new password? The two fields are enough for registration in my case.

![default](https://cloud.githubusercontent.com/assets/13515302/17271877/c0708ba6-5690-11e6-87af-8d5f6cef1740.png)

Thank you very much for your help! :)

**Comment by findlabnet** [comment]
How do you filter real humans from tons of robots registration in this case?

**Comment by bd0bd** [comment]
I am not sure.
May be simple captcha: 3+123=?
But I would not like to use any captcha — this is additional headache for people.

Is it possible to allow only one registration per a time? For example second registration from the same computer might be possible only after 24 hours. Using cookies.

**Comment by bd0bd** [comment]
No way to remove E-mail address and Confirm new password fields?

**Comment by klonos** [comment]
Looks like what you need is something like a combination of https://www.drupal.org/project/optional_mail and https://www.drupal.org/sandbox/maciej.zgadzaj/2081979. None of them is ported yet and the second one is not even a full project in d.org - just a sandbox. Hmm.

**Comment by klonos** [comment]
...[Remove Confirm Password on Registration (solved) | Drupal.org](https://www.drupal.org/node/795542) might be of help too.

**Comment by bd0bd** [comment]
@klonos, thank you!
Yes, I do know about Optional mail on register and I have saw this post  before
https://www.drupal.org/node/795542
But I do not understand how to use the code and where to place it in.

**Comment by bd0bd** [comment]
May be you will advice where to place it in

function mymodule_form_user_register_alter(&$form, &$form_state) {
  $form['pass']['#type'] = 'password';
  $form['pass']['#title'] = 'Password';
}

**Comment by klonos** [comment]
You need to create your own module. Lets say for example you call your module "my_simple_login"...

1. You need to create a `my_simple_login` folder under `/modules`.
2. Inside that folder, you need to create a my_simple_login.info file with the following contents:

```
name = My Simple Login
description = "Allow users to log in with lest steps."
backdrop = 1.x
type = module
```

3. In the same folder, create a my_simple_login.module file with these contents:

```
function my_simple_login_form_user_register_alter(&$form, &$form_state) {
$form['pass']['#type'] = 'password';
$form['pass']['#title'] = 'Password';
}
```

**IMPORTANT NOTE**: if you decide to call your module something else, that's fine, but you need to rename the folder and the .info and .module files to have the same name.

Once finished, go to your admin interface and enable this module like any other module. Pray that this works because I have not tested the code.

**Comment by bd0bd** [comment]
@klonos, thank you very much for enough clear explanations!

I have created the module but it does not work after it was activated in /admin/modules/list.

**quick_registration.module.php**

	<?php

	function quick_registration_form_user_register_alter(&$form, &$form_state) {
	  $form['pass']['#type'] = 'password';
	  $form['pass']['#title'] = 'Password';
	}

**quick_registration.info**

	name = Quick Registration
	description = "Allow people to create an account without e-mail and password confirmation fields."
	backdrop = 1.x
	type = module

**Comment by klonos** [comment]
> ...but it does not work after it was activated...

I told you I did not test the code to see if it works or not. I posted my instructions because I merely wanted to teach you the basics of creating modules (what folders and files are required and where you need to place them). Now you know what to do when someone says "put this code in a custom module". Unfortunately, it does not mean that this code works all the time and you will have to do some research and work on your own in order to figure out how to make the code work.

Having said all that, I have a remark: the module file needs to have a `.module` extension - not `.module.php`.

**Comment by bd0bd** [comment]
> Now you know what to do

Yes! Thank you very much for this!

**Comment by bd0bd** [comment]
This removes password confirmation fiels!:

	<?php

	function quick_registration_form_user_register_form_alter(&$form, &$form_state, $form_id) {
	  $form['account']['pass']['#type'] = 'password';
	  $form['account']['pass']['#title'] = t('Password');
	}

**Comment by klonos** [comment]
You can try this:

```php
<?php

function quick_registration_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form['account']['pass']['#type'] = 'password';
  $form['account']['pass']['#title'] = t('Password');
  $form['account']['mail']['#required'] = FALSE;
  $form['account']['mail']['#disabled'] = TRUE;
  $form['account']['mail']['#prefix'] = '<div style="display: none">';
  $form['account']['mail']['#suffix'] = '</div>';
}
```

**Comment by bd0bd** [comment]
@klonos, you are brilliant (almost). Thank you!
`<div style="display: none">` — this does not remove the field. Is it too difficult to remove it?

But after rgistration this warning is displayed in red:
Unable to send e-mail. Contact the site administrator if the problem persists.

**Comment by bd0bd** [comment]
This code is wrong:

    $form['account']['pass']['#type'] = 'password';
    $form['account']['pass']['#title'] = t('Password');

If we use this code in multi-language website then we get into deep trouble with translating the label of the password field.

This code remove both fields (New password and Confirm new password) and put the Password field of the "Log in" form in this place. In this case both password fields labels (in Sign up and Log in forms) will be similar. But they should be different:

**Create a password** (Sign up form) and **Password** (Log in form).

Please, what a to do? :smile_cat:

**Comment by laryn** [comment]
@bd0bd I know this is years old, but you could do this with `webform` and `webform_registration` at this point, I believe.

**Comment by BWPanda** [comment]
Closing old issues. This one has some good suggestions though.
