### ISSUE TITLE
INSTALL MODULES — Already enabled, but it was removed

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2034]
I was going to update Remove Generator module.

I have manually deleted it via FTP.

When I try to install it via /admin/modules/install I see this "Already enabled".

I have of cause flushed all cashes.

![default](https://cloud.githubusercontent.com/assets/13515302/17283277/40e1689c-57b7-11e6-8827-b47cbef43b10.png)

**Comment by serundeputy** [comment]
Hello @bd0bd 

When you install a module it makes entries in the database, at least one in the `system` table, if the `status` in the `system` table is one then Backdrop thinks the module is installed regardless of whether the code is present or not.

If you want to uninstall a module you need to leave the code in place:

  * visit: `/admin/modules/uninstall` and uninstall your module
  * that will run the modules `hook_uninstall` which will remove database entries including the `system` table

In your case put the code for the module back via FTP and then run the uninstall and then you should be able to install the latest and greatest via project browser in your screenshot.

Hope that helps.
~Geoff

**Comment by bd0bd** [comment]
Thank you!
I have no problems with this issue.
I am just reporting about this :smile:
Other people could have the same and get confused.

**Comment by quicksketch** [comment]
Thanks @bd0bd! @serundeputy is correct in that this is intended behavior. The module is still "installed" and "enabled" as far as the data being present in configuration and the database. Just removing the module without uninstalling will cause a lot of other problems as well (including a performance issue and preventing config export/import from working).

**Comment by Graham-72** [comment]
When a library is missing we often get a definite warning. Would it be possible to have something similar i.e. a warning that the module, though registered, is missing?

**Comment by quicksketch** [comment]
> Would it be possible to have something similar i.e. a warning that the module, though registered, is missing?

That's actually one of the recent changes in the latest Drupal release (7.50), we'll probably end up backporting the same fix from the meta issue at #2013.

**Comment by klonos** [comment]
>>Would it be possible to have something similar i.e. a warning that the module, though registered, is missing?

> That's actually one of the recent changes in the latest Drupal release (7.50), we'll probably end up backporting the same fix from the meta issue at #2013.

👍
