### ISSUE TITLE
PM - Private Messaging

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2035]
Do we have module for private messaging between users?

**Comment by findlabnet** [comment]
You are tried core module "Contact"?
> Enables the use of both personal and site-wide contact forms.

**Comment by bd0bd** [comment]
No. I will try.
But I do not think this is something like https://www.drupal.org/project/privatemsg

**Comment by bd0bd** [comment]
Contact module is not for this.

**Comment by Scoppettuolo** [comment]
That module is great ( https://www.drupal.org/project/privatemsg ).
I want this too.

**Comment by klonos** [comment]
Closing this one as this issue queue is for Backdrop core. You should file a request to port this module in https://github.com/backdrop-ops/contrib/issues
