### ISSUE TITLE
[UX] "Save and add fields" should be blue when creating a new content type

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2037]
Most of the time, when creating a content type, people will want to add fields. We should make the save and add fields button the blue one, and "Save" gray.

**Comment by Al-Rozhkov** [comment]
Looks like it is done already. Should we close this one?

![save-and-add-fields](https://cloud.githubusercontent.com/assets/16973264/24560413/c8ba20c8-1653-11e7-90e9-aa0152670924.jpg)

**Comment by jenlampton** [comment]
yes, thank you @Al-Rozhkov!
