### ISSUE TITLE
[UX] Change the submit button for blocks to "Save block".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2039]
It currently says "Save configuration" and although that is technically correct, I don't think that it provides any value to the end-user. I would say that it is rather confusing.

**Comment by jenlampton** [comment]
I love it :)

**Comment by klonos** [comment]
I was under the impression that we were differentiating between custom blocks and non-custom ones, but it turns out that we use "Add block" for all of them (I thought that we had two separate "Add block" and "Add custom block" submit button labels). Turns out it's the same code handling all types of blocks, so the UX issue was not only with custom blocks but with all blocks.

PR upcoming...

**Comment by klonos** [comment]
...minor change, so I think perhaps get it in in 1.4.4??

**Comment by quicksketch** [comment]
This sounds good to me. Tests still have a few failures. I'm going to kick this to the next bugfix release unless we can get an updated PR before I finish getting through the 1.4.4 issues.

**Comment by klonos** [comment]
...hold on! Just updated the PR. Give it a few minutes for the tests to complete 😄

**Comment by klonos** [comment]
...php7 is green 😄

**Comment by klonos** [comment]
...all green!

**Comment by quicksketch** [comment]
Well done! Totally rocking these code tasks! :sunglasses:

Merged in https://github.com/backdrop/backdrop/pull/1480 for 1.x and 1.4.x. This might be the last one in 1.4.4. Thanks!
