### ISSUE TITLE
Set default for "Error messages to display" setting to NONE

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#2040]
By default in new install is set to development mode: "All messages" (see admin/config/development/logging), but need to be changed to "None".
Fix should be done in core/modules/system/config/system.core.json line 17:
for now there "error_level": "all"

**Comment by jenlampton** [comment]
Thanks for your suggestion @findlabnet. Could you please provide a solid argument as to why this default needs to be changed? Is it a security issue, an annoyance, or ?

**Comment by findlabnet** [comment]
An example of "solid argument": 
attempt to crack login form by incorrect data cause print to screen something like 
`Warning: mb_strlen() expects parameter 1 to be string, array given in backdrop_strlen() (line 490 of /var/www/domain.com/core/includes/unicode.inc)`
and then 
`PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' '0ET9Jxx6'' at line 1: SELECT * FROM {users} WHERE mail = :mail_0, :mail_1; Array ( [:mail_0] => tNjzTORE [:mail_1] => 0ET9Jxx6 ) in user_login_name_validate() (line 1566 of /var/www/domain.com/core/modules/user/user.module)`.
In both messages filesystem path is present (can include username) - kind of security issue. Developers (IMHO) should get such messages via php.ini in development environment. 
In D7 this option is disabled by default.
Moreover, I think in case if error output is enabled, we need to place information about it in "Status report".

**Comment by jenlampton** [comment]
Thanks!  I think it's a good suggestion.

**Comment by findlabnet** [comment]
Filled [PR#1517](https://github.com/backdrop/backdrop/pull/1517).

**Comment by jenlampton** [comment]
@findlabnet thanks so much for the PR, I think it's really close!  I added a few notes on the PR that need to be addressed, but I think we could get this in to 1.5 :)

**Comment by quicksketch** [comment]
> In D7 this option is disabled by default.

In D7 error logging is set to display all messages in [`error_displayable()`](https://api.drupal.org/api/drupal/includes%21errors.inc/function/error_displayable/7.x):

```
variable_get('error_level', ERROR_REPORTING_DISPLAY_ALL);
```

Though in D8 it is indeed set to hide error messages by default (in system.logging.yml).

I am a bit worried that this will make finding and reporting problems more difficult. If no messages are displayed by default, most users (and developers for that matter) won't see problems as they're happening.

**Comment by jenlampton** [comment]
@quicksketch is the security issue mentioned above a real one? Is there any risk in revealing the file structure of a server to the whole world?  If so, would there be a better solution in how we handler our messaging... perhaps by removing the BACKDROP_ROOT from the messages?

**Comment by olafgrabienski** [comment]
As it is "recommended that sites running on production environments do not display any errors" (cf. _admin/config/development/logging_) it's coherent to disable them by default. In my opinion, a non developer overlooking the option to disable errors before going live is more likely than a developer not finding the option to enable errors (or to check the database log).

Messages permission-based sounds interesting and seems to solve the potential criticalness of the issue.

Just another idea whatever default: Show the status of error display and relevant instructions on the status report page.

**Comment by findlabnet** [comment]
PR was updated following recommendations @jenlampton and @quicksketch from https://github.com/backdrop/backdrop/pull/1517.  
> Show the status of error display and relevant instructions on the status report page.

It was done exactly in PR.

>In D7 error logging is set to display all messages

Right, it's my bad.

**Comment by olafgrabienski** [comment]
_> Show the status of error display and relevant instructions on the status report page._

> It was done exactly in PR.

Excellent! (Sorry for not having tested the PR, I only read the issue.)

As I saw, the status is shown when the display of errors is enabled. We could add the status (without warning style) and a relevant message, when error display is off. That would help developers coming from D7 who may expect that error display is enabled by default. It would be also useful for developers beginning to use Backdrop. Proposal:

**Display error messages	Disabled**
`Backdrop CMS provides the ability to display error messages, which can be useful while a site is in development. If your site is in development, you might want to <a href="/admin/config/development/logging">enable the display of errors</a>.`

**Comment by jenlampton** [comment]
The more I think about this the more I think it's a good idea to hide the errors by default. I know @quicksketch is worried about finding out about problems, but I think the kinds of people we are helping by making this change are not the kinds of people who are going to report the errors anyway. They are the site visitors, and maybe editors, not the developers. I value their experience more than the developer experience. 

That said, the addition recommended by @olafgrabienski is a good one (thank you so much for your helpful reviews!) and it will help the developers experience too. I would love to see that addition, if it's not too much trouble @findlabnet?

**Comment by findlabnet** [comment]
Not a trouble at all @jenlampton, so finally I'll add a proposal by @olafgrabienski (thank you!) and default for new installations is disabled (hide), right?

**Comment by jenlampton** [comment]
Yes, once you do that we can kick it back to @quicksketch for final review and hopefully inclusion! :)

**Comment by findlabnet** [comment]
PR updated: https://github.com/backdrop/backdrop/pull/1517

**Comment by olafgrabienski** [comment]
Looks good!

**Comment by findlabnet** [comment]
Thank you, @olafgrabienski! Some time ago without such info in the report I was confused by warning messages from site on production server, where PHP was properly set up.

**Comment by klonos** [comment]
> Or, what if the messages were permission-based?

...

>Messages permission-based sounds interesting and seems to solve the potential criticalness of the issue.

That's what I used in D7: https://www.drupal.org/project/disable_messages

> Just another idea whatever default: Show the status of error display and relevant instructions on the status report page.

👍 Makes perfect sense, but may I propose a change that we can implement either here or in a follow-up issue...

With this change, we are altering the default to a sensible one for people that are new to Drupal/Backdrop, but at the same time altering the expected/default behavior for existing people that come from Drupal. Developers will expect errors if something is wrong and might be annoyed by us hiding them. How about this then...

AFAIK, we show error badges on the admin bar only when there are site status "critical" errors. How about we trigger those badges when the log has "critical" errors as well? That way, we won't have site admins complaining that they had no indication of errors.

**Comment by klonos** [comment]
...and FYI, this is filed against D8: [Option to display php error messages in a block so we can limit visibility per role [#2743119]](https://www.drupal.org/node/2743119)

> At /admin/config/development/logging we have no option to display php error messages in a block that would enable admins limiting the display of error messages per role.Such a feature would be invaluable for debugging. Currently, we cannot control who sees the error messages, but in a block we could easily limit visibility per role.

https://www.drupal.org/project/errorlevelpermission

> This module overrides the error level setting with a permission.

> So you can
> * have a sitebuilder role (or even a special debugger role) **see** errors and notices
> * have others **not see** errors and notices.

**Comment by klonos** [comment]
...so with the proposed change here we mitigate the issue by providing a default that makes sense. This is really great and in tandem with our principle to value users over coders, but changes expected behavior for site builders/admins. In other words, it is a good intermediate solution, but since it is likely upset a portion of users (the ones that are using Backdrop to build and maintain sites - these are the ones we are trying to get to adopt Backdrop), it'd be best to follow up with a more solid/intuitive solution.

I think that when error messages are disabled, showing an error badge in the admin bar would be gold for site admins. We'd be putting existing functionality recently added to good use (badges) and upsetting admins less with our choice of end-user-favoring defaults.

Eventually, I would like to see Backdrop doing the dedicated error messages block thing with default visibility set to admin role only.

**Comment by findlabnet** [comment]
PR updated by following the best recommendation in conversation https://github.com/backdrop/backdrop/pull/1517.

**Comment by jenlampton** [comment]
Thanks @findlabnet! I've removed the `needs work` label and added `needs review` back to get @quicksketch's eyes back on it.

**Comment by findlabnet** [comment]
After some research I've found that the module 'Testing' (simpletest) dealing with value of 'error_level' variable from config directory of 'System' module. Changing value of this variable to 'hide' for now cause failure of test group 'Backdrop error handlers'.
So, I think we need roll back this change and left only pretty messages in the status report. 
In this case current issue should be renamed and PR deleted/recreated with new name?

**Comment by jenlampton** [comment]
I think we should update the test instead.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by findlabnet** [comment]
Done. PR updated https://github.com/backdrop/backdrop/pull/1517/files.

**Comment by quicksketch** [comment]
This PR looks perfect and all tests are passing. Merged https://github.com/backdrop/backdrop/pull/1517 into 1.x for 1.5.0. Great job @findlabnet!

**Comment by LeeteqXV** [comment]
I have played around with the following modules in D7. Should we open a new issue and see if some of that functionality could be implemented into Backdrop core? None of them are "perfect" on their own, but together they have something that could be merged into one really useful solution:

- https://www.drupal.org/project/better_messages
- https://www.drupal.org/project/disable_messages
- https://www.drupal.org/project/messages_to_block
