### ISSUE TITLE
Hiding head code

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2041]
Hi!

What is a better and simple way to hide most of the code from the head?
The reason — I would not like other people knew the website is working on Drupal or Backdrop CMS and I love a clean HTML without a garbage like this one :smile: 

```
    <style media="all">
@import url("http://domain.com/core/misc/normalize.css?obfof8");
@import url("http://domain.com/core/modules/system/css/system.css?obfof8");
@import url("http://domain.com/core/modules/system/css/system.theme.css?obfof8");
</style>
<style media="all">
@import url("http://domain.com/core/modules/layout/css/grid-flexbox.css?obfof8");
</style>
<style media="all">
@import url("http://domain.com/core/modules/comment/css/comment.css?obfof8");
@import url("http://domain.com/core/modules/date/css/date.css?obfof8");
@import url("http://domain.com/core/modules/field/css/field.css?obfof8");
@import url("http://domain.com/core/modules/user/css/user.css?obfof8");
@import url("http://domain.com/core/modules/views/css/views.css?obfof8");
</style>
<style media="all">
@import url("http://domain.com/themes/bartik/css/style.css?obfof8");
@import url("http://domain.com/files/color/bartik-2611160a/colors.css?obfof8");
</style>
<style media="print">
@import url("http://domain.com/themes/bartik/css/print.css?obfof8");
</style>
    <script>window.Backdrop = {settings: {"basePath":"\/","pathPrefix":"","drupalCompatibility":true,"ajaxPageState":{"theme":"bartik","theme_token":"9c16gRMuxP91TbFVBWo1Tqs04UCso8V-59IaqqbQaSI","css":{"core\/misc\/normalize.css":1,"core\/modules\/system\/css\/system.css":1,"core\/modules\/system\/css\/system.theme.css":1,"core\/modules\/layout\/css\/grid-flexbox.css":1,"core\/modules\/comment\/css\/comment.css":1,"core\/modules\/date\/css\/date.css":1,"core\/modules\/field\/css\/field.css":1,"core\/modules\/search\/search.theme.css":1,"core\/modules\/user\/css\/user.css":1,"core\/modules\/views\/css\/views.css":1,"layouts\/boxton\/boxton.css":1,"themes\/bartik\/css\/style.css":1,"themes\/bartik\/css\/colors.css":1,"themes\/bartik\/css\/print.css":1},"js":{"core\/misc\/html5.js":1,"core\/misc\/jquery.js":1,"core\/misc\/jquery.once.js":1,"core\/misc\/backdrop.js":1,"core\/modules\/layout\/js\/grid-fallback.js":1}},"urlIsAjaxTrusted":{"\/user\/password":true}}};</script>

<!--[if lte IE 8]>
<script src="http://domain.com/core/misc/html5.js?v=3.7.2"></script>
<![endif]-->
<script src="http://domain.com/core/misc/jquery.js?v=1.11.0"></script>
<script src="http://domain.com/core/misc/jquery.once.js?v=1.2"></script>
<script src="http://domain.com/core/misc/backdrop.js?v=1.4.3"></script>
<script src="http://domain.com/core/modules/layout/js/grid-fallback.js?v=1.4.3"></script>
```

**Comment by klonos** [comment]
In Drupal, one could remove the "Generator" meta tag (`<meta name="Generator" content="Backdrop CMS 1 (http://backdropcms.org)" />` if you were using https://www.drupal.org/project/metatag by overriding its general settings and leaving empty the respective field. If you did not have that module installed and did not want all that it offered, then there was https://www.drupal.org/project/remove_generator that simply did that.

Alternatively, one could use `hook_html_head_alter` ([which exists in Backdrop too](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_html_head_alter/1)) to unset the `system_meta_generator`:

```php
function YOUR_MODULE_OR_THEME_html_head_alter(&$head_elements) {
  unset($head_elements['system_meta_generator']);
}
```

I think that this should work just fine in Backdrop.

**Comment by klonos** [comment]
...as for `<script>window.Backdrop` etc, I'm sure that trying to remove/override that would break your site.

**Comment by bd0bd** [comment]
Thank you!

I do not have problems with >meta name="Generator" content="Backdrop CMS 1 (http://backdropcms.org)" /< I use https://github.com/backdrop-contrib/remove_generator

Sorry, I do not understand about this code. What is the file/folder name and line number where it should be placed in :smile: 

    function YOUR_MODULE_OR_THEME_html_head_alter(&$head_elements) {
      unset($head_elements['system_meta_generator']);
    }

**Comment by jenlampton** [comment]
@bd0bd if you aggregate / compress your CSS you won't see most of that garbage in your HEAD.  Go to Admin > Config > Development > Performance and check the box for "Aggregate and compress CSS files. "

**Comment by bd0bd** [comment]
I use it. This is  not a solution. Anyway there is too much coding I would like to hide. Currently it is, sorry, very ugly. not beautiful

**Comment by jenlampton** [comment]
Sorry, the only "ugly" code you provided in your first post was the CSS and JS which will not be shown if you follow the instructions I gave you. Without an example or better explanation of what it is that you actually want to hide we can't help you.
