### ISSUE TITLE
Change website language without changing URL

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2045]
When we change language then URL is changed too:
- domain.com
- domain.com/de
- domain.com/fr
- etc.

Is it possible to change language without changing URL?:
- domain.com
- domain.com
- domain.com
- etc.

**Comment by jenlampton** [comment]
I don't think this is a Backdrop Core issue. Perhaps you intended to file this in the i18n queue?

**Comment by bd0bd** [comment]
I am sure this is Backdrop issue if you have language config at
`/admin/config/regional/language`
Configure languages for content and the user interface.

**Comment by jenlampton** [comment]
How are you changing language from domain.com/de to domain.com/fr ?

**Comment by BWPanda** [comment]
Closing (again) due to lack of feedback.
