### ISSUE TITLE
Do we still need the .travis.yml file now that we are on ZenCI?

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#2051]
If we no longer need the `.travis.yml` I propose we delete it.

Looks like zen-ci has its own config in: `core/misc/zen-ci`.

thanks,
~Geoff

**Comment by Gormartsen** [comment]
@serundeputy .travis.yml and core/misc/travis-ci is not required for Zen.CI

**Comment by quicksketch** [comment]
Let's remove all the .travis.yml for 1.5.0, as well as the badge on the project page (README.md).

**Comment by quicksketch** [comment]
PR https://github.com/backdrop/backdrop/pull/1577.

And we finally get to thank ZenCI in our README.md :grinning:

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1577.

And a personal, THANK YOU once again to @Gormartsen for creating such an amazing service. I hope many, many projects get to benefit from this great tool.
