### ISSUE TITLE
Could not delete temporary file "temporary://forum-1.x-1.0.0-02.04.2015.zip" during garbage collection.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2052]
Starting this as a question because it might be limited to my specific local dev or the specific contrib module. I see this error with _every_ cron run:

Type    file system
Date    Tuesday, August 9, 2016 - 2:10am
User    Anonymous (not verified)
Location    http://localhost/admin/reports/status/run-cron
Referrer    http://localhost/admin/reports/dblog
Message Could not delete temporary file "temporary://forum-1.x-1.0.0-02.04.2015.zip" during garbage collection
Severity    error
Hostname    127.0.0.1
Operations  

---
PR by @bradbulger: https://github.com/backdrop/backdrop/pull/2512

**Comment by serundeputy** [comment]
@klonos can you post the permissions on that file vs. the permissions on other files in your tmp dir?

**Comment by klonos** [comment]
This is a Windows machine where I my account is admin and most applications run as administrator, so I don't think that this is a file system permissions issue. Besides, there is no such file in my temp directory ...if there was, I would have manually deleted it and wouldn't have filed this issue in the first place 😄

**Comment by olafgrabienski** [comment]
@klonos I saw the similar messages about files that can't be deleted in one of my sites, all of them contrib module packages. I also didn't find the files, but interestingly they were listed on the page `admin/content/files`(which might have been added to Backdrop after your issue report) where I could delete them.

**Comment by bradbulger** [comment]
I see this as well, that error is specifically generated when the file doesn't exist. Wouldn't it make sense to just remove it from file_managed at that point? It's not like there is a file that it is trying to delete and failing.

**Comment by bradbulger** [comment]
Testing this, letting it just delete the file, the File preDelete() method gets called:

> // Delete the actual file. Failures due to invalid files and files that
      // were already deleted are logged to watchdog but ignored, the
      // corresponding file entity will be deleted.

It works fine.

**Comment by herbdool** [comment]
@klonos want to test this one?

**Comment by laryn** [comment]
Seems to work for me!

**Comment by quicksketch** [comment]
Yeah this seems weird, why throw an error if the file doesn't exist when the objective is to delete it? The job is already done. :smile: 

So seems ready to go to me as well.

**Comment by quicksketch** [comment]
Merged this into 1.x and 1.14.x. Thanks folks!
