### ISSUE TITLE
Disable auto e-mail sending after user registration

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2053]
I have disabled  e-mail field in the registration form.
An user need to fill in only two fields - username and password.
After user is registered it shows _"Unable to send e-mail. Contact the site administrator if the problem persists."_

![aaa](https://cloud.githubusercontent.com/assets/13515302/17551720/605fc458-5f04-11e6-85ac-9594723c2c7b.png)

In Account settings **/admin/config/people/settings** and in Account emails **/admin/config/people/emails** I do not see the option to disable auto emailing.
Please, how to disable it?
Thank you very much!

**Comment by bd0bd** [comment]
The email WELCOME (NEW USER CREATED BY ADMINISTRATOR) /admin/config/people/emails has no option to disable it.

**Comment by bd0bd** [comment]
@klonos, you can explain clear and without garbage words.
I try to port Mailcontrol https://www.drupal.org/project/mailcontrol
I know what to do with **mailcontrol.info** file but do not know what I should redo in mailcontrol.module file. May be you might explain me, if you have a time.

**Comment by serundeputy** [comment]
@bd0bd I think this will get you what you need: `/admin/config/people/settings`

![screen shot 2016-08-10 at 6 28 40 pm](https://cloud.githubusercontent.com/assets/6763671/17573447/6d7a43c4-5f28-11e6-883a-f2bb030d0c93.png)

**Comment by bd0bd** [comment]
@serundeputy, this has no any connection with the issue :smile: 
There is no any options on this page to disable auto email sendings.

**Comment by BWPanda** [comment]
Closing old issues. Feel free to reopen if you're still needing help with this.
