### ISSUE TITLE
CKEditor - Add the ability to reuse an existing image

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2056]
When editing content it is sometimes appropriate to insert an image that has previously been uploaded to the site rather than upload another copy of the file. Therefore it is desirable that CKEditor can be used to browse the existing files on the server and select one for use, rather than the user having to know and enter the URL of the required file.

**Comment by Graham-72** [comment]
Perhaps I should have made the title 'CKEditor - improve support for reusing a previously uploaded image file'?

**Comment by docwilmot** [comment]
Or alternate title: "Add a file browser/manager to core". Something like CKFinder, Media, IMCE, etc etc.

**Comment by jenlampton** [comment]
Or "add filefield sources" to core...  wait... like this one? https://github.com/backdrop/backdrop-issues/issues/1307

**Comment by klonos** [comment]
...you beat me to it @jenlampton 👍
