### ISSUE TITLE
Module porting question

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2058]
Please, could you show me what is wrong with files I try to port:

	name = Optional mail on register
	description = New users need not enter a valid email address when registering.
	type = module
	backdrop = 1.x

	package = User Management
	files[] = optional_mail_on_register.info
	files[] = optional_mail_on_register.module
	files[] = optional_mail_on_register.js
	files[] = optional_mail_on_register.css

--

	<?php
	/*
	 * @file
	 * This module allows users to be registered without the necessity to
	 * inform an e-mail. Therefore, the e-mail field is non-mandatory.
	 * Thanks to http://drupal.org/node/747824#comment-4038044  for the
	 * initial code.
	 *
	 */

	/**
	 * Test if the module No Request New Password exists.
	 */
	function optional_mail_on_register_check_noreqnewpass() {
	  $nrnpmsg = '';
	  if (($_GET['q'] == 'admin/config/people/settings') && (variable_get('optionalmail_register', 0) == '1') && (module_exists('noreqnewpass') == FALSE)) {
		$nrnpmsg = t('We recommend the module <a href="@moduleurl">No Request New Password</a> as a complement to Optional mail on register. It removes the ability to do a password reset via email.', array('@moduleurl' => url('http://drupal.org/project/noreqnewpass')));
	  }
	  return $nrnpmsg;
	}

	/**
	 * Implements hook_form_alter().
	 */
	function optional_mail_on_register_form_alter(&$form, &$form_state, $form_id) {
	  switch ($form_id) {
		case 'user_register_form':
		  if (variable_get('optionalmail_register', 0) == '1') {
			$form['mail']['#required'] = FALSE;
			$form['account']['mail']['#required'] = FALSE;
			switch (variable_get('optionalmail_alterfield_register', 'field visible')) {
			  case 'field disabled':
				$form['mail']['#disabled'] = TRUE;
				$form['account']['mail']['#disabled'] = TRUE;
				break;
			  case 'field hidden':
				$form['mail']['#prefix'] = '<div style="display: none">';
				$form['mail']['#suffix'] = '</div>';

				$form['account']['mail']['#prefix'] = '<div style="display: none">';
				$form['account']['mail']['#suffix'] = '</div>';
				break;
			}
			$form['#validate'][0] = 'optional_mail_on_register_form_validate';
		  }
		  break;
		case 'user_profile_form':
		  if (variable_get('optionalmail_edit', 0) == '1') {
			$form['account']['mail']['#required'] = FALSE;
			switch (variable_get('optionalmail_alterfield_edit', 'field visible')) {
			  case 'field disabled':
				$form['account']['mail']['#disabled'] = TRUE;
				break;
			  case 'field hidden':
				$form['account']['mail']['#prefix'] = '<div style="display: none">';
				$form['account']['mail']['#suffix'] = '</div>';
				break;
			}
			$form['#validate'][0] = 'optional_mail_on_register_form_validate';
		  }
		  break;
		case 'user_admin_settings':
		  // Add some css and js to admin user settings' page.
		  $form['#attached']['css'] = array(
			backdrop_get_path('module', 'optional_mail_on_register') . '/optional_mail_on_register.css'
		  );
		  $form['#attached']['js'] = array(
			backdrop_get_path('module', 'optional_mail_on_register') . '/optional_mail_on_register.js'
		  );
		  // Test if the feature is On and disable the email verification on
		  // new accounts.
		  if (variable_get('optionalmail_register', 0) == '1') {
			$form['registration_cancellation']['user_email_verification']['#disabled'] = TRUE;
			$form['registration_cancellation']['user_email_verification']['#title'] .= ' <strong>Disabled by the Optional Mail on Register module</strong>.';
			if (module_exists('contact')) {
			  $form['contact']['contact_default_status']['#disabled'] = TRUE;
			  $form['contact']['contact_default_status']['#title'] .= ' <strong>Disabled by the Optional Mail on Register module</strong>.';
			}
		  }
		  $form['optionalmail_settings'] = array(
			'#type' => 'fieldset',
			'#title' => t('Optional mail on register settings'),
			'#weight' => -10,
			'#description' => optional_mail_on_register_check_noreqnewpass(),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
		  );
		  $form['optionalmail_settings']['optionalmail_register'] = array(
			'#type' => 'checkbox',
			'#title' => t('Enable optional email in the user register'),
			'#default_value' => variable_get('optionalmail_register', 0),
			'#return_value' => 1,
		  );
		  $form['optionalmail_settings']['optionalmail_alterfield_register'] = array(
			'#type' => 'radios',
			'#default_value' => variable_get('optionalmail_alterfield_register', 'field visible'),
			'#prefix' => '<div id="optionalmail-radios-options-1" class="optionalmail-radios-options">',
			'#suffix' => '</div>',
			'#options' =>
			array(
			  'field visible' => t('Leave the e-mail field visible and editable in the user register form.'),
			  'field disabled' => t('Disable the e-mail field in user register form.'),
			  'field hidden' => t('Hide the e-mail field in the user register form.'),
			),
		  );
		  $form['optionalmail_settings']['optionalmail_edit'] = array(
			'#type' => 'checkbox',
			'#title' => t('Enable optional email in the user edition'),
			'#default_value' => variable_get('optionalmail_edit', 0),
			'#return_value' => 1,
		  );
		  $form['optionalmail_settings']['optionalmail_alterfield_edit'] = array(
			'#type' => 'radios',
			'#default_value' => variable_get('optionalmail_alterfield_edit', 'field visible'),
			'#prefix' => '<div id="optionalmail-radios-options-2" class="optionalmail-radios-options">',
			'#suffix' => '</div>',
			'#options' =>
			array(
			  'field visible' => t('Leave the e-mail field visible and editable in the user profile edit form.'),
			  'field disabled' => t('Disable the e-mail field in user profile edit form.'),
			  'field hidden' => t('Hide the e-mail field in the user profile edit form.'),
			),
		  );
		  if (module_exists('contact')) {
			$form['optionalmail_settings']['user_contact_form'] = array(
			  '#type' => 'checkbox',
			  '#default_value' => variable_get('user_contact_form', FALSE),
			  '#title' => t("Disable the user's contact form in all users"),
			  '#return_value' => 1,
			);
		  }
		  $form['#submit'][] = 'optional_mail_on_register_optionalmail_settings_submit';
		  break;
	  }
	}

	/**
	 * Implements hook_form_submit().
	 */
	function optional_mail_on_register_optionalmail_settings_submit($form, &$form_state) {
	  if ($form_state['values']['optionalmail_register'] == '1') {
		backdrop_set_message(t('A request for mail in the register of new users is now optional. Email check for new user accounts has been disabled.'), 'status');
		variable_set('user_email_verification', FALSE);
		if (module_exists('contact')) {
		  variable_set('contact_default_status', FALSE);
		}
	  }
	  if ($form_state['values']['optionalmail_edit'] == '1') {
		backdrop_set_message(t('The email field in the user edit form is now optional.'), 'status');
	  }
	  if (module_exists('contact') && $form_state['values']['user_contact_form'] == '1') {
		$uids = db_select('users', 'u')->fields('u', array('uid'))->condition('uid', 0, '<>')->execute()->fetchAssoc();
		foreach ($uids as $uid) {
		  $user  = user_load($uid);
		  if ($user->data['contact'] == 1) {
			$user->data['contact'] = 0;
			user_save($user);
		  }
		}
	  }
	  backdrop_set_message(optional_mail_on_register_check_noreqnewpass(), 'status');
	}

	/**
	 * Performs user register validation, fooling the lack of e-mail in
	 * registration
	 */
	function optional_mail_on_register_form_validate($form, &$form_state) {
	  // If no email value, then stuff a temp one to fool the validation.
	  if ($form_state['values']['mail'] == NULL) {
		// A unique non-existent email.
		$form_state['values']['mail'] = 'nobody@nowhere.com';
	  }
	  // Call original system validation.
	  user_account_form_validate($form, $form_state);
	  // Stuff empty back again.
	  if ($form_state['values']['mail'] == 'nobody@nowhere.com') {
		$form_state['values']['mail'] = '';
	  }
	}

**Comment by bd0bd** [comment]
The options does  not save after saving:

![aaa](https://cloud.githubusercontent.com/assets/13515302/17602519/a210cdea-6015-11e6-9587-76b258c13264.png)

**Comment by Graham-72** [comment]
You need to introduce a config settings file and replace variable_set and variable_get with config_set and config_get, with their modifications. See 'Update your module to use Configuration management' in https://api.backdropcms.org/converting-modules-from-drupal for details.

**Comment by bd0bd** [comment]
Thank you!
I have read the article but there are a lot of letters (garbage) and it makes me to get deep in troubles.

I need very short instructions without detailed exaplanations :smile: 

Thank you @Graham-72! I will try.

**Comment by bd0bd** [comment]
>You need to introduce a config settings file 

What does it mean?

**Comment by Graham-72** [comment]
@bd0bd in case it helps I share with you my 10 point checklist I wrote for my own benefit for porting modules:
1. In module info file replace ‘core =  7.x’ with ‘backdrop =  1.x’
2. Throughout, replace ‘drupal’ with ‘backdrop’ (except for URLs etc), retaining case.
3. Introduce a mymodule.settings.json file and replace variable_get, variable_set with config_get and config_set
4. Add hook_config_info function to mymodule.module
5. Remove from module info file any load for Classes.
6. Add hook_autoload_info function to mymodule.module 
7. Add hook_update_1000 function to mymodule.install
8. Add hook_update_last_removed function to mymodule.install
9. Remove all previous hook_update functions
10. Check for any occurrences of ‘system_settings_form’ and replace with code for config.

Of course this does not tell you how to do each of these things. And there are some other changes needed for special situations in Backdrop.
Have you watched Nate's video at https://www.youtube.com/watch?v=by8mMhIpARA ?

**Comment by bd0bd** [comment]
Thank you very much!
I will try!

**Comment by bd0bd** [comment]
Nate's video is too difficult for me.

**Comment by Graham-72** [comment]
> What does it mean?

Each contributed module has a configuration settings file. As and example here is the one for the mediaelement module. The file name is mediaelement.settings.json

`
{
  "_config_name": "mediaelement.settings",
  "mediaelement_sitewide": 0,
  "mediaelement_video_default_controls": 1,
  "mediaelement_video_default_width": 640,
  "mediaelement_video_default_height": 385,
  "mediaelement_video_default_download_link": 0,
  "mediaelement_video_default_download_text": "Download",
  "mediaelement_audio_default_controls": 1,
  "mediaelement_audio_default_width": 300,
  "mediaelement_audio_default_height": 30,
  "mediaelement_audio_default_download_link": 0,

  "mediaelement_audio_default_download_text": "Download"
}
`

Some modules have fewer entries, others have many more.

**Comment by bd0bd** [comment]
I have changed variable_get, variable_set  in the file bit it does not work.

	<?php
	/*
	 * @file
	 * This module allows users to be registered without the necessity to
	 * inform an e-mail. Therefore, the e-mail field is non-mandatory.
	 * Thanks to http://drupal.org/node/747824#comment-4038044  for the
	 * initial code.
	 *
	 */

	/**
	 * Test if the module No Request New Password exists.
	 */
	function optional_mail_on_register_check_noreqnewpass() {
	  $nrnpmsg = '';
	  if (($_GET['q'] == 'admin/config/people/settings') && (config_get('optionalmail_register', 0) == '1') && (module_exists('noreqnewpass') == FALSE)) {
		$nrnpmsg = t('We recommend the module <a href="@moduleurl">No Request New Password</a> as a complement to Optional mail on register. It removes the ability to do a password reset via email.', array('@moduleurl' => url('http://drupal.org/project/noreqnewpass')));
	  }
	  return $nrnpmsg;
	}

	/**
	 * Implements hook_form_alter().
	 */
	function optional_mail_on_register_form_alter(&$form, &$form_state, $form_id) {
	  switch ($form_id) {
		case 'user_register_form':
		  if (config_get('optionalmail_register', 0) == '1') {
			$form['mail']['#required'] = FALSE;
			$form['account']['mail']['#required'] = FALSE;
			switch (config_get('optionalmail_alterfield_register', 'field visible')) {
			  case 'field disabled':
				$form['mail']['#disabled'] = TRUE;
				$form['account']['mail']['#disabled'] = TRUE;
				break;
			  case 'field hidden':
				$form['mail']['#prefix'] = '<div style="display: none">';
				$form['mail']['#suffix'] = '</div>';

				$form['account']['mail']['#prefix'] = '<div style="display: none">';
				$form['account']['mail']['#suffix'] = '</div>';
				break;
			}
			$form['#validate'][0] = 'optional_mail_on_register_form_validate';
		  }
		  break;
		case 'user_profile_form':
		  if (config_get('optionalmail_edit', 0) == '1') {
			$form['account']['mail']['#required'] = FALSE;
			switch (config_get('optionalmail_alterfield_edit', 'field visible')) {
			  case 'field disabled':
				$form['account']['mail']['#disabled'] = TRUE;
				break;
			  case 'field hidden':
				$form['account']['mail']['#prefix'] = '<div style="display: none">';
				$form['account']['mail']['#suffix'] = '</div>';
				break;
			}
			$form['#validate'][0] = 'optional_mail_on_register_form_validate';
		  }
		  break;
		case 'user_admin_settings':
		  // Add some css and js to admin user settings' page.
		  $form['#attached']['css'] = array(
			backdrop_get_path('module', 'optional_mail_on_register') . '/optional_mail_on_register.css'
		  );
		  $form['#attached']['js'] = array(
			backdrop_get_path('module', 'optional_mail_on_register') . '/optional_mail_on_register.js'
		  );
		  // Test if the feature is On and disable the email verification on
		  // new accounts.
		  if (config_get('optionalmail_register', 0) == '1') {
			$form['registration_cancellation']['user_email_verification']['#disabled'] = TRUE;
			$form['registration_cancellation']['user_email_verification']['#title'] .= ' <strong>Disabled by the Optional Mail on Register module</strong>.';
			if (module_exists('contact')) {
			  $form['contact']['contact_default_status']['#disabled'] = TRUE;
			  $form['contact']['contact_default_status']['#title'] .= ' <strong>Disabled by the Optional Mail on Register module</strong>.';
			}
		  }
		  $form['optionalmail_settings'] = array(
			'#type' => 'fieldset',
			'#title' => t('Optional mail on register settings'),
			'#weight' => -10,
			'#description' => optional_mail_on_register_check_noreqnewpass(),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
		  );
		  $form['optionalmail_settings']['optionalmail_register'] = array(
			'#type' => 'checkbox',
			'#title' => t('Enable optional email in the user register'),
			'#default_value' => config_get('optionalmail_register', 0),
			'#return_value' => 1,
		  );
		  $form['optionalmail_settings']['optionalmail_alterfield_register'] = array(
			'#type' => 'radios',
			'#default_value' => config_get('optionalmail_alterfield_register', 'field visible'),
			'#prefix' => '<div id="optionalmail-radios-options-1" class="optionalmail-radios-options">',
			'#suffix' => '</div>',
			'#options' =>
			array(
			  'field visible' => t('Leave the e-mail field visible and editable in the user register form.'),
			  'field disabled' => t('Disable the e-mail field in user register form.'),
			  'field hidden' => t('Hide the e-mail field in the user register form.'),
			),
		  );
		  $form['optionalmail_settings']['optionalmail_edit'] = array(
			'#type' => 'checkbox',
			'#title' => t('Enable optional email in the user edition'),
			'#default_value' => config_get('optionalmail_edit', 0),
			'#return_value' => 1,
		  );
		  $form['optionalmail_settings']['optionalmail_alterfield_edit'] = array(
			'#type' => 'radios',
			'#default_value' => config_get('optionalmail_alterfield_edit', 'field visible'),
			'#prefix' => '<div id="optionalmail-radios-options-2" class="optionalmail-radios-options">',
			'#suffix' => '</div>',
			'#options' =>
			array(
			  'field visible' => t('Leave the e-mail field visible and editable in the user profile edit form.'),
			  'field disabled' => t('Disable the e-mail field in user profile edit form.'),
			  'field hidden' => t('Hide the e-mail field in the user profile edit form.'),
			),
		  );
		  if (module_exists('contact')) {
			$form['optionalmail_settings']['user_contact_form'] = array(
			  '#type' => 'checkbox',
			  '#default_value' => config_get('user_contact_form', FALSE),
			  '#title' => t("Disable the user's contact form in all users"),
			  '#return_value' => 1,
			);
		  }
		  $form['#submit'][] = 'optional_mail_on_register_optionalmail_settings_submit';
		  break;
	  }
	}

	/**
	 * Implements hook_form_submit().
	 */
	function optional_mail_on_register_optionalmail_settings_submit($form, &$form_state) {
	  if ($form_state['values']['optionalmail_register'] == '1') {
		backdrop_set_message(t('A request for mail in the register of new users is now optional. Email check for new user accounts has been disabled.'), 'status');
		config_set('user_email_verification', FALSE);
		if (module_exists('contact')) {
		  config_set('contact_default_status', FALSE);
		}
	  }
	  if ($form_state['values']['optionalmail_edit'] == '1') {
		backdrop_set_message(t('The email field in the user edit form is now optional.'), 'status');
	  }
	  if (module_exists('contact') && $form_state['values']['user_contact_form'] == '1') {
		$uids = db_select('users', 'u')->fields('u', array('uid'))->condition('uid', 0, '<>')->execute()->fetchAssoc();
		foreach ($uids as $uid) {
		  $user  = user_load($uid);
		  if ($user->data['contact'] == 1) {
			$user->data['contact'] = 0;
			user_save($user);
		  }
		}
	  }
	  backdrop_set_message(optional_mail_on_register_check_noreqnewpass(), 'status');
	}

	/**
	 * Performs user register validation, fooling the lack of e-mail in
	 * registration
	 */
	function optional_mail_on_register_form_validate($form, &$form_state) {
	  // If no email value, then stuff a temp one to fool the validation.
	  if ($form_state['values']['mail'] == NULL) {
		// A unique non-existent email.
		$form_state['values']['mail'] = 'nobody@nowhere.com';
	  }
	  // Call original system validation.
	  user_account_form_validate($form, $form_state);
	  // Stuff empty back again.
	  if ($form_state['values']['mail'] == 'nobody@nowhere.com') {
		$form_state['values']['mail'] = '';
	  }
	}

**Comment by bd0bd** [comment]
>Each contributed module has a configuration settings file

No. I do not have it but my module is working fine.

**Comment by Graham-72** [comment]
You do need a quick_registration.settings.json file in a config folder to store the settings of your variables.

For example, you have config_get('optionalmail_register', 0) in your module file, but this is not correct and has to be config_get('quick_registration.settings','optionalmail_register'), and there has to be a line "optionalmail_register": 0 in your quick_registration.settings.json file.

**Comment by bd0bd** [comment]
You mean  I need to create folder **config** and place **optional_mail_settings.json**?

**Comment by bd0bd** [comment]
Thank you!
It does not help :smile: 
It does not work

Notice: Array to string conversion in form_process_checkbox() (line 3268 of /core/includes/form.inc).
Notice: Array to string conversion in form_process_checkbox() (line 3268 of /core/includes/form.inc).

**Comment by bd0bd** [comment]
I am getting out of the talk.
Thank you very much for your help!

**Comment by Graham-72** [comment]
My mistake about the name of your module.
I should have said you need a config file named optional_mail_on_register.settings.json if you follow the usual practice of using the module name as used for the other files.

**Comment by bd0bd** [comment]
>optional_mail_on_register.settings.json

Should I make config folder and place it in?
I did but it does not work.

Notice: Array to string conversion in form_process_checkbox() (line 3268 of /core/includes/form.inc).
Notice: Array to string conversion in form_process_checkbox() (line 3268 of /core/includes/form.inc).

**Comment by bd0bd** [comment]
Inside file is this code: `"_config_name": "optional_mail_on_register.settings"`

**Comment by Graham-72** [comment]
Yes.
And in your module file every config_get(...) is like this
config_get('optional_mail_on_register.settings','optional_mail.register')
where the second parameter is the particular config value needed at that point in the code

See https://api.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/config_get/1

**Comment by bd0bd** [comment]
@Graham-72, thank you!
Again I am forced to switch to Drupal 7.
Too much headache with Backdrop.

**Comment by quicksketch** [comment]
Thanks @Graham-72 for your help here! I also want to mention https://api.backdropcms.org/converting-modules-from-drupal, which is the main documentation for porting a module.

@bd0bd Sorry we weren't able to get it all figured out! The switch to configuration files is definitely one of the biggest (but most beneficial) changes in Backdrop. Perhaps you could post your module to your GitHub account and then we could look through it all in one place. Then we could suggest changes through pull requests? Though if you've decided to stick to D7 for now maybe we should close this issue.
