### ISSUE TITLE
Double escaping in Post date date format display in Views UI

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2063]
Steps to reproduce
* Change your Short date format at Admin > Config > Regional & Language > Date formats
* Use a string with a character in it, like `M jS 'y`
* Create a view of nodes (fields)
* add the Post date field
* Style it to use the short format
* BAM

![screen shot 2016-08-15 at 12 20 52 am](https://cloud.githubusercontent.com/assets/397895/17658155/606bfde0-627e-11e6-9094-33e88d2d9ce6.png)

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1574 that removes the double-escaping. Select list `#options` are escaped for us, we don't need to explicitly do it as was happening.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/1574.
