### ISSUE TITLE
[DX] make the import of config files less brittle

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2064]
I've been fighting Pantheon for the last two days dealing with config management, and I seem to have gotten myself into a pickle. I have a config file in the system that should not be there. It defines a database table that has since been deleted. In order to solve the problem all I need to do is delete the config file from Pantheon. That, however, is impossible.
- There is no SFTP access into the "files" directory, so the file can not be deleted manually.
- Config can not be safely stored in Git on Pantheon, because there is no write-access to the docroot, and nothing outside the docroot can be managed via git.
- Using the Config UI results in a PHP fatal when it attempts to delete the database table that does not exist, and the json file is not deleted.

It seems to me that the last problem is not really a problem. Deleting a database table that does not exist should not result in a fatal - Backdrop should continue as usual since the end result is the same - no database table.

I propose that we check if the table exists before we try to delete it to prevent the PHP fatal, and allow Backdrop to continue.

I'm not sure how I got myself into this pickle in the first place, but it seems to me that we should be kinder to our developers and allow us all to get out of this kind of problem should it arise :)

**Comment by docwilmot** [comment]
>Using the Config UI results in a PHP fatal when it attempts to delete the database table that does not exist, and the json file is not deleted.
> I propose that we check if the table exists before we try to delete it to prevent the PHP fatal, and allow Backdrop to continue.

I don't get this at all.  How does the Config UI try to delete a table?

**Comment by jenlampton** [comment]
@docwilmot good question, it's a couple steps removed. The config file in this case was for a field, so it triggered `field` module which invoked `field_sql_storage`, and that module was the one that attempted to delete tables that didn't exist, and fataled out.

**Comment by jenlampton** [comment]
ugh, well, this simple change isn't going to change anything, it appears. It looks like Backdrop queries the table it's about to delete before it gets deleted for some reason - perhaps to see how large it is?  not sure, I can't follow this EntityFieldQuery code around clearly enough. I'm going to go back to trying to un-bork my site and will leave this here to think about for a little while :)

**Comment by klonos** [comment]
> It seems to me that the last problem is not really a problem. Deleting a database table that does not exist should not result in a fatal - Backdrop should continue as usual since the end result is the same - no database table.

My reaction exactly as I was reading your issue summary.

**Comment by klonos** [comment]
@jenlampton it would help if you provided steps to reproduce and the exact PHP fatal you get.

**Comment by docwilmot** [comment]
Sorry to hear. Doesnt 
```
$config = config('field.prefix.name');
  $config->delete();
```
do the trick?

**Comment by docwilmot** [comment]
There should be no reason for a plain config delete to trigger any database queries except for if `hook_config_delete()` is being called AFAICT. Maybe if you temporarily commented out `field_config_delete()`?

**Comment by serundeputy** [comment]
@jenlampton 

When I go to the pantheon dashboard for a backdrop site
  and click `Connection info`
  and scroll down to ftp
  and click ` Open in SFTP client`
  then I see the /files directory
  and I see in the /files directory /files/config
  and I can delete things from there

Can you try that?

**Comment by jenlampton** [comment]
You got it @docwilmot for field config files `hook_config_delete` is called.

I tried `open in STFP client` but CyberDuck crashed. I haven't used that thing in years. Which one do you use?

**Comment by serundeputy** [comment]
I am using cyberduck

**Comment by jenlampton** [comment]
Maybe it's time for an update :)

**Comment by serundeputy** [comment]
looks like you can do it via command line sftp

```
sftp -o Port=2222 dev.{your_hash}@appserver.dev.{your_hash}drush.in
```

**Comment by jenlampton** [comment]
I tried that yesterday too with noluck, but CyberDuck worked today (after the update). Woot!  I;ve deleted those pesky configs...  fingers crossed!

**Comment by quicksketch** [comment]
> You got it @docwilmot for field config files `hook_config_delete` is called.

Just to clarify, Config UI *will* try to delete the database table and fire `hook_config_delete()`, but a simple call like:

`config('foo.settings')->delete()`

Will *not* fire the hooks. Those hooks are to facilitate the bulk importing of an entire site's config. So while doing a UI-based sync of config and deleting a field will attempt to delete the database table, just calling `config('field.field_foo')->delete()` won't actually call the hooks, and would be suitable for deleting a rogue config file.

We're still not sure how this happened in the first place though. Any idea how to reproduce the issue? It sounds like the field settings config file was added somehow accidentally, but without prior FTP access, I'm not sure how that would have happened without going through the syncing UI.

**Comment by jenlampton** [comment]
Yeah, I have no idea how it happened. Probably user error? Anyway, it sounds like there are a few good solutions to fixing the problem now, so closing this issue :)
