### ISSUE TITLE
[UX] Views exposed filters in block displays require AJAX

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2075]
If you create a views page display and add exposed filters they show on the page. If you create a block display and add views exposed filters, they do not show in the block. 

This is consistent with how views worked in Drupal 7, but the ctools views content pane displays solved this problem by adding views exposed forms into content pane displays.

Since Backdrop blocks are a lot more like content panes, we should apply the same improvements to our views block displays.

Right now it feels like a very broken user experience to add exposed filters to a view and not have them appear anywhere.

**Comment by jenlampton** [comment]
Assigning the milestone of 1.6 because not being able to use exposed filters is becoming a real problem for backdropcms.org. Not sure if others are affected or not, but it's likely.

**Comment by olafgrabienski** [comment]
Did you try to enable "Use AJAX"? I found the following hint to do it in the Exposed Form settings of the view:

> Exposed filters in block displays require "Use AJAX" to be set to work correctly.

See the two relevant links in the interface:

![backdrop-exposed-filter-block-settings](https://cloud.githubusercontent.com/assets/14188307/19538725/b862a386-9655-11e6-9c81-ae2e481e2172.png)

After setting "Use AJAX" to *Yes*, in a quick test in my local environment, I was able to use an exposed filter in a block.

**Comment by jenlampton** [comment]
No, I haven't tried that, thanks for pointing it out @olafgrabienski I hadn't seen that text. Since this is apparently not a bug (!!) I'm going to remove the label and push to 1.7. 

From a UX perspective I think this is still an important issue to address as people (like myself) will be expecting them to work without AJAX.

**Comment by klonos** [comment]
Perhaps we can have a check in place for when a *block* display is being added and if there are exposed filters, then have the "Use AJAX" setting be auto-activated (and perhaps also locked in that state until there are no exposed filters in that display).

**Comment by jenlampton** [comment]
I'd prefer that we just fix the problem that makes Ajax necessary. It's
solved with panels co tent panes. We just need to copy the code.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by jenlampton** [comment]
I'm going to close this issue since it is essentially a duplicate of https://github.com/backdrop/backdrop-issues/issues/2433, which is a lot closer to getting in.

**Comment by quicksketch** [comment]
Tagging this as 1.7.0 as it will be fixed at the same time.

**Comment by jenlampton** [comment]
Or, okay :)
