### ISSUE TITLE
Disable region HEADER for authorized users

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2079]
Hi!

Please, could you give me the code which will disable region header for for authorized users?
I need header to be visible only for people who are not loged in.

I do understand this code should be placed in page.tpl file.

I know it should look may be something like this:

```
global $user;

if ( $user->uid ) {
    print DO SOMETHING FOR LOGGED IN USERS
}
else {
    print DO SOMETHING FOR ANON USERS
}
```

Thank you!

**Comment by klonos** [comment]
Have you tried doing this through the Layout UI? You can set the visibility condition of all blocks contained in the header region to "User: Role" and then select "Anonymous". That should make the header region empty when viewed by registered and logged-in users thus not render it at all.

**Comment by bd0bd** [comment]
Thank you!
I would like to make it directly in page.tpl file of Bartik.

**Comment by bd0bd** [comment]
Solution:

<?php if (!$logged_in): ?>

  The code of header region here

<?php endif;?>
