### ISSUE TITLE
Fix small issues with responsive tabs

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2083]
Also make webfont loaded detection generic.

Making this issue for code I've already written :stuck_out_tongue:

**Comment by wesruv** [comment]
PR Here: https://github.com/backdrop/backdrop/pull/1492

**Comment by quicksketch** [comment]
Looks pretty good! I left a few items of feedback that need to be addressed in the PR as code comments: https://github.com/backdrop/backdrop/pull/1492.

**Comment by quicksketch** [comment]
I made a new issue today for splitting out Responsive Tabs JS in https://github.com/backdrop/backdrop-issues/issues/2105. If we make both this change and split out responsive tabs, Seven won't have a `script.js` file at all any more. :smile:

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1492 after @wesruv's recent updates. Excellent! Thanks this will be in 1.4.5.

**Comment by quicksketch** [comment]
After seeing this in action for a few days I ran across a bug where the font checker wasn't hidden while it was waiting for the font to load. Fixed in a follow-up commit at https://github.com/backdrop/backdrop/pull/1511.
