### ISSUE TITLE
Remove reference to  hook_image_default_styles() from hook_image_styles_alter()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2087]
In the docblock for `hook_image_styles_alter()` we still have a reference to a function that has been removed from Backdrop, `hook_image_default_styles()`. We should remove this.

**Comment by jenlampton** [comment]
Here's a good one for you @docwilmot :)

**Comment by quicksketch** [comment]
Trivial fix. Merged into 1.x and 1.4.x.
