### ISSUE TITLE
[UX] Improve the error messaging around why installer module won't install.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2093]
When you have a permissions problem with your server, the error you get on the installer page is 

```
Failed to install one project.
```

When you check the logs to find out why you get the following:

```
There was an error while installing Social field. Permissions are not set up properly.
```

[UX] I recommend that we take this second, slightly more useful error and place it on the installer page for the user. 

[DX] I would also like to add something a developer might find useful into the logs. Something like "Could not write file to disk" so we know it's a write problem, or  "could not execute files..." if it is an execute problem. This generic nondescript log message has me guessing at what permissions need to be set, and failing :(

---

PR by @daggerhart https://github.com/backdrop/backdrop/pull/1884

**Comment by Steve-A-Orr** [comment]
From the project home page, clicked the "Spin up on Pantheon" button and successfully installed site. Then, attempted to use the "Add to installation queue" module feature--got this problem immediately (having to look at log report for actual error). One would think that an automatic installation process would take care of permissions for a good "out-of-the-box" experience.

Your suggestions would've improved my understanding of the issue.

**Comment by Steve-A-Orr** [comment]
Found the source of my problem...it was a Pantheon issue. Gave detailed solution in other issue.  #2581  

I don't know if BackDrop would be able to provide an appropriate error message for my problem--but documentation on the BackDrop installation page could.

**Comment by herbdool** [comment]
I've reviewed the PR and it looks good. That is, I've read the code changes and took a look at the screenshot of the output. I'm not sure how to test it on the spun up site but it's a pretty concise PR so I think it's safe.

**Comment by jenlampton** [comment]
+1 on RTBC from me as well. Nice job :)

**Comment by quicksketch** [comment]
Excellent, thanks for the PR and reviews folks! Merged https://github.com/backdrop/backdrop/pull/1884 into 1.x and 1.6.x
