### ISSUE TITLE
[DX] Installer module should place modules in 'contrib' if it exists

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2094]
I notice that when I use installer module it places modules directly into the /modules directory, even if I have a /contrib and a /custom in there. This mucks up my organization!  I would like installer module to work like drush, and first check for a /contrib directory, and then write the modules (or themes, or layouts) into there if it exists.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2246

**Comment by klonos** [comment]
I think we had an issue about this before (or was it about shipping core with pre-existing `/contrib` and `/custom` directories under `/themes`, `/modules` and `/layouts`). Now that you mention drush the request makes more sense.

**Comment by serundeputy** [comment]
@klonos that is issue https://github.com/backdrop/backdrop-issues/issues/1996

**Comment by klonos** [comment]
Doesn't seem to work @quicksketch ...tested via Project Browser/Installer and modules/themes/layouts seem to be downloaded/extracted into the respective directories under docroot.

**Comment by herbdool** [comment]
This works for me testing locally for modules, themes and layouts. @quicksketch 

@klonos it expects that you've created the contrib directory otherwise it will download in the regular location.

**Comment by quicksketch** [comment]
Thanks @herbdool once again for reviewing! Merged https://github.com/backdrop/backdrop/pull/2246 into 1.x and 1.10.x.
