### ISSUE TITLE
Installer module can not install new releases

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2095]
As reported in https://github.com/backdrop-contrib/basis/issues/33 it looks like the project module is unable to extract themes while installing.

**Comment by jenlampton** [comment]
Looks like this is related to the fix we issued for the packager. All new releases will have this problem (not just themes).

**Comment by quicksketch** [comment]
This has been fixed in the BackdropCMS.org issue queue. It was an issue with the packager creating release nodes. The packages on GitHub were fine, but we were linking to the wrong zip file. More details posted to https://github.com/backdrop-ops/backdropcms.org/issues/264#issuecomment-242613068.
