### ISSUE TITLE
Fix some issues with sticky table headers

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2098]
Some issues came up while making basis because I did these witty drag handles:
![image](https://cloud.githubusercontent.com/assets/5607236/17985566/64aae290-6ae4-11e6-8563-221bc2945302.png)

This fixes that issue and I think improves this functionality generally.

**Comment by quicksketch** [comment]
Thanks, I took a look at the PR and it looks good from a code standpoint. I couldn't find any difference in behavior before/after this change in Seven or Bartik (which is good). I did run across another issue however: on narrow screens the table header gets offset if the table doesn't have enough room *and* you're horizontally scrolled to the right:

![2016-08-25 21 25 14 036](https://cloud.githubusercontent.com/assets/100206/17994091/b8f4ba08-6b0a-11e6-9c4d-66f16c63c7f4.gif)

But this issue exists before and after the PR.

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/pull/1499 because it looked good and solved the immediate problem. If you're interested in solving this new issue, feel free to file another PR against this issue. Otherwise we should make a new one and reference this discovered problem.
