### ISSUE TITLE
[UX] in Views UI 'Users' have not completely been renamed to 'User accounts'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2100]
When creating a view using the views wizard you select 'Users' from the first select list, not User accounts. 

---
PR from @klonos at https://github.com/backdrop/backdrop/pull/1516

**Comment by klonos** [comment]
Are you talking about just changing the UI text (drop-down) or also underlying code (functions, php files, classes, tables etc.)?

**Comment by jenlampton** [comment]
UI-only.

**Comment by klonos** [comment]
OK then, I'll give this a go...

**Comment by klonos** [comment]
Still needs some work. There's more than just the Views UI I think. There's some permissions too that will need renaming for example. I would appreciate an initial review to see if I'm in the right path in general, but I wont be able to come back to this until tomorrow perhaps.

**Comment by klonos** [comment]
...tests come back all green. Which again makes me worry about coverage. I mean, usually any UI text changes I make have a lot of test failures - not used to seeing everything green 😛

**Comment by jenlampton** [comment]
@klonos this looks like a great first start!  I'm not sure View Ui is that heavily tested for users since that's a less common use case than for nodes, so I wouldn't be too alarmed by green tests ;)

**Comment by klonos** [comment]
OK @jenlampton, I think I've addressed all your comments for change. Only UI text changes, so should come back green again. Switching to NR again. Feel free to mark RTBC if you think it's ready now.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1516 into 1.x for 1.5.0. Thanks @klonos!

**Comment by jenlampton** [comment]
I was *about* to mark this RTBC.!

**Comment by jenlampton** [comment]
:)
