### ISSUE TITLE
Add the ability to insert/attach the output of a view inside content.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2102]
@jenlampton I really love what you did with the "shinny happy faces" in https://backdropcms.org/leadership 👍!!!

Can we make this a core feature please so that people do not have to re-edit content each time that some data is updated. In this case, we could have a "PMC member" role for b.org users, create a view that spits their photo and link to profile page and have that in a (responsive) grid view. Then we could for starters provide a [view:pmc-members:grid-display] token that people could insert in the body field (or any rich text field really). Finally, we could provide CKeditor integration so that people can click a toolbar button to browse for and enter a dynamic, views-provided output and also provide a modal to edit/configure it.

**Comment by jenlampton** [comment]
Using a role for this is not a great idea because we don't actually need
special permissions for all these people. (Or at least, not yet). That
said, I do have a view for this (with more/better info, actually) but
stopped short of the token. I agree it would be a good idea :)

I'm not sure this sounds like a core use case to me, it's a bit edge-casey.
But a views-token module with creditor integration would be a great idea
for contrib! Anything like that exist for Drupal?

**Comment by Al-Rozhkov** [comment]
There is [Insert View](https://www.drupal.org/project/insert_view) module. It allows to embed views in any rich text field. But it doesn't have CKeditor integration.

**Comment by klonos** [comment]
> Using a role for this is not a great idea because we don't actually need special permissions for all these people.

Fair enough. It was just an example - we can use tags or something.

> I agree it would be a good idea :)

Hence this issue 😉 

> Anything like that exist for Drupal?

As @Al-Rozhkov mentioned, https://www.drupal.org/project/insert_view seems to be the go-to module for achieving such a thing. You can also use https://www.drupal.org/project/token_embed_views with https://www.drupal.org/project/token_filter I guess.

As for the WYSIWYG button + modal, there seem to be some contrib modules that do that for entities (https://www.drupal.org/project/token_insert_entity and https://www.drupal.org/project/entity_embed for example), but not with views AFAIK. The later uses standard `<div>` tags instead of token tags `[...]`:

```
<drupal-entity data-entity-type="node" data-entity-uuid="07bf3a2e-1941-4a44-9b02-2d1d7a41ec0e" data-entity-embed-display="entity_reference:entity_reference_entity_view" data-entity-embed-display-settings='{"view_mode":"teaser"}' />
```

There is also an issue against token 7.x (though inactive since 2012): https://www.drupal.org/node/1567962

**Comment by klonos** [comment]
There's this nice video how the WYSIWYG part with the modal of entity_embed works: https://www.youtube.com/watch?v=T26oz9H-VBY

...we could make it work like that, but browse for views instead of entities.

**Comment by jenlampton** [comment]
This might be a bit much for b.org. this is the only page we've needed this
feature on so far. Let's start with embedding the view and hold off on
creditor integration until we're sure this is a common enough use case.

**Comment by klonos** [comment]
> This might be a bit much for b.org.

I've filed this issue against core, so intended to request this as a core views/CKeditor feature that everyone can use on their sites - not just for b.org.

**Comment by jenlampton** [comment]
Still seems like a better fit for contrib to me.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by klonos** [comment]
I won't argue or push this further. Just wanted to note that that might have been the case with the respective involved modules in D7, but in Backdrop both Views and CKeditor are in core. Why not make them interact/integrate better?

**Comment by jenlampton** [comment]
B/c it's not an 80% use case.

**Comment by klonos** [comment]
Fair enough. We have plenty of contrib options in d.org. One or some of them will be ported eventually and people can use them.
