### ISSUE TITLE
[UX] Better messages for user creation/deletion/rename.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2108]
Current messages:

"The role has been added." / "The role has been renamed." / "The role has been deleted."

Lets add the actual role label there like we do for node creation messages for example. Proposed to change these messages to "The `%role_label%` role has been added." / "The `%old_role_label%` role has been renamed to `%new_role_label%`." / "The `%role_label%` role has been deleted."

PR upcoming (I expect tests to fail but will try to fix ASAP)...

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1504~~
PR by @klonos: https://github.com/backdrop/backdrop/pull/1603

**Comment by quicksketch** [comment]
Yep, a couple of failures here but looks pretty close!

```
 Status Group Filename Line Function -------------------------------------------------------------------------------- Exception Notice     user.admin.inc     624 user_admin_role_delete_confirm_subm
Undefined variable: role Exception Notice     user.admin.inc     624 user_admin_role_delete_confirm_subm
Trying to get property of non-object ---- User: User role administration (UserRoleAdminTestCase) ---- Status Group Filename Line Function -------------------------------------------------------------------------------- Fail      Other      user.test         2086 UserRoleAdminTestCase->testRoleAdmi
The role has been added. Fail      Other      user.test         2100 UserRoleAdminTestCase->testRoleAdmi
The role has been renamed. Exception Notice     user.admin.inc     624 user_admin_role_delete_confirm_subm
Undefined variable: role Exception Notice     user.admin.inc     624 user_admin_role_delete_confirm_subm
Trying to get property of non-object Fail      Other      user.test         2127 UserRoleAdminTestCase->testRoleAdmi
The role has been deleted
```

**Comment by klonos** [comment]
I tried to improve the code/messages and fix the tests but raised the test failures to 175! ...could be that the patch was filed before the 1.5.0 and there might be changes I have not accounted for. Will file a separate PR shortly...

**Comment by klonos** [comment]
...new PR: https://github.com/backdrop/backdrop/pull/1603

**Comment by klonos** [comment]
Hmm, funny... initially the php70 test came back green, but php53 had a failure that seemed random. I restarted the test trough the zen.ci UI and this time the php53 test came green, but now the php70 test seems to be stuck at "in full swing" status. Clicking the "details" link next to the php70 test 404s. I noticed that there seems to be a `-1` appended to the URL, if you remove that and visit https://zen.ci/backdrop/backdrop/test/test-php70-backdrop_backdrop_1603-2e43e12 instead, it shows the php70 test green.

@Gormartsen can you please look into that??

@quicksketch I know that closing and reopening it would restart all tests and they'd be green, but did not do so because perhaps @Gormartsen might wanna take a look at this strange hiccup first. So, other than that, I think that the PR is good for review.

**Comment by klonos** [comment]
...the issue with the zen.ci acting up has been previously reported in https://github.com/backdrop-ops/backdropcms.org/issues/276 but it was the opposite situation where the php53 test was stuck.

**Comment by klonos** [comment]
All tests are green!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1603 for 1.5.1. Thanks @klonos!
