### ISSUE TITLE
Why do we hide the "Machine name:" label for user roles?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2110]
We show it in other places like the new content type form:

![backdrop-machine_name_label-new_content_type_form](https://cloud.githubusercontent.com/assets/2423362/18127956/d26a4474-6fc6-11e6-8a6e-aaf42bd33cc2.png)

...the new view form:

![backdrop-machine_name_label-new_view_form](https://cloud.githubusercontent.com/assets/2423362/18128029/215f8fe4-6fc7-11e6-8fad-9b55bf665a5e.png)

...but not for new user role field:

![backdrop-machine_name_no_label-new_user_role_field](https://cloud.githubusercontent.com/assets/2423362/18127972/e1755cba-6fc6-11e6-9811-8630fbd0b239.png)

Is that intentional? If not, then PR coming up...

**Comment by klonos** [comment]
Trivial change. All tests are green.

**Comment by quicksketch** [comment]
Thanks @klonos, indeed trivial and a head scratcher. We could argue about the friendliness of "Machine name", but if so it should be a core-wide change. This adds consistency with what we're already doing everywhere else.

Merged https://github.com/backdrop/backdrop/pull/1506 into 1.x and 1.4.x, thanks!
