### ISSUE TITLE
Add "Export" link to drop-button for layouts.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2116]
The Views UI provides a drop-button that takes users directly to the single-item-export UI under Config Mgmt. We should do the same for other exportables, especially layouts.

**Comment by olafgrabienski** [comment]
Closing as duplicate of #2960.

**Comment by olafgrabienski** [comment]
Reopening (wanted to close another issue, not this one).

**Comment by jenlampton** [comment]
trying to reopen again :)

**Comment by jenlampton** [comment]
There's a commit for this issue on the pr on https://github.com/backdrop/backdrop-issues/issues/2960, so closing as duplicate again.
