### ISSUE TITLE
[UX] Update button text for inserting an image into the rich-text editor

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2124]
The modal for inserting an image into a rich text editor says `Save` on the submit button. This is misleading as nothing is saved when this button is pressed. `Insert` would be a better label for this button.

Before:
![screen shot 2016-09-02 at 11 55 04 pm](https://cloud.githubusercontent.com/assets/397895/18223318/bb0ea452-7168-11e6-93cb-ca21ba3f667d.png)

After:
![screen shot 2016-09-02 at 11 54 23 pm](https://cloud.githubusercontent.com/assets/397895/18223320/c0c0033c-7168-11e6-8f44-8e98749a1133.png)

**Comment by klonos** [comment]
Trivial UI text change. 👍 

...although that change not triggering test failures is worrisome (missing tests - nothing to do with this issue though) 😄

**Comment by quicksketch** [comment]
This introduces an inconsistency in labels when editing an existing image:

![selection_176](https://cloud.githubusercontent.com/assets/100206/18227935/56f97612-71eb-11e6-90b9-64c4b8d9bc0a.png)
![selection_177](https://cloud.githubusercontent.com/assets/100206/18227936/5b0a4092-71eb-11e6-8044-b0d5e7bb5239.png)

**Comment by jenlampton** [comment]
Ah good catch. We can use the same logic we do for the titles as we do for the buttons. And the same text! :)

**Comment by olafgrabienski** [comment]
Shouldn't it be as follows?

**Title / Button**
Insert image / Insert
Edit image / Save

**Comment by jenlampton** [comment]
Maybe Edit image / Update, as saving happens when you save the thing. Not when you push that button.

**Comment by olafgrabienski** [comment]
Sound good!

**Comment by klonos** [comment]
Yep, "Insert image" -> "Insert" and "Edit image" -> "Update" 👍

**Comment by klonos** [comment]
How about this?

**Comment by klonos** [comment]
...taking some things off of @serundeputy's plate. Let real noobs deal with novice issues 😛

**Comment by klonos** [comment]
...tests came back green. Not sure if the approach is the right/optimal one.

**Comment by jenlampton** [comment]
@klonos that looks great!  It's exactly what I would have done :D

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/1515 into 1.x and 1.4.x. Thanks!
