### ISSUE TITLE
[UX] Improve help text on "Update modules" page

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2128]
The help text regarding updates of Backdrop core is:

> **Manual updates required**
> Updates of Backdrop CMS core are not supported at this time.

Let's specify the text of the sentence:

"Updates of Backdrop CMS core **via this page** are not supported at this time."
(Don't know if "via" is good English.)

We should also add a link to the update documentation (for the time being https://backdropcms.org/upgrade).

---
PR by @olafgrabienski: https://github.com/backdrop/backdrop/pull/1635

**Comment by olafgrabienski** [comment]
Forgot to mention the path of the page where the message appears:

It's on **Administration > Functionality > Update modules**, URL path: `admin/modules/update`.

**Comment by olafgrabienski** [comment]
Related: [[UX] "Available updates" page doesn't link to "Update modules" page](https://github.com/backdrop/backdrop-issues/issues/2315)

**Comment by olafgrabienski** [comment]
> "Updates of Backdrop CMS core via this page are not supported at this time." (https://github.com/backdrop/backdrop-issues/issues/2128#issue-174904615)

@ native English speakers: What do you think about the phrase above? Is "via" good English in this case? Other suggestions?

**Comment by klonos** [comment]
"via" is just fine, but if we want to use more "plain" English, we can say "from" instead. How about this:

> Updates of Backdrop CMS core using the web interface are not supported yet.

If we want to be precise, we should use "possible" instead (because using "supported" might imply that there is a way to achieve that, but it is not officially recommended).

...not a native speaker per se, just my 2c.

**Comment by olafgrabienski** [comment]
Thanks @klonos , good suggestions in my opinion! New proposal:

> Updates of Backdrop CMS core using the web interface are not possible yet.
> 
> Learn how to update Backdrop CMS downloading the latest release and putting the new "core" directory inside your docroot: [Developer Guide > Upgrading Backdrop CMS](https://backdropcms.org/upgrade)

When we link to the documentation, we should make sure that URLs are redirected in case they change in the future. @jenlampton Are there automatic redirects on backdromcms.org?

**Comment by klonos** [comment]
> When we link to the documentation, we should make sure that URLs are redirected in case they change in the future. ...@jenlampton Are there automatic redirects on backdromcms.org?

I can answer that. Yes they are enabled, so the documentation nodes in b.org will always get a proper redirect 😉

**Comment by klonos** [comment]
Great idea to add help as to what the user needs to do @olafgrabienski (Instead of simply tellig them what they can't do). ...new iteration:

> Updates of Backdrop CMS core using the web interface are not possible yet.
> 
> You can update Backdrop CMS by replacing the old `/core` directory inside your docroot with the one included in the [new version](). To learn more, see the [Developer Guide > Upgrading Backdrop CMS](https://backdropcms.org/upgrade) document online.

The "new version" link should ideally always point to the latest release (https://github.com/backdrop-ops/backdropcms.org/issues/298) the https://github.com/backdrop/backdrop/releases/latest link works to always point to the latest release page, but https://github.com/backdrop/backdrop/releases/download/backdrop.zip doesn't work to point to the latest actual download file. Hmm.

**Comment by jenlampton** [comment]
why not just point them at the home page?

**Comment by olafgrabienski** [comment]
> why not just point them at the home page?

Well, if we can provide links to the proper pages, users don't have to search for them. Do you raise concerns over providing the documentation link or the release link, or both of them?

**Comment by jenlampton** [comment]
The release link, since we can't provide an accurate and never-changing one.

The Download button will always be accurate on the home page. No need to
search for anything there!

**Comment by olafgrabienski** [comment]
Sure, the big download button! Didn't have that in mind, sorry.

So, new suggestion, consisting of the last iteration's wording (thanks, @klonos), but with release link to the home page:

> Updates of Backdrop CMS core using the web interface are not possible yet.
> 
> You can update Backdrop CMS by replacing the old `/core` directory inside your docroot with the one included in the [latest release](https://backdropcms.org/). For detailed instructions, see the [Upgrading Backdrop CMS](https://backdropcms.org/upgrade) document online.

**Comment by olafgrabienski** [comment]
The PR looks fine in the test environment:

![screen-backdrop-pr-for-2128-help-text-update-modules-page](https://cloud.githubusercontent.com/assets/14188307/19987666/a8990288-a21c-11e6-86ef-8b6755891072.png)

Tests passed initially. When I edited the PR to remove redundant `<p>` tags, "some checks were not successful", but I guess that's not related to the PR.

**Comment by serundeputy** [comment]
the php7 tests passed. php53 had errors usually that is random failures; I've restarted the php53 tests.

**Comment by klonos** [comment]
> the php7 tests passed. php53 had errors usually that is random failures; I've restarted the php53 tests. 

And when you do that, https://github.com/backdrop-ops/backdropcms.org/issues/276 happens. You can see in the PR in question that the php70 test is now in an endless "in full swing" state (because an extraneous `-1` has been added to the "details" link).

**Comment by olafgrabienski** [comment]
@klonos I remember vaguely that you once discussed which milestone to give to a PR like this one but don't remember the answer. Do you?

**Comment by klonos** [comment]
There is a very fine line for me personally when a UX improvement is a bug or not and I tended to mark all UX-related issues as bugs. Unless it is a really obvious bug, I now tend to not define a milestone. If it is a bug fix, then the milestone is the next bug fix release (which now is 1.5.2).

Reason why I avoid setting the milestone now is basically because when I used to do so, it might not have been a totally right call. In such cases, I had someone (usually @jenlampton) correct that by either removing the milestone entirely or pushing it to another, future milestone. This reminded me of the way people were abusing the priority tags (major, normal, minor etc.) in the d.org issue queue and how either me or somebody else would come and correct it. It was called "tag wars" and it would waste people's time. I don't want to be doing that to our queue because I'm sure that @jenlampton has way better things to do with her time 😄

**Comment by olafgrabienski** [comment]
Thanks @klonos ! Actually, I didn't even want to mark this issue as a bug. In my eyes, the proposal isn't a bug fix but an improvement. (So "type - task" as label?) However, I guess improvements can be committed as well, but to which releases? Is somewhere a document which answers such questions?

**Comment by serundeputy** [comment]
@olafgrabienski 
> I guess improvements can be committed as well, but to which releases? Is somewhere a document which answers such questions?

* Improvements that are [UX] or [DX] with no functionality change, i.e. changing a string of help text on a field (may require updating of existing tests) can go into any release bug fix, minor release or major release.  So an increment from `1.5.1` to `1.5.2` for example could fit this example.

* Improvements that require a change in functionality and therefore new tests for that functionality wait for a minor release.  This would be an increment for example of the middle number like from `1.5.1` to `1.6.0`.

* Improvements that change/break an API that downstream developers are relying on in contrib or custom modules in Backdrop sites require a major release from `1.x.y` to `2.0.0`.

The whole thing is based on http://semver.org/ model.

So, I would say that this issue #2128 can go in at any time once it is Reviewed and Tested by the Community (RTBC).  The major factors in an issue like this are agreement on the change, passing tests, and someone(s) reviewing and setting as RTBC.

I hope that helps.

~Geoff

**Comment by serundeputy** [comment]
@olafgrabienski here https://www.youtube.com/watch?v=38tVPGVlFR0 at approximately 43.06 is a much more elegant and technical debrief (thanks @quicksketch ) on what is allowed in minor releases.

**Comment by klonos** [comment]
I wonder if your explanation @serundeputy + @quicksketch's "elegant and technical debrief" should be incorporated in https://backdropcms.org/releases ?

**Comment by serundeputy** [comment]
That is more or less what is on that page.  Maybe we could improve on presentation of that info?  For example leading with `Version Numbers` and `Branch Management` takes a lot of space and is not necessarily for the average user.

Perhaps move those two sections on the end to focus on our commitment to backwards compatibility when possible and correlate that to planning and lower cost dev based on predictability?

Not sure just spitballing  ... but we are going offtopic ... sorry @olafgrabienski are we in consensus on the wording of @olafgrabienski `PR`?  Can we get a RTBC tag?  I'm confident that the tests in PHP7 are random fails.

**Comment by klonos** [comment]
> Can we get a RTBC tag? I'm confident that the tests in PHP7 are random fails.

Yes they are, and yes, RTBC.

**Comment by klonos** [comment]
@olafgrabienski if you have access to edit the summary (first comment) of issues that you file PRs for, we usually edit them and add a `---` at the end that adds a vertical line and then link to the PR so that reviewers can find it easily. Done that for you for this issue 😉

**Comment by klonos** [comment]
@serundeputy I've added your explanation to that page as a "plain English" section right below the semver numbers in the "Version Numbers" section 😉

**Comment by olafgrabienski** [comment]
@serundeputy Thanks a lot for the clarification, very helpful! I've got one question though, regarding the "type" labels: In which case do we use "type - task"?

**Comment by olafgrabienski** [comment]
@klonos ... Thank you for reviewing, and thanks for indicating the "PR link in the first comment" practice. Such a link at the top of issues is indeed a nice service.

Maybe it's even better to not put the link below the text of the first comment but at the very top. Because, if the link is below the first comment, and that text suggests a certain solution, the combination could create the impression, that the PR follows the suggestion of the first comment, which is often not the case.

So what about just changing the order? Like this:

```
PR by @...: backdrop/backdrop#...

---

Text of first comment ...
```

**Comment by olafgrabienski** [comment]
> I've added your explanation (slightly edited in order to match the context) to that page as a "plain English" section right below the semver numbers in the "Version Numbers" section 

Good idea! To match the context of the page even better, I propose to use different version numbers in the explanation, e.g. instead of "from 1.5.1 to 1.5.2" write "from 1.2.4 to 1.2.5".

**Comment by serundeputy** [comment]
> @serundeputy I've added your explanation (slightly edited in order to match the context) to that page as a "plain English" section right below the semver numbers in the "Version Numbers" section 😉

* Thanks I think it is good.

> @serundeputy Thanks a lot for the clarification, very helpful! I've got one question though, regarding the "type" labels: In which case do we use "type - task"?

* I'm not sure that we have formal definitions for the labels.  @jenlampton would know better than I, but I think that the label `type - task` is basically used when the change/improvement is defined and just needs implementation.

Thanks @olafgrabienski !  Looks great! this is merged into `1.x` and `1.5.x` and will ship with `1.5.2`.   Nice work everyone! 💯
