### ISSUE TITLE
Move file entity info, managed file, and file usage functionality into File module

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#213]
Drupal.org issue: https://drupal.org/node/1468328

File module used to be an optional module, with the "required" portions living in System module. However File module has been required for all the D7 cycle. We should move the relevant file functionality out of System and into File.

----

PR by @Al-Rozhkov https://github.com/backdrop/backdrop/issues/1829

**Comment by jenlampton** [comment]
Also related https://github.com/backdrop/backdrop-issues/issues/2375

**Comment by quicksketch** [comment]
This definitely isn't going to happen for 1.6.0. Moving to next release.

**Comment by klonos** [comment]
This would make the file.module a required one. Correct?

**Comment by Al-Rozhkov** [comment]
PR: https://github.com/backdrop/backdrop/pull/1829

Please, review.

**Comment by klonos** [comment]
@Al-Rozhkov above my skillset for review, but what about my question above? Do you think that file becomes a required module now?

**Comment by Al-Rozhkov** [comment]
To be honest this is above my skills too. I just really want media library in Backdrop core and I try to learn as much as possible to make it happen. Backdrop is so much better than WordPress in all aspects except for file management.

As far as I understand things File module needs to be required. Looks like some parts of System and User modules use File module.

I disabled File module and discover few things.

![manage-files-page](https://cloud.githubusercontent.com/assets/16973264/25001860/75ed18fa-2058-11e7-80f4-4ada8be9070f.jpg)

1. Manage files page is still there but views handler is missing.
2. "Insert image" functionality still exist in text editors (without Image and File modules).

While I was writing this comment I realized that my PR doesn't add `required = TRUE` to the File module. So back to "needs work".

**Comment by Al-Rozhkov** [comment]
The more I dive into it, the more I think that we can keep File module unrequired :)

I thought that user pictures dependent on Image module, but looks like it is not. There is simple `if (module_exists('image'))` check.

All file related API exist in `core/includes/file.inc` and File module is for file entities, file usage and file field functionality.

**Comment by quicksketch** [comment]
Excellent work @Al-Rozhkov! I can help fix the failing tests.

It seems like making File module required would be a pretty minor concern, but I'll check what's needed to just get tests passing.

**Comment by Al-Rozhkov** [comment]
Thanks a lot @quicksketch! It would be great. I know nothing about test yet.

**Comment by jenlampton** [comment]
I also like the idea of having file module be required, actually. I think that's a non-issue either way.  Good work everyone (especially @Al-Rozhkov) on moving this issue forward!  :)

**Comment by quicksketch** [comment]
Hm, yeah on further examination here's the issue most tests are running into:

- Saving any type of content that contains filtered text.
- The filtering then parses for file IDs with `_filter_record_file_usage()`.
- In the act of saving file usages, a new `File` object is created.

So making this change means that effectively `filter.module` becomes dependent on `file.module`.

Other places like `block.module` have bits of code like this:

```php
  // Save each file as permanent, preventing it from being deleted. The same
  // process is used in Layout::save(), but that only applies to non-reusable
  // blocks (BlockText objects). If a block has been marked reusable, the files
  // are immediately marked as permanent.
  // File usages are not currently removed for custom blocks.
  // See https://github.com/backdrop/backdrop-issues/issues/2137.
  $fids = filter_parse_file_fids($block['body']['value']);
  $files = file_load_multiple($fids);
  foreach ($files as $fid => $file) {
    if ($file && $file->status !== FILE_STATUS_PERMANENT) {
      // This makes the file "self-referencing", so it will never be deleted.
      file_usage_add($file, 'file', 'file', $file->fid);
    }
  }
```

So again this is assuming the API for File "usages" is always available. From a backwards-compatibility standpoint, I think we need to make sure it remains that way.

**Comment by quicksketch** [comment]
@Al-Rozhkov Could you add the following line to `file.info` and push to the PR?

```
required = TRUE
```

**Comment by Gormartsen** [comment]
Just commit this to your repo, that a source for PR.
PR will be synced and test run again.

Regards,
Gor Martsen
@gormartsen

**Comment by Al-Rozhkov** [comment]
Thank you everyone! It is so exciting to learn git and Backdrop!

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/1829 into 1.x for 1.7.0. Great job @Al-Rozhkov!
