### ISSUE TITLE
[UX] Update block modal button to say 'Update' instead of 'Save'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2133]
This occurred to me after submitting https://github.com/backdrop/backdrop-issues/issues/2124...

The button on modals for configuring Blocks currently says `Save block`. That's likely going to cause people to think that after they click it they will be done, but in reality they _also_ need to save the layout. If we updated the block button text it may be less misleading.  How about 'Update block' for configuring an existing one?

![screen shot 2016-09-03 at 8 09 02 pm](https://cloud.githubusercontent.com/assets/397895/18228796/bb757402-7212-11e6-9977-4f43134ed725.png)
(As a side note, adding blocks already says "Add  block" instead of save, good job 👍 )

**Comment by quicksketch** [comment]
Not sure "Update" is a whole lot better than "Save", but it is a little better. Sounds good to me.

**Comment by jenlampton** [comment]
I think that you're right, a lot of people won't know the difference between the two meanings (or what we are using them for). But if we are at least consistent about "If you click Update then you also need to click another button" and "If you click save then you are done doing whatever it was." It will become intuitive to people faster.

**Comment by Graham-72** [comment]
With PR https://github.com/backdrop/backdrop/pull/1678 I have made the change from `Save block` to `Update block` and modified all the test files. On the most recent run the PHP53 tests passed but there was a failure in PHP7 tests that I do not understand, and I can do no more on the PR.

**Comment by klonos** [comment]
> ... but there was a failure in PHP7 tests that I do not understand

Not your fault @Graham-72... #2202 😉

**Comment by Graham-72** [comment]
@klonos thanks for your reassurance.

**Comment by klonos** [comment]
> But if we are at least consistent about "If you click `Update` then you also need to click another button" and "If you click `Save` then you are done doing whatever it was." It will become intuitive to people faster.

That 👍 ...eventually I would like us to come up with a solution that communicates that "Not saved yet" message in a better way (that stays within the user viewport until either 'save' or 'cancel' are specifically pressed).

**Comment by quicksketch** [comment]
Thanks @Graham-72 for the PR! Sorry about that random failure, it's really been quite the headache.

I've merged https://github.com/backdrop/backdrop/pull/1678 into 1.x and 1.5.x. Thanks!
