### ISSUE TITLE
Update documentation for managed file element

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2140]
Our managed file elements now auto-upload. We should update these docs to reflect that:
`By default a simple upload button is provided for choosing the file to upload. Once a file has been chosen it can be explicitly uploaded via the "Upload" button. The upload is via AJAX and a progress meter is displayed. The form's validate and submit handlers receive a file object ID in $form_state['values'] that represents the ID of the new file in the {file_managed} table.`

**Comment by BWPanda** [comment]
I've updated the documentation for the managed_file element: https://docs.backdropcms.org/form_api#managed_file

Since the Docs site now uses regular nodes for Form API documentation, further changes can just be made there directly.
