### ISSUE TITLE
Add back the missing ckeditor link/unlink/anchor buttons

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2142]
In the latest version of Backdrop the link/unlink/anchor buttons are missing. This is because we pulled Drupal 8's compiled version of CKeditor, and Drupal 8 uses their own link plugin, so has removed the default.

Is it time to start rolling our own compiled version of the CKeditor library?  Let's document here the steps to follow to get an adequate version of CKeditor for Backdrop.  We can follow this recipe every time the editor needs to be updated so we don't accidentally remove features people know and love.

**Comment by quicksketch** [comment]
I have no idea how/why our link buttons were removed from the default format. That is just crazy. I'll whip up a PR for this one.

**Comment by quicksketch** [comment]
Backdrop already includes link buttons and they are supposed to be enabled by default. You can still enable them manually after install, but the fact that they are missing on new installs is a bug. As shown in the PR, https://github.com/backdrop/backdrop/pull/1527, we just omitted the word "Backdrop" from the button names, they're already supposed to be positioned in the default toolbar.

**Comment by quicksketch** [comment]
Much better!

![screenshot from 2016-09-08 22-59-55](https://cloud.githubusercontent.com/assets/100206/18376909/0706dff6-7618-11e6-8bbd-3ea7d023d91d.png)

**Comment by jenlampton** [comment]
Hooray, the links are back :) RTBC from me.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.4.x.
