### ISSUE TITLE
Installer layout columns slightly borked on 1.x

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2143]
![bork](https://cloud.githubusercontent.com/assets/397895/18336668/f253c4b4-753d-11e6-93b4-0ef87aa89543.png)

**Comment by quicksketch** [comment]
This had been broken a few days ago after #2122, but it has been fixed. I think you might be using the old stylesheet, perhaps shift-reload while in the installer and then install? Screenshot from 1.x in Chrome:
![selection_182](https://cloud.githubusercontent.com/assets/100206/18337025/d236832a-7541-11e6-8f47-85805388e04c.png)
Firefox:
![selection_183](https://cloud.githubusercontent.com/assets/100206/18337035/e6e71938-7541-11e6-9838-cd1fb9fbfaee.png)

**Comment by jenlampton** [comment]
yep. fixed.
