### ISSUE TITLE
[DX] Put something searchable into failed test results

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2151]
When you're running a test with 1000+ rows of test results, one of which is a fail, finding that fail in the report can be very hard. If we added some specific text into the line where the failure appears, something like "FAIL", then developers could use the browser's "Find on page" feature to locate the line with the "FAIL". The red/green coloring is nice, but it's not enough. We need something better.

I was initially thinking of adding some kind of JS utility that would allow a "jump to next failure" button, but I think just adding some searchable text on the page would still be a huge improvement.

---
PR from @jenlampton https://github.com/backdrop/backdrop/pull/1657 simple string
PR from @docwilmot https://github.com/backdrop/backdrop/issues/1643 fancy step-through

**Comment by klonos** [comment]
Great idea and 👍 on making it so that we take advantage of the in-built search functionality of browsers. You are talking about the long list of test results from travis/zen-ci, right?

**Comment by docwilmot** [comment]
Decided to have some fun:
- Added JS which scrolls to the next failed test on hitting the ENTER key
- Added "Simpletest failed" to all fails to allow browser find/search


![simplets](https://cloud.githubusercontent.com/assets/1042283/20238727/dd00054a-a8bf-11e6-9226-305d3a073d2b.PNG)

**Comment by docwilmot** [comment]
I assume the appropriate key to press and the best string to search will be up for discussion, comments welcome.

**Comment by quicksketch** [comment]
Wow neato @docwilmot! This will be a great improvement. I like the JS overall, but the enter key seems like that may break accessibility features of the browser as the enter key is used for clicking links, opening/closing menus, submitting forms, etc. We don't have any keyboard shortcuts in Backdrop currently (outside of CKEditor). This might set a precedent for shortcuts.

Another shortcut-less option would be an absolutely positioned element at the bottom of the screen, then you could click the link to jump to the next fail (and as a side-effect of being a link, subsequent "enter" key presses would also click the link).

Overall though, I think @jenlampton's very simple suggestion might be the best one, just add a string on which failures can be matched. Although "Simpletest failed" will work, it might be more obvious if it were prepended as `PASS: ` or `FAIL: ` on each line, plus it's a shorter string to search for.

**Comment by docwilmot** [comment]
Didnt think the `ENTER` key would pass, but I think I like the ability to key between fails, though. But how about `"Fail (next / previous)"`? Links for the next and previous of course.

> prepended as PASS: or FAIL: on each line, plus it's a shorter string to search for

Note if the string is "Simpletest failed" searching for "fail" would still work. 😄

**Comment by jenlampton** [comment]
Wow @docwilmot you really went all out 👍  All I really need is a string on each record, something like this: https://github.com/backdrop/backdrop/pull/1657

I like your idea for a step-through tool though. Can we get this in first and keep working on it?

**Comment by jenlampton** [comment]
I think the simple fix version could be a candidate for 1.5.3, and then we'd have the benefit for using it on all the testing for 1.6.0, so updating milestone.

**Comment by docwilmot** [comment]
Yes I was going for excessive, and I achieved it I think. I prefer your version. 
One point though is that searching for "FAIL" in your PR wouldnt find exceptions. Thats why my version had the `!= 'pass'` bit. An exception is still a fail.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/1657 looks great and is dead-simple, but is failing a single test. Could that be fixed and resubmitted?

**Comment by jenlampton** [comment]
Fixed, rebased, and pushed a new PR.

**Comment by quicksketch** [comment]
Great thanks! Merged https://github.com/backdrop/backdrop/pull/1657 into 1.x and 1.5.x.
