### ISSUE TITLE
[UX] CSS cleanup for page title 'region'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2153]
The CSS for the page title is a little broken after https://github.com/backdrop/backdrop-issues/issues/952 was merged.

Problems:
* [UX] White region background tells the user "Drop blocks here"
* Beauty: There is an accidental gray background on `.layout-editor-block-content`

![screen shot 2016-09-11 at 4 33 39 pm](https://cloud.githubusercontent.com/assets/397895/18421357/a24f2e60-783d-11e6-9cda-ae542b9f6557.png)

---
PR from @jenlampton https://github.com/backdrop/backdrop/pull/1537

**Comment by quicksketch** [comment]
Yeah this could use another round of design feedback.

> [UX] White background tells the user "Drop blocks here"

Isn't the dashed line the indication of a draggable location? The gray title bar to me indicates "this is a draggable thing", so if we make it gray we might just change the expectation from "this is a droppable" to "this is a draggable". It's neither of those things, so what's the right pattern?

I had experimented with just removing the border entirely, but then the description and configure link looked completely disconnected. So I don't think that will work either.

**Comment by jenlampton** [comment]
> Isn't the dashed line the indication of a draggable location?

yes, and the white background color.

> The gray title bar to me indicates "this is a draggable thing", so if we make it gray we might just change the expectation from "this is a droppable" to "this is a draggable". It's neither of those things, so what's the right pattern?

There are two grays. Instead of using the dark "this-is-draggable" gray I was going to try using the  lighter "this-is-content" gray.

**Comment by jenlampton** [comment]
Hm. I'm looking at the code comment that was committed. 

`/* Remove the drop shadow indicating this item is movable */`

There shouldn't have ever been a drop-shadow on the page title area because there shouldn't have been any "content" in that area. See screenshot from before: 

![screen shot 2016-09-11 at 5 21 19 pm](https://cloud.githubusercontent.com/assets/397895/18421661/4a70b536-7844-11e6-8ca3-d44b2fd2ee5e.png)

Here's a screen-shot for the title header that keeps the aesthetic the same as it was before:

![screen shot 2016-09-11 at 5 21 19 pm](https://cloud.githubusercontent.com/assets/397895/18421669/782a7804-7844-11e6-80bf-f4b14acc0044.png)

FWIW, I did try the "middle" gray but it turns out that was the same exact color as the background, so the title disappeared. I'm now leaning this way instead.

**Comment by quicksketch** [comment]
This "middle gray" rings all my color-clashing alarm bells. It bothers me that all the other grays on this page are "warm" but the new gray is "cool" (or neutral). It looks like an accident that they aren't the same colors.

> Also yes, but moreso the white background color.

Ah, you know what the problem was? On my monitor I can't see the white vs light gray *at all*. To me the entire background was all white. If I move my window to my internal laptop screen, I can at least see the difference. The contrast on this page is not high enough. :stuck_out_tongue:

**Comment by quicksketch** [comment]
> This "middle gray" rings all my color-clashing alarm bells. It bothers me that all the other grays on this page are "warm" but the new gray is "cool" (or neutral). It looks like an accident that they aren't the same colors.

Huh, this also isn't so bad now that I've adjusted the contrast on my screen. Let's make sure the adjustments are actually on the same "warmness" of gray with just the brightness adjusted (in the HSB-sense). We'll get a variety of screens (or projectors) displaying this UI that may make color differences more obvious.

**Comment by jenlampton** [comment]
> This "middle gray" rings all my color-clashing alarm bells. It bothers me that all the other grays on this page are "warm" but the new gray is "cool" (or neutral). It looks like an accident that they aren't the same colors.

Well, the "new" middle-gray was the same color as the background of the page... so it wouldn't work. never submitted that PR.

> Let's make sure the adjustments are actually on the same "warmness" of gray with just the brightness adjusted (in the HSB-sense). We'll get a variety of screens (or projectors) displaying this UI that may make color differences more obvious.

Uh...  I'm not entirely sure what you are talking about anymore. There are no new colors added. The current PR looks exactly like it did in Backdrop 1.4.

**Comment by jenlampton** [comment]
I just cleaned up the PR (removed commented out stuff) and double checked to make sure all the block headers were the same color `#e9e8e8;`.  Can you give this another test and see if it still looks funny on your monitor?

**Comment by klonos** [comment]
I think that it looks really good the way it is now 👍

...besides, I don't think we should be spending any more time on this because I'm very confident that the page title will receive additional work soon(ish) and we'd better leave the redesign for after that has happened. I specifically believe that we will:

a) eventually make the page title a proper field and that this will become a proper (draggable too) block anyways.

b) I would also like us to separate the `<h1>` title from the `<title>` HTML tag (#2156), as we currently have these be equal all the time. I'd like to see the `<title>` **only fall back** to whatever the `<h1>` title value is **only when it's empty**.

**Comment by jenlampton** [comment]
@klonos when you say 'now' you mean this latest PR? cause what's in HEAD is currently borked.

a) Making the page title into a block is a 2.x task as it will break all templates in core and contrib. 

b) there is a contrib module (page_title) that handles your request (maybe not a candidate for core? idk), but regardless, it wouldn't affect the layout UI.

So, since neither of those are likely to happen any time soon and HEAD is borked, we should fix this asap.  Preferably before 1.5.

**Comment by quicksketch** [comment]
The adjustments in https://github.com/backdrop/backdrop/pull/1537 look great. I've merged them into 1.x for 1.5.0. Thanks!
