### ISSUE TITLE
[UX] terminology updates for the new content block.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2155]
A follow-up to the fantastic work @docwilmot did on getting the `Existing content` block in to Backdrop 1.5! https://github.com/backdrop/backdrop-issues/issues/1076

The code we are using for this is based on the code in panels, and though some of us love panels very dearly (moi!) , it's UI is the one thing we left behind in Backdrop. One of the troubles with the Panels UI is the unfriendly (but very correct!) wording that's used in various places.  As we port over beloved features from Drupal, I would love it if we could also do a clean-up pass on the user-interfaces these features bring with them.

Some minor UX/terminology nits (that can be fixed at any time)
- [x] The name `Content block` is not descriptive enough to users. Maybe `Embed existing content` or `Embedded content` if we don't want a verb. We need to paint a clearer picture for people who don't already know what this block does.
- [x] Block description is not very descriptive: `Displays a node in a block.`. Let's avoid the word node. How about `Embed existing content as a block onto other pages.`
- [x] Remove `Enter the` from Field label text `Enter the title or NID of a node`
- [x] Remove `of a node` from Field label text `Title or NID of a node`. How about `Content title or ID`. 
- [x] Remove the word node from ` Show node title in block content `. How about ` Show title within block`.
- [x] Clean up the description text `This may cause the node title to appear twice. Select "none" for the block title type if using this option.` How about `May cause the title to appear twice if <em>block title type</em> is not set to "none".`
- [x] Remove the word node from `Link the block title to the node`. How about: `Link the block title to the full-page display of the embedded content.`
- [x] Delete the description `Check this box if you would like the block title to link to the node.`. It adds no value here and clutters the UI.
- [x] Remove the word node from ` Include node links for "add comment", "read more" etc. `.  How about ` Include links to "add comment", "read more" etc. `.

Question: should we remove search search index and search result highlighting from the view modes list?  I think the use-case for embedding those is close to 0%.

---
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1556

**Comment by jenlampton** [comment]
Tagging milestone as 1.5, but that's nice-to-have and not necessary.

**Comment by olafgrabienski** [comment]
I agree with the suggestions, only one point:

> Block description is not very descriptive: Displays a node in a block.. New users won't know what a either a node or a block is yet. How about Embed existing content onto other pages.

If we assume that new users don't know what a block is, some the following suggestions, where blocks are mentioned (as in "How about `Show title within block`") don't make sense.

So I'd prefer to mention blocks in the Block description as well: `Embed existing content as a block onto other pages`

**Comment by jenlampton** [comment]
Sounds good to me, updated parent issue to reflect this suggestion.

**Comment by quicksketch** [comment]
Just for the inverse use-case, I'll point out that experienced site builders and developers may know what a "node" is as it's still in many places where "Content" isn't sufficiently clear enough, so having node in the description even if it's not in the title is good for site builders who are searching for the term "node"in the block search box.

**Comment by jenlampton** [comment]
> so having node in the description even if it's not in the title is good for site builders who are searching for the term "node"in the block search box

Fair enough :) 

Here's what I did: 
![screen shot 2016-09-14 at 7 35 37 pm](https://cloud.githubusercontent.com/assets/397895/18536476/7d62ee8a-7ab2-11e6-808d-f0894a061fad.png)

I addressed all the items in the list above as well as:
* moved all the "title" related questions to the top of the block form
* Content or ID field now shows both the title and ID
* autocomplete now autocompletes on both title and ID

**Comment by docwilmot** [comment]
I prefer the textfield to be at the top since its the main focus, every other field is optional. Otherwise, much better wording.

**Comment by quicksketch** [comment]
Hm, I don't know about the `<strong>` tag in the description. I see what you're doing, trying to associate the visual look of the label and the description text, however this is introducing a new paradigm we don't have anywhere else in Backdrop.

Actually, why do we show this option at all if "Use content title" is selected? Shouldn't we hide it with `#states` and unset the value it in the submit handler if the "Use content title" is selected?

**Comment by quicksketch** [comment]
Moving to needs work just for feedback.

**Comment by jenlampton** [comment]
>  this is introducing a new paradigm we don't have anywhere else in Backdrop.

Do we have a paradigm for LABEL vs VALUE that I should be following? The previous example was using quotes and ems, is that the right way to do it?

**Comment by jenlampton** [comment]
> I prefer the textfield to be at the top since its the main focus

I was thinking about that too initially, but the title drop-down is in the same place on every other block, so after moving it below the Content or ID field, I put it back. Then I realized some of the the checkboxes affected the title too, so I ended up with all of them together.  Taking a step back, the Content or ID field is definitely the LARGEST so I thought that might help offset it not being the first?  Iunno...  I could be convinced either way :)

**Comment by quicksketch** [comment]
> Do we have a paradigm for LABEL vs VALUE that I should be following? The previous example was using quotes and ems, is that the right way to do it?

So the reason for separating out labels is so that translators will only need to change a string once and it will affect both the label and the description where the label was referenced. e.g.

```
$element1['#label'] = t('Foo');
$element2['#description'] = t('This field is affected by the "@label" field.', array('@label' => t('Foo'));
```

Now when a translator translates "Foo", it adjusts both the label and the description that references that label.

I think that quotes are better in this situation, because we're talking those exact strings rather than using the string as an inline part of a sentence. It's all a bit fluid, but we're actually discussing this exact problem over in https://github.com/backdrop/backdrop-issues/issues/2131. Let's try using quotes for now for both strings.

**Comment by jenlampton** [comment]
> Actually, why do we show this option at all if "Use content title" is selected? Shouldn't we hide it with #states and unset the value it in the submit handler if the "Use content title" is selected?

That's a good question. I spent some time fixing states, and realized that if we don't show the option to shoot yourself in the foot, we don't have to add the description text warning people not to shoot themselves in the foot!

here are the three states:

Node/Default title:
![screen shot 2016-09-15 at 7 40 00 pm](https://cloud.githubusercontent.com/assets/397895/18573834/3f8e5e94-7b7c-11e6-8fa0-78116ec7ac33.png)

Custom title:
![screen shot 2016-09-15 at 7 38 40 pm](https://cloud.githubusercontent.com/assets/397895/18573840/44d47c80-7b7c-11e6-9db9-c5ce5117a432.png)

No title:
![screen shot 2016-09-15 at 7 39 33 pm](https://cloud.githubusercontent.com/assets/397895/18573845/49d43978-7b7c-11e6-8a32-137a54bd19c4.png)

**Comment by quicksketch** [comment]
Yay, so much better!

**Comment by quicksketch** [comment]
Oops, but the most recent changes have broken the tests on this block:

> Failed to set field nid to 2 node.test:2003

So back to needs work.

**Comment by jenlampton** [comment]
tests passing again! https://github.com/backdrop/backdrop/pull/1556

**Comment by quicksketch** [comment]
Merged the PR at https://github.com/backdrop/backdrop/pull/1556. Great job @jenlampton! We can futz with this further if desired in follow-ups.
