### ISSUE TITLE
[UX] Move Primary Navigation menu to the top of the menus list?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2164]
I know the menus are ordered alphabetically on the menus page. But most of the time the menu people are looking for is the core `Primary navigation` menu.  Would it be reasonable to move this one to the top of the list, and perhaps make it's name bold? I was thinking the bold might help explain why it is at the top of the alpha list, in addition to helping people find the menu they are looking for.
![screen shot 2016-09-12 at 1 54 36 am](https://cloud.githubusercontent.com/assets/397895/18430158/2b1987ba-788c-11e6-8479-1f3bdd4f4897.png)

**Comment by klonos** [comment]
...I have been puzzled with this dilemma as well for other places in Backdrop. "Fixing" this will cause the usability issue where people scan lists of items looking for things expecting to see them in alphabetical order. I'd personally be OK either way, but it's not about each one of us, it's about the end users.

**Comment by jenlampton** [comment]
> "Fixing" this will cause the usability issue where people scan lists of items looking for things expecting to see them in alphabetical order. 

yeah, I'm also torn. Maybe we leave them in alpha order and make the one we think they want bold?  Does that even help?

**Comment by olafgrabienski** [comment]
Difficult question. What about users who build their own "Main navigation" and use it instead of the "Primary navigation"?

**Comment by jenlampton** [comment]
> What about users who build their own "Main navigation"

Yep, anything we do to improve the 80% use-case is definitely going to make it weird for these folks.

**Comment by olafgrabienski** [comment]
I'm afraid I belong to "these folks" ;-) but I see your point ... although not being sure if the 80% rule of thumb is realistic: How many of the 80% use a site as editors which was built by a 20% person?

Apart of that, the menu list often doesn't get that long that it's so difficult to scan in alphabetical order. We could discuss the question however more generally, not only for menus: "Do we want to highlight items in lists which are probably the 'most wanted' items in that list?"

**Comment by Graham-72** [comment]
As a site developer and administrator I would rather like to be able to drag the items in the menu list into an order of my choosing, i.e not alphabetical, but this would be in less than 20% of cases where, for example, there are more than six items.

**Comment by klonos** [comment]
Yeah, I was about to suggest what @Graham-72 said. We could allow either dragging and reordering of normally non-orderable things or have a way to have most frequently accessed ones automatically bubble up. Either way, I think too much trouble for little and most importantly low-impact improvement. Let alone having the rest of the people thinking that not having alpha order is a bug.

**Comment by jenlampton** [comment]
okiedokie, sounds like a job for contrib.  Thanks for weighing in all!
