### ISSUE TITLE
Change big 'ol "Welcome to Backdrop CMS" to "Welcome to [sitename]"

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2165]
It slipped my attention when we put in the hero block, but I think the default message shouldn't be touting "Backdrop CMS" permanently on the user's site. Rather I think we should put the site name in there:

![screenshot from 2016-09-12 17-00-27](https://cloud.githubusercontent.com/assets/100206/18457448/b8c53e98-790d-11e6-9032-620b4f87e99c.png)

Although we expect the user to change the default hero, we shouldn't demand that they do it by putting our product name across the top of their home page.

**Comment by jenlampton** [comment]
I'm not sure we want to do this. That text is in a config file, it shouldn't be generated automatically each time the site name is changed. And it should be available in the UI for people to edit/remove themselves.

**Comment by quicksketch** [comment]
Yep, we can manage all those things. We'll just set the default in the standard.install file, so it will still be plain text and editable by the user, just we'll set a better default. As a bonus, this will also make the string translatable out of the box. A PR might be the clearest way to express what I'm suggesting, I'll roll one real quick.

**Comment by quicksketch** [comment]
Here we are, PR: https://github.com/backdrop/backdrop/pull/1550

> What if we kept is static, but changed the text? Welcome to your website! or... ?

Yes exactly! That's what I'm suggesting. See the above PR.

**Comment by quicksketch** [comment]
We might also find this approach useful for translating the "No promoted content has been created yet." Just translate it as part of the installation profile.

**Comment by quicksketch** [comment]
Okay that was a little trickier than I thought because the site name isn't known until *after* standard.install has run. So we need to add a submit handler to the profile form to save the user-entered value. I'm not sure this will work with installations done via the command line (or on Zen.ci).

**Comment by quicksketch** [comment]
> I'm not sure this will work with installations done via the command line (or on Zen.ci).

It does. :smile: Screenshot of the testing sandbox:

![screenshot from 2016-09-12 18-29-47](https://cloud.githubusercontent.com/assets/100206/18458590/efb428ac-7916-11e6-8ff8-a9355ec79b49.png)

**Comment by jenlampton** [comment]
Looks good.

**Comment by quicksketch** [comment]
Great, thanks @jenlampton! Merging this into 1.x for 1.5.0 then.
