### ISSUE TITLE
Clear the "Operating in maintenance mode." message before showing the "The site is no longer in maintenance mode." message.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2169]
![backdrop-maintenance_mode-no_maintenance_mode](https://cloud.githubusercontent.com/assets/2423362/18472122/d808b974-79f8-11e6-974e-e5db136779dd.png)

**Comment by klonos** [comment]
Is `backdrop_get_messages();` the right way to do it? Funny DX (although I am not one). I would expect a `backdrop_clear_messages();` or something instead.

**Comment by klonos** [comment]
All green 😉 ...still not sure if that's the best way to go about it. I just saw some related articles on the net suggesting using the equivalent `drupal_get_messages();`

**Comment by quicksketch** [comment]
> Funny DX (although I am not one). I would expect a backdrop_clear_messages(); or something instead.

Yeah, this is adequate for the task at hand. Normally I wouldn't encourage use of this function in this way, as other messages that might be set during the submission handler would be thrown away. However, there is no other accessible way to do this and this form is so dead simple it's unlikely to have any other messages added to it. So :+1:

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/1551 into 1.x and 1.4.x. Thanks again @klonos!
