### ISSUE TITLE
ckeditor: Strike button will not appear, though <del> added to allowed tags

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2174]
While I was trying to copy the default button-set from WordPress, I attempted to enable the `Strike` button (which allows the `<del>` tag) and even though the button appeared on the text format config page (admin/config/content/formats/filtered_html) 
![screen shot 2016-09-13 at 5 34 54 pm](https://cloud.githubusercontent.com/assets/397895/18496149/699f1624-79d8-11e6-8d57-fb25f954fcba.png)
It would not appear on the actual toolbar.
![screen shot 2016-09-13 at 5 31 43 pm](https://cloud.githubusercontent.com/assets/397895/18496152/71e398b4-79d8-11e6-9a97-5c5fdab5fdf9.png)

---

PR: backdrop/backdrop#1573

**Comment by quicksketch** [comment]
Confirmed. I'll see if I can figure out what's happening here.

**Comment by quicksketch** [comment]
It looks like CKEditor defaults to a `<s>` tag, rather than the `<del>` tag that Backdrop expects. We can fix this by changing the element CKEditor uses for strike, as we are already doing for underlining.

PR: https://github.com/backdrop/backdrop/issues/1573.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1573 for 1.4.5.
