### ISSUE TITLE
[DX] Offer <nav> as an additional option for the wrapper and content tag in block settings

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2175]
I asked @illfittingshoes, an extremely talented front end developer, to run through basis and he came up with some issues that we can fix that are actually in core.
- [ ] A couple small thoughts...
  Should div[role=navigation] be a `<nav>`?
- [ ] The nav item for the current page has an 'active' class. Since 'active' is a CSS pseudo-class, perhaps something like "current" or "active-page" would be clearer?

The latter we probably shouldn't change until `2.x`, the former I'm thinking would be a good move. It's practically the same thing, but `<nav>` is the new hotness.

---
PR https://github.com/backdrop/backdrop/pull/1722

**Comment by quicksketch** [comment]
Thanks @wesruv! I moved this into 1.5.0 so that it shows up in the milestone list for review.

> The nav item for the current page has an 'active' class. Since 'active' is a CSS pseudo-class, perhaps something like "current" or "active-page" would be clearer?

Hm... yes. But 'active' has been a class in Drupal menus since as long as I can remember. I don't know if we can change this in 1.x (like you suggested).

Let's keep thinking on `div[role=navigation]`. Seems logical to me but this may have CSS repercussions.

**Comment by wesruv** [comment]
Arg! You're right, maybe we shouldn't do either of these for 1.x :disappointed: 

Definitely worth doing though.

**Comment by quicksketch** [comment]
Let's move this to 1.6.0 for consideration. If it doesn't make it then, we can kick it to 2.x.

**Comment by jenlampton** [comment]
I don't think we should change core element tags in something as likely-styled as the menu mid-release. That said if we wanted to find a way to make the div tag into a nav in Basis (only) I'd be in favor of that for 1.6.  If we wait any longer though, it will need to be pushed to 2.x as our risk of inconveniencing people increases the longer we wait to do it.

@wesruv how hard would it be to change that tag in only Basis?

**Comment by klonos** [comment]
Here's an idea: How about we take advantage of the "Dynamic style" setting when customizing blocks and have it so that menu blocks have `<nav>` offered as an additional option (currently we only allow `<div>`, `aside`, `section` and `p`) for wrapper and content tag in the respective drop-down menus?

**Comment by klonos** [comment]
...we could use that for the 1.x cycle and set that to be the default in 2.x.

**Comment by jenlampton** [comment]
Love it, we need that anyway!

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by jenlampton** [comment]
Theme developers are developers too, so this issue should be marked [DX] and not [TX]. Let's try not to separate the two in Backdrop. We are all in this together :)

**Comment by jenlampton** [comment]
I submitted a PR that adds Nav to the list of allowed tags. Since menu blocks are no different from any other blocks this was a very straightforward change :)

**Comment by olafgrabienski** [comment]
Looks good to me - I was able to set the NAV element in the block setting, and it was applied to the code:

Default: Style settings "Default"
`<div class="contextual-links-region block block-system-main-menu block-menu" role="navigation">`

Custom: Style settings "Dynamic", Wrapper tag: NAV
`<nav class="contextual-links-region block block-system-main-menu">`

**Comment by olafgrabienski** [comment]
> The nav item for the current page has an 'active' class. Since 'active' is a CSS pseudo-class, perhaps something like "current" or "active-page" would be clearer?

I'd suggest `is-active` which is used in Drupal 8 (in Bartik and Classy, afaik).

> But 'active' has been a class in Drupal menus since as long as I can remember. I don't know if we can change this in 1.x (like you suggested).

Instead of changing the classes, we can add one of the new suggestions.

**Comment by jenlampton** [comment]
> Instead of changing the classes, we can add one of the new suggestions.

I'm not sure I see any value in doing this, it will just add to confusion for new users. Why are there two classes that do the same thing? Let's hold off on changing markup until backdrop 2.x. (But if someone wanted to create an issue for that so we don't forget, that would be great)

**Comment by klonos** [comment]
>I submitted a PR that adds Nav to the list of allowed tags. Since menu blocks are no different from any other blocks this was a very straightforward change :)

https://w3c.github.io/html/sections.html#elementdef-nav (emphasis mine):

>**NOTE:**
> **Not all groups of links on a page need to be in a `nav` element — the element is primarily intended for sections that consist of major navigation blocks**. In particular, it is common for footers to have a short list of links to various pages of a site, such as the terms of service, the home page, and a copyright page. The `footer` element alone is sufficient for such cases; while a `nav` element can be used in such cases, it is usually unnecessary.

So, I think the proper thing is to be providing the `nav` tag as an option *only for menu blocks*? I tried to take a crack at it myself, but I don't know how to use `dpm` from inside dialogs 😛 ...no really, how do you php ninjas do it? ...what's the best alternative?

**Comment by jlfranklin** [comment]
> I'm not sure I see any value in doing this, it will just add to confusion for new users. Why are there two classes that do the same thing?

If you are going to deprecate the `active` class, then there should be a period where both `active` and one of the other classes is used.  To make it obvious for themers, maybe we should have three classes: `active` `active-deprecated` and whatever new one we choose.

On API.BackdropCMS.org, we note deprecated functions.  Is there a way to note deprecated CSS and other theming elements?

**Comment by jenlampton** [comment]
> I think the proper thing is to be providing the nav tag as an option only for menu blocks? 

Why allow people to only add navigation via the menu system?  It is perfectly reasonable that people will add links to other pages via a custom block. There's no reason to limit how backdrop can be used in this way.

**Comment by quicksketch** [comment]
I don't think we've had enough consideration in this issue to determine if we want to move forward on the current proposal, so I'm postponing this for after 1.6.0.

**Comment by jenlampton** [comment]
Really?

**Comment by quicksketch** [comment]
I think a previous version of the PR made more significant changes. But I think you're right the current one is good to go. Although I don't think this should be considered a "bug" or "task" so much as a feature, so I'm slating it for 1.7.0. We can merge it as soon as 1.x is branched for 1.6.x for maintenance.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1722 into 1.x for 1.7.0. Thanks everyone for the discussion here and @jenlampton for the PR.
