### ISSUE TITLE
[UX] Save and continue button in the installer is not blue

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2181]
In backdrop the primary button color is blue. Looks like we missed one on the installer: 
![screen shot 2016-09-14 at 10 33 28 pm](https://cloud.githubusercontent.com/assets/397895/18539339/5559ccb0-7acb-11e6-9954-93a4a630c6ed.png)

**Comment by quicksketch** [comment]
This isn't a Basis issue, it's Seven during the installer. But even then this is probably just a missing class rather than an issue with the theme. Moving this to the general pool, we can handle this at any time.

**Comment by jenlampton** [comment]
actually, I was on the wrong branch... it seems to be fine now that I found the right one :)
![screen shot 2016-09-14 at 10 43 32 pm](https://cloud.githubusercontent.com/assets/397895/18539511/bae8bf90-7acc-11e6-8c10-a347318f2ca2.png)
