### ISSUE TITLE
Basis: make the dragon smaller

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2182]
Drop is adorable, but dragon should not steal the show. A smidge smaller, maybe?

**Comment by quicksketch** [comment]
I'll shrink him down a bit using the SVG from our [presskit](http://backdropcms.org/presskit).

**Comment by quicksketch** [comment]
Oh, drop is sized with CSS! That trixy @wesruv strikes again! Scaling down is trivial... PR coming up.

**Comment by jenlampton** [comment]
Oh yeah, that's much better. Drop is even cuter at this size!

**Comment by quicksketch** [comment]
Great then, merged in https://github.com/backdrop/backdrop/pull/1571.

**Comment by wesruv** [comment]
Yuuuump, everything is so scaleable, if you decreased the font size of the document the dragon would become proportionately smaller

squeeeeeeeee
