### ISSUE TITLE
Dragon image in footer overlapps other blocks

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2188]
If the 'Powered by Backdrop' block is not the first one in the footer, the dragon lays on top of the content in the block above. Reported by @quicksketch in to https://github.com/backdrop/backdrop-issues/issues/1361 

can we make it so that Drop only shows up if the powered by block is the first block in the footer? Otherwise things like this happen:

![screenshot from 2016-09-14 02-02-01](https://cloud.githubusercontent.com/assets/100206/18506394/c7421dd8-7a20-11e6-89c8-50a9cc11872a.png)

**Comment by wesruv** [comment]
PR here: https://github.com/backdrop/backdrop/pull/1560

**Comment by quicksketch** [comment]
Thanks @wesruv! The PR sandbox results in sort of a funny positioning. It looks like the blocks are now floated left?

![screenshot from 2016-09-15 13-31-56](https://cloud.githubusercontent.com/assets/100206/18566496/f636adba-7b48-11e6-9d8a-97f421da4e19.png)

**Comment by quicksketch** [comment]
Chatting in Gitter, it looks like this was intentional but we're second-guessing it. My suggestion would be to not float the blocks, which seems presumptive and doesn't match the positioning of blocks in the admin bar.

So perhaps we go to just only showing the dragon if he's in the first footer block, hide him otherwise.

**Comment by quicksketch** [comment]
Thanks @wesruv for pushing up a fix. This is what it looks like now with Powered By as the not-first block:

![screenshot from 2016-09-15 13-47-41](https://cloud.githubusercontent.com/assets/100206/18566997/0362a398-7b4b-11e6-8406-97d9991829d2.png)

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1560 for 1.5.0. Thanks @wesruv!
