### ISSUE TITLE
contextual menu link is invisible on the blue background

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2189]
the contextual menu element is invisible on the blue backgrounds. Perhaps add some kind of white wrapper around such elements to make them universally visible on hover?

![selection_186](https://cloud.githubusercontent.com/assets/100206/18537262/30f190a4-7ab9-11e6-8aeb-4fa1a06d1338.png)

Follow-up to https://github.com/backdrop/backdrop-issues/issues/1361

**Comment by wesruv** [comment]
PR here: https://github.com/backdrop/backdrop/pull/1561

**Comment by quicksketch** [comment]
Great, thanks @wesruv! Merged in https://github.com/backdrop/backdrop/pull/1561. These contextual links could still use a little further love, but the completely invisible problem has been solved.

**Comment by klonos** [comment]
Damn you @quicksketch and your ninja merges! 😠 ...you close the PRs and destroy the sandboxes I (ab)use to test things 😛

**Comment by wesruv** [comment]
@quicksketch they're high on my list for 1.6 fixes

**Comment by klonos** [comment]
...and now there's a dedicated meta for them 😉
