### ISSUE TITLE
Excess margin above hero

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2191]
There is a lot of whitespace above the hero.  I'm not sure this is actually a problem, but several people have mentioned that it was not in the original Basis designs. I don't actually mind it, but opening this issue incase we want to fix it.

When there is no status message: 
![screen shot 2016-09-15 at 12 59 34 pm](https://cloud.githubusercontent.com/assets/397895/18565473/b8e59c68-7b44-11e6-9bb0-4003d579c5f4.png)

When there is a status message: 
![screen shot 2016-09-15 at 12 59 22 pm](https://cloud.githubusercontent.com/assets/397895/18565481/be3d2e1a-7b44-11e6-9be4-b04b12e9ba0d.png)

**Comment by quicksketch** [comment]
I think a large part of the aesthetic to the no-margin was lost when we had trouble with the full-bleed (#2190). Perhaps we should wait on this until both are possible...

**Comment by quicksketch** [comment]
Let's just merge this with https://github.com/backdrop/backdrop-issues/issues/2190.
