### ISSUE TITLE
Enable CSS/JS aggregation by default on new installs

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2194]
Basis adds a TON of new style sheets. If we want to ship with this theme enabled by default, we should make sure that all these don't get added individually into the header. An easy way to do that would be to enable CSS/JS aggregation by default - something we should maybe do anyway.

---
PR https://github.com/backdrop/backdrop/pull/1564

**Comment by quicksketch** [comment]
Sure, and I'll add that we had planned to turn on the page cache in 1.4.0 but didn't. Should we enable all performance settings for production then?

**Comment by wesruv** [comment]
This++

**Comment by jenlampton** [comment]
yes! PR on the way.

**Comment by quicksketch** [comment]
Lots of tests seem to check if their CSS/JS is added to the page. We'll need to disable aggregation for these specific tests.

**Comment by jenlampton** [comment]
Pushed a new PR that adds aggregation only for standard, I'm hoping that will cut down on all the tests that need to be updated. For those that are remaining I'll see which I can switch to the testing profile!

**Comment by jenlampton** [comment]
Pushed a final PR that should pass all tests now. Lots more swapping from standard to testing profile!

**Comment by quicksketch** [comment]
Great job @jenlampton! Merged https://github.com/backdrop/backdrop/pull/1564 into 1.x for 1.5.0.
