### ISSUE TITLE
Move the global border-box setting into base.css

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2196]
Should we move this into base.css? Base that is the stylesheet that normalizes things. And it doesn't really have anything to do with layouts, so I'm not sure why it's in layout.css

```
* {
  box-sizing: border-box;
}
```

---
PR https://github.com/backdrop/backdrop/pull/1572

**Comment by quicksketch** [comment]
Great, merged into 1.x for 1.5.0.
