### ISSUE TITLE
[META][UX] Contextual menu links need some love.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2197]
Follow-up to #2189 and an umbrella-issue for contextual link issues.

@quicksketch:

> ... These contextual links could still use a little further love, but the completely invisible problem has been solved.

@wesruv:

> @quicksketch they're high on my list for 1.6 fixes

Sub-tasks:
- [ ] #1707 [UX] Change contextual menu to top left corner instead of top right
- [ ] ...

**Comment by bugfolder** [comment]
Can this issue be closed? No new sub-issues have been added in the past 7 years (and meanwhile there are separate CL issues, like https://github.com/backdrop/backdrop-issues/issues/5273).

**Comment by quicksketch** [comment]
@bugfolder Yes I think this and the listed issue can both be closed, since #5273 fixes the underlying issue.
