### ISSUE TITLE
Remove utility.css

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2198]
Basis has a bunch of classes defined in `utility.css` for font control and semantic purposes. Should these be included in a core theme? I'd say this is better suited for contrib as it's not very likely all sites using Basis will have a need for something like this.

---

PR https://github.com/backdrop/backdrop/pull/1569

**Comment by wesruv** [comment]
@jenlampton The only one that's not actually being used is strong.semantic.

The font-sizing ones are _really_ useful for dynamic blocks where you can set classes on the title. People who don't know CSS can more accurately style blocks.

Makes sense if we want to omit it, be easier to add it down the road.

The strong.semantic can be replaced by a style for the strong tag in the site name area.

**Comment by jenlampton** [comment]
I filed a PR for review, but I still think we need more feedback. I would prefer to have less in core, since I've seen different class names used and ways of doing things. But if others would use these classes then I could be convinced. I could see these becoming sortof a standard, but then I wonder if they shouldn't work for all themes? It seems a bit weird to have a UI tool tied to a particular theme.

**Comment by quicksketch** [comment]
Yeah, I wasn't bothered by this concept, but seeing how much unnecessary CSS we have just the purposes of the title tag (by default) makes me agree that the `semantic` class is unnecessary.

This PR needs work though because we still are printing `semantic` in the header markup, we can nix that entirely if we're not using it for targeting.

**Comment by jenlampton** [comment]
I just pushed a new PR.  It removes the `semantic` class in the header, as well as a few other things:
* added back a missing `<?php if ($site_name); ?>`
* cleaned up documentation in the template file.
LMK if those need to be done in a separate issue.

**Comment by quicksketch** [comment]
The suggestions look good to me but this PR broke everything. :wink: https://github.com/backdrop/backdrop/pull/1569/files#r79098914

**Comment by jenlampton** [comment]
Whoopsie, fixed that. heh.

**Comment by wesruv** [comment]
Looks good to me!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1569 into 1.x. Thanks @jenlampton and @wesruv!
