### ISSUE TITLE
[UX] Project Installer: Submodules not available to be enabled during the last step.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2200]
Part of #1288 

**Use case**: I want to be able to quickly install Devel in order to be able to generate sample content for demoing Backdrop.

**Process**: I find the module through Project Installer, I add it to the installation queue and install it. At the last step, after the project has been downloaded and extracted for me, I am asked whether I want to enable it. I select to do so, but once it is enabled, I see no "Generate content" menu option. I then remember that the Devel Generate sub-module needs to be enabled for that. Why wasn't I given the option to enable that?

...anyways, Move on to the List modules page, scan for Devel Generate and finally enable it in order to get the "Generate content" menu option that I was initially after. Not ideal UX there.

**Comment by klonos** [comment]
OMG, I've been annoyed by this for so long!! PR up for review...

- any submodules of installed projects are added to the list in `/admin/installer/install/enable`. You can test with Devel:

[screenshot coming up]

- bypasses the warning about installing required modules (do we actually need this?), but does install any requirements in the background.
- does not account for subthemes or layout packages that include multiple layout templates (separate issue?)
- If even one submodule has a missing dependency, the submit button is not rendered, so any legitimate projects cannot be enabled (separate, preexisting issue). You can test with References:

[screenshot coming up]

**Comment by klonos** [comment]
- the list of modules + submodules needs to be ordered alphabetically by module title.
- perhaps add some JS to automatically select required modules checkboxes when these are on the list (might need some help with that).
- perhaps leave the warning about installing dependencies to be implemented as a dialog(??).

**Comment by Dinornis** [comment]
Thanks Gregory, well done, this is a nice UX improvement.
I ran the Installer (module) test and there are 4 Fails.
Maybe I run the tests incorrectly?

**FileName:** `installer.test`
**Function:** `InstallerBrowserAdministrationTestCase->testProjectBrowserInstallPage()`
**Messages:**
```
FAIL: Found the Enable modules button		
FAIL: Found the requested form fields at
FAIL: DDD Installer test was enabled.		
FAIL: EEE Installer test was enabled.
```

**Comment by klonos** [comment]
Thanx for testing @Dinornis 👍 ...this PR is a WIP as many additional small things need to be addressed.

Nope, I don't think you have done anything wrong. I just need to fix the 492 automated test failures that come with this change 😄 ...Unfortunately, I don't have enough time to get this finished by the upcoming 1.7.0 release 😞  ...but then again this is a UX issue and will most likely be eligible for any 1.7.x release after that. I believe I will have more time after mid May. Sorry.

**Comment by laryn** [comment]
I just tested this and have a few observations:

 - There is no enable button
 - Modules that are marked as `hidden` are showing up on this screen, although they are successfully hidden on the main Modules page (e.g. sub-modules that aren't fully ported)

![Screen Shot 2019-06-20 at 4 29 41 PM](https://user-images.githubusercontent.com/871421/59882861-f22e7400-9378-11e9-98ed-a182f6ad8081.jpg)

**Comment by docwilmot** [comment]
@klonos you planning to finish this? I'd recommend 
- move the code above into `installer_browser_installation_enable_form()` instead. Both forms calling `system_rebuild_module_data()` would be avoided
- check for hidden as @laryn recommends
- show a message in the dependencies column if hidden or module missing type in info file or other brokenness

**Comment by klonos** [comment]
Yup, I'm interested to wrap this up. I'll have a look over the next couple of days.

**Comment by docwilmot** [comment]
Can we get this finished @klonos ?

**Comment by docwilmot** [comment]
Any chance of re-checking this please? Its near enough.

**Comment by docwilmot** [comment]
@klonos have a look at this PR please. https://github.com/backdrop/backdrop/pull/3295. 

Tests passing, could use more tests, but the code for tests for Installer is a bit intricate and my first attempts failed (we have to try to trick Backdrop into thinking its pulling some fake release XML files from the main site and pretend that we're downloading zip files from GitHub, and somehow it wont all behave).

One detail, copied from your code, for checking for submodules, is that `$module->info['project']` only gets a `project` key based on dependencies, so if submodules say `dependencies[] = mainmodule` in their info file then this code will detect and list them, but if for whatever reason there is a submodule which does not depend on its packaging main module, it wont be listed. If this is a likely situation then we could check by paths instead (more overhead likely as we'd need to do a string operation like `strpos()` on every module path returned by `system_rebuild_module_data()`, which is a lot).

**Comment by klonos** [comment]
Thanks @docwilmot ...I actually started reworking this on my local over the weekend. I'll look into your feedback as well.

**Comment by klonos** [comment]
...I see. New PR 😅 ...I've closed mine in favor of yours @docwilmot 👍 

I've tested this in the PR sandbox, and it works as expected, also taking into account whether the submodule is set to be hidden 👍 

One minor improvement would be to nest submodules under each "parent" module if possible. This is otherwise RTBC! Thanks @docwilmot.

**Comment by quicksketch** [comment]
Can you post some before and after screenshots? The code looks harmless but I'm not sure what the end result is here.

**Comment by BWPanda** [comment]
I haven't looked at the code or tried to test this, but reading the posts above I have one concern:

> bypasses the warning about installing required modules (do we actually need this?), but does install any requirements in the background.

I think people should know if additional modules are being installed for them. It doesn't have to be a warning, but some sort of message indicating what additional modules will be installed would be helpful. Assuming this is still part of the latest PR...

**Comment by klonos** [comment]
> Can you post some before and after screenshots?

Sure @quicksketch 👍 ...before:

![image](https://user-images.githubusercontent.com/2423362/93008175-7bcbf200-f57a-11ea-941d-b2087bec2707.png)

...and after:

![image](https://user-images.githubusercontent.com/2423362/93008157-3e676480-f57a-11ea-9f8f-03137a528920.png)

**Comment by klonos** [comment]
> I think people should know if additional modules are being installed for them. ... Assuming this is still part of the latest PR

@BWPanda the TL;DR version is that the behaviour has NOT changed with @docwilmot's PR. Things work as previously.

I think that this was an issue specific to my initial PR, which had the changes in `installer_browser_installation_enable_page()`. @docwilmot had suggested to move them into `installer_browser_installation_enable_form()`, which is where the change lives in his PR, and it solves all that.

Take installing webform_validate for example... After adding the module to the installation queue and clicking "Install", you're taken to the page where you are given the chance to select a version other than the latest:

![image](https://user-images.githubusercontent.com/2423362/93008352-5f30b980-f57c-11ea-8ded-82a444d84b6b.png)

After that step, you are taken to the "Install Dependencies" step (**this is the step that was missing in my PR**):

![image](https://user-images.githubusercontent.com/2423362/93008247-3d830280-f57b-11ea-94f5-ad823e5d3d25.png)

...after clicking "Install", any dependencies would be dowloaded, and you'd be asked to enable all the downloaded modules (including the dependencies of the module you initially selected):

![image](https://user-images.githubusercontent.com/2423362/93008283-a4a0b700-f57b-11ea-86a1-53a683df6905.png)

**Comment by quicksketch** [comment]
Thanks folks! Merged the fix in https://github.com/backdrop/backdrop/pull/3295 into 1.x and 1.16.x!

**Comment by herbdool** [comment]
Follow-up bug: https://github.com/backdrop/backdrop-issues/issues/5054
