### ISSUE TITLE
Sticky table headers issue - header not aligned well if table is wider than document

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2201]
Found by quicksketch in https://github.com/backdrop/backdrop-issues/issues/2098#issuecomment-242628378

On narrow screens the table header gets offset if the table doesn't have enough room _and_ you're horizontally scrolled to the right:

![2016-08-25 21 25 14 036](https://cloud.githubusercontent.com/assets/100206/17994091/b8f4ba08-6b0a-11e6-9c4d-66f16c63c7f4.gif)

**Comment by jenlampton** [comment]
As this is a bugfix I'm slating for 1.5.1.

**Comment by quicksketch** [comment]
I don't think this is a critical item and it might take a while to fix (those sticky headers get messy). I'm moving this to 1.x-future, but we can definitely merge this in as soon as it gets fixed. As soon as we have a PR, let's move it into the current bug fix release milestone.

**Comment by klonos** [comment]
I was looking for this issue everywhere!! I have accidentally fixed this in https://github.com/backdrop/backdrop-issues/issues/2317. PR sandbox details:

Website: http://1632.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: zVohK7cX

..screencast from the sandbox:

![backdrop-issue2201-pr1632](https://cloud.githubusercontent.com/assets/2423362/19876081/858c2b32-a026-11e6-81f3-3a4f08f87888.gif)

Messing with JS and providing PRs? ...now people really won't believe that I'm not a coder 😄
