### ISSUE TITLE
Layouts: sidebar not responding correctly to a view block with a contextual filter

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2203]
I am trying to use a layout with the main content being a page created by a view, with the nid as the contextual filter. This works fine, but when I try to place another view, this time as a block, in the sidebar, again using the nid as the contextual filter, the sidebar is not acting on the filter.

This screenshot shows my particular objective, with the main content being the body of the underlying node, and the right hand sidebar being photos that are contained in that node. The problem is that the right-hand column shows photos for all events, not just this specific one identified by the nid. However, the preview of the block works perfectly.

![event report catherine larner](https://cloud.githubusercontent.com/assets/10559274/18585162/268495f8-7c0d-11e6-80a0-1e107a8aabb6.png)

**Comment by Graham-72** [comment]
Ah well, I have found a way to achieve this layout using CSS to create a sidebar within the single column Boxton layout. An example of the result can be seen at http://www.catherinelarner.com/eventreport2/715 and this time the photos correspond to the author.

But it would be nice to be able to do it the way I hoped would work in layouts.

**Comment by olafgrabienski** [comment]
Quite late here: If I understand correct, you can achieve the same thing placing fields as blocks in the Layout. The requirement would be a Layout with node context, i.e. with *Path* set to `node/%`.

**Comment by Graham-72** [comment]
@olafgrabienski your suggestion worked for me in some situations but not all. This is perhaps a manifestation of issue #2878 and the fix for that issue solves this one. Thank you @jenlampton .

**Comment by BWPanda** [comment]
Closing this as it seems fixed...? Reopen if I'm mistaken.
