### ISSUE TITLE
[META][UX] Redesign the "Manage display" form to be consistent with the rest of the admin UI.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2205]
I do not currently have the time/energy to word my proposal, but here is a draft of the things I think should get done:

![backdrop-redesign_content_type_manage_display_tab](https://cloud.githubusercontent.com/assets/2423362/18608155/d73dc55a-7d24-11e6-871e-23cf66f60f5a.png)

This might not make sense to anybody now, but I promise to come back soon with a proposed mockup ...and a proper issue summary.

**Comment by klonos** [comment]
...so, the "Custom display settings" fieldset is only shown on the "Default" view mode. To reproduce:

1. go to `/admin/structure/types/manage/post/display` -> the fieldset is there
2. go to `/admin/structure/types/manage/post/display/teaser` -> no "Custom display settings" fieldset

Not a bug worth fixing IMO. I have a better UI proposal...

**Comment by klonos** [comment]
...related: #2250

**Comment by klonos** [comment]
...how about something like this:

![backdrop-content_type-manage_display_tab_redesign](https://cloud.githubusercontent.com/assets/2423362/18981180/259c6af4-871f-11e6-814f-c432009dc722.png)

**Comment by mikemccaffrey** [comment]
This seems like a good change. The current settings are ina non-obvious place.

I think we should try to use the same ui workflow for this that the views ui uses to add/delete additional displays.

**Comment by klonos** [comment]
Watching the BADCamp training videos, I filed #2305 so that we solve the UX issue with people not understanding that they need to hit the "Save" button on that form. Lets make this a meta-issue and also file separate issues for adding table headers and for making the management of custom displays work more like views (which is an idea I really like @mikemccaffrey 👍 ).

**Comment by jenlampton** [comment]
I'm going to close this issue in favor of https://github.com/backdrop/backdrop-issues/issues/315 since I believe that will cover these issues as well.
