### ISSUE TITLE
Contextual links to edit hero region are out of place

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2206]
I think changing `.block-hero` from `position: static;` to `position: relative;` will solve this issue -- will it cause any others?

**Comment by wesruv** [comment]
@laryn you nailed it! I'll submit a PR here.

`left:auto` is all I really needed, but I had added `position:static` as an (unnecessary) precaution.

**Comment by wesruv** [comment]
PR here: https://github.com/backdrop/backdrop/pull/1602

**Comment by quicksketch** [comment]
Thanks @laryn and @wesruv! I've merged the PR.

I made a follow-up to tweak the contextual links in the hero further, we have a problem where the increased font size also make for huge contextual links. Issue filed at https://github.com/backdrop/backdrop-issues/issues/2268.
