### ISSUE TITLE
Installer: Empty " | " in <title> tag while site name not defined yet.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2209]
So here's what the users see as page titles (`<title>` tag) during installation:

`Choose language |`
`Database configuration |`
`Installing Backdrop CMS | Backdrop`
`Configure site | Backdrop`
`Home | mySiteName`

The first two should either have "Backdrop CMS" hard-coded or the trailing " | " removed. The next two, I think should be updated to say "Backdrop CMS" instead of just "Backdrop".

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1731

**Comment by jenlampton** [comment]
This is a good issue, but not necessarily a bug.  Also, not urgent enough to need to be fixed by next week, so removing the 1.5.1 milestone.

**Comment by klonos** [comment]
> We could likely manage that by setting the site name to Backdrop CMS by default, then as the installer runs it would overwrite that value.

Yes, perhaps in a way that would allow Backdrop CMS distributions to easily override that with their name (like "Open Atrium" or "Commerce Kickstart" for example).

**Comment by klonos** [comment]
Looks like [`"site_name"` is already set to `Backdrop`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/config/system.core.json#L57) (I think better change that to `Backdrop CMS` instead), but I guess it doesn't get picked up that early during the first steps of the installer.

**Comment by klonos** [comment]
Re-classifying as bug. Reason is that there seems to be a flaw in [`template_preprocess_maintenance_page()`](https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L2758) (which we seem to be using to render the installer pages as well) with the logic that adds values in the `$head_title` array...

Old code:

```php
  if (backdrop_get_title()) {
    $head_title = array(
      'title' => strip_tags(backdrop_get_title()),
      'name' => $site_name,
    );
  }
  else {
    $head_title = array('name' => $site_name);
    if ($site_slogan) {
      $head_title['slogan'] = $site_slogan;
    }
  }
```

So, `'name' => $site_name` is added in all cases (the line exists in both the `if` and the `else`). I guess the reason for not adding this unconditionally outside the `if`/`else` is that we need to preserve the order of `'title'`/`'name'`/`'slogan'` in the `$head_title` array be cause [we `implode` it later on](https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L2797) in order to set the value for the `head_title` variable. Now, although in the early stages of the installer the site name has not been set yet, we are adding it unconditionally to the `$head_title` array in either case of the `if`/`else`. This leads to a `name` key in the array with an empty string as a value in both cases. So, when the array get imploded, we and up with that stray/empty `|`. I could have simply added a condition to check whether `$site_name` is set before we insert the `'name'` key in the array, but I would then have to do that for both the `if` and `else`. This would produce the following code:

```php
  if (backdrop_get_title()) {
    $head_title = array('title' => strip_tags(backdrop_get_title()));
    if ($site_name) {
      $head_title['name'] = $site_name;
    }
  }
  else {
    $head_title = array();
    if ($site_name) {
      $head_title['name'] = $site_name;
    }
    if ($site_slogan) {
      $head_title['slogan'] = $site_slogan;
    }
  }
```

The `if` is there to cover the `'title'`/`'name'` case and the `else` to cover the `'name'`/`'slogan'` case. It seemed much cleaner/less code to me to just initialize the `$head_title` array once and then do individual `if` checks for the 3 `'title'`/`'name'`/`'slogan'` values instead.

PR code solves the issue for me. I now need to fix the tests.

**Comment by klonos** [comment]
Interesting note: In the PR I've also changed the site name in `core/modules/system/config/system.core.json`  from `Backdrop` to `Backdrop CMS`, but I haven't done so on my local. So after running a test installation on my local, I noticed that the head `<title>` is set to the following:

`Choose language | Backdrop CMS`
`Database configuration | Backdrop CMS`
`Installing Backdrop CMS | Backdrop`
`Configure site | Backdrop`
`Home | mySiteName`

...so it seems that we are successfully reading the config file after the db config step. Why isn't that possible earlier? If there was a way, then we could perhaps consolidate the construction of the head `<title>` from https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L2658 and https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L2774 into a single function we could be calling.

**Comment by klonos** [comment]
Fixed the tests and all comes back green 😉

**Comment by klonos** [comment]
> ...so it seems that we are successfully reading the config file after the db config step. Why isn't that possible earlier?

What I meant by this is that it seems that the installer forms up to the db configuration are rendered by [`template_preprocess_maintenance_page()`](https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L2774) while from the "Installing Backdrop CMS" page thereafter are rendered by [`template_preprocess_page()`](https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L2658).
