### ISSUE TITLE
Fix typo "This is static page"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2218]
Whoopsie, on our default content `This is static page` should be `This is a static page`.

---

PR by @klonos: https://github.com/backdrop/backdrop/issues/1582

**Comment by klonos** [comment]
@jenlampton I can file a PR for this, but this is a sub-set of the changes I propose in #2210 can you please let me know what you think there and if you want to simply fix only this.

**Comment by serundeputy** [comment]
@klonos I'd say fix this up right away as this is a forward facing bug, so we don't spin on the other points in #2210 and we can address those separately in the #2210 issue.

that is my take.

**Comment by klonos** [comment]
I went with "This is a page with static content." which seems more accurate to me. Let me know if you prefer to change it so that it simply adds the missing "a".

**Comment by quicksketch** [comment]
Great. Thanks! Merged into 1.x (1.5.x) in https://github.com/backdrop/backdrop/issues/1582.
