### ISSUE TITLE
[UX] Easier way to find login link

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2221]
When I was doing sites on the side a lot of my clients would have a hard time remembering how to get to the login. Often we'd remove the login links from the page layout because only they should be logging in.

Wondering if there's something else we could add to make this a little easier?

Squarespace has it setup so if you press the "Escape" key on one of their sites it brings up the user login. I'm a fan of that functionality, but maybe there are more/better solutions?

Or maybe this isn't a 'core' problem and I just make a contrib module for this 😄

**Comment by jenlampton** [comment]
> Squarespace has it setup so if you press the "Escape" key on one of their sites it brings up the user login.

I think this would be a great candidate for a contrib module! (but I'm not sure about making it a core feature.)

**Comment by klonos** [comment]
If this is a tiny bit of code in order to get it implemented and if it doesn't break things, then I say just add it to core.

Related: perhaps we should change the login URL from `/user` to `login`?

**Comment by bd0bd** [comment]
> change the login URL from /user to /login?

Agree :)

**Comment by tomgrandy** [comment]
Yes!

**Comment by jlfranklin** [comment]
> If this is a tiny bit of code in order to get it implemented and if it doesn't break things, then I say just add it to core.

This is the path to code bloat in core.  This feature is better implemented as a contrib module.

> Related: perhaps we should change the login URL from `/user` to `/login`?

This will break any contrib module that uses `hook_menu_alter()` to update how the login page works.  This would also break sites and modules that expect links to `/user` to go to the login page for anonymous users and the profile page for authenticated users.

**Comment by olafgrabienski** [comment]
> [Changing the login URL to `/login`]  will break any contrib module that uses hook_menu_alter() to update how the login page works. This would also break sites and modules that expect links to /user to go to the login page for anonymous users and the profile page for authenticated users.

What about a redirect from `/login` to `/user`?

**Comment by jenlampton** [comment]
The URL is already /user/login and we have a separate issue to fix that.
We're getting off topic here :)

I agree about code bloat. Loosing the login link only happens for some,
those can add the module.
