### ISSUE TITLE
[UX] primary navigation menu block not rendering as drop-down on home page layout

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2222]
With the 1.5.0 release, by default, out of the box, the primary nav menu block is rendered as a drop-down _on the default layout_, but on the new home layout in 1.5.0 it is set to be rendered as a hierarchical tree. I don't really understand the reason behind this (having the same menu be rendered one way for the home page and another way for the rest of the website) and it does pose a UX WTF the way I see it.

Also, this is a blocker for what I envision for my upcoming Backdrop talk at DrupalSouth:

1. Install a fresh Backdrop test site...
2. Go to the Project Installer and then install and enable the Devel module (required for the next steps)...
  People go "wow! ...that was easy."
3. Go to the generate menus page provided by Devel Generate...
4. Generate some menu items for the primary menu and make sure there are items at 2+ depth...
5. Go to the home page and show people that the primary menu is drop-down out of the box...
  People go "WOW!!! AMAZEBALLZ!"

So, #2200 is a blocker for step 3 above (otherwise I need at least a couple more steps) and this issue here is a blocker for step 5.

---
PR from @jenlampton at https://github.com/backdrop/backdrop/issues/1585

**Comment by olafgrabienski** [comment]
I was able to reproduce the issue. Don't know the reason, anybody else?

(After I adapted the "Menu style" of the "Primary navigation" of the "Home page" layout to "Dropdown Menu" and changed the Max depth to "Unlimed", all was fine.)

@klonos - to demonstrate the anyway amazing menu in the meantime, just go to another page in step 5, not the home page ;-)

**Comment by jenlampton** [comment]
The settings for this menu aren't saved for the home page layout. The fix should be a quick one, make the changes, then copy the updated config file for the front page layout (`layout.layout.home`) into the standard profile `/config` directory.

**Comment by klonos** [comment]
> @klonos - to demonstrate the anyway amazing menu in the meantime, just go to another page in step 5, not the home page ;-)

OR... we fix this in 1.5.1 and release that version before the 27th of October. Just saying 😄

**Comment by olafgrabienski** [comment]
> The fix should be a quick one, make the changes, then copy the updated config file for the front page layout (layout.layout.home) into the standard profile /config directory.

Yes, looks quite easy. Status quo in `profiles/standard/config/layout.layout.home.json`, around line 64:

```
"block_settings": {
                        "menu_name": "main-menu",
                        "level": "1",
                        "depth": "1"
                    },

```

After I changed the menu settings, in `files/config_.../active/layout.layout.home.json` I see:

```
"block_settings": {
                        "menu_name": "main-menu",
                        "style": "dropdown",
                        "level": "1",
                        "depth": "0"
                    }

```

@jenlampton - I could make a PR in the next days, shall I?

**Comment by jenlampton** [comment]
I made one yesterday. Is it not showing here?

**Comment by olafgrabienski** [comment]
Yes, overlooked it first. Tried it then out, looks good to me. (No time to look at the code at the moment.)

**Comment by klonos** [comment]
I took a look at it. The php7 tests seem to have a (random?) failure.

This will work as expected for the out of the box installations, but I don't think that it'll fix existing 1.5.0 installations. Update hook in order perhaps then?

Other than that, the changes seem to be pretty straight forward, so RTBC from me (once we make sure that the php7 failure is random and decide on the update hook or not).

**Comment by klonos** [comment]
...I tried to find update hook examples but I could only figure out how to get/set values only for 1st-level. For the home layout, I couldn't figure out how to traverse `layout.layout.home.json` to get the primary nav menu block settings and update them 😞

**Comment by klonos** [comment]
> The php7 tests seem to have a (random?) failure.

Yep. We've got the same failure on php7 over at https://github.com/backdrop/backdrop/pull/1588 ...I've filed a meta issue to track and fix the random failures: https://github.com/backdrop-ops/backdropcms.org/issues/300

**Comment by quicksketch** [comment]
> Update hook in order perhaps then?

I think an update hook for existing installs seems reasonable. With 1.5.0 so new, it's very unlikely that users would have *intentionally* set the home page menu to be a hierarchical tree instead of a drop down.

**Comment by jenlampton** [comment]
@quicksketch where does the update hook go for this...  menu module? block module? layout module?

**Comment by jenlampton** [comment]
Pushed a new PR that adds the update hook as part of layout module. I think that's the right place, but lmk if I need to move it. https://github.com/backdrop/backdrop/issues/1585

**Comment by quicksketch** [comment]
Uh, yeah this is a little weird because the Standard profile actually "owns" the update. Can profiles even have update hooks? Probably, but we haven't ever done that before. Maybe give it a shot and put it in `standard.install`?

Putting it in `layout.install` will break tests (as did happen) because layout.module is a new module and enabled in the upgrade process, adding an update hook into it causes update.php to need to be run twice when upgrading from Drupal 7.

**Comment by quicksketch** [comment]
Left a review on the PR: https://github.com/backdrop/backdrop/pull/1585#pullrequestreview-2259177.

**Comment by jenlampton** [comment]
Pushed a new PR that addresses feedback from @quicksketch

**Comment by jenlampton** [comment]
Pushed another PR that addresses more feedback from @quicksketch https://github.com/backdrop/backdrop/pull/1585

**Comment by quicksketch** [comment]
As noted in the [weekly meeting today](https://www.youtube.com/watch?v=oqt3_UcBPe8), we'll have problems if users follow the "standard upgrade process" and just update the "core" directory and not the profiles directory. So for the time being, let's move this update into `system.install` so that it will affect all sites.

**Comment by klonos** [comment]
> So for the time being, let's move this update into `system.install` so that it will affect all sites.

Yes, lets just do that for 1.5.1 and this specific issue here, but let's also move the profile folders that are shipped with core under a `/core/profiles` folder.

**Comment by quicksketch** [comment]
PR has been updated to move the update into system.install.

**Comment by klonos** [comment]
Looks good to me 👍

...eventually, once we move the profiles shipped with core under a `/core/profiles` directory, we could add a notice (site status page perhaps) that prompts people to delete the standard, minimal and testing profiles from the root `/profiles` folder if found there. That should be enough to get their setup in a state where any future updates in core profiles are not overridden by the "left-over" profiles from old installations. Also, we are not asking anything crazy, since if the user had a way + permissions to replace the `/core` folder, then they can pretty much handle those 3 folder deletions as well.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1585 for 1.5.1. Thanks!
