### ISSUE TITLE
Add .svg to the allowed file extensions for the site logo and remove irrelevant ones (like .txt, .doc etc).

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2223]
Might come with some interesting bugs.

Follow up question, why would we allow these:
`txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm`

![image](https://cloud.githubusercontent.com/assets/5607236/18757391/c2c5406c-80c1-11e6-8bd5-bf16dfdf1165.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2203

**Comment by klonos** [comment]
I would say that this is something between a feature request and a bug. Lets call it a task then. Not much coding to be done I guess besides adding the .svg extension to the allowed list (and remove the irrelevant ones).

**Comment by quicksketch** [comment]
As a relatively minor change and "sort of a bug" like @klonos says, I've merged in https://github.com/backdrop/backdrop/pull/2203 into 1.x and 1.10.x.
