### ISSUE TITLE
[DX] Basis Sub Theming: When copying skin.css all image links break

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2224]
A little torn on the best solution for this.

We could:
* Make a root relative image link (gross, would break on installs that aren't done on server root)
* Ask users to copy the images folder
* We could leave the styles in but comment them out so a sub-themer knows what the styles are and can easily uncomment and override, might still lead to broken image links if they uncomment

... other ideas?

**Comment by wesruv** [comment]
Bug... I guess? Since the way we're recommending you sub theme will cause a bug?

**Comment by Graham-72** [comment]
I think it is reasonable that a sub-themer should copy the images folder to their themes folder rather than depend on those in core. I think there is some merit in having an images folder within the css folder for the subtheme.

**Comment by wesruv** [comment]
Thanks for the feedback @Graham-72!

I'm going to put together a PR  of something that might be a good middle ground... I'd love feedback when I get it posted.

**Comment by wesruv** [comment]
More on this issue, for status messages in particular, which are referencing files in core/misc/ which becomes problematic because we can't be sure where the sub theme is added in the codebase, and Backdrop may not be running from the server root, so root relative may not work.

**Comment by klonos** [comment]
@Graham-72 true that. Reasonable, but not ideal or intuitive. I would expect that images work the same way as other things when sub-theming: if no action, then the defaults from the parent theme are loaded - if I create an image with the same name, (or actually path relative to the subtheme), then the respective parent theme image is overridden with my custom one from the subtheme. That would IMO be optimal.

**Comment by wesruv** [comment]
> if no action, then the defaults from the parent theme are loaded

@klonos if there is no action, the images work great. 

The problem is we're recommending that people override `skin.css` if they want to change colors (until we get something like color module working). The way file paths work in CSS, the URL's are relative to the file's location. As soon as you override with a copy of the file all of the image links break since the image URL is the same, but the CSS file is in a different location.

>  if I create an image with the same name, (or actually path relative to the subtheme), then the respective parent theme image is overridden with my custom one from the subtheme. That would IMO be optimal.

It would be very tricky to get image overriding working the same way CSS does, where a similar name gets overrided simply by existing and making Backdrop aware of it. It sounds like dark magik would be involved to get that working.

If a user overrides the CSS file in their theme and copy the images folder over, they can override any image you like in your sub theme's image folder and the CSS would pick it up just fine since all of the links are relative. 

That's not as magical as what I think I'm reading, but gets the customization without messing with core.

**Comment by wesruv** [comment]
Here's a PR for suggested updates for status messages:
https://github.com/backdrop/backdrop/pull/1584

Basically make the images originate from Basis' component CSS, and the style shows up in skin.css, but it's commented out. So the user can easily uncomment and change to their liking, but the image links won't break if you override `skin.css`.

Another option, we could make status-message.css a library that Seven and Basis calls that lives in a neutral place.

**Comment by quicksketch** [comment]
I think this is a great approach @wesruv. At first I found it odd that the images were commented out, but then I saw the value in having those rules specified in the event I wanted to change them to something else. So it makes sense to me. It's definitely better than the CSS breaking when overriding skin.css.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1584 into 1.x for 1.5.1.
