### ISSUE TITLE
[DX] Basis Sub theming - Component CSS is overriding Skin CSS

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2225]
The `hero.css` is only being added if there's a hero on the page, and it's getting added lower in the cascade than `skin.css` which was not intended.

`skin.css` is supposed to be able to override the any component CSS just by being lower in the cascade, and not create a specificity war.

**Comment by wesruv** [comment]
I _could_ do a `hook_css_alter()` and increase the weight of `skin.css`, but to ensure that this also happens for sub-themes it starts to get ugly 😦 

Part of me wants to add another group, e.g.
```
'group': A number identifying the group in which to add the stylesheet. Available constants are:
    CSS_SYSTEM: Any system-layer CSS.
    CSS_DEFAULT: (default) Any module-layer CSS.
    CSS_THEME: Any theme-layer CSS
    CSS_SKIN: Appearance only styling that should be lower in the cascade than other files
```

But then we'd have to figure out how to add skin.css to that group, hopefully from the info file 😦 

I dunno.

**Comment by wesruv** [comment]
More on this issue, for status messages in particular, which are referencing files in `core/misc/` which becomes problematic because we can't be sure where the sub theme is added in the codebase, and Backdrop may not be running from the server root, so root relative may not work.

**Comment by wesruv** [comment]
BLARG! This is also an issue because `every_page` items are grouped together, which makes a lot of sense, but this means that `hero.css` (`every_page = FALSE`, `group = CSS_THEME`) will always come after `skin.css` (`every_page = TRUE`, `group = CSS_THEME`) no matter what the weights are 😭

**Comment by Graham-72** [comment]
It would be good one day to produce a section in our guide book about sub-theming Basic.

I have just made use of 'order' in flexbox to resolve an issue I have. Works a charm!

**Comment by wesruv** [comment]
@Graham-72 working on it now 😄 that's how I'm finding all of these bugs

**Comment by wesruv** [comment]
... one option is we could make `skin.css` `preprocess = false`, but I do not like that.

**Comment by wesruv** [comment]
Here's a solution I hate:

```
/**
 * Implements hook_css_alter().
 */
function basis_css_alter(&$css) {
  global $theme_key;

  $basis_path = backdrop_get_path('theme', 'basis');
  $active_theme_path = backdrop_get_path('theme', $theme_key);
  if (isset($css[$basis_path . '/css/skin.css'])) {
    $css[$basis_path . '/css/skin.css']['weight'] = 9999;
    $css[$basis_path . '/css/skin.css']['every_page_weight'] = 9999;
    $css[$basis_path . '/css/skin.css']['every_page'] = false;
  }

  if (isset($css[$active_theme_path . '/css/skin.css'])) {
    $css[$active_theme_path . '/css/skin.css']['weight'] = 9999;
    $css[$active_theme_path . '/css/skin.css']['every_page_weight'] = 9999;
    $css[$active_theme_path . '/css/skin.css']['every_page'] = false;
  }
  else {
    foreach ($css as $key => $current_css) {
      if (substr($key, 0, strlen($active_theme_path)) === $active_theme_path && substr($key, -9) == '/skin.css') {
        $css[$key]['weight'] = 9999;
        $css[$key]['every_page_weight'] = 9999;
        $css[$key]['every_page'] = false;
      }
    }
  }
}
```

**Comment by wesruv** [comment]
Here's a thought, there wasn't much CSS that I was loading dynamically, I'm just going to put it all in the info file and stop trying to be cool. That'll temporarily solve this issue, but I think the way CSS is aggregated could use some love.

PR Here: https://github.com/backdrop/backdrop/pull/1586

**Comment by jenlampton** [comment]
I actually really like the approach in https://github.com/backdrop/backdrop/pull/1586 . I know it's not quite as "correct" as the previous one, but I think there will be fewer theme-dev-WTFs if all the css is defined in the info file. RTBC from me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1586 into 1.x for 1.5.1. Thanks @wesruv and @jenlampton!
