### ISSUE TITLE
1.5.0 release

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2226]
Lets start doing this with each release. **The following is a quick demo only with example tasks and random people assigned to them**, but we can use this as a template and store it someplace so that with each upcoming release we have a list of pre- and post- tasks that need to be done.
## Pre-release tasks
- [x] Merge commits @quicksketch, @serundeputy
- [x] Create an unpublished announcement node on b.org @jenlampton, @quicksketch, @klonos  see https://backdropcms.org/news/backdrop-15-released (@quicksketch has a draft of this somewhere, with screenshots)
## Release tasks
- [x] Tag for release @quicksketch
- [x] Update the front page download link on b.org @quicksketch 
- [x] Create release notes on GitHub @quicksketch, @jenlampton
## Post-release tasks
- [x] Publish the announcement node on b.org @klonos
- [x] Draft a newsletter via MailChimp @jenlampton
## Post-follow-up-release tasks
- [x] Update the docker image to the latest @serundeputy 
- [x] Push the bug-fix release to the Pantheon repository (wait for 1.5.1: #2267)
- [x] Send a newsletter via MailChimp @jenlampton (wait for 1.5.1: #2267)

**Comment by jenlampton** [comment]
@klonos a great suggestion, I added this list into the repo at https://github.com/backdrop-ops/procedures along with a few other items we usually manage along with releases. Will update this issue in a sec.

**Comment by quicksketch** [comment]
This issue was confusing me because it was tagged for 1.5.1, but included a mix of tasks from 1.5.0 and 1.5.1. I updated the summary to reference 1.5.1 items so we can close this issue and continue in a dedicated issue for 1.5.0 at https://github.com/backdrop/backdrop-issues/issues/2267.

**Comment by jenlampton** [comment]
I'm finding https://github.com/backdrop/backdrop-issues/issues/2267 confusing because it looks like the checklist was copied from the minor-relase list and not the bug-fix release list. There are tasks on there that have nothing to do with minor releases (like sending newsletters and writing announcements)

**Comment by jenlampton** [comment]
Ah I see. I think @quicksketch  added ` (wait for 1.5.1: #2267)` to a bunch of items that do not need to wait for 1.5.1.  I've removed it from the things that need to be done asap. Okay if I reopen?

**Comment by klonos** [comment]
> Okay if I reopen?

Even though this issue is marked for the 1.5.0 milestone, it does not mean that it needs to be closed when 1.5.0 is released. It's meant to be closed only when all the tasks in it have been completed.

So what might be confusing is that for every release until now we had all issues marked with their milestone closed. With keeping these task lists as GitHub issues, it means that all **but one** issues for each release might be closed. Eventually, when all tasks will be completed, that last one issue will also be closed of course.

**Comment by klonos** [comment]
...which makes using github issues for the release tasks a "hackish" workaround (or some might also say an abuse of the queue), but oh well... if it makes things easier for us and helps us keep track of things to be delegated and eventually get done, then that's what we'll be doing.

Another way would be to create a separate, say "release-tasks" repo in github and use that for the task-list issues. That would keep the core issue queue clean.

**Comment by klonos** [comment]
@jenlampton https://github.com/backdrop-ops/procedures gives me a 404 ??

**Comment by serundeputy** [comment]
@klonos `procedures` was moved here: https://github.com/backdrop/backdrop-issues/tree/master/procedures

**Comment by jenlampton** [comment]
We moved it to the issues repo.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by jenlampton** [comment]
Newsletter is scheduled for tomorrow, closing this issue.  Thanks everyone!
