### ISSUE TITLE
[DX] If I sub theme Basis, but don't want Open Sans... how do?

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2228]
We've added opensans as a library in a preprocessor, which is great, until I wanted to use a different font. How do I prevent Open Sans from being loaded?

https://github.com/backdrop/backdrop/blob/1.x/core/themes/basis/template.php#L15

**Comment by wesruv** [comment]
@quicksketch @jenlampton I don't think there's currently an answer to this, is there?

**Comment by jenlampton** [comment]
Maybe...
'''
function subtheme_preprocess_page(&$variables) {
  // Remove the OpenSans font from core on every page of the site.
  backdrop_unset_library('system', 'opensans', TRUE);
}
'''

**Comment by wesruv** [comment]
In D8 land you're able to do the following to libraries:
* Add new
* Remove entire library
* Add an asset to an existing library
* Remove a single asset from an existing library
* Override a single asset from an existing library

I think getting the 2nd one done would be a huge step forward, but thought the others might be worth mentioning in case we wanted to think about other potential needs.

As a themer I looooooove that I can do all of these things with libraries. The last 3 are kind of "power-usery", but have solid use-cases, IMO.

**Comment by jenlampton** [comment]
Can you provide a link to the D8 api for these things? Maybe we can fork it! ;)

**Comment by wesruv** [comment]
It's done in YML files, not sure what code is behind it...
https://www.drupal.org/docs/8/theming-drupal-8/adding-stylesheets-css-and-javascript-js-to-a-drupal-8-theme
https://www.drupal.org/node/2201089

**Comment by quicksketch** [comment]
To answer the immediate question of "how do I remove Open Sans":

```
/**
 * Implements hook_css_alter().
 */
function mytheme_css_alter(&$css) {
  if (isset($css['core/misc/opensans/opensans.css'])) {
    unset($css['core/misc/opensans/opensans.css']);
  }
}
```

And then of course override the CSS for `font-family` where needed in the theme's own CSS files.

**Comment by wesruv** [comment]
For some reason I thought the JS was included with that, that's actually not too bad. Feels a little awkward to me, but maybe that's because I'm usually grumpily ripping out crap CSS when I do `hook_css_alter()`.

It'd be nice to add a library removal function, or library alter. But for now I'll recommend this in the tutorial thing I'm working on.

**Comment by jenlampton** [comment]
I created https://github.com/backdrop/backdrop-issues/issues/3718 so we can close this issue as a question (that now has an answer)
