### ISSUE TITLE
Basis should set default font-size in rem units

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2232]
This is more compatible with accessibility features in browsers.

**Comment by wesruv** [comment]
PR Here: https://github.com/backdrop/backdrop/pull/1587

**Comment by quicksketch** [comment]
Thanks @wesruv! Merged into https://github.com/backdrop/backdrop/pull/1587. Thanks for the code comment. In my testing, switching between 16px and 1rem resulted in identical output, so this has no visual impact at all.
