### ISSUE TITLE
[UX] Page title block: summary text not updated upon dialog save (plus better title summary format)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2234]
Depending on the user choice of the 4 different types of title, the description text you get is this:

"Default page title"
"Custom page title _My Custom Title_"
"Title copied from block _Promoted content_"
"No title"

Lets change them to these instead:

"Default page title"
"Custom page title: _My Custom Title_"
"Title copied from the _Promoted content_ block"
"No title"

Also, the title description is only updated *after* the layout form is saved. When we change something for other blocks (like their visibility conditions for example), they get updated *instantly* upon closing the "Configure block" dialog.

---

PR by @klonos: https://github.com/backdrop/backdrop/pull/1589

**Comment by klonos** [comment]
The part where I change the text is a task, but the part where the page title description s not updated when the "Configure page title" dialog is saved is a bug.

**Comment by klonos** [comment]
So, behavior before PR:

1. Go to the "Manage blocks" page of a layout.
2. Hit the "configure" button of the "Page title" pseudo-region
3. Change the type of the title to anything else.
4. Save the configuration -> Notice how the description on the "Page title" pseudo-region has not changed to reflect your change.
5. Refresh the page -> notice ho the description on the "Page title" pseudo-region has now been updated.

...after the PR, upon hitting the "Save configuration" button (step 4) above, the title type description is updated properly.

**Comment by klonos** [comment]
...plus the minor description format changes.

**Comment by olafgrabienski** [comment]
> Lets change [the title description text] to:
> 
> "Default page title"
> "Custom page title: My Custom Title"
> "Title copied from the Promoted contnet block" [typo]
> "No title"

I've tested the PR - works well, and in my opinion the proposed changes make sense. I'd suggest to use periods as in "The current page breadcrumb trail." Maybe with exception of the Custom page title because of the colon. Such as:

Default page title.
Custom page title: My Custom Title
Title copied from the _Promoted content_ block.
No title.

**Comment by olafgrabienski** [comment]
> ...after the PR, upon hitting the "Save configuration" button [...], the title type description is updated properly

Tested this as well, works like a charm. (Didn't review the code, though.)

**Comment by klonos** [comment]
> ...I'd suggest to use periods as in "The current page breadcrumb trail."...

Hmm...

That text is there as a description of the breadcrumb block - not to display the current settings of that block. The "Page title" pseudo-block is a bit different than the other blocks in the "Manage blocks" page: it has no `layout-editor-block-content` area available, so we show its settings next to the title (in the `layout-editor-block-title` area). For block description text we do use a period, but for the overview of block settings (the "Conditions" fieldset) we do not ...with the exception of the "User has xyz permission." line - don't know why (?):

![backdrop-manage_blocks_page-descriptions_vs_settings_overview-period_or_not](https://cloud.githubusercontent.com/assets/2423362/18915028/de1faab2-85d2-11e6-85bf-330cbfef056f.png)

Hmm...

Also, take the Site status report page for example. We do not use periods for the status of the various entries - only in their descriptions:

![backdrop-site_status_page-no_periods_on_status_entries](https://cloud.githubusercontent.com/assets/2423362/18915037/e5cb9ee2-85d2-11e6-8d65-db6eb163b2fb.png)

...there are exceptions on that page: the cron link (I guess because a period at the end could make people that copy-paste the link instead of clicking it make an accidental selection including the period as well?) and the "Rebuild permissions" link (don't know why). That bottom line though is that although some descriptions have periods while some others not, **none of the status text has periods**.

So, hmm again.

If you still feel strong about it (I have to admit that this situation triggers my OCD too), I think that we should file a separate issue to propose the establishing of a standard on when and where we should use periods or not in the Admin UI. Once we have that standard in place, we can start making changes accordingly, not only to the code of my PR, but against all user-facing text. I fear that changing my current PR now could in the future force us to change it again (if we decide on a standard that dictates removal of the added periods).

This discussion has also surfaced the matter of the difference of the "Page title" block. It might not now be a draggable thing that we can place in a region, but it might as well become one in the future. I would like to propose adding a `layout-editor-block-content` area to it and move the status text there, but this is again a matter of opinions and consensus needs to be reached first, so I'll also leave that for a separate issue.

Anyways, point is that I do not want to delay getting this fix in and to that end, I do not mind even leaving the text changes out altogether for a separate issue too. Let's please leave the PR to "needs review" and see what others have to say before I start making changes.

**Comment by klonos** [comment]
...another example where we do not use periods for displaying status/overview is the vtabs for content types:

![backdrop-content_type_config-vtabs](https://cloud.githubusercontent.com/assets/2423362/18915245/bacef468-85d3-11e6-9f62-7efac4bbbd94.png)

**Comment by olafgrabienski** [comment]
> Hmm... Hmm... So, hmm again.

I totally agree. Guess I changed the issue status too quick as I didn't doublecheck all the places mentioned now by you.

**Comment by klonos** [comment]
...and *technically* that is not a description. It is a summary (of settings). Not sure if we should change the class accordingly(?).

**Comment by klonos** [comment]
No worries @olafgrabienski. All feedback is welcomed. Nit-picking on the code is what makes it better 😉

**Comment by klonos** [comment]
> ...Not sure if we should change the class accordingly(?)

It's more than a class actually. There's the `layout_get_title_description` function name that will need to change (to `layout_get_title_summary`). API change?

**Comment by quicksketch** [comment]
The current PR has some issues dealing with translation: https://github.com/backdrop/backdrop/pull/1589/files#r81272901

I'm fine with removing the colon to make for a more readable sentence, but we need to make sure the result is still translatable.

**Comment by klonos** [comment]
...OK, I have switched to using `switch`/`case` and removed the `$options` array that was holding the `t()`ed text parts. Now the entire `$description` is rendered in a `t()` function for each `case` of `$source` (which is `$layout->settings['title_display'];`). Let me know if I'm getting too funky 😉

**Comment by quicksketch** [comment]
The PR looks great and is a nice improvement, thanks @klonos! Looks like you're getting the handle of `t()`. :wink: Merged https://github.com/backdrop/backdrop/pull/1589 into 1.x for 1.5.1.
