### ISSUE TITLE
[UX] Remove the "Add a" part from the hero and custom block titles.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2241]
![backdrop-page_title-copy_from_block-add_a_hero](https://cloud.githubusercontent.com/assets/2423362/18933132/9858356e-8616-11e6-8d32-3e6231a05a48.png)

...shouldn't this be either "Hero block" or pull whatever is in the _Display title_ field for the hero block instead ("Welcome to Backdrop CMS" by default)?

---

PR by @klonos: https://github.com/backdrop/backdrop/pull/1597

**Comment by klonos** [comment]
...other side-effect of this ("Add block" dialog):

![backdrop-add_block_dialog-custom_and_hero_block_titles_include_add_a](https://cloud.githubusercontent.com/assets/2423362/18981422/6806b3fc-8721-11e6-8faa-4622c9042d97.png)

**Comment by klonos** [comment]
I expect tests to fail (just wanted to file the PR in order to get the sandbox). I'll fix them.

**Comment by klonos** [comment]
Tests green! 😉 

...just a quick question though. What is the logic [with this part of the code](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.admin.inc#L1063)? The way we have it now, it excludes any custom blocks added. Why?

**Comment by jenlampton** [comment]
I'm not sure it's a bug, but giving the `Add block` list some much-needed attention is definitely a UX improvement :) 

Another thought: do all these blocks need to end in the word "Block"? Some items do, some don't. Is it worth being consistent?

**Comment by klonos** [comment]
> I'm not sure it's a bug,...

This issue was initially filed because of the wrong UI text "Add a hero block" that appeared in the drop-down list of blocks making it seem as an action rather than an option (because of the "Add a" part). User confusion = UX bug in my head, but bug or task I don't care so long as it's fixed 😄

**Comment by klonos** [comment]
@jenlampton I did see and comment on those issues you filed. Thank you for those.

Do you have any idea about my question above with regards to the `&& $title !== 'Add a custom block'` check in https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.admin.inc#L1063 ??

**Comment by klonos** [comment]
...and also related: #2256

**Comment by quicksketch** [comment]
> It prevents users from setting a custom block as the source of the page title. Any particular reason we are doing that for?

Perhaps it's just because the custom block lives only within the layout, there's little point in sharing it's title? I'm not sure about this myself, it does seem a little strange.

I think it might make more sense for us to use the `$block->adminLabel()` method here instead of `$block_info['info']`.

**Comment by klonos** [comment]
> I think it might make more sense for us to use the `$block->adminLabel()` method here instead of `$block_info['info']`.

I'm not sure if you are referring to something that needs to be done in my PR @quicksketch or if you are referring to the way we render the "Block to copy" drop-down menu options and the missing entry for any custom blocks present in the current layout, which seems to me like a separate issue (that I would still like to solve). My current PR simply removes the "Add block" prefix from the labels of the hero and custom blocks, which is what this issue here is about.

**Comment by quicksketch** [comment]
Thanks @klonos, I've merged https://github.com/backdrop/backdrop/pull/1597 into 1.x. As this causes a string change and 1.6.0 is right around the corner, I didn't merge this into 1.5.x.

**Comment by klonos** [comment]
@quicksketch we still did not address [this concern of yours](https://github.com/backdrop/backdrop-issues/issues/2241#issuecomment-255044946) (because I didn't understand what you meant actually). Should I file a separate issue for that?
