### ISSUE TITLE
Upgrade to 1.5.0 throws PHP notice

### ISSUE THREAD

**Issue by rstamm** [backdrop/backdrop-issues#2244]
`Notice: Undefined variable: footer in include() (line 31 of /var/www/backdrop/backdrop1p/core/themes/seven/templates/maintenance-page.tpl.php).
`

![backdrop-upgrade-throws-php-notice](https://cloud.githubusercontent.com/assets/6431849/18967916/42418920-8687-11e6-87cf-03e2ee9a94cd.png)

**Comment by dyrer** [comment]
There is a change on 1.5 version, how maintenance pages are handled.
https://api.backdropcms.org/node/44499

**Comment by klonos** [comment]
I think that this is a duplicate of #2187
