### ISSUE TITLE
[UX] Layout UI: Allow blocks & settings to be re-used (Copy Block)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2245]
This is a follow-up from https://github.com/backdrop/backdrop-issues/issues/1886

From @BWPanda 

> So, I propose new functionality something along these lines:
> - Add a new 'Symlink' block (name needs discussion)
> - This block's configuration will have the option to [...] display a specific block from a region in another layout (e.g. Header Block from Header in Default)
> - when this block is rendered it'll display the specific block from the chosen region and layout

From @mikemccaffrey 

>  we create a separate block type called Block Copy, which takes as its configuration a layout and the block within it that you'd like to duplicate in the current layout. That seems like something that could even be added to contrib first to try it out.

**Comment by jenlampton** [comment]
Possibly Related: https://www.drupal.org/project/multiblock

**Comment by docwilmot** [comment]
First try. Needs upgrade and tests of course.

**Comment by jenlampton** [comment]
@quicksketch is worried about introducing dependencies on layouts that could be deleted. I recommended that we limit the layout to the Default layout. @mikemccaffrey said that would create some UI confusion because people would want to copy from any layout, and if we aren't going to solve that problem this shouldn't go into core yet.

Everyone agreed that there was no reason this approach couldn't be contrib module today, tested and improved in contrib, and then merged into core in a later release.

**Comment by BWPanda** [comment]
As per the other [related issue](https://github.com/backdrop/backdrop-issues/issues/1886), I'm going to close this for now in favour of the contrib module: https://github.com/backdrop-contrib/copy_blocks

**Comment by docwilmot** [comment]
I'm wondering if this could be revived for core inclusion for next minor release?

**Comment by jenlampton** [comment]
I think we need to address the issues with the contrib module, but I personally would be open to including something like this in core.

**Comment by klonos** [comment]
I'm also supportive of including the features of copy_blocks in core 👍🏼 

Although the usage stats of the contrib module are low, I think that it's one of those cases where if people knew it existed, they'd use it more.

Having a common header/footer set of blocks that can be updated from a single place and changes reflected for (almost) all layouts is a very common use case IMO.
