### ISSUE TITLE
Basis logo pops out of logo space when not a wide image

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2247]
@When using a square or tall logo the logo pops out of the container and runs into the site navigation:
![screenshot from 2016-09-29 19-31-37](https://cloud.githubusercontent.com/assets/100206/18978916/8707e042-867b-11e6-8b99-feb1708e53cb.png)

**Comment by wesruv** [comment]
wwwwhhhhhaaaatttt! I I went out of my way to prevent this kind of bug!

I'll look into it.

**Comment by wesruv** [comment]
Looks like this is related to https://github.com/backdrop/backdrop-issues/issues/2338

I need PHP helps ☹️ I'm outta my league.

**Comment by wesruv** [comment]
Duplicate of https://github.com/backdrop/backdrop-issues/issues/2338#issuecomment-268913953

**Comment by wesruv** [comment]
![image](https://cloud.githubusercontent.com/assets/5607236/21443946/eac4d594-c876-11e6-9382-08861225448e.png)

**Comment by wesruv** [comment]
From PR on other issue.
