### ISSUE TITLE
Allow creation of custom view modes through the UI.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2250]
In D6 there was [Build Modes](https://www.drupal.org/project/buildmodes) and then its successor [Entity View Modes](https://www.drupal.org/project/entity_view_mode) for D7 that allow you to create custom view modes through the UI. It seems that in D8 they have implemented something like that in core (or a lite version of the respective feature of [Display Suite](https://www.drupal.org/project/ds))...

They have added a new "Display modes" menu under `/admin/structure` that has two submenus: "Form modes" and "View modes":

![d8-display_modes_under_structure](https://cloud.githubusercontent.com/assets/2423362/18980162/ea5efad8-8714-11e6-8f69-531f04c274cb.png)

"Form modes" I guess allows to manage the fields in the "Manage form display" tab (which we don't have in Backdrop - separate issue), while "View modes" allows you to manage the existing **and add new** view modes.

This is part of #378

**Comment by olafgrabienski** [comment]
Maybe a duplicate of https://github.com/backdrop/backdrop-issues/issues/315?

**Comment by klonos** [comment]
Yep, you're right. Thanx.
