### ISSUE TITLE
Continue button on update process is not blue (primary) color.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2253]
![screen shot 2016-09-29 at 11 37 18 pm](https://cloud.githubusercontent.com/assets/397895/18982812/b8f50298-869d-11e6-9411-730fa7253487.png)

---
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1599

**Comment by jenlampton** [comment]
with PR 
![screen shot 2016-09-29 at 11 44 02 pm](https://cloud.githubusercontent.com/assets/397895/18982927/a3ee1db6-869e-11e6-9865-d2790afac59b.png)

**Comment by serundeputy** [comment]
Thanks @jenlampton looks great!  Merged into `1.x` will ship with `1.5.1`.
