### ISSUE TITLE
Basis: issues when used as the admin theme.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2259]
I don't know if we want to support using it as the admin theme, but we are not currently preventing users from doing so. Here's how things look in the "Manage blocks" page:

![backdrop-basis-used_as_admin_theme-manage_blocks_page](https://cloud.githubusercontent.com/assets/2423362/19008502/1058c12a-87af-11e6-8835-17beb8aa9f48.png)

**Comment by klonos** [comment]
...perhaps we could be adding a class like `admin` in the body tag when we are in the admin backend. This way, themes that want to support being used in the admin UI can target things easily or even use a separate admin.css file that holds all their `.admin *` rules.

**Comment by wesruv** [comment]
@klonos great catch!

This one just needs some special love, shouldn't be hard to fix this one.

**Comment by klonos** [comment]
Thanx @wesruv. Not a priority I guess since as I already mentioned I don't think there will be more than a handful of people using Basis as their admin theme.

**Comment by stpaultim** [comment]
Closing as duplicate. https://github.com/backdrop/backdrop-issues/issues/2653

**Comment by klonos** [comment]
Yeah 😞 ...shame on me.

**Comment by stpaultim** [comment]
Shame I me. It was my intention to close it myself. I must have forgotten. 

:-)
