### ISSUE TITLE
CKEditor - uploaded images get absolute URLs

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2261]
Follow-up of https://github.com/backdrop/backdrop-issues/issues/2219, see https://github.com/backdrop/backdrop-issues/issues/2219#issuecomment-250686445.

When I upload an image following **Structure > Custom blocks > Add custom block**, using the image button of CKEditor, the image gets an absolute URL like `http://example.com/files/inline-images/image.png`. See the source code of the editor:

![screen-backdrop-ckeditor-insert-image-absolute-url](https://cloud.githubusercontent.com/assets/14188307/19068488/1d89ee48-8a23-11e6-917f-650ede854ad6.png)

Backdrop shouldn't use absolute image URLs which make it very difficult to manage sites in different environments (test or dev site vs. live), or to move sites to a different domain. Instead of `http://example.com/files/inline-images/image.png` the URL of uploaded images should look as follows: `/files/inline-images/image.png`.

@jenlampton - I'm not sure about the Milestone policy. In my opinion, the issue is quite urgent, so I'd tag it as 1.5.1, is that ok?

---

PR filed at https://github.com/backdrop/backdrop/pull/1605.

**Comment by quicksketch** [comment]
This is a totally reasonable request. A relative to the root of the site URL would indeed be a lot more portable. While solutions like [Pathologic](https://backdropcms.org/project/pathologic) can solve this problem, it'd be convenient to default to excluding the domain name if possible. I'll roll up a PR.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/1605. I don't think we have test coverage on this dialog because it's only accessed through JavaScript, so the change should pass even without updating tests.

**Comment by olafgrabienski** [comment]
As a test I've added an image to CKEditor following two paths:

- Structure > Custom blocks > Add custom block
- Structure > Layouts > Home page > Content (region) > Add Block

In each case, the path was fine: `src="/files/inline-images/my-picture.png`. So, looks good to me from a user perspective.

**Comment by klonos** [comment]
Yep, the code changes seem pretty straight-forward to me (`str_replace` removes the domain part of the url).

**Comment by olafgrabienski** [comment]
@klonos RTBC then?

**Comment by klonos** [comment]
@olafgrabienski there are some tests still failing in the PR as @quicksketch has already mentioned.

**Comment by klonos** [comment]
...the php70 failure seems random to me. Not sure about the layout-related failures in php53 though.

**Comment by quicksketch** [comment]
Yeah, very strange. I reran the tests and they all passed the second time around. We're all green now: https://github.com/backdrop/backdrop/pull/1605.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1605 for 1.5.1 thanks for the great suggestion and for testing @olafgrabienski.

**Comment by klonos** [comment]
...this change broke sites that don't have clean URLs enabled.

Re-opening the issue so that it doesn't slip under the radar of those that do not follow closed issues. Let me know if this should be kept closed and I'll file a separate issue.

**Comment by Dinornis** [comment]
Since this has been merged for 1.5.1in October, if I want to test what is discussed in this issue, should I do the testing in Backdrop 1.5.2 or 1.x ?

**Comment by olafgrabienski** [comment]
> this change broke sites that don't have clean URLs enabled.

@klonos Do you refer to #2220 (clean URLs are not mentioned there) or to another issue?

**Comment by Graham-72** [comment]
@olafgrabienski I don't know what happens without clean URLs enabled but I am still having problems relating to CKEditor and the base_path. I can understand the good sense of this issue here and the removal of the base_url so that it does not get stored in the datatable with the code, but if a file reference needs to use the base_path, as when it is in a subdirectory, this is not getting added back in to the rendered code.

It only seems to be failing when CKEditor is used to add images to a page. Views seems to cope perfectly with sites in subdirectories. Surely there is something better we could be doing (other than not installing Backdrop in a subdirectory)?

**Comment by Graham-72** [comment]
@olafgrabienski @klonos I have been doing some more testing and seem to have now found the solution to my problem with images in CKEditor, at least for my server. I will add a comment to issue #2220 to describe what I have found.

**Comment by olafgrabienski** [comment]
Thanks @Graham-72 , have commented there.

@klonos Can we close the issue now and add the fixed label again, or is there still another issue?

**Comment by klonos** [comment]
@olafgrabienski yes, lets close this one. I've filed #2562 😉

**Comment by olafgrabienski** [comment]
Thanks @klonos . I've also added "status - fixes" again.
