### ISSUE TITLE
Staging directory should not need to be empty on install

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#2262]
When installing backdrop, the system insists that the active configuration directory is empty, which seems like an appropriate safeguard to prevent config from being overridden accidentally, or any old config from sticking around and affecting a new installation. 

However, I'm also getting an error that the staging directory needs to be empty:

`The directory ./config/staging must be completely empty to proceed with installation.`

This doesn't make any sense, since the system would not be adversely affected by old code in the sync directory. And since the staging directory may be under version control, it might not be able to be easily emptied. And if someone is reinstalling their system, it might be to explicitly compare the new config against their staging values.

I'm thinking we should remove this check, either completely, or just display a warning.

---
~PR by @jlfranklin: https://github.com/backdrop/backdrop/pull/1716~
PR by @jlfranklin and @quicksketch: https://github.com/backdrop/backdrop/pull/1845

**Comment by jlfranklin** [comment]
I'd like to see Backdrop offer to import the staging config automatically during install.

**Comment by jlfranklin** [comment]
PR with a patch uploaded.  It does the job, but the UX could be better.  If anyone wants to weigh in on the UX, I'm all ears.

**Comment by quicksketch** [comment]
This looks really good to me. Marking this as needs review so I'll take a closer look at it later. It would be great to have a manual tester run through the following scenarios:

- Default installation.
- Installation with files in the config staging directory.
- Installation with files in the config active directory.
- Installation with files in both directories.

As the installer is not covered by SimpleTest, we can't test these warnings in the automated tests.

**Comment by jlfranklin** [comment]
If someone has a better suggestion for the text of the warning, I'd be happy to change it. It feels a bit alarming and unnecessarily scary to me.

**Comment by quicksketch** [comment]
I updated the PR to rework the messages a bit to be less scary. New PR at https://github.com/backdrop/backdrop/pull/1845. It now reads

```
The staging directory ./files/config_70aa22916764820182572af0126c32e6/staging is not empty. If this is not intentional, empty the directory before using your site.
```

I also added conditions to check if the storage is using files or not. If not, it gives a more generic warning:

```
The staging location is not empty. If this is not intentional, empty the location before using your site.
```

The code itself worked great. I confirmed the proper messages are shown when the active config directory is populated and when the staging directory is populated.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1845 into 1.x for 1.7.0.

**Comment by quicksketch** [comment]
Ah this is a bug! I cherry-picked back into 1.6.x as well.

Thanks @jlfranklin for taking the lead on this one!

**Comment by jenlampton** [comment]
We're having the same problem with updates: https://github.com/backdrop/backdrop-issues/issues/3846
