### ISSUE TITLE
[UX] Make the "Save and add fields" button the default when creating new content types.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2264]
When creating a view, there are three submit buttons available, with the "Continue & Configure" being the primary one:

![backdrop-views-create_view-submit_buttons](https://cloud.githubusercontent.com/assets/2423362/19088519/4276bef8-8ac2-11e6-8661-5d3bdb201427.png)

I was trying to create a new content type last night and because I was tired and doing things in a haste, I clicked the primary submit button. Instead of being redirected to the "Manage fields" form as I expected, I was returned to the list of content types. Sleepy as I was, I almost filed an issue for adding a "Save and add fields" button, before I thought to myself "Wait a minute... I thought we already had that added". Of course we have it. It's just that it's not the primary button in that form:

![backdrop-content_type_create_form_submit_buttons](https://cloud.githubusercontent.com/assets/2423362/19088530/4b771bc4-8ac2-11e6-8e27-5e6007954cbd.png)

Not sure if we need a cancel button here that returns the user to the content type list (`/admin/structure/types`), but **if the content type is being created** (as opposed to an existing one being edited), I think that it makes sense to have the "Save and add fields" button be the primary one. For existing content types being edited, we can leave the current "Save content type" button as primary.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1607 (requires https://github.com/backdrop/backdrop/pull/1611 to work, see https://github.com/backdrop/backdrop-issues/issues/2264#issuecomment-252383112)
~~alternative PR by @klonos: https://github.com/backdrop/backdrop/pull/1608 (not that intuitive, see https://github.com/backdrop/backdrop-issues/issues/2264#issuecomment-252277328)~~
alternative PR by @klonos: https://github.com/backdrop/backdrop/pull/1610

**Comment by klonos** [comment]
Here's what I've got so far:

![backdrop-issue2264-pr1607-button_classes_cannot_be_unset](https://cloud.githubusercontent.com/assets/2423362/19193319/5cad42ee-8cf5-11e6-8154-a2bd9e63ea10.png)

...this is the content type *add* page - the content type *edit* page buttons are left unchanged. So:

1. Changing of the order of the buttons works (by changing the `'#weight'` of the 'Save and add fields' button to a lower value in [`field_ui_form_node_type_form_alter`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/field_ui/field_ui.module#L330)) 👍 
2. `button-primary` is successfully added to the 'Save and add fields' button (by setting the `'#attributes'` value of the 'Save and add fields' button [`field_ui_form_node_type_form_alter`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/field_ui/field_ui.module#L330)) 👍 
3. Using `unset($form['actions']['save_continue']['#attributes']['class']);` and `unset($form['actions']['submit']['#attributes']['class']);` in order to remove the pre-existing classes for the two buttons (not in the PR) does not work, so the 'Save and add fields' ends up with both primary and secondary classes: `class="button-primary button-secondary form-submit"` and the 'Save content type' button retains its primary class too: `class="button-primary form-submit"`. 👎 😕 

What am I doing wrong here?

**Comment by klonos** [comment]
...but then again, if `unset` removes the classes, that would also remove the `form-submit` class. I don't want to do that.Is there a better way to remove/replace specific classes?

**Comment by klonos** [comment]
...the only way to get this to work is to change the `save_continue` button to a `submit`, re-create the plain "Save content type" button as `$form['actions']['save']` with a higher `'#weight'` and finally, (in order to get the redirection to the "Manage fields" page to work) change the condition in [`field_ui_form_node_type_form_submit`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/field_ui/field_ui.module#L347) so that it's triggered by `'submit'` instead of `'save_continue'`.

Not very good DX there ...for an admittedly inexperienced "non-coder" that is 😄 

...anyways, should I just give up trying to override things and in order to get my original PR to work and just go with the non-intuitive way that works, or is there something I am don't wrong in my PR?

**Comment by klonos** [comment]
I think that the root cause of all this frustration is the (very smart and DX-friendly otherwise) automatic addition of primary/secondary classes in [`form_process_actions`](https://github.com/backdrop/backdrop/blob/1.x/core/includes/form.inc#L3348). Perhaps there is room there for improvement in the logic, but beyond my skills I guess.

> ...Is there a better way to remove/replace specific classes?

...to answer my own question: [Drupal 7: How to remove a HTML class from a form item using hook form_alter](https://gist.github.com/phile/4081365) ...but I think it'd be very hackish.

**Comment by quicksketch** [comment]
> I think that the root cause of all this frustration is the (very smart and DX-friendly otherwise) automatic addition of primary/secondary classes in form_process_actions. Perhaps there is room there for improvement in the logic, but beyond my skills I guess.

I think the problem with that logic may be that it doesn't reorder the elements before it automatically adds the classes. Just setting the weight of the "Save and add fields" button to a lower value than the "Save content type" button should do the job, but it's not. I think we just need to adjust `form_process_actions()` to force the checking of element order by changing `element_children($element)` to `element_children($element, TRUE)`

**Comment by klonos** [comment]
New PR that replaces both previous ones: https://github.com/backdrop/backdrop/pull/1610

Moved all the logic for the "Save and add fields" button in `node.types.inc` with the rest of the buttons. It looks simpler and more rational to me and while coding it I wondered why it was not done like so in the first place. Please review and tell me what you think.

**Comment by klonos** [comment]
...all tests came back green, so I didn't break anything major 😜

**Comment by olafgrabienski** [comment]
@klonos Adding a content type on the test site, I see no "Save and add fields" button at all:

![screen-backdrop-add-content-type-button](https://cloud.githubusercontent.com/assets/14188307/19215465/3edfd2cc-8d9f-11e6-833c-98677299396e.png)

**Comment by klonos** [comment]
@olafgrabienski that's because I *intentionally* disabled the Field UI module(1)(2). This module, like the Views UI module, can be enabled/disabled(3), so I wanted to test that use case, because if that module was in fact disabled, then clicking the 'Save and add fields' button would cause either php errors(4) or "page not found" errors ...or both. To avoid those errors n that scenario, I use a `module_exists('field_ui')` condition in https://github.com/backdrop/backdrop/pull/1610/files#diff-43644fbb2a95f2cc17b6b68f7e5b08a5R291 that only renders the 'Save and add fields' button if the Field UI module is enabled. So, long story short, if you enable the Field UI module, you'll see the 'Save and add fields' button in the 'Add content type' form and if you disable it, you won't see it. That is the intentional logic of my code.

(1) just to clarify: I **manually** disabled the Field UI module on the sandbox during testing - my code in the PR does not do that.
(2) field_ui.module is the one that provides the "Manage fields" pages/tabs for all content types and in general the UI for adding/removing/reordering fields in other entities.
(3) contrary to some other core modules like field.module or views.module for example that are required and thus always enabled + hidden from the modules page.
(4) the `_field_ui_bundle_admin_path` which is a function that [is called to generate the form redirection path to the "Manage fields" tab of the newly-created content type](https://github.com/backdrop/backdrop/pull/1610/files#diff-43644fbb2a95f2cc17b6b68f7e5b08a5R421), lives inside the `field_ui.module` file, which won't be loaded if the Field UI module is disabled.

**Comment by klonos** [comment]
...so, long story short, if you enable the Field UI module, you'll see the 'Save and add fields' button in the 'Add content type' form and if you disable it, you won't see it. That is the intentional logic of my code 😉

**Comment by olafgrabienski** [comment]
@klonos Thanks for your hint. I enabled the Field UI temporarily, and that was the result:

![screen-backdrop-add-content-type-buttons](https://cloud.githubusercontent.com/assets/14188307/19216243/4dd18a72-8db4-11e6-8727-fb9bf10efb47.png)

**Comment by serundeputy** [comment]
@klonos I've left some feed back on the `PR`.

**Comment by klonos** [comment]
Thanx @serundeputy. As explained in the PR comments, I've opened a separate issue for @quicksketch's finding since that one seems to be a generic fix. Once the PR for that is committed (if it doesn't break things), my PR in https://github.com/backdrop/backdrop/pull/1607 (which I've re-opened and updated) should just work.

**Comment by klonos** [comment]
...I've updated both PRs to add a cancel button on both add/edit forms.

**Comment by quicksketch** [comment]
Looks great, I've merged https://github.com/backdrop/backdrop/pull/1607 into 1.x for 1.5.1. Thanks!
