### ISSUE TITLE
Basis: Contextual links are HUGE on the hero block

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2268]
Follow-up to https://github.com/backdrop/backdrop-issues/issues/2206, where the contextual links were fixed on the hero block. The contextual links are really big when expanded compared to the rest of the page.

Hero links:

![selection_188](https://cloud.githubusercontent.com/assets/100206/19173620/70de70b2-8bdd-11e6-95a9-8b243a567724.png)

vs. node links:

![selection_190](https://cloud.githubusercontent.com/assets/100206/19173623/75bf455c-8bdd-11e6-8a85-d81e06c678e5.png)

**Comment by wesruv** [comment]
PR here: https://github.com/backdrop/backdrop/pull/1617

**Comment by quicksketch** [comment]
Thanks for the PR @wesruv! I tried it out in the sandbox, and the result is exactly the same. It looks like maybe the CSS in `contextual.css` is winning because it has the overly-specific target that includes `div`?

```
div.contextual-links-wrapper {
  display: none;
  font-size: 90%;
  position: absolute;
  right: 5px; /* LTR */
  top: 2px;
  z-index: 999;
}
```

**Comment by wesruv** [comment]
Wrote it blind in Github's UI and didn't get back to checking it when it was done building. Should be fixed now.

**Comment by quicksketch** [comment]
Could we take it the other way and fix `contextual.css` to be less-specific? That seems more inline with the other fixes we've been making to CSS to make for less aggressive targeting in themes.

**Comment by quicksketch** [comment]
Now that I know where the CSS should live in Basis, I used the first approach you suggested but "fixed" contextual.css so that it uses less-specific selectors. Now the original approach does the job. Thanks!

Merged in https://github.com/backdrop/backdrop/pull/1620 for 1.5.2.
