### ISSUE TITLE
authorize.php does not allow entering FTP credentials

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2270]
There is an issue with the authorize.php file in that it doesn't allow you to enter FTP credentials if it determines FTP is needed in the first place. It works fine if the site root owner is the same as the web server user.

To reproduce:

- `sudo chown root:root ~/Sites/backdrop` (the root directory or wherever settings.php is stored).
- Manually install a module through Project Browser (via URL or file upload).
- Be redirected to authorize.php. You get this page:
![screenshot from 2016-10-07 12-55-19](https://cloud.githubusercontent.com/assets/100206/19203706/951279c8-8c8d-11e6-9eaf-794d3dee6187.png)

Note that there are no options for entering credentials, they appear to be hidden with JavaScript or CSS.

**Comment by quicksketch** [comment]
Looks like this is a simple fix, just an issue with the `#states` targeting the container element. PR filed at https://github.com/backdrop/backdrop/issues/1609.

**Comment by klonos** [comment]
Trivial change. RTBC from me 👍

**Comment by quicksketch** [comment]
Thanks @klonos! Merged in for 1.5.1.
