### ISSUE TITLE
Fix the logic that adds the primary class to the first button on forms.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2272]
This was discovered by @quicksketch while trying to solve https://github.com/backdrop/backdrop-issues/issues/2264

>> I think that the root cause of all this frustration is the (very smart and DX-friendly otherwise) automatic addition of primary/secondary classes in form_process_actions. Perhaps there is room there for improvement in the logic, but beyond my skills I guess.

>I think the problem with that logic may be that it doesn't reorder the elements before it automatically adds the classes. Just setting the weight of the "Save and add fields" button to a lower value than the "Save content type" button should do the job, but it's not. I think we just need to adjust `form_process_actions()` to force the checking of element order by changing `element_children($element)` to `element_children($element, TRUE)`

**Comment by quicksketch** [comment]
Thanks @klonos! Merged https://github.com/backdrop/backdrop/pull/1611 for 1.5.1
