### ISSUE TITLE
[DEP] Menu.inc:639 calls deprecated function taxonomy_vocabulary_machine_name_load()

### ISSUE THREAD

**Issue by sentaidigital** [backdrop/backdrop-issues#2273]
Warning message when flushing caches, or when logging in:

"The function _menu_load_objects() (menu.inc:639) called deprecated function taxonomy_vocabulary_machine_name_load(). It will be removed in the next major release of Backdrop."

**Comment by klonos** [comment]
A few years have passed, and nobody else reported this error. I will go ahead and close the issue as outdated, but please feel free to reopen if this is still an issue.

**Comment by klonos** [comment]
This function is being used in Views 7.x (d.org API: [taxonomy_vocabulary_machine_name_load()](https://api.drupal.org/api/drupal/modules!taxonomy!taxonomy.module/function/taxonomy_vocabulary_machine_name_load/7.x)).

We have included a wrapper function for it in taxonomy.module, with `watchdog_deprecated_function()`. See https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_vocabulary_machine_name_load/1
