### ISSUE TITLE
Replace modules and permissions checkboxes with switches

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2274]
I have never really thought about this before, but it just occurred to me that throughout Backdrop checkboxes are generally used for selecting multiple items and then doing something with them (e.g. delete, publish, etc.). However, on the modules and permissions pages, checkboxes are used for enabling or disabling something, not performing a bulk operation.

I think this could be confusing for some users, so I'd like to suggest making the checkboxes on the modules and permissions pages switches instead.

Examples of switches:
- [Module filter](https://www.drupal.org/project/module_filter) module ([screenshot](https://www.drupal.org/files/project-images/Module%20Filter%202.0.png))
- http://schoberg.net/lab/jquery-toggle-switches/
- http://abpetkov.github.io/switchery/
- http://www.bootstrap-switch.org/

**Comment by klonos** [comment]
@BWPanda the switches should be used for thingies that happen instantly, soon as you hit the switch. Think Mac OS, or Android, where there is no "Save" after you made a change in most settings/dialogs.

I personally find it a confusing UI pattern (unless the switch actually applies the change instantly, in some AJAXy/magic way), and if not mistaken, people miss clicking the submit button when you swap checkboxes for switches.

**Comment by klonos** [comment]
...having said that, if we had confirmation dialogs pop up within the page, after the user switched a module on/off, we could do this. In which case, #2532 is related.

**Comment by BWPanda** [comment]
I think we can close this issue as a 'won't fix'.

**Comment by klonos** [comment]
...yeah. FTR, this was also brought up in the Module Filter module issue queue in d.org: https://www.drupal.org/project/module_filter/issues/2485147

>The control used (the graphical on/off switch) is designed to be used on actions that are undertaken immediately (think about a light switch), which is not the case. There is a warning about this on the settings page, but people should not be forced to go to there to be educated about this. Usually the Save button is below the fold, which make things worst, as it implies that no other action is required. Lastly, the combination of green (on), red (off) and grayed on/off is very confusing.
>
>IMHO, all this make this feature very bad, in terms of UX. The end user is much better served with checkboxes.

...I also found the last comment in that issue interesting and enlightening:

>Secondly, switches are not the most understood UX elements simply because they are not physical elements that every person saw in their life: same as electricity sockets, light switches (the most commonly used switches) differ from country-to-country. For me personally, the state of this switch is never clear as in Eastern European countries (where I'm originally from) the switches markings are written outside of the the switch elements, so you usually move the toggle _towards_ a side where the marking is specified. This is visually totally opposite to how the switches in this module show state.
