### ISSUE TITLE
How to add different plugins to CKEditor?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2276]
I'd like to add a plugin to CKEditor (specifically http://ckeditor.com/addon/templates) but I'm not quite sure how...

Could someone please point me in the right direction?

**Comment by quicksketch** [comment]
You can check out how CKEditor module adds its own (external) libraries that are used for image and link handling. The basic idea is to use [`hook_ckeditor_plugins()`](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.api.php/function/hook_ckeditor_plugins/1) to expose a plugin. Typically you'd download the plugin an place it directly within your module.

CKEditor module uses this hook to add even its own plugins. See [`ckeditor_ckeditor_plugins()`](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.module/function/ckeditor_ckeditor_plugins/1).

**Comment by BWPanda** [comment]
Thanks!

**Comment by BWPanda** [comment]
I'm now trying to add the [Media Embed](http://ckeditor.com/addon/embed) plugin and am having issues I'd like help with please.

I was previously able to add the [oEmbed](http://ckeditor.com/addon/oembed) plugin, that was easy. However the Embed plugin requires the [Media Embed Base](http://ckeditor.com/addon/embedbase) plugin, and that's where the problem is.

When I setup Embed in `hook_ckeditor_plugins()` (with or without Embed Base specified as well), the button appears fine in the editor configuration, but when I try to add content using that text format, the editor doesn't appear at all and I get this error in the Javascript console:

`TypeError: h is null                                                /misc/ckeditor/ckeditor.js?v=4.5.9 (line 250, col 242)`

If I add `'dependencies' => array('embedbase')` to the Embed button configuration, then I get different errors regarding it not finding embedbase in `/misc/ckeditor/plugins`.

Any idea how I can get this working?

**Comment by robertgarrigos** [comment]
@quicksketch Does it mean we could have a contrib module just to add an specific ckeditor plugin?

**Comment by BWPanda** [comment]
I'm no longer needing to do what I was asking in https://github.com/backdrop/backdrop-issues/issues/2276#issuecomment-296496554 above, so will close this issue.

For anyone needing to add a plugin to CKEditor, here's a module I've written that does that with the oEmbed plugin (feel free to use it as a reference): https://github.com/backdrop-contrib/oembed
