### ISSUE TITLE
Admin menu doesn't update after adding, updating or deleting a field

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#2279]
When you add a field to a content type, it doesn't immediately become visible in the admin menu as an option under Manage Fields or Manage Display: 

![new_fields_missing](https://cloud.githubusercontent.com/assets/1134098/19414113/d86cfd0e-92f7-11e6-9704-dd1b7a0214b7.png)

And when you delete a field from a content type, it similarly doesn't update the menu, and a link to edit the field sticks around even after that form is gone.

We should clear the menu cache when a field is added to or deleted from a content type or other entity.

---

~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1614~~
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1618~~
PR by @klonos: https://github.com/backdrop/backdrop/pull/1622

**Comment by klonos** [comment]
...same when a field is updated (renamed).

**Comment by klonos** [comment]
This one-liner seems to fix the issue. Not sure if that's the right way to do things, but if it is, then I might create another PR for the same issue with vocabularies 😉

**Comment by klonos** [comment]
...it seems that I broke all tests!!! 😞 

```
Exception PDOExcepti field_ui.admin.in 2107 field_ui_field_edit_form_submit()  
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.simpletest[random_number_here]cache_admin_bar' doesn't exist: TRUNCATE {cache_admin_bar} ; Array
```

**Comment by quicksketch** [comment]
To implement this properly, I think we'll need to implement these hooks in admin_bar.module:

- `hook_field_create_instance()`
- `hook_field_update_instance()`
- `hook_field_delete_instance()`

We shouldn't put cache clearing directly in `field.module` because Admin Bar may not be enabled, which is probably the cause of the test failures (the testing profile doesn't enable Admin Bar).

**Comment by mikemccaffrey** [comment]
> We shouldn't put cache clearing directly in field.module because Admin Bar may not be enabled, which is probably the cause of the test failures (the testing profile doesn't enable Admin Bar).

The admin menu itself should still exist, even if the Admin Bar is not enabled?  Would it be overkill to call a full menu_rebuild()?

**Comment by klonos** [comment]
@quicksketch, is there a convention as to where in the .module function we insert new `hook_` functions? Do we go alphabetically or random? Are there any factors for specific hooks that should go first/last or after another hook etc?

**Comment by klonos** [comment]
New PR: https://github.com/backdrop/backdrop/pull/1618

**Comment by klonos** [comment]
...tested adding, renaming and deleting fields and the admin menu is updated properly. Waiting for the tests to finish (but the php53 sandbox/test seems to be having the https://github.com/backdrop-ops/backdropcms.org/issues/276 issue). I went with adding the hooks at the end of `admin_bar.module` - let me know if they need to be moved around.

**Comment by klonos** [comment]
...no time to fix tests now (or check if they are random). Will have to return to this later tonight.

**Comment by klonos** [comment]
...php53 came back green and php70 seems to be random. Settingback to NR 😉

**Comment by quicksketch** [comment]
> Would it be overkill to call a full menu_rebuild()?

We already fire a full menu rebuild, but I think because the list of fields is dynamic, they don't actually have individual entries in the administration menu hierarchy. The fields are added by admin bar in `field_ui_admin_bar_map()` (which despite its name, is in `admin_bar.map.inc`, not in `field_ui.module`).

So I think the hooks are the right way to go, admin bar registers the entries manually, so it needs to be responsible for clearing after an update.

**Comment by quicksketch** [comment]
> @quicksketch, is there a convention as to where in the .module function we insert new hook_ functions? Do we go alphabetically or random? Are there any factors for specific hooks that should go first/last or after another hook etc?

Generally, no. But, personally I prefer to put `hook_menu()` at the top, as it's sort of the "table of contents" for a module's pages. After that I tend to group hooks near the top and less important functions towards the bottom.

In this case however, we already have a bunch of other hooks that do the exact same thing:

```
admin_bar_menu_link_insert
admin_bar_menu_link_update
admin_bar_menu_link_delete
admin_bar_language_update
admin_bar_language_delete
```

Could you move your code to follow after `admin_bar_language_delete()`?

**Comment by klonos** [comment]
> Could you move your code to follow after `admin_bar_language_delete()`?

Done.

**Comment by klonos** [comment]
Don't know how to resolve merge conflicts through the GitHub UI (or even if that is possible in the first place), so I've closed the PR and created a new one in its place.

**Comment by klonos** [comment]
...all tests are green. Ready for review 😄

**Comment by klonos** [comment]
@quicksketch now with brackets after the hook names in `* Implements hook_` 😉

**Comment by quicksketch** [comment]
Super, finally merged https://github.com/backdrop/backdrop/pull/1622 into 1.x and 1.5.x. Thanks!
