### ISSUE TITLE
Installation problems, especially with 'invalid archives'

### ISSUE THREAD

**Issue by LeeteqXV** [backdrop/backdrop-issues#2280]
Today I finally got to start exploring the exciting 1.5.x :-)
The general progress and features looks very promising.

Some installation issues when installing 1.5.0 on LAMP with PHP 5.5.35: 

a) the installer reports invalid archive for these modules:
ejector_seat
eu_cookie_compliance
oauth_common
session_expire
session_limit

I tried several times with eu_cookie_compliance, deleting the files on the server between each time, and suddenly that one installed fine, but that did not help with the others. Cannot be sure if the "invalid archive" is a precise error, or if network issues/timeouts, bad downloads, etc. may be the culprit here. Manual installation from within the BD gui, uploading a file I download from BD works sometimes, but not all. Does this mean that several of the files or downloads are corrupted on/from the server? I have no problems downloading from other servers...

b) Why should the "rest" of the modules in the installation queue choke and stall when such errors occur? Why cannot the installer skip over the problems, install the rest of the modules in the queue and at the end return to display the errors for those that failed?

c) For this reason (b), it would be practical if the list of queued modules could be resorted using drag-n-drop, so that we could try again with other modules while still keeping the troublesome in the queue I can also think of other reasons (performance/memory) that would trigger a wish to re-order that list before installing. After all, for now, with relatively few modules in the repository, we go through the pages adding modules one by one so that the order of the installation is totally random, only determined by which module happens to have the latest release, as it is in that order they are displayed through those pages.

d) After installation, sometimes the landing page is the Themes page with no context (and I did not install any themes during that batch.) Strange.

**Comment by dyrer** [comment]
I still having problem with eu-cookie-compliance
https://www.screencast.com/t/MNc5vdky787F

**Comment by laryn** [comment]
@dyrer I think that should be posted in the Issues queue for that module so it gets the maintainer's attention:
https://github.com/backdrop-contrib/eu_cookie_compliance

**Comment by klonos** [comment]
I am closing this as outdated. Please feel free to reopen if it is still and issue.
