### ISSUE TITLE
Featured projects

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2281]
I had an idea about creating 'featured' projects for Backdrop. When new users want a certain feature, they can be overwhelmed with the choices that contrib provides, especially with seemingly duplicate modules that do the same thing in slightly different ways.

So I thought to suggest that Backdrop advertise 'featured' modules (can also be extended to themes and layouts maybe) that are the recommended way to perform certain tasks. For example, want a custom form, use Webform. Webform could become a 'featured' module, and these would be displayed at the top of search results, and maybe even have a page of their own, so new users know where to start with a new website. These 'featured' modules would essentially be halfway between core and contrib - officially supported/recommended by Backdrop, but still in contrib (and would likely be the first candidates for inclusion in core in future).

Other, similar contrib modules can still exist, and can even add extra functionality to these 'featured' modules (think Webform extensions), but where possible, effects should be combined in these 'featured' modules rather than duplicating functionality elsewhere.

**Comment by quicksketch** [comment]
Could you refile this issue over in https://github.com/backdrop-ops/backdropcms.org/issues/ ? We'd need to implement this functionality on backdropcms.org first for it to be applied to the project installer.

**Comment by BWPanda** [comment]
Done :)
