### ISSUE TITLE
Admin menu doesn't update after updating or deleting a vocabulary.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2285]
This is a sibling issue to #2279 and part of the #1867 meta-issue...

Contrary to the actions upon fields, the admin bar is updated when *adding* a new vocabulary - it is not updated when renaming or deleting vocabularies though.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1619

**Comment by klonos** [comment]
I do not see any `cache('admin_bar')->flush();` implemented in a `hook_taxonomy_vocabulary_insert` anywhere, so this must be done via some other means. My PR includes a cache clear for the vocabulary insert action for posterity. Let me know if you think that it should be removed (performance concerns perhaps?).

Both this as well as #2279 touch on the same file (`admin_bar.module `), so I think that I might need to update my PR after that one is merged. Nevertheless, still filing a PR in order to get feedback and get a free sandbox to test if the solution actually works.

**Comment by klonos** [comment]
...it works! Waiting for the tests to finish 😉

**Comment by klonos** [comment]
...and tests are green 😄

**Comment by quicksketch** [comment]
Great, merged in https://github.com/backdrop/backdrop/pull/1619 for 1.5.2 :smile:
