### ISSUE TITLE
[UX] Add a link to the 'Site information' page from the header block options for logo, site name, and site slogan.

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2287]
I've caught myself doing this multiple times. I want to change the site name or site logo. I hover over the site name, use the contextual links to "Edit block". Okay, now I can turn on/off the logo/name/slogan. But what I want to do is _change_ them. Of course this is a site-wide setting, not block-specific, but it would help tremendously if we just added description text:

`The site name, logo, and other settings may be changed on the site information page.`

And linked "site information page" to the appropriate path.

---

~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1627~~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1723

**Comment by klonos** [comment]
Let me give this a go...

**Comment by klonos** [comment]
...alright, not as easy as I thought, but not that hard either. PR coming up, but while testing things I discovered a bug. Let me file an issue for it before I forget and then the PR 😄

**Comment by klonos** [comment]
These checkboxes are there as individual elements, but the description text would apply to all of them. I could have added the description to the site slogan checkbox only, but that seemed wrong and could potentially cause issues in the future (not to mention setting a bad example). So I ended up wrapping the checkboxes to a fieldset and added the description text to it instead which seemed more appropriate. That though changes the way settings are stored for the block in the respective section for the block in the layout .json files from this:

```json
"block_settings": {
    "menu": "user-menu",
    "logo": 1,
    "site_name": 1,
    "site_slogan": 1
}
```

...to this:

```json
"block_settings": {
    "menu": "user-menu",
    "site_info": {
        "logo": 1,
        "site_name": 1,
        "site_slogan": 1
    }
}
```

Update hook required?

**Comment by klonos** [comment]
![backdrop-issue2287-pull1627](https://cloud.githubusercontent.com/assets/2423362/19619901/f47e929e-98bc-11e6-82dc-a384930c6623.png)

**Comment by klonos** [comment]
A couple of ideas to improve the UX even further (will file follow-up issues):

1. Add a "Site information" contextual link to the header blocks that takes the user straight to the Site information page. Perhaps instead of having the contextual link open the Site info page, have a modal open in the front-end?
2. Only show the "Site slogan" checkbox if a slogan has been defined in the site settings.

**Comment by jenlampton** [comment]
I'm not sure this is a feature request, aren't we just solving a UX problem? Perhaps this is a task? Retagging so this can get in after Jan 1st if necessary.

**Comment by jenlampton** [comment]
Rebased and addressed comments.

**Comment by Dinornis** [comment]
@jenlampton 
Going to the 1723 PR I am greeted with an install screen.

**Comment by jenlampton** [comment]
I'll close and reopen. See if that fixes it :/

**Comment by Dinornis** [comment]
Closing and reopening the PR fixed it.
Link from the configure header block works great.

**Comment by quicksketch** [comment]
Thanks @Dinornis and @jenlampton! The new PR looks great. Merged https://github.com/backdrop/backdrop/pull/1723 into 1.x for 1.6.0.
