### ISSUE TITLE
Floated content inside of Rich Text areas breaks outside container

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2295]
Probably need a clearfix.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop-issues/issues/2982 is a similar issue.

Looking at this fix vs. that one, I actually think *both* might be appropriate. While that other issue suggests adding clearfix to the entire node's content, this issue would fix the display of the body field pretty much everywhere it is used. Though to make this more comprehensive, I'd suggest that we do it both on `text_with_summary` and `text_long` fields. Right now this only covers text with summary.

**Comment by quicksketch** [comment]
I rerolled https://github.com/backdrop/backdrop/pull/1625 and added an extra selector to target long text fields as well.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1625 into 1.x and 1.11.x.
