### ISSUE TITLE
Center hero image by default

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2296]
We think this will get closer to the expected default experience in conjunction with background-size cover

**Comment by quicksketch** [comment]
My experiences with this particular problem indicate it's better to go with top in the event you have any figures (people, characters, robots, etc), centering results in a lot of headless people. It depends on the image of course, but I believe top would cause fewer problems than center. Marking for additional feedback, if anyone else has an opinion on this one.

**Comment by Dinornis** [comment]
I also think top as default would be better.
Many CMS themes default to center when using user uploaded image for hero or featured image and in many cases causing the problems as described by Nate.

**Comment by quicksketch** [comment]
Unless we have a strong argument for centering vertically, I think we should close out this issue. There's a separate discussion at https://github.com/backdrop/backdrop-issues/issues/2307 to offer some kind of centering or detecting ability, which is much more elaborate than this PR. Let's continue over there if we think this needs to be solved with an option or some kind of dynamic logic.
