### ISSUE TITLE
$enitity->uri() function for file entities does not return options array.

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#2299]
When you call `$enitity->uri()` function on file entities, it does not return the same result as other entity types. Most other entity types return an array with two keys - path and options - with the path being something like "node/1" and the options contain other url options like fragment.

However, files completely exclude the options key, and we should have it return an empty array:
https://api.backdropcms.org/api/backdrop/core%21modules%21system%21file.entity.inc/function/File%3A%3Auri/1

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/1634.

**Comment by serundeputy** [comment]
Thanks @mikemccaffrey  and @quicksketch 
This is merged into `1.5.x` and `1.x` and will ship with `1.5.3` and `1.6.0`.
