### ISSUE TITLE
Add new HTML5 FAPI element: number

### ISSUE THREAD

**Issue by hellomrcat** [backdrop/backdrop-issues#230]
**Problem/Motivation**
We want the html5 number element in core.
See http://www.html5tutorial.info/html5-number.php to see how it looks like.

**Proposed resolution**
Create a form api number element.

**Remaining tasks**
- Create the number element: done
- Create validation handler: done
  ==> the number element requires a step validator, we used the method used in webkit converted to php.
- Create tests: done

**User interface changes**
People will be able to create html5 form api elements

**API changes**
No real api changes. Only additions.

**Comment by quicksketch** [comment]
Coming from https://github.com/backdrop-ops/api.backdropcms.org/issues/9, it turns out this did cause API changes and needs a change record. @juanolalla pointed out:

> Porting Email module, I found a fatal error due to the use of this function that no longer exist in form.inc. I didn't know the reason, and I used the Change Record search to locate it, but there weren't results for "element_validate_integer_positive".

> @quicksketch explained me later in IRC that it was replaced by https://api.backdropcms.org/api/backdrop/core!includes!form.inc/function/form_validate_number/1, and that I had to use $element = array('#type' => 'number', '#min' => 0, '#step' => 1) to validate it.

> I think we should add this info to the Change Records to allow developers finding easily the solution to this problem.

**Comment by jenlampton** [comment]
Is this also worth adding into the drupal backwards compatibility layer?

**Comment by BWPanda** [comment]
Can/should this be added to the [Form API Reference](https://api.backdropcms.org/form_api)?

**Comment by BWPanda** [comment]
Actually, I just found this: https://github.com/backdrop-ops/api.backdropcms.org/issues/6
I think that covers this and other new fields being added to the FAPI...

Feel free to re-close this if you agree.

**Comment by hosef** [comment]
Closing this. Work on the Form API page is happening at backdrop-ops/api.backdropcms.org#66
