### ISSUE TITLE
[UX] Rename "Admin content" and "Comments" to "Manage content" and "Manage comments" respectively.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2301]
This is partially a follow-up to #552 ...

In that issue, I initially suggested to rename the admin bar menu item, the page title and the view label, but we ended up changing only the page title and the menu item.

There's also the "Admin content" view. I think that the admin bar menu item is OK to remain just "Content", but the page title and the view label need to be changed to "Manage content".

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1665~~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1720

**Comment by klonos** [comment]
Question: is changing the actual view machine name an API-breaking change? If not, I would also like to try to create an update hook that copies the config from the `views.view.node_admin_content.json` to a `views.view.manage_content.json` file and also the config from the `views.view.user_admin.json` to a `views.view.manage_user_accounts.json` file and finally updating everything to point to these views. That would make the views labels in the UI be consistent with the respective config file. In general, I propose to be consistent with the naming of the views labels and machine names that we use in the admin UI.

**Comment by jenlampton** [comment]
When we changed the frontpage view to promoted we checked to see if it was in it's default state and only replaced if if it had not been changed. We could do the same here.

**Comment by jenlampton** [comment]
Not sure this is a bug, but [UX] will still make it a priority.

**Comment by jenlampton** [comment]
Does this mean I should make the new view in https://github.com/backdrop/backdrop-issues/issues/2375 "Manage files" ?

**Comment by jenlampton** [comment]
What about the comments listing? Right now it's just "Comments"

**Comment by jenlampton** [comment]
Looks like `Manage user accounts` was successfully handled in https://github.com/backdrop/backdrop-issues/issues/552, changing title again.

**Comment by klonos** [comment]
Left some feedback in the PR. Also...

> When we changed the frontpage view to promoted we checked to see if it was in it's default state and only replaced if if it had not been changed (and changed its machine name). We could do the same here.

Yes, lets do that please.

> Does this mean I should make the new view in #2375 "Manage files" ?

I think yes.

**Comment by klonos** [comment]
How about my PR? It also includes an update hook that renames the view config file and replaces the active config with it if the view has not been customized.

**Comment by jenlampton** [comment]
jeez did I miss another one? :(  I'm sorry. I just looked for the tags "status - has pull request" and since there wasn't one I didn't even check for a PR.

**Comment by klonos** [comment]
No, you're good. I created my PR after you filed yours. It's just that I had the issue assigned to myself and this code ready for almost a month now but never got to actually filing the PR (browser crashed and lost track of open tabs - happens every now and then).

**Comment by jenlampton** [comment]
Ah okay, well I missed that anyway :)  I looked at the PR and the code looks good!  I haven't had time to test it yet. I did wonder about renaming the views to manage_thing instead of thing_manage. Core's a bit split on that right now, but I think I prefer node_manage, file_manage, user_manage, etc.

**Comment by klonos** [comment]
> but I think I prefer node_manage...

So, simply place the "manage" part last or also replace the "content" part with "node" as well (to match the name of the module the view is a part of)?

**Comment by jenlampton** [comment]
Maybe. What do you think?

**Comment by klonos** [comment]
Well, I was going with what the view machine name is (which is what the human-readable name is but all lower case and underscores instead of spaces). Reason is that if one tries to locate the .json file of the view, they only need to know the view name and not the module that created it.

**Comment by jenlampton** [comment]
ah that makes sense. I see you're thinking like a human again!  Let's leave it :)

**Comment by klonos** [comment]
> I see you're thinking like a human again!

😄

**Comment by klonos** [comment]
...all tests came back green ...which means that @Gormartsen must have found some time to fix https://github.com/backdrop-ops/backdropcms.org/issues/276 that has been plaguing my PRs for the past 4 months 👍 🎉 

I decided to have the title attribute in https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/config/views.view.node_admin_content.json#L388 be "Content" instead of "Manage content". This way we get the page title + primary tab combination be:

Content -> Manage content

...instead of:

Manage content -> Manage content

**Comment by jenlampton** [comment]
What does that do to the admin menu? Does it all still work nicely?

**Comment by klonos** [comment]
Yep. It just makes sure that the path from the admin menu (Content -> Manage content) is also reflected on the breadcrumb + page title + primary tab path. These screenshots are from the PR sandbox:

![backdrop-issue2301-pr1665-admin_bar_menu-manage_comments](https://cloud.githubusercontent.com/assets/2423362/21073954/05030d02-bf41-11e6-9615-d0b01a586015.png)
![backdrop-issue2301-pr1665-admin_bar_menu-manage_content](https://cloud.githubusercontent.com/assets/2423362/21073955/0506fafc-bf41-11e6-869b-026afb829a81.png)

**Comment by klonos** [comment]
...also working on #549 😉

**Comment by quicksketch** [comment]
@klonos Thanks for this PR! Overall it looks good from a code-perspective, but I do think renaming the entire view is probably out-of-scope for 1.x. Considering this change essentially means we'd also need to rename the User view (as you have done in #2422). Do you think you could descope this a bit and just manage the page title problems? We do still need an update hook to update existing sites, though I might be a bit aggressive and check what the current title is and change it if it is still the default of 'Admin Content', regardless of whether the rest of the view is in the default or overridden state.

**Comment by Dinornis** [comment]
PR https://github.com/backdrop/backdrop/pull/1720 is initiating an install.

**Comment by quicksketch** [comment]
Thanks @Dinornis for checking on the sandbox, @jenlampton has rebuild it so it available for testing.

I checked out the PR and it works great, but there is one lingering renaming of the view that needs to be reverted. Tests are also failing due to the change of the "No content available." string that needs to be updated.

The update hook looks perfect. Very nicely done!

**Comment by quicksketch** [comment]
I pushed a change to the PR at https://github.com/backdrop/backdrop/pull/1720 that removes the last file renaming. We'll see if tests pass now.

**Comment by jenlampton** [comment]
tests passing, looks good to go.

**Comment by quicksketch** [comment]
Great, merged https://github.com/backdrop/backdrop/pull/1720 into 1.x for 1.6.0.

**Comment by quicksketch** [comment]
As a follow-up, it looks like the Human Label is consistent for all default views except the "Admin Content" view:

![screenshot from 2017-01-14 14-04-07](https://cloud.githubusercontent.com/assets/100206/21958410/594e44ee-da62-11e6-97c7-88e28ade372b.png)


But oddly on new installations, the human_name is "Administer content". So it looks like we're just missing one of the properties when updating from 1.5.x in the update hook. I'll make a new PR.

**Comment by quicksketch** [comment]
Merged the follow-up at https://github.com/backdrop/backdrop/pull/1741 into 1.x for 1.6.0.

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/issues/1741 that amends the existing update hook for users upgrading from 1.5.x.

**Comment by klonos** [comment]
I wish I had chimed in earlier, but I think that we should avoid using the word "[administer](https://www.google.com/search?q=define+administer)" and use "[manage](https://www.google.com/search?q=define+manage)" instead. Perhaps I'm thinking ahead with the translation of the UI (when we have that implemented), but from the definition of the two words, there's far less chances for "manage" to be misinterpreted.

Being consistent between the names of the views is a good thing, but at the same time we should be consistent with their respective admin UI pages and menu items. In other words, I think that the views names should be "Manage content", "Manage users", "Manage comments" and "Manage files". I also think that for consistency between the view names and their config files, those should be `views.view.manage_content.json`, `views.view.manage_users.json`, `views.view.manage_comments.json` and `views.view.manage_files.json`, but I think that this was deemed considerable change that needs to happen in 2.x.

**Comment by jenlampton** [comment]
At least they are all consistent. Baby steps :)
