### ISSUE TITLE
[UX] The exposed filter for 'Username' is labeled 'Name' which can be confusing

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2302]
In backdrop-ops/docs.backdropcms.org#196 before assigning the "Editor" role to @olafgrabienski I wanted to first check what roles are assigned to me. So, I logged in to b.org and navigated to the manage user accounts page and searched for "gregory":

![backdropcms org-manage_user_accounts-search_only_by_username](https://cloud.githubusercontent.com/assets/2423362/19617144/8dab7e4e-9874-11e6-99ab-c47df7760316.png)

There were no results because the exposed search filter "Name" only searches by username. So, I've changed that to a "Global: Combine fields filter" that searches by both username and full name:

![backdropcms org-manage_user_accounts-search_by_username_and_full_name](https://cloud.githubusercontent.com/assets/2423362/19617157/07e20d36-9875-11e6-8fc2-5a398bbdeb94.png)

Lets have that be the default with core so that users don't have to wonder and then have to do the extra work. Things work out of the box = better UX 😉 

---

~PR by @klonos: https://github.com/backdrop/backdrop/pull/1628~
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2207

**Comment by klonos** [comment]
PS: sorry for making the change without filing a proper issue under the borg issue queue @jenlampton. What is the roper way to propose changes for the website? Do we create PRs? If so, how do we do that for views? Do we export the view after we make the changes and provide a diff?

**Comment by jenlampton** [comment]
I think this issue should be filed in the full-name module queue, there is no full name in backdrop core.

**Comment by jenlampton** [comment]
Oh, I see what's going on. Yes, this is confusing. The label for that exposed filter should be `Username`. It searches only the username by default since that's all we know user accounts will have. On backdropcms.org we added a full name, and yes @klonos your change there was a good one. No need for a PR since it was just a config change, just open an issue in the queue letting us know it was done so we can commit the config to git.

**Comment by klonos** [comment]
> ...just open an issue in the queue...

Done 😉 

>Labeling this issue novice.

Oh, me! me! ...

**Comment by klonos** [comment]
In the PR, I've only changed the label in the view .json file. That will only effect new installations, so I need to add an update hook that fixes this on existing ones.

**Comment by quicksketch** [comment]
> That will only effect new installations, so I need to add an update hook that fixes this on existing ones.

The current PR looks great. An update hook would be great though.

**Comment by klonos** [comment]
Questions before I move forward with this PR:

1. I have updated the PR to also rename the url identifier. Should we also change any of the other properties?
2. Not sure which file the update hook should go in. `views.install`?
3. Was thinking to first check if the label has already been changed/customized and in that case leave it alone. Thoughts?

**Comment by jenlampton** [comment]
1. sounds good.
2. yes, the .install file.
3. I think checking to see if the view has been customized is enough.  If the view has been changed there may be a lot of additional checking needed.

**Comment by serundeputy** [comment]
Looks like we still need an update hook here moving to `1.6.1` milestone.

**Comment by quicksketch** [comment]
Rerolled the PR with an update hook at https://github.com/backdrop/backdrop/pull/2207. I couldn't apply the old PR (seems the source repo is gone), so I made a new one.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2207 into 1.x and 1.10.x.
