### ISSUE TITLE
[UX] Rephrase "An illegal choice has been detected"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2313]
I don't think these choices are actually breaking any laws. We should rephrase this error message.

How to reproduce the error:
1) log in to your backdrop site
2) Edit your user profie
3) Open dev tools in your browser, and change the `Roles` form element as follows:
- Change the `name` attribute for the `Administrator` option to `roles[administrators]`
- Change the `value` attribute for the `Administrator` option to `administrators`
4) Save the form
5) See the validation error

---

~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1630~~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/2177

**Comment by klonos** [comment]
I'll give this a shot...

**Comment by klonos** [comment]
...how about "Invalid option selected" instead?

**Comment by klonos** [comment]
That text is in the `_form_validate` function in `/core.7/includes/form.inc` and the description of that function is this (emphasis mine): "First ensures required fields are completed, #maxlength is not exceeded, and **selected options were in the list of options given** to the user". So, I guess "Invalid option selected" does make sense.

PR coming up...

**Comment by klonos** [comment]
...random failures with tests as always. Other than that, ready for review.

**Comment by docwilmot** [comment]
@klonos, if we're going to deal with this here, it makes sense to make the error more specific, by naming the actual element that triggered the error.  "No value was set for @field_type @field_name" for example. Haven't looked at the code, so don't know if that's possible, but it would be preferable.

**Comment by klonos** [comment]
@docwilmot I agree that this error is a bit vague and might seem "cryptic" to the end user.

If you look at [the code changes for my PR](https://github.com/backdrop/backdrop/pull/1630/files) (essentially 4 lines changed + another 2 in the form.test), you'll see that there are two separate messages "composed": one for displaying to the end user + another one for logging it in the watchdog for the admin. The one targeted for admin eyes only is in the form of "Invalid option `%option` in `!name` element.".

While creating the PR, I also wondered why we don't simply use the same message for both the admin as well as for the end users (we'd of course need to append the "Please contact the site administrator." part to the message targeted for the end users).

I also noticed that the two messages are repeated in the two conditionals that check whether we're dealing with checkboxes/tableselect or any other kind of multiple select field. Perhaps we should consolidate those as well while at it. Let's see if I'm getting over my head with this (will file a separate, alternative PR in case I screw things up)...

**Comment by jenlampton** [comment]
I'd actually prefer to remove the "Please contact the site administrator." What value does that add, really?

**Comment by klonos** [comment]
> What value does that add?

I can only guess that in case the erroneous option was somehow not malicious, then there must be something wrong with how either the form in question or the options in the specific element that triggered this is set up. In such cases, perhaps the user getting the error might actually want to let the site admin know. Alternatively, as an idea, we can have it so that any WATCHDOG_ERROR in the log triggers the notification badge in the admin toolbar. That way, users won't need to contact the admin.

**Comment by klonos** [comment]
...but I don't have any objection to remove the text is there is no actual reason in keeping it around.

**Comment by jenlampton** [comment]
The problem I have with telling users to contact the site admin is that we don't tell them how to do so. Most people just visiting a website won't have any idea who the website admin is, or how to contact them. 

Also, these errors are usually generated when developers are writing code and got something wrong. In that case, I am the site admin, and telling me to contact myself accomplishes nothing.

It seems like the percentage of the time that telling one person to contact another person and having that instruction actually be helpful is very low.

**Comment by klonos** [comment]
> The problem I have with telling users to contact the site admin is that we don't tell them how to do so. Most people just visiting a website won't have any idea who the website admin is, let alone how to contact them.

Very good point indeed.

**Comment by quicksketch** [comment]
So then it looks like we need another update to the PR. IMO I think the message we log to watchdog() is a good one. It's better that we include the form element name in the error message, so the user (or developer) doesn't have to scroll down to see which element it is, and it won't be dependent upon a theme's CSS for displaying errors.

So I'd recommend:
```
Invalid option %option selected in !name element.
```

**Comment by jenlampton** [comment]
> "First ensures required fields are completed, #maxlength is not exceeded, and selected options were in the list of options given to the user".  So, I guess "Invalid option selected" does make sense.

We should tell the person what the actual problem is.  If the problem is with selected options, we should tell them that. If the problem is with #maxlength, we should tell them that instead.

> The problem I have with telling users to contact the site admin is that we don't tell them how to do so.

And most of the time I get this message, and I am the site admin. I find it slightly insulting that the site tells me to go talk to someone else, instead of giving me the information I need to fix the problem. :/

**Comment by jenlampton** [comment]
@klonos for some reason I was unable to get a `.patch` version of your PR, so I copy/pated your changes and made the updates recommended.  New PR at https://github.com/backdrop/backdrop/pull/2177

**Comment by quicksketch** [comment]
Thanks for rerolling! I has been a while. The PR is not passing tests and I left a comment on the PR: https://github.com/backdrop/backdrop/pull/2177#pullrequestreview-118197050

**Comment by jenlampton** [comment]
Rebased and pushed again, all tests still green.

**Comment by alexfinnarn** [comment]
I'd like to review this, but I don't see a "steps to reproduce" section. Also, I like `// Verify that the value is not longer than #maxlength.` above the maxlength check. Adding a comment above the conditional would help. All I can see is that it's something about checkboxes.

**Comment by jenlampton** [comment]
Added steps to reproduce @quicksketch

**Comment by quicksketch** [comment]
The PR looks great to me and tests are passing. Merged https://github.com/backdrop/backdrop/pull/2177 into 1.x and 1.10.x.
