### ISSUE TITLE
Sticky header cells not properly aligned with the respective cells of the regular header.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2317]
![backdrop-sticky_header_cells_not_properly_aligned](https://cloud.githubusercontent.com/assets/2423362/19859946/2905db74-9fdb-11e6-857b-8c404f4e210f.gif)

PR coming up...

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1632

**Comment by klonos** [comment]
...after the changes (from the PR sandbox):

![backdrop-issue2317-pr1632](https://cloud.githubusercontent.com/assets/2423362/19860316/5ffea7a4-9fdc-11e6-862b-5a530f6b8a13.gif)

**Comment by quicksketch** [comment]
Oddly this was introduced by an attempt to make sticky headers "more accurate", see #2098.

But it's definitely a problem as shown in the screenshot. Moreover, I can't fathom why setting the "width" property using jQuery's `outerWidth()` method would be considered safe. So let's roll back that portion of the changes to fix this bug. Thanks @klonos!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1632 into 1.x and 1.5.x.
