### ISSUE TITLE
SSD VPS in USA or Canada

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2318]
Hello,

Sorry for offtop :)

Can you advice good hosting provider in USA or Canada?
Not expencive.
I need SSD VPS.

Thank you!

**Comment by dyrer** [comment]
This post is not for backdrop issue, should be marked as spam and advertising

**Comment by bd0bd** [comment]
Sorry, my fault. Please forgive me.
But you are wrong - this is not a span and not an advertising.
It was just a question to help me.

By the way, I have already found webhosting. It is Linode.
