### ISSUE TITLE
"Update [project-type]" pages do not filter available updates by what the respective secondary tab labels claim (a bug that I don't really want us to fix).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2323]
In https://github.com/backdrop/backdrop-issues/issues/2315#issuecomment-257811481 I was trying to make a point, but there is actually a bug there: no matter to which "Update x" tab the user switches to, they see the same thing, which is available updates for **all** project types. Even for core.

Steps to reproduce:

1. Intentionally install an old(er) version of a project.
2. Visit the "Available updates" page (`admin/reports/updates`) to verify that there's an update available.
3. Sequentially go to the "Update modules" (`admin/modules/update`), "Update themes" (`admin/appearance/update`) and "Update layouts" (`admin/structure/layouts/update`) pages. -> all pages show the same update, regardless of the type of the project.

This is reproducible with core updates too: all pages show the core update as available, but the tab titles are specifically labeled for either modules/themes/layouts.

Reason why I don't want us to fix this? Because can I please has a single "Updates" page to rule them all (#1718)?

**Comment by klonos** [comment]
Seriously now though, I don't see any value in having separate pages for available updates per project type. Is there a valid use case where one would like to update only their modules and then only their themes and then only their layouts?

I do see the point in having all the updates listed and then having checkboxes in order to be able to select which ones to update. If one would like to filter the list of available updates by project type, then we could do exactly that: add a quick filter (checkboxes) at the top of that page. In fact, I think that we should remove those tabs entirely and simply take advantage of the existing "Available updates" page, have a "show only projects with updates"/"show all projects" toggle and turn this as the single place that users go to in order to view and perform updates.

**Comment by jenlampton** [comment]
> Is there a valid use case where one would like to update only their modules and then only their themes and then only their layouts?

When I'm using a base theme, I only RARELY update it. I only do sp when it's a security update (and even then I check what the fix was and often prefer to apply the patch).

**Comment by jenlampton** [comment]
no PR here, removing milestone.

**Comment by klonos** [comment]
...I'm gonna go ahead and close this in favor of #2714, which I have just brought back to life.
