### ISSUE TITLE
Webiste missing documentation on files directory

### ISSUE THREAD

**Issue by oadaeh** [backdrop/backdrop-issues#2328]
_I'm not sure if this is the right place for this or not, but here is where I'm leaving it. It seems to me that I recall that a long time ago there used to be a specific issue queue for the backdropcms.org website, but I cannot find it now, so maybe it went away._

When installing a new site and w/o preparing settings.php and files, the following is displayed:

> File system	
> The directory files is not writable. To proceed with installation, you must modify the permissions of this directory to make it writable by the web server. If you are unsure how to do this, please see the Installation Instructions page.

"Installation Instructions" is a link to https://backdropcms.org/installation

When going to that page, there is nothing there that discusses the files directory.

There is a bit of a disconnect between the site install and the instructions it references.

**Comment by oadaeh** [comment]
Thanks to @herbdool on Gitter, I now know this belongs in backdrop-ops/backdropcms.org (https://github.com/backdrop-ops/backdropcms.org). However, I do not see how I can move it there. Maybe _I_ can't, but I have seen other issues moved.

**Comment by serundeputy** [comment]
@oadaeh Thanks for reporting! 

This is definitely a fair ask and should be corrected.  Moving the issue to: https://github.com/backdrop-ops/backdropcms.org/issues/311

will pick up discussion and implementation there.
