### ISSUE TITLE
Use of contextual links by non-administrators.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2331]
I would like to create a role 'Site Editor' and give it permission to use contextual links. Setting the permission 'use contextual links' for this new role is having no effect. Is there something else I should be setting?

**Comment by serundeputy** [comment]
@Graham-72  Does the `Site Editor` have the corresponding `Administer custom blocks` permission or views permission or content permission for whatever thing you trying to access to the contextual link for?

**Comment by Graham-72** [comment]
@serundeputy I have set their permission for 'Administer custom blocks'. I am hoping to allow the Site Editor to change an image in a custom block but the contextual links are not there in the page source code.

**Comment by serundeputy** [comment]
@Graham-72 looks like you need to give `Site Editor` these permissions:

* `Administer Layouts`
* `Administer custom blocks`

that should do it.  Let us know how it goes.

**Comment by Graham-72** [comment]
@serundeputy Yes, thanks, giving the Site Editor the Administer Layouts permission does reveal the Contextual Links.

Though I'm not particularly happy to give the Site Editor access to the administer layouts pages. And I find that I have to add the slightly oddly named permission 'View the administration theme' to enable the options to be displayed clearly. (Why isn't it named 'Use the administration theme'?)

Thanks for your help. Perhaps I am being picky in not particularly liking the answer 😃

**Comment by stpaultim** [comment]
Is it ok to close an issue like this (I'm going to do it)? 

It started as a question that has been answered and I am not seeing any specific direction or any clear recommendations or requests. If someone has an idea how to fix this, they can reopen this ticket or start a new one.
