### ISSUE TITLE
getimagesize() in basis theme's template.php returns error if Apache authentication is used.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#2338]
I get:

```
Warning: getimagesize(http://example.com/mytheme/logo.png): failed to open stream: HTTP request failed! HTTP/1.1 401 Authorization Required in basis_preprocess_header() (line 54 of /var/www/vhosts/example/httpdocs/core/themes/basis/template.php).
```

I'm looking for an alternative to getimagesize() or convert the url to the image to the full filepath.

Since we always protect our environments which aren't supposed to be live, we need an alternative to this.  For now, we're using this hack:

```
    global $base_url;
    $logo_path = backdrop_realpath(str_replace($base_url . base_path(), '', $logo));
    $logo_size = getimagesize($logo_path);
```

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1697

**Comment by herbdool** [comment]
@wesruv if you have a moment can you investigate?

To recreate the error you'll need to enable Apache password authentication. Then on any page you'll see the error for getimagesize.

**Comment by klonos** [comment]
> For now, we're using this hack:

> ```
    global $base_url;
    $logo_path = backdrop_realpath(str_replace($base_url . base_path(), '', $logo));
    $logo_size = getimagesize($logo_path);
```

I searched for that code in the current code base and could not find it.

> To recreate the error you'll need to enable Apache password authentication.

I use nginx on my local, but I'll check to see if there's an equivalent. In the meantime, here's a bit of troubleshooting:

- In Basis, with the default settings in `/admin/config/system/site-information` (no logo), a `dpm($logo)` shows nothing.
- With the logo set to "Use the logo supplied by the active theme" it shows `core/themes/basis/logo.png` (but basis has no logo.png file???).
- If you place a logo.png in the Basis folder, `dpm($logo)` shows `http://localhost/core/themes/basis/logo.png` this time.
- If you deselect the "Use the logo supplied by the active theme" setting and upload a custom logo, then you get `http://localhost/files/0_logo.png` (I don't know why we add that 0 there???)

Now, as I said I have not tested this with custom themes and I also have not tested is with password authentication on, but so articles that I found online mentioned that `getimagesize` has issues with relative vs absolute paths when password authentication is used.

Hope that helps.

**Comment by herbdool** [comment]
@klonos, that "hack" I posted is not in core; I created it to get around the issue we were having.

The code in question is on line 54 of core/themes/basis/template.php

`$logo_size = getimagesize($logo);`

Thanks for your initial look. This is an issue where getimagesize() is getting passed the full URL so it's almost like a third-party resource. If Apache Auth is enabled then the URL requires that authentication on it, so better to use the internal path rather than URL.

**Comment by wesruv** [comment]
Ahh sorry, just seeing this now @herbdool, I'm way behind on email 😞 

This is issue is well outside of my comfort zone as a front-ender, I'll bring this up at our next meeting and see if someone can help us out with this, I'm glad you were able to find a workaround!

**Comment by herbdool** [comment]
thanks @wesruv!

**Comment by jenlampton** [comment]
@wesruv can you search the Backdrop codebase for other instances of `getimagesize()`?  I think there are a bunch around image style handling. Let's see how/why the theme layer call is different than those deeper in.

**Comment by herbdool** [comment]
@jenlampton @wesruv I saw two instances of getimagesize() in core. In both cases it's using the internal path to the file rather than the URL. But in basis_preprocess_header() only the URL to the image is available so a different approach to get the path has to be taken.

**Comment by wesruv** [comment]
@herbdool mentioned this was a 'hack', but it works, and to my front ender eyeballs... looks fine? 😄 

Putting it in a PR and hoping someone can say what's better or say this is totes fine.
https://github.com/backdrop/backdrop/pull/1688

**Comment by wesruv** [comment]
![image](https://cloud.githubusercontent.com/assets/5607236/21443942/e7576dfe-c876-11e6-9f5d-9fb012549e5c.png)

**Comment by herbdool** [comment]
thanks @wesruv! I tried again to find a more elegant way using parse_url, but turns out it doesn't look much better. The solution above seems like it works in all cases, even if Backdrop is installed in a sub-directory of webroot (at least I think it does).

**Comment by quicksketch** [comment]
I think the root of the problem here is that we're working with a full URL in the first place. Ideally we'd be able to work with the original file path before it's been manipulated. Or, perhaps it'd be better if we simply calculated the logo height/width and saved that value so we didn't need to calculate it in Basis at all.

How about the following?

- `backdrop_get_logo()` right now returns a string (the URL). We could either add a parameter, or make a new function for `backdrop_get_logo_properties()`.
- This new return value includes `path`, `width`, and `height`.
- We can't change the values passed into `theme('header')`, but we could add a second variable for `$logo_attributes` that includes width and height.
- Basis can be updated to use these values instead of calculating itself.

**Comment by quicksketch** [comment]
@herbdool Could you give https://github.com/backdrop/backdrop/pull/1697 a spin?

**Comment by herbdool** [comment]
Sure!

**Comment by herbdool** [comment]
@quicksketch the good news is that I don't get any errors when I try it on a site with Apache auth enabled. But I tried to recreate the error *before* applying the patch and I was unable. Still, you've managed to avoid getimagesize() for most page loads and only use it with the server path so we've side-stepped the original error.

Thank you!

**Comment by serundeputy** [comment]
@herbdool thanks for all your work on this!

Are you willing to tag it as RTBC and we can get this merged into `1.5.x` and `1.x`?

thanks.

**Comment by herbdool** [comment]
@serundeputy I'm guessing I don't have permission to tag the issue. But yes, RTBC - thanks!

**Comment by jenlampton** [comment]
@herbdool you *should* have permission to change the tags. I will add you if you do not. 

@Gormartsen can we double check that the permission-granter bot is working?

**Comment by serundeputy** [comment]
Thanks @herbool for finding and reviewing this!
Thanks @quicksketch for the PR.

This is merged into `1.x` and `1.5.x` and will ship with `1.5.3` and `1.6.0`!

@quicksketch there were merge conflicts and had to set a default `height` and `width` on the `site_logo_attributes` so tests can pass when trying to save config making sure the array index existed.  Then when I did the merge I stole your commit attribution :( ; I thought it would give you credit or joint credit.
