### ISSUE TITLE
[UX] Installer: Allow using .po translation files from d.org without having to rename them.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2345]
@quicksketch in https://github.com/backdrop/backdrop-issues/issues/2217#issuecomment-248162910:

> ...we don't have adequate documentation in the first place for this. Right now we link to http://drupal.org/localize for instructions when you click "Learn how to install Backdrop in other languages". But the instructions for Drupal aren't the same as they are for Backdrop.

> As for this exact problem, it looks like the file needs to be renamed from `drupal-7.50.de.po` to `install.de.po` then Backdrop will be able to find it.

@olafgrabienski in #2329 

> When I try to install Backdrop in German following the installer instructions and @quicksketch's hint in #2217 (comment) about renaming the language file, ...
>...
> - Download the current Drupal 7 German language file (http://ftp.drupal.org/files/translations/7.x/drupal/drupal-7.51.de.po), rename it to `install.de.po`, and put it in `files/translations`.

The translation files available from https://localize.drupal.org/download are in the format `drupal-%core_ver%.%langcode%.po`, we should be accounting for these filenames when scanning for language files instead of making the users do additional work.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1649

**Comment by klonos** [comment]
@jenlampton before you get upset at me for (ab)using the bug report tag, If this issue had a title of "Translation files downloaded from d.org are not picked up by the installer", then it would be one 😜

**Comment by jenlampton** [comment]
:)

**Comment by quicksketch** [comment]
I feel like this is a good temporary measure, it'd certainly help with new installations and people coming from Drupal until we can provide our own localization server. I think adding a `@todo: Remove "drupal" check in 2.x.` would be appropriate here (assuming we have a localization server by then).

**Comment by klonos** [comment]
@todo added. Sorry for taking ages to respond to PR reviews.

**Comment by olafgrabienski** [comment]
I just tested the PR locally using current Backdrop dev and the [patch by @klonos](https://github.com/backdrop/backdrop/pull/1649/files) . I was able to install Backdrop in German without renaming the `.po` file from drupal.org. Great!

**Comment by quicksketch** [comment]
Thanks @olafgrabienski and @klonos. Merged into 1.x and 1.5.x. Thanks!
