### ISSUE TITLE
Unable to upgrade from D7: Requirements problem: Database system 4 bit UTF-8 support

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2352]
Today I am attempting to upgrade an existing Drupal 7 site to backdrop 1.5.2, and on the "Verify requirements" step of the upgrader (update.php) I'm presented with a big ugly nasty red error:
```
Database system 4 bit UTF-8 support
Database tables need conversion
4 bit UTF-8 support enables extended characters to be saved into the database, including emojis, Asian symbols and mathematical symbols. Your server supports this feature but not all tables have been converted to use it. After making a database backup, you should convert existing tables.
```
Additionally, the link to `convert existing tables` goes to `?q=admin/config/development/utf8mb4-upgrade` which is an error page since I am unable to upgrade:

```
Exception: The configuration directory in settings.php is specified as './files/config_532d2bacbf3c88e1d93f9d4b6971405c/active', but this directory is either empty or missing crucial files. Check that the $config_directories variable is correct in settings.php. in _backdrop_bootstrap_configuration() (line 2899 of backdrop/core/includes/bootstrap.inc).
```

Though I love me some emoji, I don't think this should really be a blocker for people looking to upgrade existing Drupal 7 sites to Backdrop CMS.

**Comment by jenlampton** [comment]
If I comment out the whole if statement `if ($utf8mb4_active) {` in system.install then I am able able to upgrade without any problem.  So, I guess the question is, why is `$connection->utf8mb4IsActive();` returning `TRUE` for Drupal 7 sites that are not using utf8mb4?

**Comment by quicksketch** [comment]
> So, I guess the question is, why is $connection->utf8mb4IsActive(); returning TRUE for Drupal 7 sites that are not using utf8mb4?

This would only happen if `$database_charset = 'utf8mb4';` is set in your `settings.php` file. Note this line is *not* set by default, it should only be added if your system is detected as supporting it. It may be that you copy/pasted an existing settings.php file that had this line.

**Comment by jenlampton** [comment]
Yep, that was it!  okay, I've found and removed the offending line. thank you :)
