### ISSUE TITLE
[DX] make backdrop_uninstall_modules() delete config automatically

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2354]
I had been porting modules under the assumption that config files were both installed and uninstalled automatically. I just found out now that this is not the case. I think it would be a DX win to treat the install & uninstall process consistently.

Question from @BWPanda in https://github.com/backdrop/backdrop-issues/issues/386#issuecomment-60370040

> I previously had variable_del() in hook_uninstall() - do I need to somehow delete my config on uninstall, or is that automatic now?

Answer from @quicksketch : 

> Uninstall cleanup is currently manual, though we could in theory make backdrop_uninstall_modules() read the list of config files out of hook_config_info() and automate this.

**Comment by serundeputy** [comment]
@jenlampton Isn't this here: https://github.com/backdrop/backdrop/pull/534/files

in `includes/install.inc` line `892`:

```php
config_uninstall_config($module);
```

https://github.com/backdrop/backdrop-issues/issues/403

Is it not working for some of your modules?

**Comment by jenlampton** [comment]
Oh, honestly I hadn't even tested it!  I was just doing some research on variable_del and was like "ohnoes I've been doing it wrong!" and opened an issue.  Let me test :)

**Comment by jenlampton** [comment]
yeah, it works. Nevermind this issue! :) and thanks @serundeputy for the sanity check.
