### ISSUE TITLE
Trouble with module config file

### ISSUE THREAD

**Issue by JAyenGreen** [backdrop/backdrop-issues#2358]
I've converted a module and am having trouble getting the config methods replacing the system settings form to cause any change to the config file.

My declaration in the .module file is:

    function x_config_info() {
      $prefixes['x.first_set_of.settings'] = array(
        'label' => t('First set of settings'),
        'group' => t('x'),
      );
      $prefixes['x.second_set_of.settings'] = array(
        'label' => t('Second set of settings'),
        'group' => t('x'),
      );
      return $prefixes;
    }

In the submit handler of the form I have:

    function _x_config_submit($form, $form_state) {
      $config = config('x.settings');

      $config->set('x.settings', 'my_setting',  $form_state['values'][$cid]);

      $config->save();
    }

And I have a x.settings file in the config folder of my module. Nothing seems to get saved to the config file.

**Comment by serundeputy** [comment]
@JAyenGreen I would check the `files/config_{hash}/active/x.settings.json` for your saved config.  the `modules/x/config/x.settings.json` file contains the default config that is copied to `files/config_{hash}/active/x.settings.json` at install time.  All further changes happen in the `active` directory.

**Comment by docwilmot** [comment]
Actually, the line `$config->set('x.settings', 'my_setting',  $form_state['values'][$cid]);` shouldn't have `'x.settings', `. 
`Config:: get()` only had two parameters.

**Comment by JAyenGreen** [comment]
Thank you both. I was looking at an example of config_set and thinking config->set :-)  The settings are saved now, and I'm looking for them in the right place!

**Comment by klonos** [comment]
Great to see you around the Backdrop issue queue @JAyenGreen!! ...any book on Backdrop in the works perhaps? 😄

**Comment by JAyenGreen** [comment]
Nice to be here. Nope. I think Todd Tomlinson has it covered?

On Nov 25, 2016, at 15:54, Gregory Netsas <notifications@github.com> wrote:

Great to see you around the Backdrop issue queue @JAyenGreen!! ...any book on Backdrop in the works perhaps? 😄
