### ISSUE TITLE
Mark 1.5.2 as security release.

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2360]
In the reports of a Backdrop website running version 1.5.1, it's not clear that [1.5.2 is a security release](https://github.com/backdrop/backdrop/releases/tag/1.5.2).

Status report:
![screen-backdrop-151-status-report](https://cloud.githubusercontent.com/assets/14188307/20635892/16ea045a-b364-11e6-844c-b1ae35130a6c.png)

Available updates page:
![screen-backdrop-151-available-updates](https://cloud.githubusercontent.com/assets/14188307/20635896/20402412-b364-11e6-8f3b-bdb444ff66a7.png)

**Comment by klonos** [comment]
...should be fixed now @olafgrabienski. Can you please try and let me know?

**Comment by findlabnet** [comment]
@klonos it's OK for now.
![152up](https://cloud.githubusercontent.com/assets/11479969/20639521/b5411598-b3ce-11e6-957e-db5132a432f8.png)

**Comment by olafgrabienski** [comment]
Thanks, @klonos! Works fine now.

**Comment by klonos** [comment]
Great. Closing...
