### ISSUE TITLE
Improve print version of pages on api.backdrop.org

### ISSUE THREAD

**Issue by sentaidigital** [backdrop/backdrop-issues#2363]
The print version of pages on api.backdrop.org includes most of the web widgetry.  Some of it is useful when working with a PDF of the docs, like hyperlinks, but some of it is completely inert, even in the PDF, like the search boxes and accordion expansions.

There are times when using paper documentation is useful, and CSS supports separate styles for print vs screen.  It would be nice to have some well formatted documentation when printing from api.backdrop.org.

Attached is one sample page with a few suggestions on elements that can be removed or made more print-friendly.  While these are a good start, someone with more of an eye for design should take a long hard look at the print version.

[class Config | Backdrop CMS API.pdf](https://github.com/backdrop/backdrop-issues/files/615040/class.Config.Backdrop.CMS.API.pdf)

**Comment by jenlampton** [comment]
I've moved this issue to the API site queue: https://github.com/backdrop-ops/api.backdropcms.org/issues/59
