### ISSUE TITLE
Set Unix file permissions consistently for all files in Git

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2371]
This issue is somewhat of a follow-up to [#395: What are the correct permissions for public_html and settings.php?](https://github.com/backdrop/backdrop-issues/issues/395) and also addresses part of a question that was filed to security@backdropcms.org regarding the default file permissions of files in the Backdrop CMS repository:

> I recently noticed that all files including settings.php of a online
Backdrop installation got 755 permissions. I'm not an expert regarding
file permissions, but I guess 755 is too much, especially for settings.php.

While it's likely that the process of uploading via FTP or some other means may change the file permissions, we can at the very least ensure that the permissions of the files when they are checked out from Git are set to something reasonable (and consistently).

It's important to note that on many shared hosts, a non-executable PHP file may result in a 403 or 404 error. So right now installing Backdrop (from a Git repository) on these hosts requires that you chmod the index.php and install.php files to get the installer going. I know @jenlampton ran into this on NameCheap's hosting.

Doing a fresh checkout of the repository, I get this result:

```
❰nate❙~/Sites/backdrop2(git:1.x)❱✔≻ ls -la
total 80
drwxrwxr-x 10 nate nate  4096 Nov 30 13:54 ./
drwxrwxr-x 54 nate nate  4096 Nov 30 13:53 ../
drwxrwxr-x  8 nate nate  4096 Nov 30 13:54 core/
drwxrwxr-x  2 nate nate  4096 Nov 30 13:54 files/
drwxrwxr-x  8 nate nate  4096 Nov 30 13:55 .git/
-rw-rw-r--  1 nate nate   257 Nov 30 13:54 .gitignore
-rw-rw-r--  1 nate nate  6083 Nov 30 13:54 .htaccess
-rw-rw-r--  1 nate nate   578 Nov 30 13:54 index.php
drwxrwxr-x  2 nate nate  4096 Nov 30 13:54 layouts/
drwxrwxr-x  2 nate nate  4096 Nov 30 13:54 modules/
drwxrwxr-x  5 nate nate  4096 Nov 30 13:54 profiles/
-rw-rw-r--  1 nate nate  3814 Nov 30 13:54 README.md
-rw-rw-r--  1 nate nate  1228 Nov 30 13:54 robots.txt
-rwxrwxr-x  1 nate nate 14830 Nov 30 13:54 settings.php*
drwxrwxr-x  2 nate nate  4096 Nov 30 13:54 sites/
drwxrwxr-x  2 nate nate  4096 Nov 30 13:54 themes/
```

All files in the root are 664 *except settings.php*, which is 775 for some reason. All directories are 775.

Doing a further scan recursively with `find . -perm -111 -type f` yields hundreds of files that are executable that do not need to be.

Let's fix all the permissions so they are consistent and a value that is suitable for hosting.

- All non-executable PHP files: 644 (including settings.php)
- Executable PHP files: 755 (index.php, update.php, authorize.php)
- Executable script files: 755 (install.sh, run-tests.sh, etc)
- All directories: 755

Updated: Matched permissions recommended in Drupal (https://www.drupal.org/node/2690335).

PR at https://github.com/backdrop/backdrop/pull/2247.

**Comment by klonos** [comment]
Not an expert either, but fixing those file permissions for the current files would be a first step. I would expect us to have tests in place so that the permissions are checked against any future changes. Since that will only ensure correct permissions on the code we ship, perhaps it would also be a good idea to be checking these file permissions on cron runs or something and presenting respective status/warnings on the site status page. Something like "File permissions: secure - Last checked on xxx date/time".

Just my thoughts.

**Comment by jenlampton** [comment]
We removed that check from the status report because checking file mode
won't tell us if the files are secure or not, and the warning was confusing
to people who were secure, but still got the message.

**Comment by klonos** [comment]
Hmm, I must have missed that one. Do you have the issue or PR number for it @jenlampton?

**Comment by jenlampton** [comment]
It was here: https://github.com/backdrop/backdrop/pull/559

**Comment by quicksketch** [comment]
>  I would expect us to have tests in place so that the permissions are checked against any future changes.

Yeah, to be clear, this is just about setting the permissions that come from the repository itself by default. The permissions are all lost in the release ZIP files and reset to the default OS-level permissions when you expand it. Permissions are also lost when using FTP. The only situation we're talking about right now is just making the Git version of all files have consistent and recommended permissions. The end-user impact of this is pretty much non-existent, though it will affect developers using direct Git checkouts.

Something I had never really considered before is that while zip files do not maintain permissions, tar.gz archives do: http://stackoverflow.com/questions/10735297/maintain-file-and-folder-permissions-inside-archives. However, we don't provide tar.gz files of releases currently.

**Comment by quicksketch** [comment]
I added a PR at https://github.com/backdrop/backdrop/pull/2247 that matches the recommendations in the issue summary.

**Comment by opi** [comment]
Note that github automatically provides a .tar.gz file of any release, ex https://github.com/backdrop/backdrop/archive/1.10.1.tar.gz ;

**Comment by klonos** [comment]
@quicksketch not entirely sure how this works, but is there something we can do on the GitHub repo to have `git config core.filemode false` by default, or is this something that people need to run on their locals. More info:

https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes

**Comment by herbdool** [comment]
I did a cursory code review (didn't look at every file change) and it looks good. That should be sufficient I think.

@klonos want to file a new issue for your question?

**Comment by quicksketch** [comment]
> is there something we can do on the GitHub repo to have git config core.filemode false by default

It doesn't look like this is possible. https://stackoverflow.com/questions/6547933/is-it-possible-to-clone-git-config-from-remote-location/6548056#6548056

> Note that github automatically provides a .tar.gz file of any release, ex https://github.com/backdrop/backdrop/archive/1.10.1.tar.gz ;

Thanks @opi! I didn't know that was possible. It is good that we have tar.gz as an option, and it's much easier using existing archives rather than uploading the same release asset twice.

I actually like that .zip files loose the permissions, as it makes it so that the server gets to set the default permissions for created files. Since the user and group is different based on where you are hosting, we can't fully know what the right permissions are when we put files into Git.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2247 into 1.x and 1.10.x. Thanks all!
