### ISSUE TITLE
Basis: Primary nav menu goes mobile too soon.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2380]
With just the 2 menu items that we ship with out of the box ("Home" & "About"), the nav menu switches to mobile too soon. You can clearly see from the screenshot bellow that it could as well fit another 2 or 3 items before it requires to be wrapped:

![backdrop-issue2190-pr1656-nav_menu_goes_mobile_too_soon](https://cloud.githubusercontent.com/assets/2423362/20908487/5ec4f350-bba9-11e6-9d5f-89ffc5a27a53.png)

I realize that we are using a 3rd party lib for the menu, but I wonder if we could implement something similar to our admin theme primary tab magic here. Hmm.

**Comment by klonos** [comment]
It would be great if we were switching to mobile dynamically, based on the number of 1st-level menu items and their total length instead of having a fixed breakpoint. Would that be possible?

**Comment by klonos** [comment]
I guess @wesruv you're the guy to "ping" 😉

**Comment by wesruv** [comment]
Yep! This is a duplicate issue, I have a proposed solution for dynamically going to the mobile layout: https://github.com/backdrop/backdrop-issues/issues/2367#issuecomment-263720252

**Comment by klonos** [comment]
Yes, sorry @wesruv ...still catching up with past issues on GitHub. It takes time because if they are "low-hanging fruits" I try to file PRs 😉
