### ISSUE TITLE
Issues with checkbox rendering

### ISSUE THREAD

**Issue by JAyenGreen** [backdrop/backdrop-issues#2382]
Using the following code, I get no checkboxes showing in the checkboxes field, though the form array has the field containing the expected associative array in the options index, and the individual checkbox fields are not rendering checked despite the default value. Screenshot attached.

     function _select_feed($op = 'Process') {
      $form = array();

      $form['feeds'] = array(
        '#type' => 'checkboxes',
        '#title' => t("Select $op feeds"),
        '#options' => backdrop_map_assoc(array(t('new'),t('old'))),
      );

      $form['process_options'] = array(
        '#type' => 'fieldset',
        '#title' => 'Processing options',
      );

      $form['process_options']['download'] = array(
        '#type' => 'checkbox',
        '#title' => t('Download'),
        '#default_value' => TRUE,
        '#description' => t('Unchecking this box will result in processing using existing files rather     than downloading new ones.'),
      );
      $form['process_options']['process'] = array(
        '#type' => 'checkbox',
        '#title' => t('Process'),
        '#default_value' => TRUE,
        '#description' => t('Unchecking this box will bypass processing the data in the files.'),
      );
      $form['process_options']['write'] = array(
        '#type' => 'checkbox',
        '#title' => t('Write to DB'),
        '#default_value' => TRUE,
        '#description' => t('Unchecking this box will prevent the existing database data being overwritten'),
      );

      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Process'),
      );

      return $form;
    }

![screen shot 2016-12-06 at 1 19 39 am](https://cloud.githubusercontent.com/assets/1633477/20915491/33278c1c-bb54-11e6-9bdd-775a68e61f86.png)

**Comment by mikemccaffrey** [comment]
I am confused. Your code declares three checkbox fields, and your screenshot has three checkboxes in it. 

What exactly is the outcome you are expecting?

**Comment by mikemccaffrey** [comment]
Oh, I see, you are getting no **checks** showing in the checkboxes, even though you are setting the #default_value to TRUE. That is really weird.

I would try changing the default_value from TRUE to a numeric 1.

**Comment by JAyenGreen** [comment]
There is a declaration of checkboxes using an array that should provide two of them. They don't appear at all. 

There is also a declaration of checkbox (x3). They appear but are not set to the default. I'll try using 1 as the default.

On Dec 7, 2016, at 01:07, Mike McCaffrey <notifications@github.com> wrote:

Oh, I see, you are getting no checks showing in the checkboxes, even though you are setting the #default_value to TRUE. That is really weird.

I would try changing the default_value from TRUE to a numeric 1.

**Comment by JAyenGreen** [comment]
Such an adventure! Ok, I've learned my lesson. One additional thing to always try in addition to clearing cache...look to make sure drupal_ calls have been replaced in your code with backdrop_ equivalents, including drupal_get_form!!
