### ISSUE TITLE
Restore browser-based spellcheck ability in CKeditor

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2386]
follow up from https://github.com/backdrop/backdrop-issues/issues/2071

---
~~PR by @serundeputy: https://github.com/backdrop/backdrop/pull/1663~~ (merged)
~~follow-up PR by @serundeputy: https://github.com/backdrop/backdrop/pull/1666~~
follow-up PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1747

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/1663

Sandbox:
Website: http://1663.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: t66kcENd

![screen shot 2016-12-08 at 7 56 12 pm](https://cloud.githubusercontent.com/assets/6763671/21033762/f8c28250-bd80-11e6-9b9e-eee6b776176c.png)

**Comment by quicksketch** [comment]
This seems like a no-brainer. It looks like this is the same fix that went into Drupal 8 as well. I'm all for merging this directly.

@jenlampton pointed out that on some devices (Chrome on Windows), the built-in spell check doesn't always work, but that may be a OS-configuration issue or a problem with that version of Windows, we don't quite know what the circumstances are. But in any case, if the OS-level spellcheck is broken, that means it's not working for any website at all, so it might not be expected by that user if the spell check is universally unavailable.

**Comment by jenlampton** [comment]
Yep, I agree. That was an argument for the other issue - adding a spell-check button to CKeditor. We need this more :)

**Comment by quicksketch** [comment]
Cool, merged https://github.com/backdrop/backdrop/pull/1663 then. Thanks @serundeputy. :smile:

**Comment by olafgrabienski** [comment]
Fixed a typo in the title: `CKeditior` => `CKeditor`

**Comment by MrHaroldA** [comment]
This patch uses the browsers internal spell checker, but you can't access the suggestions because the right click is hijacked.

![image](https://cloud.githubusercontent.com/assets/695291/21043472/54a9d2f0-bdf7-11e6-94d6-04152c6821a5.png)

This can be fixed by adding contextmenu to the removePlugins configuration option, but I don't know what side-effects that has. It does seem logical to have it one way or the other: browser spell check with the browser's context menu, or a Ckeditor spell check and Ckeditor's context menu.

```
    'removePlugins' => 'image,contextmenu',
```

**Comment by serundeputy** [comment]
Updated: https://github.com/backdrop/backdrop/pull/1663

Enable right click from browser.

**Comment by MrHaroldA** [comment]
@quicksketch, there's a new PR to enable the browser's right click context menu. This is needed to select any of the spelling suggestions.

https://github.com/backdrop/backdrop/pull/1666

**Comment by klonos** [comment]
Updated the issue description to include links to both PRs. Thanx @MrHaroldA 😉

**Comment by serundeputy** [comment]
someone (s) needs to test this first and give rtbc;

**Comment by klonos** [comment]
The browser default context menu does not work for me on PR 1666 (I've already left feedback there):

![backdrop-issue2386-pr1666](https://cloud.githubusercontent.com/assets/2423362/21108391/10fbcb5e-c0e9-11e6-86e2-f98b961cc5ef.png)

**Comment by serundeputy** [comment]
clear cache?

**Comment by quicksketch** [comment]
I took a look at this and I'm not sure the solution is so simple as disabling the contextual menu. If you have a button like tables enabled, then a lack of contextual menu makes working with tables almost impossible.

It looks like Drupal went through this exact conversation as well at https://www.drupal.org/node/2307141. They decided that having the underline was useful enough, even though the right-click suggestions were broken by the built-in contextual menu.

As mentioned in that issue, it is possible to work-around the problem by holding down the `Ctrl` key to get the OS-native spelling suggestions; though I'm not a fan of that personally. I think spellcheck is a much more needed feature than table editing, so if it were possible to reverse the situation and have the CKEditor contextual menu only in some situations that would be preferred to me.

I wonder if we could A) get rid of the CKEditor contextual menu options for cut/copy/paste and then B) fallback to the native contextual menu if no other menu options are present.

**Comment by quicksketch** [comment]
> I wonder if we could A) get rid of the CKEditor contextual menu options for cut/copy/paste and then B) fallback to the native contextual menu if no other menu options are present.

Reading through the source at https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/contextmenu/plugin.js, I don't think this proposal is easily possible. Even if implemented, we'd need to fix that upstream and wait for it to be available in a new CKEditor release.

Another proposal: What if we disabled the contextual menu plugin unless a different plugin specifically requested it (like the table plugin)? We could indicate the requirement in `hook_ckeditor_plugins()` like this:

```
    'Table' => array(
      'label' => t('Table'),
      'required_html' => array(array('tags' => array('table', 'thead', 'tbody', 'tr', 'td', 'th'))),
      'extra_plugins' => array('contextmenu'),
    ),
```

So the default would be to use the native contextual menu all the time, unless another plugin requires the CKEditor contextual menu.

**Comment by Dinornis** [comment]
Apologies if I missed something that has been said, but to me it looks like the current CKEditor implementation actually breaks OS Based (at least on OS X 10.10.5) spellchecker.

It is working everywhere except in the BD CKEditor field.

**Comment by jenlampton** [comment]
@Dinornis yes, that's why this issue exists. We are working to fix that bug!

**Comment by Dinornis** [comment]
I agree with this
> So the default would be to use the native contextual menu all the time, unless another plugin requires the CKEditor contextual menu.

Is this how WordPress deals with this problem?  I know the OS / Browser native spellchecker works in both the Visual and Text editors.

**Comment by jenlampton** [comment]
WordPress uses TinyMCE, which may not override the contextual menu at all. Perhaps they do not have this problem at all.

**Comment by quicksketch** [comment]
Yeah tinyMCE doesn't have a contextual menu plugin in WordPress AFAIK, so they avoid the problem. Though it also looks like WordPress doesn't let you add tables at all these days, so they avoid the problem of managing tables as well.

I think our compromise is a good one. Let's disable contextual menus unless a different plugin (e.g. tables) asks for it.

**Comment by quicksketch** [comment]
> Let's disable contextual menus unless a different plugin (e.g. tables) asks for it.

I've implemented this in https://github.com/backdrop/backdrop/pull/1747.

Plugins in `hook_ckeditor_plugins()` may now specify `dependencies`. If not specified, the dependencies of `tabletools`, `tableresize`, and `contextmenu` are no longer automatically loaded. Enabling the Table button enables all of these plugins.

**Comment by Dinornis** [comment]
Works in Safari, misspelled words are underlined and right-click provides access to corrections as expected.  Sorry could not test other browsers at the moment.

**Comment by quicksketch** [comment]
Great, I've merged in https://github.com/backdrop/backdrop/issues/1747 into 1.x. As this expands the API, I don't think this should be backported into 1.5.x.
