### ISSUE TITLE
Admin bar: The "Manage display" menu item for user accounts should not have "Manage fields" as parent.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2388]
We have:

- Structure -> Content types -> %content_type% -> Manage fields
- Structure -> Content types -> %content_type% -> Manage display

...but:

- Configuration -> User accounts -> Manage fields -> Manage fields
- Configuration -> User accounts -> Manage fields -> Manage display

It should be like so:

- Configuration -> User accounts -> Manage fields
- Configuration -> User accounts -> Manage display

**Comment by Dinornis** [comment]
Marking as duplicate of #2448 
Has been fixed there.

**Comment by serundeputy** [comment]
closing as dupe of https://github.com/backdrop/backdrop-issues/issues/2448 ; thanks @klonos and @Dinornis

**Comment by klonos** [comment]
Yep, sorry guys, too many browser tabs open crash my browser and I lose track of issues I open.
