### ISSUE TITLE
Add default blog layout

### ISSUE THREAD

**Issue by behindthepage** [backdrop/backdrop-issues#239]
It would be beneficial for new users to be able to enable a layout that would be similar to a Wordpress blog page i.e. with an archive block and categories/tag block. 

Having a good "how to" system so users can install Backdrop and be asked whether they want a blog page or told how to enable a blog page would make it very easy.

Maybe we could have a introduction module that is enabled on install and steps people through configuring Backdrop then disabled when they finish. But I digress this post was about a blog.

Regards 
Geoff

**Comment by quicksketch** [comment]
> We still have a long ways to go completing layout functionality to make this possible to have a layout you could enable.

Just an update as it's been over a year now. Layouts are now completely capable of what's been described here. You can even ship with a default layout that is disabled if desired.

I think some simple wire-frames of the desired functionality would be helpful here.

**Comment by behindthepage** [comment]
Closing this thread as more discussion is happening at 
https://github.com/backdrop/backdrop-issues/issues/881
