### ISSUE TITLE
Basis: add a template and style for comments.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2393]
The comments styling needs some love:

![backdrop-basis-comments_unstyled](https://cloud.githubusercontent.com/assets/2423362/21073689/f3b15efc-bf39-11e6-8a56-7fb998018c97.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1668

**Comment by klonos** [comment]
Here's a first take on it:

![backdrop-issue2393-pr1668-ltr](https://cloud.githubusercontent.com/assets/2423362/21073753/752eeec6-bf3b-11e6-8beb-25134993972c.png)

**Comment by klonos** [comment]
...and RTL:

![backdrop-issue2393-pr1668-rtl](https://cloud.githubusercontent.com/assets/2423362/21073801/ebf793cc-bf3c-11e6-880f-323db903b284.png)

**Comment by klonos** [comment]
This is basically:

- The `comment.tpl.php` file from Bartik, with the following changes:
  - Moved the comment submit date next to the comment title. It simply didn't feel right having the date wrap in 3 lines bellow the comment author. Perhaps I'm used to GitHub comments 😄 
  - Moved the reply/edit/delete links to the far right bottom corner for LTR and to the far left bottom corner for RTL. I think they are more "out of the way" that way.
  - Removed the "permalink" link. The comment title is already a permalink.
- Added a `comments.css` file under `/css/component` and an entry for it in basis.info

**Comment by klonos** [comment]
@wesruv can you please take it from here because my css-fu is not as strong as yours + you are the `em`/`rem` expert 😄 ?

**Comment by olafgrabienski** [comment]
Nice, looks much better than before!

Maybe we could adjust the margins and paddings slightly:

- add some margin above the first comment and between the single comments
- remove padding above the reply/edit/delete links

Something like this:

![screen-backdrop-basis-comments-margins-padding](https://cloud.githubusercontent.com/assets/14188307/21076044/d94a4c30-bf21-11e6-8f7a-56180fe1810f.png)

**Comment by wesruv** [comment]
Haha, absolutely, thanks for taking a crack at it, I like the direction ti's taking, I'll probably modify it a bit, but this is great!

**Comment by klonos** [comment]
>I'll probably modify it a bit, but this is great!

Sure, please go ahead. Just wanted to "give you a push" 😄

**Comment by klonos** [comment]
>Maybe we could adjust the margins and paddings slightly

It's up to @wesruv now @olafgrabienski 😄

**Comment by quicksketch** [comment]
Overall looks great! The current comment list styling is indeed... sparse. Please @wesruv if you get a chance to apply any changes, file an updated PR.

**Comment by wesruv** [comment]
New PR: https://github.com/backdrop/backdrop/issues/1735

Screenshots:
![image](https://cloud.githubusercontent.com/assets/5607236/21912188/58556d0e-d8f2-11e6-8f07-3526d937570d.png)

![image](https://cloud.githubusercontent.com/assets/5607236/21912197/6f1039de-d8f2-11e6-9573-92f7f1c13119.png)

**Comment by wesruv** [comment]
Wanted to keep it simple, the design that bartik had got hair at mobile, and with longer user names. This doesn't require any special styling for mobile and I think reads quite nicely.

I liked the 'arrow' effect they had, had a slight 'speech bubble' thing going on, thought I'd keep that.

Also added a 'reply comment' arrow that looks like a carriage return. Thought it made it a bit more obvious what's going on.

**Comment by olafgrabienski** [comment]
I really like the styling, including the now better placement of the *delete / edit / reply* links. Very nice!

While testing the PR, I noticed another issue (which probably existed before this PR): Being on the home page with a post, follow the link "3 comments" (http://1735.backdrop.backdrop.qa.backdropcms.org/posts/our-second-post#comments). Unfortunately you don't jump to the comment section of the post because in the code is missing the id `#comments`. @wesruv Should I or will you open a separate issue for it?

**Comment by wesruv** [comment]
Great catch! I'll add a fix in this PR.

**Comment by wesruv** [comment]
Pushed up a fix, the issue was actually in core's original node.tpl.php, heh 😳

**Comment by olafgrabienski** [comment]
Tested the fix: missing ID had been added, and the link leads to the comment section.

**Comment by serundeputy** [comment]
Thanks @olafgrabienski @klonos and @wesruv !

Looks great!  Merged into `1.x` and `1.5.x` will ship with `1.5.3` and `1.6.0`!
