### ISSUE TITLE
Recoverable fatal error: Argument 3 passed to comment_new_page_count() must be an instance of Node, instance of stdClass given

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2395]
This might be related to #2392. I got this while trying to add the "Content: Has new content" and "Content: New comments" fields to the "Admin content" view. Now, I get the "The website encountered an unexpected error. Please try again later." error when I try to visit `admin/content`. Here's hat I see in the log:

Type	php
Date	Sunday, December 11, 2016 - 2:05am
User	admin
Location	http://localhost/?q=admin/content
Referrer	http://localhost/?q=admin/content/comments
Message	Recoverable fatal error: Argument 3 passed to comment_new_page_count() must be an instance of Node, instance of stdClass given, called in C:\www\core\modules\comment\views\views_handler_field_node_new_comments.inc on line 99 and defined in comment_new_page_count() (line 541 of C:\www\core\modules\comment\comment.module).
Severity	error
Hostname	127.0.0.1
Operations

**Comment by klonos** [comment]
I managed to track this down to the "Content: New comments" field when devel_generate comes into play...

Steps to reproduce on a fresh installation:

1. Go to `/admin/structure/views/view/node_admin_content`
2. Add the "Content: New comments" field accepting all defaults.
3 Save the view.
4. Visit the "Admin Content" page (`/admin/content`) -> Everything is OK 👍 
5. Create a post (`/node/add/post`), **but do not add any comments yet**.
6. Visit the "Admin Content" page again (`/admin/content`) -> Everything is still OK 👍 
7. Go back to the post node you created in step 5 and add any number of comments.
8. Visit the "Admin Content" page yet again (`/admin/content`) -> Everything is still OK 👍 
9. Install and enable the Devel and Devel Generate contrib modules.
10. Generate any number of post nodes **with no comments** using `admin/devel/generate/content`.
11. Visit the "Admin Content" page again (`/admin/content`) -> Everything is still OK 👍 
12. Go to `admin/devel/generate/content` and this time generate any number of post nodes **with any number of comments**.
13. Visit the "Admin Content" page again (`/admin/content`) -> 👎 "The website encountered an unexpected error. Please try again later."
14. The only way to recover from this that I could think of is to go to the `admin/devel/generate/content` page and use the "**Delete all content** in these content types before generating new content." checkbox to delete all post nodes previously generated. After that, visiting the "Admin Content" page (`/admin/content`) does not give you any error.

Weird huh? So post nodes with comments created "manually" won't get you to this situation, but generating post nodes with comments using devel_generate will. Should I move this to the devel issue queue, or is there something that needs to be fixed in core?

**Comment by robertgarrigos** [comment]
I found myself today with this bug. This is a problem within Core. I will file a PR.

**Comment by robertgarrigos** [comment]
Here it is: https://github.com/backdrop/backdrop/pull/2235

**Comment by quicksketch** [comment]
Thanks @robertgarrigos! Merged https://github.com/backdrop/backdrop/pull/2235 into 1.x and 1.10.x.
