### ISSUE TITLE
hook_block_view_alter() doesn't pass $context as it says

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2401]
`layout.api.php` has this as the correct signature for `hook_block_view_alter()` and `hook_block_view_MODULE_DELTA_alter()`:

`hook_block_view_alter(&$data, $block, $settings = array(), $contexts = array())` and
`hook_block_view_MODULE_DELTA_alter(&$data, $block, $settings = array())`

But the invocation of these hooks doesn't pass context after all:
```
protected function buildBlock() {
...
    $this->content = module_invoke($this->module, 'block_view', $this->delta, $this->settings['block_settings'], $context_data);
    backdrop_alter(array('block_view', 'block_view_' . $this->module . '_' . str_replace('-', '_', $this->delta)), $this->content, $legacy_block, $this->settings['block_settings']);
  }
  return $this->content;
}
```

Note `$context` is passed for `hook_block_view()` but not the `*_alter()` functions.
p.s. I havent actually tested this is true, it just looks that way; maybe some magic happens elsewhere.

**Comment by quicksketch** [comment]
Thanks @docwilmot! A good find. Merged https://github.com/backdrop/backdrop/pull/1757 into 1.x for 1.6.1.
