### ISSUE TITLE
[UX] Add the current page as the last breadcrumb

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2402]
> I'm thinking the current page title should always be appended as plain text, can't think of a scenario where that's not an improvement.

Yes please, I do this manually on 90% of my sites! Totally possible to do this for 1.6. See #2402

This issue is a spin-off from https://github.com/backdrop/backdrop-issues/issues/2260 since there is a chance this can still be done by 1.6 and the rest of that issue may not make it. 

---

~~PR by @Graham-72: https://github.com/backdrop/backdrop/pull/1679~~
PR by @jenlamotin https://github.com/backdrop/backdrop/pull/1705

**Comment by Graham-72** [comment]
I think my PR at https://github.com/backdrop/backdrop/pull/1679 will do what is needed to achieve this.

**Comment by olafgrabienski** [comment]
Thanks @Graham-72, the PR looks good in my opinion.

I'd prefer to replace the `<p>` element in the list item with `<span>` though.

core/themes/basis/css/component/breadcrumb.css, line 23:
```
- .breadcrumb li a, .breadcrumb li p {
+ .breadcrumb li a,
+ .breadcrumb li span {
```
core/themes/basis/template.php, line 89:
```
- $output .= '<ol><li>' . implode('</li><li>', $breadcrumb) . '</li><li><p>' . $page_title . '</p></li></ol>';
+ $output .= '<ol><li>' . implode('</li><li>', $breadcrumb) . '</li><li><span>' . $page_title . '</span></li></ol>';
```

**Comment by Graham-72** [comment]
@olafgrabienski yes, `<span>` looks good to me. Thanks for the suggestion.

**Comment by klonos** [comment]
@jenlampton 

> Totally possible to do this for 1.6. See #2402

This issue link points to itself (here). Perhaps intended to link to another issue?

The PR itself is straight-forward, but I'd rather see this as a setting for the breadcrumb block. I initially thought perhaps it could exist as a theme setting, but I don't think that people will have the need to be switching this on/off when switching themes. The point is to provide an easy way for people to enable/disable this through the UI independently of the theme chosen. Right?

**Comment by olafgrabienski** [comment]
@klonos What's the use case for a breadcrumb not ending with the current page?

**Comment by klonos** [comment]
...although setting this for each layout would be more work (until we get either #2245 or #1886 that is) than setting it once per theme. Hmm.

**Comment by klonos** [comment]
@olafgrabienski just a matter of preference I guess. But then you can argue that people can simply hide it in their custom theme via CSS (`display: none;`). Which is a valid thought I guess. Then how about we set it globally for all themes as well (in https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L1972 perhaps?) rather than just for Basis?

**Comment by klonos** [comment]
I guess the right question to ask ourselves is if people wanted to customize their breadcrumb, where would they expect this to be done? Through the UI or in their theme (#2351). If we do provide this as a setting (remember we favor regular users over coders), the would we want it to be a per-theme setting or configurable through the block UI?

**Comment by klonos** [comment]
For the current situation and as an easy solution, I think that the best approach would be to leave the PR as is (Basis is already overriding `theme_breadcrumb` anyways in order to remove the » separator), but also add the current page in theme.inc (so that it works for Bartik) and perhaps also in https://github.com/backdrop/backdrop/blob/1.x/core/themes/seven/template.php#L121 in order to work with Seven.

The best approach though would be to adapt the core `theme_breadcrumb` function to accept setting the separator and then replace the theme override in Basis (that is simply a copy-paste from the core function minus the separator).

**Comment by jenlampton** [comment]
We can't do either of those for 1.6. can we create another feature request
issue?

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by olafgrabienski** [comment]
@jenlampton But in the meantime we can take the approach of the PR https://github.com/backdrop/backdrop/pull/1679 for 1.6, right?

**Comment by jenlampton** [comment]
I think so!

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by klonos** [comment]
> We can't do either of those for 1.6,

You mean only add the current page to the breadcrumb for Basis, but leave Bartik and Seven as is?

**Comment by jenlampton** [comment]
We just clarified with @quicksketch what would be the best approach for 1.6, and he recommended adding a block setting for the Breadcrumb block that would add the current page as the last breadcrumb. (as recommended by @klonos above)  It's not a big change, so still theoretically possible for 1.6.  Tagging as such.

**Comment by quicksketch** [comment]
Yep, my preferred approach would be:

- Make it a block setting.
- Have the setting passed into theme_breadcrumb().
- Update the core themes that override theme_breadcrumb() to also respect the setting.

If we think this is the most common use-case, we should also make the setting the default.

**Comment by Dinornis** [comment]
I just tested 1679 and it seems to be working as described in the title.
Although I don't see a  use case for a breadcrumb not ending with the current page, if there needs to be settings for this I agree with what Nate suggested:
> * Make it a block setting.
> * Have the setting passed into theme_breadcrumb().
> * Update the core themes that override theme_breadcrumb() to also respect the setting.
* make the setting enabled by default.

Maybe this is a separate issue:
I would expect the **breadcrumbs to be based off the path in the URL**.
For example for the URL: http://1679.backdrop.backdrop.qa.backdropcms.org/articles/article-01
I would expect the breadcrumb to be
Home > Articles > Article 01 **not** Home > Article 01
Is there a setting for this already that I missed or should I open a separate ticket for this?

**Comment by olafgrabienski** [comment]
Tested the PR as well but couldn't find a related block setting on *Configure block "Breadcrumb"* of the default layout. (Actually, I don't miss the setting, as I don't see a use case for it, but I understood that there should be a setting.)

@Dinornis As far as I understand, the breadcrumb isn't (expected to be) based on the path in the URL but on menu hierarchy. As an example see "Article 02" on http://1679.backdrop.backdrop.qa.backdropcms.org/articles/article-02, which I made a sub item of "Articles" in the *Primary navigation*, and so its breadcrumb is *Home > Articles > Article 02*.

**Comment by jenlampton** [comment]
> the breadcrumb isn't (expected to be) based on the path in the URL but on menu hierarchy. 

That's right - it's a bit of a strange thing, but Backdrop and Drupal have no way of knowing what items are parents, or even if those parent items exist, unless some sort of hierarchy is explicitly defined. For example, anyone could set up automatic aliases for articles that include '/articles/' inthe path, but perhaps there is no page at '/articles' on that site.  Should a link for 'Articles' still appear in the breadcrumb trail?

There is a contrib module for Drupal called "menu trail by path" that does what you wish. Breadcrumbs are a mess in Drupal/Backdrop and need some love - but that is another issue (or handful of them!) altogether :)

**Comment by jenlampton** [comment]
New PR ready for review: https://github.com/backdrop/backdrop/pull/1705
@olafgrabienski @Dinornis

**Comment by Dinornis** [comment]
Thank you Jen, I just tested this, it works well and is definitely an improvement.

I will open a separate issue with some suggestions for improving the breadcrumb functionality.

**Comment by olafgrabienski** [comment]
@jenlampton I tested the setting quickly, works good!

**Comment by quicksketch** [comment]
Thanks for the feedback @Dinornis and @olafgrabienski!

The simple approach of a single setting looks good to me! Such a simple and effective change!

The PR has one minor issue that it throws a PHP notice the first time the block is configured: https://github.com/backdrop/backdrop/pull/1705/files#r94343930

This notice doesn't show up as a message though because messages are disabled by default, but it does show in watchdog:

![screenshot from 2017-01-02 12-26-53](https://cloud.githubusercontent.com/assets/100206/21595803/cb902200-d0e6-11e6-95a6-a8e0f1cba6a0.png)

Once fixed, we should be good on this PR.

**Comment by jenlampton** [comment]
Fixed and set back to RTBC

**Comment by quicksketch** [comment]
Super, I've merged https://github.com/backdrop/backdrop/pull/1705 into 1.x for 1.6.0. Thanks @jenlampton, @Graham-72, @olafgrabienski, and @Dinornis!
