### ISSUE TITLE
Why do entity_get_info() and field_view_mode_settings() return conflicting info?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2404]
I'm working on https://github.com/backdrop/backdrop-issues/issues/315 and trying to get a complete snapshot of information about an entity's view mode settings.

When I ask `entity_get_info` it tells me that teasers **do** have customized field display settings: `custom settings (Boolean) TRUE`.

However, when I ask `field_view_mode_settings()` the same question, it tells me that teasers **do not** have customized field display settings: `    custom_settings (Boolean) FALSE`

It's confusing enough that these have different keys (one with a space and the other an underscore) but why can't they agree? Which one should I trust?

**Comment by quicksketch** [comment]
From [hook_entity_info()](https://api.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.api.php/function/hook_entity_info/1), it seems like what `entity_get_info()` returns is the default value that would be used on all new bundles (for example creating a new content type). The value returned by `field_view_mode_settings()` should reflect the custom/current value of whether a view mode is enabled.

So for checking a current value, I think `field_view_mode_settings()` is the right source, all the time.

**Comment by jenlampton** [comment]
okay, ty!
