### ISSUE TITLE
Fix remaining "Add redirect" instances (should be "Add URL redirect").

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2405]
...for consistency throughout the UI and better findability in the admin bar search box 😉 

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1674

**Comment by klonos** [comment]
...also fixed a few "an URL" vs "a URL" instances while at it...

[Using "a" or "an" With Acronyms and Abbreviations](http://blog.apastyle.org/apastyle/2012/04/using-a-or-an-with-acronyms-and-abbreviations.html)

> The general rule for indefinite articles is to use a before consonants and an before vowels. The trick here is to use your ears (how the acronym is pronounced), not your eyes (how it's spelled).

The same applies for the opposite where the first letter of an acronym is a vowel, but when you pronounce it, it sounds like a consonant (which is the case with "a URL").

**Comment by quicksketch** [comment]
Nice work @klonos! Regarding "a" and "an", you're absolutely right! I think you nailed it in all changes here. I've merged https://github.com/backdrop/backdrop/pull/1674 into 1.x and 1.5.x. Thanks!
