### ISSUE TITLE
Basis: Footer region not "sticky" to the bottom of the page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2406]
![backdrop-basis-footer_not_sticky](https://cloud.githubusercontent.com/assets/2423362/21284892/4c94acb6-c47d-11e6-86bd-f65bbacbfde9.png)

---
PR by @Graham-72: https://github.com/backdrop/backdrop/pull/1677

**Comment by Gormartsen** [comment]
It's one of the not easy task with css :(

**Comment by klonos** [comment]
Yeah, we ended up using `flex` for the same issue in Bartik (#473). I tried applying the same changes before filing this issue, but failed. Dunno.

**Comment by klonos** [comment]
PR looks good. I also tested the PR sandbox by removing the hero block from the home page layout. This caused the page to be short enough to test this and the footer indeed sticks to the bottom. So 👍

**Comment by quicksketch** [comment]
The PR does indeed solve the problem, but it adds some adjustments to admin-bar that don't seem to be necessary (see https://github.com/backdrop/backdrop/pull/1677/files#r93685563). Perhaps we can remove that and update the PR? Or if it is necessary, just post an explanation here. I just haven't seen any mention of why admin bar is affected by these changes.

**Comment by klonos** [comment]
Not sure, but IIRC these are there to account for when the admin bar is set to be sticky on top.

**Comment by Graham-72** [comment]
>  it adds some adjustments to admin-bar 

I have added a response to the comment on the PR at https://github.com/backdrop/backdrop/pull/1677/files#r93685563 to indicate the history behind these adjustments, as far as I can trace it. But this does not explain why these settings were added for Bartik. Maybe they are not needed for Basis?

**Comment by Dinornis** [comment]
The footer issue appears to be fixed in the PR, tagging as fixed.

**Comment by olafgrabienski** [comment]
@Dinornis Please don't tag as fixed when a change is not committed. You can choose "pr- reviewed and tested ..." (RTBC) instead. In this case, I'm not even sure if RTBC is appropriate, as the last two comments posed questions which are not clearly answered yet.

**Comment by quicksketch** [comment]
So the PR does look good and it works as advertised, but I still can't figure out what (if anything) the adjustments to admin bar do. I've tried removing the lines and everything still works, regardless of whether the admin bar is sticky at the top of the page or not.

Let's remove those lines until we find if they're truly needed.

**Comment by quicksketch** [comment]
As this may have repercussions, let's not hurry this into 1.5.3. I do think this would be a great fix to have as soon as possible, so I'm just moving this to 1.6.1.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1677 for 1.6.1. Thanks @Graham72!
