### ISSUE TITLE
Improve documentation of globals in api.backdropcms.org

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2407]
I would like to see a fuller list of the global variables that are set in core. I will gladly do some work on drafting this, starting from (and checking) the Drupal 7 list at https://api.drupal.org/api/drupal/globals/7.x, but I do not know how amendments get made to or proposed for api.backdropcms.org. I see we have  
https://github.com/backdrop-ops/api.backdropcms.org/blob/master/documentation/globals.php but that does not seem to be what appears on the site.

**Comment by herbdool** [comment]
From what I can tell the actual documentation isn't relying on those files anymore. So looks like you'd need to be given an account on the site so you can edit some pages. Or maybe provide some copy on this issue.

@jenlampton @klonos

**Comment by Graham-72** [comment]
@herbdool yes, it seems the documentation is produced by a view and presumably from a content type 'globals' or similar. I do have an account on the site but I do not have permission to add this type of content. I am working on a spreadsheet that would be a source of data and would anyway produce this even if I cannot personally add the data to the site. But now I am wondering whether I am duplicating work that someone else is doing? @jenlampton please advise me.

**Comment by jenlampton** [comment]
@Graham-72 @herbdool most of the documentation is pulled from docblocks in code, the one exception is that form API reference page, which you have found in the codebase. I don't actually know what is up with the globals.php file, if it is used currently, ever was, or was supposed to be.  I'll check and see, but I think that's probably the way to go.

**Comment by jenlampton** [comment]
okay, so I did some digging around in API module, and there's nothing there that uses the globals.php file. In fact, globals are listed using a view - the same as Files / Classes / Functions & Topics. 

So now the question remains: why are globals not properly parsed from our codebase?

**Comment by jenlampton** [comment]
@cellear you added the globals.php file, do you remember there being some problem with globals being parsed form our codebase?  Why was this file added into the documentation directory, do you know?

**Comment by BWPanda** [comment]
Closed https://github.com/backdrop-ops/api.backdropcms.org/issues/38 as a duplicate since this issue has more feedback/discussion.

**Comment by jenlampton** [comment]
This issue is in the wrong queue, so even though it has more comments I'm going to close it in favor of https://github.com/backdrop-ops/api.backdropcms.org/issues/38, which I will re-open. I'll also try to copy all the comments from here over there, so they are not lost :)
