### ISSUE TITLE
[DX] Remove message style overrides from basis

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2408]
Here's my thinking...
1) We spent a long time making core's message styles very pretty, we should be using them.
2) Overriding message styles is something that's not usually necessary. (Why are we doing that in Basis?)
3) Creating a sub-theme of basis immediately breaks message styles. 
4) Restoring core's default message styles in a Basis sub-theme is very, very difficult (see below).

Here's what I went through:
* I created a Basis sub-theme, and immediately noticed that all the message styles were broken. 
* I thought, "That's fine, I don't want to spend any time on message styles, I'll just use core's default".
* I tried to remove the problem CSS added by Basis. I added `stylesheets[all][] = css/component/status-messages.css` to my theme's .info file.
* Some things went back to normal, but still no colors or images!
* I added `system.theme.css` back into my theme - now the colors are back, but all the images are still broken!
* One way people will try to fix this is to update all the paths to all the images in the CSS file they have just copied from core. In my case that would mean find/replacing all instances of `../../../misc` with `../../core/misc/`. The problem with this is that if the theme ever moves (a directory up or down) all these paths will be broken. This is not the right solution.
* The best way to solve this problem is to duplicate all the images that are needed for the messages. Copy them from core into the sub-theme. That's A LOT of files to copy!
```
message-16-error.png
message-16-help.png
message-16-info.png
message-16-ok.png
message-16-warning.png
message-24-error.png
message-24-help.png
message-24-info.png
message-24-ok.png
message-24-warning.png
message-32-error.png
message-32-help.png
message-32-info.png
message-32-ok.png
message-32-warning.png
message-error.svg
message-help.svg
message-info.svg
message-ok.svg
message-warning.svg
```

If we are hoping to recommend Basis as a base theme, it can't immediately break the message styles.  The above is way too much work to expect of anyone just to un-break their sites (remember, my goal was not to spend ANY time on messages at all).  We especially can't expect this of beginners. It's going to give Backdrop a bad name if the first experience front-end developers have with it is what I just went through.

I recommend we remove message style overrides from Basis, and if that means we can't remove system.theme.css, then we'll need to do some major reworking to account for that. 

---

PR https://github.com/backdrop/backdrop/pull/1743

**Comment by jenlampton** [comment]
@wesruv I'm tempted to tag this for 1.6 because the longer we leave Basis as-is, the less likely we'll be able to change it in the 1.x cycle, and the longer it stays this hard for front-enders to use, the less likely it is to be successful. That said, I'm not even sure we can still change it now.  

Could you put your thinking-hat on and see if we can come up with some creative ideas for how to prevent this kind of pain-point for people? Maybe if we moved core's message styes out of system.theme.css?

**Comment by Graham-72** [comment]
Yes, please get this fixed for 1.6 if possible. I have 3 or 4 old Drupal sites that I need to rework with Backdrop and am waiting for 1.6 to do so with subthemes of Basis. So, from my personal viewpoint, this is a priority.

**Comment by wesruv** [comment]
@jenlampton `system.theme.css` has some crappy CSS that starts a specificity war. One of my main objectives in Basis was to make everything easy to override, and I felt that file was problematic. So it wasn't that I was trying to override status messages, I just didn't like a lot of stuff in that file.

Could we split out the error messages into a different file and remove my theme's overrides to status-messages?

**Comment by wesruv** [comment]
https://github.com/backdrop/backdrop/blob/1.x/core/themes/basis/css/skin.css#L506
My lackluster workaround for sub-theming issues with status messages was to add a bg image declaration in `skin.css` and commenting it out. The problem was that to get to those images from core, and to get to them from a sub-theme is different, and I don't know for sure where the theme will be. I also don't know if the backdrop instance is installed on server root or in a sub-folder.

This definitely occured to me, but in the end I didn't think of a good work-around and forgot about it 😞

**Comment by jenlampton** [comment]
> One of my main objectives in Basis was to make everything easy to override, and I felt that file was problematic. 

I 100% agree, and that's the only reason this issue exists ;)

> Could we split out the message styles into a different file and remove my theme's overrides to status-messages?

That was my second thought too, the only problem there is that change would affect 100% of sites running Backdrop. This late in the cycle I'd prefer to only affect those using Basis.  However, the more I think about it, it's likely that themes not using Basis would prefer to leave the message styles intact too, but still override the other problematic css in system.theme.css.  **Let's try it!** We'll need @quicksketch or @serundeputy to take a look at the approach and gauge impact on existing sites. But here's what I'm thinking:

How about we create a system.messages.css file containing only the message styles in core, and rework Basis to match?  (I think changes other than the bg images would be fine if you still want to include any of those)

**Comment by quicksketch** [comment]
I think this would be a tolerable change for 1.6, however we should fix the name of the file. It shouldn't be "system.messages.css" but rather "messages.theme.css". If we're adding style-only (non-functional) CSS, it should be in a *.theme.css file (as it was before in system.theme.css).

**Comment by jenlampton** [comment]
All the other css files in system start with system, so I went with the name `system.messages.theme.css` does that work?

**Comment by serundeputy** [comment]
Is this related to #289 ? is this going to fix 289 or should I still revert #289?

**Comment by serundeputy** [comment]
@jenlampton have a look at this PR if you will.

It increases the specificity of the background color css to `.messages.error`.

**Comment by quicksketch** [comment]
> All the other css files in system start with system, so I went with the name system.messages.theme.css does that work?

We have `menu-dropdown.theme.css`, `menu-toggle.theme.css` in there that don't start with `system.`, as well as the weird `jquery.treetable.css`. So we have several example already that don't include the prefix.

**Comment by quicksketch** [comment]
I've pushed an updated commit to the current PR that minimizes a few of the Basis differences and renames the file to just `messages.theme.css`.

**Comment by jenlampton** [comment]
The updated commit makes it hard to tell what's been changed without an interdiff, but I pulled the branch and did a diff on the merge, and as far as I can tell it looks like the only thing that's changed is the name of the CSS file. If that's all it is this is RTBC from me.

>  that minimizes a few of the Basis differences

I wasn't able to review these.

**Comment by quicksketch** [comment]
Sorry I should have been more specific. The only other change was switching `px` to `em` in the media queries, copying what Basis did instead of core (but the end result should be identical in both).

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1743 for 1.6.0.
