### ISSUE TITLE
Update smartmenu library when they hit the next release

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2418]
Has a fix we want: https://github.com/vadikom/smartmenus/issues/58#issuecomment-268988978

**Comment by klonos** [comment]
I'm watching that project so would have filed an issue upon new release, but thanx for acting ahead @wesruv 👍

**Comment by quicksketch** [comment]
Still a good idea, but they haven't made a release that includes this fix yet.

**Comment by BWPanda** [comment]
There seems to be a new release that includes this now.

@wesruv Any tips on using flexbox on the main drop-down menu in Backdrop? It would like you've done it before...

**Comment by klonos** [comment]
I have attempted a "bulk" PR to update to the latest 1.1.0 (released Sept 2017), just in case this worked OOTB. It did not 😅

...seems that there might be some changes in classes being used etc., so will need some more work and testing to ensure that things do not break.

Anyway... [changes in 1.1.0](https://github.com/vadikom/smartmenus/releases/tag/1.1.0):

- **support jQuery 1.7+ (no more 1.4.4+)** 
- support jQuery "slim" versions (no JS errors any more)
- new Bootsrap 4 addon
- new option "collapsibleBehavior"
- remove Compass dependency in the themes
- replace bind/unbind, delegate/undelegate with on/off in the JS
- replace :before/:after with ::before/::after in the CSS
- fix: themes SCSS files renamed to avoid filename issue for @import in node-sass (e.g. from "_sm-blue.scss" to "_sm-blue-theme.scss")
- deprecate and remove "overlapControlsInIE" option

**Comment by klonos** [comment]
...lets close this one in favor of #3715
