### ISSUE TITLE
Form API Reference: missing fieldset properties - #collapsed & #collapsible

### ISSUE THREAD

**Issue by Gormartsen** [backdrop/backdrop-issues#2421]
See here: https://api.drupal.org/api/drupal/developer%21topics%21forms_api_reference.html/7.x#fieldset
> Properties: #access, #after_build, #attributes, #collapsed (default: FALSE), #collapsible (default: FALSE), #description, #element_validate, #parents, #post_render, #prefix, #pre_render, #process, #states, #suffix, #theme, #theme_wrappers, #title, #title_display, #tree, #type, #weight

Compare to here: 
https://api.backdropcms.org/form_api#fieldset
> Properties: #access, #after_build, #attributes, #description, #group, #element_validate, #parents, #post_render, #prefix, #pre_render, #process, #states, #suffix, #theme, #theme_wrappers, #title, #title_display, #tree, #type, #weight

These properties are still available and used in `List modules` but we missing documentation.

**Comment by BWPanda** [comment]
This has since been updated: https://docs.backdropcms.org/form_api#fieldset
