### ISSUE TITLE
[UX] D7 to Backdrop upgrade: Entity Reference to References migration

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2428]
I've missed the last dev meeting, but as always I did watch it at a later time. At some point while discussing the status of the task of getting References into core for the upcoming 1.6.0, the matter of the upgrade path came up. So, in Drupalland, there are two main solutions in contrib for implementing referencing between entities in D7: [Entity Reference](http://drupal.org/project/entityreference) and [References](https://www.drupal.org/project/references). Entity Reference has been chosen to be merged in D8 core, while for Backdrop core we have chosen to go with References.

At the time of writing this there are [more than 120k reported installations of References](https://www.drupal.org/project/usage/references) and [275k for the Entity Reference module](https://www.drupal.org/project/usage/entityreference). It seems obvious that ignoring the sites that are using Entity Reference (by not providing some way to migrate to References) will push them towards D8 instead of considering Backdrop. I am sure that the task will be huge and really hard, but just wanted to officially start off an issue for it.

At this point I would also like to link to a D7 contrib module that does the opposite: [Reference to EntityReference Field Migration](https://www.drupal.org/project/entityreference_migration) ...might prove to be of help (perhaps all we'll need to do is somehow reverse its logic).

**Comment by serundeputy** [comment]
* [Reference](https://github.com/backdrop-contrib/reference) module is the core candidate
  * Reference is a new module that provides a field to let any entity reference any other entity

* [References](https://github.com/backdrop-contrib/references) is a backdrop-contrib module which is a port of the drupal module (references)[https://www.drupal.org/project/references]
  * This module provides a field that can reference a Node or a User entity

That being said upgrade paths from Entity Reference and References are still desirable.  We just need to make sure we have the source data and the targets specified correctly:
  * `entityreference` fields --> `reference` fields
  * D7 `references` fields --> `reference` fields
  * Backdrop `references` fields --> `reference` fields

Regarding "Backdrop `references` fields" that are provided by contrib; I think in the case of `ckeditor` we provided a message to the user strongly urging them to disable the contrib version and use the core version.

[Reference to EntityReference Field Migration](https://www.drupal.org/project/entityreference_migration) could still provide some insight but make sure to target the `reference` DB structure.

**Comment by herbdool** [comment]
I've used the Backdrop References module on a project but I won't upgrade to a core version until it's feature comparable. I think we've still got some work on that. 

The other thing which I think needs an upgrade path is term reference to reference, since it seems like this is also desirable.

**Comment by moonray** [comment]
Has there been any progress on an upgrade path?

**Comment by herbdool** [comment]
@moonray I don't think so. But if you need to, you can use entity reference for now https://github.com/backdrop-contrib/entityreference until there is an upgrade path. The module is working well enough though it doesn't have an official release yet.

**Comment by jenlampton** [comment]
> Has there been any progress on an upgrade path?

There is an PR on the reference module that includes an upgrade path from both entity_reference and node_reference. I don't think I've done term_reference yet because reference is still missing some of those features.

**Comment by jenlampton** [comment]
Closing this issue because we have others in the contrib queue: 
* https://github.com/backdrop-contrib/reference/issues/29
* https://github.com/backdrop-contrib/reference/issues/28

**Comment by klonos** [comment]
@jenlampton closing this makes it seem that this task is done in https://github.com/backdrop/backdrop-issues/projects/7 ...perhaps leave open, to serve as a meta/tracker issue, until those contrib PR have been merged, and we actually are certain that the upgrade path works?

**Comment by jenlampton** [comment]
This issue should never have been in the core queue, that's why it's
closed.
