### ISSUE TITLE
Port the Views Content Panes submodule from Ctools and add it in core.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2433]
@klonos / @jenlampton in https://github.com/backdrop/backdrop-issues/issues/330#issuecomment-269251521

>>If we want different setting per block instance, then the only way I see this being possible is to create a separate block display for each block.
>
>There is a setting that was available on views (content pane displays) in Drupal 7 but was not ported to Backdrop. Views should have a display-setting that allows per-instance configurations (on things like number of items, field displays, contextual filter sources, etc).
>
>Do we have an issue for "Make views block displays more like views content pane displays" or similar? This issue might be blocked by that one... Also related, the "exposed filters don't work w/o ajax" bug - that's solved with content pane displays as well.

If you enable the Views Content Panes submodule that comes with Ctools, there is a new "Content pane" display type that becomes available in views:

![d7-ctools-views_content_panes-content_pane_views_display](https://cloud.githubusercontent.com/assets/2423362/21507271/0916b2ee-cccb-11e6-82d5-456fffc31a0e.png)

...this in turn enables a new "Pane settings" section in the display with an "Allow settings" setting (perhaps we should change this to something more appropriate like "Expose settings" in the Backdrop port):

![d7-ctools-views_content_panes-content_pane_views_display-pane_settings](https://cloud.githubusercontent.com/assets/2423362/21507328/8ae990c0-cccb-11e6-96f5-b7c8d6de93f6.png)

...some of the settings that you can expose though this setting are all the pager settings:

![d7-ctools-views_content_panes-content_pane_views_display-pane_settings-allow_settings-pager_settings](https://cloud.githubusercontent.com/assets/2423362/21507426/3cd6ac5a-cccc-11e6-81b1-51e51d8d0ec4.png)

...which are then made available in each instance of that pane when placed in a Panel layout:

![d7-ctools-views_content_panes-view_pager_settings_exposed_in_panels_pane](https://cloud.githubusercontent.com/assets/2423362/21507531/326a839e-cccd-11e6-8b66-b9f27d7a5b7e.png)

So, in essence, using a single view display, we can provide a block that exposes the view pager options (mainly the number of recent comments for our specific use case in #330) as block settings. The important win with this is that each block instance will be able to have different settings while in order to achieve this with what we currently have available, we have to create a separate block display in the view for each block we want to place in each layout/region.

---
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1700

**Comment by klonos** [comment]
...only in Backdrop, instead of making this a different view display type, we should see if we can add the additional functionality as a new block display feature. Basically what @jenlampton has suggested:

> ..."Make views block displays more like views content pane displays"...

**Comment by jenlampton** [comment]
@klonos you are amazing :)

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by quicksketch** [comment]
I took a crack at this to see how much work it would be. The basics of it are: it's all possible, but it's going to take a bit of work. Although I got the simplest functionality working (overriding the number of items for example), other pieces are quite a bit more complex. The handling of contexts and reusing the exposed form filters as block configuration for example.

In any case, the PR is available for experimentation and further work here: https://github.com/backdrop/backdrop/pull/1700

**Comment by quicksketch** [comment]
Screenshots:

![screenshot from 2016-12-31 20-22-22](https://cloud.githubusercontent.com/assets/100206/21580182/f06ea156-cf96-11e6-94b2-d0081c349f34.png)

![screenshot from 2016-12-31 20-22-51](https://cloud.githubusercontent.com/assets/100206/21580183/f34e606e-cf96-11e6-9ef6-43acb72da19e.png)

**Comment by klonos** [comment]
Fantastic @quicksketch!! Mostly works as you said. Not posting any further detailed feedback because as you state in the PR it is experimental and I'm sure you mostly know what works and what not. Since this is a feature, I guess it is 1.7 material, right? If so, then that makes #330 also a target for 1.7.0. I can work on #330 once this is done, but unfortunately this one here is beyond my skills.

**Comment by klonos** [comment]
This would be amazing to have as a feature in 1.7.0

**Comment by Al-Rozhkov** [comment]
Do you plan to keep "Title override" setting? It is already possible to set "Custom" block title type for any block and override it.

**Comment by jenlampton** [comment]
No, I don't think we'll need it.

**Comment by quicksketch** [comment]
I've updated the PR at https://github.com/backdrop/backdrop/pull/1700. I think this is fully functioning, but in order to compromise between timeline and features, I punted on the ability to set a context from a layout. (e.g. you can't take the NID from the URL and pass it to a contextual filter). The ability to take a context object and transform it into a single value requires an entire sub-system we don't have yet. You can still set manual values.

Some notable changes:

- Blocks can now have exposed filter forms (with or without AJAX).
- Blocks can now have exposed filter forms *in a separate block* as well. So you can have one block with the exposed form that affects other blocks on the same page.
- There is now a second class for `ViewsSpecialBlock` to handle exposed filter forms (I had broken them previously).
- I organized most of the options into fieldsets and collapsed them by default. Here they all are when enabled:

![image](https://cloud.githubusercontent.com/assets/100206/25559454/70958b6e-2cef-11e7-81dc-4ebebb101152.png)

This PR will definitely need tests. For now though I wanted to get it up for others to test/review.

**Comment by klonos** [comment]
Not enough time to test, but if we do manage to get this in in 1.7.0, then it would unblock the conversion of certain blocks like recent comments/content to views (no stress; just wanted to mention it again 😄 ).

**Comment by Al-Rozhkov** [comment]
I do not understand how to use Contextual filter input yet. But other settings works as expected. Also "Title override" should be removed as was mentioned earlier.

This feature is so handy! The upcoming release will be amazing.

**Comment by quicksketch** [comment]
Thanks for the reminder on title override. I had thought that comment was part of the other Layout issue (#1704). I've removed that option from the Views UI (it was already removed from the blocks themselves).

I've added tests that cover just about everything. Context input is still uncovered, but all override options are now tested.

**Comment by quicksketch** [comment]
All tests are passing. I've merged in https://github.com/backdrop/backdrop/pull/1700 for Backdrop 1.7.0. Let's make a follow-up for handling passing Contexts from layouts into Views Contextual Filters.
