### ISSUE TITLE
[UX] Make layout weight configurable 

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2435]
Conceivably, more than one layout could be valid for a given context path. I don't think there is currently a way to weight the layouts to set the preferential order.

_From a Gitter conversation:_

>  @laryn: What happens when more than one layout could be valid for a given path/context? Is there a way to weight them?

> @Gormartsen: If I remember code properly, first one will be selected
> First that match access and is not disabled
> https://github.com/backdrop/backdrop/blob/6973511a06ad5ad70b12ce3727da2125befdfbbf/core/modules/layout/layout.module#L1078

> @jenlampton:  there is an option to rearrange them, yes.

> @Gormartsen: yeah, sort is happening here: https://github.com/backdrop/backdrop/blob/6973511a06ad5ad70b12ce3727da2125befdfbbf/core/modules/layout/layout.module#L976
> by path and weight

> @laryn: I must be looking right past it -- where do you adjust a layout's weight?

> @Gormartsen: I don’t see this settings too
> If you change json file manually by changing weight value - it would work for sure
> probably that functionality has been lost)

**Comment by jenlampton** [comment]
The settings are in the same place you change menu router info. The link is
on the darker path row, not the layout row.

- -
Please excuse brevity and typos. Message typed with my thumbs from an Open
Source OS.

**Comment by laryn** [comment]
Thanks, I now see the "Reorder" link if there is more than one Layout with the same context path:

![screenshot 2016-12-27 20 43 01](https://cloud.githubusercontent.com/assets/871421/21512648/36782386-cc75-11e6-9f4b-934ffa55f5b2.jpg)

This works for current core functionality so I will close this issue.

@Gormartsen's solution for #2412 does raise some questions about sorting/weighting layouts when you have supplemental/wildcard layout paths listed for some layouts but that's an issue for [layout_wildcard](https://github.com/backdrop-contrib/layout_wildcard) I suppose.
