### ISSUE TITLE
Improve test requirements / setup when running against local dev

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2439]
When I build a dev environment for Backdrop, I'll start with a clean VM install of some flavor of Linux and install the Drupal 7 package to get the LAMP stack and the handful of required PHP plugin packages.  A couple minutes of admin work to fetch Backdrop, set up a database, and configure apache, and I'm able to run through the web `install.php` process.

The install is successful, but this creates an environment that does not match the automated test environment and some of the tests fail.  Some things can be updated by a test's `setup()` function, like ensuring the default timezone is UTC, not the dev's local timezone.  Some cannot, but can be detected and a clear error returned, like missing intl and zip PHP plugins.

PR: https://github.com/backdrop/backdrop/issues/1694

**Comment by jlfranklin** [comment]
PR adds some requirements checks and extra setup to reduce test false negatives.

**Comment by quicksketch** [comment]
This entire PR is pure awesome cleanup! I gave it a review and everything looks great to me. Thanks @jlfranklin for taking the time to work through this. I'm marking this RTBC, but I'll leave it be if @Gormartsen or anyone else has time to review it in the next day.

**Comment by Gormartsen** [comment]
No promises until first days of January.


Regards,
Gor Martsen
@gormartsen

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/pull/1694 into 1.x and 1.5.x. Thanks again @jlfranklin! No worries Gor, this all looked like just plain-sense improvements. Zen.ci had no complaints when running the updated code.
