### ISSUE TITLE
Admin bar: ghost "settings" and "edit" menu items for layouts.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2443]
This issue was originally filed against the b.org issue queue, but moved to core as others seem to be having that issue too.

Here's what I see in all Structure -> Layouts -> %layout_name% menus:

![backdropcms org-admin_bar-ghost_menu_items_in_structure-layouts](https://cloud.githubusercontent.com/assets/2423362/21578538/10601f26-cfd8-11e6-9183-15c715c7791c.png)

Tried a cache clear, but it didn't help.

**Comment by Graham-72** [comment]
I confirm that this is happening with BD 1.5.2, for five of my six main sites. The blank appears for all structure>layout menu entries that have subsidiary options i.e. it appears at the fourth level.

I will try and find out why this is not happening on one of the sites.

**Comment by docwilmot** [comment]
No longer happening
