### ISSUE TITLE
[UX] Misleading text on "Backdrop already installed" page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2445]
If you are trying to set up Backdrop on a new site but make some mistakes, you may accidentally end up on a page telling you that backdrop is already installed. One of the things on this page is the text: 
`To install to a different database, edit the appropriate settings.php file in the sites folder.`

I believe this is left over from Drupal when all settings files were in the sites folder. For backdrop, we should change this text so it is clear that the settings file is usually in the docroot.

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1765~~
PR by @jenlampton at https://github.com/backdrop/backdrop/pull/1847

**Comment by klonos** [comment]
...lets scratch the easy tasks off our list 😄

**Comment by klonos** [comment]
...I noticed that we use the word "appropriate":

` ... edit the appropriate settings.php file ...`

This will either need to be removed altogether (considering that most people won't be using the multi-site feature), or then the text will need to be changed to accommodate for both single- as well as multi-site installations. Something like so:

> To install to a different database, edit the settings.php file located either in your site's root folder or in the appropriate sites folder.

**Comment by jenlampton** [comment]
I don't have any problems with the word `appropriate`. Even though I am not using multi-site on any backdrop sites (yet) I do almost always use the new settings.local.php file we reference at the bottom of settings.php, so the phrasing is still suitable.

The part that's no longer accurate is `in the sites folder.`

**Comment by klonos** [comment]
> The part that's no longer accurate is `in the sites folder`.

My PR says `in the root folder of your site.` I guess that for people using multi-site the "of your site" part applies to every `settings.php` file of every individual site.

**Comment by jenlampton** [comment]
How about `usually in the root folder of your site`? multi-site definitely won't have those files in the root folder.

**Comment by quicksketch** [comment]
Agreed with @jenlampton, the word "usually" is key here. Otherwise we're swapping one inaccurate message for another for multisite installations.

**Comment by jlfranklin** [comment]
There are only two possibilities. Let's spell it out for the user. "Most sites will find their settings.php in the docroot. Sites using Backdrop's multisite feature will find it under the sites directory."

We can also call conf_path(), check if it is the root path, and display one message or the other. If it's not a security issue, we can specify where Backdrop thinks the settings file should be.

**Comment by jenlampton** [comment]
> There are only two possibilities. Let's spell it out for the user. "Most sites will find their settings.php in the docroot. Sites using Backdrop's multisite feature will find it under the sites directory."

This is too much text and is likely to confuse people who aren't using multisite (the majority). The more text we add, the more people are likely skip over it. 

My vote is for being as concise as possible. How about we always print  "Most sites will find the settings.php file in the docroot." and then we also run a `conf_path()` to check if it is the root path, and only if it's not, we can add "Sites using Backdrop's multisite feature will find the settings.php file under the sites directory."

**Comment by jenlampton** [comment]
Hm, I think I also object to the word "docroot" appearing in the UI. Let's keep it closer to the original text:

Before: 
`To install to a different database, edit the appropriate <em>settings.php</em> file in the <em>sites</em> folder.`

After:
`To install to a different database, edit the appropriate <em>settings.php</em> file located in the root directory for your site.`

After, with multisite:
`To install to a different database, edit the appropriate <em>settings.php</em> file located in the root directory for your site.  Sites using Backdrop's multisite feature will find the appropriate <em>settings.php</em> file in the sites directory.`

**Comment by jenlampton** [comment]
Pushing a PR for review: 
<img width="888" alt="screen shot 2017-04-27 at 10 39 56 pm" src="https://cloud.githubusercontent.com/assets/397895/25515590/7c372cc6-2b9a-11e7-9f07-16dd577ac469.png">

**Comment by Dinornis** [comment]
The new text is much better, thanks.

**Comment by klonos** [comment]
Since there are going to be multiple settings.php files inside the `/sites` folder for each site, better say "Sites using Backdrop's multisite feature will find their <em>settings.php</em> file in the respective folder inside the <em>sites</em> folder."

...or something like that.

**Comment by quicksketch** [comment]
I'm having trouble with the new text. Like @klonos reports this isn't accurate for multisites. How about we do a quick check on `conf_path()` and vary the message based on where `settings.php` is located? I think the two strings would be best:

```
To install to a different database, edit the `settings.php` file located in the root folder of this site.
```

```
To install to a different database, edit the `settings.php` file corresponding to this site within the `sites` directory.
```

**Comment by jenlampton** [comment]
That works. I'll update the PR.

**Comment by quicksketch** [comment]
Well now we have a bit of a translation problem. The string concatenation makes it so potx won't be able to parse it. And you end up translating the entire set of instructions twice with a different sentence in the middle. I think we should split each of these into its own string and then assemble the `<ul>` list outside of the translated  strings.

**Comment by jenlampton** [comment]
Pushed a new PR that rebuilds the page using `theme('item_list')` where all the list items are translated separately. This is probably how the page should have been built in the first place...

**Comment by klonos** [comment]
RTBC.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/1847 into 1.x only, as we're changing translated strings around here. This will be in 1.7.0.
