### ISSUE TITLE
[UX] Admin bar: expose the "Manage fields" and "Manage display" for vocabularies. 

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2447]
...we do that for content types and user accounts. Why not for vocabularies?

If I get this right, then this should be taken care of by https://github.com/backdrop/backdrop/blob/1.x/core/modules/field_ui/field_ui.module#L72 and https://github.com/backdrop/backdrop/blob/1.x/core/modules/field_ui/field_ui.module#L124 as I believe is done so for the rest of the fieldable things that have menu items in the admin bar. But it doesn't happen(?),

---

~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1706~~
New PR by @Al-Rozhkov : https://github.com/backdrop/backdrop/pull/1813

**Comment by klonos** [comment]
Not sure if this the right way to go about it (because I feel that this should be handled by the code that handles the respective tabs for other entities in field_ui.module), but this works for me.

**Comment by klonos** [comment]
...oops, no it doesn't. The menu items show up in the admin bar and the pats work, but the forms displayed in these pages are not the proper ones. Back to NW. Sorry for the noise.

**Comment by serundeputy** [comment]
With release tomorrow and still work to be done here moving to milestone `1.6.1`

**Comment by Al-Rozhkov** [comment]
Oh! It was tricky to catch, but solution is pretty simple :)

**Comment by Dinornis** [comment]
PR 1813 looks good.

**Comment by klonos** [comment]
> The menu items show up in the admin bar and the pats work,

"pats"?? ...I don't know what I was referring to. "tabs" perhaps? I'm not on drugs; I promise 😄 ...just tired that's all.

@Al-Rozhkov thanx for picking this up as my time is very limited lately. Good catch and much simpler code change in the PR. RTBC

**Comment by quicksketch** [comment]
Nice one @Al-Rozhkov! Merged https://github.com/backdrop/backdrop/pull/1813 into 1.x and 1.6.x.
