### ISSUE TITLE
[UX] remove 'Configure menu' contextual link from menu blocks

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2453]
I always click this by accident, and I never need to change the menu's name or description when I do it. Let's remove this seldom-used link from the place where it's oh-so likely to trip people up!

**Comment by quicksketch** [comment]
This is great. Thanks @jenlampton and @Dinornis! Merged https://github.com/backdrop/backdrop/pull/1721 into 1.x for 1.6.0.
