### ISSUE TITLE
Remove breadcrumb block from home page.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2454]
Since it won't do much good there anyway, it doesn't make much sense to have the block on the page. We should remove it for people :)

**Comment by quicksketch** [comment]
I'll take a look at this one.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/1745 that adds an update hook and removes the breadcrumb from the home layout on new installs.

**Comment by jenlampton** [comment]
This looks great. I've confirmed that on existing sites it the update hook removes the breadcrumb, and new installs are created without the block. 👍

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/1745 into 1.x.
