### ISSUE TITLE
Why isn't the "Block title type" option available for custom blocks?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2459]
Most other blocks (besides the "Page title" pseudo-block) have this drop-down menu available by default:

![backdrop-block_title_type_drop-down_menu](https://cloud.githubusercontent.com/assets/2423362/21755873/e545f792-d66d-11e6-947e-6031f268cfd4.png)

Custom blocks do not have it...

1. Add a custom block (or edit an existing one) -> no "Block title type" option.
2. Make the custom block reusable by clicking the respective checkbox -> the "Admin label" field is made available via `#states` -> still no "Block title type" option at the top of the form.
3. Give the block an admin label and save it.
4. Edit the block again -> the "Block title type" option is now available at the top of the form.

...I would expect the "Block title type" option to be made available via `#states` after step 2 (clicking the "Make this block reusable" checkbox).

**Comment by quicksketch** [comment]
It's because it's not needed. All blocks have a "Custom" title, so there's no need to have a "Default" option. But the field just isn't required, so you can leave it blank for "None". Basically it's simply unnecessary to have title types for a custom block.
