### ISSUE TITLE
Update CKEditor to version 4.6

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2463]
While preparing for 1.6, we should update to the latest version of CKEditor, version 4.6. We are currently on version 4.5.

Version 4.6 adds some interesting new abilities (http://ckeditor.com/blog/CKEditor-4.6-released) including a notifications system, drag and drop file uploading, balloon-based forms, and other features.

However as we're on the cusp of Backdrop 1.6, we don't have time to implement new features, but we can at least update the library and bundle the new default plugins, even if they are not enabled or integrated yet.

Version  4.6 also includes a new "flat" variation on the default theme, called "Moono-Lisa" (the current version is called "Moono"). I'm not sure whether we should use the new default theme or stick with the old default.

---

~~PR by @quicksketch backdrop/backdrop#1740.~~
PR by @YesCT https://github.com/backdrop/backdrop/issues/1746

**Comment by quicksketch** [comment]
I'm working on rolling a PR for this functionality.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/1740.

I did update the theme to use the new default, but otherwise all functionality should be identical.

**Comment by Dinornis** [comment]
Seems to be working fine, not sure about which theme would be preferable, highly subjective, would not worry about that.

**Comment by olafgrabienski** [comment]
Had a look at the PR and created a test page with all kind of formatting. Works fine.

I like the new editor theme. Is there a way to choose the theme in the settings (e.g. admin/config/content/formats/filtered_html)? Didn't see it at first sight. Btw, on the mentioned page under "Active toolbar", you see the editor still themed by Moono (old theme).

Another question: testing links in the editor, I noticed that you can't just put in a URL like www.example.com (without `http://(s)`). If you do so, the link on your site will be `http://mysite.org/www.example.com`, and by clicking it you get a "Page not found". I'd suggest to add a relevant help text and/or to check the form if there's a protocol in the link. Does anyone know if there is already a related issue?

**Comment by YesCT** [comment]
I think changing the theme (to the new default) is out of scope, and deserves its own issue and discussion.

From rebuilding multiple different ways, and talking with quicksketch, I want to note that upload widget is added to the build-config.js (which depends on the notification system) so that later, when the integration is added, it won't show as replacing with a whole new ... everything. But the other features mentioned were not actually added.

Some more notes coming on my actual pull request.

**Comment by quicksketch** [comment]
> I think changing the theme (to the new default) is out of scope, and deserves its own issue and discussion.

Thanks, I agree, especially in light of @olafgrabienski's observation that the configuration page is separately coded to appear in the "Moono" theme.

The PR is looking great @YesCT! I'll give it another pass, and some more manual testing would be appreciated on the sandbox, as updating the CKEditor library has affected some Backdrop-specific functionality in the past that isn't covered by SimpleTest (e.g. inserting an image in the editor on the node form).

**Comment by Dinornis** [comment]
Ran more test with inserting images in the editor and through image field, all seems to work fine.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1746 into 1.x. Thanks @YesCT, @Dinornis, and @olafgrabienski! Please file an issue and tag it for 1.6.0 if any issues are found.
