### ISSUE TITLE
[UX] checking checkboxes within Fieldsets often collapse fieldsets instead

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2467]
In the views UI Fieldset labels don't have enough space below them. This causes me to often collapse the fieldset when I am trying to check the first checkbox within. A smidge more space below the fieldset label will solve this problem.

Before:
![screen shot 2017-01-14 at 11 09 01 pm](https://cloud.githubusercontent.com/assets/397895/21960905/b73169d2-daae-11e6-95a4-06d8e95b1800.png)

After:
![screen shot 2017-01-14 at 11 10 44 pm](https://cloud.githubusercontent.com/assets/397895/21960903/b4190a2a-daae-11e6-9917-52ca5dcb8794.png)

----
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1751

**Comment by Graham-72** [comment]
I think this also fixes #1734 thank you.

**Comment by serundeputy** [comment]
Thanks @jenlampton and @Graham-72 looks and works good!

This is merged into `1.5.x` and `1.x` and will ship with `1.5.3` and `1.6.0`.
