### ISSUE TITLE
Views UI: title missing from the "Access" box.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2468]
Anyone know why [we've left this empty](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/plugins/views_plugin_display.inc#L1100)?:

![backdrop-views_ui-title_missing_from_the_access_box](https://cloud.githubusercontent.com/assets/2423362/21966089/1634e400-dbc1-11e6-8a3b-c4c34d32b3ae.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1753

**Comment by klonos** [comment]
Tiny one-liner change. @serundeputy review if you have time please?

![backdrop-issue2468-pr1753](https://cloud.githubusercontent.com/assets/2423362/21966125/d23b4676-dbc1-11e6-9716-db2f77aba6b5.png)

**Comment by quicksketch** [comment]
Perhaps it's just because saying "Access" followed by "Access: Permission" is redundant? I do agree it seems a little strange without a heading present at all.

I think in D7 it just looked so similar that adding a heading wasn't necessary:
![image](https://cloud.githubusercontent.com/assets/100206/21967188/fee8dcc8-db36-11e6-98e2-b36b8c290f4e.png)

So rather than adding another heading, perhaps we should work on reducing the unnecessary added padding?

**Comment by klonos** [comment]
I noticed this (along with another issue with even/odd classes added to the settings rows for which I have not filed an issue yet) while working on #930. After I added zebra coloring in the rows, this row seemed to be "stray", without a heading:

![backdrop-issue2468-pr1753-stray_zebra-colored_row_without_header](https://cloud.githubusercontent.com/assets/2423362/21967595/6e1272f6-dbde-11e6-8e3e-b5ca6b897394.png)

Besides, the rendered HTML code seemed inconsistent without an `<h3>` like the rest of the boxes (`.views-ui-display-tab-bucket` divs):

![backdrop-issue2468-pr1753-no_h3_title_in_rendered_html](https://cloud.githubusercontent.com/assets/2423362/21967606/83584f1e-dbde-11e6-836b-d5b0792e03ad.png)

So, this is not unnecessary added padding per se (assuming that it is the space between the access setting row and the "Settings" box that you are talking about). In order to get rid of it, we'd either need to render the access setting as part of the "Settings" box or to target that single row specifically via css (which would be special-casing something for no obvious reason in my opinion).

**Comment by klonos** [comment]
...point is that the current code renders a box/bucket without a header. So we either need to move that setting as part of another box, or specifically target and hack the css for it. I think that the single line that adds the title back is less code and does not special-case anything (that might make beginner coders wonder why).

**Comment by serundeputy** [comment]
I think it looks good with the `ACCESS` header.
Tells the user that there is configurable access section for views.

I'm in favor of the consistent markup over a weird css selection and I don't think we should move the  access settings into the above page settings `<div>`.

I'm for merging current `PR` as is.   @quicksketch objections?

**Comment by klonos** [comment]
> I'm for merging current `PR` as is.   @quicksketch objections?

Lets try to get this issue within his radar 😄 😉

**Comment by Dinornis** [comment]
I am on the fence about this although since the Access heading has no other options/settings underneath it I am leaning more towards keeping the access settings within the (Display) settings section and fixing the odd vertical spacing.

**Comment by quicksketch** [comment]
I think the consistency fix makes it so that we won't have to special-case anything in CSS and is less likely to need maintenance in the future. So while I'm ambivalent as well, if this code is ready I'm in favor of merging it.

The PR has an issue that the new title isn't translated however, let's fix that up: https://github.com/backdrop/backdrop/pull/1753#pullrequestreview-35481861

**Comment by klonos** [comment]
Fixed.

**Comment by Dinornis** [comment]
Looks good 👍

**Comment by klonos** [comment]
...let's get this in soon then 😄

**Comment by quicksketch** [comment]
Thanks @klonos! And @Dinornis you are kicking some ass reviewing issues! Thank you!

Merged https://github.com/backdrop/backdrop/pull/1753 into 1.x and 1.6.x.

**Comment by klonos** [comment]
I was to say that @Dinornis seems to be a good fit for helping with triaging the issue queues and perhaps helping with the contrib queue as well. I mean if you're up to it @Dinornis.
