### ISSUE TITLE
"required" asterisk missing on text date field with no field set

### ISSUE THREAD

**Issue by YesCT** [backdrop/backdrop-issues#2469]
Noticed while watching https://github.com/backdrop/backdrop-issues/issues/289 be tested,

that a text date field that is required is missing the asterisk.

To test (to make sure fixing does not cause other regressions):
date field with no end date
date field with end date
multivalue date field with no end date
multivalue date field with end date

There are soooo many permutations for date, here is a site config export that can be imported to help with testing [config-lotsofdates.tar.gz.zip](https://github.com/backdrop/backdrop-issues/files/707216/config-lotsofdates.tar.gz.zip)

An export of a site with a content type with those fields would be handy.

**Comment by quicksketch** [comment]
Here's an export that has a content type with a broken date field.

Bizarrely, GitHub doesn't allow "gz" extensions, so I added .zip to the file name (but it needs to be removed).

[config.tar.gz.zip](https://github.com/backdrop/backdrop-issues/files/706939/config.tar.gz.zip)

Here's a date field (as text) that demonstrates the missing asterisk:

![screenshot from 2017-01-15 14-02-37](https://cloud.githubusercontent.com/assets/100206/21966607/5439f5a6-db2b-11e6-815c-b6667117b072.png)

**Comment by YesCT** [comment]
Thanks. Used that config export and added more variations.

With that, I can with some confidence say that the situation where the asterisk is missing,
only effects dates that:
are "text",
has the exclude field set check box unchecked. (Note it is usually checked by default, so usually there is not a field set, except when the widget is "select".)

Does not effect asterisk:

with or without end dates, and even if the end date is not required (but the field is).
(Help text does not effect the missing asterisks, as one would expect.)

[config-lotsofdates.tar.gz.zip](https://github.com/backdrop/backdrop-issues/files/707216/config-lotsofdates.tar.gz.zip)

**Comment by argiepiano** [comment]
I can confirm this is still an issue, as noted in #6274.

The image below shows a required text date field, which is missing the asteriks. 

<img width="605" alt="Screen Shot 2023-11-19 at 9 06 36 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/755aa3fe-0365-43bf-8047-b297149a0082">

To reproduce, this code may be helpful:

```php
  $form['my_text_date'] = array(
    '#type' => 'date_text',
    '#date_format' => 'l F j, Y',
    '#title' => t('My text date'),
    '#default_value' => '',
    '#required' => TRUE,
    '#size' => 40,
  );
```

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4571 submitted. Ready for testing and review.

**Comment by quicksketch** [comment]
Thanks @argiepiano! Wow super simple fix here. Thanks I have merged https://github.com/backdrop/backdrop/pull/4571 into 1.x and 1.26.x.
