### ISSUE TITLE
Typo: "4 bit UTF-8 support" -> "4-byte UTF-8 support"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2481]
![backdrop-site_status-typo-4_bit_utf-8_support](https://cloud.githubusercontent.com/assets/2423362/22116198/dee38ba4-dec3-11e6-9e34-2aef8c3a8834.png)

bit -> byte

---
PR by @dyrer: https://github.com/backdrop/backdrop/pull/1760

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1760 into 1.x for 1.6.1. Thanks @dyrer!
