### ISSUE TITLE
In Manage Fields, add control to change the "Title" field's Display Name

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2485]
It seems very unintuitive that this can only be changed in 'configure' since you're doing very similar operations on custom fields.

![image](https://cloud.githubusercontent.com/assets/5607236/22176385/116b5926-dfd7-11e6-93cb-6c3450d7e1c1.png)

**Comment by klonos** [comment]
@jenlampton way ahead of you 😄: #1950
