### ISSUE TITLE
uploaded image file not deleted

### ISSUE THREAD

**Issue by gembes** [backdrop/backdrop-issues#2490]
Uploaded image file not deleted after node deleted..
in drupal 7, image file deleted after deleting  node

FYI : fresh install version 1.6

**Comment by gembes** [comment]
file deleted after cron...
[solved]

**Comment by serundeputy** [comment]
Looks like you've got it.  After you delete the node the file is marked as temporary and after 6 hours cron garbage collection picks it up and deletes it.

So, you have to wait 6 hours to see the result.

**Comment by jlfranklin** [comment]
What does the new "manage files" view show?  Does it say the file is "pending deletion?"
