### ISSUE TITLE
Update /sites/README.md

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2491]
Needs to account for layouts and there's a small typo there as well.

---
PR by @klonos https://github.com/backdrop/backdrop/pull/1766

**Comment by klonos** [comment]
I haven't actually used multi-site installations, so this part of the README made me wonder...

> **URL:** http://www.example.com:8080/mysite/test/
> ```php
> $sites['8080.www.example.com.mysite.test'] = 'example';
> ```

If the site was configured as `$sites['8080.www.example.com.au.mysite.test'] = 'example';` using dots instead of slashes, then how do we differentiate between these two:

`http://www.example.com.au:8080/mysite/test/`
`http://www.example.com:8080/au/mysite/test/`

**Comment by jlfranklin** [comment]
My experience with Backdrop mutlisite has been with different domains, all at the root.  That way of doing it does seem .... fragile.

The host, port, and path are all three separate concepts, and should be stored as separate items.  That means the `$sites` array is backwards.  It would work better if we flip it around, like this:

```php
$sites['example'] = array(
  'host' =>'www.example.com.au',
  'port' => 8080,
  'path' => 'mysite/test',
);
```

**Comment by klonos** [comment]
@docwilmot has actually already marked the PR as RTBC.

**Comment by klonos** [comment]
I find it really weird too @jlfranklin, but that's a different issue.

**Comment by quicksketch** [comment]
Thanks PR at https://github.com/backdrop/backdrop/pull/1766 has been merged.

**Comment by klonos** [comment]
>I find it really weird too @jlfranklin, but that's a different issue.

@jlfranklin: #2534 😉
