### ISSUE TITLE
Add jQuery and jQuery UI versions in site status report.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2492]
Would be nice to be able to see the version being used since these are two important libraries. Also, users coming from Drupal are used to jQuery Update showing that info there.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1767

**Comment by klonos** [comment]
...screenshot from the PR sandbox:

![backdrop-issue2492-pr1767](https://cloud.githubusercontent.com/assets/2423362/22217129/f3726dbc-e1f5-11e6-8792-98adf15f8a07.png)

**Comment by klonos** [comment]
... #2493

**Comment by Dinornis** [comment]
Well done, thank you.

**Comment by Dinornis** [comment]
Should this issue have a milestone?

**Comment by klonos** [comment]
> Should this issue have a milestone?

I never seem to get milestones right, but what the heck... lets try for the next 1.6.1 release. Unless people see that as a feature, in which case it might get pushed to 1.7.0

**Comment by quicksketch** [comment]
This is pretty trivial and I think it could be considered a UX improvement? If so we can put it in 1.6.1. What do you think?

**Comment by klonos** [comment]
Yep, I'd love it if this was in 1.6.1 👍  ...it will make me feel a tiny bit better since i did not get to contribute that much in 1.6.0 😛

**Comment by quicksketch** [comment]
Great, thanks merged https://github.com/backdrop/backdrop/pull/1767 into 1.x for 1.6.1.
