### ISSUE TITLE
Allow + symbol in usernames

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2494]
Followup from https://github.com/backdrop/backdrop-issues/issues/1994#issuecomment-274277549
See issue in Drupal: https://www.drupal.org/node/2157963

---
PR @klonos: https://github.com/backdrop/backdrop/pull/1769

**Comment by klonos** [comment]
Created a PR from [the patch](https://www.drupal.org/files/issues/drupal-allow-plus-in-usernames-2790923-3.patch) in the D7 issue: https://www.drupal.org/node/2790923

**Comment by quicksketch** [comment]
Looks great to me!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/1769 into 1.x and 1.6.x. Thanks @klonos and @docwilmot!
