### ISSUE TITLE
[UX] List URL redirects: the "Update options" fieldset should always be visible.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2495]
![backdrop-manage_url_redirects-bulk_operations_fieldset_shown_via_states](https://cloud.githubusercontent.com/assets/2423362/21577080/c1f3edc6-cfa1-11e6-9d9f-3f503f7b270e.gif)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1771

**Comment by klonos** [comment]
...this was not done via `#states`. It was by attaching https://github.com/backdrop/backdrop/blob/1.x/core/modules/redirect/js/redirect.admin.js which only includes a single function with the only purpose of it being to shows/hide the fieldset. Not sure why this was added in the first place(?). PR removes `'#attached'` from the form and also deletes the entire `redirect.admin.js` file.

**Comment by Dinornis** [comment]
The Redirect Functional Tests throws 45 debug messages, but maybe I am just using the testing facility incorrectly.  Everything else seems fine.

**Comment by klonos** [comment]
@Dinornis all PRs run the tests and this one comes back all green: https://github.com/backdrop/backdrop/pull/1771

...so I'm not sure what you are talking about. Are you running tests locally?

**Comment by Dinornis** [comment]
Sorry, I enabled the testing module and ran the test within the PR.

**Comment by klonos** [comment]
Hmm. I think that that should have worked. Never tried it, but quite often I see people saying that the tests fail here but pass locally - not the other way around. Beats me.

**Comment by Dinornis** [comment]
It is quite likely I have not used the tools correctly 😄

**Comment by quicksketch** [comment]
Nice one! Thanks @Dinornis for your review once again and @klonos for the fix. Merged https://github.com/backdrop/backdrop/pull/1771 into 1.x for 1.6.1.
