### ISSUE TITLE
View > Contextual Filter > Notice: Undefined property

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop/backdrop-issues#2496]
(I can export and paste view if you like)  I have a view and have added 1 contextual filter... it is pretty much an exact copy (the view) from a Drupal 7 site.  

Path: /business-listings/%
Filter: Content: Has taxonomy term ID (with depth)
depth - 2
Specify validation criteria - checked
Validator - Taxonomy Term
Vocab - Business Listings Categories (yes, it is a "term reference" field on my content type)
Filter value type - Term name converted to Term ID
Transform dashes - checked

Is the basic setup.  When I go to the path:
/business-listings/hotels
I get this PHP Notice:
Notice: Undefined property: stdClass::$machine_name in views_plugin_argument_validate_taxonomy_term->validate_argument() (line 179 of C:\wamp\www\japantravel\core\modules\taxonomy\views\views_plugin_argument_validate_taxonomy_term.inc).

This is a pretty simple contextual filter view... works fine in the D7 site... thinking it is actually a bug in Backdrop??

---
PR: https://github.com/backdrop/backdrop/pull/1925

**Comment by JugglingCoder** [comment]
I "Hacked" the core file:
\core\modules\taxonomy\views\views_plugin_argument_validate_taxonomy_term.inc
around line: 179
From:
if ($term && (empty($vocabularies) || !empty($vocabularies[$term->machine_name]))) {
To just:
if($term){
and filters work correctly.  When I var_dump "$term" above this line, there is no "machine_name" property for the term object so the "if" fails and therefore the contextual filter fails.  I have no idea why there is no "machine_name" property...  Anyways... its working with the "hack" I mentioned... don't know if any of the core developers want to change it or fix it or leave as is.

**Comment by jenlampton** [comment]
I ran into this today too, the problem is that the machine name for a term is `$term->name`. PR forthcoming.

**Comment by opi** [comment]
Reviewed and approved: backdrop/backdrop/pull/1925#pullrequestreview-54529445

**Comment by quicksketch** [comment]
Thanks @opi for the review and @jenlampton for the PR! Merged https://github.com/backdrop/backdrop/pull/1925 into 1.x and 1.7.x. Thanks @JugglingCoder for identifying this problem and reporting it!
