### ISSUE TITLE
[UX] Consistency with the actions drop-down menu in listing pages.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2497]
When the listing page is generated by a view and VBO is used, we get this:

- "Operations" for the fieldset label.
- "- Choose an action -" placeholder as the default value for the drop-down menu.
- "Execute" as the submit button label.

When the listing is a non-views generated one, we instead have this:

- "Update options" for the fieldset label.
- The first available option is the default selected value for the drop-down menu.
- "Update" as the submit button label.

If a listing is converted to be generated by a view, I guess we will automatically get consistency as an added bonus. With non-views listings though we should be making sure that we use the same labels/patterns as with the views-provided ones.

PS: When there is only a single operation available, does it make sense to have the "- Choose an action -" placeholder or even to be rendering the drop-down and a separate submit button in the first place? I mean, why not ditch the drop-down in these cases and replace the label in the submit button with the label of the single operation that's available? Instead of 3 clicks (open the drop-down, select the single operation, click the submit button), it'd be only one => UX+

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1770~~
Replaced by PR https://github.com/backdrop/backdrop/pull/2542

**Comment by klonos** [comment]
PR up for review...

There are currently 3 non-views operations fieldsets: `/admin/content/comment`, `/admin/config/urls/path/bulk-update` and `/admin/config/urls/redirect/list` (this last one suffers from #2495, so you will need to create a redirect and select its checkbox in order to make the fieldset appear).

The one in the "Manage comments" page was the only one not being wrapped in a `.container-inline` div (the class was added to the fieldset itself). Fixed that and went with `comment-operations` as the fieldset class (the other fieldsets use `.path-bulk-operations` and `.redirect-list-operations`). Let me know if you think of a better class name that should be used instead.

The comments operations form again was different from the other two in that the `$form` array was using `['options']` as a key instead of `['operations']`. Fixed that as well. Let me know if this is not an acceptable change in the 1.x cycle and I'll revert that.

The '#title' for the drop-down menu in the "Generate URL aliases" page was set to an empty string while in the other two forms was set to "Operations" and was then hidden with `'#title_display' => 'invisible'`. Fixed that, but I think we should change all these labels to "Actions" instead (since the default option is "Choose an action"). Thoughts?

**Comment by docwilmot** [comment]
This is a nice idea. Test fixes should be simple, then RTBC for me.

**Comment by quicksketch** [comment]
The PR looks good but needs to have it's tests updated for the changes.

Long-term the Comment listing should be converted to a View of course. But paths and redirects will probably stay as hand-coded operation pages.

**Comment by herbdool** [comment]
@klonos I fixed the tests so they pass. I had to create a new PR since your branch was deleted.

Somehow I ended up fixing this because it was mistakenly linked to the Meta: Improve internationalization.

**Comment by klonos** [comment]
Looks good, and tests are green 👍 ...RTBC

**Comment by klonos** [comment]
...milestone candidate for 1.12.6?

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2542 into 1.x and 1.12.x. Thanks folks!
