### ISSUE TITLE
[UX] Sort list of content types by human-readable name

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2502]
The list of content types is sorted by machine name: 
![screen shot 2017-01-26 at 9 53 43 pm](https://cloud.githubusercontent.com/assets/397895/22361785/fa666632-e411-11e6-9d74-3c725ac387e8.png)
These should probably be sorted by label instead.

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1773~~
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1774~~
PR by @klonos and @quicksketch: https://github.com/backdrop/backdrop/pull/1809

**Comment by Dinornis** [comment]
Yes.

**Comment by olafgrabienski** [comment]
> These should probably be sorted by label instead.

Very good idea!

It's also important for multilingual sites when they use the built-in content types and translate the label which then is alphabetically at a different 'place*, e.g. **P**age vs. the german **S**eite.

**Comment by klonos** [comment]
Very good idea indeed. One-liner PR up for review. It's paying attention to those small details that will make Backdrop a perfected version of Drupal 7 😉

**Comment by olafgrabienski** [comment]
Looks good:

![screen-backdrop-pr-1773-content-types-order](https://cloud.githubusercontent.com/assets/14188307/22380753/ebd07dc6-e4be-11e6-8a49-b63d5acaf5b3.png)

**Comment by olafgrabienski** [comment]
I guess we have to fix the order of content types on the "Add content" page as well. See in comparison:

**Content types page, sorted now by label:**
<img width="751" alt="screen-backdrop-pr-1773-order-1-page-content-types" src="https://cloud.githubusercontent.com/assets/14188307/22390068/34eafc46-e4e9-11e6-9650-5d70598af042.png">

**Add content page, sorted still by machine name:**
<img width="751" alt="screen-backdrop-pr-1773-order-2-page-add-content" src="https://cloud.githubusercontent.com/assets/14188307/22390069/34f1a226-e4e9-11e6-9679-ea55fa539ef3.png">

**Comment by klonos** [comment]
PR updated to also sort the "Add content" page list by human name instead of machine name 😉 Thanx for catching that @olafgrabienski 👍

**Comment by jenlampton** [comment]
Well @klonos it's up to the core committers how they choose their workload, but I would imagine that all PRs marked RTBC get reviewed, regardless of milestone or tag.

**Comment by Dinornis** [comment]
Works great. Marking RTBC.

**Comment by olafgrabienski** [comment]
Nice, thanks @klonos !

**Comment by serundeputy** [comment]
@klonos thanks this is great!

I left a review on the PR: https://github.com/backdrop/backdrop/pull/1773

I think we should add tests too.  If this is to become or already is the user expectation we should test for it.

**Comment by klonos** [comment]
Good catch on doing the sorting in the module level instead of the theme level @serundeputy 👍 ...filed a new PR (because I don't know how to revert commits/changes through the GitHub web UI).

From [your comment in the previous PR](https://github.com/backdrop/backdrop/pull/1773#pullrequestreview-19217610):

> You'll want to change the `$a['title']` to `$a->name` as the function `node_type_get_types()` is returning objects not arrays and make the corresponding change for `$b['title']`.

Not entirely sure how/why I need to make the specific change. AFAICT, [this line](https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/node.pages.inc#L48):

```php
  return theme('node_add_list', array('content' => $content));
```

...will still use the `$content` array to return the object. So, if I make sure that I have sorted the array beforehand, it should still be OK. At least it works for me 😛 

>I think we should add tests too. If this is to become or already is the user expectation we should test for it.

I agree, but unfortunately, I don't speak test language yet 😞. I would appreciate any pointers as to where to begin, but in all honesty, with my new job commencing tomorrow, I don't know how much time I'll be able to allocate on actually learning this 😞 ...but it is definitely something I want to learn, so I can help with things like adding tests for all the forms that are not saving changes (#2473, #2478 etc.). So, if anyone wants to and has the energy/time, please feel free to jump in and write those tests.

**Comment by klonos** [comment]
...back to NR for the actual code implementation. Feel free to switch back to NW for adding the tests.

**Comment by quicksketch** [comment]
The PR looks like it would have worked but we can improve it a bit with the suggestions @docwilmot left in the PR. I filed a replacement PR at https://github.com/backdrop/backdrop/pull/1809 that includes these changes. Could use another review.

**Comment by Dinornis** [comment]
The PR at http://1809.backdrop.backdrop.qa.backdropcms.org/ initiates an install.

**Comment by olafgrabienski** [comment]
I confirm, no way to test the new PR at the moment.

**Comment by klonos** [comment]
I have no access to open/close the current PR by @quicksketch in order to re-initiate the sandbox 😞

**Comment by serundeputy** [comment]
@klonos @Dinornis @olafgrabienski I've closed and re-opened to get a new sandbox:

http://1809.backdrop.backdrop.qa.backdropcms.org/
User: admin
Pass: Q73BQhHn

thanks.

**Comment by Dinornis** [comment]
Thanks the new PR is now working fine and content type sorting properly as well.

**Comment by olafgrabienski** [comment]
Looks good at first view. Then I've seen another place where the content types don't sort correctly: The *Add content* links in the Admin bar seem to not being ordered at all:

![screen-backdrop-pr-1809-sort-order-add-content-admin-bar](https://cloud.githubusercontent.com/assets/14188307/25426081/5037dd14-2a6e-11e7-81c6-1b219449c9a8.png)

**Comment by jenlampton** [comment]
@olafgrabienski I've noticed a few places where admin menu sort order is odd.. can you create a separate issue for that? Maybe we can solve all those at once.

**Comment by serundeputy** [comment]
I've opened https://github.com/backdrop/backdrop-issues/issues/2655 to address the admin bar issues.

Thanks for all the work on this one @jenlampton @olafgrabienski @klonos @Dinornis @quicksketch what a team! 🎉 🎈 🎉 

Nice UX win for Backdrop!

This is merged into `1.x` and will ship with `1.7`!
