### ISSUE TITLE
URL alias pattern settings form values not saved

### ISSUE THREAD

**Issue by huizache** [backdrop/backdrop-issues#2504]
backdrop 1.6 fresh install, marking it in alias patterns settings. it unmarks itself when configuration is saved, and then does not transliterate...

---

PR by @Al-Rozhkov https://github.com/backdrop/backdrop/pull/1801

**Comment by huizache** [comment]
@serundeputy says: This smells like system_settings_form() to me.
possibly related to: [ backdrop/backdrop-issues#2478](https://github.com/backdrop/backdrop-issues/issues/2478)

**Comment by Al-Rozhkov** [comment]
I can confirm that the option "Transliterate prior to creating URL aliases" is not saving on fresh 1.6.1 install.

**Comment by Al-Rozhkov** [comment]
Actually whole form doesn't work.

**Comment by Al-Rozhkov** [comment]
I guess this one is good candidate for next bug fix release.

**Comment by quicksketch** [comment]
Thanks @Al-Rozhkov and @huizache for the PR and issue (respectively)! I confirmed this form isn't saving at all(!)

I've merged https://github.com/backdrop/backdrop/pull/1801 into 1.x and 1.6.x, so this will be fixed in 1.6.2.

**Comment by quicksketch** [comment]
Oops, this should have been closed and marked as included in 1.6.2. Updating labels and closing.
