### ISSUE TITLE
Project installer won't install - Access denied message in logs

### ISSUE THREAD

**Issue by SamStamport** [backdrop/backdrop-issues#2509]
I'm trying to manually install the Radix theme using URL https://github.com/backdrop-contrib/radix.git. I get no error messages in the UI, but in the log there's an access denied message. 

I'm a newbie. What am I doing wrong. Is this a file permission issue? If so please tell me which file(s) to fix on Windows 10. I'm running Backdrop with XAMPP Version 7.0.13, PHP Version 7.0.13, MariaDB version 10.1.19, Apache version 2.4.23.

**Comment by jenlampton** [comment]
Hi @ColumbiaBlooms, can you please paste the whole access denied message from the log into this issue? That will help us diagnose what's going on. It may be unrelated to Radix!

**Comment by ColumbiaBlooms** [comment]
Happy to help.

Here's the log data.

Details
TYPE	access denied
DATE	Thursday, February 2, 2017 - 5:02pm
USER	Anonymous (not verified)
LOCATION	http://localhost:8080/BD/admin/appearance/install
REFERRER	
MESSAGE	admin/appearance/install
SEVERITY	warning
HOSTNAME	::1
OPERATIONS	

The HOSTNAME value looks odd.

**Comment by jenlampton** [comment]
Is there a link for that log entry, to show you more details?

It looks like the access denied message is related to the project installer `admin/appearance/install` not the theme itself. I would guess you are correct, and this is likely a file permissions issue.  You'll need to make sure that Apache can write to the /themes directory (and /modules, and /layouts) within backdrop. 

I'm not sure exactly what that looks like on windows with XAMP, but if you match whatever is going on with the  /files/ directory, that should work for you.

**Comment by klonos** [comment]
> The HOSTNAME value looks odd.

`::1` is the IPv6 address for localhost. So not odd.

**Comment by klonos** [comment]
...I had another tab open on my browser and meant to reply, but I left that unfinished:

> Hello @ColumbiaBlooms and welcome to Backdrop CMS!

> Can you please try this URL instead: https://github.com/backdrop-contrib/radix/archive/7.x-3.0-beta2.zip

...To manually install a theme (or a module, or a layout) via the URL copy/paste method, you will need to provide a link to a .zip file (tar, tgz, gz and bz2 are also supported, but our releases are currently packaged by GitHub and they are only .zip). It seems that the Radix theme project had a last release back in November 2014 and quite some thing have changed since. I mean, the .info file doesn't even have a `type = theme` defined: https://github.com/backdrop-contrib/radix/blob/1.x/radix.info

**Comment by klonos** [comment]
...I'll give this a go one I get a chance and see if for example trying the "install by project name" method (`radix` in this case) works.

**Comment by klonos** [comment]
Don't bother testing...

![backdrop-issue2509-radix_error](https://cloud.githubusercontent.com/assets/2423362/22576907/bd43f7ae-ea12-11e6-98dc-cab3db1f6045.png)

The "Install project by name" feature is broken (not sure if it ever worked - has anyone actually tried it?). There is a spinning wheel for some seconds (same as when installing from URL), but nothing happens. Will file a separate issue for that.

@ColumbiaBlooms it seems that Radix is not updated to work with latest versions of Backdrop. Please use another theme and sorry about all that.

**Comment by olafgrabienski** [comment]
> The "Install project by name" feature is broken (not sure if it ever worked - has anyone actually tried it?). 

Just installed Backup and Migrate 1.x-1.0.10 on a Backdrop 1.6 site via the "Install project by name" dialog without any issue.

**Comment by klonos** [comment]
Thanx for testing @olafgrabienski it might be my local then, but I'm seeing this in two separate installations of 1.6.0 and 1.5.2. The only thing that differs from a "normal" installation is that my clean URLs are not enabled. Anyways, lets take this to the other issue I've opened.

**Comment by klonos** [comment]
...can others please also try to install Radix and report back if it works or not for them?

**Comment by ColumbiaBlooms** [comment]
Thanks so much for all your hard work on this. Looks like I "opened a can of worms"! Sorry about that.

**Comment by klonos** [comment]
> Looks like I "opened a can of worms"! Sorry about that.

No need to be apologizing @ColumbiaBlooms, we appreciate people reporting bugs as they find them. This way, we get to fix them and make Backdrop a better CMS.

**Comment by jenlampton** [comment]
> I found that the folders mentioned by Jen were marked Read only in Windows 10. I unchecked that box and it looks like error messages disappeared when I install a module.

Does that mean you are not having this problem anymore? Problem solved?

> Odd thing is that when I go back in Windows and check the Read only box it is colored in again.

What does "colored in" mean? Sorry - I'm not familiar with Windows 10.

**Comment by ColumbiaBlooms** [comment]
Hi Jen,

 

                I’m not having the problem anymore. It’s odd, however, that after I unchecked the box it later became colored in or checked. I found this https://www.tenforums.com/general-support/12513-cant-unmark-read-only-folder-2.html?s=d31d61ca9ef8778f58236b33ce426fed that essentially says this is a Microsoft bug. It also mentioned removing OneDrive. Here’s the procedure to do that https://support.office.com/en-US/article/Turn-off-or-uninstall-OneDrive-f32a17ce-3336-40fe-9c38-6efb09f944b0. I removed OneDrive since I don’t use it so we’ll see if that makes a difference in the days ahead. Microsoft acts like Drupal support when it comes to things like this.

 

Sam

**Comment by quicksketch** [comment]
Looks like this has been resolved and there's no recent updates here. Please reopen if needed.
