### ISSUE TITLE
Multi-select now has a fixed-height since 1.6.0

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2511]
Since we released Backdrop 1.6 the multi-select form element has a fixed-height.  I was attempting to increase the height of single-select elements on browsers like Chrome, that don't respect padding on select elements.  Unfortunately, my selector was too general.

----
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1776

**Comment by klonos** [comment]
Tested creating a list field with multiple values for the page content type and that field was rendered properly in the form when adding page content. RTBC from me 👍

**Comment by serundeputy** [comment]
Looks good thanks @jenlampton and @klonos; merged will ship with `1.6.1`.
