### ISSUE TITLE
Project installer: Install projects by name is not working.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2514]
I've never personally used this before (always use either the URL method or the project browser or manually uploading the project files via FTP), but I recently needed to test #2509 and noticed that this feature does not work for me (tested in a 1.6.0 as well as in a 1.5.2 installation).

I've never heard anybody complain about it and this might be a not so often used feature that might have regressed, but @olafgrabienski [said that it works for him](https://github.com/backdrop/backdrop-issues/issues/2509#issuecomment-277208907):

> > The "Install project by name" feature is broken (not sure if it ever worked - has anyone actually tried it?). 
> 
> Just installed Backup and Migrate 1.x-1.0.10 on a Backdrop 1.6 site via the "Install project by name" dialog without any issue.

Can anyone else please test and confirm either success or failure?

PS: my installations do not have clean URLs enabled, so this might have to do something with it.

**Comment by Dinornis** [comment]
I could not get it to work on localhost (MAMP) no error message, no related messages in dblog.

Seems to work on current PRs here.

**Comment by klonos** [comment]
OK, that might be the issue then. I am noticing this on a local, same as @Dinornis. @olafgrabienski were you trying on a local or live?

**Comment by olafgrabienski** [comment]
@klonos It was a remote site.

**Comment by serundeputy** [comment]
this works for me on my local.

Keep in mind for this to work on a local (or server) the machine has to have the ftp service configured and the ports open.  On a server usually some ftp configuration is present on a local this is more probable to fail as ftp is either not configured/installed or the port is not open.

To further complicate things the web user needs to have permission to write the `BACKDROP_ROOT/modules` directory.

**Comment by klonos** [comment]
I am testing this on my local Windows as an admin, so should have all required permissions. IIRC @serundeputy is on linux(?). @Dinornis, @olafgrabienski what are you guys using to test this?

>Keep in mind for this to work on a local (or server) the machine has to have the ftp service configured and the ports open.

I don't understand why this should be the case (at least on a Windows local). I also don't understand why the installation by name fails while the installation by URL works. As I said I have never used this method before, but I always though that the *by name* method was sort of a shortcut for the *by URL* method, "automagically" resolving project URL and then acting pretty much like adding things to the installation queue. I believe that the purpose of that multi-line field was to allow users to install multiple projects (or what was described as "project recipes") via copy-pasting a list of project names from tutorials etc.

**Comment by olafgrabienski** [comment]
@klonos As I said, I tested it on a remote site, it's on a subdomain of my own website running on a shared hosting service (linux / apache / mysql / php). Unfortunately, I've got no time to set up a local environment for testing purposes at the moment, which would be anyway on Mac OS X, not on Windows.

**Comment by Dinornis** [comment]
> ... what are you guys using to test this?
I am testing this on MAMP, but I am sure this is just my configuration.

Could be a firewall issue?
