### ISSUE TITLE
Fix Enabled components checkboxes on Admin Menu Settings page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#252]
"Enabled components" means nothing.  Can we have an explanation as to what components are, and what it means for them to be enabled?

Also, the checkboxes on the admin menu settings page are supposes to adjust the appearance of these menu "components" in real time, but that appears to be broken atm.

**Comment by quicksketch** [comment]
Hm, I think this PR is causing test breakage. I tried to resolve it directly, but it's more complicated than just fixing a typo. I'm going to revert it and make a new PR with the fixes that I know of.

**Comment by quicksketch** [comment]
New PR at https://github.com/backdrop/backdrop/pull/630 that tries to fix this problem again.

**Comment by quicksketch** [comment]
New PR at https://github.com/backdrop/backdrop/pull/663.
