### ISSUE TITLE
Show the number of views at the blog post for guests - How does it work

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#2523]
Hello Developers,

How can I show the number of views on each blog post at the last backdrop CMS? I should be able to see this as an admin and my guests.

Such a module I found not yet.

I would gladly realize it with me.

Thanks in advance.

**Comment by laryn** [comment]
Hi @AlexL777 

Maybe something like Google Analytics? https://backdropcms.org/project/googleanalytics

**Comment by AlexL777** [comment]
Thanks with the module tip and I have now set it up.

But a question still! Can I view the views directly under each blog post? So the visitor of the website will be able to see how often the blogposts have been viewed.

In G-Analytics, the first stats are already visible.

Thanks in advance.

**Comment by BWPanda** [comment]
Sounds like you want https://github.com/backdrop-contrib/statistics

Closing old issue.
