### ISSUE TITLE
Missing "Enable Modules" button

### ISSUE THREAD

**Issue by pixelota** [backdrop/backdrop-issues#2524]
Fresh install of Backdrop 1.52 was immediately updated to 1.6 (still using hte default theme). Selected a list of modules to install, including the Mailchimp module. I got an error that Mailchimp was missing a dependency (entity_ui). 

I continued and arrived at the page where "You may enable modules using the form below or on the main Modules page." This is at example.com/admin/installer/install/enable.

As you see there is no button to enable the modules here. Although I can enable them from the Modules page. (not Mailchimp though)
![missing enable modules button](https://cloud.githubusercontent.com/assets/11141324/22804094/6582ba8c-eecc-11e6-8a2f-ccc29543f077.jpg)

**Comment by quicksketch** [comment]
Thanks @pixelota for the report! This was fixed over in https://github.com/backdrop/backdrop-issues/issues/2200. If you're still experiencing the problem on current versions of Backdrop, please reopen.
