### ISSUE TITLE
Unable to find base table field_config

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2525]
When I add a field of type taxonomy term reference to post, and then try to create or edit a node of any type, I get this error:
```
EntityStorageException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabase.field_config' doesn't exist in NodeStorageController->save() (line 304 of /backdrop/core/modules/node/node.entity.inc).
```

Here's the section of code that refers to:
```
catch (Exception $e) {
      $transaction->rollback();
      watchdog_exception($this->entityType, $e);
      throw new EntityStorageException($e->getMessage(), (int) $e->getCode(), $e);
    }
```

Could this to be to do with the transaction rollback? I don't see a database query in here for the table field_config.

**Comment by herbdool** [comment]
This is on 1.6.0?

I can't replicate. Created a new taxonomy, added to page content type as a new field and created a new node.

**Comment by jenlampton** [comment]
Hm, I thought I had closed this issue. It turns out it was caused by a contrib module that hadn't been properly updated, and queried that table directly. Sorry for wasting your time!
