### ISSUE TITLE
Twitter Module needs Oauth_common modules

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2526]
Hello Developers,

The Twitter module for Backdrop CMS searches for me for "**Oauth_common**" and I do not find this module on the official website.

Who can help me? I would like to have my last tweets displayed in the sidebar on the blog.

Thanks in advance.

**Comment by Graham-72** [comment]
Hello @AlexL777 

Oauth_common is part of module Oauth at https://github.com/backdrop-contrib/oauth

I must investigate why this is not appearing - probably because of name difference.

I believe there is another way to achieve what you want, by using a widget provided by twitter.com - see https://support.twitter.com/articles/20170071.

**Comment by AlexL777** [comment]
Many Thanks,
A new Twitter application I have now created and wanted to run the cron to load the tweets.

Unfortunately the cron with the Backdrop 1.6.0 does not work with me.

A few more questions! Do I have to set any permissions to display the tweets m layout in the sidebar?

To the layout of the default layout and the homepage I have added the Twitter Block, but it is not yet displayed at https://alexanderliebrecht.de.

How can I solve this problem?

Thanks in advance.

**Comment by AlexL777** [comment]
Ok, I can solve the problem with the module "Elysia Cron".

Now I only have to find out how I can adjust the number of tweets for the sidebar.

The cron and its execution now work well.

How can I determine the tweets.

Thanks in advance.

**Comment by AlexL777** [comment]
Ok, just in the "Views" set the number of tweets.

Sorry, I posted here several times. I wanted to find it myself by the way and have now realized it.

Thanks for your attention and the issue you can close now.

**Comment by Graham-72** [comment]
@AlexL777 I'm glad you have solved your problem. Because you opened this issue I think it is best (and normal practice) that you are the one to close it, but is there a separate issue with cron in Backdrop 1.6.0? I have not experienced this problem.

**Comment by AlexL777** [comment]
I have created a cron issue, and I can not remember the previous backdrop versions of this cron problem.

But ok, I offered you in the issue to check the Cron again.

The tweets in the sidebar are doing well and I dealt today with the "Views" in the backend. So I learn something about it.
