### ISSUE TITLE
Update the screenshot.png for Basis.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2531]
The new screenshot features the full-bleed hero block, the default "Your first post" node instead of the "No content yet" text and keeps @wesruv's text from the old screenshot, ...which for future reference and copy-paste is this:

>Yeah, I like animals better than humans sometimes... Especially dogs. Dogs are the best. Every time you come home, they act like they haven't seen you in a year. And the good thing about dogs... is they got different dogs for different people.

Here's the new screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/2423362/22859922/9a8e6dda-f141-11e6-9d70-a598d9ac0aee.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1790

**Comment by quicksketch** [comment]
Thanks @klonos! Merged https://github.com/backdrop/backdrop/pull/1790 into 1.x for 1.6.1.
