### ISSUE TITLE
Possible noob problem - settings accordions do not open

### ISSUE THREAD

**Issue by KLGates** [backdrop/backdrop-issues#2537]
Hello I am an medium-level site builder in Drupal, looking to get involved with Backdrop. 
This is my first, fresh install, PHP5.6, no error messages, no log messages..
When I go to /admin/structure/types/manage/post, I am unable to open the accordions for "publishing settings" etc. They do not respond to clicking, nothing.
![2lh76lnh19f0gvep-l9svl3og9pzhc0lu4moik9m440](https://cloud.githubusercontent.com/assets/25755415/22905876/f7a61a76-f20f-11e6-8500-d362ff4d5698.png)

**Comment by KLGates** [comment]
Possibly related? Unable to install new modules through the browser interface installation queue. When I attempt this, the install progress bar is stuck at 0%. I am, however, able to install by manually uploading to modules directory.

**Comment by laryn** [comment]
Hi @KLGates! Are you working locally or on a remote webserver? Any error messages in the console?

**Comment by KLGates** [comment]
Yes, working on a remote webserver, no error messages in the logs (not sure what you mean by console?)

**Comment by laryn** [comment]
The browser console for Javascript errors. Try this and refresh the page:
http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by KLGates** [comment]
Aha! 

"TypeError: Backdrop.menu_update_parent_list is not a function”

Also GET (long css filename)  [HTTP/1.1 403 Forbidden 0ms]

**Comment by KLGates** [comment]
“Style sheet could not be loaded http://mysitename.com/files.css.cssblahblahblah.css”

**Comment by KLGates** [comment]
OK looks like re-setting the tmp directory location path to /home/myaccountname/tmp in admin/config/media/file-system seems to have done the trick on the accordions.

Still getting the “style sheet could not be laoded” message though.

-kg

**Comment by klonos** [comment]
Hello @KLGates and welcome to Backdrop!

Can you please try the following things (in that order):

1. Clear caches (if not already done so).
2. Temporarily disable CSS aggregation (Configuration -> Development -> Performance -> uncheck "Aggregate and compress CSS files." at the bottom of the page -> save)
3. Clear caches once again.

**Comment by laryn** [comment]
@KLGates I'm guessing maybe a permissions issue is not allowing the CSS aggregation to occur. Try turning off CSS aggregation as a test to see if that is likely.

**Comment by klonos** [comment]
@laryn cross-post 😄

**Comment by KLGates** [comment]
Thank you both, problem solved when I changed the location of the tmp directory to the proper location outside of root and flushed caches.
This may be useful information for install troubleshooting in future documentation.

**Comment by klonos** [comment]
Yay for getting things to work! 👏 ...let us know if you are having any other issue.
