### ISSUE TITLE
Problem updating to Backrop 1.6.1 

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2538]
My updates to 1.6.1 have been going well except for the one site where I have Backdrop installed as a subdomain. For this particular site when I try to run the update script I get this error message

Exception: The <em class="placeholder">./files/config_fa00212d2cdf86b5e53a593559292cb2/active</em> configuration must be completely empty to proceed with installation. in backdrop_install_config_directories() (line 722 of /var/www/vhosts/_mydomain_.com/backdrop._mydomain_.com/core/includes/install.inc).

This may well be specific to my site, or has anyone else had a subdomain problem?

**Comment by klonos** [comment]
Either duplicate or just related to #2262

**Comment by serundeputy** [comment]
@Graham-72 is this a subdomain like: graham.example.com

or 

a sub directory like: example.com/graham

?

**Comment by Graham-72** [comment]
@serundeputy It is a subdomain like graham.example.com that has given me this problem.

**Comment by serundeputy** [comment]
Thanks @Graham-72 

I could not reproduce.  So, there must be something different in our steps and/or configuration.

Here is what I did.

  * On local `cd BACKDROP_ROOT`
  * `drush up backdrop`
    * this downloads latest backdrop
    * makes a backup of current `BACKDROP_ROOT/core` to `~/.drush/$site_name-core-$current_version`
    * moves the core folder from the latest backdrop to `BACKDROP_ROOT/core`
    * Removes the temporary copy of the latest backdrop (that we got the core folder from)
    * Runs update.php

Can you identify anything different about your steps?  Otherwise maybe it is configuration of the server?

Let us know so we can reproduce and get this working.

thanks,
~Geoff

**Comment by Graham-72** [comment]
@serundeputy my steps were much the same as yours so I started detailed checking of progress through the update scripts and found the answer. I had no staging folder in my config directory and it seems this is needed even if required to be empty. I'm not sure how I had lost it, but creating an empty staging folder has solved my problem.

**Comment by jenlampton** [comment]
I believe this is caused by https://github.com/backdrop/backdrop-issues/issues/3846, which I have finally tracked down and fixed.
