### ISSUE TITLE
Vertical tabs still have black left/right border and text on mobile (when they switch to accordion style).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2539]
This must be a remnant of #1718 and my attempt to correct things in #1864:

![backdrop-vtabs-black_on_mobile](https://cloud.githubusercontent.com/assets/2423362/22982502/7560f2e4-f3f3-11e6-90cb-eb2af588f2d8.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1791

**Comment by quicksketch** [comment]
Thanks @klonos! I have noticed this minor detail whenever I give a Backdrop demo and show the responsive tabs, but in practice I rarely see the node form on mobile. Your PR also fixes the display in RTL languages! Nice extra fix there, great job. :+1: 

I merged https://github.com/backdrop/backdrop/pull/1791 into 1.x and 1.6.x.

**Comment by klonos** [comment]
With everything going on in my life lately, I had completely forgotten about this one. Makes me feel good that I finally got this right (after 3 PRs 😛 ) ...the additional fix is in order to compensate for the half-baked previous PRs 😄
