### ISSUE TITLE
Project Installer: Modules "remembered" as disabled/newly-added even if they have already been enabled.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2541]
Steps to reproduce:

1. Go to `/admin/modules/install`.
1. Add a module to the queue and install it.
1. When you reach the "Enable modules" page (`admin/installer/install/enable`) **do not** enable the module and **do not** click any of the "Enable modules" or "Finish without enabling" buttons. Just navigate away.
1. Go to "List modules" (`/admin/modules`).
1. Search for and enable the module you installed in the previous steps.
1. Go to `admin/appearance/install`.
1. Add a theme to the queue and install it.
1. When the installation finishes, you get to the "Set themes" page  (`admin/installer/install/theme`) where there is a "Next: enable new modules" button. Click that -> you are back to the the "Enable modules" page (`admin/installer/install/enable`) where the module you have already enabled is shown as disabled.

**Comment by quicksketch** [comment]
Thanks for the PR @daggerhart! This is some minor cleanup to code-style needed, https://github.com/backdrop/backdrop/pull/1881#pullrequestreview-38022486.

@klonos could you give this a spin and see if you can break it? I'm curious if this solution will cover situations where there are multiple projects downloaded (or multiple modules within a single project). As this will only remove items from the list if that exact module has been enabled. Perhaps we should entirely empty the queue of new modules if *any* module has been enabled.

**Comment by daggerhart** [comment]
Minor code cleanup complete. Let me know if the approach, or anything else, needs to change.

**Comment by quicksketch** [comment]
Finally merged https://github.com/backdrop/backdrop/pull/1881 into 1.x and 1.10.x. Thanks @daggerhart!
