### ISSUE TITLE
Notice: Undefined index in _color_rewrite_stylesheet()

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#2542]
I believe this [issue in Drupal 7/8](https://www.drupal.org/node/1236098) is also an issue for Backdrop:

> When new colors choices are added to a theme, they do not appear on the theme settings form. This causes an error notice and user confusion.
>
> The problem happens when using a custom color palette on the theme settings form (/admin/appearance/settings/THEME). As newer versions of a theme add support for more color-izable items, there is currently no way to get the new color fields added into this form. The form is built from the previously saved color_THEME_palette variable. Because that variable array does not contain the new colors, those fields are not added to the form.

It could be a really simple patch: https://www.drupal.org/files/color-newFieldsMissing-jim0.patch

**Comment by hosef** [comment]
I went with a slightly more complicated change than in the original patch because simply merging the arrays would cause new items to show up at the bottom of the list and stay there forever. using a foreach, and overwriting keys puts the existing custom colors in the correct place in the list.

**Comment by quicksketch** [comment]
Thanks @hosef! Merged https://github.com/backdrop/backdrop/pull/2124 into 1.x and 1.9.x.
