### ISSUE TITLE
Add background color and background image to basicolor

### ISSUE THREAD

**Issue by ColumbiaBlooms** [backdrop/backdrop-issues#2544]
Would it be possible to add functionality to the UI for basicolor to allow changing the background color of web pages? As I grow older I find that reading black fonts on white screens very tedious & tiring. If background color could be easily changed through the UI it would make using my site easier for us old folks.

Also, would it be possible to add functionality to optionally use an image as the background?

**Comment by klonos** [comment]
@ColumbiaBlooms wrong issue queue. This one is for core. Can you please copy-paste this into a new issue over at https://github.com/backdrop-contrib/basicolor/issues ?

**Comment by ColumbiaBlooms** [comment]
Done. Sorry I got the wrong queue.

**Comment by klonos** [comment]
No worries 😄
