### ISSUE TITLE
Create a standard "help" element

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2546]
In dozens of places throughout core we have a pattern of creating a "help" element with the following code:

```php
$form['help'] = array(
  '#markup' => '<p>' . t('Help text') . '</p>',
);
```

We should create a standard element so that help text is displayed consistently. e.g.

```php
$form['help'] = array(
  '#type' => 'help',
  '#markup' => t('Help text'),
);
```

This would allow themers to override `theme_help()` if needed, and we could standardize whether a `<p>` tag is added or not.

---

PR https://github.com/backdrop/backdrop/issues/1794

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1794 adds the following:

- Adds a help element as described above, and replaces all the locations where we had added `$form['help']` in a form structure.
- Creates markup such as:
```
<div class="help"><p>The help text.</p></div>
```
- `<p>` tags are automatically added if missing. But allow for them to be present with `#markup` if the help text needs multiple paragraphs of explanation.

**Comment by klonos** [comment]
Seems a simple change to me and it is backwards compatible as in if someone still uses the "old", `#markup` way, things will still work. 👍

**Comment by quicksketch** [comment]
Great thanks for the review @klonos! Merged https://github.com/backdrop/backdrop/issues/1794 into 1.x for 1.7.0.

**Comment by klonos** [comment]
Shouldn't https://api.backdropcms.org/form_api be updated to include this?

**Comment by jenlampton** [comment]
I've updated the Form API docs at https://api.backdropcms.org/form_api. Can someone confirm that #attriubutes will work? I think I got everything else.
