### ISSUE TITLE
Locating page-specific layout HTML

### ISSUE THREAD

**Issue by JAyenGreen** [backdrop/backdrop-issues#2547]
I need to add a div to my page, and have that div be a child of the body, i.e. not a div added to a block that then is generations-removed from the body tag.

I see that hook_page_alter has been removed (congrats...it was ugly), so template.php is not the right place.

I also see that page--my-page.tpl.php is no longer possible. 

I read that the way to go is to create a new layout (done), assign it to the page path (done), and select the format (done...Boxton). That all done, I can't find anything that tells me in which folder I would find or need to add the layout file that is the path-specific version of layout--boxton.tpl.php, in which I can add the markup.

**Comment by Al-Rozhkov** [comment]
You need to modify template.php file in your theme. Add hook_preprocess_layout function if it doesn't exist yet.

```
function YOUR_THEME_preprocess_layout(&$variables) {
  $original = $variables['theme_hook_original'];
  $variables['theme_hook_suggestions'][] = $original . '__' . $variables['layout']->name;
}
```

In your case use `layout--boxton--LAYOUT_MACHINE_NAME.tpl.php` for your layout template file.

**Comment by BWPanda** [comment]
Since this question has been answered and there's been no followup, I'll close this issue.
