### ISSUE TITLE
Unable to remove label on image field on front page view promoted content

### ISSUE THREAD

**Issue by SamStamport** [backdrop/backdrop-issues#2549]
Unchecking create a label for field image in front page view promoted content has no effect. The label is always displayed. Likewise checking the label for body has no effect. The body label is never displayed.

I ported a "simplenews newsletter" content type from my D7 site. The fields/add function showed only simplenews as the content type instead of simplenews newsletter. I exported the configuration for that content type and changed name to simplenews. I then imported that configuration and then clicked content. The content type now reads simplenews instead of simplenews newsletter. This had no effect on the above behavior of the labels.

**Comment by markabur** [comment]
In the view, is the "Show: " setting set to "Content" or "Fields"?

**Comment by ColumbiaBlooms** [comment]
Thanks so much! When I changed from content to fields the problem went away.

How can I learn more about this kind of setting in Views? I know there are lots of videos for Drupal 7 out there, but I don't know if they apply to Backdrop.

**Comment by markabur** [comment]
Great, glad to hear it! 

AFAIK any kind of docs of videos that you find about Views for d7 will apply to Backdrop as well. I don't know of any differences at this time.
