### ISSUE TITLE
Incorrect head_title reported by dpm() in mytheme_preprocess_page()

### ISSUE THREAD

**Issue by markabur** [backdrop/backdrop-issues#2551]
I have a custom layout that is set to hide the page title, and there is no menu entry for the layout. As expected, that leaves the head_title as just the site name, so I went into my theme and created a mytheme_preprocess_page() function so that I can add my page title into the head_title.

Strangely, when I `dpm($vars['head_title'])`, I get "Error 404 - File not found | MySite" rather than just "MySite". 

But -- when page.tpl.php prints `$head_title`, the "Error 404 - File not found" part isn't there anymore so the head_title comes out as just "MySite".

Even more strangely, if I go ahead and change `$vars['head_title']` from within the preprocess function, it *does* change the $head_title in page.tpl.php...

```
function mytheme_preprocess_page(&$vars) {
  dpm($vars['head_title']);
  // Prints "Error 404 - File not found | MySite" in the message area 
  // But $head_title outputs as "MySite" in the title tag in page.tpl.php
  $vars['head_title'] = 'hi';
  // Now $head_title outputs as "hi" in the title tag
}
```

**Comment by klonos** [comment]
Hello @markabur and welcome to the Backdrop CMS issue queue! Incidentally, I just filed #2550 a few minutes before you filed this issue, and then added a comment to it about the same time as you filed this. That issue is a follow-up of #2209, where I made a few changes to the logic that `$head_title` is constructed in order to have more sanity in the head <title> during the installation phase. You can see the changes that got committed [here](https://github.com/backdrop/backdrop/pull/1731/files).

**Comment by klonos** [comment]
>Strangely, when I `dpm($vars['head_title'])`, I get "Error 404 - File not found | MySite" rather than just "MySite". 

Are you saying that you are seeing this behavior now (after Backdrop 1.6.0) and that it worked properly before (with 1.5.x)?

**Comment by klonos** [comment]
...with the new logic in place, the "MySite" part is `$site_name` and what comes before that is whatever `backdrop_get_title()` spits. Both of these together comprise the `$head_title`. So `$head_title` = `backdrop_get_title()` + `$site_name` + `$site_slogan` (if there is one) and all these parts are separated by a `|`. At least that was the intention.

If the intention is to have the head `<title>` showing only the site name for a specific page in your theme, then I believe what you should be using is [`backdrop_set_title()`](https://api.backdropcms.org/api/backdrop/core!includes!bootstrap.inc/function/backdrop_set_title/1). I could be wrong though and this might have been working before. Can you please try that and let us know?

**Comment by markabur** [comment]
Thanks... I don't know about 1.5 as I've only used 1.6. 

I am also seeing that `arg()` is incorrect in `mytheme_preprocess_page()` -- it gives me the node/nid of my 404 page rather than the path of the custom layout. Expected result would be "my-page" for `arg(0)` and nothing for `arg(1)`.

```
function mytheme_preprocess_page(&$vars) {
  dpm(arg(0)); //=> node
  dpm(arg(1)); //=> 81
}
```

**Comment by klonos** [comment]
I'll have to check all that with both 1.5 and 1.6, but don't have time now. Will get back to you soon as I can (unless someone else gets to it before me).

**Comment by markabur** [comment]
Actually it seems to be a problem with `dpm()`?

```
function mytheme_preprocess_page(&$vars) {
  // dpm() says that arg(0) is "node" for my custom "buy-online" layout:
  dpm(arg(0)); //=> prints "node" in the message area
  
  // But this works:
  if (arg(0) == 'buy-online') {
    $vars['head_title'] = 'Buy Online | ' . check_plain($vars['head_title_array']['name']);
  }
  
  // In fact, print_r() is correct while dpm() is not:
  print_r(arg(0)); //=> prints "buy-online" at the top of the page
}
```

**Comment by markabur** [comment]
> If the intention is to have the head <title> showing only the site name for a specific page in your theme, then I believe what you should be using is backdrop_set_title(). 

I'm looking for the opposite. When there is a custom layout and the page title is hidden, Backdrop only shows the site name in the head, which makes sense -- but I want the title to be visible in the head even though it is hidden on the page. 

Maybe the best way to accomplish this is to just go ahead and add a menu entry for the layout, but then go in and disable it. That works just fine, with no code necessary. However, there is still a bug related to dpm() within a preprocess_page function.

Note that *setting* the title from within a preprocess_page function works just fine whether I assign the variable directly or use `backdrop_set_title()`. The bug is when trying to use dpm() to display the current title, or the current page args, etc.

**Comment by klonos** [comment]
Hmm, glad you have figured a workaround @markabur 👍 ...can you please keep this issue open until I test things out myself and verify your findings about `arg(0)` and `dpm()`?

**Comment by markabur** [comment]
Thanks, this was related to a broken image in the css for my custom theme. The file was generating a 404 behind the scenes.
