### ISSUE TITLE
[UX] Basis: Improve styling of responsive dropdown on smaller screens

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2553]
PR by @olafgrabienski: https://github.com/backdrop/backdrop/pull/1825

---

This is a follow-up of #2370:

> @BWPanda: In a dropdown menu that responds to smaller screens/devices, when you have a parent link that you want to click on you have to essentially double-click on it - once to expand the child menu, and then again to navigate to the parent link's URL. At the same time (when clicking the parent link), the child menu disappears, so it appears to be that clicking the parent link the second time simply closes the child menu, that is until the page reloads and you're taken to the parent's URL.

> @klonos: With the +/- signs, I think that we should make them more prominent if they are set to handle the expanding/collapsing of the menu (different shade of background color perhaps?).

> @olafgrabienski: Interestingly, the +/- signs are already set to handle the expanding/collapsing of a child menu.

I suggested the following changes in the mentioned issue:

- Make the parent link link only to it's URL, and leave the opening/closing of the child menu to the +/- sign on the right.
- Style the +/- signs more prominent (as an example see screenshot in @klonos' comment above).
- Additional styling: indent the child menus via CSS.

After testing the styling improvements, I'd say the first change isn't necessary. The better styling makes quite clear how to use the links and the +/- signs. See a comparison in the next comment.

**Comment by olafgrabienski** [comment]
**Current styling (1.6):**

![screen-backdrop-dropdown-current](https://cloud.githubusercontent.com/assets/14188307/23143435/bd300656-f7c1-11e6-99d3-1146f5cb9cf7.png)

**Proposed styling:**

![screen-backdrop-dropdown-new](https://cloud.githubusercontent.com/assets/14188307/23143442/c585b33c-f7c1-11e6-8820-3d675c07e31f.png)

To get a good overall result, I changed four things:

- styled the +/- signs more prominent
- indented the child menus via CSS
- added borders to all menu items
- removed padding of header inner
- styled the toggle link "Menu" gray instead of white

**Comment by olafgrabienski** [comment]
@BWPanda , @klonos - what do you think of the proposal?

@wesruv - I could make a PR with the changes (it's all in *Basis*) but I guess my CSS isn't perfect. Are you interested to write the CSS by yourself?

**Comment by BWPanda** [comment]
I like! I'll let others discuss and finalise the nitty-gritty details (like colours, padding, etc.), but I like the general concept and direction :+1:

**Comment by klonos** [comment]
I like the general direction as well. I'll leave the details on the css etc to @wesruv (although I know he's busy with other commitments currently). Just wanted to say 👍 as well.

**Comment by wesruv** [comment]
Looks nice! Is there a PR or a place where I can check this code out locally?

**Comment by olafgrabienski** [comment]
@wesruv No PR yet but I could make one tomorrow... Or I just post the changes here which is easier for me, and you get the idea as well.

**Comment by olafgrabienski** [comment]
@wesruv I've made a PR to improve the dropdown on smaller screens: https://github.com/backdrop/backdrop/pull/1825

To test on the sandbox website, have a look at the "About" section which has some sub items.

The CSS isn't perfect, but you'll get the direction. Feel free to to or to suggest some finetuning.

**Comment by olafgrabienski** [comment]
Added "status - has pull request" (forgot it when I created the PR 17 days ago!). Hoping on reviews.

**Comment by olafgrabienski** [comment]
^ actually not sure if the status is correct. @klonos What's the difference between "pr - needs review" and "status - has pull request"?

**Comment by Dinornis** [comment]
Well done @olafgrabienski , I just tested your PR and like to changes.  Will let someone else review the CSS code.

I think your labels for this issue are correct, the `pr - needs review` compliments the `status - has pull request` by indicating that the PR needs testing and code review.

**Comment by klonos** [comment]
> ^ actually not sure if the status is correct. @klonos What's the difference between "pr - needs review" and "status - has pull request"?

You need both tags when you file a PR and is ready for review. After a review, someone could set it to "pr -needs work", but still the "status - has pull request" remains. I sometimes file PRs with "status - has pull request" & "pr -needs work" when I don't have time to finish it off. I do so in order to not lose any work done so far and then also perhaps I'm stack at some point and someone else might come at a later point and pick up where I left it 😉

**Comment by klonos** [comment]
- I would make the + and - signs larger (#364 btw anybody?? 😄 )
- There's a 1px gap bellow the +/- squares
- There's also a gap to the left of child items that I don't particularly like, but don't have any suggestions for either.
- We need to make sure any styling works in RTL too.

![image](https://cloud.githubusercontent.com/assets/2423362/25366211/873f65ec-29b1-11e7-8b4c-d9631ae07f7f.png)

![image](https://cloud.githubusercontent.com/assets/2423362/25366228/a699a8c6-29b1-11e7-9049-259cd9343fde.png)

**Comment by olafgrabienski** [comment]
@Dinornis @klonos Thanks for your reviews!

@klonos Re 1px gap: which OS and browser did you use?

I'll try to address your points. Well, actually, I'd prefer if Wes could ...

@wesruv would you mind to have a look at the PR? You know Basis so much better! I guess I could get it working *somehow* but probably without respecting the styling concept of the theme very well.

**Comment by Dinornis** [comment]
The gap is also visible in OSX Firefox.

**Comment by klonos** [comment]
@olafgrabienski yep, sorry I forgot to mention... I'm on Windows x64 using latest firefox nightly x64 (55.0a1 at the time of writing this).

**Comment by olafgrabienski** [comment]
@klonos @Dinornis I've updated the PR and have adressed the issues. Tested it with Chrome dev tools and on an iPhone 5/SE, and I'm quite happy with the results. What do you think about it?

> I would make the + and - signs larger

- Changed the font size (and set the weight to normal).
- Used *en dash* instead of hyphen for the - sign.

> There's a 1px gap bellow the +/- squares

- The gap appeared only on minimum screen width of 544px, that's why I didn't see it. Thanks for pointing it out.
- Should be fixed now.

> a gap to the left of child items that I don't particularly like, but don't have any suggestions for either

- Removed the gap using padding on the links instead the list items, so that the borders are full width again.

> We need to make sure any styling works in RTL too.

- Disclaimer: don't know how to test that exactly
- Even on a vanilla Backdrop 1.6.3 site (without my PR), when I change in `<html>` the  `ltr` class to `rtl` using Chrome dev tools, the menu looks quite broken.
- @klonos Can you check RTL on a site without my PR and make a separate issue if things are broken?

**Comment by olafgrabienski** [comment]
Updated the PR again: Removed unwanted padding for sub-links for desktop layout.

**Comment by Dinornis** [comment]
Very nice, well done Olaf 👍

**Comment by quicksketch** [comment]
The PR in https://github.com/backdrop/backdrop/pull/1825 looks great. I've manually merged it into 1.x with https://github.com/backdrop/backdrop/commit/f3027384d876f0dc9fbb04e9f3c728d9d00780ff.

As this may have an impact on styling for existing sites, I've only merged it into 1.x and not 1.6.x. This will be in 1.7.0. Thanks @olafgrabienski! Great work.

**Comment by olafgrabienski** [comment]
@quicksketch Great news, I'm happy to see this committed!

@wesruv As this is a change of *Basis*, feel free to check if my changes fit your theming concept.

> this may have an impact on styling for existing sites, I've only merged it into 1.x and not 1.6.x.

Good point, I agree! That said, wouldn't the changes also have an impact for sites when updated to 1.7.x, and should we mention that in the release notes?

**Comment by BWPanda** [comment]
Re-worded title to make it clear this change was only for Basis theme...

**Comment by klonos** [comment]
> We need to make sure any styling works in RTL too.

#4070 😉
