### ISSUE TITLE
Cannot invoke entity hooks if "entity class" key is not defined

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2558]
In porting entity based modules in contrib, we've repeatedly faced an annoying exception from Filter module: `Recoverable fatal error: Argument 1 passed to filter_entity_insert() must implement interface EntityInterface, instance of stdClass given in filter_entity_insert()`. This so far with porting Profile, Feeds, Rules, and latest Flag module. I've figured out why at last and want to document it here.

The error is because of the fact that `filter_entity_insert(EntityInterface $entity)` requires an `Entity` object.

Prior to the addition of `filter_entity_insert()` (in the CKEditor commit) you could define an entity in `hook_entity_info()`; you didnt need to extend `Entity` for it, and when creating a new instance of this new Entity you could simply do `$stub_entity = (object) $values`, and even invoke `hook_entity_insert()` on this stub object. But in Backdrop if you try this, when the `hook_entity_insert()` hooks fire off, `filter_entity_insert()` exceptions because it only wants an Entity (implementing `EntityInterface`). 

So now, in Backdrop, to create an entity, you need to always do `entity_create('my_entity', $values)`, or you cannot invoke the `hook_entity_insert()` or other `hook_entity_whatever()` hooks. 

And `my_entity` here must extend `Entity`.

Furthermore if you intend to save values in your entity, `EntityDatabaseStorageController::save()` also invokes `hook_entity_insert()`.

So in Backdrop to avoid issues you really must create a class for your entity, and define it in "entity class".

Or extend the `EntityDatabaseStorageController` class and delete all the `hook_entity_whatever()` invokations (we did that with Rules I believe) which isnt ideal.

Finally, note that in Entity API, you could simply use `Entity` as your "entity class"; not so in Backdrop because Entity class is abstract and `EntityDatabaseStorageController::create()` exceptions when trying to instantiate it.

---
PR by @alexfinnarn: https://github.com/backdrop/backdrop/pull/2253

**Comment by Graham-72** [comment]
@docwilmot very interesting, thanks for documenting this. Is it perhaps the reason why the Entity Example would not work for me https://github.com/backdrop-contrib/examples/issues/7? And why some things that worked in early releases of Backdrop (pre CKEditor) will no longer work?

**Comment by docwilmot** [comment]
@Graham-72 exactly!

Note that the `entity_example_entity_info()` doesnt define an `entity class`; note also that the controller function creates a new `entity_example_basic` entity by 
```
public function create() {
    $entity = new stdClass();
    ...
    return $entity;
  }
```

Which is not an actual `Entity`.

And the controller `save()` and `deleteMultiple()` functions call `hook_entity_insert()` and delete functions, passing this fake entity, leading to the exception.

So to fix this error, we either:
- create a `class EntityExampleBasic extends Entity` and add this as the `entity class`
- remove all `hook_entity_whatever()` invocations from `EntityExampleBasicControllerInterface` (not the right fix).

**Comment by docwilmot** [comment]
I'm marking this as a bug and assigning for review because it needs either documentation or some fixing since it will affect the majority of contrib implementing Entity API.

**Comment by serundeputy** [comment]
@docwilmot thanks for the detailed report!

My inclination is the second solution you outlined.

> create a class EntityExampleBasic extends Entity and add this as the entity class

@quicksketch do you have an opinion?

**Comment by serundeputy** [comment]
oh @docwilmot but this:

> create a class EntityExampleBasic extends Entity and add this as the entity class

you are saying is a fix for `entity_example` module not in general right?

hmm.

**Comment by serundeputy** [comment]
@docwilmot you are right on the nose with this.  If you de-abstract the `Entity` class:

<details>

```php
diff --git a/core/modules/entity/entity.class.inc b/core/modules/entity/entity.class.inc
index 3d6a59e26..db27a828b 100755
--- a/core/modules/entity/entity.class.inc
+++ b/core/modules/entity/entity.class.inc
@@ -106,7 +106,7 @@ interface EntityInterface {
 /**
  * Defines a base entity class.
  */
-abstract class Entity extends stdClass implements EntityInterface {
+class Entity extends stdClass implements EntityInterface {
   /**
    * Constructs a new entity object.
    */
@@ -126,6 +126,19 @@ abstract class Entity extends stdClass implements EntityInterface {
     return !empty($this->is_new) || !$this->id();
   }

+  public function id() {
+    return 'blah';
+  }
+  public function entityType() {
+    return 'node';
+  }
+  public function label() {
+    return 'lable';
+  }
+  public function uri() {
+    return 'da uri';
+  }
+
   /**
    * Implements EntityInterface::bundle().
    *
```
</details>

You can then instantiate in the `entity_example` module 

<details>

```php
diff --git a/entity_example/entity_example.inc b/entity_example/entity_example.inc
index 72ab23a..514f255 100644
--- a/entity_example/entity_example.inc
+++ b/entity_example/entity_example.inc
@@ -50,12 +50,12 @@ class EntityExampleBasicController
    * Create and return a new entity_example_basic entity.
    */
   public function create() {
-    $entity = new stdClass();
-    $entity->type = 'entity_example_basic';
-    $entity->basic_id = 0;
-    $entity->bundle_type = 'first_example_bundle';
-    $entity->item_description = '';
-    return $entity;
+    //$entity = new stdClass();
+    $entity['type'] = 'entity_example_basic';
+    $entity['basic_id'] = 0;
+    $entity['bundle_type'] = 'first_example_bundle';
+    $entity['item_description'] = '';
+    return new Entity($entity);
   }

   /**
@@ -137,4 +137,3 @@ class EntityExampleBasicController
```
</details>

and thins work™ ... not necessarily a solution, but I think confirms what you are saying.

So, we need to document it.  I think this means that modules like rules, entity_example etc need to define `RulesEntity extends Entity` etc and instantiate those.

**Comment by quicksketch** [comment]
> I think this means that modules like rules, entity_example etc need to define RulesEntity extends Entity etc and instantiate those.

Agreed with everything you guys have concluded. The "right" solution is extending the `Entity` class every time you want to make a new type of entity. You cannot directly use the `Entity` class and that is intentional, as we can't provide reasonable defaults for something like `label()` or `uri()`, these things all differ and that is why you must extend the base class and define them explicitly.

**Comment by quicksketch** [comment]
So as far as core is concerned this is a documentation issue:

- Document `entity class` in `hook_entity_info()` and specify it is required.
- Update the example for `node` in `hook_entity_info()`, right now it doesn't include the line
```
      'entity class' => 'Node',
```
   which exists in the actual implementation.

**Comment by jenlampton** [comment]
This seems like an important bug, so moving to 1.7.1

**Comment by robertgarrigos** [comment]
There is something else I believe it needs to get documented as well or maybe it is documented somewhere else but I cannot find it: when you add
```
'entity class' => 'YourEntityClass',
```
in you ```hook_entity_info``` and create the corresponding class you cannot use the example class used in the [entity_example module](https://github.com/backdrop-contrib/examples/blob/1.x-1.x/entity_example/entity_example.inc), with empty functions. That's what I did in ubercart and I was having problems with updating an entity because ```public function id()```returns nothing. I had to add ```return isset($this->nid) ? $this->nid : NULL;``` otherwise ```Entity::isNew()```returns always TRUE. Is that correct? Is there anything else I should take into account when creating my own entity class?

**Comment by docwilmot** [comment]
Youre right. We should have better exmples.
I cant think of anything else you would need though.

**Comment by btopro** [comment]
Spent the night running through these threads and have been able to port a D7 entity over to Backdrop. Perhaps it's a better example or could at least be pointed to in the docs / have the example updated to be cleaner and more realistic (plurals removed in some spots as simple example): https://github.com/backdrop-contrib/webcomponents/blob/1.x-1.x/includes/webcomponents.entity.inc

**Comment by jenlampton** [comment]
I'm removing the milestone from this issue since it looks like the to-do item here is to update the  example module (in contrib?). If we need to do something to core too, let's note that here (and add a milestone back, if necessary).

**Comment by alexfinnarn** [comment]
Going back to...

> Document entity class in hook_entity_info() and specify it is required.
> Update the example for node in hook_entity_info(), right now it doesn't include the line

https://api.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.api.php/function/hook_entity_info/1

Looks like this still needs to be done. I stared at `hook_entity_info` for a while before I found this issue. Anything else to add to the docs @quicksketch?

I just copied @btopro and his example and it got me through my errors. Thanks, sir!

**Comment by docwilmot** [comment]
in the spirit of the recent thursday meeting where agreed not to bomb @quicksketch with everything, and since this is documentation, and i'm the docs guy, I'll jump in. would you be able to do a PR @alexfinnarn?

**Comment by alexfinnarn** [comment]
@docwilmot I made a PR, but I don't really know what verbiage to use for the description of "entity class". Feel free to change that to whatever makes sense.

**Comment by docwilmot** [comment]
D7 Entity API has `A class the controller will use for instantiating entities. It is suggested to make use of the provided "Entity" class or to extend it.`

Perhaps combine the two: `A class the controller will use for instantiating entities. Must extend the Entity class or implement EntityInterface.`

**Comment by alexfinnarn** [comment]
sounds good. I made that change in the PR.

**Comment by docwilmot** [comment]
I've marked it RTBC. Was initially wondering if just documenting this key is enough and if we should say that it is required, but I notice that none of the other keys are marked as either required or optional.

**Comment by klonos** [comment]
I have added a comment in the PR for consideration re language being used from a non-English speaker PoV. Please bear in mind that my English is not 100% all the time. Just my 2c.

**Comment by oadaeh** [comment]
It looks like I may have created a slightly duplicate issue to this one: #2997 
I didn't quite get around to doing anything more with it than filing it.

**Comment by quicksketch** [comment]
Thanks everyone! I noticed this just yesterday, so I'm glad we have this now documented in hook_entity_info()! Merged https://github.com/backdrop/backdrop/pull/2253 into 1.x and 1.10.x.
