### ISSUE TITLE
Link for "Add URL Redirect" not working

### ISSUE THREAD

**Issue by markabur** [backdrop/backdrop-issues#2561]
In 1.6.1, if I go to /admin/config/urls/redirect/404 and click one of the "Add URL Redirect" links, I get redirected right back to /admin/config/urls/redirect/404 instead than going to the add-redirect form. The problem seems to be that the generated link uses /search/ when it should use /urls/. Here's an example non-working link:

http://badr.localhost/admin/config/search/redirect/add/?source=sites/default/files&destination=admin/config/urls/redirect/404

If I manually change the URL to have "urls" instead of "search", it works:

http://badr.localhost/admin/config/urls/redirect/add/?source=sites/default/files&destination=admin/config/urls/redirect/404

**Comment by olafgrabienski** [comment]
I can confirm both the issue and the workaround. Seems the issue has been introduced before 1.6.1, I see the same behaviour on a Backdrop 1.6.0 site.

**Comment by markabur** [comment]
There is a redirect built in to redirect module that does take you from  `admin/config/search/redirect/add` to `admin/config/urls/redirect/add` and it works just fine with the bare url, but when there's a destination in the query string as above, that takes precedence (see `backdrop_goto()`), so we end up back at `admin/config/urls/redirect/404` instead.

**Comment by klonos** [comment]
@markabur I was looking at the very same thing right now. Are you working on a PR?

**Comment by markabur** [comment]
No... feel free. Seems like it would be best to just fix the urls that redirect module generates?

**Comment by klonos** [comment]
Perhaps later tonight when I return from work. Depending on time and energy left 😉

**Comment by klonos** [comment]
You've beaten me to it @markabur. I guess we missed redirect.module when implementing #635.

...tested adding a 404 redirect in the PR sandbox and everything worked 👍 RTBC from me.

**Comment by markabur** [comment]
Super, thanks!

There's also an occurrence of /search/redirect/ in path module. I wonder if that should change now, or separately as its own issue, or later when the backwards-compatibility redirects are deleted?

**Comment by klonos** [comment]
@markabur are you referring to https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.admin.inc#L513 ? ...if yes, then I say just fix it in this PR here, but to be safe wait first to get confirmation from one of the core committers.

**Comment by quicksketch** [comment]
Thanks @markabur! As @klonos has already RTBC'd this patch and it fixes tons of old paths, I've gone ahead and merged it into 1.x and 1.6.x. We could use a follow-up PR for path.module. You can file a new issue or reopen this one if that is preferable.
