### ISSUE TITLE
Update from Drupal 7 and enabling 4-byte UTF-8 support not possible at the same time

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2563]
When I visit update.php while attempting to upgrade from a Drupal 7 site, I see the following"requirements problem" that prevents me from upgrading:
```
Database system 4-byte UTF-8 support	Database tables need conversion
4-byte UTF-8 support enables extended characters to be saved into the database, including emojis, Asian symbols and mathematical symbols. Your server supports this feature but not all tables have been converted to use it. After making a database backup, you should convert existing tables.
```

Since I am unable to run update.php without resolving this critical error, I click the link to `convert existing tables` which of course throws an exception telling me my config files don't exist. These files will only be created AFTER the upgrade from Drupal 7 to backdrop.

```
Error
Error message
Exception: The configuration directory in settings.php is specified as '../config/dev-active', but this directory is either empty or missing crucial files. Check that the $config_directories variable is correct in settings.php. in _backdrop_bootstrap_configuration() (line 2900 of backdrop/core/includes/bootstrap.inc).
The website encountered an unexpected error. Please try again later.
```

So, which needs comes first? the upgrade from D7 or the UTF-8 conversion?

---
PR from @jenlampton at https://github.com/backdrop/backdrop/pull/1799

**Comment by jenlampton** [comment]
Tagging this with the 1.6.2 milestone since it's likely preventing anyone from upgrading from Drupal to Backdrop if they are not already using UTF-8.

**Comment by quicksketch** [comment]
Thanks @jenlampton, this is a great catch and makes sense that we don't want to prevent running update.php, only that we want an error shown on the status page. So this PR looks good to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1799 into 1.x and 1.6.x.
