### ISSUE TITLE
update_get_update_list() comparisons between $compare_version  $schema_version $comparison_schema_version and $last_removed do not take into account a last update N of 6xxx

### ISSUE THREAD

**Issue by YesCT** [backdrop/backdrop-issues#2565]
A) While porting tagadelic,
https://github.com/YesCT/tagadelic

B) when I followed the instructions
https://api.backdropcms.org/converting-modules-from-drupal

to:

1) set the last removed
```
/**
 * Implements hook_update_last_removed().
 */
function tagadelic_update_last_removed() {
  return 6100;
}
```

2) and number the first d7 -> backdrop hook as: `function tagadelic_update_1000()`

See https://github.com/YesCT/tagadelic/commit/fdb056f9569035a3f688ee80e4e794427de1e6c7

C) because tagadelic 7.x-1.x had an update hook in tagadelic.install function `tagadelic_update_6100()`

https://github.com/YesCT/tagadelic/blob/976344a8539157fc4200417fbf8a5b9592092ede/tagadelic.install#L10

D) The d7 -> backdrop hook `tagadelic_update_1000()` is not added to the list of hooks to run in `update_get_update_list()`

--------

E) While debugging this, I could get the hook to appear (without changing core) in the list by: 

1) returning 7100 in tagadelic_update_last_removed()
*and*
2) manually editing the d7 database (then imported before running update.php on the backdrop site)
```
UPDATE `system` SET `schema_version` = '7100' WHERE `system`.`filename` = 'modules/tagadelic/tagadelic.module';
```

**Comment by YesCT** [comment]
Maybe making `update_get_update_list()` also consider 6xxx last removed possibilities will fix this. Note though that that function is ... complicated enough ... already.

**Comment by docwilmot** [comment]
@YesCT we only support upgrades from D7, so no need to support 6xxx. You upgrade D6 to D7 first, then Backdrop.

**Comment by YesCT** [comment]
Thanks for the clarification.

Will test "just" deleting the d6 upgrade and not using the last schema function.. but I think I did that and it prevented the hook from running.
