### ISSUE TITLE
Fatal error when attempting to filter redirect list

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2570]
When you use the form on the top of the redirect list to filter, you get `Error. The website encountered an unexpected error. Please try again later.`.  In the logs there is this message:
```
Recoverable fatal error: Argument 2 passed to backdrop_goto_deprecated() must be of the type array, string given in backdrop_goto_deprecated() (line 782 of backdrop/core/includes/common.inc).
```

**Comment by quicksketch** [comment]
This has been fixed in https://github.com/backdrop/backdrop-issues/issues/2561.
