### ISSUE TITLE
system_settings_form() calls deprecated function drupal_set_message()

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2571]
The system_settings_form() function has a call to `drupal_set_message()` in it. Although this call is wrapped in a check ensuring that the compatibility layer is available and so will never cause an error, there's no reason why we should use `drupal_set_message()` instead of `backdrop_set_message()` to display the warning.

Here's the code in question:
```php
  if (empty($form['#config']) && !settings_get('backdrop_drupal_compatibility')) {
    drupal_set_message(t('Drupal compatibility layer is disabled and this form has not be updated to use Backdrop configuration management.  Changes will not be saved.'), 'warning');
  }
```

---

PR: https://github.com/backdrop/backdrop/pull/1803

**Comment by klonos** [comment]
Just a grammar mistake and a double space in the text that we might as well fix in this PR 😉

**Comment by quicksketch** [comment]
Thanks @klonos! Fixed. Merged into 1.x and 1.6.x.
