### ISSUE TITLE
Fix failing tests due to 1.6.2 release

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2576]
- [x] Administration bar: Menu link access permissions (AdminBarPermissionsTestCase) 114 passes, 3 fails, 0 exceptions, and 30 debug messages | https://github.com/backdrop/backdrop/pull/1806
- [x] Comment: Comment fields (CommentFieldsTest) 118 passes, 0 fails, 30 exceptions, and 30 debug messages
- [x] Field types: Text field (TextFieldTestCase) 218 passes, 0 fails, 134 exceptions, and 66 debug messages
- [x] Filter: Filter format hooks (FilterHooksTestCase) 39 passes, 0 fails, 2 exceptions, and 12 debug messages
- [x] Filter: Security (FilterSecurityTestCase) 33 passes, 0 fails, 4 exceptions, and 11 debug messages
- [x] Filter: Filter administration functionality (FilterAdminTestCase) 237 passes, 0 fails, 61 exceptions, and 78 debug messages
- [x] Filter: Filter format access (FilterFormatAccessTestCase) 313 passes, 0 fails, 27 exceptions, and 99 debug messages
- [x] Layout: Layout Upgrade Test (LayoutUpgradePathTest) 86 passes, 0 fails, 24 exceptions, and 19 debug messages
- [x] Locale: Locale uninstall (FR) (LocaleUninstallFrenchFunctionalTest) 36 passes, 0 fails, 3 exceptions, and 8 debug messages
- [x] Locale: Locale uninstall (EN) (LocaleUninstallFunctionalTest) 36 passes, 0 fails, 3 exceptions, and 8 debug messages
- [x] Module: Module uninstallation (ModuleUninstallTestCase) 3 passes, 0 fails, and 1 exception
- [x] Module: Module API (ModuleUnitTest) 72 passes, 0 fails, 40 exceptions, and 8 debug messages
- [x] Node: Node types (NodeTypeTestCase) 163 passes, 4 fails, 0 exceptions, and 44 debug messages  | https://github.com/backdrop/backdrop/pull/1806
- [x] SimpleTest: SimpleTest functionality (SimpleTestFunctionalTest) 114 passes, 1 fail, 0 exceptions, and 32 debug messages
- [x] System: Authorize API (SystemAuthorizeCase) 22 passes, 0 fails, 55 exceptions, and 5 debug messages
- [x] System: Update functionality (UpdateScriptFunctionalTest) 175 passes, 52 fails, 22 exceptions, and 51 debug messages  | https://github.com/backdrop/backdrop/pull/1806
- [x] Taxonomy: Taxonomy vocabularies (TaxonomyVocabularyUnitTest) 72 passes, 0 fails, 3 exceptions, and 16 debug messages
- [x] Taxonomy: Taxonomy vocabulary interface (TaxonomyVocabularyFunctionalTest) 189 passes, 4 fails, 0 exceptions, and 57 debug messages  | https://github.com/backdrop/backdrop/pull/1806
- [x] Upgrade path: Bare upgrade test (BareUpgradePathTestCase) 26 passes, 0 fails, 15 exceptions, and 9 debug messages
- [x] Upgrade path: Filled upgrade test (FilledUpgradePathTestCase) 25 passes, 0 fails, 10 exceptions, and 9 debug messages
- [x] Upgrade path: Language upgrade test (LanguageUpgradePathTestCase) 58 passes, 0 fails, 5 exceptions, and 15 debug messages
- [x] User: Role assignment (UserRolesAssignmentTestCase) 54 passes, 19 fails, 11 exceptions, and 16 debug messages  | https://github.com/backdrop/backdrop/pull/1806
- [x] Views Plugins: Argument default (ViewsArgumentDefaultTest) 23 passes, 1 fail, 1 exception, and 5 debug messages | https://github.com/backdrop/backdrop/pull/1806
- [x] Views UI: Views UI default views functionality (ViewsUIWizardDefaultViewsTestCase) 53 passes, 1 fail, 0 exceptions, and 18 debug messages

**Comment by jenlampton** [comment]
I found a bug in all these test fails, it was in `Views Plugins: Argument default (ViewsArgumentDefaultTest) 23 passes, 1 fail, 1 exception, and 5 debug messages` Looks like we forgot a `;` on one of our additions of the query tags. Relabeling this issue as a bug report.

**Comment by klonos** [comment]
Just quickly run through the PR diff. Good catch on the missing `;` @jenlampton 👍

**Comment by klonos** [comment]
...too bad that fixing the tests still fails the tests 😄 😞

**Comment by jenlampton** [comment]
there's one left... we're working on it now

**Comment by jenlampton** [comment]
... and we're green! https://github.com/backdrop/backdrop/pull/1806

**Comment by quicksketch** [comment]
I've been reviewing the PR and the premise of "assign roles" is extremely muddled in the implementation. It introduces the concept of "restricted roles", and then treats them special in a number of weird ways:

- If you have "administer users" but not "assign roles", then you can assign *some* roles, but not roles that are "restricted".
- If you have "assign roles", then you can assign all roles (even those that are restricted).

This behavior is extremely confusing to me. If I didn't give a role the "assign roles" permission, why would it be able to assign some, but not all roles? It shouldn't be able to assign any.

If we're trying to imitate the functionality of the D7 module [roleassign](https://www.drupal.org/project/roleassign), which also adds a permission for "assign roles" but then lets you choose which roles that applies to, that should be done as a separate feature addition or contrib module.

**Comment by quicksketch** [comment]
Latest PR looks good, passes all tests and simplifies the implementation substantially. There's just one minor indentation problem noted in the PR.

**Comment by quicksketch** [comment]
Looks great, merged into 1.x and 1.6.x for 1.6.3.
