### ISSUE TITLE
[UX] Permission name 'Administer users' should be `Administer user accounts'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2578]
We missed an instance of `users` that should be `user accounts`. It's the permission name. We can't change the permission string (the key) but we can change the nice friendly label.

----
PR by @Skydragonsz https://github.com/backdrop/backdrop/pull/2061

**Comment by Skydragonsz** [comment]
Hey, this is my first time contributing. 
Hope all goes well.

This is releted to https://github.com/backdrop/backdrop/pull/2061

**Comment by laryn** [comment]
@Skydragonsz I just took a look and I think it needs a little more. You found one place that the label was used but there is another (at least one, maybe more). At that point, this label in the permissions page should be changed:

![screen shot 2018-01-04 at 2 34 27 pm](https://user-images.githubusercontent.com/871421/34583201-7222e5f8-f15c-11e7-950a-abe23affbc9c.jpg)

You should be able to search through the codebase for "Administer users" and see if you find another one (or more).

**Comment by Skydragonsz** [comment]
I changed the labels I missed.

**Comment by laryn** [comment]
Looks good to me! Thanks @Skydragonsz!

![screen shot 2018-01-04 at 4 30 17 pm](https://user-images.githubusercontent.com/871421/34587136-a10ebddc-f16c-11e7-8366-9f478cde4ef3.jpg)

**Comment by serundeputy** [comment]
Nice work @Skydragonsz !  thanks for the help @jenlampton and @laryn !

Merged into `1.x` and `1.8.x` will ship with `1.9.0` and `1.8.2`.

Nice work everyone!
