### ISSUE TITLE
The Basis CSS bug of inside pages

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2586]
CSS bug of inside pages.
Android smartphone - Huawei MediaPad X1 7.0.
![screenshot_2017-03-18-13-19-24 2](https://cloud.githubusercontent.com/assets/13515302/24081329/360e372a-0cba-11e7-8804-b28715fded7b.jpg)

**Comment by BWPanda** [comment]
Going to close due to lack of activity. Reopen if its still a bug in latest version.
