### ISSUE TITLE
Database test's "skipTest" always evaluates to false.

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2587]
The following line always evaluates to `false`:

```php
    $this->skipTest = (bool) $connection_info['default']['driver'] != 'mysql';
```

The `(bool)` cast applies only to `$connection_info['default']['driver']`, which means any non-empty string will be cast to `true`.  To evaluate the statement, the `'mysql'` is implicitly cast to a bool, which makes it `true` as well.  `true != true` is `false`.

---
PR by @jlfranklin: https://github.com/backdrop/backdrop/issues/1812

**Comment by markabur** [comment]
Reviewed, looks good. Not tested as I have no idea how to do that in this situation.

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.6.x. Thank you both @jlfranklin and @markabur!
