### ISSUE TITLE
Reword FRONT PAGE to HOME PAGE

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2589]
/admin/config/system/site-information

Reword;
FRONT PAGE
HOME PAGE

Default front page
Default home page

and

Optionally, specify a relative URL to display as the **front** page. Leave blank to display the default content feed.
Optionally, specify a relative URL to display as the **home** page. Leave blank to display the default content feed.

**Comment by olafgrabienski** [comment]
Related: https://github.com/backdrop/backdrop-issues/issues/2588

**Comment by klonos** [comment]
Closing as a duplicate of #2162 and/or #2588
