### ISSUE TITLE
Site status report. The "enable/disable the display of errors" link does not account for sites with non-clean URLs.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2592]
Noticed this while working on #485. That link is rendered as an absolute, clean URL no matter if clean URLs are enabled on the site or not. This causes clicking on that link to lead to a 404 page in such cases.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1818

**Comment by klonos** [comment]
...I've also fixed some extraneous spaces, converted some other `<a>` tags within description texts to use `l()` and gave the substitution placeholders more meaningful names.

**Comment by olafgrabienski** [comment]
@klonos Sorry, I can't evaluate the code things but I've got another idea to improve the "enable/disable the display of errors" link: make the link that it redirects to the Status report page.

**Comment by klonos** [comment]
@olafgrabienski sorry, I got carried away with https://github.com/backdrop/backdrop/pull/1819 and didn't get a chance to file a PR for this issue here. Will get back to it after "recharge" (😪 again).

Yes, that is a good idea 👍 ...eventually though, I would like certain things like that to be modal dialogs instead of having to redirect to a different page and then back to where the user started from. In this specific case, there could be a confirmation dialog with a "Do you want to enable/disable the display of errors?" message. This way we spare the user a couple of redirects and a few extra clicks.

**Comment by klonos** [comment]
...oh, This issue here *has* a PR. I was referring to #485 ...I'm so tired.

**Comment by olafgrabienski** [comment]
> didn't get a chance to file a PR for this issue here
> ... This issue here *has* a PR.

Yes, I saw it, only can't evaluate it know-how-wise.

> In this specific case, there could be a confirmation dialog with a "Do you want to enable/disable the display of errors?" message.

Yes, also a nice idea. There are however some options on the enable/disable page, so it might make sense to really go there (or to show the options in the modal as well).

**Comment by klonos** [comment]
I've updated the PR as discussed in https://github.com/backdrop/backdrop/pull/1819#issuecomment-288489308 to use `url()` on the path instead of moving the link in the description to an `l()`.

**Comment by quicksketch** [comment]
Nice catch @klonos! The PR at https://github.com/backdrop/backdrop/pull/1818 is simple and fixes an obvious issue (if you're looking for it at least). Merged into 1.x and 1.6.x.
