### ISSUE TITLE
Update path.module for the change of /admin/config/search to /admin/config/urls

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2593]
This is a follow-up from #635 and #2561

---
PR by @markabur: https://github.com/backdrop/backdrop/pull/1817
PR by @klonos: https://github.com/backdrop/backdrop/pull/1819

**Comment by klonos** [comment]
Hey, how about that? ...all tests are green!! ...despite my sleeplessness 😄

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1819 into 1.x and 1.6.x.

**Comment by quicksketch** [comment]
As these two PRs are not in conflict with each other (fixing the same problem in different places), I've also merged https://github.com/backdrop/backdrop/pull/1817 into 1.x and 1.6.x.

Thanks to both @markabur and @klonos for their work on this issue!
