### ISSUE TITLE
Deleting a node should not validate the form.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2594]
STR:

1. Create a new content type or use an existing one.
2. Add at least one piece of content of that type.
3. Edit the content type and add a new field.
4. Make that field required.
5. Find any existing piece of content of that type (created in step 2 above).
6. Edit that content type and hit the "delete" button -> "field is required" error 👎 

What happens here is that the form validation kicks in. It shouldn't, because we are trying to delete the node. The user now has to fill in any required fields before they can be allowed to delete the node.

We should check if this happens with required fields added in other entities too.

---

PR by @daggerhart: https://github.com/backdrop/backdrop/pull/1880
....updated PR by @opi: https://github.com/backdrop/backdrop/pull/2043

**Comment by klonos** [comment]
...deleting nodes from the content list view (`/admin/content`) is not effected by this - only directly trying to delete an individual node via edit -> delete.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1880 looks pretty good. In that implementation, the delete button is changed to a link (though it still retains the styling of a button). We could also solve this problem by using `#validate` and [`#limit_validate_errors`](https://api.backdropcms.org/form_api#limit_validation_errors), which would require less styling adjustments but be less effective since it would still use a POST request and send all the data to the server, even though it would all be ignored.

I don't think we have used the button-styling on links in Backdrop elsewhere. Although it conveniently already exists, I'd like us to do a check for consistency. If we're going to introduce a new UI pattern we should make sure we do it explicitly.

**Comment by daggerhart** [comment]
I searched the core codebase and found 2 similar occurrences:

* `core/modules/config/config.admin.inc` - https://github.com/backdrop/backdrop/blob/1.x/core/modules/config/config.admin.inc#L159
    ```php
    $build['actions']['back'] = array(
      '#type' => 'link',
      '#title' => t('Back to "Synchronize configuration" page.'),
      '#href' => 'admin/config/development/configuration',
      '#attributes' => array('class' => array('button', 'button-secondary', 'form-submit')),
    );
    ```
* `core/modules/update/update.theme.inc` - https://github.com/backdrop/backdrop/blob/1.x/core/modules/update/update.theme.inc#L43
    ```php
    $output .= l(t('Check manually'), 'admin/reports/updates/check', array('attributes' => array('class' => array('button', 'button-secondary')), 'query' => backdrop_get_destination()));
    ```

The first example is pretty much exactly what this PR is doing, with some code-style differences.  The second is similarly using the 'button' and 'button-secondary' classes.

Let me know how you'd like for me to proceed.

**Comment by klonos** [comment]
The PR looks fine to me too. 👍 @daggerhart!

Only think I'd perhaps do is add a comment as to why we are using a link instead of a button. This will help people that use this as an example for their code and also prevent changing it back to a submit button without good reason.

**Comment by daggerhart** [comment]
Updated.

Added a comment about button being a link. Removed "- solved" from PR. And combined the the attributes array into a single line to match the coding style of the similar usage in config.admin.inc

**Comment by quicksketch** [comment]
Thanks @daggerhart! Minor updates requested in the PR. https://github.com/backdrop/backdrop/pull/1880#pullrequestreview-54543955

Thanks for doing that consistency check. I think you're right that we're already using this pattern in other places and should consider it to be acceptable throughout Backdrop.

**Comment by opi** [comment]
New PR with changes requested https://github.com/backdrop/backdrop/pull/2043, asking for review.

**Comment by olafgrabienski** [comment]
@opi I'm not able to evaluate the code but have tested the steps mentioned in the issue description in the PR's sandbox site, and from this perspective the PR looks good: I was able to delete a node with an empty required field.

**Comment by quicksketch** [comment]
I've merged this into 1.x only, as it does delete a function (though that function shouldn't be called outside of its form). This will be in 1.9.0. Thanks @daggerhart and @opi for the PRs! And @klonos and @olafgrabienski for filing and feedback. :+1:
