### ISSUE TITLE
1 user (admin) but indicated 2 users in the bar

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2596]
![screenshot_2017-03-24-17-00-29 2](https://cloud.githubusercontent.com/assets/13515302/24297387/45d42648-10ab-11e7-9f6d-6c53d975a798.jpg)

**Comment by bd0bd** [comment]
Hm, now it is 1 user again.
Do not understand.
No any users related modules were installed.

**Comment by bd0bd** [comment]
Again I have 2 users but I have only 1 - admin.
No any additional users were registered.
I had a look at the data, pls see:
![screenshot_2017-03-25-14-44-37 2](https://cloud.githubusercontent.com/assets/13515302/24321922/c8faab12-1161-11e7-9f58-2e724285b336.jpg)

**Comment by olafgrabienski** [comment]
I'm only guessing, but in the database "User 0" could be the guest / anonymous user.

**Comment by markabur** [comment]
Yes, user 0 is the anonymous user. In the original post I think the admin bar said that there were two users on the site because someone was visiting the site at the same time as Natalya was logged in.

**Comment by BWPanda** [comment]
Closing as answered.
