### ISSUE TITLE
Compatible Drupal themes

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2598]
Is there a possibility to make drupal themes compatible to backdrop?

**Comment by Gormartsen** [comment]
Hi @supermew10 

Backdrop themes work around layout module, while Drupal 7 themes works around blocks pointed to regions defined by theme.

It makes it almost impossible to make it compatible.

But it is not so hard to convert Drupal 7 theme to Backdrop theme.

Please read this articles:
 - https://api.backdropcms.org/converting-themes
 - https://api.backdropcms.org/themes

Also check this theme: https://github.com/backdrop-contrib/bootstrap_lite

You need to understand that backdrop theme is not handling layout of the pages, but style elements.
All layout changes can be applied by Layout managing.
