### ISSUE TITLE
[DX] Remove the crazy from user_page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#260]
I found a code comment today that says 

```
// We need to log back in and out below, and cannot simply grant the
// 'administer users' permission, since user_page() makes your head explode.
```

...and thought to myself "we should fix that." Here are my ideas on how to fix user_page so heads stop exploding.

1) if logged out, /user should simply redirect to /user/login
2) if logged in, /user should simply redirect to /user/%uid

---

PR by @jenlampton (reroll by @quicksketch): https://github.com/backdrop/backdrop/pull/2052

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/752 tested & approved.

**Comment by quicksketch** [comment]
Thanks @opi! This has stuck around in the RTBC queue for a while because the PR was failing tests. I rerolled the PR to fix the tests and filed an updated version at https://github.com/backdrop/backdrop/pull/2052. Other than tests, code is the same.

**Comment by opi** [comment]
*Remove the "good first issue" label, as it is not that simple to review.*

Reviewed, and manually tested. Works fine, thanks @quicksketch ; Why this issue is not milestoned as 1.8.2 ?

**Comment by jenlampton** [comment]
It might be too big a change to go into a bug-fix release?

**Comment by opi** [comment]
agreed. I'm always too hurried ;)

**Comment by serundeputy** [comment]
Thanks @opi @jenlampton and @quicksketch nice teamwork!

Works as expected merged into `1.x` for `1.9.0.`!
