### ISSUE TITLE
Page class in body

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2600]
Basis has class for each node in body -   **page-node-4**   -  and Bartik has no it :-(
Why?

**Comment by Graham-72** [comment]
It is there because I suggested it should be included when Basis was being developed.

Before that I was using Bartik and added the following function to the template.php file in my customised version of Bartik
```
/**
 * Implements hook_preprocess_page()'
 * To add a class 'page-node-N' to each page.
 */
function mysubtheme_preprocess_page(&$variables) {
  $node = menu_get_object();
  if ($node) {
    $variables['classes'][] = 'page-node-' . $node->nid;
  }
}
```

**Comment by bd0bd** [comment]
@Graham-72, you are well done! Good suggestion.

Yes, I have used something like this in Bartik about 2 years ago but have forgot about this construction.
Thank you for reminding!

**Comment by Graham-72** [comment]
>you are well done! Good suggestion

Credit belongs to @quicksketch who told me this in https://github.com/backdrop/backdrop-issues/issues/1011#issuecomment-112641253

**Comment by klonos** [comment]
This has been addressed. Closing.
