### ISSUE TITLE
Update normalize.css to 7.0.0

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2602]
https://github.com/necolas/normalize.css/releases/tag/6.0.0

https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md

> 6.0.0 (March 26, 2017)
> 
> - Remove all opinionated rules
> - Correct document heading comment
> - Update `abbr[title]` support

@quicksketch, https://github.com/backdrop/backdrop-issues/issues/2460#issue-199477386

>Sort of a spin-off from #2311, where we're dealing with inconsistent browser behaviors for abbr[title] CSS. Firefox now adds a dotted underline, while all other browsers use a bottom-border.
> ...

Well, the changelog for 6.0.0 mentions updating `abbr[title]` support.

Related: #2314 

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/1821~~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1957

**Comment by klonos** [comment]
**Warning**: this version of normalize.css removes all "opinionated" rules that seem to have been there for quite some versions back, which seems to be quite a big change. The most notable change is the [removal of margin in all browsers](https://github.com/backdrop/backdrop/pull/1821/files#diff-559705329d9c91b650cecd51754445bbL27). The most obvious effect on Backdrop is that it makes Basis have a white "frame" around it:

![backdrop-issue2602-pr1821](https://cloud.githubusercontent.com/assets/2423362/2442136/b3f31afa-1441-11e7-806b-5571ac0d6a46.png)

In general, I think that we should be more cautious with this update than with the previous update to 5.0.

**Comment by klonos** [comment]
The decision seems to have been made with the reasoning that normalize.css **is not a reset library** and should not be used as such...

...from https://github.com/necolas/normalize.css/issues/664:

> I understand that Normalize isn't a classical CSS Reset but removing those that you call opinionated rules is harsh.
>...
>It's 2017 everybody is setting their box sizing to border-box
>>Nope!
>Leaving the body margin?
>>Why not using a reset for that? I don't think Normalize should be the only styles sheet devs should include as their base.
> removing setting the font family to sans-serif
>>If we look at Normalize as a sheet that addresses differences *between User Agent styles sheets* then it becomes easier for devs to understand **what to expect from it**.

Are we using resets in Drupal/Backdrop?

**Comment by klonos** [comment]
I know that the easy solution here would be to be ignoring any future versions of normalize.css after 6.0.0, but if we do so we risk missing out on the benefits it actually offers ("addresses differences between User Agent styles sheets"), so we will eventually be hitting issues like #2311.

Can we please consider separating roles of libraries (as it seems we should be already doing) and evaluate reset libraries that are considered "standard"? Here's a list of what I've gathered from a quick google search:

http://meyerweb.com/eric/tools/css/reset
http://html5doctor.com/html-5-reset-stylesheet (seems to be based on the previous one)
http://html5reset.org / https://github.com/murtaugh/html5-reset

...others???

**Comment by klonos** [comment]
@wesruv, I think we need your input on this one 😄

**Comment by klonos** [comment]
...I think that the changes involved call for pushing the milestone to 1.7.0

**Comment by klonos** [comment]
FYI: https://github.com/adamgruber/opinionate.css has been created as a compliment to normalize.css. It includes the "opinionated" rules that got removed from 6.0.0 of normalize.css. Including this means that we can keep updating normalize.css from its original source, thus acquiring all new features/fixes, while still not breaking our current styles:

> ## Why?
> 
> [Normalize.css][normalize] is awesome. Unfortunately, as of version 6.0.0, some opinionated rules were removed. This package aims to restore those rules for anyone who wants to keep up with the latest changes but still needs/wants the opinionated rules.
> 
> *You still need to include [normalize.css][normalize] in your project. This only includes the rules that were removed.*
> 
> ## Acknowledgements
> 
> The code for opinionated.css was taken directly from [normalize.css][normalize].
> All credit goes to [Nicolas Gallagher](https://github.com/necolas) and [Jonathan Neal](https://github.com/jonathantneal).

Updated the PR to include this new library 😉

**Comment by klonos** [comment]
...unpostponing and setting back to NR.

**Comment by quicksketch** [comment]
Thanks @klonos. I'm not sure what to do about this one, and I think we should wait it out at least until the dust settles over in https://github.com/necolas/normalize.css/issues/664. As it's only been 10 days so far and I expect more developer feedback back will come in.

The addition of `opinionate.css` seems appropriate, though (IMO) undesirable to add another separate CSS file for such a minor list of changes (especially ones themes are likely to override again). I don't think there are any other options for backwards-compatibility though.

**Comment by klonos** [comment]
Sure. We have some time until 1.7.0 and we can even push it further back to 1.8.0 if it makes people uneasy. I just wanted to file this issue as a to-do list (and why not file a PR now that I can?), so that we don't forget. This is part of my on-going monitoring of 3rd party tools we use in our code. If there's straight-forward fixes and we use really outdated versions, then we should update soon as we can, but some cases (like this one here) might require some waiting 😉 

Having said all that, the devs seem to be very firm about their decision and I don't think they will change their minds and roll back the changes. If we are to update the library at some point anyways, I wouldn't want us to be "surprised" by the bc-breaking changes. And this issue here will serve that purpose.

**Comment by jenlampton** [comment]
As per design call, bumping to 1.8

**Comment by klonos** [comment]
Yeah, I'm glad we brought this up during the last dev meeting and said that it's best to wait until things settle, because there does seem to be some "interesting" updates on the issue: https://github.com/necolas/normalize.css/issues/664#issuecomment-298368496

Also: https://github.com/necolas/normalize.css/pull/673 & https://github.com/necolas/normalize.css/pull/672

**Comment by jenlampton** [comment]
It looks like things may be back to normal with normalize.css. We should update to 7.0.0 and see how that affects Backdrop.

**Comment by jenlampton** [comment]
I pushed a new PR for updating to 7.0.0. As best I can tell everything looks good!

**Comment by quicksketch** [comment]
Yeah, most opinionated styles have returned in normalize 7.0.0.

The only changes include:

- Removing `font-family: sans-serif` on the body tag.
- Removing rules for `outline` on links (affects Firefox).
- Removes rules for margin and padding on fieldsets (which we override already anyway).

Looks like we can pretty easily upgrade to 7.0.0, even though it doesn't do much of anything except revert the changes from 6.0.0.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/1957 looks good to me and has no impact on core themes or any themes that inherit from `system.theme.css`.
