### ISSUE TITLE
Annoyng terrorist report in the Recent log messages

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2603]
Every day, several times per day, I get this in Recent log messages:

Type: file system

**Could not delete temporary file "public://inline-images/file_name.png" during garbage collection**

I have no this file. It was deleted a long time ago.

How to stop this annoyng garbage terrorist report?

Thank you!

**Comment by daggerhart** [comment]
Just a guess, but that error log is probably happening when cron runs, and you have a row in your file_managed db table that is pointing to a missing file.

The easiest way to solve it would probably be to put some dummy image in that path and let cron delete it. Chances are you would need to put the image here: `/files/inline-images/file_name.png`, but it depends on how you have the file system setup.

If you are comfortable executing a database query, I suspect you can solve your problem with something like this:

`DELETE FROM file_managed WHERE uri="public://inline-images/file_name.png" AND status = 0;`

**Comment by bd0bd** [comment]
Directly in a DB is better. Via phpMyAdmin.
Thank you!

**Comment by olafgrabienski** [comment]
Related: #2052
