### ISSUE TITLE
[UX] Why is there still a block IP addresses permission?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2609]
Didn't we remove this feature?

**Comment by klonos** [comment]
Yep, I think we did. The permission must be a left-over.

**Comment by Dinornis** [comment]
Duplicate of #1394 ?
Blocked IP table removed in #35
Feature request at #1878

**Comment by jenlampton** [comment]
yep, thank you!

**Comment by jenlampton** [comment]
change record added: https://api.backdropcms.org/change-records/ip-address-blocking-removed-from-core
