### ISSUE TITLE
Add missing languages to core/includes/standard.inc

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2610]
Compared to the list of Drupal core .po files which are available on https://localize.drupal.org/download, the language list in Backdrop's `core/includes/standard.inc` is missing eight languages:

- fy (Frisian, Western)
- km (Khmer / Cambodian)
- ms (Bahasa Malaysia)
- os (Ossetian)
- prs (Afghanistan Persian)
- ps (Pashto)
- ta (Tamil)
- ~~tvy~~ tyv (Tuvan), **edit:** corrected typo

We should add the mentioned languages to Backdrop.

---

PR https://github.com/backdrop/backdrop/pull/2067

**Comment by olafgrabienski** [comment]
To add the languages, we need the language code, the english name of the language, and (optional?) the local name of the language.

Example: `'fy' => array('Frisian', 'Frysk'),`

From Drupal's `iso.inc` we know that information for six out of eight missing languages:

```
'fy' => array('Frisian', 'Frysk'),
'km' => array('Cambodian'),
'ms' => array('Malay', 'Bahasa Melayu'),
'os' => array('Ossetian'),
'ps' => array('Pashto', /* Left-to-right marker "‭" */ 'پښتو', LANGUAGE_RTL),
'ta' => array('Tamil', 'தமிழ்'),
```

*prs (Afghanistan Persian)* and *tvy (Tuvan)* are missing not only in Backdrop's but also in Drupal's `.inc` file.

**Comment by serundeputy** [comment]
@quicksketch @jenlampton Is there any harm in adding these additional languages to the array?

**Comment by jenlampton** [comment]
I don't think so. @quicksketch ?

**Comment by quicksketch** [comment]
Looks like we already had `'ta' => array('Tamil', 'தமிழ்'),`. I've made a PR for the other 7 languages at backdrop/backdrop#2067.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/2067 into 1.x and 1.8.x. Thanks @olafgrabienski!
