### ISSUE TITLE
CKEditor - Correct faulty and chopped off HTML

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2613]
I need my original HTML. I have created new editor but anyway it  is formating my nice beautiful and correct html in its own  format/way.

Correct faulty and chopped off HTML - does not work.

![screenshot_2017-04-03-22-16-33 2](https://cloud.githubusercontent.com/assets/13515302/24626949/b1184462-18bb-11e7-83c9-1cf944658481.jpg)

**Comment by Graham-72** [comment]
Are you saying that it is modifying your HTML even though you have no filters enabled (as in your screenshot)?

**Comment by bd0bd** [comment]
Yes! It is modifying my and your HTML even though we have no filters enabled in BD 1.6.3.

**Comment by Graham-72** [comment]
It would help if you could give an example of code that is being altered please. Is it just code formatting or is it more significant?

**Comment by bd0bd** [comment]
For example I need a list be inline:

    <ul>
    <li></li><li></li><li></li>
    </ul>

But it changes to its own way:

    <ul>
    <li></li>
    <li></li>
    <li></li>
    </ul>

Sample 2

    <li>
                    <a href="a.html">
                        <img src="">
                        <p>Name</p>
                    </a>
    </li>

changes to

    <li>
                    <a href="a.html">
                        <img src="">
                    </a>
                    <p>
                        <a href="a.html">Name</a>
                    </p>
    </li>

**Comment by laryn** [comment]
Just checking -- do you need CK Editor on this text format at all? Otherwise remove CK Editor from this text format (set "Text editor" = "None"), and call the text format "HTML Code" or something along those lines.

**Comment by bd0bd** [comment]
Yes, it works.
An alternative option for my case.

But anyway we need to fix the problems with filters, right?

**Comment by Graham-72** [comment]
@bd0bd I did a search for 'ckeditor html correction' and found a great deal of discussion. It seems this is an issue about the way CKEditor behaves, and not specific to Backdrop filters. A solution that satisifes everyone is difficult or even impossible - see http://ckeditor.com/forums/CKEditor/Editor-changing-html though there may well be something more recent. The recommendation would seem to be that if one wants to retain full control of one's HTML, don't use a WYSIWYG editor. This is not, of course, the answer we as users would like.

**Comment by bd0bd** [comment]
> if one wants to retain full control of one's HTML, don't use a WYSIWYG editor

But what **Correct faulty and chopped off HTML** is for?

**Comment by klonos** [comment]
https://drupal.stackexchange.com/questions/108616/is-it-necessary-to-use-correct-faulty-and-chopped-off-html

**Comment by BWPanda** [comment]
It seems that CKEditor corrects HTML, as does one of Backdrop's filters. Backdrop's filter is needed for when you're not using an Editor, and we can't fix the editor ourselves (have to wait for it to be fixed/addressed upstream), so going to close this.
