### ISSUE TITLE
[UX] Missing titles on Manage display sub-pages 

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2614]
The "manage display" subpages currently have no tabs or even title. Not sure if it is related to https://github.com/backdrop/backdrop-issues/issues/2450

**Main "Manage display" screen with title/tabs:**
<img width="1204" alt="screen shot 2017-04-03 at 2 35 42 pm" src="https://cloud.githubusercontent.com/assets/871421/24627621/25203cf2-187b-11e7-8db1-4d62b8d0a0ca.png">

**After clicking "Manage display" on a view mode:**
<img width="1211" alt="screen shot 2017-04-03 at 2 36 00 pm" src="https://cloud.githubusercontent.com/assets/871421/24627651/412fe564-187b-11e7-9a88-d208248e8c35.png">

PR: https://github.com/backdrop/backdrop/pull/1868

**Comment by olafgrabienski** [comment]
I confirm, seems to happen since 1.6.0: When you click to manage a display, there are no tabs, and there is no page title. I'm not sure if we need tabs on such pages. A page title is definitely missing, without you're quite lost.

Had a look at #2450 but I don't understand if it's related. What do you think @jenlampton ? I also had a look at #315 , didn't find any related comment there, so I guess the missing page title wasn't intended.

**Comment by jenlampton** [comment]
We definitely need something on the page to help people know where they are, but we worked really hard to get rid of those tabs, I'd hate to see them return.  I think a title is a nice easy win and we should start there.

I was also thinking...  Maybe we should enable the last breadcrumb on the admin layout by default. That would give people one more piece of information letting them know where they are. That's probably a separate issue.

**Comment by olafgrabienski** [comment]
To have the page title would indeed be a nice win, and if easy to accomplish even better!

Re last breadcrumb: I like that too, and I guess we have to do some stuff there (see below), so a separate issue makes sense.

---

I just enabled the last breadcrumb on a test site and had a look at the relevant pages.

Manage displays for posts:

- Path: `admin/structure/types/manage/post/display`
- Breadcrumbs: `Home > Administration > Structure > Content types > Page > Page`

Manage teaser display for posts:

- Path: `admin/structure/types/manage/page/display/teaser`
- Breadcrumbs: `Home > Administration > Structure > Content types > Page > Manage displays > (empty)`

In both cases the breadcrumbs aren't too helpful.

**Comment by klonos** [comment]
> I confirm, seems to happen since 1.6.0

Yep, that's when that new UI for managing display modes was introduced (#315). The thing with the missing titles could be a simple oversight, or just that the old UI patters (title and tabs) were not a good fit for the new. There were a lot of back and forths before finalizing on the UI so that it is as less confusing as possible, so somewhere along the way we might have missed things.

**Comment by klonos** [comment]
...and this is what happens when you keep tabs open for a long time before responding. People have already replied 😄

**Comment by klonos** [comment]
@olafgrabienski the second example will fix itself once we get the proper title there (the name of the display). Will have to look into the other one.

**Comment by laryn** [comment]
Agreed, a title and breadcrumb will go a long way towards making this page feel better. 

It's not immediately clear to me why losing the tabs is a benefit but I wasn't following that discussion and trust the decision.

**Comment by wesruv** [comment]
I skimmed #315 and vaguely remember the design issues around the tabs, it feels naked without them right now since manage fields and all of it's sub pages keeps them, it'd seem more consistent to keep them here as well.

Especially since hitting the Save button on a view page doesn't get you back to the display listing (which seems like a fine behavior, but makes it less intuitive to get back).

**Comment by wesruv** [comment]
That said I'm suuuuuper happy this is in core! Go team! I know this was a bear :sweat: 

Jen and everyone who worked on this ++

**Comment by olafgrabienski** [comment]
@Al-Rozhkov Just saw your PR which ensures that there is a title on *Manage display* sub-page. Can't evaluate the code, so I guess we need another reviewer. However the title is there, which is nice! Here's a screenshot of the sub-page for the Teaser.

![screen-backdrop-pr-1868-manage-displays-teaser](https://cloud.githubusercontent.com/assets/14188307/25841397/37ca38c6-34a0-11e7-8339-abcf08045d4f.png)

I guess we should stick with that change and open a separate issue to enable the last breadcrumb on the admin layout by default, everybody agreed?

**Comment by Al-Rozhkov** [comment]
I read closed issues trying to find out why we hate tabs :) Could someone explain it briefly?

**Comment by olafgrabienski** [comment]
I remember some people expressing dissatisfaction about sub-tabs in #2086. The issue was fixed with a small design change but I have the impression that the concept of sub-tabs is still in question on a more general level. That said, I don't think they are so bad.

**Comment by jenlampton** [comment]
I dislike tabs :) Most of my objection is to tabs **on the front-end**: Having a "tab" to "edit" a page is weird and non-intuitive. It's an interface pattern that's unique to Drupal/Backdrop. 

Tabs on the back end don't bother me quite as much as they do the front end, but they are often misused in Drupal/Backdrop and become something people need to study and learn how to use. "Where are the comment settings? Oh, buried on some sub-tab for content types..." it's non-intuitive and creates a less-than ideal user experience.

This isn't to say it's necessarily the back-end tabs that are the problem, if our interfaces naturally lead people through the various tabs (maybe by redirecting on form submit?) there might be a better way to educate people what's done where.

The fewer places people need to "just know" to look in a tab (or sub-tab) the better!

**Comment by Dinornis** [comment]
I confirm that the missing title issue has been fixed, marking as RTBC.
+1 for a separate issue to address the breadcrumbs and the missing tabs.
I don't see anything wrong with the tabs that were there in 1.5.0.  The way it is now seems to break the workflow.

**Comment by olafgrabienski** [comment]
> Having a "tab" to "edit" a page is weird and non-intuitive. It's an interface pattern that's unique to Drupal/Backdrop.

Not sure if it's so unique, see for instance the Github comments:

![screen-github-comment-tabs](https://cloud.githubusercontent.com/assets/14188307/25867691/ad3d9300-34fa-11e7-8c25-8ecc71a538b7.png)

Anyway, talking about the backend, in my perception the sub-tabs at the top of admin pages often help to visualize where I "am". Hm, should write that perhaps in the upcoming separate issue!

**Comment by jenlampton** [comment]
> The way it is now seems to break the workflow.

Well, there was no workflow at all in 1.5. There was no way to get to the next page *except* to click on the secret tabs. You had to know how it worked to be able to use it. Now, for the first time, we actually have a workflow. There's a way to get to the page you need from the page you are already using that does not involve secret tabs.

<img width="2414" alt="screen shot 2017-05-09 at 12 03 54 pm" src="https://cloud.githubusercontent.com/assets/397895/25867882/e198e834-34af-11e7-9e92-20d5e4555f14.png">

This said, I don't see a downside to having both a normal workflow and secret tabs. That would solve the problem for new users (who will use the button) and the old pros (who like the sub-tabs)

**Comment by Dinornis** [comment]
Sorry for not communicating clearly.
I was referring to the fact that the tabs: `LIST TERMS` `CONFIGURE` `MANAGE FIELDS` `MANAGE DISPLAYS` available at `/admin/structure/taxonomy/tags/display` disappear when you arrive at `/admin/structure/taxonomy/tags/display/default`.

**Comment by jenlampton** [comment]
oh, now that sounds like a problem. :/

> Is that was #2450 is about?

No, that's just for adding links into the admin menu.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/1868#pullrequestreview-37727987 is missing a translation call, otherwise looks good.

**Comment by Al-Rozhkov** [comment]
PR updated.

**Comment by Dinornis** [comment]
I don't know if this is related, but I just ran a test Views Taxonomy Relationship test and it shows 1 fail.
**Message:** `FAIL: Identical result set`
**Filename:** `taxonomy_views_handler_relationship_node_term_data.test`
**Function:** `TaxonomyViewsHandlerRelationshipNodeTermDataTest->testViewsHandlerRelationshipNodeTermData()`

**Comment by quicksketch** [comment]
Thanks @Al-Rozhkov! I've merged https://github.com/backdrop/backdrop/pull/1868 into 1.x and 1.7.x. Thanks for fixing that array mapping issue that was causing the title to fail. It doesn't look like the issue @Dinornis mentioned is related (but please file an issue if I'm wrong on that).
