### ISSUE TITLE
CKEditor: allow uploading a file

### ISSUE THREAD

**Issue by jackaponte** [backdrop/backdrop-issues#2619]
Title inspired by issue #1088. :)

That feature request was about images; in this case, I'm seeking a way to enable users to upload other kinds of files (e.g. PDFs, text files, images too) and then link text or images to those files via the WYSIWYG. I'm going to try the [Insert contrib module,](https://github.com/backdrop-contrib/insert) but in Drupal 7 I've been able to upload files or use IMCE "Browse server" functionality via the Link button in the WYSIWYG. That approach would be ideal for my users!

Happy to help with these efforts if there's a good way for me to do so.

**Comment by klonos** [comment]
When I initially saw the title of this issue, my first reaction was "How can files be inserted in a WYSIWYG?" ..."As links to the file" is the answer 😄 Seems like a reasonable request to me, although you can use a file field, set it to render links to the files, and reference the "documents" section on your text. Not the same thing, but a workaround.

**Comment by klonos** [comment]
...I also remember that in d.org issue queues you could upload a file and insert a link to it in the text.

**Comment by jackaponte** [comment]
Thanks for the responses, @klonos! Yup, my users need an easy way to link text or an image to PDFs and other files, within their Body and other HTML-enabled fields. Your suggested workaround probably wouldn't be user-friendly enough for end users, but the Insert module I mentioned earlier is doing well enough for now!

**Comment by Al-Rozhkov** [comment]
#2072 [UX] Allow uploading a file from the link dialog in rich-text editor
Duplicate?

**Comment by jackaponte** [comment]
Ah, I think you're right, @Al-Rozhkov; thank you! This does seem to duplicate #2072. I'll close this issue!
