### ISSUE TITLE
Respect iframe height

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2622]
When you put an iframe with a certain height on a Backdrop site using the _Basis_ theme, the height of the iframe is not respected.

Example: `<iframe height="600" src="http://www.example.com" width="100%"></iframe>`
Result: an actual iframe height of only 150px
Reason: `height: auto;` in `base.css`:

```
iframe, img {
    height: auto;
    max-width: 100%;
}
```

Can we just remove the height rule for iframes from _Basis_, or is there another reasonable default?

---
PR by @wesruv : https://github.com/backdrop/backdrop/pull/1900

**Comment by BWPanda** [comment]
I agree. This is an issue for me at the moment, while building my site with the Basis theme as default. I'll eventually change to a custom theme, but for now it's annoying.

**Comment by olafgrabienski** [comment]
@BWPanda I didn't make a PR so far because I'd like to get feedback about my suggestion to remove (or change) the height rule.

Pinging @wesruv now: What's your opinion regarding the iframe height in Basis?

**Comment by Graham-72** [comment]
I would prefer that this iFrame height rule be removed from Basis. On the two occasions (so far) that I have used an iFrame within a site using Basis I have had to override it in subtheme CSS.

**Comment by olafgrabienski** [comment]
@Graham-72 Thanks for your feedback! I'd prefer the iFrame height rule to be removed as well, but I'm still unsure because I guess there was a reason to introduce it. Any ideas?

**Comment by wesruv** [comment]
Arg, that is annoying.

So the original rule was for images, which shouldn't be distorted so I needed to override the default height. I tacked on iframe because I had iframes breaking outside the limits of their parents, which wasn't ideal.

I hadn't thought of how that'd break `iframe` heights, I only really wanted `iframe`s to respect the width of their parent.

How do you all feel about:
```
img {
    height: auto;
    max-width: 100%;
}

iframe {
    max-width: 100%;
}
```

**Comment by olafgrabienski** [comment]
Looks good to me!

**Comment by wesruv** [comment]
PR Here: https://github.com/backdrop/backdrop/pull/1900

**Comment by olafgrabienski** [comment]
Looks also good!

Test page: http://1900.backdrop.backdrop.qa.backdropcms.org/test-iframes

**Comment by Graham-72** [comment]
👍

**Comment by serundeputy** [comment]
looks good; works good!  thanks everybody!

merged into `1.x` and `1.7.x` will ship with `1.7.2`!
