### ISSUE TITLE
Missing file add.png from Basis

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2623]
add.png is called from basis/css/skin.css but does not exist in basis/images.

---

PR by @laryn: https://github.com/backdrop/backdrop/pull/3020

**Comment by klonos** [comment]
Related: #2224

**Comment by laryn** [comment]
On a test site I saw this in the watchdog log all over the place -- I just made a PR to remove the reference to `add.png` which doesn't seem to exist (or have existed from what I could find).

**Comment by quicksketch** [comment]
Thanks! Perhaps we should add the missing file? But we don't know what that file should be, and we don't seem to have any substantial complaints about the lack of the plus sign on local actions. For now this is a great fix to prevent the 404s. I've merged https://github.com/backdrop/backdrop/pull/3020 into 1.x and 1.14.x.
