### ISSUE TITLE
Can not open images in CKEditor

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2627]
It doesnot work in Android. Nothing opens. Loading forever.
![screenshot_2017-04-08-08-51-21 2](https://cloud.githubusercontent.com/assets/13515302/24826206/ff154568-1c38-11e7-8255-e5e92a6b73e1.jpg)

**Comment by quicksketch** [comment]
Thanks @bd0bd for filing this issue. Could you provide some information about the device you're using? I tried this on my Android phone and I didn't have any problems opening the image dialog or uploading an image.

I tried in both Chrome (57.0) and Firefox (52.0) on Android 5.1.0.

From the looks of things though, Backdrop isn't even opening the image _dialog_, which shouldn't be dependent on any kind of operating system or browser. My guess is that there may be a JS error on the page, but I don't know how to confirm that. If it's a JS-error though, it probably should occur on your desktop as well.

**Comment by bd0bd** [comment]
Chrome and Firefox newest  versions.
Android 4.2
Huawei MediaPad X1 7.0

The same issue happens with the link dialog.

**Comment by bd0bd** [comment]
The same problem on my Windows PC.
May be this is because of my settings (modules etc) of BD 1.6.3?

**Comment by bd0bd** [comment]
Detected!
This and many other troubles happens because of the module - XML sitemap node.
I have had XML sitemap and XML sitemap node activated. If XML sitemap node is deactivated then everything is ok.

**Comment by quicksketch** [comment]
Great, thanks yeah sounds like it may be a JS error on the page that breaks everything (including the dialogs). I wish we could transfer issues between repositories here on GitHub, but it's not possible. Let's close this issue as it's not related to core and you've filed a new issue at https://github.com/backdrop-contrib/xmlsitemap/issues/36.
