### ISSUE TITLE
[DX][UX] Unable to remove or replace the core taxonomy/term node listing

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2629]
On a taxonomy term page, people often want to change the listing of nodes. If you are a fan of layouts, you probably want to do this by building your own view (block display), and plunking it into a layout at `taxonomy/term/%`.

Well, bad news for you! The only way to remove that "existing" list is to remove the "Main page content" block, which is likely to break 500 other things that are depending on `hook_entity_view()`.

And leaving the block there is just as frustrating, as you now have no way to customize that listing, because it is not a view.

**Comment by jenlampton** [comment]
To make matters worse, there's no way to alter out the listing, either. Both `hook_entity_view` and `hook_taxonomy_term_view()` are called when the term, alone, is being rendered. The node listing is haphazardly tacked on after that, with no way to alter the output before it's shoved into the display via 
```php
$build += node_view_multiple($nodes);
```

**Comment by jenlampton** [comment]
I've pushed a PR that adds a `taxonomy_term_page_alter()` so that we can get rid of that nodelist.

**Comment by olafgrabienski** [comment]
I'd like to be able to change taxonomy term pages as well. Could test the PR but don't know what to test exactly. Just build a Views block display and put it into a layout at `taxonomy/term/%`, or is there more?

**Comment by jenlampton** [comment]
Hi @olafgrabienski, the PR just adds a hook, so the only real way to test it would be to add a custom module that used the hook. Mine removed both the node list and the pager. Here's what the code looked like: 
```
/**
 * Implements hook_taxonomy_term_view_alter().
 */
function jeneration_taxonomy_term_page_alter(&$build) {
  unset($build['nodes']);
  unset($build['pager']);
}
```

**Comment by serundeputy** [comment]
Thanks @jenlampton 

Looks good. works good!

Merged into `1.x` and `1.6.x` will ship with `1.7` and `1.6.4`.

**Comment by olafgrabienski** [comment]
> And leaving the block there is just as frustrating, as you now have no way to customize that listing, because it is not a view.

@jenlampton Has there been already a discussion somewhere if Backdrop should deliver taxonomy term pages as a view?

**Comment by klonos** [comment]
@olafgrabienski when searching for remaining tasks to convert core listings to views, #151 is the place to go. From there, you'd find #145 😉

**Comment by jenlampton** [comment]
I've been thinking a lot about https://github.com/backdrop/backdrop-issues/issues/145 while working on this, trying to determine the best way to do that. In Drupal that was converted into a page display, but I don't think that's the right solution for Backdrop. I think it should be a block (and maybe a custom layout?) but done in a way that this, and those things, all work together. I'll add a comment over there with my thoughts :)

**Comment by laryn** [comment]
@olafgrabienski -- as a stopgap (until something is in place in core) you can disable the term listings using https://github.com/backdrop-contrib/disable_term_node_listings and then fill in with your custom views blocks.

**Comment by olafgrabienski** [comment]
@laryn - Belated thanks for mentioning the *Disable Term Content Listings* module. Tested it today, very helpful!
