### ISSUE TITLE
Upload images in CKEditor via Drag and Drop or Clipboard Paste

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2630]
It would be great to be able to copy/paste directly into CKEditor and have it upload the file to the server, respecting the configuration of the text format.

Drupal has an issue for this as well at https://www.drupal.org/node/2061377.

I'm surprised we don't have an issue for this yet. I've added this issue to the meta at #1087.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1828

**Comment by quicksketch** [comment]
I filed a PR for this at https://github.com/backdrop/backdrop/pull/1828.

Some differences compared to the Drupal approach:

- Drupal decided to capture the paste event and use it to open the image dialog. In our version we just paste directly into the editor and then let the user open the dialog later if desired. Drupal did this because they require the Alt text be entered. Backdrop does not require the Alt text.
- In the similar vein, Drupal restricted the upload to one image at a time because of the dialog/alt text requirement.
- We save the file directly using CKEditor's built-in file uploading mechanism. This requires a new server-side callback to handle the saving of the files.

Overall, this is pretty flippin' cool. CKEditor supports both copy/paste as well as drag and drop from the desktop. I like that if you emulate a slow connection (as you can do easily in Chrome), you can upload multiple images in different places within the editor, all while the upload is in progress. 

![ckeditor-upload](https://cloud.githubusercontent.com/assets/100206/24834120/12d51166-1c91-11e7-9253-cebb8cfe4791.gif)

**Comment by docwilmot** [comment]
Pretty Flippin Cool!

**Comment by Al-Rozhkov** [comment]
It works great! Can't wait for 1.7.0 :)

**Comment by serundeputy** [comment]
This is great @quicksketch ; very cool!

I pulled it down to test locally on a mac:

  * I could not drag files into the editor from Desktop or Finder (I could drag from Finder on the sandbox http://1828.backdrop.backdrop.qa.backdropcms.org/)
    * The editor just did not respond in any way
  *  On local I could paste in content from google docs that contained an image, but it is not uploading to the backdrop file system, just putting an image src from google url.
  * I tried pasting in from mac Pages application and that just pastes in the text of the doc ignoring the image(s) on both local and zen qa sandbox.
  * I tried TextEdit as well same result
  * You can copy and paste from internet web pages like freebsd.org, but that is same as google docs serving the images from that website

Are you guys all using the sandbox?  Anybody from windows, mac, linux?

**Comment by Al-Rozhkov** [comment]
I was able to drag files from desktop on windows and copy-paste from Word application. Yes, I'm using sandbox site.

**Comment by quicksketch** [comment]
@serundeputy The behavior you're describing sounds like the code isn't there at all. Copy/paste "works" in Firefox but it pastes the entire image into the body as a base64 encoded string (not a good thing for page size).

CKEditor loads its plugin JS files outside of the Backdrop normal approach, meaning it's not affected by clearing caches. I've found that browsers have a hard time refreshing those files (even shift-reloading). So perhaps try visiting http://backdrop.dev/core/modules/ckeditor/js/plugins/backdropimage/plugin.js directly and check if the expected changes are showing up there.

@Al-Rozhkov I haven't even tried copy/paste from Word. That works!?! That sounds amazing. I'll give it a shot.

One thing I've found a bit strange but not entirely unacceptable: If you set max dimensions in the text format configuration (e.g. 400x400 pixels) and then upload a larger one via copy/paste, the image shows up full size initially until the upload is finished, then it "snaps" down to the resized version.

We could implement this in a way were only a black square placeholder is shown until the file finishes uploading, but personally I think showing the image client-size in the non-resized form has a clear UX advantage in that the user sees the full image in place even before the upload is finished. That and setting a max upload dimension that small is probably uncommon.

**Comment by quicksketch** [comment]
Copy/paste from Word doesn't seem to work right for me it just embeds them base64 encoded (Firefox on Linux). The code seems to find the images and even shows the message "File uploaded successfully.", AND the file shows up under `admin/content/files`, it's just not replaced in the browser it seems.

**Comment by Al-Rozhkov** [comment]
> Copy/paste from Word doesn't seem to work right for me it just embeds them base64 encoded

Word + Chrome. Image is inserted as regular <img> tag and file is uploaded on server. Looks like it browser dependent behaviour.

**Comment by serundeputy** [comment]
@quicksketch

>So perhaps try visiting http://backdrop.dev/core/modules/ckeditor/js/plugins/backdropimage/plugin.js directly and check if the expected changes are showing up there.

the expected code changes are present when visiting this file.

* On chrome `Version 57.0.2987.133 (64-bit)` I get the above described behaviour where nothing happens when dragging in an image from the finder.

* firefox `52.0.2 (64-bit)` I got this error about not being able to move the file:

<img width="1455" alt="screen shot 2017-04-09 at 5 14 31 pm" src="https://cloud.githubusercontent.com/assets/6763671/24841048/c3c4af24-1d48-11e7-823a-f441d12465f1.png">

* Safari reports same as Firefox `10.1 (12603.1.30.0.34)`

🔨 Not sure what is going on.  File permissions?

**Comment by quicksketch** [comment]
Thanks @Al-Rozhkov, confirmed that Chrome works as expected. I've fixed the Firefox implementation so that it functions correctly now as well; it was a problem in my porting from the CKEditor "uploadimage" plugin.

We could potentially take this even further yet. I tried copy/pasting from Google docs and that works, but all `<img>` tags point at an image hosted on Google's servers (so no upload is needed). However if we so wanted, we could copy that image off the remote server and re-upload it to the site. That would be pretty killer. Thoughts?

**Comment by quicksketch** [comment]
> Not sure what is going on. File permissions?

Yeah possibly. Here's the code from `file_save_upload()` where that error is thrown:

```
    form_set_error($form_field_name, t('File upload error. Could not move uploaded file.'));
    watchdog('file', 'Upload error. Could not move uploaded file %file to destination %destination.', array('%file' => $file->filename, '%destination' => $file->uri));
```

So check in Recent Log Entries to see where the file is moving from and to. The most obvious problem would be the destination directory isn't writable. Can you upload a file through the CKEditor image dialog? That should save to the same destination even though the approach is different.

**Comment by serundeputy** [comment]
I think that you must have been right on cache of that file, because now it is working locally on chrome and firefox.

there is  a javascript error on save, but the image does save and display after node save.  here is the chrome console of the js error:

<img width="1427" alt="screen shot 2017-04-09 at 9 05 07 pm" src="https://cloud.githubusercontent.com/assets/6763671/24842637/6ea43198-1d68-11e7-99d1-4be03accb77b.png">

**Comment by Graham-72** [comment]
It is working well for me using Windows 10, with both Firefox and Chrome. Drag and drop from desktop, or copy and paste from folders and applications e.g. Picasa Photo Viewer. 👍 

The only difference I have noticed is that when trying to add an image before the inline-images folder exists you get an error message, whereas with 'normal' insert image Backdrop creates the inline-images folder for you.
![edit page test page](https://cloud.githubusercontent.com/assets/10559274/25071444/170a06e6-22af-11e7-8c3b-4892a615d8c6.png)

**Comment by quicksketch** [comment]
> The only difference I have noticed is that when trying to add an image before the inline-images folder exists you get an error message, whereas with 'normal' insert image Backdrop creates the inline-images folder for you.

Thanks @Graham-72! That might be the missing piece that I had encountered but didn't understand what was happening. This should be trivial to fix, I bet we're just missing a call to `file_prepare_directory()` to create directory.

I'll take another look at the JS console and see if I can reproduce what @serundeputy reported as well.

**Comment by quicksketch** [comment]
I updated the PR at https://github.com/backdrop/backdrop/pull/1828. Indeed we were just missing a `file_prepare_directory()` call. With that fix in place new sites shouldn't have any problem upload a file via copy/paste as their first interaction.

As for the JS error reported by @serundeputy, I do get the same thing _only in Chrome_, but the post does save properly. It looks like this is an issue in CKEditor itself, as reported here: https://dev.ckeditor.com/ticket/16825

So perhaps just an update to CKEditor may fix it.

**Comment by quicksketch** [comment]
> We could potentially take this even further yet. I tried copy/pasting from Google docs and that works, but all `<img>` tags point at an image hosted on Google's servers (so no upload is needed).

I looked into this as well, but it was not in any way trivial. So for now I think this is feature-complete.

**Comment by olafgrabienski** [comment]
Great feature! I tested it in the sandbox on Mac OS X.

Chrome:
- Drag & drop works
- Copy & paste doesn't work. It pasts just the file name.

Firefox:
- Drag & drop works
- Copy & paste doesn't work. Doesn't upload the actual image but a placeholder image called `image.png` which looks like a default Mac preview image.

**Comment by quicksketch** [comment]
> Copy & paste doesn't work. It pasts just the file name.

I tried this out and found the same results as you, but only when copy/pasting _entire files from the Finder_. The copy/paste from clipboard works when an image selection is in the clipboard. e.g. Open an image in Preview.app, then copy. Or select a part of of the image with the select (marquee) tool, then copy. Then paste the image from the clipboard into the editor.

You can also screenshot within MacOS by using Command + Control + Shift + 4. That copies a selection to the clipboard. Then paste into the editor.

I'm not sure copy/paste from the Finder is supported at the OS level. I tried copy/paste from the Finder in Gmail and Google Docs. Neither is supported (matching the same results we get in CKEditor). So it appears that MacOS is incapable of this ability currently. You can still drag and drop, as well as paste images from clipboard. Hopefully Apple will fix this limitation and then our implementation will work in the same way as an image in the clipboard.

**Comment by quicksketch** [comment]
Further update: Copy/paste images directly from Finder into even _local_ applications such as Keynote.app and Pages.app also just past the path the file instead of the entire image. I think that pretty much seals it as direct copy from Finder as being unsupported (or "by design"?) on MacOS.

**Comment by quicksketch** [comment]
Considering the issues noted by @olafgrabienski are not solvable for MacOS, I'm tentatively marking this RTBC. Unless there are other concerns, I'll commit this in two days (Apr 29).

**Comment by Dinornis** [comment]
👍 Thanks @quicksketch , this is awesome!

Your d.o link actually points to Drupal issue where they are working on allowing image style to be selected in the editor's image dialog.  Do we need to open a separate issue for this here or is there one already?  I could not find one other than https://github.com/backdrop/backdrop-issues/issues/2010

**Comment by jenlampton** [comment]
I'm trying to test this, but I'm on MacOS so maybe my results are not related to the code here...  however:

* I took a screenshot of this page
* I opened it in preview
* I hit ctrl-A to select all (which appeared to work)
* I hot ctrl-C to copy
* I created a post on my backdrop site, and in the body field hit Ctrl-V to paste.
* I can see the image inside the ckeditor dialog
* But when I save the post, nothing appears.
* Viewing the source, I see a base64 version of the image.

**Comment by jenlampton** [comment]
edit: an interesting discovery: If I change my input format to FULL HTML then I can see the image I pasted!

**Comment by jenlampton** [comment]
Trying to drag and drop this time (Firefox):

* I take a screenshot (it saves to my desktop)
* I created a post on my backdrop site
* I clicked on the image on my desktop
* I dragged it over the CKEditor area on my post on the backdrop site
* I let go
* nothing happens. 
* The image remains on my desktop, nothing appears in the editor.

For me, this PR does nothing. That said, it also doesn't break anything, so if anyone else can confirm that it does something for them, let's get it in.

**Comment by laryn** [comment]
Strange, I went to the sandbox and did almost the exact same thing and it worked beautifully:

 - log in, begin to create page
 - take screenshot
 - drag screenshot file from desktop to editor window and drop it
 - image uploads successfully into the editor
 - save
 - realize i forgot to add a title
 - add a title
 - save again

http://1828.backdrop.backdrop.qa.backdropcms.org/posts/test

**Comment by jenlampton** [comment]
@laryn yeah, I am testing now from Chrome and I'm having more luck!  Both drag/drop and paste have worked: http://1828.backdrop.backdrop.qa.backdropcms.org/posts/jen-testing-paste-clippy-chrome and http://1828.backdrop.backdrop.qa.backdropcms.org/posts/jen-testing-dragdrop-desktop-chrome

**Comment by jenlampton** [comment]
Whelp, I tested again on FF on the sandbox site, and EVERYTHING seems to be working. I suspect my earlier testing is due to some problem with the branch on my local. 
http://1828.backdrop.backdrop.qa.backdropcms.org/posts/jen-testing-paste-ff
http://1828.backdrop.backdrop.qa.backdropcms.org/posts/jen-testing-dragdrop-ff

**Comment by jenlampton** [comment]
@quicksketch I think this looks good and is ready to merge :)

**Comment by quicksketch** [comment]
Excellent, well with the consensus of all the testers here, I've merged https://github.com/backdrop/backdrop/pull/1828 into 1.x for 1.7.0. Thanks for all the awesome feedback!

**Comment by NguyenQuocTruong14110425** [comment]
![image](https://user-images.githubusercontent.com/22490604/43314048-f497ea60-91bb-11e8-85cf-ebe35b9797cd.png)

Hi everybody! I'm having a problem dragging an image into ckeditor. And I think my problem is due to the trial version.
ps:/ image with format: jpg.

**Comment by klonos** [comment]
Hello @NguyenQuocTruong14110425 I have just tested this functionality in a vanilla Backdrop installation and it works fine for me. A couple of notes:

1. When you say "due to the trial version" are you referring perhaps to usage of [CKfinder](https://ckeditor.com/ckeditor-4/ckfinder/)?

2. I see that the error in the console says `The requested resource type is invalid`, which makes me think that this is perhaps to not explicitly listing the default resource types in your php configuration. More here: https://stackoverflow.com/questions/33215839/unable-to-open-ckfinder-invalid-resource-type

In any case, can you please open a new issue for this? Thanks.
