### ISSUE TITLE
Update CKeditor skin to "Moono-Lisa" or provide a setting to switch skins

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop/backdrop-issues#2631]
I'd like to use new "Moono-Lisa" skin in CKeditor, it has less borders and gradients. It fits much better in Seven admin theme since we don't have any gradients in other components.

![moono-lisa](https://cloud.githubusercontent.com/assets/16973264/24837501/c1e4292a-1d46-11e7-80d6-61d1bf8ae5b0.jpg)

PR: https://github.com/backdrop/backdrop/issues/1843

**Comment by Al-Rozhkov** [comment]
BTW, Wordpress has very similar default skin for WYSIWYG editor.

![wp-dropdown](https://cloud.githubusercontent.com/assets/16973264/24837532/53b51bfc-1d47-11e7-8332-7a1ccf9b58ff.jpg)

**Comment by bd0bd** [comment]
I think it is a right idea.

**Comment by quicksketch** [comment]
> Update CKeditor skin to "Moono-Lisa" or provide a setting to switch skins

I think that switching the skin is a good idea. Providing a setting I'd like to avoid. We considered switching the skin when we last updated CKEditor, but we were after code freeze and wanted to minimize feature changes.

**Comment by klonos** [comment]
Yep, lets just make it match the rest of our UI for now and we can file a follow-up to make it easier (and document how) people can change the theme either in their custom admin theme or when creating a subtheme of Seven.

**Comment by quicksketch** [comment]
Awesome @Al-Rozhkov, thanks for making the PR!

**Comment by quicksketch** [comment]
The PR works perfectly. No issues at all switching the theme and having it work with all of our customizations, including the custom icon for the image and link buttons. Looks much nicer IMO as well.

The only issue I've found is that our admin UI uses a heavily styled design to match the UI of the previous Moono skin.

![image](https://cloud.githubusercontent.com/assets/100206/25463973/b8655638-2aae-11e7-9e21-e9c06749baa5.png)

It doesn't affect the functionality, but the consistency grates on me. Should we require that be updated now? Or make it a follow-up?

**Comment by Al-Rozhkov** [comment]
I think it is better to do that at once. I'm going to update my PR.

**Comment by Al-Rozhkov** [comment]
![ckeditor-toolbar](https://cloud.githubusercontent.com/assets/16973264/25503289/e64a03c6-2baa-11e7-8a28-08457e65b39d.gif)

Just want to show you unfinished work. I like that toolbar groups have borders. This helps to distinguish them from the separators. What do you think? Should we keep borders for groups?

**Comment by olafgrabienski** [comment]
@Al-Rozhkov I like the borders, guess they make it more easy to manage the toolbar buttons.

**Comment by Al-Rozhkov** [comment]
Great! Then go back to needs review. PR updated.

**Comment by docwilmot** [comment]
RTBC
very nice.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1843 into 1.x for 1.7.0.

Woot! Thank you everyone! Great work.
