### ISSUE TITLE
[DX] skin.css in Basis doesn't get output where Wes wants it to be

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#2638]
The title is horrible, I'm not sure how to succinctly describe this. 

Here's the situation that I'm seeing in D7, and I assume it will happen in Backdrop as well, but haven't tried yet.

Have Basis which lists a number of CSS files, `skin.css` is the last one:
```
...
stylesheets[all][] = css/component/hero.css
stylesheets[all][] = css/component/teasers.css
stylesheets[all][] = css/component/comment.css
stylesheets[all][] = css/skin.css
stylesheets[print][] = css/print.css
```

I overrode it in my sub-theme and added a bunch of component CSS files for things specific to my site, again keeping skin.css on the bottom.
```
...
stylesheets[all][] = css/component/tout.css
stylesheets[all][] = css/component/quotes-carousel.css
stylesheets[all][] = css/component/quote.css
stylesheets[all][] = css/component/organizations-list.css
stylesheets[all][] = css/component/news-reference.css
stylesheets[all][] = css/component/social-media-listing.css
stylesheets[all][] = css/skin.css
```
But in the rendered HTML attaching the CSS files skin.css goes where it would have put Basis' skin.css if I hadn't overwritten it, before all of my active theme's CSS (4th from the top of this list):
```
...
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/hero.css?oobc0o");
@import url("http://website.com/sites/all/themes/contrib/basis/css/component/teasers.css?oobc0o");
@import url("http://website.com/sites/all/themes/contrib/basis/css/component/comment.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/skin.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/overrides/colorbox.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/customizeable-section.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/tout.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/quotes-carousel.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/quote.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/organizations-list.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/news-reference.css?oobc0o");
@import url("http://website.com/sites/all/themes/custom/mysubtheme/css/component/social-media-listing.css?oobc0o");
```

**Desired result** would be that it'd go after all of my current theme's CSS because that's where I listed it in my active theme's CSS.

This is a bit of DX issue for how I expect people to use/override Basis, but I'm not sure if anyone else will notice 🤓

**Comment by wesruv** [comment]
This does bring up the question of what behavior you expect when a CSS file is replaced/overridden from an info file. My expectation is that it appears grouped with my current theme's CSS and in the order that they're listed in the info file.

One could argue that it's an override and should be where the file was declared originally, and was probably what was originally intended.

It does break how I expected Basis to work with sub-theming using a SMACSS'ish organization.

**Comment by klonos** [comment]
Hey @wesruv, quick question: what's up with `.../sites/all/themes/contrib/basis/...`? Basis is in core now, so are you using the contrib version of it (prior to getting it into core)? ...old Backdrop installation perhaps?

**Comment by markabur** [comment]
I can confirm that it's happening in Backdrop too. Any CSS file that is overridden by the subtheme will appear in the spot where the orginal file would have appeared, rather than after all the parent css files.

That behavior kind of surprises me too (I haven't created a subtheme in years), but I wonder if it's a good thing? E.g. if the core theme has a reset.css and I override it in a subtheme, wouldn't I still want it to be output before any of the css files in either of the themes?

**Comment by jenlampton** [comment]
@klonos that's from a Drupal 7 site. 

@wesruv can you use `hook_css_alter()` to put them in the order you want? IIRC that's what it's there for.

**Comment by markabur** [comment]
The more I think about it, the more the current behavior makes sense. That way it is the base theme that determines the stylesheet order, and a subtheme can replace individual files here and there without screwing the order up. If the subtheme needs to put a css file at the end it just has to name it different than an existing file.

> Desired result would be that it'd go after all of my current theme's CSS because that's where I listed it in my active theme's CSS.

What about if the subtheme does add some components but doesn't define a replacement skin.css file -- should skin.css still go after all the components (ideally, if possible)?

**Comment by BWPanda** [comment]
Going to close this old issue based on the fact that it seems to be a 'works as designed' and @jenlampton seems to have posted a workaround for those who want different.
