### ISSUE TITLE
(Feature Request - Showcase Page) If there are no example sites, how can new clients become interested?

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop/backdrop-issues#2639]
Sorry, I asked something similar to this before but did multiple searches and couldn't find the thread... but, anyways... I know there is a "Showcase" page on backdrop.org at ( https://backdropcms.org/showcase ) but I see no link to the page from the main menu.  How about creating a "showcase" content type on backdrop.org and letting registered users submit sites?  Or, even on github?  After all... new coders and clients can't get interested if they can't see actual sites built with backdrop.  I just completed a backdrop site ( http://www.JapanTravelPackages.com ) which has multiple content types (a couple with 20-40 fields), a couple views, node referencing (a couple layers deep), etc.  AND, the site flies!

**Comment by Al-Rozhkov** [comment]
@JugglingCoder looks like you already aware of [issue queue especially for backdropcms.org](https://github.com/backdrop-ops/backdropcms.org/issues), because you have commented there :)

This issue queue is for Backdrop core development. I think it is better to continue this topic there and close this issue.

> AND, the site flies!

Congrats! Great site! And I share your feelings about Backdrop. It's awesome :)

**Comment by Graham-72** [comment]
>Backdrop. It's awesome

👍 and it gets better every month. Spread the word! 

Excellent site @JugglingCoder please can you tell us more about the contrib modules you have used?

**Comment by JugglingCoder** [comment]
Other than the "base" mods that come with Backdrop I used these contribs:
IMCE
Node clone
SEO Meta Tags
Google Analytics
Webform
XML sitemap

Plus... a whole lot of pretty complicated custom coding.  I created a "business", "day" and "tour" content type.
A "day" references multiple "business" content types and a "tour" content type reverences multiple "day" content types.  So if you look at a tour you can see how they display. A tour page is not a view... its a lot of custom coding of days loading businesses and tours loading days.  Quite a bit of "calls" going on but loads very fast.

**Comment by Graham-72** [comment]
@JugglingCoder thanks for the information.

>How about creating a "showcase" content type on backdrop.org

Actually this already exists, as 'Website for Showcase'. I believe we are waiting for final styling of the showcase before it goes 'public'. But yes, we need it.

**Comment by klonos** [comment]
@JugglingCoder do you have a user account on backdropcms.org? Can you please create one and then create a showcase for www.JapanTravelPackages.com ?
