### ISSUE TITLE
Node type edit page has broken fieldsets in 1.x branch

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop/backdrop-issues#2641]
![vtabs-broken](https://cloud.githubusercontent.com/assets/16973264/25028137/42bb99be-20c3-11e7-933d-ac741147875a.jpg)

I have tested sandbox with current dev version and find out that node type edit page is broken. Some fieldsets are separated from vertical tabs. Probably it caused by one of latest commits, because 1.6.3 works fine.

----
PR: https://github.com/backdrop/backdrop/pull/1834

**Comment by serundeputy** [comment]
@Al-Rozhkov thanks for reporting!

The a closing `</code>` tag was `<code>` causing the markup to go astray.

sandbox:
Website: http://1834.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: 5bcGJfjP

@Al-Rozhkov can you give that sandbox a look?

**Comment by klonos** [comment]
Yep. My doing with https://github.com/backdrop/backdrop/pull/1819/commits/07ad01abc09f150be15d2456d5c36eae47107555. Sorry 😞 

RTBC 👍

**Comment by serundeputy** [comment]
Thanks for the report @Al-Rozhkov; thanks for RTBC @klonos 

merged into `1.x` and `1.6.x`
