### ISSUE TITLE
Convert double spaces to single spaces on the generated HTML output from function theme_menu_toggle() in menu.inc

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2642]
Reduce double spaces to single spaces (1st PR):

![image](https://cloud.githubusercontent.com/assets/2423362/25058439/c3f0ffac-21bc-11e7-9180-2a48d17642f1.png)

Reduce double spaces to single spaces for attributes and completely remove the spaces between span tags (2nd PR):

![image](https://cloud.githubusercontent.com/assets/2423362/25058624/1aac6f3c-21bf-11e7-8d45-8a8aab60603a.png)

It bothered me, so I fixed it. ...don't ask why 😄 

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1837 (converts double spaces to single spaces)
alternative PR by @klonos: https://github.com/backdrop/backdrop/pull/1838 (completely removes spaces between `<span>`s)

**Comment by klonos** [comment]
Notes: the single space after the `'<ul'` in [function theme_menu_tree()](https://github.com/backdrop/backdrop/blob/1.x/core/includes/menu.inc#L1736) is completely unnecessary, since a space is always added before the first attribute in [function backdrop_attributes()](https://github.com/backdrop/backdrop/blob/1.x/core/includes/common.inc#L2709)

**Comment by quicksketch** [comment]
Completely remove spaces FTW. Spaces can be notoriously problematic in menu markup because a space *renders*. If you want to make elements that are exactly next to each other, a space will create a gap. Then you have to CSS it out somehow.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1838 (no spaces) into 1.x and 1.6.x. Thanks @klonos!
