### ISSUE TITLE
The document is not mappable to XML 1.0 due to two consecutive hyphens in a comment.

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2645]
<!-- /.layout--moscone-flipped

**Comment by raseldewy** [comment]
Please use this comments formet

**Comment by BWPanda** [comment]
What does mapping the document to XML give/provide? In other words, is this a bug? If so, who does it affect, etc.? Or a feature request?

More info please 🙂

**Comment by BWPanda** [comment]
Due to lack of further information, I'm closing this issue.
