### ISSUE TITLE
Delete url aliases shows wrong form

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop/backdrop-issues#2649]
I'm a little confused. "Delete url aliases" duplicate "Url alias pattern settings" form.

![delete-url-aliases](https://cloud.githubusercontent.com/assets/16973264/25203508/87fad188-256a-11e7-850f-cbec929654af.jpg)

But looks like we don't need separate delete aliases page, because we have "Generate URL aliases" which actually can delete url aliases too.

![generate-url-aliases](https://cloud.githubusercontent.com/assets/16973264/25203587/cf6893e8-256a-11e7-97c5-d3946fde950c.jpg)

I have double checked everything. And things are the same on all my 1.6.3 Backdrop sites. I was able to delete aliases on "Generate URL aliases" page :)

As I understand it we should remove "Delete url aliases" pages and rename "Generate URL aliases" in something about bulk operations.

PR: https://github.com/backdrop/backdrop/issues/1848

**Comment by Al-Rozhkov** [comment]
Interesting update.

![admin-menu](https://cloud.githubusercontent.com/assets/16973264/25203909/2b951fc8-256c-11e7-849b-cf07773de54d.jpg)

> As I understand it we should remove "Delete url aliases" pages and rename "Generate URL aliases" in something about bulk operations.

In admin menu everything it is exactly like that. But my tabs still have confusing labels "Delete url aliases" and "Generate URL aliases".

**Comment by olafgrabienski** [comment]
I can confirm the issue: The page "Delete URL aliases" (admin/config/urls/path/bulk-delete) doesn't exist, or: it exists but it shows the content of the "URL alias pattern settings" page (admin/config/urls/path/patterns/settings).

Btw, on my test site, the issue exists even in the admin menu.

**Comment by Al-Rozhkov** [comment]
"Generate URL aliases" renamed to "URL aliases bulk actions". "Delete URL aliases" removed.

I think it is good candidate for 1.6.4

**Comment by Dinornis** [comment]
PR looks good, there is one failed test, not sure what it means.
**Message:** `FAIL: Alias for node/3 with language 'und' was node/3, expected content/node1.`
**Filename:** `path_pattern.test`
**Function:** `PathPatternFunctionalTestCase->testNodeOperations()`

**Comment by quicksketch** [comment]
Nice find and fixing @Al-Rozhkov! Merged your PR into https://github.com/backdrop/backdrop/pull/1848 for 1.7.0 and 1.6.4.

**Comment by serundeputy** [comment]
This is merged so closing.
