### ISSUE TITLE
Documentation for hook_ckeditor_plugins() incorrect

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2650]
I believe the documentation for [hook_ckeditor_plugins()](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.api.php/function/hook_ckeditor_plugins/1) is incorrect...

It says one of the properties of the plugin array is 'location', however that doesn't appear anywhere in core's implementation: [ckeditor_ckeditor_plugins](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.module/function/ckeditor_ckeditor_plugins/1).

'path' seems to be the correct property instead...
Am I reading this right?

**Comment by BWPanda** [comment]
Added a PR that fixes this. After some research I'm convinced that the documentation was wrong and that 'location' should be 'path'.

**Comment by herbdool** [comment]
@BWPanda do you have any links to the research to review?

**Comment by BWPanda** [comment]
Will have to research again, can't remember what I was looking at...

1. The [API example](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.api.php/function/hook_ckeditor_plugins/1) code shows 'path' and not 'location'.
2. The [sole implementation](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.module/function/ckeditor_ckeditor_plugins/1) of `hook_ckeditor_plugins()` in core doesn't use 'location' once but uses 'path' three times.
3. [`ckeditor_get_settings()`](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.module/function/ckeditor_get_settings/1) (which calls the function that invokes `hook_ckeditor_plugins()`) uses 'path' and not 'location'.

Hope that helps.

**Comment by herbdool** [comment]
Thanks, that helps! I think it's pretty clear you're right then.

**Comment by quicksketch** [comment]
Thanks! You're right @BWPanda! At one point in early development we had used "location" that included both the path and file, but then we separated them. I don't think we ever had a production version that used location though.

Merged https://github.com/backdrop/backdrop/pull/2209 into 1.x and 1.10.x. Thanks!
