### ISSUE TITLE
[UX] Add missing tokens for date fields

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2652]
Backdrop should provide a token for date fields with a custom date format like `[node:field_event_date:custom:?]` and other alternatives to the default format. Such tokens exist for node creation dates, e.g. `[node:created:custom:?]`, but not for date fields.

In my opinion, customized date field tokens are a important feature because not customized ones lead to ugly strings like `2017-04-27-140000-to-2017-04-27-170000` in the URL alias.

@jenlampton agreed on Gitter a couple of days ago:

> Missing tokens should be added directly from their source, in this case it sounds like date module? If theres one you need that's not there we should add it :grinning: Can you open an issue for the missing token(s)?
> 
> The fact that we have it for created/post date but not for date field dates might be an indicator of the underlying data structure being different (unix timestamp vs mysql date) but that doesn't mean we shouldn't also provide the same feature for mysql dates, just that it was an oversight when these things went in.

Re date module, see `core/backdrop/core/modules/date/date.tokens.inc`.

Below is a list of tokens provided for the created/post date. I guess they're all useful for date fields:

```
[node:created]
[node:created:long]
[node:created:medium]
[node:created:short]
[node:created:custom:?]
[node:created:since]
[node:created:raw]
```

Unfortunately, I myself don't have the skills to implement the request.

**Comment by Al-Rozhkov** [comment]
Duplicate of #2069, but described more detailed.

**Comment by olafgrabienski** [comment]
I've just found the related issue #1425 where missing tokens were discussed and labeled as a bug:

>> ... has anyone proposed using configurable tokens by adding additional arguments within the brackets? Then we could enter something like [node:field_event_date:start_date:short] to just display the short version of the start date. -- by @mikemccaffrey 

> I was also a little surprised to find that wasn't working. I think this functionality should also exist by default. It works for [node:created] e.g. [node:created:short], but not for date fields. Looks like something that didn't make it in the port somehow. -- by @quicksketch 

Closing this issue as a duplicate.
