### ISSUE TITLE
Potential bugs with hooks in user_save_role()

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#2654]
I can't get `hook_user_role_update` to fire. So I think there are a couple issues with `user_save_role()` that is at the root of this:

1. `$config->isNew()` is being checked *after* the $config object is saved. In my testing it seems that once the config file is created `isNew() never returns `true`.

2. The two hooks seem to be backwards. Shouldn't `hook_user_role_insert` be triggered when `$config->isNew()` is `true` and not `hook_user_role_update`?

```
if ($config->isNew()) {
    module_invoke_all('user_role_update', $role);
    $status = SAVED_NEW;
  }
  else {
    module_invoke_all('user_role_insert', $role);
    $status = SAVED_UPDATED;
  }
```
----
PR by @herbdool https://github.com/backdrop/backdrop/pull/1841

**Comment by docwilmot** [comment]
I think youre right on all counts:
```
Config::save() {
  ...
  $this->isNew = FALSE;
  ...
  return $this;
}
```

Ouch!

**Comment by herbdool** [comment]
I think we can use the same structure as the save() function here: `taxonomy/taxonomy_vocabulary.class.inc`

**Comment by mikemccaffrey** [comment]
Great catch @herbdool. Amazing that we had not caught this for three years.

**Comment by quicksketch** [comment]
Yep a great find @herbdool.

Merged https://github.com/backdrop/backdrop/pull/1841 into 1.x and 1.6.x. Thanks @herbdool!
