### ISSUE TITLE
Views/Teaser format: Read more link.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2656]
When using the teaser format for a view, is there a way to supress the 'read more' link when the content is so short that there isn't any more to read?

**Comment by klonos** [comment]
I believe you can do this by unticking the "Display links" option under teaser settings within views:

![image](https://cloud.githubusercontent.com/assets/2423362/25551833/7bc9b59e-2cce-11e7-9e95-bc2775d6d1db.png)

![image](https://cloud.githubusercontent.com/assets/2423362/25551842/99329d30-2cce-11e7-8d7f-17b214973044.png)

**Comment by klonos** [comment]
...ooh I have read your question again and realized that you want this *conditionally* when there's nothing more to read. No idea about that.

**Comment by klonos** [comment]
...I think that the more link is there to serve as a "read the entire article" or "view the rest of the node (there might be other fields besides this text)" thing. You obviously have a use case where that text is all there is. Not sure how to deal with that.

**Comment by olafgrabienski** [comment]
I'm also interested in the topic and had a look at how you would solve the issue in Drupal. I've found two approaches so far: an article about how to conditionally display the *Read more* link configuring Views (but with fields display), and a module which has a relevant option.

- [Drupal: Conditional Read More link in Views](http://www.amaslo.com/2012/12/drupal-conditional-read-more-link-in.html) (Article)
- [Read More Control](https://www.drupal.org/project/readmorecontrol) (Drupal Module)

**Comment by klonos** [comment]
This has been asked in the forum: https://forum.backdropcms.org/forum/how-does-backdrop-cms-handle-read-more-links

@BWPanda replied with this:

> Not sure if this is helpful, but I use the [Smart Trim](https://github.com/backdrop-contrib/smart_trim) module which, among other things, lets you add a read more link (or not).

**Comment by klonos** [comment]
If the already-ported [Smart Trim](https://github.com/backdrop-contrib/smart_trim) module doesn't cut it, then I suggest opening a port request in https://github.com/backdrop-ops/contrib/issues for Read More Control.

I'll go ahead and close this old issue here.
