### ISSUE TITLE
Sutro layout duplicates "Main page content" block when used as the default layout.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2660]
I had set Sutro as my default layout and was seeing my main content duplicated on the page. After investigation I realised that this is because Sutro has its default region as half1 but still has a Content region.

On the `Manage Blocks` admin page it does not show that the main page content is assigned to the Half First (half1) region, and if it is assigned to the Content region it appears twice.

There seems to be no way for the user to see that it is going to appear in the Half First region, nor to override this.
<img width="2430" alt="screen shot 2017-05-01 at 11 58 27 am" src="https://cloud.githubusercontent.com/assets/397895/25590470/8f874c66-2e65-11e7-88e8-e52f35425bd9.png">

---
PR: https://github.com/backdrop/backdrop/pull/1853

**Comment by Dinornis** [comment]
Thanks for your detailed description. I tested this in 1.7.x-dev and confirm this bug.

**Comment by jenlampton** [comment]
Thanks for the bug report @Graham-72, I think the content region being set to half1 is a remnant from before we added the content region to Sutro. Can you check and see if fixing the defined content region in Sutro solves the issue?  
Here's a PR: https://github.com/backdrop/backdrop/pull/1853

The assumption was that a layout either had a region named `content` - and that was the default region - or it did not have a region named `content`. This use-case of having that region but not using it as the default region was not accounted for.

**Comment by Graham-72** [comment]
I think it may need more than this PR because there still seems to be something strange happening. Maybe the Sutro template needs checking? If I now try to assign the main content to half1 and remove it from content it still appears in both. I will do some more testing in a day or so.

**Comment by bd0bd** [comment]
I think layout--sutro.tpl code is wrong.

Or this image is wrong (incorrect) - there is no the main content block on this image:
![sutro](https://cloud.githubusercontent.com/assets/13515302/25579150/dc1e6b32-2e7d-11e7-8bb8-4346930362a4.png)

      <?php if (!empty($content['content'])): ?>
        <div class="l-content" role="main" aria-label="<?php print t('Main content'); ?>">
          <?php print $content['content']; ?>
        </div>
      <?php endif; ?>

      <div class="l-middle l-halves row">
        <div class="l-halves-region col-md-6">
          <?php print $content['half1']; ?>
        </div>
        <div class="l-halves-region col-md-6">
          <?php print $content['half2']; ?>
        </div>
      </div>

**Comment by Graham-72** [comment]
I think this image could be used
![sutro](https://cloud.githubusercontent.com/assets/10559274/25583340/482cb51c-2e89-11e7-8b57-656f1861d134.png)
but I don't know how to upload it as a PR!

**Comment by jenlampton** [comment]
The image is definitely incorrect.  I've added this updated graphic into the PR that's currently open, but I'm also seeing rendered content twice, once in the content region.  Will dig deeper!

**Comment by bd0bd** [comment]
> The image is definitely incorrect.

May be no.
I consider this layout the same like Moscone but with equal left and right columns width.

**Comment by jenlampton** [comment]
@bd0bd the Moscone region has "content" on the left, and "Sutro" has an additional "content" region above the left/right columns. (There's an extra row on Sutro -- like the new graphic)

**Comment by bd0bd** [comment]
@jenlampton, I understand. For Sutro I need the same.

**Comment by Graham-72** [comment]
Looking at function `ensurePageContentBlock()` in `layout_renderer_standard.inc` it seems that this is intended behaviour for the default layout. If one needs to place the main content in a block other than the default region, one has to create a new layout with a name other than 'default layout'.

However, with Sutro there was I think a particular problem, because the template seemed to be written for content to be the default region because of the placing of the code `role="main" aria-label="<?php print t('Main content'); ?>`

So the PR is correct?

**Comment by jenlampton** [comment]
> Looking at function ensurePageContentBlock() in layout_renderer_standard.inc it seems that this is intended behaviour for the default layout. If one needs to place the main content in a block other than the default region, one has to create a new layout with a name other than 'default layout'.

This seems bizarre to me. Why is this the intended behavior @quicksketch ?

> However, with Sutro there was I think a particular problem, because the template seemed to be written for content to be the default region

Yes, I think the PR still needs to go in, but it would be good to figure out why all the custom magic for the default layout, and if there's a way we can support this use case.

It's a valid use case to want to move the "Main page content" block on the 'Default' layout, Especially with one like Sutro.

**Comment by Graham-72** [comment]
One of the disconcerting things from a user viewpoint is that the Manage Blocks page does not always show where the main page content is going to appear.

**Comment by jenlampton** [comment]
Yeah, that's a problem :)

**Comment by quicksketch** [comment]
`ensurePageContentBlock()` seems a little overzealous to me. It should ensure a main page content block exists, and if it does not, put it into the default region. The duplicating of the main page content block is not intentional. It should never be adding the entire page content a second time.

I think we need to refresh this implementation so that it checks for the existence of the main page content, and if it exists it can just bail out immediately.  This is intended to be a safety-check, not a limit to the way an end-user can configure the layout.

**Comment by quicksketch** [comment]
I made a new bug for the duplicate main page content issue: https://github.com/backdrop/backdrop-issues/issues/2691

The PR at https://github.com/backdrop/backdrop/issues/1853 to fix Sutro in particular has been merged into 1.x and 1.6.x.
