### ISSUE TITLE
Unclosed <code> tags in Pathauto and System modules help text.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2663]
It looks like the pathauto description text for user accounts has an unclosed tag

`For example the URL <code>members/jane-doe<code>` 

<img width="1206" alt="screen shot 2017-04-30 at 8 07 50 pm" src="https://cloud.githubusercontent.com/assets/397895/25571105/c9edc1da-2de0-11e7-928b-1f4d2ef9db50.png">

---
PR https://github.com/backdrop/backdrop/pull/1857

**Comment by klonos** [comment]
This is the doing of [one of my PRs](https://github.com/backdrop/backdrop/commit/ba845f5ec5fcbd4c5fdb840cb0ddc474abfb7064). Ooops. I told you guys... I'm sleep deprived most of the time. Be careful when reviewing and merging my PRs 😄 😞 

Thanx for picking that up @jenlampton 👍 RTBC.

**Comment by klonos** [comment]
...there's more of them in there. Filing a PR against your branch @jenlampton ...

**Comment by klonos** [comment]
https://github.com/jenlampton/backdrop/pull/2 ...sorry for my sloppiness.

**Comment by jenlampton** [comment]
Merged, thanks for the PR @klonos

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/1857 into 1.x and 1.6.x.
