### ISSUE TITLE
[UX] Layout and Block visibility conditions: add validation when entering entity IDs to ensure that only numbers are allowed.

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2668]
**Updated issue description**

I created a custom node Layout and tried to set the visibility condition of the Layout to "Node ID is `node/7`" (see Original issue description below). That didn't work because you have to enter just the number, e.g. `7`, instead of the path.

To prevent such an error, the Node ID form of the visibility condition dialog should be validated so that only numbers can be entered, and if needed, the user should get a respective message.

Another update: Looking at the dialog again, you see "Node ID is: node/7", but when you click on "Configure", there is a `0` (zero) in the Node NID field. So, the form seems to be validated, and the value is set automatically to `0` in the case you don't enter a number, but you don't get a reasonable feedback about it.

I tested Block visibility conditions as well. They have the same issue.

---

**Original issue description**

When I create a custom node layout, the condition "Node ID is `node/XYZ`" doesn't work.

Steps to reproduce on a Backdrop 1.6.3 site:

1. Add a node, e.g. `node/7`.
2. Add a custom layout, Path: `node/%`, Visibility condition: "Node ID is `node/7`".
3. Add a unique block to the custom layout, just to be able to check if it's displayed.
4. Go to `node/7`. The custom layout isn't in use. Instead I see the content in my default node layout (path: `node/%`, no further conditions).

If you change the visibility condition in step 2 to "Current path is `node/7`", everything works fine.

As mentioned above, on the site in question, there is a more general custom node layout in use on the site:

- I changed the order of the layouts, just in case, even if the more specific should work anyway. Changing the order didn't resolve the issue.
- To check if the more general custom layout causes any problem, I disabled it. That didn't help, resulting in the display of the Default layout provided by Backdrop core.

I'd be happy if someone could try to reproduce the issue!

**Comment by klonos** [comment]
@olafgrabienski I was just reading the steps you were taking over on Gitter and this is what I think might be wrong: "Node ID is `node/7`". Node IDs are just numbers; no paths. So this condition should be just "Node ID is `7`". I have not tested this, but that's what I think you're doing wrong. Need to attend the weekly dev meeting. Back with some testing after that 😄 ...

**Comment by klonos** [comment]
...but what we definitely need here is validation on the form so that only numbers are entered as NID.

**Comment by olafgrabienski** [comment]
> So this condition should be just "Node ID is 7".

@klonos Thanks for your suggestion, that's absolutely true!

I'll change the issue description and title to reflect the need of form validation.

**Comment by olafgrabienski** [comment]
@klonos After some more testing I updated title and issue description again. Seems that there is a form validation, but it doesn't help really and should be improved.

**Comment by klonos** [comment]
@olafgrabienski yes, the validation should happen for both layout conditions and block conditions. I had renamed the issue and included only blocks, you renamed it to change blocks to layouts, then must have realized that these conditions apply to both and re-renamed it 👍 

This is not only about NID only though. Depending on context it could be a UID or a TID. So, I am re-re-renameing to account for entities 😄 

Also, there is no actual validation on the dialog that adds/edits the visibility conditions and this leads to the form allowing strings to be saved where only numeric values should be entered:

![image](https://cloud.githubusercontent.com/assets/2423362/25763026/95e76a2e-3224-11e7-90f2-680b9851f165.png)

Notice how I was not prevented to enter "abc" as NID and when I try to edit it, the NID has fallen back to 0.

This is a bug; not a task.

**Comment by olafgrabienski** [comment]
Thanks, @klonos - I agree with all points.

> Notice how I was not prevented to enter "abc" as NID and when I try to edit it, the NID has fallen back to 0.

At the screenshot notice also the difference between "Node **ID** is: ..." and "Node **NID** is ...". "Node NID" sounds quite confusing, we should use just "Node ID".

**Comment by klonos** [comment]
Yes, I think that the "Node NID" was unintentional (perhaps carried away because the drop-down menu has a "Node: NID" entry, which in the context of the drop-down does make sense).

**Comment by jenlampton** [comment]
Closing https://github.com/backdrop/backdrop/pull/3759 in favor of this issue, since it was older. Thanks @bugfolder for the quick PR!

**Comment by jenlampton** [comment]
I've provided an [alternate PR](https://github.com/backdrop/backdrop/pull/3760) that changes only 2 lines, But the error messaging is a little different:
<img width="594" alt="Screen Shot 2021-09-29 at 4 50 59 PM" src="https://user-images.githubusercontent.com/397895/135363998-f40bbca8-db57-4a93-8cb4-a806b47d10bc.png">

**Comment by klonos** [comment]
I prefer https://github.com/backdrop/backdrop/pull/3760 where we leave the validation to the number field type.

**Comment by quicksketch** [comment]
I think @bugfolder's PR at https://github.com/backdrop/backdrop/pull/3759 is probably the better fix. As he points out, it's also helpful to validate the associated entity actually exists.

But I think we should do both! It's helpful to use the `type="number"` form element for assistive technologies and keyboards (such as touch devices) that adjust the keyboard based on the element type.

So for now I've gone ahead and already merged https://github.com/backdrop/backdrop/pull/3760 (Jen's PR). I think https://github.com/backdrop/backdrop/pull/3759 may now need to be adjusted to only handle the additional ID checking. Or perhaps we should set `#element_validate = array()` to let it handle all the validation.

**Comment by jenlampton** [comment]
I like this compromize, the best of both!

**Comment by indigoxela** [comment]
Hm, something went wrong with this PR - in contains several unrelated changes from other PRs. Maybe merged instead of rebased?

Also: @bugfolder actually EntityIDLayoutAccess now uses a "number" form API element instead of textfield. That change got merged and already does the validation for positive integer. Another check in validation seems redundant, the only thing needed is to verify that an entity with that ID exists, or am I missing something?

**Comment by bugfolder** [comment]
> Maybe merged instead of rebased?

Wow, yes. Not sure what went awry, but I'll redo the PR.

> Another check in validation seems redundant, the only thing needed is to verify that an entity with that ID exists, or am I missing something?

The check is to avoid giving two error messages for the same error. If we don't do the re-check, then if someone enters "foo" they'll get two error messages: "Node NID is not numeric" and "There is no node with ID 'foo'". They don't need the second error message if the NID itself fails to be a positive integer, and we don't need to spend db cycles to attempt to perform an entity load.

**Comment by bugfolder** [comment]
PR replaced. New one includes just the goodies. https://github.com/backdrop/backdrop/pull/3771

**Comment by bugfolder** [comment]
Whoa, though. The 'number' element is not forcing the type to be numeric. Enter 'foo' and the dialog happily transforms it to a 0 and accepts it.

**Comment by bugfolder** [comment]
Issue filed. https://github.com/backdrop/backdrop-issues/issues/5281.

**Comment by bugfolder** [comment]
Per [this comment](https://github.com/backdrop/backdrop-issues/issues/5281#issuecomment-932991744), we can prevent non-numeric entries by setting the element `'#required' => TRUE`. The browser validation will submit an empty string, and then standard form validation will reject the empty submission.

PR updated.

**Comment by bugfolder** [comment]
Note, though, that if you enter something like `node/1`, the field will be cleared and the error message will be "Node NID is field is required" rather than something more useful like "what you typed in wasn't numeric". I don't think there's any way to achieve that, though, because the browser submits an empty string, so there's no way for the server to know that you had typed something in.

**Comment by docwilmot** [comment]
> Note, though, that if you enter something like node/1, the field will be cleared and the error message will be "Node NID is field is required" rather than something more useful like "what you typed in wasn't numeric". I don't think there's any way to achieve that, though, because the browser submits an empty string, so there's no way for the server to know that you had typed something in.

Perhaps change the message to "Please enter an integer value for Node NID"? That would be appropriate for both empty submissions and string submissions.

**Comment by bugfolder** [comment]
Agreed. That will be possible after https://github.com/backdrop/backdrop-issues/issues/5348 is merged in, but for now, the error message for required fields is unchangeable.

**Comment by indigoxela** [comment]
I followed the steps again, and here's what I get for a non-existent nid:

![node-visibility-cond](https://user-images.githubusercontent.com/842066/145595666-d668e6ae-5bc2-4989-974d-aecd6eb214f6.png)

Nice! Definitely works for me.

**Comment by indigoxela** [comment]
@bugfolder  A tiny coding standard improvement and then we're done.

**Comment by bugfolder** [comment]
I made that change, both in the function noted, and in three more places in the same file. (Also see the same thing in a few other access plugins, but I'll leave those alone for now.)

**Comment by docwilmot** [comment]
I'm finding that I cannot type non-numeric characters in the number field. Is this browser dependent?

**Comment by bugfolder** [comment]
Yes. Some browsers won't let you type non-numeric values, others let you type it in but then submit an empty value. (My recollection was that Chrome did the former, Safari did the latter.)

**Comment by indigoxela** [comment]
> I made that change, both in the function noted, and in three more places in the same file.

Great, many thanks. This really improves code readability. :+1: RTBC!

**Comment by klonos** [comment]
@indigoxela please excuse my ignorance, but can you please point me to the coding standard about breaking long lines of functions that include arrays as parameters? I'm asking because unless I'm mistaken, I think it is best-practice and preference rather than a coding standard. (I do not disagree - just curious of whether we have this documented in our coding standards or not)

**Comment by klonos** [comment]
@bugfolder just a couple of extraneous spaces in the PR (I've left code suggestions).

**Comment by indigoxela** [comment]
@klonos the officially published coding standards for Backdrop are very sparse. I mostly rely on phpcs, as I'm using it with both, Backdrop and Drupal.

PS: I'd never try to argue coding standard topics with you. :stuck_out_tongue_winking_eye: I've learned.
Just do what you feel is appropriate.

**Comment by bugfolder** [comment]
> just a couple of extraneous spaces in the PR (I've left code suggestions).

Thanks, suggestions merged into PR.

**Comment by klonos** [comment]
> PS: I'd never try to argue coding standard topics with you. 😜 I've learned.

@indigoxela 😝 ...these specific were double spaces between array key/values. For example:

```diff
- '@entity'  => $this->entity_info['label'],
+ '@entity' => $this->entity_info['label'],
```

In general though, my process is look in the Backdrop coding standards, if they don't say anything, then fall back to D7 coding standards (and try to copy the D7 coding standards to our docs.b.org), if nothing there either, then I usually start a discussion/issue about establishing a coding standard.

**Comment by quicksketch** [comment]
I merged the follow-up PR at https://github.com/backdrop/backdrop/pull/3771 into 1.x and 1.20.x. Thanks for following through on this @bugfolder! Thanks @indigoxela, @klonos, and @docwilmot for the follow-up reviews!

**Comment by klonos** [comment]
I had some half-done solution in my local instead of the odd usage of `round()` in the validation. I was using a combination of `'#step' => 1,` + adding `pattern="\d*"` via `'#attributes'` in the form element (to avoid decimals). Perhaps I'll file a follow-up PR.
