### ISSUE TITLE
Token dialogs missing `[current-date:*]` tokens

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2670]
In #1585, it was noted that we should have current date tokens available for specifying the CKEditor upload directory. But looking throughout Backdrop, I found that the `current-date` tokens don't seem to be present anywhere. They still exist in `system_token_info()` though, so it seems as though they should be there.

PR: https://github.com/backdrop/backdrop/pull/1866

**Comment by Al-Rozhkov** [comment]
I tested sandbox and it works, [current date:*] tokens are there.

**Comment by Dinornis** [comment]
Same here.

**Comment by quicksketch** [comment]
Holy moly @daggerhart! You are so amazing. I spent a good half hour trying to figure this out and it was just a typo! Nice spotting.

Thanks @Al-Rozhkov and @Dinornis for testing! Merged into 1.x and 1.6.x.
