### ISSUE TITLE
Basis. Wrong css properties in skin.css

### ISSUE THREAD

**Issue by Al-Rozhkov** [backdrop/backdrop-issues#2671]
Responsive menu styles in skin.css contain wrong css properties: `border-color-top`, `border-color-left`... Correct properties are `border-top-color`, `border-left-color`.

Looks like this is not affect on functionality, because correct styles defined in menu-dropdown.css file. Should we remove this lines or correct?

PR: https://github.com/backdrop/backdrop/pull/1869

**Comment by olafgrabienski** [comment]
@Al-Rozhkov Haven't checked the file yet, but I guess we shouldn't remove the properties but change them. As far as I know, many styles of different files were intentionally duplicated by @wesruv in `skin.css` to use or to override them easily in a sub-theme.

**Comment by olafgrabienski** [comment]
@Al-Rozhkov By the way, regarding "Responsive menu styles". I recently made a PR to improve the look and feel on smaller screens. If you feel like having a look at it: [Proposal](https://github.com/backdrop/backdrop-issues/issues/2553#issuecomment-281195587),  [PR](https://github.com/backdrop/backdrop/pull/1825)

**Comment by Al-Rozhkov** [comment]
Thank you for explanation @olafgrabienski. I'll provide PR to correct css properties.

**Comment by quicksketch** [comment]
The PR code looks great, thanks for fixing those @Al-Rozhkov!

> Looks like this is not affect on functionality, because correct styles defined in menu-dropdown.css file.

In that case, this seems good to merge. Marking it RTBC for later.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1869 into 1.x and 1.6.x. Thanks @Al-Rozhkov!
