### ISSUE TITLE
[UX] Misleading/inaccurate message after installing layouts (layout projects)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2672]
![image](https://cloud.githubusercontent.com/assets/2423362/25763226/5feeac10-3225-11e7-849a-37090ef38dea.png)

What's wrong with this page?...

1. It tells the user that new "layouts" we installed in a page where layouts are listed, but the layouts just installed are not there. The reason of the WTF here is the disambiguation between what a layout *project* and a layout is and the fact that what was actually installed is a layout *project* which includes either one or more layout *templates*. We had this discussion and made a decision and some compromises, so I will not get into that again. The fact remains though that telling the user that new layouts were installed is not 100% accurate. There is no way to avoid introducing more confusion unless we are intentionally vague here. I propose changing the first part of the message to the generic "Installation finished successfully." instead.

2. The second part of the message tells the user that they may *enable* layouts on the "Layout" page. Right. What? This refers to the layouts *Settings* page, where layout *templates* can be enabled **and disabled** and to make things worse, even if we change the link to point to `admin/structure/layouts/settings` (which we should), the user will navigate there only to find out that all newly-added templates are already enabled by default. So there's nothing to *enable* as the message suggests. So, I think that the second part of the message should be changed to "All newly-added layout templates have been enabled and are available for use in your layouts." ...so the user knows that there is nothing they need to do. And continue to say: "You may manage layout templates on the Layout settings page."

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1865

**Comment by klonos** [comment]
...an alternative way to address this (will file a new PR soon) would be to be redirecting to the layout "Settings" page instead of the "List Layouts" page. The message could then say "One or more layout templates were installed. All these templates ware enabled for you, but you can disable the ones you don't need using the list below. Enabled templates can be used when building [layouts](url)." ...and have the link point to the "List Layouts" page.

**Comment by quicksketch** [comment]
I think your new message is just fine. I like that we auto-enable the layouts and if a user doesn't use one, it's not going to hurt anything.

Translation-wise, I normally wouldn't encourage separating the text of the link out from the string, as the link text may be context-sensitive. However in the case of the word "Settings" (which is already going to be translated), I think you did the right thing here.

RTBC unless you have any further concerns here.

**Comment by klonos** [comment]
Hey @quicksketch, I was about to start drafting a PR for the alternative, but realized that when most users install contrib layouts, they will most likely need to head to the layouts page rather than the layouts template page. I say lets just get it in 😄 ...also (shamelessly promoting my PRs) if you could take a look at this oldie: https://github.com/backdrop/backdrop/pull/1871

**Comment by quicksketch** [comment]
Great, merged https://github.com/backdrop/backdrop/pull/1865 into 1.x and 1.6.x. Thanks @klonos!
