### ISSUE TITLE
Duplicate: Provide commonly used formatters for fields in core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2674]
We should provide more field formatters to cover the most common use-cases for the display of multiple values.

Suggestions include:
* [Comma separated list](https://github.com/backdrop/backdrop-issues/issues/316)
* HTML list
* Other?

In Drupal 6 you could choose to display taxonomy terms on a node as a comma separated list of links. In Drupal 7, the only way to achieve the same thing was to use the [taxonomy formatter module](https://www.drupal.org/project/taxonomy_formatter).

I would love to see this common-use-case feature restored to backdrop.

Here's a summary of sorts for these requests:

- Apply this new formatter to any multi-valued field
- Allow separating items by a custom delimiter (e.g. `,`, `;`, `-`, etc.)
- Allow formatting multi-valued fields as HTML lists (e.g. `<ul>`, `<ol>`)
- Allow specifying a different custom delimiter for the last two items (e.g. `&`)

Modules to use for inspiration:

- https://www.drupal.org/project/taxonomy_formatter (This module adds a new formatter that allows you to specify the element type, the wrapper type, classes for both, the separator used, and if they link to the term pages or not. This gives much more customizable layout options.)
- https://www.drupal.org/project/field_delimiter Field Delimiter provides an additional setting for field formatters, allowing multi-value fields to be displayed with a delimiter between the values.
- https://www.drupal.org/project/textformatter This module provides a field display formatter to render field values as HTML or comma-separated lists. This can currently be used on all core field types (text, long text, number, list, and taxonomy reference etc..) and some contributed fields. (see below).

**Comment by laryn** [comment]
Agreed that this would be good in core. This module also allows it in contrib for now:
https://github.com/backdrop-contrib/textformatter

**Comment by jenlampton** [comment]
Selfishly adding milestone :)

**Comment by jenlampton** [comment]
I really want this feature, but with 2 weeks before code freeze and a fantastic contrib solution already, it's not a priority for 1.8. I'm going to bump the milestone to 1.9.

**Comment by opi** [comment]
I used to have a custom "delimiter" formatter, that allow user to choose the delimiter (like a comma, br tag, ...), and a custom delimiter for the last element ( &, "and", ...)
can share the code if needed.

**Comment by jenlampton** [comment]
I seem to have a PR for this, but I'm not sure what's in it. Pushing here so I don't loose it...

**Comment by BWPanda** [comment]
Copying ideas from the other duplicate issue, it'd be great to also allow displaying multi-value fields as `<ul>` or `<ol>` as well.

So here's a summary of sorts for these requests:

- Apply this new formatter to any multi-valued field
- Allow separating items by a custom delimiter (e.g. `,`, `;`, `-`, etc.)
- Allow formatting multi-valued fields as HTML lists (e.g. `<ul>`, `<ol>`)
- Allow specifying a different custom delimiter for the last two items (e.g. `&`)

Modules to use for inspiration:

- https://www.drupal.org/project/taxonomy_formatter
- https://www.drupal.org/project/field_delimiter
- https://www.drupal.org/project/textformatter

Modules already ported to Backdrop contrib:

- https://github.com/backdrop-contrib/textformatter

Feel free to copy this to the original post above if it's helpful, and to edit at will.

**Comment by jenlampton** [comment]
Now that https://github.com/backdrop/backdrop/pull/2493 is in, I wonder if that changes how this might be implemented, or if what's in this PR is still the best path forward?

**Comment by klonos** [comment]
@jenlampton the PR is not linked anywhere.

**Comment by jenlampton** [comment]
Hm, well. Here's the branch: https://github.com/jenlampton/backdrop/tree/2674-formatter-comma

**Comment by jenlampton** [comment]
Well, I tried to make a new PR from that branch and GitHub said there were no differences. Let me rebase and make a new branch.

**Comment by jenlampton** [comment]
Since neither issue has had any activity lately, I'm switching back to the original one with the lower number: https://github.com/backdrop/backdrop-issues/issues/316

**Comment by jenlampton** [comment]
Resuming work on https://github.com/backdrop/backdrop-issues/issues/316
