### ISSUE TITLE
Backdrop news page

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2675]
Sorry for posting here.

There is a margin on right side of the page. Probably because of the video blocks:

![screenshot_2017-05-07-16-40-46](https://cloud.githubusercontent.com/assets/13515302/25781967/b36a8e66-3349-11e7-8258-05d961dbdf9d.jpeg)

**Comment by docwilmot** [comment]
Yep, between approx 768 and 1105px
But wrong queue @bd0bd

**Comment by bd0bd** [comment]
Sorry!
I know the queue is wrong.
But I prefer to write in a wrong place than NOT to write at all.

Every new time I do not remember the right place to write about the site.
Plus - it is difficult for me to find and go to the correct place :smile:

**Comment by klonos** [comment]
@bd0bd 👉  https://github.com/backdrop-ops/backdropcms.org/issues

**Comment by bd0bd** [comment]
Pls , how to?

**Comment by laryn** [comment]
@bd0bd Since this issue is already closed you should be able to just start one in the correct queue (linked above). Thanks for reporting!
