### ISSUE TITLE
Views RSS feeds dont work if using fields instead of content

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2679]
The feed tags come up but no content or links. Note in the image below fields are all empty. 

![screen-shot-2017-05-09-at-12 23 54-pm](https://cloud.githubusercontent.com/assets/1042283/25861690/16791862-34ab-11e7-812a-d1568dc3737a.png)

**Comment by docwilmot** [comment]
This one was hard to track: seems `theme()` doesnt see `theme_views_view_field()` unless you include the file in `views_plugin_style_rss::render()`.

Not sure if this is the best approach. @quicksketch?

**Comment by daggerhart** [comment]
Looks like can just need to include one new line in views.module.  ~ line 107 we can tell that theme hook what file its function lives in. `'file' => 'views.theme.inc',`

So that the result is:

```
  // Default view themes
  $hooks['views_view_field'] = $base + array(
    'pattern' => 'views_view_field__',
    'variables' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
    'file' => 'views.theme.inc',
  );
```

Can create a PR right this moment, on wrong computer. But if someone else hasn't w/i the next few hours, I'll do so.

**Comment by docwilmot** [comment]
Ahh silly. I tried the that, but put `path` instead of `file`.
Thanks.

**Comment by docwilmot** [comment]
Tested, added a new RSS feed, works like a charm. RTBC.

**Comment by serundeputy** [comment]
Nice one! thanks @docwilmot for finding and testing and thanks @daggerhart for PR!

This is merged into `1.x` and `1.6.x` will ship with `1.7` and `1.6.4`. thanks!
