### ISSUE TITLE
[UX] Missing Primary Tabs on Manage Display Sub-Pages

### ISSUE THREAD

**Issue by Dinornis** [backdrop/backdrop-issues#2681]
The Manage display sub-pages at `/admin/structure/taxonomy/tags/display/default` are missing the `LIST TERMS` `CONFIGURE` `MANAGE FIELDS` `MANAGE DISPLAYS` tabs.

To replicate:
1. Navigate to `/admin/structure/taxonomy/tags/display`
2. Click on the `MANAGE DISPLAY` operation for the `Default view` mode
3. When you arrive at `/admin/structure/taxonomy/tags/display/default` you can see the tabs are missing on that page.

The missing page title is being addressed at https://github.com/backdrop/backdrop-issues/issues/2614

---

PR https://github.com/backdrop/backdrop/pull/2205

**Comment by jenlampton** [comment]
I think this may be a duplicate? 
https://github.com/backdrop/backdrop-issues/issues/2614

**Comment by olafgrabienski** [comment]
@jenlampton The other issue is about the missing *title*, this one about tabs. I understood that you suggested in https://github.com/backdrop/backdrop-issues/issues/2614#issuecomment-300321979 to open *this* issue, or is it a misunderstanding?

**Comment by quicksketch** [comment]
I think there is a misunderstanding here. The missing *primary* tabs are a problem on these pages, they shouldn't go away if we can help it. It was intentional that the secondary tabs listing the display modes were removed (in 1.6.0).

The other issue is indeed just for fixing the page titles.

**Comment by jenlampton** [comment]
Oh jeez, what a mess. Sorry all, yes these are separate issues. Not sure what I was thinking :/

**Comment by Dinornis** [comment]
😀

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/2205.

**Comment by jenlampton** [comment]
YAY THE TABS ARE BACK 
<img width="966" alt="screen shot 2018-05-23 at 5 40 47 pm" src="https://user-images.githubusercontent.com/397895/40458363-7925d83a-5eb0-11e8-9ca7-31ce24d9a4d0.png">

**Comment by jenlampton** [comment]
Follow-up: https://github.com/backdrop/backdrop-issues/issues/3141

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2205 into 1.x and 1.10.x. Thanks!
