### ISSUE TITLE
[UX] Provide an option to maintain the aspect ratio when resizing an image and set it as the default.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2684]
### Steps to reproduce

Create a post node and add an image in the body via the CKeditor or edit an existing post with an image and double-click on the image. . 

### Actual behavior

When you change one of the image dimensions, the other one does not get updated. The user needs to calculate the other value on their own and update it accordingly.

### Expected behavior

There should be a "maintain aspect ratio" checkbox below the image dimension text fields that is checked by default. When one of the values is changed (either via typing a value, or by using the up/down arrows, or by pasting a value, or by scrolling their mouse wheel), the other one should be automatically updated.

**Comment by Graham-72** [comment]
When using Basis it seems that the dimension entered as the width is in control and the aspect ratio will be maintained as that of the uploaded file whatever is entered here as height.

**Comment by Graham-72** [comment]
This issue seems similar to #2054.
