### ISSUE TITLE
[UX] missing contextual links for views on page displays

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#2690]
# Issue Summary

The problem is that contextual links to edit views are broken on most sites (I believe they work in the admin theme). 

According to @robertgarrigos (and verified by @stpaultim) adding a "relative" position to the ancestor of the `contextual-links-wrapper` solves the problem. 

It has been suggested that the contextual link is simply being hidden by the admin bar, but that can not be correct, because the expected position of the contextual link is nowhere near the admin bar. 

![test_view___pr_1898_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/50543233-84f31080-0b97-11e9-9e5e-383ff86d2e5b.png)

@robertgarrigos has a pull request that partially works to resolve the issue, but NOT for all views. He is looking for feedback on his approach. 

The comments that seem most relevant towards finding a solution can be found here:

- https://github.com/backdrop/backdrop-issues/issues/2690#issuecomment-301975586
- https://github.com/backdrop/backdrop/pull/1898#issuecomment-302223781 (On Pull Request)

# ORIGINAL ISSUE

### Steps to reproduce
go to any page with a view, having the contextual links module active.

### Actual behavior
missing contextual link to edit the view, although you can see other links for blocks, menues and othjer elements

### Expected behavior
I would expect a link to edit the view

---

PR that forcibly adds classes: ~~https://github.com/backdrop/backdrop/pull/1898~~
PR that restores D7 behavior: ~~https://github.com/backdrop/backdrop/pull/2543~~
PR that places the contextual link via view template: https://github.com/backdrop/backdrop/pull/2544

**Comment by serundeputy** [comment]
Seems like a CSS positioning problem to me.

![views-contextual-link](https://cloud.githubusercontent.com/assets/6763671/26037131/0c326c6e-38bb-11e7-9e08-ea8406521291.png)

Link present in the markup and accessible in the top right of the page.  Needs to be repositioned.

**Comment by robertgarrigos** [comment]
In fact the problem is not with the position of the .contextual-links-wrapper or .contextual-links classes but with the missing position property of its ancestor. You can check it by adding position:relative to its ancestor, which in the case of the view's link is the div.l-page-title (with basis as theme and moscone flipped layout)

**Comment by robertgarrigos** [comment]
Even more: what is wrong, in my opinion, is that the .contextual-links-wrapper doesn't have an ancestor with a class .contextual-links-region. This class adds the position property needed. So I would add this class to the layout templates. It works for me.

**Comment by robertgarrigos** [comment]
Obviously, adding in the layout templates the class itself wouldn't be the best solution. Provably some of the preprocess_view functions out there would be best. This one, maybe: views_ui_preprocess_views_view()?

**Comment by robertgarrigos** [comment]
I need some help with this. The contextual-links-region class is being added in the contextual_preprocess() function, then printed in each of the layouts tpl files in the wrapper div (then gets out of sight), but not in the ancestor div of the title (where it should be, imho). The only way to have this class in the ancestor of the title is to add the class in each layout tpls an put some logic somewhere to check whether we actually need to print this class. The login could be something like this:
```
if (array_search('contextual-links-region', $classes)) {
  unset($classes[array_search('contextual-links-region', $classes)]);
  $contextual_region_class = 'contextual-links-region';
}
else {
  $contextual_region_class = '';
}
```

Where would be the best place to put this logic? A preprocess function, where?

**Comment by serundeputy** [comment]
There was a duplicate issue with some similar conversation and slightly different solutions here for reference: https://github.com/backdrop/backdrop-issues/issues/2909

**Comment by Graham-72** [comment]
Maybe things have changed since the above discussion because I am seeing the parent contextual-links-region class here
`<div class="layout--boxton layout contextual-links-region">`

My current problem is that the 'configure view' link is largely hidden by the admin bar across the top of the page and it needs to be positioned a few pixels lower in Basis. Perhaps this is best done by adding to the contextual.css file in Basis, such as
```
.l-page-title .contextual-links-wrapper{
  margin-top:7px;
}
```
This works for me.

**Comment by herbdool** [comment]
I see the html too in Basis and adjusting it down helps. The div is absolutely positioned so it could be done by making `top` bigger. But it needs to be smart enough to not add it if JS is disabled.

**Comment by stpaultim** [comment]
Some of the comments here suggest that this is Basis specific. I just switched to Bartik and seem to be experiencing the same problem.

**Comment by klonos** [comment]
I think that this is a common issue with the admin bar. The contextual links seem to be hidden behind it @stpaultim ...we just need to add some top margin.

**Comment by stpaultim** [comment]
Going to try and breath some life into this issue, it's a pet peeve of mine that I seem to deal with all the time. https://forum.backdropcms.org/forum/where-contextual-configure-view-link

We have a pull request that solves the problem for core themes, but that seems to be an inadequate solution. Can we get some feedback on the proper solution?

**Comment by klonos** [comment]
Thanks for taking the time to update the issue summary @stpaultim 👍 ...although I do not have an answer to this, I think that the discussion between @docwilmot and @robertgarrigos in the PR might also be of help:

@docwilmot:

>I'm not sure this is the ideal fix for the issue. This PR adds a contextual link element to a particular layout region. What if the View isnt in that region? If I put it in the footer for example? And the contextual links DIV in this case would be the entire content are including the sidebars.
>
>We need the contextual links data to be output in the Views preprocess itself, I suspect.

@robertgarrigos:

> @docwilmot agree, it's not ideal. I was looking to do it as you say, but found views much different from the drupal version and got stacked

**Comment by klonos** [comment]
...also, maybe I am missing something, but I still do not see the contextual link for the "promoted content" view in the home page of the PR sandbox 🤔

**Comment by jenlampton** [comment]
If we put some debug statements into `views_ui_preprocess_views_view()` in Backdrop, it looks like the if statement `if (!empty($view->views_ui_context) && module_exists('contextual'))` never evaluates to true. It looks like `$view->views_ui_context` isn't getting set, I'm going to look into why.

**Comment by jenlampton** [comment]
Update: In Drupal 7 there were two functions that added these classes, `views_preprocess_html()` and `views_preprocess_page()`. In backdrop, `views_preprocess_page()` has been replaced with `views_preprocess_layout()` and `views_preprocess_html()` has been removed.

In Backdrop's version of views, the function `views_add_contextual_links()` has been added, my guess is in an attempt to solve this problem. I'm going to dig into that function to have a look at what it's doing, and see if maybe something in there is being missed.

**Comment by jenlampton** [comment]
I've restored the `views-contextual.js` and made a few other changes to get the contextual links to appear in the top-right corner of the parent container of both the page title and view (as in D7/Bartik), but in Backdrop this parent container is usually the layout (not the region, as in D7/Bartik).

I've pushed a new PR for this that restores the D7 behavior, but I think we can do better. I'd like to see the contextual link appear right next to the view - just like it does for a block display. I'm going to see if I can find the code that treats a page display differently from a block, and remove that instead.

**Comment by jenlampton** [comment]
I've pushed a cleaner fix that removes any special handling for page displays, and instead adds the contextual link via the `views-view.tpl.php` file, which should place it closer to the view content. I think this makes more sense from a UX perspective, since it more closely matches the location of the links for block displays. 

New PR: https://github.com/backdrop/backdrop/pull/2544

**Comment by herbdool** [comment]
It doesn't seem to be working for me on a view as a page: http://2544.backdrop.backdrop.qa.backdropcms.org/test-view. Is the PR missing the fix for JS?

**Comment by jenlampton** [comment]
It's there:
<img width="977" alt="Screen Shot 2019-03-25 at 10 25 37 PM" src="https://user-images.githubusercontent.com/397895/54975071-30232400-4f53-11e9-9195-001033058c71.png">

**Comment by klonos** [comment]
Yeah, there is an empty sidebar there to the right of the view @herbdool:

<img width="1204" alt="Screen Shot 2019-03-26 at 7 02 08 pm" src="https://user-images.githubusercontent.com/2423362/54980379-ae3a0600-4ff9-11e9-90b6-87c2a4b1e072.png">

...so you'll need to hover a little bit to the left.

**Comment by herbdool** [comment]
Thanks, though for this one I couldn't find it http://2544.backdrop.backdrop.qa.backdropcms.org/my-view. Seems that a view of fields works, but not if it's teasers.  I think I saw the latter before.

**Comment by klonos** [comment]
>Seems that a view of fields works, but not if it's teasers. I think I saw the latter before.

Yeah, we are trying to solve that one here: #3615

**Comment by jenlampton** [comment]
Setting back to NR because that issue is unrelated.

**Comment by quicksketch** [comment]
This fix seems low impact and we have multiple confirmations of it improving the situation (though not solving everything, if the contextual links overlap). Looks good enough to proceed to me!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2544 into 1.x and 1.12.x. Thanks @robertgarrigos, @serundeputy, @stpaultim, @jenlampton, @herbdool, @Graham-72, and @klonos!
