### ISSUE TITLE
Add easy-to-enable HTTPS redirect rules in .htaccess

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2694]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/219

From @olafgrabienski 

> As HTTPS-only websites became more common in the last years, can we add corresponding rule examples while we're at changing the rewrite rules?

From @jenlampton:

> Yes, this is a great idea! 

From @jlfranklin :

> HTTPS can be, and probably should be, its own rule, separate from the add/remove www rules.

From @olafgrabienski 👍 

> I've no idea of which rewrite syntax makes sense technically. If it's possible I'd love however to have simply four rules of which I can uncomment the one that fits my needs:

- redirect all users to access the site with the 'www.' prefix
- redirect all users to access the site with the 'www.' prefix and using HTTPS
- redirect all users to access the site without the 'www.' prefix
- redirect all users to access the site without the 'www.' prefix and using HTTPS

---
PR by @opi: https://github.com/backdrop/backdrop/pull/2165

**Comment by jenlampton** [comment]
I think they should be separate, for simplicity's sake. One rule for the www or non-www redirect, and one for the https redirect. This is often how I end up doing things today anyway, by adding a second https redirect condition.

**Comment by olafgrabienski** [comment]
> I think they should be separate, for simplicity's sake. One rule for the www or non-www redirect, another one for the https redirect.

Sounds good!

**Comment by olafgrabienski** [comment]
> This is often how I end up doing things today anyway, by adding a second https redirect condition.

@jenlampton Could you share your suggestion for the HTTPS-only redirect? (I need it for a current project and such rules are quite cryptic for me.)

**Comment by laryn** [comment]
@olafgrabienski I use this one (taken from Stack Exchange at some point). Underneath `RewriteEngine On` add these two lines:

```
RewriteCond %{HTTPS} !=on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by olafgrabienski** [comment]
Thanks @laryn! Was not sure if Drupal and Backdrop work the same here. Do you put it above or below the redirect to always `www` (or the resprective non www) redirect?

I noticed however that in the case of my project there is an option to enforce SSL in the hosting provider interface, and that works fine so far.

**Comment by laryn** [comment]
@olafgrabienski I don't think it matters if it is above or below the others, although I usually put it above.

**Comment by opi** [comment]
PR: https://github.com/backdrop/backdrop/pull/2165

**Comment by jenlampton** [comment]
@opi I have a question on the PR. Not sure if it really NW but it worries me that we may be deleting a variable that's used later.

**Comment by laryn** [comment]
I think @opi is right (in the comment on the PR) that that variable is no longer used in the .htaccess file.

> opiniated change included, I remove the directive that define the [E=protossl] env variable, unused since https://github.com/backdrop/backdrop-issues/issues/219

**Comment by quicksketch** [comment]
Yep, agreed. Thanks @laryn and @opi! I've merged in https://github.com/backdrop/backdrop/pull/2165 for 1.10. Thanks!
