### ISSUE TITLE
Backdrop 1.6.4 Release.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#2695]
1.6.4 Release Checklist
==================================

## Pre-release tasks

- [x] Merge commits @serundeputy
- [x] Create a new bugfix release to follow the current version
- [x] Move all unfinished issues to the next bugfix release
- [x] Draft Release notes @serundeputy

## Release tasks

- [x] Update bootstrap.inc with version number @serundeputy
- [x] Tag for release, push to GitHub @serundeputy
- [x] Create release notes on GitHub @serundeputy
- [x] Revert version number back @serundeputy

**Comment by jenlampton** [comment]
I've merged this modified checklist into the minor release checkist for next time: https://github.com/backdrop/backdrop-issues/blob/master/procedures/docs/create-release-minor.md

**Comment by serundeputy** [comment]
closing.
re-open if something in `1.6.4` needs attending to.
