### ISSUE TITLE
tokens list not shown on url path patterns page

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#2697]
## Describe your issue or idea

Token list doesn't appear when clicking on "browse available tokens for content" on /admin/config/urls/path/patterns page

### Actual behavior (if reporting a bug)

php throws an error:

`
PHP Error:  Cannot use string offset as an array in /.../core/modules/system/system.theme.inc on line 692, referer: http://backdrop.cat/admin/config/urls/path/patterns
`

### Relevantt version/system information (if applicable)

* Last version 1.7, just upgraded
* works on `PHP 7.0.14` but not `7.1.1`

----
PR of @robertgarrigos: https://github.com/backdrop/backdrop/pull/1895

**Comment by robertgarrigos** [comment]
I fixed it by changing this function
`/**
 * Build a row in the token tree.
 */
function _token_token_tree_format_row($token, array $token_info, $is_group = FALSE) {
  // Build a statically cached array of default values. This is around four
  // times as efficient as building the base array from scratch each time this
  // function is called.
  static $defaults = array(
    'id' => '',
    'class' => array(),
    'data' => array(
      'name' => '',
      'token' => '',
      'value' => '',
    ),
  );

  $row = $defaults;
  $row['id'] = backdrop_clean_css_identifier($token);
  $row['data']['name']['data'] = $token_info['name'];
  $row['data']['name']['class'][] = 'token-name';

  if ($is_group) {
    // This is a token type/group.
    $row['class'][] = 'token-group';
    $row['data']['token']['data'] = '<span class="token-group-description">' . $token_info['description'] . '</span>';
  }
  else {
    // This is a token.
    $row['data']['token']['class'][] = 'token-token';
    $row['data']['token']['data'] = '<span class="token-key">' . $token . '</span>';
    if (isset($token_info['value'])) {
      $row['data']['value'] = $token_info['value'];
    }
    if (!empty($token_info['parent'])) {
      $row['parent'] = backdrop_clean_css_identifier($token_info['parent']);
    }
    $row['data']['token']['data'] .= '<span class="token-description">' . $token_info['description'] . '</span>';
  }

  return $row;
}`

to this
`/**
 * Build a row in the token tree.
 */
function _token_token_tree_format_row($token, array $token_info, $is_group = FALSE) {
  // Build a statically cached array of default values. This is around four
  // times as efficient as building the base array from scratch each time this
  // function is called.
  static $defaults = array(
    'id' => '',
    'class' => array(),
    'data' => array(
      'name' => '',
      'token' => '',
      'value' => '',
    ),
  );

  $row = $defaults;
  $row['id'] = backdrop_clean_css_identifier($token);
  $row['data']['name'] = $token_info['name'];
  $row['class'][] = 'token-name';

  if ($is_group) {
    // This is a token type/group.
    $row['class'][] = 'token-group';
    $row['data']['token'] = '<span class="token-group-description">' . $token_info['description'] . '</span>';
  }
  else {
    // This is a token.
    $row['class'][] = 'token-token';
    $row['data']['token'] = '<span class="token-key">' . $token . '</span>';
    if (isset($token_info['value'])) {
      $row['data']['value'] = $token_info['value'];
    }
    if (!empty($token_info['parent'])) {
      $row['parent'] = backdrop_clean_css_identifier($token_info['parent']);
    }
    $row['data']['token'] .= '<span class="token-description">' . $token_info['description'] . '</span>';
  }

  return $row;
}`

I'll try to make the PR, but still dealing with git newbie staff

**Comment by robertgarrigos** [comment]
Done my first PR: https://github.com/backdrop/backdrop/pull/1895

Hope it's ok.

**Comment by olafgrabienski** [comment]
@robertgarrigos I've had a look at your PR. Don't have the skills to review the code, but I can confirm that the Token browser on `admin/config/urls/path/patterns` works again on the sandbox site of the PR.

**Comment by olafgrabienski** [comment]
PS: Can you put the link to your PR in the description of this issue as well? Something like "PR of @robertgarrigos : {Link to the PR}". Doing so helps finding PRs when issue threads get longer.

**Comment by robertgarrigos** [comment]
Thanks, @olafgrabienski. Done.

**Comment by serundeputy** [comment]
I can not replicate this problem.  On HEAD of `1.x` commit `8733ed1e6e8f09fa2e3a1a19209f3c789143ae80` token browser works for me at `admin/config/urls/path/patterns` and I can insert and save tokens.

@robertgarrigos @olafgrabienski can you replicate the problem on latest `1.x`?

If so we need to identify the difference in either steps or environment set ups.

**Comment by docwilmot** [comment]
Also couldnt replicate

**Comment by olafgrabienski** [comment]
@serundeputy Sorry, no time available at the moment :-/

**Comment by robertgarrigos** [comment]
```
$ git checkout core/1.x
Note: checking out 'core/1.x'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8733ed1... Reverting version string.
robert@barcelonabagels ~/dev.backdrop ((8733ed1...)) $ 
```
and still having this issue
```
[Wed May 17 21:01:02.369286 2017] [php7:notice] [pid 15342] [client 88.0.75.129:59341] PHP Error:  Cannot use string offset as an array in /home/robert/dev.backdrop/core/modules/system/system.theme.inc on line 692, referer: http://dev.backdrop.cat/admin/config/urls/path/patterns
```

**Comment by robertgarrigos** [comment]
After the checkout i have the _token_token_tree_format_row() function as i shown in my first comment. The elements of the array are wrong.

**Comment by serundeputy** [comment]
Thanks @robertgarrigos that was the missing component.  It was working for me on `PHP 7.0.14` switched to `PHP 7.1.1` and the token browser fails to open.

**Comment by robertgarrigos** [comment]
thanks @serundeputy I was starting to think I did something wrong (again...) ;-)

**Comment by robertgarrigos** [comment]
In any case, those arrays don't look right for me, even for a previous version of php

**Comment by serundeputy** [comment]
PR https://github.com/backdrop/backdrop/pull/1895 is working for me on `PHP 5.5.38`, `PHP 5.6.29`, `PHP 7.0.14`, and `PHP 7.1.1` on `admin/config/urls/path/patterns`.

nice work @robertgarrigos !

Are there any other places in core we use tokens that I/we can test.

**Comment by serundeputy** [comment]
Token browser working correctly with `admin/structure/types/manage/post/fields/field_image` and `admin/structure/types/manage/page` as well!

**Comment by serundeputy** [comment]
@robertgarrigos this also works:

```php
  static $defaults = array(
    'id' => '',
    'class' => array(),
    'data' => array(
      'name' => array(),//'',
      'token' => array(),//'',
      'value' => '',
    ),
  );
```

which is more inline with this drupal patch: http://cgit.drupalcode.org/token/patch/?id=6fa49e98a450f6df34f9e1ab9abea1721b105085

@quicksketch any thoughts about which way is preferred?

**Comment by quicksketch** [comment]
The root of this seems to be in a change in PHP 7.1.0 [array handling](http://php.net/manual/en/language.types.array.php):

> Note: As of PHP 7.1.0, applying the empty index operator on a string throws a fatal error. Formerly, the string was silently converted to an array. 

That silent conversion is what was happening previously. Just instantiating the empty array directly as @serundeputy suggests seems like the lowest-impact solution. We should always be doing that anyway to avoid ambiguity.

**Comment by serundeputy** [comment]
thanks @quicksketch 
@robertgarrigos  up for updating or filing a new PR?

**Comment by robertgarrigos** [comment]
Yep. Let me get back from vacations...just a couple of days more

**Comment by robertgarrigos** [comment]
Done new PR

**Comment by serundeputy** [comment]
Great work @robertgarrigos ! Thanks for sticking with it!
Thanks @olafgrabienski, @docwilmot, and @quicksketch  for testing and reviewing.
This will ship with the `1.7.1` release!
