### ISSUE TITLE
How can I create more formatting buttons for Ckeditor

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2699]
## Describe your issue or idea

I would like to include such formatting buttons as `code` and `pre` in the styles of the ckeditor.

I know that when I edit text formats and Full HTML, there is a text field there for it. How should these styles be called when it comes to code and pre-tags.

Thanks in advance.

I use since today on Backdrop 1.7.0 and the editor has too few formatting possibilities.

**Comment by BWPanda** [comment]
Wow, sorry for missing this @AlexL777!

Hopefully you worked something out in the meantime, but if not (and for those coming across this in future) here's an issue that I think addresses what you're wanting: https://github.com/backdrop/backdrop-issues/issues/2980

If not the issue/feature itself, then at least in the comments you should get an idea how to use the Styles option for custom code/tags...

Will mark this as a duplicate, but feel free to post back here if you still need help with this.
