### ISSUE TITLE
[UX] Maintenance mode message: add destination to the "Go online" link and make sure it's a warning.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2701]
## Describe your issue or idea

As per issue title^^

### Steps to reproduce

1. Navigate to `admin/config/development/maintenance` and set the site to maintenance mode. Notice how the "The site is now in maintenance mode ..." message is a warning:

    ![image](https://cloud.githubusercontent.com/assets/2423362/26197331/2b7563cc-3c05-11e7-9d83-0ec472b1be38.png)

2. Navigate to any other admin section of the site. Notice how "Operating in maintenance mode." is now a green status message:

    ![image](https://cloud.githubusercontent.com/assets/2423362/26197426/7a6e3bb6-3c05-11e7-921b-85ef8b6de8c0.png)

### Actual behavior

1. The "Operating in maintenance mode." message is a green status.
2. The user starts from a certain page, is lead to the "Maintenance mode" page to turn the site back online, but is not redirected back to where they started.

### Expected behavior

1. The "Operating in maintenance mode." message should be a warning.
2. When taking the site back online, the user should be redirected back to the page where they started from.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1901

**Comment by Dinornis** [comment]
Thank you klonos, nice improvement.
While everything seems to be working fine from the user perspective, running `Site Maintenance Mode Functionality` tests reports 3 fails and 6 exceptions:

**Message:** `FAIL: "Operating in maintenance mode." found`
**Filename:** `system.test` Line: `1120`
**Function:** `SiteMaintenanceTestCase->testSiteMaintenance()`

**Message:** `FAIL: "Operating in maintenance mode." found`
**Filename:** `system.test` Line: `1163`
**Function:** `SiteMaintenanceTestCase->testSiteMaintenance()`

**Message:** `FAIL: "Operating in maintenance mode." found`
**Filename:** `system.test` Line: `1197`
**Function:** `SiteMaintenanceTestCase->testSiteMaintenance()`

**Message:** `EXCEPTION: Undefined variable: destination`
**Filename:** `menu.inc` Line: `4003`
**Function:** `_menu_site_status()`

**Comment by quicksketch** [comment]
Added a commit to the PR that fixes the notices and test failures (just updating the test to match the new text). If it passes this should be good to go. https://github.com/backdrop/backdrop/pull/1901

**Comment by olafgrabienski** [comment]
Tests on the PR passed. Had a look at the new behavior which works fine, and there were no notices in the DBlog.

**Comment by quicksketch** [comment]
Thanks @olafgrabienski for the review! I've merged https://github.com/backdrop/backdrop/pull/1901 into 1.x and 1.7.x. Thanks @klonos for this improvement!
