### ISSUE TITLE
Can not upgrade from 1.6.3 to 1.7.0

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2702]
url: /core/update.php?op=selection&token=_oqPLt1LK_Z4CtBNTj4A8i08ZzGvL3oSZz8tHC5CvBI

Backdrop database update

Status message No pending updates.
Error message
Warning: Illegal offset type in isset or empty in BackdropCacheArray->offsetGet() (line 368 of /core/includes/bootstrap.inc).
Warning: array_key_exists(): The first argument should be either a string or an integer in BackdropCacheArray->offsetGet() (line 368 of /core/includes/bootstrap.inc).
Warning: Illegal offset type in isset or empty in SchemaCache->resolveCacheMiss() (line 3680 of /core/includes/bootstrap.inc).
Warning: Illegal offset type in SchemaCache->resolveCacheMiss() (line 3681 of /core/includes/bootstrap.inc).
Warning: Illegal offset type in BackdropCacheArray->persist() (line 406 of /core/includes/bootstrap.inc).
Warning: array_keys() expects parameter 1 to be array, null given in backdrop_schema_fields_sql() (line 7867 of /core/includes/common.inc).
Warning: Illegal offset type in isset or empty in BackdropCacheArray->offsetGet() (line 368 of /core/includes/bootstrap.inc).
Warning: array_key_exists(): The first argument should be either a string or an integer in BackdropCacheArray->offsetGet() (line 368 of /core/includes/bootstrap.inc).
Warning: Illegal offset type in isset or empty in SchemaCache->resolveCacheMiss() (line 3680 of /core/includes/bootstrap.inc).
Warning: Illegal offset type in SchemaCache->resolveCacheMiss() (line 3681 of /core/includes/bootstrap.inc).
Warning: Illegal offset type in BackdropCacheArray->persist() (line 406 of /core/includes/bootstrap.inc).
Warning: array_keys() expects parameter 1 to be array, null given in backdrop_schema_fields_sql() (line 7867 of /core/includes/common.inc).
Front page

**Comment by jenlampton** [comment]
What version of PHP are you running?

**Comment by bd0bd** [comment]
Well, probably some modules are the reason of this problem.

I have uninstalled and deleted some modules and now everything is ok.

Not sure but may be this happened because of the system module - I have copied it to the /modules folder. Why? Because I need custom header template.

**Comment by jenlampton** [comment]
> Why? Because I need custom header template.

You should copy the `header.tpl.php` file to your theme and keep the changed version there. Template files exist so they can be changed in this way - there should be no reason to modify anything in the core modules directly (unless you are fixing a bug). When change those files, problems like this will occur.

**Comment by bd0bd** [comment]
I see. Thank you!
