### ISSUE TITLE
Configurable registration form

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2706]
Why to force  new users to type in email and confirm password when registering?
This is additional headache for users.
I do not want to create problems for my users.
2 fields are enough - username and password.

Why there is no options to select only the necessary fields in the Account settings `admin/config/people/settings`

:smile:

**Comment by klonos** [comment]
Thank you for filing this issue @bd0bd 👍. This has actually been in my mind for some time now. There is a trend lately in various websites as well as in mobile apps to be replacing the password confirmation field with a show/hide toggle. There's quite a few articles about it on the net and some usability studies too. One such article is this: http://uxmovement.com/forms/why-the-confirm-password-field-must-die

![text-button-toggle](https://cloud.githubusercontent.com/assets/2423362/26266970/29eb73b2-3d2b-11e7-97d7-459231a58a43.png)

![eye-icon-toggle](https://cloud.githubusercontent.com/assets/2423362/26266977/2ea3a64a-3d2b-11e7-8339-7c6c934e6b85.png)

**Comment by bd0bd** [comment]
> There is a trend lately in various websites

This is not a new option.
I did it for my website in 2012.
J. Nielsen has wrote about this in 2009 - Stop Password Masking - https://www.nngroup.com/articles/stop-password-masking/

**Comment by bd0bd** [comment]
> Consider replacing the **confirm password** field with a show/hide toggle.

Consider replacing the **confirm password** and **e-mail** fields with a show/hide toggle.

**Comment by bd0bd** [comment]
![img_20170520_002857](https://cloud.githubusercontent.com/assets/13515302/26267567/9628f032-3cf3-11e7-8d0a-acd798876e04.JPG)

![img_20170520_003017](https://cloud.githubusercontent.com/assets/13515302/26267576/a3c8cb90-3cf3-11e7-9f58-7e1d83059f50.JPG)

**Comment by bd0bd** [comment]
**Another reason why to hide e-mail address field**

Because there are a lot of people who would not like to show you e-mails, credit cards and another personal information.
We should respect users privacy.

If a user would like to type in e-mail then he/she can do it in the users profile settings.

**Comment by klonos** [comment]
Sorry @bd0bd. I filed a separate issue for my suggestion and moved my comments there: #2707 

You are asking for two different things in one issue here:

1. To hide the password confirmation field. This will be discussed in #2707 
2. To provide an option to make email optional instead of required when registering user accounts.

Should we keep this issue about the second thing only?

**Comment by klonos** [comment]
In Drupal, you could make the email field optional using https://www.drupal.org/project/optional_mail. If this module is ported to Backdrop, then it would satisfy your use case. What worries me about introducing such a feature in core would break other core things. From that module's description:

>This module must be used in very specific cases. Consequently, it might possibly cause problems with some Drupal features, such as the user's personal contact form and the e-mail checking of new user accounts (this feature is disabled by this module, by the way).

So I'm really worried about the implications. Lets wait for more feedback.

**Comment by bd0bd** [comment]
Yes, I use this module on my Drupal site.

**Comment by klonos** [comment]
...also, this makes it a feature request and certainly not a UX task.

**Comment by bd0bd** [comment]
OMG!
I talk about 2 fields and not about only email field.
This is important.

Why to change the title ...

**Comment by bd0bd** [comment]
I think people should have a right to configure the registration form.
Like in the Webform.

**Comment by klonos** [comment]
This is related: #2669 

@bd0bd perhaps language is a barrier here, but I honestly did not mean to upset you. Sorry, but you are asking for two different things using a single ticket. It is better to break them down to smaller tasks that we can decide and act upon:

1. Use one field for password: this will be decided in #2707 
2. Make the email optional on registration: this issue here

Does that make sense?

**Comment by klonos** [comment]
Sorry @bd0bd just to reassure you that I did not mean to hijack your ticket, I have created a separate issue for making the email field optional on the registration form: #2708

I am re-instating the original title of this issue.

**Comment by klonos** [comment]
I should not have responded in the first place. Apologies.

**Comment by klonos** [comment]
I think that having the freedom to configure the site registration form field is very valuable. [Webform has already been ported](https://github.com/backdrop-contrib/webform), the only think remaining is to port https://www.drupal.org/project/webform_register and you would be able to achieve this @bd0bd

**Comment by Graham-72** [comment]
> 2 fields are enough - username and password.
> If a user would like to type in e-mail then he/she can do it in the users profile settings.

I would not like this for the users of my site where I need to know that the person applying to use the members-only section of the site is already a member of the club. So yes to making the registration form configurable, no to just removing the email field.

**Comment by bd0bd** [comment]
> So yes to making the registration form configurable, no to just removing the email field.

I talk only about the reg form to be configurable.
I do not say anythings about total removing e-mail field

@klonos, there are problems with Webform Register and the developer does not have a time to fix it (he wrote me in 2016).

Anyway, I mean incore reg form configuration, without any additional modules.

**Comment by jlfranklin** [comment]
This can be easily done in a contrib module with `hook_form_alter()` and a couple other hooks.  Putting a change like this into core would break modules like LoginToboggan and potentially other modules that alter the login form.  For these two reasons, I think it would be best to keep the login page simple and make this feature request a contrib module.

**Comment by bd0bd** [comment]
@jlfranklin, I understand you.
But **registration form** is an important part of a website.
It is not a minor attribute/element.
In one my project it is a key thing on the front page (kind of GitHub front page).
I am sure anyone who operate a website for users would like to have a possibility to configure the registration form.

Sometimes I am forced to go back to Drupal because Backdrop has no basic things for users.

**Comment by jlfranklin** [comment]
>  I think anyone who operate a website for users would like to have a possibility to configure the registration form.

All of which can be done with a contrib module.  [LoginToboggan](https://github.com/backdrop-contrib/logintoboggan) is one such module that makes several different changes to the registration form and the login form.  These registration form changes can be made with a contrib module, too.

**Comment by bd0bd** [comment]
I have installed it but I do not see these options in this module.
1. To hide email field
2. To hide confirm password field

**Comment by bd0bd** [comment]
/admin/config/people/logintoboggan

![img_20170521_205717](https://cloud.githubusercontent.com/assets/13515302/26286204/2e1dcb5e-3e68-11e7-9f48-4d1009b94857.JPG)

**Comment by bd0bd** [comment]
> All of which can be done with a contrib module. LoginToboggan is one such module

Sorry to say but this module can not do the things I am talking about in this issue: _hiding **e-mail** and **confirm password** fields_.

**Comment by BWPanda** [comment]
@bd0bd You mention hiding the email field from the registration form. You also state that you're not talking about removing it altogether, and that users should be able to enter an email in their profile later on.

As email is a required and heavily integrated field for user accounts, making it optional/hidden at registration time is not trivial. You can't have a required field that's hidden from the registration form (unless you somehow provide a default value, but then where does that come from?) So what you're asking is basically only possible by making the email field optional. There's a contributed module for that, and a separate issue linked above for discussing adding that to core. If you still want users to add an email address later on in their profile, you could simply make a new email field that's only shown on the profile form and leave it up to users to add that themselves later.

**Comment by BWPanda** [comment]
And core has now removed the 2nd password (confirm) field. So is this still an issue...?

**Comment by klonos** [comment]
I guess that the only remaining issue here is to have a way to make the email field optional, and be able to remove it from the form.

There has not been any other request for this in over 2 years, so not an 80% use case. This should be left to contrib, which means porting https://www.drupal.org/project/optional_mail. There's already a request for that here: https://github.com/backdrop-ops/contrib/issues/173 (although again, no interest in 2 years).

I think that it is safe to close this issue here.
