### ISSUE TITLE
[UX] Consider replacing the confirm password field with a show/hide toggle.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2707]
This has actually been in my mind for some time now. There is a trend lately in various websites as well as in mobile apps to be replacing the password confirmation field with a show/hide toggle. There's quite a few articles about it on the net and some usability studies too. One such article is this: http://uxmovement.com/forms/why-the-confirm-password-field-must-die

![text-button-toggle](https://cloud.githubusercontent.com/assets/2423362/26266970/29eb73b2-3d2b-11e7-97d7-459231a58a43.png)

![eye-icon-toggle](https://cloud.githubusercontent.com/assets/2423362/26266977/2ea3a64a-3d2b-11e7-8339-7c6c934e6b85.png)

There are two places where we currently require a password and have a confirm password field along with that:

- During installation for the admin password
- During user registration

**Comment by bd0bd** [comment]
Your offer is to use 2 fields?
Or 1 field with hide/show option?

1 field is enough :smile:

**Comment by bd0bd** [comment]
Well, I talk only about user registration form.

**Comment by klonos** [comment]
Only one field instead of two 😄

**Comment by serundeputy** [comment]
dupe: https://github.com/backdrop/backdrop-issues/issues/297
we should close.

**Comment by klonos** [comment]
Yes, it is. Told you, I'm starting to lose my touch 😞 Sorry.
