### ISSUE TITLE
[UX] "View site reports" Permission does not grant access to Status/Update reports

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2711]
## Describe your issue or idea

There is a permission for "View site reports" yet when I assign this permission, my user cannot access the status report or the Available updates report. They both use the "administer site configuration" permission instead. 

We should change the status report and the Update Manager report to use the "View site reports" permission. Any links on those reports that may be dangerous should have their own permissions.

### Steps to reproduce (if reporting a bug)
* Grant a role the "View site reports"  permission
* Visit the status report

### Actual behavior (if reporting a bug)
* Access denied

### Expected behavior (if reporting a bug)
* able to view the Status report

### Relevant version/system information (if applicable)

----
PR: https://github.com/backdrop/backdrop/pull/1905

**Comment by serundeputy** [comment]
Sandbox Website: http://1905.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: 33jUvmhN

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1905 into 1.x and 1.7.x. Thanks!
