### ISSUE TITLE
[UX] Rearrange tabs at /user/login

### ISSUE THREAD

**Issue by bd0bd** [backdrop/backdrop-issues#2712]
/user/login

Now we have:

1. Create new account
2. Log in
3. Reset password

I offer to rearrange like in Drupal 8:

1. Log in
2. Create new account
3. Reset password

And may be to reword **Create new account** to **Create an account**.

**Comment by BWPanda** [comment]
It looks like we're rather in favour of removing the tabs altogether: https://github.com/backdrop/backdrop-issues/issues/3309

Closing as a duplicate.
