### ISSUE TITLE
hook_block_view_alter() is only called for legacy blocks.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2713]
While working with block_refresh module, I noticed that the `$block` we passed into `hook_block_view_alter()` for legacy blocks was not a real `Block` class block, so didn't have settings or context or even the UUID included. It was only an `(object)` version of an array of the module name and delta. 

While trying to track down what it was for non-legacy blocks, it became clear that `hook_block_view_alter()` wasn't called at all! It was only being called on legacy blocks.

The PR provided attempts to fix `hook_block_view_alter()` so that it is called for all blocks. There will be a small API change that removes the passing along of settings and context for the block --
 since those never worked before anyway.  Those values will now be included in the `$block` object after this change.

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1906
Change notice: https://api.backdropcms.org/node/44981

**Comment by quicksketch** [comment]
Thanks @jenlampton! PR contains some unrelated changes, could you reroll? https://github.com/backdrop/backdrop/pull/1906#pullrequestreview-44704075

Overall, this looks like a great suggestion. The current behavior is definitely broken: there's no way to alter any blocks other than legacy ones. And the way the hook works for legacy ones is incorrectly documented. Fixing both at once would be great.

**Comment by jenlampton** [comment]
Rebased and pushed updated PR

**Comment by jenlampton** [comment]
Removed all the unrelated changes and pushed a new commit. Ready for another review.

**Comment by klonos** [comment]
Gave the PR a quick look. I don't have any constructive comments. Reading the change notice could help me understand, but unfortunately, I don't have access to view unpublished content on api.b.org. Can someone please help with that?

Thanks in advance :)

**Comment by jenlampton** [comment]
@klonos you should be able to see them now :)

**Comment by jenlampton** [comment]
@opi thanks for looking at this PR. I reviewed the site where I had discovered this bug and sure enough, the new call to `hook_block_view_alter()` was missing from this PR.  I've added it back now, and this issue is ready for a new review.

**Comment by opi** [comment]
reviewed: https://github.com/backdrop/backdrop/pull/1906#pullrequestreview-59215768

**Comment by quicksketch** [comment]
Thanks @opi! Merged https://github.com/backdrop/backdrop/pull/1906 into 1.x for 1.8.0. I've published the change notice as well, thanks for writing that up @jenlampton.

**Comment by quicksketch** [comment]
Due to the API change, I'm moving this to be 1.8.0 only. Change notice has been updated to reflect the correct version: https://api.backdropcms.org/node/44981
