### ISSUE TITLE
[UX] Keep module filter in place after page reload

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2715]
When you filter the list of modules at /admin/modules (e.g. to find a specific module you just downloaded), then enable it and Save, the page reloads but the filter is reset. So to find that module again (to see if there's any permissions or configure links), you have to re-type in the filter. That's annoying and, I believe, unnecessary.

### Steps to reproduce
1. Go to the Modules page (/admin/modules)
2. Enter 'lang' in the filter field
3. Tick to enable the Language module
4. Scroll down and click 'Save configuration'

### Actual behavior
The page reloads and all modules are shown, with the 'lang' filter having been reset. The newly-enabled module(s) is lost among the rest of them.

### Expected behavior
The 'lang' filter still being in place, therefore being able to easily access any permissions or configuration for the newly-enabled module(s) (without having to scroll or re-filter to find it).

Not sure if there's another issue about this already (apologies if so).

----
~~PR: vy @serundeputy  https://github.com/backdrop/backdrop/pull/1907~~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1994

**Comment by serundeputy** [comment]
QC Sandbox:
Website: http://1907.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: AuSSW8k5

**Comment by quicksketch** [comment]
Thanks @serundeputy! Needs a little work yet: https://github.com/backdrop/backdrop/pull/1907#pullrequestreview-52778465

**Comment by serundeputy** [comment]
Thanks @quicksketch 
PR updated and rebased.

**Comment by jenlampton** [comment]
@serundeputy it looks like there are some PHP notices. Can you check those out?

**Comment by jenlampton** [comment]
I pushed a new PR that should prevent the PHP notices. I tested this and I think this is a great improvement, thanks @serundeputy !

**Comment by laryn** [comment]
This looks good to me.

**Comment by olafgrabienski** [comment]
I had a look at the sandbox site of the new PR, and the module filter works as expected: A chosen filter was still place after I had enabled a module.

Btw, didn't see any PHP notices.

**Comment by olafgrabienski** [comment]
So, RTBC?

**Comment by olafgrabienski** [comment]
@jenlampton via Gitter: 

> woohoo! thanks  can you mark it rtbc?

Done!

**Comment by quicksketch** [comment]
The functionality and implementation in the PR is great! Good job!

Unfortunately we have a PHP notice introduced that is mentioned in the test results:

https://github.com/backdrop/backdrop/pull/1994#pullrequestreview-63194465

Could we get a quick re-roll?

**Comment by jenlampton** [comment]
> Could we get a quick re-roll?

on it.

**Comment by jenlampton** [comment]
I pushed a fix for the PHP notice. testing now.

**Comment by quicksketch** [comment]
Thanks! I've merged https://github.com/backdrop/backdrop/pull/1994 into 1.x for 1.8.0. Great job everybody!
