### ISSUE TITLE
Adding the description field for custom blocks.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2716]
Has something changed with release 1.7.0? I have previously entered some custom descriptions for custom blocks. The descriptions are still there, but I cannot see how or where to edit them, nor have I been able to find where they are stored (not in config it seems).

**Comment by Graham-72** [comment]
I haven't yet figured out why things seem to have changed but I have worked out a fix to the blocks module that will enable me to add and display a description of each of my custom blocks so that there is better guidance for a site editor. The listing now looks like this
![custom blocks](https://cloud.githubusercontent.com/assets/10559274/26654143/90d533f8-464d-11e7-9a74-49761a9668bc.png)

Once I am sure this works I will create a PR.

**Comment by Graham-72** [comment]
There is another problem but with descriptions for blocks provided by views. I have previously added descriptions for their use in layouts and these still exist but now I cannot edit them, nor can I find where they are stored.

**Comment by klonos** [comment]
@Graham-72 unless the description column is something you have added with your changes, I don't see it in an 1.6.3 local instance I have handy and I don't see it in 1.7.0.

**Comment by Graham-72** [comment]
@klonos it is something that I have added in my code and intend to propose a PR soon. Interestingly the description field is mostly there in the existing code. I am trying to understand what has happened but don't now have a 1.6.3 instance handy so I am building one now.

**Comment by Graham-72** [comment]
I now realise that there are two separate issues here, one relating to custom blocks, the other to blocks created by views. So I have opened two new issues, #2722 and #2723 in order to address these individually, and am closing this issue.
