### ISSUE TITLE
OpenSUSE 42.2 PHP .zip extension error

### ISSUE THREAD

**Issue by sacredsunder** [backdrop/backdrop-issues#2717]
When trying to install a module or theme via admin/appearance/install or admin/modules/install I get an error:"Sorry, it seems that the PHP .zip extension is not loaded on your server. You will not be able to download any projects using Project Installer until this is fixed. Please contact your website administrator."

I have tried this in both PHP5 and PHP7 with the php7-zip and php5-zip installed and enabled. When viewing admin/reports/status/php it states that the zip extension is enabled. No related errors show in /admin/reports/dblog

Not sure if related, but I have a similar situation with cURL being enabled but failing the Clean URL Test.

Backdrop 1.7.0, PHP 5.5.14 (looking to move back to 7 when deploying) MariaDB 10.0.29

**Comment by sacredsunder** [comment]
Was able to clear the PHP .zip extension error by flushing all caches. Still getting permissions error though. Not sure which permissions are being referenced.

Was able to work around the cURL error by visiting /admin/config/urls/settings, and clicking Enable clean URLs. This checkbox would not show on the page using ?q=/admin/config/urls/settings. Still fails the Clean URL Test even though it is now working.

**Comment by jasin** [comment]
I am having a similar problem with zip, how are you flushing the cache?

**Comment by jasin** [comment]
I found it, wasn't very intuitive given the description of the page
Now I see the big 'clear all cache' button once I went to the page. 

This also fixed the error for me and I can now download and install themes, layouts, etc from the web interface.

**Comment by jenlampton** [comment]
@sacredsunder Were all the necessary PHP extensions installed at the time Backdrop was installed, or were they enabled afterward? If afterward I expect the problem might be cache related (as @jasin suggests) but if not there could be something else going on.

**Comment by klonos** [comment]
We've had a more recent report about this error in the forum, and #3978 was filed to deal with this problem. I will go ahead and close this issue in favor of the newer one.
