### ISSUE TITLE
Image style config names have json extension

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2724]
All default configs must have a `"_config_name"` key which for every other module does not include a `.json` extension.
Example: 
`"_config_name": "image.style.large.json",` vs
`"_config_name": "language.settings",`

**Comment by opi** [comment]
Changing `_config_name` in default configuration located in `core/modules/image/config/image.style.*` is easy, but I wonder what are the consequences on existing Backdrop site.

From my test, even if Default configuration has `"_config_name": "image.style.large.json"`, my exported configuration without changing anything to the *large* image style has a clean `"_config_name": "image.style.large"`.

So maybe it's just the default configuration to fix. I Will provide a basic pull request to start.

**Comment by klonos** [comment]
...I confirm @opi's finding: on a fresh installation, all the `image.style.*.json` file have proper (`.json`-less) `_config_name` entries. RTBC 👍

**Comment by quicksketch** [comment]
Great, thanks! Seems like this typo doesn't have any reaching impact, but would be great to fix anyway. Merged into 1.x and 1.7.x.
