### ISSUE TITLE
Notice: Undefined variables in page-components.tpl.php

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2734]
## Describe your issue or idea

After placing the "page title" block on a custom layout, I see the following error:
```
Notice: Undefined variable: messages in include() (line 30 of backdrop/core/modules/system/templates/page-components.tpl.php).
Notice: Undefined variable: title in include() (line 36 of backdrop/core/modules/system/templates/page-components.tpl.php).
Notice: Undefined variable: tabs in include() (line 40 of backdrop/core/modules/system/templates/page-components.tpl.php).
Notice: Undefined variable: action_links in include() (line 46 of backdrop/core/modules/system/templates/page-components.tpl.php).
```

### Steps to reproduce (if reporting a bug)
1) Create a new custom layout using the boxton template
2) Add a "Page title" block to the content region
3) save the layout
4) view the page
5) reload the page a few times

### Actual behavior (if reporting a bug)
errors shown on all page loads that are not immediately following cache clears. After cache clears, no errors are shown.

### Expected behavior (if reporting a bug)
no errors

### Relevant version/system information (if applicable)
Backdrop core 1.7.0+

--- 
PR https://github.com/backdrop/backdrop/pull/1911

**Comment by jenlampton** [comment]
It looks like the problem is that `system_preprocess_page_components` is not called for the title block. I think this function should have been `template_preprocess_page_components`.

**Comment by jenlampton** [comment]
Changing the function name doesn't seem to prevent the errors in call cases. Marking NW.

**Comment by jenlampton** [comment]
Things like the page title and messages may not be available this early in the render pipeline (when preprocess is called for the content of a block). 

Before 1.7.0, they were loaded as the last possible thing before the layout was rendered, and that itself was after all the blocks were rendered. Did we account for that timing when the new page title blocks were added? 

If so, when does this "preprocess" function run? Is there some special magic that makes it run at the correct time (instead of with the other blocks) and could that be failing us here?

**Comment by docwilmot** [comment]
I cant reproduce this. I created a new layout at path 'boxton', added titel block, visited page, no error; created new layout at path 'node/%', added title block, visted page, block shows, no error. Perhaps there's a missing step?

**Comment by jenlampton** [comment]
I can't reproduce this on a fresh install either. Perhaps it was my upgraded website. Closing for now, will reopen if the problem reappears.

**Comment by behindthepage** [comment]
I had the same problem on a recent site and I found it only occurred when I had "Page Tabs (Local tasks)" as a block and I used the Body field block instead of the main Content block. When I removed the Pages tabs and used the Main Page Content block the errors went away. I ALSO couldn't replicate the problem on a fresh install. Very strange.
