### ISSUE TITLE
[UX] Rename "Add text editor" to "Add text format"

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2736]
To add a text format to Backdrop, you go to the *Text editors and formats* page (`admin/config/content/formats`) and have to click on the action link "Add text editor". This terminlogy is confusing because you might want to add a text format which doesn't use an editor.

### Actual behavior (if reporting a bug)

The action link is called "Add text editor"

### Expected behavior (if reporting a bug)

The link name should be "Add text format"

---
PR by @alexfinnarn: https://github.com/backdrop/backdrop/pull/2260

**Comment by alexfinnarn** [comment]
Yes, I was just going to file an issue about this. I will make a PR.

**Comment by olafgrabienski** [comment]
Great, looks good, thank you! RTBC from me. I'm also going to set a milestone for the next bugfix release.

**Comment by klonos** [comment]
I am not opposed to this, but we still call these things "editors" in the WYSIWYG "Formatting options"

<img width="565" alt="screen shot 2018-08-03 at 4 03 12 pm" src="https://user-images.githubusercontent.com/2423362/43626832-e65d07c0-9736-11e8-846b-3849d68e3894.png">

**Comment by olafgrabienski** [comment]
> we still call these things "editors" in the WYSIWYG "Formatting options"

Good catch! So let's change the label as well, just "Format" instead of "Editor"?

**Comment by olafgrabienski** [comment]
@quicksketch Thanks for the feedback! Do you prefer "Editor" in the *Formatting options* section (visible for content-creators), or are you more generally against the scope of the issue (rename "Add text editor" to "Add text format", for site builders)?

**Comment by quicksketch** [comment]
I like "Editor" for content creators specifically. And then "Add text editor" was changed just to match to make it consistent in both places. My preference would be to leave things as they are in both places. But that's only my personal preference.

**Comment by olafgrabienski** [comment]
> And then "Add text editor" was changed just to match to make it consistent in both places.

The intention to change "Add text editor" was because there are text formats which don't use an "Editor" at all: "Full HTML" and "Plain text". See the "Editor" row on the *Text editors and formats* page, there is explicitly displayed: "Editor: None". In my opinion, it's confusing to see (or to add) an "Editor" without an "Editor".

**Comment by quicksketch** [comment]
I'm willing to concede, though eventually the inconsistency will be noted and then we'll have to change it in both places :yum: 

Merged in https://github.com/backdrop/backdrop/pull/2260 into 1.x and 1.11.x. Thanks!
