### ISSUE TITLE
[UX] Align the operations dropbuttons to the left (right for RTL).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2740]
## Describe your issue or idea

This has actually been on my mind for some time now. I've been using Backdrop for so long that I had forgotten that this was actually how things were in D7 Views UI:

![image](https://user-images.githubusercontent.com/2423362/27252615-82902f08-53a6-11e7-9f7a-70ce82f84b8d.png)

...and I just noticed that it this is how it's implemented in D8:

![image](https://user-images.githubusercontent.com/2423362/27252623-a40e35bc-53a6-11e7-8954-32bb1859fddc.png)

It makes more sense visually to me than what we do.

### Steps to reproduce (if reporting a bug)

Navigate to `/admin/config/content/formats`...

### Actual behavior (if reporting a bug)

![image](https://user-images.githubusercontent.com/2423362/27252633-c3c1fc4a-53a6-11e7-9bb2-e4e0fdb4db8f.png)

### Expected behavior (if reporting a bug)

![image](https://user-images.githubusercontent.com/2423362/27252704-2d1b3764-53a8-11e7-8dee-37981ffedb81.png)

---
~PR by @klonos: https://github.com/backdrop/backdrop/pull/1944~
PR update by @quicksketch: https://github.com/backdrop/backdrop/pull/1953

**Comment by klonos** [comment]
I have filled a PR. Not ready for review yet, as I just noticed that it breaks the dropbutton positions in the Views UI. It fixes other places though where the dropbutton position was weird. For example, this:

![image](https://user-images.githubusercontent.com/2423362/27253187-3b8f947e-53b3-11e7-9d81-9b60b8e5cfb8.png)

...not becomes like so:

![image](https://user-images.githubusercontent.com/2423362/27253195-6737b0de-53b3-11e7-8d85-b384de8d9b7e.png)

Still not ideal (should also adjust the "Operations" column width), but better than before IMO.

**Comment by klonos** [comment]
I have added the change from https://github.com/backdrop/backdrop-issues/issues/2741 to this PR as it is required in order to fix the positions of the "add" dropbuttons in the Views UI.

**Comment by opi** [comment]
corresponding PR is backdrop/backdrop/pull/1914

**Comment by klonos** [comment]
Thanks for the review @opi ...unfortunately, as previously mentioned, this PR included [a change](https://github.com/backdrop/backdrop/pull/1914/commits/c04eba0203f34fcffdd66fe038652eef934cda45) from #2741 which has already been merged separately.

I'll quickly file a separate PR...

**Comment by klonos** [comment]
@opi care for a second quick code review please?: https://github.com/backdrop/backdrop/pull/1944

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/1944#pullrequestreview-54639360 approved.

**Comment by quicksketch** [comment]
Thanks @opi and @klonos! This has actually long been an objective for me, but I couldn't figure out how to get it working!

I've merged the PR at https://github.com/backdrop/backdrop/pull/1953 into 1.x and 1.7.x. Thanks!

**Comment by jenlampton** [comment]
This seems to have broken drop-buttons all over the place. Can we please revert this commit and revisit?

**Comment by quicksketch** [comment]
We have fixed this regression in a new issue: https://github.com/backdrop/backdrop-issues/issues/2806
