### ISSUE TITLE
[DX] Add a "dropbutton-single" class to dropbuttons with single items.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2741]
## Describe your issue or idea

We only add `dropbutton-multiple` to non-single dropbuttons. Adding `dropbutton-single` to single-item dropbuttons will make it easier for themers to target them. D8 has these classes added by the way:

![image](https://user-images.githubusercontent.com/2423362/27252992-33ec52e8-53ae-11e7-92df-d6284ede69d7.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1913

**Comment by quicksketch** [comment]
Thanks @klonos! A very simple addition and a good idea. Merged https://github.com/backdrop/backdrop-issues/issues/2740 into 1.x and 1.7.x.
