### ISSUE TITLE
Whitespace issue on 'Available updates' page

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2744]
There's a whitespace issue on the 'Available updates' page, specifically the lack of any space between 'Backdrop 1.7.0' and 'Includes: Contact, Entity, ...'.

![firefox_screenshot_2017-06-19t06-32-09 440z](https://user-images.githubusercontent.com/2385329/27272298-dc401bfa-550c-11e7-923f-3f131fb6e4bc.png)

I'm running Backdrop 1.7.0 with Seven 1.7.0.

----
~PR: https://github.com/backdrop/backdrop/pull/1916~
PR: https://github.com/backdrop/backdrop/pull/1940

**Comment by serundeputy** [comment]
Website: http://1916.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: zpZNfzwP

http://1916.backdrop.backdrop.qa.backdropcms.org/admin/reports/updates

**Comment by opi** [comment]
Website: http://1940.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: 8koypNtu

http://1940.backdrop.backdrop.qa.backdropcms.org/admin/reports/updates

**Comment by BWPanda** [comment]
Out of the two, I like @opi's fix better...

**Comment by quicksketch** [comment]
Thanks! I've merged @opi's https://github.com/backdrop/backdrop/pull/1940 into 1.x and 1.7.x.
