### ISSUE TITLE
Backdrop 1.7.1 Release Tasks

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2745]
1.7.1 Release
==================================

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create a new bugfix release to follow the current version @quicksketch
- [x] Move all unfinished issues to the next bugfix release @quicksketch
- [x] Draft Release notes @quicksketch

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, push to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @jenlampton
- [x] Update the front page download link on b.org @jenlampton

## Post-release tasks

- [x] Push the bug-fix release to the Pantheon repository @quicksketch
- [x] Tweet that a new release is out @jenlampton
- [ ] Update the docker image to the latest @serundeputy 
- [x] Update the Wikipedia articles to at least show the proper version number and date for latest release @klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by jenlampton** [comment]
@serundeputy go ahead and close this issue after the docker image has been updated :)

**Comment by serundeputy** [comment]
PR filed: https://github.com/docker-library/official-images/pull/3108

**Comment by serundeputy** [comment]
Merged; closing.

**Comment by quicksketch** [comment]
Woo, thanks everyone!

**Comment by klonos** [comment]
I've updated the Wikipedia dates as well (sorry for not being around to do the entire task in the first place).
