### ISSUE TITLE
[UX] Config Management: "Stage import" button should be blue (primary)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2748]
## Describe your issue or idea
On the CM UI the button didn't get it's proper color

<img width="652" alt="screen shot 2017-07-06 at 12 07 30 pm" src="https://user-images.githubusercontent.com/397895/27928355-b8e36808-6243-11e7-8ecb-b782ded366b7.png">

----
PR by @serundeputy: https://github.com/backdrop/backdrop/pull/1917

**Comment by serundeputy** [comment]
Website: http://1917.backdrop.backdrop.qa.backdropcms.org
Username: admin
Password: DXrSy8du

**Comment by quicksketch** [comment]
The fix would work but we should be consistent and use `#type = 'actions'` for the primary buttons on the page.

**Comment by serundeputy** [comment]
hehe; me too: https://github.com/backdrop/backdrop/pull/1917

**Comment by klonos** [comment]
Thought I'd save you some time @serundeputy :smile: ...closed mine in favour of yours :wink:

**Comment by jenlampton** [comment]
<img width="657" alt="screen shot 2017-07-06 at 12 07 00 pm" src="https://user-images.githubusercontent.com/397895/27928366-c1dfbf42-6243-11e7-8743-0a80331eb068.png">

Great work team, RTBC!

**Comment by serundeputy** [comment]
This is merged and will ship with `1.7.2`. closing.  thanks everyone!
