### ISSUE TITLE
Release 1.7.1 isn't marked as security release on "Available updates" page

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2749]
On the "Available updates" page of a Backdrop 1.7.0 site I see the 1.7.1 release but it's not marked as a security release.

### Steps to reproduce (if reporting a bug)

On a Backdrop 1.7.0 site go to `admin/reports/updates`, and have a look at the available updates.

### Actual behavior (if reporting a bug)

Under Backdrop CMS, version 1.7.1 is mentioned as "Recommended version", and the item has a yellow icon:

![screen-backdrop-1-7-available-updates](https://user-images.githubusercontent.com/14188307/27485183-0a177ff6-582c-11e7-8075-878604e47644.png)

### Expected behavior (if reporting a bug)

1.7.1 should be mentioned as a security release (don't remember the exact wording), and the item should probably have a red icon.

**Comment by serundeputy** [comment]
@olafgrabienski  good catch!

I just marked the release as a security release on https://backdropcms.org/releases/backdrop-171, and you `Check Manually` for updates again with the button and see if it is marked as security?

thanks!

**Comment by olafgrabienski** [comment]
@serundeputy - perfect: the release is now labeled as security update on `admin/reports/updates`. (Also on `admin/reports/status` and `admin/modules/update`.)

**Comment by serundeputy** [comment]
@olafgrabienski great!

closing this out.  reopen if necessary.

**Comment by klonos** [comment]
So we don't forget next time:

![image](https://user-images.githubusercontent.com/2423362/27498456-68dd9cfc-58a2-11e7-8a06-9ee90bd63b3e.png)

😉 

...I've added the task to the task list for bug fix releases only. Let me know if you think that it should also be added to the minor/major tasks as well.
