### ISSUE TITLE
Full HTML allows script tags (possible XSS vector)

### ISSUE THREAD

**Issue by zhonghaozhao** [backdrop/backdrop-issues#2750]
I found a xss issuse:
You can check it in https://github.com/zhonghaozhao/backdrop/issues/1
It not only cause annoy  issuse but also can cause security problem. Deeply suggest have a change on it .

**Comment by klonos** [comment]
@zhonghaozhao https://backdropcms.org/security

>If you have discovered a security issue with Backdrop CMS, please contact the Backdrop Security Team directly at security@backdropcms.org. We manage security issues separately in a private repository until the issue has been resolved. Even if you're not sure if it's a security problem, please contact the security team before filing an issue, blogging, or tweeting about it.

**Comment by olafgrabienski** [comment]
@zhonghaozhao Security issues shouldn't be discussed publicly, so I think it's better to remove the description of the issue in your repository.

**Comment by klonos** [comment]
I have pm'ed @quicksketch and @serundeputy to take a look at this. Geoff replied that he did take a look, but does not think that it is a XSS issue. I don't have more info, but basically what @olafgrabienski said^^

**Comment by quicksketch** [comment]
We did receive an email at security@backdropcms.org that included this same report. @jenlampton answered it by email as well at https://github.com/zhonghaozhao/backdrop/issues/1#issuecomment-310920018. As there was no vulnerability, we can leave this public.
