### ISSUE TITLE
[UX] Remove "Provide markup text for the area." text in views

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2757]
## Describe your issue or idea

In the views global custom text settings form, there is a element that simply shows the text `Provide markup text for the area.`.  These words make no sense to me. Is this supposed to be explaining what "Global: Text area" means? If so, it's doing a poor job. Let's fix it :)

<img width="1388" alt="screen shot 2017-06-30 at 5 55 48 pm" src="https://user-images.githubusercontent.com/397895/27757934-ed0ff93c-5dbd-11e7-8232-d9bd43486b0c.png">

----
PR by @GianniCoene : https://github.com/backdrop/backdrop/pull/2063

**Comment by GianniCoene** [comment]
Hello, I would like to work on this issue for my first Open Source contribution.

**Comment by jenlampton** [comment]
Hi @GianniCoene and thanks for tackling this one :) I think the easiest way to improve the situation would be to simply remove the text "Provide markup text for the area" from the page. 

If you can search for the string "Provide markup text for the area" in the views_ui directory, see if you can remove the whole form element that provides it.

**Comment by serundeputy** [comment]
This is great @GianniCoene thanks so much for your first open source contribution!
@jenlampton thanks for the RTBC!

This is merged into `1.x` and `1.8.x` and will ship with `1.9.0` and `1.8.2`.
