### ISSUE TITLE
[UX] Simplify user interface text on "Allow Upscaling" checkbox

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2764]
Before:
<img width="474" alt="screen shot 2017-07-10 at 1 22 17 pm" src="https://user-images.githubusercontent.com/397895/28038163-d887a7b4-6572-11e7-959d-2b0ccc55e284.png">

After: 
<img width="559" alt="screen shot 2017-07-10 at 1 37 04 pm" src="https://user-images.githubusercontent.com/397895/28038790-e7ee95d0-6574-11e7-90d5-ea01c25e7b95.png">

---
PR: https://github.com/backdrop/backdrop/pull/1926

**Comment by klonos** [comment]
Hmm, not sure about the implementation. I think that input labels of various settings should be short/minimal and text that explains what the setting does placed below the element as help text. It looks as if we are using the help text as the checkbox label here.

I don't think we are using a full stop in any other input element label in the UI (and if we do, it's probably wrong), but if we remove the full stop, we have a full-blown sentence without one (which is equally wrong).

I would go with:

- "Enable upscaling" for label (use a different word than "allow", which will be used in the help text)
- "Allow images to be scaled up, making them larger than their original size." as help text.

**Comment by jenlampton** [comment]
> I think that input labels of various settings should be short/minimal and text that explains what the setting does placed below the element as help text.

The proposed change is inline with all the other UX improvements that have been going into both core and contrib. Since people (not you, the other people ;) don't read help text, the movement has been to remove help text, and instead to make the checkbox label fully indicate what the checkbox does (instead of using help text to add more explanation). 

In this case "Allow upscaling" isn't really all that bad since it is fairly self-explanatory. If you don't think this is an improvement we should leave it as its. I was just trying to be consistent in our removal of help text if we want people to actually read the information contained within.

**Comment by jenlampton** [comment]
Here we are:

<img width="501" alt="screen shot 2017-08-10 at 6 32 27 pm" src="https://user-images.githubusercontent.com/397895/29198593-5639f622-7dfa-11e7-9d10-c6323ca81025.png">

new PR pushed.

**Comment by quicksketch** [comment]
Thanks, simple change that seems better to me as well. Merged into 1.x for 1.8.
