### ISSUE TITLE
Path URL alias settings should handle curly quotes

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2765]
A site I was working on had a page title pasted from Word, including curly quotes. Those curly quotes ended up in the URL and when I went to adjust the URL alias pattern settings (admin/config/urls/path/patterns/settings) there was no option to remove those under "Punctuation".

PR forthcoming!

---

PR by @laryn - https://github.com/backdrop/backdrop/pull/1927
Alt PR by @quicksketch - https://github.com/backdrop/backdrop/pull/1963

**Comment by laryn** [comment]
Out of curiousity I did a search and see this issue (10 years old) in the Drupal queues... maybe not as simple as I had thought?

https://www.drupal.org/node/207840

**Comment by klonos** [comment]
Thank you for opening this ticket @laryn 👍 ...attention to detail is what makes Backdrop a better D7 😉 

How about we add the [different types of dashes](https://en.wikipedia.org/wiki/Dash) to the set while we're at it?

**Comment by klonos** [comment]
...and quotation marks I guess: https://en.wikipedia.org/wiki/Quotation_mark

**Comment by olafgrabienski** [comment]
@laryn Just tested: I confirm that checking the options *Transliterate prior to creating URL aliases* and *Reduce URL alias characters to letters and numbers* on `admin/config/urls/path/patterns/settings` removes the curly quotes from the URL (as long as quotation marks are configured to be removed in the *Punctuation* settings on the same page, which is the default).

In my opinion it's a good idea to enable the mentioned transliteration settings by default. Are there common use cases where that doesn't make sense?

**Comment by laryn** [comment]
@klonos @olafgrabienski 
I think I'd be okay with checking the two option boxes that solve a lot of this by default. Or if someone thinks that is a bad idea, possibly expanding the direction I've gone here to include some additional common punctuation marks that aren't currently covered.

**Comment by quicksketch** [comment]
From the Drupal.org issue (from fletchgqc ) at https://www.drupal.org/node/207840#comment-7018526

> I believe a reasonable use-case has been overlooked. If I'm wrong just close it again. Here is the use-case: I want to use native characters for Japanese, Russian, whatever (i.e. I don't want to transliterate), but I don't want punctuation in my URLs. How do I do this?

That seems like a very valid and even common scenario that could affect non-English/ASCII websites: They may not want transliterated or ASCII URLs but do want to remove quotes. So I think we should move forward with making it so that these characters can be replaced without the ASCII-only or transliteration options.

*However*, I think adding multiple options for double and single quotes (especial separate options for "opening" vs. "closing") is overkill. How about we make it so that if double-quotes are replaced, it affects all kinds of double-quotes (`"` `“` and `”`), while single quotes affect all types of single quotes (`'` `‘` and `’`)? Or are there reasons we may want to keep them separate?

**Comment by quicksketch** [comment]
I made an alternative PR at https://github.com/backdrop/backdrop/pull/1963 that piggy-backs off the current single and double quote settings to affect "fancy" quotes as well.

**Comment by laryn** [comment]
@quicksketch Looks good to me. Which leaves @klonos' question open:

> How about we add the different types of dashes to the set while we're at it?

Do we do something similar for various types of dashes?

**Comment by quicksketch** [comment]
> Do we do something similar for various types of dashes?

Sounds good to me. Looks like that may include `–` (endash) and `—` (emdash)

Also looks like I missed a few quote styles, including `′` (prime) and `″` (double-prime) as well as `‚ ` (low-quote) and `„` (double low-quote).

Thanks https://www.w3.org/wiki/Common_HTML_entities_used_for_typography

**Comment by quicksketch** [comment]
PR updated at https://github.com/backdrop/backdrop/pull/1963.

**Comment by jenlampton** [comment]
This is a great and sensible approach to the problem at hand. Thanks for the feedback everyone, and thanks for the PR @quicksketch!

**Comment by jenlampton** [comment]
Test results: 
* http://1963.backdrop.backdrop.qa.backdropcms.org/posts/quote-test
* http://1963.backdrop.backdrop.qa.backdropcms.org/posts/apostrophe-test
* http://1963.backdrop.backdrop.qa.backdropcms.org/posts/dash-test

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1963 into 1.x for 1.8.0.
