### ISSUE TITLE
[UX] Installation: keep language choice as a simple dropdown list

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#2768]
When installing backdrop with a translation file already present, the first step of the installation wizard ("Choose language") display a multiple select box that clutter interface.
This dropdown list should be a regular one, not a multiple or sized one. Incoming pull request.

### Steps to reproduce

Before installing backdrop, add a language file : 
```
mkdir -p files/translations
wget http://ftp.drupal.org/files/translations/7.x/drupal/drupal-7.56.fr.po
mv drupal-7.56.fr.po files/translations
```
then visit the installation wizard.

### Actual behavior

![backdrop_install_language_before](https://user-images.githubusercontent.com/159548/28214020-e5f4d780-68a8-11e7-9eef-3b4f91aefdc4.png)

### Expected behavior

![backdrop_install_language_after](https://user-images.githubusercontent.com/159548/28214107-43c117f2-68a9-11e7-81e2-e2d60939aed3.png)

**Comment by opi** [comment]
Screenshots from Firefox 52 running on Debian 8 Gnome. Same behavior observed on Chromium 57.

**Comment by olafgrabienski** [comment]
Looks good (from the screenshot)!

**Comment by serundeputy** [comment]
thanks @opi ; looks good; works good!

merged into `1.x` and `1.7.x`; will ship with `1.7.2` and later.

**Comment by opi** [comment]
First contrib to backdrop, amazed to find back my good old procedural-drupal-style-coding \o/ 
I hope this will not be my last patch, I really enjoy backdrop so far !
