### ISSUE TITLE
Allow users to login using either their username OR their e-mail address

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#277]
Problem/Motivation

Part of a series of reforms for the login system, this patch would ideally allow users to log in using either their username OR their e-mail address, a feature that has previously been provided by the LoginToboggan module.

Proposed resolution

Update validation to allow login with email address and not require a username.
Change wording of login form to reflect new requirements.
Provide configuration options for site admins at admin/config/people/accounts to choose how logins are handled. Options are "username," "email address" or "Username or email address"

Remaining tasks:
- [x]  [#2014185](https://www.drupal.org/node/2014185): Check usernames that are email addresses more rigidly, only allow if matches email.
- [x] [#111317](https://www.drupal.org/node/111317): Allow users to log in using either email or password

**Comment by jenlampton** [comment]
Added a check for email-addresses-as-usernames matching email-addresses-as-mail on an account, as per the [d8 issue](https://www.drupal.org/node/2014185).  It introduces a new variable `user_email_match` that is by default ON.

**Comment by quicksketch** [comment]
Added a chunk of feedback to https://github.com/backdrop/backdrop/pull/524. Overall looks pretty good. My primary issue is with the new `user_email_match` option, which prevents a user from using one e-mail for a username and a different e-mail for their e-mail. It seems obvious that you'd always want that to be the case and we shouldn't ever allow them to be different if they're both e-mail addresses.

**Comment by quicksketch** [comment]
Let's bump to the next release. This is low priority but handy. With only a day left, something's gotta give. :)

**Comment by jenlampton** [comment]
agreet :)

**Comment by quicksketch** [comment]
It'd be nice to have this but we're not going to make it for 1.1.0. This isn't a high priority but still would be very nice to have. Moving this into the general 1.x pool.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/issues/951 gets this super-close. The only thing I ran across was that we're now "officially" going with "Email" instead of "E-mail". See #1056.

But even though this looks great, it's going to take a while for me to review properly. I'm moving this to the 1.3.0 release, as I'd love to see it in that next version.

**Comment by jenlampton** [comment]
That old PR was out of date, so I've created a new one at https://github.com/backdrop/backdrop/pull/1156.  we'll see if tests still pass.

**Comment by quicksketch** [comment]
The new PR still has a lot of issues (and failing tests). I'm going to take another stab at this and see if I can get it up-to-date. I posted a bunch of feedback in https://github.com/backdrop/backdrop/pull/1156. Things like `user.settings.json` don't exist in the current version of Backdrop (it was consolidated into `system.core.json` before 1.0.0 release), and the upgrade path isn't quite right.

**Comment by quicksketch** [comment]
New PR updated at https://github.com/backdrop/backdrop/issues/1172.

**Comment by quicksketch** [comment]
With the fixes to the config file names and a few minor adjustments, this is ready to go! Merged into 1.x.

3rd (or 4th) times a charm on this one. We'd been wanting this since 1.0 and I'm glad to see it make it for the UX release of 1.3.0. :smile:
