### ISSUE TITLE
PHP is inconsistent about Chile time abbreviations, use Central Europe instead for testing

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2771]
From the "Nothing is Ever Simple' file...

In `core/modules/user/tests/user.test`, we test some timezone functions and date formatting using America/Los_Angeles and America/Santiago as the two test timezones.  For the former, we look for PST and PDT in the formatted string, for the latter we look for CLT and CLST.  Kinderspiel, right?

Unfortunately, depending on the version of PHP you're using, you may get CLT/CLST back or you may get -04/-03 back.  You can see the results for various versions of PHP and [America/Santiago](https://3v4l.org/uI4Pf) on 3v4l.org.

The tests fail under certain versions of PHP, not because of a bug in Backdrop, but because of a bug in PHP.  Fedora 26 ships with PHP 7.1.7 and Debian 9 ships with 7.0.19, both of which are affected.

PHP is consistent for [Europe/Paris](https://3v4l.org/Lnlch), so we can use CET/CEST for testing instead.

**Comment by klonos** [comment]
Good catch @jlfranklin 👍  ...wonder whether this has to do with any of the random failures we get now and then with our PRs.

**Comment by jlfranklin** [comment]
Seems unlikely, unless the testing framework is randomly selecting a version of PHP to run.

**Comment by quicksketch** [comment]
Wow, nice catch @jlfranklin! Merged into 1.x and 1.7.x.

**Comment by quicksketch** [comment]
Really merged it today. This is now in 1.x and 1.7.x.
