### ISSUE TITLE
[i18n] Untranslated string in system_menu_block_form()

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#2772]
https://github.com/backdrop/backdrop/blob/7e94b0cd373efb4683bf6e67e20bb8bb8fba75e8/core/modules/system/system.menu.inc#L108

The 'toggle' checkbox title string is not wrapped with `t()` function.

PR incoming.

**Comment by serundeputy** [comment]
Thanks @opi looks great!

Merged into `1.x` and `1.7.x`; will ship with `1.7.2`.

**Comment by serundeputy** [comment]
thanks for the review @herbdool !
