### ISSUE TITLE
Add a CHANGELOG.md file

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2778]
I was filing some PRs for #2774 and noticed that some of the respective Drupal patches change a CHANGELOG.txt file, but we don't have one in Backdrop. I think we should.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1935

**Comment by klonos** [comment]
@jenlampton care to take a look?: https://github.com/klonos/backdrop/blob/patch-141/CHANGELOG.md

It's just a rough "template" that includes only dates and links to all releases to date, but I intent to slowly update it with actual features/fixes for each release. I will need this file to exist when I'm filing PRs for issues like #2774, so the sooner this gets merged, the better. Thanks in advance 😉

**Comment by klonos** [comment]
...PS: I have made our changelog an .md file, since I see that format as a trend lately + it allows linking to further info online.

**Comment by jenlampton** [comment]
I thought we decided a changelog would only add extra work, and would not
provide any real benefit?

**Comment by jenlampton** [comment]
Removing it from backdrop was not an oversight, it was intentional. You can
mark any commits to Drupal's changlog as NA.

**Comment by herbdool** [comment]
I agree, only a developer would look in a changelog and why manually create one when they can just look at git log.

**Comment by quicksketch** [comment]
I'm also not a fan of CHANGELOG files, as they are predominantly useful only to developers who have access to the code base and don't have a marketing benefit. On Drupal sites I most frequently use the CHANGELOG.txt file to version check what a site is running, but that can be a bad thing to provide such a public way to identify the version of the software.

**Comment by klonos** [comment]
Fair enough. Closing this issue then.
