### ISSUE TITLE
Odd behavior with block configuration

### ISSUE THREAD

**Issue by JAyenGreen** [backdrop/backdrop-issues#2779]
## Describe your issue or idea
I have a block configuration form function, below. The final two fields, destination_url and destination_title were additions. I fill in both fields in the block config in my layout and save. If I configure the block again, both fields have been persisted.

In the block's view function, the settings array does not contain the destination_title index, but does contain the destination url index and value.

If I clear cache, the destination_url value is still present when configuring the block, but the destination_title field is now blank.
### Steps to reproduce (if reporting a bug)
```php
function my_module_block_configure($delta = '', $settings = array()) {
  $form = array();

  if ($delta == 'poster_block' || $delta == 'poster_block_double') {
    $settings += array(
      'poster_string' => '',
    );

    $form['poster_string'] = array(
      '#type' => 'textfield',
      '#title' => t('Poster text'),
      '#size' => 60,
      '#description' => t('This text will appear in the poster block'),
      '#default_value' => $settings['poster_string'],
    );
  }

  if ($delta == 'linkshare_image_block' || $delta == 'linkshare_image_block_double') {
    $settings += array(
      'linkshare_image_url' => '',
    );

    $form['image_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Image URL'),
      '#size' => 120,
      '#description' => t('The URL for the image to be displayed'),
      '#default_value' => $settings['image_url'],
    );
    $form['image_alt_text'] = array(
      '#type' => 'textfield',
      '#title' => t('Alt text'),
      '#size' => 120,
      '#description' => t('Enter the text that a screen reader would announce'),
      '#default_value' => $settings['image_alt_text'],
    );
  }

  $form['destination_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Destination URL'),
    '#size' => 120,
    '#description' => t('Enter a relative URL to make this block clickable'),
    '#default_value' => $settings['destination_url'],
  );
  $form['destination_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Destination title'),
    '#size' => 120,
    '#description' => t('Enter the text to show when hovering over the link'),
    '#default_value' => $settings['destination_title'],
  );

  return $form;
}
```
### Expected behavior (if reporting a bug)
I would expect all values in the form to be persisted.
### Relevant version/system information (if applicable)
1.5.2

**Comment by JAyenGreen** [comment]
It seems when I add a line to the form in the module, configure the block, add text to the new field and save, that it is not being written to the JSON file.

**Comment by BWPanda** [comment]
@JAyenGreen Is this still an issue in the latest version, or has it been fixed?

**Comment by BWPanda** [comment]
Closing due to lack of further info.
