### ISSUE TITLE
Add atom tags to views RSS feeds.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2780]
When trying to validate an RSS feed produced by my Backdrop site, the [W3C feed validator](https://validator.w3.org/feed/) makes the following recommendation:

```
This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

    line 21, column 2: Missing atom:link with rel="self" [help]
```

The 'help' link points to: https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html

Can we add this to core? Drupal request for the same is here: https://www.drupal.org/node/1337894

**Comment by quicksketch** [comment]
Thanks @BWPanda! Great idea. I've added a PR at https://github.com/backdrop/backdrop/pull/1943. Let's test the sandbox against the validator when complete. I'm not familiar with feed syntax, so double-checking the output manually would be a good idea.

**Comment by quicksketch** [comment]
Well it's passing validation at least! https://www.feedvalidator.org/check.cgi?url=http%3A%2F%2F1943.backdrop.backdrop.qa.backdropcms.org%2Frss.xml

![image](https://user-images.githubusercontent.com/100206/29007850-ccd29db2-7ac0-11e7-8342-4e962f3ce1c8.png)

**Comment by BWPanda** [comment]
Looks good to me! Thanks!

**Comment by quicksketch** [comment]
Great, merged into 1.x and 1.7.x.
