### ISSUE TITLE
[UX] Menu block settings: Improve the help text of the hamburger icon option

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2781]
This sparked from reviewing #2773 (thank you @opi). The current help text is:

> A menu toggle button, commonly known as a hamburger icon, allows the menu to be hidden initially on devices with small screens, but then easily expanded.

Now, English is not my primary language, but it seems to me that the right way is to say "initially hidden".

Anyway, while at it, we might as well improve the entire thing. I was thinking something like this makes better sense:

> On devices with small screens, this option reduces the menu to a toggle button, commonly known as [_hamburger icon_](https://en.wikipedia.org/wiki/Hamburger_button). Clicking the icon reveals or hides the menu, saving screen space.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1938

**Comment by opi** [comment]
Reviewed and approved: backdrop/backdrop/pull/1938#pullrequestreview-54529395

**Comment by quicksketch** [comment]
Thanks @opi! There's an issue with the `t()` call and handling a URL (it's always confusing). I left a comment at https://github.com/backdrop/backdrop/pull/1938#pullrequestreview-54545058.

Feel free to move to "pr - reviewed and tested by community" after completing reviews. :smile:

**Comment by quicksketch** [comment]
BTW I think the new help text looks great.

**Comment by klonos** [comment]
Thank you @opi and @quicksketch for the CR. I've fixed the url thing.

**Comment by quicksketch** [comment]
Thanks @klonos! Merged https://github.com/backdrop/backdrop/pull/1938 into 1.x. As this is a string change, it will first be included it in 1.8.0.
