### ISSUE TITLE
[UX] Add the ability to upload multiple images at once

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2786]
## Describe your issue or idea

In an intent to improve our image handling abilities in Backdrop, it would be nice to allow users to upload lots of images at the same time. 

In Drupal 7 there were several contrib solutions to this problem, but [Multiupload Filefield Widget](https://www.drupal.org/project/multiupload_filefield_widget) and [Multiupload Imagefield Widget](https://www.drupal.org/project/multiupload_imagefield_widget) were included in Drupal 8.

I propose that we incorporate these two new widgets in Backdrop CMS as well.

**Comment by laryn** [comment]
Related:

- https://github.com/backdrop/backdrop-issues/issues/440
- https://github.com/backdrop/backdrop-issues/issues/1380

**Comment by jenlampton** [comment]
Oh, it looks like this is a duplicate of https://github.com/backdrop/backdrop-issues/issues/1380 entirely. I'll just add my recommendation as a comment there...  I searched but didn't find it :(

Thanks!

**Comment by nimek2** [comment]
Resumable upload drupal module.
Does exactly what you expect and even more. Auto upload and skip file size limit.
