### ISSUE TITLE
NodeMultiByteUtf8Test checks the wrong xpath

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2787]
The NodeMultiByteUtf8test looks for an H1 with `id="page-title"`.  The test fails because the H1 tag for the title has `class="page-title"`.

### Steps to reproduce (if reporting a bug)
Run the tests in an environment that has utf8mb4 enabled by default.

### Actual behavior (if reporting a bug)
Test fails:
```
---- Node: Multi-byte UTF-8 (NodeMultiByteUtf8Test) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Exception Notice     node.test         2856 NodeMultiByteUtf8Test->testMultiByt
    Undefined offset: 0
Fail      Other      node.test         2856 NodeMultiByteUtf8Test->testMultiByt
    The passed title was returned.
```

### Expected behavior (if reporting a bug)
Test passes.

**Comment by quicksketch** [comment]
Nice catch @jlfranklin! Merged https://github.com/backdrop/backdrop/pull/1947 into 1.x and 1.7.x.
