### ISSUE TITLE
Syntax error, unexpected ';', expecting ')' on entity.api.php line 531

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#2791]
### Actual behavior (if reporting a bug)
Syntax error, unexpected ';', expecting ')' on entity.api.php line 531

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
Thanks for the PR and review @robertgarrigos and @herbdool! Merged https://github.com/backdrop/backdrop/pull/1948 into 1.x and 1.7.x.
