### ISSUE TITLE
document theme_image changes from Drupal7

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#2793]
## Describe your issue or idea
I found myself looking for changes in theme_image function and found no documentation other than the api. In D7 associative array contains 'path' where in backdrop should be 'uri'.
### Actual behavior (if reporting a bug)
There is a page (https://api.backdropcms.org/converting-modules-from-drupal) with major changes and then you are directed to the change records page (https://api.backdropcms.org/change-records) for other changes you don't find there. However, you cannot find anything about this particular theme function in any of those pages.
### Expected behavior (if reporting a bug)
Would it be good to have this documented somewhere?

**Comment by jlfranklin** [comment]
This may be covered by #2521.

**Comment by robertgarrigos** [comment]
thanks. it is.
