### ISSUE TITLE
Add the ability to edit an existing managed file

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2796]
I'm splitting this issue off from https://github.com/backdrop/backdrop-issues/issues/2633 because I'm having trouble with the Add part, but want to be sure to get the Edit part done for 1.8.

Steps for testing the PR:
* Go to the manage files page at admin/content/files
* Edit a file using the drop-button on the right
* Tell us what you experienced! Does it make sense? If not, what were you expecting, and what did you get?

---
~PR: https://github.com/backdrop/backdrop/pull/1955~
~https://github.com/backdrop/backdrop/pull/1997~
https://github.com/backdrop/backdrop/pull/2056

**Comment by herbdool** [comment]
Good idea. This is useful on its own no matter where the file was uploaded. Does it include deleting?

**Comment by jenlampton** [comment]
We already have deleting in core :)

**Comment by olafgrabienski** [comment]
I've had a look at the sandbox site and at the PR page where @jenlampton and @herbdool discussed a few questions regarding functionality and concept of editing files. Maybe it's better to continue the discussion here on the issue page?

Copying therefore important information about the concept from the PR page to this comment:

> What should happen is that the original file should be marked "temporary" (since is is about to be deleted) and the new one should be marked "permanent". The new file should retain the file name of the original, which makes the list on the "Files" page a hard place to see the changes...
>
> All the field values (like FID and file name) should be the exactly the same, but an image you see on the node should appear different after replacing the file. (...)
> 
> I wonder if some of the confusion could be cleared up by throwing away the file name of the replacement file (since it's weird when the files swap names), and instead rename the old file to something like "replaced-file-X".

Update:

> the temporary file now changes it's own name to replacement-file-FID.jpg so that when it appears in the files list it won't confuse anyone.

**Comment by olafgrabienski** [comment]
While testing the sandbox site, I was quite confused of the *Edit file* interface, or by how an edited file is reflected on a node with a field of this image. To begin, I'm not sure if and why a new file should retain the name of the replaced 'original' file. Can someone provide a use case for it, and are there possibly other use cases?

**Comment by jenlampton** [comment]
> Can someone provide a use case for it, and are there possibly other use cases?

Sure!

** Already supported in core **
First use case - you want to have a different file on a node: 

Solution: edit the node, remove the old file, and add the new file.

** New feature **
Second use case - you attached a PDF to a node that's a meeting agenda. The agenda has changed.

Solution: edit the FILE instead of the node, replace the old agenda with the new agenda. Keeping the file name the same means any links you emailed to people with the meeting agenda will not be broken - and they'll all get the correct (new) agenda.

**Comment by olafgrabienski** [comment]
Thanks @jenlampton for the use cases. I've tested a variation of the third use case, see [Another test post](http://1955.backdrop.backdrop.qa.backdropcms.org/posts/another-test-post) on the sandbox site. It works as expected: By *editing* an image file and uploading the new logo via the *File edit* page (i.e. not removing and adding a new logo via the node form), the image URL remains the same.

I was however a bit puzzled about the result on `admin/content/files`. Regarding the two related image files in the list I expected that the temporary `replacement-file-XYZ.png` would be the old logo but it is the new one, so both images are identical (see the file size as an indicator):

- dummy-logo-1.png | image/png | 08/25/2017 - 12:41pm | 8.89 KB | Permanent
- replacement-file-14.png | image/png | 08/25/2017 - 12:41pm | 8.89 KB | Temporary

**Comment by olafgrabienski** [comment]
Apart from the technical aspects, I guess we could improve the usability a lot. I managed to test the mentioned use case on the sandbox site mainly with the help of information given in this issue. In the real world an editor wouldn't know of the mentioned differences (node form via file edit form). Even if she/he would know, it remains difficult to find an image via the file edit page when there are hundreds of images, or even more.

I'd suggest to integrate file editing to the node form, adding an `Edit` button (see mockup below), and opening the respective file edit form in a modal.

![screen-backdrop-pr-1955-b-image-edit-or-remove](https://user-images.githubusercontent.com/14188307/29715855-58cf2a00-89a9-11e7-9ca1-6dc3b6aff35e.png)

**Comment by olafgrabienski** [comment]
> I'd suggest to integrate file editing to the node form, adding an `Edit` button, and opening the respective file edit form in a modal.

Replacing a file without changing the file name is probably the main use case here. To make it more clear, we could add a `Replace` button instead of an `Edit` button.

**Comment by jenlampton** [comment]
I love this idea, but I'm not sure we'll have time to get it in for 1.8, since we still have some work to do on this PR. However, once we have the form in it should be easier to add it into a modal, elsewhere.  I've created https://github.com/backdrop/backdrop-issues/issues/2810 and tagged it for 1.9.

**Comment by jenlampton** [comment]
> Regarding the two related image files in the list I expected that the temporary replacement-file-XYZ.png would be the old logo but it is the new one, so both images are identical

Yes, that's because we first upload the new file, then copy it over to replace the old one.  Maybe we should create 3 files instead? If we were to do that we would end up with something like:

- dummy-logo-1.png | image/png | 08/25/2017 - 12:41pm | 8.89 KB | Permanent
- replacement-file-14.png | image/png | 08/25/2017 - 12:41pm | 8.89 KB | Temporary
- backup-file-15.png | image/png | 07/24/2016 - 1:30pm | 6.67 KB | Temporary

**Comment by olafgrabienski** [comment]
> We could create 3 files instead (generating a little more trash to be deleted moments later). But that could be worthwhile if there was a UX benefit by doing so.

Yes, three files would be less confusing in my opinion. To make the temporary files thing more comprehensible I suggest also to arrange the temporary files as indented and/or grouped items under the respective permanent file:

- dummy-logo-1.png | image/png | 08/25/2017 - 12:41pm | 8.89 KB | Permanent
  - replacement-file-14.png | image/png | 08/25/2017 - 12:41pm | 8.89 KB | Temporary
  - backup-file-15.png | image/png | 07/24/2016 - 1:30pm | 6.67 KB | Temporary
- ANOTHER FILE | TYPE | DATE - TIME | SIZE | Permanent

**Comment by jenlampton** [comment]
> I suggest also to arrange the temporary files as indented and/or grouped items 

Unfortunately the files listing is just a view (database query) and there's nothing in the database that associates these files with one another, so there's no way to add the grouping. I'll see about adding a third file and see if that works.

**Comment by jenlampton** [comment]
@olafgrabienski I've now also added the backup/temporary file. I do think it helps with the experience a little, but we'll see what others think.

**Comment by quicksketch** [comment]
One change I can see right off in testing this is that we don't have an update hook to update the File view for existing sites yet. That makes this new functionality invisible for all upgrading sites.

**Comment by quicksketch** [comment]
I left a code review over in https://github.com/backdrop/backdrop/pull/1955#pullrequestreview-60472796.

Some other thoughts in general:

- Upgrade hook needs to edit the view to add the edit link.
- Upgrade hook should auto-add the ability to edit files to any role that has the ability to delete them.
- file_admin_paths() should include `file/*/edit` as an admin path to match `file/*/delete`.
- The "destination" section seems unnecessary if there is only one type of destination (e.g. private has not been set up).

Uploading a file also didn't have the expected result for me. When replacing a file, my newly uploaded file was registered as a new, temporary file. The new file showed up in `/content/files` separate from the original file that I edited. And the original file was not modified at all. The file entity remained with the same file attached to it.

I know the upload functionality has been rearranged recently, so perhaps its intended functionality was broken in the updates.

**Comment by jenlampton** [comment]
> Uploading a file also didn't have the expected result for me. When replacing a file, my newly uploaded file was registered as a new, temporary file. The new file showed up in /content/files separate from the original file that I edited. And the original file was not modified at all. The file entity remained with the same file attached to it.

Are you sure? Did you open the file attached to the original entity? Most people are assuming that since the file name remains unchanged, the file contents remain unchanged too, without checking the file contents.

**Comment by quicksketch** [comment]
Oh. Huh, yes the contents *were* changed, but I had to force-reload the image in my browser. This might be helped substantially by providing some kind of preview on the file edit screen. Keeping the same file name will inevitably cause some problems though. On a local machine a shift-reload is sufficient. But on a site with a CDN or reverse-proxy like Varnish, that image will be cached for a long period of time (probably 2 weeks per the .htaccess file) and difficult to get a fresh copy without manually clearing the caches at those layers.

And the creation of the new, temporary files in the file listing even after doing the upload is considered expected behavior? It seems like they should be deleted right away after all the replacement is said and done.

**Comment by jenlampton** [comment]
It seems like this issue still needs a lot of work. The user experience is weird as-is, and we're facing issues with file caching by keeping the filename the same, though that is what's desired. Additionally, as @jlfranklin mentioned in Gitter, we haven't addressed revisioning. What if someone were to change/replace an important attached document, the node does not track that change as a revision? 

I think we have too many unresolved issues to try to get this change into 1.8. Bumping milestone.

**Comment by laryn** [comment]
I just tested without having read the entire thread, and noticed a few things I was expecting that were not on the edit page:

 - A preview of the image I was about to replace.
 - An option (or at least an explanation) about whether the filename would change after upload. (e.g. is it going to overwrite the old filename, or redirect the old filename to the new one?)
 - Not as critical, but I expected the upload to start immediately the way it does on node forms, instead of waiting for me to click "Save".

**Comment by quicksketch** [comment]
Thanks @laryn! Those are some more good suggestions. I agree the file name situation is still confusing.

I filed a new PR at https://github.com/backdrop/backdrop/pull/1997, changes:

- Temporary files are now immediately cleaned up on save. So after saving the form, only the new file remains.
- Switched the uploader to the AJAX-enabled `managed_file` element. (This makes the uploader act like the node form an upload immediately.)
- Code clean up the items noted in the previous PR.

Still needs the upgrade path.

**Comment by olafgrabienski** [comment]
I had a look at the new PR's sandbox site. Without the temporary files the page feels less confusing, nice! The uploader works also fine.

@laryn I agree that a preview of images on the *Manage files* page would help a lot. For the moment there is at least a workaround: a site builder could add the preview images in the *Administer files* view, adding the relationship "File: Content using Image" and the respective image field. Result:

![screen-backdrop-pr-1997-edit-files-incl-preview](https://user-images.githubusercontent.com/14188307/30400170-48d75276-98d6-11e7-92ed-6580bc0c2567.png)

However, maybe not the best solution if you use many different image fields on your site. And I guess, we should have a preview for other file types as well.

**Comment by herbdool** [comment]
Perhaps the preview improvement can be a new issue. I think it can still be added later.

**Comment by Graham-72** [comment]
Earlier @olafgrabienski suggested
>To make it more clear, we could add a Replace button instead of an Edit button.

Would it not be much easier to understand this operation if we called it 'Replace' instead of 'Edit'?

**Comment by jenlampton** [comment]
The act of replacing a file does use a "replace" button. The problem is the drop-button, which allows  editing of metadata as well as replacing a file, and may, eventually, also including editing of the file (image cropping, etc).  What if we used `Manage` there?

**Comment by Graham-72** [comment]
Yes, to me ```Manage``` sounds appropriate.

**Comment by olafgrabienski** [comment]
> Yes, to me `Manage` sounds appropriate.

To me as well! I see that my former suggested term `Edit` is not wide enough, especially for upcoming actions.

**Comment by quicksketch** [comment]
:+1:  "Manage". Seems almost obvious doesn't it? Even our menu items in the admin bar say "Manage files", "Manage content", etc. I think that term was intended to encompass not just editing, but also deletion, unpublishing, moderation, and other tasks.

So Manage could get confusing if there ever were other things you might want to do with a file (e.g. if there were both "Manage" AND "Edit" I would be unsure which did what). But with only one option, "Manage" seems like a good choice.

Should we leave the menu path as `file/[fid]/edit`? Even though the label would say "Manage"?

**Comment by olafgrabienski** [comment]
> Should we leave the menu path as `file/[fid]/edit`? Even though the label would say "Manage"?

If there's no technical reason to keep `edit` in the path, I'd prefer `manage`. Sounds more consistent to me. Also maybe one time we could need `edit` for real file editing like image cropping.

**Comment by jenlampton** [comment]
I agree with @olafgrabienski :)

**Comment by jenlampton** [comment]
Pushed an updated PR to use the word "managed". Writing an update hook now...

**Comment by quicksketch** [comment]
Thanks @jenlampton! The latest PR looks great. Update hook is working and all tests are passing with the new terminology.

I've merged in https://github.com/backdrop/backdrop/pull/2056 into 1.x for 1.9.0.
