### ISSUE TITLE
Basis: Out of the box CiviCRM CSS conflicts with Basis CSS

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2798]
## Describe your issue or idea

Out of the box, the CSS files in CiviCRM conflict with the CSS in Basis. (See below)

<img width="867" alt="screen shot 2017-08-18 at 12 22 13 pm" src="https://user-images.githubusercontent.com/871421/29469971-29939eea-8410-11e7-8ffd-4aef152a81d9.png">

Basically the left padding is overwritten by CiviCRM and is no longer enough to keep the text fully visible. I can add that back quite easily, but am not sure where to do this -- can we have a CiviCRM-specific override in the Basis CSS? Or should I be barking up the CiviCRM tree instead?

For reference, here's how it looks on a Drupal site:

<img width="962" alt="screen shot 2017-08-18 at 12 31 15 pm" src="https://user-images.githubusercontent.com/871421/29470239-329c0562-8411-11e7-9d33-70e433606cab.png">

It's easy enough to fix in my own theme but it seems this should be fixed out of the box for everyone.

**Comment by quicksketch** [comment]
This CSS seems to be coming from `messages.theme.css` in System module, which affects all themes by default.

The styling in Backdrop is fairly extensive and may be difficult for CiviCRM to entirely disable. But it looks like the conflict would actually affect pretty much any messages set by Backdrop, not just those set by CiviCRM.

If it's possible, I think the best solution would be for CiviCRM to use a different class for it's messages (perhaps prefixing `.messages` with `.civicrm-messages`).

Or if that would impact sites too heavily, perhaps just not set padding?

Or lastly, perhaps the Backdrop CSS for `messages.theme.css` can be positioned after the CiviCRM CSS file in the page load order, that might give it precedence, depending on how specific the CSS selectors in Civi are.

**Comment by laryn** [comment]
@quicksketch It does just affect CiviCRM messages, not regular Backdrop messages. Here's the offending CSS that CiviCRM is adding:

```
.crm-container .status {
    background-color: #FFFFCC;
    background-image: none;
    border: 1px solid #FFFF66;
    margin: 0.5em 0;
    padding: 0.25em 0.5em;
    color: #3e3e3e;
    font-weight: normal;
}
```

So simply adjusting the weight of the Backdrop CSS doesn't do it unfortunately because it only has one selector:

```
.messages {
    position: relative;
    box-sizing: border-box;
    margin: 0.375rem 0;
    padding: 0.9em 0.625em 1em 3.438em;
    border-radius: 4px;
    min-height: 3.2em;
    overflow: hidden;
}
```

I'll inquire with some CiviCRM folks as to whether any changes on that end are possible or not. The downside of that would be that the Backdrop formatting would be lost on CiviCRM messages -- it feels a little more integrated to share the styles a bit for messages no matter where they come from.

**Comment by laryn** [comment]
CiviCRM issue / PR is here:
https://issues.civicrm.org/jira/browse/CRM-21095

We'll see if they like the approach.

**Comment by laryn** [comment]
@quicksketch This got merged so should be taken care of on the CiviCRM side in future releases.

**Comment by quicksketch** [comment]
Nicely done @laryn!
