### ISSUE TITLE
Upgrade CKEditor to version 4.7.2

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2799]
## Describe your issue or idea

CKEditor 4.7 was released May 25, 2017. We should upgrade to the latest version in Backdrop 1.8.

https://ckeditor.com/blog/CKEditor-4.7-released

This new version looks mostly to improve copy/paste support. Though they did also add an option to disable the contextual menu, which we might consider using as an alternative way to solve #2386 (which was already fixed by disabling the entire contextual menu plugin).

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1960

**Comment by quicksketch** [comment]
Simple upgrade with no config changes at all. Merged in https://github.com/backdrop/backdrop/pull/1960 into 1.x for 1.8.0.

**Comment by jenlampton** [comment]
We should include notes on how to update our build of CKEditor under "Procedures" in the [Backdrop-Issues repo](https://github.com/backdrop/backdrop-issues), so that other people can update it, if you are in a meeting or something...
