### ISSUE TITLE
Coding Standards: explicitly declare DatabaseSchema::prefixNonTable() as public

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2801]
Minor coding standard fix.

**Comment by jlfranklin** [comment]
If someone would like to turn this into a coding standards audit meta-bug, feel free to assign yourself the bug.

**Comment by quicksketch** [comment]
Great little fix. Thanks @jlfranklin! Merged https://github.com/backdrop/backdrop/pull/1962 into 1.x and 1.7.x.
