### ISSUE TITLE
Seven: icon cleanup: replace old icons with lager font-awesome equivalents & rename.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2802]
Spin-off from https://github.com/backdrop/backdrop-issues/issues/2814
Follow-up to https://github.com/backdrop/backdrop-issues/issues/1178

In the Seven theme, we have several icons that we inherited from Drupal. Two of them are never used. None of them look good on retina displays. Many of these icons are different sizes. Some of these icons are gray, some are blue, and one is green. They are currently named as follows:

* add.png (blue)
* angle-right--gray.png
* arrow-asc.png (gray)
* arrow-desc.png (gray)
* ~~arrow-next.png (not used - blue)~~
* ~~arrow-prev.png (not used - blue)~~
* task-check.png (green)

We are about to add a suite of black icons to Seven for the display on the admin/config page. 
See https://github.com/backdrop/backdrop-issues/issues/1178 

I would like to propose that we replace any old icons in the Seven theme with new, larger font-awesome equivalent versions that we can size-down via CSS so they will look good on retina displays. 

Additionally, I would like to rename these files to include 1) the font-awesome name without the `fa-`, 2) the color 3) the size.  New names would be as follows:

* plus--blue--32.png
* chevron-right--gray--32.png
* caret-down--gray--32.png
* caret-up--gray--32.png

After the addition of https://github.com/backdrop/backdrop-issues/issues/1178 I would like to recommend that any icon included in the Seven theme have the color and size appended to the file name as well.

New Plus icon for action links: 
<img width="245" alt="screen shot 2017-09-02 at 11 41 31 pm" src="https://user-images.githubusercontent.com/397895/30001098-4a3ebbfa-9038-11e7-80f4-9cf42cd1dbf8.png">

New carets for tablesorters:
<img width="363" alt="screen shot 2017-09-02 at 11 50 35 pm" src="https://user-images.githubusercontent.com/397895/30001145-96b1159a-9039-11e7-8158-e323b910c438.png">

New chevron in breadcrumbs:
<img width="197" alt="screen shot 2017-09-02 at 11 54 02 pm" src="https://user-images.githubusercontent.com/397895/30001159-250c6f38-903a-11e7-883e-07308f20d56c.png">

New chevron icon for bullet:
<img width="489" alt="screen shot 2017-09-02 at 11 55 59 pm" src="https://user-images.githubusercontent.com/397895/30001162-4d8c4eec-903a-11e7-9929-3db81623500f.png">

---
PR: https://github.com/backdrop/backdrop/pull/1966

**Comment by jenlampton** [comment]
Had some issues with my PR, but I think this one is working now: https://github.com/backdrop/backdrop/pull/1966

**Comment by klonos** [comment]
PR looks good 👍 

Eventually I would like to see Backdrop use icon fonts so that we can easily change size and color via CSS.

**Comment by jenlampton** [comment]
> Eventually I would like to see Backdrop use icon fonts

I agree. I went and edited that issue and linked to this one as related.

**Comment by quicksketch** [comment]
I had to do a little rebasing after the new additions to /admin/config icons from https://github.com/backdrop/backdrop-issues/issues/1178, but everything in the PR looks great!

I've merged https://github.com/backdrop/backdrop/pull/1966 after resolving the conflicts. This will be in Backdrop 1.8.0.

**Comment by jenlampton** [comment]
woohoo! :)

**Comment by olafgrabienski** [comment]
@jenlampton I'm not sure if it's related with exactly this fix: After an update from BD 1.7.1 to 1.8.0 I miss the "new chevron icon for bullet" mentioned in the issue description. And as the old bullet icon seems to be dropped in 1.8.0, there is no bullet icon at all on the *Add content* page and in similar lists. See a comparison:

**Backdrop 1.7.1** (old bullet icons):

![screen-backdrop-list-bullet-icon-old](https://user-images.githubusercontent.com/14188307/30568533-f6df33f4-9cd5-11e7-8225-df0c557c71d5.png)

**Backdrop 1.8.0** (missing bullet icons):

![screen-backdrop-list-bullet-icon-missing](https://user-images.githubusercontent.com/14188307/30568536-ffe1b53a-9cd5-11e7-82b1-7ffcf09f7b73.png)

**Comment by jenlampton** [comment]
Yep, that's related. This definitely no longer matches the screenshot in the issue. I'll see if I can track down the problem.

**Comment by jenlampton** [comment]
Actually, it looks like these icons were removed in https://github.com/backdrop/backdrop-issues/issues/1178

**Comment by jenlampton** [comment]
@olafgrabienski will you review https://github.com/backdrop/backdrop-issues/issues/2856?

**Comment by olafgrabienski** [comment]
@jenlampton Have commented threre!
