### ISSUE TITLE
Update styling of progress bar: green burst to blue barber pole

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2803]
## Describe your issue or idea

The progress bar in Backdrop has been a small point of contention since the restyling of the Seven theme in #736. See the progress-bar specific issue at #758.

The current design frequently looks downright terrible on projectors, with not enough contrast to see the animation, and the green/yellow color tints towards light yellow. Going with a high-contrast color and animation will display better in more situations, plus prevent clashing color schemes.

I'd like to propose we go with a less stylized implementation, and go with a blue barber-pole design that matches the blue from our color scheme:

![image](https://user-images.githubusercontent.com/100206/29501062-79fd1822-85da-11e7-840d-0d9d99bf0618.png)

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1968

**Comment by quicksketch** [comment]
Screenshots of current and suggested designs in animation:

![old-progress-bar](https://user-images.githubusercontent.com/100206/29501292-6b3bd86c-85dc-11e7-943a-8e1ee0ec941f.gif)

![new-progress-bar](https://user-images.githubusercontent.com/100206/29501295-6f6c5cc2-85dc-11e7-85c8-397b0e0dc2b6.gif)

**Comment by jenlampton** [comment]
I love it!!!!

**Comment by klonos** [comment]
I always hated the green progress bar :)

I love the new, blue one 👍

**Comment by klonos** [comment]
I have given this a go using the Project Installer and it works fine and looks great. There is this issue with the LHS with the steps not being rendered while the progress bar is shown, but that's a pre-existing issue that we might want to handle separately. Other than that, RTBC from me 👍

**Comment by quicksketch** [comment]
Super, merged https://github.com/backdrop/backdrop/pull/1968 into 1.x for 1.8.0 then. :smile: 

More style changes regarding the installer and project browser are in https://github.com/backdrop/backdrop-issues/issues/2804. I'd love to see that implemented as well.
