### ISSUE TITLE
[UX] Drop-button displays messed up by 1.7.2

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2806]
## Describe your issue or idea
I've upgraded 3 sites and on each one once the caches are cleared, the Views display is messed up.

Before upgrade (1.7.1 to 1.7.2):
<img width="1190" alt="screen shot 2017-08-21 at 8 41 59 pm" src="https://user-images.githubusercontent.com/871421/29545063-bf7b27a4-86b1-11e7-9c5f-00cfecead0fb.png">

After upgrade and cache clear:
<img width="1540" alt="screen shot 2017-08-21 at 8 44 24 pm" src="https://user-images.githubusercontent.com/871421/29545067-c65b45a4-86b1-11e7-87fe-c4c7be9c1263.png">

---

~PR: https://github.com/backdrop/backdrop/pull/1971~
Latest PR: https://github.com/backdrop/backdrop/pull/1999 (merged)

Example PR w breakpoints adjustment: https://github.com/backdrop/backdrop/pull/2012

**Comment by laryn** [comment]
At a glance, this CSS may be the issue (if I disable it in Firebug things jump back to the expected layout):

`.js .dropbutton-widget { position: absolute; }`

**Comment by jenlampton** [comment]
Can we revert the commit `0e14e648e9ee17e5dd809a1dd65f396075fdd05c` and reopen #2740?

**Comment by quicksketch** [comment]
From #2740:

> This seems to have broken drop-buttons all over the place. Can we please revert the commit 0e14e648e9ee17e5dd809a1dd65f396075fdd05c and revisit?

I can't find any other places that are broken besides Views UI, where it has been broken because of specific-styling in Views that overrides the normal display of drop buttons. I made a PR that effectively reverts the Views UI but keeps everything else in place. Can we find any other places that are broken in the new sandbox?

PR: https://github.com/backdrop/backdrop/pull/1971

Screenshot:
![image](https://user-images.githubusercontent.com/100206/29794945-fc938f1c-8bfe-11e7-8209-7c88e14b1a10.png)

**Comment by jenlampton** [comment]
Wasn't it broken on the Manage Blocks page for layouts as well?

**Comment by olafgrabienski** [comment]
Can confirm: I've had a look at the sandbox site and didn't find any broken page other than the pages mentioned above (Views UI, Manage Blocks).

**Comment by opi** [comment]
@quicksketch I don't wan't to fill another separate PR for a small patch like this, so here is my diff to fix the layout admin page: 

```diff
diff --git a/core/modules/layout/css/layout.admin.css b/core/modules/layout/css/layout.admin.css
index cca062c..edacfd4 100755
--- a/core/modules/layout/css/layout.admin.css
+++ b/core/modules/layout/css/layout.admin.css
@@ -219,7 +219,7 @@
 }
 .layout-editor-block-title .buttons {
   float: right; /* LTR */
-  width: 120px;
+  width: 140px;
 }
 [dir="rtl"] .layout-editor-block-title .buttons {
   float: left;
```

**Comment by jenlampton** [comment]
The menu listing page is also messed up: 
<img width="1229" alt="screen shot 2017-08-31 at 10 54 29 am" src="https://user-images.githubusercontent.com/397895/29937547-c9e6131c-8e3a-11e7-9892-497994b0ca74.png">

I think this is a larger issue than just a few displays. I feel like we're playing whack-a-mole with this one.

**Comment by opi** [comment]
I think that the overflow issue was always there, but since we change buttons alignement from right to left, the overflow become visible. (This overflow is due to a `position:absolute` element with an extra padding in a `position:relative` element, inside the table cell. Table cells have hard times dealing with children's width :/ )

Before changing drop-buttons alignement, this overflow was on the left side of the drop-button, so over a white background, with a maximum width of 2em, so it rarely hide text.

Now it's on the right size, so everyone see the overflow issue. 

In the example of [menu admin page](https://github.com/backdrop/backdrop-issues/issues/2806#issuecomment-326373989), the last `<td>` have no minimum width defined. Regarding existing code every dropbutton containing `<td>` should have a `min-width: 140px` CSS rule.

**Comment by jenlampton** [comment]
> every dropbutton containing <td> should have a min-width: 140px CSS rule.

But every drop-button is a different width. It depends on the width of the text in the first link within.

**Comment by opi** [comment]
Width are also dependent on interface language (think about french or german verbosity...)

I know fixing width is a bad idea, for maintainability and flexibility, but having relative/absolute elements in table/td is hard. We have to define some `min-width`.
One improvement could be a little JS that check for `td.operations` and adjust min-width dynamically, but I'm not a huge fan of use-JS-to-patch-CSS... 
Another solution is to revert https://github.com/backdrop/backdrop-issues/issues/2740 to have the overflow bug less visible (but still present). It's a step back, nobody loves it.

**Comment by opi** [comment]
As dropbutton are added with JS, I found it acceptable to fix the parent min-windth with JS too. It's more a path than a proper solution, but at least it seems to do the trick. See the magic one-liner at https://github.com/backdrop/backdrop/pull/1996

**Comment by jenlampton** [comment]
This looks great @opi!
Views is fixed:
<img width="1177" alt="screen shot 2017-09-07 at 1 27 06 pm" src="https://user-images.githubusercontent.com/397895/30183817-a13258e0-93d0-11e7-8764-cd46215cc0b5.png">
Layotus is fixed:
<img width="1191" alt="screen shot 2017-09-07 at 1 27 19 pm" src="https://user-images.githubusercontent.com/397895/30183831-b2cfe07c-93d0-11e7-8426-3233010368e7.png">
Menu Ui is fixed:
<img width="1181" alt="screen shot 2017-09-07 at 1 27 29 pm" src="https://user-images.githubusercontent.com/397895/30183824-a7e99fae-93d0-11e7-8cc8-228afb86850a.png">

**Comment by quicksketch** [comment]
@opi: Your idea to just use JS to set the width is inspired! We've been struggling with this for ages.

Once equipped with this approach, I thought we might also be able to solve this problem mentioned in Gitter:

> When opening the dropbutton, the button "jumps" out from under the cursor.

For demonstration:

![dropbutton-jumpy](https://user-images.githubusercontent.com/100206/30192447-a519518a-93fc-11e7-8dac-b821e7f8df16.gif)

Combining the approach of setting a min-width for the parent and also setting a min-width on the button itself, we could make the button display as wide as it's widest child, solving the "jumping" problem. But this causes buttons to be wider in places where it may not be convenient, such as the Layouts UI.

Here's the combined fix in action:

Views:
![dropbuttons](https://user-images.githubusercontent.com/100206/30192493-ea175322-93fc-11e7-9a9d-87e74ceafe2f.gif)

Layout list:
![dropbuttons2](https://user-images.githubusercontent.com/100206/30192507-f36fad0c-93fc-11e7-9d37-2e957b256626.gif)

PR at https://github.com/backdrop/backdrop/pull/1971.

**Comment by quicksketch** [comment]
One more note: I put these dropbutton width adjustment's in Seven's script.js, so it only affects Seven and not other themes. This avoids any concerns about matching markup, since Seven will be in control of that. But the reason I moved it there is because we need to wait until after the "Open Sans" font is loaded before calculating widths.

**Comment by opi** [comment]
Good idea to define a min-width on list based on widest child !
I pushed a new PR with a cleanup of your cost, especially the use of a `clone()` element to prevent altering current item CSS.
Adding some comment, as this part could be hard to understand for another contributor in some month ;)
https://github.com/backdrop/backdrop/pull/1999
( added commit is https://github.com/backdrop/backdrop/pull/1999/commits/cd1d9a95152a14cf33fdb14660b2d76315ee3b51 )

**Comment by jenlampton** [comment]
Hm, it looks like we now have a problem in the views UI on narrow screens when the min-width of the widest child is wide and so is the heading:
<img width="1708" alt="screen shot 2017-09-10 at 9 20 19 pm" src="https://user-images.githubusercontent.com/397895/30258426-267c8e9a-966e-11e7-82ff-826af4185e64.png">
Can we make the buttons wrap below the text?

**Comment by opi** [comment]
aaaah, views, my love !

The problem comes from the fact that dropbuttons have a `position:absolute` here ; I manage to use `float` instead and so having the text wrap below the button, but for that I need to tweak some views markup: dropbutton should be printed before title, related PR is https://github.com/backdrop/backdrop/pull/2007. I'm not sure it's the right way to change views content, but let's discuss it on that PR, or create a corresponding issue

**Comment by jenlampton** [comment]
I've pulled in both PRs from https://github.com/backdrop/backdrop/pull/1971 and https://github.com/backdrop/backdrop/pull/2007 to test them together, but the drop-buttons in the views UI are still overlapping the titles.
<img width="306" alt="screen shot 2017-09-14 at 1 38 34 pm" src="https://user-images.githubusercontent.com/397895/30455067-53c87e26-9953-11e7-96c5-37fb7d103bf8.png">

One thing we could do is adjust the breakpoints on the views UI to break to fewer columns at smaller screen sizes.

**Comment by jenlampton** [comment]
I'm seeing a teeny overlap for filter criteria on one breakpoint, but all others look good to me:
<img width="1184" alt="screen shot 2017-09-14 at 4 07 05 pm" src="https://user-images.githubusercontent.com/397895/30459688-0b4279d6-9967-11e7-85bd-84e98052e886.png">
<img width="938" alt="screen shot 2017-09-14 at 4 07 21 pm" src="https://user-images.githubusercontent.com/397895/30459695-100d3460-9967-11e7-9d98-c0218f022407.png">
<img width="943" alt="screen shot 2017-09-14 at 4 07 35 pm" src="https://user-images.githubusercontent.com/397895/30459696-1339a3e4-9967-11e7-9ab6-e5486829581d.png">
<img width="714" alt="screen shot 2017-09-14 at 4 07 52 pm" src="https://user-images.githubusercontent.com/397895/30459697-157df51a-9967-11e7-8eda-be150d523a01.png">
<img width="703" alt="screen shot 2017-09-14 at 4 08 13 pm" src="https://user-images.githubusercontent.com/397895/30459701-17a98f70-9967-11e7-8961-a7ae0a2b43e9.png">

**Comment by quicksketch** [comment]
I've merged @opi's latest PR at https://github.com/backdrop/backdrop/pull/1999 that fixes 90% of the problems. That should make it easier @jenlampton for you to file a new PR directly against 1.x if we want to change the Views breakpoints.

**Comment by jenlampton** [comment]
ty! That's much better than what we had before :)

**Comment by jenlampton** [comment]
There's still at PR at https://github.com/backdrop/backdrop/pull/2012 that changes the Views UI to a 2-column layout on smaller screen sizes. Is that the way we want to go with this, or do we want to try to float these drop-buttons instead of absolutely positioning them?

**Comment by quicksketch** [comment]
I rerolled and tried out the PR at https://github.com/backdrop/backdrop/pull/2012. Overall, I don't think it's an improvement. The 2-columns followed by a very-wide 3rd column seems really difficult for me to navigate. While the 2-columns look good, the single 3rd column is actually so wide it introduces new difficulties.

This issue has been open for so long, I think we should close it out and pursue a new solution for Views in a separate issue, if we deem it necessary.
