### ISSUE TITLE
Wrong URLs in the robots.txt comments

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#2807]
## Describe your issue or idea
We have two URLs seems obsolete in comments part of robots.txt:

```
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/wc/robots.html
#
# For syntax checking, see:
# http://www.sxw.org.uk/computing/robots/check.html
```

### Expected behavior (if reporting a bug)
First URL should be replaced with more actual one:
`http://www.robotstxt.org/robotstxt.html`

and second can be just removed.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1979

**Comment by klonos** [comment]
Thanks for filing this issue @findlabnet 👍 

...marking as NR for deleting the link to the syntax checking URL. Anyone have any clue why that specific site was selected? Should we remove or select a few more?

**Comment by opi** [comment]
ideas:
- use canonical http://www.robotstxt.org for main link, or even https://en.wikipedia.org/wiki/Robots_exclusion_standard
- use http://www.robotstxt.org/checker.html for syntax checking

**Comment by klonos** [comment]
I say lets just go with http://www.robotstxt.org/robotstxt.html and http://www.robotstxt.org/checker.html

PR up for review.

**Comment by opi** [comment]
I'm not a huge fan of http://www.robotstxt.org/checker.html, as it only mention a Google tool with required account, but I can deal with it.
RTBC for me.

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/1979 into 1.x and 1.7.x.
