### ISSUE TITLE
Add file humans.txt

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#2812]
## Describe your issue or idea

We can (and should) be first of most popular CMS provides such file, for more info please see http://humanstxt.org
IMO, this is right way to memorize most valuable members of our community, part of them may be not with us already, but 

> The internet is for humans...

@klonos, I think this is task especially for you ;-)

**Comment by klonos** [comment]
@findlabnet it _was_: #1319 😄
