### ISSUE TITLE
Use class instead of ID for layout admin table.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2813]
Since we are trying to get away from using IDs in core, this is part of our effort to clean up some admin tables.

Tagging for 1.8 since there's a markup change. Impact on community is negligible since it's not likely admin themes would target this table specifically.

**Comment by opi** [comment]
Self-reminder: `git grep "'#attributes' => array('id' =>"` to find some more.

**Comment by jenlampton** [comment]
This looks good to me. Marking RTBC Code changes are clean, and table looks the same after the change as before.
<img width="1205" alt="screen shot 2017-08-31 at 12 48 48 pm" src="https://user-images.githubusercontent.com/397895/29942451-c6aa71ba-8e4a-11e7-9cb3-7e734a2d0ede.png">

**Comment by quicksketch** [comment]
Thanks @opi! Merged https://github.com/backdrop/backdrop/pull/1973 into 1.x for 1.8.0.
