### ISSUE TITLE
[UX] Use "configure" on the Image Styles UI

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2817]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/771. We missed a spot where we should be using `Configure` instead of `Edit`: The image styles user interface.

---
PR: https://github.com/backdrop/backdrop/pull/1977

**Comment by quicksketch** [comment]
Overall looks pretty good but tests need to be updated for the new paths.

**Comment by jenlampton** [comment]
Tests updated, passing locally. Pushed a new PR.

**Comment by quicksketch** [comment]
PR looks great, but I found a problem that backdrop_goto_deprecated() doesn't handle wildcards properly. It's a separate issue but it affects this PR substantially, since the image style UI is full of wildcard paths. I filed a new issue at #2833, that doesn't need to hold this one up though.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1977 into 1.x for 1.8.0. Thanks @jenlampton! Let's continue getting the redirects working fully in #2833.
