### ISSUE TITLE
How to add JS settings that don't overwrite each other

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2818]
I have a custom JS file that creates a caption in a lightbox popup by getting it from the image's attribute. The attribute it uses is configurable, from the field formatter (alt or title), so I need to send the caption setting to the JS file via backdrop_add_js().

I have it working, however when there are two different fields on the one node, the latter overwrites the former. Is there a way I can send a setting to JS without multiple fields overwriting each other?

I know I can create an array of settings, but then how do I know which setting to get from the array in the JS file?

**Comment by docwilmot** [comment]
You'd need to send an array keyed by something unique I suspect. Image path maybe? I'd understand more clearly with code examples.

**Comment by BWPanda** [comment]
@docwilmot Here's the module I'm writing: https://github.com/BWPanda/featherlight/

Here's where I'm sending the setting to the JS: https://github.com/BWPanda/featherlight/blob/master/featherlight.module#L74
And here's the JS itself: https://github.com/BWPanda/featherlight/blob/master/js/featherlight.caption.js

Thanks for the assistance!

**Comment by docwilmot** [comment]
I'm thinking
```
  backdrop_add_js(array('featherlight' => array(
    $item['url'] => array(
      'caption' => $variables['caption'],
  ))), 'setting');
```
And
```
    $.featherlight.prototype.afterContent = function() {
      var imgData= this.$currentTarget.find('img');
      var imgURL= imgData.getURL();     // This is fake; you'd need to figure how to get the img url.
      var captionData = imgData.attr(settings.featherlight);
      var caption = captionData[imgURL]['caption'];
      this.$instance.find('.featherlight-caption').remove();
      $('<div class="featherlight-caption">').text(caption).appendTo(this.$instance.find('.featherlight-content'));
    };
```

**Comment by BWPanda** [comment]
Thanks, I'll try and have a play tomorrow.

**Comment by BWPanda** [comment]
Thanks for your assistance @docwilmot! Using your code as an example, I came up with the following working solution:

```php
  $itemFID = 'id-' . $item['fid']; // Cause numbers as array keys didn't seem to work...

  backdrop_add_js(array('featherlight' => array(
    $itemFID => array( // Key by the unique file ID.
      'captionAttr' => $variables['caption'],
    ),
  )), 'setting');

  $image_variables = array(
    'uri' => $item['uri'],
    'width' => $item['width'],
    'height' => $item['height'],
    'alt' => $item['alt'],
    'title' => $item['title'],
    'attributes' => array( // Add the file ID to the img tag to retrieve later via jQuery.
      'data-file-id' => $item['fid'],
    ),
  );
```

```js
    $.featherlight.prototype.afterContent = function() {
      var imgData = this.$currentTarget.find('img');
      var fileID = imgData.attr('data-file-id');
      var captionAttr = settings.featherlight['id-' + fileID]['captionAttr'];
      var caption = imgData.attr(captionAttr);
      this.$instance.find('.featherlight-caption').remove();
      $('<div class="featherlight-caption">').text(caption).appendTo(this.$instance.find('.featherlight-content'));
    };
```
