### ISSUE TITLE
Watchdog logs flooded with views "Missing join" notices

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2820]
## Describe your issue or idea
In the views module, if a join is missing, a watchdog log is entered. There's also this crazy hack in Views for making a table always available, by adding a join:
```php
  $data['views']['table']['join'] = array(
    // #global is a special flag which let's a table appear all the time.
    '#global' => array(),
  );
```
We need to check for this crazy hack before we log to watchdog, so that watchdog doesn't get flooded when we intentionally created a join that won't join.

### Steps to reproduce (if reporting a bug)
* Install the [Similar Entries](https://github.com/backdrop-contrib/similar) module
* Place the Similar Entries block on the default layout
* Create and view a node
* Check the logs

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1978

**Comment by klonos** [comment]
I have repeated the STR in a PR sandbox that does not contain the changes by @jaymejohnson and got the "Missing join: similar_entries node" errors each time a node was viewed. I then repeated the STR in @jenlampton's PR sandbox and I did not get any "Missing join" notices (I did get a couple of php notices, but I believe that these were related to the Similar Entries contrib module, so I have filed https://github.com/backdrop-contrib/similar/issues/10 for that).

...other than that, the PR seems to be fixing the problem, so RTBC from me 👍

**Comment by quicksketch** [comment]
PR looks great but it desperately needs a code comment explaining just what the heck `#global` is. Perhaps copy the code comment from `views_views_data()` and add a comment `See views_views_data().` ?

**Comment by jenlampton** [comment]
can do.

**Comment by jenlampton** [comment]
@quicksketch like this? https://github.com/backdrop/backdrop/pull/1978/files

**Comment by quicksketch** [comment]
Perfect, merged https://github.com/backdrop/backdrop/pull/1978 into 1.x and 1.7.x!
