### ISSUE TITLE
[DX] Rename the 'url_alias' table to something sensible like 'path'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2821]
because I can never find it when I need it...

**Comment by oadaeh** [comment]
And then the rest of the world, who is used to looking for it by 'url_alias', won't be able to find it.

**Comment by jenlampton** [comment]
Yeah. Since we renamed path aliases to URL Aliases, I think this issue should be closed. Makes sense now :)

**Comment by klonos** [comment]
@bugfolder perhaps this provides some insight as to why we started using "URL alias" in the UI/comments/documentation.
