### ISSUE TITLE
[UX] Update the text for version incompatability

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2822]
## Describe your issue or idea
On the modules page we indicate when a module is not compatible with Backdrop 1.x by putting big bold text in the description column that says **This version is not compatible with Backdrop CMS 1.x and should be replaced.**

I'd like to soften this language a little, and change it to simply **This version is not compatible with Backdrop CMS 1.x**.

In a lot of cases, the module that is not compatible is part of a larger project and can't be "replaced" without also removing the other modules that are compatible. In those cases, this text is misleading.

---
PR https://github.com/backdrop/backdrop/pull/1980

**Comment by klonos** [comment]
PR looks good and the tests are green, so RTBC from me 👍

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/1980 into 1.x and 1.7.x. Thanks!
