### ISSUE TITLE
[UX] Fix the sort order on the admin/config page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2828]
## Describe your issue or idea

This is a spin-off from https://github.com/backdrop/backdrop-issues/issues/506 for cleaning up the admin/config page.

* The categories seem to be in random order. They should be in alphabetical order (unless somebody has another suggestion).
* The items under each category seem to be randomly placed as well. They should be listed alphabetically (unless somebody has another suggestion).
* We use a two-column layout that is not responsive and by default makes the page unnecessarily long on wide screens. Perhaps we should consider using a responsive grid or an accordion or some other solution that wraps the categories under each other in small screens.
---
PR https://github.com/backdrop/backdrop/pull/1982

**Comment by jenlampton** [comment]
> The items under each category seem to be randomly placed as well. They should be listed alphabetically (unless somebody has another suggestion).

These are using the same order the items are in in the menu. That way if someone rearranges their menu, that same order will be reflected here. I think this is a fine solution for now, and I'm going to focus on the quick/easy fix for the category order.

**Comment by klonos** [comment]
PR does not seem to do the trick :(

**Comment by jenlampton** [comment]
@klonos it should work for you now. (I'm also bumping the milestone to 1.8 since there's a markup change to make the layout responsive.)

**Comment by olafgrabienski** [comment]
I've had a look at the sandbox site of the PR. I had to flush all caches before, then the sort order became alphabetical. The responsive layout seems also to work fine, nice!

**Comment by quicksketch** [comment]
Thanks @olafgrabienski for reviewing!

This looks good to me as well. I find it a little weird that the order in the menu doesn't match the page layout (I would expect it to match, even if they're non-alphabetical). But if we rearrange the menu to be alphabetical by default, that would make them consistent at least initially.

Anyway, this improves several areas, including making the sections have a reasonable order and making the page responsive in Seven.

Merged https://github.com/backdrop/backdrop/issues/1982 into 1.x for 1.8.0.

**Comment by klonos** [comment]
Great job @jaymejohnson 👍
