### ISSUE TITLE
Theme thumbnails missing from /admin/appearance

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2831]
We must have broken something in one of our recent commits. The `<img>` tags are not rendered at all and there is a series of 3 theme warnings in the log (as many as the number of thumbnails that are supposed to be rendered in that page):

`Theme hook "path" not found.`

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1985

**Comment by klonos** [comment]
...I believe it must be https://github.com/backdrop/backdrop/commit/88d243bd46d2eba52195da1fa0da1a385abf7c08

**Comment by klonos** [comment]
I think it must be this change specifically: https://github.com/backdrop/backdrop/commit/88d243bd46d2eba52195da1fa0da1a385abf7c08#diff-4069bef0c8037fa96f53813774940102R102

**Comment by klonos** [comment]
...we should add tests to ensure that this does not break in the future. But I don't speak test language 😞

**Comment by quicksketch** [comment]
Thanks, for something this particular, tests are a bit over the top. Thanks for the fix, and sorry for having caused the problem in the first place. Merged https://github.com/backdrop/backdrop/issues/1985 into 1.x, which is the only place this problem should exist.
