### ISSUE TITLE
[UX] Form elements with errors are not showing colors in Basis

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2832]
## Describe your issue or idea
When a form fails validation, it's helpful to be able to easily see which field has an error. That feature is provided in Backdrop core, but the Basis theme overwrites the color coding with it's own form element styles.

### Steps to reproduce (if reporting a bug)
* Fill out a form in a way that you know will fail
* note the border color, text color, and background colors are not red/red/pink, as they should be

### The fix
I recommend we add more specific form-element error syles to Basis, overriding the default, to add back the missing color coding.

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2006

![backdrop_basis_error](https://user-images.githubusercontent.com/159548/30274266-f55476f4-96fc-11e7-9564-1357c9adfb2a.png)

note: the style of the Timezone fieldset is due to a too generic `.error` style in `skin.css`, intended for status messages.

**Comment by jenlampton** [comment]
This looks great @opi, thank you :)

>  the style of the Timezone fieldset is due to a too generic .error style in skin.css, intended for status messages.

I believe system's `.error` class was intended for form elements as well as error messages, and also for table-row styles. That said, I don't really mind the fieldset turning pink like this once it gets that class on it.  Let's leave it like this for now and let @wesruv create a separate issue if he has specific feelings about what a tableset with an error should look like.

**Comment by opi** [comment]
> That said, I don't really mind the fieldset turning pink like this

Me neither, and at least error fields are now visible. Thanks for your feedback

**Comment by quicksketch** [comment]
Looks great to me too. Thanks @opi! Merged https://github.com/backdrop/backdrop/pull/2006 into 1.x and 1.7.x!
