### ISSUE TITLE
Add support for wildcards in deprecated path redirects.

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2833]
## Describe your issue or idea

We have used backdrop_goto_deprecated() in many places to handle old-to-new path changes. In most cases, these redirects work great. But if the redirect contains a wildcard, the redirect goes to a new URL with the name of the wildcard in the final URL itself, rather than performing the substitutions.

### Steps to reproduce (if reporting a bug)

- Install Backdrop.
- Go to a path that contains a wildcard redirect, such as `admin/structure/layouts/manage/%layout_tempstore/settings`. An example would be `admin/structure/layouts/manage/home/settings`.

### Actual behavior (if reporting a bug)

- User is redirected to `/admin/structure/layouts/manage/%25layout_tempstore/configure`

### Expected behavior (if reporting a bug)

- User should be redirected to `/admin/structure/layouts/manage/home/configure` (the wildcard `%layout_tempstore` replaced with `home`).

We have about a two dozen path redirects right now, and 6 of them seem to have this problem:

- `admin/structure/layouts/manage/%layout_tempstore/edit`
- `admin/structure/layouts/manage/%layout_tempstore/settings`
- `admin/config/search/redirect/edit/%redirect`
- `admin/config/search/redirect/delete/%redirect`
- `admin/config/search/path/delete/%path`
- `admin/config/search/path/edit/%path`

----

PR https://github.com/backdrop/backdrop/pull/1986

Advocate: @quicksketch

**Comment by jlfranklin** [comment]
The `backdrop_goto_deprecated()` function was a wrapper for `backdrop_goto()`, adding a call to `watchdog()` to the process.  It was originally used in a menu router entry replacing `backdrop_goto()` when `WATCHDOG_DEPRECATED` was added in 1.5. 

This is pushing the scope of `backdrop_goto_deprecated()` far beyond what is intended.  Think of it this way: If you wouldn't add this PR to `backdrop_goto()`, then it doesn't belong in `backdrop_goto_deprecated()`, either.

Instead, maybe this functionality should be more integrated with the menu router itself, adding a `'#deprecated'` key, a way to specify the new path, and a way to translate the callback and arguments from the old form to the new.

**Comment by quicksketch** [comment]
Yeah I thought this might be pushing it a bit too far as well. Rather than adding a new ability to the menu system, we could make a new function that is intended to be a menu callback, rather than calling `backdrop_goto_deprecated()` directly. The new menu callback would include the wildcard replacement, then just called backdrop_goto_deprecated().

**Comment by quicksketch** [comment]
I updated https://github.com/backdrop/backdrop/pull/1986 with this new approach, introducing a new function made for being a menu callback named `system_redirect_deprecated_page()`.

**Comment by quicksketch** [comment]
I'm revisiting this issue since it came up again in https://github.com/backdrop/backdrop-issues/issues/4899.

I've updated the PR at https://github.com/backdrop/backdrop/pull/1986 based on @jlfranklin's feedback (thanks for that!). And although it has now been 10(!) releases since we introduced `backdrop_deprecated_goto()` I think this is still a great enhancement that will help us in the future and allow for bigger renames (such as changing `people` to `accounts`, if that's something we want to pursue).

**Comment by quicksketch** [comment]
I'm willing to advocate for this issue for 1.19.0 now that I feel it is very close.

**Comment by quicksketch** [comment]
I updated https://github.com/backdrop/backdrop/pull/1986 again based on @jlfranklin's latest code review.

**Comment by jlfranklin** [comment]
Does this warrant a Change Record?

**Comment by quicksketch** [comment]
Yep, I wrote up a change record at https://docs.backdropcms.org/change-records/system_redirect_deprecated_page-should-be-used-for-deprecated-paths, please let me know if you have any suggestions. Thanks!

**Comment by quicksketch** [comment]
I have merged in https://github.com/backdrop/backdrop/pull/1986 into 1.x for 1.19.0. Thanks @jlfranklin for your reviews and suggestions on this issue!
