### ISSUE TITLE
Views to 404: Logs flooded with "Cannot modify header information"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2835]
## Describe your issue or idea

I have a view at `articles` and my aliases for my article nodes set to `articles/[node:title]`, as you do.  But I noticed that when I mis-typed the URL for an individual article, instead of getting a 404, I see the results of that view.

No problem, I thought, I'll just add a global NULL argument and force the page to 404 if any argument is present. That way if the path isn't a node alias and falls back to the view, any path other than `articles` will 404. Problem solved!

...or so I had thought. Checking back on the site this morning showed hundreds of these messages in my logs:

```
Warning: Cannot modify header information - headers already sent by (output started at backdrop/core/includes/bootstrap.inc:1723) in backdrop_send_headers() (line 1540 of backdrop/core/includes/bootstrap.inc).
```

One was generate for every 404! It looks like both Views and Backdrop core are attempting to set the 404 header, causing a little havoc on my site.

I tracked the problem down to a line in `views_plugin_display_feed.inc`:
```php
return backdrop_not_found();
```

Returning `backdrop_not_found()` doesn't make any sense, since that function doesn't have any return value. In fact, on the docs page for that function it says:

```
Page callback functions wanting to report a "page not found" message should return MENU_NOT_FOUND instead of calling backdrop_not_found(). However, functions that are invoked in contexts where that return value might not bubble up to menu_execute_active_handler() should call backdrop_not_found().
```

Replacing the code in question with the recommended alternative did the trick, and prevented the flooding in my logs.

### Steps to reproduce (if reporting a bug)

1) build a view at `articles`
2) set a global null argument 
3) add validation criteria for when the argument IS present
4) choose PHP and enter the following code
```php
if ($argument != '') {
return FALSE;
}
```
5) Visit the url `articles/test`
6) check the logs
7) Create a node at `page-not-found`
8) Update your 404 settings to redirect to this page

---
~~PR: https://github.com/backdrop/backdrop/pull/1990~~
Fllow-up PR: https://github.com/backdrop/backdrop/pull/1992

**Comment by quicksketch** [comment]
We should update not only calls to `return backdrop_not_found()` but also `return backdrop_access_denied()`, which is the exact same set of problems but under different circumstances. See https://github.com/backdrop/backdrop/pull/1990#pullrequestreview-60469597.

**Comment by jenlampton** [comment]
Nice catch! I've fixed that one too and pushed up a new PR.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1990 into 1.x and 1.7.x. Thanks!

**Comment by jenlampton** [comment]
Hm. I'm not sure this fix is doing what we need... reopening.

Before this change Backdrop was able to successfully locate my page-not-found page and return that, but after the change all I see this this...

<img width="1082" alt="screen shot 2017-09-04 at 4 29 00 pm" src="https://user-images.githubusercontent.com/397895/30040032-33494044-918e-11e7-9888-899e1640dd39.png">

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop/backdrop/pull/1992 into 1.x and 1.7.x.
