### ISSUE TITLE
Menu callbacks appearing on admin/config page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2837]
## Describe your issue or idea

After we introduced `backdrop_deprecated()` we made it so that we could have a bunch of menu callbacks that would be temporary. But when we did that, other places in core that assumed all menu callbacks should appear (like the admin/config page) started displaying callbacks as well as MENU_NORMAL_ITEMs. (See https://github.com/backdrop/backdrop-issues/issues/1529#issuecomment-327033884)

This issue fixes that problem by pulling only MENU_NORMAL_ITEMs for our admin listings.

---
PR: https://github.com/backdrop/backdrop/pull/1991

**Comment by quicksketch** [comment]
Thanks! Simple fix. This had a conflict in 1.7.x, so I've only merged it into 1.x for 1.8.0.
