### ISSUE TITLE
[UX] Rename the file field 'Description' field to 'Label'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2838]
## Describe your issue or idea

When you are using a filefield, a site architect has the opportunity to enable a  `Description` field. Unfortunately, that's not actually a description field. As it says in the fine print - it's a label: `may be used as the label of the link to the file.`.

**Comment by opi** [comment]
Always drive me nuts during all this Drupal years ;)
*Adding an incentive Github label*

**Comment by BWPanda** [comment]
I believe this has since been fixed in https://github.com/backdrop/backdrop-issues/issues/4178
