### ISSUE TITLE
[UX] Make the "All URL aliases" label clickable

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#2839]
When visiting the URL Aliases bulk operation page (`admin/config/urls/path/bulk-update`), I would like to click on the "All URL aliases" label, but so far only the checkbox can be clicked, because the text is not a `<label>` form element.

This checkbox is added with javascript, so following this path the incoming PR will add the `<label>` tag with JS too.

**Comment by opi** [comment]
Note that the margin-right for the checkbox is updated to 10px to match regular form item spacing.

**Comment by opi** [comment]
( By testing this PR, one can try to reproduce [this bug](https://github.com/backdrop/backdrop-issues/issues/2477) with Safari browser )

**Comment by Dinornis** [comment]
Sorry for the delayed reply.
The label nor the checkbox works properly in Safari.
Clicking the label or checkbox directly does not do anything.

**Comment by opi** [comment]
This current issue is about making the label clickable. I'm closing this as the Safari bug is addressed in a specific issue https://github.com/backdrop/backdrop-issues/issues/2477 ;
