### ISSUE TITLE
[UX] Use 'Configure' on field settings (not 'Edit')

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2840]
## Describe your issue or idea

On the manage fields page I notice we are still using 'Edit' where we mean 'Configure'
<img width="1198" alt="screen shot 2017-09-07 at 1 28 47 pm" src="https://user-images.githubusercontent.com/397895/30183786-84fd6a20-93d0-11e7-8d95-87445daf3297.png">

After change:
<img width="1183" alt="screen shot 2017-09-07 at 1 54 30 pm" src="https://user-images.githubusercontent.com/397895/30184814-207ddb3a-93d4-11e7-8667-b4e708c294e9.png">

---
PR: https://github.com/backdrop/backdrop/pull/1998

**Comment by quicksketch** [comment]
Thanks, simple fix that brings consistency to our Configure/Edit terminology. Merged https://github.com/backdrop/backdrop/pull/1998 into 1.x and 1.7.x.
