### ISSUE TITLE
Create a new, resized version when inserting an image with a different width/height in the editor

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2841]
When you add an image to the editor using the Image button, you have the option to specify a custom width and height.

![screenshot-2017-9-8 edit post your first post peter anderson](https://user-images.githubusercontent.com/2385329/30193650-a832b218-9491-11e7-8164-feeecbdf3da7.png)

If you do, the inserted image is shown at the custom size. However the image itself is still full-size. This isn't good, as users are having to download a full-size image to just view a small version of it.

I recommend instead automatically resizing a copy of the image and then inserting that, preferably with an option to automatically create a link to the full-size version as well. This is basically what the [Image Resize Filter](https://www.drupal.org/project/image_resize_filter) Drupal module does.

I started [migrating that module to Backdrop](https://github.com/backdrop-ops/contrib/issues/227), but I now think this'd be better in core.

**Comment by quicksketch** [comment]
I posted a comment over in the contrib issue (https://github.com/backdrop-ops/contrib/issues/227#issuecomment-327989354). Initially, I think this would make more sense as a contrib module.

**Comment by BWPanda** [comment]
Closing in favour of https://github.com/backdrop-ops/contrib/issues/227 for now.
