### ISSUE TITLE
CKEditor: Long link URLs being truncated

### ISSUE THREAD

**Issue by freedog96150** [backdrop/backdrop-issues#2843]
## Issue
Editors using a basic subset of ckeditor tools are finding that when they paste long query style URL's into the modal box that is presented by the link function, that URL is truncated, which breaks the link.  Shorter links work as expected.

## Expected behavior
The link function accepts any valid link.

## Observed Workaround
Switching to HTML Editor allows the complete URL to be entered into the code and in view it works as expected.  Since exposing HTML Editor can be a security issue, it is preferred that the WYSIWYG editor work as expected.

##  Comments
Seems that input filtering controls this either in core or at the plugin level.  Would be nice if this was exposed as an admin setting so that it can be en/dis/abled or the value that controls the length of the truncate can be modified.

---

~PR by @alexfinnarn : https://github.com/backdrop/backdrop/pull/2032~ merged
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2940

**Comment by olafgrabienski** [comment]
Thanks for posting the issue @freedog96150 . Will try to reproduce it, can you provide an example link?

**Comment by freedog96150** [comment]
`http://www.bootfitters.com/reviews/results?keys=&field_boot_category_tid%5B%5D=2&year%5B%5D=2018&gender=All&hike=All&width%5B%5D=narrow&field_cantology_compatible_value=All&sort_by=field_boot_msrp_value&sort_order=DESC`

**Comment by olafgrabienski** [comment]
Thanks for the link. I played around a little bit and can confirm that a URL with more than 128 characters is truncated at the moment when you type or paste it in the URL field of the CKEditor link modal.

Examples:

- `http://twitter.com/intent/tweet?url=http://www.example.com/a-test-post-i-want-to-share-on-twitter-and-which-has-a-quite-long-url` (128 characters, works fine)
- `http://twitter.com/intent/tweet?url=http://www.example.com/a-test-post-i-want-to-share-on-twitter-and-which-has-an-even-longer-url` (130 characters, is truncated after the last `u`)

**Comment by olafgrabienski** [comment]
I guess the truncating is a bug, and it contradicts the (not directly related) help text for the *Convert URLs into links* option on the text format configuration page:

> URLs longer than this number of characters will be truncated to prevent long strings that break formatting. **The link itself will be retained; just the text portion of the link will be truncated.**

I've no idea where the truncating of the link happens, will tag the issue with "status - needs feedback".

**Comment by jenlampton** [comment]
@olafgrabienski thanks for confirming. I believe the URL filter might be the problem here. Do either of you have the URL filter enabled on that text format?
<img width="958" alt="screen shot 2017-09-11 at 2 00 52 pm" src="https://user-images.githubusercontent.com/397895/30296626-af263b48-96f9-11e7-8034-57dec5322b9a.png">
If so, can you turn it off and see if the link is not truncated?

The truncate is supposed to apply to the text between the `<a>` tags, not to the `href` attribute. This definitely sounds like a bug.

**Comment by olafgrabienski** [comment]
@jenlampton Forgot to mention that I already tried to disable the *Convert URLs into links* filter, which didn't change the behaviour. (Actually I tried it more for curiosity because the default *Maximum link text length* of 72 characters however doesn't match the 128 characters limit of the bug / the link itself.

**Comment by jenlampton** [comment]
Drat.

**Comment by olafgrabienski** [comment]
I guess it's an issue with the *widget* where you past or type the URL. IIRC, the widget is a 'normal' URL field and an autocomplete (for local links, see #1206) at the same time.

**Comment by freedog96150** [comment]
@jenlampton I can also confirm that prior to submitting this inquiry I had disabled the _Convert URL into Links_ option as well as changed the _Maximum link length text_ to a large 3 digit number.

**Comment by alexfinnarn** [comment]
I can confirm that adding `'#maxlength => 512'` to https://github.com/backdrop/backdrop/blob/1.x/core/modules/filter/filter.pages.inc#L52 can mitigate the chopped off URLs, however, you could always be upping that value if people have bigger and bigger URLs they want to enter. 

So, I think something should be done in a validation step to inform the user and just reject the URL or make a stand on the number of characters that are reasonable in a URL.

**Comment by olafgrabienski** [comment]
From an editor's perspective: Increasing the number of characters is much better than rejecting longer URLs. Can't evaluate the `maxlength` approach from a technical standpoint though. @jenlampton What do you think about it?

If we (increase and) have to limit the number by `maxlength`, 512 characters seems reasonable. The example link posted by @freedog96150 - https://github.com/backdrop/backdrop-issues/issues/2843#issuecomment-328562490 - has 218 characters, so in this case 256 would also be an acceptable limit. I don't see such long links frequently, but I guess there are legitimate URLs with even more characters, so I'd prefer 512 seems about 256.

**Comment by jenlampton** [comment]
I don't really understand why there needs to be a maxlength...

**Comment by olafgrabienski** [comment]
Neither do I but I'm not a code expert. @alexfinnarn - can you clarify the approach?

**Comment by jlfranklin** [comment]
In general, the advice is to keep URL lengths below 2000 characters [[1]](https://stackoverflow.com/questions/29458445/what-is-a-safe-maximum-length-a-segment-in-a-url-path-should-be) [[2]](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers), and under 256 is even better.

**Comment by freedog96150** [comment]
Not that this is important, but the link I pasted above was generated by Backdrop exposed filters.  I suppose that 256 characters is reasonable, but 512 leaves more options for queries using a larger set of exposed filters.  Linking those query strings into published articles seeds those queries on the site and exposes more potential content to the reader. 

So if expanding maxlength becomes an issue, can this problem be tackled by using an onboard URL shortener?  Or by restructuring how Backdrop creates it query URL strings?

**Comment by jenlampton** [comment]
>  Or by restructuring how Backdrop creates it query URL strings?

FWIW I always change the way views builds it's query string by overriding the default keys to remove things like `field_` from the beginning of each one. I have been thinking that should be something we do for people all the time, anyway.

**Comment by alexfinnarn** [comment]
Regarding "#maxlength", there doesn't need to be one explicitly set; however, the Form API sets that element to a default of 128 characters https://api.backdropcms.org/form_api#textfield. To allow for more characters on that field the easiest thing to do is increase the max length on https://github.com/backdrop/backdrop/blob/1.x/core/modules/filter/filter.pages.inc#L52.

**Comment by olafgrabienski** [comment]
Thanks for the clarification @alexfinnarn ! My impression is that there is some consensus to add a maxlength of 256: an improvement without bloating the size too much, and in combination with the upcoming [smarter query strings](https://github.com/backdrop/backdrop-issues/issues/2893) even an improvement for more complex exposed filter use cases.

Are there any objections to increase (add) the maxlength of 256 on https://github.com/backdrop/backdrop/blob/1.x/core/modules/filter/filter.pages.inc#L52?

**Comment by alexfinnarn** [comment]
I was going to add a test to that PR, but that would really be testing the Form API and `maxlength` so it didn't make sense to me.

**Comment by olafgrabienski** [comment]
Thanks for the PR, @alexfinnarn ! I made a test post with some links in the PR's sandbox site - works perfect: URLs with more as 128 (and up to 256) characters are now accepted by the modal form.

Tagging as "needs review" to get another pair of eyes on it.

**Comment by quicksketch** [comment]
Going even longer would be okay to me. But starting at 256 characters sounds good. I've merged the existing PR at https://github.com/backdrop/backdrop/pull/2032 into 1.x and 1.8.x.

**Comment by jenlampton** [comment]
I'm still having issues with this. I think when we switched from a plain link field to an autocpmplete field we lost the maxlength setting. What I see in there now is:

```
  // Use a "textfield" rather than "url" to allow relative paths.
  $form['href'] = array(
    '#title' => t('Link destination'),
    '#type' => 'textfield',
    '#element_validate' => array('_filter_format_editor_link_url_validate'),
    '#placeholder' => ' ',
    '#default_value' => isset($values['href']) ? $values['href'] : NULL,
    '#parents' => array('attributes', 'href'),
    '#wrapper_attributes' => array(
      'data-editor-image-toggle' => t('Link to existing content'),
    ),
    '#weight' => -10,
    '#autocomplete_path' => 'filter-link/autocomplete',
    '#description' => t('Start typing to see a list of suggestions, enter the relative path to another page, or enter an external URL.<br>Examples: <em>About Us</em>, <em>/about</em>, or <em>http://backdropcms.org</em>'),
  );
```

Aadding `'#maxlength' => 256,` fixes the problem again for me.

**Comment by jenlampton** [comment]
PR provided updates the maxlength for both text and image links

**Comment by olafgrabienski** [comment]
>  klonos added pr - ready to be committed pr - works for me

Tested in the sandbox, works for me as well.

**Comment by quicksketch** [comment]
Looks like there's an unrelated change in the PR: https://github.com/backdrop/backdrop/pull/2940/files#r341346794

**Comment by jenlampton** [comment]
Removed.

**Comment by stpaultim** [comment]
I just experienced this problem this week for the first time.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.14.x. Thanks!
