### ISSUE TITLE
Cannot delete cloned default Views

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#2845]
## Describe your issue or idea
If you clone a module-provided View (like the User Admin list for example), The clone cannot be deleted

### Expected behavior (if reporting a bug)
A cloned View should be considered User-defined, and no longer module-provided. For example, I wanted to delete about 3000 spam users from a site, so cloned the user view (the default allows 50 only operations at a time) to make it possible to delete a few hundred at a time. When I was done I tried to delete the clone; not possible. That shouldnt be so.

### Relevant version/system information (if applicable)
Latest Views core.
Current Backdrop code only allows deleting user-provided Views. Cloned Views keep the 'module' line in their config, which thus makes them impossible to delete in the UI. We should remove the `module` key during cloning as well as changing `storage` to 1.

### Test case

1. Enable a default view (aka module provided), like the *Recent comment* one. You should be able to revert it, but not to delete it.

2. Clone a default view (aka module provided), like the *Recent comment* one. You should be able to delete the clone, not to revert it.

Last PR: ~~https://github.com/backdrop/backdrop/pull/2045~~ https://github.com/backdrop/backdrop/pull/2062

**Comment by klonos** [comment]
> We should remove the `module` key during cloning as well as changing `storage` to 1.

Sounds right to me.

**Comment by olafgrabienski** [comment]
@akalata - Thanks for the PR! I guess as long as one doesn't comment on the issue itself, the participants won't get noticed necessarily of a related PR.

(Commenting therefore now without having tested the PR and going to label the issue with PR related tags.)

**Comment by opi** [comment]
Made a review on https://github.com/backdrop/backdrop/pull/2031#pullrequestreview-73781765, and ask for some little changes. Change issue label accordingly.

**Comment by opi** [comment]
@akalata : do you want to work on https://github.com/backdrop/backdrop/pull/2031 again ? otherwise do you mind if I take over your PR to finish the job ? ;)

**Comment by akalata** [comment]
hi @opi, please take it over if you have time. I'm swamped, sorry!

**Comment by opi** [comment]
New pull request to test and review: https://github.com/backdrop/backdrop/pull/2045

**Comment by laryn** [comment]
Just tested the PR and it works fine functionally from what I can see. I could clone a view, make changes, save, and then delete the cloned view.

**Comment by quicksketch** [comment]
Oops, dang. Sorry for marking this RTBC. The code itself does look great and thanks @laryn for confirming. However the test failures are legitimate and related to the Revert functionality. They just need to be updated to cover the new functionality.

**Comment by opi** [comment]
Actually the views module use `$view->clone_view()` in some different places, to enhance the PHP's native object cloning. This PR introduce some bad behaviors with module provided views, see https://github.com/backdrop/backdrop/pull/2045#issuecomment-354434999

So what about doing our magic with `module` and `storage` key in https://api.backdropcms.org/api/backdrop/core%21modules%21views_ui%21views_ui.admin.inc/function/views_ui_clone_form_submit/1 ? *Asking for opinion before filling another PR.*

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2062 attempted to solve this issue by another way. It does not make any changes to `$view->clone_clone()` method, but it only changes the `views_ui_clone_form_submit` submit handler.

**Comment by quicksketch** [comment]
Thanks @opi this looks great! Merged into 1.x and 1.8.x.
