### ISSUE TITLE
Release Backdrop 1.8.0 and 1.7.3

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2849]
1.7.3 (Accompanying Bug-Fix Release) Checklist
---------------------------------------

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Move all unfinished issues to the next bugfix release milestone @quicksketch
- [x] Draft Release notes @quicksketch 

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, push to GitHub @quicksketch
- [x] Create release notes on GitHub @jenlampton
- [x] Revert version number back @quicksketch

1.8.0 (Minor Release) Checklist
------------------------

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create a new minor release to follow the current version @quicksketch
- [x] Move all unfinished issues to the next minor release milestone @quicksketch
- [x] Draft Release notes @jenlampton
- [x] Draft blog post @tomgrandy
- [x] Draft a newsletter via MailChimp @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch
- [x] Tag for release, push to GitHub @quicksketch
- [x] Revert version number back @quicksketch
- [x] Create release notes on GitHub @jenlampton
- [x] ~Unpublish preview release on backdropcms.org~
- [x] Update the front page download link on b.org. @jenlampton
- [x] Tweet that a new release is out @jenlampton
- [x] Publish blog post @tomgrandy, @klonos, @jenlampton
- [x] email katie@phpweekly.com for a note in the PHP Weekly Newsletter @jenlampton

## Post-release tasks (asap)

- [ ] Update the docker image to the latest @serundeputy
- [x] Update the [Roadmap](https://backdropcms.org/roadmap) page on b.org, @klonos:
  - "Project History and Future" section:
    - [x] Add a new entry for the next minor release in the list of releases
    - [x] Move the "(current release)" pointer to the current release entry
  - Add a section for the next-to-next release in the main text:
    - [x] Copy-paste the "New features planned for ..." section and change the version number, release date and GitHub issue tracker link
  - In the section for the current release:
    - [x] Change the "New features planned for" to "Key features in" in the section title
    - [x] Change the star icon to a checkbox icon (`class="fa fa-star-o"` to `class="fa fa-check-square-o"`)
    - [x] Add a "([release notes]())" link
    - [x] Add an [announcement]() link (when respective blog post is published)
    - [x] Update the list of features as necessary, according to release notes
    - [x] Remove the "See the Github issue tracker..." item
- [x] Update the Wikipedia articles to at least show the proper version number and date for latest release @klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

## Post-release tasks (after first bug-fix release)

- [ ] Push the minor release to the Pantheon repository @serundeputy
- [x] Send a newsletter via MailChimp @jenlampton

**Comment by jenlampton** [comment]
# Release notes for 1.7.3

**Changes since 1.7.2**

* 6 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2376">#2376</a>: Change 'View mode' to 'Display mode' to avoid confusion with views module.
* 3 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/687">#687</a>: Upgrade jquery.once.js to 1.2.6.
* 1 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2740">#2740</a>: Set fixed dropbutton width.
* c Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2832">#2832</a>: Form elements with errors are not showing colors in Basis.
* 3 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2837">#2837</a>: Prevent menu callbacks from appearing in administrative task lists.
* b Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2614">#2614</a>: [UX] Manage display sub-pages have no titles.
* 8 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1884830">#1884830</a> by <a href='/u/pwolanin'>pwolanin</a>, <a href='/u/dcam'>dcam</a>: Regression - replace md5 in Filter module calls with sha2 hashes.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2776">#2776</a>: Issue 2870289 by <a href='/u/markcarver'>markcarver</a>: file_ajax_upload() causes malformed Backdrop.settings.
* b Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2835">#2835</a>: Follow-up: Allow custom 404 page to be delivered.
* 2 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2839">#2839</a>: Make the 'All URL aliases' label clickable.
* 0 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2840">#2840</a>: Use the word 'Configure' for field settings. .
* 8 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/991">#991</a>: Refresh update.php and task list styling.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2835">#2835</a>: Prevent logs from being flooded with PHP warnings on Views 404 pages.
* 4 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2269">#2269</a>: Add an unpublished indicator to the Basis theme.
* c Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2802">#2802</a>: Seven: icon cleanup: replace old icons with lager font-awesome equivalents & rename.
* 9 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1178">#1178</a> by <a href='/u/wesruv-and-jenlampton'>wesruv and jenlampton</a>: Add icons to the configuration overview page.
* 3 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2817">#2817</a>: Use the word configure instead of edit for image styles.
* 2 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2831">#2831</a>: Theme thumbnails missing from /admin/appearance.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2828">#2828</a>: Fix the sort order on the admin/config page and make the page responsive.
* 8 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2820">#2820</a>: Prevent logs in watchdog for #global joins.
* b Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2701">#2701</a>: [UX] Maintenance mode message: add destination to the "Go online" link and make sure it's a warning.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1478">#1478</a>: Remove random values from Batch processing.
* 0 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1478">#1478</a>: Remove random string from image style test.
* b Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2688">#2688</a>: Date Popup does not handle the S (English ordinal suffix for the day of the month) properly.
* 6 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2826">#2826</a>: Fix jQuery version number to match.
* 0 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2807">#2807</a>: Wrong URLs in the robots.txt comments.
* 7 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2822">#2822</a>: Update the text for version incompatability.
* e Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2713">#2713</a>: Fixed: hook_block_view_alter() is only called for legacy blocks.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2773">#2773</a>: Add 'expand all' checkbox on menu block config form.
* 4 Use class instead of ID for layout admin table.
* 1 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2765">#2765</a>: Support replacing fancy quotes in path patterns.
* 2 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2513">#2513</a>: Adjust view style for filters/operations to match importance.
* 4 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2803">#2803</a>: Refresh design of progress bar to barber pole style.
* 5 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2799">#2799</a>: Upgrade CKEditor to 4.7.2.
* 0 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1200">#1200</a>: Image caption should wrap.
* 4 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2521">#2521</a>: Restore support for 'path' to theme_image().
* 4 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2744">#2744</a>: Whitespace issue on 'Available updates' page.
* e Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2764">#2764</a>: Simplify user interface text on "Allow Upscaling" checkbox.
* 0 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2792">#2792</a>: Add deprecated taxonomy functions for ease of upgrading and visibility.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2801">#2801</a>: Explictly declare DatabaseSchema::prefixNonTable() as public.
* d Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2602">#2602</a>: Update normalize.css to 7.0.0.
* 9 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2792">#2792</a>: Undefined taxonomy_get_parents_all().
* 8 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2787">#2787</a>: NodeMultiByteUtf8Test checks the wrong xpath.
* 3 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2780">#2780</a>: Add atom tags to views RSS feeds.
* f Non-AJAX view can be executed by requesting views/ajax URL.
* b Properly sanitize Bundle name in Manage Displays help text.
* 1 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2724">#2724</a>: Image style config names have json extension.
* e Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2740">#2740</a>: [UX] Align the operations dropbuttons to the left (right for RTL).
* f Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2791">#2791</a>: Fixed Syntax error, unexpected ';', expecting ')'
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1478">#1478</a>: Coding standards follow-up fix
* 7 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1478">#1478</a>: Avoid random content in layout block content.
* d Drupal 7.50 cross-ports.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1478">#1478</a>: Avoid random content in layout block content.
* 8 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2781">#2781</a>: [UX] Menu block settings: Improve the help text of the hamburger icon option.
* 5 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2771">#2771</a>: Use Europe/Paris instead of America/Santiago because PHP is inconsistent about CLT's timezone abbreviations.
* 3 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2496">#2496</a>: Fix problem with vocabulary validation on term contextual filters.
* b Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1959">#1959</a>: Failure to install module even if manager should be capable to install.
* 7 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1198">#1198</a>: Add front-end styles into the rich text editor.
* c Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2777">#2777</a>: Fix untranslated strings.
* 9 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2772">#2772</a>: Wrap toggle checkbox title with t() function.
* 4 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2622">#2622</a>: Respect iframe heights.
* 1 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2768">#2768</a>: keep language choice as a simple dropdown list.
* b Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2748">#2748</a>: Give stage import button the button-primary class.
* 8 Adds session variable for anonymous users to view their own uploaded files.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1086">#1086</a>: [UX] be more descriptive about the "Roles" section in the text format config page.
* d Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2711">#2711</a>: Respect permission access site reports.
* 0 Bumping minor dev version to 1.8.x
* 6 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2669568">#2669568</a> by <a href='/u/soaratul'>soaratul</a>: Fixed docblock typo in file_download_headers.
* 3 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1364694">#1364694</a> by <a href='/u/gielfeldt'>gielfeldt</a>: MemoryQueue::createItem should return TRUE.
* a Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2311305">#2311305</a> by <a href='/u/donutdan4114'>donutdan4114</a>, <a href='/u/stefan.r'>stefan.r</a>, <a href='/u/polonium'>Polonium</a>, <a href='/u/rpayanm'>rpayanm</a>, <a href='/u/tadityar'>tadityar</a>, <a href='/u/fabianx'>Fabianx</a>, <a href='/u/dave-reid'>Dave Reid</a>: Schema::getPrefixInfo() return value refers to the wrong database.
* e Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2694731">#2694731</a> by <a href='/u/nicrodgers'>nicrodgers</a>: Updated user_access() documentation.
* 6 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2660240">#2660240</a> by <a href='/u/kgaut'>Kgaut</a>: Fixed a typo in menu.inc.
* 0 Issue <a href="https://github.com/backdrop/backdrop-issues/issues/376391">#376391</a> by <a href='/u/mimran'>mimran</a>, <a href='/u/snehi'>snehi</a>, <a href='/u/pietmarcus'>pietmarcus</a>, <a href='/u/jhodgdon'>jhodgdon</a>: Document that module_invoke_all / ModuleHandlerInterface::invokeAll reindexes arrays.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.7.3 is cut.

**Comment by jenlampton** [comment]
Release notes added: https://github.com/backdrop/backdrop/releases/tag/1.7.3

**Comment by jenlampton** [comment]
# 1.8.0 release notes

**Changes since 1.7.3**

* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2715">#2715</a>: On admin/modules if previous search is present preserve it on redirect.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2376">#2376</a>: Change 'View mode' to 'Display mode' to avoid confusion with views module.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/687">#687</a>: Upgrade jquery.once.js to 1.2.6.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2837">#2837</a>: Prevent menu callbacks from appearing in administrative task lists.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/991">#991</a>: Refresh update.php and task list styling.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2269">#2269</a>: Add an unpublished indicator to the Basis theme.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2802">#2802</a>: Seven: icon cleanup: replace old icons with lager font-awesome equivalents & rename.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1178">#1178</a> by <a href='https://github.com/wesruv'>wesruv</a>: Add icons to the configuration overview page.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2817">#2817</a>: Use the word configure instead of edit for image styles.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2831">#2831</a>: Theme thumbnails missing from /admin/appearance.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2828">#2828</a>: Fix the sort order on the admin/config page and make the page responsive.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2713">#2713</a>: Fixed: hook_block_view_alter() is only called for legacy blocks.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2773">#2773</a>: Add 'expand all' checkbox on menu block config form.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2813">#2813</a>: Use class instead of ID for layout admin table.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2765">#2765</a>: Support replacing fancy quotes in path patterns.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2513">#2513</a>: Adjust view style for filters/operations to match importance.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2803">#2803</a>: Refresh design of progress bar to barber pole style.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2799">#2799</a>: Upgrade CKEditor to 4.7.2.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2521">#2521</a>: Restore support for 'path' to theme_image().
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2764">#2764</a>: Simplify user interface text on "Allow Upscaling" checkbox.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2602">#2602</a>: Update normalize.css to 7.0.0.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2781">#2781</a>: Menu block settings: Improve the help text of the hamburger icon option.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1198">#1198</a>: Add front-end styles into the rich text editor.

**Comment by jenlampton** [comment]
Tag updated with release notes: https://github.com/backdrop/backdrop/releases/tag/1.8.0

**Comment by klonos** [comment]
Updated the Wikipedia articles. On to the Roadmap page on b.org...

**Comment by klonos** [comment]
...alright. I've updated the roadmap page:

- The section for 1.9 was already there, so basically nothing to do.
- Based on the release date stated on GitHub, I have set the release date for 1.8 to Sept. 16th (original text said scheduled for the 15th).
- I have not been around much for this release, so not entirely sure about the "Add new files independent from other content, and edit existing files." feature that was planned for 1.8. I have moved that to the 1.9 release ( @jenlampton ??).
- Not sure if the list of features is complete either. Again, @jenlampton can you please take a look?
- I have added the links for the release notes and the announcement. Since the announcement page does not exist yet, the link leads to https://backdropcms.org/news ...but it will work if we make sure that the path to the post is `backdrop-1-8-released`

A second pair of eyes would be nice.

**Comment by jenlampton** [comment]
All Backdrop releases are on the 15th. Why did you change this one to 16th?
I'll take a look and review the features, but they should generally match
what's in the blog post issue.

**Comment by jenlampton** [comment]
Closing this issue in favor of 1.9.1
