### ISSUE TITLE
[UX] Use the word "Configure" instead of "Edit" in the language UI

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2850]
We missed a spot:
<img width="1192" alt="screen shot 2017-09-15 at 10 45 33 pm" src="https://user-images.githubusercontent.com/397895/30509533-a5110914-9a67-11e7-9d8a-a14fa13b6119.png">

---
PR: https://github.com/backdrop/backdrop/pull/2726

**Comment by jenlampton** [comment]
Added a quick PR for this so I could include the correct button label in screenshots :)

**Comment by klonos** [comment]
I don't agree with changing the button label to "Save order". We are doing other things via this form, so it should stay as "Save configuration".

**Comment by jenlampton** [comment]
What other things are we doing? I didn't see anything.

**Comment by klonos** [comment]
...there's a column with checkboxes for enabling/disabling each language, and another with radios where we select the default language.

**Comment by jenlampton** [comment]
Yep, your comment on the PR made it clear :) I merged your changes back in.

**Comment by klonos** [comment]
Thanks. RTBC 👍

**Comment by serundeputy** [comment]
This one went from changing a label on the button to deprecating functions and using a different function to save the form.

I'll defer to @quicksketch as I don't have enough experience with this form to know if those are the right changes or not.

**Comment by quicksketch** [comment]
Yeah, I agree. The label change would have been fine for 1.13.3, but for deprecating a function I feel that should wait on the next minor release.

If we bump up the `@deprecated` docblock to `1.14.0` I think this is good to go otherwise.

**Comment by jenlampton** [comment]
@quicksketch 	merged your suggestions into my PR.

**Comment by quicksketch** [comment]
Looks like there are still a number of test failures in `LocaleTranslationFunctionalTest`.

**Comment by jenlampton** [comment]
It looks like the change of function names made the form_alter not work anymore, in spite of the BC function that returned the form...  I've reverted the function name changes. 

This issue goes back to being just string changes. Re-tagging milestone for 1.13.3

**Comment by klonos** [comment]
RTBC again 😄

**Comment by quicksketch** [comment]
Ha! Okay. https://github.com/backdrop/backdrop/pull/2726 is now a lot simpler and doesn't make any API changes. I've merged it into 1.x and 1.13.x. Thanks everyone!
