### ISSUE TITLE
[UX][DX] Automatically create a database backup before running update.php

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2854]
## Describe your issue or idea

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/2842 where @klonos mentioned a brilliant idea. Automatic database backups! If someone is doing something as dangerous as upgrading their site, they probably already have a backup of the database. But what about every other update? People get lazy - I must admit, I do.

Can we have Backdrop automatically create a database backup -- every time -- before running database updates?

If so, it would also make any failed update less terrifying, as we'll have a nice clean copy of the DB from before the update was run. It would also make any bad news delivered by https://github.com/backdrop/backdrop-issues/issues/2852 more bearable, as we could also deliver the database backup to the user, for them to try again.

**Comment by jlfranklin** [comment]
Backups of the database are commonly done by hosting providers (sometimes for a fee) or via cron-jobs calling `drush sql-dump`.

This is a good idea for a contrib module, but I don't think it belongs in core.

**Comment by jenlampton** [comment]
I'm also concerned about security implications of dumping the whole database to a web-writable directory on the filesystem.

**Comment by opi** [comment]
automatic backup could be available **only** if a private file path is configured, with the relevant warning in the status report page if not. (Maybe some code could be stolen from backup_migrate about that).

**Comment by docwilmot** [comment]
It would also be a bit annoying if your site database is 500MB and you have to sit and wait for that every time. Maybe we can offer a link to download a copy of your database if you want to. Or ideally, leave this to contrib.

**Comment by jenlampton** [comment]
Yes, and Backup & Migrate does already provide this in contrib. Okay, closing this issue for the time being. We can reopen if we change our minds and decide core should get into the business of making backups.

**Comment by olafgrabienski** [comment]
Indeed, if *Backup and Migrate* is installed, there is the following notice on the *Backdrop database update* page:

> Before you run any database updates, make sure you have a backup of your database. Use Backup and Migrate (link to `/admin/config/system/backup_migrate`) to create that backup now.

To improve the situation in case *Backup and Migrate* is not installed, Backdrop could then provide a link to the project on b.org or in the project browser.
