### ISSUE TITLE
[UX] Messages set on the update page do not look like messages

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2857]
## Describe your issue or idea

I ran into a problem updating a site, but I didn't notice there was a problem because the messages on the update page did not look like messages:
<img width="878" alt="screen shot 2017-09-21 at 11 27 19 am" src="https://user-images.githubusercontent.com/397895/30712145-dd544712-9ebf-11e7-92c7-4ff4e4e9c393.png">

Could it be that our new system messages.theme.css is not loaded on the maintenance page?

### Steps to reproduce (if reporting a bug)

* TBD

**Comment by opi** [comment]
With PR https://github.com/backdrop/backdrop/pull/2033
![capture d ecran de 2017-11-02 14-03-31](https://user-images.githubusercontent.com/159548/32327413-b618dd88-bfd6-11e7-9495-eaf31814abed.png)

**Comment by klonos** [comment]
Simple, straight-forward change, and it seems to fix things (I could only get the "No pending updates" message, but that was stilled properly as an info system message).

RTBC from me 👍

**Comment by quicksketch** [comment]
Thanks everyone! Great fix.

Merged https://github.com/backdrop/backdrop/pull/2033 into 1.x and 1.8.x.
