### ISSUE TITLE
[UX] Clean up the description text on menu block setting "Starting level"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2859]
## Describe your issue or idea

I have no idea what this means: `Blocks that start with the 2nd level or deeper will only be visible when the trail to the active menu item passes though the block’s starting level.`

Can we attempt to reword this in a way that is a little clearer?

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2739

**Comment by BWPanda** [comment]
What about something like: `The level of the hierarchy this menu will start from. Blocks starting from the 1st level will always be visible. Blocks starting from other levels will only be visible if the active menu item is at that level or deeper.`

**Comment by jenlampton** [comment]
That's quite verbose... Let's remove `of the hierarchy`...

`The level of the menu to start from. Blocks starting from the 1st level will always be visible. Blocks starting from other levels will only be visible if the active menu item is at that level or deeper.`

I still have trouble with `if the active menu item is at that level or deeper.`

**Comment by BWPanda** [comment]
How about? `The level of the menu to start from. The block will be visible only if the current page has a menu item at or below this level.`

**Comment by klonos** [comment]
> The level of the menu to start from.

We can get rid of this if we want to focus/spend "verbosity" on the rest of the help text. The label of that field is "Starting level", so repeating the same in the help text does not achieve much. So how about:

> The block will be visible only if the current page has a menu item at or below the level set here.

**Comment by jenlampton** [comment]
Love it!

**Comment by klonos** [comment]
PR up for review then: https://github.com/backdrop/backdrop/pull/2739

**Comment by BWPanda** [comment]
Looks good.

**Comment by serundeputy** [comment]
looks good works good; thanks @jenlampton @BWPanda @klonos !

Merged into `1.x` and `1.13.x` will ship with `1.13.3`
