### ISSUE TITLE
[UX] Remove or improve description text on Menu Block "Menu style" setting

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2860]
## Describe your issue or idea

On the menu block settings form, the select list for 'Menu style' contains three options. It's description text repeat's it's name, and two of the options within:
`The menu style may adjust how a menu is displayed, such as a tree of links or a dropdown.`

As it is now, this text provides no real value but adds clutter to the interface. Should we try to add some text that does explain what a menu style is, or is that not necessary, and this text should be removed instead?

I'm leaning towards the latter (removing the description text)

----
PR by @QuintenDegraeve https://github.com/backdrop/backdrop/pull/2060

**Comment by QuintenDegraeve** [comment]
Hey, first time contribution! I'll take a crack at this one. 
I also think it is not necessary. The description does not add any extra information/value. 
So the extra clutter may hurt the User Experience.

**Comment by laryn** [comment]
Looks good!
![screen shot 2018-01-04 at 2 39 57 pm](https://user-images.githubusercontent.com/871421/34583376-3113ea34-f15d-11e7-8b96-d5e295f4f557.jpg)

**Comment by serundeputy** [comment]
@QuintenDegraeve first contribution! Well done.
@jenlampton @laryn thanks for the issue and review!

This is merged into `1.x` and `1.8.x` and will ship with `1.9.0` and `1.8.2`.

thanks everyone!
