### ISSUE TITLE
[UX] Clean up description text on menu block 'Show all menu links' checkbox

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2862]
## Describe your issue or idea

The description for the checkbox `Show all menu links` contains a rewording of title. Let's change `When checked, all menu links will be displayed. When unchecked, only expanded or active trail menu links will be displayed.` to `When unchecked, only expanded or active trail menu links will be displayed.`

<img width="587" alt="screen shot 2017-09-21 at 4 25 55 pm" src="https://user-images.githubusercontent.com/397895/30723207-8cc3978c-9eea-11e7-8584-a649c628756f.png">

----
PR by @migomlevi https://github.com/backdrop/backdrop/pull/2059

**Comment by migomlevi** [comment]
Hey i would like to do this as my first open source contribution but i can't seem to find the right file.

**Comment by opi** [comment]
thanks @migomlevi, welcome to the beautiful open source world ;)

**Comment by serundeputy** [comment]
Nice @migomlevi ! First open source contribution! Well done.
thanks @jenlampton for reporting and @opi for RTBC!

This is merged into `1.x` and `1.8.x` and will ship with `1.9.0` and `1.8.2`.

thanks everyone!
