### ISSUE TITLE
[Q] Options for Auto Unpublish & Purge Expired Content

### ISSUE THREAD

**Issue by Dinornis** [backdrop/backdrop-issues#2863]
Does anyone have any recommendations for configuring Backdrop to automatically unpublish and purge content that has been set to expire?

Our volunteer-run website (currently on D6) provides a notice board for the local community where people can post various notices similar to how classifieds work.
At the moment this functionality is made possible thanks to the [**Auto Expire** module](https://www.drupal.org/project/auto_expire) (D6 only,) which allows us to set expiration time for 30 days for a content type and users are allowed to renew the content for one or more cycles. Before a node is expired a warning message is sent to the user who can then extend the node for another 30 days.

The nodes are unpublished on the first cron run after the expiry date and nodes that have expired for a certain amount of time can be automatically purged.

Although we could upgrade to Drupal 7 and with a combination of modules maintain this ability, we would much rather find a way to switch to Backdrop while being able to retain this functionality.

Simmilar D7 Modules:
- [Job Scheduler](https://www.drupal.org/project/job_scheduler)
- [Node expire](https://www.drupal.org/project/node_expire)
- [Node expire extras](https://www.drupal.org/project/node_expire_extras)
- [Node expire patterns](https://www.drupal.org/project/node_expire_patterns)
- [Rules](http://drupal.org/project/rules)
- [Scheduler](https://www.drupal.org/project/scheduler)

Any suggestions are very much appreciated.

Edit: added D6 notes.

**Comment by docwilmot** [comment]
You could do this with Rules, but why not just port the auto expire module? Perhaps I'm reading your issue wrong.

**Comment by laryn** [comment]
Scheduler is in process of being ported. If that module would suffice, feel free to help me get to a formal release:

https://github.com/laryn/scheduler/

**Comment by Dinornis** [comment]
> You could do this with Rules, but why not just port the auto expire module? Perhaps I'm reading your issue wrong.

Thanks for the suggestions. Unfortunately, I am not a coder, so my ability to help with porting any modules is quite limited.

Also, I forgot to mention that Auto Expire is available only for D6.

**Comment by laryn** [comment]
@Dinornis The upgrade path isn't ready yet but if you're willing to install the current version and do some testing on it it would be great.

**Comment by Dinornis** [comment]
I will see if I can be of any use... 😄

**Comment by Dinornis** [comment]
Hi @laryn, I did some testing, added few issues to your list, but really hit a roadblock at https://github.com/laryn/scheduler/issues/12 where I can't even save a node while using the Scheduler due to a conflict between various date formats.

**Comment by laryn** [comment]
Thanks, @Dinornis! I'll try to take a look soon.

**Comment by Dinornis** [comment]
@docwilmot said:
> You could do this with Rules, but why not just port the auto expire module? Perhaps I'm reading your issue wrong.

I am also looking at the Rules module, but fail to see how I would go about setting this up.  Have you used Rules for something simmilar and have any hints/suggestions that would help me getting started?

**Comment by docwilmot** [comment]
Youll need to enable Rules and Rules scheduler. And see this article for steps: https://groups.drupal.org/node/240678
I would think the steps for your case would be something like this;
1. Set up a flag or field on the node type which shows that it has not expired
2. Rule 1 triggers whenever a node is created or that flag is clicked; it evaluates after 25 days to send email
3. Rule 2 triggers when Rule 1 executes. This Rule 2 deletes the node in 5 days if its flag is expired.

Something like that?

**Comment by Dinornis** [comment]
Thank you @docwilmot although definitely not intuitive interface it looks like one can do a lot with rules.  At the moment it does not seem to be ready for production, will try to help testing and identifying issues at https://github.com/backdrop-contrib/rules/issues

**Comment by docwilmot** [comment]
Sorry about the errors. We've done a lot of work with Rules and EMW while porting Ubercart and I'm pretty sure it's stable now, since Ubercart uses quite a bunch of Rules to work well (and we've got all tests passing on Ubercart now). But unfortunately we haven't pushed a new release of Rules nor EMW yet. @Graham-72 is on vacation I believe, so when he's available we can tackle this. (We probably should check Rules tests as well)

**Comment by quicksketch** [comment]
Closing this question out. Please reopen if needed.
