### ISSUE TITLE
View Tags on the Homepage horizontally - how does it work

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#2867]
## Describe your issue or idea

Hello Developers,

I'll show you here a screenshot, on which my tags are only displayed vertically.

How can I make it display horizontally and perhaps something else different?

That would be my idea at the moment. Thanks in advance.

![backdrop-cms-tags-horizontal](https://user-images.githubusercontent.com/7885632/31081984-dee18a8c-a78d-11e7-91c9-c7915288f090.jpg)

### Relevant version/system information (if applicable)

Backdrop 1.8.0 and Plugins

**Comment by olafgrabienski** [comment]
@AlexL777 As far as I know, there is no option in the UI to change the orientation of the tags. I would style them with CSS (in a sub-theme). Something like this:

```
.field-name-field-tags .field-item {
  display: inline-block;
  margin-right: 0.5rem;
}
```

Result:
![screen-backdrop-tags-horizontal](https://user-images.githubusercontent.com/14188307/31083501-244e196a-a792-11e7-88b3-ad6af62904a0.png)

**Comment by laryn** [comment]
@AlexL777 @olafgrabienski There is a contrib module that can provide more options here:
https://github.com/backdrop-contrib/textformatter

**Comment by AlexL777** [comment]
Thanks @laryn !

Where can I control the look of the tags? Is this in the backend in the "Views"?

**Comment by laryn** [comment]
@AlexL777 Are you using a custom View on the front page, or the typical "Summary" style display? You can control the formatting in the view modes available on the content type displays (e.g. "Admin > Structure > Content Types > Post > Manage Display" and then select "Manage Display" for the view mode in question, such as the teaser or the default displays.

If you are adding fields to a View, you can also use the formatter in the field settings for the "Tags" field.

**Comment by laryn** [comment]
@AlexL777 I'm going to close this here in the core issue queue. If you are successful, would you be willing to write up instructions in the `textformatter` wiki?

https://github.com/backdrop-contrib/textformatter/wiki

If you are not successful, maybe follow up in the issue queue over there?

https://github.com/backdrop-contrib/textformatter/issues

**Comment by AlexL777** [comment]
Thanks, it worked as my screenshot shows here. 

![backdrop-cms-1-8-0-tags-horizontal](https://user-images.githubusercontent.com/7885632/31090727-f49b0a9a-a7a8-11e7-9266-a2035a7856bb.jpg)


I had to edit the teas for the content type "Post". So I could make the tags with the teaser so with commas in between.

This is good with this module and I can report this in my own blog.

As I see, you have already reported it in the wiki.

**Comment by laryn** [comment]
@AlexL777 Yes, I just pasted what I wrote above into the wiki. If it is clear enough, great! If you think it could be clearer, feel free to edit. 👍
