### ISSUE TITLE
Ckeditor in Backdrop 1.8.0 not visible

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#2868]
## Describe your issue or idea

Today I noticed that the ckeditor is not displayed when creating the content.

I rely on Backdrop 1.8.0 and numerous modules. Previously, with old backdrop version everything was fine. Here is another screenshot.

How can I fix the problem?

Thanks in advance.

![backdrop-ckeditor-not-visible](https://user-images.githubusercontent.com/7885632/31083508-279f8ab8-a792-11e7-83e8-a0e7f3e40070.jpg)

**Comment by laryn** [comment]
Just curious -- does it show for Filtered HTML? That is provided by default so I'm wondering if it is a problem only on custom text formats or all. I haven't seen a problem on any of my sites but haven't created a custom format.

**Comment by AlexL777** [comment]
The problem has been solved and I have uploaded the `/core` directory of 1.8.0 again. Now all is well again.
Why it was so before, I can not say 😸

**Comment by laryn** [comment]
Sounds like some core files were not copied correctly the first time. Glad your site is working again!
