### ISSUE TITLE
Tags on a Page are displayed multiple times - what am I doing wrong

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#2870]
## Describe your issue or idea

Hello Developers,

I have added tags to a page, and unfortunately other tags are separated by semicolons. Where do these tags come from and how can I remove them?

This would be this page under https://alexanderliebrecht.de/%C3%BCber-mich

Something I did wrong, probably just do not know what is wrong.

Thanks in advance.

**Comment by laryn** [comment]
@AlexL777 It looks like you have pasted those "other tags" in to your page in the Body area. If you edit the page and scroll down in the body area, they are probably at the bottom.

**Comment by AlexL777** [comment]
Thanks for your help. These tags were present in the source code in the editor. Now I have deleted them and everything is all right.

I just thought that I had something serious.
