### ISSUE TITLE
[UX] Contact form: Improve the recipients field

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2872]
When you enable the core Contact module and then go to /admin/structure/contact/configure/1 to add multiple email addresses as recipients, you have to separate them with a comma. But since the Recipients field is a textarea, one may assume that you can enter one email address per line (e.g. separated by a newline character). This isn't the case.

For better UX, I'd suggest either:

1. Make the Recipients field a textfield (not a textarea), so it's more obvious that multiple email addresses need to be separated by a specific character.
2. Change the backend to split multiple email addresses by a newline character instead of a comma (and therefore make better use of the existing textarea field).
3. Keep the textarea, but allow separating multiple email addresses by a newline OR a comma (i.e. allow the user to enter addresses in whatever format they're used to).

My preferred solution (in order of preference) is: 3 > 2 > 1

---
PR by @opi: https://github.com/backdrop/backdrop/pull/2147

**Comment by BWPanda** [comment]
Here are screenshots when trying to enter one email address per line...

![screenshot-2017-10-3 configure contact category panda s backdrop sandbox](https://user-images.githubusercontent.com/2385329/31105197-f6ff6dd2-a82d-11e7-96be-af51ef60ec26.png)

![screenshot-2017-10-3 configure contact category panda s backdrop sandbox 1](https://user-images.githubusercontent.com/2385329/31105196-f6fb7b6e-a82d-11e7-8ed5-e8fdede444ee.png)

**Comment by opi** [comment]
PR https://github.com/backdrop/backdrop/pull/2147 for solution 3, following the [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) : *Be conservative in what you send, be liberal in what you accept*.

Contact category form can accept addresses separated by comma, space or line-break.
After submission, addresses list is always cleaned up to a proper comma-separated list.

**Comment by quicksketch** [comment]
Great job @opi! I updated your PR with minor changes:

- Added test coverage of the new input formats. Also switch from directly using config() modification of the contact settings to the new contact settings form.
- Rerolled against 1.x
- IMO the best presentation of a list of emails is separation by new lines. I switched the display in the settings form to use new lines, though they are still stored with commas.

**Comment by quicksketch** [comment]
With all the modifications to Contact module happening at the same time, this would by easier if we only merged this into 1.x for 1.11.0.

**Comment by quicksketch** [comment]
Hm, one more thought here. Potentially we should also allow semicolons as a separator. I believe that is the default separator for Outlook (or it was years ago).

https://www.lifewire.com/separate-multiple-email-recipients-1173274

> Outlook and any other email program that looks for names in the last name, first name format, where the program uses the comma as a delimiter, may run into problems if you separate email recipients with commas. Email clients that use commas as delimiters typically use semicolons to separate multiple addresses in their header fields. In Outlook, multiple addresses are entered with semicolon separators by default.

**Comment by opi** [comment]
> IMO the best presentation of a list of emails is separation by new lines. I switched the display in the settings form to use new lines, though they are still stored with commas.

agreed, thanks.

> Hm, one more thought here. Potentially we should also allow semicolons as a separator. 

I'll add semicolons as separator, nice improvement. I'll probably rebase & squash the PR, while keeing both authorship.

**Comment by opi** [comment]
I finally update the PR with semicolon separator, and a little UX improvment https://github.com/backdrop/backdrop/pull/2147/files#diff-037ce3d000dd806422b7fda44dddab91R203 ; I found myself in a merge-apocalyspe, thus we need to cleanup the Git history before considering the merge into 1.x

**Comment by klonos** [comment]
> I found myself in a merge-apocalyspe

😆 

Wondering how/if #1005 fits here.

**Comment by opi** [comment]
Tests are green, ready for review !

**Comment by olafgrabienski** [comment]
@opi The sandbox site displays an "unexpected error" on the home page. It's possible to log in though, and Status report says that there are Database updates available.

**Comment by opi** [comment]
@olafgrabienski sandbox fixed, thanks for the report.

**Comment by olafgrabienski** [comment]
Thanks for fixing the sandbox! I've tested the recipient field there with the "ready to paste" list, the results look good: email addresses can be entered in various ways, are displayed using new lines (configuration view) or commas (overview). Great improvement!

**Comment by klonos** [comment]
Suggestions/comments:

1. Very clever to have the textarea rows be entries + 2 👍

2. We could be sorting email addresses alphabetically for an added bonus. This would help in cases where these lists get long. I would first go by grouping by domain, then alpha sorting for each domain.

I have filed a few follow-up UX issues for things that I have noticed related to the contact categories form and the listing.

**Comment by opi** [comment]
Marked as RTBC as 3 different people said it's ok.

**Comment by klonos** [comment]
RTBC indeed 👍

**Comment by quicksketch** [comment]
Thanks all! Merged https://github.com/backdrop/backdrop/pull/2147 into 1.x for 1.11.0. Because we have so many changes to Contact module in the works, I'm not backporting this into 1.10.x (though if we feel strongly I can cherry-pick it back).

**Comment by opi** [comment]
> Because we have so many changes to Contact module in the works, I'm not backporting this into 1.10.x

Agree. Thanks for merging this one.
