### ISSUE TITLE
[DX] Add a not-front CSS class

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#2874]
When viewing the front page, a helpful `.front` CSS class is added to the `<body>` tag. I'd like to have a corresponding `.not-front` class when **not** viewing the front page.

**Comment by docwilmot** [comment]
Couldn't use CSS `:not()`?

**Comment by opi** [comment]
Oh, I every forget about these fancy selector, but you're right.  (Reference: https://caniuse.com/#feat=css-sel3)

Anyway, I'll find my code more readable with a plain `.not-front .foo {}`.  Feel free to close this issue if I'm the only one with this feeling

**Comment by jenlampton** [comment]
I'm not sure we should add any `.not-X` classes into core since it's so easy get what you need in other ways (as noted above).  However, if they are needed for any particular theme. it's also pretty easy to add them in via preprocess.

**Comment by opi** [comment]
agreed. Closing this to avoid clutter. Thanks for your good advices.

**Comment by klonos** [comment]
After watching the recording of the latest VUG video re porting themes, I would like to reopen this issue, in order to reconsider adding this class.

It seem that this would save themers some time, and it would make certain things "just work".

Pinging @jenlampton. 2 years later, do you think we should reconsider?

**Comment by klonos** [comment]
...at the very least we should document this, and mention this bit of code example:

```php
/**
 * Override or insert variables into the page template.
 */
function MYTHEME_preprocess_page(&$variables) {
  if (!backdrop_is_front_page()) {
    $variables['classes'][] = 'not-front';
  }
}
```

**Comment by opi** [comment]
> ...at the very least we should document in https://api.backdropcms.org/converting-themes the fact the Backdrop has intentionally left out the `.not-front` class, and mention this bit of code example that people can use in order to get it back:

Totally agree !

**Comment by jenlampton** [comment]
Well, I just fell into the rabbit hole. I spent a bunch of time updating https://api.backdropcms.org/converting-themes, including adding a section for the not-front class.

**Comment by klonos** [comment]
Thanks @jenlampton 🙏 ...I just added this bit to that section:

> Alternatively, you may replace all instances of the `not-front` class in your CSS with `:not(.front)`
