### ISSUE TITLE
Each Drop-button on "Manage displays" page should read "Manage display"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2876]
## Describe your issue or idea

Each one of these is a single display, not plural:
<img width="2402" alt="screen shot 2017-10-06 at 2 24 57 pm" src="https://user-images.githubusercontent.com/397895/31299223-43de1e3e-aaa2-11e7-9231-3347c1b65f7b.png">

**Comment by tauschersiemen** [comment]
Hello, I can't seem to find the file where this should be changed. This is my first contribution ever so a little help would be awesome!

**Comment by jenlampton** [comment]
it's probably somewhere in `field_ui.theme.inc`.

**Comment by tauschersiemen** [comment]
Created pull request for the change here: https://github.com/backdrop/backdrop/pull/2057

**Comment by serundeputy** [comment]
Thanks @tauschersiemen ! First open source contribution!
Thanks @jenlampton for reporting and RTBC!

This is merged into `1.x` and `1.8.x` and will ship with Backdrop `1.9.0` and `1.8.2`.

thanks!
