### ISSUE TITLE
Add support for async and defer to backdrop_add_js()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2877]
## Describe your issue or idea
I have an external script that is recommending that we add the async attribute when the script is added in the head tag. Unfortunately, there's no way to do that in Backdrop.

I've found several pieces of conflicting information indicating that it can be done in Drupal, but both on documentation for contrib modules:
* https://www.drupal.org/project/async_script_shim
* https://www.drupal.org/node/2299773

I think something like this would be a nice addition and should be supported in core.

---

PR by @herbdool: https://github.com/backdrop/backdrop/pull/2035

**Comment by jenlampton** [comment]
Looks like defer might also be useful

**Comment by opi** [comment]
As far as I understand https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_add_js/1 & https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_pre_render_scripts/1, `defer` is supported ;

I see 2 ways for handling `async` : 
- copy/paste the way `defer` works. quick'n'easy
- Support a `attributes` option in drupal_add_js

**Comment by herbdool** [comment]
I think I need this too. I think an attributes approach might be the way to go. @quicksketch suggested a backport of adding an attributes array a few years back of this https://www.drupal.org/node/1664602#comment-6684562 and others have been working on patches. Looks like it might make it into Drupal 7.60.

**Comment by opi** [comment]
Should we craft a PR based on http://cgit.drupalcode.org/drupal/commit/?id=12eefe5  ?
I'd like to have an attributes array, but I'd like to keep the old behavior of having a `defer` key, and maybe support a `async` key too. 
What do you think ?

**Comment by herbdool** [comment]
@opi I think our PR should be based on the patch in the thread I pasted above for Drupal 7. https://www.drupal.org/files/issues/1664602-123.patch from comment 123. It keeps there defer tag but adds attributes. And it's most likely to be merged into Drupal 7.

**Comment by herbdool** [comment]
@opi I see now. The patch you pasted is closer to how common.inc is in Backdrop than the Drupal 7 patch.  I think what we need is a mix of the two. The tests are closer to Backdrop in the Drupal 7 patch and the rest is closer to the early Drupal 8 commit you found.

**Comment by herbdool** [comment]
@opi would you like to review this PR? Tests are passing.

**Comment by herbdool** [comment]
In my PR I left the old approach for "defer" for backwards compatibility, but going forward put everything in the attributes array much like in Drupal 8.

**Comment by opi** [comment]
You are right. Adding an `async` for easier DX may add more legacy code, for a small benefit

**Comment by herbdool** [comment]
@opi thanks for the review!

**Comment by quicksketch** [comment]
Great job everyone on this issue!! Merged https://github.com/backdrop/backdrop/pull/2035 into 1.x and 1.8.x for 1.8.1. Thanks!
