### ISSUE TITLE
Views Blocks missing passing arguments from the URL

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2878]
## Describe your issue or idea

In Drupal + Panels content panes the most commonly used setting for "Contextual filter input" was "Panel argument" which mapped exactly to `arg()`.  Unfortunately, that most-commonly used setting was excluded from Backdrop for some reason.

I have a handful of sites I'm porting over from Drupal + Panels that all make heavy use of this feature, so here's a PR that takes a stab at adding it back :)

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2020

**Comment by quicksketch** [comment]
The PR code looks good to me. We should include test coverage of this new functionality.

I was thinking about if we should more deeply integrate this with Layout's contexts, but even if we build out some kind of official context support into this block, pulling from the URL may still be useful and less of a hassle than using contexts. For example I've seen situations where a view takes an argument that is a string, but that string isn't a term or node ID or any other internal representation. It would be a hassle to require users to set up a string-passthrough context just to pull the argument from the URL.

So anyway, looks good! Seems like a good plan to me.

**Comment by jenlampton** [comment]
> I was thinking about if we should more deeply integrate this with Layout's contexts

yes, there's a "From context" option in the code as well, but it's commented out at the moment. In panels, both options existed, so I think we should have both in Backdrop too. 👍 

I'll add some tests and see if we can't get this into the next minor release.

**Comment by jenlampton** [comment]
This needs more review/testing before it's ready. Removing milestone since it missed 1.9 as well.

**Comment by jenlampton** [comment]
Grumpily adding the milestone back since I'm getting tired of re-applying this patch :)

**Comment by klonos** [comment]
Hey @jenlampton, I would like to test the PR, but I have never used this feature before. It would help if you can point to a tutorial, or provide steps to test.

**Comment by jenlampton** [comment]
Ah, good idea. Okay, so I was using it today on this page:
http://www.onlinembareport.com/find-a-school/CA

The view of colleges on this page is filtered by state -- the 2-letter abbreviation at the end of the URL. 

This value exactly maps to the values in a "state" field value I have on the "college" node, so I want the list of colleges here to use arg(1) for the contextual filter.

**Comment by klonos** [comment]
Code-wise the PR looks good to me 😄 ...would be nice to know how to actually use this in real life, so I could give it a spin in the PR sandbox.

**Comment by jenlampton** [comment]
@klonos, I added an example on the demo site. There are three layouts at shirts/small shirts/medium and shirts/large that use `small` `medium` and `large` as contextual filters, to filter a (block) view on those pages. 

There's also a content type called "shirts" with a "size" field containing those values.

**Comment by herbdool** [comment]
Tested Jen's demo and looks good to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2020 into 1.x for 1.12.0. Thanks @jenlampton, @herbdool, @opi, and @klonos!
