### ISSUE TITLE
'Status report' page links to '/admin/modules/update' even when 'Project Installer' module isn't enabled

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2880]
On the 'Status report' page (/admin/reports/status), it says:

> **Out of date (Updates available)**
There are updates available for one or more of your modules or themes. To ensure the proper functioning of your site, you should update as soon as possible. See the available updates page for more information.

The 'Updates available' on the first line links to '/admin/modules/update', but since I don't have the 'Project Installer' module enabled, I just see the Modules page when I click on it. The 'available updates' in the last sentence links to the 'Available updates' page (/admin/reports/updates).

I propose making the first line's 'Updates available' link point to the 'Available updates' page (/admin/reports/updates) when the 'Project Installer' module isn't enabled.

--
[PR](https://github.com/backdrop/backdrop/pull/2099) by laryn

**Comment by laryn** [comment]
Or leaving it unlinked might be fine, too, instead of the same link multiple times. I think this was a PR I worked on, so I'm happy to try to make a revision -- I didn't consider that the Project Installer module might not be installed, but it should be a pretty simple check.

**Comment by klonos** [comment]
The bigger UX fail here is that we have multiple places for viewing and performing updates. What I would like to see instead is:

a) do not render the `/admin/appearance/update`, `/admin/modules/update` and `/admin/structure/layouts/update` tabs at all if there are no updates. Another related WTF is that these pages show ALL updates, not taking under account the type of project:

<img width="891" alt="screen shot 2017-11-13 at 6 13 47 am" src="https://user-images.githubusercontent.com/2423362/32702343-eaee53b0-c839-11e7-8fb7-5f50272c77a9.png">

b) Merge the "Update xyz" tabs into a single "Update projects" tab/page (or whatever we decide to call it). So we currently have this:

<img width="781" alt="screen shot 2017-11-13 at 6 19 13 am" src="https://user-images.githubusercontent.com/2423362/32702399-b8ac0630-c83a-11e7-995a-7a3a23c0d9d5.png">

...which, if there are updates available, redirects to `/admin/xyz/update`. Well, in my head, this is very similar to the Project Installer pages, filtered down to projects that are already installed. So, the "Update xyz" tabs could very well be converted to a single Project Installer page/tab, filtered by projects already installed, or by projects already installed AND with updates available. Then, we could have an "Update queue" sidebar (in place of the "Installation queue" sidebar), and these projects could have a "Add to update queue" button/link.

So, this:

<img width="892" alt="screen shot 2017-11-13 at 6 32 05 am" src="https://user-images.githubusercontent.com/2423362/32702505-6f631fc0-c83c-11e7-9f8e-a7d4cf72263f.png">

...could become something like this:

<img width="892" alt="screen shot 2017-11-13 at 6 45 26 am" src="https://user-images.githubusercontent.com/2423362/32702672-51cdc756-c83e-11e7-8004-7a152b9c685b.png">

So people can follow a single, streamlined and familiar process of installing updates (opposed to how we currently have them pogo-sticking around various pages in the UI).

**Comment by olafgrabienski** [comment]
@klonos Nice direction in my opinion! @BWPanda stated however, that the 'Project Installer' module isn't enabled on his site. How can we handle that?

**Comment by laryn** [comment]
I was just looking at this and I mis-spoke, it was not related to the changes I worked on at one point, but the same issue applies there. I am attaching a small PR that should take care of it.

@klonos do you want to pull your comment out into a separate issue?

**Comment by opi** [comment]
approved https://github.com/backdrop/backdrop/pull/2039#pullrequestreview-83182437

**Comment by quicksketch** [comment]
This had been merged last week but I forgot to update here. Thanks @laryn for the PR! @opi for the review! And @BWPanda for filing in the first place!

**Comment by laryn** [comment]
File this under "I forgot to test both sides of the equation" -- this fixed the problem but a faulty/untested assumption broke the part that was not broken previously. PR coming to address it.

**Comment by opi** [comment]
Sorry for my bad previous review :/

**Comment by laryn** [comment]
It was my fault @opi. Luckily not a big deal.

**Comment by quicksketch** [comment]
Doh! Well it's a minor issue. This will be fixed again in 1.9.4. Merged https://github.com/backdrop/backdrop/pull/2099 into 1.x and 1.9.x. :)

**Comment by klonos** [comment]
I have created #3039 for my comment from back in November above (so it does not block this ticket from being closed).

**Comment by quicksketch** [comment]
Oops, we should have closed this. 1.9.4 was released yesterday, with this change included.
