### ISSUE TITLE
How to theme/override an image inserted in CKEditor?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2882]
I need to be able to override the HTML for an image uploaded (or linked from an external URL) and inserted into a CKEditor field. I cannot find a `theme_*()` function that controls this however...

Is there a way to override images inserted into CKEditor from a contributed module?

**Comment by docwilmot** [comment]
Don't quite understand the question to be honest

**Comment by BWPanda** [comment]
When you add an image to CKEditor, you upload a file or specify an external URL, then CKEditor adds the HTML: an IMG tag with src, alt, height, width, data-file-id, etc. attributes.

I'd like to edit this HTML, to add additional attributes (automatically obviously, not manually each time I insert an image). I can do this with all other images by overriding theme_image(), but CKEditor doesn't use that theme function (I think it outputs the IMG tag itself)...

Does that explain it better?

**Comment by docwilmot** [comment]
@BWPanda that's a problem. We came across this in https://github.com/backdrop/backdrop-issues/issues/1580#issuecomment-329004345.
It doesnt seem there is a way to do this AFAICT.

**Comment by BWPanda** [comment]
Since this was just a question, and since it's been answered (not possible), and since there's been no further activity or people reporting the same thing for 4+ years, I'll close this issue now.
