### ISSUE TITLE
[UX] Link to add a redirect should not show on node form if new node

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2884]
## Describe your issue or idea

When you are creating a new node, there is a link to add a redirect to this node, before there is a node. If a user clicks this link before saving the node, all their work creating the node will be lost.

We should not show this link unless we are editing an existing node.

### Steps to reproduce (if reporting a bug)

* View the node form
* Enter text
* Click the "Add new redirect" link
* :(

-----
~PR by @akalata https://github.com/backdrop/backdrop/pull/2030~
PR by @akalata & @opi https://github.com/backdrop/backdrop/pull/2046

**Comment by olafgrabienski** [comment]
Not tested the PR so far, just labeled the issue as PR.

**Comment by serundeputy** [comment]
PR backdrop/backdrop#2030  works as advertised left some feedback for minor adjustment.

**Comment by opi** [comment]
New PR https://github.com/backdrop/backdrop/pull/2046 is a take over on [https://github.com/backdrop/backdrop/pull/2030](PR#2030) with adjustements from https://github.com/backdrop/backdrop/pull/2030#pullrequestreview-74254282

**Comment by serundeputy** [comment]
Thanks everyone. reviewed; tested; looks good works good.

merged into `1.x` and `1.8.x`
