### ISSUE TITLE
Drop-down menu no longer displays all menu links, after adding checkbox to show all menu links for menu tree

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2886]
## Describe your issue or idea

Drop-down menu no longer displays all menu links, after adding checkbox to show all menu links checkbox (for menu tree)

### Steps to reproduce (if reporting a bug)

* Upgrade to 1.8.0
* See broken menu

**Comment by laryn** [comment]
Duplicate of https://github.com/backdrop/backdrop-issues/issues/2879?

**Comment by jenlampton** [comment]
Yes.

**Comment by olafgrabienski** [comment]
Closing (duplicate of #2879, see above).
