### ISSUE TITLE
Tweak some tests to make them more robust

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2889]
## Describe your issue or idea
A few tests in the test suite rely on how MySQL stores and returns data.  Specifically, MySQL returns unsorted rows in the order they were written, which is not guaranteed by any standard.  Ensuring the data stored has a clear sort order and returning the data sorted makes these tests more robust.

### Steps to reproduce (if reporting a bug)
See #2888.

### Actual behavior (if reporting a bug)
Test fail because the database doesn't behave as expected.

### Expected behavior (if reporting a bug)
Tests should pass regardless of the underlying database engine.

**Comment by quicksketch** [comment]
Thanks @jlfranklin! Although Backdrop doesn't officially support Postgres, these minor changes do no harm and it's a good idea not to depend upon inherent sort order anyway. I've merged your PR into 1.x and 1.8.x. Thanks again!

**Comment by jlfranklin** [comment]
Thanks @quicksketch for committing this and other issues like it.  The less Silkscreen drifts from Backdrop, the fewer merge conflicts I see, the easier it is to keep up.
