### ISSUE TITLE
Custom block templates

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#2892]
I'm trying to create custom block.tpl.php file for theming menus. Want to add a line of HTML code in div class="block-content"

I managed to do this for custom menu "Test" with template file "block--menu--menu-test-menu.tpl.php" in my custom theme folder where I suppose "--menu--" is name of the module and "menu-test-menu" is menu_name of menu as I see in Configuration manager. So, theming of custom menus is OK, tpl file with such file name is working.

But when I am trying to do the same for Primary navigation with template file "block--menu--main-menu.tpl.php" there is no effect on Primary navigation block code in web page.

Is there some difference between system Primary navigation menu block and custom menu blocks and I have to name Primary navigation block template file with different pattern?

Thanks a lot!

**Comment by bjoern-st** [comment]
Hey @amilenkov 

You might want to try something like "block--system--main-menu.tpl.php".

**Comment by amilenkov** [comment]
Thanks a lot! I've asked the same question in the Forum of Backdrop and there the issue was fully clarified.

https://forum.backdropcms.org/forum-topic/custom-block-templates
