### ISSUE TITLE
Backdrop Forum is not fully accessible

### ISSUE THREAD

**Issue by simone960** [backdrop/backdrop-issues#2901]
I have logged in to the forum but I couldn't create any post. Here the issues I found:

1) No button to create new post
2) No link to the user profile (I need to manually type https://forum.backdropcms.org/user)
3) No logout button 

Meanwhile I'm only allowed to add comment to the existing posts. I can't fully participate. Please advise. Thanks!

![forum](https://user-images.githubusercontent.com/7530286/32252206-8737268a-bee8-11e7-94f0-1a1cd47557b3.jpg)

**Comment by docwilmot** [comment]
@simone960 thank you for this. Though Backdrop's been around for a while we only just decided to get serious about our forums, and your feedback is very welcome. 

Those of course are major oversights, (embarrassingly so), and will be fixed ASAP.

**Comment by dyrer** [comment]
Forum also need some bug fixes like https://cl.ly/0G1g1n3U2j2M

**Comment by klonos** [comment]
@simone960, we have a dedicated issue queue for the forum: https://github.com/backdrop-ops/forum.backdropcms.org/issues ...can you please create a ticket for this issue there?

@dyrer that problem has already been reported: https://github.com/backdrop-ops/forum.backdropcms.org/issues/40

**Comment by simone960** [comment]
@klonos Noted. Nice to have a dedicated issue queue specially for forum. Thanks !
