### ISSUE TITLE
[UX] Hide all field labels by default

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2902]
## Describe your issue or idea
I notice that almost every time an image field is added, it's label needs to be hidden. And most of the time, people forget to visit "Manage displays" after adding the field (and maybe that's a cause for another issue).

It seems that we might be able to solve the first part of that problem very easily: can we hide the label for all image fields by default?

**Comment by olafgrabienski** [comment]
Yes, that makes usually sense for images. Some questions:

- Are there other specific field type labels which should be hidden by default? Afaik, it's already the case with the body field.
- Are there other labels which should be displayed by default, for example email?
- Should we even hide all labels for the sake of consistency?

**Comment by laryn** [comment]
I lean towards hiding all labels by default.

**Comment by jenlampton** [comment]
I agree.

**Comment by olafgrabienski** [comment]
> I lean towards hiding all labels by default.

> Sounds good to me.

To me as well.

Should we do the same with Views fields? (in a separate issue, I guess)

**Comment by stpaultim** [comment]
I just did a quick test and it appears to me that upon creation of a new content type or after adding a image field to an existing content type, that the field labels are currently hidden by default. Maybe this issue has been solved elsewhere.

I think that this might still be an issue with views, but that would be a different issue.

**Comment by klonos** [comment]
...FTR, this was done as part of #317, with commit https://github.com/backdrop/backdrop/commit/7ec8b7522e8f984638493a7f49895a3131aeb642
