### ISSUE TITLE
Entity queries assume entities to be defined with ['entity keys']['id']

### ISSUE THREAD

**Issue by oadaeh** [backdrop/backdrop-issues#2905]
## Describe your issue or idea
In the core/modules/entity/entity.api.php file is this snippet of documentation (at lines 41-42):
```
 *   - entity keys: (optional) An array describing how the Field API can extract
 *     the information it needs from the objects of the type. Elements:
```
Which means that this is only necessary if the entity being defined is fieldable. Also, the 'fieldable' element defaults to FALSE (even though that part is not documented - see line 36 of core/modules/entity/entity.api.php and lines 173-186 of core/modules/entity/entity.module).

However, in core/modules/entity/entity.query.inc at about lines 815-822, it is assumed that $entity_info['entity keys']['id'] (and therefore $entity_info['entity keys']) will always exist:
```
    // Process the four possible entity condition.
    // The id field is always present in entity keys.
    $sql_field = $entity_info['entity keys']['id'];
    $id_map['entity_id'] = $sql_field;
    $select_query->addField($base_table, $sql_field, 'entity_id');
    if (isset($this->entityConditions['entity_id'])) {
      $this->addCondition($select_query, $base_table . '.' . $sql_field, $this->entityConditions['entity_id']);
    }
```

So, one of two things needs to happen:
1. The documentation needs to be corrected, or
2. The code needs to be modified to not assume that neither ['entity keys']['id'] or ['entity keys'] are present (and it may be that there are other places where that change might need to be made).

I believe it should be the second, but I don't know if the future way of things with entities in Backdrop is to assume that all entities are fieldable or not.

### Steps to reproduce (if reporting a bug)
I found this by creating a basic, custom entity with as few options defined as possible, enabling the Entity UI module (https://github.com/backdrop-contrib/entity_ui) and attempting to view the entity's admin UI page.

### Actual behavior (if reporting a bug)
2 PHP notices like this:
> Notice: Undefined index: id in EntityFieldQuery->propertyQuery() (line 817 of /backdrop/core/modules/entity/entity.query.inc).

a PDOException, and the page did not load.

### Expected behavior (if reporting a bug)
The page loads without any errors in the log.

### Relevant version/system information (if applicable)
The downloadable copy of Backdrop 1.8.0 (though the code is currently the same in 1.x) and the current (at the time of this writing) Entity UI module.

**Comment by oadaeh** [comment]
It appears that this code comes to Backdrop via Drupal 7, so I may need to spend a little time there trying to figure out why I haven't encountered this error before (or maybe I have and don't remember it).

**Comment by oadaeh** [comment]
I have not forgotten about this, I've just been preoccupied elsewhere.
I did verify that the same issue exists in Drupal 7 core, but I believe the only progress I will be able to make there is a documentation change, so once I get that started, I will do the same here.

**Comment by quicksketch** [comment]
Thanks @oadaeh and @herbdool (for the review)! Merged in https://github.com/backdrop/backdrop/pull/2108 into 1.x and 1.9.x.
