### ISSUE TITLE
Give menu items the same language as the underlying node 

### ISSUE THREAD

**Issue by bjoern-st** [backdrop/backdrop-issues#2907]
## Describe your issue or idea
Give menu items the same language as the underlying node in helper function menu_node_save.
Helper for hook_node_insert() and hook_node_update().

### Steps to reproduce (if reporting a bug)
 - Enable module "Content Translation", enable one of your content types to be translated.
 - Create an new node in a defined language.
 
### Actual behavior (if reporting a bug)
 The menu item has no language relation to the node language - there is no language set.

### Expected behavior (if reporting a bug)
The menu item should have the same language as the underlying node.

**Comment by olafgrabienski** [comment]
@bjoern-st That sounds like a very useful enhancement for multilingual sites. I can't evaluate the code, would be happy if we could get feedback from others. (Tagging the issue as such.)

**Comment by bjoern-st** [comment]
That was the idea @olafgrabienski
Unfortunately the code failed one test, but i was not able to see the details.

But with that enhacement it would be much easier to show only the menu items corresponding to the current language. 
I've tested that and in the current backdrop setup menu items can be attached to a language ( please see also https://github.com/bjoern-st/language_menu_item ). But if languages are enabled, this shoul be the normal behavior. 

So let's see :-) 

Cheers 

Bjoern

**Comment by serundeputy** [comment]
@bjoern-st I'm guessing the test failures are random as PHP 5.3 tests all passed and only a couple failed in PHP 7.

I'm looking at the PR now which looks great; I'm struggling with manual testing as my language skills are weak to non existent 🐶 .

**Comment by bjoern-st** [comment]
Thanx @serundeputy 

I tried to look at the details, but I got a "page not found" error.

Cheers Bjoern

**Comment by serundeputy** [comment]
I've done these two steps:
> * Enable module "Content Translation", enable one of your content types to be translated.
> * Create an new node in a defined language.

On the sandbox site: http://2037.backdrop.backdrop.qa.backdropcms.org/node/3

But the menu is still in english; Oh; I bet i have to upload the french po files 🔹  :duh:

**Comment by bjoern-st** [comment]
Of course your menu is still in english @serundeputy.

That patch doesn't translate your menu .. it's just for giving the corresponding menu item the same language as the created / updated node .. so both of them can be filtered out when selecting a language for a multilingual site.
And of course you have to enable mor than one language in your sandbox .. than you'll see the difference

**Comment by serundeputy** [comment]
I uploaded: `drupal-7.56.fr.po` to the sandbox: http://2037.backdrop.backdrop.qa.backdropcms.org/admin/config/regional/language

Still see the english menu.

**Comment by serundeputy** [comment]
I guess it translates the `account` menu but not the `primary navigation`:
<img width="1524" alt="screen shot 2017-11-13 at 6 30 59 pm" src="https://user-images.githubusercontent.com/6763671/32754920-e2d6524c-c8a0-11e7-83ef-d1dd066c79a6.png">

**Comment by olafgrabienski** [comment]
@serundeputy The `account` menu is translated for another reason: "My account" and "Log out" are user interface strings.

**Comment by olafgrabienski** [comment]
@bjoern-st I've had a look at the sandbox site:

- configured pages to be translatable
- assigned English as a language to the "About" page
- translated "About" to French ("A propos de"), and made a corresponding menu item

Translation worked well, and I can switch between the pages using the language link below the content. But both menu items ("About" / "A propos de") show up, irrespective of the page I visit. Any idea what I could have missed?

**Comment by bjoern-st** [comment]
Hey @olafgrabienski 

You have missed nothing. To achieve that we still need some preprocessing. 
One option would be to preprocess your menu blocks as described here: https://github.com/bjoern-st/language_menu_item/wiki/Make-language-sensitive-menu-blocks

I'm lookimg for a more complete solution, but this will take some time.

**Comment by bjoern-st** [comment]
Hey @olafgrabienski .
Menu items of translated nodes are stored as language neutral.
And by now the functions, that build the menus, are not language sensitive.
So we still need to make the step with the preprocessing. This is only a patch for menu items with nodes in a defined language should be stored with the same language context. 


Hey @serundeputy .. please  read the issue :-) 

So this is just a first step to make backdrop multilingual.

**Comment by olafgrabienski** [comment]
@bjoern-st Thanks for your feedback, sounds reasonable! Are you considering to make the menu building functions language sensitive? That would be great!

One more question: Where would I place the preprocess code (to test the patch)?

Off topic: Are you by chance interested to help out in a Backdrop [transliteration issue](https://github.com/backdrop/backdrop-issues/issues/2637)? (Saw "Berlin" as location on your Github profile.) The issue might sound complicated over there, but essentially it's just about transliterating URL aliases according to a site's default language (like German) when the site is not multilingual but only localized. That doesn't work in the moment in Backdrop. Maybe you have an idea?

**Comment by bjoern-st** [comment]
Hey @olafgrabienski 

I'll have a look at your Issue https://github.com/backdrop/backdrop-issues/issues/2637. But right now I have a rough time in my office.

The preprocessing can be placed at two different places:
- template.php .. please have a look at https://api.backdropcms.org/creating-sub-themes
- in your custom module with hook_preprocess_Hook

If need further help, please feel free to ask here.

Cheers Bjoern

**Comment by quicksketch** [comment]
This change seems like a good one to me. It's a very small incremental approach to full menu item translation.

You might also take a look at #225, which includes this change as part of a much larger effort to make menu items fully translatable in core. That PR has always been very close, but I think it has some usability problems.

I think making this one change separate seems like a good idea, then we can continue working on the more comprehensive solution in #225.

**Comment by quicksketch** [comment]
Oh, I just realized that this does take a slightly different approach. The PR in #225 makes a dedicated column in the database for `langcode`, while this sets the language in `$link['options']['language']`. Is that property specially treated anywhere in Backdrop currently? Or is the idea that this provides the ability to check the language by some other means later?

**Comment by bjoern-st** [comment]
Hello @quicksketch 

I took that approach because as I had a look at that I found, that menu items by default has a variable called 
"localized_options". This value is set correctly if you set the '$link['options']['language']' value. 
I was hoping that this value is used somewhere, but it doesn't seem so. 
The downside of that approach is, that '$link['options']' is stored as blob in the database, so it can't be used for searching or filtering when building the menu tree. 
So filtering the menu tree is necessary after building the complete tree. 

I'll have a look at #225 as soon as I find the time.

**Comment by quicksketch** [comment]
Let's close this in favor of https://github.com/backdrop/backdrop-issues/issues/225, which is comprehensive in its fixing. It makes a dedicated column in the database for langcode, and actually builds in support for saving and displaying menu items in different languages. It also includes the fix here, though using the new dedicated property for langcode instead of putting it inside of the "options" property.
