### ISSUE TITLE
Admin site information - unable to upload favicon.ico

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2912]
I experienced this response when I tried to use the system information page to upload a favicon.ico file
![site_information](https://user-images.githubusercontent.com/10559274/33529183-eed01140-d864-11e7-9d1f-747719158654.png)

The wording of the page suggests that this should be possible. Have I got something wrong in my system?
![shortcut_icon](https://user-images.githubusercontent.com/10559274/33529196-1eb6db1e-d865-11e7-930f-cc138aade190.png)

**Comment by BWPanda** [comment]
Is this still an issue for you @Graham-72? I just tried on a new install and it works fine for me. Were you perhaps trying to upload a favicon.ico to the Logo field?
