### ISSUE TITLE
[backport] Use text instead of blob for locale source/target and watchdog variables

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#2913]
## Describe your issue or idea
Several Locale tests and a Node test fail when run against pgsql.  All of these tests fail because of SQL queries with a WHERE clause against a blob column, but succeed if the column is a text column.  All three of the columns are explicitly for textual data.

### Steps to reproduce (if reporting a bug)
This is a backport of one of a number of patches for silkscreencms/silkscreen-issues#6.  Like other backport issues, this one doesn't fix a specific issue with Backdrop, but the patch does apply and has no negative impact on Backdrop.

### Actual behavior (if reporting a bug)
Some Locale tests and the NodeCreationTestCase fail.

### Expected behavior (if reporting a bug)
Tests pass.

### Relevant version/system information (if applicable)
SIlkscreen 1.8.0 / Backdrop 1.8.0

**Comment by quicksketch** [comment]
Ironically, it looks like this column was changed from `text` to `blob` in D7 specifically for PostgreSQL, it seems as though reverting it back to `text` may cause regressions. Could you read through https://www.drupal.org/node/690746 and post how that might relate to Backdrop today?

**Comment by quicksketch** [comment]
I'm going to go ahead and move this to needs work, as per the Drupal issue: if we convert some of our serialized columns, we should do all them.

But if this turns out to only be a testing issue, perhaps fixing or adding an exception in tests would be a better approach.

**Comment by jlfranklin** [comment]
I guess none of the tests save objects with private fields, since that's what breaks the serialize-to-text-columns in PostgreSQL.

From the d.o issue:
> Blob fields for serialized data makes sense, its serialized therefore there is no need to index or search on such fields.

One of the broken tests is a problem with the test itself.  We're doing a `WHERE serializedColumn LIKE '%foo%'` to verify (IIRC) a watchdog entry.  That test can be converted to iterate over the Watchdog records, filtered by type.

The others test failures are in Locale tests.  I'll have to dig deeper into those, but I have a bad feeling about them.  The schema for `locales_source` and `locales_target` defines the source and translated strings as blobs, which would be impossible to search.

Ugh.  Just found it.  In commit [4301a86edb](/backdrop/backdrop/commit/4301a86edb#diff-c93370c6f6233145211ba46c8e19c047), they were converted from `'type' => 'text', 'mysql_type' => 'blob'` to simply `'type' => 'blob'`, which is totally sensible if all you intend to support is MySQL (and friends.)

I'll update the patch here to revert back to the type/mysql_type definition, and update the watchdog test.

I don't like them being two different types, but it may be the best solution.  Why are `source` and `translation` serialized in the first place?

**Comment by jlfranklin** [comment]
Updated the PR.

The Drupal issue converted certain serialized `text` fields to `blob` because PHP's `serialize()` would add `NULL`s in the middle of objects with private or protected members.  The `text` columns in PostgreSQL would stop at the `NULL`, truncating the serialized data.

The `locale` columns are not serialized, they're just straight (UTF8) text, so they can be converted to `text` without a problem.  The `variables` column in `watchdog` is serialized, so it should stay the way it is.

The PR is changed as follows:
* Converting the serialized `variables` column in `watchdog` is dropped.
* The one failing test in `node.test` that tries to use `LIKE` on the `variables` column is changed to search the results of the `db_query()` rather than using a `WHERE .... LIKE` clause in the SQL.
* The not-serialized `source` and `translation` columns in the `locale` module remain converted from `blob` to `text`.

**Comment by quicksketch** [comment]
Thanks @jlfranklin for the PR (and sorry for the review delay). The PR looks great to me. As the entire point of dropping other database support was to lessen restrictions and edge-cases needed to support other database systems, I'm happy to see it's fixing general issues with Backdrop rather than being adding work-arounds for other DBs.

This looks good to me but I'm nervous about including it in the 1.10 release. I've marked it RTBC but moved it to 1.11.0 so it will be not in the May 15 release but the Sept 15 one.
