### ISSUE TITLE
Forum: Spam everywhere

### ISSUE THREAD

**Issue by simone960** [backdrop/backdrop-issues#2916]
The new forum has plenty of spam and getting worse. Report was made but no response and actions taken so far. Honeypot not working? Hopefully someone from the community can clean up. Thanks.

![spams](https://user-images.githubusercontent.com/7530286/33646729-302d0f16-daa5-11e7-9c26-7cb10fca9715.jpg)

https://forum.backdropcms.org/forums-custom/other

Issue reported:
https://github.com/backdrop-ops/forum.backdropcms.org/issues/47

**Comment by olafgrabienski** [comment]
@simone960 Thanks for your report! @docwilmot is aware of the issue and working on it but has to wait that Captcha gets committed to the forum.

**Comment by simone960** [comment]
@olafgrabienski You are welcome. Glad to know @docwilmot is working on it. I will close the issue then. 
Thanks for the attention.
