### ISSUE TITLE
[UX] Views: Add a "[hidden]" label to fields when excluded from display

### ISSUE THREAD

**Issue by simone960** [backdrop/backdrop-issues#2922]
In Drupal 8, if you "**Exclude from display**" to hide a field...

![exclude from display](https://user-images.githubusercontent.com/7530286/34076688-b8f577ca-e342-11e7-9b7f-594d00756c98.png)

...the field is labelled as **[hidden]** in Views. e.g 

![exclude from display-hidden label](https://user-images.githubusercontent.com/7530286/34076689-c1c1ee2e-e342-11e7-8819-7a38d315fe98.png)

This feature is small but quite useful and important as I always used to name the label with "hidden" when I exclude a field from display in Drupal 7. This practice helps me to see what fields are actually hidden and understand these fields are meant to be used or output somewhere else or in another fields. It also help the developer easily to figure out what's going on in the Views when following up the projects of other developer instead of going round to find out which field is excluded and which is not.  I was surprise this small practice which I learnt initially from Chris Shattuck (buildamodule.com) is added to the core in Drupal 8. I believe there's a good point of adding it. So please consider adding to core in the near future as well. Thanks!

**Comment by olafgrabienski** [comment]
That's an excellent suggestion! I saw the enhancement in Drupal 8 as well, it's indeed very useful. The feature provides good practice by default and makes the life of site builders much easier.

In Drupal 7 and Backdrop I use to fill in a respective hint by myself as "Administrative title", e.g. `Content: Nid [hidden]` but that's an annoying repetitive task, and there's always the risk to forget to do it.

@simone960 Do you have the coding skills to provide a PR?

**Comment by simone960** [comment]
> I use to fill in a respective hint by myself as "Administrative title", e.g. Content: Nid [hidden]

Em... that's another good way of doing it. But as you pointed out, it's an annoying repetitive task, whichever way we do, that's always a chance to forget either to do it or to undo it. Default setting will make life easier. 

> Do you have the coding skills to provide a PR?

I'm afraid not. I'm more familiar with site building and theming. Not a coder really. But I would love to help testing out.

**Comment by olafgrabienski** [comment]
>> Do you have the coding skills to provide a PR?

> I'm afraid not. I'm more familiar with site building and theming. Not a coder really. But I would love to help testing out.

Same here, so tagging as "help wanted".

**Comment by opi** [comment]
Tests for PR https://github.com/backdrop/backdrop/pull/2076 are green \o/

**Comment by olafgrabienski** [comment]
Thanks for your help, @opi! I've created a view in the sandbox site with some hidden fields:

![screen-backdrop-pr-2076-views-hidden-fields](https://user-images.githubusercontent.com/14188307/35174427-afa35394-fd6f-11e7-952a-4c1f053a16aa.png)

Works as expected, great!

**Comment by simone960** [comment]
Thanks @opi ! I have tested too and all is good ! One small but a life saving feature !

**Comment by quicksketch** [comment]
Great addition, thanks @opi for making the PR! Thanks to @olafgrabienski and @simone960 for the testing and suggestion!

I've merged https://github.com/backdrop/backdrop/pull/2076 into 1.x and 1.9.x, this will be in 1.9.1. Thanks!

**Comment by quicksketch** [comment]
On version clarification: UX changes with low code impact can be deployed in bug fix releases, so this will be out in 1.9.1 instead of needing to wait for 1.10.0.
