### ISSUE TITLE
Move 'contextual-links-region' class to end of block classes list

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2924]
When scanning through the source code of a Backdrop site, it can be hard to find where the blocks are because a block looks like this:

```html
<div class="contextual-links-region block block-system-header">
  ...
</div>
```

Meaning, the 'block' and 'block-[BLOCK-NAME]' classes come after the 'contextual-links-region' class.

Here's an example of a block from Drupal:

```html
<div id="block-views-explore-further-block-1" class="block block-views contextual-links-region first last odd">
  ...
</div>
```

Ignoring the fact that Backdrop doesn't have block IDs, it was much easier to read the block classes as they started with 'block'.

I believe this is because, in Backdrop, in the [template_preprocess_block](https://api.backdropcms.org/api/backdrop/core!modules!layout!layout.theme.inc/function/template_preprocess_block/1) function, the contextual classes get added before the basic block classes.

Would it be possible to move the contextual code below the rest of the code in that function, or am I being too pedantic?

**Comment by BWPanda** [comment]
Added PR that addresses this.

**Comment by BWPanda** [comment]
Block classes are now ordered as:

1. 'block'
2. 'block-MODULE-DELTA'
3. Hero block classes
4. Custom classes
5. Contextual links classes

**Comment by herbdool** [comment]
Tested. PR looks good--good suggestion.

**Comment by quicksketch** [comment]
Thanks, great little suggestion! Merged https://github.com/backdrop/backdrop/pull/2240 into 1.x and 1.10.x.
