### ISSUE TITLE
Switch to the Basis theme for the Minimal profile

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2927]
## Describe your issue or idea
@3magnus reported in [the forum](https://forum.backdropcms.org/forum-topic/minimal-profile-default-theme) that we are still using Bartik as the default theme for the Minimal profile, inspite switching to Basis on the Standard profile. We should fix this.

### Steps to reproduce (if reporting a bug)

* Install Backdrop using the minimal profile

### Actual behavior (if reporting a bug)

* Bartik is the default theme

### Expected behavior (if reporting a bug)

* Basis should be the default theme

**Comment by opi** [comment]
@jenlampton Should the title be "Switch to the **Basis** theme for the Minimal profile", or maybe I misunderstood something

**Comment by jenlampton** [comment]
@opi yes, that's right. Thanks for catching that!

**Comment by quicksketch** [comment]
Thanks @jenlampton, @fmann, and @opi! Merged https://github.com/backdrop/backdrop/pull/2083 into 1.x and 1.9.x.
