### ISSUE TITLE
Images cannot have styles applied in CKEditor

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2929]
When you create a style in CKEditor to apply to images (using the 'Styles' dropdown, e.g. `img.bordered|Bordered image`), it won't let you apply it to images you've selected in the editor.

Some Googling revealed this Drupal issue which I think explains the reason for this: https://www.drupal.org/project/drupal/issues/2642808

Hopefully we can fix this in Backdrop?

**Comment by Graham-72** [comment]
I think my question at #2147 is related to this.

Also, there is #2658.

**Comment by BWPanda** [comment]
That second one is a different issue I believe (image styles as opposed to CSS styles), but the first one is the same issue. Closing this in favour of that.
