### ISSUE TITLE
Restyle the Password Confirm element to take less space and work on small screens

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#293]
The password reset styling has always been bulky, but now with the need to work on small screens, the bulkiness is a problem. Here's a screenshot of the current UI on a small screen:

![password-broken](https://cloud.githubusercontent.com/assets/100206/3869796/3ff5d39e-20a7-11e4-9b03-98613fe8e3f5.png)

I'd like to suggest the following adjustments:
- Put the password meter bar inside the textfield instead of outside of it, so the layout does not require additional space.
- Simply say "match" or "mismatch" in the confirmation textfield.
- Hide password hints entirely, as the suggestions are not actually required and often do not result in actually more secure passwords. (See [correct horse battery staple](http://xkcd.com/936/)).

Screenshot from another site that already has this styling applied:

![password-suggested](https://cloud.githubusercontent.com/assets/100206/3869797/45e81406-20a7-11e4-9c4a-4bea84d2fbe4.png)

**Comment by serundeputy** [comment]
[`xkcd`](http://xkcd.com/290/)++;
