### ISSUE TITLE
Some "file edit" language in code was not changed to "file manage"

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2932]
I was glancing over the recent PR for [this issue](https://github.com/backdrop/backdrop-issues/issues/2796) (which was merged) and it seems a bit of the "file edit" language in the code was not fully switched to "file manage". PR coming -- let me know if I read it right.

**Comment by laryn** [comment]
@jenlampton I removed the permission machine name changes.

**Comment by jenlampton** [comment]
@laryn looks great!  Can you please squash the two and change the commit message to be in this format? https://github.com/backdrop/backdrop/pulls
(That will make it easy for maintainers to merge)

**Comment by laryn** [comment]
@jenlampton I changed the title of the PR but I don't see an option to squash via the UI. Am I missing something obvious or is it a permissions thing?

**Comment by jenlampton** [comment]
Hm, maybe it can't be done via the UI. I usually do a `git rebase -i` and squash that way. Then I do a `commit commit --amend -m "new message"` to reword, but you could do that in a rebase too, I think.

**Comment by laryn** [comment]
@jenlampton I'll give it a try. I have seen the squash option in the UI in other repos where I have higher levels of access.

**Comment by jenlampton** [comment]
Maybe that's it, maybe you need to be a committer to see that.

**Comment by quicksketch** [comment]
Thanks @laryn! I've merged your PR. I reviewed this a few days ago and I remember it changed the permission name from "edit files" to "manage files". It looks like that change may have been lost in the latest updates. If we're going for full consistency, including that would also be good.

I've merged https://github.com/backdrop/backdrop/pull/2065 (which updates the form name and some descriptions, but not the permission name). Could you file another PR that includes the permission change?

**Comment by laryn** [comment]
@quicksketch In a review on the original PR @jenlampton indicated: "we can't change the machine name of this permission as it will affect upgrades. this should match the file entity module in D7."

So I took that change out but left the rest.

**Comment by jenlampton** [comment]
@quicksketch backwards compatibility is important ;) If you wanted to change the permission name, we could include an update hook.

**Comment by jenlampton** [comment]
Okay, new PR with an update hook available for review here: https://github.com/backdrop/backdrop/pull/2069

**Comment by quicksketch** [comment]
Thanks for the new PR with the update hook. Upon running update.php however, I get an error:

```
Warning: array_search() expects parameter 2 to be array, null given in file_update_1002() (line 720 of /home/nate/Sites/backdrop/core/modules/file/file.install).
```

Though I'm not sure why. The code appears fine at first glance. I'll look a little further.

**Comment by quicksketch** [comment]
Ah, it's because `user_roles(FALSE, 'edit files')` returns an array of `$role_name => $role_label`, so we need to use the key part, not the value in the returned array. I've pushed an update to the PR that corrects this.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2069 into 1.x for Backdrop 1.9.0. Thanks @jenlampton!
