### ISSUE TITLE
Remove unused 'property_type' key from Email module

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#2933]
The [documentation](https://api.backdropcms.org/api/backdrop/core%21modules%21field%21field.api.php/function/hook_field_info/1) for `hook_field_info()` doesn't mention anything about a `property_type` key, but [`email_field_info()`](https://api.backdropcms.org/api/backdrop/core%21modules%21email%21email.module/function/email_field_info/1) uses it...

Can we add this to the documentation please?

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2782

**Comment by BWPanda** [comment]
So it seems this isn't used in core at all, apart from the email module. And then it turns out that this was copied over from Drupal: https://github.com/backdrop-contrib/email/blob/1.x-1.x/email.module#L18

So this [PR](https://github.com/backdrop/backdrop/pull/2782) simply removes it :slightly_smiling_face:

**Comment by klonos** [comment]
Here's what I was able to find in the internetz about this mysterious property:

- https://drupal.stackexchange.com/questions/34823/what-does-the-property-type-key-do-in-hook-field-info

> They're not part of Drupal core, but are extra keys provided/used by the Entity Module. The comments in `entity.api.php` clear it up quite nicely:
>
>>For providing entity property info for fields each field type may specify a property type to map to in its field info using the key `'property_type'`. With that info in place useful defaults are generated, which is already suiting for a lot of field types.
>>
>>However it's possible to specify further callbacks, that may alter the generated property info. To do so use the key `'property_callbacks'` and set it to an array of function names. Apart from that any property info provided for a field instance using the key `'property info'` is added in too.

- https://www.drupal.org/project/barcode/issues/1608378

> I've created a content type, with a barcode field.
> I want to update the barcode of a node on this content type via rules.
>
> In rules I selected the specific content type as a condition.
But when I select in the actions the action Set data value, the barcode field isn't available.
>
>Is there something i'am missing or is this just not supported?

...

> I added property_type to the barcode.module file and it seem to work without breaking anything!

- https://www.drupal.org/project/email/issues/1160302

> Attached patch fixes bug, corrects typo, and adds a question about 'property_type' in the array.

The question was: `// @todo Is this used somewhere?`

...

> the @todo can go away, though - the 'property type' is used by Entity API contrib module.

- https://www.drupal.org/project/field_countdown/issues/2291465

> I had the same problem, i just added one line of code in `field_countdown_field_info`: `'property_type' => 'date',`
...
> Now this field is available to rules and i can autofill expiration date (in my case 7 days after node is published)

- https://www.drupal.org/project/languagefield/issues/2805191

> I looked at email, link, country, address and commerce_line_item modules on how they support both tokens and entity properties for custom fields. What I learnt is that for a simple, one-column field providing a simple data type like `language_field`, the `hook_field_info()` does not need a `'property_callbacks'` attribute. Instead, it needs to set a proper `'property_type'` attribute (still in `hook_field_info()`) and implement `hook_token_info()` and `hook_tokens()`.
>
>The result is that token `[node:field_language]` yields "English", `[node:field_language:value]` and `$wrapped_node->field_language->value()` yield `'en'`. What's more, `$wrapped_node->field_language` has a `'token'` property type, which enables us to carry on using it with Rules. Everyone happy.

- https://www.drupal.org/project/probabilistic_weight/issues/1879600

> ...the module seems to work fine when doing normal views. I want to add this to Search API as it is a field based weight system and the others aren't. It doesn't seem to be able to be pulled in via Search API as a valid field so that I can use it as an initial sort criteria for my searches. Any reason why? Any help would be useful.

...

> ...you can try adding a line `'property_type' => 'decimal',` ... Now (after clearing caches), probabilistic weight fields will appear in index fields page ...One question, are you using and Search API pages and Search API sorts? ...With the "patch" (the line I told you to add), it looks like it works with those modules

**Comment by klonos** [comment]
...so in D7 it seems that this line is needed in order to provide integration with contrib modules such as Views, Rules, Search API, Token (via Entity API).

But you are right @BWPanda in that I was not able to find any _official_ documentation about it; everything seems to be passed-on knowledge 🤷‍♂

**Comment by BWPanda** [comment]
Hmm, interesting. I haven't read through all the links yet, but I find it funny that there's only one instance of this in core. What about all the other core fields? Do they not integrate with those modules?

**Comment by klonos** [comment]
> ...I find it funny that there's only one instance of this in core. What about all the other core fields?

That's most likely because we have inherited the code from the contrib email module that was merged into Backdrop core early on. I'm also curious why the other field-providing modules we've merged do not implement this 🤔

**Comment by BWPanda** [comment]
Ok, so D7's Entity module added the `property_type` key for core modules/fields: https://git.drupalcode.org/project/entity/blob/7.x-1.x/includes/entity.property.inc#L166

And it seems [Entity Plus](https://github.com/backdrop-contrib/entity_plus) is the successor for the parts of Entity not in Backdrop core: https://github.com/backdrop-contrib/entity_plus/blob/b8b3f13cb270b315941ea2c7356044cc76a9ff6c/includes/entity_plus.property.inc#L167

So I'd say we remove this key from Backdrop core as per my PR, then create an issue to add it to the Entity Plus module, since that's where the rest of the core field support lives.

**Comment by klonos** [comment]
🤷‍♂ wouldn't know. The PR is trivial, and tests are happy, so code-wise this is good to go. Would still need the input of some core committers though.

My worry is that I would be expecting the opposite of removing this code, and moving it to contrib (it's just a single line - so no overhead to maintain it); I would expect that property to be documented, and added to the rest of the contrib modules merged into core. As mentioned in various D7 contrib, the absence of this line breaks things for popular contrib like Rules, Views and Search API. Moving things to Entity API would effectively make it a dependency for all such contrib modules. Am I thinking this the wrong way?

**Comment by BWPanda** [comment]
If the presence of this key is what provides compatibility with Rules, etc. then how are core fields like `text` compatible? The only place their `property_type` key is defined is in the Entity Plus module. So isn't there already a dependency there? If not, let's make Email compatible in the same way that Text is.

**Comment by BWPanda** [comment]
> it's just a single line - so no overhead to maintain

My main concern here is consistency.

**Comment by docwilmot** [comment]
This can be removed. Its only meant for Entity APIs metadata property code, which contrib can add back in via `hook_field_info_alter()` if dependent on Entity Plus. So core doesnt need to worry about that.

**Comment by klonos** [comment]
Fair enough. Thanks for filing https://github.com/backdrop-contrib/entity_plus/issues/14 @BWPanda 👍 

Updating issue title here then...
