### ISSUE TITLE
How to clean up the 'config' files directory?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2938]
I have a database snapshot of my sandbox site, which I just restored to start afresh. However I forgot that Backdrop stores things in the 'config' files directory, and so now there are a bunch of config files for modules that aren't installed anymore.

Now ideally in future I'd backup the 'config' files directory as well as the database, but for now, is there anyway to clean up config?

I couldn't find a module that'd do it, and I couldn't find any API functions that would do it. I'd be interested in writing a module to do this, but I couldn't even find any API functions that would help me map config files to installed modules...

Any ideas?

**Comment by docwilmot** [comment]
whats the 'contrib' files directory?

**Comment by BWPanda** [comment]
@docwilmot Sorry, I meant 'config'. Edited OP to fix mistakes.

**Comment by quicksketch** [comment]
There isn't any tool that I know of that will "clean up" the config directory. Although you'll probably find that configuration imports won't work while you have stray config files present, because no module knows how to handle them.

The config sync system is a bit too complicated to pull an example from, but here's what I would guess would get you somewhere:

```php
// Ask all enabled modules what files they are responsible for.
$prefixes = module_invoke_all('config_info');

// Get all the configurations from the active config directory.
$storage = config_get_config_storage('active')
$all_configs = $storage->listAll();

// Then check if any module knows about each file.
foreach ($all_configs as $config_name => $config) {
  $config_info_found = FALSE;
  foreach ($prefixes as $prefix => $config_info) {
    if (substr($config_name, $prefix) === 0) {
      $config_info_found = TRUE;
      break;
    }
  }

  // If no module knows about this configuration file, do something. 
  if (!$config_info_found) {
    print "Config file $config_name is not known by any installed module!";
    // $config->delete();
  }
}

```

(Note, completely untested probably has syntax errors)

**Comment by BWPanda** [comment]
Awesome, thanks @quicksketch! I'll have a play with that.

**Comment by BWPanda** [comment]
Came up with the following:

```php
$modules = module_invoke_all('config_info');
$files = config_get_names_with_prefix('');

foreach ($modules as $module => $info) {
  foreach ($files as $id => $file) {
    if (strpos($file, $module) === 0) {
      unset($files[$id]);
    }
  }
}

foreach ($files as $file) {
  $config = config($file);
  $config->delete();
}
```

Works for me. Might see if this can be added to Devel module or something...
