### ISSUE TITLE
Basis missing margin on aligned images

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2940]
## Describe your issue or idea

When editing a piece of content with Basis as the front-end theme, CKEditor (correctly) includes a margin on images that are aligned left or right:

![image](https://user-images.githubusercontent.com/100206/34966471-c7d885d6-fa10-11e7-942d-c2d475c85b1f.png)

But when viewing this content on the front-end, there is no margin:

![image](https://user-images.githubusercontent.com/100206/34966497-e23607d2-fa10-11e7-877a-49c796e0ffc4.png)

### Steps to reproduce (if reporting a bug)

- Create a Post piece of content.
- Insert and align an image left.
- Save and view the content.

### Relevant version/system information (if applicable)

Backdrop 1.8.1.

---

PR: https://github.com/backdrop/backdrop/pull/2070

**Comment by quicksketch** [comment]
Pushed up a quick fix that copies the default styles from system.theme.css into Basis. Merged https://github.com/backdrop/backdrop/pull/2070 into 1.x and 1.8.x.

**Comment by olafgrabienski** [comment]
@quicksketch Nice quick fix! I think, `core/themes/basis/css/component/caption.css` isn't the right place (the fix isn't about image captions). I'd suggest to put it in `core/modules/system/css/system.css` instead, there are already some image alignment definitions in lines 330-335.

(Not sure if I should reopen this issue or make a new one.)
