### ISSUE TITLE
Sites just upgrading to Backdrop 1.9.0 cannot visit `user/login` path (Page not redirecting properly)

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2943]
## Describe your issue or idea

Sites that are upgrading to Backdrop 1.9.0 may have a problem visiting the login page immediately after updating their code base. It's common to log into your site after doing an upgrade, so that you can get authenticated to visit update.php. But with the login page broken, that may make things more difficult for users. The only way they can run update.php is by:

- Adding `$settings['update_free_access'] = TRUE;` in settings.php.
- If they are already logged in, visiting update.php directly.
- Using `drush updb`

### Steps to reproduce (if reporting a bug)

- Install a clean Backdrop 1.8.2
- Log out.
- Upgrade to Backdrop 1.9.0
- Attempt to visit /user/login

### Actual behavior (if reporting a bug)

- You get infinitely redirected to /user/login. The browser will show a message indicating, "The page is not redirecting properly".

### Expected behavior (if reporting a bug)

- The login form is shown.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2074

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/2074 that fixes this problem, but I'm not sure if it's a good implementation. Doing lazy checks like this sometimes result in the action being performed when it's not intended. And in the case of running a `menu_rebuild()`, that could be very bad for a site. However, I can't think of any way you'd end up in the `user_page()` menu callback unless the menu was out of date (from earlier versions of Backdrop). So even though this fix isn't very pretty, I don't think it would cause any harm.

**Comment by jlfranklin** [comment]
> So even though this fix isn't very pretty, I don't think it would cause any harm.

Yesh.  It does feel kinda like a hack to fix something that shouldn't be broke in the first place, and for a specific instance, not a general case.  

I just ran into this issue on a site I'm upgrading.

**Comment by quicksketch** [comment]
In lieu of any other available fixes, I've merged https://github.com/backdrop/backdrop/pull/2074 into 1.x and 1.9.x so we can prevent this problem for users upgrading to 1.9.1.
