### ISSUE TITLE
Correct format of $config_directories in settings.php?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2944]
When I had individual websites running on individual instances of Backdrop, my settings.php file was given the following on installing a new site:

`$config_directories['active'] = 'files/config_[RANDOM_STRING]/active';`

Whereas when I installed a new site in a multisite setup, it was given the following:

`$config_directories['active'] = './sites/[SITE_NAME]/files/config_[RANDOM_STRING]/active';`

I've since moved all individual sites into the multisite setup, and everything's working, but I have the two different formats for the `$config_directories` array now.

Which is correct? And why does one start with a '.' and the other doesn't? Are they both relative to the backdrop root directory, or is the one without the '.' relative to the sites directory?
Confused...

**Comment by BWPanda** [comment]
BTW, the default settings.php has the following by default:

`$config_directories['active'] = 'files/config_' . md5($database) . '/active';`

i.e. no '.'

**Comment by BWPanda** [comment]
I basically want to get all my settings.php files matching, so they all use the correct, up-to-date format for the `$config_directories` array setting.

**Comment by jenlampton** [comment]
> Which is correct? 

they both are.

> And why does one start with a '.' and the other doesn't?

No idea, maybe an oversight?

> Are they both relative to the backdrop root directory

Yes. That's why your multi-sites need to start with `sites`. The `files` directory is in the backdrop root directory by default. It can also be moved to `sites` for your multi-sites.

**Comment by BWPanda** [comment]
Ok, so if they're both correct, and they're both relative to the root directory, then my next question is why does the first example still work?

When I had individual Backdrop sites as mentioned above, this is what my settings.php file looked like:

`$config_directories['active'] = 'files/config_[RANDOM_STRING]/active';`

I've since moved those sites into one Backdrop install as multisites, and even though I changed the value of my 'Public file system path' in the UI to 'sites/[SITE_NAME]/files', the settings in settings.php in still:

`$config_directories['active'] = 'files/config_[RANDOM_STRING]/active';`

And it still works. There's nothing in the foot files directory except a README.md.

What is the relationship between the settings.php setting and the 'Public file system path' value at /admin/config/media/file-system?

**Comment by serundeputy** [comment]
@BWPanda It is relative to the location of the `settings.php` file in question (you could have more than one in different directories). 

For a single Backdrop installation installed in `BACKDROP_ROOT` both:

```php
$config_directories['active'] = 'files/config_[RANDOM_STRING]/active';
```

and


```php
$config_directories['active'] = './files/config_[RANDOM_STRING]/active';
```

will work; the `.` just start this path relative to where we currently are in this case `BACKDROP_ROOT`

If you have a `settings.php` for each multisite in `BACKDROP_ROOT/sites/[SITE_X]/settings.php` then the config string could be:

```php
$config_directories['active'] = 'files/config_[RANDOM_STRING]/active';
```

as well. As it will be relative to this settings file.

**Comment by serundeputy** [comment]
@bwpanda I'm going to close this as answered. Reopen if you need more info.
