### ISSUE TITLE
'exclusive' install profiles are ignored

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2947]
The 'exclusive' flag for install profiles makes it so that the install profile selection form is skipped and the exclusive profile is run automatically.

However, the code where this happens has a bug. It only lists a profile as 'exclusive' if it's also 'hidden'. This is basically the result of using an `elseif` instead of just an `if`.

**Comment by BWPanda** [comment]
Added PR.

**Comment by jenlampton** [comment]
Nice catch!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2075 into 1.x and 1.9.x. Thanks @BWPanda!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2075 into 1.x and 1.9.x. Thanks @BWPanda!
