### ISSUE TITLE
Document '#token_types' form API parameter

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2951]
The documentation for [token_element_validate()](https://api.backdropcms.org/api/backdrop/core%21includes%21token.inc/function/token_element_validate/1) says:

> Form elements that want to add this validation should have the #token_types parameter defined.

However, the `#token_types` parameter isn't documented anywhere on the [Form API](https://api.backdropcms.org/form_api) page...

**Comment by BWPanda** [comment]
Ping @bugfolder 🙂  I know you were doing lots of updates to the Form API page...

**Comment by bugfolder** [comment]
I've added `#token_types` as a property, but it appears that the Properties edit UI is broken on docs.b.org. See, for example, https://docs.backdropcms.org/node/46553/edit.

**Comment by bugfolder** [comment]
Properties edit UI is working again, and `token_types` has been added as a property to all elements that accept the `#value` property. Also some notes added to `#value` and `#token_types` documentation.
