### ISSUE TITLE
Fix taxonomy placeholder and move implementations of hook_layout_context_info() into node, taxonomy, & user modules.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2952]
## Describe your issue or idea

I discovered `hook_layout_context_info()` today and was surprised that only Node module implemented this hook. What about the other types of core contexts that are present for layouts? I believe this layout info is necessary for terms and users to have required contexts in contrib.

edit: I'm tagging this issue as a bug report because the previous context info provided for taxonomy terms used the wrong placeholder value. A fix for that is included in this PR.

---
~~PR: https://github.com/backdrop/backdrop/pull/2080~~
PR: https://github.com/backdrop/backdrop/pull/2112

**Comment by jenlampton** [comment]
Aha, I've found them!  It appears that layout module has been doing the work taxonomy, and all the contexts have been added in `layout_layout_context_info()`. I think we should move taxonomy's to taxonomy module, and possibly user's to user module.

**Comment by jenlampton** [comment]
Thanks to @opi's feedback I've updated the PR. I've changed `User` to `User account` and `Node` to `Content (node)`. I've also moved the node context into node.module.

**Comment by opi** [comment]
Approved !
