### ISSUE TITLE
Blocks of existing content should follow the translation system

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#2957]
We recently discussed a promising approach to allow the translation of block content in the [Backdrop4Good issue about block translation](https://github.com/Backdrop4Good/backdrop4good.org/issues/39#issuecomment-350908345) and in the [core issue about page-less nodes](https://github.com/backdrop/backdrop-issues/issues/100#issuecomment-353688485):

1. make a (page-less) node type for content blocks
2. translate content using core "Content translation"
3. place content as "Existing content" block in a layout

It then turned out, that blocks of existing content in a layout don't follow the content translation system. When you place such a block, it is chosen by node ID, but in contrast to the node module the layout system doesn't look for translations of the node. Consequently it just displays the 'original' node even if a visitor is using the site in a different language and there are translations available.

So, here are my suggestions:

- Make "Existing content" blocks in layouts aware of the content translation system.
- Add a checkbox to follow the translation system on the block configuration form.

--
Replaced by https://github.com/backdrop/backdrop-issues/issues/3464

**Comment by klonos** [comment]
> - Add a checkbox to follow the translation system on the block configuration form.

Although I do not oppose this, why should this be an option? If a content block has been translated to another language and the entire page is being rendered/viewed in that language, then would there be legitimate use cases (80/20 rule) where one would not want the translated content block to be shown?

**Comment by klonos** [comment]
...by the way, I see this as a multilingual system bug and not a feature request, but I will refrain from changing the issue status.

**Comment by olafgrabienski** [comment]
>> Add a checkbox to follow the translation system on the block configuration form.

> why should this be an option?

Not sure, IIRC that was a suggestion by @quicksketch . Maybe because of backwards compatibility? (For the time being, you have to place several blocks, each for one language, and apply a respective visibility condition. I guess such a configuration would break if you follow the translation system, and in this case the checkbox would make sense.)

**Comment by klonos** [comment]
Well, I guess that currently most likely people are using the multiple blocks per language approach to get things translated. This was never seen as a viable, long-term solution though; merely a workaround. I honestly do not see an easy way to have a migration/upgrade path from that to whatever solution we end up implementing in core. Although...

AFAIR, when translating content in Drupal, one can only add translations to a "source" node by creating new nodes (pressing the "add translation" button opens a node edit form). What would be interesting is to have that "add translation" button allow people to either create a new translation, or add an existing piece of content as the translation of the source. That would be something and it would allow people to add (actually reference) other blocks as being the translated versions of other blocks. Just an idea; have not fully fleshed that one out yet.

**Comment by jenlampton** [comment]
This definitely sounds like a bug to me @olafgrabienski. The rendered node should always take into account the site's language.

Hm, this problem doesn't look like it has anything to do with the block. I can print out the site language in `node_view()` and it's correct, but it's still showing me the wrong translation of the node. 

In fact, after I've translated the about page into Spanish `/es/about` still shows me the english version. I have to go to `es/about-1` to see the Spanish translation. Is that how this is supposed to work?

**Comment by olafgrabienski** [comment]
>> The rendered node should always take into account the site's language.

> Agreed! (...) I think however that there's a conceptual challenge regarding how nodes and blocks work.

So, here's the conceptual challenge how I see it: When you place a block of existing content, it is chosen via Content title or ID in an autocomplete form, resulting in something like the following in the autocomplete: `Existing content example [5]`. I guess the content ID gets saved, and that's an English content in this case. As the content ID is the relevant information and translations are just new nodes with other IDs, I can also chose a translation of `node/5` like the Spanish `Contenido existente: Ejemplo [7]` in the block placement configuration.

If both of the above -- the placement of a source node and the placement of a translation -- are valid choices, it's kind of understandable that exactly the chosen values (and not a translation) is displayed, even if it doesn't make sense.

I'd suggest that, as a first step, Backdrop looks for the language status of existing content in the block placement configuration and provides only the source of translated content, not the translations. In a second step, existing content blocks should then follow the translation system, like nodes do. Does that make sense?

**Comment by jenlampton** [comment]
I suspect I may not fully understand how the translation system works. But that might be a good indicator that there's a DX issue here if I can't figure it out :) Either way, no PR here yet.

**Comment by jenlampton** [comment]
No PR here yet, removing milestone. (We can add it back into the next bug-fix release as soon as we have a PR)

**Comment by sthomen** [comment]
I bumped into this problem yesterday and wrote a small module that adds the functionality in a new block--Existing content (translated)--by extending NodeBlock. It can be found [here](https://github.com/sthomen/translated_node_block).

It seems to me that it's the cleaner/simpler solution to not modify the node module to be language aware (unless it already is, I didn't check, and I'm still unfamiliar with backdrop...), but instead add this functionality to translation and keep it as a separate block type. This retains separation of concerns, node doesn't need to depend on translation and the choice of wheter you want to translate a block follows naturallly if your site has installed content translation--look for a block for existing content, "ah, I want the translated version here".

**Comment by klonos** [comment]
Thank you for taking the time to put this module together @sthomen. I think though what needs to be done here is to ensure that multilingual works as expected in Backdrop core. If people start using a contrib module, then moving back into the core functionality (once this issue here is fixed) might prove hard and require manual work.

Having said that, I have to acknowledge that perhaps we have not been prioritising multilingual support as much as we should. I have no explanation or excuse other than the fact that we are a small community and so we are often shorthanded. On the bright side, I think that we are doing a much better job than Drupal in how (relatively) fast we are addressing issues that frustrate our users.

Anyway, next step here is to bring this topic (not this issue here specifically; multilingual in general) up during our next dev meeting. We already support custom block translation since 1.10 (#2956), we also have recently added support for translating taxonomy terms (#2934), and we have merged work required for configuration translation (#704). So perhaps we have enough use cases to use as examples or starting points, and we have one less issue to worry about (if this issue here depends on config translation).

Please bear with us as we are working on multilingual support @sthomen ...we are pedalling as fast as we can 😄. Also stay tuned, because we might need feedback and/or help with testing pull requests.

**Comment by olafgrabienski** [comment]
@sthomen Thanks for your input! Does the custom module work for you?

You suggested "to not modify the node module to be language aware (unless it already is ...)". I'm not sure if the mode module is "language aware" (or if I got the meaning of the question), but content translation generally works in Backdrop.

I guess, we need more feedback and/or help from people who know both Backdrop and Drupal's translation system. Maybe @herbdool?

**Comment by herbdool** [comment]
@sthomen I like your module. I think too that it could be incorporated into the translation module. An alternative would be to edit the NodeBlock with a conditional checking if the translation module exists. Maybe not as elegant but it would mean one less block. That being said, having it as a separate block isn't so bad either.

**Comment by herbdool** [comment]
I don't consider this a bug. This worked the same way in D7. Even if something doesn't work how you expect it to work, doesn't make it a bug. We have to evaluate it against its actual built behaviour and whether it's failing.

@sthomen I encourage you to file a PR with your idea, adding this to the translation module.

**Comment by sthomen** [comment]
I've added a feature request #3464, with a patch for the translation module. Please tell me if I'm doing this right :-)

**Comment by olafgrabienski** [comment]
Thanks for the patch [over there](https://github.com/backdrop/backdrop-issues/issues/3464) (@klonos made a PR from it), I've tested it, and it works like a charm, see https://github.com/backdrop/backdrop-issues/issues/3464#issuecomment-453082137.

As a non coder, I'm not sure about the best approach (make blocks of existing content language aware vs. new block type), but for me as a site builder, the latter would do the job.

**Comment by herbdool** [comment]
I think you're right @olafgrabienski
