### ISSUE TITLE
New theming experience with Atomium

### ISSUE THREAD

**Issue by drupol** [backdrop/backdrop-issues#2959]
## What it is

Atomium is a base theme that aims a better use of templates and better themes mechanisms to ease everybody's experience, from the theme integrator to the developers.

On of the complexity in the theme layer lies in the fact that Drupal/Backdrop allows you to define/render HTML from a template file or from a PHP function. And defining them is often complex.

Drupal 7 with standard profile defines 152 HTML elements or commonly named ‘hook themes’. 132 of them are made out of PHP functions. The 20 leftovers are from templates. According to me, mixing templates and functions for rendering HTML is a bit messy.
HTML should resides in template files and should be easy to extend.

I recently published a new branch of Atomium: [backdrop](https://github.com/ec-europa/atomium/tree/backdrop), compatible with Backdrop 1.x.

It's in sync with the [7.x-2.x branch of Atomium](https://github.com/ec-europa/atomium/tree/7.x-2.x) which has been written for D7.

I also rewrote the **basis core theme** into **atomium_basis** to provide an example on how to use it.
It has the same visual result as the **basis core theme** provided by Backdrop.

I'm looking for people interested into improving Atomium for Backdrop.

IMHO, it has very interesting set of features, some of them are unique to Atomium.

Here's a glimpse:

1. Tag attributes are handled via a [PHP Class](https://github.com/ec-europa/atomium/blob/7.x-2.x/atomium/includes/classes/Attributes.php),
2. Attributes values can be nested, append-ed, removed, cleared, [from the preprocess](https://github.com/ec-europa/atomium/blob/7.x-2.x/atomium/templates/block/block.component.inc) or [from the template directly](https://github.com/ec-europa/atomium/blob/7.x-2.x/atomium/templates/block/block.tpl.php),
3. All the core theme hooks are converted into a template file, no PHP functions are used to render HTML when using Atomium,
4. No calls to the `theme() function` in any **preprocess** or **process** functions. We only deals with arrays (_process workflow has been removed from Atomium for Backdrop as [process hooks has been removed](https://github.com/backdrop/backdrop/pull/560)_),
5. Preprocess functions can be inherited ([see issue on drupal.org](https://www.drupal.org/node/2563445)),
6. Code is clean, [GrumPHP](https://github.com/phpro/grumphp) is enabled so your code is automatically checked for the codestyle and PHPUnit tests are runned also, 
7. Tests are runned against a nifty scaffolding system based on [OE Task Runner](https://github.com/ec-europa/oe-task-runner),
8. Visual regressions are about to be included in the tests [very soon](https://github.com/ec-europa/atomium/pull/63),
9. JS and CSS can be automatically loaded from component,
10. Many more features...

I wrote [a blog post about Atomium](http://not-a-number.io/2017/a-word-about-atomium) not so long ago but it has evolved so much that some parts are outdated, but it can already give you an idea on the history of the project.

Let me know what you think about this whole idea and the theme, don't hesitate to "_test it, fork it, break it, report it, pull it, retry it_", I'm quite reactive and I'm already looking forward for your feedback!

**Comment by BWPanda** [comment]
Closing this core issue in favour of the issue queue at https://github.com/backdrop-contrib/atomium
