### ISSUE TITLE
Update documentation for filter_format_save()

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#2962]
The documentation for [filter_format_save()](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.module/function/filter_format_save/1) mentions nothing about these properties:

- editor
- editor_settings

Both of which are used in [standard_install](https://api.backdropcms.org/api/backdrop/profiles%21standard%21standard.install/function/standard_install/1).

**Comment by BWPanda** [comment]
Same with [`filter_format_build_format()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.module/function/filter_format_build_format/1).

**Comment by klonos** [comment]
Looks good @BWPanda 👍🏼  ...thanks.

**Comment by BWPanda** [comment]
Thanks @klonos. Merged https://github.com/backdrop/backdrop/pull/3921 into 1.x and 1.21.x.
