### ISSUE TITLE
Include managed files in autocomplete for links.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2963]
When using the Rich-Text editor and inserting links the autocomplete function will offer nodes, users, taxonomies and views but not files. It would be helpful to include managed files that are registered in the file_managed data table.
The desirability of this has been identified in issue #2072.

**Comment by herbdool** [comment]
Hi Graham,

It's hard to review the full functionality of this PR without also having them all together in one PR. Maybe it's okay to have it all in one PR but reference each separate issue? Then we can review it together.

**Comment by jenlampton** [comment]
This looks like a straightforward fix, though I wonder if on a site with tons of files it might make the autocomplete very slow. I still think it's a good improvement and would like to see it included. One minor not spotted by @opi in the PR, changing to NW for a tweak.

**Comment by Graham-72** [comment]
I think this issue is now included in my PR for #2072 although maybe the comment by @opi needs to be applied there. Maybe this issue should be closed?

**Comment by jenlampton** [comment]
Closing (and removing milestone since https://github.com/backdrop/backdrop-issues/issues/2072 was merged!
