### ISSUE TITLE
Add admin settings to CKeditor for upload of files.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#2964]
There are already settings per format for upload of images. 
If uploading of files is to be added to our WYSIWYG (issue #2072 or similar) similar settings for other types of file are needed such as maximum file size, allowed file types and the subdirectory for the files.

**Comment by jenlampton** [comment]
Closing this in favor of https://github.com/backdrop/backdrop-issues/issues/2072 ?
