### ISSUE TITLE
[UX] Add a "delete" operation on the Menus overview page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2968]
## Describe your issue or idea

On the administration page for menus, I'm bothered by the fact that I can't delete a custom menu from the overview listing. Instead, I need to "Configure" the menu to delete it. 

I'd like to add a drop-button to the operations column that allows me to delete the menu item right from here.
<img width="1198" alt="screen shot 2018-02-06 at 10 10 31 pm" src="https://user-images.githubusercontent.com/397895/35901288-c2158b72-0b8a-11e8-8183-511b04e5d16e.png">

---
PR: https://github.com/backdrop/backdrop/pull/2092

**Comment by quicksketch** [comment]
Makes sense. And core-provided menus (e.g. Main Menu, User menu, and Management), can't be deleted at all, so the overall risk is fairly low.

**Comment by quicksketch** [comment]
The PR worked great. Shows the link to delete for custom menus, hides it for system-provided menus, and it goes to the right page.

Merged in https://github.com/backdrop/backdrop/pull/2092 to 1.x and 1.9.x. Thanks!
