### ISSUE TITLE
[UX] Add an "Export" operation on the Menus overview page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2969]
## Describe your issue or idea

I love that you can export the view you just edited directly from the views UI, by using the "Export" drop-button action. I'd love to see this functionality on menus as well.

<img width="1198" alt="screen shot 2018-02-06 at 10 10 31 pm" src="https://user-images.githubusercontent.com/397895/35901568-2e1972ce-0b8c-11e8-9070-89bbca8e28ff.png">

---
PR: https://github.com/backdrop/backdrop/pull/2093

**Comment by quicksketch** [comment]
Let's rework this to use query strings, as mentioned in this sister-issue at https://github.com/backdrop/backdrop-issues/issues/2970.

**Comment by jenlampton** [comment]
There's a commit for this over in the PR on https://github.com/backdrop/backdrop-issues/issues/2960. Marking this issue as dupe.
