### ISSUE TITLE
[UX] Make password fields more touch-friendly: Remove confirmation add show/hide option

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#297]
This is a followup to https://github.com/backdrop/backdrop-issues/issues/293, where we restyled the password confirmation element.

Currently signing up or creating an account from a touch device (be it phone or tablet) is a tedious process because the password must be typed twice. An excellent [article by LukeW promotes an alternative](http://www.lukew.com/ff/entry.asp?1653) where the double-password requirement is disabled in favor of simply showing a password in clear text in the first place so it doesn't need to be typed twice. If you'd like to hide the password, you can click the "Hide" link.

I think LukeW's example (which was for a mobile app only) took things a little bit far by _always_ showing passwords in the clear, but it's a good thing to consider for sign-up/registration forms. Perhaps we could show passwords as normal textfields when signing up, but hide the password by default when signing in. In both cases the password could be toggled by using a hide/show link.

Drupal is also considering this option at https://www.drupal.org/node/2293803

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2129

**Comment by serundeputy** [comment]
I had to change the tests on this one; I think it is ok since the tests were looking for 2 password fields and this PR changed it to one field; thoughts, objections ... anyone, @quicksketch

**Comment by quicksketch** [comment]
Nice, looks like there's some progress here! Thanks @serundeputy for taking it on. A few thoughts:

- I like the idea that you've just left the `password_confirm` field alone and worked on modifying the `password` field.
- However, the password strength indicator is currently only available in the `password_confirm` element, we'd like to maintain this even in the single-password version.
- This currently requires users to manually add a checkbox and a JavaScript file. We could simplify this for developers by making it a property on `password` fields such as:
```
$form['password'] = array(
  '#type' => 'password',
  '#title' => t('Password'),
  '#password_toggle' => TRUE,
  '#password_shown' => TRUE,
  '#password_strength' => TRUE,
);
```

I added 3 options here, one for including the toggle, one for showing the password by default, and one for including the password strength. All of these options should automatically adjust the markup or add JS through a `#process` callback on the password element.

**Comment by serundeputy** [comment]
This is travis testing; it will need some code clean up, but I believe it is close to hitting the mark.  @quicksketch let me know if there is more to do.

**Comment by quicksketch** [comment]
Hey @serundeputy, to clarify the approach, we need a few changes to the current PR:

- The "password_confirm" element should stick around for compatibility. Though we may convert existing forms from using password_confirm to the new enhanced "password" element that includes the strength checker and show/hide password option.
- Right now it looks like the show/hide ability is *always* present. It should be able to be enabled/disabled through FormAPI as described in the comment 2 above this one. To pass these values to the JavaScript, we should use `data-` attributes on the password element, then check these values in the JavaScript using `$('.selector').data('passwordToggle')` (or passwordShown or passwordStrength).
- The existing password_confirm element should internally use the enhanced password field to leverage it's password strength meter, but it still needs specialized JS for providing the "match" checking.

It's exciting to see this coming along! I'd like to see this in a sooner release rather than the nebulous 2.x release, so if we can take this approach we'd be able to see it in a minor 1.x update. Thanks!

**Comment by serundeputy** [comment]
Thanks @quicksketch ;

I will begin on the 1.x approach asap.

**Comment by quicksketch** [comment]
Added the UX "tag" to the title.

**Comment by quicksketch** [comment]
It doesn't look like we'll have time for this in 1.1.0, due next week. This isn't a particular priority, but if it gets completed we can get it into any point release.

**Comment by Dinornis** [comment]
Does this need a new PR?

**Comment by bd0bd** [comment]
Yes, please lets remove confirmation field and add show/hide option.

**Comment by quicksketch** [comment]
I filed a new PR for this at https://github.com/backdrop/backdrop/pull/2129.

**Comment by quicksketch** [comment]
Here are the details of the implementation:

- Password strength moved to the normal "password" element. Can be enabled with `$element['#password_strength'] = TRUE`.
- Password toggle added to the normal "password" element. Can be enabled with `$element['#password_toggle'] = TRUE`.
- Password toggle can be made on by default by setting `$element['#password_shown'] = TRUE`.
- All places where password_confirm had previously been used has been replaced by a normal password field with the toggle.
- All the new properties default to FALSE, so they must be explicitly enabled to use the new password toggle ability.
- As with all new JavaScript, we're trying to reduce use of `Backdrop.settings` and use `data-` attributes on the elements. So this enables the new capabilities through `data-password-strength`, `data-password-toggle`, `data-password-shown`, and `data-password-confirm`.

Here is the field in action on the user edit form:

![image](https://user-images.githubusercontent.com/100206/38745823-91267230-3efa-11e8-9ccc-6ea6faacc462.png)

And on the installer:

![image](https://user-images.githubusercontent.com/100206/38745931-e481823a-3efa-11e8-928a-178549ea5dd0.png)

All tests have now been updated. We're no longer using `password_confirm` anywhere visible in core, but I moved the current tests for it into the example `user_form_test.module` to validate it still works as before.

**Comment by serundeputy** [comment]
@quicksketch i've filed a PR against your PR; https://github.com/quicksketch/backdrop/pull/5/files#diff-4ad1c261e20bfda2a28f08d04fd746deR76 to prevent a js error from being thrown when the password field is toggled to `password-shown`.

https://github.com/quicksketch/backdrop/pull/5/files#diff-4ad1c261e20bfda2a28f08d04fd746deR76

**Comment by quicksketch** [comment]
Thanks, I implemented the firing of the form-submit differently so that the warning should no longer be thrown.

**Comment by klonos** [comment]
A couple of comments:

1. I believe that until this (having a show/hide toggle instead of an additional password confirm field) becomes a widely-used pattern, we should default to hidden password by default *everywhere* (and show the "show password" toggle). Trying to put myself in the shoes of a first-time user as well as a seasoned one, I think that my first reaction would be that there's something wrong when one password is hidden behind dots/stars while the other is available in plain sight. My 2c anyway.

2. Now that the new password thingy is a single field, I think that it makes more sense then ever to change its weight in the user account edit form so that it comes right after the "Current password" field, and also move the email field right after the username field. So the new order should be:

Username
E-mail address
Current password
New password

3. The description for the "Current password" field is "Required if you want to change the E-mail address or Password below.", which got me thinking why we have it visible all the time in that form, if its sole purpose is to be used only for a specific task (changing the password/email)?

I propose we do the following:

- Hide the current/new password fields from that form (using #states).
- Add a "Change password" link/button in the form.
- If the value of the email field is changed, or the "Change password" link/button is clicked, then we show the password field(s) and require it/them in order for the form to be submitted.

...alternatively, we could be rendering the email field in a disabled state, in which case the "Change email" button/link would present the current password field (in a modal?) that would "unlock" the email field.

Please let me know what you think. Does any of these tasks seem like something that could/should be done as part of this ticket?

**Comment by serundeputy** [comment]
Looks good works good; thanks @quicksketch I've merged into `1.x` will ship with `1.10.0`.

@klonos 

> I believe that until this (having a show/hide toggle instead of an additional password confirm field) becomes a widely-used pattern, we should default to hidden password by default everywhere (and show the "show password" toggle). Trying to put myself in the shoes of a first-time user as well as a seasoned one, I think that my first reaction would be that there's something wrong when one password is hidden behind dots/stars while the other is available in plain sight. My 2c anyway.

this is happening with this PR; all PW fields are defaulting to * and have a Show toggle

for your points 2 and 3 I think open up follow up issues.

**Comment by olafgrabienski** [comment]
@serundeputy In the first screenshot of https://github.com/backdrop/backdrop-issues/issues/297#issuecomment-381194108 the "New password" isn't hidden. @klonos Maybe because it had been toggled manually before the screenshot was taken.

**Comment by serundeputy** [comment]
@olafgrabienski must have been toggled; here is a screenie of `/user` fresh hit:
<img width="1666" alt="screen shot 2018-04-19 at 6 25 40 pm" src="https://user-images.githubusercontent.com/6763671/39021541-2a3e0902-43ff-11e8-9957-ca415c43034f.png">
