### ISSUE TITLE
Account Emails for Upgraded Drupal 7 sites contain \n characters instead of line breaks.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2971]
## Describe your issue or idea

When a site has been upgraded from Drupal 7, the email messages get converted into config files, and the line breaks that were stored in the database as \n end up entered into the config files as the characters \n.

### Steps to reproduce (if reporting a bug)

* Upgrade from Drupal 7
* View or edit the Account emails at admin/config/people/emails

### Actual behavior (if reporting a bug)

Many instances of \n are present in the messages.

### Expected behavior (if reporting a bug)

the \n should be line breaks instead.

PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2109

**Comment by jenlampton** [comment]
Here's the update hook I've been using in my upgrades, in case anyone else needs it before I have a PR ready:
```php
/**
 * Implements hook_update_N(). Fixes system email linebreaks.
 */
function iw_update_update_1011() {
  // Migrate variables to config.
  $config = config('user.mail');
  $fixed_mail = str_replace('\n', "\n", $config->get('register_admin_created_body'));
  $config->set('register_admin_created_body', $fixed_mail);
  $fixed_mail = str_replace('\n', "\n", $config->get('register_pending_approval_body'));
  $config->set('register_pending_approval_body', $fixed_mail);
  $fixed_mail = str_replace('\n', "\n", $config->get('register_no_approval_required_body'));
  $config->set('register_no_approval_required_body', $fixed_mail);
  $fixed_mail = str_replace('\n', "\n", $config->get('password_reset_body'));
  $config->set('password_reset_body', $fixed_mail);
  $fixed_mail = str_replace('\n', "\n", $config->get('status_activated_body'));
  $config->set('status_activated_body', $fixed_mail);
  $fixed_mail = str_replace('\n', "\n", $config->get('status_blocked_body'));
  $config->set('status_blocked_body', $fixed_mail);
  $fixed_mail = str_replace('\n', "\n", $config->get('cancel_confirm_body'));
  $config->set('cancel_confirm_body', $fixed_mail);
  $fixed_mail = str_replace('\n', "\n", $config->get('status_canceled_body'));
  $config->set('status_canceled_body', $fixed_mail);
  $config->save();
}
```

**Comment by quicksketch** [comment]
The PR looks great! Well written and looks to do the job. There was a stray `dpm()` in there though that was causing test failures. I've removed the call and set tests to re-running.

**Comment by olafgrabienski** [comment]
Has the fix already been committed? (If so, "Status - fixed" is missing.)

**Comment by jenlampton** [comment]
Thanks @olafgrabienski !  Feel free to change these labels yourself in the future, you are usually right about these kinds of things :)
