### ISSUE TITLE
drupal_strtoupper() should be converted to backdrop_strtoupper()

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#2972]
> Error: Call to undefined function drupal_strtoupper() in image_hex2rgba() (line 473 of /home/user/webroot/core/includes/image.inc).

**Comment by opi** [comment]
reviewed, nice catch !

Even the documentation said so, see https://api.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/function/drupal_strtoupper/1
We (i.e. a script) should look after every `drupal_` function listed [here](https://api.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/1) to see if there are any calls left.

**Comment by quicksketch** [comment]
Thanks @laryn and @opi! Merged https://github.com/backdrop/backdrop/pull/2095 into 1.x and 1.9.x!
