### ISSUE TITLE
[UX] Instant-filter should search project grouping names

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2973]
## Describe your issue or idea
On the modules page, searching by package should return results.

### Steps to reproduce 

* navigate to modules page
* Search for `Categorization`

### Actual behavior (if reporting a bug)

* see everything on the page disappear

### Expected behavior (if reporting a bug)

* see everything in the fieldset for `Categorization`

---

PR by @jenlampton https://github.com/backdrop/backdrop/pull/2128

**Comment by laryn** [comment]
It's not working for me on the test/demo server. All the modules still disappear when I type "Categorization".

**Comment by laryn** [comment]
This one looks good to me. Nice job!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2128 into 1.x for 1.10. Thanks!

**Comment by opi** [comment]
The re-works of https://github.com/backdrop/backdrop/pull/2128 seems to have leave some variable and function name mismatch:
- `showPackageFieldset` function [removed](https://github.com/backdrop/backdrop/pull/2128#pullrequestreview-113758503).
- `$fieldset` renamed to `$fieldsets`, one occurrence missed.

Result is I have some JS error in my console : `Uncaught ReferenceError: $fieldset is not defined`, and some empty fieldset ![capture d ecran de 2018-04-23 15-22-30](https://user-images.githubusercontent.com/159548/39129210-36646cf4-470a-11e8-940b-86d0739dac6e.png)


Here is a PR with, I hope, a cleanup: https://github.com/backdrop/backdrop/pull/2144

**Comment by quicksketch** [comment]
Thank you @opi! The removal of `showPackageFieldset` was intentional, now we just don't hide the module if its fieldset title matches, so we eliminated an extra round of show/hide calls. You're spot on the fieldset problem though, I've merged your PR. Thanks!!

**Comment by opi** [comment]
> The removal of showPackageFieldset was intentional

I know, thus we have to remove the call to this function ;)

Thanks for the quick merge
