### ISSUE TITLE
[META] [UX] Make sure Basis works in RTL locales.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2975]
...similar to #1719, but for the Basis theme.

While playing around with some UI enhancements, I realized a few places where our RTL does not work as it should. These are quite a few places and I'm sure more will come up, so this is the place to keep track of it.

List with separate issues coming up...

- [x] #3405 | [UX] Fix RTL admin_bar style
- [x] #3421 | [UX] Fix RTL Autocomplete style

**Comment by klonos** [comment]
...not sure if separate issues are required. Perhaps just separate PRs under this issue here.

**Comment by klonos** [comment]
...let fix these few things for starters:

![screen shot 2018-02-10 at 6 43 31 am](https://user-images.githubusercontent.com/2423362/36046845-6ba1c2c8-0e2e-11e8-9379-c0a339be998e.png)

So, I think that we should be switching the direction of the site identity block, the main nav menu, and the header menu.

Also, the primary tabs and the breadcrumb.

![screen shot 2018-02-10 at 6 42 58 am](https://user-images.githubusercontent.com/2423362/36046847-6e1df350-0e2e-11e8-9c2f-2f46639c265f.png)

In the comment section, we should be making sure that the expand/collapse arrow in the formatting options section is in the right place (pun intended :) ), and also that the spacing of the "Cancel" link is correct.

**Comment by klonos** [comment]
...this is more of a generic question about RTL menus (people from countries with RTL locales, please chime in): do we also need to change the order of the menus? ...if yes, then that might prove tricky, because the top-level menu items are listed horizontally, while the children items are listed vertically. At the very least, we should make sure that child menu items after the 2nd level are expanding towards the proper direction (left), otherwise we might end up with menu items outside the view port. I have checked, and it seems that [smartmenus](https://www.smartmenus.org/) does not properly handle RTL. Not sure if we are to fix this upstream or on our theme level (?).

**Comment by shabibalm** [comment]
finish fix (Formatting options)
![formatting-options](https://user-images.githubusercontent.com/45591694/49826700-99ae6680-fd98-11e8-974c-d7743a4d8293.gif)

**Comment by quicksketch** [comment]
I think with the many RTL issues filed over the past 18 months we've been doing a good job of addressing RTL issues as they come up. I don't think we need to maintain this meta permanently (I don't think we'd remember to update it anyway). Reopen if you think otherwise.

**Comment by klonos** [comment]
Yeah, I agree. We have the `[RTL]` tag, which makes it easy to track these issues.
