### ISSUE TITLE
Backdrop 1.9.2

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#2984]
Backdrop 1.9.2 Release
==================================

Drupal 7.57 was released today, which includes 4 security fixes for Drupal 7. We'll need to push out a corresponding release for Backdrop.

## Pre-release tasks

- [x] Merge commits @quicksketch, @serundeputy
- [x] Create a new bugfix release to follow the current version
- [x] Move all unfinished issues to the next bugfix release
- [x] Draft Release notes @serundeputy, @quicksketch, @jenlampton
- [x] Draft Security Advisory (if necessary) @serundeputy, @quicksketch

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch, @serundeputy
- [x] Tag for release, push to GitHub @quicksketch, @serundeputy
- [x] Revert version number back @quicksketch, @serundeputy
- [x] Create release notes on GitHub @serundeputy, @quicksketch, @jenlampton
- [x] Update the front page download link on b.org.
- [x] Tweet that a new release is out @quicksketch, @jenlampton, @thejimbirch
- If this is a security release:
  - [x] Publish Security Advisory on b.org
  - [x] Mark the release node on b.org as a security release (tick the checkbox)

## Post-release tasks (asap)

- [ ] Update the docker image to the latest @serundeputy
- [x] Push the bug-fix release to the Pantheon [repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch, @serundeputy
- [x] Push the bug-fix release to the Platform.sh [repository](https://github.com/platformsh/platformsh-example-backdrop) @quicksketch, @serundeputy
- [x] Update the Wikipedia articles to at least show the proper version number and date for latest release @jenlampton
  - [ ] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [ ] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by jenlampton** [comment]
@serundeputy  should we remove the docker task from these todo lists?

**Comment by serundeputy** [comment]
@jenlampton re: docker; We can either remove or get a new maintainer.

we've released `1.9.3` closing this.
