### ISSUE TITLE
Pantheon easy install process broken

### ISSUE THREAD

**Issue by Steve-A-Orr** [backdrop/backdrop-issues#2986]
## Describe your issue or idea
I've used the _easy Pantheon install_ method to start up a new site using Pantheon, but even after moving the development mode to "SFTP" and accomplishing initial install steps, it throws an error.

### Steps to reproduce (if reporting a bug)
1. Visit this page:  https://pantheon.io/blog/backdrop-cms-10-available-pantheon
2. Click the "you can try Backdrop on Pantheon right now" link going to:  https://dashboard.pantheon.io/products/backdrop/spinup
3. ...wait for Pantheon to set up environment...
4. Click set-up CMS button.
5. Set "development mode" to SFTP in Pantheon dashboard UI.
6. Click "Visit Development Site" button in Pantheon dashboard UI.
7. Choose language and configure site as normal (site information, primary user account, etc).

### Actual behavior (if reporting a bug)
Efforts result in the following error:
```
Fatal error: Call to undefined function field_attach_load() in /srv/bindings/03fff8d9f893431c925990df7c4c570b/code/core/modules/entity/entity.controller.inc on line 333
```

### Expected behavior (if reporting a bug)
I would expect no error and an opportunity to see the new site, like other Drupal installation processes.

### Relevant version/system information (if applicable)
I performed this a couple of times in the past two months, with similar results, but most recently on 2018-02-22 so I'm guessing it is the latest Pantheon Upstream. (Maybe 1.9.2?)

**Comment by jenlampton** [comment]
Thanks @Steve-A-Orr, we've noticed this problem frequently recently too. If you use [the link on our home page](https://dashboard.pantheon.io/sites/create?upstream_id=bf703821-4c18-45a1-88b8-3d9ec302273d) instead, we find that one works consistently.

I've asked @populist to update the blog post to use that link too, hopefully that will save the next people from the same issue you're encountering :)

**Comment by Steve-A-Orr** [comment]
Ah, that is unfortunate. When I first tried to get them (Pantheon) to troubleshoot the issue, they came back with something like "The upstream file is managed by BackdropCMS folks, so ask them."

It'd be nice to alter/wipe out these links in documentation, so no one makes an attempt and blames Backdrop.

**Comment by jenlampton** [comment]
> When I first tried to get them (Pantheon) to troubleshoot the issue, they came back with something like "The upstream file is managed by BackdropCMS folks, so ask them."

Yeah, I got that response too. Unfortunately the problem doesn't have anything to do with the upstream (you can tell because the other link works just fine). It's something to do with the way they are redirecting to the link that works...  don't ask me how that's possible...  but here we are :)

**Comment by populist** [comment]
As a followup, the link at https://pantheon.io/blog/backdrop-cms-10-available-pantheon has been updated to the new upstream spinup pattern.

**Comment by jenlampton** [comment]
Fantastic, thanks @populist! :)
