### ISSUE TITLE
Add template for redirecting to https in .htaccess so developers know the best practice

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#2989]
Currently .htaccess has a template for redirecting to www or to without the www. It could be useful to add a template for redirecting to https so people using Apache know the best way to always use https.

In this forum post there are a few different approaches it seems: https://forum.backdropcms.org/forum-topic/how-install-ssl

**Comment by opi** [comment]
Duplicate of https://github.com/backdrop/backdrop-issues/issues/2694
