### ISSUE TITLE
[UX] Missing tabs on Manage display sub-pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2998]
## Describe your issue or idea

We mentioned this in https://github.com/backdrop/backdrop-issues/issues/2614 (which is marked fixed) but the tabs are still missing.  Opening a new issue so we can focus on the tabs:

**Main "Manage display" screen with title/tabs:**
<img width="1204" alt="screen shot 2017-04-03 at 2 35 42 pm" src="https://cloud.githubusercontent.com/assets/871421/24627621/25203cf2-187b-11e7-8db1-4d62b8d0a0ca.png">

**After clicking "Manage display" on a view mode:**
<img width="1211" alt="screen shot 2017-04-03 at 2 36 00 pm" src="https://cloud.githubusercontent.com/assets/871421/24627651/412fe564-187b-11e7-9a88-d208248e8c35.png">

**Comment by laryn** [comment]
I feel like I've seen this before. :) 

https://github.com/backdrop/backdrop-issues/issues/2614
https://github.com/backdrop/backdrop-issues/issues/2681

**Comment by jenlampton** [comment]
I *swear* searched!!!!

**Comment by opi** [comment]
So now we have 3 closed issues for something that really looks like a bug to me... Thanks for bringing it back @jenlampton, I have this *missing tabs* feeling every time I play with displays

**Comment by opi** [comment]
Oops, tired  phone reading, #2681 is open #sorry
