### ISSUE TITLE
[UX] Don't say 'edit' when we mean 'configure' - date formats edition

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#2999]
Looks like we missed a spot: 
<img width="1211" alt="screen shot 2018-03-14 at 12 50 27 am" src="https://user-images.githubusercontent.com/397895/37389459-b939dde8-2721-11e8-8bc9-528205fe4f70.png">

Adding milestone candidate tag for 1.11.4

---
PR: https://github.com/backdrop/backdrop/pull/2466

**Comment by opi** [comment]
related issue https://github.com/backdrop/backdrop-issues/issues/2850

**Comment by jenlampton** [comment]
removing milestone, but [UX] issues can go into any bug-fix release.

**Comment by klonos** [comment]
looks like the PR includes far more changes than intended (like from the node preview issues)

**Comment by klonos** [comment]
...I agree with the milestone candidate. If we can make it 😄 ...otherwise 1.12.3

**Comment by jenlampton** [comment]
The code change here is silly simple, I think we can make it :)

**Comment by klonos** [comment]
RTBC 👍 😄

**Comment by quicksketch** [comment]
Great, simple enough. Perhaps we should follow-up to update the URLs with `/configure` at some point, but we'd probably need https://github.com/backdrop/backdrop-issues/issues/2833 to handle the wildcards.

Merged into 1.x and 1.12.x. Thanks!

**Comment by klonos** [comment]
> ..we should follow-up to update the URLs with `/configure` at some point, but we'd probably need #2833 to handle the wildcards.

#3536 😉
