### ISSUE TITLE
Changing the site's timezone

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3000]
For those who don't yet know, I've just [moved](https://panda.id.au/posts/moving-estonia) from Australia to Estonia. I'm now trying to update my websites to reflect the new timezone.

Previously, my blog showed the date & time I posted an article (e.g. 19th Dec at 1:16pm). After I change the site's default timezone, all existing articles get updated to show the new date/time (e.g. 19th Dec at 4:16am).

Now call me pedantic, but I'd like the date/time of an article to reflect the date/time it was actually posted (e.g. 1:16pm, not 4:16am). I guess this means storing the timezone with the article's timestamp...?

I remember also having this issue with Drupal back in 2009 when I went to New Zealand on holidays and blogged from there. I had to manually change each blog entry's time/date to match NZ's timezone, otherwise it looked like I was posting at weird hours of the day.

I understand that different users can have different timezones, so they'll see weird times if they're quite different from the site's default timezone, but I'm referring more to a simple site with a single timezone, where the owner has either moved timezones or travelled overseas for a while, and wants times to match where/when they posted.

This is open for discussion - I want to get an idea of what others think. Am I being silly, or is there a use-case for something like storing a timezone for each article such that future default timezone changes don't affect them?
Thoughts?

**Comment by quicksketch** [comment]
> or is there a use-case for something like storing a timezone for each article such that future default timezone changes don't affect them?

> I guess this means storing the timezone with the article's timestamp...?

I don't know of a way to do this immediately. But you've put your finger on it here. The "created" column in the database is an integer (a timestamp). Timestamps do not take into account timezones, they are always UTC, which makes for a simple and consistent exact point in time.

However, the Date module fields use MySQL DateTime fields, which DO include timezone data. This means that you could in theory store a date always in the local timezone of wherever the user is (including the time zone itself). Then when displaying that date, you could format it in a way that respected the local timezone and did not adjust it to match the site-wide timezone.

Or, alternatively you could add a separate database column or field for timezone and then output the existing timestamp in the date that matches that timezone.

Either solution the key would likely be to implement hook_preprocess_node() in your theme and set the `$variables['date']` variable using the correct timezone (whether that came from a date field or a separate field/column). The `format_date()` function can be told a particular timezone, but it uses the user or site timezone by default.

**Comment by BWPanda** [comment]
Wrote a module that does this: [Authored Timezone](https://github.com/backdrop-contrib/authored_timezone).
