### ISSUE TITLE
Requirements check frequently leads to missing table exception

### ISSUE THREAD

**Issue by jhodgdon-drp** [backdrop/backdrop-issues#3007]
## Describe your issue or idea

The Admin Bar module frequently does a requirements check, in order to make its little alert icon. If you are an admin and open multiple windows on the same site at about the same time, and the cache has been cleared recently, this can lead to getting a PDO exception in some of the newly opened windows. The error message is something like this:

PDOException: SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'DATABASE_NAME.backdrop_utf8mb4_test': DROP TABLE {backdrop_utf8mb4_test}; Array ( ) in _system_check_db_utf8mb4_requirements() (line 632 of /DOCUMENT_ROOT/core/modules/system/system.install).

I believe this is happening because:
- admin_bar_output() gets called, and calls admin_bar_links_alert(), if it doesn't find the admin bar in the cache.
- admin_bar_links_alert() calls system_get_requirements()
- system_get_requirements() invokes hook_requirements() on all modules.
- The system module implementation of this hook, system_requirements(), makes a call to _system_check_db_utf8mb4_requirements()
- Assuming you're using MySQL database, this ends up calling DatabaseConnection_mysql::utf8mb4IsSupported(), which creates and then drops this temporary database table.

### Steps to reproduce (if reporting a bug)

This is not exactly reliable, but if you try it a few times you'll most likely see the error:

a) Do something, such as saving configuration, that clears the cache.
b) Open several windows to admin pages, such as a node/add/* page.

### Actual behavior (if reporting a bug)

In one of the open windows, instead of the page you expect, you'll get a PDO exception message.

### Expected behavior (if reporting a bug)

All of the windows should work.

### Relevant version/system information (if applicable)
Looks like we're using Backdrop version 1.9.2 here.

### How to fix this
Should actually be an easy fix. Here's the code from the connection class:
````
  // Ensure that the MySQL server supports large prefixes and utf8mb4.
  try {
    $this->query("DROP TABLE IF EXISTS {backdrop_utf8mb4_test}");
    $this->query("CREATE TABLE {backdrop_utf8mb4_test} (id VARCHAR(255), PRIMARY KEY(id(255))) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT=DYNAMIC ENGINE=INNODB");
  }
  catch (Exception $e) {
    return FALSE;
  }
  $this->query("DROP TABLE {backdrop_utf8mb4_test}");
````
That last DROP TABLE query could be changed to DROP TABLE IF EXISTS, and the problem should not occur.

**Comment by quicksketch** [comment]
Thanks @jhodgdon-drp! I filed a PR at https://github.com/backdrop/backdrop/pull/2131 that makes your suggested change.

**Comment by serundeputy** [comment]
I couldn't replicate the error, but the change looks like a good one to me. Marking RTBC.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2131 has been merged into 1.x and 1.9.x. Thanks @jhodgdon-drp and @serundeputy!
