### ISSUE TITLE
Backdrop 1.9.3, 1.8.3, 1.7.4 Release

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3009]
Backdrop 1.9.3, 1.8.3, 1.7.4
==================================

This is for the previously announced security update that will be coming out today. See https://backdropcms.org/security/psa-2018-001

As stated in the announcement, we'll be doing multiple releases. We'll cover the current version and back two releases to 1.7.x to obtain maximum coverage.

## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Create a new bugfix release to follow the current version
- [x] Move all unfinished issues to the next bugfix release
- [x] Draft Release notes @jenlampton
- [x] Draft Security Advisory (if necessary) @jenlampton

## Release tasks

- [x] Update bootstrap.inc with version number @quicksketch, 
- [x] Tag for release, push to GitHub @quicksketch,
- [x] Revert version number back @quicksketch,
- [x] Create release notes on GitHub @jenlampton
- [x] Update the front page download link on b.org. @jenlampton
- [x] Tweet that a new release is out  @jenlampton
- If this is a security release:
  - [x] Publish Security Advisory on b.org  @jenlampton
  - [x] Mark the release node on b.org as a security release (tick the checkbox)  @jenlampton

## Post-release tasks (asap)

- [x] Push the bug-fix release to the Pantheon [repository](https://github.com/backdrop-ops/backdrop-pantheon) @quicksketch
- [x] Push the bug-fix release to the Platform.sh [repository](https://github.com/platformsh/platformsh-example-backdrop) @serundeputy
- [x] Update the docker image to the latest ???, @serundeputy
- [x] Update the Wikipedia articles (version number and date) @klonos
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by quicksketch** [comment]
All releases are now out:

https://github.com/backdrop/backdrop/releases/tag/1.9.3
https://github.com/backdrop/backdrop/releases/tag/1.8.3
https://github.com/backdrop/backdrop/releases/tag/1.7.4

**Comment by jenlampton** [comment]
Tweeted: https://twitter.com/backdropcms/status/979084195359150080

**Comment by findlabnet** [comment]
Well done! Thanks to all!

**Comment by serundeputy** [comment]
Updated p.sh Backdrop example: https://github.com/platformsh/platformsh-example-backdrop

**Comment by serundeputy** [comment]
Backdrop Docker image PR: https://github.com/docker-library/official-images/pull/4185

**Comment by jenlampton** [comment]
Now who's on 🔥 ?!?

**Comment by klonos** [comment]
Updated the Wikipedia pages 👍

**Comment by jenlampton** [comment]
Nice work team!  Closing this issue :)
