### ISSUE TITLE
Empty elements being inserted in head

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3010]
This is happening when I use Flexslider Fields and have a flexslider on a page, but a simple fix in core takes care of it.

A part of empty elements are inserted into the `<head>` area of the code:
![screen shot 2018-03-29 at 10 23 16 am](https://user-images.githubusercontent.com/871421/38097639-83559b6a-333b-11e8-8051-f92efce58971.jpg)

The watchdog shows: 
`Notice: Undefined index: #tag in theme_head_tag() (line 2449 of /path/to/backdrop_html/core/includes/theme.inc).`

PR: https://github.com/backdrop/backdrop/pull/2116

**Comment by opi** [comment]
From [my review](https://github.com/backdrop/backdrop/pull/2116#pullrequestreview-109472476)

> I see 2 different ways to fix this :
> - add a check at the beginning of the theme function to return an empty string if #tag is not defined.
> - The notice is already displayed + this parameter is required in documentation + an empty html element is not that bad (even if dirty) = the issue belong to the contrib module ;)

**Comment by quicksketch** [comment]
I think I have to agree with @opi here. This is a bug in Flexslider Fields, that it needs to provide a `#tag` property. The documentation already states it as being required: https://api.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_head_tag/1

A PHP notice will be thrown if it doesn't exist, which also indicates something isn't right.

**Comment by laryn** [comment]
@quicksketch I did a quick `grep` in the Flexslider module and I don't think it calls that function at all. But I will move this over to the Flexslider queue for now.
