### ISSUE TITLE
Remove the taxonomy_vocabulary table from taxonomy_schema()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3012]
## Describe your issue or idea

As raied by laz [in the forum](https://forum.backdropcms.org/forum-topic/where-does-backdrop-store-vocabularies) vocabularies are stored in configuration, not in the database. Yet when you install Backdrop (or enable the taxonomy module, if you are using the minimal profile) the `taxonomy_vocabulary` database table is still created, even though it's never used.

For those upgrading from Drupal, the `taxonomy_vocabulary` database table is removed in [taxonomy_update_1002()](https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.install/function/taxonomy_update_1002/1), so I suspect it's an oversight that it's added for new Backdrop sites.

### Steps to reproduce (if reporting a bug)

* Install backdrop
* Inspect the database for a `taxonomy_vocabulary` table

### Proposed fix

* Delete `$schema['taxonomy_vocabulary']` from [taxonomy_schema()](https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.install/function/taxonomy_schema/1).

**Comment by sethlbrown** [comment]
Steps I took:
1. Deleted `$schema['taxonomy_vocabulary']` from taxonomy_schema()
2. Reinstall Backdrop
3. Manually test adding vocabulary, terms with relationships and hierarchy between terms
4. Verify the data is properly written to the taxonomy_ tables
5. Enable test module
6. Run the taxonomy tests

![test result backdrop test 2018-08-05 11-10-45](https://user-images.githubusercontent.com/852739/43688152-dbf6760c-98a0-11e8-9222-b05faa7854d9.jpg)

**Comment by quicksketch** [comment]
PR looks great but we need an update hook to remove this table for sites that already have this table, which would happen for new Backdrop installs. Users upgrading from D7 would have had this table dropped properly because of the existing update hooks.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2266 into 1.x and 1.10.x. Thanks @sethlbrown!
