### ISSUE TITLE
[UX] Views Pager fields should be type 'number' instead of type 'textfield'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3015]
## Describe your issue or idea

In the views pager settings both the **Number of items** field and the **Offset** field should be number fields instead of text. 

<img width="819" alt="screen shot 2018-03-30 at 2 37 39 pm" src="https://user-images.githubusercontent.com/397895/38154642-f69e6b32-3427-11e8-9d2e-52f8997fa406.png">

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2275 into 1.x and 1.10.x. Thanks @sethlbrown for the PR! And kudos to @BWPanda and @herbdool for providing reviews!
