### ISSUE TITLE
Empty date field generates warnings at node editing on PHP 7.1

### ISSUE THREAD

**Issue by kleomash** [backdrop/backdrop-issues#3017]
I have a field with type 'date'. When I open a node with this field empty for editing I get warnings:

> Warning: Illegal string offset 'value' in date_combo_element_process() (line 1422 of htdocs/core/modules/date/date.elements.inc).
> Warning: Cannot assign an empty string to a string offset in date_combo_element_process() (line 1422 of htdocs/core/modules/date/date.elements.inc).
> Warning: Illegal string offset 'value' in date_local_date() (line 830 of htdocs/core/modules/date/date.elements.inc).
> Notice: Uninitialized string offset: 0 in date_local_date() (line 830 of htdocs/core/modules/date/date.elements.inc).
> Warning: Illegal string offset 'value' in date_combo_element_process() (line 1425 of htdocs/core/modules/date/date.elements.inc).
> Warning: Cannot assign an empty string to a string offset in date_combo_element_process() (line 1425 of htdocs/core/modules/date/date.elements.inc).

I suppose something is wrong. What's the matter?

I use backdropcms 1.9.2 

-----
PR: https://github.com/backdrop/backdrop/pull/2121

**Comment by olafgrabienski** [comment]
Hi @kleomash - I wasn't able to reproduce the error on a Backdrop 1.9.3 site. To test it, I created a content type called "Event" with a Date field and the Pop-up calender widget, added an Event without filling in a date, and saved the Event. Then I tried to edit the Event, which was possible, and I didn't see any errors.

Can you post information about which type of Date field you're using (Date, Date ISO format, Date Unix timestamp), and how the field is configured?

**Comment by kleomash** [comment]
Hi, @olafgrabienski !

I've reproduced it not only with my content types but also with new empty content type.

Field type: 'date', not 'Date ISO format' and not 'Date Unix timestamp'. No configuration changes from default. Which settings are interesting? I could test with clean 1.9.3 install.

**Comment by opi** [comment]
@kleomash what is your PHP version ?

**Comment by olafgrabienski** [comment]
@kleomash I've no particular idea which configuration could be of interest. Was just asking me if there is something special in configuration which would explain the issue.

**Comment by kleomash** [comment]
The problem is in php version. PHP-5.6 works fine. PHP-7.1 make warnings.

**Comment by serundeputy** [comment]
I can confirm warnings using `1.x` and php `7.1`

<img width="1644" alt="screen shot 2018-04-04 at 1 58 29 pm" src="https://user-images.githubusercontent.com/6763671/38325221-62efca10-3810-11e8-9679-802214d84519.png">

```
Warning: Cannot assign an empty string to a string offset in date_combo_element_process() (line 1425 of /app/core/modules/date/date.elements.inc).
```
STR:
  * Added a field type `Date` to `post` content type
  * visited a `post` node
  * clicked edit
  * saved w/out providing a value for the `Date` field

**Comment by kleomash** [comment]
I've tested with different php versions for now:
5.6.34 - ok
7.0.28 - ok
7.1.13 - warnings

Field configuration attached (txt extention added for github upload)

[field.field.field_conf_request_dates.json.txt](https://github.com/backdrop/backdrop-issues/files/1877286/field.field.field_conf_request_dates.json.txt)
[field.instance.node.conf_event.field_conf_request_dates.json.txt](https://github.com/backdrop/backdrop-issues/files/1877287/field.instance.node.conf_event.field_conf_request_dates.json.txt)

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/2121

In PHP 7.2 it will not auto create an array given an empty index.

> The empty index operator is not supported for strings anymore 

http://php.net/manual/en/migration71.incompatible.php

this PR adds in checks for the case that a `default_date` is not set.

**Comment by quicksketch** [comment]
Thanks! I tweaked the PR slightly, retested and then merged https://github.com/backdrop/backdrop/pull/2121 into 1.x and 1.9.x.

**Comment by serundeputy** [comment]
Thanks @kleomash and @quicksketch closing.
