### ISSUE TITLE
hook_ckeditor_plugins documentation

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3018]
The documentation for the [hook_ckeditor_plugins() function](https://api.backdropcms.org/api/backdrop/core!modules!ckeditor!ckeditor.api.php/function/hook_ckeditor_plugins/1) has an issue in that a code block is placed in the wrong spot (see PR for details).

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/2118

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2118 into 1.x and 1.9.x.
