### ISSUE TITLE
Support install profiles with no version number

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3019]
I'm using a custom install profile that doesn't have a version number. When I go to admin/reports/status it says:

> Install profile: PackWeb (pw_profile-)

The hyphen at the end is meant to separate the install profile name from it's version, but since there's no version number you just get that.

It's a very minor issue, but can we make it not add the hyphen if there's no version number?
For reference, this comes from [line 35 of system.install](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.install#L35).

**Comment by BWPanda** [comment]
Made a PR for this: https://github.com/backdrop/backdrop/pull/2784

**Comment by klonos** [comment]
Hey @BWPanda have you released the PackWeb profile somewhere publicly? I would like to test this on my local, and don't have a profile handy 😅

**Comment by BWPanda** [comment]
@klonos https://github.com/PackWeb/pw_profile

**Comment by BWPanda** [comment]
PR updated with @klonos' suggestion.

**Comment by klonos** [comment]
Sorry for taking this long for this small change @BWPanda 😓 ...the code looks good, and I expect it to work as expected, but I'm gonna take a few mins to test it anyway.

**Comment by klonos** [comment]
I tried to test this with https://github.com/PackWeb/pw_profile but getting an error: https://github.com/PackWeb/pw_profile/issues/12

Do we have another installation profile I can use to test this?

**Comment by BWPanda** [comment]
Maybe just make a copy of one of the core profiles, and remove the version number from the info file...?

**Comment by klonos** [comment]
Works 👍 

![image](https://user-images.githubusercontent.com/2423362/109450692-39c53880-7a54-11eb-912f-d1c741876d5f.png)

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2784 into 1.x and 1.18.x.
