### ISSUE TITLE
[DX] Date and Link modules still uses $vars instead of $variables

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3026]
## Describe your issue or idea

It looks like our link module theme functions sill use the drupal-6 style shorthand `$vars` instead of the longer `$variables` the rest of core uses. We should fix this!

**Comment by opi** [comment]
`git grep '&vars'` told me that the Date module is still using `$vars` too.

    docroot/core/modules/date/date.theme.inc:function template_preprocess_date_views_filter_form(&$vars) {

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Thanks @Plochem for the PR! Looks great and I'm glad to see those abbreviated variables finally replaced. Merged into 1.x and 1.12.x.

**Comment by klonos** [comment]
Just noting that this PR included a change that belongs to https://github.com/backdrop/backdrop-issues/issues/3608
