### ISSUE TITLE
Adding a "contextual link" field to a view displays the label

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3030]
## Describe your issue or idea

I've not used it before but had a situation where I thought it would be useful to add a contextual link to a View that displays fields. Surprise! It is easy to add a contextual link field in a View. But for some reason the label keeps displaying.

### Steps to reproduce (if reporting a bug)

 - Create a view that displays fields of a content type.
 - Add an "Edit link" field and exclude it from display.
 - Add a "Contextual link" field and check the box to include the "Edit link" you've just added prior.

### Actual behavior (if reporting a bug)

 - A "Contextual links: " label displays on the View output.

### Expected behavior (if reporting a bug)

- No label should display. The fields are already hidden from the admin UI in Views ([see here](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/handlers/views_handler_field_contextual_links.inc#L17-L21)) but for some reason the label is displaying on the front end.

PR: https://github.com/backdrop/backdrop/pull/2223 (by @laryn)

**Comment by laryn** [comment]
I haven't quite been able to figure out how to ensure that the label is set to be empty, but as a workaround for the moment, I have commented out these lines:
https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/handlers/views_handler_field_contextual_links.inc#L18-L20

This allowed me to uncheck the "Create a label" box.

**Comment by olafgrabienski** [comment]
I was able to reproduce this bug :-/

Even worse, the *Contextual Links* field and label HTML, in contrast to other fields, has no CSS classes, which makes it difficult to hide the label as a workaround via CSS:

```
<div>
  <span>Contextual Links: </span>
  ...
</div>
```

**Comment by olafgrabienski** [comment]
Still no idea how to fix this (help needed) but here's an workaround:

Preparation (like above):
- Create a view that displays fields of a content type.
- Add an "Edit link" field and exclude it from display.
- Add a "Contextual link" field and check the box to include the "Edit link" you've just added prior.

Workaround:
- Exclude all fields, incl. "Contextual link", from display.
- Add a global field of type `Custom text` (without label) and add the excluded fields via the *Replacement patterns*.

Example of the `Custom text` field

```
<div>[contextual_links]</div>
<h3 class="views-field-title">[title]</h3>
<div class="views-field-body">[body]</div>

**Comment by olafgrabienski** [comment]
The PR works in the sandbox site, cool!

(Test page: http://2223.backdrop.backdrop.qa.backdropcms.org/test-contextual-links)

**Comment by BWPanda** [comment]
Can confirm PR works after re-saving Contextual Filter fields in view.

**Comment by quicksketch** [comment]
Thanks for the PR @laryn and the reviews @BWPanda and @olafgrabienski! I've merged https://github.com/backdrop/backdrop/pull/2223 into 1.x and 1.10.x.
