### ISSUE TITLE
Use new JavaScript to detect timezone

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3032]
## Describe your issue or idea

Modern JavaScript can now detect timezones directly from the browser, rather than just getting the offset from GMT. We should use this increased accuracy method to set the site and user timezones when displaying a timezone element.

~Because we can more accurately detect timezone, we should also then hide the timezone from the installer. Similar to Clean URLs detection: if we can accurately determine it through JavaScript, hide it from the form as a hidden element. Of course if needed, the timezone can always be changed later, and removing the timezone reduces friction in site configuration~

To limit the scope of this issue and get the clear improvement in, we'll just worry about adding the new JavaScript and leave the removal of the timezone for later (if at all).

### Steps to reproduce (if reporting a bug)

- Set your site timezone to an unpopular location that matches a major one. For example, I set my timezone to Phoenix, AZ as it has different daylight savings rules than the rest of the US.
- Install Backdrop, during the installer, note instead of "America/Phoenix", the timezone selected is "America/Los_Angeles" (in the winter) OR "America/Denver" (in the summer). Neither is the correct timezone as those areas have different daylight savings rules than Phoenix.

### Actual behavior (if reporting a bug)

- The wrong timezone is selected

### Expected behavior (if reporting a bug)

- The right timezone, matching my operating system should be selected.
- And we should ultimately remove this field entirely, once we know that the right value is being prepopulated.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2127

**Comment by quicksketch** [comment]
This idea came from this StackOverflow post: https://stackoverflow.com/a/34602679

Browser compatibility is pretty complete: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions#Browser_compatibility

But we can always fallback to the previous method if that approach fails.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/2127.

This PR does both steps at once (sets the timezone correctly and hides the field). You'll need to use the developer tools to verify the right timezone is set, or visit `admin/config/regional/settings` after completing the installer.

I found that if you change the timezone in your operating system, Chrome can sometimes cache the previous location for a while before picking up the change. Double-check it's picking up the right TZ by using this line in the browser JavaScript console:

```
console.log(Intl.DateTimeFormat().resolvedOptions().timeZone)
```

Or even use the "Run Snippet" capability on the aforementioned StackOverflow post: https://stackoverflow.com/a/34602679

**Comment by olafgrabienski** [comment]
The technical improvement sounds nice but I'm not sure if it's good to hide the timezone setting from the installer. Think of a developer who works in a different timezone than the site owner. Sure, the timezone can be changed later, but (1) you have to know that, (2) you have to remember it and (3) you have to look where this setting is. Isn't it easier to just set the correct timezone during installation?

**Comment by olafgrabienski** [comment]
... And in other cases (correct timezone), I find the setting not that disturbing, it acts more as a confirmation than as a setting.

**Comment by klonos** [comment]
...perhaps we could have the result of `date_default_timezone_get` and `resolvedTimezone` bubble up the list as "suggestions" or something.

**Comment by klonos** [comment]
...use something like https://www.devbridge.com/sourcery/components/jquery-autocomplete or https://select2.org

**Comment by jenlampton** [comment]
I've created a new issue "set the timezone from the browser" https://github.com/backdrop/backdrop-issues/issues/3041

**Comment by quicksketch** [comment]
Although I feel that reducing installer friction (however small) is more important than getting a custom timezone, I'll cede on that issue for now. I've descoped changes to the installer in my PR and now it's just a JavaScript-only change. Review ensuring the right timezone is selected would still be appreciated.

PR https://github.com/backdrop/backdrop/pull/2127

**Comment by herbdool** [comment]
@quicksketch I've reviewed and looks great! Got the right timezone--tested with Chromium/Ubuntu.

**Comment by quicksketch** [comment]
Excellent, thanks @herbdool! Considering the low impact of this, and the fallback being used if it fails, let's merge this in for 1.10. Merged https://github.com/backdrop/backdrop/pull/2127.
