### ISSUE TITLE
[UX] layouts: visibility condition label for vocabularies is wrong 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3033]
## Describe your issue or idea

When creating a visibility condition to limit a `taxonomy/term/%` layout to vocabulary, the label refers to the vocabulary as a "Taxonomy term"
<img width="1180" alt="screen shot 2018-04-15 at 12 19 02 pm" src="https://user-images.githubusercontent.com/397895/38782382-7632259c-40a7-11e8-911c-289aed4e6e80.png">

This should be changed to say 'Vocabulary is "Categories"` instead of `Taxonomy term is "Categories"`.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2264

**Comment by klonos** [comment]
While filing the PR for this, I have noticed a few inconsistencies with the rest of the `layout_access` plugins, but I will file follow-ups for fixing those.

**Comment by alexfinnarn** [comment]
I have reviewed this PR and `Taxonomy term is "Tags"` was changed to `Vocabulary is Tags`. The only thing to maybe add back the quotes. "Tags" is italicized, though, which visually sets it apart.

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2264 into 1.x and 1.10.x.
