### ISSUE TITLE
Add ability to supress creation of automatic Body field on new content types

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3035]
When adding a new content type via the UI, [`node_add_body_field()`](https://api.backdropcms.org/api/backdrop/core!modules!node!node.module/function/node_add_body_field/1) is called which adds a hard-coded Body field to the content type.

I'd like to see the ability to alter or remove this Body field in core. My initial thought is to add a `hook_node_body_field_alter()` call at the end of the function, so that the Body field can either be edited before it's saved, or removed entirely (by returning nothing).

This would be useful, for example, in my custom install profile where it adds it's own Body field to the pre-configured content type. Upon creating new content types, it'd be nice not to have two separate Body fields (body and field_body) in use, but to re-use my existing one...

**Comment by BWPanda** [comment]
Or, maybe a simpler approach would be to simply add an option to the UI of the content type add form that lets the user choose whether or not the Body field is added...

In my case, I could simply choose not to add the core Body field when adding a new content type, and then add my existing one from the Fields page.

**Comment by BWPanda** [comment]
Added a PR based on my second comment.

**Comment by BWPanda** [comment]
@quicksketch If not a UI option, then what about my first thought for an API `_alter()` hook?

**Comment by quicksketch** [comment]
A new hook seems unnecessary. As you're just wanting to modify a single submit handler, let's just make that submit handler have the ability to optionally create the body field, but we just won't show a UI option for it. You can just use a normal form_alter() introduce the option, or disable creating the body every time. e.g.

In the form:

```php
   // Create the body field by default on form submission. This may be altered by other modules.
   $form['submission']['body'] = array(
     '#type' => 'value',
     '#value' => TRUE,
   );
```

And in the submit handler:
```php
   if ($form_state['values']['body']) {
     node_add_body_field($type);
   }
```

**Comment by BWPanda** [comment]
Created a new PR that addresses @quicksketch's suggestions.

**Comment by quicksketch** [comment]
Thanks @BWPanda! Merged https://github.com/backdrop/backdrop/pull/2182 into 1.x and 1.10.x.
