### ISSUE TITLE
Backdrop 1.9.4 Release

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3037]
Steps to create a BUG-FIX release
==================================

## Pre-release tasks

- [x] Merge commits - quicksketch
- [x] Create a new bugfix release - quicksketch
- [x] Create the next bugfix milestone - jenlampton
- [x] Move all unfinished issues to the next bugfix release milestone - jenlampton
- [x] Draft Release notes - serundeputy
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)
- If this is a security release:
  - [x] Draft Security Advisory - serundeputy

## Release tasks

- [x] Update bootstrap.inc with version number  - serundeputy
- [x] Tag for release, and push tag to GitHub - serundeputy
- [x] Revert version number back - serundeputy
- [x] Create release notes on GitHub - jenlampton
  - [x] Double check if any changes were made to files outside the `core` directory
- [x] Update the front page download link on b.org - jenlampton
- [x] Tweet that a new release is out - jenlampton 
- If this is a security release:
  - [x] Publish Security Advisory on b.org - serundeputy
  - [x] Mark the release node on b.org as a security release - jenlampton

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon)  - serundeputy
- [x] Push the bug-fix release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop)  - serundeputy
- [x] Update the Wikipedia articles - klonos

**Comment by klonos** [comment]
All done ;)
