### ISSUE TITLE
[UX] Consolidate the places where we list available updates...

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3039]
...and also fix UX WTFs.

This is a lazy copy-paste from my comment in #2880

The bigger UX fail here is that we have multiple places for viewing and performing updates. What I would like to see instead is:

a) do not render the `/admin/appearance/update`, `/admin/modules/update` and `/admin/structure/layouts/update` tabs at all if there are no updates. Another related WTF is that these pages show ALL updates, not taking under account the type of project:

<img width="891" alt="screen shot 2017-11-13 at 6 13 47 am" src="https://user-images.githubusercontent.com/2423362/32702343-eaee53b0-c839-11e7-8fb7-5f50272c77a9.png">

b) Merge the "Update xyz" tabs into a single "Update projects" tab/page (or whatever we decide to call it). So we currently have this:

<img width="781" alt="screen shot 2017-11-13 at 6 19 13 am" src="https://user-images.githubusercontent.com/2423362/32702399-b8ac0630-c83a-11e7-995a-7a3a23c0d9d5.png">

...which, if there are updates available, redirects to `/admin/xyz/update`. Well, in my head, this is very similar to the Project Installer pages, filtered down to projects that are already installed. So, the "Update xyz" tabs could very well be converted to a single Project Installer page/tab, filtered by projects already installed, or by projects already installed AND with updates available. Then, we could have an "Update queue" sidebar (in place of the "Installation queue" sidebar), and these projects could have a "Add to update queue" button/link.

So, this:

<img width="892" alt="screen shot 2017-11-13 at 6 32 05 am" src="https://user-images.githubusercontent.com/2423362/32702505-6f631fc0-c83c-11e7-9f8e-a7d4cf72263f.png">

...could become something like this:

<img width="892" alt="screen shot 2017-11-13 at 6 45 26 am" src="https://user-images.githubusercontent.com/2423362/32702672-51cdc756-c83e-11e7-8004-7a152b9c685b.png">

So people can follow a single, streamlined and familiar process of installing updates (opposed to how we currently have them pogo-sticking around various pages in the UI).

**Comment by laryn** [comment]
I like the direction towards simplifying. Stepping one step even further back, what about when you click directly on "Functionality" and get the list of modules (enabled or not). If there are updates, it's noted in a notification at the top of the page. Would it make sense on this top level page to do: 

- subtle indicators of some kind to show which are up to date, which are outdated, etc.
- some kind of sorting here like was done on the status page, so security updates are at the top, followed by other available updates, followed by the usual list? (or at least a way to filter to show only the ones that have updates pending in a quick sort kind of way)
- links to update a module directly from this page?

**Comment by laryn** [comment]
Mockup of "Available Updates" for discussion, adding an "Update all" button at top, and individual "Update" buttons by the individual entries. (Visual includes [sort changes](https://github.com/backdrop/backdrop-issues/issues/3132) and [ability to update core](https://github.com/backdrop/backdrop-issues/issues/3105))

![screen shot 2018-05-18 at 3 40 48 pm](https://user-images.githubusercontent.com/871421/40256999-1b40cab0-5ab2-11e8-8844-6177040c3f69.jpg)

I'm also thinking that maybe the ones with no updates don't even need to show on this page, to be honest.

**Comment by jenlampton** [comment]
Can we rename this issue? I'm confused about the intent, since we already have a consolidated place where we list all updates: the Available Updates report.

We also have https://github.com/backdrop/backdrop-issues/issues/2714, which I think will move the updating of all the things to a single place, so is this issue different from that one? And if so, how so?
