### ISSUE TITLE
[UX] Show a screenshot in the modules / themes / layouts browsers

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3040]
## Describe your issue or idea

It's hard to tell what your themes or layouts will look like before you install them, because there are no screenshots in the browsers. Let's link up the images we already have.

Like this:
<img width="988" alt="screen shot 2018-04-20 at 3 47 49 pm" src="https://user-images.githubusercontent.com/397895/39076751-36dcda0e-44b2-11e8-8e6e-26b4409d8289.png">

On tablet: 
<img width="706" alt="screen shot 2018-04-20 at 3 48 25 pm" src="https://user-images.githubusercontent.com/397895/39076769-5565cab2-44b2-11e8-84a1-813f7ba19c59.png">

On mobile:
<img width="309" alt="screen shot 2018-04-20 at 3 50 51 pm" src="https://user-images.githubusercontent.com/397895/39076814-a5a799b0-44b2-11e8-9500-b7ce725fd356.png">

Project details:
<img width="699" alt="screen shot 2018-04-20 at 3 52 02 pm" src="https://user-images.githubusercontent.com/397895/39076838-d008afd2-44b2-11e8-9a9a-917185f103db.png">

Project details on mobile: 
<img width="363" alt="screen shot 2018-04-20 at 3 53 31 pm" src="https://user-images.githubusercontent.com/397895/39076885-065c6696-44b3-11e8-9ccd-58efe058d958.png">

---
~~PR: https://github.com/backdrop/backdrop/pull/2135~~
PR: https://github.com/backdrop/backdrop/pull/2138

**Comment by jenlampton** [comment]
It looks like these interfaces could use a designer's touch, so adding the audience-design tag. let's get this in and then iterate on design if we can get some guidance :)

**Comment by herbdool** [comment]
I think it looks pretty good! Looked on desktop and mobile. It meets the basic requirements of providing screenshots and looking clean. I'm not a designer, but I'd say it's ready for including.

**Comment by jenlampton** [comment]
I'm marking this as RTBC to get @quicksketch's eyes on it :)

**Comment by olafgrabienski** [comment]
> let's get this in and then iterate on design if we can get some guidance

> It meets the basic requirements of providing screenshots and looking clean.

Same here, looks good, especially the list of themes. I guess to iterate on design, we also need to improve the theme pages on backdropcms.org itself, maybe take the showcase pages as model.

**Comment by jenlampton** [comment]
We have designs already for b.org.

**Comment by quicksketch** [comment]
Thanks @olafgrabienski and @herbdool! I agree, this looks fantastic!! I can't believe we had this functionality _already_ in the feed and just weren't taking advantage of it. Seems like a no-brainer as far as a major UX improvement and minimal impact. It's an easy win so let's take it. :grinning: 

We had a little sandbox shenanigans so I ended up rerolling this at https://github.com/backdrop/backdrop/pull/2138. @opi and @docwilmot chimed in with some suggestions there, which were spot-on.

With the current approvals, code reviews, and changes made, this looks good to go! I'll let the tests finish one more time and then we can merge in.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2138 into 1.x for 1.10.

Honestly this could go in 1.9.x as well as a UX improvement. But being so close to 1.10 and being a major improvement, let's save this for 1.10 only as a great new feature we can showcase.
