### ISSUE TITLE
detect timezone directly from the browser

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3041]
## Describe your issue or idea

This is a follow up to https://github.com/backdrop/backdrop-issues/issues/3032 in an attempt to de-scope the changes introduced into something we can all agree on for Backdrop 1.10.

> Modern JavaScript can now detect timezones directly from the browser, rather than just getting the offset from GMT. We should use this increased accuracy method to set the site and user timezones when displaying a timezone element.

**Comment by quicksketch** [comment]
Let's just reuse https://github.com/backdrop/backdrop-issues/issues/3032 to implement the JS only and not worry about the installer.
