### ISSUE TITLE
[UX] Enable the password toggle on all core password fields

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#3048]
## Describe your issue or idea

Should there be a show password toggle on the Database configruation installation step?

![39031192-9b408460-441b-11e8-9287-b1c8ac863c7f](https://user-images.githubusercontent.com/6763671/39095296-450b97f4-460c-11e8-8fe6-ae8e9e56d582.png)

### Steps to reproduce (if reporting a bug)

* Install Backdrop
* On the `Database configuration` step it asks for the Database password
* In #297 we added a password show/hide toggle fo the backdrop users password field (user 1)

### Actual behavior (if reporting a bug)

Currently the database password field does not have this toggle.

### Expected behavior (if reporting a bug)

Up for debate, but should we provide a consistent experience here and add a show/hide password toggle?

### Relevant version/system information (if applicable)

`1.x`

**Comment by BWPanda** [comment]
I believe it should. I'm all for consistency.

I'd go one step further and suggest that any and all [```type=password```](https://api.backdropcms.org/form_api#password) fields have this toggle.

**Comment by klonos** [comment]
...setting a milestone and the tag to "needs feedback" to grab attention for this. We should either do, or close.

Personally, what @BWPanda said.

**Comment by jenlampton** [comment]
I like this idea, but I'm not sure this is a feature, or needs this milestone. As soon as we get a PR it can be slated for the next bug-fix release (removing milestone).

**Comment by BWPanda** [comment]
Changed this to a more broad issue about updating all core password fields, and made a PR to that effect.

**Comment by BWPanda** [comment]
I did a `grep "'#type' => 'password',"` to find all core password fields, but if there's any I missed please point them out (I purposefully ignored any in tests)..

**Comment by klonos** [comment]
Thanks @BWPanda 👍 

I've checked the PR and tested the respective forms. This is RTBC 👍 

PS: I've left a comment in the PR about fixing a wrapping issue, but it's not related to the changes in the PR, so feel free to ignore me.

**Comment by BWPanda** [comment]
Thanks @serundeputy for the suggestion, and @klonos for the review.Merged https://github.com/backdrop/backdrop/pull/3213 into 1.x and 1.16.x.
