### ISSUE TITLE
Set fixed "from:" and add "Reply-to:" to improve deliverability of Drupal mail

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#305]
In the fight against spam more and more ISP's require mail send though the php function to originate from the main domain. The contact form however uses the senders email as "from:" address.

Add a field in settings to optionally set a fixed "from address" (for example contactform@domain.tld) and use "reply-to" to enable replies to the sender, while still using the fixed from address which is accepted by the isp.

Here's the same issue on [d.o](https://www.drupal.org/node/111702)

**Comment by quicksketch** [comment]
A bunch of tests need to be updated in the PR it looks like, so marking this needs work.

**Comment by jenlampton** [comment]
Pushing a new PR to run test suite again

**Comment by quicksketch** [comment]
Great, thanks! Merged into 1.x in https://github.com/backdrop/backdrop/pull/764.
