### ISSUE TITLE
[UX] Add a site-wide contact form block

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#3053]
Part of [[META] Contact module improvements #3023](https://github.com/backdrop/backdrop-issues/issues/3023).

> I would love to se a contact form block in core! This is something I see a lot in designs, and I need to use webform to achieve it. Would be great if we could get that in core instead. (@jenlampton)

Backdrop core should provide a contact form block, with the same fields as /contact page.

---
PR from @jenlampton https://github.com/backdrop/backdrop/pull/2294

**Comment by jenlampton** [comment]
> The contact form block should handle this too ?

Yes, ideally.

> Should we move this code into a separate function to not repeat ourselves ?

yes, great idea! :)

**Comment by herbdool** [comment]
@opi looks like it only calls `flood_is_allowed()` so seems to me it's already abstracted. Unless you also want to put the message there too.

**Comment by jenlampton** [comment]
I've got a PR up at https://github.com/backdrop/backdrop/pull/2294 that could use some testing. Sorry I didn't get this done in time for 1.11, but I've tagged this issue for 1.12 so hopefully we'll get it in for the next one :)

**Comment by quicksketch** [comment]
I'm specifically marking this postponed just so we don't accidentally merge it into 1.x before we branch for 1.11.x.

**Comment by quicksketch** [comment]
Merged into 1.x for 1.12.0. Thanks everyone!
