### ISSUE TITLE
Enable tokens on maintenance mode 'message' field

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3058]
The 'Message to display when in maintenance mode' field (at /admin/config/development/maintenance) would be a great place to enable tokens, especially things like `[site:name]`...

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2172

**Comment by BWPanda** [comment]
Add PR that fixes this.

**Comment by quicksketch** [comment]
Left a code review on https://github.com/backdrop/backdrop/pull/2151.

- Probably should keep t() in place.
- Needs an update hook to replace `@site` with `[site:name]`

Separately, I wonder if this is overkill. Tokens can do much much more, but what other tokens are likely to be used here? I do like that it's adding consistency in the way we do replacements, and it documents the fact that replacements are done at all. Right now `@site` is just "magically" replaced with no indication that it is possible.

**Comment by BWPanda** [comment]
@quicksketch I think tokens are the more 'proper' way of doing this. As you said, they better document the 'magic' replacement we have currently. Also, I can see the following tokens being used in addition to `[site:name]`:

- `[site:slogan]` (for displaying in addition to the site name)
- `[site:mail]` (for contacting the website owner while the contact page is offline)
- `[site:login-url]` (for directing authorised users to the login page)

I had the thought to support tokens when writing the [Maintenance Page](https://github.com/backdrop-contrib/maintenance_page) module. Better to have support in core, then I can add support to my extra 'title' field.

**Comment by BWPanda** [comment]
New PR here: https://github.com/backdrop/backdrop/pull/2172

**Comment by quicksketch** [comment]
Good points all. The new PR looks great.

I've merged https://github.com/backdrop/backdrop/pull/2172 into 1.x for 1.10. Thanks!
