### ISSUE TITLE
Security Releases - should we officially support 2 minor versions? or maybe 3?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3059]
## Describe your issue or idea

For both the 1.9.5 and 1.9.3 releases, we also issued a security release for other branches. 

I think it would be good for Backdrop to adopt a policy of issuing security releases for at least 2 minor versions for all security fixes, though my preference would be for 3.

Since we do three releases each year, this would give every site a year to get up to the latest version of backdrop - and would still be protected until they do.

**Comment by olafgrabienski** [comment]
Three releases / one year sounds great!

It might be however challenging to provide always three security releases *in time* in case of short-dated releases (determined by Drupal release dates).

**Comment by klonos** [comment]
I like the 3 releases option too.

**Comment by BWPanda** [comment]
It seems '2 minor releases' was decided:

> Security releases will be issued **for the last 2 minor releases** of Backdrop, or for the last 8 months.

https://backdropcms.org/security
