### ISSUE TITLE
Module list page: Use a little brighter colours for the enabled/disabled indicators.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3066]
Instead of the current #080 / #800

![screen shot 2018-04-30 at 6 42 48 pm](https://user-images.githubusercontent.com/2423362/39420380-ab5b3f0e-4ca7-11e8-8f33-ba4481c1620e.png)

![screen shot 2018-04-30 at 6 53 51 pm](https://user-images.githubusercontent.com/2423362/39420416-d8f9de02-4ca7-11e8-8cf7-6f1c169e33a6.png)

...use something brighter that provides a little more contrast, like say #C61214 / #00BE58:

![screen shot 2018-04-30 at 6 48 03 pm](https://user-images.githubusercontent.com/2423362/39420375-a4f5434e-4ca7-11e8-98a4-cbd7ac04dff0.png)

![screen shot 2018-04-30 at 6 49 51 pm](https://user-images.githubusercontent.com/2423362/39420378-a7c5e54c-4ca7-11e8-804a-4cb84c2f2f87.png)

PS: I have used "parakeet" and "crimson" from https://digitalsynopsis.com/design/color-thesaurus-correct-names-of-shades

---

PR by @klonos: https://github.com/backdrop/backdrop/pull/2158

**Comment by klonos** [comment]
...I expect a lot of bike shading re the colours we should used, but the point was just to use something brighter, in order to make it easier to spot these indicators both when the mouse hovers over the table rows (yellowish background) and when it is not.

**Comment by quicksketch** [comment]
This looks good to me. The scope is very limited here, only the modules page is affected and nothing else, so it's a low-risk change. RTBC unless there are any complaints.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2158 into 1.x and 1.9.x. Thanks!
