### ISSUE TITLE
[UX] Don't call people users

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3068]
## Describe your issue or idea

People hate being called users. When creating a node, the comment settings refer to people as users twice: 
![screen shot 2018-04-30 at 1 59 56 pm](https://user-images.githubusercontent.com/397895/39450051-cf1b1b40-4c7e-11e8-8ea1-b6cf200e3df5.png)

Note: This is not be confused with calling "User accounts" people - which is also a problem in Drupal/Backdrop. This is simply about improving our text to be more human.

People should be called "People" in this instance, as we're not talking the records in the database and/or associated PHP objects, but the humans who are using them.

### Steps to reproduce (if reporting a bug)

* Create a Post

### Actual behavior (if reporting a bug)

* People are called "Users"

### Expected behavior (if reporting a bug)

* People should be called "People" in this instance, see above.

---
PR: https://github.com/backdrop/backdrop/pull/2161

**Comment by jenlampton** [comment]
I've pushed a PR with the following text improvements:
![screen shot 2018-04-30 at 2 06 07 pm](https://user-images.githubusercontent.com/397895/39450353-dcf73dc4-4c7f-11e8-899e-1bac07fe15cd.png)

**Comment by serundeputy** [comment]
Thanks @jenlampton; the language is nicer and works well.
Merged will ship with `1.9.6` and `1.10.0`.

**Comment by jenlampton** [comment]
I think this may be the fastest opened / PRed / Merged issue in Backdrop history!
