### ISSUE TITLE
[UX] Add vertical spacing below fieldset description 

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#3071]
Follow https://github.com/backdrop/backdrop-issues/issues/3064#issuecomment-385288385

PR: https://github.com/backdrop/backdrop/pull/2164

**Comment by olafgrabienski** [comment]
I've had a look at the description above the 'Clear log messages' button, looks good!

To arbitrarily check if there are side-effects I've had also a look at two other places with a fieldset description: in the *Indexing* section of `admin/config/search/settings` and in the *Shortcut icon settings* on `admin/config/system/site-information`. They're not affected by the change, as the following element has already a `margin-top` definition.

**Comment by quicksketch** [comment]
Thanks! I've merged https://github.com/backdrop/backdrop/pull/2164 into 1.x and 1.9.x.
