### ISSUE TITLE
Decouple Node from Depending on Date and use consistent date fields

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3073]
## Describe your issue or idea

In https://github.com/backdrop/backdrop-issues/issues/857, we added scheduled publishing. However, the date field we used there was a `date_popup` field, which is provided by Date module. We also used the `BackdropDateTime` object, which is also provided by Date module. We need to do one of the following:

- Make Date module required, as Node module is.
- Move the BackdropDateTime object and all FormAPI fields out of Date module.
- Use Date functionality conditionally in Node module if it is enabled.

We should also be consistent about the date fields in the node form. While "scheduled" date is a "date_popup", the "Authored on" (`created`) date field is just a plain text field. We should use a date_popup on that field as well.

**Comment by herbdool** [comment]
I say A (make date module required) for now, then B later (move code out).

**Comment by laryn** [comment]
> We should also be consistent about the date fields in the node form. While "scheduled" date is a "date_popup", the "Authored on" (created) date field is just a plain text field. We should use a date_popup on that field as well.

Related bug with the 'authored on' date field: https://github.com/backdrop/backdrop-issues/issues/1370

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/2171.

Removing the date elements from Date module is hard, but moving `date.inc` (essentially Date API from D7) and `BackdropDateTime` into the `/includes` directory is easy. So this PR moves the general Date API functionality into core as a globally available API. But it leaves Date elements where they are and has Node module simply switch back to using a textfield if Date module is not available.

Since this deals with toggling between the Date Popup field and just a plain textfield, it covers #1370 in the PR as well, because both date fields on the node form have the same problems.

**Comment by quicksketch** [comment]
With the new tests in place covering both the Date-enabled and Date-disabled use-cases, I'm going to merge the current PR lest we need to ship 1.10 with a major flaw in the new scheduling system. Let's file follow-ups if needed to continue adjusting.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2171 into 1.x for 1.10.
