### ISSUE TITLE
New "Show option for scheduling" checkbox gets pushed below multilingual options

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3074]
### Steps to reproduce (if reporting a bug)
On the content type configuration:

![screenshot from 2018-05-02 09-15-31](https://user-images.githubusercontent.com/1071483/39525339-adcf9cb0-4de9-11e8-9a73-d31e47a33754.png)

### Actual behavior (if reporting a bug)
Checkbox gets pushed below by multilingual options.

### Expected behavior (if reporting a bug)
Should stay next to publishing options

---

PR https://github.com/backdrop/backdrop/pull/2168

**Comment by quicksketch** [comment]
Thanks! Marking for 1.10.

**Comment by quicksketch** [comment]
There are no weights on this form yet, the checkbox was literally just beneath the language options in the form API array. PR filed at https://github.com/backdrop/backdrop/pull/2168.

**Comment by opi** [comment]
PR visually approved.
