### ISSUE TITLE
[UX] Provide a hint that classes can be added to the inner wrapper of a region.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3075]
I have noticed this small UX problem while posting a comment in https://github.com/backdrop/backdrop-issues/issues/682#issuecomment-386072304 ...

So by default, when one clicks the "Configure region" option of any region in the "Manage blocks" page:

![screen shot 2018-05-03 at 4 09 42 am](https://user-images.githubusercontent.com/2423362/39541073-f6dddcca-4e87-11e8-8071-7e25f6b601b3.png)

...they see this:

![screen shot 2018-05-03 at 4 11 16 am](https://user-images.githubusercontent.com/2423362/39541110-11fc1e18-4e88-11e8-9b4d-fa932adfd117.png)

What is not clear, is that if you select any option other than the default "no inner wrapper", you get a "CSS classes for inner wrapper" field, that allows you to add classes:

![screen shot 2018-05-03 at 4 12 40 am](https://user-images.githubusercontent.com/2423362/39541184-49fd1862-4e88-11e8-864b-915a66c3f38e.png)

This is a very useful feature, but we are hiding it away from the user. I see 2 options that would help improve the situation:

1. Add some help text while the select option in the dropdown is "no inner wrapper". Something very simple like: 

    > Selecting an inner wrapper would allow you to specify custom classes for it, which you can then use to help you theme your site.

    Here's how this would look:

    ![screen shot 2018-05-03 at 4 29 43 am](https://user-images.githubusercontent.com/2423362/39542012-b105f9dc-4e8a-11e8-9a8a-bc22d97caf04.png)

2. "CSS classes for inner wrapper" field be rendered all the time, instead of being hidden via `#states`, but have it be disabled (with an explanation as to why), until the user has selected an option other than "no inner wrapper". Something like this:

    ![screen shot 2018-05-03 at 4 47 16 am](https://user-images.githubusercontent.com/2423362/39542906-1cd38808-4e8d-11e8-84ec-0524f32ee291.png)

Thoughts?

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2527

**Comment by klonos** [comment]
...I personally like the 2nd option, because... nobody reads help text unfortunately 😞

**Comment by quicksketch** [comment]
Yeah second option is better. We can use #states to set enabled/disabled, but it doesn't have the ability to directly set description text. We could hide/show description text by making it a separate element, but it wouldn't be pretty, either in markup or in the UI due to extra margins. Though we could perhaps use a description like "If an inner wrapper is added, specify classes separated by spaces."

**Comment by klonos** [comment]
So yeah, turns out that `'#type' => 'help'` does not support `#states` or `#attributes` (or if meant to, then it doesn't work). So this does not work:

```php
  $form['help'] = array(
    '#type' => 'help',
    '#markup' => t('Separate multiple classes with spaces.'),
    '#attributes' => array('class' => array('description')),
    '#states' => array(
      'visible' => array(
        ':input[name="element"]' => array('value' => ''),
      ),
    ),
  );
```

...in that the class is not added, and the `#states` functionality never kicks in.

Anyway, I went with what @quicksketch has suggested for the help text, which is a much simpler change too:

<img width="615" alt="Screen Shot 2019-03-09 at 8 41 59 pm" src="https://user-images.githubusercontent.com/2423362/54069415-ee844f00-42ab-11e9-9e52-fcde6e932b5d.png">

Suggesting 1.12.4 milestone.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2527 into 1.x and 1.12.x. Thanks @klonos and @herbdool!
