### ISSUE TITLE
Hide task list in the update.php page if the page is being viewed as anonymous.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3079]
Here's what anonymous users currently see when visiting `/update.php`:

<img width="848" alt="screen shot 2018-05-04 at 11 14 14 am" src="https://user-images.githubusercontent.com/2423362/39609506-d66036e0-4f8c-11e8-8259-836c4183015e.png">

We should remove the steps sidebar when anonymous, because it simply does not make sense and serves no purpose.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2170

**Comment by klonos** [comment]
...after:

<img width="875" alt="screen shot 2018-05-04 at 11 46 57 am" src="https://user-images.githubusercontent.com/2423362/39610044-e0810402-4f90-11e8-88c4-8e7f3713b4b3.png">

**Comment by klonos** [comment]
...I guess should get in before we start work on #3078

**Comment by klonos** [comment]
...actual, live thing (from the PR sandbox): http://2166.backdrop.backdrop.qa.backdropcms.org/core/update.php

**Comment by quicksketch** [comment]
Nice one @klonos! Merged https://github.com/backdrop/backdrop/pull/2170 into 1.x for 1.10.
