### ISSUE TITLE
Insert link - problem with conversion of uri to url.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#3085]
I have found a problem with the change introduced by the PR for issue #2072. The code should not be adding the prefix derived from `base_path()` if the link is an external one starting with `http`.

This problem occurs when the site is installed in a subdirectory.

---
PR by @Graham-72: https://github.com/backdrop/backdrop/pull/2179

**Comment by Graham-72** [comment]
It would be highly desirable to also make the change suggested in issue #3083 and help the user create an external link correctly  by including the http prefix needed for this fix to function.

**Comment by klonos** [comment]
@Graham-72 I've left a comment on the PR.

**Comment by Graham-72** [comment]
@klonos maybe I have broken something but I cannot find your comment.

**Comment by quicksketch** [comment]
Thanks @Graham-72! Merged https://github.com/backdrop/backdrop/pull/2179 into 1.x for 1.10.
