### ISSUE TITLE
Completely blasted Layout under "Manage Blocks" - how to fix?

### ISSUE THREAD

**Issue by AlexL777** [backdrop/backdrop-issues#3088]
## Describe your issue or idea

Hi Developers,

i have blasted Layout under "Manage Blocks" in the Backend of Backdrop 1.9.5. Look this Screenshot.

![backdrop-manage-block-layout-errors](https://user-images.githubusercontent.com/7885632/39717034-57fe2070-5232-11e8-900b-e4669a2c59c0.jpg)

How can I fix this problem because I've had it for at least 3 backdrop versions. That's always in the Google Chrome browser with me. So what should I do now?

Thanks in Advance, Alexander

**Comment by laryn** [comment]
Which layout are you using?

**Comment by AlexL777** [comment]
`layout >> list themes >> basis`

Now I use something different and everything is fine again. But maybe the developers should look at it with the layout with the administration theme "Basis".

**Comment by laryn** [comment]
Basis is the theme, and which Layout template is configured when the display is blasted? Is it a core Layout or a custom one? (e.g. when you click on "Configure Layout" in the screenshot above, which Layout template is selected?)

**Comment by AlexL777** [comment]
![backdrop-configure-layout-backdrop-1-9-5](https://user-images.githubusercontent.com/7885632/39718323-3958129e-5236-11e8-9367-5e1a38350a84.jpg)

**Comment by docwilmot** [comment]
Basis currently cannot be used as an admin theme. Already and issue: see https://github.com/backdrop/backdrop-issues/issues/2653.

**Comment by AlexL777** [comment]
If that's the case, then I like to use another theme. Also worked with it now. Thank you.

**Comment by laryn** [comment]
Closing as duplicate.
