### ISSUE TITLE
[UX] Mobile project browser: make search box better for mobile

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3095]
This issue was spun off from https://github.com/backdrop/backdrop-issues/issues/3092

Original suggestion from @klonos: 

> Replace the "Search" text in the button with a magnifying glass icon, and inline the button with the search field.

**Comment by jenlampton** [comment]
This will be easy after 1.10 ships!

**Comment by klonos** [comment]
I will go ahead and close this in favor of #4652, which seeks to add an option for this in the search block settings (along with a setting that allows the search block to always be rendered as a searchbar with a magnifying glass, independently of screen size).
