### ISSUE TITLE
[UX] - Insert link/upload file dialogue needs advice about file types and size limit

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#3101]
@olafgrabienski has pointed out that in the new procedure introduced in response to issue #2072 there is no help text about the allowed file types in the "Upload a file and link to it" part of the link dialog. (Comment is at https://github.com/backdrop/backdrop-issues/issues/2072#issuecomment-386832890.)

I am preparing a PR to fix this issue with this result as the aim
![screenshot-2018-5-10 edit basic page a new test page backdrop starter](https://user-images.githubusercontent.com/10559274/39892004-1c806f14-5497-11e8-84fd-1bcda3a43937.png)

**Comment by klonos** [comment]
@Graham-72 minor nit-pick comment in the PR.

**Comment by quicksketch** [comment]
I updated the PR to use `theme('file_upload_help')` so we output the help text in the same way as in Image and File modules.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2184 into 1.x for 1.10. Thanks all!
