### ISSUE TITLE
[UX] Improve the comment closing override text

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3102]
## Describe your issue or idea

Follow-up to https://github.com/backdrop/backdrop-issues/issues/3001 where we added comment closing capability. We should improve the UX of the "Override the automatic closing of comments" checkbox:

![image](https://user-images.githubusercontent.com/100206/39892007-0f8ca572-5454-11e8-90cc-0789132775b5.png)

The wording and functionality here is awkward. Checking the box *disables* the automatic closing. Whereas on the content type form, you check the box to enable automatic closing. Instead what should be done here is the checkbox should by checked all the time by default if automatic closing is enabled, and you would *uncheck* the box to disable the automatic closing. Such as this:

![image](https://user-images.githubusercontent.com/100206/39909186-8ddd1b6c-54a6-11e8-9506-2589b2b20f0e.png)

### Relevant version/system information (if applicable)

Backdrop 1.x (1.10 dev)

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/2183.

**Comment by herbdool** [comment]
The change looks reasonable and code looks good!

**Comment by herbdool** [comment]
I've also tested it out too. Works as expected and the UX is more sensible.

**Comment by quicksketch** [comment]
Thanks @herbdool! Merged https://github.com/backdrop/backdrop/pull/2183 into 1.x for 1.10.
