### ISSUE TITLE
Add new entity info keys: referenceable

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#3103]
In order for the reference module to be able to query possible target entities based on their title and bundle, each entity type needs to actually define the columns in their database that are used to store the label and status fields.

I currently have this code in `reference.module` to set the proper values for the entities in core:

```
function reference_entity_info_alter(&$entity_info) {
  $entity_info['comment']['entity keys']['status'] = 'status';
  $entity_info['file']['entity keys']['status'] = 'status';
  $entity_info['node']['entity keys']['status'] = 'status';
  $entity_info['user']['entity keys']['status'] = 'status';
}
```

We should move setting those values into the core entity definitions.

**Comment by bugfolder** [comment]
In addition to adding this information to core entities, `hook_entity_info()` documentation needs to be updated to note their new requirement.

https://docs.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.api.php/function/hook_entity_info/1

**Comment by laryn** [comment]
From @docwilmot in [another thread](https://github.com/backdrop-contrib/ubercart/issues/274):

> I think the code in Reference is actually correct, but unnecessary. In D7 Entity you needed a way to know how to find an Entity's label, so for Node it would be `title`, or for comments, `subject`, so that you could say in code `$node->title` or  `$comment->subject`. But in Backdrop all our Entities are classed objects, and all *must* have a `Entity::label()`, hence we dont any longer need a `label` key in the `entity keys`. For any Entity in Backdrop you can call `$entity->label()` without knowing if the label is stored in `subject` or `title` etc, so `$node->label()` is the same as `$node->title`

> So that `if...else` code block shouldnt be necessary I think. Labels are everywhere.

**Comment by jenlampton** [comment]
We should also add a key for an entity type to declare if it is referenceable or not, so that terms and files don't need to be fully supported at the time reference gets into core. 

This would also allow contrib entity types to define if they are referencable or not.

**Comment by jenlampton** [comment]
As per the comment from @docwilmot above, I've removed label from the list of keys to add.
