### ISSUE TITLE
BackdropWebTestCase::assertOption cannot test select fields with optgroups

### ISSUE THREAD

**Issue by mikemccaffrey** [backdrop/backdrop-issues#3104]
Currently, you can't successfully test that an option exists within a select field if the options within the field are organized into optgroups. 

One example of a field like this is the widget selection for creating new fields on a manage fields page. Before a field type is selected and the widget field is limited to applicable widgets using javascript, the widget field is organized by field types in optgroup tags:

```
<select class="widget-type-select form-select" id="edit-fields-add-new-field-widget-type" name="fields[_add_new_field][widget_type]">
  <option value="" selected="selected">- Select a widget -</option>
  <optgroup label="Date (ISO format)">
    <option value="date_popup">Pop-up calendar</option>
    <option value="date_select">Select list</option>
    <option value="date_text">Text field</option>
  </optgroup>
...
```

The assertOption function isn't working because it is looking for option tags that are the immediate children of select tags:
```
$this->xpath('//select[@id=:id]/option[@value=:option]', array(':id' => $id, ':option' => $option));
```

Instead, we should add an extra slash, so we are looking for options that are descendants of select tags:
```
$this->xpath('//select[@id=:id]//option[@value=:option]', array(':id' => $id, ':option' => $option));
```

This is a related issue for Drupal: https://www.drupal.org/node/1413888

**Comment by quicksketch** [comment]
This is a trivial fix. I've merged https://github.com/backdrop/backdrop/pull/2185 into 1.x and 1.10.x. Thanks @mikemccaffrey!
