### ISSUE TITLE
[DX] Add core updates via Backdrop UI.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#3105]
## Describe your issue or idea

In https://github.com/backdrop/backdrop-issues/issues/2018 we are interested in providing the ability for automatic updates to Backdrop core.  As an initial step towards that goal this issue adds the ability to manually update Backdrop core via UI at `/admin/modules/update`

### Actual behavior (if reporting a bug)

Currently at `/admin/modules/update` core updates are relegated to there own `Manual` section that prompts the user to download Backdrop and then move the files around themselves via server tools or cli.

### Expected behavior (if reporting a bug)

Allow updating of core by selecting the core update from `/admin/modules/update` from the list the same way you can update modules.

### Relevant version/system information (if applicable)

`1.x`

----

~~PR: https://github.com/backdrop/backdrop/pull/2186~~ this one was `corrupted` w/ `.swp` file
~~PR: https://github.com/backdrop/backdrop/pull/2201~~
PR: https://github.com/backdrop/backdrop/pull/2289

**Comment by serundeputy** [comment]
This one can not be tested via sandbox; since sandboxes are downloading `1.x` backdrop (which does not need an update)

To test (I"m using [lando](https://docs.devwithlando.io) so I can have drush and things I need):

* Initiate a backdrop site
 
```bash
lando init
```

select backdrop

* download an old backdrop
  * lando.dev drush dlb backdrop --select
    * select an eld backdrop I chose `1.9.3`  which at the time of this writing was option `2`

* install backdrop

```bash
lando drush si --db-url=mysql://backdrop:backdrop@database/backdrop
```

Make note of the username and password (you can install via UI as well, this is just a little faster if say you want to test this `11` times).

* Apply this patch: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2186.patch

  * get the patch:

```bash
wget https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2186.patch
```

  * apply
 
```bash
patch -p1 < 2186.patch
```

you should see output similar to: 

```bash
geoff@yep backdrop exit code: [0] $ patch -p1 < 2186.patch
patching file core/modules/system/system.updater.inc
patching file core/includes/updater.inc
patching file core/modules/installer/installer.authorize.inc
patching file core/modules/installer/installer.manager.inc
patching file core/modules/installer/installer.module
patching file core/modules/system/system.module
Hunk #1 succeeded at 2113 (offset -48 lines).
Hunk #2 succeeded at 3829 (offset -48 lines).
patching file core/modules/system/system.updater.inc
```

* clear cache so Backdrop can pick up on the new class `CoreUpdater`

```bash
lando drush cc all
```

* visit: `/admin/modules/update`; you should see:

<img width="1635" alt="screen shot 2018-05-13 at 1 52 47 pm" src="https://user-images.githubusercontent.com/6763671/39970163-ff36ddf6-56b4-11e8-87b5-7069ff72d634.png">

* select the Backdrop update checkbox and proceed as normal.

**Comment by findlabnet** [comment]
Sorry if I lost something, but for doing such all document root should be writable for web-server?

**Comment by herbdool** [comment]
Who knew it was this easy?!

It worked smoothly for me. I tested with Lando using @serundeputy's steps -- quite helpful!

A few things:

* This is pretty awesome.
* swp file shouldn't be in the PR I'm guessing
* We should change the links on the status page to point to the Update module tab instead of where it points now. Currently someone would click on the red dot at the top:

![screenshot from 2018-05-13 19-52-05](https://user-images.githubusercontent.com/1071483/39972987-4c728912-56e7-11e8-9f6c-bb480e606dfb.png)

Then when the click *Available Updates* it brings them to:

![screenshot from 2018-05-13 19-45-30](https://user-images.githubusercontent.com/1071483/39972989-6023cc0a-56e7-11e8-84b3-b8ada59613a4.png)

which sadly makes it seem like all you can do is download the release and manually upgrade.

* Is it just installing the `/core` folder or also index.php, .htaccess and so on? I couldn't tell from the code. If the latter should we put a warning that any customizations to .htaccess or the like will be lost?

**Comment by herbdool** [comment]
Maybe we need to add ability for people to disable these updates in settings.php similar to how Wordpress does it https://codex.wordpress.org/Configuring_Automatic_Background_Updates

**Comment by laryn** [comment]
Haven't tested yet but will do so as soon as I can (looks awesome!). The screenshot brings to mind this issue: https://github.com/backdrop/backdrop-issues/issues/3039

(e.g. core updates show up under "Update Modules"? Maybe it's time just to have a single "Update" page that lists core, modules, layouts, themes...)

**Comment by olafgrabienski** [comment]
Wow, I've successfully updated a Backdrop 1.9.3 remote test site (on shared hosting) via the UI.

(Will try to do the same with another test site soon.)

**Comment by serundeputy** [comment]
@herbdool 
> swp file shouldn't be in the PR I'm guessing

  * removed; thaks

> We should change the links on the status page to point to the Update module tab instead of where it points now. Currently someone would click on the red dot at the top:

  * updated PR with link from /admin/reports/updates to /admin/modules/update
<img width="1622" alt="screen shot 2018-05-14 at 5 22 17 pm" src="https://user-images.githubusercontent.com/6763671/40024253-aa4c01a8-579b-11e8-97e6-92a0c27dac1e.png">

@olafgrabienski, @laryn, @herbdool thanks for testing; if you test further download the latest patch please:

```bash
wget https://github.com/backdrop/backdrop/pull/2186.patch
```

**Comment by klonos** [comment]
cc'ing @mbaynton

**Comment by quicksketch** [comment]
> but we should think about what to do if these files should have something relevant (security wise?), seems unlikely, but if there are ideas i'm glad to hear them

For .htaccess files (or other potential updates to root files), we typically parse them on status checks to make sure they have the needed information in them. Same thing for settings.php. If something is amiss in those core files, we have been (and should continue to) flag problems in `system_requirements()`. I also agree we should be overwriting those files, and attempting to merge/update them is a potentially messy business.

**Comment by serundeputy** [comment]
@quicksketch 

> I also agree we should be overwriting those files

did you mean you agree `we should not be` overwriting ... ?

**Comment by olafgrabienski** [comment]
@serundeputy I've tried to get the latest patch release for another test, using `wget https://github.com/backdrop/backdrop/pull/2186.patch` as recommended by you. I guess that didn't work for me, at least there was no link to `admin/modules/updates` on the *Available updates* page. The auto-update worked however, just like my test yesterday.

Maybe I didn't answer the "Assume" question during patching correctly? (The first time I answered with `n` and the patch hadn't been applied, so I started from scratch, answering this time with `y`.)

```
patch -p1 < 2186.patch
patching file core/modules/system/system.updater.inc
patching file core/includes/updater.inc
File core/modules/installer/.installer.authorize.inc.swp: git binary diffs are not supported.
patching file core/modules/installer/installer.authorize.inc
patching file core/modules/installer/installer.manager.inc
patching file core/modules/installer/installer.module
patching file core/modules/system/system.module
Hunk #1 succeeded at 2113 (offset -48 lines).
Hunk #2 succeeded at 3829 (offset -48 lines).
patching file core/modules/system/system.updater.inc
The next patch would delete the file core/modules/installer/.installer.authorize.inc.swp,
which does not exist!  Assume -R? [n] y
File core/modules/installer/.installer.authorize.inc.swp: git binary diffs are not supported.
patching file core/modules/update/update.theme.inc
```

**Comment by olafgrabienski** [comment]
Another thing: After updating, on `core/authorize.php` I read:

> **backdrop**
> Installed backdrop successfully

and

> **Next steps**
> Your projects have been downloaded and updated.
> Run database updates

I guess, "Your projects have been downloaded and updated." should move above the "Next steps" section.

**Comment by serundeputy** [comment]
@olafgrabienski since you already have a patch applied the new patch did not apply.

You'll either want to start with a fresh install of Backdrop < 1.9.5 and apply the patch

or

Figure out the answers to apply the new patch on top of the old patch.

I've just been blowing away the install and getting a new pre 1.9.5 backdrop release

you can do that with:

```bash
drush dlb backdrop --select
```

thanks for testing!

**Comment by herbdool** [comment]
@serundeputy I don't see any difference on the status report after trying your latest patch.

I think instead of linking the title "Security update required" we should make it an action: **Update Backdrop** and then we either reword "Download" to "Alternative: download" or something, or we get rid of it altogether. For those who are manually updating they already know how to get the file, everyone else will have a clear option to upgrade via the UI.

**Comment by serundeputy** [comment]
thanks @herbdool 

>  I don't see any difference on the status report after trying your latest patch.

  * the difference is that the `Security update required` text is now a link to `/admin/modules/update`

> I think instead of linking the title "Security update required" we should make it an action: Update Backdrop and then we either reword "Download" to "Alternative: download" or something, or we get rid of it altogether.

  * I just did it this way because that is what happens for modules that appear on the updates page.  That doesn't mean we have to keep it that way, but that is the way it is now. So, before changing that too much I'd like to have a consensus on the change.  Otherwise the dev (me in this case) ends up writing a lot of code that chase disparate ideas.

How we come to consensus has always been a mystery to me ;) ; let's see if others chime in.

**Comment by serundeputy** [comment]
oh; i see you are saying no change on `status report`; yep i did not change that as it already links to `admin/modules/update` and the other link goes to the updates list.  Is this not the desired behaviour?

**Comment by herbdool** [comment]
I don't see either change.

This is what I see at `admin/reports/status`:
![screenshot from 2018-05-15 11-22-21](https://user-images.githubusercontent.com/1071483/40066538-5585b5d2-5832-11e8-95a4-f11004e503db.png)
has both links going to `/admin/reports/updates` and that looks like:
![screenshot from 2018-05-15 11-22-40](https://user-images.githubusercontent.com/1071483/40066539-55a0252a-5832-11e8-8f1a-25f4171dd2ff.png)
which still looks like the old format.

**Comment by serundeputy** [comment]
@herbdool I'm guessing either the patch isn't applied (maybe it failed) or cache.  It is working for me:

![bcms-updates](https://user-images.githubusercontent.com/6763671/40070867-4fb2d576-583d-11e8-9eea-57da550765ea.gif)

**Comment by olafgrabienski** [comment]
> You'll either want to start with a fresh install of Backdrop < 1.9.5 and apply the patch

@serundeputy That's what I did. Seems to be the same issue which happens to @herbdool. Going to disable cache now.

**Comment by serundeputy** [comment]
i guess the removal of the `.swp` file is causing you folks issues with the patch.

**Comment by olafgrabienski** [comment]
Sounds reasonable! Anything we can change by ourselves there, or better wait for a revised patch?

**Comment by serundeputy** [comment]
I'm not sure why the patch works for me and not for you or @herbdool different os?

I'm on:

```bash
geoff@yep backdrop (1.x) exit code: [0] $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202
```

and the command i issue for the patch is:

```bash
patch -p1 < 2186.patch
```

**Comment by olafgrabienski** [comment]
I'm on a remote server (shared hosting), OS is Linux Ubuntu.

**Comment by olafgrabienski** [comment]
Could this notice (during patching) be of interest?

`The next patch would delete the file core/modules/installer/.installer.authorize.inc.swp,
which does not exist!`

Does it make sense to remove the `.swp` file related code of the patch?

**Comment by serundeputy** [comment]
I made a commit that removed the `.installer.authorize.inc.swp` file which i had accidentally committed on the first go round. so now this patch has a delete ref to a file that does not exist.

Maybe if you put a blank file there before applying the patch it will be happier?

```bash
touch core/modules/installer/.installer.authorize.inc.swp
```

A terrible hack, I know, not very convenient, but might get you up and testing again.

**Comment by mbaynton** [comment]
I'm glad to see concrete headway on this in Backdrop! Just to touch base, there's more overall interest and activity around this in Drupal now than in the past as well, though ambitions still far rival contributors. Hence I tihnk it's great to see simpler / custom-tailored solutions like this that work for many people and for Backdrop specifically.

Drupal's objectives, as backed by several official initiatives, include getting the Composer engine to run behind an in-browser experience, the concept of a live and inactive code tree that a small readonly "bootloader" can toggle between to make multi-file code changes totally atomic and provide some rollback capability, code signing and verification, and hopefully some of the work I did a year or so ago too :). So basically we're letting perfect be the enemy of good, but maybe the day will come where we have something really neat and worth sharing. (It's always been my goal to solve this stuff without tightly coupling it to D8 core, and I've succeeded, I think, in selling that idea.)

**Comment by serundeputy** [comment]
@olafgrabienski you could open the patch file and take out the `swp` stuff then apply the patch.

I think when I get time I'll re-roll the PR and therefore the patch to never have had the erroneously committed `swp` ☘️ 

thanks for your dedication!

**Comment by serundeputy** [comment]
@olafgrabienski @herbdool @laryn I've re-rolled the patch sans `.swp` file hopefully it will apply cleanly for you folks now and allow for testing.

Patch: https://github.com/backdrop/backdrop/pull/2201.patch

be nice to get this in so we can start working on the automatic part of it.

**Comment by serundeputy** [comment]
ugh; I'll have to look this weekend.

**Comment by laryn** [comment]
I just took a look at the patch and I think it is adding the `.swp` file and then later removing it. I tried to remove all `.swp` references (attached) and applied it to a dev site on a remote server:

```
[~/remote_dev/backdrop_html]# patch -p1 < 2201_sans_swp.patch 
patching file core/modules/system/system.updater.inc
patching file core/includes/updater.inc
patching file core/modules/installer/installer.authorize.inc
patching file core/modules/installer/installer.manager.inc
patching file core/modules/installer/installer.module
patching file core/modules/system/system.module
Hunk #1 succeeded at 2113 (offset -48 lines).
Hunk #2 succeeded at 3829 (offset -48 lines).
patching file core/modules/system/system.updater.inc
patching file core/modules/update/update.theme.inc
```

I'm not sure if the `Hunk #1` and `Hunk #2` indicate I missed some of the `swp` portions or if those are valid.

It allowed me to begin the process and seemed to download Backdrop, asked me to put it in maintenance mode, and then I had a fatal error and when I reloaded Backdrop had not updated and this was in the log:

```
UpdaterException: The info file (<em class="placeholder">temporary://update-extraction-2042941c/backdrop/profiles/testing/modules/backdrop_system_listing_compatible_test/backdrop_system_listing_compatible_test.tests.info</em>) does not define a 'type' attribute. in Updater::getProjectType() (line 194 of /remote_dev/backdrop_html/core/includes/updater.inc).
```

[2201_sans_swp.patch.txt](https://github.com/backdrop/backdrop-issues/files/2028451/2201_sans_swp.patch.txt)

**Comment by klonos** [comment]
Thanks @serundeputy and everyone else that's working hard for this. I am about to give it a go, so I should return back with more. Just wanted to quickly provide the following feedback, in case I get distracted...

> ... So if there are files outside of /core that need updating should it be flagged as can't update via UI? Or should there be a warning that people will need to do some manual steps after core is updated?

Yep, we need to find a good way to deal with this. A "flag" someplace?

> Haven't tested yet but will do so as soon as I can (looks awesome!). The screenshot brings to mind this issue: #3039

...please, do not get me started! 😄

> Edit: Corrected to say we should *not* be overwriting.

@quicksketch no you didn't 😛..."we not should" 😆

**Comment by klonos** [comment]
I have tested this on a 1.9.5 installation:

```
wget https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2186.patch
...
patch -p1 < 2186.patch
patching file core/modules/system/system.updater.inc
patching file core/includes/updater.inc
File core/modules/installer/.installer.authorize.inc.swp: git binary diffs are not supported.
patching file core/modules/installer/installer.authorize.inc
patching file core/modules/installer/installer.manager.inc
patching file core/modules/installer/installer.module
patching file core/modules/system/system.module
Hunk #1 succeeded at 2113 (offset -48 lines).
Hunk #2 succeeded at 3829 (offset -48 lines).
patching file core/modules/system/system.updater.inc
The next patch would delete the file core/modules/installer/.installer.authorize.inc.swp,
which does not exist!  Assume -R? [n] y
File core/modules/installer/.installer.authorize.inc.swp: git binary diffs are not supported.
patching file core/modules/update/update.theme.inc
```

The update was downloaded, and I was redirected to `/admin/update/ready`, but clicking the "Continue" button resulted in this error:

![screen shot 2018-06-17 at 6 29 15 pm](https://user-images.githubusercontent.com/2423362/41506202-db206c66-725c-11e8-8811-de3076e2893f.png)

...and it resulted in a totally broken installation ("Forbidden, You don't have permission to access / on this server."). I had seen this error before in the past, and it had to do with folder permissions. So I have restarted the environment and got my installation to work once again. After the restart, the installation was still on 1.9.5 and attempting to reinstall the latest 1.10.1 got me to this loop of error.

I was testing using https://github.com/beetboxvm/beetbox which is what I currently use for all my other local setups. I can give lando/ddev a go, but as @olafgrabienski, I would like to bring some environment diversity to add to the test cases. We should make sure that this works "everywhere".

@serundeputy I am looking for ways to troubleshoot this further, so can you please explain where is the new update file supposed to be downloaded and how/where does it get extracted, so I can as a first step start by verifying that these steps are actually being performed?

Thanks

**Comment by klonos** [comment]
...this repeated PHP error that was caught in the logs might be of help 😄:

```
UpdaterException: The info file (<em class="placeholder">temporary://update-extraction-90c96fad/backdrop/profiles/testing/modules/backdrop_system_listing_compatible_test/backdrop_system_listing_compatible_test.tests.info</em>) does not define a 'type' attribute. in Updater::getProjectType() (line 194 of /var/beetbox/docroot/core/includes/updater.inc).
```

**Comment by klonos** [comment]
...I think that the `[BackdropSystemListingCompatibleTestCase]` line at the top of the .info file upsets the installer. I have moved the `name = Installation profile module tests helper` above that, and it then moved to the next step, which was `/core/authorize.php`:

![screen shot 2018-06-17 at 7 45 16 pm](https://user-images.githubusercontent.com/2423362/41506746-fe41e99a-7266-11e8-8c8a-2be1149f4aa0.png)

...this is as far as I get with other modules/themes/layouts with my current setup, so that's good progress 😄. I think I'll give it a rest now.

**Comment by klonos** [comment]
...oh you know me, I simply could not leave it alone. I have tried this quickly on ddev. Same problem and same errors in the log. I have then tested a quick and dirty "fix": I have commended [this line](https://github.com/backdrop/backdrop/blob/1.x/core/includes/updater.inc#L190) out and replaced it with simply `$info['type'] = "module";`. Gave it yet another go, and everything worked just flawlessly this time!

So I guess all we have to do now is to make the installer happy with finding (or not) `type = module` in .info files of test modules.

**Comment by docwilmot** [comment]
Someone posted an issue before: https://github.com/backdrop/backdrop-issues/issues/1294

**Comment by klonos** [comment]
"Someone"?? 😆

**Comment by serundeputy** [comment]
I took a shot at a first pass at some documentation on what kinds of file permissions are required for the updates via UI to be possible are and some of the consequences. Definitely needs our docs crew to look it over and help out with wording.  It is in part based on this Drupal node: https://www.drupal.org/node/244924#automated-tools-to-set-permissions pared down and tailored for Backdrop.

I nominate: @docwilmot, @jenlampton, @quicksketch, @klonos, @mikemccaffrey, @wesruv, and Jack Aponte to have a look: https://backdropcms.org/file-permissions-and-ownership

**Comment by klonos** [comment]
I have done a first pass @serundeputy. A missing space here, some commas there to make things more readable, and we're looking good 😉

![its good](https://user-images.githubusercontent.com/2423362/44089761-a6a52340-9fd0-11e8-9a17-078cdc3599f8.gif)

**Comment by herbdool** [comment]
@serundeputy I tested this PR again. I think it works fine, though I've got a couple things that need fixing in order for it to work:

1. The PR probably has to be squashed before merging. And if people are going to test with a patch they need to manually remove the sections with the .swp file. I know you removed it but in the patch you'll see that there is both a diff to *add* the .swp binary and then another diff to *remove* it. So I presume that squashing this will ensure that this history just disappears and there will be no mention of the .swp file.
2. If people are testing with an old version of backdrop they should realize that older versions have line 114 in `update.theme.inc` line 114 wrong. It needs to reference the correct module. It should be `if ($update_link && module_exists('installer')) {` and NOT `project_installer`, which doesn't exist. The current 1.10.0 release has it right.

So a good MVP here!

**Comment by herbdool** [comment]
@klonos before testing this again, can you check the patch file? Remove all sections relating to .swp binary and patch with that.

**Comment by olafgrabienski** [comment]
On yesterday's weekly Backdrop video meeting there was a discussion if to provide core updates via UI with the 1.11 release because the feature would be much easier to test when it's in the release. In my opinion it would help a lot to have easier testing conditions. On the other hand I see a certain risk of critical issues with the core updates via UI, just because we haven't tested the feature very deeply, nor in many different hosting situations.

What about to hide the Core UI update feature somehow, or/and to give a statement in the help text that it's still in an experimental status?

**Comment by findlabnet** [comment]
Should this functionality to be mandatory, or can be disabled/skipped somehow?

**Comment by olafgrabienski** [comment]
@findlabnet The core update via Backdrop's UI isn't mandatory. You'll still be able to update Backdrop core in the usual way, replacing the old "core" directory with a newer one, as currently described here: https://backdropcms.org/upgrade#minor-updates.

That said, when we're getting closer to provide also [*automatic* core updates](https://github.com/backdrop/backdrop-issues/issues/2018), I expect a discussion about the option how to disable / skip them - see for instance https://github.com/backdrop/backdrop-issues/issues/2018#issuecomment-376959901.

**Comment by findlabnet** [comment]
So, before we sell something spare, we must to buy it?

**Comment by quicksketch** [comment]
@olafgrabienski:

> What about to hide the Core UI update feature somehow, or/and to give a statement in the help text that it's still in an experimental status?

@findlabnet:

> Should this functionality to be mandatory, or can be disabled/skipped somehow?

Yes, absolutely! I had this same thought today but you two beat me to suggesting it. Let's included this core update functionality in 1.11.0 but hide it. We can enable it by default in a later release.

We already have an `installer.settings.json` config file. We should add a new option for enabling core updates, e.g. `config_get('installer.settings', 'core_update')`.

In fact it would be great to have all of the various installation/updating options be able to be toggled (e.g. `"module_update", "module_install", "theme_update", "theme_install", "layout_update", "layout_install"`). But as we're in a time crunch, let's add the toggle for core only and expand that out later. Our primary concern here is just making it so that we can test this after release with a real example and the whole system together.

So we need the following:

- Add `core_update: false` to `installer.settings.json`.
- An update hook to set the default to `false` for existing sites.
- A conditional check ensuring `config_get('installer.settings', 'core_update')` is TRUE before allowing any core updates.

At this point, I don't think any UI for toggling the option is needed.

**Comment by olafgrabienski** [comment]
> At this point, I don't think any UI for toggling the option is needed.

How would I enable the feature for testing purposes: just change a configuration file?

**Comment by serundeputy** [comment]
squashed commits to remove `*.swp` from git history; https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2201.patch

**Comment by herbdool** [comment]
@olafgrabienski yes, you'd have to edit the installer.settings.json file.

**Comment by herbdool** [comment]
@serundeputy as per @quicksketch suggestion, I've created a PR https://github.com/backdrop/backdrop/pull/2289

**Comment by quicksketch** [comment]
I've tested out @herbdool's additions at https://github.com/backdrop/backdrop/pull/2289 and they look great! As we've already tested this prior to the disabling option, I think we're good to go here.

I've merged in https://github.com/backdrop/backdrop/pull/2289. Thanks everyone, especially @serundeputy for his direct and simple approach to this problem. This is an exciting development and I'm so glad we came up with a way to proceed on this. Woot!

**Comment by quicksketch** [comment]
Follow-up to enable after 1.11.0 is released: https://github.com/backdrop/backdrop-issues/issues/3271

**Comment by serundeputy** [comment]
Wow! went to work on this today and it's merged! Amazing job everyone!

**Comment by docwilmot** [comment]
As a followup to this, can we move all update links to one place please? Like a top-level `Updates` link on the Admin bar, which links to a page with Layout, Module, Theme, and Core tabs or fieldsets. The current UI is confusing. Core updates is appearing under the Update Themes page, etc.

**Comment by jenlampton** [comment]
@docwilmot 	I think we have an issue for that...  Maybe https://github.com/backdrop/backdrop-issues/issues/2714 ?
