### ISSUE TITLE
Warning: require_once(..\backdrop\core/core/includes/bootstrap.inc): failed to open stream: No such file or directory in ..\www\backdrop\index.php on line 19

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#311]
I got this error when trying to run the db update script. I am on Windows upgrading from a build that I downloaded on Aug. 02 to a fresh one I just downloaded today.

Is this something you'd care to fix or do we NOT support alpha2alpha/head2head upgrades?

BTW, notice the ```...\core/core/...``` part of the path there? Could be related to #265 (?).

**Comment by klonos** [comment]
Irrelevant now. Closing...

**Comment by quicksketch** [comment]
Thanks for opening and closing. :smile:
