### ISSUE TITLE
[UX] Include time interval in the scheduling publish status message

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3113]
## Describe your issue or idea

When scheduling content to be published, we currently show a message such as `Post will be published on Thursday, Jan 1, 2018`, using the "medium" date format from the site. We should include a time increment there as well, to help identify exactly when content will be published. This is useful for same-day publishing or scheduling something late at night for an early morning publish.

---

PR https://github.com/backdrop/backdrop/pull/2190

**Comment by quicksketch** [comment]
My recommended message is adding `(@interval from now)` to the current message. Such as this:

![image](https://user-images.githubusercontent.com/100206/40036357-e8ead838-57bb-11e8-9b38-ba5fb6f2441a.png)

**Comment by klonos** [comment]
Looks good 👍 RTBC!

**Comment by klonos** [comment]
...last minute nit-picking:

- perhaps better to have the message include the content title in it
- "will be published on" sounds too optimistic if we consider the limitations we have with cron. Perhaps "is scheduled to be published on" is more accurate :)

**Comment by quicksketch** [comment]
I'll take the RTBC and merge what we have for now. I merged https://github.com/backdrop/backdrop/pull/2190 into 1.x for 1.10.
