### ISSUE TITLE
[UX] "Default is the link or file identifier" text is unclear

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3120]
## Describe your issue or idea

After adding the file-upload in the Insert link dialog, I noticed the description text on the `Link text` field was 'Default is the link or file identifier. Enter some alternative link text here if needed.'   I'm not sure what this means. I'd love to get to the bottom of the intent with this text, and choose some clearer language.

<img width="627" alt="screen shot 2018-05-15 at 2 17 57 pm" src="https://user-images.githubusercontent.com/397895/40084069-caf1cd02-584a-11e8-87c6-72a1b4d05f91.png">

**Comment by jenlampton** [comment]
> Maybe we shouldn't have any explanation here, just let the user discover this?

In this case, I'd be in favor of that, actually. Good suggestion!

**Comment by quicksketch** [comment]
Great, agreed the help text is not helpful here. The label is clear enough by itself. Merged https://github.com/backdrop/backdrop/pull/2196 into 1.x and 1.10.x.
