### ISSUE TITLE
Notice: Undefined index: description - Backdrop 1.10.0 

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#3125]
## Describe your issue or idea
After update to 1.10.0 in dblog
`Notice: Undefined index: description in block_block_info() (line 115 of /.../core/modules/block/block.module).`
### Steps to reproduce (if reporting a bug)
Existing custom block have not value for new field "Admin description"
After fill it in and save - all OK.
### Actual behavior (if reporting a bug)
Any request to site generate notice.
### Expected behavior (if reporting a bug)
Check field if not empty.

**Comment by opi** [comment]
Introduced in bce9f4593a

Fixed by PR https://github.com/backdrop/backdrop/pull/2194

**Comment by quicksketch** [comment]
Thanks! I reset the $block_info array in your PR to be safe that we don't accidentally mix up items each time through the loop. Marking RTBC for merging after next test run finishes.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2194 into 1.x and 1.10.x for 1.10.1.
