### ISSUE TITLE
'Available Updates' page recommends beta release over stable release

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3128]
I have the [Auto Menu Settings](https://backdropcms.org/project/auto_menu_settings) module installed on a few sites and, on the 'Available Updates' page (/admin/reports/updates), they all recommend 'updating' from 1.x-1.0.0 to 1.x-1.0.0-beta1.

Clearly the beta version came out first, then the stable release later. The stable release (that I have installed) should be the recommended version and so I shouldn't get any update notifications.
What have I done wrong with releasing this module?

[I thought this issue already existed somewhere, but I couldn't find it... Please mark as duplicate if you find the original, or let me know if I need to post this elsewhere instead.]

**Comment by quicksketch** [comment]
Everything looks good as far as how the module is set up... Releases are all good and the beta version is dated before the final version. The right version shows up on the project page (https://backdropcms.org/project/auto_menu_settings). However, it looks like there is a problem with the project release history feed. This is where update.module checks for newer versions:

https://updates.backdropcms.org/release-history/auto_menu_settings/1.x

Update module is a bit dumb and doesn't do any version checking itself to determine what the latest release is, it uses the order provided by backdropcms.org. So the problem we have here is that the feed has them in the wrong order. The latest release should be at the top. I'll look into why this is.

**Comment by BWPanda** [comment]
So looks like this was addressed at https://github.com/backdrop-contrib/project/pull/23 ?

**Comment by quicksketch** [comment]
Yep, it was fixed in project module. But I just now deployed the new version to backdropcms.org. It should be fixed now. My local is now showing 1.0.0 as the recommended version:

![image](https://user-images.githubusercontent.com/100206/40823603-c3af0b12-6525-11e8-8920-77533a3d457c.png)

**Comment by BWPanda** [comment]
@quicksketch Yay! Works for me too. Thanks so much!
