### ISSUE TITLE
[DX] Updated documentation for `hook_schema_alter()`.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3129]
The documentation for [`hook_schema_alter()`](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_schema_alter/1) needs updating to mention that updating the schema for a module requires also calling `hook_install()`.

---

I'm writing a module which adds a field to the `node` table. I implement `hook_schema_alter()` in my install file, but when I install my module, the node table isn't updated and I get errors along the lines of:

> PDOException: ... Column not found: ...

The only place I can find where `hook_schema_alter()` is used in core is the comment module, and when I look at that I notice that it not only implements `hook_schema_alter()` in its install file, but it also implements `hook_install()` where it adds the field if it doesn't exist already.

Is implementing `hook_install()` in addition to `hook_schema_alter()` a requirement? If so, the documentation should be updated to reflect this (there's nothing mentioned [here](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_schema_alter/1)).

**Comment by BWPanda** [comment]
Ok, so after playing with this a bit, it seems that implementing `hook_install()` and also `hook_uninstall()` in addition to `hook_schema_alter()` is necessary to get this working properly, to both add the new field on install, and remove it on uninstall.

I'd have thought that that was what `hook_schema_alter()` would have done automatically...

If someone with more knowledge about this can confirm (and maybe explain why this is), I'll convert this into an issue for updating the documentation for `hook_schema_alter()`.

**Comment by herbdool** [comment]
Yup, I added that column to the comment module in the last version! I think your latter interpretation is closer to the mark, given what I recall of searching for info related to this hook.

**Comment by BWPanda** [comment]
Ah, just found this documentation for [backdrop_install_schema()](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_install_schema/1):

> Creates all tables defined in a module's [hook_schema](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_schema/1)().
>
> Note: This function does not pass the module's schema through [hook_schema_alter](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_schema_alter/1)(). The module's tables will be created exactly as the module defines them.

**Comment by BWPanda** [comment]
Here's a PR to update the documentation: https://github.com/backdrop/backdrop/pull/4125

**Comment by bugfolder** [comment]
PR currently says:

```
... [the module] should also implement hook_install() (and
  * possibly hook_uninstall()) to perform the alterations manually. See
  * comment.install for an example.
```

Minor wording nit-pick: if the module is doing things automatically in an update hook, then it isn't performing the alterations "manually." So how about (ignoring line breaks for the moment):

```
... [the module] should also implement hook_install() (and
  * possibly hook_uninstall()) to perform the alterations in those functions. See comment.install for an example.
```

**Comment by BWPanda** [comment]
By 'manually' I meant as opposed to all this happening automatically like I was expecting just by implementing `hook_schema_alter()`. But yes, if it's confusing we can change the wording.

**Comment by BWPanda** [comment]
PR updated.

**Comment by bugfolder** [comment]
Looks good to me. RTBC.

**Comment by quicksketch** [comment]
Thanks folks! I found the new description to be quite helpful! I merged https://github.com/backdrop/backdrop/pull/4125 into 1.x and 1.22.x.
