### ISSUE TITLE
[D8] Create a new 'Assign user roles' permission

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#313]
The only way to allow someone to assign roles when editing a user currently is to grant them the "administer permissions" permission.  This is a lot of power for someone who may not know the implications of what they are doing. 

Lots of times you have high-level admins who know that Sally should be an editor but Jake is only a contributor, even if they don't know the extent of permissions assigned to each role.

These people should be allowed to grant/assign roles with a new, separate permission.

Current solutions to this problem include:
https://www.drupal.org/project/roleassign
https://www.drupal.org/project/role_delegation
https://www.drupal.org/project/administerusersbyrole
https://www.drupal.org/project/drupal/issues/267342 (D8 core, which makes this part of #378)

**Comment by MrHaroldA** [comment]
Based on Drupal's "Reported installs", role_delegation is a clear winner. It also has tests included, so I guess that would be the best candidate for a merge into Backdrop core.

**Comment by klonos** [comment]
> ...role_delegation is a clear winner

I think so too. It has fine-grained delegation control by allowing to select which rolls can assign which...

## Using [RoleAssign](https://www.drupal.org/project/roleassign) (two-step procedure)

![roleassign-settings](https://cloud.githubusercontent.com/assets/2423362/8466964/cb240c52-209b-11e5-8a22-33a2bd3ec032.png)

![roleassign-permissions](https://cloud.githubusercontent.com/assets/2423362/8466972/e0dbb86a-209b-11e5-9b34-358f5d703a89.png)

## Using [Role Delegation](https://www.drupal.org/project/role_delegation)

![role_delegation](https://cloud.githubusercontent.com/assets/2423362/8467087/3819e3ee-209d-11e5-970a-f34c1bc130ac.png)

![role_delagation-roles_tab_in_user_ profile_page](https://cloud.githubusercontent.com/assets/2423362/8467245/44e6e570-209f-11e5-9daa-edd8cb687426.png)

**Comment by quicksketch** [comment]
I'm not sure about either of these solutions. Both seem rather complicated. Could we only include the single permission for "assign roles" and then leave the rest to contrib?

**Comment by MrHaroldA** [comment]
@quicksketch, that's exactly how I did it in my PR ;)

I only have to fix, and add some tests ... if I'm correctly implementing it.

https://github.com/backdrop/backdrop/pull/988

**Comment by quicksketch** [comment]
@MrHaroldA Oh, excellent :+1: 

We've got some discrepancy between "assign all roles" (the machine name) and "assign any role". I suppose that could prevent a conflict with a contrib module that named permissions "assign [role_name] role", in the event that there was a role named "any".  Do you have any feelings one way or the other?

**Comment by MrHaroldA** [comment]
That's why I've used 'roles' instead of 'role', to prevent users adding 'any' as role ...

I've also thought about removing it, and just use 'administer users' instead.

**Comment by klonos** [comment]
...for clarity it could be "assign role: [role_name]" instead, which would make it "assign role: any". Just thinking out loud here.

**Comment by MrHaroldA** [comment]
@klonos, I've thought about using the node permission naming too: "Article: Delete any content", but that would result in "Administrator: Assign role" ... also quite weird.

**Comment by klonos** [comment]
@MrHaroldA how about the reverse? So, "Delete any content: Article" and thus "Assign role: Administrator".

**Comment by MrHaroldA** [comment]
"Delete Artice" and "Assign Administrator role" seem way more logical ...

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/988 still needs some work. We won't see this in 1.2.0, but maybe 1.3.0?

**Comment by klonos** [comment]
What can we do... :disappointed: ...still, we've accomplished a great lot for 1.2.0!!

**Comment by docwilmot** [comment]
isnt this done?

**Comment by jenlampton** [comment]
Yes! :) thanks @docwilmot

**Comment by klonos** [comment]
FTR, this was "subtly" introduced with the fixes that went in for #2576, in https://github.com/backdrop/backdrop/pull/1806/files#diff-0d9bd97d91568a099e773bc296444be2

**Comment by jenlampton** [comment]
oops, we should have caught that!

**Comment by klonos** [comment]
Yeah, maybe for posterity we should add it to the release notes in https://github.com/backdrop/backdrop/releases/tag/1.6.3 @jenlampton?
