### ISSUE TITLE
Layout module revision in 10.0 is causing failure.

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#3130]
I have a site that uses Views to generate pages using data from a specified node. One example is a page with path `eventreport2/%`. This is displayed by a layout specifically for this path. On the configure layout admin page the Context is set to 'Position 2:eventreport2/%' and the Type then automatically becomes 'string pass-through'.

Such pages with custom layouts are no longer being displayed after update to 10.0 and the log shows two reports
`Notice: Undefined index: load callback in layout_get_layout_by_path() (line 1082 of layout.module)`
and
`Error: Function name must be a string in layout_get_layout_by_path() (line 1083 of layout.module)`

I have fixed this temporarily by reverting to the previous version of layout.module, i.e. before Issue #3004.

Note: I am not using the Taxonomy module which was perhaps the reason for #3004.

**Comment by quicksketch** [comment]
Fixing this is pretty simple, we should just check if a "load callback" is specified before attempting to call it. Right now it looks like it's `NULL` in @Graham-72's example. PR at https://github.com/backdrop/backdrop/pull/2214 adds a simple check.

**Comment by quicksketch** [comment]
Additional test now added to ensure string pass-through arguments work as expected.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2214 into 1.x and 1.10.x.
