### ISSUE TITLE
BootstrapDestinationTestCase fails under Debian 9 + PHP 7 + Apache 2.4.25

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#3131]
## Describe your issue or idea
A few tests in BootstrapDestinationTestCase fail in my local environment, but they pass in the CI environment. 

### Steps to reproduce (if reporting a bug)
Create a Debian 9 VM with Apache 2.4.25, PHP 7, and MariaDB (see packages.txt below.)

Set up the database and webserver as appropriate.

MySQL: `create database backdrop default char set 'utf8'; grant all on backdrop.* to back@localhost identified by 'drop'; flush privileges;`

Install with `sudo -u www-data php core/scripts/install.sh --db-url=mysql://back:drop/localhost/backdrop`

Run the tests with `sudo -u www-data php core/scripts/run-tests.sh --color --verbose --url http://backdrop.vm --concurrency 8 --force BootstrapDestinationTestCase` 

### Actual behavior (if reporting a bug)
[backdrop-tests.txt](https://github.com/backdrop/backdrop-issues/files/2017199/backdrop-tests.txt)

Tracing through the tests, the `CURLOPT_POSTFIELDS` carries the `destination` information, which shows up in bootstrap.inc as part of the `$_POST`, but not the `$_GET`.  When we get to the fragment below (core/includes/bootstrap.inc:3186), there is no `$_GET['destination']` to parse.

```php
    // If there is a query string, check its query parameters.
    $destination_parts = backdrop_parse_url($_GET['destination']);
    if (!empty($destination_parts['query'])) {
      $sanitized_keys = _backdrop_bootstrap_sanitize_input($destination_parts['query'], $whitelist);
    }
```

### Expected behavior (if reporting a bug)
All tests pass.

### Relevant version/system information (if applicable)
`dpkg -l | egrep "(apache|mysql|maria|php)"`: [packages.txt](https://github.com/backdrop/backdrop-issues/files/2017206/packages.txt)

**Comment by indigoxela** [comment]
@jlfranklin does the problem still occur?

I wasn't able to reproduce, but my setup is slightly different:

- Debian 10
- MariaDB 10.3.25
- PHP 7.0 (also tried with 7.4)

If I run your command all tests pass here.

```
Backdrop test run
---------------

Tests to be run:
 - URL destination validation (BootstrapDestinationTestCase)

Test run started:
 Saturday, November 14, 2020 - 3:22pm

Test summary
------------

Bootstrap: URL destination validation (BootstrapDestinationTestCase) 27 passes, 0 fails, 0 exceptions, and 7 debug messages. [8.762s]
```

**Comment by jlfranklin** [comment]
The tests pass in my environment, too.
