### ISSUE TITLE
[UX] Sort "Available Updates" page in the same way as the "Status Report" page

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3132]
## Describe your issue or idea
Right now the "Available Updates" page sorts alphabetically, which is understandable although not super clear when you are looking to see what updates are available. We've resorted the "Status Report" page to have issues first sort by priority and then alphabetically – can we do the same for "Available Updates"? 

e.g. security updates show first, then bug fix updates, then current.

---
PR by @laryn: https://github.com/backdrop/backdrop/pull/2812

**Comment by klonos** [comment]
@laryn 👍 for this, but a couple of questions:

1. were you thinking to ditch the grouping by type (core/module/theme)?
2. we'd still want core to be at the top of the list, right?

**Comment by laryn** [comment]
@klonos 
1. No, not necessarily
2. Yes, it makes sense to keep core at top

**Comment by laryn** [comment]
Here's a screenshot of **Reports > Available Updates** with a few selected outdated modules installed to show the sort:

![Screen Shot 2020-08-24 at 9 07 22 AM](https://user-images.githubusercontent.com/871421/91054171-538b4c00-e5e9-11ea-9063-38a50bb5db5c.jpg)

**Comment by olafgrabienski** [comment]
Nice! I've installed a couple more modules in the sandbox website to check the alphabetical sorting within the different categories. Looks good:

![screen-backdrop-pr-2812-available-updates](https://user-images.githubusercontent.com/14188307/91056442-450f5580-e626-11ea-9e76-df2fdfe08c38.png)

**Comment by BWPanda** [comment]
Very nice! This looks much better! Thanks for suggesting this @laryn and writing the PR. Thanks also to @olafgrabienski and @klonos for testing. I've merged https://github.com/backdrop/backdrop/pull/2812 into 1.x.
