### ISSUE TITLE
Module `.info` files version requirements don't understand `-dev` versions

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3135]
## Describe your issue or idea
When adding version requirements to a module's `.info` file, it doesn't seem to understand how to handle `-dev` (and possibly `-beta` etc.).

From @herbdool on Gitter in relation to [`save_draft`](https://github.com/backdrop-contrib/save_draft):
> Requires: System (>=1.10.0) (incompatible with version 1.11.x-dev)

I changed it to require `>1.9.99` in an attempt to fix this (albeit in an ugly way) but in my testing it is not working 100%. It seems to work if I manually update `system.info` and put `version=1.10.x-dev` but fails if I put `version=1.11.x-dev`.

This Drupal thread is related:
https://www.drupal.org/project/drupal/issues/1013302

**Comment by klonos** [comment]
Trying to install Save Draft 1.x-1.4.2 on latest Backdrop 1.10.x-dev:

![screen shot 2018-05-24 at 9 06 49 am](https://user-images.githubusercontent.com/2423362/40455815-ea3c65ee-5f31-11e8-8836-9a5ffa30de69.png)

**Comment by quicksketch** [comment]
Two separate problems here:

- @klonos: installer.module does not handle version checking _at all_. So no matter what version is required in the .info file, any requirement at all will cause it to think there are unmet dependencies.
- @laryn's problem affects the normal /admin/modules page, and only deals with -dev releases.

A 3rd version checking problem is that we do not currently handle alpha/beta/rc/preview releases.

So to fix all problems here, we should:

- Start interpreting indicator strings such as `-dev`, `-beta`, etc. into numbers so version_compare() can handle them.
- Add support for checking versions to `installer_browser_installation_enable_form()`, using the same functions as are used on the module listing page.

**Comment by laryn** [comment]
Is this related at all?

> Module/release question. How does it choose which version to highlight? Specifically curious about this module right now, which presents 1.1.1 as the default but also lists 2.0 as an option: https://backdropcms.org/project/scrollreveal

**Comment by quicksketch** [comment]
@laryn No, not related. Right now setting the default branch requires an admin permission on b.org, though that's something we could improve by pulling that information from the default branch on Github, or allowing normal b.org users to administer projects. I've fixed it for that project. Page for that setting is https://backdropcms.org/node/143/edit/releases for posterity.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/2211 that fixes all the problems. It might be too ambitious.

- Adds support for properly checking `-dev` versions (assuming dev is always the latest).
- Adds support for comparing alphas, betas, previews, and rcs against each other.
- Makes installer.module support version checking in the built-in module enabling form.
- Adds support for checking Git checkout versions.

**Comment by laryn** [comment]
@herbdool made some [comments](https://github.com/backdrop/backdrop/pull/2211#issuecomment-392300611) in the PR itself.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2211 into 1.x and 1.10.x. Thanks @herbdool, @laryn, and @klonos!
