### ISSUE TITLE
[UX] update the page title on the manage displays admin pages

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3141]
## Describe your issue or idea

After fixing https://github.com/backdrop/backdrop-issues/issues/2681 I noticed that the page title for both the Teaser display and the Default display of posts is simply `Post` which is not very helpful.

I'd love to add a title callback for these menu entries so the page title can be something like `Post: Default display` or  `Post: Teaser display`.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2288 looks great. Merged into 1.x and 1.10.x. Thanks!
