### ISSUE TITLE
[UX] Indicate "Scheduled" in main content page instead of just "Not published" or "Published"

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3145]
The main content management page gives no indication that content has been scheduled. It would be good to indicate in the Status column that it is not simply "Not published".

![screen shot 2018-05-17 at 3 28 45 pm](https://user-images.githubusercontent.com/871421/40202384-6714cc32-59e7-11e8-9795-47e726da0a55.jpg)

---
PR by @laryn: https://github.com/backdrop/backdrop/pull/2208

**Comment by laryn** [comment]
Comment from @quicksketch:

> That is not trivial to set up in Views currently because the status of the node is either 0 or 1. A scheduled piece of content has a status of 0 but a scheduled property that is a timestamp, so we'd need to combine these two fields to determine if content is unpublished, published, or scheduled.

**Comment by laryn** [comment]
So in Views we could pull two fields and use them as follows:

-`scheduled` (Exclude from display. If it exists, rewrite as "Scheduled"; if it is empty, rewrite as "Draft" to match the new language that came in with scheduling, instead of "Not Published")
- `status`  (count 0 as empty, if this exists rewrite as "Published"; if empty, rewrite as `scheduled` value)

**Comment by laryn** [comment]
Added a PR to test in a sandbox.

**Comment by quicksketch** [comment]
Impressive! Though what should we do about the exposed filter?

**Comment by laryn** [comment]
Ay, there's the rub!

**Comment by docwilmot** [comment]
> Ay, there's the rub!

Indeed. Either:
1. a bulk actions form that presents all selected nodes and offers a single date field to apply to al of them as their schedule date. 
2. a very complicated bulk actions form that presents all selected nodes in a table with a separate date field for each.

I say 1 sounds more reasonable, certainly simpler, but 2 more likely to be what a user would expect in a bulk form.

**Comment by laryn** [comment]
@quicksketch @docwilmot @herbdool Here's an alternative that still keeps Scheduled and Draft in the same "Unpublished" bucket (so perhaps the dropdown could remain as is). Also updates the date format to match the "Updated" date format. Thoughts?

![screen shot 2018-05-29 at 12 14 11 pm](https://user-images.githubusercontent.com/871421/40674313-0cac19e2-633a-11e8-89c1-14e9c93bc716.jpg)

**Comment by docwilmot** [comment]
@larynx that is an improvement, but people will certainly want to filter by nodes scheduled to be published. I don't think we can escape crafting a handler to allow that.

**Comment by quicksketch** [comment]
If we were to update the filter, what would be the functionality? Just adding "Scheduled" to the "Published" select list? That seems like it may actually cause problems because if I selected "Unpublished", I might not be able to find content that is Scheduled (though Scheduled content is also unpublished). Is that being pedantic or an actual usability problem?

**Comment by klonos** [comment]
Do you guys think it's high time we introduced multi-select pill buttons in core, like Bootstrap v4?: http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

...that way we could make that dropdown a **Published** | **Draft** | **Scheduled** triplet, and people could select one, multiple, or none.

**Comment by klonos** [comment]
...btw, short term, I find the current direction in the PR an improvement. Good job @laryn 👍

**Comment by laryn** [comment]
Just updated the PR. Still missing the update hook (I need help there on how to update a view on an existing install) and I haven't done anything with the filters, which could be a separate issue if we want to break it out.

I thought we might be able to expose the "Scheduled date" field as a select list of grouped filters (e.g. Scheduled publication: Not scheduled (default), All scheduled content, Within the next week, Within the next month...) but the exposed/group filter option doesn't seem to work with a date field. That may be a bug -- I can file separately, and then if people like that possibility (ie. breaking the filter under discussion into two: Published (yes/no) and Scheduled (select options)) it could be added here when the bug is fixed.

**Comment by herbdool** [comment]
You can take a look at the latest release for webform for an example. I update a view.

**Comment by herbdool** [comment]
I say it is an improvement as is and we could settle on this as a first iteration. Unless we've got time and energy to also work on the filters. But I like to prevent overloading any issue which could prevent anything from being accepted.

**Comment by laryn** [comment]
@herbdool I copied your webform update hook and made a few modifications. Thanks!

**Comment by herbdool** [comment]
@laryn since we're not certain on the best way to do the filter, I propose a possibly more useful layout for the main table:

![screenshot from 2018-08-27 00-23-43](https://user-images.githubusercontent.com/1071483/44640395-7dc0b980-a98f-11e8-9e91-f551f923f1f3.png)

If we separate out the published/not published and the scheduled date into separate columns then at least people can sort by the scheduled date if it exists. I've modified the view slightly to reflect that.

(By the way, it should be "Not published" and not "Unpublished" since that's the original language.)

Then I suggest in a follow-up issue we address the exposed filters.

**Comment by herbdool** [comment]
@laryn did you file that error for trying grouped filters for date fields? I noticed it too and tried it on other date fields:

```
Notice: Undefined index: #states in views_handler_filter->build_group_form() (line 963 of /app/core/modules/views/handlers/views_handler_filter.inc).
Warning: Invalid argument supplied for foreach() in views_handler_filter->build_group_form() (line 963 of /app/core/modules/views/handlers/views_handler_filter.inc).
```

**Comment by herbdool** [comment]
@laryn might have something to do with https://www.drupal.org/project/date/issues/1876168 though patch hasn't been accepted yet.

**Comment by laryn** [comment]
@herbdool Thanks, I like the changes to the layout that you propose! I don't think I ended up filing the error but can do it now.

**Comment by herbdool** [comment]
@laryn I can give you an export of the view so you can update your PR if you like.

**Comment by laryn** [comment]
@herbdool Just tried to update that View and reboot the sandbox.

**Comment by herbdool** [comment]
Thanks @laryn! Looks great.

**Comment by klonos** [comment]
Sorry for coming late to the party. I have to say that I find the separate column for scheduled kinda extraneous (because it is just another type of unpublished). Were there technical restrains for making the decision? Was it the issue with the date exposed filter? If so, then we can still leave the status/scheduled column as one, and add the exposed filter for the date at a later point.

PS: ...I do not like the random ordering of the exposed filters + some other issues with them:

- There is no exposed filter for searching by author
- Exposed filters should match the order of the columns of the table. So: Title contains | Type | Author (to be added) | Status

I thought that we already had a ticket for fixing those. If not, could we perhaps squeeze these changes in the same PR (would avoid the need for additional update hooks for the same view).

**Comment by herbdool** [comment]
@klonos https://github.com/backdrop/backdrop-issues/issues/3145#issuecomment-394328082 and https://github.com/backdrop/backdrop-issues/issues/3145#issuecomment-416110792.

I'll also add that the separate field for date is more user-friendly as well. It looks ungainly combined with select options and there's no way to sort by scheduled date.

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...perhaps I am misunderstanding these comments, but both seem to be referring to the hurdles of trying to implement filtering by scheduled date/range. Given the known bug with the date exposed filters, I think that this should be a separate follow-up ticket.

Having said that, are we trying to implement the minimum achievable functionality? ...i.e. being able to filter by scheduled (indifferent to date), and then being able to sort the column by date?

**Comment by herbdool** [comment]
@klonos so you're suggesting leave out the scheduled date entirely for now? That would be in keeping with the title of the issue I guess.

@laryn and I were discussing above was what could we easily do that didn't involve a filter. Laryn had rewritten the status field to include the scheduled date. I argued that it looked (and functioned) better as a separate column. Opinions will vary of course. If there are no scheduled dates, the column doesn't appear.

**Comment by klonos** [comment]
> ...so you're suggesting leave out the scheduled date entirely for now?

Yes, especially if there are known bugs with the date module that need to be sorted first. It can be a follow-up ticket for after the issues are sorted. That way we will not hold this ticket.

> ...Opinions will vary of course. If there are no scheduled dates, the column doesn't appear.

Yeah, I get that. It just seems a waste of horizontal space to have an entire column ...especially when there is only one or just a few scheduled nodes. I am referring to visual comparison of the screenshots/mockups in https://github.com/backdrop/backdrop-issues/issues/3145#issuecomment-392862483 vs https://github.com/backdrop/backdrop-issues/issues/3145#issuecomment-416110792

**Comment by herbdool** [comment]
I agree with @laryn.

By the way the bug found was only for grouped filters and not for a date field directly.

**Comment by klonos** [comment]
>... If you've scheduled 10 posts, it seems clear you'd like to be able to scan them in the order they will be published.

@laryn if we keep the status as "Unpublished (Scheduled for `[date]`)" as per the screenshot in https://github.com/backdrop/backdrop-issues/issues/3145#issuecomment-392862483, then one should be able to filter by status "Scheduled" and also sort the "Status" column. Right?

**Comment by laryn** [comment]
@klonos There is no way to filter on "Scheduled" currently, since it doesn't have a dedicated value of its own to use in the exposed filter (1 = published; 0 + no scheduled date = unpublished; 0 + scheduled date = scheduled). So for the limited scope of this ticket we were aiming to leave the filters alone, and open a new ticket to handle other improvements.

The sort you describe would work for the most part but is not bulletproof. If the date format is changed, the sort could become hard to understand (e.g. if someone adjusts the "Short date" format to show dd-mm-yy then the sorting results will be strange, I think).

**Comment by herbdool** [comment]
@laryn good point, I hadn't thought of that. Plus a date format like "January 12, 2018" would end up sorting alphabetically instead of by date. Which is not what we want.

**Comment by klonos** [comment]
>There is no way to filter on "Scheduled" currently, since it doesn't have a dedicated value of its own to use in the exposed filter (1 = published; 0 + no scheduled date = unpublished; 0 + scheduled date = scheduled). So for the limited scope of this ticket we were aiming to leave the filters alone, and open a new ticket to handle other improvements.

@laryn that makes so much sense now. Thanks 👍

@herbdool also very valid points 👍

**Comment by quicksketch** [comment]
I'm all in favor of handling the exposed filter question later. In the PR, I found that we're pulling in the view configuration directly from the default config file. I don't think we can do this as the view configuration may change in the future. Other places where we've needed to create or update views, we have to update the config explicitly through PHP code. I tried to post a reason of why this is to the question @klonos asked a while back: https://github.com/backdrop/backdrop-issues/issues/3347

**Comment by herbdool** [comment]
I updated the PR to add the PHP array version of the json file to the update hook. Then I had a git conflict so I created a duplicate PR https://github.com/backdrop/backdrop/pull/2450 which resolves it (had to fix update hook number).

**Comment by quicksketch** [comment]
Thanks @herbdool! I've merged https://github.com/backdrop/backdrop/pull/2450 into 1.x for 1.12.0. Thanks @laryn, @docwilmot, and @klonos for your work on this issue!

**Comment by quicksketch** [comment]
Because this requires an update hook and potentially changes the UI, I've only merged this into 1.x for 1.12 and not into the 1.11.x.
