### ISSUE TITLE
[UX] Reduce status messages when a node is scheduled

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3150]
## Describe your issue or idea

When scheduling content, you currently get two messages that are somewhat redundant. We should reduce these messages so only a single message is present when a node is created/updated/scheduled.

### Steps to reproduce

- Create a Post. Schedule it in the future.

**Comment by quicksketch** [comment]
Before (scheduling new content):
![image](https://user-images.githubusercontent.com/100206/40568032-f92c03ec-602c-11e8-8af6-1bc2fddbf291.png)

Before (scheduling previously published content):
![image](https://user-images.githubusercontent.com/100206/40568013-e4090e42-602c-11e8-9d57-973812554840.png)

---

After (scheduling new/unpublished content):
![image](https://user-images.githubusercontent.com/100206/40567967-aab8dc1c-602c-11e8-9b80-e3bcd085dd69.png)

After (scheduling previously published content):

![image](https://user-images.githubusercontent.com/100206/40567974-b5592d66-602c-11e8-9174-7566595b2ef0.png)

---

Messages for normal published/unpublished content stays the same, with no indication of changing between states. Just "Page %title has been created/updated." as before. I think dealing with all transition states is a thorny area, but transitions to scheduled we should continue to describe, as they have the highest potential for confusion.

**Comment by docwilmot** [comment]
Yes this is better. RTBC.

**Comment by quicksketch** [comment]
Thanks @docwilmot! Merged https://github.com/backdrop/backdrop/pull/2210 into 1.x and 1.10.x. All tests still passing with these changes.
