### ISSUE TITLE
[UX] Improve description for block admin description field

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3152]
## Describe your issue or idea

When adding a reusable custom block, there's a field for `Admin description` that has some text beneath it that reads `Used in administrative interfaces and not shown to end-users.`

<img width="558" alt="screen shot 2018-05-29 at 10 14 21 am" src="https://user-images.githubusercontent.com/397895/40674349-680b0e30-6329-11e8-92c3-0aa8676695fe.png">

I'd love it if we could remove the technical term `end-users` from the description text and come up with something a little more human here. 

`This text is used in administrative interfaces and will not be displayed publicly.`

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2216

**Comment by klonos** [comment]
The most common non-technical term for "end-users" is "site visitors" 😄

**Comment by quicksketch** [comment]
Looks good to me. Thanks @klonos! I definitely prefer "site visitors" over "publicly", as public/private can get complicated. Not all content is public but it may still be shown to visitors (e.g. members-only content). I've merged this into 1.x and 1.10.x.
