### ISSUE TITLE
Remove image handling from the color module

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#3153]
## Describe your issue or idea
Currently, the color module has a large amount of code and settings to allow it to alter the colors of images provided by the theme. This code was added to the module to handle gradients and rounded corners from before those things were supported in CSS. Now that we have border radius, gradients, SVG images, and icon fonts that can handle most use cases directly in CSS and HTML, this code is no longer needed.

As far as I am aware, Garland was the only published theme to ever use these features in the color module.

**Comment by herbdool** [comment]
Hard to test the removal of functionality but I reviewed the code.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2215 into 1.x for 1.11.

Also filed a change record for removing this capability at https://api.backdropcms.org/change-records/image-manipulation-support-removed-color-module.
