### ISSUE TITLE
Backdrop 1.10.1 Bug Fix Release

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3154]
Backdrop 1.10.1 Bug Fix Release
==================================

It's been 2 weeks since 1.10.0 came out, so it's time to make 1.10.1 to resolve the known issues and push the 1.10 version out to Pantheon/Platform.sh upstreams.

## Pre-release tasks

- [x] Merge commits (@quicksketch)
- [x] Create a new bugfix release (@quicksketch)
- [x] Create the next bugfix milestone (@quicksketch)
- [x] Move all unfinished issues to the next bugfix release milestone (@quicksketch)
- [x] Draft Release notes (@jenlampton)
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Revert version number back (@quicksketch)
- [x] Create release notes on GitHub (@jenlampton)
  - [x] Double check if any changes were made to files outside the `core` directory
- [x] Update the front page download link on b.org (@jenlampton)
- [x] Tweet that a new release is out (@jenlampton)

## Post-release tasks

- [x] Push the bug-fix release to the [Pantheon repository](https://github.com/backdrop-ops/backdrop-pantheon) (@quicksketch)
- [ ] Push the bug-fix release to the [Platform.sh repository](https://github.com/platformsh/platformsh-example-backdrop) (@serundeputy)
- [x] Push the bug-fix release to the [Docker repository](https://github.com/docker-library/official-images/blob/master/library/backdrop) (@jenlampton)
- [x] Update the Wikipedia articles (@klonos)
  - [x] https://en.wikipedia.org/wiki/Backdrop_CMS
  - [x] https://en.wikipedia.org/wiki/List_of_content_management_systems

**Comment by quicksketch** [comment]
Tag is cut: https://github.com/backdrop/backdrop/releases/tag/1.10.1

**Comment by jenlampton** [comment]
Release notes:

* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3130">#3130</a>: Check that a load callback exists before calling.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/1951">#1951</a>: [UX] field_validate_field() message assumes a field is being created.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2681">#2681</a>: Show tabs when managing display modes.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3135">#3135</a>: Fix version checking for dev releases and in installer.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3150">#3150</a>: Reduce messages shown when scheduling content.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3035">#3035</a>: Added ability to override Body field being added to new content types.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3104">#3104</a>: BackdropWebTestCase::assertOption should work on select fields with optgroups.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3133">#3133</a>: Update three database queries for better compatibility.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2295">#2295</a>: Clearfix rich text areas in case of floated content.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/984">#984</a>: [UX] Manually installed layout templates should not require a cache clear.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/2541">#2541</a>: Project Installer: Modules "remembered” even if enabled.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3120">#3120</a>: Remove unclear explanation text.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3070">#3070</a>: Clarify multilingual options on node form.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3125">#3125</a>: Fix Undefined index: description in block info.
* Issue <a href="https://github.com/backdrop/backdrop-issues/issues/3123">#3123</a>: Hide the langcode markup if language module is not enabled.

**Comment by jenlampton** [comment]
Docker repo is updated: https://github.com/backdrop-ops/backdrop-docker/issues/24
