### ISSUE TITLE
[UX] Support a 4th "info" type for backdrop_set_message

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3155]
https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/backdrop_set_message/1

...we currently support only the following message types:

- status:

    ![screen shot 2018-05-31 at 5 44 58 am](https://user-images.githubusercontent.com/2423362/40744004-9249f45e-6496-11e8-9af2-1fe5b0b1b724.png)

- warning:

    ![screen shot 2018-05-31 at 5 45 43 am](https://user-images.githubusercontent.com/2423362/40744001-8cba2c2a-6496-11e8-90df-586ab995d3ea.png)

- error:

    ![screen shot 2018-05-31 at 5 44 19 am](https://user-images.githubusercontent.com/2423362/40743998-89fc3438-6496-11e8-8681-8c11e97daca8.png)

I propose supporting another type of `info`:

![screen shot 2018-05-31 at 5 50 03 am](https://user-images.githubusercontent.com/2423362/40744270-5bc8d8ae-6497-11e8-911e-b8526e5d7627.png)

I think that by doing this, we would also allow contrib modules to communicate info things in a standardised manner. Think Drupal webform module and the message that was added recently:

![screen shot 2018-05-31 at 5 53 28 am](https://user-images.githubusercontent.com/2423362/40744146-0f7bff6c-6497-11e8-95b4-5b489091a1c7.png)

(This should not affect our backwards compatibility, as it seems like an API addition.)

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/2217~~
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2291

**Comment by opi** [comment]
Agreed. I suggest we use an "Info" picto, like https://fontawesome.com/icons/info-circle?style=solid

**Comment by opi** [comment]
Note that in `backdrop_set_message` and `backdrop_get_message`, the `$type` argument is never checked, nor in `theme_status_messages` where the type is printed out as CSS class, without check or sanitization.
It means the implementation is only on the admin theme side, and documentation.

**Comment by klonos** [comment]
> Agreed. I suggest we use an "Info" picto, like https://fontawesome.com/icons/info-circle?style=solid

Of course we should! ...I was lazy when I was putting the mockups together :)

**Comment by klonos** [comment]
PR just filed: https://github.com/backdrop/backdrop/pull/2217

Unfortunately, the `info` type for messages is not being used anywhere in core at the time being, so you cannot test this in the sandbox. For those that cannot test locally, here's how it looks:

<img width="541" alt="screen shot 2018-06-02 at 7 20 53 am" src="https://user-images.githubusercontent.com/2423362/40864580-b9169d7e-6637-11e8-9d5c-0a74835b2546.png">

**Comment by docwilmot** [comment]
Is there anywhere in core now where this could or should be used? If the answer is "no" I suspect we should be questioning if this is necessary.

**Comment by klonos** [comment]
@docwilmot yes, I think I have mentioned this in another issue recently. Here are a few examples where messages we throw at the user are either not using `backdrop_set message` when they should've:

![screen shot 2018-06-04 at 6 20 46 am](https://user-images.githubusercontent.com/2423362/40890872-1af96114-67c0-11e8-9e33-8333af37adf4.png)

...or are using the status/success message type, when the user has not performed any directly related action:

![screen shot 2018-06-04 at 6 23 15 am](https://user-images.githubusercontent.com/2423362/40890898-7be8607e-67c0-11e8-9294-4513710b644a.png)

^^ this is visiting the management page, after having installed modules that were intentionally left disabled. I have just *intentionally* navigated back to the Project Installer page with the intention to install additional modules that I forgot to add in the first go.

...this specific message persists across other project installer sections as status/success. Here's the same message, talking about recently installed **modules**, while I'm at the layouts installation page:

![screen shot 2018-06-04 at 6 33 17 am](https://user-images.githubusercontent.com/2423362/40890970-8b9197ec-67c1-11e8-8b95-9f5fd29cdc33.png)

^^ this can a) either be considered a bug (in which case we should make sure that this message only shows in the modules installer page), or b) considered a feature (in which case the message could use the new "info" type).

Here's another example:

![screen shot 2018-06-04 at 6 40 24 am](https://user-images.githubusercontent.com/2423362/40891016-3b140524-67c2-11e8-85c7-f5e47cd89938.png)

^^ ...layout templates are automatically enabled during the last step of the installer (unlike modules and themes). The first part of this message is correctly thrown as a success, the last part should be an `'info'`. Separating this message to a success and an info one, would allow us to dismiss the one, while keeping the second one persistent...

...here's how this story continues, if you navigate away from the layout templates page and install a theme:

![screen shot 2018-06-03 at 11 20 41 am](https://user-images.githubusercontent.com/2423362/40891065-13ecd5f6-67c3-11e8-95a7-26ce15037800.png)

^^ this is where my previous suggestion makes sense. The first message now seems like a bug, unless we have only kept the "You can manage layout templates on the layouts Settings page." as a persistent `'info'` message. Also, the part that is placed at the top of the list of themes as plain text feels like it could also be a separate `'info'` message.

There's other examples where this could be used in core, but contrib can also use it to convey messages like additional manual steps that might be required after upgrading to a major version etc.. In general, messages that need to be shown as help text, but unlike actual help text, should not be shown all the time.

**Comment by docwilmot** [comment]
I'm not clear on the difference between status and info though. Can we have it explicitly described and agreed on in preparation for this?

**Comment by klonos** [comment]
Sure. Here's my take on this...

"Sophisticated" definitions:

- **Status/Success message**: something that needs to be displayed to the user as a direct result of the action they were performing. Shown once, on the page where the action finishes.
- **Help/Info message**: something that needs to be displayed to the user persistently across various pages. Can be the result of their actions on another section of the site (excludes messages that should be warnings/errors).

(overly) simplified rules:

- **Status/Success message**: Yay! It worked.
- **Help/Info message**: Did you know ...??

Would be interested to know what other think.

**Comment by klonos** [comment]
...having said that, I personally think that although it is good to define/document these, they should not be strict/explicit. The success messages have been abused in many cases over the years, bot in Drupal and in Backdrop. The introduction of the new `'info'` message type should be a way to better the situation and clarify things IMO. A means to expend and provide more options; not a means to impose and restrict.

**Comment by opi** [comment]
> I'm not clear on the difference between status and info though.

Probably because 'status' is more a 'success' message, with a green color theme and a positive check pictogram. Is it worth renaming ?

**Comment by opi** [comment]
Here is a full list of message display through `backdrop_set_message()` : https://gist.github.com/opi/f28a1ed0dc2e26b44b543b02026addb4 ; Not sure we will find so much to display as 'info'

**Comment by jenlampton** [comment]
Yes please! Love this idea, thanks @klonos :)

**Comment by klonos** [comment]
@laryn ...this is my OCD talking again plus my personal preference for the Backdrop the product to be "intelligent", but I believe that the examples you have listed are not 100% fit for the use case. If a message has been triggered by a user action, then these should be success messages. The info type should be used in the case that we need to convey something additional to the user, or if the message we are trying to display has not been a direct consequence of the user's current action.

To be more precise...

- in the case of the "Your account is pending approval" message, it *should* be a success message if it is shown to the user directly after they have created an account. If they revisit the page at a later point in time (not sure if that is possible in this specific case), then this message should change to an info type. So first time we show the message: success (convey "it worked!"), successive times we show the message: info (convey "still pending").

- in the case of "There are no updates currently", it should be a success message if the user has just clicked the "check for updates" button, but if we need to show this message to the user again at a later point (they navigated away and have returned to the same page after a while for example), then this should be an info message this second time. In actuality, we show this to the users:

    ![screen shot 2018-06-26 at 8 01 21 am](https://user-images.githubusercontent.com/2423362/41878126-2c646c74-7917-11e8-9fb2-bb2033205a0f.png)

    ...I see how this could be a "Checked available update data for 3 projects." success message (as opposed to a "something went wrong" error), followed by:
    - a possible "all projects are up to date" success message
    - a possible "updates found for x projects" info message
    - a possible "recommended updates found for x projects" warning
    - a possible "pending security updates found for x projects" error

**Comment by klonos** [comment]
...another example where this can be used in contrib:

![screen shot 2018-06-26 at 10 25 16 am](https://user-images.githubusercontent.com/2423362/41882271-5f82146c-792b-11e8-9cbd-d30d33346d6b.png)

The "Installation is complete." success message would suffice in this case, and the other 2 messages could be shortened to just "[module_name] does not provide any new functionality on its own but may be used by other modules.", and converted to the new info type 😉

**Comment by opi** [comment]
Filled a related issue: [DX] Use proper 'success' message type and deprecate the ambiguous 'status' type. #3179

**Comment by klonos** [comment]
Joomla has this "messages" section that lists messages that need to be communicated to the user:

![screen shot 2018-07-02 at 6 46 07 am](https://user-images.githubusercontent.com/2423362/42138629-d97b3f40-7dc3-11e8-845e-8e669fb4f7cf.png)

...although some of these seem that they should be warnings, respective messages about stats collection, or unsupported php versions in upcoming Backdrop releases could use this new `info` message type (unsupported php version in the current installation should still be a warning/error).

**Comment by klonos** [comment]
...bootstrap also seems to have this [4th info alert type](https://v4-alpha.getbootstrap.com/components/alerts/#examples) too:

![screen shot 2018-07-02 at 6 58 20 am](https://user-images.githubusercontent.com/2423362/42138730-71156104-7dc5-11e8-8df3-888258781be0.png)

**Comment by klonos** [comment]
Note to self (for when this gets merged): another place where this could be used: #2583 / #3050

**Comment by klonos** [comment]
...with the current implementation, if there's a link within an info message, you cannot tell:

<img width="643" alt="screen shot 2018-07-10 at 3 38 32 am" src="https://user-images.githubusercontent.com/2423362/42468055-101880d8-83f7-11e8-94b5-a52a6b827e15.png">

I have made the assumption that we need to keep the link same as the blue used throughout the rest of the admin UI (`#0074bd`), so I have tried different shades of blue for the info icon square and the info text...

`#0000b2`:

<img width="647" alt="screen shot 2018-07-10 at 4 03 33 am" src="https://user-images.githubusercontent.com/2423362/42468239-a2bafbaa-83f7-11e8-920b-bf3b725fd690.png">

`#00007f`:

<img width="645" alt="screen shot 2018-07-10 at 4 05 29 am" src="https://user-images.githubusercontent.com/2423362/42468326-f473fe60-83f7-11e8-9252-d6c92180459f.png">

`#000066`:

![image](https://user-images.githubusercontent.com/2423362/42468405-3653fa1a-83f8-11e8-89f8-8e607544e206.png)

**Comment by klonos** [comment]
...I personally like the combination of `#0074bd` for the icon and link, and `#00007f` for the rest of the text:

![image](https://user-images.githubusercontent.com/2423362/42469921-68dcf7d0-83fc-11e8-9471-77b99b786659.png)

**Comment by klonos** [comment]
...here's how it would look if we adopted the bootstrap alpha4 alert colors:

![image](https://user-images.githubusercontent.com/2423362/42470753-c5d48140-83fe-11e8-84fd-d1dae9664aa7.png)

![image](https://user-images.githubusercontent.com/2423362/42470760-c98fbb9c-83fe-11e8-9b86-7ceb5ec1fa87.png)

**Comment by klonos** [comment]
...and this is with [Bootstrap v4](https://getbootstrap.com/docs/4.0/components/alerts/) alert colors:

![image](https://user-images.githubusercontent.com/2423362/42471089-dd7ae748-83ff-11e8-8188-019d221ed323.png)

**Comment by klonos** [comment]
...oh sorry, the blue color in Bootstrap 4 is actually "primary alert". The info has a more teal color:

![image](https://user-images.githubusercontent.com/2423362/42471168-1a0d23f6-8400-11e8-8841-3c7a80e32d79.png)

**Comment by opi** [comment]
Contrast will never be strong enough with the info type (a11y). What about using a old fashionned underline for any link in messages ?

**Comment by klonos** [comment]
Thanks guys 😄 ...working on it 😄

**Comment by klonos** [comment]
OK, here it is... Links within messages are underlined, and they match the color of the rest of the text:

<img width="634" alt="screen shot 2018-07-17 at 7 40 14 am" src="https://user-images.githubusercontent.com/2423362/42785184-d3e83bd2-8994-11e8-8714-250bd9cc6c97.png">

...and here's how they would look if also bolded:

<img width="641" alt="screen shot 2018-07-17 at 7 40 36 am" src="https://user-images.githubusercontent.com/2423362/42785192-e4bb7ba4-8994-11e8-9496-86525d033c7c.png">

Please let me know which of the two is preferable (bolded or not), and I will then update my PR.

Thanks

**Comment by opi** [comment]
+1 on underlined link, normal weight.

**Comment by klonos** [comment]
...how it would look with links within messages underlined, and matching the color of the rest of the text:

<img width="634" alt="screen shot 2018-07-17 at 7 40 14 am" src="https://user-images.githubusercontent.com/2423362/42785184-d3e83bd2-8994-11e8-8714-250bd9cc6c97.png">

**Comment by klonos** [comment]
...and here's how they would look if also bolded:

<img width="641" alt="screen shot 2018-07-17 at 7 40 36 am" src="https://user-images.githubusercontent.com/2423362/42785192-e4bb7ba4-8994-11e8-9496-86525d033c7c.png">

**Comment by klonos** [comment]
Please let me know which of the two is preferable (bolded or not) by voting 👍and/or 👎 , and I will then update my PR.

Thanks

**Comment by docwilmot** [comment]
This is getting awfully in-depth for a simple feature. 
I vote we add the blue info type and forget about changing the links.

**Comment by klonos** [comment]
...I understand why you might be feeling this way @docwilmot, but I hope that you can see how this would introduce a UX issue. Can you tell from the screenshot below that the "a link" part of the text is actually a link:

<img width="660" alt="screen shot 2018-07-19 at 1 59 49 am" src="https://user-images.githubusercontent.com/2423362/42893438-a5b00c5e-8af7-11e8-8a2b-639859093869.png">

**Comment by docwilmot** [comment]
Actually, my bad, I thought underline was already decided. I now vote for underlined links in the info type alerts.

**Comment by wesruv** [comment]
Can we double check that this is close to or above and beyond AAA:
https://webaim.org/resources/contrastchecker/

**Comment by opi** [comment]
Add a [request](https://github.com/backdrop/backdrop/pull/2217#pullrequestreview-143393231) regarding accessibility of focused links. Easy to fix though

**Comment by klonos** [comment]
Thanks @opi 👍...for posterity and so that we get some feedback from others, I am posting your comment here too:

> just realized that links has no hover or focus effect. This is not nice regarding accessibility.
> The easiest could be to remove the text-decoration:
> 
> ```
> .messages a:hover,
> .messages a:focus {
>   text-decoration: none;
> }
> ```

...although from what I see we are doing the opposite everywhere else in the admin UI: links are not underlined by default, and they get underlined on hover/focus. Hmm... let me give it a bit of thought and I will update the PR ...I will probably go with your suggestion @opi unless anyone else has better ideas. @wesruv?

**Comment by jenlampton** [comment]
I've filed a new PR that includes the hover state: https://github.com/backdrop/backdrop/pull/2291

**Comment by quicksketch** [comment]
Looks great. I added one more commit to add `@since 1.11.0 Added "info" as an acceptable $type parameter.` to the docblock of `backdrop_set_message()`.

I've merged https://github.com/backdrop/backdrop/pull/2291 into 1.x for 1.11.0. Thanks @klonos, @opi, @docwilmot, and @jenlampton!

**Comment by klonos** [comment]
Thanks everybody for finishing this off 👍...I have plans for putting it into good use 😄
