### ISSUE TITLE
[UX] Add a persistent "This content is scheduled for..." message for scheduled content

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3156]
This is a follow-up to #3150...

### Steps to reproduce/Actual behavior

1. Create a new piece of content and schedule it for some time in the future.
2. Save ->

![screen shot 2018-05-31 at 5 24 47 am](https://user-images.githubusercontent.com/2423362/40742913-44cfd1ec-6493-11e8-902f-dd57099fbf72.png)

3. Refresh the page (to simulate visiting this page as admin, while still not published) ->

![screen shot 2018-05-31 at 5 25 04 am](https://user-images.githubusercontent.com/2423362/40742945-68d82ef4-6493-11e8-8d38-2693164c7cc7.png)

### Expected behavior

- After the scheduled content has been saved, the red status makes me think that something went wrong. Also, we have a standard way to be communicating success/warning/error/status messages, so we should be using that instead.

- After revisiting a scheduled/unpublished piece of content, I would like to still see info about the fact that this content is scheduled to be published.

I propose the following:

1. Convert the "This page is unpublished" custom message to a standard `backdrop_set_message`, and set its type to `info` (#3155)

2. Upon save, only show the status/success message that was added in #3150.

3. Upon revisiting unpublished pages (be they scheduled or not), persistently show the "This page is unpublished" info message.

4. Upon revisiting unpublished pages that are scheduled, include the "It is scheduled for ..." message in the info text.

**Comment by serundeputy** [comment]
dupe: https://github.com/backdrop/backdrop-issues/issues/3077

**Comment by serundeputy** [comment]
In the current PR I've moved the functionality out of the `basis` theme and into `node.theme.inc`
@quicksketch feels it should remain in `basis`.
I said it should be available to anyone regardless of theme.  Anyone else have opinion?
https://github.com/backdrop/backdrop/pull/2199#discussion_r191011322

- [ ] Decide on moving the functionality to `node.theme.inc` or leave in `basis`
- [ ] We need to change the date to use the `medium` date format.

**Comment by quicksketch** [comment]
Yeah, let's continue in https://github.com/backdrop/backdrop-issues/issues/3077.

FYI using messages only has not been suggested in that issue. Messages have a problem however that they would only work on the full node version of the page. The current implementation works on teaser (or other view modes), which is why it wasn't a message when we first added it.

![image](https://user-images.githubusercontent.com/100206/40751727-4c477ca8-6421-11e8-8805-6186b95e6728.png)

**Comment by klonos** [comment]
I'm have brought shame to my good name by opening a duplicate 😞 ...I have not been around lately and have lost track of tickets. ...not only that, but I have failed to search before opening this one, having assumed that I was the only person to have noticed this.

😄 ...taking it to #3077
