### ISSUE TITLE
[UX] VBO: Actions field still referred to as "Operation" + no error message if no items selected.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3158]
### Steps to reproduce / Actual behavior

1. Navigate to `/admin/content/node`.
2. Without making any selection, click on the "Execute" button -> you get an "**Operation** field is required." error message:

    ![screen shot 2018-06-02 at 2 41 16 pm](https://user-images.githubusercontent.com/2423362/40870460-17a49842-6673-11e8-98e6-bad29bac0e03.png)

    ...while the respective field says "Choose an action"

3. This time select an action, but do not select any item from the list. Click "Execute" -> nothing ???

### Expected behavior (if reporting a bug)

1. Navigate to `/admin/content/node`.
2. Without making any selection, click on the "Execute" button -> you get an "**Action** field is required." error message instead.
3. This time select an action, but do not select any item from the list. Click "Execute" -> get a "No items selected." error message.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2218

**Comment by opi** [comment]
UX improvements, one step at a time <3

**Comment by quicksketch** [comment]
Thanks @opi and @klonos! Merged https://github.com/backdrop/backdrop/pull/2218 into 1.x and 1.10.x.
