### ISSUE TITLE
[UX] Better module uninstallation confirm form.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3161]
Before:

<img width="850" alt="screen shot 2018-07-31 at 2 40 20 pm" src="https://user-images.githubusercontent.com/2423362/43438089-da9148d4-94cf-11e8-8b59-479e9a45bb4f.png">

After:

<img width="634" alt="screen shot 2018-07-31 at 2 34 18 pm" src="https://user-images.githubusercontent.com/2423362/43437928-d9f4721c-94ce-11e8-97a4-939ef87490b2.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2220

**Comment by klonos** [comment]
In this PR:

- moved the "Would you like ..." text to the confirmation page title (same as done for confirming deleting content)
- Converted the "all data will be lost" text to a warning (we were previously emphasising it using `<em>` tags)
- removed the now redundant "Would you like to continue with uninstalling the above?" question, as it was repeating what is already being asked in the form title.

**Comment by olafgrabienski** [comment]
> Are you sure you want to continue with uninstalling the modules listed bellow?

@klonos There's a small typo at the end of the sentence: "bellow" (two `l`)

**Comment by klonos** [comment]
Good catch @olafgrabienski 👍 ...fixed!

**Comment by opi** [comment]
In the 2nd screenshot, the lonely bullet list without heading feels a little lost

**Comment by klonos** [comment]
I hear ya @opi, but the text that was previously there has been moved to the page title and the warning. There was nothing left 😄 ...any suggestion?

**Comment by quicksketch** [comment]
I often find that putting an entire sentence in the title to be ineffective for my reading. As I skim over the entire header area to read the "content" area. What I read on this page after the changes is the status message, the bullet list, and the buttons. I miss the header title entirely.

So I think a solution that would solve the lonely bullet list and my title problem would be keeping the title "Confirm uninstall" and moving the question sentence into the body area.

**Comment by klonos** [comment]
I have updated the PR. Better now?:

<img width="634" alt="screen shot 2018-07-31 at 2 34 18 pm" src="https://user-images.githubusercontent.com/2423362/43437928-d9f4721c-94ce-11e8-97a4-939ef87490b2.png">

**Comment by opi** [comment]
Yay! Marking as RTBC.
@quicksketch please squash the 3 commits before merge to keep a clean git history.

**Comment by klonos** [comment]
@quicksketch always squashes 😄

![image](https://user-images.githubusercontent.com/2423362/43451576-9dc93b04-94f8-11e8-8ec9-6fce3ec350e1.png)

![image](https://user-images.githubusercontent.com/2423362/43451642-c0d33d20-94f8-11e8-884c-82da67120b3a.png)

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2220 into 1.x. Though this could be included in 1.10, as we're so close to 1.11 it's better to avoid unnecessarily changing strings used in translations.

**Comment by quicksketch** [comment]
Also, per @herbdool's PR comment, I reverted the title change. It had been changed to "Confirm uninstallation", I reverted it back to "Confirm uninstall". The body and message area is the big win here.
