### ISSUE TITLE
[SPAM] (...) Helpline Number (...) Support Number

### ISSUE THREAD

**Issue by AlinaClarks** [backdrop/backdrop-issues#3163]
### Relevant version/system information (if applicable)

[*Please do not use this issue queue to report security issues*. If you believe
you may have discovered a security issue with Backdrop CMS, contact the Backdrop
Security Team directly at security@backdropcms.org. In order to keep everyone
safe, we manage security issues separately in a private repository. So please
refrain from publicly blogging, or tweeting about it until the issue has been
resolved.]: #

**Comment by AlinaClarks** [comment]
When we talk about ultimate protection, McAfee is on   the topper. It assures maximum security and keeps all your important data   safer. If you are confronted to any threat imposing your system then you can   call us any time at McAfee Helpline Number USA for desired assistance.
--
http://www.customer-help-number.com/mcafee-support.php

**Comment by olafgrabienski** [comment]
Reported the user at Github contact page.
