### ISSUE TITLE
update.php show Error >> Call to undefined function tablesort_cell() in theme_table() 

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3167]
## Describe your issue or idea

Hi Developers,

i have a Problem with update to Backdrop 1.10.0. The Error is this:

`Error: Call to undefined function tablesort_cell() in theme_table() (line 2219 of /xxxxxxxxxxxxx/backdrop.cms-blogger.eu/core/includes/theme.inc).`

How to fix this?

Thanks in Advance.

### Relevant version/system information (if applicable)

[*Please do not use this issue queue to report security issues*. If you believe
you may have discovered a security issue with Backdrop CMS, contact the Backdrop
Security Team directly at security@backdropcms.org. In order to keep everyone
safe, we manage security issues separately in a private repository. So please
refrain from publicly blogging, or tweeting about it until the issue has been
resolved.]: #

**Comment by klonos** [comment]
Hello @AlexL777. Can you please provide more information, like where/when does this happen? Is it happening in specific sections/pages? Any steps to reproduce would help too.

Thanks

**Comment by jlfranklin** [comment]
We saw this before with the redesign of the status report in #2693.  We probably need to add the same include line in `update.php`.

**Comment by AlexL777** [comment]
Hello Developers,
ok, more Info!

I normally do a standard upgrade by uploading the new directory `/core` to the server. Then I call in the browser `/update.php`.

I took the new version Backdrop 1.10.0.

On the server I have Shared Hosting and PHP 7.1, MariaDB 10.x.

**Comment by klonos** [comment]
Thanks for the additional info @AlexL777. Can you please also let us know which version you tried to upgrade from?

**Comment by AlexL777** [comment]
The upgrade was from Backdrop 1.9.5 to 1.10.0.

**Comment by klonos** [comment]
Thanks @AlexL777 👍 ...I will give this a go over the weekend and try to reproduce the error you got. From your description, I understand that you received the error after trying to run `update.php`. Correct?

**Comment by AlexL777** [comment]
Yes, this is correct!

**Comment by klonos** [comment]
Hello @AlexL777, I have just tried the following, but could not reproduce the problem you have reported:

- Downloaded a fresh copy of 1.9.5 and install it.
- Navigated to `/admin/reports/status`
- Downloaded a fresh copy of 1.10.0 and extracted its contents
- Deleted the `/core` folder from the 1.9.5 installation
- Copied the `/core` folder from the extracted 1.10.0 into the 1.9.5 installation
- Refreshed the `/admin/reports/status` page -> got a warning about pending database updates
- Clicked the link available in the status page, run the updates -> no errors
- Navigated back to `/admin/reports/status` -> all good
- Checked the error log -> nothing but info messages

I did not even have to clear caches or anything.

Perhaps a contrib module has caused this? Can you please list the modules you have installed/enabled? I will then give it another go with these installed.

**Comment by AlexL777** [comment]
Thank you for taking the trouble and helping me. In the interim I have newly installed Backdrop 1.10.x and the reinstallation ran without problems. I will watch it and especially when new updates appear.

I'll probably give up the old project. Just take a look. Anyway, it may well be due to a module and I usually always worry about module updates, so everything is always up to date.

**Comment by AlexL777** [comment]
Yes, you can close this Ticket. Thanks!

**Comment by klonos** [comment]
Thanks fr providing feedback @AlexL777. Closing...

**Comment by klonos** [comment]
...possibly a duplicate of #2693 ??
