### ISSUE TITLE
DATE_RFC7231 already defined in PHP 7.0.19 and 7.1.5

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3169]
This is the respective issue for https://www.drupal.org/project/drupal/issues/2877243. From that ticket:

> The issue observed on Windows, IIS 10, and PHP 7.
> 
> The latest version of PHP, 7.0.19, fixes this bug in PHP and defines the constant DATE_RFC7231 in PHP itself.
> 
> As a result, Bootstrap now generates a notice:
> 
> `Constant DATE_RFC7231 already defined in C:\vhosts\my-site\includes\bootstrap.inc on line 258`
> 
> In my environment, a PHP notice at that stage of Bootstrap completely broke the site. I could revert the PHP version to the previous one, but there was no workaround in user interface.

This was at the top of the list of issues to port in https://github.com/backdrop/backdrop-issues/issues/2776, but was marked as N/A for Backdrop(?). I know that we did not have any reports of this error in the queue, but the original issue description mentions Windows and IIS, so perhaps none of the Backdrop users work on Windows and that explains why.

Anyway, this seems like a small change, and over in the d.org issue they mention that there were no breakages.

Also from the d.org issue:

> This seems like a straightforward enough quick fix, regardless of the priority level. Strictly speaking we could make it a const, instead of a define(), but the difference is marginal so... RTBC.

...

> We cannot make it a const as that syntax (outside of class context) is only supported since PHP 5.3.0 (see http://php.net/manual/en/language.constants.syntax.php) and Drupal 7 officially still supports PHP 5.2.5+ (see https://www.drupal.org/docs/7/system-requirements/php#php_required).

Noting that in [backdrop we require PHP 5.3.2+](https://backdropcms.org/requirements), so not sure if this *should* be a `CONSTANT` for us.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2225

**Comment by klonos** [comment]
@serundeputy, @quicksketch ...as I said, not sure if this indeed does not apply to us, but the code change seems "harmless" 😄 ...done my bot, so now deferring it to your expertise.

**Comment by klonos** [comment]
PS: you might wanna check [my shameless plug over in the d.org issue](https://www.drupal.org/project/drupal/issues/2877243#comment-12653944).

> I don't think D7 is still being taken care of... sadly, so, better add this patch to your makefiles ;-)

...

> ...better yet, lets fork D7 and let's take this off of drupal.org, make a new update module that pulls from Github instead.

...

> I don't think this is a good idea... even if I would prefer to work on Github :-)
>
>"Forking" Drupal 7 would makes things even more messier.
>
>I just hope one day some people will just take care of D7 for the millions of sites yet running it.

...sorry, but I couldn't help it after having read the comments 😈

**Comment by quicksketch** [comment]
We don't have this line in Backdrop because we removed this constant as part of the removal of aggregator.module from core. We could add this line back in for the purposes of contrib work and compatibility.

**Comment by klonos** [comment]
> We could add this line back in for the purposes of contrib work and compatibility.

👍 ...otherwise, please feel free to close this ticket and the respective PR.

**Comment by quicksketch** [comment]
It won't hurt I suppose, and could save someone a headache later, especially if porting a module from Drupal, so let's pull it in. Merged in https://github.com/backdrop/backdrop/pull/2225.

I added a `@since` to the docblock for clarity.
