### ISSUE TITLE
[UX] Fixed: Hide the email verification checkbox when only admins can create accounts.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3170]
This setting has a long description, which adds to the page "noise" and required scrolling (more obvious on tablet/mobile):

![screen shot 2018-06-16 at 9 39 19 am](https://user-images.githubusercontent.com/2423362/41493318-586b764e-7149-11e8-8261-d053dbc007a4.png)

Let's hide it.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2227

**Comment by klonos** [comment]
...one peculiar thing I've noticed in the PR sandbox, and then also tested on a couple of test Backdrop installations is that although we've merged the required changes in https://github.com/backdrop/backdrop-issues/issues/574, still the default OOTB is "Visitors, but administrator approval is required". Huh!? Anyone care to confirm?

**Comment by stpaultim** [comment]
This seems like a simple, nice idea. 

I created a new PR - so folks can try this out. https://github.com/backdrop/backdrop-issues/issues/3170

Thanks @klonos for getting this started.

**Comment by olafgrabienski** [comment]
> This seems like a simple, nice idea.
> 
> I created a new PR - so folks can try this out. https://github.com/backdrop/backdrop/pull/4621

Indeed a nice idea! Tested in the PR sandbox: As expected, the "Require email verification when a visitor creates an account" checkbox is there only shown if visitors are allowed to register accounts.

**Comment by stpaultim** [comment]
Does anyone else think this is a good enough idea to add to the bugfix milestone?

I think it would be nice to get at least one more person to review this idea and help us decide if we should push forward.

**Comment by kiamlaluno** [comment]
Since JavaScript is already used to hide settings when they do not apply (because a different setting), I think it makes sense to do the same on this form for the *Require email verification* setting.

**Comment by docwilmot** [comment]
Looks good to me, PR https://github.com/backdrop/backdrop/pull/4621 tested and looks good. RTBC to me.

**Comment by quicksketch** [comment]
Thanks folks! I have merged https://github.com/backdrop/backdrop/pull/4621 into 1.x and 1.27.x.

**Comment by klonos** [comment]
Sorry folks, didn't get a chance to review the PR that got merged and request this change to be made in time, but we should be indenting form elements that depend on others (since we got #5999). Here's a one-liner follow-up PR to do that: https://github.com/backdrop/backdrop/pull/4716

Here's a side-by-side before/after screenshot:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/7d09b59a-86f8-4ebf-9afb-6e47c15ab455)

**Comment by quicksketch** [comment]
Thanks @klonos! I tested and merged your follow-up!
