### ISSUE TITLE
[UX] Hover indication missing from selected layout templates.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3172]
👍:
![screen shot 2018-06-22 at 8 40 30 am](https://user-images.githubusercontent.com/2423362/41749177-6b094804-75f8-11e8-80a4-a304f685e66d.png)

👎:
![screen shot 2018-06-22 at 8 42 06 am](https://user-images.githubusercontent.com/2423362/41749193-7a292afc-75f8-11e8-8608-57a6fc877b5c.png)

---
PR by @klonos: upcoming 😄...

**Comment by opi** [comment]
Proposal: https://github.com/backdrop/backdrop/pull/2274

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2274 Seems good to me. It's a little strange when deselecting an option that the border stays present until I click off that template (removing focus), but as the entire point is to display focus, that's a side-effect of this implementation.

gif in action:
![peek 2018-08-31 19-43](https://user-images.githubusercontent.com/100206/44941605-1f605600-ad56-11e8-8237-917ae1119e86.gif)

So it seems good to me. Let's just update the PR to remove the commented-out lines permanently.

**Comment by opi** [comment]
> Let's just update the PR to remove the commented-out lines permanently.

@quicksketch done!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2274 into 1.x and 1.10.x. Thanks!

**Comment by klonos** [comment]
> It's a little strange when deselecting an option that the border stays present until I click off that template (removing focus) ...

Yeah, I was working on this on my local, but the reason I did not push a PR was that I could not for the love of me figure out how to sort that problem with pure CSS 😞 ..annoying.

Anyway, the situation is now much better than before. Thanks for beating me to it @opi 👍
