### ISSUE TITLE
Hard-code update.php and install.php to use the System module's maintenance-page.tpl.php

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3175]
If you have a theme or module that provides a custom maintenance-page.tpl.php, that custom version is used for the update.php and install.php pages too. Generally, I don't think that a custom maintenance-page.tpl.php implementation is going to account for the elements/layout that the update.php and install.php pages use. Therefore I'd like to suggest that those pages use the System module's version of maintenance-page.tpl.php: https://api.backdropcms.org/api/backdrop/core%21modules%21system%21templates%21maintenance-page.tpl.php/1

**Comment by BWPanda** [comment]
Or, at the very least, provide an option to choose which theme/module's maintenance-page.tpl.php gets used for the update/install pages.

**Comment by klonos** [comment]
Not sure about hard-coding or enforcing anything, but this is an actual problem, and the best place for it in the UI is in the admin theme settings (mockup):

<img width="570" alt="screen shot 2018-06-27 at 9 51 32 am" src="https://user-images.githubusercontent.com/2423362/41945322-cb3db91c-79ef-11e8-8bf6-9726f4b054d4.png">

**Comment by BWPanda** [comment]
I don't think this is needed anymore. Custom maintenance templates in themes aren't used on core pages as far as I can tell. And modules just need to conditionally overwrite the theme registry (as I've just done here: https://github.com/backdrop-contrib/maintenance_page/commit/3426a766684a3d772a1df83d194cfe9fc56b0a94).

Closing then. Feel free to re-open if necessary.
