### ISSUE TITLE
Rules "Send mail to users of role " action fails

### ISSUE THREAD

**Issue by barneylodge** [backdrop/backdrop-issues#3181]
When attempting invoke "Send mail to users of role" after creation of new content I see this error.

_PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.rid' in 'where clause': SELECT DISTINCT u.mail FROM {users} u INNER JOIN {users_roles} r ON u.uid = r.uid WHERE r.rid IN (owner); Array ( ) in rules_action_mail_to_users_of_role() (line 111 of /var/www/html/modules/rules/modules/system.eval.inc)._

I am advised ..

_"Looks like the module is still looking for a role ID in the database, but that's now a role name instead."_

**Comment by klonos** [comment]
Hello @barneylodge and thanks for taking the time to report this issue 👍 

This seems to be with the contributed module Rules, and not with Backdrop core. So I am afraid that you are in the wrong issue queue 😄 ...can you please copy this over to a new issue in https://github.com/backdrop-contrib/rules ? Thanks.

In general, https://github.com/backdrop/backdrop-issues/issues is for core issues, and https://github.com/backdrop-contrib is where issues for contrib modules should be filed.

I am going to go ahead and close this issue now.

**Comment by barneylodge** [comment]
Ooops!! Sorry

Thanks a million for  a super fast response

Barney

**Comment by barneylodge** [comment]
Hi Greg

This may not be consistent with the Backdrop CMS philosophy, but is there
any way a user can pay to advance an issue fix. Sending mail to users of a
role is so critical to my applications.

Barney Lodge

**Comment by klonos** [comment]
Hello @barneylodge and sorry for the slow follow-up responce. You are somewhat right. Paying for issues to be fixed is not explicitly prohibited or endorsed as far as I know, but you could attempt to contact the module maintainers, or hire an independent Drupal/Backdrop developer to fix things for you.

**Comment by klonos** [comment]
...I actually just saw that your issue [seems to have been sorted](https://github.com/backdrop-contrib/rules/issues/26) by @Graham-72 😄 ...you can always consider buying the contrib module maintainers a beer ...or see if they are available for hire, and recommend them to others for their next project/site. Graham does not explicitly state in [his backdropcms.org user profile](https://backdropcms.org/account/graham-72) that he is available for hire ...but I am sure that he must have a list of things that he'd like, such a book or something 😄...you can try to contact and ask.

Another thing that I am sure helps is to [donate to Backdrop CMS](https://backdropcms.org/contribute#donate) ...or to spread some good words about us 😄
