### ISSUE TITLE
[DX] Split path.path.inc file into their respective modules

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#3182]
https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.path.inc

This file implements `hook_path_info` for 3 other core modules : node, taxonomy and user.

Quoting the `path.path.inc` top comment:
>  Path is an optional module in Backdrop, providing essentially a UI for the
>  core path functionality. Because this module may be disabled, it's up to this
>  module to provide implementations for other core modules.

I really don't understand the point here. I think we are facing the same issue as https://github.com/backdrop/backdrop-issues/issues/2952#issuecomment-360335294 with `hook_layout_context_info`.

Some related issues : https://github.com/backdrop/backdrop-issues/issues/2954 & https://github.com/backdrop/backdrop-issues/issues/3024

--

PR https://github.com/backdrop/backdrop/pull/2254

**Comment by jlfranklin** [comment]
There is no reason node, taxonomy, and user can’t own their own hook implementations.  They won’t be called unless path is enabled. 

This may be a hold over from when Path was a contrib module.  Core doesn’t implement hooks for non-core modules.

**Comment by opi** [comment]
> Core doesn’t implement hooks for non-core modules.

Indeed, It explains everything here. Thanks

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2254 is ready for review

**Comment by klonos** [comment]
The PR looks good to me, but I would like someone with more knowledge on this to also take a look.

By removing the path.path.inc file, we have lost this docblock:

```
/**	
 * @file	
 * Path integration for core modules.	
 *	
 * Path is an optional module in Backdrop, providing essentially a UI for the	
 * core path functionality. Because this module may be disabled, it's up to this	
 * module to provide implementations for other core modules.	
 */
```

Not sure if I get things right, but does the above mean that every `*_path_info()` function should be checking `if (module_exists('path'))`? ...or am I missing the point here and the core path functionality is all that's needed?

**Comment by opi** [comment]
This docblock is actually wrong I guess. Ans implementing a hook for a disabled module is no harm

**Comment by quicksketch** [comment]
Looks great. I've merged https://github.com/backdrop/backdrop/pull/2254 into 1.x. This shouldn't be an API change (it's functionally identical), but the rearrangement might surprise some people so I've not backported it into 1.10.x.
