### ISSUE TITLE
Add a Views handler for rendered display of Files

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#3183]
## Describe your issue or idea
In the [image gallery issue](https://github.com/backdrop/backdrop-issues/issues/3134) we have a View of image files for selecting images to be inserted into CKEditor. The View now uses a global text field to rewrite the image display (`<img class="image-library-image" src="[uri]">`) because there is no way now to render an image if this is a pure File View (ie not a Content View).

This is because our limited adoption of Files as entities didnt include a Views handler to render Files.

### Steps to reproduce (if reporting a bug)
Create a File View. Try and find a way to actually show an image in that View. wont happen without rewriting

### Actual behavior (if reporting a bug)
Not possible

### Expected behavior (if reporting a bug)
There should be some way to create a View which displays actually the images from your site.

### Relevant version/system information (if applicable)
Backdrop 1.10

[*Please do not use this issue queue to report security issues*. If you believe
you may have discovered a security issue with Backdrop CMS, contact the Backdrop
Security Team directly at security@backdropcms.org. In order to keep everyone
safe, we manage security issues separately in a private repository. So please
refrain from publicly blogging, or tweeting about it until the issue has been
resolved.]: #

**Comment by jenlampton** [comment]
We should be able to port this from the file_entity module.

**Comment by docwilmot** [comment]
I think my issue title may have been a bit simplistic. We *could* simply do a handler to render an image file, but then that becomes specific to Views. We should in fact create a method to render images generally, but then Files aren't all images; then do we need a way to also render videos, documents etc? 

In short should we have a discussion about rendering Files generally?

**Comment by jenlampton** [comment]
Yes, or we could copy what file_entity does, maybe with a little UX cleanup? I think that would be the most backwards-compatible with Drupal 7.

**Comment by docwilmot** [comment]
> Yes, or we could copy what file_entity does

File Entity does a hell of a lot, that was the point of my last post: how much of that do we want to do? A simple image render handler? Image rendering generally? File rendering generally?

**Comment by klonos** [comment]
Images have a "native" preview in browsers, and we have image styles in core ...with an existing "Thumbnail" image style already in place.

We could have video thumbnails too, and videos (most types) do have native browser preview too, but that would require additional work.

As for other file types, we could have a generic image placeholder to serve as their "thumbnail".

But mostly what @jenlampton said. We should get https://www.drupal.org/project/file_entity fully in core. It seems that [we are claiming that it is already in core](https://backdrop-ops.github.io/slides/intro-mini.html#/19), yet certain features the D7 module provides seem to be missing.

**Comment by docwilmot** [comment]
>  We should get https://www.drupal.org/project/file_entity fully in core

@klonos the problem with "fully" is that File Entity probably does a lot more than we need. The `file_entity.module` file alone is 2700 lines of code and there are 42 other files apart from `file_entity.module`. For the image browser, which is the reason this issue came up, we only want a Views image file handler, about 50 lines of that code, I'd suspect, but would love the experts to suggest if that is reasonable, or if it would be necessary to bring in some other features to support that handler code, or if really we need to fully port File Entity, or any other compromise to move forward, so will call out @quicksketch  @jenlampton @serundeputy @mikemccaffrey etc.

**Comment by jenlampton** [comment]
> how much of that do we want to do

Yes, this is the real question... Maybe we should focus on https://github.com/backdrop/backdrop-issues/issues/2632 as getting that issue done would solve this problem.

**Comment by herbdool** [comment]
Is this issue still relevant? Don't we have an image gallery now?

**Comment by jenlampton** [comment]
@herbdool In our image gallery we're using a hack:

> The View now uses a global text field to rewrite the image display (<img class="image-library-image" src="[uri]">) because there is no way now to render an image if this is a pure File View (ie not a Content View).

This issue would provide a "Rendered file" formatter so that people don't have to put together their own 'IMG' tag.

**Comment by stpaultim** [comment]
I was just looking for a way to render a PDF on a node and came across this issue.

**Comment by klonos** [comment]
The way I am reading this issue here, we have 2 options:

1. Port the 7.x https://www.drupal.org/project/file_entity and include it in core in its current status.
2. Cherry-pick things from https://www.drupal.org/project/file_entity and rewrite the Backdrop implementation.

Option 1 would get us quicker into feature parity with 7.x (200k D7 sites using it - that's ~25%), but would also introduce a lot of code overhead. Option 2 would reduce the amount of code we need to maintain, but would take us much more time to implement.

**Comment by docwilmot** [comment]
We're well on the way with https://github.com/backdrop/backdrop-issues/issues/2632. We discussed this as well in at least a few Thursday meetings and the consensus seems to be this would be really good in core, since most people (>80%?)  would benefit. My hesitation with the port was that it is a beastly amount of code, but it would be hard to pick out bits of it, we probably need the whole thing.

But a rendered File formatter alone shouldnt be too hard even without all of https://github.com/backdrop/backdrop-issues/issues/2632 as a separate PR.

**Comment by jenlampton** [comment]
This should already be included in 1.14 via https://github.com/backdrop/backdrop-issues/issues/2632, let's not duplicate effort. Anyone who wants to help get this done - please help me over there :)
