### ISSUE TITLE
Add help text to Views' 'Global: Text area' field

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3188]
The 'Global: Text area' Views field is missing help text, so it looks like this:

![screenshot-2018-7-5 packages content packweb](https://user-images.githubusercontent.com/2385329/42321313-2b292b32-8061-11e8-98a3-c2df241ac6b3.png)

https://github.com/backdrop/backdrop/pull/2236 PR fixes this.

**Comment by klonos** [comment]
Good catch @BWPanda 👍 ...RTBC

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2236 into 1.x and 1.10.x.
