### ISSUE TITLE
[UX] Allow contact form permissions to be set on the contact settings page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3190]
## Describe your issue or idea

Add a list of permissions to view the contact form, with checkboxes, on the contact module settings page. 

Since people will often visit the configure link for contact module, but may forget to set permissions, adding them in this second location will make it more likely that people will remember to set the permissions for the module.

![43b3da06-63ab-11e5-9c7f-f60de59a3290](https://user-images.githubusercontent.com/397895/42347096-a3601230-8059-11e8-9c4d-dc5a14579ff5.png)

This is a spun off from https://github.com/backdrop/backdrop-issues/issues/1168

---
PR https://github.com/backdrop/backdrop/pull/2258

**Comment by klonos** [comment]
This is a no-brainer UX+

**Comment by opi** [comment]
Adding to 1.11.0 milestone, hope it helps to get some review ;)

**Comment by olafgrabienski** [comment]
I've had a look at the sandbox site. Looks good (see highlighted area in the screenshot below), and the permissions are synchronizing well between the contact settings page and the permissions page.

![screen-backdrop-pr-2258-contact-settings-permissions](https://user-images.githubusercontent.com/14188307/44023298-400843c4-9eea-11e8-8cf1-2696f1441edf.png)

**Comment by opi** [comment]
Thanks @olafgrabienski for your review !

**Comment by quicksketch** [comment]
Thanks all! Merged https://github.com/backdrop/backdrop/pull/2258 into 1.x for 1.11.0.
