### ISSUE TITLE
[UX] Better labels and help text for the Contact module settings form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3192]
This is a follow-up to #2990

Sorry for coming late to the party. A couple of comments:

1. About the "Show the 'Send yourself a copy' checkbox" label ...I cannot think of any other place in the admin UI where we offer an option to show/hide form elements. I think that we instead give things titles related to the functionality they enable/disable. I think that the help text of this checkbox is more fitting for its title:

    > Allow users to send themselves a copy of the submitted data.

    ...and the help text could then be:

    > Exposes a 'Send yourself a copy' checkbox on site-wide and personal contact forms.

2. I feel that using the word "limit" in an element and then using the word "threshold" to explain it is backwards. Think this:

     **supercalifragilisticexpialidocious**
     The thing that Mary Poppins used to say.

    So, I think that the label of the collapsed fieldset should be "Email send thresholds" ...and the help text could be simplified to something like this:

    > Limit the amount of emails that can be sent from contact forms, from the same IP, within a specific window of time. This helps prevent malicious users from sending multiple emails.

Screenshot from the PR sandbox:

![screen shot 2018-06-16 at 7 30 30 am](https://user-images.githubusercontent.com/2423362/41490389-3a940e5e-7137-11e8-88a3-acb3c3b7add3.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2226

**Comment by opi** [comment]
Why not ;) I believe this is an improvment !

I do not have a strong opinion on this, mostly because I'm not a good english writer. I'd like other contributors to review your PR.

**Comment by klonos** [comment]
Thanks @opi ...I have added the "needs feedback" flag to this issue to draw more attention.

@herbdool has left this comment in the PR:

> I don't think "threshold" is the correct word. It has almost the opposite meaning. From the dictionary: "the magnitude or intensity that must be exceeded for a certain reaction, phenomenon, result, or condition to occur or be manifested." Maybe just rename it "Limiting Emails".

**Comment by Graham-72** [comment]
Perhaps use the heading 'EMAIL LIMITATION' in place of 'EMAIL SEND THRESHOLDS'?

**Comment by quicksketch** [comment]
I don't have strong preferences on this text before/after either, but I think @herbdool's comment is valid. We shouldn't use "threshold" to describe a "limit". Previously it was simply "Send limit". If we want to include the other changes and just leave the label as-is that would work for me.

**Comment by opi** [comment]
Nice, I like it. Marking as RTBC as this is only a minor text change. Thanks @klonos to support my current obsession with contact module ;)

**Comment by opi** [comment]
> While we're at it, this form is very small so having the "Send limit" fieldset be collapsed does not make much sense to me. Should we have it be expanded by default?

We'll see later with https://github.com/backdrop/backdrop-issues/issues/3190 (Permissions on the settings page) if we have to expand or collapse some fieldset.

**Comment by klonos** [comment]
Thank YOU @opi for working on all these contact form issues ...just because this has become your obsession, it does not mean that it has not been mine too. Before you file #3023 there was #1168 filed by yours truly 😄 

...I just don't have much time lately to be winching about things, that's all 😆

**Comment by klonos** [comment]
...I was reviewing the PR for #3110 and found that form to have a better implementation by using proper titles for the dropdown elements, and then `'#title_display' => 'invisible',` + `'#prefix' => t(),` for the markup before then elements.

I also found it better to move the description from the fieldset to a separate help item. That made it also be styled as help text:

<img width="696" alt="screen shot 2018-07-28 at 7 58 46 pm" src="https://user-images.githubusercontent.com/2423362/43355507-b402211a-92a0-11e8-9bef-886a28ca3010.png">

...this also adds more consistency to the coding patterns for similar things, ...and you know me and consistency/OCD 😄

@opi care for a second review please?

**Comment by klonos** [comment]
This is a very valid point @opi 👍 ...perhaps we should be using `aria-hidden` so to have screen readers ignore one of the two? I am guessing that there are other places in core where this is being used and thus will need fixing.

**Comment by opi** [comment]
Did some ready about a11y, and I guess wrapping these `#prefix` with a `<span aria-hidden="true">` tag is good enough.
@klonos can you do that ? If not, I can get over your PR.

**Comment by klonos** [comment]
...oh, turns that `#attributes` is not working with `item` type: https://api.drupal.org/api/drupal/developer%21topics%21forms_api_reference.html/7.x#item 😞

**Comment by opi** [comment]
The `aria-hidden` attribute should be on the `#prefix`, so we can do:
`#prefix => '<span aria-hidden="true"> . t('Limit to') . '</span>'`. 

What do you think ?

**Comment by opi** [comment]
New PR https://github.com/backdrop/backdrop/pull/2302 with:
- @jenlampton comment https://github.com/backdrop/backdrop/pull/2226#pullrequestreview-151875128 fixed in e8e1cf38afae60a7e709ca3c0f8731f6df36af6c
- #a11y issues https://github.com/backdrop/backdrop-issues/issues/3192#issuecomment-408770997 addressed in c5049256aea8cfe3518afeda1b62ade83526f270

**Comment by nico3333fr** [comment]
For accessibility, you might add `id` on select (the value used in `label for="this value"`), it is better for all speech synthesis to set it up explicitly.

So when users with speech synthesis will reach inputs, it will tell them what is in the label linked to.

If you want more details, you may add ` aria-describedby="an_id"` with an extensed description, but in this case, I don't think it will be necessary. 

@goetsu : do you confirm?

**Comment by opi** [comment]
> For accessibility, you might add id on select (the value used in label for="this value"), it is better for all speech synthesis to set it up explicitly.

@nico3333fr sorry about that, the `id` **is** actually set on select, the demo was wrong on that point (too much focused on the label / aria-hidden part).

Thanks a lot for your time and review :heart:

**Comment by nico3333fr** [comment]
> Thanks a lot for your time and review ❤️

You're welcomed ;)

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/2302 looks great. Merged into 1.x for 1.11.0. Thanks everyone!
