### ISSUE TITLE
How to use translation?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3197]
So I'm researching the possibility of setting up my first multilingual website (and now that I'm living in Europe I'm guessing there'll be a lot more to come). I've never used translation/internationalisation/languages in Drupal/Backdrop before, so this is all very new to me.

My primary goal is to allow my client(s) to add content in different languages to their BD site, and for their visitors to switch between the supported languages.
To that end, I was able to install the core 'Content Translation' module (and hence the required 'Language' and 'Locale' modules) on my sandbox/testing site (I installed then on an existing site, not via the install profile). I then enabled the Estonian language (in addition to the default English), and configured the settings. I added the language switcher block, and enabled translation on a content type. All good so far.

Then I come across `admin/config/regional/translate` and see how there's no Estonian translation as yet. On the one hand, I don't think I need this as I really only need the content translated for visitors (not the backend, as I need to be able to read and manage the site still, and I don't know Estonian (yet)). On the other hand, maybe this is where we can add translation for non-node content (like field names, Views headings, etc.)...? I haven't played with this much yet, but I'm assuming there'll be text that visitors see that's not covered by the node translation system.

So then I read up in the issue queue about how to install additional language .po files, and I was able to find, download and import the Estonian D7 file, and now I have 4297/5220 (82.32%) translation status for Estonian! How do I do the rest though (the other 17.68%)? Does it have to be done manually? Or can/should I download the non-core files from Drupal's localize server and import them too (e.g. Views, Token, Pathauto, Date, etc.)?

Also, I notice that some things aren't translated (e.g. in the Admin bar: 'User Accounts', 'Functionality', etc.). If these were to be translated manually for this site, how can I utilise that for future sites I build (since Estonian will likely be a language I use over and over again)? Also, I searched for 'functionality' and filtered by Estonian and untranslated strings at `admin/config/regional/translate`, but nothing comes up... How would we translate that?

Sorry for the brain dump. New to all this and trying to get my head around it all so I can provide this as a service to future clients. Thanks!

**Comment by olafgrabienski** [comment]
@BWPanda Welcome to the wide field of multilanguage questions! I'm also interested in the topic and can provide some information after my summer holiday. For the moment just two notes:

(1) We started to build a Backdrop translation server, see the roadmap on https://github.com/backdrop-ops/localization/issues/5. I plan to continue the work there in August or September.

(2) In the meantime:

- Yes, you can import the Drupal 7 language files of modules like Views, Pathauto etc.
- To use the improved translations of a site, you can export them via the user interface. Don't remember the exact page at the moment but the export option should be available near the option to import language files.

**Comment by klonos** [comment]
@BWPanda I do not have any detailed documentation handy ATM, but here are some key concepts/things to keep in mind:

**Content translation**: Allows _the content_ of a site to be translated to other languages (this mean that the admin UI will still be in English - or whichever language you have selected during installation, or switched it post-installation). Targeted towards international/multilingual/non-English sites and their visitors. Modules https://www.drupal.org/project/entity_translation (formerly https://www.drupal.org/project/translation - sorta).

**Admin UI translation** (or "localisation"): Allows the _Drupal/Backdrop admin UI strings_ (contrib modules too) to be translated. Targeted towards international/multilingual/non-English site admins and content authors. Modules: https://www.drupal.org/project/l10n_update, http://drupal.org/project/l10n_client, https://www.drupal.org/project/i18n and all the respective ecosystem of l10n_* and i18n_* modules etc.

The interesting (read: messy) part is when content translation (or what should have been that) gets mixed with localisation ...will make your head spin 😄 😞 

I always find this useful: https://www.lullabot.com/articles/localized-and-multilingual-content-in-drupal-7

Best of luck!

**Comment by BWPanda** [comment]
Wrote this as custom code for the site I'm working on, but then decided to contribute it back as a module (will likely use it for future sites): https://github.com/backdrop-contrib/language_switcher_dropdown

**Comment by indigoxela** [comment]
Are there still open questions? (I'd bet there are... :wink: )
My question should rather be: is there something left to do in this issue or could it get closed?

**Comment by BWPanda** [comment]
Happy to close. I'm no longer doing this anymore and I'm sure those who are with similar questions can either reopen this or start new, more specific issues.
