### ISSUE TITLE
Status Report and  'Available updates' page gets Backdrop core version wrong

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3198]
## Describe your issue or idea

My site is running on Pantheon, and should be running the latest version of Backdrop core - 1.10.1.

Since updating to 1.8.1, my site occasionally throws the red dot onto the admin bar indicating something is wrong with my site. When I visit the Status Report, the `Backdrop CMS update status` line has a red X, but shows the version number is the most recent (1.10.1).
<img width="1206" alt="screen shot 2018-07-16 at 10 09 15 am" src="https://user-images.githubusercontent.com/397895/42772830-796e0330-88e0-11e8-9dd5-60a672d78b50.png">

However, when I visit the "Available Updates" page, my site shows the core version as 1.8.0, and recommends updates. 
<img width="1188" alt="screen shot 2018-07-16 at 10 10 13 am" src="https://user-images.githubusercontent.com/397895/42772931-ada9fb72-88e0-11e8-8be7-5378b5f7ede4.png">

Why would the Available Updates page think core is a different version than the Status report? And why would anything at all think Core was on version 1.8.0 -- when it's not?

**Comment by klonos** [comment]
Far fetched, but could this be related to #3128?

**Comment by klonos** [comment]
@jenlampton still care about this one, or should we close it?

**Comment by jenlampton** [comment]
Anyone else still seeing it happen? I still get it from time to time. Would
like to sort out why, and fix that.

**Comment by jenlampton** [comment]
Closing.
