### ISSUE TITLE
[UX] Allow specifying just one dimension for 'Maximum/Minimum image dimensions'

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3200]
Currently if you want to resize images that are uploaded to an image field, you have to specify both the width and the height. I'd like to be able to just specify one (e.g. width) and leave the other one blank. I get the following error message otherwise: "Both a height and width value must be specified in the Maximum image dimensions field."

I guess I can get around it by setting the height to something like '9999', but that's a bit of a hack...

---

PR https://github.com/backdrop/backdrop/pull/2259

**Comment by Graham-72** [comment]
What would you like the system to do about the unspecified dimension? Presumably leave it unlimited so that it becomes whatever the scale operation produces.

**Comment by klonos** [comment]
> Presumably leave it unlimited so that it becomes whatever the scale operation produces.

That's what I would expect.

**Comment by BWPanda** [comment]
As @klonos said, yes.

**Comment by Graham-72** [comment]
I think this would be a small but significant improvement, making life easier for the user. I have produced this PR which makes this change for both uploading of images as individual files and through WYSIWYG editing.

**Comment by Graham-72** [comment]
PR is working for uploading through WYSIWYG but not resizing properly when uploading as an individual file.

**Comment by Graham-72** [comment]
The PR **is** resizing the image field properly in the sandbox. I was mislead because the default setting for the display of the image field in a post is the 'large' image style. I have now changed it to be the original image.

**Comment by quicksketch** [comment]
This sounds good to me. I've left some feedback on the PR: https://github.com/backdrop/backdrop/pull/2259/files#diff-4243f81fe8bbbf2ed2ccaa38f1a2ea10R100

**Comment by Graham-72** [comment]
@quicksketch thanks for your feedback. I have revised the PR.

**Comment by quicksketch** [comment]
Thanks! Another review: https://github.com/backdrop/backdrop/pull/2259#pullrequestreview-146300131

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2259. Thanks @Graham-72 for the PR and updates! And thanks @BWPanda for filing the request in the first place. :+1:
