### ISSUE TITLE
APCu not detected when using PHP7.x

### ISSUE THREAD

**Issue by loopyd** [backdrop/backdrop-issues#3204]
## Describe your issue or idea

Receiving this error on a cpanel/WHM EasyApache4 vhost install of backdrop under /admin/reports/status:

> Your server is capable of displaying file upload progress, but does not have the required libraries. It is recommended to install the PECL uploadprogress library (preferred) or to install APC.

**Deprication information:**
uploadprogress was depricated in PHP>=7.0 in favor of APCu, which provides a newer alternative to the old module.  uploadprogress will not compile against PHP>=7.0 as a result of the feature deprecation.

- This error **does not** occur if you use a PHP5.6 vhost with the PECL uploadprogress module.
- The relevant entries **are** included in php.ini, and the PECL module APCu has been compiled and installed via the following command:

```
/opt/cpanel/ea-php72/root/usr/bin/pecl install apcu
...[log cropped]
The APCu module has been built successfully.
APCu module has been installed into PHP.ini
```

To further ensure the module is loaded (it should be from php.d, but I was experiencing the error still), the additional manual configurations where added to MultiPHP's PHP 7.2 .ini confiugration editor in advanced mode:

**PHP.ini in WHM for PHP 7.2:**
[relevant entries]

```
extension_dir = "/opt/cpanel/ea-php72/root/usr/lib64/php/modules"
extension=apcu.so
```

The error persists, as shown above after restarting the apache daemon and PHP-FPM.

Additionally, APCU is reporting itself __enabled__ in phpinfo() from the PHP information link in backdrop's admin panel.

__@klonos suggests:__
> @loopyd not sure, but this might be related: >https://www.drupal.org/project/supercache/issues/2833414
>Unfortunately, starting with PHP 7.0, APCu removed the option for full backwards compatibility with APC that existed with APCu in PHP 5.5 and 5.6. This means that PHP7 only accepts new APCu functions (for example apc_fetch()).
>
>The best solution for the time being would be for your own modules or contrib modules to account for both (e.g. if apc_fetch() exists, use that, else apcu_fetch()). This of course would be true for all apc_* functions.
>
>Perhaps the APC detection is broken because of this in php7
>...care to file a ticket for this in https://github.com/backdrop/backdrop-issues/issues ??
>
>...found some more APC/php7 related issues. This one seem more like it: https://www.drupal.org/project/apc/issues/2846622

This is a drupal7 known issue that requires a commit/fix.

### Steps to reproduce (if reporting a bug)
1.  Install the most recent version of Backdrop CMS.
2.  Compile and install the APCu PECL pear module.
3.  Enable the module in php.ini
4.  Restart the apache webserver.
5.  Browse to the reports section of the administrator panel, observe the error.

### Actual behavior (if reporting a bug)
The APCu module is not detected and upload progress indicators do not function.

### Expected behavior (if reporting a bug)
The APCu module is correctly detected for PHP>=7.0, and upload progress indicators work as intended without the error in the Administration->Reports section.

### Relevant version/system information (if applicable)

CENTOS 7.5 kvm
WHM/CPanel v72.0.10 stable
EasyApache4 - Apache 2.4 vhost
PHP 7.2
APCu PECL module 5.1.12

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2248

**Comment by quicksketch** [comment]
I filed a PR for this at https://github.com/backdrop/backdrop/pull/2248. It looks like it should be a fairly small increment on top of the current APC support, since APCu is a subset of APC and looks identical for upload progress support.

I don't have APCu installed on my local however. @loopyd could you try it out and verify?

**Comment by quicksketch** [comment]
>  uploadprogress was depricated in PHP>=7.0 in favor of APCu, which provides a newer alternative to the old module. uploadprogress will not compile against PHP>=7.0 as a result of the feature deprecation.

I don't think this is entirely true. APC was deprecated in favor of APCu, but it looks like PHP built-in upload progress into version 5.4 and higher: http://php.net/manual/en/session.upload-progress.php

So we should not only support APCu, but also PHP's now built-in upload progress support.

**Comment by quicksketch** [comment]
> So we should not only support APCu, but also PHP's now built-in upload progress support.

Except it appears that is nearly impossible for two reasons:

- session.upload_progress is not compatible with custom session handlers or any session stored in the database. https://bugs.php.net/bug.php?id=74131
- session.upload_progress does not work with custom session names, such as the one we use in backdrop_settings_initialize(). https://bugs.php.net/bug.php?id=64075

So unfortunately that makes using the built-in session uploading very difficult. We'd have to change the way session handling works entirely in order to use this upload support. So... for now let's just see if we can get APCu up and working.

**Comment by quicksketch** [comment]
Well, further complicating things, as has been found in the Drupal issues and elsewhere, APCu doesn't support RFC1867 on PHP 7 and higher.

*However*, I found that Ubuntu 18.04 has absolutely no problem working with `uploadprogress`. Installing is as simple as `sudo apt install php-uploadprogress`. This is with PHP 7.2.7:

```
php -i | grep uploadprogress
/etc/php/7.2/cli/conf.d/20-uploadprogress.ini,
uploadprogress
uploadprogress support => enabled
uploadprogress.file.contents_template => /tmp/upload_contents_%s => /tmp/upload_contents_%s
uploadprogress.file.filename_template => /tmp/upt_%s.txt => /tmp/upt_%s.txt
uploadprogress.get_contents => 0 => 0
```

So the situation for upload progress currently appears to be the following:

- PHP 5.x versions: Use either uploadprogress or APC.
- PHP 7.x versions:
  - PHP 7.0 can still use `uploadprogress` installed through `pecl install uploadprogress`. Some users have managed to get it working on PHP 7.1.
  - Ubuntu users in 16.10 and higher can simply use `sudo apt install php-uploadprogress`. Reports indicate this works on PHP 7.1 and 7.2.
  - APCu does not provide upload progress capabilities any longer, despite the documentation saying it's there. Here's the bug asking the docs be corrected: https://bugs.php.net/bug.php?id=75879
  - PHP's native `session.upload_progress` does not work with database sessions or custom session names, both of which we use in Backdrop.

The PECL `uploadprogress` might eventually start working again if someone starts maintaining it. It's pretty clear that someone in the Debian/Ubuntu world must have updated it for their distribution at least.

As for `APCu`, it looks like they're moving away from ever restoring upload progress support. So perhaps we should simply version check for PHP and stop suggesting the use of APC on anything 7+.

**Comment by quicksketch** [comment]
Well, perhaps we should throw out this entire idea of PHP extensions for handling progress bars. We can handle this all client-side now with minimal changes. I've filed a new issue taking that completely different approach: https://github.com/backdrop/backdrop-issues/issues/3211.

**Comment by quicksketch** [comment]
Let's close this in favor of the client-side approach that avoids APCu or `uploadprogress` entirely in https://github.com/backdrop/backdrop-issues/issues/3211.
