### ISSUE TITLE
"Select all" checkbox should check if all checkboxes are checked on page load

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3207]
## Describe your issue or idea

The "Select all" checkbox at the top of certain tables, like that a admin/content, does not check the state of the checkboxes at page load time. This came up in #3178.

### Steps to reproduce (if reporting a bug)

Visit `admin/content`. Check the "Select all" checkbox at the top of the table. All checkboxes are checked. In Firefox or Chrome, then reload the page. These browsers maintain the value of the checkboxes. But the "Select all" checkbox gets unchecked for some reasons.

### Actual behavior (if reporting a bug)

The "Select all" checkbox is not checked at page load time.

### Expected behavior (if reporting a bug)

It should remain checked.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/2245.

**Comment by herbdool** [comment]
It works!
