### ISSUE TITLE
Backdrop.attachBehaviors() fires twice after any AJAX request within a form

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3210]
## Describe your issue or idea

The Backdrop AJAX system automatically attaches behaviors to newly inserted content. The most common way of inserting content is via #ajax['callback'], which inserts new form elements into a form.

Whenever the Backdrop.ajax.commands.insert() command is fired, it attaches behaviors on the new content. But almost immediately afterwards, behaviors are attached again, but this time to the entire form. This results in the same DOM elements getting behaviors attached a second time.

The documentation states helpfully:

```
  // Reattach behaviors, if they were detached in beforeSerialize(). The
  // attachBehaviors() called on the new content from processing the response
  // commands is not sufficient, because behaviors from the entire form need
  // to be reattached.
  if (this.form) {
    var settings = this.settings || Backdrop.settings;
    Backdrop.attachBehaviors(this.form, settings);
  }
```

Which means, if we're attaching behaviors on the entire form, there's no need to attach behaviors on the individual elements. Adding a check to prevent this is easy and can save substantial processing client-side.

This mirrors a Drupal issue at https://www.drupal.org/project/drupal/issues/2958673

### Steps to reproduce

- Visit `node/add/post`.
- Upload a file. Then remove the new file. This makes it so that the file element now has been inserted via an AJAX command, and receives the double-binding.
- Upload another file. Note that the throbber shows up twice. This is because auto-upload behavior is attached twice, and then fires twice on the second upload.

### Actual behavior (if reporting a bug)

- Note that the throbber shows up twice. This is because auto-upload behavior is attached twice, and then fires twice on the second upload.

Double attachment:
![image](https://user-images.githubusercontent.com/100206/43057422-0f7e6ac0-8df7-11e8-84c4-b8f364c20435.png)

### Expected behavior (if reporting a bug)

-  Only a single attachment should occur.

Single attachment:
![image](https://user-images.githubusercontent.com/100206/43057416-029ea392-8df7-11e8-8a37-8cc4e6b7a547.png)

---

PR at https://github.com/backdrop/backdrop/pull/2251

**Comment by klonos** [comment]
I second the RTBC 👍. I see only a single throbber after applying the changes from the PR.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2251 into 1.x and 1.10.x. Thanks @klonos and @herbdool for reviewing!
