### ISSUE TITLE
Add a .once() guard on File module's AJAX uploads to prevent double-uploading

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3212]
## Describe your issue or idea

This is a related issue to the double-binding problem we have with AJAX events: https://github.com/backdrop/backdrop-issues/issues/3210

That PR will solve the double-throbber problem in the most common case, but other AJAX events can result in the same double-binding problem for File module.

### Steps to reproduce (if reporting a bug)

- Add a post at node/add/post
- For testing, open the developer tools in your browser and enable connection throttling down to "3G" in the network tab.
- Upload an image (at least 2MB).
- Remove the image.
- Upload an image again.

### Actual behavior (if reporting a bug)

- During the second upload you'll see the throbber displayed twice.

### Expected behavior (if reporting a bug)

- During the second upload only a single throbber should be shown.

This is actually worse than it looks because the second image is actually _uploaded twice_, doubling the amount of time it takes to upload on a slow connection.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2252

**Comment by alexfinnarn** [comment]
I can confirm that the attached PR fixes the double throbber issue; however, the tests are failing. I can't see which tests are failing.

**Comment by klonos** [comment]
I also confirm that the issue with the double throbber is fixed in the PR sandbox. Thanks for filing this ticket and for providing a fix @quicksketch 👍...this has annoyed me oh so many times (my OCD again 😜).

The failing tests are pointing to a missing `/core/misc/zen-ci/init_test.sh` file ...which if not mistaken has something to do with the recent work @Gormartsen and @serundeputy have been doing in order to allow zenCI to run phpcs (#3213). ...I think.

**Comment by serundeputy** [comment]
@klonos nah; nothing from #3213 is merged yet.  It was just a hiccup with the test suite/runners ... I restarted and it is happier now: https://zen.ci/backdrop/backdrop/test/test-php53-backdrop_backdrop_2252-c9c7d06

**Comment by klonos** [comment]
Thanks @serundeputy 👍 ...the php70 test has gone AWOL though.

**Comment by klonos** [comment]
@serundeputy don't be fooled ...did you actually expand the "All checks have passed" fieldset and then check the "details" links for php53 and php70? ...as I said, AWOL:

![screen shot 2018-07-29 at 9 08 33 am](https://user-images.githubusercontent.com/2423362/43361317-0c2cafb8-930f-11e8-8f33-6e84376ad1b9.png)

...this bug with zen CI has been happening for a while when you close and reopen a PR:

![screen shot 2018-07-29 at 9 09 22 am](https://user-images.githubusercontent.com/2423362/43361320-19dcec2c-930f-11e8-9a79-5c4f1b7b7d4d.png)

**Comment by serundeputy** [comment]
this is an expanded one: https://zen.ci/backdrop/backdrop/deploy/deploy-backdrop_backdrop_2252-c9c7d06-2 but i think we are getting off track on **this** issue; if there are issues with testing you wish to sort out file them and scope them.

**Comment by quicksketch** [comment]
Super, I've merged https://github.com/backdrop/backdrop/pull/2252 into 1.x and 1.10.x. Thank @alexfinnarn and @klonos for reviewing!
