### ISSUE TITLE
[META][DX] Automate phpcs code checks (linting) against all backdrop/backdrop PRs.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#3213]
## Describe your issue or idea

Run `phpcs` Backdrop code standards checks against all backdrop/backdrop PRs.
  * Devs get near real time feedback on code standards violations that can be addressed before a human gets the time to review it for technical implementation.

### Actual behavior (if reporting a bug)

* Currently PRs are not checked for code standards except by humans.

### Expected behavior (if reporting a bug)

* Automate the `phpcs` checks in ZenCI

-----

There are two PRs on the table to enable this to happen:

  * https://github.com/backdrop-ops/backdropcms.org/pull/460
    * This gets BackdropCMS to fire the ZenCI requests
  * https://github.com/backdrop/backdrop/pull/2244
    * this one against core provides the test to run

----

To run the `phpcs` checks locally follow the instructions in the README.md here: https://packagist.org/packages/backdrop/coder

----

Here is an example of running `phpcs` locally against one file:

```bash
vendor/bin/phpcs --standard=./vendor/backdrop/coder/coder_sniffer/Backdrop core/modules/admin_bar/admin_bar.inc
```

and the output:

```bash

FILE: ...f/code/sites/backdrop-ops/backdrop/core/modules/admin_bar/admin_bar.inc
--------------------------------------------------------------------------------
FOUND 18 ERROR(S) AND 3 WARNING(S) AFFECTING 20 LINE(S)
--------------------------------------------------------------------------------
  35 | WARNING | Line exceeds 80 characters; contains 81 characters
 124 | WARNING | Line exceeds 80 characters; contains 81 characters
 126 | ERROR   | Missing parameter type at position 1
 168 | ERROR   | Missing parameter type at position 1
 172 | ERROR   | Data type of return value is missing
 215 | ERROR   | Inline comments must start with a capital letter
 252 | ERROR   | Doc comment for var A does not match actual variable name
     |         | $tree at position 1
 252 | ERROR   | Parameter comment must be on the next line at position 1
 254 | ERROR   | Missing parameter type at position 2
 256 | ERROR   | Missing parameter type at position 3
 367 | ERROR   | Missing parameter type at position 1
 369 | ERROR   | Missing parameter type at position 2
 396 | ERROR   | The first index in a multi-value array must be on a new line
 399 | ERROR   | Array indentation error, expected 6 spaces but found 4
 408 | ERROR   | Missing parameter type at position 1
 465 | ERROR   | Missing parameter type at position 1
 469 | ERROR   | Data type of return value is missing
 479 | ERROR   | Inline comments must end in full-stops, exclamation marks, or
     |         | question marks
 757 | ERROR   | Missing parameter type at position 1
 821 | WARNING | Format should be "* Implements hook_foo().", "* Implements
     |         | hook_foo_BAR_ID_bar() for xyz_bar().",, "* Implements
     |         | hook_foo_BAR_ID_bar() for xyz-bar.html.twig.", or "*
     |         | Implements hook_foo_BAR_ID_bar() for xyz-bar.tpl.php.".
 834 | ERROR   | Missing parameter type at position 1
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------


```

----

* We can break this up into per module tasks.  
* We should file the PRs against this branch `https://github.com/backdrop/backdrop/tree/phpcs` rather than the `1.x` branch until we get complete coverge

Each participant should self assign themselves a core module and add it to the list here:

`core/includes`
----
 - [ ] `database` @serundeputy
   - [x] `mysql` @serundeputy
  - [ ] `filetransfer`

`core/modules`
-----

- [x] `admin_bar` @serundeputy
- [x] `block` @serundeputy
- [x] `book` @serundeputy
- [ ] `ckeditor`
- [ ] `color`
- [ ] `comment`
- [ ] `config`
- [ ] `contact`
- [ ] `contextual`
- [ ] `dashboard`
- [ ] `date`
- [ ] `dblog`
- [ ] `email`
- [ ] `entity`
- [ ] `field`
- [ ] `field_ui`
- [ ] `file`
- [ ] `filter`
- [ ] `image`
- [ ] `installer`
- [ ] `language`
- [ ] `layout`
- [ ] `link`
- [ ] `locale`
- [ ] `menu`
- [ ] `node`
- [ ] `path`
- [ ] `redirect`
- [ ] `search`
- [ ] `simpletest`
- [ ] `syslog`
- [ ] `system`
- [ ] `taxonomy`
- [ ] `translation`
- [ ] `update`
- [ ] `user`
- [ ] `views`
- [ ] `views_ui`

**Comment by serundeputy** [comment]
@quicksketch for `core/module/X` on the `X.info` files `phpcs` reports:

```
geoff@yep backdrop (phpcs) exit code: [0] $ vendor/bin/phpcs --standard=./vendor/backdrop/coder/coder_sniffer/Backdrop core/modules/admin_bar/admin_bar.info

FILE: .../code/sites/backdrop-ops/backdrop/core/modules/admin_bar/admin_bar.info
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 1 | ERROR | "core" property is missing in the info file
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

should we be adding the `core` property to the info files or write some magic into the `phpcs` rules to ignore this for `core` modules` but use it for custom and contrib?

**Comment by serundeputy** [comment]
@quicksketch there are probably going to be a fair amount of these lower_case class names; here is what I did so far:

```php
// @codingStandardsIgnoreStart
// @TODO: Make all classes CamelCase and class methods lowerComelCase in 2.x.
class views_plugin_argument_default_book_root extends views_plugin_argument_default_node {	class views_plugin_argument_default_book_root extends views_plugin_argument_default_node {
  function get_argument() {	  function get_argument() {
    // Use the argument_default_node plugin to get the nid argument.	    // Use the argument_default_node plugin to get the nid argument.
@@ -19,3 +21,4 @@ class views_plugin_argument_default_book_root extends views_plugin_argument_defa
    }	    }
  }	  }
}	}
// @codingStandardsIgnoreEnd
```

seem appropriate?  what do you think?

**Comment by serundeputy** [comment]
> I like UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY if that works? I'm all about being lazy :) Can that happen for the subtasks on the meta-issue?

I know the php version for that version of phpcs is > php 5.3 so i'm not sure we could do that

**Comment by klonos** [comment]
Mentioning #659

**Comment by klonos** [comment]
Comment by @drupol in https://github.com/backdrop/backdrop-issues/issues/3896#issuecomment-506693859:

> Hi,
> 
> I started to do this project: [drupol/backdrop-conventions](https://packagist.org/packages/drupol/backdrop-conventions), maybe it would be something to evaluate ?
> 
> It's based on [Grumphp](https://github.com/phpro/grumphp).

**Comment by klonos** [comment]
I commented re this on Gitter, but I was sure that we had an issue someplace for this 😄 

I just came across https://github.com/marketplace/hound which seems to be free for open-source, public projects

> Hound reviews your code then comments directly in Pull Requests, helping your team maintain consistent coding style and high code quality. ...integrates with your existing workflow by reviewing changes and commenting the moment a Pull Request is created or updated.

![image](https://user-images.githubusercontent.com/2423362/63230882-2eb50980-c21c-11e9-9d59-bed16d914787.png)

![image](https://user-images.githubusercontent.com/2423362/63230884-3379bd80-c21c-11e9-8a6f-d3c983308f25.png)

Supports phpcs: http://help.houndci.com/en/articles/2461415-supported-linters

...seems all we need is a subscription, and adding a .hound.yml file to the repo.

**Comment by klonos** [comment]
...also https://github.com/marketplace/imgbot which is free!

![image](https://user-images.githubusercontent.com/2423362/63230889-54daa980-c21c-11e9-8402-0ff9eec17fa3.png)

**Comment by BWPanda** [comment]
@serundeputy What is needed to make this happen? i.e. Can/how can I help?

**Comment by quicksketch** [comment]
@serundeputy Part of the recent changes to the packager on BackdropCMS.org allows us to now exclude certain files from the ZIP package files on releases. It already excludes .zenci.yml and .gitlc.yml files.

I'd love to have us switch to a `.zenci.yml` file (just copy the current .gitlc.yml off of backdropcms.org) and put it in the repository. And that way we'll be able to verify that the changes in the YML file work as expected all in one PR, since the code style checks will apply to the PR on which the new YML file is included. Could you rework this into a single PR just against Backdrop core?

**Comment by quicksketch** [comment]
On further thought, for something like this where we're just running code checks, could we use GitHub actions? We have actions enabled on the Backdrop repository, so you should be able to put scripting into a ` .github/workflows/phpcs.yml` file (or similarly named) and have it run. @jenlampton tried an example one on the `backdrop-issues` repository a while back: https://github.com/backdrop/backdrop-issues/commit/fd6058d8a4476eaa9f039db9ec803a128b244c82

**Comment by jenlampton** [comment]
@quicksketch I don't think I ever got any actions working, but back then actions were new and maybe still had some issues. We should set one up for coding standards and see if we can get it working :)

**Comment by jenlampton** [comment]
I started working on PHPCS reviews via github actions last week, and I was eventually able to get them working. I jotted down some quick notes on the changes that were required in [Let's get PHP_CodeSniffer working with Backdrop
#10](https://github.com/backdrop-contrib/coder_review/issues/10#issuecomment-643516562) since @alanmels was having the same problems.

**Comment by jenlampton** [comment]
> @serundeputy started looking at GH actions for this, but need more research … I’ve not determined where and how they actually load PHPCS into the action, so that I can inject `backdrop/coder` into it as well

The project is now named `coder_review` for Backdrop, and from my testing a `git clone` did not work, but a `wget` did. I think I read somewhere that a `curl` would also work, so to remove the specific version and grab latest, I was going to try `curl --silent "https://api.github.com/repos/$1/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'` instead, but I didn't get there last week.

**Comment by quicksketch** [comment]
In the rapidly changing landscape of GitHub Linters, GitHub has published their own official linter for use through GitHub Actions: https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/

Unfortunately it does not yet support PHP, but there's a lot of activity on that front: https://github.com/github/super-linter/issues/122

However regardless of which approach we use, we'll need to make sure that our linting rules for phpcs are up-to-date.

**Comment by quicksketch** [comment]
And the "super-linter" now supports PHP. Yay! But it's extremely rudimentary, just syntax checking, not code style. We may want to still pursue our own linter after all.

**Comment by BWPanda** [comment]
Heard some discussion about this in the dev meeting, and I was wondering, if we're going to be using this for all Backdrop core PRs etc., should the code styleguide be in Backdrop core rather than a contrib module...?

@serundeputy is doing this with [Drush](https://github.com/backdrop-contrib/backdrop-drush-extension), and he uses his own repo: https://github.com/serundeputy/coder He basically forked the contrib module, then removed all the other stuff and just left the code sniffer stuff (the contrib module does a lot of different things it seems).

I was thinking we should standardise this by merging @serundeputy's repo into core (then Drush can use that too), and then removing that part of it from the contrib module. So the contrib module does everything else it currently does, and just the code sniffer part is in core.

Make sense?

**Comment by klonos** [comment]
> Make sense?

It does to me.

**Comment by jenlampton** [comment]
The problem with having it in core is that it will be used by less than 20% of actual Backdrop sites, which goes against our principles. Maybe we can have the packager strip it out? 

Also, the "code styleguide" isn't a generic set of instructions for Backdrop, it's specifically for PHPCS...  (not sure if that matters, other than to say "it's usless" by itself)

**Comment by BWPanda** [comment]
Ok, so not core, but what about its own repo in backup-ops then?

My point being basically that as far as I'm aware, the code we need to integrate with PHP Code Sniffer (like all the Backdrop-specific styleguide stuff) in lumped in to a module that does other things too. Related things, sure, but not necessary, for example, when you're testing a core PR against our coding standards. I believe this is why @serundeputy forked the contrib module and pulled out all that other stuff, because it wasn't necessary to include all that each time you just want to check code on the command line.

So I suggest we pull that PHPCS stuff out of the Coder Review module, and then put it in its own repo (either backup-ops or its own contrib module). Then anyone that needs it (Backdrop core when testing PRs, Drush, Coder Review, etc.) can depend on it.

**Comment by jenlampton** [comment]
> So I suggest we pull that PHPCS stuff out of the Coder Review module, and then put it in its own repo (either backdrop-ops or its own contrib module). Then anyone that needs it (Backdrop core when testing PRs, Drush, Coder Review, etc.) can depend on it.

I think that makes sense. This is essentially what the Drupal `coder` contrib project is right now.

I was thinking that we might want to fork that one (instead of using what's in coder_review) because Drupal's project already works with PHPCS 3.x and with Drupal 7. Maybe we even call ours "coder" and leave it in backdrop-contrib? 

Then comes the other question I've been struggling with: what version number do put on it? If we wanted to match the Drupal version numbering it would end up 8.3.9 -- which I have mixed feelings about.

**Comment by BWPanda** [comment]
> what version number do put on it?

Does it need a version number...? As a "command line tool" and "not a module" (source: https://www.drupal.org/project/coder) can't we just have a 1.x branch that has Backdrop's up-to-date coding standards?

> it's specifically for PHPCS

What if we called it something like `backdrop_phpcs` then?

**Comment by klonos** [comment]
> As a "command line tool" and "not a module"

Good catch, ...but even drush has versions: https://github.com/backdrop-contrib/backdrop-drush-extension/releases

> What if we called it something like `backdrop_phpcs` then?

I like that 👍

**Comment by jenlampton** [comment]
Why change the name from coder though, if it's the same thing? Won't it be
easier for people coming from Drupal?

**Comment by BWPanda** [comment]
> it will be used by less than 20% of actual Backdrop sites

> Won't it be easier for people coming from Drupal?

What percentage of Backdrop sites using Coder will be coming from Drupal...? :wink:

**Comment by jenlampton** [comment]
In today's weekly meeting @quicksietch pointed out that in the future we may also want to include javascript testing, and that we might want the code for those js tests to live in the same project as the code for our PHP tests. That way, if we made a change to our coding standards that affected both, we could update the project with one PR. 

So maybe including `phpcs` in the project is too specific. What about something like `backdrop_standards`? Though my preference is still to stick with `coder`.

> What percentage of Backdrop sites using Coder will be coming from Drupal...?

Right now: 100% of people using coder are coming from Drupal. But as Backdrop grows that number should decrease :)

**Comment by BWPanda** [comment]
Here're some thing that might be of interest:

- https://github.com/marketplace/actions/phpcs-code-review (defaults to Wordpress standards, but can be customised)
- https://github.com/marketplace/actions/phpcs-drupal-check-with-annotations (uses Drupal standards, but might be hard-coded...)

If they don't suit, there are plenty of others: https://github.com/marketplace?type=actions&query=phpcs

**Comment by BWPanda** [comment]
It seems we got hung up on the name. But that aside...

> I was thinking that we might want to fork that one (instead of using what's in coder_review) because Drupal's project already works with PHPCS 3.x and with Drupal 7.

We need to decide if we fork Drupal's Coder module, or if we just pull the [`coder_sniffer` directory](https://github.com/backdrop-contrib/coder_review/tree/1.x-1.x/coder_sniffer) out of [`coder_review`](https://github.com/backdrop-contrib/coder_review) and make it its own project that others can depend on.

@docwilmot is the current maintainer for `coder_review`. Thoughts?

**Comment by BWPanda** [comment]
I'm asking again now because I'm wanting to add PHPCS checks to Bee, and I'd rather not have to download the entire `coder_review` module when all I need is what's in the `coder_sniffer` subdirectory...

**Comment by docwilmot** [comment]
Just including the directory makes sense.

**Comment by BWPanda** [comment]
@docwilmot Do you want to do that, or you'd rather someone else maintain that part of the code...?

**Comment by indigoxela** [comment]
I'm not sure, where to add the PR, but it seems that I got some basic linter setup working, which only fires on updated/added files and adds annotations.

Example:
https://github.com/backdrop/backdrop/pull/3749/files

**Comment by quicksketch** [comment]
That looks great @indigoxela! I'm a fan of the GitHub Actions to avoid a lot of custom scripting in our own repository. Now if we can work out applying Backdrop-specific code style.

**Comment by serundeputy** [comment]
@quicksketch is this https://github.com/backdrop/backdrop/pull/3749/files#diff-a036b60d22557d7f21abeaecaa42088f12680e7d72056f9d7de8c0db426984a6R32 not backdrop specific? 

idk ... it's been a few years lolz;

**Comment by BWPanda** [comment]
Since this was originally raised for Zen.CI and since `phpcs` has been implemented as a GitHub action, I'm closing this issue. The fixing of existing coding issues throughout core will be handled in https://github.com/backdrop/backdrop-issues/issues/6004
