### ISSUE TITLE
[UX] Contact form categories: better messages

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3215]
Part of the #3023 META...

1. When the "Recipients" text area contains more than one invalid email addresses, the validation message only tells the user about the first one that is not valid:

    <img width="533" alt="screen shot 2018-07-28 at 10 11 55 pm" src="https://user-images.githubusercontent.com/2423362/43356446-24367e28-92b4-11e8-8eb6-1a2a8719e5c5.png">

    I think we should either be listing all invalid addresses, or in the case where more than one, have the message be generic, like "Multiple invalid email addresses detected." or something.

2. The success message is "Category `xyz` has been saved/deleted.". I think that it should be "Contact form category `xyz` has been saved." instead.

    <img width="313" alt="screen shot 2018-07-28 at 10 33 38 pm" src="https://user-images.githubusercontent.com/2423362/43356584-898bf8f0-92b6-11e8-9cbd-754a9a854dc2.png">

    <img width="329" alt="screen shot 2018-07-28 at 10 45 22 pm" src="https://user-images.githubusercontent.com/2423362/43356653-06ab1eb4-92b8-11e8-89b0-67ce353ebc02.png">

    ...especially for the watchdog message:

    <img width="763" alt="screen shot 2018-07-28 at 10 46 32 pm" src="https://user-images.githubusercontent.com/2423362/43356660-2a16b1ba-92b8-11e8-8abf-8382c322618e.png">

---
PR https://github.com/backdrop/backdrop/pull/2257

**Comment by opi** [comment]
Creating PR https://github.com/backdrop/backdrop/pull/2257 as a starter for discussion.

1. Here are the 2 error messages, depending if there is one or more invalid addresses:
    - test@wrong is an invalid e-mail address.
    - test@wrong, more, error are invalid e-mail addresses.

2. Totally agree

**Comment by klonos** [comment]
...the way this is currently implemented in the PR, we check whether there is one or multiple invalid email addresses. If we wanted to achieve "natural language", we should be having the message including an "and" between the previous to last and the last item. Something like this: https://stackoverflow.com/questions/8586141/implode-array-with-and-add-and-before-last-item

...but this complicates things even more code-wise. I think that it'd be better, and more readable if we said something like "The following are not valid email addresses:" ...and then we had the invalid ones in a list.

**Comment by opi** [comment]
Poll:
1. "The following are not valid email addresses: aaa, bbb, ccc" 
2. "The following email addresses are not valid: aaa, bbb, ccc"

**Comment by klonos** [comment]
Either is fine by me.

**Comment by opi** [comment]
PR updated with this message: `The following email addresses are not valid: %recipients.`.

**Comment by opi** [comment]
PR updated with `The following email addresses are invalid: %recipients.`. Mostly because `'%recipient is an invalid e-mail address.'` should be already translated in most cases.

**Comment by klonos** [comment]
Yep, RTBC 😉

**Comment by opi** [comment]
PR rebase against 1.x, and updated with a proper format_plural usage. Back to "need review" then.

**Comment by opi** [comment]
@serundeputy is [this long line](https://github.com/backdrop/backdrop/pull/2257/files#diff-037ce3d000dd806422b7fda44dddab91R286) OK with coding standards ?

**Comment by herbdool** [comment]
Tested and looks good to me. 

@opi that line doesn't look any longer than others nearby.

**Comment by quicksketch** [comment]
To avoid unnecessary string changes in 1.10.x, I've merged https://github.com/backdrop/backdrop/pull/2257 into 1.x only.

Thanks everyone!
