### ISSUE TITLE
[UX] Contact form categories: recipients should be rendered as a list

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3216]
Part of the #3023 META...

Current situation (single line of text w/o spaces):

<img width="1270" alt="screen shot 2018-07-28 at 10 48 38 pm" src="https://user-images.githubusercontent.com/2423362/43356683-8127b490-92b8-11e8-936d-87ed31e2b247.png">

These should be rendered as a list.

---
PR https://github.com/backdrop/backdrop/pull/2256

**Comment by opi** [comment]
*from https://github.com/backdrop/backdrop-issues/issues/2872#issuecomment-408606979*
> We could be sorting email addresses alphabetically for an added bonus. This would help in cases where these lists get long. I would first go by grouping by domain, then alpha sorting for each domain.

I agree with rendering recipients as list, but sorting addresses alphabetically, and/or by domain can be confusing for user : The recipients order would be different between the overview page and the category edit form. Not sure this is good UX.

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2256 simple PR with a line break added for each recipient address.

**Comment by klonos** [comment]
Agreed about the alpha order, but I still think that it'd be better to have the emails rendered as a list. That is the best option semantically (because it is a list of things), and this is the pattern being followed elsewhere in the admin UI:

<img width="1187" alt="screen shot 2018-07-30 at 10 17 21 pm" src="https://user-images.githubusercontent.com/2423362/43396981-b1a66d48-9446-11e8-94ee-77f5a01cb625.png">

**Comment by opi** [comment]
PR updated with a proper `<ul><li>` structure. Note that this structure is used even with only one recipient.

![](https://i.imgur.com/aR0sCn7.png)

**Comment by klonos** [comment]
> Note that this structure is used even with only one recipient.

That's what currently happens with the list of roles in the user account page too. I personally do not find this annoying in these cases. It is just a clearer indication that this specific thing can have more than one items.

![its good](https://user-images.githubusercontent.com/2423362/43435885-5c60bc9c-94c5-11e8-941a-18a928d258a5.gif)

**Comment by klonos** [comment]
I have left a minor comment in the PR, but in general RTBC from me 😄

**Comment by opi** [comment]
Using `theme('item_list')` now as suggested by @klonos ; I guess we're RTBC now, if you can review a last time and set the proper label, thx !

**Comment by klonos** [comment]
Poifect! RTBC from me 👍

**Comment by quicksketch** [comment]
Thanks @opi and @klonos! Merged https://github.com/backdrop/backdrop/pull/2256 into 1.x for 1.11.0.
