### ISSUE TITLE
Views warns "All changes are stored temporarily" even when nothing has changed

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#3219]
## Describe your issue or idea

Incorrect message on views page warns user that they have unsaved changes, even when there are no unsaved changes. 

A colleague of me pointed this out and suggested that he found this very confusing in situations where he knew that he had not made any actual changes.

### Steps to reproduce (if reporting a bug)

1. Open an existing view
2. Click on the "format" option
3. Click on "Cancel"
4. Notice that BackdropCMS displays a warning "* All changes are stored temporarily. Click Save to make your changes permanent. Click Cancel to discard your changes." even though user has not actually made any changes.

### Actual behavior (if reporting a bug)

Follow above steps and see this message "* All changes are stored temporarily. Click Save to make your changes permanent. Click Cancel to discard your changes."

### Expected behavior (if reporting a bug)

I would only expect to see the "All changes are stored temporarily" message if I have actually made a change. 

### Relevant version/system information (if applicable)

I checked a Drupal 7 site to see if I got the same results, but I did not.

**Comment by stpaultim** [comment]
![administer_user_accounts__user_account____riverton](https://user-images.githubusercontent.com/3144571/43361169-c61650dc-928d-11e8-8d8a-daf8f5579d28.png)

**Comment by klonos** [comment]
@stpaultim, waaay ahead of you: #2391 😄

**Comment by stpaultim** [comment]
Looked like something that would have already been reported, but my search did not turn up an existing issue. Thanks!!

**Comment by klonos** [comment]
@stpaultim I have added the "All changes are stored temporarily" text in the issue summary, so that the issue comes up in the results when one searches using that string 😉
