### ISSUE TITLE
settings.php installer error (bad database_prefix and connection array)

### ISSUE THREAD

**Issue by skaught-** [backdrop/backdrop-issues#3223]
## Describe your issue or idea
  installer writes bad database_prefix array.
 
### Steps to reproduce (if reporting a bug)
  install 1.10.1. php7.1.12
  add dbase creds (as per install steps) -- had first used dbase name "back_1_10_1"
   error:  PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /local/backdrop1.10.1/settings.php on line 17

### Actual behavior (if reporting a bug)
   settings.php ln 16 start
<pre>
$database_prefix = '';
  'default' => '',
);
</pre>

### Expected behavior (if reporting a bug)
  app to install. (:
<pre>
$database_prefix = array(
  'default' => '',
);

</pre>

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2350

**Comment by klonos** [comment]
Hello @skaught- I have tried to reproduce this:

- Span up a local with php7.1.20 and mariaDB 5.7.22
- Cloned backdrop
- Checked out 1.10.1
- Started installation and used `back_1_10_1` as database name (have configured that earlier)

Installation finished successfully, without any errors. Heres the resulting db config block in settings.php post-installation:

```
$database = 'mysql://dbuser:dbpass@127.0.0.1/back_1_10_1';
$database_prefix = 'dbpre_';
```

**Comment by skaught-** [comment]
i did not add a database_prefix at all. 
also, had used pre build .zip downloaded from website link. not cloned repo.
was using sql 5.6.38, for the record.  but it seems the write to settings.php failled.

**Comment by klonos** [comment]
@skaught- I do not have the luxury of time to set up a test environment with your exact specs (php/mysql), but I will have a go at it using the .zip file from b.org. I will let you know how it goes.

In the meantime, it strikes odd to me by something being written in the `$database_prefix` variable in settings.php, while you say that you have specified no prefix. Hmm...

**Comment by klonos** [comment]
...OK, I have tested again, this time using the .zip from b.org. No problems this time either.

Curious @skaught-, was this a one-off? Can you reproduce on the same environment if you run the installation from scratch (if that is an option)?

**Comment by klonos** [comment]
...also noting that the default settings.php file looks like this before installation:

```
/**
 * Database configuration:
 *
 * Most sites can configure their database by entering the connection string
 * below. If using master/slave databases or multiple connections, see the
 * advanced database documentation at
 * https://api.backdropcms.org/database-configuration
 */
$database = 'mysql://user:pass@localhost/database_name';
$database_prefix = '';
```

...so I am not sure where this is coming from:

```
$database_prefix = '';
  'default' => '',
);
```

...and I am not sure how/why the `$database_prefix` becomes an array(?).

**Comment by chill-fpraz** [comment]
I had the same problem upon install from the downloaded .zip file on backdropcms.org homepage:

- Mac OS 10.13.6
- MAMP PRO 4.5
- PHP 5.6.32
- MySQL 5.6.38

Steps:

1. Downloaded zip from backdrop homepage.
2. Unzipped, moved to local mamp site folder
3. Created DB in phpmyadmin
4. Opened browser to local MAMP site
5. Went through install page, added lang, db name, db uname, and dbpassword.
6. Save and continue.
7. HTTP error 500 in browser.
8. PHP error log: PHP Parse error:  syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /Users/xxxxx/Sites/backdrop/settings.php on line 17

Checking settings.php file: 

**Before install**

```
$database = 'mysql://user:pass@localhost/database_name';
$database_prefix = '';
```

**After install page**

```
$database = 'mysql://root:mydbpasswordhere@127.0.0.1/backdrop';
$database_prefix = '';
  'default' => '',
);
```

**Comment by olafgrabienski** [comment]
Today I ran into this installation issue as well. Unfortunately I don't have any information to add, expect the Backdrop version which was a fresh 1.11.0, downloaded via `wget` from Github.

After noticing the issue, I removed the part

```
  'default' => '',
);
```
from `settings.php`,  and the installation ran without problems.

**Comment by olafgrabienski** [comment]
> ...and I am not sure how/why the $database_prefix becomes an array - https://github.com/backdrop/backdrop-issues/issues/3223#issuecomment-409752621 by @klonos 

I guess it's from https://github.com/backdrop/backdrop/blob/1.x/core/includes/install.core.inc#L1080:

```
$settings['database_prefix'] = array(
    'value' => $db_settings['prefix'],
  );
```

Don't have the required coding skills to understand what's happening though.

**Comment by olafgrabienski** [comment]
@quinnanya reported the same issue (same PHP notice during install) in #3342 and found a different workaround:

> I started over (deleted the backdrop directory and put in a fresh one), and in the installer, opened the "advanced options". I realized that the host automatically gets populated with 127.0.0.1, and I created the user under localhost. Once I changed the database host to localhost under "advanced options", I was able to install it successfully.

Still not understanding what's the reason for the issue. Anyone else?

**Comment by olafgrabienski** [comment]
So far, it was difficult to reproduce the installation error intentionally. If I understand the report in #3342 correctly, it should be reproducable with an environment that is configured to use `localhost` instead of `127.0.0.1`.

**Comment by quinnanya** [comment]
I get it under two conditions: when I've assigned a user to the database using `localhost` or `all` (%). I've been creating the databases and users via PHPMyAdmin on MAMP. It's possible there's something MAMP-specific going on here, maybe?

**Comment by klonos** [comment]
@chill-fpraz also mentions using MAMP. @olafgrabienski? @skaught-?

**Comment by olafgrabienski** [comment]
@klonos No MAMP -- as far as I remember it was on a remote server (shared hosting), don't remember the which one, though.

**Comment by skaught** [comment]
yes, mamp is my goto local server.

**Comment by klonos** [comment]
Thanks @skaught- 👍 

Can I please get everyone that has reported this issue to also state their PHP and MySQL versions?

**Comment by olafgrabienski** [comment]
I *think* it was a certain site: If so, here is the status report information:

- MySQL Database: MySQL, MariaDB, or equivalent version 5.6.34
- PHP: Version: 7.1.12

**Comment by klonos** [comment]
Thanks @chill-fpraz 👍 ...I think that we now have STR. I cannot confirm yet, as I am working on other issues ATM, but will do soon as I get a chance.

**Comment by quicksketch** [comment]
Thanks @chill-fpraz, @quinnanya, and @olafgrabienski for all the amazingly detailed reports. I reproduced this in the opposite situation: where 127.0.0.1 works for me but localhost does not. So if I change the host to "localhost" during the installer, I get the same problem.

This problem seems to be in the exception handling we added in 1.11.0. Where we wanted to make it so that both `localhost` and `127.0.0.1` would automatically be attempted if either one was used. When we rewrite the settings.php file a second time to try the alternative, we accidentally used the full array version of database prefix instead of choosing just the default key within the array.

PR at https://github.com/backdrop/backdrop/pull/2350 should fix this. Could you verify this solves the installation problem when the wrong host is used during the installer?

**Comment by chill-fpraz** [comment]
@quicksketch PR at [backdrop/backdrop#2350](https://github.com/backdrop/backdrop/pull/2350) worked for me!

MAMP PRO 4.5
PHP 7.2.1
MySQL 5.6.38

Thank you!

**Comment by klonos** [comment]
@quinnanya do you have the time/energy to try https://github.com/backdrop/backdrop/pull/2350 and report if that fixed the issue without you having to manually change to `localhost`?

**Comment by quinnanya** [comment]
Will give it a try tomorrow and report back!

**Comment by quinnanya** [comment]
@klonos Just tried that against v1.11.3 and it does the trick! (Installation worked regardless of whether the admin user was created under localhost or "any host".)

**Comment by jenlampton** [comment]
Setting to RTBC based on feedback from @quinnanya and @chill-fpraz.

I also use MAMP, but have not been able to reproduce any issues with installation since the localhost/127.0.0.1 change in 1.11.0. I'm not sure what's different about my MAMP set-up?

**Comment by quinnanya** [comment]
@jenlampton FWIW, I'm using MAMP 5.1 without any modifications from the defaults. PHP 7.2.8, MySQL 5.7.23.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2350 into 1.x and 1.11.x. Thanks everyone! Sorry this wasn't in 1.11.3, it'll be in the next release!
