### ISSUE TITLE
Document all global variables

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3227]
https://api.backdropcms.org/api/backdrop/globals lists just two variables. There are many more that should be added here (just grep core for `global $`; e.g. $theme, $base_url, etc.).

**Comment by stpaultim** [comment]
It's not clear to me if this task requires experience with Backdrop CMS to be able to identify and document these variables. I am thinking that for OSD, @jenlampton might be able to provide some participants with instructions on how to work on this task. 

If this task is actually inappropriate for beginners in the issue queue (with some limited assistance), then please remove the "Good First Issue" tag.

**Comment by BWPanda** [comment]
Closing as a duplicate of https://github.com/backdrop-ops/api.backdropcms.org/issues/38
