### ISSUE TITLE
Decide if we need to include the Spectrum library and whether we should be using that instead of Farbtastic

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3239]
Spectrum has originally been included as part of the PR in #3186, but was then removed with the intention to be discussed in this follow-up (which basically makes this part of #1905).

The [Spectrum library](http://bgrins.github.io/spectrum/) acts as a shim for IE browsers that do not support native color pickers.

[Farbtastic](https://acko.net/blog/farbtastic-jquery-color-picker-plug-in/) is a similar library. It has been in Drupal core since D5, but it is not being used at the moment (not in core, what about contrib though?), and has not been updated since Jan 2007.

All modern browsers besides IE are using native color pickers now. Removing Farbtastic would not "break" functionality per se, because things would simply degrade the same way as when javascript is disabled, i.e. using the hex color field. Having said that, removing a library is an API change, and although we are open to API *additions*, API changes/removals are not endorsed, and are being pushed to Backdrop 2.0.

Next steps: discuss/decide/do 😄

**Comment by hosef** [comment]
It was reported in #3295 that Safari does not support the color HTML input type. I also checked out https://caniuse.com/#feat=input-color and it appears that Safari for iOS also does not support the color element.

**Comment by hosef** [comment]
Backdrop already has Form API elements for all of the HTML 5 input types, so you can add
```php
<?php
$form[my_color_field] = array(
  '#type' => 'color',
  '#title' => t('My Color Field'),
  '#default_value' => '#123456',
);
```
to any form on the site and it will validate and handle everything as one would expect.

The only thing we would need to add from the color_field module is the Field API widgets to put them on content types and the Spectrum library to support older browsers.

**Comment by hosef** [comment]
An example of how the Form API element could be used right now is adding a block style that allowed the text color and background color to be changed on a per block basis with no theme changes.

![colorable_style_example](https://user-images.githubusercontent.com/1253691/50058357-daf19e00-012b-11e9-80cb-5add1709444f.png)

**Comment by jlfranklin** [comment]
Adding entire libraries to core?  I think it would be better to detect non-conforming browsers in the color widget and fall back to a simple text field, with a way to allow modules to override the color widget.

**Comment by klonos** [comment]
Just noting that Safari currently has ~15% global market share, although that is across all devices. If you limit that to desktops/laptops, that number drops down to less than 5%.

**Comment by jenlampton** [comment]
no PR here, removing milestone.

**Comment by hosef** [comment]
As of Safari 12.1, Safari now supports the Color input type. This means that the only browser that does not support the color module now is Internet Explorer.

I am going to close this issue since the amount of people who would be helped by this is Significantly reduced, and IE11 provides a fallback as a text box so it is still possible to use the color module although it is more cumbersome.

**Comment by klonos** [comment]
I agree 👍 ...IE global usage is so low, that it's not included in certain stats:

https://gs.statcounter.com/browser-market-share
https://caniuse.com/usage_table.php
