### ISSUE TITLE
[DX] Add Styleguide module in core.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3240]
I have brought up this idea in other issues in the past (like #1106 and #3186)...

As a themer, I would like to make sure that all possible elements have been properly styled in my theme. We are doing a great job in #3186 by adding a way for themers to browse their entire site using a separate theme than the one that is set as the default, but in order for one to be sure that they have styled every element properly, they would have to visit many pages, which makes this task tedious.

https://github.com/backdrop-contrib/styleguide provides a single page with an overview of all elements. So when one starts building a new theme, they have a single place to inspect their work. Similarly, when a themer has been requested to make changes to a theme, they'd have a single place to see if their recent changes have broken any previous styling. Once you finish the job, you'd also have a single place where people can do QA testing, and a single place to showcase the new design to the site owner.

Is this something that would be useful in core you think?

**Comment by jenlampton** [comment]
After watching @Pol's demo today in the Backdrop virtual user group, I can see how having a styleguide in core would be a real win for theme developers. Since we need to foster the theme developer community in Backdrop, I see this as a real win.

Rather than moving the styleguide module into Backdrop core as it is, I saw our path forward working a little bit more like the Atomium styleguide: Each theme could have it's own styleguide page (maybe with, or near the theme settings page). Theme developers could use this page to make sure that any theme developed for contrib covers all components in the styleguide. People evaluating themes could use this styleguide to get a nice overview of how everything on their site would look in this theme.

**Comment by jlfranklin** [comment]
Such a thing is a development tool.  I don't think it belongs in core anymore than Devel does.

**Comment by jenlampton** [comment]
No, see my use-case #2 from above:

> People evaluating themes could use this styleguide to get a nice overview of how everything on their site would look in this theme.

**Comment by klonos** [comment]
> Such a thing is a development tool. I don't think it belongs in core anymore than Devel does.

I always wanted to have Devel in core 😛

...Jokes aside I tried to find an existing issue for it, but maybe instead of that, I just mentioned it somewhere (most likely on Gitter or during one of our dev meetings). I would love it if there was a `developer` profile shipped with core (or a "developer mode") that would get things set up for this group of people. Things like:

- enabling theme_debug
- disabling js/css aggregation
- enabling all errors (`/admin/config/development/logging`)
- installing and enabling devel and devel_generate

To that end, we already have issues like #99, #1561, #1591, and #3126. We also have previously mentioned that it would be great to allow community-contributed "recipes" (name TBD), which would be a way to allow people to install "collections" of things (modules, themes, layouts, preconfigured settings etc.)

**Comment by klonos** [comment]
>Rather than moving the styleguide module into Backdrop core as it is, I saw our path forward working a little bit more like the Atomium styleguide: Each theme could have it's own styleguide page (maybe with, or near the theme settings page).

Yeah, I would like to see this as a generic thing that could be used by all themes (something like how themes can enable support for color.module) + have it be an additional operation (besides "enable"/"disable"/"set default"), or a tab in the settings page of each theme.

**Comment by stpaultim** [comment]
I'm thinking about the guidelines for what goes into core. The main one that I can think of is the 80% rule. That for something to go into core it should meet 80% of the use cases. I think that means it meets the needs of 80% of the site admins. 

I know that I never/seldom add the style guide module, despite knowing that it exists. I think that if it were in core, I would use it on many if not most of my sites (that involve any kind of custom theming). I think that adding it to core would mean that I would use it much more often and that it would have a very positive effect on my "admin/developer" experience.

I don't feel strongly either way, about it being in core. But, I do think that I would prefer that it was in core (or something like it) and see that as a benefit. I can see arguments for not including it in core as well.

**Comment by klonos** [comment]
The Style Guide module was brought up as something we could use in the Ready2Wear initiative:

>Goal: Make it easy for non-coders/non-designers to create attractive Backdrop sites

I initially thought that the module was simple, and all it provided was a page with all possibly themable elements, but I just had a look at the 7.x version, and it seems to be a considerable amount of code 😞 : https://git.drupalcode.org/project/styleguide/-/tree/7.x-1.x

Perhaps we can find a way to promote the module instead of including it in core? (#3193)

**Comment by docwilmot** [comment]
What exactly would you be using the Style Guide Module for?

**Comment by klonos** [comment]
We'd want to allow people to see what the various elements in their site would look like, when showcasing/switching themes.

Internally, we'd want to use it as the means to see if themes qualify for the R2W initiative; all the various elements would need to look good in those themes.

**Comment by jenlampton** [comment]
We have a pretty solid plan for the styleguide module thanks to R2W, but
definitely in contrib. (Check the queue for the backdrop contrib version of
the module.)

One of the requirements for a promoted theme is that everything in the
styleguide module was supported (but we need to get those layouts and views
added).

I'm against putting it in core.

We need to he able to move faster than core for updates, and now that it is
a requirement for promoted themes, more people will be aware of it.

**Comment by klonos** [comment]
> I'm against putting it in core.

Yeah, let's close this issue here.
