### ISSUE TITLE
[UX] Project Installer: "Select versions" step: checkbox labels in the project releases list should not be rendered as links.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3246]
## Describe your issue or idea

As it is currently, when clicking the "change release" link, the labels of the project releases list are being rendered as links:

<img width="809" alt="screen shot 2018-08-08 at 3 40 00 am" src="https://user-images.githubusercontent.com/2423362/43792732-ff19abfe-9abc-11e8-92ae-d5823ea3b709.png">

The norm is for checkboxes/radios to be selected when one clicks on their label, but here clicking on the label opens a new browser tab. This leaves only the actual radio as click target, which is not good UX.

### Steps to reproduce (if reporting a bug)

1. Using the Project Browser/Installer, install a module (or theme, or layout) that has more than one release available.
2. When you reach the "Select versions" step, click on the "change release" link to expand the available releases list.

### Actual behavior (if reporting a bug)

Clicking a radio label opens a new browser tab, that opens the release/tag page on GitHub.

### Expected behavior (if reporting a bug)

Clicking a radio label should be selecting the respective radio option. There should be a separate link for the release notes on GitHub.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2273

**Comment by klonos** [comment]
From the PR sandbox:

<img width="814" alt="screen shot 2018-08-08 at 3 53 31 am" src="https://user-images.githubusercontent.com/2423362/43793572-4e21ce64-9abf-11e8-929e-f05edb44a5c0.png">

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/2273 looks great. Simple fix (as is your specialty). Merged into 1.x and 1.10.x. Thanks!
