### ISSUE TITLE
Warning when creating a new Term view

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3249]
## Describe your issue or idea

![screen shot 2018-08-09 at 2 25 55 pm](https://user-images.githubusercontent.com/871421/43921118-791ba47e-9be0-11e8-8723-8feb7ee3cafd.jpg)

### Steps to reproduce (if reporting a bug)

- `Add a View`
- Select `Taxonomy terms` and specify a type/vocabulary (e.g. `Tags`)
- Create a page or block, doesn't matter
- `Continue and Configure`

### Actual behavior (if reporting a bug)

The View has no filter to specify the vocabulary that was selected in the first step and we get a status message as follows: "This view has been automatically updated to fix missing relationships. While this View should continue to work, you should verify that the automatic updates are correct and save this view."

### Expected behavior (if reporting a bug)

There should be a filter to make sure it is pulling terms only from the chosen vocabulary and there should not be a "missing relationships" status.

---
PR by @laryn: https://github.com/backdrop/backdrop/pull/2508

**Comment by laryn** [comment]
I just realized that it doesn't actually work. There is no filter added to restrict the terms to the type that was selected.

**Comment by klonos** [comment]
Sorry, I have not used a term view specific to a certain vocabulary in some time, so not sure if the message is Backdrop-specific or comes with Views. Either way, once the view is created, I do not see any relationships configured. If there were none, then I see no point in the specific message being shown to the end user.

Also, I do not understand what I am supposed to do with "you should verify that the automatic updates are correct". Besides, I think that the "automatic updates" bit should change to "automatic configuration" given that we will at some point (soon?) will have #2018 and we need to avoid confusion between these things.

Finally, I also confirm that there is no filter criterion added to limit terms to the vocabulary that's being selected in the wizard.

**Comment by laryn** [comment]
I did this again with errors displayed and see a bit more information:


>  Notice: Undefined variable: table in ViewsUiBaseViewsWizard->default_display_filters_user() (line 706 of /path/core/modules/views_ui/wizards/views_ui_base_views_wizard.php).

>  Notice: Undefined index: machine_name in ViewsUiBaseViewsWizard->default_display_filters_user() (line 709 of /path/core/modules/views_ui/wizards/views_ui_base_views_wizard.php).

> Notice: Undefined variable: table in ViewsUiBaseViewsWizard->default_display_filters_user() (line 719 of /path/core/modules/views_ui/wizards/views_ui_base_views_wizard.php).
```

**Comment by laryn** [comment]
I'm not sure if it's the best way to go about it, but I figured out a way to make this work. Would appreciate a code review -- it seems there was some D7 cruft in there yet and there may be further related clean up that can happen.

https://github.com/backdrop/backdrop/pull/2508

**Comment by klonos** [comment]
Thanks @laryn 👍 ...I am not the best person to comment on the code (other than that it looks fine standards-wise), but I have tested the PR sandbox and confirm that things work as expected.

...plus we seem to have gotten rid of the message with the weird "automatic updates" mentions 👍 (#3542)

Point is that this seems to be working as expected from A UX point. Someone with better understanding of the internals of Views should review.

**Comment by herbdool** [comment]
@klonos feel free to mark it as RTBC. There's usually final code review before it gets merged anyway.

**Comment by klonos** [comment]
RTBC it is then!

**Comment by klonos** [comment]
This is a bug fix and it has a PR, so meets the criteria for the next bug fix release.

**Comment by quicksketch** [comment]
I think we can fix this a different way that doesn't special-case taxonomy. Left a comment on the PR: https://github.com/backdrop/backdrop/pull/2508/files#r263555524.

**Comment by laryn** [comment]
Thanks @quicksketch, I've updated based on your suggestion.

**Comment by klonos** [comment]
Thanks @laryn 👍 ...still works as expected, so RTBC again 😄

The php53 tests seem to have been stuck with `Installing Backdrop. This may take a moment... Connection interrupted.`. Can you please restart the tests @laryn ? ...alternatively, close the PR -> wait 1-2min -> reopen the PR. Thanks

**Comment by klonos** [comment]
...and tests are now green by the way :tada:

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2508 has been merged into 1.x and 1.12.x. Thanks @laryn, @klonos, and @herbdool!
