### ISSUE TITLE
[A11Y] Natively support the HTML5 #required property

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#325]
Drupal 8 decided to natively support the HTML5 #required property, but it has resulted in some accessibility regressions.  We should evaluate if this is a desired change for backdrop, and if so resolve the regressions.

See [Natively support the HTML5 #required FAPI property](https://www.drupal.org/node/1174938) and in particular [#1797438: HTML5 validation is not fully accessible](https://www.drupal.org/node/1797438)

**Comment by klonos** [comment]
Sorry I missed this @jenlampton but I've already started working on these things as part of #5346 #5348 (which are both preludes for #1040).

Closing this as duplicate then.
