### ISSUE TITLE
Link to Advanced Installation Instructions of Backdrop from Standard Install Documentation

### ISSUE THREAD

**Issue by mettamatt** [backdrop/backdrop-issues#3254]
Some developers might be searching for how to install Backdrop from the command-line. Consider linking to the [advanced installation](https://api.backdropcms.org/advanced-installation) instructions from the [standard installation](https://backdropcms.org/installation) overview page. Something like: _If you're looking to install Backdrop from the command line, see our advanced instructions._

**Comment by laryn** [comment]
Agreed! Would you mind posting this issue in the queue here and closing this one?

- https://github.com/backdrop-ops/backdropcms.org/issues/

**Comment by serundeputy** [comment]
Thanks @mettamatt and @laryn 

For future reference issues about backdropcms.org do belong in https://github.com/backdrop-ops/backdropcms.org/issues/

I've updated the standard [installation page](https://backdropcms.org/installation) with the recommended sentence and link to advanced install.

**Comment by mettamatt** [comment]
Thank you! And apologies for not filing this in the correct location. Now I know, and I appreciate your kindness. Cheers!

**Comment by laryn** [comment]
@mettamatt No worries, how were you to know?
