### ISSUE TITLE
Override of layout display renderer only works on new layout paths, not existing paths

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3256]
## Describe your issue or idea

As a follow-up to #2475, I found that overriding an existing path's layout does not have the ability to specify an alternative renderer, which only works on newly created paths.

### Steps to reproduce

There is no core implementation of this functionality. It can only be reproduced manually through manipulating the existing `LayoutRendererTest` test.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2284.

**Comment by quicksketch** [comment]
As @docwilmot made the original request over in #2475, getting his review here would be best. I'll reach out and see if he can take a look at this.

**Comment by herbdool** [comment]
@docwilmot approved on the PR so I'm updating the labels.

**Comment by quicksketch** [comment]
Excellent, merged https://github.com/backdrop/backdrop/pull/2284 into 1.x and 1.10.x.
