### ISSUE TITLE
Admin Bar include file loads itself

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3260]
I believe [this line](https://github.com/backdrop/backdrop/blob/af52d4223b77413a5e05c67a4bea9362c8cd84f5/core/modules/admin_bar/admin_bar.inc#L50) in `admin_bar.inc` is unnecessary as it seems to be trying to load itself...

`module_load_include('inc', 'admin_bar');`

Is that indeed the case? I'm sure `module_load_include()` has measures in place to avoid loops or whatever, but if it's not necessary then I recommend removing it.

-----

PR @jenlampton https://github.com/backdrop/backdrop/pull/2304

**Comment by jenlampton** [comment]
That may be left over from before this code was in this file. If you remove that line does it still work as expected?

**Comment by BWPanda** [comment]
When I commented it out and re-saved the admin menu and cleared caches, everything still worked as expected. Wasn't an extensive test though.

**Comment by serundeputy** [comment]
Good catch @BWPanda !
Thanks for the PR @jenlampton 

Merged into `1.x` and `1.10.x`.
