### ISSUE TITLE
How to disable CKEditor removing empty tags

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3269]
FontAwesome recommends displaying its icons using `<i class="fab fa-facebook"></i>` (an empty `i` tag). However [CKEditor removes empty tags](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html#property-S-removeEmpty).

One way around this is to enable source mode in CKEditor, add the empty `i` tag and then save the entity without turning off source mode (so CKEditor doesn't remove the tag). However I'm wanting to use this in a block and, because of https://github.com/backdrop/backdrop-issues/issues/1259, this workaround doen't work.

The proper [solution to allow empty tags](https://stackoverflow.com/a/21118988/4168619) in CKEditor is to add some code to a config.js file, however I'm not sure how to do that in Backdrop without hacking core... Is there another way I can do this, or can we add a UI option in core to specify allowed empty tags?

**Comment by quicksketch** [comment]
The config object for CKEditor is assembled in `ckeditor_get_settings()`. You can alter the config array through `hook_ckeditor_settings_alter()`.

However, in some of the examples present, they modify not only the `config` variable but also `CKEDITOR.dtd`. I think in order to modify that value, you'd have to load a CKEditor plugin which could execute that JavaScript.

Maybe take a look at existing CKEditor plugins for adding font awesome support, like https://ckeditor.com/cke4/addon/ckeditorfa?

**Comment by BWPanda** [comment]
Question has been answered, closing.

**Comment by klonos** [comment]
I would like to reopen this and make it a feature request. I would like us to add another filter (most likely in `filter_filter_info()`), which can be enabled/disabled, and where people can either allow all empty HTML tags, or specify which HTML tags may be left empty and/or specific CSS classes that allow their HTML elements to be empty.

**Comment by quicksketch** [comment]
@klonos Maybe this should be a separate contrib module, or part of https://github.com/backdrop-contrib/font_awesome itself? I don't think empty HTML tags have common usage (outside of Font Awesome).

**Comment by bugfolder** [comment]
> I don't think empty HTML tags have common usage (outside of Font Awesome).

Also [Bootstrap Icons](https://backdropcms.org/project/bootstrap_icons) and [Bootstrap Lite](https://backdropcms.org/project/bootstrap_lite), both for the same reason. (Bootstrap Lite has FontAwesome built in.)
