### ISSUE TITLE
[DX] hook_menu: default 'page callback' to 'backdrop_get_form'

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3273]
From the Gitter discussion between @rimu_twitter and @laryn ...

> ...Is there anything different about hook_menu, compared to D7, that I should be aware of?
I'm copying a working hook_menu chunk of code from an existing site but am getting the 'Access denied' screen when trying to visit the URIs that are defined in hook_menu
>> @rimu_twitter Hi there! I don't know the answer but maybe the API site will help? https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu/1
>>> Thanks @laryn . i just tried copy+paste of the very first example on that page
Same 'Access denied' problem
>>>> Did you clear caches?
>>>>> Yes
>>>>>> As anonymous user or user 1?
>>>>>>> user 1

...

> It looks like, unlike drupal, it is not acceptable to leave `'page callback'` empty. I needed to have `'page callback' => 'backdrop_get_form',`
> as well as `'page arguments' => array('custom_abc_view'),`
> in D7 you can leave `'page callback'` empty and it has the same effect as `'page callback' => 'drupal_get_form',`
> sigh I wonder what other gotchas await me on the backdrop journey

**Comment by klonos** [comment]
...this sounds like a BC bug that causes frustration when migrating custom code from D7. We should fx this as a DX/BC regression IMO.

**Comment by oadaeh** [comment]
I do not think this is a bug, although I have not tested it, nor actually read the code to be sure.
However, according to the documentation,

> "page callback": The function to call to display a web page when the user visits the path. If omitted, the parent menu item's callback will be used instead.

https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu/1

It is the same for D7.

It does NOT default to calling backdrop_get_form/drupal_get_form, unless that is the "page callback" for the parent menu item.

**Comment by serundeputy** [comment]
I agree with @oadaeh closing.
