### ISSUE TITLE
[DX] Provide backwards-compatible wrapper function for user_role_load_by_name()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3279]
As part of #177 we have removed `user_role_load_by_name()`, since [all roles are loaded by names now with CMI in Backdrop core](https://api.backdropcms.org/change-records/converted-user-roles-cmi), so `user_role_load()` should now be used in its place (which takes the role name as its argument instead of role ID). This makes it so that when `user_role_load_by_name()` is being used, there's a "Call to undefined function user_role_load_by_name()" fatal php error.

I believe that it would be best if we provided a BC wrapper function, that calls `user_role_load()` and then also logs a "deprecated" message in the system log.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2296

**Comment by opi** [comment]
`WATCHDOG_DEPRECATED` (as `WATCHDOG_DEBUG` too) are not logged by default. Update `watchdog_enabled_severity_levels` in `system.core.json` config file to as `8` severity level.

**Comment by klonos** [comment]
Thanks for the CR @opi ...and good call on adding the link to the API documentation 👍

...also thanks for the follow-up ticket and PR for providing a UI 👍. I've reviewed that and left a comment.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2296 into 1.x, as an API "addition" this isn't fixing a bug I don't think, and it _might_ require a change notice? I'm not sure. It seems strange that this function would have gone missing for 4 years only to come back later. I get that previously we didn't have the deprecation watchdog logging, or even the pattern of using `@deprecated`, so now we have better tools that lets us manage more deprecated functionality.

**Comment by BWPanda** [comment]
This CR mentions `user_role_load_by_name()`: https://docs.backdropcms.org/change-records/converted-user-roles-to-cmi Previously it said it was removed, I just changed it to say 'deprecated' instead.
