### ISSUE TITLE
Image dialogue won't open after I've updated the core to the latest 1.11.x-dev

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3284]
## Describe your issue or idea
Image dialogue won't open after I've updated the core on a test site to the latest 1.11.x-dev release and ran the update script which said it imported the new view for the image library. It just gets stuck at "loading" and provides some ajax errors.

![screenshot from 2018-09-09 23-45-38](https://user-images.githubusercontent.com/1071483/45275396-91d5e200-b48a-11e8-8675-a354622a8c4b.png)

The new view works fine when I look at it from the Views admin. Just nothing from CKEditor.

This was working fine before I updated the test site.

**Comment by herbdool** [comment]
Update: looks like it finally did open (when I tried it again a few hours later). But now the library just appears to the right of the form, no tabs.

![screenshot from 2018-09-10 14-48-44](https://user-images.githubusercontent.com/1071483/45317754-e6b83d80-b508-11e8-8fea-64aac3d8425e.png)

**Comment by docwilmot** [comment]
That is weird. Not a cache problem? Browser cache?

**Comment by herbdool** [comment]
Nope. I cleared both site and browser cache.

**Comment by olafgrabienski** [comment]
I've just tested the image browser in a sandbox site of a PR which has been made one day ago (status report says `1.11.x-dev`), and there it works fine. So maybe there is a problem with the update script?

**Comment by herbdool** [comment]
I tested again on a fresh install of 1.10.1 and then upgraded to 1.11.x-dev. The upgrade this time looks fine and it works fine. So I think it might be that there's just something wrong with my one particular test install, which isn't surprising since it's got a bunch of other modules on there I've tested. So I'm closing this.
