### ISSUE TITLE
Need ability to set color of primary tab so custom themes are not ugly

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3286]
## Describe your issue or idea

Because the primary tabs aren't a color option in Basis, it means that it's easy to make ugly looking color schemes. I'm going to be controversial and mark this as a bug (though even as a UI tweak might make it into 1.11.x?).

### Steps to reproduce (if reporting a bug)
Create some color schemes like "Tropical" in this PR https://github.com/backdrop/backdrop/pull/2299.

### Actual behavior (if reporting a bug)

![45274677-7a94f580-b486-11e8-9981-7e35f0dc2b67](https://user-images.githubusercontent.com/1071483/45403143-f7f76c00-b626-11e8-8a42-8b3888fd9b2b.png)

### Expected behavior (if reporting a bug)

Primary tabs should be a color option so that it can be controlled better.

Tested with 1.11.x-dev

**Comment by quicksketch** [comment]
PR was minimal and reviewed by @oadaeh. Merged https://github.com/backdrop/backdrop/pull/2303 into 1.x for 1.11.0. Thanks @herbdool!
