### ISSUE TITLE
Cannot redeclare node_path_bulk_update_batch_process - PHP Fatal Error

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3290]
## Describe your issue or idea

Hello Developers! 

After the upgrade to the last Backdrop version my blog is not available and under / user PHP Fatal Error 500.

In the error.log I find these Errors.

    [17-Sep-2018 11:51:15 Europe/Berlin] PHP Fatal error:  Cannot redeclare node_path_bulk_update_batch_process() (previously declared in /xxxxxxxxx/backdrop.cms-blogger.eu/core/modules/path/path.path.inc:73) in /xxxxxxxxx/backdrop.cms-blogger.eu/core/modules/node/node.path.inc on line 68                                           

Does it have anything to do with why I can not access my user profile?

The update under /core/update.php went very well without incidents. Just the blog start page and the profile are not available.

Maybe it is also due to the file .htaccess ?!

Thanks in advance.

### Relevant version/system information (if applicable)

PHP 7.1, MariaDB Engine, latest backdrop Version

[*Please do not use this issue queue to report security issues*. If you believe
you may have discovered a security issue with Backdrop CMS, contact the Backdrop
Security Team directly at security@backdropcms.org. In order to keep everyone
safe, we manage security issues separately in a private repository. So please
refrain from publicly blogging, or tweeting about it until the issue has been
resolved.]: #

**Comment by findlabnet** [comment]
Just remove or rename "core" directory and replace it with new one from distributive (new version haven't file "core/modules/path/path.path.inc").

**Comment by AlexL777** [comment]
Yes, Thanks for this Hints. My Problem is now solved 👍
