### ISSUE TITLE
Cache not (always) cleared with updates

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3294]
## Describe your issue or idea

In [the forum](https://forum.backdropcms.org/forum/problems-1110-release) this issue was reported:

> I was thinking I had cleared the cache yesterday after upgrading but perhaps I didn't. I know I ran updatedb.

I have also had problems with getting `backdrop_cache_clear_all()` to reliably clear caches when called from within an update function, and I wonder if there is some kind of race condition we are running into where the cache is cleared before the updates are complete?  Thought it was worth notting here.

### Steps to reproduce (if reporting a bug)

I don't have these yet, but will attempt to gather a list...

### Actual behavior (if reporting a bug)

Caches not cleared.

### Expected behavior (if reporting a bug)

Caches cleared.

**Comment by vstemen** [comment]
I thought it might be helpful for you to know, I ran some more tests and have been able to consistently reproduce the problem.

After upgrading from Backdrop 1.10.1 to 1.11.0, if I run **update.php** from the UI, the cache gets cleared and the color module preview works.  However, if I update the database via **"drush updatedb"** the cache does not get cleared and the preview does not show until I clear the cache.

**Comment by opi** [comment]
Current status

- `update.php`
    - clear cache when updates are finished: https://github.com/backdrop/backdrop/blob/1.x/core/includes/update.inc#L609-L611
    - clear cache if there are no updates: https://github.com/backdrop/backdrop/blob/1.x/core/update.php#L139-L140

- Drush
    - do not clear cache when there are no updates https://github.com/backdrop-contrib/drush/blob/1.x-0.x/includes/update.inc#L237
    - assume caches are already cleared when updates are finished https://github.com/backdrop-contrib/drush/blob/1.x-0.x/includes/update.inc#L312-L314
 
I guess this last item is wrong ; With a little debug, I see that `backdrop_flush_all_caches` is never called by `drush updb`; Any though @serundeputy 

Do we move this issue to the https://github.com/backdrop-contrib/drush/ repo ?

**Comment by jenlampton** [comment]
Yes, sounds good @opi

**Comment by opi** [comment]
Done https://github.com/backdrop-contrib/drush/issues/153
