### ISSUE TITLE
[UX] Sort the search CONTENT RANKING settings

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3296]
## Describe your issue or idea

On the search page, I really want my content ranking items to be listed in order of ranking.

Additionally, it would be great if I could drag and drop these into the correct order, instead of needing to use the select lists. 

<img width="1213" alt="screen shot 2018-09-20 at 5 09 29 pm" src="https://user-images.githubusercontent.com/397895/45853050-fb11ec80-bcf7-11e8-992f-9645d82b4bc5.png">

----
PR https://github.com/backdrop/backdrop/pull/2309 by @opi

**Comment by opi** [comment]
did it for contact categories, still fresh in my brain. I could give a shot for this

**Comment by opi** [comment]
hmm, after looking at the code, I realize that this "Influence" field is not a "Order" field.

- 0 means *disabled*
- having 3 item with influence 1,2,3 is not the same as 1,2,10 ; The factor (weight) is important, not only the order.

Not sure then that having a tabledrag is a good solution.

**Comment by jenlampton** [comment]
Ah...  yeah maybe not. Can we at least sort them in order in the table, then?

**Comment by opi** [comment]
it won't be dynamic, but it could be a UX improvement at least when viewing this form.

**Comment by opi** [comment]
PR https://github.com/backdrop/backdrop/pull/2309 with simple sorting. I let you decide the milestone.

**Comment by docwilmot** [comment]
@opi is a ranking of 9 less "influence" than a ranking of 1? If not then the larger number should sort to the top instead. Sort descending that is.

**Comment by jenlampton** [comment]
I am always confused about this, sorting here may also be a UX win as well
:)

**Comment by opi** [comment]
> @opi is a ranking of 9 less "influence" than a ranking of 1? If not then the larger number should sort to the top instead. Sort descending that is.

Damn right !

**Comment by opi** [comment]
PR updated with highest ranking on top.

**Comment by herbdool** [comment]
@opi PR looks good. However, maybe we can have some help text with the simple sorting to explain the ranking. I am also confused by the ranking: when using Search API I had thought it used the higher numbers as more influence and thought that was the same here.

**Comment by herbdool** [comment]
@opi I see. I was confused by some of the comments above then. Still, I didn't see help text on the search settings page to help explain that.

**Comment by klonos** [comment]
@herbdool we'll be adding the help text back in #2743 😉

This is just a single-line change, and it works as advertised. The only thing to note is that the sorting happens only during page load (after saving the form). Not sure if this is good or bad, but thought I'd mention it for consideration.

**Comment by quicksketch** [comment]
Thanks folks! #2743 needs a little work but this one looks good to go. I've merged https://github.com/backdrop/backdrop/pull/2309 into 1.x and 1.11.x. Thanks!
