### ISSUE TITLE
[CKEditor] Link to URL with trailing '/' gets converted to FID link

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3301]
## Describe your issue or idea

I'm writing a new blog post on my Backdrop site, and I added a link to an external website to some text. When saving the blog post, or even just viewing the source code from within CKEditor, the link doesn't show the external site but rather an image I uploaded to a previous blog post.

### Steps to reproduce (if reporting a bug)

1. Edit the 'Full HTML' format
1. Enabled CKEditor and 'image uploads'
1. Save
1. Create a new 'Post'
1. Add a title and set the Body's 'editor' to 'Full HTML'
1. Upload an image to the Body field using CKEditor's image upload button
1. Save
1. Create another new 'Post'
1. Add a title and set the Body's 'editor' to 'Full HTML'
1. Add some text to the Body field, highlight a word and click CKEditor's 'Link' button
1. Enter an external URL in the 'Link value' field (e.g. https://duckduckgo.com/)
1. Save
1. Either click CKEditor's 'Source' button or save the post and click the link

### Actual behavior (if reporting a bug)

The link points to the image you uploaded to the first post.

### Expected behavior (if reporting a bug)

The link points to the external URL you entered.

### Relevant version/system information (if applicable)

I'm using Backdrop v1.10.1.

Not sure if https://github.com/backdrop/backdrop-issues/issues/2476 is a similar/related issue...?

**Comment by Graham-72** [comment]
I have tried to reproduce this but am not seeing this problem.

**Comment by laryn** [comment]
I've had a report of something similar but assumed it was a copy/paste issue on the users part. I'll try to test this using your steps to reproduce today and report back.

**Comment by BWPanda** [comment]
@Graham-72 Hmm... Try again, and this time in step 6 upload this image: https://backdropcms.org/themes/borg/images/drop-lounging.png. Then for step 11 copy and paste the DuckDuckGo URL I provided above. That trigged the bug for me.

**Comment by Graham-72** [comment]
Yes, that triggered it for me too. But I have not been able to repeat this at the moment.

**Comment by Graham-72** [comment]
I would like to know whether this only happens when linking to an external image or whether it has anything to do with the link https://duckduckgo.com because it didn't happen when I used www.example.com.

**Comment by laryn** [comment]
I can reproduce as well. Bizarre!

**Comment by BWPanda** [comment]
Ok, I think I worked it out. If the URL you enter for a link ends with a '\', it'll link to the last image you uploaded. If it doesn't end with a '\', it'll link to the actual link you enter.

Presumably (I haven't checked the code), it's because it sees the trailing slash, then tries to do its autocomplete thing and so finds the first matching path begining with a '\'...

**Comment by BWPanda** [comment]
Found and fixed (see PR)!

**Comment by Graham-72** [comment]
Well pin-pointed! 👍

**Comment by laryn** [comment]
Nicely done, @BWPanda!

**Comment by quicksketch** [comment]
Thanks merged https://github.com/backdrop/backdrop/pull/2312 into 1.x and 1.11.x!
