### ISSUE TITLE
The new 'info' message type CSS affects the "Available update" display

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3305]
## Describe your issue or idea

The new 'info' message type CSS affects the "Available update" display:

![screen shot 2018-10-05 at 1 20 25 pm](https://user-images.githubusercontent.com/871421/46552831-929f3f80-c8a1-11e8-809f-9b0b5c3e93b0.jpg)

This doesn't look right.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2315

**Comment by opi** [comment]
I guess it's the `<div class="info">` from https://github.com/backdrop/backdrop/blob/c9ee437d06b1b9834c33229d3dd92ba9f8a14a14/core/modules/update/update.theme.inc#L275, which is really generic and could be replaced by a `project-info` class.

Also, maybe these CSS rules are also too generic https://github.com/backdrop/backdrop/blob/3d5074a261c5af713286614d1aa2048919e69b00/core/modules/system/css/messages.theme.css#L59-L105 , and should be `.messages.info, .messages.error` instead.

**Comment by opi** [comment]
Original .info type for messages issue https://github.com/backdrop/backdrop-issues/issues/3155

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/2315

**Comment by klonos** [comment]
From the PR sandbox:

![screen shot 2018-10-12 at 1 24 17 pm](https://user-images.githubusercontent.com/2423362/46844377-7744af00-ce22-11e8-9583-0eb380ef150c.png)

...so the issue in the Available Updates" page has been fixed, and various types of messages seem to still work/look as expected:

![screen shot 2018-10-12 at 1 21 28 pm](https://user-images.githubusercontent.com/2423362/46844376-7744af00-ce22-11e8-8134-9752660ae073.png)
![screen shot 2018-10-12 at 1 24 49 pm](https://user-images.githubusercontent.com/2423362/46844378-7744af00-ce22-11e8-9fc3-6838cf65e8d6.png)

**Comment by opi** [comment]
Thanks @klonos for the PR ; Reviewed, and changes requested.

**Comment by klonos** [comment]
Thanks @opi ...good catch re update.css, not sure re the divs. I have updated the PR.

**Comment by opi** [comment]
perfect!

**Comment by herbdool** [comment]
Thanks @klonos, @opi and @laryn. Merged https://github.com/backdrop/backdrop/pull/2315 into 1.x and 1.11.x.
