### ISSUE TITLE
[DX][Docs] Update the API documentation to include the new 'info' type for messages

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3311]
...this is a follow-up to #3155

As it is currently, [our documentation](https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/backdrop_set_message/1) only mentions the 3 other types:

> **`string $type`**: (optional) The message's type. Defaults to 'status'. These values are supported:
> 
> - 'status'
> - 'warning'
> - 'error'

---
~~PR by @klonos (informal tone): https://github.com/backdrop/backdrop/pull/2317~~
PR by @klonos (formal tone): https://github.com/backdrop/backdrop/pull/2575

**Comment by BWPanda** [comment]
I just came across the API docs for this and recalled seeing a fourth type in the issue queue, but still have old docs... Be good to get this updated ASAP.

As for the wording, I looked over the PR and I don't like the informal tone I'm afraid. I think I'd prefer to see the 'sophisticated' tone from the linked comment above.

**Comment by klonos** [comment]
I have created an alternative PR, which uses a formal tone: https://github.com/backdrop/backdrop/pull/2575

@jenlampton your words are better than mine 😅 ...care to have a look please?

PS: I hope that nobody minds my "authoritarian" setting of the milestone. The intention is for this to not be forgotten for yet another release.

**Comment by jenlampton** [comment]
I like the PR! One recommended change:

`This type is to be used when the message is not a warning nor an error.` should maybe be `This type is to be used when the message is not an error, a warning, or a success message.` Just so we get success in there too :)

**Comment by jenlampton** [comment]
> PS: I hope that nobody minds my "authoritarian" setting of the milestone.

I agree with the milestone of 1.12.6 :D

**Comment by klonos** [comment]
Thanks @jenlampton 👍 ...done.

I am assuming that we are going with the PR with the formal tone. Right?

**Comment by jenlampton** [comment]
I preferred that one :)

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2575 into 1.x and 1.12.x. Thanks folks!
