### ISSUE TITLE
[SEO] Bulgarian Transliteration Improvement - bg.php

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#3314]
Some time ago I sent you a bg. php file for transliteration into Bulgarian and you put it in core\includes\transliteration. In this old file, Latin transliteration is based on one of the some different methods used in Bulgaria for transliteration from Cyrillic to Latin.

Now I am sending a new bg. php file which is based on the rules for transliteration of Bulgarian, which are implemented by Google. This would help search engines to better understand Bulgarian keywords and text written in Latin in URLs and accordingly to better SEO of Bulgarian web pages.

I suggest that you replace the old file with the new one in core\includes\transliteration in the next version of the core.

[bg.zip](https://github.com/backdrop/backdrop-issues/files/2475546/bg.zip)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2321

**Comment by klonos** [comment]
Thanks for taking the time to respond @amilenkov ...there is a similar situation in Greek, where we have invented a method of input called [Greeklish](https://en.wikipedia.org/wiki/Greeklish). There are variations of this, depending on the preference of people to either to be phonetically correct (the argument being that phonetic is simpler + when non-natives read words they sound more accurate), or to be orthographically correct (the argument being similar to the reason behind [this joke](http://www.davidpbrown.co.uk/jokes/european-commission.html)).

I was hoping that there would be some publicly accessible, "Google-approved" list of transliteration lists, but it seems that this has been the product of empirical work 👍 ...oh well.

**Comment by jenlampton** [comment]
This looks like an easy win, adding milestone candidate for the next bug-fix release.

**Comment by amilenkov** [comment]
That's great, thank you!

Since publishing this issue on October 13, 2018, with every core update, I had to manually edit the core / includes / transliteration / bg.php file to get the desired transliteration. 

Since then I carefully observed the transliteration used by other Bulgarian sites and I am convinced that the proposed transliteration is the most common and acceptable for both site visitors and search engines.

I have developed and maintained more than 20 Backdrop CMS sites and since the beginning of this year I have only been working with this CMS.

**Comment by herbdool** [comment]
I've done a code review. Kind of hard to test but seems safe to include.

**Comment by quicksketch** [comment]
Looks like we have a failing test:

> fail първа статия is correctly transliterated to pyrva statija (actual: parva statiya) in bg langcode. transliteration.test:60

**Comment by quicksketch** [comment]
It looks like this issue was replaced by https://github.com/backdrop/backdrop-issues/issues/1604? Which states a similar purpose and was also vetted by @amilenkov. Please reopen if I've misunderstood. I've merged the associated PR from that issue. Thanks @amilenkov and @klonos!
