### ISSUE TITLE
[UX] "Add redirect" form has "URL redirects" as page title.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3315]
...discovered while working on #3304

`/admin/config/urls/redirect/edit` has "Edit redirect" as page title 👍 
`/admin/config/urls/redirect/add` has "URL redirects" as page title 👎 

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2323

**Comment by opi** [comment]
Tested, works as expected. 

Note that menu item title is not set because `/admin/config/urls/redirect/add``is a `MENU_LOCAL_ACTION`. Corresponding d.o. issue: https://www.drupal.org/project/drupal/issues/891892

**Comment by klonos** [comment]
Thanks @opi 👍 ...I have added a `@todo` comment in the PR, just above the `backdrop_set_title` to link to the d.org core issue and this ticket here. This for when (if) that issue is ever fixed upstream in the core menu.module.

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop/backdrop/pull/2323 into 1.x and 1.11.x.
