### ISSUE TITLE
[UX] Add human name to fields list at admin/reports/fields

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3316]
I often struggle finding the field I need on the fields list, because over time the machine name sometimes strays from the human readable label. I think we should add a column to the field list to include the human-readable label.

Here's an example of a site that's been upgraded from Drupal 6:
<img width="1048" alt="screen shot 2018-10-16 at 1 50 59 pm" src="https://user-images.githubusercontent.com/397895/47046699-9d33c180-d14a-11e8-98de-cf7233346a88.png">

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/2324~~
PR by @opi: backdrop/backdrop#2528 (based on klonos' 2324 with table sorting)

**Comment by klonos** [comment]
The same field can have different labels in different content types (bundles in general), so a single label per field instance is not applicable in all cases. I have filed a PR that does the following:

- Splits the "(module: xyz)" to a column of its own (better readability, and we could allow sorting in the future)
- Adds the `priority-low` class to the new "Module" column, so that it is hidden on tablet (leaving the class of the "Field type" column as `priority-medium` so that it is hidden only on mobile).
- Renders the items in the "Used in" column as a list.
- Appends "(field label: xyz)" at the end of the bundle name/link

Here's what it looks like:

![screen shot 2018-10-17 at 8 08 19 pm](https://user-images.githubusercontent.com/2423362/47075591-968b7400-d248-11e8-852d-f13bd355faf6.png)

**Comment by klonos** [comment]
...while working on this ticket, I have noticed the following:

- It is possible to enable sorting in the columns of a table rendered via `theme_table()`, **but only if the table is a product of db query**. I have filed a feature request to allow sorting for all tables: #3317

- The "Used in Views" tab only lists the `comment_body` field used in the "Recent comments" view. Filed a separate ticket for that: #3318

**Comment by olafgrabienski** [comment]
> When the same field is reused across multiple content types (bundles in general), it might have different labels. So a single label per field instance is not applicable in all cases.

Good point!

> - Appends "(field label: xyz)" at the end of the bundle name/link

I like the solution but I'm not sure if the prefix "field label" is necessary. I'd suggest to drop it or to write just "label". Let's compare:

`body | Text (long with summary) | Text | Layout Node (field label: Teaser)`

`body | Text (long with summary) | Text | Layout Node (label: Teaser)`

`body | Text (long with summary) | Text | Layout Node (Teaser)`

**Comment by klonos** [comment]
Thanks for the review @olafgrabienski 👍 

...yeah, I also initially thought to use just `label:`, but having that next to the content type label seemed confusing from a new Drupal/Backdrop user point of view (implies that the label is for the content type). No prefix at all is even worse if you ask me.

Having said that, I am OK to changing this to whatever works best, but lets wait for more feedback before changing anything.

**Comment by klonos** [comment]
...another idea is to have the entries in that column use a more "human" language. I have updated the PR:

- "Used in" column renamed to "Used as"
- entries use the format `[field name] in [bundle]` ("_Teaser_ in Layout node" for example)
- `[field name]` is rendered in italics and is now a link to the configure form of that field in the respective bundle.

Here's how it looks:

![screen shot 2018-10-18 at 5 48 48 am](https://user-images.githubusercontent.com/2423362/47109280-936ca400-d299-11e8-8506-49afa3b297fa.png)

Feel free to give it another spin @olafgrabienski 😉

**Comment by opi** [comment]
Nice ! I wonder about the use of italic, but looks good otherwise :+1:

**Comment by klonos** [comment]
I have given the table sorting another go, but cannot get it to work. I have pushed my code in the PR, which does render the column headers as (seemingly) sortable, but the actual sorting is not happening. Can I please get a second pair of eyes to figure out what I might be doing wrong?

I have looked in the documentation and comments available at https://api.drupal.org/api/drupal/includes%21theme.inc/function/theme_table/7.x and also related sources in the internetz, like https://drupal.stackexchange.com/questions/14889/can-tablesort-be-used-without-a-query but cannot figure out what I'm missing.

**Comment by jenlampton** [comment]
Doesn't table sorting use database sorting? If these aren't in the database anymore, tablesort won't work here.

**Comment by opi** [comment]
@klonos here's a PR with table sorting : https://github.com/backdrop/backdrop/pull/2528

**Comment by klonos** [comment]
Thanks @opi ...RTBC 👍

PS: I did leave a small comment re a tiny coding standard fix (missing period at the end of a comment), but that should not stop this from RTBC 😉

**Comment by opi** [comment]
PS: Commited in my browser, thanks to Github awesome UI !

**Comment by klonos** [comment]
> thanks to Github awesome UI !

Yeah, I really love that too @opi 😄 

This is truly RTBC now.

**Comment by klonos** [comment]
...if #3620 gets accepted, we should revise the PR here to use that 😉

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2528 into 1.x and 1.12.x. Thanks @klonos and @opi! I wasn't sure about the tablesort usage, it did seem a little out of ordinary but it worked well in practice in my testing.
