### ISSUE TITLE
CKEditor: Not possible to add content after inserted image.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3321]
@Graham-72 in https://github.com/backdrop/backdrop-issues/issues/3134#issuecomment-417910226:

>If I add an image at the foot of the edit window and right align it, it does not seem possible to add anything after it because CKEditor will not allow an insertion point after the image. This seems to be the case whether or not there is a caption. I wonder whether this is a more general CKEditor problem because I have experienced something like this in other circumstances.
>
>And the same problem exists if the image is left aligned.

@quicksketch:

> I've found this as well, but I don't think it's related to this PR.

**Comment by Graham-72** [comment]
@klonos is this the same issue as #3282 ?

**Comment by klonos** [comment]
@Graham-72 yes it is 😅 ...I discovered https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf yesterday. It has a feature that shows similar already-filed issues in the sidebar on GitHub. ...hope that they eventually implement it natively on github.com 🤞
