### ISSUE TITLE
Typing a "/" in a field label stops the machine name autocomplete

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3323]
### Steps to reproduce (if reporting a bug)

In an existing or new content type, start adding a field by typing in the field label -> While typing, the machine name of the field is autocompleted to the right 👍 ...

### Actual behavior (if reporting a bug)

...as you type in the label field, try typing a `/` and continue typing anything else after that -> anything that you type after the `/` is not added to the machine name autocomplete 👎 

### Expected behavior (if reporting a bug)

The `/` should be replaced with an underscore in the machine name autocomplete (same as other symbols). Autocomplete should continue past the `/`.

---
PR by @amoutiers: https://github.com/backdrop/backdrop/pull/2415

**Comment by klonos** [comment]
Thanks for the PR @amoutiers 👍 RTBC!

**Comment by quicksketch** [comment]
Thanks @amoutiers! Merged https://github.com/backdrop/backdrop/pull/2415 into 1.x and 1.11.x.
