### ISSUE TITLE
[DX] Use WATCHDOG_* constants instead of numerical values

### ISSUE THREAD

**Issue by opi** [backdrop/backdrop-issues#3325]
When reading through code, I often find it annoying to have numerical values instead of plain constants. 
Following PR will replace any occurence of watchdog related value with the proper constant string.

----
PR by @opi https://github.com/backdrop/backdrop/pull/2327

**Comment by klonos** [comment]
RTBC 👍

**Comment by quicksketch** [comment]
Simple change, merged into 1.x and 1.11.x. Thanks @opi!
