### ISSUE TITLE
[UX] Modules page: Modernize the error icon for incompatible modules

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3331]
## Describe your issue or idea

When a module is incompatible and cannot be installed, we render a red x icon instead of a checkbox, but that icons seems outdated.

### Steps to reproduce (if reporting a bug)

1. Install a version of a module that is not compatible with Backdrop core (at the time of writing, XML Sitemap 1.0.2 includes the `xmlsitemap_i18n` submodule which is not compatible).
2. Visit the modules page.

### Actual behavior (if reporting a bug)

We are currently using https://github.com/backdrop/backdrop/blob/1.x/core/misc/watchdog-error.png:

<img width="1177" alt="screen shot 2018-10-20 at 1 54 57 pm" src="https://user-images.githubusercontent.com/2423362/47250620-337c2600-d470-11e8-9ada-5d57b738143a.png">

### Expected behavior (if reporting a bug)

We could use https://github.com/backdrop/backdrop/blob/1.x/core/misc/icon-error.png and have it be the same red as the rest of the UI (`#EE3D23`):

<img width="1187" alt="screen shot 2018-10-20 at 1 58 29 pm" src="https://user-images.githubusercontent.com/2423362/47250630-7a6a1b80-d470-11e8-871c-522b90de1874.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2331

**Comment by klonos** [comment]
...oops 😅

**Comment by klonos** [comment]
Thanks @quicksketch 👍 ...PR updated.

**Comment by klonos** [comment]
@herbdool check the `xmlsitemap_i18n` module in the modules listing page in the PR sandbox 😉

**Comment by klonos** [comment]
@quicksketch I have addressed all your review comments, but the PR still shows up as "1 change requested" for some reason 🤷‍♂

**Comment by quicksketch** [comment]
Looks great! Confirmed it's still working locally. Merged https://github.com/backdrop/backdrop/pull/2331 into 1.x and 1.13.x.
