### ISSUE TITLE
Node preview: "page not found" when the content type name has spaces.

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3336]
Under certain circumstances the node preview feature (#3062) leads to a "Page not found" message.

### Steps to reproduce

- Create a content type with the name "My news", machine name: `my_news`.  
(Or use an existing content type with a name of two or more words.)
- Add a content item of that type. The path is `node/add/my-news`.
- Fill in a title and some content, and hit the "Preview" button at the bottom of the page. The path changes to `/node/preview/my_news/d666ebab(...)`.

### Actual behavior

There is no preview. Instead, I see a "Page not found" message with the following detail:
> The requested page "/node/preview/my_news/d666ebab(...)" could not be found. 

### Expected behavior

The preview should be displayed.

### Version/system information

Backdrop 1.11.2

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2335

**Comment by olafgrabienski** [comment]
I guess the problem is the use of an underscore in `node/preview/my_news/...`. When I replace it manually by a dash (`node/preview/my-news/...`) in the browser bar, the preview is displayed as expected.

**Comment by olafgrabienski** [comment]
Thanks for confirming, @klonos !

> if we should actually change the node/add/xyz path to use underscores instead of dashes

Why? I really like them! URLs with dashes are better readable, and they don't look so technical.

**Comment by herbdool** [comment]
I think it's an easy fix. In node_form_preview it's building the path using node type instead of replacing underscores with dashes.

**Comment by olafgrabienski** [comment]
@herbdool Thanks for the hint, I guess I've found it.

https://github.com/backdrop/backdrop/commit/9c219da36cef9e9680c2ab3ea8b8a8282edaa527#diff-7461e8a6902482c1fc141e24028ebfaaR461:

`$form_state['redirect'] = 'node/preview/' . $node->type . '/' . $node_tempstore_id;`

What would be the equivalent which replaces underscores for `$node->type`?

**Comment by herbdool** [comment]
It would be like in node_menu:

$type_url_str = str_replace('_', '-', $type->type);

**Comment by herbdool** [comment]
b) is not an option since it breaks backwards compatibility and probably affects multiple areas.

If you feel up for making a PR @klonos, cool. I think this should do it in `node_form_preview`:

`$form_state['redirect'] = 'node/preview/' . str_replace('_', '-', $node->type) . '/' . $node_tempstore_id;`

**Comment by olafgrabienski** [comment]
> are you up for filing a PR, or should I go ahead and do it?

@klonos I'm not really ready to file the PR at the moment, so yes, please!

**Comment by klonos** [comment]
^^false alarm. ZenCI tests just fired up and the sandbox was created. Seems that GitHub is still having issues and hooks are slow to respond.

Tested on the PR sandbox with a test content type that has space in its name, and there is not "page not found" on preview 👍

**Comment by klonos** [comment]
@herbdool while testing in the PR sandbox I discovered that the same problem would occur when switching view modes (via the dropdown in the lower-right corner). Updated the PR to account for that 😉

**Comment by klonos** [comment]
...same goes for the "Back to content editing" link. Re-updated the PR 😅

**Comment by docwilmot** [comment]
OOps thats a good catch. Agree with https://github.com/backdrop/backdrop-issues/issues/3336#issuecomment-431931959 @herbdool

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2335 into 1.x and 1.11.x. Thanks everyone!
