### ISSUE TITLE
[UX] "This is a preview. ..." message should be a warning and should be persistent.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3338]
I think that it is misleading the way that it is a success (`status`) message currently, because it resembles the message shown when a piece of content is actually being successfully saved:

<img width="1177" alt="screen shot 2018-10-23 at 9 49 15 am" src="https://user-images.githubusercontent.com/2423362/47323784-f51d7b80-d6a8-11e8-9c19-1739ddfa07b9.png">

I initially thought that it should be an `info` message (#3312), but then remembered that everywhere else in the admin UI when things have been stored temporarily, we through a warning (Views UI, reordering fields etc.).

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2336

**Comment by klonos** [comment]
...another issue with this message is that it goes away once you switch display mode (via the dropdown in the lower-right corner), or if you refresh the page.

**Comment by olafgrabienski** [comment]
I agree that a warning is more suitable. Providing however screenshots of the other *two* message types for a visual comparison.

**Warning:**

![screen-backdrop-preview-warning](https://user-images.githubusercontent.com/14188307/47350831-0ec5bf80-d6b7-11e8-8f94-2ff08177cab3.png)

**Info:**

![screen-backdrop-preview-info](https://user-images.githubusercontent.com/14188307/47350828-0e2d2900-d6b7-11e8-8570-a226c60ea137.png)

**Comment by klonos** [comment]
I have filed a PR which:

- moves the message from `node_form_preview()` to `node_preview_banner_form()`. This makes it persistent across page refreshes and switching display modes.
- splits the single message into 2:

> - This is a preview, and links within the page are disabled.
> - Changes are stored temporarily. Click _Save_ to make your changes permanent, or _Back to content editing_ to make additional changes.

Here's how it looks:

<img width="737" alt="screen shot 2018-10-24 at 5 27 49 am" src="https://user-images.githubusercontent.com/2423362/47382264-9c53ee80-d74d-11e8-8ac9-656de8873f2d.png">

PS: I wanted to also make the "Back to content editing" bit a link, but this would not work because all links within the preview are disabled. I tried to figure out how to exclude messages from the js that disables links within node previews, but my js-fu is not strong enough ...so I have settled with the excuse that it would be scope creep 😅

PPS: in the respective warning in the Views UI, we have an asterisk in front of the message to emphasize the fact that changes are temporary:

<img width="1199" alt="screen shot 2018-10-24 at 5 30 21 am" src="https://user-images.githubusercontent.com/2423362/47382419-02d90c80-d74e-11e8-801e-fa4a9f0df9bc.png">

...do you think that we should do the same here? ..or perhaps make that bit bold, like so?:

<img width="752" alt="screen shot 2018-10-24 at 5 29 54 am" src="https://user-images.githubusercontent.com/2423362/47382521-361b9b80-d74e-11e8-8e02-e5a8b4437bd6.png">

**Comment by klonos** [comment]
Following a couple of excellent suggestion made  by @herbdool in the PR, I have:

- split the first message to two sentences
- added the word "click" in the second message, before "back to content editing"

...I have also:

- fixed a problem with the messages show twice when changing displays
- made the "Changes are stored temporarily" bit bold.

Here's how it looks like now:

<img width="708" alt="screen shot 2018-12-29 at 1 01 43 pm" src="https://user-images.githubusercontent.com/2423362/50537570-f4520b80-0b69-11e9-846a-6a8fcd431ba2.png">

PR ready for another review.

**Comment by herbdool** [comment]
Looks good!

**Comment by quicksketch** [comment]
Thanks @klonos, @olafgrabienski, and @herbdool! Merged https://github.com/backdrop/backdrop/pull/2336 into 1.x and 1.11.x.
