### ISSUE TITLE
[UX] Show a message when viewing hidden/pageless content.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3339]
## Describe your issue or idea

This is a follow-up of #100 and #3275...

We should show a message that explains that this specific piece of content cannot be viewed on its own without proper permissions, and also link to:

- content type settings to change that behavior (if user has the "Administer content types")
- permissions page to grant/revoke the "View hidden paths" permission (if user has the "Administer permissions" permission)

---
OLD PR by @klonos: https://github.com/backdrop/backdrop/pull/2339

RECENT PR by @stpaultim (based upon PR by @klonos): https://github.com/backdrop/backdrop/pull/3900

**Comment by klonos** [comment]
PR up for review. Here's how it looks:

<img width="964" alt="screen shot 2018-10-26 at 3 51 03 am" src="https://user-images.githubusercontent.com/2423362/47516926-7572f500-d8d2-11e8-8d43-dd009e458cf7.png">

**Comment by klonos** [comment]
... I have updated the PR. It is still WIP, but I would love to get some feedback before moving on.

What I have done is to add the message in the "Display settings" tab in the content type add/edit form, and also instead of providing a link to the main permissions page, I have embedded the "View hidden paths" permission in the same tab:

<img width="1183" alt="screen shot 2018-10-26 at 12 40 49 pm" src="https://user-images.githubusercontent.com/2423362/47539493-72045b80-d91c-11e8-82d5-ef2b470344ad.png">

The message is rendered as `info` by default, but if the user does not have permission to edit user permissions, it is rendered as a `warning`:

![screen shot 2018-10-26 at 12 49 03 pm](https://user-images.githubusercontent.com/2423362/47539761-97de3000-d91d-11e8-91bc-cccd2d1534ac.png)

@todo:
- Saving the permissions does not actually work yet
- I would like to be able to hide the permissions matrix when the "Hide path display" checkbox is unchecked, but this does not currently work either (https://github.com/backdrop/backdrop-issues/issues/3332#issuecomment-433254903)
- Remove the "Configure which user roles can view content with hidden path" link from the message shown when viewing content with hidden paths (once the embeded permissions matrix in the form works).

**Comment by olafgrabienski** [comment]
I've had a look at the sandbox site. As expected, the message is shown to an admin user but not to an anonymous visitor (who gets a "Page not found" instead). Didn't test a user without "Administer permissions" so far, because it's planned to remove this part.

More generally, I agree that such a message can be helpful. Assuming that a site architect configured a  content type to have a hidden path on purpose, I'd suggest however to make the message

- less alarming (`info` instead of `warning` message), and
- less verbose (the linked setting displays the full explanation)

Current text suggestion:
> **This content is configured to have a hidden path**. It can be placed as a block or within a listing, but will not be accessible at its URL without proper permissions. This facilitates content that is meant to be embedded with other content, but never viewed on its own. Users who have the *View hidden paths* permission will still be able to visit the full page URL, while those without this permission will receive a "Page not found" error.

Less verbose:
> **This content is configured to have a hidden path.** It will not be accessible at its URL without proper permissions. Users who have the *View hidden paths* permission will still be able to visit the full page URL, while those without this permission will receive a "Page not found" error.

Even less (and "People" instead of "Users"):
> **This content is configured to have a hidden path.** People who have the *View hidden paths* permission will still be able to visit the full page URL, while those without will receive a "Page not found" error.

**Comment by klonos** [comment]
Thanks for reviewing @olafgrabienski 👍 ...great suggestions!

Re the type of the message, yeah, I contemplated about that myself. I though that perhaps the help text in the content type setting could be an `info`. Or perhaps have the smallest possible version of it as help text, and then have an `info` message that mentions an example use case (slide nodes that are part of a slideshow is a good candidate). You can see that I "played around" with that option in #3344. Anyways, the point is that I am not sure, and I do not have strong feelings about it either. Lets wait for some more feedback before I update the PR so that we limit the amount of back and forths.

I love your suggestions re less verbose text, and frankly I expected this to be the most common review feedback 😄 ...I used an almost verbatim version of the help text we have under the "Hide path display" checkbox in the content type config form:

![screen shot 2018-11-01 at 7 17 26 am](https://user-images.githubusercontent.com/2423362/47816083-39460580-dda6-11e8-88cd-38472a0844b9.png)

...perhaps we should consider shortening/improving that too as part of #3344. I personally like the "even less" version, and definitely yes to using "people" instead of "users".

PS: the two links for "Change this setting" and "Configure which user roles.." will be able to become a single one with #3344.

Thanks once again @olafgrabienski

**Comment by jenlampton** [comment]
I also prefer the least verbose option currently: 

> This content is configured to have a hidden path. People who have the View hidden paths permission will still be able to visit the full page URL, while those without will receive a "Page not found" error.

Though, I wonder if we can do even better... What about:

```
Only people who have access to `View hidden paths` are able to view this page. Everyone else will receive a "Page not found" error.
```

**Comment by klonos** [comment]
I have updated the PR to say:

> Only people with the _View hidden paths_ permission will be able to view this page. Everyone else will receive a "Page not found" error.

...if the user has the "administer content types" permission, then there is also a "Change this setting" link that takes them to the configuration page of that content type, and specifically to the "Display settings" vertical tab.

...if the user has the "administer permissions" permission, then there is also a "Configure which user roles can view content with hidden path" link, which takes them to the permissions page, and specifically scrolls to the "View hidden paths" permission.

PS: note that currently there is a bug where the sticky table header in the permissions page hides the permission scrolled to using URL fragments (`#`). I have filed a separate issue for that, and added a PR with a CSS-only solution: #3414

**Comment by jenlampton** [comment]
> I'm not sure though if the configuration links are helpful. 

I agree with @olafgrabienski, I think the message is sufficient without the additional links.

**Comment by stpaultim** [comment]
I'm going to cast a vote in favor of the proposed message. I don't feel strongly about the links either way.

**Comment by stpaultim** [comment]
The old PR was not working and needed a dramatic rebase, so I went ahead and created a new PR with the following changes (to see how they go over). 

1) Removed links
2) Changed status from Warning to Info

I moved the code changes to a new file, since the place where @klonos had put the code had been moved to this new file. Please, verify that this is all in the correct place. 

![image](https://user-images.githubusercontent.com/3144571/148486719-b5cf685d-2f10-42bd-a8f5-6412eb666e68.png)

**Comment by olafgrabienski** [comment]
Tested in the sandbox with roles admin (message + content visible) and Editor (no message, content not found). Works great!

**Comment by herbdool** [comment]
I suspect it's better to put it in https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_page_view/1 where the other hidden path logic is sitting.

It doesn't seem right to overload that view method with stuff like this. Plus currently it doesn't take into account the view_mode so it might be indiscriminate in where the message is displayed.

**Comment by olafgrabienski** [comment]
> won't it also show the message if the node is in a block?

Good catch! It *does* show the message in this case.

To test it, I've added a hidden path existing content block in the default layout of the PR's sandbox. On https://pr3900-nubh6zcqv7bytydb9auoc9gyqp8msxrc.tugboat.qa/about I see the message "Only people with the View hidden paths permission will be able to view this page (...)". Interestingly, the message on such a page is also shown for Editors and anonymous visitors.

**Comment by herbdool** [comment]
It shows for all roles because there's no access checking in the current PR.

**Comment by stpaultim** [comment]
Well, it's my PR right now. But, I just updated a prior PR and I'm not sure I'm able to fix these problems (certainly not prior to next release). If anyone wants to submit a new PR or create PR against mine, I'm good with that.

**Comment by stpaultim** [comment]
Thanks @jenlampton and @herbdool for hints on the old PR. I created a new PR based upon the latest branch and containing our new pageless nodes content type. 

Moving the code to the `function node_page_view(Node $node)` function seemed to take care of the access issues, without additional access conditions.

![image](https://user-images.githubusercontent.com/3144571/167979633-e503739a-5205-43fa-86fa-1a5de700b4a9.png)

Since we are adding a new pathless nodes content type, having this merged might help users understand what is going on with this new content type. It's a task, meaning it should be eligible for the 1.21.5 release.

**Comment by olafgrabienski** [comment]
@stpaultim I've tested the sandbox website with user 1, an editor and as guest. As far as I can tell, it works generally good. I've stumbled about of the message text, though:

> will be able to view this content on this specific page

The double "this" sounds a bit awkward. Also, while the phrase seems to be more accurate than just "this page" (as it was before IIRC), it is not correct. E.g., if you place an Existing content block with hidden content in the sidebar of the default layout, it's possible to have two hidden content items on the page: one of them is supposed to be hidden, but the other one in the sidebar not. In such a situation, as an editor, I might ask me which one is "this content". So, I'd suggest to just stick with "this page":

> will be able to view this page

**Comment by stpaultim** [comment]
@olafgrabienski - I see your concern with the wording. My concern with the original wording "Only people with the View hidden paths permission will be able to view this page" is that I think many people will associate `page` with `content` and UNDERSTAND it as "Only people with the View hidden paths permission will be able to view this content."

I'll see if I can come up with a better alternative.

**Comment by olafgrabienski** [comment]
Thanks @stpaultim . I see your point for changing the text and agree it's better to make improvements later. Labeled as `works for me` now, based on my yesterday's testing and under the assumption that only the wording was changed since then.

**Comment by herbdool** [comment]
I think it looks good.

I removed a commented out if statement and also the duplicate `$type =` statement. I'm marking it ready now.

**Comment by BWPanda** [comment]
Made a small suggestion to the code comment. If @stpaultim can fix it quickly, I won't bother changing the label to "needs work".

**Comment by herbdool** [comment]
I committed the suggestion. Pretty small change

**Comment by BWPanda** [comment]
Thanks to all involved in making/testing this PR: @stpaultim, @klonos, @olafgrabienski, @jenlampton & @herbdool. I've merged https://github.com/backdrop/backdrop/pull/4072 into 1.x and 1.21.x.
