### ISSUE TITLE
Set the default comment title setting to disabled

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#334]
In this day and age, titles for comments are uncommon.  Let's set this usual behavior as our default.

**Comment by quicksketch** [comment]
Let's try and get this in 1.1.0.

**Comment by quicksketch** [comment]
Last PR for this was at https://github.com/backdrop/backdrop/pull/484. It's close but had failing tests. I've closed the PR for now, since it'll need to be made against the 1.1.x branch anyway. We haven't created this branch yet, we're going to wait a week while we work out the bugs in 1.0.0.

**Comment by quicksketch** [comment]
It doesn't look like we'll have time for this in 1.1.0 (due next week). This isn't a particularly prioritized feature, even though I'd still love to see it as soon as possible. Moving into general 1.x queue until we get a volunteer here.

**Comment by docwilmot** [comment]
done.

**Comment by quicksketch** [comment]
Nice job @docwilmot! The PR looks great to me.

**Comment by quicksketch** [comment]
Merged into 1.x, so this will make it into 1.1.0 after all. Thanks!
