### ISSUE TITLE
[UX] Layouts: The default/only action for broken blocks should be "remove".

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3345]
### Steps to reproduce (if reporting a bug)

1. Enable the "Recent comments" view in `/admin/structure/views`.
2. Choose any layout and add the block provided by the "Recent comments" view to any region.
3. Save the layout.
4. Disable the "Recent comments" view.
5. Back to the layout "Manage blocks" page, the block added in step 2 above is now shown as broken...

### Actual behavior (if reporting a bug)

...click the "Configure" option on the broken block -> nothing happens (only a spinning wheel shown momentarily).

### Expected behavior (if reporting a bug)

There should not be a "Configure" option (leaving "Remove" as the only possible action).

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2340

**Comment by quicksketch** [comment]
I don't think we need the new method, we could just check the class name instead. See https://github.com/backdrop/backdrop/pull/2340#pullrequestreview-201828402.

**Comment by klonos** [comment]
PR updated to remove the method and rely on `!is_a()`.

**Comment by herbdool** [comment]
RTBC. A couple test failures but they look like glitches.

**Comment by klonos** [comment]
Thanks @herbdool 👍 

> A couple test failures but they look like glitches.

Yeah, this has been a major ongoing pain: #1478 ...the links to the tests were once again giving me "page not found" errors, so I have closed and re-opened the PR to restart them 🤞

**Comment by klonos** [comment]
...tests are green this time 😄 🎉

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/2340 into 1.x and 1.12.x. Thanks @klonos and @herbdool for the one-two punch here!
