### ISSUE TITLE
Remove concept of "disabled module"

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#335]
This obviously had a huuge discussion thread on https://drupal.org/node/1199946 so I can imagine it is not a simple thing. I certainly cant do it. But I think it was a positive change based on following the original issue.

**Comment by klonos** [comment]
> I'm not very keen on this. In Drupal 8 some people are trying to restore the ability to have disabled modules in https://www.drupal.org/node/2081873. ...

For historical reasons (in case we ever decide to revive this issue), there's now also a D8 contrib module available that restores this functionality: https://www.drupal.org/project/disable_modules
