### ISSUE TITLE
[UX] Add a time-picker (for the publishing scheduler and elsewhere)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3353]
This is a follow-up to #857...

Here's how things work currently:

![date-time-pick](https://user-images.githubusercontent.com/2423362/47822054-e759ab80-ddb6-11e8-9b5e-780e86380a10.gif)

I find the ability to use the keyboard within the time field really handy, but it is not ideal for mobile/touch devices. Perhaps we should consider adding a modern solution PIE.

**Comment by klonos** [comment]
This is what I was able to find around the net:

- http://jonthornton.github.io/jquery-timepicker

- ...

**Comment by klonos** [comment]
...I just realised that we are not using proper HTML5 date and time fields for these so don't know how much this is hurting our accessibility 😞 ...we could use something like this: http://afarkas.github.io/webshim/demos/index.html for IE and switch these fields to HTML5.

**Comment by indigoxela** [comment]
I think this issue has been fixed for FAPI in #3972

And there's already a follow-up for an additional field widget: #4255

Feel free to re-open if something's not yet addressed.

**Comment by klonos** [comment]
FTR, here's what the native time-picker currently looks like in latest MacOS Chrome:

![image](https://user-images.githubusercontent.com/2423362/99929606-7ea34a00-2d56-11eb-892c-a306df288383.png)
