### ISSUE TITLE
[UX] CKEditor 4: Consider adding the Auto Grow and Fixed plugins in core

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3354]
This was something that was requested in https://github.com/backdrop/backdrop-issues/issues/1087#issuecomment-172387989

https://ckeditor.com/cke4/addon/autogrow

> With this plugin, CKEditor will automatically expand and shrink vertically depending on the amount and size of content entered in its editing area.
> 
> The following configuration options are available:
> 
> - maximum and minimum editor height after adjustment to content,
> - extra space to be added between content and editor bottom bar,
> - having auto grow happen on editor startup

**Comment by klonos** [comment]
...I think that this makes sense especially after implementing #1034 where we have changed the default lines from 20 to 10. It is OK to have only 10 lines when creating new content, as this reduces the real estate taken in the form by the rich text editor (which is empty anyway), but when editing existing content with a lot of text, it would make it easy if we had more of the text area shown by default (still limited to a sensible default).

The plugin offers this feature:

> **Height Adjustment on Startup**
> 
> By default, the editor with the Auto Grow feature enabled will adjust its height once it gets into focus...

Demo of how this works: https://sdk.ckeditor.com/samples/autogrow.html

**Comment by laryn** [comment]
I like the plugin and currently use @opi's https://github.com/backdrop-contrib/ckeditor_autogrow

**Comment by klonos** [comment]
Interesting! I was not aware of the contrib module. Thanks @laryn for pointing me to it, and @opi for creating it 👍 ...it might serve me as an example to implement #3357 if I get the time/energy to do it.

Curious to see if people think autogrow is core-worthy or should be left for contrib.

**Comment by opi** [comment]
btw, autogrow plays well with the [fixed](https://ckeditor.com/cke4/addon/fixed) ckeditor plugin, which I implemented in backdrop too, but never pushed my custom module...

**Comment by klonos** [comment]
Do push it in contrib @opi 🙏 

...although FTR, I personally find that these 2 plugins fix some rather big UX issues and should be in core.

**Comment by opi** [comment]
here you go @klonos https://github.com/backdrop-contrib/ckeditor_fixed ; Not sure that it works flawless

**Comment by klonos** [comment]
Thank you @opi 👍 ...even if it doesn't, we'll fix it 😉

**Comment by quicksketch** [comment]
I'm going to close this issue because CKEditor 5 has the auto-grow behavior by default. Now we sort of have the opposite problem where limiting its height is hard, see https://github.com/ckeditor/ckeditor5/issues/636. But the goal of having auto-grow is now the default setting in CKEditor 5. No further work on CKEditor 4 is planned.
