### ISSUE TITLE
Keep CKEditor 4 and plugins up to date.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3355]
This is a sibling to #2493 

Keeping the editor up to date regularly should minimise troubleshooting issues introduced along the way (because we'll be "jumping" less versions up).

**List of things to test each time we update**:

- uploading an image via form field in modal
- uploading an image via drag & drop into rich-text area
- uploading an image via copy/paste into rich-text area
- align image + caption right and left with P alignment buttons
- link to existing content via link dialog
- link to file upload via link dialog
- more??

---
~PR by @klonos (4.7.3 to 4.11.1): https://github.com/backdrop/backdrop/pull/2361~ Merged into 1.12.0
~PR by @quicksketch (4.11.1 to 4.12.1) https://github.com/backdrop/backdrop/pull/2881~
~PR by @quicksketch (4.12.1 to 4.14.0) https://github.com/backdrop/backdrop/pull/3103~

**Comment by klonos** [comment]
...we are currently using version 4.7.3 (https://github.com/backdrop/backdrop/pull/2134), which was a security update.

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/2347

Note that the build has automatically added `core/misc/ckeditor/plugins/clipboard`.

**Comment by klonos** [comment]
New PR to update to 4.11.0: https://github.com/backdrop/backdrop/pull/2361

Notable changes since 4.10.1:
* [#2062](https://github.com/ckeditor/ckeditor-dev/pull/2062): Added the emoji dropdown that allows the user to choose the emoji from the toolbar and search for them using keywords.
* [#2154](https://github.com/ckeditor/ckeditor-dev/issues/2154): The [Link](https://ckeditor.com/cke4/addon/link) plugin now supports phone number links.
* [#1815](https://github.com/ckeditor/ckeditor-dev/issues/1815): The [Auto Link](https://ckeditor.com/cke4/addon/autolink) plugin supports typing link completion.
* [#651](https://github.com/ckeditor/ckeditor-dev/issues/651): Text pasted using the [Paste from Word](https://ckeditor.com/cke4/addon/pastefromword) plugin preserves indentation in paragraphs.
* [#1176](https://github.com/ckeditor/ckeditor-dev/pull/1176): The [Balloon Panel](https://ckeditor.com/cke4/addon/balloonpanel) can now be attached to a selection instead of an element.
* [#2202](https://github.com/ckeditor/ckeditor-dev/issues/2202): Added the `contextmenu_contentsCss` configuration option to allow adding custom CSS to the [Context Menu](https://ckeditor.com/cke4/addon/contextmenu).

**Comment by herbdool** [comment]
I tested image embedding, linking to existing content and file embedding in https://github.com/backdrop/backdrop/pull/2361. All works well for me.

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...ideally, I would like us to have a way to get this update out to people that wish to help with testing, and in fact get such changes (CKEditor, jQuery, jQuery UI etc.) out as early as possible to give them enough time to be beta-tested. I realise that people using git as part of their deployments can checkout the branch, but it would help to have a packaged dev version, or even RCs. A subject for the next meeting to be discussed I guess.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2361 into 1.x for 1.12.0. The 3 week lead time before the Jan 15 is less than we wanted, and that's my fault for dallying the merge of this PR. Please keep an eye out for any problems with the CKEditor update so we can correct them before the 1.12 release. Thanks @klonos and @herbdool!

I'm not sure if I should close this issue or keep it open to bump to the next version. Thoughts?

**Comment by quicksketch** [comment]
New PR at https://github.com/backdrop/backdrop/pull/2881 for CKEditor 4.12.1.

**Comment by jenlampton** [comment]
I'll give this a test.

**Comment by klonos** [comment]
RTBC 👍

**Comment by quicksketch** [comment]
Great, merged https://github.com/backdrop/backdrop/pull/2881. We're now up to 4.12.1. :smile:

**Comment by jenlampton** [comment]
My RTBC here is for this pr: https://github.com/backdrop/backdrop/pull/3103 which brings CKE up to 4.14.0

**Comment by quicksketch** [comment]
We're now on the current version, CKEditor 4.14.0.

**Comment by klonos** [comment]
Well, necessity causes things to get done 😅 ...after the [recent 1.19.1 security update](https://github.com/backdrop/backdrop/releases/tag/1.19.1), we're now in the most recent v4.16.1:

- https://github.com/backdrop/backdrop/pull/3636
- https://github.com/backdrop/backdrop/pull/3637

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/3684 updates us to 4.16.2.

**Comment by quicksketch** [comment]
We are no longer updating CKEditor 4 (as no new versions are being released). We're doing similar tracking for CKEditor 5 now, such as #6481 and #6695. We make one issue per minor release currently, since the discussions can get long when trying to update CKEditor 5.
