### ISSUE TITLE
CKEditor: consider the new Autocomplete plugin (introduced in 4.10) for addition to core.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3357]
https://ckeditor.com/cke4/addon/autocomplete

> This plugin provides contextual completion feature for custom text matches based on user input. Every time the user types a pre-configured matching character, such as "@" or "#", they get information about available autocomplete options. It includes the following features:
> 
> - Customization of the text matching function.
> - Asynchronous data feed.
> - Templating system for both the dropdown options and accepted output.
> - Throttling to reduce text check frequency.
> 
> ![image](https://user-images.githubusercontent.com/2423362/47831743-00c61c00-dde6-11e8-99ca-5521b558a280.png)
> 
> ![image](https://user-images.githubusercontent.com/2423362/47831750-09b6ed80-dde6-11e8-9029-d4f624753bc3.png)
> 
> ![image](https://user-images.githubusercontent.com/2423362/47831760-12a7bf00-dde6-11e8-8137-e20e24da3170.png)
> 
> ![image](https://user-images.githubusercontent.com/2423362/47831776-1f2c1780-dde6-11e8-8233-3390aae52b10.png)
> 
> This feature is a base for implementing specialized autocomplete features, such as mentions, emoji or custom implementations.

**Comment by klonos** [comment]
Mentions: https://ckeditor.com/cke4/addon/mentions

![image](https://user-images.githubusercontent.com/2423362/47831822-56022d80-dde6-11e8-8ca9-29f576b4c068.png)

![image](https://user-images.githubusercontent.com/2423362/47831831-5c90a500-dde6-11e8-9fde-950f2b063dbe.png)

![image](https://user-images.githubusercontent.com/2423362/47831834-61edef80-dde6-11e8-99a7-d7c178ae00bd.png)

![image](https://user-images.githubusercontent.com/2423362/47831839-687c6700-dde6-11e8-9800-5363a8e41687.png)

**Comment by klonos** [comment]
Emoji: https://ckeditor.com/cke4/addon/emoji

![image](https://user-images.githubusercontent.com/2423362/47831856-83e77200-dde6-11e8-8be3-5f23fa385659.png)

![image](https://user-images.githubusercontent.com/2423362/47831860-89dd5300-dde6-11e8-9f1a-dbe9a50ba755.png)

![image](https://user-images.githubusercontent.com/2423362/47831864-8e097080-dde6-11e8-807b-1b2b57fcdee8.png)

**Comment by quicksketch** [comment]
I'm going to close this issue out in favor of a new one specifically for CKEditor 5 emoji: https://github.com/backdrop/backdrop-issues/issues/6772

There is no generic auto-complete plugin in CKEditor 5, though there is a dedicated [mentions plugin](https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html). However I think that integration might be better as a contrib module.
