### ISSUE TITLE
"Administer comments and comment settings" should be split into two permissions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#336]
Administer comments - should provide access to the `admin/content/comment` page
Administer comment settings - should provide access to the comment settings vertical tab on nodes

**Comment by quicksketch** [comment]
This didn't get into 1.0.0. We could put this into 1.1.x I think, but it's a little dicey. Is this an API change or not? We need to come up with criteria for what's acceptable.

**Comment by jenlampton** [comment]
It's an API change for sire.  Guess we're stuck with comment-stupidness till 2.0 :)

**Comment by jenlampton** [comment]
whoops, didn't mean to close.

**Comment by BWPanda** [comment]
Would it be enough to simply provide an update hook thing (can't think of the proper name for `hook_update_N()` implementations) that sets the value of the new permission (`administer comment settings`) to the same value as the old one (`administer comments`)? Then we can still do this now but we're not breaking anything either...

**Comment by BWPanda** [comment]
Hmm, seems @quicksketch already suggested this: https://github.com/backdrop/backdrop/pull/478#issuecomment-57071426

**Comment by klonos** [comment]
> can't think of the proper name for

No, you're right 👍  ...these are called "update hooks".

**Comment by jenlampton** [comment]
> Is this an API change or not? We need to come up with criteria for what's acceptable.

I think as long as the change is backwards-compatible, it can go into 1.x. If adding an update hook makes sites behave exactly the same before this change as after, then it should be able to go into 1.x.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3370

**Comment by indigoxela** [comment]
Several related tests are currently failing, so back to "needs work".

**Comment by BWPanda** [comment]
Thanks, all fixed.

**Comment by BWPanda** [comment]
Is there not already a test for Backdrop that checks whether permissions work correctly? If not, maybe that'd prevent needing to write tests for each and every permission...

**Comment by jenlampton** [comment]
There are tests that permissions save, but there's no way to test them globally because every one does something different.

**Comment by BWPanda** [comment]
PR updated and test added.

**Comment by BWPanda** [comment]
Adding minor milestone candidate label in case this PR gets RTBC, and/or someone wants to advocate for it (I will if/once my other advocated issue gets merged).

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...I've reviewed the code, and it looks good to me 👍🏼 

I understand the value of this change, but worried that it may not be as backwards-compatible as we think/hope it is (sorta). I would be more comfortable if we had a way to make new permissions still work as before, similarly to how we use "wrapper functions" in https://github.com/backdrop/backdrop/blob/1.x/core/includes/drupal.inc, but then again, we are not renaming a permission here - we are repurposing it (splitting some of its functionality into a new permission). 

This PR is "upgrading" permissions on existing sites, so functionality won't be lost per se, since any user role that previously had the `administer comments` permission will now have that same permission + `administer comment settings`. That's great 👍🏼 

If a contrib or custom module was previously relying on the `administer comments` permission to do things that now require `administer comment settings`, then things might not work as expected. It also depends on the logic that the module has in place around that permission 🤔

**Comment by stpaultim** [comment]
I was checking this issue because it's marked good first issue. It seems that the work is done and we just need to decide if we consider this backward compatible. I put this on the agenda for meeting tomorrow, maybe we can wrap this up. 

I will remove the good first issue tag, since I don't think there is anything for a new contributor to do right now.

**Comment by jenlampton** [comment]
> This PR is "upgrading" permissions on existing sites, so functionality won't be lost per se, since any user role that previously had the administer comments permission will now have that same permission + administer comment settings. That's great 👍🏼

> If a contrib or custom module was previously relying on the administer comments permission to do things that now require administer comment settings, then things might not work as expected. It also depends on the logic that the module has in place around that permission 🤔

@klonos I'm not sure the use-case you brought up here is a valid one. The only way this could be a problem is if you have people who have permission to administer settings, without administering comments themselves. Not only is this likely to be a very rare scenario, but because the settings-only permission did not exist before this change, the liklihood of that affecting existing sites is zero. (so, this is not a BC issue at all)

For new sites, it is possible that someone could add this settings-only permission and get themselves into a pickle, but it's perhaps more likely that the contrib project would update the permission it requires before then.

What's done in this PR is the way we've handled all permission updates in the past. If we want to add a backwards-compatible permission system to 2.x -- and I think that's a reasonable discussion to have! -- but let's not block this useful feature by doing it here :) Can you please open a new issue? (If you haven't already)

**Comment by jenlampton** [comment]
> I will remove the good first issue tag, since I don't think there is anything for a new contributor to do right now.

@stpaultim  this issue both needs code review and testing. And since the code change is minimal, those are both realistic for first time contributors. I'm going to add the label back since we have a shortage of people helping to test issues.

**Comment by quicksketch** [comment]
This looks good to me. We now have precedent for adding/splitting permissions and have done the same thing in a few other places, such as:

* https://github.com/backdrop/backdrop-issues/issues/313
* https://github.com/backdrop/backdrop-issues/issues/382

There was a fair amount of permissions additions added throughout File module's history too.

**Comment by quicksketch** [comment]
One more comment @BWPanda if you could take a look: https://github.com/backdrop/backdrop/pull/3370/files#r825147313

**Comment by BWPanda** [comment]
Done.

**Comment by stpaultim** [comment]
I tested the Pull Request and it seems to work as expected. 

I created a TEST account and gave them editor role. 

When I gave them Administer comments permission they were able to access to the admin/content/comment page.
When I gave them Administer comments settings permission they were able to access to the comment settings vertical tab on nodes.

It all seems to work as expected. 

(I did this as part of an OpenForce2022 demo)

**Comment by quicksketch** [comment]
Thanks folks! I have merged https://github.com/backdrop/backdrop/pull/3370 into 1.x for 1.22.0! I don't think this qualifies as either a bug or UX improvement, so I have not pulled it back into 1.21.x. Huge thanks for knocking out this very old issue!
