### ISSUE TITLE
[UX] Show CKEditor in the site status report page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3360]
![screen shot 2018-11-01 at 11 29 12 pm](https://user-images.githubusercontent.com/2423362/47851931-38f14d00-de2e-11e8-929e-95a580e51f04.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2348

**Comment by klonos** [comment]
...OK, PR up for review:

- adds a new "CKEditor" entry as `REQUIREMENT_INFO`
- changes the jQuery entry from `REQUIREMENT_OK` to a `REQUIREMENT_INFO` (to make it bubble up with the entries for PHP/MySQL/Web server)
- removes the extraneous "version" string from various entries for simplification.

**Comment by findlabnet** [comment]
We should check, if module "CKEditor" enabled before reporting.

**Comment by klonos** [comment]
You are absolutely right @findlabnet 👍 ...I was under the impression that ckeditor.module was a system module, hence required and always on by default. This explains those `Use of undefined constant CKEDITOR_VERSION` exceptions in the tests too 😅 

PR updated.

**Comment by jenlampton** [comment]
This doesn't look like a feature request, just a UX issue. Adjusting tags and milestones.

**Comment by jenlampton** [comment]
This issue still needs more feedback, removing milestone, but adding milestone candidate tag.

**Comment by jenlampton** [comment]
Okay, reading this over again, I agree with the milestone candidate tag :) Adding milestone.

**Comment by klonos** [comment]
...I have split the jQuery changes off to a separate issue: #3879. Hoping to make it easier to review and approve this change here.

**Comment by jenlampton** [comment]
There still seem to be some unrelated changes in the PR: changes to how the PHP version info links are generated. Marking as NW.

**Comment by docwilmot** [comment]
Was going to push a new PR to address @jenlampton comments, but I actually agree with @klonos changes here. Brings consistency. We have:
```
Backdrop CMS | 1.16.x-dev              <-----NO  "version" string
PHP | Version: 5.6.31 (PHP information)             <----- "version" string
Web server | Apache/2.4.27 (Win64) PHP/5.6.31              <----- NO "version" string
jQuery | jQuery version 1.12.4 / jQuery UI version 1.12.1              <----- "version" string
```
Not a major issue, but I think its worth keeping and not worth a separate PR. RTBC.

**Comment by quicksketch** [comment]
I know we have a lot of similar reports in System module, so it's easy to copy/paste there. But because CKEditor is exposed by ckeditor.module, this should go in a new `ckeditor_requirements()` function, not in `system_requirements()`.

**Comment by docwilmot** [comment]
This is true. So once @jenlampton agrees to leave the "Version" changes in there, will redo properly. Thanks.

**Comment by klonos** [comment]
With #3879 merged, I've updated the PR. @quicksketch you are absolutely right, but there's no need for a new function, as there is an existing `ckeditor_requirements()` function in `ckeditor.install`. With it's current implementation, that function only shows this message if no text formats have been configured to use CKEditor:

![Screen Shot 2020-06-11 at 8 37 46 pm](https://user-images.githubusercontent.com/2423362/84420966-87c6b180-ac23-11ea-95fe-d978bd4a7f15.png)

Now, the version is shown at the top of the message:

![Screen Shot 2020-06-11 at 8 52 37 pm](https://user-images.githubusercontent.com/2423362/84422313-839b9380-ac25-11ea-99a3-ea5ba7e93bd3.png)

I've swapped the part that started with "Visit..." as that in combination with the fact that this is shown as a warning made the sentence sound "commanding". Starting with "To configure..." makes it sound informational/optional.

If the person viewing the status report does not have permission to edit formats, this is shown instead:

![Screen Shot 2020-06-11 at 9 00 45 pm](https://user-images.githubusercontent.com/2423362/84423178-c14cec00-ac26-11ea-9c9d-8ad1e7f2891a.png)

Previously, if at least one text format was configured to use CKEditor, this entire row was hidden. Now with the version shown, there's a "more" link which when clicked shows this:

![Screen Shot 2020-06-11 at 9 03 32 pm](https://user-images.githubusercontent.com/2423362/84423446-243e8300-ac27-11ea-9a62-e514a589e6d7.png)

...or this:

![Screen Shot 2020-06-11 at 9 04 01 pm](https://user-images.githubusercontent.com/2423362/84423496-36b8bc80-ac27-11ea-9bd5-eaa067f6762a.png)

(depending on whether the person viewing the report has permission to edit formats or not)

**Comment by indigoxela** [comment]
The sandbox seems broken, it only leads to the installer. @klonos can you request a fresh one, please?

**Comment by klonos** [comment]
Done @indigoxela 👍

**Comment by stpaultim** [comment]
I tested it with a new text format. Seems to be working for me.

![Screen Shot 2020-08-30 at 12 46 13 PM](https://user-images.githubusercontent.com/3144571/91665942-cd767600-eabe-11ea-91cb-d26a5729ef1c.png)

**Comment by indigoxela** [comment]
I like the display of CKEditor version on status page (although it ships with core anyway).

But there's on thing I don't get: why is it worth a warning if none of the text formats uses the editor? There's nothing broken or in danger then. Unlike other warnings like "Trusted host settings", which in contrast to editor usage really has security implications.

@klonos could you explain the idea behind that? Why warn if some functionality isn't used?

![no-editor-in-formats](https://user-images.githubusercontent.com/842066/91689914-5516c000-eb65-11ea-92e6-9ab1ccbc4c73.png)

**Comment by klonos** [comment]
> (although it ships with core anyway)

The same can be said for jQuery; we still show it in the status report.

>@klonos could you explain the idea behind that?

I guess to avoid WFTs when site builders new to Drupal/Backdrop enable the CKEditor module, but they don't see the toolbar show above their text areas. I'm not married to this though; it can be changed to be `REQUIREMENT_INFO` instead.

**Comment by indigoxela** [comment]
>  I'm not married to this though; it can be changed to be REQUIREMENT_INFO instead.

Personally, I'd prefer "info" then. Let's not worry admins, when nothing dangerous happens anyway.

**Comment by klonos** [comment]
Done 👍

**Comment by indigoxela** [comment]
To be honest, I don't understand the status page mapping for info and ok anyway... :wink: 

The PR works as advertised and the listing of ckeditor-enabled formats is nice to have, too. Works for me.

**Comment by BWPanda** [comment]
> (depending on whether the person viewing the report has permission to edit formats or not)

I don't like this (I left a message in the PR about this too). I don't know of anywhere else in core where we list the different roles that have access to something in order for the current user (who doesn't have access) to contact them. In fact in another issue we specifically removed all "contact your site administrator" messages...

**Comment by stpaultim** [comment]
> I don't like this (I left a message in the PR about this too). I don't know of anywhere else in core where we list the different roles that have access to something in order for the current user (who doesn't have access) to contact them. In fact in another issue we specifically removed all "contact your site administrator" messages...

So, I understand and appreciate the goal to provide contextual help to point a user in the right direction to solving their problem. But, I share the concern from @BWPanda about handling this in a piecemeal fashion. Are we doing this for any other setting? Are there are status report pages items where it makes sense to do this. If so, why are we not making this decision for all of them. 

My concern is that we add this here without any consensus that this is a good idea and we end up with an inconsistent and only partially implemented idea. Then the next time we are making a change to the status page, we have to have this dicussion again and/or possibily revert changes that we've already made. 

If we are going to provide helpful information about which roles can update something, let's make that decision in general and not on such a specific case by case basis. 

Maybe we have already had this discussion elsewhere and there is a precedent for it. If so, let's mention that. 

Should this be a separate issue?

**Comment by BWPanda** [comment]
> Should this be a separate issue?

Definitely.

**Comment by klonos** [comment]
> I don't like this ... In fact in another issue we specifically removed all "contact your site administrator" messages...

Agreed. I'll remove that bit of logic from the status report.

**Comment by stpaultim** [comment]
So, my team is working on porting a Drupal 7 module to Backdrop CMS. 
https://www.drupal.org/project/ckeditor_blocks

The Drupal install instructions say the site must be upgraded to Ckeditor 4.3, so I went to check which version of CKEditor that we are using in core and could not find this information anywhere. Was a little surprised it was not on the status page, because it was there in Drupal 7. 

I see from screenshots of this PR, that we must still be on CKEditor 4.14, so it appears I have a different problem.

**Comment by jenlampton** [comment]
> The Drupal install instructions say the site must be upgraded to Ckeditor 4.3

We're on the latest, version 4.17.1: https://github.com/backdrop/backdrop/blob/1.x/core/misc/ckeditor/CHANGES.md

> so it appears I have a different problem.

You might be thinking 17 is less than 3 because it starts with a 1? That catches me sometimes too. I don't think you have a problem :)

**Comment by stpaultim** [comment]
@Jen Lampton ***@***.***> - Yes, I feel very silly now. And, I
just posted something in the forum asking about this same question. Now, I
look silly in two places, not to mention our internal JIRA issue queue.

:-)

**Comment by jen** [comment]
Hi all! I’m @jen but not your jen.

**Comment by klonos** [comment]
PR rebased and tests are green. It seems that we missed updating `CKEDITOR_VERSION` in #5358, so I've updated that as well. See #5476 for a follow up to automate that in the future.

**Comment by klonos** [comment]
...screenshots:

![image](https://user-images.githubusercontent.com/2423362/151547900-6909cdab-3fbe-4d68-80c4-033c9e28cd6c.png)

![image](https://user-images.githubusercontent.com/2423362/151547800-d17df832-2324-478d-bca1-be9f64d3bdd3.png)

**Comment by klonos** [comment]
> It seems that we missed updating `CKEDITOR_VERSION` ...

If #5476 is approved and gets merged before this, we should update the PR here to use `ckeditor_get_version()` instead of the hard-coded `CKEDITOR_VERSION` constant.

**Comment by BWPanda** [comment]
If there's no objections in that other issue and its likely to get in, we should probably do that here anyway.

**Comment by klonos** [comment]
Yup, I'm fine with that too 👍🏼 ...just don't want to delay this one getting in on account of discussions/concerns on the other; that's all.

**Comment by jromine** [comment]
Echoing @stpaultim's comment that just now _I went to check which version of CKEditor that we are using in core_ and had to dig through the ckeditor.module file to find it, and would very much like to see this merged.

**Comment by stpaultim** [comment]
Just reread this issue and I think the issues raised have all been addressed and the PR seems to work for me.

**Comment by BWPanda** [comment]
I've requested some changes in the PR.

**Comment by jenlampton** [comment]
I've reviewed the previous PR as well as one I created today, and I went with the newer one. The older one changed a lot of things not related to the task and those changes were what caused most of the change requests on the PR. 

One major difference between the newer one and the older, was that the older one depended on the constant `CKEDITOR_VERSION` but the newer one uses the hard-coded string for the version. This means that when the version number changes, we'll need to remember to change it in two places.

I'm not sure if the constant `CKEDITOR_VERSION` is available when `hook_requiremeents()` is running, since it's defined in the `.module` file.  `.module` files are not available when updates are running, and since this file contains the updates, it seems like that could be problematic.

**Comment by quicksketch** [comment]
I left some suggestions on the PR.

**Comment by jenlampton** [comment]
Suggestions merged.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4509 into 1.x and 1.25.x (just in case that gets any installs) to start including CKEditor version in the status report. Thanks everyone for their feedback, review, and code!

https://github.com/backdrop/backdrop/commit/d657bfa5581563153ddb86fc314755c55e6b4cac by @jenlampton, @klonos, @kiamlaluno, @quicksketch, @docwilmot, @BWPanda, @stpaultim, and @jromine.
