### ISSUE TITLE
Make Node Preview Optional (and correct "Access denied" without permission "Create new content")

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3361]
On my site there is a role for editorial assistants, and when I click the *Preview* button as a person with this role, I get an "Access denied" page.

### Steps to reproduce

Set up a role with restricted node permissions for an editorial assistant, mainly "TYPE: Edit any content" and "View any unpublished content", but not "TYPE: Create new content".

### Actual behavior
When the person hits the "Preview" button in the node form, she doesn't see the preview but an "Access denied" message.

### Expected behavior
The preview should be displayed.

---

PR by @docwilmot: https://github.com/backdrop/backdrop/pull/2445

**Comment by olafgrabienski** [comment]
It turned out that the role needs the "TYPE: Create new content" permission to see the Preview. That doesn't make sense because the Preview button is also available when I edit content.

**Comment by docwilmot** [comment]
Working on this

**Comment by docwilmot** [comment]
The fix for this was quick: changed the `access callback` on `node_menu()` to TRUE; this means anyone can access the preview page. But there are only two ways to get to that page: either know the preview UUID, which should be near impossible to guess, or click the 'Preview' button, in which case you need to already have had `create` or `edit` permissions. Is this sufficiently robust? We could have an access callback on the preview which says `if (node_access('create') || (node_access('edit')` instead.

While there, though, I took the opportunity to add per-node-type controls for preview, so you can turn off previews for an entire node type, as in D7.

**Comment by herbdool** [comment]
@docwilmot While the UUID is practically impossible to guess, it is trivial to put it into, say, an email and have shared around unintentionally. Maybe a rare case but still a potential security issue when people assume the content is private. I like `(node_access('create') || (node_access('edit')` better. 

I think `'access callback' => (node_access('create') || (node_access('edit'),` would be good enough?

You've got some extraneous commits in the PR.

**Comment by docwilmot** [comment]
@herbdool only two commits as far as I can see, both part of the same code. Would need squashing, but not extraneous.

And I agree with the access rules, make sense, should have just done just that. But will have to wait till tomorrow, unless someone else can take over.

**Comment by herbdool** [comment]
@docwilmot there already seems to be a `node_access_preview(Node $node)` function but it's not being used in node_menu. Maybe you forgot? It looks like exactly what you need and just add to node_menu.

**Comment by herbdool** [comment]
Duh, it's late here so I'm not thinking clearly. So we have `node_access_preview` but we don't necessarily have a $node object nor ID so we can't use it (which uses node_access()) to check access. And we can't just make it true. I'll stop there for now.

**Comment by herbdool** [comment]
Or maybe not. I thought locked was part of tempstore but no.

**Comment by herbdool** [comment]
How about just checking if the user has access to edit the content type rather than the specific node/node-to-be? Not perfect but better than fully open access.

**Comment by docwilmot** [comment]
@herbdool excuse the delay responding. At my day job so cant code now sadly.
`node_acccess()` takes either a node object or a node type for the `$node` parameter so the code in that `node_access_preview()` would be perfect. That function must have snuck in there unused in the initial commit. But we can use it now!! So:
```
      'access callback' => 'node_access_preview',
      'access arguments' => array($type->type),
```
and

```
/**
 * Access callback: Checks a user's permission for previewing a node.
 *
 * @param $type
 *   The node type being created or updated.
 *
 * @return bool
 *   TRUE if the user has access to the preview, FALSE otherwise.
 *
 * @see node_menu()
 *
 * @since 1.11.0
 */
function node_access_preview($type) {
  if (node_access('create', $type) || node_access('update', $type)) {
    return TRUE;
  }
  return FALSE;
}
```

**Comment by herbdool** [comment]
@docwilmot no prob. I just post whenever I have a moment, but don't expect an immediate response.

Is it possible that node_access will only check the node type if it's the "create" operation? Which would mean for the "update" operation it needs the full node object? From the docblock:

> The node entity on which the operation is to be performed, or the node type (e.g., 'post') for the 'create' operation.

**Comment by docwilmot** [comment]
@herbdool 
> Is it possible that node_access will only check the node type if it's the "create" operation?

I think its both operations; `node_node_access()` is called by that function and it checks access for both.
But we really should extend the tests to actually check that.

**Comment by herbdool** [comment]
Ah, I didn't think to look at the hook.

**Comment by herbdool** [comment]
Tested and looks good.

While this is a bug fix it also has a new checkbox to be able to disable the preview per content type. I'd say it's minor enough to be added in a patch release.

**Comment by klonos** [comment]
Sorry for coming late to the party, I think we should be using `1` and `0` instead of `'1'` and `'0'` for on/off true/false values in config files. Small follow PR to this: https://github.com/backdrop/backdrop-issues/issues/3361

@quicksketch ^^
