### ISSUE TITLE
BackdropCMS v. 1.11.1 is changing underscores in classes to hyphens

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#3365]
## Describe your issue or idea

The update to Backdrop v. 1.11.1 includes some work to "Clean up CSS classes for blocks and regions." I believe that change is breaking some classes that I inserted on blocks and regions through the UI. It is converting classes with underscores into classes with hyphens. 

A little research suggests that I should probably not be using underscores in my classes, but I've not found anything that would explain why Backdrop would be making this change intentionally.

### Steps to reproduce (if reporting a bug)

On a fresh installation of BackdropCMS
1) Go to: admin/structure/layouts/manage/home
2) On any existing block click "configure"
3) Open up the "Style Settings" section
4) Add the following two classes: "test_underscore test-hyphen"
5) Save your work and inspect this element. In the rendered markup, both classes will now have a hypen rather than an underscore. 

### Actual behavior (if reporting a bug)

This happened to me when I tried to update a site from v. 1.11.0 to 1.11.2 and found that my theme broke. Upon further research, I traced the problem to the 1.11.1 update and the introduction of a change that modified some of my UI inserted css classes. 

### Expected behavior (if reporting a bug)

I expect that it won't change my classes without warning.

If in fact it's not totally crazy that someone like me might use underscores in a class AND if in fact there is a reason that Backdrop needs to convert those underscores to hyphens, then the UI should probably validate css classes to make sure they are acceptable or at least provide guidance on the best practices for css classes. 

If the underscores are a real problem that needs to be fixed, we should include a note in the release notes warning users that existing classes on blocks and regions with underscores will break. 

### Relevant version/system information (if applicable)

[*Please do not use this issue queue to report security issues*. If you believe
you may have discovered a security issue with Backdrop CMS, contact the Backdrop
Security Team directly at security@backdropcms.org. In order to keep everyone
safe, we manage security issues separately in a private repository. So please
refrain from publicly blogging, or tweeting about it until the issue has been
resolved.]: #

---
PR by @Radcliffe: https://github.com/backdrop/backdrop/pull/2411

**Comment by herbdool** [comment]
This commit https://github.com/backdrop/backdrop/commit/5d8fc76961b303c7068bb9848fa94d35f754cea1 runs the classes through `backdrop_clean_css_identifier` https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_clean_css_identifier/1 which from what I understand is also used with views classes. I can see that the default will change underscore to hyphens.

**Comment by opi** [comment]
for the record, underscores are [W3C valid](https://www.w3.org/TR/CSS21/syndata.html#characters) for CSS idendifiers, and the [Backdrop CSS coding standards](https://api.backdropcms.org/css-standards) does not have explicit rule for CSS identifiers neither.

**Comment by herbdool** [comment]
Looks like the function can be set to keep underscores but that by default they get converted. The function comments say that underscores are valid too.

It happens in a number of places so we'd want to change that all over, no?

**Comment by stpaultim** [comment]
My research and the discussion here suggests that many people discourage the use of underscores in CSS classes. However, it also suggests that there is nothing to prohibit underscores and that some people use them regularly. 

I'm happy to quit using underscores. However, if Backdrop is going to convert classes entered into the UI for reasons that are not entirely obvious to users, there should be some kind of warning and/or validation.

In the meantime, this update broke my website. My insertion of underscores in the UI may be a fringe case, but I would NOT assume so. I was very reluctant to believe that it was the update that caused this problem and it was over a week before I confirmed that it was the upgrade that caused this change and created this issue and it was relatively difficult to see the problem, even when it was right in front of my face. Even with a DIFF file showing me the difference in the new markup, it took me several views to realize what the DIFF was (underscores vs hyphens). It's a very easy different to miss.

I think it best to assume that there might be other sites that either still trying to debug this issue and/or simply have not run the upgrade yet and when they do it will break their css. 

Seems to me that we should either fix this ASAP or potentially append a warning in the readme file for the upgrade explaining what is happening.

**Comment by herbdool** [comment]
I'm okay with allowing underscores but the problem is that we don't want to have one set of rules just for blocks and regions and another for everywhere else. We either allow underscores in everyplace the UI allows user set classes or in none of them.  Now in the current release we don't allow underscores anywhere.

If we do allow underscores everywhere are we breaking backwards compatibility?

**Comment by olafgrabienski** [comment]
> We either allow underscores in everyplace the UI allows user set classes or in none of them.

In my opinion we should allow underscores in CSS classes everywhere in the UI. Don't know if this would break backwards compability, but I guess it would not because it's less restrictive. If we however decide to not allow underscores, there should really be a warning in the UI.

> or potentially append a warning in the readme file for the upgrade explaining what is happening.

Let's also add the information in the release notes.

**Comment by Graham-72** [comment]
The other day I found that part of one of my active sites was broken because of this. I had a menu item 'about us' and somehow a class 'about_us', consequently the styling of a submenu was broken without warning.
Also, I note that Views seems to introduce some underscores in styles, though these don't get broken by the change.
Please allow underscores everywhere.

**Comment by herbdool** [comment]
This should be any easy PR whoever takes it on. But you'll need to decide which items in this list need to be updated because they are cleaning up a class entered via a UI. https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/calls/backdrop_clean_css_identifier/1 Everything else should stay as is because it would break backwards compatibility.

**Comment by stpaultim** [comment]
My colleague and I just took a look at this problem and would like to help with a pull request. But, we have some questions.

1) It would help to better understand the motivation of the change that caused this issue to appear. I can see the commit where the change was make, but I'm not sure how to track that back to an issue that explains why the change was made. 

2) It has been pointed out that we ought to be consistent with how we handle CSS. However, it's unclear to me how we can be both consistent and not potentially break sites. If I added the class "test_class" to a block in Backdrop 1.10, that class would have rendered as "test_class." If I understand correctly that views was already cleaning classes at that time, then the same class in views would have rendered "test-class." Either way, I might have created custom CSS in my theme to accommodate the rendered CSS. 

This suggests to me that we can not be both consistent in how we process CSS and NOT potentially break themes unless we were to render "test_class" as both "test_class" and "test-class" consistently.  

:-(

Another option, would be to be inconsistent and simply apply a different set of filters under different circumstances that best reflect the situation before this change was made. Example: filter out underscores in views (or anyplace that we were filtering for them already), but use different filters in blocks and regions (where we weren't filtering for them). 

Then again, I could be totally misunderstanding the issue.

**Comment by stpaultim** [comment]
More questions:

3) We noticed that the filter on [this function](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_clean_css_identifier/1) seems to change underscores to hyphens, while right below the filter there are comments that specifically indicate that underscores should be permitted. Either the filter is wrong or the comments should be changed?

4) It would appear that the TEST on this page https://api.backdropcms.org/api/backdrop/core%21modules%21simpletest%21tests%21common.test/function/CommonHTMLIdentifierTestCase%3A%3AtestBackdropCleanCSSIdentifier/1 is testing to make sure that valid characters are not being stripped out and includes the underscore in that test. How come this test is not catching this problem?

**Comment by Radcliffe** [comment]
I think that we replace `backdrop_clean_css_identifier($class)` with `backdrop_clean_css_identifier($class, array())` in the lines changed by commit  backdrop/backdrop@5d8fc76. This will remove disallowed characters from the class name without performing character substitutions.

**Comment by herbdool** [comment]
Thanks for the PR, @Radcliffe. I don't think we want to only do this for block classes, because there are other places in the UI where admins can add classes, such as in Views. We need to be consistent if we're going to allow more characters in classes.

Do we want to now allow underscores or also all the others? By passing an empty array we're allowing a bunch of new characters.

**Comment by Radcliffe** [comment]
This change only allows the underscore. The $filter array changes some other characters to hyphens, but if the $filter array is empty then those characters are deleted.

**Comment by Radcliffe** [comment]
Passing an empty array will only allow underscores.  The other characters in the $filter array will be removed by the preg_replace() function.

**Comment by herbdool** [comment]
@stpaultim the original commit was a security fix. I think that's why you don't see an issue number, or maybe it was left out by mistake.

**Comment by stpaultim** [comment]
I tested this in the sandbox. I created a custom block. I placed the custom block in a region and gave the block a class of "tims_block" and the region of "tims_region." I think inspected the code and found that both classes remained unaltered. 

This fixes the problem. However, to mark the RTBC I think we still need someone smarter than myself to verify the following:

1) That this in no way undermines the original intention of the security fix that caused this problem. 
2) Does this fully address @herbdool's concern:

> "I don't think we want to only do this for block classes, because there are other places in the UI where admins can add classes, such as in Views. We need to be consistent if we're going to allow more characters in classes.

To answer this question, I created a Test View in the sandbox and gave it a class of "tims_view" - I then inspected the view in the browser and found BackdropCMS did change my class to "tims-view."

I agree that it is probably important that we are consistent regarding which classes we allow. Does that mean:

1) That we should open another issues for classes for views?
OR 
2) Modify this pull request to also allow underscores in user inputed classes for views?

**Comment by Radcliffe** [comment]
There are quite a few instances of the function
backdrop_clean_css_identifier() in Backdrop core, and I do not know which
ones should be modified to allow underscores. So I made a conservative pull
request to allow underscores where they were removed by the recent security
patch backdrop/backdrop@5d8fc76
<https://github.com/backdrop/backdrop/commit/5d8fc76961b303c7068bb9848fa94d35f754cea1>.
I feel that allowing underscores elsewhere has the potential to affect more
users, so I would propose opening a new issue for this.

**Comment by quicksketch** [comment]
Thanks @Radcliffe for the PR! I agree, I think this is a great solution the solves the immediate problem of the regression created in 1.11.1.

As for other locations, I think anywhere the user explicitly types in a class name we should allow all valid characters, using the same approach you included in your PR of passing in an empty array for the second parameter. Anywhere we have "automatic" class names (such as when we pass in the node type) should stick with the current behavior because otherwise class names are going to change all over the place where we pass in machine names.

For now though, I've merged in https://github.com/backdrop/backdrop/pull/2411 to solve the immediate  problem. Thanks @Radcliffe, @stpaultim, et al!

**Comment by klonos** [comment]
So are we keeping this issue open so to fix the problem in other places too, or follow-ups?

**Comment by jenlampton** [comment]
> So are we keeping this issue open so to fix the problem in other places too, or follow-ups?

Follow-ups please!

**Comment by herbdool** [comment]
I added a follow-up https://github.com/backdrop/backdrop-issues/issues/3428
