### ISSUE TITLE
[UX] The page titles on various "Add xyz" pages do not reflect the action being performed.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3367]
Noticed this while filing #3366:

- `/admin/structure/taxonomy/add`:

    ![screen shot 2018-11-05 at 12 45 49 pm](https://user-images.githubusercontent.com/2423362/47973551-2eb6a380-e0f9-11e8-9e35-abce940d9ae3.png)

- `/admin/structure/menu/add`:

    ![screen shot 2018-11-05 at 12 46 35 pm](https://user-images.githubusercontent.com/2423362/47973572-42620a00-e0f9-11e8-9213-e479d8d3de2f.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2353

**Comment by klonos** [comment]
...some more places:

- `/admin/config/urls/path/add`
- `/admin/config/regional/date-time/formats/add`
- `/admin/config/regional/date-time/formats/[format]/localize`
- `/admin/config/media/image-styles/add`

PR updated.

**Comment by herbdool** [comment]
Tested. Looks good.

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2353 into 1.x and 1.11.x.
