### ISSUE TITLE
[UX] The submit button in the "Add image style" page not styled as primary button.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3368]
### Steps to reproduce (if reporting a bug)

Navigate to `/admin/config/media/image-styles/add`...

### Actual behavior (if reporting a bug)

<img width="535" alt="screen shot 2018-11-05 at 7 15 20 pm" src="https://user-images.githubusercontent.com/2423362/47985952-5c1e4400-e12f-11e8-8e3a-e2831174fc21.png">

Hovered over:

<img width="536" alt="screen shot 2018-11-05 at 7 15 29 pm" src="https://user-images.githubusercontent.com/2423362/47985966-66d8d900-e12f-11e8-9bc3-07126d48999a.png">

### Expected behavior (if reporting a bug)

The button should be styled same as the rest of the primary submit buttons in the admin UI.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2354

**Comment by opi** [comment]
Follow-up: Playing with `git grep "form\['submit'\]"`, I found that the submit button in `admin/modules/install` (in `installer_browser_install_button_form` function). Don't know if it needs to be a primary button.

**Comment by klonos** [comment]
Thanks for the review @opi 🙏 ...and grepping for other instances in order to ensure consistency?! ...my type of guy!! 👍 😄

I think that that specific button is meant to be similar to the "remove" and "add another" buttons in multi-value fields. Perhaps quickly ask the question on Gitter?

**Comment by quicksketch** [comment]
Thanks @klonos and @opi! Merged in https://github.com/backdrop/backdrop/pull/2354 into 1.x and 1.11.x.
