### ISSUE TITLE
Why are 'title' and 'description' in hook_menu() implementations not passed through t().

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3370]
I have noticed that the `'title'` and `'description'` properties in menu items in most if not all `hook_menu()` implementations in core are not passed through `t()`. Unless there is a good reason why not, then we should update them to do so.

**Comment by klonos** [comment]
...if I have this right, this practically makes pages like `/admin/config` untranslatable.

**Comment by herbdool** [comment]
See the explanation for _menu_item_localize() in includes/menu.inc. Title and description get translated there unless the menu router defines a different title callback.

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...it all makes sense now.
