### ISSUE TITLE
The "You do not have any administrative items." message in '/admin/config' is never shown.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3371]
## Describe your issue or idea

I am testing various scenarios with "junior admin" accounts, such as content translators for example. In other words, users with roles that have very few elevated admin permissions.

### Steps to reproduce (if reporting a bug)

1. Create a new role in `/admin/config/people/roles`, for example "translator".
2. Head over to `/admin/config/people/permissions` and assign the "Access administration bar" and "Use the administration pages" permissions to the role created in the previous step.
3. Create a new user and assign them the role created in step 1.
4. Log in as the user created in previous step, and head to `/admin` -> you should see 2 admin items: "Structure" and "Configuration"

### Actual behavior (if reporting a bug)

5. Click on "Structure" -> "You do not have any administrative items." message shown 👍 
6. Go back and click on "Configuration" -> no message 👎 

### Expected behavior (if reporting a bug)

The same "You do not have any administrative items." message should be shown in step 6.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2356

**Comment by quicksketch** [comment]
Minor issue here: https://github.com/backdrop/backdrop/pull/2356/files#r248174517

**Comment by klonos** [comment]
>But I have to ask, why is a user shown admin/config or admin/structure if they don't have any administrative items?

I thought the same while working on this @quicksketch, but I thought that there might be a reason for that (perhaps menu performance?), so instead of changing the current behaviour, I went with just fixing the bug/inconsistency.

>The current fix seems good, just food for thought.

Yes, perhaps follow-up for consideration once this get in?

**Comment by quicksketch** [comment]
Sounds good. The updated PR looks good and I can't see any other issues. Merged into 1.x and 1.12.x. Thanks!
