### ISSUE TITLE
Update jQuery.once to the latest 2.x - or switch to Drupal once()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3376]
This was the initial purpose of #687:

@quicksketch:
>Version 2.2.0 is now the latest. From the PRs, I think we can jump right to 2.x versions rather than sticking on 1.x. The differences in actual code between branches are pretty minimal. The addition of `findOnce()` and more packaging options seem to be the two big differences, which shouldn't affect us or our using of `.once()` in Backdrop.

...

> Looks like I was incorrect about 2.x being compatible.
> 
> We have many uses of `once` that use this syntax:
> 
> ```
> $('.selector').once('collapse', function() { ... });
> ```
> 
> But passing in a function as the second parameter is no longer supported. You now have to use `.each()` to loop over the result:
> 
> ```
> $('.selector').once('collapse').each(function() { ... });
> ```

---

Related: https://www.drupal.org/project/drupal/issues/2402103 

> ## Problem/Motivation
> The once feature is used in almost all core behaviors. The once feature is implemented as a jQuery plugin, making it impossible to remove jQuery from core scripts.
>
> ## Proposed resolution
> Implement a vanilla js version of the once feature.

---

> # Original report by droplet
>Inspired from http://eleks.github.io/js2js/. Now I totally rewritten jQuery.once into Plain JavaScript Code. Aiming to provide a modern pattern widely used everywhere, not just the Drupal way.
> 
> ## Features / Changes:
>
> - Remove dependency on jQuery.
> - Use HTML5 `data-*` attribute (not the `jQuery.data()`). It's better for debugging and work with other scripts. eg. You now able to query it directly: `document.querySelectorAll(["data-drupal-once"]))`
> - Performance improvements
> - Fully pass jQuery.once testcases
> - Light weight & More easier to adopt other libs. eg. Converting to jQuery Chaining way: https://github.com/KayLeung/dropletOnce/blob/master/jquery.droplet.once.js

> ## Performance testing result:
> https://docs.google.com/spreadsheets/d/1KXVKZS-HJhbQFgUYUmzPzMpJpEMOPXyGZEAn46I_RVY/edit?usp=sharing
> ** Noticeable performance diff on iPhones.
>
> ## Testing Repo:
> https://github.com/KayLeung/dropletOnce

> ## The reason I do not like jQuery.Once 2.0:
>
> - jQuery adding overhead. Including libs size and execution time ( I'm doubt the performance improves between jQuery Once 1.0 .class way and Version 2.0 jQuery.data on modern browsers )
> - No standard identify for themer (.once-class)
> - No visual debugging info for themer ( You can't see the Onced elements in devtools. You must use JS to loop over to see if that elements if Onced or not. This is not friendly for HTML/CSS themers)
> - One way synced only. jQuery.Once 2.0 use jQuery.data to track Onced elements. It will not synced back to HTML DOM.
> - Not a modern way. Popular frameworks use standard HTML5 `data-*` attribute. Not the `jQuery.data()`

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2376 (updates to 2.2.2)

**Comment by herbdool** [comment]
I left one small comment.

**Comment by klonos** [comment]
Sorry @herbdool ...I don't see the comment. Forgot to press "save" perhaps?

**Comment by herbdool** [comment]
Now it's there. On mobile the submit review button is way on the bottom.

**Comment by klonos** [comment]
😄 ...saw it, fixed 😉

**Comment by quicksketch** [comment]
I don't think we can do this without an API break. The PR switching the arguments works but it clearly is making a change due the difference in 1.x vs. 2.x of the `once` library. This library is used extensively through contrib using the previous syntax. We could go ahead and switch to the new syntax but not update the library, getting ready essentially, but we can't break most of contrib's JS mid-cycle.

I'm going to move this to 2.x, but if we have other thoughts about how to make this feasible in 1.x we can reconsider.

**Comment by klonos** [comment]
Sounds reasonable @quicksketch 👍 

I will see if I can figure out a way to intercept usage of `.once` and have some sort of BC layer to it. ...but it may be over my skillset 😓

**Comment by klonos** [comment]
...and yet a newer 2.2.3 release 5 days ago: https://github.com/RobLoach/jquery-once/releases/tag/2.2.3 ([single-line change](https://github.com/RobLoach/jquery-once/commit/c78e26c8c8d919601d9168fe62eb01e494cd2b87), to fix https://github.com/RobLoach/jquery-once/issues/91).

PR updated again.

**Comment by klonos** [comment]
Drupal has replaced jQuery.once with a custom, pure JS alternative in 9.2.x. Change record: https://www.drupal.org/node/3158256

The change record mentions backward compatibility:

> ## Backwards compatibility
> If code is relying on an existing once call from core, an additional BC layer is automatically added when once is used alongside jquery.once. Calls to jQuery.once will honor previous calls to once().

Perhaps this means that we can also switch to that (the assumption being that it will be more well-maintained), but I'm not knowledgeable enough to be the judge of that.

**Comment by klonos** [comment]
v2.3.0 was released back in January this year: https://github.com/RobLoach/jquery-once/releases/tag/2.3.0

**Comment by indigoxela** [comment]
> v2.3.0 was released back in January this year

@klonos you might have missed, that we forked jQuery.once [last year](https://github.com/backdrop/backdrop-issues/issues/6195).

It's probably time, to close this issue here. It won't happen and is unnecessary, anyway.

**Comment by klonos** [comment]
Closing then 👍🏼
