### ISSUE TITLE
Undefined index: path in path_entity_insert when creating content with paragraphs module

### ISSUE THREAD

**Issue by andybroomfield** [backdrop/backdrop-issues#3377]
## PHP error in path module when creating a node that uses paragraphs module
Not sure if this is right place or belongs as an issue in paragraphs. 
The error is generated by path.module when trying to auto alias, and paragraphs entities won't have anything to alias as they do not have paths.

### Steps to reproduce (if reporting a bug)

1. - Install and enable Paragraphs module.
2. - Create a paragraph bundle with at least one field.
3. - Create a content type that uses paragraph field and the bundle your created.
4. - Create new content of that type, with some content inside the paragraph field.
5. - Save new content.
Error only occurs when creating new content, not updating.

### Actual behavior (if reporting a bug)
PHP error : Undefined index: path in path_entity_insert()
> Error messageNotice: Undefined index: path in path_entity_insert() (line 455 of /Users/Andy/Sites/fantsuam-new/httpdocs/core/modules/path/path.module).
### Expected behavior (if reporting a bug)
No error message

### Relevant version/system information (if applicable)
Backdrop v1.11.2
Paragraphs v1.x-1.0.1

I was able to fix by wrapping the path_entity_insert hook code in an empty check for entity url
````php
function path_entity_insert(Entity $entity) {
  $langcode = isset($entity->langcode) ? $entity->langcode : LANGUAGE_NONE;
  $uri = $entity->uri();
  
  // Patch for paragraphs no uri in entity so no path to alias
  if (!empty($uri)) {
````

This also happens when deleting content with paragraph fields.
Applied same fix from line 759
````php
function path_delete_all_by_entity(Entity $entity, $default_uri = NULL) {
  $uri = $entity->uri();
  
  // Guard check if URI is present
  if (!empty($uri)) {
    path_delete_all_by_source($uri['path']);
    if (isset($default_uri) && $uri['path'] != $default_uri) {
      path_delete_all_by_source($default_uri);
    }
  }
}
````
---
PR by @andybroomfield: https://github.com/backdrop/backdrop/pull/2379

**Comment by klonos** [comment]
Hello @andybroomfield and thanks for taking the time to file this report. I was able to reproduce the error using the steps you mention in the issue summary. I also confirm that it only happens on node add/delete - not on node update.

No need to worry if this actually belongs in https://github.com/backdrop-contrib/paragraphs/issues or not. If it does, we can now transfer issues across repos in GitHub:

![screen shot 2018-11-11 at 8 28 59 pm](https://user-images.githubusercontent.com/2423362/48311215-7e610780-e5f0-11e8-8844-d6666bc5aa0f.png)

😉

**Comment by andybroomfield** [comment]
Thanks @klonos and @laryn, I noticed that the path_entity_update hook wraps its code in 
````php
if (isset($entity->path)) {
````
Which might be a better fix and keep things consistent.

**Comment by klonos** [comment]
Thanks @andybroomfield 👍 ...the code changes make perfect sense, and tests now also pass in the CI 😄.

I have re-tested and things still work and no errors logged, so RTBC!

**Comment by klonos** [comment]
...still leaving the "needs feedback" tag for @quicksketch or @serundeputy to chime in.

**Comment by quicksketch** [comment]
Thanks @andybroomfield, @klonos, and @laryn! Merged https://github.com/backdrop/backdrop/pull/2379 into 1.x and 1.11.x. You're right that URI is optional, per the documentation, so we need to handle this use-case.
