### ISSUE TITLE
[UX] Default text formats are not saved properly without accompanying values

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3378]
## Background

This is related to #2615 and the respective d.org issue https://www.drupal.org/project/drupal/issues/784672 (see also issue https://www.drupal.org/project/better_formats/issues/1295248 for the contrib module [Better Formats](https://www.drupal.org/project/better_formats))

The discussion in the "parent" issue brought https://www.drupal.org/project/drupal/issues/1278886 to life, which is what this issue here is about. It was originally filed against D7, but as it tends to happen for most issues, it was switched to D8. So there is also https://www.drupal.org/project/drupal/issues/2852019, which is D7-specific.

TL;DR or still confused? 😄 ...keep calm and read the STR bellow:

### Steps to reproduce (if reporting a bug)

1. Either add a new field of type "Text (long)" or "Text (long with summary)", or edit an existing one.
2. In the "Text processing" section, change the value to "Filtered text (user selects text format)" if not already set to that:
   ![screen shot 2018-11-11 at 1 21 04 pm](https://user-images.githubusercontent.com/2423362/48308274-02959980-e5b5-11e8-80ea-8a53d510e516.png)
   ...if you had to change this setting, save the field settings and re-edit the field to have the WYSIWYG editor with the options be rendered (#3379).
3. Expand the "FORMATTING OPTIONS" fieldset bellow the WYSIWYG editor, and select a format other than what the default is set to. In a vanilla installation of Backdrop, it should be "Filtered HTML", so change it to "Full HTML":
   ![screen shot 2018-11-11 at 1 22 33 pm](https://user-images.githubusercontent.com/2423362/48308282-3cff3680-e5b5-11e8-8bf5-04178fd2133a.png)
4. Save the field settings...

### Actual behavior (if reporting a bug)

...when you edit the field settings again, the format is still set to "Filtered HTML" (or whatever the default is for your installation).

### Expected behavior (if reporting a bug)

...when you edit the field settings again, the format should be set to "Full HTML"
(or whatever it was that you set it to in step 3 above).

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2377 (all credits for this should go to @jenlampton as she is the author of the original patch against D7 core)

**Comment by klonos** [comment]
Comments worth mentioning from the long discussions in d.org:

@david-hernandez [commented 8 February 2013 at 07:34](https://www.drupal.org/project/drupal/issues/1278886#comment-7039630)

> Hi there,
> 
> I'm not sure if this change is really necessary. Do we really need to save the input format of the default value if the default value is empty?
> 
> If the default value is empty, means that the user will have to write the content of the field and then, the input format selected by default should be on "Text Processing".
> 
> I'm not sure if I'm not understanding correctly the issue or the issue itself doesn't make any sense.
> 
> By the way the solution for tests failing (#17) is not changing the test, but fixing the issue that is causing the test to fail. A test should only be changed if the requirement has changed too.
> 
> I think this works as designed and the issue can be closed.
> 
> Regards,
> David.

If I am reading this comment right, then what is debatable is that the filter setting for the default value only makes sense when actually setting a default value. If the sole purpose of changing the filter value was in order to have that value be the default filter when the content edit form loads, then perhaps this should be worked on in #2615.

@sun [commented 10 February 2013 at 15:48](https://www.drupal.org/project/drupal/issues/1278886#comment-7048638)

> ...
> Filter module provides a pretty advanced concept for default text formats already. It automatically figures out which formats are available and intersects that with the formats that the current user is able to access. Out of that limited set of formats, the first one (weighing lowest) is the current user's default format.
> 
> That part seems to be missing in your equation, as your use-case seems to be to create a new, empty node, with a pre-configured text format? And you're making the bold assumption that the "other" user who's supposed to edit that node (also) has access to the text format you selected?
> 
> If the current user does not have access to the selected text format, then all the user sees is a disabled textarea that informs him/her that its content cannot be edited due to access constraints.

@jenlampton [commented 6 September 2015 at 06:42](https://www.drupal.org/project/drupal/issues/1278886#comment-10296839)

> I'm still using this patch on all my sites. In my view this is definitely a UX problem for the site-builder, and therefore a core bug. The solution also offers a UX improvement to the user entering content. win-win!
> 
> @sun's comment in [#26](https://www.drupal.org/project/drupal/issues/1278886#comment-7048638) is a valid one. Drupal does have a complicated process for figuring out what the "default" text format should be based on the current user and their level of access.
> 
> However, the user + access calculation will result in the same "default" format everywhere on a Drupal site, and in reality, not all filtered text fields are equal. You may have one field where you want users to have a WYSIWYG (for example, body) and others where you specifically do not want users to have a wysiwyg. Drupal's calculations do not take this into effect.
> 
> Though it's possible to demand that everyone who encounters that problem should provide either a custom module with a `form_alter` in it, or require that they use a complicated set of contrib modules, the solution in this patch is much simpler.
> 
> @sun, what's the harm in setting a default format? A user who does not have access to the default won't get it, they'll get the behavior we see now. But a user who does have access to that format gets a UX improvement. I'm not sure I understand the hesitation here.

...then -unless there are other valid reasons- let's not hesitate in Backdrop @jenlampton. Shall we? 😄 ...that way neither you nor I nor anybody else should have to re-apply patches on their sites 😉

**Comment by jenlampton** [comment]
This issue still needs more feedback, removing milestone, but adding milestone candidate tag.

**Comment by oadaeh** [comment]
This issue is really quite frustrating.
The PR in https://github.com/backdrop/backdrop/pull/2377 fixed it for my testing.
Whether it's the correct approach or not I cannot say, as I'm trying to evaluate something else, and the time I can put into that is quite limited.

**Comment by laryn** [comment]
I would love to be able to set a default editor on a field! From a end user perspective this PR works -- I created a new content type and changed the Body field's text format to "Filtered HTML". Then I changed the Body field in the Page content type to "Full HTML" by default. When I create new content in each type, the format of the Body is different, as expected.

**Comment by quicksketch** [comment]
I tried out the sandbox and everything works as expected. I was pleased to see that if a user doesn't have access to a format on /node/add/post, the text format just selects the first format they do have access to as long as the text string is empty.
