### ISSUE TITLE
Both Basis and Bartik claim to be "the default front-end theme for Backdrop CMS"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3392]
<img width="921" alt="screen shot 2018-11-25 at 9 09 35 am" src="https://user-images.githubusercontent.com/2423362/48973371-fcfa8200-f091-11e8-85d0-c16738fdaba9.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2392

**Comment by klonos** [comment]
...simple PR filed to change the description of Bartik to "Legacy front-end theme."

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2392 into 1.x and 1.11.x.
