### ISSUE TITLE
[UX] Better description for the breadcrumb block.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3394]
In Backdrop, we have moved the breadcrumb settings from the theme level into block settings (#130). The description we are currently using for the breadcrumb block though uses the word "breadcrumb" to describe the breadcrumb:

> The current page breadcrumb trail.

🙄

![screen shot 2018-11-25 at 9 25 38 am](https://user-images.githubusercontent.com/2423362/48973468-1f8d9a80-f094-11e8-8db8-b80452d8549a.png)

...I think that the description in [`hook_form_system_theme_settings_alter()`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/theme.api.php#L92) is doing a much better job (although not used anywhere in the admin UI AFAICT - see #3393):

> Show a trail of links from the homepage to the current page.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2393

**Comment by klonos** [comment]
...screenshot from the PR sandbox:

<img width="887" alt="screen shot 2018-11-25 at 9 34 56 am" src="https://user-images.githubusercontent.com/2423362/48973537-6a5be200-f095-11e8-8946-76419087c547.png">

**Comment by herbdool** [comment]
Other than small correction, looks good.

**Comment by stpaultim** [comment]
I also checked this out in the sandbox and it looks good to me. Seems like a sensible improvement.

**Comment by stpaultim** [comment]
I am going out on a limb and going to mark this RTBC. Let me know if that was premature.

**Comment by quicksketch** [comment]
Thanks! Great little improvement. Merged into 1.x and 1.11.x.
