### ISSUE TITLE
[D8 feature parity] Views: add machine name and show all displays in the views listing.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3395]
The views listing in D8 offers some additional info, like the machine name of the view, and they have replaced the "Paths" column with a slightly more informative "Displays" column, which shows all display types:

![screencapture-8-6-2-local-admin-structure-views-2018-11-25-16_52_11](https://user-images.githubusercontent.com/2423362/48976031-664eb500-f0d3-11e8-9915-b26140f95f50.png)

Here's what we have currently:

<img width="1182" alt="screen shot 2018-11-25 at 4 51 16 pm" src="https://user-images.githubusercontent.com/2423362/48976034-79618500-f0d3-11e8-80b1-3cf427b263d4.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2394

**Comment by klonos** [comment]
PR up for review:

![screencapture-2394-backdrop-backdrop-qa-backdropcms-org-admin-structure-views-2018-11-25-17_20_25](https://user-images.githubusercontent.com/2423362/48976191-bd09be00-f0d6-11e8-8260-7b615f70549e.png)

Changes:

- Removed the "Displays" entry form the "View info" column.
- Added a "Machine name" entry in the  "View info" column.
- Renamed the "Path(s)" column to "Displays"
- Added all displays in the "Displays" column
  - If a display has a path (feed or page display), the path is added next to the display type label, and paths are linkified if the view is not disabled, and if there are no argument placeholders in the path:
    - Page: /path/to/page
    - Feed: /path-to-feed.xml
  - If the display is a block, then the block admin label is added next to the display label:
    - Block: [block_label]

Code-wise:

- I have added a new `_views_ui_get_displays()` helper function, since the existing one `_views_ui_get_paths()` would not make sense name-wise. Is it safe to remove that helper function now that it is not being used?
- There was also a `_views_ui_get_displays_list()` helper function used in `theme_views_ui_view_info()` in views_ui.theme.inc to render the "Displays" entry in the "View info" column. I have removed the calls to this function, since the displays are not going to be rendered in that column any more. Again, is it safe to remove this helper function?

**Comment by BWPanda** [comment]
Review of screenshot above:

- I've never liked the collection of (overwhelming) information in the 'View info' column. I'd prefer each piece of information deemed worthy of being shown in this table be given its own column...
- I love the new/improved 'Displays' column, but I don't like the bullets used there, especially since it means the content doesn't line up with the column heading.

**Comment by herbdool** [comment]
I tend to agree with @BWPanda so long as it doesn't get too wide with columns.

**Comment by klonos** [comment]
Thanks for the feedback @BWPanda and @herbdool 👍

D8 has the advantage of this listing spanning 100% of the width of the screen, so they can accomodate more columns without resulting in an overly "crammed" table (many columns wrapping text/content etc.). They do have the view machine name be in a separate column, so if we also moved it, we'd reach more feature parity, but not sure if that is as important as having the info available. I would worry more about the fact that we do not provide a search field in that listing TBH.

Anyway, if we get consensus on what needs to be moved into a separate column, and also what priorities these columns should have (for when viewed in mobile/tablet mode), then I will update the PR.

Things to note:

- I have added a "Status" label for Default/Custom, but this feels that it should be a "Type" label instead (status should be reserved for Enabled/Disabled). But I could not use that, because there is a "Type" label already, used for the base table of the view. If we could come up with a better label for the base table info, then the "Type" label would be free to be used for Default/Custom.
- If we added a searchbox at the top of that listing, we could add a filter for Default/Custom, so these could then be removed from the "View info" column altogether perhaps.

@BWPanda the bullets are required IMO, because in narrower screens the text of the same list item might get wrapped and then it is becomes a readability issue. I have updated the PR to adjust the margin in the lists within the "Displays" column. Care to take another look and see how it feels now?:

![screencapture-2394-backdrop-backdrop-qa-backdropcms-org-admin-structure-views-2018-11-26-14_50_07](https://user-images.githubusercontent.com/2423362/48992193-acb31b00-f18a-11e8-99ed-073b3a8425e2.png)

**Comment by klonos** [comment]
@BWPanda we have been introducing the bullets as a readability enhancement in a couple of other places like ??? and ???, so it'd feel weird to not be doing the same here. As for what D8 is doing in smaller screens, well not much really:

![screencapture-8-6-2-local-admin-structure-views-2018-11-26-17_56_32](https://user-images.githubusercontent.com/2423362/48998003-0aa12c00-f1a6-11e8-8ca2-462dd4fcd4e6.png)

(the portion to the right of the screenshot is outside the browser viewport)

I do like the idea about a fieldset (or more/less section) where we can stash the additional info currently crammed into the "View info" column. It is a UI pattern we are using elsewhere (modules listing, site status page, etc.). But perhaps a separate follow-up issue?

**Comment by herbdool** [comment]
How about:

* Name (machine_name)
* Info (Status, Type, Tags)
* Description
* Displays
* Operations

Machine name doesn't seem important enough to be its own column but moving the other stuff to their own column might make it read better.

**Comment by klonos** [comment]
I agree @herbdool ...with the exception of tags, which I feel that they fit perfectly with the description (as it currently is). I have updated the PR. Here's how it looks:

![screen shot 2018-11-27 at 10 42 26 am](https://user-images.githubusercontent.com/2423362/49048994-387f8280-f231-11e8-8cae-3e57cf8c0d18.png)

**Comment by klonos** [comment]
...I thought too add priorities in the columns, in order for the "View info" and "Description" to be hidden on tablet and then also "Displays" hidden on mobile, but it seems that we are using a totally different layout on mobile:

![screencapture-2394-backdrop-backdrop-qa-backdropcms-org-admin-structure-views-2018-11-27-10_44_48](https://user-images.githubusercontent.com/2423362/49049112-b6dc2480-f231-11e8-9b58-dcf689a6da4e.png)

...so I've left things as they are for now.

**Comment by herbdool** [comment]
Looks good to me now

**Comment by jenlampton** [comment]
wow, I love this :)

**Comment by BWPanda** [comment]
A few thoughts based on https://github.com/backdrop/backdrop-issues/issues/3395#issuecomment-441842972:

- Either add 'View ...' to each column name, or remove 'View' from all (I personally prefer the latter (e.g. Name, Info, Description, etc.). Since this is an overview of views, I don't see the need for adding 'View' to the column names (though it'd be better to be consistent than have some with and some without).
- Put the machine name on a new line after the view name. This is how most are displayed anyway (because of the length of the names), but when there's a shorter one (user_admin) it looks different... Be nice to have them all consistent.
- Is there a reason for the different font type for machine names and types? Can they not all use the same font as everything else?

**Comment by klonos** [comment]
@BWPanda:

- You are absolutely right. I have removed "Views" from all the column headers.

- Done!

- Hmm, I guess I was under the impression that we have been using monospace for machine names throughout the UI. Seems we are just using `font-size: smaller;`:

  ![screen shot 2018-11-27 at 6 17 03 pm](https://user-images.githubusercontent.com/2423362/49066511-73a3a500-f275-11e8-927f-31fac15dfb9c.png)
  ![screen shot 2018-11-27 at 6 15 49 pm](https://user-images.githubusercontent.com/2423362/49066515-756d6880-f275-11e8-8b3a-c052f196cd7f.png)

**Comment by klonos** [comment]
...here's how the new iteration looks like (I have also made some minor adjustments to the column widths so that it looks a bit nicer OOTB):

![screen shot 2018-11-27 at 7 23 58 pm](https://user-images.githubusercontent.com/2423362/49068423-d186bb80-f27a-11e8-89a1-cfc52bfd053b.png)

**Comment by BWPanda** [comment]
Yes, much nicer and very clean looking! :+1:

**Comment by jenlampton** [comment]
Yes, much better!

I wonder, however, if the `Type` information should go somewhere other than the `Info` column.  I'd like to see that column labeled "Storage state" like it is everywhere else in core (and the `Status:` label removed). here are a few examples:
* the layouts list (admin/structure/layouts) 
* the image style list (admin/config/media/image-styles)

Can we move the type into the description field?  Keep in mind that Tags will rarely show up after https://github.com/backdrop/backdrop-issues/issues/2074 gets done.

**Comment by klonos** [comment]
Makes perfect sense @jenlampton (you know me and consistency 😜) ...next iteration:

![screen shot 2018-11-30 at 5 12 31 am](https://user-images.githubusercontent.com/2423362/49242390-b96f9180-f45e-11e8-83e2-367e882e601f.png)

**Comment by jenlampton** [comment]
Love it!

**Comment by laryn** [comment]
Sidebar question: In terms of consistency, do we want to consider (in a separate issue) moving `machine_name` to the name/label column more generally? e.g.

![screen shot 2018-11-29 at 5 30 11 pm](https://user-images.githubusercontent.com/871421/49258853-8ac0cf00-f3fc-11e8-9514-eb74cfccbb3b.jpg)

**Comment by klonos** [comment]
@laryn I would not mind it if we did. The reasons we did it here is a) because we are trying to save some horizontal space, and b) the table rows are spanning multiple lines, so adding the machine name under the free/unused space under the label seemed like a good choice.

Perhaps it does not make as much sense to do it for such reasons in other places, but as I said it does not take to much arguing to convince me about consistency-related issues 😄 ...follow-up issue?

**Comment by jenlampton** [comment]
The code for this PR looks fantastic, I've marked it as RTBC and tagged it with 1.11.3. @herbdool @quicksketch @serundeputy I didn't see a reason this change couldn't go into a bug-fix release, but if you'd rather it wait for 1.12 feel free to set the milestone back.

**Comment by quicksketch** [comment]
Looks like there is one markup issue and two `t()` calls that could be formatted better. I left suggestions in the PR: https://github.com/backdrop/backdrop/pull/2394#pullrequestreview-184453342

**Comment by jenlampton** [comment]
> not sure if I can automatically set back to RTBC or not.

Not if you are the one who fixed it... But I can! :) I added a few more comments on the PR about language for the UI.

**Comment by klonos** [comment]
Sorry for the late response @jenlampton ...both great suggestions 👍 ...updated the PR. Care to take another look and RTBC if happy with it now?

PS: the PR is still marked as "Changes requested", even though I have addressed all comments by @quicksketch. Perhaps it needs manual approval? 🤷‍♂️

**Comment by jenlampton** [comment]
Looks great @klonos nice work!

**Comment by herbdool** [comment]
Yup looks good. It helped me notice that the image library view is set to custom instead of module provided. That's a mistake I think. Do we have an issue for that?

**Comment by jenlampton** [comment]
> the image library view is set to custom instead of module provided. That's a mistake I think. Do we have an issue for that?

I haven't seen one.

**Comment by herbdool** [comment]
I added one https://github.com/backdrop/backdrop-issues/issues/3443

**Comment by klonos** [comment]
> It helped me notice that the image library view is set to custom instead of module provided.

Glad to see this is being useful before it even gets committed 😄
