### ISSUE TITLE
HTTP status 200 returned for "Additional uncaught exception thrown while handling exception"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3398]
This is the respective issue for https://www.drupal.org/project/drupal/issues/2666908 (and could be related to #1655)..

> Drupal seems to return a 200 OK HTTP status code for exception errors thrown by `_drupal_exception_handler()`. This doesn't seem right, since that causes the error page to be cached, for example in Varnish. Is there a reason for this behaviour? I couldn't find an issue for the bug, but it has been mentioned on the support forum at https://www.drupal.org/node/2598442.

...the respective issue for D8 is [Default all responses to 500 before any code is run so PHP will throw 500's on FATAL errors](https://www.drupal.org/project/drupal/issues/2688999):

> ## Problem/Motivation
>If PHP throws a FATAL error, a 200 response will be returned.
>
>This could mean that the 200 'OK' response gets cached by a browser, a reverse proxy, or a CDN.
>
> ## Proposed resolution
> I was sure PHP could return a 500 is maybe display_errors were turned off, but from testing this wasn't happening for me.
>
>If we set the status code to 500 in index.php, before any other code is run, we can ensure that PHP will return a 500 response code for FATAL errors. All other cases will be handled by a Response object, so will have the correct/intended status code

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2395

**Comment by klonos** [comment]
This major bug, which was reported back in Feb 2016 and has been RTBC'ed in d.org since May 2018, has creeped on us today in the GovCMS project, where error pages caused by a misbehaving https://www.drupal.org/project/redis module were being cached by Akamai. So this was perceived as "broken sites" by end users.

I understand that this seems like more of an "enterprise" problem, which is less likely to effect our target audience, but although we are placing ourselves as a CMS for the "small players", it certainly does not mean that Backdrop CMS is not used in "big" infrastructure, where this problem seems to be more prone to surface often.

^^ that's my way of saying that we should not wait for another year and a half before our d.org brethren decide to finally act and apply this single-line-of-code fix and release a new D7 version.

**Comment by herbdool** [comment]
I reviewed but didn't test. I read through the comments on d.org and all are positive. This patch should help for Backdrop sites on Pantheon, etc

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2395 into 1.x and 1.11.x.
