### ISSUE TITLE
PHP 7.2 compatibility: "The each() function is deprecated." Views and Diff modules.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3403]
I couldn't find an existing issue for this...

I'm getting this message when using Views:

> Deprecated function: The each() function is deprecated. This message will be suppressed on further calls in views_ui_ajax_form() (line 2840 of /[BACKDROP]/core/modules/views_ui/views_ui.admin.inc).

See https://github.com/backdrop/backdrop/blob/1.x/core/modules/views_ui/views_ui.admin.inc#L2840

I believe this is part of PHP7 (I'm running PHP v7.2.10).

---
PR: https://github.com/backdrop/backdrop/pull/2436 by @herbdool.

**Comment by quicksketch** [comment]
Thanks! I just did a quick search based on the Drupal 7.61 cross-ports issue (https://github.com/backdrop/backdrop-issues/issues/3375). While Backdrop is not affected by the patch applied to Drupal 7, we do still have 4 locations where `each()` is used, which is a deprecated function in PHP 7.2.

`view.inc` line 1775:
```
    if (isset($this->last_query_key)) {
      while (list($id, $query) = each($queries)) {
        if ($id == $this->last_query_key) {
          break;
        }

        unset($temp[$id]);
      }
    }
```

`views_ui.admin.inc` line 2839:

```
    reset($view->stack);
    list($key, $top) = each($view->stack);
    unset($view->stack[$key]);

    if (array_shift($top) != $identifier) {
      $view->stack = array();
    }
```

`diff.inc` line 383 and 392:
```
        while (list(, $y) = each($matches)) {
          if (empty($this->in_seq[$y])) {
            $k = $this->lcsPos($y);
            assert('$k > 0');
            $ymids[$k] = $ymids[$k - 1];
            break;
          }
        }

        while (list(, $y) = each($matches)) {
          if ($y > $this->seq[$k - 1]) {
            assert('$y < $this->seq[$k]');
            // Optimization: this is a common case:
            //	next match is just replacing previous match.
            $this->in_seq[$this->seq[$k]] = FALSE;
            $this->seq[$k] = $y;
            $this->in_seq[$y] = 1;
          }
          elseif (empty($this->in_seq[$y])) {
            $k = $this->lcsPos($y);
            assert('$k > 0');
            $ymids[$k] = $ymids[$k - 1];
          }
        }
```

Unfortunately, `each()` usage like this is completely foreign to me. @hosef fixed most of our `each()` usages a while back in https://github.com/backdrop/backdrop-issues/issues/2948. Looks like either we added a few new ones or these are just ones that are Backdrop-specific that did not affect Drupal core, which seems likely because all 3 of these files came from D7 contrib.

**Comment by herbdool** [comment]
The Views patch is here https://www.drupal.org/project/views/issues/2946216

**Comment by herbdool** [comment]
The diff patch is not quite the same but the fix is similar https://www.drupal.org/project/diff/issues/2946139

**Comment by herbdool** [comment]
I made a PR https://github.com/backdrop/backdrop/pull/2436

**Comment by klonos** [comment]
PR looks good in general, and tests are green. I'd like to see if I can test more in depth the functionality of the sections changed, but don't have the time at the moment.

@quicksketch at some point during one of the dev meetings we have discussed about making the php70 test a php72 instead. What would be the best way to go about doing that?

^^ ping @Gormartsen

**Comment by herbdool** [comment]
@klonos I think we can mark it RTBC since my PR is based on the patches for D7 which were reviewed and merged into those projects.

**Comment by quicksketch** [comment]
Awesome work @herbdool! I tested out the diff manually using the config sync and it works great there. Thanks! I've merged into 1.x and 1.11.x.

**Comment by jenlampton** [comment]
I'm getting a similar deprecation notice about `assert()` 
see https://github.com/backdrop/backdrop-issues/issues/4531
