### ISSUE TITLE
Custom message blocks

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3408]
## Describe your issue or idea

Now that we have #3155, I think that it would be a great feature to allow the creation of a new block type called "Custom message". These blocks would allow for some text to be added, and the user would have a drop-down menu available to select from `info`, `success`, `warning`, and `error`. Such blocks would then be rendered and styled to look like the system messages generated by [`backdrop_set_message()`](https://api.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/backdrop_set_message).

This would effectively allow site builders to add custom messages to various pages (layouts really), and would allow them to take advantage of the visibility conditions we have in place, to show these messages for example only to specific users/roles, or only in specific paths etc.

Another use case would be to allow site builders/admins to show messages such as scheduled downtime and/or announcements, using contrib modules such as https://github.com/backdrop-contrib/block_scheduler.

Related to #495, since we could use such blocks to allow site builders to provide custom help text to the people using the admin dashboards.

---
PR by @klonos (allows selecting a message style from the block configuration dialog): https://github.com/backdrop/backdrop/pull/2432
alternative PR by @klonos (simply removes extraneous top padding from blocks styled as messages): https://github.com/backdrop/backdrop/pull/2438

**Comment by klonos** [comment]
Not sure if we want to create a separate block type, or extend the existing custom block type.

Also not sure if these should be text blocks styled to resemble messages, or if the text added to these blocks should actually be passed on to `backdrop_set_message()`. I think that later.

**Comment by olafgrabienski** [comment]
> This would effectively allow site builders to add custom messages to various pages (layouts really), and would allow them to take advantage of the visibility conditions we have in place, to show these messages for example only to specific users/roles, or only in specific paths etc.

That would be great, I need such blocks quite often. At the moment, to do so, I create custom blocks in Full HTML format and copy the markup of system messages.

**Comment by klonos** [comment]
...lets see if we can get this in for 1.12 🤞

http://2432.backdrop.backdrop.qa.backdropcms.org/posts/your-first-post

<img width="1158" alt="screen shot 2018-12-26 at 5 57 07 pm" src="https://user-images.githubusercontent.com/2423362/50450661-f7fe4c00-0937-11e9-8d1d-075378ed90df.png">

I have implemented this as a new block style available for custom text blocks:

<img width="618" alt="screen shot 2018-12-26 at 6 00 00 pm" src="https://user-images.githubusercontent.com/2423362/50450702-33991600-0938-11e9-8601-f94b5674e292.png">

@olafgrabienski it would be great to get your opinion on this since you say you are using it currently 😄

**Comment by olafgrabienski** [comment]
@klonos I've had a quick look at the PR's sandbox page and created a test message block for `node/add/page` and  `node/add/post`, works like a charm!

I'm not sure how to handle the "Display title" of the block. Using this block style, the "Display title" isn't rendered when you visit the page with the block. That's reasonable, in my opinion, and the "Display title" is still useful as block name within the layout. But people might expect that the "Display title" is shown on the page with the block, and there is no indication in the block configuration that it would not.

**Comment by klonos** [comment]
> ...But people might expect that the "Display title" is shown on the page with the block, and there is no indication in the block configuration that it would not.

How about this then @olafgrabienski?:

<img width="627" alt="screen shot 2018-12-27 at 10 09 16 pm" src="https://user-images.githubusercontent.com/2423362/50493121-28231900-0a24-11e9-8fea-8f7482a6cc0e.png">

**Comment by klonos** [comment]
...things I would like to improve:

- Either set a default message type when creating a new message block, or have the message type be required. As it is now, without any default + the field not being required, one is allowed to create a message type that has no styling ...which with the current implementation breaks the page styling in that case.

- Have any custom text block that is styled as a message, be denoted as such in the "Manage blocks" page (have a "Custom message block" title, instead of just "Custom block")

I would like some feedback re the first point. Should I go with a default type? ...and if so, then which type?

**Comment by olafgrabienski** [comment]
@klonos Re `The display title will not be rendered in the frontend when the block type is set to "message" (...)`, I think the term "frontend" is ambiguous because you can place such a block in the 'backend' (i.e. on administrative pages). What about `The display title will not be rendered with the block if the type is set to "message" (...)`?

Regarding a default message type, I'd suggest `info`.

**Comment by jenlampton** [comment]
People can already use a custom block, add the necessary classes and markup
if they really want to fake a message.

I don't want to see this feature in core unless is be ones a top contrib
project, it's a slippery slope for other block styles.

Jen

**Comment by klonos** [comment]
Fair enough. Although this assumes that people know what classes to use :/

The only thing I have found that is required when using the classes directly in the block configuration dialog, is some CSS to remove some extraneous top padding from the block content. I have filed a small PR that does only that exactly: https://github.com/backdrop/backdrop/pull/2438

**Comment by klonos** [comment]
...before:

<img width="1139" alt="screen shot 2018-12-31 at 12 33 44 pm" src="https://user-images.githubusercontent.com/2423362/50558619-8851dd80-0cf8-11e9-9e5e-f7a25b703443.png">

...after:

<img width="1168" alt="screen shot 2018-12-31 at 12 33 35 pm" src="https://user-images.githubusercontent.com/2423362/50558624-8f78eb80-0cf8-11e9-9c79-696969d26ea5.png">

**Comment by jenlampton** [comment]
> The only thing I have found that is required when using the classes directly in the block configuration dialog, is some CSS to remove some extraneous top padding from the block content. I have filed a small PR that does only that exactly: backdrop/backdrop#2438

We should not be filing PRs against core for specific use-cases. The CSS change can be made by the person who needs to add the message - on their own site, or, they can change the markup (remove the inner div, or remove/change/add the classes on it) so the existing core CSS does not apply.

**Comment by klonos** [comment]
@jenlampton these types of messages are to also be used in both the admin theme and/or Basis too.

This feature request was meant to help site builders, which could be lego-builder style people, perhaps with no theming skills. Your suggestions assume that a) they know which classes they need to use in order to style text blocks as messages, b) that they will be building a custom frontend theme and/or admin theme.

My use case on the other hand was this:

As a site builder, I need an easy way to add messages to various places on the site, be it in the frontend (to be viewed by site visitors - perhaps also scheduled via https://github.com/backdrop-contrib/block_scheduler), or the backend (to be viewed by content editors). I do not want to create a new theme in order to be able to do that; just use Basis with its new color module support, and Seven.

I don't want to have to tell this group of people that then need to go and learn how to (sub)theme and learn CSS in order to achieve that.

**Comment by jenlampton** [comment]
Your use case is still not 80%.

I could pick any other feature less than 1% of sites would need, and file
similar PRs, and we'd end up with a really bloated and hard to maintain
piece of software. What you want to achieve is already possible with CSS
and markup changes only, which is easier than many other possible features
I could dream up.

A site builder who didn't know CSS could ask in the forum and get help, or
install this contrib module ;) .

We can't support every theoretical use of Backdrop in core. This is what
contrib / custom modules / themes are for.

**Comment by olafgrabienski** [comment]
As stated at beginning of the discussion, I use blocks with `messages` styling quite often. While I still think it would be great to do so using a setting in the UI, I agree that this would be a good contrib candidate.

**Comment by BWPanda** [comment]
Based on discussion and lack of recent activity, closing in favour of contributed option.

**Comment by klonos** [comment]
Agreed. I have claimed the namespace: https://github.com/backdrop-contrib/custom_message_blocks

**Comment by olafgrabienski** [comment]
@klonos Great, looking forward to your first contributed module!

Regarding the namespace `custom_message_blocks`, I was recently thinking about the `custom` part which has two meanings: (1) allowing to customize something like your module will do, but also (2) "custom" vs. "contrib", as in "custom module".  To me, `custom` in a module name sounds ambiguous. Why not name it "Message Blocks"?

**Comment by klonos** [comment]
Thanks for the recommendation @olafgrabienski ...I guess I was thinking `custom blocks` + `messages` -> `custom message blocks`, but you are right; plus I like the shorter version 🙂 ...I've renamed the repo: https://github.com/backdrop-contrib/message_blocks 😉
