### ISSUE TITLE
[UX] Permissions page: Use darker gray background for module-grouping rows.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3412]
Our admin table rows usually have an alternating white/gray background (often called "zebra stripping"), but there are some tables that need to visually group certain rows together. In such cases, we give the grouping rows a darker gray color. These rows visually resemble table headers, but contrary to the actual table headers, they are not sticky. Some examples are, the "Customised for..." row in the display modes listing page for content types:

![screen shot 2018-12-09 at 1 59 15 am](https://user-images.githubusercontent.com/2423362/49691968-ec004500-fb56-11e8-8624-39861df797a2.png)

...and the layout grouping rows in the layout listing page:

![screen shot 2018-12-09 at 2 01 16 am](https://user-images.githubusercontent.com/2423362/49691972-16520280-fb57-11e8-99a4-44a2ea94a3f9.png)

For consistency, and for better UX, we should be doing the same in the permissions page.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2410

**Comment by stpaultim** [comment]
I checked the sandbox and compared it one of my current sites using v. 1.11.2. 

The change looks great and I'm supportive. How else can I be helpful.

**Comment by klonos** [comment]
That's all that was needed @stpaultim 👍 😄 

...I am marking this issue as RTBC, based on Tim's review and the fact that this is a one-line CSS change that simply changes the background color for this specific table.

**Comment by olafgrabienski** [comment]
@klonos Great improvement, and the one-line change looks also good! The php53 test is "pending" but I guess that's not related to the change.

**Comment by klonos** [comment]
Yeah @olafgrabienski I randomly get these situations where either the php53 or the php70 test seems to get stuck (see https://github.com/backdrop-ops/backdropcms.org/issues/276). I have restarted the tests, and they are now green.

PS: thanks @Gormartsen for very promptly fixing that temporary hiccup with the tests 👍 🙏

**Comment by quicksketch** [comment]
Looks good. Those two different grays have different "warmth" to them, as Seven is slightly warm (reddish) while core styles are completely neutral. The fix looks good though, as it adds a core style. If we want to fix the gray differences, we should make another PR for Seven that adjusts the darker grays into a warmer version.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2410 into 1.x and 1.11.x. Thanks @klonos, @olafgrabienski, and @stpaultim!
