### ISSUE TITLE
[UX] Change the wording of Maintenance Mode message from "Go online" to something better.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#3418]
I'm going to be naughty and open a ticket on this little thing I ran into tonight, since we're working on the UX of the maintenance page. 

I was asked to comment on a issue improving the UX of the Maintenance Mode page (https://github.com/backdrop/backdrop-issues/issues/3313). In doing so, I put the site in Maintenance mode and saw the message "The site is currently in maintenance mode. Go online" everywhere. I assumed this was part of the problem, since the words "go online" meant nothing to me. I was online already. 

@jenlampton made a similar observation in this issue: https://github.com/backdrop/backdrop-issues/issues/2583

**Describe the solution you'd like**

I would change the words "go online" to something like any of the following:

- "Change status"
- "Make site live"
- "Undo maintenance mode"
- "Turn off"

Or remove the words "go online" and link the words "maintenance mode" to the maintenance mode page. This actually makes sense, because the link is taking to you to place, not doing something for you. Almost anything would be better than the useless instructions "go online."

NOTE: I see that this wording has carried over from Drupal 7. I wonder how far back these words go?

**Additional information**

![content___backdrop](https://user-images.githubusercontent.com/3144571/49784933-70cc9980-fce4-11e8-9b7d-a6ef15ced68f.png)

**Comment by klonos** [comment]
Thanks for filing this issue @stpaultim 👍 

> Or remove the words "go online" and link the words "maintenance mode" to the maintenance mode page.

I like that too ^^. As part of #2583, we are embedding the "Use the site in maintenance mode" permission in the form, so there is more to it than just "Going online".

**Comment by stpaultim** [comment]
Just noticing that the "go online" link in the message contains destination information. Not sure if that effects the final solution.
<a href="/admin/config/development/maintenance?destination=admin/content">Go online.</a>

If we remove the "go online" link and just make the words "maintenance mode" into a link to maintenance mode page, do we still want to redirect the user back to where they were before they clicked on the link?

**Comment by stpaultim** [comment]
Marking this as a good first issue, I expect it is. For a new contributor interested in this issue, I recommend choosing the alternative wording that you like best. Once we actually have a PR, we're likely to get more feedback on the final wording and other suggestions.

**Comment by philsward** [comment]
+1 for "Go Live"

**Comment by klonos** [comment]
I find "Go live" equally inadequate/odd as "Go online". I'd rather this instead:

> Maintenance mode is currently enabled for this site. [Disable it](url).

or:

> Maintenance mode is currently turned on for this site. [Turn it off](url).

**Comment by jenlampton** [comment]
What about just "Disable Maintenance Mode"?

**Comment by philsward** [comment]
These are just as odd

> Maintenance mode is currently enabled for this site. Disable it.

> Maintenance mode is currently turned on for this site. Turn it off. (better, but still odd)

> What about just "Disable Maintenance Mode"?

I personally hate the "sentences" that are are becoming all-too common among CTAs in BD. If the UI isn't intuitive enough for someone to figure out what is going to happen if they click on a CTA, then the UI needs to be changed to address the UX, not the text of the CTA button.

If we're going to go down this road, I would like to see what is being used as the link, converted to an actual action. "Go Live" or whatever should be the thing that takes you out of maintenance mode, not the thing that takes you somewhere else to click two more times just to get out of maintenance mode. "Are you REALLY REALLY sure you want to exit Maintenance mode??" "Um... I wouldn't have clicked you if I wasn't ready...?" Pair this with a new status message on page reload that says "Your site is now live. Not what you wanted? [Undo Live]"

To be fair, "Go online" is probably good enough and descriptive enough for 90% of the people out there. It may not make sense at first to someone new, but the link creates a CTA which leads to another page that is inherently intuitive enough to understand what needs to happen next; it just creates a lot of unnecessary hoops to jump through.

In the end, I would rather see the entire "maintenance mode" added to the admin menu with a "Live" or "Maintenance" indicator (Icon and color change?) and clicking on the indicator would switch between the two modes. Remove the checkbox that is on the maintenance admin page and just leave the custom textbox for a custom message. Going in and out of maintenance mode shouldn't take 3 clicks and it would make it that much easier for the end-user who isn't a site builder to move their site from live to maintenance.

I'm honestly not sure why I'm even commenting. I think I've put my various combined sites into maintenance mode maybe 5-10 times in the last 15 years. I might use it more if it were more readily available. A good candidate for Telemetry?

**Comment by klonos** [comment]
> Remove the checkbox that is on the maintenance admin page and just leave the custom textbox for a custom message. Going in and out of maintenance mode shouldn't take 3 clicks and it would make it that much easier for the end-user who isn't a site builder to move their site from live to maintenance.

@philsward have you seen #2583. I think you should chime in there with what you'd think would be a better option.

**Comment by philsward** [comment]
Thanks @klonos 

Updated my previous comment to yank out the pieces that are more appropriate in the issue you suggested.

**Comment by BWPanda** [comment]
Since the link doesn't take you live/online (you just go to a page where you can enable/disable maintenance mode and change the text on the maintenance page), I like the option of making 'maintenance mode' the link to that page.

**Comment by BWPanda** [comment]
This is how the message is currently set:

```php
$message = t('The site is currently in maintenance mode.');
if (user_access('administer site configuration')) {
  $message .= ' ' . l(t('Go online.'), 'admin/config/development/maintenance', array('query' => backdrop_get_destination()));
}
```

The regular message is set, then (if the user has access) the link is appended to it.

But how would we do this if we wanted the text 'maintenance mode' to be the link? Do we:
1. Add the link regardless and users without access will just get an 'Access denied' page?
2. Set two messages - one without the link and one with it (the latter overriding the former)? E.g.:

```php
$message = t('The site is currently in maintenance mode.');
if (user_access('administer site configuration')) {
  $message = t('The site is currently in <a href="@maintenance-url">maintenance mode</a>.', array(
    '@maintenance-url' => url('admin/config/development/maintenance'),
  ));
}
```

**Comment by indigoxela** [comment]
> Do we ... Add the link regardless

I'm not aware of any example we do that. And if someone finds it, it would be worth a bugfix. :smirk:

Of course, we don't send people to "403". You'll very likely need conditional messages (as a whole).

**Comment by BWPanda** [comment]
Thanks @indigoxela, here's a PR: https://github.com/backdrop/backdrop/pull/4120

![image](https://user-images.githubusercontent.com/2385329/176983430-62057c6c-4731-4b97-98a6-4078ccd40c3a.png)

The link goes to the maintenance mode page, but without a destination set, since we don't add destinations to all links on the site. People might click the link just to see what it means, or to see what the current maintenance mode message is, without wanting to actually take the site out of maintenance mode.

**Comment by indigoxela** [comment]
> The link goes to the maintenance mode page, but without a destination set,

@BWPanda if you remove the destination, the comment right above might need some update, too.

**Comment by BWPanda** [comment]
Thanks, PR updated.

**Comment by indigoxela** [comment]
> PR updated.

Thanks, looks great now.

@stpaultim does this PR address what you requested?

**Comment by stpaultim** [comment]
Just discovered that there is a PR for this issue. Putting on my list to test and review ASAP.

**Comment by klonos** [comment]
> The link goes to the maintenance mode page, but without a destination set, since we don't add destinations to all links on the site. People might click the link just to see what it means, or to see what the current maintenance mode message is, without wanting to actually take the site out of maintenance mode.

Yeah, and with the recent addition of the "back to site" link in the admin bar, this is really not necessary 😉 

The PR needs a rebase + fixing the failing tests (seems like a simple fix to the string that the test expects). So setting this to NW for that.

**Comment by stpaultim** [comment]
I created a new PR based 100% on Peter's work and tried to fix at least one test.

**Comment by stpaultim** [comment]
Seems that tests are passing. This is a pretty simple issue that has been open for a long time. 

@klonos, @indigoxela, @BWPanda, @jenlampton - Any thoughts?

**Comment by yorkshire-pudding** [comment]
Tested sandbox and reviewed code. All looks good to me.

**Comment by quicksketch** [comment]
This simple change looks good to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4598 into 1.x and 1.26.x. Thanks everyone!
