### ISSUE TITLE
[UX][D8] Allow 'Content: Link' views field to just output URL

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3419]
Often when creating a view that requires a URL to the content (e.g. for adding to the 'Output this field as a link' setting on other fields), I'll add the 'Content: Link' field, forgetting that this is meant to display an actual link (e.g. 'View more') as opposed to outputting just the URL/path that I can use elsewhere. I need to add the separate 'Content: Path' field instead.

It'd be nice if we merged these two very similar fields into one, by adding an option to the 'Content: Link' field for outputting just the URL (and therefore hiding the 'Text to display' setting).

Drupal 8 does this nicely:
![screenshot_2018-12-11](https://user-images.githubusercontent.com/2385329/49787541-a480e100-fd2f-11e8-9cc8-ae758e832cc5.png)

- - - - - - - 

PR by @BWPanda: https://github.com/backdrop/backdrop/pull/3223

**Comment by BWPanda** [comment]
And here's D8 without that box checked (showing the 'Text to display' setting):
![screenshot_2018-12-11_2](https://user-images.githubusercontent.com/2385329/49787719-178a5780-fd30-11e8-8fae-b685d991526c.png)

**Comment by BWPanda** [comment]
As an extra feature request, and slightly different from Drupal 8, what about also merging all the link fields together? E.g. remove 'Content: Delete link' and 'Content: Edit link' in favour of a more powerful 'Content: Link'.

Here's how it could look:
![screenshot_2018-12-14 administer content content panda s backdrop sandbox 1](https://user-images.githubusercontent.com/2385329/49997384-1bb9ad80-ff9a-11e8-803b-167b5cf3deb5.png)
(I couldn't screenshot the select list open, but it'd have 'View', 'Edit', & 'Delete' as options.)

Also the 'absolute' option from D8 would be handy.

**Comment by docwilmot** [comment]
I think this issue was a good idea with just the original thought. But the merged link types make it more complicated. Which would mean tests and upgrade paths. Should this be rolled back to just outputting a link?

**Comment by jenlampton** [comment]
> Should this be rolled back to just outputting a link?

I think that would be a good first step. We can create a separate issue for @BWPanda's suggestion, and add tests for that issue separately.

**Comment by jenlampton** [comment]
@klonos didn't add a comment about why he added the 1.12 milestone, perhaps a mistake? Removing, since we don't have a working PR in scope.

**Comment by jenlampton** [comment]
removing `[D8 feature parity]` from title, adding `[D8]` for brevity, adding into project.

**Comment by BWPanda** [comment]
Ok, reworked the [PR](https://github.com/backdrop/backdrop/pull/2425) to just change the Link field (not the others).

**Comment by klonos** [comment]
Simple yet useful change. Thanks @BWPanda 👍 

I've left a comment in the PR re the order of form elements + tests are failing.

**Comment by BWPanda** [comment]
Here's a new, updated PR that hopefully fixes tests and addresses @klonos suggestion: https://github.com/backdrop/backdrop/pull/3223

**Comment by stpaultim** [comment]
The sandbox for this one also seems broken, but in a different way. It's asking me to go through the install process. That's not right, is it? @BWPanda

**Comment by BWPanda** [comment]
@stpaultim Try again now?

**Comment by BWPanda** [comment]
I've updated the PR with the latest core changes, which now includes a Tugboat preview.

**Comment by indigoxela** [comment]
@BWPanda many thanks for reviving this issue.

Yes, that we currently have to use the "path" to get the full url is one of those hidden features in views. And for sure confusing for newbies. The PR now provides the url in both, the path and the link field.
That *could* potentially be confusing, but having url as an option in both fields doesn't hurt IMO. And a lot of people would probably search in the "link" field first.

Works for me.

**Comment by stpaultim** [comment]
I'd like some more precise steps to find and test this change.

**Comment by stpaultim** [comment]
This issue has a PR and is marked "Works for Me". It just needs a code review, but is not on the milestone. Is this still a candidate for 1.21.0? Should it be?

**Comment by stpaultim** [comment]
> I'd like some more precise steps to find and test this change.

I dug a little deeper and figured this one out (it wasn't that hard). 

To recreate or test this issue, create a view of all content displaying an unformatted list of fields.

BEFORE:

![image](https://user-images.githubusercontent.com/3144571/147975103-f87bfb2d-266a-4923-9afd-55cfde6d75eb.png)

AFTER:

![image](https://user-images.githubusercontent.com/3144571/147975212-e6dfc8d3-6ac3-4a33-ac06-fee80c1707e3.png)

SAMPLE VIEW:

![image](https://user-images.githubusercontent.com/3144571/147975328-63c0dbb0-640b-4dbc-aa74-49bbc93a3390.png)

RESULTS:

![image](https://user-images.githubusercontent.com/3144571/147975279-173978e9-bc37-4f2b-b917-311f6b8976ab.png)

**Comment by jenlampton** [comment]
Hm, after seeing tim's screenshots, I'm not sure we need either description. I've left some feedback on the PR - technically the code review looks great 👍  but I have a few text suggestions for the interface. (and I think this is still reasonable for 1.21)

**Comment by BWPanda** [comment]
> It just needs a code review, but is not on the milestone. Is this still a candidate for 1.21.0? Should it be?

@stpaultim Without an advocate, this issue can't be added to the 1.21 milestone until it's RTBC: https://backdropcms.org/user-guide/adding-milestones-to-issues?destination=admin/dashboard

**Comment by stpaultim** [comment]
> Without an advocate, this issue can't be added to the 1.21 milestone until it's RTBC: backdropcms.org/user-guide/adding-milestones-to-issues?destination=admin/dashboard

I understood that. I am just asking if we want to try and get it into 1.21 (even thought it's not on the milestone, yet).

**Comment by BWPanda** [comment]
Updated PR:

![image](https://user-images.githubusercontent.com/2385329/150713687-a095aef4-a32b-4f0d-8f03-c63052e0725a.png)

**Comment by bugfolder** [comment]
Code reviewed. LGTM. (Also tested for myself, and WFM.)

**Comment by quicksketch** [comment]
This is great! I merged https://github.com/backdrop/backdrop/pull/3223 into 1.x for 1.27.0. Great work @BWPanda! Thanks @jenlampton, @stpaultim, @klonos, @indigoxela, and @bugfolder for reviewing and providing feedback!

**Comment by klonos** [comment]
Sorry to reopen this. Small, 3-line follow-up PR to make use of the `#indentation` property in the "Content: Edit link" dialog: https://github.com/backdrop/backdrop/pull/4573

Before/after screenshot:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/2c94e3ac-331c-42d5-83c0-69af64704486)

**Comment by quicksketch** [comment]
Thanks @klonos! I merged it into 1.x as well. Thanks!
