### ISSUE TITLE
[UX] Fix RTL Autocomplete style

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3421]
Fix RTL Autocomplete style
befor and after
![untitled](https://user-images.githubusercontent.com/45591694/49826243-851d9e80-fd97-11e8-8826-b8d075225415.gif)
just add after 
`.js input.form-autocomplete {
  background-position: 98% center;
}`
this 
`.js[dir="rtl"] input.form-autocomplete {
  background-position: 1% center;
}`
in core/themes/seven/css/style.css

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2416

**Comment by klonos** [comment]
PR up for review:

<img width="806" alt="screen shot 2018-12-12 at 5 19 17 am" src="https://user-images.githubusercontent.com/2423362/49844998-908bbc80-fdcd-11e8-96d5-7616d6a27417.png">
