### ISSUE TITLE
[UX] FIX RTL width page add content

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3423]
here fix width in page add content with RTL
![untitled](https://user-images.githubusercontent.com/45591694/49861571-2f83d900-fe0d-11e8-90a1-e465e34ca12f.gif)
just delete 
`[dir="rtl"] fieldset {
    padding: 2.5em 0 0;
}`
file = core/themes/seven/css/style.css
with Responsive 
![untitled-1](https://user-images.githubusercontent.com/45591694/49867643-25b5a200-fe1c-11e8-8fa9-4a62da810138.gif)

---
PR by @klonos (but all credits should go to @shabibalm): https://github.com/backdrop/backdrop/pull/2489

**Comment by quicksketch** [comment]
Agreed, thanks @shabibalm for all these excellent reports and solutions! Merged https://github.com/backdrop/backdrop/pull/2489 into 1.x and 1.12.x. Thanks @klonos and @opi for tag-teaming these RTL issues.

**Comment by shabibalm** [comment]
same problem backdrop 1.15.0

**Comment by stpaultim** [comment]
@shabibalm - are you saying that this problem was fixed in 1.14, but that backdrop 1.15 broke it again? 
Did you experience this problem when upgrading an 1.14 site to 1.15 or on new sites? 
Or both?

**Comment by shabibalm** [comment]
@stpaultim yes backdrop 1.15.0 again same problem just upgrading an 1.14 site to 1.15 
new install backdrop 1.15 no problem
