### ISSUE TITLE
[UX] FIX RTL vertical tabs style

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3424]
fix vertical tabs with RTL
![fix-rtl-vertical tabs](https://user-images.githubusercontent.com/45591694/49868410-68787980-fe1e-11e8-9340-fba44d83f01a.jpg)
add in core/themes/seven/css/vertical-tabs.css
`  [dir="rtl"] .vertical-tabs:before {
    right: 0;
  }`
second problem
![fix-rtl-vertical tabs-2](https://user-images.githubusercontent.com/45591694/49868772-78448d80-fe1f-11e8-996e-83cc85557b67.jpg)
edit core/themes/seven/css/vertical-tabs.css
change 
`[dir="rtl"] .vertical-tabs-list {
    margin-left: 0;
    margin-right: -15em;
    float: right;
  }`
to 
`[dir="rtl"] .vertical-tabs-list {
	margin-left: 0;
	margin-right: -15em;
	float: right;
	margin-top: 0;
	border-top: none;
}`
![vertical-tabs-backdropcms-rtl](https://user-images.githubusercontent.com/45591694/49869023-310acc80-fe20-11e8-80e4-40e94d7d0218.gif)

---
PR by @klonos (but all credits should go to @shabibalm): https://github.com/backdrop/backdrop/pull/2488

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/2488

Thanks @shabibalm 👍

**Comment by opi** [comment]
vertical tabs looks better with this PR !

**Comment by quicksketch** [comment]
I posted a few questions on the PR: https://github.com/backdrop/backdrop/pull/2488#pullrequestreview-201810918

**Comment by klonos** [comment]
...moved things around and fixed a few more things in that file, including comments and wrong indentations.

Ready for review again.

**Comment by jenlampton** [comment]
Looks good to me.

**Comment by quicksketch** [comment]
Great, merged into 1.x and 1.12.x.
