### ISSUE TITLE
Seven: disabled buttons are not styled as disabled

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3425]
**Describe the bug**
I can across this problem while working on #2461...

**Steps To Reproduce**
When programmatically setting a form button to be disabled (when using `#states` for example), the `disabled` property and the `form-disabled` class are properly added to the input element, but the element is not styled as disabled.

To reproduce:

1. navigate to `/admin/structure/types/add`
2. inspect the submit buttons with your browser dev tools, and change the code to this (to invoke a disabled state):

```html
<div class="form-actions" id="edit-actions">
  <input class="button-primary form-submit form-disabled" type="submit" id="edit-save-continue" name="op" value="Save and add fields" disabled>
  <input class="button-secondary form-submit form-disabled" type="submit" id="edit-submit" name="op" value="Save content type" disabled>
  <a href="/admin/structure/types" class="form-cancel" id="edit-cancel">Cancel</a>
</div>
```

**Actual behavior**

The buttons are disabled (clicking them does nothing), but they are not styled as such:

<img width="578" alt="screen shot 2018-12-12 at 4 23 00 pm" src="https://user-images.githubusercontent.com/2423362/49875666-3bca5f00-fe2a-11e8-9379-1b98974640e4.png">

**Expected behavior**

<img width="599" alt="screen shot 2018-12-12 at 4 17 27 pm" src="https://user-images.githubusercontent.com/2423362/49875604-0faede00-fe2a-11e8-8d39-73fcbbae824a.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2419

**Comment by klonos** [comment]
...thanks, but what you proposed did not exactly work @quicksketch. Moving the selectors a bit further down did the trick though 😉 I have updated the PR.

**Comment by quicksketch** [comment]
Looks great, thanks @klonos! Merged https://github.com/backdrop/backdrop/pull/2419 into 1.x and 1.12.x.
