### ISSUE TITLE
SA-CORE-2014-003 - Drupal core - Multiple vulnerabilities

### ISSUE THREAD

**Issue by tarekdj** [backdrop/backdrop-issues#343]
Drupal 7.29 release notes: 
https://www.drupal.org/drupal-7.29-release-notes

https://www.drupal.org/SA-CORE-2014-003

**Comment by quicksketch** [comment]
Double-checked:

- [x] Denial of service with malicious HTTP Host header (Base system - Drupal 6 and 7 - Critical)
- [x] Access bypass (File module - Drupal 7 - Critical)
- [x] Cross-site scripting (Form API option groups - Drupal 6 and 7 - Moderately critical)
- [x] Cross-site scripting (Ajax system - Drupal 7 - Moderately critical)
