### ISSUE TITLE
Views: messages within dialogs do not have any padding

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3430]
**Describe the bug**
This is slightly related to #2696 in that they both make the views dialogs seem neglected/afterthoughts when it comes to UX. Although this is more of a bad-first-impression thing rather than a UX issue.

**Steps To Reproduce**

1. Set the site in maintenance mode.
2. Intentionally install a module with a security release available 
3. Edit a view and configure any option that opens in a dialog...

**Actual behavior**

<img width="679" alt="screen shot 2018-12-15 at 4 49 54 pm" src="https://user-images.githubusercontent.com/2423362/50044408-ab8b5480-008b-11e9-8b63-1ea83f8697c2.png">

**Expected behavior**

<img width="691" alt="screen shot 2018-12-15 at 5 05 31 pm" src="https://user-images.githubusercontent.com/2423362/50044410-b0e89f00-008b-11e9-8ce8-8ecdd24d23af.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2422

**Comment by klonos** [comment]
...PR up for review. It also works well even when the [`max-height: 200px;`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views_ui/css/views_ui.admin.css#L353) kicks in:

<img width="774" alt="screen shot 2018-12-15 at 5 09 23 pm" src="https://user-images.githubusercontent.com/2423362/50044479-97942280-008c-11e9-8fe8-5280940bcc6f.png">

**Comment by opi** [comment]
agreed !

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.11.x.
