### ISSUE TITLE
[UX] FIX RTL ui datepicker

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3434]
problem ui-datepicker with rtl
![ui-datepicker-div-rtl](https://user-images.githubusercontent.com/45591694/50139674-647fa800-02b3-11e9-9736-28108919dc61.jpg)

add 
```
[dir="rtl"] .ui-datepicker {
	width: auto;
}
```

add
```
[dir="rtl"] .ui-datepicker .ui-datepicker-next {
	right: auto;
	top: 4px;
}
```

in core/themes/seven/css/style.css 
![ui-datepicker-div-fix-rtl](https://user-images.githubusercontent.com/45591694/50140300-529f0480-02b5-11e9-9fbe-24815b7b73cd.jpg)

---
PR: https://github.com/backdrop/backdrop/pull/2473

**Comment by jenlampton** [comment]
I've filed a PR at https://github.com/backdrop/backdrop/pull/2473 
Would someone please give this a review for me?

**Comment by findlabnet** [comment]
Datepicker is fixed.

**Comment by quicksketch** [comment]
Thanks @shabibalm for the fixes! Thanks @jenlampton and @findlabnet for making/reviewing the PR. Merged https://github.com/backdrop/backdrop/pull/2473 into 1.x and 1.11.x.
