### ISSUE TITLE
[UX] FIX RTL Formatting options theme basis

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3435]
problem Formatting options form comment
![fix-rtl-formatting-options-theme-basis](https://user-images.githubusercontent.com/45591694/50164019-b267d080-02f2-11e9-8cb2-ddc221bf405c.jpg)

edit core/themes/basis/css/component/fieldset.css
add 
```
.js[dir="rtl"] fieldset.collapsible .fieldset-title {
  padding: 0.3em 1.8em 0.3em 0.3em;
}
```

and add 
```
.js[dir="rtl"] fieldset.collapsed .fieldset-legend a:before {
  -webkit-transform:
    translate(0, 0.125em)
    rotate(90deg);
  transform:
    translate(0, 0.125em)
    rotate(90deg);
}
```
and add 
```
.js[dir="rtl"] fieldset.collapsible .fieldset-legend a:before {
	right: 0.6em;
}
```

---
PR: https://github.com/backdrop/backdrop/pull/2472

**Comment by jenlampton** [comment]
I've created a PR for testing this solution, if someone else could give it a try? 
https://github.com/backdrop/backdrop/pull/2472

**Comment by findlabnet** [comment]
Bug fixed in PR.

**Comment by quicksketch** [comment]
Thanks @shabibalm, @jenlampton, and @findlabnet! Merged https://github.com/backdrop/backdrop/pull/2472 into 1.x and 1.11.x.
