### ISSUE TITLE
[UX] Add dropzone.js in core and use it for image/file fields (to enable bulk uploading).

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3436]
**Is your feature request related to a problem? Please describe.**
This is related to #3297 and #3203...

Here's what we currently have in place:

<img width="480" alt="screen shot 2018-12-20 at 4 42 17 pm" src="https://user-images.githubusercontent.com/2423362/50291150-6c3b7a00-0476-11e9-976c-7327adc55ee3.png">

...when there is need to upload multiple files, the task becomes very tedious, as the user needs to repeatedly click the "Choose file" button:

<img width="1185" alt="screen shot 2018-12-20 at 4 42 50 pm" src="https://user-images.githubusercontent.com/2423362/50291177-82493a80-0476-11e9-8114-25b45487d9cf.png">

**Describe the solution you'd like**

We will improve things a great deal when #3297 is implemented, but that will work for selecting already uploaded files. For uploading new files, things would ideally look something like this:

<img width="786" alt="screen shot 2018-07-20 at 8 15 08 am" src="https://user-images.githubusercontent.com/2423362/42977268-8b9bed34-8c09-11e8-90ce-f809fc1d7538.png">

<img width="751" alt="screen shot 2018-12-20 at 6 12 21 pm" src="https://user-images.githubusercontent.com/2423362/50296286-d9eda300-0482-11e9-9b2c-6085e6644e32.png">

**Comment by findlabnet** [comment]
Please note: any upload related feature should be carefully checked (and then continuously maintained) for security leaks.

**Comment by olafgrabienski** [comment]
For reference: maybe also a duplicate of #440.
