### ISSUE TITLE
Remove the 16px message icons from the core/misc directory

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3437]
We have a lot of duplicate icons in the misc directory. 

It looks like we can remove the 16px ones by adding a `background-size` property to the `dblog.css` file.  See https://github.com/backdrop/backdrop/pull/2426 

This change will affect only the dblog at 'admin/reports/dblog'

---
PR: https://github.com/backdrop/backdrop/pull/2426

**Comment by klonos** [comment]
RTBC 👍

**Comment by quicksketch** [comment]
A few issues on the PR: 

- The `info` status message icon was accidentally removed.
- We should stick to `em` units to match the rest of Basis.

**Comment by jenlampton** [comment]
> The info status message icon was accidentally removed.

No, it wasn't. It was moved to line 71.

> We should stick to em units to match the rest of Basis. 

The change here is to a core CSS files `core/modules/dblog/css/dblog.css`, not to Basis.

**Comment by quicksketch** [comment]
Thanks, you're right! Merged https://github.com/backdrop/backdrop/pull/2426 into 1.x for 1.12.0. As this isn't a bug fix, I've left it out of the 1.11.x branch.
