### ISSUE TITLE
Some file.module files dont appear in the API list

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#3439]
**Describe the bug**
This is the list of functions in `file.module`:
![file-module-funcs](https://user-images.githubusercontent.com/1042283/50340449-03d9b080-04e9-11e9-855c-fab3245c604e.PNG)

This is the list on the API site:
```
file_action_info
file_ajax_upload
file_autoload_info
file_element_info
file_entity_info
file_file_download
file_menu
file_permission
file_theme
file_views_api
```
**Steps To Reproduce**
Compare: https://api.backdropcms.org/api/backdrop/core%21modules%21file%21file.module/1
With: https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/file.module

**Actual behavior**
Some functions are missing from the API list, including for example `file_managed_file_value()`

**Expected behavior**
All functions should be listed on the API site

**Comment by docwilmot** [comment]
Maybe this should be expanded to be an issue about the API site's parsing generally. `backdrop_autoload()` and quite a few other functions don't show up either. Interestingly if you google `backdrop_autoload()` you get a hit on the API site (https://www.google.com/search?q=backdrop_autoload) but when you click said link, you get "page not found". (Does this impact SEO byt the way?)

**Comment by docwilmot** [comment]
Actually there is s specific problem with `bootstrap.inc`. https://github.com/backdrop-ops/api.backdropcms.org/issues/55

**Comment by quicksketch** [comment]
This should be fixed now that https://github.com/backdrop-ops/api.backdropcms.org/issues/55 is corrected.

**Comment by herbdool** [comment]
I checked some of the functions above and they now appear in the api site. I think we can close this.
