### ISSUE TITLE
[D8 feature parity][DX] Form API submit button property and CSS classes to denote the primary button in a form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3440]
This is the respective issue for https://www.drupal.org/project/drupal/issues/1238484 ([Change record](https://www.drupal.org/node/1848288))

> **Description**: 
> Previously, all submit buttons in a form were treated of equal **importance** and **implications**.
> 
> Drupal 8 provides a new Form API property for submit buttons and corresponding CSS classes, as well as CSS styles (in core themes) to visually denote the primary form submit button (e.g., "Save") and buttons that have destructive implications (e.g., "Delete").
> 
> Read http://www.lukew.com/resources/articles/PSactions.asp to learn about the visual interface concept.
> 
> For a wider range of sophisticated examples of this concept, have a look at [Bootstrap's button styles](http://twitter.github.com/bootstrap/base-css.html#buttons).
> 
> **Drupal 7**
> Drupal 7 does not have this concept. However, Drupal 7 previously used the `#button_type` property as an internal Form API property to control the form submission process.
> 
> **Drupal 8**
> The internal `#button_type` Form API property has been renamed to `#is_button`. Since this was an internal property, no code should be affected.
> 
> The new `#button_type` property for submit buttons allows to specify a string value, which should map to one of the button types of this concept, and which is automatically translated into a corresponding CSS class on the button on output.
> 
> **Usage**:
> ```php
> $form['actions']['submit'] = array(
>   '#type' => 'submit',
>   '#value' => t('Save'),
>   '#button_type' => 'primary',
> );
> $form['actions']['preview'] = array(
>   '#type' => 'submit',
>   '#value' => t('Preview'),
> );
> $form['actions']['delete'] = array(
>   '#type' => 'submit',
>   '#value' => t('Delete'),
>   '#button_type' => 'danger',
> );
> ```
> 
> It will result like this (standard/mobile):
> 
> ![image](https://user-images.githubusercontent.com/2423362/50369693-385d7300-05a2-11e9-9bf8-694751a4be5a.png)
> 
> ![image](https://user-images.githubusercontent.com/2423362/50369694-3eebea80-05a2-11e9-8698-09714d52f162.png)
> 
> **Interface Guidelines**
> 1. Not every form has to have a primary submit button.
> 
> 1. A button should only be marked as primary if it truly completes the form submission.
> 
>     I.e., the "Save" button can be primary, but do not make the "Preview" button primary.
> 
> 1. If there is no clear primary button in a form, do not mark any button as primary.
> 
> 1. Submit buttons in filter forms, search sidebar forms, etc. should not be marked as primary button, since they are not part of the main page interaction.
> 
> 1. Any kind of destructive button (e.g., "Delete") should NEVER be marked as primary button (even when it is the primary button).
> 
> 1. Only mark a destructive button with "danger" if it appears as an alternative option within a set of other buttons.

**Comment by jenlampton** [comment]
@klonos we already have this in Backdrop. 

We use CSS classes rather than another form API attribute, since most devs will already know how to add `['#attribute']['class']` on other things.  The first button on a Backdrop form is always `button-primary`, unless otherwise specified. Classes like `button-danger` need to be added by the module maintainer.
