### ISSUE TITLE
Project Installer: wording: "relevancy" vs "relevance"

### ISSUE THREAD

**Issue by quinnanya** [backdrop/backdrop-issues#3442]
On the module installation search page (/admin/modules/install), the default sort order when you search is "relevancy". Could the wording in English be adjusted to "relevance"? (See usage note here that "relevance" is 20x more commonly used in the US and 50x in the UK: https://en.wiktionary.org/wiki/relevancy.)

Sorry, I know it's a tiny and picky issue, but I work with humanities scholars who notice things like that. Thanks!

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2433

**Comment by klonos** [comment]
I personally don't mind either way, but the internet has spoken 😄 ...a few more resources on the matter:

https://english.stackexchange.com/questions/230461/can-someone-explain-when-to-use-relevance-and-when-relevancy

> Relevance is the more common form, according to grammarist.com:
> 
> [Relevance vs. relevancy](http://grammarist.com/usage/relevance-relevancy/):
> 
>> There is no difference between relevance and relevancy. Though the latter is the older form, relevance is now preferred in all varieties of English. In this century, relevance is about ten times as common as relevancy in U.S. popular usage, and the gap is even wider in British, Australian, and Canadian sources.
>
> [Ngram](https://books.google.com/ngrams/graph?content=relevance%2C%20relevancy&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Crelevance%3B%2Cc0%3B.t1%3B%2Crelevancy%3B%2Cc0) revevance vs relevancy
> 
>> Etymology:
>>
>> relevance (n.) 1733; see relevant + -ance. Related: Relevancy (1560s).
>
> [-ancy](http://www.etymonline.com/index.php?term=-ancy) (suffix):
> 
>> word-forming element denoting quality or state, from Latin -antia, forming abstract nouns on past participle adjectives in -antem, appearing in English mostly in words borrowed directly from Latin (those passing through French usually have -ance or -ence; see -ance).

**Comment by stpaultim** [comment]
PR does what it is supposed to and even I can tell that the code changes (spelling change) seem appropriate. :-)

But, it's failing a test. I assume that I can't mark it RTBC if it's failing a test.

**Comment by stpaultim** [comment]
Anything I can do to help with this? 
Why are we having problems with TESTS for such a simple change?
(Last batch of tests never finished running).

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2433 into 1.x and 1.11.x. Thanks @quinnanya and @klonos for taking care of this! Sorry for the trouble with testing. Tracking down why we get some of the random failures has been a thorn in our side for months and months. General issue for random failures is https://github.com/backdrop/backdrop-issues/issues/1478, which we still revisit fairly regularly.
