### ISSUE TITLE
"Specified key was too long" error when importing sql dump on server that does not support utf8mb4

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3446]
I installed backdrop on my local machine, then dumped the database so I could import it into a test site on my web host (Dreamhost). The import stopped at creating the table cache_admin_bar with the error "Specified key was too long; max key length is 767 bytes"

full error:
CREATE TABLE IF NOT EXISTS `cache_admin_bar` (
  `cid` varchar(255) NOT NULL DEFAULT '' COMMENT 'Primary Key: Unique cache ID.',
  `data` longblob DEFAULT NULL COMMENT 'A collection of data to cache.',
  `expire` int(11) NOT NULL DEFAULT 0 COMMENT 'A Unix timestamp indicating when the cache entry should expire, or 0 for never.',
  `created` int(11) NOT NULL DEFAULT 0 COMMENT 'A Unix timestamp indicating when the cache entry was created.',
  `serialized` smallint(6) NOT NULL DEFAULT 0 COMMENT 'A flag to indicate whether content is serialized (1) or not (0).',
  PRIMARY KEY (`cid`),
  KEY `expire` (`expire`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='Cache table for Administration bar to store client-side…'

MySQL said: 
#1071 - Specified key was too long; max key length is 767 bytes

There is one row in the table and the values are:
('admin_bar:1:B7_tGG0TzXzjdXwYhaou9poJ62Xtpm7qEZpp9Q7PxOU:en', _binary 0x3431383633383364393262613034623265313764633338396261623139373635, 0, 1546053951, 0);

**Steps To Reproduce**
* Install Backdrop with Apache 2.4.37 / PHP 7.2.1 / MariaDB 10.2.11
* Dump the database
* Import into MySQL 4.8.3

**Actual behavior**
MySQL fatal error

**Expected behavior**
A successful import

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version: 1.11.3
- Web server and its version: 
Source: Apache 2.4.37 (Win64) | PHP 7.2.13
Destination: Apache 2.0 | PHP 7.2.11
- Operating System and its version: 
Source: Windows 10
Destination: Linux Ubuntu ??

**Comment by stpaultim** [comment]
I don't know if it's relevant, but it seems worth linking this issue to the issue with CiviCRM that you recently opened. I assume its the same site?

**Comment by herbdool** [comment]
I recommend making sure the cache tables are empty before exporting.

There are different ways to accomplish it. You could export the structure first and data in a second export that excludes cache_ and session tables. Or use backup_migrate module.

**Comment by herbdool** [comment]
I don't think that issue is related Tim.

**Comment by docwilmot** [comment]
I've had this issue before. It's got nothing to do with cache unfortunately. It required lots of googling and manually fudging with tables and indexes and keys. 
I think in the end it imported via a mysql utility rather than using phpmyadmin, but I don't recall.

**Comment by Radcliffe** [comment]
I've had this problem before. Let me explain what is happening, as I understand it. Your index column cid can have up to 255 characters; but the character encoding "utf8mb4" can use up to four bytes per character. So the index column requires 4 * 255 = 1020 bytes, which exceeds the maximum key length.

One way to solve this problem is to use the "utf8" encoding instead, since this uses at most three bytes to encode a character. I performed a search and replace in the SQL dump, replacing each instance of "utf8mb4" with "utf8". I did this using vim, with the following command.

`:%s/utf8mb4/utf8/g`

If you Google the error message that you received then you will get a variety of conflicting suggestions, but this worked for me.

**Comment by Radcliffe** [comment]
If you use my solution, you should search the SQL dump for the string "utf8mb4" to make sure that all replacements are appropriate.

**Comment by laryn** [comment]
This sounds similar to something I experienced some months back, where the initial install was on a server that supported `utfmb4` but the server that I was importing to did not. Here's my summary (from Gitter):

>  I think I figured it out... edited the SQL file and changed all utf8mb4 to utf8 then reimported; changed it in the settings.php file as well. Apparently this server doesn't support utf8mb4 which was causing some issues. Hoping that was all...

**Comment by klonos** [comment]
> Import into MySQL 4.8.3

As I understand this @foobass this is referring to the db on your destination, where you are trying to import the db dump. Is there any option to use MariaDB on the destination as well?

**Comment by oadaeh** [comment]
This is not due to a bug in Backdrop, so I removed the label.

**Comment by herbdool** [comment]
This doesn't sound like there's anything else to do here so I'll close this issue.
