### ISSUE TITLE
Core Updates failing due to missing module 'type' in *.tests.info file

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#3447]
**Describe the bug**
In issue - https://github.com/backdrop/backdrop-issues/issues/3433, I have been trying to get Core Updates working locally using a fresh Lando installation without success. 

It turns out that I'm getting an error even when enabling core updates manually and before applying the patch in issue - https://github.com/backdrop/backdrop-issues/issues/3271

I'm opening this new issue, because this seems to be a bug in the original PR added to v 1.11.0 - https://github.com/backdrop/backdrop-issues/issues/3105

I'm not sure what the bug was, but I reported it and @serundeputy was able to reproduce it and wrote a PR for it: https://github.com/backdrop/backdrop/pull/2431 (but, I don't think there is any other issue for this PR yet). 

I've tested this PR and I am still unable to get updates working. 

**Steps To Reproduce**

1) Setup environment with Lando

* git clone git@github.com:backdrop/backdrop.git bd-updates
* cd bd-updates
* git checkout 1.11.0
* wget https://github.com/backdrop/backdrop/pull/2431.patch
* git apply 2431.patch
* lando init
* lando start
* lando drush si --db-url=mysql://backdrop:backdrop@database/backdrop
* In active/installer.settings.json change `"core_update": false` to `"core_update": 1`

**Probably not necessary, but trying to be thorough (Adjust permissions and ownership as per - https://backdropcms.org/file-permissions-and-ownership)**

In Backdrop root.

* chown -R timothyerickson:staff .
* find . -type f -exec chmod 664 '{}' \\;
* find . -type d -exec chmod 755 '{}' \\;
* chmod 774 index.php
* chmod 774 core/install.php
* chmod 774 core/update.php
* chmod 774 core/cron.php

**Login to site:**

* Go to: http://localhost:32773/admin/modules/update
* Select Backdrop and "Download these updates"
* See: Perform updates with site in maintenance mode (strongly recommended)
* Select "Continue"
* See error page with "The website encountered an unexpected error. Please try again later."
* Check recent log messages and find: "UpdaterException: The info file (<em class="placeholder">temporary://update-extraction-a2f14549/backdrop/core/modules/email/tests/email.tests.info</em>) does not define a 'type' attribute. in Updater::getProjectType() (line 194 of /app/core/includes/updater.inc)."

**Test module update**

* Install (manually copy it into the modules folder) Devel 1.x-1.6.0 (old version)
* Enable Devel module
* Go to: http://localhost:32773/admin/modules/update
* Select Devel and "Download these updates"
* Finish update
* Module is updated successfully

**Actual behavior**

See error message above.

**Expected behavior**

Successful update. 

**Additional information**

**Comment by stpaultim** [comment]
@serundeputy - FYI - I did try with the shorter script that you provided as well. Getting the same error both ways.

**Comment by serundeputy** [comment]
@stpaultim what php version are you running?

**Comment by stpaultim** [comment]
According to the Backdrop CMS status page, I'm running PHP v 7.0.33
I dropped a phpinfo.php in Backdrop root and that is telling me the same thing (as I would expect).

I may have other versions of php installed on my laptop, but doesn't Lando and/or the Backdrop recipe determine which version of php is being used?

FYI: This is what my .lando.yml file looks like:

> name: 'test'
> recipe: backdrop
> config:
>  webroot: .

**Comment by serundeputy** [comment]
yes; lando determines the php version (for backdrops that are running via lando)

**Comment by jenlampton** [comment]
> Is this a duplicate of #1294? 

yes.
