### ISSUE TITLE
Locale: admin bar links not updated when changing the default URL path prefix for a language

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3448]
**Describe the bug**
I came across this tiny WTF while testing #704

**Steps To Reproduce**

1. Enable locale.module (which also requires language.module to be enabled).
2. [optional] Add another language, or not - all the same.
3. Leave the detection method (`/admin/config/regional/language/detection`) configured as URL-based.
4. Leave the default path prefix for the second language added in step 2 above as is, but change English to `/en` (or something).
5. Save configuration -> configuration gets saved successfully, and the URL in the browser address bar gets updated to include the `/en` prefix 👍
6. Use the admin bar to navigate anywhere -> 404 👎

...say you are one of the extra-cautious kind, and you hover your mouse over the admin toolbar links before clicking away. Say you notice that the links in the admin bar do not include the newly-added `/en` prefix, or perhaps say that you are Drupal/Backdrop-savvy and know that you need to clear caches after making such changes. So try to clear caches to fix this problem. If you happen to use the admin toolbar to do that -> 404 👎

**Actual behavior**
The links in the admin bar do not get updated to include any change in the language prefix setting, which causes any link in the admin bar to lead to a 404.

**Expected behavior**
Caches (at least the menu cache) should be programmatically cleared when saving the form in `/admin/config/regional/language/detection/url`

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2435

**Comment by klonos** [comment]
1-liner PR up for review 😉

**Comment by herbdool** [comment]
Marking RTBC since @opi approved the PR.

**Comment by quicksketch** [comment]
Great, thanks! Merged https://github.com/backdrop/backdrop/pull/2435 into 1.x and 1.11.x. Thanks @klonos and @opi!
