### ISSUE TITLE
Identify translatable strings in core static config files

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3455]
Follow-up to https://github.com/backdrop/backdrop-issues/issues/704.

Add config translatable arrays to core config files. Update views, layouts, etc code so that translatables are added to new config files. And update display of those config so they're localized.

Update: I'm restricting this to just the "static" config files, and will deal with "dynamic" config files separately. For example, Views, Layouts and Image styles. These will require more complicated solutions.

--
PR https://github.com/backdrop/backdrop/pull/2458

**Comment by herbdool** [comment]
@quicksketch @serundeputy do you think we should add `_config_translatables` setting to the default json files out of the box, or add them with `$config->set` if locale is enabled?

The former is easier to add, but might be confusing to site builders who aren't going to use locale. 

The latter might require a new hook which runs on `locale_enable` and which will add the `config_translatables` if the hook is called in the respective module. Ideally we'd want it to add the config translatables if locale or the other module is enabled. And remove them all if locale is uninstalled. The latter gets a bit complicated.

**Comment by quicksketch** [comment]
I think `_config_translatables` should always be present and be part of the main config system at all times. Otherwise you wouldn't be able to easily turn on Locale module later on a site that previously had not been localized. Sort of similar to how we always store `langcode` columns in the database even though most of the time they're `und`, we always want to be ready to convert a site to translation.

**Comment by klonos** [comment]
...adding milestone as per our dev agenda: https://docs.google.com/document/d/1HJUF3dKkSXA64Y7rx_avGVBH5ldtqbLPyCx8fDThzVA

**Comment by jenlampton** [comment]
There's no PR here yet, should we bump this issue to the next milestone, or is this something we can get done in less than one month?

**Comment by herbdool** [comment]
@jenlampton There's a PR listed at the top of the issue already https://github.com/backdrop/backdrop/pull/2458

**Comment by jenlampton** [comment]
oh duh, sorry I missed it as there were no PR labels on the issue.

**Comment by olafgrabienski** [comment]
I've added "works for me", based on my reports over in the PR, cf. https://github.com/backdrop/backdrop/pull/2458#issuecomment-485993307 and https://github.com/backdrop/backdrop/pull/2458#issuecomment-486426226.

**Comment by quicksketch** [comment]
Hi @herbdool, I realized I had started a review weeks ago but had never hit the save button. To GitHub's credit, it remembered it. :smile: There are a few suggested changes on the PR now. https://github.com/backdrop/backdrop/pull/2458#pullrequestreview-203970419

**Comment by herbdool** [comment]
@quicksketch :smile: I've done the same thing!

The PR is ready for another review. I've made all the changes you've suggested.

**Comment by quicksketch** [comment]
Looks great! Thanks! I think maybe we should close out this issue as being specific to the files we've already covered, and make new ones for the other static files? Or should we just keep going here?

I've merged https://github.com/backdrop/backdrop/pull/2458 into 1.x for 1.13.0, which includes site settings (slogan, title), out of box user roles, maintenance message, and email templates.

**Comment by herbdool** [comment]
Let's create new issues for follow-ups.
