### ISSUE TITLE
[UX] Add cute arrow indicators to the more/less links

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3456]
Iv'e always wanted cute arrows on these things, so we could go from:
<img width="1194" alt="screen shot 2019-01-01 at 1 20 16 pm" src="https://user-images.githubusercontent.com/397895/50576508-016c3600-0dc8-11e9-8153-aed472666ba9.png">

...to:
<img width="1183" alt="screen shot 2019-01-01 at 1 42 31 pm" src="https://user-images.githubusercontent.com/397895/50576648-1d250b80-0dcb-11e9-9018-656c0e70e5a2.png">

---
PR: https://github.com/backdrop/backdrop/pull/2448

**Comment by docwilmot** [comment]
RTBC

**Comment by quicksketch** [comment]
Great thanks! Merged https://github.com/backdrop/backdrop/pull/2448 into 1.x and 1.11.x.

I had thought this might be slightly better with a pseudo-element for the arrow instead of an empty span, but the result would be the same so :man_shrugging:

**Comment by jenlampton** [comment]
whitespace nowrap problem, reopening.

**Comment by quicksketch** [comment]
Thanks! That whitespace fix corrects the little arrow from ending up on its own line. Merged https://github.com/backdrop/backdrop/pull/2453.
