### ISSUE TITLE
[UX][DX] Improve the message about theme color.module support.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3458]
While reviewing #3257, I have noticed that when color.module is disabled, we show [a message in the theme settings page of Basis](https://github.com/backdrop/backdrop/blob/1.x/core/themes/basis/theme-settings.php#L11):

> This theme supports custom color palettes if the Color module is enabled on the [modules page](). Enable the Color module to customize this theme

...the link in that message points to `/admin/modules`.

Things we could improve:

1. The message could be a `backdrop_set_message()` of type `info` instead of a form `#markup` element.

2. The entire text could be shortened to:

    > This theme supports custom color palettes. [Enable the Color module]() to start customising it.

3. The link to the modules page could also be filtered to show only the color module (`/admin/modules?search=color`), and we should add destination so that the user is taken back to the theme settings page after enabling the module.

4. This bit here seems like code which could benefit all themes that support color.module. Perhaps consider moving the logic out of Basis and into a system-wide module.

5. When color.module is disabled, there are no other form elements left in that page (other than the `#markup` message), so the "Save theme settings" button does not make sense:

    <img width="564" alt="screen shot 2019-01-04 at 3 12 21 am" src="https://user-images.githubusercontent.com/2423362/50681937-d5de8b00-1015-11e9-8018-be7b3c5ad824.png">

    ...we should have some logic in place so that this submit button is rendered only if there are settings to save.

---
PR by @hosef: https://github.com/backdrop/backdrop/pull/2614

**Comment by hosef** [comment]
I created a PR that implements the various improvements recommended by Klonos.

**Comment by jenlampton** [comment]
> The message could be a backdrop_set_message() of type info instead of a form #markup element.

I don't think we should be setting messages unless we need to. Messages carry some overhead, they are user-specific and always appear on the page-load after they are triggered. None of this is necessary here. Can't we make this a `#type = help` instead?

**Comment by klonos** [comment]
> ... Can't we make this a `#type = help` instead?

Hmm 🤔 ...not sure I agree. It seems to me that help text as a form element is logically "attached" to either the form, or a specific element in the form. The "info" type messages have been introduced for use cases like this, where we want to provide "tips" or "hey, did you know that ..." messages to users (or at least that was the idea when I was working on that feature).

> Messages carry some overhead, they are user-specific and always appear on the page-load after they are triggered.

Care to elaborate on the first two points? Not sure what you mean by "overhead" and messages being user-specific.

Anyway, if the issue is the fact that we are calling `backdrop_set_message()` (with whatever drawbacks this has), then I think that #3329 might be the solution.

**Comment by klonos** [comment]
@hosef the PR sandbox is going straight to the installer. Can you please refresh the PR (close/reopen it)?

**Comment by hosef** [comment]
I updated the PR with the latest changes from the 1.x branch and refreshed the test sandbox.

**Comment by hosef** [comment]
I agree with @klonos. This seems like a perfect use for info messages. As far as the overhead, I profiled the related functions, and it looks like the time to render a status message is less than 50 ms, so I don't think it is that bad. Also, it only shows on follow up pages when the message is issued after the rendering has started, which is not the case in this case, so the message does show up on the first page view.

**Comment by klonos** [comment]
I've tested the PR, and it WFM 👍 ...I've left a minor comment about the wrapping of an inline code comment, plus I am receiving this error when trying to access theme settings:

```
Notice: Undefined index: default in color_form_system_theme_settings_alter() (line 42 of /core/modules/color/color.module).
```

Once those 2 things are addressed, this is RTBC.

**Comment by klonos** [comment]
...strangely enough, I am cannot reproduce the "Undefined index" error when testing the PR on my local, but I did rebase. Perhaps do the same and refresh the PR sandbox @hosef?

**Comment by stpaultim** [comment]
I tested this issue and it works for me! 

I like the change and certainly like the look of the info message.

I'm not sure what the intention was for info messages nor do I have opinions about the "overhead."

![color-module-settings](https://user-images.githubusercontent.com/3144571/103493024-90b3e600-4df4-11eb-8795-29db8cc7b601.png)

![new-info-message](https://user-images.githubusercontent.com/3144571/103493026-914c7c80-4df4-11eb-88e9-2519136216cc.png)

**Comment by laryn** [comment]
Thanks for the PR @hosef and for the review @klonos and @jenlampton! Thanks for testing @stpaultim. Merged into 1.x and 1.19.x.

Contrib themes may have to clean things up a bit if they've implemented a Color module notice of their own but I don't see a way around that.
