### ISSUE TITLE
file_unmanaged_move() should issue rename() where possible instead of copy() & unlink()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3459]
**Describe the bug**
This is the respective issue for https://www.drupal.org/project/drupal/issues/2752783, and is also related to #1380. The D7 patch is a backport of what has already been merged in [the respective D8 issue](https://www.drupal.org/project/drupal/issues/1377740), it is RTBC and slated for Drupal 7.70:

> **Problem/Motivation**
> When drupal moves a file it issues a `copy()` and then an `unlink()` this causes a very significant amount of I/O. If the source and destination are on the same filesystem and `rename()` is issued instead then virtually no I/O occurs because filesystems can perform this operation by just changing a pointer on disk.
> 
> **Proposed resolution**
> Instead of `file_unmanaged_move()` calling `file_unmanaged_copy()`, break out the common code into a new function `file_unmanaged_prepare()` and have `file_unmanaged_move()` attempt to issue a `rename()`, falling back to `copy()` and `unlink()` if this does not work.
> 
> This optimizes `drupal_build_css_cache()`, `drupal_build_js_cache()`. It also prevents a race condition with these functions where other processes or servers may start reading the files before they are fully written.
> 
> A further advantage of issuing a `rename()` is that some remote schemes have implemented this method, e.g. it would be possible for a file to be moved to a different location on Amazon S3 without having to download it and re-upload it to the correct location.

Given that a) we had to wait for more than a year to see a non-security release of D7, b) that both the D7 and D8 issues are categorised as major bugs, and c) the fact that we have much more frequent release cycles in Backdrop, we should not have to wait in order to get this in.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2455

**Comment by herbdool** [comment]
I agree this can be added at any time. What version of the patch for D7 did you use @klonos?

**Comment by klonos** [comment]
I have used https://www.drupal.org/files/issues/drupal-file_unmanaged_move-rename-where-possible-2752783-17.patch, but there also was this early version of a backport from D8: https://www.drupal.org/files/issues/file_unmanaged_move_rename_where_possible-2752783-6.patch

...AFAICT, the objection for that one was that it was changing strings, which is unacceptable for D7. We don't have this problem in Backdrop, so if the respective versions of the D8 strings make more sense, we could (should?) use those instead. Happy to update the PR using those.

**Comment by herbdool** [comment]
Updating strings is fine (though it does add work for translators) so you could use that second patch. But I would still include the change to watchdog messages in https://www.drupal.org/project/drupal/issues/2752783#comment-12387279

**Comment by klonos** [comment]
> But I would still include the change to watchdog messages in drupal.org/project/drupal/issues/2752783#comment-12387279

I thought that I had already done so @herbdool ...if I happened to miss anything, can you please point it for me in the PR? Thanks.

**Comment by herbdool** [comment]
@klonos yes you already did. I mean if you update the PR with strings from other patch.

**Comment by quicksketch** [comment]
This code looks good. Do existing tests already ensure the correct behavior? The end-result should be identical after all, just a lot faster with `rename()`.

**Comment by quicksketch** [comment]
Love this issue. Gave it a closer look and left a short review: https://github.com/backdrop/backdrop/pull/2455#pullrequestreview-191500461

**Comment by klonos** [comment]
@quicksketch I have updated the PR with the requested changes + the strings that were not added in the D7 patch (use `moved/copied` instead of just `copied`). Care to have a final look?

**Comment by quicksketch** [comment]
Looks great. With all the testing coming from the Drupal.org side plus our own testing and reviewing this seems good to go. Last changes all look great. I've merged https://github.com/backdrop/backdrop/pull/2455 into 1.x and 1.12.x, thanks!
