### ISSUE TITLE
Should git ignore settings.php?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#346]
I'm a bit confused... When I checkout Backdrop with git and setup a new site, I have to create a `files` directory and Backdrop adds database info to the `settings.php` file. When making changes to commit to core, git also says `settings.php` has been modified, but mentions nothing about the newly-created `files` directory. Both `settings.php` and `files` are listed in the `.gitignore` file, but only one seems to be working...

Should `settings.php` be ignored (and hence there's a problem with the `.gitignore` file), or should it not be ignored (and hence should be removed from the `.gitignore` file)?

**Comment by mikemccaffrey** [comment]
>On a production site, you wouldn't be running a Git checkout from the Backdrop core repository

Hmmmm.... @quicksketch, doesn't the upstream repository for Pantheon pull from the Backdrop core repository? When I clone my site from the pantheon repo, there is a settings.php files included which is constantly showing as overridden.

I'm fine just running "git update-index --assume-unchanged settings.php", but whenever I run git stash, it reverts my settings.php to the version in the repository. Does that happen to other people too? How are people working around this issue?

**Comment by MrHaroldA** [comment]
I'm getting tired of my changes to settings.php and sites.php being overwritten every time I checkout a different branch of Backdrop. I also committed settings.php a couple of times already, even in GitHub pull requests.

Can we pretty please add a file exists check and an include to allow local untracked php files to set all configuration options needed?

**Comment by alexfinnarn** [comment]
I also like the idea of including a check for a settings.local.php file as I've always used this in Drupal 7 sites and it's now in Drupal 8 by default.

**Comment by gifad** [comment]
Another solution would be to fix the `chdir('..')` trick in update.php, cron.php, to allow your dev environment(s) with `core` symlinked to the `core` folder of your repo.
see [#1297 : Installation and update problem with symlinked core folder](https://github.com/backdrop/backdrop-issues/issues/1297) 
Additionally, this would make easier to test PR with contrib modules/themes !

**Comment by Gormartsen** [comment]
PR backdrop/backdrop#1310 created.

**Comment by BWPanda** [comment]
I imagine that if this were still an issue for people that there'd be more activity here...? Closing this old issue, but feel free to re-open if necessary.
