### ISSUE TITLE
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in backdrop_clear_opcode_cache()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3461]
Reported on Gitter by @twmfc:

>I’ve just installed BD 1.11.3 on a standard ServerPilot build using php 7.2 and it throws a few of the following warning messages during the install process:-
> `Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in backdrop_clear_opcode_cache() (line 4339 of /xxxxxxx/core/includes/bootstrap.inc).`

---
PR by @klonos (use `@` to suppress PHP warnings): https://github.com/backdrop/backdrop/pull/2457

**Comment by klonos** [comment]
...This seems to be a common problem with some hosting providers:

https://github.com/Automattic/wp-super-cache/issues/536

https://wordpress.org/support/topic/no-access-for-zend-opcache/

A quick and dirty solution would be to prepend [`opcache_invalidate()`](https://github.com/backdrop/backdrop/blob/1.x/core/includes/bootstrap.inc#L4339) with a `@` to ignore any such errors.

There is an issue for D8: [Use less demanding check to see if OPcache is active](https://www.drupal.org/node/2639878) ...but the fix was not backported to D7 😞

There seem to be some other related issues too:

- [Opcache warning is inappropriate when HHVM is in use](https://www.drupal.org/project/drupal/issues/2657030)
- [Add a hook_requirements() warning if no opcode cache is enabled](https://www.drupal.org/project/drupal/issues/2502507)
- [Recommend xcache or opcache in the requirements check](https://www.drupal.org/project/drupal/issues/2630624)

**Comment by quicksketch** [comment]
Looks great, thanks @klonos! We're already suppressing the warnings when using the matching APC function, so suppressing warnings for Zend as well doesn't seem like it would be problematic. I've merged https://github.com/backdrop/backdrop/pull/2457 into 1.x and 1.12.x. Thanks!
