### ISSUE TITLE
Saving an Image field with an image that has undeterminable dimensions throws PDOException.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3462]
**Describe the bug**
Saving an Image field with an image that has undeterminable dimensions throws a fatal error. You'd think a missing file isn't that big of a deal, right? 

```
EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'field_image_width' at row 1 in NodeStorageController->save() (line 320 of backdrop/core/modules/node/node.entity.inc).
```

**Steps To Reproduce**
To reproduce the behavior:
1. Upload an image onto an article, save the node.
2. Delete the file from disk so it no longer exists in the location Backdrop is tracking.
3. Edit/Save the same page again.
4. Fatal error.

**Actual behavior**
Fatal error.

**Expected behavior**
No fatal error.

**Additional information**
- [Related d.o issue](https://www.drupal.org/project/drupal/issues/1330952)

---
PR https://github.com/backdrop/backdrop/pull/2459

**Comment by herbdool** [comment]
I was curious if your approach was similar to that taken in d.o. Seems like it takes a simpler route. Maybe that's better

**Comment by jenlampton** [comment]
I applied the D7 patch from that issue, I thought?

**Comment by herbdool** [comment]
Where's the D7 patch? I took a look at the D8 issue but don't see it.

**Comment by jenlampton** [comment]
This one: https://www.drupal.org/files/issues/drupal-image_get_info_failure-1330952-57-D7.patch

**Comment by quicksketch** [comment]
This looks good from the code-side. With such easy to reproduce instructions and a fatal error resulting, we should add new tests to cover this situation.

**Comment by jenlampton** [comment]
Can we fix the bug now and add tests later? Or does the bug have to stay if we don't have tests? (I personally don't know how to get test bot to delete a file from disk... )

**Comment by herbdool** [comment]
You might be able to get the path to the test file and then call backdrop_unlink or unlink().

**Comment by quicksketch** [comment]
> Can we fix the bug now and add tests later? Or does the bug have to stay if we don't have tests? (I personally don't know how to get testbot to delete a file from disk... )

We should add tests at the same time. Deleting a file from disk in a test isn't hard:

```
// See FileManagedFileElementTestCase::testManagedFile() for full example.
// Create a node with a file uploaded.
$nid = $this->uploadNodeFile($test_file, $field_name, $type_name);
// Remove the file from disk out from under Backdrop.
unlink($file_path);
// View the node.
$this->backdropGet('node/' . $nid);
```

**Comment by herbdool** [comment]
I started working on a test for this, but I'm having a hard time recreating the fatal error. Even if I manually remove the image and resave it I don't get an error and the image is still visible though it's no longer at that path. Odd. Perhaps it's the browser cache.

Here's my test. The test is all green even before I apply the patch from above:

```
class ImageFieldMissingTestCase extends ImageFieldTestCase {

  /**
   * Test for no fatal errors if image file missing when resaving content.
   */
  function testMissingImage() {
    $image = $this->backdropGetTestFiles('image');
    $nid = $this->uploadNodeImage($image[0], 'field_image', 'post');
    $node = node_load($nid);
    $test_image_uri = $node->field_image[LANGUAGE_NONE][0]['uri'];

    $this->assertTrue(is_file($test_image_uri), 'Test image exists.', 'Image');

    backdrop_unlink($test_image_uri);

    $this->assertFalse(is_file($test_image_uri), 'Successfully removed the test image.', 'Image');

    // Test for fatal error.
    $this->backdropPost('node/' . $nid . '/edit', array(), t('Save'));

  }
}
```

**Comment by klonos** [comment]
>I couldn't make the Better Login module work for Backdrop, so I've gone another route, using a custom layout

This is no good then. We definitely need a failing test with the current situation, which passes when the fix for this issue is applied.

**Comment by jenlampton** [comment]
I have a site that suffers from this, let me see if I can get better steps to reproduce.

**Comment by jenlampton** [comment]
Okay, I just updated my site to 1.12.4, so I have a fresh chance to study this again.

**Comment by jenlampton** [comment]
I'm nolonger getting this fatal. Closing issue.
