### ISSUE TITLE
PHP Notice: Undefined property: stdClass::$name in field_ui_display_overview()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3463]
**Describe the bug**
PHP notice appears on "manage displays" page for entities who's bundles don't have a name property.

```
Notice: Undefined property: stdClass::$name in field_ui_display_overview() (line 836 of backdrop/core/modules/field_ui/field_ui.admin.inc). 
```

**Steps To Reproduce**
To reproduce the behavior:
1. Install multifield module
2. Add a multifield to any content type
3. Click manage subfields, and add any field.
4. Click "Manage displays" for the subfields, see the notice.

**Actual behavior**
PHP notice

**Expected behavior**
No PHP notice

---
PR: https://github.com/backdrop/backdrop/pull/2460

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/2460 reviewed by @herbdool and changes made. Looks good to me. Merged into 1.x and 1.11.x.
