### ISSUE TITLE
ETag Header Generated By Backdrop should be in Quotes

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3466]
**Describe the bug**
In #1214 we changed the way headers were returned, and as part of that we started appending `-gzip` to compressed output while omitting any suffix from non-gzipped output. In that change we stopped quoting the ETag header. Recently I encountered issues where non-quoted Etags were not being respected by some CDNs like Akamai. Adding the quotes matches the specification and makes it so that 304 Not Modified responses may be returned. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

**Steps To Reproduce**
To reproduce the behavior:
1. New Backdrop install (page caching turned on by default). Log out.
2. Open Network inspector and load any page. See the request has an ETag that is not in quotes.
3. Reload the page, with only Apache you get a 304 Not Modified response. If Akamai is in front of the site. You will not get a 304 response, instead you will always get an HTTP 200.

**Actual behavior**
HTTP 200 returned instead of cached HTTP 304.

**Expected behavior**
HTTP 304 returned for identical content.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2462

**Comment by quicksketch** [comment]
Screenshot of our current ETags. Note that Apache seems to handle this fine so there are no problems on a local installation.

![image](https://user-images.githubusercontent.com/100206/50992888-24d06880-14cd-11e9-9636-9b80b0e18dd4.png)

It's also interesting that `backdrop_page_header()` adds the quotes as expected, it's only when the page cache is used that the quotes are omitted in `backdrop_serve_page_from_cache()`.

**Comment by herbdool** [comment]
This would be hard for most people to fully test. Perhaps it's enough to just confirm quotes are present?

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2462 into 1.x and 1.12.x.
