### ISSUE TITLE
[UX] Don't say 'edit' when we mean 'configure' - user roles edition

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3468]
Looks like we missed another spot:
<img width="1408" alt="screen shot 2019-01-10 at 6 28 35 pm" src="https://user-images.githubusercontent.com/397895/51009582-90362c80-1505-11e9-9e0c-6b3f195e9daf.png">

---
PR: https://github.com/backdrop/backdrop/pull/2467

**Comment by klonos** [comment]
LGTM 👍

**Comment by klonos** [comment]
...I agree to get it in for 1.11.4 👍

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2467 into 1.x and 1.11.x.
