### ISSUE TITLE
[UX] Add Manage fields and Manage displays drop-buttons for vocabularies

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3469]
On the content type listing we have drop-buttons for managing fields on nodes. We should do the same for managing fields on taxonomy terms. 
<img width="1404" alt="screen shot 2019-01-10 at 6 37 28 pm" src="https://user-images.githubusercontent.com/397895/51009900-caec9480-1506-11e9-9bc5-8475e31c3ea9.png">

Adding milestone candidate tag for 1.11.4

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2465

**Comment by klonos** [comment]
RTBC 👍 ...as for the milestone candidate, I concur 😄 (is that all it takes?)

**Comment by jenlampton** [comment]
> as for the milestone candidate, I concur 😄 (is that all it takes?)

Yep! If you agree, you can add the milestone :)

**Comment by quicksketch** [comment]
Thanks, looks good! Merged https://github.com/backdrop/backdrop/pull/2465 into 1.x and 1.11.x.
