### ISSUE TITLE
Allow specifying menu to display in Admin Bar (per role)

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#347]
I'd love it if you could choose which menu gets displayed in the Admin Bar (i.e. replace the Management menu with a custom menu). And maybe set different menus for different roles (so Admins see Management menu and Editors see custom menu).

Use case for this would be wanting to use the Admin Bar as _the_ place for administering the site (rather than adding menus to the sidebar for editors), but wanting to heavily customise the menu items for Editors (and don't want to mess with adding/removing items from the Management menu).

Thoughts?

**Comment by BWPanda** [comment]
Re-reading this, I totally agree that this should be in contrib. Since it's not even there yet though, closing this for now.
