### ISSUE TITLE
PHP Deprecated Warning with Link module 'INTL_IDNA_VARIANT_2003 is deprecated' PHP 7.3

### ISSUE THREAD

**Issue by andybroomfield** [backdrop/backdrop-issues#3470]
**Describe the bug**
As Title.
Using the Link Module, I see the following PHP error
"Deprecated function: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in _link_escape_domain() (line 707 of /Users/andy/Sites/fantsuam-new/httpdocs/core/modules/link/link.module)."

**Steps To Reproduce**
To reproduce the behavior:
1. Enable and add a link field to a content type
2. Add content with the link field (filling out a url).
3. Save and view the page.

**Actual behavior**
See above error.

**Expected behavior**
No Error.

**Additional information**
- Backdrop v 1.11.3
- PHP 7.3.1
(I think error may exist on PHP 7.2 as well).
This is a deprecation warning so doesn't effect the links functionality.

My fix is here:
https://github.com/andybroomfield/backdrop/commit/e8b607588b9730889acb0789dff9250e8d1464ab
However I believe this may break PHP 5.3 compatibility.
Ref: http://php.net/manual/en/function.idn-to-ascii.php

**Comment by andybroomfield** [comment]
Have added a PR (https://github.com/backdrop/backdrop/pull/2517)

**Comment by herbdool** [comment]
Thanks for the fix @andybroomfield. I see the automated tests pass for both 5.3 and 7.x so I think your check works well enough. I'm marking this as RTBC.

**Comment by quicksketch** [comment]
This PR looks good. The situation is confusing though. It seems that the default value for PHP 7.2 is `INTL_IDNA_VARIANT_2003`, even though it's deprecated. So the fix here is to pass in ` INTL_IDNA_VARIANT_UTS46` (if it exists).

**Comment by quicksketch** [comment]
I pushed an update to the PR that tries to make sense of the whole mess by clarifying what's happening in code comments.

**Comment by quicksketch** [comment]
Ah! I see why I shouldn't have done that:
![image](https://user-images.githubusercontent.com/100206/53614030-31984100-3b8d-11e9-967c-e2a0fc86cffc.png)

Well so much for refactoring any further. I'll revert my commit and go with the original one. :smile:

**Comment by andybroomfield** [comment]
@quicksketch It is very confusing when I encountered it. Happy to go with what you think works best.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2517 into 1.x and 1.12.x. Thanks @andybroomfield and @herbdool!
