### ISSUE TITLE
[UX] Remove unused CSS and other minor cleanups for dblog module.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3471]
Original issue: The changes from #3437 caused a color change for info icons. (edit: this is intended, this is the new info color added in https://github.com/backdrop/backdrop-issues/issues/3155)

Style now: 
<img width="1209" alt="screen shot 2019-01-11 at 10 29 43 pm" src="https://user-images.githubusercontent.com/397895/51070174-aa4d3900-15f1-11e9-8f65-f401e6740a2e.png">

PR addresses the following:
* the ok icon is paired with any dblog message that's not info, warning, or error. (this matches the color change made in https://github.com/backdrop/backdrop/pull/2426)
* all icons are more reasonably sized now
* pink background on errors now works for the whole row
* pink background on errors now has lighter color for odd rows than even
* all other background row colors (that were not working) have been removed

<img width="1233" alt="screen shot 2019-01-12 at 12 17 48 am" src="https://user-images.githubusercontent.com/397895/51071022-8bee3a00-15ff-11e9-9daa-23d14b2557e0.png">

---
Adding milestone candidate for 1.11.4

---
PR: https://github.com/backdrop/backdrop/pull/2469

**Comment by jenlampton** [comment]
uhoh, yeah. looking!

**Comment by jenlampton** [comment]
@klonos I am re0purposing this issue for a general DBlog css cleanup. Adding items to the main issue.

**Comment by klonos** [comment]
> @klonos I am re-purposing this issue for a more general DBlog css cleanup. I have added various other CSS clean up items to the main issue, and those are all addressed in the PR.

Thanks @jenlampton 👍 

> @klonos I think what you are seeing here is a bug-fix that went in as part of #3437.

Yep, that's why it was the first thing I mentioned in the issue description 😛 

> We have a new "info" status message, and colors that go with it (blue!). We also have an "Info" status for the dblog, but before the new status message went in, we didn't have any colors associated with the info log messages.

Yep, what triggered this issue was that certain info rows had a gray color (`dblog-notice` class), while others had blue (`dblog-info` class). I was not leaning towards or the other specifically; just calling out for consistency 😉 ...is this intentional? If so, then ignore me. If not, then still not fixed in the PR:

<img width="1186" alt="screen shot 2019-01-12 at 10 24 52 am" src="https://user-images.githubusercontent.com/2423362/51071093-5fb0d880-1654-11e9-9d06-9abedb5b652d.png">

Other things I'd like to see fixed before I mark this as RTBC:

- Light/dark error rows do not have a hover color like the rest of the info/warning rows.
- The intersection cell of the yellow hovered-over rows and the rorted-by column does not get any hover color.

**Comment by jenlampton** [comment]
> Yep, what triggered this issue was that certain info rows had a gray color (`dblog-notice` class), while others had blue (`dblog-info` class).

The rows that gray were not info rows. they were any other status than info, warning, or error. I've since changed the icon for those to the checkmark to make that less confusing for everyone (and added UX to the issue title).

I looked at the hover color issues, but those didn't seem quick easy to fix. I'll give it another go tomorrow with fresher eyes :)

**Comment by klonos** [comment]
Thanks @jenlampton 👍

...yeah, I just noticed that the screenshot you have provided in the issue summary have gray ticks instead of gray info symbols, but that is not the case in the PR sandbox (see my screenshot) ...and I did flush caches multiple times.

A final thing: the symbols within the circles seem to be off to the left by 1px (more obvious in the triangular exclamation sign I think):

<img width="87" alt="screen shot 2019-01-12 at 1 58 01 pm" src="https://user-images.githubusercontent.com/2423362/51073387-db248100-1678-11e9-8d34-ce335d98ba84.png">

...I think that it has to do with using even/odd px for widths/heights and `background-size`. I have mocked around with using the browser dev tools, and it seems that setting `background-size` to `25px` instead of `26px` works better:

<img width="96" alt="screen shot 2019-01-12 at 1 57 40 pm" src="https://user-images.githubusercontent.com/2423362/51073410-276fc100-1679-11e9-9407-372ac9f4ac57.png">

**Comment by klonos** [comment]
...and I concur on the milestone 😉

**Comment by jenlampton** [comment]
> but that is not the case in the PR sandbox

well, it is the case in the PR...  I'll push again (with the 1px change) and see if that fixes the sandbox...

**Comment by klonos** [comment]
>Do they need to? The hover color is to help people navigate the same row all the way across. Doesn't the red/pink color solve that problem?

Your are absolutely right 👍

> This is a problem with the seven theme. See #3477

Agreed. I have reviewed and RTBC'ed that issue as well 😉

> edit: it seems to be fine now:

Indeed, icons look good now 👍 ...but one thing that was wrong that I could not put my finger to till now is the blue color of the info icon. It should be #0074bd, as that is the background color of the info icon in messages (#004570 that is currently used in the PR is the color of the info message text). Fix that, and this issue is RTBC from me as well.

**Comment by klonos** [comment]
Yep, fixed 👍 

Everything looks good now ...especially with #3477 merged 😉

RTBC!

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2469 looks good! Thanks merged into 1.x and 1.11.x.
