### ISSUE TITLE
Remove search block default title

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3476]
In https://github.com/backdrop/backdrop-issues/issues/2923 we discussed how there are a lot of instances of the word "Search". Ideally, the search form block would have no title. We can remove it, but we'd also need an update hook to update all existing layouts to add a custom block title for any block that had previously used the default. This could be a bit tricky, so in the hopes of getting https://github.com/backdrop/backdrop-issues/issues/2923 in for Backdrop 1.12, I've split this off into a separate issue. 

The problem: 
<img width="2758" alt="screen shot 2019-01-12 at 11 08 14 am" src="https://user-images.githubusercontent.com/397895/51077347-6f332000-165a-11e9-84c4-165cff4d02d0.png">

The solution:
<img width="2766" alt="screen shot 2019-01-12 at 11 09 14 am" src="https://user-images.githubusercontent.com/397895/51077352-925dcf80-165a-11e9-9e03-2cb90f257a73.png">

Steps to test:
1. Fresh install of backdrop (or, untouched sandbox)
2. Confirm there is no search block on any layout
3. Add a search block -- ignore all settings on the configure block form, just add it blindly.
4. Confirm there is no title shown for the search block.

---
PR: https://github.com/backdrop/backdrop/pull/2470

**Comment by quicksketch** [comment]
PR looks good, and it has an update hook, yay!

**Comment by quicksketch** [comment]
Oops, sorry PR is failing tests: `exception Undefined index: settings search.install:214` Back to needs work.

**Comment by docwilmot** [comment]
This seems a simple one to get done. @jenlampton can you revisit?

**Comment by docwilmot** [comment]
@jenlampton update?

**Comment by herbdool** [comment]
@docwilmot I made a fix. All tests pass. Want to give it a review?

**Comment by BWPanda** [comment]
I might be missing something, but I can't see any code that removes/hides the search block title... There's only an update hook added which changes 'default' block titles to 'custom' ones, and a whitespace change.

To confirm, I tested adding a search block on my dev site before patching it. The block was added with a title 'Search'. I removed it, applied the patch, ran update.php, then added the block again. It still had a title 'Search'...

**Comment by jenlampton** [comment]
> I can't see any code that removes/hides the search block title [...] There's only an update hook added which changes 'default' block titles to 'custom' ones

That's right, there is already code in core that will hide a block title if it's overridden, and the overridden value is blank. All this PR does is change the configuration of existing search blocks that have not had their configuration changed (ones that are in the default state).

To test:
* Install Backdrop
* Confirm search block titles on every layout
* apply patch, run update
* Confirm NO search block titles on every layout

**Comment by BWPanda** [comment]
> To test:
>
> - Install Backdrop

Done.

> - Confirm search block titles on every layout

No layouts had a search block by default, so I added one to the Default layout. I left everything as the default, and confirmed the search block had a title.

> - apply patch, run update

Done.

> - Confirm NO search block titles on every layout

Default layout's search block still has title... :frowning_face: 

Am I doing something wrong, or does this PR need more work?

**Comment by jenlampton** [comment]
> Am I doing something wrong, or does this PR need more work?

No, it's me *facepalm*.  
I re-read the previous issue and found the code that was missing from the PR, and added it back. 

Steps to test:
1. Fresh install of backdrop
2. Confirm there is no search block on any layout
3. Add a search block -- ignore all settings on the configure block form, just add it blindly.
4. Confirm there is no title shown for the search block.

**Comment by BWPanda** [comment]
Ok, so this worked better this time, I just want to confirm what I experienced was the expected result...

- No patch applied, all layouts reverted to default: no search blocks anywhere
- Added search block with default settings to homepage: block title shown
- Applied patch, cleared caches: homepage search block still has title (is this expected?)
- Added search block to default layout, default settings: no block title show :+1: 

If existing, default search blocks are supposed to lose their title, then this still needs work. If not then this seems to work as expected.

**Comment by stpaultim** [comment]
>Steps to test:
>Fresh install of backdrop

Does this mean that we're not supposed to test this in the Sandbox and that we should install the parent branch of this PR for testing?

**Comment by stpaultim** [comment]
I did this locally and this was the result (spoiler = "no block title shown")

![Screen Shot 2020-08-30 at 1 21 10 AM](https://user-images.githubusercontent.com/3144571/91652674-1bf42800-ea5f-11ea-9171-08a0a2ce68ae.png)

**Comment by klonos** [comment]
> If existing, default search blocks are supposed to lose their title, then this still needs work. If not then this seems to work as expected.

The goal is to leave existing sites as is, so that's expected 👍

**Comment by jenlampton** [comment]
> Applied patch, cleared caches: homepage search block still has title (is this expected?)

Yes, this provides BC for sites that already exist and are using the block title. jynx to @klonos :) thank you

> Does this mean that we're not supposed to test this in the Sandbox and that we should install the parent branch of this PR for testing?

This should still work in the sandbox. The first time you add a search block to a layout (leaving all settings in the block-add-form untouched) there should be no title on the search block. Screenshot of sandbox result:
<img width="1276" alt="Screen Shot 2020-09-03 at 7 05 39 PM" src="https://user-images.githubusercontent.com/397895/92191393-866ae680-ee18-11ea-9bbf-78929037b1f2.png">

**Comment by klonos** [comment]
I'm for this change 👍 ...but comparing the screenshot above from the PR sandbox to the screenshots in the issue summary, the search field and the button now seem as though "disjoined". Things could be better if there was a subtle border around the search block, or if the search button was "attached" to the field, or at least inline with it 🤔

**Comment by BWPanda** [comment]
I see @klonos' point. Would it be too far of a stretch to convert the blue 'Search' button to a magnifying-glass icon and position it, right-aligned, inside the search box?

**Comment by jenlampton** [comment]
> Would it be too far of a stretch to convert the blue 'Search' button to a magnifying-glass icon and position it, right-aligned, inside the search box?

I think we have an issue for that too? Searching...

**Comment by jenlampton** [comment]
> I think we have an issue for that too?

Nope, I was thinking of https://github.com/backdrop/backdrop-issues/issues/3095 

I am in support of this, but it would affect existing sites without [supplemental css](https://github.com/backdrop/backdrop-issues/issues/4512)

**Comment by indigoxela** [comment]
> Would it be too far of a stretch to convert the blue 'Search' button to a magnifying-glass icon and position it, right-aligned, inside the search box?

Possibly.

Here's [example code](https://github.com/backdrop-contrib/pelerine/blob/1.x-1.x/css/component/search.css) from a contrib theme that makes the search box a "search bar".

![searchbar](https://user-images.githubusercontent.com/842066/94235098-4d9bca00-ff0b-11ea-8658-dcb70d40dc10.png)

> but it would affect existing sites without supplemental css

Yeah, that's a good point. It could interfere with subthemes of Basis that implemented something similar.

**Comment by klonos** [comment]
Well, I don't want to derail this, so we can commit the change, and then have a follow-up to add options to the search block, similar to those that we have for the menu blocks re the menu "style":

![image](https://user-images.githubusercontent.com/2423362/94328158-c73dc180-ffb8-11ea-9f96-11a7340a3058.png)

**Comment by jenlampton** [comment]
Oooooh I like it :)

**Comment by klonos** [comment]
> Oooooh I like it :)

Follow-up created here: #4652 ...so to not hold this back 😉

**Comment by klonos** [comment]
> ...the search field and the button now seem as though "disjoined".

To wrap this up, how does everyone feel about adding some placeholder text by default, which would make a mental connection between the search field and the search button? Something like this perhaps?:

![image](https://user-images.githubusercontent.com/2423362/94362652-9303f700-00c5-11eb-8558-3ff2b47ece3b.png)

**Comment by herbdool** [comment]
@klonos seems like scope creep - create a new issue?

**Comment by klonos** [comment]
@herbdool if you look at the before/after screenshots in the issue summary, you'll see that there existed some placeholder text in the search field. The initial proposal was to change this:

![image](https://user-images.githubusercontent.com/2423362/94485493-ac509480-01e6-11eb-8d83-77f232d4172d.png)

...to this (remove the block title):

![image](https://user-images.githubusercontent.com/2423362/94485523-ba061a00-01e6-11eb-84a8-ff444a304931.png)

But the changes in the PR change the default to this instead:

![image](https://user-images.githubusercontent.com/2423362/94485584-d73ae880-01e6-11eb-869d-09cb75b7a248.png)

So we've removed the field label, and the placeholder text. This has caused the two elements to not have any visual indication of being a single thing, which personally I see as a UX regression. We should either bring back the field label, or the placeholder text.

**Comment by jenlampton** [comment]
> So we've removed the field label, and the placeholder text. 

The placeholder text removal was not intentional. This still NW

**Comment by docwilmot** [comment]
I cant see any problem with this? All issues seem to have been fixed AFAICT. And tests are passing without conflict. I'm going to RTBC it.

**Comment by laryn** [comment]
Thanks @jenlampton, @quicksketch, @herbdool, @docwilmot, @BWPanda, and @klonos! Merged https://github.com/backdrop/backdrop/pull/2470 into 1.x and 1.19.x.

Just think of all the time we'll save now, not having to update this milestone anymore! :stuck_out_tongue_winking_eye:

**Comment by klonos** [comment]
> Just think of all the time we'll save now, not having to update this milestone anymore! 😜

What a ride this has been! 😅
