### ISSUE TITLE
Seven table row hover color doesn't appear for sorted columns

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3477]
**Describe the bug**

When hovering over table rows that have been sorted, the yellow hover indicator does not appear on the column with the sort indicator. 

**Steps To Reproduce**
To reproduce the behavior:
1. Visit the DBlog page: admin/reports/dblog
2. Hover over any table row
3. Notice the "Date" column does not change colors.

**Actual behavior**
the "Date" column does not change colors.

**Expected behavior**
the "Date" column should change colors.

This was noticed / brought to our attention in https://github.com/backdrop/backdrop-issues/issues/3471

---
Milestone candidate added for 1.11.4

---
PR: https://github.com/backdrop/backdrop/pull/2471

**Comment by klonos** [comment]
LGTM 👍...I concur for the 1.11.4 milestone.

**Comment by quicksketch** [comment]
Thanks, merged into 1.x and 1.11.x!
