### ISSUE TITLE
Improve handling of theme configuration files

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#3478]
Currently, there are 2 problems with the way theme config is handled in core. First, the theme config files (and the color module files for that theme) are not removed when a theme is disabled. The second is that `system_config_info()` is not properly checking if the theme has settings that need to be handled by config which causes subthemes where the settings come from the base theme to not import correctly.

---
PR by @hosef: https://github.com/backdrop/backdrop/pull/2477

**Comment by herbdool** [comment]
The PR looks though haven't tried it. Will people expect to lose their settings if they disable the theme? Perhaps it makes sense since people can have multiple themes enabled.

**Comment by herbdool** [comment]
I tested disabling a theme. It deleted all the config but it didn't remove the file. I think this needs more work to address the bug.

**Comment by hosef** [comment]
Which theme were you using?

**Comment by herbdool** [comment]
I tested on the test site here with Bartik

**Comment by herbdool** [comment]
Based on my testing I put it back to NW but comments on the PR suggests it fixes the bug.

If my expectation that the config file is removed if theme disabled and not just emptied, then this needs a tiny bit more work. Otherwise I'd be happy to label it RTBC.

**Comment by hosef** [comment]
@herbdool I think I figured out what is going on.
The system module was still register the config objects even if the theme was disabled and the files were deleted, which caused them to show up in the import/export UI.

I pushed a new commit that should fix this.

**Comment by herbdool** [comment]
Works for me now.

**Comment by quicksketch** [comment]
Thanks these are great things to get fixed. The code looks good but we need tests to cover the functionality to ensure it doesn't break again in the future. Thanks (and welcome!) to @SummittDweller who also tested the PR. :smile:

**Comment by hosef** [comment]
There is now a test in the PR that checks that config files are created when a theme is enabled and has settings and removed when it is disabled.

**Comment by herbdool** [comment]
Looks good to me.

**Comment by klonos** [comment]
@herbdool 1.12.1 is already out 😄

**Comment by docwilmot** [comment]
> Or maybe we need a new uninstall action for themes so we keep the same language as modules enable/disable/uninstall

Or maybe its time for https://github.com/backdrop/backdrop-issues/issues/131

> If need be the two fixes in this PR could be treated separately if we don't want to remove theme config when disabling.

Agreed

**Comment by herbdool** [comment]
It's not clear in #131 if a theme is inactive that all its settings are still there or wiped out. Given that the thread is mostly taking about UI changes I assume the status quo for settings. So we still might want to either confirm when disabling/switching that the user understands all settings will be deleted or add an uninstall option.

**Comment by quicksketch** [comment]
Seems like we can merge this as-is, but we need a follow-up to indicate that disabling a theme also resets its settings.

**Comment by klonos** [comment]
@quicksketch ^^ : #3533 😉

**Comment by quicksketch** [comment]
With that concern separated out I've merged https://github.com/backdrop/backdrop/pull/2477 into 1.x and 1.12.x. Thanks to @hosef, @SummittDweller, @herbdool, @docwilmot, and @klonos!

**Comment by klonos** [comment]
...have also filed #3535 so that this is properly discussed:

>Or maybe we need a new uninstall action for themes so we keep the same language as modules enable/disable/uninstall
