### ISSUE TITLE
Recoverable fatal error: Argument 1 passed to file_usage_add() must be an instance of File, boolean given

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3484]
**Describe the bug**

Fatal error occurs when image in rich-text area is not able to be saved.

**Steps To Reproduce**

1. Create a post on site A with an embedded image.
2. Edit the post, copy all text and the image.
3. Create a post on site B, paste in the text from site A, where the image file exists.
4. Save the node on site B, where there is no image.
5. See the fatal error.

**Actual behavior**

I got a "An unexpected error..." message, and this was logged in the dblog 👎:

```
Recoverable fatal error: Argument 1 passed to file_usage_add() must be an instance
of File, boolean given, called in /www/core/modules/filter/filter.module on line
1700 and defined in file_usage_add() (line 684 of /www/core/includes/file.inc).
```

**Ohter oddities that happened**

The content gets created without a pretty, pathauto-generated URL 👎 ...but can be edited to enable "Generate automatic URL alias" and re-save. Then the content gets a pretty URL, no errors 👍

**Expected behavior**

Perhaps an error letting the user know that their image could not be saved, but the rest of the post should save as usual.

**Comment by klonos** [comment]
I can now consistently reproduce this on b.org when trying to create a blog post 😞

...the content is created with no pathauto-generated URL, but you can edit it, enable the "Generate automatic URL alias" setting and save again, which works without any errors.

**Comment by jenlampton** [comment]
I'm also ran into this problem on api.backdropcms.org, but only when copy/pasting in an image tag from b.org. So essentially, if the file does already exist on disk, the node cannot be saved. 

@klonos I expect there was a problem with the file upload that was supposed to happen "by drag-n-drop". Did you try this in different browsers? I wonder if it was a one-time problem or happens consistently.

**Comment by indigoxela** [comment]
The lines in code have changed in the meantime, but looking at [the relevant function code](https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/filter/filter.module#L1756) makes me think that we should improve the logic.

Currently file_usage_add() is called regardless of a successful file_load().

**Comment by indigoxela** [comment]
It should be noted that I'm unable to reproduce the fatal error. Everything works fine even if I try to upload the same image into the same node again.

So please provide the steps for a vanilla install.

**Comment by jenlampton** [comment]
I have updated the Steps To Reproduce in the Original Post. In order to ensure that the image cannot be saved (to create the fatal error) try using one from a different website.

**Comment by indigoxela** [comment]
Yes, now I can reproduce it! The essential thing is that no file with the fid exists on that other site. So file_load returns false. Got it.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3335) is available for testing and review.

How to test:

1. Open a node form
2. Paste in below HTML code (in editor source mode)
3. Save

Before the PR this throws an error. With this PR the node saves smoothly.
Note: the file still doesn't exist, so it won't "display".

Copy/paste:
```
<p><img alt="" data-file-id="555" height="678" src="/files/field/image/foobar.png" width="960" /></p>
```

**Comment by klonos** [comment]
Code looks good ...I just need to test this a bit more thoroughly before adding the WFM label.

**Comment by klonos** [comment]
OK, this works as expected 👍

**Comment by BWPanda** [comment]
Thanks @klonos for reporting this, @indigoxela for the PR and @jenlampton for helping test. I've merged https://github.com/backdrop/backdrop/pull/3335 into 1.x and 1.17.x.
