### ISSUE TITLE
Update hook message in taxonomy.install is inaccurate

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3487]
**Describe the bug**
Message for `taxonomy_update_1006` says: "Add langcode, ttid, translate columns to {taxonomy_term_data} table." but actually it only adds langcode.

**Steps To Reproduce**
Update to Backdrop 1.12.1.

**Actual behavior**
"Add langcode, ttid, translate columns to {taxonomy_term_data} table."

**Expected behavior**
"Add langcode column to {taxonomy_term_data} table."

---
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2481

**Comment by klonos** [comment]
RTBC 👍

**Comment by quicksketch** [comment]
Thanks! Merged in https://github.com/backdrop/backdrop/pull/2481 into 1.x and 1.12.x.
