### ISSUE TITLE
Restore definitions of variables $v_version and $v_magic in Archive_Tar

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#3492]
*Describe the bug**

After creating backup of entire site with Backup and Migrate 1.x-1.0.14 I see the following messages:

Notice: Undefined variable: v_magic in Archive_Tar->_writeLongHeader() (line 1650 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1651 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_magic in Archive_Tar->_writeLongHeader() (line 1650 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1651 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_magic in Archive_Tar->_writeLongHeader() (line 1650 of /home/mebcom/public_html/core/modules/system/system.tar.inc).
Notice: Undefined variable: v_version in Archive_Tar->_writeLongHeader() (line 1651 of /home/mebcom/public_html/core/modules/system/system.tar.inc).

and so on - enfless list of the same notices.

**Steps To Reproduce**
To reproduce the behavior:
1. Go to Backup and select Entire site
2. Click on 'Backup Mow'
3. Scroll down to Same page with backup report

But on the SAVED BACKUPS Backup file is created and can be downloaded.

I have not seen such messages with previous versions of Backdrop. I changed PHP version of hosting account from 7.2 to 7.1 then to 5.6 and than again to 7.2 but the messages stay again.

**Actual behavior**
Describe what was the result of following the steps above. Add screenshots if
you think they would help.

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version:
- Web server and its version:
- Operating System and its version:
- Browser(s) and their versions:

----- 
PR https://github.com/backdrop/backdrop/pull/4441

**Comment by amilenkov** [comment]
Appendix: I tested the same on several other sites as new-created, outright with 1.12.1, and with ones that are upgrading ftom older versions (from 1.11.3). The same error messages are received in all cases. For site with the 1.11.3 version with the exact same configuration as a set of modules, the same server and the same version of PHP does not have such error messages. Once I upgrade to 1.12.1 the messages appear without any other configuration changes.

**Comment by klonos** [comment]
...I believe that the regression is from https://github.com/backdrop/backdrop/pull/2480 (recent Drupal security fixes)

**Comment by amilenkov** [comment]
Update: 

These warnings appear only with backup Entire site. There are no such warnings if you backup only DB or Public Files Directory. 

But of all three type of backups (Public Files Directory, Default database, Entire site) when go to SAVED BACKUPS only Entire site backup file be downloaded, Public Files Directory and Default database backup CANNOT be downloaded from SAVED BACKUPS.

Restoring from  SAVED BACKUPS 
Restore of Default Database - works OK.
Restore of Public Files Directory - works OK
Restore of Entire Site (code, files & DB) - dozens of warnings like:

Warning: mkdir(): No such file or directory in _backup_migrate_move_files() (line 80 of /home/mebcom/public_html/modules/backup_migrate/includes/files.inc).
Warning: mkdir(): Permission denied in _backup_migrate_move_files() (line 80 of /home/mebcom/public_html/modules/backup_migrate/includes/files.inc).
Warning: rename(/home/mebcom/private/temp/backup_migrate_5c45eaa2540b9/docroot//files/README.md,/files/README.md): No such file or directory in _backup_migrate_move_files() (line 89 of /home/mebcom/public_html/modules/backup_migrate/includes/files.inc). (I post here only some of first warnings)

but finally stays OK text:
Entire Site (code, files & DB) restored from Manual Backups Directory file xxx-2019-01-21T17-28-58.sitearchive in 7 sec.

So, you can hide warnings by /admin/config/development/logging - but problems with downloading backups remain. There is something wrong.

Note: this site is very simple - only basic installation and two web pages:

**Comment by jenlampton** [comment]
no PR here yet, so removing milestone.

**Comment by argiepiano** [comment]
The issue was also [reported](https://github.com/backdrop-contrib/backup_migrate/issues/75) more recently in the `backup_migrate` issue queue. 

The problem here is simple to spot. Both variable definitions `$v_version` and `$v_magic` were removed  (by mistake) from method `Archive_Tar::_writeLongHeader()` in [this PR](https://github.com/backdrop/backdrop/pull/2480/files). This PR was created as a cross port of some security updates from Drupal 7.62 - however, if you look at [that D7 PR](https://git.drupalcode.org/project/drupal/-/commit/617d1cefac0f8ff927a8bef072c280436533dc0a#af3663a19e35d8da9df9de8c9c42c6335748134d_1642_1644), those two variables are still defined in that method  - they were moved a bit higher. So, the person who did the cross-port missed that.

The solution is to add those two definitions. PR coming.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4441 ready for review and testing.

**Comment by klonos** [comment]
Thanks @argiepiano 🙏🏼  ...I've reviewed the code changes and they seem reasonable 👍🏼 

As per our recent discussion in the previous dev meeting, I'm removing the "needs code review" label, however not adding the RTBC tag, which can be added once the PR has been tested.

@amilenkov sorry for taking so long to come back to this. Do you still have capacity to test this?

**Comment by argiepiano** [comment]
Based on testing done by @nattywebdev in the actual [PR - see comment](https://github.com/backdrop/backdrop/pull/4441#issuecomment-1561472673), I'm marking this as "WFM"

**Comment by klonos** [comment]
Thanks @nattywebdev 🙏🏼 ...and since I have reviewed the code, this is RTBC then.

**Comment by quicksketch** [comment]
Thanks @argiepiano! I merged https://github.com/backdrop/backdrop/pull/4441 into 1.x and 1.25.x.

Thanks @amilenkov and @nattywebdev for reporting and testing the fixes! I've added both of you to the docs & organization team on GitHub, which will allow you to assign labels and edit issues.
