### ISSUE TITLE
PHP warnings caused by views classes

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3493]
**Describe the bug**
My error log is flodded with PHP warnings after upgrading to Backdrop 1.12.1:
```
Warning: strtr(): The second argument is not an array in backdrop_clean_css_identifier() (line 4134 of backdrop/core/includes/common.inc).
```

**Steps To Reproduce**
1) create a LIST style view
2) add a wrapper class
3) add a list class
4) save the view

<img width="495" alt="screen shot 2019-01-31 at 3 11 10 pm" src="https://user-images.githubusercontent.com/397895/52091815-8898ff00-256a-11e9-9580-982981091048.png">

**Actual behavior**
PHP notices

**Expected behavior**
no PHP notices

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version: 1.12

---
PR: https://github.com/backdrop/backdrop/pull/2495

**Comment by opi** [comment]
Issue is not with the `$identifier` but with the `$filter` (2nd arg).

We need to figure out where is the call to `backdrop_clean_css_identifier` with a non-array filter.

**Comment by jenlampton** [comment]
My guess so that these are all coming from views, since it started in 1.12.

But we shouldn't be running the function if we don't need to.

**Comment by jenlampton** [comment]
I'm seeing this on backdropcms.org, but not sure I see it on other sites yet. Will keep an eye out, but removing milestone since it may be site-specific.

**Comment by jenlampton** [comment]
I've located the code that doesn't pass the correct second parameter. PR for review: https://github.com/backdrop/backdrop/pull/2495

**Comment by findlabnet** [comment]
@jenlampton thanks for fix, see my comment for PR.

**Comment by opi** [comment]
Thanks !

**Comment by quicksketch** [comment]
Thanks @jenlampton, @opi, and @findlabnet! Merged https://github.com/backdrop/backdrop/pull/2495 into 1.x and 1.12.x!
