### ISSUE TITLE
[UX] The node edit form "horizontal tabs" mode doesn't work

### ISSUE THREAD

**Issue by sthomen** [backdrop/backdrop-issues#3497]
The node edit form lets you create fieldsets presented as horizontal tabs, this does not seem to work at all.

![tabs1](https://user-images.githubusercontent.com/1172760/51678505-3e9d9f80-1fe5-11e9-9e68-8ffa50512714.png)

![tabs2](https://user-images.githubusercontent.com/1172760/51678509-40676300-1fe5-11e9-8ac3-bb7c13a904a8.png)

**Comment by olafgrabienski** [comment]
Are the horizontal tabs provided by the [Field group](https://github.com/backdrop-contrib/field_group) module? (I'm not aware that they're part of Backdrop core.)

**Comment by sthomen** [comment]
Hm, yes, I you're right.
