### ISSUE TITLE
[Views] [multilingual] Titles of views in blocks cannot be translated

### ISSUE THREAD

**Issue by sthomen** [backdrop/backdrop-issues#3498]
It's (as far as I can make out) impossible to translate the titles of views in blocks.

**Additional information**
- Backdrop CMS version:
1.12.x

**Comment by olafgrabienski** [comment]
IIRC, Views titles will be made translatable via configuration translation, cf. issue [Identify translatable strings in core config files](https://github.com/backdrop/backdrop-issues/issues/3455).

I guess in the meantime they can be translated with a workaround -- maybe a variation of [this one](https://github.com/backdrop/backdrop-issues/issues/1748#issuecomment-201356335), mentioned in an issue about Views page translation.

**Comment by herbdool** [comment]
This was never a feature of core Backdrop so marking this as new feature rather than bug.

**Comment by sthomen** [comment]
Thanks for the hints, the multiple blocks idea will work of course. I guess the thing I'm really itching for is configuration translation, it would make so many problems go away :-)

Should I close this ticket or keep it as a feature request if it will be solved by configuration translation?

**Comment by indigoxela** [comment]
> It's (as far as I can make out) impossible to translate the titles of views in blocks.

For the records: this has been fixed in Backdrop 1.16.3 (https://github.com/backdrop/backdrop-issues/issues/4382).

Titles and (unfiltered) text are translatable again with the Locale module - as they were in D7.

Feel free to re-open this issue in case something's still missing.
