### ISSUE TITLE
[UX] DBlog: error rows do not have hover color

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3502]
This issue was brought up in https://github.com/backdrop/backdrop-issues/issues/3471#issuecomment-453778564, but was dismissed at that time as moot:

>>> Light/dark error rows do not have a hover color like the rest of the info/warning rows.
>>
>>Do they need to? The hover color is to help people navigate the same row all the way across. Doesn't the red/pink color solve that problem?
>
>Your are absolutely right 👍

That was then based on the assumption that there will usually be a couple of error rows amidst the rest of the gray rows, in which case there indeed seems to be no issue:

<img width="1233" alt="screen shot 2019-01-12 at 12 17 48 am" src="https://user-images.githubusercontent.com/397895/51071022-8bee3a00-15ff-11e9-9daa-23d14b2557e0.png">

...but when there are many consecutive error rows, this does become a UX issue:

<img width="1180" alt="screen shot 2019-01-26 at 11 01 35 am" src="https://user-images.githubusercontent.com/2423362/51779159-cd332d80-2159-11e9-857a-4b03f4a0eec2.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2487

**Comment by klonos** [comment]
4-liner PR up for review: https://github.com/backdrop/backdrop/pull/2487

@jenlampton not sure whether bugs also need to go through the milestone candidate process, or they can automatically be assigned to next bug release?

**Comment by klonos** [comment]
...while at it, I have noticed that the select fields within the "FILTER LOG MESSAGES" fieldset were missing some bottom padding, and that the LTR CSS code had [a duplicate/extraneous entry for `margin`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/dblog/css/dblog.css#L10) (all margins were defined 2 rows above). I fixed those small bits in this PR too, but please let me know if you'd prefer a separate PR for it.

Before:

<img width="676" alt="screen shot 2019-01-26 at 12 19 00 pm" src="https://user-images.githubusercontent.com/2423362/51780712-d4ac0400-2164-11e9-826b-f9fdb4690e09.png">

After:

<img width="693" alt="screen shot 2019-01-26 at 12 19 13 pm" src="https://user-images.githubusercontent.com/2423362/51780713-d7a6f480-2164-11e9-933d-bfa09cd2eccd.png">

**Comment by jenlampton** [comment]
We decided this wasn't necessary in the other issue. What changed?

**Comment by klonos** [comment]
@jenlampton see issue summary where I already explain. ...most common scenario is that there would be only a few errors scattered here and there in the log, so this would be fine. But when there are many repeated errors (for example failure to install multiple modules due to #3488), and especially when the user filters the dblog to show only errors, then it is hard to distinguish which line is for what (see screenshot also in issue summary).

**Comment by herbdool** [comment]
RTBC, tho not clear if there's consensus. I think the hover change is simple enough and might help.

**Comment by jenlampton** [comment]
Yes, we have consensus, the explanation was clear... I just needed to read it through. :)

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2487 into 1.x and 1.12.x. Thanks!
