### ISSUE TITLE
"Aggregation of Javascript and CSS files is disabled." ...but it's actually not

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3503]
**Describe the bug**
There must be some flaw in the logic that detects this, because my CSS is being aggregated, but I still get this:

<img width="626" alt="screen shot 2019-01-26 at 11 07 04 am" src="https://user-images.githubusercontent.com/2423362/51779295-8d207a80-215a-11e9-8e23-cd0364480fed.png">

**Steps To Reproduce**
This is a basic/vanilla installation, so I do not have any specific STR here.

**Actual behavior**
The "Aggregation of Javascript and CSS files is disabled." warning is shown, while the respective checkboxes for CSS/JS aggregation are ticked + disabled (user cannot click to untick these options) 👎. So the user cannot disable aggregation via the UI.

Workaround: edit the `system.core.json` file, and change the `preprocess_css` and `preprocess_css` entries' value from `1` to `0` to disable; set back to `1` to reenable.

**Expected behavior**
Public directory permissions should be properly detected, so that these checkboxes are not disabled in the UI. The user should not have to edit config files to enable/disable aggregation.

**Additional information**
I am using https://github.com/beetboxvm/beetbox for my local dev. Not sure if this has something to do with it.

**Comment by klonos** [comment]
@serundeputy I would appreciate you help and any pointers on this one.

...I initially thought that a quick fix would be to never disable these checkboxes, but then again if we did that, we'd be giving false expectations to users in cases where aggregation does not actually work. I think it'd be best to solve the flow in the logic instead.

**Comment by BWPanda** [comment]
@klonos Does this still happen for you?

**Comment by klonos** [comment]
I have since switched to Lando, so this does not happen any longer. Let's close this until it becomes an issue for someone else too. Then we can revisit.
