### ISSUE TITLE
CKEditor configuration: Toolbar icons broken in RTL

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3504]
**Steps To Reproduce**
1. Enable the core Language module and add a RTL language (such as Hebrew or Arabic).
2. Make the RTL language the default.
3. Navigate to Configuration >> Content authoring >> Text editors and formats and click on the "CONFIGURE" operation for the _Filtered HTML_ format (which uses CKEditor)...

**Actual behavior**
Most of the toolbar icons are broken:

![screen shot 2019-01-27 at 11 23 55 am](https://user-images.githubusercontent.com/2423362/51794387-194ba400-2226-11e9-9fb1-4ee13c37291b.png)

...swhich back to a LTR language -> icons are shown.

**Expected behavior**
Icons should not be broken in RTL languages.

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/2526~~
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2558

**Comment by jenlampton** [comment]
no PR here, bumbing to 1.12.3

**Comment by klonos** [comment]
Initial PR up for review: https://github.com/backdrop/backdrop/pull/2526 ...only addresses the rendering of the button icons. Will follow-up for RTL CSS. Gotta run...

**Comment by klonos** [comment]
...here's what the current status is in the PR sandbox:

<img width="1198" alt="screen shot 2019-03-08 at 9 59 00 am" src="https://user-images.githubusercontent.com/2423362/53995335-d831a280-4188-11e9-962c-9f8ac0adb368.png">

So, the button icons are fixed, but the padding/margin is off. I have found that the offending CSS is this: https://github.com/backdrop/backdrop/blob/1.x/core/themes/seven/css/seven.base.css#L129

```css
[dir="rtl"] ul,
[dir="rtl"] .block ul,
[dir="rtl"] .item-list ul {
  margin: 0.25em 1.5em 0.25em 0;
}
```

I have tried overriding it in `ckeditor.admin.css`, but could not get it to work, so any help appreciated. Thanks.

**Comment by jenlampton** [comment]
@klonos I think I fixed it! PR could use a second test:
https://github.com/backdrop/backdrop-issues/issues/3504
<img width="1308" alt="Screen Shot 2019-03-28 at 4 38 44 PM" src="https://user-images.githubusercontent.com/397895/55199637-f0895180-5177-11e9-90fe-e182f1f2193d.png">

**Comment by klonos** [comment]
Almost there @jenlampton 👍 ...here's how the LTR version of that section looks with another row of icons added:

<img width="1177" alt="Screen Shot 2019-04-01 at 3 14 18 am" src="https://user-images.githubusercontent.com/2423362/55291631-5998ef80-542c-11e9-8333-4e600e6031a9.png">

...and here's the same in your PR, in RTL:

<img width="1177" alt="Screen Shot 2019-04-01 at 3 14 48 am" src="https://user-images.githubusercontent.com/2423362/55291632-61f12a80-542c-11e9-9a2f-b8de6410fe12.png">

So:

- the row add/remove controls (+/-) need some attention. Filed a PR against yours that fixes this: https://github.com/jenlampton/backdrop/pull/6

- the margin added to `.ckeditor-active-toolbar-configuration` is still being overridden by the margin added to `[dir="rtl"] ul, [dir="rtl"] .block ul, [dir="rtl"] .item-list ul` in `seven.base.css` 😓

**Comment by klonos** [comment]
...finally!!! I have update my PR against yours @jenlampton. Turns out that some paddings/margins needed to be set for `[dir="rtl"]` explicitly.

**Comment by klonos** [comment]
Hey @shabibalm 👋 ...care to test https://github.com/backdrop/backdrop/pull/2558 and let us know if things work as expected? Thanks.

**Comment by klonos** [comment]
@jenlampton turns out that one of the changes I proposed was a bit too excessive:

<img width="1194" alt="Screen Shot 2019-04-08 at 1 15 46 am" src="https://user-images.githubusercontent.com/2423362/55685643-ddf2f180-599b-11e9-9be4-683e493698d6.png">

Fixed that with: https://github.com/jenlampton/backdrop/pull/7

**Comment by shabibalm** [comment]
Problem 
`[dir="rtl"] .ckeditor-button {
  padding: 0;
  margin: 0;
}`
That's perfect https://github.com/jenlampton/backdrop/pull/7/files

**Comment by klonos** [comment]
Thanks for merging my PR @jenlampton 👍 ...I have cleared caches in the PR sandbox, and things work as expected now! 🎉

**Comment by stpaultim** [comment]
When I try it the icons are all still lining up on the left side. I think that they should be lining up on the right side. 

I just opened the test site and tried editing "Your first post."

![Edit_Post_Your_first_post____PR_2558_backdrop_backdrop_testing_site_and_Gitter](https://user-images.githubusercontent.com/3144571/56835398-baec8c80-6839-11e9-98cb-f580db109116.png)

**Comment by shabibalm** [comment]
the Problem with firefox

**Comment by klonos** [comment]
>I just opened the test site and tried editing "Your first post"...

@stpaultim I think I may have mentioned this over Gitter, but this issue and PR is about fixing RTL in the CKEditor configuration form; not the CKEditor instances themselves. You need to test things in this admin page in the PR sandbox: http://2558.backdrop.backdrop.qa.backdropcms.org/admin/config/content/formats/filtered_html

**Comment by olafgrabienski** [comment]
I've had a look at the sandbox site, seems to works for me (not an expert regarding RTL). Here a visual comparison of LTR to RTL:

**Left to right:**
![screen-backdrop-pr-2558-ltr](https://user-images.githubusercontent.com/14188307/57766737-312d3200-7708-11e9-84e9-54db62afc625.png)

**Right to left:**
![screen-backdrop-pr-2558-rtl](https://user-images.githubusercontent.com/14188307/57766738-312d3200-7708-11e9-92b0-b5be8012c919.png)

**Comment by jenlampton** [comment]
There's an unresolved comment on the PR from the code review, the hard-coded link needs to be restored (the use of theme_image and theme_link removed). I'll take a stab at that so we can get this in today.

**Comment by quicksketch** [comment]
Looks great. Thanks @klonos, @jenlampton, @shabibalm, @stpaultim, and @olafgrabienski! Merged into 1.x and 1.12.x.
