### ISSUE TITLE
[UX] Move the translation settings for content types to its own vertical tab

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3505]
These settings do not belong in that section, and it seems to confuse non-Drupal/Backdrop users. This was mentioned before, but I could not find any existing issue for it, so here it is...

Before:

![screen shot 2019-01-27 at 1 26 37 pm](https://user-images.githubusercontent.com/2423362/51795479-34271400-2238-11e9-8641-341df172f38a.png)

After:

![screen shot 2019-01-27 at 1 35 45 pm](https://user-images.githubusercontent.com/2423362/51795509-80725400-2238-11e9-9944-18f6da4ee07b.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2490

**Comment by klonos** [comment]
Initial PR up for review: https://github.com/backdrop/backdrop/pull/2490

Todo: add js for the "Multilingual support" vertical tab summary.

**Comment by olafgrabienski** [comment]
@klonos Looks good in the sandbox site so far. (As you say, the vertical tab summary text is missing.)

**Comment by herbdool** [comment]
Looks like the vertical tab summary is there now. I tested and think it looks good. @klonos also changed the order of some other tabs so just wanted to make that explicit on this issue. I'm indifferent to the order.

**Comment by klonos** [comment]
> Looks like the vertical tab summary is there now.

Yep, sorry I failed to communicate that here 😅 

> @klonos also changed the order of some other tabs so just wanted to make that explicit on this issue. I'm indifferent to the order.

Just wanted to clarify that the actual order of the tabs in the UI was not changed. What I have done is this:

- Added in-code comments at the start of each tab section
- Reordered **the code sections** of the tabs, so that these match the order of the tabs in the UI (makes it easier for find one's way around the long form function 😉)
- Renumbered the weights of the tabs so that they use increments of 5. This should make it easier and more future-proof for contrib to inject tabs in the right place with form overrides.

Suggesting 1.12.4 for milestone since this is a UX task. Failing that, then 1.13.0 please. Thanks.

**Comment by quicksketch** [comment]
Code-wise https://github.com/backdrop/backdrop/pull/2490 looks great! And I agree, I can NEVER remember where the multilingual settings are after enabling the various translation modules. Sometimes I double or triple check that I turned on the modules. Search the admin bar, etc. This helps tremendously.

This has the potential for contrib/custom module breakage if they are modifying this form (as the node module did). I don't think we guarantee the order of FormAPI elements stays constant, but this at least needs to wait until 1.13.0.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2490 into 1.x for 1.13.0. Thanks @klonos, @olafgrabienski, and @herbdool!
