### ISSUE TITLE
Notice when not declaring `#type = 'markup'`

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3512]
According to the docs, we don't need to declare `#type = 'markup'`, but apparently in Paragraphs we're getting an undefined index error unless we add that. 
https://github.com/backdrop-contrib/paragraphs/issues/29

**Steps To Reproduce**

> I have a Paragraphs field set to use buttons, with no default values so it starts out with no paragraphs. When I am looking at the node creation form, if I click on the Add Paragraph button, and then the Remove button, I get an error:

>> Notice: Undefined index: #type in form_process_actions() (line 3369 of /mypath/www/core/includes/form.inc).

> It's complaining about the 'remove_button' item that's just #markup value. If you add '#type' as "markup", the error goes away.

**Actual behavior**
Notice given when not declaring `#type = 'markup'`

**Expected behavior**
No error given, since docs state it is not necessary to declare this (the default option).

--
PR by @bradbulger - https://github.com/backdrop/backdrop/pull/2494

**Comment by laryn** [comment]
Looks good to me, thanks @bradbulger.

**Comment by quicksketch** [comment]
Looks great to me also, thanks @bradbulger and @laryn! Merged https://github.com/backdrop/backdrop/pull/2494 into 1.x an 1.12.x.
