### ISSUE TITLE
CKEditor: image caption removes link class

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3519]
The "Add a caption" functionality of the CKEditor image dialog removes CSS classes of linked images.

**Steps To Reproduce**
1. Create or edit a post, add an image via the dialog in CKEditor.
2. In the image dialog, tick the option "Add a caption", and insert the image.
3. Enter some image caption text below the image.
4. Add a link to the image, e.g. using the link dialog, and add a CSS class to the link.
5. Look at the source code, the link has a class:
`<a class="my-class" href="/my-path"><img alt="My image" data-caption="My caption" src="/files/inline-images/my-image.jpg" /></a>`
6. Save the post. Look at the generated code.

**Actual behavior**
After saving the post, the link class has been removed:
```
<figure class="caption caption-a">
<a href="/my-path"><img alt="My image" src="/files/inline-images/my-image.jpg"></a>
<figcaption>My caption"</figcaption>
</figure>
```

**Expected behavior**
The link class should be kept.

**Additional information**
I stumbled about this with the `colorbox-load` class, which means that Colorbox doesn't work on images with a caption. The class removal happens however with any class on a link that surrounds an image with a caption.

Backdrop CMS version: 1.12.x

---

PR by @ksthomas: https://github.com/backdrop/backdrop/pull/2525

**Comment by herbdool** [comment]
I can confirm the class on the link tag stays with this patch. Though even without the patch the class on the link stays.

I don't understand the example in the Actual Behaviour. It doesn't look like my tests and looks quite different from the before. How did it get coverted to using <fig>? Something weird going on the examples above that I can't replicate

**Comment by olafgrabienski** [comment]
@ksthomas Thanks for making the PR! (And sorry for answering late, I didn't get a notice about the PR; it seems that Github sends notices about issue comments but not about related PRs to me.)

I've had a look at the sandbox site of the PR and have created a [test post](http://2525.backdrop.backdrop.qa.backdropcms.org/posts/test-post) where the link class of an image with caption is kept. Looks good to me! (Hoping that someone else will review the code.)

**Comment by olafgrabienski** [comment]
@herbdool Thanks for your testing! Did you have a look at the HTML code in Firebug or another browser dev tool after saving the post? Here is a comparison:

**With the PR, link class is kept**, see http://2525.backdrop.backdrop.qa.backdropcms.org/posts/test-post:

```
<figure class="caption caption-a">
  <a class="my-class" href="https://www.example.com">
    <img alt="Dummy image" data-file-id="3" height="200" src="/files/inline-images/dummy_300.png" width="300">
  </a>
  <figcaption>Figure: Dummy Image</figcaption>
</figure>
```

**Without the PR, link class is removed:**

```
<figure class="caption caption-a">
  <a href="https://www.example.com">
    <img alt="Dummy image" data-file-id="1" height="200" src="/files/inline-images/dummy_300.png" width="300">
  </a>
  <figcaption>Figure: Dummy Image</figcaption>
</figure>
```

I'm currently on a vacation and have no test site at hand, so I've used the sandbox site of *another* (not related) recent PR for the comparison, see http://2509.backdrop.backdrop.qa.backdropcms.org/posts/test-post.

Re the weird conversion, do you ask about the addition of the elements `figure` and `figcaption`? These elements aren't visible in CKEditor source code mode but only in the generated HTML, after saving the node. I don't know the details but it looks like the checkbox "Add a caption" generates a `data-caption` attribute in CKEditor which is then converted somehow to the `figure` / `figcaption` code.

**Comment by olafgrabienski** [comment]
Added the "milestone candidate" tag. I'd be happy if the fix would be shipped with the next bugfix release.

**Comment by herbdool** [comment]
Thanks for explaining @olafgrabienski. I was comparing the ckeditor source. I see it now. I don't fully understand the code but it does seem to have done the trick.

**Comment by klonos** [comment]
I second the suggestion for the milestone, so setting it for 1.12.4

**Comment by quicksketch** [comment]
This seems to make sense to me. Given the confirmations here and code seems fine, I've merged this into 1.x and 1.12.x.

**Comment by quicksketch** [comment]
Thanks @ksthomas for the PR! Merged https://github.com/backdrop/backdrop/pull/2525.
