### ISSUE TITLE
[UX] "Add another item" buttons are hard to distinguish from the field label

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3520]
This was reported by @bradbulger in #3516 along with other, related issues. Separating it to its own issue here:

> These started as comments from a client, I largely agree though. The overall point is that once the content types get to a certain level of complexity, the node forms begin to look awkward in the default Seven styles. Buttons and other elements that are there for the user to perform some kind of action aren't always easy to see and tell what they are.
>
>For instance, on a text field with unlimited values, the "ADD ANOTHER ITEM" button is the same size, shape, and color as the field title. ... If you have several of these fields in a form, it gets confusing visually.

![screen shot 2019-02-01 at 4 08 13 pm](https://user-images.githubusercontent.com/1234634/52156505-61f7c880-263d-11e9-9df1-a99e0c8ad329.png)

D8 for comparison:
![screen shot 2019-02-01 at 4 07 40 pm](https://user-images.githubusercontent.com/1234634/52156533-86ec3b80-263d-11e9-9b33-f161f8691c0a.png)

**Comment by klonos** [comment]
Not a designer or much of an artistic person, but I gave it a go using some of the colors in the palette we already use elsewhere (first button is hover, second normal):

<img width="575" alt="screen shot 2019-02-03 at 6 21 12 pm" src="https://user-images.githubusercontent.com/2423362/52174124-986f4800-27e3-11e9-9b7f-a846a9a16fd7.png">

---

<img width="566" alt="screen shot 2019-02-03 at 6 27 54 pm" src="https://user-images.githubusercontent.com/2423362/52174129-a91fbe00-27e3-11e9-8ea8-9a9cd5eddfd2.png">

---

<img width="567" alt="screen shot 2019-02-03 at 6 31 20 pm" src="https://user-images.githubusercontent.com/2423362/52174131-b341bc80-27e3-11e9-98a9-fcda64822053.png">

What do you think? Improved a bit?

**Comment by oadaeh** [comment]
I agree with Laryn.
We have a site we use, and when I'm blowing through one of the forms, not paying close attention, I frequently click that button instead of the one I actually want.
I also think it would help if the button were "indented" in the form a bit, like maybe set the left edge of the button at the same level as the first character of the field's title.

**Comment by klonos** [comment]
OK, mockup time...

No caps:

<img width="582" alt="screen shot 2019-02-06 at 10 14 55 am" src="https://user-images.githubusercontent.com/2423362/52310725-84e8fa80-29f8-11e9-8349-ad9981d4ccc9.png">

...reduced button size:

<img width="569" alt="screen shot 2019-02-06 at 10 17 37 am" src="https://user-images.githubusercontent.com/2423362/52310754-9cc07e80-29f8-11e9-836b-2833de1f1a9d.png">

...or even:

<img width="801" alt="screen shot 2019-02-06 at 10 09 43 am" src="https://user-images.githubusercontent.com/2423362/52310411-6d5d4200-29f7-11e9-99aa-5f8a6bac2dda.png">

**Comment by klonos** [comment]
...or this if we want to keep the original `#CFDE56` color on hover:

<img width="564" alt="screen shot 2019-02-06 at 10 32 12 am" src="https://user-images.githubusercontent.com/2423362/52311267-83b8cd00-29fa-11e9-8cb7-933ca17fbfdd.png">

**Comment by olafgrabienski** [comment]
Thanks for all the mockups, @klonos!

At first sight, the "or even" version with the `+` prefix looks very promising, but I'm not sure if we use this pattern somewhere else. However, if we want to use it, it would be helpful if the mouse cursor would change to `pointer`.

Another, more simple idea which looks also good in my opinion: leave button color as is, no text-transform, more indentation, i.e. alignment with the inputs. Here's a mockup screenshot:

![screen-backdrop-node-form-add-another-item-idea](https://user-images.githubusercontent.com/14188307/52356891-63f2ca80-2a35-11e9-8818-37a682b62165.png)

**Comment by klonos** [comment]
> ...the "or even" version with the `+` prefix looks very promising, but I'm not sure if we use this pattern somewhere else.

We are using `+ Add xyz` links at the top-left of pages like:

- "+ Add content" in `/admin/content`
- "+ Add user account" in `/admin/people`
- "+ Add content type" in `/admin/structure/types`
- "+ Add custom block" in `/admin/structure/block`
- "+ Add layout" in `/admin/structure/layouts`
...the list goes on and on.

The difference is that these links in these pages open a new page with a form, which allows the user to add xyz. These "Add another item" buttons on the other hand insert new elements in the form in an AJAXy way, without redirections and page loads.

> ...leave button color as is, no text-transform, more indentation

I am fine with more indentation if others agree, but aligning the button vertically with the left edge of the fields seems that will only work for standard, non-nested fields (have not actually tested - only assuming).

Anyway, the main concern in the initial issue report is that these buttons are hard to distinguish because they have the same background color and the same height as the table header of the multiple elements container. So a color change is required IMO.

The secondary concern raised later is that these buttons are large and their capitalised text gives them too much prominence (whereas that should be left for the main form submit buttons, at the bottom of the form). So, removing the caps was one step, and then reducing their size was an additional change in an effort to reduce prominence further.

There another 2 issues with these things btw:

- The action of these buttons is triggered even on right click. Tis sooo annoying.
- There is no "Remove item" button/link (#2917)

**Comment by klonos** [comment]
...talking about using existing patterns (and taking #2917 into consideration), we have now introduced `+` `-` buttons to the right of list field options:

<img width="743" alt="screen shot 2019-02-07 at 5 04 13 am" src="https://user-images.githubusercontent.com/2423362/52363098-135f8980-2a96-11e9-9160-4f34eb6bda29.png">

...which also has an "Add item" link to the bottom-right of the list.

No matter what we choose, we should aim for consistency.

**Comment by laryn** [comment]
Actually I kind of like the idea of using the options element model, which would remove a bunch of large buttons off the page when you've got multi-value fields. None of the screenshots here show it, but if you have a lot of values in these fields, the "REMOVE" buttons are also quite large and heavy.

**Comment by quicksketch** [comment]
I love the ideas here. Lots of ways we could make this better. One more to add to the pile: If we can make the background of the "Add another item" match that of the table above, it will do a lot to tie the elements together. e.g.

Before:
![image](https://user-images.githubusercontent.com/100206/52510899-b9081b00-2bb2-11e9-9fb1-5a24a705b12d.png)

After:
![image](https://user-images.githubusercontent.com/100206/52510908-bf969280-2bb2-11e9-82c1-78dbf266d9de.png)

These don't take into account other suggested changes, like caps and button color. I'm just talking about the backgrounds in these screenshots.

**Comment by klonos** [comment]
...it seems that something has changed since February, so when you add fields with their cardinality set to unlimited, there are 2 instances created by default instead of one:

![Screen Shot 2019-10-12 at 12 55 16 pm](https://user-images.githubusercontent.com/2423362/66692979-930dba00-ecef-11e9-83e1-e78c8ad9dda1.png)

That's fine, but it would make it harder to make the background color match as @quicksketch suggested in the last comment here, because of the zebra stripping 🤔 

PS: now that #4124 has been brought up, I don't like how these fields are rendered with table headers, which are capitalized. Also 🤔

**Comment by olafgrabienski** [comment]
> That's fine, but it would make it harder to make the background color match as @quicksketch suggested in the last comment here, because of the zebra stripping

Yep! Interestingly, an indentation of `Add another row` without table background color matching looks still okay. I'd suggest to choose a white background then for the `Add` button because white is the background color of the first table row.

**Comment by jenlampton** [comment]
I love this approach! if we can extend the white table background it will make the button belong with the rows of items above. 

I like it aligned right, or aligned with the left side of the input above, both of those are better than aligned all the way to the left like it is now.

I also prefer the "Ghost button" style (white background, gray border, gray text) but I think we should soften the border so that it matches the input borders above.

**Comment by jenlampton** [comment]
@klonos pointed out that the description text wasn't getting the intended style, so I've fixed that (and some other code cleanup he pointed out - thank you). Posting a recent screenshot: 
<img width="736" alt="Screen Shot 2021-08-28 at 12 02 35 PM" src="https://user-images.githubusercontent.com/397895/131228216-da8cb2af-fdcf-4414-8ce2-ebfd242e5d86.png">

**Comment by stpaultim** [comment]
My thoughts on this issue are. 
1) The original problem is not obvious to me, but I can understand from other peoples comments how these buttons might not be visually distinct enough. 
2) It seems to me that the most recent PR by @jenlampton is an improvement and I'm fine with it. 
3) This issue isn't very urgent to me personally, but I'm happy with the change and support it.

**Comment by jenlampton** [comment]
> It seems to me that the most recent PR by @jenlampton is an improvement and I'm fine with it.

I also think it's an improvement, but we can do more if people still aren't happy with it.

> The secondary concern raised later is that these buttons are large and their capitalised text gives them too much prominence (whereas that should be left for the main form submit buttons, at the bottom of the form). So, removing the caps was one step, and then reducing their size was an additional change in an effort to reduce prominence further.

When I removed the all-capps button-like appearance from this one button, I really struggled with this button looking different form all the others within the form. For example, compare the Add another item button to the `Select existing file` button in this screenshot: 

<img width="1206" alt="Screen Shot 2021-08-28 at 2 23 56 PM" src="https://user-images.githubusercontent.com/397895/131231383-c408725d-d1c3-4dc1-adfd-4f83c9192275.png">

So I ended up changing the CSS to affect all submit buttons within `.form-item` divs:

<img width="1237" alt="Screen Shot 2021-08-28 at 2 29 39 PM" src="https://user-images.githubusercontent.com/397895/131231490-08acd52f-6ab8-461f-8932-64cc2091a0ad.png">

**Comment by klonos** [comment]
The situation is much better now, and the vertical alignment of the buttons with the fields helps a lot. The buttons do not resemble the table headers 👍🏼

Having said that, using gray shades makes the buttons seem kinda "dull" and perhaps still easy to "miss".

I think that a more vivid color would help. I hope that this side by side screenshot helps see what I mean:

![image](https://user-images.githubusercontent.com/2423362/131232247-3ce56a02-b386-4f29-b7dd-785b74c3de0a.png)

(I picked `#0074bd` for lack of any other suggestion, and because it's already in the palette of color we use in Seven - other suggestions welcomed of course)

**Comment by jenlampton** [comment]
I like the blue text! 
I wonder if the blue border doesn't still give the element too much emphasis? What if we started with a gray border, and then the hover/focus was blue?

No hover:
<img width="1203" alt="Screen Shot 2021-08-28 at 4 10 57 PM" src="https://user-images.githubusercontent.com/397895/131233177-bb20a1f2-96c4-476c-8524-1711b4e0c2a1.png">

Hover:
<img width="1218" alt="Screen Shot 2021-08-28 at 4 11 06 PM" src="https://user-images.githubusercontent.com/397895/131233180-6d306f1f-cb68-4661-a9bb-95f2c87769af.png">

**Comment by olafgrabienski** [comment]
I've had a look at the PR's sandbox, works for me! And agreed, the button shouldn't be given too much emphasis.

I've also left a small comment at https://github.com/backdrop/backdrop/pull/3697#discussion_r697914797.

**Comment by klonos** [comment]
That works for me too @jenlampton 👍🏼 

Since you were the one to initially bring this up, I'm interested to find out what you think @bradbulger. If you have time to spare, you can either let us know based on the screenshots provided above, or even better if you can give the PR sandbox a spin.

**Comment by indigoxela** [comment]
Pinging @jenlampton again... a tiny whitespace change...

**Comment by herbdool** [comment]
Has this been checked for accessibility? Is there enough contrast? Seems like @jenlampton's PR might.

**Comment by jenlampton** [comment]
Sorry, I'm a little under water.
If anyone wants to file a PR against my PR, I'll merge it. Or you can steal
it and file a new one! :)

**Comment by olafgrabienski** [comment]
> Is there enough contrast?

@herbdool Which element are you refering to?

**Comment by klonos** [comment]
I've added the fix for that whitespace as a code suggestion, so that a core committer can commit it before merging the PR. Setting this to RTBC.

**Comment by klonos** [comment]
> Has this been checked for accessibility? Is there enough contrast? Seems like @jenlampton's PR might.

Looks good to me (checked using WAVE):

![image](https://user-images.githubusercontent.com/2423362/147844496-12401101-a595-43d6-b9ba-9b855ab64b96.png)

(the missing label thing is a separate issue)

**Comment by laryn** [comment]
@jenlampton Did the PR for this one get closed before it was merged? I think this one: https://github.com/backdrop/backdrop/pull/3697

**Comment by laryn** [comment]
Looks great -- a nice visual improvement. Thanks @jenlampton for the fix, and thanks @klonos for filing (and all the work in the issue itself). Thanks for all the teamwork on this one @herbdool, @indigoxela, @olafgrabienski, @quicksketch, @stpaultim, and @oadaeh. Merged in `1.x` and `1.20.x`.
