### ISSUE TITLE
[UX] Fix RTL table headers

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3523]
Before:

<img width="780" alt="screen shot 2019-02-07 at 5 15 26 am" src="https://user-images.githubusercontent.com/2423362/52363804-bcf34a80-2a97-11e9-8c82-dded38ab3df0.png">

After:

<img width="799" alt="screen shot 2019-02-07 at 5 18 31 am" src="https://user-images.githubusercontent.com/2423362/52363851-dd230980-2a97-11e9-9e3e-ab0750b06ed4.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2500

**Comment by opi** [comment]
nice!

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2500 into 1.x and 1.12.x.
