### ISSUE TITLE
[UX] Fix RTL options element

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3525]
Before (no right padding for the tabledrag handle, "Add item" link to the right):

<img width="1188" alt="screen shot 2019-02-07 at 10 56 53 am" src="https://user-images.githubusercontent.com/2423362/52381908-6b62b400-2ac7-11e9-98f9-592259d97be5.png">

After:

<img width="1173" alt="screen shot 2019-02-07 at 10 58 27 am" src="https://user-images.githubusercontent.com/2423362/52381912-6f8ed180-2ac7-11e9-8c5b-f426e6a2d6e0.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2501

**Comment by klonos** [comment]
...btw, the weirdness with the leading `<` and trailing `>` in the "Allowed HTML tags" help text is a whole separate (preexisting) issue, unrelated to the CSS-only changes made in this PR: #3526

**Comment by opi** [comment]
tested in sandbox, works fine.

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop/backdrop/pull/2501 into 1.x and 1.12.x.
