### ISSUE TITLE
[UX] Drupal's `Admin` module for core?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3527]
1 - put the admin menu on the left and make it expandable to the left with only icons (like grav admin panel do) and maybe give the option to put it on the top (like drupal navbar module do)

This issue was spun off from a comment by @fivepoints79 in 
https://github.com/backdrop/backdrop-issues/issues/495#issuecomment-461456258

**Comment by jenlampton** [comment]
There was a popular module for Drupal called `Admin` that did exactly this. When we decided on a new admin module for Backdrop, we went with admin_menu since that was more popular. I'd love to see an admin module for Backdrop though, for people who liked the menu in the sidebar instead, so https://github.com/backdrop-ops/contrib/issues/319 

Marking this issue as a contrib candidate, as we already have the most popular admin solution in core.

**Comment by klonos** [comment]
@fivepoints79 re docking the admin menu to the left/right, we already have #1842 😉

**Comment by fivepoints79** [comment]
> There was a popular module for Drupal called `Admin` that did exactly this

yes, I've used this module in the past, but I think it's sufficient (at least for me) the navbar module (https://www.drupal.org/project/navbar).

> When we decided on a new admin module for Backdrop, we went with admin_menu since that was more popular.

great choice : )

**Comment by fivepoints79** [comment]
> @fivepoints79 re docking the admin menu to the left/right, we already have #1842 😉

ok, thank you! : )
