### ISSUE TITLE
Indicate that disabling a theme also resets its settings

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3533]
Follow-up to #3478

@quicksketch:

> Seems like we can merge this as-is, but we need a follow-up to indicate that disabling a theme also resets its settings.

@docwilmot:

> This PR makes disabling a theme a destructive process now. For a complex theme that would lose all configuration, this may be unexpected. Should we add a confirm form to theme settings form?

Here it is 😉

------
PR https://github.com/backdrop/backdrop/pull/2507

**Comment by herbdool** [comment]
I created a PR https://github.com/backdrop/backdrop/pull/2507. I took @docwilmot's approach of adding a confirmation form when disabling a theme.

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...PR looks good. I have left some comments.

**Comment by klonos** [comment]
This is RTBC ...I will file a separate issue about the things mentioned in the PR comments.

**Comment by quicksketch** [comment]
Looks good! Merged https://github.com/backdrop/backdrop/pull/2507 into 1.x and 1.12.x. Thanks @herbdool and @klonos!
