### ISSUE TITLE
[UX] Fix RTL in "Manage comments" page (Published/Unapproved comments tabs)

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3534]
problem Published comments+Unapproved comments in page Manage comments with RTL
admin/content/comment

![ux fix rtl page manage comments published comments unapproved comments](https://user-images.githubusercontent.com/45591694/52512166-8262ec80-2c14-11e9-8736-5a36d818a2e0.png)

edite core\modules\system\css\system.theme.css
`[dir="rtl"] ul.secondary li {
  border-right: none;
  display: inline;
  padding: 0 1em;
}`
to 
`[dir="rtl"] ul.secondary li {
  border-right: none;
 display: inline-block;
}`

![ux fix rtl page manage comments published comments unapproved comments -1](https://user-images.githubusercontent.com/45591694/52512869-3ca82300-2c18-11e9-8792-794df01f0b45.png)

I am very sorry not reply because I am busy 
thanks

---
PR: https://github.com/backdrop/backdrop/pull/2718

**Comment by quicksketch** [comment]
Thanks @shabibalm! Please continue to file issues as you find them! We included a lot of fixes in 1.12.2 because of you. :smile:

**Comment by shabibalm** [comment]
thanks @quicksketch 
another solution 
just delete display: inline; with rtl 
`[dir="rtl"] ul.secondary li { border-right: none;}`

![backdropcms-comment-rtl](https://user-images.githubusercontent.com/45591694/58751601-3c72b280-84a9-11e9-8210-93f598c18ebd.jpg)

**Comment by klonos** [comment]
...simple, 1-liner PR up for review: https://github.com/backdrop/backdrop/pull/2718

**Comment by quicksketch** [comment]
Thanks everyone! Merged https://github.com/backdrop/backdrop/pull/2718 into 1.x and 1.14.x.
