### ISSUE TITLE
Cannot call entity_create in hook_install

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#3537]
**Describe the bug**
If a module provides a new Entity - that is it implements `hook_entity_info()` and has an implementation of `hook_autoload_info()` to load its classes - then `entity_create()` cannot be called in the `hook_install()` for that same module.

**Steps To Reproduce**
Find any contrib module that implements `hook_entity_info()`, note the id of one of its entities (one of the keys from `hook_entity_info()`), and add `entity_create('the_entity_id', array())` to that module's install file in `hook_install()` 

**Actual behavior**
`Fatal error: Class name must be a valid object or a string in <ROOT>\core\modules\entity\entity.module...`

**Expected behavior**
No error, you should be able to create an instance of your entity in the install file.

**Additional information**
Backdrop 1.13
This error suggests that the classes defined in `hook_entity_info()` are not yet available during `module_enable()`. 

---
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/2506

**Comment by docwilmot** [comment]
Calling `entity_info_cache_clear()` before the `entity_create()` solves this. Incidentally the same error arose if the call is in `hook_disable()` and the same solution works for both. 

@quicksketch should we add `entity_info_cache_clear()` to `module_enable()` and `module_disable()`?

**Comment by klonos** [comment]
> ...should we add `entity_info_cache_clear()` to `module_enable()` and `module_disable()`?

Similar solution was used in issues like #3448 (where we added `menu_cache_clear_all()` in `language_negotiation_configure_url_form_submit()`). I don't see why not.

**Comment by jenlampton** [comment]
Love it, it's a nice, simple fix!

**Comment by quicksketch** [comment]
One more question though, in the code why is `entity_info_cache_clear()` _before_ disabling the module, while all other cache-clearing mechanisms are _after_? See https://github.com/backdrop/backdrop/pull/2506/files#r261467165

**Comment by docwilmot** [comment]
The answer to the (only) question on this PR was already given on the PR issue, so unless there are still questions, I've marked RTBC again

**Comment by quicksketch** [comment]
Great thanks @docwilmot! I just wanted to make sure that wasn't an oversight, seems like the location of the `entity_info_cache_clear()` call was for a reason. Merged https://github.com/backdrop/backdrop/pull/2506 into 1.x and 1.12.x.
