### ISSUE TITLE
[UX] Views: Avoid using the term "automatic updates" in the message about fixed missing relationships.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3542]
When we automatically fix missing relationships for a view, we throw this message:

> This view has been automatically updated to fix missing relationships. While this View should continue to work, you should verify that the automatic updates are correct and save this view.

A few things wrong with this text:

- Since we are planning to get automatic updates in core (#2018), we should avoid using that term here. We can say "configuration changes" instead.
- Too many instances of "this view"
- There is an instance of the word "View" that is capitalised.

We should change this message to something like:

>This view has been automatically configured to fix any missing relationships. It should still continue to work, but you should verify that the automatic configuration changes are correct before saving them.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2509

**Comment by klonos** [comment]
...pinging @jenlampton to chime in. Your words are usually better than mine 😄

**Comment by stpaultim** [comment]
I don't feel strongly about any of this. But some quick feedback to take or leave. 

1) Possibly remove "any" from first sentence unless we can assure that all missing relationships have been fixed. Including "any" suggests that they have all been fixed. Removing "any" leaves open the possibility that some but not all missing relationships may have been fixed. 

2) I would remove "automatic configuration" from the second line. I just don't think it's necessary.

> This view has been automatically configured to fix missing relationships. It should still continue to work, but you should verify that the changes are correct before saving them.

**Comment by klonos** [comment]
Agree on both points @stpaultim 👍 ...I have updated the PR, with the minor change to say "that these changes" instead of "that the changes". Final text is this:

> This view has been automatically configured to fix missing relationships. It should still continue to work, but you should verify that these changes are correct before saving them.

**Comment by jenlampton** [comment]
It still seems quite verbose. How about this?
	
```
Missing relationships have been fixed automatically. This view should continue to work, but please verify these changes before saving.
```

**Comment by klonos** [comment]
Last one seems fine 👍 ...updated the PR.

**Comment by herbdool** [comment]
Looks good

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...setting milestone candidate for 1.12.4

**Comment by quicksketch** [comment]
Looks good to me. Merged into 1.x and 1.12.x.
