### ISSUE TITLE
[UX] Fix RTL password field style

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3543]
Before:

<img width="765" alt="screen shot 2019-02-13 at 3 23 54 pm" src="https://user-images.githubusercontent.com/2423362/52690157-da9d4400-2fb0-11e9-8f65-20b83b3b9252.png">

After:

<img width="657" alt="screen shot 2019-02-13 at 5 00 00 pm" src="https://user-images.githubusercontent.com/2423362/52690164-dec96180-2fb0-11e9-898a-d66a4579b4c3.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2510

**Comment by quicksketch** [comment]
A few comments left on the PR: https://github.com/backdrop/backdrop/pull/2510/files.

**Comment by klonos** [comment]
Thanks @quicksketch ...both comments addressed. Back to NR

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2510 into 1.x and 1.12.x. Thanks @klonos and @herbdool!
