### ISSUE TITLE
Maintenance mode and updates via the UI

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3550]
I believe in D7, when you update a module via the UI, you are prompted to put the site in maintenance mode, and then it automatically comes out of maintenance mode after the download is completed successfully. In Backdrop currently, it remains in maintenance mode until you go to manually turn it off.

---
PR by @laryn: https://github.com/backdrop/backdrop/pull/2515

**Comment by laryn** [comment]
It looks like the intention is to take it out of maintenance mode automatically:

https://github.com/backdrop/backdrop/blob/c9ee437d06b1b9834c33229d3dd92ba9f8a14a14/core/modules/installer/installer.authorize.inc#L204-L210

**Comment by laryn** [comment]
Given the clear intent of the code and the fact that people who want a more extended maintenance mode can simply manually put it into maintenance mode before doing any updates (and it will stay in maintenance mode afterwards), I'm changing this to a bug.

**Comment by olafgrabienski** [comment]
> I believe in D7, when you update a module via the UI, you are prompted to put the site in maintenance mode, and then it automatically comes out of maintenance mode after the download is completed successfully.

Confirming how it works in D7, see screenshot:

![screen-d7-update-manager-out-of-maintenance-mode](https://user-images.githubusercontent.com/14188307/53155982-961c3480-35be-11e9-8280-88e1304800f5.png)

**Comment by serundeputy** [comment]
seems weird to me to take the site out of maintenance mode before you check if things are ok :woman_shrugging: imho.

**Comment by herbdool** [comment]
Looks like a simple fix. I requested a small change @laryn

**Comment by laryn** [comment]
Thanks @herbdool -- good catch.

**Comment by jenlampton** [comment]
Code looks great, and testing showed that my site came out of maint mode :) 
<img width="905" alt="Screen Shot 2020-01-15 at 3 07 43 PM" src="https://user-images.githubusercontent.com/397895/72479247-cd806a80-37a8-11ea-8528-4ef7cd71a450.png">

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2515 into 1.x and 1.14.x. Thanks folks!
