### ISSUE TITLE
[UX] Basis: Fix RTL breadcrumb style

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3554]
this fix Breadcrumb with theme basis
before
![fix-rtl-breadcrumb-styles-theme-basis](https://user-images.githubusercontent.com/45591694/53260257-1d15fd80-36e2-11e9-97d6-7444cdb0d918.jpg)
 after
![fix-rtl-breadcrumb-styles-theme-basis-1](https://user-images.githubusercontent.com/45591694/53260264-20a98480-36e2-11e9-87a9-c65a500c7513.jpg)
edite
core/themes/basis/css/component/breadcrumb.css
add
`[dir="rtl"] .breadcrumb li {
  float: right;
}`
and
`[dir="rtl"] .breadcrumb li:after {
  left: 0;
  right: inherit;
  -webkit-transform:
    translate(0, -50%)
    rotate(220deg);
  transform:
    translate(0, -50%)
    rotate(220deg);
}`

thanks

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2518

**Comment by klonos** [comment]
Thanks for taking the time to report this @shabibalm 👍 ...PR up for review (slightly modified your proposed CSS changes): https://github.com/backdrop/backdrop/pull/2518

**Comment by herbdool** [comment]
@klonos small change needed

**Comment by klonos** [comment]
...thanks. Done! :smile:

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
Thanks @shabibalm, @klonos, and @herbdool! Merged https://github.com/backdrop/backdrop/pull/2518 into 1.x and 1.12.x.
