### ISSUE TITLE
Change "Backing up a site" documentation link

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3556]
**Description of the bug**
Updating a module using the UI, after downloading the module, I see the page *Ready to update* with the message "Back up your database and site before you continue. Learn how." The "Learn how" link points to the page ["Backing up a site"](https://www.drupal.org/node/22281) on drupal.org.

**Steps To Reproduce**
To reproduce the behavior:
1. Use a test site where's an outdated module.
2. Go to the page `admin/modules/update`.
3. Check the outdated module and hit the button "Download these updates".
4. You're on the *Ready to update* page (`admin/update/ready`) with the sentence "Back up your database and site before you continue. Learn how."
5. Click on the link "Learn how".

**Actual behavior**
The link points to the Drupal page "Backing up a site", URL: https://www.drupal.org/node/22281.

**Expected behavior**
The link should point to a page on the Backdrop CMS website, e.g. as part of https://backdropcms.org/user-guide.

----

PR @serundeputy https://github.com/backdrop/backdrop/pull/2981

**Comment by olafgrabienski** [comment]
(I'm not sure if I'm supposed to mark a *documentation* issue also as a bug. Feel free to remove the label.)

**Comment by olafgrabienski** [comment]
Comment by @klonos, copied from https://github.com/backdrop/backdrop-issues/issues/414#issuecomment-431688763:

> I could not find anything in https://backdropcms.org/user-guide, so by all means create a separate documentation issue. We will need to link to it from other pages too, like in update.php, where we say:

>> **Create backups.** This update utility will alter your database and config files. In case of an emergency you may need to revert to a recent backup; make sure you have one.

**Comment by olafgrabienski** [comment]
Hm, I'm not sure if / where to post the actual issue to create the missing documentation page. @klonos?

**Comment by klonos** [comment]
Hey @olafgrabienski ...I think it's a task. And the doc creation request should most likely go here: https://github.com/backdrop-ops/backdropcms.org/issues (tag as `content-documentation`)

**Comment by klonos** [comment]
...here it is: https://github.com/backdrop-ops/backdropcms.org/issues/508

**Comment by olafgrabienski** [comment]
@klonos Thanks for creating the task over there!

**Comment by serundeputy** [comment]
Added the doc page in https://backdropcms.org/node/2585 and PR https://github.com/backdrop/backdrop/pull/2981

@olafgrabienski @klonos one we review and publish the new doc page we can merge this.

**Comment by stpaultim** [comment]
Should we discuss the text for that page here.

I have concerns about this principle (and/or whether or not we're providing sufficient information). 

> It cannot be stressed enough that if a site's data does not exist in three places, it doesn't exist at all.

I understand and admire this principle, but I'm personally not sure I always by it. I think that many people are living without backups at all and getting them to have one solid backup is a step in the right direction. 

If you are a small non-profit with a Backdrop site on GoDaddy (or another shared host). What does this statement mean?

- Does your original database count?
- Does a snapshot of the server count?
- Does a backup and migrate backup into a sub-directory below root (but on the same server) count?
- If someone has a Godaddy account and subscribes to their Backup service - are they doing it wrong, because that's only two places?

I don't think that this is bad advice, but I think it might be confusing to a lot of novice web owners. I think we should either soften this advice a bit OR at least provide better guidance on what it means.

**Comment by serundeputy** [comment]
@stpaultim thanks.

I think we should publish this page sooner than later; then we can open a follow up an bikeshed till our hearts are content, but right now we have nothing.

Softening advice here, like softening on security advice, is a bad idea.

The last thing we want is someone saying i followed b.org recs and now i'm out of luck.
for example:  my site was hacked and i have no trusted backup

that is just one example.  I agree that if they are not backing up at all then an on server backup is better than nothing, but we should not lead them astray.

We can however create some deep link pages that go into more details about using these tools and hosts.

config is in a file somewhere does not matter if it is in the `files/` dir or not it is still a file somewhere.

**Comment by olafgrabienski** [comment]
@serundeputy Thanks for creating the "Backing up a site" page on the Backdrop website! I've also had a look at the page. I agree that we should publish the page soon but I think we can polish it a bit before. Here is my feedback so far:

I don't like the style of the "best practices" section, it sounds quite 'pedagogic'. We could give the same information in a more friendly way. However, that may be a topic for bikeshedding, and in case it's difficult to discuss let's publish it first and improve it later.

From the same section:

> Document and test your backup and restore procedure before you need it. The forum and gitter chat are full of people who want help recovering from some unforeseen fatal error, and if they knew how to restore their site using the backups, they'd created, they would be in business and making money rather than waiting for help from a Backdrop volunteer

This paragraph is *really* unfriendly. The first sentence is okay, but the rest not. It would be better to provide information how to test a backup. (Or let's leave it just at the first sentence, without the rest.)

From the section "Backing up a database":

> The Backup and Migrate module allows you to download backups or save backups on a schedule, though users should stay updated on open, known issues.

In my opinion, we don't need the part about staying updated on known issues. On the Drupal page, that was primarily related to D8 where Backup and Migrate didn't work properly for a long time.

**Comment by stpaultim** [comment]
I'm in favor of publishing and then improving. I was providing feedback, not suggesting that we need to settle these issues before publishing.

**Comment by serundeputy** [comment]
@olafgrabienski @stpaultim either/both of you up for testing the PR sandbox and putting this in RTBC or needs work if that is the case?

thanks.

**Comment by olafgrabienski** [comment]
@serundeputy I've tested the sandbox site, it works fine!

Apart of content bikeshedding which can happen later, there is one issue which I'd like to get fixed before: The link points to https://backdropcms.org/node/2585. Let's point (or redirect) it to a readable URL like https://backdropcms.org/user-guide/backing-up-a-site. (I've not the permissions to set an URL alias.)

**Comment by serundeputy** [comment]
I'm afraid to point to an alias because if someone changes the alias the link will break ... Thoughts?

**Comment by olafgrabienski** [comment]
@serundeputy AFAIK an alias is fine, at least we've used an alias in a comparable issue. However, in that case we removed `/user-guide` from the path to make sure (or likely) the URL doesn't change, see https://github.com/backdrop/backdrop-issues/issues/3560#issuecomment-481450012 and below. When we use the same pattern here, the URL for the Backup page would be `https://backdropcms.org/backing-up-a-site`.

**Comment by serundeputy** [comment]
@olafgrabienski except for example that is not the path that `pathauto` assigned to the page (https://backdropcms.org/user-guide/backing-site), so someone might change that, i.e. you **think** it should be `backing-up-a-site`, but it is not (pathauto is not configured that way).

So, we need a canonical decision on URL (PMC?) or go with `node/NID`; In the other issue you folks came to consensus; so ... I'll wait.

**Comment by docwilmot** [comment]
Isnt that redirects are for though?

**Comment by olafgrabienski** [comment]
> that is not the path that pathauto assigned to the page

@serundeputy I guess that was (one of) the point(s): a path neither declared by `pathauto` nor within the usual `user-guide` path suggests to other editors that it was set intentionally and therefore shouldn't be changed without asking.

But I understand your caution. And I don't know if there are automatic redirects on URL change. Let's ask @jenlampton!

**Comment by olafgrabienski** [comment]
Re Redirects: still lacking in Backdrop core btw: a redirect from `node/NID` to the aliased content item. (There is a core issue somewhere.) With that feature, we could just use `node/NID` in the PR.

**Comment by serundeputy** [comment]
yeah; if you try to redirect from `node/NID` to `/pathauto-path` it yells that you are about to create an infinite loop :+1: for the warning and not doing that, but I don't know how to solve that as Backdrop uses the `node/NID` paths as canonical.

So, still we need to decide on a path or go with `node/NID`

**Comment by docwilmot** [comment]
> I'm afraid to point to an alias because if someone changes the alias the link will break ... Thoughts?

I mean if we change an alias in the future, then redirect.

**Comment by serundeputy** [comment]
it should automatically redirect when alias is changed, still seems fragile to me.

I'll change it and stop my crying.  Just seems to me like using canonical URL is safest/best.

**Comment by jenlampton** [comment]
We should never link to a node/NID url in anything public. We need an alias. 

> it should automatically redirect when alias is changed, still seems fragile to me.

This is how Backdrop works. If there's ever a problem with it, then we'll fix it. There is no point in not using the tools we have!

**Comment by serundeputy** [comment]
changed the backup node to [`/backups`](https://backdropcms.org/backups) will update the PR to reflect that.

**Comment by serundeputy** [comment]
PR updated https://github.com/backdrop/backdrop/pull/2981 ; @olafgrabienski if you are willing to test again and get this to RTBC i'll

- [ ] publish the /backups page on b.org
- [ ] merge this PR ftw

thanks,

**Comment by olafgrabienski** [comment]
Sure! I've tested the pull request again, the link now points to `https://backdropcms.org/backups`.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/2981 into 1.x and 1.14.x. The alias of backdropcms.org/backups seems good to me, it's similar to other short, permanent aliases we have for things like https://backdropcms.org/requirements or https://backdropcms.org/installation

I published that page on backdropcms.org. Any site editors, please update that page as needed.

**Comment by olafgrabienski** [comment]
Follow-up: https://github.com/backdrop-ops/backdropcms.org/issues/508#issuecomment-571641124
