### ISSUE TITLE
[DX] Consolidate the warning about theme_debug being enabled in a single place

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3558]
This is a (belated) follow-up to #1052...

We currently repeat the same code twice in core:

- https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.admin.inc#L107
- https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.admin.inc#L376

...and contrib has no way to (re)use this. It would be better I think if that was in a single function that we call wherever required. Another plus is that if this needs to be changed for whatever reason in the future, then we'd only need to do it in a single place.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2521

**Comment by opi** [comment]
Minor feedback on PR, but RTBC anyway

**Comment by quicksketch** [comment]
Makes sense but I have a concern over starting a function with the word `theme_` because of it's special mean in Backdrop. https://github.com/backdrop/backdrop/pull/2521/files#r261466210

**Comment by klonos** [comment]
Responded in the PR with a question as to where to move the actual function.

**Comment by klonos** [comment]
PR updated to move the function to system.module.

**Comment by klonos** [comment]
This is a fairly small and straight-forward change. I suggest 1.12.5 for milestone. If not, then 1.13.0

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2521 into 1.x. As this isn't user facing and isn't fixing a bug, I'm leaving this for 1.13.0 only.
