### ISSUE TITLE
Switch the translation links in the installer from drupal.org to backdropcms.org

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3560]
- [x] Create a documentation page about installing Backdrop in different languages
  Separate issue: https://github.com/backdrop-ops/backdropcms.org/issues/523
- [ ] Switch the documentation link from drupal.org to backdropcms.org
- [ ] Switch the translation link from localize.drupal.org to localize.backdropcms.org

---

PR by @olafgrabienski: https://github.com/backdrop/backdrop/pull/2571

**Comment by olafgrabienski** [comment]
Reminder: identify all the links to localize.drupal.org. I'm not sure if it's only in the installer or also somewhere in the language related pages of the admin interface.

**Comment by olafgrabienski** [comment]
There are two drupal.org related lines in `core/includes/install.core.inc`:

**Download link, l. 1355:**
`$output .= '<li>Download a translation from the <a href="http://localize.drupal.org/download" target="_blank">translation server</a>.</li>';`

**Documentation link, l. 1358:**
`$output .= '<p>For more information on installing Backdrop in different languages, visit the <a href="http://drupal.org/localize" target="_blank">drupal.org handbook page</a>.</p>';`

I'm going to update the title and issue description to include also the documentation part.

**Comment by olafgrabienski** [comment]
I've made a PR, https://github.com/backdrop/backdrop/pull/2571. It's a two-liner, I hope there's no typo and the wording is fine!

**Comment by klonos** [comment]
The PR looks fine @olafgrabienski 👍 ...thanks 👍 

The actual b.org pages may need some work to bring them in parity with the respective d.org ones though.

**Comment by olafgrabienski** [comment]
Thanks for the review, @klonos! 

> The actual b.org pages may need some work to bring them in parity with the respective d.org ones though.

Yes, the documentation pages need for sure some work. Regarding installing Backdrop in other languages there is https://github.com/backdrop-ops/backdropcms.org/issues/523. (In my opinion, also the main page about installing Backdrop could be improved -- primarily arranged more clearly --, but that's stuff for a separate issue some day.

**Comment by quicksketch** [comment]
This looks great! Those last few drupal.org links are fairly embarrassing at this point, especially as one of them is on the very first page of the installer.

I don't see any actual page at https://backdropcms.org/user-guide/install-backdrop-another-language though. And I didn't see a page for installing Backdrop anywhere in the user guide actually, seems it's actually under "Developer Notes" these days? https://backdropcms.org/installation

IMO we should ensure the URL never changes, so perhaps removing `/user-guide` from the portion of the URL would be smart to future-proof it.

**Comment by olafgrabienski** [comment]
> I don't see any actual page at https://backdropcms.org/user-guide/install-backdrop-another-language though.

Are you sure? I see it.

> And I didn't see a page for installing Backdrop anywhere in the user guide actually, seems it's actually under "Developer Notes" these days? https://backdropcms.org/installation

Yes, that's correct, it's part of the Developer Notes, so removing the `/user-guide` part of the URL -- or replace it by `/installation` -- is a good idea.

(It's however strange not to have information about installing Backdrop in the User Guide.)

> we should ensure the URL never changes

Hoping there are automatic redirects.

**Comment by olafgrabienski** [comment]
@quicksketch As the documentation page isn't part of the PR (but discussed in issue https://github.com/backdrop-ops/backdropcms.org/issues/523), I'm not sure why to remove the `pr works ...` label. What the PR does (changing the documentation link and the translation server link), is still working, so it actually doesn't need work.

But yes, it needs documentation ... or clarification at which URL the documentation should live.

**Comment by olafgrabienski** [comment]
> What the PR does (changing the documentation link and the translation server link), is still working, so it actually doesn't need work, in my opinion.

Oh, sorry, got it: I have to change the documentation link in the PR when we have a new URL!

**Comment by klonos** [comment]
>> I don't see any actual page at backdropcms.org/user-guide/install-backdrop-another-language though.
>
>Are you sure? I see it.

Yep, I see it too. I have checked all the b.org links in the PR.

**Comment by klonos** [comment]
...I personally don't mind the `/user-guide` in the URL. I know that for some "popular" documentation pages we have removed it, but so long that these pages live in the user guide, and since URL redirects work, we can have both in place. Let's use the shorter version in the PR though 😉

**Comment by olafgrabienski** [comment]
@klonos Thanks for your feedback! I'll change the URL in the PR to use the shorter version when the URL of the documentation page is changed, cf. https://github.com/backdrop-ops/backdropcms.org/issues/523#issuecomment-481696206.

**Comment by jenlampton** [comment]
I've updated the URL of the other page to https://backdropcms.org/installing-in-other-languages. Does that work?

**Comment by olafgrabienski** [comment]
> I've updated the URL of the other page to https://backdropcms.org/installing-in-other-languages.

Thanks! I've also updated the documentation URL in the PR. @klonos Can you have another look at it?

**Comment by klonos** [comment]
PR still looks good 👍 ...lets get rid of as many remaining d.org links in the codebase as possible; we can improve on the actual documentation pages on b.org iteratively.

**Comment by olafgrabienski** [comment]
To merge this PR, it makes sense to also have #3674 in the same release. The PR over there allows to use .po translation files from b.org in the installer without having to rename them before.

**Comment by quicksketch** [comment]
Looks great! I posted some feedback on #3674, but this one is good to go. Nice new handbook page and thank you for making a "permanent" URL that isn't dependent on the structure backdropcms.org. Merged https://github.com/backdrop/backdrop/pull/2571 into 1.x and 1.12.x. Thanks @olafgrabienski, @jenlampton, and @klonos!
