### ISSUE TITLE
[UX] Add a recent news block to the dashboard

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3566]
FROM: https://github.com/backdrop/backdrop-issues/issues/495

Issue Summary updated June 25 (up to this comment: https://github.com/backdrop/backdrop-issues/issues/3566#issuecomment-505559367)

# Problem/Motivation

Add a "Backdrop CMS News" block on the new admin dashboard for Backdrop CMS.

# Proposed resolution

1) Generate a JSON feed from BackdropCMS.org with news items
2) Display that feed in core block added to the Dashboard module

There was discussion about making this block flexible and providing users with a UI option to switch out other JSON feeds for the BackdropCMS feed. We opened another issue for that idea: https://github.com/backdrop/backdrop-issues/issues/3891

# Remaining tasks

* We have a patch that adds a block to the Dashboard. It's currently using a UI configured sample feed. Current thought is that we hard-code a single JSON feed into the block, or possibly provide 2-3 options (provided by BackdropCMS.org) and allow users to select which of them they wish to display. PR: https://github.com/backdrop/backdrop/pull/2751
* Set up a JSON feed of content (for a Recent News block in core). SEE: https://github.com/backdrop-ops/backdropcms.org/issues/560

The focus for this issue right now is probably on getting a JSON feed setup on BackdropCMS.org

# Original Issue

I'd love to see a News block on the dashboard that pulls in the latest news items from http://backdropcms.org/news. 

In order to do this we'll need to generate a feed of data from backdropcms.org, and ingest the feed in backdrop core. There is currently no mechanism for ingesting feeds in core, so this will need to be addressed in this ticket.

Ideas for things we can put in the news feed:
* Links to recent (important) blog posts
* Information about pre-releases for minor version
* Links to polls to get feedback from our non-GitHub userbase.

-----

Advocate: @stpaultim 

~PR by @serundeputy: https://github.com/backdrop/backdrop/pull/2751~
PR by @stpaultim (Almost the same as the above by @serundeputy) - https://github.com/backdrop/backdrop/pull/3026

**Comment by BWPanda** [comment]
As an alternative to infesting feeds in core, what about setting up a plain page elsewhere that shows the feed items, then creating a block in core that displays this in an iFrame (or whatever the modern equivalent is)?

**Comment by stpaultim** [comment]
As I entered a sandbox site and was taken immediately to the dashboard, it occurred to me how nice it would be if there were a default block there that had important updates from backdropcms.org. 

To me, this would be an important core feature for the Backdrop project as a whole. We need to make it easy to get news and information from Backdrop CMS project. I think it's reasonable to have simple and non-intrusive block with this information on the dashboard by default. It would be easy to turn it off, reconfigure it, or move it. 

I'm wondering what the current thoughts are on putting this in core? 
This feels like a project I could advocate for. 

I've heard discussion about idea before, but I'm surprised that there is not more discussion here. Is there another related issue.

**Comment by klonos** [comment]
Yep, there are discussions about this now and then; and I am sure that it will be done eventually. We just need someone to work on it 😄 

I have recently mentioned on Gitter how I ind it very cool how certain software present what's new after each release/update for example. Here's how they do it on Slack:

![Screen Shot 2019-06-13 at 6 23 32 pm](https://user-images.githubusercontent.com/2423362/59887022-01f39a00-9405-11e9-8f48-709f35745e6d.png)

![Screen Shot 2019-06-18 at 12 55 50 pm](https://user-images.githubusercontent.com/2423362/59887030-07e97b00-9405-11e9-86ea-a409a5bc40cc.png)

![Screen Shot 2019-06-18 at 12 56 08 pm](https://user-images.githubusercontent.com/2423362/59887038-0d46c580-9405-11e9-95a4-4f30021af597.png)

**Comment by jenlampton** [comment]
>  what about setting up a plain page elsewhere that shows the feed items, then creating a block in core that displays this in an iFrame (or whatever the modern equivalent is)?

This is an interesting idea. I wonder if we could pull something in with javascript?

**Comment by serundeputy** [comment]
The [headless](https://github.com/backdrop-contrib/headless) module can expose a view (among other things) as json data.

So, one possible architecture is:

  * Install headless module on backdropcms.org
  * Create view on backdropcms.org (of the intended dashboard content)
  * Expose view on /admin/config/services/headless
  * Create a block in backdrop/backdrop to consume the view json and output it

So the only addition to core would be a block in code.

**Comment by jenlampton** [comment]
I don't think we need the headless module. Why not just a views json
display, if that's all we need?

**Comment by serundeputy** [comment]
> Why not just a views json
display, if that's all we need?

I did not know about this! I just jumped in to make a view, but I don't see a views json display option. How does one make a view that is a json display?

**Comment by klonos** [comment]
I thought that you need something like https://www.drupal.org/project/views_datasource

**Comment by docwilmot** [comment]
This is a great idea. How would we provide the feed though? It would probably be one news item at a time, maybe sometimes two. Maybe different types of items, to be consumed by different blocks? A way to tag an item as a "top" item? And would these be dismissable on the block?

I think a View makes sense, but we'd need some way to push the View result to clients. We could also just create a single endpoint that serves the `json_encode()`ed View results.

Or it could even be RSS?

**Comment by jenlampton** [comment]
With RSS, we already have the generator in views on b.org, so wouldn't need anything to create the feed, but we would need to add an RSS parser to core to ingest the RSS (maybe something from Aggregator module).

With JSON we'd need to add [a contrib module(https://github.com/backdrop/backdrop-issues/issues/3566#issuecomment-504538047) to b.org to generate the feed, but we could use PHP's native parsing in [a new block](https://github.com/backdrop/backdrop-issues/issues/3566#issuecomment-504363093) that ingests the feed.

My preference would be for a messy b.org rather than a messy core, so I'd vote for JSON.

> It would probably be one news item at a time, maybe sometimes two. 

I think we should limit it to one -- at least for now.

> Maybe different types of items, to be consumed by different blocks?

This is a good idea in the long run, but I'd like to start with a single "announcement" type item made specifically for this purpose. 

> And would these be dismissable on the block?

This could be a follow-up item too, but for now let's just get the block onto the dashboard (by default). For those who don't to see Annoucnements, they can remove the block.

**Comment by serundeputy** [comment]
> I think a View makes sense, but we'd need some way to push the View result to clients. We could also just create a single endpoint that serves the json_encode()ed View results.

this is exactly what the [headless module](https://github.com/backdrop/backdrop-issues/issues/3566#issuecomment-504363093) does.

**Comment by jenlampton** [comment]
We don't need the headless module on b.org. A views display type on its own is enough. 

I was thinking that we might want to revive the `views_json` namespace since that Drupal module is abandoned. We could pull the views display type from any one of the other modules that has it. 

(My motivation for getting it out of something that does a bunch of other stuff we don't want is that I secretly think that this (a display type on its own) might end up being a reasonable and non-offensive candidate for core. However, I want it to live in contrib first so we can get an accurate sense of usage, first.)

**Comment by docwilmot** [comment]
> this is exactly what the headless module does.

Good point.
@jenlampton I'm not understanding your meaning in the last post, are you suggesting creating a custom module that serves the View as JSON?

**Comment by jenlampton** [comment]
A contrib module, something suitable for core.

**Comment by klonos** [comment]
Here's another idea for the news block:

- new contrib modules (could be a weekly or daily thing)
- welcome new contrib group member(s)
- new community spotlight blogs

...basically what we do during the first bit of our weekly dev meeting, only automated.

**Comment by docwilmot** [comment]
> A contrib module, something suitable for core.

Even more confused now.

**Comment by jenlampton** [comment]
Maybe an example will help :) I'll try to write something up (and some docs
to explain it better)

**Comment by serundeputy** [comment]
Once we decide on a way to make a json endpoint getting and rendering the block is trivial:

![image](https://user-images.githubusercontent.com/6763671/59980392-3e6cf480-95c3-11e9-9c1c-3af8552799ef.png)

that pulls from a headless endpoint from my site.

**Comment by klonos** [comment]
@jenlampton any objections on using https://github.com/backdrop-contrib/headless on b.org? It seems to do the job + maintained by a core committer 😉

**Comment by stpaultim** [comment]
> I think we should limit it to one -- at least for now.

I would vote for having more than one item. Maybe 3-4 headlines that link back to backdropcms.org. I think that the block idea that @serundeputy posted looks very reasonable to me. But, hopefully we'll have more descriptive headlines. 

I'm assuming that we would have a special tag for headlines that went to this feed and be careful about what we add.

**Comment by jenlampton** [comment]
> @jenlampton any objections on using backdrop-contrib/headless on b.org?

yes.

**Comment by serundeputy** [comment]
I think maybe there is some confusion about what the `headless` module does, maybe not, but to be perfectly clear. The `headless` module is completely opt-in. So in this case we would opt-in a single view on b.org to expose exactly one json endpoint to be used by backdrop sites to read in the news feed from b.org.

![image](https://user-images.githubusercontent.com/6763671/60016147-568c5480-9653-11e9-8d7d-52e1baa759ca.png)

So we just check off the one box for the one view and that is it.

Any other mechanism of exposing json will also work.

**Comment by jenlampton** [comment]
All the discussion about how to generate a JSON feed on b.org is distracting from how to build the block for the dashboard. We should be talking about it in the b.org queue, where it will eventually be implemented. I copied the conversation [over there](https://github.com/backdrop-ops/backdropcms.org/issues/560) for anyone who wants to join!

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/2751

We'll need to adjust according to what the final json structure ends up being.

**Comment by stpaultim** [comment]
Looking great. Thanks @serundeputy! Is is supposed to link to something more than the raw JSON feed right now? 

I generally like the look of the block. I expect there will be discussion about how much to include there. I'm undecided if I prefer more titles (without any additional descriptions or content) or one or two updates that actually includes a snippet of information.

**Comment by klonos** [comment]
I really like the configurable JSON endpoint 👍 ...this would allow people to customise their sites with different sources. I would like to see a "revert to BackdropCMS news" link/toggle if possible.

**Comment by jenlampton** [comment]
> I really like the configurable JSON endpoint 

I really dislike this. Instead, we should provide human-readable options, like 
1) news feed
2) recent modules
3) something else

We shouldn't allow people to specify a JSON feed in the UI.

**Comment by stpaultim** [comment]
>I really dislike this. Instead, we should provide human-readable options
> We shouldn't allow people to specify a JSON feed in the UI.

I was a bit confused, so let me see if I understand the point you are making @jenlampton.

I assume your point is that this block should be for Backdrop News only and we should NOT allow users to repurpose it for other misc feeds (as I think @klonos was suggesting). Your point is that any configuration should be limited to which type of Backdrop Updates you wish to receive (offered in a human readable list of options)?

SIDE NOTE: I'm interested in a possible CONTRIB module that provides some other possible blocks for the Dashboard. This might be a way to test blocks for future inclusion in core dashboard. Maybe the flexible JSON feed block belongs in CONTRIB?

**Comment by serundeputy** [comment]
> I generally like the look of the block. I expect there will be discussion about how much to include there. I'm undecided if I prefer several titles (without any additional descriptions or content) or one or two updates that actually includes a snippet of information.

  * this will be determined by the content type that ends up on b.org in https://github.com/backdrop-ops/backdropcms.org/issues/560 if it is just tittles than it will look similar to the current implementation, if it is titles + taglines then it will change a little, but probably titles + taglines would just mean 3 to 5 items in the block whereas just titles would probably be something like 5 to 7 items in the block

from gitter:
> I surfaced this issue to see if I should advocate for it in this milestone. But, it may be complete before I get a chance.

  * @stpaultim I think the issue could use an advocate; there are many opinions here and not a definitive spec (i.e. moving target on two apps b.org and backdrop/backdrop proper) we could use direction and a high level wrangling of opinions, options, and ultimately an actionable course of action.  I think you would be a good advocate


from @klonos 
> I really like the configurable JSON endpoint +1 ...this would allow people to customise their sites with different sources. I would like to see a "revert to BackdropCMS news" link/toggle if possible.

  * i did not intend to leave it like this as the site owners could put either non-sense in there that would not work; or put a legit json endpoint, but if the json was not structured exactly like ours (which is TBD) chaos would ensue

> I really dislike this. Instead, we should provide human-readable options,

  * I hadn't thought of this, but totally possible; I was thinking we would hardcode a particular json endpoint (once that is determined from b.org)
    * I think the easiest since we have a lot of moving parts here; is make one content type on b.org with set fields and json structure from the view; and get this completed and rolled out
    * in future iterations we could spin up issue(s) for adding a select list of diff feeds once we have content types and content for them

**Comment by docwilmot** [comment]
> I really dislike this. Instead, we should provide human-readable options, like

Can we combine both? I was expecting that this block could be used by anyone to access any valid json feed. How about allowing changing the endpoint but requiring the feed be structured in a way that the block shows options. 

You enter
`https://json.example-bicycle-news-feed.com`  and click connect and available feeds at that endpoint load:
```
- bicycle news
- helmet info
- rubber and road
```

or
You enter
`https://json.backdropcms.org`  and click connect and available feeds at that endpoint load:
```
- news feed
- recent modules
- something else
```

**Comment by serundeputy** [comment]
that would require that each of these sub-feeds

```
- news feed
- recent modules
- something else
```

match exactly a specification that we (the backdrop community would need to come up with and enforce), i.e. if you meet our json spec; we can add you to the featured news block.

not impossible, but sounds like a future iteration to me.

We don't even have a determined way to provide the feed yet, let alone a prescribed json format.

**Comment by docwilmot** [comment]
What does this mean exactly though? This block will be only able to show feeds from BackdropCMS.org?

**Comment by jenlampton** [comment]
> This block will be only able to show feeds from BackdropCMS.org?

Yes, exactly. This issue is to put important announcements from Backdrop CMS on the dashboard. 

> I was expecting that this block could be used by anyone to access any valid json feed.

I think that should be a separate block / feature request. I don't think we should confuse the two. (And I don't personally think this one is an 80% use-case, perhaps better suited for contrib?)

> that would require that each of these sub-feeds...

Yes, I think 'other lists of things' was mentioned earlier as an idea, but I agree that is out of scope for this issue.

**Comment by serundeputy** [comment]
it could potentially show news from other feeds, but we'd have to tell the feed providers that this is our spec, i.e. we expect this otherwise it will not work/display.

fake spec:

```json
{
  "type": "backdropcms-news-feed",
  "data": {
    {
       "id": HASH,
       "title": "SOME TITLE"
       "tagline": "SOMETAGLINE"
    },
    {
       "id": HASH,
       "title": "SOME TITLE"
       "tagline": "SOMETAGLINE"
    },
    .
    .
    .
  }
}
```

or some format that we decide on and expect.

**Comment by jenlampton** [comment]
> we'd have to tell the feed providers that this is our spec

yep, but if we are the feed providers, that's pretty easy :)

**Comment by serundeputy** [comment]
I definitely agree that scope an priority of this issue should be to deliver a BackdropCMS.org feed to our Backdrop installations.

**Comment by docwilmot** [comment]
Related question: will we hard code the endpoint in code, or as a config setting?

**Comment by serundeputy** [comment]
i think for this iteration hard code it.

**Comment by docwilmot** [comment]
So (spitballing here), if this is a flat feed of items:
```
{
  "type": "backdropcms-news-feed",
  "data": {
    "items": [
      {
         "id": "HASH",
         "title": "SOME TITLE",
         "tagline": "SOMETAGLINE"
      },
      {
         "id": "HASH",
         "title": "SOME TITLE",
         "tagline": "SOMETAGLINE"
      },
      .
      .
      .
    ]
  }
}
```

@jenlampton idea of topics will be not simple. The feed would need to be in some kind of grouping:
```
{
  "type": "backdropcms-news-feed",
  "data": {
    "items": [
      "news_feed": [
        name: News feed
        subitems:
          {
             "id": "HASH",
             "title": "SOME TITLE",
             "tagline": "SOMETAGLINE"
          },
          {
             "id": "HASH",
             "title": "SOME TITLE",
             "tagline": "SOMETAGLINE"
          },
      .
      "recent_modules": [
        name: Recent modules
        subitems:
          {
             "id": "HASH",
             "title": "SOME TITLE",
             "tagline": "SOMETAGLINE"
          },
          {
             "id": "HASH",
             "title": "SOME TITLE",
             "tagline": "SOMETAGLINE"
          },
      .
      .
      .
    ]
  }
}
```

You think?

**Comment by jenlampton** [comment]
I was thinking different feeds, but we can discuss that in the follow-up
issue.

**Comment by serundeputy** [comment]
I agree different feeds and follow up issue.

**Comment by docwilmot** [comment]
> I agree different feeds and follow up issue.

FWIW I'm not against this at all, "enemy of done" and all that, But I don't feel the code for a reusable block that can display a JSON endpoint, not just a hardcoded one, would be that complex that we need to postpone it. I feel it would be more efficient to do it that way now than to have to re-write code later.

**Comment by serundeputy** [comment]
We don't have a specific or the diff datasets yet; so let's focus on delivering the content we have at present

**Comment by jenlampton** [comment]
And there's also not a consensus that something like that belongs in core.
;)

**Comment by docwilmot** [comment]
> And there's also not a consensus that something like that belongs in core.

This is how we build consensus, by encouraging free expression of ideas.
> We don't have a spec or the diff datasets yet; so let's focus on delivering the content we have at present

I don't know what that means, sorry.

**Comment by jenlampton** [comment]
Yes, but in an issue for the new feature, not by shoving it into something
unrelated ;)

**Comment by klonos** [comment]
Yeah, so the point is that we seem to have 2 choices:

1. build a "Backdrop News" block: it makes sense for this to have a hard-coded endpoint.

2. build a generic "JSON consumer" (or whatever name) block, and use that to deliver Backdrop-related content, as an example of what people can do with it.

I initially was excited about the potential option 2 would have, but I was thinking like a "power" site-builder; it does sound like out of scope for core. Besides, we cannot predict what the format of the to-be-consumed JSON will have in all use cases; so it could get messy indeed.

**Comment by stpaultim** [comment]
I added myself as the advocate for this issue. I edited the original issue description (see top of thread) to include an issue summary of where I think the discussion currently stands. Let me know if anyone thinks I got it wrong.

I opened a new issue where we can discuss whether or not there should be a flexible " JSON Consumer" block in core. If we reach some kind of consensus on that need, we can then discuss whether or not it should be combined with this block or be a stand alone block. 
https://github.com/backdrop/backdrop-issues/issues/3891

In my opinion, the focus for this issue is now on providing a feed from BackdropCMS.org. 
SEE: https://github.com/backdrop-ops/backdropcms.org/issues/560

**Comment by klonos** [comment]
Thanks for becoming an advocate @stpaultim ...and for splitting the generic JSON thingy thing to #3891 🙂 👍

**Comment by serundeputy** [comment]
updated PR https://github.com/backdrop/backdrop/pull/2751 with some clean up and production url.

**Comment by klonos** [comment]
@serundeputy PR against yours to add an icon to the block: https://github.com/serundeputy/backdrop/pull/4

I used https://fontawesome.com/icons/bell?style=solid

**Comment by serundeputy** [comment]
I've updated the PR to incorporate @klonos, @docwilmot, and @quicksketch feedback.

**Comment by klonos** [comment]
Thanks @serundeputy 👍 ..it looks almost ready now (apart from that `"url": "https://api.serundeputy.io/api/views/events_past_api"` line in the config file).

Now we need to work on the b.org side of things 🙂

**Comment by serundeputy** [comment]
thanks @klonos I've updated the PR to remove the old test config.
https://github.com/backdrop/backdrop/pull/2751

there are a number of outstanding things to be decided and implemented in https://github.com/backdrop-ops/backdropcms.org/pull/562#issuecomment-507038684 that are blocking work here.

**Comment by quicksketch** [comment]
So after reading through the thread at https://github.com/backdrop-ops/backdropcms.org/pull/562, a summary of what I'd like to see on the backdropcms.org side:

Endpoint at:

https://backdropcms.org/api/notifications

Formatted as:
```
{
  notifications: {
    notification-[nid]: {
      title: "Node title",
      summary: "The notification summary.",
      url: "https://backdropcms.org/news/notification-node-title",
    }
  }
}
```

Like @stpaultim posted in the PR comments, I'd like this to not be exposing direct field names and terminology directly from Backdrop's data structure.

On the backdropcms.org side, setting up the content type like this to match:

Content type: `notification`
Name: Public notification
Description: Notifications are served via an API to the Backdrop News block shown on the default Dashboard for all Backdrop installations.

With the fields `title`, `field_notification_summary`, and `field_notification_url`.

**Comment by klonos** [comment]
For reference, here's what the respective dashboard block in WP looks like:

![Screen Shot 2019-08-25 at 11 46 48 pm](https://user-images.githubusercontent.com/2423362/63655645-63ccd900-c793-11e9-9549-8f29263dcefe.png)

I like the fact that they have a separate "events" type of consumed thingie, which shows events people can attend.

I also think that a [Backdrop external mentions](https://backdropcms.org/news/mentions) should be in this block.

**Comment by quicksketch** [comment]
Preemptively bumping this one to the next version. Without the backdropcms.org feed in place yet we don't have the time to put this together.

**Comment by stpaultim** [comment]
No update for DEV meeting. I keep postponing this issue because other issues attract my attention. We had hoped to address this during infrastructure week, but didn't get there. I will start to focus attention on this before next release. I really want to see this in 1.15

**Comment by stpaultim** [comment]
@quicksketch - How does this look for the feed:

```
{
  "notifications" : [
    {
      "notification" : {
        "title" : "Backdrop version 1.15 has been released",
        "summary" : "Check out some of the new features available. ",
        "url" : "https://backdropcms.org/news/backdrop-113-released"
      }
    },
    {
      "notification" : {
        "title" : "Next Virtual User Group is Jan 7, 2020",
        "summary" : "Join with us as we discuss our favorite contrib modules for Backdrop CMS.",
        "url" : "https://backdropcms.org/news/events/virtual-user-group-contrib-modules"
      }
    },
    {
      "notification" : {
        "title" : "Backdrop CMS is Planning our 5th Birthday Party",
        "summary" : "Check to see if there is a Backdrop CMS birthday party in your local community. ",
        "url" : "https://backdropcms.org/news/its-time-start-planning-your-backdrop-cms-birthday-party"
      }
    }
  ]
}
```

**Comment by jenlampton** [comment]
I deployed @stpaultim's changes last week, but got cold feet about the config sync. I sync'd the view but not the content type since I had thought we already had one on live. We don't so I'm going to complete the sync now :)

**Comment by stpaultim** [comment]
I hacked the PR by @serundeputy and pushed a new one:
https://github.com/backdrop/backdrop/pull/3026

I just need reviews and final comments. Let's be sure to get this into 1.15.0. 

@quicksketch - Did you have any final comments on the json format?

**Comment by stpaultim** [comment]
For the record, there are currently 4 notifications published on backdropcms.org. The most recent three are displaying. 

I unpublished all 4 briefly to test what happens on sites and this was the result. 

![Dashboard___PR_3026_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/71647137-c8ef8880-2cb7-11ea-9e25-7fa66fcd4da7.png)

**Comment by jenlampton** [comment]
I tested the PR and it looks great. I like all the conversations going on in the PR thread, but I don't think any of them should hold up the merge. 

The discussion there is around if we should store the feed URL in config or a constant, and if we should add an additional test for what happens if the results from that URL are something unexpected.

**Comment by quicksketch** [comment]
We need to add a filter_xss() call on the notification contents. Although it's coming from backdropcms.org we don't want to have JS executed from a remote feed under any circumstances. Posted feedback to the PR: https://github.com/backdrop/backdrop/pull/3026

There are a few other things that I think should happen, but can be done in a follow-up:

- The feed URL should come from a config setting in `dashboard.settings.json`.
- We should disable checking for updates at all in all test runs, probably by blanking out that setting in the config file.
- We should add a cache to the HTTP request and update the feed on cron runs rather than doing it on-the-fly.

**Comment by quicksketch** [comment]
@stpaultim has updated the PR as of a few hours ago with the filter_xss() fix now in place on the news summaries. I've merged https://github.com/backdrop/backdrop/pull/3026 into 1.x for 1.15.0. Thanks everyone and especially @stpaultim and @serundeputy for their work on this issue!

We need follow-ups on this one to switch the URL to a config setting and cache the news updates.

**Comment by stpaultim** [comment]
@quicksketch - I assume we can close this now that the followup issue is created. 
https://github.com/backdrop/backdrop-issues/issues/4254
