### ISSUE TITLE
Nested items in draggable tables are dragged in the opposite left/right direction in RTL

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3573]
**Description of the bug**
It seems that we have somehow missed https://www.drupal.org/project/drupal/issues/197641

**Steps To Reproduce**
1. Enable the Language core module
2. Add an RTL language (Arabic or Hebrew for example), and set that as the site default -> this should switch the site to RTL
3. Navigate to a page with some nested draggable items (taxonomy terms or menu items).

**Actual behavior**
Drag an item to the left -> it is dragged to the right 👎 
Drag an item to the right -> it is dragged to the left 👎 

**Expected behavior**
Nested draggable items should be dragged to the correct left/right direction.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2529

**Comment by herbdool** [comment]
@klonos we should also include this https://www.drupal.org/project/drupal/issues/197641#comment-10396111 as commenter noticed an issue with 2 levels deep.

**Comment by herbdool** [comment]
Tested and it looks good. 2+ levels deep.

**Comment by quicksketch** [comment]
Padding here is still a little off:

LTR:
![image](https://user-images.githubusercontent.com/100206/54781020-33cc4900-4be9-11e9-8c5b-2e25bcfd37b5.png)

RTL:
![image](https://user-images.githubusercontent.com/100206/54781049-434b9200-4be9-11e9-892d-96f2f73658fa.png)

Seems like it's the generic padding on `[dir="rtl"] ul` that may be causing the problem. We may need to add `[dir="rtl"] .ckeditor-active-toolbar-configuration { padding: 0; margin: 0; }`. Even though it's not different from RTL to LTR, the specificity of `[dir="rtl"] ul` is winning over the `.ckeditor-active-toolbar-configuration` selector.

**Comment by klonos** [comment]
@quicksketch we know, but this is the wrong issue 😛: #3504

Setting this back to RTBC.

**Comment by quicksketch** [comment]
Oops! I'm sorry! I'll take another look at this one and make sure I'm looking at the right thing. :sweat_smile:

**Comment by quicksketch** [comment]
Okay, now looking at the *right* PR, looks great! Thanks @klonos and @herbdool! Merged https://github.com/backdrop/backdrop/pull/2529 into 1.x and 1.12.x.
