### ISSUE TITLE
Wrong preprocess function listed

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3576]
**Description of the bug**
Wrong preprocess function listed in `page.tpl.php` -- should be `template_preprocess_page` rather than `template_preprocess_html`.

PR: https://github.com/backdrop/backdrop/pull/2514

**Comment by klonos** [comment]
Nice catch @laryn 👍 ...RTBC

**Comment by quicksketch** [comment]
Thanks @laryn, @klonos, and @herbdool! Merged https://github.com/backdrop/backdrop/pull/2514 into 1.x and 1.12.x.
