### ISSUE TITLE
Add 'Reset' button to Modules page

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3581]
**Description of the need**
On the modules page (`/admin/modules`) you can search for modules using the filter field, and whatever you type in here stays when the page reloads (e.g. after enabling/disabling a module). That's good and desired, however it'd also be nice to have a way to quickly reset the filtering to go back to the full module list.

**Proposed solution**
A 'Reset' button should suffice (like the Views exposed form reset option).

----
PR: https://github.com/backdrop/backdrop/pull/2591

**Comment by daggerhart** [comment]
I've updated the PR to align the button with the text field. Screenshot on the PR is updated to reflect this change.

**Comment by daggerhart** [comment]
Updated the PR to include a simple test for both the filtering and the reseting of the filter. The tests assert that the Url is correct after each operation.

Also updated the CSS to better align the button with the filter in both firefox and chrome.

Firefox:
![firefox](https://user-images.githubusercontent.com/1205329/56461340-11ac1f00-637f-11e9-9825-922d4e2f6b00.png)

Chrome:
![Screen Shot 2019-04-20 at 3 12 41 PM](https://user-images.githubusercontent.com/1205329/56461341-183a9680-637f-11e9-9a4f-ae4ecf3a546a.png)

**Comment by serundeputy** [comment]
@daggerhart this is great! thanks for the great work

merged into `1.x` will ship w/ `1.13.0`
