### ISSUE TITLE
Node's `Title` field gets focus regardless of weight

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3583]
**Description of the bug**
I have a content type with the Title field (renamed to 'Description') sitting below other fields (ordered on the `/admin/structure/types/manage/[TYPE]/fields` page). When I go to create content of that type, the title/description field has the focus, even though it's the last/bottom field on the form. This seems weird and undesirable (for my situation).

**Steps To Reproduce**
To reproduce the behavior:
1. Create a new content type
2. Add a few custom fields
3. Arrange the fields so that Title is the last one (i.e. has the highest weight)
4. Create a node of that type

**Actual behavior**
The Title field (at the bottom of the form) has the focus.

**Expected behavior**
The top/first field gets the focus.

**Additional information**
Possible related issue: https://github.com/backdrop/backdrop-issues/issues/2625

**Comment by olafgrabienski** [comment]
Good catch! Looks like we didn't think about custom ordering of node form fields in #2625, where the autofocus attribute was added to the **title** field (of the *Add content* and *Add term* forms), not to the **top** field.

**Comment by indigoxela** [comment]
Another problem: when the node title already has a value (node is not new).

When opening a node form of existing nodes, it's more likely that any of the other fields should get updated (for instance body). The autofocus on the title is pointless or maybe even obstrusive then.

**Comment by laryn** [comment]
Agreed that the autofocus as we added it in #2625 is not working well across the board. (I really like it on the term name field when adding a bunch of terms in a row, but like @BWPanda I've moved the node title around on the node page in many cases and it's strange to have focus jump there)

**Comment by indigoxela** [comment]
The autofocus on terms forms is cool and totally makes sense to me (as long as no fields are attached to terms, though.)
The autofocus on node forms has some negative side effects.

How about that: only set the autofocus attribute on *new* nodes, but skip for later edits?
That's still no solution for re-ordered fields (title below other fields). I'd assume that a site-builder does that by intention (other fields are more important).

**Comment by olafgrabienski** [comment]
> How about that: only set the autofocus attribute on new nodes, but skip for later edits?

Agreed! Actually, it was the intention of #2625 to give focus to the **top** field when **creating** content.

**Comment by indigoxela** [comment]
These bouncing node forms just **drive me crazy**! Let's stop it. A [PR](https://github.com/backdrop/backdrop/pull/3816) is ready for testing and review.

**Comment by indigoxela** [comment]
I'm aware that the initial request was to handle it based on field weight - but even if the bouncing only stops with existing nodes, it's already a big win.

**Comment by olafgrabienski** [comment]
Quickly tested the PR in the sandbox website, works like a charm!

- When you *create* a node, the Title field gets focus.
- When you *edit* a node, Title doesn't get focus.
- Taxonomy terms behave as before (focus in both cases).

> the initial request was to handle it based on field weight ...

Shall we change the issue title and update the issue description (copying the original description below the updated text)?

**Comment by indigoxela** [comment]
> Shall / can we change the issue title and update the description

Some feedback by @BWPanda and @laryn would be helpful re that. What do you two think?

**Comment by BWPanda** [comment]
It kinda feels to me like someone reported a bug, but after a while it still wasn't fixed. So then someone else comes along and says let's do this instead, which doesn't fix the original problem, but since doing something's better than doing nothing, we'll repurpose this issue anyway...

So no, I don't think we should change the title/description of this bug report. I think we should leave it as-is in the hope it'll one day get fixed (I just took a stab but couldn't work out where the code is that arranges the fields according to their specified weight). I think @indigoxela's suggestion/PR should be moved to a new issue where that can be discussed/implemented separate to this issue.

**Comment by indigoxela** [comment]
> I don't think we should change the title/description of this bug report. I think we should leave it as-is in the hope it'll one day get fixed

Fair enough.

@BWPanda would completely **removing** the autofocus from node title form items fix the problem for you? IMO it has been a bad decision, anyway - for **nodes**.

**Comment by laryn** [comment]
I’d support removing it from nodes if @BWPanda  feels that solves his issue here, otherwise a new issue to discuss the two options separately (remove all vs remove on update only)

**Comment by olafgrabienski** [comment]
While the intention of https://github.com/backdrop/backdrop-issues/issues/2625 was to give focus to the **top** field when **creating** content, we have introduced focus on the **title** field when **creating and editing** content. Instead of removing the feature for nodes completely, I'd prefer to fix the implementation.

Separate issues make sense, in my opinion. This one for giving focus to the top field, and a new one for removing focus when editing content).

**Comment by indigoxela** [comment]
> Instead of removing the feature for nodes completely, I'd prefer to fix the implementation.

OK.

**Comment by BWPanda** [comment]
The issue here is not that the Title field is autofocused when it shouldn't be, but rather that the *first* field isn't.

So the solution I'd like to see here is not removing autofocus altogether, but auto focusing the *first* field (whatever it may be).

**Comment by indigoxela** [comment]
@BWPanda I understand that. Unfortunately, this feature doesn't make any sense to me, as I consider the autofocus on nodes to be an anti-feature - no matter which field. A different issue for removing doesn't make any sense, either, because then the two issues would be contradictory. I'm not planning to work on this issue, feel free to take over.

**Comment by klonos** [comment]
> I just took a stab but couldn't work out where the code is that arranges the fields according to their specified weight...

I also took a look at this and couldn't figure it out ...that's why I have not replied here earlier.

> While the intention of #2625 was to give focus to the top field when creating content, we have introduced focus on the title field when creating and editing content. Instead of removing the feature for nodes completely, I'd prefer to fix the implementation.

I agree with that ^^

> The issue here is not that the Title field is autofocused when it shouldn't be, but rather that the _first_ field isn't.

... but also agree with that ^^ and think that this is what needs fixing here.

**Comment by olafgrabienski** [comment]
>> I just took a stab but couldn't work out where the code is that arranges the fields according to their specified weight...

> I also took a look at this and couldn't figure it out ...that's why I have not replied here earlier.

Maybe we can get some help! (Added `help wanted` label.)

**Comment by klonos** [comment]
With #5386 now merged, this issue here is moot, as there is no autofocus on the node add/edit form for the title field.

Closing.
