### ISSUE TITLE
Add a mod_php7 block to .htaccess

### ISSUE THREAD

**Issue by bradbulger** [backdrop/backdrop-issues#3587]
The PHP directives in the default core .htaccess file are all inside `<IfModule mod_php5.c>`. I noticed when I ran over max_input_vars trying to sort a large vocabulary.

---

PR by @klonos: https://github.com/backdrop/backdrop/pull/2534

**Comment by opi** [comment]
Related Drupal (8) issue: https://www.drupal.org/project/drupal/issues/2455465

Last patch: https://www.drupal.org/files/issues/2455465-utf8-34.patch

**Comment by klonos** [comment]
Thanks @opi I too have noticed that there are inconsistencies between our .htaccess and those of D7 and D8:

Backdrop
```
# Override PHP settings that cannot be changed at runtime. See
# settings.php and backdrop_environment_initialize() in includes/bootstrap.inc
# for settings that can be changed at runtime.
<IfModule mod_php5.c>
  php_flag session.auto_start               off
  php_value mbstring.http_input             pass
  php_value mbstring.http_output            pass
  php_value max_input_vars                  10007
  php_flag mbstring.encoding_translation    off
</IfModule>
```

D7:
```
# Override PHP settings that cannot be changed at runtime. See
# sites/default/default.settings.php and drupal_environment_initialize() in
# includes/bootstrap.inc for settings that can be changed at runtime.

# PHP 5, Apache 1 and 2.
<IfModule mod_php5.c>
  php_flag magic_quotes_gpc                 off
  php_flag magic_quotes_sybase              off
  php_flag register_globals                 off
  php_flag session.auto_start               off
  php_value mbstring.http_input             pass
  php_value mbstring.http_output            pass
  php_flag mbstring.encoding_translation    off
</IfModule>
```

D8:
```
# Most of the following PHP settings cannot be changed at runtime. See
# sites/default/default.settings.php and
# Drupal\Core\DrupalKernel::bootEnvironment() for settings that can be
# changed at runtime.

# PHP 5, Apache 1 and 2.
<IfModule mod_php5.c>
  php_value assert.active                   0
  php_flag session.auto_start               off
  php_value mbstring.http_input             pass
  php_value mbstring.http_output            pass
  php_flag mbstring.encoding_translation    off
  # PHP 5.6 has deprecated $HTTP_RAW_POST_DATA and produces warnings if this is
  # not set.
  php_value always_populate_raw_post_data   -1
</IfModule>
```

**Comment by klonos** [comment]
...the drupal patch is adding a new `<IfModule mod_php7.c>` section to support php7, but it is my understanding that the same settings are present in the `<IfModule mod_php7.c>` section.

It seems that it is possible to have all settings in a single section, supporting both php5 and php7. With something like this:

```
<IfModule mod_php5.c>
    SetEnv MOD_PHP 5
</IfModule>
<IfModule mod_php7.c>
    SetEnv MOD_PHP 7
</IfModule>
<If "reqenv('MOD_PHP') != '' || reqenv('REDIRECT_MOD_PHP') != ''">
  ...put things here
</If>
```

Source: https://stackoverflow.com/questions/39450760/how-to-check-in-htaccess-if-php-is-enabled

**Comment by klonos** [comment]
...so, @bradbulger can you please try replacing the try the entire `<IfModule mod_php5.c>` section with the following and see if it works?:

```
<IfModule mod_php5.c>
    SetEnv MOD_PHP 5
</IfModule>
<IfModule mod_php7.c>
    SetEnv MOD_PHP 7
</IfModule>
<If "reqenv('MOD_PHP') != '' || reqenv('REDIRECT_MOD_PHP') != ''">
  php_flag session.auto_start               off
  php_value mbstring.http_input             pass
  php_value mbstring.http_output            pass
  php_value max_input_vars                  10007
  php_flag mbstring.encoding_translation    off
</If>
```

**Comment by bradbulger** [comment]
That PR works for me. Apache/2.4.38 (Ubuntu), PHP 7.0.33.

**Comment by klonos** [comment]
Thanks @bradbulger 👍 ...adding milestone candidate tag for 1.12.5

**Comment by quicksketch** [comment]
Looks like Apache doesn't support `<If>` for conditions like this until Apache 2.4: https://httpd.apache.org/docs/2.4/mod/core.html#If

As tests and sandboxes are running Apache 2.2, both broke after this change. If we can figure out a way to consolidate duplicated code, that would be great, but duplication may be necessary here.

**Comment by bradbulger** [comment]
As far as I can figure out the only way to avoid repeating the mod_phpN lines would be to put them into an external file and include it in the matching IfModule. That seems like way more work than just repeating the lines. I don't know if Apache 2.4+ is required by anything, but PHP 7 definitely is. So probably we should just add the copy for mod_php7.

**Comment by klonos** [comment]
I'll go ahead and close this in favor of #3824.
