### ISSUE TITLE
CKEditor: Allow selecting image style from the "Insert image" dialog

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3589]
This is basically the respective issue for what is being worked on for D8 core here: https://www.drupal.org/project/drupal/issues/2061377

This is part of #1087 and #378, and related to #2841

![2061377-test-273](https://user-images.githubusercontent.com/2423362/54338485-24e41480-4686-11e9-984a-6bebcd2f5554.gif)

If we apply this to #3297 as well, it will be practically bringing the features provided by https://www.drupal.org/project/iss into core.

**Comment by laryn** [comment]
Related (or duplicate?): https://github.com/backdrop/backdrop-issues/issues/2658

**Comment by klonos** [comment]
Yep, duplicate. Sorry 😞

**Comment by klonos** [comment]
...moved the latest screengrab gif in #2658
