### ISSUE TITLE
SA-CORE-2014-005 - Drupal core - SQL injection

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#359]
See [https://www.drupal.org/SA-CORE-2014-005](https://www.drupal.org/SA-CORE-2014-005)

The process for doing security updates is as follows: 
- Look for the commit that contains only the Drupal release number.  
- Review the diff (or create a patch from it) 
- Apply these same changes to Backdrop.

**Comment by quicksketch** [comment]
- [x] SA-CORE-2014-005 - Drupal core - SQL injection (double-checked)
