### ISSUE TITLE
[UX] Views: Change the "Weight" field for the page menu/tab to a number field

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3593]
This is a sibling issue to #3592, although there is no `is_numeric` validation for this one here, simply changing the form field to a number field for the end users' benefit.

<img width="589" alt="Screen Shot 2019-03-17 at 2 20 45 pm" src="https://user-images.githubusercontent.com/2423362/54497489-49bedd00-494f-11e9-804d-298f83797bd1.png">

<img width="773" alt="Screen Shot 2019-03-17 at 2 21 20 pm" src="https://user-images.githubusercontent.com/2423362/54497493-5cd1ad00-494f-11e9-8f7b-edda37404134.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2536

**Comment by klonos** [comment]
I have filed a PR for review. Same dilemma as with #3592 as to whether to change this to a `weight` field instead of a number, and if so, what to set the `#delta` to?

While at it, I improved the help text of the field. Before:

> Enter the weight of the menu item or tab. The lower the number, the earlier in the list it will be.

I did not find the first sentence of that help text of any use, as it was simply stating the obvious. I thought that explaining how this "weight" works would be of better use. Also, wearing my "newbie" hat, I found myself asking what is `the list` this text refers to? ...so changed it to this:

> This number sets the order of the menu item or tab, with lower weights coming first. Negative values are allowed.

Still about the same text length, and slightly better. @jenlampton usually has better words for things, so `ping` 😄

**Comment by jenlampton** [comment]
Yes on #weight field, good catch. And I love the language!

**Comment by klonos** [comment]
> Yes on #weight field

Sure. The only reason I may sound skeptical about using fields of type `#weight` is because they are limiting to a specific min/max value. Number fields are easy to use with the mouse scroll when focused (no additional clicks).

Having said that, I'm glad to switch the PR to `#weight`, but I need to know what to use for the `#delta` value for it?

**Comment by herbdool** [comment]
I think there's a reason it wasn't originally made with a weight field. I suspect that it can't easily know about the other fields and how to present options for ranking, the delta, as @klonos mentioned. The weight field needs to know how many items there are in the list.

I think a number field is the only other option.

**Comment by klonos** [comment]
> The weight field needs to know how many items there are in the list.

That is not true. Menu items (generally items that rely on a weight value to be sorted), are allowed to have the same weight as other menu items. In other words the weight value is not exclusive.

I believe that items with the same weight will be first ordered appropriately in relation to other items with different weight values, and then ordered in alpha order between themselves.

> I think a number field is the only other option.

Not the only option, but less "limiting". If the weight input field allowed an infinite delta somehow, then this would not be an issue.

**Comment by jenlampton** [comment]
@klonos can you see what menu items do for weight?

**Comment by klonos** [comment]
@jenlampton hold on... I've done some research and this (`#weight` fields) seems to go a bit deeper. I am putting together a separate issue 😄

**Comment by klonos** [comment]
...sorry for the delay. Here: #3626

So I think that we should make a start with these 2 issues here and start changing weight fields to number fields.

> @klonos can you see what menu items do for weight?

So menu items seem to have a `#delta` of 50.

**Comment by klonos** [comment]
OK, so changing `weight` fields to `number` fields, with min/max values instead of `#delta` (if that's required) seems like something we'll attempt in #3626. So the PR for this ticket here is good as is. Please review and RTBC 😄

**Comment by herbdool** [comment]
I checked the menu settings in the view. Looks fine.

(Originally I was looking at the field settings in the view - wrong place)

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...adding milestone candidate for 1.12.6

**Comment by quicksketch** [comment]
Looks good to me and the reasoning for using a number field instead of weight makes sense. PR at https://github.com/backdrop/backdrop/pull/2536 has been merged into 1.x and 1.12.x. Thanks @klonos, @herbdool, and @jenlampton!
