### ISSUE TITLE
[D8] Provide image style tokens (imagecache_token module in core)

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3594]
**Description of the need**
The functionality of [Imagecache Token](https://www.drupal.org/project/imagecache_token) could be merged into the existing token functionality. ([It looks like this functionality is merged into token in D8](https://www.drupal.org/node/2611866).)

> This module provides additional tokens for image fields. For each image style available, a token `[node:field_image_field:style_name]` will be provided. It is also possible to get image properties like width or height by using tokens like `[node:field_image_field:style_name:height]`.

**Proposed solution**
Since token is in core, I think merging this image style token functionality into core would be ideal.

I would like to be the advocate for getting this feature into 1.15. I've added the milestone candidate label.

---

Core minor release advocate: @jenlampton 

---

PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2849

**Comment by klonos** [comment]
> Since token is in core, I think merging this image style token functionality into core would be ideal.

That, plus the fact that this is in D8 core since its early versions, and we are aiming for as much feature parity as possible. Which makes this issue here part of #378 😉

**Comment by jenlampton** [comment]
I just posted this link into the main ussue, but it looks like tese were added to token module for D7 after we added tokens into Backdrop core: https://www.drupal.org/project/token/issues/2611866

**Comment by laryn** [comment]
Works for me -- awesome!

**Comment by jenlampton** [comment]
I would like to be the advocate for getting this feature into 1.15. I've added the milestone candidate label.

**Comment by jenlampton** [comment]
I just pushed passing tests to the PR.

**Comment by jenlampton** [comment]
In the weekly meeting today there was some resistance to adding these tokens into core. The concern is that perhaps the only place these tokens are used is in metatags, and metatag module is a contrib module. Perhaps this should remain a contrib module too?

Adding the needs feedback label to see if others have different use-cases.

**Comment by BWPanda** [comment]
Since it was mentioned above that this is already in D8 core, do we know what their use case is? I'd be happy to see this added for the reasons given already (adding to existing core functionality, feature parity with D8).

**Comment by laryn** [comment]
I guess image style tokens could be used anywhere regular image tokens are used, and regular image tokens are in core... so I'm not sure I see the problem. It makes sense to me to have it in core, anyway.

**Comment by jenlampton** [comment]
Me either. I thought this would be a no-brainer. as I thought these tokens
had simply been forgotten. ¯\_(ツ)_/¯

**Comment by klonos** [comment]
...there's another issue in d.org against the D8 core Token module, which is related: [Add support for field properties](https://www.drupal.org/project/token/issues/2621598) ...and that one seems to have about half a dozen of children issues.

**Comment by jenlampton** [comment]
So those sound like arguments for leaving this in contrib? Maybe even as
part of the metatag module?

**Comment by BWPanda** [comment]
That was my thought too, after reading @klonos' quotes from D.org... If there's no use-case for this other than social media's `og:image` tag, then I guess this should be in Metatag (at least I'd prefer that over Metatag requiring another contrib module).

**Comment by klonos** [comment]
...the use case for core is mobile devices, where you need "automagic" derivatives of images you upload, so that people don't download a 2MB image in their phone, over mobile data networks (where speed/cost is an issue).

**Comment by klonos** [comment]
...long-term, this might fit into #1440 too 😉

**Comment by jenlampton** [comment]
@klonos I don't see how the mobile device thing is a relevant use case for image style tokens. Can you explain?

**Comment by laryn** [comment]
Was there a consensus here? Personally I'd put them in core but if others feel strongly against that, I'd say merge into Metatag.

**Comment by laryn** [comment]
In terms of whether this functionality could ever be used outside of metatag -- if using HTML email sending, I could easily see wanting to use an image style in that rather than the original image.
(I think it belongs in core.)

**Comment by klonos** [comment]
This issue has a label to target the next minor + its milestone set to the next bug fix release. For now, I've chosen to remove the milestone, since features go into minor releases.

I did a light code review, and left some comments (coding standards mainly), but the PR sandbox is broken. @jenlampton can you please refresh the sandbox when you get a chance?

**Comment by jenlampton** [comment]
@klonos thanks for the review, I've addressed your feedback, updated the PR and requested a new sandbox!

**Comment by laryn** [comment]
I've tested the latest sandbox and it still seems to be working well.

**Comment by klonos** [comment]
@jenlampton should we add `imagecache_token` to the list of modules in `backdrop_merged_modules()` as part of this? I realize that the D7 module has not been ported to Backdrop, but for good measure perhaps? (in case someone needs it and attempts to use the verbatim 7.x version with Backdrop for example).

**Comment by jenlampton** [comment]
@klonos hm. Maybe we should clarify exactly when and why modules appear on that list, and then update it to include every D7 contrib module that matches the criteria. I'm still not 100% sure why only a few modules make that cut, so I never know when they need to be included.

**Comment by laryn** [comment]
Took the liberty of adding the 1.17.0 milestone since @klonos suggested it should not go into a minor release.

**Comment by jenlampton** [comment]
Yep! because someone else (me) added the milestone candidate label :)

**Comment by herbdool** [comment]
Tests are failing

**Comment by BWPanda** [comment]
FTR, I'd like to retract my previous comment that this should (maybe) be in contrib. I can see this belongs in core, don't know why I previously thought otherwise.

**Comment by jenlampton** [comment]
I'm stuck on the failing test. https://github.com/backdrop/backdrop/pull/2849#issuecomment-683348739 
I'm going to move on to another issue for now.

**Comment by quicksketch** [comment]
> I'm stuck on the failing test. backdrop/backdrop#2849 (comment)

I pushed a commit to the PR that should fix the two failing tests. Because the image styles are cached in memory, if you modify the image styles in various POST requests, the static in-memory cache must be cleared in the testing thread to get a fresh list of styles from the database. So I just added two `backdrop_static_reset('image_styles');` calls in there and the tests are passing now.

**Comment by quicksketch** [comment]
There are a few changes that I think we should make here, I posted a review to the PR: https://github.com/backdrop/backdrop/pull/2849#pullrequestreview-480414056

There are some features here that I think are too granular for core, like `:first`, `:second`, and `:third` support for image fields, when as far as I know, we don't have any similar support for any other multi-value fields. That said, their value to me seems clear even if I think they're uncommon by core's current practices.

Lastly, if this is replacing a contrib module in its entirety, we should add it to `backdrop_merged_modules()` and disable it in an update hook. See `field_update_1004()` as an example where `field_formatter_settings` was merged into core.

**Comment by herbdool** [comment]
It doesn't have an update hook yet to disable the contrib version, nor backdrop_merged_modules.

**Comment by jenlampton** [comment]
> See field_update_1004() as an example where field_formatter_settings was merged into core.

There is no Backdrop version of `imagecache_token`, so I don't think we need the visible message telling people to remove the from their site. I will leave the bit of code that deletes the entry from the system table though, for people upgrading from Drupal 7.

**Comment by jenlampton** [comment]
Looks like the works for me label was removed when tests were failing, adding back since the problem was with the tests and not the functionality.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2849 into 1.x for 1.17.0. Thanks everyone!
