### ISSUE TITLE
Review the markup provided for layouts

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#360]
We need someone with HTML expertise to check out the markup in layout module, and let us know:

1) are we misusing any HTML5 elements (we've already corrected some mistakes found in D8)
2) is the markup as clean as possible, or are we still using too many div tags?
3) is the markup easy to understand?

**Comment by quicksketch** [comment]
The PR is now updated so that all tests are passing. If anyone has time to review the new markup for a final check, that would be excellent. :)

**Comment by behindthepage** [comment]
I can't see any problems. This improved html makes it a lot easier to see what is happening in the templates. Excellent!

You mentioned on IRC that there could be a problem over riding the CSS files as they are all called layout.css. I haven't thought about this but could calling the css files the same as the layout name solve any conflits? e.g. one-column.css, two-column.css, three-three-four-column.css.

**Comment by quicksketch** [comment]
> I haven't thought about this but could calling the css files the same as the layout name solve any conflits? e.g. one-column.css, two-column.css, three-three-four-column.css.

Yes, I think that's the solution that would be best. You can already specify the stylesheets in the layout .info file, but we added the default `layout.css` shortcut to match the `style.css` shortcut in themes. But since you have multiple layouts but only one theme, that was a poor decision. Let's tackle that in a followup.

**Comment by jenlampton** [comment]
Also, for the record, I hate the shortcuts (style.css especially) . It adds error-prone "magic" that people can't see, and saves almost nothing (~31 characters of text).  let's not add any new nonsense like this, and +1 on the matching file names :)

**Comment by quicksketch** [comment]
Cool, I reviewed this one last time and with @behindthepage's input, I think we're good for an initial merge. @tjdjours, if you get another chance to look at the result, we'd love the additional in-depth checking.

**Comment by quicksketch** [comment]
I had to rebase after some other changes. With tests still passing and another review in Chrome/IE/Safari/Firefox, I think we're looking good here. Thanks again!
