### ISSUE TITLE
Backdrop 1.11.8

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3602]
## Pre-release tasks

- [x] Merge commits @quicksketch
- [x] Draft Release notes @quicksketch
  - [x] Short, descriptive summary of the release
  - [x] Note if any changes were made to files outside the `core` directory
  - [x] Note if updates (update.php) needs to be run
  - [x] Include changelog since last version (generated with drush rn)

## Release tasks

- [x] Update bootstrap.inc with version number  @quicksketch
- [x] Tag for release, and push tag to GitHub  @quicksketch
- [x] Revert version number back  @quicksketch
- [x] Create release notes on GitHub @quicksketch

If this is a security release:
- [x] Mark the release node on b.org as a security release @klonos

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/releases/tag/1.12.5

**Comment by klonos** [comment]
We're done here!
