### ISSUE TITLE
Git pull overwriting sites.php

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3603]
How does/should git and sites.php work?

I have a BD sandbox site that I use for making PR's and stuff for Backdrop core and contributed modules, so BD is a git repo. When I pull from git to update BD, `sites.php` gets overwritten and I have to edit it again to make my sandbox site work.

Is this by design, or should we/I somehow make git ignore `sites.php`?

**Comment by klonos** [comment]
@BWPanda have you tried adding `sites/sites.php` in the `.gitignore` file in the root folder? Perhaps try that and report back if things work with that change.

**Comment by BWPanda** [comment]
I've tried adding it to `.got/info/exclude`... But that doesn't seem to affect anything.

**Comment by klonos** [comment]
Hmm, did you try in the Backdrop https://github.com/backdrop/backdrop/blob/1.x/.gitignore in the docroot folder?

**Comment by BWPanda** [comment]
This is where I don't understand this git ignore/exclude stuff and get confused...

If I add `sites.php` to `.gitignore`, `git status` then says:

```
modified:   .gitignore
modified:   sites/sites.php
```

So that seems to make things worse! And how does it know I've modified `.gitignore` if `.gitignore` is ignoring itself?

```
# Ignore this file so it can be changed 
.gitignore
```

**Comment by herbdool** [comment]
@BWPanda you should be using .gitignore as the main way of ignoring files. I've never tried the other way. 

If your trying to ignore a file that is currently being tracked by the repo, you may need to do something special, like in this thread https://stackoverflow.com/questions/6618612/ignoring-a-directory-from-a-git-repo-after-its-been-added. If you use `git rm --cached <filename>` make a copy of it first, then update .gitignore to exclude it and add the file back to the directory. I think you have to commit at the end. I haven't tested this so you may want a backup.

**Comment by BWPanda** [comment]
I haven't come across this issue anymore, and some good suggestions were provided, so closing this issue now.
