### ISSUE TITLE
Problems with installation of Rules module

### ISSUE THREAD

**Issue by amilenkov** [backdrop/backdrop-issues#3604]
**Description of the bug**
I tried several times to install Rules module. With the necessary "entity" modules dependencies. About two weeks ago with Backdrop 1.12.2 and rules-1.x-2.0.2.
Today I tried again with Backdrop 1.12.5 and Rules 1.x-2.1.0.

I did it both through admin/modules/install as well as through FTP - manually upload and activate.

In all attempts I receive the same error: White screen with message: 

Fatal error: Declaration of RulesRuleUI::form(&$form, &$form_state, $options = Array) must be 

compatible with RulesActionContainerUI::form(&$form, &$form_state, $options = Array, $iterator 

= NULL) in /home/remoogme/public_html/modules/rules/ui/ui.plugins.inc on line 80

After which the site is unavailable, you cannot log in as a user and the only one that fixes this is deleting the database and importing the db backup through phpMyAdmin.

**Steps To Reproduce**
To reproduce the behavior:

**Actual behavior**
Describe what was the result of following the steps above. Add screenshots if
you think they would help.

**Expected behavior**
Describe what you expected to happen instead.
Add mockup screenshots if possible.

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version:
- Web server and its version:
- Operating System and its version:
- Browser(s) and their versions:

**Comment by Graham-72** [comment]
@amilenkov I am sorry you are having this problem with the Rules module.
Please let me know which versions of Entity modules you have installed.
I currently have Rules 1.x-2.1.0 installed with
Entity Plus 1.x-1.0.3 and
Entity UI 1.x-1.0.0-beta

and (important) with Entity Metadata Wrapper module removed from the system.

We should really be discussing this problem as an issue in the Rules contrib module at https://github.com/backdrop-contrib/rules/issues

**Comment by amilenkov** [comment]
Thank you very, very much for your prompt answer!
Because I thing Rules is a key important module for Backdrop to succeed.
Now I'm on a business trip and have only a limited Internet access. 
I will check and answer your questions next week.

**Comment by amilenkov** [comment]
error, sorry - "think" instead of "thing"

**Comment by herbdool** [comment]
@amilenkov copied your issue here https://github.com/backdrop-contrib/rules/issues/37
