### ISSUE TITLE
[DX] Create a change record for all removed registry_*() and _registry_*() functions

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3605]
This is a follow-up from #3557 

@opi:
>Some Drupal's issues are about the `registry_update` function, which disappear from Backdrop code. I can't find anything related in changes records, so an input from old Backdropers is welcome, cc @quicksketch !

@herbdool:
> @opi the registry functionality is not needed in Backdrop since classes are defined in an info hook instead of needing to be discovered and cached.

@klonos:
>Searching api.b.org for `registry_update` brings no results: https://api.backdropcms.org/search/node/registry_update
>@serundeputy @quicksketch @herbdool shouldn't we at least have a change record for that? I would think also a wrapper function that logs a watchdog "deprecated" message when `registry_update` is being used.

@quicksketch:
>The registry does have a change record at https://api.backdropcms.org/change-records/class-registry-has-been-replaced-static-class-map, though it could be fleshed out further to list these functions that have been removed for better searchability.

**Comment by klonos** [comment]
...this seems to be the PR that removed all these functions: https://github.com/backdrop/backdrop/pull/231/files

**Comment by jenlampton** [comment]
no PR, removing milestone.

**Comment by jenlampton** [comment]
@klonos I don't think we should add a bunch of unnecessary code to core for documentation purposes. We have a tool for documenting API changes and removals already (the Change records on the API site) -- we just need to make better use of them :) 

Here's the change record for the removal of all those registry functions: https://docs.backdropcms.org/change-records/class-registry-has-been-replaced-static-class-map

I'm going to add a section for all the registry-related functions that were removed, and that should trigger when people are searching for them.

**Comment by jenlampton** [comment]
Change record updated: https://docs.backdropcms.org/change-records/the-class-registry-has-been-replaced-with-a-static-class-map
