### ISSUE TITLE
[UX] Remove duplicate description text on date field

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3609]
While doing our training yesterday, I noticed that the description text for the `Date attributes to collect` field is `Select the date attributes to collect and store.`. This text is a near exact duplicate of the field label, and should be removed.

<img width="550" alt="Screen Shot 2019-03-21 at 5 51 25 PM" src="https://user-images.githubusercontent.com/397895/54789898-2bccd300-4c02-11e9-8883-2c871ddcfbc9.png">

To test this: 
- Edit an existing content type, or create a new one
- Either edit an existing field of type "Date"
- If creating a new field, these settings should be obvious in the form before saving the field
- If editing an existing date field, scroll to the bottom of the form, and expand the "Global settings" fieldset to reveal the settings

----
PR: https://github.com/backdrop/backdrop/pull/2593
follow-up PRs to fix typo:
- https://github.com/backdrop/backdrop/pull/2629
- https://github.com/backdrop/backdrop/pull/2630 (alternative wording)

**Comment by serundeputy** [comment]
I commented on the PR. We should clean up the `has data` version of the description text now that the primary description is an empty string.

**Comment by Wylbur** [comment]
I committed a new pull request, is that gong to break this?

**Comment by Wylbur** [comment]
OK, updated the code wth Geoff's suggestions and pushed, so this is ready for review now.

**Comment by quicksketch** [comment]
Thanks @Wylbur, @serundeputy, @matthui, and @jenlampton for this fix! Merged https://github.com/backdrop/backdrop/pull/2593 into 1.x and 1.12.x. This will be in 1.12.7.

**Comment by quicksketch** [comment]
Also, I didn't feel it so important as to hold this up, but if you want to make a follow-up, the grammar here could be improved:

`t('Changes to date attributes only effects new or updated content.')`

"effects" should be "affects"

**Comment by jenlampton** [comment]
Doh, sorry about that.

**Comment by olafgrabienski** [comment]
>> Changes to date attributes only effects new or updated content.

> "effects" should be "affects"

Shouldn't it be "affect", without the "s"?

**Comment by klonos** [comment]
> >> Changes to date attributes only effects new or updated content.
> >
> > "effects" should be "affects"
> 
> Shouldn't it be "affect", without the "s"?

Yep. Either that, or:

`t('Changing date attributes affects only new or updated content.')`

**Comment by klonos** [comment]
@quicksketch lets please not create a separate issue for the typo. Follow-up PRs to pick and choose from:

https://github.com/backdrop/backdrop/pull/2629

`Changes to collected date attributes affect only new or updated content.`

https://github.com/backdrop/backdrop/pull/2630

`Changing collected date attributes will affect only new or updated content.`

@jenlampton (or anyone else) feel free to propose alternative wording, and I'll amend.

**Comment by jenlampton** [comment]
What are `collected date attributes`?

**Comment by klonos** [comment]
Granularity. Year/month/day/hour/min/sec.

**Comment by jenlampton** [comment]
Can we say that instead of `collected` ?

**Comment by klonos** [comment]
Should we change the field label then too? It reads `Date attributes to collect`.

One thing to note, as a person whose first language is not English, I think that there are way more chances for people to be familiar with the word `attributes` rather than with `granularity`.

**Comment by jenlampton** [comment]
But `attributes` has a specific meaning in web, and we use that word all over the place for that other meaning. I think we use `granularity` elsewhere for dates, it would be good not to mix the two.

**Comment by klonos** [comment]
Fair enough. Changed the help text in the 2 PRs to:

`Changes to date granularity affect only new or updated content.`

and:

`Changing date granularity will affect only new or updated content.`

Also changed the field label from `Date attributes to collect` to `Date granularity` in both PRs.

**Comment by matthui** [comment]
I think the wording in backdrop/backdrop#2630 is a little better since its more instructive, but I couldn't find where the fix is on the site when trying to test it.

**Comment by klonos** [comment]
@matthui I have updated the issue summary with steps to get you to these settings, either when creating a new date field, or editing an existing one 😉

**Comment by matthui** [comment]
The new help message shows up for me!

**Comment by quicksketch** [comment]
Thanks @klonos and @matthui for sticking this through! Merged https://github.com/backdrop/backdrop/pull/2630 into 1.x and 1.12.x to wrap this up.
