### ISSUE TITLE
a potential security Issue

### ISSUE THREAD

**Issue by prasadlingamaiah** [backdrop/backdrop-issues#3612]
**Message deleted.** Security issues should never be posted in a public queue.

**Comment by jenlampton** [comment]
Hi @prasadlingamaiah and thanks for reporting a security issue.  

I have deleted the contents of this issue to protect all Backdrop sites from a potential threat.

Please read the instructions on how to report a security issue [on our Security page](https://backdropcms.org/security) or [in this issue queue](https://github.com/backdrop/backdrop-issues/issues/new?assignees=&labels=&template=security-issue.md&title=)

**Comment by quicksketch** [comment]
I've posted responses to this in the security issue and through email.
