### ISSUE TITLE
Consider supporting 'type = test' and 'type = profile' in .info files

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3613]
In #1294 we have excluded `.test.info` files from requiring a `type =` line in them. In #3553 we are doing the same for `.info` files of profiles.

Wondering if instead of excluding/ignoring those .info files, it would make sense to support `type = test` and `type = profile`.

---
PR by @klonos (adds `type = profile` to core profiles): https://github.com/backdrop/backdrop/pull/2541

**Comment by klonos** [comment]
I have filed a PR that adds `type = profile` in the .info files of the 3 profiles shipped with Backdrop core. Unfortunately, I cannot reproduce #3553, so cannot test if that works as a fix in that case 😞

**Comment by herbdool** [comment]
@klonos thanks for the alternative PR. Probably best to link your PR to the original issue since it's an alternative approach to fix the same issue (I'm open to either). And then close this one.

**Comment by klonos** [comment]
Agreed @herbdool ...moving there.
