### ISSUE TITLE
[UX] Project Browser: Fix RTL in the "Install new themes" page

### ISSUE THREAD

**Issue by shabibalm** [backdrop/backdrop-issues#3616]
before
![UX  fix rtl Install themes](https://user-images.githubusercontent.com/45591694/54871098-40ef6080-4dc0-11e9-9e82-86263f1fef4c.jpg)

after
![UX  fix rtl Install themes-1](https://user-images.githubusercontent.com/45591694/54871108-52d10380-4dc0-11e9-87f0-3ad7eed2c2be.jpg)

edite modules\installer\css\installer.css

after 
`  .screenshot {
    float: left;
    width: 133px;
    height: 100px;
    margin: 0;
  }`
add
`[dir="rtl"]  .screenshot {
    float: right;
  }`

after
`  .has-image .project-information {
    margin-left: 148px;
  }`
add 
`[dir="rtl"]  .has-image .project-information {
    margin-right: 148px;
    margin-left: 0;
  }`

---
PR: https://github.com/backdrop/backdrop/pull/2547

**Comment by klonos** [comment]
Thanks once again @shabibalm 👍 ...PR up for review: https://github.com/backdrop/backdrop/pull/2547

**Comment by quicksketch** [comment]
Thanks @klonos, @shabibalm, and @Plochem! Merged https://github.com/backdrop/backdrop/pull/2547 into 1.x and 1.12.x.
