### ISSUE TITLE
[UX] Better messages and clear caches when changing the default theme

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3617]
When switching the default theme in `/admin/appearance`, we throw a long success message that feels as if it should be of type `info` instead:

> Please note that the administration theme is still set to the `[admin_theme]` theme; consequently, the theme on this page remains unchanged. All non-administrative sections of the site, however, will show the selected [`selected_theme]` theme by default.

<img width="773" alt="Screen Shot 2019-03-24 at 1 52 28 pm" src="https://user-images.githubusercontent.com/2423362/54874294-2d81db00-4e3c-11e9-8ca5-93ab633e88b6.png">

We should be showing a very short "things have worked" success message, and then all that long text as info.
We should also be clearing caches when the theme is changed.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2546
~~alternative PR by @klonos (moves admin theme fieldset to the top of the page): https://github.com/backdrop/backdrop/pull/2549~~

**Comment by klonos** [comment]
...setting the tag for a milestone candidate. I believe that it can get in in either 1.12 or 1.13.

Here's an "after" screenshot:

<img width="784" alt="Screen Shot 2019-03-24 at 1 53 00 pm" src="https://user-images.githubusercontent.com/2423362/54874358-f90f1e80-4e3d-11e9-88ae-5ca9ea4a856f.png">

The success messages are short and clean, with the long message shown as info.

**Comment by olafgrabienski** [comment]
> Please note that the administration theme is still set to the [admin_theme] theme; consequently, the theme on this page remains unchanged. All non-administrative sections of the site, however, will show the selected [selected_theme] theme by default.

Every time i see  this text it sounds a bit awkward and lengthy to me. Let's take the opportunity to improve not only the message type but also the text itself. A first attempt:

> - The administration theme is set to the [admin_theme] theme. You can change the administration theme below on this page.

**Comment by klonos** [comment]
I agree @olafgrabienski 👍 ...we could change the success message to:

> [selected_theme] is now the default theme for all non-administrative pages.

...and the info message to:

> The administration theme is set to the [admin_theme] theme. [Change the administration theme](url).

I was also thinking to make the "Change the administration theme" part of the info text a link to jump top the bottom of the page, since the section where you set the admin theme already has a `system-themes-admin-form` id that can be used in a URL fragment.

**Comment by klonos** [comment]
...OK, I have updated the PR. Here's how it looks when changing to a theme different then the admin theme:

<img width="822" alt="Screen Shot 2019-03-25 at 5 18 01 pm" src="https://user-images.githubusercontent.com/2423362/54898955-449af880-4f22-11e9-8bd9-aa53841808d7.png">

...and here's what it looks like when the default theme is changed to be the same as the admin theme (the info message is omitted):

<img width="820" alt="Screen Shot 2019-03-25 at 5 18 34 pm" src="https://user-images.githubusercontent.com/2423362/54898973-54b2d800-4f22-11e9-8f35-5a2deb27ef8b.png">

**Comment by klonos** [comment]
...I've thought of an alternative approach and have started an alternative PR. Instead of asking the user to scroll to the bottom of the page (either manually, or by providing a link for them), how about if we moved the "Admin theme" fieldset at the top of the page:

<img width="695" alt="Screen Shot 2019-03-25 at 8 11 04 pm" src="https://user-images.githubusercontent.com/2423362/54907781-7324cd80-4f3a-11e9-9beb-f835a17b801b.png">

So, I have:
- Made the info message as simple as "The administration theme is still set to the [admin_theme] theme."
- Moved the fieldset to the top of the page. This makes is so that it is right bellow the info massage. So, no need to scroll to see that fieldset is available 😉 ...the UX gain here is even more obvious when there is a big number of themes installed on the site.
- Made the fieldset collapsible, and collapsed by default. The thought behind this was that this setting is not changed that often.
- Added a fieldset summary to show which theme is currently set as the admin theme. So there is no need to expand to see that 😉(needs some more tweaking to get everything right)

Interested to know what people think about this change.

**Comment by klonos** [comment]
...OK, I have fixed the fieldset summaries, so second PR is really ready for review now 😄

**Comment by olafgrabienski** [comment]
@klonos Thanks for adjusting https://github.com/backdrop/backdrop/pull/2546, it works fine in the sandbox site!

Re the wording, the term "all" is used twice:

> - [selected_theme] is now the default theme for **all** non-administrative pages.
> - **All** caches have been cleared.

In my opinion, we don't need the "all" in the first sentence.

---

I'm not sure about the alternative approach. I think it's not 'necessary', clicking a link to the bottom is also fine. However, **if** the alternative approach gets implemented, we don't need the info message about the admin theme at all.

---

Another note: When you change the Administration theme, the message is still very unspecific:

> The configuration options have been saved.

**Comment by klonos** [comment]
> Another note: When you change the Administration theme, the message is still very unspecific:

@olafgrabienski the "The configuration options have been saved." message is there to account for changes made to the "Use the administration theme when editing or creating content" checkbox. So that message needs to stay.

I have updated both PRs so that appropriate messages are shown (in addition to "The configuration options have been saved."):

- If the admin theme has changed, then:
  > The administration theme has been changed to [admin_theme].
- If the admin theme has switched to "default":
  > The administration theme will be the same as the rest of the site (currently [default_theme])
- If there was no change in the admin theme, then none of the above messages is shown (only "The configuration options have been saved.").

**Comment by klonos** [comment]
>I'm not sure about the alternative approach. I think it's not 'necessary', clicking a link to the bottom is also fine.

This is not only a matter of finding the fieldset when the info message is shown. The list of themes could in theory grow really big, and the bigger it grows, the more scrolling is required to reach the "Admin theme" section. Since that fieldset is less likely to change in size (especially collapsed), I think that it is a good idea to keep it at the top of the page.

This at the same time, saves scrolling, and also mitigates the need to have to tell the user to scroll to the bottom of the page, or to have them click a link to achieve the same.

>However, if the alternative approach gets implemented, we don't need the info message about the admin theme at all.

I think we do need it. It helps clarify why the user is not seeing the change they just made... We need to look at this from a non-Drupal/Backdrop point of view: when a user changes the default theme, there is a success message telling them that the change has happened, but they don't see the new theme. The info message is there to explain that the admin theme has not changed. Having the info message explain something about the admin theme, and also the admin theme fieldset right after it, is a UX gain IMO, because if the user wants to change the admin theme too, they don't have to look around for the form that achieves that.

**Comment by klonos** [comment]
> The hint about the selected administration theme is overlapping with the admin theme label on narrow screens.

Yeah, I was afraid that this would be the case. Not sure how to best address that. Lets wait for some more feedback/ideas.

**Comment by klonos** [comment]
...another thing to note is that the "Use the administration theme when editing or creating content" setting does not make sense when the "Default theme" option is selected from the drop-down. Perhaps we should be hiding the checkbox via `#states` in that case.

**Comment by olafgrabienski** [comment]
> The list of themes could in theory grow really big, and the bigger it grows, the more scrolling is required to reach the "Admin theme" section. Since that fieldset is less likely to change in size (especially collapsed), I think that it is a good idea to keep it at the top of the page.

I agree, still not being sure at the same time. I'm not sure to change the position of the Admin theme section, at least *now*, because I've the impression that the different naming, presentation and selection of "Default" and "Administration" themes are either way hard to understand for non-Drupal newcomers. Actually, I wouldn't be surprised if the current discussion of single elements would turn into a more fundamental discussion about the "Appearance" page concept, and its layout. If that's the case, it might be better to limit the *current* changes to improvements which don't change the position of elements and the layout of the page.

---

> when a user changes the default theme, there is a success message telling them that the change has happened, but they don't see the new theme. The info message is there to explain that the admin theme has not changed.

Hm, having the admin theme fieldset directly below the message, we'd say the same thing twice over. Example:

> The administration theme is still set to the Seven theme.
>
> Administration theme: Seven

**Comment by olafgrabienski** [comment]
Added the 'needs more feedback' tag to get more feedback regarding the alternative PRs.

**Comment by herbdool** [comment]
I like the improved messages. I hate the admin theme fieldset at the top. Of all the theme settings, changing the admin theme or settings is probably the least important.

**Comment by arjunk2004** [comment]
This is what I see, I think it looks good.
<img width="1154" alt="Screen Shot 2019-04-20 at 10 56 05 AM" src="https://user-images.githubusercontent.com/49816728/56460657-eadbf180-635a-11e9-9f73-095dd2f9f33a.png">

**Comment by quicksketch** [comment]
> We need to look at this from a non-Drupal/Backdrop point of view: when a user changes the default theme, there is a success message telling them that the change has happened, but they don't see the new theme.

From a non-Backdrop perspective, changing the Admin theme at all would be highly unusual. I don't think other major CMSes even have this capability. The WordPress admin theme is always the same for everybody. You don't have the option to change the entire UI of SquareSpace or Weebly.

In my opinion, providing any messaging about the admin theme is unnecessary and confusing. I think just the message "Basis is now the default theme for all non-administrative pages." is good enough.

**Comment by klonos** [comment]
OK, let me recap the status of this issue to the best of my understanding:

1. We seem to have consensus that the admin theme fieldset should stay where it is (I have crossed the alternative PR out - still there for anyone that wants to give the sandbox a spin)

2. Clearing caches after either the default or the admin theme has been changed. OK with this change?

3. Hiding the "Use the administration theme when editing or creating content" checkbox via `#states` when the "Default theme" option is selected from the drop-down. This makes sense. Correct? ...is it OK to sneak this in with this change here, or split it to a separate issue/PR?

- side-by-side before/after screenshot of messages:

    ![Screen Shot 2019-06-02 at 9 23 55 am](https://user-images.githubusercontent.com/2423362/58754652-7fb83a00-8518-11e9-8128-f44542c68e7b.png)

    This basically communicates the same things as before (with the addition of the message re cache clear), but splits the bit about the admin theme being different into a separate, `info` message.

    @quicksketch prefers to ditch the info message entirely. More feedback re that please?

**Comment by klonos** [comment]
...and also, please add the 1.13.3 milestone if you agree with the candidate label.

**Comment by BWPanda** [comment]
1. I agree.
2. I'm OK with clearing caches, but I don't think we should expect users to know or care about that. This likely needs a separate issue, but I think there should be a permission/setting so we can still show 'cache cleared' messages to developers, but not editors, etc.
3. If you mean that when someone sets the admin theme to be the same as the default non-admin theme then that checkbox is hidden, then yes, that makes sense.
4. If this message stays, then I'm not 100% happy with the wording 'still' and 'change'. These seem to indicate that you *need* to change the admin theme (e.g. sounds like: 'the admin theme's *still* not changed, change it now!'). I can't think of better wording that's not as wordy as the 'before' screenshot, which leads me to think removing it altogether is best...
Also, we refer to 'non-administrative pages' (in the status message). I wonder if this is something users will understand, or if something like 'frontend pages' would be a better choice...?

**Comment by klonos** [comment]
Thanks for the review @BWPanda 👍 

> I don't think we should expect users to know or care about that. 

Are you suggesting to remove the "All caches have been cleared" message?

>  I think there should be a permission/setting so we can still show 'cache cleared' messages to developers, but not editors.

I agree with the idea, but unless we get #1285 implemented, I doubt that there would be a way to do that. Unless you are suggesting to assign the new permission to show the message to the administrator role, and not the authenticated. In any way, definitely a separate issue 🙂 

>If you mean that when someone sets the admin theme to be the same as the default non-admin theme then that checkbox is hidden, then yes, that makes sense.

Yep, that is what I am saying.

> If this message stays, then I'm not 100% happy with the wording 'still' and 'change' ...I can't think of better wording that's not as wordy as the 'before' ...

I see your point. @jenlampton perhaps can chime in with ideas for better wording.

> ...something like 'frontend pages' would be a better choice...?

I don't think that front-/back-end are terms that an average content editor would be familiar with either; but I don't have any better alternatives at the moment either.

**Comment by BWPanda** [comment]
> Are you suggesting to remove the "All caches have been cleared" message?

No. Leave it here, and if a separate issue means we can show those messages more specifically, then that'll do the trick.

> Unless you are suggesting to assign the new permission to show the message to the administrator role, and not the authenticated.

Yes. I'll create a separate issue.

**Comment by klonos** [comment]
@BWPanda I have wrapped the `backdrop_set_message()` for cleared caches in a `if (user_access('flush caches'))`, so only users that have the permission to clear caches see that message. That would suffice for now I think.

Besides, I feel that #3844 should be closed as a duplicate of #1062 (as it was recently pointed to me by @docwilmot in #3831 😅)

**Comment by BWPanda** [comment]
@klonos As per my comments in https://github.com/backdrop/backdrop-issues/issues/3844, I see this as a unique situation in that users submitting this form/page are not specifically clearing caches (they may not even know what 'caches' are and why they should be cleared). In every other situation where a 'caches cleared' message is shown in core, it's because the user specifically chose to do so (by clicking a button or link label as such).

Therefore, I think in just this situation alone an access check is needed to avoid users seeing the 'caches cleared' message unnecessarily. You've done that already using the existing `flush caches` permission, but as I realised in the other issue, that permission is part of the Admin Bar module which isn't required and can be disabled. I don't think we can therefore rely on that permission being available all the time. I'd therefore (how many times have I used the word 'therefore' now...?) suggest using a different, core permission instead. The best candidate I can see is `administer site configuration`.

**Comment by jenlampton** [comment]
Or we could move the flush caches permission to system module.

**Comment by BWPanda** [comment]
> Or we could move the flush caches permission to system module.

Actually that'd probably be better, as (in my case at least) I sometimes need to give clients access to 'administer site configuration' (for changing the site name, email address, etc.) but I'd never want them seeing the 'caches cleared' message(s).

**Comment by klonos** [comment]
>> ...that permission is part of the Admin Bar module which isn't required and can be disabled. ... suggest using a different, core permission instead.
>
> Or we could move the flush caches permission to system module.

Yeah, @jenlampton's suggestion seems more reasonable:

**Comment by BWPanda** [comment]
I've re-opened https://github.com/backdrop/backdrop-issues/issues/3844 for that purpose.

**Comment by klonos** [comment]
Thanks guys 👍 ...so I guess that with #3844 RTBC'ed, what's left here is a code review?

...also milestone set to 1.13.3 if you agree that this can go in on a bug release 😉

**Comment by klonos** [comment]
Repeating @quicksketch's comment from the PR:

> IMO we should just remove this second message. This message makes it sound as though you _should_ change the admin theme, even though that's an uncommon task.

The `The administration theme is still set to ...` bit is still required, in order to let people understand that the fact that they are not seeing the new theme applied is normal/expected. ...I see how the `Change the administration theme` link may make it seem as what you describe.

We need to either come up with a better wording for the link, or remove that link altogether (and unfortunately assume that people know that they need to scroll to the bottom of the page to change that - if they want).

**Comment by klonos** [comment]
...OK, I have updated the PR, to remove the `Change the administration theme` link from the info message, and made the `administration theme` bit a link to the settings at the bottom of the page instead 😉 

So, here's before:

![Screen Shot 2019-08-19 at 8 50 13 pm](https://user-images.githubusercontent.com/2423362/63287675-92ded880-c2c3-11e9-974a-82e38be0b534.png)

...and after:

![Screen Shot 2019-08-19 at 8 51 36 pm](https://user-images.githubusercontent.com/2423362/63287682-95d9c900-c2c3-11e9-859a-69f322132265.png)

**Comment by BWPanda** [comment]
Reviewed and approved! (hope I set the right milestone...)

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2546 into 1.x and 1.13.x. Thanks @klonos, @BWPanda, @arjunk2004, @herbdool, and @olafgrabienski!
