### ISSUE TITLE
Warning when creating custom options for list field

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3622]
**Description of the bug**
I was creating a list (text) field and added some custom options, including custom keys. When I saved the form I got the following warnings:

> Warning: A non-numeric value encountered in _form_options_from_text() (line 334 of /[SNIP]/core/modules/field/modules/options/options.element.inc).

**Steps To Reproduce**
To reproduce the behavior:
1. Add a new field to a content type
2. Select 'List (text)' as the field type
3. In Field Settings, tick 'Custom keys' and add some custom keys/labels (e.g. 'first > First one, second > Next one, third > Last one')
4. Click 'Save Field Settings'

**Actual behavior**
The above warning is displayed for each option you added (e.g. 3 options, 3 warnings).

**Expected behavior**
No warnings, carry on as normal.

---
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2565

**Comment by herbdool** [comment]
Do you see the same error in D7 with options_element module?

**Comment by herbdool** [comment]
I wonder if it's PHP being more strict? What version are you using?

```
$int_key = $item['key'] * 1;
    if (is_int($int_key)) {
      $new_key = max($int_key, $new_key);
    }
```

Seems like it's testing if the key is an integer. Does it expect a float or integer, or also was multiplying on strings?

**Comment by herbdool** [comment]
Can you try the patch in https://www.drupal.org/project/options_element/issues/2920613. As long as it doesn't prevent having strings as keys.

**Comment by BWPanda** [comment]
Quite possibly it's just PHP being more strict; I'm running v7.2.0.

**Comment by herbdool** [comment]
@BWPanda are you able to test the D7 patch? Not sure if it's right approach or not.

**Comment by BWPanda** [comment]
Can't test the D7 patch, but I suspect it'll do the trick as this is why the warning is appearing: https://www.php.net/manual/en/migration71.other-changes.php#migration71.other-changes.apprise-on-arithmetic-with-invalid-strings

**Comment by klonos** [comment]
I was able to reproduce this with php 7.1.26, and i can confirm that the patch in https://www.drupal.org/project/options_element/issues/2920613 fixes things.

I have to say though that I am also puzzled, same as another user in that d.org issue. So here's the bit of code that needs to be changed:

```php
  foreach ($items as $item) {
    $int_key = $item['key'] * 1;
    if (is_int($int_key)) {
      $new_key = max($int_key, $new_key);
    }
  }
```

So I don't get why we multiply `$item['key']` by `1`? This is always `0` when the keys are alphanumeric, so multiplying by 1 does nothing.

The proposed patch changes this:

```patch
-    $int_key = $item['key'] * 1;
+    $int_key = (int) $item['key'] * 1;
```

Which if I understand correctly is making sure that `$item['key']` is an int (?), ...in which case why not do something like this instead?:

```php
  foreach ($items as $item) {
    if (is_int($item['key'])) {
      $new_key = max($item['key'], $new_key);
    }
  }
```

Having no comments in code to explain "magical" things does not help 😓

**Comment by herbdool** [comment]
@klonos `is_int(23)` is TRUE, but `is_int("23")` is FALSE. So I think that multiplying by 1 will ensure it's an integer while avoiding using `(int)` which will do odd things. `(int)` will turn "9ABC" into 9, and "ABC" into 0. I think for now let's go with the patch from D7. I've tested various scenarios and it works okay for me so I think I'll make a PR.

**Comment by herbdool** [comment]
Created PR https://github.com/backdrop/backdrop/pull/2565

**Comment by klonos** [comment]
Yep, the PR solves the issue, and the code change looks reasonable to me. RTCB

**Comment by quicksketch** [comment]
Looks great! I find it interesting that the "multiply by `1`" trick doesn't seem to do the job any more. Indeed this may be a PHP version thing. New code is actually more clear though slightly more verbose. Merged into 1.x and 1.12.x. Thanks @herbdool, @klonos, and @BWPanda!
