### ISSUE TITLE
[DX] Remove the hard-coded parentheses from fieldset summaries

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3623]
This was brought up in #3595

> One question: Do we need the parentheses for the summary? Looks slightly better without, in my opinion...

Instead of hard-coding these, we could be adding them with CSS `:before`/`:after`, which would allow themers to change them easily using CSS.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2553

**Comment by klonos** [comment]
PR up for review.

I could have added the parentheses in `system.css`, but that would mean that they would be there by default for all new custom themes. I have instead added them via CSS for Seven, Basis, and Bartik (I have not bothered with Stark, since we seem to be hiding that ...with the intention to deprecate it I guess?). This way, we don't break existing sites that use the core themes (or subthemes based on them), but at the same time do not force them on new themes.

This was a small change, so I think can get in in 1.12.6.

**Comment by klonos** [comment]
...please let me know if we should go the other way: remove the parentheses entirely from all core themes, and leave it up to custom/contrib themes to add them if required.

**Comment by olafgrabienski** [comment]
@klonos I've had a look at the sandbox site. Unfortunately, with this PR the parentheses get added on every fieldset summary, even if there is no summary, see screenshot:

![screen-backdrop-pr-2553-empty-parentheses-everywhere](https://user-images.githubusercontent.com/14188307/55004585-cbaba780-4fda-11e9-8ba4-8205b0928ec6.png)

**Comment by klonos** [comment]
...doh! 😅 ...I missed that. Will try to figure it out and sort it.

**Comment by klonos** [comment]
...easy fix. Done! (please flush caches if you still see the issue)

**Comment by olafgrabienski** [comment]
Looks good to me now!

**Comment by quicksketch** [comment]
Seems like a good suggestion IMO. Code change is simple enough and has Olaf's thumbs-up, so I've merged https://github.com/backdrop/backdrop/pull/2553 into 1.x and 1.12.x. Thanks!
