### ISSUE TITLE
[D8] theme_table() should take an optional footer variable and produce tfoot

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3627]
This is the same as https://www.drupal.org/project/drupal/issues/1892654 for D7, which is a backport of what has already been done for D8 in https://www.drupal.org/project/drupal/issues/806982 (which makes it part of #378)

> ## Problem/Motivation
> Somehow the `<tfoot>` element of a table never got into core. While not commonly used, it still is a necessary component on some sites. Themes have to add this functionality when its optional use should be provided by core.
> 
> ## Proposed resolution
> Add optional `#footer` variable in theme hook and corresponding `<tfoot>` markup in table template.

---
PR: https://github.com/backdrop/backdrop/pull/2554

**Comment by klonos** [comment]
This is an API addition, so proposing 1.13.0 for milestone.

**Comment by jenlampton** [comment]
removing `[D8 feature parity]` from title, adding `[D8]` for brevity, adding into project.

**Comment by indigoxela** [comment]
This has been fixed in https://github.com/backdrop/backdrop-issues/issues/5042 as part of a cross port.
