### ISSUE TITLE
[Policy] Use data-* attributes instead of IDs or Classes for JS-only operations

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#363]
With Backdrop 1.0, we're already trying to reduce the use of IDs where possible and use classes. For example, blocks now have classes such as `block-[module]-[delta]` instead of an ID by the same format. Primarily because the same block can be placed multiple times on the same page, but also because IDs are "too heavy" as a CSS selector, and can inadvertently override other styles.

We have a number of places in core where we have either IDs, e.g. `#ajax['wrapper']` or `drupal_add_tabledrag()`, or classes e.g. Views' `.scroll` class in its dialogs, that are used exclusively for adding a JavaScript behavior to the page. This results in a mishmash of classes and IDs being used for both CSS and JS, and front-end developers never know which classes or IDs are important to maintain JavaScript functionality.

To prevent this problem, we could use data- attributes whenever targeting an item specifically for JS behaviors. It could be a simple attribute with a simple value e.g. `data-tabledrag="true"`, or we could use the data attribute to set particular options such as `data-tabledrag-weight="input[name='foo']"`.

The increased use of data attributes could also free us up from the use of backdrop_add_settings() all over the place, and instead put the data for behaviors directly on the elements that specify them.

Thoughts on this idea?

**Comment by jenlampton** [comment]
Closing this issue in favor of https://github.com/backdrop/backdrop-issues/issues/366, which is also tagged for documentation.
