### ISSUE TITLE
[UX] Improve the help text in the visibility condition form

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3633]
`Add a new visibility condition to limit the situations in which this block will be shown.` should be `Limit the situations in which this block will be shown.`

Locations to test:
From the layouts page, click
1. menu settings
1b. Add visibility condition
2. dropdown --> manage blocks
2b. configure
2c. visibility conditions
2d. add visibility condition
3. dropdown --> configure layout
3b. add visibility condition
(/admin/structure/layouts/manage/[layout]/configure)
(/admin/structure/layouts/menu/[layout])

<img width="618" alt="Screen Shot 2019-03-29 at 9 57 36 AM" src="https://user-images.githubusercontent.com/397895/55249358-1ad71f80-5209-11e9-9ddc-ad33b18f653c.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2563

**Comment by klonos** [comment]
👍 ...PR up for review.

**Comment by olafgrabienski** [comment]
Looks good in the sandbox:

![screen-backdrop-pr-2563-add-visibility-condition](https://user-images.githubusercontent.com/14188307/55411560-26f31200-5566-11e9-927f-cab6c7ecfc43.png)

**Comment by klonos** [comment]
The same chunk of code is used for the visibility conditions dialog in "Menu settings" (`/admin/structure/layouts/menu/[layout]`):

<img width="618" alt="Screen Shot 2019-04-03 at 5 57 39 am" src="https://user-images.githubusercontent.com/2423362/55428937-f5199400-55d5-11e9-82e3-4fac13fa0a6e.png">

...and for the one in the layout configuration page (`/admin/structure/layouts/manage/[layout]/configure`):

<img width="627" alt="Screen Shot 2019-04-03 at 5 58 08 am" src="https://user-images.githubusercontent.com/2423362/55428913-e92dd200-55d5-11e9-9287-b08663f764fd.png">

(screenshots also from the PR sandbox)

**Comment by matthui** [comment]
All 3 locations look good, same as the screenshots above.

**Comment by quicksketch** [comment]
Thanks @matthui! I found one minor indentation issue: https://github.com/backdrop/backdrop/pull/2563/files#r277146076 Normally I'd push to that PR to fix it, but looks like the "Allow changes from maintainers" option wasn't checked.

**Comment by quicksketch** [comment]
> Normally I'd push to that PR to fix it, but looks like the "Allow changes from maintainers" option wasn't checked.

GitHub is acting a little strange. I can't modify a PR via suggestions, but I can click the Edit button on the file and add another commit to a PR that way. I've fixed that minor indentation issue.

**Comment by klonos** [comment]
Thanks @quicksketch 👍 ...and sorry I missed that earlier.

**Comment by quicksketch** [comment]
No problem! Merged https://github.com/backdrop/backdrop/pull/2563 into 1.x and 1.12.x. Thanks folks!
