### ISSUE TITLE
[UX] Improve link text for menu settings

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3635]
On the admin page for menus, the drop-button for accessing the list of menu links reads `Edit links`. Since `Edit` isn't exactly the right choice here, I recommend changing this to `Manage links` instead.

What do people think?  Is `Edit` providing value here, because this setting is saved in the database, or should we try to improve this language?

<img width="1194" alt="Screen Shot 2019-03-29 at 10 17 33 AM" src="https://user-images.githubusercontent.com/397895/55250725-15c79f80-520c-11e9-8708-d20e0849517b.png">

---

PR: https://github.com/backdrop/backdrop/pull/2592

**Comment by klonos** [comment]
I don't object to this, but perhaps consider things after implementing #475?

**Comment by TopperSaburo** [comment]
Great, although I do agree with @klonos about implementation of #475 before implementation of the manage links feature change. I definitely agree with you that manage links would be a more comprehensive feature description. 👍

**Comment by matthui** [comment]
I tested it and the "manage links" works as expected.

**Comment by quicksketch** [comment]
Thanks for the review @matthui and the PR @jenlampton! With no opposition and seeming an improvement, I've merged https://github.com/backdrop/backdrop/pull/2592 into 1.x and 1.12.x, though it's likely to change again after #475 is implemented.
