### ISSUE TITLE
CKEditor: Link to existing content gets confused by paths that match file extensions (like /pdf and .pdf)

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3643]
Using CKEditor's link dialog autocomplete, a link to a page with a title corresponding to an allowed and used file extension doesn't link to the page but to a file.

**Example:** A link to a page with title "PDF" doesn't point to the "PDF" page but to a `.pdf` file.

(The issue happens also with other file types, e.g. with a page called "XML" and a `.xml` file.)

**Steps To Reproduce**
1. Check if your site manages at least one `.pdf` file on `admin/content/files`.
2. If there's no `.pdf` file:
  Make sure you have a content type where you can upload a PDF file via a *File* field.
  Create a content item, and attach a PDF file to it.

3. Add a page with title "PDF", e.g. `example.com/pdf`.
4. Add a post, write some body text, and use the link dialog to link to the "PDF" page.
5. Save the post.

**Actual behavior**
The link points to *one of the PDF files* of the site, e.g. `example.com/files/dummy.pdf`.

**Expected behavior**
The link points to *the PDF page* which had been chosen in the link dialog.

**Additional information**
- Backdrop 1.12.5 (also earlier versions)
- Web server and OS: happens in different environments

---

PR by @olafgrabienski: https://github.com/backdrop/backdrop/pull/2750

**Comment by klonos** [comment]
I confirm this bug on a 1.13.x-dev installation (git cloned at some point, and not pulled for some time, so don't know exact version).

This happens right after submitting the link dialog (you can see it if you hit the "source" button in CKEditor). So it has to do with that; not with the active filters for the editor.

Good catch @olafgrabienski 👍 ...I am curious what the culprit is, but don't have time to debug right now. I am guessing that it has to do with the autocomplete for the path to the link.

**Comment by olafgrabienski** [comment]
I've noticed that the issue doesn't only happen with a page called "PDF" and a `.pdf` file but e.g. also with a page called "XML" and a corresponding file. Updated the title and the issue description.

**Comment by olafgrabienski** [comment]
> I am guessing that it has to do with the autocomplete for the path to the link.

Note to myself: Autocomplete was introduced in https://github.com/backdrop/backdrop-issues/issues/1206.

@klonos Thanks for confirming the issue, btw!

**Comment by olafgrabienski** [comment]
According a conversation with @docwilmot on Gitter the culprit is https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.pages.inc/function/filter_format_editor_link_form_submit/1.

(See also https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.pages.inc/function/_filter_get_file_id/1, which is in use there.)

Suggested approaches to fix the issue:

- `filter_format_editor_link_form_submit()` should be checking if the link matches a piece of content before it checks if it is a file, OR
- it should be checking if the return is from the link vs the file dialogs

**Comment by docwilmot** [comment]
Actually I think `_filter_get_file_id()` should be checking if a href is a valid filename with an extension. In this situation its receiving a href called `posts/pub`; normally it would like `file/path/file.ext`. But the function only looks for whatever is after the last slash (normally `file.ext`, but in this case just `pub`) and doing a mysql LIKE query on all filenames in the database. Of course its finding `whatever.pub`, and passing that as a file at url `posts/pub`.
If we made sure `href` is a valid url before the LIKE query runs, it would prevent this situation.

**Comment by olafgrabienski** [comment]
For reference, here's the function mentioned in the last comment:

```
function _filter_get_file_id($href) {
  $result = 0;

  // Extract file name and directory from $href.
  $pos = strrpos($href, "/");
  $filename = substr($href, $pos + 1);

  // Now find this file name in uri field to get fid.
  if (!empty($filename)) {
    $results = db_select('file_managed')
      ->fields('file_managed', array('fid', 'uri'))
      ->condition('uri', '%' . $filename, 'LIKE')
      ->orderBy('fid', 'DESC')
      ->execute();

    foreach ($results as $found) {
      $result = $found->fid;
    }
  }

  return $result;
}
````

Source: https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.pages.inc/function/_filter_get_file_id/1

**Comment by Graham-72** [comment]
Yes, the simple addition of a test using `file_valid_uri()` seems to solve the problem. So then we have 

`function _filter_get_file_id($href) {

  $result = 0;
  if(!file_valid_uri($href)){
    return $result;
  }`

etc.

**Comment by olafgrabienski** [comment]
@Graham-72 Thanks for the hint! I've quickly tested your suggestion locally, and it seems to fix the issue.

That's the complete code, including the `file_valid_uri` check:

```
function _filter_get_file_id($href) {
  $result = 0;

  // Check URI for valid file scheme.
  if(!file_valid_uri($href)){
    return $result;
  }

  // Extract file name and directory from $href.
  $pos = strrpos($href, "/");
  $filename = substr($href,$pos + 1);

  // Now find this file name in uri field to get fid.
  if (!empty($filename)) {
    $results = db_select('file_managed')
      ->fields('file_managed', array('fid', 'uri'))
      ->condition('uri', '%' . $filename, 'LIKE')
      ->orderBy('fid', 'DESC')
      ->execute();

    foreach ($results as $found) {
      $result = $found->fid;
    }
  }

  return $result;
}
```

Will make a PR of it.

**Comment by olafgrabienski** [comment]
I've made the pull request, checks have passed, and for me the issue is fixed in the sandbox website.

@klonos @docwilmot @Graham-72 Thanks for your very helpful comments! Mind to test and review the PR?

**Comment by olafgrabienski** [comment]
Added the `milestone candidate - bug` tag, I suggest milestone 1.13.3.

**Comment by docwilmot** [comment]
RTBC

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2750 into 1.x and 1.13.x. Thanks @olafgrabienski, @Graham-72, @docwilmot, and @klonos!
