### ISSUE TITLE
Views "not equal to" filter <> returns no results

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3644]
**Description of the bug**
A short description of what the problem is.

**Steps To Reproduce**
Set up content:
1. Add a "status" field of type "list: text" to a post
2. Set the allowed values to applied, approved, and concluded
3. Add content, one post with each value

Set up view
1. Create a test view. format: table, fields: title, status
2. Add filters: published = yes, type = post
3. Test the view, see all 3 posts

Add problem filter:
1. Add a filter for field status not equal to "concluded"
2. Test the view, see no results at all.

**Actual behavior**
status not equal to "concluded" returns no results

**Expected behavior**
status not equal to "concluded" should return 2 results

**Comment by laryn** [comment]
@jenlampton See if this is related: https://github.com/backdrop/backdrop-issues/issues/3614

**Comment by jenlampton** [comment]
Yes! that's the same thing :)  I'll add some more keywords there so it matches next time I search.

**Comment by klonos** [comment]
...I have updated the issue summary in #3614 to include your STR @jenlampton 😉
