### ISSUE TITLE
Error: Call to undefined function admin_bar_suppress()

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#3649]
**Description of the bug**
Error: 'Call to undefined function admin_bar_suppress()' in color.module - If 'Administration bar' module is disabled on `BACKDROP_ROOT/?q=admin/appearance/settings/basis` page.

**Steps To Reproduce**
1. Disable 'Administration bar' module.
2. Go to `BACKDROP_ROOT/?q=admin/appearance/settings/basis` page.

**Actual behavior**
Fatal error: Call to undefined function admin_bar_suppress() in BACKDROP_ROOT\core\modules\color\color.module on line 293

**Expected behavior**
Preview-window without error message.

**Additional information**
- Backdrop CMS version: 1.x
- Possibe solution: https://github.com/VasasA/backdrop/commit/d2a7b75792b59ca707cfeb1cfaaa10eaf6cc6894
#

---
PR: https://github.com/backdrop/backdrop/pull/2566

**Comment by klonos** [comment]
Thanks for bringing this up @VasasA ...your approach to use `module_exists('admin_bar')` is correct, but I would wrap that around `admin_bar_suppress();` specifically, instead of adding it as a condition to the existing `if` statement. So this:

```php
function color_custom_theme() {
  $preview = _color_preview_theme();
  if (($preview)) {
    if (module_exists('admin_bar')) {
      admin_bar_suppress();
    }
    return $preview;
  }
}
```

Care to file a pull request?

**Comment by klonos** [comment]
...wondering if we should implement a more generic solution here.

The admin_bar module is optional, so can be disabled. If contrib and/or core uses `admin_bar_suppress()`, they are bound to hit the same problem. So perhaps we should introduce a new `backdrop_admin_bar_suppress()` or `system_admin_bar_suppress()` function, which all it does is to wrap `admin_bar_suppress()` in a `module_exists('admin_bar')` condition. We should then discourage usage of `admin_bar_suppress()` in favor of that new function.

**Comment by VasasA** [comment]
A screenshot with the error.
![fata_error](https://user-images.githubusercontent.com/8567234/55440341-9dfcca80-55a7-11e9-961a-40c174369148.png)

**Comment by klonos** [comment]
I have brought up this issue during the weekly dev meeting. It was decided that contrib/custom modules should check if `module_exists('admin_bar')` on their end each time they call `admin_bar_suppress()`. So I have filed a PR that specifically fixes this for this issue with color.module.

**Comment by klonos** [comment]
I have tested this in the PR sandbox by disabling the Admin Bar module, and then visiting the Basis settings page -> no error 👍

**Comment by VasasA** [comment]
I am glad, thank You and the members of dev meeting! :smile:

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2566 into 1.x and 1.12.x. Thanks @klonos for the PR and @VasasA for the excellent report and information!
