### ISSUE TITLE
API documentation inconsistency re adding JS to every page

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3650]
The [documentation](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_add_js/1) for `backdrop_add_js()` says:

> It is critical that all preprocessed files are added unconditionally on every page, even if the files are not needed on a page. This is normally done by calling backdrop_add_js() in a hook_init() implementation.

However, the [documentation](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_init/1) for `hook_init()` says:

> To add CSS or JS files that should be present on all pages, modules should not implement this hook, but declare these files in their .info file.

I'm guessing the latter is the correct one...

**Comment by opi** [comment]
:+1:  , and this part of documentation for `backdrop_add_js` is really confusing to me

**Comment by BWPanda** [comment]
So it seems that the `backdrop_add_js()` documentation was originally added in July 2010:

[![image](https://user-images.githubusercontent.com/2385329/151535135-a8cae5e0-e4d1-457d-8e5b-b8e7ff2d00da.png)](https://github.com/backdrop/backdrop/blame/c144627cadb416d979aaa89bc9659c0cb04a7b2b/core/includes/common.inc#L4529)

And the `hook_init()` documentation was originally added in September 2010:

[![image](https://user-images.githubusercontent.com/2385329/151535367-bcc7b906-9b45-42ec-b40f-3adbe05e3193.png)](https://github.com/backdrop/backdrop/blame/68db4b5999f54e450918fd7d41c2322bc8fa4849/core/modules/system/system.api.php#L1371)

So I'd say that yes, the `hook_init()` documentation is the most correct/up-to-date. Out of interest, here's the Drupal issue where the ability to add CSS/JS to .info files was added: https://www.drupal.org/project/drupal/issues/328357

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3925

**Comment by klonos** [comment]
Looks good to me 👍🏼

**Comment by quicksketch** [comment]
I think this needs a bit more rewording. The new help text now reads:

```
 * $options['preprocess'] should be only set to TRUE when a file is required for
 * all typical visitors and most pages of a site. It is critical that all
 * preprocessed files are added unconditionally on every page, even if the
 * files do not happen to be needed on a page. However, it is preferred that
 * modules do not implement this hook, but declare CSS files intended for all
 * pages in their .info file instead.
```

It mentions "However, it is preferred that modules do not implement this hook", but there's no "hook" mentioned now. Previously `hook_init()` was mentioned, but now there's no hook at all.

I suggest we just omit any mention of any hook.

```
 * $options['preprocess'] should be only set to TRUE when a file is required for
 * all typical visitors and most pages of a site. It is critical that all
 * preprocessed files are added unconditionally on every page, even if the
 * files do not happen to be needed on a page. Modules and themes that
 * declare CSS files in their .info files will use this option automatically.
```

**Comment by BWPanda** [comment]
@quicksketch I took it to mean the hook (function) the documentation was describing (i.e. `backdrop_add_css/js()`). I've re-worded this to say 'use this function' instead of 'implement this hook' for clarity.

**Comment by quicksketch** [comment]
Perfect @BWPanda. Looks great now. I merged https://github.com/backdrop/backdrop/pull/3925 into 1.x and 1.21.x. Thanks!
