### ISSUE TITLE
[UX] Add number of terms column to vocabulary overview page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3655]
Before:
<img width="1295" alt="Screen Shot 2019-04-06 at 11 14 52 AM" src="https://user-images.githubusercontent.com/397895/55673457-2eb00080-585d-11e9-8c66-c11244c48398.png">

After:
<img width="1249" alt="Screen Shot 2019-04-06 at 11 20 36 AM" src="https://user-images.githubusercontent.com/397895/55673534-070d6800-585e-11e9-9f20-18d09ec3572e.png">

---
PR: https://github.com/backdrop/backdrop/pull/2594

**Comment by klonos** [comment]
Once again, it's these small things 😄 ❤️ ...I really like this 👍 

I have left a comment in the PR for consideration. I also mentioned this during our previous dev meeting, when referring to #3485: I find `db_select()`/`db_update`/`db_delete()` much easier to understand than "direct" `db_query()`.

**Comment by jenlampton** [comment]
I've left an explanation in in the PR about why db_select()/db_update/db_delete() are being removed from Backdrop core (someday).

I think you may be the exception to the rule here, because you are coming to Backdrop as a someone who's never queried any database before. Most people who start to dabble in Backdrop code will have had a little experience with SQL queries (or database queries) somewhere before, and will understand the universal language of db_query(). If we throw the unique language of our database abstraction layer at them, that's a much harder thing to learn.

**Comment by docwilmot** [comment]
This should have new tests.

**Comment by klonos** [comment]
@jenlampton fair enough 👍 ...I still left a couple of minor suggestions for your consideration.

Sounds like we need to be actively discouraging the use of `db_select()`/`db_update`/`db_delete()` with a watchdog message then. I will file a separate issue for that though.

**Comment by jenlampton** [comment]
> I will file a separate issue for that though.

We have one: https://github.com/backdrop/backdrop-issues/issues/61

**Comment by klonos** [comment]
Thanks @jenlampton 👍 ...back when #61 was created, I knew far less than I know now, so never actually took the time to participate to the discussion. Not that my knowledge is enough to contribute anything substantial now 😅 ...just saying.

**Comment by jenlampton** [comment]
Well maybe add a comment there too, so we know your perspective. That
hasn't happened yet, so there's room for more discussion!

**Comment by klonos** [comment]
Thanks @jenlampton ...done that already 😉

...back to the point, this is RTBC from me. Just wondering if it might be easier to the eye if the column was aligned to the right:

<img width="813" alt="Screen Shot 2019-04-08 at 2 52 45 am" src="https://user-images.githubusercontent.com/2423362/55686827-6e83fe80-59a9-11e9-89e8-970dee7838f1.png">

**Comment by jenlampton** [comment]
Yes! PR? I'm on a plane today to DrupalCon :)

**Comment by klonos** [comment]
> Yes! PR?

Sure 😄 ...here: https://github.com/jenlampton/backdrop/pull/8

I went with making changes to the `taxonomy.theme.inc` file directly (by using `'style' => 'text-align: right'`). Please let me know if you'd prefer a CSS solution instead.

>I'm on a plane today to DrupalCon :)

Godspeed (or universe-speed), and have fun you guys! 🎉

**Comment by jenlampton** [comment]
Is there an admin facing CSS file? Taxonomy.admin.css? If not this one is
fine :)

**Comment by klonos** [comment]
>Is there an admin facing CSS file? Taxonomy.admin.css? 

Nope. There is only a `taxonomy.css` file, and this is all it has in it:

```css
.taxonomy-term-preview {
  background-color: #eee;
}
.taxonomy-term-divider-top {
  border-bottom: none;
}
.taxonomy-term-divider-bottom {
  border-top: 1px dotted #ccc;
}
.taxonomy-term-description {
  margin: 5px 0 20px;
}
```

**Comment by jenlampton** [comment]
Okay, ty!

**Comment by daggerhart** [comment]
Added some additional tests insertions in this PR: https://github.com/backdrop/backdrop/pull/2594

**Comment by herbdool** [comment]
Code looks good

**Comment by quicksketch** [comment]
This could be optimized using a single query with a `GROUP BY` instead of one query per vocabulary, but in the scheme of overall site speed, this seems like it would be negligible. I've merged https://github.com/backdrop/backdrop/pull/2594 into 1.x.

I haven't pulled this into 1.12.x as this is a moderate impact as far as UI presentation. With 1.13.0 around the corner I hope that should be fine.

**Comment by jenlampton** [comment]
This issue has a "fixed" label, and a commit. Think it's safe to close.

**Comment by jenlampton** [comment]
It appears https://github.com/backdrop/backdrop/pull/2567 has not been merged, re-opening.

**Comment by jenlampton** [comment]
well, that PR had merge conflicts because it had already been merged. Closed the PR to avoid confusion. @klonos if you want to add the text-align right bit, can you do that in a new issue/pr?

**Comment by klonos** [comment]
Sure @jenlampton ...2 follow-up issues filed; one for the align right thing (#3780), and another for @quicksketch's suggestion to use a single query (#3781).

😉
