### ISSUE TITLE
[UX] Add vertical tabs to the taxonomy term edit form

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3657]
I find it confusing that on node edit forms my Metatags, URL settings, and Redirects are nicely organized into vertical tabs, but on taxonomy term edit forms they are all in separate fieldsets. I think we should make the UI consistent across all edit forms.

Term after:
<img width="1197" alt="Screen Shot 2019-04-06 at 3 37 34 PM" src="https://user-images.githubusercontent.com/397895/55676068-e6570980-5881-11e9-8ffd-5eda96968717.png">

Term before:
<img width="1200" alt="Screen Shot 2019-04-06 at 2 33 36 PM" src="https://user-images.githubusercontent.com/397895/55675534-f3232f80-5878-11e9-8a73-8fcfec168761.png">

Node, for comparison: 
<img width="1202" alt="Screen Shot 2019-04-06 at 2 33 05 PM" src="https://user-images.githubusercontent.com/397895/55675529-e272b980-5878-11e9-9931-1ea9c3bf002d.png">

To get to the term edit form on the sandbox to test, go to http://2572.backdrop.backdrop.qa.backdropcms.org/taxonomy/term/3/edit

---
~PR: https://github.com/backdrop/backdrop/pull/2568~
PR: https://github.com/backdrop/backdrop/pull/2572

**Comment by klonos** [comment]
Things work as expected, but there's a chunk of code that's commented out. Either add a `@todo`, or remove it completely(?).

**Comment by jenlampton** [comment]
I don't see the commented code in the PR: https://github.com/backdrop/backdrop/pull/2568/files

Can you point to where you see that?

**Comment by klonos** [comment]
Thank YOU! RTBC 👍

**Comment by quicksketch** [comment]
Looks pretty good! I left [one code comment that we're missing a t()](https://github.com/backdrop/backdrop/pull/2568/files#r273680050) call. Seems like a big UX change for 1.12. Can we move this to 1.13?

**Comment by klonos** [comment]
> Seems like a big UX change for 1.12. Can we move this to 1.13?

I don't mind this. By the time we get this merged, 1.13 will be around the corner 😄

**Comment by quicksketch** [comment]
I made a fix to the PR to handle if multiple parents are selected and filed a new PR at https://github.com/backdrop/backdrop/pull/2572. If we can get another UX review we can move to RTBC.

**Comment by isabelhaas** [comment]
I tested the PR and I was confused about this: in the Relations tab on the node edit form, the description added an s to the parent name (ex. the description was 'Parents: <root>s'  when the parent name was '<root>'.

**Comment by quicksketch** [comment]
Thanks @isabelhaas and welcome! Nice catch on that typo. I've updated the pull request to fix that and also took into account single vs. multiple values. So now selecting a single item is `Parent: <root>` and multiple items is `Parents: term1, term2`.

**Comment by jenlampton** [comment]
Bumped milestone to 1.13 as per @quicksketch 's request.

> Seems like a big UX change for 1.12. Can we move this to 1.13?

**Comment by isabelhaas** [comment]
@quicksketch Thanks! The typo is fixed, I tried the new sandbox and it worked for me.

**Comment by klonos** [comment]
Hmm, the things even an old-timer Drupal/Backdrop user can learn. I was not aware that the same term can be assigned to multiple parents. I guess I never had a use case for it.

**Comment by jenlampton** [comment]
FWIW, I haven't either ;)

**Comment by quicksketch** [comment]
Thanks @jenlampton, @isabelhaas, and @klonos! Merged https://github.com/backdrop/backdrop/pull/2572 into 1.x for 1.13.0.
