### ISSUE TITLE
[UX] Change "Theming" to "Theme" or "Theme developer" throughout core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3658]
I've noticed that throughout core we use the word "theming" all over the place, for all different kinds of meanings. Sometimes we do mean `the act of creating a theme` but more often than not we simply mean `rendering` or even `markup`.

I'm going to take a pass through core and see if I can replace this word (mostly in documentation) with a more specific alternative, better suited to the intended meaning. 

---
PR: https://github.com/backdrop/backdrop/pull/2570

**Comment by klonos** [comment]
@jenlampton this is set to NT/NR, but no PR 😅

**Comment by jenlampton** [comment]
doh, sorry: https://github.com/backdrop/backdrop/pull/2570

**Comment by klonos** [comment]
I have removed the NT tag, since all changes are in docblocks, and some labels or help text.

I left a couple of comments and a question in the PR, but overall this looks great 👍. Thanks.

**Comment by jenlampton** [comment]
> and some labels or help text.

Don't we need to test these? Confirm I didn't delete a `;` and break everything?

**Comment by klonos** [comment]
All such changes are limited in `core/modules/views/plugins/views_plugin_display.inc `. I will test them when I get a chance ...unless anyone beats me to it 😄

**Comment by nicolascrossi** [comment]
The changes made didn't break anything for me. However, there were two typos I pointed out

**Comment by jenlampton** [comment]
@nicolascrossi if you see something in the PR that needs work, you are welcome to add the tag `pr - needs work`.

**Comment by jenlampton** [comment]
Pushed an updated PR with the fixed addressed. @nicolascrossi I didn't see any comments on the PR from you about typos. If you started a multi-comment review, can you make sure that it was actually submitted? Sometimes that trips me up and I never actually add my comments :(

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2570 into 1.x and 1.13.x. Thanks @jenlampton, @nicolascrossi, and @klonos!
