### ISSUE TITLE
Views: header/footer "Display even if view has no result" setting not working

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3663]
<img width="599" alt="Screen Shot 2019-04-11 at 5 33 21 am" src="https://user-images.githubusercontent.com/2423362/55908196-27ea0a80-5c1c-11e9-8102-51518ed3ddd6.png">

I came across this while working on https://github.com/backdrop-contrib/webform/issues/143 and it seems to be a long-standing issue, that was sorted in D8 Views in core, and now pending on a backport for Views 7.x: https://www.drupal.org/project/views/issues/1217394

The solution for that issue might be solving #3411 too (?)

**Comment by klonos** [comment]
...I may have jumped the gun with this one, as further testing shows that this is actually working. Can someone please confirm?

I wonder if we backported the D8 solution, or applied one of the 7.x patches early.

**Comment by klonos** [comment]
...this might have actually been #3662

**Comment by klonos** [comment]
...I have searched our codebase for occurrences of `function is_empty() {`, `case 'block_hide_empty':`, and `function output_is_empty() {`, but I could not find any. So yeah, we will need that patch whenever it gets committed to Views 7.x ...problem is that there seems to be some disagreement at the moment as per which among 2 proposed solutions to go with.

I will go ahead and close this one in favor of the older #3411

**Comment by danksearle** [comment]
This is still an issue for me, I think. In a view's header I have tried both "Results summary" and "Text area", with "Display even if view has no result" checked - and when there were no results to show, the header isn't shown either.
