### ISSUE TITLE
[DX] format_xml_elements() should use proper indentation

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3667]
**Description of the bug**
The `format_xml_elements()` function takes an array and converts it into XML. This function tries but fails to use indentation on nested elements.

This came up as part of https://github.com/backdrop/backdrop-issues/issues/1992 (package signing) and in particular https://github.com/backdrop-contrib/project/issues/25, where update.module's XML feeds are being updated.

**Steps To Reproduce**
TBD

**Actual behavior**
Generated XML is indented a single space regardless of nesting. e.g.
```xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns:dc="http://purl.org/dc/elements/1.1/">
 <title>Webform</title>
 <short_name>webform</short_name>
 <releases>
 <release>
 <name>Webform 1.x-4.18.0</name>
 <version>1.x-4.18.0</version>
 <status>published</status>
 <date>1540427700</date>
 <filesize>286582</filesize>
 <security_update>false</security_update>
 <version_major>4</version_major>
 <version_minor>18</version_minor>
 <version_patch>0</version_patch>
 <release_link>https://github.com/backdrop-contrib/webform/releases/tag/1.x-4.18.0</release_link>
 <download_link>https://github.com/backdrop-contrib/webform/releases/download/1.x-4.18.0/webform.zip</download_link>
 </release>
 </releases>
</project>
```

**Expected behavior**
Generated XML should be indented two (or four) spaces per level of nesting. e.g.
```xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns:dc="http://purl.org/dc/elements/1.1/">
  <title>Webform</title>
  <short_name>webform</short_name>
  <releases>
    <release>
      <name>Webform 1.x-4.18.0</name>
      <version>1.x-4.18.0</version>
      <status>published</status>
      <date>1540427700</date>
      <filesize>286582</filesize>
      <security_update>false</security_update>
      <version_major>4</version_major>
      <version_minor>18</version_minor>
      <version_patch>0</version_patch>
      <release_link>https://github.com/backdrop-contrib/webform/releases/tag/1.x-4.18.0</release_link>
      <download_link>https://github.com/backdrop-contrib/webform/releases/download/1.x-4.18.0/webform.zip</download_link>
    </release>
  </releases>
</project>
```

---

PR https://github.com/backdrop/backdrop/pull/2576

**Comment by klonos** [comment]
Code looks good to me (apart from a tiny nit + typo in one of the comments) 👍

Since there are no steps to reproduce, I have tested this with a `dpm()`.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/2576 merged into 1.x and 1.12.x. Thanks @jlfranklin, @klonos, AND @herbdool for reviewing! You all rock!
