### ISSUE TITLE
Performance: Make multisite opt-in

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3672]
I was reading the description of https://www.drupal.org/project/drupal/issues/1757536. The moving of settings.php bit is not of any interest to Backdrop I believe, but this bit might be (emphasis mine):

> ...
> Merge `/sites/sites.php` into the top-level `/settings/settings.php`, and turn the `$sites` variable into an explicit flag for enabling the multi-site functionality.
> 
> This means:
> 
> 1. **If the root `/settings/settings.php` does not define the `$sites` variable at all, then there is no multi-site functionality and no site directory discovery process.**
> 2. If the root `/settings/settings.php` defines an empty `$sites = array();`, then the multi-site functionality is enabled and the site directory is discovered on every request.
> 3. If the root `/settings/settings.php` defines site aliases in the form of `$sites['localhost.example'] = 'example.com';`, then the specified site aliases are resolved during the site directory discovery (no change).
> 
> This also means:
> 
> 1. When the multi-site functionality is enabled, then the root `/settings/settings.php` acts as if it was a `/sites/all/settings.php`, which is a concept that does not exist thus far — i.e., the root `/settings.php` can contain shared settings for all sites.
> 2. The root `/settings/settings.php` is always loaded first. The site-specific `sites/foo/settings.php` has access to all of the global variables and is able to override them in a granular way.

**Comment by jenlampton** [comment]
@klonos multi-site is already opt-in in Backdrop.
