### ISSUE TITLE
'AJAX HTTP error' on CKEditor Link autocomplete

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3676]
**Description of the bug**
When I try to add a link to an image in CKEditor (in a custom block), the link autocomplete pops up this error each time:

![error](https://user-images.githubusercontent.com/2385329/56270741-87a25300-60ff-11e9-9784-0480c8af599c.png)

At first I thought it was because the site is offline, but I tried it online and same thing happens.
I also tried it on my BD sandbox site, and it doesn't happen there... So not sure how to reproduce this. Be interested to hear if others can.

**Comment by olafgrabienski** [comment]
I've tested the issue as well on a sandbox site and couldn't reproduce it.

**Comment by BWPanda** [comment]
Hmm, must be something with my site then... If anyone can reproduce this, feel free to re-open.
