### ISSUE TITLE
[UX] Update "Front page" link on update complete page to "Home page"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3678]
When you complete updates, the top link is to your site's "Front page". This is a very drupally term. I'd prefer we stick to a standard web term here and rename the text in this link to "Home page". 

Before:
<img width="892" alt="Screen Shot 2019-04-17 at 6 28 24 PM" src="https://user-images.githubusercontent.com/397895/56330803-93613a00-613e-11e9-9a88-b955fd23edf3.png">

After:
<img width="896" alt="Screen Shot 2019-04-17 at 6 28 55 PM" src="https://user-images.githubusercontent.com/397895/56330829-a2e08300-613e-11e9-83f7-4a97d44fee57.png">

**Comment by monsij** [comment]
Interested @jenlampton

**Comment by herbdool** [comment]
Looks good.

**Comment by klonos** [comment]
1.12.7?

**Comment by quicksketch** [comment]
1.12.7 seems fine to me. Now that the localization server is up and running we can confirm if suggested strings are already present. "Home page" is already in the .po files so there's no need to delay.

**Comment by quicksketch** [comment]
Thanks @monsij for the PR! There is a failing test due to the string change: https://github.com/backdrop/backdrop/pull/2584#issuecomment-485161584

Please ignore the other test that failed (`comment-new class not found.`), it's one of the lingering random failures we haven't been able to figure out (#1478).

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2584 into 1.x and 1.12.x. Thanks @monsij, along with @jenlampton for opening the issue and @herbdool for reviewing it. :smile:
