### ISSUE TITLE
hook_menu() menu item not created by default

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3679]
**Description of the bug**
[`hook_menu()`](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu/1) says:

> "menu_name": Optional. Set this to a custom menu if you don't want your item to be placed in the Main menu.

But leaving this out means no menu item is created. So either this is a bug, or the documentation needs updating (assuming the former).

**Steps To Reproduce**
To reproduce the behavior:
1. Add the following code to a custom module
    ```php
    function my_module_menu() {
      return array(
        'test' => array(
          'title' => 'Test',
          'page callback' => 'my_module_test',
          'access arguments' => TRUE,
        ),
      );
    }
    ```

2. Clear caches
3. Look in main menu

**Actual behavior**
No new menu item.

**Expected behavior**
New menu item created.

**Additional information**
It only works once you specifically set `'menu_name' => 'main-menu',`...

**Comment by BWPanda** [comment]
Turns out this is by design and just needs a documentation update: https://github.com/backdrop/backdrop-issues/issues/4797
