### ISSUE TITLE
hash IP addresses when tracking project usage

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3688]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/3168 which I think will replace the need for that issue entirely.

From [my comment](https://github.com/backdrop/backdrop-issues/issues/3168#issuecomment-485032077):

> I think the only real issue here is that we are sending an IP address so that we can tell all the sites apart. Why don't we just hash the IP address so that no recognizable data is ever stored?

I'm not sure if this is an issue that needs to go against core, project module, or b.org, but we should be able to move this issue when we decide where it should go :)

**Comment by quicksketch** [comment]
I tried transferring this to backdrop-contrib/project, but the feature on GitHub to do this isn't working. This is part of project module and should be moved over there.

**Comment by BWPanda** [comment]
Here you go: https://github.com/backdrop-contrib/project/issues/39

**Comment by klonos** [comment]
Just to clarify things, so Backdrop core does not send the IP; it is instead being recorded on the Project module end?

**Comment by quicksketch** [comment]
> Backdrop core does not send the IP; it is instead being recorded on the Project module end?

Right, Backdrop core does not explicitly send the IP address of the hosting site, but the IP address can easily be checked on the receiving end as the requester address.
