### ISSUE TITLE
[UX] Existing warning not shown when changing view's display machine name.

### ISSUE THREAD

**Issue by nicolascrossi** [backdrop/backdrop-issues#3691]
There is a warning message about changing the view's display name in the code, but it does not appear in the user interface. The message is in views_plugin_display.inc.

**Steps To Reproduce**
To reproduce the behavior:
1. Configure a view
2. Under other, click on 'Machine Name' and change it
3. Under other, click on 'Theme: Information'

**Actual behavior**
No warning appears

**Expected behavior**
A warning appears under "This section lists..." to let the user know that there may be issues with things attached to the display, like themes, until it is saved

---
PR: https://github.com/backdrop/backdrop/pull/2597

**Comment by jenlampton** [comment]
I've filed a pull request to fix this at https://github.com/backdrop/backdrop/pull/2597

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Thanks for the report @nicolascrossi! I've merged https://github.com/backdrop/backdrop/pull/2597 into 1.x and 1.12.x. Thanks @jenlampton for the PR and @herbdool for the review!
