### ISSUE TITLE
.DS_Store should not be included in git commits

### ISSUE THREAD

**Issue by aparwani02** [backdrop/backdrop-issues#3693]
When making a new branch, after typing "git status" in terminal, git includes .DS_Store files in modified files when they shouldn't be there.

**Comment by jlfranklin** [comment]
This is an issue specific to working on a Mac.  Mac developers should add `.DS_Store` and `.AppleDouble` to their global `.gitignore`, and code reviewers should check for them.  Those entries are not specific to Backdrop, nor global for all developers, and thus shouldn't be added to Backdrop's `.gitignore`.

Instead, if you're on a Mac, create a `.gitignore_global` file in your home directory with those two items in it, and then run the command:

`git config --global core.excludesfile ~/.gitignore_global`
