### ISSUE TITLE
Spelling error RE: options element

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3698]
**Description of the bug**

> The contributed module Options Element has been located at /path/. The module has been disabled, since its **functionlity** is now provided by Backdrop core. It is recommended that you remove this module from your site. 

PR: https://github.com/backdrop/backdrop/pull/2608

**Comment by klonos** [comment]
Good catch @laryn 👍 ...RTBC

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2608 into 1.x and 1.12.x.
