### ISSUE TITLE
php 7.1 Warning: A non-numeric value encountered in theme_pager()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3699]
This is the same as https://www.drupal.org/project/drupal/issues/2902430, which is currently RTBC.

---
PR: https://github.com/backdrop/backdrop/pull/2609

**Comment by klonos** [comment]
PS: cross-referencing #797

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2609 into 1.x and 1.12.x.
