### ISSUE TITLE
php 7.3: session_id() cannot be changed after session is started

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3700]
This is the respective issue for https://www.drupal.org/project/drupal/issues/3025335

> **Problem/Motivation**
> On PHP 7.3, session regeneration fails when logging in if an anonymous session was already active. A warning is thrown in drupal_session_regenerate(), line 375 of includes/session.inc: session_id(): Cannot change session id when session is active.
> 
> **Proposed resolution**
> The original D8 fix is here: [#2989734: PHP 7.3 compatibility](https://www.drupal.org/project/drupal/issues/2989734) . This patch resolves the issue on Drupal 7 in an analogous way by closing the old session (without saving it, so there is not even a split second with the old session ID and new user ID in the session store), regenerating the session ID, starting a new session, restoring the global user object, and finally re-enabling session saving.

---
PR: https://github.com/backdrop/backdrop/pull/2610

**Comment by quicksketch** [comment]
With multiple confirmations in the Drupal issue queue, passing tests, and code review that looks good, I've merged this into 1.x and 1.13.x.
