### ISSUE TITLE
Installer: Profiles reported as modules.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3712]
This one is easy to miss, since it's the last thing reported on the very last page of the installer:

<img width="400" alt="Screen Shot 2019-04-26 at 9 14 34 pm" src="https://user-images.githubusercontent.com/2423362/56835433-8ddebf00-68b7-11e9-8369-ba4500559803.png">

(I wanted to report it so many times, but each time I tried to grab a screenshot, I was too slow 😅)

**Comment by indigoxela** [comment]
"module" seems hardcoded in function [_install_module_batch](https://github.com/backdrop/backdrop/blob/0362219161a9b42275fdfbe54ae36d857c2af672/core/includes/install.core.inc#L1732).

**Comment by klonos** [comment]
I think that this may be a duplicate...

**Comment by klonos** [comment]
I'm a horrible-horrible person 😓 : https://github.com/backdrop/backdrop-issues/issues/3796#issuecomment-753761270

> I think this is the third time that @klonos reported this issue: :-)
