### ISSUE TITLE
Typo in `batch_set()` documentation.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3713]
> **operations:** (required) Array of operations to be performed, where each item is an array consisting of the name of an implementation of callback_batch_operation() and an array of parameter.

Should be:

**operations:** (required) Array of operations to be performed, where each item is an array consisting of the name of an implementation of callback_batch_operation() and an array of parameters.

(Added 's' onto end of 'parameter')

---
PR: https://github.com/backdrop/backdrop/pull/2615

**Comment by klonos** [comment]
Nice catch @BWPanda 👍 ...RTBC.

**Comment by quicksketch** [comment]
Thanks @BWPanda! Merged https://github.com/backdrop/backdrop/pull/2615 into 1.x and 1.12.x.
