### ISSUE TITLE
Keep smartmenus.js up to date

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3715]
https://github.com/vadikom/smartmenus/releases

Making a note of the diff (`git diff -R`) between our current version of SmartMenus (1.0.0) vs the vanilla 1.0.0:

```diff
diff --git b/core/misc/smartmenus/addons/keyboard/jquery.smartmenus.keyboard.js a/core/misc/smartmenus/addons/keyboard/jquery.smartmenus.keyboard.js
index 289f6069f..53b85b7e8 100644
--- b/core/misc/smartmenus/addons/keyboard/jquery.smartmenus.keyboard.js
+++ a/core/misc/smartmenus/addons/keyboard/jquery.smartmenus.keyboard.js
@@ -44,7 +44,7 @@
 			this[0].focus();
 		}
 		return this;
-	}
+	};
 
 	$.extend($.SmartMenus.Keyboard = {}, {
 		docKeydown: function(e) {
diff --git b/core/misc/smartmenus/css/sm-core-css.css a/core/misc/smartmenus/css/sm-core-css.css
index b0717753b..bad559e0a 100644
--- b/core/misc/smartmenus/css/sm-core-css.css
+++ a/core/misc/smartmenus/css/sm-core-css.css
@@ -2,7 +2,7 @@
    You need this once per page no matter how many menu trees or different themes you use.
 -------------------------------------------------------------------------------------------*/
 
-.sm{position:relative;z-index:9999;}
+.sm{position:relative;z-index:998;}
 .sm,.sm ul,.sm li{display:block;list-style:none;margin:0;padding:0;line-height:normal;direction:ltr;text-align:left;-webkit-tap-highlight-color:rgba(0,0,0,0);}
 .sm-rtl,.sm-rtl ul,.sm-rtl li{direction:rtl;text-align:right;}
 .sm>li>h1,.sm>li>h2,.sm>li>h3,.sm>li>h4,.sm>li>h5,.sm>li>h6{margin:0;padding:0;}
@@ -11,4 +11,7 @@
 .sm a{display:block;}
 .sm a.disabled{cursor:not-allowed;}
 .sm:after{content:"\00a0";display:block;height:0;font:0px/0 serif;clear:both;visibility:hidden;overflow:hidden;}
-.sm,.sm *,.sm *:before,.sm *:after{-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box;}
\ No newline at end of file
+.sm,.sm *,.sm *:before,.sm *:after{-moz-box-sizing:border-box;-webkit-box-sizing:border-box;box-sizing:border-box;}
+
+/* Additional rules moved from themes to the core.css file for Backdrop: */
+.sm-nowrap>li>a, .sm-nowrap>li>:not(ul) a{white-space: nowrap;}
diff --git b/core/misc/smartmenus/jquery.smartmenus.js a/core/misc/smartmenus/jquery.smartmenus.js
index 8735d2c82..270cb2353 100644
--- b/core/misc/smartmenus/jquery.smartmenus.js
+++ a/core/misc/smartmenus/jquery.smartmenus.js
@@ -1127,7 +1127,7 @@
 				if (!('onorientationchange' in window) || e.type == 'orientationchange') {
 					var isCollapsible = this.isCollapsible();
 					// if it was collapsible before resize and still is, don't do it
-					if (!(this.wasCollapsible && isCollapsible)) { 
+					if (!(this.wasCollapsible && isCollapsible)) {
 						if (this.activatedItems.length) {
 							this.activatedItems[this.activatedItems.length - 1][0].blur();
 						}
@@ -1211,4 +1211,4 @@
 	};
 
 	return $;
-}));
\ No newline at end of file
+}));
```

---
~PR by @klonos https://github.com/backdrop/backdrop/pull/2678~
PR by @justafish https://github.com/backdrop/backdrop/pull/2880

**Comment by klonos** [comment]
- [ ] [1.0.1](https://github.com/vadikom/smartmenus/releases/tag/1.0.1) Nov. 1, 2016 | [commit](https://github.com/vadikom/smartmenus/commit/7f5845d0129caff70415f3a7b1acd6265f3011ee)
  - Added support for the [`data-sm-options`](https://www.smartmenus.org/docs/#data-sm-options) attribute on the root `<ul>` element
  - CSS bug fixes for the themes

**Comment by klonos** [comment]
- [ ] [1.1.0](https://github.com/vadikom/smartmenus/releases/tag/1.1.0) Sep. 17, 2017 | [commit](https://github.com/vadikom/smartmenus/commit/9a73dd16049c8ac0b000d0c7b23b47defed61015)
  - support jQuery 1.7+ (no more 1.4.4+)
  - support jQuery "slim" versions (no JS errors any more)
  - new Bootsrap 4 addon
  - new option `collapsibleBehavior`
  - remove Compass dependency in the themes
  - replace `bind`/`unbind`, `delegate`/`undelegate` with `on`/`off` in the JS
  - replace `:before`/`:after` with `::before`/`::after` in the CSS
  - fix: themes SCSS files renamed to avoid filename issue for `@import` in node-sass (e.g. from `_sm-blue.scss` to `_sm-blue-theme.scss`)
  - deprecate and remove `overlapControlsInIE` option

**Comment by klonos** [comment]
I have filed a PR and done separate commits for:

- The actual update of all files with the respective ones in 1.1.0
- Repeating the customizations we have previous had in place for the 1.0.0 version
- Update the `jquery.smartmenus.combined.js` file (which was simply copy-pasting the respective contents of the .min.js files)

I have tested this on my local and on the PR sandbox, and things have obviously been broken ...but I luck the skills to troubleshoot and fix things. Consider my PR as "legwork" done; now someone should step in and do the actual work 😅

**Comment by jenlampton** [comment]
This PR is working great for me in the sandbox. I also reviewed the code and it looks like the only changes are to the sm library itself, and how the files are added in `core/modules/system/system.module`.

**Comment by klonos** [comment]
...we need to remove the `demo` folder

**Comment by klonos** [comment]
...also `jquery.smartmenus.combined.js` has been removed; but the comments from the existing file are `This file is combined for Backdrop distribution, as we always need both.`

**Comment by jenlampton** [comment]
> ...also jquery.smartmenus.combined.js has been removed; 

That was intentional, this was what was causing the problems with your PR.

**Comment by quicksketch** [comment]
I was looking at the `jquery.smartmenus.combined.js` file and how/why we put it in. I think it was because (as stated in the code comments), we always need both, so why add them separately? But that line of thinking may be out of date. When we made Basis the default core theme, it added a dozen separate CSS files. But now we have CSS/JS aggregation on by default. And HTTP/2 has made it so that separate files (and HTTP requests) don't have the same overhead as they did previously.

So from a maintenance perspective, I think the splitting of the two files is fine.

I am in support of removing the demo folders.

**Comment by quicksketch** [comment]
Thanks @justafish and @klonos! I've merged https://github.com/backdrop/backdrop/pull/2880 into 1.x for 1.14.0.
