### ISSUE TITLE
[DX] Add back views_clean_css_identifier as a wrapper for backdrop_clean_css_identifier

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3716]
In https://github.com/backdrop/backdrop/pull/2590/files I noticed a problem with a PR that may have been caused by a missing function that was in views, but is not in Backdrop core. In an effort to make Backdrop as backwards-compatible as possible, I'd like to add back `views_clean_css_identifier()` as a wrapper for `backdrop_clean_css_identifier()` as follows:

```
/**
 * Drupal-compatible wrapper for creating safe CSS identifiers.
 *
 * @deprecated since 1.0.0
 */
function views_clean_css_identifier($identifier, $filter = array(' ' => '-', '/' => '-', '[' => '-', ']' => '')) {
  watchdog_deprecated_function('drupal', __FUNCTION__);
  backdrop_clean_css_identifier($identifier, $filter);
}
```

The main difference between these two functions is that the default value for `$filters` in  `backdrop_clean_css_identifier()` converts underscores to dashes, while for the views version underscores are allowed. 

---
PR: https://github.com/backdrop/backdrop/pull/2616

**Comment by monsij** [comment]
Up for it @jenlampton

**Comment by klonos** [comment]
RTBC 👍

**Comment by monsij** [comment]
@klonos : Can I have a link to the existing PR ?

**Comment by klonos** [comment]
@monsij always look at the bottom of the issue summary ^^ (1st comment)

**Comment by klonos** [comment]
...actually, @jenlampton can you please move the function after `system_get_date_types()`, so that it is in alphabetical order?

**Comment by jenlampton** [comment]
Fixed @klonos

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2616 into 1.x an 1.13.x.
