### ISSUE TITLE
Replace deprecated `format_username()` in `comment.test` with `user_format_name()`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3728]
We seem to have missed that.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2619

**Comment by laryn** [comment]
Looks good to me.

**Comment by laryn** [comment]
I will say I just verified that the old function was deprecated and that the new function was the replacement, and that there were no typos. I didn't actually test.

**Comment by klonos** [comment]
...there is no way to test a test (I think); the testbot has done that for us, and all was green 🙂 

Thanks @laryn 👍

**Comment by quicksketch** [comment]
Nice! Merged https://github.com/backdrop/backdrop/pull/2619 into 1.x and 1.13.x.
