### ISSUE TITLE
Views: Where should we move any drush-related code?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3729]
As part of the tasks in #3719, we need to account for [this issue in Views 7.x](https://www.drupal.org/node/1389720), and [this respective commit](https://git.drupalcode.org/project/views/commit/c615dadb7eae26e207540344171dbc6a9a2693ce).

It seems that we have removed the `/drush` directory from our version of views, so where should that code live now? Do we support this in https://github.com/backdrop-contrib/drush ??

**Comment by quicksketch** [comment]
Yes, any core-specific commands should be moved into the backdrop-contrib drush project. Note at the time we ported Views into Backdrop, there was no backdrop-contrib/drush. So all commands are probably missing an may need to be ported.
