### ISSUE TITLE
Add NID to node block class

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3730]
**Description of the need**
When displaying a node in a block, there's no way to differentiate one node block from another based on the block classes. I was able to fix this by adding the following to my theme's `template.php` file, but I think something similar in core would be better:

```
/**
 * Prepares variables for block templates.
 */
function THEME_preprocess_block(&$variables) {
  if ($variables['theme_hook_original'] == 'block__node__content') {
    $nid = $variables['block']->settings['nid'];
    $variables['classes'][] = "block-node-$nid";
  }
}
```

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3218

**Comment by indigoxela** [comment]
A tiny change that can be really helpful for styling, as the css class is on the wrapper tag.

Sure, the `<article>` tag contained in these blocks has an id but the wrappers and title aren't accessible for special styling currently.

**Comment by BWPanda** [comment]
Thanks @indigoxela. Merged https://github.com/backdrop/backdrop/pull/3218 into 1.x.
