### ISSUE TITLE
Standardise vertical tab summary wording for content types

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3733]
On the content type configuration form, the summary wording for Revision and Menu settings varies:

![image (4)](https://user-images.githubusercontent.com/2385329/56964184-57c56780-6b63-11e9-892a-57405684e7b3.png)

I suggest making them the same (probably just 'Disabled' is the better of the two).

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3923

![Peek 2022-01-28 15-17](https://user-images.githubusercontent.com/2385329/151486611-a4d07629-0f1b-43a4-a0b6-fb55a9a1e0d2.gif)

**Comment by bugfolder** [comment]
Well, that's a nice, simple improvement. Tested, verified, WFM.

Code reviewed (both lines!), LGTM.

RTBC.

**Comment by klonos** [comment]
There's 3 different states that are possible:
1. both checkboxes unticked
2. "Show option to create new revisions" ticked / "Create new revision by default" unticked
3. "Show option to create new revisions" unticked / "Create new revision by default" ticked
4. both checkboxes ticked

I would expect the following summaries respectively:
1. Disabled
2. Optional
3. Optional, created by default
4. Always created

Given the current situation, I would classify this as a bug.

**Comment by klonos** [comment]
...well, this doesn't work as expected 🤔 ...if I have only "Create new revision by default" ticked, I expect that revisions will always be created, without giving the authors the option to not create a revision. If that is not how that option is meant to be working and is only meant to apply when revisions are enabled, then I'd expect it to be hidden away (via `#states`) if the "Show option to create new revisions" is unticked.

What is currently happening when "Show option to create new revisions" is unticked and "Create new revision by default" ticked, is that the revisions tab is not presented to authors at all and no new revision is created when updating the content.

**Comment by klonos** [comment]
...aha!: #6103

**Comment by klonos** [comment]
I have a PR in my local that looks like this, which is how I believe things should work:
![Kapture 2023-10-17 at 15 37 42](https://github.com/backdrop/backdrop-issues/assets/2423362/0dade80a-c4fb-4359-bad8-a0b99638f992)

...but until we fix #6103 the above doesn't reflect reality. So this issue here is basically blocked on that other one.

**Comment by klonos** [comment]
I've filed a PR over in #6103 that addresses this issue as well. I think that it makes sense to close this as duplicate.
