### ISSUE TITLE
[DX] Log watchdog deprecated messages when `element_validate_integer()`, `element_validate_integer_positive()` and `element_validate_number()` are being used.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3739]
I would like to see proper deprecated watchdog log messages, linking to change records in api.b.org. So, instead of this:

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback,
function 'element_validate_integer' not found or invalid function name
in _form_validate() (line 1490 of /core/includes/form.inc).
```

...I would like to see this:

```
The function _form_validate() (form.inc:1490) called
deprecated function element_validate_integer().
It will be removed in the next major release of Backdrop.
```

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2637

**Comment by klonos** [comment]
...we already have https://api.backdropcms.org/change-records/elementvalidateinteger-and-elementvalidateintegerpositive-replaced-number-element, but nothing for `element_validate_number()`. Should we include that in the same change record?

**Comment by klonos** [comment]
I have filed a PR for this here: https://github.com/backdrop/backdrop/pull/2637

- I have used `https://api.backdropcms.org/node/43955` instead of `https://api.backdropcms.org/change-records/elementvalidateinteger-and-elementvalidateintegerpositive-replaced-number-element`, but please let me know if I should use the pretty URL.

- I have used `drupal` as `$type` for the deprecated message, but I eventually would like to see this parameter become more useful: #3740 

- I have also linked `element_validate_number()` to [the same change record](https://api.backdropcms.org/node/43955), since we don't actually have one for that function specifically. That's why this issue here has the `type - documentation` and `needs - documentation` labels. If we decide to create a separate change record, then I will update the PR to link to that. If we decide to keep the same change record for all these 3 functions, then the PR can remain as is, and the change record will be updated to include `element_validate_number()`.

**Comment by jenlampton** [comment]
this issue has a PR so can be added to the next bug-fix release milestone.

**Comment by laryn** [comment]
Note: the `number` type (and options like min, max, step) doesn't show up in the [Form API Reference](https://api.backdropcms.org/form_api) page, either.

**Comment by herbdool** [comment]
@laryn can you make a new issue for adding that to Form API?

**Comment by herbdool** [comment]
Thanks @klonos looks good!

**Comment by klonos** [comment]
...to take care of the loose ends, I've filed a follow-up for @laryn's comment, and I've updated the api.b.org change record from this:

> element_validate_integer() and element_validate_integer_positive() have been removed.

>The `element_validate_number()`, `element_validate_integer()` and `element_validate_integer_positive()` functions have been removed, in favor of a proper HTML5 number element in Form API.

Feel free to change/tweak the change record.

**Comment by BWPanda** [comment]
Thanks @klonos and @herbdool for the PR and review. I've merged https://github.com/backdrop/backdrop/pull/2637 into 1.x and 1.16.x.

**Comment by laryn** [comment]
> I've filed a follow-up for @laryn's comment

Thanks @klonos!
