### ISSUE TITLE
Admin tables are missing a bottom border

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3741]
**Description of the bug**

In seven, admin tables have left and right borders, but no bottom border. This leaves things feeling unfinished when the bottom row is white. 

I recommend we add the following to seven:

```
table.body {
  border-bottom: 1px solid #f7f7f7;
}
```

**Steps To Reproduce**
To reproduce the behavior:
1. Go to the dashboard
3. look at the tables in the right hand column:

* left border
* right border
* NO BOTTOM BORDER

<img width="666" alt="Screen Shot 2019-05-01 at 5 46 46 PM" src="https://user-images.githubusercontent.com/397895/57051992-274ffd00-6c39-11e9-9f74-c975ea5437fa.png">

---
~~PR by @matthui: https://github.com/backdrop/backdrop/pull/2695~~
PR: https://github.com/backdrop/backdrop/pull/2714

**Comment by matthui** [comment]
Added a pull request
https://github.com/backdrop/backdrop/pull/2695

**Comment by laryn** [comment]
Here's what it looks like in the sandbox:
![Screenshot_2019-05-20 Dashboard PR 2695 backdrop backdrop testing site](https://user-images.githubusercontent.com/871421/58069170-cb9ed280-7b59-11e9-968f-70a42b7fcf04.png)

**Comment by klonos** [comment]
Yeah the situation has improved, but still not good enough IMO. Perhaps we need a darker gray for the border (used `#eeeeee` in this example)?:

<img width="583" alt="Screen Shot 2019-05-21 at 3 14 54 pm" src="https://user-images.githubusercontent.com/2423362/58070174-6986b180-7bdb-11e9-8d53-2e65c822c2a5.png">

 ...by the way, making the border darker via the browser code inspector makes it obvious that there is a 1px difference between the header and the other table rows (only on their right border):

<img width="214" alt="Screen Shot 2019-05-21 at 3 15 47 pm" src="https://user-images.githubusercontent.com/2423362/58070211-87ecad00-7bdb-11e9-9585-8e7b2e464fef.png">

**Comment by laryn** [comment]
The header has rounded corners -- do we want that on the bottom, too?

**Comment by jenlampton** [comment]
No, just the header.

**Comment by klonos** [comment]
I second that: only the header should have rounded corners.

**Comment by quicksketch** [comment]
The current PR also adds a bottom border on _all_ odd rows. I think the intention here was to only add it at the bottom of the entire table?

I think we should try to get an opinion from @dariusgarza on this. Most borders within Backdrop's Seven are heavy 2px borders, and only around the outside of things. I think the no-border on tables is an intentional design choice, as we're talking about _all_ tables here, not just the dashboard.

It's possible that the existing border on the left/right was entirely unintentional. One most pages you can't visibly distinguish them. The border color is `#f7f7f7`but the background color is `#fafafa`. That's indistinguishable to all but the most observant. Perhaps we could pull up the original designs and check?

**Comment by jenlampton** [comment]
Posted a new PR that only adds a bottom border to the `tbody`:
<img width="673" alt="Screen Shot 2019-05-31 at 5 27 47 PM" src="https://user-images.githubusercontent.com/397895/58741004-77051e00-83c9-11e9-85cc-6418be55568f.png">

**Comment by quicksketch** [comment]
For anyone else going digging like I did, the original Seven Redesign issue is https://github.com/backdrop/backdrop-issues/issues/736 and we have a styleguide at http://backdrop-ops.github.io/styleguide/#table

Unfortunately the border seemed to be present on the sides but missing at the bottom even in those cases. So there's nothing new/different there.

Adding _just_ to the bottom row though seems inconsequential. I just read the PR and was worried about adding a border to every row.

**Comment by quicksketch** [comment]
> Posted a new PR that only adds a bottom border to the tbody:

Looks good but if we want to minimize any design changes and attempt to just fix this overlooked item, then we should match the left/right borders.

**Comment by jenlampton** [comment]
The styleguide only shows the tables on a gray background. In the case of the dashboard, the background is already white. I think we may not have considdered the white on white situation. I'm happy to revisit table styles, but would prefer to do that as a follow-up :)

**Comment by klonos** [comment]
What @jenlampton said @quicksketch ^^ ...fix the missing border now, so it doesn't look bad ...follow-up to nit-pick.

**Comment by dariusgarza** [comment]
Little more context, before/after would help me put the issue into
perspective...been a while ;)

**Comment by jenlampton** [comment]
@dariusgarza I'll write the out the whole saga over here:
https://github.com/backdrop/backdrop-issues/issues/3841

With pretty pictures :)
