### ISSUE TITLE
Add field_formatter_settings module to backdrop_merged_modules()

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3742]
**Description of the bug**
Follow-up to https://github.com/backdrop/backdrop-issues/issues/1376, where Field Formatter Settings was merged into core.

We need to uninstall the contrib version of Field Formatter Settings when upgrading to Backdrop 1.13.0

**Steps To Reproduce**
To reproduce the behavior:
1. Install Backdrop 1.12.6
2. Install https://github.com/backdrop-contrib/field_formatter_settings via UI or manually.
3. Upgrade to Backdrop 1.x latest (or Backdrop 1.13.0-preview), be sure to run update.php
4. Manage fields on a content types. 

**Actual behavior**
* You may get function already defined error for `field_formatter_settings_get_instance_display_settings()`.

**Expected behavior**
* Field Formatter Settings module should be uninstalled during the update and should not be possible to re-enable in the UI.

We should also add `@since` to all the new functions added in https://github.com/backdrop/backdrop/pull/2493/files. Sometimes that difficult to do during development because we don't know when the feature will be merged, so let's use this opportunity to include `@since 1.13.0` now that we know it's version.

---
PR: https://github.com/backdrop/backdrop/pull/2644

**Comment by opi** [comment]
Should we copy/paste https://github.com/backdrop/backdrop/pull/2564/files (Issue #3485: Add options_element in backdrop_merged_modules()) ?

I left a comment on this merged PR: https://github.com/backdrop/backdrop/pull/2564/files#r280312750

**Comment by quicksketch** [comment]
Yeah, just copying what we have before is probably what we want here. As with Options Element, this should probably go in field.install.

**Comment by opi** [comment]
PR https://github.com/backdrop/backdrop/pull/2644 roughly tested with following steps

```
cd path/to/backdrop
git checkout 1.12.6
drush dl field_formatter_settings && drush en -y field_formatter_settings
git checkout opi/3742-add-field_formatter_settings-to-backdrop_merged_modules
drush updb
drush pm-list | grep field_formatter_settings
```

The last drush command shows that field_formatter_settings contrib module is now disabled.

**Comment by herbdool** [comment]
RTBC

**Comment by laryn** [comment]
FYI I've made a new release of the [contrib version](https://github.com/backdrop-contrib/field_formatter_settings) that has a dependency on `system` being less than 1.13. (`dependencies[] = system (<1.13)`)

**Comment by opi** [comment]
Thank you both :heart:

**Comment by klonos** [comment]
...wondering if it's worth moving the code we are reusing into a `backdrop_remove_merged_modules()` function, and then calling that from the update hooks (we are going to be merging more modules as time goes by).

**Comment by quicksketch** [comment]
That's a great idea @klonos! We have a set of utility-like functions in `includes/update.inc` that includes things like `update_variable_get()` and `update_module_enable()`. Creating an `update_module_uninstall()` or even `update_module_uninstall_merged_module()` could get rid of redundancy.

**Comment by quicksketch** [comment]
I don't want to hold this up, so we can consolidate those similar places in a follow-up issue.

I've merged https://github.com/backdrop/backdrop/pull/2644 into 1.x for 1.13.0 (and the preview release). Thanks @opi, @herbdool, @laryn, and @klonos!

**Comment by klonos** [comment]
> That's a great idea @klonos! ...I don't want to hold this up

#3760 😉
