### ISSUE TITLE
Date resets to now if an editor doesn't have full 'Administer content' permission

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3744]
**Description of the bug**
I was trying to set up an Editor role and it seems if people don't have access to the full "Administer content" permission it is resetting the created date on content when they simply edit an existing page.

**Steps To Reproduce**
To reproduce the behavior:
1. Create an 'editor' role.
2. Give this role permission to edit some content types but not full "Administer content" permissions.
3. Edit some existing content (note the created date if possible). You shouldn't see all of the details in the vertical tabs at the bottom.
4. Check the `created` date on the content. 

**Actual behavior**
Created date has been reset to the current date/time.

**Expected behavior**
Created date should remain as it was.

---
PR: https://github.com/backdrop/backdrop/pull/2640

**Comment by laryn** [comment]
The PR is a dirty fix because I discovered this on a live site. I'm guessing it may not be the best way to handle this.

I found that [these lines](https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/node.module#L1006-L1009) seem to be the issue:

 - When logged in with "Administer content" permission, `$node->date` comes back as a string: e.g. `2019-05-02 11:52`
 - When logged in without "Administer content" permission, it comes back as an array: e.g. `array ( 'date' => '2019-05-02', 'time' => '11:52 am', )`

**Comment by klonos** [comment]
Could be unrelated, but sounds similar ([Node Export 7.x](https://www.drupal.org/project/node_export)): [imported data has changed date reset to current](https://www.drupal.org/project/node_export/issues/2839976)

I have filed a meta to consider some date-related issues from Drupal land: #3747

**Comment by klonos** [comment]
...it seems that that whole `// Convert the date into a timestamp.` bit is something that we have introduced in Backdrop. It's not there in the respective D7 core code: https://git.drupalcode.org/project/drupal/blob/7.x/modules/node/node.module#L1052

**Comment by herbdool** [comment]
@klonos an even quicker way to find out is to click on the blame button. https://github.com/backdrop/backdrop/commit/260628a5500e8c00c39b94af494a010f86f179e0

**Comment by herbdool** [comment]
I've RTBCed it with a little tweak.

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2640 into 1.x and 1.12.x.
