### ISSUE TITLE
Dashboard menu shows even if user doesn't have dashboard permission

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3745]
**Description of the bug**
I was testing a separate PR in a new sandbox and saw the Dashboard when I logged in as admin -- awesome! That PR involved setting up a user that has editor permissions, but not full admin permissions and I gave access to the admin menu and some content types only. The Dashboard link also shows up (but in this case it doesn't work).

![Screen Shot 2019-05-02 at 12 36 24 PM](https://user-images.githubusercontent.com/871421/57094765-ef979280-6cd6-11e9-8b4a-fa307c36af22.jpg)

This menu item should be hidden if the user doesn't have permission to view the Dashboard.

~~PR by @laryn (not working): https://github.com/backdrop/backdrop/pull/2641~~
~~Alternate PR by @drupol: https://github.com/backdrop/backdrop/pull/2680~~
Alternative PR by @herbdool https://github.com/backdrop/backdrop/pull/2681

**Comment by laryn** [comment]
Hmm... I thought I could quickly fix it in browser but it doesn't seem to work in the sandbox. 😞

**Comment by herbdool** [comment]
Maybe remove the access check on the overview menu? Or vice versa?

**Comment by olafgrabienski** [comment]
I've had a look at the PR in the sandbox. As a user with the `Editor` role I still see "Dashboard" link in the Admin bar. (And when I click it, I get a "Page not found" error.)

**Comment by drupol** [comment]
I tried to do that

```php
function dashboard_menu() {
  $items = array();

  // Check if any dashboard is present and is not disabled.
  $dashboard_layouts = layout_load_multiple_by_path('admin/dashboard');
  $dashboard_layout = array_pop($dashboard_layouts);
  if (!$dashboard_layout->disabled && $dashboard_layout->hasContexts(array('dashboard'))) {
    $items['admin/dashboard'] = array(
      'title' => 'Overview',
      'type' => MENU_NORMAL_ITEM,
      'weight' => -100,
      'access arguments' => array('access dashboard'),
      'description' => 'Get an overview of your site and manage administrative tasks.',
    );
    $items['admin/dashboard/overview'] = array(
      'title' => 'Overview',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -100,
      'access arguments' => array('access dashboard'),
    );
    $items['admin/dashboard/settings'] = array(
      'title' => 'Settings',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('dashboard_admin_settings'),
      'description' => 'Admin dashboard settings',
      'access arguments' => array('administer dashboard'),
      'type' => MENU_LOCAL_TASK,
      'weight' => -10,
    );
  }

  return $items;
}
```

But it's not working, I'm digging.

**Comment by herbdool** [comment]
I've taken a different approach by just adding access control to the dashboard menu item in the JSON file.

**Comment by jenlampton** [comment]
I love this approach @herbdool. Nice and simple, plus visible to the admin so there's no magic involved. RTBC.

**Comment by quicksketch** [comment]
Looks great, merged https://github.com/backdrop/backdrop/pull/2681 into 1.x for 1.13.0. Thanks folks!

**Comment by drupol** [comment]
I think I know why it was failing on my PR #2680 ... you must reinstall Backdrop once the file `core/modules/dashboard/config/layout.menu_item.dashboard.json` is removed.

**Comment by klonos** [comment]
Hey @drupol 👋 FYI, closing the PR and then reopening it will refresh the sandbox. Please wait a couple of minutes between closing and reopening though, to allow the CI to clean things up properly.
