### ISSUE TITLE
Views field handler chokes on multilingual

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3746]
**Description of the bug**
On a multilingual upgrade, I am seeing this:

> Notice: Undefined property: stdClass::$language in views_handler_field_field->field_language() (line 970 of /path/core/modules/field/views/views_handler_field_field.inc).

PR: https://github.com/backdrop/backdrop/pull/2642

**Comment by laryn** [comment]
Just upgraded this dev site to 1.13.0 and got hit with this again. 😄

**Comment by herbdool** [comment]
@laryn what's the best way to test this? Does the issue only appear on upgrade?

**Comment by laryn** [comment]
@herbdool Hmm... I only see it on one site (every time I upgrade) but I'll try to find a way to reproduce on a site if I can...

**Comment by indigoxela** [comment]
There's at least on additional appearance of that code:

```
> grep -nr 'language_content->language' core/modules/field
core/modules/field/views/views_handler_field_field.inc:256:                                array($language_content->language, $default_language),
core/modules/field/views/views_handler_field_field.inc:974:                              array($language_content->language, $default_language),
```
@laryn I'm pretty sure, your finding is correct, this should be "langcode".

On the other hand it's impossible to verify without getting that code to run.

In a "normal" Backdrop installation it never runs because `field_is_translatable()` always returns false.

Maybe it helps if you provide a little more info about your install. Which contrib modules are installed? Anything that registers a field translation handler?

**Comment by laryn** [comment]
@indigoxela This was an upgrade from Drupal 7, which had entity translation installed at the time. I've basically converted it to Backdrop's core content translation now but perhaps some settings deep within are causing this...

**Comment by laryn** [comment]
I've updated the PR to get the second occurence as well.

**Comment by indigoxela** [comment]
It's still tricky to test this. Can you check your active config, if any of your fields is marked as "translatable"?

In case you have shell access to that install:

`grep translatable /path/to/confg..../field.field.*.json`

**Comment by laryn** [comment]
@indigoxela Yes, when I look in field configs I see:

`    "translatable": "1",`

Should I change that to a `0`?

**Comment by indigoxela** [comment]
> Should I change that to a 0?

That should fix your problem. But I wonder, how this "1" (true) came in. Do all your (migrated) fields have that value, or is it just a single one? Which type(s)?

**Comment by laryn** [comment]
I assume it carried over in the upgrade somehow -- there are a bunch of fields that have this value, but the migration was some time back so I don't know which fields came from the migration (or were not translatable on the old site). 

This does give me a way to provide STR, however:

1. Export config for the `body` field.
2. Change `translatable` to `1`.
3. Import this updated config.
4. Activate language/translation modules and add a new language.
5. Enable multilingual/translation on the `Post` content type.
6. Create a view that displays fields rather than rendered content.
7. Check the logs after viewing or previewing the output of this view.

![Screen Shot 2020-08-06 at 3 00 18 PM](https://user-images.githubusercontent.com/871421/89576932-91b8fb00-d7f5-11ea-9035-c625f3c66b13.jpg)

**Comment by indigoxela** [comment]
Yep, now we are able to test and verify. RTBC!

**Comment by BWPanda** [comment]
Thanks @laryn & @indigoxela! Merged https://github.com/backdrop/backdrop/pull/2642 into 1.x and 1.16.x.
