### ISSUE TITLE
[UX] Remove the hover color from header account links in Basis

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3748]
While testing https://github.com/backdrop/backdrop-issues/issues/3209 I found it distracting that the account links in the Header area had a hover color. I would prefer that they have an underline while hovered.

I was distracted by the big color block, especially when it does not reach the top of the menu area. I don't think we should treat them the same way as the main menu.

---
PR by @jenlampton: https://github.com/backdrop/backdrop/pull/2822

**Comment by klonos** [comment]
I've left a comment and a suggestion in the PR @jenlampton

**Comment by klonos** [comment]
Thanks for fixing @jenlampton 👍 RTBC!

**Comment by quicksketch** [comment]
I also approve of this change. Though this has design implications. @wesruv what do you think?

**Comment by quicksketch** [comment]
Before:
![image](https://user-images.githubusercontent.com/100206/63241983-83e81f80-c20a-11e9-9c07-ccb4c88133c8.png)

After:
![image](https://user-images.githubusercontent.com/100206/63242005-9e21fd80-c20a-11e9-9a7a-833ec125e9d5.png)

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2822 into 1.x for 1.14.0. Changes that directly affect the front-end appearance I think are better left to minor versions. So if it's acceptable I won't cherry-pick this into 1.13.x.
