### ISSUE TITLE
Multilingual typo in menu.inc

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3751]
**Description of the bug**

> Notice: Trying to get property of non-object in menu_tree_output() (line 1132 of /path/core/includes/menu.inc).

Debugging shows that `$data['link']['language']->langcode` should be simply `$data['link']['language']`.

PR: https://github.com/backdrop/backdrop/pull/2643

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Is there a way to reproduce this problem? Usually we use `language` to refer to a language object, while `langcode` is used if it's a string. I searched menu.inc for where language would be set but I'm not seeing it easily

**Comment by laryn** [comment]
@quicksketch I'll see if I can come up with a way to reproduce. It was an upgrade from a D7 site with Entity Translation, so... I'll let you know.

**Comment by klonos** [comment]
> t was an upgrade from a D7 site with Entity Translation ...

I have added this issue to the "Upgrade path" project.

**Comment by laryn** [comment]
@quicksketch So I'm seeing this again after upgrading core on this dev site. It's not necessarily a way to reproduce on a separate site, but a `dpm($data['link']['language']);` just before line 1132 produces a bunch of the following:
 - `en`
 - `und`
 - etc.

Various menu items are either not translated yet or in English.

When I activate Language and Locale on a dev site, `$data['link']['language']` is not even set, although `$data['link']['langcode']` is. Strangely, I did `dpm($data['link']);` on the dev site at this point for comparison, and `$data['link']['langcode']` exists there, too. It doesn't always even match `$data['link']['language']` though. (ie. on one entry, one was `und` and one was `en`.)

Does that mean this is just cruft from the upgrade process somehow?

**Comment by quicksketch** [comment]
Yeah, I think it must be. We probably need to add an update hook that changes `$data['link']['language']` to `$data['link']['langcode']`. This may be the result of using the i18n Menu Translation module in D7 and moving to Backdrop, which provides core menu item translation.

**Comment by laryn** [comment]
@quicksketch I updated the PR to change 'language' to 'langcode' on that line -- is that what you meant? The notice does go away after I made that change.

**Comment by quicksketch** [comment]
Ah, well yeah if that does the job! I didn't understand that "langcode" was already set. If that's it then this looks good.

Merged https://github.com/backdrop/backdrop/pull/2643 into 1.x and 1.13.x.
