### ISSUE TITLE
Remove all implementations of hook_help()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3758]
I was just poking around in Text module and noticed an implementation of hook_help(), which is never called. We should clean these out:

* ./field.module: * Implements hook_help().
* ./modules/field_sql_storage/field_sql_storage.module: * Implements hook_help().
* ./modules/list/list.module: * Implements hook_help().
* ./modules/number/number.module: * Implements hook_help().
* ./modules/options/options.module: * Implements hook_help().
* ./modules/text/text.module: * Implements hook_help().

**Comment by BWPanda** [comment]
I couldn't find any implementations of `hook_help()` in core anymore, so they must have been cleaned up already.

I did, however, find one reference to it in a docblock as an example that I thought should be replaced with a real hook. Here's a PR: https://github.com/backdrop/backdrop/pull/3349

**Comment by stpaultim** [comment]
Just ran into this same example in the code and was looking to see if it's still necessary. We should be able to commit this and close this issue.

**Comment by klonos** [comment]
Yes, would be good to clone this old one off.

**Comment by BWPanda** [comment]
Thanks @jenlampton, @stpaultim & @klonos. I've merged https://github.com/backdrop/backdrop/pull/3349 into 1.x and 1.20.x.
