### ISSUE TITLE
Documentation for adding keys along with fields is confusing.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3759]
The **$keys_new** parameter for `db_add_field()` is not explained well in the docblock in `core/includes/database/database.inc` or [our API](https://api.backdropcms.org/api/backdrop/core%21includes%21database%21database.inc/function/db_add_field/1)

I spent forever trying to wrap my head around what this meant:

> Optional keys and indexes specification to be created on the table along with adding the field. The format is the same as a table specification, but without the 'fields' element. If you are adding a type 'serial' field, you MUST specify at least one key or index including it in this array. See db_change_field() for more explanation why.

I recommend we reword this as follows:

> Optional. An array containing the specification for keys and indexes to be created on the table along with the field. The format is the same as a schema definition, but without the 'columns' element.  If you are adding a 'serial' type field, you MUST specify at least one key or index in this array. See db_change_field().

Of note: 
* we do not have a `fields` element, we do ave a `columns` element.
* `table specification` is ambiguous, `schema definition` has a concrete meaning.

**Comment by jenlampton** [comment]
The PR here looks great, and since it's only a documentation change, it does not need to be tested. RTBC!

**Comment by quicksketch** [comment]
Thanks to new contributor @nzare for the PR at https://github.com/backdrop/backdrop/pull/3651! I have merged the PR into 1.x and 1.19.x. Thanks @jenlampton and @BWPanda for reviewing!
