### ISSUE TITLE
Changing layout templates can result in loss of blocks if there are no matching regions in the new template

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3762]
**Description of the bug**
When switching between layout templates, blocks can disappear if there are no matching regions in the new layout template.

This is not a big deal for non-custom blocks (although still a UX WTF), since they are not completely gone and can be re-added; whereas custom blocks, if they're not set to reusable, are gone gone.

**Steps To Reproduce**
To reproduce the behavior:
1. Add a block to the home layout and save.
2. Change layout template for home and save.

**Actual behavior**
Block will be gone.

**Expected behavior**
All blocks should end up somewhere, either in a nearby region or in a "dummy" region where they can stay until manually moved to a different layout.

-------
PR https://github.com/backdrop/backdrop/pull/2662

**Comment by klonos** [comment]
If implementing this "dummy", "bucket" region to be available in every layout template is not immediately implementable, we should at the very least be checking which blocks will be removed, and show a warning to the user (I vote to also prevent them from making the change) ...alternatively, simply randomly choose an existing region in the new template, and move all these otherwise-to-be-lost blocks there. Anything at this point would be better than the current data-loss situation (in the case of custom, non-reusable blocks).

**Comment by klonos** [comment]
Cross-linking #1936 ...if we had this "dummy" region persist (i.e don't hide it if no blocks in it), then we could use it to hide/disable blocks. Not saying that this is the ideal solution for #1936, but people could use it that way 😉

**Comment by herbdool** [comment]
I agree we need a short term fix for this issue. And also that longer term we have a dummy region or a new dialog that lets you decide which region to put all the orphan blocks. Panels had something similar. And it didn't save automatically when changing the template.

The short term fix could show an error and prevent saving though could be difficult for people to know how to fix it since they aren't shown what are the region names. Better than nothing though.

**Comment by herbdool** [comment]
Turns out the validation function gets called before the checking if a block doesn't fit, which I guess makes sense so we'd need logic to double check during validation.

It's actually easier to have the form save the orphan blocks into the last (or first) region and display a message which blocks were orphans and where they are, suggesting the user fix it manually. That's probably better for the user.

**Comment by herbdool** [comment]
@klonos ready for testing https://github.com/backdrop/backdrop/pull/2662

**Comment by herbdool** [comment]
As a try to change the expectations of the automated test, it makes me realize it's not something we can include in a patch release. The tests expect the blocks to disappear when the template changes. So a bug fix would be to show a warning (after the layout is already saved) but not change any behaviour. And for 1.14.x we could have it reassign the blocks.

**Comment by stpaultim** [comment]
I just tested and this works for me. 

I'm anxious to help with this issue, I've gotten bit by this bug a few times lately.

**Comment by klonos** [comment]
The solution in the PR takes us to a better place than what we currently have. Thanks @herbdool 👍

I would suggest that instead of multiple messages for each orphan block, we have a single "The following blocks ..." message, with all the orphan blocks in a list.

**Comment by jenlampton** [comment]
I have one concern with the PR, and that's that the orphaned blocks get added into the "last region" instead of the pre-defined `default region` for the layout. Comment added on PR.

**Comment by klonos** [comment]
I don't mind either way TBH, because in the end, we are moving these blocks to an arbitrary region. I would like us to eventually have a separate, dedicated, "dummy" region for that (which should be a follow-up, as mentioned before).

**Comment by stpaultim** [comment]
I didn't know about `default region`. If there is a `default region` then I assume it's to be used for exactly this kind of thing and we should make use of it. 

However, I assume it's possible that a contrib or custom layout might not have a default region defined. Do we have a way of enforcing this? Throwing a warning if the user enables a theme without any "default" region?

If we can't be sure that there is a defined default region, then we need to include a backup plan and the last regions seems to work for that. 

In an ideal world, I think the process would work like this:

1) Anytime a user enables a theme without a defined `default region` they get a warning letting them know that every layout should have a default region. 
2) If a user enables a layout and there are orphaned blocks, they are automatically put into the default region. 
3) If no `default` region is available, they are put into the last `region` or a `dummy` region if that makes better sense. I don't know if we want to be that heavy handed, but we could prevent the enabling of layouts without a `default region.`

In today's world, I'd love to see this PR progress as temp solution if we are not able to decide on best solution quickly.

**Comment by jenlampton** [comment]
> I didn't know about default region. If there is a default region then I assume it's to be used for exactly this kind of thing and we should make use of it.

Yep :) It's also where the "content" comes out for any page that does not have it's own layout override.

> I would like us to eventually have a separate, dedicated, "dummy" region for that

But..  we already have a default region.

> If we can't be sure that there is a defined default region

Any region named `content` is already used as the `default region` elsewhere in core, if no default is defined. I'm not sure that will come through as the `default region` here, if it wasn't defined that way. You should test this and see, and if not and make sure `content` is for the first fallback.

1) defined `default region`
2) if not 1, a region named `content`
3) if not 1 or 2, the last region is fine :) -- this is such a limited use-case I don't think we need to add another dummy region @klonos

**Comment by herbdool** [comment]
Ready for a code review. And perhaps another test that now the blocks end up in the default region if it exists (or last region if not).

**Comment by klonos** [comment]
@herbdool please see my PR agains yours here: https://github.com/herbdool/backdrop/pull/6

It makes it so that the block names in the warning are rendered in a list, which makes it more readable when there are numerous blocks...

Before:

![Screen Shot 2019-07-23 at 12 53 23 pm](https://user-images.githubusercontent.com/2423362/61679825-dc7ee680-ad4a-11e9-963d-e3083df75f06.png)

After:

![Screen Shot 2019-07-23 at 1 04 40 pm](https://user-images.githubusercontent.com/2423362/61679821-d8eb5f80-ad4a-11e9-9012-efe73875aae8.png)

**Comment by herbdool** [comment]
Thanks @klonos. I've updated the message.

Still needs code review.

**Comment by klonos** [comment]
Thanks @herbdool 👍 both @docwilmot and myself have left comments in the PR. Also pinging @jenlampton to have a look.

**Comment by quicksketch** [comment]
The concept and functionality of the PR look great! I posted a comment recommending we move things around a bit so that we're not setting messages directly from within Layout's methods: https://github.com/backdrop/backdrop/pull/2662/files#r310400830

**Comment by herbdool** [comment]
@quicksketch I've updated with your suggestions and changed the labels for a final review.

**Comment by quicksketch** [comment]
Super thanks! Merged https://github.com/backdrop/backdrop/pull/2662 into 1.x and 1.13.x.

Thanks to everyone who helped on this one! @herbdool, @docwilmot, @jenlampton, @klonos, and @stpaultim!

**Comment by BWPanda** [comment]
Follow-up bug report from this issue: https://github.com/backdrop/backdrop-issues/issues/4420

**Comment by jenlampton** [comment]
Related: https://github.com/backdrop/backdrop-issues/issues/6461
