### ISSUE TITLE
[UX] Enable autocomplete on all link/path fields

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3764]
**Description of the need**
One of the things I hate when teaching a client how to use their new Backdrop site is linking to internal pages. The conversation goes something like this:

"And here's a link field where you can link to any page on your site, or to any other website. For linking to pages on your site, you need to go and open that page separately, then copy the URL and then paste it here. Now when you paste the URL here, the best way to do it is to paste everything after your domain name. In other words, if you want to link to https://example.com/projects/my-awesome-project, paste in just the '/projects/my-awesome-project' part (and don't forget the beginning '/'). You can paste in the full URL, but if your domain name ever changes then your links might not work anymore."

This is convoluted and unnecessary. Firstly, having to open a new tab to find the content you want to link to so you can copy the URL, Secondly, having to only paste in part of the URL (and getting frustrated if you do it wrong).

**Proposed solution**
A better solution would be an autocomplete field that shows pages from your site when you start entering keywords. This solves both of the above problems: no need to open a separate tab to find the page yourself, and when you click on a matching result, it'll enter the proper URL for you.

This is actually already in core: https://github.com/backdrop/backdrop-issues/issues/1206 But apparently only in CKEditor. I'd like to see this feature expanded as follows:

- Enable this on any and all link/URL/path fields where internal links are supported (e.g. Link fields, menu item Path fields, Default Front Page (in Site Information), Existing System Path (when adding a URL alias), redirect From & To fields, etc.).
- Support matching all paths/URLs on the site. This includes menu items, views pages, layout pages, the contact page, etc.

**Alternatives that have been considered**
Drupal's [Linkit](https://www.drupal.org/project/linkit) module provides a lot of this functionality, but I think most of what it provides is already in Backdrop as part of the CKEditor link feature. I believe there are open issues for supporting menu items in general though (rather than just nodes, etc.). Also, [Linkit Views](https://www.drupal.org/project/linkit_views) seems to allow linking to views pages, and [Linkit Panel Pages](https://www.drupal.org/project/linkit_panel_pages) seems to do the same for Page Manager Pages.

---

PR by @BWPanda: https://github.com/backdrop/backdrop/pull/3066

**Comment by laryn** [comment]
I have the same conversations and love the idea.

**Comment by BWPanda** [comment]
I've made a PR (see 'Linked pull requests' in the sidebar) that adds this. My PR changes the code from https://github.com/backdrop/backdrop/pull/1779 to make it more generic and available all the time (e.g. moved to System module). It adds autocomplete for menu items (to support linking to the Contact form for example), and then makes the different link/path fields mentioned in the first post above work with the new autocomplete feature.

Here's a screencast demo:
![Peek 2020-02-05 22-04](https://user-images.githubusercontent.com/2385329/73878618-8a735d80-4863-11ea-97a2-21c1257774fd.gif)

**Comment by laryn** [comment]
Thanks @BWPanda!

This is great. Everything looks really good. Here are some thoughts for possible tweaking:

1. Should the admin menu be excluded by default? Seeing all those admin paths makes me wonder how often they'd actually be useful as opposed to cluttering the results.
2. Should it be activated on the 404/403 page settings?
![Screen Shot 2020-02-05 at 2 27 05 PM](https://user-images.githubusercontent.com/871421/73880465-18c7ef00-4824-11ea-81c0-8eacbc2c8b84.jpg)
3. This may be beyond scope, but if adding a path to a link field and there is an empty title field next to it, what about automatically pulling in the title of the content that is being linked?
![Screen Shot 2020-02-05 at 2 27 27 PM](https://user-images.githubusercontent.com/871421/73880434-0cdc2d00-4824-11ea-8db6-300cb6dfc156.jpg)

**Comment by BWPanda** [comment]
@laryn

1. I'm of two minds about this. One the one hand it'd be nice for people to link to whatever path they want, one the other hand I do see your point. Interestingly, the existing functionality of searching for matching Views pages only shows matches `if (!path_is_admin($path))` (so it seems to be filtering out admin paths too). If we were to do this, should we filter:
  - Paths starting with `admin/`
  - Paths in the 'Management' menu
  - 'Admin' paths (e.g. `path_is_admin()`)?

2. Absolutely. I missed those, thanks!

3. That sounds like a very nice feature to have. I'm just not sure if its possible, and if so how... Perhaps a separate issue? (unless its easy and someone can tell me how to do it)

Thanks for the review!

**Comment by BWPanda** [comment]
I've updated the PR to include points 1 and 2 from above.

On consideration re. point 1, I figured that the 80% use case is for linking to an existing, public page/path, so admin paths can be hidden from the autocomplete for simplicity and consistency with the existing Views matching. Editors can always manually enter admin paths if needed anyway.

**Comment by olafgrabienski** [comment]
Great feature! I've tested the PR in the sandbox, and it works good. Tested at these places:

- CKEditor: Link dialog (still working)
- Post: Link field √
- Menu item √
- Site information: Default Home / 403 / 404 √

I've also checked if `admin` paths are not autocompleted anymore but can still be inserted manually.

**Comment by klonos** [comment]
Awesome feature @BWPanda!! 👍 

Can we please have the content type mentioned in the bracket, like `%title% (Content - %content-type%)`? ...other wise you can end up with something like this:

![Screen Shot 2020-02-13 at 2 20 14 am](https://user-images.githubusercontent.com/2423362/74349027-bebcc000-4e07-11ea-8ff6-23898f35226c.png)

Also, show human-readable names for views displays.

**Comment by BWPanda** [comment]
I've updated the PR with suggested changes by @docwilmot and @klonos. I renamed the path to the autocomplete callback, moved the code into the System module, and changed the output of the autocomplete matches to show the type for all matches (where possible). E.g.:
![image](https://user-images.githubusercontent.com/2385329/74376938-af2f7e00-4deb-11ea-8def-f76d1fe72478.png)
All matches (the part in brackets) are now:
- Content: [content type]
- File: [file type]
- User
- Taxonomy term: [vocabulary]
- View: [human name] - [display name]
- Layout: [menu name]
- Menu item: [path]

**Comment by klonos** [comment]
...I've tested the PR sandbox, and everything works as expected, and looking good 👍 ...on minor nit re the use of "User" vs. "User account" and this is RTBC.

(by accident I've added the bug milestone label - changed that to minor candidate instead now)

**Comment by BWPanda** [comment]
PR updated to change "User" to "User account".

**Comment by BWPanda** [comment]
Merged https://github.com/backdrop/backdrop/pull/3066 into 1.x. Thanks @laryn, @olafgrabienski, @docwilmot & @klonos for your feedback and reviews! I think this is a very exciting feature! :smiley:

**Comment by docwilmot** [comment]
Belated request/idea: working on contexts PR and I want to use this to autocomplete, but filtered by entity type. Currently once you start typing it shows you every piece of content/term/whatever. 

But what if we changed the path to `path-autocomplete/%` and passed the type of content to the `path_autocomplete($string = '', $type = NULL)` function to filter by that type? Or even `path-autocomplete/%/%` and `path_autocomplete($string = '', $type = NULL, $exclude = FALSE)` to allow a negative filter.

In a form you could set `'#autocomplete_path' => 'path-autocomplete/node` to get only nodes, or, as in the case I'd like to accomplish, `'#autocomplete_path' => 'path-autocomplete/' . $context->type.`
