### ISSUE TITLE
`hide()`-ing fields cause issues with their values not being set properly

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3768]
I'm updating the [Simplify](https://github.com/backdrop-contrib/simplify) module to use [`hide()`](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/hide/1) for hiding fields from various UI forms. When testing, I noticed a problem with a required field...

On the 'Add term' form (`/admin/structure/taxonomy/[VOCABULARY]/add`), in the Relations fieldset, there's a Weight field that's required. It has a default value of '0'. If I add a new term and don't touch this field, or even expand the Relations fieldset, I can submit the form without errors. However, if I use Simplify to hide the Relations fieldset and submit the form, I get an error "Weight field is required." I would expect that since this field has a default value that hiding it wouldn't be a problem. Why does this happen? The code for the `hide()` function says that it merely sets the `#printed` value to TRUE, so I don't see how this would affect required fields...

-----

PR: https://github.com/backdrop/backdrop/pull/2675

**Comment by BWPanda** [comment]
Ok, so I worked out what's going on I think, and I believe this could be a bug...

The validation for the required Weight field happens in [`_form_validate`](https://api.backdropcms.org/api/backdrop/core%21includes%21form.inc/function/_form_validate/1). When Simplify is turned off and everything works fine, a `dpm()` of the `$elements` variable during validation shows that the `#value` of the field is `'0'`. However when I turn on Simplify and the Relations fieldset is hidden, the `#value` of the Weight field is `0` - a subtle difference, but while the string in the first instance validates, the integer in the second doesn't.

Therefore, by `hide()`-ing the field, the default `0` value never gets converted from an integer to a string. I'm assuming this is because `hide()`-ing a field prevents it getting printed, and therefore the value never gets output in a textfield (which is how I'm guessing the integer -> string conversion happens). Note that this only happens when the default value is `0`; any other value would pass validation, regardless whether it's a string or an integer.

So I guess the bug is that when a field with a default value is not printed, it's not converted to a string and therefore a default value of `0` will fail validation.

**Comment by BWPanda** [comment]
It seems there's more to this issue than I realised. When I hide the Relations fieldset, and add the code from the PR to prevent the validation error, I can submit the 'Add Term' form, and the term _is_ created in the database, but it doesn't appear in the list of terms for that vocabulary (e.g. `/admin/structure/taxonomy/[VOCABULARY]`). Since the original issue was with the Weight field, my first thought was that maybe it's at the top or bottom of the list, but even after Resetting to Alphabetical order, the term still doesn't appear. I know it's been created though as the watchdog message about its creation links to it...

**Comment by BWPanda** [comment]
Ok, so the term doesn't appear in the term list as it's not returned by `taxonomy_get_tree()`. It's not returned by that function as it's not listed in the `taxonomy_term_hierarchy` DB table. It was never added to that table as the Parent field wasn't set properly. Parent wasn't set because of the same/similar reason for the Weight field's issue - not displaying the field (as a result of `hide()`-ing it) means the `#value` is different/not set properly.

**Comment by BWPanda** [comment]
Hmm, it seems this might not be a bug after all...

https://stackoverflow.com/a/21041471/4168619 suggests that `hide()`-ing a field should only be done if you intend to display it elsewhere:

> I.e. hiding it (somewhere I saw someone suggesting that):
`hide($form['field_myfield']);`
really hides the field, but after that, when form is saved this field has empty value, validation fails, etc, so that's not a good way to do this. Hiding makes sense only if you want to print separately that field later, at some other place.

Also, https://api.drupal.org/comment/59900#comment-59900 says:

> Using hide() on field of type Date will give you a validation error, so #access = FALSE has to be used.

It seems that I was trying to use `hide()` incorrectly, and that I should be using `'#access' => FALSE` instead. Closing this issue then.

**Comment by klonos** [comment]
Good on ya for figuring this one out @BWPanda 👍

>> Also, api.drupal.org/comment/59900#comment-59900 says:
>
>Using hide() on field of type Date will give you a validation error, so #access = FALSE has to be used.

Follow-up documentation issue filed: #3788
