### ISSUE TITLE
[UX] Vocabulary overview page: Align number of terms to the right.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3780]
This is a follow-up to #3655, since this minor fix could not be merged (PR had conflicts).

> ...wondering if it might be easier to the eye if the column was aligned to the right:
> 
> <img width="813" alt="Screen Shot 2019-04-08 at 2 52 45 am" src="https://user-images.githubusercontent.com/2423362/55686827-6e83fe80-59a9-11e9-89e8-970dee7838f1.png">

---
~~PR by @klonos: https://github.com/backdrop/backdrop/pull/2676~~
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/3485

**Comment by klonos** [comment]
...the parent issue [got into 1.13 only](https://github.com/backdrop/backdrop-issues/issues/3655#issuecomment-487337485), so setting the milestone for this accordingly.

**Comment by jenlampton** [comment]
we are releasing soonish, bumping to 1.13.1

**Comment by klonos** [comment]
I have included the fix for this in the latest PR for #2029. So if that one gets accepted/merged, we'll be free to close this one here too 😉

**Comment by BWPanda** [comment]
Here's a new PR that simply adds the core `text-align-right` class to the column: https://github.com/backdrop/backdrop/pull/3485

This addresses @jenlampton's concern re. adding inline styling, and also negates the need for a new CSS file (which the linked issue that also includes this fix does).

**Comment by indigoxela** [comment]
Here's a screenshot from the sandbox:

![aligned-taxonomy-numbers](https://user-images.githubusercontent.com/842066/116813542-7563a800-ab54-11eb-9ac9-e7f1548f0ef3.png)

Works for me. :+1: 

@BWPanda I've left a tiny suggestion re code formatting, otherwise your PR looks good.

**Comment by BWPanda** [comment]
Thanks @indigoxela. PR updated.

**Comment by jenlampton** [comment]
Beautiful! RTBC :)

**Comment by BWPanda** [comment]
Thanks @klonos, @indigoxela & @jenlampton for help with this. I've merged https://github.com/backdrop/backdrop/pull/3485 into 1.x and 1.18.x.
