### ISSUE TITLE
[PS] Vocabulary overview page: use a single query with a `GROUP BY`, instead of one query per vocabulary

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3781]
This is a follow-up to #3655.

@quicksketch:

> This could be optimized using a single query with a `GROUP BY` instead of one query per vocabulary, but in the scheme of overall site speed, this seems like it would be negligible. I've merged https://github.com/backdrop/backdrop/pull/2594 into 1.x.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2682

**Comment by klonos** [comment]
...same as with #3780, the parent issue [got into 1.13 only](https://github.com/backdrop/backdrop-issues/issues/3655#issuecomment-487337485), so setting the milestone for this accordingly.

**Comment by jenlampton** [comment]
There are some unrelated changes in this PR. Tagging NW to get those removed.

**Comment by jenlampton** [comment]
we are releasing soonish, bumping to 1.13.1

**Comment by klonos** [comment]
I have closed the PR with those "extraneous" changes. I'll make sure to file a separate issue to change that once this one gets in.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2682 into 1.x and 1.13.x. Nice work @klonos!

**Comment by quicksketch** [comment]
This was missed in 1.13.2, I've now actually merged it into 1.13.x so it will be in 1.13.3.
