### ISSUE TITLE
[DX][UX] Add a full-width layout to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3783]
As was mentioned in the virtual user group today, its hard to support a striped layout  in core, and usually requires a custom layout (or some complex basis-hero style css).

If we aded a single full-width layout, we might be able to better facilitate this use-case.

**Comment by docwilmot** [comment]
Or https://github.com/backdrop/backdrop/pull/2646/files. Supports adding multiple rows, and container width is configurable.

**Comment by jenlampton** [comment]
I'm giddily testing the PR!

**Comment by klonos** [comment]
...for clarity: this was closed in favor of #3755
