### ISSUE TITLE
Document where `#access = FALSE` should be used instead of `hide()`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3788]
This came up in #3768 (credits to @BWPanda for figuring that out). Perhaps we should document this in [`hide()`](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/hide/1) so that people don't have to waste time re-researching things:

> https://stackoverflow.com/a/21041471/4168619 suggests that `hide()`-ing a field should only be done if you intend to display it elsewhere:
>
>>I.e. hiding it (somewhere I saw someone suggesting that): `hide($form['field_myfield']);` really hides the field, but after that, when form is saved this field has empty value, validation fails, etc, so that's not a good way to do this. Hiding makes sense only if you want to print separately that field later, at some other place.
>
>Also, https://api.drupal.org/comment/59900#comment-59900 says:
>
>>Using `hide()` on field of type Date will give you a validation error, so `#access = FALSE` has to be used.
>
>It seems that I was trying to use `hide()` incorrectly, and that I should be using `'#access' => FALSE` instead. Closing this issue then.

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2713

**Comment by quicksketch** [comment]
How's this look? https://github.com/backdrop/backdrop/pull/2713

**Comment by klonos** [comment]
Thanks @quicksketch ...RTBC 👍

**Comment by quicksketch** [comment]
Super, thanks! Merged https://github.com/backdrop/backdrop/pull/2713 into 1.x and 1.13.x.
