### ISSUE TITLE
Content referred to as 'post' regardless of content type

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3799]
**Description of the bug**
Regardless of the name of your content type, in certain places the content is referred to as a 'post'. This will likely confuse people considering one of the default content types is called 'Post'.

**Steps To Reproduce**
To reproduce the behavior:
1. Go to the Page content type configuration form: `/admin/structure/types/manage/page`
2. Click on the 'Publishing Settings' vertical tab
3. Note the text for the Sticky and Promote options

**Actual behavior**

> **Sticky**
[ ] Show option to make *posts* sticky
[ ] Make *posts* sticky by default
Sticky *posts* may be shown at the top of listings.

> **Promote**
[ ] Show option to promote *posts*
[ ] Promote *posts* by default
Promoted *posts* will often be shown on the main homepage or blog.

**Expected behavior**

> **Sticky**
[ ] Show option to make *content* sticky
[ ] Make *content* sticky by default
Sticky *content* may be shown at the top of listings.

> **Promote**
[ ] Show option to promote *content*
[ ] Promote *content* by default
Promoted *content* will often be shown on the main homepage or blog.

(emphasis mine)

---

PR: https://github.com/backdrop/backdrop/pull/2692

**Comment by findlabnet** [comment]
In this context, the word “post” is used as “this content item”, so simply “content” loses this meaning.

**Comment by BWPanda** [comment]
@findlabnet Would 'content of this type' be better then? E.g. 'Show option to promote content of this type'

**Comment by findlabnet** [comment]
Sorry, I'm not good at linguistics. 
BTW, in Drupal this word just omitted for this form.

**Comment by olafgrabienski** [comment]
> I'd love to use the actual name of the content type instead (e.g. 'Show option to promote pages'), but that would require having the ability to enter singular and plural names of content types... Like this: #1145!

@BWPanda This is a perfect use case for #1145, let's revive that important issue!

**Comment by klonos** [comment]
> I'd love to use the actual name of the content type instead (e.g. 'Show option to promote pages'), but that would require having the ability to enter singular and plural names of content types

I have though of that option too, but #1145 is not our only problem in this case; we also need to deal with the fact that there's no content type name specified yet, when creating a new content type. I guess that's where something like `content of this type` would come to save the day.

**Comment by BWPanda** [comment]
> we also need to deal with the fact that there's no content type name specified yet, when creating a new content type.

Hmm, good point @klonos. Maybe then we can get this issue committed with wording like 'content of this type', and then if/when https://github.com/backdrop/backdrop-issues/issues/1145 gets committed we can look at re-wording this accordingly (maybe needing different wording for new/existing content types).

**Comment by klonos** [comment]
Yep, if repeating "content of this type" in all options is a bit too much, we can consider adding it to the field labels. Something like so:

> **Sticky settings for this content type**
[ ] Show option to make sticky
[ ] Make sticky by default
Sticky *content* may be shown at the top of listings.

> **Promotion settings for this content type**
[ ] Show option to promote
[ ] Promote by default
Promoted *content* will often be shown on the main homepage or blog.

**Comment by klonos** [comment]
...perhaps we could even get away with omitting the "content" or "content of this type" entirely and be done with this 😅

**Comment by BWPanda** [comment]
[PR](https://github.com/backdrop/backdrop/pull/2692) updated to remove 'content' from `sticky` and `promote` checkboxes (I think it still makes sense elsewhere).

**Comment by BWPanda** [comment]
FTR, here's what it now looks like with the current PR:
![image](https://user-images.githubusercontent.com/2385329/90008620-fd143880-dcdf-11ea-8753-42e4074c5e5f.png)

Code reviews/testing welcome!

**Comment by klonos** [comment]
Thanks @BWPanda ...RTBC 👍 

PS: I had to pull the changes and test locally, because the PR sandbox seems to be broken (leads to that generic "Welcome" page from drupalhosting.ru). Perhaps refresh the sandbox, so that others can test?

**Comment by BWPanda** [comment]
Thanks @klonos for the review. Thanks also to @findlabnet & @olafgrabienski for the feedback! Merged https://github.com/backdrop/backdrop/pull/2692 into 1.x.
