### ISSUE TITLE
Let's get Backdrop ready to run on Pantheon!

### ISSUE THREAD

**Issue by kreynen** [backdrop/backdrop-issues#380]
While it is possible to spin up an instance of Backdrop on Pantheon, it requires jumping through a few hoops.  Nothing serious at first, but this is more automated with other distributions and could be improved in Backdrop as well.

The first issue users run into is Backdrop can't create the files necessary for the install.  

![cannot_install_backdrop_in_git_mode](https://cloud.githubusercontent.com/assets/385234/4718021/fdbd652a-591b-11e4-97e8-e7f8c469ff0a.png)

This is because the instance is started in Git mode.  This is easy enough to fix for each instance, but it's also possible to ask someone at Pantheon to configure the instances to start in SFTP mode.  Until then users simply need to go to the site's dashboard and switch the mode from Git to SFTP there.  It can be switched back to Git after the install.

![pantheon_dashboard](https://cloud.githubusercontent.com/assets/385234/4718191/6a861d8a-591e-11e4-8db2-d090537059bb.png)

Once in SFTP mode, clicking Try Again will allow the install to continue.  The next step requires the user to get the database settings from Pantheon Dashboard.  This is something that happens automagically in other distributions.  I think this is what @populist and @fluxsauce wanted to address with https://github.com/backdrop/backdrop/pull/60, but for now the user needs to get the database settings from Pantheon Dashboard and use the Advance section of that form to change the Database Host from localhost to dbserver.dev.xxx...xxx.drush.in and update the port.  

![database_screen](https://cloud.githubusercontent.com/assets/385234/4718192/71251a24-591e-11e4-8070-51aafbd8ff0e.png)

Success!  Now users can start using Backdrop for themselves... until Pantheon updates the database connection information.  The site also can't connect to the database after being pushed from dev -> test either.  This is because the install process writes static database configuration to settings.php and that information can both change at any point in time for the dev instance and is different on the test and live instances.

To get this to continue working on dev, users need to replace 1 line of the settings.php.  Instead of...

`$database = 'mysql://pantheon:...`

Pantheon requires something more like...

```
if (!empty($_SERVER['PRESSFLOW_SETTINGS'])) {
  $env = json_decode($_SERVER['PRESSFLOW_SETTINGS'], TRUE);
  if (!empty($env['conf']['pantheon_binding'])) {
    $pantheon_db = $env['databases']['default']['default'];
    $pantheon_conf = $env['conf'];

    //user name and password
    $db_string = $pantheon_db['driver'] . '://' . $pantheon_db['username'] . ':' . $pantheon_db['password'] . '@';
    //host
    $db_string .= 'dbserver.' . $pantheon_conf['pantheon_environment'] . '.' . $pantheon_conf['pantheon_site_uuid'] . '.drush.in' . ':' . $pantheon_db['port'];
    // database
    $db_string .= '/' . $pantheon_db['database'];

    $database = $db_string;
  }   
}

```

But even with that in place the site won't even load when pushed to test.  `$config_directories['active'] = 'files/config_' . md5($database) . '/active';` in the settings.php is probably an issue.  Because the database connection string is dynamic, this would change unexpectedly in every environment.  I hard coded it to the directory created on dev, but that still didn't resolve the issue on live.

Pantheon also reports that their Pantheon Platform API Module is not installed.

![pantheon_api_module_missing](https://cloud.githubusercontent.com/assets/385234/4719023/56981f00-5926-11e4-86ef-95fabf4ee366.png)

Without a backdrop version of that module, I'm not sure how someone would install that.

I don't have time to continue chasing this, but I've achieved my goal of being able to get the new layout tool in front of more people.

**Comment by jenlampton** [comment]
I just pushed the code from Backdrop 1.0.0-preview up to the backdrop-pantheon repo (I think, I may have pushed the latest from 1.x) either way, the demo button on backdropcms.org should work if we can get pantheon pulling this latest code.  @populist is that automatic?

**Comment by populist** [comment]
Pantheon will pull the latest code from the backdrop-pantheon repository automatically and will notify existing sites that an update exists in their dashboard.

**Comment by populist** [comment]
As an update, I also made another pass at the Pantheon settings injection to simplify everything based on new changes in the Backdrop CMS. There are a couple quirks that still need to be resolved (https://github.com/backdrop-ops/backdrop-pantheon/pull/1) but that is the branch for testing.

**Comment by kreynen** [comment]
Just spun up 1.0 with no errors on the install :)  Really amazing work! I also merge the 1.0 updates @jenlampton merged into the Pantheon Drop reop into my existing Backdrop test sites without any issues.  So that process (though manual) is working as well.

**Comment by quicksketch** [comment]
w00t! Thanks @kreynen! Much easier now than it had been, eh?

**Comment by populist** [comment]
And it has been written up to much excitement - https://www.getpantheon.com/blog/backdrop-cms-10-available-pantheon

**Comment by jenlampton** [comment]
<3

**Comment by jenlampton** [comment]
I just wrote up a comparison of our three leading candidates for handling config in backdrop with Git over at https://github.com/backdrop/backdrop-issues/issues/855#issuecomment-91419775 if anyone is curious.
