### ISSUE TITLE
Dashboard: Available Updates information not correct

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3801]
**Description of the bug**
The *Available Updates* block of the *Dashboard*, which lists the projects on a site (core, modules, and so on), says there is an update available for every listed project, even if most of the projects are already up to date.

**Steps To Reproduce**

1. Go to `admin/reports/updates` and check if there are available updates for your site.
2. Make sure that there's at least one project which is up to date, by the time of writing e.g. *Backdrop core* 1.13.0 and *Backup and Migrate* 1.x-1.0.14.
3. Go to the *Dashboard* at `admin/dashboard`, and have a look at the *Available Updates* block.

**Actual behavior**

Projects which are already up to date are listed with available updates, for instance:
- `Backdrop core (version 1.13.0 available) - Update`
- `Backup and Migrate module (version 1.x-1.0.14 available) - Update`

**Expected behavior**

The mentioned projects should be listed as up to date.
  (Or: Don't even list projects which don't have an update.)

**Additional information**

- Backdrop CMS version: 1.13.0

---
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2752

**Comment by findlabnet** [comment]
Additional note: "Update" link for Backdrop core have target to `/admin/modules/update` - this is right?

**Comment by laryn** [comment]
I'd suggest the modules that don't actually have an update should not even appear in this dashboard list.

**Comment by olafgrabienski** [comment]
> Additional note: "Update" link for Backdrop core have target to `/admin/modules/update` - this is right?

@findlabnet That's right for the time being. See the recent discussion about it in https://github.com/backdrop/backdrop-issues/issues/2714#issuecomment-493324039 and the following comment.

**Comment by klonos** [comment]
> I'd suggest the modules that don't actually have an update should not even appear in this dashboard list.

I have spotted some additional related issues with the updates dashboard block, and had started some work on it, but never got to finish that. The fixes could be follow-ups, I didn't want to hold the feature up for that (although have not gotten to actually filing issues for them 😓). The main thing that stopped me from doing further work was that I found out that for the sake of splitting the list in the available updates page into core/modules/themes/layouts, and then also the same set of things but disabled ones vs enabled ones, we seem to be doing something "unholy" to the arrays returned by some functions (cannot remember details right now). So I have gotten myself into another rabbit hole, trying to fix this underlying issue first 😓 ...I will have another go at it.

**Comment by olafgrabienski** [comment]
>> **Expected behavior**
>> The mentioned projects should be listed as up to date.

> I'd suggest the modules that don't actually have an update should not even appear in this dashboard list.

@laryn I agree! (Updated the issue description.)

> I have spotted some additional related issues with the updates dashboard block, and had started some work on it (...)

@klonos Are you able to provide the parts of your work which regard this issue as a PR?

**Comment by klonos** [comment]
> Are you able to provide the parts of your work which regard this issue as a PR?

No 😓 ...my way of working is kinda "sporadic", so things I work on oftentimes get lost in the branches I create. Sorry.

I will try to find that work and pick it up again soon though.

**Comment by laryn** [comment]
The fact that 1.13.x is considered an update to 1.14.x-dev is a separate issue -- @herbdool's PR looks like it does the trick:

![Screen Shot 2019-06-26 at 12 04 10 AM](https://user-images.githubusercontent.com/871421/60152426-125d9900-97a6-11e9-878d-052a59bb0eff.jpg)

**Comment by olafgrabienski** [comment]
Indeed, looks good! I've installed two modules in the sandbox site, one of them as an older release and the other one with the current version.

Result: The *Available Updates* block of the Dashboard shows correctly an available update only for the outdated module, not for the other one.

**Comment by herbdool** [comment]
Since I copied the small bit of code from a different part of the update module I'm making this ready.

**Comment by klonos** [comment]
Since this is RTBC, and it fixes a bug, I am adding it to the next bug release milestone.

**Comment by quicksketch** [comment]
Thanks! Simple fix. Merged https://github.com/backdrop/backdrop/pull/2752 into 1.x and 1.13.x.
