### ISSUE TITLE
`hook_block_configure()` missing `$settings` parameter documentation

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3802]
https://api.backdropcms.org/api/backdrop/core%21modules%21layout%21layout.api.php/function/hook_block_configure/1

There's no documentation for the `$settings` parameter in `hook_block_configure()`.

**Comment by klonos** [comment]
Nice find @BWPanda 👍 

That's a new addition in Backdrop; the respective function in D7 doesn't have that parameter.

The addition of the `$settings` parameter was introduced in #86, with this PR: https://github.com/backdrop/backdrop/pull/483/files#diff-b0d220534bd7b0ebefa087c27434ba73R423

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3924

**Comment by BWPanda** [comment]
Since it's just a documentation change, I've gone ahead and merged https://github.com/backdrop/backdrop/pull/3924 into 1.x.

**Comment by klonos** [comment]
@BWPanda when new parameters are added/removed or return values change, we add a `@since` in the docblock of the respective functions. Small follow-up PR to do that in this case: https://github.com/backdrop/backdrop/pull/4342

Reopening this to draw your attention.

**Comment by BWPanda** [comment]
Thanks @klonos. Merged.
