### ISSUE TITLE
Project browser not working

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3803]
**Description of the bug**

On one of my sites, I don't see the project browser but the following warning:

`Warning: array_merge(): Argument #2 is not an array in installer_browser_fetch_results() (line 240 of (...)/core/modules/installer/installer.browser.inc).`

There's also a success (!) message:

`Encountered an error when trying to fetch results from . Error -1002 : missing schema`

**Steps To Reproduce**

1. Go to `admin/modules/install` (or `admin/appearance/install`).

**Actual behavior**

There's no project browser.

**Expected behavior**

Project browser available

**Additional information**

- I've upgraded the site from Drupal 7. (Apart of this issue, it's running fine so far.)
- Backdrop CMS version: 1.12.6

---

Meanwhile the issue is fixed for me, see https://github.com/backdrop/backdrop-issues/issues/3803#issuecomment-494818530. It's however not clear why it happened in the first place.

**Comment by olafgrabienski** [comment]
> `Encountered an error when trying to fetch results from . (...)`

Strange, in the message there's something missing after the "from". According to https://api.backdropcms.org/api/backdrop/core%21modules%21installer%21installer.browser.inc/function/installer_browser_fetch_results/1 there should be a value for `@name`:

`Encountered an error when trying to fetch results from @name. (...)`

**Comment by klonos** [comment]
...yeah, if you look further, you will see that `'@name' => $server['name']` ...could it be that it is still looking for updates and project data in d.org instead of b.org?

**Comment by olafgrabienski** [comment]
> '@name' => $server['name'] ...could it be that it is still looking for updates and project data in d.org instead of b.org?

Well, nearly! Actually, the information about the project server was completely missing from the respective configuration file.

I found the line `$server = config_get('installer.settings', 'installer_server');` on the [function installer_browser_get_server API page](https://api.backdropcms.org/api/backdrop/core%21modules%21installer%21installer.browser.inc/function/installer_browser_get_server/1), and had a look at `installer.settings.json`. In this file, the following part was missing:

```
    "installer_server": {
        "url": "https://projects.backdropcms.org",
        "name": "Backdrop"
    },
````

So, the issue is fixed for me (hooray!) -- I've however no idea, why the server information was missing from the config file.

**Comment by olafgrabienski** [comment]
Closing the issue for now. (Feel free to reopen if you encounter the same.)
