### ISSUE TITLE
[UX] Admin bar: Search result list is hidden in RTL view

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#3804]
**Description of the bug**
Bug in 'Administration bar' core module: If an RTL language is default, the search result list is hidden under search bar.

**Steps To Reproduce**
To reproduce the behavior:
1. Enable the 'Language' core module.
2. Set an RTL language as default. For example: Hebrew
3. Write a key word in the search bar. For example: url

**Actual behavior**
There isn't result list.

**Expected behavior**
Result list is displayed with links.

**Additional information**
I will create a PR: We need to remove a line (307) from admin_bar.css, and the result list appears.

---
PR by @VasasA: https://github.com/backdrop/backdrop/pull/2696

**Comment by klonos** [comment]
The PR sandbox works as expected, whereas my local (which does not include the fix) is broken.

I see quite a few related CSS rules being overridden, so these may not be needed at all. Will test some more before RTBCing this.

**Comment by VasasA** [comment]
Ok, thank You!

**Comment by klonos** [comment]
Thank YOU sir 🙂

**Comment by quicksketch** [comment]
> I see quite a few related CSS rules being overridden, so these may not be needed at all. Will test some more before RTBCing this.

Since the fix seems to work as-is, I went ahead and merged https://github.com/backdrop/backdrop/pull/2696. Further clean-up can be in a separate issue.

Thanks @VasasA for making the PR! And as always thanks so much @klonos. :smile:
