### ISSUE TITLE
Fix inline docs in `user_cancel_user_action()`

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3806]
The inline docs in `user_cancel_user_action()` refer to nodes instead of users. These need to be updated to reflect what actually happens to user accounts in this function.

```php
/**
 * Queues a specific user account for cancellation.
 *
 * @param User $account
 *   The user entity whose account will be blocked.
 *
 * @ingroup actions
 */
function user_cancel_user_action($account, &$context) {
  // Save the list of nodes to be deleted in the session. Append to the existing
  // list if within the last minute, otherwise start a new list of nodes.

```

- - - - - - 

PR by @chuyich https://github.com/backdrop/backdrop/pull/3341

**Comment by jenlampton** [comment]
This looks great @chuyich!  I left one minor recommendation on the PR, and removed the `pr - needs testing` label since this is a documentation update only.

**Comment by chuyich** [comment]
I have fixed it based on your suggestion. :-)

**Comment by jenlampton** [comment]
Looks great! I have marked the PR RTBC, and added the milestone candidate label. Does anyone else agree that this could go into 1.17.2?

**Comment by stpaultim** [comment]
> Does anyone else agree that this could go into 1.17.2?

Agreed.

**Comment by BWPanda** [comment]
Small change requested re. documentation standards.

**Comment by BWPanda** [comment]
Thanks @chuyich & @jenlampton! I've merged https://github.com/backdrop/backdrop/pull/3341 into 1.x and 1.17.x.
