### ISSUE TITLE
Make sure all core modules/themes/layouts use title case for their names

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3810]
This is an old pet peeve of mine: https://www.drupal.org/docs/7/creating-custom-modules/writing-module-info-files-drupal-7x#name

>**name (Required)**
> This displays the name of your module, which will appear on the Modules page. Since module names are proper names, it should be capitalized as a proper name (e.g., "Really Neat Widget", not "really neat widget" or "Really neat widget"), and it should be a human-readable name (not really_neat_widget). If your module name includes an acronym (CSS, WYSIWYG, UI, etc.) or a third-party trade name (jQuery, JavaScript), of course follow the standard capitalization for those.
> `name = Really Neat Widget`

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2700

**Comment by laryn** [comment]
Looks good to me.

**Comment by quicksketch** [comment]
Super, merged https://github.com/backdrop/backdrop/pull/2700 into 1.x and 1.13.x. Thanks for your ever-diligent eye!
