### ISSUE TITLE
[DX] Form API: fields of type `item` do not support `#attributes` - document that `#wrapper_attributes` can be used instead

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3817]
This is a sibling issue to #3569...

This does NOT work:

```php
$form['form_item'] = array(
  '#type' => 'item',
  '#attributes' => array('class' => array('description')),
  '#markup' => t('This is help.'),
  '#states' => array(
    'visible' => array(
      ':input[name="another_form_item"]' => array('checked' => FALSE),
    ),
  ),
);
```

...so one needs to use `#prefix`/`#suffix` instead:

```php
$form['form_item'] = array(
  '#type' => 'item',
  '#prefix' => '<div class="description">',
  '#markup' => t('This is help.'),
  '#suffix' => '</div>',
  '#states' => array(
    'visible' => array(
      ':input[name="another_form_item"]' => array('checked' => FALSE),
    ),
  ),
);
```

...which results in additional markup:

```html
<div class="description">
  <div id="edit-form-item" class="form-item form-type-item" style="display: block;">
   This is help.
  </div>
</div>
```

To get rid of that, one needs to use `#theme_wrappers`:

```php
$form['form_item'] = array(
  '#type' => 'item',
  '#theme_wrappers' => array(),
  '#prefix' => '<div class="description">',
  '#markup' => t('This is help.'),
  '#suffix' => '</div>',
  '#states' => array(
    'visible' => array(
      ':input[name="another_form_item"]' => array('checked' => FALSE),
    ),
  ),
);
```

...to finally get:

```html
<div class="description">
  This is help.
</div>
```

...but it turns out that once you use `#theme_wrappers`, `#states` stops working 😓

**Comment by klonos** [comment]
Note-to-self: This may be simply a case where we overwrite `#attributes` in the theme function that is responsible for rendering `item` FAPI elements; which would make the solution similar to the one from #5157 😉 ...once I have figured which theme function renders FAPI items that is.

**Comment by indigoxela** [comment]
> This may be simply a case where we overwrite #attributes in the theme function that is responsible for rendering item FAPI elements;

It's a bit trickier...

The type [item](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.module#L480) as defined in core/modules/system/system.module doesn't have it's own theme function, but uses function backdrop_pre_render_markup() and function theme_form_element().
The latter puts attributes in `#wrapper_attributes` the pre-render function simply provides the `#markup` as element children.

I didn't actually try, but if you use `#wrapper_attributes` instead of `#attributes`, you might get your expected result.

**Comment by klonos** [comment]
@indigoxela you were right 👍🏼 ...I tested this with the changes that got committed for #1895.

So this becomes a documentation task now, since others have faced this before (in D7): https://drupal.stackexchange.com/questions/34175/adding-class-to-form-item

**Comment by indigoxela** [comment]
@klonos that's great! ... Never underestimate the importance of proper documentation. :+1:

**Comment by bugfolder** [comment]
Now documented: https://docs.backdropcms.org/form_api#item

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼 ...closing this one then 😉
