### ISSUE TITLE
Add Backdrop repo to CodeTriage

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3818]
Is it worth submitting Backdrop to CodeTriage?

https://www.codetriage.com

Might be a good way to get more involvement from those lurking on the edges of the community...

I haven't tested to see if anyone (like me) with access to the Backdrop repo can add it there, or if only the owner can do it. Thought I'd get some feedback first.

**Comment by klonos** [comment]
Sounds like a nobble cause, and a great idea to "recruit" contributors. 👍 from me.

**Comment by BWPanda** [comment]
OK, turns out anyone can add a repo with a URL, so I've done it: https://www.codetriage.com/backdrop/backdrop-issues

I'll close this issue then open one in the API issue queue for adding this to the Contribute page.

**Comment by BWPanda** [comment]
https://github.com/backdrop-ops/api.backdropcms.org/issues/60
