### ISSUE TITLE
[D8][UX] Better Taxonomy permissions

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#382]
Since discovering it 8 months ago, I have been installing the [Taxonomy access fix module](https://www.drupal.org/project/taxonomy_access_fix) on all my sites. It is a great, simple module that fixes the lacking Taxonomy permissions in Drupal core. I recommend implementing it (or something similar) in Backdrop.

Basically, it adds additional permissions for accessing Vocabulary pages and _adding_ new terms (currently you have to give users the broader 'Administer vocabularies and terms' permission to do this).

There is an issue for doing the same thing in Drupal 8 core here: https://www.drupal.org/node/1848686 (which might be helpful if we decide to do the same).

---
~PR by @BWPanda: https://github.com/backdrop/backdrop/pull/508 (merge conflicts)~
~PR by @herbdool https://github.com/backdrop/backdrop/pull/3319~
PR by @docwilmot https://github.com/backdrop/backdrop/pull/3716

**Comment by jenlampton** [comment]
I also want better UX for permissions. Can I pretty please have a vertical tab on the vocab config form that adds the permissions for terms in this vocab? See related: https://github.com/backdrop/backdrop-issues/issues/900

**Comment by jenlampton** [comment]
Optimistically changing milestone?

**Comment by klonos** [comment]
...part of #378

**Comment by klonos** [comment]
The d.org project page for https://www.drupal.org/project/taxonomy_access_fix links to another related, very useful module: https://www.drupal.org/project/taxonomy_autocomplete_permission

> Defines which roles can add new taxonomy terms when using the autocomplete widget.
>
> Adds 1 permission per vocabulary: "Add terms in %term via autocomplete"

Now with #38 implemented, it would be a great addition to merge the functionality of these modules.

**Comment by klonos** [comment]
Proposing milestone to be set for 1.13

**Comment by jenlampton** [comment]
What's the use-case for different permissions via autocomplete than edit? Is it just that you don't want people re-ordering terms?

**Comment by stpaultim** [comment]
I am working on adding a default editor role and as I play with the default permissions I realized that the taxonomy permissions are not that great (or I need to experiment some more). But it is possible to give a user the permission to edit and delete terms without them having access to administer vocabularies and terms. 

With this set of permissions, they can in theory delete and add terms, but they can not access the list of terms. I supposed there might be a use case for this, but it's not very intuitive to me. 

Also, with the new Dashboard module and these permissions, they have access to the taxonomy block on the dashboard which has a "list terms" link, but if you click on the link you get access denied.

**Comment by klonos** [comment]
> Also, with the new Dashboard module and these permissions, they have access to the taxonomy block on the dashboard which has a "list terms" link, but if you click on the link you get access denied.

Seems that this is something we must have missed @stpaultim. Care to file a separate bug issue for that?

**Comment by klonos** [comment]
@BWPanda can you please re-open the PR (and update it if need be)?

**Comment by BWPanda** [comment]
Don't have permission... Can maybe look at updating this tonight (in ~5 hrs time).

**Comment by klonos** [comment]
I have also pinged @quicksketch in the PR, as he was the one that closed it (back in 2014) ... @jenlampton also has permission to open/close PRs IIRC, but it seems that you may need to file an entirely new PR @BWPanda:

![Screen Shot 2020-02-05 at 1 06 26 am](https://user-images.githubusercontent.com/2423362/73751737-d1a21580-47b3-11ea-887f-d6c2d29f7ffd.png)

**Comment by klonos** [comment]
...if you don't wanna start from scratch, you could try the following:

```
git clone https://github.com/backdrop/backdrop
cd backdrop
git remote add BWPanda https://github.com/BWPanda/backdrop
git fetch origin pull/508/head:issue-382
git checkout issue-382
...
...
git push -u BWPanda issue-382
```

**Comment by BWPanda** [comment]
@klonos I'll just use this: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/508.patch

**Comment by klonos** [comment]
...or that 😅 ...just patches do not retain commit history ...but then again, that PR only had a single commit in it.

**Comment by BWPanda** [comment]
So I just tried to apply the above patch to Backdrop and it failed. I'm in the middle of some other stuff ATM, so don't have time to look into how much work is involved in updating the PR, but I'll add it to my todo list (unless anyone else wants to jump in).

**Comment by herbdool** [comment]
Thought I'd give @BWPanda patch a go. PR is ready for testing. https://github.com/backdrop/backdrop/pull/3319

**Comment by herbdool** [comment]
This is ready for testing by anyone. @klonos @olafgrabienski @stpaultim etc. I think it's relatively straightforward. It adds new permissions to add, update, delete terms and allow them to view the taxonomy overview of terms.

**Comment by olafgrabienski** [comment]
Ah, oh! I've put it on my list (unfortunately short of time).

**Comment by olafgrabienski** [comment]
@herbdool I've tested the PR in the [sandbox](http://3319.backdrop.backdrop.qa.backdropcms.org/): Added a test account with Editor role and played with different permissions. The different combinations work fine.

@stpaultim Should default permissions (on new installations) of the Editor role stay the same with this PR? Now it would be possible to *not* provide "Administer vocabularies and terms" but only all single permissions for "Tags". Not sure if it would fit the concept of the Editor role better, though. (Vaguely remembering there was an issue discussing Editor permissions, but where?)

**Comment by olafgrabienski** [comment]
**PS:** The Taxonomy block on the Dashboard -- see https://github.com/backdrop/backdrop-issues/issues/382#issuecomment-524590974 -- may need some more attention. With only the `Edit terms` permission everything is fine. With only `Create terms` and/or `Delete terms` the block doesn't show up. While via Admin menu it's rightfully possible to get to the terms in this case, it may make sense to not show the Taxonomy block on the Dashboard because it's an edge case. Not sure!

**Comment by stpaultim** [comment]
I'll try to review this issue ASAP. In the meantime will note that this issue is doing pretty well on our current survey. It is tied for [9th place on the list](https://survey.backdropcms.org/feature-ideas?flagged=All&order=count&sort=desc). This one is much closer to completion than most and could be the first item in our survey to be merged into core.

**Comment by stpaultim** [comment]
Testing in Sandbox.

1) I'm able to give Test Editor ability to Create, Edit, and Delete terms in one taxonomy and not another. (WORKS)
2) Tried to access admin path for taxonomy I should not be able to edit. (WORKS - I was unable to access).
3) Test Editor given permission to delete terms, but not create or edit them. (WORKS as expected)
4) Test Editor with permission to create, edit and delete terms should also have access to view them, which was not the case before. (WORKS NOW) https://github.com/backdrop/backdrop-issues/issues/382#issuecomment-524590974

This seems to work well. @olafgrabienski has also tested and approved this. It looks like a code review could get this important fix into 1.20.

**Comment by olafgrabienski** [comment]
@stpaultim Thanks for looking into this again! Could really be a nice thing for the 1.20 release.

If you find time, here are some follow-up questions to consider sooner or later:

- https://github.com/backdrop/backdrop-issues/issues/382#issuecomment-777333247
- https://github.com/backdrop/backdrop-issues/issues/382#issuecomment-777341774

**Comment by stpaultim** [comment]
@olafgrabienski - I'm inclined to treat your two comments as follow-up issues unless anyone else things they need to get into this PR. This one seems so close to inclusion in 1.20, I don't want to slow it down. 

As far as I can tell, it only needs a code review. This one was in the top 10 of our survey back in March. https://survey.backdropcms.org/

**Comment by herbdool** [comment]
@docwilmot what's changed with your PR compared to mine?

**Comment by docwilmot** [comment]
Not a thing, except yours had conflicts since we merged https://github.com/backdrop/backdrop/pull/3703.

**Comment by herbdool** [comment]
@docwilmot ok, thanks. I've closed the other PR. I guess I can't officially approve the code review since I've worked on it, but it still looks fine after I've reviewed your fixing of the merge conflicts. We'll need someone to do a final code review. @laryn are you interested?

**Comment by laryn** [comment]
@herbdool I glanced over the code and it looks good -- at first I was thinking we should also check if any other roles besides the admin role have 'administer taxonomy' permissions and give them the new create permission, but then realized they'll still have 'administer taxonomy' permissions and be able to do anything they used to be able to do. So I think it's all set!

**Comment by jenlampton** [comment]
The recent PR is going to need a rebase because we removed the form from the taxonomy overview page. I saw no other issues with the PR, so once we get the conflicts sorted out this should be RTBC, but we should review it again. @docwilmot  if you don't have time to do the rebase let us know, I'm sure someone else here would be happy to help :)

**Comment by jenlampton** [comment]
Code in newest PR looks great - thanks for resolving the conflicts @docwilmot :)

I took it for another spin in the sandbox, but after a fresh install, the `Editor` role has the Edit and Delete permission on the `Tags` vocabulary, but not Create, which seems odd.  I'd recommend we do it the other way around, and set them to Create, but not Edit or Delete.

<img width="1212" alt="Screen Shot 2021-09-01 at 9 47 34 AM" src="https://user-images.githubusercontent.com/397895/131711543-0e58b4e9-a52f-4c85-999b-79505cadf9dd.png">

**Comment by jenlampton** [comment]
Ah, I see, the editor role previously had `Administer taxonomy` as well as Edit and Delete, so these permissions are unchanged. 

<img width="1225" alt="Screen Shot 2021-09-01 at 9 58 47 AM" src="https://user-images.githubusercontent.com/397895/131712733-62fda6bd-eeae-4e35-b94f-f4d912b6f729.png">

For existing sites, I recommend that we add the `Create` permission for Editors. For new installs, I'd prefer that we remove the existing permissions and add only `Create terms` permission.

**Comment by laryn** [comment]
> For existing sites, I recommend that we add the Create permission for Editors.

Maybe check first to make sure the existing Editor role still has "Administer taxonomy" permissions?

> For new installs, I'd prefer that we remove the existing permissions and add only Create terms permission.

Sounds good to me.

**Comment by stpaultim** [comment]
I agree with Jen's suggestions for permissions. I was going to delay the discussion of default permissions to a follow-up issue, but if you are able to get those change in here too, great.

**Comment by docwilmot** [comment]
Done.

**Comment by jenlampton** [comment]
Testing again now! :)

**Comment by BWPanda** [comment]
I've merged https://github.com/backdrop/backdrop/pull/3716 into 1.x. Thanks to @docwilmot, @quicksketch, @jenlampton, @stpaultim, @klonos, @herbdool, @olafgrabienski & @laryn for your work on this!

**Comment by laryn** [comment]
And thanks to @bwpanda for getting the whole issue rolling way back in 2014! :wink:

**Comment by klonos** [comment]
@laryn or @BWPanda follow-up PR with some small fixes: https://github.com/backdrop/backdrop/pull/3718
