### ISSUE TITLE
UI vs. themes. Who gets the last say?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3822]
When there's a UI setting that controls the display of something on the site, should themes be able to override that, or should the UI setting override any and all themes?

Two issues I've been working on recently have come across this dilemma:

1. https://github.com/backdrop/backdrop-issues/issues/2351 deals with the issue site owners face when they want to change the look of the breadcrumb trail. Traditionally this has been controlled by themes, but the suggestion is to move (and standardise) certain settings to the breadcrumb block so people can change how the breadcrumb trail looks without needing to override theme functions, etc., particularly the breadcrumb separator.
1. https://github.com/backdrop/backdrop-issues/issues/576 deals with the addition of the Backdrop logo (mark) to the 'powered by' block. A block setting is needed to allow users to choose a black or white logo (for use on different colour backgrounds).

In both cases, the UI setting can currently be overridden by themes. In the case of the breadcrumb separator, most core themes define their own separator, and so setting the separator in the block UI has no effect. The same is true of the 'powered by' logo - choosing a black or white logo has no effect when using the Basis theme as it removes the whole `system.theme.css` file (where the CSS logo is defined).

So who should have the last say: the UI, or the theme?
There are arguments for both I think, and I'll try to summarise them here:

### Pro UI

Part of the Backdrop [philosophy](https://backdropcms.org/philosophy#importance) states that "Backdrop values the needs of the editor and architect over the needs of the developer." This could be interpreted as indicating that editors should be able to control aspects of their site without needing to write code (overriding theme functions, etc.). In other words, provide UI settings to control certain theme elements, and not create confusion by allowing themes to then override these settings.

### Pro Themes

Themes have traditionally had the final say in how something is displayed, and one of the Backdrop [principles](https://backdropcms.org/philosophy#principles) states that "Backwards compatibility is important." So in keeping with tradition and not breaking stuff, themes should be able to override any UI settings/styling.

I'm personally on the fence about this. I see how UI settings that always work are ideal for users who don't want to have to write code just to change something quick and simple. But I also see how that would break a lot of themes and be a change in how we generally do things...
What do you think?

Ultimately I'd like to reach a PMC-approved consensus on this topic, so that other issues (like those linked above) can move forward, knowing they're doing things the 'right way'.

**Comment by herbdool** [comment]
Backwards compatibility is key so we can't change the hierarchy. Themes get the last say.

That being said, it is technically possible to add inline CSS from the UI (as you did) and that gets the final say. I'll put aside the question of whether we actually want to do that in the core UI.

**Comment by BWPanda** [comment]
Thanks @herbdool.

> Backwards compatibility is key so we can't change the hierarchy. Themes get the last say.

Follow-up question: If we decide that themes get the last say, then UI settings that are immediately overridden by the theme will result in 'WTF' moments for users (case in point: https://github.com/backdrop/backdrop-issues/issues/576#issuecomment-496683942). Do we then:

1. Not bother with adding UI settings for theme-controlled things?
1. Add UI settings but state that changes may not take effect if the current theme overrides it?
1. Something else? (suggestions?)

**Comment by olafgrabienski** [comment]
> If we decide that themes get the last say, then UI settings that are immediately overridden by the theme will result in 'WTF' moments for users (case in point: #576 (comment)). Do we then:
>
> 1. Not bother with adding UI settings for theme-controlled things?
> 2. Add UI settings but state that changes may not take effect if the current theme overrides it?
> 3. Something else? (suggestions?)

Goood question! I'd vote for the first option (no UI setting) in cases where it's possible to customize something via CSS (theme, or *CSS injector*).

- In the case of #2351 I'd suggest to follow the approach in https://github.com/backdrop/backdrop-issues/issues/2351#issuecomment-454548910.
- Regarding #576 a solution could be to provide a logo which works more or less with any background color (and allow the theme to change it, ideally via CSS). Instead of providing a not so good looking logo for Bartik _and_ Basis, I'd also be fine to be more opinionated and to optimize it for Basis which has been our default theme for quite a while now.

**Comment by docwilmot** [comment]
I'm for allowing the UI, as per the pro-UI argument in the first post. The UI setting can say that this overrides the theme just for clarity.

**Comment by herbdool** [comment]
Why not put the UI into the theme settings instead? That way there's no WTF moment because the theme can override itself and it's backwards compatible.

**Comment by herbdool** [comment]
I don't know how it intersects with Backdrop philosophy but I like this from WordPress': https://wordpress.org/about/philosophy/

> As developers we sometimes feel that providing options for everything is a good thing, you can never have too many choices, right? Ultimately these choices end up being technical ones, choices that the average end user has no interest in. It’s our duty as developers to make smart design decisions and avoid putting the weight of technical choices on our end users.

**Comment by klonos** [comment]
I agree that there should be a line drawn to where options in the UI stop; but wearing my PMC had and trying to honour our current principles, I still lean towards adding UI options for things that make sense.

> Why not put the UI into the theme settings instead?

Would that mean that every theme would need to implement support for this (same as color module support for example)?

**Comment by oadaeh** [comment]
I agree that smart design decisions should be made from the start, but I do not agree that options should be kept from the end users. Developers do not always know what the end users want nor do they always have their best interests in mind. It was due to that mindset that I stopped using both KDE 4 and Gnome 3, because in both cases, the developers did not really care what the end users wanted and just did what suited them.
I do not think it is unreasonable to
- make good design decisions from the end-users' point of view,
- provide an easy to find & modify UI for basic, common options, and
- provide advanced options that are not in their face, but are accessible.
I might not always succeed, but that is how I try to operate with all the UIs I create or modify.

**Comment by herbdool** [comment]
@klonos short answer: yes.

**Comment by findlabnet** [comment]
@klonos a little more long answer: 
yes, in case if theme can/prefer override any/some defaults (for example defined in another UI).

**Comment by BWPanda** [comment]
FYI, here's where this issue was discussed somewhat during the weekly meeting: https://www.youtube.com/watch?v=Z2no6XI4Jd0&feature=youtu.be&t=2355

**Comment by BWPanda** [comment]
@jenlampton made a comment in the meeting (https://youtu.be/Z2no6XI4Jd0?t=2808) that I hadn't considered: that almost every UI setting can already be overwritten by a theme (e.g. you can add custom titles to blocks, but all a theme has to do is hard-code a title in a template file and that title setting in the UI isn't going to work anymore). So unless we're going to change that behaviour across all of Backdrop, I'd say the answer here is that themes can always override UI settings. That's the way it works currently, that's the way Drupal 7 works, and that's what most people expect (based on the current state of things).

So I'll close this issue now. If you feel that Backdrop should change this behaviour however, that's a larger issue and probably deserves it's own separate issue.

**Comment by jenlampton** [comment]
> So unless we're going to change that behaviour across all of Backdrop

I don't even think this is possible...
