### ISSUE TITLE
What's up with the "Code Triage" badge in the README.md?

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#3823]
Looks like a badge was added to the README.md for this repo a few days ago:

![image](https://user-images.githubusercontent.com/100206/58601014-cc132980-823b-11e9-8f8a-cd3dcc6ba73e.png)

What's the purpose of Code Triage and could we get some explanation of what it's intended purpose is? There wasn't an issue or anything in the commit that added it (https://github.com/backdrop/backdrop-issues/commit/fed7372074019a4022fddc4a80f81bb4f292481f).

**Comment by klonos** [comment]
Sorry @quicksketch 😓 ...twas me who took the initiative, after @BWPanda has filed https://github.com/backdrop-ops/api.backdropcms.org/issues/60

This is to add to our efforts to expose Backdrop to more people; this one specifically to members of the community that want to contribute code/documentation or help with triaging issues in the queue.

**Comment by klonos** [comment]
...it seems that it is already working btw 😄 ...we have one person subscribed that is not one of the known members of our community (not one that I know of at least)

**Comment by klonos** [comment]
...closing this now (we are now at 7 contributors BTW 🙂 )
