### ISSUE TITLE
Misleading description for 'Trimmed limit' setting on long text fields

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3828]
When configuring the 'Trimmed' field format, the 'Trimmed limit' setting has the following description:

> If the summary is not set, the trimmed [FIELD] field will be shorter than this character limit.

This description is the same for both the 'Summary or trimmed' and 'Trimmed' formats. It makes sense for the 'Summary or trimmed' format, but the 'Trimmed' format doesn't take the text's summary into consideration when trimming, so this is misleading. THe description should be changed for the 'Trimmed' format.

![image](https://user-images.githubusercontent.com/2385329/58618336-0ed01280-82cb-11e9-8e64-e059b0504c93.png)

**Comment by BWPanda** [comment]
Made a PR that fixes this by changing the description text for the 'Trimmed' format: https://github.com/backdrop/backdrop/pull/2712

**Comment by BWPanda** [comment]
The description is now just:

> The trimmed *%label* field will be shorter than this character limit.

PR updated for Tugboat and test suite.

**Comment by laryn** [comment]
WFM and code looks good. 👍

**Comment by argiepiano** [comment]
RTBC!

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/2712 into 1.x and 1.25.x.
