### ISSUE TITLE
Extend `backdrop_set_message()` to allow easier hiding/showing of messages

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3831]
Back in 2011, I have created https://www.drupal.org/project/drupal/issues/1149006 ...but I did not have Backdrop back then 😄 

Currently, there is no easy way to know which module spat out a certain message, and there is no easy way to stop certain messages from being displayed.

Use cases include:

- Hide (or defer to log) site-admin-eyes-only messages, that are of no help to users. For example module/core security update messages.
- Hide developer-eyes-only messages during testing.
- Display which module "complains" so that people can report issues against the proper project queue.
- ...

So in other words:

> As a site owner, I want to have an easy way to hide potentially "scary" messages that my site visitors should never see.

> As a site builder, I want to have the option to be able to redirect certain messages that have been hidden from end users (site visitors or content authors), to the site log (watchdog entry instead of UI message), and to be able to see messages that other users should not.

> As a Backdrop developer/contributor I would like to have an easy way to know whether an error message has been thrown by core or one of my installed contrib modules, and have an easy way to get to the issue queue of that module on GitHub.

Contrib does the best it can, but usually resorts to methods like regex matching ([Disable Messages](http://drupal.org/project/disable_messages) for example), that simply do not scale (when messages are translated for example).

**Proposed resolution**
We should be able to:

- easily discover which module throws each message
- allow module developers to define if a message is meant for end users or site admins
- allow site admins to hide/show messages (or message "categories") on a user role basis
- allow disabling/hiding/redirecting messages generated by specific modules

If we cannot do all that in core, we should at the very least provide the means for contrib to step in and fill this gap.

Related issues in the [Disable Messages](http://drupal.org/project/disable_messages) project's queue:

- [#1137722: Filter messages by module](https://www.drupal.org/project/disable_messages/issues/1137722)
- [#1903298: Need help in disabling all notifications from the site except a few like registration email notification](https://www.drupal.org/project/disable_messages/issues/1903298)

**Comment by docwilmot** [comment]
dupe? https://github.com/backdrop/backdrop-issues/issues/1062

**Comment by klonos** [comment]
Most certainly yes @docwilmot 😅
