### ISSUE TITLE
PHP Warning: strtr(): The second argument is not an array in backdrop_clean_css_identifier

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3832]
**Description of the bug**
On a views page, I see the following error in the logs:
```
Warning: strtr(): The second argument is not an array in backdrop_clean_css_identifier() (line 4166 of backdrop/core/includes/common.inc).
```

**Steps to reproduce**
1) Enable all errors in `admin/config/development/logging`
1) Create a view using a list style display
1) add a css class for the wrapper
1) add a css class for the list
1) save the view
1) view the view -> error 👎 ...if you have enabled errors in step 1 above; if not, then...
1) check the logs -> error 👎 

**Additional information**
This happens because we are using `array_walk()` in `views.theme.inc` to pass classes in views through `backdrop_clean_css_identifier()` but we are not passing an equal number of argument-sets to the number of classes, and `array_walk()` requires that they match. When they don't, NULL is passed as the second argument, and `backdrop_clean_css_identifier()` expects an array - which causes this error.

---
PR: https://github.com/backdrop/backdrop/pull/2710

**Comment by jenlampton** [comment]
I filed a PR that removes `array_walk()` and uses a normal `foreach()` instead.

**Comment by klonos** [comment]
Hey @jenlampton ...I was able to reproduce this, but the PR sandbox is having that php issue (https://github.com/backdrop-ops/backdropcms.org/issues/552). Mind refreshing the PR sandbox so I can lazy-test 😄?

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2710 into 1.x and 1.13.x. Nice cleanup with the use of a simple loop instead of `array_map()`. Thanks!
