### ISSUE TITLE
[UX] Add link to dashboard from update.php results (replace admin page link)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3840]
When an a database update (update.php) completes, the success page has three links on it:
* Home page
* Administration pages
* Status report

<img width="969" alt="Screen Shot 2019-05-31 at 5 50 44 PM" src="https://user-images.githubusercontent.com/397895/58741342-9fdae280-83cc-11e9-8a2f-21254842c957.png">

The one link in this list that I never, ever click, is `Administration pages`.

How would everyone feel if we replaced that link with a `Dashboard` link, if the site has the dashboard module enabled? If not, we can fall back to the `Administration pages` link.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2717

**Comment by klonos** [comment]
Sure, sounds like a good idea (I never click on the "admin pages" link either).

**Comment by stpaultim** [comment]
I like it!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2717 into 1.x and 1.13.x. Thanks folks!
