### ISSUE TITLE
Improve table border color in Seven (admin theme)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3841]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/3741

---

We were just noticing that in the [styleguide](http://backdrop-ops.github.io/styleguide/#table) the tables didn't have a bottom border. There they looked great because the styleguide shows everything on a light gray background:
<img width="1024" alt="styleguide" src="https://user-images.githubusercontent.com/397895/58744292-9ca81c80-83f5-11e9-93f4-7226e55fc7ac.png">

But on the dashboard in Backdrop core, we have tables on a white background. When the bottom row of a table also has a white background, this caused the tables to have this weird floaty feel:
<img width="662" alt="floaty" src="https://user-images.githubusercontent.com/397895/58744311-d842e680-83f5-11e9-9c5e-c30ba9df3d53.png">

@jenlampton recommended adding a bottom border to the tables, one that matched the left & right borders. When we tried that, we noticed that color gray was so light that the border was still almost invisible:
<img width="670" alt="invisible" src="https://user-images.githubusercontent.com/397895/58744323-0cb6a280-83f6-11e9-836d-d00438200684.png">

@klonos recommended that we darken the gray color, so it would be easier to see where the table ends:
<img width="664" alt="ends" src="https://user-images.githubusercontent.com/397895/58744333-29eb7100-83f6-11e9-89f7-5e1df20842b6.png">

@quicksketch pointed out that this made the left-right borders now a different color from the bottom border. And that maybe we should bring in @dariusgarza since this gets into the area of changing the design.
@klonos had also noticed that when you can see the borders, it becomes clear that the left/right borders are 1px wider than the header, which gets distracting. 
<img width="665" alt="sideburns" src="https://user-images.githubusercontent.com/397895/58744352-5d2e0000-83f6-11e9-922f-fc9a4a3d6329.png">

@jenlampton proposes that we replace these actual borders with "box-shadow borders" instead, which will not cause the 1px difference in width:
<img width="669" alt="better" src="https://user-images.githubusercontent.com/397895/58744493-7172fc80-83f8-11e9-962f-e84eee337d3b.png">

**Comment by klonos** [comment]
Gave the PR sandbox a quick spin...

- borders now are much less "invisible" 👍

- because 1px border is added to both top/bottom on every row, the "in-between" borders are 2px, which makes it weird 👎 ...how about we only add borders to the bottom of every row, and in order to account for tables without header, we also add a top border to the first row?

**Comment by jenlampton** [comment]
Pushed a new PR that doesn't add the box-shadow-border on the top, which prevents the double-border between rows. Needs another review!

**Comment by klonos** [comment]
Just tested this again ...I needed to clear caches in the PR sandbox, and after that everything looked/worked as expected. Thanks @jenlampton ...RTBC 👍

**Comment by quicksketch** [comment]
Thanks @klonos for pulling this one out of the freezer to push it to completion! The code and end result are great, no more tables with no bottom border! I've merged https://github.com/backdrop/backdrop/pull/2716 into 1.x and 1.16.x. Thanks!
