### ISSUE TITLE
[UX] Views: No success message when clicking "Save and exit" if creating a page display

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3848]
**Steps To Reproduce**
Repeat the below steps multiple times, to create a view with a page display, another with a block, and another with no display:

1. Start creating a new view (`/admin/structure/views/add`)
2. Select to create a page/block/nothing
3. **Click on "Save and exit"**, instead of "Continue $ configure"
...

**Actual behavior**
- When creating a block display, or no display, you are redirected to the views listing, and there is a success message 👍:

  ![Screen Shot 2019-06-04 at 7 38 38 am](https://user-images.githubusercontent.com/2423362/58836627-96879980-869c-11e9-8d8e-f936016af981.png)
 
- When creating a page display, you get redirected to that page, but there is no success message:

  ![Screen Shot 2019-06-04 at 7 44 15 am](https://user-images.githubusercontent.com/2423362/58836774-0d249700-869d-11e9-9685-824b158a4ee2.png)

**Expected behavior**

There is a success message when creating a page display, with 2 links to a) configure the view, b) return to the views listing page.

PR: https://github.com/backdrop/backdrop/pull/2793

**Comment by klonos** [comment]
Thanks for picking this up @isabelhaas 👍 ...the PR looks good, except of a rogue trailing space, and some indentation issue (left a comment, with a code suggestion in the PR 😉). Once that's sorted, this is RTBC.

**Comment by isabelhaas** [comment]
Thanks @klonos! I made the changes you suggested to fix the indentation issues.

**Comment by klonos** [comment]
Thank YOU @isabelhaas 👍

**Comment by quicksketch** [comment]
There's an issue in the nesting of `if` statements that might cause both messages to show up: https://github.com/backdrop/backdrop/pull/2793/files#r307398260

**Comment by BWPanda** [comment]
@isabelhaas updated the PR with @quicksketch's suggestion, but I'd like to make another one...

I think the message should be re-worded from:

> Your view was saved. Click here to [configure the view](#) or [return to the views listing page.](#)

to:

> Your view was saved. You may [configure](#) it or return to the [views listing page](#).

**Comment by herbdool** [comment]
Merged! Thank you @isabelhaas, @klonos and @quicksketch
