### ISSUE TITLE
[DX] Rewrite/optimize `config_install_default_config()`

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3849]
Looking at the `config_install_default_config()` function, it seems to me that some slight changes would make sense... But I'd like to know if I'm missing something or why it was written this way in the first place.

I'll explain my proposed changes by way of a PR (that way you can see the diff easily).

---
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2725

**Comment by BWPanda** [comment]
Diff here: https://github.com/backdrop/backdrop/pull/2725/files

**Comment by BWPanda** [comment]
Since `$module_config_dir` is already set to `backdrop_get_path('module', $module) . '/config'` I figure best to reuse that variable for the `is_dir()` check.
And I don't believe there's any point setting the `$storage` variable unless we know `$module_config_dir` is actually a directory.

Small changes, and likely no noticeable performance gain, but can't hurt either, right?

**Comment by klonos** [comment]
I have responded on the PR @BWPanda ...I fully agree with the change in the conditional, where you propose reusing the variable that's already been defined earlier. That makes perfect sense to me, and I don't see any obvious reason why it was not done like that before.

I have no clue about the other change though 😅

**Comment by serundeputy** [comment]
I agree w/ @klonos and @drupol that the proposed change looks sound, but I defer to @quicksketch for this deeply rooted change; also maybe `1.14` target; not really a bug fix as much as a possible performance enhancement.

The test suite passed and the sandbox installed which gives us some confidence that this works (still) for importing config.

What else (if anything) has been done to verify that the change works when default config needs to be imported?

**Comment by quicksketch** [comment]
I think test coverage guarantees there's no regression here. I think it's safe to include in the next bugfix. The logic looks sound and I don't see any way this would create a difference.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2725 into 1.x and 1.13.x. Thanks @BWPanda, @drupol, and @klonos!
