### ISSUE TITLE
[UX] Update "Front page" to "Home page" on the Site information page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3855]
We've changed most of the text in Backdrop for "Front page" to "Home page" but we missed the Site information page:
<img width="1205" alt="Screen Shot 2019-06-06 at 12 51 23 PM" src="https://user-images.githubusercontent.com/397895/59054674-cfb93880-8859-11e9-8b80-656158cf51e0.png">

Like this: 
<img width="1219" alt="Screen Shot 2019-06-06 at 1 03 12 PM" src="https://user-images.githubusercontent.com/397895/59055459-794cf980-885b-11e9-9a72-ef1c2b97e59e.png">

---
PR: https://github.com/backdrop/backdrop/pull/2728

**Comment by klonos** [comment]
LGTM 👍

**Comment by serundeputy** [comment]
Thanks @jenlampton and @klonos 
This is merged into `1.x` and `1.13.x`.  Will ship with `1.13.3`. :shipit: :rocket:
