### ISSUE TITLE
Database configuration setting not used anywhere

### ISSUE THREAD

**Issue by oadaeh** [backdrop/backdrop-issues#3858]
At the end of ```install_system_module()``` in ```core/includes/install.core.inc``` is this:
```
  // Prevent the hook_requirements() check from telling us to convert the
  // database to utf8mb4.
  $connection = Database::getConnection();
  if ($connection->utf8mb4IsActive()) {
    state_set('backdrop_utf8mb4_tables', TRUE);
  }
```

The problem is that ```backdrop_utf8mb4_tables``` is not referenced anywhere else in the code base.

I believe it should be setting ```database_utf8mb4_active```, which is used in the code base, and especially in the sort of situation the comment mentions.

I will have a PR to correct this as soon as I figure out how to do it with GitHub.

---
~~PR by @oadaeh: https://github.com/backdrop/backdrop/pull/2732~~
PR by @oadaeh: https://github.com/backdrop/backdrop/pull/2761

**Comment by klonos** [comment]
RTBC 👍 

...unless we want to include an update hook to remove this from existing config (just for sanity).

**Comment by serundeputy** [comment]
The reasons outlined by @oadaeh make sense to me, but this is above my pay grade :) ... deferring to @quicksketch

**Comment by quicksketch** [comment]
> ...unless we want to include an update hook to remove the previous value from existing config/state (state_del - just for sanity).

Yeah, let's be tidy and include an update hook to fix that in system.install.

**Comment by oadaeh** [comment]
I probably did this incorrectly, but I closed the original PR, due to the two commits and other commits showinwg up between them, and created a new PR here: https://github.com/backdrop/backdrop/pull/2761

**Comment by klonos** [comment]
Thanks @oadaeh 👍 ...RTBC once again 😉

**Comment by quicksketch** [comment]
Super! Thanks merged https://github.com/backdrop/backdrop/pull/2761 into 1.x and 1.13.x.
