### ISSUE TITLE
How to convert variable_[get/set]() to CMI?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#386]
Support question posted here due to: https://github.com/backdrop/backdrop-issues/issues/385

I'm trying to port one of my Drupal 7 modules [Simplify](https://www.drupal.org/project/simplify) to Backdrop (see [GitHub](https://github.com/BWPanda/backdrop-simplify)) and have come across the first problem; variables. Backdrop uses CMI (or at least some version of CMI), but I'm not sure how best to go about migrating my settings from variables to CMI.

Are there any good resources you can point me to? I read through https://www.drupal.org/node/1667896 but, from what I can tell, there's a lot of Drupal 8-specific info there that doesn't apply to Backdrop, making it hard to know what to do and what not to do...

**Comment by Michael-IDA** [comment]
If this is already answered somewhere, please link to it.  No need to re-invent the wheel, Google’s just not that helpful finding info on Backdrop. :(

> Instead of:
> 
> ```
> $variable = variable_get('foo', 'bar');
> variable_set('foo', $variable);
> ```
> 
> It looks like this:
> 
> ```
> $variable = config_get('mymodule.settings', 'foo');
> config_set('mymodule.settings', 'foo', $variable);
> ```

`config_get($config_file, $option = NULL)`

Sorry for the really late question, but how does one find out programmatically what `$config_file` `foo` is in?

(e.g. for code that isn't in a module environment, so you’ve got no way to hard code it.)

Crappy example...

Drupal:
```
$variable_default = 'bar';
$variable_name = $look_this_up_for_me;

$variable = variable_get($variable_name, $variable_default);
```

Backdrop:
```
$variable_default = 'bar';
$variable_name = $look_this_up_for_me;

$config_file = {return the JSON file name that contains $look_this_up_for_me}

$variable = config_get($config_file, $variable_name);
if empty($variable) {
  $variable = $variable_default;
}
```

Thanks,
Michael

**Comment by BWPanda** [comment]
@Michael-IDA I think you just have to know where the config value is stored, or else do your own search (outside of the code) to find it first. Also see: https://github.com/backdrop/backdrop-issues/issues/1954

**Comment by Michael-IDA** [comment]
Hi Peter,

Thanks for pointing me to the right place!

Best,
Michael
