### ISSUE TITLE
Notice : Array to string conversion dans _options_storage_to_form()

### ISSUE THREAD

**Issue by salahjaafar** [backdrop/backdrop-issues#3864]
this error appears

Notice : Array to string conversion dans _options_storage_to_form() (ligne 315 dans /opt/lampp_5.5.19-0/htdocs/core/modules/field/modules/options/options.module).

**Comment by indigoxela** [comment]
Hi salahjaafar,
to be able to actually help you, we'd need some more information regarding _when_ and _where_ this error appears.

Particularly helpful would be a way to reproduce the error.

**Comment by salahjaafar** [comment]
Hello,
I create a new type of content, and when submitting the form this message appears.
here is a picture of the list of installed modules:
![Screenshot_2019-06-15 Modules GSI](https://user-images.githubusercontent.com/47123877/59548702-13432f00-8f4b-11e9-9121-2817cb869671.png)

**Comment by salahjaafar** [comment]
here is the list of errors that appears:
![Screenshot_2019-06-15 Créer Materiels GSI](https://user-images.githubusercontent.com/47123877/59548749-98c6df00-8f4b-11e9-912a-2590c28ece61.png)

**Comment by indigoxela** [comment]
Hm... Can't reproduce this (yet).

You attached a lot of fields to your content type. I suspect, some of these cause errors.

Can you post a list of the types? (From /admin/structure/types/manage/YOURTYPE/fields)

**Comment by indigoxela** [comment]
After almost a month of silence I suppose, you solved your problem.

If this is not the case, feel free to re-open this issue. But please provide us with a way to reproduce the errors or at least more information about your setup.
