### ISSUE TITLE
On dashboard, the Manage Users Accounts links to wrong URL

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3865]
**Description of the bug**

On the new dashboard, the block, User Accounts Overview, has a link to the wrong URL. It goes to Content instead of Users. On version 1.13.2.

---
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2733

**Comment by olafgrabienski** [comment]
Confirmed (for Backdrop 1.13.0).

**Comment by serundeputy** [comment]
Thanks @herbdool @olafgrabienski @klonos @drupol looks good; works good!

Merged into `1.x` and `1.13.x` will ship w/ `1.13.3`.

-----

@drupol if you want to open up a follow up issue re: dashboard module using `'#theme' => 'link'` instead of `'#type' => 'link'` that'd be good.
