### ISSUE TITLE
Typo in BlockText docblock

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3866]
**Description of the bug**
It's referred to as "TextBlock" in the docblock but should actually be "BlockText".

---
PR by @laryn: https://github.com/backdrop/backdrop/pull/2734

**Comment by klonos** [comment]
Hey @laryn 👋 ...not 100% sure how things work with classes etc., but I see that some of the classes that extend `Block` have `SomethingBlock` names:

`ViewsSpecialBlock`
`ViewsBlock`
`NodeBlock`
`DashboardWhateverBlock`
`FieldBlock`

...while others have `BlockSomething`:

`BlockBroken`
`BlockLegacy`
`BlockHero`

I cannot understand why?

**Comment by klonos** [comment]
...they seem to follow the name of their respective file:

`views.special_block.inc` -> `ViewsSpecialBlock`
`views.block.inc` -> `ViewsBlock`
`node.block.inc` -> `NodeBlock`

`block.hero.inc` -> `BlockHero`
`block.text.inc` -> `BlockText`

If that is the case, then `BlockLegacy` class should be in a `block.legacy.inc` file, but it is in `block_legacy.class.inc`. But that is a separate issue 😅

**Comment by klonos** [comment]
...this updates the respective docblock with the correct name of the class as specified in the code following immediately after it, so RTBC 👍

**Comment by laryn** [comment]
@klonos I think you raise some good questions and I don't have the answers. 😄

**Comment by serundeputy** [comment]
Thanks @laryn and @klonos !

Merged into `1.x` and `1.13.x` will ship with `1.13.3`.
