### ISSUE TITLE
[UX] Taxonomy term list: table headers broken when Language module is enabled.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3869]
1. Add at least a couple of terms in a vocabulary, so that you don't get the "No terms available" empty table.
2. Enable Language module (no need to actually add any language)
3. Head over to `/admin/structure/taxonomy`, and click the "List terms" operation of the vocabulary from step 1 above -> the "Operations" header is missing from the table:

    ![Screen Shot 2019-06-15 at 11 14 05 pm](https://user-images.githubusercontent.com/2423362/59551888-aae46400-8fc3-11e9-9060-1e0dcdf649b0.png)

4. Click the "Show row weights" link -> the "Operations" header is shown, but it is over the weight column:

    ![Screen Shot 2019-06-15 at 11 13 55 pm](https://user-images.githubusercontent.com/2423362/59551911-1af2ea00-8fc4-11e9-9016-5b8642ed1d9f.png)

5. Edit the vocabulary, and enable multilingual support.
6. Visit the terms listing page again -> everything works as expected

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2738

**Comment by indigoxela** [comment]
@klonos, good catch, your PR works like a charm.

As it's a tiny bug fix it might even get into the next milestone (I'm not sure about that).

**Comment by jenlampton** [comment]
Code looks good, RTBC.

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2738 into 1.x and 1.15.x.
