### ISSUE TITLE
Wrong description in deprecated function `taxonomy_vocabulary_machine_name_load()`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3874]
https://api.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.module/function/taxonomy_vocabulary_machine_name_load/1

> Legacy wrapper to return the parents of a term by TID.

....whereas: https://api.drupal.org/api/drupal/modules%21taxonomy%21taxonomy.module/function/taxonomy_vocabulary_machine_name_load/7.x

> Return the vocabulary object matching a vocabulary machine name.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2742

**Comment by docwilmot** [comment]
RTBC

**Comment by quicksketch** [comment]
Function summaries should all fit on one line per the documentation standards.

https://github.com/backdrop/backdrop/pull/2742/files#r409131942

**Comment by BWPanda** [comment]
I made a commit to @klonos' PR to address @quicksketch's comment. Then, based on the RTBC status above, I merged https://github.com/backdrop/backdrop/pull/2742 into 1.x and 1.17.x. Thanks @klonos, @quicksketch, @laryn & @docwilmot!
