### ISSUE TITLE
Coding standards: use `elseif` instead of `else if`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3876]
I have done a grep and found ~many~ a few instances of `else if (` in our codebase. See https://www.drupal.org/docs/develop/standards/coding-standards#controlstruct and https://api.backdropcms.org/php-standards#control-structures

> (Note: Don't use `else if` -- always use `elseif`.)

...we should make sure that we don't change any externally-maintained, 3rd-party files, nor .js files (https://api.backdropcms.org/js-standards#control-structures does not mention not using `else if`).

---
PR by @isabelhaas: backdrop/backdrop#2790

**Comment by klonos** [comment]
...should make sure that we don't change any externally-maintained, 3rd-party files, nor .js files (https://api.backdropcms.org/js-standards#control-structures does not mention not using `else if`).

**Comment by klonos** [comment]
Thanks @isabelhaas 👍 RTBC!

**Comment by quicksketch** [comment]
Thanks @klonos and @isabelhaas! Merged https://github.com/backdrop/backdrop/pull/2790 into 1.x and 1.13.x.
