### ISSUE TITLE
Error: Call to undefined function `field_attach_load()`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3878]
I have started porting https://www.drupal.org/project/govcms and I am getting this error while running the installer:

```
Error: Call to undefined function field_attach_load()
in DefaultEntityController->attachLoad()
(line 333 of /core/modules/entity/entity.controller.inc).
```

Any pointers on how to troubleshoot this?

**Comment by indigoxela** [comment]
Can you verify, that core module _field_ is correctly installed, when at that point of the install process?

**Comment by klonos** [comment]
yeah, perhaps you are right @indigoxela ...I have added `module_load_include('inc', 'field', 'field.attach');` just before `field_attach_load()` is called in `entity.controller.inc`, and that moved the installer a bit further, but I then got these:

```
Warning: Use of undefined constant FIELD_LOAD_CURRENT - assumed 'FIELD_LOAD_CURRENT' (this will throw an Error in a future version of PHP) in field_attach_load() (line 578 of /core/modules/field/field.attach.inc).
```

```
Error: Call to undefined function _field_info_collate_fields() in field_attach_load() (line 579 of /core/modules/field/field.attach.inc).
```

...further investigation showed that only very few config files are created at this point:

![Screen Shot 2019-06-21 at 8 28 56 pm](https://user-images.githubusercontent.com/2423362/59916702-3dbd4c80-9463-11e9-8dc1-c9bc8d0750df.png)

**Comment by klonos** [comment]
...I should mention that this is on php7.2

**Comment by indigoxela** [comment]
I guess module_load_include() won't do the trick.

FIELD_LOAD_CURRENT, for instance, is defined in core/modules/field/field.module.

**Comment by klonos** [comment]
I did get through the installer after multiple attempts (kept refreshing the installer page at the point where modules are bring installed). After the installation, there was no theme enabled (I can fix that I believe), some basic-functionality modules like the admin bar and dblog were disabled (also fixable), and of course no default content either (as it was not in the config of the new profile - also fixable).

Not giving up on this one 🙂

**Comment by klonos** [comment]
...I wish that there was some way to have the installer be more verbose via some setting in settings.php.

**Comment by herbdool** [comment]
Since you are trying this out on an install profile that has a lot of code that's not in core, I don't think having an issue in the core issue queue is a good idea. I recommend creating a backdrop contrib project and using the issue queue there. Only create an issue here if you're sure it's a core issue.
