### ISSUE TITLE
Update the html5shiv library to version 3.7.3.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3880]
We currently use 3.7.2

https://github.com/aFarkas/html5shiv/releases/tag/3.7.3

**Comment by klonos** [comment]
...I'm adding this as a to-do. Will need to wait on some clean-up I am doing on #3879

**Comment by hosef** [comment]
I created a PR to update the html5shiv library from 3.7.2 to 3.7.3.

**Comment by klonos** [comment]
Changes between 3.7.2 and 3.7.3: https://github.com/aFarkas/html5shiv/compare/3.7.2...3.7.3

**Comment by herbdool** [comment]
I did a code review. The changes look pretty minimal. Not sure how to test.

**Comment by klonos** [comment]
Not sure that it is worth spending time specifically testing things here. This shiv is added in order to provide support for legacy browser versions (Internet Explorer 6-9, Safari 4.x (and iPhone 3.x), and Firefox 3.x), which should be considered best-effort.

According to https://en.wikipedia.org/wiki/Usage_share_of_web_browsers as well as other sources on the internetz, the global market share of all versions of these browsers seem to be:

IE: ~3-6%
Firefox: ~8%-9%
Safari: ~5%-10%

These numbers represent all versions of these browsers, which means that the legacy versions have trivial usage numbers.

If you look at the top 10 browser stats here: https://www.w3counter.com/globalstats.php which seem to be ~71% of global usage ...you'll see that none of these versions are even listed there.

**Comment by BWPanda** [comment]
Let's just do it. I've looked at the changes and they're pretty basic. Looks good to me.

**Comment by laryn** [comment]
Thanks @hosef, @klonos, @herbdool and @BWPanda for filing, fixing, and looking over this one. I've [merged](https://github.com/backdrop/backdrop/pull/3094) into 1.x and 1.22.x.
