### ISSUE TITLE
[UX] Content type listing page: style it consistently with the Views listing page

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3882]
Sibling issue to #2029 and #3886

Current:

![Screen Shot 2019-06-22 at 10 52 04 pm](https://user-images.githubusercontent.com/2423362/59964171-62d3bd00-9540-11e9-8d83-42a03cfd5bd7.png)

Proposed:

![Screen Shot 2019-06-22 at 10 48 07 pm](https://user-images.githubusercontent.com/2423362/59964175-69facb00-9540-11e9-89d0-9776e7aa20f6.png)

- split description into its own column, and add `priority-low` class, so that it can be hidden on mobile.
- bold the content type name, for better scannability/readability.
- wrap machine name into a second line, and make the font smaller.
- font in rows of disabled content types should be grayed out (`#999999`).

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2746

**Comment by klonos** [comment]
https://github.com/backdrop/backdrop/pull/2746

Mobile:

![Screen Shot 2019-06-22 at 10 47 51 pm](https://user-images.githubusercontent.com/2423362/59964283-4769b180-9542-11e9-9880-32a5ab729543.png)

The enable/disable feature is not included in this PR, as it would make it a feature request instead of a UX task: #3883

**Comment by bugfolder** [comment]
@klonos, would you rebase the PR https://github.com/backdrop/backdrop/pull/2746, which has conflicts, and add the magic "Fixes" word to the first comment?

(BTW, I think these changes are indeed good UX improvements.)

**Comment by klonos** [comment]
Some time has passed between when this issue and PR have been filed, and most of the things outlined in the issue description have already been implemented in recent versions of Backdrop. Here's what that page looks like now:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/cd3e8f6d-2b9a-4227-a91b-cb69a9acc59f)

So, to the points in the issue summary:
> - split description into its own column, and add `priority-low` class, so that it can be hidden on mobile. 

This has been done, with the exception of adding the `priority-low` class to the description column.

> - bold the content type name, for better scannability/readability.
> - wrap machine name into a second line, and make the font smaller.

This has been done 👍🏼 ...the newly-introduced `theme_label_machine_name()` function is being used to consistently output machine names across various listing pages now. Most of all this has been addressed as part of #3402.

> - font in rows of disabled content types should be grayed out (`#999999`).

I don't see any option to disable content types. Regression? Functionality intentionally removed? Was it even there to begin with? (perhaps it was something I was playing with on my local) ...in any case, outside the scope of this issue here.

I'm gonna go ahead and close this as outdated/WAD.
