### ISSUE TITLE
Installer module should check for file-write permissions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3893]
**Description of the need**
We have this problem on Pantheon with the installer module: If the site is not in SFTP mode, then the installer can't install. 

We know that the installer can't install, so when we try to install something, we throw a nice error saying that there's a permissions issue. 

**Proposed solution**
Why don't we use this check as a dependency for the installer module? If you can't write modules to your filesystem, then you can't use this module.

**Comment by quicksketch** [comment]
Maybe this should be marked a duplicate of https://github.com/backdrop/backdrop-issues/issues/4472?
