### ISSUE TITLE
Basis Theme: Make "Drop the Dragon" Optional

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#3895]
**Description of the need**
Ability for user to hide Drop the Dragon in basis theme. 

Until now, I have loved having Drop the Dragon in Basis theme, because I've only used Basis (out of the box) for demo'ing Backdrop and Drop looks very friendly sitting at the bottom of the page. 

I've always built my sites with custom themes that did not include Drop. 

Recently, I've been thinking about creating a tutorial on all the ways that you can customize your site using Basis out of the box. As I think about all the options that a simple site builder can use to customize their site using Basis, it occurs to me that they do not have the ability to remove Drop. I suspect that very few users would actually want to keep Drop on their own custom site.  

If we would like for the Basis theme to be useful to simple site builders, I think Drop should be optional. I don't want to remove it. 

**Proposed solution**
A checkbox in the theme that allows the user to hide/remove Drop. I think that it's great to have Drop there by default, but a simple site builder should have the option to hide it. 

**Alternatives that have been considered**

1) I am considering a contrib fork of basis that has all the best features of Basis but with changes that make it more versatile and usable for site builders with simple needs. 
2) Users can simply use any other existing contrib theme if they don't want Drop there. 
3) Removing Drop completely from Basis (hopefully not necessary). 

**Additional information**

Is there a way to remove Drop through the UI and I'm simply missing it?

**Comment by oadaeh** [comment]
Is it not removable for you by removing the "Powered by Backdrop" block in the Footer regions of your layouts? That works for me.
Unless what you're asking for is to separate the logo from the text into two separate blocks.

**Comment by stpaultim** [comment]
@oadaeh - Your right. I was certain that I tried that, but clearly I didn't get it right. 

It seemed odd to me that there would not be a way to remove the dragon. Turns out it was just user error.
