### ISSUE TITLE
url_alias column: language or langcode

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3897]
This issue is from @dmyerson but was posted under backdrop-ops:

> I documented this in the forum at https://forum.backdropcms.org/forum/d7-conversion-crash, but the short story is that on bootstrap when I am trying to convert my D7 site to backdrop, it is crashing because D7 has `url_alias.language` while backdrop is querying `url_alias.langcode`.

**Comment by jenlampton** [comment]
> D7 has url_alias.language while backdrop is querying url_alias.langcode

@dmyerson When upgrading from Drupal to Backdrop the database update script (`update.php`) will change the  the `url_alias` table from `language` to `langcode`.  If you are not seeing that change, then something must have gone wrong when you ran the update script. Did you see any errors or other messages when it completed?

**Comment by dmyerson** [comment]
The site is trying to access url_alias while booting so I can't bring up the site to run update.php with this error. So it is a catch 22 problem. How can you run update.php when you can't bring up the home page?

**Comment by dmyerson** [comment]
OKay, I typed in the update.php url from scratch and it started running. It stopped with errors but I found that by keeping on running it, it got down to one remaining (views) update. The front page now has this error: ConfigStorageReadException: The configuration file "taxonomy.vocabulary.tags" is not properly formatted JSON. Contents: <pre> </pre>in ConfigFileStorage->read() (line 1134 of C:\Apache24\htdocs\dev2\core\includes\config.inc).  I would emphasize that this is a test upgrade to see how it would go and I was not expecting to actually use this site. I should probably throw it away at this point and start all over again, noting the need to run mydomain.com/core/update.php from the start.

**Comment by jenlampton** [comment]
> The site is trying to access url_alias while booting so I can't bring up the site to run update.php with this error. So it is a catch 22 problem. It's trying to get an alias for the home page.

Why do you want to access the home page before the update? 

Type in the URL http://example.com/update.php and run the update script first, then after the update completes you'll be able to get to the home page.

**Comment by dmyerson** [comment]
I tried to get to the homepage first because that's how I always ran update.php in the past. I would just note that it is example.com/core/update.php.

**Comment by jenlampton** [comment]
> I tried to get to the homepage first because that's how I always ran update.php in the past.

Ah, well I wouldn't recommend doing that. Visiting any page on a Drupal/Backdrop site before the update has been run will cause database reads and writes that can sometimes cause problems (as you've noticed!). This is especially true for a major version upgrade from something like Drupal 6 to Drupal 7 or Drupal 7 to Backdrop.

**Comment by jenlampton** [comment]
I wonder if many people have this habit. Maybe we should add something to our update instructions to specially state that the update needs to run before things will work as usual... Adding the documentation tag.

**Comment by dmyerson** [comment]
I did update my forum post on this issue with that - just type in the full url to run it, don't try to bring up the front page first. I think it would be good to add to the D7 conversion documentation.

**Comment by jenlampton** [comment]
Thank you.  :)
I just re-read your comment containing the error from the update. It's strange that the tags vocabulary config file is empty. If that happens when you run the update again, would you please open a new issue? If it happens consistently, we should look into why.

**Comment by jenlampton** [comment]
I found the line in the documentation about running the update, and it is quite ambiguous: `Navigate to this site in a browser, and visit /update.php to proceed with the update.`

That could *definitely* be read as "Visit the home page and click a link to get to update.php"

Thank you for bringing this to our attention!

**Comment by jenlampton** [comment]
Okay, I have updated the upgrade docs as follows:

* Open up a browser and visit https://example.com/update.php to proceed with the update. (Replace example.com here with your domain or local site alias.)
  - Note: You will need to be both logged in and have sufficient privileges to run the update. If this is not the case you can change $settings['update_free_access'] = TRUE;  in your settings.php file.
  - Note: Your site will not function normally until after the update has been run, we recommend you run the update script before visiting any other page on your site.

**Comment by klonos** [comment]
Thanks @jenlampton ...I have done a quick run-through and tweaked https://backdropcms.org/upgrade-from-drupal here and there, so that long sentences are made shorter, or proper punctuation is used. Hope that things are more readable and make more sense now.

Could use another pair of 👀, but I realize that that document is meant to be updated iteratively as we go.
