### ISSUE TITLE
[UX] Editor image modal title should be 'Edit image details'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3898]
**Description of the bug**

When editing existing content containing an inline image, you have the ability to change the details of that image such as: the alt text, size, alignment, and whether the image has a caption, and replacing the image. You do not have the ability to edit the image itself. The title of this modal is 'Edit image'.

**Steps To Reproduce**
To reproduce the behavior:
1. Create a post, add an image via the rich-text editor, save the post.
2. Edit the same post again.
3. Double click on the inline image.
4. Read the title of the modal that pops open.

**Actual behavior**
Modal title reads `Edit image`

**Expected behavior**
Modal title should read `Edit image details`

This can be fixed by updating line 178 in `filter.module`

---
PR by @isabelhaas: https://github.com/backdrop/backdrop/pull/2764

**Comment by klonos** [comment]
The PR is RTBC. Thanks @isabelhaas 👍 

Having said that, I don't think that "Edit image details" encompasses the remove/replace image actions possible via that same dialog; but I don't have any good suggestion either 🤔

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2764 into 1.x and 1.13.x. Thanks!
