### ISSUE TITLE
[DX] Add config->getData() to match config->setData()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3902]
**Description of the need**
I know that `$config->get()` -- with no parameters passed -- gets all the data from a config file, but every time I'm using `config->setData()` I always first type `config->getData()` when attempting to retrieve the data. It doesn't ever work, and I always have to look it up. 

**Proposed solution**
Can we add `$config->getData()` even just as a wrapper function to `$config->get()` for consistency?

**Comment by quicksketch** [comment]
Looks good. I suggested adding a `@since` line and milestoning this to `1.23.0` if that sounds good to folks.

**Comment by BWPanda** [comment]
Marking as needs work as @quicksketch made a suggestion in the PR that is yet to be committed, and the PR should also probably be rebased so that the new GH Actions tests can run.

**Comment by herbdool** [comment]
@quicksketch @BWPanda I think we have a couple options given that there is a tiny change to a docblock and no response in a while:

1. Merge the PR and then add the `@since` afterwards.
2. Merge the alternative PR I created https://github.com/backdrop/backdrop/pull/4183 which was branched from @jlfranklin's PR with the added small change.

**Comment by herbdool** [comment]
I'm marking it rtbc because the only change from the previous rtbc was to add a `@since` line to the docblock.

**Comment by quicksketch** [comment]
Thanks @herbdool! Yeah I should have made a PR myself. With some PRs I can merge the `@since` line directly onto the existing PR, which is what I normally do. 

Thanks @jlfranklin for the PR and @jenlampton for the suggestion. This has been merged into 1.x for 1.23.0!
