### ISSUE TITLE
Redirect from cron.php to core/cron.php is too greedy

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3903]
**Description of the bug**
I have CiviCRM installed on a Backdrop site. Civi has its own cron file at `modules/civicrm/bin/cron.php`. But when trying to use it, it'll redirect to `modules/civicrm/bin/core/cron.php`.

**Expected behavior**
Backdrop should not try to redirect files that are not part of Backdrop.

**Comment by herbdool** [comment]
This redirect happens in `.htaccess`:

```
  # Redirect common PHP files to their new locations.
  RewriteCond %{REQUEST_URI} ^(.*)?/(update.php) [OR]
  RewriteCond %{REQUEST_URI} ^(.*)?/(install.php) [OR]
  RewriteCond %{REQUEST_URI} ^(.*)?/(cron.php)
  RewriteCond %{REQUEST_URI} !core
  RewriteRule ^ %1/core/%2 [L,QSA,R=301]
```

So this is gobbling up all files with the same name and tacking on `/core` at the end of the path.

In the meanwhile I've used the CLI version for calling CiviCRM cron https://docs.civicrm.org/sysadmin/en/latest/setup/jobs/#php-cli

**Comment by herbdool** [comment]
Doing this `RewriteCond %{HTTP_HOST} ^(.*)?/(cron.php)` seems to work but I'm not sure if it respects if Backdrop is installed in a sub-directory.

**Comment by catorghans** [comment]
This works:

`# Redirect common PHP files to their new locations.
RewriteCond %{REQUEST_URI} ^(.*)?/(update.php) [OR]
RewriteCond %{REQUEST_URI} ^(.*)?/(install.php) [OR]
RewriteCond %{REQUEST_URI} ^(.*)?/(cron.php)
RewriteCond %{REQUEST_URI} !core
RewriteCond %{REQUEST_URI} !civicrm
RewriteRule ^ %1/core/%2 [L,QSA,R=301]`

**Comment by herbdool** [comment]
@catorghans thanks for this - this might help anyone who wants to edit their own .htaccess file. Though changing core, we'd need to find a way to fix this without making the fix specific to any one non-Backdrop application. So it can't mention civicrm.

**Comment by catorghans** [comment]
Well, I do think civicrm is not yet another app for backdrop, but I see your point. It should be more specific. 
But I see the reason for ending with cron.php etc, because backdrop can start from a subdirectory, so we can not do ^/cron.php

**Comment by herbdool** [comment]
@catorghans even if the site was installed in a subdirectory, wouldn't the .htaccess still be in the subdirectory too? I can't recall exactly how that works.

At any rate maybe there's a way to take one level of subdirectory without including civicrm's cron. I think this would work: `^(.[^\/]*\/){1,2}(cron.php)`. It includes `/cron.php` and `/subdirectory/cron.php` but ignores `/modules/civicrm/bin/cron.php`.

**Comment by catorghans** [comment]
Yeah, I was trying to find how .htaccess can find files in #current# directory. Have failed sofar.
Your  proposal then would make this the only reason backdrop can not be installed in
/public_html/dir/subdir/subsubdir/backdrophome

Probably very rare, but still, hard to explain what happens then and why.

Finding "current" dir in .htaccess would be the best imo. 
And if not possible.... move this to tiny core module (or add it to an existing one).

I would even say: if we find usage of cron.php/update.php/install.php from root dir, make a warning on status page: update your scripts, they are still drupal-like...

**Comment by catorghans** [comment]
> @catorghans even if the site was installed in a subdirectory, wouldn't the .htaccess still be in the subdirectory too? I can't recall exactly how that works.
> 
> At any rate maybe there's a way to take one level of subdirectory without including civicrm's cron. I think this would work: `^(.[^\/]*\/){1,2}(cron.php)`. It includes `/cron.php` and `/subdirectory/cron.php` but ignores `/modules/civicrm/bin/cron.php`.

current-dir in .htaccess I did not find.

I now think excluding "modules" is a proper solution
`RewriteCond %{REQUEST_URI} !modules`

Any custom/contrib module in either /modules or /sites/[site]/modules can then have it's own cron.php/update.php/install.php
wdyt?

**Comment by herbdool** [comment]
Sure that seems reasonable.

**Comment by quicksketch** [comment]
Thank you @bugfolder for reviewing! I merged https://github.com/backdrop/backdrop/pull/3961 into 1.x and 1.21.x.

Thanks @catorghans and @herbdool for working out a low-risk solution!
