### ISSUE TITLE
[D8][UX] Update the dated icons for sorting tables

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3906]
Those caret icons are dated, and they are being used all over the place:

<img width="1189" alt="Screen Shot 2019-06-30 at 8 59 24 am" src="https://user-images.githubusercontent.com/2423362/60390252-b6807080-9b15-11e9-9d1d-12304964d0cc.png">

It does make sense when used to expand/collapse things:

<img width="1206" alt="Screen Shot 2019-06-30 at 9 06 17 am" src="https://user-images.githubusercontent.com/2423362/60390289-9bfac700-9b16-11e9-8eb1-a68ad7997756.png">

...but we should be using more universally acceptable icons for sorting.

Here's what is being implemented in the new D8 admin theme that is being developed at the moment:

<img width="951" alt="Screen Shot 2019-06-30 at 9 12 43 am" src="https://user-images.githubusercontent.com/2423362/60390313-44a92680-9b17-11e9-86b0-d0c274582435.png">

**Comment by klonos** [comment]
I was about to ask for a review of both PRs here, but when I tried to refresh the sandboxes I got problems again 😓 (see #4351)

**Comment by herbdool** [comment]
Either pr looks good to me. What do other people prefer? Are there other places to change if we use the new ones?

**Comment by olafgrabienski** [comment]
I like the `sort-amount-up` and `sort-amount-down` icons more. Just the arrows, they are visually too narrow, in my opinion.

We use (the `down` variant of) it for the *Structure* item in the *Admin bar*, there is doesn't have the same meaning -- not sure if that's a problem. Wanted to have a look at it, but sandboxes don't work for me atm.

**Comment by klonos** [comment]
I've restarted the PR sandboxes. Let's hope that things will come back green 🤞 

@olafgrabienski I hear you re the arrows being to narrow/small. I have also thought of these:

https://fontawesome.com/icons/sort-alpha-up-alt?style=solid
https://fontawesome.com/icons/sort-alpha-up?style=solid
https://fontawesome.com/icons/sort-alpha-down-alt?style=solid
https://fontawesome.com/icons/sort-alpha-down?style=solid

![image](https://user-images.githubusercontent.com/2423362/83571459-79480e00-a530-11ea-8283-b590e984de12.png)

But these would only make sense when sorting alphanumeric things, like node titles etc. - it wouldn't work so great with numbers/dates, which means that we'd need a way to tell things apart, and then use the numeric equivalents:

https://fontawesome.com/icons/sort-numeric-up-alt?style=solid
https://fontawesome.com/icons/sort-numeric-up?style=solid
https://fontawesome.com/icons/sort-numeric-down-alt?style=solid
https://fontawesome.com/icons/sort-numeric-down?style=solid

![image](https://user-images.githubusercontent.com/2423362/83571653-d774f100-a530-11ea-957a-b3b642d6b0da.png)

I also hear you re the `sort-amount-down` icon being used in Structure. Perhaps we need to update that one 🤔 ...Drupal uses this:

![image](https://user-images.githubusercontent.com/2423362/83571783-19059c00-a531-11ea-8025-debbc6fe5453.png)

...but I wasn't able to find a free alternative for it in fontawesome 😞 ...anyway, that should be a separate issue.

**Comment by klonos** [comment]
Can I please get some feedback here? ...there are 2 PRs, each one using different icons. Can people please test and chime in to say what they think? ...do you agree with the change? ...do you have an alternative set of icons to propose instead?

PS: I've rebased both PRs, and confirmed that tests are passing and sandboxes spin up w/o issues (at least the Tugboat ones).

**Comment by indigoxela** [comment]
The sorting icons containing (latin) characters or numbers don't seem optimal to me, as they're not generic and might be the wrong choice for different languages, especially character sets. But I don't know what might represent sorting in Chinese anyway. :wink: 

Regarding the other ones (arrows with or without bars, or carets), I don't have any preference. Whatever fits.

**Comment by BWPanda** [comment]
I understand my suggestion (below) is a larger issue, but if we're considering changing icons then it should be considered now, rather than needing to change things again in future...

I propose using icon fonts rather than images, since we're discussing dark themes in other issues, and one of the sticking points is that most of our icons/images are designed only for light-coloured backgrounds. An icon font will make it easier to allow different coloured icons on different coloured backgrounds.

At least keep that in mind when deciding how to implement new icons here.

As for which icons to use, I like the arrows next to the varying-length bars.

**Comment by klonos** [comment]
> I propose using icon fonts rather than images

@BWPanda care to un-postpone #364 then? 😅 ...would open the door for things like #3819 too 😉

**Comment by BWPanda** [comment]
Hmm, it seems that SVGs were discussed there, and that would solve the same problem here (allowing icon colours to change)...

**Comment by olafgrabienski** [comment]
> I like the `sort-amount-up` and `sort-amount-down` icons more. Just the arrows, they are visually too narrow, in my opinion.

Looking again into it, I guess I have changed my mind completely:

- Of the two new suggestions, I like the arrows more. Compared to the sort-amount icons, the arrows look more clear to me. They are still narrow, but it isn't a problem with enough padding.
- I've also compared the new suggestions to the existing icons (carets). Actually, the existing ones don't look dated at all, in my opinion. Maybe it makes more sense to update the icons as part of a bigger overhaul (or of a new admin theme).

Apart of that, both PRs seem to put the icons the wrong way round. Example: `admin/content?order=title&sort=asc` displays the icons pointing *down*.

**Comment by klonos** [comment]
> both PRs seem to put the icons the wrong way round

Hehe, I guess it's the way people look at things: do the buttons convey the current sorting order, or the sorting you will get when you click on them? 😅 

Anyway, I'm happy to change the order, but let's get some more feedback first.

> Actually, the existing ones don't look dated at all, in my opinion.

It's not only that the current ones look dated (which can be a totally subjective opinion):
- They are gray color over dark blue background, which makes them less accessible
- The "down" ones are the same as what we use in fieldsets, and in drop buttons. The fieldset/dropbutton icons both have the action of expanding, whereas the ordering icons need to convey sorting/direction.

> Maybe it makes more sense to update the icons as part of a bigger overhaul (or of a new admin theme).

That would take time though, and I have found it that it's harder to get bigger sets of changes in 😓 ...I don't want to wait long for changes that are "easy wins".

**Comment by olafgrabienski** [comment]
@klonos I agree that the icons, apart of the "dated" question, are not ideal. Personally, I don't have strong feelings about which icon choose. If the goal is an 'easy win', I'd however suggest the arrows without sorting symbol, so that we don't have to (wait for a) change (of) the Admin bar "Structure" icon.

Re "do the buttons convey the current sorting order?": I'm skeptical if we should change the behavior people are used to. However, if your change intentional, it should also be mentioned in the issue description.

**Comment by klonos** [comment]
> I'm skeptical if we should change the behavior people are used to. However, if your change was intentional, it should also be mentioned in the issue description.

Nope, not intentional at all. Happy to change it if others agree re it being the "wrong" direction. Just waiting for more feedback.

> ...so that we don't have to (wait for a) change (of) the Admin bar "Structure" icon.

I hear you 👍 ...I'd like to fix both these things though. We never seem to have found a good icon for "Structure", so we went with the current one, which is not ideal at all.

**Comment by BWPanda** [comment]
If we're going to change icons, the new icons should point in the same direction as the old ones. I see only confusion otherwise.

We can open a separate issue to discuss different arrow directions if needbe, but I don't think it should be part if this change.

**Comment by klonos** [comment]
Here's the PR that uses `sort-amount-up` and `sort-amount-down`: https://github.com/backdrop/backdrop/pull/2765

![Screen Shot 2019-06-30 at 10 33 33 am](https://user-images.githubusercontent.com/2423362/60390826-a327d200-9b22-11e9-98bf-08030859a652.png)

**Comment by klonos** [comment]
...and the PR that uses `fa-long-arrow-up` and `fa-long-arrow-down`: https://github.com/backdrop/backdrop/pull/2766

![Screen Shot 2019-06-30 at 10 52 20 am](https://user-images.githubusercontent.com/2423362/60390905-382bca80-9b25-11e9-971d-ae2260aced93.png)

**Comment by klonos** [comment]
...please provide feedback and up/down-vote on the comments above^^, using 👍 / 👎 as reaction.

**Comment by philsward** [comment]
I didn't think to ask this earlier, but would you mind adding an option for the regular fontawesome arrow? I have a feeling it wont look as good, but at least we can see the comparison. No worries if that's out of the question.

**Comment by klonos** [comment]
@philsward can you please provide a link to the fontawesome arrow icon you are referring to? Happy to provide a PR and screenshot.

**Comment by philsward** [comment]
@klonos give these a try

https://fontawesome.com/icons/arrow-up?style=solid

https://fontawesome.com/icons/arrow-down?style=solid

**Comment by BWPanda** [comment]
Another option (as if we need *more* options) is to have one icon to indicate sortability, and then change it to an up/down arrow when actually used for sorting.

I got this idea from Drupal 8's Webform module. Here's a screencast:
![Peek 2020-12-15 13-19](https://user-images.githubusercontent.com/2385329/102159818-626b7680-3ed8-11eb-9ea5-c174c478018b.gif)

**Comment by philsward** [comment]
I do like the D8 approach @BWPanda pointed out.

**Comment by docwilmot** [comment]
To maliciously seed confusion, I take @BWPanda's suggestion but would prefer use the *three-bars-plus-an-arrow* icons instead of the single arrow for the sorted rows.

**Comment by klonos** [comment]
> To maliciously seed confusion...

😈

**Comment by philsward** [comment]
@docwilmot did you vote for it?? ⬆️ 😝

**Comment by stpaultim** [comment]
I'm looking at this (somewhat) old issue for the first time. I don't feel strongly about this issue, but I think that the `three-bars-plus-an-arrow` icon looks good. I would consider this a small improvement.

**Comment by herbdool** [comment]
I agree with @stpaultim, three bars with an arrow.

**Comment by herbdool** [comment]
Tested the three bars with an arrow and it looks great. Code looks good too.

In case anyone else is wondering the fontawesome free is GPL friendly (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt). I couldn't recall if we were using their icons anywhere else.

I think eventually the icons in Seven could switch to using SVG but it should be a separate issue.

**Comment by olafgrabienski** [comment]
> No reason not to update this one?

Not at all! And now let's also revive https://github.com/backdrop/backdrop-issues/issues/4427. (Most people voted for the [layer-group icon](https://github.com/backdrop/backdrop-issues/issues/4427#issuecomment-743970438).)

**Comment by klonos** [comment]
> I couldn't recall if we were using their icons anywhere else.

We are (IIRC all the Admin Bar icons, the Dashboard, the icons in `/admin/config`, and elsewhere). We usually use an online service like https://fa2png.app to convert them to .png.

> I think eventually the icons in Seven could switch to using SVG but it should be a separate issue.

Not sure about SCGs, but we have #364, in which we discussed fontawesomme.

**Comment by klonos** [comment]
...I guess that by `three-bars-plus-an-arrow` everyone refers to the `sort-amount-up`/`sort-amount-down` pair. Right?

**Comment by laryn** [comment]
Re #364  — note @wesruv’s comment and following:
https://github.com/backdrop/backdrop-issues/issues/364#issuecomment-796897147

**Comment by klonos** [comment]
@laryn my preference was plain arrows - just going with what the majority wants here. If I had to choose between the two though, then I'd lean towards the `-alt` variant, since it makes it more visually distinct.

Here's a PR for that: https://github.com/backdrop/backdrop/pull/3715

**Comment by klonos** [comment]
...to make it clear, since the difference is subtle, we're takling about this:

![image](https://user-images.githubusercontent.com/2423362/131394193-4a8addda-f2cc-4142-a2d0-f6f17be3e4bc.png)

...vs. this:

![image](https://user-images.githubusercontent.com/2423362/131393993-29222af1-a780-4a9f-8bda-2412557ffd79.png)

**Comment by klonos** [comment]
...vs. this (`sort-amount-down`):

![image](https://user-images.githubusercontent.com/2423362/131393993-29222af1-a780-4a9f-8bda-2412557ffd79.png)

**Comment by laryn** [comment]
Am I bikeshedding with this? Riffing on https://github.com/backdrop/backdrop-issues/issues/3906#issuecomment-745008643 I did a quick mock with the bars visually unsorted:

![Screen-Shot-2021-08-30-at-3 09 16-PM](https://user-images.githubusercontent.com/871421/131399358-92b43850-24a0-4e09-aa4c-6666a6356147.png)

Using: 
![sort-amount-unsort--white--64](https://user-images.githubusercontent.com/871421/131399370-1ebef5b7-c961-421a-8c40-62b4f9b76daf.png)

**Comment by klonos** [comment]
I like that icon @laryn ...is it fontawesome, and if so, then which one is it? (it would have to be black or some dark gray color though, since the unsorted headers are light gray and we'd have accessibility issues)

**Comment by laryn** [comment]
@klonos It's taken from the fontawesome icons you were using and then tweaked in Photoshop. I'm sure we can adjust colors on the SVG and then export as a PNG if we know which colors to use.

**Comment by klonos** [comment]
@laryn IU admire your creativity! ...you've made an icon that I find to be quite accurately denoting "unsorted" 👏🏼 

Can you please provide a transparent 64px .png in `#444b53`, and another in `#000000`? I wanna "play" with it 😅

**Comment by laryn** [comment]
@klonos  [unsorted.zip](https://github.com/backdrop/backdrop-issues/files/7085630/unsorted.zip)

**Comment by laryn** [comment]
@klonos Are we moving this back to "Needs work"? What's your feeling on it.

**Comment by klonos** [comment]
@laryn I was hoping to get more feedback before adding the "unsorted" icon, but it can be a follow-up.

The currently approved variation is the one with `sort-amount-down`, but we still need people to chime in re using `sort-amount-down-alt` instead:

![image](https://user-images.githubusercontent.com/2423362/132890702-5befc1ba-365d-42ba-b376-e843b1e1f0e8.png)

**Comment by bugfolder** [comment]
When I look at both and ask myself "which conveys sorting alphabetically versus inverse alphabetically?", I'm not sure from either. I'll just click it and then go "oops, I wanted the other way" and click again. (So no preference.)

**Comment by olafgrabienski** [comment]
> The currently approved variation is the one with `sort-amount-down`, but we still need people to chime in re using `sort-amount-down-alt` instead

I've just had a look at both PRs. The alternative icon `sort-amount-down-alt` helps me better to understand the sort order.

**Comment by klonos** [comment]
Thanks everyone for chiming in. Can someone please add the 1.19.4 milestone to this issue?

**Comment by herbdool** [comment]
Same @olafgrabienski

**Comment by klonos** [comment]
Thanks @laryn 👍🏼 

Follow-up for the "unsorted" icon: #5221 😉

**Comment by robertgarrigos** [comment]
I just come across this issue when I realized that the icons we are showing now are inducing me to confusion.

Right now we are showing these icons:
![131394193-4a8addda-f2cc-4142-a2d0-f6f17be3e4bc](https://user-images.githubusercontent.com/105581/202693505-105ebf26-f215-48e0-a936-6dad51236f5d.png)
which in fact mean the same: ascendant sorting, from the smaller line to the larger line. The only difference is that there are shown upside-down.

Whether these icons:
![131393993-29222af1-a780-4a9f-8bda-2412557ffd79](https://user-images.githubusercontent.com/105581/202694137-f48bafb6-9f2b-43cc-b936-c7ef50176cf5.png)
are really showing different sorting: descendant on the left, from de larger line to the smaller line, and ascendant on the right, from the smaller line to the larger line.

Thus, I would suggest using the second set of icons, instead of the first one.

**Comment by olafgrabienski** [comment]
@robertgarrigos I agree with you, if you look at the icons in an analytical way. But when I just have a quick look at the icons, the first icon set seems more appropriate to me. I guess, that's because in the first set both elements change, and it's easier to recognize the direction of the arrow.

**Comment by robertgarrigos** [comment]
@olafgrabienski I agree that for a quick look, the arrow is very graphic, but then it shouldn't be contradictory when you look at it closely. If we use those icons just because of the arrow, let's forget about anything else which is giving wrong information.

**Comment by olafgrabienski** [comment]
> If we use those icons just because of the arrow, let's forget about anything else which is giving wrong information.

Well, I'm open for that, and it reminds me at the begin of the discussion in this thread and some comments below, e.g. https://github.com/backdrop/backdrop-issues/issues/3906#issuecomment-743055761. Anyway, as this issue here is fixed and closed, maybe open a new issue to put the decision into question?
