### ISSUE TITLE
[UX] Seven theme: Fix breadcrumb in RTL

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3907]
Follow-up to #3554, but for the Seven theme.

Before:

<img width="457" alt="Screen Shot 2019-06-30 at 11 24 06 am" src="https://user-images.githubusercontent.com/2423362/60391102-90b19680-9b2a-11e9-97ab-5d0646f0ccb4.png">

After:

<img width="462" alt="Screen Shot 2019-06-30 at 12 03 00 pm" src="https://user-images.githubusercontent.com/2423362/60391323-0d467400-9b2f-11e9-8168-fdfa119dbb35.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2767

**Comment by stpaultim** [comment]
I tested in sandbox and it's working for me as described. I'm confused about reading words right to left but letters within words left to right.

**Comment by klonos** [comment]
> I'm confused about reading words right to left but letters within words left to right.

Thanks for reviewing @stpaultim 👍 ...it does require some getting used to for us LTR readers, but it is actually kinda obvious once you get the hang of it 😄. If you agree with the milestone, please set to 1.13.3.

Pinging @shabibalm for this 😉

**Comment by VasasA** [comment]
I tested the PR in my local test environment and in the sandbox https://github.com/backdrop/backdrop/pull/2767 with Chrome 75.0.3770.142 and Firefox 68.0.1, works fine.
![kép](https://user-images.githubusercontent.com/8567234/62663085-8dee6080-b976-11e9-99d7-7f2ef94c3310.png)

**Comment by quicksketch** [comment]
Looks great! Thanks @klonos, @stpaultim, and @VasasA!
