### ISSUE TITLE
Remove 'field_ui.admin.incmate' from Field UI module

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#3912]
A blank file exists in the Field UI module called `field_ui.admin.incmate`. Guessing this was an accident...?

----

PR by @BWPanda https://github.com/backdrop/backdrop/pull/2772

**Comment by serundeputy** [comment]
thanks @BWPanda and @herbdool merged into `1.x` and `1.13.x` will ship with `1.13.3`.
