### ISSUE TITLE
Fatal error: "Column 'tid' cannot be null" when term reference fields, with select list as widget, link to vocabularies w/o any terms

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3913]
**Description of the bug**

Working on a site and starting to see something strange. Adding a term reference field to a content type with the select widget, and then trying to create a node without selecting a term is giving this:

> EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tid' cannot be null in NodeStorageController->save() (line 487 of /path/core/modules/node/node.entity.inc).

and 

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tid' cannot be null: INSERT INTO {taxonomy_index} (nid, tid, sticky, created) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array ( [:db_insert_placeholder_0] => 4 [:db_insert_placeholder_1] => [:db_insert_placeholder_2] => 0 [:db_insert_placeholder_3] => 1562184910 ) in taxonomy_build_node_index() (line 2013 of /var/lib/tugboat/core/modules/taxonomy/taxonomy.module).

**Steps To Reproduce**
To reproduce the behavior:
1. Add a term reference field to a content type (not required) 
2. Create a piece content for this type (fill in required fields, but leave the term reference empty)
3. Save

**Actual behavior**
![Screen Shot 2019-07-03 at 3 23 30 PM](https://user-images.githubusercontent.com/871421/60622694-8a2f5300-9da6-11e9-9b7a-428b6bf7a3c9.jpg)

---
PR by @jackaponte: https://github.com/backdrop/backdrop/pull/2808

**Comment by ksthomas** [comment]
I am having the same issue. I am porting custom integration code over that creates fields, terms and nodes on the fly and I am getting the same error.

I will craft a fix and post to the current development branch for review.

**Comment by bradbulger** [comment]
I just set up a generic site running 1.x branch code to test something else and I'm seeing this with a Term reference field that has no default value and unlimited cardinality, using checkboxes.

**Comment by bradbulger** [comment]
A change to taxonomy_build_node_index() to skip NULL values prevents the error. You could do that when collecting tids, or when processing them. Can zero be a legitimate tid value for the taxonomy_index table? I can't think of a case offhand but maybe.

**Comment by jackaponte** [comment]
I'm experiencing the same errors as described by @laryn and others, with a few differences: Locale is not enabled, and the error happens with any term reference field widget selected, not just "Select."

**Comment by laryn** [comment]
Confirmed -- just spun up a demo and it happens without Locale being enabled, and with Checkboxes and Autocomplete as well. 😲

**Comment by bradbulger** [comment]
This is related to #3950 too - the root problem is that during node creation, the field has a value of array('tid' => NULL). The error doesn't repeat on edit.

**Comment by bradbulger** [comment]
it's getting the array('tid'=>NULL) from the default_value for the instance in field_default_insert(). i haven't traced where that default_value gets set, or why.

**Comment by ksthomas** [comment]
I have been debugging this for hours and I am not sure why it is getting set that way as well. I debugged the same scenario in D7 and the default value is array('und' => 0) so the tid test (if (!empty($items[$langcode]))) in the taxonomy_build_node_index works correctly. Not knowing why the default value is being set differently and if changing the default value could potentially break something else. My vote is to add the test for tid NULL.

**Comment by jackaponte** [comment]
This was blocking me from moving forward with my work, so taking queues from this thread I've created [a pull request](https://github.com/backdrop/backdrop/pull/2808) that includes the test for tid NULL that we've been discussing. Hopefully this really fixes things, it's fixing the problem on my site!

**Comment by klonos** [comment]
Tested this on my local vs the PR sandbox, and it works as advertised 👍 ...the change is simple and straight-forward, so RTBC. Great team work everyone 👏

**Comment by bradbulger** [comment]
So is it true that 0 would never be a legitimate value to add to the table? I believe it, I just didn't know if there was some special case floating out there. (empty vs NULL)

**Comment by quicksketch** [comment]
I don't think tid = 0 has any special meaning in the taxonomy_index table. The PR looks good to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2808 into 1.x and 1.13.x. Thanks folks!

**Comment by jackaponte** [comment]
Woohoo! Glad we got that fixed. :)

And yeah @bradbulger, as far as I know there are never any taxonomy terms with a `tid` of 0, so that would never be a legitimate value to add to the table that maps nodes to the terms with which they're tagged.
