### ISSUE TITLE
Wrong function parameter for user_save() in user.test

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#3920]
**Description of the bug**
There is a wrong function parameter for user_save() in user.test line 2238:
user_save($user1, $edit);
I created a PR with two commits.

---
PR by @VassasA: https://github.com/backdrop/backdrop/pull/2786

**Comment by quicksketch** [comment]
Thanks @VasasA and @klonos! Merged https://github.com/backdrop/backdrop/pull/2786 into 1.x and 1.13.x.
