### ISSUE TITLE
Link field: Recursion in field formatter with views

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#3934]
I run into a problem wuth a contrib module (https://github.com/backdrop-contrib/headless/issues/12) and ended up finding a drupal fix for a problem (https://www.drupal.org/project/link/issues/2295071) still in backdrop. 

Added a PR (https://github.com/backdrop/backdrop/pull/2792) to solve this.

**Comment by klonos** [comment]
Thank you @robertgarrigos for tracking this down 👍 ...RTBC!

**Comment by jenlampton** [comment]
We should check and see if this change is included in https://github.com/backdrop/backdrop-issues/issues/2076, and if so, cross-link that `#xx` to this issue.

**Comment by klonos** [comment]
Done @jenlampton 😉

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2792 into 1.x and 1.13.x. Really appreciate the work you did tracking down and cross-porting this @robertgarrigos!
