### ISSUE TITLE
constant cycle of PHP errors from theme_file_icon()

### ISSUE THREAD

**Issue by bradbulger** [backdrop/backdrop-issues#3947]
I am seeing these errors repeat every few seconds - possibly because they're caused by looking at the error log? But there are tons from before I started looking, as well, so they may be related to cron (which is producing "attempting to run cron while it's still running" errors now).

Notice: Undefined property: stdClass::$uri in theme_file_link() (line 51 of /home/www/esdresearch/esd-backdrop/www/core/modules/file/file.theme.inc).
Notice: Undefined property: stdClass::$uri in theme_file_link() (line 71 of /home/www/esdresearch/esd-backdrop/www/core/modules/file/file.theme.inc).
Notice: Undefined property: stdClass::$fid in theme_file_link() (line 75 of /home/www/esdresearch/esd-backdrop/www/core/modules/file/file.theme.inc).
Warning: array_flip(): Can only flip STRING and INTEGER values! in DefaultEntityController->load() (line 183 of /home/www/esdresearch/esd-backdrop/www/core/modules/entity/entity.controller.inc).
Notice: Trying to get property of non-object in theme_file_icon() (line 118 of /home/www/esdresearch/esd-backdrop/www/core/modules/file/file.theme.inc).
TypeError: Argument 1 passed to file_icon_url() must be an instance of File, boolean given, called in /home/www/esdresearch/esd-backdrop/www/core/modules/file/file.theme.inc on line 119 in file_icon_url() (line 870 of /home/www/esdresearch/esd-backdrop/www/core/modules/file/file.module).
Warning: Cannot modify header information - headers already sent by (output started at /home/www/esdresearch/esd-backdrop/www/core/includes/common.inc:3087) in backdrop_send_headers() (line 1613 of /home/www/esdresearch/esd-backdrop/www/core/includes/bootstrap.inc).
Warning: Cannot modify header information - headers already sent by (output started at /home/www/esdresearch/esd-backdrop/www/core/includes/common.inc:3087) in backdrop_send_headers() (line 1617 of /home/www/esdresearch/esd-backdrop/www/core/includes/bootstrap.inc).

These are all in watchdog with a Location of /admin/reports/dblog. It says the user is Anonymous but it's clearly me (it's my IP address in Hostname).

Running Backdrop 1.13.2. It says Cron last ran 1 week 1 day ago, but I am seeing those "cron is still running" errors right now.

The website is not visibly affected that I can tell, so I don't know what this is about.

**Comment by bradbulger** [comment]
And so of course as soon as I put this in, it stops. Possibly related to manually running cron, which seems to have forced its way through to completion. I've added some lines to try to trace the source if it starts happening again.

**Comment by BWPanda** [comment]
Will close this issue for now, but feel free to re-open if it happens again.
