### ISSUE TITLE
Missing "edit" link for comments

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#3948]
**Description of the bug**
We have permissions for users to edit their own comments, but even with this permission granted there is no edit button on users comments. 

This issue recently came up with forums.backdropcms.org (https://github.com/backdrop-ops/forum.backdropcms.org/issues/87). I assumed the problem was specific to that site, but it appears that this is a problem with Backdrop Core. 

In the forum it feels like a major bug that a user can edit their initial question, but no one can edit their own comments unless they have admin privileges and can manage comments.

**Steps To Reproduce**
To reproduce the behavior:
1. On fresh demo site go to: `node/1/edit` and enable comments
2. On `posts/your-first-post` make a comment
3. On permissions page `admin/config/people/permissions` ensure that all authenticated users have the ability to `Edit own comments`.
4. Try to edit your own comment. There is no edit button.

![Permissions___Tim](https://user-images.githubusercontent.com/3144571/61848042-58278300-ae72-11e9-9743-4a471b9eb4c1.png)

![Your_first_post____Tim](https://user-images.githubusercontent.com/3144571/61848077-7d1bf600-ae72-11e9-9d98-ef6751478615.png)

**Expected behavior**
I would expect to see a "delete," "edit," or "reply" button by my comments.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2798

**Comment by klonos** [comment]
Tiny PR to fix this: https://github.com/backdrop/backdrop/pull/2798

Interesting:

- https://github.com/backdrop/backdrop/blob/1.x/core/modules/comment/comment.module#L1507-L1509:

```
 * Authenticated users can edit their comments as long they have not been
 * replied to. This prevents people from changing or revising their statements
 * based on the replies to their posts.
```

- https://github.com/backdrop/backdrop/blob/1.x/core/modules/comment/comment.module#L1531-L1532:

```
  // Log to watchdog for DX. @todo add watchdog_deprecated_parameter().
    $message = 'The function comment_access() was called with the operation <em>edit</em>. This operation is now named <em>update</em>. The <em>edit</em> operation will be removed in the next major release of Backdrop.';
```

**Comment by klonos** [comment]
...should the order of the links be reply/edit/delete instead of delete/edit/reply?

**Comment by klonos** [comment]
...this is a one-liner, but I have snuck in a few related docblock fixes here and there 😉

**Comment by stpaultim** [comment]
This fixes the problem in this issue. However, I tested whether or replying to a comment removed the users ability to edit it and that did not work. Sounds like another issue for another day. :-)

I left a trail of comments in Sandbox on "My first post" to demonstrate.

**Comment by stpaultim** [comment]
I don't know which things need tests in Backdrop. But should there be a test for the availability of the edit link if a user has edit comment permissions?

**Comment by klonos** [comment]
@stpaultim your last comment in http://2798.backdrop.backdrop.qa.backdropcms.org/posts/your-first-post reads:

> I can still reply, despite the fact that admin replied to my comment.

The feature is meant to prevent you from editing your original comment if someone has replied to it. Having said that, I have not tested this myself, but as you say, this would be a separate bug.

**Comment by indigoxela** [comment]
> Wondering why this did not kick in (watchdog deprecation warning)

@klonos usually $op is "update" - this is set in hook_menu() as access arguments for path $items['comment/%comment/edit']

I'm not actually sure, whether this compability wrapper (if ($op == 'edit')) is still needed, but maybe I'm missing something.

**Comment by indigoxela** [comment]
I can confirm @stpaultim's finding that replying to a comment doesn't prevent the initial comment from getting edited. But that should be an extra issue.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2798 into 1.x and 1.13.x thanks @klonos, @stpaultim, and @indigoxela!
