### ISSUE TITLE
Checkbox to select all tests doesn't work

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3949]
The checkbox to select all tests on the `/admin/config/development/testing` page doesn't work (it neither changes its own state when clicked, nor does it change the state of any other checkbox on the page). I believe this is because the [JS is missing](https://github.com/backdrop/backdrop/blob/1.x/core/modules/simpletest/js/simpletest.js) (there's JS for the group checkboxes, but not this main one in the table header)...

---
PR by @isabelhaas: backdrop/backdrop#2816

**Comment by herbdool** [comment]
Right, I noticed this for quite a while but never bothered to create a bug report.

**Comment by herbdool** [comment]
Tested @isabelhaas' PR and it works. Thanks!

**Comment by quicksketch** [comment]
Thanks @BWPanda for making this issue! I've merged https://github.com/backdrop/backdrop/pull/2816 into 1.x and 1.13.x. Thanks again to super-reviewer @herbdool. And @isabelhaas for the fix!
