### ISSUE TITLE
[UX] Replace text suggestion to run updates in maint mode with checkbox

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#3960]
**Description of the bug**
When you do a core or module update, we present you with a checkbox to put your site into maintenance mode while doing the update. 

When you run update.php, we instead give you a not-very-helpful list of 3 steps.  I recommend that we remove step 2: `Put your site into maintenance mode.` and instead, replace it with a checkbox, like we do for updates. 

By default, this box should be checked (like it is with updates) and when the updates complete, we should notify people that their site has been taken out of maintenance mode.

If your site is already in maintenance mode, we hide the checkbox and do not take your site out of maintenance mode when the updates are done. (If you put it into maintenance mode manually, you probably want to take it out manually too - after additional testing)

Once steps 2 and 3 are removed, step 1 should be refactored so it is not a "step" anymore.

**Steps To Reproduce**
To reproduce the behavior:
1. Visit /update.php
2. read the checklist

**Actual behavior**
No checkbox here

**Expected behavior**
Checkbox here

**Additional Information**
Related: https://github.com/backdrop/backdrop-issues/issues/3959

**Comment by klonos** [comment]
@jenlampton can we please close this in favor of #512?

**Comment by klonos** [comment]
...also, I have started working on this, and it may not be such a good first issue 😅

**Comment by BWPanda** [comment]
Closing in favour of https://github.com/backdrop/backdrop-issues/issues/512 since @klonos is working on this as part of that other issue.
