### ISSUE TITLE
[UX] Revamp the text of the "Access denied" message on update.php

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3963]
This is a sibling issue to #512, but for when the update.php page is attempted to be accessed by non-logged-in users. Here's what that page currently looks like:

![Screen Shot 2019-08-04 at 8 09 56 am](https://user-images.githubusercontent.com/2423362/62422040-b6dfce80-b6b4-11e9-89aa-0116120d397d.png)

What's wrong:

- The "Access denied" bit is being repeated in the page title, and the beginning of the main text. I find that superfluous.
- Point 1 is a slight grammatical/logical mess, because you are not to find the settings.php file with a text editor; you are meant to open it with one.
- I think that there should be a "try again" or "refresh this page" step, after step 2.
- Point 4 is basically repeating the text in the main paragraph; it should be removed.
- The entire thing is actually html passed on as output within the [`update_access_denied_page()`](https://github.com/backdrop/backdrop/blob/1.x/core/update.php#L337) function, and the strings are not passed through `t()`, so not translatable.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2805

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/2805

<img width="861" alt="Screen Shot 2019-08-04 at 1 05 33 pm" src="https://user-images.githubusercontent.com/2423362/62422284-9d408600-b6b8-11e9-942e-939dcf45d5da.png">

**Comment by stpaultim** [comment]
I think that this looks good from user perspective. I've marked this `works for me.`

I might do code review on text only changes, but I'm unfamiliar with the process being used for output, so I'm not going to comment on it.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/2805 looks great! I've merged it into 1.x and 1.13.x. Thanks!
