### ISSUE TITLE
[UX] Views: Fix description text for the "Fill up single line" setting

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3965]
Empty brackets within the description text:

![Screen Shot 2019-08-05 at 10 33 43 pm](https://user-images.githubusercontent.com/2423362/62490214-7f1a7900-b7d1-11e9-902a-ba928451ed5d.png)

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2807

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/2807

<img width="596" alt="Screen Shot 2019-08-05 at 10 58 52 pm" src="https://user-images.githubusercontent.com/2423362/62491487-bdfdfe00-b7d4-11e9-82a2-debbfe2c5fae.png">

**Comment by bradbulger** [comment]
I tested the PR on my local site, works fine. Code change looks good to me.

**Comment by klonos** [comment]
Thanks @bradbulger 👍

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2807 into 1.x and 1.13.x.
