### ISSUE TITLE
Link autocomplete throws ajax error if starting with slash

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3968]
**Description of the bug**

![Screenshot from 2019-08-07 11-28-56](https://user-images.githubusercontent.com/1071483/62636064-dec67080-b906-11e9-8faf-50a62c9f94aa.png)

**Steps To Reproduce**

In the wysiwyg of a post, add a link. Start the link destination with a slash "/".

**Actual behavior**

Get an ajax error. And also this error in watchlogs:

> ArgumentCountError: Too few arguments to function _filter_link_autocomplete(), 0 passed in /app/core/includes/menu.inc on line 582 and exactly 1 expected in _filter_link_autocomplete() (line 35 of /app/core/modules/filter/filter.pages.inc).

The URL is `/index.php?q=filter-link/autocomplete/%2F`. So it's basically getting slash slash so the argument is empty. We need to intercept before it does an AJAX call.

**Expected behavior**

Should just take it in stride and remove the slash from the autocomplete.

------------------
PR: https://github.com/backdrop/backdrop/pull/2867

**Comment by BWPanda** [comment]
Related: #3676

**Comment by herbdool** [comment]
I've got a really small fix https://github.com/backdrop/backdrop/pull/2867, which is nice because I was starting to think it was going to be hard to fix.

@BWPanda want to test?

**Comment by docwilmot** [comment]
i dont get the AJAX error, but I do get the Watchdog error and this does fix that, so RTBC.

**Comment by BWPanda** [comment]
PR appears to work for me too!

**Comment by klonos** [comment]
Yup, RTBC 👍

**Comment by quicksketch** [comment]
Thanks everyone! Nice easy fix. Thank you so much for the multiple confirmations. Merged https://github.com/backdrop/backdrop/pull/2867 into 1.x and 1.13.x.
