### ISSUE TITLE
system_settings_form_submit() still saves to variables

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#397]
``` php
function system_settings_form_submit($form, &$form_state) {
  // Exclude unnecessary elements.
  form_state_values_clean($form_state);

  foreach ($form_state['values'] as $key => $value) {
    if (is_array($value) && isset($form_state['values']['array_filter'])) {
      $value = array_keys(array_filter($value));
    }
    variable_set($key, $value);
  }

  backdrop_set_message(t('The configuration options have been saved.'));
}
```

Should this be changed to `config_set()` instead, or are variables still used/available in Backdrop?

**Comment by sentaidigital** [comment]
I know I'd miss it.  It's not so much that we'll have to write a submit handler, it's that we'll be constantly writing the _same_ commit handler over and over.  

The common form is a single `mymodule.settings` bucket, and I think `system_settings_form()` should support that.  I also like the more complicated `$form['my_setting']['#config'] = 'mymodule.special';` to handle the uncommon case.

I suggest taking it a step further and let the `#config` setting propagate down to sub-elements, so if you set:

```php
<?php
$form['grouping'] = array(
    '#type' => 'fieldset',
    '#config' => 'mymodule.special',
);
```

... any settings fields in the `grouping` fieldset would also be saved to `mymodule.special.`  I think the common case for multiple config buckets will be (should be!) to group them together by bucket on the form itself, anyway, so allowing a form to set the config bucket on a fieldset keeps the form DRY.

Now that I think about it, adding `$form['#config'] = 'mymodule.settings';` could cover the entire form in the most common case, and would be a degenerate case of adding it to a fieldset.  Then, `system_config_form()` doesn't even need a new parameter, just more smarts.
