### ISSUE TITLE
[UX] Basis: Hamburger menu broken in RTL

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3970]
LTR:

<img width="473" alt="Screen Shot 2019-08-07 at 11 37 04 pm" src="https://user-images.githubusercontent.com/2423362/62656714-824a6c00-b96d-11e9-9537-948039d2c874.png">

RTL:

<img width="480" alt="Screen Shot 2019-08-08 at 12 10 15 am" src="https://user-images.githubusercontent.com/2423362/62658207-ef133580-b970-11e9-965d-2454bc82b7c6.png">

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2810

**Comment by klonos** [comment]
Pinging @shabibalm 😉

**Comment by VasasA** [comment]
I tested the PR in my local test environment and in the sandbox https://github.com/backdrop/backdrop/pull/2810 with Chrome 75.0.3770.142 and Firefox 68.0.1, works fine.

**Comment by klonos** [comment]
Thanks @VasasA 👍

**Comment by shabibalm** [comment]
work fine thanks @klonos :tada:

**Comment by klonos** [comment]
Thank you @shabibalm ...you might also wanna have a look at #3804 😉

Unfortunately, we missed the opportunity to get these fixes in the 1.13.3 release, but I'm confident we'll get them in the next one.

**Comment by quicksketch** [comment]
Thanks folks! Merged into 1.x and 1.13.x. https://github.com/backdrop/backdrop/pull/2810
