### ISSUE TITLE
user_has_role doesn't work, should be different from D7 version

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#3971]
**Description of the bug**
The function was added in https://github.com/backdrop/backdrop/commit/6ddeb046f89fe106eb8f0af3c0b429ccd7c5ba9b and is same as the D7 patch https://www.drupal.org/node/2394517.

It doesn't work since `$account->roles` in Backdrop is stored in a non-associated array but the function seems to assume the keys are the machine_names. The parameter `$rid` is a clue that it might not have been ported properly (I suspect). It should be `$role`.

----
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2811

**Comment by herbdool** [comment]
I created a PR. The best way to test it is with a custom module that calls the function, nothing fancy. It's not being used in core so shouldn't impact tests at all.

**Comment by klonos** [comment]
@herbdool I believe that `rid`s need to be changed to role names: https://api.backdropcms.org/change-records/converted-user-roles-cmi

> - Role IDs no longer exist, they are replaced by new role (machine) names.
> - The rid column in the users_roles table is now a varchar role column.
> - Old role "names" are now "labels".

**Comment by herbdool** [comment]
Ready for testing.

**Comment by klonos** [comment]
Tested on my local, and it seems to be working as expected. The code looks good too, so RTBC 👍

**Comment by quicksketch** [comment]
Merged into 1.x per the `@since` line this will be in 1.14.0.
