### ISSUE TITLE
Use localized date input format in node form for "Authored on" and "Publish on"

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#3976]
**Description of the need**
Currently Backdrop provides a popup calendar for "Authored on" and "Publish on" node form fields (if date module is enabled), but the date format pattern used in the form is hardcoded to 'Y-m-d g:i a'.

**Proposed solution**
There are many different date formats out there. It's more user friendly to take regional date formats into account when setting dates in node forms. Ideally date formats for node forms are configurable (can get localized) via user interface.

The idea came up with issue #3972 but is unrelated. It seems, I'm not the only one who thinks, this is an enhancement.

To my knowledge there's no contrib module handling this (note: input, NOT display).

**Comment by indigoxela** [comment]
I've created an _experimental_ branch to show a possible solution (not ready for production, needs to do a lot more checks to prevent possible problems).

https://github.com/indigoxela/backdrop/tree/localized-nodedate

How it works:

- Only does something, if core date module is enabled.
- Date format needs to get localized (admin/config/regional/date-time/formats/short/localize)
- For simplicity I use the "short" date format to get the date pattern for current language.

**Comment by klonos** [comment]
Thanks @indigoxela 👍 ...can you please make a PR against core from your branch? It would be easier to see changes and provide feedback. As you push changes to your branch, the PR will be automatically updated to reflect those 😉

**Comment by indigoxela** [comment]
> can you please make a PR against core from your branch

I did so now.

Some things to consider:

It might not be smart to re-use the short date format, because that's actually meant to be used for display and it could be ambiguous.
Think of patterns like "y/m/d". This needs more investigation and testing.

**Comment by indigoxela** [comment]
Closed in favor of https://github.com/backdrop/backdrop-issues/issues/3972 (date/time html5 input in core).
