### ISSUE TITLE
E-Mail Fields not available as target in Feeds

### ISSUE THREAD

**Issue by bobchristenson** [backdrop/backdrop-issues#3980]
I created a new content type which is the target of my feeds import.  The content type has a field of the 'email' type.  When I go into feeds to setup my importer (CSV format), the e-mail field I created in my content type isn't available.  All other text-based (simpler) fields are available.

**Comment by klonos** [comment]
Hey @bobchristenson 👋 ...this seems to be a problem with the Feeds module, and it has already been reported here: https://github.com/backdrop-contrib/feeds/issues/18

I will go ahead and close this one, but please feel free to reopen if you find that there is something in core that is blocking the fix.

**Comment by bobchristenson** [comment]
Thanks!
