### ISSUE TITLE
Add change record for the missing `image_style_path_token()`

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#3989]
Uh, what happened to [`image_style_path_token`](https://api.drupal.org/api/drupal/modules%21image%21image.module/function/image_style_path_token/7.x)? 'Twas in D7, but no references to it in Backdrop core, API, change records, etc...

A contrib module calls it, and I'd like to know what I need to replace it with.

---
PR by @klonos (adds wrapper function to log a watchdog message - links to change record): https://github.com/backdrop/backdrop/pull/2829

**Comment by klonos** [comment]
According to https://api.drupal.org/api/drupal/modules%21image%21image.module/function/image_style_path_token/7.x this function was called in 2 places:

- image_style_deliver()
- image_style_url()

Portions of these function differ considerably from the respective ones in D7 🤔 ...looking at git blame/history next to see if I can figure out what has happened along the way.

**Comment by klonos** [comment]
...I have traced the problem to be this missing commit: https://git.drupalcode.org/project/drupal/commit/3a24da1b40f5e05876ad7775044500b61eb2ed94 ...which was a security fix in D7 ...we seem to have decided to not implement the same fix that introduced the `function image_style_path_token()` function. The respective issue with the discussion about it is this: #34 (2-digit one 😮 🙂)

**Comment by klonos** [comment]
Thanks for digging this up @BWPanda 👍 

It seems that we need:

- A change record (to explain why we have implemented a different fix in Backdrop + tell contrib maintainers what to do when porting modules that use this function).

- A wrapper function around `image_style_path_token()` to log a watchdog "deprecated" message, and point people to the change record.

**Comment by klonos** [comment]
...hey @BWPanda, FTR, which contrib have you been trying to port that has lead you to this?

FYI, there's a list of modules that broke after the D7.20 release here: https://www.drupal.org/project/drupal/releases/7.20

Was it one of those modules?

**Comment by klonos** [comment]
...never mind; I see now 😅 

I believe that it is safe to remove that entire conditional in https://github.com/BWPanda/insert/blob/1.x-1.x/includes/image.inc#L64 😉

**Comment by BWPanda** [comment]
@klonos Yep, Insert is the module I'm playing with and I noticed a call to the function in one of the template files.

**Comment by klonos** [comment]
Draft change record here: https://api.backdropcms.org/change-records/imagestylepathtoken-does-not-exist-backdrop

...working on a placeholder function next.

**Comment by klonos** [comment]
PR to add placeholder/deprecated function: https://github.com/backdrop/backdrop/pull/2829

**Comment by BWPanda** [comment]
PR looks good to me.

**Comment by klonos** [comment]
...thanks @quicksketch ...I have merged your code suggestion to update the change record URL to the one with the underscores.

I don't have permission to edit content types in api.b.org, but the values of the "related GitHub Issues" field need to be linkified on display:

<img width="792" alt="Screen Shot 2019-08-27 at 3 15 21 am" src="https://user-images.githubusercontent.com/2423362/63731635-365a5b00-c879-11e9-98cf-bb6515210f80.png">

**Comment by quicksketch** [comment]
Thanks @klonos, that addition looks excellent and the 3 separate links to information as to why it doesn't exist are very helpful.

Merged into 1.x and 1.13.x. Thanks @BWPanda for filing this issue!
