### ISSUE TITLE
[UX] Remove "new" from any "Add new X" menu items

### ISSUE THREAD

**Issue by dgoutam** [backdrop/backdrop-issues#399]
![backdrop-ux-menu-naming-inconsistency](https://cloud.githubusercontent.com/assets/827654/4773362/9d8879b4-5ba1-11e4-8f34-09a3bac1bccd.png)

**Comment by klonos** [comment]
Also, I think that "create" is more fitting than "add" (with the exception of "Add file" or "Add field" or "Add block"). "Add" implies adding something already existing, while what is actually done is creating something...

Create content
Add file (not implemented yet)
Create user account
Create content type
Create block
Create layout
Create menu
Add link (to parent menu that is already created)
Create vocabulary
Add term(s) (to parent vocabulary that is already created)
Create view
Add text format (not sure about this one)
Create image style (even the button in that form is "**Create** new style")
Add date format
Add alias

**Comment by BWPanda** [comment]
PR removes 'new' from Layout, View, Module & Theme links.

**Comment by BWPanda** [comment]
Have updated PR to try and fix tests.

**Comment by quicksketch** [comment]
Thanks @BWPanda! It'll be in 1.0.1 now. :)
