### ISSUE TITLE
[UX][WP] Dashboard block: Welcome to Backdrop CMS

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#3994]
After the rebirth of the Dashboard in #495, we no longer show "Welcome to Backdrop ...This is your first post! You may edit or delete it." We should add a block that does something equivalent.

Here's what WP does:

![Screen Shot 2019-08-26 at 12 04 38 am](https://user-images.githubusercontent.com/2423362/63655775-223d2d80-c795-11e9-9e64-b9ad6a00ff40.png)

Things to decide upon:

1. Should our welcome block also run across the entire width of the page?

2. Should this be a dismissible block? We currently don't have those (#1725 anyone?) ...well, not as easy as clicking a "dismiss" button that is: the user can configure the block, which takes them to another page ("Manage blocks") -> but the block configuration dialog only has an "Update block" button 👎 - no "Remove block" button 😞 ...so they have to close that dialog -> locate the block -> click the dropbutton -> select "remove" -> figure out that they need to scroll down the page (#2430 anyone?) -> save ...that's way too many actions; so, really bad UX.

3. What links/text/things should we include in this block. Starting with what WP has, and comparing that with what thingies of ours we could place there:
    - **"Get Started" section**:
      - The big "Customize" button would take you to the settings page of the current theme (`/admin/appearance/settings/basis`).
      - The "change your theme completely" would be the Project Browser for themes (`/admin/appearance/install`).
    - **"Next steps" section**:
      - "Write your first article" link: `/node/add/post`
      - "Add an About page": link `/node/2/edit` (should really be `/about/edit` - #1418)
      - "Set up your homepage" link: `/admin/structure/layouts/manage/home` and/or `/admin/config/system/site-information`
      - "View your site" link: `<front>`
    - **"More Actions" section**:
      - "Manage widgets or menus" could be "Manage menus and taxonomy"
      - "Turn comments on or off" could be a custom link, with confirmation, to completely disable the Comment module.
      - "Learn more about getting started": link to docs on b.org

Other things we could add:
- Link to site status report: `/admin/reports/status`
- Link to dedicated security settings page: #3624 
- Link to dedicated accessibility settings page: #3991

---

follow-ups 
* #3996 Dashboard: Dismissible blocks
* #3995 Dashboard: Collapsible blocks
* #4009 Ensure there's proper access/visibility checks for all blocks
* #4010 Make sure things look decent for users with lesser permissions

---
~PR by @klonos: https://github.com/backdrop/backdrop/pull/2831~
Updated PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2836

**Comment by klonos** [comment]
Well, I made some decisions to start with 😅 ...here's an initial PR to get things rolling: https://github.com/backdrop/backdrop/pull/2831

<img width="1186" alt="Screen Shot 2019-08-26 at 3 58 55 am" src="https://user-images.githubusercontent.com/2423362/63658765-e070af00-c7b5-11e9-9ab6-d1289076875b.png">

Things that need work/decision:

- what links to add/change/remove
- should we add icons to the links
- add permission/access checks for links that need it
- make the 3 columns responsive (I may need some help with that - looking at you @jenlampton 😉)
- other styling? ...should this block be different from the others, and if so, how?

Moar feedbackz welcomed.

**Comment by docwilmot** [comment]
I like this. Very cool.

**Comment by klonos** [comment]
...I have implemented this as a "locked" block. In other words, it has no settings (other than block title that is). I think that the content it shows should be controlled "internally". Let me know if you think otherwise.

**Comment by stpaultim** [comment]
I love it!

How about adding a link for "Customize your dashboard" = admin/structure/layouts/manage/dashboard/blocks

This provides the user an obvious way to disable this block once they decide they don't need it anymore. 

But, it occurs to me that there might be an issue with this block and my PR for an editor role. I've given the editor role access to the dashboard, but at this time they do not have access to all the features linked to here. 

We need to either:

1) Simply make this block only available to people with role`adminstrator.`
2) Create a custom block for editor. (Maybe that's a next step)
3) Make sure that each link is only visible if the user has permission to do that item, so if the admin changes roles a specific user does not see a link that takes them to a page that they do not have access to. (NOTE: You might have addressed this already as I have yet to test that workflow).

**Comment by stpaultim** [comment]
I tested and there is no testing for permissions on links. I created a editor role with limited permissions. They can access the dashboard and this block, but most of the links take them to access denied messages. So, maybe this block is only visible to admin, which is really the intended audience, isn't it. 

We could think about a more contextually appropriate block in the future (or experiment with it in [Dashboard Plus](https://backdropcms.org/project/dashboard_plus)).

**Comment by klonos** [comment]
> ...This provides the user an obvious way to disable this block once they decide they don't need it anymore.

Yup, can surely do that ...but TBH, I would like us to eventually implement #1725, so that we can expose "remove"/"dismiss" links for blocks.

> Make sure that each link is only visible if the user has permission to do that item, so if the admin changes roles a specific user does not see a link that takes them to a page that they do not have access to. (NOTE: You might have addressed this already as I have yet to test that workflow).

See how in my previous comment I say "add permission/access checks for links that need it"? ...may not seem like it, but that's what I meant ...sorry, I had a lazy moment where I did not want to type many words 😅 ...I won't let that happen again  😆

**Comment by klonos** [comment]
...i should also have mentioned that the intention of these 3 columns is to include tasks that are gradually more advanced as you move from left to right. I hope that I have done a good job, but please let me know if tasks need to switch to another column.

...and as I was typing that, I thought that it would be great if there was an easy way to have the order of these columns change on RTL languages (so that the notion of easy-to-advanced is still retained visually).

**Comment by stpaultim** [comment]
I didn't read all your notes, just got excited and started playing....

> should we add icons to the links

I vote no on this. I think it's too much work for too little value. Also means that each new link needs an icon. Let's not set that expectation, it doesn't need icons. I do like the main one. 

How hard is it to create a block that a user can `dismiss` rather than `delete.` I think the concerns around #1725 have to do with how destructive it is. But, simply saying I don't want to see this block anymore seems much less destructive. 

Or at a minimum, make this block into an accordion that can be opened or closed to save real estate (possible followup issue).

**Comment by olafgrabienski** [comment]
Nice! ... and here some questions:

> Edit the About page

Can we show this item only if the page exists?

> Write your first article

Hm, at least at first visit, there is already a "First post".

**Comment by klonos** [comment]
>>Edit the About page
>
>Can we show this item only if the page exists?

We sure can. This will be part of my second pass, where I add logic and access permissions to the rendered links.

>> Write your first article
>
>Hm, at least at first visit, there is already a "First post".

Hmm indeed. Good point.

Please keep the good feedback and suggestions coming guys 😉

**Comment by klonos** [comment]
Thanks for the feedback @laryn 👍 

> Something highlighting/linking to the Project Browser/Installer for modules would be good

There already is a "Add more functionality" link in the "More actions" section 😉 

> Presumably they've just entered the Site Information when installing so maybe we can remove the "Update your site information" link?

Indeed. Or... we could remove the entire "Site information" section from the "Configure site" step of the installer (by setting the site name to a default, like "My Backdrop site"), in order to achieve #467 😉

**Comment by klonos** [comment]
Updating this to be a feature request, and adding the 1.14 milestone, as per discussion during the dev meeting earlier today.

**Comment by quicksketch** [comment]
I made a new PR at https://github.com/backdrop/backdrop/pull/2836 that keeps all the current links, but adds access checks to all paths so only applicable links show up.

**Comment by klonos** [comment]
Thanks @quicksketch 👍 ...it works fine when viewed by an admin account, but certain issues start coming up when accessing the Dashboard as a user with less permissions...

I created a new user, and give it just the "authenticated" role. I then logged in, and (as expected), I saw nothing 👍 ...moving on, I gave the "authenticated" user role the "Access Dashboard" permission, and also the "Access administration bar" permission -> refreshed the page -> clicked the "Dashboard" link in the admin bar -> realised that the Dashboard was not built with other themes in mind, except Seven 😅:

![2019-09-02-00-25-2836 backdrop backdrop qa backdropcms org](https://user-images.githubusercontent.com/2423362/64082529-334be880-cd19-11e9-96df-c12b6b791c82.png)

...perhaps we need to make the "Access Dashboard" permission work the same way as the "Access administration bar" permission, where a pop-up suggests that we also provide the "Use the administration pages" + the "View the administration theme" permissions (I believe that @stpaultim has mentioned something similar during his work in additional blocks for the Dashboard)? But that is definitely a separate issue - just mentioning it here so it doesn't get lost in time.

Anyway, I then granted the "Use the administration pages" permission -> refresh ->

![Screen Shot 2019-09-02 at 12 39 30 am](https://user-images.githubusercontent.com/2423362/64082602-28458800-cd1a-11e9-8fc7-9d2b3cc0396e.png)

...so, we need permission checks for the other Dashboard blocks too (also separate issue), and we need to account for when the current user has enough access only to see external links. In that case, we should not render the "More actions" `<h4>` at all. In general, we should not be rendering the `<h4>`s if there is only one links section (the "Here are some links to get you started" text suffices in those cases I believe).

For some reason `<front>` does not pass the access checks, so the "View your site" link is never rendered - not even for user1.

...also left a code suggestion in the PR re the "Write your first article" link 😉 

Same as with #1285, I think that functionality-wise this is OK to go in; we can bikeshed re which links to add/change/remove over the next couple of weeks, before the final release of 1.14.0.

**Comment by quicksketch** [comment]
> For some reason <front> does not pass the access checks, so the "View your site" link is never rendered - not even for user1.

Fixed this. However that means for a user with no permissions will be able to see two columns now: 
![image](https://user-images.githubusercontent.com/100206/64083281-09230800-ccd2-11e9-8302-d6793de20d56.png)

> ...also left a code suggestion in the PR re the "Write your first article" link wink

Thanks, this is much better being "Create a new post".

**Comment by quicksketch** [comment]
Yay, thanks @klonos! Merged in https://github.com/backdrop/backdrop/pull/2836 into 1.x for 1.14.0. This was a nice easy one. Thanks everyone for your excellent feedback! We can continue in the follow-ups we have for https://github.com/backdrop/backdrop-issues/issues/3996 and https://github.com/backdrop/backdrop-issues/issues/3995

**Comment by klonos** [comment]
> We can continue in the follow-ups we have for #3996 and #3995

...and also #4009 and #4010 😉
