### ISSUE TITLE
[UX] File Type configuration form changes

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4014]
From https://github.com/backdrop/backdrop-issues/issues/2632#issuecomment-527664811:
> I do this all the time, I think that's bad advice. We should remove that text... where did you find it?

@jenlampton It comes from the description text on the 'Media types' field at `/admin/structure/file-types/manage/[TYPE]`: "You should not use the same media types in more than one file type."

![image](https://user-images.githubusercontent.com/2385329/64228729-54b2fd00-cef0-11e9-8f7b-5a963a2a5836.png)

**Comment by klonos** [comment]
...one of the unticked checkboxes with tasks left to be done as follow-ups in #2632 is `File type config form: Mimetypes should be a checklist or something helpfully clickable like tokens.`

I found the "Available media types" fieldset to be the most annoying thing while testing the PR ...we need to fix this in combination with the "Media types" text field. I would like this to ideally become a series of checkboxes, and once one of the mime types has been selected for another file type, it should not be listed as an option.

**Comment by klonos** [comment]
...that list is outdated by the way: http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by klonos** [comment]
I think that the best UI for this long-term would be a nested checkbox tree, with expandable/collapsible sections. Something like one of these modules:

- https://www.drupal.org/project/taxonomy_tree_select

    ![image](https://user-images.githubusercontent.com/2423362/64294403-68557680-cf77-11e9-8a39-f7f3f27a7bf9.png)

- https://www.drupal.org/project/term_reference_tree

    ![image](https://user-images.githubusercontent.com/2423362/64294487-9d61c900-cf77-11e9-9c02-4d68d578cc9b.png)

- https://www.drupal.org/project/entity_reference_tree

    ![image](https://user-images.githubusercontent.com/2423362/64294520-b36f8980-cf77-11e9-9104-37c10b50dfe9.png)

- https://www.drupal.org/project/jquery_jstree

    ![image](https://user-images.githubusercontent.com/2423362/64294559-d0a45800-cf77-11e9-87d5-ffee679bf80e.png)

There's this jQuery plugin we could use to build our own thing: https://www.jstree.com/

<img width="322" alt="Screen Shot 2019-09-05 at 12 56 32 am" src="https://user-images.githubusercontent.com/2423362/64294652-09dcc800-cf78-11e9-8b4f-e81ec4d2799a.png">

**Comment by BWPanda** [comment]
I think @klonos' suggestions should be a separate issue (if not already). I'm re-purposing this issue to not only fix the wording as described above, but also a few other things on this form I've noticed...

- Media Types description incorrect (as above)
- Typo in Media Types description (mentioned in https://github.com/backdrop/backdrop-issues/issues/2632 but not fixed)
- Name field too long, machine name wraps to 2nd line

The Name field length is currently set to the default of 60 (see https://docs.backdropcms.org/form_api#textfield) but other fields with a machine name at the end (e.g. Content Type name) have a size of 30. So let's do that here too.

For the record, here's what happens when you have multiple file types with the same media type:
![image](https://user-images.githubusercontent.com/2385329/151723181-311ea13c-03f3-4a08-8886-e13f2bab53c2.png)
Have updated the description accordingly. It now says: "If multiple file types have the same media type, you'll be prompted to select one manually."

Here's a PR that addresses all this: https://github.com/backdrop/backdrop/pull/3931

**Comment by BWPanda** [comment]
I also added a note to the description about the ability to use wildcards (e.g. `image/*`) (this was also mentioned in https://github.com/backdrop/backdrop-issues/issues/2632).

**Comment by klonos** [comment]
> I think @klonos' suggestions should be a separate issue (if not already).

Yup, will get to that if there's not an existing issue already.

> Have updated the description accordingly...

Thanks @BWPanda 🙏🏼  ...while fixing things in the text...

- Can we simplify/shorten this:
  > This is the list of media types (MIME types) which will be associated with this file type.

  ...to something like this:
  > The media (MIME) types to be associated with this file type.

- There is too much duplication/repetition of the same or similar words here, and the word "one" may be interpreted as either "media type" or "file type":
  > When files with these media types are uploaded, Backdrop will identify the file type based on its media type. If multiple file types have the same media type, you'll be prompted to select one manually.

  How about this instead?:

  > When files are uploaded, Backdrop will attempt to automatically identify the file type based on its media type. If the same media type is associated with multiple file types, you will be prompted to select a file type manually.

This is a lengthy help text, and usually things are easier to read/parse/notice if different things are added as separate bullet points. Otherwise people will either miss them, or ignore the help text completely.

Compre this:

> This is the list of media types (MIME types) which will be associated with this file type. When files with these media types are uploaded, Backdrop will identify the file type based on its media type. If multiple file types have the same media type, you'll be prompted to select one manually. Enter one media type per line. Asterisks can be used as wildcards, e.g. 'image/*'.
[More information about media types](https://en.wikipedia.org/wiki/Media_type).

To this:

> The media (MIME) types to be associated with this file type. When files are uploaded, Backdrop will attempt to automatically identify the file type based on its media type. If the same media type is associated with multiple file types, you will be prompted to select a file type manually.
> - Enter one media type per line.
> - Asterisks can be used as wildcards, e.g. 'image/*'
> - [More information about media types](https://en.wikipedia.org/wiki/Media_type)

**Comment by BWPanda** [comment]
Thanks @klonos. PR updated based on your suggestions (but with a bit of my own re-wording too):

![image](https://user-images.githubusercontent.com/2385329/151910308-0b6be27c-d863-4c93-aae4-dd4e12df475a.png)

**Comment by indigoxela** [comment]
Nice, this works for me. Thanks for removing that misleading sentence.

**Comment by jenlampton** [comment]
This is a significant improvement, and the code change is straightforward. RTBC from me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3931 into 1.x and 1.23.x. Thanks @BWPanda, @klonos, @indigoxela, and @jenlampton!
