### ISSUE TITLE
Assigning Flexible Layout template to existing layout removes all blocks in 1.14-preview

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4019]
**Description of the bug**
After creating a flexible layout template and then assigning it to an existing layout, all blocks go missing.

**Steps To Reproduce**
To reproduce the behavior:
1. Create a new flexible layout template.
2. Configure an existing layout (e.g. Home)
3. All blocks are missing, with a warning saying they've been moved (but to no region specified_.

**Actual behavior**
_After saving the configuration on the layout:_
![Screen Shot 2019-09-06 at 10 28 51 AM](https://user-images.githubusercontent.com/871421/64440378-78fa0f80-d091-11e9-8df7-8c3af83aa41f.jpg)

_After trying to manually add back the blocks:_
![Screen Shot 2019-09-06 at 10 38 34 AM](https://user-images.githubusercontent.com/871421/64440977-97143f80-d092-11e9-9bc0-af8528c264d3.jpg)

If I save the Layout and then add back the blocks manually it allows me to save again.

**Expected behavior**
At a minimum, the blocks should all exist somewhere on the layout so they can be repositioned in the new layout template.

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS 1.14-preview

--

~~PR by @laryn: https://github.com/backdrop/backdrop/pull/2861~~
Alternate PR by @laryn: https://github.com/backdrop/backdrop/pull/2865

**Comment by laryn** [comment]
Related to: https://github.com/backdrop/backdrop-issues/issues/3762

**Comment by laryn** [comment]
Maybe Flexible Layout templates need a "refuge_region" set by default?

**Comment by herbdool** [comment]
The refuge region is supposed to be the default region if the template defines one. If it isn't defined it picks the last region in the array. So either way there should be something. Looks like we need a default but also figure out why it can't find regions in the new template.

**Comment by klonos** [comment]
What @herbdool said ^^. This was fixed for the "classic" layout templates, so there must be something wrong with the logic that does not account for how flexible templates are set up.

**Comment by herbdool** [comment]
No it's more than that. Why can't it find any regions at all? That's bigger than just the fix I did.

**Comment by laryn** [comment]
Added a PR that seems to work.

**Comment by stpaultim** [comment]
I tested it a couple of times in the sandbox and it works for me.

**Comment by herbdool** [comment]
So looks like your fix works, though why doesn't it work without it? I think it would be better to see if it can be fixed a bit earlier in the file.

**Comment by laryn** [comment]
@herbdool Essentially the issue (as I saw it) was that `$new_positions` never gets set for flexible templates because there are no direct matches between regions on the old layout template and the flexible layout template.

At the end the part that assigns orphans to the refuge references `$new_positions` for placement, but since it's empty it doesn't work.

https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/includes/layout.class.inc#L713-L721

I just checked if it was empty before that orphan assignment section, and if so, populated it with regions from the new template. I guess instead of defining `$new_positions` as an empty array near the top:

https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/includes/layout.class.inc#L678

We could just define it as an array of all the positions in the new layout?

**Comment by herbdool** [comment]
The logic is all a bit confusing. I considered perhaps putting the defining the `$new_positions` at the beginning but then I think it might mess with the orphaned blocks. It looks like there was an overlooked situation where a "default region" is not defined *and* no regions match. This fix is probably still important though I think we should also have a default region always defined in flexible templates.

**Comment by laryn** [comment]
@herbdool That's a good idea. But yes, it is technically possible that someone deletes the row that has the default region on a flexible template. I suppose adding a default region on a flexible template also means having to check it before using it to make sure it still exists?

**Comment by laryn** [comment]
I just made an alternate PR that tries to clean things up a bit -- does this look reasonable?
https://github.com/backdrop/backdrop/pull/2865

**Comment by herbdool** [comment]
@laryn yes, that second PR is more like what I was thinking. I've reviewed and tested it.

**Comment by klonos** [comment]
@laryn minor nits re coding standards in the inline comments. I have left code suggestions in the PR 😉

**Comment by quicksketch** [comment]
Thanks folks! I only merged this into 1.x for 1.14.0. I can't see any reason why it couldn't be pulled into 1.13.x but as 1.13.x isn't affected by the problem I thought it best to minimize change on that branch.
