### ISSUE TITLE
Trying to get property 'langcode' of non-object in locale_language_url_rewrite_url()

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4021]
**Description of the bug**
While this is related to https://github.com/backdrop/backdrop-issues/issues/3751, this is not the same error. This time it's in core/includes/locale.inc.

**Steps To Reproduce**
To reproduce the behavior:
1. Enable Language and Locale modules (enable another language)
2. Now go to any existing node in your Backdrop and open node/XX/edit
3. Change the alias or add a redirect manually
4. Open node/XX/edit again

**Actual behavior**
Notice: Trying to get property 'langcode' of non-object in locale_language_url_rewrite_url() (line 434 of ....core/includes/locale.inc).

I see this notice on every 'node/XX/edit' with a redirect. Once for every redirect it has. If a node has no redirect, no notice shows up.

**Expected behavior**
No PHP notice.

**Additional information**
- Backdrop CMS version: 1.14.0-preview (and current dev)
- Web server and its version: Apache, PHP 7.0 or 7.2

<hr />
PR: https://github.com/backdrop/backdrop/pull/2856

**Comment by olafgrabienski** [comment]
> Backdrop CMS version: 1.14.0-preview (and current dev)

Do you think the issue has been introduced recently, or is it rather an older one?

**Comment by indigoxela** [comment]
> Do you think the issue has been introduced recently, or is it rather an older one?

I think it's an older one. I stumbled upon it while playing with the pre-release (for which I turned on error display). But I see this notice in dblogs on older installs, too.

**Comment by olafgrabienski** [comment]
Thanks for your feedback! I've had a look at the PR in the sandbox site and on one of my test sites. On both sites, the *Trying to get property 'langcode' of non-object* notice isn't displayed anymore.

However, I saw the following PHP warning under certain conditions:

`Illegal offset type in isset or empty in locale_language_url_rewrite_url() (line 434 of /(...)/core/includes/locale.inc).`

Steps to reproduce, if I recall correctly:

- Enable *Language* and *Locale* modules.
- Enable another language.
- Enable *Multilingual support* on your content type.
- Go to a node of that type and open `node/XX/edit`.
- Change the alias or add a redirect manually.
- Enable a language on the node.
- Disable the language again.
- Disable *Multilingual support* on the content type.
- Open `node/XX/edit` again.

**Comment by indigoxela** [comment]
> Illegal offset type in isset or empty

Good catch!
I can reproduce it. If a language _is_ set in nodes, $options['language'] is an object, hence not appropriate as array offset.

I've updated my pull request to take that into account. But I suspect, there's still a problem.

**Comment by indigoxela** [comment]
This `$options['language']` thing is a bit like quicksand... It's either completely missing, can be set to FALSE, can be an object.

But I think, I catch them all now - for language neutral content and content with a language set.
PR has been updated, but might need a closer look regarding the base logic.

**Comment by olafgrabienski** [comment]
Thanks for the updated PR! I've had a look at it in the sandbox site and wasn't able to reproduce the warning mentioned in https://github.com/backdrop/backdrop-issues/issues/4021#issuecomment-529895258, great!

**Comment by herbdool** [comment]
I looked at the code and I think it's good. A bit complicated I see.

**Comment by klonos** [comment]
If this bit of code is confusing/complicated, then perhaps add some inline comments (or improve the existing ones), to explain the whats and whys.

**Comment by indigoxela** [comment]
Maybe it's better to simplify/straighten the code now, so the next person touching it won't spend so much time scratching the head. ;)

Actually I see potential for improvement, for instance starting with `!is_object()` right away, then "else", then sorting out disabled languages,...

This all could be more readable. If there's a consensus, that simplifying is welcome, I'd do that of course.

**Comment by herbdool** [comment]
I took inspiration from https://carlalexander.ca/mastering-php-conditionals/ on how to use guard clauses to reduce complexity.

**Comment by olafgrabienski** [comment]
I've had another look at the sandbox site of the PR and repeated the *Steps to reproduce* mentioned in the issue description as well as the ones mentioned in https://github.com/backdrop/backdrop-issues/issues/4021#issuecomment-529895258. There weren't any PHP notices or warnings in the DBlog.

**Comment by indigoxela** [comment]
Anyone willing to review the latest changes in my PR?

**Comment by herbdool** [comment]
I'll try to review it next week.

**Comment by indigoxela** [comment]
Weekend is coming - anyone willing to review my PR?

**Comment by klonos** [comment]
Code looks good from a first look, but I would like someone with a better knowledge/understanding of this to also have a look.

**Comment by klonos** [comment]
...adding the issue to the "Bugs" project, and initially triaging it as medium priority. Can be raised to high - especially if RTBC 😉

**Comment by quicksketch** [comment]
I posted a comment on the PR, I'm not sure if the current implementation is safe from accidental side-effects: https://github.com/backdrop/backdrop/pull/2856/files#r331812275

**Comment by indigoxela** [comment]
@quicksketch many thanks for having a look. I've updated my PR.

**Comment by jenlampton** [comment]
I've reviewed the code in the PR. I like the new approach where we remove `array_flip()` and instead search the languages using `in_array()`. It seems simpler than the previous approach. 

I also noted the new value of `NULL` for `$options['language']`, thanks for fixing that @indigoxela !

**Comment by quicksketch** [comment]
Thanks @jenlampton for reviewing! And @indigoxela thanks for trying a new approach in your PR. The code reads better, avoids the problem you found and seems more robust. Merged https://github.com/backdrop/backdrop/pull/2856 into 1.x and 1.14.x.
