### ISSUE TITLE
Need to add flexible layout config to hook_config_info

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4023]
We should be able to export and import flexible layout configurations. So it should be in `layout_config_info()`.

---
PR by @herbdool: https://github.com/backdrop/backdrop/pull/2862

**Comment by stpaultim** [comment]
In the sandbox, I created a flexible layout called Minnesota. I exported this flexible layout using the single export feature. I then edited the name of the layout and called it Florida and imported it back into the same Backdrop site. 

I'm not 100% sure I'm testing the right thing or if this is a sufficiently rigorous test. I would import it into my local site, but I suspect that it will not work without the PR.

**Comment by klonos** [comment]
The PR looks and works fine @herbdool, thanks 👍

Care to expand it so that there is an "Export" operation for the dropbuttons of flexible layouts in `/admin/structure/layouts/settings`?

**Comment by herbdool** [comment]
@klonos sounds useful. If it looks like it isn't quick then I'll make a follow-up issue.

**Comment by herbdool** [comment]
@stpaultim @klonos I've added the Export button so that can be tested too. The code change is fairly basic so should be easy to do a code review as well.

**Comment by klonos** [comment]
RTBC 👍

**Comment by quicksketch** [comment]
Thanks @herbdool and @klonos! Merged https://github.com/backdrop/backdrop/pull/2862 into 1.x for 1.14.0.
