### ISSUE TITLE
The specified file public://file.ext could not be moved because the destination is invalid.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4028]
I tried changing the author of a file, and got this error upon saving it:

>The specified file public://test.png could not be moved because the destination is invalid. More information is available in the system log.

Not sure if it is a regression in 1.14, or existing issue. Can someone please test and confirm?

**Comment by klonos** [comment]
...never mind, I just found an old 1.13.x instance and tested there. It is a 1.14 regression after all.

**Comment by indigoxela** [comment]
Can you provide the steps to reproduce?

I tested it on a fresh 1.14.x-dev and it seems to work properly.

I added a user, added a file, changed the author via the "manage" tab (as admin). It worked. No error, nothing in dblog. You probably did it differently.
