### ISSUE TITLE
[A11Y]  Remove 'navigation' role from 'nav' elements

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4032]
`<nav role="navigation" class="breadcrumb">`
This code gives the following warning when [validated](https://validator.w3.org/):

> The `navigation` role is unnecessary for element `nav`.

We should change instances of the above code to `<nav class="breadcrumb">` instead.

For more information, see: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role

---

PR: https://github.com/backdrop/backdrop/pull/2871

**Comment by indigoxela** [comment]
Tested this on a 1.15.x-dev with default basis theme. It works fine, the redundant "role=navigation" on the "nav" tag is gone.

validator.w3.org is a little happier.

**Comment by stpaultim** [comment]
Marking this as milestone candidate. Looks to be almost done.

**Comment by laryn** [comment]
Thanks @BWPanda for filing and fixing! Thanks for testing, @indigoxela and code review @docwilmot. I've merged https://github.com/backdrop/backdrop/pull/2871 into 1.x and 1.19.x.
