### ISSUE TITLE
No 'footer' ARIA role

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4034]
There doesn't seem to be any such ARIA role as `footer`. Instead, `footer` elements should be given the `contentinfo` role: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer#Accessibility_concerns

Instances of `<footer ... role="footer">` should be fixed.

---

PR: https://github.com/backdrop/backdrop/pull/2873

**Comment by indigoxela** [comment]
validator.w3.org is still not happy with it:

> Warning: The contentinfo role is unnecessary for element footer.

It seems, "contentinfo" would only be needed, if it weren't already a "footer" (e.g. "div").

**Comment by indigoxela** [comment]
Here's some info with examples for "ARIA Techniques" and "HTML Techniques".
The latter example doesn't use a role.

https://www.w3.org/TR/wai-aria-practices/examples/landmarks/contentinfo.html

**Comment by serundeputy** [comment]
@indigoxela I'm not seeing w3 complaining about the footer: https://validator.w3.org/nu/?doc=http%3A%2F%2F2873.backdrop.backdrop.qa.backdropcms.org%2F against the PR sandbox.

Has the checking on the w3 side changed? They state this on top of the checker tool:

> This tool is an ongoing experiment in better HTML checking, and its behavior remains subject to change

I think we should probably go with  the `role="contentinfo"` in the PR as that is not flagged by either w3 or lighthouse: 

![image](https://user-images.githubusercontent.com/6763671/75627569-41cb6d80-5b9f-11ea-8a5d-854b76b19dcb.png)

https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=http://3088.backdrop.backdrop.qa.backdropcms.org/

**Comment by klonos** [comment]
I see what @indigoxela is saying. See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Contentinfo_role:

> Each page should only include one contentinfo landmark, created by either using the <footer> element or by declaring role="contentinfo".
> ...
> Using the <footer> element will automatically communicate a section has a role of contentinfo. Developers should always prefer using the correct semantic HTML element over using ARIA, ...

**Comment by serundeputy** [comment]
that's what MDN says; w3 doesn't express an opinion; https://www.w3.org/TR/wai-aria-practices/examples/landmarks/contentinfo.html  not sure who is canonical.

**Comment by serundeputy** [comment]
that being said the w3.org site does not have the `contentinfo` role on their footer.

![image](https://user-images.githubusercontent.com/6763671/75628918-704f4580-5bab-11ea-84e6-62c76677a0e3.png)

**Comment by BWPanda** [comment]
W3 *does* express an opinion, though slightly hidden under the ['HTML Techniques' tab](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/contentinfo.html#tab2):

> - The HTML `footer` element defines a `contentinfo` landmark when its context is the `body` element.
> - The HTML `footer` element is not considered a `contentinfo` landmark when it is descendant of any of following elements:
>   - `article`
>   - `aside`
>   - `main`
>   - `nav`
>   - `section`

This matches MDN's ['Prefer HTML'](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Contentinfo_role#Prefer_HTML) best practice:

> When it is an immediate descendant of the `<body>` element, using the `<footer>` element will automatically communicate a section has a role of `contentinfo` (save for a known issue in VoiceOver). If at all possible, prefer using `<footer>` instead. Note that a `footer` element nested within an `article`, `aside`, `main`, `nav`, or `section` is not considered `contentinfo`.

In our case(s), the `footer` is not a descendent of any `article`, `aside`, `main`, `nav`, or `section` elements, which means it should have the `contentinfo` landmark automatically. However, it's also not an immediate descendent of the `body` element like MDN says (it's within the layout `div` wrapper). But since both MDN's and W3's own websites have `footer` elements also within `div`s, and since neither specify the `contentinfo` role, I think it's safe to assume that the `footer` will have the `contentinfo` landmark and so we shouldn't add it separately.

PR updated as such.

**Comment by klonos** [comment]
Code change is simple, but I couldn't testing the PR sandbox against w3.org because it starts in the installer. @BWPanda can you please refresh it (close/re-open the PR)?

**Comment by BWPanda** [comment]
@klonos Try again now

**Comment by klonos** [comment]
All good 👍 ...at least no footer-related warnings/errors - we'll need separate issues for the remaining warnings:

![Screen Shot 2020-03-03 at 3 22 01 am](https://user-images.githubusercontent.com/2423362/75695533-54a88400-5cfe-11ea-8eb9-321bf609166c.png)

**Comment by BWPanda** [comment]
@klonos https://github.com/backdrop/backdrop-issues/issues/4163

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2873 into 1.x and 1.15.x. Thanks @BWPanda, @indigoxela, @serundeputy, and @klonos for the great discussion and figuring out whether or not that ARIA role was necessary! The fix was simple and I loved to see how this turned out.
