### ISSUE TITLE
Core fieldable file permission issues after upgrade from 1.13.3

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4039]
**Description of the bug**

Not yet sure if this is a bug. Looking for some help to determine if I'm misunderstanding something.

I just upgraded live version of Triplo.co from 1.13.3 to 1.14.x-dev and I am not seeing any of the UI options for core fieldable files. 

I spun up a fresh new site with the same code and on the fresh new site I have the ability to:
- add a file on the manage files page
- In the structure menu, I have a file types menu

Neither of these options are available to me on my upgraded Triplo.co site. 

I ran the database updates and got the message about "Existing files must be classified according to the currently defined file types"

Is there anything else I need to do?

I have not configured Trusted Host Patterns, but I don't think these are related.

---

PR: https://github.com/backdrop/backdrop/pull/2882

**Comment by klonos** [comment]
Hey @stpaultim 👋 ...is there any error if you enable all errors in `/admin/config/development/logging`, or anything helpful in the log?

**Comment by jenlampton** [comment]
Check for permissions: `Administer file types` will give you the link under structure, and ` Add and upload new files ` will give you the `Add file` link.

I wonder if we need a special update hook to add these permissions, or if we want people to add them manually?

**Comment by stpaultim** [comment]
As I said in Gitter. That was the problem. The admin role did not have permission for these new features and I was not logged in a user #1. 

I lean towards simply granting these permissions to any admin. BUT, I do see a case for not adding them BUT including guidance in release notes to suggest that site owners add them.

**Comment by stpaultim** [comment]
I think we are more likely to run into users like myself who update the site as an admin and don't realize that the new features are there, because they can't see them - then we are to accidentally grant them to someone who should not have them. 

On the other hand, I see a conservative argument for NOT granting new permissions to users on an existing site, without the deliberate decision of the site owner/manager. On existing sites without an editor role there may be "editors" that have been granted a curated set of admin privileges and we would be tinkering with that.

**Comment by olafgrabienski** [comment]
> I lean towards simply granting these permissions to any admin.

I don't know the permission policy for new functionality. Actually, I thought the administrator role usually gets all permissions. Isn't that the case?

**Comment by stpaultim** [comment]
On a new site, the administrator would have automatically gotten these permissions. This issue is about an upgrade. It is possible that the owner of a new site might grant multiple people admin role and then disable some permissions reserved for user #1 only. 

(I don't think this is a common scenario, but it is a potential scenario). 

We have added new features and as part of the upgrade process we DID NOT give permissions to the admin role (I think it was an oversight, not a deliberate decision). The discussion is that while **upgrading** a site, should we automatically give these permissions?

**Comment by olafgrabienski** [comment]
> The discussion is that while upgrading a site, should we automatically give these permissions?

(I assume, you speak of *updating* a site.)

In my opinion, we should give the permissions.

Re your potential scenario: If an owner of a site wants to grant multiple people an 'admin' role but disable some permissions, wouldn't it make more sense to create a separate role for it (to not use the usual administrative role)? Not sure if I've considered it enough but I think we shouldn't account for the uncommon scenario.

**Comment by jenlampton** [comment]
I'm working on an update hook...  PR coming!

**Comment by jenlampton** [comment]
PR ready for review https://github.com/backdrop/backdrop/pull/2882

**Comment by stpaultim** [comment]
The PR gives access to most of the general file permissions for the admin role. But it does not give permissions for all the special file types. 

![Permissions___green](https://user-images.githubusercontent.com/3144571/64930492-d101e600-d7f6-11e9-9b48-90ed7ae7ecee.png)

**Comment by quicksketch** [comment]
Thanks @stpaultim, good find. I updated the PR slightly to prevent duplicate permissions from being assigned and added a safety check to ensure that the admin role existed before modifying it. I'll work to fix these permissions, though it's mostly a UI issue since administrators will already have the "manage files" permission which gives them access to all types.

**Comment by quicksketch** [comment]
Okay PR now updated to add permissions to the admin role for every individual file type as well.

**Comment by jenlampton** [comment]
I got all of the file permissions!

<img width="992" alt="Screen Shot 2019-09-15 at 7 09 49 PM" src="https://user-images.githubusercontent.com/397895/64931279-6a77ca80-d7ec-11e9-9ade-d526b10d613c.png">

**Comment by stpaultim** [comment]
Me too! Works as expected.

**Comment by quicksketch** [comment]
Thanks for the double-confirmation! Merged https://github.com/backdrop/backdrop/pull/2882 into 1.x for 1.14.0.

Seems like this is the last issue! :crossed_fingers: Onward to 1.14.0!
