### ISSUE TITLE
[DX] Introduce a `theme_has_color()` function

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4044]
We already have [`theme_has_settings()`](https://api.backdropcms.org/api/backdrop/1/search/theme_has_settings) ...so while working on #4042 I had to do this:

```php
    if (theme_has_settings($default_theme)) {
      $themes = list_themes();
      $color_support = $themes[$default_theme]->info['settings']['color'];
      if (module_exists('color') && $color_support) {
        $theme_link_label = t('Change the current theme\'s settings and colors');
      }
      else {
        $theme_link_label = t('Change the current theme\'s settings');
      }
      $links_col1['admin/appearance/settings/' . $default_theme] = $theme_link_label;
    }
```

I would like to be able to do this instead:

```php
    if (theme_has_settings($default_theme)) {
      $theme_link_label = t('Change the current theme\'s settings');
    }
    if (theme_has_color($default_theme)) {
      $theme_link_label = t('Change the current theme\'s settings and colors');
    }
    $links_col1['admin/appearance/settings/' . $default_theme] = $theme_link_label;
```

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2928

**Comment by klonos** [comment]
...I know that usually new features go in on minor releases, but since this will be an API addition instead of a change, I was hoping to get it in sooner; so added the label for a next bug release.

**Comment by hosef** [comment]
I like this. I think we could make the theme settings system check for color.inc settings as well as normal theme settings and we could remove the unnecessary `settings[color] = true` line from all of the theme info files.

**Comment by klonos** [comment]
> I like this. I think we could make the theme settings system check for color.inc settings as well as normal theme settings and we could remove the unnecessary `settings[color] = true` line from all of the theme info files.

Hey @hosef 👋 ...I have filed an initial PR for review: https://github.com/backdrop/backdrop/pull/2928

I currently check for both the `settings[color] = true` setting + the existence of `color/color.inc`, but as you say, we can consider only checking for `color.inc`, and then remove the `settings[color] = true` line from the .info files of core themes.

**Comment by stpaultim** [comment]
Is there something to test in the UI? 
It looks like this is just a API change and can only be tested with code?

**Comment by klonos** [comment]
Yup, this can only be tested in code.

**Comment by hosef** [comment]
I reviewed your pull request. Everything looks good except that there is a call to `drupal_get_path()` in it that should be replaced.

**Comment by klonos** [comment]
Good catch! 👍 (force of habit 😅) ...I've fixed it.

**Comment by hosef** [comment]
Cool. Everything looks ready to go now

**Comment by serundeputy** [comment]
do we need a test for the API addition of `them_has_color`? 

Protocol dictates yes; I did a quick perusal of `color.test` and I don't see a test for `theme_has_settings`, but maybe that is in a different test not sure

**Comment by quicksketch** [comment]
I too questioned if this needed tests. But as the code is the same, just wrapped in a function, this function get tested by `ColorTestCase` when it tests the Color UI. So it seems fine to me.

I merged https://github.com/backdrop/backdrop/pull/2928 into 1.x for 1.16.0. I'm not pulling into 1.15.x as this is an API addition, not a bug fix.
