### ISSUE TITLE
[UX] Rename Layout template list from Settings to Templates

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4048]
In the process of adding our awesome new flexible layout templates, we managed to loose the settings form. We now have a fancy list of layouts, but nowhere to put other layout settings, like, for example, layout permissions. 

Additionally, when people are on an admin page adjusting a flexible layout template, and want to go "up one level" to the listing of all layout templates, it's very unclear that the "Settings" breadcrumb would take them there. 

This breadcrumb, page title, and URL should be updated to reflect that this is now a layout template listing.

Before:
<img width="1268" alt="before" src="https://user-images.githubusercontent.com/397895/64931303-93985b00-d7ec-11e9-86c0-133c0a1e3f5b.png">
After:
<img width="1226" alt="after" src="https://user-images.githubusercontent.com/397895/64931306-9abf6900-d7ec-11e9-9d13-047729f70e6c.png">

The PR here will include:
* 'Settings' tab renamed 'Layout templates'
* ~The paths `admin/structure/layouts/settings/*` become `admin/structure/layouts/templates/*`~ (moved to #4134)
* ~The paths `admin/structure/layouts/settings/flexible-template/*` becomes `admin/structure/layouts/templates/flexible/*`~ (moved to #4134)

---

Complete fix PR: https://github.com/backdrop/backdrop/pull/2884

---

Partial fix PR: https://github.com/backdrop/backdrop/pull/2935

**Comment by stpaultim** [comment]
This doesn't look right to me. 

![Update_layouts___PR_2884_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/64931419-3907fa80-d7fe-11e9-8e62-67ee88320359.png)

**Comment by klonos** [comment]
@stpaultim this ^^ is #2714 ...it's been bugging me forever!

**Comment by quicksketch** [comment]
This all looks pretty reasonable but I don't want to rush it for 1.14.0. I'm also not entirely sure this is something that should be put into a "bugfix" release, as it has practically no impact on end-users.

**Comment by klonos** [comment]
> ...it has practically no impact on end-users.

Yes it has. People navigate to a "Settings" tab/menu link, but there are no settings there. "Templates" is a more fitting label for it.

**Comment by herbdool** [comment]
A small but useful fix. It's not intuitive to look under settings for templates.

**Comment by stpaultim** [comment]
> I'm also not entirely sure this is something that should be put into a "bugfix" release, as it has practically no impact on end-users.

It is a UX issue. In my extensive testing of Flexible Layouts this week, this is my number 1 annoyance. As @herbdool says, it just doesn't make sense to find a list of layouts under "settings" tab. I'd love to see this fixed quickly if possible.

**Comment by quicksketch** [comment]
This looks pretty good. Can we add a `backdrop_goto_deprecated()` for the old `admin/structure/layouts/settings` path? The flexible layout paths are both so new and unusual to link to I don't think we need to have deprecated redirects for them.

Or if we take this one step at a time: Just rename the tab from "Settings" to "Templates" and not the path in 1.14.x, then change the entire path in 1.15.0.

**Comment by jenlampton** [comment]
> Or if we take this one step at a time: Just rename the tab from "Settings" to "Templates" and not the path in 1.14.x, then change the entire path in 1.15.0.

I pushed a PR that only changes the tab name to "Templates": https://github.com/backdrop/backdrop/pull/2935

**Comment by klonos** [comment]
Thanks @jenlampton ...RTBC 👍

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2935 into 1.x and 1.14.x for 1.14.1. Should we just keep this issue open to continue the bigger change (path renaming) in 1.15.0?

**Comment by klonos** [comment]
...I'll file a follow-up @quicksketch 😉

**Comment by klonos** [comment]
Done: #4134
