### ISSUE TITLE
Viewing a file (e.g. /file/1) seems to mess up theme

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4051]
**Description of the bug**

After upgrade to 1.14.0, and using the new file entity feature to view a file at its entity path, e.g. `/file/1`, I get this:

![Screenshot from 2019-09-16 10-19-40](https://user-images.githubusercontent.com/1071483/64965916-d64d4800-d86b-11e9-9610-4c2979308cc8.png)

I can't recall if it's supposed to show the admin theme or the public theme.

It's possible it's just on my test site, though I started with a relatively fresh install.

**Comment by herbdool** [comment]
Okay, my fault. I had tested flexible layouts but hadn't reverted the change before testing this. Once I did that the theme looked fine on this page.

**Comment by klonos** [comment]
Yeah, I had the same when testing a layout with `node/%` as context, and viewing any content 😅 ...that empty blue rectangular thing is what you get if you add the header block to the first row/region.
