### ISSUE TITLE
Remove any remaining references to 8.x versions of modules (or core) 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#406]
We should do a through grep through Backdrop for any references to "8.x" and make sure they all get removed or updated before we release 1.0.0.

**Comment by quicksketch** [comment]
I'm going to pick this one up since there's not much left to do here and we've only got a few days left before 1.0.0.

**Comment by quicksketch** [comment]
Turns out there were a bunch of references to 8.x in our update tests, which took a little work to get through tests again. Now fixed and PR is at https://github.com/backdrop/backdrop/issues/660.

**Comment by quicksketch** [comment]
We're now free of any references to:

- Drupal 8
- D8
- 8.x
