### ISSUE TITLE
Fix ambiguous wording in filter.module comment

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4061]
In `filter.module` there's the following comment and code:

```php
// Programmatic saves may not contain any filters.
if (!isset($format->filters)) {
  $format->filters = array();
}
```

This sounds like it means "Programmatic saves are not allowed to contain any filters", but the code seems to suggest it's actually "Programmatic saves might not contain any filters."

I suggest changing this to avoid confusion.

**Comment by BWPanda** [comment]
And here's a [PR](https://github.com/backdrop/backdrop/pull/2886).

**Comment by indigoxela** [comment]
Totally makes sense. :+1:

Hm, normally, as it's only a comment change, I'd not request a rebase, but your PR didn't even run on GHA, it's 600 commits behind backdrop:1.x.

Mind to rebase? Not a strict requirement, though.

**Comment by yorkshire-pudding** [comment]
Makes sense to me to

**Comment by BWPanda** [comment]
Thanks guys. PR updated with latest changes from `1.x`.

**Comment by BWPanda** [comment]
Thanks guys. I've merged https://github.com/backdrop/backdrop/pull/2886 into 1.x and 1.21.x.
