### ISSUE TITLE
Fixed: Undefined variable '$values' in token.test.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4062]
On line [210](https://github.com/backdrop/backdrop/blob/1.x/core/modules/simpletest/tests/token.test#L210) of `token.test`, there's a `$values` variable which, from what I can see, never gets defined.

I didn't get any errors related to this, just saw the code and suspect it's a bug...

**Comment by klonos** [comment]
Seems that you're right @BWPanda

**Comment by BWPanda** [comment]
Question now is, what to do about it... :-)

**Comment by BWPanda** [comment]
Pinging the test master: @hosef

**Comment by argiepiano** [comment]
Excuse me for jumping in @hosef and @BWPanda , but I saw that when I added some new date token fulfillments to core a couple of months ago and forgot to fix it. 

That particular line is in an if statement that checks if we are supposed to expect NULL as the fulfillment value of a token. So, to check if this is actually true, we should be changing line 210 to:

```php
        $this->assertTrue(!isset($replacements[$name]), t("Token value for @token was not generated.", array('@type' => $type, '@token' => $token)));
```

I haven't tested this, but I can do some checking (and submit a PR if you wish) later today.

**Comment by argiepiano** [comment]
Confirming that the (edited) line in my previous comment works. 

PR https://github.com/backdrop/backdrop/pull/3918

To check that this works, insert a breakpoint in line 210 of token.test. Then run any tests that uses `assertTokens()` and sends an array of tokens where at least one of them has an expected value of NULl. 

For example, run `TokenURLTestCase`.

**Comment by quicksketch** [comment]
Thanks @argiepiano, @klonos, @BWPanda, and @indigoxela! I merged https://github.com/backdrop/backdrop/pull/3918 into 1.x and 1.21.x.
