### ISSUE TITLE
PHP Notice: Undefined property: view::$exposed_input in attach_to()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4075]
When a views attachment is configured to inherit exposed filters, but does not have any exposed filters, I see this PHP notice:

```
Notice: Undefined property: view::$exposed_input in 
views_plugin_display_attachment->attach_to() (line 234 of backdrop/core/modules/views/plugins/views_plugin_display_attachment.inc).
```

**Steps to reproduce:**
1. Build a view with a block display.
2. Add an attachment display. 
3. Under "Attachment" set the `Inherit exposed filters` setting to `inherit`
4. Attach the attachment to the block display.
5. Place the block on the home page.
6. View the home page.

---
PR: https://github.com/backdrop/backdrop/pull/2892

**Comment by klonos** [comment]
@jenlampton https://www.drupal.org/project/views/issues/2481401

#3853

**Comment by jenlampton** [comment]
This problem was mentioned in https://github.com/backdrop/backdrop-issues/issues/3853 so I am going to close this issue and mark as dupe, but the PR should remain open for that issue.

**Comment by klonos** [comment]
Thanks @jenlampton 👍 

Can you please add the following to the PR summary:

https://www.drupal.org/node/2481401
https://git.drupalcode.org/project/views/commit/ddaeddc

**Comment by laryn** [comment]
I'm going to reopen this and link this issue from the Views crossport meta. Maybe it can be merged in now from this issue, before all the cross-ports are ready.

**Comment by herbdool** [comment]
Code looks good.

**Comment by klonos** [comment]
@jenlampton just to be safe, can we please get a rebase? ...the checks still have ZenCI.

**Comment by jenlampton** [comment]
yes of course! rebased and PR pushed back up. Tests running now.

**Comment by klonos** [comment]
Thanks @jenlampton ...tests still green 👍🏼

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2892 into 1.x and 1.21.x. Thanks @jenlampton, @klonos, @laryn, and @herbdool!
