### ISSUE TITLE
Max length of the 'Allowed file extensions' field is too small - triggers validation error when too many extensions

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4085]
**Description of the bug**
The 'Allowed file extensions' field (a setting on the 'File' field type (not sure if its present elsewhere too)) has an issue where you can enter file extensions separated by a space *or* a comma, but when you save and reload the form, they're displayed with a space *and* a comma.

This causes issues with the max length of the field, which may be fine when you separate extensions with just a space, but when the form's reloaded and commas are added too, if you try to re-save the form it says you've exceeded the max length of the field.

**Steps To Reproduce**
To reproduce the behavior:
1. Create a File field and edit it.
2. Enter `pdf doc docx dot dotx odt ott odm txt rtf csv xls xlsx xlt ods ots ppt pptx pps pot odp otp zip tar gz tgz rar bz2 mpg mpeg mov avi wmv flv mp3 wma m4a mp4 m4p aac wav ogg mid jpg jpeg png gif tif tiff ico bmp` in the 'Allowed file extensions' field.
3. Save.
4. Re-edit the field.
5. Note the new value of 'Allowed file extensions' as `pdf, doc, docx, dot, dotx, odt, ott, odm, txt, rtf, csv, xls, xlsx, xlt, ods, ots, ppt, pptx, pps, pot, odp, otp, zip, tar, gz, tgz, rar, bz2, mpg, mpeg, mov, avi, wmv, flv, mp3, wma, m4a, mp4, m4p, aac, wav, ogg, mid, jpg, jpeg, png, gif, tif, tiff, ico, bmp`.
6. Re-save.

**Actual behavior**
The following error is displayed:

> Allowed file extensions cannot be longer than 256 characters but is currently 259 characters long.

And the form isn't saved.

**Expected behavior**
The 'Allowed file extensions' field should have a value of what was originally submitted (e.g. `pdf doc docx dot dotx odt ott odm txt rtf csv xls xlsx xlt ods ots ppt pptx pps pot odp otp zip tar gz tgz rar bz2 mpg mpeg mov avi wmv flv mp3 wma m4a mp4 m4p aac wav ogg mid jpg jpeg png gif tif tiff ico bmp`) and therefore no error should be displayed and the form should save successfully.

**Additional information**
Backdrop CMS version: 1.13.3

**Comment by BWPanda** [comment]
Well that was easy: https://github.com/backdrop/backdrop/pull/2899

**Comment by BWPanda** [comment]
The PR simply disables the re-writing of the default value. It apparently was meant to help readability (by adding additional commas between each extension), but since the field is saved with spaces separating them anyway, I think it's still readable.

The alternative would be to run the validation function (`_file_generic_settings_extensions()`, which converts all commas to spaces) before validating the `#maxlength`, however since `#maxlength` gets validated before custom validation functions, this would require a bit of re-writing and bypassing Backdrop's default methodology.

So I figure my PR is simplest and easiest.

**Comment by klonos** [comment]
Thanks @BWPanda 👍 ...I would have preferred the comma-separated list, if the character limit issue was not a problem with saving the form; but the bug is more serious than the "cosmetics".

Ideally, we can consider increasing the character limit of the field, but that can be a follow-up 😉

**Comment by quicksketch** [comment]
I have a slight preference for leaving the comma in-place. It seems like the problem of running out of characters could easily happen just if you had enough extensions (whether there were commas or not). I think we should just increase the `#maxlength` property to to 512 (up from 256).

**Comment by klonos** [comment]
> Ideally, we can consider increasing the character limit of the field, but that can be a follow-up 😉

Now that @quicksketch has second that, I feel more confident that this should be the way to go 🙂 ... @BWPanda, care to update the PR accordingly?

**Comment by BWPanda** [comment]
Sure, updated the [PR](https://github.com/backdrop/backdrop/pull/2899).

**Comment by klonos** [comment]
Thanks @BWPanda ...back to RTBC 👍

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2899 into 1.x and 1.14.x. Thanks @BWPanda and @klonos!
