### ISSUE TITLE
[UX] Missing translation function calls in layout.module

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#4087]
**Description of the bug**
Missing translation function calls in `layout.module` and `layout.admin.inc`. Localization needs these.
I will create two PRs.

---
PR by @VasasA: https://github.com/backdrop/backdrop/pull/2898

**Comment by herbdool** [comment]
Simple change. Thanks!

**Comment by quicksketch** [comment]
Thanks @VasasA! Is it necessary to translate every one of these strings completely? I posted a comment at https://github.com/backdrop/backdrop/pull/2898/files#diff-90b335b9ddd5cf70b15b598e53b824c3R2084-R2086

**Comment by VasasA** [comment]
Good idea, thank You! I created a new commit:
https://github.com/backdrop/backdrop/pull/2898/files#diff-90b335b9ddd5cf70b15b598e53b824c3R2084-R2086

**Comment by klonos** [comment]
LGTM 👍 ...thanks @VasasA

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/2898 into 1.x and 1.14.x. Thanks @VasasA, @klonos, and @herbdool!
