### ISSUE TITLE
Basis: Remove the default color change behind the site name 

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4093]
One of the most frustrating things for me with the Basis theme is default color behind the site name. I don't recall ever building a site where I wanted the site name in a block with a different color than the rest of the header. 

I've heard that this might be helpful on mobile sites, but I think it's a distraction and makes Basis less attractive to people who are testing or previewing BackdropCMS. 

Users can change this color through the UI using the color module. However, I think that the default should have the site name background the same color as the rest of the header region. 

![Home___Flexible_and_Create_videos_screencasts_about_the_major_features_in_Backdrop_CMS_·_Issue__130_·_backdrop-ops_backdropcms_org](https://user-images.githubusercontent.com/3144571/65725167-a37b2f00-e077-11e9-866c-dc4117263ddc.png)

- - - - - - - - 

PR by @stpaultim = https://github.com/backdrop/backdrop/pull/2950

**Comment by klonos** [comment]
@stpaultim if you want this added to the `Bugs` project, you'll need to label it as `type - bug report` instead of feature request.

...but to the point: I find this to be a mater of preference, and it works nicely on mobile:

<img width="500" alt="Screen Shot 2019-10-03 at 7 22 43 am" src="https://user-images.githubusercontent.com/2423362/66082955-a06bcb80-e5ae-11e9-9583-2558f7ce88f7.png">

Besides, Basis has Color module support, and the specific element can be customized:

<img width="853" alt="Screen Shot 2019-10-03 at 7 20 48 am" src="https://user-images.githubusercontent.com/2423362/66082998-b9747c80-e5ae-11e9-89a6-568ad41ba793.png">

...so people that don't like it being a different color, can always change it to be the same color as the rest of the header. It takes only a few clocks 😉

**Comment by stpaultim** [comment]
I am not sure I would consider this a bug as (I agree) it is a matter of preference. While I agree, that is is easily fixed with the color module. I don't know that most users necessarily understand that and I would estimate that 90% or more of them will make this change. Why require that 90% or more users (if you accept that number) make a few clicks to make their site look less ugly (in my opinion). 

From a Backdrop CMS perspective, I believe that this light blue box on Backdrop CMS out of the box, is the least attractive aspect (or ugliest, depending upon your preference) aspect of the theme. For me, changing the default would radically improve the appearance of the Basis theme (out of the box). 

This is not a critical issue for me, because I know how to fix this and no longer use Basis out of the box without a sub-theme. But, I am concerned because this detail is a major part of any new users first impression of Backdrop CMS.

**Comment by stpaultim** [comment]
@olafgrabienski just suggested in Twitter that the default could be the light blue on mobile and the same color as the full header for desktop devices. 

I agree that this would work, but I'm not sure if that would cause a problem with color module support. Users are able to change this using the color module, but they can only make one selection. 

We could remove the ability to change this using the color module in Basis??

**Comment by klonos** [comment]
The more complicated solution would be to have Color module support breakpoint variations for the same item. The simplest (in this specific scenario) would be to just have changes made "manually", for each breakpoint. I have not worked on color support-enabled themes for a while, so I'd have to look into it to see how feasible/easy/hard it is.

One thing to keep in mind though is that this could potentially change how existing sites work; so we need to take that into consideration.

**Comment by klonos** [comment]
> ...it is a matter of preference. ... Why require that 90% or more users (if you accept that number)

Metrics people!! ...we need metrics 😄 (#285)

**Comment by hosef** [comment]
> The more complicated solution would be to have Color module support breakpoint variations for the same item. The simplest (in this specific scenario) would be to just have changes made "manually", for each breakpoint. I have not worked on color-support-enabled themes for a while, so I'd have to look into it to see how feasible/easy/hard it is.

I do not think this would require any changes to the Color module. It would just require adding new settings to Basis to support the behavior. IE, have a 'mobile site name background' setting and a 'desktop site name background' setting and adjusting the form so that it looks ok with those settings.

Each theme has quite a bit of control over how the form next to the preview is setup.

**Comment by stpaultim** [comment]
Is it possible to make this change without breaking existing sites. 

What we are discussing here is changing the default background color for the site name on large screens (basis theme). Can that be done without effecting existing sites that are happy with the status quo?

**Comment by hosef** [comment]
@stpaultim We could make an update hook to rewrite the color settings for every site that is using basis, although I am not sure if that is a good idea because we would be forcing all existing sites to be using a custom color scheme instead of the default.

**Comment by quicksketch** [comment]
We have made adjustments to the display of Basis over time. For example in 1.14.0 we removed the background from the login links in https://github.com/backdrop/backdrop-issues/issues/3748.

So another option here is to just remove the background color on desktop sizes or entirely. Though this is subjective and should be advised by @wesruv or other designers.

**Comment by wesruv** [comment]
FWIW I have no opinion on this

**Comment by jenlampton** [comment]
I think we should leave it on mobile, remove it entirely on desktop, and change the label in the color settings to "Mobile site name background".

**Comment by stpaultim** [comment]
I created a PR: https://github.com/backdrop/backdrop/pull/2950

All this PR does is change the background color behind the title to match the rest of the background at 34em and larger. Anything larger than 34em should automatically match the rest. Below 34em it should use the same color module setting as before, except it's been renamed to: "Mobile site name background."

**Comment by jenlampton** [comment]
Code looks great. Tested, also working great!
<img width="600" alt="Screen Shot 2019-10-25 at 12 14 34 AM" src="https://user-images.githubusercontent.com/397895/67550928-8e1c1380-f6bc-11e9-8eca-a96b28365bd4.png">
<img width="250" alt="Screen Shot 2019-10-25 at 12 14 59 AM" src="https://user-images.githubusercontent.com/397895/67550953-9f652000-f6bc-11e9-8b6d-91810beca130.png">

**Comment by quicksketch** [comment]
My inclination would have been to implement this in 1.15.0 only (as a minor release change). But with @stpaultim, @klonos, and @jenlampton all agreeing this is suitable for a bugfix change I've merged this into both 1.x and 1.14.x.

Thanks everyone for reaching this solution. I think it strikes a good balance and makes Basis a more robust theme for sites that have long site titles.

**Comment by stpaultim** [comment]
@quicksketch - Thanks. I understand your inclination. As you might have seen, I have opened another issue to address the best way of making these kinds of changes in the future. 

https://github.com/backdrop/backdrop-issues/issues/4167

**Comment by olafgrabienski** [comment]
Should we put a hint in the release notes how people can get the background color back, if they want to?
