### ISSUE TITLE
Fix formatting of detailed test results

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4099]
Sorry if this isn't the right place for this, wasn't sure where else to put it...

When I have a PR and tests run automatically and fail, here's the output I see:

```
Detailed test results
---------------------


---- Filter: Filter format access (FilterFormatAccessTestCase) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      filter.test        617 FilterFormatAccessTestCase->testFor
    Old title not found.
Fail      Other      menu.test          689 MenuNodeTestCase->testMenuNodeFormW


---- Menu: Menu settings for nodes (MenuNodeTestCase) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
    Link with label i8U9pEzK not found.
Fail      Other      menu.test          698 MenuNodeTestCase->testMenuNodeFormW
    Link with label i8U9pEzK not found.
```
(Source: https://zen.ci/backdrop/backdrop/test/test-php70-backdrop_backdrop_2903-860d7d6-1)

To me that looks messed up. There should be one failed Filter test, and two failed Menu tests, but everything seems a bit all over the place.

Here's how I think it should look:

```
Detailed test results
---------------------


---- Filter: Filter format access (FilterFormatAccessTestCase) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      filter.test        617 FilterFormatAccessTestCase->testFor
    Old title not found.


---- Menu: Menu settings for nodes (MenuNodeTestCase) ----


Status    Group      Filename          Line Function                            
--------------------------------------------------------------------------------
Fail      Other      menu.test          689 MenuNodeTestCase->testMenuNodeFormW
    Link with label i8U9pEzK not found.
Fail      Other      menu.test          698 MenuNodeTestCase->testMenuNodeFormW
    Link with label i8U9pEzK not found.
```
(E.g. the `Fail      Other      menu.test          689 MenuNodeTestCase->testMenuNodeFormW` line should be moved down into its appropriate section)

I've seen this happen on other tests, where there were more failures and so it was even harder to interpret because of the weird formatting.
Not sure where/how this formatting is set, but I think it needs looking into...

**Comment by BWPanda** [comment]
Here's an excerpt from another test:

```
---- Taxonomy: Taxonomy term functions and forms (TaxonomyTermTestCase) ----


Status    Group      Filename          Line Function                            
Fail      Other      taxonomy.test      717 TaxonomyTermTestCase->testTermInter
--------------------------------------------------------------------------------
    The randomly generated term description is present.
```
(Source: https://zen.ci/backdrop/backdrop/test/test-php53-backdrop_backdrop_2894-2259e14)

The result is displayed above the header separator, and is separated from its description.

**Comment by klonos** [comment]
...here's another bit that may need fixing: https://zen.ci/backdrop/backdrop/test/test-php70-backdrop_backdrop_2897-8851462

```
fail Default value for checkboxes_all_scenarios: expected array ( 0 =&gt; &#039;test_1&#039;, 1 =&gt; &#039;test_3&#039;, ), returned array ( &#039;test_1&#039; =&gt; &#039;test_1&#039;, &#039;test_3&#039; =&gt; &#039;test_3&#039;, ). form.test:477
fail Default value for checkboxes_all_scenarios: expected array ( 0 =&gt; &#039;test_1&#039;, 1 =&gt; &#039;test_3&#039;, ), returned array ( &#039;test_1&#039; =&gt; &#039;test_1&#039;, &#039;test_3&#039; =&gt; &#039;test_3&#039;, ). form.test:477
```

**Comment by BWPanda** [comment]
Ping @gormartsen

**Comment by Gormartsen** [comment]
I think issue somewhere in this code
https://github.com/backdrop/backdrop/blob/1.x/core/scripts/run-tests.sh#L889

So if fixxed there, should be properly rendered.

**Comment by BWPanda** [comment]
Tried looking into this, but I can't even replicate the problem on my local environment... I applied this patch (https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/2903.patch) and then ran `php ./core/scripts/run-tests.sh --verbose --cache --concurrency 10 --color MenuNodeTestCase FilterFormatAccessTestCase MenuTestCase`

But I kept seeing nicely formatted results...
