### ISSUE TITLE
Decide if we need to add plugin-system to core.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#41]
A plugin architecture forms the foundation of both CTools and Views in Drupal 7. In order to include Views in core, we may need a (hopefully mostly-compatible) plugin system to load these files.

The general consensus on D8's plugin system is that it's quite good, other than the PSR-0 directory structure and the use of Annotations for discovery. Until we decide otherwise, perhaps the typical _info() hook structure is the fastest/most-compatible way forward.

Or alternatively, do we even actually need plugins?  What do they provide that we don't have already?

**Comment by donquixote** [comment]
Just for the record, there is also https://drupal.org/project/renderkit with /cfr, which in many ways works as a "plugin system", but without the overhead on plugin implementations.
Yes, I am advertising my own pet project here, but I think it is relevant.
