### ISSUE TITLE
Typo in the `default_allowed_extensions` form element in `file_settings_form()`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4101]
...there's a stray bracket there:

```php
  $form['default_allowed_extensions('] = array(
    '#type' => 'textfield',
    '#title' => t('Default allowed file extensions'),
    '#default_value' => $config->get('default_allowed_extensions('),
    '#description' => t('Separate extensions with a space and do not include the leading dot.'),
    '#maxlength' => NULL,
  );
```

Same goes for the `'#default_value'`.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2909

**Comment by BWPanda** [comment]
Wow, thanks @klonos! How does something so simple, yet so broken, go unfixed for so long? Merged https://github.com/backdrop/backdrop/pull/2909 into 1.x and 1.16.x.
