### ISSUE TITLE
File test for deleting metadata doesn't check correctly.

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#4103]
**Description of the bug**

In file.test:1921, the `testImageDimensions()` test deletes the file at the end and then tries to check the metadata was deleted with the file.  However, query looks for a `fid` with the string literal `'fid'`, not the integer file ID of the deleted file.

The test happens to pass for invalid reasons.

**Steps To Reproduce**
Visual inspection.

MySQL will quietly convert a string to a number, if it is something like '10', and will convert any other strings to integer 0.  This was discovered while trying to run the test against PostgreSQL. PostgreSQL throws an exception when trying to compare an integer field with a string literal.

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version: 1.14
- Web server and its version: Apache
- Operating System and its version: Debian
- Browser(s) and their versions: simpletest

- - - - - - - - 

PR by @jlfranklin - https://github.com/backdrop/backdrop/pull/2910

**Comment by klonos** [comment]
Good catch @jlfranklin 👍 ...the change is pretty straight-forward, so RTBC.

**Comment by quicksketch** [comment]
Thanks @jlfranklin! Merged https://github.com/backdrop/backdrop/pull/2910 into 1.x and 1.14.x.
