### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sitebaba** [backdrop/backdrop-issues#4109]
while installing the backdrop cms version 1.14.0  i was taken back to database configuration step instead of profile setup. i tried to drop the database tables and redo the process, but the result is same. so i am unable to install the backdrop and my enthusiasm has been thrashed. is this a bug?

**Comment by indigoxela** [comment]
>  i was taken back to database configuration step instead of profile setup

Hi @sitebaba - can you please provide the messages shown (screenshots) and the exact steps you made?

Which instructions did you follow? This one? https://backdropcms.org/installation

**Comment by klonos** [comment]
Thanks for taking the time to report this @sitebaba, and sorry to see that you've had a bad first experience.

1.14 has been released almost 3 weeks ago, and we did not have any reports of such a problem. Perhaps this is specific to your setup, but we can certainly help.

Besides the screenshots, can you please also let us know what your setup/configuration is? Are you trying the installation on your local, or on a hosting server? What is the operating system and apache/nginx, mysql, and php versions? Have you downloaded Backdrop from bacropcms.org, or cloned it from GitHub?

**Comment by sitebaba** [comment]
hi guys @indigoxela and @klonos , thanks for that, but when i check now, it asked for me to setup profile and i went through and all went good. don't know what was the issue. i have installed it here https://hamroweb.com/backdrop/
i will try to replicate the issue in another location and let you know if i can duplicate the issue. cheers

**Comment by indigoxela** [comment]
> ...don't know what was the issue

One possible cause could have been a typo in your database credentials (db name or password).
This would get you back to the database step, as Backdrop isn't able to create the tables then.

Anyway - glad you sorted things out. Welcome to the Backdrop community!
