### ISSUE TITLE
[UX] Better defaults position for breadcrumbs on installation of new sites.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4113]
**Revised Description** - UPDATED: Aug 14,2020 by @stpaultim 

The original issue suggested changing the order of title, breadcrumbs, and tabs. The only portion of this that I've noticed real support for (and the most urgent part of this in my own mind) is moving the breadcrumbs above the title. We can revisit other ideas for improving the layout in the future. 

The original PR changed the core file: core/modules/layout/config/layout.layout.default.json which meant that this change would effect all news sites regardless of install profile.

**Reasons for change:**

The default theme in Backdrop CMS standard install profile is Basis and positioning the breadcrumbs below the Title doesn't seem practical or appealing for Basis. While there are definitely use cases for positioning the breadcrumbs where they are, I believe that the default settings should be configured to look good and be useful in the default theme. Site admins using other themes and/or creating their own themes can easily move the breadcrumbs to the position that works best for them. The goal here is to make Basis look good and work good out of the box. 

The approach in the existing PR is simply to edit the install file in the Standard Install Profile. This should only effect new sites using the Standard Install Profile and not have any effect on existing sites. 

We could make the same changes directly here: core/modules/layout/config/layout.layout.default.json, but in this case these changes would effect all new sites and may have an unintended effect on users who have created their own custom install profile. 

PROPOSED SOLUTION:

Based upon some feedback, I've modified the PR to only effect the standard install profile. With this PR, the standard install profile will modify the layout.layout.default.json config file to do the following:

1) It implements the "Page Title Combo" block, instead of the default hard-coded Title on the page. I don't see any other way of getting the breadcrumbs above the title in the install profile. 
2) It positions the breadcrumbs above the title. 

CURRENT STATUS OF ISSUE:

Looking for feedback on this new approach. Also, need review of PR to check my syntax and variables. 

---
Below this issue is the original issue and proposed solutions, some of which is no longer relavent.

**ORIGINAL - Description of the need**

Backdrop out of the box starts with a page layout that puts breadcrumbs below the page title. This seems REALLY weird and unhelpful (even though it is easy to fix). 

I think that we need a better place to put the default breadcrumbs block than the current location and current layouts do not have a suitable place. We can't move the default position of the block to the header, because it just doesn't work and we can't move the default position of the title, because it's hard-coded into core templates. 

While it is relatively easy to solve this problem by turning off breadcrumbs or adding your own title block in another region, I think it's poor user experience to require everyone to make this change and sets a poor first impression of Backdrop CMS (out of the box) to find your breadcrumbs in such a strange position. 

**ORIGINAL - Proposed solution**

I propose adding another region (need ideas on what to name this region) to all core layouts between the header and the default title. Adding a region will not break existing sites and provides the opportunity to move the default breadcrumb positioning above the page title where most people would expect it to be. 

**Alternatives that have been considered**

1) We could turn off the breadcrumbs block by default. Requiring users to turn it on would remove the poor first impression, but also force new users to figure out how to place breadcrumbs properly on their own (if they want breadcrumbs). 
2) Placing a default TITLE block in the content region for new sites. This would turn off the current title block and by default the breadcrumbs would be above the page title. 
3) Create new sites with a custom Flexible Layout Template that resolves this problem by default, instead of the current core layouts. 
4) **(ADDED)** Add a single NEW layout that can used in the default install profile to address these issues. 

**Additional information**

1) I don't think this is a critical issue, but if this solution makes sense, I think would be easy to implement and improve the out of the box experience for new users. 
2) I'm not convinced that this is the right solution, but would like to start a discussion. 
3) I think that this would be a good easy issue for a beginner to create a PR. If I am correct, we'd just need to add a region to all core layouts. 
4) I think that an argument can be made that there are lots of other things that a user might want between the header and the page title for which these new regions would be helpful. 
5) Best practices in breadcrumbs design? = https://www.nngroup.com/articles/breadcrumbs/

![Your_first_post____Demo](https://user-images.githubusercontent.com/3144571/66250875-4124cd00-e70e-11e9-9ecd-82099c5cf2bb.png)

**Comment by stpaultim** [comment]
It just occurred to me that we could add a single NEW layout template to core and incorporate that into the default install profile to address these issues. Then all existing layout templates could be left as they are.

PRO: Not changing existing layout templates, only adding new options. 
CON: The problem persists with all other layout templates.

**Comment by klonos** [comment]
> ...and we can't move the default position of the title, because it's hard-coded into core templates. ... move the default breadcrumb positioning above the page title where most people would expect it to be.

@stpaultim if you add the "Page title" and the "Page tabs (Local tasks)" in the layout, then you get the desired outcome; and people can then reorder these blocks as they see fit. Right?:

<img width="924" alt="Screen Shot 2019-10-05 at 6 47 53 pm" src="https://user-images.githubusercontent.com/2423362/66252575-c062e100-e7a0-11e9-86fc-c197c185cc1b.png">

This problem originates from the fact that the ability (or rather "trick") to make the "hard-coded" title block reorder-able came at a later stage in the Backdrop dev cycle, with #1704, in 1.7 (May 15, 2017). In that issue, we've added the ability to change things, but we have not made it the default, OOTB status. Perhaps that is what we need to reconsider.

In other words, I am not opposed to the idea of another region, but I think we can do better. Perhaps the right solution here would be to have the "Page title" and the "Page tabs (Local tasks)" be added to the default core layouts OOTB (still in the existing "Top" region though - not a new one). I'm sure that existing sites would have already solved this issue manually if they needed things configured that way, so this will only happen for new installations. This would solve this bit:

> I think it's poor user experience to require everyone to make this change and sets a poor first impression of Backdrop CMS (out of the box) to find your breadcrumbs in such a strange position.

Having these blocks placed in the default core layouts OOTB would spare new users the additional clicks they'd have to otherwise perform, in order to add them themselves. All they'd need to do is to edit the layout (#3946 anybody 🙂), and move the blocks around, as per their desired page style.

**Comment by stpaultim** [comment]
I am aware that this is easy to resolve for a site builder familiar with Backdrop CMS. I'm thinking here only about the OOTB experience and first impressions. 

Your proposed solution is roughly what I had in mind for alternative option #2 and may very well be the better solution.

**Comment by klonos** [comment]
> ...and I feel like it's a huge OOTB improvement.

Oh for sure. That is the goal here 👍

**Comment by stpaultim** [comment]
Going to change title of this issue to focus less on one specific solution to the problem. We can achieve a better default layout in a number of different ways (see options above). Which is best solution?

![Your_first_post____Demo](https://user-images.githubusercontent.com/3144571/66273289-26e70e00-e838-11e9-91f3-114f02dd4fa4.png)

![Your_first_post____Demo](https://user-images.githubusercontent.com/3144571/66273336-9957ee00-e838-11e9-9b4f-8e5f0f9877b3.png)

Specific questions:

1) Is there any advantage in using the hard-coded page title block in layout templates vs overriding it with a movable page title block?
2) All core layout templates seem to have two regions above the basic content region, 'header' and 'top.' Is this enough for the best "out of the box experience"? It seems to me that a more sensible default layout might include a 'header', 'top', and 'title' region. Not wed to 'title' as name for this region, just looking for the ability to put things between the title and the header.

**Comment by olafgrabienski** [comment]
> It seems to me that a more sensible default layout might include a 'header', 'top', and 'title' region.

An additional region for one element feels like too much to me. I nearly always use the page title combo block. Would be nice if that could be the default.  (Not sure if there are caveats, though.)

**Comment by stpaultim** [comment]
Might this be a quick win for 1.15?

My PR just reorganizes the default layout on new sites to something that makes more sense to me. 

WAS:

![Your_first_post____PR_3030_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/71648012-4d480880-2cc4-11ea-86b3-f6b53c2395b2.png)

PROPOSED (In this PR):

![Your_first_post____PR_3031_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/71648023-82545b00-2cc4-11ea-9123-460d548fd24a.png)

**Comment by jenlampton** [comment]
> Backdrop out of the box starts with a page layout that puts breadcrumbs below the page title. This seems REALLY weird and unhelpful

I'm not sure this placement seems weird and unhelpful to everyone? I have a handful of sites that place the breadcrumb below the page title. 

<img width="1501" alt="Screen Shot 2020-01-01 at 6 44 56 PM" src="https://user-images.githubusercontent.com/397895/71649871-0b6c9180-2cc7-11ea-9887-1c073f33eade.png">

<img width="1492" alt="Screen Shot 2020-01-01 at 6 49 10 PM" src="https://user-images.githubusercontent.com/397895/71649997-03612180-2cc8-11ea-9caf-0b561a594457.png">

<img width="1501" alt="Screen Shot 2020-01-01 at 6 44 56 PM" src="https://user-images.githubusercontent.com/397895/71650000-065c1200-2cc8-11ea-94a9-a29dc68a5ae7.png">

<img width="1498" alt="Screen Shot 2020-01-01 at 6 50 50 PM" src="https://user-images.githubusercontent.com/397895/71650003-0825d580-2cc8-11ea-9763-98f3ef5c3886.png">

<img width="1496" alt="Screen Shot 2020-01-01 at 6 52 13 PM" src="https://user-images.githubusercontent.com/397895/71650006-0cea8980-2cc8-11ea-8144-26f81575c948.png">

Let's get some more feedback to see if everyone feels that above the title is a more common use-case?

**Comment by stpaultim** [comment]
@jenlampton - after our initial exchange on Gitter in which I very hastily stated that I couldn't imagine breadcrumbs below the title, I began to imagine the kinds of designs you are posting and realized how silly my statement was. 

The problem I'm trying to address is making Backdrop CMS easier to use "out of the box". I'm continually thinking about what a site builder or general user can achieve with Backdrop without creating a custom theme. When I open Backdrop out of the box, the breadcrumbs feel really out of place to me and without a significant redesign, I feel like they need to be moved. 

Your suggestion in Gitter to make this change specific to Basis would be totally acceptable to me. I just need to figure out how to do that. :-)

**Comment by oadaeh** [comment]
I definitely believe breadcrumbs belong above tabs. I even have a task to modify Basis (read: hack core) so that layout is the default for all our new sites.
As to whether they belong above or below the title or not, I don't have as strong of an opinion.
Breadcrumbs are navigation and represent a broader aspect of a website/page, where as the title is specific only to the current page that is being viewed. So with that in mind, I might prefer going down from the top of the page with more broad website elements to the bottom with more specific page elements, putting breadcrumbs above page title. But that's only what logically makes sense to me, and not necessarily what might make a good design layout.

**Comment by stpaultim** [comment]
I still think that we could easily make some very minor changes to our default settings that would make Backdrop CMS easier to use out of the box. I understand/appreciate the feedback that have been provided and would like to discuss this in a design/ux meeting to see if we can't agree on some minor changes that would move this issue forward - or decide against these changes totally and close this issue. 

I've added this to the [Design/UX agenda for 2020/07/30](https://docs.google.com/document/d/1X1YVtG3EzhXx9qpeLF3GNZtUmbt27s7NVuvLigL65hY/edit).

**Comment by oadaeh** [comment]
What Steve Krug says about breadcrumbs in his book Don't Make Me Think:

> Put them at the top. Breadcrumbs seem to work best if they’re at the top of the page, above everything. I think this is probably because it literally marginalizes them—making them seem like an accessory, like page numbers in a book or magazine. When Breadcrumbs are farther down on the page they end up contending with the primary navigation. Result? It makes me think. (“Which one is the real navigation? Which one should I be using?”)

However, he's advocating for them to be all the way at the top, above the site title, and I think that might be too much, but they definitely don't belong where they are in Basis.

**Comment by stpaultim** [comment]
I've updated this PR, the issue title, and the description in the original post. I've narrowed the focus of this PR and issue to ONLY address the positioning of breadcrumbs on the default layout AND only when using the standard install profile. This will only effect new sites. 

OLD:

![Your_first_post____Backdrop](https://user-images.githubusercontent.com/3144571/90294275-aa578f80-de4b-11ea-9f78-6e53d3e7b369.png)

NEW: 

![Your_first_post____Breadcrumbs_33](https://user-images.githubusercontent.com/3144571/90294384-e25ed280-de4b-11ea-9db7-f11f95bc40cb.png)

**Comment by jenlampton** [comment]
I think this change is a fine one, if several of you agree this is an improvement I have no objection :)

**Comment by stpaultim** [comment]
We discussed this in the last Design/UX meeting. @jenlampton raised a (small?) concern about the fact that this fix enables the Title Combo block instead of relying on the default title position in Backdrop Core. I understood the concern to be that there might be better systematic ways of fixing this issue. 

In my view, this PR is just about changing default settings and is not intended to fix problems with the way the title is rendered. I think that fixing problems with the way in which the page title is rendered would probably have to wait until Backdrop CMS 2.0 - and I don't think we want to wait that long to make this simple change.

**Comment by stpaultim** [comment]
I just discussed this with @quicksketch during the 1.17 sprint. He suggested that I not use the standard install profile, but that if I am going to make this change I do it in: core/modules/layout/config/layout.layout.default.json

This will still only effect new sites. 

Does anyone else have an opinion on this making this change?

**Comment by jenlampton** [comment]
> We discussed this in the last Design/UX meeting. @jenlampton raised a (small?) concern about the fact that this fix enables the Title Combo block

I've been thinking about this...

> Your suggestion in Gitter to make this change specific to Basis would be totally acceptable to me.

...and I have an idea!

The title is hard-coded in the template file for the layout. Why don't we override the template files for each layout in the Basis theme? Not only would this allow us to put the title where we want it witout placing additional blocks, but it would serve as a good example of how (contrib) themes should support all 10 core layouts. :)

**Comment by stpaultim** [comment]
> The title is hard-coded in the template file for the layout. Why don't we override the template files for each layout in the Basis theme? Not only would this allow us to put the title where we want it witout placing additional blocks, but it would serve as a good example of how (contrib) themes should support all 10 core layouts. :)

This sounds interesting to me, but I'll need more information. I may need to talk this through with you to fully understand the implications.

**Comment by quicksketch** [comment]
I'm not sure about this being a bug-fix candidate. Although it only affects new sites, it changes the default layouts quite a bit. I'd feel better about making this a 1.18.0 item.

**Comment by jenlampton** [comment]
This issue is only about moving breadcrumbs now, not the title?

I had an idea for an alternate approach, if we needed to move the title.
It's hard-coded in layout template files, but those can be overridden in
the theme. We could make this a basis-only change by adding theme overrides
for the layout template files.

**Comment by stpaultim** [comment]
@jenlampton - Isn't there a backward compatibility problem if we override this in the theme? Can we do it in the theme in a way that only effects new sites. 

My current approach only changes the layout for new sites. 

I will put this on the agenda for the next meeting. I'd like to figure this out for 1.18.0.

**Comment by jenlampton** [comment]
Based on today's meeting, I'd like to pursue moving only the breadcrumbs (not placing any other blocks). The Current PR seems to add the "title_combo" block as well as breadcrumbs. Is it possible to move the crumbs without adding the title combo block?

**Comment by cptX** [comment]
As a newcomer to Backdrop me too felt strange with the position of the breadcrumb and from the first moment I wanted to change it's position. Good thing is that it was relatively easy.
This is my visual result now 
![image](https://user-images.githubusercontent.com/9040042/108328785-ac712100-71d5-11eb-9741-c2b49be23472.png)
and I have achieved this with this block arrangement
![image](https://user-images.githubusercontent.com/9040042/108329188-cd397680-71d5-11eb-9bb8-14f1155d9e3d.png)

and just these three css modifications

.l-header {
	margin:0;
}

.l-top .block-hero {
	margin-top: 0;
}

nav.breadcrumb {
	margin-top: 0;
}

**Comment by stpaultim** [comment]
I'm reviewing old issues and ran across this one. I'm not sure how important this is to me anymore, because of my general frustration with Basis and the lack of consensus on how to fix existing CSS problems without breaking core. 

@jenlampton - Suggested a few things. Making this change in Basis, but I'm not sure how to do that in a Backward compatible way. 

She also asked if we can move the breadcrumbs without enabling the title_combo block. But, I don't know how to accomplish this AND I'm not sure why that is important. 

We are currently using the hard-coded "Title" which isn't a block at all. Does that provide any benefit? Why not enable the "Title Combo" block from the outset. It is my understanding that the fixed positioning of the title is a legacy from Drupal 7 anyway. 

By enabling the Title_Combo block from the outset, we make it clear to users that they can move the Title around as a block and we solve the breadcrumbs problem. 

I plan to bring this up once again in a Design/UX meeting to see if there is any more consensus on making this change now. 

Again, the current PR simply enables the Title_Combo block during installation and places the breadcrumbs above it. It does not effect any existing sites.

**Comment by stpaultim** [comment]
A user posted this comment on the Youtube page for the last Design/UX meeting:

> I expect the breadcrumb to be above the Page Title, and to duplicate the Page Title in the breadcrumb.  (And strangely I like the page edit under the page title, I think that is from my old AT Commerce Drupal 7 theme.) (https://www.youtube.com/watch?v=jMrY3xpyilc&lc=UgxrUUpdq0LXRkVvvN54AaABAg)

**Comment by klonos** [comment]
> We are currently using the hard-coded "Title" which isn't a block at all. Does that provide any benefit? Why not enable the "Title Combo" block from the outset. It is my understanding that the fixed positioning of the title is a legacy from Drupal 7 anyway.
> 
> By enabling the Title_Combo block from the outset, we make it clear to users that they can move the Title around as a block and we solve the breadcrumbs problem.

I'm thinking the same here @stpaultim 👍🏼  ...anything hard-coded requires more work, whereas if we mimic the current style using blocks, we make it easier for site builders to arrange the breadcrumb/title/tabs elements to their preference/needs via the convenience of the Block UI. Point is that we may never agree which order is the best to have OOTB, but if we allowed customization with as less effort as possible, then I think that would lead to better UX.

**Comment by klonos** [comment]
> Does anyone want to add this to the Milestone?

Well, this feels like a task rather than a feature request. As such, it could get in with a bug fix release. But it is currently labeled as a feature request, and these get implemented only in minor releases.

Now that I have read all comments in this thread since I last checked it, I feel up to speed and should be better prepared to talk about it during our next meeting.

**Comment by stpaultim** [comment]
> But it is currently labeled as a feature request, and these get implemented only in minor releases.

But, it also has the "Milestone Candidate - Bug" label. ;-)

**Comment by stpaultim** [comment]
Extensive discussion about this issue this week in Design/UX meeting. See: https://youtu.be/LSKK1f_Bu9s?t=1549

In my opinion the main blocker on this has been some reluctance/reservations about using the install profile to place the Title Combo block instead of the default Title Block that we have been using. 

It's my understanding that we have sufficient consensus to go ahead and give this a try. The reservations are not entirely gone, but there seems to be sufficient counter opinions that using the Title Combo block would be a better experience for new users and is worth trying. 

The point was made that we can easily reverse this change in the future if we get negative feedback.

**Comment by olafgrabienski** [comment]
> We get a "Works For Me" from someone

Works for me 👍

**Comment by jenlampton** [comment]
> Someone adds this to the 1.19.4 milestone

Done.

> Then we'll need a pretty simple code review

Done! I left one question in the PR, and recommend removing two empty lines. Other than that, RTBC!

**Comment by klonos** [comment]
I've also left a small comment re `[]`s breaking php5.3 tests - these should be replaced with `array()`s unless in .json files.

The PR could use a rebase as well.

**Comment by jenlampton** [comment]
> I've also left a small comment re []'s breaking php5.3 tests

Oh I missed that :( So glad you're here @klonos!

**Comment by stpaultim** [comment]
@jenlampton and @klonos - New PR pushed. 

@jenlampton suggested making better use of the variable for the Title_Combo_UUID which got me thinking that maybe I should create and use a variable for the Breadcrumb block as well, for better code understandability? Did that make sense or should I revert that change?

The UUID for the Breadcrumb block is already set in the core layouts.

**Comment by stpaultim** [comment]
There are three test failures. The first two appear unrelated to the PR, but the third one might be related. This PR moves the Title into a different region, which could be causing that third test to fail.  Anyone?

**Comment by stpaultim** [comment]
Here is where the title WAS in the mark-up prior to PR. 

![title-1](https://user-images.githubusercontent.com/3144571/133146966-5f370af7-0fef-4aea-8969-cc6e872fac7f.png)

Here is where it is now:

![title-2](https://user-images.githubusercontent.com/3144571/133147002-f1574fae-cb3c-450b-992e-e6955dc3ffee.png)

I believe that the test was failing because it was looking for the title in the `l-page-title` region and it is no longer there. It is now in the `l-top` region. So, I made this change to the test and it's now passing. 

![title-3](https://user-images.githubusercontent.com/3144571/133147216-bdc3332e-e5fd-453e-862b-0292b4672a36.png)

**Comment by stpaultim** [comment]
![title-4](https://user-images.githubusercontent.com/3144571/133147827-1dad4d9c-f7d1-4634-b04f-008caac37569.png)

:-)

**Comment by jenlampton** [comment]
nice job with the test failure fix!

**Comment by stpaultim** [comment]
That was fast. I've never gotten a code review in 12 seconds before. Nice work @jenlampton

**Comment by jenlampton** [comment]
It actually took 2 minutes, our comments cross-posted. The new PR looks great and was easy to review :D

**Comment by stpaultim** [comment]
I literally applied the "Needs Code Review" and then was immediately checking to see if I had done it correct and it was already RTBC. :-)

**Comment by quicksketch** [comment]
I found a slightly weird behavior caused by the current approach. The standard profile directly updates the config of the `layout.layout.default.json` config file, but it doesn't set the layout as overridden. This means that in the UI, it's still considered a "Default" layout out of the box:

![image](https://user-images.githubusercontent.com/100206/135378481-12b1abbb-57db-40d6-8c14-7a60f46fa7bf.png)

But if you make a change to the layout, save, and then revert it to the default, then the breadcrumb position returns below the title (the "real" default), rather than the way the layout was configured by the Standard install profile.

My preference is still to update the out-of-box `layout.layout.default.json` directly, as I don't think custom install profiles are a big concern for us compared to existing sites (which would be unaffected). However, if we're set on using the install profile to make this change, we should at least set the "storage" property to `2` (`LAYOUT_STORAGE_OVERRIDE`).

**Comment by stpaultim** [comment]
@quicksketch - Thanks for this feedback. It's useful. I'll have to go back and look at how this is working in core now, because I've been working under the impression that the install profile was the only safe way we could think of to do this. But, your comments make sense and I'm happy to try something else if we can do in a way that is compatible with old sites.

**Comment by stpaultim** [comment]
@quicksketch - I fixed this as you requested. 

@olafgrabienski and/or @jenlampton 

Can I get another test/review? 
Let's get this easy one out of the way.

**Comment by docwilmot** [comment]
This makes so much sense to me. Its still got a few genuine failures though.

**Comment by JSitter** [comment]
Tested in sandbox by adding subpage and tried in Bartik and Basis. Works for me.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/3693 into 1.x for 1.21.0! A big thank you for all the collaboration and discussion on this issue! Thank you @stpaultim, @jenlampton, @oadaeh, @docwilmot, @BWPanda, @klonos, @JSitter, @cpx, and @olafgrabienski!

**Comment by BWPanda** [comment]
I was literally reviewing this when @quicksketch merged it. I had some concerns about the tests, namely:

```php
    // Create a node page.
    $page_node = $this->backdropCreateNode(array(
      'type' => 'page',
      'title' => "Test node title",
    ));
    $this->backdropGet('admin/structure/layouts/manage/default');
    $this->clickLink(t('Remove'), 3);

    // Save the layout.
    $this->backdropPost(NULL, array(), t('Save layout'));
```

The get, link and post are all related, so I think they should be separated from the existing node creation by a blank line with no blank line/comment separating them. I'm also not sure what purpose they serve, so a comment describing this would be nice. E.g.:

```php
    // Create a node page.
    $page_node = $this->backdropCreateNode(array(
      'type' => 'page',
      'title' => "Test node title",
    ));

    // Describe what this does...
    $this->backdropGet('admin/structure/layouts/manage/default');
    $this->clickLink(t('Remove'), 3);
    $this->backdropPost(NULL, array(), t('Save layout'));
```

**Comment by quicksketch** [comment]
Thanks @BWPanda, sounds like a small change, would you be able to file a
followup PR using this same issue number?

**Comment by stpaultim** [comment]
Thanks to everyone that has helped on this! 

I've been looking forward to this very small, but helpful (IMHO) change for a long time.

**Comment by BWPanda** [comment]
@stpaultim Can you please describe the purpose of this:

```php
$this->backdropGet('admin/structure/layouts/manage/default');
$this->clickLink(t('Remove'), 3);
$this->backdropPost(NULL, array(), t('Save layout'));
```

**Comment by stpaultim** [comment]
@BWPanda - Actually, I'm not sure that I can. 

I was unable to fix this test, so I asked about it during Office Hours and I had a team of folks helping me. I believe that @klonos, @docwilmot, and possibly @hosef (or @bugfolder) were involved. 

For this part of the PR, I was simply typing what the others told me to type. Maybe one of them can better explain it.

**Comment by stpaultim** [comment]
@BWPanda - As I think about it some more, it had to do with moving the Page Title block to different positions and then testing to see if things were in the places that we expected them to be after moving the page title.

**Comment by klonos** [comment]
Yes, that pretty much sums it up @stpaultim 👍🏼 

@BWPanda IIRC, one or more assertions further down that code change were failing. We had 2 options: either adapt the tests with the new positions of the blocks, or remove the block that this change adds, which reverts things back to what the previous set of tests expect, and make sure that the tests still pass after that.

**Comment by BWPanda** [comment]
@quicksketch New PR to add comment to test code: https://github.com/backdrop/backdrop/pull/3916

**Comment by BWPanda** [comment]
PR merged into 1.x and 1.21.x.
