### ISSUE TITLE
For sites installed in sub-directories, the `Run database updates` link is incorrect

### ISSUE THREAD

**Issue by oadaeh** [backdrop/backdrop-issues#4117]
**Description of the bug**
For sites installed in sub-directories, the `Run database updates` link directs the user to a Page not found page and not to the Backdrop database update page.

**Steps To Reproduce**
To reproduce the behavior:
1. Install or move a site in a sub-directory of the HTTP server's root directory
2. Open any .install file
3. Add a new update function with something like `backdrop_set_message(t('This is a test.'));` or `watchdog('test', 'This is a test.');` in it
4. Clear the caches
5. Visit the Status report page at `/admin/reports/status`
6. Click the `Run database updates` link

**Actual behavior**
You are directed to a Page not found page.

**Expected behavior**
You are directed to the Backdrop database update page.

**Additional information**
The `database update script` link works correctly.

This is because the first link uses the `l()` function and also adds `base_path()` to the `core/update.php` path (which is added again via the `url()` function the `l()` function calls), but the other one is just uses `base_path() . core/update.php`.

A PR = https://github.com/backdrop/backdrop/pull/2924

**Comment by BWPanda** [comment]
@oadaeh Just to clarify, does this issue have anything to do with the `$base_url` setting in `settings.php`? I.e. was that set correctly  when the issue occurred? Does setting it fix the issue?

**Comment by oadaeh** [comment]
@BWPanda setting or not setting $base_url does not change the behavior.

The link was added in commit 0847278dea0f818689d38b80a149a09f6a1ae639.

**Comment by indigoxela** [comment]
@oadaeh that's a good catch. Of course, _l()_ and _url()_ already take care of the base path. No need to set it. Currently the base path is added twice, ending up with a wrong url.

Stripping base_path() is correct.

**Comment by quicksketch** [comment]
Thanks, this was a simple fix. Merged https://github.com/backdrop/backdrop/pull/2924 into 1.x and 1.16.x. Thanks @oadaeh and @indigoxela!
