### ISSUE TITLE
Core  Responsive Design with  Semantic HTML5 markup

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4128]
**Description of the need**
HTML5 brings a number of new elements to enhance the semantics of our web pages. The table below lists these new elements along with links to the spec and relevant articles on each.

**Proposed solution**
Templates and theme functions to use new HTML5 elements
https://www.drupal.org/node/1193054

**Additional information**
This provides support for HTML content to be passed to any theme function with the expectation that the HTML content will be render as DOM and not text.

We will start with theme_datetime and use this as the model for existing theme functions that do not support the render system (to be listed) and new theme functions (see above).

**Comment by klonos** [comment]
@domaingood can you please have a look at #200 and other HTML%-related issues in the queue, and identify what's missing that you would like to see implemented?

**Comment by domaingood** [comment]
@klonos HTML 5 is fine with backdroop But I dont see any HTML Semantic Elements Design with basic theme.Just need semantic markup.

https://www.freecodecamp.org/news/semantic-html5-elements/

**Comment by BWPanda** [comment]
Since we can't move forward with this without more info, and since more info hasn't been forthcoming, let's close for now. If @domaingood (or anyone else) is able to provide more info, please feel free to re-open.
