### ISSUE TITLE
JSON-LD module outputs schema.org markup

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4130]
Since the Schema.org list is huge, and growing, this module only provides a
small subset of those values, but it is designed to be extensible. Several types
are included which can be copied to add new types (groups) with any number of
their own properties. The current list of Schema.org top-level (entity) object types includes:

Schema.org/Article
Schema.org/Organization
Schema.org/Person
Schema.org/VideoObject
Schema.org/ImageObject
Schema.org/Event
Schema.org/Movie
Schema.org/TVSeries
Schema.org/TVSeason
Schema.org/TVEpisode
Schema.org/JobPosting
Schema.org/Recipe
Schema.org/HowTo
Schema.org/QAPage
Schema.org/FAQPage
Schema.org/Product
Schema.org/Service
Schema.org/Review
Schema.org/WebSite
Schema.org/WebPage
Schema.org/ItemList (for Views)
Many second-level properties are available to use on the above, including:

Schema.org/Action
Schema.org/Address
Schema.org/Brand
Schema.org/BreadcrumbList
Schema.org/Country
Schema.org/MonetaryAmount
Schema.org/NutritionInformation
Schema.org/Offer
Schema.org/OpeningHoursSpecification
Schema.org/Organization
Schema.org/Person
Schema.org/Place
Schema.org/ProgramMembership
Schema.org/Question
Schema.org/Answer
Schema.org/HowToStep
Schema.org/Rating
Schema.org/Review
It's fairly easy to add more properties to these types. To add properties that most users would want, like things that Google requires, provide a patch. To add properties that are specific to your own use case, you can create a custom module with any properties you want to add. The Article Example module shows how to do it.

**Additional information**
https://www.drupal.org/project/schema_metatag

**Comment by klonos** [comment]
This is a good candidate for porting to https://github.com/backdrop-contrib

**Comment by oadaeh** [comment]
I do not think this should be in the core issue queue.

Also, there is this module: https://github.com/backdrop-contrib/structured_data

**Comment by domaingood** [comment]
@oadaeh Thanks But [schema metatag](https://www.drupal.org/project/schema_metatag) made by Lullabot @quicksketch (Nate Lampton) company and more powerful JSON-LD module . Nate Lampton can easily ported to   Backdrop core.

**Comment by klonos** [comment]
@domaingood it seems that Lullabot is supporting https://www.drupal.org/project/schema_metatag, but they are not the maintainers of the project. The fact that @quicksketch happens to be working for that company does not make it that it falls to him to port the module. In fact Nate is one of our core committers, and I believe that it would be to our benefit if his focus remained in tasks related to Backdrop core.

As @oadaeh pointed, this is does not seem like it belongs in the core queue. The d.org project seems to have about 18k installations at this time, which compared to the 1mil+ Drupal installations is a very small usage percentage. I would start by porting the module to Backdrop, and adding it to https://github.com/backdrop-contrib

**Comment by jenlampton** [comment]
> I do not think this should be in the core issue queue.

> As @oadaeh pointed, this is does not seem like it belongs in the core queue.

That's correct, this is an issue about contrib. Please create an issue for the appropriate contrib queue, or in https://github.com/backdrop-ops/contrib if you would like to request a new port.
