### ISSUE TITLE
Backup file for flexible_template.png snuck into the code

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#4136]
The file `core/modules/layout/templates/flexible_template.png~` appears to be a backup copy of `flexible_template.png` that snuck in to the repository.

**Comment by quicksketch** [comment]
Sure enough. Doh! Thanks @jlfranklin, merged https://github.com/backdrop/backdrop/pull/2938 into 1.x and 1.14.x.
