### ISSUE TITLE
Password reset link

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4140]
The password reset link (e.g. `/user/reset/1/1571250190/TFjb_t-2GB3YIxkt2BPTu77ZsVNT0aq2eVptVMNnenk/login`) I believe should either:

- Not have the word `reset` in it (since it simply logs you in and takes you to the dashboard)
OR
- Should take you to the Edit page for your user profile (for resetting your password) instead of the dashboard
OR
- At the very least should include a message (in addition to the current "You have used your one-time log-in link and are now logged-in.") along the lines of: "Visit your user profile to reset your password."

**Comment by indigoxela** [comment]
@BWPanda hm... are you sure, things are like you described?

Following a reset link from an email, the very first thing a user sees is the password form.
After resetting it, an unprivileged user gets redirected to the start page and an appropriate message is shown. Admin users get redirected to the dashboard - _after_ they set their new password.

Or am I missing something?

**Comment by indigoxela** [comment]
Ah, wait, why does your reset link contain a "login" at the end? Mine don't.
I get:
`domain.tld/user/reset/[uid]/[the long hash]`

**Comment by BWPanda** [comment]
Ah ok. I was using the link provided by `drush uli` which I wrongly assumed was the same as password reset links, but I guess they're different...

**Comment by indigoxela** [comment]
This is how core user module builds the url: https://github.com/backdrop/backdrop/blob/1a01277bbf69c1120fdf34adf87be59e8aaf8028/core/modules/user/user.module#L1832

**Comment by indigoxela** [comment]
Drush adds the "/login" to the url, not Backdrop.
It does so in public function passResetUrl().

So I think this issue should get closed. Feel free to re-open it, if there are new findings.
