### ISSUE TITLE
Restore MAINTAINERS.txt?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4143]
We had [an issue in the b.org queue](https://github.com/backdrop-ops/backdropcms.org/issues/467) that included this, but since MAINTAINERS.txt this would be a core issue I'm copying the original request here:

From @oadaeh:

> Restore the MAINTAINERS.txt (or .md) file that lists all the modules and subsystems in Backdrop CMS and who has said they can and/or will be a point of contact for and help maintain that item. For items that have had multiple volunteers/maintainers step up, list them all. For items that have had no volunteers/maintainers step up, list them, too, without anyone's name (Drupal just uses a question mark).

**Comment by BWPanda** [comment]
I'm not sure... I can see the benefit of knowing who the maintainer is for a contrib project, but in core there are a lot more people who can answer questions, review PRs, commit code, etc. Do we even have specific maintainers for specific modules/features?

**Comment by jenlampton** [comment]
> Do we even have specific maintainers for specific modules/features?

Not right now, I don't think, but that is the end-goal.

I'm personally against a maintainers.txt because it's going to be hard to keep up to date in code, and will require time from core committers to do so. I'd rather have the information somewhere on backdropcms.org where anyone who's an editor can help keep it up to date.

**Comment by stpaultim** [comment]
I don't have strong feelings about this. We could have a maintainers.txt file that provides general information and links to page on backdropcms.org?

Just a thought. Again, I have yet to hear why someone thinks we need a maintainers.txt in core. I'm ready to be convinced.

**Comment by oadaeh** [comment]
I think the ideas @jenlampton and @stpaultim presented are perfectly fine: have a page on b.o that lists the information instead and make the MAINTAINERS.txt file simply point to that page.
Something else I think would be a good thing to include is a note about how to interact with those people, i.e., create an issue in the issue queue, don't contact them directly (so maybe not include their email addresses, but a link to the Backdrop issue queue).

The idea in having this is to let people know:
- Who has the keys to the code, i.e., who it is that can approve and/or commit changes to the code base
- Where gaps in maintainership are or might be (for later on when there are more people involved)
- Where there might be someone who might have too much on their plate and could use some help (also for when there are more people involved)
If I can see there are areas that are weak in maintenance or oversight, I can go to the issue queue and look specifically for issues in those areas to try to help solve them. At least that is what I have done in the past. We could even include directions to that effect in either or both of the file and the page.

I do understand, that there are only a few people who currently commit to core, and we aren't currently listing anyone who is a domain expert, but I expect that to change in the not too distant future, and having these things in place in advance makes it easier to keep up on them long term, and having them in place helps direct new people who might be looking for a place to fit in and help out.

**Comment by BWPanda** [comment]
I think it's agreed that having a list of contacts for parts of core code is better to be on B.org rather than in a text file in core itself. If we want to link from core to that B.org page, I think a line in the README file would suffice, rather than a whole new file.

Can we close this issue then?

**Comment by jenlampton** [comment]
Sounds good to me.
