### ISSUE TITLE
Contact form categories menu item generates error 

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4145]
**Description of the bug**
If on a fresh install of Backdrop CMS a user enables the contact form module and goes to 'admin/structure/contact/list,' they will get an error message:

```
Warning: Missing argument 1 for contact_category_list() in contact_category_list()
(line 166 of /core/modules/contact/contact.admin.inc).
Warning: Missing argument 2 for contact_category_list() in contact_category_list()
(line 166 of /core/modules/contact/contact.admin.inc).
```

**Steps To Reproduce**

To reproduce the behavior:
1. Spin up fresh installation of Backdrop CMS
2. Enable the contact form module
3. Go to Structure > Contact form > Categories
4. Observe error message

"Too few arguments to function contact_category_list(), 0 passed in /var/lib/tugboat/core/modules/system/system.module on line 2464 and exactly 2 expected"

**Additional information**

The problem seems to be that the form is trying to take the user to: /admin/structure/contact/list
I think that the user is just trying to get here: /admin/structure/contact/

I'm not sure if the original contact/list page exists or even needs to exist. 

I'm guessing this is an easy fix to this file: core/modules/contact/contact.module

![contact_module_-_backdrop-starter_-____Sites_lando_backdrop-starter_](https://user-images.githubusercontent.com/3144571/67135594-f2ccff00-f1e0-11e9-93fb-5ba38a244d38.png)

I thought about it some more and wondered if we need that link at all. Because, if the user clicks on the parent menu item "Contact form" they are taken to the categories page anyway.

![Contact_form___Fish](https://user-images.githubusercontent.com/3144571/67135710-1f354b00-f1e2-11e9-9798-786dcc457b03.png)

But, then I see that all the top level items under Structure have a sub-menu item that is "list," when the top menu item already takes you there. So, I guess we need to fix this Category link to be consistent. 

**We should probably also name it "List categories" to be consistent with the other menu items.**

- - - - - - - - -

PR by @stpaultim - https://github.com/backdrop/backdrop/pull/2942

**Comment by stpaultim** [comment]
Not that more info is needed, but I now see that for the other menu items under structure, the top level menu item and the 'list' item both have different paths but point to the same place. 

admin/structure/types
admin/structure/types/list

admin/structure/block
admin/structure/block/list

admin/structure/file-types
admin/structure/file-types/list

admin/structure/contact
admin/structure/contact/list (THIS JUST DOESN"T WORK)

**Comment by stpaultim** [comment]
I added a PR that does the following:

1) changes menu link from "Categories" to "List categories" 
2) changes

FROM:

```
$items['admin/structure/contact/list'] = array(
    'title' => 'Categories',
    'page callback' => 'contact_category_list',
    'access arguments' => array('administer contact forms'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
    'file' => 'contact.admin.inc',
  );
```

TO

```
  $items['admin/structure/contact/list'] = array(
    'title' => 'List categories',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
```

**Comment by olafgrabienski** [comment]
@stpaultim I've had a quick look at the PR's sandbox site, and it works for me. The name of the link to `admin/structure/contact/list` is "List categories", and the page is accessible.

**Comment by herbdool** [comment]
I see what you mean. I get same error on a fresh install of 1.14.1. But on a site that I updated from d7 (it's on 1.13.3). I don't see the same error. Odd.

**Comment by jenlampton** [comment]
code change looks straightforward, RTBC.

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2942 into 1.x and 1.14.x.
