### ISSUE TITLE
For contact module add path info on settings page?

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4146]
**Description of the need**
The contact module automatically creates a contact form at /contact. For some new users that do not know it, it may be difficult for them to find or understand what the path is for the contact form. 

There is a link in the text on /admin/structure/contact to the contact form, but I overlooked this link in a recent attempt to remember what the path was. 

**Proposed solution**
Maybe make the text a bit more explicit. 
WAS:

```Configure the categories shown in the [site-wide contact form](https://backdropcms.org/contact) here.```

PROPOSED:

```Configure the categories shown in the [site-wide contact form](https://backdropcms.org/contact) found at /contact.```

![Contact_form___Demo](https://user-images.githubusercontent.com/3144571/67136143-e5ffd980-f1e7-11e9-835c-863f1865ca91.png)

This is easy enough, I'll try to submit a PR in case anyone else thinks this is a good idea.

- - - - - - -

PR by @stpaultim = https://github.com/backdrop/backdrop/pull/2941

**Comment by stpaultim** [comment]
I am not sure if this is a good idea or necessary, but I find it a helpful clue. I believe that on more than one occasion, I've struggled (a tiny bit) to remember or try to figure out where the contact page is located (which path). 

![Contact_form___Demo](https://user-images.githubusercontent.com/3144571/67152293-8c0b1c80-f298-11e9-9eff-e0ffc9cf7f1c.png)

**Comment by stpaultim** [comment]
At @olafgrabienski suggestion, I made this small change:

![Contact_form___PR_2941_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/67359332-9cd1c180-f528-11e9-90ac-368c5639337a.png)

**Comment by olafgrabienski** [comment]
Works for me in the sandbox!

**Comment by klonos** [comment]
Sorry for taking so long to review this @stpaultim 😓 ...RTBC 👍

I don't see this as a new feature; it is a task about fixing the UI text and can go into any bug fix release.

**Comment by quicksketch** [comment]
We made this change somewhere else recently... I can't recall where though. However instead of using a relative URL like `/contact`, we printed out the entire full URL such as `https://your-site-name.com/contact`. Would that be preferable here for clarity?

**Comment by klonos** [comment]
> ...we printed out the entire full URL

That's what this PR does 😉 (@stpaultim implemented this after @olafgrabienski suggested it): https://github.com/backdrop/backdrop/pull/2941#pullrequestreview-304410235

**Comment by klonos** [comment]
@stpaultim can you please close/re-open the PR to refresh the sandbox? It currently is not working.

**Comment by quicksketch** [comment]
@klonos The current code uses a relative path like `/contact`. The current placeholder is:
```
array('!url' => url('contact'))
```

To be absolute it would specify it as:
```
array('!url' => url('contact', array('absolute' => TRUE)))
```

**Comment by quicksketch** [comment]
Well I don't feel the need to hold this up over including the full URL, just the path is definitely an improvement over the ambiguous link from before. I've merged https://github.com/backdrop/backdrop/pull/2941 into 1.x and 1.16.x. Thanks!
