### ISSUE TITLE
Fix _config_name for `system.core` default config file

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4147]
The default config file in system module `system.core.json` includes the line:
```
"_config_name": "system.performance",
```

We should probably correct this to 
```
"_config_name": "system.core",
```

**Comment by AromaR** [comment]
I just checked the main branch and name is system.core. This can be closed?

**Comment by jenlampton** [comment]
> This can be closed?

Yes, thank you! 
I'll invite you to the documentation team so you have access to manage the issues.

**Comment by stpaultim** [comment]
@AromaR Thanks!

**Comment by klonos** [comment]
FTR, fixed with https://github.com/backdrop/backdrop/commit/131c1b102bba97ed6470a63ac9836cf1d311fc40#diff-cc5eaca5ac6bc453bd73e2a694dbc8ef86908613023f07b561234fedfccb533e (in #4591)
