### ISSUE TITLE
Remove duplication in `install.sh`

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4149]
[`install.sh`](https://github.com/backdrop/backdrop/blob/1.x/core/scripts/install.sh) has a duplicated `site-name` [array key](https://github.com/backdrop/backdrop/blob/1.x/core/scripts/install.sh#L51).

We should remove it.

**Comment by indigoxela** [comment]
That's an easy and straightforward fix. One time should be sufficient :wink:

**Comment by BWPanda** [comment]
I feel this is a small enough change that we don't need anymore eyes on this, so I've gone ahead and merged https://github.com/backdrop/backdrop/pull/2944 into 1.x and 1.17.x. Thanks for the help @indigoxela!
