### ISSUE TITLE
[BC] Call to undefined method stdClass::id() in file.field.inc

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4150]
I've seen this error a few times on several of my sites, but I have not yet been able to track down the cause. 

I'm opening this issue to post my hot-fix incase others are suffering from the same problem.

I'm not yet convinced we should merge this solution into core, but here are my arguments to do so:

* In Drupal 7, entities were stdClass. 
* stdClass entities did not have `->id()` methods. 
* Many entities used the property 'id' as a property.

If we added this code, we'd be saving people some headaches if a contrib project was not properly (or entirely) ported from D7 to Backdrop. 

---

PR: https://github.com/backdrop/backdrop/pull/2945

**Comment by indigoxela** [comment]
I'm curious, does this problem occur on plain Backdrop installs, or are contrib modules involved.

I'm asking because this happened to me, while trying to reproduce another issue: https://github.com/backdrop/backdrop-issues/issues/4170#issuecomment-548286895

**Comment by jenlampton** [comment]
I'm getting it on a lot of backdrop sites with various different collections of contrib modules. Once I think I've found the contrib module that's causing the problem and fix it, this error crops up on another site with different modules. 

I still think we should include a backwards-compatible fix so that sites aren't broken because of a core change we made -- even if the "correct" fix would be to update the contrib modules to match.

**Comment by herbdool** [comment]
@jenlampton what's the best way to test this? Which contrib modules were broken before?

**Comment by jenlampton** [comment]
@herbdool I believe I ran into it with multifield, nodequeue, and metatag. 

I'm [positive about multifield](https://github.com/backdrop-contrib/multifield/issues/32) but I'll check some sites patch docs to confirm  the others.

**Comment by herbdool** [comment]
I've tested. I'm leaning towards just fixing this in multifield and any other modules which need to implement this properly.

Even with this patch I get two errors. I created a multifield that contained an image field on the page content type. When updating a node I still get:

`Notice: Undefined property: stdClass::$original in file_field_update() (line 284 of /app/core/modules/file/file.field.inc).`

And when creating a new node I still get:

`Error: Call to undefined method stdClass::id() in file_field_insert() (line 236 of /app/core/modules/file/file.field.inc).`

**Comment by jenlampton** [comment]
> better to just create a new beta release there

If it were a PHP notice or something less serious I might agree that we could say its contrib's fault for not coming out with a new release the same day core made the API change. But in this case the error is fatal, and it was caused by core change we made mid-cycle.  We shouldn't be doing that.

**Comment by herbdool** [comment]
Seems like a bit of an edge case all the same. If I'm correct it's where there's an entity type which wasn't set up properly in Drupal 7 and has field types which are expecting a method which doesn't exist. (I assume this issue of combining these two modules was also an issue in Drupal 7).

But if the consensus is to put in a temporary fix in the file_entity module, then perhaps using `entity_extract_ids` https://api.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.module/function/entity_extract_ids/1 might be a better option to add to each hook: `hook_field_insert`, `hook_field_update`. `hook_field_delete`, `hook_field_delete_revision`.

**Comment by herbdool** [comment]
But even that fix doesn't address this error `Notice: Undefined property: stdClass::$original in file_field_update() (line 284 of /app/core/modules/file/file.field.inc).`. I assume that having the entity properly set up handles all this.

**Comment by jenlampton** [comment]
Because this issue is now fixed in multifield, I don't think we need this core fix anymore. I'm going to remove the patch from my sites and see if the problem reoccurs. 🤞

**Comment by klonos** [comment]
Hey @jenlampton when you have some time, can you please confirm if this was fixed indeed, and if so then perhaps also close the PR? (and remove the irrelevant labels too while at it)

Thanks.
