### ISSUE TITLE
Disable comments by default on NEW content types

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4156]
**Description of the need**
Most new content types do not need comments, but the default setting is turned to "on." I almost always forget to turn off comments, until I create a node and then have to go back and first turn them off on the content type, then go back and turn them off on that particular node. 

**Proposed solution**
Change the default setting for comments to "OFF" for new content types. 

**Additional information**
I think it's good that we have comments turn on for the default "Post" content types, because that reminds users that comments are available for them to be turned on. But, I don't think we need to have them on for ALL new content types. 

I don't feel strongly about this change, but it came up in a discussion with @Radcliffe and I'm curious what others think.

- - - - - - - - - 
PR by @stpaultim = https://github.com/backdrop/backdrop/pull/3029

**Comment by laryn** [comment]
Agree.

**Comment by alanmels** [comment]
Have to admit I had exactly the same experience of going back to content types to turn comments off many times. So I also support the suggestion.

**Comment by domaingood** [comment]
Agree too

**Comment by stpaultim** [comment]
We talked about this on the last weekly dev call and there seemed to be support for this proposal. The PR is a one word change. https://github.com/backdrop/backdrop/pull/3029

I expected this to break some tests, but it didn't. Does that suggest a need for better coverage?

This will change the behavior of new content types on existing sites, but should not effect any existing content types. I assume that is not a problem.

Am I forgetting anything?

**Comment by olafgrabienski** [comment]
I agree as well, great idea! To test the PR; I've had a look at the sandbox website, checked if *Posts* have still open comments by default (yes), created a new content type called "News" and checked if the default comment setting for new content of this content type is "Closed comments" (yes). So, the PR works for me!

**Comment by herbdool** [comment]
Code looks good.

**Comment by quicksketch** [comment]
Love it. I have to change this setting during every training workshop when setting up new content types (and frequently forget). I've merged https://github.com/backdrop/backdrop/pull/3029 into 1.x for 1.15.0. With this being a change in behavior and 1.15 right around the corner, I'm not pulling this into 1.14.x.
