### ISSUE TITLE
[UX] Add 'Empty Paragraph Killer' feature to core

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4157]
The [Empty Paragraph Killer](https://www.drupal.org/project/emptyparagraphkiller) module for Drupal 7 is a very simple module that filters out empty paragraphs (i.e. subsequent line breaks).

So this:
```
One paragraph



Two paragraph
```

Becomes this:
```
One paragraph

Two paragraph
```

As such a [simple module](https://git.drupalcode.org/project/emptyparagraphkiller/blob/7.x-1.x/emptyparagraphkiller.module) I thought it might be nice to have in core (maybe as a checkbox setting in the existing 'Convert line breaks into HTML' filter). Thoughts?

**Comment by oadaeh** [comment]
What happens when people want the extra space? Sometimes, that's intentional.

**Comment by BWPanda** [comment]
Then they disable it I guess 🙂

**Comment by oadaeh** [comment]
As long as that option remains, and it isn't assumed that everyone will just want and use it, then sure.

**Comment by BWPanda** [comment]
Mmm, fair enough. I might port it to contrib instead then.

**Comment by klonos** [comment]
...given the simplicity of the code, I wouldn't mind it if this was added into core, but disabled by default for new text formats.
