### ISSUE TITLE
XSS filter mangles title and alt attributes

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#4158]
**Description of the bug**
When I add a colon (`:`) in an `alt` or a `title` attribute of an image through CKEditor, the content before the colon is stripped.

This happens also at other places. I noticed the same issue with `title` attributes in links of the *Footnotes* module.

**Steps To Reproduce**
To reproduce the behavior:
1. Create a post.
  (Leave *Filtered HTML* as Editor.)
2. Add an image to the post through CKEditor.
3. Add an `alt`attribute which contains a colon to the image, e.g. `alt="Image: Dummy"`.
4. Save the post and have a look at the result with a browser inspector.

**Actual behavior**
`<img alt=" Dummy" (...) />`

**Expected behavior**
`<img alt="Image: Dummy" (...) />`

There is a fix for Drupal 8 and a working patch (RTBC) for Drupal 7. See *Related issues* below.

**Additional information**
- Backdrop version: 1.14.1

**Related issues**
- https://github.com/backdrop/backdrop-issues/issues/1201 (Backdrop, Image captions, fixed)
- https://www.drupal.org/project/drupal/issues/2105841 (D8, fixed)
- https://www.drupal.org/project/drupal/issues/2859006 (D7, RTBC)

---

PR by @olafgrabienski : https://github.com/backdrop/backdrop/pull/2959

**Comment by bobchristenson** [comment]
Confirmed this in my installation as well.  It seems to only happen with Filtered HTML...if you switch to Full HTML it doesn't remove the text.  I suspect it has something to do with the 'filtered tags' input filter configuration.

**Comment by olafgrabienski** [comment]
On a test site, I've applied the D7 patch from https://www.drupal.org/project/drupal/issues/2859006#comment-12865639 manually. That fixes the issue regarding images and *Footnotes* for me. I'm however not sure if it's a good approach for Backdrop and if or how it should be adapted to Backdrop. We should probably also compare the D7 fix with the Backdrop fix for image captions: https://github.com/backdrop/backdrop/pull/1067/files

**Comment by olafgrabienski** [comment]
> We should probably also compare the D7 fix with the Backdrop fix for image captions

I've created a quite simple pull request which extends the [Backdrop fix for image captions](https://github.com/backdrop/backdrop/pull/1067/files) instead of applying the more complex [D7 patch](https://www.drupal.org/project/drupal/issues/2859006#comment-12865639).

@bobchristenson Are you maybe up to test the PR and to verify if it fixes the issue?

**Comment by olafgrabienski** [comment]
The mentioned D7 patch adds some tests. Do we need (some of) them as well?

I've absolutely **no** experience with tests, so in case we need to add tests, I'd need assistance.

**Comment by indigoxela** [comment]
I've been testing this PR on a fresh 1.15.x-dev. It works fine.

I've added an image with an alt attribute containing a colon and a link with a title attribute containing a colon to a node content.

Without this patch, the attributes get mangled, with this patch applied, both attributes stay intact.

**Comment by olafgrabienski** [comment]
@indigoxela Thanks for testing the PR, much appreciated! What do you think of the approach in comparison to the more complex D7 patch mentioned in https://github.com/backdrop/backdrop-issues/issues/4158#issuecomment-547861397?

**Comment by indigoxela** [comment]
> What do you think of the approach in comparison to the more complex D7 patch

Personally, I prefer the simpler approach wherever possible.

I admit, I don't fully understand that Drupal patch. It seems to create a new (more permissive) filter function, but only uses it in the test... :confused: 
But I didn't dig deeper there...

**Comment by klonos** [comment]
> Personally, I prefer the simpler approach wherever possible.

Yup, I'm all for that too, but we also need to keep backwards compatibility with D7, and (where possible) also feature parity with D8. Besides, if/when the D7 patch gets committed, we'd need to implement the same changes, in order to come to code parity (the introduction of the `filter_xss_data_attributes()` function basically). So, if we are to do that in the long run, might as well do it now.

@olafgrabienski are you up to file a second, alternative PR, that applies the same fix as D7/D8? If that also fixes the issue, then I think we should go with that one instead.

My 2c.

**Comment by indigoxela** [comment]
@klonos your feedback is always welcome.

Regarding the D7 patch: do you understand the purpose of that filter_xss_data_attributes() function?
It's only used in the tests, but nowhere in common.inc. Attribute alt and title are just skipped, like @olafgrabienski's much simpler PR does.
Or am I missing something?

**Comment by olafgrabienski** [comment]
> I'm all for that too, but we also need to keep backwards compatibility with D7, and (where possible) also feature parity with D8.

@klonos Don't you think my PR is backwards compatible? It has the same result as D8 (or D7 patched) even if accomplished in a slightly different way. Same question regarding feature parity: Is there a feature missing?

> if/when the D7 patch gets committed, we'd need to implement the same changes, in order to come to code parity

@klonos I saw you ported a lot of D7 fixes to Backdrop, so you may know better than me. Actually, I don't know much of the details, but I suppose many crossports were fixes that hadn't been fixed in Backdrop before. In my understanding, the goal of these ports wasn't code parity but compatibility and feature parity. Code parity per se doesn't make sense, does it?

**Comment by olafgrabienski** [comment]
> are you up to file a second, alternative PR, that applies the same fix as D7/D8?

@klonos Yes and no! Sure, it wouldn't hurt to also have the D7 patch as a PR, but I'm short of time for a while. (However, some time ago I've applied the D7 patch manually on a Backdrop site, and it worked for me.) Can you maybe make the D7 approach PR? If so, please consider that my PR extends the [fix for image captions](https://github.com/backdrop/backdrop/pull/1067/files) by @quicksketch. I guess for the D7 approach that fix has to be reverted.

**Comment by klonos** [comment]
> Can you maybe make the D7 approach PR?

Surely can do. ...and I will make sure that the fix for captions is included.

Re the feature/code parity, I was merely referring to the existence of a function in D7, which will not be available in Backdrop (`filter_xss_data_attributes()`). I understand that it may only be used in tests at the moment, but we cannot be sure what it can be used in the future for contrib/custom modules. If we don't include it (as a cross-port), then we will need to deviate, and most likely provide a wrapper function to denote it as deprecated.

**Comment by olafgrabienski** [comment]
@klonos Thanks for your PR at https://github.com/backdrop/backdrop/pull/3002 (wasn't aware that you had already made it). I've had a look at the sandbox site of your PR. It seems that the issue isn't fixed there.

Expected behavior:
`<img alt="Image: Dummy" (...) />`

Actual behavior:
`<img alt=" Dummy" (...) />`

Looking at the code, I saw that you've added the test part but didn't change `common.inc` so far. Were you still planning to work on `common.inc`?

**Comment by jenlampton** [comment]
Code change looks simple and straightforward. RTBC from me.

**Comment by quicksketch** [comment]
Thanks! Yeah our fix seems a bit simpler. We already ran into (and fixed) this particular problem for `data-` attributes, which is still affecting Drupal 7. Amending our fix to also apply to alt and title looks perfect.

Merged https://github.com/backdrop/backdrop/pull/2959 into 1.x and 1.14.x. Thanks!
