### ISSUE TITLE
Views utility function gives Drupal instructions

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4159]
**Description of the bug**
There are [a few lines in the Views utility function file](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/includes/utility.inc#L22-L34) that specify in an error/watchdog message:

> Verify the class file has been registered in the corresponding .info-file (files[]).

Should this be changed to language about `hook_autoload_info` instead?

**Comment by stpaultim** [comment]
If this recommendation is correct, this could be a good first issue. If you can confirm that this text change should happen, the please add the "Good First Issue" tag.

**Comment by laryn** [comment]
From https://docs.backdropcms.org/converting-modules-from-drupal

> In Backdrop the class registry has also been removed and replaced with a static class map (see the related change record). This means that you'll need to remove any lines in your info file that define files containing PHP classes: files[] = whatever.inc. To have this class loaded you'll need to implement hook_autoload_info() in your module file instead.

> The exception is test classes. The .test files are loaded with a .tests.info file and not listed in hook_autoload_info(). For example: files = menu_import.test. Read more in next section...

**Comment by bugfolder** [comment]
This looks like https://github.com/backdrop/backdrop-issues/issues/1559, which has a pending PR.

**Comment by laryn** [comment]
Good catch. And I just put the milestone on that one :sweat_smile:
