### ISSUE TITLE
SQL fatal an PHP Notice: Undefined variable: id in file_field_update()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4170]
After upgrading to 1.14, I'm getting the following PHP notice when removing, and then adding a new image to an existing multifield (to an image subfield). 

```
Notice: Undefined variable: id in file_field_update() (line 292 of backdrop/core/modules/file/file.field.inc).
```
I'm also seeing the following SQL fatal:
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null
```

There may be an oversight here:
```php
  // Add new usage entries for newly added files.
  foreach ($items as $item) {
    if (!in_array($item['fid'], $original_fids)) {
      if ($file = file_load($item['fid'])) {
        file_usage_add($file, 'file', $entity_type, $id);
      }
    }
  }
```
Shouldn't this `$id` be `$item['fid']` instead?
```php
  // Add new usage entries for newly added files.
  foreach ($items as $item) {
    if (!in_array($item['fid'], $original_fids)) {
      if ($file = file_load($item['fid'])) {
        file_usage_add($file, 'file', $entity_type, $item['fid']);
      }
    }
  }
```

---
PR: https://github.com/backdrop/backdrop/pull/2958

**Comment by indigoxela** [comment]
@jenlampton I was trying to reproduce the error, but am not able yet.

I cloned a fresh Backdrop and installed.
I created a new content type, with an unlimited image field. Added an image, saved, edited again, removed that image, added a new one, saved.
No notice so far, nothing in dblog.

Could you provide more details, how to reproduce the error?

**Comment by jenlampton** [comment]
Nice catch @indigoxela -- if you see something like this feel free to add the label `pr - needs work`

**Comment by jenlampton** [comment]
Here's the related issue: https://github.com/backdrop-contrib/multifield/issues/32

I'm still seeing the error `Call to undefined method stdClass::id() ` on backdrop 1.15.0-preview after the removal of `entity_create_stub_entity()` **without** the patch from that issue, but with it everything works as expected. 

Closing this issue.
