### ISSUE TITLE
[UX] Rename the file "Description"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4178]
There are several places in the UI where we refer to the thing we call a file as a file `Description`. The help text on this field explains what it is really used for: `This description will be used as the text in links to the file.`

I'd like to rename this to something that better conveys what it actually is. Suggestions?

Ideas:
* Text for the link to the file 
* File Label
* File Display name
* File Description
* File Title

Here are some places where we can see the text:

1) when managing the file 
<img width="1208" alt="Screen Shot 2019-10-30 at 1 55 35 PM" src="https://user-images.githubusercontent.com/397895/67898682-056b0080-fb1e-11e9-83c3-8c379529d12c.png">
or
<img width="1184" alt="Screen Shot 2019-10-30 at 1 37 26 PM" src="https://user-images.githubusercontent.com/397895/67898591-cfc61780-fb1d-11e9-8ada-ed4ff65d32b6.png">

2) when adding a file into a field
<img width="1182" alt="Screen Shot 2019-10-30 at 1 37 03 PM" src="https://user-images.githubusercontent.com/397895/67898656-f2583080-fb1d-11e9-93b0-526bee8c4d68.png">

3) When allowing the value to be set on a file field
<img width="1186" alt="Screen Shot 2019-10-30 at 1 36 40 PM" src="https://user-images.githubusercontent.com/397895/67898668-fd12c580-fb1d-11e9-852a-941debbf2c2f.png">

---

PR: https://github.com/backdrop/backdrop/pull/2961

**Comment by olafgrabienski** [comment]
> Text for the link to the file

What about "Link text"? We use that in the "Insert Link" dialog (which can also link to files if enabled in the text format settings).

**Comment by klonos** [comment]
I usually refer to the "label" as "File name", and the actual name of the file in the filesystem as "filename", but I see how "File description" can be better ...or even "File label".

I like "File display name", but would prefer it if we avoided the word "name". How about "File display title"?

**Comment by jenlampton** [comment]
> I usually refer to the "label" as "File name", and the actual name of the file in the filesystem as "filename",

Me too, but this gets confusing. Especially when saying it out loud!

> that is limiting to only when that "thingy" is rendered as a link.

And the link text is only when the link is to the file, the name/title/label text would also often be a linked to the file/FID pages.

> How about "File display title"?
Let me give that a go...

**Comment by jenlampton** [comment]
Here are some screenshots using `File display title`:
<img width="1208" alt="Screen Shot 2019-10-30 at 1 55 35 PM" src="https://user-images.githubusercontent.com/397895/67903009-bd50db80-fb27-11e9-9063-07b643f4c026.png">
<img width="842" alt="Screen Shot 2019-10-30 at 3 11 53 PM" src="https://user-images.githubusercontent.com/397895/67903014-c0e46280-fb27-11e9-9a87-12dc38931134.png">
<img width="1179" alt="Screen Shot 2019-10-30 at 3 12 03 PM" src="https://user-images.githubusercontent.com/397895/67903017-c3df5300-fb27-11e9-95b5-3110e3e00974.png">

**Comment by klonos** [comment]
Not because I suggested it 😅, but I think we have a winner!

**Comment by klonos** [comment]
RTBC! 👍

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/2961 into 1.x and 1.14.x.
