### ISSUE TITLE
Request to add a link to project pages for modules on Functionality page

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4179]
**Description of the need**

While reviewing the list of modules, I sometimes need to quickly jump to certain module's project page. However quick can be constructing the project page's URL in the address bar, it takes  valuable seconds anyway. Some project names are crazy long, as for example, of https://www.drupal.org/project/db_export_edit_mysql_row_as_text_and_import, so you have to first find the project page and then copy-paste it's URL.

**Proposed solution**
I propose to enhance usability of Backdrop's Functionality page and introduce a new `Project Page` link in the drop-down section of each module's Operations column as shown on the screenshot:

![project_page](https://user-images.githubusercontent.com/56604405/67945584-53e8cf80-fbf0-11e9-8e16-4b8e959363d4.jpg)

**Comment by alanmels** [comment]
Whether such a hypothetical Project page link should be linked to respective project pages on https://backdropcms.org/project or https://github.com/backdrop-contrib is debatable. Because from (1) one hand the https://backdropcms.org/project seems right, because projects pages there have the links to respective GitHub pages anyway, however (2) on the other hand I don't like the fact the list of projects on https://backdropcms.org is limited to only released projects. Why not to make https://backdropcms.org/project to list all projects including those which have only development branches? OR should this be filled as a separate feature request?

**Comment by laryn** [comment]
I like this idea (e.g. if researching newer releases, etc. to be able to jump over to the project's info page quickly). I can see arguments both ways for where to link to.

 - Backdropcms.org/project seems more invitational for non-developers. 
- Github solves the issue of development releases having links, and also provides an easy way to look at past releases, issue queue, and wiki.

**Comment by oadaeh** [comment]
If this were to gain traction, I would think that the best course of action would be to add a new key-value pair in the .info file where the project maintainers can specify the URL where that link should point to (like the 'configure' key). That way, core doesn't have to try to guess what the correct path is, and the project's maintainer can choose whether to direct the user to backdropcms.org or to github.com.

**Comment by alanmels** [comment]
If consensus will be not to squeeze too much info into the drop-down menu for each project, also taking into account that some projects do not have drop-down menus at all, we could place additional links in the description part like so:

<img width="1037" alt="Screen Shot 2019-10-31 at 8 02 29 PM" src="https://user-images.githubusercontent.com/56604405/67969058-82c76b80-fc19-11e9-9e08-624c285d6222.png">

**Comment by klonos** [comment]
I was about to comment the other day; kept the browser tab open, but forgot to get back to it. ...I am not opposed to this; having that information available without having to navigate away from the current page is a welcomed UX. Here's some feedback to consider:

I agree that this should not be in the dropbutton, as that is reserved for actions, rather than opening new external pages.

Keep in mind that in the Project Browser, we already have this sort of functionality, which opens an info popup:

![Screen Shot 2019-11-02 at 11 38 24 am](https://user-images.githubusercontent.com/2423362/68063470-61739600-fd65-11e9-90e8-66ecc0330d84.png)

Perhaps we can reuse that?

**Comment by alanmels** [comment]
@klonos, good to know, thanks! So project browser provides links to project pages for not-yet-installed modules. Now let's think what should we do with the projects that have already been installed? Would be nice to have some quick links for them too.

**Comment by klonos** [comment]
Of course @alanmels ...was just saying that we should look into reusing the code that does that for the Project Browser, and have the same UI pattern (links, that when clicked open a dialog).

**Comment by BWPanda** [comment]
This feature has since been added in https://github.com/backdrop/backdrop-issues/issues/5003. Sorry we didn't find this existing issue before opening a new one.
