### ISSUE TITLE
[UX] Automatically focus username field on login page

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4183]
**Description of the need**
It's annoying when you click the 'Login' link in Backdrop, and then after the login page loads have to click in the Username field before you can enter your credentials.

**Proposed solution**
It'd be nice if the 'Username' field received focus automatically when the page loads (i.e. click 'Login', page loads, type username, tab, type password, enter).

**Alternatives that have been considered**
Apparently it's in Drupal... https://www.drupal.org/project/drupal/issues/20446

**Comment by alanmels** [comment]
Nice one, I second it.

**Comment by BWPanda** [comment]
Made a PR: https://github.com/backdrop/backdrop/pull/3216

**Comment by olafgrabienski** [comment]
Nice thing, works for me in the sandbox.

One question btw: autofocus fields like this one or the title field in the node edit form prevent me from using the keyboard (`Cmd` + left arrow) to go back to the previous page. Do you know of a way to preserve such keyboard actions?

**Comment by BWPanda** [comment]
@olafgrabienski I'm not sure... I just tried on my computer (Linux) and it's Alt + Left/Right for me. It works fine both with and without the autofocus.

**Comment by olafgrabienski** [comment]
Interesting, seems to be an Mac OS issue then. Thanks for checking!

**Comment by klonos** [comment]
> Included autofocusing the username field on the password reset form too, as that seems to make sense as well.

Agreed 👍  ...can we please do the same on `user/register` as well?

**Comment by BWPanda** [comment]
I was going to do the registration form too, but its the same form as the user edit form, and I don't see a need to automatically focus on the username field when editing your user account (how often do people edit their account to change their username? Not much me thinks)

**Comment by klonos** [comment]
> ... but its the same form as the user edit form, ...

Couldn't we use `user_is_logged_in()` or something, and have autofocus when that's `FALSE`? Something like:

```php
    '#attributes' => array(
      'autofocus' => user_is_logged_in() ? 'autofocus' : '',
    ),
```

**Comment by klonos** [comment]
...scratch that: https://stackoverflow.com/questions/4445765/is-it-autofocus-autofocus-or-autofocus

> The absence of the attribute is the only valid syntax for false

So it'd have to be a conditional that adds `autofocus` outside the form element:

```php
if (user_is_logged_in()) {
  $form['name']['#attributes']['autofocus'] = 'autofocus';
}
```

**Comment by BWPanda** [comment]
@klonos Done. There was even an existing `$register` boolean variable I was able to use.

**Comment by klonos** [comment]
Thanks @BWPanda simply code changes, and it works as advertised in the PR sandbox. RTBC 👍

**Comment by klonos** [comment]
This is not a new "feature", rather than a UX improvement. It can go in on the next bug fix release.

**Comment by klonos** [comment]
...let's follow process, and have someone else add the actual milestone 😉

**Comment by klonos** [comment]
@BWPanda if I could bring your core committer attention to the related #4524 😅 ...while testing this PR here, it was annoying to have to double-tab to get to the password field, after having used to a single tab over all these years.

**Comment by BWPanda** [comment]
Thanks @olafgrabienski for the test and @klonos for suggestions and testing. Merged https://github.com/backdrop/backdrop/pull/3216 into 1.x and 1.16.x.
