### ISSUE TITLE
EntityDatabaseStorageController::create() should require entity class

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4187]
**Description of the bug**
```
public function create(array $values) {
  $class = isset($this->entityInfo['entity class']) ? $this->entityInfo['entity class'] : 'Entity';
  return new $class($values);
}
```
This implies that if `$this->entityInfo['entity class']` isn't set the function will then return `new Entity()`, but thats bogus since Entity is abstract and trying to initialize `new Entity()` will result in a PHP fatal.

**Steps To Reproduce**
Create an Entity and dont declare `'entity class'` in the `hook_entity_info()` then try to call `entity_create()` on your new Entity.

We should either require ['entity class'] or throw an exception or something.

---

PR: https://github.com/backdrop/backdrop/pull/2973

**Comment by docwilmot** [comment]
Just realised this is almost a dupe of https://github.com/backdrop/backdrop-issues/issues/2558. We fixed the documentation but not this bit of code.

Would something like this be in order here?:
```
public function create(array $values) {
  $class = $this->entityInfo['entity class']) ? $this->entityInfo['entity class'] : NULL;
  if empty($class) {
    throw new EntityMalformedException(t('Missing Entity class'));
  }
  return new $class($values);
}
```

**Comment by docwilmot** [comment]
Immediately wondering if would be better to use the entity machine name instead of its label, in case it also doesnt have a proper label. Thoughts?

**Comment by herbdool** [comment]
Not sure if it's a big deal but then I haven't come across improper entity class labels.

**Comment by docwilmot** [comment]
Can we get a RTBC? Minor change I think.

**Comment by herbdool** [comment]
I haven't tested this but the code change looks simple enough.

**Comment by quicksketch** [comment]
Yep, looks good to me! Throwing an exception is much better than causing a PHP fatal! Thanks @docwilmot! Merged https://github.com/backdrop/backdrop/pull/2973 into 1.x and 1.14.x.
