### ISSUE TITLE
[DX] Add cron job to clean up configuration files for uninstalled contributed files

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4189]
**Description of the need**

With the growing number of Backdrop users, some websites could end up with messy configuration directories if uninstalled contributed modules did not care enough to properly clean up after themselves.

**Proposed solution**

If https://github.com/backdrop/backdrop-issues/issues/1811 is implemented, then it would be trivial task to add a clean up cron job to the core. 

As for @jenlampton's concern:

> We would need to be careful that we aren't deleting information that's not intended to be deleted. I often will disable a module for a period of months when it's not needed (or, for testing purposes) but want to re-enable it later. I don't want it's config accidentally purged by a cleanup routine. Still a good idea! 

I believe the main point in your comment is the word **disable**. Proposed cron job should not touch any configuration files for just **disabled** modules. However, if they, on the contrary, have the **uninstalled** status, then the leftover configuration files would be deleted anyway if the modules correctly implemented deletion of their config files as discussed on https://github.com/backdrop/backdrop-issues/issues/4186.

**Comment by jenlampton** [comment]
Since all config files will be deleted by core when a module is uninstalled (as discussed in https://github.com/backdrop/backdrop-issues/issues/5049) I don't think this issue is necessary anymore. Closing.
