### ISSUE TITLE
Add missing `@see` lines in the `config_*()` functions' docblocks.

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4191]
The `config_set()`, `config_diff()`, `config_clear()` and `config_menu()` functions do not have the @see lines in the doc blocks. As a result, API documentation pages like https://api.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/config_get/1 are missing **See also** sections.

The issue was first reported on https://github.com/backdrop-ops/api.backdropcms.org/issues/71, however because PR titles automatically pull up issue IDs from https://github.com/backdrop I had to create this one.

---
~~PR by @alanmels: https://github.com/backdrop/backdrop/pull/2969~~
PR by @alanmels: https://github.com/backdrop/backdrop/pull/2979

**Comment by klonos** [comment]
PR looks good, and the changes are only in doc blocks, so RTBC 👍 

The test failures seem to be one of the random ones (see https://github.com/backdrop/backdrop-issues/issues/1478).

**Comment by quicksketch** [comment]
Thanks @alanmels! I posted feedback to https://github.com/backdrop/backdrop/pull/2969#pullrequestreview-312649368

Adding more crosslinking is a good thing, but some of the changes made introduce inconsistencies in the way we commonly use `@see` references. See my notes in the review about common ways to reference `hook_menu()` and page callbacks.

**Comment by alanmels** [comment]
@quicksketch Thanks for the review! I had to create a new PR at https://github.com/backdrop/backdrop/pull/2979, because the original branch on which this PR was based is gone since long. And I forked Backdrop several times over to the same path, so could not restore the branch. Please review again.

**Comment by klonos** [comment]
RTBC 👍

**Comment by quicksketch** [comment]
Thanks @alanmels! The revised PR looks perfect! Merged into 1.x and 1.14.x.
