### ISSUE TITLE
[UX] Views: open the "rewrite results" fieldset if the results are rewritten

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4194]
When I'm configuring a view, I want to know at first glance whether a field has been rewritten, without needing to click on the fieldset label to expand it. When all fieldsets are closed all the time, finding the field with the settings I need to change is time-consuming.

<img width="1335" alt="Screen Shot 2019-11-04 at 1 17 17 PM" src="https://user-images.githubusercontent.com/397895/68160215-18a81280-ff08-11e9-9923-519acaa95335.png">

---
PR w stand-alone fix: https://github.com/backdrop/backdrop/pull/2975
PR with API change: https://github.com/backdrop/backdrop/pull/2976

**Comment by jenlampton** [comment]
I've created a PR that checks for any non-default value within the fieldset, and opens the fieldset if it has been selected. 

---

I'm thinking it might make for Better UX if this happened automatically for all collapsed fieldsets in Backdrop, so we wouldn't need to rely on all contrib developers to add in these kinds of checks to open the fieldsets.

Maybe we can add another form API property to `fieldset` that would include an array of all default values, keyed by element name. Then in `form_process_fieldset()` we could check for changed defaults, and if they'd been changed, leave off the `collapsed` class.

**Comment by stpaultim** [comment]
I've had views with 20 fields in which it's pretty clear that one of them is rewriting the results, but I had no idea which one and I've had to click through each one. I was hoping you were going to provide some indication on the list of fields, if a field has been rewritten. 

I just noticed the [hidden] note. I don't remember seeing that before. Is that a Backdrop CMS improvement, because I don't think D7 does it (unless it's been added recently)? 

The [hidden] helps a lot already, but would it make sense to add [rewritten] to fields that have been rewritten. (Is this a new issue?)

![Cats__Content____PR_2975_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/68161836-5020ba00-ff1c-11e9-92ed-4c2eb3dd6d9a.png)

Despite my wish for more, I believe that this PR is a clear UX improvement and it seems to work as intended for me.

**Comment by jenlampton** [comment]
> I just noticed the [hidden] note. I don't remember seeing that before. Is that a Backdrop CMS improvement,

Yep!

> The [hidden] helps a lot already, but would it make sense to add [rewritten] to fields that have been rewritten. (Is this a new issue?)

Hm, this might be a slippery slope...  What happens when fields are both hidden and rewritten, and have a title? And are there going to end up being 5 other tags we want to add here too?

**Comment by stpaultim** [comment]
> Hm, this might be a slippery slope... What happens when fields are both hidden and rewritten, and have a title? And are there going to end up being 5 other tags we want to add here too?

Yes, I recognized this as I was thinking about the request. In some ways, we've already started down the slippery slope with [hidden], but that alone is not enough justification for going further. 

For this to make sense, there would need to be something different or more important about [rewritten] over other possible tags. Just as we must have assumed that about [hidden]. 

I am not sure if there is, other than my experience with the fact that the most of the things you do within the views settings for a specific field effect that field specifically. If you rewrite a field, it can have effects any other fields as well and debugging a "rewriting" problem is trickier than other possible candidates for tags. 

Having said all of that, usually if I am rewriting a field into another field, I hide the original field. The [hidden] tag does help a lot already. 

Sounds like this would be a new issue, if it were an issue. My current thought is that between the exposed [hidden] tag and this PR, we've made pretty good progress over D7 already.

**Comment by jenlampton** [comment]
Here's an alternate PR with an API change to fix this for all fieldsets:
https://github.com/backdrop/backdrop/pull/2976

**Comment by indigoxela** [comment]
I've tested both patches (standalone and api change), both work fine.
I'm not sure if the api change affects any other module - it doesn't affect field group fieldsets in any way.

Works for me and I think this is really a UX improvement.

**Comment by olafgrabienski** [comment]
> The [hidden] helps a lot already, but would it make sense to add [rewritten] to fields that have been rewritten. (Is this a new issue?)

@stpaultim It does make sense in my opinion, would be very helpful! Should be a new issue, also to discuss the slippery slope.

**Comment by olafgrabienski** [comment]
> Here's an alternate PR with an API change to fix this for all fieldsets:
backdrop/backdrop#2976

I've tested the PR with API change using the PR sandbox site. What do you mean by "all" fieldsets?

For instance, when I add an "Administrative title" or change the "Column used for click sorting" in the "More" fieldset of a Views field and save the changes, the fieldset isn't open when I configure the field again.

**Comment by indigoxela** [comment]
> What do you mean by "all" fieldsets?

Good question. I supposed only the "rewrite results" should be open. At least, the '#defaults' array only handles the fields included in that fieldset (alter_text, make_link...)

**Comment by quicksketch** [comment]
I reviewed both PRs and I think the version that just modifies Views and doesn't add any new properties to the `#type = fieldset` element makes more sense to accomplish the task at hand.

I merged https://github.com/backdrop/backdrop/pull/2975 into 1.x and 1.16.x. And I closed https://github.com/backdrop/backdrop/pull/2976 separately.
