### ISSUE TITLE
Wrong location for maintenance-page.tpl.php in settings.php

### ISSUE THREAD

**Issue by twmfc** [backdrop/backdrop-issues#4202]
**Description of issue**

The specified location of maintenance-page.tpl.php in settings.php [1.14.1] is incorrect.

**Proposed solution**

See the correct location of maintenance-page.tpl.php to:- 

core/modules/system/templates/maintenance-page.tpl.php

- - - - - - - - - - 

PR by @stpaultim = https://github.com/backdrop/backdrop/pull/2986

**Comment by BWPanda** [comment]
All good!

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/2986 into 1.x and 1.14.x.
