### ISSUE TITLE
Basis: add hover-over and focus indication to the delete/edit/reply links for comments

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4203]
I would like us to at least indicate hover by underlining the links, or ideally make these behave like "buttons", with a hover/focus color change.

<img width="552" alt="Screen Shot 2019-11-11 at 8 41 44 am" src="https://user-images.githubusercontent.com/2423362/68551261-29eca400-045f-11ea-9f32-403363762b9b.png">

**to do**
* add `text-decoration: underline` to these links on hover.
* decide if more button-like styles should be added.

- - - - - - - - - - - - - 
PR by: @ArchanaAnand0212 https://github.com/backdrop/backdrop/pull/3333

**Comment by ArchanaAnand0212** [comment]
Hi, I worked on this as an Open Source Day Mentor in GHC 2020. I made the changes that creates a link on hover as suggested in to do.

**Comment by stpaultim** [comment]
@ArchanaAnand0212 - We may need to document this better, but if you put the line "Fixes backdrop/backdrop-issues#4203" in the first comment of a PR, it automatically links to this issue. 

Please ping me in Slack to provide any other tips, based upon your experience, that we can add to our OSD documentation. 

Commenting is also important, because it helps draw attention to the fact that work has been done on an issue.

**Comment by BWPanda** [comment]
Thanks @ArchanaAnand0212! I've left a review in the PR requesting a few small changes based on our CSS coding standards.

**Comment by stpaultim** [comment]
@BWPanda - I believe that your comments were addressed. Right?

**Comment by BWPanda** [comment]
@stpaultim Yes. PR changes look good. However now I'm wondering *why* this is necessary in the first place - why don't these links have a hover state already. Is there a larger issue here, or is that out-of-scope for this particular issue...?

**Comment by klonos** [comment]
This is basically why: https://github.com/backdrop/backdrop/blob/1.x/core/themes/basis/css/component/small-text-components.css#L132

Not sure where else that code is being used, but it seems that it makes it so that you need to explicitly specify `text-decoration: underline;` for the links that you DO want links to be underlined on hover.

**Comment by BWPanda** [comment]
Ok, https://github.com/backdrop/backdrop-issues/issues/4670 is generally what I was referring to. Question now is: do we wait for feedback on that issue before continuing here, or merge this and hope it doesn't need reverting later?

**Comment by stpaultim** [comment]
> Ok, #4670 is generally what I was referring to. Question now is: do we wait for feedback on that issue before continuing here, or merge this and hope it doesn't need reverting later?

@BWPanda - this is a good question. I don't know the answer. It might make sense to wait and have someone look at the larger picture here and suggest a systematic solution before merging this commit. 

I don't know if the solution here will be one commit or many.

**Comment by stpaultim** [comment]
Well, it looks like we are moving towards a more global solution in this issue:
https://github.com/backdrop/backdrop-issues/issues/4670

**Comment by bugfolder** [comment]
Code reviewed on https://github.com/backdrop/backdrop/pull/3333, LGTM. (Note that its initial comment doesn't include the magic "Fixes" word to bind it to this issue.)

**Comment by quicksketch** [comment]
Thanks @bugfolder for resurfacing this issue. I've merged https://github.com/backdrop/backdrop/pull/3333 into 1.x and 1.26.x. Thanks so much @ArchanaAnand0212 and sorry this took so long to get merged!
