### ISSUE TITLE
Basis: Remove underline from Delete button

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4206]
**Description of the need**
In the Basis theme, the Delete 'button' (on node edit forms) is actually a link styled to look like a button. As such, it has an underline which looks wrong considering the actual buttons it's styled after don't...

![image](https://user-images.githubusercontent.com/2385329/68948222-13787c80-07c0-11ea-8a6d-f6f4a6cdc405.png)

**Steps to recreate**

1. Visit admin/appearance 
2. Choose Basis as Administration Theme (near bottom of page)
3. Go to admin/content
4. Edit any existing node and go to the bottom of the node edit form

**Proposed solution**
Remove the underline on the any links styled to look like buttons (`a.button`).

**Comment by jenlampton** [comment]
I don't think this change needs designer feedback, so removing the `design` label.

**Comment by stpaultim** [comment]
Whoops, I think that this has been fixed already. 

I just spun up a new site and went to edit the "Your first post" post and I am not seeing this behavior. I'm also not seeing it on hover. 

![Edit_Post_Your_first_post____Beetlesa](https://user-images.githubusercontent.com/3144571/94106915-070e7880-fe02-11ea-8cc5-a768354e9171.png)

**Comment by BWPanda** [comment]
@stpaultim You need to turn off the admin theme for node forms to see this. E.g. uncheck 'Use the administration theme when editing or creating content' on the Appearance page.

**Comment by stpaultim** [comment]
I'm looking at this issue with the Open Source Day group.

**Comment by stpaultim** [comment]
Our proposed solution to this is the following CSS rule in Basis styles.css

```
a.form-delete {
  text-decoration: none;
}
```
We also considered 
  
a#edit-delete {
  text-decoration: none;
}

This seems specific enough that it should not break anything unexpected.

**Comment by himanshu007-creator** [comment]
<a href="https://github.com/backdrop/backdrop/pull/3667">This </a>PR resolves the issue. Tested successfully

**Comment by jenlampton** [comment]
I added the "works for me" label yesterday thanks to the testing done by @himanshu007-creator (thank you).

The code also looks straightforward, RTBC!

**Comment by klonos** [comment]
This is a style inconsistency/bug. It can go in on a bug release.

**Comment by laryn** [comment]
Thinking out loud a bit here, but instead of pinpointing `a.form-delete` -- is this a change that should happen to any `.button` element? (Is there any button link implementation that should have an underline?)

**Comment by jenlampton** [comment]
> Is there any button link implementation that should have an underline?

Sometimes we have cancel buttons that need to appear as though they are links -- but in those cases that's the button that should be targeted specifically.

**Comment by stpaultim** [comment]
OK, I did some poking around for another example of a button with an underline and found this.

![check-manually](https://user-images.githubusercontent.com/3144571/133152353-d4e3896a-7f42-4538-92ff-d6a40f94227a.png)

This button would not have been fixed by the old PR but is fixed by this one.

**Comment by stpaultim** [comment]
@jenlampton - I don't usually assign people to issues, but somehow it seemed appropriate! ;-)

**Comment by jenlampton** [comment]
Looks great! :) Thanks @stpaultim

**Comment by laryn** [comment]
Thank you for filing this @BWPanda, and for the PR, testing, and review @stpaultim, @himanshu007-creator, and @jenlampton! I've merged https://github.com/backdrop/backdrop/pull/3667 into 1.x and 1.19.x.

**Comment by stpaultim** [comment]
@laryn - Thank you for spotting a better solution with broader implications.
