### ISSUE TITLE
Fatal errors on install when config directory not empty

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#421]
During install, I encounter fatal errors when there are files already in the config directory.  It would be nice if we could present the user with some kind of useful messaging about needing to empty the config directory on install, instead of all these confusing errors that make it look like something is wrong with our code.

**Comment by tarekdj** [comment]
@jenlampton I think this has been fixed by https://github.com/backdrop/backdrop/pull/659

**Comment by quicksketch** [comment]
You're right @tarekdj! Now it prevents install. Thanks for finding this issue. I added it to the meta at https://github.com/backdrop/backdrop-issues/issues/531 of resolved problems.
