### ISSUE TITLE
[UX] Display the default search setting option only if more than one search modules are active

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4210]
**Sub-issue**

Per discussion on https://github.com/backdrop/backdrop-issues/issues/4197 AltaGrade team has started to work on getting some features of the Search Index Options module into Backdrop core. And because the module incorporates several different features, not all of which might be liked and accepted by Backdrop community, I've decided to split the project into several issues with respective PRs.

**Description of the need**

This one is for hiding the options for setting the default search module in case if only one such module is enabled. It makes perfect sense to display such a configuration option only if more than one search modules are activated.

I will later create a PR which provides the following features shown on the demo screencast below:

1. If there are more than one search modules available (for example, both `Content` and `User accounts`) then it makes the default one greyed out (disabled);

2. If there is only one search module enabled (for example, only `Content`), then it hides the `Default search` fieldset, because no need to display the only choice, which is chosen by default anyway.

![Search_settings](https://user-images.githubusercontent.com/56604405/68996821-69c4e880-08b0-11ea-82b9-cb0b5f079b38.gif)

Note that currently the [Search Index Options](https://github.com/backdrop-contrib/search_index_options) module behaves slightly differently: namely it does not effectively hide the `Default search` fieldset, but shows the single option like so:

<img width="565" alt="Screen Shot 2019-11-16 at 8 57 09 PM" src="https://user-images.githubusercontent.com/56604405/68997135-25d3e280-08b4-11ea-87de-d2dcfdb3232e.png">

However, I thought to make it even better for core and completely hide that fieldset, which is useless and just unnecessarily takes place on the page.

**Comment by docwilmot** [comment]
> If there are more than one search modules available (for example, both Content and User accounts) then it makes the default one greyed out (disabled);

what if you want to disable both?

**Comment by alanmels** [comment]
> > If there are more than one search modules available (for example, both Content and User accounts) then it makes the default one greyed out (disabled);
> 
> what if you want to disable both?

You can try to do so on your current Backup website and it won't let you do so giving an error notice:

> Your default search module is not selected as an active module.

So instead of letting user to perform useless action (disabling both modules) that will not go through anyway, it's much better to grey out the default search module, so it never possible to uncheck its checkbox.

**Comment by klonos** [comment]
Thanks for filing this @alanmels 👍 

I would still like us to eventually turn this into a table as per the screenshot/mockup in #3385, but this is not bad as an easy first step to remove some of the UI WTFs.

The benefit of having it as a table will start paying off once there are many enabled search items/modules, as it would not be repeating the same options.

**Comment by alanmels** [comment]
@klonos, I've completely forgot about the #3385. The table you suggested looks much better, so let's concentrate on that one instead. Closing this one.

**Comment by klonos** [comment]
I have actually started re-working on that one @alanmels ...I have in the meantime lost the PR I had almost ready, so will need to start from scratch 😞
