### ISSUE TITLE
Capitalize "Reply-To" header

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4214]
**Description of the bug**
This issue https://github.com/backdrop/backdrop/pull/688 fixed an issue with "from" and "reply-to". However I believe it incorrectly sets `$headers['Reply-to']` instead of `$headers['Reply-To']` in `core/includes/mail.inc`. I think this is a regression in Backdrop.

This causes a problem with Webform emails: the emails get both `Reply-to` and `Reply-To` set. Webform is expecting the same behaviour as in Drupal 7 which sets `Reply-To`.

This reference https://tools.ietf.org/html/rfc5322 also references `Reply-To`.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/2992

**Comment by klonos** [comment]
Might as well get this out of the way: https://github.com/backdrop/backdrop/pull/2992

**Comment by herbdool** [comment]
Thanks @klonos, looks good.

**Comment by herbdool** [comment]
I'm not convinced this needs the comment since we could reference the official docs for any and all parts of creating an email.

**Comment by klonos** [comment]
The intention of the comments is so that others do not touch that bit of code in the future.

**Comment by quicksketch** [comment]
Thanks! This is pretty minor but I agree with @herbdool that we shouldn't need to link back to the issue unless it's an unusual or confusing situation. I like the link to the spec, though it applies to all headers. Maybe move the code comment up and rephrase? https://github.com/backdrop/backdrop/pull/2992/files#r354537879

**Comment by herbdool** [comment]
@klonos there's a comment on your PR. If you'd rather I can make the change for you.

**Comment by klonos** [comment]
👀

**Comment by klonos** [comment]
All done 😉

**Comment by quicksketch** [comment]
Looks great! Thanks @herbdool and @klonos! Merged https://github.com/backdrop/backdrop/pull/2992 into 1.x and 1.14.x.
