### ISSUE TITLE
Number (integer) field: should be able to have a minimum with no maximum

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4216]
**Description of the bug**

When adding a number integer field it should be possible to set a minimum and leave the maximum blank. Instead it gives an error that the maximum needs to be greater than the minimum. At least I think it should be possible. For example, what if a field should only have positive numbers? There might be no need to set a maximum bound.

**Comment by indigoxela** [comment]
>  it should be possible to set a minimum and leave the maximum blank

I totally agree. And here's a PR: https://github.com/backdrop/backdrop/pull/2997

Please test and review.

**Comment by herbdool** [comment]
Thanks! Works great and code looks good

**Comment by quicksketch** [comment]
Looks great, merged https://github.com/backdrop/backdrop/pull/2997 into 1.x and 1.14.x.
