### ISSUE TITLE
[UX] Replace double dashes (hyphens) with single character in menu parent select list

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#4218]
**Description of the need**
Currently when selecting a menu item, we use two dashes to indicate a level in the hierarchy:

![image](https://user-images.githubusercontent.com/100206/69270109-340d5180-0b87-11ea-8926-10dcc44838e5.png)

The double-dashes can be difficult to determine exactly how many levels something is in the hierarchy (number of dashes divided by two).

**Proposed solution**

It might make things easier to read if we used a single character per hierarchical level, such as a square bullet.

---

PR by @verygladden: https://github.com/backdrop/backdrop/pull/3078

**Comment by olafgrabienski** [comment]
Interesting! As an experiment, I've replaced the double dashes using my browser's dev tools with different signs, e.g.

- `–` (n dash)
- `>`
- `·` (middot)

The `middot`s, separated by a space, gave the best result so far. Here's a screenshot:

<img alt="backdrop-menu-dropdown-middots" src="https://user-images.githubusercontent.com/14188307/69279799-69488c80-0be5-11ea-95a7-ae8e7c3c7cb2.png">

**Comment by klonos** [comment]
I like the middots better @olafgrabienski 👍 ...will you be able to file a PR for it?

PS: I would like us to eventually implement a more user-friendly and familiar way (reuse UI patterns) for selecting menus. What is proposed in #3029 basically. That would provide the best UX; but this is a nice improvement in the interim.

**Comment by olafgrabienski** [comment]
Thanks for your feedback @klonos ! I'm still short of time and the issue doesn't seem to be urgent, so unfortunately no PR from me.

Apart of that, I'm indecisive about the middots: They look good but at the same time uncommon. Are (single) dashes maybe better because more common? Here's a comparison:

**Single dashes:**

<img alt="screen-backdrop-menu-dropdown-dashes" src="https://user-images.githubusercontent.com/14188307/69579788-80b3bb00-0fd3-11ea-90eb-3f2d41bac646.png">

**Middots:**

<img alt="backdrop-menu-dropdown-middots" src="https://user-images.githubusercontent.com/14188307/69279799-69488c80-0be5-11ea-95a7-ae8e7c3c7cb2.png">

**Comment by olafgrabienski** [comment]
As a side note, looking at the select list, I noticed the angle brackets around top level items, e.g. `<Primary navigation`>. Do we need those brackets? In my opinion, the list is better readable without. Have a look at the following comparison:

```
<Primary navigation>
- Home
- About
-- History
- Portfolio
- Contact
```

```
Primary navigation
- Home
- About
-- History
- Portfolio
- Contact
```

**Comment by quicksketch** [comment]
I'm in favor of removing the angle brackets. A lot of sites only have a single menu available (like the out-of-box functionality).

As for middot vs. dashes, I think the middot is a lot more readable than the dash. It's easy to count the level of indentation, as opposed to dashes where they all run together.

**Comment by olafgrabienski** [comment]
Thanks for your feedback, @quicksketch! I'd like to make a last comparison between middots, separated by a space (as above) vs. middots without separation:

**(1) Middot + space:**

Primary navigation
· Home
· About
· · History
· · · 2019
· · · 2018
· · · 2017
· Portfolio
· Contact

**(2) Just middot:**

Primary navigation
· Home
· About
·· History
··· 2019
··· 2018
··· 2017
· Portfolio
· Contact

Okay, in my opinion it looks better *with* space.

**Comment by olafgrabienski** [comment]
> will you be able to file a PR for it?

@klonos I might find some time soon but have not the minimal idea where the characters for the menu item select list are defined. Do you have an idea or can you give me a hint where to look?

**Comment by indigoxela** [comment]
@olafgrabienski this hides in function [_menu_get_options](https://github.com/backdrop/backdrop/blob/8dbc2cd6ede188c6c134db7161baf3f119ae28de/core/modules/menu/menu.module#L398)

**Comment by verygladden** [comment]
I made a PR that should fix this issue.

**Comment by olafgrabienski** [comment]
@verygladden Thanks for the PR, and welcome to Backdrop!

I've tested the PR in the sandbox website (http://3078.backdrop.backdrop.qa.backdropcms.org), looks good to me! Here's a screenshot from the sandbox site:

<img width="262" alt="screen-backdrop-pr-3078-menu-select" src="https://user-images.githubusercontent.com/14188307/74785265-3710fe80-52aa-11ea-8c02-5f146fb33df7.png">

I'd be happy if someone else could make the code review.

**Comment by BWPanda** [comment]
Merged https://github.com/backdrop/backdrop/commit/f8fa25635f4bd65094905387db415c8ead39be94 into 1.x. Thanks @quicksketch for the suggestion, and to @olafgrabienski & @herbdool for the reviews and feedback! And a very big thank you to @verygladden for the PR! Congrats on your first official contribution to Backdrop core :smiley:
