### ISSUE TITLE
Add missing API definitions in code, so the API site can show them

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4223]
Some clever folks have noticed that we are missing some functions on https://api.backdropcms.org/api/backdrop/core%21modules%21field%21field.api.php/group/field_formatter/1

<img width="817" alt="Screen Shot 2019-11-24 at 3 43 17 PM" src="https://user-images.githubusercontent.com/397895/69503684-2cc0ad80-0ed1-11ea-9337-bcd776a0f864.png">

The best way to get them in there would be to define example functions in `field.api.php` so that the API site can parse them out properly and add them to the table. 

---

~PR by @BWPanda https://github.com/backdrop/backdrop/pull/2908~
PR by @quicksketch https://github.com/backdrop/backdrop/pull/3117

**Comment by BWPanda** [comment]
@jenlampton Are you saying we should move the functions from `field_ui.api.php` to `field.api.php`? (See https://github.com/backdrop-ops/api.backdropcms.org/issues/49#issuecomment-536156616)

If not, this should be enough: https://github.com/backdrop/backdrop/pull/2908

**Comment by jenlampton** [comment]
That should do it, thank you!

**Comment by docwilmot** [comment]
RTBC

**Comment by quicksketch** [comment]
> Hm, I didn't think to look there. I wonder why they aren't getting picked up, if they are there?

That page is specifically `field.api.php` it only lists the hooks called by Field module. There is a similar page for Field UI: https://api.backdropcms.org/api/backdrop/core%21modules%21field_ui%21field_ui.api.php/1

**Comment by quicksketch** [comment]
Here's a PR that puts the hook in the right documentation groups: https://github.com/backdrop/backdrop/pull/3117

[field.api.php](https://api.backdropcms.org/api/backdrop/core!modules!field!field.api.php) defines 3 groups:

- `field_types`
- `field_widget`
- `field_formatter`

The `field_ui.api.php` incorrectly puts _everything_ in `field_types`, when everything should actually be in `hooks`, with the individual hooks placed into one of the 3 field API groups.

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
Thanks @herbdool! I've merged https://github.com/backdrop/backdrop/pull/3117 into 1.x and 1.16.x.
