### ISSUE TITLE
`url()` adds fragments after `?destination=`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4226]
**Steps To Reproduce**
Consider the following bit of code:

`url('admin/some-other-page', array('fragment' => 'some-fragment', 'query' => array('destination' => 'admin/back-to-original-page')))`

**Actual behavior**
Rendered URL/link:

`https://my.site/admin/some-other-page?destination=admin/back-to-original-page#some-fragment`

**Expected behavior**
`https://my.site/admin/some-other-page#some-fragment?destination=admin/back-to-original-page`

**Additional information**
The latest comment [here](https://drupal.stackexchange.com/a/192902/85335) seems to suggest that this is intentional:

> Page fragment is always passed after the query string. Otherwise, the browser will recognize the query string as part of the fragment.

**Comment by klonos** [comment]
...I'm changing this to a question. Lets get some feedback before deeming it to be a bug.

**Comment by BWPanda** [comment]
It seems that's just how URLs work. See the example at the end of this section of the page: https://url.spec.whatwg.org/#url-representation

> `https://localhost:8000/search?q=text#hello`

The question now is, how do you (or is it even possible to) specify a destination that includes a fragment...?

**Comment by BWPanda** [comment]
Ah, here's the answer: https://drupal.stackexchange.com/a/192902

So I think this question has been answered now. @klonos Do you concur?

**Comment by BWPanda** [comment]
Closing as answered.

**Comment by klonos** [comment]
Yes 👍🏼 ...belated thank you @BWPanda 🙏🏼
