### ISSUE TITLE
Image fields: Do not allow min resolution to be larger than max resolution

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4227]
Filing this as a follow-up to #4221.

When creating image fields, there is no validation for the resolution when min > max. So you end up with this:

<img width="394" alt="69861930-80763100-12ed-11ea-813c-f39916cb9f6b" src="https://user-images.githubusercontent.com/2423362/69913598-c407a100-148d-11ea-951a-e8ca54d260c3.png">

---
~~PR by @klonos https://github.com/backdrop/backdrop/pull/3009~~
PR by docwilmot https://github.com/backdrop/backdrop/pull/3109

**Comment by indigoxela** [comment]
@klonos it works like a charm, but I added some suggestions in a comment at your PR.

**Comment by klonos** [comment]
Thanks @indigoxela 👍 ...I have fixed the typo, and added the `$name` parameter in `form_set_error()`. I have tried to implement this but it did not work, because I was doing this:

`form_set_error('instance[settings][min_dimensions]'`

For my benefit, can someone please explain the logic behind having to use `][`, and why things don't work when including the trailing `]`?

**Comment by indigoxela** [comment]
> For my benefit, can someone please explain the logic behind having to use ][...

To be honest, I usually tinker until it works, starting with the html name attribute. The "][" separator is needed to traverse through the parent/child structure of a nested form. That's all I know. So - I'm not much of a help here either.

**Comment by klonos** [comment]
Thanks again @indigoxela ...that's more than I know on the matter 😅 ...I just find it odd; that's all.

**Comment by indigoxela** [comment]
Your PR works fine and seems ready to get merged.

**Comment by quicksketch** [comment]
This is a great suggestion, it's odd that this is allowed at all.

I left some feedback on the PR: https://github.com/backdrop/backdrop/pull/3009#pullrequestreview-327828965

**Comment by docwilmot** [comment]
New PR up, addressing @quicksketch concerns, and adding test.

**Comment by docwilmot** [comment]
One bogus fail, so "green" tests. Please review.

**Comment by jenlampton** [comment]
One tiny code comment change recommendation, otherwise this is RTBC!

**Comment by docwilmot** [comment]
Done!

**Comment by jenlampton** [comment]
Nice! Thank you :) If you are still around, I found one more tiny docs nit:
https://github.com/backdrop/backdrop/pull/3109#pullrequestreview-399549216

**Comment by jenlampton** [comment]
RTBC!

**Comment by quicksketch** [comment]
Super work! Thanks @docwilmot and @klonos for the PRs! Thanks @indigoxela and @jenlampton for reviewing!

Merged https://github.com/backdrop/backdrop/pull/3109 into 1.x and 1.15.x.
