### ISSUE TITLE
[DX] Mention `NOT` operator in `backdrop_process_states()`

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4228]
[`backdrop_process_states`](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_process_states/1) details the use of `#states` for the Form API, but nowhere does it mention how to use the `NOT` operator. E.g. if you want a field to be visible only when another field is NOT a certain value.

The solution is described here: https://api.drupal.org/comment/24708#comment-24708 and looks like this:

```php
'#states' => array(
  'visible' => array(
    ':input[name="other_field"]' => array('!value' => 'not_this_value'),
  ),
),
```
(i.e. `'!value'`)

This should be added to the documentation.

**Comment by klonos** [comment]
This seems to be one of those little things that are meant to be "common knowledge", but not "officially" documented. Similar #3450.

So yes, let's properly document these as we come across them 👍

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3935

**Comment by BWPanda** [comment]
Since its only a documentation change, I went ahead and merged https://github.com/backdrop/backdrop/pull/3935
