### ISSUE TITLE
embed media in the rich text editor

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4229]
**Description of the need**
WYSIWYG editor will allow media embedding.
**Proposed solution**
https://www.youtube.com/watch?v=sTc2JJzs9iU

**Comment by quicksketch** [comment]
We already allow direct image embedding that is very similar to what's shown in the video, including a views-based image browser.

We don't provide generic media type embedding, like videos or PDF documents though. However, in those cases often a filter like https://backdropcms.org/project/video_filter can do the job for externally hosted videos.

Could you clarify which type of functionality you're looking for? If it's only what's in the video, I would say we already have this feature.
