### ISSUE TITLE
Entity reference cannot be null not

### ISSUE THREAD

**Issue by neessen** [backdrop/backdrop-issues#4234]
An entity reference field without value causes error: 

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_reference_test_target_id' cannot be null

**Steps To Reproduce**
-Create content type. 
-Add entity reference of other content type
-Save

Error shows after save if no value is selected.

- Backdrop CMS version: 1.14.1

**Comment by stpaultim** [comment]
Entity reference module? https://github.com/backdrop-contrib/entityreference/issues
