### ISSUE TITLE
Add more display options for boolean fields

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4235]
**Description of the need**
When using a boolean / "on/off" field, Single on/off checkbox widget, and using the "Use field label instead of the "On value" as label" setting, the display gets a bit ugly on the node view. By default it will show the label with a colon at the end and no value. It shouldn't use the same formatting as the node form since it usually doesn't make much sense. E.g.: "Are you over eighteen?" is a useful label when the user can check it off. But when someone else views the node, it would just display "Are you over eighteen?" The only other option out of the box is to use the key, which by default is 1/0. So that's ugly.

**Proposed solution**
Something like this in core https://www.drupal.org/project/boolean_formatter

---
PR https://github.com/backdrop/backdrop/pull/3013

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...this is a really nice UX touch!

I have noticed this comment in the module page in d.org:

> Inspired by the Views boolean field handler, which ironically cannot be used for boolean field API fields.

...so I also tested it in Views, and I have found that the `#states` visibility for the custom on/off values does not work:

![Screen Shot 2019-12-11 at 5 48 35 am](https://user-images.githubusercontent.com/2423362/70559303-84059400-1bda-11ea-9410-c2fcb9b9b986.png)

(notice how the two fields are visible, even when the output format is not set to "custom")

Other than that, I have found the code to look good, and everything else I tested works as expected 👍 

PS:
- `name` attribute for those fields when editing display settings:
`fields[field_bool][settings_edit_form][settings][custom_on]` | `fields[field_bool][settings_edit_form][settings][custom_off]`
- `name` attribute when editing the Views output format:
`options[settings][custom_on]` | `options[settings][custom_off]`

**Comment by herbdool** [comment]
@klonos ready for another review with a fix for what you reported

**Comment by klonos** [comment]
Thanks @herbdool 👍 ...WFM, and almost RTBC. I've left a comment/suggestion in the PR re readability of the `$states` conditionals.

**Comment by herbdool** [comment]
@klonos thanks for the suggestion. I've updated it. I made it match this in core: https://github.com/backdrop/backdrop/blob/9d73493ba92c6e5e049e61cc424fbb9b0a09e5a7/core/modules/views/plugins/views_plugin_display_page.inc#L353. The "or" line is implied.

**Comment by klonos** [comment]
> I made it match this in core: ... The "or" line is implied.

Huh, I always thought that AND was implied 🤔 ...anyway, the PR works as expected, so I'm the one that got this wrong 😅 ...RTBC 👍

**Comment by quicksketch** [comment]
This looks good to me!

I think a few things here warrant test coverage:

- Testing the basic options for On/Off, TRUE/FALSE, etc.
- Setting custom text values and ensuring they come out on display.
- Using the "Reverse" option to get the opposite value.

We already have list.test that makes test listing fields and we can imitate `FileFieldDisplayTestCase` or other field tests that cover formatter output.

**Comment by herbdool** [comment]
@quicksketch done.

**Comment by jenlampton** [comment]
Testing results -- WFM:

Yes/No display. 
<img width="1191" alt="Screen Shot 2020-01-01 at 3 53 18 PM" src="https://user-images.githubusercontent.com/397895/71647648-e409ca80-2cae-11ea-9f2d-96d339a867e1.png">

True/False
<img width="1216" alt="Screen Shot 2020-01-01 at 3 54 10 PM" src="https://user-images.githubusercontent.com/397895/71647653-fab02180-2cae-11ea-957c-f5f219d99905.png">

On/Off:
<img width="1205" alt="Screen Shot 2020-01-01 at 3 54 42 PM" src="https://user-images.githubusercontent.com/397895/71647657-13b8d280-2caf-11ea-9527-2031a9a97206.png">

Enabled/Disabled:
<img width="1192" alt="Screen Shot 2020-01-01 at 3 55 25 PM" src="https://user-images.githubusercontent.com/397895/71647664-29c69300-2caf-11ea-89d5-985863bc8b95.png">

1/0:
<img width="1201" alt="Screen Shot 2020-01-01 at 3 56 02 PM" src="https://user-images.githubusercontent.com/397895/71647671-42cf4400-2caf-11ea-94aa-396ae579f08b.png">

check/X
<img width="1207" alt="Screen Shot 2020-01-01 at 3 56 51 PM" src="https://user-images.githubusercontent.com/397895/71647686-5a0e3180-2caf-11ea-8d9f-d9fdf40d1dca.png">

Custom (yes values):
<img width="1194" alt="Screen Shot 2020-01-01 at 3 57 54 PM" src="https://user-images.githubusercontent.com/397895/71647697-832ec200-2caf-11ea-9e2d-b03cb23ed053.png">

Custom (no values):
<img width="1184" alt="Screen Shot 2020-01-01 at 3 58 37 PM" src="https://user-images.githubusercontent.com/397895/71647708-a194bd80-2caf-11ea-941c-19e8080b73d7.png">

**Comment by jenlampton** [comment]
The only problem I found in the code review is two missing line breaks at the end of files. @quicksketch is that something you can add when you merge the PR?

**Comment by quicksketch** [comment]
I added the two missing new lines.

This looks great! Thanks so much for adding those tests @herbdool! This makes Boolean fields much better than it was before.

**Comment by herbdool** [comment]
Big thanks to @davereid for the original Drupal module!
