### ISSUE TITLE
Notice: Undefined index: settings in DashboardWelcomeBlock

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4236]
**Description of the bug**
When visiting the Dashboard page (admin/dashboard) a php notice happens:

`Notice: Undefined index: settings in DashboardWelcomeBlock->getContent() (line 55 ...core/modules/dashboard/includes/block.welcome.inc). 
`
https://github.com/backdrop/backdrop/blob/9d73493ba92c6e5e049e61cc424fbb9b0a09e5a7/core/modules/dashboard/includes/block.welcome.inc#L55

**Additional information**

- Backdrop CMS version: 1.14.1 
- Web server and its version: Apache/2.4 
- PHP version: 7.2.25
- color module is disabled
- Seven it the admin theme (active at that page)
- default theme is a custom subtheme of Basis

If I set Seven or Basis as the _default theme_, the notice goes away.

Some other experiments without any effect:
* enabling color module
* flushing caches
... didn't prevent the notice.

The problem arises in function theme_has_settings(), as it returns true if the base theme has settings. My subtheme has no settings at all.
Even Basis has no settings on that website, because the color module is disabled.

The question is: where to fix it?

1. Catch it in DashboardWelcomeBlock (check if info['settings'] exists before trying to access it)
2. Catch it in function theme_has_settings() (return FALSE for subtheme if it has no settings)

Does anyone know, why theme_has_settings() returns the _base theme_ value, not the current theme value?
What sort of theme settings are inherited by subthemes?

This is slightly related to https://github.com/backdrop/backdrop-issues/issues/3348

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/3015

**Comment by indigoxela** [comment]
For people interested in a qad workaround: put following line in your subtheme's .info file:

`settings[color] = FALSE`

The only thing this does is to prevent the php notices, it's not an actual fix.

**Comment by klonos** [comment]
Easy fix @indigoxela 😉 ...can you please test this 1-liner on your local (simply wrap `$themes[$default_theme]->info['settings']['color']` in `isset()`)?

**Comment by indigoxela** [comment]
@klonos your one-liner sure fixes the notice, thanks for providing a PR. But my concerns go beyond that.

There will still be a link to admin/appearance/settings/[theme name] even though there are no settings at all. Isn't that confusing for users?

I admint, I don't understand the concept of setting inheritance in subthemes. Which ones are inherited? We know, currently color settings aren't.

**Comment by herbdool** [comment]
@indigoxela according to https://api.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_has_settings/1 `theme_has_settings` checks the `.info` files of the current default theme as well as the parent theme if it exists. So it's doing both. Basis has `settings[color] = true` so even if color module is disabled it still technically has settings. And thus so do all children themes.

**Comment by indigoxela** [comment]
@herbdool many thanks for your explanations.

So the PR provided by @klonos fully covers the problem. No need for other fixes.

**Comment by quicksketch** [comment]
Thanks! I merged https://github.com/backdrop/backdrop/pull/3015 into 1.x and 1.14.x.
