### ISSUE TITLE
File usage of files used in text blocks increases on every block save

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4237]
**Description of the bug**
Blocks of type BlockText handle files referenced in block body to a certain degree. Unfortunately file usage is increased every time such a block gets saved.

**Steps To Reproduce**
Two ways to reproduce it, directly via layout and for reusable blocks.

1. Go to admin/structure/layouts/manage/home
2. Add a custom block
3. Add an image in the block body
4. Save that block
5. Inspect file usage (admin/content/files)
6. Repeat step 4 and 5 several times
---
Alternate way to reproduce:

1. Go to admin/structure/block/add
2. Add an image in the block body (fill out required admin label, too)
3. Save that block
4. Inspect file usage (admin/content/files)
5. Repeat step 3 and 4 several times

**Actual behavior**
Whenever a block with an image in block body gets saved, the file usage increases.

**Expected behavior**
Do not increase file usage every time a block gets saved.

**Additional information**

- Backdrop CMS version: 1.15.x-dev
- Web server and its version: Apache 2.4
- PHP version: 7.0+

I'm aware that file usage handling in blocks isn't perfect for several reasons, but the ever-increasing usage count could get fixed.

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/3016), which addresses the usage increase.
Please test and review.

**Comment by indigoxela** [comment]
@herbdool we seem to disagree regarding the right way to fix the check. :smile: 

The main difference is that you suggest to cast a boolean to integer while I suggest to cast the integer to string. Both work, so it's maybe not worth a discussion. Or is it?

**Comment by indigoxela** [comment]
I've updated my PR according to your change request.

**Comment by herbdool** [comment]
Thank you

**Comment by quicksketch** [comment]
Thanks @indigoxela! Those strict operators failing make me sad it's necessary, ideally those properties would always be the right type, but I recognize it's often not the case. The solution is great, thanks so much to you and @herbdool for fixing this problem!

https://github.com/backdrop/backdrop/pull/3016 merged into 1.x and 1.14.x.
