### ISSUE TITLE
MySQL 8 support

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#4238]
**Description of the need**
MySQL 8 has a number of incompatibilities with previous versions, including new keywords that need to be escaped, and removing of the `NO_AUTO_CREATE_USER` init SQL mode. This causes Backdrop to fail to install or work properly with MySQL 8.

Similar issues documented for Drupal:
D8: https://www.drupal.org/project/drupal/issues/2966523
D7: https://www.drupal.org/project/drupal/issues/2978575

---

PR for 1.x: https://github.com/backdrop/backdrop/pull/3018 (merged)
PR for 1.17.x: https://github.com/backdrop/backdrop/pull/3381

This issue is under consideration for including in 1.17.x.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/3018 that includes the basic support. It does not specify a full whitelist of reserved keywords like the D8 approach, instead it just quotes all table names. This patch is a direct port from https://www.drupal.org/project/drupal/issues/2978575#comment-13352288. It will need some further clean-up before it's ready (doc block updates, additional tests, etc).

**Comment by quicksketch** [comment]
Updated the PR at https://github.com/backdrop/backdrop/pull/3018 that should now be passing all tests. Thanks @hosef for the review!

**Comment by quicksketch** [comment]
Possibly squeeze into 1.17.0? Backdrop not working out of the box on the current releases of RedHat or CentOS servers is a bad look. And if Debian/Ubuntu users install MySQL instead of MariaDB (their out of box default) it's also MySQL 8 there.

**Comment by jenlampton** [comment]
@quicksketch what's the best way to test mysql 8?

**Comment by quicksketch** [comment]
@jenlampton If you have Lando, you can switch it to use MySQL 8: https://docs.lando.dev/config/mysql.html#supported-versions

Alternatively, create any VM using the latest CentOS or Ubuntu and install MySQL.

The best solution may be to start running tests with MySQL 8.

Overall though, I think the most important thing here is to not break existing sites. If there are MySQL 8 specific issues, that could be handled in separate issues.

**Comment by quicksketch** [comment]
I don't think we have time to safely put this into the current release unfortunately. I'm bumping this to the next release.

**Comment by jenlampton** [comment]
@quicksketch can this go into a bug-fix release?

**Comment by herbdool** [comment]
My feeling is that it could be in a bug fix release. So long as there's enough kicking of tires.

**Comment by indigoxela** [comment]
Did anyone test this yet?

If I try to install Backdrop on a MySQL8 I get:

```
Database configuration
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system ( `filename` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'The path of the pr' at line 1 
```
Right after inputting the db credentials in the web installer.

**Comment by indigoxela** [comment]
FTR: I set up a small virtual machine (Debian) with MySQL 8.0.21 to help out with testing here.

**Comment by domaingood** [comment]
I m also try with Redhat 8 with MySQL 8

**Comment by earlyburg** [comment]
I will try it with MySQL Ver 8.0.21 on Ubuntu 20.04 on an x86_64

**Comment by quicksketch** [comment]
Thanks @indigoxela for testing! In my situation, I already had the site install and switched to MySQL 8. So perhaps the installer needs some additional treatment, or creation of tables might not be escaped. I'll take a look.

**Comment by quicksketch** [comment]
I updated the PR so that table names are now escaped now as well. There are still some tests to be worked out but I think it will now work to install Backdrop fresh on MySQL 8.

**Comment by quicksketch** [comment]
Posted another update where all tests are passing and it's a safer approach to escaping tables. I think this should on complete installs but I haven't tried it in MySQL 8 yet. Seems to work fine as far as compatibility with existing tests and modules though.

**Comment by indigoxela** [comment]
Cool, it works now! I tried both, without and with table prefix.

![status-mysql8](https://user-images.githubusercontent.com/842066/93665111-49d3f780-fa74-11ea-9332-cf67f94a2d90.png)

**Comment by domaingood** [comment]
I cannot install Backdrop CMS in Mysql 8 with php 7.4 in Red-hat 8
Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1457 of /var/www/phalcon0/data/www/phalconcms.com/core/includes/form.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1457 of /var/www/phalcon0/data/www/phalconcms.com/core/includes/form.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1457 of /var/www/phalcon0/data/www/phalconcms.com/core/includes/form.inc).
Failed to connect to your database server. The server reports the following message: Access denied for user 'phalcon0_data'@'localhost' (using password: YES).

For more help with configuring your database server, see the Installation Instructions page.

**Comment by indigoxela** [comment]
> Failed to connect to your database server. The server reports the following message: Access denied for user 'phalcon0_data'@'localhost' (using password: YES).

@domaingood either there's something wrong with your credentials (a typo), or the db user you created has the wrong authentication plugin. Make sure that "Native MySQL authentication" is in use. You can verify that with phpMyAdmin or on command line:

An example for a user "backdrop":
```
mysql> SELECT plugin from mysql.user where User='backdrop';
+-----------------------+
| plugin                |
+-----------------------+
| mysql_native_password |
+-----------------------+
1 row in set (0.00 sec)
```

**Comment by domaingood** [comment]
@indigoxela  Thank you for your reply.I m using Redhat 8 with my custom Hosting panel.I already created mysql user password and onting wrong with that I already tested Other software Like Drupal 7 
https://www.drupal.org/project/drupal/issues/2978575
tuhin:~# mysql -V
mysql  Ver 8.0.17 for Linux on x86_64 (Source distribution)
tuhin:~# apachectl -v
Server version: Apache/2.4.37 (centos)
Server built:   Jun  8 2020 20:14:33
tuhin:~# nginx -v
nginx version: nginx/1.14.1

I can sure its problem in Backdrop CMS

**Comment by domaingood** [comment]
New Error
Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1457 of /var/www/phalcon0/data/www/phalconcms.com/core/includes/form.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1457 of /var/www/phalcon0/data/www/phalconcms.com/core/includes/form.inc).
Warning: count(): Parameter must be an array or an object that implements Countable in _form_validate() (line 1457 of /var/www/phalcon0/data/www/phalconcms.com/core/includes/form.inc).
Failed to connect to your database server. The server reports the following message: SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'.

For more help with configuring your database server, see the Installation Instructions page.

**Comment by indigoxela** [comment]
> Failed to connect to your database server. The server reports the following message: SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'.

@domaingood That's [exactly what the PR fixes](https://github.com/backdrop/backdrop/pull/3018/files) If you still have NO_AUTO_CREATE_USER in your testing web, you're either on the wrong branch or used the wrong download.

Please use this one: https://github.com/quicksketch/backdrop/archive/4238/mysql8.zip
Or if you prefer git, make sure that you switch to the right branch: `git checkout '4238/mysql8'`

**Comment by domaingood** [comment]
Issue Fixed
Info | Backdrop CMS | 1.17.x-dev
Info | Backdrop CMS update status | Developer version (version 1.17.0 available) more
Info | MySQL Database | MySQL, MariaDB, or equivalent version 8.0.21
Info | PHP | Version: 7.4.10 (PHP information)
Info | Web server | Apache/2.4.37 (centos) mpm-itk/2.4.7-04 OpenSSL/1.1.1c PHP/7.4.10

**Comment by domaingood** [comment]
Its too late for mySQL 8 1.8 Better move it 1.7.x

**Comment by klonos** [comment]
> Its too late for mySQL 8 1.8 Better move it 1.7.x

Given that major linux distros have switched to MySQL 8.x as their default, I'd be fine to get this into a 1.17.x release, but as @herbdool said:

> So long as there's enough kicking of tires.

So how do we kick more tires till (or before) Jan. 2021? We should merge this as soon as possible, but keeping it in 1.x will only get us testing on PR sandboxes, which always get MySQL 5.5.x 🤔 

I will bring this up during our dev meeting this week, but I was thinking that perhaps we could consider cutting a 1.18.0-beta and include it there (for those that need an official release rather than the most recent 1.x branch).

I'm gonna set lando to use MySQL 8 and test this on my local...

**Comment by earlyburg** [comment]
I tested this issue on my local dev system and heres my analysis.
System Environment:
Ubuntu 20.04 (Focal Fossa)
PHP 7.4.3
mysql  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))

Backdrop patched version found here:
https://github.com/quicksketch/backdrop/archive/4238/mysql8.zip

On this server I have two backdrop sites side by side - one the latest official release and the other from quicksketch/backdrop/archive and used the Devel module to analyze query times and page load times. My latest offical release uses MySql 5.7 server running on a networked system and the quicksketch/backdrop/archive versions uses MySql 8.0.21 running locally (should be faster?). 

Loading /admin/modules/list, the return times were as follows:
quicksketch/backdrop/archive version: Executed 82 queries in 1125.76 ms. 
Vanilla version: xecuted 76 queries in 156.35 ms.

A cache clear of the same page:
quicksketch/backdrop/archive version: Executed 327 queries in 3295.51 ms. 
Vanilla version: Executed 335 queries in 785.82 ms.

It seems as if for me performance is compromised. The site using MySql 8 has a slowed user experience. The site speed is what makes Backdrop very appealing for some so this may need further refinement? I would love to hear feedback from other tests as well.

**Comment by indigoxela** [comment]
@earlyburg Many thanks for sharing your benchmarks!

> My latest "offical release" site uses MySql 5.7 server running on a networked system and the "quicksketch/backdrop/archive" site uses MySql 8.0.21 running locally

That makes me think that these two instances might have different configuration. Did you compare the respective `my.cnf` files?

Another thought: the quoting/escaping also applies to MariaDB. Did you benchmark that with/without patch? Did you also find a comparable slowdown with MariaDB?

**Comment by indigoxela** [comment]
Another thought: @quicksketch's branch is 25 commits behind backdrop:1.x. To make sure, only the relevant code change gets benchmarked, apply [only the patch](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3018.patch) instead of downloading the full branch zip file (that doesn't have much impact, though).

To get some values for MariaDB, I did a rather (possibly silly) benchmark on recent code with and without the above patch applied.

I generated a bunch of posts with devel, created a view with 20 posts per page, disabled page cache, flushed caches and ran:

`ab -n 100 -c 10 -C 'SESSxyz=XYZ' http://my.testdomain.tld/all-posts`

(Both, MariaDB and Apache are on same server, ab run on the same, no network latencies.)

Before every `ab` run I flushed all caches, I ran the command several times, with and without patch, to get some average values.

My conclusion so far: there's no significant difference. At least not on MariaDB. So I'd find it odd if **MySQL** would slow down that much.

**Comment by earlyburg** [comment]
This logic seems quite reasonable, and my curiosity was piqued, so I decided to perform more tests.
Initially, I did a bit of baseline benchmarking for the environment in two ways: First I performed some basic tests on mySql5 and mySql8 to establish a baseline pattern for read write times.
Second, I set up 4 more sites;  fresh installs of WordPress and Backdrop (latest releases) using mySql5, and fresh installs of WordPress and Backdrop (latest releases) using mySql8.

For reference, the names of the sites are bckdrp_mysql5, bckdrp_mysql8, wp_mysql5, wp_mysql8. mySql5 is running on a networked machine, mySql8 is running on localhost.
Testing was performed several times per instance to help weed out anomalies.

Baseline Tests: 
I adapted a script found here: https://tournasdimitrios1.wordpress.com/2012/07/30/benchmarking-mysqli-sqlite/

**For mySql8:**
Db connection established at : 0.00033307
Table created at : 0.00332212
Data inserted into the table at : 0.09619498

**For mySql5:**
Db connection established at : 0.00256801
Table created at : 0.00752997
Data inserted into the table at : 1.80699897
Data is read from table and inserted into an array at : 1.83962703

This seems to follow my hypothesis that the networked db server is going to run a bit slower than localhost.

Next I tested two strictly vanilla installs of WordPress and used a benchmarking plugin called Query Monitor which can be found here: https://wordpress.org/plugins/query-monitor/

This testing yielded the following results:

**wp_mysql5:**
load /wp-admin/edit.php (all posts overview page)
	Page Generation Time - 0.0507
	Database Query Time - 0.0229
	
load /wp-admin/themes.php (themes overview page)
	Page Generation Time - 0.0391
	Database Query Time - 0.0132
	
load /wp-admin/options-general.php (general settings page)
	Page Generation Time - 0.0459
	Database Query Time - 0.0181

**wp_mysql8:**
load /wp-admin/edit.php (all posts overview page)
	Page Generation Time - 0.0290
	Database Query Time - 0.0062
	
load /wp-admin/themes.php (themes overview page)
	Page Generation Time - 0.0225
	Database Query Time - 0.0027
	
load /wp-admin/options-general.php (general settings page)
	Page Generation Time - 0.0235
	Database Query Time - 0.0031
	
Again, the mySql8 performed a bit better on localhost than mySql5 on a networked box.

For our backdrop test, I used the latest release of backdrop. I dropped the patch file into the root of my installation (document root) as somefilename.patch file and
did a "git apply somefilename.patch" to apply it successfully. The backdrop sites were identical and the only contrib module that was installed was the devel module.
	
**bckdrp_mysql5:**
load front page
	Page execution time was 115.35 ms.

load /admin/modules/list (modules listing page)
	Page execution time was 134.41 ms.

load /admin/config/development/devel (devel setting page)
	Page execution time was 54.38 ms.


**bckdrp_mysql8:**
load front page
	Page execution time was 31.58 ms.

load /admin/modules/list (modules listing page)
	Page execution time was 139.54 ms.

load /admin/config/development/devel (devel setting page)
	Page execution time was 18.56 ms.
	
Thanks for inspiring me to take a deeper look into this, I appreciate it. I agree we seem to be good to go with this.

**Comment by earlyburg** [comment]
More testing:

**bckdrp_mysql5:**
load /admin/appearance/list (themes page)
Page execution time was 82.11 ms.

load /admin/config/search/settings (search settings page)
Page execution time was 61.49 ms.

load /admin/reports/fields/list (field list page)
Page execution time was 107.12 ms.

**bckdrp_mysql8:**
load /admin/appearance/list (themes page)
Page execution time was 126.89 ms.

load /admin/config/search/settings (search settings page)
Page execution time was 17.69 ms.

load /admin/reports/fields/list (field list page)
Page execution time was 156.49 ms.

for these pages the speed differences do not seem to have the same proportional speed increase that we see elsewhere in the analysis. This is what I initially felt I noticed.

**Comment by domaingood** [comment]
@earlyburg  Can you provide somefilename.patch file for backdrop MySQL 8 patch I want test it too on my Server.

**Comment by earlyburg** [comment]
@domaingood I used the file that @indigoxela referenced here:
[](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3018.patch
)

**Comment by domaingood** [comment]
Im getting error Why

wget -q -O - https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3018.patch | patch <  3018.patch

can't find file to patch at input line 17
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|From 38654350f0985d2106520932dcaaef7cbdcc5bd1 Mon Sep 17 00:00:00 2001
|From: quicksketch <nate@quicksketch.org>
|Date: Thu, 12 Dec 2019 12:29:23 -0800
|Subject: [PATCH 1/3] Issue #4238: MySQL 8 support.
|
|---
| core/includes/database/mysql/database.inc     | 46 ++++++++++++++++++-
| core/includes/database/mysql/query.inc        |  5 ++
| core/includes/database/query.inc              |  9 +++-
| .../simpletest/tests/database_test.test       |  4 +-
| 4 files changed, 60 insertions(+), 4 deletions(-)
|
|diff --git a/core/includes/database/mysql/database.inc b/core/includes/database/mysql/database.inc
|index daad3f89e6..a370b68311 100644
|--- a/core/includes/database/mysql/database.inc
|+++ b/core/includes/database/mysql/database.inc
--------------------------
File to patch:

**Comment by earlyburg** [comment]
I created a blank text file named mySql.patch
go here: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3018.patch
select all :: copy then paste into mySql.patch, and save it.
Move the mySql.patch file to the web root where backdrop is running
At the command line navigate to your web root
if you dont have a git repo initialized there already you will need one
otherwise type:
sudo git apply mySql.patch
worked for me this way

**Comment by earlyburg** [comment]
> Im getting error Why
> 
> wget -q -O - https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3018.patch | patch < 3018.patch
> ## can't find file to patch at input line 17
> Perhaps you should have used the -p or --strip option?
> The text leading up to this was:
> ## |From 38654350f0985d2106520932dcaaef7cbdcc5bd1 Mon Sep 17 00:00:00 2001
> |From: quicksketch [nate@quicksketch.org](mailto:nate@quicksketch.org)
> |Date: Thu, 12 Dec 2019 12:29:23 -0800
> |Subject: [PATCH 1/3] Issue #4238: MySQL 8 support.
> |
> |---
> | core/includes/database/mysql/database.inc | 46 ++++++++++++++++++-
> | core/includes/database/mysql/query.inc | 5 ++
> | core/includes/database/query.inc | 9 +++-
> | .../simpletest/tests/database_test.test | 4 +-
> | 4 files changed, 60 insertions(+), 4 deletions(-)
> |
> |diff --git a/core/includes/database/mysql/database.inc b/core/includes/database/mysql/database.inc
> |index daad3f89e6..a370b68311 100644
> |--- a/core/includes/database/mysql/database.inc
> |+++ b/core/includes/database/mysql/database.inc
> 
> File to patch:

@domaingood
I created a blank text file named mySql.patch
go here: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3018.patch
select all :: copy then paste into mySql.patch, and save it.
Move the mySql.patch file to the web root where backdrop is running
At the command line navigate to your web root
if you dont have a git repo initialized there already you will need one
otherwise type:
sudo git apply mySql.patch
worked for me this way.

**Comment by quicksketch** [comment]
Thanks folks for all the testing. I'm of the opinion we should merge this into 1.x so it's not so difficult to test, then testers can at least just download the latest `1.x` zip file.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/3018 into 1.x for 1.18.0.

Let's keep this issue open though and consider cherry-picking the fix into 1.17.x (hopefully for 1.17.2).

**Comment by quicksketch** [comment]
I made a new PR specifically for 1.17.x: https://github.com/backdrop/backdrop/pull/3381

It's just a simple cherry-pick of the already merged PR for 1.x.

**Comment by klonos** [comment]
> Let's keep this issue open though...

Reopened 😉

**Comment by quicksketch** [comment]
After 2 weeks with no additional reports of errors and lots of new features being added and tested on the 1.x branch, I think we've received adequate continuous testing of this functionality. I've mentioned on weekly calls that we would be better suited to release this in a non-security bug-fix release, so let's pull in the existing PR for 1.17.2

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3381 into 1.17.x for 1.17.2. This is already in the 1.x branch.
