### ISSUE TITLE
Custom layout template files aren't loading

### ISSUE THREAD

**Issue by Slepana** [backdrop/backdrop-issues#4242]
**Description of the bug**
When selecting any custom layout, it appears to always use the default template file. Only occurs for custom layouts, core layouts work fine. 

**Steps To Reproduce**
To reproduce the behavior:
1. Go to layouts folder of backdrop root folder
2. Add a new folder with files test.info layout--test.tpl.php test.png
3. Create a new layout with Test template

Alternatively:
1. Install Boxton Hero or Senjo contributed layouts
2. Create a new layout with one of the templates provided by them

**Actual behavior**
Block arrangement and count doesn't match what's described in the template.

**Expected behavior**
Block arrangement and count matches what's described in the template.

**Additional information**
- Backdrop CMS version: 1.14.1
- Web server and its version: Apache 2.4 PHP 7.1 MariaDB 5.5

The images are loading, the layouts appear in the list, the issue seems to be the .tpl.php files. I'm attaching a zip file with the test layout I've tried. If I copy the contents of the template file to a core layout it works as intended.
[test.zip](https://github.com/backdrop/backdrop-issues/files/3979129/test.zip)

Please let me know if I can provide more information that can help. I'd love to be more specific, but I've spent literal hours trying to fix this and I have no idea where it goes wrong. I thought I might be doing something wrong, but even contrib layouts don't work.

**Comment by docwilmot** [comment]
This might be this: https://github.com/backdrop/backdrop-issues/issues/3665

Try clearing theme cache.

**Comment by Slepana** [comment]
It helped, thank you so much! I've tried clearing layouts cache, but it didn't occur to me that I need to clear themes cache. And I apologize for missing the other issue, I'm not used to github, I guess I didn't search correctly.

I will add though, while the other issue says that it has to be a manually added template, for me it occurred even with templates I installed using the backdrop administration UI (unless I misunderstand what manually installed means).

**Comment by stpaultim** [comment]
In my opinion, issue #3665 does cover this and we can close this issue. If anyone disagrees, please reopen.

**Comment by klonos** [comment]
Hey @Slepana 👋 ...welcome to the community!

> ...unless I misunderstand what manually installed means

Yup, that's what it means. Can you please add a comment in #3665 to mention that it happened to you when installing via the admin UI?

**Comment by stpaultim** [comment]
Thanks @klonos for the much friendlier and useful response than mine.
