### ISSUE TITLE
Messages cause Views modal windows to muck up

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4246]
**Description of the bug**
When viewing a modal window in Views, if there are any messages displayed at the top of the modal, it causes the bottom of the modal contents to be cut off (i.e. the adjusted height isn't accounted for).

**Steps To Reproduce**
To reproduce the behavior:
1. Open a view (e.g. `/admin/structure/views/view/node_admin_content`)
2. Click on a field (e.g. `Scheduled status flag [hidden]`)
3. In the modal, scroll down to see that all content is displayed nicely in the window (expand the last fieldset to confirm)
4. Put the site in maintenance mode (`/admin/config/development/maintenance`)
5. Repeat steps 1 & 2

**Actual behavior**
The bottom of the content is cut-off/hidden by the modal buttons.

**Expected behavior**
Contents display properly as before.

**Additional information**
![image](https://user-images.githubusercontent.com/2385329/71312784-f3c81a00-2437-11ea-9247-b04b1b564ab2.png)
This screenshot shows the modal window after scrolling all the way to the bottom. Note that the last fieldset ('More') is no longer visible.

The duplicated messages are [another issue](https://github.com/backdrop/backdrop-issues/issues/4247) (not sure why that is), but my suggestion is to either not show messages in modal windows, or to account for their extra height to fix this bug.

**Comment by BWPanda** [comment]
I can no longer reproduce this. Considering no one else has chimed in to say they're experiencing it too, I'll close this issue now. It can be re-opened if someone can update the steps to reproduce.
