### ISSUE TITLE
Date: Do not show remaining days if event is on same day, and time has elapsed

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4248]
The following was reported in #4180 by @indigoxela:

> I concentrated on testing your changes in date.theme.inc.
> 
> Your PR has one glitch, that doesn't appear without the patch:
> 
> If a date is on the same day, but some hours back, the "remaining" text appears, although it shouldn't.
> 
> "Less then 1 day remaining to event." (But the field date is several hours in the past)
> 
> Maybe you need two date_diff? Check if the date isn't already in the past (check time), then get the remaining days?

@klonos 

>> If a date is on the same day, but some hours back, the "remaining" text appears, although it shouldn't.
>
> Oh yes, I have not thought of that @indigoxela, nor tested for it. If I understand this correctly though, you are referring to the use case of an event that has happened already; in which case, the problem is with the logic in `date.theme.inc` - not with the test fixes. So we need to do the following:
> 
> - Account for this use case in `date.theme.inc`, and have the text being shown to users reflect that (something like "Event date/time has passed").
> - Either create a new test case for this use case, or update the logic in the current test to account for it too.
>
> TBH, this sounds like a different issue to what we are trying to solve here, and in fact must be a pre-existing one (without your PR or mine for that matter). This issue here though was/is to fix the random test failures, so separate issue perhaps?

@indigoxela 

>> something like "Event date/time has passed"...
> 
> That would rather be a new feature, as up until now nothing is shown if the date has passed. The display settings help text says "Show remaining days" - I'm not sure if users would expect an "Event has passed" text.

**Comment by indigoxela** [comment]
@klonos I hope, you didn't forget about this issue, did you?

**Comment by indigoxela** [comment]
Assuming that @klonos is too busy currently, I've created a PR.

How to test:

- Create a date field on some content type
- Edit field display setting to show remaining days
- Create content with that date field, test values on same day, still in future or past
- Check the display of "...remaining to event" on node page

**Comment by laryn** [comment]
Tested and it looks good to me.

**Comment by herbdool** [comment]
Code looks good to me - concise.

**Comment by quicksketch** [comment]
Thanks @herbdool for the review and bringing this into RTBC! I've merged https://github.com/backdrop/backdrop/pull/3039 into 1.x and 1.16.x.

Thanks @indigoxela, @klonos, and @laryn for fixing this issue!
