### ISSUE TITLE
[UX] Fixed: Add better help text for Date fields.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4249]
It would certainly use some punctuation, and/or be split into two sentences or shortened:

> Date objects can be created and cached as date fields are loaded rather than when they are displayed to improve performance.

...something like this perhaps:

> Create and cache date objects when date fields are being loaded, rather than when they are being displayed. This improves performance.

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/3027

**Comment by klonos** [comment]
...BTW, if this setting improves performance, why isn't it on by default?

**Comment by klonos** [comment]
Here's another one, for the "Position of date part labels" setting:

> The location of date part labels, like "Year", "Month", or "Day" . "Above" displays the label as titles above each date part. "Hidden" doesn't visually label any of the date parts.

For better UX and readability, the last 2 sentences could be moved under each individual option they are referring to.

**Comment by klonos** [comment]
...there's also a tiny typos in the help text for the "Exclude wrapping fieldset" setting:

> If using simple inputs such a a single textfield or the date popup, omitting the fieldset may provide simpler styling.

- `such a a` -> `such as a`
- `textfield` -> `text field`

How about this:

> Simplify styling when using simple inputs, such as a single text field or the date popup.

**Comment by klonos** [comment]
...filed a PR for all this: https://github.com/backdrop/backdrop/pull/3027

Before:

![Screen Shot 2019-12-28 at 9 06 21 am](https://user-images.githubusercontent.com/2423362/71534211-5f871700-2951-11ea-94a9-febdf8611dfd.png)

After:

![Screen Shot 2019-12-28 at 9 00 00 am](https://user-images.githubusercontent.com/2423362/71534220-6d3c9c80-2951-11ea-87f7-27d2076c3ec5.png)

**Comment by stpaultim** [comment]
These changes look good to me!

**Comment by sudipto68** [comment]
We submitted a new pull request based on the feedback of @BWPanda.
Please provide your valuable feedback.

**Comment by BWPanda** [comment]
Ha, this other duplicate issue was also wanting to update some of this text: https://github.com/backdrop/backdrop-issues/issues/4482 I've closed that one, so we'll work on everything here.

**Comment by BWPanda** [comment]
I've made a suggestion in the PR for how to simplify a chunk of code.

**Comment by stpaultim** [comment]
Updated PR available for review.

**Comment by BWPanda** [comment]
Still needs work.

**Comment by BWPanda** [comment]
@sudipto68 Are you still interested in moving forward with this?

**Comment by stpaultim** [comment]
New PR based upon the work of @sudipto68. Needs testing and code review.

Atten: @klonos

**Comment by kiamlaluno** [comment]
I left a comment about the tense I would rather use.

**Comment by stpaultim** [comment]
@kiamlaluno - Your suggestion made sense to me. I've updated the PR, it's ready for additional review.

**Comment by kiamlaluno** [comment]
I tried to look at the preview site to see the changes, but the site is not even shown. I will try in the morning. (It is 10 PM, here.)

**Comment by stpaultim** [comment]
@kiamlaluno Fixed Sandbox!

**Comment by kiamlaluno** [comment]
I created a date field and changed widget type to see what changed in their settings and the descriptions used for those settings. For what I can see, all has been changed as per issue.

**Comment by quicksketch** [comment]
Thank everyone! I merged https://github.com/backdrop/backdrop/pull/4620 into 1.x and 1.27.x. This is a great improvement to configuring date fields!

https://github.com/backdrop/backdrop/commit/41113e4a7f46c19aca426561e15131cf86e24af0 by @stpaultim, @sudipto68, @BWPanda, @klonos, @kiamlaluno, and @herbdool.
