### ISSUE TITLE
[DX] Consolidate "js-show" and "js-only" classes

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#4252]
**Description of the bug**
Both views_ui.admin.css and system.css provide a way to show contents on pages only if JS is enabled:

system.css:
```
/**
 * For anything you want to show on page load only when JS is enabled.
 */
.js-show {
  display: none;
}
.js .js-show {
  display: block;
}
```

views_ui.admin.css:
```
.js-only {
  display: none;
}

html.js .js-only {
  display: inherit;
}

html.js span.js-only {
  display: inline;
}
```

We should remove the Views-specific one and update all instances of the "js-only" class to use "js-show".

This came up as I was trying to make the Browse button for the image library hide when JS is disabled in #3297.

**Steps to test:**
* Edit the admin_content view
* Click `Rearrange` for filters.
* Click `+ Create new filter group`
* Confirm that the text `Drag to add filters` appears in the new row

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3229 Wonder if it'll 'just work'...?

**Comment by jenlampton** [comment]
Code loos great :)

**Comment by indigoxela** [comment]
This issue seems to be RTBC, but has no milestone nor has it a milestone candidate label. Which milestone is it supposed to have?

**Comment by BWPanda** [comment]
@indigoxela Milestones aren't required. In fact, unless something needs to go into the next bugfix release, then there's not much benefit assigning a milestone, since all issues will go into the next minor release regardless...

**Comment by indigoxela** [comment]
> Milestones aren't required. ... since all issues will go into the next minor release regardless.

@BWPanda many thanks for clarification. My concern was that a fix could get missed because it doesn't appear in the milestone list. I don't know much about the actual core committer workflow, though.

**Comment by BWPanda** [comment]
Worse case scenario is that a bug fix only gets merged into the minor branch (e.g. 1.18.x). But if we notice that before a bugfix release is made, we should be able to include it in the bugfix branch too after-the-fact.

**Comment by quicksketch** [comment]
Thanks folks! Although _very_ minor, I only merged this into 1.x as it's a change that might affect other views plugins, though even in core it was only in use in 5 places, making this seem pretty uncommon. Merged https://github.com/backdrop/backdrop/pull/3229 into 1.x for 1.18.0
