### ISSUE TITLE
1.15: News Block Followup: Switch URL to a config setting and cache the news updates

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4254]
**Description of the need**
Follow up issue to: https://github.com/backdrop/backdrop-issues/issues/3566

We added a block to the Dashboard that will ingest a feed of public notifications from BackdropCMS.org. @quicksketch asked for the following followup issues:

There are a few other things that I think should happen, but can be done in a follow-up:

- The feed URL should come from a config setting in `dashboard.settings.json`.
- We should disable checking for updates at all in all test runs, probably by blanking out that setting in the config file.
- We should add a cache to the HTTP request and update the feed on cron runs rather than doing it on-the-fly.
- Add a test that loads the URL, checks its contents, and verifies that the block displays the feed contents

---

PR https://github.com/backdrop/backdrop/pull/3033

**Comment by jenlampton** [comment]
I added one of @docwilmot's test requests to the issue here too so it wouldn't get lost.

**Comment by quicksketch** [comment]
So I know I approved the current JSON structure, but working on this I found it to be overly nested and cumbersome. I also didn't know that the views_json module allows top-level and individual item keys to be omitted entirely just by leaving the fields blank. I tried updating the view on BackdropCMS.org and we can simplify the nesting from:

```
{
  "notifications" : [
    {
      "notification" : {
        "title" : "Backdrop CMS 1.14.2 Released",
        "summary" : "This is a security release",
        "url" : "https://github.com/backdrop/backdrop/releases/tag/1.14.2"
      }
    },
    {
      "notification" : {
        "title" : "Build a sub-theme of Basis, the default frontend theme of Backdrop",
        "summary" : "Blog post",
        "url" : "https://backdropcms.org/news/build-sub-theme-basis-default-frontend-theme-backdrop"
      }
    },
    {
      "notification" : {
        "title" : "Jan 15th - Join/plan a local Backdrop CMS birthday party",
        "summary" : "We're turning 5 years old this year. ",
        "url" : "https://backdropcms.org/news/its-time-start-planning-your-backdrop-cms-birthday-party"
      }
    }
  ]
}
```

To this, which eliminates the top-level "notifications" as well as the repeated "notification" within each item. I added "id" and "timestamp"  as they could be used for display and caching purposes.

```
[
  {
    "id" : "2680",
    "timestamp" : "1577408647",
    "title" : "Backdrop CMS 1.14.2 Released",
    "summary" : "This is a security release",
    "url" : "https://github.com/backdrop/backdrop/releases/tag/1.14.2"
  },
  {
    "id" : "2679",
    "timestamp" : "1577404566",
    "title" : "Build a sub-theme of Basis, the default frontend theme of Backdrop",
    "summary" : "Blog post",
    "url" : "https://backdropcms.org/news/build-sub-theme-basis-default-frontend-theme-backdrop"
  },
  {
    "id" : "2678",
    "timestamp" : "1577404399",
    "title" : "Jan 15th - Join/plan a local Backdrop CMS birthday party",
    "summary" : "We're turning 5 years old this year. ",
    "url" : "https://backdropcms.org/news/its-time-start-planning-your-backdrop-cms-birthday-party"
  }
]
```

Current: https://backdropcms.org/api/notifications
New: https://backdropcms.org/api/notifications2

Of course if we changed the structure at this point, the 1.15.0-preview release we just made would start throwing errors. But fixing this now would prevent us from having two levels of nesting in our feed structure for years to come.

**Comment by stpaultim** [comment]
@quicksketch - Can we just leave the current feed as it is. Set up a duplicate feed (as you did) at notifications2 and submit a new core PR that uses the new feed for testing.

Then, on Jan 15th before we commit the final change, we change the address (which will be in config at that time) and change the feed over. 

OR

We just break the preview release now and get a new PR working?

I'm good either way.

**Comment by quicksketch** [comment]
I'm inclined towards option 1. We can even use that one at https://backdropcms.org/api/notifications2, and we'll update the URL and feed right before merging.

I've got an update nearly ready for this, so I'll self-assign this issue.

**Comment by quicksketch** [comment]
Initial PR at https://github.com/backdrop/backdrop/pull/3033 that uses the less-nested feed, adds caching, and a config setting for the feed URL.

It still needs to update tests to set the value to NULL to suppress the news checking during test runs.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/3033 updated to suppress news checking during test runs.

**Comment by jenlampton** [comment]
I reviewed the PR and this looks good to go 👍 

I had one question about some of the OO syntax, but I think a procedural wrapper function can/should wait until we are sure it is needed. RTBC!

**Comment by quicksketch** [comment]
Great, I updated the feed to the final location (https://backdropcms.org/api/notifications) in the PR and we can now switch the feed on backdropcms.org. That will break news updates for `1.15.0-pre-release` but we'll have a good feed for the future.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/3033 into 1.x for 1.15.0 and updated the backdropcms.org feed. https://backdropcms.org/api/notifications now uses the simplified data structure.
