### ISSUE TITLE
File Settings form supports tokens but doesn't display them

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4257]
**Description of the bug**
The File Settings form (`/admin/structure/file-types/settings`) supports tokens in the 'Default file directory' field, but there's no link to open the token browser and no other way of viewing them...

**Steps To Reproduce**
To reproduce the behavior:
1. Go to `/admin/structure/file-types/settings`
2. Try to view/add tokens

**Actual behavior**
No apparent way to see what tokens are available.

**Expected behavior**
A link that opens the token browser in a popup.

**Comment by BWPanda** [comment]
Well that was easy: https://github.com/backdrop/backdrop/pull/4014

**Comment by quicksketch** [comment]
@BWPanda I think that perhaps the subsequent lines can be removed from your PR?

```
  $form['default_file_directory']['tokens'] = array(
    '#theme' => 'token_tree',
    '#dialog' => TRUE,
  );
```

Seems as though that might have been an old syntax or some other approach that is not working? The token tree link on the other hand seems to do the job.

**Comment by BWPanda** [comment]
Thanks @quicksketch, PR updated. Tokens still work 👍

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4014 into 1.x and 1.21.x. Thanks @BWPanda!
