### ISSUE TITLE
PHP 7.4: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4263]
I get the following warning when running Backdrop on PHP 7.4:

> Deprecated: Array and string offset access syntax with curly braces is deprecated in /{SNIP}/core/modules/views/handlers/views_handler_filter_string.inc on line 275

I'm pretty sure we don't officially support PHP v7.4 yet, but considering the fix is to use a syntax that works in older versions too then I don't see why we can't fix this easily now.

https://stackoverflow.com/questions/12769982/reference-what-does-this-error-mean-in-php/59158847#59158847 says that it's just a matter of replacing `{}` with `[]` when accessing string offsets or array elements.

---

PR: https://github.com/backdrop/backdrop/pull/3036

**Comment by indigoxela** [comment]
> considering the fix is to use a syntax that works in older versions too

That's not an easy fix.

PHP 5.3 doesn't support [] array syntax at all, we can't support both, 5.3 and 7.4.

See also: https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by BWPanda** [comment]
@indigoxela I think you're referring to `$my_array = [1, 2, 3];` which you're correct that PHP v5.3 doesn't support, but this issue is about *accessing* array elements (not initialising them): `$first = $my_array[0];`

https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.accessing doesn't mention anything about certain PHP versions not supporting the square bracket syntax (unless I'm missing something).

**Comment by indigoxela** [comment]
@BWPanda you're right! I didn't even know that this is supported currently. :wink: Never saw this anywhere before...

That actually looks like an easy fix: https://github.com/backdrop/backdrop/blob/30222aa67e42d9831b615cb7f96680d076393fdb/core/modules/views/handlers/views_handler_filter_string.inc#L275

**Comment by BWPanda** [comment]
Indeed. Here's a PR: https://github.com/backdrop/backdrop/pull/3036 :smiley:

**Comment by indigoxela** [comment]
I found even two more usages of that syntax:

views_handler_filter_combine.inc
https://github.com/backdrop/backdrop/blob/30222aa67e42d9831b615cb7f96680d076393fdb/core/modules/views/handlers/views_handler_filter_combine.inc#L114

search.extender.inc
https://github.com/backdrop/backdrop/blob/30222aa67e42d9831b615cb7f96680d076393fdb/core/modules/search/search.extender.inc#L211

**Comment by BWPanda** [comment]
I'm not sure if there are any other places in core where curly brackets are used in this way. This was just one I noticed when running a sandbox site on PHP v7.4. When I saw the warning and realised what caused it, I changed my sandbox to run on PHP v7.2 instead (no don't have it to test anymore).

**Comment by indigoxela** [comment]
> I'm working on something else ATM

Me too, unfortunately...

**Comment by BWPanda** [comment]
No worries, since I still had the repo open I added those you found to the PR.

**Comment by indigoxela** [comment]
When trying to test your PR I realized some more PHP7.4 issues:

`Notice: Trying to access array offset on value of type int in element_children() (line 7230 of .../core/includes/common.inc).`

Do you prefer to handle it in this current issue or should this be a follow-up issue?

On which pages do you get the Deprecation warning? Can't seem to find it anywhere in the logs, but that's so crowded with the Notice.

I installed php7.4 just now on a Debian VM (sury repo, 7.4.1-1+0~20191218). And I tested with B 1.15.x-dev. But maybe I'm missing something.

**Comment by BWPanda** [comment]
> Do you prefer to handle it in this current issue or should this be a follow-up issue?

If it's a different error/warning/notice then probably a separate issue. This issue can be easily fixed and is backwards-compatible, other PHP v7.4 issues might not be...

I think I saw the notice at the top of the User list page/view (`/admin/people`).

**Comment by indigoxela** [comment]
> I think I saw the notice at the top of the User list page/view (/admin/people).

Still no luck. (I checked "Deprecated" on /admin/config/development/logging).

All I get is tons of the Notice re common.inc I mentioned.

Possibly Debian/sury patched out that deprecation in their php?

**Comment by indigoxela** [comment]
Funny... by chance I came across a possible explanation: when I restart the corresponding php-fpm process (7.4 in this case), the Deprecation warning gets logged _once_ in the error_log.
It never appears in the dblog.

So unfortunately I'm not able to test this PR. I could do a code review, though.

**Comment by klonos** [comment]
FWIW, a long time ago, I have read someplace that PHP treats strings like arrays, so I guess I've always been using that.

Great catch @BWPanda, and thanks @indigoxela for picking up those other 2 places 👍 

> If it's a different error/warning/notice then probably a separate issue. This issue can be easily fixed and is backwards-compatible, other PHP v7.4 issues might not be...

Agreed. RTBC 👍

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/3036 into 1.x and 1.14.x. We also covered this issue during the weekly meeting, which resulted in some banter about PHP version support: https://www.youtube.com/watch?v=QBokPZ8ozZ8
