### ISSUE TITLE
Custom block edits not getting saved

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4268]
**Description of the bug**
Sometimes it takes multiple edits for a custom block to actually save my changes. The custom block is in a layout. When first adding it things are fine but then editing it seems to ignore my changes. I have to repeat it multiple times in order for things to "stick".

**Steps To Reproduce**
To reproduce the behavior:
1. Add a custom block to a layout. Don't make it reusable.
2. Save the layout.
3. Edit the custom block and change the text.
4. Save again. The changes won't appear (or maybe they will but it seems random).

**Comment by laryn** [comment]
@herbdool Do you happen to be switching to source mode on the ones that don't save? If so, that is a long-standing bug (that I unfortunately have no idea how to fix):
https://github.com/backdrop/backdrop-issues/issues/1259

**Comment by herbdool** [comment]
@laryn I think you're right. I'm going to close this.
