### ISSUE TITLE
Possible regression in 1.15.x-dev when adding blocks with file fields

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4270]
**Description of the bug**

When newly adding certain types of blocks to a layout, they don't appear on the "Manage blocks" page after clicking "Add block".

Also the message "This form has unsaved changes. ..." won't show.
After flushing the layout cache via admin menu, or even simply reloading the layout form page, both show in the form (block and message).

**Steps To Reproduce**

1. Go to a layout and add a hero block
2. Save the block

Please note: not all types of blocks seem affected. It only affects block types with a file field like the core Hero block type.

Nothing in dblog, nothing in error_log.

**Expected behavior**
Block and message should show up.

**Additional information**

- Backdrop CMS version: 1.15.x-dev (latest)
- Web server and its version: Apache 2.4
- PHP version 7.2

---

PR by @indigoxela: https://github.com/backdrop/backdrop/pull/3037

**Comment by indigoxela** [comment]
Ah, interesting... If I revert https://github.com/backdrop/backdrop/commit/e7774a046e2ee578cba95b45ada0c59c4346845f in that install, the problem doesn't occur.

That was "Issue #3297: Add file browser capability to file module...."

**Comment by olafgrabienski** [comment]
Confirming the issue, tested with a fresh installation of the 1.15 preview release. As @indigoxela said, not all blocks are affected. In a vanilla site, it's only the Hero block.

@indigoxela: I don't know the Image block module, but I guess the block has an image upload widget, such as the Hero block. Which could indicate a common conflict with the file browser capability commit.

**Comment by indigoxela** [comment]
> I don't know the Image block module, but I guess the block has an image upload widget, such as the Hero block

Yes, that's right.
Unfortunately I'm still clueless, what exactly is happening here.

**Comment by indigoxela** [comment]
OK, slightly more info:

If I comment out `$(window).on('dialog:afterclose.fileBrowser', Backdrop.file.dialogCloseEvent);` (line 237 in core/modules/file/js/file.js) hero and imageblocks work correctly again.

My javascript/ajax fu is very limited. We'll need help with that.

**Comment by indigoxela** [comment]
It turned out that the problem is 100% javascript.

`$browserContainer` exists, but is empty. In addition a js error was logged: 
`TypeError: Backdrop.settings.file is undefined`

Enhancing that check with .length fixes both, the TypeError and the missing block and message in form.

As I already mentioned, my js fu is limited, so please be picky when testing and reviewing.

**Comment by olafgrabienski** [comment]
Thanks for the PR! I've tested it in the PR's sandbox website as well as in a local installation of the 1.15 preview release. It works in both environments: I was able to add a Hero block and an Image block. Both blocks showed up, also the "unsaved changes" message.

**Comment by quicksketch** [comment]
Thanks @indigoxela and @olafgrabienski! You're right! And nice fix. I've merged https://github.com/backdrop/backdrop/pull/3037 into 1.x for 1.15.0.
