### ISSUE TITLE
remove README.txt from the core modules and themes directories

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#428]
Since the core modules directory is now inside the core directory, it will be less likely that people add contributed or custom modules in there. I propose that we remove the README.txt file from the modules directory (and from the themes directory too).

If we really need a README.txt telling people not to add files inside core, shouldn't it be in the root of the core directory now?

**Comment by klonos** [comment]
This is trivial, so I believe we can remove these in 1.0.0
