### ISSUE TITLE
Spelling mistake: "chronologocal"

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4280]
"chronologocal" should be "chronological" (in the comment module).

![Screen Shot 2020-01-17 at 2 24 40 PM](https://user-images.githubusercontent.com/871421/72643836-30067180-3935-11ea-9037-6837dd61dffb.jpg)

---

PR: https://github.com/backdrop/backdrop/pull/3042

**Comment by docwilmot** [comment]
Maybe this might be a good time to improve the language a bit: 
> 'A threaded list differs from chronological in that each comment follows

to 
> 'A threaded list differs from a chronological list in that each comment follows

**Comment by indigoxela** [comment]
I wonder if this PR is ready for review, or if the wording improvement is likely to get added.

If the latter is the case, please adapt the labels accordingly. :wink:

**Comment by laryn** [comment]
Updated the PR.

**Comment by indigoxela** [comment]
@laryn many thanks for your update.

Looks good to me.

![screenshot-spelling-fix](https://user-images.githubusercontent.com/842066/73243484-f12fb180-41a7-11ea-8d04-46521049c7bb.png)

**Comment by quicksketch** [comment]
Thanks folks! Looks great. Merged https://github.com/backdrop/backdrop/pull/3042 into 1.x and 1.15.x.
