### ISSUE TITLE
Disabling a text format does not clear configuration files

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4282]
**Description of the bug**
Disabling a text format on the `/admin/config/content/formats` page does not delete its configuration json file (as filter.format.php_code.json) and the respective entry in the `user.role.administrator.json` file.

**Steps To Reproduce**
To reproduce the behavior:
1. Just create a custom text format on the `/admin/config/content/formats` page (Let's call it `plain_filter`)
2. The disable it on the same page. 

**Actual behavior**

Now if you run the following command in CLI:

```
grep -Ril "plain_filter" /var/www/docroot/files/config_*/active/
```
and you will see two configuration files:

```
filter.format.plain_filter.json
user.role.administrator.json
```

**Expected behavior**

Disabling a text format is kind of equivalent of completely removing it, because you can't bring it back as re-creating another text format with the same machine name is prevented. 

In fact, I wanted to completely ditch the format, however I couldn't find the option for removing the text format. So I believe `disabling` instead is there intentionally. Which is confirmed by the warning text on the next page:

> Disabled text formats are completely removed from the administrative interface, and any content stored with that format will not be displayed. This action cannot be undone.

So it says only about removing from the administrative interface and not removing it from the system and the configuration files. I am not sure if that's intentional, for example, in order not to break existing content that used the deleted text format. 

However imagine one creates multiple text formats for any reason, then decides to ditch them all leaving only the initial three text formats. Does his website exist forever with completely unnecessary configuration files for the deleted (pardon disabled) text formats?

I see two different and yet related issues here:

1) The wording should be clarified to users on UI why it is `disabling` and not `removing` - maybe in description field. If it was supposed to be `removing`, then the wording should be changed.

2) I'd like Backdrop core to take proper care of its configuration files and remove all the unnecessary files and entries and to expect the contributed modules do the same.

**Comment by BWPanda** [comment]
@alanmels See this related issue https://github.com/backdrop/backdrop-issues/issues/1575

**Comment by alanmels** [comment]
@BWPanda Thanks for the link. Closing this one in favor of https://github.com/backdrop/backdrop-issues/issues/1575
