### ISSUE TITLE
Disabling JavaScript with Views doesn't work properly

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4283]
This might be related to https://github.com/backdrop/backdrop-issues/issues/3734, but since I was not sure I decided to file a separate bug report.

**Description of the bug**
Disabling JavaScript on Views' Advanced settings page (http://view.docksal/admin/structure/views/settings/advanced) does not have full effect: it **does**  open the option links on a regular window (instead of a pop-up modal one), but it **does not** close the option page to return to the initial page.

**Steps To Reproduce**

To reproduce the behavior:
1. Go to `/admin/structure/views/settings/advanced`, select the `Disable JavaScript with Views` option and press on the `Save Settings` button.
2. Go to any views configuration page (for example to `Administer content (Content)`  at `admin/structure/views/view/node_admin_content`).
3. Click on any option (for example Path :/admin/content/node), which will take you to `/admin/structure/views/nojs/display/node_admin_content/page/path`.
4. Click on Apply or Cancel button to be stuck at the same page.

![views-ajax-fail](https://user-images.githubusercontent.com/56604405/72691926-23754b00-3ae6-11ea-9820-870458d34bc0.gif)

**Expected behavior**
Expected behavior was returning to previous screen as on Drupal 7:

![works-on-d7](https://user-images.githubusercontent.com/56604405/72691953-5fa8ab80-3ae6-11ea-8e33-bb4c03175601.gif)

**Comment by indigoxela** [comment]
Confirmed, views still uses js/ajax for *some* buttons, even if this setting is active.

But...
Disabling javascript for views doesn't fully work in Drupal 7 either, it's very alike to how it works in Backdrop (but not the same).
Drupal 8 has _removed_ that setting completely.

Should we remove it in Backdrop, too?

**Comment by alanmels** [comment]
My opinion is that if it's not possible to fix it, then removing is better than leaving at the current state, which looks like broken.

**Comment by indigoxela** [comment]
I'm all for removing that setting.
It's also broken in Drupal 7 (who knows how long) and no one seems to miss it. And it has been removed in Drupal 8.
I'm using Drupal and Views for many years now, and not once did I use that option.

So here's a [PR](https://github.com/backdrop/backdrop/pull/3050).

I need some guidance regarding function views_update_2000() - is that done the right way? Is the numbering correct?

**Comment by BWPanda** [comment]
@indigoxela You'd use `views_update_2000()` if this were only to happen when Backdrop 2.x comes out (which isn't for another few years yet). Not sure if that was your intention...?

**Comment by indigoxela** [comment]
> You'd use views_update_2000() if this were only to happen when Backdrop 2.x comes out

Yeah, that's why I ask here. The [comment text](https://github.com/backdrop/backdrop/blob/9ed127933df9994ec3e96f9110520359451a183d/core/modules/views/views.install#L191
) somewhat confuses me:

```
/**
 * @} End of "addtogroup updates-7.x-to-1.x"
 * The next series of updates should start at 2000.
 */
```

**Comment by BWPanda** [comment]
So that comment matches this initial comment: https://github.com/backdrop/backdrop/blob/9ed127933df9994ec3e96f9110520359451a183d/core/modules/views/views.install#L29

Basically everything between them is the updates for people upgrading from Drupal 7 or Backdrop 1. Hence everything after that final comment is for Backdrop 2.

Your `views_update_1007()` should go directly after views_update_1006() and *before* the comment you linked to.

**Comment by indigoxela** [comment]
@BWPanda many thanks for your explanation. This "addtogroup updates-7.x-to-1.x" really confused me.

PR has been updated.

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
Thanks @indigoxela for the PR! I've merged https://github.com/backdrop/backdrop/pull/3050 into 1.x and 1.16.x.

Thanks @alanmels for reporting this issue. And @BWPanda and @herbdool for reviewing the PR and providing input. :smile:

**Comment by alanmels** [comment]
Thanks for working on this guys!
