### ISSUE TITLE
Remove 'Spock' from Backdrop.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4286]
I'm looking at the Dashboard welcome block properly for the first time and I have some thoughts:

- Change the block icon
  Don't know why we have the Star Trek/Spock/Live-long-and-prosper icon there (apart from maybe we were feeling geeky at the time), but I think this should be changed to look more professional; something like https://fontawesome.com/icons/comment?style=solid, https://fontawesome.com/icons/handshake?style=solid, https://fontawesome.com/icons/smile?style=solid, or just the Backdrop mark logo.
- ~~Reword 'modules' to 'functionality'~~ Others don't seem to mind this wording, so leaving for now...
  'Functionality' is the term we use in the top-level of the admin bar (I know the term 'module' is used in the sub-links, but that's not what people see initially, and it's a bit of a Drupal-ism). We should use something like this wording instead for the first two items in the 'More actions' column respectively: 'Toggle existing functionality' (or 'Turn existing functionality on or off' if we don't like the word 'toggle'), 'Add new functionality'.

Current block:

![Dashboard___Luke](https://user-images.githubusercontent.com/3144571/73142399-ac930180-4053-11ea-8757-a2c8626e2f5f.png)

**Comment by stpaultim** [comment]
> Don't know why we have the Star Trek/Spock/Live-long-and-prosper icon there

I always thought of that as a wave. But, I admit it's an unusual wave. I have no strong feelings about which icon to use. The existing or either suggestion work for me. 

How about:
* Enable or disable functionality

Not sure if thats an improvement.

**Comment by olafgrabienski** [comment]
> Star Trek/Spock/Live-long-and-prosper icon [...] should be changed to look more professional

Good point, @bwpanda! All your suggestions (comment/speech bubble, handshake, smiley) look more professional. I'd prefer the speech bubble as the most neutral icon of the three (being however fine with each of them).

> Reword 'modules' to 'functionality'

In my opinion it's more helpful to have *both* terms here, "functionality" and "modules". "Functionality" works fine as a generic term but not as a word for a concrete thing like a *module*. In my opinion, the sentence `Add new modules for more functionality` which contains both terms explains the concept very good. I'd even suggest to put that sentence first:

> **More actions**
> Add new modules for more functionality
> Turn existing modules on or off
> [...]

**Comment by BWPanda** [comment]
That 'Spock' hand annoys me everytime I see it. Here's a PR to replace it with the Backdrop logo mark: https://github.com/backdrop/backdrop/pull/3375

![image](https://user-images.githubusercontent.com/2385329/95936105-8f3fd680-0e20-11eb-9c70-99b8d9eb7ac2.png)

**Comment by BWPanda** [comment]
Doesn't seem like others mind the current wording, so I'll rename this issue to just be about the icon.

**Comment by indigoxela** [comment]
Oh, spock got fired... :wink: But I agree, the Backdrop logo makes more sense here. Works as expected.

![spock-gone](https://user-images.githubusercontent.com/842066/95951748-43c50280-0df7-11eb-9d14-df856395f27d.png)

I still hesitate to mark this issue RTBC, although the code's looking good, because I'm not sure yet, if we really have consensus. Do we?

**Comment by stpaultim** [comment]
I've never had a problem with Spock. ;-) 

BUT, I agree that this is an improvement.

**Comment by olafgrabienski** [comment]
I agree as well.

**Comment by indigoxela** [comment]
Looks like we have consensus.

**Comment by klonos** [comment]
> ...maybe we were feeling geeky at the time

Yup, it was exactly that 😅 ...I didn't mind the Spock hand, but I also like the Backdrop icon, so 👍 form me as well.

**Comment by BWPanda** [comment]
Thanks everyone! I've merged https://github.com/backdrop/backdrop/pull/3375 into 1.x and 1.17.x.
