### ISSUE TITLE
Easier way to distinguish Filter log and Clear log on dblog page

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4287]
**Description of the need**
Not for the first time I almost deleted all dblog messages instead of filtering.
It's the switched order on dblog page (admin/reports/dblog) compared to Drupal 7 that tricks me.

In Drupal 7 _Filter_ comes first, in Backdrop _Clear_ comes first. What a trap!

From a new user's perspective the order is better in Backdrop (Filter closer to the log table), but for people who are using both (D7 and B) it's a little dangerous.
Drupal 8 moved the Clear form item to a different tab.

**Proposed solution**
Either somehow better distinguish (color?) Filter and Clear, or move Clear to a tab like D8, or move Clear below the table... Not sure, what's best.

In Drupal Filter comes first:
![drupal-dblog](https://user-images.githubusercontent.com/842066/72984508-2624b880-3de4-11ea-9e74-07958df590fe.png)

In Backdrop Clear comes first:
![backdrop-dblog](https://user-images.githubusercontent.com/842066/72984516-2ae96c80-3de4-11ea-86ce-60d248089640.png)

That's a real pitfall for distracted admins. :wink:

**Comment by olafgrabienski** [comment]
> It's the switched order on dblog page (...) compared to Drupal 7 that tricks me.

Oh yes, that happens to me all the time, even after nearly two years :-/ The order was changed as part of https://github.com/backdrop/backdrop-issues/issues/3064, see https://github.com/backdrop/backdrop-issues/issues/3064#issuecomment-385198076.

> Either somehow better distinguish (color?) Filter and Clear, or move Clear to a tab like D8, or move Clear below the table... Not sure, what's best.

I'm also not sure. As I don't clear the logs often, I'd be fine with moving that action out of focus. Separate tab or below the log table, both would be fine for me. The latter was discussed in #2353, and there were some objections which in turn lead to #3064, so we're getting kind of circular now.

**Comment by jenlampton** [comment]
As mentioned in the other issue all other filters in Backdrop come immediately above the listing, so this is the only page that has them backwards in Drupal 7. For someone coming from D7 it could be jarring, but to everyone else the way D7 is odd.

@indigoxela I'd be curious about your feedback on https://github.com/backdrop/backdrop-issues/issues/2353. Would it be better/safer to move that delete button to the bottom of the page, out of the way entirely?

**Comment by indigoxela** [comment]
@jenlampton many thanks for pointing me to that other issue.

Reading that thread makes me think, this one here is actually a duplicate. So I'm closing it in favor of #2353.
