### ISSUE TITLE
Typo in taxonomy_vocabulary_load_multiple

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4288]
**Description of the bug**
There's a typo in `taxonomy_vocabulary_load_multiple` docblock. 

`@param $vocabulary_names` should be `@param $machine_names`

---

PR: https://github.com/backdrop/backdrop/pull/3046

**Comment by jenlampton** [comment]
Since the typo is in a docblock I'm changing the type from bug to task but either way we have  PR so this can go in the next bug-fix release :)

**Comment by jenlampton** [comment]
Code looks great, RTBC!

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/3046 into 1.x and 1.15.x.
