### ISSUE TITLE
Replace $vars with $variables in color module

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#429]
Back in Drupal 7, we replaced almost all instances of $vars with $variables.  Looks like good old color module was overlooked.  Anyone want to tackle a little find / replace in color module and get all our variables spelled out?

- [x] | Color module
- [x] | Comment module (views)
- [x] | Node module (views)
- [x] | Search module (views)
- [x] | Views module
- [x] | Views UI module

**Comment by quicksketch** [comment]
Color module was fixed in https://github.com/backdrop/backdrop/pull/707. There are probably still lots of others. Should we start a list?

**Comment by serundeputy** [comment]
does this help?
`
./core/includes/evalmath.inc:295:  function pfx($tokens, $vars = array()) {
./core/includes/evalmath.inc:344:        } elseif (array_key_exists($token, $vars)) {
./core/includes/evalmath.inc:345:          $stack->push($vars[$token]);
./core/includes/gettext.inc:348:  $vars = array('%filename' => $file->filename);
./core/includes/gettext.inc:350:    $vars['%line'] = $lineno;
./core/includes/gettext.inc:353:  backdrop_set_message($t($message, $vars), 'error');
./core/modules/comment/views/comment.views.inc:650:function template_preprocess_views_view_row_comment(&$vars) {
./core/modules/comment/views/comment.views.inc:651:  $options = $vars['options'];
./core/modules/comment/views/comment.views.inc:652:  $view = &$vars['view'];
./core/modules/comment/views/comment.views.inc:654:  $comment = $plugin->comments[$vars['row']->{$vars['field_alias']}];
./core/modules/comment/views/comment.views.inc:670:  $vars['comment'] = backdrop_render($build);
./core/modules/node/views/node.views.inc:715:function node_row_node_view_preprocess_node(&$vars) {
./core/modules/node/views/node.views.inc:716:  $node = $vars['node'];
./core/modules/node/views/node.views.inc:717:  $options = $vars['view']->style_plugin->row_plugin->options;
./core/modules/node/views/node.views.inc:720:  if ($vars['view_mode'] == 'full' && !$vars['view']->display_handler->has_path()) {
./core/modules/node/views/node.views.inc:725:    unset($vars['content']['links']);
./core/modules/node/views/node.views.inc:729:    $vars['content']['comments'] = comment_node_page_additions($node);
./core/modules/search/views/search.views.inc:160:function template_preprocess_views_view_row_search(&$vars) {
./core/modules/search/views/search.views.inc:161:  $vars['node'] = ''; // make sure var is defined.
./core/modules/search/views/search.views.inc:162:  $nid = $vars['row']->nid;
./core/modules/search/views/search.views.inc:184:  $vars['url'] = url('node/' . $nid);
./core/modules/search/views/search.views.inc:185:  $vars['title'] = check_plain($node->title);
./core/modules/search/views/search.views.inc:195:  $vars['info_split'] = $info;
./core/modules/search/views/search.views.inc:196:  $vars['info'] = implode(' - ', $info);
./core/modules/search/views/search.views.inc:198:  $vars['node'] = $node;
./core/modules/search/views/search.views.inc:200://$vars['score'] = $item->score;
./core/modules/search/views/search.views.inc:201:  $vars['snippet'] = search_excerpt($vars['view']->value, $node->body);
./core/modules/views/templates/views.theme.inc:44:function template_preprocess_views_view(&$vars) {
./core/modules/views/templates/views.theme.inc:47:  $view = $vars['view'];
./core/modules/views/templates/views.theme.inc:49:  $vars['rows']       = (!empty($view->result) || $view->style_plugin->even_empty()) ? $view->style_plugin->render($view->result) : '';
./core/modules/views/templates/views.theme.inc:51:  $vars['css_name']   = backdrop_clean_css_identifier($view->name);
./core/modules/views/templates/views.theme.inc:52:  $vars['name']       = $view->name;
./core/modules/views/templates/views.theme.inc:53:  $vars['display_id'] = $view->current_display;
./core/modules/views/templates/views.theme.inc:56:  $vars['css_class'] = '';
./core/modules/views/templates/views.theme.inc:58:  $vars['classes'] = array();
./core/modules/views/templates/views.theme.inc:59:  $vars['classes'][] = 'view';
./core/modules/views/templates/views.theme.inc:60:  $vars['classes'][] = 'view-' . backdrop_clean_css_identifier($vars['name']);
./core/modules/views/templates/views.theme.inc:61:  $vars['classes'][] = 'view-id-' . $vars['name'];
./core/modules/views/templates/views.theme.inc:62:  $vars['classes'][] = 'view-display-id-' . $vars['display_id'];
./core/modules/views/templates/views.theme.inc:66:    $vars['css_class'] = preg_replace('/[^a-zA-Z0-9- ]/', '-', $css_class);
./core/modules/views/templates/views.theme.inc:67:    $vars['classes'][] = $vars['css_class'];
./core/modules/views/templates/views.theme.inc:70:  $empty = empty($vars['rows']);
./core/modules/views/templates/views.theme.inc:72:  $vars['header'] = $view->display_handler->render_area('header', $empty);
./core/modules/views/templates/views.theme.inc:73:  $vars['footer'] = $view->display_handler->render_area('footer', $empty);
./core/modules/views/templates/views.theme.inc:75:    $vars['empty'] = $view->display_handler->render_area('empty', $empty);
./core/modules/views/templates/views.theme.inc:78:  $vars['exposed']    = !empty($view->exposed_widgets) ? $view->exposed_widgets : '';
./core/modules/views/templates/views.theme.inc:79:  $vars['more']       = $view->display_handler->render_more_link();
./core/modules/views/templates/views.theme.inc:80:  $vars['feed_icon']  = !empty($view->feed_icon) ? $view->feed_icon : '';
./core/modules/views/templates/views.theme.inc:82:  $vars['pager']      = '';
./core/modules/views/templates/views.theme.inc:86:  $vars['title'] = !empty($view->views_ui_context) ? filter_xss_admin($view->get_title()) : '';
./core/modules/views/templates/views.theme.inc:90:    $vars['pager']      = $view->query->render_pager($exposed_input);
./core/modules/views/templates/views.theme.inc:93:  $vars['attachment_before'] = !empty($view->attachment_before) ? $view->attachment_before : '';
./core/modules/views/templates/views.theme.inc:94:  $vars['attachment_after'] = !empty($view->attachment_after) ? $view->attachment_after : '';
./core/modules/views/templates/views.theme.inc:102:  views_add_contextual_links($vars['view_array'], 'view', $view, $view->current_display);
./core/modules/views/templates/views.theme.inc:116:    $vars['dom_id'] = $view->dom_id;
./core/modules/views/templates/views.theme.inc:117:    $vars['classes'][] = 'view-dom-id-' . $vars['dom_id'];
./core/modules/views/templates/views.theme.inc:126:          'views_dom_id:' . $vars['dom_id'] => array(
./core/modules/views/templates/views.theme.inc:134:            'view_dom_id' => $vars['dom_id'],
./core/modules/views/templates/views.theme.inc:149:    $output = !empty($vars['rows']) ? $vars['rows'] : $vars['empty'];
./core/modules/views/templates/views.theme.inc:154:      $vars['header'] = '';
./core/modules/views/templates/views.theme.inc:155:      $vars['exposed'] = '';
./core/modules/views/templates/views.theme.inc:156:      $vars['pager'] = '';
./core/modules/views/templates/views.theme.inc:157:      $vars['footer'] = '';
./core/modules/views/templates/views.theme.inc:158:      $vars['more'] = '';
./core/modules/views/templates/views.theme.inc:159:      $vars['feed_icon'] = '';
./core/modules/views/templates/views.theme.inc:161:    $vars['rows'] = $form;
./core/modules/views/templates/views.theme.inc:168:function template_preprocess_views_view_fields(&$vars) {
./core/modules/views/templates/views.theme.inc:169:  $view = $vars['view'];
./core/modules/views/templates/views.theme.inc:173:  $vars['fields'] = array(); // ensure it's at least an empty array.
./core/modules/views/templates/views.theme.inc:178:    if (empty($field->options['exclude']) && (!$empty || (empty($field->options['hide_empty']) && empty($vars['options']['hide_empty'])))) {
./core/modules/views/templates/views.theme.inc:181:      $object->inline = !empty($vars['options']['inline'][$id]);
./core/modules/views/templates/views.theme.inc:183:      $object->element_type = $object->handler->element_type(TRUE, !$vars['options']['default_field_elements'], $object->inline);
./core/modules/views/templates/views.theme.inc:211:      if (isset($view->field[$id]->field_alias) && isset($vars['row']->{$view->field[$id]->field_alias})) {
./core/modules/views/templates/views.theme.inc:212:        $object->raw = $vars['row']->{$view->field[$id]->field_alias};
./core/modules/views/templates/views.theme.inc:218:      if (!empty($vars['options']['separator']) && $previous_inline && $object->inline && $object->content) {
./core/modules/views/templates/views.theme.inc:219:        $object->separator = filter_xss_admin($vars['options']['separator']);
./core/modules/views/templates/views.theme.inc:226:      if ($object->inline_html === '' && $vars['options']['default_field_elements']) {
./core/modules/views/templates/views.theme.inc:265:        $object->element_label_type = $object->handler->element_label_type(TRUE, !$vars['options']['default_field_elements']);
./core/modules/views/templates/views.theme.inc:291:      $vars['fields'][$id] = $object;
./core/modules/views/templates/views.theme.inc:300:function theme_views_view_grouping($vars) {
./core/modules/views/templates/views.theme.inc:301:  $view = $vars['view'];
./core/modules/views/templates/views.theme.inc:302:  $title = $vars['title'];
./core/modules/views/templates/views.theme.inc:303:  $content = $vars['content'];
./core/modules/views/templates/views.theme.inc:316:function template_preprocess_views_view_grouping(&$vars) {
./core/modules/views/templates/views.theme.inc:317:  $vars['content'] = $vars['view']->style_plugin->render_grouping_sets($vars['rows'], $vars['grouping_level']);
./core/modules/views/templates/views.theme.inc:327:function theme_views_view_field($vars) {
./core/modules/views/templates/views.theme.inc:328:  $view = $vars['view'];
./core/modules/views/templates/views.theme.inc:329:  $field = $vars['field'];
./core/modules/views/templates/views.theme.inc:330:  $row = $vars['row'];
./core/modules/views/templates/views.theme.inc:331:  return $vars['output'];
./core/modules/views/templates/views.theme.inc:341:function template_preprocess_views_view_field(&$vars) {
./core/modules/views/templates/views.theme.inc:342:  $vars['output'] = $vars['field']->advanced_render($vars['row']);
./core/modules/views/templates/views.theme.inc:348:function template_preprocess_views_view_summary(&$vars) {
./core/modules/views/templates/views.theme.inc:349:  $view     = $vars['view'];
./core/modules/views/templates/views.theme.inc:351:  $vars['row_classes'] = array();
./core/modules/views/templates/views.theme.inc:368:  foreach ($vars['rows'] as $id => $row) {
./core/modules/views/templates/views.theme.inc:373:  foreach ($vars['rows'] as $id => $row) {
./core/modules/views/templates/views.theme.inc:374:    $vars['row_classes'][$id] = '';
./core/modules/views/templates/views.theme.inc:376:    $vars['rows'][$id]->link = $argument->summary_name($row);
./core/modules/views/templates/views.theme.inc:384:    $vars['rows'][$id]->url = url($view->get_url($args, $base_path), $url_options);
./core/modules/views/templates/views.theme.inc:385:    $vars['rows'][$id]->count = intval($row->{$argument->count_alias});
./core/modules/views/templates/views.theme.inc:386:    if (isset($active_urls[$vars['rows'][$id]->url])) {
./core/modules/views/templates/views.theme.inc:387:      $vars['row_classes'][$id] = 'active';
./core/modules/views/templates/views.theme.inc:396:function template_preprocess_views_view_summary_unformatted(&$vars) {
./core/modules/views/templates/views.theme.inc:397:  $view     = $vars['view'];
./core/modules/views/templates/views.theme.inc:399:  $vars['row_classes'] = array();
./core/modules/views/templates/views.theme.inc:416:  foreach ($vars['rows'] as $id => $row) {
./core/modules/views/templates/views.theme.inc:421:  foreach ($vars['rows'] as $id => $row) {
./core/modules/views/templates/views.theme.inc:424:      $vars['rows'][$id]->separator = filter_xss_admin($vars['options']['separator']);
./core/modules/views/templates/views.theme.inc:426:    $vars['rows'][$id]->link = $argument->summary_name($row);
./core/modules/views/templates/views.theme.inc:434:    $vars['rows'][$id]->url = url($view->get_url($args, $base_path), $url_options);
./core/modules/views/templates/views.theme.inc:435:    $vars['rows'][$id]->count = intval($row->{$argument->count_alias});
./core/modules/views/templates/views.theme.inc:436:    if (isset($active_urls[$vars['rows'][$id]->url])) {
./core/modules/views/templates/views.theme.inc:437:      $vars['row_classes'][$id] = 'active';
./core/modules/views/templates/views.theme.inc:445:function template_preprocess_views_view_table(&$vars) {
./core/modules/views/templates/views.theme.inc:446:  $view     = $vars['view'];
./core/modules/views/templates/views.theme.inc:448:  // We need the raw data for this grouping, which is passed in as $vars['rows'].
./core/modules/views/templates/views.theme.inc:450:  // therefore swap the raw data out to a new variable and reset $vars['rows']
./core/modules/views/templates/views.theme.inc:453:  $result   = $vars['result'] = $vars['rows'];
./core/modules/views/templates/views.theme.inc:454:  $vars['rows'] = array();
./core/modules/views/templates/views.theme.inc:455:  $vars['field_classes'] = array();
./core/modules/views/templates/views.theme.inc:456:  $vars['header'] = array();
./core/modules/views/templates/views.theme.inc:483:    $vars['fields'][$field] = backdrop_clean_css_identifier($field);
./core/modules/views/templates/views.theme.inc:485:      $vars['fields'][$field] .= ' active';
./core/modules/views/templates/views.theme.inc:492:        $vars['header'][$field] = $label;
./core/modules/views/templates/views.theme.inc:513:        $vars['header'][$field] = l($label, $_GET['q'], $link_options);
./core/modules/views/templates/views.theme.inc:516:      $vars['header_classes'][$field] = array();
./core/modules/views/templates/views.theme.inc:519:        $vars['header_classes'][$field][] = "views-field";
./core/modules/views/templates/views.theme.inc:520:        $vars['header_classes'][$field][] = "views-field-" . $vars['fields'][$field];
./core/modules/views/templates/views.theme.inc:524:        $vars['header_classes'][$field][] = $class;
./core/modules/views/templates/views.theme.inc:528:        $vars['header_classes'][$field][] = backdrop_clean_css_identifier($options['info'][$field]['align']);
./core/modules/views/templates/views.theme.inc:532:        $vars['header_classes'][$field][] = 'active';
./core/modules/views/templates/views.theme.inc:536:      if ($vars['header'][$field]) {
./core/modules/views/templates/views.theme.inc:539:          $vars['header'][$field] = '<' . $element_label_type . '>' . $vars['header'][$field] . '</' . $element_label_type . '>';
./core/modules/views/templates/views.theme.inc:547:      if (in_array(RESPONSIVE_PRIORITY_MEDIUM, $vars['header_classes'][$field])) {
./core/modules/views/templates/views.theme.inc:550:      elseif (in_array(RESPONSIVE_PRIORITY_LOW, $vars['header_classes'][$field])) {
./core/modules/views/templates/views.theme.inc:557:      $vars['fields'][$field] .= ' ' . backdrop_clean_css_identifier($options['info'][$field]['align']);
./core/modules/views/templates/views.theme.inc:563:      $vars['field_attributes'][$field][$num] = array();
./core/modules/views/templates/views.theme.inc:564:      $vars['field_classes'][$field][$num] = array();
./core/modules/views/templates/views.theme.inc:566:        $vars['field_classes'][$field][$num][] = "views-field";
./core/modules/views/templates/views.theme.inc:567:        $vars['field_classes'][$field][$num][] = "views-field-" . $vars['fields'][$field];
./core/modules/views/templates/views.theme.inc:572:        $vars['field_classes'][$field][$num][] = $responsive_columns[$field];
./core/modules/views/templates/views.theme.inc:576:        $vars['field_classes'][$field][$num] = array_merge($vars['field_classes'][$field][$num], $classes_array);
./core/modules/views/templates/views.theme.inc:587:        if (empty($field_output) && !empty($vars['rows'][$num][$column])) {
./core/modules/views/templates/views.theme.inc:592:        if (!empty($vars['rows'][$num][$column])) {
./core/modules/views/templates/views.theme.inc:594:            $vars['rows'][$num][$column] .= filter_xss_admin($options['info'][$column]['separator']);
./core/modules/views/templates/views.theme.inc:598:          $vars['rows'][$num][$column] = '';
./core/modules/views/templates/views.theme.inc:601:        $vars['rows'][$num][$column] .= $field_output;
./core/modules/views/templates/views.theme.inc:608:      foreach ($vars['rows'] as $num => $columns) {
./core/modules/views/templates/views.theme.inc:612:        foreach ($vars['rows'] as $num => &$column_items) {
./core/modules/views/templates/views.theme.inc:614:          unset($vars['header'][$column]);
./core/modules/views/templates/views.theme.inc:621:  if (!array_filter($vars['header'])) {
./core/modules/views/templates/views.theme.inc:622:    $vars['header'] = array();
./core/modules/views/templates/views.theme.inc:626:  foreach ($vars['rows'] as $num => $row) {
./core/modules/views/templates/views.theme.inc:627:    $vars['row_classes'][$num] = array();
./core/modules/views/templates/views.theme.inc:629:      $vars['row_classes'][$num][] = ($count++ % 2 == 0) ? 'odd' : 'even';
./core/modules/views/templates/views.theme.inc:632:      $vars['row_classes'][$num][] = $row_class;
./core/modules/views/templates/views.theme.inc:637:    $vars['row_classes'][0][] = 'first';
./core/modules/views/templates/views.theme.inc:638:    $vars['row_classes'][count($vars['row_classes']) - 1][] = 'last';
./core/modules/views/templates/views.theme.inc:641:  $vars['classes'] = array('views-table');
./core/modules/views/templates/views.theme.inc:642:  if (empty($vars['rows']) && !empty($options['empty_table'])) {
./core/modules/views/templates/views.theme.inc:643:    $vars['rows'][0][0] = $view->display_handler->render_area('empty');
./core/modules/views/templates/views.theme.inc:645:    $vars['field_attributes'][0][0]['colspan'] = count($vars['header']);
./core/modules/views/templates/views.theme.inc:646:    $vars['field_classes'][0][0] = array('views-empty');
./core/modules/views/templates/views.theme.inc:652:    $vars['classes'][] = 'sticky-enabled';
./core/modules/views/templates/views.theme.inc:660:    $vars['classes'][] = 'responsive-enabled';
./core/modules/views/templates/views.theme.inc:662:  $vars['classes'][] = 'cols-'. count($vars['header']);
./core/modules/views/templates/views.theme.inc:666:    $vars['attributes'] = array('summary' => filter_xss_admin($handler->options['summary']));
./core/modules/views/templates/views.theme.inc:671:    $vars['caption'] = filter_xss_admin($handler->options['caption']);
./core/modules/views/templates/views.theme.inc:674:    $vars['caption'] = '';
./core/modules/views/templates/views.theme.inc:681:function template_preprocess_views_view_grid(&$vars) {
./core/modules/views/templates/views.theme.inc:682:  $view     = $vars['view'];
./core/modules/views/templates/views.theme.inc:699:    foreach ($vars['rows'] as $row_index => $item) {
./core/modules/views/templates/views.theme.inc:722:    $num_rows = floor(count($vars['rows']) / $columns);
./core/modules/views/templates/views.theme.inc:724:    $remainders = count($vars['rows']) % $columns;
./core/modules/views/templates/views.theme.inc:727:    foreach ($vars['rows'] as $count => $item) {
./core/modules/views/templates/views.theme.inc:764:    $vars['row_classes'][$row_number] = $row_classes;
./core/modules/views/templates/views.theme.inc:781:      $vars['column_classes'][$row_number][$column_number] = $column_classes;
./core/modules/views/templates/views.theme.inc:784:  $vars['rows'] = $rows;
./core/modules/views/templates/views.theme.inc:785:  $vars['classes'] = array('views-view-grid', 'cols-' . $columns);
./core/modules/views/templates/views.theme.inc:789:    $vars['attributes'] = array('summary' => filter_xss_admin($handler->options['summary']));
./core/modules/views/templates/views.theme.inc:794:    $vars['caption'] = filter_xss_admin($handler->options['caption']);
./core/modules/views/templates/views.theme.inc:797:    $vars['caption'] = '';
./core/modules/views/templates/views.theme.inc:804:function template_preprocess_views_view_unformatted(&$vars) {
./core/modules/views/templates/views.theme.inc:805:  $view = $vars['view'];
./core/modules/views/templates/views.theme.inc:806:  $rows = $vars['rows'];
./core/modules/views/templates/views.theme.inc:810:  $vars['row_classes'] = array();
./core/modules/views/templates/views.theme.inc:819:      $vars['row_classes'][$id][] = 'views-row';
./core/modules/views/templates/views.theme.inc:820:      $vars['row_classes'][$id][] = 'views-row-' . $count;
./core/modules/views/templates/views.theme.inc:823:      $vars['row_classes'][$id][] = ($count % 2 ? 'odd' : 'even');
./core/modules/views/templates/views.theme.inc:825:        $vars['row_classes'][$id][] = 'first';
./core/modules/views/templates/views.theme.inc:828:        $vars['row_classes'][$id][] = 'last';
./core/modules/views/templates/views.theme.inc:833:      $vars['row_classes'][$id][] = $row_class;
./core/modules/views/templates/views.theme.inc:841:function template_preprocess_views_view_list(&$vars) {
./core/modules/views/templates/views.theme.inc:842:  $handler  = $vars['view']->style_plugin;
./core/modules/views/templates/views.theme.inc:850:  $vars['class'] = implode(' ', $class);
./core/modules/views/templates/views.theme.inc:851:  $vars['wrapper_class'] = implode(' ', $wrapper_class);
./core/modules/views/templates/views.theme.inc:852:  $vars['wrapper_prefix'] = '';
./core/modules/views/templates/views.theme.inc:853:  $vars['wrapper_suffix'] = '';
./core/modules/views/templates/views.theme.inc:854:  $vars['list_type_prefix'] = '<' . $handler->options['type'] . '>';
./core/modules/views/templates/views.theme.inc:855:  $vars['list_type_suffix'] = '</' . $handler->options['type'] . '>';
./core/modules/views/templates/views.theme.inc:856:  if ($vars['wrapper_class']) {
./core/modules/views/templates/views.theme.inc:857:    $vars['wrapper_prefix'] = '<div class="' . $vars['wrapper_class'] . '">';
./core/modules/views/templates/views.theme.inc:858:    $vars['wrapper_suffix'] = '</div>';
./core/modules/views/templates/views.theme.inc:861:  if ($vars['class']) {
./core/modules/views/templates/views.theme.inc:862:    $vars['list_type_prefix'] = '<' . $handler->options['type'] . ' class="' . $vars['class'] . '">';
./core/modules/views/templates/views.theme.inc:864:  template_preprocess_views_view_unformatted($vars);
./core/modules/views/templates/views.theme.inc:870:function template_preprocess_views_view_rss(&$vars) {
./core/modules/views/templates/views.theme.inc:874:  $view     = &$vars['view'];
./core/modules/views/templates/views.theme.inc:875:  $options  = &$vars['options'];
./core/modules/views/templates/views.theme.inc:876:  $items    = &$vars['rows'];
./core/modules/views/templates/views.theme.inc:883:  $vars['description'] = check_plain(decode_entities(strip_tags($style->get_description())));
./core/modules/views/templates/views.theme.inc:895:  $vars['title'] = check_plain($title);
./core/modules/views/templates/views.theme.inc:916:    $vars['link'] = check_url(url($path, $url_options));
./core/modules/views/templates/views.theme.inc:919:  $vars['langcode'] = check_plain($language_content->langcode);
./core/modules/views/templates/views.theme.inc:920:  $vars['namespaces'] = backdrop_attributes($style->namespaces);
./core/modules/views/templates/views.theme.inc:921:  $vars['items'] = $items;
./core/modules/views/templates/views.theme.inc:922:  $vars['channel_elements'] = format_xml_elements($style->channel_elements);
./core/modules/views/templates/views.theme.inc:926:  if (empty($vars['view']->live_preview)) {
./core/modules/views/templates/views.theme.inc:934:function template_preprocess_views_view_row_rss(&$vars) {
./core/modules/views/templates/views.theme.inc:935:  $view     = &$vars['view'];
./core/modules/views/templates/views.theme.inc:936:  $options  = &$vars['options'];
./core/modules/views/templates/views.theme.inc:937:  $item     = &$vars['row'];
./core/modules/views/templates/views.theme.inc:939:  $vars['title'] = check_plain($item->title);
./core/modules/views/templates/views.theme.inc:940:  $vars['link'] = check_url($item->link);
./core/modules/views/templates/views.theme.inc:941:  $vars['description'] = check_plain($item->description);
./core/modules/views/templates/views.theme.inc:942:  $vars['item_elements'] = empty($item->elements) ? '' : format_xml_elements($item->elements);
./core/modules/views/templates/views.theme.inc:948:function template_preprocess_views_exposed_form(&$vars) {
./core/modules/views/templates/views.theme.inc:949:  $form = &$vars['form'];
./core/modules/views/templates/views.theme.inc:955:    $vars['q'] = backdrop_render($form['q']);
./core/modules/views/templates/views.theme.inc:958:  $vars['widgets'] = array();
./core/modules/views/templates/views.theme.inc:984:    $vars['widgets'][$id] = $widget;
./core/modules/views/templates/views.theme.inc:994:    $vars['widgets']['checkboxes'] = $widget;
./core/modules/views/templates/views.theme.inc:998:    $vars['sort_by'] = backdrop_render($form['sort_by']);
./core/modules/views/templates/views.theme.inc:999:    $vars['sort_order'] = backdrop_render($form['sort_order']);
./core/modules/views/templates/views.theme.inc:1002:    $vars['items_per_page'] = backdrop_render($form['items_per_page']);
./core/modules/views/templates/views.theme.inc:1005:    $vars['offset'] = backdrop_render($form['offset']);
./core/modules/views/templates/views.theme.inc:1008:    $vars['reset_button'] = backdrop_render($form['reset']);
./core/modules/views/templates/views.theme.inc:1011:  $vars['button'] = backdrop_render_children($form);
./core/modules/views/templates/views.theme.inc:1046:function theme_views_mini_pager($vars) {
./core/modules/views/templates/views.theme.inc:1049:  $tags = $vars['tags'];
./core/modules/views/templates/views.theme.inc:1050:  $element = $vars['element'];
./core/modules/views/templates/views.theme.inc:1051:  $parameters = $vars['parameters'];
./core/modules/views/views.module:316:function views_preprocess_node(&$vars) {
./core/modules/views/views.module:318:  if (!empty($vars['node']->view) && !empty($vars['node']->view->name)) {
./core/modules/views/views.module:319:    $vars['view'] = $vars['node']->view;
./core/modules/views/views.module:320:    $vars['theme_hook_suggestions'][] = 'node__view__' . $vars['node']->view->name;
./core/modules/views/views.module:321:    if (!empty($vars['node']->view->current_display)) {
./core/modules/views/views.module:322:      $vars['theme_hook_suggestions'][] = 'node__view__' . $vars['node']->view->name . '__' . $vars['node']->view->current_display;
./core/modules/views/views.module:326:      if ($vars['page'] && $vars['view_mode'] == 'full' && !$vars['view']->display_handler->has_path()) {
./core/modules/views/views.module:327:        $vars['page'] = FALSE;
./core/modules/views/views.module:333:  if (!empty($vars['view']->style_plugin->row_plugin) && get_class($vars['view']->style_plugin->row_plugin) == 'views_plugin_row_node_view') {
./core/modules/views/views.module:334:    node_row_node_view_preprocess_node($vars);
./core/modules/views/views.module:342:function views_preprocess_comment(&$vars) {
./core/modules/views/views.module:344:  if (!empty($vars['node']->view) && !empty($vars['node']->view->name)) {
./core/modules/views/views.module:345:    $vars['view'] = &$vars['node']->view;
./core/modules/views/views.module:346:    $vars['theme_hook_suggestions'][] = 'comment__view__' . $vars['node']->view->name;
./core/modules/views/views.module:347:    if (!empty($vars['node']->view->current_display)) {
./core/modules/views/views.module:348:      $vars['theme_hook_suggestions'][] = 'comment__view__' . $vars['node']->view->name . '__' . $vars['node']->view->current_display;
./core/modules/views_ui/views_ui.module:427:function views_ui_preprocess_views_view(&$vars) {
./core/modules/views_ui/views_ui.module:428:  $view = $vars['view'];
./core/modules/views_ui/views_ui.module:432:      if (!empty($vars[$section])) {
./core/modules/views_ui/views_ui.module:433:        $vars[$section] = array(
./core/modules/views_ui/views_ui.module:437:          '#content' => is_array($vars[$section]) ? backdrop_render($vars[$section]) : $vars[$section],
./core/modules/views_ui/views_ui.module:441:        $vars[$section] = backdrop_render($vars[$section]);
./core/modules/views_ui/views_ui.theme.inc:42:function theme_views_ui_reorder_displays_form($vars) {
./core/modules/views_ui/views_ui.theme.inc:43:  $form = $vars['form'];
./core/modules/views_ui/views_ui.theme.inc:242:function theme_views_ui_rearrange_filter_form(&$vars) {
./core/modules/views_ui/views_ui.theme.inc:243:  $form = $vars['form'];
./core/modules/views_ui/views_ui.theme.inc:409:function theme_views_ui_view_preview_section($vars) {
./core/modules/views_ui/views_ui.theme.inc:410:  return '<h1 class="section-title">' . $vars['title'] . '</h1>'
./core/modules/views_ui/views_ui.theme.inc:411:  . $vars['links']
./core/modules/views_ui/views_ui.theme.inc:412:  . '<div class="preview-section">'. $vars['content'] . '</div>';
./core/modules/views_ui/views_ui.theme.inc:471:function template_preprocess_views_ui_view_preview_section(&$vars) {
./core/modules/views_ui/views_ui.theme.inc:472:  switch ($vars['section']) {
./core/modules/views_ui/views_ui.theme.inc:474:      $vars['title'] = t('Title');
./core/modules/views_ui/views_ui.theme.inc:475:      $links = views_ui_view_preview_section_display_category_links($vars['view'], 'title', $vars['title']);
./core/modules/views_ui/views_ui.theme.inc:478:      $vars['title'] = t('Header');
./core/modules/views_ui/views_ui.theme.inc:479:      $links = views_ui_view_preview_section_handler_links($vars['view'], $vars['section']);
./core/modules/views_ui/views_ui.theme.inc:482:      $vars['title'] = t('No results behavior');
./core/modules/views_ui/views_ui.theme.inc:483:      $links = views_ui_view_preview_section_handler_links($vars['view'], $vars['section']);
./core/modules/views_ui/views_ui.theme.inc:487:      $vars['title'] = t('Exposed Filters');
./core/modules/views_ui/views_ui.theme.inc:488:      $links = views_ui_view_preview_section_display_category_links($vars['view'], 'exposed_form_options', $vars['title']);
./core/modules/views_ui/views_ui.theme.inc:492:      $vars['title'] = t('Content');
./core/modules/views_ui/views_ui.theme.inc:493:      $links = views_ui_view_preview_section_rows_links($vars['view']);
./core/modules/views_ui/views_ui.theme.inc:496:      $vars['title'] = t('Pager');
./core/modules/views_ui/views_ui.theme.inc:497:      $links = views_ui_view_preview_section_display_category_links($vars['view'], 'pager_options', $vars['title']);
./core/modules/views_ui/views_ui.theme.inc:500:      $vars['title'] = t('More');
./core/modules/views_ui/views_ui.theme.inc:501:      $links = views_ui_view_preview_section_display_category_links($vars['view'], 'use_more', $vars['title']);
./core/modules/views_ui/views_ui.theme.inc:504:      $vars['title'] = t('Footer');
./core/modules/views_ui/views_ui.theme.inc:505:      $links = views_ui_view_preview_section_handler_links($vars['view'], $vars['section']);
./core/modules/views_ui/views_ui.theme.inc:509:      $vars['title'] = t('Attachment before');
./core/modules/views_ui/views_ui.theme.inc:513:      $vars['title'] = t('Attachment after');
./core/modules/views_ui/views_ui.theme.inc:528:    $vars['links'] = backdrop_render($build);
./core/modules/views_ui/views_ui.theme.inc:530:  $vars['theme_hook_suggestions'][] = 'views_ui_view_preview_section__' . $vars['section'];
./modules/contrib/devel/devel_generate/devel_generate_batch.inc:46:function devel_generate_batch_content_pre_node($vars, &$context) {
./modules/contrib/devel/devel_generate/devel_generate_batch.inc:47:  $context['results'] = $vars;
./modules/contrib/devel/lib/firephp/FirePHP.class.php:1773:                $vars = self::encodeObject($var);
./modules/contrib/devel/lib/firephp/FirePHP.class.php:1778:                                        array_keys($vars),
./modules/contrib/devel/lib/firephp/FirePHP.class.php:1779:                                        array_values($vars));

`

**Comment by quicksketch** [comment]
Hah! Yeah it does, if a bit verbose. :wink:

So it looks like the only places we still use $vars is in Node, Comment, and Views. Really Node and Comment's references are in their Views integration (which was copied over from Views module).

**Comment by jenlampton** [comment]
Yes, and also Search.  I just updated the issue with a list.  Thanks @serundeputy!

**Comment by serundeputy** [comment]
should I do this on the same branch ; new pull request?

**Comment by jenlampton** [comment]
New branch, new PR :)

**Comment by quicksketch** [comment]
Looks like @serundeputy got all these with the new PR (https://github.com/backdrop/backdrop/issues/708). Thanks!
