### ISSUE TITLE
Content display modes: Remove angle brackets from the label options

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4297]
Not sure why that is that way in the first place ("Above" and "Inline" do not have that):

![Screen Shot 2020-02-02 at 5 45 40 pm](https://user-images.githubusercontent.com/2423362/73604375-f21b7580-45e3-11ea-8fc5-2b5b461ca232.png)

---
PR by @codelover96: https://github.com/backdrop/backdrop/pull/3063

**Comment by codelover96** [comment]
I'm working on this. I'll have an update until tomorrow.

**Comment by codelover96** [comment]
Same happens at format, dropdown menu 
![screenshot2](https://user-images.githubusercontent.com/12110485/73610896-fe540280-45e4-11ea-8d17-c9e226971a78.png)

**Comment by findlabnet** [comment]
Not so clear (maybe to me only): why this form of representation for special element in selector has named "bug"?

**Comment by olafgrabienski** [comment]
>> Not sure why that is that way in the first place ...

> why this form of representation for special element in selector has named "bug"?

I also don't understand the angle brackets as a bug but as attempt to highlight a special element. Not sure if it's necessary, though. But do the angle brackets have an effect on sorting the elements, so that `<Hidden>` is always at the bottom, independent from alphabetical order of the other terms?

**Comment by klonos** [comment]
@codelover96 thanks for taking up on this patrida 🙂 ...and yes, I would also fix that in the format select. Good catch 👍 

AFAIK, we use these brackets for things like `<front>`, and `<none>`/`<any>`, but these are special, literal strings being used as input. In this case here, this is just a select option, so I don't see why to use brackets. If you see this as a normal thing, then for consistency we should be using that pattern in the rest of the options in the select as well?

> why this form of representation for special element in selector has named "bug"?

We have issue categories for "bug", "task", and "feature request"; leaving "Question" and "Documentation" obviously out, what would you guys categorize this as if not a UI bug?

@olafgrabienski the options in select/checkboxes/radios are rendered in the order they have in code (they are arrays) - not alphabetical. So even if we remove the brackets, `Hidden` should remain last.

**Comment by olafgrabienski** [comment]
> the options in select/checkboxes/radios are rendered in the order they have in code (they are arrays) - not alphabetical.

Thanks for the clarification!

Btw, the menu select list makes also use of angle brackets, and we're considering to remove them while working on https://github.com/backdrop/backdrop-issues/issues/4218, see https://github.com/backdrop/backdrop-issues/issues/4218#issuecomment-558353641 and https://github.com/backdrop/backdrop-issues/issues/4218#issuecomment-569124747.

**Comment by findlabnet** [comment]
So this issue seems more complex than before.
Just from my experience: every time when we try to fix a non-broken thing, we are surely trying to break something near (or even far away from) it.

**Comment by BWPanda** [comment]
I disagree with the 'bug' categorisation. I'd say this is a 'feature request'. I.e. something added/changed from the default/current behaviour.

**Comment by klonos** [comment]
Seems that this is a good topic for discussion during our next meeting then 😅  

I categorize anything in the UI that could potentially baffle people, as a UX bug. To me, the definition of a feature is something that introduces new functionality to the product; something that one could use when they are trying to pitch Backdrop to others. So I see views as a feature, I see CKEditor as a feature ...in general anything that would be worthy to mention in https://backdropcms.org/roadmap. I certainly do not see improving the consistency of the options of a single dropdown in the UI as a new feature at all.

...that fine though, because that's what we have "tasks" for 😉

**Comment by codelover96** [comment]
Okay, angle brackets removed. Turns out they where concatenated to the Label options and Format options.
FIle : _backdrop/core/modules/field_ui/field_ui.admin.ic_
- line 1000 : ` 'hidden' => '<' . t('Hidden') . '>',`

- line 1057: `$formatter_options['hidden'] = '<' . t('Hidden') . '>';`

Screenshot from local enviroment :
![screenshot](https://user-images.githubusercontent.com/12110485/73648679-bd142f00-4686-11ea-809d-645289f054dc.png)

So now,if i understand correctly, I have to fork backdrop, then commit my changes to that fork and then create a PR while referencing this issue #4297?

**Comment by klonos** [comment]
Correct @codelover96 👍

**Comment by klonos** [comment]
Hey @codelover96 👋 ...thanks for filing that PR 👍 ...when you do file PRs, please remember to add the following labels to the respective issue in the queue:

- `status - has pull request`
- `pr - needs code review`
- `pr - needs testing`

😉

**Comment by klonos** [comment]
RTBC 👍 ...code changes are very minimal, tests are green, and things look/work as expected in the PR sandbox.

**Comment by quicksketch** [comment]
Thanks folks! Extra thanks and welcome to @codelover96! Merged in https://github.com/backdrop/backdrop/pull/3063 into 1.x and 1.15.x.

**Comment by codelover96** [comment]
Thanks a lot @klonos for the advise. It was fun. Looking forward to get into more 😁
@quicksketch Thank you!
