### ISSUE TITLE
Make it possible to directly upload an image file from the camera of iPhones, again

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4300]
**Description of the bug**
Back in version 1.4 we [added the ability to select an image from a mobile device's camera](https://github.com/backdrop/backdrop-issues/issues/869). Sometime since then, we lost it. We should find out how that happened and add it back. 

Heres the markup for current input element:
```
<input data-file-auto-upload="1" data-file-extensions="png,gif,jpg,jpeg" accept="*/*,capture=camera" type="file" id="edit-field-image-und-0-upload" name="files[field_image_und_0]" size="22" class="form-file validate-extension-processed auto-upload-processed">
```

I think the problem maybe `accept="*/*,capture=camera"`.
That may need to be `accept="image/*,capture=camera"`.

**Steps To Reproduce**
To reproduce the behavior:
1. Log into a clean backdrop install from your iPhone or iPad.
2. Create a post, and scroll to the image field.
3. Click "upload" and see if you can browse through your camera.

**Actual behavior**
Unable to open images in the camera app
![iphone](https://user-images.githubusercontent.com/397895/73774250-8696ec80-4738-11ea-8740-e2a72d43afa1.png)

**Expected behavior**
I should be able to load photos from my camera on an iPhone

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version: 1.15 and 1.14 (and maybe others)

---
PR: https://github.com/backdrop/backdrop/pull/3064

**Comment by BWPanda** [comment]
I can't reproduce this. I do the steps above and it works fine...

[![Screenshot-20200204-052110-Android-system.png](https://i.postimg.cc/Yq3FNScr/Screenshot-20200204-052110-Android-system.png)](https://postimg.cc/9rDzCCFK)

I'm using Brave browser 1.5.3 on Android 9.

**Comment by BWPanda** [comment]
@jenlampton Don't you need two people to add a milestone? https://backdropcms.org/user-guide/adding-milestones-issues

Until others can reproduce this, we don't know it's a bug or what the best fix is...

**Comment by laryn** [comment]
Related (or dupe): https://github.com/backdrop/backdrop-issues/issues/4185

**Comment by klonos** [comment]
Yeah, the reports so far in #4185 have been that this cannot be reproduced.

I just tested this again on my Android, and it worked fine with both the image field on a post, as well as with the image browser in CKEditor. Although, it has to be said that the original report in #4185 was about iOS devices. @jenlampton are you seeing this on an iPhone?

**Comment by BWPanda** [comment]
> Actual behavior
> Unable to locate images in camera (especially from iPhone)

**Comment by klonos** [comment]
> (especially from iPhone)

I would say "exclusively on iPhone/iOS". All the people that have reported this issue seem to be using an iDevice.

**Comment by jenlampton** [comment]
> I can't reproduce this. I do the steps above and it works fine...

Maybe you need to be on an iPhone for it not to work? My client was on an iPhone, I'll post her screenshot to the top issue.

> @jenlampton Don't you need two people to add a milestone? backdropcms.org/user-guide/adding-milestones-issues

For minor releases, yes. For bug-fix releases any issues with a PR can get added to the next milestone.

**Comment by jenlampton** [comment]
This is definitely a dupe of https://github.com/backdrop/backdrop-issues/issues/4185, so I'm going to close this as dupe and update my PR to point at that issue instead. 

I did really search for that issue before, but I wasn't able to find it :(
