### ISSUE TITLE
Empty large text fields are rendering markup

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4319]
**Description of the bug**
Empty fields seem to still be rendering markup in the layout.

**Steps To Reproduce**
To reproduce the behavior:
1. Add a 'text area' field to a content type.
2. Create a piece of content of that type, leaving this new field empty.
3. View source on the page.

**Actual behavior**
Empty divs are rendered in the page.
![Screen Shot 2020-02-26 at 1 24 10 PM](https://user-images.githubusercontent.com/871421/75379804-99b25d80-589b-11ea-9ee6-0a1bced91633.jpg)

**Expected behavior**
These fields should not render if they are empty.

**Additional information**

*Maybe* related? Really not sure at all.

 - https://github.com/backdrop/backdrop-issues/issues/3378
 - https://github.com/backdrop/backdrop-issues/issues/3873
 - https://github.com/backdrop/backdrop-issues/issues/4152

---

PR by @indigoxela : https://github.com/backdrop/backdrop/pull/3086

**Comment by quicksketch** [comment]
Thanks @laryn! This may be related to #3873. Where now the text format is saved even if the text value is blank.

**Comment by indigoxela** [comment]
Confirmed, fields of type long text (textarea) get rendered empty, but only if a _text format_ is set.

Yes, that's related to #3378. We need hook_field_is_empty to return false, because otherwise the format setting is lost.

I wonder, if we can fix it in text modules' hook_field_formatter_view implementation. A quick idea is to return an empty `$element` array if `$item['value']` is empty.
Or could this have side effects?

**Comment by quicksketch** [comment]
@indigoxela That seems like a good approach.

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/3086) that returns an empty render array, it values are empty.

**Comment by laryn** [comment]
Just tested and this works great for field displays, including fields that are placed as blocks in a layout. Thanks!

One possible step further -- I also tried creating a simple view block which displays only one text area field and is filtered on that field being NOT NULL (and also selecting "Hide if empty" for that field). This block continues to show up on pages, so perhaps there's a section where Views is still thinking there is content in the empty field somehow.

**Comment by indigoxela** [comment]
@laryn many thanks for testing this.

Regarding views:

I guess, views relies on an existing / non-existing database entry for that field for filter type "NOT NULL". And that entry exists - and it must exist to keep the format setting.

I was able to get around that in a test view by choosing "Is not equal to" and an empty value for filtering.

**Comment by laryn** [comment]
@indigoxela I suppose that workaround could be fine for the filters. What do you think we can do about the "Hide if empty" checkbox/setting? Anything?

**Comment by indigoxela** [comment]
> What do you think we can do about the "Hide if empty" checkbox/setting?

The empty text fields are actually already hidden, but the pager doesn't seem to consider the empty status unless a filter is set.

So if only using the "Hide if empty" setting without additional filter, the fields are hidden, but the pager still counts the fields, resulting in wrong item count per page.
This can get verified by adding a "Global: Result summary" to the view header.

That header shows, for instance, "Displaying 1 - 10 of 17" when the page only contains two field items. The hidden ones are the ones with empty values.

_BUT:_ I compared that to a D7 instance and the behavior is the same there. Without additional filter the pager result count is wrong. Adding a filter fixes it for both, B1 and D7. But in D7 the "NOT NULL" filter also works.

The only difference between B1 and D7 is the fact that B1 needs a different filter compared to D7.
I'm not sure if that's actually something that has to be fixed or this is desired behavior.

**Comment by laryn** [comment]
@indigoxela Okay, maybe it is not an issue then. Certainly the PR solves the main issue here.

I was mainly thinking of the use case where in a View you rewrite a field, but check the box that says "Hide rewriting if empty" -- which won't work anymore if I understand correctly. But that may be a separate issue from this one.

**Comment by jenlampton** [comment]
Code change looks straightforward, RTBC!

**Comment by quicksketch** [comment]
Thanks folks! I've merged https://github.com/backdrop/backdrop/pull/3086 into 1.x and 1.15.x. Nice simple fix @indigoxela! Thanks @laryn for posting this issue and keeping tabs on it!
