### ISSUE TITLE
Parameter 3 to views_ui_build_form_state() expected to be a reference, value given in views_ui_ajax_form()

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4323]
I'm seeing this warning on a site when using Views, just noting here in case anyone is searching for the error later:

> Warning: Parameter 3 to views_ui_build_form_state() expected to be a reference, value given in views_ui_ajax_form() (line 2882 of /path/core/modules/views_ui/views_ui.admin.inc). 

It looks like it's covered by [a Drupal issue](https://www.drupal.org/project/views/issues/2810431) that is already linked in the [Views crossport meta](https://github.com/backdrop/backdrop-issues/issues/3853) but I'll break it out here in case it can be committed now.

--
PR by @klonos https://github.com/backdrop/backdrop/pull/3056

**Comment by jenlampton** [comment]
PR looks straightforward, and since it was a crossport. RTBC!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3056 into 1.x and 1.15.x. Thanks @klonos for the PR! Thanks @laryn for reporting and @jenlampton for the review.
