### ISSUE TITLE
Invalid ARIA role "footer" for many of Backdrop's layouts.

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#4324]
**Description of the bug**
I was checking the a11y of some of my Backdrop sites and it was flagged that `footer` is not a valid ARIA role.

* Valid roles: https://www.w3.org/TR/wai-aria-1.1/#role_definitions

![image](https://user-images.githubusercontent.com/6763671/75626422-733f3b80-5b95-11ea-8c7a-de7bd6b1687f.png)

**Steps To Reproduce**
To reproduce the behavior:
1. Run a lighthouse a11y report on any Backdrop page that has a Backdrop provided footer.
2. See ARIA role footer flagged as an invalid value 

**Actual behavior**

ARIA role values for Backdrop footers are invalid.

**Expected behavior**

ARIA roles should be valid.

----

PR: https://github.com/backdrop/backdrop/pull/3088

**Comment by serundeputy** [comment]
Here is the lighthouse report for the sandbox w/ the PR
https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=http://3088.backdrop.backdrop.qa.backdropcms.org/

![image](https://user-images.githubusercontent.com/6763671/75626569-830b4f80-5b96-11ea-809f-4974a898b0f9.png)

**Comment by BWPanda** [comment]
Duplicate of #4034?

**Comment by serundeputy** [comment]
yep; dupe; sorry about the noise!
