### ISSUE TITLE
A small typo in `core/themes/basis/css/README.md`

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4326]
There is a small typo in `core/themes/basis/css/README.md`:

> Basis inludes very granular CSS files so that a sub theme can override

for which I offered a PR https://github.com/backdrop/backdrop/pull/3080 some time ago, but forgot to create an issue for it.

**Comment by oadaeh** [comment]
There's no code to review, only a text file, and the change looks fine.

**Comment by BWPanda** [comment]
Merged https://github.com/backdrop/backdrop/pull/3080 into 1.x and 1.15.x. Thanks @alanmels for finding this and making a PR! And thanks @oadaeh and @klonos for the review :smiley:
