### ISSUE TITLE
viewsSearchQuery class missing from search_autoload_info

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4328]
**Description of the bug**
As title says

**Steps to reproduce**

Follow the instructions in [this tutorial](https://www.drupal4u.org/howtos/how-display-search-results-views):

1. Create a view with a Page display
2. Add the contextual filter "Search: Search Terms" to the view
3. Set the page path to `/search/node/%`
4. Visit `/search/node`, and try searching for "first" -> error 👎 

![Screen Shot 2020-03-04 at 3 42 55 pm](https://user-images.githubusercontent.com/2423362/75846154-879e6500-5e2f-11ea-98d4-f08a8f1f30c1.png)

**Comment by klonos** [comment]
...have tested this on a demo sandbox -> error happens 👎 

...then tested it on the PR sandbox -> works 👍 

![Screen Shot 2020-03-04 at 3 50 01 pm](https://user-images.githubusercontent.com/2423362/75846245-d3e9a500-5e2f-11ea-90a7-0cef80054b63.png)

**Comment by klonos** [comment]
As I mentioned in the PR, I am unsure if moving the class is OK or not; otherwise RTBC 👍

**Comment by docwilmot** [comment]
Moving it is OK; `hook_autoload_info()` is there for that purpose, to tell Backdrop where it is. I moved it to that file because it is extending `SearchQuery` so makes sense to have it in the same file with its parent. And practically it doesnt matter since Backdrop didnt know it existed before this PR anyway!

**Comment by docwilmot** [comment]
Can you RTBC please?

**Comment by quicksketch** [comment]
Thanks @docwilmot and @klonos! Moving the code around gives me pause too, but as @docwilmot points out, it doesn't really matter where it lives as `hook_autoload_info()` makes loading of the file automatic. We can move it around as needed.

Merged https://github.com/backdrop/backdrop/pull/3089 into 1.x and 1.15.x. Thanks @docwilmot and @klonos!
