### ISSUE TITLE
Users with the "Administer themes" permission cannot change colors

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4330]
**Steps To Reproduce**
To reproduce the behavior:
1. On a vanilla installation, create a new user, and assign them the "Editor" role.
2. Grand the "Administer themes" permission to the "Editor" role.
3. Log in as that user
4. Navigate to the color settings page for Basis (`/admin/appearance/settings/basis`)
5. Try to change any color, in any of the color fieldsets

**Actual behavior**
- The color is not reflected in the live preview 👎 
- There is an "access denied" error in the log:

    **Location**: https://my.site/color/save_preview_settings/basis/?token=s0m3R@nd0mStr1ngH3r3
    **Referrer**: https://my.site/admin/appearance/settings/basis/
    **Message**: color/save_preview_settings/basis
    **Severity**: warning

**Expected behavior**
- Colors are updated in the theme preview
- No error

**Comment by BWPanda** [comment]
Wow, that seems like such a weird bug. Having a permission should allow you to do more, not less...

**Comment by edcaracas** [comment]
Is really strange.
As admin or editor when it goes to the function: _color_preview_theme() has the correct permissions set user_access('administer themes') = true.
In a normal admin flow then goes to color_save_preview_settings() function.
But as "administrator privileges" on other account, it doesnt make the jump to color_save_preview_settings()

**Comment by hosef** [comment]
I took a look at the color module. This is because I accidentally used `administer theme settings` in the hook_menu implementation instead of `administer themes`.

**Comment by klonos** [comment]
Simple one-liner, and following the STR in the PR sandbox do not cause the bug nor the errors. So RTBC 👍 

> `administer theme settings` is not defined in any implementation of hook_permissions, although maybe it should be. Then we could allow people to change the color of an existing theme without being able to install/enable/disable themes on the site or change the admin theme.

Yes please, but follow-up.

**Comment by quicksketch** [comment]
Nice one @hosef! Thanks @klonos and @edcapetti for your input and help tracking this one down. I've merged https://github.com/backdrop/backdrop/pull/3102 into 1.x, 1.15.x, and (accidentally) into 1.14.x. This will be in 1.15.1 and 1.14.3.
