### ISSUE TITLE
Use of undefined constant VIEWS_STORAGE_OVERRIDE

### ISSUE THREAD

**Issue by oadaeh** [backdrop/backdrop-issues#4343]
**Description of the bug**
When upgrading a Drupal site to Backdrop while using a version of PHP >= 7.2.0, the following error is thrown:
> Warning: Use of undefined constant VIEWS_STORAGE_OVERRIDE - assumed 'VIEWS_STORAGE_OVERRIDE' (this will throw an Error in a future version of PHP) in node_update_1018() (line 1194 of /path/to/backdrop/core/modules/node/node.install).

Here is the relevant part of that function:
```
  // Only update if view isn't overridden.
  if ($config->get('storage') == VIEWS_STORAGE_OVERRIDE) {
    return;
  }
```

The code in the install file is using a named constant that is not defined at that point, which means that code will never evaluate to TRUE, even if it should.

Here is the constant's definition at line 19 of `views.module`:
```
/**
 * Views constant for views that override module-defined presets.
 */
define('VIEWS_STORAGE_OVERRIDE', 2);
```

**Proposed Solution**
The code in `node.install` could be changed to (maybe with a comment of explanation):
```
  // Only update if view isn't overridden.
  if ($config->get('storage') == 2) {
    return;
  }
```
Or `views.module` could be included just before using that named constant.
(Or something else?)

**Steps To Reproduce**
To reproduce the behavior:
1. Set up a new Drupal 7 site (I used the latest version of 7.69 at the time of creating this)
2. Download and place the files for a new Backdrop installation
3. Configure the settings.php file to use the database configuration for the Drupal site above
4. Navigate to /path/to/backdrop/core/update.php and run through the process

**Actual behavior**
There is the error at the top of the final update page (it is also in watchdog for referencing at a later time).

**Expected behavior**
The error notice is not generated (and maybe the update might behave differently).

**Additional information**
Add any other information that could help, such as:
- Backdrop CMS version: 1.15.0 downloaded package from b.o
- Web server and its version: Apache/2.4.38 (Ubuntu)
- Operating System and its version: Ubuntu 19.04
- Browser(s) and their versions: Firefox 72.0.1 (64-bit)
- PHP version: 7.2.24-0ubuntu0.19.04.2

**Comment by indigoxela** [comment]
My first thought was to simply use the integer value in this single case, but then...

The same usage of that constant also appears in comment.install and taxonomy.install (in hook_uninstall, though).

That makes me think that it might be cleaner to do a "require_once" in cases like that.

**Comment by herbdool** [comment]
I'm going to close in favour of https://github.com/backdrop/backdrop-issues/issues/4858.
