### ISSUE TITLE
Adding a date field leaves a watchdog "Theme hook not found" error

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4357]
**Description of the bug**
Adding a date field leaves a watchdog "Theme hook not found" error

**Steps To Reproduce**
Add a date field to a content type and check the logs

Backdrop Version 15.1

**Comment by olafgrabienski** [comment]
Confirmed! Tested with a Tugboat demo site.

**Comment by indigoxela** [comment]
To be more precise, the message is:
`Theme hook "" not found.`

I figures out that the message does not appear if the field widget is _date_select_.

For whatever reason '#theme' is set to an empty string here in function _date_field_widget_settings_form() if the widget is anything else than date_select :

https://github.com/backdrop/backdrop/blob/ec99b72110ae2f4fff023b7a2399ba03bd89edff/core/modules/date/date.admin.inc#L420

If I change that to:
`'#theme' => $widget['type'] == 'date_select' ? 'date_text_parts' : NULL,`
the message goes away.

But I'm not sure if that's the right approach. Can someone confirm it?

**Comment by quicksketch** [comment]
Hm, while `#theme` being `NULL` is sometimes the same thing as not existing at all, I think I'd be more comfortable with `#theme` not having a key. e.g.

```
if ($widget['type'] == 'date_select') {
  $element['#theme'] = 'date_text_parts';
}
```

**Comment by indigoxela** [comment]
@quicksketch many thanks for having a look.

PR is available, please test and review.

**Comment by quicksketch** [comment]
Super thanks @indigoxela! And thanks @docwilmot and @olafgrabienski for reviewing! Merged https://github.com/backdrop/backdrop/pull/3119 into 1.x and 1.15.x.
