### ISSUE TITLE
Register for HackerOne?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4358]
I came across [HackerOne](https://www.hackerone.com/) today and it looks like an interesting system for detecting, reporting, fixing, etc. security issues. I'm not 100% sure how it works (whether we'd get free security testing from ethical hackers, or whether we have to specifically ask and pay for tests), but they have an open-source, community edition of their platform that might be worth looking into: https://www.hackerone.com/product/community

Here's WordPress' page if that's of any help: https://hackerone.com/wordpress

**Comment by reedloden** [comment]
Let me know how I can help! I do open source security for HackerOne. :-)

**Comment by BWPanda** [comment]
Closing this issue, as I've copied it over to https://github.com/backdrop-ops/backdrop-community/issues/22 instead.
