### ISSUE TITLE
Can't save the setting to use the installation profile cache

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#4360]
**Actual behavior**

When you change the value of the 'Cache installation profiles' setting on /admin/config/development/testing/settings and click save, it is not saved.

**Expected behavior**

When you change the setting, it should actually save.

**Comment by docwilmot** [comment]
RTBC

**Comment by docwilmot** [comment]
The fix is simple and tests green, but is this something we should have had tests for? A test would have found this.

**Comment by hosef** [comment]
I took a look, and there don't appear to be any tests for the Simpletest UI, so that should probably be fixed.

I think the issue was that I assumed it was using `system_settings_form()` which was not the case at all. Since I rebuild my test site quite often and I forgot to go through the process manually on an existing install, I did not run into the issue.

**Comment by quicksketch** [comment]
Thanks @hosef and @docwilmot! Merged https://github.com/backdrop/backdrop/pull/3111 into 1.x and 1.15.x.
