### ISSUE TITLE
Add a dedicated slug field type...or adjust db schema...

### ISSUE THREAD

**Issue by ps23Rick** [backdrop/backdrop-issues#4361]
**Description of the need**

I need a CMS that has the ability to use/define a slug field as part of a specific content type.  
For now I'm just creating the "slug" field as part of the content type.  Unfortunately for me, probably due to the way the Backdrop stores fields associated with a specific content type, if I create my first new content type and add a field called "slug" (aka field_slug) and save it.  If I then add another new content type and try to put a field in it also called slug (aka field_slug), I get an error as field_slug is already taken by the first content type.  

**Proposed solution**

It would be nice to have things changed to allow each content type to have a field_slug (or similar) without stepping on each others toes, so to speak -- effectively privatizing field names within content types to be specific to the content type.  I realize doing a mod of this sort will take some database schema tweaking to accomplish. 

I've not found this sort of an issue with other CMSs that I've tried.  They either handle slugs natively (they provide a specific field type called "slug") or the database schema is designed so that conflicts in field names are not an issue from one content type to another.
Description how you would expect things to work ideally.

**Alternatives that have been considered**

For now I need to have the first content type field named "slug -- aka field_slug", and give the 2nd content type a different slug field name (e.g. slug2 -- aka field_slug2).  This doesn't really work well if I'm using this sort of thing through a bunch of different content types.  It gets messy rather quickly.

**Additional information**

<img width="1188" alt="Screenshot 2020-04-06 16 10 16" src="https://user-images.githubusercontent.com/38017680/78613779-8f339e00-7821-11ea-8e94-018a8942b628.png">

**Comment by olafgrabienski** [comment]
Have you seen the **URL alias pattern** setting on the Configuration page of your content type? Given the content type is called "Foo", you can find the setting at **Structure > Content types > Foo > Configure** (or typing the URL `admin/structure/types/manage/foo/configure`).

**Comment by indigoxela** [comment]
@ps23Rick I'm not sure if I get your request right, but I think you are searching for "Add existing field".
![add-existing-field](https://user-images.githubusercontent.com/842066/78647698-3adcfc80-78bb-11ea-8632-84eaa7be7363.png)

Is that correct?

**Comment by ps23Rick** [comment]
Ok ... You saw stuff that I apparently missed @indigoxela!  Thanks all for pointing that out.. It was right under my nose.. Doh!  Consider this a non-issue!  I'll close this issue.  Thanks again!
