### ISSUE TITLE
Fixed: Drupal 7 upgrade path must include setting for 'Error messages to display'.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4364]
In D7, the 'Error messages to display' setting (at `/admin/config/development/logging`) has values of 0, 1 & 2 (for 'None', 'Errors...' & 'All...' respectively). However in Backdrop these values have changed from integers to strings: 'hide', 'some' & 'all' respectively. That means that upgrading from D7 to Backdrop causes this setting to not be defined (at least in the UI):

![errors_radios](https://user-images.githubusercontent.com/2385329/78760353-b3aa8a00-7989-11ea-8186-3d1df31aea78.png)

We should add upgrade code that converts the integer values to the new string values.

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/4013

**Comment by BWPanda** [comment]
Done, thanks!

**Comment by indigoxela** [comment]
Many thanks for fixing, now this works properly. :+1:

**Comment by indigoxela** [comment]
The code is clear and simple. RTBC!

**Comment by quicksketch** [comment]
Thanks @indigoxela and @BWPanda! Merged https://github.com/backdrop/backdrop/pull/4013 into 1.x and 1.22.x.
