### ISSUE TITLE
[UX] Add a link to the layout path on the manage blocks page

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4370]
**Description of the need**
When you create a layout with its own path and want to see what it looks like, you have to remember the path and type it or go to the layout list page and search for it. We're lazy, thats too much work. 

**Proposed solution**

Views has a nice bar at the top with actions, the default which is to go to the page URL ("view page"). We should add this to layout block add pages.

![views bar](https://user-images.githubusercontent.com/1042283/79565891-35c83c00-8077-11ea-9216-d30ad2663b98.PNG)

**Comment by Graham-72** [comment]
👍

**Comment by docwilmot** [comment]
Simple PR adds this only for custom paths. Paths like node paths (`node/%`) would be more complex. We'd need to pick an existing node that the user has access to to use as the display. Maybe after more input.

**Comment by docwilmot** [comment]
To test, create a layout with a random path that doesnt already exist, there should be a link at the top of the Add Block page to preview it.

**Comment by hosef** [comment]
I took a look at the PR and it looks good. I also tested the change and it worked as expected. :+1:
I think the bootstrap test fails are random, but I am not sure about the locale test.

As far as the preview links on more complex layout paths, I think that might need to be an API addition because there would need to be different logic based on which contexts were used, and might not be possible if there are combinations of layout contexts. This seems like a nice start though.

**Comment by quicksketch** [comment]
Added a few comments to the PR: https://github.com/backdrop/backdrop/pull/3130/files

I think the link should be "View page" (like Views), not "Preview page" because it's the actual real page, not a preview of unsaved functionality.

**Comment by quicksketch** [comment]
As a minor UX improvement this can be done post-freeze for 1.16.0.

**Comment by jenlampton** [comment]
> As a minor UX improvement this can be done post-freeze for 1.16.0.

Or for 1.15.2!

**Comment by herbdool** [comment]
I fixed the automated test and everything passes. But I ended up making one small change to @docwilmot PR: have link target be same tab so it works the same as Views. So needs someone else to RTBC.

**Comment by indigoxela** [comment]
This link is a nice addition that saves some clicks.
Tested with a new custom layout, checked that the link also appears on other layouts without placeholder (like home) and that it doesn't appear where it shouldn't (layouts with placeholder paths)

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3130 into 1.x and 1.16.x. Thanks folks!
