### ISSUE TITLE
Wrong file path placeholder in layout_layout_context_info()

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4371]
**Description of the bug**

`    'path placeholder' => 'file',` should be     `'path placeholder' => '%file'` in `layout_layout_context_info()`

Steps to reproduce:
- Configure any layout in this sandbox (with this PR) and set the path to `file/%`, and as expected the context table will load with type `File` in position 2.
- Configure any layout in current backdrop without this PR and set the path to `file/%`. The context table will not load a File entity as expected, but will load "String passthrough".

---
PR by @docwilmot: https://github.com/backdrop/backdrop/pull/3125

**Comment by docwilmot** [comment]
Quick fix.

**Comment by jenlampton** [comment]
Code review looks good. Can you add steps to reproduce the problem, or how to test this?

**Comment by docwilmot** [comment]
No steps or testing, just a missing %.

**Comment by docwilmot** [comment]
To get this RTBC, here's a quick test: 
- Configure any layout in this sandbox (with this PR) and set the path to `file/%`, and as expected the context table will load with type `File` in position 2.
- Configure any layout in current backdrop without this PR and set the path to `file/%`. The context table will not load a File entity as expected, but will load "String passthrough".

**Comment by indigoxela** [comment]
Let's see if I got the problem right, here's how I tested:

- On a fresh install I created a layout with path `file/%`.
- Set context to "File" in the dropdown that appears on that form
- Uploaded a file (an image)
- Visited path `/file/1`
- File appears as expected

- Then I added a _visibility condition_ to the main content of that layout: "Type is image"
- Visited path `/file/1` again
- Got `call to a member function bundle() on boolean`

- Applied the patch
- Visited path `/file/1` again
- File appears again as expected

If that patch is applied _before_ creating the layout, no dropdown appears, but "File" is selected by default.

**Comment by docwilmot** [comment]
@indigoxela that was a longer test, but more thorough. 👍 
Could you RTBC please? Not much code review needed for a one-character PR!

**Comment by indigoxela** [comment]
> Could you RTBC please?

Sure, I just wanted to make sure, which problem this PR actually solves. :wink:

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/3125 into 1.x and 1.15.x.
