### ISSUE TITLE
[D8][UX] Use the user_admin_role config setting as a flag to allow all actions, simplify permissions page, remove user_modules_installed

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4372]
I am raising this as a replacement for #1462 which has over the years become obsolete. This is basically the equivalent of https://www.drupal.org/project/drupal/issues/2435075 (which also makes this issue part of #378).

`user_access()` has the following, which effectively makes it so that permission checks are bypassed for user 1:

```php
  // User #1 has all privileges:
  if ($account->uid == 1) {
    return TRUE;
  }
```

Additionally, we allow selecting a specific user role via the admin UI (/admin/config/people/roles) and then `user_modules_installed()` makes it so this role gets assigned all permissions:

```php
function user_modules_installed($modules) {
  // Assign all available permissions to the administrator role.
  $role_name = config_get('system.core', 'user_admin_role');
  $role = user_role_load($role_name);
  if ($role) {
    $permissions = array();
    foreach ($modules as $module) {
      if ($module_permissions = module_invoke($module, 'permission')) {
        $permissions = array_merge($permissions, array_keys($module_permissions));
      }
    }
    if (!empty($permissions)) {
      user_role_grant_permissions($role_name, $permissions);
    }
  }
}
```

This is all nice, but it does seem to add some UI complexity which could be improved:

1. If the administrator role is assigned all permissions, then why should we be keeping it around in the permissions page? In other words, is there any 80% use case where the administrator role should NOT have any specific permission? If not, then we could do either of these:

    - Simplify the admin UI by completely omitting the entire column of that role in the permissions page, as well as any other admin page where we have a permission matrix (like the "Permissions" vertical tab in the content type edit form, or the one in the settings form of the Contact module etc.)
    - Do not hide the column, but instead have all checkboxes be ticked and disabled/locked by default.

    No matter which one we choose to go with, we should also make it so that there is a note at the top of the permissions page (`backdrop_set_message()` with type `info`), with which we denote whichever role has been selected to be a "super admin", allowed to perform all tasks. We could also link to the configuration page where this setting can be changed.

2. We should keep the feature of allowing to specify which user role has the special ability to be able to perform all tasks. As @quicksketch mentioned in #1462:

    > The entire point of the Admin Role however was to make it so that multiple users could share the responsibility of full permissions without being logged in as UID 1.

    ...but instead of having the logic that goes this whole permission assigning, let's have a flag that basically makes it so that permissions are bypassed for this role (basically have it behave the same as user1 in that context). We already have this flag in config; it is basically `config_get('system.core', 'user_admin_role')`, so we're halfway there 😉. As @docwilmot suggested in #1462:

    > So change:

      ```php
      function user_access($permission_name, $account = NULL) {
      ...
        // User #1 has all privileges:
        if ($account->uid == 1) {
          return TRUE;
        }
      ...
      }
      ```

    > to:

      ```php
      function user_access($permission_name, $account = NULL) {
      ...
        $admin_role = config_get('system.core', 'user_admin_role');
        // User #1 and admin users have all privileges:
        if ($account->uid == 1 || in_array($admin_role, $account->roles)) {
          return TRUE;
        }
      ...
      }
      ```

    > Then check and disable all admin permission checkboxes a la D8.

3. Let's go one step further and also additionally remove the `user_modules_installed()` function. This function is basically an implementation of `hook_modules_installed()` with the sole purpose to go through every permission, and grant them to whichever role is selected to be the "Administrator" (`user_admin_role` flag in system.core.json) - it is not being called anywhere in core code. If we adapt `user_access()` as mentioned above in point 2, then this whole function will not be required.

**Comment by klonos** [comment]
I've filed a PR, and chosen to go with disabling the permission checkboxes for whichever role is set to be the "special" administrator role. In the example screenshot below, I have switched the admin role to be the "Editor":

![Screen Shot 2020-04-21 at 11 00 03 pm](https://user-images.githubusercontent.com/2423362/79909941-7bde2080-8426-11ea-8a0b-4baf76cf2fed.png)

What throws me off in this case is that both ticked and unticked permission checkboxes for that role are disabled/locked. This is nice to convey what is happening "under the hood", which is that although permission checks for this role are being bypassed, no actual permission has been changed. This means that if the admin role is changed, the checkboxes status here will be reflecting reality. If you see it from an end user point of view though, then you might be wondering if that role has the permissions with the unticked checkboxes or not ...and also if not, then how do you grant those permissions with the checkboxes locked.

If we make this work by automatically ticking all checkboxes for that role, then we are reflecting reality from an end user point of view (i.e. this role has all permissions), but it will not be 100% accurate _technically_ speaking (because we are not changing permissions for that role - we are bypassing them).

Hiding the entire column of whichever role is set to be the "special" admin role would be a possible solution to the above dilemma, but then people might be wondering why that role is not being listed in the permissions page 🤔

Another option would be to be hiding the checkboxes in that column:

![Screen Shot 2020-04-21 at 11 15 14 pm](https://user-images.githubusercontent.com/2423362/79909969-839dc500-8426-11ea-83f9-31bb2fb7d866.png)

D8 does that by the way (for permissions that are "implied"):

![Screen Shot 2020-04-21 at 11 18 32 pm](https://user-images.githubusercontent.com/2423362/79910014-97492b80-8426-11ea-8ef0-550cf3dad777.png)

Alternatively, we could be replacing the checkboxes with something like a "N/A" (or another string).

![Screen Shot 2020-04-21 at 11 16 44 pm](https://user-images.githubusercontent.com/2423362/79910067-b21ba000-8426-11ea-9519-58e163e05a31.png)

Thoughts? Ideas?

**Comment by klonos** [comment]
![Screen Shot 2020-04-21 at 11 27 01 pm](https://user-images.githubusercontent.com/2423362/79910571-a11f5e80-8427-11ea-837b-ce447577df7a.png)

**Comment by klonos** [comment]
...or use a muscle icon 💪 

![image](https://cloud.githubusercontent.com/assets/5062925/5933987/8d0110a2-a6f0-11e4-9ed3-648857dc4ce5.png)

**Comment by klonos** [comment]
Or:

- https://fontawesome.com/icons/sparkles
- https://fontawesome.com/icons/gem
- https://fontawesome.com/icons/magic

**Comment by indigoxela** [comment]
I like it exactly the way it currently is: admin role gets all permissions but it's possible to remove some of them.
I often grant _almost_ all permission to admins but, for instance, take away the permission to edit views (which would be too dangerous, as making a mistake can break too much).

I also like the way user number one (uid=1) always has all permissions as some sort of safety net to prevent trouble if crucial permissions are taken away from admin role. This always made sense to me in Drupal and also does in Backdrop.

Personally, I don't see any benefit in changing it. Please don't "fix" something that isn't broken.

**Comment by oadaeh** [comment]
I have to agree with @indigoxela on this. The idea with UID 1 always having full access is so that at least one user can get into the site and fix things that might be horribly broken. The administrator role is not the same and might not have all permissions assigned to it for various reasons.

**Comment by docwilmot** [comment]
Agreed with this as well.

**Comment by klonos** [comment]
I consider this proposal shot down, but will leave it up to a core maintainer to chime in and close this issue if they see no value in it (ping @BWPanda).

**Comment by BWPanda** [comment]
I'm in the same boat as others in that I often assign most permissions to an 'admin' role, but generally never all of them.

I see that setting as more of "assign all *new* permissions to this role automatically". (e.g. when new modules are added, new content types created, etc.). If people are expecting it to add *all* permissions verbatim then perhaps we need to change the words of that setting instead...?

**Comment by herbdool** [comment]
Closing. Not much appetite for this pr.
