### ISSUE TITLE
Incorrect cache bin used in 'views_handler_relationship_groupwise_max::query'

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4373]
in `views_handler_relationship_groupwise_max::query()` is has this code:

```php
// Get the stored subquery SQL string.
$cid = 'views_relationship_groupwise_max:' . $this->view->name . ':' . $this->view->current_display . ':' . $this->options['id'];
$cache = cache('views_data')->get($cid);
if (isset($cache->data)) {
  $def['left_query'] = $cache->data;
}
else {
  $def['left_query'] = $this->left_query($this->options);
  cache('cache_views_data')->set($cid, $def['left_query']);
}
```

The last line sets the value in cache bin `cache_views_data`, but the bin `views_data` is used above to get the value.

`cache_views_data` needs to be changed to `views_data`.

I noticed this when setting up a 'Taxonomy term: Representative node' relationship in Views. The sorting didn't work unless I ticked 'Generate subquery each time view is run' (which is for testing only).

**Comment by BWPanda** [comment]
Made a PR to fix this: https://github.com/backdrop/backdrop/pull/3122

**Comment by indigoxela** [comment]
@BWPanda the existing code does work too, even _with_ the "cache_" prefix, but your fix is correct.

The prefix is legacy, see the code comment for details: https://github.com/backdrop/backdrop/blob/4af391f1af9023a57fa8438f148ba758ba7d8fcb/core/includes/cache.inc#L26

Removing the prefix makes sense.

**Comment by BWPanda** [comment]
Thanks for the review @indigoxela! Merged https://github.com/backdrop/backdrop/pull/3122 into 1.x and 1.15.x.
