### ISSUE TITLE
Views: strings provided via UI aren't translatable at all

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4382]
**Description of the bug**

In Drupal 7 Views ships with translation (localization) support, but Backdrop has none at all, hence _no_ strings provided via Views UI are translatable.

For instance views labels, titles, header, footer, exposed form elements...

Marking this as a bug, as it's a clear regression compared to D7.

At following point Views came into core, but _all translation handling was stripped_:

https://github.com/backdrop/backdrop-issues/issues/40

The definitions still seem to be there, for example:
https://github.com/backdrop/backdrop/blob/c645dfb16e0a0b054132b70f15ecc13e8e84a63d/core/modules/views/plugins/views_plugin_display.inc#L509

They're useless without the functions that translate (localize) the strings, of course.

views_plugin_localization_core.inc
views_plugin_localization.inc
views_plugin_localization_none.inc

**Comment by indigoxela** [comment]
A PR is available. The change looks bigger than it is. I basically copies three plugin files from D7 views module and adds the functions that are needed to actually localize views strings.

Tests are still missing (will add them later).

Feedback is welcome.

**Comment by olafgrabienski** [comment]
@indigoxela I've had a quick look at the PR sandbox site but wasn't able to translate Views strings so far. Tested as followed:

- Enabled Locale and Language modules.
- Added German language.
- Created a test view with two fields (including labels):
  - Content: Title (Title)
  - Content: Body (Body field)
- Searched for the labels on `admin/config/regional/translate/translate`.
  Result: "No strings available."
- Cleared all caches and ran cron.
- Searched again for the labels on `admin/config/regional/translate/translate`.
  Result: same as above

Did I miss anything?

**Comment by indigoxela** [comment]
> Did I miss anything?

Many thanks for having a look. It's more likely that I missed something. :wink:

**Comment by indigoxela** [comment]
Ah, OK, first I played with you view. I saw that you only created the "master" display, so I added "page". Then went to that page and switched to german (/de/thetestpage). From then on the strings were available for translation.

I'll compare that to a D7 install. (Is ability to translate bound to visit the view once in a different language....?).

**Comment by indigoxela** [comment]
@olafgrabienski I definitely missed something - the functions to extract translatable strings when saving a view. These have been added now. You'll need to flush caches in the sandbox.

**Comment by olafgrabienski** [comment]
@indigoxela Thanks for the update! I've tested the sandbox site again: Flushed caches, added some more strings (field with label, views footer text) in the test view, saved the view, and searched for the strings on the *User interface translation* page. Without further steps, the strings didn't appear, but they did appear after visiting the German views page.

**Comment by indigoxela** [comment]
@olafgrabienski Confimed, it still doesn't work as expected. If editing the view in german (/de/admin/structure/views/view/test_localization), strings get added. If in english, they don't appear.

Hm...

**Comment by indigoxela** [comment]
The sandbox has php 5.3, on my dev I (successfully) tried with php 7.0 and 7.2.

Could someone try my PR on a local dev?

**Comment by indigoxela** [comment]
I've updated the code that triggers string saving. This seems to work properly even in the sandbox. (The code (from D7 views) looked a little strange anyway.)

Testing is welcome.

**Comment by olafgrabienski** [comment]
> I've updated the code that triggers string saving. This seems to work properly even in the sandbox.

Indeed, works like a charm!

**Comment by indigoxela** [comment]
I wonder which milestone and label would fit this PR. The required change is a little bigger than I hoped.

For possible reviewers: a lot of code just comes from D7 views, with modifications where necessary, of course.

https://git.drupalcode.org/project/views

**Comment by docwilmot** [comment]
If it's a bug then the next release is always appropriate (1.15.2). If it doesn't get reviewed in time it'll be bumped to 1.16.1 and so on until it gets in.

**Comment by herbdool** [comment]
This is great work. I didn't realize this was stripped out. I had thought we'd need to use the new core config translation functions but that was going to be hard. This is much better.

**Comment by herbdool** [comment]
Code looks good to me - I made one comment for a change.

**Comment by quicksketch** [comment]
Thanks @indigoxela! I appreciate you digging up why this happened too. Looks like it was me that removed localization as part of the migration to the config system.

This looks like a solid port from the D7 functionality. I think the hope when this was removed was that config translation would eventually replace the need for Views to do it's own localization. We did eventually add Config translation in #704. But use of the config translation system is spotty at best currently.

The premise of config translation is that keys that are possible to translate within a config file are specified in the JSON file under `_config_translatables`. Take `system.core.json` as an example:

```
    "_config_translatables": [
        "anonymous",
        "site_name",
        "site_slogan",
        "maintenance_mode_message"
    ],
```

Each corresponds to a key within the file that is translatable. Then when [`$config->getTranslated()`](https://api.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/Config%3A%3AgetTranslated/1) is called, it just calls `t()` but with a specific `context` passed in:

```
    if (!array_key_exists('context', $options)) {
      $options['context'] = 'config:' . $this->getName() . ':' . $key;
    }
    return t($value, $args, $options);
```
Well anyway, explanations aside, I don't know how we should reconcile these systems, if at all. Restoring the capabilities of D7 seems like it's definitely a win. Do you folks have any further thoughts on how these two systems should interact?

**Comment by indigoxela** [comment]
Regarding the use of config translation:

One problem is that translations from migrated views (D7) are lost, as the original translations don't have the required context then.

Another thought: both, config translation and views_plugin_localization_core rely on locale's `t()`, so in the end there's not so much difference.
If using the views localization plugin way, there can be alternate plugins which could provide different approaches for translation, for instance ways that don't require the source language to be English (locale's t() does).

So I think the views localization plugin approach is more flexible.

And as this has been there before and is known to work reliably, why reinventing the wheel?

**Comment by herbdool** [comment]
I agree. They both use locale so I think it's ok. With config translate we didn't have a good way to deal with dynamic and nested variables. Presumably we could still merge the two approaches in the future.

**Comment by klonos** [comment]
> With config translate we didn't have a good way to deal with dynamic and nested variables. Presumably we could still merge the two approaches in the future.

Do we have a follow-up for that?

**Comment by herbdool** [comment]
@klonos we do. Can't look right now but I believe I created it a year or more back.

**Comment by quicksketch** [comment]
I re-reviewed https://github.com/backdrop/backdrop/pull/3132 for a second time and it looks good to me. I agree with the points made here, and this is inline with Backdrop's principles for backwards-compatibility, even if I would like to see something leveraging config translation.

I've merged https://github.com/backdrop/backdrop/pull/3132 into 1.x and 1.16.x.

Thanks @indigoxela for this big lift to get this restored into Backdrop! Views code is particularly complex. Great job!

Thanks @herbdool and @olafgrabienski for your testing and reviewing of this functionality!
