### ISSUE TITLE
PHP notice on "Layouts" page when "Dashboard" disabled

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#4389]
**Description of the bug**

PHP notice on "Layouts" page when "Dashboard" disabled:
`Notice: Undefined index: access dashboard in UserPermissionLayoutAccess->summary() (line 26 of /<document_root>/core/modules/layout/plugins/access/user_permission_layout_access.inc).`

**Steps To Reproduce**

To reproduce the behavior:
1. Disable module "Dashboard"
2. Go to 'admin/structure/layouts'

![layout](https://user-images.githubusercontent.com/11479969/81492516-0b962280-92a1-11ea-8cf2-94431b901624.png)

**Expected behavior**

Disabled (via module) layout should not be checked for user permissions. Maybe such layout should be removed from layouts list.

**Comment by findlabnet** [comment]
Note: uninstalling "Dashboard" module also remove related layout from the list, so this issue can have reasonably low priority.

**Comment by quicksketch** [comment]
Thanks @findlabnet! Seems like we should have a fallback if the look-up of the permission name fails, use the machine name of the permission. As a bonus it would also be preferable to append a message indicating the permission is not defined. e.g. `User has "access foo" permission (missing module)`

**Comment by indigoxela** [comment]
There's some more glitches.

If the dashboard module gets disabled, the menu item in in admin menu stays, only the icon vanishes.
[This](https://github.com/backdrop/backdrop-issues/issues/3888) is the related Issue for that (not actually a duplicate but the same base problem).

And I'm afraid the base problem isn't only affecting the dashboard module.

If a module gets disabled, shouldn't all its config (including layouts) get disabled, too?

The file layout.layout.dashboard.json contains the information `"module": "dashboard",`.
In theory it's possible to prevent the layout from showing up in the list with a `module_exists()`.
Not sure how bad this is performance-wise.

**Comment by indigoxela** [comment]
@quicksketch is of course right, all we need is to check if the permission is provided by any module and if not show some text that describes the problem on the listing page.
(I didn't realize that the disabled state of the dashboard layout is already set properly.)

PR is available, please test and review.

**Comment by indigoxela** [comment]
Regarding the actual text shown I'm open for suggestions:

![screenshot-layout-listing](https://user-images.githubusercontent.com/842066/82032682-dec87d80-969b-11ea-93c1-31d98de17985.png)

**Comment by quicksketch** [comment]
Thanks @indigoxela! I merged https://github.com/backdrop/backdrop/pull/3137 into 1.x and 1.15.x. Thanks @findlabnet for finding and reporting the issue.
