### ISSUE TITLE
Get run-tests.sh script with profile cache running on newer environments

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4392]
**Description of the bug**

Currently running tests via script run-tests.sh _with profile cache on_ doesn't work on newer environments, namely mysql 5.7+ or mariadb 10.2.2+.

These db versions with settings like listed below choke on the `alter table` to MyISAM in backdrop_web_test_case_cache.php.

Message:
`ERROR: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
`

**Steps To Reproduce**

Make sure your db is new enough (on Ubuntu Bionic, Debian Buster...) and has following variables set:

- innodb_large_prefix ON
- innodb_default_row_format dynamic
- innodb_file_per_table ON
- innodb_file_format Barracuda

Then download and install Backdrop (via install.sh or however).

Then go to the Backdrop root directory and try to run the tests with profile caching (param --cache):

`./core/scripts/run-tests.sh --url http://localhost/ --force --cache BlockTestCase`

**Actual behavior**

PDO Exception and no tests run at all.

**Expected behavior**

Tests running.

**Additional information**

I ran into this issue when trying to get Simpletests working with travisCI, but now found a way to reproduce.

Here's the [Zulipchat thread](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/pdo.20when.20running.20tests) with my question.

Joseph Flatt provided a trick: setting `$test->prepareCache(TRUE)` in run-tests.sh bypasses the table conversions to MyISAM - and then the tests run without problem. But patching around in core is no real solution, of course.

**Please note:**

Variable innodb_large_prefix is deprecated in both, mysql and mariadb, and large prefixes will be the default setting after this variable has gone.

See details to the large prefix variable for [MySQL](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix) and [MariaDB](https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix).

**Comment by quicksketch** [comment]
Thanks @indigoxela! I have run into this issue as well. Although switching to MyISAM sped up copying tables quite a lot in the past, I think you're right that we can't depend on that in the current and future MySQL-family, which clearly is moving away from MyISAM support. Let's try dropping the entire conversion and see how that impacts tests. If it's really substantial, say an increase of 20% or more, then perhaps we can give the script a new flag like `./run_tests.sh --cache --myisam-convert` to enable it for ZenCI only.

**Comment by indigoxela** [comment]
So let's gather some numbers.

On a VM known to not being the fastest when running tests, running with following parameters:

`--cache --concurrency 3 --directory core/modules/field/tests/`

**With** MyISAM conversion

Test run duration: 1 min 59 sec

**Without** MyISAM conversion

Test run duration: 9 min 37 sec

Uh-oh, that's a significant difference.

PHP version 7.4, mariadb version 10.1.44 (with innodb_large_prefix OFF and innodb_default_row_format compact, that's why alter table to MyISAM works).

I ran tests with the same parameters, the only difference is that for the second run I disabled table conversion with `$test->prepareCache(TRUE)`.

Between the tests I did a cache cleanup with "--clean".

**Comment by indigoxela** [comment]
Another thought: the tables to convert have just been created for the tests, is that correct? Why not creating them as MyISAM right away? (Didn't dig deeper, though...)

**Comment by indigoxela** [comment]
I'm trying to revive this issue... :wink: 

We could at least get *some* table conversions to MyISAM (and some progress in this issue) if we either:

- Wrap the ALTER TABLE in function alterToMyISAM() in try/catch
- Get a list of all tables that cause trouble because of max key length and add another loop to add those to `$skip_alter` array based on current mariadb/mysql Version and/or after evaluating that the conversion will fail because row format "dynamic" is set to default in the db

**Comment by hosef** [comment]
@indigoxela I have been working on another change in order to mitigate the effect of not being able to convert all the tables here: https://github.com/backdrop/backdrop-issues/issues/4353. One of the changes I did there is to wrap the table conversion in a try/catch, to get rid of the errors.

**Comment by indigoxela** [comment]
@hosef when I did some local tests with try/catch, it turned out that only for a handful of tables the MyISAM conversion still works on newer environments. So the alternate approach (not deleting all, even unchanged tables after individual test runs) looks very promising.

**Comment by indigoxela** [comment]
> I have been experimenting with is to change the default test profile to the testing profile

That might have negative side effects for tests in contrib modules. Not sure about that.

**Comment by hosef** [comment]
> > I have been experimenting with is to change the default test profile to the testing profile
> 
> That might have negative side effects for tests in contrib modules. Not sure about that.

That is true, but I think that it should not be too hard to fix if you need something from the standard profile. I created an issue for that here: https://github.com/backdrop/backdrop-issues/issues/4943, but I don't have a PR ready yet.

**Comment by indigoxela** [comment]
I'd like revive this issue - it's a blocker for [GitHub Actions](https://github.com/backdrop/backdrop-issues/issues/4753), as the default databases in the runners are definitely newer and choke with described error.

It has been discussed to completely drop MyISAM conversion or to add a parameter to explicitly set it, but IMO that would have negative side effects for existing setups like for instance already running tests for contrib.

Instead of that, my suggestion is to add an option to _turn it off_ in a backwards compatible way.
That's what my [PR](https://github.com/backdrop/backdrop/pull/3677) tries to achieve. Please test and review.

**Comment by herbdool** [comment]
@indigoxela I've reviewed the code. Looks good. So this is just extending the use of `$skip_myisam` to the script and I noticed it was originally added last year here: https://github.com/backdrop/backdrop/pull/3076/files

**Comment by indigoxela** [comment]
> So this is just extending the use of $skip_myisam to the script

Yes, skip_myisam is no new invention.
It's currently not available yet on command line, but it would be so useful. Not only for GH Actions, but in all newer environments.

**Comment by quicksketch** [comment]
The PR looks great. I would probably prefer to have the option be `--myisam-convert` rather than the inverted `--skip-myisam`, even if that's a difference in the performance by default, because the conversion to MyISAM is _less compatible_ and does not work on newer environments. I would prefer to have the safe (if slower) option be the default.

However, as we found in #4753, we could potentially switch from converting to MyISAM into converting into ARIA instead, which may have some performance benefit but not as substantial as MyISAM. In that case, it might be nice to have the conversion flags be separate, so you can choose which is appropriate for your environment e.g. `./run-tests.sh --myisam-convert` or `./run-tests.sh
 --aria-convert`.

**Comment by indigoxela** [comment]
> I would prefer to have the safe (if slower) option be the default.

I'm afraid that would affect existing test setups in contrib (and elsewhere). I'm not sure, how many setups exist, I'm only aware of my own. :wink:

As the currently missing option to turn that conversion off on command line is a show stopper for GH Actions, I'd suggest to merge, so the Actions issue isn't blocked. In my experimental branch which implements GH Actions, I put everything in shared mem (db datadir, db tmpdir, and also the /files directory), so IMO conversion wouldn't be faster - that assumption is based on benchmarks posted by @quicksketch in that other issue. BTW Aria currently also suffers from the "key too long" problem.

So maybe we should discuss to completely drop table conversion long term? Potentially in a new issue?

**Comment by herbdool** [comment]
@indigoxela I also now think it should be `--myisam-convert` even though it's not backwards compatible for some with a testing framework. I don't imagine it's very many. It's just safer to consider the default be without the conversion plus it allows for other flags to turn on, without also needing to turn off MyISAM.

**Comment by indigoxela** [comment]
> I also now think it should be --myisam-convert even though it's not backwards compatible for some with a testing framework. I don't imagine it's very many.

Could we figure out, how many contrib projects might be affected? That would give me a little more confidence in this potentially breaking change.

**Comment by herbdool** [comment]
I searched for run-tests: https://github.com/search?q=org%3Abackdrop-contrib+run-tests&type=code. Only a handful and it's not clear how many will be affected by this. Can we say at worst their tests would go slower before they add the flag?

**Comment by hosef** [comment]
what about adding a try/catch block around the table conversion in order to just stop the errors from being generated?
https://github.com/backdrop/backdrop/pull/3106/files#diff-c4dc42bdf299765dd26e48d19428aacdf05309d8de0d29bfe4bb6aee1246dbc1

**Comment by indigoxela** [comment]
> I searched for run-tests ... Only a handful 

That gives me confidence. :+1: Travis is broken anyway, the others (most) avoid to use `--cache` - probably because of the problem we try to solve here.

The current core tests will slow down, but we can switch the param in core/misc/zen-ci/run_tests.php until we can switch to GHA.

> what about adding a try/catch block around the table conversion...

I tried that some times back, but realized that it's no real solution. Conversion would only work for a handful of tables, most of them fail. I'd say: better solve it in a more future-proof way.

So I'll switch the default logic and use a `--myisam-convert` param instead.

**Comment by indigoxela** [comment]
> So I'll switch the default logic and use a --myisam-convert param instead.

Done. :smiley:

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/3677 looks great. Though in the future we may need to change the parameters to `prepareCache()` to expand to non-MyISAM options (like ARIA), this sticks with what we internally but sets us up good for better script options in the future.

I merged into 1.x and 1.19.x. Thanks!
