### ISSUE TITLE
New Backdrop-only modules won't run update hooks when upgrading from Drupal 7.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4396]
New Backdrop-only modules won't run update hooks when upgrading from Drupal 7.

From @quicksketch in https://github.com/backdrop/backdrop-issues/issues/4161#issuecomment-629490558

> I filed a modified version of your PR at backdrop/backdrop#3139 that fixes this problem, any new modules enabled in the D7 -> Backdrop upgrade are assumed to be running at the latest schema version, instead of 0, which makes it so that update.php doesn't think it needs to be run again.

**Comment by jenlampton** [comment]
Can we add a reset as a system module update, that reset's all those new module's schema versions back to zero during an upgrade from Drupal, or would that break other things?

**Comment by docwilmot** [comment]
This is also probably this: https://github.com/backdrop/backdrop-issues/issues/1759

**Comment by klonos** [comment]
Yes it is @docwilmot

**Comment by jenlampton** [comment]
Thank you both :)
