### ISSUE TITLE
VBO: Allow bulk operations for updating entity values (including taxonomy terms)

### ISSUE THREAD

**Issue by newpress** [backdrop/backdrop-issues#4401]
The Views Bulk Operations actions appear limited to basic actions like delete, promote, publish.
I would like to update a taxonomy field in a list of nodes but do not see a way to do this.
Being that taxonomy is THE way we organize content relationships, I see this as a critical feature that appears to be lacking. 
I would greatly appreciate a resolution on this issue.

**Comment by indigoxela** [comment]
> I would like to update a taxonomy field in a list of nodes but do not see a way to do this.

I see, you already tried it [in the forum](https://forum.backdropcms.org/forum/vbo-action-add-terms-nodes).

Yes, compared to D7 VBO in B1 looks a little limited.

Additional info for people who read this and/or are also interested: the actions they'd need are something like _Modify entity values_ as provided by the [D7 contrib module](https://git.drupalcode.org/project/views_bulk_operations/-/blob/7.x-3.x/actions/modify.action.inc).

**Comment by olafgrabienski** [comment]
To be able to modify entity values as a bulk operation, can be very useful. I've used the functionality in Drupal -- not often but in one case it's an essential tool for me. I'd be happy to have this option in Backdrop, too, be it in core or in contrib. @jenlampton, IIRC once you were working on a custom solution for this. Want to chime in?

**Comment by klonos** [comment]
Thanks for taking the time to file this issue @newpress 👍 ...I have added it to the existing meta-issue we have for VBO: #3797

> @jenlampton, IIRC once you were working on a custom solution for this.

See this comment: https://github.com/backdrop/backdrop-issues/issues/3797#issuecomment-495033095

**Comment by olafgrabienski** [comment]
> I have added it to the existing meta-issue we have for VBO

@klonos You had already added it before 😃Now we have two checkboxes there:

- [ ] "Modify entity values" action + options ([see comment](https://github.com/backdrop/backdrop-issues/issues/3797#issuecomment-493886717))
- [ ] ...
- [ ] #4401 | Allow bulk operations for updating entity values (including taxonomy terms)

**Comment by klonos** [comment]
Right 😅 ...fixed.

**Comment by indigoxela** [comment]
Some digging... The D7 version of views_bulk_operations relies on entity_metadata_wrapper() function, which is provided by [entity_plus](https://backdropcms.org/project/entity_plus) (Backdrop contrib module).

So I'm leaning towards "Modify entity values" actions go to a contrib module, too. I didn't dig deeper, though, what is needed to get a module up and running with comparable functionality.

**Comment by oadaeh** [comment]
I haven't looked at the code to verify, but if all it is using is the functionality to wrap the objects and chain their methods & properties, it should be possible to do it "long hand" by instantiating each object individually, using the ID of the previous object to load the next one.

**Comment by irinaz** [comment]
Contrib module  for Views Bulk Operation that adds option "Modify entity values" sound like a perfect solution.  Should we open an issue for porting VBO module to Backdrop in https://github.com/backdrop-contrib ?

**Comment by olafgrabienski** [comment]
> Should we open an issue for porting VBO module to Backdrop

Sounds interesting, but how would we handle it that parts of VBO are already in Backdrop core?

**Comment by irinaz** [comment]
I do not have a good answer from the coding perspective, but I know that in D9 there are two bulk operations modules - one is in core (node bulk) and another one adds other options, like "modify value"  (https://www.drupal.org/project/views_bulk_operations).  I think that it is very similar approach.

**Comment by argiepiano** [comment]
I have just ported [Views Bulk Operations](https://github.com/backdrop-contrib/views_bulk_operations) to Backdrop. 

Among the configurable actions now available in VBO, is "Modify entity values" - so now it's possible to do that. 

Please read more details about this port here:
https://github.com/backdrop/backdrop-issues/issues/3646#issuecomment-1120498234

**Comment by olafgrabienski** [comment]
I've just tested the contrib module, it works nicely! Should we close this issue and mark it as `contrib candidate`?

**Comment by argiepiano** [comment]
Agreed. I'll close. Eventually it'd be great to merge the features provided by VBO this into core's Bulk Operations
