### ISSUE TITLE
Empty mail to admin because of missing subject/body for register_pending_approval_admin

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4403]
**Description of the bug**

This popped up [in the forum](https://forum.backdropcms.org/forum/empty-email-send-administrator-created-new-user-account). Two people were able to reproduce it.

**Steps To Reproduce**

When user registration with admin approval is enabled, the site owner should get a mail whenever a new user registers. This mail has empty subject and body because Backdrop has no values set for _register_pending_approval_admin_.

This is where the mail gets sent: https://github.com/backdrop/backdrop/blob/7cf6dcb736532491f4796136acd98431008eb760/core/modules/user/user.module#L2765

Note: this is the only occurrence of "register_pending_approval_admin" in Backdrop.

Drupal 7 sets the values in function _user_mail_text(), Backdrop doesn't.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop-issues/issues/3148) is available.

When testing this, make sure your site mail (admin/config/system/site-information) is a real address able to receive mail.

Which leads me to a question: shouldn't we use user number one's (uid 1) email account instead as recipient?

Backdrop sets the site email to noreply@... by default - which is probably the cause that it lasted some time until someone found this bug.

Or even better: make the recipient address configurable. The site email is a bad choice for sure, but uid 1 might also inappropriate.

Feedback is welcome!

**Comment by olafgrabienski** [comment]
> A PR is available.

@indigoxela Thanks for the PR, I'm looking forward to test it! Before, one small thing: The link in your comment points to `.../backdrop-issues/issues/3148`, I guess it should be `.../backdrop/pull/3148`.

**Comment by olafgrabienski** [comment]
I've tested the PR using the sandbox website:

- enabled user registration with admin approval
- changed the site mail temporarily to an existing address
- created an account as a new user

The PR works well, the user got a mail which was not empty! Here's the content of the mail:

Subject:
> Account details for USER NAME at SITE NAME (pending admin approval)

Body:
> USER NAME has applied for an account.
>
> SITE-URL/user/ID/edit

That's all we need, and the texts can even be adapted in the settings, great! I'd suggest however to change the Subject to make it a bit more clear and less wordy by default, e.g.:
> New account of USER NAME at SITE NAME (pending approval)

**Comment by olafgrabienski** [comment]
> shouldn't we use user number one's (uid 1) email address instead as recipient? (...)
> Or even better: make the recipient address configurable.

Thanks for bringing up this question! We discussed a site-wide TO mail address setting a while ago. Should we add this use-case to that [issue](https://github.com/backdrop/backdrop-issues/issues/2365) and  move forward over there?

**Comment by indigoxela** [comment]
> Should we add this use-case to that issue and move forward over there?

@olafgrabienski many thanks for pointing to that [existing Issue](https://github.com/backdrop/backdrop-issues/issues/2365). Yes, that looks like a better place to discuss this further.

Regarding the shorter mail subject: yes, less verbosity really makes sense here.

**Comment by herbdool** [comment]
Looks good to me

**Comment by jenlampton** [comment]
> When testing this, make sure your site mail (admin/config/system/site-information) is a real address able to receive mail.

> Which leads me to a question: shouldn't we use user number one's (uid 1) email address instead as recipient?

Yes, there should be nothing anywhere in backdrop core that sends mail TO `site_mail` that is a FROM email address only. If there is, that is an oversight and was not corrected when we removed the FROM address from the installation form.

> Or even better: make the recipient address configurable. The site email is a bad choice for sure, but uid 1 might also be inappropriate.

I would like to see this be configureable, perhaps on the same page where the text for the emails can be configured. The default value should be the email address from user/1. I believe we do this in contact module also, it would be good to follow the same pattern. 

Should this be a follow-up issue?

**Comment by olafgrabienski** [comment]
> I would like to see this be configureable (...) Should this be a follow-up issue?

@jenlampton or use the existing one #2365, seems right the right place to me, what do you think?

**Comment by jenlampton** [comment]
@olafgrabienski I was talking about a specific setting for the administrator approval emails, not the site-wide global setting. (We need both)

**Comment by olafgrabienski** [comment]
I see! The admin approval emails could however also be part of the existing issue #2365 which is open for several uses. However, I've no strong feelings which is the best place. The page with the emails texts sounds reasonable at first sight.

**Comment by jenlampton** [comment]
Since this issue is RTBC I'm going to start a new one about fixing the from/to email address bug. I don't want to delay this any more :) 

See https://github.com/backdrop/backdrop-issues/issues/4428

**Comment by herbdool** [comment]
>>When testing this, make sure your site mail (admin/config/system/site-information) is a real address able to receive mail.
>
> no no we shouldn't be telling people to do this. This is likely to make all messages coming from the site undeliverable :(

@jenlampton for the purposes of this PR, @indigoxela advice was correct. We are testing the email message, not *where* it is going to.

**Comment by jenlampton** [comment]
I just didn't want anyone doing that on their own sites to get around the admin approval problem. Moved that over to the other issue though, don't want to disrupt the rtbc here :)
