### ISSUE TITLE
Notice: Undefined property: Comment::$comment_body in comment_submit() (line 2135 of comment.module).

### ISSUE THREAD

**Issue by nickonom** [backdrop/backdrop-issues#4411]
**Description of the bug**

The bug appears if you delete the default $comment_body field, create a custom field and try to post a comment.

**Steps To Reproduce**

To reproduce the behavior:
1. Go to any content type's comment fields settings page, for example, `/admin/structure/types/manage/post/comment/fields`.
2. Delete the default comment body field and add another field instead.
3. Go to `node/1/` and add a comment.
4. Find the reported PHP error on `/admin/reports/dblog`.

**Additional information**

The same error for Drupal 7 is discussed on https://www.drupal.org/project/drupal/issues/1038652

**Comment by indigoxela** [comment]
@nickonom many thanks for reporting this bug!

The [D7 patch](https://www.drupal.org/files/issues/1038652-128.patch) has some code that already is in Backdrop core, but we still do not check if comment_body actually exists before trying to access it.

https://github.com/backdrop/backdrop/blob/36b5ba3f4141f1ac0c0057359da67e6e7832a84d/core/modules/comment/comment.module#L2135

**Comment by indigoxela** [comment]
A [PR](https://github.com/indigoxela/backdrop/pull/new/undefined-prop-comment) is available for testing and review.

How to test: follow the instructions provided in Issue description.

Additionally, after you created some (pointless) empty comments, also visit admin/content/comment and check that no php notices happen there.

**Comment by alanmels** [comment]
I just have tested this, works as expected, so no more errors. Has everything that is on https://www.drupal.org/files/issues/1038652-128.patch. Looks nice to me.

**Comment by herbdool** [comment]
Looks good to me.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/3149 into 1.x and 1.16.x. Thanks @indigoxela, @alanmels, @nickonom, and @herbdool!
