### ISSUE TITLE
[UX] Better label for "allow comment title" option

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4413]
We are working on a Backdrop project which intensively deals with comments, so expect lot's of comment-related issues from AltaGrade these days.

**Description of the need**

Ensure the comment titles are not allowed in content type settings:

![no-comment-titles](https://user-images.githubusercontent.com/56604405/82708727-3044af80-9c3c-11ea-8d46-ea675f7e889f.jpg)

Add new comments on a content page and you will see the `(No subject)` comment titles everywhere like so:

![comment-subjects](https://user-images.githubusercontent.com/56604405/82708748-405c8f00-9c3c-11ea-91ed-7fb161077063.jpg)

**Proposed solution**

I believe the whole point of not allowing comment titles in the settings is about not seeing any kind of titles. The `(No subject)` comment titles would make sense if the comment titles were allowed, but entered empty when comments submitted. Therefore, I suggest to completely remove comment titles in the comments if they were not allowed in the settings.

**Comment by indigoxela** [comment]
> We are working on a Backdrop project which intensively deals with comments, so expect lot's of comment-related issues from AltaGrade these days.

Yes, obviously... :wink: 

> I believe the whole point of not allowing comment titles in the settings is about not seeing any kind of titles.

Interesting question. The setting "Allow comment title" really only handles the ability to set subjects manually. It's not meant to handle the display.
And there's (as far as I know) no option to handle the subject display via UI.

That may be because the comment subject has additional purposes. It also holds the permalink / bookmark feature and the "is new" labelling.

**Comment by alanmels** [comment]
Well, then maybe the wording "Allow comment title" should be changed to something like "Allow setting subjects manually"? Semantically when you do not "allow comment titles", then you do not expect to see any titles.

I see the link also has permalink, and it could be easily replaced with something like:

``Permalink #cid```

or just:

```#N```

Outputting the comment id or the sequential order number of the comment on the page will look much more appealing and nicer than outputting `(No subject)` when the user actually didn't want to see any subject.

**Comment by stpaultim** [comment]
I am working on the website for Backdrop CMS Live event and I am running into this problem and it seems REALLY weird. 

#1) "Allow comment title" is turned off (I see the point, that this might just be mislabeled). 
#2) My comments are all being auto populated by a title, which is really just the first line of text from the comment, formatted as a link which really does nothing but take me to the comment I'm already on. 

This title and/or link looks really weird and doesn't serve any purpose that I can imagine. Also, I can't find anyway to hide this in the UI. 

![Your_first_post____Comments](https://user-images.githubusercontent.com/3144571/91003581-4fced980-e597-11ea-8ee5-81252ae57431.png)

In my view, we definitely need to relabel that configuration option for comments. BUT, we really should provide an option to remove titles completely.

**Comment by stpaultim** [comment]
So, I created a PR that adds one word. It changes "Allow comment title" to "Allow custom comment title." I believe that this is much more descriptive of what is actually happening, but I am open to better text. 

I'm changing this from "Feature Request" to "But report" - IMHO it is a UX bug. It does not accurately describe to the user what is happening. I'm also marking this as a milestone candidate. 

I will be opening up a new issue to make the title optional as I think that is the more important change.

**Comment by klonos** [comment]
Thanks @stpaultim 👍 ...this makes way more sense now (and thanks for filing the follow-up as well). Can we also please add another line here, to add some help text for that option? Something like:

`The default is to automatically add the first x characters of the comment as its title.`

**Comment by stpaultim** [comment]
Is "x characters" sufficient or do I need to figure out what x equals?

If not, I added your text exactly as is.

**Comment by klonos** [comment]
I meant to figure out what x is 🤣

**Comment by klonos** [comment]
...alternatively, we can say "the first few characters".

**Comment by klonos** [comment]
...I also meant to add the description in the form element (as help text).

**Comment by stpaultim** [comment]
@klonos - How does this look?

![Screen Shot 2020-08-30 at 2 15 09 AM](https://user-images.githubusercontent.com/3144571/91653450-a5f3bf00-ea66-11ea-8be9-5ee4e2d053a0.png)

**Comment by klonos** [comment]
Yup, that works fine. Thanks 👍

**Comment by BWPanda** [comment]
I'm not happy with the wording here... I'd suggest:

**Allow a custom title to be set for each comment**
When disabled, the comment title will be automatically generated from the comment text.

**Comment by klonos** [comment]
Or, we could make this a radio set, with 2 options and no help text:

**Comment title behavior**
- ( ) Comment authors may customize the titles of their own comments
- ( ) Comment titles are automatically generated from the comment text

**Comment by stpaultim** [comment]
@BWPanda - I like your text better. Thanks. I was unhappy with the phrase "The default is to ..." I like your solution better.

**Comment by BWPanda** [comment]
@stpaultim I also suggested different text for the label of the checkbox, not just the description text.

**Comment by stpaultim** [comment]
@BWPanda Sorry, I skimmed and acted too quickly. I'm fine with your change there. I was worried that my suggestion was too long already, I see yours is slightly longer. But, it's also more clear. 

![comments-66458](https://user-images.githubusercontent.com/3144571/91768925-050b1e00-eba4-11ea-8252-0f96153dad36.png)

**Comment by BWPanda** [comment]
Looks good to me. Nice simple change. RTBC.

**Comment by BWPanda** [comment]
Thanks everyone! @alanmels for reporting this discrepancy, @stpaultim for the PR, and @indigoxela & @klonos for helping review and give feedback. I've merged https://github.com/backdrop/backdrop/pull/3263 into 1.x and 1.16.x.
