### ISSUE TITLE
Clean up formatting and line-length on .txt files in core

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4417]
There are some issues in some of the core text files, namely lines overflowing the 80-character mark and non-centered headings in the LICENSE file.

**Comment by klonos** [comment]
Looks good @BWPanda 👍 ...RTBC.

PS: this is part of #3213

**Comment by BWPanda** [comment]
Thanks for the review @klonos. Merged https://github.com/backdrop/backdrop/pull/3150 into 1.x.
