### ISSUE TITLE
Remove unnecessary string concatenation

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4424]
There's a small code change I noticed we should make in `config_install_default_config()`, simply because there's no reason why it should be done the way it is and changing it would make it slightly more readable:

`$files = glob($module_config_dir . '/' . '*.json');` -> `$files = glob($module_config_dir . '/*.json');`

**Comment by BWPanda** [comment]
Hmm, this might be the tip of a larger iceburg... Noticed quite a few other instances of this in core (e.g. https://github.com/backdrop/backdrop/blob/557824453eeec969800c2ff47db7bde4da036467/core/includes/theme.inc#L635). If someone can confirm this is unnecessary coding, I'll go through and fix the rest in the PR as well.

**Comment by indigoxela** [comment]
> Hmm, this might be the tip of a larger iceburg [...] If someone can confirm this is unnecessary coding

I think you're right. This looks like something that happened when somebody was already pretty tired (or hungry, or both).

Go for it!

**Comment by BWPanda** [comment]
Ok, so I found more instances of that code and fixed them in the updated PR.

**Comment by indigoxela** [comment]
> Ok, so I found more instances of that code

Ooops, that's the "iceberg" you meant, I see...

Code is looking good. Test are passing (except for unrelated old buddy BootstrapPageCacheTestCase).

There's actually nothing to test here, so RTBC.

Out of curiosity: how did you find all those redundant `' . '` so quickly? Recursive regex grep?

**Comment by BWPanda** [comment]
@indigoxela Yep, just ran `grep -ir --color "' \. '"` from the `/core` directory (and then went through each one to make sure it wasn't a legitimate case for `' . '`, such as this one from `core/includes/transliteration/x0d.php`: `0xF0 => NULL, NULL, 'RR', 'LL', ' . ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,`).

**Comment by herbdool** [comment]
I wonder if it was written that way to allow for changing the directory separator to something else? Like for Windows?

**Comment by indigoxela** [comment]
> I wonder if it was written that way to allow for changing the directory separator to something else?

How could that work then anyway? For example:
`'site_logo_path' => $GLOBALS['base_url'] . '/' . 'core/misc/feed.png',`

I still believe, these redundant concatenations just went in by mistake.

**Comment by klonos** [comment]
The PR is RTBC, so adding milestone 😉

**Comment by jenlampton** [comment]
@klonos I think this can go in the bugfix milestone. Any reason you chose 1.17?

**Comment by BWPanda** [comment]
@jenlampton I think we were thinking this wasn't a bug, as in nothing's broken per se. Hence the minor release milestone/tag.

**Comment by jenlampton** [comment]
There's nothing in here that would cause an API break, so it's safe to put it into a bug-fix release if it's just a cleanup task. Things that need to wait for a minor release are things that contain some inherent risk. Maybe this all needs to be better documented somewhere. Tasks are a bit of a gray area.

**Comment by BWPanda** [comment]
Ah ok, I didn't realise tasks were equivalent to bug fixes:

> It must be tagged with either the label "type - bug report", or the label "type - task"

Makes sense now.

**Comment by jlfranklin** [comment]
The redundant concatenation for the wildcards is probably to prevent `/*.json` from looking like a comment.  Maybe an old version of PHP choked on it, maybe some IDE's pretty-printing went awry.

The one with the "year, month, day" in the string may have been an overzealous code-style auto-formatter insisting there be spaces between strings and the `.` concatenation operator.

Others may be readability or ensuring tags and end-tags are in their own strings.

(Note: I'm not objecting to the patch or anything like that.  Just providing plausible reasons for why the code was that way.)

**Comment by quicksketch** [comment]
Thanks @jlfranklin, those are some good hypotheses. I didn't see any problems with the code as it was and merged it earlier (and forgot to mark this fixed).

I've merged https://github.com/backdrop/backdrop/pull/3154 into 1.x and 1.16.x. Let me know if there is anything further that we should consider here.
