### ISSUE TITLE
EntityMalformedException: Missing bundle property on entity of type comment

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4426]
**Description of the bug**

If you canceled a user account, which had added comments previously, by choosing "Delete the account and its content" option while the Comment module is disabled and enabled the Comment module afterwards, then pages where the deleted user added comments give the reported error.

**Steps To Reproduce**

1. Create a node as the admin user.
2. Log in as a regular user and leave a comment on the node.
3. Log back in as the admin, disable the Comment module, cancel the regular users account by choosing the "Delete the account and its content" option, and then turn the Comment module back on again.
4. Visit the node and you will see the following fatal error on UI:

```
Error
Missing bundle property on entity of type comment.
```

If you proceed to the **Recent log messages** (`/admin/reports/dblog`) page, then you will see three different entries:

```
EntityMalformedException: Missing bundle property on entity of type comment. in entity_extract_ids() (line 350 of /var/www/docroot/core/modules/entity/entity.module).
```

```
Warning: Creating default object from empty value in comment_prepare_thread() (line 900 of /var/www/docroot/core/modules/comment/comment.module).
```

```
Notice: Undefined variable: key in comment_prepare_thread() (line 900 of /var/www/docroot/core/modules/comment/comment.module).
```

**Additional information**

Checking the `comment` table in the website's database shows the test comment by regular user was never deleted, apparently because the Comment module was disabled when the user got deleted. 

This exact situation is discussed on https://www.drupal.org/project/drupal/issues/1451072 and there is a working patch over there, which hopefully will work as well for Backdrop.

**Comment by indigoxela** [comment]
@alanmels Many thanks for reporting this bug. Yes, that's a nasty one, as nodes with attached comments by (in the meantime) deleted users can't get accessed anymore because of the exception. I just verified that this also affects Backdrop.

Using the logic from the Drupal patch seems feasible.

One disadvantage is that there still will be some orphaned data in the database (fields attached to comments...). On the other hand there's no possibility to properly delete an already broken comment entity. So this approach, while not perfect, seems a lot better than the current situation, where we end up with totally broken nodes.

**Comment by alanmels** [comment]
@indigoxela, thanks for the input. 

> One disadvantage is that there still will be some orphaned data in the database (fields attached to comments...). On the other hand there's no possibility to properly delete an already broken comment entity. 

Why? Never tested, but I had an impression that the "Delete the account and its content" option removes all the relevant content. 

If choosing that option really does delete all the relevant content in normal (i.e. when the Comment module is enabled) circumstances, then all we need to do is to make that option to take into account states when the Comment module is disabled.

If that option leaves orphaned data in the database regardless if the Comment module (of for that matter any other module) was disabled or not at the moment of action, then we are talking about different bug in the core and then it's better be fixed. Don't you think so?

**Comment by indigoxela** [comment]
> "Delete the account and its content" option removes all the relevant content.

Right, but the comment module is _disabled_ at that moment, hence it can't do its job. That's why this problem exists anyway. :wink: 
I verified that orphaned data exist (and stay) in the database then.

**Comment by alanmels** [comment]
Then maybe we should attempt to make it so the option DOES delete all the relevant content regardless if the Comment module is disabled or not?

**Comment by indigoxela** [comment]
@alanmels I'm currently working on it, give me a little more time, please :wink:

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3156) is available for testing and review.

While my approach is based on the Drupal patch, it's going beyond that by additionally cleaning up the comment db table in hook_enable.

**Comment by alanmels** [comment]
@indigoxela Thanks for the PR. I've just previewed it and left a comment.

**Comment by indigoxela** [comment]
@alanmels many thanks for having a look, the PR has been updated accordingly.

**Comment by indigoxela** [comment]
@alanmels you already tested and reviewed code, but the Issue labels are still the same (needs testing / code review).
Is that by intention?

**Comment by alanmels** [comment]
@indigoxela Unfortunately, I don't see any options on my UI to set labels. I don't think I was granted sufficient permissions to change labels.

**Comment by herbdool** [comment]
I've added a comment in the PR @indigoxela

**Comment by indigoxela** [comment]
@herbdool many thanks for reviewing.

I understand your concern regarding "delete vs. anonymous", but I think the way it is done now is less problematic. Likely we won't be able to find a 100% solution, we can only choose what we consider to be less bad:

1. comments are gone but actually should be assigned to anonymous
2. comment are still there (anonymous) but should have been deleted (e.g. spam)

It's impossible to know with which parameters a user account got cancelled while the comment module was disabled. The only thing we reliably know is that the uid is gone.

**Comment by herbdool** [comment]
Perhaps instead of making an arbitrary decision we should add an entry to the status report announcing there are orphaned comments. And allow admins to choose what happens (not sure how we'd do that - a couple buttons?).

Anyone want to weigh in on this?

**Comment by indigoxela** [comment]
Before this gets too complicated (additional form in UI) - we could check the default setting for user cancellation:

`$default_method = config_get('system.core', 'user_cancel_method');`

Then handle orphaned comments based on that setting (reassign or delete).
If we don't find consensus, it might be better to leave orphaned comments untouched.

**Comment by herbdool** [comment]
That might work, use the default method for the site.

**Comment by alanmels** [comment]
What about properly processing the content (including comments) during user deletion regardless if Comment module was enabled or disabled at the moment? I mean, the reported problem is the result of the fact the Comment module was disabled at the moment when user was deleted, otherwise (if it was enabled) the system takes proper care of the relevant content. So logic tells me instead of dealing with the orphaned content, it's much better to make the system do the exactly the same job for relevant content even if the Comment module is disabled. You see what I mean?

**Comment by indigoxela** [comment]
It seems, the database cleanup job needs some more discussion.

But as the main problem described here is an Exception, I'd suggest to get the fix into core without delay and discuss the proper cleanup of orphaned data in a new Issue. That's why I removed the database query in hook_enable().

**Comment by herbdool** [comment]
I've marked it ready for committing since it was previously tested and only change was removing one thing. Tests are passing for 5.3 and for 7.0 I can't see which two are failing but assume they're unrelated.

**Comment by quicksketch** [comment]
Thanks folks! That failing test was indeed unrelated.

With the agreement here and the sign-off from @herbdool, I've merged https://github.com/backdrop/backdrop/pull/3156 into 1.x and 1.16.x. Thanks!

**Comment by alanmels** [comment]
Thanks guys for getting this sorted!
