### ISSUE TITLE
Add a new icon for "Structure" in the admin bar

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4427]
This came up in #3906, where we are planning to modernize the dated sorting icons in sortable tables, and these ones are considered as an option:

![image](https://user-images.githubusercontent.com/2423362/83572625-941b8200-a532-11ea-847a-138d203fff03.png)

(the icon we currently use for the Structure menu item in the admin bar is the `sort-amount-down` variant)

Drupal uses this:

![image](https://user-images.githubusercontent.com/2423362/83572781-d93fb400-a532-11ea-88e0-f59be24f0f4d.png)

For reference, here is a screenshot of our current admin toolbar. 

![Home___Grace_Hopper1](https://user-images.githubusercontent.com/3144571/94849228-b5aa4e80-03ea-11eb-8e79-44223beb61ee.png)

---

Options are as follows:

6 **layer-group** https://github.com/backdrop/backdrop/pull/3440
<img width="1278" alt="Screen Shot 2021-08-29 at 4 23 55 PM" src="https://user-images.githubusercontent.com/397895/131268670-772f35af-8745-41b3-87c6-db5b6f231868.png">

2 **cubes** https://github.com/backdrop/backdrop/pull/3441
![image](https://user-images.githubusercontent.com/2423362/102011653-41771a00-3d4e-11eb-90b7-223e9951e9c7.png)

0 **list-tree**** https://github.com/backdrop/backdrop/pull/3439
![image](https://user-images.githubusercontent.com/2423362/102011721-ccf0ab00-3d4e-11eb-9d32-836de430d499.png)

1 **Sitemap (what Drupal did)** https://github.com/backdrop/backdrop/pull/3442
![image](https://user-images.githubusercontent.com/2423362/102011666-65d2f680-3d4e-11eb-86e1-1525bdf8f0d0.png)

1 **Sort (current)**
![Home___Grace_Hopper1](https://user-images.githubusercontent.com/3144571/94849228-b5aa4e80-03ea-11eb-8e79-44223beb61ee.png)

**Comment by klonos** [comment]
Here are the ones that find more relevant (out of the free ones provided by font-awesome):

![image](https://user-images.githubusercontent.com/2423362/83572838-f6748280-a532-11ea-8959-88cd1f929596.png)

![image](https://user-images.githubusercontent.com/2423362/83572930-20c64000-a533-11ea-869b-8a1296b74fb0.png)

icofont also has this:

![Screen Shot 2020-06-03 at 12 46 43 am](https://user-images.githubusercontent.com/2423362/83573244-b8c42980-a533-11ea-8297-5849b8747f5a.png)

**Comment by jschen1721** [comment]
In terms of consistency in style, I think that the sort, cubes, cube, and sitemap icons are pretty consistent and fit well together. It seems that dice-d20 and layout icons don't fit in with the others as well. Particularly regarding minimalism and roundness of the icons, dice-d20 and layout seem busier and have sharper angles than the others.

**Comment by stpaultim** [comment]
I just edited the issue summary to add a screenshot of the entire admin menu to put this issue into better context. 

Personally, I like the cubes icon. It seems like a good "structure" icon.

**Comment by klonos** [comment]
To help us decide, although I couldn't find any such icons in fontawesome, we could look for things that resemble structure, such as:

- lego blocks
- tetris blocks
- molecules
- dna chains
- bee hive hexagons

Some examples from around the web:

<img src="https://user-images.githubusercontent.com/2423362/101800263-c2979c80-3b15-11eb-83f9-97c25547cde0.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/549721

<img src="https://user-images.githubusercontent.com/2423362/101799877-4e5cf900-3b15-11eb-9714-06cba316dd77.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/35523

<img src="https://user-images.githubusercontent.com/2423362/101799941-5e74d880-3b15-11eb-9793-18da6540c23a.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/35576

<img src="https://user-images.githubusercontent.com/2423362/101799652-16ee4c80-3b15-11eb-9ac1-6f06d058b7c5.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/573415

<img src="https://user-images.githubusercontent.com/2423362/101797694-fde49c00-3b12-11eb-9c16-8ae7a54bbf13.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/493802

<img src="https://user-images.githubusercontent.com/2423362/101798778-28832480-3b14-11eb-9039-f90a6c5fd74c.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/535156

<img src="https://user-images.githubusercontent.com/2423362/101799100-697b3900-3b14-11eb-8ec1-f5f0adb5e5da.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/491316

<img src="https://user-images.githubusercontent.com/2423362/101799280-a6dfc680-3b14-11eb-9c46-5f4408810191.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/499131

<img src="https://user-images.githubusercontent.com/2423362/101799201-8b74bb80-3b14-11eb-9a50-72788f86b48e.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/56389

**Comment by klonos** [comment]
...here's a couple more:

<img src="https://user-images.githubusercontent.com/2423362/101978066-e284a880-3c5a-11eb-8548-4bff57dea5e4.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/456816

<img src="https://user-images.githubusercontent.com/2423362/101978052-caad2480-3c5a-11eb-90d7-8833337afab6.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/456815

**Comment by klonos** [comment]
I've opened this issue: https://github.com/FortAwesome/Font-Awesome/issues/17475 in hope that FontAwsome would add new icons that look like the last two in my previous comment.

**Comment by klonos** [comment]
The new Claro-based admin theme Gin uses https://fontawesome.com/icons/layer-group for the "Structure" menu:

![layer-group-solid](https://user-images.githubusercontent.com/2423362/102001821-f5e94f80-3cfe-11eb-8e7d-599b3d9359fd.png)

![image](https://user-images.githubusercontent.com/2423362/102001834-10232d80-3cff-11eb-9c80-96a29283e39a.png)

I like it!

**Comment by klonos** [comment]
Here's a PR using the to-be-added `list-tree` FontAwesome icon (**we'll need to wait for the offical release, to see if it's free/GPL**): https://github.com/backdrop/backdrop/pull/3439

![image](https://user-images.githubusercontent.com/2423362/102006240-35786180-3d28-11eb-95e6-be729ecff3fe.png)

**Comment by klonos** [comment]
Here's another PR using the existing [`layer-group` icon](https://fontawesome.com/icons/layer-group) (GPL/free): https://github.com/backdrop/backdrop/pull/3440

![image](https://user-images.githubusercontent.com/2423362/102006359-42e21b80-3d29-11eb-8508-435e46568621.png)

**Comment by klonos** [comment]
Here's yet another PR, using the [`cubes` icon](https://fontawesome.com/icons/cubes) (GPL/free): https://github.com/backdrop/backdrop/pull/3441

![image](https://user-images.githubusercontent.com/2423362/102006478-095de000-3d2a-11eb-866f-7af99b02f0b6.png)

**Comment by BWPanda** [comment]
I'm torn between the `layer-group` icon and the `cubes` icon...

`layer-group` looks better when shrunk down (it's more minimal, less busy) and I guess having the same icons as Drupal might have some advantages.

'cubes' seems to fit the idea of 'structure' better (to me) - as in, the 'building blocks' of Backdrop are the things in that menu (content types, layouts, taxonomy, etc.).

**Comment by olafgrabienski** [comment]
Visually, I like the layer-group much more. Idea-wise it's also okay, in my opinion.

**Comment by klonos** [comment]
> ...having the same icons as Drupal might have some advantages.

I also like `layer-group` better, but that's what's used in the toolbar that comes with the Gin contrib theme; core Seven and Claro still use the core toolbar, which uses the `sitemap` icon. Perhaps I should file a PR for that too, in case people prefer it.

**Comment by klonos** [comment]
Here's a PR that uses the same https://fontawesome.com/icons/sitemap icon as D8 core default toolbar: https://github.com/backdrop/backdrop/pull/3442

![image](https://user-images.githubusercontent.com/2423362/102011614-f8bf6100-3d4d-11eb-91be-c8c77ee657ed.png)

**Comment by stpaultim** [comment]
I'm not too worried about this issue. Here are my thoughts.

1) I understand the concerns about the current icon, but personally am not too worried about it.
2) I agree that any of the four suggested alternatives to the current choice are probably an improvement.
3) Of the four suggested alternatives, I think I like the layers and the blocks best. Mostly because of their simplicity and appearance at small sizes. But, I would not object to either of the other two.

**Comment by bugfolder** [comment]
I find **layer-group** more readable than **cubes**, but that could be just my eyesight.

**Comment by klonos** [comment]
Thanks @stpaultim and @bugfolder ...FTR, can you please add a 👍 / 👎 tot he comment with the icon(s) you like/dislike?

**Comment by herbdool** [comment]
I vote for layer group.

**Comment by herbdool** [comment]
I've tested and reviewed https://github.com/backdrop/backdrop/pull/3440, which seems to have the most votes.

**Comment by klonos** [comment]
Can we also get a milestone label added here? (I can't do it, since I've raised this issue + filed all the PRs).

**Comment by quicksketch** [comment]
Thanks folks. I've merged https://github.com/backdrop/backdrop/pull/3440 into 1.x for 1.20.0.
