### ISSUE TITLE
Clarify validation message when posting comments with existing username

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4429]
**Description of the need**

If an anonymous user attempts to post a comment putting under the _Your name_ field his name, which to his/her "luck" coincides with a registered username, then all s/he gets is the _The name you used belongs to a registered user._ message, because of the following [condition check](https://github.com/backdrop/backdrop/blob/497c43b0b7a99b63ca1db81683b9ff59aa99ffac/core/modules/comment/comment.module#L2089):

```
elseif ($form_state['values']['is_anonymous']) {
    // Validate anonymous comment author fields (if given). If the (original)
    // author of this comment was an anonymous user, verify that no registered
    // user with this name exists.
    if ($form_state['values']['name']) {
      $query = db_select('users', 'u');
      $query->addField('u', 'uid', 'uid');
      $taken = $query
        ->condition('name', db_like($form_state['values']['name']), 'LIKE')
        ->countQuery()
        ->execute()
        ->fetchField();
      if ($taken) {
        form_set_error('name', t('The name you used belongs to a registered user.'));
      }
    }
  }
```

Git blame shows the check was introduced to resolve the problem for _Cannot override comment author to or from Anonymous_ reported on https://www.drupal.org/node/936844. Good for the problem was addressed, but at the same time the solution introduced a new problem: now users with popular names (e.g. Sarah, Tom, John, Alan, etc.) putting their real names under the _Your name_ field are punished, because the filed is validated against existing usernames in the database. 

To me it's a regression, because the UI does not explicitly explain one real Tom why he can not use his own real name. However, even if properly reflected (in unlikely scenario the  _Your name_ should become  _Your username_) it is not welcoming at all as it makes new users feel like we said _Sorry Tom, we have another Tom, therefore you can not be Tom_.

**Proposed solution**

Ideally, names and usernames must be explicitly separated and differed. And not only for comment forms, but everywhere in the system. While usernames must stay unique for each user, multiple occurrences of the same name should be allowed. 

I realize it's a bold proposal about probably massive code change in the core. Therefore, in case if this will be met by rather conservative take, I have alternative just a minor change proposal: at least, the message should be changed to something like:

> The name you used is a registered username. If it belongs to you then login to post. If not then use another name.

Please polish the text to make it more appealing to a confused user as otherwise the original text  _The name you used belongs to a registered user._ is not fool-proof as it does not suggest to take any further steps for those users who do not realize their names had already been taken and who just need to use another name.

**Comment by shruti1421** [comment]
Can I work on this issue?

**Comment by klonos** [comment]
Yes, please feel free to work on this @shruti1421, and let us know if you need any help.

**Comment by indigoxela** [comment]
@shruti1421 many thanks for providing a pull request. It still needs a little work, though, because the automated test related to that form error message is currently failing. The new text should get used in that test, too.

This is the failing test: https://github.com/backdrop/backdrop/blob/08f9bf83c717088a7544325c2e4b05a626e55a50/core/modules/comment/tests/comment.test#L1190

Updating tests can be a bit daunting at first. Please let us know, if you need any guidance.

**Comment by klonos** [comment]
I've made a suggestion re adding commas to the if/then text conditionals (not code - grammar), but I'm not sure that using the word "post" is ideal 🤔 

The original suggestion for the error message by @alanmels is this:

> The name you used is a registered username. If it belongs to you then login to post. If not then use another name.

...if you add the commas to it, it becomes:

> The name you used is a registered username. If it belongs to you, then login to post. If not, then use another name.

I'm suggesting this instead:

> The name you entered is already used by an existing user account. If the account belongs to you, then log in to use it. If not, then enter another name.

**Comment by shruti1421** [comment]
I've completed this task, can you please check and suggest any changes?

**Comment by indigoxela** [comment]
Hi @shruti1421 many thanks for working on this issue.

Hint: if you link this issue in your PR's description with the Word `Fixes` prepended, then two things happen:

1. The PR gets automatically linked here in the issue header, so people can easily find it to test and review.
2. The PR will automatically close this issue, as soon as it gets merged.

Let us know, if you need further guidance.

**Comment by indigoxela** [comment]
@shruti1421 many thanks for your patience. :pray:

As I see, all changes requested by @klonos are done, the text looks good to me, tests are passing. RTBC from my side :+1:

**Comment by quicksketch** [comment]
Thanks @shruti1421, @indigoxela, and @klonos for creating and reviewing the PR! Thanks @alanmels for making the original issue and suggestion. We ended up implementing pretty much exactly as you suggested.

https://github.com/backdrop/backdrop/pull/3644 has been merged into 1.x and 1.19.x.
