### ISSUE TITLE
Link to b.org backups page when installing

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4431]
**Description of the need**

When installing a module via the UI there is still a link to the d.org backups page.

**Proposed solution**

Link to the b.org version: https://backdropcms.org/backups

I would have thought this issue would exist already. Maybe I just haven't found it yet.

PR: https://github.com/backdrop/backdrop/pull/3161

**Comment by olafgrabienski** [comment]
> I would have thought this issue would exist already.

Oh yes, and we fixed it, see #3556, but that one was about the link on *update* pages.

**Comment by herbdool** [comment]
Ah thanks Olaf. I've reworded the title.

**Comment by herbdool** [comment]
@olafgrabienski pr is available. I get extra points for creating my PR on my phone 😁

**Comment by olafgrabienski** [comment]
Tested in the sandbox site, works for me!

**Comment by indigoxela** [comment]
Pretty straightforward change, RTBC.

**Comment by indigoxela** [comment]
This link is a nice addition that saves some clicks.
Tested with a new custom layout, checked that the link also appears on other layouts without placeholder (like home) and that it doesn't appear where it shouldn't (layouts with placeholder paths)

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3161 into 1.x and 1.16.x. Thanks folks!
