### ISSUE TITLE
When resetting a password have to click twice on the "Save password & Log in" button

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4432]
**Description of the bug**

As shown on the screenshot you have to click twice on the "Save password & Log in" button when resetting a password. 

**Steps To Reproduce**

To reproduce the behavior:
1. Click on a password reset link (sent by putting your e-mail on the `user/password` page).
2. Enter a new password on both `New password` and `Confirm new password` fields and then click on the `"Save password & Log in` button.
3. Unfortunately, you won't be logged in immediately as the first click only expands the `password-confirm-wrapper` to output the `password-match match` span tag. And only when you click on the same button twice you get logged in.

![twice](https://user-images.githubusercontent.com/56604405/83602313-8d3f4000-a52f-11ea-94eb-e44e769d234b.gif)

**Actual behavior**

Not sure which ones of my suggestions the community will accept, so let me just list all of them:

1. Definitely the button should be clicked only once. The solution could be to automatically expand the `password-match` span tag immediately just after the `Confirm new password` field is filled.

2. Sudden expansion of both fields wrappers looks buggy. There is a big difference between what user sees first:

![Screen Shot 2020-06-03 at 12 22 27 AM](https://user-images.githubusercontent.com/56604405/83602714-5289d780-a530-11ea-95ed-057b23c24b40.png)

and the final height of the form s/he ends up with:

![Screen Shot 2020-06-03 at 12 22 43 AM](https://user-images.githubusercontent.com/56604405/83602748-659ca780-a530-11ea-80cf-26b55c6909cf.png)

So would be nice if either (1) fields wrappers were expanded from the very beginning to accommodate the space for expanded confirmation span tags, so we could avoid twitching effect; or (2) some nice place should be devoted for confirmation messages and the height of the form should be constant. 

3. Also you are not sure if you've clicked the button or not yet, because the cursors stays the same all the time. Maybe it's time for everybody to re-visit https://github.com/backdrop/backdrop-issues/issues/2865 and say your opinion.

**Comment by indigoxela** [comment]
@alanmels Which browser were you using? I wasn't able to reproduce (yet). For me the spans expand immediately after typing or pasting something in. And only one click on the button is sufficient to log in.

**Comment by alanmels** [comment]
> @alanmels Which browser were you using? I wasn't able to reproduce (yet). For me the spans expand immediately after typing or pasting something in. And only one click on the button is sufficient to log in.

That's strange. I was testing on Firefox 76.0.1

**Comment by BWPanda** [comment]
I also cannot reproduce. I'm using FF 81.0. Feel free to re-open if you can reproduce this.

**Comment by stpaultim** [comment]
I also tested this in Chrome and was unable to recreate the issue. @alanmels - If this is still an issue, maybe provide more specific information to help recreate.

**Comment by alanmels** [comment]
I've just tested this again with Firefox 81.0.1 (64-bit) and the issue is till there. 

Guys, maybe we are not on the same page. Please generate one time-login (without the `/login` in the end to avoid autologin), so the URL looks like http://docroot/user/reset/1/1601853795/UYj15p4uhfIA2SyfyacO7eYbOdjoy2znBoI3Mli-ZTA. Open it in your browser to see two password fields. Try to fill them in and you will see the form suddenly drags expanding its height and doing nothing else. So you have to click to `Save password and Login` button once again.

**Comment by BWPanda** [comment]
Sorry @alanmels, still can't reproduce this:

![Peek 2020-10-05 10-26](https://user-images.githubusercontent.com/2385329/95029659-6a978080-06f5-11eb-8130-8cd3725284b7.gif)

In the screencast I tabbed between the fields, but I tried again later by clicking in each one, and the same result - the password match thing pops up automatically after enting text, and so only 1 click is needed for the submit button.

**Comment by klonos** [comment]
FTR, although **I never had this issue**, I have [LastPass](https://www.lastpass.com) and the respective Chrome extension installed, and I notice that when my pointer is focused in a password field, my mouse scroll gets "locked". I have to manually tab or click out of the password field before I can scroll again. @alanmels do you happen to have any password managers and respective extensions installed?
