### ISSUE TITLE
"Comments per page" setting cannot be configured to be larger than 300

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4433]
**Description of the bug**

We are working on a Backdrop project that uses comments as not comments per se, but as log entries and each node should have more than 300 entries displayed on the same page. Unfortunately, the 300 comments per page is the hard-coded upper limit as shown on the screenshot:

![Screen Shot 2020-06-03 at 1 41 36 AM](https://user-images.githubusercontent.com/56604405/83608785-941f8000-a53a-11ea-91c9-85f8bb1604df.png)

Naturally, we don't want to deal with this issue every time Backdrop core updates/upgrades, so hopefully we can get this addressed in the core.

**Additional information**

There is a discussion on the subject matter for Drupal on https://www.drupal.org/project/drupal/issues/2239369 first created back on 2014 and last updated in 2017. Hopefully, Backdrop won't follow Drupal's suit to postpone this kind of simple issues for so long.

--
PR https://github.com/backdrop/backdrop/pull/3162 by @indigoxela

**Comment by alanmels** [comment]
I don't see any reasons why we can't raise the limit up to 3000. Most of Backdrop projects will stay with lower caps anyway, however for some projects even 1000 might be to restrictive, so not to spend more time on this, IMO, it's better to increase limit up to really large, but still sane number like 3000.

**Comment by indigoxela** [comment]
I'm not really sure if your request really meets the 80% rule (Backdrop is for the majority).

Have you already considered [hook_form_alter()](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_form_alter/1) for your _very_ special use case?

**Comment by alanmels** [comment]
Ho about D8 feature parity principle? https://git.drupalcode.org/project/drupal/commit/2516dc3 looks like this was fixed on D8, so why we should keep Backdrop fallen behind?

**Comment by indigoxela** [comment]
@alanmels I read your comment as "no, didn't consider nor want to consider hook_form_alter()". :smile: 
```
      '#required' => TRUE,
      '#min' => 10,
      '#max' => 1000,
      '#step' => 10,
```
Note: this still wouldn't meet your needs of 3000.

But a number field with min/max probably makes sense here. Are there any other opinions? Some concerns regarding the max value and possible performance penalties?

**Comment by alanmels** [comment]
> @alanmels I read your comment as "no, didn't consider nor want to consider hook_form_alter()". 

Sorry I made that impression, but believe me: we'll survive if nothing gets changed 😄 So it's just another attempt to improve Backdrop little bit.

Well, if 3000 looks too big number, then let's follow D8's cap and make it at least 1000. Nobody will get hurt, but we will avoid lot's of cases Drupal has had (https://www.drupal.org/project/drupal/issues/2239369).

**Comment by indigoxela** [comment]
Another thought and actually a little off-topic here: Have you considered using views instead?

A views block (based on comments, unlimited length) with a contextual filter on the current node's nid.
Then a customized node.tpl.php which hides comments (supposing you have a custom theme). Then attach the views block to your default layout.

Back to topic: hm... personally I consider even 1000 way to high, but would be happy for additional opinions from other people.

@alanmels 
I'm not convinced that your suggestion of 3000 really makes Backdrop any better.

But a form item of type number instead of the dropdown is a good proposal.

**Comment by alanmels** [comment]
@indigoxela, thanks for the suggestion, and don't worry about our use case as we have our solution. This issue is more about changing the number in the core to prevent some of future Backdrop users from frustration with the limitation.

> I'm not convinced that your suggestion of 3000 really makes Backdrop any better. 

I am not sure about 3K either, maybe it should be just 1K or 500. Whatever number we pick, it's all subjective as any number could seem too little or too big to someone else. What is important here is to realize that 300 is just an arbitrary number that stuck in Drupal and Backdrop inherited it as the upper limitation for the comments. We live in digital age and Backdrop could be potentially used in unimaginable ways and to impose just 300 number seems not right to me.

> But a form item of type number instead of the dropdown is a good proposal.

Even better. Let's not impose any kind of limitations and let users choose their own limits for their Backdrop projects. 

Whatever the outcome will be, I believe there is no any kind of logical justification for the limit to be 300.

**Comment by herbdool** [comment]
I agree with @indigoxela, change it to a number element with a max of 1000. For anyone who wants more they have two ways of achieving that.

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop/backdrop/pull/3162) is available.

A screenshot of the "Comments per page" form item - now a number element:

![screenshot-comment-setting](https://user-images.githubusercontent.com/842066/83963506-ef3cd400-a8a6-11ea-970f-081933978d30.png)

**Comment by indigoxela** [comment]
@alanmels mind to close your PR? I don't have permission to do so.

**Comment by herbdool** [comment]
![Screenshot_20200607-054824__01](https://user-images.githubusercontent.com/1071483/83965589-ad019b80-a882-11ea-905d-8bb858415d35.jpg)

@indigoxela looks like we need fix the JS in the tab to still work.

**Comment by herbdool** [comment]
Looks great!

**Comment by indigoxela** [comment]
@herbdool hehe, you were faster in reviewing than me in posting a comment here. And as I see, the other PR is already closed.

**Comment by alanmels** [comment]
Looks great to me!

**Comment by quicksketch** [comment]
Yay, what a great improvement! The solution seems elegant and more flexible than before. I've merged https://github.com/backdrop/backdrop/pull/3162 into 1.x for 1.17.0.

This could be argued a UX improvement and thus qualify as a bugfix issue. As is I've only merged into 1.x. If you'd like this applied to 1.16.x, please reopen and give it a `milestone candidate - bugfix` tag.

**Comment by alanmels** [comment]
Thanks for everyone! Really good progress. Yes, I would like to tag it as `milestone candidate - bugfix`, but I don't believe I have enough permissions. Could someone else do so or give me permission level, so I could tag issues? Thanks!

**Comment by herbdool** [comment]
Reopening to get it in as a bug fix.

**Comment by quicksketch** [comment]
Great, moving into the 1.16.3 milestone and moving back to RTBC for the cherry-pick.

**Comment by quicksketch** [comment]
I've cherry-picked https://github.com/backdrop/backdrop/pull/3162 into 1.16.x as well now.
