### ISSUE TITLE
Optimize color_css_alter()

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#4434]
**Description of the need**

Currently, color_css_alter() runs several nested foreach loops to check for css files that need to be replaced and calls backdrop_basename() several times inside these loops. This causes a significant amount of overhead when using the color module on otherwise light weight pages.
I profiled the home page on a fresh backdrop install, and with the default files, it loaded in ~0.06 seconds and with a custom color scheme, it took ~0.11 seconds. Because the loops are based on the list of files in the theme, this effect would get worse as the number of files increases.

**Proposed solution**

Rework color_css_alter() to reduce the performance impact of checking files.

**Comment by herbdool** [comment]
Code looks good to me. Seems to me that it has many fewer file checks. I haven't tested impact on performance.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3160 into 1.x and 1.16.x. Thanks @hosef and @herbdool!
