### ISSUE TITLE
Field Settings : Enable Display Field causing errors

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#4450]
I am getting `EntityStorageException` and `PDOException` error reports like this

`EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_audiofile1_display' cannot be null in EntityDatabaseStorageController->save() (line 676 of ............../core/modules/entity/entity.controller.inc).`

They seem to originate from here

![image](https://user-images.githubusercontent.com/10559274/85217707-b8c58580-b38b-11ea-83d9-d43123470b32.png)

This is happening in more than one site.
They are using Backdrop CMS 1.16.2

**Comment by olafgrabienski** [comment]
@Graham-72 I've tried to reproduce the issue. I don't see any message or other issues with the `Enable Display field` setting on a test site, no matter which state at the content type and at single content items. (Setup: file field at the *Post* content type, allowed: `pdf`) Can you provide more detailed steps?

**Comment by Graham-72** [comment]
@olafgrabienski thank you for trying to reproduce this. I also have been unable to do so but I am still getting these reports from existing sites.

One thing I now notice is that the reports always coincide with completion of a cron run.
![image](https://user-images.githubusercontent.com/10559274/85258358-46be7080-b45f-11ea-8a74-221d2f0a55ba.png)

Also, from server logs, there is always a user (web crawler) accessing the site at the time, though no particular URL, i.e. accessing different URLs in each case.

It seems that cron is attempting to update a file record. In this particular case the file is an audiofile of type mp3.

**Comment by indigoxela** [comment]
@Graham-72 Can you post the second Exception, too? The PDOException would also be interesting.

**Comment by Graham-72** [comment]
@indigoxela here it is:
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_audiofile1_display' cannot be null: INSERT INTO {field_data_field_audiofile1} (entity_type, entity_id, revision_id, bundle, delta, language, field_audiofile1_fid, field_audiofile1_display, field_audiofile1_description) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8); Array ( [:db_insert_placeholder_0] => node [:db_insert_placeholder_1] => 615 [:db_insert_placeholder_2] => 3487 [:db_insert_placeholder_3] => book_review [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => und [:db_insert_placeholder_6] => [:db_insert_placeholder_7] => [:db_insert_placeholder_8] => ) in field_sql_storage_field_storage_write() (line 451 of ........../core/modules/field/modules/field_sql_storage/field_sql_storage.module).`

**Comment by indigoxela** [comment]
@Graham-72 

Yes, really helpful.

Expected data according to PDOException:

- entity_type, 
- entity_id, 
- revision_id, 
- bundle, 
- delta, 
- language, 
- field_audiofile1_fid, 
- field_audiofile1_display, 
- field_audiofile1_description

Provided data:

- [:db_insert_placeholder_0] => node 
- [:db_insert_placeholder_1] => 615 
- [:db_insert_placeholder_2] => 3487 
- [:db_insert_placeholder_3] => book_review 
- [:db_insert_placeholder_4] => 0 
- [:db_insert_placeholder_5] => und 
- [:db_insert_placeholder_6] => 
- [:db_insert_placeholder_7] => 
- [:db_insert_placeholder_8] => 

In node 615 there's a file missing (no **fid** for that file). That's why an exception appears.

Can you _view_ that node/615? If you open the form - is there a file?

**Comment by Graham-72** [comment]
@indigoxela many thanks for this.
The file entry has disappeared from the form for node/615 but fortunately the file is still on the server so I can upload it again.

**Comment by indigoxela** [comment]
> The file entry has disappeared from the form

Any idea what might have happened?
Did uploading the file fix all the Exceptions?

You mentioned that this happens on more than one sites - are these errors similar?

**Comment by Graham-72** [comment]
No recurrence of problem so closing issue.
