### ISSUE TITLE
Typos in Layout storage definition

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4454]
**Description of the bug**

This is the comment on the `$storage` property in `layout.class.inc`:

>    The storage state of the layout.
   
>  This is the machine-version of the $type variable, which represents whether
    this view is has a default, user-created, or overridden configuration.
    Possible values for this variable include the constants

This may be copied from Views and needs fixing:
- I dont think there is a `$type` variable
- It should be "this layout" not "this view"
- And "is has" is not grammar.

**Comment by BWPanda** [comment]
Thansk @docwilmot! https://github.com/backdrop/backdrop/pull/3288 has been merged into 1.x and 1.17.x.
