### ISSUE TITLE
Legacy template causing error reports

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#4462]
On a fairly old site, now upgraded to 1.16.2, I was getting the following error report:
`Notice: Undefined index: template in layout_preprocess_layout() (line 307 of ........./httpdocs/backdrop/core/modules/layout/layout.theme.inc).`

It seems that the legacy template does not have a setting `$variables['layout_info']['template']`

To fix this I have added the condition `isset($variables['layout_info']['template'])` to line 307 in `layout.theme.inc` so that the line is now
`if (isset($variables['layout_info']['template']) && ($variables['layout_info']['template'] == 'layout--flexible')) {`

PR at https://github.com/backdrop/backdrop/pull/3180

**Comment by klonos** [comment]
Although I have no way to reproduce the problem, it seems like a straight-forward 1-liner change to me. RTBC 👍

**Comment by quicksketch** [comment]
Thanks @Graham-72 and @klonos! Merged https://github.com/backdrop/backdrop/pull/3180 into 1.x and 1.16.x.
