### ISSUE TITLE
Add our Linux Foundation CII badge

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4464]
I’ve applied for a Linux Foundation Core Infrastructure Initiative (CII) Badge for Backdrop, and we passed! 
This is a security “seal of approval”

I'd like to add this badge to Backdrop's info file, by placing the following into our markdown file:

```
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/4114/badge)](https://bestpractices.coreinfrastructure.org/projects/4114)
```

Here's what it looks like:
<img width="966" alt="Screen Shot 2020-07-02 at 2 26 37 PM" src="https://user-images.githubusercontent.com/397895/86410688-1604e500-bc70-11ea-824a-1adf5361c14b.png">

**Comment by klonos** [comment]
The PR is straight-forward, and the badge seems to be rendering as expected in https://github.com/jenlampton/backdrop/tree/4464-security-badge ...RTBC :+1:

**Comment by quicksketch** [comment]
In general, I'm not sure about these badges provided by 3rd parties. To all but the most tuned-in developers, how much are they providing? I still don't fully understand why we have the badge on the backdrop-issues repository for:

![image](https://user-images.githubusercontent.com/100206/87084513-39391280-c1e3-11ea-9100-b316bab60414.png)

My perspective may be colored by the various browser and platform badges of the 90s: http://www.asmrdating.com/img-badges.html

I do appreciate the value in following the CII recommendations, and I think it's great that we're listed at https://bestpractices.coreinfrastructure.org/en/projects?q=backdrop I'm just not sure about the badge (this and similar ones).

**Comment by quicksketch** [comment]
From the [weekly meeting today](https://www.youtube.com/watch?v=Gl7NMoE7WTg), our approach to this badge (and possibly others in the future) is that we'll put it where the badge seems appropriate and relevant. In the case of this badge, putting it on https://backdropcms.org/security would be a great location, as it's relevant to people interested in security concerns. If we have a page describing automatic updates in the future, it would also be relevant to include the badge there.

We're not setting an official blanket policy on badges at this point, only deciding that we'll need to evaluate each badge individually in the future.

**Comment by BWPanda** [comment]
I think we can close this issue as the badge is now on the Security page:

![image](https://user-images.githubusercontent.com/2385329/104005052-aceec300-51f8-11eb-8d63-7f6a77172143.png)
