### ISSUE TITLE
Color module strange markup in color.theme.inc

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4468]
**Description of the bug**

It doesn't seem to cause any problems, but the closing tag should match the opening tag to get valid markup:

https://github.com/backdrop/backdrop/blob/9994d4d00bc00819450acf911f30624308e8325b/core/modules/color/color.theme.inc#L25

It opens an `<object>` but closes an `<iframe>`
Browsers seem to interpret it as "object", I didn't see any side effects.

What is this supposed to be? Iframe or object?

**Comment by klonos** [comment]
Good catch @indigoxela 👍 ...this seems to have been a CR oversight in https://github.com/backdrop/backdrop/pull/2228/files#diff-854a186b448a82fbcebaf8c1b34cd404R25 (see #3186). Now as to whether it should be an `<object>` or an `iframe`, perhaps @hosef can chime in?

**Comment by hosef** [comment]
Yes, that was an oversight on my part. It was originally an iframe, but I changed it to an object since some browsers were doing weird things with their handling of iframes.

I made a PR that fixes the issue. backdrop/backdrop#3242

**Comment by klonos** [comment]
Thanks @hosef ...RTBC 👍

**Comment by BWPanda** [comment]
Thanks @indigoxela for reporting this, @hosef for the PR and @klonos for testing! I've merged https://github.com/backdrop/backdrop/pull/3242 into 1.x and 1.16.x.
