### ISSUE TITLE
Save old role ids when upgrading from drupal 7

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#4469]
**Description of the need**

I just ported a module which uses role ids (menu_item_visibility). The upgrade path from drupal 7 is right now impossible as rids (role ids) from drupal are missing after user module gets upgraded. Thus, this new module, or any other which use rids, cannot upgrade its table.

**Proposed solution**

Could the upgrade just save the original relation rid-role somewhere in a config file so any module could just pull the data and do its own upgrade?

**Additional information**

There was a little talk about this on zulip with @klonos (https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/menu.20access)

**Comment by docwilmot** [comment]
See https://github.com/backdrop/backdrop-issues/issues/2842#issuecomment-332468932

**Comment by robertgarrigos** [comment]
Thanks @docwilmot I wasn't aware of that issue. Closing this, then.
