### ISSUE TITLE
PHP 7.4 Invalid characters in Color module base conversion functions

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4474]
**Description of the bug**

When changing the color set for Basis theme on a system with PHP 7.4 it gives the error:

```
Deprecated function: Invalid characters passed for attempted conversion, these have been ignored in _color_unpack() (line 875 of /home/in/public_html/core/modules/color/color.module).
```

**Additional information**

This has been fixed for Drupal 7 four month ago: https://www.drupal.org/project/drupal/issues/3084955
Also read https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.invalid-base-characters

**Comment by klonos** [comment]
Thanks @alanmels 👍 ...I've tested on my local with php 7.4.7, first on a vanilla Backdrop installation, and I was able to reproduce the problem. I then pulled your PR on my local, re-built the site and tested again to verify that there are no errors.

I've also reviewed the PR, and it matches the one for D7, so RTBC 👍

**Comment by quicksketch** [comment]
Thanks @alanmels! I've merged https://github.com/backdrop/backdrop/pull/3186 into 1.x and 1.16.x.
