### ISSUE TITLE
Consistency between order of sub-menu items and overview page links

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4477]
**Description of the need**

Ok, that's a really bad issue title. Since a picture's worth a thousand words, try this instead:

![image](https://user-images.githubusercontent.com/2385329/87379368-69adf180-c5d3-11ea-96de-1316845232d2.png)

Notice the discrepancy between the order of the sub-menu items and the links on the overview page? The menu seems to be sorted by a custom weight for each item while the overview page seems to be sorted in alphabetical order.

**Proposed solution**

I recommend sorting the overview page the same as the menu (i.e. by custom weight).

**Other information:**

Backdrop v1.16.2 (if that's important).

**Comment by klonos** [comment]
Agreed. Although this is a task more than a new feature request.

**Comment by BWPanda** [comment]
Duplicate of https://github.com/backdrop/backdrop-issues/issues/4885 (which has more activity).
