### ISSUE TITLE
Allow partial matching in path autocomplete text fields.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4478]
This is a follow-up to #3764

1. Go to `admin/config/system/site-information` (or any place where there's a path autocomplete field really)
2. Try typing "your" in any of the "Default home page" or custom 404/403 path fields -> the "Your first post" content becomes available in the autocomplete suggestions 👍 
3. Try typing "first" in any of the path fields -> the "Your first post" content is NOT available in the autocomplete suggestions 👎

**Comment by klonos** [comment]
Tiny PR up for review: https://github.com/backdrop/backdrop/pull/3188

**Comment by quicksketch** [comment]
I'd be fine merging this as it is today and see what feedback we get from users with the partial, more loose matching.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3188 into 1.x and 1.16.x. Thanks @klonos!
