### ISSUE TITLE
[UX] Link autocomplete: Improve the readability/scannability of suggestions in the dropdown

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4481]
Makes it hard to distinguish the actual options with all the additional info:

![Screen Shot 2020-07-14 at 12 38 25 pm](https://user-images.githubusercontent.com/2423362/87411019-c0b1c780-c5cf-11ea-8193-eba0b13f1b2a.png)

**Comment by klonos** [comment]
...a few options:

- bolded suggestions:

  ![Screen Shot 2020-07-14 at 1 05 31 pm](https://user-images.githubusercontent.com/2423362/87413835-82b6a280-c5d3-11ea-99d4-0ae39ea0b9d6.png)

- grayed-out descriptions:

  ![Screen Shot 2020-07-14 at 1 08 26 pm](https://user-images.githubusercontent.com/2423362/87413778-6d417880-c5d3-11ea-9a13-56099fad7523.png)

- bolded suggestions + grayed-out descriptions:

  ![Screen Shot 2020-07-14 at 1 07 53 pm](https://user-images.githubusercontent.com/2423362/87413805-77fc0d80-c5d3-11ea-9e95-306e0f3bfb60.png)

**Comment by klonos** [comment]
I've filed a PR: https://github.com/backdrop/backdrop/pull/3189

...I went with grayed-out descriptions and also decreased their font size to 80%. Here's what it looks like:

![Screen Shot 2020-07-14 at 1 25 34 pm](https://user-images.githubusercontent.com/2423362/87415834-649e7180-c5d6-11ea-8a4f-80c7d5b54f81.png)

**Comment by stpaultim** [comment]
How widespread is this change? Are there other core autocomplete menus that would be effected by this?

On the surface, this is visually a nice improvement and I support it. I'm just trying to think of unintended sites effects or whether or not we have any conflicting styles choices elsewhere in Backdrop CMS.

**Comment by BWPanda** [comment]
I like the grey and the smaller text, and that it matches machine name styling :+1:

**Comment by klonos** [comment]
Thanks for the feed back all 🙏 ...this is ready for another round of review/testing. I've fixed the contrast of the gray description when the list items in the drop down are being selected and/or hovered-over. Before:

<img width="598" alt="Screen Shot 2020-07-24 at 5 31 24 am" src="https://user-images.githubusercontent.com/2423362/88357277-61904780-cd73-11ea-8462-3d4363e68272.png">

After:
![Screen Shot 2020-07-24 at 5 44 09 am](https://user-images.githubusercontent.com/2423362/88357288-69e88280-cd73-11ea-8ed0-8596b7910408.png)

Also made sure that the suggestion descriptions are properly positioned in RTL. Before:
![Screen Shot 2020-07-24 at 5 53 24 am](https://user-images.githubusercontent.com/2423362/88357314-808ed980-cd73-11ea-8a3c-7c9507ace9b5.png)

After:
![Screen Shot 2020-07-24 at 5 57 50 am](https://user-images.githubusercontent.com/2423362/88357316-85ec2400-cd73-11ea-89eb-3f703276c490.png)

**Comment by BWPanda** [comment]
@klonos I reviewed the code and made some cleanup suggestions.

**Comment by klonos** [comment]
Thanks @BWPanda 👍 ...nice catch with the Views matches description; I was doing some weird variable usage in that `t()` there.

As for the space string concatenations, I've fixed them too, but we do not mention anything about that in https://api.backdropcms.org/php-standards#string-concatenation (nor does the respective documentation in d.org: https://www.drupal.org/docs/develop/standards/coding-standards#concat). We should either allow that, or add something about it in the coding standards documentation 😉

**Comment by BWPanda** [comment]
> As for the space string concatenations, I've fixed them too, but we do not mention anything about that in https://api.backdropcms.org/php-standards#string-concatenation

I'd have thought because it was common sense not to concatenate strings together without some sort of variable in between. Like, we wouldn't do: `'this' . ' is ' . 'some' . ' ' . 'text'`...

Sorry, not having a go at you. I realise it was probably left-over from something being removed at some point. If you think it's worth adding to the standards documentation, we can do that. I just figure it's a fairly basic thing that doesn't need to be specified as such...

THanks for the changes, looks good to me. Just some test failures that I can't see details of because CI's playing up again...

**Comment by klonos** [comment]
No worries @BWPanda 😄 ...I'm not too fussed about it either. This was actually a left-over form when I had the code like this:

```php
$match_description = '<span class="autocomplete-description">(' . t('User account') . ')</span>';
$matches[$path] = $match . ' ' . $match_description;
```

...I then moved the `<span>`s in the `$matches[$path]`, and ended up with this:

```php
$match_description = t('User account');
$matches[$path] = $match . ' ' . '<span class="autocomplete-description">(' . $match_description . ')</span>';
```

All good 👍 

Re test failures, I know 😓 ...ZenCI has been giving me a hard time for some time now. I've restarted them 🤞

**Comment by klonos** [comment]
All tests are finally green 👍

**Comment by BWPanda** [comment]
Nice! RTBC from me.

**Comment by quicksketch** [comment]
Thanks @klonos and @BWPanda for your work on this! I merged https://github.com/backdrop/backdrop/pull/3189 into 1.x and 1.16.x.
