### ISSUE TITLE
'Cache dates' setting description needs re-wording

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4482]
Date fields have a checkbox setting called 'Cache dates' with the following description:

> Date objects can be created and cached as date fields are loaded rather than when they are displayed to improve performance.

To me when reading this, I read 'as' as 'because', which means the sentance doesn't make sense. It took me a while to realise that 'as' means 'when', in which case it does make sense.

Having said that, the sentance is too long and a bit confusing in my opinion, so I believe we could re-word it to avoid future confusion.

Suggestions:

"Date objects can be created and cached when date fields are loaded rather than when they are displayed to improve performance."

"To improve performance, date objects can be created and cached when date fields are loaded (rather than when they are displayed)."

**Comment by klonos** [comment]
Punctuation people ...punctuation! 😅 

I like your last suggestion @BWPanda 👍 :

>To improve performance, date objects can be created and cached when date fields are loaded (rather than when they are displayed).

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/4016

**Comment by olafgrabienski** [comment]
Tested in the sandbox, works for me!

One question for better understanding: at which point are date fields "loaded"?

**Comment by BWPanda** [comment]
Oops, this string is already being updated/fixed in https://github.com/backdrop/backdrop-issues/issues/4249. Closing this issue as a duplicate then.
