### ISSUE TITLE
Consider moving the LICENSE.txt file in the GitHub root

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4485]
We currently have it under `/core`, which makes it not show up in the sidebar summary on GitHub. Here's what it looks like on other projects, where this file is in the top level:

![Screen Shot 2020-07-16 at 6 28 53 pm](https://user-images.githubusercontent.com/2423362/87690546-441b1680-c792-11ea-877a-e046162b107a.png)

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/3205

**Comment by quicksketch** [comment]
I think this is a good idea to make it so GitHub aggregates Backdrop with other GPL software.

**Comment by quicksketch** [comment]
We can should delete this sentence from the `README.md` file if we move the license:
```
See the LICENSE.txt file in the core directory for complete text.
```

No need to keep that if the LICENSE.txt is in the root.

**Comment by klonos** [comment]
Good catch @quicksketch 👍  ...done: [`240fc71` (#3205)](https://github.com/backdrop/backdrop/pull/3205/commits/240fc71201b8466fb99307b83ca0993035ab91c3)

Taking the liberty to put this back to RTBC.

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop/backdrop/pull/3205 into 1.x and 1.16.x!
