### ISSUE TITLE
Page title of /user/register is not translated

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4493]
**Description of the bug**

The page title of /user/register is not translated / translatable because the string is not wrapped in t().

**Steps To Reproduce**

1. Enable user registration
2. Add a language, import translations
3. Visit /XX/user/register, where XX is the langcode of your additional language

**Actual behavior**

The original string shows up although the string has a translation.

![screenshot-untranslated-title](https://user-images.githubusercontent.com/842066/88180954-6d262600-cc2e-11ea-81cf-8b66d0e3c9cd.png)

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3196) is available.

Without any other changes the same page looks like that after applying.

![screenshot-translated](https://user-images.githubusercontent.com/842066/88181604-69df6a00-cc2f-11ea-9f34-9001771ff0e4.png)

Additionally the meta title also is correct afterwards. German in my case, so "Neues Benutzerkonto erstellen".

**Comment by jenlampton** [comment]
Code looks good. Tested in the sandbox, working for me :)
http://3196.backdrop.backdrop.qa.backdropcms.org/fr/user/register?aon

**Comment by quicksketch** [comment]
Thanks @indigoxela and @jenlampton! Merged https://github.com/backdrop/backdrop/pull/3196 into 1.x and 1.16.x.
