### ISSUE TITLE
Remove obsolete region support from themes.

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#450]
When the theme registry is built, it initializes defaults for theme .info files. Apparently this still contains a default set of regions in `_system_rebuild_theme_data()`:

```
'regions' => array(
  'sidebar_first' => 'Left sidebar',
  'sidebar_second' => 'Right sidebar',
  'content' => 'Content',
  'header' => 'Header',
  'footer' => 'Footer',
  'highlighted' => 'Highlighted',
  'page_top' => 'Page top',
  'page_bottom' => 'Page bottom',
),
```

We should just remove this 'regions' array, since themes no longer provide regions now that Layout module controls all regions (from #86).

**Comment by jenlampton** [comment]
Opened a new PR over here: https://github.com/backdrop/backdrop/pull/646

**Comment by quicksketch** [comment]
Closed the PR at https://github.com/backdrop/backdrop/pull/646 until tests can be fixed. Really close here!

**Comment by quicksketch** [comment]
Fixed the tests in a new PR: https://github.com/backdrop/backdrop/issues/1421

Because this affects maintenance-page.tpl.php files, I'm marking this for 1.5.0. This will require an API change notice.

**Comment by quicksketch** [comment]
Finally merged https://github.com/backdrop/backdrop/pull/1421. I'll work on getting up a change record.

**Comment by quicksketch** [comment]
Change record posted: https://api.backdropcms.org/node/44499
