### ISSUE TITLE
[UX] Automatically clear caches when making changes to the "Who can register accounts?" setting.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4500]
**Steps To Reproduce**

1. On a vanilla Backdrop site, go to `admin/config/people/settings`
2. Change the "Who can register accounts?" setting from the default "Administrators only" option to any of the other 2 options, and save.
3. In another browser, or in an incognito window, visit `user/login/password` -> only the "Log in" and the "Reset password" tabs are shown - the "Create new account" tab is not shown 👎 
4. Clear caches
5. Refresh the page in the incognito window -> the "Create new account" tab is shown
6. Back in `admin/config/people/settings`, change the setting back to "Administrators only" and save.
7. In the incognito browser tab, refresh the page -> the "Create new account" tab is still shown 👎 ...you can actually even switch to it, and try to register an account (but you'll get "Access denied" when you submit the form)
8. Clear caches.
9. In the incognito browser tab, refresh the page -> if you where in the "Create new account" tab, you get "access denied" ...if you were in any of the other 2 tabs, you see the "Create new account" tab gone 👍 
10. Back in `admin/config/people/settings`, change the "Who can register accounts?" setting to any of the 2 "Visitors" options and save.
11. Clear caches.
12. In the incognito window, switch to `user/register`.
13. Back in `admin/config/people/settings`, disable the "Require email verification..." setting and save.
14. In the incognito window, while in `user/register`, refresh the page -> no password field shown 👎 
15. Try to register an account -> you get a "Password field is required." error, and the required password field is now shown 👎 

**Expected behavior**

Changes should become effective immediately, without requiring manual cache clearing.

**Recommended solution**

Add a `backdrop_cache_clear_all()` to the submit handler for this form.

**Comment by bharathk005** [comment]
@klonos do you mean browser cookies? 
Steps 4,8,11 what do you mean by Clear caches?

**Comment by klonos** [comment]
Hello @bharathk005 Backdrop uses the same caching mechanics as Drupal. You can clear caches via the admin UI if you:
- use the admin menu: Home → Flash all caches:
  ![image](https://user-images.githubusercontent.com/2423362/121690470-8ea23180-cace-11eb-8170-8e3979142fa3.png)
- navigate to Configuration → Development → Performance and click the "CLEAR ALL CACHES" button: 
  ![image](https://user-images.githubusercontent.com/2423362/121690417-7cc08e80-cace-11eb-9b5d-6fff625c5679.png)

Programatically, you can clear caches using the [`cache_clear_all()`](https://docs.backdropcms.org/api/backdrop/1/search/cache_clear_all) function, or selectively using the [`cache_flush()`](https://docs.backdropcms.org/api/backdrop/1/search/cache_flush) function.

**Comment by klonos** [comment]
...were you asking out if curiosity @bharathk005, or were you planning to work on this issue?

**Comment by bugfolder** [comment]
@klonos's recommended fix does indeed fix the issue. PR submitted.

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼 

...one would think that `backdrop_flush_all_caches()` should be clearing all caches, as the function name suggests, but it seems that that is not the case with token caches. That must be most likely because in D7 the Token module was a separate thing, and we either must have missed to integrate `token_cache_clear()` into `backdrop_flush_all_caches()` when we merged the token functionality in Backdrop core, or we must have had valid reasons not to.

Anyway, my point is that the already existing `token_cache_clear()` in `user_admin_settings_submit()` has a reason to remain there.

Code LGTM 👍🏼 ...but the PR did not trigger any PR sandbox so that I could test to confirm. @bugfolder do you want to try closing the PR, then waiting for a couple of mins, then reopening? Thanks.

**Comment by bugfolder** [comment]
Restarted sandbox, tests pass.

**Comment by klonos** [comment]
Thanks @bugfolder ...tested and now things work as expected of course :) 👍🏼

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3648 into 1.x and 1.19.x. Thanks folks!
