### ISSUE TITLE
Module list is strangely ordered, sort by Package name alphabetically

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4503]
**Description of the bug**

When viewing the module list, the order is hard to understand.

**Steps To Reproduce**

To reproduce the behavior:
1. Install a variety of modules and go to the **admin/modules** page. 

**Actual behavior**

The packages are the main grouping, but don't have anything to do with the order. For example, a report in Ubercart queue: https://github.com/backdrop-contrib/ubercart/issues/225

It's not actually random, but it's just sorting on the module names rather than considering the packages they are in.

**Expected behavior**

Ordering by package and then module name seems wise.

----------

PR by @laryn: https://github.com/backdrop/backdrop/pull/3201

**Comment by klonos** [comment]
Thanks @laryn straight-forward one-liner, and it works as advertised. RTBC 👍

**Comment by quicksketch** [comment]
Thanks @laryn and @klonos! I merged https://github.com/backdrop/backdrop/pull/3201 into 1.x and 1.16.x.

It's arguable that passing in the `NATURAL_SORT` flag might result in better sorting, but I think the presence of numbers in the package names is pretty unusual.

**Comment by docwilmot** [comment]
Should this be closed?
