### ISSUE TITLE
Fixed: Remove mention of global theme settings from docblock on `theme_get_setting()`.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#451]
#130  removed the concept of global theme settings. Code comments on theme_get_setting() function needs to be updated to reflect this.

**Comment by BWPanda** [comment]
How's this? https://github.com/backdrop/backdrop/pull/3348

**Comment by indigoxela** [comment]
Looks good.

Normally I'd request a rebase, but as this is a docblock-only change, which means, there's nothing to test, I'm fine with the PR as-is. RTBC :+1: 

(311 commits behind backdrop:1.x. - new record? :grinning: )

**Comment by quicksketch** [comment]
Thanks @BWPanda, @indigoxela, and @docwilmot! Wow, a 7 year old issue! Such a simple fix, and one less issue open. :smile:
