### ISSUE TITLE
Broken views_handler_relationship_translation.inc because of table column name

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4513]
**Description of the bug**

While trying to test an unrelated issue I came across a complex problem in views relationship handler: some tables have "langcode" column, some have "language", the query always assumes "language".

https://github.com/backdrop/backdrop/blob/12aafa88ad37d773d92e9a32f71d739323481416/core/modules/translation/views/views_handler_relationship_translation.inc#L67

**Steps To Reproduce**

Just as example:

1. Enable translation module with dependencies
2. Enable node translation on a node type
3. Create a view with a relationship on content translations, use anything except "all languages", for instance "current language"

**Actual behavior**

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node_node.language' in 'on clause'`

**Expected behavior**

Correct query returning some values, not throwing an exception.

**Additional information**

This could get tricky. The column is "langcode" for node, comment and taxonomy_term_data, the column is "language" for users.
The field columns are also "language", for instance in field_data_body (does Backdrop use field language?).

How can this get solved? Any views gurus around?

**Comment by indigoxela** [comment]
Wait, maybe it isn't tricky at all to fix this.

Class views_handler_relationship_translation ships with the translation module. It extends the base class views_handler_relationship.

This only applies (my assumption!) to stuff that's *translatable*.

So, what's translatable in Backdrop:

- node
- taxonomy term
- menu item
- config (if marked as translatable)

The latter has no database table, so we can ignore it in this case, as we're dealing with db queries here.

Node, term and menu item - all have the column "langcode" in their database tables.
So the solution could be to simply change all three "language" to "langcode" in function query(). That should fix all possible queries.

Concerns so far or did I miss anything?

**Comment by indigoxela** [comment]
Based on my findings (see previous comment) I've created a [PR](https://github.com/backdrop/backdrop/pull/3212).

To test it follow the steps in the Issue description.

**Comment by herbdool** [comment]
I say we merge this PR. And make a new issue for changing the column name for users and fields. Get it all standardized before i18n is released. Currently I assume we can't translate users now fields (no entity translation module) so hopefully no contrib relies on those column names.

**Comment by indigoxela** [comment]
> And make a new issue for changing the column name for users and fields.

I don't think the change is necessary for users table, as the "language" column there is for *user's default language* and has nothing to do with translation.

Regarding fields this could get tricky. It would be a bigger task for core alone, but might be a contrib-breaker. Personally, I don't fully understand the language handling re fields.

**Comment by herbdool** [comment]
I see: regarding users.

AFAIK the language column on fields is just there for entity translation? Which hasn't been ported yet. Anyway, it can be handled in a new issue if need be.

**Comment by herbdool** [comment]
Looks good to me! (I've already tested my exact duplicate PR so this one should also work the same.) 😉

**Comment by quicksketch** [comment]
Looks great! Thanks @indigoxela for both filing the issue and figuring it out! Thanks @herbdool for the review. Merged https://github.com/backdrop/backdrop/pull/3212 into 1.x and 1.17.x.
