### ISSUE TITLE
Views link to node translation not showing

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4514]
**Description of the bug**

The "Translate link" in views never shows because of a mistake in an if clause.

**Steps To Reproduce**

To reproduce the behavior:
1. Enable Content Translation module, add another language
2. Enable multilingual support for node types, "Enabled, with translation"
3. Add some nodes and translate
4. Create a node view
5. In that view add a views field `Content translation: Translate link` (Provide a simple link to translate the node.)

**Actual behavior**

That link never shows, always empty values.

**Expected behavior**

A link with url to the nodes "Translate" tab shows.

**Additional information**

Easy one-liner fix here:

https://github.com/backdrop/backdrop/blob/12aafa88ad37d773d92e9a32f71d739323481416/core/modules/translation/views/views_handler_field_node_link_translate.inc#L18

**Comment by stpaultim** [comment]
I need to learn more about Backdrop CMS content translation features. 

In steps to reproduce, I assume that "enable node translation" means "enable Content Translation module"

**Comment by indigoxela** [comment]
@stpaultim I've updated the issue description to provide more details regarding the steps. Does this help?

**Comment by klonos** [comment]
@indigoxela the code change is simple and it makes links show, but I have found the following issues:

1. With a single language enabled, the "Translate link" label is shown w/o any link. I know that in such cases the "Hide if empty" setting for the field would solve things - just wondering if we should be throwing an error when this field has been added to a view when there is only a single language (+ a link to the language listing page, where they can add more languages). This can be a follow-up - just adding it here as a note.

2. When clicking the "translate" link for nodes that have their language set to `none`, you get a 404 "access denied". Should we not be rendering the translation links in that case?

**Comment by indigoxela** [comment]
@klonos I will have a look.

**Comment by indigoxela** [comment]
So I played with your findings:

1. Set up everything as in Issue description, then _disabled_ all except for one language.

Result: link still available in the view, leading to the translate tab (still accessible), but there nothing is available to translate - only one language.
Correct to my understanding. (I wasn't able to produce a text-only entry.)

2. Set up everything as in Issue description, then create a page in "language neutral".

Result: link still shows, but leading to a 403 access denied page.
So confirmed, there is a problem with mixed stuff - a content type has translation enabled but language is not required and that node has no language set.

I'd like to dig a bit, if it's possible to catch it without an extra filter, not sure yet.

**Comment by indigoxela** [comment]
Regarding the failing tests, which seem totally unrelated: I already noticed some trouble when pushing my latest commit (ran in a timeout at first). Looks like Github is in (perfomance) trouble again. Worth restarting the sandbox?

**Comment by indigoxela** [comment]
@klonos I restarted the sandbox (all tests passing as expected). Are you ready for another review?

**Comment by stpaultim** [comment]
@indigoxela - Thanks. Your added instructions helped. I'm a little embarrassed that I've never played with these features before. The translations are pretty cool. 

I would say that the PR fixes the problem that it intends to fix. 

We have a problem right now where a field is not doing what it is supposed to in views. This PR fixes that fundamental problem. If we have other ideas on how to make it work better, I recommend follow-up issues, since there are ways to work around these other issues in views.

**Comment by indigoxela** [comment]
@klonos friendly reminder to review the latest changes in this [PR](https://github.com/backdrop/backdrop/pull/3208)

And this issue still needs a milestone set.

**Comment by herbdool** [comment]
Looks good to go.

**Comment by quicksketch** [comment]
Great find @indigoxela! Thanks for the collaboration folks on all these recent translation issues. I've merged https://github.com/backdrop/backdrop/pull/3208 into 1.x and 1.18.x.
