### ISSUE TITLE
Wrong langcode data on admin/config/regional/translate if default language is not English

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4517]
**Description of the bug**

If the default language of a site is not English, locale's table shows wrong data.

**Steps To Reproduce**

To reproduce the behavior:

1. Install a site in a different language or enable an additional language and set that to the site's **default language**
2. Go to admin/config/regional/translate

**Actual behavior**

A typical WTF moment:

![locale-table-wrong-colum-data](https://user-images.githubusercontent.com/842066/89265181-6509b580-d634-11ea-8f9d-0652986dcd5c.png)

The table hides the default language in column "Languages" and shows English as "untranslated" - which is totally wrong.
Instead of a strikethrough "EN" there should have been "DE" and it should show as translated (translation exists).

**Proposed solution**

- Fix the weird logic in function _locale_translate_language_list()

**Compared to Drupal:**

- D7 does not show these problems. (The code is pretty different compared to Backdrop)
- D8 has a totally different translation system.

**Comment by olafgrabienski** [comment]
> If the default language of a site is not English, locale's table shows wrong data.

Thanks for bringing this issue up! I'm able to reproduce it, bothers me quite often on localized sites.

**Comment by olafgrabienski** [comment]
> That leads to the basic logic problem in Backdrop's translation handling.
>
> Source lang for t() is *always* English and it's impossible to translate something *to* English.

Not sure about this one. I guess, "translate to English" is meant as "override English strings by using the translation interface", e.g. change "Log in" to "Sign in". (Interesting information about translating English in Drupal 8: http://hojtsy.hu/blog/2013-aug-20/drupal-8-multilingual-tidbits-12-english-can-now-be-translated.)

**Comment by indigoxela** [comment]
Can anyone out there explain how `translate_english` could _ever_ work in Backdrop?

If not, we should completely remove this config item. (It was inherited from early Drupal 8.)

**Comment by olafgrabienski** [comment]
> Can anyone out there explain how translate_english could ever work in Backdrop?

I was curious and have just tried it on a multilingual site, and it basically works. Steps to reproduce:

- Go to `admin/config/regional/language/edit/en`, and check "Enable interface translation to English".
- Go to `admin/config/regional/translate/translate`, and translate the string "Log in" for English to "Sign in".
- Visit `user/login` or `en/user/login` as a guest (check if you're on an English page).

Result: Page title and name of the active tab are "Sign in", as expected.

**Comment by indigoxela** [comment]
Wow! Never realized that. In this case we should, of course, keep that setting. But we should make the UI less confusing.

**Comment by olafgrabienski** [comment]
> In this case we should, of course, keep that setting. But we should make the UI less confusing.

Yes, that's a good idea! The setting however doesn't seem to related to the actual issue (locale's table shows wrong data). Mind to move the "Additional information" from the issue description to a separate issue?

**Comment by indigoxela** [comment]
I've created a new [Issue regarding](https://github.com/backdrop/backdrop-issues/issues/4520) the confusing UI and updated the Issue description here.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3211) is available.

It basically reverts the small wrong part of the otherwise correct changes in a [previous commit](https://github.com/backdrop/backdrop/commit/80527bf03c7216fc564195044933eb309d5cf087).

**How to test:**

- Enable additional language(s)
- Set default language to something not "en"
- visit admin/config/regional/translate
- check the langcodes shown in column "Languages"

Additionally:

- check it with default language English
- check it with the "Enable interface translation to English" setting (admin/config/regional/language/edit/en)

**Comment by herbdool** [comment]
I think this PR is ready. I didn't find any regressions when testing. I'm not entirely sure why the previous commit was not totally working - perhaps it was not entirely done. Anyway, works for now.

**Comment by BWPanda** [comment]
I tried testing this as per https://github.com/backdrop/backdrop-issues/issues/4517#issuecomment-669756880 but I got the same ~~crossed out~~ results before and after applying the patch... I don't use translation/multiple languages at all, so I'm probably not the best person to test/review this.

Can someone else confirm this works as expected? Maybe post before and after screenshots?

**Comment by olafgrabienski** [comment]
> I got the same ~~crossed out~~ results before and after applying the patch

@BWPanda Not sure if you're aware: Crossed out results per se aren't the issue but results showing the wrong language code.

Without the PR the list on `admin/config/regional/translate/translate` displays the English language code for the translation status of a non-English default language (see screenshot in issue description).

With the PR (tested in the sandbox), it shows the language code of the non-English default langauge, e.g. `nl` for Dutch, as expected:

![screen-backdrop-3211-translation-interface](https://user-images.githubusercontent.com/14188307/90871137-e2eef000-e39a-11ea-8c00-a836cb76acd2.png)
