### ISSUE TITLE
Rename theme_html_tag to theme_head_tag and limit it's use.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#452]
As a follow up from https://github.com/backdrop/backdrop-issues/issues/298, I don't believe we'll have the time to properly dive in and kill theme_html_tag in backdrop 1.x, but I would like to remove the WTF moment that happens when front end devs find this function.

Let's limit it's use to only tags that are output in the HTML head, and name it accordingly.

**Comment by jenlampton** [comment]
Okay, changing the name to theme_head_tag might solve all those problems.

**Comment by quicksketch** [comment]
> Okay, changing the name to theme_head_tag() might solve all those problems.

+1
