### ISSUE TITLE
Standardise on the spelling of 'email' across Backdrop

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4521]
The word 'email' can be (and is) spelt differently in Backdrop. One example is on the login and password reset forms:

![image](https://user-images.githubusercontent.com/2385329/89615208-6bfd2600-d8c9-11ea-8c72-1743f3ee0749.png)

![image](https://user-images.githubusercontent.com/2385329/89615225-761f2480-d8c9-11ea-8179-1102e74ba2f6.png)

Here are the number of ways 'email' is spelt in Backdrop core (case-sensitive):

- Email (47)
- E-mail (28)
- E-Mail (2)
- email (484)
- e-mail (190)

I think we should standardise on Email/email (they seem to be the most popular ones.

**Comment by klonos** [comment]
Deja vu: #1056

@quicksketch 
> I'd prefer to follow Drupal on this one and use "email" as well. I used "e-mail" in Webform module for years and always regretted it in my heart of hearts. Adding the hyphen is indeed harder to type, which can make selecting a field more difficult from a select list. HTML5 uses `<input type="email" />`; the resulting inconsistency between label and markup can be grating for me.
>
>The New York Times dropped the hyphen: http://www.thewire.com/national/2013/10/tweet-and-email-are-now-fit-print/70864/
As did the AP: http://www.huffingtonpost.com/2011/03/18/ap-removes-hyphen-from-em_n_837833.html
>
>I read that the SF Chronicle still uses "e-mail", but my Google search results of their site seems to indicate otherwise, and "email" seems dominate there as well.

...

>With #476 going in to add "Email" module this pretty well seals the deal here in favor of hyphen-less "email". Although I'd love to replace every occurrence wholesale, I think we should only change the occurrence that are code comments or non-translated strings, to avoid having translations broken.

**Comment by BWPanda** [comment]
Hmm, guess I only looked for open issues before opening this new one. Missed that. Don't know why it was closed though... And I personally don't agree with keeping core un-standardised just for the sake of translations. I think that sets a bad precedent...

**Comment by klonos** [comment]
>And I personally don't agree with keeping core un-standardised just for the sake of translations.

I'm of the same mind 👍

**Comment by olafgrabienski** [comment]
> don't agree with keeping core un-standardised just for the sake of translations

Well, I wouldn't say "just" translations ... However, as a translator I wouldn't even translate "e-mail" and "email" in different ways to German. So, I guess many translators already *have* standardised the strings themselves, so that there shouldn't be much risk of losing translations.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3576

**Comment by BWPanda** [comment]
And just to solidify the reasoning of choosing 'email' spelling over 'e-mail':

![image](https://user-images.githubusercontent.com/2385329/174295751-e0ab5e37-b4e3-43ec-b071-45b2a25d3c6c.png)
(source: https://trends.google.com/trends/explore?date=all&q=email,e-mail)

**Comment by argiepiano** [comment]
Left a small comment. Otherwise LGTM

**Comment by BWPanda** [comment]
Thanks @argiepiano! I made a new commit that fixed some grammar (`a email`) and also includes the changes from [@alanmels' PR](https://github.com/backdrop/backdrop/pull/4093) which was attached to a duplicate issue.

**Comment by argiepiano** [comment]
Thanks, @BWPanda. I found a couple of "user name" - made another comment to the commit. Most of the instances are "username" or "Username", so I think it'd be a good idea to match that.

**Comment by BWPanda** [comment]
Hmm, I'm not sure... That seems like 'scope-creep' territory to me. Perhaps open another issue where we can address that. There may be other places in core that need updating too...

**Comment by argiepiano** [comment]
OK, sounds good. RTBC

**Comment by quicksketch** [comment]
Looks good to me too. This has a fair amount of impact on existing strings. Perhaps this should be a 1.23.0 item?

**Comment by argiepiano** [comment]
>  Perhaps this should be a 1.23.0 item?

Yes, that's probably best. It was marked as milestone bug rather than milestone minor, so I chose 1.21.1, but I can change to 1.23.0

**Comment by BWPanda** [comment]
Happy for this to go into a minor release :+1:
