### ISSUE TITLE
Do not capitalize the word "Date" in the default date formats

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4522]
I'm annoyed by the fact that the word "Date" is being capitalized in the labels of the existing OOTB date formats; can we fix those (for new sites only - in `system.date.json`)?

![Screen Shot 2020-08-07 at 9 47 19 pm](https://user-images.githubusercontent.com/2423362/89678360-b2697980-d8f7-11ea-99c7-4ae050a4442c.png)

**Comment by Nimisha94** [comment]
Hi! I'm working on this issue as a part of GHC Open Source Day. @klonos It is mentioned that this needs to be fixed for new sites only. Does that mean there need not be an update in `system.install` for this?

**Comment by jenlampton** [comment]
Yes, that's right!

**Comment by klonos** [comment]
> Does that mean there need not be an update in `system.install` for this?

Correct 👍

**Comment by klonos** [comment]
I've just tested this in the PR sandbox, and it looks as expected (letter d in "date" in all date format names is lower-case) 👍

**Comment by klonos** [comment]
...I've also reviewed the code. It seems like a simple and straight-forward change. So this is RTBC 👍 

Thanks @Nimisha94 for working on this 🙏

**Comment by BWPanda** [comment]
The PR changes the case of names of date formats that are hidden (which I think is good, we should be consistent), however there are some other hidden formats that could use a name case change (e.g. `HTML Time -> HTML time`, `HTML Week -> HTML week`, etc.).

Marking as needs work so we can fix all the formats at once.

**Comment by stpaultim** [comment]
Good catch. 

@Nimisha94 - Do you think you will still be able to work on this one?

![Issue__4522__Change_the_word__Date__in_the_OOTB_date_formats_to_lowercase_by_Nimisha94_·_Pull_Request__3329_·_backdrop_backdrop](https://user-images.githubusercontent.com/3144571/94885213-4017a000-0435-11eb-82d6-9bbdca60ef7a.png)

**Comment by Nimisha94** [comment]
Yes, thanks for pointing it out @BWPanda @stpaultim 
Will fix it and update the PR.

**Comment by klonos** [comment]
Sorry for late responce here @Nimisha94 

Thanks for updating the PR 🙏 ...I've reviewed the changes and they look OK. This is RTBC 👍

**Comment by BWPanda** [comment]
Thanks! Merged into 1.x and 1.17.x.
