### ISSUE TITLE
[UX] Tab index: Password toggle should come after password field

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4524]
This is a follow-up to #3048

Before that change, you could do this:

1. Focus the username field (won't be needed after #4183 😉 )
2. Type your username.
3. Press tab -> the password field gets focus
4. Type your password
5. Press enter -> log in

After #3048 was merged, you need to tab twice after step 2:

1. Focus the username field
2. Type your username.
3. Press tab -> the "show password" link gets focus
4. Press tab again -> the password field gets focus
5. Type your password
6. Press enter -> log in

**Comment by klonos** [comment]
...I'm thinking that this may need to be a wider change 🤔 ...do we in general (not specifically to the log in form) want the tab index for the show/hide toggle to have priority over the actual password text field, or should we have it so that the toggle always comes after the password field?

**Comment by klonos** [comment]
Simple one-line PR up for review: https://github.com/backdrop/backdrop/pull/3220

Before:

```html
<div class="form-item form-type-password form-item-pass">
  <label for="edit-pass">Password
    <abbr class="form-required" title="This field is required.">*</abbr>
  </label>
  <span class="password-toggle-wrapper password-hidden">
    <a href="#" class="password-toggle">Show password</a>
    <input data-password-toggle="..." type="password" id="edit-pass" name="pass" size="60" maxlength="128" class="form-text required password-toggle-processed" autocomplete="off" style="...">
  </span>
</div>
```

After (visually, CSS-wise nothing changes):

```html
<div class="form-item form-type-password form-item-pass">
  <label for="edit-pass">Password
    <abbr class="form-required" title="This field is required.">*</abbr>
  </label>
  <span class="password-toggle-wrapper password-hidden">
    <input data-password-toggle="..." type="password" id="edit-pass" name="pass" size="60" maxlength="128" class="form-text required password-toggle-processed" autocomplete="off" style="...">
    <a href="#" class="password-toggle">Show password</a>
  </span>
</div>
```

**Comment by BWPanda** [comment]
> should we have it so that the toggle always comes after the password field?

Yes, I believe so.

The PR works nicely and is beautifully simple :-) RTBC from me.

**Comment by BWPanda** [comment]
I added the `milestone candidate - bug` label as this fixes a slight UX regression introduced by the other linked issue.

**Comment by quicksketch** [comment]
This sounds great! I frequently accidentally focus "Show password" when tabbing between the username and password field. This allows for the quick series of keystrokes: `Enter username, [Tab], Enter password, [Enter]` as you would expect, instead of needing to tab twice between username and password.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3220 into 1.x and 1.16.x. Thanks @klonos and @BWPanda!
