### ISSUE TITLE
Comment Body field duplicated on reply page

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop/backdrop-issues#4528]
Was experiencing this problem on a new site, and have replicated the issue on a new local installation running Backdrop 1.16.2 and PHP 7.2.2.

The Comment Body field is duplicated on the comment reply page. On the normal node page with comments at the bottom, the field is printed once. However it's when you press the reply button and get taken to the reply page is when the  Comment Body field is duplicated.

**Comment by indigoxela** [comment]
Hey, right, I can confirm that. It only occurs on comment reply and it seems to be independent from the theme in use.

It seems to happen with the call to field_attach_load() inside function comment_reply().

https://github.com/backdrop/backdrop/blob/ff56f8a394c521bdbad36a7f2c4d03a0707d4819/core/modules/comment/comment.pages.inc#L66

At least, that's the point where the comment_body field item value gets duplicated, as comment_body is already a property of the previously created comment object.

**Comment by stpaultim** [comment]
@sbgraphicdesign - Thanks for opening an issue. I am pretty sure that I've seen this issue before and thought there was an existing github issue, but I looked last night and could not find one.

**Comment by indigoxela** [comment]
I belief that the line `field_attach_load('comment', array($comment->cid => $comment));` is redundant, as `comment_load($pid);` already took care of loading attached fields - see protected function attachLoad() (entity module, file entity.controller.inc).

**Comment by indigoxela** [comment]
I also tested with an additional text field (comments are fieldable entities). Same problem, all attached fields get duplicated on the comment reply page.

Screenshot:

![screenshot-dup-fields](https://user-images.githubusercontent.com/842066/89773679-ae5e7700-db04-11ea-86cc-076e3f1ca9f6.png)

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3228) is available for testing and review.

Note: an automated test has been added, too. (Oops, I just saw my typo in the commit message... :disappointed: )

**Comment by klonos** [comment]
This is RTBC @indigoxela. Thanks 👍 ...there's a php5 test failure though. Can you please restart the tests, to make sure that this is random.

**Comment by indigoxela** [comment]
@klonos all tests passing in a fresh sandbox.

**Comment by BWPanda** [comment]
Do we know why that line isn't needed for Backdrop? Drupal has the same code - do they have the same issue, or has something changed in Backdrop to cause this?

Just like to know more about this before removing a line of code... :slightly_smiling_face:

**Comment by indigoxela** [comment]
What has changed in Backdrop is that the entity module has been incorporated.

see [protected function attachLoad()](https://github.com/backdrop/backdrop/blob/3eaf60b4d1fe88d5c32dfbbb913f079d843208fe/core/modules/entity/entity.controller.inc#L447)

Some lines above the (now removed) field_attach_load() there's already `$comment = comment_load($pid);`.
That loads the full entity with fields already attached. So the call to field_attach_load() adds them a second time.

If in doubt: get a current dev version of Backdrop and apply the test alone - it fails.

**Comment by BWPanda** [comment]
Thanks for reporting this issue @sbgraphicdesign! Thanks also to @indigoxela for the PR and @klonos for testing. Merged https://github.com/backdrop/backdrop/pull/3228 into 1.x and 1.16.x.
