### ISSUE TITLE
Reference to deprecated file_create_htaccess() function

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4530]
The docblock for [`file_htaccess_lines()`](https://api.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_htaccess_lines/1) references the deprecated [`file_create_htaccess()`](https://api.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/function/file_create_htaccess/1) function. It should reference [`file_save_htaccess()`](https://api.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_save_htaccess/1) instead.

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3235

**Comment by indigoxela** [comment]
Yep, nice catch. Let's not confuse developers...

**Comment by BWPanda** [comment]
Thanks @indigoxela, merged https://github.com/backdrop/backdrop/pull/3235 into 1.x and 1.16.x.
