### ISSUE TITLE
Deprecated function: assert() in php 7.2

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4531]
**Description of the bug**

When doing a config sync on php 7.2, I see the following error repeated:
```
Deprecated function: assert(): Calling assert() with a string argument is deprecated in HWLDFWordAccumulator->addWords() (line 885 of backdrop/core/includes/diff.inc).
```

**Additional information**

Related: https://github.com/backdrop/backdrop-issues/issues/3403

---
PR: https://github.com/backdrop/backdrop/pull/3236

**Comment by hosef** [comment]
There is an updated version of that class in PhpWiki 1.5.5 with that line fixed.
https://sourceforge.net/p/phpwiki/code/HEAD/tree/branches/release-1.5.5/lib/diff.php#l59

**Comment by jenlampton** [comment]
Thanks @hosef that was extremely helpful :) I've filed a PR that replaces the `addWords()` method with the newer version, and I don't get notices on config sync anymore :)

**Comment by hosef** [comment]
Do you think that it might be a good idea to update the whole file since the version of PhpWiki it is based on is quite old now? It's possible that might cause breakages in our config file diffs though.

**Comment by hosef** [comment]
Actually, it looks like the config file diffs are broken anyway.

**Comment by indigoxela** [comment]
Too many tests are failing - this PR needs more work.

**Comment by herbdool** [comment]
probably better to update the whole file, but I'm seeing if tests will pass by fixing Jen's PR.

**Comment by jenlampton** [comment]
Tests pass now with @herbdool's fix. Testing now on a new site...

**Comment by jenlampton** [comment]
Still works to resolve the PHP warning :)

**Comment by herbdool** [comment]
I've tested current PR with tests - still getting lots of:

> Calling assert() with a string argument is deprecated

**Comment by indigoxela** [comment]
I think this issue is a duplicate of https://github.com/backdrop/backdrop-issues/issues/4777

Or maybe it's the other way round... :wink: 

Anyway, the other PR seems to have a more complete fix.

**Comment by jenlampton** [comment]
Thank you @indigoxela that PR is working much better for me. Going to close this issue in favor of that one.
