### ISSUE TITLE
Undefined variable in ConfigFileStorage::initializeStorage()

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4532]
**Description of the bug**

The [`ConfigFileStorage::initializeStorage()`](https://api.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/ConfigFileStorage%3A%3AinitializeStorage/1) has an undefined variable: `$config_directory`.

**Steps To Reproduce**

To reproduce the behavior setup a new Backdrop site with the `$config_directories` variables in `settings.php` set to something ridiculous (like `'../../../../../../../../../config/active'`, i.e. this directory isn't possible on my filesystem). Now try installing Backdrop.

**Actual behavior**

Error:

> Notice: Undefined variable: config_directory in ConfigFileStorage->initializeStorage() (line 1252 of /app/backdrop/core/includes/config.inc).

**Expected behavior**

Just the exception:

> The directory '../../../../../../../../../config/active' could not be created or could not be made writable.

**Comment by BWPanda** [comment]
PR to fix this: https://github.com/backdrop/backdrop/pull/3237

**Comment by indigoxela** [comment]
Brilliant! Yes, that variable isn't defined.

This is how I tested:

- Downloaded the branch
- Created a directory `testconfig` outside webroot, owned by root (no write permission for the apache user).
- Set that directory as base for `$config_directories` in settings.php
- Started the install process
- Got "The directory ../testconfig/active could not be created or could not be made writable. ..."
- Did a chown to the apache user on the testconfig dir
- Reloaded the install page
- The install happily proceeded and Backdrop was installed successfully

**Comment by klonos** [comment]
Code looks good too 👍 Thanks @BWPanda 🙏

**Comment by jlfranklin** [comment]
Looks good.  Can you add a test?

**Comment by BWPanda** [comment]
@jlfranklin A test for what?

**Comment by jlfranklin** [comment]
A test that checks the exception triggers when the directory is missing/unwritable and includes the name of the directory as intended.

**Comment by BWPanda** [comment]
@jlfranklin Ok, I see what you mean. However I think that's outside the scope of this issue. THis issue is purely about fixing a variable that's undefined. It has nothing to do with whether or not that exception is triggered or not. In fact, that exception was still triggered when I was testing this above. It's just the the undefined variable error was being displayed as well, and more prominently.

If you feel a test is needed, I'd suggest opening a seperate issue for that.

**Comment by jlfranklin** [comment]
You found a bug.  Write a test that covers it so it doesn't happen again.  It may be there is already a test looking for the exception and all it needs to do is also look for "the name of the directory as intended."

**Comment by indigoxela** [comment]
> It may be there is already a test looking for the exception

There isn't and is could be tricky to create one, as this happens before Backdrop is even installed.

But if you can provide a functioning test, we'd be happy.
