### ISSUE TITLE
Documentation for path_save_automatic_entity_alias() wrong

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4537]
The documentation for [`path_save_automatic_entity_alias()`](https://api.backdropcms.org/api/backdrop/core%21modules%21path%21path.inc/function/path_save_automatic_entity_alias/1) is wrong:

> Update the URL aliases for an individual taxonomy term.

This function is not specific to taxonomy terms, but is generic and applies to all entities.

**Comment by indigoxela** [comment]
That's a tiny change and it's correct. The function is all about _entities_, only the comment mentions taxonomy term.

**Comment by BWPanda** [comment]
Thanks for reviewing @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/3253 into 1.x and 1.16.x.
