### ISSUE TITLE
[DX] Wrong description for user_add_role_action()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4538]
https://api.backdropcms.org/api/backdrop/1/search/user_add_role_action

The description says:

User $account: The user entity whose account will be blocked.

**Comment by BWPanda** [comment]
Basically all docblocks in that file were just copied/pasted and needed updating: https://github.com/backdrop/backdrop/pull/3244

**Comment by klonos** [comment]
I've left a couple of suggestions in the PR; although my English is not 100%, so feel free to shoot them down.

**Comment by BWPanda** [comment]
Thanks @klonos, PR updated.

**Comment by BWPanda** [comment]
Thanks for finding and reporting this @klonos! Merged https://github.com/backdrop/backdrop/pull/3244 into 1.x and 1.16.x.
