### ISSUE TITLE
Combine jquery.once.js into backdrop.js

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#454]
In Drupal 7, the jQuery "once" library (http://plugins.jquery.com/once/) was added to avoid a common pattern in Drupal 6 of using "guard" classes. It basically automated the process.

Drupal 6:
```js
$('.my-selector-class:not(.my-behavior-processed)').each(function() {
  $(this).addClass('my-behavior-processed');
  // Bind events, etc.
});
```

Drupal 7:
```js
$('.my-selector-class').once('my-behavior').each(function() {
  // Bind events, etc.
});
```

The jQuery Once library is now required by nearly every JS file in Backdrop core. It's a miniscule library: less than .7kb compressed and added on every page of the site. I'd like to recommend that we merge this library into backdrop.js directly for a few reasons:

- This code is extremely stable and basically unchanged for the last 5 years.
- The `.once` method is not widely used outside of the Drupal/Backdrop ecosystem. It was actually written specifically for Drupal in the first place.
- This gets our out-of-box JS down to simply two files: jquery.js and backdrop.js and eliminates an HTTP request.

**Comment by serundeputy** [comment]
travis testing: https://github.com/backdrop/backdrop/pull/725

**Comment by klonos** [comment]
> Interested in what other people might think.

I am basically against these sort of things (merging code in a single file). Especially since people can use server-side solutions for minification and merging in order to reduce HTTP requests (google SPDY for example has an apache module and is include in nginx for some time now).

If we do end up doing this though...

> This code is extremely stable and basically unchanged for the last 5 years

...we are using v1.2 (when latest 1.x is the [1.2.6](https://github.com/RobLoach/jquery-once/releases/tag/1.2.6)) and 2.0.0 was released a couple of weeks ago: https://github.com/RobLoach/jquery-once/releases

**Comment by quicksketch** [comment]
> I am basically against these sort of things (merging code in a single file). Especially since people can use server-side solutions for minification and merging in order to reduce HTTP requests (google SPDY for example has an apache module and is include in nginx for some time now).

Yeah, I agree here. There are lots of server-side solutions available (including our own JS aggregation). On SPDY, I don't think any commonly available services use SPDY (Pantheon, Acquia, any shared host, etc). Considering our target audience, I don't think we should consider web-server level solutions unless they're the widely available default (like our use of .htaccess).

I'm not sure this is a good idea either, but it seemed an opportunity to boost end-user experience in a small way with a small determent to developer experience. I think we need some more feedback before this is either closed, with or without a merge.

**Comment by quicksketch** [comment]
But thanks @serundeputy for getting a PR ready. ;)

**Comment by serundeputy** [comment]
@quicksketch no worries; fewer http requests++

**Comment by klonos** [comment]
In the meantime, while we await more feedback, we should update to 2.0.0. Filed #687

**Comment by quicksketch** [comment]
Let's close this issue. It was a crazy idea that in hindsight doesn't seem like a very good idea.
