### ISSUE TITLE
[DX] Add inline comment to explain why the ellipsis in truncate_utf8() is wrapped in t()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4545]
https://github.com/backdrop/backdrop/blob/1.x/core/includes/unicode.inc#L338

```php
  if ($add_ellipsis) {
    // Truncate ellipsis in case $max_length is small.
    $ellipsis = backdrop_substr(t('…'), 0, $max_length);
    $max_length -= backdrop_strlen($ellipsis);
    $max_length = max($max_length, 0);
  }
```

Full story behind that here: https://www.drupal.org/project/drupal/issues/86461#comment-2829792

> According to the [Wikipedia article](http://en.wikipedia.org/wiki/Ellipsis), ellipses are used in many languages, including Chinese, though in that case, it is usually represented as 6 dots arranged vertically. It seems to me that the purpose of the `$dots` parameter is to "indicate an intentional omission," and that any logic about how (and whether) to represent it ought to be handled at the translation layer, since it's language specific.
>
>While `truncate_utf8()` just adds `' ...'`, perhaps it should add `t('&hellip;')`, `t('&#8230;')`, or something similar instead. I don't know if passing HMTL entities or numeric character references is valid in `t()`, but you get the point. A translator with the appropriate knowledge could then provide the proper character(s) for his or her language.
>
>Either way, I don't think it's something specific to truncating paths, and perhaps ought to be addressed in how `truncate_utf8()` handles it.

**Comment by klonos** [comment]
I've filed a PR that adds this:

>The ellipsis character is wrapped in t(), since intentional omissions may be indicated using different character(s) in different languages.

Happy to tweak as needed.

**Comment by indigoxela** [comment]
```
    // Truncate ellipsis in case $max_length is small. The ellipsis character is
    // wrapped in t(), since intentional omissions may be indicated using
    // different character(s) in different languages.
```
I do understand why the ellipsis needs to be translated. What I do not understand is the explanation. :laughing: 

"...intentional omissions may be indicated using..." huh, what? I had to read that several times. Bear in mind that it should be understandable by non-native speakers. Isn't there a simpler way to phrase that?

**Comment by docwilmot** [comment]
> "...intentional omissions may be indicated using..." huh, what? I had to read that several times. Bear in mind that it should be understandable by non-native speakers. Isn't there a simpler way to phrase that?

Ditto.
Why not just say "The ellipsis character is wrapped in t(), since a different string of characters or symbols may be used for this purpose in other languages."

**Comment by klonos** [comment]
I'm open to improving the wording. Let's get more eyes on this, so that we get a few more alternatives before we decide.

Pinging @jenlampton and @stpaultim, but also some non-native English speakers like @olafgrabienski and @VasasA.

As a non-native English speaker myself, what I found confusing/hard when I started learning was lengthy sentences, without any punctuation (that's why I tend to over-punctuate). Another way to help with long sentences is to try to break them down to several smaller ones. So here's my wordier alternative:

> In many languages, the ellipsis character is used to indicate intentional omissions. In some other languages though, a different set of characters or symbols may be used instead for the same purpose. For this reason, the ellipsis is wrapped in t() here.

**Comment by jenlampton** [comment]
I like the wordier language :)

**Comment by olafgrabienski** [comment]
> In many languages, the ellipsis character is used to indicate **intentional omissions**. (...)

Hm, "intentional omissions" without further context sounds strange to me. Even if a bit wordier, here are two alternatives, inspired by Wikipedia and the Cambridge Dictionary:

> In many languages, the ellipsis character is used to indicate **intentional omissions of a word, sentence, or whole section from a text**. (...)
> In many languages, the ellipsis character is used to indicate **one or more words that have been intentionally left out**. (...)

**Comment by docwilmot** [comment]
We dont need to be defining what an ellipsis is for here, just explain why we translate it. the intentional commissions business is unnecessary.

**Comment by indigoxela** [comment]
How about: "The ellipsis character is wrapped in t(), since different characters or symbols may be used for this purpose in other languages."

That's a simplified version of @docwilmot's suggestion.

**Comment by VasasA** [comment]
Is it too long?:
"The ellipsis character is wrapped in t(), since different characters or symbols may be used for this purpose in other languages. For example the ellipsis character is used to indicate one or more words that have been intentionally left out."

**Comment by BWPanda** [comment]
I like @indigoxela's and/or @docwilmot's simple versions. We don't need an essay here, and I agree that we don't need to explain what ellipsis' are used for.

@klonos Can we please get an updated/rebased PR?

**Comment by klonos** [comment]
Thanks for digging up this old low-hanging fruit @BWPanda 🙏🏼

> I like @indigoxela's and/or @docwilmot's simple versions. We don't need an essay here, and I agree that we don't need to explain what ellipsis' are used for.

I also like those variants, and I agree on the points you and others have made re length and definition of elipsis.

...I've updated the PR and rebased it too. Ready of a final review 😉 (pending on tests to run, but the change is on an inline comment anyway, and I have made sure to not exceed the 80 characters limit)

**Comment by BWPanda** [comment]
All tests passing, changes look good to me, so RTBC!

**Comment by quicksketch** [comment]
Thanks folks! Great explanation! I merged https://github.com/backdrop/backdrop/pull/3249 into 1.x and 1.24.x.
