### ISSUE TITLE
Odd text in the $break_points array in text_summary()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4546]
@BWPanda brought this up in Zulip:

> What is going on with the text at the end of this line?https://github.com/backdrop/backdrop/blob/1.x/core/modules/field/modules/text/text.module#L415

```php
  // If the first paragraph is too long, split at the end of a sentence.
  $break_points[] = array('. ' => 1, '! ' => 1, '? ' => 1, '。' => 0, '؟ ' => 1);
```

@klonos
>Good catch @BWPanda ...seems like the result of a search/replace or something like that. ...it's about line breaks. ...the equivalent line in D7 is exactly the same: https://git.drupalcode.org/project/drupal/-/blob/7.x/modules/field/modules/text/text.module#L420
>...same thing in D8: https://git.drupalcode.org/project/drupal/-/blob/8.9.x/core/modules/text/text.module#L134 (and assuming in D9)

@BWPanda
> It's weird though, because if I move my cursor through the line left-to-right, it jumps around towards the end...

![Peek-2020-08-16-21-56](https://user-images.githubusercontent.com/2423362/90334408-1fef6700-dfd6-11ea-83c2-4e78ea3aebb5.gif)

@klonos
>Yeah, I noticed that too ...seems like some odd tab character or something.
>...reminds me of the same odd thing that's happening when you try to select text split in <span>s in RTL languages.
>...there you go, that character is the Arabic question mark: https://en.wiktionary.org/wiki/؟

@BWPanda
>Ok, so that character is making that section of text be displayed RTL...

@klonos
>...not sure how it works TBH ...that array element declaration seems wrong to me.

**Comment by klonos** [comment]
The latest patch in https://www.drupal.org/project/drupal/issues/1482178#comment-10811866 shows that an earlier version of that line was:

```php
// If the first paragraph is too long, split at the end of a sentence.
$break_points[] = array('. ' => 1, '! ' => 1, '? ' => 1, 'ã€‚' => 0, 'ØŸ ' => 1);
```

🤷

**Comment by BWPanda** [comment]
I don't know much about RTL languages/characters or unicode, etc., but I suspect this isn't a bug...

It seems to me that it should be written like this: `'。' => 0, '? ' => 1);` (but I changed the character to a normal question mark to avoid displaying it wrong). As soon as the renderer (GitHub, my text editor, etc.) reads the backwards question mark, it displays it and the following text in reverse (RTL).

**Comment by klonos** [comment]
>It seems to me that it should be written like this: ...

Hmm 🤔 ...then we'd end up with this:

```php
$break_points[] = array('. ' => 1, '! ' => 1, '? ' => 1, '。' => 0, '? ' => 1);
```

...which repeats `'? ' => 1` twice.

**Comment by klonos** [comment]
>...but I changed the character to a normal question mark to avoid displaying it wrong

Oh, I see. This is very weird 😅  ...so I try to paste the Arabic question mark (`؟`) in here, and then continue typing `' => 1);` after it. ...see what happens when I reach the number `1` and be amazed!!

```php
$break_points[] = array('. ' => 1, '! ' => 1, '? ' => 1, '。' => 0, '؟' => );
```

![odd-behavior-with-arabic-question-mark](https://user-images.githubusercontent.com/2423362/90334905-8d50c700-dfd9-11ea-94b8-ebbb06ba76a1.gif)

...I'm typing `1` and then delete it using backspace ^^

**Comment by klonos** [comment]
...it happens when typing any digit actually 😅

**Comment by klonos** [comment]
...I thought that we could change those `1`s and `0`s to `TRUE`/`FALSE` instead, but these aren't booleans - they are offsets 🤔 

This could work:

```php
$arabic_questionmark_offset = 1;
$break_points[] = array('. ' => 1, '! ' => 1, '? ' => 1, '。' => 0, '؟ ' => $arabic_questionmark_offset);
```

...but I'm laughing even at the idea of starting to add an inline comment as to why we are doing that 🤣

**Comment by klonos** [comment]
...we could point people to this issue here, so that they can see the screen captures.

**Comment by klonos** [comment]
Filed a PR here: https://github.com/backdrop/backdrop/pull/3250 ...lets see if it breaks anything.

**Comment by klonos** [comment]
...this may be a non-issue actually @BWPanda ...or an "aesthetics"/display issue from a DX point of view I guess. Try running this:

```php
$break_points = array('. ' => 1, '! ' => 1, '? ' => 1, '。' => 0, '؟ ' => 1);
dpm($break_points);

$arabic_questionmark_offset = 1;
$fixed_break_points = array('. ' => 1, '! ' => 1, '? ' => 1, '。' => 0, '؟ ' => $arabic_questionmark_offset);
dpm($fixed_break_points);

dpm(array_diff($break_points, $fixed_break_points));
```

![image](https://user-images.githubusercontent.com/2423362/90336908-9183e100-dfe7-11ea-9b17-38877ee58576.png)

**Comment by BWPanda** [comment]
Yeah, I think all we should do is add a comment explaining that the text might look weird, but its actually correct. See this issue for details.

Don't think we need to change the code itself.

**Comment by klonos** [comment]
> Don't think we need to change the code itself.

👍 ...PR updated to only include an inline comment.

**Comment by BWPanda** [comment]
One little comment on PR, otherwise looks good!

**Comment by klonos** [comment]
Done 👍

**Comment by BWPanda** [comment]
Great, thanks!

Wonder if I'm allowed to commit a simple change like this now, or should we wait for another core committer...?

**Comment by klonos** [comment]
No worries. I'll bring it to @quicksketch's attention during our next dev meeting (unless this mention does that before then, or if @herbdool happens to see this too 😉 )

**Comment by BWPanda** [comment]
It's a simple change, only a comment, so I think fine to commit now. Merged https://github.com/backdrop/backdrop/pull/3250 into 1.x. Thanks @klonos!
