### ISSUE TITLE
Better alignment of 'Add new field' row on 'Manage fields' page

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4547]
The 'Add new field' row on the 'Manage fields' page is currently not aligned very well. The proposed PR fixes this as shown:

**Before:**
![before1](https://user-images.githubusercontent.com/2385329/96545703-9ec59080-12f4-11eb-9887-006a0e0a66e6.png)

**After:**
![after1](https://user-images.githubusercontent.com/2385329/96545719-a5540800-12f4-11eb-9279-fc206b917f66.png)

And also when the drag handle sits above the label:

**Before:**
![before2](https://user-images.githubusercontent.com/2385329/96545764-ba309b80-12f4-11eb-98e7-e80f10d0b5b4.png)

**After:**
![after2](https://user-images.githubusercontent.com/2385329/96545774-bf8de600-12f4-11eb-98c5-308a9dc5d3f0.png)

---

**Original post**

Here's how that row currently looks normally:
![image](https://user-images.githubusercontent.com/2385329/90347958-df93f580-e076-11ea-906f-d58806e0ef41.png)

And here's how it looks if the cells are wider and the draggable handle sit above the field:
![image](https://user-images.githubusercontent.com/2385329/90347983-04886880-e077-11ea-9949-0506ee7e4bca.png)

**Comment by BWPanda** [comment]
I suggest removing the `vertical-align: top;` css from that row, and then hiding the blank placeholder above the machine name part.

Here's how it'd look then:
![image](https://user-images.githubusercontent.com/2385329/90348041-4e714e80-e077-11ea-9ae2-deb665c4e6b0.png)

And with wider cells:
![image](https://user-images.githubusercontent.com/2385329/90348059-6a74f000-e077-11ea-887a-280aff8f1a63.png)

**Comment by BWPanda** [comment]
Here are the images overlaid on each other, to better see the differences:
![add_new_field_1](https://user-images.githubusercontent.com/2385329/90348217-4ebe1980-e078-11ea-9e68-5706cccea96d.jpg)

![add_new_field_2](https://user-images.githubusercontent.com/2385329/90348218-51207380-e078-11ea-923c-a15e3163210a.jpg)

I think this results in better alignment overall.

**Comment by klonos** [comment]
I would like to test how things would work with `vertical-align: middle;` (including the drag handle).

**Comment by BWPanda** [comment]
This is how things work with `vertical-align: middle;`. That's what it falls back to when you remove `vertical-align: top;` (as per the PR). I can try centering the drag handle too, but everything should already be centred now.

**Comment by klonos** [comment]
> That's what it falls back to when you remove `vertical-align: top;`

**Comment by klonos** [comment]
Pinging @jenlampton

**Comment by BWPanda** [comment]
@klonos How does that look when the machine name is visible? I.e. start typing a label...

**Comment by klonos** [comment]
You're right @BWPanda ...not good 😓 ...but we are adding a "placeholder" above the type/widget fields, for what it seems to be spacing purposes:

![image](https://user-images.githubusercontent.com/2423362/90569592-d3af4d00-e1b6-11ea-97c5-49e9b20d0cf5.png)

...perhaps we could do the same with the machine name, only place the placeholder at the bottom? 🤷

**Comment by klonos** [comment]
>...perhaps we could do the same with the machine name, only place the placeholder at the bottom?

...and then it "works":

![image](https://user-images.githubusercontent.com/2423362/90569927-6d76fa00-e1b7-11ea-85a6-65fe46619a69.png)

**Comment by BWPanda** [comment]
I've updated the PR. I couldn't change the empty placeholder from `#prefix` to `#suffix` as that apparently just doesn't work (it was still displayed above the machine name). So I used CSS instead to set that cell to be `vertical-align: middle;`.

Here's how it looks now:

![image](https://user-images.githubusercontent.com/2385329/90587527-f5431f80-e21c-11ea-9687-00887339b859.png)

![image](https://user-images.githubusercontent.com/2385329/90587560-0724c280-e21d-11ea-903f-56e6ad1d31f4.png)

The machine name in the second screenshot is a bit high... In this case adding the placeholder above it pushes it back down nicely, but then the machine name in the first screenshot would be too low...

I think this is currently better than the current situation though.

**Comment by stpaultim** [comment]
@BWPanda - I'm a little confused, because the boxes all seem to line up nicely in your screenshot. This is what I'm seeing in the current sandbox. 

![Post___PR_3251_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/91010423-18b4f400-e5a8-11ea-876f-011b9d92564a.png)

I think it's ok if the machine name isn't centered perfectly, but if we are going to improve this, shouldn't we at least get these boxes to line up?

**Comment by BWPanda** [comment]
@stpaultim The sandbox site wasn't refreshed after the latest commit. I'm doing so now, then you should be able to see the latest changes.

**Comment by stpaultim** [comment]
Got it. Yes, this is a big improvement. I'm going to mark this "Works for Me" - because it is a big improvement, even if the machine name could be vertically aligned better. I know you tried to do that and I don't have an idea on how to make it better.

**Comment by klonos** [comment]
I have been playing with this on my local, and it turns out that placing the drag handlers in a dedicated column works much better (the "Add new field" textfield/label doesn't wrap bellow it that way). I'm testing how the machine name alignment works with and w/o it being in edit mode ...that _is_ a bit tricky. ...I'll file a PR against yours when (if?) I get it to behave @BWPanda.

**Comment by BWPanda** [comment]
> I'll file a PR against yours when (if?) I get it to behave

Sure. I think the drag handle in a seperate column should be a seperate issue though, as I'm sure there are many more places in core whaere that should be updated too for consistency...

**Comment by BWPanda** [comment]
I've updated the original post with updated screenshots to better get an idea of the current suggestion.

**Comment by quicksketch** [comment]
I don't see any problems with the implementation. With @stpaultim and @klonos having reviewed this functionality on the front-end, this seems ready. I've merged https://github.com/backdrop/backdrop/pull/3251 into 1.x and 1.17.x. Thanks folks!
