### ISSUE TITLE
Remove check for 'php_code' filter

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4548]
Since we removed the PHP Filter module from core, we should remove the check for that filter from [`text_summary()`](https://api.backdropcms.org/api/backdrop/core%21modules%21field%21modules%21text%21text.module/function/text_summary/1):

```php
// We check for the presence of the PHP evaluator filter in the current
// format. If the body contains PHP code, we do not split it up to prevent
// parse errors.
if (isset($format->filters['php_code']) && $format->filters['php_code']->status && strpos($text, '<?') !== FALSE) {
  return $text;
}
```

**Comment by indigoxela** [comment]
And we should also replace it in the [api example](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.api.php/function/hook_filter_info_alter/1).

@BWPanda do you think that should be an extra Issue?

**Comment by BWPanda** [comment]
Hmm, probably can be included here, but needs replacing with another example then...

**Comment by indigoxela** [comment]
> Hmm, probably can be included here, but needs replacing with another example then...

@BWPanda how did you decide? Code would be RTBC otherwise.

Maybe something like:

```
  // Replace the image caption process callback with an improved custom version.
  $info['filter_image_caption']['process callback'] = 'my_module_custom_caption';`
```

**Comment by indigoxela** [comment]
@BWPanda I doubt that you need a full month of thinking this over :smile: You probably missed my suggestion.

**Comment by BWPanda** [comment]
@indigoxela Sorry. I like your suggestions. PR updated.

**Comment by indigoxela** [comment]
The code looks good. Nothing to test here, so RTBC.

**Comment by BWPanda** [comment]
With @klonos giving the thumbs-up in the PR, I'm happy that enough people (3) have seen and OK'd this to merge it now.

**Comment by BWPanda** [comment]
Thanks for the help @indigoxela & @klonos. Merged https://github.com/backdrop/backdrop/pull/3252 into 1.x and 1.17.x.
