### ISSUE TITLE
[UX] Admin Bar drop-downs go off-screen

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4549]
**Description of the bug**

When a drop-down menu from the Admin Bar is too close to the right edge of the screen, it goes off the edge:

![Peek 2020-08-17 16-59](https://user-images.githubusercontent.com/2385329/90382634-5bfff600-e0c2-11ea-84ca-58b14d5a2a7e.gif)

**Steps To Reproduce**

To reproduce the behavior:
1. Shrink the window until the Reports menu item is as close to the right side of the window as possible
2. Hover over it, then a sub-menu item with children (e.g. Available Updates)

**Actual behavior**

The Available Updates sub-menu goes off the edge of the screen.

**Expected behavior**

The sub-menu should be dynamically repositioned to appear fully on-screen.

**Comment by klonos** [comment]
Related: #2809

https://www.smartmenus.org/docs/#keepInViewport

> **keepInViewport**
> Type: Boolean
> Default value: `true`
> Determines whether the sub menus should be repositioned if needed to make sure they always appear inside the viewport.

**Comment by BWPanda** [comment]
Here's a PR that seems to work! https://github.com/backdrop/backdrop/pull/4017

![Peek 2022-03-24 23-07](https://user-images.githubusercontent.com/2385329/159913245-865a55da-5b9e-485b-8105-5f4423763c03.gif)

**Comment by quicksketch** [comment]
Seems good to pull into the next milestone.

**Comment by jenlampton** [comment]
I've tested the sandbox and this is a great improvement. Code looks great too, RTBC  from me!

**Comment by klonos** [comment]
Amazing work @BWPanda at resolving this long-standing issue 👏🏼 🙏🏼 🎉

**Comment by klonos** [comment]
...one thing that we should fix is this case where the "flipped" child menu overlaps with the grant-parent men:

<img width="977" alt="image" src="https://user-images.githubusercontent.com/2423362/160042483-e2488a04-3701-4e64-a742-6224a708f894.png">

Since this is a huge improvement over the current problematic UX, this can be a follow-up issue.

**Comment by BWPanda** [comment]
@klonos Yep, that's a problem. I'm not sure what the fix would be though...

But yes, let's fix 95% of issues by merging this PR, then open a new issue to fix the remaining bugs like that one.

**Comment by laryn** [comment]
Thanks @BWPanda for filing and fixing this UX issue! Also thanks to @jenlampton, @klonos, @yorkshire-pudding, and @quicksketch for the testing, code review, and feedback.
Merged into `1.x` and `1.21.x`.
