### ISSUE TITLE
[WP] Use native browser-level lazy-loading for images by default

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4550]
There seem to be a [few ways to implement lazy image loading](https://web.dev/lazy-loading-images/), but native browser-level lazy-loading seems to be extremely easy: https://web.dev/native-lazy-loading

> In Chrome 76 onwards, you can use the `loading` attribute to lazy-load images without the need to write custom lazy-loading code or use a separate JavaScript library. ...
>
>## Browser compatibility
> `<img loading=lazy>` is supported by most popular Chromium-powered browsers (Chrome, Edge, Opera) and [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75#HTML). The implementation for WebKit (Safari) is [in progress](https://bugs.webkit.org/show_bug.cgi?id=200764). [caniuse.com](https://caniuse.com/#feat=loading-lazy-attr) has detailed information on cross-browser support. Browsers that do not support the loading attribute simply ignore it without side-effects.

Currently, caniuse.com currently reports ~73% global support, and the freshly-released [WordPress v5.5 supports that feature too](https://wordpress.org/news/2020/08/eckstine):

> ## Speed
>Posts and pages feel faster, thanks to lazy-loaded images.
>
>Images give your story a lot of impact, but they can sometimes make your site seem slow.
>
>In WordPress 5.5, images wait to load until they’re just about to scroll into view. The technical term is ‘lazy loading.’
>
>On mobile, lazy loading can also keep browsers from loading files meant for other devices. That can save your readers money on data — and help preserve battery life.

Could we simply add `loading="lazy"` to `theme_image()` and win?

**Comment by olafgrabienski** [comment]
Isn't this issue a duplicate of https://github.com/backdrop/backdrop-issues/issues/3659?

**Comment by klonos** [comment]
Thanks @olafgrabienski ...second time within a week that this is happening to me 😓 ...where did the duplicate issue suggestions feature that GitHub used to have go? 🤔
