### ISSUE TITLE
[UX] Better help text for layout path field

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4555]
**Description of the need**

I just spend a long time trying to figure out the correct path to create a custom layout for taxonomy terms. 
https://forum.backdropcms.org/forum/how-do-i-configure-custom-layout-taxonomy-term-page

In retrospect, it shouldn't have been that difficult. I think that the 3 most common layouts of this type would node/%, taxonomy/term/%, and user/%. Why not include all three of these examples in the help text?

Not even sure that is the right path for user, wouldn't it be nice if there was a clue in the UI. :-)

**Proposed solution**

Change the following:
OLD: "Use the "%" (percent) symbol to indicate a wildcard in the path. i.e. "node/%" or "node/%/edit"."
NEW"Use the "%" (percent) symbol to indicate a wildcard in the path. i.e. "node/%", "taxonomy/term/%", "user/%", "node/%/edit", etc.

**Alternatives that have been considered**

1. Better documentation for this in the user manual. 

**Additional information**

![Add_layout___Backdrop_CMS_Live](https://user-images.githubusercontent.com/3144571/90673335-376c6100-e21d-11ea-8aba-f207488cbb8f.png)

---

PR: https://github.com/backdrop/backdrop/pull/3274

**Comment by klonos** [comment]
Related: #1602 #2411 #2618

**Comment by klonos** [comment]
...would be nice to add an example for comments too.

**Comment by albanycomputers** [comment]
Can you have multiple conditions or just one condition.. i.e.  "/node/$, /node/%/edit"  or is it only possible to have one "/node/%"

**Comment by klonos** [comment]
You can have multiple _visibility_ conditions @albanycomputers ...but these are not conditions, these are contexts/paths. You may be interested to follow #3750, which would allow adding custom contexts to layouts...

Before:

![image](https://user-images.githubusercontent.com/2423362/90785709-4fbaa980-e30b-11ea-8b6f-ea8a68b1b21d.png)

...and after (notice the "+ Add context" link):

![image](https://user-images.githubusercontent.com/2423362/90785763-66f99700-e30b-11ea-8077-da852eaf0369.png)

The goal is to ship that feature with the upcoming 1.17.0 release of Backdrop, on September 15 😉

**Comment by jenlampton** [comment]
I also want to add that we are using the wrong word. A `Wildcard` is an asterisk `*`, and we use that language for asterisks in other places. What we mean here is `Placeholder` since we want people to enter a percent `%`.

I'd like to fix that while we're changing the text.

**Comment by jenlampton** [comment]
I've pushed a PR that fixes the wildcard/placeholder terminology problem, and adds all core examples to the description text for the Path field:

<img width="1135" alt="Screen Shot 2020-08-29 at 5 18 26 PM" src="https://user-images.githubusercontent.com/397895/91648387-bcc0f400-ea1b-11ea-8b13-c2a0a5ffe5ac.png">

**Comment by stpaultim** [comment]
This works for me. I'm going to let at least one more person look at this before marking it "works for me."

**Comment by klonos** [comment]
This also works for me, and the help text improvements are great 👍 ...I've left 2 nit-picking comments in the PR, but feel free to ignore them. I don't want to be dragging this for too long, as @stpaultim said, there's better things coming with #2618 that will make all this obsolete.

**Comment by jenlampton** [comment]
@klonos I've merged your PR to my PR, but would prefer to leave the &nbsp; over the CSS changes if this is all going to be replaced soonish anyway :)

**Comment by stpaultim** [comment]
OK, @klonos does that make this RTBC?

**Comment by klonos** [comment]
After all the recent activity and merged changes, the PR now has conflicts that need to be fixed + failing tests. Happy to review again when these are addressed.

**Comment by jenlampton** [comment]
Rebased and pushed a new PR.

**Comment by klonos** [comment]
@jenlampton there are 3 failures related to `layout.test` and messages + it seem to that the PR sandbox is broken dues to #4611 😓

**Comment by indigoxela** [comment]
Some related tests are currently failing. I suppose, some text should get updated to fix them.

Back to "needs work".

(I'm a bit unhappy with the html tags inside translatable text, but don't want to start the same discussion again.)

**Comment by jenlampton** [comment]
> I'm a bit unhappy with the html tags inside translatable text

At first I thought that what is in the tags here didn't need to be translated, so I tried to to concatenate it instead... But then I realized that this would be a problem with Japanese or other LTR languages since they would need it at the beginning of the string instead of the end. So I put it back.

> Some related tests are currently failing

It looks like i had some unrelated code changes in here, removed, and now tests are passing again :)

**Comment by stpaultim** [comment]
These little changes really make Backdrop CMS a much better tool to use. Thanks. I just looked again at this PR and it looks good.

**Comment by klonos** [comment]
Code looks good 👍 ...thanks @jenlampton 🙏 

PS: ZenCI is acting up again, so can you please close/re-open the PR to rerun the tests?

**Comment by jenlampton** [comment]
I have requested new sandboxes.

**Comment by klonos** [comment]
Thanks @jenlampton ...all green now 👍

**Comment by BWPanda** [comment]
Thanks @jenlampton, @stpaultim, @klonos & @docwilmot! I've merged https://github.com/backdrop/backdrop/pull/3274 into 1.x and 1.17.x.
