### ISSUE TITLE
[UX] Allow *all* blocks to have an admin label

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4558]
**Description of the need**

If you create a custom block in a layout, but you don't want it to be reusable, there's no way to give that block an admin label that's not displayed on the frontend. Similarly, if you add lots of, say, hero blocks to a layout (all with different visibility conditions), there's no way to differentiate them in the layouts UI if you don't give them a frontend-visible block title.

**Proposed solution**

Just as custom, reusable blocks have admin labels that are seperate from frontend block titles, so should all other blocks have this ability. All blocks should get an optional 'Admin label' field that displays in admin interfaces only (not the frontend).

**Additional information**

This issue is a combination of https://github.com/backdrop/backdrop-issues/issues/4325 (which requests this for existing, pre-made blocks) and https://github.com/backdrop/backdrop-issues/issues/1703 (which requests this for non-reusable, custom blocks). Both have been marked duplicates of this new one.

---
PR by @docwilmot : https://github.com/backdrop/backdrop/pull/3267

**Comment by docwilmot** [comment]
Assigning to me

**Comment by BWPanda** [comment]
> Assigning to me

When @docwilmot takes over an issue, you know it's going to be good! :smile:

**Comment by docwilmot** [comment]
All blocks now have a field to set an administrative title.
![admin title](https://user-images.githubusercontent.com/1042283/91361653-6c008f80-e7be-11ea-9b86-55dbfb56a9fc.PNG)
Please test and milestone if OK.

**Comment by Egarbeil** [comment]
Woo-hoo!! Testing tomorrow.  THANK YOU!

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by stpaultim** [comment]
This is awesome. Great work. 

But, I think we have a problem. In a couple of situations we seem to have redundant options. It is now possible for a custom block to have:

1) A display title (or custom title) 
2) An admin label (if it's reusable)
3) An administrative title 

In a case like this, the admin label and administrative title seem redundant AND the help text for administrative title is wrong, because if the administrative title is left blank, the admin label is used. 

Ideally, I think the option would have been to allow an admin label on blocks that are not reusable. Then we could have avoided the new concept of an administrative title. However, if there is a reason that this does not work. We may just need better help text or something to distinguish the admin label from the administrative title. 

![Home_page__home____PR_3267_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/91382202-c9acd000-e7ee-11ea-8e47-c70174d60178.png)

 - - - - - - - - 

Depending upon solution to the first issue, the title of the field set and the field title seem redundant. Do we need both?

![Home_page__home____PR_3267_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/91382256-f234ca00-e7ee-11ea-8416-76fd7eaf2063.png)

My suggested change to help text may no longer make sense, given the other issues.

**Comment by docwilmot** [comment]
😄 I hadnt realised this about custom blocks. Will reassess.

**Comment by klonos** [comment]
...ooops! I've jumped the gun there. We need an advocate for this issue in order to add a milestone; or get it to RTBC before September 1st.

**Comment by klonos** [comment]
Thanks for working on this @docwilmot 🙏  ...comments:

- I like @stpaultim's suggestion for the help text addition 👍 
- I believe that we use the term "label" for things that will be for admin-eyes-only, in the admin UI.
- Perhaps this could work better as a checkbox under the block title, similar to how the description checkbox works for views:

  ![image](https://user-images.githubusercontent.com/2423362/91465516-8c038200-e896-11ea-9867-90bd670d42dc.png)

**Comment by Egarbeil** [comment]
Perhaps just add the admin label to standard block types?

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by docwilmot** [comment]
I wanted to save the admin titles out of the way, since that would only be important in one type of block (BlockText) and only then in certain situations, hence hiding in an admin title (can rename to "admin label" for consistency) fieldset, like Views does.

I could disable the new fieldset on custom blocks and use the existing "Admin label" checkbox for those. Would that do?

**Comment by Egarbeil** [comment]
It would work for me

Elisabeth Garbeil, MBA PMP
Brainwrap Web Design
(810) 560-7181

**Comment by BWPanda** [comment]
I would prefer consistency across all blocks. So the admin label should look/work the same everywhere.

Guess this means either making the new ones match the existing ones, or changing the existing ones with the new location/field set.

**Comment by docwilmot** [comment]
I pushed a commit that addresses this earlier. Need to rename some things and use the description and do upgrade path (and there's probably still some kinks) but likely will be tomorrow. But please check out the UI change and let me know if that's workable.

**Comment by klonos** [comment]
@docwilmot was, that works for me 👍 ...there are a few issues, but since you already mentioned that it's WIP, I won't go into details. Let us know when this needs another round of testing/review. Thanks.

**Comment by docwilmot** [comment]
This was looking so simple before I realised reusable blocks complicate everything. 

So the minor complication here is that when you check reusable, the block needs a machine name, and that is normally generated from the admin label field. The minor issue left is that now that every block has an admin label fiedl, even when you *dont* check reusable, the admin label field will still of course have a machine name generator attached. I suppose we could disable the machine name field with JS upon checking the box, but that may be more than I can pull off by feature freeze.

**Comment by stpaultim** [comment]
_(I thought I commented on this last night)._

What you were able to accomplish looks good. But, I understand the problem.

In the end, I think that fixing this problem is going to make a lot of people happy, once it gets in. Even if it doesn't get in until 1.18.

**Comment by BWPanda** [comment]
@docwilmot I'm assuming that the admin label field was shown/hidden via `#states` based on the reusable checkbox field. Can you not simply move that `#states` behaviour from the admin label field to the machine name field?

**Comment by docwilmot** [comment]
I did try that in the current code, but that doesnt work. Once the page loads, the JS is already running and has replaced the textfield with the machine name `<span>`, so states have no effect. I think a bit of JQuery triggered on clicking the checkbox would do it, even if just hiding the machine stuff with CSS. But I dont think I'll have the time.

**Comment by docwilmot** [comment]
Found some time. Hiding the machine name field with JQuery.

**Comment by stpaultim** [comment]
I'm still a little confused about why it's important to hide the machine name. But, having said that, it doesn't appear to be hiding as expected. 

I'm in the sandbox. I have not checked the "reusable" box, but I can still see a machine name. Is there where you intended to hide it?

![default_layout_4455](https://user-images.githubusercontent.com/3144571/91797894-4f62be00-ebe9-11ea-953f-c8033826f0ce.png)

**Comment by BWPanda** [comment]
@stpaultim The most recent sandbox was created before the commit with the machine name field hiding:
![image](https://user-images.githubusercontent.com/2385329/91798599-9fcd3080-ec68-11ea-9e2f-565e42db14ad.png)

I'm not sure the sandbox is updated retroactively... It'll need to be re-created to test the new commits.

**Comment by docwilmot** [comment]
Maybe cache. I cleared, it seems to be working?

**Comment by stpaultim** [comment]
Yeah, maybe that was it. This is not a problem today. BUT, I see another small potential problem. 

1) Go to admin/structure/layouts/manage/default and add a custom block that is NOT "reusable"
2) Give it an admin title and click "Add Block" but DO NOT save layout
3) Click on Configure for that same block and make it reusable (note machine name does not appear)
4) Click on "Update Block" and then "Save Layout"
5) Go back to configure this block through the layout and the machine name is still not there. 

NOTE: If you create the block and give it an admin title and then add the block and save the layout BEFORE making it reusable, this problem does not exist. The machine label acts as expected. This is only a problem if you first add the admin label and then make it reusable, BEFORE saving the layout.

NOTE: In both circumstances, the machine label is available and visible through the custom blocks menu - admin/structure/block it only hidden on the layouts page.

**Comment by docwilmot** [comment]
Thanks @stpaultim the selector for the checkbox is getting a new ID on reload. Changed to selecting it by name instead.

**Comment by docwilmot** [comment]
This also shouldnt need an update hook since it doesnt change how custom blocks identify themselves.

**Comment by stpaultim** [comment]
@docwilmot - I am not seeing any difference. I've tried clearing the cache and opening in a new browser window. Am I missing anything?

**Comment by docwilmot** [comment]
Because I didnt actually save the right change? 🙄

**Comment by stpaultim** [comment]
Works for me! Great work.

**Comment by klonos** [comment]
I have tested this and it works as expected. I think that it's good to be merged as is now, for 1.17.0, and then we have a couple of weeks ahead to polish things.

Polishing:

The fieldset needs a better label, and the "This text is used only in administrative interfaces." bit applies to both the admin label and the description, so perhaps add it on the fieldset instead? I was thinking something like:

> Text used to identify the block when multiple blocks of the same type are added on the same layout. This is _not_ shown to site visitors - only in administrative pages.

So it'll look like this:

![image](https://user-images.githubusercontent.com/2423362/91920349-73013380-ecd1-11ea-8622-2de03adc3311.png)

Compare to current:

![image](https://user-images.githubusercontent.com/2423362/91918959-23b90400-eccd-11ea-9914-65952483ebd1.png)

**Comment by klonos** [comment]
Reviewing code next...

**Comment by klonos** [comment]
OK, I think that this is good to go! ...great work indeed @docwilmot 👍 ...as always 🙂

**Comment by Egarbeil** [comment]
Wonderful.  Thank you all!  This is a lifesaver for me.

Warmest regards,

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by quicksketch** [comment]
Looks good to me. I was trying to figure out if we could reduce code duplication, we have this same snippet in a dozen places:
```
    if (!empty($this->settings['admin_label'])) {
      return check_plain($this->settings['admin_label']);
    }
```

But even if we made a shared method for getting the admin label, it wouldn't be any shorter than these 3 lines.

I see one test is updated to use the `admin_label` value. Could we add a bit more test coverage to include checking `admin_description`?

> the "This text is used only in administrative interfaces." bit applies to both the admin label and the description, so perhaps add it on the fieldset instead? I was thinking something like:

I actually like the description below each field separately, but that may be a personal problem that I skip over fieldset descriptions when reading but individual fields the description is _right there_ so I read it while I'm typing and looking at the individual field.

Marking this needs work for the test coverage.

**Comment by docwilmot** [comment]
> But even if we made a shared method for getting the admin label, it wouldn't be any shorter than these 3 lines.

I debated this for at least 24 hours, even tried it. Thats what I concluded too.
> Marking this needs work for the test coverage.

Done

**Comment by quicksketch** [comment]
Thanks @docwilmot! I've merged https://github.com/backdrop/backdrop/pull/3267 into 1.x for 1.17. Great work and an excellent turn-around on this feature. :+1:

Thanks @BWPanda for filing the request. And thanks to @stpaultim, @klonos, and @Egarbeil for your reviews and feedback!
