### ISSUE TITLE
SQL error when uninstalling Locale module, if a language other than English has been set as the default

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4559]
**Description of the bug**

In trying to reproduce https://github.com/backdrop/backdrop-issues/issues/4517, I stumbled upon this bug: uninstalling the Locale module give this error:

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.locales_source' doesn't exist: SELECT s.source, s.context, t.translation, t.language FROM {locales_source} s LEFT JOIN {locales_target} t ON s.lid = t.lid AND t.language = :language WHERE s.version = :version AND LENGTH(s.source) < :length; Array ( [:language] => et [:version] => 1.16.2 [:length] => 75 ) 

**Steps To Reproduce**

There may be a quicker/simpler way to reproduce this, but here's how I did it:
1. Install the Language and Locale module
1. Add a language, set that one as default
1. Disable the Locale module
1. Uninstall the Locale module

**Actual behavior**

The error above is displayed.

**Expected behavior**

The Locale module is uninstalled and you can go on to uninstall the Language module too.

**Additional information**

I've tried this on my own sandbox dev site, then on a brand new Tugboat sandbox site.

<hr />

There are now two different approaches:

- wrap the query in function locale() in try/catch: https://github.com/backdrop/backdrop/pull/3260
- change the order of steps in function backdrop_uninstall_modules(): https://github.com/backdrop/backdrop/pull/3264

We can use one of those, or combine both approaches.
In the meantime both approaches have been combined to one PR.

**Comment by indigoxela** [comment]
After figuring out that simply switching the steps in backdrop_uninstall_modules() also fixes the SQLSTATE, I added an alternate [PR](https://github.com/backdrop/backdrop/pull/3264).

We now have to decide which approach is the best, or if we want to combine both.

**Comment by indigoxela** [comment]
I didn't seem much activity here regarding decide which approach to use. So I decided to combine both in one PR. Ready for another round of testing and review.

**Comment by herbdool** [comment]
Both of these approaches seem reasonable to me. I'll try to test it soon.

**Comment by herbdool** [comment]
I haven't tested it yet but was just thinking that the try/catch more stops a fatal error rather than fix the error itself so perhaps switching the uninstall order is the only option we have so far for fixing it. I'll get around to testing soon.

**Comment by herbdool** [comment]
Okay, I've tested both with steps above and with other modules such as Webform. I haven't seen any errors. The tables are still being removed ok. I assume the config files are too. Though I think @quicksketch should have final say.

**Comment by quicksketch** [comment]
I think combining both the re-arrangement of the uninstall function and the `try/catch` as done in https://github.com/backdrop/backdrop/pull/3260 is a good approach. Thanks @indigoxela for figuring those out!

The only suggestion I have to make, I left in a comment: https://github.com/backdrop/backdrop/pull/3260/files#r504954769, if it's possible to narrowly catch only the exception when the `locales_source` table is missing entirely, that might save us headaches later because we're silently suppressing something that might otherwise be a problem.

And... we should add an automated test, since this issue is tricky to reproduce.

**Comment by indigoxela** [comment]
> if it's possible to narrowly catch only the exception when the locales_source table is missing entirely, that might save us headaches later

Good point, done.
I do have some concern regarding performance (see my PR comment answer), but am not 100% sure if that's a real problem.

> And... we should add an automated test

Didn't I see that coming... :laughing:

**Comment by herbdool** [comment]
@indigoxela did your performance question get answered? It seems you're waiting on that before implementing suggested changes to the throw/catch.

**Comment by indigoxela** [comment]
> t seems you're waiting on that before implementing suggested changes to the throw/catch.

I already implemented that `throw` (see it directly below my question comment), but am still concerned because of possible performance penalties.

No, my question didn't get answered yet. Btw. tests have also been added.

**Comment by indigoxela** [comment]
My question has been answered. :wink: 

@herbdool the current label combination is a bit confusing. Was your intention to set it to RTBC?

**Comment by herbdool** [comment]
I had the labels I intended - you got some feedback so I think it's ready now.

**Comment by BWPanda** [comment]
Thanks for the PR @indigoxela! Thanks also to @klonos, @herbdool & @quicksketch. I've merged https://github.com/backdrop/backdrop/pull/3260 into 1.x and 1.17.x.
