### ISSUE TITLE
Could it make sense to switch the step order in function backdrop_uninstall_modules()?

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4570]
In an otherwise unrelated Issue (#4559) I realized that when a module is uninstalled, the config gets deleted *after* the database tables get dropped.

https://github.com/backdrop/backdrop/blob/5bc661ea3c6a4ac61fe7fad0355126558d9ba522/core/includes/install.inc#L1047

Could it be that it makes more sense to drop the db tables last?

I'm aware that Locale *might* be a special case.

But couldn't other modules also choke on the fact that the config is still around although the db tables are already gone?
Does anyone know of any? Feedback is welcome.

**Comment by indigoxela** [comment]
Wow! I just played in a local crashburn install with uninstalling Locale with the order of config and database deletion switched - and it fixes it.

To be honest, I didn't expect that. The question here was rather a general one regarding code logic. Hm... I'll update the other Issue.

**Comment by herbdool** [comment]
Seems to me that this would be a good move to switch the steps. We'll need test it thoroughly. I can't think of why a module would need to delete the tables before the config, but I can see how the reverse is potentially a problem. A problem which just didn't show up until the system tried to look up translated config strings.

**Comment by indigoxela** [comment]
> We'll need test it thoroughly.

Do you have any suggestions? What could be potential pitfalls?
