### ISSUE TITLE
[UX][DX] Add the ability to make messages dismissible

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4571]
This is related to #1912 (and a sibling to #3995).

There are quite a few contrib modules that allow this. Some examples:

https://www.drupal.org/project/pdm

> Have you ever wished for a very simple way to have a status message (set by `drupal_set_message()`) persist across multiple pages and also be dismissable? Well, you've come to the right place, because PDMs (persistent dismissable messages) is what we're selling.
>
>The PDM module takes over all dsms (messages set by `drupal_set_message()`) and modifies them to become dismissable (similar in some respects to the [Absolute Messages](https://www.drupal.org/project/absolute_messages) module. Each message appears in its own div and visual area (as opposed to the default in Drupal, which is to group all warning, status and error messages together) and can be removed by clicking a 'hide' link.

https://www.drupal.org/project/dismiss

> Adds a jQuery-powered "dismiss" button to all Drupal messages so they can be closed without refreshing or opening browser devtools. There's also a config option to auto-hide status messages (warnings/errors will not disappear).

https://www.drupal.org/project/absolute_messages

> - each message has its own "Dismiss" (close) icon,
> - optional "Dismiss all" icon is displayed if total number of messages exceeds value defined in module settings,
> - messages could be dismissed automatically after a specific time - configurable in module settings for each message type separately,

https://www.drupal.org/project/messageclose

> Add a close button to each status message.

Also a related feature added to Webform 8.x-5.x: https://www.drupal.org/node/2956598

> The Webform module's help manager now supports notifications which displays a custom dismissible message on the Webform administration page (/admin/structure/webform).

---

Translation update: We'll now need a translation for `Dismiss`

**Comment by BWPanda** [comment]
PR available for testing: https://github.com/backdrop/backdrop/pull/3387

I started trying to add a timeout feature for status and info messages, but I couldn't get the JS working properly. So if anyone else wants to add that, I'd be grateful!

![image](https://user-images.githubusercontent.com/2385329/98063886-27bbfa80-1ea5-11eb-80f9-657aaee42494.png)

**Comment by herbdool** [comment]
I would keep this totally stripped down for a first run at this.

We don't even need to have an UI for enabling/disabling it. Just make it default and if someone really doesn't want it they can set it in the settings file.

And leave off the timer. I don't think it's great UI. Maybe I could be convinced otherwise but it is more controversial and could always be added later if people do want it.

**Comment by BWPanda** [comment]
Thanks @herbdool. I mainly added the UI because I was hoping for a timeout setting too. But if that doesn't happen then we can remove the UI altogether. Let's see if others agree and, if so, I'll update the PR.

**Comment by klonos** [comment]
Thanks so much @BWPanda 🙏 

...and before anyone else wonders:

"dismissable" vs. "dismissible" => "Capable of being dismissed" vs. "That may be dismissed" ...not sure which adjective of the 2 is the best fit in our situation, but FWIW Chrome spell check marks the first as wrong 🤷 

![image](https://user-images.githubusercontent.com/2423362/98088630-5a0c2e80-1e8a-11eb-8ceb-ac8da23ef147.png)

**Comment by klonos** [comment]
...I did a quick review, but cannot test. We seem to have lost our PR sandboxes 😞

**Comment by BWPanda** [comment]
In case it wasn't mentioned or obvious already, this is also a functioning contributed module for Backdrop: https://github.com/backdrop-contrib/dismiss

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...there seem to be conflicts in the PR. Care to rebase/update and then let us know so we can test?

**Comment by BWPanda** [comment]
Sandbox working again.

**Comment by stpaultim** [comment]
I just tested this in the sandbox. I like it. 

I tested using the "Execute PHP" page. Not sure if we need to test this under other circumstances as well or if we can trust it will work well on all messages?

**Comment by herbdool** [comment]
We could also test this with a Bootstrap theme to see how it interacts with Bootstrap's ability to dismiss messages as well. I recall that in D7 but I haven't tried it on Backdrop.

I'm wondering how others feel about my position that this feature in core should be without the timer and no UI. Leave that part to contrib.

**Comment by klonos** [comment]
Code looks good, and things seem to work as expected (I tested with "regular" messages, after saving content or submitting configuration forms).

I also like the simple on/off approach, w/o timer @herbdool.

**Comment by klonos** [comment]
...damn it! Just noticed that there are yet more conflicts, so this needs another rebase please @BWPanda.

**Comment by stpaultim** [comment]
> I'm wondering how others feel about my position that this feature in core should be without the timer and no UI. Leave that part to contrib.

Didn't comment on UI, because I don't know where the UI is or would be. I don't really see the need for one. 

In terms of timer, I'm also not sure what this means. Does this mean that messages are only dissmissible for a specific time frame after they appear OR that messages disappear automatically after a certain length of time? I guess, I don't think either are necessary.

**Comment by BWPanda** [comment]
@klonos PR updated.

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ... @docwilmot added a couple of comments in the PR, one re the help text referring to the x that dismisses messages as a link instead of a button.

Just a final thought: are there any drawbacks to having the close button be there all the time; hence no settings page? (perhaps that's what @herbdool meant by "no UI")

**Comment by herbdool** [comment]
@klonos yes, I meant that: no settings page

**Comment by klonos** [comment]
Thanks @herbdool 👍🏼 ...I'm thinking the same: no settings, but still allow contrib to easily override/disable this.

**Comment by jenlampton** [comment]
> I'm wondering how others feel about my position that this feature in core should be without the timer and no UI. Leave that part to contrib.

I agree 100%

> We don't even need to have an UI for enabling/disabling it. Just make it default and if someone really doesn't want it they can set it in the settings file.

I agree with @klonos and @herbdool No settings needed :) Those could all be left to the `dismiss` module in contrib!

This is still marked PR needs review, so I'm going to go have a look at that too :)

**Comment by quicksketch** [comment]
This set of changes looks pretty good! I was worried about what would happen if sites didn't provide styling for the "Dismiss" option, but turns out it's just a link appended to the end. So a typical situation without theming might look like this:

![image](https://user-images.githubusercontent.com/100206/131595948-6b047ce9-799e-4eec-a2e9-f7a68abfd0eb.png)

However, the default markup has "element-invisible" on the dismiss element. Which means it's not actually visible at all by default, you'd have to add CSS to make it seen. That might be okay too. Themes that didn't provide any styling at all for the dismiss option just wouldn't show it (though the Seven theme would still show them for administrators).

Seems most folks here so far want to avoid a settings page. Should we leave the config option `config_get('system.core', 'messages_dismissable')` in place even without the UI to disable them? Also in such a case, seems that we would enable dismissable messages all existing sites, because there wouldn't be any easy way to enable them without a UI.

**Comment by jenlampton** [comment]
> Should we leave the config option config_get('system.core', 'messages_dismissable') in place even without the UI to disable them?

I was thinking no. But would contrib be able to add this feature easily?

**Comment by herbdool** [comment]
I think we should keep the config option. Make it easy for themes to disable it if it conflicts with the theme functionality.

Looks like consensus is developing here.

**Comment by klonos** [comment]
> I think we should keep the config option.

I'm of the same opinion, for the same reason 👍🏼

**Comment by jenlampton** [comment]
I'm going to work on an update to the PR, in the chance this might still be able to get in tonight :D

**Comment by jenlampton** [comment]
Okay, I've added a second commit to the PR that removes the UI, changes the spelling from `dismissable` to `dismissible` and updates the number of the update hook in system module.

**Comment by docwilmot** [comment]
Pending removal of a semicolon (which kills the sandbox and fatals the site), looks good. Ready to RTBC once thats fixed.

**Comment by herbdool** [comment]
I fixed the semicolon. And I also fixed the update hook - so that it's enabled by default since it would be hard for people to enable with no UI (as @quicksketch mentioned above).

**Comment by herbdool** [comment]
I'm tempted to merge this but not sure if I'll have time tonight. Maybe but if someone else gets to it before I do feel free.

**Comment by BWPanda** [comment]
I merged https://github.com/backdrop/backdrop/pull/3717 into 1.x. Thanks to @jenlampton, @klonos, @herbdool, @stpaultim, @quicksketch & @docwilmot for your work on this!
