### ISSUE TITLE
[DX] Basis: list css in basis.info alphabetically

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4572]
The stylesheets section lists .css files randomly.

PR upcoming...

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/3266

**Comment by klonos** [comment]
...taking the liberty to add the bug release milestone, since this just shuffles lines of code, and their order doesn't affect the theme in any way.

**Comment by klonos** [comment]
...oops, I might have jumped the gun here. During my testing, I didn't notice anything break in Basis, but there's mentions on the web saying that the order does matter:

https://www.drupal.org/forum/support/post-installation/2015-08-10/how-to-reliably-set-the-loading-order-of-css-files#comment-10216017

> If you are adding your files in the .info file, they will be loaded in the order they are listed in that file.

https://www.drupal.org/docs/7/theming/working-with-css/adding-style-sheets-from-info-files

> - The order in which the styles are listed in the .info file will reflect the order it is displayed on head of the page.

Can someone please confirm?

**Comment by hosef** [comment]
That is correct. It would probably be a good idea to alphabetize the files in the component folder, but base.css and layout.css should be at the top and skin.css should be at the bottom.

**Comment by indigoxela** [comment]
I can also confirm that order matters here, alphabetical would be a breaker.

Background: CSS files are ordered the way they appear in the info file, both when added to the html head aggregated and not aggregated. Later rules override previous rules.
Another important thing is the scope: "all" comes before "screen".
And additionally CSS files added via backdrop_add_css() can have a weight set, which controls their position. The same applies to js files.

@klonos your impression that the order is "random" isn't actually correct.

**Comment by klonos** [comment]
>@klonos your impression that the order is "random" isn't actually correct.

I figured that much (can you tell that I'm not doing a lot of theming? 😅) ...let's close this one then.
