### ISSUE TITLE
URL alias pattern 'maxlength's don't match

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4573]
The 'Default URL alias pattern' field on `/admin/config/urls/path/patterns` has a `maxlength` attribute set to `1280`. But the same field on `/admin/structure/types/manage/[CONTENT_TYPE]` has a `maxlength` attribute set to `128`. We should increase the latter to match the former.

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3268

**Comment by indigoxela** [comment]
You're right, the `#maxlength` should, of course, be the same as in the site-wide form on admin/config/urls/path/patterns.

Currently the pattern is truncated to 128 chars in the node form.

But while testing I found another glitch: the node form does not validate if the "pattern" contains a token anyway.
On the main form I got "The URL alias pattern for all Footype URLs cannot contain fewer than one token."
On the node form I could put in anything without a token.

So it seems, that `#min_tokens` is also missing.

**Comment by BWPanda** [comment]
Thanks @indigoxela. I added that, plus some other properties I found on the site-wide form. PR updated.

**Comment by indigoxela** [comment]
I see, nice catch! Token validation was also missing.

When I now add a non-existent token, I get something like:
```
The Default URL alias pattern is using the following invalid tokens: [node:foobar]. 
or
The Default URL alias pattern is using the following invalid tokens: [term:foobar]. 
```
...on the node type form or the vocabulary form.

The main and the node/vocab forms behave consistently, RTBC.

**Comment by BWPanda** [comment]
Thanks @indigoxela! Merged https://github.com/backdrop/backdrop/pull/3268 into 1.x and 1.16.x.
