### ISSUE TITLE
[UX] Make the "Update XXX" pages less confusing

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4577]
**Description of the bug**

Currently core updates show up on the theme _and_ layouts _and_ module update pages. That's confusing, especially regarding the theme and layout update page.
Core is neither a theme nor a layout nor a module. On the other hand, admin/reports/updates/list links to the admin/modules/update page for core updates.

Can we find a more consistent and less confusing concept for this UI?
At least, we should not show core updates on the theme and layout update pages.

![update-themes](https://user-images.githubusercontent.com/842066/91417895-b97a0c80-e851-11ea-95b2-b0b68a4c1d56.png)

![update-layouts](https://user-images.githubusercontent.com/842066/91417917-bf6fed80-e851-11ea-9776-364c95005e4a.png)

And I find it pretty weird, that I *can* update core from the theme update page.

Another question: do we really need three pages for that?
What about one central page for all types of projects. (I thought, there's already an Issue for that, <strike>but couldn't find it in the queue.</strike>)

UPDATE: spoken too soon, there it is https://github.com/backdrop/backdrop-issues/issues/2714

**Comment by klonos** [comment]
> ...do we really need three pages for that?

Nope 😅 ...glad to have another person support the idea behind #2714 ...let's close this as a duplicate.
