### ISSUE TITLE
Add a :link sub-token for user tokens

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4584]
This is basically the same as the following Token 7.x issues:

- https://www.drupal.org/project/token/issues/1176592

> I'm working on D7 Submitted By module and found that there is no way to have a `$submitted` with a linked user name, like we normally have for content and comment.
>
> Suggesting adding a fully themed username, `[user:name_themed]` via `theme('username')`

- https://www.drupal.org/project/token/issues/698242

> `[user]` is replaced with `$account->name`. This makes it difficult when trying to output all user names the same way by overriding `theme_username()`.
> 
> Is there a reason that this line:
> 
> ```php
> $values['user'] = $account->uid ? check_plain($account->name) : variable_get('anonymous', 'Anonymous');
> ```
>
> Cannot be replaced with this line?:
>
> ```php
> $values['user'] = theme('username', $account);
> ```
>
>This would be a lot more consistent with how user names are output. If this change is not acceptable, then perhaps we could introduce a new token that does call the proper theme function.

**Comment by klonos** [comment]
This could be used with the recently introduced #2379, so that the author name in the "submitted by" info can be rendered as links to the user profile (if the user viewing this has the proper permissions).

**Comment by klonos** [comment]
PR up for testing: https://github.com/backdrop/backdrop/pull/3276

This is a very simple, 5-line change, in which I've added support for `:link` to user tokens. ...currently, the default "submitted by" setting for both pages and posts is `[node:created:medium] by [node:author]`. Although this should remain untouched for existing sites, should we change it to `[node:created:medium] by [node:author:link]` for new installations? Let me know.

**Comment by stpaultim** [comment]
Works for me.

**Comment by olafgrabienski** [comment]
> should we change it to [node:created:medium] by [node:author:link] for new installations?

Makes in any case only sense with a good looking and informative profile page, which Backdrop doesn't provide out of the box.

**Comment by klonos** [comment]
@olafgrabienski my use case for recommending this is not for the benefit of site visitors, but for site admins. Consider this:

- Adding content is enabled for authenticated users (think of our forum site).
- Spam user adds multiple content.
- Spam filter doesn't catch it.
- Admin logs in and notices the spam in the first piece of content, but they don't wanna waste time deleting content individually...

Without the node author as link:

1. Copy the username.
1. Go to the user management listing.
1. Paste and search for the user.
1. Click the edit dropbutton.
1. Delete user and all its content/comments.

With the node author as link:

1. Click on the username.
2. Click edit.
3. Delete user and all its content/comments.

IOW, we are saving site admins a couple of steps, and multiple clicks, keystrokes, and page loadings.

**Comment by olafgrabienski** [comment]
@klonos I don't have strong feelings about the default, and your use case makes perfectly sense. It's however not very common. And with this PR (even without [node:author:link] as default), it would be easy to change the token for the use case.

**Comment by klonos** [comment]
Right, we can always leave that as a follow-up. The main thing here is the addition of `:link` for user tokens. Can I please get a milestone label @stpaultim or @olafgrabienski ?

**Comment by indigoxela** [comment]
Code looks good, RTBC.

Regarding the milestone: is it supposed to go into 1.17.1 or 1.18?

**Comment by klonos** [comment]
Thanks @indigoxela 🙏 ...since it's a new feature, I'm afraid that will need to wait for 1.18.0.

**Comment by BWPanda** [comment]
To me, this new token should be the same as the `name` token, but with a link added. However, for Anonymous users, this token outputs `Anonymous (not verified)`, whereas the `name` token just outputs `Anonymous`... Not sure of the solution, but I thought to mention it.

For the benefit of those who don't look at the PR, I made a suggestion there to change the wording of this token:

> After reading the names and descriptions of the other tokens in this function, I think the following wording would be better to use:
> 
> ```
> 'name' => t('Name (linked)'),
> 'description' => t("The login name of the user account, displayed as a link to the user's profile page."),
> ```
 This is instead of the current wording:
```
'name' => t("Profile link"),
'description' => t("Link to account profile page based on the <em>View user profiles</em> permission."),
```

**Comment by klonos** [comment]
Thanks for reviewing @BWPanda 🙏 ...re the "not verified" thingy, I don't think that it should be addressed here. We already have a separate issue for it: #3390 

I can update the description of the token, but let's wait for some feedback before actually doing so. My personal objection is with the "displayed as a link" portion of your suggestion. This is not true if the role viewing the output does not have the "View user profiles" permission. I think that although it'd be more wordy, a combination of the existing and your suggested description might be better. Something like this perhaps:

> The login name of the user account. If the user viewing the output has the _View user profiles_ permission, then the output is displayed as a link to the user's profile page.

**Comment by klonos** [comment]
...I just revisited the PR and noticed that the name of the token is "Profile link". If we are to change the description, then this also needs to make sense.

**Comment by quicksketch** [comment]
I like the compromise you suggested @klonos. And agreed that if we change the description, updating the label also makes sense. I think `Name (linked)` as suggested by @BWPanda sounds good .

**Comment by BWPanda** [comment]
What about the slighty more condensed:

> The login name of the user account, displayed as a link to the profile page (for users with the *View user profiles* permission).

**Comment by klonos** [comment]
I went with `Name (linked)` for the label of the token, and for its description:

>The login name of the user account (for users with the _View user profiles_ permission it's displayed as a link to the profile page).

@jenlampton @stpaultim and others, are you happy with the above?

**Comment by klonos** [comment]
![image](https://user-images.githubusercontent.com/2423362/96929976-a9825000-14c3-11eb-96d0-c70d72724af0.png)

![image](https://user-images.githubusercontent.com/2423362/96930016-b7d06c00-14c3-11eb-9f79-065a7aecb3d6.png)

**Comment by jenlampton** [comment]
Oh interesting, I thought the `:link` token was for the url -- not for the name (linked). Any chance we can change the token name to "linked" to avoid the confusion? There are other past-tense verbs in tokens as precident, like `user:created`.

**Comment by quicksketch** [comment]
We don't have any other `link` or `linked` terminology in tokens that I could find (other than `menu-link`, which is a whole thing). IMO `current-user:link` is accurate terminology (a link is both the anchor tag with URL and the text it wraps). The description provides any needed clarity.

**Comment by indigoxela** [comment]
It seems to me that the updated label and description clarified things. And I also think it's easy to distinguish "Name", "Name (linked)" and "URL".

Another token browser screenshot:
![token-browser](https://user-images.githubusercontent.com/842066/97103444-d2196e00-16ac-11eb-8ee8-7ec77e1205db.png)

So back to RTBC.

@jenlampton feel free to revert that if you still have concerns (which I don't expect).

**Comment by stpaultim** [comment]
I am good with the current PR, but offering a few thoughts for consideration.

Regarding "current-user:link" vs "current-user:linked" - I see the point. If "linked" is not breaking any existing use patterns, I think it's slightly better. But I'm not sure that the change adds much clarity and don't feel strongly about it. I think "link" is also fine.

> The term "Login name" isn't something we use anywhere else in core. Can we stick with "Username" for consistency?

@jenlampton - I agree that "Login name" doesn't feel right. I searched the code base only to find we use it in one other place. 

![Page__PR_3276_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/97116320-44e51200-16ca-11eb-920d-00fa3f6bf1f7.png)

I assume that is where this PR got the term. I think it would be good to drop that term in favor of username, but we would need to do that in both places. I think that the problem is that for every current-user token, we describe it as the user account. Does "username of user account" make sense? Does that make this a new/different issue and/or PR.

TEXT SUGGESTION:

CURRENT: "The login name of the user account (for users with the View user profiles permission it's displayed as a link to the profile page)."

SUGGESTED: "The login name of the user account (displayed a link to the profile page for users with the View user profiles permission)."

**Comment by klonos** [comment]
@jenlampton thanks for the feedback, but re `user:linked` it also has the drawback that this is not what people coming from D7 will be using in their existing token-enabled fields - so keeping it the same as in D7-land would make upgrades easier 😉 

> Can we stick with "Username" for consistency?
...
> I assume that is where this PR got the term...

Yup, I have copied the description from the other similar token, for consistency.

> ...I think it would be good to drop that term in favor of username, but we would need to do that in both places.

Exactly 👍 ...if we change the newly-introduced one, then we'd also need to update the existing one too IMO. Let me know if the consensus is that, and I'll update the PR accordingly.

**Comment by jenlampton** [comment]
> this is not what people coming from D7 will be using in their existing token-enabled fields

Ah, I thought we were creating something new. Never mind then :)

> if we change the newly-introduced one, then we'd also need to update the existing one

Yes please!

**Comment by klonos** [comment]
I've updated the PR to change both instances of "The login name of the user account" to "The account username":

![Screen Shot 2020-11-04 at 9 34 39 pm](https://user-images.githubusercontent.com/2423362/98159782-d6802b00-1ee5-11eb-964a-ec411b06ff4c.png)

Still RTBC I assume. Right?

**Comment by jenlampton** [comment]
Looks great!

**Comment by BWPanda** [comment]
Thanks @klonos for thefeature request and PR! Thanks also to @stpaultim, @indigoxela, @quicksketch & @jenlampton for reviews/testing. I've merged https://github.com/backdrop/backdrop/commit/0189645a44b1df45b24252731a2e7e05227b5df7 into 1.x.
