### ISSUE TITLE
Mismatch in config file name and _config_name value in system.core.json

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4591]
**Description of the bug**

I'm not 100% sure if this is a bug (it didn't seem to cause problems so far), but it's a bit weird:

The system module ships with default config in file system.core.json (core/modules/system/config), but the "_config_name" inside that file is `"system.performance"`.

Is this by intention or an oversight?

Note: the actual config file (files/config_thelonghashhere/active/system.core.json) does contain `"_config_name": "system.core"`

**Steps To Reproduce**

There's nothing to reproduce, just json content: https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/config/system.core.json

**Expected behavior**

Usually the filename and the value of "_config_name" correspond.

**Comment by BWPanda** [comment]
Ha, indeed. Seems like a bug (oversight) to me...

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3285

**Comment by klonos** [comment]
Thanks @BWPanda ...RTBC 👍

**Comment by BWPanda** [comment]
Thanks @klonos, I've merged https://github.com/backdrop/backdrop/pull/3285 into 1.x and 1.16.x. Thanks also to @indigoxela for finding this!
