### ISSUE TITLE
Fixed: Ensure that layout conditions have all required contexts.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4594]
**Description of the bug**

When creating a `User compare` context (to compare my user account to the user account for the profile page I am viewing, for example) I noticed that even though contexts were marked as **required**, the visibility condition is still visible in the drop-down menu.

This new visibility condition has two required user contexts, so should not be available on any path without a user context (the second user context is `global $user` and is always available). Yet it appears in the select list for the home page layout. 

<img width="2750" alt="Screen Shot 2020-09-02 at 3 28 39 PM" src="https://user-images.githubusercontent.com/397895/92043589-2c432600-ed31-11ea-9812-f1e3f2c47847.png">

**Steps To Reproduce**

To reproduce the behavior:
1. Apply the patch from https://github.com/backdrop/backdrop-issues/issues/4029
2. Manage blocks on the home page layout
3. Attempt to add a visibility condition

**Actual behavior**

4. Confirm that `User: compare` appears in the list

**Expected behavior**

Since `User: compare` appears in the list has required contexts that are not present, `User: compare` should NOT appear in the list of available visibility conditions

**Comment by jenlampton** [comment]
I did some testing and it does not look like this is a problem for conditions with only a single required context. 

I think the problem here is that Backdrop might not be able to tell that there are two required user contexts. I think it checks the first and asks "Is there a user? yes." then it gets to the second one and again says "Is there a user? Yes." Without identifying that it needs a **second** user context.

**Comment by jenlampton** [comment]
Here's some code from ctools that might be relevant?
```php
function ctools_get_relevant_access_plugins($contexts) {
  if (!isset($contexts['logged-in-user'])) {
    $contexts['logged-in-user'] = ctools_access_get_loggedin_context();
  }

  $all_plugins = ctools_get_access_plugins();
  $plugins = array();
  foreach ($all_plugins as $id => $plugin) {
    if (!empty($plugin['required context'])
      && !ctools_context_match_requirements($contexts, $plugin['required context'])
    ) {
      continue;
    }
    $plugins[$id] = $plugin;
  }

  return $plugins;
}
```
and 
```php
function ctools_context_match_requirements($contexts, $required) {
  if (!is_array($required)) {
    $required = array($required);
  }

  // Get the keys to avoid bugs in PHP 5.0.8 with keys and loops.
  // And use it to remove optional contexts.
  $keys = array_keys($required);
  foreach ($keys as $key) {
    if (empty($required[$key]->required)) {
      unset($required[$key]);
    }
  }

  $count = count($required);
  return (count(ctools_context_filter($contexts, $required)) >= $count);
}
```

I think the trick is to count the number of contexts and make sure it's greater than or equal to the number of required contexts.

**Comment by argiepiano** [comment]
The new `User compare` condition needs very specific `User` contexts: (1) the logged in user, and (2) the user from the URL. 

The problem is that Layout, when deciding which visibility conditions to show, doesn't currently differentiate where a required `User` context comes A `User` context could come from the logged in user (always available), a user ID manually entered in the context UI, or the user from URL.

That's why all visibility conditions that use `User` as required context are shown in the Home page layout: basically the logged in user is a context that's always available, regardless of the path.  

This kind of granular check may require an overhaul of the way Layout handles required context, so that you can specify which type of user context you want to require - whether it's a logged in user, a user from path, or a user entered through the context ui.

**Comment by argiepiano** [comment]
I've changed this to a Feature request and change to minor candidate. We can discuss whether this is a bug or not...

**Comment by jenlampton** [comment]
I've tested the latest PR, but I'm still not able to load any fields from the author's context. Here's my example layout:
https://pr4087-hh5tzd5cgyw6q2dgx5wvdvasfxyg96fq.tugboatqa.com/about

I've added the same field (photo) into the left sidebar and the right, left sidebar should be pulling the node author, and right sidebar pulls from the currently logged-in user. The right works, but the left does not.

**Comment by argiepiano** [comment]
Yes, this issue is not related to the "author of node" context problem. :)

**Comment by herbdool** [comment]
Just tested. Good news: I don't see "User compare" on the Home layout. Bad news: I don't see "User compare" on a new `user/%` layout either. Marking this needs work unless I'm not testing this right.

**Comment by argiepiano** [comment]
Can you let us know how you are testing?

**Comment by argiepiano** [comment]
You must apply the patch here https://github.com/backdrop/backdrop-issues/issues/4029 in order for the `User compare` feature to work. If you are testing with tugboat, and this patch is not applied, you won't see `User compare` because it's not in core yet.

**Comment by argiepiano** [comment]
To clarify: for testing you must apply both patches:

- #4029 (adds the User compare feature)
- https://github.com/backdrop/backdrop/pull/4087  (linked to this issue - fixes the requirement of 2 user contexts as a condition of showing the User compare feature)

**Comment by jenlampton** [comment]
@argiepiano I can confirm the same behavior. 

<img width="1574" alt="Screen Shot 2022-08-05 at 1 45 33 PM" src="https://user-images.githubusercontent.com/397895/183160186-d42d2c7e-c129-4d3f-a7a2-987ad38fb435.png">

This is a screenshot of my user profile layout for a site that was previously using https://github.com/backdrop/backdrop-issues/issues/4029 (adds the User compare feature) (which you can see on the top-most block). 

I am not able to add the User: Compare visibility rule to any other blocks anymore. (As you can see from the open list of visibility rule options from the current block configuration)

**Comment by jenlampton** [comment]
I am able to see the User Compare visibility rule when 2 user contexts are available. Here's a screenshot of a site using both patches: 

**user/% Layout**
<img width="1574" alt="Screen Shot 2022-08-05 at 1 45 33 PM" src="https://user-images.githubusercontent.com/397895/183160375-f35a90a9-8e04-4c56-b70e-db3c58158dac.png">

**home Layout**
<img width="1584" alt="Screen Shot 2022-08-05 at 1 50 11 PM" src="https://user-images.githubusercontent.com/397895/183160537-b9f770dc-80c7-45b5-99e8-0fd880e4d262.png">

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4087 into 1.x for 1.25.0. Thanks @argiepiano, @jenlampton, and @herbdool!

**Comment by jenlampton** [comment]
I couldn't find a way to re-title this issue to make it sound more like a feature request and less like a bug fix for the release notes, so I switched the labels back. Hope that's okay.
