### ISSUE TITLE
Vocabulary names not shown at /admin/config/urls/path/patterns

### ISSUE THREAD

**Issue by djzwerg** [backdrop/backdrop-issues#4597]
**Description of the bug**

As described above the different vocabulary names weren't shown at /admin/config/urls/path/patterns. Only "@vocab-name" is shown there. So it's hard to use different patterns for different vocabularies.

I'm using Backdrop with the German translation and do not know whether this is an internationalization issue.

**Steps To Reproduce**

To reproduce the behavior:
1. Go to /admin/structure/taxonomy/add and create a new vocabulary
2. Go to /admin/config/urls/path/patterns
3. Scroll down to the taxonomy URL patterns

**Actual behavior**

You can only see "@vocab-name"

**Expected behavior**

The vobulary name should be shown up (e. g. "tags").

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.16.2
- Web server and its version: Apache, php 7.3.20
- Browser(s) and their versions: Firefox Developer Edition, Google Chrome

**Comment by indigoxela** [comment]
I can reproduce it in German. Let me guess, your website is German? That's a placeholder mismatch in the translation.

![screenshot-translation](https://user-images.githubusercontent.com/842066/92134809-456bd580-ee0a-11ea-906b-ed3ffa63d3f8.png)

That's super easy to fix: Go to admin/config/regional/translate/translate, search for string "URL alias pattern for all" and replace that `@` with `%`.

**Comment by olafgrabienski** [comment]
> That's a placeholder mismatch in the translation.

Good catch! Once the fix is confirmed, I'll check the translations on localize.backdropcms.org.

**Comment by olafgrabienski** [comment]
Okay, I was also able to reproduce the issue for German and can confirm that changing the German translation to `Alias-Muster für alle URLs des Vokabulars %vocab-name` fixes the issue.

I've updated the translation on localize.backdropcms.org accordingly. The downloads on https://localize.backdropcms.org/translate/languages/de contain the fix.
