### ISSUE TITLE
Regression: help text was previously removed

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4601]
I'm making this a bug report since it's a regression. I don't think we discussed why it was previously removed here https://github.com/backdrop/backdrop-issues/issues/4265

I hadn't realized that in #293 the help text was removed (I only just found the issue). There were a couple good reasons: worked better on small screens, and having a variety of characters, numbers and punctuation doesn't help as much as length.

@quicksketch mentioned:

> Also, concerning the changing nature of "secure" passwords, I determined that maintaining the "password tips" in any way was largely unnecessary. Why? Because as mentioned in the Dropbox article simply using numbers or symbols does not make a more secure password. Especially when using common character variations, if you're just replacing "e" with 3 and "o" with "0", it's still a password that would likely get cracked by dictionary lookups.
>
> So instead of calculating based on those criteria alone, I adopted the approach used by zxcvbn to first determine the level of entropy in the character set, then multiply that by the length of the string. This makes it so that extremely long passwords (e.g. correcthorsebatterystaple) are considered more secure than short passwords with one a symbol, number, and mix of characters. Using this approach resulted in a much more linear approval of passwords. Any password can be made acceptable by adding enough characters.

**Comment by herbdool** [comment]
I think we could either remove the help text on account creation, or put more emphasis on length. The latter won't help with the mobile view though.

**Comment by indigoxela** [comment]
This is what we currently have:

![screenshot-password-field](https://user-images.githubusercontent.com/842066/92207892-5bb97600-ee8a-11ea-8097-f764f05ca14c.png)

This could get tweaked:

<strike>Provide a password for the new account.</strike> Weak passwords will be rejected.

-    The password cannot be the same as the username or e-mail address.
-    The password must be sufficiently long or complex<strike>: containing a number of lower- and uppercase letters, digits and punctuation.</strike>

Maybe emphasize length a bit more.

Removing the help text completely seems counterproductive to me.

People really need to know that:

1. Username/email will be rejected anyway
2. What a "strong" password needs (length)

If rejecting weak passwords is disabled, this form field needs no help text at all, "Provide a password for the new account." is pretty redundant. It's a password field.

**Comment by herbdool** [comment]
@indigoxela I like the approach. I've added a PR.

**Comment by indigoxela** [comment]
@herbdool thanks for the PR.

Here's a screenshot (Basis this time and the form item on user/register, on a small screen).
Short and precise text, I like it.

![screenshot-pw-form](https://user-images.githubusercontent.com/842066/92302016-e670a280-ef68-11ea-99d0-3e28da6843cb.png)

If rejecting weak passwords setting is off, there's no help text. A password field is pretty self-explanatory anyway.

**Comment by klonos** [comment]
RTBC 👍

**Comment by quicksketch** [comment]
Thanks @herbdool and @indigoxela! Merged https://github.com/backdrop/backdrop/pull/3292 into 1.x for 1.17.0.

I especially like the removal of "Please provide a password for the new account." as though that wasn't obvious that if you're creating an account, that's what the password will be used for.
