### ISSUE TITLE
EntityLayoutContext::formValidate may try to load invalid entity ID

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#4605]
**Description of the bug**

The `EntityLayoutContext::formValidate()` function checks if the ID is blank, and invokes `form_set_error()` if so.  It then tries to load the blank ID.  Instead, `formValidate()` should skip trying to load an entity that it knows is invalid.

**Steps To Reproduce**

Visual inspection of core/modules/layout/plugins/context/entity_layout_context_handler.inc.

**Additional information**

This manifests as a PDOException when running the test suite using PostgreSQL (see below.)  Even though MySQL quietly casts empty string to something else (NULL? zero?), there is no reason to even try. 

```
Exception PDOExcepti entity.controller  301 DefaultEntityController->load()    
    SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax
    for integer: ""
    LINE 4: WHERE  (base.fid IN  ('')) 
```

---

PR by @jlfranklin https://github.com/backdrop/backdrop/pull/3297

**Comment by indigoxela** [comment]
@jlfranklin which Backdrop version and with which test? Without being able to reproduce testing an code review isn't possible. The test only fails with Postgres, did I get that right?

**Comment by indigoxela** [comment]
> Even though MySQL quietly casts empty string to something else

Which version of MySQL or MariaDB are you using?

The php version might be helpful, too.

**Comment by jlfranklin** [comment]
The test only fails with PostgreSQL, that is correct.  That's because MySQL quietly casts an empty string to some integer value in the WHERE clause, whereas PostgreSQL is more particular and rejects empty string as an integer.

Take a quick look at the patch.  It's clear that the patch is the Right Thing To Do™, even if MySQL allows empty string.  Why should we even try loading an entity with a blank ID?

For the record, I'm running Debian 9 for my test environment, so PHP 7.0.33 and MySQL 5.5.  The test that fails is **LayoutInterfaceTest**.

**Comment by indigoxela** [comment]
Some digging:

MariaDB (10.3) _does_ allow a query like `SELECT * FROM node WHERE 'nid' in ('')`, so we will never be able to test something in our sandboxes or functional tests. That doesn't mean that we shouldn't fix that bug.

Here's a screenshot of the form this validation applies to (custom contexts):

![screenshot-validation-context](https://user-images.githubusercontent.com/842066/92565973-d401ac00-f27b-11ea-98d5-acc5b19b1a49.png)

I can confirm that the PR prevents the pointless query from running - locally. And it's obvious that the logic is better with `elseif`.

**Comment by quicksketch** [comment]
Thanks! Great work @jlfranklin and @indigoxela! I really appreciate you working to test the new features of 1.17.0 in your work on Silkscreen John. Merged https://github.com/backdrop/backdrop/pull/3297 into 1.x for 1.17.0.
