### ISSUE TITLE
Wrong dialog title "AJAX callback" on form validation errors - custom context form

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4609]
**Description of the bug**

When adding or configuring a custom context, a dialog opens with the title "Add context" or "Configure context".
When the form fails validation and an error message shows up, the dialog title turns to "AJAX callback".

**Steps To Reproduce**

1. Create a layout, add a custom context
2. Make the context validation fail with either an empty value or a non-existent entity ID
3. Check the dialog title

**Expected behavior**

The dialog title shouldn't change on validation errors.

Here's a screenshot:
![screenshot-validation-title](https://user-images.githubusercontent.com/842066/92567996-cd286880-f27e-11ea-94c8-acf04088e8d8.png)

**Additional information**

- Backdrop CMS version: 1.17-preview

---

- <strike>PR by @klonos https://github.com/backdrop/backdrop/pull/3306</strike> (outdated)
- PR by @docwilmot https://github.com/backdrop/backdrop/pull/3309 (set title in layout_context_add_form)

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/3306

**Comment by indigoxela** [comment]
@klonos many thanks for the PR, I'm afraid backdrop_set_title() isn't the right approach here. And it fails in some cases (non-existent file/node id). 

Additionally it doesn't fix the duplicate html id in markup after validation failure.

![double-id](https://user-images.githubusercontent.com/842066/93016123-2cf47b80-f5bf-11ea-8044-37f0270c50d4.png)

**Comment by klonos** [comment]
You're right @indigoxela ...I also just noticed that although the title in the "Add context" validation error is "Add context", for the "Configure context" dialog it changes to "Save context". So grabbing the text from the dialog submit buttons is not ideal 🤔

...seems that my AJAX-fu is weak, so I'm afraid that I don't have any clue how to fix this properly 😓

**Comment by indigoxela** [comment]
> ...seems that my AJAX-fu is weak

Same here... :disappointed: 

But there's also the due day, so a workaround might be better than nothing at all. Here's my [PR](https://github.com/backdrop/backdrop/pull/3307) (also works with translations)

How to test:

- Add a layout
- Open the "Add context" dialog and hit the submit button without setting anything
- Select a type and submit with an empty id form item
- Select a type and submit with a non-existent id
- Save with a real id
- Open the configure form
- Also get the form validation failing

I'm pretty sure that just using backdrop_set_title() isn't the best option here, so if anyone comes up with the proper solution, I'd be glad.

**Comment by docwilmot** [comment]
I dont know *why* this happens, yet, but since the AJAX callback checks the `$form['#title']`, then this will work in `layout_context_add_form()`: set the form title with `$form['#title'] = $is_new_context ? t('Add context') : t('Configure context');`

I could do a PR but out and about today.

**Comment by indigoxela** [comment]
I closed my workaround PR in favor of [this better one](https://github.com/backdrop/backdrop/pull/3309).

Setting the title in function layout_context_add_form() makes more sense. Tested locally and it works fine.

I set the milestone to 1.17.0 - if that's not the right one, feel free to remove it.

For the duplicate html id in markup I'll create a follow-up, as that's unrelated here.

**Comment by klonos** [comment]
Thanks @docwilmot 👍 ...I've tested this and everything works as expected now. RTBC.

Also thanks @indigoxela for opening #4620

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/3309 into 1.x for 1.17.0.
