### ISSUE TITLE
[DX] Add field_get_value() to get single value from field

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#461]
This happens often:

```
  $my_field_items = field_get_items('node', $node, 'field_my_field');
  if ($my_field_items) {
    $my_field_first_item = reset($my_field_items);
    $my_field_value = $my_field_first_item['value'];
  }
```

Since most times you are likely to be checking a single value field, why not make this a core function? Not necessary as is, but something that gets that result.

---
~~PR by @docwilmot https://github.com/backdrop/backdrop/pull/957~~
~~PR by @docwilmot https://github.com/backdrop/backdrop/pull/1758~~
~~PR by @jenlampton https://github.com/backdrop/backdrop/pull/1956~~
PR by @docwilmot https://github.com/backdrop/backdrop/pull/2560

**Comment by quicksketch** [comment]
I left some feedback on @docwilmot's PR at https://github.com/backdrop/backdrop/pull/957.

We'd need some tests on this new functionality, especially considering the number of moving pieces just in getting a consistent value out of an entity (field schema, language, entity info, etc).

**Comment by docwilmot** [comment]
Help wanted:
I copied code to field.test from an existing field test
```
class FieldValueTestCase extends FieldTestCase {
  function setUp() {
    parent::setUp('field_test');

    // Create a field and instance.
    $this->field_name = 'test_field';
    $this->label = $this->randomName();
    $this->cardinality = 4;

    $this->field = array(
      'field_name' => $this->field_name,
      'type' => 'test_field',
      'cardinality' => $this->cardinality,
    );
    $this->instance = array(
      'field_name' => $this->field_name,
      'entity_type' => 'test_field_entity',
      'bundle' => 'test_bundle',
      'label' => $this->label,
      'display' => array(
        'default' => array(
          'type' => 'field_test_default',
          'settings' => array(
            'test_formatter_setting' => $this->randomName(),
          ),
        ),
        'teaser' => array(
          'type' => 'field_test_default',
          'settings' => array(
            'test_formatter_setting' => $this->randomName(),
          ),
        ),
      ),
    );
    field_create_field($this->field);
    field_create_instance($this->instance);

    // Create an entity with values.
    $this->values = $this->_generateTestFieldValues($this->cardinality);
    $this->entity = field_test_create_stub_entity();
    $this->is_new = TRUE;
    $this->entity->{$this->field_name}[LANGUAGE_NONE] = $this->values;
    field_test_entity_save($this->entity);
  }

  /**
   * Test the field_get_value() function.
   */
  function testFieldGetValue() {
    debug(field_get_value($this->entity, $this->field_name));
  }

}
```

Figured I need to test on *any* entity with *any* field. But that simple test is saying `Call to undefined method stdClass::entityType()	`. Is the test entity not a real entity? How do I use this to test this function?

**Comment by quicksketch** [comment]
Thanks @docwilmot the new PR looks great!

Overall I think it's a great improvement. Continuing a question from some months ago, do you think providing a method to do this as well would be a good idea? e.g. `$node->getField('field_body')`? Then we would probably move all this code into the `Entity` class and then just have `field_get_value()` wrap around it. Thoughts?

**Comment by rudiedirkx** [comment]
If you pass in `$single_value = TRUE` for an empty or non-existent field, you get `NULL`, but you're probably expecting an array. That seems strange.

**Comment by docwilmot** [comment]
> you're probably expecting an array

Why expecting an array? Docs say NULL if field doesnt exist, which seems logical no?

**Comment by jlfranklin** [comment]
Including a `field_set_value()` would be even better, but I know that's a lot more complicated.

**Comment by jenlampton** [comment]
> do you think providing a method to do this as well would be a good idea? e.g. $node->getField('field_body')? 

Yes please!!!

**Comment by docwilmot** [comment]
> I would also like to see a matching field_get_values for us poor sobs who have to deal with multi-value fields too, and who also want a handy utility function to help :)

It does that already:

```
@return
 NULL if the entity does not contain the field requested or if the field
 does not contain the key specified in the $key parameter;
 An array of field values if  $single_value parameter is FALSE;
 The first field value  if the $single_value parameter is TRUE.
```

**Comment by jenlampton** [comment]
Hm, that's a bit strange. I think I'd prefer to have two functions, each with guaranteed return data types, than a single one that changes the type based on parameters. I could be persuaded though, I suppose. Are there other functions that do this in core already?

**Comment by jenlampton** [comment]
Descoping from 1.7 since we are 4 days from release.

**Comment by jenlampton** [comment]
I pushed a new PR that adds two functions, with consistent return values. One for `field_get_value()` and another for `field_get_values()` Also added some docs cleanup, otherwise this is much the same. Could use a review if anyone is up for it.

**Comment by jenlampton** [comment]
Since no one has had a chance to look at this since the last update, bumping the milestone. 

I still think this is a great improvement, and would love to see these procedural functions as well as a `$node->getFieldValue('field_body')` and matching `$node->getFieldValues('field_items')` .

**Comment by herbdool** [comment]
I took at look at the code and read through the tests, which seem to cover all the usages. All passing so I think it's RTBC!

**Comment by klonos** [comment]
I agree with the milestone recommendation for 1.13 (assuming that this was the intention, since this is a feature request)

**Comment by quicksketch** [comment]
I've merged @https://github.com/backdrop/backdrop/pull/2560 into 1.x for 1.13 finally. Thanks @docwilmot for your patience on this and taking it to the finish line.

I have one more suggestion that we didn't cover in this issue. We have singular and plural procedural functions (e.g. field_get_value() and field_get_values()) but we only have a plural method `$entity->fieldGetValues()`. Seems like there should be a singular version on the entity as well? I'll make a follow-up issue.

**Comment by quicksketch** [comment]
Follow-up: https://github.com/backdrop/backdrop-issues/issues/3690
