### ISSUE TITLE
Forward slashes and asterisks removed from update hook descriptions

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4610]
https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/node.install#L1992

```php
/**
 * Update the admin content view with new/updated indicators and filter.
 */
```

![Screen Shot 2020-09-09 at 3 58 50 pm](https://user-images.githubusercontent.com/2423362/92601478-886bf400-f2b5-11ea-9b9e-036c8be21d6b.png)

**Comment by indigoxela** [comment]
I guess, [here](https://github.com/backdrop/backdrop/blob/979c9ced6e8baf0e116a04484dbe75c20dd545fb/core/includes/update.inc#L685) it happens.

Hm, that's a bit tricky. This is how the wrapping comment characters get removed.

`str_replace(array("\n", '*', '/'), '', $func->getDocComment());`

**Comment by indigoxela** [comment]
Good point... Play with it, that was only a quick idea - to get improved. :wink:

**Comment by klonos** [comment]
> This: `"\n * "` would remove the leading space...

Using `"\n *"` was also problematic, since it was removing the `*` from the last `*/`, resulting in the last item in the replace array (`'*/'`) to have no effect, and the trailing forward slash to be left in the description. The solution was to change the order of the items in the replace array, so that `'/**'` and `'*/'` are removed first, and all the `"\n *"` are removed last.

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/3299

I ended up replacing `str_replace()` with `preg_replace()`, which allows to define start/end of line in the replacement patterns.

**Comment by BWPanda** [comment]
Made a small suggestion.

**Comment by BWPanda** [comment]
On second thoughts, this regex could be more robust. Currently I don't think it accounts for whitespace, etc. that's outside of our coding standards...

**Comment by BWPanda** [comment]
Here's an updated PR: https://github.com/backdrop/backdrop/pull/4123

It:
- Uses `#` as the regex delimiters (for better readability, since slashes are heavily used in the pattern)
- Allows for 0-or-more whitespace before/after the docblock formatters (to better allow for non-standard formatting)

**Comment by argiepiano** [comment]
Thanks for the PR @BWPanda!

While it fixed the OP problem, I'm finding that the \n character in multiline descriptions is not replaced. The result is that the \n is still included after the replacement.

Try for example the docblock for node_update_1019()

```php
/**
 * Update each content type with new node_preview configuration defaulted to
 * enabled.
 */
```

results in the string "Update each content type with new node_preview configuration defaulted to \n enabled."  (notice the \n)

To test this, run in dpm

```php
$s = "/**\n * Update each content type with new node_preview configuration defaulted to\n * enabled.\n */";
dpm(preg_replace(array('#^\s*\/\*\*\s*#m', '#^\s*\*\/\s*$#m', '#^\s*\*\s*#m'), '', $s ));
```

**Comment by BWPanda** [comment]
@argiepiano I'm not seeing that...

![image](https://user-images.githubusercontent.com/2385329/177060023-65a62cef-aef5-4aed-99e9-f5e6bb2ab559.png)

![image](https://user-images.githubusercontent.com/2385329/177060046-8d052a8a-74a2-45ef-9568-700ef8a39ebc.png)

**Comment by argiepiano** [comment]
You are right. RTBC

**Comment by quicksketch** [comment]
Super! I love this fix. The slight formatting issues on updates has bothered me a for long time. Thanks @BWPanda, @argiepiano, @klonos, and @indigoxela! Merged https://github.com/backdrop/backdrop/pull/4123 into 1.x and 1.22.x.
