### ISSUE TITLE
Fatal error: Unsupported operand types in layout_menu_item.class.inc on line 253

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4611]
I was running the db updates for the PR sandbox in https://github.com/backdrop/backdrop/pull/3274, and I receive this fatal:

> **Fatal error**: Unsupported operand types in **/home/qa/github/backdrop/backdrop/pr/3274/core/modules/layout/includes/layout_menu_item.class.inc** on line **253**

The offending line is https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/includes/layout_menu_item.class.inc#L253 

```php
    $this->contexts += $contexts;
```

Seems to be related to #3750

**Comment by klonos** [comment]
cc @docwilmot

**Comment by klonos** [comment]
Hmm 🤔 ...there's also this:

> Warning: Invalid argument supplied for foreach() in LayoutMenuItem->resetContexts() (line 265 of /home/qa/github/backdrop/backdrop/pr/3274/core/modules/layout/includes/layout_menu_item.class.inc).

**Comment by indigoxela** [comment]
Oh, wait, that sounds familiar... Did you already check https://github.com/backdrop/backdrop-issues/issues/4604?

@jenlampton already provided a PR there.

Any idea how to reproduce it? I wasn't able to, but only tested with a vanilla install.

**Comment by klonos** [comment]
> Oh, wait, that sounds familiar... Did you already check #4604?

Yup. That's a dupe. Sorry 😓 

> Any idea how to reproduce it? I wasn't able to, but only tested with a vanilla install.
