### ISSUE TITLE
Error: Call to a member function init() on null in view->init_localization() on updating core (latest release)

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4626]
**Description of the bug**

This already _did_ pop up in [another issue](https://github.com/backdrop/backdrop-issues/issues/4604#issuecomment-690296336) while testing the preview release, but we missed the actual [root cause](https://github.com/backdrop/backdrop/pull/3132).

**Steps To Reproduce**

1. Install an outdated Backdrop version (like 1.16.2)
2. Enable the locale and language modules and add any language (translations aren't needed)
3. Replace core directory with the one from 1.17.0 (or 1.16.3)
4. Visit the start page or any other page containing a view - **before** flushing caches or running the updater

**Actual behavior**

`Error: Call to a member function init() on null in view->init_localization() (line 2009 of .../core/modules/views/includes/view.inc).`

**Expected behavior**

No error, of course.

Many people probably run the updater immediately after replacing files, but others may not and the site shouldn't look broken then - even if flushing caches fixes the problem.

People who are running core updates via UI won't get that error, neither people who run `drush updb` or `b updb` right after replacing files.

**Additional information**

It's too late for the 1.16.3/1.17.0 releases, but we could fix it for people who didn't update yet.

Possibly by catching it in function init_localization() - if $this->localization_plugin is still NULL, return instead of trying to act on it?

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/3315) that catches the problem.

To test it, follow the steps in the issue description.

**Comment by herbdool** [comment]
I think it looks good I'll test later. Wondering when it'll actually ever be "none"? Maybe that part isn't working?

**Comment by indigoxela** [comment]
> Wondering when it'll actually ever be "none"?

That's an admin setting. Localization can be turned off on admin/structure/views/settings/advanced
Translation method can be "core" or "none". Both ship with views.

In rare cases no localization_plugin is available (file not included) - which leads to the error.
Especially in the latest update, because the file containing that plugins is new.

**Comment by klonos** [comment]
Code looks good, but there's punctuation missing in the inline comments, and they wrap into the next line while more words still fit. Testing on my local next...

**Comment by indigoxela** [comment]
> but there's punctuation missing in the inline comments

Where?

> and they wrap into the next line while more words still fit

One full sentence per line - for readability.

**Comment by klonos** [comment]
> Where?

I'll add comments with suggestions in the PR ...but mostly conditional clauses.

> One full sentence per line - for readability.

Nope. That's been widely used by some devs (the Views module is a huge offender of that), but it's against both Drupal and Backdrop standards. See https://api.backdropcms.org/doc-standards#general (emphasis mine):

> Lines containing comments (including docblocks) **must wrap as close to 80 characters as possible** without going over, with a few exceptions (noted in the Tag Reference below).

**Comment by indigoxela** [comment]
> ... must wrap as close to 80 characters as possible without going over ...

Means: not longer - but shorter is not forbidden.

**Comment by klonos** [comment]
> without going over

^^ _this_ means "not longer"

> as close to 80 characters as possible

^^ this means "fit as many words as possible"

**Comment by indigoxela** [comment]
I disagree but did it.

**Comment by klonos** [comment]
> I disagree but did it.

This means that we need to update/clarify our coding standards wording, so that there is no disambiguation: #4666 ...with #3213 this becomes more important.

**Comment by indigoxela** [comment]
Don't forget to actually _test_ the PR... :smile:

**Comment by klonos** [comment]
Yup, I'm doing that now... 😅

**Comment by klonos** [comment]
...OK, here's what I did:

- `git clone` fresh
- `git checkout 1.16.0`
- install Backdrop
- enable all errors in `admin/config/development/logging`
- enable Language and Locale modules
- add a language
- `git checkout 1.x core`
- visit home page -> error 👎 

Then:

- destroyed my local
- `git checkout -b issue-4626`
- `git fetch origin pull/3315/head:issue-4626`
- `git checkout 1.16.0`
- install Backdrop
- enable all errors in `admin/config/development/logging`
- enable Language and Locale modules
- add a language
- `git checkout issue-4626 core`
- visit home page -> no error 👍

**Comment by klonos** [comment]
Thanks for putting up with my pedantic code-standards compliance comments @indigoxela 🙏 ...this is now RTBC.

**Comment by indigoxela** [comment]
...and too late for 1.17.1 or 1.16. So this fix probably isn't urgent anymore. :disappointed:

**Comment by BWPanda** [comment]
Thanks @indigoxela, @klonos & @herbdool. I've merged https://github.com/backdrop/backdrop/pull/3315 into 1.x and 1.17.x.
