### ISSUE TITLE
When try to install backdrop CMS HTTPS not working in Installation tasks

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4629]
\*\*Description of the bug\*\*

When try to install **backdrop CMS HTTPS not working** in Installation
tasks  
CSS and others file is missing

--  
  \| @import
url("http://www.phalconcms.com/core/themes/seven/css/seven.base.css?");  
  \| @import
url("http://www.phalconcms.com/core/themes/seven/css/style.css?");  
  \| @import
url("http://www.phalconcms.com/core/themes/seven/css/responsive-tabs.css?");

\*\*Steps To Reproduce\*\*

To reproduce the behavior:  
1\\. Go to
https://www.phalconcms.com/core/install.php?langcode=en&profile=standard  
2\\. Click on CSS and File are Missing.  
3\\. Scroll down to '....'

\*\*Actual behavior\*\*

\*\*Expected behavior\*\*

it should be works with SSL and non SSL as same as

\*\*Additional information\*\*

Add any other information that could help, such as:  
- Backdrop CMS version: 1.17.0  
- Web server and its version: Apache  
- Operating System and its version: Redhat 8  
- Browser(s) and their versions:Google Chrome on Gentoo Linux

**Comment by olafgrabienski** [comment]
There's an option to enable HTTPS redirect rules in the .htaccess file, see https://github.com/backdrop/backdrop/commit/c51d971e316a4b45a2521b71930f625488a8bfe0. Have you tried to enable these rules?

**Comment by domaingood** [comment]
@olafgrabienski  I m using basic installer Like Wordpress Drupal all works with http & https. Backdrop CMS also act like that.
Some problem in CSS Linking

**Comment by stpaultim** [comment]
> I m using basic installer Like Wordpress Drupal all works with http & https without change .htaccess. Backdrop CMS also act like that.

Is this true?

On all of my Drupal 7 sites I have been required to make adjustments to the server config or https to direct http traffic to https. On NGINX this requires specific configuration in the block file, on Apache I used to used to make changes to the .htaccess file to force all traffic to https. 

I have been under the impression that this is really a server specific task and that different hosts might handle this differently. We created an install script for our NGINX Linode which does this configuration when we install new sites.

**Comment by indigoxela** [comment]
> I have been under the impression that this is really a server specific task

I'd agree. And also keep in mind that [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) plays an important role.

@domaingood it seems that HSTS isn't enabled for that vhost. Additionally I get an SSL_ERROR_BAD_CERT_DOMAIN for the  certificate on the url you posted (certificate isn't valid for that domain).

To my understanding this isn't a Backdrop issue, but a server setup issue.
