### ISSUE TITLE
Synchronize the width and height values in "Edit image details" dialog when editing dimensions in numeric form items

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4631]
**Description of the need**

It is possible to change the inline image dimensions in the node form in two ways:

1. By dragging the image to the requested size
2. By directly changing the numeric value in form item edit-attributes-width or edit-attributes-height

If using method 1, the dimensions in the form get synced. If using method 2 they're not.

![image-dimensions-form](https://user-images.githubusercontent.com/842066/93746654-c93d0480-fbf5-11ea-94fb-467a697afcc6.png)

Maybe even worse, these values persist even after saving the node, resulting in wrong attribute values in markup.
That's obfuscated by some CSS in, for instance, Basis theme: `img {height: auto;}`

![markup-wrong-dimensions](https://user-images.githubusercontent.com/842066/93746694-db1ea780-fbf5-11ea-9aa7-2a1ad6a9cd79.png)

**Proposed solution**

Some calculation (via javascript), so the dimension values stay synced.
Additionally it would be cool, if the values get inserted automatically when uploading or selecting an image from server. (Not sure it that's possible)

**Alternatives that have been considered**

To get responsive images most themes will use some CSS like `img {height: auto;}`. So browsers will render images correctly.
Providing the right dimensions in attributes seems more accurate, though.

**Comment by olafgrabienski** [comment]
Is this a duplicate of https://github.com/backdrop/backdrop-issues/issues/2054?

**Comment by indigoxela** [comment]
Oh, apparently it is, yes. It would be *very* helpful if someone updated the issue description there (and possibly the title).

Sigh... open since 2016 and no concept for a PR yet...
