### ISSUE TITLE
Date fields never show in localized display formats, always in default formats

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4632]
**Description of the bug**

It is possible to localize date formats so they show up according to the current language (admin/config/regional/date-time).
That works fine for the content overview page (for instance), but this is currently broken for date fields.

**Steps To Reproduce**

1. Enable locale and language module
2. Add a language (no translations needed), set up detection and selection to use path prefix (admin/config/regional/language/detection)
3. Add a date field to a content type
4. Localize your date formats (admin/config/regional/date-time)
5. Create content of that type with a date
6. Visit that node
7. Switch between languages

**Actual behavior**

The configured date display formats per language are ignored. You always only see the default (fallback) format.

**Expected behavior**

Switching between languages should also change the date display format - just like it does in D7.

**Additional information**

This happens in date_format_type_format(), which changed a bit.
Compare the [Backdrop version](https://api.backdropcms.org/api/backdrop/core%21modules%21date%21date.module/function/date_format_type_format/1) with the [Drupal 7 version](https://git.drupalcode.org/project/date/-/blob/7.x-2.x/date.module#L473).

Fun fact: the D7 version seems to be a bit awkward anyway, but works... coincidentally.

If it's unclear what I mean with "switching date display formats", visit the content overview page (admin/content) after localizing your formats - there it works correctly.

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/3317). Comment changes mostly, the actual code change is minimal. (I know, never underestimate a 4-liner :wink: )

**Comment by stpaultim** [comment]
I verified the problem in a local site without the PR, I then tested in the PR sandbox with the instructions provided. This works for me.

**Comment by herbdool** [comment]
I reviewed the code. @stpaultim thanks for testing. I think the code change looks appropriate.

**Comment by BWPanda** [comment]
@indigoxela THere are some test failures, but I can't access them to see if they're related or not. Can you reset the PR to see if that gives us the all green?

**Comment by indigoxela** [comment]
> ...test failures, but I can't access them to see if they're related or not...

Yep, that box is a 404. Tried to turn it off and on again.

**Comment by BWPanda** [comment]
Thanks @indigoxela, @stpaultim & @herbdool. I've merged https://github.com/backdrop/backdrop/pull/3317 into 1.x and 1.17.x.
