### ISSUE TITLE
hook_element_info() has duplicated documentation

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4633]
The documentation for `hook_element_info()` starts like this:

> Allows modules to declare their own Form API element types and specify their default values.
>
> This hook allows modules to declare their own form element types and to specify their default values. The values returned by this hook will be merged with the elements returned by hook_form() implementations and so can return defaults for any Form APIs keys in addition to those explicitly mentioned below.

The first two sentances are basically duplicates. We should remove one.

**Comment by BWPanda** [comment]
Thanks @herbdool. I've merged https://github.com/backdrop/backdrop/pull/3318 into 1.x and 1.17.x.

**Comment by klonos** [comment]
I still have my usual concerns about having long sentences, without any punctuation, but I came late to the party it seems  😅 

https://www.grammarbook.com/punctuation/commas.asp

**Comment by BWPanda** [comment]
@klonos :slightly_smiling_face: New issue?

**Comment by klonos** [comment]
@BWPanda nuh, we'll eventually need to change something else surrounding that function, and I'll fix it then. Not worth it now 😄
