### ISSUE TITLE
Add documentation for `hook_taxonomy_term_page_alter()`.

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4635]
[Line 69](https://github.com/backdrop/backdrop/blob/1.x/core/modules/taxonomy/taxonomy.pages.inc#L69) of taxonomy.pages.inc has this:

> `backdrop_alter('taxonomy_term_page', $build);`

This means that you can implement `hook_taxonomy_term_page_alter()`, however that hook isn't documented. It should be detailed in [taxonomy.api.php](https://github.com/backdrop/backdrop/blob/1.x/core/modules/taxonomy/taxonomy.api.php).

Todo: 

* add an example use of `hook_taxonomy_term_page_alter()` into `taxonomy.api.php`. Here is an example I use in the wild:

```php
/**
 * Implements hook_taxonomy_term_page_alter().
 */
function custom_taxonomy_term_page_alter(&$build) {
  // Remove the list of nodes with this term.
  unset($build['nodes']);
  // Remove the pager for the list of nodes.
  unset($build['pager']);
}

```

**Comment by PadminiRai** [comment]
I'd like to work on this issue.

**Comment by jackaponte** [comment]
Awesome, @PadminiRai! I think you can feel free to assign this ticket to yourself and take a crack at it. Let folks know here if you need any help with it!

**Comment by jackaponte** [comment]
(And thank you for working on it!)

**Comment by PadminiRai** [comment]
Created the pull request.

**Comment by laryn** [comment]
@PadminiRai Thank you! I've made some suggestions in your PR.

**Comment by PadminiRai** [comment]
> @PadminiRai Thank you! I've made some suggestions in your PR.

Got it. Working on it.

**Comment by klonos** [comment]
@PadminiRai thank you for working on this 👍🏼 ...can you please edit the first comment in the PR, to add this?: `Fixes https://github.com/backdrop/backdrop-issues/issues/4635` (that will "link" the PR to this issue here 😉 )

**Comment by laryn** [comment]
LGTM - thanks @PadminiRai

**Comment by BWPanda** [comment]
@PadminiRai I've requested a few changes to bring the code up to standard (I've provided links to our documentation standards where appropriate).

**Comment by herbdool** [comment]
I removed one word from PR "build" as brought up by @BWPanda. RTBC

**Comment by quicksketch** [comment]
Great work @remote007! I merged https://github.com/backdrop/backdrop/pull/3641 into 1.x and 1.21.x. Thanks @laryn, @BWPanda, @jackaponte, @klonos, and @herbdool for the guidance to get this hook documented!

**Comment by remote007** [comment]
Thanks @quicksketch , I look forward to support the community more.
