### ISSUE TITLE
FileAdminTestCase appears three times in file.tests.info

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4636]
We should remove any duplicate references to tests. Note this duplication: https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/tests/file.tests.info#L61

And there's the third one: https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/tests/file.tests.info#L97

```
[FileAdminTestCase]
name = File administration
description = Test file administration page functionality.
group = File
file = file.test
```

Once should really be sufficient. :wink:

**Comment by Ammko128** [comment]
@indigoxela 
Hi, I hope my PR fixes this issue.
I wrote a program in Java that will find duplicate lines in source code containing brackets and "TestCase" and it found another duplicate that I removed from a .test.info file. Can't remember which one. You can see it in commits of my PR.
Have a good day.

**Comment by indigoxela** [comment]
Hi @Ammko128 

> and it found another duplicate that I removed from a .test.info file

Nice catch, right, "CronRunTestCase" also has a duplication.

Many thanks for providing a pull request.

A little tip regarding your [pull request description](https://github.com/backdrop/backdrop/pull/3325): Github has [several keywords](https://docs.github.com/en/enterprise/2.13/user/articles/closing-issues-using-keywords) that automatically links the PR here and closes when it gets merged.

Simply replacing "task done" with "Fixes" does the trick.

**Comment by indigoxela** [comment]
Code looks good, RTBC. :+1:

**Comment by Ammko128** [comment]
Awesome. Thanks for the tip. 👍

**Comment by BWPanda** [comment]
Thanks @Ammko128 & @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/3325 into 1.x and 1.17.x.
