### ISSUE TITLE
Trusted host security setting in Backdrop

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4637]
Not configured less
The trusted_host_patterns setting is not configured in settings.php. It is highly recommended that you configure this to protect your site. See Protecting against HTTP HOST Header attacks for more information.

I don't find settings.php

My Backdrop Info
==============
Info | Backdrop CMS | 1.17.x-dev
Info | Backdrop CMS core update status | No update data available more
Info | MySQL Database | MySQL, MariaDB, or equivalent version 8.0.21
Info | PHP | Version: 7.4.10 (PHP information)
Info | Web server | Apache/2.4.37 (centos) mpm-itk/2.4.7-04 OpenSSL/1.1.1c PHP/7.4.10

**Comment by stpaultim** [comment]
@domaingood - Hopefully this will help. 

You should have settings.php in the root directory of your Backdrop CMS site. Maybe you can provide a little more information. 

![settings_php_—_backdrop](https://user-images.githubusercontent.com/3144571/94054819-bb2be700-fda1-11ea-9095-cdd1c537a197.png)

**Comment by domaingood** [comment]
Ah I got it I missed it
Why setting.php in root Its bad Idea.
Need to make "secure" Directory and" secure" directory must be in 500 like Drupal Does in "sites" Directory and secure/setting.php 444 permission

**Comment by olafgrabienski** [comment]
I guess the question ("I don't find settings.php") is answered ("in the root directory of your Backdrop CMS site"), so closing.
