### ISSUE TITLE
[UX] Rename the "Save roles" button to "Save configuration"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4638]
On the user roles page `admin/config/people/roles` we have a button at the bottom labeled `Save Roles`. This button saves everything on the page -- not just the roles. We've recently moved additional role settings from other places in the admin UI to this page, and neglected to update the `Save` button label.

<img width="1446" alt="Screen Shot 2020-09-23 at 3 33 44 PM" src="https://user-images.githubusercontent.com/397895/94076681-84aa9800-fdb2-11ea-9ee8-bfa62357ef3b.png">

**Comment by stpaultim** [comment]
This PR looks good. Seems to do exactly what was requested. The code is simple enough that I'm tempted to provide code review, but I'm still not sure that I might not be missing something. 

Works for me. 

![Roles___PR_3324_backdrop_backdrop_testing_site](https://user-images.githubusercontent.com/3144571/94101374-50a49680-fdf5-11ea-9f67-5d2d069664d5.png)

**Comment by BWPanda** [comment]
> but I'm still not sure that I might not be missing something

@stpaultim Don't worry about that. A core committer will always look over an RTBC issue before committing it. No one's perfect, but the more eyes on code the better.

**Comment by klonos** [comment]
PR looks good @Ammko128 👍 ...there is something wrong with the tests (it's ZenCI again 😓 - not the PR):

![image](https://user-images.githubusercontent.com/2423362/94193806-7bf0b980-feb9-11ea-8f10-a76500a290ce.png)

@Ammko128, can you please try the following:

- close the PR (temporarily)
- wait 2 minutes or so
- reopen the PR
- allow about 10min for the tests to run again

Thanks 🙏

**Comment by Ammko128** [comment]
@klonos 
Sorry, I didn't respond earlier, I didn't get a notification for your comment even though I'm subscribed to this issue. I did what you asked but that failed test stayed there after reopening the PR and trying to create a new one with same commits. So I just made a new commit and it restarted all tests.
👍

**Comment by klonos** [comment]
Thanks @Ammko128 👍 

Re-tested and re-reviewed ...still RTBC of course 😄

**Comment by BWPanda** [comment]
Thanks @Ammko128 for your work on this! Thanks also to @jenlampton, @stpaultim & @klonos for reporting & testing. I've merged https://github.com/backdrop/backdrop/pull/3332 into 1.x.

**Comment by klonos** [comment]
Thanks @BWPanda ...I've added the 1.18.0 milestone, to denote that this will be in that version. Having said that, this is a UX task, which means that it can be merged in for 1.17.1 as well. Can you do that, or is it too late now?

**Comment by BWPanda** [comment]
@klonos Done.
