### ISSUE TITLE
Configure default date formats based on timezone/country.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4645]
**Description of the need**

As highlighted in https://github.com/backdrop/backdrop-issues/issues/989, we don't have any OOTB date formats that start with the day as is frequently used in European countries.

Available formats seem to be heavily orientated towards users in the USA. 

**Proposed solution**

Add at least one simple date format that starts follows day/month/year format to address this large European format. I recommend:

DD/MM/YYYY

**Alternatives that have been considered**

Users can easier create their own date formats, which is useful because there are so many different options available. 

Given the almost infinite number of possible date formats, I understand that it might be difficult to settle on one date format that is common enough to warrant inclusion in core. But, I think that we should pick the most commonly used European format that starts with the date and include it. 

**Additional information**

"Official EU documents still tend to use DD.MM.YYYY but one document specifies the use of ISO 8601: "Dates should be formatted by the following format: YYYY-MM-DD."
https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe

I would also like a simple MM/DD/YYYY format as well, but agreeing to two new date formats at once is probably unlikely. 

Current options:

![Date___Beetles](https://user-images.githubusercontent.com/3144571/94207487-577ee800-fe8d-11ea-9270-3600aae7d628.png)

Would like the input of other European users on this regarding it's usefulness and/or which specific format would be most useful?

**Comment by stpaultim** [comment]
Adding a date format is probably a good first issue with the caveat that this issue is likely to generate a lot of discussion and may not get resolved quickly (or this idea might easily get dismissed). :-)

However, having a specific PR available to discuss will help push a decision on this issue and the PR can easily be updated or modified as the conversation proceeds.

**Comment by jenlampton** [comment]
I am in support of adding a European date format to core. I would even support adding three (long, medium, and short).

> Would like the input of other European users on this regarding it's usefulness and/or which specific format would be most useful?

Adding needs more feedback label.

**Comment by stpaultim** [comment]
I was specific with the DD/MM/YYYY format in the title, because I think that we already have a single European format. YYYY-MM-DD is (I think) commonly considered a European format (non USA) and is in core already. 
But, the new title works fine too!

**Comment by jenlampton** [comment]
I only abstracted the title because...

> Would like the input of other European users on this regarding it's usefulness and/or which specific format would be most useful?

:)

**Comment by Graham-72** [comment]
Regarding the current options (shown in a comment above) here in the UK we would not be using the 2nd, 3rd or 7th because of the confusion over day and month.
 
We are also more likely to use a hyphen rather than a slash, so d-m-Y would be a useful option to have.

Please keep the option for the site builder to add a custom option. Often we would just use the two digits of the year, e.g. the format d-m-y. Also often we use a full stop as a separator, e.g. d.m.y

**Comment by BWPanda** [comment]
Hmm, interesting topic :slightly_smiling_face: 

Firstly, DMY is not just a European format; it's used practically worldwide (see link below).

Secondly, I did some research and number crunching and, based on what I found, I'd recommend changing the *default* date formats in Backdrop to the one used by the most number of people: DMY!

Here are the number of people around the world (in millions) that use the different date formats:
- DMY: 5,516
- MDY: 584
- YMD: 4,480

(source: https://en.wikipedia.org/wiki/Date_format_by_country#Usage_map)
In my calculations, if an area used two or more formats, I added that population number to each of those formats.

The current default format in Backdrop, MDY, is by far the minority. I vote to remove it as default.

**Comment by domaingood** [comment]
I think All options for date We need add in backdrop.
https://en.wikipedia.org/wiki/Date_format_by_country#Usage_map

**Comment by indigoxela** [comment]
@BWPanda cool, many thanks for that Wikipedia link.

I belief, the issue title needs another update. Something like "Add most commonly used date formats as default options to core".
Only "European" doesn't seem to cover the topic.

> ...is by far the minority. I vote to remove it as default.

As always, when something is already "out there", removal is more difficult compared to addition.

Please keep in mind: we shouldn't bloat the list of default options. Overly long select lists are rather confusing.

**Comment by klonos** [comment]
>I would even support adding three (long, medium, and short).

Yes please 👍 

> ...because I think that we already have a single European format. YYYY-MM-DD is (I think) commonly considered a European format (non USA) and is in core already.

That's not a "human" format - it is an ISO format, so that official documents can easily be sorted properly etc. I could be wrong about other countries, but that format is not common/popular; it seems like a machine format.

> Often we would just use the two digits of the year, e.g. the format d-m-y. Also often we use a full stop as a separator, e.g. d.m.y

Yup, I confirm that that's legit 👍 

> Please keep in mind: we shouldn't bloat the list of default options. Overly long select lists are rather confusing.

As an alternative, we could have a "date before month" checkbox that converts all the options within the dropdown menu that qualify (those that include date and month). I would have to look at the settings though, and think this a bit more thoroughly so that it doesn't end up being odd UI/UX. Perhaps this should be a per-locale setting (? 🤷 ).

PS: I think that we should remove the "good first issue" label from this issue. We shouldn't rush any decision or solution in.

**Comment by stpaultim** [comment]
> PS: I think that we should remove the "good first issue" label from this issue. We shouldn't rush any decision or solution in.

I added the "Good First Issue" tag, because I assumed that this would be a technically easy PR to write and that having a PR sandbox with a first draft might be helpful to move this issue along. 

In my view, having a PR does not necessarily mean we are rushing a decision. Sometimes, it's a great way to move the discussion along. 

If it's easy, I think a good first draft PR would be one that includes three (long, medium, and short) formats starting with the day, month, and then year (in my opinion). I would not assume that this is the final word, just something for folks to look at while discussing it further. 

If this isn't easy, then we should hold off for more information.

**Comment by stpaultim** [comment]
Adding the good first issue, because I think getting a PR for this would stimulate discussion and move us towards a decision.

**Comment by BWPanda** [comment]
I was literally just thinking about this issue today...

**Comment by BWPanda** [comment]
Here's a PR that (for new sites only) adds new default date formats in d/m order, and adds the USA ones (in m/d order) separately: https://github.com/backdrop/backdrop/pull/3992

![image](https://user-images.githubusercontent.com/2385329/158477289-49fb6865-999c-4cbb-aba0-3aeda531571e.png)

**Comment by stpaultim** [comment]
Thanks @BWPanda, this one seems like a easy win. 

Personally, I would remove the time from the short format. I think that the use cases for a showing a date and time are much fewer than the use cases with a time. 

I think that we should have at least one date format with a time on it, but would be happy to simply see the time removed from the short format.

**Comment by jenlampton** [comment]
We need to be careful about removing time from existing formats because there are some places where the time part is mission critical (like on the dblog page). 

If we want to add new formats without time, that's a safer thing to do, because people won't have the same expectations about where they can use "Short" safely.

**Comment by stpaultim** [comment]
> If we want to add new formats without time, that's a safer thing to do, because people won't have the same expectations about where they can use "Short" safely.

Than maybe two "Date only" formats. I almost always create a "Date only" format MM/DD/YYYY for all my sites. We could that and DD/MM/YYY.

**Comment by BWPanda** [comment]
@stpaultim What about also a 'time-only' format? I suspect though with the 'date-only' and 'time-only' ones we're getting too specific for default core functionality. Users can easily add their own formats.

**Comment by stpaultim** [comment]
> What about also a 'time-only' format? I suspect though with the 'date-only' and 'time-only' ones we're getting too specific for default core functionality. Users can easily add their own formats.

I agree that "Time Only" is too specific for core. I seldom need that and rarely see that used on sites. On the other hand, I use "Date Only" far more than all the other time formats combined and I suspect that is true for most people. 

I'm going to do a random check of 5+ sites listed in our showcase right now. 

0) We use a data only format for the showcase itself. 
1) https://www.takemeoutsidensw.org.au/ - Could not find any public facing dates. 
2) https://lynchingsitesmem.org/ - They use the default 'short date' with time for events (this is the most common use case for including a time). They use a day only format on many of their nodes (source date). 
3) https://instituteofandeanstudies.org/ - Could not find any public facing dates.
4) https://procreative.com.au/ - Could not find any public facing dates.
5) https://jukebox-videos-livres.clarus-mons.net/ - Could not find any public facing dates.
6) https://landwirtschaft.ag/news - Date only format. Could not find any dates with times.
7) https://meandtheoperators.ch/aktuell - I see date only formats, no use of dates with time.
8) https://panda.id.au/contact - I see date only formats, no use of dates with time.
9) https://indiana.bank/calendar  - I see date only formats, no use of dates with time.
10) https://thirtyforthirty.packweb.eu/ - Could not find any public facing dates.
11) https://www.rob-tomlinson.com/blog - I see date only formats, no use of dates with time.

Of these 11 random sites and backdropcms.org - 7 had publicly facing dates. All of those with publicly facing dates used "date only" formats, only one used a date + time format, and none used a time only format. 

I think we can safely assume that "time only" is too specific and that "date only" is super common and at the minimum a legitimate possibility for inclusion in core. Personally, if I had to pick one date format to include in core, it would be date only.

**Comment by olafgrabienski** [comment]
> Here's a PR that (for new sites only) adds new default date formats in d/m order
> **Short** 16/03/2022 - 8:37am

If I understand the description correct, the main goal of the issue is to add a common European date format, and I think, most common in Europe for the short format is the usage of dots instead of slashes and a 24 hours time format (with or without leading zero) - see https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe. Proposal for the short format:

`16.03.2022 - 8:37`

**Comment by findlabnet** [comment]
> Proposal for the short format:

I've use `2022-03-16 08:37` - no way to be confused IMHO.

**Comment by stpaultim** [comment]
If most people are more likely to use date formats without a time stamp - which is suggested my informal research above - then it seems if we are not really solving a problem that our users have. Rather, we are just providing a format that allows us to say that we have non-US centric date formats.

Since it's just as easy to edit a US centric date format as a non US centric date format, the only accomplishment here is symbolic. 

If we focus on non US centric date formats, why not provide at LEAST ONE of the three as date only - which appears to be much more commonly used than formats that include a time stamp?

We do not lack data to show that it is much more common to use date only formats. If it would be help, I would be happy to increase the scope of my survey to get more results.

(OK, I will quit complaining about this, because it's much less of a problem since we added the ability to create custom date formats for the "date posted" in the content type UI. Prior to that it really irritated me that I was not given an option of a date format without a timestamp).

**Comment by BWPanda** [comment]
If we add a date-only format, I think we should do it for both regular and US formats. But that'll take us from 3 default formats to 8!

But if we were to implement my suggestion from https://github.com/backdrop/backdrop-issues/issues/4645#issuecomment-1068634607, then we'd only have 4 default formats, yet still be covering most scenarios...

So I might try looking into that possibility.

**Comment by stpaultim** [comment]
Reminder to self - We didn't think to compare how Basis does the same thing, which could be instructive. Let's be sure to check that.

**Comment by indigoxela** [comment]
@BWPanda I actually like the suggestion to add formats based on timezone setting when installing. Usually one of the first things I have to do is to get rid of the US formats, which are unusable here in central Europe. :wink: One concern is, that this may derail this issue.

> We didn't think to compare how Basis does the same thing,

@stpaultim I'm confused, themes don't play any role here, or am I missing something?

**Comment by stpaultim** [comment]
@indigoxela - you are absolutely correct. I posted my comment in wrong issue and have deleted it to avoid further confusion.

**Comment by klonos** [comment]
Just a thought: why aren't we tying various date formats to languages/locales?

In D7, there was the [`system_default_date_formats()`](https://api.drupal.org/api/drupal/includes%21date.inc/function/system_default_date_formats/7.x) function, which returned the available default (not added by the user) formats, and each format array included a `'locales' => array()` in it. For example:

```php
  // Short date formats.
  $formats[] = array(
    'type' => 'short',
    'format' => 'm/d/Y - H:i',
    'locales' => array(
      'en-us',
    ),
  );
  $formats[] = array(
    'type' => 'short',
    'format' => 'd/m/Y - H:i',
    'locales' => array(
      'en-gb',
      'en-hk',
      'en-ie',
      'el-gr',
      'es-es',
      'fr-be',
      'fr-fr',
      'fr-lu',
      'it-it',
      'nl-be',
      'pt-pt',
    ),
  );
  $formats[] = array(
    'type' => 'short',
    'format' => 'Y/m/d - H:i',
    'locales' => array(
      'en-ca',
      'fr-ca',
      'no-no',
      'sv-se',
    ),
  );
```

This function seems to have been completely removed from Backdrop (and D8+), and our default formats (defined in [`system.date.json`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/config/system.date.json)) array doesn't include any locale information. (see #5548)

Perhaps we should revisit/revise this, and allow additional formats to be added automatically, as part of adding more languages to the site, or the defaults specified depending on which language was selected during installation.

I believe that something like that would streamline the process a lot, in a manner that makes sense depending on the locale(s) of each site.

Thoughts?

**Comment by BWPanda** [comment]
Here's a new PR that configures the default date formats based on the chosen timezone/country: https://github.com/backdrop/backdrop/pull/4005

**Default**

![image](https://user-images.githubusercontent.com/2385329/159196428-c11a9324-5045-4c1c-9f59-1573c39547fd.png)

**United States**

![image](https://user-images.githubusercontent.com/2385329/159196485-c90a6789-7d05-4757-8559-1cd77c854c7f.png)

**Comment by stpaultim** [comment]
Thanks for indulging my concerns about "Date Only". 

This is an interesting option, I think. I'd like to test it. 

I am not sure if the PR is broken or if I am misunderstanding how it should work. The sandbox site is set up to use European times, if we go with this approach, it will be important that the site admin can change the setting. I tried changing the country to US and it did not have any effect. 

![image](https://user-images.githubusercontent.com/3144571/159200473-63f4efbd-0921-48f5-924a-40c1ae2ea151.png)

**Comment by BWPanda** [comment]
The PR only changes the *default* date/time formats, it doesn't try to tie them to the country/timezone settings in general. I think if you wanted to do that, you'd need to go down the rabbit hole of making date/time formats have states like 'default' and 'overridden'. Then when you change the country it'd change only the 'default' date formats (not the 'overridden' ones). But I think that's a separate issue. This PR just tries to set sensible default values on install, so that users setting up an Australian website don't have a bunch of US date formats they don't need (and vice versa).

Hope that makes sense.

**Comment by stpaultim** [comment]
@BWPanda - That's makes perfect sense (now that I understand it) and seems like a smart solution. I'm anxious to hear what others have to say.

**Comment by indigoxela** [comment]
@BWPanda many thanks for the alternate PR - tests are currently failing, though.

There's now two patterns (example short), which are both uncommon in central Europe. whether it's `d/m/Y - g:ia` or `m/d/Y - g:ia` doesn't make any difference for us here. We use `d.m.Y - H:i` (24 hour format).
So, TBH, the PR doesn't provide any improvement for us. :wink: But I don't oppose.

**Comment by BWPanda** [comment]
@indigoxela I can add another condition that changes this for Europe, assuming this is common across all of Europe (just targeting Central Europe might not be possible/feasible)... Also ping @klonos @olafgrabienski

**Comment by indigoxela** [comment]
Maybe we should revisit the original task/question: what *are* the most commonly used date formats? :wink: 

Re Europe: @VasasA or @robertgarrigos or @yorkshire-pudding  might want to share their thoughts. I don't actually think that one date format fits all Europe. But the 24 hour format is rather common here - with some exceptions.

**Comment by findlabnet** [comment]
How can people understand: is it January or February - 01/02/2022?

**Comment by BWPanda** [comment]
> what are the most commonly used date formats?

We are doing that, just for different regions of the world 😊

**Comment by VasasA** [comment]
Hungarian formats aren't most commonly used in Europe :thinking:
Short:
```
2022. 03. 21. 9:50
yyyy. mm. dd. hh:mm
PHP: Y. m. j. g:i
```

Medium:
```
2022. már. 21. 9:50
yyyy. mon. dd. hh:mm
PHP: Y. M j. g:i
```
(The month must be written in lower case. )

Long:
```
2022. március 21. 9:50
yyyy. month dd. hh:mm
PHP: Y. F j. g:i
```
(The month must be written in lower case. )

**Comment by yorkshire-pudding** [comment]
> How can people understand: is it January or February - 01/02/2022
If I saw that in the UK on UK paperwork or a UK site, I would know it was February.  If I saw on a US site I would presume it would be January.

@indigoxela - in UK it is typically dd/mm/yyyy with 24 hour time.  Some people use 12 hour with am/pm but it is not a commonly used one in written, though is in speech.  

Long form would typically be as we would say it e.g. "Monday 21st March 2022", possibly with a comma after the day.  Although the date would be as said, the tie written would probably still be 24 hour.

Medium would be dd mmm yyyy, again with 24 hour time.

**Comment by olafgrabienski** [comment]
> I don't actually think that one date format fits all Europe. But the 24 hour format is rather common here

I agree. According to https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe and https://en.wikipedia.org/wiki/Date_format_by_country  `dd.mm.yyyy` seems to be the most common short format in Europe, probably followed by `dd/mm/yyyy`, and the most common time format in Europe seems to be 24 hours. It's however difficult to find information about all Date formats (short, medium, long).

From a European perspective I'm now skeptical to add a format, as no format seems to fit the need of enough people. The current PR might still make sense for English speaking countries outside of the US.

**Comment by indigoxela** [comment]
So, looking again at the previously linked [Wikipedia page](https://en.wikipedia.org/wiki/Date_format_by_country): DMY seems to be a widely used format, with two exceptions: US format is MDY and in China it's probably rather YMD (can anyone confirm the latter?). Re that (besides the various delimiters), the second PR seems like a very good starting point.

The tricky part is the 12-hour vs. 24-hour format problem. That's a [hotchpotch](https://en.wikipedia.org/wiki/File:12_24_Hours_World_Map.svg). Not sure if we could cover that in a comprehensive way.

**Comment by BWPanda** [comment]
PR updated to add European dates (`d.m.Y`) and fix tests.

As for 12/24 hour time, I recommend a new issue to add that option to the installer, then we can tweak the default time formats appropriately.

**Comment by indigoxela** [comment]
> PR updated to add European dates (d.m.Y) ...

Did we have enough consensus for that? `'d.m.Y - g:ia'` ... I doubt it. :grinning: If you add a format specific for Europe, it should be in 24 hour format, otherwise it makes no sense. If you do not want to add any 24 hour format, then adding a format for Europe isn't actually useful. Also, the dots as delimiters maybe aren't optimal. Thoughts?

**Comment by BWPanda** [comment]
I was going off this:

> According to https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe and https://en.wikipedia.org/wiki/Date_format_by_country dd.mm.yyyy seems to be the most common short format in Europe,

and this:

> The tricky part is the 12-hour vs. 24-hour format problem. That's a [hotchpotch](https://en.wikipedia.org/wiki/File:12_24_Hours_World_Map.svg).

Happy to revise if I misunderstood...

**Comment by indigoxela** [comment]
> Happy to revise if I misunderstood...

I'm actually not sure. :grin:

For me (personally), a format like `d.m.Y - H:i` would be optimal, but ...

1. I can't decide that, because I'm one citizen, not a majority in Europe
2. Even if we find the perfect format for Europe - what about Africa, Asia...?

A possible compromise: `d/m/Y - H:i` (slashes as delimiter, but 24 hour format).

If that won't work for enough people/regions, or there are objections, maybe completely skip the addition and only set `m/d/Y` for US and `d/m/Y` for the rest of the world. As it initially was in the second PR.

**Comment by indigoxela** [comment]
@BWPanda I thought it over a bit - if you remove that `elseif (strpos($timezone, 'Europe') === 0) {...` it would "work for me".

A format like `d.m.Y - g:ia` isn't used anywhere in Europe (AFAIK), so adding it doesn't seem to make much sense.

**Comment by BWPanda** [comment]
@indigoxela European formats fixed (PR updated). How's this?

```php
  elseif (strpos($timezone, 'Europe') === 0) {
    config('system.date')
      ->set('formats.long.pattern', 'l, j F, Y - H:i')
      ->set('formats.medium.pattern', 'D, d.m.Y - H:i')
      ->set('formats.short.pattern', 'd.m.Y - H:i')
      ->set('formats.date_only.pattern', 'd.m.Y')
      ->save();
  }
```

**Comment by indigoxela** [comment]
> European formats fixed...

With a pinch of humor: wouldn't you have to "fix European formats" [elsewhere](https://icu4c-demos.unicode.org/icu-bin/locexp)? :smile:

I'll try to give a quick and incomplete overview of commonly used formats:

<details>
<summary>Short datetime formats in several countries</summary>
<pre>
bg
Pattern s: j.m.y \г., G:i
Example s: 27.03.22 г., 14:20

hr
Pattern s: d. m. Y. H:i
Example s: 27. 03. 2022. 14:20

cs
Pattern s: d.m.y G:i
Example s: 27.03.22 14:20

fi
Pattern s: j.n.Y G.i
Example s: 27.3.2022 14.20

fr
Pattern s: d/m/Y H:i
Example s: 27/03/2022 14:20

de
Pattern s: d.m.y, H:i
Example s: 27.03.22, 14:20

el
Pattern s: j/n/y, g:i a
Example s: 27/3/22, 2:20 pm

en-gb
Pattern s: d/m/Y, H:i
Example s: 27/03/2022, 14:20

hu
Pattern s: Y. m. d. G:i
Example s: 2022. 03. 27. 14:20

it
Pattern s: d/m/y, H:i
Example s: 27/03/22, 14:20

nl
Pattern s: d-m-Y H:i
Example s: 27-03-2022 14:20

nb
Pattern s: d.m.Y, H:i
Example s: 27.03.2022, 14:20

pl
Pattern s: d.m.Y, H:i
Example s: 27.03.2022, 14:20

pt-pt
Pattern s: d/m/y, H:i
Example s: 27/03/22, 14:20

ro
Pattern s: d.m.Y, H:i
Example s: 27.03.2022, 14:20

sk
Pattern s: j. n. Y G:i
Example s: 27. 3. 2022 14:20

sv
Pattern s: Y-m-d H:i
Example s: 2022-03-27 14:20

sl
Pattern s: j. m. y H:i
Example s: 27. 03. 22 14:20

sq
Pattern s: j.n.y, g:i a
Example s: 27.3.22, 2:20 pm
</pre>
</details>

Do you see the problem? Most - but not all - use the 24-hour format. Many, but not all use dots as date separator...

That's why I suggested in my previous comment, to not try to fix things for Europe. With all those differences, this can not be done in such a generic way. There's no "one size fits all" for datetime formats.

However, I still support the idea to special-case the US m/d/Y format (by timezone), because that one clearly is only used there. That makes it more likely that for *some* locales the provided d/m/Y format will fit. This is where I see the improvement.

**Comment by BWPanda** [comment]
Ok, point taken. I've removed the European customisations.

**Comment by robertgarrigos** [comment]
In Catalonia and Spain is mainly used ```d/m/Y``` with time in 24h if needed.

**Comment by indigoxela** [comment]
@BWPanda I just realized a possible side effect of your PR: On command line install, people can't set a default country (it's actually empty then), so where previously the US format was in use (m/d/Y), it's now the more generic d/m/Y order. That changes the behavior. Is that OK, or should we also try to catch things for command line install? If so - how?

**Comment by BWPanda** [comment]
I think its OK, since (as discussed above) the US format is in the minority. So on average more people will want to use d/m/Y.

**Comment by stpaultim** [comment]
@BWPanda and/or @indigoxela - Please, make sure I understand the status of this PR correctly. 

As I understand it, this PR basically does two things. 

1) It adds a single Date only date format to core
2) It automatically configures the default date format differently for users based upon Geography. 

If the user is in the USA (based upon browser):

![image](https://user-images.githubusercontent.com/3144571/165689031-36779493-dca5-4066-aba9-fbe4b1402dbc.png)

If the user is anywhere else (based upon browser):

![image](https://user-images.githubusercontent.com/3144571/165689141-1327e1f4-7237-49eb-b1ed-89350a7a7c9e.png)

I'm inclined to mark this "Works for me" - but, I'd like to confirm that my understanding is correct?

Is this a possible candidate for 1.22.0?

**Comment by indigoxela** [comment]
@stpaultim you understand it correctly. One addition: it's not the browser, but the timezone setting on install that controls the date format selection.

Yes, I think this is a possible candidate for 1.22.

**Comment by stpaultim** [comment]
Well, as far as I can tell, it's working as expected.

**Comment by indigoxela** [comment]
I took a final look at the code and consider this RTBC

It's a compromise, of course, but probably the best solution we're able to provide - given the variety of date/time formats out there.

**Comment by quicksketch** [comment]
Thanks everyone! I love the solution to this issue. Clever approach that maintains the current behavior for US-based installations yet makes Backdrop more inclusive/intuitive for a global audience. I've merged https://github.com/backdrop/backdrop/pull/4005 into 1.x for 1.22.0.

https://github.com/backdrop/backdrop/commit/89165d33d8c3caf1cae29d9cea337c4784fb6348 by @BWPanda, @stpaultim, @indigoxela, @Graham-72, @klonos, @olafgrabienski, @jenlampton, @findlabnet, @VasasA, @yorkshire-pudding, @domaingood, and @robertgarrigos.
