### ISSUE TITLE
[UX] Add the date a module was updated to BD website module list

### ISSUE THREAD

**Issue by albanycomputers** [backdrop/backdrop-issues#4651]
**Description of the need**

I had a problem installing a module; the bug was squashed by Jen and updated.  When I looked to reinstall the module I looked on BD website and said it was released in 2015.  This could be misinterpreted by someone as the module being old and outdated and they may not click on the module for more information.  The module was updated on the 25th Sept 2020.

**Proposed solution**

Add the "last updated:" field to the BD website module list summary view.

**Additional information**

Add any other information or screenshots that would help.
![image](https://user-images.githubusercontent.com/1705388/94338368-88742f80-ffe9-11ea-8e9c-271afcc25bd3.png)

**Comment by indigoxela** [comment]
Hi @albanycomputers 
your feature request absolutely makes sense. However, I'm not sure if this is the right issue queue for it.

Can someone point us to the right direction, please?
I'd bet on https://github.com/backdrop-ops/backdropcms.org/issues but could be wrong.

**Comment by BWPanda** [comment]
I think https://github.com/backdrop-ops/backdropcms.org/issues would be the right place for this. I imagine that this new 'updated' date could be obtained from GitHub and that we don't need to add any functionality to core itself to make this possible.

**Comment by klonos** [comment]
Thanks for raising this @albanycomputers 🙏 

Yup, this belongs in https://github.com/backdrop-ops/backdropcms.org/issues, and it's not limited to that specific module. Do you mind opening an issue over in that queue, and then closing this one here?

It seems that this field has the date of the first release of each project (the first time a release was created in GitHub, which is also the first time the project node is created in b.org). Displaying this field next to the most recent release does indeed seem to imply the date of the specific release - not the date of the initial release.

**Comment by stpaultim** [comment]
Good catch. This is very misleading. Let's get this fixed in the backdropcms.org issue queue.

**Comment by BWPanda** [comment]
Made an issue for this in the backdropcms.org issue queue: https://github.com/backdrop-ops/backdropcms.org/issues/709
