### ISSUE TITLE
token_filter causes 500 error when enabled for Plain Text - Text format

### ISSUE THREAD

**Issue by albanycomputers** [backdrop/backdrop-issues#4655]
**Description of the bug**

When enabling "Replace tokens" in the Plain Text Formats it causes a 500 error...  

While I know that adding 'Replace Token' filter to plain text is useless :) It may cause confusion for someone who accidentally adds it... Like me on autopilot lol :) 

Error logs showed...

Got error 'PHP message: PHP Fatal error:  Call to undefined function token_get_entity_mapping() in /public_html/subdomain/2020/modules/token_filter/token_filter.module on line 39\n'

**Steps To Reproduce**

To reproduce the behavior:
1. Go to '/admin/config/content/formats'
2. Click on 'Configure' for plain text format
3. Scroll down to 'Filter settings', 'Filter', click Enable for 'Replace tokens' 

**Actual behavior**

Caused 500 server error.

**Expected behavior**

The token filter should have been ignored or should not be available to add to the Plain Text format.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.17.0

**Comment by klonos** [comment]
Cross-linking some related issues: #1033 #2357 #3363

**Comment by indigoxela** [comment]
@albanycomputers I suspect this is actually a bug in module token_filter.

> PHP Fatal error: Call to undefined function token_get_entity_mapping() in .../modules/token_filter/token_filter.module on line 39

Function token_get_entity_mapping() does not ship with core, neither with the token_filter module, but the module tries to use it.

Here's the related change record:

https://api.backdropcms.org/change-records/token_get_entity_mapping-replaced-by-info-from-entity_get_info

I suggest that you open an issue in the token_filter queue, providing the link to this change record.

**Comment by indigoxela** [comment]
I didn't check if that contrib issue has been created. But as the bug is not in core, I'm closing this one.
