### ISSUE TITLE
CKEditor: Native Markdown Support

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4658]
Native Markdown Support

**Comment by klonos** [comment]
There seem to be 2 addons that provide this functionality in CKEditor 4.x:

https://ckeditor.com/cke4/addon/markdown
https://ckeditor.com/cke4/addon/savemarkdown

What is interesting is the comment in https://stackoverflow.com/questions/22252875/ckeditor-have-it-return-markdown-syntax-instead-of-html by a core developer of CKEditor, saying that this is not a good idea 🤔 (so I'm adding the "contrib candidate" label to this issue)

**Comment by klonos** [comment]
...and there are 2 projects already in contrib that provide markdown support:

https://github.com/backdrop-contrib/markdown
https://github.com/backdrop-contrib/markdowneditor
