### ISSUE TITLE
Mixed use of $config->get and config_get in the same functions

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4664]
**Description of the bug**

From https://api.backdropcms.org/change-records/variableget-variableset-and-variabledel-deprecated-cmi we know that:

> Every time you call config_get() or config_set(), it hits the disk to read/write the file. If you're doing a lot of reads or writes, it's better to do all the reads at once and all the writes at once like this:
> 
> ```
> $config = config('mymodule.settings');
> $value = $config->get('foo');
> ```

Unfortunately, core still have some functions which have multiple occurrences of `config_get` and sometimes mixed use of both `$config->get` and `config_get`. Take, for example, the [system_site_information_settings()](https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.admin.inc#L1200) function. 

It declares `$site_config = config('system.core');` in [the very beginning of the function](https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.admin.inc#L1201), so the content of `$site_config` could be re-used as expected in such lines as `'#default_value' => $site_config->get('site_name')`, `'#default_value' => $site_config->get('site_logo_theme')`, etc. 

However, the same function unnecessarily calls `config_get` multiple times at lines:

https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.admin.inc#L1306
https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.admin.inc#L1326
https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.admin.inc#L1335
https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.admin.inc#L1358

**Expected behavior**

To reduce the overhead, we need to use one read per function instead of multiple reads. 

I haven't analyzed other files, so there could be some other cases of mixed use of two methods in the same core functions. The above case is just what I've noticed in the `system.admin.inc` while working on something else, so I've decided to create a standalone issue for this particular file (system.admin.inc) only.

**Comment by indigoxela** [comment]
@alanmels many thanks for providing a PR. Hint: if you add the text "Fixes [link-to-issue]" to the description of your PR, it gets linked here automatically and closes the issue when merged.
The PR title doesn't work that way, unfortunately.

**Comment by alanmels** [comment]
> @alanmels many thanks for providing a PR. Hint: if you add the text "Fixes [link-to-issue]" to the description of your PR, it gets linked here automatically and closes the issue when merged.
> The PR title doesn't work that way, unfortunately.

Noted, thanks! I believe the PR has picked both issues:

![Screen_Shot_2020-09-30_at_10_05_17_AM](https://user-images.githubusercontent.com/56604405/94709527-034b8c00-0303-11eb-80cd-23185891defe.jpg)

**Comment by klonos** [comment]
@alanmels what @indigoxela was referring to is having a link added in the "Linked pull requests" section of the issue metadata sidebar to the right of this issue here (not the PR). See for example how that works on other issues:

![Screen Shot 2020-09-30 at 7 40 20 pm](https://user-images.githubusercontent.com/2423362/94714487-dde76e00-0354-11eb-9906-301fbf01661a.png)

...that only works if you add those "magic" keywords in the PR:

![image](https://user-images.githubusercontent.com/2423362/94714556-f788b580-0354-11eb-98b5-04293afd856e.png)

**Comment by alanmels** [comment]
@klonos, thanks for the explanation. Edited the PR and hopefully this time it's linked properly.

**Comment by klonos** [comment]
Yup, it worked just fine 😉

**Comment by indigoxela** [comment]
@alanmels Sorry for the delay here.

Although the impact of multiple calls to config_get() per page are mitigated by the static cache in use, it's cleaner to stick with $config->get() in all four functions.

Many thanks for finding and fixing this!

These are the paths to the forms that had mixed usage:

- admin/config/system/site-information
- admin/config/development/logging
- admin/config/media/file-system
- admin/config/urls/settings

It seems that @klonos already confirmed the PR to "look good" - but seems to have forgotten to change the labels accordingly :smile:

There's not much to test here - nothing actually changed in the forms, code *is* looking good, RTBC.

**Comment by BWPanda** [comment]
Thanks for this @alanmels! I love these sorts of PRs that make simple, clean changes with possible performance enhancements :-) Thanks also to @indigoxela and @klonos for testing/review. I've merged https://github.com/backdrop/backdrop/pull/3336 into 1.x and 1.17.x.
