### ISSUE TITLE
Core contains link to drupal.org whereas there is a respective documentation page for Backdrop

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4665]
**Description of the bug**

If you go to `/admin/config/media/file-system` of your Backdrop site and click on the `more information about securing private files.` link then you'll be re-directed to https://www.drupal.org/docs/7/core/modules/file/overview. That's because  the [line 1807](https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.admin.inc#L1807) of system.admin.inc looks like:

`    '#description' => t('An existing local file system path for storing private files. It should be writable by Backdrop and not accessible over the web. See the online handbook for <a href="@handbook">more information about securing private files</a>.', array('@handbook' => 'https://www.drupal.org/docs/7/core/modules/file/overview')),`

However, we already have the same documentation page for Backdrop at https://backdropcms.org/user-guide/file-system, so it would be really nice to cleaning up such links to Drupal.org if we do have the respective documentation pages for Backdrop.

**Comment by indigoxela** [comment]
@alanmels does this issue actually have a pull request? You linked this issue in https://github.com/backdrop/backdrop/pull/3336, with the "Fixes" keyword, so it's referenced here and will close this issue when merged.

But that PR has nothing to do with urls. Mind to remove the unrelated link in your PR?

**Comment by klonos** [comment]
@indigoxela the actual change is this line: https://github.com/backdrop/backdrop/pull/3336/files#diff-c518400aff0cb1100d3ceafbbe3514bf2f2a7d1249c126776e21b63ae9f62946R1810

@alanmels also replaced multiple calls to instances of `config_get('system.core', ...)` with `$config->get(...)` instead, which I find an improvement (less config file reads).

**Comment by klonos** [comment]
...the URL bit is fixed. Leaving the "needs code review" label, as others my feel that this is scope creep, and would prefer the `config_get()` fixes to go in a separate issue.

**Comment by alanmels** [comment]
Sorry I had put two different issue fixed into a single PR thinking the URL-fix was minor and could go in together with the rest of PR. It's not now clear to me should I edit the PR and create another one for URL-part or is the current one is good enough?

**Comment by stpaultim** [comment]
I'm a little confused about whether this issue was supposed to be closed?

**Comment by BWPanda** [comment]
Oops, nope. Happened automatically because this issue was mistakingly linked in a PR.

**Comment by klonos** [comment]
It should be closed. That PR fixed the link: https://github.com/backdrop/backdrop/pull/3336/files#diff-c518400aff0cb1100d3ceafbbe3514bf2f2a7d1249c126776e21b63ae9f62946R1810

😉

**Comment by BWPanda** [comment]
Oh right, missed that, sorry.

**Comment by indigoxela** [comment]
:rofl: I'm not the only one who got confused by the "one PR fixes two issues" thing.
