### ISSUE TITLE
Code inside update_module_enable is never run

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4667]
While reading this function code (for something unrelated), I realized that a small part of function update_module_enable can't ever run:

```
    $function = $module . '_schema_0';
    if (function_exists($function)) {
      $schema = $function();
      foreach ($schema as $table => $spec) {
        db_create_table($table, $spec);
      }
    }
```
I don't think that there is a `mymodule_schema_0()` anywhere in Backdrop.

Here's a [link to the code](https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/includes/update.inc#L344)

Maybe related: https://www.drupal.org/project/drupal/issues/1929816

And this maybe explains [comments like this one](https://github.com/backdrop/backdrop/blob/f12660fd62fbdbd507bdf8b89deec086d4db9b6d/core/modules/system/system.install#L1814)

I wonder how this could get solved. I don't fully get that schema_0 thing. Simply switching to `$module . '_schema'` (hook_schema, no zero) could be a solution but requires updating existing hook_update_N code.

Simply dropping that broken code could be another solution, possibly the simpler one.

**Comment by klonos** [comment]
Hmm 🤔 ...this comment in the d.org issue makes me have second thoughts re removing that code:

> This was originally a critical upgrade path issue due to the unpredictability of using hook_update_N() to enable modules during major upgrade. However now that major upgrades are handled by the migration API, we can relax things for minor updates.

AFAIK, we'll never have a major upgrade till Backdrop 2.0, but is upgrading from D7 to Backdrop 1.x a major upgrade? Would things break for that then?
