### ISSUE TITLE
Random tokens are missing

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#4672]
**Description of the bug**

Drupal 7 (with the Token module installed) provides "Random" tokens like `[random:number]`. Backdrop has integrated tokens but without the Random ones. They should be added to Backdrop, in my opinion.

The Drupal implementation of Random tokens
- https://git.drupalcode.org/project/token/-/blob/7.x-1.x/token.tokens.inc#L346
- https://git.drupalcode.org/project/token/-/blob/7.x-1.x/token.tokens.inc#L877

**Comment by docwilmot** [comment]
Are those in D8 core? Would make a simple contrib module I'd think. Doubt its a commonly used feature.

**Comment by olafgrabienski** [comment]
I find them useful but I guess a contrib module would also be okay. (For the time being, I have a custom one.) Not sure about the best contrib approach. One module per missing token seems odd. To integrate in core could be more easy and wouldn't do any harm, would it?

However, yesterday @klonos` suggested in Zulip:

> ..if these tokens were in the 7.x Token module and not in Backdrop, then they should be. Can you please open an issue for it if that's the case

https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Random.20token/near/211789941

**Comment by catorghans** [comment]
> I find them useful but I guess a contrib module would also be okay. (For the time being, I have a custom one.) Not sure about the best contrib approach. One module per missing token seems odd. To integrate in core could be more easy and wouldn't do any harm, would it?
> 
> However, yesterday @klonos` suggested in Zulip:
> 
> > ..if these tokens were in the 7.x Token module and not in Backdrop, then they should be. Can you please open an issue for it if that's the case
> 
> https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Random.20token/near/211789941

Can you share your custom one?

**Comment by olafgrabienski** [comment]
> Can you share your custom one?

Sure (attached below), hope it helps!

[custom_random_tokens.zip](https://github.com/backdrop/backdrop-issues/files/8677731/custom_random_tokens.zip)

**Comment by indigoxela** [comment]
> Are those in D8 core? Would make a simple contrib module I'd think.

@docwilmot I did a quick check of D9 - they don't ship with the core, but with the contrib module. So we might do the same or get it into Backdrop core for BC.

> One module per missing token seems odd

@olafgrabienski I agree. Does anyone here know, which other tokens (types) aren't in core, but shipped with Token in D7.

If it's really only the random tokens, I'd recommend to put them in core (that's just a few lines of code). If there are several missing, we could combine them in a contrib module - if we agree on that.

You might have guessed - I'm using random tokens in a project and if they're in core, the upgrade might get easier.

**Comment by nattywebdev** [comment]
Would be great to have this custom module as a contrib module, at least so I can remember where to find it next time I need it! Thank you @olafgrabienski

**Comment by olafgrabienski** [comment]
> Would be great to have this custom module as a contrib module

At the moment, I don't have the time to publish the custom module as a contributed one, and I still think random tokens should be integrated into core (for convenience, and for easier updates from Drupal 7). That said, I wouldn't object if anyone else published it as contrib module.

**Comment by kiamlaluno** [comment]
I agree with @olafgrabienski: At least for sites migrating from Drupal 7, that token could be helpful.  

It is also true those tokens are defined by a contributed Drupal 7 module, which means only the Drupal 7 sites with the Token module rely on those tokens. Since the Token module in BackDrop is part of core, those tokens should be defined in core.

**Comment by indigoxela** [comment]
My interpretation of recent comments here is, that adding random tokens to core is preferred.

Here's a [PR](https://github.com/backdrop/backdrop/pull/4595) that provides that. Probably the easiest way to test is to use the PR sandbox, and play with node alias patterns.

**Comment by nattywebdev** [comment]
Thank you @indigoxela - I've done a little testing and recorded it as comments on your PR. 
If this feature can be included in core it would be marvellous - not to mention the time-saving in hunting down this issue!

**Comment by indigoxela** [comment]
@nattywebdev many thanks for testing, I'm setting labels accordingly (assuming that you don't have permission to do so - or, do you?).

**Comment by argiepiano** [comment]
Thank you for providing a PR, @indigoxela, and for testing, @nattywebdev. I've reviewed the code, and it LGTM. This is RTBC.

**Comment by nattywebdev** [comment]
> @nattywebdev many thanks for testing, I'm setting labels accordingly (assuming that you don't have permission to do so - or, do you?).

Absolutely not - I'm too ignorant to be let loose on anything important!

**Comment by quicksketch** [comment]
Thanks folks for the renewed interest in this issue (and @olafgrabienski for filing it back in 2020). I agree with others that a missing token from D7 is a bug, as it could disrupt upgraded sites. The PR looks good to me too and matches the D7 implementation.

I merged https://github.com/backdrop/backdrop/pull/4595 into 1.x and 1.26.x. Thanks everyone!
