### ISSUE TITLE
[UX] install.php: Provide help text for site name

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4675]
**Description of the need**

During Open Source Day today, two participants both mentioned uncertainty over what was required for site name during installation. They weren't sure if there was something specific that was required in this field. 

I think that having "localhost" here as default (when installing locally) is confusing.

![Configure_site___Backdrop_CMS](https://user-images.githubusercontent.com/3144571/94880569-f1640900-0428-11eb-97b7-0b85583411e4.png)

**Proposed solution**

Add some help text for this field that says something to the effect of:
"Your chosen name for this website, this can be changed later." 

**Alternatives that have been considered**

Adding a default name (placeholder) that reads something like "My Site" or "My Backdrop Site."
See: https://github.com/backdrop/backdrop-issues/issues/2291

I think that placeholder text might help demonstrate the intention for this field.

**Comment by klonos** [comment]
Talking about small things that experienced Drupal/Backdrop users have gotten used to over the years, but are actually not straight-forward to others ...we should definitely fix this 👍

My preference would be the default value of this field (not a placeholder - an actual value), so that people can skip having to enter something, and proceed with the installer without any "field is required" errors (think "finish faster" if the goal is to quickly set up a test site). I personally like the "My Backdrop site" recommendation.

**Comment by indigoxela** [comment]
Currently the domain name gets pre-filled in that field.

I understand that this is confusing, if the domain is "localhost" (some testing box). And it also might not be the best choice on real domains. "My Backdrop site" seems like a good option, although very generic. Are there other suggestions?

**Comment by Nimisha94** [comment]
I think something like "Enter your website name here" as a placeholder would be good too. I also like the "My Backdrop site" suggestion.

**Comment by jlfranklin** [comment]
This would be a good place to put an [info cirlcle](https://wikimania2014.wikimedia.org/wiki/File:Info_sign_font_awesome.svg) that triggers a pop-up with more details.   Drop could appear in the pop-up explaining with a dragon-themed example. What kind of a site would Drop make?  

> When I made a site for a Swiss sci-fi & fantasy book club, I called it "Dragon Readers of Bern."

**Comment by BWPanda** [comment]
@jlfranklin That sounds like a whole other issue (help text popups with a mascot) 😄 But I kinda like it.

As for this issue, I agree that the domain name is not a good default value, and I think finding a better one would negate the need for more help text. I'm happy with "My Backdrop Site" (I even thought of that myself before scrolling down to see others had suggested it too 😊).

**Comment by BWPanda** [comment]
BTW, and maybe slightly off-topic, what's the thing on the right of the 'Site name' field in the screenshot?

**Comment by jlfranklin** [comment]
> That sounds like a whole other issue (help text popups with a mascot) :smile:  But I kinda like it.

Opened #4680 to discuss it.

**Comment by stpaultim** [comment]
> BTW, and maybe slightly off-topic, what's the thing on the right of the 'Site name' field in the screenshot?

This icon is from LastPass browser plugin. I should remove that from screenshots to avoid confusion. Good question.

**Comment by RakeshPotnuru** [comment]
Can I go ahead with this? Domain autofill looking fine instead of placeholder, adding help text will be enough.

**Comment by RakeshPotnuru** [comment]
@BWPanda 
Guest?

**Comment by BWPanda** [comment]
So did we decide in this issue to:
- Add a field description,
- Add placeholder text (and remove the default value), or
- Change the default value?

**Comment by RakeshPotnuru** [comment]
My vote is for both 1 and 2

**Comment by BWPanda** [comment]
Here's a simple PR: https://github.com/backdrop/backdrop/pull/4119

![image](https://user-images.githubusercontent.com/2385329/176895021-5dea39b3-9d1c-4019-8c2e-80674c844736.png)

**Comment by indigoxela** [comment]
A quick question: site_name is translatable - is it planned to also translate that "My Backdrop Site" to other languages by default? People may install in a different language (currently not super-easy, but possible). On the other hand - nobody would leave the default as-is, so the translation is only useful once and for a short time. :wink:

**Comment by BWPanda** [comment]
@indigoxela I'm confused... The PR's code has: `st('My Backdrop Site')`, so it *is* translatable. Unless you're saying it shouldn't be...?

**Comment by indigoxela** [comment]
I see, my comment was confusing. :wink:

Yes, sure, it *is* translatable. But should core translations translate it? It's not about your code, it's about: "should core translators translate "My Backdrop Site", so someone installing B in another language, for example German, they'd see "Meine Backdrop Seite" instead of the English text?

**Comment by BWPanda** [comment]
Ah, I see.

I'm not a translator, and I only know/speak one language (for all intents and purposes), so take this with a grain of salt... But I'd say yes.

When I have visited websites in other languages, and used their built-in English translation, it's so annoying when some text still appears in the native language.

So yeah, I'd say translate it for a fuller experience.

**Comment by stpaultim** [comment]
I downloaded the branch and spun up a fresh site in my local environment. This very simple PR seems to work as expected. 

I think it's an improvement. 

As far as I understand it, the decision on whether or not to translate this string is ultimately up to the translator. I am happy to leave that decision to them. I can envision that in some languages it might make sense to leave it as it is and it others it might be easily translatable. 

Works for me.

**Comment by quicksketch** [comment]
Thanks folks! I retitled the issue to the end-solution. I merged https://github.com/backdrop/backdrop/pull/4119 into 1.x and 1.22.x.

I wasn't sure about this being a 1.22.1 item or 1.23.0. But as this was labeled a bug fix and UX improvement, I figured pulling it into 1.22.x was fine. Thanks all!

**Comment by jenlampton** [comment]
Removing the feature request label because the PR that was merged included only a fix to the current system.
