### ISSUE TITLE
Layouts: the 'View page' link on the Manage Blocks page should just be the path from the layout

### ISSUE THREAD

**Issue by bradbulger** [backdrop/backdrop-issues#4678]
The 'View page' button on the Manage Blocks page of a layout was added by #4370. It adds a link to the path from $layout->getPath(). The 'href' value used is being run through url(), which prefixes it with the base path. In sites with more of a base path than "/" this results in a bad link. The 'href' value should be an internal URL, as it will be run through url() again during rendering.

**Steps to reproduce**

1. Install Backdrop in a subdirectory, for instance /backdrop
2. Go to any layout, for instance /backdrop/admin/structure/layouts/manage/home
3. Follow the "View page" link

**Result**

`The requested page "/backdrop/backdrop/home" could not be found. `

Note the duplication of `base_path`.

**Comment by indigoxela** [comment]
Nice catch, confirmed.

The links get run through `l()` in function theme_links(). That's why the call to `url()` isn't necessary - and breaks things for Backdrop installs in a subdirectory.

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/3353) which removes the redundant call to `url()`.

**Comment by stpaultim** [comment]
I need some hints on how to test this. How do I create a path where this does not work so I can verify the fix?

**Comment by bradbulger** [comment]
It's dependent on the base_path of the installation being more than "/". Can you simulate that in testing? 
If your site is at eg https://my.server/path/to/backdrop than the link will be wrong for any layout.

**Comment by indigoxela** [comment]
@stpaultim I updated the issue description to give more detailed instructions.

**Comment by stpaultim** [comment]
I guess I was hoping there was a way to test this in the PR sandbox. I will test this later in local installation. Thanks for instructions, that helps.

**Comment by klonos** [comment]
@indigoxela can you please refresh the PR sandbox?

**Comment by indigoxela** [comment]
> can you please refresh the PR sandbox?

@klonos Sure, I tried to turn it off and on again... :grin:

**Comment by klonos** [comment]
Thanks @indigoxela 🙏 ...that has fixed the tests, but the sandbox still get you to that drupalhosting.ru page 😞 

![image](https://user-images.githubusercontent.com/2423362/95193384-6a25e500-07dc-11eb-99f3-a24eca5a0461.png)

**Comment by indigoxela** [comment]
Hm. Seems to work now... http://3353.backdrop.backdrop.qa.backdropcms.org/ - could it be that the browser cache tricks you?

**Comment by klonos** [comment]
Yup. Twas cache. All good now 👍

**Comment by stpaultim** [comment]
I set up two local versions of the site, one with the PR and one without. I set the path in each to include a sub-directory such as: 

localhost:32781/subdirectory/backdrop-root

I was able to confirm that the "view page" link did not work on layouts without the PR, but did work with the PR.

**Comment by quicksketch** [comment]
Thanks folks! Looks great. I've merged https://github.com/backdrop/backdrop/pull/3353 into 1.x and 1.17.x.

Thanks @indigoxela, @klonos, @bradbulger, and @stpaultim!
