### ISSUE TITLE
Dashboard test looks for hardcoded relative paths so fails in subdirectories

### ISSUE THREAD

**Issue by bradbulger** [backdrop/backdrop-issues#4686]
This line from dashboard.test

`$disable_link = $this->xpath('//a[starts-with(@href, "/admin/structure/layouts/manage/dashboard/disable")]');`

will fail on an installation running in a subdirectory - eg https://my.server/my/testing/backdrop/.

It needs to be run through url().

**Comment by bradbulger** [comment]
I added a [PR](https://github.com/backdrop/backdrop/pull/3360) to fix this. Note that the Dashboard test will still fail because of #4656. Only the combination of this fix and that one gets the Dashboard test to run without failures in a subdirectory.

**Comment by indigoxela** [comment]
Wouldn't it be easier in this case to use [base_path()](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/base_path/1) directly? Function [url()](https://api.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/url/1) does so much more, and the only thing needed here is the base path.

I suggest that because test performance (and resource usage) is always something to keep an eye on.

Example:
`$disable_path = base_path() . 'admin/structure/layouts/manage/dashboard/disable';`

**Comment by bradbulger** [comment]
That seems right. Can I just update this existing PR or do I need to close it and make a new one?

**Comment by indigoxela** [comment]
> Can I just update this existing PR or do I need to close it and make a new one?

Add as many commits as you need to your existing PR, no need to start fresh.

**Comment by bradbulger** [comment]
That's done, then.

**Comment by indigoxela** [comment]
> That's done, then.

Yay, code looks good! :+1: 

I have two more requests regarding your PR, unrelated to code:

1. The title of your PR doesn't describe anymore what it actually does. Mind to update it?
2. ZenCI messed the test run (this sometimes happens) - to fix it, we usually "turn it off and on again", means we close the PR, wait _several_ minutes, and then open it again (sorry for the inconvenience).

**Comment by bradbulger** [comment]
I tried renaming it - let me know any suggestions, what I came up with feels awkward.

Are you talking about the automated zenci/test/php53 and zenci/test/php70? My impression has been that those always fail but it seems like it's for unrelated reasons.

**Comment by indigoxela** [comment]
> zenci ... My impression has been that those always fail but it seems like it's for unrelated reasons.

Not always, but way too often. :disappointed:

Anyway, code is looking good, tests are passing, PR description fits - RTBC.

As I was the one who added label "milestone candidate - bug", someone else should set the actual milestone.

**Comment by BWPanda** [comment]
Looks good to me too!

**Comment by BWPanda** [comment]
Thanks @bradbulger for reporting *and* fixing this! And thanks @indigoxela for the support and testing. I've merged https://github.com/backdrop/backdrop/pull/3360 into 1.x and 1.17.x.
