### ISSUE TITLE
Basis pager ellipsis colour

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4695]
**Description of the bug**

The colour of the ellipsis in Basis' pager is the same as the pager background colour and so isn't visible:

![image](https://user-images.githubusercontent.com/2385329/95705994-5af1dc00-0ca1-11eb-9d48-ffb7b15bad28.png)

**Steps To Reproduce**

To reproduce the behavior:
1. Use Devel Generate to create lots of Post nodes
2. Scroll to the bottom of the homepage to see the pager

**Actual behavior**

Ellipsis is present, but the same colour as the background and so not actually visible.

**Expected behavior**

Ellipsis is coloured white, like the other pager links.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3367

It seems the ellipsis, like everything else in the pager, was coloured white, but then right below that the pager alone was set back to the background colour... Not sure why.

**Comment by indigoxela** [comment]
That extra css obviously slipped in by mistake.

PR works like a charm in the [sandbox](http://3367.backdrop.backdrop.qa.backdropcms.org/). Tested with several color sets.

It's a small change, RTBC.

**Comment by quicksketch** [comment]
Thanks @BWPanda and @indigoxela! Merged https://github.com/backdrop/backdrop/pull/3367 into 1.x and 1.17.x.
