### ISSUE TITLE
What's up with Pager calculations?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4697]
In [`theme_pager()`](https://api.backdropcms.org/api/backdrop/core%21includes%21pager.inc/function/theme_pager/1) there are various 'markers' that are calculated to help with theming the pager:

- `$quantity`
- `$pager_middle`
- `$pager_current`
- `$pager_first`
- `$pager_last`
- `$pager_max`

And I'm a bit confused by some of them... Here's an example:

![image](https://user-images.githubusercontent.com/2385329/95709031-7f51b680-0ca9-11eb-87d3-a6e52d2aa1b2.png)

I setup a view with 12 pages of content, then went through each page to see what each of the 'markers' were...

`$quantity` is always `9`. This seems to be the number of 'numbered' links in the pager (i.e. ignoring the 'first', 'previous', 'next', etc. links) :+1: 

`$pager_middle` is always `5`. This seems to be the number of the 'numbered' link (counting from the left) that is the middle one. :+1: E.g.:
![image](https://user-images.githubusercontent.com/2385329/95709299-1585dc80-0caa-11eb-8ce4-5f3568eb805e.png)

`$pager_current` changes and is always the current page I'm viewing, i.e. the highlighted one :+1: 

`$pager_max` is always `12`. This seems to be the total number of pages :+1: 

`$pager_first` and `$pager_last` is where it gets weird... Here are their values when I'm on each page of results:

- Page 1: `$pager_first = -3` `$pager_last = 5`
- Page 2: `$pager_first = -2` `$pager_last = 6`
- Page 3: `$pager_first = -1` `$pager_last = 7`
- Page 4: `$pager_first = 0` `$pager_last = 8`
- Page 5: `$pager_first = 1` `$pager_last = 9`
- Page 6: `$pager_first = 2` `$pager_last = 10`
- Page 7: `$pager_first = 3` `$pager_last = 11`
- Page 8: `$pager_first = 4` `$pager_last = 12`
- Page 9: `$pager_first = 5` `$pager_last = 13`
- Page 10: `$pager_first = 6` `$pager_last = 14`
- Page 11: `$pager_first = 7` `$pager_last = 15`
- Page 12: `$pager_first = 8` `$pager_last = 16`

I don't understand these numbers, nor do I understand the comments in the code: "first/last is the first/last page listed by this pager piece (re quantity)"...

Is someone able to explain this?

**Comment by indigoxela** [comment]
This is the Drupal issue causing that very old code: https://www.drupal.org/project/drupal/issues/135931

I can't explain either. :confused:

**Comment by quicksketch** [comment]
There's no doubt that the pager code is terribly confusing. Reading over it a bit... I think `$pager_first` and `$pager_last` indicate that page number at the extremities of the lowest page number shown and the highest page number shown.

In the case where `$quantity` is `9` and you're on page 5 for example, you listed the following values:

```
Page 5: $pager_first = 1 $pager_last = 9
```

So the first link shown goes to page 1 and the last link shown goes to page 9. Makes sense.

But it gets messy when you're less than 5 pages from either the first or last page of results. You end up with negative numbers that are ignored, or you have higher numbers than the maximum page count, which are also ignored.

**Comment by BWPanda** [comment]
Thanks for the explanation @quicksketch. Makes (a bit) more sense now :slightly_smiling_face:
