### ISSUE TITLE
Fix references to node language fields in Views when updating from Drupal 7

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4698]
**Description of the bug**

When updating from Drupal 7 Views, old fields and filters in the updated views, still refer to "language" instead of "langcode".

**Steps To Reproduce**

To reproduce the behavior:
1. Set up a Drupal 7 site with language and node translation and Views.
2. Create a view with a language field, language filter.
3. Set up a Backdrop site and update the D7 database.
4. Visit the view config of the view created in D7.

**Actual behavior**

Get a broken array/field/filter.

**Expected behavior**

Fields and filters should be using "langcode" instead of "language".

**Comment by indigoxela** [comment]
Almost...

I followed your steps, but also added a relationship to translations in my Drupal view.

Everything went smoothly, the view with the language fields was broken as expected.

Then I applied the change and ran the db update. The view was still broken because of the translation relationship.

Screenshot:
![screenshot-broken-view](https://user-images.githubusercontent.com/842066/96336157-e2629500-107d-11eb-8769-03b66e44237f.png)

Here's the broken view export for further testing (had to change the extension to upload it):
[language-test-view.json.txt](https://github.com/backdrop/backdrop-issues/files/5395563/language-test-view.json.txt)

**Comment by indigoxela** [comment]
Ah, [there](https://github.com/backdrop/backdrop/blob/14dfd0edd4482184abc68a60ee7dfa87b95e8002/core/modules/translation/views/views_handler_relationship_translation.inc#L67) it is. :wink:

**Comment by herbdool** [comment]
I think we can ignore the relationship for this issue.

What do you think of the code? Do you want to review it too?

**Comment by indigoxela** [comment]
As #4513 has been merged in the meantime, I did a quick check with my "bdroptesting-drupal-prep.sql" from yesterday. This time everything ran smoothly out-of-the-box.

> Do you want to review it too?

Sure. The code's looking good.
And the place is correct, too. For a moment I was thinking about combining it with the update hook where all views get converted from db to json, but realized that it wouldn't make sense.
The update hook's only needed if the Translation module (which is the one that ships with all the related views handlers) is on.

RTBC from my side.

**Comment by quicksketch** [comment]
Thanks @indigoxela and @herbdool!

I think we need a [`hook_update_dependencies()`](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_update_dependencies/1) in `translation.install` to ensure that `views_update_1001` has already run -- that's where Views are converted from the database to config. In coming from Drupal 7, updates are run in a calculated order with dependencies. While it works currently, it might just be luck that Views module is running updates before Translation module is.

**Comment by herbdool** [comment]
@quicksketch thanks for the tip. I've added the dependencies hook.

**Comment by indigoxela** [comment]
> I've added the dependencies hook.

Looks good. And with hook_update_dependencies() we're on the safe side.

**Comment by BWPanda** [comment]
Thanks @herbdool for the issue and PR, and to @indigoxela & @quicksketch for reviews/testing. I've merged https://github.com/backdrop/backdrop/pull/3372 into 1.x and 1.17.x.
