### ISSUE TITLE
Relationship handler for translations should be using langcode instead of language

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4699]
**Description of the bug**

In `views_handler_relationship_translation.inc` the options for the relationship should be using `'field' => 'langcode'`.

**Steps To Reproduce**

To reproduce the behavior:
1. Enable node translations
2. Create a view with the Content translations relationship.

**Actual behavior**

Get this error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'node_node.language' in 'on clause'

**Expected behavior**

No error.

**Comment by herbdool** [comment]
@indigoxela wondering if you'd be able to test/review. Fairly simple fix I think.

**Comment by indigoxela** [comment]
@herbdool you missed this issue: https://github.com/backdrop/backdrop-issues/issues/4513 where I provided a PR with the exact same fix. :rofl: 

So, not only the issue is a duplicate, but also the PR.

You could test/review the original PR.

**Comment by herbdool** [comment]
Oops!
