### ISSUE TITLE
hardcode the config directory names during install (not based on the database connection info)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#470]
I don't know if I have done some unholy thing here, but...

I had a local dev environment with my mysql root password blank. I've setup a fresh installation of Backdrop and at some point later on I've set a password for mysql root.

My settings.php while the mysql password was blank was:

```$database = 'mysql://root:@localhost/backdrop';```

So when I test my installation after the password (re)set I naturally get:

```
Error
The website encountered an unexpected error. Please try again later.

PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) in lock_may_be_available() (line 167 of C:\www\backdrop\core\includes\lock.inc).
```

So, I've changed my settings.php to include the password:

```$database = 'mysql://root:password@localhost/backdrop';```

Page refresh, aaand...

```
Fatal error: Call to undefined function menu_get_custom_theme() in C:\www\backdrop\core\includes\theme.inc on line 102
Call Stack
#  Time    Memory   Function                        Location
1  0.0091  1212064  _backdrop_exception_handler( )  ..\bootstrap.inc:0
2  0.0096  1271136  _backdrop_log_error( )          ..\bootstrap.inc:2553
3  0.0454  4833248  theme( )                        ..\errors.inc:242
4  0.0454  4833408  theme_get_registry( )           ..\theme.inc:1037
5  0.0454  4834096  backdrop_theme_initialize( )    ..\theme.inc:281
```

How do I get out of this? (other than the obvious of setting the mysql root password back to blank I mean)

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/659. It addresses a number of installation issues, including this one.
