### ISSUE TITLE
Rename default Contact form category

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4703]
**Description of the need**

I suspect that most people who enable the core Contact form do so in order to allow visitors to contact them, without needing to provide their email address publicly. As such, I also believe that most emails recieved through the contact form have nothing to do with feedback about the website itself (that seems like a very specific use-case).

**Proposed solution**

I therefore propose renaming the default Contact form category from "Website feedback" to something like "Website enquiry", or just "Enquiry". To me this seems more generic and a better default option.

**Alternatives that have been considered**

Users can always just edit the default category themselves (I personally have to do that all the time).

**Additional information**

![image](https://user-images.githubusercontent.com/2385329/95937183-e9da3200-0e22-11eb-831c-1c9c6eedb4ef.png)

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3376

**Comment by olafgrabienski** [comment]
Not sure if "enquiry" works well both in British and American English, does the latter prefer "inquiry"?

**Comment by indigoxela** [comment]
> ... I also believe that most emails received through the contact form have nothing to do with feedback about the website itself ...

That's also my experience, yes.

But as always, when it's about renaming something, some additional feedback seems helpful.
Although the change only applies to newly installed websites, or when the Contact module is initially enabled (naming happens in hook_install).

**Comment by stpaultim** [comment]
I've not thought much about this issue, but would agree that the default name for this form is not ideal. 

The most common use and name for this form is a simple "contact us" form (I think).  How about?

- Sitewide contact form
- Contact us
- Default contact form

Another point, this is called the category, not the form name. It is administrative only and does not show up to users, so how about Category =

- General 
- General interest

**Comment by BWPanda** [comment]
@olafgrabienski My understanding (after doing some research) is that 'enquiry' and 'inquiry' mean the same thing in American English (with the latter being more popular), but have slightly different meanings in British English - 'enquiry' being a question/query and 'inquiry' being a formal investigation.

@stpaultim The category for a contact form *is* shown to users as it's added in brackets to the very beginning of subjects in the emails sent.

**Comment by stpaultim** [comment]
I'm going to argue for "Contact form" as the new category. 

I don't think that this is an important issue, but if others think that this is an improvement, we can push this forward. If not, this is a pretty minor issue that only effects site administrators. It has no effect on the front end or the experience of site visitors.

**Comment by kiamlaluno** [comment]
Since, when there is a single category, that is shown to accounts without administrator permissions only in the email subject, for me *Contact form* is fine as default category.

*Website feedback* does not seem generic enough as default category, at least for me that I would use it for an email that is giving an opinion about the site, not an email posted by a person who is not able to log in on the site.

*website feedback* is shown in the *Configure contact category* form (*Example: 'website feedback' or 'product information'.*), but that should be fine as suggestion for a different category name.

**Comment by herbdool** [comment]
I don't think "contact form" makes sense as a category. The end users will see it in the email subject and if they add a second category, it will also be visible on the form itself. It just seems self-referential and focusing on the tool rather than the recipient or type of communication. Something like "General" or "Contact" is better in my opinion.

**Comment by stpaultim** [comment]
When I took over this PR, I probably didn't look deep enough into this issue regarding the implications. At first glace, it seemed like this was a purely a backend issue. I was thinking about this more as the name of the form. It now seems like there are a few places where this matters to end users. 

If there is only one category, it does not show up on the form. However, the intent of this feature is to provide the option for more than one category on a single form. If more than one category is available, then they show up in a drop down form that looks like this.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/262e81b9-99af-41be-ad14-e05851f82519)

The category shows up in brackets in emails sent to the recipient and (if selected) the copy sent to the sender.

 ![image](https://github.com/backdrop/backdrop-issues/assets/3144571/aca5b3f2-88d1-484f-bdca-4d59a953bf7f)

Thinking more about this, "Contact Form" is probably not the best Category. I'm now inclined to agree that "General" might be a good general option.

**Comment by kiamlaluno** [comment]
I am fine with *General* too, although I expect an adjective to be followed by a noun. (*General query* makes more sense to me.)

We should still keep in mind that those emails are sent to people involved in the site administration, or the organization behind the site, not to people who use the site services. Whichever default category we choose, we should consider it is not seen by a person who right created an account on a site five-ten minutes ago.

**Comment by stpaultim** [comment]
@kiamlaluno I understand your point. After looking at this issue closer I have changed my opinion. I find that the "Category" label is correct. This word is being used as a category to help end users find the right  form (assuming more than one category) and get their messages to the right person. 

Examples of form categories I can imagine. I believe that in this context, "General" is often used as a category:

- General
- Support
- Sales
- Accounts Payable
- Zookeepers
- Caregivers
- Security

We are simply providing the first default category on a single form. The form happends to be called "Contact form." We are not describing the form, but describing the kind of content in the Contact form and who it should go to. 

Contact forms can be configured to send a copy to the sender, which means that someone who has not created an account on the site might come to the site, fill out the form, and get a copy of their email back with the category in the header of the email. I tested this.

Also, once a site manager adds a second category to the site, everyone who visits the site MIGHT also see the default category. When I first looked at this issue, I assumed this would only effect admins, but I see now that it can effect more people. 

NOTE: I don't care too much about this issue. I am just hoping for a small improvement and the ability to close this issue. ;-)
I've maining changed my opinion, based upon the feedback of others.

**Comment by stpaultim** [comment]
Of the folks who have participated in this thread, I think we have something pretty close to a consensus that "General" would be an improvement, even if we not necessarily agreed on the exact best phrasing. If I read the messages correct, the following folks all like "General".

1. @izmeez 
2. @herbdool 
3. @kiamlaluno (although he would prefer "General query")
4. @stpaultim (that's me, I think "General" works well best, but could be persuaded to go with something else)

Does @indigoxela, @olafgrabienski or @BWPanda have anything to add?
An emoji reply is sufficient. Thumbs Up if you agree.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4623 into 1.x and 1.27.x. Thanks everyone for the great rounds of feedback and explanation of how Contact Form categories are used.

**Comment by stpaultim** [comment]
Another, of the many issues started by @BWPanda.

**Comment by quicksketch** [comment]
[Only another 110 to go](https://github.com/backdrop/backdrop-issues/issues/created_by/BWPanda).
