### ISSUE TITLE
Change page title name to `Configuration Manager`

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4711]
Today I saw the label `Configuration Manager` (again) for the first time in the Permissions matrix. I love this name! I'd love to see this label also appear in the Admin bar, and on the pages for managing configuration like `admin/config/development/configuration`.

Using the same label in both places will mean less to translate, and I prefer this shorter version to describe the tool itself. 

<img width="1192" alt="Screen Shot 2020-10-15 at 3 52 07 PM" src="https://user-images.githubusercontent.com/397895/96194033-5c6c1000-0efe-11eb-8f54-88dd04ef7986.png">

**Comment by Aryamanz29** [comment]
I would like to work on this @BWPanda

**Comment by klonos** [comment]
@Aryamanz29 please go ahead, and do let us know if you need help/direction with anything. Cheers!

**Comment by himanshu007-creator** [comment]
hi, its been long, if @Aryamanz29  is not working on this issue, i will be really happy to work, @klonos , please assign me this issue and guide me to the files

**Comment by Aryamanz29** [comment]
I'll be raise PR soon .. ✌️

**Comment by Aryamanz29** [comment]
@himanshu007-creator  You can start working on this issue.

**Comment by himanshu007-creator** [comment]
Please guide me to the file responsible👻

**Comment by indigoxela** [comment]
> Please guide me to the file responsible

Sure, the file is [core/modules/config/config.module](https://github.com/backdrop/backdrop/blob/1.x/core/modules/config/config.module#L12). Just follow the link to see the exact line. :slightly_smiling_face:

**Comment by indigoxela** [comment]
@himanshu007-creator many thanks for the pull request, the change looks good to me. :+1: 

One request (unrelated to the change in code): our automatic integration tests freaked out again (randomly failing tests). There's one thing you can do to run the tests again:

1. Close your PR (for clarity you can add a comment re Zen.CI...)
2. Wait at least five minutes
3. Open your PR again

(Or as we say in our chat "turn it off and on again" :grin:)

Hopefully then the tests pass as expected.

**Comment by himanshu007-creator** [comment]
Next try 5mins from now

**Comment by indigoxela** [comment]
Here we go, the "Configuration manager":

![configuration-manager](https://user-images.githubusercontent.com/842066/125810705-1152c022-d752-4f18-b64d-53d586419aac.png)

A small and straight forward change, RTBC. :+1:

**Comment by quicksketch** [comment]
Thanks @himanshu007-creator and @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/3664 into 1.x and 1.19.x.
