### ISSUE TITLE
Backdrop does not run on PHP 5.3.3 (or PHP 5.3.2?)

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4712]
**Description of the bug**

In the [requirements section on bakdropcms.org](https://backdropcms.org/requirements) we clearly state that you need to be running **PHP 5.3.2 or higher** to run Backdrop.

I have a server running two Drupal 7 sites (and a Drupal 6 site, but sshhh) that is on 5.3.3 that cannot run Backdrop.

I get the following fatal error when trying to log in: 
```
Fatal error: Can't inherit abstract function UserInterface::id() (previously declared abstract in EntityInterface) in backdrop/core/modules/user/user.entity.inc on line 10
```

**Steps To Reproduce**

To reproduce the behavior:
1. Find an old server running PHP 5.3.3 (preferably, one that runs Drupal 7 with no issues)
2. Import working database + config + code from Backdrop 1.17.x site
3. Attempt to log in

**Actual behavior**

fatal errors

**Expected behavior**

things should work.

Add any other information that could help, such as:
- Backdrop CMS version: `1.17.1`
- Web server and its version: `nginx version: nginx/1.10.2`
- Operating System and its version: `CentOS release 6.9 (Final)`

**Comment by indigoxela** [comment]
Hm... If this is the _first_ time someone actually realized this problem, then it's very likely a really rare one... :wink: 

@jenlampton _In theory_ php version 5.3.9 could handle that code, but updating the requirements info is probably not what you want. And updating php on your CentOS server is probably impossible, too.

Anyway, I can't test/verify nor provide a PR as the oldest php version I can get on my dev is 5.6.40. And this very likely is the case for most of us.

BTW: our 5.3 testboxes have 5.3.29.

**Comment by jenlampton** [comment]
> Hm... If this is the first time someone actually realized this problem, then it's very likely a really rare one

It's possible that someone had realized the problem but gave up on Backdrop immediately and then didn't bother to tell us. I suspect though, that this is a rare problem. 

I am tempted to move these sites to a newer server for the client, but I also want to use this server as a testing ground for Backdrop... 

Is it possible to rework the code so that it can run on `PHP 5.3.2 or higher`, or is that a lost cause at this point? If a lost cause, we should update the documentation to match reality. (and close this issue)

**Comment by indigoxela** [comment]
> Is it possible to rework the code so that it can run on PHP 5.3.2 or higher, or is that a lost cause at this point?

It's very likely possible, but who could provide a PR? Does anyone still have such an oooold php available in a dev box? Or maybe the question should be: is anyone willing to spend time on it?

> If a lost cause, we should update the documentation to match reality.

Backdrop supports 5.3.29 - the testboxes prove it. Anything older would be hard to verify, even 5.3.9 - which should have fixed that php bug.

Note: many of the 5.3 releases after 5.3.2 have been security releases. It's not recommended to run *anything* on such an old and insecure php version. At least not if it's "in the internet".

**Comment by jenlampton** [comment]
> Does anyone still have such an oooold php available in a dev box?

Well, I do, apparently :)

> Does anyone still have such an oooold php available in a dev box?

Surely docker can do this?

> It's not recommended to run anything on such an old and insecure php version

I expect that there are a lot of sites that were built, launched, and have been "working fine" ever since, with little thought toward maintenance. In my case, the Drupal 6 site is still doing it's intended job well.

**Comment by stpaultim** [comment]
> Note: many of the 5.3 releases after 5.3.2 have been security releases. It's not recommended to run anything on such an old and insecure php version. At least not if it's "in the internet".

I appreciate that it's not recommended. But, if our documentation says that we support 5.3.2 or higher, then we should support it. I assume that this is a policy decision that we took at some point and that there are reasons behind it. 

What is very cool, is that we will (at lease we should) soon have telemetry data to give us some idea of what versions of PHP our users are using.

**Comment by klonos** [comment]
Lando configured with `php: '5.3'` installs 5.3.29 (although many errors - some re composer, some re drush) ...anyway, I can get Backdrop installed manually in php 5.3.29, but the goal is to get 5.3.2 installed. Perhaps @serundeputy can help with a `.lando.yml` example that gets us 5.3.2?

**Comment by quicksketch** [comment]
This is now a moot issue as we're bumping the minimum version to 5.6 in https://github.com/backdrop/backdrop-issues/issues/3992. I don't think it makes sense for us to cause confusion by bumping the version number twice; which may lead to people thinking that newer versions of 5.3 (or anything below 5.6) is going to be sufficient.
