### ISSUE TITLE
Consider raising required minimum PHP version for Backdrop

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4715]
The Backdrop CMS requirements for PHP are currently defined as [PHP 5.3.2 or higher](https://backdropcms.org/requirements).

However, it seems we're increasingly running into trouble with this - for several reasons. For instance, if automated tests fail in the 5.3 testboxes, we can only guess, how to fix it. And as we definitely need testboxes with newer PHP versions in the near future, it might be impossible to run both versions on the same box.

**First of all, it has been reported that:**

- Backdrop does not run on PHP 5.3.3 (or PHP 5.3.2?) #4712 (not confirmed yet)

Who could confirm or provide a fix for it, if confirmed?

**Several related discussions exist in other issues:**

- Drop support for PHP lower than 5.6 (or establish best-effort policy) #3992
- [SR][WP] Warn about EoL PHP versions. #3490

Nowadays hardly any core contributor/committer is able to get a dev instance with PHP older than 5.6.
On the other hand it's not easy to figure out, which version actually *is* insecure (updated by Linux distri vs. really unmaintained).

I'm pretty sure we all agree that PHP 5.3 is extremely old.
But raising core requirements is something that needs extensive discussion. And that's what this issue tries to start.

**Comment by klonos** [comment]
Thanks for starting this issue @indigoxela 👍 ...at the same time (yesterday, after the weekly meeting actually), @jenlampton has raised an internal issue about the very same thing in the Leadership issue queue (PMC + core committers). So I'd expect an official decision on this soon(ish). In the meantime, this is a great place to allow those w/o access to the Leadership queue to provide feedback.

**Comment by indigoxela** [comment]
A pragmatic solution could be to raise the min version to 5.3.29 - that's the php version of our testboxes. Then no additional checks are needed.

**Comment by klonos** [comment]
@indigoxela should we close this as a duplicate of #3992?

Also:

> A pragmatic solution could be to raise the min version to 5.3.29 - that's the php version of our testboxes.

If the policy re "best effort" for issues related to PHP lower than 5.6 passes, then we could raise the testboxes to latest php 5.6.x ...or not 🤷

**Comment by indigoxela** [comment]
> should we close this as a duplicate of #3992?

That might make sense, these two issues at least overlap, although I don't think that we can raise the min version to 5.6 soon.
