### ISSUE TITLE
Trying to sort the content overview via table header ticks (and filters by) new/updated content 

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4719]
**Description of the bug**

Trying to sort the content overview via table header (any of it) ticks (and filters by) "New/updated content".

**Steps To Reproduce**

1. Go to admin/content
2. Click on any of the table headers to change sorting
3. See the checkbox automatically checked and the results filtered

**Actual behavior**

![header-triggers-checkbox](https://user-images.githubusercontent.com/842066/97106941-e79a9200-16c4-11eb-85ed-b38b3c142487.png)

Unchecking the filter and clicking on "Filter" also resets sorting back to default (Updated column).

**Expected behavior**

Table header sorting should not trigger the filters.

**Additional information**

- Backdrop CMS version: 1.17.1
- Browser(s) and their versions: Firefox ESR and Chromium (and probably others, too)

**Comment by olafgrabienski** [comment]
Confirmed! I've also stumbled upon this issue some days ago.

**Comment by BWPanda** [comment]
Huh, weird! My only thought was that it might be some sort of conflict with that exposed field's machine name ('timestamp' by default), but I just changed it and it still happens...

**Comment by BWPanda** [comment]
Here's a screencast in case anyone has trouble understanding the issue here:

![Peek 2020-10-27 20-31](https://user-images.githubusercontent.com/2385329/97283008-73621900-1893-11eb-8163-478ac086dc2e.gif)

**Comment by indigoxela** [comment]
Ha! I was just able to reproduce it on a vanilla Drupal 7 install. So it seems that we inherited this quirk from Drupal.

**Comment by BWPanda** [comment]
> So it seems that we inherited this quirk from Drupal.

I suspected as much, since there was nothing in the view that would cause this, it had to be in the Views code/module itself.

**Comment by indigoxela** [comment]
That's tricky...

First of all I verified that it's neither a browser problem nor has it anything to do with Javascript. The problem is how the form API handles checkboxes that get values via $_GET.

[function form_type_checkbox_value](https://github.com/backdrop/backdrop/blob/e084bb8137dcbb76b1fbd627ece68a822077ca1b/core/includes/form.inc#L2393)

> if ($input === FALSE)

That's never true for this single checkbox. `$input` is **NULL** if nothing set (simple page call of admin/content).

The value if it's checked is `'1'`.
The value when click-sorting happened is `'0'`.

So the first if clause won't ever strike for that checkbox.

Let's have a look at the `else`.

> isset($input) ? $element['#return_value'] : 0;

The value _is set_ (via $_GET param), but it is `'0'`. Nevertheless the checkbox value gets set to its return_value, which is `'1'`.
changing that `isset` to `!empty` fixes the problem in this form for this checkbox.

But the length of the comments in that function make me precautious.
It's old code BTW (2010) from [Drupal 7](https://www.drupal.org/project/drupal/issues/654796)

**Comment by indigoxela** [comment]
Another indicator that the current handing of checkbox values is fuzzy is following example:
`/admin/content?status=All&type=All&title=&timestamp=foobarwhatever&order=type&sort=asc`

The value "foobarwhatever" also checks the checkbox.

It seems that we need an additional check that the input actually fits the form item `#return_value`.

That's what my [PR](https://github.com/backdrop/backdrop/pull/3385) does.

Please test and review.

**Comment by indigoxela** [comment]
Very likely the next request here would be to add a test, so I added a test to save us some time. :smirk:

**Comment by olafgrabienski** [comment]
The PR works for me using the sandbox website: I was able to sort every column of the `admin/content` table and didn't see unwanted effects on the "New/updated content" checkbox.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏 ...code also looks good to me, RTBC 👍

**Comment by indigoxela** [comment]
> I did leave a suggestion for consideration re the inline comment

Sure, the comment makes more sense that way. :+1: Change applied.

**Comment by BWPanda** [comment]
Thanks @indigoxela, @olafgrabienski & @klonos! I've merged https://github.com/backdrop/backdrop/pull/3385 into 1.x and 1.17.x.

**Comment by markabur** [comment]
Note that this change also fixes the same behavior on the pagination controls on the admin/content screen. 

Currently in 1.17.1 it's not possible to page through all of the site content. Also the "last >>" button results in a blank "No content found" message. Both issues fixed with this patch.

**Comment by klonos** [comment]
> ... Both issues fixed with this patch.

🎉
