### ISSUE TITLE
Make core aware of Nginx and PHP-FPM to avoid confusing alerts

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#472]
This is the same as https://www.drupal.org/node/1559116 for D8.

In setups where there is nginx + uploadprogress enabled, the site status page still says "Upload progress Not enabled" and continues to state that "Your server is not capable of displaying file upload progress. File upload progress requires an Apache server running PHP with mod_php".

Lets fix this in 1.0.0 since it's a D8 port.

**Comment by quicksketch** [comment]
Cool, I'll take a stab at porting the D8 version, which reads easier for me and doesn't complicate things.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/623.

**Comment by omega8cc** [comment]
Thanks!
