### ISSUE TITLE
ApisCP auto-installer for Backdrop CMS

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4722]
ApisCP, a full-stack hosting platform for modern websites. 
https://apiscp.com/
They have their own App installer Web App like  Softaculous auto-installer

ApisCP is open-source software and base on PHP. Can we add our Backdrop CMS in their web app

Drupal 7 Here 

**Additional information**
https://github.com/apisnetworks/apiscp-webapp-drupal
https://docs.apiscp.com/admin/Hooks/
We can also hook into the API on drupal: install to add the plugin

**Comment by stpaultim** [comment]
Thanks for opening this issue @domaingood. 

However, I am moving this issue to BackdropCMS.org issue queue. That is where we usually put issues related to marketing, outreach, or community stuff. This issue does not effect the core code base, so it is probably better there. 

https://github.com/backdrop-ops/backdropcms.org/issues/722
