### ISSUE TITLE
Update LICENSE.txt formatting

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4726]
This is a *very* minor issue, but something that bugs me each time I look at it...

The [LICENSE.txt](https://github.com/backdrop/backdrop/blob/1.x/LICENSE.txt) file wraps well before the 80-character mark:
![image](https://user-images.githubusercontent.com/2385329/97549264-4db84980-1a24-11eb-82db-cad63311653e.png)

Also, there is a section at the bottom titled 'How to Apply These Terms to Your New Programs' which contains instructions and a bunch of dummy business names. Is this necessary to include in the license, or is it presumed that you remove it after following its advice?

All-in-all, should/can we update the LICENSE.txt file to be better formatted and have less unnesessary information?
I know there's a statement about the license up the very top that says "changing it is not allowed", so maybe we can't remove the bottom section, but I don't think that applies to formatting, especially since https://opensource.org/licenses/gpl-2.0.php seems to have removed the wrapping and even added HTML tags for formatting...

**Comment by indigoxela** [comment]
> This is a very minor issue

Hehe, 80 chars? :smirk:  I'd say, leave the file untouched, it's not your "code", so there's no need to obey the coding standards.

**Comment by stpaultim** [comment]
Could be a good issue for a demo or a first time contributor to practice creating a PR.

**Comment by BWPanda** [comment]
I had another thought: Let's change this from a `.txt` file to a `.md` file. Then it can be rendered nicely in Github (and other places) with nicer formatting for headings, sections, etc.

**Comment by indigoxela** [comment]
As this is a _license_ file, we probably need to make sure, that it's exactly as it's supposed to be:

https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

Any changes might be problematic.

**Comment by BWPanda** [comment]
https://github.com/IQAndreas/markdown-licenses/blob/master/gnu-gpl-v2.0.md ?

**Comment by indigoxela** [comment]
Hm. The raw version shows the same short lines: https://raw.githubusercontent.com/IQAndreas/markdown-licenses/master/gnu-gpl-v2.0.md I wonder, if it's allowed to change newlines or anything beyond that...

**Comment by BWPanda** [comment]
I found this question on Law StackExchange: https://law.stackexchange.com/questions/3419/re-formatting-and-displaying-of-software-licenses-privacy-policy-impressum Their first question is similar to mine, and the answer says that it's ok to format the license differently (regarding line-breaks, etc.).

However I then found these questions on Open Source StackExchange: https://opensource.stackexchange.com/questions/8254/can-we-re-format-the-text-of-a-license-after-forking-a-repository and https://opensource.stackexchange.com/questions/1613/can-i-make-typographical-changes-to-the-mit-license Those answers not only warn that the formatting of the license could have legal significance, but also that changes may result in an entirely new license (so it wouldn't techincally be GPL2 anymore)...

I guess better to err on the side of caution here :frowning_face: Closing then. Feel free to re-open if you disagree.
