### ISSUE TITLE
Problems with hidden_path views support (views_handler_filter_node_hidden_path)

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4727]
**Description of the bug**

Hidden paths have views support ... in theory. But actually it seems broken/incomplete.

**Steps To Reproduce**

1. Create a view of type node
2. Try to add a filter "Content: Hidden path"
3. The first problem is that it has no exposed support
4. The major problem is that it throws an exception when the filter is set to "**Yes**", but there's no content type (yet) with hidden paths setting

Even if one switched hidden paths on in a content type, but later sets it back to off, the exception appears again.

**Actual behavior**

![hidden-path-exception](https://user-images.githubusercontent.com/842066/97589716-29497680-19fe-11eb-868b-0ac2fcd21c7f.png)

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) )) LIMIT 10 OFFSET 0' at line 4 
`
Here's the db query: 

```
SELECT node.nid AS nid
FROM 
{node} node
WHERE (( (node.status = '1') AND (node.type IN ()) ))
LIMIT 10 OFFSET 0
```
And THIS is the query when content type "has hidden path" got that setting back:

```
SELECT node.nid AS nid
FROM 
{node} node
WHERE (( (node.status = '1') AND (node.type IN ('has_hidden_path')) ))
LIMIT 10 OFFSET 0
```

And support for exposed forms would be nice, too.

![no-exposed-option](https://user-images.githubusercontent.com/842066/97590825-534f6880-19ff-11eb-9af0-892d9bc527e4.png)

**Additional information**

- Backdrop CMS version: 1.17.1 
- Web server and its version: apache / php-7.4.11
- Database server: MariaDB 10.3.25

Update: Had to remove some wrong info.

**Comment by indigoxela** [comment]
It's actually an easy fix. A [PR](https://github.com/backdrop/backdrop/pull/3384) is available for testing and review.

**Comment by herbdool** [comment]
This works @indigoxela 

I'm wondering how hard it would be to also add the (Yes) or (No) behind the filter like it does for Published? If it's hard I can create a new issue. I don't want to delay this bug fix.

![Screenshot from 2020-10-30 09-48-05](https://user-images.githubusercontent.com/1071483/97712716-349bb100-1a95-11eb-9df7-50040eeac88d.png)

**Comment by indigoxela** [comment]
> I'm wondering how hard it would be to also add the (Yes) or (No) behind the filter like it does for Published

Not hard at all. :wink:

And I also fixed the coding standards violations (phpcs is happy now).

**Comment by herbdool** [comment]
Excellent. Still looks good.

**Comment by olafgrabienski** [comment]
Wow, that was quick! Added to the 1.17.2 milestone.

**Comment by BWPanda** [comment]
Thanks @indigoxela, @herbdool & @olafgrabienski. I've merged https://github.com/backdrop/backdrop/pull/3384 into 1.x and 1.17.x.
