### ISSUE TITLE
Footer not sticky at the bottom (Bartik)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#473]
This is what people see after installation:

![backdrop-footer_not_sticky](https://cloud.githubusercontent.com/assets/2423362/5487872/c8ff45de-870a-11e4-901a-daec2523c195.png)

It would be nice if the footer was set to always stick to the bottom of the page without any white space below it.

Things to consider/keep in mind:

- Once the front page is populated with enough content, this won't matter for the front page, but any other 'short' page will be affected nevertheless.

- If we are to remove Bartik, this is a non-issue for that theme itself, but it is related to Blocks and Layouts and thus we should consider providing a generic solution for making footer regions stick to the bottom.

**Comment by tjdjours** [comment]
Took a look at this thinking I might offer some options and noticed the footer was indeed sticking after a recent pull. 

The footer is sticking, but primary nav tabs lost as I shrink the browser height beneath 600px.
Three screengrabs below to illustrate with browser dimensions. I first noticed the issue in the context of the second image, after creating a node. The new node message was similarly obscured/squished.

![y-less-than-600px--1](https://cloud.githubusercontent.com/assets/5393205/5615535/152bf750-94ca-11e4-8b2b-d06b573ca19d.png)
![y-less-than-600px--2](https://cloud.githubusercontent.com/assets/5393205/5615537/1b2ac230-94ca-11e4-84b7-f74e9ff0d930.png)
![y-less-than-600px--3](https://cloud.githubusercontent.com/assets/5393205/5615541/1fb28aa4-94ca-11e4-907a-7a79b0062e79.png)

**Comment by tjdjours** [comment]
Curious as to what was going on, I found that it is that display: flex. on .layout.

I was going to point to this method: http://ryanfait.com/resources/footer-stick-to-bottom-of-page/
Made less ornery by a mixin. I name that .push class .footer-placement to remind me of the hack/technique.

There's also this method which uses display:table and display:table-row. http://jsbin.com/cevobu ([see html/css](http://jsbin.com/cevobu/2/edit)). Displaying things as tables to solve css problems seems counterintuitive after scrapping `<table>` layouts.

**Comment by quicksketch** [comment]
Thanks @tjdjours! I hadn't noticed this behavior in my testing. This problem appears to occur in Chrome, but not Firefox or even IE10. I think with the right adjustment, we can get this flexbox thing working.

> I was going to point to this method as a solution: http://ryanfait.com/resources/footer-stick-to-bottom-of-page/

I think this method only works with a fix-height footer, at least those are the examples given.

I'll see if I can fix this in Chrome. The situation is quite unacceptable, as if you post enough content, the header disappears entirely.

**Comment by dboulet** [comment]
Applying `flex: none` to the header should fix this.

**Comment by quicksketch** [comment]
This should fix it: https://github.com/backdrop/backdrop/pull/639/files

It looks like if you're going to use the flexbox display, you have to explicitly specify which items should be stretchy and which ones should display fixed height. In Firefox and IE, things are implied to display at their full height, but in Chrome, it defaults to making everything stretchy, including squeezing to 0 to fit tall content.

> Applying flex: none to the header should fix this.

Thanks @dboulet, I used `flex: 0 0 auto;` to the same effect. Would `none` be better? I admit I only barely grasp how flexbox works.

**Comment by quicksketch** [comment]
From https://developer.mozilla.org/en-US/docs/Web/CSS/flex, `none`:

> This keyword computes to 0 0 auto.

**Comment by dboulet** [comment]
As I understand it, `flex: none` and `flex: 0 0 auto` is exactly the same thing—using the `none` keyword is just shorter.

**Comment by quicksketch** [comment]
> Need to add .l-messages to that flex: 0 0 auto; too. 

Ah, nice catch. Fixed. I merged in the PR after adding in messages. Thanks @dboulet and @tjdjours!
