### ISSUE TITLE
Add native widget to Date field

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4733]
**Description of the need**

There exists an HTML input type: `date` which provides native support for date fields, with a popup calendar, for modern browsers and mobile devices: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
However browser support is spotty, so we can't implement this as the default solution.

**Proposed solution**

I propose adding a new, core widget (but not set as default) for the Date field which uses this native format. Then people who want to support mobile and modern browsers can do so, while others can use the existing 'popup calendar' widget.

**Alternatives that have been considered**

A contrib solution is an option, considering lack of consistency with browser support and possible confusion with existing widgets...

**Comment by klonos** [comment]
> However browser support is spotty...

Yeah 🤔 ...although given the global usage stats and Chrome's world dominance, that may not be an issue:

https://caniuse.com/mdn-html_elements_input_input-date

![image](https://user-images.githubusercontent.com/2423362/97938803-1252ad80-1d8b-11eb-8fbe-e69b88e0f0d7.png)

https://caniuse.com/input-datetime

![image](https://user-images.githubusercontent.com/2423362/97938833-2696aa80-1d8b-11eb-8add-c94077cede81.png)

**Comment by indigoxela** [comment]
We have the date field in [core form API](https://api.backdropcms.org/form_api#html_datetime).
![datetime-field](https://user-images.githubusercontent.com/842066/97956659-8c922a80-1da9-11eb-8ce1-992e3a6a85a5.png)

However, there's no field widget yet. But there's a [follow up issue](https://github.com/backdrop/backdrop-issues/issues/4255) for that task.

**Comment by BWPanda** [comment]
@indigoxela Ah, thanks. Missed that somehow... Closing as a duplicate.
