### ISSUE TITLE
Add missing .htaccess rules for mod_php7

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4752]
Some of the `.htaccess` rules for PHP 5 are not applied for PHP 7:

```
# Override PHP settings that cannot be changed at runtime. See
# settings.php and backdrop_environment_initialize() in includes/bootstrap.inc
# for settings that can be changed at runtime.
<IfModule mod_php5.c>
  php_flag session.auto_start               off
  php_value mbstring.http_input             pass
  php_value mbstring.http_output            pass
  php_value max_input_vars                  10007
  php_flag mbstring.encoding_translation    off
</IfModule>
```

Should be changed to 

```
# Override PHP settings that cannot be changed at runtime. See
# settings.php and backdrop_environment_initialize() in includes/bootstrap.inc
# for settings that can be changed at runtime.
<IfModule mod_php7.c>
  php_flag session.auto_start               off
  php_value mbstring.http_input             pass
  php_value mbstring.http_output            pass
  php_value max_input_vars                  10007
  php_flag mbstring.encoding_translation    off
</IfModule>
# Same settings again for PHP 5 versions.
<IfModule mod_php5.c>
  php_flag session.auto_start               off
  php_value mbstring.http_input             pass
  php_value mbstring.http_output            pass
  php_value max_input_vars                  10007
  php_flag mbstring.encoding_translation    off
</IfModule>
```

---
PR: https://github.com/backdrop/backdrop/pull/3399

**Comment by klonos** [comment]
Thanks @jenlampton ...simple change, LGTM 👍

**Comment by klonos** [comment]
...php8 is in RC state and about to be released in a few days (https://wiki.php.net/todo/php80). Should we add a section with the same setting for it?

**Comment by indigoxela** [comment]
> php8 ... Should we add a section with the same setting for it?

I think before that we should check if Backdrop is compatible with PHP 8. :wink:

**Comment by BWPanda** [comment]
Added a question in the PR asking why a line was being removed from the PHP5 section...

**Comment by klonos** [comment]
I totally missed that @BWPanda ...my bad 😓 ...I think that @jenlampton has mixed this issue with #3824 in her local.

**Comment by jenlampton** [comment]
Sorry folks, pushed a fix that restores the php5 value and adds it as a php7 value too.

**Comment by klonos** [comment]
That's better 🙂 ...thanks for the very prompt fix @jenlampton 🙏 ...back to RTBC then.

**Comment by BWPanda** [comment]
Thanks for that change. Looks fine to me, though I don't understand a lot of PHP config stuff... :slightly_smiling_face:

**Comment by quicksketch** [comment]
Thanks, merged into 1.x and 1.17.x!
