### ISSUE TITLE
1.17.2 regression: Fieldset style broken

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4758]
(Still looking into this, but wanted to quickly create an issue for it)

I've noticed certain styles broken with fieldsets:

<img width="1192" alt="Screen Shot 2020-11-14 at 12 51 17 am" src="https://user-images.githubusercontent.com/2423362/99128770-6031a600-2614-11eb-9bef-373b9ac9617a.png">

1. "Formatter options" fieldsets under CKEditor-enabled fields have lost their specific style (rounded instead of sharp corners, white background instead of gray etc.)
2. Fieldsets within vertical tabs have left/right/bottom border added to them.

I believe that #3930 is what broke them (sorry 😓 )

**Comment by klonos** [comment]
...something must have gone terribly wrong as this seems to have broken the mobile vtabs/fieldsets as well 😓:

![image](https://user-images.githubusercontent.com/2423362/99129522-848e8200-2616-11eb-8c7b-f091066dd1be.png)

I swear that I tested this as part of #3930

**Comment by BWPanda** [comment]
Confirmed on demo sandbox.

**Comment by herbdool** [comment]
Maybe we reverse it until there's a fix?

**Comment by BWPanda** [comment]
I tested doing a `rebase` on my local, and confirmed that it fixed the regression. I just don't know how to make a PR from a rebase...

**Comment by klonos** [comment]
Let me give it a go @BWPanda ...

**Comment by klonos** [comment]
...hmm, rebasing didn't seem to fix things for me: https://github.com/backdrop/backdrop/pull/3402 I've tested in both PR sandboxes (tugboat and ZenCI) and the breakage is still there 🤷

**Comment by indigoxela** [comment]
Here's a temporary solution which simply reverts the problematic commit: https://github.com/backdrop/backdrop/pull/3403
In case we find no smarter solution.

This verifies that it's really commit 2b28f327d3e4aae24b11e3be468232de959508f0, which introduced the problem. A sandbox is available, but Zen.CI ran into a timeout.

**Comment by olafgrabienski** [comment]
The temporary solution works for me in the Tugboat sandbox:

- Formatting options look good again
- Vertical tab fieldsets look also good

**Comment by klonos** [comment]
I've updated the PR at https://github.com/backdrop/backdrop/pull/3402 to fix most of the regressions (including the mobile version of vertical tabs). The only thing I need help with is fixing the padding between CKEditor and the "Formatting options" fieldset:

![image](https://user-images.githubusercontent.com/2423362/99541951-223cd500-29ba-11eb-8360-63384c94af4d.png)

**Comment by indigoxela** [comment]
> The only thing I need help with is fixing the padding between CKEditor and the "Formatting options" fieldset

Yep, it's really only the label gap, the other things seem fixed.

**Comment by klonos** [comment]
Thanks @indigoxela for testing things so promptly 👍 

If anyone else has the time/energy please feel free to grab my changes and take a shot at fixing that gap. I need to take a break now.

**Comment by klonos** [comment]
I've updated the PR yet again, with a suggestion @indigoxela provided in Zulip (thanks 🙏 ). That fixed the annoying gap, and also made the fieldset less "jumpy". The "jumpiness" is a preexisting issue though: #3596

**Comment by indigoxela** [comment]
Some screenshots from the current solution:

Longer text collapsed (fiddled in with browser dev tools):
![long-text-collapsed](https://user-images.githubusercontent.com/842066/99552081-e6efd580-29bc-11eb-9b91-f99c2c92e123.png)

Expanded formatting fieldset:
![formatting-expanded](https://user-images.githubusercontent.com/842066/99552147-f5d68800-29bc-11eb-82fc-d1f57f347160.png)

RTL on smaller screens:
![mobile-rtl](https://user-images.githubusercontent.com/842066/99552345-30402500-29bd-11eb-825f-790de6c2c454.png)

**Comment by quicksketch** [comment]
As we're doing a release today and this is fairly noticeable, I've merged https://github.com/backdrop/backdrop/pull/3402 into 1.x and 1.17.x for today's 1.17.3.

**Comment by BWPanda** [comment]
There are still some issues. Made a follow-up here: https://github.com/backdrop/backdrop-issues/issues/4766

**Comment by jenlampton** [comment]
We probably should have merged the PR that reverted the commit that caused the problem.
