### ISSUE TITLE
Add email (field) module to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#476]
Instead of leaving this as a stand-alone module, it should be added as a field type to field module.
Form element types will also need to be updated to use the email element.

**Comment by juanolalla** [comment]
I've ported Email Field as a contrib module: https://github.com/backdrop-contrib/email

**Comment by quicksketch** [comment]
Awesome, thanks @juanolalla! Can't wait to try it out!

Also, regarding the original report, it's likely that we'll add this module as a stand-alone module (like text.module, options.module, etc) during the 1.x release. We might consider combining them, but I think it'd be a lot more likely we'd want to simply hide the module if we wanted to make it required.

**Comment by quicksketch** [comment]
I'm reviewing this work and so far it looks really good! Most of the clean up required is actually *more* removing of functionality. I'm pruning the code now and will file a PR on top of the one at https://github.com/backdrop/backdrop/pull/1011.

In particular, I've run across the following:

- The old token hooks don't work (and aren't really needed anyway). They still use D6-implementation that is no longer needed (Field module provides the token automatically).
- The "Contact Form" formatter seems overly bloated for core. This functionality should be split out into a separate module (as @klonos mentioned as well).
- Removing the contact form means this module no longer needs a config file either, which further simplifies things.
- It looks like tests aren't running currently. I'm working on fixing them to get some basic test coverage.

This module is a lot simpler than I had anticipated, which is great news for getting it finished up and moved into core. :smile:

**Comment by jenlampton** [comment]
I'm applying this patch to my client site, will report any issues I find here :)

**Comment by quicksketch** [comment]
New pull request filed at https://github.com/backdrop/backdrop/pull/1029. Changes:

- Fixed tests.
- Added an upgrade path similar to CKEditor, where System module will notify the administrator that Email module is now bundled in core, and links to the change notice at https://api.backdropcms.org/node/42928
- Removed SpamSpan formatter.
- Removed the Email Contact formatter.

It would be great if the SpamSpan formatter and Email Contact formatters were moved into separate modules (or possibly merge into SpamSpan and make a stand-alone module for Email Contact Formatter).

Overall though, this module is so simple I don't see how we can go wrong.

**Comment by jenlampton** [comment]
okay, reverted and now trying *this* patch.  So far so good!

**Comment by quicksketch** [comment]
I gave this another review today and found a small issue where our `hook_requirements()` was checking for a ckeditor.module instead of email.module to report the duplicate module warning. Other than that, I didn't find anything in my review. I think this is ready to go.

**Comment by jenlampton** [comment]
If anyone needs the contact-form functionality we removed from core, that can be found in this contrib project: https://github.com/backdrop-contrib/email_contactform
