### ISSUE TITLE
**redacted potential security issue**

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#4761]
This is a redacted report of a potential security issue.

**Reporting a Security Issue**

If you have found a security issue in Backdrop Core or a Contributed Project, send an email to security@backdropcms.org. Do not file an issue on GitHub if you think you have encountered a security issue. The Backdrop Security Team uses a private repository on GitHub where security issues are discussed and managed.

**Comment by indigoxela** [comment]
@domaingood security issues should not be posted here. See https://backdropcms.org/security for details.

But first of all: the variable $match_operator you're referring to does _not_ exist in Backdrop.

**Comment by jenlampton** [comment]
Thank you @indigoxela for noticing this issue, and for providing @domaingood with the instructions on how to report security issues responsibly. 

This issue has been copied into the private security queue for closer examination.
