### ISSUE TITLE
Slight style breakage in the "Select versions" step of the Project Installer

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4768]
![image](https://user-images.githubusercontent.com/2423362/99918460-ad51fe00-2d1f-11eb-8c28-d40d6386de85.png)

This broke sometime around 1.17.0 or 1.17.1. Here's how it used to look:

![image](https://user-images.githubusercontent.com/2423362/99918854-5f8ac500-2d22-11eb-902b-11b69061c9c9.png)

**Comment by indigoxela** [comment]
Also just noticed it.

Here's a markup screenshot.

![module-install-markup](https://user-images.githubusercontent.com/842066/101051452-cf504980-3585-11eb-9d1b-efbdb55f1f59.png)

CSS in core/modules/system/css/system.css:

```
.js .js-show {
  display: block;
}
```
This probably shouldn't be "block" for a link (a) tag, but rather be "inline".

Suggested addition:

```
.js a.js-show {
  display: inline;
}
```
(I don't dare to provide a core CSS PR :wink: )

**Comment by klonos** [comment]
I notice that this does not happen all the time. I just tried it in a demo sandbox, and the problem is not there 🤷 ...we need to figure out what triggers it.

Are you seeing this in 1.17.4 @indigoxela ?

**Comment by indigoxela** [comment]
> I notice that this does not happen all the time.

Strange...

> Are you seeing this in 1.17.4

It happened on 1.18.x-dev, admin theme is Seven. On 1.17.4 the class of that link is "js-only".

**Comment by indigoxela** [comment]
> I don't dare to provide a core CSS PR

I do dare, and usually I don't listen to my own advice. :smile: 

The change is really minimal.

**How to test:**

Log into the sandbox and try to install any module. You don't have to actually install it, BTW, it's sufficient to add one to the queue and then hit the Install button. There the "change release" link should be shown inline again. You can safely abort the install then.

**Comment by klonos** [comment]
> The change is really minimal.

It really is, and it makes sense, so I'm RTBC'ing this. I still need a reliable way to reproduce the issue though, so leaving the "needs testing" label.

**Comment by klonos** [comment]
> It happened on 1.18.x-dev ...

Confirmed 👍 ...I originally tested in a demo sandbox, which uses 1.17.4. I now tested in a recent PR sandbox that has the latest 1.18.x (https://github.com/backdrop/backdrop/pull/3171 if it matters), and I was able to reproduce.

**Comment by BWPanda** [comment]
Thanks guys! I've merged https://github.com/backdrop/backdrop/pull/3421 into 1.x and 1.17.x.
