### ISSUE TITLE
Replace double dashes with middot in Taxonomy fields

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4770]
Similar to https://github.com/backdrop/backdrop-issues/issues/4218, we should be consistent and change dashes in Taxonomy fields to middots as well.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3410

**Comment by indigoxela** [comment]
Nice catch. The PR fixes it on the field settings and node form. What's still missing is the term/add (and edit) form:
![term-add-edit](https://user-images.githubusercontent.com/842066/100062942-b2eb3900-2e30-11eb-982a-17de996818dc.png)

(In taxonomy.admin.inc I suppose.) I didn't check views yet.

**Comment by BWPanda** [comment]
Thanks @indigoxela, PR updated.

**Comment by klonos** [comment]
Thanks @BWPanda ...one last place is https://github.com/backdrop/backdrop/blob/1.x/core/modules/taxonomy/views/views_handler_filter_term_node_tid.inc#L135

**Comment by BWPanda** [comment]
PR updated (again).

**Comment by indigoxela** [comment]
> PR updated (again).

Many thanks, I think we now really catched them all.

Tested with:

- admin/structure/taxonomy/category/add
- admin/structure/types/manage/post/fields/field_category
- node/add/post
- a test view with an exposed filter as a dropdown (with hierarchy)

Works for me.

**Comment by klonos** [comment]
> I think we now really catched them all.

Yup, I think so too 👍 

Same as #4218 this is a task, not a feature request. I've added the milestone candidate label accordingly, so if a second person agrees, please set the milestone too 😉

**Comment by BWPanda** [comment]
Thanks guys. I've merged https://github.com/backdrop/backdrop/pull/3410 into 1.x and 1.17.x.
