### ISSUE TITLE
Complete PHP 7.4 Test Fixes

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#4777]
**Description of the bug**

I tried running Backdrop's full test suite against PHP 7.4 and found a number of PHP notices and warnings.

Some errors that are thrown:

```
Exception Notice     bootstrap.test     613 BootstrapOverrideServerVariablesTes
    unserialize(): Error at offset 0 of 152 bytes

Exception Warning    session.inc        240 backdrop_session_initialize()      
    session_set_save_handler(): Cannot change save handler when session is
    active

Exception Notice     menu.inc          1125 menu_tree_output()                 
    Trying to access array offset on value of type bool
```

When doing a config sync on php 7.2 (or above) the following error is repeated:
```
Deprecated function: assert(): Calling assert() with a string argument is deprecated in HWLDFWordAccumulator->addWords() (line 885 of backdrop/core/includes/diff.inc).
```

It seems most or all of the errors thrown are caused when testing edge-case scenarios and may not occur in the normal usage of Backdrop, however if we are going to upgrade our testing to PHP 7.4+, we'll need to get all tests passing.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.18.x
- Web server and its version: PHP-FPM + nginx (Lando)

**Comment by quicksketch** [comment]
PR to fix all test failures in PHP 7.4: https://github.com/backdrop/backdrop/pull/3416

**Comment by indigoxela** [comment]
I can't help out with testing here, my dev VM doesn't have enough resources (CPU). After 2.5 hours under full load it managed to run until "Form API" tests. That's when I gave up - I need this machine for productive work.

I could run single tests, though, if someone provides a list of currently failing tests.

**Comment by herbdool** [comment]
@indigoxela mine finished in 2.5 hours testing this patch. I'm looking further into some fatal errors and fails - not sure if it's just some local issue. Can you check these for fatal errors:

* Entity Token
* ViewsUpgradeTestCase

And for Fails:

* Update API: Update from Drupal 7 hook order
* System: Update functionality
* Module: Enable/disable modules
* Installer (module): Installer UI tests

**Comment by indigoxela** [comment]
> Entity Token

Is this a core test? Didn't find it.

For the other failures: It makes a big difference for me if profile caching is on or off. There's already an issue for that: https://github.com/backdrop/backdrop-issues/issues/4392 (no solution yet). The fact that I can't run tests at all with caching on makes test runs sooo slow on my dev.

Now for the failures:

Views Upgrade test (ViewsUpgradeTestCase)

Passes, no exception when profile caching is off, exceptions with caching on:

```
    Notice: Undefined property: BackdropWebTestCaseCache::$originalLanguageDefault in BackdropWebTestCaseCache->tearDown() (line 160 of .../core/modules/simpletest/backdrop_web_test_case_cache.php).
    Notice: Undefined property: BackdropWebTestCaseCache::$originalLanguageDefault in BackdropWebTestCaseCache->tearDown() (line 160 of .../core/modules/simpletest/backdrop_web_test_case_cache.php).
    Notice: Undefined property: BackdropWebTestCaseCache::$originalLanguageDefault in BackdropWebTestCaseCache->tearDown() (line 160 of .../core/modules/simpletest/backdrop_web_test_case_cache.php).
    The test run did not successfully finish.
```
See related Issue https://github.com/backdrop/backdrop-issues/issues/4679

Pretty similar problems:

- Update API: Update from Drupal 7 hook order (UpdateDrupal7TestCase)
- System: Update functionality (UpdateScriptFunctionalTest)
- Module: Enable/disable modules (EnableDisableTestCase)
- Installer (module): Installer UI tests (InstallerBrowserAdministrationTestCase)

All passing when profile caching is off, total failure with caching on:

311 passes, 120 fails, 43 exceptions, and 96 debug messages.

So for me the profile caching seems to be the main problem (and I'm not the only one, there are other issues re profile caching in our queue). The patch per se makes sense.

**Comment by herbdool** [comment]
@indigoxela thanks for confirming.

I'm not sure how Entity Token got in there. I had told it to only run tests in core. But the error did show up referencing entity_token. I'll have to try run the core entity tests again.

I'm guessing that I have profile caching on? Is that the default? I'm running the tests with Lando and it's currently using MySQL 5.7.

**Comment by herbdool** [comment]
I moved the contrib modules I had out of the local site so now the Entity tests work fine. I'll try the others again.

**Comment by herbdool** [comment]
* All the Views test pass for me now.

Of the other ones I mention above:

* I get failures with InstallerBrowserAdministrationTestCase - but might be just a local file permissions issue ("Cannot chmod /app/modules/ddd_installer_test")
* I got an exception with UpdateTestContribCase ("EXCEPTION: Undefined index: basis"). Not sure why, might disappear if I started fresh.

**Comment by jenlampton** [comment]
The PR here is working for me, much better than the one in https://github.com/backdrop/backdrop-issues/issues/4531. I'm going to close that issue in favor of this one but am going to add that error message into the OP here so that people searching for it will find this issue.

**Comment by jenlampton** [comment]
PR looks great!

**Comment by quicksketch** [comment]
Thanks folks. I've merged https://github.com/backdrop/backdrop/pull/3416 into 1.x and 1.17.x.
