### ISSUE TITLE
Non-existing function system_elements() mentioned in template_preprocess_page()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4779]
See: https://github.com/backdrop/backdrop/blob/1.x/core/includes/theme.inc#L2688

I could not find any reference of that function, but in D6: https://api.drupal.org/api/drupal/modules%21system%21system.module/function/system_elements/6.x

Is that meant to be https://api.backdropcms.org/api/backdrop/1/search/system_element_info now?

**Comment by indigoxela** [comment]
> Is that meant to be https://api.backdropcms.org/api/backdrop/1/search/system_element_info now?

Yes, it has been renamed, here's the related [D issue](https://www.drupal.org/project/drupal/issues/572932).

**Comment by klonos** [comment]
OK, lets' fix it then: https://github.com/backdrop/backdrop/pull/3418 😉 

I've searched and could not find any other instances of `hook_elements()` in our codebase.

**Comment by indigoxela** [comment]
I wonder if it makes sense to completely remove that line, as to me it seems unrelated.

hook_element_info() - Allows modules to declare their own Form API element types and specify their default values.

template_preprocess() - Adds a default set of variables for variable preprocessors and templates.

**Comment by klonos** [comment]
🤷

**Comment by BWPanda** [comment]
I think its still relevant. Change looks good. RTBC.

**Comment by laryn** [comment]
Thanks @klonos, @indigoxela and @BWPanda. I've merged [this](https://github.com/backdrop/backdrop/pull/3418) into 1.x and 1.22.x.
