### ISSUE TITLE
An arbitrary role can accidentally be set as admin when the role that was previously set as admin is deleted

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4783]
I've noticed this while working on #3813

## Steps to reproduce:

1. Depending on what you have access to, either:
   1. Go to `admin/config/development/configuration/single/export` -> Select "Configuration" from the group dropdown -> then select "System core settings"
   1. Open your `system.core.json` config file
1. Inspect the `user_admin_role` setting and confirm that it is set to: `"user_admin_role": "administrator"` 👍 
1. Go to `admin/config/people/roles`
1. Expand the "Administrator role" fieldset -> confirm that the "Administrator" role is selected as admin 👍 
1. Add a new role
1. Expand the "Administrator role" fieldset -> set the newly-added role from the previous step as admin -> save
1. Expand the "Administrator role" fieldset -> confirm that the new role is now configured as admin 👍
1. Once again, either check your `system.core.json` config file, or in `admin/config/development/configuration/single/export` -> confirm that the `user_admin_role` setting is set to the machine name of the new role, instead of `"administrator"` 👍 
1. Back in `admin/config/people/roles` -> delete the role you have created (which is also set as admin).
1. Yet once again, either check your `system.core.json` config file, or in `admin/config/development/configuration/single/export` -> confirm that the `user_admin_role` setting is missing/deleted 👍 (perhaps that shouldn't happen and this is the actual culprit? ...but that's the way things work currently)
1. Back in `admin/config/people/roles` -> Expand the "Administrator role" fieldset -> ...

## Actual behavior

A random role is selected in the dropdown menu (whichever role is at the top of the list; usually "Editor") 👎 ...this means that if people delete a role that was previously set as admin, and then they reorder the roles and save the form (without checking the "Administrator role" fieldset, which is collapsed by default), they may set a random role as admin ...which means that this role will be granted ALL permissions from there on 👎 👎 👎 👎 

## Expected behavior

Things we could do:

1. Make sure that the "disabled" option is the first option in the dropdown menu, so that that is the one that gets selected by default.
1. When deleting the role that's set as admin:
   - throw a warning
   - set the "Administrator role" fieldset to be expanded instead of collapsed (although people may still miss this and accidentally set an arbitrary role as admin).
1. Make sure that after a role that was previously set as admin is deleted:
   - the admin dropdown is set to the "disabled" option (so that no random role gets accidentally set as admin)
   - instead of removing the `"user_admin_role"` entry in `system.core.json`, explicitly set it to `"user_admin_role": 0`
1. In the "Delete role" confirmation dialog:
   - show a warning if the to-be-deleted role is set as admin
   - provide a dropdown, to prompt selecting a new role to be set as admin ...or select the "disabled" option

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/3423

...I might take some time to write tests about all this.

**Comment by indigoxela** [comment]
@klonos the Tugboat sandbox failed, and the other one leads to the installer. Mind to close/open your PR to get fresh sandboxes?

**Comment by klonos** [comment]
I've tried closing/re-opening several times @indigoxela but it seems that both ZenCI and Tugboat hate me 😓 ...or at least this specific PR.

I tried to see if there's any change in my PR that could possibly trip the installer, but could not think of anything 🤷 ...I'd appreciate it if someone tried pulling the changes and trying on their local, to see if there's any specific error.

**Comment by indigoxela** [comment]
It's a fatal (WSOD): "Got error 'PHP message: PHP Fatal error:  Cannot redeclare user_update_1018()".

Increase the update number :wink:

**Comment by klonos** [comment]
>> I tried to see ... but could not think of anything
>
> Increase the update number 😉

🤦

**Comment by klonos** [comment]
Thanks for catching that one @indigoxela 🙏 ...since my local was already installed, I was getting no errors, but the fresh installation revealed the culprit.

I've fixed the duplicate hook update number, and also a failing test. ZenCI and Tugboat sandboxes are happy now, and tests are passing.

**Comment by indigoxela** [comment]
> I've fixed the duplicate hook update number

Never mind, that also happened to me when rebasing. :wink: 

I'm curious: why did you choose integer `0` as the default? Isn't that a bit misleading?

**Comment by klonos** [comment]
> why did you choose integer `0` as the default?

This is what the `'#options'` array index was set to for that select before for the option "disabled". See: https://github.com/backdrop/backdrop/blob/1.x/core/modules/user/user.admin.inc#L515

You can test this in a demo sandbox of the current 1.17.4 version:

1. Go to `admin/config/people/roles`
1. Expand the "Administrator role" fieldset -> change the admin user select to "disabled" -> save
1. Go to `admin/config/development/configuration/single/export`
1. Select "Configuration" from the group dropdown -> then select "System core settings"

You will notice that: `"user_admin_role": "0",`

Now, if you are wondering why `0` (numeric) instead of `"0"` (string), then it's the same reason as #2557 🤷

**Comment by indigoxela** [comment]
> Even before my changes, this is what the '#options' array index was set to

Ah, got it.

**This is how I tested:**

First I verified the dangerous current behavior on an 1.17.4 install:

- Added a new role
- Set that to the "admininstrator role"
- Deleted that role
- Saved the role form on admin/config/people/roles without further checking the (hidden / collapsed) admin role setting
- Went to admin/config/development/configuration/single/export
- Verified that "user_admin_role" was set to editor :-1: 

Then I repated the same steps in the sandbox:

- Even after step 3 the user_admin_role was already set to "0" (disabled)
- The same after saving the form on admin/config/people/roles (without changes)

I can confirm that the PR prevents the accidental admin role switch. Works for me.

**Comment by indigoxela** [comment]
The code is looking good now, many thanks for switching back the load order in function user_role_delete(). RTBC from my side.

Regarding the wording of the update hook text - I'll leave that to additional reviewers (not my area of expertise).

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3423 into 1.x and 1.17.x. Thanks @klonos and @indigoxela!

I did shorten the update hook docblock by one word to make it all fit on one line to match coding standards. Great job!
