### ISSUE TITLE
Menu UI: The "Show menu in language" option does not filter by language

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4784]
**Description of the bug**

The "Show menu in language" option to filter Menu Links by language does not seem to filter the listed items.

**Steps To Reproduce**

To reproduce the behavior:
1. Enable content translation module + Locale module
1. Add one language
1. Translate about page, place new node into menu
3. Visit Menu UI, confirm "Show menu in language" select lis is present
1. Use this select to filter the menu

**Actual behavior**

Page reloads, same menu items present

**Expected behavior**

Page reloads, only "all" items, and items in specified language should be present

---

PR: https://github.com/backdrop/backdrop/pull/3425

**Comment by indigoxela** [comment]
Confirmed, the language filter on menu items currently doesn't work.

The PR fixes that. This is how I tested:

- Made the sandbox multilingual (installed locale, language, content translation)
- Added a language
- Created a page with a menu item in English
- Translated that page to the other language (with menu item)
- Went to admin/structure/menu/manage/main-menu and switched the filter

Works for me.

**Comment by indigoxela** [comment]
The change is minimal and absolutely makes sense.

Although I'm sure that the failing tests are unrelated - @jenlampton could you please restart the sandbox to see if tests are passing. Your PR is RTBC otherwise.

**Comment by klonos** [comment]
I've also tested this and confirm it works. Code also seems right 👍 ...only thing as @indigoxela said, lets please restart tests to verify that the failures are indeed random.

**Comment by jenlampton** [comment]
I've closed/opened the PR for a fresh test run. 🤞

**Comment by klonos** [comment]
Tests are happy 👍

**Comment by olafgrabienski** [comment]
Strange, I **can not** reproduce the bug. On a Tugboat demo site, the "Show menu in language" option **does** filter by language without any issues.

The STR in the issue description look incomplete to me. Here is what I did on my demo site:

- Enabled the core modules Content Translation, Language, and Locale.
- Added a language (German).
- Enabled Multilingual support with translation for the *Page* content type (admin/structure/types/manage/page).
- Edited the *About* page and set its language to English.
- Translated the *About* page to German. Provided a menu link in *Primary navigation*, using the node form.
- Went to the *Primary navigation* link list (admin/structure/menu/manage/main-menu).
- Made sure that the "Show menu in language" option exists.

Result: the "Show menu in language" option was set to English. The list displayed two menu links:
- Home (Language: All)
- **About (Language: English)**

After setting the option to German and hitting the Filter button, these items were displayed instead:
- Home (Language: All)
- **Über (Language: German)**

That's how it should work, as far as I know. Did I miss anything?

**Comment by indigoxela** [comment]
> On a Tugboat demo site, the "Show menu in language" option does filter by language without any issues.

Is that menu item you tested with a parent or a child of another menu item? If it's not a child (sub-) item, can you check that, too?

**Comment by olafgrabienski** [comment]
> If [the menu item is] not a child (sub-) item, can you check that, too?

Sure! The results are the same. Works still as expected for me:

```
Show menu in language: English

- Home (All)
- About (English)
  - About us (English)

Show menu in language: German

- Home (All)
- Über (German)
  - Über uns (German)
```

**Comment by indigoxela** [comment]
> Sure! The results are the same

Strange, still doesn't work for me. On the url en/admin/structure/menu/manage/main-menu?langcode=en I get:

![menu-items-lang](https://user-images.githubusercontent.com/842066/101471115-333c8e80-3947-11eb-9d35-dd46ac847c76.png)

Ah, wait... the parent item in my example is language neutral, but the child is German. If I switch the parent item to German, too, the filter works. However, I don't think that this is the desired behavior.

@olafgrabienski can you verify that (parent language matters)?

**Comment by olafgrabienski** [comment]
> the parent item in my example is language neutral, but the child is German

Nice catch! Was able to reproduce it. All sub-items (of different language) of a language neutral parent item are displayed, no matter how the filter is set. Example:

```
Show menu in language: English

- Contact (All)
  - Contact us (English)
  - Kontaktieren Sie uns (German)Show menu in language: English | German | All

Show menu in language: German

- Contact (All)
  - Contact us (English)
  - Kontaktieren Sie uns (German)

Show menu in language: All

- Contact (All)
  - Contact us (English)
  - Kontaktieren Sie uns (German)
```

@jenlampton Can you confirm that the language neutral parent item is the actual issue here?

**Comment by quicksketch** [comment]
I can confirm based on the code that the problem here is with _any_ 2nd-level menu items or lower. This includes when the parent is language-neutral, but also in the unusual situation where a parent is another language. The language of the parent isn't really the problem, it's that the 2nd-level or deeper doesn't respect the language filter ever. The one-liner in the PR fixes this problem seems like it's an obvious mistake in the implementation.

I've merged https://github.com/backdrop/backdrop/pull/3425 into 1.x and 1.17.x. Thanks folks!

**Comment by jenlampton** [comment]
> @jenlampton Can you confirm that the language neutral parent item is the actual issue here?

Yes, I had a language-neutral parent
