### ISSUE TITLE
Replace "Less then/More then" with "Less than/More than"

### ISSUE THREAD

**Issue by Radcliffe** [backdrop/backdrop-issues#4786]
There are several instances in the code of the phrases "less then" and "more then". These should be changed to "less than" and "more than", respectively.

**Comment by indigoxela** [comment]
@Radcliffe Nice catch. Mind to provide a pull request?

**Comment by BWPanda** [comment]
Glad to see I'm not the only one trying to enforce good grammar/spelling 😊

**Comment by klonos** [comment]
Thanks for reporting and for providing a PR @Radcliffe 👍

**Comment by BWPanda** [comment]
Thanks @Radcliffe! I found two more instances which I added to your PR, then merged https://github.com/backdrop/backdrop/pull/3426 into 1.x and 1.17.x.
