### ISSUE TITLE
Do not capitalize words in the label of the "Show End Date" checkbox

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4791]
Add a date field in any content type, and configure it to _optionally_ collect an end date:

![image](https://user-images.githubusercontent.com/2423362/101543853-7a5d6a80-39ad-11eb-98b4-4df75df2bf60.png)

**Comment by indigoxela** [comment]
Tested in the sandbox, works for me.

Here's a screenshot:
![show-end-date-no-uppercase](https://user-images.githubusercontent.com/842066/101657054-ba6f2c80-3a43-11eb-86e1-24cd91e67486.png)

It's a minimal spelling-only fix, RTBC.

**Comment by klonos** [comment]
I've added the 1.17.5 milestone, although I shouldn't do that (because I was the one to add the milestone label)

**Comment by BWPanda** [comment]
Looks good. Thanks @klonos & @indigoxela. I've merged https://github.com/backdrop/backdrop/pull/3430 into 1.x and 1.17.x.
