### ISSUE TITLE
[UX] Add a "Cancel" link in the role edit form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4792]
I noticed that there is no "Cancel" link in that form while working on #3813.

We should add one.

**Comment by indigoxela** [comment]
Nice catch.

Tested in the sandbox: Followed the "Configure role" links on admin/config/people/roles. Cancel link is there and leads back to the roles overview. Works for me.

Here's a screenshot of the edit form:

![role-edit-cancel](https://user-images.githubusercontent.com/842066/101656410-f48bfe80-3a42-11eb-852a-3675ac6b461e.png)

**Comment by indigoxela** [comment]
The change is small, code looks good. The existing functional test has been enhanced to also check for a cancel link for the configure action (edit form). RTBC.

**Comment by BWPanda** [comment]
Other cancel links take you back to the page you came from (not a hard-coded path): https://github.com/backdrop/backdrop/blob/26101dbdc91f15b1f6b432f1428732bcec77f899/core/modules/user/user.module#L3128

Wonder if it's worth doing the same here...? Or is it not possible to access this form from anywhere other than the Roles overview page?

**Comment by klonos** [comment]
Unless you create a custom form that replaces the one we provide OOTB, I cannot imagine how that could happen @BWPanda

**Comment by quicksketch** [comment]
I don't think we need to make this as complicated as the node/term/user forms, where there are lots of different ways you might get to the edit form. The existing Cancel link in `user_admin_role()` also just assumes linking back to the main roles page, and this is consistent with that Cancel link. 

I merged https://github.com/backdrop/backdrop/pull/3431 into 1.x and 1.17.x. Thanks @klonos, @indigoxela, and @BWPanda!
