### ISSUE TITLE
Menu items not added to main menu automatically

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4797]
People coming from Drupal are [having issues](https://forum.backdropcms.org/forum-topic/menu-items-not-showing) with menu items in their modules not appearing in the main menu as they did in Drupal. After looking into this and reproducing the problem, I discovered that a [change in 2016](https://github.com/backdrop/backdrop/commit/e445c758d4ce13c1e718da20ec75d28f6b9658d7) made it so that menu items were now saved to a hidden 'internal' menu instead of the 'main menu'. @quicksketch's comment from the linked issue was that:

> If you want your menu links to be in the `main-menu` by default, you now have to specify `$item['menu_name'] = 'main-menu'` in `hook_menu()`.

This is all well and good, but the [documentation for `hook_menu()`](https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu/1) was never updated, and [no change record exists](https://api.backdropcms.org/change-records?field_impacts_value=All&keys=hook_menu)...

We therefore need to update the documentation and create a change record.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/4109

It:
- Updates the documentation for `menu_name` (as described above)
- Fixes text overflowing the 80-character margin
- Standardises the quoting of list keys (as per https://docs.backdropcms.org/doc-standards#lists)
- Standardises the use of `(optional)` and `(default)` (as per https://docs.backdropcms.org/doc-standards#lists)

**Comment by BWPanda** [comment]
And here's the change record: https://docs.backdropcms.org/change-records/hook_menu-defaults-to-putting-menu-items-in-an-internal-hidden-menu

**Comment by BWPanda** [comment]
Since it was just a documentation change, I went ahead and merged https://github.com/backdrop/backdrop/pull/4109 into 1.x.
