### ISSUE TITLE
Add token module to core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#480]
Steps to moving token (contrib module) into core:
- [x] Move Token requirements check into system module.
- [x] Move Token cache table schama definition into system module.
- [x] Add a 'token type' to hook_entity_info [d.o](https://www.drupal.org/node/737726)
- [x] Move token helper functions into token.inc.
- [x] Move Token cache clearing into core.
- [x] Move Book, Field, and Menu tokens into respecive modules.
- [x] Move Token libraries into system module.
- [x] Move Token theme functions into system module.
- [x] Move token support for email messages into user.admin.inc.
- [x] Move tests into simpletest module
- [x] Move Node tokens from token.inc into node.tokens.inc
- [x] Move Taxonomy tokens from token.inc into taxonomy.tokens.inc
- [x] Move File tokens from token.inc into system.tokens.inc
- [x] Move Entity tokens from token.inc into entity.tokens.inc
- [x] Move User tokens from token.inc into user.tokens.inc
- [x] Move Current page tokens from token.inc into system.tokens.inc
- [x] Move URL tokens from token.inc into system.tokens.inc
- [x] Move Menu tokens from token.inc into system.tokens.inc
- [x] Move Array tokens from token.inc into system.tokens.inc
- [x] Add default_token_formatter to field info
- [x] Add token browser to field UI
- [x] Fix comment author name token as per https://www.drupal.org/node/920056

Things to consider improving:
- [x] Refactor `token_node_menu_link_load` or merge into core
- [x] Refactor `token_menu_link_load` or merge into core
- [x] Refactor `_token_menu_link_translate` or merge into core
- [x] Rename `token_clear_cache` to `token_cache_clear` for consistency (?)

Things removed from token module:
- Token support on block titles
- Devel module support (should be moved into devel module)
- Random tokens [random:hash] and [random:number]
- Token [node:type] replaced with [content-type:machine-name]
- Token [node:type-name] replaced with [content-type:name]
- Token [node:content-type] replaced with [content-type:machine-name]
- Token [comment:name] replaced with [comment:author:name]
- Token [term:vocabulary:vid] removed

Function name changes
- `_token_field_info` renamed to `_field_token_info`
- `token_pre_render_field_token` renamed to `field_pre_render_token`

This issue is Required by #87

**Comment by jenlampton** [comment]
Great start @enzolutions !  thanks so much for taking a stab at this :)  We'll take a closer look after 1.0.0 is out :)

**Comment by enzolutions** [comment]
I did a version without drupal compatibility https://github.com/backdrop-contrib/token

**Comment by quicksketch** [comment]
Great @enzolutions! We'll start taking a look at integrating this into core in the coming months.

Unless I'm mistaken, I think all of the functionality within Token module should be distributed between other core modules:

- The token additions should be distributed to their appropriate core modules (Taxonomy, Node, User, System, File, Book, Menu, Field, etc.)
- The token page display should be move to system.module.
- The token dialog should be converted to use the core dialog API.

Then the Token module itself will no longer be needed at all. During the upgrade path, we should disable the existing Token module if users have installed it before it was merged into core.

**Comment by klonos** [comment]
I would also like to suggest to add the feature of allowing tokens to be used in the default value of fields.

- Respective issue in d.org for D8: https://www.drupal.org/node/1070878
- D7 module: [Field Default Token](https://www.drupal.org/project/field_default_token)

PS: I'll file an issue in https://github.com/backdrop-contrib/token too.

**Comment by quicksketch** [comment]
> I would also like to suggest to add the feature of allowing tokens to be used in the default value of fields.

Yep, also a good idea. However, I'd like to implement the parts that we're able to as soon as possible. If we add features to Token module that make porting it to core difficult, we might delay the entire core integration. I'm not sure this would be the case, but it may be better to try and implement the token support for fields directly into core rather than into Token. Core already has token support, it's just lacking a complete set of tokens and the UI.

**Comment by jenlampton** [comment]
I'm making a ton of progress, I now have working tokens (in modals!) in core.  I just need to finish up moving a few more token definitions around, and consider a little more refactoring...

**Comment by quicksketch** [comment]
I've resolved all the test failures in @jenlampton's PR in a new branch: https://github.com/quicksketch/backdrop/tree/jenlampton-480-token-in-core

I've also added the update hook to disable the contrib Token module (if present) and alter the module list to prevent the contrib Token module from being enabled.

![token-disabled](https://cloud.githubusercontent.com/assets/100206/7306215/649e4cd2-e9b8-11e4-9fac-5db2d613e165.png)

In my testing, everything worked great. Good job on the port @jenlampton! There's still some minor cleanup that could be done to consolidate the tests in one location. Right now the token tests are split between system.test and token.test. We should probably merge everything into the single token.test file.

**Comment by quicksketch** [comment]
> Refactor token_node_menu_link_load or merge into core
> Refactor token_menu_link_load or merge into core
> Refactor _token_menu_link_translate or merge into core

I finished up these changes tonight with the following modifications: token_menu_link_load () is now _token_menu_link_load(), but it no longer duplicates core functionality. Instead of being a copy of `menu_link_load()`, `menu_link_load()` now takes a parameter for `$skip_access_check` (which defaults to FALSE). Tokens can now use this directly to get the same behavior from D7.

I also moved `_taxonomy_token_term_parent_list()` into `taxonomy.tokens.inc` and `_field_token_info()` into `field.tokens.inc`. That gets all of our module-specific code into module .inc files and out of the core `token.inc` file.

I think the PR at https://github.com/backdrop/backdrop/pull/840 is ready to go. I'll give this another read through to see if I can dig up anything else.


>  Rename token_clear_cache to token_cache_clear for consistency (?)

**Comment by quicksketch** [comment]
> Right now the token tests are split between system.test and token.test. We should probably merge everything into the single token.test file.

This is also done.

**Comment by quicksketch** [comment]
I've read through the PR 2 more times to correct various typos and clean up the docblocks (https://github.com/quicksketch/backdrop/commit/dceaaadbb06bc2f13fe1efa2d396fb88becaaa0b) and ensure that we maintain the existing tokens even though they are deprecated (https://github.com/quicksketch/backdrop/commit/c6d621445708882e56b63abfe063cb54741c50f8).

This is a great enhancement to core. My own reading and reviewing can't find any further issues, so I'm going to merge the PR so we'll have a few weeks for wider testing before 1.1.0.

**Comment by klonos** [comment]
So great! Backdrop is truly becoming what Drupal 7 was supposed to be. The mere fact that once installed, you (will) get views, token, pathauto, admin_menu (+ lets not forget the removal of overlay!!!) is so convenient. And all those little improvements and illumination of annoyances! So exciting!!! Thank you guys. :+1:

**Comment by docwilmot** [comment]
:+1:

**Comment by docwilmot** [comment]
I feel foolish asking this,but where can I test this? is there a UI somewhere?

**Comment by quicksketch** [comment]
The only place it's visible (until we merge pathauto) is on the form for Account Settings, where you set up all the e-mails for password reset, new accounts, etc. Instead of listing 6 tokens in the description, there is now a link for "Browse available tokens".
