### ISSUE TITLE
[UX] Remove all instances of "please contact an administrator" from messaging

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4802]
I really hate it when Backdrop tells people to contact an administrator. 

For one, lots of people are the administrator when they see that message. Telling them to contact themselves is unhelpful. 

For two, lots of people have no idea who an administrator is, or how to contact them. Telling this person to do so is also unhelpful. 

For three, The people who can contact an administrator will usually do so anyway, when they get any kind of error - they don't need to be told to do it. 

## Proposal: 

I would like to remove all instances of 'please contact a site administrator' from core. 

Related: 
* see related conversations in #2229 
* Comment: https://github.com/backdrop/backdrop-issues/issues/3824#issuecomment-743503886

**Comment by klonos** [comment]
Fair enough 👍

**Comment by jlfranklin** [comment]
This is so brilliant, I wish GitHub would let me respond two thumbs up.

I can't tell you how often I've read that message on any number of platforms and said, "I *am* the administrator, please give me a clue!"

**Comment by jenlampton** [comment]
Same!

**Comment by BWPanda** [comment]
I grep-ed core to look for instances of 'contact * admin' and text along those lines. Found a few and so made a PR: https://github.com/backdrop/backdrop/pull/3446 Let me know if I missed any.

**Comment by indigoxela** [comment]
> Found a few and so made a PR

Many thanks for your PR! I've left two comments with questions / suggestions.

**Comment by BWPanda** [comment]
Updated PR based on feedback.

**Comment by indigoxela** [comment]
> Updated PR based on feedback.

Many thanks!

At the risk to annoy you... :smile: 
There's another suggestion for that phpinfo() message.

**Comment by stpaultim** [comment]
This seems to be an easy issue that stalled because of a disagreement over the code suggestion in PR by @indigoxela. Has that been resolved?

Atten: @BWPanda or @jenlampton

**Comment by BWPanda** [comment]
@stpaultim I just resolved it. Unless other core committees disagree, the the PR stands as-is.

**Comment by indigoxela** [comment]
> Has that been resolved?

Sort of, I guess. :wink:  My suggestion (and it was only meant to be a suggestion) has been rejected.

What the PR needs, though, is a rebase. It's  241 commits behind backdrop:1.x.

**Comment by BWPanda** [comment]
PR updated to merge in latest 1.x commits.

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...everything looked good to me, besides a sentence that was missing a verb and sounded odd. I've left a couple of suggestions on how to fix, but you may have something better. Once that's fixed, this is RTBC from me 👍🏼

**Comment by BWPanda** [comment]
Fixed, thanks @klonos.

**Comment by quicksketch** [comment]
Thanks folks! Because this changes a number of translated strings, I've only merged it into 1.x (for 1.21.0). With the release around the corner I figure keeping PRs that only include string changes in the 1.x branch is going to be fine. Thanks @BWPanda, @jlfranklin, @indigoxela, @klonos, and @jenlampton!
