### ISSUE TITLE
D7 upgrades: Make the reminder message about update_free_access a proper warning

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4804]
When you upgrade a site from D7 to Backdrop, after running the pending updates, you get this message:

![image](https://user-images.githubusercontent.com/2423362/102012479-5904d180-3d53-11eb-937f-5859a54ea035.png)

That warning in bold text should be a proper warning message, using `backdrop_set_meassge()`

**Comment by klonos** [comment]
...like this:

![image](https://user-images.githubusercontent.com/2423362/102012595-f6f89c00-3d53-11eb-87c9-e6f14719b87c.png)

**Comment by findlabnet** [comment]
An error message on status report page and red icon in the administration bar is not enough?

**Comment by klonos** [comment]
This is shown right after the update, so no admin bar, and no red icons. The intention is to get people to "fix" this issue before clicking the "Home page", and since most don't read help text, they might miss the warning/reminder if just in bold text.

**Comment by indigoxela** [comment]
Here's the code: https://github.com/backdrop/backdrop/blob/21244974670b3845dd6a2503fd9b1c042f2e7bf4/core/update.php#L231

**Comment by klonos** [comment]
Yup, I've already filed a PR for this about an hour ago @indigoxela 😅 ^^

**Comment by indigoxela** [comment]
> Yup, I've already filed a PR

How could I miss that! :laughing:

Works as expected, here's a screenshot from a local test with the patch applied:

![update-free-access-warn](https://user-images.githubusercontent.com/842066/102015882-696e7980-3d5e-11eb-92a8-09742cf16a78.png)

I admit, for a moment I thought, this should be an error, not a warning. But then I realized that most people will connect this with the update action - they could get the impression that something went wrong. "Warning" is correct here.

The message is definitely better visible now. Works for me.

**Comment by klonos** [comment]
Thanks for the prompt testing @indigoxela 🙏 

> ...for a moment I thought, this should be an error, not a warning.

Yeah, an error would have implied a failed upgrade, which is not what's going on here; this is meant to serve as a security reminder. And yeah, also not easy to miss not that it's a warning.

**Comment by klonos** [comment]
I've rebased and removed `t()` from the PR.

I've also filed #5394 as a separate issue, to figure out why strings in update.php are not passed through any translation function.

**Comment by klonos** [comment]
@indigoxela @docwilmot are you happy with the change now?

**Comment by indigoxela** [comment]
> are you happy with the change now?

Haven't been unhappy before, just a little concerned. :smirk:

I did a quick local check: yes, still works. This is what it looks like now (using code tags in message):

![update-free-access-reminder](https://user-images.githubusercontent.com/842066/145716285-b6f78846-8101-4753-8bcd-32afb8fd9d64.png)

RTBC :+1: , as I'm pretty sure, @docwilmot is now fine with it, too.

**Comment by BWPanda** [comment]
Left a question/suggestion in the PR: https://github.com/backdrop/backdrop/pull/3444#pullrequestreview-845506793

**Comment by klonos** [comment]
@BWPanda there's a catch. I've responded in the PR.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3444 into 1.x and 1.21.x. Thanks folks!
