### ISSUE TITLE
SA-CORE-2014-006

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#481]
See https://www.drupal.org/SA-CORE-2014-006.

The process for doing security updates is as follows:
- Look for the commit that contains only the Drupal release number.
- Review the diff (or create a patch from it).
- Apply these same changes to Backdrop.

**Comment by quicksketch** [comment]
Double-checked: 

- [x] Session hijacking (Drupal 6 and 7)
- [x] Denial of service (Drupal 7 only)
