### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in path_entity_load() (line 427 of ../path.module).

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4810]
**Description of the bug**

A Backdrop website running on PHP 7.1.22 is giving the following warning:

`Warning: Invalid argument supplied for foreach() in path_entity_load() (line 427 of /var/www/docroot/core/modules/path/path.module).
`

Apparently, the warning triggered because the argument `$path_info['entity type']` in [line 427](https://github.com/backdrop/backdrop/blob/f3fa59b6cb8cb15e06e0ccf040fd5bd6a48d9690/core/modules/path/path.module#L427) doesn't exist.

**Additional information**

The offending block at whole looks like:

```
    foreach ($all_path_info as $path_info) {
      if (isset($path_info['entity type'])) {
        $path_entity_types[] = $path_info['entity type'];
      }
    }
```

Now, adding simple check if `$all_path_info` is empty before executing loop like this:

```
    if (!empty($all_path_info)) {
      foreach ($all_path_info as $path_info) {
        if (isset($path_info['entity type'])) {
          $path_entity_types[] = $path_info['entity type'];
        }
      }
    }
```

not only suppresses the warning messages, but saves useless loop from executing.

**Comment by indigoxela** [comment]
@alanmels Many thanks for digging into this and for providing a pull request :+1: 

Can you also provide steps to reproduce? Although your code's looking good, we'd need a way to verify.

**Comment by alanmels** [comment]
@indigoxela, just install Backdrop on a system with PHP 7.1.22 and browse some nodes. Then look at the website's log.

**Comment by indigoxela** [comment]
> just install Backdrop on a system with PHP 7.1.22

Meh, I don't have that version available. I could test 5.6, 7.0, 7.3, 7.4. Are you sure, it's really that specific PHP version? Couldn't it be something in that site's setup? Possibly a module?

**Comment by klonos** [comment]
Our Tugboat demos use php 7.2.34, and the ZenCI PR sandboxes use 5.3.29.

I use lando on my local, and AFAIK you can only specify minor versions of PHP. So I've installed a vanilla site with php 7.1, which resulted in 7.1.33, and then tested with some users/content generated with devel_generate. I wasn't able to reproduce 🤷 

Having said that, the code change does make sense @alanmels

**Comment by alanmels** [comment]
I am trying to replicate this on a fresh install without success, so it might be not about PHP version, but something else. 

I remember trying [node_export module](https://github.com/backdrop-contrib/node_export), which in turn installed [UUID module](https://github.com/backdrop-contrib/UUID) as a requirement, then turned them off. That could be culprit here.

**Comment by indigoxela** [comment]
@alanmels have you been able to figure out the root cause of the warning you see? Are you still sure that it's a core bug?

**Comment by alanmels** [comment]
@indigoxela, thank you for reminding about this issue. 

Unfortunately I could not replicate the issue on a fresh install and had to proceed to other priorities. I think one of the multiple contributed modules which were installed on the faulty setup could easily cause the issue. So I am more inclined to think the cause was not the core, but a contributed module. And since the problem could not be replicated, I am cancelling the PR and closing this issue.
