### ISSUE TITLE
[DX] Automate saving of default theme settings values to config.

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4814]
I'm reading through [Adding theme settings (advanced)](https://api.backdropcms.org/documentation/adding-theme-settings-advanced) in order to better understand theme settings (something which I rarely use/need), and am confused by this part near the end of that page:

> **Setting default values**
> In order to set the default value for any form element you add, you’ll need to add a simple line to your .info file: `settings[SETTING_NAME] = DEFAULT_VALUE`.

> **Initializing the default values**
> Add the following code near the top of your `template.php` file:
> ```php
> if (is_null(theme_get_setting('menu_tab_color'))) {
>   config_set('foo.settings', 'menu_tab_color', 'blue');
> }
> ```

It seems that we need to set the default value of our theme settings twice - once in the info file, and once in `template.php`. Why is this necessary?

If both places require a default value (i.e. if this isn't just outdated information), then can't we automate the latter? Can't we make it so that when a theme is installed/enabled, the info file is read, a config file is created, and default values are automatically populated?

It just seems unnecessary having to specify default values twice...

**Comment by BWPanda** [comment]
While we're at it, what is this about?

```php
// Force refresh of Backdrop internals.
theme_get_setting('', TRUE);
```

That seems very hacky... The second parameter should be the theme name, or NULL for the current theme.

**Comment by BWPanda** [comment]
I *think* I may have figured it out. Part of it at least...

So setting a default value in your info file doesn't really do anything, but it does mean Backdrop can parse the file and get your default values that way.
Setting default values in `template.php` via `config_set()` actually creates the config file where the values are then stored.

So when you need to get a theme setting value, `theme_get_setting()` first looks in config. If it doesn't find the value there, it then parses the info file.

If we only specify the default value in `template.php` via `config_set()`, it'll still work since `theme_get_setting()` checks config first. **But** if your theme is used as a base theme and never actually enabled, that initialisationis never run. `theme_get_setting()` checks base themes for theme setting values, so that's why the default value in the info file is required (so the default value can be retrieved outside of config).

So we've established that the default value *needs* to be set in the info file. But why does it need to be duplicated in `template.php`? Even if we didn't create a config file with default values, anytime the theme setting is needed, `theme_get_setting()` checks the info file anyway if config is empty... And as soon as the theme settings form is saved for the first time, the config file is created. So what's the big deal?

The best I can figure is that a lot more work is needed to get the default values from the info file than from config. Based on the code in `theme_get_setting()`, it first tries to load config, then if that fails it parses the info files of *all* enabled themes. Then it gets the default value from the specified theme's info file.

So I assume that while you *could* just set the default value once in your theme's info file, it's better performance-wise to *also* create the config file in `template.php` with default values there too.

Can someone with more knowledge about this please confirm I have the above all correct?

Two questions then remain:
- Can we not make it so that the creation of a theme's config file with default values happens automatically upon the theme being enabled for the first time?
- What's with `theme_get_setting('', TRUE);`? How does that work and why is it necessary?

**Comment by klonos** [comment]
Seems that once we got everything answered, we need to add some inline comments to our code + perhaps also update our online documentation. That will prevent others in the future for this kind of head-scratching.

**Comment by indigoxela** [comment]
Strange, I never used config_set() in a theme. `theme-settings.php` and `theme_get_setting()` usually do the trick for me.

This is how I'm doing it (wrong?):

1. Define the default setting in MYTHEME.info `settings[key] = value`
2. Add the file theme-settings.php with hook_form_system_theme_settings_alter(), define *only* the form fields there
3. Do whatever I need to do with that settings variable in template.php - grab the setting with theme_get_setting()

The rest is dark magic. (I find it spooky, if I compare it to module development.)

**Comment by docwilmot** [comment]
I have wondered about this before. I think its just a remnant from the D7 conversion process that never really got fully worked out. It looks to me like we should decide to use one or the other (template.php vs info file) and fix the code to do it that way. Which method do you think we should choose?

**Comment by BWPanda** [comment]
@indigoxela While defining fields in `hook_form_system_theme_settings_alter()` will work, you can also just define them outside of any function and they'll still work.

@docwilmot Well as I discussed above, it seems that defining default values in the info file only will work (as @indigoxela has experienced, though there might be performance issues), but that defining only in template.php might not work with base themes... I'd be interested to do some testing with all this.

**Comment by docwilmot** [comment]
> While defining fields in hook_form_system_theme_settings_alter() will work, you can also just define them outside of any function and they'll still work

We're considering changing that: https://github.com/backdrop/backdrop-issues/issues/4438
> Well as I discussed above, it seems that defining default values in the info file only will work

Then maybe make this a documentation issue and modify the advice to `"Add the following code near the top of your template.php file: if (is_null(theme_get_setting('menu_tab_color'))) { ..."` to say this is optional.

**Comment by BWPanda** [comment]
Ok, so I can't really test this. I don't know what I'm doing, what results I'm getting, or even if I'm doing it right. So I think I'll just wait and see if anyone can confirm that there's a performance issue with only using info files for deault values...

**Comment by indigoxela** [comment]
> I think I'll just wait and see if anyone can confirm that there's a performance issue with only using info files

I wouldn't expect a performance issue. Both, config_get() and theme_get_setting() use a static cache, both read from the file system - one from the settings json file, one from the theme's info file. So at least in theory there shouldn't be any difference re performance.

Regarding documentation: I find the "Initializing the default values" section a bit confusing, possibly even misleading.

**Comment by BWPanda** [comment]
@indigoxela Regarding performance, `theme_get_setting()` uses a static cahe for config, but *not* for reading from info files. If the value is not found in config, *all* themes info files are parsed and the value obtained that way. However this value is never saved back to the static cache, so this process is repeated each time a value is requested until the config value is set by saving the settings form for the first time.

Or am I reading the code wrong...?

**Comment by indigoxela** [comment]
> Or am I reading the code wrong...?

I have to admit, I only had a quick look at both function's api pages. I didn't dig any deeper. So you might be right.

But I never had any trouble with it. Usually I either set an additional body class or add something to the page head (css, setting...) based on the theme setting, so I suppose the page cache catches this anyway.

**Comment by jenlampton** [comment]
I think most of this might be related to the fact that we don't have install, uninstall, or update functions for themes.

**Comment by docwilmot** [comment]
> I think most of this might be related to the fact that we don't have install, uninstall, or update functions for themes.

Thats because we don't install or uninstall, so we just need `hook_themes_enabled()`.

But where has this issue gotten to though? A bit lost as to what we're looking or waiting for now.

**Comment by BWPanda** [comment]
@docwilmot Status of this issue:

- Is this statement correct? "Default values for theme settings must be set in both the theme's info file (for when used as a base theme) and in `template.php` (for performance reasons)."
- If not correct, let's work out what the situation is and update the documentation accordingly
- If correct, can we automate the setting of default values in `template.php` to make less work for themers?
- What's up with `theme_get_setting('', TRUE);`? Is that a hack? Is it necessary? Can we document it better or make it less ambiguous?

**Comment by jenlampton** [comment]
> Is this statement correct? "Default values for theme settings must be set in both the theme's info file (for when used as a base theme) and in template.php (for performance reasons)."

No, I don't think this is correct. The code in [`theme_get_setting()`](https://api.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme_get_setting/1) will first check config, and then check the info file if there is not a setting in config. There should never be a case where `theme_get_setting()` returns NULL if the value is defined in the info file, so the code in template.php would never be executed.

**Comment by BWPanda** [comment]
@jenlampton I think you're saying that we should only need to specify default values in the info file, and that using the `template.php` file for that reason is not actually required...?

If that's the case, what about when a theme with settings is enabled, but the settings form is never accessed? In that case, the config file is never setup, and so anytime the default value is needed, `theme_get_setting()` has to read the info file. While this process works, isn't there a performance impact of needing to parse all theme's info files each time `theme_get_setting()` is called? From what I can see, the info file values are never cached and are re-read each time...

**Comment by docwilmot** [comment]
I suppose one way could be to save all of a themes settings from the info file to config when that function is first called?

**Comment by jenlampton** [comment]
> I think you're saying that we should only need to specify default values in the info file

yes. 

> and that using the template.php file for that reason is not actually required...?

Not only is it not required, but the example code provided won't do anything at all. The code `if (is_null(theme_get_setting('menu_tab_color'))) {` will never evaluate to TRUE if there are default values set in the `.info` file. 

It's also generally a bad practice to do any kind of write while doing a read. 

> what about when a theme with settings is enabled, but the settings form is never accessed? In that case, the config file is never setup, and so anytime the default value is needed, theme_get_setting() has to read the info file.

yep. 

> isn't there a performance impact of needing to parse all theme's info files each time theme_get_setting() is called?

But the theme settings aren't usually needed very often, and the results of `theme_get_setting()` is statically cached. And even when not using the static cache, the system_list is cached (in the cache table) so the .info file is very unlikely to be read on any given page load.

I haven't run any benchmarks, but I'm fairly certain that doing a bunch of checks (and sometimes writes!?!) in `template.php` would be much slower. 

> From what I can see, the info file values are never cached and are re-read each time...

Reading info files is slow and painful so there is a LOT of caching in place that prevents them from being read except for when absolutely necessary.

**Comment by BWPanda** [comment]
Here's a PR to test: https://github.com/backdrop/backdrop/pull/3458

With this then we shouldn't need to add default values to `template.php` anymore.

**Comment by jenlampton** [comment]
I missed what you are intending to do in the PR. That bit of code copies the settings from themeA to themeB, if themeA is a base-them for themeB. Is that related to this issue?

**Comment by klonos** [comment]
> That bit of code retrieves the settings from themeA for use in themeB, if themeA is a base-theme for themeB. Why would it need to be changed at all?

I haven't looked at the code yet @jenlampton, but that sounds like theme setting inheritance from the base them. There are use cases where that is needed.

The way I see it, any sub-theme should be able to override the base theme settings (assuming that these are being saved in a .json file). If a setting has not been specifically (un)set in the sub-theme, I'd expect that it would inherit the value from the base theme.

**Comment by jenlampton** [comment]
> that sounds like theme setting inheritance from the base theme. There are use cases where that is needed.

Right, but it already works as intended. So I was asking "why change it?"

**Comment by indigoxela** [comment]
> We should test the default theme settings in the .info file to confirm.

As I already described in my previous comment: I never needed to initialize a theme's default setting, the info file plus settings form worked out of the box for me.

@jenlampton Many thanks for updating that confusing documentation section.

Lucky me, that I didn't read it before, it would have confused me just like @BWPanda . :laughing:

**Comment by BWPanda** [comment]
So this issue and the PR can be closed as fixed/unnecessary then...?

**Comment by indigoxela** [comment]
> So this issue and the PR can be closed as fixed/unnecessary then...?

It depends - are your questions answered? Or do you have any use-case left, that's not covered by the current solution?

Also note the [related issue](https://github.com/backdrop/backdrop-issues/issues/4829) about introducing hook_enable/disable for themes.

**Comment by BWPanda** [comment]
Well I thought there was a performance issue with not doing things as per the old documentation; but since no one else thinks so, and since none of the core themes ever did it that way, then I guess there's no issue. So I'm all good. Will close as 'fixed' (thanks to @jenlampton's updated documentation).
