### ISSUE TITLE
Drupal 7 upgrade instructions say update.php instead of core/update.php

### ISSUE THREAD

**Issue by realuser** [backdrop/backdrop-issues#4815]
**Description of the bug**

The instructions at https://api.backdropcms.org/documentation/upgrading-from-drupal-7
say in section "Step 3: Upgrade your Drupal site to Backdrop CMS"

> 7. Open up a browser, and visit https://example.com/update.php to proceed with the update. (Replace example.com here with your domain or local site alias)

However there isn't a file at https://example.com/update.php instead it seems to be at https://example.com/core/update.php

I don't know if that's a misconfiguration on my part or the docs are wrong, but https://example.com/core/update.php worked

Version: https://github.com/backdrop/backdrop/releases/tag/1.17.4

**Comment by olafgrabienski** [comment]
Hey @realuser, thanks for the report!

As far as I know, the path `update.php` has a redirect to `core/update.php`. So, the docs are correct but it seems they're not clear enough. I'd suggest to close *this* issue and report it in the API queue instead, cf. https://github.com/backdrop-ops/api.backdropcms.org/issues.

**Comment by klonos** [comment]
I have tested some vanilla/simple D7 to Backdrop upgrades last week. When trying to access `/update.php`, you are automatically redirected to `/core/update.php`. I don't think that we should change that; it's easier to remember `/update.php` 😉 

PS: similarly, there are other places where such redirects happen, such as `/user`, which automatically redirects to `/user/login`.

**Comment by realuser** [comment]
/update.php didn't work for me while /core/update.php did, but sounds like it might be a configuration issue on my system
