### ISSUE TITLE
Is it necessary to leave the administration theme enabled?

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4818]
Seven 1.17.4 comes enabled as the administration theme by default. However, if you disabled it leaving it as the administration theme and the option `Use the administration theme when editing or creating content ` checked, then  you can still be perfectly using it. So what's the point of having it always enabled?

**Comment by klonos** [comment]
I believe that this is related, or even duplicate of #4459 @alanmels

**Comment by alanmels** [comment]
@klonos, thanks for the pointing to already existing discussion.
