### ISSUE TITLE
update_calculate_project_data() doesn't put the "main" module in the info"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4822]
**Description of the bug**

A short description of what the problem is.

**Steps To Reproduce**

To reproduce the behavior:

**Actual behavior**

Describe what was the result of following the steps above. Add screenshots if
you think they would help.

**Expected behavior**

Describe what you expected to happen instead.
Add mockup screenshots if possible.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version:
- Web server and its version:
- Operating System and its version:
- Browser(s) and their versions:

**Comment by indigoxela** [comment]
@klonos has this issue been created by mistake? It looks like [that one](https://github.com/backdrop/backdrop-issues/issues/4823) and this one try to cover the same topic.

**Comment by klonos** [comment]
Sorry, you're right @indigoxela ...I think that my browser did something odd and double-submitted the same tab somehow 🤷
