### ISSUE TITLE
Remove blank lines before @file docblocks

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4824]
As per our [PHP coding standards](https://api.backdropcms.org/php-standards#indenting):

> The `@file` docblock at the beginning of a PHP file should not be preceded by a blank line...

But I often see files in core where this is the case. We should fix these.

To clarify, we should change any instances of:
```php
<?php

/**
 * @file
 *  ...
```

with:
```php
<?php
/**
 * @file
 *  ...
```

**Comment by indigoxela** [comment]
phpcs requires that blank line. Otherwise you get:

```
-----------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------
 1 | ERROR | [x] The PHP open tag must be followed by exactly one blank line
-----------------------------------------------------------------------------
```

**Comment by BWPanda** [comment]
> phpcs requires that blank line.

Then phpcs needs updating. Backdrop's coding standards (see link above) state there should be no preceeding blank line.

I tried to find where the `The PHP open tag must be followed by exactly one blank line` error is coming from, but I can't find it. It doesn't seem to be in https://github.com/backdrop-contrib/coder_review, but I found very similar tests in https://github.com/squizlabs/PHP_CodeSniffer, so maybe it's a generic PHP thing. Either way, `coder_review` needs updating to adhere to our coding standards, but that's a separate issue (and separate repo).

In any case, core file need updating. *If* the fact is that *our* coding standards need updating, then we still need to fix core, since there are currently both types of files:
- https://github.com/backdrop/backdrop/blob/1.x/core/includes/actions.inc (blank line)
- https://github.com/backdrop/backdrop/blob/1.x/core/includes/ajax.inc (no blank line)

**Comment by indigoxela** [comment]
> I tried to find where the The PHP open tag must be followed by exactly one blank line error is coming from, but I can't find it. 

That's the Drupal phpcs coder variant.

I see no use in forcing anyone to update all of their code because of a single (silly) empty line, when both, coder for Backdrop and Drupal do not mark it as error/warning when it's there. What a waste of time and effort.

**Comment by Sahana-Pandurangi** [comment]
Please assign this issue to me - Sahana from GHC

**Comment by BWPanda** [comment]
Due to the sheer number of files being changed, I'm not comfortable putting this in a bug-fix release.

**Comment by BWPanda** [comment]
Merged PR into 1.x.
