### ISSUE TITLE
Multiple issue with our coding standard documentation

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4825]
Our [coding standard docs](https://api.backdropcms.org/php-standards) need some loving care.

First of all the example for the file docblock misses the empty line after the opening php tag:

```
<?php
/**
 * @file
 * Foo file does bar.
 */
```
Many of us use phpcs to verify coding standards, and the Drupal variant of coder _requires_ that empty line, while the backdrop variant _tolerates_ when it's missing.

Worse IMO is the section "Persistent Variables":
```
Persistent variables (variables/settings defined using Backdrop's variable_get()/variable_set() functions) should be...
```
In Backdrop variable_set/get is deprecated. The docs shouldn't list these, but provide config_set/get examples.

**Comment by klonos** [comment]
@indigoxela I think that this issue belongs in https://github.com/backdrop-ops/api.backdropcms.org/issues ...can you please copy-paste there, and close this issue (nothing we can do in core, unless we had PHPCS and needed to tweak its settings).

**Comment by indigoxela** [comment]
Sure, no problem. Someone with sufficient permissions could set a label over there.
