### ISSUE TITLE
Autocomplete throbber icon doesn't support RTL languages

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4826]
In https://github.com/backdrop/backdrop-issues/issues/3421 it was pointed out that the autocomplete throbber icon is right-alighed in RTL languages when it should be left-aligned. The solution used back then was to add new CSS to the Seven theme to fix this.

However it seems the root cause is actually incorrect CSS in the System module's CSS (https://github.com/backdrop/backdrop/blob/26101dbdc91f15b1f6b432f1428732bcec77f899/core/modules/system/css/system.css#L37):

```css
[dir="rtl"] .js input.form-autocomplete {
```

The `[dir="rtl"]` and `.js` are both on the same element, yet there's a space between the selectors, so this doesn't work.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/3455

I chose not the remove the now-unnecessary CSS from Seven (because of the whole changing-CSS-in-core thing).

**Comment by indigoxela** [comment]
Nice catch! (You probably should restart the sandbox, it ran into a timeout with Zen.CI.)

For Seven there's already CSS to catch that, but in Basis the throbber currently shows on the wrong side for RTL-languages.

This is how I tested:

- Enabled language and locale
- Added arabic
- Turned off asset aggregation
- Went to /ar/node/1/edit and inspected css of the tags field (in Seven)
- Switched the "Use the administration theme when editing or creating content" off
- Went to /ar/node/1/edit (now in Basis) and inspected css of the tags field

Works as expected. :+1: And it's a really minimal change.

**Comment by quicksketch** [comment]
Thanks @BWPanda and @indigoxela! Merged https://github.com/backdrop/backdrop/pull/3455 into 1.x and 1.17.x.
