### ISSUE TITLE
Fix CKEditor admin display for RTL languages

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4832]
**Description of the bug**

When trying to configure CKEditor in a right-to-left language, many icons are missing and many php Notices are thrown.
This is because not all icons have (or need) a RTL variant.

**Steps To Reproduce**

1. Enable language and locale modules
2. Add Arabic language
3. Enable all errors under `/admin/config/development/logging`
4. Go to /ar/admin/config/content/formats/filtered_html

**Actual behavior**

Broken display:
![ckeditor-admin-rtl](https://user-images.githubusercontent.com/842066/103136813-023cb780-46c4-11eb-9f09-598bf43d13eb.png)

And a lot of Notices, one for every missing icon:

`Notice: Undefined index: image_rtl in {closure}() (line 66 of .../core/modules/ckeditor/ckeditor.theme.inc`

**Expected behavior**

Fall back to the original images.

**Additional information**

- Backdrop CMS version: 1.17.4

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3459) is available for testing and review.

It checks, if `image_rtl` (can also be `image` on LTR) is set and only then tries to create the file url, falls back to `image`.

![ckeditor-admin-rtl-fixed](https://user-images.githubusercontent.com/842066/103137109-5e084000-46c6-11eb-9a26-233c13f692ff.png)

**Comment by klonos** [comment]
Huh!? ...I thought we had that fixed with #3504 but we may have regressed 🤔 

Thanks @indigoxela 🙏

**Comment by klonos** [comment]
WFM + code is simple and looks good 👍

**Comment by indigoxela** [comment]
> I thought we had that fixed with #3504 but we may have regressed

Strange, but you're probably right, several commits happened in the meantime. Not sure, though, what might have caused the regression.

**Comment by quicksketch** [comment]
Thanks @indigoxela! The PR fix looks good, though the automated test seems fragile and I'm not sure that it will be effective at determining if icons are really showing or not. Lots of things could make it so that the error message might not show up on the page: If the markup for notices were modified, if error messages were disable, if PHP changed it's error messaging in a new version of PHP, or if we changed the associated code so that it was not in a closure.

Even then, we're only checking for an undefined index, not that the icon actually can be found and loaded. I think we could use an XPath selector to find each image src property, then check if it exists by requesting each URL individually.

**Comment by indigoxela** [comment]
> I think we could use an XPath selector to find each image src property

The image src attributes get set via Javascript, so I can't use XPath for these directly. But I can grab the script tag and parse for the image src strings in there.

My PR has been updated and is ready for another review.

**Comment by klonos** [comment]
🤔 ...I was looking in `filter.format.filtered_html.json` but can't see anything re toolbar buttons. Where are these saved?

**Comment by indigoxela** [comment]
@klonos if the settings are still the default ones, for instance after install, you won't find the editor toolbar settings in that file yet. Save the form once (admin/config/content/formats/filtered_html) and they'll appear.

In case you need some explanation for my test addition:

For the test I get the `<script>` tag that contains the js settings and verify that the img src values are complete.

When it works properly, the url to the image points to the icon image, for instance:

`img src=\u0022http:\/\/domain.tld\/core\/modules\/ckeditor\/images\/buttons\/bold.png`

When it doesn't work the img src only contains the domain part (hence the image wouldn't display):

`img src=\u0022http:\/\/domain.tld\/\u0022 title=\u0022Bold\u0022`

**Comment by jenlampton** [comment]
Nice clean fix, plus tests!!  RTBC.

**Comment by quicksketch** [comment]
Still not 100% on the test implementation, but I think it will be fine. If it breaks in the future we may revisit making it a more robust check. I merged https://github.com/backdrop/backdrop/pull/3459 into 1.x and 1.17.x. Thanks @indigoxela, @klonos, and @jenlampton!
