### ISSUE TITLE
Password strength indicator label has double colon

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4848]
The password strength indicator has a double colon:

![image](https://user-images.githubusercontent.com/2385329/103434050-c9668a80-4c4f-11eb-89e7-fdae5f9a25c0.png)

This appears to have been introduced recently: https://github.com/backdrop/backdrop/commit/a167f5875811b91de74d2dae1cd4e68157aabef1#diff-3c6cd11de053f221577847f69b6c15b686cf927cb86ea391054d9b180acf6814R11

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3466

**Comment by klonos** [comment]
Simple fix + works as advertised. RTBC 👍

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3466 into 1.x and 1.17.x. Thanks!
