### ISSUE TITLE
[UX] Add a new pageless node above the "Promoted Content" block on Home page

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#4849]
**Description of the need**

We've had a number of frustrated users report problems understanding how to use the home page layout in Backdrop CMS. Coming from Drupal, many users assume the need to change the default home page path to a node and then are confused when the home page layout is not working, because the new home page is a node and uses the node layout.

In todays [Design meeting](https://youtu.be/Fc-oQ55LQi0) we talked about this problem. The discussion spilled over after the dev meeting (after recording stopped). During the discussion, we discussed the possibility of creating a "home" or "welcome" page and then using this as part of the default content on the home page. 

This idea is based on a couple of assumptions:

1) That very seldom do users really need to change the default path for the home page. But, that there are things we could do to help new users understand this. Users coming from Drupal 7 are especially vulnerable to the assumption that they need to change the home page path to other content.
2) That most people do not want a feed of promoted content on the front page (well, this is my assumption, not sure how others feel about this). 

By putting an "existing content" block on the front page by default, we make it much easier for them to understand and proceed with customizing the home page layout, rather than changing the default path for the home page to a node. 

**Proposed solution**

I decided to give this whole thing a try to see what folks think. 

1) I created a new node of type page with the title of "Home page" and some helpful content as part of the install profile.
2) I replaced the "Promoted content block" in the default home page layout with an "Existing content" block that refers to the new "Home page" node. The node title is NOT used on the home page layout.
3) As per a suggestion by @philsward - I made sure that the new "Home page" node has NID 1 (I don't know if this is important and might not be a good idea).

Putting a new "existing content" block on the front page with the "promoted content block" seemed a bit cluttered. I am certainly open to other options. 

All of the changes in this PR effect the install profile and will only impact new sites. They will have no impact on any existing sites.

I went ahead and added a little text to the home page designed to introduce the idea of using the home page layout to new users. I'm not sure if folks will like this idea, but I wanted to give it a try and see what the feedback was - and listen for alternative ideas.

**Alternatives that have been considered**

We could also improve this situation with some help text. 
https://github.com/backdrop/backdrop-issues/issues/4839

**Additional information**

![home-page-new](https://user-images.githubusercontent.com/3144571/103434597-5ca8ad00-4bc9-11eb-8bf9-6e804ec75587.png)

**Comment by BWPanda** [comment]
I like it! We can tweak the wording and maybe link to where the homepage can be customised, but I much prefer this front-page over the existing one.

**Comment by philsward** [comment]
Did we decide if this will be a core or profile change? I know we talked about it, but I don't think an actual direction was picked.

**Comment by cellear** [comment]
I think the previous of experience of people coming to Backdrop from Drupal is _so_ different from those coming from the rest of the world that we'll never be able to find a single solution that works for both.  We've been trying (I think) to not disrupt the views of those coming from Drupal too much, while that has been the source of most of our users, but that will probably (hopefully?) change at some point.

My feeling is that we should diverge from Drupal _more,_ and treat Drupal transfers as a special case, with some sort of "Hey Drupal people, here is what you need to know" content.  And then optimize the experience for people who have never used Drupal.

**Comment by stpaultim** [comment]
> Did we decide if this will be a core or profile change? I know we talked about it, but I don't think an actual direction was picked.

@philsward - Actually, it turns out that everything in this change is part of the install profile. Techically, it's part of core. But, nothing in this PR would effect any existing site. It will only effect new sites. 

> My feeling is that we should diverge from Drupal more, and treat Drupal transfers as a special case, with some sort of "Hey Drupal people, here is what you need to know" content. And then optimize the experience for people who have never used Drupal.

@cellear I don't know that these things are necessarily in conflict. Yes, we defined this problem in terms of users coming from Drupal. I don't think we can ignore that situation. If something is obviously confusing for users coming from Drupal, I want to fix it. If something is obviously confusing for users that have never seen Drupal before, I want to fix it. In either case, I don't want the fix to make things harder for either group and I hope that in either case the fix is going to make things better for both groups. 

Yes, this specific issue came from a discussion about an issue that is specifically confusing to users coming from Drupal. But, I would argue that having the default content on the front page to be a list of promoted content is not specifically helpful to any users. I think that this change is going to be helpful to most new users.

I would say that the main advantage of having a list of promoted content on the front page is that it highlights the availability of the views module. But, I'm not sure that it hightlights views in a way that is helpful to beginners. 

I think that this change highlights the way that we intend for users to use the home page layout (in a way that is useful to all users, but that is particularly useful to users coming from Drupal 7).

**Comment by BWPanda** [comment]
Since we're removing the node feed in favour of a page, maybe we should add a view of latest content to the sidebar...?

**Comment by olafgrabienski** [comment]
> maybe we should add a view of latest content to the sidebar...?

Good idea, only: there is no sidebar in the home page layout 🙂

**Comment by olafgrabienski** [comment]
Thanks for the PR @stpaultim, quite inspiring! I agree, we should (and can) help people understand the usefulness of the home layout.

> That most people do not want a feed of promoted content on the front page

Not sure if I share this assumption. IIRC, WordPress displays the latest posts on the home page by default and provides an option in the general "Reading" settings to display a static page as home page instead. In my opinion, we should also provide *both* options. (And make it super easy to choose between them.)

> By putting an "existing content" block on the front page by default, we make it much easier (...) to understand and proceed with customizing the home page layout

I think, it's the right direction. Sure, just putting the block there won't be enough. @BWPanda already suggested to tweak the page content and add helpful links. Another idea:

- Add *Admin label* and *Admin description* to the "Existing content" block on the Manage Blocks page (if not, it appears as "Displays content of node ID: 1").

**Comment by olafgrabienski** [comment]
A while ago, I've had a "Info blocks" in core idea, independently from the Home page discussion, but in a way I think it could also be a good fit for the Home page. As long as we use a Page as Existing content block, the Page will exist twice: on the home page, and under its own path, which isn't ideal, I guess.

As an alternative, we could use an own content type for the Existing content block, let's call the type "Info block" for the time being. The content type could be set to "Hidden path display", it could provide more fields, e.g. for images, and most important, it would also be a nice feature to use (btw translatable) "Existing content" blocks in other places. I'm planning to make a feature request for such a third core content type sometime. If others think it's interesting for the Home page, I'd be happy to move the idea forward more soon.

**Comment by indigoxela** [comment]
I don't have strong feelings about the home page layout and what it should contain. But I'd like to note that I consider views to be one of the greatest features of Backdrop and that we should provide an example view somewhere - just to show how powerful views can be.

**Comment by stpaultim** [comment]
> I don't have strong feelings about the home page layout and what it should contain. But I'd like to note that I consider views to be one of the greatest features of Backdrop and that we should provide an example view somewhere - just to show how powerful views can be.

I think this makes sense. I would love suggestions. Will think about it myself some more.

**Comment by klonos** [comment]
>>That most people do not want a feed of promoted content on the front page
>
> Not sure if I share this assumption. ... In my opinion, we should also provide both options. (And make it super easy to choose between them.)

I agree with this. We shouldn't be making assumptions (not without telemetry data to support it). We can definitely be linking to the page where this setting (what is shown as a home page) can be changed, and make it super-easy to understand the options, and select one.

> I consider views to be one of the greatest features of Backdrop and that we should provide an example view somewhere - just to show how powerful views can be.

Also agree with this 👍 

If a page contains a view or a block, we show contextual links, which allow people to easily "jump" to the right admin page where the respective thing can be configured. Perhaps we should add a contextual link to the home page (layout), that goes to the admin page where these various options exist. Contextual links assumes that the module is enabled, and that the user has the proper permission; so perhaps this can be an info message instead, with help text and links in it?

**Comment by philsward** [comment]
Is it worth looking at the long game on this issue and look at the bigger picture of having several profiles as a choice during install?

@BWPanda suggested recipes in another issue which can go hand-in-hand with profiles.

For now, I would keep the home page simple. Either make the home page content a custom (hard coded?) block or add a predefined node(/1?) as a block.

Welcome Text:

> Welcome to BackdropCMS!
>
> This is your home page where you can write the introduction for your new site.
>
> To change this text and make it your own, let's head over to the home page layout group and edit this block [link]

I do like the idea of filling up the home page with lots of "cool things you can do" but that is only ideal for brand new users. Advanced users don't want to have to go in and remember to delete a bunch of blocks every time they spin up a site.

I think if we can pull out the profile issue discussion and come to a consensus on what that would look like, we can re-purpose this issue to handle an "advanced" scenario where it's setup for someone who needs the skeleton ready to go for content.

**Comment by stpaultim** [comment]
> Since we're removing the node feed in favour of a page, maybe we should add a view of latest content to the sidebar...?

Just realized that we don't have a view of recent content in core yet. We have an old style "Recent content" block, but it does not use a view. https://github.com/backdrop/backdrop-issues/issues/146

**Comment by stpaultim** [comment]
> I consider views to be one of the greatest features of Backdrop and that we should provide an example view somewhere - just to show how powerful views can be.

I agree that views is one of the greatest features of BackdropCMS and we should do our best to make sure that users are aware of it. 

I tried to think about how to do that while keeping the "Existing Content" block on the front page (as per this PR) and ran into these problems. 

1) I'm not sure what "view" makes sense to put on the front page. "Recent content" seems like a good choice, but we don't actually have a "recent content" view in core yet (#146). Also, I'm not sure where to put it, given the single column layout that we default to on the home page.

2) Does placing a block with a view in it really help new users find and understand views? This is a great goal, but is this the right solution. We do have several admin views that any site builder will experience (although they might not realize it). 

* admin/content/node
* admin/content/files
* admin/people/list 

It seems like the main objection to this PR (SO FAR) is that it removes the only view used by default for users. Is this really a problem? If so, what other suggestions do folks have for including a default view in the standard install profile? Would it be ok to make this change and then create a new issue for adding a default view to the standard install profile?

**Comment by findlabnet** [comment]
How about a third default page with same view (feed of content) as it is on front page now? And an additional item in the default main menu.

**Comment by BWPanda** [comment]
This is likely a whole separate issue, but afterlistening to the meeting discussion about this, I wondered whether a 'tour' of the homepage would work to help people understand things better...

Something like: https://zurb.com/playground/jquery-joyride-feature-tour-plugin
https://github.com/backdrop-contrib/joyride

I just installed the Umami demo of Drupal 9 yesterday for the first time and they have a similar 'tour'.

**Comment by jenlampton** [comment]
I like the idea of a tour in general, but I don't like the idea of adding one to core. (Tour module for Drupal 8+ is incomplete and very hard to maintain.) 

That said, I'd *love* to see something like this on our TugBoat demo site. We had plans to make that into "more than just core" at some point, and adding something like this could be a great training tool in addition to helping demonstrate Backdrop's abilities!

**Comment by philsward** [comment]
I agree with the tugboat idea. Commenting on the issue that talks about install profiles, I wanted to suggest a "tour" type of profile, but realized it would be better if people could get their feet wet and "tour" without ever installing Backdrop.

**Comment by stpaultim** [comment]
This issue was discussed in Design meeting this week. See: https://www.youtube.com/watch?v=FsEVAkVdXQ8 (24:20 minutes into meeting). 

Concern was raised that the existing "river of nodes" is something familiar to users that come from Drupal or earlier versions of Backdrop CMS. 

We had a brief discussion about how the front page might look with both a static node and a view (river of nodes). Maybe a static text block with the river of nodes underneath it?

**Comment by klonos** [comment]
> Does placing a block with a view in it really help new users find and understand views?

It does make the feature more obvious/discoverable ...although having a view that can display multiple pieces of content but then only have a single piece of content shown is not obvious at all (only people that already know how views work understand it). If #146 was fixed by 1.19.0 then the fact that it's not a block wouldn't be a ...blocker (pun 😅 ).

Jokes aside, a home page that is comprised by a node block in the main section + a recent content block placed in a sidebar region would be ideal IMO. (I'm basically saying "lets fix #146").

> I like the idea of a tour in general, but I don't like the idea of adding one to core.

I would like us to eventually have a properly-maintained, lightweight and functioning tour solution in core (especially since we've removed the Help module and `hook_help()`). (Idea: alternatively, we could allow installation profiles to download and install contrib modules).

All that would be awesome, but it'd require a 3rd-party library to be added to core + help/tour content added + tour scenarios/steps drafted. That sounds like a lot more work than just fixing #146.

So while a "proper", full-fledged tour solution sounds like it would take a long time, what @stpaultim has done in the PR sandbox can be done in a short amount of time. We could expand the content of the node used as a node block to include things like:

- Explain that the page they are looking at is comprised by various _blocks_, that are placed in _regions_.
- Explain that starting from top to bottom:
  - the main navigation at the top of the page is also a block, containing a menu.
  - the hero section is also a block, containing some text + a background image that is configured to stretch across the entire width of the page.
  - the text they are reading is a piece of content of type "page", which was placed as a block (but point out that not all content needs to be placed that way)
  - the "recent content" block on the side bar is also a block, which dynamically generates a list, and that any content added to the site will be added to that block, up to a maximum of ...I don't know, say 5 (whatever the view will be configured to display). Then also link to Views documentation on docs.b.org, or video tutorials on our youtube channel.
  - the "Powered by Backdrop" section in the footer is also a block.
- Explain that any block may be added/removed/tweaked and even moved around the various regions of the page, by editing the layout. Then provide pointers on how to start doing that + link to documentation.

You get the picture: since we don't have a tour/help solution, we can use the node that's placed as a block to the home page as a short intro to blocks, layouts, menu, views etc.

PS: Did I mention that we should fix #146? 😅

**Comment by klonos** [comment]
> ...we can use the node that's placed as a block to the home page as a short intro to blocks, layouts, menu, views etc.

Something like this:

![screencapture-1-18-1-taxfbbtorsiffmcqyyzgcfgiivxxfa2a-tugboat-qa-2021-01-30-21_43_25](https://user-images.githubusercontent.com/2423362/106366473-cd67f400-6344-11eb-82d9-60435f3484d3.png)

[home-node-tour-text.txt](https://github.com/backdrop/backdrop-issues/files/5898621/home-node-tour-text.txt)

**Comment by BWPanda** [comment]
This is why I suggested a 'tour' of the hompage/regions. Because I see people wanting to add help text into a node on tge himepage as default content. This is never going to stay as content - users will either need to delete the node, or edit it to remove all the help text before their site goes live.

Tour functionality, on the other hand, doesn't add content that needs to be removed. And the benefit of being in core means maybe it can be used for other parts of the site when the user accesses them for the first time - layouts, views, functionality page, updates page(s), etc.

**Comment by philsward** [comment]
#4903 should be addressed before the node to this issue gets added to the PR.

**Comment by philsward** [comment]
Take a step back, let's look at who this is for:

New users: create some better help text to explain where they need to go next to get started.

Existing users: create a way that allows the home page to have content ready to be added with the click of a button instead of navigating to layouts, deleting the waterfall block, adding a pathless content type, creating the pathless node, adding the content, going back to layouts, adding that new pathless node and finally viewing the home page to make sure it looks right.

**Comment by indigoxela** [comment]
As a contrib theme maintainer this is a little frustrating for me. I spent a lot of time to let the "Promoted Content" block on the start page look good. Pointless effort, as it seems now. Anyway, just go for it.

@stpaultim seems like your PR needs more work, as 53 tests are currently failing in both php versions.

**Comment by stpaultim** [comment]
I think we are along way from worrying about tests. ;-) This is still just an idea under discussion. 

> As a contrib theme maintainer this is a little frustrating for me. I spent a lot of time to let the "Promoted Content" block on the start page look good. Pointless effort, as it seems now. Anyway, just go for it. My themes: Lateral, Pelerine, Snazzy, Monochrome.

This is a good point that I don't think anyone has raised yet, so don't get frustrated yet. We're still just talking. 

But, if in fact very few people are using "promoted content" on the front page of their sites (I recognize that not everyone agrees with that statement), then maybe it's better to get rid of it now and save contrib themers in the future the time of having to theme a block that almost everyone is going to get rid of immediately (at least in my opinion). Why not focus on making something look good that users will actually use.

Counterpoint, if people are using that block. Then the theming will still pay off when users put it back on the page (assuming we remove it).

**Comment by indigoxela** [comment]
One quick idea: why not showcasing both on the start page - a view *and* a single node (BTW why do you disregard the view so much?).

People who need a feed for their project see it, people who prefer "static" content see it. It's just a matter of removing the part from the layout, they do not need. Many might even need both.

**Comment by jenlampton** [comment]
I like @indigoxela's recommendation of having both. It's much easier to remove something than create something :)

**Comment by stpaultim** [comment]
I don't object to having both. I tested it, but I didn't like the way it looked. I could use some suggestions (even mock-ups) of how that might look good and not be confusing to a new user.

**Comment by stpaultim** [comment]
Well changing the title might have been premature (but it's fine), here is where I am on this discussion. 

1) I believe that the pageless node on front page provides more value to new users than the current view of a single Promoted Node. 

2) I'm not sure that we will be able to make both of them look good, without making CSS changes to Basis - and we still haven't figured out how to do that (https://github.com/backdrop/backdrop-issues/issues/4167). 

I am afraid that assuming that we will put both items on the front page is a poisen pill that will kill this issue, because I don't know how to make it look good. But, if anyone has ideas on how to make that happen, I'm open to it. I would rather replace the the "Promoted Content" block than stick with the status quo, but that's just my humble opinion. :-)

**Comment by olafgrabienski** [comment]
> put both items on the front page (...) don't know how to make it look good

I have some ideas, will come back to it later or tomorrow.

**Comment by stpaultim** [comment]
I think that this issue is on hold pending outcome of https://github.com/backdrop/backdrop-issues/issues/4903. #4903 does not directly address the original goal of this issue, however it might have some benefit for the goals mentioned here. However, it will be hard to include an Existing Content block on front page after the changes in #4903.

**Comment by jenlampton** [comment]
We could put it elsewhere, like the sidebar of the default layout :)

**Comment by stpaultim** [comment]
There is so much progress on this issue: https://github.com/backdrop/backdrop-issues/issues/4903

That I would like to close this issue right here. By the time we are done with #4903 - this discussion will be quite different and to the extent it is still relevant it will probably need a fresh discussion.
