### ISSUE TITLE
Rename "Functionality" menu link to something less unfriendly.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#4851]
I propose "Extend" or "Extensions" to match D8.

**Comment by BWPanda** [comment]
This was previously discussed here: https://github.com/backdrop/backdrop-issues/issues/341
And this: https://github.com/backdrop/backdrop-issues/issues/1150 looks to be a similar, open issue.

I suggest closing this as a duplicate of #1150

**Comment by docwilmot** [comment]
Reasonable.
