### ISSUE TITLE
Fixed path autocomplete AJAX error

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4854]
**Description of the bug**

When entering a path in an autocomplete-enabled field, if the Taxonomy module is not installed you get an error:

```
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: [SNIP]/index.php?q=path-autocomplete
StatusText: Internal Server Error
ResponseText: 
```

**Steps To Reproduce**

To reproduce the behavior:
1. Go to `/node/add/page` and click the Link icon in the Body field's editor toolbar
2. Enter 'post' in the Link Destination field - note that you can select the Post node to link to 👍🏻 
3. Go to `/admin/structure/types/manage/post/fields` and delete the Tags field
4. Go to `/admin/modules` and `/admin/modules/uninstall` to fully uninstall the Taxonomy module
5. Repeat steps 1 & 2

**Actual behavior**

The above error pops up 👎🏻 

**Expected behavior**

You see a list of matching paths to select from.

**Comment by BWPanda** [comment]
Simple PR: https://github.com/backdrop/backdrop/pull/3476

**Comment by stpaultim** [comment]
I was able to recreate the problem in a Tugboat sandbox site using the steps to recreate. 

I then tested the PR with the sames steps and can confirm that the problem no longer existed.

It looks like a pretty simple PR, but I'm still not ready to vouch for the code. 

Works for me.

**Comment by indigoxela** [comment]
I was also able to reproduce it and can confirm that the PR fixes it.

Indeed a simple and obviously correct approach. RTBC!

**Comment by BWPanda** [comment]
Thanks guys! I've merged https://github.com/backdrop/backdrop/pull/3476 into 1.x and 1.17.x.
