### ISSUE TITLE
[UX] The "this is a preview" message appears after content has saved

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4856]
**Description of the bug**

When you preview a node, you see a warning message stating that the node you are viewing has not yet been saved. This is good.

However, when you click the "save" button on that page, you also see the same preview message stating that the node you are viewing has not yet been saved -- even though it has. Additionally, you also see a contradictory message stating that the node was just saved.

![preview](https://user-images.githubusercontent.com/397895/103570026-34e16f80-4e7d-11eb-94cb-74c2533ca32c.png)

**Steps To Reproduce**

To reproduce the behavior:
1. Create a node, save it.
2. Edit the node, hit preview. see message. :)
3. Scroll down, hit "Save". See two contradictory messages :(

**Actual behavior**

two contradictory messages :(

**Expected behavior**

one accurate message :)

**Comment by klonos** [comment]
1-line fix (+ inline comments): https://github.com/backdrop/backdrop/pull/3486

**Comment by klonos** [comment]
...added tests too 😉

**Comment by jenlampton** [comment]
Huh. You might have just showed me how to solve my problem with the max-input-vars messages!  Nice work with the PR (my client thanks you)!

**Comment by klonos** [comment]
Perhaps the client can make a donation to Backdrop, or consider sponsoring the next event or something?

**Comment by jenlampton** [comment]
They've already sponsored 4 contrib modules (including reference!)
countless patches, and have a laundry list of new feature requests for the
coming year. They're doing great. :)

**Comment by BWPanda** [comment]
Requesting a change to the comment describing the new line of code. See PR for details.

**Comment by klonos** [comment]
Thanks @BWPanda ...please see my reply in the PR. I'd be happy to accept any suggestion, but FTR, I believe that if anything should be clarified, then it should be done in the API site, in https://api.backdropcms.org/api/backdrop/1/search/backdrop_get_messages (so basically in the docblock of the `backdrop_get_messages()` function). What do you think?

**Comment by docwilmot** [comment]
You could do:
```
  foreach ($_SESSION['messages']['warning'] as $key => $message) {
    if ($message == t('This is a preview. Links within the page are disabled.')) {
      unset($_SESSION['messages'][$type][$key]);
    }
  }
```

**Comment by BWPanda** [comment]
@docwilmot If that works then I think I'd prefer that over clearing all messages outright.

**Comment by klonos** [comment]
During the dev meeting, we also discussed the option of making that warning a pseudo-message (div container + markup with the classes `message`, and `warning`). I'll give that a go first, because I don't really like the `$_SESSION['messages']` way either.

**Comment by klonos** [comment]
OK, I've rebased + updated the PR, to move the messages from `node_preview_banner_form()` to `node_view()` instead + added some logic to make sure that they are shown only when this is a node preview. This does keep the warnings shown when switching display modes, while at the same time doesn't show them after the node is saved.

The tests that I've added prior to this change would catch:

- any duplicate warnings
- warnings not shown when switching display modes
- warnings shown in the saved node page

All these tests are green, but please also test manually to confirm.

**Comment by BWPanda** [comment]
Didn't test, but code looks good to me. Much better from a best-practices POV!

**Comment by indigoxela** [comment]
This is how I tested:

- Open a node form, add some content
- Open preview
- Switch "Select a display mode"
- Back to form
- Preview again
- Save

While in preview mode, the message was always there, and only once.
After saving the message was gone.

**Comment by indigoxela** [comment]
I agree with @BWPanda, moving message creation from function node_preview_banner_form() to function node_view() - with condition - seems much cleaner. And it has no side-effects. RTBC.
