### ISSUE TITLE
Errors in update hooks from use of undefined constants

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4858]
**Description of the bug**

Getting undefined constant errors in update hooks. For example:

> Warning: Use of undefined constant COMMENT_NODE_OPEN - assumed 'COMMENT_NODE_OPEN' (this will throw an Error in a future version of PHP) in comment_update_1001() (line 357 of /app/core/modules/comment/comment.install).

> Warning: Use of undefined constant COMMENT_NODE_HIDDEN - assumed 'COMMENT_NODE_HIDDEN' (this will throw an Error in a future version of PHP) in comment_update_1003() (line 401 of /app/core/modules/comment/comment.install).

> Warning: Use of undefined constant VIEWS_STORAGE_OVERRIDE - assumed 'VIEWS_STORAGE_OVERRIDE' (this will throw an Error in a future version of PHP) in node_update_1018() (line 1194 of /path/to/backdrop/core/modules/node/node.install).

**Steps To Reproduce**

To reproduce the behavior:

1. Upgrade a Drupal 7 site to Backdrop (can test with just core modules).
2. Run update.php

**Additional information**

Add any other information that could help, such as:

- Backdrop CMS version: 1.17.4
- PHP 7.2

[Updated to include more examples. Also see https://github.com/backdrop/backdrop-issues/issues/4343]

**Comment by herbdool** [comment]
Hm, I wonder if this happens when the D7 site has comment module disabled? If so, then we should probably include comment.module in the update hooks to ensure the constants are defined there.

**Comment by quicksketch** [comment]
> Hm, I wonder if this happens when the D7 site has comment module disabled? If so, then we should probably include comment.module in the update hooks to ensure the constants are defined there.

Yes, that can be one cause. There's no guarantee that a .module file will be included when update hooks are run. Update hooks are run even if the module is disabled (but had been enabled at some point previously). IMO the update hook should be updated just to use the constant values (whether a string or integer), perhaps with a code comment referring to the constant name.

**Comment by indigoxela** [comment]
Related? https://github.com/backdrop/backdrop-issues/issues/4343

**Comment by herbdool** [comment]
@indigoxela ah yes. Since this one has more comments on it now we could close the older one and make the title and description of this one more generic.

**Comment by herbdool** [comment]
@indigoxela want to review the PR?

**Comment by BWPanda** [comment]
> IMO the update hook should be updated just to use the constant values (whether a string or integer), perhaps with a code comment referring to the constant name.

What's the point of setting constants then if we just use integer values? Isn't this a PHP issue where the solution is just to add quotes to the constant names? I've seen this come up before somewhere...

**Comment by docwilmot** [comment]
The constant is clearly defined in `comment.module` so if its undefined, then that file is not loaded at the time. So we'd either have to make sure the file is loaded during the upgrade, or we use the value.

**Comment by klonos** [comment]
> So we'd either have to make sure the file is loaded during the upgrade, or we use the value.

I'd prefer making sure the proper module is loaded. As @BWPanda said:

>What's the point of setting constants then if we just use integer values?

**Comment by indigoxela** [comment]
> @indigoxela want to review the PR?

@herbdool it seems to me that there's sort of consensus that including the file that defines the constant might be the cleaner approach.

**Comment by herbdool** [comment]
I don't think we have consensus around the approach yet. @quicksketch do you have a reason why you prefer the value rather than including the module file? My guess is that it has fewer unintended consequences such as where a disabled module's code gets run during the updates - want to avoid side effects here.

It's not so unusual to include values where we also have constants. We are forced to do it in the json files too.

**Comment by quicksketch** [comment]
I don't like loading the (disabled) module into active memory because it could theoretically cause hooks to get invoked on a disabled module, since now calls to `function_exists()` now return true for hooks in the module file. This _shouldn't_ happen because `module_implements()` checks the list of enabled modules, but it still makes me uneasy. Generally, update hooks can't use any of the APIs of modules for this same reason: that the module might be disabled. You might consider access to the constants to be part of that module's "API".

**Comment by BWPanda** [comment]
I defer to @quicksketch's wisdom 🙂

**Comment by indigoxela** [comment]
@herbdool so we have consensus to use the _values_. :wink: I've left some minor suggestions re coding standards in a PR comment. I hope, I'm not too picky.

**Comment by herbdool** [comment]
@indigoxela would you have a chance to update the labels if you think it's RTBC?

**Comment by indigoxela** [comment]
> would you have a chance to update the labels if you think it's RTBC?

Sure, I'll have another look soon. But today I'm too exhausted for code review. :wink:

**Comment by herbdool** [comment]
Still might be time to get this in? @quicksketch

**Comment by quicksketch** [comment]
Oops, darn. This one slipped off my radar. Sorry! This looks good, moving it to RTBC for 1.18.1

**Comment by BWPanda** [comment]
Thanks @herbdool, @indigoxela & @quicksketch! I've merged https://github.com/backdrop/backdrop/pull/3482 into 1.x and 1.18.x.
