### ISSUE TITLE
Automate release notes for minor releases

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4859]
@quicksketch asked me to look into a better system of automatically generating release notes when a minor release is published. Currently `drush rn` is used, but it includes a bunch of commits that aren't relevant to minor releases. So I started looking for alternatives.

I found the [Release notes generator](https://github.com/marketplace/actions/release-notes-generator) and [Wiki page creator](https://github.com/marketplace/actions/wiki-page-creator-action) GitHub actions. The first makes release notes for a closed milestone and saves them to a file in the virtual machine that runs the action. The second action then reads those notes and publishes them to the repo's wiki (so they're visible once the action completes). The idea is then that we'd copy/paste them into the release notes for the new release (like we do with `drush rn`) and then delete (or keep?) the wiki page.

I've tested this on my repo and got it working, but a better test will be to merge this into this repo (where the issues/milestones are) and test it 'live'. There's no danger in doing so, as the action is only triggered when a milestone is closed, and the only thing it does is publish a wiki page. Everything is undo-able (milestones can be opened/closed and wiki pages can be deleted). Also, the PR (see below) only adds two files to this repo, so they're easily delete-able too if we decide not to go ahead after testing this.

**Comment by BWPanda** [comment]
Here's the PR: https://github.com/backdrop/backdrop-issues/pull/4860

**Comment by BWPanda** [comment]
If/when this is merged, someone with admin access to this (`backdrop-issues`) repo will need to enable the wiki, and create an initial 'Home' page (apparently at least one wiki page must exist for the action to work).

**Comment by klonos** [comment]
Thanks for working on this @BWPanda 🙏

**Comment by quicksketch** [comment]
Awesome, thanks @BWPanda! I'm not sure we need the wiki page component of it. IMO it will be sufficient for us to be able to download the asset ZIP from the build job (assuming that happens). Let's give a shot with the 1.18.0 milestone and see how it goes.

I've merged the PR, though I'm leaving this open because I think we'll likely need further adjustments.

**Comment by quicksketch** [comment]
Wow, it works! I closed the 1.18.0 milestone and it made this nice wiki page!

https://github.com/backdrop/backdrop-issues/wiki/1.18.0

Picture for posterity in the event we remove this page:
![image](https://user-images.githubusercontent.com/100206/103726073-ddcac000-4f8c-11eb-8fb3-7f5e43b2ca30.png)

I really like how it can automatically map our labels to particular categories like "Bug fixes" vs "Features". Apparently it can also generate a list of "contributors" based on the people involved in the issues! Very neat.

I'm not sure this is the best use of the Wiki however. We could take a few options from here:

* We could embrace use of the Wiki and move our "procedures" into it: https://github.com/backdrop/backdrop-issues/tree/master/procedures We would also probably group all release notes into a directory.
* We could remove the saving of the notes to the wiki, and instead save the markdown file as a job artifact using https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts Then we could download the artifact from the build job (this example being https://github.com/backdrop/backdrop-issues/runs/1654183699?check_suite_focus=true)

For the time being, I'm leaning towards the second approach. Even if we start using the GitHub wiki more extensively, I am not sure that putting the release notes in it is really helpful for our users. We may end up with people starting to link to both the release note Wiki pages and the Release pages (onto which we copy release notes). I think we'd prefer to just have them in one place.

**Comment by BWPanda** [comment]
@quicksketch Glad it worked! 🎉 

I like the idea of moving the procedural docs to the wiki, but I'll leave that for a separate issue. And I agree that having release notes in two places isn't ideal, so I've gone ahead and changed the action to upload the notes as an artifact instead. I closed (and re-opened the milestone) and here's the result: https://github.com/backdrop/backdrop-issues/actions/runs/465228286

![image](https://user-images.githubusercontent.com/2385329/103730922-0eb3ff00-5038-11eb-9816-de2891312260.png)

That link allows you to download a zip file that has the release node markdown file in it.

**Comment by BWPanda** [comment]
So if you're happy with this solution, you can:
- Delete the release notes from the wiki (but leave the wiki in place for now as I'll open an issue about moving the docs there)
- Remove dragonbot's token from the repo settings (not needed anymore)

**Comment by quicksketch** [comment]
Super! I'll delete that token since I feel it's good to be tidy about such things. This is a great solution and will save us hours of work every single release. Thanks so much @BWPanda!
