### ISSUE TITLE
Place files in consistent locations for all core modules

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#486]
There are some files located in strange places in core. We should clean these up before we release. Items listed below are included in the attached PR:
- [x] all .js files in modules placed in a /js/ directory
- [x] all .tpl.php files in modules placed in a /templates/ directory
- [x] all .tests.info files in modules placed into the /tests/ directory
- [x] all .*.inc files in modules placed into the module root directory
- [x] views_ui module moved outside views module (to match field and field_ui)

Follow-up issues:
- https://github.com/backdrop/backdrop-issues/issues/537 Should all theme functions / preprocess functions be placed in a *.theme.inc file?
- https://github.com/backdrop/backdrop-issues/issues/556 PHP classes are sometimes in a .entity.inc file and sometimes in a .class.inc file. Standardize? 
- https://github.com/backdrop/backdrop-issues/issues/557 Should we move all the field modules outside field/modules?
- https://github.com/backdrop/backdrop-issues/issues/558 should there be an 'includes' directory, and if so, what goes in it?

**Comment by jenlampton** [comment]
I've got a local branch that's about half way through cleaning these up...  assigning to myself :)

I disagree that any .inc files should go in an /includes/ directory.  If all we had in the root of a module was an .install .module and .info it would be really hard to see what the module was doing (or where to find it) without mucking around in the code (or folders). Plus, almost everything would eventually end up in /includes/ and then what's the point?

On the other hand, if you open the module and see .admin.inc .theme.inc .pages.inc you know what's going to be where, and roughly what that module's doing at first sight.  Transparency++

I have a feeling I may eventually lose out on this one, but this initial PR will not include moving .inc files around.  We can bikeshed on that change a smidge longer :)

**Comment by docwilmot** [comment]
```
all .admin.inc files in modules placed into the module root directory
all .pages.inc files in modules placed into the module root directory
all .theme.inc files in modules placed into the module root directory
```
Agreed with this for the reason you suggest. If there are more .inc files than these though, it would be better organization to have them all in an /includes directory.

**Comment by jenlampton** [comment]
That's actually a good rule of thumb, we could have an includes directory recommended once we exceed a certain number of files in a module. Can you create a follow-up issue to do that so we don't forget? :)

**Comment by jenlampton** [comment]
I'm 90% of the way done with this issue, all that's left is cleaning up views module. This change will break most of our other patches/PRs, so it should be merged in almost last. 

Work underway over at https://github.com/jenlampton/backdrop/tree/486-cleanup-file-locations.  PR shortly!
