### ISSUE TITLE
Move procedural docs to wiki?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4861]
This (`backdrop-issues`) repository stores a folder of [Procedural Documents](https://github.com/backdrop/backdrop-issues/tree/master/procedures) which are markdown files that explain how to do various things in GitHub, etc.

In https://github.com/backdrop/backdrop-issues/issues/4859 it was briefly discussed whether these documents would be better stored in this repository's [Wiki](https://github.com/backdrop/backdrop-issues/wiki) instead.

I'm opening this issue to discuss moving the documents from code to the wiki.

I personally think the wiki makes more sense. Interested to hear others' thoughts...

**Comment by indigoxela** [comment]
I think, wiki pages are searchable. That might be a benefit.

**Comment by BWPanda** [comment]
And I think they're easier to navigate (menu of page on the side, etc.).

**Comment by stpaultim** [comment]
This makes sense to me.

**Comment by BWPanda** [comment]
I wonder if it'd be better to use the core repo's wiki instead...? Or perhaps https://github.com/backdrop-ops/backdrop-community Neither wikis are enabled yet, but that's easy to do.

Considerations:
- Who has access to edit wiki pages?
- Where does it make sense to put these pages?

Either way, we could copy the page contents to the new wiki, then update the issue repo pages to link to their new location. Then down the track we can delete the issue repo pages altogether.

**Comment by jenlampton** [comment]
My only real concern is for the issue templates that we use for releases. We need to be able to copy/paste those into the issue queue to retain the formatting, and having them in version control is helpful for adding things consistently across all the template options.

Can we keep the issue templates in the repo, but move all the other procedures to wiki?

**Comment by BWPanda** [comment]
> Can we keep the issue templates in the repo, but move all the other procedures to wiki?

That seems reasonable. Makes sense to keep issue templates in the issue queue repo :-)

**Comment by quicksketch** [comment]
>  We need to be able to copy/paste those into the issue queue to retain the formatting, and having them in version control is helpful for adding things consistently across all the template options.

Documents in the wiki can be copy/pasted by clicking "Edit" on the page and then copying the content out, like on [this page that is already in the wiki](https://github.com/backdrop/backdrop-issues/wiki/New-%22Recipe%22-Project-Type):

![Peek 2023-02-12 12-09](https://user-images.githubusercontent.com/100206/218334590-150dac3c-dc19-436a-9c87-9b97e585c624.gif)

And the wiki is actually also accessible via Git if you want to clone the entire wiki and work on it locally:

![image](https://user-images.githubusercontent.com/100206/218334662-8996440c-3999-48b7-93ad-722b933b6380.png)

**Comment by jenlampton** [comment]
Okay, so that eliminates my concerns. :) Is the wiki really a good place for issue templates?  (to me it seems like there's no benefit? - but for all the other notes there are.)

**Comment by BWPanda** [comment]
I've moved all procedural docs (other than issue templates) over to the wiki: https://github.com/backdrop/backdrop-issues/wiki

I'll now go and update the repo files to point there temporarily.

**Comment by BWPanda** [comment]
@stpaultim Since the backdrop-issues repository's wiki is now for the procedural docs, can you please move https://github.com/backdrop/backdrop-issues/wiki/New-%22Recipe%22-Project-Type elsewhere? @quicksketch also seemed to be questioning why this was there during today's meeting.

**Comment by BWPanda** [comment]
Repo updated now too: https://github.com/backdrop/backdrop-issues/commit/e59f05d41601259c0bdd9cc2b15e9166963ae081

I'll close this issue now.
