### ISSUE TITLE
Bring back textgroup to locale

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4864]
Textgroup was removed in early 8.x https://www.drupal.org/project/drupal/issues/1188430. We should bring it back.

It would fix https://github.com/backdrop/backdrop-issues/issues/4838 and make i18n and all the modules that rely on it a lot easier to support in Backdrop. Bring it back and get it all working and then consider the reasons for why it was removed (and how to evolve it instead with something like https://www.drupal.org/project/i18n/issues/1191662)

**Comment by klonos** [comment]
I'm in favor of this (for the sake of backwards compatibility), but I'd like us to see if there are any easy-wins that we can fix at the same time as reintroducing this. Perhaps look into the things that have been listed as reasons to rip this out of D8 core in the issue summary of https://www.drupal.org/project/drupal/issues/1188430?

Any harder-to-solve things can be follow ups.

PS: I haven't looked into this in depth, so it's not clear to me whether in D8 this thing was removed altogether, or if they changed to a more robust solution. If the later, then perhaps we need to work towards some sort of upgrade path if possible.

**Comment by indigoxela** [comment]
> it's not clear to me whether in D8 this thing was removed altogether, or if they changed to a more robust solution

They just ripped it out, totally ignoring its value and that their change was a contrib breaker.

**Comment by klonos** [comment]
> They just ripped it out, totally ignoring its value and that their change was a contrib breaker.

Typical evil D8 👿 ...sheesh!! 😅

**Comment by indigoxela** [comment]
@herbdool many thanks for your PR. :+1:

I've left some comments on stuff that caught my eye in a first quick scan. Currently several tests seem to fail - hard to tell which ones, as the Zen.CI boxes are 404.

**Comment by herbdool** [comment]
@indigoxela it's almost ready. I didn't update the labels bc I knew there were issues.

**Comment by herbdool** [comment]
@indigoxela I guess it's ready for a review now. I realized that in `locale_update_1001()` it removes textgroup which I shouldn't be surprised by because it wasn't dropped in D7. Anyway it means that for new upgrades we can't have that run. Not sure what to do about sites where it was already removed and we're adding it back. Do we default everything to "default"? Not sure what else we can do since we don't really know easily where the string is coming from.

**Comment by herbdool** [comment]
Also where the string is coming from configuration, such as where context is "config:system.core:anonymous", wondering if the textgroup should be something other than Built-in interface.

**Comment by indigoxela** [comment]
> Not sure what to do about sites where it was already removed and we're adding it back. Do we default everything to "default"?

Hm. Probably yes, as it's the default value of the database table column in D7.

> Also where the string is coming from configuration, such as where context is "config:system.core:anonymous", wondering if the textgroup should be something other than Built-in interface.

That's a good question. It could be something different.

**Comment by herbdool** [comment]
I think it's still a question of whether it's best to put this back in core or just leave it for i18n. I'm not sure which is less disruptive. We'll see if anyone else has an opinion.

**Comment by indigoxela** [comment]
> I'm not sure which is less disruptive. We'll see if anyone else has an opinion.

To be honest, if we're putting them back to core, I'd need some help and guidance, how I could handle the change in i18n. It's for sure feasible, but ATM I feel a bit lost.
Currently the table column is brought back in function i18n_string_schema_alter().

If core ships with it again (in whatever version), I'd have to consider that and also consider it in the bunch of code I added to export the .po files.

Yes, feedback please. :wink:

**Comment by herbdool** [comment]
I'm in the middle of doing a website upgrade so dealing with some of these issues in realtime. I realized that whether textgroup is re-added here or in i18n, it'll still mean that locale_update_1000() needs to be mostly removed. That's because it's removing *all* translations that aren't related to core (i.e "default"). Oops, can't have that. I guess we can't help with sites that have already been upgraded (including one I've done), but can help anyone going forward.

I saw the code in i18n_string_schema_alter(). Even if it stays there it at least won't run unless textgroup actually doesn't exist. As for exporting .po via i18n I don't know the extent of your changes there. How hard is it to revert anything which relies on textgroup only existing in i18n?

Anyway, it's possible to still drop textgroup in locale_update_1000() but don't delete the rows. And textgroup can be revived in i18n and repopulated based on i18n_string table. (I'll be providing some PRs to i18n soon regarding that).

**Comment by indigoxela** [comment]
I'd suggest to solve this problem in i18n - which turned out to be possible.

**Comment by indigoxela** [comment]
Is this issue obsolete? Contrib module i18n handles textgroups (adds field to table, implements hook_schema_alter...) - any change in core would require (yet another) module rewrite, so the module maintainer begs: "No please, leave it as-is now" :smile:

**Comment by herbdool** [comment]
Yeah, I think we have some consensus to just leave it in textgroup. (Ignoring for now configuration translation.)
