### ISSUE TITLE
Better documentation for dependencies when enabling, disabling or uninstalling modules

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4872]
The [`module_enable()`](https://api.backdropcms.org/api/backdrop/core%21includes%21module.inc/function/module_enable/1), [`module_disable()`](https://api.backdropcms.org/api/backdrop/core%21includes%21module.inc/function/module_disable/1) and [`backdrop_uninstall_modules()`](https://api.backdropcms.org/api/backdrop/core%21includes%21install.inc/function/backdrop_uninstall_modules/1) functions all have a parameter that determines whether dependencies will be taken into account when performing these actions. However, it's not obvious to me whether setting this parameter to `FALSE` will bypass dependency checking altogether and just perform the action regardless of the implications, or whether it simply prevents dependencies being *automatically* added/removed as needed...

For example, `module_enable()` has an `$enable_dependencies` parameter set to `TRUE` by default. The documentation says:

> If TRUE, dependencies will automatically be added and enabled in the correct order. This incurs a significant performance cost, so use FALSE if you know $module_list is already complete and in the correct order.

It also says that the return value of the function is:

> FALSE if one or more dependencies are missing, TRUE otherwise.

So can the function only return FALSE if `$enable_dependencies` is `FALSE`? Will it always return `TRUE` otherwise, because it automatically adds dependencies? What if a dependency hasn't been downloaded and doesn't exist in the filesystem?
Or will it always return `FALSE` if there are dependency issues, and setting `$enable_dependencies` to `FALSE` only serves to make things quicker if it's known that all dependencies are already satisfied?

I'm similarly confused about the two other functions. Especially `backdrop_uninstall_modules()`:

> **$uninstall_dependents**: (optional) If TRUE, the function will check that all modules which depend on the passed-in module list either are already uninstalled or contained in the list, and it will ensure that the modules are uninstalled in the correct order. This incurs a significant performance cost, so use FALSE if you know $module_list is already complete and in the correct order. Defaults to TRUE.

> Returns TRUE if the operation succeeds or FALSE if it aborts due to an unsafe condition, namely, $uninstall_dependents is TRUE and a module in $module_list has dependents which are not already uninstalled and not also included in $module_list).

If I set `$uninstall_dependents` to `FALSE`, will it uninstall the module regardless of any dependencies (potentially breaking the site)?

I believe these three functions could use some better, less-ambiguous documentation...

**Comment by BWPanda** [comment]
Ok, I did a test to see what would happen...

The Rules module depends on Entity Plus and Entity UI. On my test site, I had Entity Plus downloaded (but not installed), and Entity UI wasn't even downloaded. I downloaded Rules, then ran the following code with the following results:

- `dpm(module_enable(array('rules'), TRUE));` - `FALSE` was returned, Rules wasn't enabled, no error messages.
- `dpm(module_enable(array('rules'), FALSE));` - I got a fatal error message about some Entity class not found in one of the Rules files, and the whole site's broken now.

It seems that when set to `TRUE`, the second parameter enables dependency-checking. If dependencies aren't available, it'll return FALSE.
However, when the second-parameter is set to `FALSE`, dependency-checking is disabled altogether. You can therefore enable modules, without their dependencies, and break your site.

If my basic testing isn't flawed, then I think the following should happen (for the `module_enable()` function):

- The documentation for the `$enable_dependencies` parameter should be updated to explain that `TRUE` means dependencies are checked (and added automatically where possible), and `FALSE` means no dependencies are checked and the module(s) will be enabled regardless (site breakage may occur).
- The documentation for the return value should be updated to explain that if `$enable_dependencies` is `FALSE`, it will always return `TRUE` (i.e. the module(s) will always be enabled).

**Comment by BWPanda** [comment]
Have run a few more tests (using other modules, as it seems Rules was displaying errors even outside of my testing), and am dumping results here for future reference...

**Legend**: [Return value] / [Action was performed on module] / [Action was performed on dependencies/dependents]

ENABLE | $enable_dependencies=TRUE | $enable_dependencies=FALSE
-- | :--: | :--:
**Dependencies available** | TRUE / Yes / Yes | TRUE / Yes / No
**Dependencies missing** | FALSE / No / No | TRUE / Yes / No

DISABLE | $disable_dependents=TRUE | $disable_dependents=FALSE
-- | :--: | :--:
**Dependents enabled** | n/a / Yes / Yes | n/a / Yes / No
**Dependents disabled** | n/a / Yes / n/a | n/a / Yes / n/a

UNINSTALL | $uninstall_dependents=TRUE | $uninstall_dependents=FALSE
-- | :--: | :--:
**Dependents installed** | FALSE / No / No | TRUE / Yes / No
**Dependents uninstalled** | TRUE / Yes / n/a | TRUE / Yes / n/a

**Comment by BWPanda** [comment]
Here's an initial PR that updates documentation for `module_enable()`: https://github.com/backdrop/backdrop/pull/3494 Will add the other functions too soon.

**Comment by BWPanda** [comment]
PR now updates all 3 function's documentation and is ready for review.

**Comment by indigoxela** [comment]
This looks good to me, many thanks @BWPanda for clarifying these doc blocks. RTBC :+1:
(Your branch deserves a little rebase, it's lags behind a lot.)

**Comment by quicksketch** [comment]
I have a minor suggestion to the text in https://github.com/backdrop/backdrop/pull/3494/files#r665872649

I see this was opened quite some time ago. If @BWPanda has a chance to update it then that would be great. Otherwise I'll make the minor change the next time I'm going through the RTBC queue.

**Comment by BWPanda** [comment]
Thanks @quicksketch, PR updated.

**Comment by quicksketch** [comment]
Thanks @BWPanda! I merged https://github.com/backdrop/backdrop/pull/3494 into 1.x and 1.19.x.
