### ISSUE TITLE
Locale should not be deleting all "non-default" translations during an upgrade

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4874]
I'm in the middle of doing a website upgrade from Drupal 7. In `locale_update_1000()` is removing all translations that aren't related to core (i.e "default"). The update hook has this comment: "Update assumes i18n migrated this data before the update happened." But we can't have that since we can't expect i18n module in Drupal 7 to help us here since it is just set up for stability and there's no Drupal 8 version. So all of these translations just get lost. 

I guess we can't help with sites that have already been upgraded (including one I've done), but can help anyone going forward.

**Comment by indigoxela** [comment]
I'm not even sure, if "feature request" fits. Deleting bunches of translations is pretty destructive, I'm not surprised that we inherited that update hook from Drupal.

This commit [8b5bcb2a66](https://github.com/backdrop/backdrop/commit/8b5bcb2a66f48db942d0c8e7f36f9116ecee1e8b) did it.

Yes, please, lets remove that.

**Comment by herbdool** [comment]
Note that we should either merge this PR or the other, more ambitious one: https://github.com/backdrop/backdrop-issues/issues/4864, but not both. What might help us decide: without textgroup column will translations still work properly? That is, is it possible that there might be apparent "duplicates"?

**Comment by indigoxela** [comment]
> What might help us decide: without textgroup column will translations still work properly? That is, is it possible that there might be apparent "duplicates"?

I can't tell for sure, but textgroups shouldn't get mixed up with translation context. The latter prevents string ambiguity, the former allows export (and import) segregation and are for more reasons pretty important for i18n (contrib module).
Views (core) also has textgroup support, but that could be removed easily.

**Comment by herbdool** [comment]
I see, that helps me understand better.

Would it be possible to wrap the Views support for textgroup in a `module_exists('i18n')`? If so then perhaps we can just leave textgroup out of core.

**Comment by herbdool** [comment]
Ah, looks like it should be easy to ensure i18n is enabled for Views. (in `locale_views_data()`).

**Comment by indigoxela** [comment]
It seems, we're able to restore data thrown away in locale_update_1000() by using a temporary table in an update hook in module i18n (upgrade path there is work in progress).

Maybe this issue gets obsolete.

**Comment by herbdool** [comment]
Since core is expecting i18n to do something before I don't think it's a problem to tweak this update hook in core. What's the advantage of the temporary table over this pr?

**Comment by indigoxela** [comment]
> What's the advantage of the temporary table over this pr?

IMO the advantage is that data are kept only, when they're actually needed. It might happen that an upgraded site does not need i18n anymore. Then it would be OK to discard the data, I guess.

However, i18n still uses these data and with the temporary table(s) we're able to keep them without affecting other sites, that don't.

We could achieve the same by wrapping that "cleanup" in locale_update_1000() in `!module_exists('i18n')`, but then we also shouldn't drop column "textgroup", because that column contains important data, too.

I suppose, we can get a quicker solution by doing things in contrib (i18n). Waiting for a decision regarding core might take longer.

**Comment by indigoxela** [comment]
Is this issue obsolete? Contrib module i18n - which is probably the only one using these data - now takes care of keeping them.

**Comment by herbdool** [comment]
Agreed.
