### ISSUE TITLE
_locale_get_config_translatables() should use the proper context

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4878]
`locale_get_config_translatables()` is calling `locale()` with just the config name as the context, e.g. `site_name`. However it should be doing the same thing as `locale_enable()` which is setting the context like this `config:system.core:site_name`. I'll take the blame for this when I created the original PR a couple years ago.

**Comment by herbdool** [comment]
@indigoxela maybe we have time to squeeze this in too? This was a dumb mistake of mine a couple years ago.

**Comment by indigoxela** [comment]
> maybe we have time to squeeze this in too?

Unfortunately related tests are failing: `Undefined property: Config::$_config_name`

**Comment by indigoxela** [comment]
Before the change this resulted in, for example:
`locale('My cool site', 'site_name');` (incorrect)
After:
`locale('My cool site', 'config:system.core.site_name');` (correct)

So when importing a single (or syncing all) config, useless entries in db table locale_source get created - with the incomplete context string. This PR fixes it.

I verified with a single export/import of system.core.json, without and with patch applied. RTBC.

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop/backdrop/pull/3496 into 1.x and 1.18.x!
