### ISSUE TITLE
Backdrop shows a security update available if current version is a preview release

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4880]
<strike>Not sure if this is a bug, so I start it as a question.</strike> This is a bug, function update_calculate_project_update_status() does exact string comparison, which never matches for a pre-release version.

On sites that had 1.18.0-preview installed (for testing), 1.18.0 shows as "security update".

The "Available update" page looks weird, I'm pretty sure, that's not as intended:

![every-sec-update-ever-since](https://user-images.githubusercontent.com/842066/104808883-5c272d80-57e9-11eb-85a0-19c822e8a7ea.png)

I'm almost sure for the lengthy sec update list there's already a bugreport somewhere.

**Comment by laryn** [comment]
It also shows that way from 1.17.3:

![Screen Shot 2021-01-16 at 7 30 24 AM](https://user-images.githubusercontent.com/871421/104813126-ce3d4980-57cc-11eb-98a9-76cdd820c399.jpg)

**Comment by laryn** [comment]
Sorry for the noise... Just realized I saw this on a testing site that was on 1.17.3 (hadn't been upgraded to 1.17.4 as I thought)... :flushed:

**Comment by indigoxela** [comment]
I think, the problem is in core/modules/update/update.compare.inc

The version compare is exact, the loop stops adding releases, when `$project_data['existing_version'] === $version`, which never hits, as `1.18.0-preview` will never exactly match, so we get the full list of all releases ever.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3508) is available for testing and review.

**How to test:** install 1.18.0-preview and check admin/reports/updates

**Comment by klonos** [comment]
Straight-forward code change, and works as expected:

![image](https://user-images.githubusercontent.com/2423362/105640802-a6af4680-5e88-11eb-86dd-263dd3507a06.png)

RTBC 👍

**Comment by quicksketch** [comment]
Nice, thanks for finding and fixing this during the brief window when we had a preview release! I merged https://github.com/backdrop/backdrop/pull/3508 into 1.x and 1.18.x. I'm sure this will help contrib modules which use alpha/beta/rc releases more frequently.
