### ISSUE TITLE
Fix @file docblock formatting for install.inc

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4883]
The `@file` docblock for the `install.inc` file is missing a space before its asterisks. This result in improper formatting on the [API site](https://api.backdropcms.org/api/backdrop/core%21includes%21install.inc/1):

![image](https://user-images.githubusercontent.com/2385329/104836635-5a518d00-5903-11eb-8366-f9828e646de1.png)

**Comment by BWPanda** [comment]
Made a PR that fixes this (tested on my local API site).

**Comment by klonos** [comment]
Thanks @BWPanda  ...RTBC 👍

**Comment by BWPanda** [comment]
Thanks @klonos. I've merged https://github.com/backdrop/backdrop/pull/3498 into 1.x and 1.18.x.
