### ISSUE TITLE
Fix the links to non-existent pages in core

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4884]
It's not the bug per se, however not to confuse users we still have to address this one.

The `/core/modules/file/tests/file.test` contains links to non-existent pages as http://backdrop.org/node/1555862 and http://backdrop.org/node/1239376. There are no pages with such nids on http://backdropcms.org, however both links correspond to respective discussions on https://drupal.org/node/1555862 and https://drupal.org/node/1239376

**Comment by alanmels** [comment]
In fact, there are more occurrences of `backdrop.org` in core, so I'll submit one PR fixing all of them.

**Comment by klonos** [comment]
Seems that this was the result of a search/replace we didn't catch.

**Comment by indigoxela** [comment]
@alanmels Many thanks for your PR. There's nothing to "test", only comment and testcase changes. RTBC

BTW, security.backdropcms.org doesn't exist, just like security.backdrop.org, but that's irrelevant for these tests, because they only check for the syntax.

**Comment by BWPanda** [comment]
Thanks for finding and fixing this @alanmels! I've merged https://github.com/backdrop/backdrop/pull/3499 into 1.x and 1.18.x.
