### ISSUE TITLE
PHP Notice: Undefined index: label in filter_admin_format_form()

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4886]
**Description of the bug**

Implementation of [hook_editor_info()](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.api.php/function/hook_editor_info/1) in a custom module's function produces the error:

```
Notice: Undefined index: label in filter_admin_format_form() (line 245 of /var/www/docroot/core/modules/filter/filter.admin.inc).
```
**Steps To Reproduce**

To reproduce the behavior:
1. Use code from [the hook's API page](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.api.php/function/hook_editor_info/1) in a custom code. 
2. Enable the module and go to `admin/config/content/formats/filtered_html`, drop down the `Text editor` menu and note there is one empty option (next to None and CKEditor). 
3. Go to `admin/reports/dblog` to see the actual error.

**Additional information**

The API page for the hook is providing the following code:

```
function hook_editor_info() {
  $editors['myeditor'] = array(
    'title' => t('My Editor'),
    'settings callback' => '_myeditor_settings',
    'default settings' => array(
      'enable_toolbar' => TRUE,
      'toolbar_buttons' => array('bold', 'italic', 'underline', 'link', 'image'),
      'resizeable' => TRUE,
    ),
    'js settings callback' => '_myeditor_js_settings',
  );
  return $editors;
}
```
with the following explanation for the return value:

> **An associative array of editors, whose keys are internal editor names,**: which should be unique and therefore prefixed with the name of the module. Each value is an associative array describing the editor, with the following elements (all are optional except as noted):
> 
> - **title**: (required) A human readable name for the editor.
> - **settings** callback: The name of a function that returns configuration form elements for the editor. See [hook_editor_EDITOR_settings](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.api.php/function/hook_editor_EDITOR_settings/1)() for details.
> - **default settings**: An associative array containing default settings for the editor, to be applied when the editor has not been configured yet.
> - **js settings callback**: The name of a function that returns configuration options that should be added to the page via JavaScript for use on the client side. See [hook_editor_EDITOR_js_settings](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.api.php/function/hook_editor_EDITOR_js_settings/1)() for details.

However, in fact only [the following code](https://github.com/backdrop-contrib/bueditor/commit/08c2be1097257d6bff5a3ccad7fdbd42436a3c93) with minimal implementation worked correctly for BUEditor:

```
/**
 * Implements hook_editor_info().
 */
function bueditor_editor_info() {
  $editors['bueditor'] = array(
    'label' => t('BUEditor'),
    'library' => array('bueditor', 'backdrop.bueditor'),
  );
  return $editors;
}
```

So I believe API information for the hook needs to be re-worked.

**Comment by alanmels** [comment]
BTW, [the implementation of the hook by CKEditor](https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.module/function/ckeditor_editor_info/1) in core is consistent with the above finding:

```
function ckeditor_editor_info() {
  $editors['ckeditor'] = array(
    'label' => t('CKEditor'),
    'library' => array('ckeditor', 'backdrop.ckeditor'),
    'default settings' => array(
      'toolbar' => array(
        array(
          array(
            'name' => 'Formatting',
            'items' => array('Bold', 'Italic', 'Blockquote', 'Format'),
          ),
          array(
            'name' => 'Lists',
            'items' => array('BulletedList', 'NumberedList'),
          ),
          array(
            'name' => 'Alignment',
            'items' => array('JustifyLeft', 'JustifyCenter', 'JustifyRight'),
          ),
          array(
            'name' => 'Linking',
            'items' => array('BackdropLink', 'BackdropUnlink'),
          ),
          array(
            'name' => 'Media',
            'items' => array('BackdropImage'),
          ),
          array(
            'name' => 'Tools',
            'items' => array('Source', 'Maximize'),
          ),
        ),
      ),
      'format_list' => array('p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'),
      'style_list' => array(),
    ),
    'file' => 'ckeditor.admin.inc',
    'settings callback' => 'ckeditor_settings_form',
    'js settings callback' => 'ckeditor_get_settings',
  );

  return $editors;
}
```

So the `title` array member on the API changed needs to be replaced with `label`. Also without `library` array member it again gives error, therefore besides other optional array members such as `default settings`, the `label` and `library` should be described on API as required ones.

**Comment by indigoxela** [comment]
@alanmels Nice catch! Comparing the API docs to actual code in function filter_admin_format_form() confirms your finding.

```
  // Build the list of all available editors.
  $editor_options = array('' => t('None'));
  foreach ($editors as $editor_name => $editor) {
    $editor_options[$editor_name] = $editor['label'];
  }
```
This should be `label`, not title.

So two API examples are misleading:

- hook_editor_info() and its doc block should use label instead of title.
- hook_editor_info_alter() should also use label instead of title

Mind to file a PR?

**Comment by alanmels** [comment]
I happily would, however I am not sure what should be description for `library` array member. You see I've got away using at least two array members in https://api.backdropcms.org/api/backdrop/core%21modules%21ckeditor%21ckeditor.module/function/ckeditor_editor_info/1, so without `library` it will give an error. Give me your best description for `library` and I will create PR.

**Comment by indigoxela** [comment]
> so without library it will give an error. Give me your best description for library and I will create PR.

Another nice catch... I suppose that happens because function [filter_get_attached()](https://api.backdropcms.org/api/backdrop/core%21modules%21filter%21filter.module/function/filter_get_attached/1) assumes that `$editor['library']` exists.

Can you confirm that? (Did the error you got refer to function filter_get_attached?)

In that case we should either state that `library` is a required key, or catch it in function filter_get_attached with an `isset()`.
The related comment in that function states:
`// Add the library associated with a format's editor if needed.`
But the function doesn't check if the key exists.

Personally, I don't think that editors will always ship with a Javascript library, so that key shouldn't be required. But maybe a core committer can provide more info.
Either way (required or not), the `library` key should be mentioned in the doc block. Sort of: "A Javascript library associated with the editor."

**Comment by alanmels** [comment]
I do confirm the second error is about `filter_get_attached()` function:

```
Notice: Undefined index: library in filter_get_attached() (line 1422 of /var/www/docroot/core/modules/filter/filter.module).
```

> Personally, I don't think that editors will always ship with a Javascript library, so that key shouldn't be required. But maybe a core committer can provide more info.

I feel the same way. Because BUEditor does not have library, however I had to use:

```
/**
 * Implements hook_editor_info().
 *
 */
function bueditor_editor_info() {
  $editors['bueditor'] = array(
    'label' => t('BUEditor'),
    'library' => array('bueditor', 'backdrop.bueditor'),
  );
  return $editors;
}
```
just to satisfy the core's requirements. So shall we wait a core commiter to put their stance here or am I good to proceed to creating PR making the `library` not required?

**Comment by indigoxela** [comment]
> So shall we wait a core commiter to put their stance here or am I good to proceed to creating PR making the library not required?

Hm, I'd say proceed (make it optional). When it comes to merging, a core committer will have a look, anyway. :wink:

**Comment by alanmels** [comment]
Please review https://github.com/backdrop/backdrop/pull/3500/files

**Comment by indigoxela** [comment]
@alanmels Many thanks for fixing the doc comment and for the code cleanup in function filter_get_attached().

Test are all passing, CKEditor in the sandbox still works fine, RTBC.

**Comment by alanmels** [comment]
@indigoxela, thanks for your review.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3500 into 1.x and 1.18.x. Thanks @alanmels and @indigoxela!
