### ISSUE TITLE
Add `_config_translatables` for sites installed before May 2019 (and all sites migrated from D7)

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4888]
**Description of the bug**

When upgrading from Drupal 7, user.mail settings get converted to config in user_update_1005(), but no _config_translatables get added. Later on, in user_update_1017() mail text for pending approval get added, but at that point there are no translatables set.

So the upgrade ends up with only two translatables for user.mail (register_pending_approval_admin_body and register_pending_approval_admin_subject). All the others are missing in the json file, which means only the two strings added in 1017 can get translated.

The same happens with system_update_1017() and system.core. There are zero translatables in the resulting json file.

The same problem happens in Backdrop sites that were installed before the translatables got added. No config translation.

**Steps To Reproduce**

Upgrade from D7 and then inspect the resulting user.mail.json in your active config directory.

Or visit one of your older Backdrop sites, initially installed before May 2019.

**Full list of translatables:**

user.mail
```
    "_config_translatables": [
        "cancel_confirm_body",
        "cancel_confirm_subject",
        "password_reset_body",
        "password_reset_subject",
        "register_admin_created_body",
        "register_admin_created_subject",
        "register_no_approval_required_body",
        "register_no_approval_required_subject",
        "register_pending_approval_body",
        "register_pending_approval_subject",
        "register_pending_approval_admin_body",
        "register_pending_approval_admin_subject",
        "status_activated_body",
        "status_activated_subject",
        "status_blocked_body",
        "status_blocked_subject",
        "status_canceled_body",
        "status_canceled_subject"
    ],
```
system.core
```
    "_config_translatables": [
        "anonymous",
        "site_name",
        "site_slogan",
        "maintenance_mode_message"
    ],
```

**Expected behavior**

All config translatables available like in a new Backdrop install.

**Comment by indigoxela** [comment]
As this means that people who already did the upgrade are missing translatables, we can't simply update the two hooks that didn't add them.

Idea: get the two configs (user.mail, system.core) and if the count of "_config_translatables" is less than expected, update the values. Or should be just always update?

**Comment by indigoxela** [comment]
**Update:** the translatables are also missing in older Backdrop installs, one more reason to fix this.

A [PR](https://github.com/backdrop/backdrop/pull/3504) is available for testing and review.

**Comment by herbdool** [comment]
Good catch. I was wondering too the best way to check. Perhaps best to just fetch the whole _config_translatables array if it exists and add the items and reduce duplicates before writing the config back. We don't really need to check if they're there already or not.

**Comment by indigoxela** [comment]
@herbdool What do you think about my PRs approach?

**Comment by klonos** [comment]
@indigoxela how about this:

- make sure that the default config we include with core modules has all required translatables
- use a code similar to `config_install_default_config()`, to load all expected translatables
- do a regular `$config->get('_config_translatables')` on the already installed module
- compare existing translatables vs expected translatables
- add any missing ones and makes sure no duplicates
- `$config->save()`

I think that a reusable `config_update_translatables($module)` function would be nice, so that contrib can use it as well. What do you think?

**Comment by indigoxela** [comment]
Ehm... it seems, you all underestimate my impatience. :smile: A PR is available since yesterday.

If you have any suggestions, why not posting comments at the PR?

**Comment by klonos** [comment]
> it seems, you all underestimate my impatience. ...If you have any suggestions, why not posting comments at the PR?

Sorry 😅  ...added comments in the PR.

**Comment by indigoxela** [comment]
> Sorry sweat_smile ...added comments in the PR.

No problem, you're welcome.

Now some answers to your previous comment:

> make sure that the default config we include with core modules has all required translatables

The default config is always the "source of knowledge", if translatables aren't defined there, they don't exist, at least that's what I think.

> use a code similar to config_install_default_config(), to load all expected translatables

A function to get default values could be a nice to have feature - are there more use-cases for it, than this bug / issue here?

> do a regular $config->get('_config_translatables') on the already installed module

Hm, not sure about that. Don't we trust our own system? ... OK except for this current bug. :wink:

**Comment by klonos** [comment]
>A function to get default values could be a nice to have feature - are there more use-cases for it, than this bug / issue here?

Yeah, it would be nice. Contrib could reuse that too.

> Hm, not sure about that. Don't we trust our own system?

I see what you mean. Then how about just getting the translatables from the default config that ships with each module, and "blindingly" adding/updating existing config (skipping the whole compare part).

**Comment by klonos** [comment]
BTW, why are you replying here and not in the PR 😝

**Comment by indigoxela** [comment]
> BTW, why are you replying here and not in the PR stuck_out_tongue_closed_eyes

Ehem... Because you commented here :laughing: 

>>    A function to get default values could be a nice to have feature - are there more use-cases for it, than this bug / issue here?

> Yeah, it would be nice. Contrib could reuse that too.

What are possible additional use-cases?

**Comment by klonos** [comment]
> What are possible additional use-cases?

I can only think of when needing to compare current configuration with the default, OOTB state, and then possibly revert. With modules for example, this may happen when disabling -> uninstalling -> reinstalling.

**Comment by indigoxela** [comment]
> I can only think of when needing to compare current configuration with the default, OOTB state, and then possibly revert. With modules for example, this may happen when disabling -> uninstalling -> reinstalling.

That seems like a valuable feature, although I don't have a real use-case in mind, yet.

But I do have one concern (already noted in a PR comment answer):
Adding a new function to core might need some more time and discussions and possibly blocks this bugfix until May (1.19). Waiting for months for a bugfix, we already have a solution for, doesn't seem very efficient to me.

In case, more people vote for a "read the original config file" feature - could it be a follow-up?

**Comment by klonos** [comment]
> ...although I don't have a real use-case in mind, yet.

We already allow reverting core-provided views.

> ...and possibly blocks this bugfix until May (1.19).

The new function could be a follow-up.

**Comment by indigoxela** [comment]
> We already allow reverting core-provided views.

Actually, that was the first thing I checked, when you suggested to add a new function. :wink: But views does it with the "storage" property (see VIEWS_STORAGE_OVERRIDE), so that's not applicable for our comparison use-case.

**Comment by klonos** [comment]
> views does it with the "storage" property

Gotcha

**Comment by indigoxela** [comment]
My PR has been updated as suggested, ready for another review.

**Comment by herbdool** [comment]
Code looks good to me. I'll do some testing soon.

**Comment by herbdool** [comment]
I've tested with a D7 upgrade. Without the patch I have missing translatables. With the patch it works! Thanks @indigoxela

**Comment by quicksketch** [comment]
This looks great. I'd like to move this to 1.18.2 however, so our security update (coming today) doesn't require an update.php run.

**Comment by quicksketch** [comment]
I have merged https://github.com/backdrop/backdrop/pull/3504 into 1.x and 1.18.x. Thanks @indigoxela, @herbdool, and @klonos!

**Comment by cptX** [comment]
I can verify this patch works for site slogan in 1.18.1
