### ISSUE TITLE
language negotiation setting not upgraded properly from Drupal 7

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4889]
**Description of the bug**

When upgrading from Drupal 7, the language detection configuration does not get set.

**Steps To Reproduce**

- Create a D7 site with multiple languages, with path prefix set for language detection
- Upgrade to Backdrop

**Actual behavior**

The setting is empty. (Neither path prefix nor domain)

**Expected behavior**

The setting should be kept.

**Comment by indigoxela** [comment]
And this seems to be the problem:

In Drupal 7:
```
includes/locale.inc:define('LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX', 0);
includes/locale.inc:define('LOCALE_LANGUAGE_NEGOTIATION_URL_DOMAIN', 1);
```

In Backdrop:
```
includes/locale.inc:define('LANGUAGE_NEGOTIATION_URL_PREFIX', 'path_prefix');
includes/locale.inc:define('LANGUAGE_NEGOTIATION_URL_DOMAIN', 'domain');
```

The defined values changed.

In function locale_update_1003() it's attempted to migrate the setting with:
```$config->set('language_negotiation_url_part', update_variable_get('locale_language_negotiation_url_part', 'path_prefix'));```

This results in an entry in locale.settings.json like `"language_negotiation_url_part": "0",`.

But a value of "0" or "1" has no meaning in Backdrop. We need to update locale_update_1003() to reflect the changed values.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3506) is available for testing and review.

**Comment by klonos** [comment]
Code looks good 👍  ...just need to test the D7 -> Backdrop upgrade path before/after the change.

**Comment by herbdool** [comment]
I came across this a few days ago but didn't report it (oops!). Thanks for the fix - this works for me.

**Comment by quicksketch** [comment]
Looks great folks. Merged https://github.com/backdrop/backdrop/pull/3506 into 1.x and 1.18.x. Thanks!
