### ISSUE TITLE
Change Role edit URLs to use the word 'configure' instead.

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#4899]
There was an [issue](https://github.com/backdrop/backdrop-issues/issues/771) years ago to consistently use the words 'edit' and 'configure' appropriately. The Roles page (`/admin/config/people/roles`) has drop-buttons that say 'Configure role', but the URL is `/admin/config/people/roles/edit/[ROLE]`.

Image Style 'edit' URLs were deprecated and redirected to 'configure' URLs, so I propose doing the same thing here.

**Comment by klonos** [comment]
@BWPanda a test is failing re the "Cancel" link.

**Comment by BWPanda** [comment]
Ah thanks. Missed one. PR updated and tests passing.

**Comment by klonos** [comment]
Code looks good, but the redirects do not work as expected (which means that perhaps we'd need to adjust our current tests):

- configure a role, say `admin/config/people/roles/configure/administrator`
- manually change the URL to `admin/config/people/roles/edit/administrator` and hit enter -> 404 👎 

You get redirected to `admin/config/people/roles/configure/%25user_role`

**Comment by BWPanda** [comment]
@klonos The redirect issue is being worked on in https://github.com/backdrop/backdrop-issues/issues/2833.

In https://github.com/backdrop/backdrop-issues/issues/2817#issuecomment-326834570 @quicksketch said that the redirection issue shouldn't hold up changing paths, so I'm thinking this should be able to go ahead as-is...

**Comment by klonos** [comment]
> The redirect issue is being worked on in #2833. ...this should be able to go ahead as-is

Agreed 👍 ...I'd forgotten about that issue. This is RTBC then 😉

**Comment by jenlampton** [comment]
It looks like the menu entries with `backdrop_goto_deprecated()` are missing. 

Getting them working (via https://github.com/backdrop/backdrop-issues/issues/2817#issuecomment-326834570) shouldn't hold up adding them in, but they still need to be added in this PR.

**Comment by jenlampton** [comment]
> maybe I mssised then. Checking again... 

Yep, it's there. I'm blind :) 

```php
// @deprecated: Remove backwards-compatibility redirect in 2.0.
  $items['admin/config/people/roles/edit/%user_role'] = array(
    'page callback' => 'backdrop_goto_deprecated',
    'page arguments' => array('admin/config/people/roles/configure/%user_role'),
    'access arguments' => array('administer permissions'),
    'type' => MENU_CALLBACK,
  );
```

**Comment by quicksketch** [comment]
Thanks @BWPanda!

In my previous comment (https://github.com/backdrop/backdrop-issues/issues/2817#issuecomment-326834570), that was for a minor release. I think we should either wait on this until 1.19.0, or get the wildcard redirects working in https://github.com/backdrop/backdrop-issues/issues/2833

**Comment by quicksketch** [comment]
I'm putting this in 1.19.0 for now, as we're about to release 1.18.1. Please move again as needed.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3509 into 1.x for 1.19.0. Thanks folks! I'll take a look at that redirect issue again to see if we can move forward with fixing deprecated wildcard redirects (https://github.com/backdrop/backdrop-issues/issues/2833).

**Comment by quicksketch** [comment]
I rerolled https://github.com/backdrop/backdrop-issues/issues/2833 and updated it to work in combination with this change, so if completed, the new redirects added in this issue would be completely redirected.
