### ISSUE TITLE
Translating `Show password` and `Hide password` does not work

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4900]
To replicate the issue, just install any language in addition to English, go to `/admin/config/regional/translate/translate` and try to translate `Show password` or `Hide password`, clear cache, log out and go to `/user/login` to find both strings didn't translated.

Not sure is it because of toggle function, but both strings are correctly put in between `t()` function as https://github.com/backdrop/backdrop/blob/0362219161a9b42275fdfbe54ae36d857c2af672/core/modules/user/user.module#L2903 shows:

```
  if ($element['#password_toggle']) {
    $toggle_settings = array(
      'toggleShowTitle' => t('Show password'),
      'toggleHideTitle' => t('Hide password'),
      'toggleDefault' => $element['#password_shown'] ? 'show' : 'hide',
    );

    $element['#attributes']['data-password-toggle'] = backdrop_json_encode($toggle_settings, FALSE);
  }
```

**Comment by indigoxela** [comment]
@alanmels I can't reproduce the problem, text is translated here (same steps as you did). Here's an example in German.

![show-pw-text](https://user-images.githubusercontent.com/842066/105574588-e92c3280-5d65-11eb-89cd-0991faadc129.png)

Could it be a problem with browser cache?

**Comment by alanmels** [comment]
Turned a false alert. Indeed it was a browser cache problem. Thanks!
