### ISSUE TITLE
Field UI: (Almost) empty page titles on display settings pages for user and comment

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4901]
**Description of the bug**

It starts in [field_ui_menu()](https://github.com/backdrop/backdrop/blob/0362219161a9b42275fdfbe54ae36d857c2af672/core/modules/field_ui/field_ui.module#L59), where comment and user entities have no bundle argument, so only the string (bundle name) can get handed over to function field_ui_display_form().

Function [field_ui_display_form()](https://github.com/backdrop/backdrop/blob/1.x/core/modules/field_ui/field_ui.admin.inc#L933) relies on the $bundle variable to be an object, to set the page title to "bundlename: displaymode".
So that won't work for comment or user, "bundlename" stays empty.

Which results in page titles like that:

![empty-field-ui-title](https://user-images.githubusercontent.com/842066/105577817-1f74ac80-5d7c-11eb-995b-8de5061a5645.png)

It's a minor UI bug.

**Steps To Reproduce**

To reproduce the behavior:
1. Go to admin/config/people/manage/display/default
2. Or go to admin/structure/types/manage/post/comment/display/default
3. Inspect the page heading and meta title

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3511) is available for testing and review.

Here's the same page title with this fix:

![correct-field-ui-title](https://user-images.githubusercontent.com/842066/105578066-dc1b3d80-5d7d-11eb-8d20-e41dc4abb4e8.png)

**Comment by klonos** [comment]
@indigoxela not 100% sure, but can you please have a look at the `field_extract_bundle()` function, which is by the way called a few lines after the code you've added, in the form of `$bundle = field_extract_bundle($entity_type, $bundle);`. It feels that this should be moved at the beginning of the `field_ui_display_form()` function, and then re-work the logic in those `if`/`elseif` `is_object($bundle)` things at the top.

Be warned that I could be totally wrong though 😅

**Comment by indigoxela** [comment]
@klonos many thanks for having a look!

Function field_extract_bundle() returns the *name* - which we already have, but not the *label* - which we'd need.

At that point in function field_ui_display_form() the only info we get from hook_menu() is the string ` $entity_type` and string `$bundle`, that's why I use entity_get_info() to get the label for the entity.

**Comment by klonos** [comment]
Yeah ...I quickly tested on my local, and things wouldn't work they way I'd imagine. I was about to post a "never mind" comment here, but you beat me to it @indigoxela 😅 

Code looks good, and things work as expected. RTBC 👍

**Comment by quicksketch** [comment]
There's a minor issue in the PR that could cause strings to be double-encoded. This problem already exists in the current code, where the Entity type label could contain a character like `<` or `&` and then it will get double-encoded in the page title. I posted a comment to the PR as well: https://github.com/backdrop/backdrop/pull/3511#pullrequestreview-577754176

**Comment by indigoxela** [comment]
@quicksketch many thanks for your hints!

I decided to keep the sanitize job in backdrop_set_title() - see my comment for an explanation. I added a code comment to clarify that the title components aren't sanitized yet and that backdrop_set_title() does it. As a hint if someone want's to re-use one of the variables later on in that function - which currently isn't the case.

**Comment by indigoxela** [comment]
This PR still needs a final review. It would be nice, to get this small UI fix in.

**Comment by klonos** [comment]
@indigoxela can you please rebase the PR for this? Thanks.

**Comment by laryn** [comment]
Thanks @indigoxela for filing and fixing, and to @quicksketch, @klonos, and @docwilmot for code review and testing! I've merged the PR in https://github.com/backdrop/backdrop/pull/3511 in https://github.com/backdrop/backdrop/commit/1ab106d09ab934caf80e1c62152a856715eab1b7 for 1.x and 1.19.x.
