### ISSUE TITLE
Convert the hard coded path field to a fieldable field

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#4908]
I would love to see the hard coded path field converted to an entity field or at the very least, exposed to the "manage fields" page where it could be disabled for a particular entity.

Taxonomies are used for a lot more than tagging content; for example they can be used as select lists. This means that currently, any taxonomies that you don't want to be indexed, have to be added as a disallow to the robots file.

In the case of the content type, maybe someone needs to use a node as a "fieldable block" inside a layout. The architect could opt to remove the path field so there is no "public" alias. Maybe they need a bunch of nodes to hold info to be displayed in a view, but the nodes themselves do not need a path.

How cool would it be to have a configurable path alias field that can be added or removed based on the usecase? I feel like this approach would give the platform a lot more flexibility overall.

Internal paths can continue to work as they always have and the hard coded entities can continue to work as they always have.

**Comment by klonos** [comment]
@philsward as far as content types go, Backdrop includes what used to be the Rabbit Hole module in core, so what you are asking can be achieved already. See the "Hide path display" checkbox in the "Display settings" tab when configuring a content type:

> If enabled, this content can be placed as a block or within a listing but will not be accessible at its URL without proper permissions. This facilitates "hidden path" content that is meant to be embedded with other content and never on its own. Users who have the "View hidden paths" permission will still be able to visit the full page URL, while those without this permission will receive a "Page not found" error.

Wouldn't that work for the use case you had in mind?

What we could consider is to extend this functionality to also be available for vocabularies (or other entities).

**Comment by klonos** [comment]
...yup, the [Drupal version of the contrib module](https://www.drupal.org/project/rabbit_hole) that offers this functionality already support more entities:

> ## Supported entities
> This project includes sub modules that are responsible to add this behavior to different entities. The currently supported entities are:
> 
> - Nodes
> - Taxonomy terms
> - Users
> - Files
> - Field collection
> - Profile 2
> - Bean
>
> You'll only need to enable the modules that you wish to add the functionality for. More entities are likely to be supported in the future. If you have a suggestion, submit a feature request using the issue queue.

**Comment by philsward** [comment]
@klonos I'll take a look. Thanks for pointing it out.

I have zero experience with the Drupal version of it so I don't even know where to look for it on Backdrop.

That said, some of these things might be found better if they were to live in a different area (UX). I'll post back and close this if I feel like it does what I would expect.

**Comment by klonos** [comment]
> I'll post back and close this if I feel like it does what I would expect.

I suspect that Backdrop core already does what you are after, **but only for content types**. We could repurpose this issue to support additional entities (taxonomy terms, files, users).

**Comment by philsward** [comment]
@klonos I don't see it in core and I took a look at the rabbit hole module.

While the rabbit hole module looks like it would do what I'm suggesting, I think core could handle this a lot better.

The suggestion here is a feeler for a much bigger picture I have for all of the admin fields. I've always struggled on Drupal with being able to manipulate the hard coded fields. Because you can't... I ran across a module once (can't remember the name) that would expose all of the admin fields but it was too buggy to use in a live environment when I tested it years ago.

**Comment by philsward** [comment]
This took a while to find... Example module: https://www.drupal.org/project/rel

**Comment by stpaultim** [comment]
I don't know if this is exactly what you are looking for. But, I believe that this is the issue that @klonos is referring to (committed Sept 2018). This seems to meet at least part of your use case.

https://github.com/backdrop/backdrop-issues/issues/100

![hide path display](https://user-images.githubusercontent.com/3144571/105788330-e38d4300-5f45-11eb-95d7-1f83a0807972.png)

**Comment by philsward** [comment]
@stpaultim Well boo... Thanks for pointing it out. So many nuggets that I just haven't run across yet.

Good enough.

**Comment by stpaultim** [comment]
Well, as others have pointed out. We could expand this feature to other entities. I'm not sure if there are open issues on that yet. BUT, this is a good start.

**Comment by klonos** [comment]
> @klonos I don't see it in core and I took a look at the rabbit hole module. ... @stpaultim Well boo... Thanks for pointing it out. So many nuggets that I just haven't run across yet.

@philsward I guess you are a visual person 😅 ...because I've explained in words what @stpaultim pointed with a screenshot:

> See the "Hide path display" checkbox in the "Display settings" tab when configuring a content type

**Comment by klonos** [comment]
> We could expand this option to other entities.

I think that a separate issue, with a clean start re comments would be best. Here it is: #4912

**Comment by philsward** [comment]
@klonos I skim everything I read. It's bad on my part, but just how my brain is wired.

If I don't see the keywords that create the context of what I think is being said, I end up overlooking what is actually being said.

I'll explain further... I read maybe 5 words and my brain starts working. I become so consumed with my thoughts and forming what I think is being said, so I can "hurry up and be done", that I sometimes overlook the actual context and look like the village idiot in the process.

It gets even worse if the ideas start flowing because I want to hurry up and get them down before they leave.

Welcome to my world of looking at everything from a wide-angle lens...

**Comment by philsward** [comment]
BTW, thx for getting the path display setting issue created for taxonomy.

**Comment by klonos** [comment]
> ...I sometimes overlook the actual context and look like the village idiot in the process.

🤣 ❤️ 

> It gets even worse if the ideas start flowing because I want to hurry up and get them down before they leave.

That happens to me too ...like, A LOT! ...how I deal with it is open new browser tabs and start putting my thoughts down in the form of draft issues. ~85% of the times, these drafts end up being submitted as actual issues; ~10% I discard because in the process of writing things down, I realize that things are either hard/impossible or my thinking was simply flawed. The rest ~5% gets lost because my browser eventually crashes on me 😅 

> ...thx for getting the path display setting issue created for taxonomy.

You are welcome ...I am known for opening new issues out of thoughts/ideas people randomly post on other issues 😉 ...what ends up happening is that I open all these issues, and then @BWPanda cleans up after me a few years later (sorry).

**Comment by philsward** [comment]
So I've noticed Github is kind of bad about project management.

You might check out https://www.notion.so/ to create a workflow that makes sense for you.

I could see the Backdrop community using it, but I'm not going to push the idea.

On a side note, is it me or is the github website a nasty memory hog?
