### ISSUE TITLE
install.sh script uses 'locale' instead of 'langcode'

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4915]
**Description of the bug**

The [install.sh](https://github.com/backdrop/backdrop/blob/1.x/core/scripts/install.sh) script uses '[locale](https://github.com/backdrop/backdrop/blob/0362219161a9b42275fdfbe54ae36d857c2af672/core/scripts/install.sh#L150)' when it should be using 'langcode'.

**Steps To Reproduce**

To reproduce the behavior:
1. Make sure the translation file for a language other than English is available
2. Run the install.sh script from the command line, specifying the language with `--locale=[CODE]`

**Actual behavior**

> An error occurred. Output of installation attempt is as follows:
> Sorry, you must select a language to continue the installation.

**Expected behavior**

Site installs in the specified language.

**Additional information**

'langcode' appears to be correct based on:

- URL parameter when installing the site via the UI
- [install_begin_request](https://api.backdropcms.org/api/backdrop/core%21includes%21install.core.inc/function/install_begin_request/1)

**Comment by BWPanda** [comment]
@indigoxela I think this might be up your alley... 🙂

**Comment by indigoxela** [comment]
@BWPanda many thanks for your PR! Obviously installing Backdrop in a foreign language via command line isn't done very often. 

First of all I confirmed the broken install when using the "locale" command line parameter.

I created the files/translations/ directory and added the translation file (backdropcms-1.18.de.po) in there, then ran the script:

`sudo -u www-data ./core/scripts/install.sh --db-url=mysql://bla:bla@localhost/bla --account-name=bla --account-pass=bla --locale=de`

Which resulted in:
```
An error occurred. Output of installation attempt is as follows:
Sorry, you must select a language to continue the installation.
```

Then I applied the patch and ran the same command again and got:
```Backdrop installed successfully.```
And a fully functional Backdrop install.

Works like a charm. :+1:

**Comment by klonos** [comment]
Code changes also look good 👍 ...RTBC

**Comment by indigoxela** [comment]
I'm assuming that installing in other languages has never worked (since 2013) - how could it. So we don't have to care about backwards compatibility (no need to catch the removed locale parameter). The code change is straight forward, RTBC from my side.

Regarding the milestone I'm a bit insecure... But I see that @klonos beat me to it. :smile:

**Comment by klonos** [comment]
Yup, ditto 😅

**Comment by quicksketch** [comment]
Thanks folks! I agree that changing the argument is of little consequence because it hasn't been working in the first place. I merged https://github.com/backdrop/backdrop/pull/3520 into 1.x and 1.18.x. Thanks!
