### ISSUE TITLE
Add Insert Block Button to CKEditor

### ISSUE THREAD

**Issue by mikesoltis** [backdrop/backdrop-issues#4916]
**Description of the need**

The module would benefit long-ish manuals and description pages that incorporate tables, publication references or other displays generated by Views.

**Proposed solution**

The button would insert a block at the current cursor position, chosen from a list of blocks (Like CKEditor Blocks for Drupal)

CKEditor Blocks at https://www.drupal.org/project/ckeditor_blocks

**Alternatives**

Layouts can be used for short pages with single contiguous text and some blocks, but not applicable for longer interspersed pages of text and views blocks.   

**Draft of feature description for Press Release (1 paragraph at most)**

Backdrop now includes embedding blocks in CKEditor.

**Comment by indigoxela** [comment]
@mikesoltis Many thanks for taking the time to create this issue.

> Alternatives
> 
> Layouts can be used for short pages with single contiguous text and some blocks, but not applicable for longer interspersed pages of text and views blocks.

Are you sure? The strength of layouts is the ability to compose pages of any length from blocks, views, existing nodes (content)... If adding a context, it's even possible to add individual fields of the context entity to any region of that layout.
And you can construct your own layouts with flexible layout templates - without writing a single line of code.
Compared to that embedding blocks in a node body feels pretty limited.

Possibly you didn't discover the full power of layouts yet?

BTW: the use-case you describe lets me think of the [Paragraphs](https://backdropcms.org/project/paragraphs) module.

**Comment by mikesoltis** [comment]
OK - I should test building one of the longer pages (from my drupal 7 site) with flexible layouts or more likely, paragraphs - my intuition said avoid breaking up these manuals into potentially many subsections, but I think it does offer more flexibility.  One issue though will be porting the 50+ pages of manuals over to the new format! 
Thanks for the feedback.

**Comment by indigoxela** [comment]
> One issue though will be porting the 50+ pages of manuals over to the new format!

I see... If I get it right, the ckeditor_blocks module uses a token-like syntax (I never used it)? I agree, porting those pages could get tricky.

But you still have options:

- Add a port request in the [backdrop-ops/contrib](https://github.com/backdrop-ops/contrib/issues) issue queue (success isn't guaranteed, though)
- Find a way to migrate the pages (custom code) - the blocks themselves should get ported properly, when upgrading from D7
- Use the feeds module to import markup into body fields (could create messy content)
- Ask in our [Zulip chat](https://backdrop.zulipchat.com/) for other ideas - maybe someone has done something similar before

Anyway, to me this seems rather like a contrib candidate. The D7 module page reports only 514 installs - not enough to include it in Backdrop core, I guess.

**Comment by klonos** [comment]
@mikesoltis I understand where you are coming from. This request makes more sense when you need to "inject" things that are generated by Views or other modules (like charts, slideshows etc.) into arbitrary positions within long pieces of text. This way of injecting token-like "thingies" reminds me of the way WordPress allows for snippets of of code-like thingies, called "shortcodes". That method has both pros and cons, but it is the main difference between WordPress (where pages are stored as huge "blobs" of all-the-things in the database) and Drupal/Backdrop (where "pages" are actually data-driven structured content, rendered from various things stored in the database).

I also agree that [Paragraphs](https://backdropcms.org/project/paragraphs) is a better fit for this use case, so that the various views/charts/slideshows/what-have-you can be moved intuitively within the main text of the page.

Allowing "blocks" within the WYSIWYG is basically the same as using Gutenberg and the various look-alikes that have sprung all over the internet lately. Unfortunately, using something like Gutenberg would mean giving up on the way Backdrop/Drupal fundamentally work. Having said that though, it can be done: https://www.drupal.org/project/gutenberg (and there are more modules, integrating other such editors).

**Comment by mikesoltis** [comment]
Update - I tested Paragraphs, Paragraphs can be used to effectively "insert" images and files within paragraphs of text in the Paragraphs field using different Paragraph Types such as Image and File. So analogous in a way that Insert works for Ckeditor.

But Paragraphs also has the same issue as Ckeditor.  There is no easy way to inject a view or a block (from a list) into a Paragraph Type.  Ckeditor and Paragraphs require the same functionality in order to easily insert a block (i.e. something like the CKEditor Blocks module at https://www.drupal.org/project/ckeditor_blocks). 

Alternatively, the Insert View module allows for a token replacement anywhere in the body/paragraph text, based on the name of the view and display [view:view_name=display_name] - better, but still a manual process and you need to find the block name and display name and it only workd for views.

The Block Embed module allows for embedding a block after a specified number of paragraphs. But I haven't got it to work yet and it doesn't look like it works per node - rather per node type.

Layouts lets you insert blocks anywhere in the layout, but for a long manual with lots of view blocks, it requires breaking the manual into separate text fields or blocks.  This makes the insertion of images and files with selectable formatting break (Insert only works with the Body field).

Using Paragraphs with Layouts "could" be the best solution because you can add the Paragraph field (Field_paragraph) to the layout.  However, since you can't select which Paragraph Items within the field to display in the layout, its not a solution.  I tried using the Trim parameter in the Field_paragraph Configuration, but it could not be used to control the display of individual Paragraph Items.

So I will make requests for: a CKEditor Blocks port (insertion from a list) and/or the ability for Layouts to select individual paragraph entries within the Paragraphs field.  The later is the more powerful, but I presume more of a challenge to implement.

**Comment by laryn** [comment]
> There is no easy way to inject a view or a block (from a list) into a Paragraph Type.

@mikesoltis, you could use [ViewField](https://github.com/backdrop-contrib/viewfield) to add a field to a Paragraph Type that allows a view to be inserted.

> ... the ability for Layouts to select individual paragraph entries within the Paragraphs field.

Not 100% sure I understand your need exactly, but you could set up multiple Paragraph fields on a content type (e.g. Sidebar Paragraphs; Content Paragraphs, Footer Paragraphs, ...) and then pull those Paragraph fields out separately in the layout in the correct region. Each of those Paragraphs fields could be defined to allow only certain kinds of Paragraphs types if desired (e.g. if you don't want to allow certain kinds of Paragraphs types in the sidebar region).

**Comment by mikesoltis** [comment]
>you could use ViewField to add a field 

I forgot about this one, since I did test it recently - ViewField does solve the problem!  Thanks!  The drawback at the time I tested it was that the Insert module did not work with it.  But I had not used Paragraphs yet. Now I can easily arrange Files, Text, Images and Views types within a Paragraphs field.
