### ISSUE TITLE
autocomplete-enabled link in editor complains that path to translated content is not a valid URL...?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4917]
**Description of the bug**

I cannot add a link to the Spanish translation of a page, from the English version of that same page. I tried various other combinations with and without the language code `/es`, but could not find anything that would work, including the URL shown in the browser's address bar for that page.

The error I get is always `The URL /es/meetings/abcde is not valid`

**Steps To Reproduce**

To reproduce the behavior:
1. Enable Locale and Content translation, add at least 1 additional language
2. Enable translation on pages
3. Create a page.
4. Translate that page into the second language, save, and copy the path.
5. Edit the translated page again, and link text in the body field to the path that was copied (yes this is the same page, but my use-case is for text that will appear in a teaser only on another page)

**Actual behavior**

`The URL ABCDE is not valid`

**Expected behavior**

This link should be valid.

**Related issues**

* https://github.com/backdrop/backdrop-issues/issues/4855

**Comment by indigoxela** [comment]
@jenlampton I haven't been able yet to reproduce the problem you describe (link from a page to its translation). It works here - not sure yet, what I'm missing.

But:

The concept of the core link dialog does have issues. Compared to the ckeditor_link module in D7 (which uses a filter) it's error prone and can be pretty confusing for users.

Additional multilingual example:

- Set up a site with at least two languages, make sure, both languages use a prefix (en/de)
- Set the page content type to be translatable
- Create a page and translate it
- Make sure, the current interface language is *not* the default language
- Create a post and try to link to the page (using autocomplete) in the non-default language (de)

Autocomplete will work fine, validation succeeds, but the link inserted is an invalid one - leading to 404 for both pages, as the prefix is missing.

**Comment by jenlampton** [comment]
@indigoxela I went back and looked at the ticket my client made for me, and I can reproduce the problem when adding a link to the current translated page. (I've updated the STR, above)

![Uploading Screen Shot 2021-01-27 at 11.23.15 PM.png…]()

**Comment by indigoxela** [comment]
Now I get it! That's yet another (existing) issue: https://github.com/backdrop/backdrop-issues/issues/4630

The trick in this case is: turn on transliteration. :wink:

**Comment by jenlampton** [comment]
So, maybe this issue is a duplicate?

**Comment by indigoxela** [comment]
> So, maybe this issue is a duplicate?

Seems to be - looking at the title and issue description. The problem with 404 on "valid" paths should probably be an new issue then.
