### ISSUE TITLE
1.18.1 release does not need to run update script as stated

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#4918]
This latest release (https://github.com/backdrop/backdrop/releases/tag/1.18.1) doesn't need to run update script as stated.

**Comment by klonos** [comment]
Pinging @jenlampton @BWPanda @herbdool as I don't have permission to edit releases.

**Comment by herbdool** [comment]
I updated the release text in GitHub.

**Comment by BWPanda** [comment]
Normally @jenlampton adds that text for a reason. Are you sure there aren't situations in which an update *is* necessary...?

**Comment by jenlampton** [comment]
Yeah, I added the text becauee I saw two new update hooks in the bug-fixes from yesterday, but when I was updating all the b.org sites I wasn't prompted to update.

**Comment by indigoxela** [comment]
@quicksketch moved the PRs that have update hooks to the next milestone by intention - to avoid the need to run updates in a security release. So @robertgarrigos is right, no need to run updates for 1.18.1.
