### ISSUE TITLE
Error site under maintenance in my website "Backdrop CMS"

### ISSUE THREAD

**Issue by AlejandroSQ** [backdrop/backdrop-issues#4930]
Hi, use the CMS "background CMS". I have encountered a problem in the administration of my site because I cannot due to the maintenance of my site.

I would like if someone could give a resolution about the error.

Thanks

![image](https://user-images.githubusercontent.com/78305259/106384959-fa141e00-63cd-11eb-8554-a42ba12b71f7.png)

**Comment by indigoxela** [comment]
Hi @AlejandroSQ,

your site is in maintenance mode, which means that only people with proper permissions can login. That's for instance the first user created, when installing Backdrop CMS (*not* background CMS :smile:)

If you have username and password of that admin user, go to /user/login and ... login.
You can then turn off the maintenance mode. Go to admin/config/development/maintenance and uncheck that setting. Save, and you're done.

I'd also like to recommend our forum for questions like that. Do you already have an account there? https://forum.backdropcms.org/forum

**Comment by klonos** [comment]
May I add that there is an existing post in the forum about this problem: https://forum.backdropcms.org/forum/stuck-maintenance-mode

**Comment by BWPanda** [comment]
Closing as duplicate of forum post and lack of response from OP.
