### ISSUE TITLE
Incorrect use of `config_get` in `node.api.php` file 

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4935]
**Description of the bug**

[Line 862](https://github.com/backdrop/backdrop/blob/ac819913fdb7aadcec9c7579fd33920327526792/core/modules/node/node.api.php#L862) in `node.api.php` file should be changed to `$config = config('my_module.settings');`, because further use of `$config->get` in the function expects `$config` to be an object containing all $option settings in the same configuration file.

At the present, the whole functions looks like:

```php
function hook_ranking() {
  // If voting is disabled, we can avoid returning the array, no hard feelings.
  $config = config_get('my_module.settings');
  if ($config->get('vote_node_enabled')) {
    return array(
      'vote_average' => array(
        'title' => t('Average vote'),
        // Note that we use i.sid, the search index's search item id, rather than
        // n.nid.
        'join' => array(
          'type' => 'LEFT',
          'table' => 'vote_node_data',
          'alias' => 'vote_node_data',
          'on' => 'vote_node_data.nid = i.sid',
        ),
        // The highest possible score should be 1, and the lowest possible score,
        // always 0, should be 0.
        'score' => 'vote_node_data.average / CAST(%f AS DECIMAL)',
        // Pass in the highest possible voting score as a decimal argument.
        'arguments' => array($config->get('vote_score_max')),
      ),
    );
  }
}
```

I will be fixing this minor bug as part a larger PR that addresses multiple other issues soon.

**Comment by indigoxela** [comment]
@alanmels many thanks for your PR. :+1:  Yes, the api example is misleading and should get fixed. Regarding the other changes - your PR still needs some work, many tests are currently failing. I set the issue labels accordingly.

**Comment by alanmels** [comment]
Only after several attempts the https://github.com/backdrop/backdrop/pull/3525 with just a tiny change finally passed all checks.

**Comment by klonos** [comment]
Thanks @alanmels 🙏 ...yeah, ZenCI can be like that some times (quite often really).

Anyway, this is a tiny change in the API docs, and it makes sense (plus tests are not randomly failing now). RTBC 👍

**Comment by BWPanda** [comment]
Thanks @alanmels for finding and fixing this typo! Thanks also to @klonos and @indigoxela for reviewing. I've merged https://github.com/backdrop/backdrop/pull/3525 into 1.x and 1.18.x.
