### ISSUE TITLE
Replace multiple occurences of `config_get()` in the same core functions with `$config->get` implementation

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4936]
**Description of the bug**

As I mentioned in https://github.com/backdrop/backdrop-issues/issues/4664:

> I haven't analyzed other files, so there could be some other cases of mixed use of two methods in the same core functions. The above case is just what I've noticed in the system.admin.inc while working on something else, so I've decided to create a standalone issue for this particular file (system.admin.inc) only.

Checking other core files revealed plenty use of `config_get()` within the same functions, that is not ideal, because per https://docs.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/config_get/1 the function:

```
function config_get($config_file, $option = NULL) {
  $config = config($config_file);
  return $config->get($option);
}
```

already reads the configuration file with `config()`, so there is no need to do it again.

**Additional information**

I've left all the instances of `config_get()` in mutually exclusive condition checks like:

```
function date_default_timezone($check_user = TRUE) {
  global $user;
  if ($check_user && config_get('system.date','user_configurable_timezones') && !empty($user->timezone)) {
    return $user->timezone;
  }
  else {
    $default = config_get('system.date','default_timezone');
    return empty($default) ? 'UTC' : $default;
  }
}
```

because thanks to `if else` it's always one configuration read. 

At the same time, wherever there is potentially two ore more reads, I've replaced with the recommended on https://docs.backdropcms.org/change-records/variableget-variableset-and-variabledel-deprecated-cmi method:

> Every time you call config_get() or config_set(), it hits the disk to read/write the file. If you're doing a lot of reads or writes, it's better to do all the reads at once and all the writes at once like this:
> 
> ```
> $config = config('mymodule.settings');
> $value = $config->get('foo');
> ```

**Comment by klonos** [comment]
Thanks for working on this @alanmels ...there are currently 100s of test failures in the PR. Can you please fix those?

**Comment by indigoxela** [comment]
> there are currently 100s of test failures in the PR

@klonos that's why I set the label to "pr - needs work". And now set it back to that. :wink: We're far from "needs testing".

**Comment by indigoxela** [comment]
> that's why I set the label to "pr - needs work"

Oops, no, that was the other PR. :laughing: @alanmels opened two issues for one PR. - confused again...

**Comment by indigoxela** [comment]
@alanmels at least for me it is very confusing, when you combine one PR for multiple issues. I wonder if it were possible for you, to separate the PR according to the issues - one PR per issue. That makes it less confusing and the review process a lot easier.

**Comment by alanmels** [comment]
My bad that I thought the other one (https://github.com/backdrop/backdrop-issues/issues/4935) was too minor to have it's own PR. I'll fix this today.

**Comment by alanmels** [comment]
> Thanks for working on this @alanmels ...there are currently 100s of test failures in the PR. Can you please fix those?

I really don't know how to get them fixed. Tried to close and re-open PR several times, however it always fails to pas PHP tests https://zen.ci/backdrop/backdrop/test/test-php70-backdrop_backdrop_3522-fc5608e-2

**Comment by indigoxela** [comment]
> My bad that I thought the other one was too minor to have it's own PR.

Baby steps... :wink: A one-liner is easer to review and will get into core faster, than a change in 34 files.

> there are currently 100s of test failures ... Any recommendations?

Just an obvious one: Walk through all the failures, and fix them.

For instance: `Undefined variable: site_config` and `Call to a member function get() on null`.
It seems, in some functions the config isn't loaded yet (missing `$site_config = config('system.core');`). Changing 34 files at once is ambitious. :wink:

**Comment by alanmels** [comment]
Then maybe I should divide this one into separate PRs per changed file?

**Comment by indigoxela** [comment]
> Then maybe I should divide this one into separate PRs per changed file?

Not necessarily. That would result in 34 PRs - uh-oh :laughing: Maybe divide by directory or module? It's up to you.

**Comment by alanmels** [comment]
Finally all checks have passed https://github.com/backdrop/backdrop/pull/3522 Please take another look. Thanks.

**Comment by alanmels** [comment]
I don't know why, but this kind of changes https://github.com/backdrop/backdrop/pull/3522/commits/ff82f8c424568f4b35747a4f06c731568454338f didn't want to pass the checks.

**Comment by indigoxela** [comment]
> Finally all checks have passed

Woot! :tada: 

> I don't know why, but this kind of changes... didn't want to pass the checks.

Probably because the value of that config item changes within the test, so the initial value from $search_settings_config is outdated later on?

The change is a bit bigger (27 files), so it might take some time to review (and some cups of coffee... :smirk: )

**Comment by klonos** [comment]
Thanks @alanmels ...I really like the cleanup in this PR 👍

I did a quick pass, and could only spot one minor thing + had a small suggestion (which might be out of scope for this PR); otherwise RTBC from me.

Since as @indigoxela mentioned, this change spans across many files, I'll leave it for a second person to cast their 👀 on the PR and mark this issue RTBC. The fact that tests now pass gives me more confidence that the changes are safe 👍

**Comment by alanmels** [comment]
Thank you, guys, for your inputs. @klonos I've left some comments on the PR page, please review them. Thanks!

**Comment by indigoxela** [comment]
@alanmels Many thanks again, that you dig into this.

I also left some comments with suggestions. (Off topic: dammit, Backdrop *does* have looong forms :joy:)

**Comment by alanmels** [comment]
@indigoxela, thanks for your recommendations. I've made changes, so please review once again.
(Off topic: the one you referenced was indeed really long function.)

**Comment by indigoxela** [comment]
I did a finale review, many thanks @alanmels for updating the PR. :+1:  It's now RTBC!

**Comment by quicksketch** [comment]
I did another review and it all looks good to me. I merged https://github.com/backdrop/backdrop/pull/3522 into 1.x and 1.18.x. Perhaps this wasn't exactly a "bug fix", but I merged it based on the current milestone. It could result in some minor performance improvement.

Thanks @alanmels, @indigoxela, and @klonos for your work on all this clean-up!
