### ISSUE TITLE
Fix multiple argument behavior for search terms

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#4938]
**Description of the bug**

I have set up a view with a context search filter (search terms). So putting just 1 keyword as argument, the view gives me results. But if there are more words, there are always no results.

This problem was seen on backdropcms.org, and is a duplicate of [a drupal.org issue](https://www.drupal.org/node/1615438).

**Steps To Reproduce**

To reproduce the behavior:
1. Create a view
2. Add an exposed filter for search
3. Create nodes with multiple words in the title
4. Search for those nodes by adding all words from the title in the exposed filter of the view.

**Actual behavior**

NO results.

**Expected behavior**

Results.

**Comment by BWPanda** [comment]
Code looks good to me, and I tested by using the Module search on B.org (where @jenlampton said she'd already pushed the fix).

**Comment by herbdool** [comment]
I checked code and compared to Drupal patch which was accepted there. Looks good.

**Comment by quicksketch** [comment]
Thanks! I merged https://github.com/backdrop/backdrop/pull/3526 into 1.x and 1.18.x.
