### ISSUE TITLE
Fix tiny typo in core/modules/file/file.file.inc file description.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4939]
```php
/**
 * @file
 * File hooks implemented by the Fil module.
 */
```

Fil -> File 😄

**Comment by indigoxela** [comment]
Congratulation, this must be the smallest change ever done in a PR. :rofl:

**Comment by BWPanda** [comment]
Rtbc from me too. Its not a bug though. Documentation or task. Can still go into a bug fix release as one of those.

**Comment by indigoxela** [comment]
> Rtbc from me too. Its not a bug though. Documentation or task.

"Task" seem appropriate for such a tiny fix.

**Comment by klonos** [comment]
...now it also sounds like a task 😉

**Comment by BWPanda** [comment]
Thanks @klonos & @indigoxela. I've merged https://github.com/backdrop/backdrop/pull/3528 into 1.x and 1.18.x.
