### ISSUE TITLE
[UX] Re-organize modules into more useful groupings on the modules page

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#494]
Since we don't have time to replace packages with something more useful for 1.x, the goal here is to split all the core modules into useful groupings that contrib can follow.

Here's a first pass at a re-organization:
![40026daa-871a-11e4-8b5d-1443619439d9](https://cloud.githubusercontent.com/assets/397895/5521748/4afd90e0-895e-11e4-8113-da136f791e04.png)
This issue was split off from https://github.com/backdrop/backdrop-issues/issues/37 .

**Comment by jenlampton** [comment]
I also like the win/win case #3 stated above, and will continue to move forward on this PR.  I'll remove the "User Interface" grouping and put Views UI and Field UI back with their respective parts.

I also agree that the most common use case for visiting the modules page is to turn something *new* on. I pushed for adding a new item to the top of the list in D8, and would love to see that here as well. See https://github.com/backdrop/backdrop-issues/issues/532 as another follow up.

**Comment by jenlampton** [comment]
Pushed a new version of my PR: https://github.com/backdrop/backdrop/pull/607

**Comment by BWPanda** [comment]
> I'll remove the "User Interface" grouping...

Is this just for core modules, or will this affect contrib too? (As mentioned above, my Simplify module adds itself to the 'User interface' group).

On that note, will there be a place where all the (recommended) groups are listed (similar to Drupal's [Package names for contributed modules](https://groups.drupal.org/node/97054))?

**Comment by jenlampton** [comment]
Contrib modules will still be able to add their own groupings same as always :)

**Comment by BWPanda** [comment]
Added my thoughts here https://github.com/backdrop-ops/backdropcms.org/issues/26#issuecomment-68513901 with a suggestion for putting this on the API site.

**Comment by quicksketch** [comment]
I've merged in Jen's PR from https://github.com/backdrop/backdrop/pull/607 to get this started (along with @BWPanda's consistent column width fix). I removed the "core-" prefix after consulting with Jen, as there's an alternative to that at https://github.com/backdrop/backdrop-issues/issues/498.

**Comment by jenlampton** [comment]
Nice :)

**Comment by klonos** [comment]
Indeed! Sooo much better now.
