### ISSUE TITLE
Variable typo in path.module

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4944]
**Description of the bug**

There is a typo in a variable name in the `path.module` file, function `path_get_info()`:
https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.module#L590-L611

The line `if (!isset($info)) {` should actually be `if (!isset($all_info)) {`

----

PR: https://github.com/backdrop/backdrop/pull/3529

**Comment by indigoxela** [comment]
> The line if (!isset($info)) { should actually be if (!isset($all_info))

@laryn many thanks for your PR. There's nothing broken per se, but the static cache wouldn't work as expected, as the condition is never true.

There are 6 calls to path_get_info() in core, but I wasn't able to find a place, where backdrop_static() would actually catch multiple calls per page call. However, the change is obviously correct.

**Comment by klonos** [comment]
Yeah, I agree with @indigoxela ...pretty obvious fix, but I don't know how to test it 😅

**Comment by BWPanda** [comment]
Thanks @laryn for the report and PR! Thanks to @indigoxela and @klonos for reviews as well. I've merged https://github.com/backdrop/backdrop/pull/3529 into 1.x and 1.18.x.
