### ISSUE TITLE
url alias not available in forum edit page

### ISSUE THREAD

**Issue by cptX** [backdrop/backdrop-issues#4948]
**Description of the need**
In Drupal 9 in every forum edit page there is a URL alias field. (Although, the default core forum module has a bug on this in D9, after patching I was able to use it successfully.) In Backdrop though there is no such field at all. How can I set a manual url alias for a specific forum?
This is not to be confused with the aliases for the corresponding taxonomies. Taxonomies have url alias fields but if you go to that url you don't get the forum page but the taxonomy page.

Also, I'm not talking about the forum topic but the forum page, the page that hosts the topics! So let's say I have a forum with the following structure:

forum > english > electric-cars > batteries > topic-1

Currently in order to produce the path for the "batteries" forum page there is no way except going to /admin/config/urls/path and manually setting them, which of course is not a good method. What drupal 9 now has is a url alias field inside the forum page where you can set the custom url. This is missing from Backdrop

![drupal9_forum_alias](https://user-images.githubusercontent.com/9040042/108032386-10131700-703b-11eb-9495-dd287c00e762.png)

**Comment by indigoxela** [comment]
Just spitballing - it might be more motivating for the Backdrop community, if you wouldn't start your issues with "In Drupal 9...". :smirk:

Now for the feature request: the Forum module isn't in core anymore, so I'm not sure, if the core issue queue is the right place for it.
Is there a special reason, why you decided to close the contrib issue and opened a core issue?

**Comment by cptX** [comment]
First of all, Backdrop is a fork of Drupal, fine I like this fact and I'm with it. But forking doesn't mean we shouldn't follow the progress Drupal is doing in some fields? I believe referring to Drupal is OK, and many other modules state this clearly when they are ported from Drupal.
Regarding closing the first issue, as I'm really new to Backdrop I'm not sure where to post what. Another member suggested me to place issues in backdrop-issues and started doing so. Please if you can explain better where I should post what please tell

**Comment by olafgrabienski** [comment]
> Regarding closing the first issue, as I'm really new to Backdrop I'm not sure where to post what.

> I didn't think that the forum is a contrib module.

@cptX The Forum module was removed from Backdrop core in https://github.com/backdrop/backdrop-issues/issues/16. I know it can be hard to find the right places to post something in Backdrop. There is certainly https://github.com/backdrop/backdrop-issues for all Backdrop core issues. In your case, I guess https://github.com/backdrop-contrib/forum/issues (as part of https://github.com/backdrop-contrib) is the place to go.

Actually, there are some more places, e.g. various queues for 'operational' issues. Which can indeed be misleading when you see another "Forum" queue at https://github.com/backdrop-ops/forum.backdropcms.org. However, this one isn't about the Forum module but the Backdrop Forum site.

PS: Feel free to also join the Backdrop Live chat on https://backdrop.zulipchat.com, often it's easier to ask a quick question there.

**Comment by klonos** [comment]
> ...you wouldn't start your issues with "In Drupal 9...". 😏

I don't agree with that @indigoxela 🙂 ...we already have a special `[D8]` "tag" for our issues. See https://backdropcms.org/core-issue-queue#issue-titles

> - [D8] = Drupal 8 feature parity. This issue is for a feature similar to something already included in Drupal 8.

It is my understanding that we do strive for as much feature parity with Drupal as possible/applicable. The main reason for this being to make it easier for people that are considering Backdrop vs D8/D9 to make the move, without feeling that they will be missing out on features they need (or want).

Still @cptX, as the others stated here, this issue queue is about Backdrop core, and since the Forum module has been removed from core and move to contrib-land, I think that it's best to close this request here, and move it to https://github.com/backdrop-contrib/forum/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by cptX** [comment]
First of all, I want to thank you all guys that you are here, reading and responding so fast. In Drupal forums I had really bad experience recently with some major even critical issues where there is no response for months, so I'm really happy to be here with you. Keep up the good work!
@klonos Thank you for clarifying the official freedom to refer to Drupal, it makes absolute sense to me and probably my issue here should have this tag in the title.
Regarding if here is the correct place to post my issue, honestly I still have doubts that this issue doesn't stem from the core, as normally in drupal the alias are generated from pathauto which now is in Backdrop core. If someone can prove with certainty that this issue comes exclusively from the forum module I'll delete it from here and move it to the corresponding forum module thread.
Also, just to give a hint, in D9 (never checked in D7) in pathauto you can select to which content types you can have alias, so again this shows that could be an issue of the backdrop core alias system.

**Comment by klonos** [comment]
> ...in D9 (never checked in D7) in pathauto you can select to which content types you can have alias...

It's the same for all content types in D7 and in Backdrop; but forums are **NOT** a content type (forum topics **ARE**, and there's no problem with being able to specify a URL alias for those). I believe that the forum and forum container URLs in the Backdrop version of the Forum module are controlled via the respective vocabularies. Have you checked `admin/config/urls/path/patterns` @cptX? This is what I see:

![screencapture-4948-lndo-site-admin-config-urls-path-patterns-2021-02-17-04_25_49](https://user-images.githubusercontent.com/2423362/108147894-63877280-70d8-11eb-96ce-0272362ec2e2.png)

Can you please try specifying a path pattern for the Forums vocabularies, and see if that works as expected? If it does, then all we'd need to do is to expose that field in the forum edit form, same as we are doing for other URL path pattern fields, for better UX (not a core issue though).

Bonus: not sure if you are using those, but the same path pattern should also work for forum containers. This is from D7 + Pathauto module:

![image](https://user-images.githubusercontent.com/2423362/108148141-e27cab00-70d8-11eb-8ce3-ef1d96a97599.png)

...so can you please also test forum containers and report back?

If this does not work, then I believe that the Forum module should implement a custom `hook_path_info()`, which seems to be the respective of `hook_pathauto()` ...also NOT a core issue though, but here's the implementation in the 7.x version of the module: https://git.drupalcode.org/project/pathauto/-/blob/7.x-1.x/pathauto.module#L975

I hope that this helps clarify things.

**Comment by cptX** [comment]
@klonos there are several issues with forums and I raise your attention not to mix them / confuse them. Unfortunately you are confusing them here and this could lead to misunderstanding.
In this thread I'm referring exclusively to the fact that the forum page has no "Generate automatic URL alias" checkbox and no "Url Alias" field which drupal 8/9 have. By having them missing you cannot define a manual url for a forum page. So I'm not talking about patterns at all here!!!!!
Also, this is not to be confused with the lack of forum tokens which I have openned in another thread.
Moreover, I see that you are confusing the forum pages with the pages of their corresponding taxonomies. It is a great unfortune in Drupal that the forum pages are having corresponding taxonomies. First of all this creates a mess in understanding and secondly if you visit the url you define in the taxonomy section you don't end in the forum page but in the corresponding taxonomy page which is completely different. A forum page hosts the topics and presents them in a table format. A corresponding taxonomy page justs lists forum topics without any format. I'm again repeating this is a great misfortune for forums in Drupal as by involving taxonomy you create a huge mess with multiple paths and different things, that's why in another issue I have suggested creating forums as content types independently of the taxonomy.
I would suggest you to install forum module and try playing with it, then you will see that the field you suggested above has nothing to do with it. The first image in the beggining of this issue is from Drupal 9 forum edit page where the "Generate automatic URL alias" checkbox and the "Url Alias" field exist. In Backdrop they don't exist at all.

**Comment by klonos** [comment]
Sorry @cptX, I haven't used the Forum module extensively, so yeah, I seem to have some misconceptions around how it works.

> The first image in the beggining of this issue is from Drupal 9 forum edit page where the "Generate automatic URL alias" checkbox and the "Url Alias" field exist. In Backdrop they don't exist at all.

Yup, I got that 👍 

> After clarifying the above are we sure this is a forum module issue?

Yes, I still think so, but I'll let others chime in. Perhaps @docwilmot who is listed as the contrib Forum module maintainer has more insight re this.

**Comment by indigoxela** [comment]
See this [related issue](https://github.com/backdrop/backdrop-issues/issues/4951) for some explanation.

The form ships with contrib, so the form item has be get provided by the module, core can't do it.

**Comment by cptX** [comment]
Reopened the issue here where it better belongs https://github.com/backdrop-contrib/forum/issues/31
