### ISSUE TITLE
Forum Pages have no pattern field in URL aliases

### ISSUE THREAD

**Issue by cptX** [backdrop/backdrop-issues#4951]
**Description of the bug**
Forum pages (like /forum/id) have no pattern field in URL aliases.
URL aliases provide a field for **forum topics** and a field for **forum taxonomies** but there is no field for **forum pages**.
This makes it impossible to define a Url alias pattern for the forum pages (the hosts of the forum topics presented in a table).
This problem together with the other problem described here https://github.com/backdrop/backdrop-issues/issues/4948 block the user for having any chance of defining (manually or by pattern) a url alias for a forum page (/forum/id).

**Steps To Reproduce**
Go to admin/config/urls/path/patterns and you will see that there is no field for forum pages. Only forum topics and forum taxonomies fields exist.

![image](https://user-images.githubusercontent.com/9040042/108212592-bdb72080-7136-11eb-935e-7f3c54a16d72.png)

**Expected behavior**
Drupal 8/9 have this field available. Please check the screenshots:

![image](https://user-images.githubusercontent.com/9040042/108212740-eb9c6500-7136-11eb-9132-0493ff15280a.png)
![image](https://user-images.githubusercontent.com/9040042/108212785-f5be6380-7136-11eb-83a8-dd15e17bbb3b.png)
![image](https://user-images.githubusercontent.com/9040042/108212859-0ff84180-7137-11eb-883d-a77cdac0195c.png)

As you see D8/9 differentiate the forum pages from the taxonomy forum vocabulary pages...

This should be included in Backdrop. At the moment I'm trying to fix my forum pages paths and it's impossible. I have managed to fix the forum topics paths by using the Entity Tokens module, but still it's impossible to define (manually or by pattern) any path for the forum pages

**Comment by indigoxela** [comment]
Hi again, @cptX,

It is possible to create these aliases, here the steps to create an alias for the Forum (table) page:

- Go to admin/config/urls/path
- Click on "Add URL alias"
- Enter your values in the form (see screenshot below) and save
- Go to your new alias (in my example it's "/mygeneralforumpage")
- See the Forum page alias in action :smiley:

_But there's one important note:_ The Forum module is **contrib**, it's not in core anymore, so you should create an issue in the [right issue queue](https://github.com/backdrop-contrib/forum/issues)
Core can't do it, the module has to implement the additional form item in function forum_form_forum() - that form ships with the module, not with core.

Screenshot:
![forum-alias](https://user-images.githubusercontent.com/842066/108217136-8bf08a80-7133-11eb-88c7-3c263ccd137a.png)

**Comment by cptX** [comment]
@indigoxela let's not confuse the fact that the url alias field is missing from the forum edit page with the other fact that is missing also from the pattern alias configuration. These are two different issues.
Regarding the manual setting of the url alias of a forum page  I know I can do it manually from the admin/config/urls/path/add, but this is not intuitive compared with the possibility to set it directly inside the forum edit page.

Regarding the above issues I'm going to open them in here https://github.com/backdrop-contrib/forum/issues and then close them here. Thanks

**Comment by cptX** [comment]
Openned here where it should be https://github.com/backdrop-contrib/forum/issues/37
Closing this issue
