### ISSUE TITLE
Remove backdropGetToken() from file.test

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4954]
[`file.test`](https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/tests/file.test) overrides the [`backdropGetToken()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21simpletest%21backdrop_web_test_case.php/function/BackdropWebTestCase%3A%3AbackdropGetToken/1) function with its own version because, in Drupal, the core function didn't allow for hash salts (see https://www.drupal.org/node/1555862). However in Backdrop our core function does allow for that, so we should remove the overridden function now.

```php
/**
 * Overrides BackdropWebTestCase::backdropGetToken() to support the hash salt.
 *
 * @todo Remove when http://backdrop.org/node/1555862 is fixed in core.
 */
protected function backdropGetToken($value = '') {
  $private_key = backdrop_get_private_key();
  return backdrop_hmac_base64($value, $this->session_id . $private_key . backdrop_get_hash_salt());
}
```

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/3530

Wonder if it'll "just work"...

**Comment by indigoxela** [comment]
@BWPanda nice catch, right, that's in core since [this commit for B 1.6.0](https://github.com/backdrop/backdrop/commit/b780466c45ff65ec7ef63845cf6a8ba891b441aa), time to clean up.

> Wonder if it'll "just work"...

Apparently it did - besides the unrelated request timeout.

**Comment by quicksketch** [comment]
Looks good to me, nice one @BWPanda! I had to merge with `1.x` to fix a conflict, but assuming tests pass still, https://github.com/backdrop/backdrop/pull/3530/ is good to go.
