### ISSUE TITLE
Config translation always adds new entries with same context to locale tables instead of updating

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4955]
**Description of the bug**

Config translatables work with locale(), they allow translation of strings from config files, using a translation context.
However, entries with these contexts are never updated on follow-up edits, new entries get added every time.

**Steps To Reproduce**

1. Enable language and locale modules
2. Go to admin/config/system/site-information and configure the site name
3. Check the database entries with the query below (phpmyadmin, or shell)
4. Change the site name again
5. Check the database entries with the query below
6. ...

```
SELECT * FROM `locales_source` WHERE `context` = 'config:system.core:site_name' 
```

**Actual behavior**

Every time you change the config item, a **new** entry in the database table gets created - with the exact same translation context.

**Expected behavior**

If the translation context is identical, the existing database record should get updated.

Note that 'config:system.core:site_name' is just an example, the problem occurs with all config translations. I discovered that behavior with a custom one in a contrib module.

**Additional information**

- Backdrop CMS version: 1.18.1
- Database version: MariaDB 10.3.27

The problem is sort of hidden, because the locale search page (admin/config/regional/translate/translate) has no filter on context, that's why an sql query is necessary to verify.

**Comment by indigoxela** [comment]
Just to verify I played with "normal" t() function usage.

I added something like that: `t('This is a string with context - 1', array(), array('context' => 'my-custom-custom-context'));` to a template.
Then changed the string, but not the context ("This is a string with context - 2"), and so on, calling the page every time after text changes. Every time a new entry has been created. Same context, new entry (lid).

Maybe I totally misunderstand something, but isn't that a concept problem? Normally, when providing t() via code, not so many new strings get added to locales_source. But with config translation, the situation is a bit different. It's more likely, that a text changes more often. Every tiny typo fix will create a new row in locales_source table.

**Comment by herbdool** [comment]
Does it pick the right translation? I'm not clear on how it's supposed to work. Does it pick the highest id for the translation with the same context, or is that part messed up because it's expecting only one row per context?

**Comment by indigoxela** [comment]
> Does it pick the right translation? I'm not clear on how it's supposed to work. Does it pick the highest id for the translation with the same context,...

As far as I can tell, it picks the right translation. Maybe it just was a misconception on my side. I thought that the context should get updated, but that never happens.

The search key seems to be source (stripped to 30 chars) + context, the context is not supposed to be unique - that's what baffled me.

**Comment by herbdool** [comment]
I think context isn't used much outside of config translation, if I recall correctly. We had decided that we would put the config key into the context so we could know exactly which key the translation refers to. I hadn't thought about how the translations get updated, but I can confirm too that the primary key is a combination of the source and context.

Since this seems to work by design can we close this? And, if you like, create a new issue to change this behaviour if you can think of a better way to do this (while also being backwards compatible)?

**Comment by indigoxela** [comment]
> I think context isn't used much outside of config translation

I don't fully agree on that, translation contexts are useful to prevent translation overlap - which is useful without config, too. But that's a bit off-topic here.

Yes, I think we can close this issue. I still see it as a (sort of) problem of the base concept of config translation, resulting in useless database entries, cluttering the locales_* tables, but it doesn't seem to do any harm besides that.
