### ISSUE TITLE
[UX][UI] Systematically add a mechanism for HTML5 Placeholders

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#4956]
**META**
[[META] Placeholders #4958](https://github.com/backdrop/backdrop-issues/issues/4958)

**Description of the need**

Placeholders were added into the HTML5 spec as a way to add custom labels in the text and textarea input fields for cleaner UI and better UX.

Drupal 7 was never updated to be compliant with HTML5 standards and as a result, these types of things have to slowly be added to backdrop.

On D7, contrib had to make up for the lack of this in core through contrib. Backdrop should handle these scenarios and allow contrib to tie into it.

**Proposed solution**

I'm not sure what the best approach is for the solution so this will need discussion.

Option 1) Do we add a placeholder input field alongside the label input field?

Option 2) Do we simply add a common CSS selector to core and allow the respective theme itself to be responsible for adding that selector?

Option 3) Do we add a hybrid of both option 1 and 2 which will allow some forms to have a hard-coded placeholder like image title and alt-text fields yet other forms like views exposed filters to allow a choice of using a standard label or placeholder label or both?

**Alternatives that have been considered**

D7 has a few workaround modules for this very purpose:

https://www.drupal.org/project/form_placeholder
https://www.drupal.org/project/placeholder

**Additional information**
N/A

**Draft of feature description for Press Release (1 paragraph at most)**

Backdrop now fully supports HTML5 placeholders for input fields on both the backend admin areas and front-end themes.

**Comment by jenlampton** [comment]
Placeholders have issues with accessibility, and will not be any use to describe the field once it already contains a value. This would be a prettier solution for sighted users, but a UX regression for all users.

For those who prefer placeholders, contrib is a great place to find solutions. Let's port drupal.org/project/placeholder and drupal.org/project/form_placeholder so that people can continue to use them, but let's not consider this in core.

**Comment by jenlampton** [comment]
I'm closing this issue as "works as designed" for now, but if others stumble across this later and want to weigh in, please feel free to re-open.

**Comment by philsward** [comment]
That's fine. I agree
With not adding additional complication.

The one possible suggestion would be to add a checkbox where a form field can be togged between the label and placeholder for cleaner UI. The downside is that labels are supposed to be like descriptions and placeholders are supposed to be hints according to the "standards". Personally I think this should be left up to the site maintainer.

Otherwise leaving this closed.
