### ISSUE TITLE
[UX][UI] Move File Display Title Label into Input as HTML5 Placeholder

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#4959]
**Blocking Request**
https://github.com/backdrop/backdrop-issues/issues/4956

**Description of the need**
Labels take up space and with HTML5, this same information can be added into input text/textarea fields as placeholders

**Proposed solution**

Create a cleaner UI and better UX by moving the file description label into the input field as a placeholder. This reduces the overall height of file containers when editing.

**Alternatives that have been considered**

https://www.drupal.org/project/form_placeholder
https://www.drupal.org/project/placeholder

**Additional information**

From
![image](https://user-images.githubusercontent.com/3436110/108564193-59c46180-72c8-11eb-9990-ec2c04934167.png)

To
![image](https://user-images.githubusercontent.com/3436110/108564227-63e66000-72c8-11eb-9755-5cea66b0b9cb.png)

**Draft of feature description for Press Release (1 paragraph at most)**

Backdrop file "File display title" is moved into the input fields as placeholders to make the edit file container smaller and easier to work with.

**Comment by jenlampton** [comment]
Placeholders have issues with accessibility, and will not be any use to describe the field once it already contains a value.

**Comment by jenlampton** [comment]
I'm closing this issue as "works as designed" for now, but if others stumble across this later and want to weigh in, please feel free to re-open.
