### ISSUE TITLE
[UX] Create database at installation time.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#496]
This is the same as https://www.drupal.org/node/203955 created after request by @jenlampton over at #467

It is convinient for developers, who deploy sites on local computers. Usually they open phpMyAdmin to create a database and then they return to the web installer to go on. We can skip this step and provide a way for them to create a db during installation (provided that they have the right privilege to create databases). This way the installation UX is improved:
- shorter installation times
- installation not interrupted by trivial tasks that can be automated or done through the installer UI

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/2126

**Comment by serundeputy** [comment]
hrmm ... i'm just spitballing here, but would that be a security risk as you are creating a DB before there is a user 1; and also user 1 can input DBs through like backup_migrate, but not actually create DBs.

Not sure.

**Comment by quicksketch** [comment]
Yeah, I have my concerns here as well. You shouldn't be setting up a site using an account that can create (and probably drop) databases in the first place. I had considered that maybe this would be okay if we did some basic domain checking. e.g. the domain contained:

- `.local`
- `local.`
- `localhost`
- `dev.`
- `.dev`
- `127.0.0.1`

But this wouldn't be fool-proof. Additionally, it would introduce inconsistent behavior between setting up Backdrop on a localhost and setting up Backdrop on a production host. That sort of "sometimes magic" can cause a lot of confusion.

So while I like the idea and I'd certainly appreciate it in my localhost installations, I'm not sure this an idea we should implement.

**Comment by Dinornis** [comment]
I also vote against this for the security reasons mentioned above.

**Comment by quicksketch** [comment]
On further thought here... I'm not sure my concerns are totally valid. Backdrop already requires all permissions on a database, including the ability to drop tables. If you can drop tables, you can drop the entire database. Similarly, the CREATE permission in MySQL is the same whether you're creating a single table or the entire database. So the permission level needed to create a DB is the same that Backdrop requires anyway.

Many servers or shared hosting accounts only run a single site, or even if they have multiple sites, many users have a single database username for all of them. Automatically creating the database just saves a step. If they are going to use the same username and password, making them do it manually doesn't make things any more secure.

I also thought that eventually https://www.drupal.org/node/203955 would be merged into D7, as it made it into D8 quite a while ago. But seems development there has slowed. I've taken the D7 patch (and the follow-ups noted in the issue) and made a Backdrop port.

**Comment by quicksketch** [comment]
Here are screenshots of the behaviors in action:

- User does not have permission to create a database (same as the current error):
![image](https://user-images.githubusercontent.com/100206/38710284-6b9dae10-3e74-11e8-8cf9-6f1adba85306.png)
- User exists but does not have permission to create the database (or any tables), new error for edge-case handling:
![image](https://user-images.githubusercontent.com/100206/38710263-488f0da6-3e74-11e8-821d-a952242ee966.png)

And in the case the database can be created, no error or message is shown at all. The database is immediately created and then used.

**Comment by serundeputy** [comment]
@quicksketch I put an open question/review on the PR: https://github.com/backdrop/backdrop/pull/2126/files#r182904879

what to do when DB specified in the installer is the same as an existing DB (by accident perhaps).

**Comment by jenlampton** [comment]
> what to do when DB specified in the installer is the same as an existing DB (by accident perhaps).

I don't understand. this is how it works now. If you put in a database that already exists, Backdrop will attempt to connect to it, just like you asked. :)

**Comment by serundeputy** [comment]
Steps using a database that exists that has nothing to do with backdrop:
  * `create database geoffisthebest;`
  * add a table to `geoffisthebest`
  * add some data to the table
  * visit backdrop installer
    * when prompted for the Datbase name use `geoffisthebest`
  * Backdrop installs to `geoffisthebest` leaves your table there with its data
    * not sure if this is good or bad, but could definitely lead to confusion and cruft
  
If you specify a DB that exists that already has Backdrop tables you get:
![screen shot 2018-04-19 at 7 34 32 pm](https://user-images.githubusercontent.com/6763671/39023456-b997708a-4408-11e8-8897-18dd4c3f9d74.png)

but, then if you visit the site there is a config has mismatch:

![screen shot 2018-04-19 at 7 35 31 pm](https://user-images.githubusercontent.com/6763671/39023479-da9d8382-4408-11e8-89da-a12683f552ba.png)


maybe we can add a check in the installer for 

```mysql
create database USERSPECIFIEDVIAINSTALLER  IF NOT EXISTS
```

**Comment by serundeputy** [comment]
I guess this is a `problem` we already have though; nothing to do with this PR.

This PR is checking if it exists, if so go on as usual, which will write to whatever database you told it to that already exists, and if it doesn't exist than it creates it.

So, all the stuff I said above happens with or without this PR ... never mind me ... carry on .... nothing to see here: ⛵️

**Comment by quicksketch** [comment]
Yeah, all of that is an existing issue. I agree though, the config mismatch problem can be annoying. Perhaps we should handle that somehow (automatically make a new config directory if the DB is empty?), but it is a separate issue than this one.

**Comment by quicksketch** [comment]
FYI here's a screenshot of the installer now if the username/password/host is incorrect. We can remove all the messaging about "Does the database exist" because if it doesn't exist we would have created it. Plus the previous error was overwhelming with its suggestions, this pairs it down a bit:

![image](https://user-images.githubusercontent.com/100206/39031192-9b408460-441b-11e8-9287-b1c8ac863c7f.png)

**Comment by serundeputy** [comment]
> Is it a problem that the user can't see the password here?

I don't think it is a problem, but a toggle similar to the user::password field could be added, but I wouldn't hold this up on account of it

**Comment by serundeputy** [comment]
fyi: here is the follow up: https://github.com/backdrop/backdrop-issues/issues/3048
