### ISSUE TITLE
Optimize `path_admin_form()`: Avoid calling `url()` multiple times.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4963]
This came up while reviewing https://github.com/backdrop/backdrop/pull/3522

See https://github.com/backdrop/backdrop/pull/3522#discussion_r578281484

> Here, we could do something like:
>
> ```php
>   $field_prefix = url(NULL, array('absolute' => TRUE)) . ($site_config->get('clean_url') ? '' : '?q=');
> ```
> ...and then reuse:
>
> ```php
>   '#field_prefix' => $field_prefix,
> ```
> 
> It would save us 2 calls to url() 😉 ...but perhaps scope creep for this PR.

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/3533

**Comment by indigoxela** [comment]
@klonos your PR totally makes sense, but as the same lines already change in the related PR, you'll run into a conflict.

I suppose, one of these PRs has to wait for the other one to get merged.

**Comment by klonos** [comment]
> I suppose, one of these PRs has to wait for the other one to get merged.

Yup. I only created this PR because as small a change as this may be, it still was "scope creep" for the other issue/PR. Happy to wait 🙂

**Comment by indigoxela** [comment]
As expected - the other issue got merged, so this one now has conflicts. The PR needs a tiny update.

**Comment by BWPanda** [comment]
I've fixed the merge conflicts in the PR. Ready for review/testing.

**Comment by indigoxela** [comment]
@BWPanda many thanks for updating this mini-improvement. It still works and the code still makes sense. RTBC :+1:

**Comment by quicksketch** [comment]
Thanks folks! I've merged https://github.com/backdrop/backdrop/pull/3533 into 1.x and 1.21.x.
