### ISSUE TITLE
Use already included tableresponsive.js in core themes to hide less important columns?

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4964]
Backdrop core ships with core/misc/tableresponsive.js to hide columns by css classes ".priority-low" and ".priority-medium". That library is loaded, if the table uses one of the responsive css classes.

However, none of the core themes actually uses these classes as intended (no "display: none" for these). The toggle button isn't visible, either, and the strings used for that link are a bit misleading.

My main question: Is this an oversight, or has tableresponsive.js been skipped, potentially deprecated by intention?

Additionally: If we plan to actually _use_ it in a core theme (Seven?), we really should think over the UI, in particular the texts...

- Initially the link has no text at all (so isn't even visible)
- The link has the title attribute set to 'Show table cells that were hidden to make the table fit within a small screen.'
- When using the css classes in a theme, and when toggling, the link text gets set via js, either 'Show all columns' or 'Hide less important columns', which can be sort of contradictory to the title attribute

Because of theses text glitches, it's even hard to make use of tableresponsive.js in custom themes.

Example table that uses the classes (ineffectively, as no theme does anything with them): admin/content (Content overview)

**Comment by BWPanda** [comment]
> Example table that uses the classes (ineffectively, as no theme does anything with them): admin/content (Content overview)

I'm not sure what you mean by this... If I view that page on my phone (portrait mode), then I see columns: Title, Status, Created, Operations. If I turn my phone to landscape mode, I then see the Content Type column added in.

**Comment by indigoxela** [comment]
> If I view that page on my phone (portrait mode)

Interesting, I don't see any difference. At least in desktop browsers, no matter how narrow the viewport is. Neither in Basis nor in Seven. The same when switching the developer tools to use device emulation.

Which theme are you using?

And important: do you ever see the toggle button (link) directly above the table?

**Comment by BWPanda** [comment]
So because I'm on my phone and don't have my testing sandbox available (and didn't want to spin up a B.org demo site just for this), I tested on B.org itself. I believe it just uses the Seven theme.

I've never seen any link to toggle this behaviour...

**Comment by indigoxela** [comment]
What the... :confused:  now it works, columns get hidden as expected. But the button still won't show up.

**Comment by indigoxela** [comment]
Ooops, my bad, Seven *does* use the priority-xxx classes in core/themes/seven/css/style.css. Only Basis doesn't.

The button never shows, no theme takes care of `tableresponsive-toggle`. Anyway, it seems that my question is answered.
