### ISSUE TITLE
The toggle link for responsive tables never shows

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4965]
**Description of the bug**

Responsive tables (core/misc/tableresponsive.js) also ship with a toggle link, but that never shows as it initially has no text, only a title attribute (which is a bit misleading, anyway).

**Steps To Reproduce**

1. Go to admin/content or admin/people
2. Resize the browser window to a very small viewport

**Actual behavior**

The columns get hidden, but the toggle link won't show.
Note that this actually only affects Seven, as Basis has no css rules regarding .priority-low or .priority-medium classes.

**Expected behavior**

The link should show, when something could be hidden.

**Additional information**

- Backdrop CMS version: latest dev
- Browser(s) and their versions: any

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3535) is available for testing and review.

Here a screenshot of the link this issue is about - you've never seen it before, as it had no text set initially.

![toggle-link-visible](https://user-images.githubusercontent.com/842066/108708660-047b9080-7512-11eb-9139-d63436baa2ac.png)

The link text toggles, when columns are hidden/shown, and it's not displayed, when the screen is big enough to not hide columns with classes "priority-low" and "priority-medium".

**Comment by BWPanda** [comment]
Nice!!! PR works and seems like a really useful piece of functionality. Thanks for finding/fixing this @indigoxela!

**Comment by klonos** [comment]
Nice find @indigoxela 👍 ...RTBC.

**Comment by indigoxela** [comment]
Garbage, I just found and fixed a silly typo in the title attribute text (Toogle -> Toggle). No other changes.

**Comment by BWPanda** [comment]
Thanks @indigoxela & @klonos for this! I've merged https://github.com/backdrop/backdrop/pull/3535 into 1.x and 1.18.x.
