### ISSUE TITLE
Fix old browser quirk workaround in Seven theme. Caused new trouble with Firefox

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#4971]
**Description of the bug**

This affects Firefox 86 (not ESR): Fielsets in Seven look weird.

![image](https://user-images.githubusercontent.com/2385329/109384541-a3a0ed80-7941-11eb-9095-b6b81f406ce5.png)

![image](https://user-images.githubusercontent.com/2385329/109384551-b3b8cd00-7941-11eb-95b3-7e29747448aa.png)

**Steps To Reproduce**

1. Go to, for instance, admin/config/people/settings

**Actual behavior**

Fieldsets appear like in "inline" style.

**Additional information**

- Backdrop CMS version: 1.19.x and any before
- Browser(s) and their versions: only Firefox 86+ ?

Here's the FF bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1694729

This is the CSS code: https://github.com/backdrop/backdrop/blob/fc38836bee1e52d247c241e2f384af0e0e67baa6/core/modules/system/css/system.theme.css#L15

Related (very old) issue: https://github.com/backdrop/backdrop-issues/issues/515

**Proposed solution**

Get rid of this workaround - at least, verify if it's still necessary (probably not).

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3548) is available for testing and review.

**How to test**

Only in Seven (core theme). This workaround only ever affected _Firefox_. It's appreciated to test the change in different FF versions. Check pages with fieldsets with different window (viewport) sizes. And also check vertical tabs.

Note that the bottom margin for fieldsets in Firefox ESR (78) is now similar to other browsers. It has been bigger before.

**Comment by BWPanda** [comment]
PR works for me in the Tugboat sandbox (I'm using FF v86).

**Comment by klonos** [comment]
I've tested the following Firefox versions in Mac OS and Windows 10:

![image](https://user-images.githubusercontent.com/2423362/109424713-7e69b900-79ed-11eb-8372-99720db77a72.png)

...and I confirm that the problem exists only in v86-beta. I then tested the PR sandbox in both Mac/Windows10, and confirm that it fixes the issue 👍 

Let me know if anything else needs testing, I have access to a Browserstack account, so can test various combinations of OS/browsers and different versions 😉

**Comment by indigoxela** [comment]
@klonos thank you so much for testing this in various FF versions!

Just to make sure: did you verify that there are no negative side effects for vertical tabs in mobile view (small screens)?

**Comment by klonos** [comment]
I did resize the browser window, but I should really test on actual mobile devices. I'll do some more testing once I get a chance.

**Comment by indigoxela** [comment]
> ...but I should really test on actual mobile devices

As this problem only affects Firefox in the latest version, it might be hard to test on mobile anyway. Actually I think, resizing the window should be sufficient.

But additional testing never hurts. :smile:

**Comment by quicksketch** [comment]
Thanks @indigoxela! I just started seeing this issue in Firefox as well this week. I'll take a look shortly.

**Comment by quicksketch** [comment]
According to the StackOverflow post mentioned in the code comments (https://stackoverflow.com/questions/17408815/fieldset-resizes-wrong-appears-to-have-unremovable-min-width-min-content), this work-around has no longer been necessary since Firefox 53, which was released in April 2017. The StackOverflow post also says the "correct" fix for newer versions is setting a `min-width: 0`, which we are already doing.

So this fix looks good to me. And testing in the latest Firefox it indeed fixes the problem. Thanks @indigoxela!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3548 into 1.x and 1.18.x. Thanksk @indigoxela, @klonos, and @BWPanda!
