### ISSUE TITLE
Improve the documentation for user_save() wrapper function

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4973]
**Description of the bug**

Following the documentation on https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_save/1, I have created a test user object like so:

```
$account = new stdClass();
$account->name = 'Test User';
$account->mail = 'test@example.com';
$account->is_new = TRUE;
```

However attempting to save it with `user_save($account);` produced the following error:

```
Error: Call to undefined method stdClass::save() in user_save() (line 336 of /var/www/docroot/core/modules/user/user.module). 
```

Only following the documentation on https://docs.backdropcms.org/converting-modules-from-drupal:

> **Classed entities**
> 
> Several entities in Backdrop are now classed objects which extend the Entity Class. Users, nodes, comments, files, taxonomy terms and vocabularies have been converted to extend the new base class. Therefore programmatic creation of these objects has changed in Backdrop. For example:
> 
> Old
> 
> ```
> $node = new stdClass();
> $node->type = 'blog';
> $node->title = 'New Title';
> ...
> node_save($node);
> ```
> 
> New
> 
> ```
> $node = entity_create('node', array ('type' => 'blog'));
> $node->uid = $user->uid;
> $node->title = 'New Title';
> $node->save();
> ```

in particular, using this code worked as expected:

```
$extra_edit = array();
$account = entity_create('user', array(
  'name' => 'Test3 User',
  'mail' => 'info3@example.com',
  'roles' => array(
    BACKDROP_AUTHENTICATED_ROLE => 'authenticated',
    3 => 'committer',
  ),
  'pass' => user_password(),
  'status' => 1,
) + $extra_edit);
$account->save();
```

Please someone test and confirm this and I will create PR. Thanks!

**Comment by indigoxela** [comment]
@alanmels I'm not sure yet, what you're after. Is it updating the doc block for user_save()?

User accounts are entities, so you can either:

`$account = entity_create('user', $your_array);`
or alternatively...
`$account = new User($your_array);`

Which docs suggest that it should be a stdClass()? Can't seem to find that, maybe I misunderstand something. :wink: 

The user entity class is defined in core/modules/user/user.entity.inc

**Comment by alanmels** [comment]
I thought the wording of https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_save/1 of suggested to create an object:

> $account: The user object to modify or add. If you want to modify an existing user account, you need to ensure that (a) $account is an object,

**Comment by indigoxela** [comment]
> I thought the wording of ... suggested to create an object:

Agreed, if you misunderstand it, others might, too. That's an unnecessary pitfall. So we probably should explicitly mention that it's about a "User entity"...

PR welcome. :+1:

**Comment by alanmels** [comment]
@indigoxela, should I be modifying just the documentation block text:

> $account: The user object to modify or add. If you want to modify an existing user account, you need to ensure that (a) $account is an object, and (b) you have set $account->uid to the numeric user ID of the user account you wish to modify. If you want to create a new user account, you can set $account->is_new to TRUE or omit the $account->uid field.

emphasizing that function is not for use in custom module to create users and without mentioning `$account = entity_create('user', $your_array);` or `$account = new User($your_array);` or removing misleading references to `object` and suggesting this is about "User entity" would suffice?

To say frankly, I'm not sure what would be the ideal edit. My concern, is that coders who are looking for ways programmatically creating users will end up on that page and try `user_save()` whereas they were supposed to use `entity_create()` instead.

**Comment by indigoxela** [comment]
Uh-oh, wording... :smile: At least we should clearly state that "the object" should be a User entity. Maybe some of the native speakers can help here?

**Comment by alanmels** [comment]
Turns out the text is word to word copy from Drupal 7's user_save() API: https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_save/7.x It is indeed confusing, so the text should totally be updated to reflect the change on https://docs.backdropcms.org/change-records/user-entity-now-classed-object

I will create a PR and who wants to improve the doc block, they can do it while reviewing the PR.

**Comment by alanmels** [comment]
I found this part:

> 
If you want to create a new user account, you can set $account->is_new to TRUE or omit the $account->uid field.

obsolete, so should be deleted.

I'm not sure if code example is allowed in doc block, so please suggest improvements for the new doc block text.

**Comment by indigoxela** [comment]
> I'm not sure if code example is allowed in doc block

Yes, they are - wrap them in `@code` and `@endcode`.

I'm not sure, how detailed the description of entity creation should be in the user_save() docblock. Of course, it should be clear that it's about User entities, but wouldn't a reference (with `@see`) to entity_create() be sufficient?

**Comment by alanmels** [comment]
How about now? I have simplified the whole doc block and per your recommendation referenced the `entity_create()` with `@see`. Also replaced `add` and `modify` to math the order of `new` or `updated` in the starting sentence.

**Comment by indigoxela** [comment]
I've left a comment with a recommendation.

Another thought: would an additional reference to user_load() provide helpful info? What do you think?

**Comment by alanmels** [comment]
Responded on PR page. Thanks!

**Comment by alanmels** [comment]
Thanks for noting about `@param User $account`. I've just made another update to PR.

Now, when we polished it for this specific case, I have a question. I've just searched for `@param $account` and found ton's of occurrences. Do you think we should start fixing them all? Do you want me to create a massive PR?

**Comment by indigoxela** [comment]
@alanmels many thanks for the update, looking good now - RTBC.

> ... found ton's of occurrences. Do you think we should start fixing them all? Do you want me to create a massive PR?

I know, the datatypes are missing in many, many doc blocks (for historical reasons). Adding all at once? You frighten me. :laughing: 

Maybe create a follow-up for the MODULE.api.php files? I'd assume that datatypes are most helpful in api documentation of the (core) modules - at least, for my understanding. Personally, I'd prefer to do it in steps. Smaller PRs are much easier to handle.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3551 into 1.x and 1.18.x. A nice simplification/clarification of our docs.

I'm definitely in favor of updating our docblocks to include more data type hints like we have done here. Drupal 7 largely does not use data type hints at all, and we have been adding them in places as we go. Like @indigoxela suggests though, I would love if these bulk updates were separated into reasonable groupings to keep the PRs from getting too huge.
