### ISSUE TITLE
Empty class attributes added to block markup when setting custom elements but not specifying a class

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#4977]
I noticed this while testing #1818, and have confirmed that it happens on Vanilla Backdrop.

Steps to reproduce (I'm using specific a layout/block here, but same applies to any layout/block):

1. Edit the Home page layout
2. Edit the "Promoted content" block
3. Change the block title to something custom (to ensure that it's being rendered)
3. Expand the "Style settings" fieldset, and change:
   - the "Wrapper tag" to something like a SECTION
   - the "Heading level" to something like a H6
   - the "Content tag" to something like an ASIDE
4. Do NOT specify any classes
5. Save the block and save the layout.
6. Clear caches (just in case)
7. Inspect the generated HTML

## Actual result

The block wrapper already includes some default classes, so you get the following, which is fine 👍 :

```html
<section class="block block-views-promoted-block contextual-links-region">
  ...
</section>
```

Empty `class` attributes are getting added for the block heading and the block content elements though 👎 :

```html
<h6 class="">some title</h6>
<aside class="">
  ...
</aside>
```

## Expected result

No empty `class` attributes added if no classes have been specified, and no default classes exist:

```html
<h6>some title</h6>
<aside>
  ...
</aside>
```

**Comment by klonos** [comment]
...not sure if this is due to missing logic in the Basis theme templates, system//views/block templates, or `backdrop_attributes()`. Best if we solved this in a "global" way though.

**Comment by indigoxela** [comment]
@klonos handling it in backdrop_attributes() doesn't seem appropriate, as that function handles *all* sorts of attributes - even ones that should be rendered when empty. The best place for fixing it is function template_preprocess_block_dynamic(), which currently adds the attribute regardless of existing values - which seems wrong anyway.

A [PR](https://github.com/backdrop/backdrop/pull/3553) is available for testing and review.

**Comment by indigoxela** [comment]
Pinging @klonos to test and review the PR for the problem you reported (empty class attribute).

**Comment by BWPanda** [comment]
Code looks good to me, but PR should be updated to run current test suite.

**Comment by indigoxela** [comment]
> PR should be updated to run current test suite

Definitely, it's been quite a while. :smirk: Rebased.

**Comment by BWPanda** [comment]
Thanks @indigoxela. I've tested and it works as advertised, and the code looks good. So RTBC from me.

**Comment by quicksketch** [comment]
Thanks folks! I've merged https://github.com/backdrop/backdrop/pull/3553 into 1.x and 1.22.x!
