### ISSUE TITLE
Fix syntax error: unexpected '||' (T_BOOLEAN_OR) in user.module

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#4982]
When trying to access a site based on the latest `1.x` code, the following error is displayed:

> ParseError: syntax error, unexpected '||' (T_BOOLEAN_OR) in backdrop_load() (line 3200 of /app/www/core/modules/user/user.module).

![image](https://user-images.githubusercontent.com/2385329/110049025-1b897080-7da5-11eb-850d-a289b7b422f3.png)

This is because of a bug introduced in a [recent commit](https://github.com/backdrop/backdrop/commit/92a755084f50a7ded5d08c67529cc46a86233a8e#diff-90826de90e80df8f9261df0b25b789e77c60673cc1016ccde1ec00bf2f94011bL3198-R3202) - an extra `)` that should have been removed causes the problem. This is the current, buggy code:

```php
if (!$user_email_verification) || $admin) {
```

**Comment by BWPanda** [comment]
Simple PR to fix this: https://github.com/backdrop/backdrop/pull/3554

**Comment by quicksketch** [comment]
Thanks @BWPanda! Merged https://github.com/backdrop/backdrop/pull/3554 into 1.x and 1.18.x
