### ISSUE TITLE
core function transliteration_get() not in global scope

### ISSUE THREAD

**Issue by earlyburg** [backdrop/backdrop-issues#4983]
**Description of the bug**

File /core/includes/transliteraton.inc contains the function transliteration_get() on line 284, which is not in global scope, and therefore not available to contributed modules. 

**Steps To Reproduce**

To reproduce the behavior:
Install Backdrop
enable all the core translation/language modules (content_translation, language, and locale)
Install Devel Module
Execute the following code:

if( function_exists('transliteration_get') ) {
backdrop_set_message('exists');
}else {
backdrop_set_message('nope');
}

if( function_exists('backdrop_build_form') ) {
backdrop_set_message('exists');
}else {
backdrop_set_message('nope');
}

**Actual behavior**
function backdrop_build_form() from /core/includes/form.inc was found = code returns "exists"
function transliteration_get() from /core/includes/transliteraton.inc was not found = code returns "nope"

**Expected behavior**
Functions in core should be in global scope and usable by contributed modules

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.18.1 
- Web server and its version: Apache/2.4.41 (Ubuntu) 
- Operating System and its version: Ubuntu 20.04
- Browser(s) and their versions: Mozilla Firefox

**Comment by earlyburg** [comment]
Relates to this issue for Search API
https://github.com/backdrop-contrib/search_api/issues/20

**Comment by indigoxela** [comment]
I wonder, why `include_once BACKDROP_ROOT . '/core/includes/transliteration.inc';` isn't a solution for you.

All the core functions, that use transliteration_get(), do it that way.

**Comment by earlyburg** [comment]
I'm ok with that - I did not realize. Thank you for helping me I appreciate it.
