### ISSUE TITLE
Views tokens are not properly rendered when used as class rewrites

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4988]
**Description of the bug**

I wanted to use custom classes for taxonomy terms that re output on views page. So I went to my view edit page, clicked on `Content: All taxonomy terms` link and per the description:
 
> You may use token substitutions from the rewriting section in this class.

![Screenshot from 2021-03-07 22-42-28](https://user-images.githubusercontent.com/56604405/110279950-36bbd200-7f97-11eb-8200-b547a0e03713.png)

Unfortunately, as the result of the above token usage I've got the following HTML-code:

```
<span class="term_node_tid-tid term_node_tid_tid term_node_tid-vocabulary-machine-name "><a href="/label/enhancement">enhancement</a></span>
```

**Comment by indigoxela** [comment]
@alanmels can you verify that it would work properly if you use the "Rewrite the output of this field" option and only the css class field don't get their tokens replaced?

Did you try different tokens in that CSS field - and they all fail, or only some of them?

**Comment by alanmels** [comment]
I've just put the following code in the rewrite section copying all suggestions from the **Replacement patterns**:

```
1. [term_node_tid] == Content: All taxonomy terms <br>
2. [term_node_tid-tid] == The taxonomy term ID for the term.<br>
3. [term_node_tid-name] == The taxonomy term name for the term.<br>
4. [term_node_tid-vocabulary-machine-name] == The machine name for the vocabulary the term belongs to.<br>
5. [term_node_tid-vocabulary] == The label for the vocabulary the term belongs to.<br>
```

and only the first item rendered successfully. So probably when using the "Content: All taxonomy term" it can render all of the taxonomy terms, but can not render them individually. In that case, the suggestions in **Replacement patterns** should only be offering `term_node_tid]` and nothing else.

**Comment by indigoxela** [comment]
I'm not sure yet, if I get things right.

- The term you try to create a css class from: is that a multi-value field on the node, or a single value field?
- Do you work with relationships on the terms? (e.g. "Content: Taxonomy terms on node") Or are you directly using the field value?

**Comment by alanmels** [comment]
@indigoxela regardless whatever I'm doing here, the problem is that the tags suggested in Replacement patterns do not work. I'm afraid we've moved on and won't have time to troubleshoot this further, so consider closing this if you can't run tests on your end. Thanks!
