### ISSUE TITLE
Path error in views_handler_field_field.inc

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#4990]
**Description of the bug**

[Reported on the forum](https://forum.backdropcms.org/forum/flexslider-views-block-caused-layout-page-http-error-500):

> Warning: require_once(/app/includes/language.inc): failed to open stream: No such file or directory in require_once() (line 261 of /app/core/modules/field/views/views_handler_field_field.inc).

It looks like there's an error in the path of this `require_once`.

**Comment by laryn** [comment]
PR: https://github.com/backdrop/backdrop/pull/3560

**Comment by indigoxela** [comment]
@laryn, many thanks for providing this super-quick PR. Yes, that looks like a clear oversight in early Drupal to Backdrop conversion steps (it's the old D path).

One small request: can you please add the magic "Fixes link-to-this-issue" to your PR description, so your PR gets linked here and closes this issue automagically?

**Comment by klonos** [comment]
Code change is straight-forward, and it's obvious that the missing `/core` bit from the path was an oversight. RTBC 👍

**Comment by indigoxela** [comment]
Corrected the issue labels. :smile:

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3560 into 1.x and 1.18.x. Thanks folks!
