### ISSUE TITLE
Introduce "node-by-viewer" and "node-by-anonymous" classes

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#4991]
**Description of the need**

There are couple classes - `comment-by-viewer` and `coment-by-anonymous` offered by the `core/modules/comment/templates/comment.tpl.php` file to themers for style the look of comments by current user differently from comments submitted by others. The classes are defined in https://github.com/backdrop/backdrop/blob/9058d7cec7ea49dd54c5d6482347e1c9105d95b7/core/modules/comment/comment.theme.inc#L128-L147

```
  // Gather comment classes.
  // 'comment-published' class is not needed, it is either 'comment-preview' or
  // 'comment-unpublished'.
  if ($variables['status'] != 'comment-published') {
    $variables['classes'][] = $variables['status'];
  }
  if ($variables['new']) {
    $variables['classes'][] = 'comment-new';
  }
  if (!$comment->uid) {
    $variables['classes'][] = 'comment-by-anonymous';
  }
  else {
    if ($comment->uid == $variables['node']->uid) {
      $variables['classes'][] = 'comment-by-node-author';
    }
    if ($comment->uid == $variables['user']->uid) {
      $variables['classes'][] = 'comment-by-viewer';
    }
  }
```

Unfortunately, there are no equivalents to make current user's nodes look differently.

The respective lines from https://github.com/backdrop/backdrop/blob/9058d7cec7ea49dd54c5d6482347e1c9105d95b7/core/modules/node/node.theme.inc#L247-L260:

```
  // Gather node classes.
  $variables['classes'][] = backdrop_html_class('node-' . $node->type);
  if ($variables['promote']) {
    $variables['classes'][] = 'promoted';
  }
  if ($variables['sticky']) {
    $variables['classes'][] = 'sticky';
  }
  if (!$variables['status']) {
    $variables['classes'][] = 'unpublished';
  }
  if ($variables['view_mode']) {
    $variables['classes'][] = backdrop_html_class('view-mode-' . $variables['view_mode']);
  }
```

**Proposed solution**

Even-though it's fairly easy to call `global $user`, compare `$node->uid` with `$user->uid` and if they match then inject needed classes anywhere in template file, for the purpose of convenience and consistency, I believe the core should offer ready-to-use classes.

**Comment by klonos** [comment]
> for the purpose of convenience and consistency...

Totally agree 👍 ...for the same reasons ^^

**Comment by alanmels** [comment]
> > for the purpose of convenience and consistency...
> 
> Totally agree +1 ...for the same reasons ^^

Thanks, @klonos, so if you agree can you review https://github.com/backdrop/backdrop/pull/3562?

**Comment by alanmels** [comment]
Would be nice if this one went in together with https://github.com/backdrop/backdrop-issues/issues/5032 Anyone to review https://github.com/backdrop/backdrop/pull/3562?

**Comment by klonos** [comment]
Sorry for taking this long to review this @alanmels and thanks for the reminder. The code change is simple and straight-forward. RTBC 👍🏼

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3562 into 1.x for 1.19.0. Thanks @indigoxela for bumping this up for visibility!
