### ISSUE TITLE
[RTL] Fix Draggable tables in Basis theme

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5006]
I randomly discovered this issue while testing #4835

Steps to reproduce:
1. Set the default admin theme to Basis
2. Enable the Language module
3. Add a RTL language, such as Arabic or Hebrew:
   ![image](https://user-images.githubusercontent.com/2423362/111825060-b0d14c80-88ef-11eb-959f-cc132e3d4116.png)
3. Make the RTL the default language:
   ![image](https://user-images.githubusercontent.com/2423362/111825170-d1010b80-88ef-11eb-9498-32837b62130b.png)

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3571) is available for testing and review.

As always with core themes: be very picky with testing. :grin:

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼 ...works as expected, and code looks good. For posterity, can we please add the missing `/* LTR */` inline comments in the CSS properties that have respective RTL bits now? Would be RTBC then 😉 

For more info, see: https://docs.backdropcms.org/css-standards

> **Styling for Right-To-Left Languages**
> ... For direction specific property/values, add the code comment /* LTR */ on the same line, preceded by a single space.

**Comment by indigoxela** [comment]
> can we please add the missing /* LTR */ inline comments in the CSS properties that have respective RTL bits now?

Yes, sure, these comments have been added now.

**Comment by docwilmot** [comment]
While youre in the mode, have a look at https://github.com/backdrop/backdrop-issues/issues/2689 too?

**Comment by klonos** [comment]
Thanks @indigoxela ...RTBC 👍🏼

**Comment by quicksketch** [comment]
Thanks @indigoxela and @klonos! I merged https://github.com/backdrop/backdrop/pull/3571 into 1.x and 1.18.x.
