### ISSUE TITLE
Fix static caching in `layout_get_path_layout_names()`

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5017]
The code for `layout_get_path_layout_names ()` is

```
function layout_get_path_layout_names($path) {
  $path_map = &backdrop_static(__FUNCTION__, array());

  $configs = layout_get_all_configs('layout');
  foreach ($configs as $layout_name => $config) {
    if (isset($config['path'])) {
      $path_map[$config['path']][] = $layout_name;
    }
  }

  return isset($path_map[$path]) ? $path_map[$path] : array();
}
```
It looks like the `backdrop_static()` declaration doesn't accomplish anything as currently written. Should this be:

```
function layout_get_path_layout_names($path) {
  $path_map = &backdrop_static(__FUNCTION__, array());
  if (empty($path_map)) {
    $configs = layout_get_all_configs('layout');
    foreach ($configs as $layout_name => $config) {
      if (isset($config['path'])) {
        $path_map[$config['path']][] = $layout_name;
      }
    }
  }

  return isset($path_map[$path]) ? $path_map[$path] : array();
}
```
?

**Comment by klonos** [comment]
> Should this be:

Seems like it 🤔 ...care to file a PR with this change @bugfolder, to see if it breaks any of our tests?

**Comment by bugfolder** [comment]
Will do.

**Comment by bugfolder** [comment]
[PR 3573](https://github.com/backdrop/backdrop/pull/3573)

**Comment by klonos** [comment]
The code change seems reasonable, and no tests were broken 👍🏼  ...although not sure if we have enough 
(or even at all) test coverage for that specific function 🤷🏼 

Perhaps this will need some "manual" testing on one's local (with some custom code) before marking "works for me".

**Comment by indigoxela** [comment]
This is how I tested locally:

With the change applied I put in two `debug()`, one outside the if clause, one inside ("it runs" and "it does something").
Then flushed caches on different pages, counting the messages.

Although it's not a big deal regarding performance, the (now) correct usage of backdrop_static() catches a few calls to the code inside the if clause. So marking this as "works for me".

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼 ...and the code change looks good, so RTBC 👍🏼

**Comment by quicksketch** [comment]
Nice catch @bugfolder! Thanks @indigoxela and @klonos for reviewing! I merged https://github.com/backdrop/backdrop/pull/3573 into 1.x and 1.18.x.
