### ISSUE TITLE
[PS] Optimize field_sync_field_status()

### ISSUE THREAD

**Issue by hosef** [backdrop/backdrop-issues#5028]
There is a function in the field module called `field_sync_field status()`. This is run every time one of 4 events happens:

- When cron is run
- When caches are cleared
- When a module is enabled
- When a module is disabled

Inside this function we run a loop that calls `field_associate_fields()` per installed module, and in there we call `field_read_fields()`. During this process it does a scan of the config directory for every module installed on the site, which gets more expensive as you get more modules or more config files.

We should optimize this to reduce the number of times that we call `field_read_fields()`

**Comment by indigoxela** [comment]
Wow, I'm impressed!

This is how I tested:

In core/modules/field/field.crud.inc in function `field_read_fields()` I put in a watchdog line:

`watchdog('field-debug', 'it runs');`

And then I ran cron (via bee). I quickly realized, that counting of the watchdog entries is better done via sql... too many:

`SELECT count(*) FROM `watchdog` WHERE `type` = 'field-debug'` --  **69** (that testing web has several module installed, but isn't too big, either).

Then I applied [the patch](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/3577.patch), adapted the watchdog command to use "field-debug-2".
Ran cron again via command line and counted again the watchdog entries: **4**

That baffled me that much, that I repeated the tests (reverted patch, adapted watchdog "type", ...). It's reproducible. :+1: Definitely works for me :smiley:

**Comment by indigoxela** [comment]
I suppose, this also needs an `@since` and a change record, because field_associate_fields() now has a second (optional) param.

Code is looking good, RTBC from my side. :+1:

**Comment by quicksketch** [comment]
Looks great @hosef! Thanks @indigoxela for the PR review!

The passing `$fields` by reference seems a little hokey but this function is called from exactly one place in all of core. Seems like this optimization is a definite win with very little chance of impacting contrib with the addition of the new parameter (which has a fallback check anyway).

I merged https://github.com/backdrop/backdrop/pull/3577 into 1.x and 1.18.x. Thanks!

**Comment by quicksketch** [comment]
I'm unsure if this warrants a change record. The old behavior still works as before (no need to actually pass in a `$fields` value). And this isn't a function that many modules (if any at all) would be calling in the first place. `field_sync_field_status()` is the parent function that is actually called in a lot of places.

Seems like this might just be noise to developers keeping track of relevant changes. IMO the `@since` line and git history are sufficient for anyone wanting to track down the change.

**Comment by klonos** [comment]
@indigoxela what @quicksketch said above re a change record make sense to me. Do you still think we need one? If not, then please feel free to remove the "needs - change record" label.

**Comment by indigoxela** [comment]
> Seems like this might just be noise to developers keeping track of relevant changes.

I get the point and am happy to remove the 'needs change record' label.
