### ISSUE TITLE
Update Copyright information in License section of README.md

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#5029]
**Description of the bug**

The **License** section of https://github.com/backdrop/backdrop/blob/1.x/README.md says:

`All Backdrop code is Copyright 2001 - 2016 by the original authors.`

**Actual behavior**

Copyright seems to be only valid for 2001 - 2016.

**Expected behavior**

Copyright is valid until the present year.

**Comment by klonos** [comment]
Seem that we should update our minor release documentation, to include a task that says "Make sure that the end year in the copyright is updated to reflect the current year."

**Comment by himanshu007-creator** [comment]
hi, I would like to work on this issue😄

**Comment by indigoxela** [comment]
Hi @himanshu007-creator,

Yes, of course, you're welcome. :+1:

**Comment by himanshu007-creator** [comment]
> Seems that we should update our minor release documentation, to include a task that says "Make sure that the end year in the copyright is updated to reflect the current year."

Can someone point me to this file :)

**Comment by indigoxela** [comment]
@himanshu007-creator the file to update is the README.md - which currently really lags behind regarding year info.

I don't think you or me have access to the release documentation of the core committers. :smile_cat: I assume, that @klonos just commented here to have sort of a self-reminder for an additional task (to be documented somewhere else).

**Comment by indigoxela** [comment]
@himanshu007-creator many thanks for working on this issue. :pray:

The change is small, but our README will look a lot less "dusty" with the current year in it. RTBC :+1:

**Comment by quicksketch** [comment]
Thanks @himanshu007-creator! I merged https://github.com/backdrop/backdrop/pull/3661 into 1.x and 1.19.x.

**Comment by klonos** [comment]
>I don't think you or me have access to the release documentation of the core committers. 😸 I assume, that @klonos just commented here to have sort of a self-reminder for an additional task (to be documented somewhere else).

Yup, I was referring to the documents in https://github.com/backdrop/backdrop-issues/tree/main/procedures. I've updated things now 👍🏼 ...see:

- https://github.com/backdrop/backdrop-issues/commit/7fd602d5263391c276f0c40945d1c193c2e43e16
- https://github.com/backdrop/backdrop-issues/commit/5bf1a85d4b8b952e1fbc6ca973761d2190dc2b22
