### ISSUE TITLE
Fix error: Call to undefined function `module_implements()` in `backdrop_autoload()`

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5034]
**Description of the bug**

As reported on the forum: 

 - https://forum.backdropcms.org/forum/installation-error-call-undefined-function-moduleimplements-backdropautoload

> Error: Call to undefined function module_implements() in backdrop_autoload() (line 3999 of mysite/webroot/core/includes/bootstrap.inc).

I ran into this, too, as did another responder in the forum -- unfortunately I haven't been able to figure out what's triggering it. The site in question is a CiviCRM site (as was @bugfolder's site) so maybe something there. (The line number has changed since the original report, of course. I think it was 4012 or so for me.)

The fix @bugfolder suggests does function as a workaround, I'm not sure if it seems like a good solution for core or not. The workaround is to add: 

> include_once BACKDROP_ROOT . '/core/includes/module.inc';

before

> foreach (module_implements('autoload_info') as $module) {

**Comment by bugfolder** [comment]
Here's the code where this happens:
```
  if (!isset($class_registry)) {
    include_once BACKDROP_ROOT . '/core/includes/bootstrap.classes.inc';
    $class_registry = backdrop_class_list();
    // Loop through all modules to build the list of classes. We avoid
    // module_invoke_all() because it uses array_merge_recursive(), which is an
    // expensive O(n^2) operation. Instead we use module_implements() and merge
    // the array manually, which is O(n).
    foreach (module_implements('autoload_info') as $module) {
      $module_classes = module_invoke($module, 'autoload_info');
      $module_path = backdrop_get_path('module', $module);
      foreach ($module_classes as $module_class => $relative_path) {
        $class_registry[$module_class] = BACKDROP_ROOT . '/' . $module_path . '/' . $relative_path;
      }
    }
    backdrop_alter('autoload_info', $class_registry);
  }
```
It's pretty clear from the comments that the call to `module_implements()` was intended, and so adding the `include_once BACKDROP_ROOT . '/core/includes/module.inc';` is the right thing to do.

But why does it only appear sporadically? Here's the call stack:

![From Clipboard](https://user-images.githubusercontent.com/29214084/113883677-39b30980-9773-11eb-8391-25f0dd338100.jpg)

`backdrop_autoload()` is getting called for a class (`UcAddress` in my test installation, which looks like an Ubercart class) that has been serialized in the `variables` table. So that situation is only going to arise when upgrading a D7 site that contains a serialized class in the variables table, which is infrequent; hence this issue's sporadic appearance.

At any rate, though, adding the `include_once` to core looks like the proper thing to do.

**Comment by bugfolder** [comment]
PR https://github.com/backdrop/backdrop/pull/3583

**Comment by laryn** [comment]
WFM

**Comment by indigoxela** [comment]
What are the exact steps to reproduce, please?

It seems that some (or all) modules that still use the deprecated variable_get() are affected? Or does this only happen *while the upgrade from D7 is running*? Or are more special steps necessary?

**Comment by laryn** [comment]
Hard to provide STR (at least yet) since it happens during the upgrade from Drupal 7 in sporadic circumstances.

**Comment by bugfolder** [comment]
> What are the exact steps to reproduce, please?

1. Create a Drupal site. Include and enable a module that stores a classed object in the variables table. A good example would be Ubercart, which stores the store address (`'uc_quote_store_default_address'`) as a UcAddress object using `variable_set()`/`variable_get()` (in the D7 version).
2. Attempt to upgrade the site to Backdrop. The failure happens during initialization, before any `hook_update_N()` calls.

> It seems that some (or all) modules that still use the deprecated variable_get() are affected? 

No. This branch of the code is only reached when you need to unserialize a class during upgrade. It doesn't matter whether the Backdrop version of the module uses deprecated `variable_get()`.

> Or does this only happen while the upgrade from D7 is running? 

It happens at the very beginning of the upgrade-from-D7 process: specifically at the point that Backdrop is readling in all of the variables from the `variables` table.

> Or are more special steps necessary?

Just steps 1 and 2 above.

**Comment by indigoxela** [comment]
@bugfolder Thank you for your analysis.

> The failure happens during initialization, before any hook_update_N() calls. ...
> ...specifically at the point that Backdrop is reading in all of the variables from the variables table.

I see. In this case include_once makes sense.

**Comment by klonos** [comment]
> I see. In this case include_once makes sense.

Code change is simple, and it makes sense. RTBC.

**Comment by quicksketch** [comment]
Thanks! This fix makes sense and doing `include_once` in `bootstrap.inc` is not uncommon when loading new APIs for the first time (such as in `backdrop_language_initialize()`). I merged https://github.com/backdrop/backdrop/pull/3583 into 1.x and 1.18.x. Thanks folks!
