### ISSUE TITLE
Trying to sort NULL array in field_ui_widget_type_options()

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5037]
**Description of the bug**

A module can decide to **support**  a field type, by providing a new widget, by listing this in `hook_field_widget_info()`:
```
function my_module_field_widget_info() {
  return array(
    'my_module' => array(
      'label' => t('My module'),
      'field types' => array(
        'a_field_provided_by_another_module',
      ),
    ),
  );
}
```
If the field type doesnt exist however, there is a `Warning: asort() expects parameter 1 to be array, null given in field_ui_widget_type_options() (line 1517` error in the logs. This is because Backdrop has added a `asort($options[$widget_field_type])` line in that function, when in fact for our `a_field_provided_by_another_module` no options are available because the module is not installed.

**Steps To Reproduce**
Implement `my_module_field_widget_info()` as above and add a random string. In D7 this would be fine, in Backdrop theres watchdog errors about `aosort` and missing indexes.

**Expected behavior**

In D7 you could do this so that your new module could provide a widget for this field type *if* the user ever installed it. 

**Additional information**

In core since https://github.com/backdrop/backdrop/commit/656c8945be0089de1d3bf394eacb82528bc35846

**Comment by indigoxela** [comment]
Nice catch, and confirmed.

Probably I'd normally wrap the widget info in `if (module_exists('othermodule'))`, but that's no requirement. And as it works fine in D7, it should also work in B for compatibility reasons.

This is how I confirmed it:

In a custom module I put in this minimal code:
```
function testthing_field_widget_info() {
  return array(
    'testthing' => array(
      'label' => t('Test thing widget'),
      'field types' => array(
        'a_field_provided_by_another_module',
      ),
    ),
  );
}
```
Enabled that module and went to admin/structure/types/manage/post/fields.

There I got:
```
    Warning: asort() expects parameter 1 to be array, null given in field_ui_widget_type_options() (line 1517 of ...core/modules/field_ui/field_ui.admin.inc).
    Notice: Undefined index: a_field_provided_by_another_module in field_ui_widget_type_options() (line 1528 of ...core/modules/field_ui/field_ui.admin.inc).
    Notice: Trying to access array offset on value of type null in field_ui_widget_type_options() (line 1528 of ...core/modules/field_ui/field_ui.admin.inc).
```
Wrapping that asort() in !empty() fixes the problem.

A [PR](https://github.com/backdrop/backdrop/pull/3586) is available for testing and review.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼 ...code looks simple/straight-forward. I'll have to also test this ...unless someone else beats me to it.

**Comment by quicksketch** [comment]
@indigoxela Could you check my comment on the PR? I think there's still a further edge-case where this problem could occur even with the proposed fix: https://github.com/backdrop/backdrop/pull/3586/files#r625452136

**Comment by indigoxela** [comment]
> Could you check my comment on the PR?

Sure, many thanks for having a look, please see my answer / question there.

**Comment by klonos** [comment]
@docwilmot since you reported this, could you have a look at the now updated PR and review/test? Thanks.

**Comment by indigoxela** [comment]
@docwilmot friendly reminder - as you opened this issue you'd be the perfect candidate for review. It shouldn't be too much effort, as the change is minimal.

**Comment by docwilmot** [comment]
Tested, fixed, RTBC. Thanks @indigoxela.

**Comment by quicksketch** [comment]
Thanks folks! I've merged https://github.com/backdrop/backdrop/pull/3586 into 1.x and 1.19.x.
