### ISSUE TITLE
Dashboard menu item shows up even if module is not enabled

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5039]
**Description of the bug**

I'm going through a trial upgrade on a D7 site and it looks like the Dashboard menu link is created even though the Dashboard module is not activated. 

We should either activate the Dashboard module on upgrades, or make sure the menu item isn't activated.

**Comment by klonos** [comment]
I'm also doing test (vanilla) D7 to Backdrop updates as part of #5036. I'll keep this in mind and check for the Dashboard module and menu item status after the upgrade is completed.

**Comment by klonos** [comment]
Lets address this issue in #3888.
