### ISSUE TITLE
Flexible layout templates: Use region name as default class name and option for additional CSS classes for regions

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5044]
**Description of the need**

Be able to set **Additional CSS classes** for regions in flexible layout templates. Addresses https://forum.backdropcms.org/forum/using-bootstrap-classes-flexible-layouts-regions.

There's already one for rows:

![Screenshot from 2021-04-16 14-54-09](https://user-images.githubusercontent.com/1071483/115072572-c5d8d580-9ec5-11eb-9244-2ecda9f4e576.png)

but it would be useful to be able to target "utility" generic classes per region. For example, to be able to add more Bootstrap grid classes per region to have more control over different screen widths. By default only medium screen is set. So a four column layout would be "col-md-3" and any smaller screen would be only one column. With additional classes it would be possible to set "col-sm-6" for two columns. Or, add Bootstrap padding classes, or Bootstrap classes that leverage CSS Flex. Or, another example, be able to set background classes per region. Other CSS frameworks also have their own generic utility classes as well.

**Proposed solution**

Add an `Additional classes` field [for each region].

<img width="1448" alt="Screen Shot 2021-12-23 at 4 42 14 PM" src="https://user-images.githubusercontent.com/397895/147302522-287aeae9-7da4-40bc-b1c8-758310989674.png">

---

Markup for "Region 1"  before PR: `<div class="l-col col-md-8">`

Markup for "Region 1" after PR (with added additional class of "foo bar": `<div class="l-col col-md-8 l-region--region-1 foo bar">`

**Alternatives that have been considered**

* Avoid using flexible layout template entirely and just craft a custom template. But that's not very easy for non-developers. 
* Or, create a contrib module that only addresses adding this one field. Not a great option: modules with minor UI improvements seldom get widely used, are not that discoverable. And it's a lot of overhead for just one small field.
* Or, create a contrib module that provides a UI for adding additional classes everywhere. Add this UI into that module (and, as we find other places that could benefit from the ability to add custom classes, add those to this module also)

This now includes the automatic class name from https://github.com/backdrop/backdrop-issues/issues/5032.

---

**Advocate: @herbdool **

---

PR: https://github.com/backdrop/backdrop/pull/3592

**Comment by stpaultim** [comment]
I can see how this would be helpful. I've tested in the sandbox and it works for me. 

BEFORE:

![region-no-classes](https://user-images.githubusercontent.com/3144571/131776279-a22579b0-1904-489e-ad93-4ffc34bb3995.png)

AFTER:

![region-classes](https://user-images.githubusercontent.com/3144571/131776296-f66ed608-17a8-4799-80a8-0066ccac8031.png)

Here is the markup showing that the classes are where they are expected to be:

![Actual markup](https://user-images.githubusercontent.com/3144571/131776476-e172babc-d62b-486b-ac01-51358fcee443.png)

**Comment by stpaultim** [comment]
I just went back and read the discussion that leads up to splitting the PR in from #5032

With that discussion in mind, I'm going to be wishy-washy. I don't think that in my day to day theming I require a custom class for a region like this. However, I see the value in being able to add classes to items like this. I think that if I were better at using Bootstrap Grid classes, this field could be very useful. 

I share the frustration with the subjectiveness of the 80% rule and am personally not sure how to apply it here. 

My biggest concern with adding this field to the core UI is additional clutter. Adding classes through the UI is something that I don't do often, but when I do it, I'm glad it's there. 

I certainly have the concern that this is too small a feature on it's own to get into a contrib module. The suggestion of a Layout Extra's module sounds good, but I haven't any idea what else would go into it and/or how likely it is to come into being.

**Comment by klonos** [comment]
I like this feature as well, and I see the value of having it in core. It will allow no/low-code site builders to get more things done, without having to write their own custom templates.

@herbdool the PR needs to be rebased, and I'd like us to change the following:
- "Additional classes" -> "Additional CSS classes"
- "Style" -> "Row style"
- "Additional row classes" -> "Additional row CSS classes"

I have also tested the PR sandbox, and I have noticed this regression compared to how things work now:
1. Start creating a new flexi template -> add a name -> save
2. Edit the middle row -> change number of regions to 2 -> pick any width combination -> save
3. When you return to the row edit modal, the "Content" name of the first region is retained, so I only need to add a name to the newly-added region 👍🏼 

In the PR sandbox, the existing region name changes to "Region 1" 👎🏼

**Comment by jenlampton** [comment]
I see this issue has a minor release milestone, but since it doesn't have an advocate I'm going to remove it. (If it does have an advocate, please add that into the Original Post and add it back)

**Comment by herbdool** [comment]
@stpaultim @klonos I was inspired by the Views UI and changed the UI here so that there's a checkbox to add css classes for regions. I think that helps address the "clutter". See my example:

![Screenshot from 2021-12-01 17-00-37](https://user-images.githubusercontent.com/1071483/144321348-6700b81a-517e-449d-a0f1-dab20c1dc814.png)

And to differentiate it from https://github.com/backdrop/backdrop-issues/issues/5032 - I removed the "machine name as css class". So now there's just this one field.

By the way, one reason this PR is quite useful, particularly for Bootstrap, is that by default the flexible template will only set the columns (in Backdrop they're "regions") to 2 breakpoints: the default (narrowest screens) and medium (e.g.: col-md-8). This additional field allows for more breakpoints (e.g. `col-12 col-sm-6 col-md-8 col-lg-4 col-xl-2`, offsets, and anything else that Bootstrap or other themes can offer (see https://getbootstrap.com/docs/4.0/layout/grid/). 

(Aside from this issue it might be even useful to have an option to not have any preset CSS classes for regions. Then we could even do variable width content: https://getbootstrap.com/docs/4.0/layout/grid/#variable-width-content).

**Comment by herbdool** [comment]
Or maybe if someone checks "Create CSS classes" it overrides the default. Rename it to "Override default CSS classes"?

**Comment by indigoxela** [comment]
Some odd things are going on...

First of all, there's a visual regression in the preview (template edit, layout edit):

![layout-template-edit](https://user-images.githubusercontent.com/842066/144707437-2909ff68-4401-4dd3-8427-96f676df82cf.png)

And the resulting layout also appears broken (wrong margin): https://pr3592-oio7ppxe7perday9nr3sbs5sjaayobwv.tugboat.qa/fooflexipage

Note that this only happens _if I add a region CSS class_. As soon as I remove that class (uncheck "Create CSS classes"), the layout works again as expected. At least, as I'd expect it to work.

Or is that "ripping out of normal layout behavior" some special feature I missed?

**Comment by herbdool** [comment]
@indigoxela oops. Probably happened after I merged conflicts. Wasn't happening locally. I'll fix.

**Comment by herbdool** [comment]
@indigoxela I just realized it's not broken. That's how it's supposed to be, though I do realize it needs more work (or put back something I took out - which may be fine).

The reason I took a drastic turn is that I realized that the flexible template was hardcoding stuff that people might not want at all. For example, it is now possible in Bootstrap 4+ to have variable width columns: https://getbootstrap.com/docs/4.0/layout/grid/#variable-width-content. So someone may want `col-md-auto` or even just `col`. But flexible template builder assumes that someone *always* wants a class starting with `col-md-` (1-12). But that would prevent these more "flexible" layouts.

Perhaps I put this back to it not removing that default (and leave that for contrib) but I would still like to consider for core the ability to set *additional* CSS classes. What do you think?

**Comment by indigoxela** [comment]
So this is a feature? Hm... should the issue description get updated then?

If I **add** a css class, I wouldn't assume, that I actually override existing classes. Is this override the thing you're actually after?

**Comment by herbdool** [comment]
@indigoxela yes, a feature, but I realize now, going by your feedback, that it's a step too far. Better in contrib. But I will adjust this PR to have it *add* rather than override.

**Comment by herbdool** [comment]
@indigoxela I've updated the PR. Now it's like you expect: it'll just add classes to existing classes.

**Comment by indigoxela** [comment]
> Now it's like you expect: it'll just add classes to existing classes.

Confirmed, it's working again. This is what we have now:

![region-dialog](https://user-images.githubusercontent.com/842066/145354086-94ad82f2-ef53-42c7-a60d-146dd25f40dd.png)

Status unchecked (closed) and checked (opened).

Looks pretty nice, but maybe other people might want to leave some feedback here, too.

**Comment by olafgrabienski** [comment]
> maybe other people might want to leave some feedback here, too

I like it! One question: should the label be called "Additional CSS classes"? (I think, the checkbox is fine without "additional".)

Btw, I see a typo in the description text, the `s` in `multiples`.

**Comment by herbdool** [comment]
@olafgrabienski I've updated it based on your suggestions.

**Comment by olafgrabienski** [comment]
Many thanks for the update! Works like a charm, and I think it's really useful, e.g. to style the main content region and a sidebar differently.

**Comment by klonos** [comment]
Sorry for the label change. @herbdool I take it that you are currently advocating for #1739 first. Right?

**Comment by herbdool** [comment]
@klonos there's no rush on #1739

**Comment by jenlampton** [comment]
I took another look at the latest PR. The interface is a lot better than the last time I saw it. I don't use flexible templates very much so I'm happy to defer to others on this one. If you all like it, then let's get it in :)

@herbdool I think you said you wanted to advocate for this issue today so I added your name to the Original Post. I also posted a recent screenshot from the PR.

I have some thoughts on the language for the interface, and will provide a PR in a moment with:
* The checkbox label `Additional CSS classes`: I think we should change this label to an action, like `Add additional CSS classes` because checking the box makes that action possible.
* The input label `CSS classes`: I would like this label to match the one for the CSS classes on the row, so `Additional region CSS classes` might be a better fit here.
* Description text: `Define multiple classes separated by spaces.` could be shortened to `Separate multiple classes with spaces.`

**Comment by jenlampton** [comment]
Okay, I've posted [a PR](https://github.com/herbdool/backdrop/pull/17) because I feel like if I'm going to complain about something I better at least help try to improve it.

**Comment by indigoxela** [comment]
Just for better understanding: these additional classes aren't sanitized. That's probably the usual behavior - is that correct?

**Comment by herbdool** [comment]
@indigoxela I'll check.

**Comment by herbdool** [comment]
@indigoxela I notice they're cleaned in this example: https://docs.backdropcms.org/api/backdrop/core%21modules%21layout%21layout.theme.inc/function/template_preprocess_block/1. I wonder if we have to fix it for custom classes on rows as well.

**Comment by indigoxela** [comment]
I'd like to note that it doesn't do any harm. So maybe it's not necessary to sanitize at all (?). If there isn't a clear policy for that yet, I'd suggest to open a follow-up issue where we can properly discuss it - and then do it consistently in core.

IMO this isn't a show-stopper for this PR. @herbdool what do you think?

**Comment by herbdool** [comment]
I suppose it can be a follow-up.

**Comment by herbdool** [comment]
Oops, accidentally closed. I'll get back to this after Christmas.

**Comment by herbdool** [comment]
Ready for a review.

**Comment by jenlampton** [comment]
Would this be an XSS issue without sanitization?

**Comment by herbdool** [comment]
@jenlampton @indigoxela I've taken a stab at sanitizing the custom classes. Audi did it for rows.

**Comment by indigoxela** [comment]
Great, CSS classes now get sanitized - works for me (still).

@herbdool two really tiny standard / code readability fixes and we're done.

> Would this be an XSS issue without sanitization?

@jenlampton no XSS issue, but we'd let people potentially put in invalid (useless) stuff into the class attribute.

**Comment by herbdool** [comment]
@indigoxela I've made the fixes. Ready for rtbc?

**Comment by indigoxela** [comment]
> Ready for rtbc?

Yes, this is now RTBC :+1: Many thanks for your patience with all the iterations.

**Comment by herbdool** [comment]
I've now merged in #5032 into this one since it seems there was general consensus for both. Seemed easiest way to manage this. The code was quite similar - just copied over the machine name functionality and have it add to the classes for the template.

@jenlampton @indigoxela

**Comment by herbdool** [comment]
Does this need another review or is it okay since both were previously RTBC?

**Comment by quicksketch** [comment]
I posted a review to https://github.com/backdrop/backdrop/pull/3592#pullrequestreview-842458807, I think this needs a little more work since if we're anticipating the machine name may be used for more things other than just "class" in the future, we should rename the "region_class" key to a general word. I suggested we use "name" for the machine name, which would make it line up with Layouts and Views configurations.

I also think region names _should_ be required to be unique, as machine names are required to be unique in every other situation, such as field keys within a view, node type names, and the region names within a non-dynamic layout (using a normal layout.info file).

Comments posted to the PR with a bit more detail: https://github.com/backdrop/backdrop/pull/3592#pullrequestreview-842458807

**Comment by herbdool** [comment]
@quicksketch thanks for the review. I agree we can change to label/name. I'm having trouble coming up with a reasonable way to force region names to be unique. I don't think we want to force it across *all* templates, but I also don't see how we can dynamically discover the current region names in the loaded template. And it has to also know about the other field values on the form. It seems to me it needs to be more complex than what the machine_name FAPI can handle.

**Comment by quicksketch** [comment]
I posted a comment back to the PR: https://github.com/backdrop/backdrop/pull/3592#discussion_r777288247 I believe it should be possible to do unique checking just within the current layout.

**Comment by quicksketch** [comment]
I saw in Zulip that @herbdool has been having some power outage problems. I'll take a look at this and see if I can work out the validation and fix the failing tests.

**Comment by quicksketch** [comment]
I pushed a small fix to the display of labels on flexible template regions to the PR: https://github.com/backdrop/backdrop/pull/3592/commits/b35a2f23f4bc73ae5612fd2206ec46976171322d

I think that should fix the failing tests.

**Comment by herbdool** [comment]
Thanks @quicksketch. I just had layout_layout_info in a corner while I had a moment but you found it first. 😁 For some reason I had a hard time tracking it down.

**Comment by herbdool** [comment]
I tested that last part and the labels show up correctly. Tests passing. But since it's my PR I'll let someone else update the labels.

**Comment by quicksketch** [comment]
I tested this and confirmed the new validation handler on region machine names works correctly, nice job @herbdool! With the tests now passing and everything looking tidy, I've merged this into 1.x for 1.21.0. Thanks everyone for your work and collaboration on this!
