### ISSUE TITLE
Hide admin bar when printing

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5048]
This is the respective of https://www.drupal.org/node/2472025, which is part of #5042

Do we need the same in Backdrop? If so, then this is the code change: https://git.drupalcode.org/project/drupal/commit/88de1737a6dac893d5f2e480dbf5b17263705628

**Comment by indigoxela** [comment]
> Do we need the same in Backdrop?

Printing the admin menu makes no sense, so let's add that change. :+1:

I don't think that we really need a new css file for that, `@media print {}` might also do the trick.

**Comment by BWPanda** [comment]
Do people actually print websites...!? 🤯😆

**Comment by klonos** [comment]
I often print web pages to pdf (usually receipts from online transactions etc.).

**Comment by BWPanda** [comment]
'Printing to PDF' should really be 'saving as PDF' IMO. But yes, I get your point.

**Comment by klonos** [comment]
> 'Printing to PDF' should really be 'saving as PDF' IMO.

Agreed, but AFAIK, that's how it works (using virtual printers) ...at least on Mac and Windows. In both cases, you specify `@media print` in CSS, and that's what's being used.

**Comment by jenlampton** [comment]
> I don't think that we really need a new css file for that, @media print {} might also do the trick.

Google really penalizes sites that use media queries (in a single file) over those that only load the CSS files that are needed for a given media. I think if we have the option to add something new, we should do it the same way Drupal did it, in a separate file, so don't bring down the pagerank of Backdrop sites.

I feel differently about device width -- a single page-load can result in multiple widths being necessary (turning your phone sideways, for example) -- but CSS for the "print" action isn't going to be necessary when viewing the page in a browser.

I'm going to apply the drupal patch as-is and we can start from there.

**Comment by jenlampton** [comment]
Pr ready for review at https://github.com/backdrop/backdrop/pull/3625

**Comment by quicksketch** [comment]
I checked the network inspector and I was surprised to see that browsers download CSS files even if they're not going to parse them (in the case of `media="print"`). There's a StackOverflow discussion on why this might be: https://stackoverflow.com/questions/6311235/why-do-all-browsers-download-all-css-files-even-for-media-types-they-dont-sup

But as this only applies to users that can see that admin bar, I don't think it's an issue for overall Backdrop performance.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3625 into 1.x and 1.18.x. Thanks folks!
