### ISSUE TITLE
/node/X not redirecting to permalink

### ISSUE THREAD

**Issue by LubomirKurpel** [backdrop/backdrop-issues#5050]
**Description of the bug**

When making a website in Drupal 7, I use to write <a href="/node/X" where X is a node ID. I use this technique so when permalink changes it does not break anything, because NID is always the same.

But in backdrop this does not redirect me to permalink set to given node. It loads the node just fine and everything but this surely results in duplicate pages - one with permalink and one with node/ID.

**Expected behavior**

Redirect to permalink if possible, like it is done in Drupal I think.

**Comment by indigoxela** [comment]
@LubomirKurpel many thanks for taking the time to report your issue.

I don't think that Drupal redirects automatically if you add a link like "node/4" _in content_.

If you use the _ckeditor_link_ module and enable the filter, bare "node/X" links get replaced with the node alias - maybe you mean that?
Backdrop does this differently, though. The editor link plugin adds the alias out of the box, there's no additional filter that rewrites content when rendered.

BTW if you add items to a menu like "node/X", the link automatically shows the alias - same as in D7.

So maybe the first thing to clarify here is: Where did you expect different behavior and which modules provide that functionality in Drupal. :smiley:

**Comment by olafgrabienski** [comment]
> I don't think that Drupal redirects automatically if you add a link like "node/4" in content.

Right, Drupal doesn't redirect links automatically out of the box but with the help of the contrib modules Redirect and Global Redirect. Redirect was integrated into Backdrop core, and in #2871 people were wondering if we shouldn't also put the Global Redirect functionality into core's. Most people agreed with the request, but nobody ever worked on it.

I'm all for to revive #2871 (and to close this issue as duplicate).

**Comment by LubomirKurpel** [comment]
Oh okay I see, I have redirect and global redirect modules installed on all my projects, somehow I install it by default and it does this behaviour I guess.

**Comment by olafgrabienski** [comment]
Yes, https://backdropcms.org/project/globalredirect should do the trick in Backdrop.

(Closing this issue in favor of #2871.)
