### ISSUE TITLE
Should function system_rebuild_module_data() use static caching anyway?

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5052]
Follow up for https://github.com/backdrop/backdrop-issues/issues/5046

[That function](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_rebuild_module_data/1) uses backdrop_static which is currently broken anyway, as it immediately gets reset.

Using the static cache for a function that *resets* caches (also static) just feels wrong by concept.

A discussion has started, if that function actually *should* use a static cache anyway. To not further block the related bugfix, this issue has been created. As a question at first - we'll see how far we get. :smile:

**Comment by indigoxela** [comment]
Some more background: backdrop_static() is a handy tool to re-use output from helper functions, that are likely to run several times per page call (request). The static caching prevents the same code from running again and again. It's widely used in Backdrop.

However, function system_rebuild_module_data() *refreshes* information and is supposed to only run once per request. It makes sure that no stale data get used on, for example, /admin/modules - which is a form. To my understanding that's no actual use-case for static caching.

I might be wrong, that's the reason for this question issue. :smile:

**Comment by indigoxela** [comment]
> Maybe the static cache is needed elsewhere?

I don't actually think that benchmarks are an answer to my question.

I do understand why someone added the static cache there, but I think it was based on wrong assumptions. A function that's supposed to reset caches, currently also the one in use *in that function*, should not use static caching.

What it needs IMO is to make sure that the function only runs *once*. And that's not hard.

**Comment by jenlampton** [comment]
But if there are four systems that need to rebuild module data that all
activate one one page request, we really need to only rebuild the data
once. The static cache makes sense.

**Comment by indigoxela** [comment]
@jenlampton  I'll give it another try...

This popped up with an issue, where two different modules run the same cache rebuild on the same page. And my suggestion was to let the module that "owns" the page (defines it in hook_menu) do the refreshing. And the other one should not interfere.

But digging a bit deeper caused me to raise this question here: A function that **resets** caches is IMO no real use-case for static caching. I find this paradox.

> But if there are four systems that need to rebuild module data that all
> activate one one page request, we really need to only rebuild the data
> once.

Exactly: only do it once! Means, on a page one module is responsible for cache reset, not all / any.

> The static cache makes sense.

IMO no. It conceals a problem, that should get fixed differently. - Apart from that it's currently not working properly as the static cache in use also gets reset. (That's why /admin/modules is so slow when there are more modules installed - see the other issue)

**Comment by jenlampton** [comment]
> Exactly: only do it once! Means, on a page one module is responsible for cache reset, not all / any.

But there's no way that system A can always know which of systems B, C, D, or E (or any other) might also need to reset the cache on that same page or not.

**Comment by indigoxela** [comment]
> But there's no way that system A can always know which of systems B, C, D, or E (or any other) might also need to reset the cache on that same page or not.

This all happens in core. The problem is caused by two core modules. System, which is always on, and Update which is not necessarily on. I'm convinced that there's a clean and elegant way to resolve things without breaking page performance by calling an expensive function twice per request.

And I'm still sure that the static cache is no solution for a function that resets caches. I really tried to explain why, but seem to have failed so far. :smile: I give up. :shrug:

**Comment by jenlampton** [comment]
This one example you're looking at now is in core, but the function to
reset module data could also be called by any number of contrib projects,
which is why it needs the static cache. :)
