### ISSUE TITLE
Fix PHP warning: from layout_get_layout_by_path(). 2nd argument should be an array.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5057]
In layout.module, function `layout_get_layout_by_path()`, line 1261 is
```
$context_data = call_user_func_array($context_info['load callback'], $router_item['original_map'][$context->position]);
```

But [the 2nd argument of `call_user_func_array()` should be an array](https://www.php.net/manual/en/function.call-user-func-array.php). In the rare situation that this branch is ever reached, a warning is issued:

> Warning: call_user_func_array() expects parameter 2 to be array, string given...

The proper line should be

```
$context_data = call_user_func_array($context_info['load callback'], array($router_item['original_map'][$context->position]));
```

PR to follow.

**Comment by indigoxela** [comment]
@bugfolder nice catch!

> In the rare situation that this branch is ever reached,...

Can you provide an example situation? I'm no expert with the layout system and am not sure when a 'load callback' is set.

Also, thank you for your PR. It seems that some (unrelated?) tests are failing and the deploy ran into a timeout. Mind to "turn it off and on again"?

**Comment by bugfolder** [comment]
> Can you provide an example situation? I'm no expert with the layout system and am not sure when a 'load callback' is set.

I haven't been able to find a situation when this branch is reached in ordinary operation. (I found it by chance while [debugging an issue in Layout Wildcard](https://github.com/backdrop-contrib/layout_wildcard/issues/17).)

From the code logic, I had thought that this scenario would get one there:
1. Create and enable a module with a page defined in `hook_menu()` at path `mymodule/%node`.
2. Create a layout with path `mymodule/%`.
3. Set the context to be of type Node, and give it a visibility condition (e.g., Node:Type).
4. Save.
5. Go to `mymodule/1` in the browser.

Except that when you save at step 4, the Configure Layout page silently changes your chosen context type from "Node" to "String pass-through", discards your visibility condition, and then (really annoying) hides this from you by not re-loading the Configure Layout page, but takes you to the Manage Blocks page, and you have to click back to Configure Layout to see. (I think this is another bug, will submit a separate issue.)

> It seems that some (unrelated?) tests are failing and the deploy ran into a timeout. Mind to "turn it off and on again"?

Not sure what "turn it off and on again" means, but if it's something you can do, by all means, please proceed.

**Comment by indigoxela** [comment]
> I haven't been able to find a situation when this branch is reached in ordinary operation.

Then I won't be able to test.

> Not sure what "turn it off and on again" means, but if it's something you can do,

Nope, I can't. No permission.

It means: close your PR wait 5 minutes, then open it again and hope that the deploy doesn't time out and tests are passing. (Zen.CI)

**Comment by bugfolder** [comment]
Yup, understood about the test. And of course, if there's no way to get to that branch of the code, there's no urgency to fix it since an unreachable branch is unlikely to affect many people. ;o) I'll keep looking. Meanwhile, I'll do the restart thing you described.

**Comment by bugfolder** [comment]
OK, after some further investigation, that branch of code is reached when a layout has a context whose data object is not already loaded into `$router_item` in `layout_get_layout_by_path()`. The built-in contexts don't do that, but a contrib module that creates a LayoutContext could do so.

So, this minimal module sets up the situation.

[bug_demo.zip](https://github.com/backdrop/backdrop-issues/files/6370230/bug_demo.zip)

1. Enable the module (which creates a simple page at path `bug-demo/%` and creates a context for the path).
2. Create a new layout. Give it the path `bug-demo/%` (so that it will apply to the path that the module creates).
3. The Layout configuration page will automatically give it the `LayoutLCStringContext`.
4. Save the layout.
5. Visit the page `bug-demo/1`.
6. The "Warning: call_user_func_array() expects parameter 2 to…" will appear in the dblog.

Then:

1. Apply the patch from the PR.
2. Revisit the page `bug-demo/1`.
3. No more warning.

**Comment by klonos** [comment]
I don't think that the issue here is about the logic branch being reached or not; it is about the fact that the php function `call_user_func_array()` expects the second parameter to be an array, and `$router_item['original_map'][$context->position]` is not one.

Having said the above, I think that we should add an inline comment in that conditional, so that next time a person has to troubleshoot that bit of code knows what it's used for. What you mentioned at the start of your previous comment @bugfolder seems appropriate:

> This branch of code is reached when a layout has a context whose data object is not already loaded into $router_item in layout_get_layout_by_path(). The built-in contexts don't do that, but a contrib module that creates a LayoutContext could do so.

**Comment by bugfolder** [comment]
> I don't think that the issue here is about the logic branch being reached or not

Of course. I only mentioned it because (in response to @indogoxela's comment) I had to figure out how to get to the branch in order to provide a testable scenario.

Happy to add that comment to the PR.

**Comment by indigoxela** [comment]
@bugfolder many thanks for fiddling that test module!

I could easily reproduce the problem, as `$router_item['original_map'][$context->position]` is clearly no array.
And I can, of course, confirm that the PR fixes it.

RTBC from my side.

> I don't think that the issue here is about the logic branch being reached or not

@klonos You're right, that's not the issue. But when testing/reviewing something, I prefer to understand what's going on there - which I'm able to now. Proposing a change to core - even if it looks right - feels odd if I don't know when this code is called.

**Comment by indigoxela** [comment]
In case, someone's interested - this is what `$context` looks like at that point:

```
LayoutLCStringContext::__set_state(array(
   'plugin' => 'lc_string',
   'aliases' => 
  array (
  ),
   'required' => true,
   'locked' => true,
   'position' => 1,
   'name' => NULL,
   'label' => NULL,
   'data' => '5',
   'argument' => NULL,
   'restrictions' => 
  array (
  ),
   'storage' => false,
   'is_new' => false,
   'settings' => 
  array (
  ),
))
```

**Comment by quicksketch** [comment]
Thanks @bugfolder for reporting and fixing this issue!! Thanks @indigoxela and @klonos for reviewing. Definitely an oversight in the code of Layout, because we never encounter that situation in core, that code branch has probably never really been executed. The fix looks correct to me and thanks to your folks' testing I feel good about merging this. Merge https://github.com/backdrop/backdrop/pull/3607 into 1.x and 1.18.x. Thanks!
