### ISSUE TITLE
Language field can't be moved around reliably (terms)

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5060]
**Description of the bug**

Vocabularies that has multilingual support enabled receive a new "Language" field. When organizing fields on the "Manage fields" page, this field can be moved around and reorganized. Unfortunately, when visiting the "Add term" page for this vocabulary, that Language field gets displayed in a different location.

This is a parallel issue to what was fixed here: https://github.com/backdrop/backdrop-issues/issues/4321

--

[PR](https://github.com/backdrop/backdrop/pull/3606) by @laryn based on @indigoxela's fix in the node issue

**Comment by klonos** [comment]
Thanks @laryn 👍🏼 ...adding `Fixes #5060` in the PR won't cut it unfortunately, because the Backdrop issue queue and the PRs are on separate GitLab repos. It will need to be `Fixes https://github.com/backdrop/backdrop-issues/issues/5060` instead.

**Comment by indigoxela** [comment]
@laryn many thanks for providing your PR. We're halfways there, but... something seems fishy

1) The system name of that pseudo field changes, which means that we end up with both names in the json file, example:

```
        "display": {
            "description": {
                "default": {
                    "weight": "0",
                    "visible": true
                }
            },
            "langcode": {
                "default": {
                    "weight": "0",
                    "visible": true
                }
            },
            "language": {
                "default": {
                    "weight": "0",
                    "visible": true
                }
            }
```
(From field.bundle.taxonomy_term.[my_vocab].json) Heck, do we need an update hook? And wouldn't the previous node change also need one?

Something to still figure out: The language/langcode pseudo field isn't displayed at all (by core, no contrib like i18n involved). Is this by intention? So why doesn't the display setting reflect that?

**Comment by klonos** [comment]
Don't you all just love these rabbit holes 😅

**Comment by laryn** [comment]
@indigoxela Are one or both of the items you mention okay as follow up issues?

**Comment by laryn** [comment]
@indigoxela No, you're right about the update hook. That should be part of this (and we can probably just wrap the update hook for the node into this PR). But maybe this is a separate thing?

> Something to still figure out: The language/langcode pseudo field isn't displayed at all (by core, no contrib like i18n involved). Is this by intention? So why doesn't the display setting reflect that?

**Comment by indigoxela** [comment]
Ah, now I get it, the display thing. Sure, that can be a follow-up.

**Comment by laryn** [comment]
@indigoxela 
I've added an update hook that clears out the `language` cruft from term-related configs. I looked in a site that had this and didn't see anything that needed cleaning in the node files. Do you think I should add a parallel update hook in the node install file just to be safe?

**Comment by indigoxela** [comment]
@laryn Great! I'll try to test and review ASAP. :+1:

**Comment by indigoxela** [comment]
After some time I now try to start fresh and reproduce the initially reported problem... and I can't.

Moving the language pseudo field on the admin/structure/taxonomy/THE_VOCAB/fields works as expected. Tried all sorts of combination (above title, below description, in between...)

Every time I open the form taxonomy/term/X/edit or create a new one, the language field appears at the perfectly correct place.
I can not reproduce the problem at all on a vanilla (multilingual) install.

**Comment by indigoxela** [comment]
Ha, got it, that's the "reliable" part. Sometimes positioning is right, but only by chance. This all looks different, if one adds more fields to terms.

**Comment by indigoxela** [comment]
It works for me. Partly. After applying the changes (and running the config update), the fields appear perfectly, where they should.

Hm. I **did** run the update hook, then inspected my field.bundle.taxonomy_term.MY_VOCAB.json, and the language cruft was still there:

```
{
    "_config_name": "field.bundle.taxonomy_term.multilingual",
    "bundle": "multilingual",
    "entity_type": "taxonomy_term",
    "view_modes": [],
    "extra_fields": {
        "form": {
            "name": {
                "weight": "0"
            },
            "description": {
                "weight": "1"
            },
            "language": {
                "weight": "3"
            },
            "langcode": {
                "weight": "3"
            }
        },
        "display": {
            "description": {
                "default": {
                    "weight": "1",
                    "visible": true
                }
            }
        }
    }
}
field.bundle.taxonomy_term.multilingual.json
```

**Comment by indigoxela** [comment]
Ah, got it, that's `extra_fields` vs. `display`.

The hook does: `config_clear($config_name, 'extra_fields.display.language');` but not `config_clear($config_name, 'extra_fields.form.language');`

@laryn you asked for letting the display thing be a follow-up. But actually updated the display part, not the form(-display) part.

**Comment by laryn** [comment]
@indigoxela See if the latest changes in the PR get at what you mean.

**Comment by indigoxela** [comment]
> See if the latest changes in the PR get at what you mean.

Yes, works like a charm now. If I recall correctly, we decided to let the "always hidden language field display" thing be a follow-up. I don't think, we created that yet, is that correct?

**Comment by jenlampton** [comment]
The PR looks straightforward, thanks for working on this fix. RTBC from me.

**Comment by quicksketch** [comment]
I made one suggestion to the PR's update hook to work with config that has already been updated: https://github.com/backdrop/backdrop/pull/3606/files#r1038589658

**Comment by laryn** [comment]
@quicksketch Good idea, I merged that suggestion into the PR.

**Comment by jenlampton** [comment]
PR looks great with the suggested change.

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/3606 has been merged into 1.x and 1.23.x. Thanks @laryn, @indigoxela, @klonos, and @jenlampton!
