### ISSUE TITLE
Move node preview layout code into node module via new hook in layout module

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5067]
This is a follow-on to https://github.com/backdrop/backdrop-issues/issues/5018, to take on the longer-term plan outlined in [comment](https://github.com/backdrop/backdrop-issues/issues/5018#issuecomment-825210749), as determined during the development meeting on 4/22:

> Separately, I will proceed with long-term solution of adding hooks to layout module and moving node-specific code into node module implementation of the hooks.

This is under way, and I will post a PR when I have something ready to review.

Advocate: @bugfolder

**Comment by bugfolder** [comment]
This is a description of the changes made in [PR NNNN](). I'm putting them here rather than in the PR to preserve them in case the PR ends up needing to be rebuilt.

## Summary

* Add `hook_layout_layouts_alter()` and `hook_layout_contexts_alter()` to layout module.
* Document the hooks in `layout.api.inc`.
* Remove node-specific code from layout module and replace with hook instantiations `node_layout_layouts_alter()` and `node_layout_contexts_alter()`.
* Make sure hooks get called everywhere else they might apply (which includes dashboard module).
* Move node preview tests out of layout module tests and into node module tests.

## Rationale and details

Biggest question: why add two hooks, rather than just one? The reason is that two separate things need to be done to support node previews:

* Choose different layouts for certain paths;
* Alter contexts for some chosen layouts from the default setting of contexts.

These happen in different places in the code in `layout_get_layout_by_path()`, one outside a loop, one inside the loop. If we used only a single hook, then implementers would have to include the loop and duplicate all the code in the loop. Whereas with two hooks, the individual hook implementations can be small and tight. So two hooks it is.

One of the issues I considered was what should be the additional information passed in the `*_alter()` hooks. Should it be just the path, or something more? And if it is the path, should it be:

* the _system_ path (e.g., `node/%`)
* the _normal_ path (e.g., `node/1`)

I chose to pass the full router item because in `layout_get_layout_by_path()`, the router item already exists (so no extra cost) and the node preview logic needs information found in the router item: information from the normal path (specifically, information in `$router_item['map']`).

Also, implementers of these hooks may well want to use that additional information from the normal path.

(An alternative to passing the full router item would be to just pass the normal path itself. But then implementers needing that information (like the `1` in `node/1`) would have to parse the normal path, which could be done by calling `menu_get_item()`, which returns a router item, so we might as well pass the router item to begin with and save them the trouble.)

Now, the main place where the hooks are called is in `layout_get_layout_by_path()`, but they should probably be called anywhere that `layout_load_multiple_by_path()` is called, which happens in a total of four places in core.

(Another aside: if `$layouts = layout_load_multiple_by_path()` should always be followed by `backdrop_alter('layout_layouts', $layouts, ...)`, then should the alteration happen inside of `layout_load_multiple_by_path()`? No, because `layout_load_multiple_by_path()` only gets the system path as its argument, and hook implementers need the additional information found in the router item.)

Continuing. In core, the 4 places where `layout_load_multiple_by_path()` is called are:

1. `layout_get_layout_by_path()` in core/modules/layout/layout.module
    Get the layout which is active based on a path or router item.
2. `layout_page_callback()` in core/modules/layout/layout.pages.inc
    Menu callback; Generic page callback for all Layout-provided pages.
3. `dashboard_menu()` in core/modules/dashboard/dashboard.module
    Implements `hook_menu()`.
4. `dashboard_user_login()` in core/modules/dashboard/dashboard.module
    Implements `hook_user_login()`.

The first place is the "main" implementation, part of the rendering pipeline for module-provided pages, which is called for (almost) every page load.

The second place is part of the rendering pipeline for layout-provided pages. Since we want consistent behavior for module-provided and layout-provided pages, both hooks need to be called here.

But this presents a small problem, because the hooks require the full router item. 

In `layout_page_callback()` we could get the router item from `get_menu_item($normal_path)` if we had the normal path, but we don't; `$menu_item->path` is a system path, not a normal path. But `$args` contains the elements of the normal path, so we can reconstruct it and then use `get_menu_item()` to obtain the router item for our two calls to `backdrop_alter()`.

The last two places to check for `layout_load_multiple_by_path()` are the two implementations in the dashboard module. Both functions deal with the specific path `admin/dashboard`. Do we need to call our hooks there?

Sure. A hook implementer might want to use a different layout for the dashboard based on some criteria that can only be expressed in code. (Even though the existing contexts and visibility conditions already provide a lot of flexibility to do that). So we need to call our hooks there. Fortunately, since the code deals only with the specific path `admin/dashboard`, we can get our router item from `get_menu_item('admin/dashboard')`.

So, now we've incorporated our hooks everywhere they'd be needed in core.

What about possible effects on contrib modules?

If a contrib module did its own tinkering with layout and used `layout_load_multiple_by_path()`, they'd likely need to upgrade their module to add the calls to `backdrop_alter()` for the two hooks. This is important enough that we might consider mentioning it in the release notes.

One module that will be hugely affected is Layout Wildcard, which replaces the entire layout-choosing call chain, starting with its own route handler, and so it has had to track changes in several core routines in its own copies of those core routines. Now all that code duplication can be thrown away; instead, LW can do its thing just via implementation of these two new hooks. (And, incidentally, LW needs the extra information stored in the router item, so that's another point in support of passing the full router item in the hook calls.)

What happens if someone upgrades core with these changes but doesn't upgrade the corresponding update to Layout Wildcard? Older versions of LW won't call the new hooks, so any functionality provided by those hooks (like proper layouts for node preview pages) won't happen. Since proper layout for node preview pages wasn't happening anyway for core versions older than 1.18.3, this doesn't seem too bad. And presumably, anyone updating core is also likely to do bugfix updates of their modules as well.

Conversely, what happens if someone upgrades a new version of LW but not the version of core that incorporates these changes? Since all the functionality of LW will in the future rely on the hooks, LW would totally break. So when LW upgrades, it needs to include a minimum core version in its dependencies. (It did this once before for [version 1.x-1.2](https://github.com/backdrop-contrib/layout_wildcard/releases/tag/1.x-1.2).) Since we can't explicitly require minor versions of Backdrop core, it will have to be handled by `hook_requirements()` or something like that.

**Comment by klonos** [comment]
Wow! Thanks for your work in this cleanup @bugfolder, and thanks for time/effort/energy spent on documenting/explaining things that thoroughly! 🙏🏼

**Comment by bugfolder** [comment]
I'm not out of the woods yet; automated tests are failing, and I can't yet figure out why. So we'll hold off on the balloons for now. (I'll update the PR "fixes," thx for the note.)

**Comment by docwilmot** [comment]
Curious that the PR doesnt actually remove the special-casing Node code in `layout_get_layout_by_path()`? Will that be done later?

**Comment by bugfolder** [comment]
Grrr, well, it was supposed to be there. Appears that got lost in the shuffle of trying to merge and rebase with other commits to 1.x. It's back in the latest update to the PR.

But I'm having second thoughts about passing $router_item. All the reasons I gave above are applicable; but one of the testing errors was because `layout_get_multiple_by_path()` was getting called in `dashboard_menu()`, and calling `get_menu_item()` from inside of a `hook_menu()` implementation can lead to infinite recursion (because `get_menu_item()` could rebuild the menu, which calls `hook_menu()` implementations). So I want to ponder this further. It may be safer to go back to passing the normal path.

**Comment by bugfolder** [comment]
And one more tweak added: the previous version of `layout_get_layout_by_path()` statically cached its result based on the system path (`$router_item['path']`). But the layout for a given system path might vary due to visibility conditions resulting from contexts. So I've changed the caching to be based on the normal path (`$router_item['href']`).

**Comment by bugfolder** [comment]
## More changes

After an extensive Zulip discussion with @**docwilmot**, we came up with a modified approach that adds only a single hook, `hook_layout_layouts_alter()`.

One of the important considerations for the addition is that we are not **just** moving the layout alterations for node preview pages into the node module without messing up any existing behavior (though we certainly want to accomplish that); we are also creating a API for client modules to use if they wish to alter the layouts used to display pages—for example, using the same layout on pages that have very different paths (something not currently possible with core). An illustrative case would be the Layout Wildcard module, which currently achieves its goals by inelegantly duplicating the menu handling call chain in Layout module. Ideally, it should be able to accomplish its current behavior simply by implementing this hook. And, perhaps, implementing more fine-grained behavior as well in the future.

And if features of Layout Wildcard or some other contrib module eventually get moved into core (as some have expressed an interest in), ideally, this hook would provide a graceful way of doing so.

So, this new approach does (I think) accomplish all of that.

I should mention a principle I assumed, based on the observation that there are layout-created pages (whose page callback is `layout_page_callback()`) as well as "regular" module-created pages (everything else in the menu router table). It seemed like if we are creating a way for developers to modify what layouts are used for regular pages, for consistency's sake, they should be able to modify the layouts used for layout-created pages in the same way via the same hook. So the mechanism for choosing layouts and invoking the hook needed to be the same in both cases. The practical effect of that is that the choice of layout (and hook invocation) always happens via the function `layout_get_layout_by_path()`, which is now used for both cases (rather than separate-but-equivalent blocks of code as before). But that necessitated adding another variable to `layout_get_layout_by_path()` and giving it a default value so that existing usage of that function doesn't get broken.

Let me also explain one documentation change. In the previous version of layout module, there is a check to see if `LayoutContext::data` has been loaded by checking to see if its value is an object (e.g., Node, User). This is currently the case for all core LayoutContext subclasses that have a load callback, so that is currently a safe assumption. However, if a contrib module implements their own LayoutContext subclass context with a load callback that returns a non-object (e.g., it transforms one string into another string), that would break this check (even in the current code). The new code relies on using the same check. So I have added to the documentation of `hook_layout_context_info()` the requirement that the load callback must return an object for LayoutContext subclasses that might be created in the future.

**Comment by indigoxela** [comment]
I really like that elegant single-hook approach. I'll try to play with the new PR soon.

@bugfolder and @docwilmot many thanks for working on it.

**Comment by klonos** [comment]
Thank you for the detailed description of the solution you have agreed to go forward with @bugfolder 👍🏼

**Comment by indigoxela** [comment]
Not sure if this is useful testing... :smile: 

I created two layouts with path `node/%`. To distinguish them, I added custom blocks with some text.

Then I created a custom module with this minimal hook implementation:

```
<?php
function custom_layout_layouts_alter(&$layouts, $router_item) {
  $map = $router_item['map'];
  if ($map[0] == 'node' && is_object($map[1])) {
    $node = $map[1];
    if ($node->type == 'post' && $node->promote == TRUE) {
      // Switch from node_custom to node_custom_two.
      unset($layouts['node_custom']);
    }
  }
}
```
Seems to work as expected. 
All nodes get the 'node_custom' layout except for promoted posts, which get 'node_custom_two'.

So, works for me - but for sure needs more testing.

**Comment by indigoxela** [comment]
@bugfolder Both of your PRs are still open, which could be a bit confusing for testers. Mind to close the first (replaced) one?

**Comment by indigoxela** [comment]
Oh, I should note: I also tested the actual node preview solution in the sandbox - works like a charm. :+1:

**Comment by bugfolder** [comment]
@indigoxela yes, old PR is closed. Thanks for testing!

**Comment by quicksketch** [comment]
I did a code review and this looks great! I really appreciate your attention to detail @bugfolder and the work put in to expand the documentation.

The only major suggestion I have is that the hook should be renamed to clarify when it is getting called. See the PR for my suggestion and reasoning. https://github.com/backdrop/backdrop/pull/3618#pullrequestreview-680270792

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/3618 has been updated by @bugfolder and is ready for another round of review it seems.

**Comment by quicksketch** [comment]
After a few more grammatical fixes in the code comments, I think the PR at https://github.com/backdrop/backdrop/pull/3618 is ready to go.

**Comment by quicksketch** [comment]
Okay, thanks folks I finally merged this into 1.x for 1.20.0! Thanks @bugfolder for your work on this! Thanks @indigoxela, @docwilmot, and @klonos for the additional reviewing and feedback!
