### ISSUE TITLE
Admin bar CSS doesn't scale well with bigger font size

### ISSUE THREAD

**Issue by rudiedirkx** [backdrop/backdrop-issues#507]
Some people (me) need a bigger font than 11px, or 13px. You can tell the browser to take 18px (my fav) as minimum always. It breaks a lot of things, because people don't use `px` and `em` well. Same in Seven.

The `margin-top` (always 30px) is too little so the page's contextual link hardly shows:

![screen-backdrop-adminbar-pre](https://cloud.githubusercontent.com/assets/168024/5551203/53129cf2-8bc1-11e4-80cc-4b3b380e5f79.png)

With fix, using `em` instead of `px`, it does:

![screen-backdrop-adminbar-post](https://cloud.githubusercontent.com/assets/168024/5551204/5312f9d6-8bc1-11e4-9f1f-32d0a61489ca.png)

Another thing: the `margin-top` should be `padding-top`, because with `margin-top` every page is more than 100% high, which always adds a scrollbar. Difference visible in screens.

I also removed the `!important` because it's unnecessary and a subtheme might want to override it.

**Comment by quicksketch** [comment]
I filed a new PR at https://github.com/backdrop/backdrop/pull/624 that leaves the font size as-is but adjusts a lot of the other padding/margins to take into account the font size. Could you try applying it from https://github.com/backdrop/backdrop/pull/624.patch and see if it meets your needs?

**Comment by quicksketch** [comment]
Hm, I can't get the styling consistent between Chrome and Firefox. It seems like Chrome's definition of an `em` is rendered 1px differently than Firefox's. :P

**Comment by BWPanda** [comment]
Is this still an issue with all the changes to Backdrop and even browsers in the last 5 years?

Rather than wait for an answer that may not come, I'll just close this as outdated, but if anyone finds this is still an issue today feel free to reopen.
