### ISSUE TITLE
Layout save doesn't properly save context

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5072]
Saving a Layout on which you've set a context doesn't always save the context properly.

This can be demonstrated with the attached module, which creates pages at two paths: `demo-1/%node` and `demo-2/%`. Both pages expect the path placeholder to be a valid node nid, and both pages properly handle the case where it's not.

[demo.zip](https://github.com/backdrop/backdrop-issues/files/6392286/demo.zip)

To reproduce the bug:

1. Enable the module.
2. Go to Layouts. Click "Add Layout."
3. Give it a name; choose a template; and give it the path `demo-1/%`.
4. A context automatically appears for position 2. Choose "Node".
5. Click "Create Layout."
6. Select tab "Configure Layout". Look at the context.

Expected result: it should be of type "Node", like we set in step 4.

Actual result: it is set to "String pass-through."

You can try setting it to type "Node" again, but it won't be saved.

Verified behavior on 1.18.3 and 1.x.

**Comment by bugfolder** [comment]
I just checked this against 1.x after the flurry of PR mergings of 2021-05-03, and am not seeing the problematic behavior any more. Hooray! 

(I suspect it got fixed as a side effect of adding Relationships to contexts per https://github.com/backdrop/backdrop-issues/issues/2134 via https://github.com/backdrop/backdrop/pull/3611.)

**Comment by bugfolder** [comment]
Yes, this is definitely fixed in 1.19.0-preview.

**Comment by klonos** [comment]
Lets close this one then :) ...anyone still able to reproduce this should feel free to reopen.
