### ISSUE TITLE
Fix layout action links so additional links can be added to the list.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5074]
**Description of the bug**

There seem to be two `UL` tags with the class `action-links` being added to the page, rather than two links in the same list: 

<img width="1057" alt="Screen Shot 2021-05-02 at 6 49 21 PM" src="https://user-images.githubusercontent.com/397895/116835637-35162100-ab78-11eb-8ea6-3dd0ee7d1003.png">

This is happening because both links fake the action-links `UL` by adding it with prefix and suffix:
```
'#prefix' => '<ul class="action-links"><li>',
'#suffix' => '</li></ul>',
```

This makes it impossible to add a second item into the action-links list.

**Comment by jenlampton** [comment]
I'm working on adding a new theme function, `theme_layout_action_links()` that will allow us to use it in a renderable array.

**Comment by quicksketch** [comment]
Review posted to https://github.com/backdrop/backdrop/pull/3615#pullrequestreview-650072131

**Comment by indigoxela** [comment]
@jenlampton was there a special reason to put this in milestone 1.19.0 instead of 1.18.4? This rather looks like a bugfix than a new feature.

**Comment by jenlampton** [comment]
@indigoxela the current PR changes the relationships feature that went into 1.19.0, where I noticed it, which is why it was a follow-up to that one. We could add it into 1.18.4 also, but then it would take a smidge more work.
