### ISSUE TITLE
Backdrop 1.19.0-preview Release

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5078]
Scheduled for May 3, 2021 6-10pm PT

## Pre-release tasks

- [x] Merge commits (quicksketch)
- [x] Create a new minor release milestone (quicksketch)
- [x] Move all unfinished issues to the next minor release milestone (quicksketch)
- [x] Draft Release notes (quicksketch)
  - [x] Include a short, descriptive summary of the release, for example:
    - This is the preview release of Backdrop 1.16.0. Please use this version if you would like to help us test the features in the new version of Backdrop prior to the official release on January/May/September 15th, 20xx.
  - [x] Include a section containing **Notes for updating**
    - [x] Note if any changes were made to files outside the `core` directory, for example:
      * No changes have been made to the `.htaccess`, `robots.txt` or default `settings.php` files in this release. Updating customized versions of those files is not necessary.
    - [x] Note if updates (update.php) needs to be run, for example:
      * Use the text "The database update script does **not** need to be run."
      * or "It will be necessary to run the update script (located at /update.php) for this release."
  - [x] Include changelog since last version:
      * navigate to [Actions](https://github.com/backdrop/backdrop-issues/actions)
      * Select the most recent time "Release Notes Generator" has been run.
      * Download the `release-notes` artifact attached to the generator.
      * Unzip the file, and copy/pate contents into release notes draft.
      * Re-word issue titles to indicate that the problems have been fixed.

## Pre-release Publicity + documentation tasks

- [ ] Review issues for new features @jenlampton 
  - [x] Update the issue title (Bugs should start with `Fix` or `Fixed`, new features with `Added` or similar)
  - [x] Add `Documentation` label if the feature needs to be documented (or needs docs to be updated)
  - [ ] Add a conclusion suitable for blog post + release notes
- [ ] Draft blog post for release on the 15th @todo? 
- [ ] Draft roadmap updates for backdropcms.org @klonos 
- [ ] Create new forum topic for feedback on the release @stpaultim

## Release tasks

- [x] Update bootstrap.inc with version number (@quicksketch)
- [x] Tag for release, and push tag to GitHub (@quicksketch)
- [x] Branch for new minor number (e.g. `1.10.x-preview`) and push to GitHub (@quicksketch)
- [x] Revert version number back on 1.x branch with minor number increased (e.g. `1.11.x-dev`) (@quicksketch)
- [x] Revert version number back on new minor number branch (e.g. `1.10.x-dev`)(@quicksketch)
- [x] Create release notes on GitHub (@quicksketch)

**Comment by quicksketch** [comment]
Closing this issue as we're doing the final release today: https://github.com/backdrop/backdrop-issues/issues/5088

**Comment by jenlampton** [comment]
okay, I copied all unfinished items over to the official release issue.
