### ISSUE TITLE
[D8] Add crop anchor option to Scale and Crop image effect

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5080]
This is the equivalent of https://www.drupal.org/project/drupal/issues/1252606 which was introduced in Drupal 8.6.0 ([change record](https://www.drupal.org/node/2972030)).

Before:

![image](https://user-images.githubusercontent.com/2423362/117315888-c6dfa000-ae90-11eb-9892-be5d4ad0c48c.png)

After:

![image](https://user-images.githubusercontent.com/2423362/117315904-cba45400-ae90-11eb-9058-de8ad23b77bf.png)

**Comment by klonos** [comment]
...we already have #4489 and #1774, but these issues seem rather harder to implement or at least will most likely take longer, since we'd be implementing things from scratch. Perhaps backporting the D8 implementation will take less effort/time, and at the same time we'd provide feature parity and familiar UI.

**Comment by klonos** [comment]
Turns out that there was intention to backport this to D7, but was blocked because of string changes (🙄 )... the D7 patch has been tested by a few users, who reported it to be working as expected. I created a PR based on [that patch](https://www.drupal.org/project/drupal/issues/1252606#comment-8305805): https://github.com/backdrop/backdrop/pull/3619

**Comment by herbdool** [comment]
Makes sense to me. I've tested and reviewed. Looks all good.

**Comment by quicksketch** [comment]
Thanks @klonos and @herbdool! https://github.com/backdrop/backdrop/pull/3619 looks great to me. I don't think this requires a change record, since it's only an API addition, not a change. I did add a `@since 1.21.0` docblock line however. I merged this into 1.x for 1.21.0.
