### ISSUE TITLE
[UX] Reduce Update Status module's nagging messages on admin/* pages

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5083]
**Description of the need**

The Update Status module displays error messages on all administrative pages when security updates are available, such as on the /admin/modules page:

![image](https://user-images.githubusercontent.com/100206/117556581-47cca200-b01f-11eb-847c-cf741cded61f.png)

This behavior has been in place since Backdrop 1.0, something we carried over from Drupal 7.

---

Backdrop now has several other places where administrators are notified of updates, including:

1. The admin toolbar Notification icon (from #639)
![image](https://user-images.githubusercontent.com/100206/117556619-aa25a280-b01f-11eb-8810-96e3cdc73a34.png)

2. The admin dashboard:
![image](https://user-images.githubusercontent.com/100206/117556627-c295bd00-b01f-11eb-8eae-1183e42a2d1b.png)

3. The status report:
![image](https://user-images.githubusercontent.com/100206/117556638-d6d9ba00-b01f-11eb-90e0-7f0c1454feff.png)

4. And the new unified updates page added in https://github.com/backdrop/backdrop-issues/issues/2714
![image](https://user-images.githubusercontent.com/100206/117556653-05579500-b020-11eb-9cc6-75052a3e3940.png)

And although we are working on fixing some performance impacts caused by Update module in https://github.com/backdrop/backdrop-issues/issues/5046, displaying these messages requires that Update module perform relatively expensive comparison operations that can cause admin pages to slow down dramatically. We could further eliminate expensive processing on random administrative pages if we were to stop showing these messages. Instead we could relegate regenerating the available updates list to more predictable locations, such as the status report and on cron jobs.

**Proposed solution**

Remove the nagging messaging Update module currently displays on all `/admin/*` pages, instead allow other existing update mechanisms (email notifications, Twitter, the [Backdrop Security feed](https://backdropcms.org/security/), the notification dot, status report, and dashboard) be considered adequate notification of security updates.

**Alternatives that have been considered**

* None yet.

---

PR: https://github.com/backdrop/backdrop/pull/3638

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/3638 that makes this change.

I couldn't see any other changes necessary to `hook_cron()` or `hook_requirements()`. Seems as though just removing `hook_init()` is really all that is needed here.

Testing this on a sandbox isn't very viable, you may need local testing to simulate having installed old versions of modules or core to trigger the update status requirements.

**Comment by indigoxela** [comment]
Interesting - and sooo silent.

I tested locally by applying the patch, then installed an outdated module (webform 1.x-4.20.1), ran cron.

- The red dot in the admin menu appeared as expected.
- No messages at all - to be honest, that was a bit irritating. At least, unfamiliar.

Do we want Backdrop to be *that* silent? Or do messages on certain pages make sense (which ones)? I agree, that the current "haunting with messages throughout the admin pages" isn't the best solution, but no messages at all also feels odd - maybe just because I'm used to the "haunting" for so many years now. :grin: 

BTW some related tests (that check for the messages) still need an update or removal, they're currently failing.

**Comment by olafgrabienski** [comment]
> No messages at all - to be honest, that was a bit irritating.

Even not in the status report? That's the place where I'd expect such messages.

**Comment by indigoxela** [comment]
> Even not in the status report?

The status page does show the pending security update, of course, but no messages above.

Here's a screenshot from the sandbox:

![status-page-warning](https://user-images.githubusercontent.com/842066/120176216-4ef26480-c207-11eb-83ba-b13081f62f87.png)

**Comment by olafgrabienski** [comment]
> The status page does show the pending security update, of course, but no messages above.

Thanks for sharing the screenshot! In my opinion, the notice about the pending security update is enough.

**Comment by klonos** [comment]
I could get used to this, but my issue with showing this only via the red dot in the admin bar is that the core Administration Bar module can be disabled. Admittedly, this would be an odd case, and people would most likely replace the core module with something like https://github.com/backdrop-contrib/navbar, which also supports the red dot indicator.

**Comment by indigoxela** [comment]
> I could get used to this, ...

That sounds a bit like you "could resign to it". :smirk:

I agree, having *only* the red dot could be a bit too silent. And the change compared to the current behavior might be a bit too radical. Most D and B users are used to the nagging - at least, I am.

Where are those messages essential? On which pages do people expect them to appear? All admin pages? Some admin pages?

**Comment by jenlampton** [comment]
I think this may have just become urgent. See related https://github.com/backdrop/backdrop-issues/issues/6077

**Comment by stpaultim** [comment]
I don't have a site to test this on, but I think I would appreciate it if the nagging were reduced a bit. I'm sure this PR would need rebasing.

**Comment by quicksketch** [comment]
Yay, one of my favorite peeves might get some traction :smile:

I rebased the PR to give it a fresh sandbox.

**Comment by stpaultim** [comment]
Is there anyway to simulate a website that needs a security update in the PR sandbox, or do I really need to apply this to a local site to see the effects. @quicksketch

**Comment by quicksketch** [comment]
I don't have any good suggestions there @stpaultim. You could probably use Devel module to execute PHP to download an insecure module. Backdrop doesn't provide any mechanisms for downgrading.

**Comment by quicksketch** [comment]
I updated the PR to remove the test coverage for checking the messages. It's now 100% passing.

**Comment by klonos** [comment]
I have installed and tested this on my local, and things work as expected, with the exception of a thing that is actually pre-existing. I've filed #6482 to address that separately.

The code changes look good too (code reduction++), so this is RTBC 👍🏼

**Comment by klonos** [comment]
@indigoxela I've also raised #6483, which I think will somewhat address some of your concerns (even if partially).

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3638 into 1.x and 1.27.x. Yay, glad to see this old issue resolved. Thanks @klonos, @indigoxela (even playing the disapproving role), @stpaultim, @jenlampton, and @olafgrabienski.
