### ISSUE TITLE
Problem with Backup and Migrate Module - conflict with 1.19.0

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5096]
**Description of the bug**

The changes to Backdrop 1.19 seem to have uncovered a bug in the Backup and Migrate module. 
https://github.com/backdrop-contrib/backup_migrate/issues/63

This bug in the module has already been fixed and released. However, I've found that this bug maybe causing errors that are not obviously connected to Backup and Migrate. For example, I tried to enable the HoneyPot module on a site and got an error message. 

It very much appeared to me that the problem was with the HoneyPot module and I spent time trying to debug this problem before realizing that this problem was being caused by Backup and Migrate. 

https://github.com/backdrop-contrib/honeypot/issues/33

While this may not be a core issue, I am concerned that a core update may be causing Backup and Migrate to break peoples sites in ways that might not be obviously caused by Backup and Migrate (although I could be wrong here). 

Given that Backup and Migrate is the most popular contrib module with over 650 reported installations, do we need to do either of the following:

1) Issue some kind of notification warning users that they need to upgrade Backup and Migrate module if they use 1.19. 

Or

2) Release 1.19.1 with some fix that remediates the problems with Backup and Migrate. 

Or 

3) Assume that users that update Backdrop Core after today will also be updating Backup and Migrate, just because they see it's available, and that this won't be an issue moving forward?

---

Edited by @olafgrabienski: Closed in favor of #5094

**Comment by stpaultim** [comment]
I just tried to edit a view on another site with 1.19 (where i had not yet updated Backup and Migrate) and the entire site is now crashed. As a site admin, I'm not sure that there is any obvious indications that updating Backup and Migrate would solve this problem, unless I find one of the mentions of this problem in the forum or here.

**Comment by indigoxela** [comment]
@stpaultim are you aware of this issue? https://github.com/backdrop/backdrop-issues/issues/5094

**Comment by indigoxela** [comment]
Hm. Can we close this issue as duplicate?

**Comment by olafgrabienski** [comment]
> Can we close this issue as duplicate?

I think so. Closing in favor of https://github.com/backdrop/backdrop-issues/issues/5094.

**Comment by stpaultim** [comment]
@indigoxela - Sorry, I did not see your issue (not sure how I missed it).
