### ISSUE TITLE
Backdrop 1.19 no longer has direct calls to PDO methods

### ISSUE THREAD

**Issue by quackers8me** [backdrop/backdrop-issues#5100]
Due to a issue with the backup_migrate module restore function https://github.com/backdrop-contrib/backup_migrate/issues/64
it does not appear that there is a way to make a native prepare() call to allow for excluding substitution of, for example, braces

The D7 dev branch of database.inc has this call and I'm wondering why it wasn't included in B 1.19's version?

 /**

   ** Proxy possible direct calls to the \PDO methods.
   **
   ** Since PHP8.0 the signature of the the \PDO::query() method has changed,
   ** and this class can't extending \PDO any more.
   **
   ** However, for the BC, proxy any calls to the \PDO methods to the actual
   ** PDO connection object.
   **/
`
  public function __call($name, $arguments) {
    return call_user_func_array(array($this->connection, $name), $arguments);
  }
`

**Comment by quicksketch** [comment]
Thanks for filing this issue. We already have an issue at https://github.com/backdrop/backdrop-issues/issues/5094 that tracks this same problem. Could we join over there?
