### ISSUE TITLE
Allow autocomplete on CKEditor image insertion

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5102]
**Description of the need**

I had a few minutes and was going to start puzzling over https://github.com/backdrop/backdrop-issues/issues/3293 and this line in the code jumped out at me in the image form in CKEditor:

>   // Use a "textfield" rather than "url" to allow relative paths.

I thought about @BWPanda's great solution for autocomplete textfields and wondered how easy it would be to repurpose for images. Turns out very easy!

**Proposed solution**

PR https://github.com/backdrop/backdrop/pull/3631 (copies the pattern in @BWPanda's `path-autocomplete` solution)

**Comment by laryn** [comment]
![image-autocomplete](https://user-images.githubusercontent.com/871421/119229156-2c13d200-badc-11eb-8598-5ab9d7464926.png)

**Comment by laryn** [comment]
Maybe it would be good to use the space after the filename _(where it currently says "(File: Images)")_ to show the uploaded date instead (and sort by uploaded date with newer files first) -- anyone have thoughts on that?

**Comment by laryn** [comment]
What would be amazing would be if we could begin to filter the image library on the right at the same time as the autocomplete results began to show up...

**Comment by olafgrabienski** [comment]
Nice, looks very promising, and the PR works for me!

One thought: ​I guess for most people it won't be clear that the field is an autocomplete and can be used to filter existing images. Maybe we can add a description, something like `Start typing to get suggestions from the library.`

Regarding the space after the filename, I like the idea showing the date and sorting by it. Will it be possible to change / localize the date format?

That said, there isn't necessarily enough space after the filename (see example below). Should we trim the file name in this case, so that the date remains visible?

<img width="453" alt="backdrop-pr-3631-autocomplete" src="https://user-images.githubusercontent.com/14188307/119233919-71132500-bb2b-11eb-983a-9a0a12ad88d1.png">

**Comment by olafgrabienski** [comment]
Out of curiosity: would the approach also work for image fields?

**Comment by klonos** [comment]
Great idea @laryn! 👍🏼 

> Maybe it would be good to use the space after the filename (where it currently says "(File: Images)") to show the uploaded date instead...

Yeah, the the "File: Image" bit provides no real value when selecting a file in the "Insert image" dialog - all results will be images (plus we also show the file extension, which I am assuming is enough for most people to tell the file type). I think that the use case of people having added a file and then wanting to embed it is the most common one, so sorting by most-recently-uploaded makes sense to me. Wonder what others think.

> What would be amazing would be if we could begin to filter the image library on the right at the same time as the autocomplete results began to show up...

Yeah, I was looking at the way we do that in the modules listing page the other day with the "Search..." field at the top. We use a combination of `text` and `table-filter-text-source` classes + some JS to filter by the text contained within any HTML tag that contains matching words. On the modules page we need to filter by module name/description/tags/dependencies, but here there'd be only the file name, so should be easier.

> Should we trim the file name in this case, so that the date remains visible?

@olafgrabienski I think that in the context of this dialog, the filename is more important. There may be files with the same prefix, but different ending bits that get trimmed out, and people won't be able to tell which file is which. I think it'd be better allow the width of the results list to exceed the width of the field.

**Comment by olafgrabienski** [comment]
> There may be files with the same prefix, but different ending bits that get trimmed out

Indeed, was also thinking about it, and allowing to exceed the width sounds like a good alternative.

Btw, my Mac trims the center instead of the ending of file names (see below). Is this possible in PHP?

<img width="300" alt="mac-os-trim-filename" src="https://user-images.githubusercontent.com/14188307/119235124-3613f000-bb31-11eb-8efb-46fb5ca87594.png">

**Comment by klonos** [comment]
> Is this possible in PHP?

@olafgrabienski I'm sure there is a way to do it, but we'd still have the same issue. For example in the screenshot you provided in your last comment, the dimensions could be at the very end of the filenames (after the image number), which would lead to the same problem of not being able to tell which image is which.

Allowing image thumbnails in the dropdown with the results would be a nice-to-have, and would somehow make the issue with similar names slightly less of a problem (for sighted users at least). That's a separate feature request though 😄 

> Out of curiosity: would the approach also work for image fields?

We'd need to add the field to the dialog we've added in #3297 🤔

**Comment by laryn** [comment]
Thanks @olafgrabienski and @klonos. I just pushed additional changes -- are you willing to test again? 

@elmuche I'd love to get your testing on this one as well as I may have solved https://github.com/backdrop/backdrop-issues/issues/3293 at the same time!

**Comment by laryn** [comment]
Other notes:

 - Not yet added: field description "Start typing to get suggestions from the library"
 - Not yet implemented: What to do if the autocomplete line is longer than the available width? Trim the filename somehow? Allow the width to go beyond the field's width?
 - RE: file fields, with the latest version there is an exposed filter in the file field library implementation -- perhaps that is enough?
 - Date format -- currently it's using the "Short" date format, so whatever is defined by the user for that format should be used.

**Comment by herbdool** [comment]
Looks like you'd need to do json_decode and then the data element has some html in it.

**Comment by olafgrabienski** [comment]
> additional changes -- are you willing to test again?

Looks promising! Below is a screenshot of the current state. I guess the main change is the `Filename` field and how it works together with the autocomplete: When I type something in the autocomplete, the same string gets applied to the `Filename` field and filters the images respectively.

![backdrop-pr3631-autocomplete-b](https://user-images.githubusercontent.com/14188307/119627080-25eb6180-be0c-11eb-8f66-b246f75c54e8.png)

**Comment by laryn** [comment]
Here's a 2min screencast of the current version. Still hoping for more feedback and maybe a boost on the Ajax Delivery callback...

https://vimeo.com/555256951

**Comment by laryn** [comment]
So I played around and ended up making my own delivery callback that only contained:

`print backdrop_render_page($page_callback_result);`

However, the strange style issue (where Basis styles get pulled in when the image library is clicked/loaded) occurs just the same. **Anyone have any ideas on what is causing that?**

**Comment by docwilmot** [comment]
Thinking, maybe the new path `filter_image_library_ajax` isnt an admin path so its bumping off the admin theme? Change to `admin/filter_image_library_ajax` and see? Or implement `hook_admin_paths()` for it?

**Comment by laryn** [comment]
@docwilmot Thanks! That may have done it for the style issue. I'm sure there are still other rough edges so anyone interesteed feel free to try again.

Not yet implemented pending more feedback:

 - Field description "Start typing to get suggestions from the library"
 - What to do if the autocomplete filename line is longer than the available width? Trim the filename somehow? Allow the width to go beyond the field's width?

**Comment by docwilmot** [comment]
TBH I think `admin/filter_image_library_ajax` seems neater then the hook, but glad it worked. Also, having both the autocomplete and the filter textfield seems like overkill to me. Is the a case where a file would exist that wouldnt be found on autocomplete but would need the filter? Or vice versa?

**Comment by laryn** [comment]
Removing the autocomplete (ie. closing this issue and going back to just https://github.com/backdrop/backdrop-issues/issues/3293 is definitely an option at this point, I think. Do others agree?

I did the hook instead of the `admin/` path because I was thinking of people that may not be administrators but have permission to add content on the front end. (ie. non-admins accessing an `admin/` path could seem insecure) But maybe that's not a valid concern since they wouldn't ever see the actual path since it's loaded by Ajax...

**Comment by docwilmot** [comment]
Actually, rethinking, it may not really be a problem to keep the autocomplete: if a user knowns which file they want, may be faster. The JS copying of the filename is definitiely not needed, I think. I dunno. I think the exposed filter is more useful since you'd actually see the image results. Wonder what others think?

Also minor: we tend to use dashes usually for paths, so `admin/filter-image-library-ajax` not `admin/filter_image_library_ajax`

**Comment by olafgrabienski** [comment]
> Removing the autocomplete [...] is definitely an option at this point [...] Do others agree?

> I think the exposed filter is more useful since you'd actually see the image results. Wonder what others think?

I think I agree, also because the exposed filter applies to the file field as well.

**Comment by quicksketch** [comment]
The big problem previously was that the AJAX within the view did not work. By some change you made in the PR, the view AJAX filtering now works perfectly. I even tried adding a new filter to the view for "File ID", and that works as well. Same with the Pager. Great job fixing that!

I agree that we should probably nix the auto-complete field. Having two fields that effectively do the same thing is confusing. Also this allows for more flexibility where a developer could configure the media browser in any way they wanted and we're not tying the configuration so tightly to the core code.

I posted some additional feedback in https://github.com/backdrop/backdrop/pull/3631#pullrequestreview-680307254

Great job @laryn!

**Comment by laryn** [comment]
@quicksketch I took your feedback and will incorporate it into a PR in the original #3293 -- I'll close this issue which is technically about autocomplete (which everyone seems to agree is not needed if the views exposed filter works).
