### ISSUE TITLE
[SR][D7][D9][WP] Add Permissions-Policy header to block Google FLoC

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5103]
Although there exists [a contrib module for this](https://www.drupal.org/project/flocblock) that we could port to Backdrop, it seems that our Drupal brethren have decided to take action in core:

- D7: https://www.drupal.org/project/drupal/issues/3209976 ([commit](https://git.drupalcode.org/project/drupal/-/commit/eb66609d55ae8e0e70186550a70bd5d73982e783))
- D9: https://www.drupal.org/project/drupal/issues/3209628 (fixed in 9.2.0-beta1 - [change record](https://www.drupal.org/node/3213197))

This has been raised as a concern in our forum already: https://forum.backdropcms.org/forum/floc

**Comment by indigoxela** [comment]
OMG, the data :octopus: strikes again... "FLoC is a part of the Chrome browser’s source code and it helps them do cookie-less and consent-less ad targeting."

Further reading:
- https://plausible.io/blog/google-floc
- https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea

I vote for getting this into Backdrop core.

**Comment by herbdool** [comment]
Sounds like WordPress will also be adding the header.

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/3635

Draft change record for Backdrop: https://docs.backdropcms.org/change-records/header-added-by-default-to-disable-floc

**Comment by jenlampton** [comment]
Code looks good, but still needs testing. Not likely for 1.19.1.

**Comment by quicksketch** [comment]
I supposed technically this may be an API change, but considering FLoC is so new and is very likely not going to be a desirable default behavior, enabling this in a bug fix release seems fine.

The implementation all looks really good to me. I made a minor edit to the change record to provide an example settings.php value.

**Comment by quicksketch** [comment]
I posted a minor request that the new tests use the `testing` profile instead of `standard`: https://github.com/backdrop/backdrop/pull/3635#pullrequestreview-669694167

**Comment by klonos** [comment]
Thanks @jenlampton ...I've merged the change @quicksketch proposed, so you might wanna do a follow-up CR when you have the time (unless anyone else has the capacity to do it before you get to it).

> I supposed technically this may be an API change, but ... enabling this in a bug fix release seems fine.

Yeah, my rationale exactly. The Chrome version that introduced this privacy-invasive "feature" has been out since March, so I thought that we may want to provide Backdrop site owners with the means to protect the privacy of their site visitors as soon as possible.

**Comment by indigoxela** [comment]
Some local testing. I applied the changes and ran update.php.

Opened the browser developer tools and inspected the network analysis result - header was there.

![screenshot-response-header](https://user-images.githubusercontent.com/842066/119846009-0b97ad80-bf0a-11eb-9294-ca66ff70aef9.png)

Then I set `$config['system.core']['block_interest_cohort'] = FALSE;`, another request, checked again - header was gone. :+1: 

I also checked against https://securityheaders.com/ (I can make my dev webs publicly available if I need) - they also recognized the header.
Works for me.

**Comment by indigoxela** [comment]
Another note on the actual problem we're trying to solve: I don't think we can. It's just a http header, Google is free to ignore it if they decide to at some point.

I still belief, we should do it. IMO the whole concept of "personalized ads" - an euphemism for prejudice as a business model - is the wrong way.
We can't stop them doing it, but we can send clear signals, that we disapprove. And the more Open Source projects (web CMS or other) are aboard, the sooner they might figure out that people really mean it: stop fingerprinting, stop making products out of us.

**Comment by BWPanda** [comment]
> FLoC is being developed as a part of Google's Privacy Sandbox initiative...

(Source: https://en.m.wikipedia.org/wiki/Federated_Learning_of_Cohorts)

A privacy initiative by Google is an oxymoron, IMO.

I'm glad to read:

> As of April 2021, every major browser aside from Google Chrome that is based on Google's open-source Chromium platform **has declined to implement FLoC**. The technology has been criticized on privacy grounds by groups including the Electronic Frontier Foundation and DuckDuckGo, and has been described as anti-competitive; it has generated an antitrust response in multiple countries as well as questions about General Data Protection Regulation compliance.

**Comment by indigoxela** [comment]
Oops, D7 was faster: https://www.drupal.org/node/3215877 :stuck_out_tongue_winking_eye:

**Comment by indigoxela** [comment]
I just realized, that this PR still needs a little work - @herbdool suggested changes.

While the test group is a matter of taste, the `config->get()` is not - it only has one parameter (key).

**Comment by herbdool** [comment]
@indigoxela I made the one change to the config->get to @klonos PR. Do you feel like reviewing it?

**Comment by indigoxela** [comment]
@herbdool sure, will do. I've left a question regarding the logic.

**Comment by indigoxela** [comment]
Code looks good to me, my question got answered, a change record draft has been prepared - see [previous comment](https://github.com/backdrop/backdrop-issues/issues/5103#issuecomment-849031438).

RTBC from my side. :+1:

**Comment by laryn** [comment]
Thanks @klonos for filing the issue and submitting a PR. Thanks to @indigoxela, @quicksketch, @herbdool, @jenlampton, and @BWPanda for reviewing, code suggestions, and feedback. I've merged into 1.x and since by consensus we seem to be okay with considering this a bug fix I've also merged it into 1.19.x.

✌️

**Comment by laryn** [comment]
Re-opening until Change Record is published:

 - https://github.com/backdrop/backdrop-issues/issues/5103#issuecomment-849031438

**Comment by jenlampton** [comment]
Published :)
