### ISSUE TITLE
When multiple file fields are present on the same form, auto-upload is triggered only for the first one

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5114]
**Steps To Reproduce**

To reproduce the behavior:
1. On a vanilla Backdrop installation, edit the default _Post_ content type.
1. Add another file/image field to it (leave defaults as is)
1. Start creating a node of type _Post_
1. Add a title
1. Click the "Choose file" button on the widget of the first file field.
1. Try adding a file type that is not allowed to be uploaded on the field (for example, add a text or doc file if this is an image field) -> a validation error is thrown 👍🏼  
1. Click the "Choose file" button again, and this time add an image to the first file/image field -> the image is auto-uploaded 👍🏼 ...a thumbnail is created for it 👍🏼 ...and the "Remove" button is shown 👍🏼 
1. Click the "Choose file" button on the widget of the second file field.
1. Add a file type that is not allowed to be uploaded on the field -> no validation error 👎🏼 
1. Add another file/image to the second field -> the file name is added to the field widget 👍🏼 ...but there is no preview (if the field you added is an image field) 👎🏼 ...the "Select existing file" button still remains present next to the field 👎🏼 ...the "Remove" button is not shown 👎🏼 

**Expected behavior**

When multiple file/image fields are present on a form, auto-upload works for all of them, and works consistently:
- thumbnails are generated for image fields
- meta-fields (alt text, image title, etc) are shown
- the "Remove" button is shown next to the uploaded file
- if a wrong file type/size is selected, there is a validation error thrown, attached to the field where the wrong file was attempted to be uploaded/added.

**Comment by indigoxela** [comment]
This seems familiar to me... Is [that issue](https://github.com/backdrop/backdrop-issues/issues/4284) related?

**Comment by indigoxela** [comment]
No, [that one](https://github.com/backdrop/backdrop-issues/issues/3396) is it, right?

**Comment by klonos** [comment]
Yup 👍🏼 ...sorry for the duplicate.
