### ISSUE TITLE
Confusing conditions around "Administer Custom Blocks" Permission

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5117]
edit: issue moved to security queue.

**Comment by olafgrabienski** [comment]
In my opinion, part of the problem (or another aspect) is the quite broad permission "Administer Layouts" which reminds me the similarly broad "Administer content" permission. However, content related permissions are all listed under the `Node` section of the Permissions page, which makes configuration a bit easier. In contrast, "Administer custom blocks" and "Administer Layouts" are listed in different sections (`Block` vs. `Layout`). Maybe it's better to put both under `Layout`?

**Comment by jenlampton** [comment]
closing.
