### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by sg7801** [backdrop/backdrop-issues#5119]
There are some typos in the documentation ( some grammatical errors and some typing mistakes)

**Comment by indigoxela** [comment]
@sg7801 Now I get it, there was no pre-existing issue for that, you acted proactively. :smirk_cat:

**Comment by sg7801** [comment]
I directly came to the project and saw errors in documentation, hence I started contributing by correcting the documentation.

**Comment by klonos** [comment]
Thanks you @sg7801 🙏🏼 ...please see my comment in the PR re `webserver` vs `web server`. Otherwise, looks good 👍🏼

**Comment by stpaultim** [comment]
@sg7801 - Thanks for jumping in and offering a PR. We appreciate it!

**Comment by indigoxela** [comment]
@sg7801 sorry for the delay and many thanks for your patience. :pray: Currently your pull request conflicts with existing code, as the README got updated recently.

Do you know how to resolve git conflicts? Please let us know, if you need guidance or help.
Or, if you prefer to create a fresh pull request, based on the updated README, just do so.

**Comment by sg7801** [comment]
@indigoxela I would be great if you would guide me a bit on resolving git conflicts.

**Comment by indigoxela** [comment]
> I would be great if you would guide me a bit on resolving git conflicts.

Hm, I just saw that you made the changes in your fork on the 1.x branch - that's impractical in this case. A new PR would be _much_ easier.

I don't know which IDE you use, so I give an example for command line, for the whole fork-edit-push-pull_request process.

1. Fork the project on Github (as you did)
2. Create a local branch for your change: `git branch your-name-describes-problem`
3. And checkout that branch with `git checkout your-name-describes-problem`
3. Work locally on that branch to fix the problem
4. `git push` - git will nag, but provide the correct command that includes the upstream setting :smirk: 
5. Run that command - that will output a link to create a PR
6. Create that PR (from your branch)

Time passes, someone was faster, changes to that file already got merged...

1. Checkout **1.x** on your local dev - note, you didn't touch that, you worked on a branch
2. `git remote add upstream https://github.com/backdrop/backdrop.git` this adds the original backdrop repo as additional remote named "upstream" (the name can be different - your choice)
3. `git fetch upstream` get the updated code from the original repo
4. `git merge upstream/1.x` merge that into your own 1.x branch
5. `git push origin 1.x` push that to your fork on Github

Now resolve the conflict:

1. `git checkout your-name-describes-problem`
2. `git rebase 1.x` put your changes on top of the updated code from the original repo
3. ... ouch a conflict ...
4. Follow the instructions you get from git
5. Probably you have to edit files manually
6. `git add the-conflicting-file`
7. `git rebase --continue`
8. Repeat if necessary until the rebase gets finished
9. `git push -f` push your changes to your branch on Github

BUT ... as you did your changes directly on your 1.x branch, you better:

1. Close your pull request
2. Delete your fork
2. Create a fresh fork
3. Create a branch with `git branch your-name-describes-problem`
4. Checkout that branch with `git checkout your-name-describes-problem`
5. Add your changes again
6. ...

I don't know if that's really helpful, maybe someone else can provide a much easier step-by-step guide. :grinning:

Again, I'd recommend to start fresh. And this time you work on a branch, so it's easier to add an upstream and get your fork up-to-date with the original repo.

**Comment by herbdool** [comment]
I think it's ready to be merged. Thank you @sg7801

**Comment by BWPanda** [comment]
Many thanks to @sg7801 for this issue/PR! Thanks also to @indigoxela, @klonos & @herbdool for the reviews. I've merged https://github.com/backdrop/backdrop/pull/3649 into 1.x and 1.20.x.
