### ISSUE TITLE
Remove trailing slashes from robots.txt

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5122]
**Description of the bug**

Backdrop's [`robots.txt` file](https://github.com/backdrop/backdrop/blob/1.x/robots.txt) includes paths that have a trailing slash (e.g. `/user/login/`). Since these are paths and not directories, search engines don't ignore them like they should. This means that login pages (just one example) are indexed:

![image](https://user-images.githubusercontent.com/2385329/124114409-0de6ad80-da5c-11eb-9b46-4977ba769ee4.png)

**Steps To Reproduce**

To reproduce the behavior:
1. Search Google for 'backdropcms.org user' (in a private window)

**Actual behavior**

One of the search results is 'Log in | Backdrop CMS', which links to https://backdropcms.org/user/login

**Expected behavior**

There should be no login page in the search results, as indicated by this line in `robots.txt`: https://github.com/backdrop/backdrop/blob/6380ba22e52829ead1da37de19122f28ce28e0f0/robots.txt#L35

**Additional information**

This problem with the `/user/*` paths was fixed in Drupal recently: https://www.drupal.org/project/drupal/issues/3123285
The Drupal issue of trailing slashes in general was started by @jenlampton and is still open: https://www.drupal.org/project/drupal/issues/3167542

**Comment by BWPanda** [comment]
See https://developers.google.com/search/docs/advanced/robots/robots_txt#url-matching-based-on-path-values for Google's syntax.

![image](https://user-images.githubusercontent.com/2385329/124116421-7767bb80-da5e-11eb-9be3-e4fbb3972626.png)

**Comment by BWPanda** [comment]
But note:

![image](https://user-images.githubusercontent.com/2385329/124117035-2c01dd00-da5f-11eb-948c-72456f1a37c0.png)

So removing the trailing slash (e.g. from `/admin`) will still prevent indexing of paths 'below' that URL (e.g. `/admin/modules`), as well as the path itself (this is what we want).

**Comment by indigoxela** [comment]
Oops, confirmed, search with Google with patterns like `site:backdropcms.org inurl:/user/login` or `site:backdropcms.org inurl:/user/register`...

Many hits...

Now, Google sometimes does weird stuff, also search with Duckduckgo: `site:backdropcms.org inurl:"/user/register"` (note that their extended search pattern slightly differs). Also some hits.

Let's fix this :+1:

**Comment by indigoxela** [comment]
Yes, removing the trailing slash is the way to go. RTBC.

Will need a release hint that the robots.txt needs to be updated (for existing sites).

By the way, don't expect Google to immediately follow the new robots.txt rules.

**Comment by BWPanda** [comment]
> By the way, don't expect Google to immediately follow the new robots.txt rules.

Yeah, I discovered this issue today with a Drupal site. Told the customer that I wasn't sure how long it'd take Google to update their index to remove the `/user/*` pages, but still better to make the change than not.

**Comment by jenlampton** [comment]
It usually takes about 2 weeks for Google to update its index.

**Comment by quicksketch** [comment]
Looks good to me too. Thanks, merged into 1.x and 1.19.x!
