### ISSUE TITLE
Create a user_is_admin() function

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5123]
We have `user_is_anonymous()`, why not a `user_is_admin()` or `user_is_administrator()`?

**Comment by BWPanda** [comment]
I'm not saying its a bad idea, but just wondering what the use case would be...? Where/when is `user_is_anonymous()` used for example?

**Comment by indigoxela** [comment]
> Where/when is user_is_anonymous() used for example?

@BWPanda Not very often :smirk: 
```
core/modules/file/file.api.php:438:  if (user_is_anonymous()) {
core/modules/comment/comment.module:2213:    if (user_is_anonymous()) {
core/modules/user/user.module:1246:function user_is_anonymous() {
core/modules/user/user.module:1268:  return user_is_anonymous() && config_get('system.core', 'user_register') !== USER_REGISTER_ADMINISTRATORS_ONLY;
core/modules/user/user.module:1343:    'access callback' => 'user_is_anonymous',
core/modules/user/user.module:1575:    if (user_is_anonymous()) {
core/modules/system/system.api.php:3923:  if ($menu_site_status == MENU_SITE_OFFLINE && user_is_anonymous() && $path == 'my_module/authentication') {
```

@docwilmot a one-liner feature request is hard to evaluate. Could you describe your use-case a bit?

**Comment by BWPanda** [comment]
Also, how do you define 'admin/administrator'? Is it simply based on a role of the same name, or a specific permission, or just User 1?

**Comment by docwilmot** [comment]
> Also, how do you define 'admin/administrator'? Is it simply based on a role of the same name, or a specific permission, or just User 1?

"The role that will be automatically assigned new permissions whenever a module is enabled" as it is described on the roles page  at `admin/config/people/roles` and referenced in `system.core.json` as `user_admin_role`.

I find that writing especially access callbacks I want users to be able to do X if they are the owner of a particular display for example, like view a table under `user/x`, but would like admins to be able to as well, so code like 
```
global $user;
if $account->uid == $user->uid OR if user_access(adminster site content)
```

would replace above with 
```
global $user;
if $account->uid == $user->uid OR user_is_admin()
```
I found this D7 issue for the same, which was closed and "wont fix"ed. https://www.drupal.org/project/drupal/issues/2446341

Its not that big a deal, and I suppose  the `user_access()` idea is just as clean, so will close this unless any other supporting requests.

**Comment by BWPanda** [comment]
Thanks for the clarification @docwilmot. I think it's a great request. Let's leave it open for feedback/discussion.

**Comment by indigoxela** [comment]
Interesting. So we'd need to combine `user_has_role()` and `config_get('system.core', 'user_admin_role')`. That shouldn't be too hard, but is it worth it?

**Comment by quicksketch** [comment]
If we have even two places where this occurs, seems like it would be a useful addition. But does it even occur that often? Doing a full search for `user_has_role()` and we're actually only calling that in _one_ place: in a test! But perhaps that demonstrates what is useful site developers isn't always helpful directly for core. Code can get a lot more specific and make more assumptions in custom modules and themes.

**Comment by docwilmot** [comment]
Based on comments this wouldnt save much code and probably would be a bit more complexity after all. Closing.
