### ISSUE TITLE
README.md still links to the old API subdomain

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5125]
**Description of the bug**

The [README](https://github.com/backdrop/backdrop/blob/1.x/README.md) still links to `api.backdropcms.org` in section "Developer Documentation", but our new url is `https://docs.backdropcms.org/api/backdrop/groups`.

Not a big deal, as the old "api" subdomain gets redirected. However, the redirect leads to the combined docs not to the specific API docs.

**Comment by himanshu007-creator** [comment]
HI i would like to work on this issue.

**Comment by indigoxela** [comment]
Hi @himanshu007-creator,

sure, you're welcome, just go for it! Let us know, if you need any guidance.

**Comment by indigoxela** [comment]
Oh, I just realized, that my report is incomplete.

There's another outdated link: Backdrop Handbook (the user guide) should probably point to `https://docs.backdropcms.org/documentation/getting-started`

**Comment by quicksketch** [comment]
Thanks @himanshu007-creator and @indigoxela! I have merged https://github.com/backdrop/backdrop/pull/3656 into 1.x and 1.19.x.

@himanshu007-creator: I also added you to the "triage" group so you can now add labels and edit issues here on GitHub. Thanks!
