### ISSUE TITLE
[UX] Button colors inconsistent when Basis used as admin theme

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5130]
**Description of the bug**

We should have four distinct button colors:
- primary (blue for basis)
- secondary (white for basis)
- default (gray for basis)
- dangerous (red for basis)

Every time there is a button in the admin theme, it should be gray, unless it also has a class for primary or secondary, in which case it should take on the specific color.

**Steps To Reproduce**

To reproduce the behavior:
1. Switch your site to use Basis for admin theme
2. Visit the content listing
3. Edit an Article

**Actual behavior**

Many buttons are blue, when they should be white or gray.

<img width="2574" alt="Screen Shot 2021-07-15 at 12 35 19 PM" src="https://user-images.githubusercontent.com/397895/125847181-199aa076-f419-47f7-8a5f-bd86e1627af2.png">

**Expected behavior**

Only the "Save" button should be blue.

**Comment by hosef** [comment]
We also use red buttons for dangerous actions like deleting content.

**Comment by jenlampton** [comment]
Thanks @hosef, I added that to the list above (though I haven't noticed any issues with danger buttons in Basis yet...)

**Comment by hosef** [comment]
I haven't either. I just wanted to make sure it was on the list so the styles didn't get removed accidentally.

**Comment by himanshu007-creator** [comment]
HI @jenlampton , kindly review <a href="https://github.com/backdrop/backdrop/pull/3668">this</a> PR. It will close this issue.
Made during the OSD

**Comment by jenlampton** [comment]
I found a small coding standards issue that needs to be resolved. Since I was doing the testing while the PR was being created, we'll need someone else to test it. Testing can be done in the [sandbox on the PR](https://github.com/backdrop/backdrop/pull/3668#issuecomment-880988942)

**Comment by himanshu007-creator** [comment]
@jenlampton Hi! Changes were made as you suggested and I have tested these changes positively.
They work as expected and now both buttons are gray. Good job @thivyaa-web-dev 🎉

**Comment by jenlampton** [comment]
Looks great, this PR is RTBC and I've adjusted the milestone so it should get into the next release!

**Comment by laryn** [comment]
Thanks to @thivyaa-web-dev for this PR, and to @jenlampton and @himanshu007-creator for testing and review! I've merged https://github.com/backdrop/backdrop/pull/3668 into 1.x and 1.19.x in https://github.com/backdrop/backdrop/pull/3668
