### ISSUE TITLE
[UX] Fixed: Views wizard button text says 'edit' and not 'configure'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5131]
**Description of the bug**

From @klonos: In the Views UI we have this for the add view form:

![create_view_form_buttons](https://cloud.githubusercontent.com/assets/2423362/8142384/86ab37e4-11be-11e5-9383-f6b9123680d6.png)

I don't like the "Save & exit" - particularly the "exit" thing does not sit well with me. How about we change these buttons to "Save and edit" and "Save view" instead? The default does not need to be changed I think since the save and edit seems to be the most common action.

This was split-off from https://github.com/backdrop/backdrop-issues/issues/999 so we could separate that issue into two.

**Actual behavior**

Button text is currently "Continue and Configure" and "Save & exit"

**Expected behavior**

Button text should read "Continue and Configure" (TBD?) and "Save view"

**Steps To Reproduce**

To reproduce the behavior:
1. Go to `admin/structure/views/add`

**Comment by jenlampton** [comment]
From @quicksketch 

> I don't like the "Save & exit" - particularly the "exit" thing does not sit well with me. How about we change these buttons to "Save and edit" and "Save view" instead? The default does not need to be changed I think since the save and edit seems to be the most common action.

Agreed on all counts here.

**Comment by jenlampton** [comment]
> How about we change these buttons to "Save and edit" 

The problem with "Save and edit" is that we don't actually save here, we're only creating the view (saving happens later, unless you hit the save button). 

Also, "edit" has since been changed to "configure" so the text currently reads "Continue and configure" which still seems a little odd.

**Comment by jenlampton** [comment]
I'd also like to note that there is some code in [this old pull request](https://github.com/backdrop/backdrop/pull/973) for the change to the "Save and Exit" button that we could start with. It may not apply cleanly anymore, but might still be useful.

**Comment by BWPanda** [comment]
I'd say "Configure view" and "Save view"

**Comment by Aryamanz29** [comment]
I would like to work on this issue @BWPanda  @jenlampton  @indigoxela. If I'm not wrong, I think [this file](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views_ui/views_ui.admin.inc), I need to change for this issue :thinking:?

**Comment by philsward** [comment]
I'd get rid of the save button altogether and just have the save & edit. I don't think I've ever created a view I did not go into "edit" to at least make sure everything was right. I honestly don't think I haven't created a view I haven't ended up editing. It's one more click to go back to the overview page if we remove the save button.

If others just hit save to go back to the overview, then keep it (telemetry sure would be nice here...) but in my eyes, it's clutter to have both buttons.

**Comment by indigoxela** [comment]
@philsward I'd suggest: one step at a time. :slightly_smiling_face: What you request is a bigger change that needs more discussion and might not be suitable as "good first issue".

I'd recommend to create a new issue for the bigger change, so we can properly discuss that.

@Aryamanz29 yes, correct, views_ui.admin.inc is the file. But you will also need to adapt the functional tests in views_ui.test to reflect the button text change. Don't worry, just ask if you need help.

**Comment by Aryamanz29** [comment]
@indigoxela  PR raised, could you please review it

**Comment by indigoxela** [comment]
@Aryamanz29 many thanks for your pull request, the code looks good and tests are passing. :+1: 

I'd recommend that @jenlampton does the final review here, as she opened the issue. And as it's about wording - I'm not a native speaker, so I'm not really the best candidate for review.

A screenshot from the sandbox:

![add-view-buttons](https://user-images.githubusercontent.com/842066/126745675-7bd3533b-b692-4592-8e87-a0a2e1ec78c8.png)

**Comment by BWPanda** [comment]
I don't see the point of the word 'Continue'... Do we use that elsewhere in core?

**Comment by Aryamanz29** [comment]
@indigoxela Thanks for helping me out 🙌

**Comment by Aryamanz29** [comment]
> I'd say "Configure view" and "Save view"

I think this is more relevant :thinking: :arrow_up:

**Comment by indigoxela** [comment]
For comparison: two other "add something" forms:

Node type:
![node-type-add](https://user-images.githubusercontent.com/842066/126746773-2d5ff98a-6fe5-40b6-b236-1b07b3cca886.png)

Layout:
![add-layout-buttons](https://user-images.githubusercontent.com/842066/126746802-2bbf1536-54f7-49d5-8f49-f51212ac5f8e.png)

"Configure View" seems more consistent with the layout form. Node type is slightly different (it gets configured in place and the next step is to add fields, hence the buttons text there makes sense).

**Comment by jenlampton** [comment]
I left a comment on the PR, but there is one issue that still needs to be addressed before this is RTBC.

While we're working on that... Here's a crazy idea: 

What if we saved the view at this point instead of "continuing" only to save it later? I think the reason we are all struggling with language is because the form does something weird here. Rather than trying to describe the weird thing it's doing with inconsistent button text, why don't we make the action consistent?

If we were do to that, we could change the language to "Save and configure" and "Save view" so it would be more like the buttons on node types and other fieldable entities. If we did the same thing with layouts, buttons there could be "Save and manage blocks" vs "Save layout". 

If we do decide to make that change we should probably do it in a separate issue, but before I create it let me know if it seems like a good way to go?

**Comment by indigoxela** [comment]
> What if we saved the view at this point instead of "continuing" only to save it later?

Sorry, as I already recommended in a previous comment: one step at a time. @jenlampton Mind to open a new issue for that? It's pretty confusing for people providing pull requests, if the topic changes in the middle of the process.

> I think the reason we are all struggling with language is because the form does something weird here.

I'm not struggling in any way, I just avoid getting involved in wording discussions. Personally, I don't think this form does anything weird. For me it works as-is.

**Comment by BWPanda** [comment]
I like @jenlampton's suggestions.

**Comment by olafgrabienski** [comment]
> What if we saved the view at this point instead of "continuing" only to save it later?

Sounds more consistent but a pity if it blocks the text improvement of the current PR.

**Comment by jenlampton** [comment]
Ok, so let's proceed with this current PR as is and I'll also make a new
issue for other changes :)

**Comment by jenlampton** [comment]
I'm on my phone and can't change the labels (can someone else do it for
me?) But I just reviewed the updated PR and it's RTBC!

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3671 into 1.x and 1.19.x. Thanks and welcome to @Aryamanz29! I noticed that you did not have the "Triage" permission to assign labels and invited you to the Backdrop Docs team so you can add labels in the future.

Thanks everyone for your help in reviewing and suggesting these changes!
