### ISSUE TITLE
Fixed repeating icons on main Configuration page

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#5138]
**Description of the bug**

The section icons on the *Configuration* page (`admin/config`) are displayed in a strange way. The most striking issue: each icon is displayed repeatedly.

**Steps To Reproduce**

To reproduce the behavior:
1. Install a fresh Backdrop site, version 1.19.2, or update your site to 1.19.2.
2. Go to the main *Configuration* page (`admin/config`).
3. Have a look at the sections, especially the icons.

**Actual behavior**

Each icon is displayed repeatedly, the headings are hidden by the icons, and they look generally not correct.

**Expected behavior**

Icons are displayed once, headings displaying correctly.

**Screenshots**

Backdrop 1.19.2:
<img width="576" alt="backdrop-admin-config-issue-icons" src="https://user-images.githubusercontent.com/14188307/126902545-02fe6141-d800-4b02-ac35-7503c69daf52.png">

Backdrop 1.19.1 / expected behavior:
<img width="576" alt="backdrop-admin-config-ok" src="https://user-images.githubusercontent.com/14188307/126902548-ae78cab8-127b-4529-9fa2-d5083af71834.png">

**Additional information**

The problem was probably introduced by #5083, see https://github.com/backdrop/backdrop-issues/issues/5038#issuecomment-886196936.

**Comment by indigoxela** [comment]
Probably two things are needed here:

1. `background-repeat: no-repeat`, `background-size`, `padding`
2. The semantic structure is also wrong on that page - if we're also considering that, the h3 need to get changed to h2

Note: I will _not_ provide a PR. But I'm willing to test and review.

**Comment by olafgrabienski** [comment]
Is it a good approach to roll back, or modify, the CSS changes of the [Dashboard issue commit](https://github.com/backdrop/backdrop/commit/2c8fb3d115caea9f223d27793f1505b9518b8ce7#diff-e376e77e7a112390744d75e640cc24b43108cea9c527cfcde90290cc705d7a90L1193)?

I'm not yet sure about the exact scope of the single CSS changes. As a start, some information from #5038:

- > it also requires css changes. Otherwise the subheadings get (wrong) icons applied
- > The scope of the CSS changes is very limited. (...) A too greedy selector has been replaced with a more specific one.

**Comment by olafgrabienski** [comment]
> Is it a good approach to roll back, or modify, the CSS changes of the Dashboard issue commit?

Here's a 'roll back' approach:

(1) To fix the *Configuration* page, add the `.admin-panel h3` selector [removed by the A11y Dashboard fix](https://github.com/backdrop/backdrop/commit/2c8fb3d115caea9f223d27793f1505b9518b8ce7#diff-e376e77e7a112390744d75e640cc24b43108cea9c527cfcde90290cc705d7a90L1193) back.

Adding the selector back will display the *Dashboard Welcome* block subheadings in a wrong way (primarliy unwanted icons).

(2) To fix the *Dashboard Welcome* subheadings, add something like this:

```
.block-dashboard-welcome h3 {
  margin: 4px 0;
  padding: 6px 0;
  font-size: 1.154em;
  text-transform: none;
  background: none;
}
```

**Comment by olafgrabienski** [comment]
> Here's a 'roll back' approach (...)

Alternatively we could leave the *A11 Dashboard fix* as is.

"Fix the *Configuration page*" approach:

```
.admin-panel-people h3,
.admin-panel-content h3,
.admin-panel-system h3,
.admin-panel-administration h3,
.admin-panel-media h3,
.admin-panel-search h3,
.admin-panel-regional h3,
.admin-panel-urls h3,
.admin-panel-development h3,
.admin-panel-services h3 {
  margin: 9px 9px 0;
  padding: 6px 0 6px 35px; /* LTR */
  font-size: 0.923em;
  text-transform: uppercase;
  background: url('../images/chevron-circle-right--black--64.png') no-repeat left center; /* LTR */
  background-size: 23px;
}
```

Unfortunately, the element classes on the *Configuration* page aren't very convenient. So, we'd need to address every single section, like above, and do the same for `[dir="rtl"]`. The approach could be more elegant, if we added a specific class to `body` element or the `admin-panel` elements of the *Configuration* page.

Thoughts?

**Comment by indigoxela** [comment]
> Thoughts?

How about adding a css class to the headings, that actually get icons ... something like "has-icon" and act only on those? A selector like "h3" or "h2" will always be too greedy and might cause trouble later on. But that would again be a bigger change in this "Seven CSS house of cards" ...

**Comment by olafgrabienski** [comment]
> How about adding a css class to the headings, that actually get icons ... something like "has-icon" and act only on those?

Your suggestion sounds generally good, but as you say, it would be a bigger change. (Follow-up?) In my opinion, we should fix the duplicate icons soon and in a simple way. That's why I'd prefer the 'roll back' approach mentioned in https://github.com/backdrop/backdrop-issues/issues/5138#issuecomment-887829321. Let's see what others think!

**Comment by quicksketch** [comment]
This is a bit gnarly to untangle! I don't see an easy fix here, so I think I agree with @olafgrabienski that we should revert the whole commit and reopen https://github.com/backdrop/backdrop-issues/issues/5038

**Comment by olafgrabienski** [comment]
> I think I agree with @olafgrabienski that we should revert the whole commit and reopen #5038

In my opinion, we don't have to revert the whole commit. Instead, in a new PR here we can add the selector `.admin-panel h3` back at three places and add a few lines to `.block-dashboard-welcome h3`.

**Comment by jenlampton** [comment]
> How about adding a css class to the headings, that actually get icons ... something like "has-icon" and act only on those?

I like this solution. I filed a quick PR to see what the change might look like: https://github.com/backdrop/backdrop/pull/3674

**Comment by olafgrabienski** [comment]
> but then I added a specific `has-icon` class instead of the bare `h3`

Interesting! The `has-icon` class makes the selector more specific though, so as a side-effect the special icons on the *Configuration* page get overwritten by the standard chevron icons:

<img width="466" alt="backdrop-pr-3674-config-icon-fix" src="https://user-images.githubusercontent.com/14188307/127571788-e71a1035-bce2-4095-88c1-a1368714608d.png">

**Comment by olafgrabienski** [comment]
Filed an alternative PR for comparison, approach as described in https://github.com/backdrop/backdrop-issues/issues/5138#issuecomment-889457658.

PR: https://github.com/backdrop/backdrop/pull/3675

Screenshot of configuration page (with special icons):

<img width="718" alt="backdrop-pr-3675-config-icon-fix" src="https://user-images.githubusercontent.com/14188307/127573393-61317863-1cb3-4b1b-8b05-961ad0006e50.png">

**Comment by indigoxela** [comment]
Both approaches have their pro and con...

Personally, I always find less greedy selectors better, but it seems like @olafgrabienski's approach is fully working.
@jenlampton's PR still needs some work regarding the icons on admin/config and RTL display.

**Comment by olafgrabienski** [comment]
I'm fine with both approaches. @jenlampton, mind to update your PR?

**Comment by jenlampton** [comment]
I've updated my PR so that all the icons on the `admin/config` page are also targeted with the `has-icon` class.

**Comment by olafgrabienski** [comment]
@jenlampton Thanks for the updated PR! Unfortunately I discovered a little visual regression on the main *Configuration* page: the `h3` margin is too small. Comparison:

[Your current PR](https://github.com/backdrop/backdrop/pull/3674):

```
.admin-panel .block-title, .admin-panel h3.has-icon {
  margin: 9px 9px 0;
  ...
```

Backdrop before 1.19.2 and [my alternative PR](https://github.com/backdrop/backdrop/pull/3675):

```
@media (min-width: 34em) {
  .admin-panel .block-title, .admin-panel h3 {
    margin: 15px;
  }
}
```

I think the challenge of your (more elegant) approach is that it effects more places. Hopefully the margin is the last issue. If not (or if it's hard to say) we can always return to my (more limited but straightforward) approach.

**Comment by jenlampton** [comment]
Thanks @olafgrabienski and @indigoxela for reviewing my PR. I've taken care of both issues :)

**Comment by quicksketch** [comment]
The CSS rules look fine to me but I think if a front-end dev were to look at this they would recommend reducing specificity of the selectors. I left a suggestion at https://github.com/backdrop/backdrop/pull/3674/files#r685627656.

**Comment by jenlampton** [comment]
I think this is true if we were working on improving the markup, but we're
just trying to fix a css bug before Thursday. I'm starting to feel like
this is too much change. If we're adding classes and changing levels of
specicififty that's really going to cause people with admin themes.

I think we should go with Olaf's PR.

**Comment by quicksketch** [comment]
With 1.19.3 coming out tomorrow and @jenlampton's suggestion we should just use @olafgrabienski's PR, I've merged https://github.com/backdrop/backdrop/pull/3675 into 1.x and 1.19.x. Thanks folks!
