### ISSUE TITLE
Is hook_pathauto missing from Backdrop?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5139]
**Description of the bug**

The pahtauto module in Drupal 7 provided a hook that allowed other entity types to add options onto the form at
`search/path/patterns`. Was this hook renamed in Backdrop, and if so, what is it's new name? Was it removed intentionally in favor of another approach? Was it forgotten? 

https://git.drupalcode.org/project/pathauto/-/blob/7.x-1.x/pathauto.api.php#L97

**Comment by docwilmot** [comment]
I think this would be [hook_path_info()](https://docs.backdropcms.org/api/backdrop/core%21modules%21path%21path.api.php/function/hook_path_info/1) though I suspect there would be some differences. Havent checked.

**Comment by jenlampton** [comment]
Starting on a change record: https://docs.backdropcms.org/change-records/hook_pathauto-replaced-by-hook_path_info

**Comment by jenlampton** [comment]
I used field_collection as an example: https://docs.backdropcms.org/change-records/hook_pathauto-replaced-by-hook_path_info closing.
