### ISSUE TITLE
'&' missing from calls to backdrop_static()

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5142]
The design pattern for using [`backdrop_static()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/backdrop_static/1)` calls for a reference assignment, like this:
```
function example_list($field = 'default') {
  $examples = &backdrop_static(__FUNCTION__);
  ...
```

However, there are several places in core where the '&' is missing; easily found by a search for the text `= backdrop_static(`.

Omission of the '&' means that subsequent calls won't get the static variable created inside the function, thereby losing the value of this construction. To see an example of the difference, run this code somewhere (with Devel module enabled):

```
$foo1 = backdrop_static('FOO1', array());
$foo1['foo1'] = 'FOO1';
$foo1a = backdrop_static('FOO1', array());
dpm($foo1a,'$foo1a');

$foo2 = &backdrop_static('FOO2', array());
$foo2['foo2'] = 'FOO2';
$foo2a = &backdrop_static('FOO2', array());
dpm($foo2a,'$foo2a');
```

In the first case (incorrect), `$foo1a` will be a new empty array. In the second (correct), `$foo2a` is a reference to the same array as `$foo2`, as intended.

Solution is straightforward: just add an `&` in all the places that they're missing (I count 7 occurrences).

Effect should be some speedups since the values weren't previously getting the benefit of static caching.

See https://github.com/backdrop/backdrop/pull/3673/#discussion_r680400810.

**Comment by indigoxela** [comment]
Works for me. :+1: 
My favorite one is field_info_field_map(), because that also "strikes" on the default start page view. Before adding the ampersand, the code was called once for every node in that view.

**Comment by indigoxela** [comment]
The code review is an easy job here. Before it was done wrong, now it's done right. And that's obvious - odd that it took so long, until it caught somebody's eyes.

RTBC from my side.

**Comment by laryn** [comment]
I left a comment in the PR -- could this somehow have messed up the two failing `format_date` tests?
https://github.com/backdrop/backdrop/pull/3678#issuecomment-896288511

**Comment by laryn** [comment]
Thanks @bugfolder and @indigoxela! I've merged into 1.x and 1.19.x.
