### ISSUE TITLE
Add an option to node types config to hide the publish options tab for some roles.

### ISSUE THREAD

**Issue by CoachJos** [backdrop/backdrop-issues#5159]
I have create a node type, and I want hte users with a spesific role will be able to create nodes of this type; But I want them not be able to select the node path, the date, if is promoted, if is sticky, if hte comments are open or closed, and other comments options neither create revisions.

I config this options with default values, and I want an option to hide this configuration for other users, I only want them can see the field, fills these and save the node.

I try to get this function with the backdrop form block module, loading the form creation node in a block, but this options are available to change yet, and the block dont have options to hide this.

Thanks for reading and please excuse my english if it is bad.

**Comment by indigoxela** [comment]
Hi @CoachJos,

that makes sense and luckily there's a module for that: [Simplify](https://backdropcms.org/project/simplify).

BTW: you don't have to excuse for your English - many people here aren't native speakers and rely on online translation tools. :wink:

**Comment by olafgrabienski** [comment]
> luckily there's a module for that: Simplify

Another approach would be to not assign the permission "Administer content" to the role in question, then maybe tweak the options with [Override Node Options](https://backdropcms.org/project/override_node_options).

**Comment by CoachJos** [comment]
Nice, thanks for explain, I am configuring simplify now.

Excuse-me but I was search modules, but the module name is not specific.
