### ISSUE TITLE
Recommendation to move layout CSS from Seven to system.admin.css

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#517]
In issue #506 we found that the page at admin/config has its CSS in both system/admin.css and Seven. In fact this should be provided by core mainly since it is essential CSS for the page layout. 
But other CSS in Seven should also be moved to core. 
Backdrop has the fantastic Layouts module, which comes out of the box with all responsive goodness and allows different Layouts easily even for admin themes. This should make it easier to have more admin themes contributed. So we should not be thinking of Seven as THE admin theme as such. 
Hence core-essential CSS should be fished out of Seven into core, probably system.admin.css.
Related Issue #516

**Comment by jenlampton** [comment]
If the css is for laying out things in blocks *within* that one column "layout" then yes, I agree with this.  We should be careful that we aren't moving styling that still belongs in seven though.
