### ISSUE TITLE
Add theme_radios and theme_checkboxes to drupal.inc, mark as deprecated?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5191]
In https://github.com/backdrop/backdrop/pull/324 `theme_radios()` and `theme_checkboxes()` were removed in favor of `theme_container()`. 

Since those functions existed in Drupal 7, should we have instead moved them to `drupal.inc` as wrapper functions, and marked them as deprecated?

**Comment by klonos** [comment]
Yes please 👍🏼

**Comment by jenlampton** [comment]
This issue is a duplicate of https://github.com/backdrop/backdrop-issues/issues/5162.
Closing.
