### ISSUE TITLE
Example in help text for current-page `args` tokens is wrong

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#5194]
**Description of the bug**

The help text in the Token browser for `[current-page:url:args]` and `[current-page:url:unaliased:args]` mentions the following example: `'arg:1' on the page 'node/1' returns '1'`. It doesn't work.

**Steps To Reproduce**

To reproduce the behavior:
1. Go to a place where you can insert `current-page` tokens, e.g. the *Display settings* on `admin/structure/types/manage/post`.
2. Hit the *Browse avaiable tokens* link below the *Author/date format* field.
3. In the token browser, go to *Current page > URL > Arguments* [current-page:url:args], choose the *more* link, and have a look at the helpt text:
  `The specific argument of the current page (e.g. 'arg:1' on the page 'node/1' returns '1').`
4. Put the string "Test: [current-page:url:arg:1]" in the *Author/date format* field, and navigate to a post, e.g. to *Your first post* (node/1).

**Actual behavior**

The token doesn't work. You see just "Test: [current-page:url:arg:1]".

**Expected behavior**

Token works, and you see "Test: your-first-post" (i.e. the 2nd part of `posts/your-first-post`).

To get the example working, use [current-page:url:args:value:1] instead. Comparison:

- `[current-page:url:arg:1]` doesn't work
- `[current-page:url:args:value:1]` works

**Additional information**

Drupal change record: [The [current-page:arg:N] tokens have been renamed ...](https://www.drupal.org/node/1265010)

**Comment by olafgrabienski** [comment]
So, the fixed example text could be:

`The specific argument of the current page (e.g. 'args:value:1' on the page 'node/1' returns '1').`

However, `node/1` is a confusing example: At first sight, it might not be clear that Number `1` in the token and the same number as node ID are completely different things. Suggestion:

`The specific argument of the current page (e.g. 'args:value:1' on the page 'node/123' returns '123').`

**Comment by olafgrabienski** [comment]
Thanks for looking up the code line, @indigoxela ! If nobody beats me to it, I'll file a PR in the next days.

**Comment by olafgrabienski** [comment]
A PR is available now. Happy testing!

**Comment by klonos** [comment]
> I like the `node/123` variant. Agreed, an example with node/1 and the first argument is ambiguous.

I agree with that, and your PR @olafgrabienski does exactly that. RTBC 👍🏼

**Comment by laryn** [comment]
Thanks @olafgrabienski for filing and fixing, @indigoxela for help and encouragement along the way, and @klonos for code review! I've merged the PR from https://github.com/backdrop/backdrop/pull/3725 into 1.x and 1.19.x with https://github.com/backdrop/backdrop/commit/2e3d9f515f33ddad2cd5462534ac94e99e26edaa.

**Comment by laryn** [comment]
Re-opening for translation update reminder: @olafgrabienski how do we normally handle that?

**Comment by olafgrabienski** [comment]
@laryn Thanks for merging the PR!

Re `needs - translation update`, good question! From the discussion in https://github.com/backdrop/backdrop-issues/issues/2162#issuecomment-751674836, I'd say the label is a reminder, to ask if fixing a language string is important enough to justify the need of translation updates for people who are running localized sites. The question wasn't explicetely discussed in this issue, but I guess the implicit answer is "yes".

**Comment by quicksketch** [comment]
As such translation updates happen on the localize.backdropcms.org site, I think we're still done here. I'll close this to mark it completed in 1.19.4.
