### ISSUE TITLE
Remove Zen.CI from the core repository.

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5197]
**Description of the need**

We switched Backdrop core's CI service from Zen.CI to GitHub Actions in https://github.com/backdrop/backdrop-issues/issues/4753. This switch allows us better control over the CI process, access to newer PHP and OS versions, tighter integration with GitHub, and a simpler infrastructure setup. Additionally it is free, well-supported, and familiar to the vast audience of developers on GitHub.

Currently we still have Zen.CI configured as an application in GitHub, but it is "suspended" in the UI:

![image](https://user-images.githubusercontent.com/100206/131945651-ea98c426-65b3-4aa0-8682-fde4ec817722.png)

URL: https://github.com/organizations/backdrop/settings/installations/10228 (requires admin permission on the repository)

**Proposed solution**

- [x] Finish removing Zen.CI, including the directory from /core/misc/zenci
- [ ] Remove Zen.CI configuration from BackdropCMS.org
- [x] Remove the app entirely from the GitHub Repository.

**Comment by klonos** [comment]
This is a (clean-up) task, so can be done at any moment - even in a bug fix release.

**Comment by klonos** [comment]
Let's get the core repo-related clean-up out of the way at least: https://github.com/backdrop/backdrop/pull/3894

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
Thanks @klonos and @herbdool! I merged https://github.com/backdrop/backdrop/pull/3894 into 1.x.

For now I left it out of the 1.20.x branch, I figure it might be nice to have a clean cut-off point at 1.21.0, which is right around the corner anyway.

**Comment by quicksketch** [comment]
I went ahead and remove the GitHub Application from the "backdrop" organization as well. We still need to remove corresponding code from backdropcms.org.
