### ISSUE TITLE
Fixed: Missing update description for system_update_1076()

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5203]
**Description of the bug**

When upgrading from 1.19.x to 1.20-preview, the description for `system_update_1076()` is missing on the update page.

![missing-description](https://user-images.githubusercontent.com/29214084/132270857-04306668-6f1e-4bd6-9a4c-110b7e70cabd.jpg)

Fix is easy. There's a missing * in the docblock comment:

```
/*
 * Add default values for dismissible message settings.
 */
function system_update_1076() {
```

Single-character PR to follow shortly.

**Comment by klonos** [comment]
Tiny straight-forward fix. Lets get this in.

**Comment by quicksketch** [comment]
Thanks! This only affects 1.20.0 as this update hook was only added recently. I merged https://github.com/backdrop/backdrop/pull/3726 into 1.x.
