### ISSUE TITLE
Use ubuntu-20.04 for GHA

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5209]
Another Github Actions task: use ubuntu-latest instead of ubuntu-18.04.

This has been asked for before we switched, but in the rush I wasn't able to get MySQL 8 running with datadir /dev/shm/mysql.
As suspected - easy to accomplish, after figuring out the glitch.

**Comment by indigoxela** [comment]
Switching to ubuntu-20 also means switching to MySQL8 - for which we don't have full support yet in Backdrop.

One show stopper: https://github.com/backdrop/backdrop-issues/issues/4931 (in status needs review since February this year)

Another show stopper: php 5.3 completely fails with MySQL8. Alright, that combination in the real world is ... uncommon. :wink: 

Options considered: use Docker images ("services" in GHA). Problem: we can't use our /dev/shm trick with these, as they always run at the beginning, so we can't prepare directories for mysql. Which means the tests will run two to three times longer.

One option would be to create our own GHA with that custom Docker setup. Unlikely to happen - who has extra time for that.

Another option is to switch to a _locally_ installed MariaDB - that will eat up some time at the beginning of the tests to do the `apt install` jobs.

@quicksketch what do you think?

**Comment by klonos** [comment]
Are there php5 packages for Ubuntu 20?

**Comment by quicksketch** [comment]
I think we should try using a local MariaDB/MySQL, using one of the pre-built actions like https://github.com/marketplace/actions/actions-setup-mysql

That's what we're doing for PHP already, so we can install PHP 5.3 - 8.0 on any version of Ubuntu.

**Comment by indigoxela** [comment]
> I think we should try using a local MariaDB/MySQL, using one of the pre-built actions like actions-setup-mysql

I'll give it a try soon. The tricky part might still be the moving to /dev/shm, we'll see.

Luckily there's no urgent need for it. :wink:

**Comment by indigoxela** [comment]
PR updated, but now back to a more urgent problem - the random failures.

**Comment by quicksketch** [comment]
Great work @indigoxela! This looks perfect. It only takes 30 seconds to install the requested version of MariaDB, which seems completely acceptable.

This is marked needs work, but seems everything is in place. Is there more to be done here?

As a wishlist item: it would be ideal if we could put the MariaDB/MySQL version into the "matrix" YAML option, so that PRs wanting to test multiple versions of MySQL at once could just update the matrix values.

**Comment by indigoxela** [comment]
> This is marked needs work, but seems everything is in place. Is there more to be done here?

Actually, yes. I'd like to investigate, why I need a 777 on /dev/shm/mysql_tmp although the user running the db and php and directory owner are the same.

And I also wanted to verify that switching between MariaDB and MySQL works as expected.

> As a wishlist item: it would be ideal if we could put the MariaDB/MySQL version into the "matrix"...

Right, this is also something, I'd like to check. Currently we're using two conf items, `distribution` and `mysql-version` to set the database type and version. At first sight, this makes using a matrix value complicated. Not sure...

A conditional could make sense, too: for instance, using a different version when running it with PHP 5.3 or 7.4 (or 8.0).

Or: which version should we use now? I'd like to recommend MariaDB, as it seems slightly faster, but maybe a newer version.

**Comment by quicksketch** [comment]
I think the default version of MariaDB supported on the latest Debian and Ubuntu (10.3) is a good default for now, which is what the PR uses already. :+1:

One additional suggestion I have on this PR is to switch from `ubuntu-latest` to `ubuntu-20.04`. For now, they mean the same thing. But two years from now I don't want to have all our tests break unexpectedly when it changes to `ubuntu-22.04`, since we have no idea if the scripts we're using to install PHP and MySQL will immediately work with the new version released in 2022.

**Comment by indigoxela** [comment]
> the default version of MariaDB supported on the latest Debian and Ubuntu (10.3)

That's 10.5 in [Debian Bullseye](https://packages.debian.org/bullseye/mariadb-server-10.5) :wink:

**Comment by olafgrabienski** [comment]
>  indigoxela changed the title Use ubuntu-latest for GHA Use ubuntu-**22**.04 for GHA 1 hour ago

Shouldn't it be **20**.04?

**Comment by indigoxela** [comment]
So, some final checks done:

1. Permissions on mysql_tmp would have worked if I didn't unintentionally remove the chown :roll_eyes: 
2. Matrix: yes, works (looking at their async function determineVersion, I assumed it might)

(Rebasing to the latest changes also fixes the randoms :tada: )

**Comment by klonos** [comment]
> (Rebasing to the latest changes also fixes the randoms 🎉 )

🎉

**Comment by indigoxela** [comment]
OK, now I also made the version explicit in the workflow file: `runs-on: ubuntu-20.04` (Ubuntu 20.04 LTS has EOL in April, 2025)

**Comment by quicksketch** [comment]
Thanks @indigoxela! The PR looks perfect. And the 30 seconds of additional time to use whatever version of MySQL we want on a stable version of Linux is great. I merged https://github.com/backdrop/backdrop/pull/3729 into 1.x and 1.20.x. Thank you!
