### ISSUE TITLE
Spelling mistake: langauges

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5211]
**Description of the bug**

Front facing text on blocks available for translation contains a spelling error:

> If assigned a language, options will be shown to translate this block into other langauges.

![Screen Shot 2021-09-10 at 9 48 56 AM](https://user-images.githubusercontent.com/871421/132872823-b5ff2d35-0268-46fb-963c-3a9fb3554e5c.jpg)

 - `langauges`  should obviously be `languages` instead.

**Comment by MukulKolpe** [comment]
Hey @laryn @klonos can I work on this issue?

**Comment by laryn** [comment]
@MukulKolpe Please do!

**Comment by klonos** [comment]
Thank you @MukulKolpe ...RTBC 👍🏼

**Comment by quicksketch** [comment]
Thanks @MukulKolpe! I merged https://github.com/backdrop/backdrop/pull/3731 into 1.x and 1.19.x.

**Comment by MukulKolpe** [comment]
Hey, @quicksketch Thanks !!
