### ISSUE TITLE
Dashboard: Either hide the "Check manually" button, or the entire "Available updates" block, if user doesn't have the required permission

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5213]
1. Grant the "Access Dashboard" permission to the "Authenticated" role
2. Create a user; do not assign any role to them
3. Log into the site with the user you created in the previous step, and navigate to admin/dashboard ->
   - the "Available updates" block is there (I guess that's OK - should we not be showing this block at all if the user doesn't have the "View site reports" permission?)
   - clicking the "Check manually" button throws a 404 👍🏼 ...but in that case the button should not be there in the first place.

**Comment by RakeshPotnuru** [comment]
@klonos 
I am able to reproduce this issue. Can you tell how we find if a user has no Administration permission?

**Comment by oadaeh** [comment]
You have to be logged into the site with an account that has at least some administrative permission (the first user, or user ID (UID) 1 has that) and click the "User accounts" menu item in the admin bar at the top of the page. The path is /admin/people.
That page has a list of all user accounts on the system.

![image](https://user-images.githubusercontent.com/376249/158063058-ba24f6d2-6130-4075-8b0d-0f39aa93f5d8.png)

You will most likely have to create the account.

**Comment by RakeshPotnuru** [comment]
@oadaeh 
Sorry it's my mistake for unclear comment. I actually asked code to find admin or user so that I can hide the button.
I successfully reproduced this issue.

**Comment by stpaultim** [comment]
The current PR works as expected, in terms of hiding the button from users that do not have the "View site reports". However, even those with that permission are unable to use the button, so I think we are looking at the wrong permission. 

My experimentation suggests that a person with the `Administer site configuration` role is able to manually check for updates and that this would be a better role to check for. Anyone with that permission is able to check for updates, anyone without is unable to check for updates.

@klonos - am I missing something?

**Comment by indigoxela** [comment]
> My experimentation suggests that a person with the Administer site configuration role is able to manually check for updates...

Maybe it's rather `'use installer browser'`? ('Install and update modules, themes & layouts')

**Comment by stpaultim** [comment]
I tested this and it works for me. 

This is what a person logged in with the default editor role will see. 

![image](https://user-images.githubusercontent.com/3144571/158309826-dfe99247-1b13-4d79-8a12-8b842932959e.png)

This is what a person logged in with the editor role AND the permission `administer site configuration` will see:

![image](https://user-images.githubusercontent.com/3144571/158309585-28f451cc-cb20-485c-b043-e64bd8e2b1ad.png)

A user without the role of `administer site configurationi` is not able to manually check for updates. A user with that role is able to.

**Comment by stpaultim** [comment]
@RakeshPotnuru - I went ahead and marked this RTBC (Ready to be committee). It's a pretty simple Pull Request and will get another final review by core committer.

**Comment by BWPanda** [comment]
Users require the `View site reports` permission to see updates via the `/admin/reports/updates` page. I think we should hide the block entirely if they don't have that permission.

And then (as already pointed out) they need the `Administer site configuration` permission to use the button to check for updates.

So the PR is good in that it addresses the second part, but needs to also address the first, IMO.

**Comment by BWPanda** [comment]
Also, I think the fact that this shows an access denied message indicates this is a bug.

**Comment by stpaultim** [comment]
I see your point @BWPanda, I guess I was too focused on only part of the issue and missed the other part. @RakeshPotnuru is working on a revision to the PR.

**Comment by stpaultim** [comment]
@RakeshPotnuru has submitted an updated PR that should fix the problem raised by @BWPanda. It should be a really simple change, but the diff file is a mess. I assume that this is because so many lines of code were indented. Isn't there a cleaner way to manage that diff? 

If anyone has time to look at this and provide feedback, it would be appreciated. I won't have time until much later today to test it myself.

**Comment by BWPanda** [comment]
Aaand then I just realised you can do the same in GitLab itself 🤦🏻‍♂️ 

Here you go: https://github.com/backdrop/backdrop/pull/3988/files?diff=unified&w=1

**Comment by stpaultim** [comment]
@BWPanda Thanks for sharing those tricks. That is nice. 

I've tested this PR with the following test user:

UN: Test User
PW: test1234
Role = Editor

This user is NOT able to view the report or check for updates by default. If I provide them with permission to `View Site Reports`, they are able to view the available updates, but not check for available updates.

If I add the permission to `Administer site configuration` then they can see the Available Updates on the dashboard AND check manually.

I believe that this resolves the issues that have been identified so far. Works for Me. (Fingers crossed).

The PR is pretty simple. I am most interested in whether or not there is a better place for the IF statement that checks for the "View Site Reports" permission.

**Comment by klonos** [comment]
Thanks @RakeshPotnuru ...this is RTBC 👍🏼

**Comment by BWPanda** [comment]
> I am most interested in whether or not there is a better place for the IF statement that checks for the "View Site Reports" permission.

Ah, very good question @stpaultim! After a bit of research, it seems that indeed there is:

```php
function checkAccess() {
  return user_access('access site reports');
}
```

[This function](https://docs.backdropcms.org/api/backdrop/core%21modules%21layout%21includes%21block.class.inc/function/Block%3A%3AcheckAccess/1) returns `TRUE` or `FALSE` based on whether the block should be shown or not. I think this is a much more elegant solution than just wrapping the whole `getContent()` function in an `if` statement...

@RakeshPotnuru Can you please update the PR accordingly?

**Comment by RakeshPotnuru** [comment]
@BWPanda Where can I find this function?

**Comment by stpaultim** [comment]
@RakeshPotnuru 

I think that @BWPanda just means to add (1) instead of (2)

![image](https://user-images.githubusercontent.com/3144571/158941582-67a7a418-f707-4e88-ba62-09e43299e664.png)

Do I have this correct @BWPanda ?

**Comment by BWPanda** [comment]
Yep. We should add the new `checkAccess()` function with the conditional, instead of wrapping the entire contents of the `getContent()` function in the conditional.

**Comment by RakeshPotnuru** [comment]
Done

**Comment by BWPanda** [comment]
I've reviewed and tested and all looks good. RTBC from me!

**Comment by klonos** [comment]
Good catch @stpaultim and @BWPanda 👍🏼

**Comment by quicksketch** [comment]
Thank you @RakeshPotnuru, @BWPanda, @stpaultim, @klonos, and @oadaeh! I've merged https://github.com/backdrop/backdrop/pull/3988 into 1.x and 1.21.x. Sorry for the delay in getting this merged.
