### ISSUE TITLE
User accounts: Bundle name missing from the "Manage display" form title (admin/config/people/manage/display/%)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5218]
Head to `admin/config/people/manage/display/default`, or any display under `admin/config/people/manage/display/default`

<img width=50% src="https://user-images.githubusercontent.com/2423362/133144605-dae9740a-f448-486c-a90f-ade1c0ec5637.png">

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/3740

<img width=70% src="https://user-images.githubusercontent.com/2423362/133148759-463f40e9-59eb-437c-8f2c-a5cb582e67b6.png">

**Comment by docwilmot** [comment]
https://github.com/backdrop/backdrop-issues/issues/4901 has a RTBC PR.

**Comment by klonos** [comment]
Damn it, I'm getting old 😞
