### ISSUE TITLE
[UX] The structure of the Content -> Add content menu acts funny.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#522]
Here's what we have out of the box:
- Content
  - Add content
    - Basic page
    - Article
  - Find content
  - Comments
    - Published comments
    - Unapproved comments ([count])

The top-level entries ("Add content", "Find content", "Comments") are not listed alphabetically. Perhaps the intention here was to group the content-related entries together while keeping them separate from the comments. Still, why not list the content types alphabetically under `Content` -> `Add content`?

What's even stranger is how this listing works...
- out-of-the-box, the menu entries are seemingly in reverse alphabetical order while both the "Add content" page (`/node/add`) as well as the "Content types" index page (`/admin/structure/types`) are in alphabetical order.
- when you add a "test" content type, the menu list is "Basic page", "test", "Article" (so definitely not alphabetical nor reverse), while both the `/node/add` and `/admin/structure/types` pages list them properly/alphabetically ("Article", "Basic page", "test").
- adding another "lets see" content type makes things even weirder: Both "Add content" and "Content types" pages list them as "Article", "lets see", "Basic page" and "test" (WTF?) and both the menus start listing them alphabetically now (whaaat??)

**Comment by jenlampton** [comment]
I think this issue has resolved, as types are always alpha ordered for me. Please re-open if that is not the case.
