### ISSUE TITLE
Views: initial setting "Use a pager" ignored

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5224]
**Description of the bug**

When creating an view, there's a checkbox "Use a pager", which is by default checked.
But when submitting that first form with "Continue and configure", this setting is ignored, the view gets created with "Display a specified number of items". No pager.

**Steps To Reproduce**

1. Go to admin/structure/views/add
2. Add a new view with "Use a pager" checked
3. Continue and configure
4. Verify that the pager setting was ignored

Other initial settings like "Create a menu link" or "Include an RSS feed" work as expected. And I also verified that this works as expected in Drupal 7 Views.

**Screenshots**

![views-use-pager](https://user-images.githubusercontent.com/842066/133388340-2ecfd68e-fedc-405f-b8fe-a668f6b395e0.png)

![views-no-pager](https://user-images.githubusercontent.com/842066/133388362-412c10d6-7980-4e06-b9f8-8f524779b727.png)

**Additional information**

- Backdrop CMS version: 1.20.0-preview

**Comment by indigoxela** [comment]
This is broken since 2013 - by a tiny typo.

Writing the issue took me more time than creating the [PR](https://github.com/backdrop/backdrop/pull/3743). :laughing:

**Comment by klonos** [comment]
Good catch @indigoxela ...RTBC 👍🏼

**Comment by laryn** [comment]
PS. is anyone keeping stats on the time from an issue's filing to the time a PR is committed? This one would be competitive, I guess!
