### ISSUE TITLE
Fixed: Render function in `views_handler_field_file_filemime` passes bad info to `file_icon_url()`

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5227]
**Description of the bug**

I was creating a View using fields, and was trying to pull out the file mime icon separately. I linked the File to the view by a relationship, which allowed me to add "File mime icon" as a field. This field has a checkbox that says "Display an icon representing the file type, instead of the MIME text (such as "image/jpeg")". When I checked this box and tried to view the result, I got this error:

> TypeError: Argument 1 passed to file_icon_url() must be an instance of File, instance of stdClass given, called in /app/core/modules/file/file.theme.inc on line 119 in file_icon_url() (line 1811 of /app/core/modules/file/file.module).

**Steps To Reproduce**

To reproduce the behavior:
1. Make sure a Post has an image attached
2. Create a content view displaying fields, for Post content
2. Add a Views relationship to the image field
3. Add a field for "File mime icon"
4. Check the box "Display an icon representing the file type, instead of the MIME text (such as "image/jpeg")"
5. Save the View and look at the result.

**Actual behavior**

Fatal error as above.

**Expected behavior**

No fatal error and the file mime icon displays correctly.

**Comment by laryn** [comment]
Easier STR:

1. Add a Post with an image.
2. Unzip and import this View: [views.view.test_file_mime_icon.zip](https://github.com/backdrop/backdrop-issues/files/7172263/views.view.test_file_mime_icon.zip)
3. Visit `/icon-test` on your dev site.

**Comment by klonos** [comment]
RTBC 👍🏼 

@laryn how's that for how quickly an issue is fixed 😅

**Comment by quicksketch** [comment]
Thanks! Really simple fix and this looks good. Merged https://github.com/backdrop/backdrop/pull/3744 into 1.x and 1.19.x.
