### ISSUE TITLE
Add a Github Action to run phpcs (coding standards)

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5245]
Now that we have GHA up and running for Simpletest, we should also add a linter action using phpcs.

There's a related [meta issue](https://github.com/backdrop/backdrop-issues/issues/3213), but that one doesn't seem appropriate, as it's mostly about Zen.CI and about fixing standards in existing code.

What we need:

- run phpcs in a GHA (automated job), showing annotations
- run phpcs with our custom standards
- run phpcs only against added/changed code in a PR, as we have a lot of legacy code not conforming yet

Turned out that this is feasible with an [existing action](https://github.com/thenabeel/action-phpcs)

---

Related:
* https://github.com/backdrop/backdrop-issues/issues/2785
* https://github.com/backdrop/backdrop-issues/issues/5568

**Comment by indigoxela** [comment]
My PR seems to work so far, see it in action with some intentional failures: https://github.com/backdrop/backdrop/pull/3749/files

The report output is a bit... It seems like the output style hardcoded to "checkstyle" (xml), so we end up with the `&quot;`. I'm not sure, if we can do anything about that.

The annotations seem pretty helpful, though. Just a little hard to read sometimes.

Note that there are [other phpcs related actions](https://github.com/marketplace?type=&verification=&query=phpcs) available, but they come with disadvantages. The ones requiring a configured bot and a github token, for instance, aren't (to my understanding) available for non-members. And they require additional configuration via Github UI (by people with sufficient permissions) to run.
I have to admit, though, that I didn't try them all out, I quickly decided for thenabeel/action-phpcs, after reading several descriptions (and issues).
Another note: thenabeel/action-phpcs is a fork from an abandoned action.

**Comment by klonos** [comment]
It seems that the Coder version that we are installing via https://packagist.org/packages/backdrop/coder is being pulled from https://github.com/serundeputy/coder. Should we move that to another community-controlled repo? There currently are:
- https://github.com/backdrop-contrib/coder which points to:
  - https://github.com/backdrop-contrib/coder_review
  - https://github.com/backdrop-contrib/coder_upgrade

Should we change packagist to https://github.com/backdrop-contrib/coder_review?

**Comment by quicksketch** [comment]
I think could side-step questions about composer for now by downloading the latest coder release zip file, then caching the downloaded file per https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows

**Comment by indigoxela** [comment]
Regarding the coder repo: note the difference between coder (by @serundeputy) and the fully blown module coder_review, which contains lots of stuff we don't need, but does not take care of installing the phpcs dependency (correct version 1.5.x).

That's why composer has advantages here.

Regarding caching: I can copy/paste the setup from [i18n](https://github.com/backdrop-contrib/i18n/blob/1.x-1.x/.github/workflows/coding-standards.yml) but it isn't any faster than installing every time. The cached stuff also has to get pulled every time.

**Comment by indigoxela** [comment]
If I'm getting it right, we are stuck here because of concerns regarding the repo for our coding standards? Correct me if I'm wrong.

Regarding composer: I'd like to defend my approach. Having the composer.json in the main directory might be confusing for people - this file is really only needed for GHA, so the .github/misc directory is the better place for it.

Regarding caching: Note my previous comment - there's no performance gain at all, because with or without caching, the files have to get pulled into the runner box. It's just a matter of from where this pulling happens.

Regarding using composer anyway: yes, that makes sense, because we need a special version of phpcs, that's compatible with our coding standards. Getting our current setup working with a more recent phpcs, requires a rewrite of all our sniff classes.

Regarding some concerns regarding the output (`&quot;`) - very likely we have to live with that. It's caused by the hardcoded usage of "checkstyle" output in the action we use (`thenabeel/action-phpcs@v8`).

**Comment by quicksketch** [comment]
> If I'm getting it right, we are stuck here because of concerns regarding the repo for our coding standards? Correct me if I'm wrong.

That's one part. The other:

> we need a special version of phpcs, that's compatible with our coding standards. Getting our current setup working with a more recent phpcs, requires a rewrite of all our sniff classes.

I had hoped that this work may have been done already in @serundeputy's fork. But alas, no it's still using that old version.

Perhaps we should make a 1.x branch of `coder` that uses PHPCS 1.5.x (like Drupal 7), but immediately branch it into a 3.x version that is build on PHPCS 3.x (3.6.0 being the latest version https://github.com/squizlabs/PHP_CodeSniffer/releases).

Or should we bite the bullet now and delay GitHub integration until this work has been done, so we don't have two sets of coding standards that need to be maintained.

**Comment by indigoxela** [comment]
> Perhaps we should make a 1.x branch of coder that uses PHPCS 1.5.x

I'm not sure, but the contrib projects using phpcs (how many? I know at least one) use serundeputy/coder together with phpcs 1.5.x...

If there's consensus, that we need our sniffs repo somewhere in backdrop-contrib land, we could start with 3.x right away.
But... the syntax for 3.x sniffs is really different. It might even make sense to fork from Drupal coder (again) and start fresh with that?

Rewriting our existing 1.x sniffs might require more work than it's worth it.

Drupal repo: https://github.com/pfrenssen/coder

**Comment by laryn** [comment]
Is this helpful?
https://github.com/backdrop-contrib/coder_review/pull/14

**Comment by indigoxela** [comment]
> Is this helpful?

Yes, for sure. Wow, I wasn't aware that @hosef already did a lot of work regarding phpcs compatibility. :+1: 

But, wait, right, this would push the PHP version requirement to 5.4+, which means we have to revisit issues like #3992 and/or  #4712. Are we stuck again?

**Comment by laryn** [comment]
See also https://github.com/backdrop-contrib/coder_review/issues/12#issuecomment-756364126

**Comment by indigoxela** [comment]
We have options:

1. live with the outdated phpcs for now (1.5)
2. create an independent repo for *only the sniffs* - compatible with 3.x, use that in our GHA, and trying to get the module UI working step by step
3. fix everything in backdrop-contrib/coder_review and take that as base for our checks (might take some time, though)

TBH, I wouldn't want the Backdrop Coder Review UI (or module altogether) being a show stopper for automatic (and annotated) checks in a GHA.
Personally, I think the benefit of having phpcs checks in our GH workflow is big enough to consider option 1. or 2. But that's just my 2c. :wink:

**Comment by BWPanda** [comment]
As I was suggesting in https://github.com/backdrop/backdrop-issues/issues/3213, I **highly recommend** pulling the sniffs out of `coder_review` and into their own repo. This means that Backdrop core can use them in GitHub Actions (as per this issue), @serundeputy can use them for Drush (instead of his own forked repo), I can use them for Bee, and then `coder_review` can use them too (without needing to duplicate them in its own repo). And core, Drush, Bee, etc. who want to use these sniffs in their various checks don't need to pull in all the other `coder_review` code unnecessarily.

So I guess that means I prefer @indigoxela's 2nd option above. Now, what version of phpcs these sniffs support is another question altogether, but I'm leaning towards using modern standards of 3.x, rather than old, legacy code.

Hope that all makes sense.

**Comment by quicksketch** [comment]
I agree with @BWPanda. And I like option #2 best. We start a new repository with minimal coding standards and work to expand it; starting with 3.x version of PHPCS.

**Comment by indigoxela** [comment]
What do we need to get progress here:

1. A repository for the Backdrop sniffs, with sniffs compatible with phpcs 3.x
2. Update the existing PR to get sniffs from that new repo

Seems feasible. :wink:

I'd not recommend to use the full [Coder Review](https://github.com/backdrop-contrib/coder_review) module, as it provides loads of thing we don't need here - we just need the sniffs.

And they should be compatible with a more recent phpcs, 3.x - which is not the case with the sniffs in coder_review (still requires 1.x).

@hosef you did a lot of work re updating the sniffs, and so did @quicksketch https://github.com/backdrop-contrib/coder_review/pulls But both try to fix the sniffs inside the module.

@BWPanda suggests to put the sniffs in an extra repo and I fully agree with that.

We "just" need to figure out, how to proceed with the sniffs repo.

@hosef do you think, your PR for coder_review (the sniffs) is a possible starting point for the new repo?
@quicksketch or would you prefer to start completely fresh and update the rulesets from D to meet the B standards? (yes, there are some differences)

**Comment by klonos** [comment]
> @BWPanda suggests to put the sniffs in an extra repo and I fully agree with that.

Same ✋🏼 ...I think I'd prefer the new repo under `https://github.com/backdrop` instead of `https://github.com/backdrop-contrib` (less people with access to it, but still not necessarily limited to the core committers).

**Comment by BWPanda** [comment]
I think `/backdrop-ops` is a better group for the new repo @klonos.

**Comment by klonos** [comment]
Yes, or that @BWPanda 👍🏼 ...my point was:
- not in contrib, cause too many people have too much access there
- access should not be limited only to core committers, so that more people can contribute to managing/maintaining it

**Comment by hosef** [comment]
@indigoxela I think that my PR would be a good starting point if you want to update the sniffs to work with a newer version of PHP_CodeSniffer, but there are still a lot of things that don't work in it. If I remember correctly, they changed the string parsing interfaces, so most of the checks related to comments are completely broken.

**Comment by indigoxela** [comment]
> so most of the checks related to comments are completely broken.

Then it might make sense to start fresh with a Drupal sniffs fork...

**Comment by indigoxela** [comment]
Here we go, rebased and switched to a different approach. :tada:  https://github.com/backdrop/backdrop/pull/3749/files

Instead of figuring out where to put and maintain our custom ruleset, I decided to only cherry-pick from the built-in rulesets, which reduces the new Backdrop ruleset to a single xml file.

Sure, sooner or later we should create a repo and also create custom rules - but that seems to block us currently. So, why not simply postpone the whole repo topic?

Good thing: we can now use the latest and greatest phpcs (3.7 ATM), which ships with php 8.1 support. And that means: no more composer, as shivammathur/setup-php provides it as a tool.

Bad thing: most of the comment rules are gone. (The ones from Generic, Squiz and PEAR ruleset are a bit too opinionated, but I'll take a closer look.)

@quicksketch do you think, this is a feasible approach?

**Comment by indigoxela** [comment]
Long term goal: combine this and the (otherwise unrelated) [PHPStan PR](https://github.com/backdrop/backdrop-issues/issues/5467) to one workflow (use the same GHA runner).

**Comment by indigoxela** [comment]
Here's a [repo](https://github.com/indigoxela/phpcs_backdrop) to discuss:

- name
- location
- maintenance
- functionality

**Comment by jenlampton** [comment]
@indigoxela I forked your repo into the `backdrop-ops` group, and made you an admin. 

* name: @quicksketch likes `phpcs` 
* location: `backdrop-ops`
* maintenance: I added @indigoxela -- @BWPanda and/or @serundeputy let me know if you also want access. 
* functionality: @quicksketch is happy as-is

**Comment by jenlampton** [comment]
Okay, I have cloned and pushed the repo up to https://github.com/backdrop-ops/phpcs. @indigoxela  you are still an admin :)

**Comment by indigoxela** [comment]
I'm not sure if using the same name as the commandline tool itself is ideal...

I'm still admin, and already fixed another bug. :wink:

**Comment by indigoxela** [comment]
PR updated:

- Removed confusing (temporary :grinning: ) xml file (we now have a repo, so we can checkout instead of providing it here)
- Tagged repo (1.0.0-beta1) and use that tag for actions/checkout

Last steps: if we're happy with the outcome, the `test.php` file should get removed before merge.

**Comment by laryn** [comment]
I like it and I think it will be very helpful on PRs.

> ![Screen Shot 2022-08-30 at 2 28 05 PM](https://user-images.githubusercontent.com/871421/187526101-568faea2-e22c-41ab-9052-63d843bb339c.jpg)

**Comment by hosef** [comment]
@indigoxela Do you know if the current rule set in backdrop-ops/phpcs matches our coding standards outlined on https://docs.backdropcms.org/doc-standards?

**Comment by indigoxela** [comment]
@hosef they do, because I built it around that documentation. :wink: If you find something that does not, please open an issue in backdrop-ops/phpcs.

**Comment by hosef** [comment]
Ok, I just wanted to check.

If that is the case, then I think that this looks good to go. I have tried out the sniffs locally and I didn't get any errors using the latest phpcs and PHP 8.1.

**Comment by indigoxela** [comment]
Great! So it's time to remove the test.php file (done).

**Comment by hosef** [comment]
Merged https://github.com/backdrop/backdrop/pull/3749 into 1.x. Thanks @indigoxela, @jenlampton, @quicksketch, @laryn, @BWPanda, and @klonos!

Special thanks to @indigoxela for doing a lot of the heavy lifting of setting up our GitHub Actions.

**Comment by klonos** [comment]
@indigoxela @hosef is there a way to point the GHA to latest release instead of a hard-coded tag of the [backdrop-ops/phpcs](https://github.com/backdrop-ops/phpcs) repo? (unfortunately, GitHub doesn't have an API or easy way to retrieve the latest tag of a repo as it allows retrieving the lates release) ...separate issue? ...follow up PR?

**Comment by hosef** [comment]
@klonos I am not sure about the technical details there.

As far as if we should, it might be better to include changes to the coding standards check with a patch that fixes the new coding standards problems. That way we don't make PRs that were previously passing suddenly not pass with no changes in the core code that they could see.

**Comment by indigoxela** [comment]
> is there a way to point the GHA to latest release instead of a hard-coded tag

The tag is there to have a reliably consistent version, while development can still go on (if needed). There has to be a way for fixes.
IMO it's too early for a stable release (zero feedback so far).

Keep in mind that phpcs only runs on **changed code in a PR**. So if we decide that some standard needs adaption, this doesn't mean that all of a sudden everything breaks. :wink:

**Comment by bugfolder** [comment]
> Keep in mind that phpcs (GHA) only runs on changed code in a PR.

Well, that's not quite correct (at least the way it's working out). If you change one line in a file, PHPCS runs on the entire file, not just the changed code, and so will flag preexisting issues in the file unrelated to the code changes. For example, in https://github.com/backdrop/backdrop/pull/4246/files, the second change at line 670 was the original code change; the first change at line 378 was flagged as being needed by PHPCS.

**Comment by indigoxela** [comment]
> Well, that's not quite correct ..

At least, that's what the documentation of that action says.

https://github.com/thenabeel/action-phpcs

The default scope of that action is "blame", which means only changed code.

I can see the nagging on [this commit](https://github.com/backdrop/backdrop/pull/4246/commits/51a009210d460b9da926d85d3452f513a5f6bccf) - to me it seems, that the line number is wrong. The nagging's for line 667, but the hint points to line 378. Probably a bug in the action. :shrug:
