### ISSUE TITLE
Added the ability to clone a views display while changing the display plugin

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5246]
This is the same change as committed in Views 7.x back in May: https://www.drupal.org/node/1401778

> If you have multiple displays, and one page display has overridden fields or style plugin settings, and you want to create a block display that has those exact settings, you have to manually rebuild it.
> 
> The idea is that you could choose the new display plugin while cloning, along with a warning saying that all display settings will be unconditionally thrown away. Some display plugins share similar setting names that mean different things, so there should be no attempt to translate those.

**Comment by laryn** [comment]
Great idea.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/3751 into 1.x and 1.20.x. Although this is a feature, we try to keep pace with core cross-ports as often as possible, so I've gone ahead and included this for 1.20.2.
