### ISSUE TITLE
broken html at custom blocks admin page

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#5251]
Since I updated to 1.20.0, my custom blocks admin page is broken. It happens with all my updated sites which already had custom blocks in it, but NOT the ones without, even if I add them now:

![Cursor_and_Custom_blocks___lluitanoviolenta_cat](https://user-images.githubusercontent.com/105581/134468583-1972e7d3-479d-49f0-be39-c58502dcec3a.jpg)

This happens with seven but also with basis as admin theme.

**Comment by indigoxela** [comment]
This looks weird! I bet, you tried to flush caches several times, right.

I'm not using custom blocks very often, but none of my sites shows such a broken table after updating. And - as far as I know - [1.20.0](https://github.com/backdrop/backdrop/releases/tag/1.20.0) didn't change anything regarding custom blocks.

Could you inspect your config directory? For what I see, the same blocks get repeated again and again - did something go wrong in your config directory? Are you using config sync?

Anything in your dblog? admin/reports/dblog

What's your php version, BTW?

**Comment by indigoxela** [comment]
Oh, and another question: did you update from 1.19.3 or an older version?

**Comment by jenlampton** [comment]
1.20.0 consolidated the labels and machine names of many admin tables which included a rewrite of the markup that generated the block listing. It appears that the change also included an inadvertent change that also added columns for each row to the previous row, causing these display issues. 

One-line change in PR posted for review :)

**Comment by bugfolder** [comment]
dpm() is still in the PR.

**Comment by jenlampton** [comment]
hah! thanks :) Updated the PR.

**Comment by bugfolder** [comment]
Reviewed and tested. LGTM.

**Comment by stpaultim** [comment]
This seems to meet the criteria. https://backdropcms.org/user-guide/adding-milestones-to-issues

Added this to 1.20.1 milestone

**Comment by indigoxela** [comment]
Code looks good to me. It simply reverts the unintentional removal of a single (yet important) line in https://github.com/backdrop/backdrop/pull/3710/files

RTBC!

**Comment by Egarbeil** [comment]
I applied this fix to 2 sites that have custom block lists - It fixed the issue with no problems on one, but I'm still having the issue on the other site - it's a big problem. This is a live site and those custom blocks are updated often (at least weekly).  HALP!  
![mhs-custom-block-list](https://user-images.githubusercontent.com/41450710/135353888-750241a6-125a-42d9-8e7f-09205189f46e.jpeg)

**Comment by stpaultim** [comment]
@Egarbeil - it looks like there might be a type in the block file you provided. 

I see this `$row = @array();`

Should be

`$row = array();`

**Comment by Egarbeil** [comment]
> @Egarbeil - it looks like there might be a typo in the block.admin.inc file you provided.
> 
> I see this `$row = @array();`
> 
> Should be
> 
> `$row = array();`

Tim, not sure why that's there - it's not in the file that's on the site.  Re-uploading the file now.  I'm still having the issue (after clearing caches on browser and site
[block.admin.inc.txt](https://github.com/backdrop/backdrop-issues/files/7255344/block.admin.inc.txt)
).

**Comment by Egarbeil** [comment]
Update - out of grasping at straws.  I deleted line 22 completely, re-saved the file, and then re-typed it in manually.  That seems to have fixed the issue.  Thanks!   All 10 custom blocks appear correctly.

**Comment by jenlampton** [comment]
I'd like to see this get into 1.20.1 before we push to Pantheon today. Ahem @quicksketch @laryn @herbdool or anyone else!

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/3758 into 1.x and 1.20.x.

This regression was introduced in #3402. We'll get 1.20.1 out soon. Probably tomorrow or Oct 1.
