### ISSUE TITLE
Dashboard isn't available after enabling

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5254]
**Steps To Reproduce**

To reproduce the behavior:

1. Disable the module 
2. Now enable the module and go to `admin/dashboard` just to see "Page not found" notice.

**Expected behavior**

- Disabling the module does work correctly, however leaving the Dashboard menu item in the Toolbar. So ideally the menu item also should be disabled.
- Enabling the module should bring the functional Dashboard page on `admin/dashboard` without any additional steps.

**Additional information**

To bring the missing page back you have to additionally go to `admin/structure/layouts` and enable the Dashboard layout, which should've been automatically turned on when enabling the module.

**Comment by indigoxela** [comment]
Nice catch, and confirmed. When disabling the module, the layout gets disabled, but when enabling the module again, the layout isn't enabled.

**Comment by olafgrabienski** [comment]
> Disabling the module does work correctly, however leaving the Dashboard menu item in the Toolbar. So ideally the menu item also should be disabled.

For this part there is already an issue, see #3888.
