### ISSUE TITLE
Default layout page broken if Basis set as administration theme

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5255]
**Steps To Reproduce**

To reproduce the behavior:
1. Go to 'admin/appearance' and set Basis as administration theme.
2. Go to 'admin/structure/layouts/manage/default' and you will see the page is broken.

![Screen Shot 2021-09-23 at 10 32 46 PM](https://user-images.githubusercontent.com/56604405/134614033-13f9f16a-e071-4d32-8d77-c15208169d51.png)

**Expected behavior**

Since Basis theme is the default theme, it should work well in all kind of scenarios, including when it is set as the default theme.

**Additional information**

The page 'admin/structure/layouts/manage/home/blocks' (Home page layout) is well rendered unlike the 'admin/structure/layouts/manage/default', so I believe just styling for Default layout is messed up.

![Screen Shot 2021-09-23 at 10 32 51 PM](https://user-images.githubusercontent.com/56604405/134614053-dac12d29-f869-47bf-8fb6-ad3c6c40920f.png)

**Comment by indigoxela** [comment]
Hey @alanmels, welcome back!

Yes, Basis isn't working well when used as admin theme, that's a known problem.

We have this [meta issue](https://github.com/backdrop/backdrop-issues/issues/2653) which tries to provide an overview of open tasks.

**Comment by alanmels** [comment]
Hi @indigoxela, thanks for pointing to the meta issue. I'm closing this one in favor of that one.

**Comment by indigoxela** [comment]
> thanks for pointing to the meta issue. I'm closing this one in favor of that one.

I think, closing was actually not necessary.

The other issue is a meta issue, which should provide an overview. If you plan to file a PR for admin/structure/layouts/manage/default display, it's easier to relate it to this issue here - a merge will close the issue and that's not what we want for the meta issue, there's a lot more work to do re "Basis as admin theme". :wink:
