### ISSUE TITLE
Allow filtering tests and display class name for each test

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5257]
Just spent a few wasted minutes. `TokenNodeTestCase()` failed in a test, so I want to re-run it locally on my PC. But in the test list in the UI, which one is `TokenNodeTestCase()`?
```
Array token tests
Comment token tests 
Current page token tests 
Entity token tests 
File token tests 
Menu link and menu token tests 
Node and content type token tests 
Taxonomy and vocabulary token tests 
Token replacement 
Token scanning 
Token unit tests 
URL token tests 
User token tests 
```
This required me to go to the API site, search for `TokenNodeTestCase()`, figure out that its coming from Simpletest, go find `simpletest.test.info` (after wrongly checking `node.test.info` and `token.test.info`) to figure out, at last.

Is there an easier way to highlight in the GHA test result which actual test this is? 
Or maybe I'm doing this wrong and there already is an easier way?

**Comment by indigoxela** [comment]
Oh, a third person struggling with the output. :wink: 

@docwilmot you might want to share your thoughts in this previous issue: #5236

**Comment by docwilmot** [comment]
No @indigoxela this is not the fault of GHA at all. Your work there is great and well appreciated. 

In fact this was the same issue with Zen as well, and is a general issue about difficulty discovering the labels given to tests. For example, again, just now, a fail in `FileSaveUploadTest` happened on GHA. There is no easy way to discover which actual test this is from. Turns out its not in File module's `file.test`, but its in Simpletest's `file.test` and in the Backdrop UI its actually called just `File uploading`. 

I dont have a solution to mind yet, just ranting, sorry.

**Comment by bugfolder** [comment]
Dunno if this is helpful, but it might be adaptable. When I've encountered a failing error class (say, `TokenNodeTestCase `), I use BBEdit to search for that name over the core directory, which takes just a few seconds. It typically returns two files: the .info file (`simpletest.tests.info` in this case) and the actual file containing the tests (`token.test`). Clicking on the .info result shows the name (`Node and content type token tests`) and group (`Token`), making it easy then to find and run that test from the UI.

Also, once I've established which test function is failing, in the test file I do a search-and-replace of `function test` to `function _test`, then go back and remove the underscore from the function I want to work on. That way, that will be the only function that runs. Once it's working, I reverse the S&R to restore all the other test functions.

Seems like in the UI it would be nice to add the class name as a "machine name" to the listing; if the group is obvious or guessable, then one could skip the search step, just expand the likely group in the UI and look for the class name.

**Comment by docwilmot** [comment]
Morning, can I get a milestone please?

**Comment by indigoxela** [comment]
> Morning, can I get a milestone please?

Sure. It's labelled as "feature request", hence is supposed to go into 1.21, right?

**Comment by indigoxela** [comment]
Hey, I almost missed this issue, that's a cool idea (js filter for simpletests).

The code looks good. RTBC! :+1:

**Comment by klonos** [comment]
During the weekly dev meeting today, @quicksketch mentioned that this may actually be considered a UX improvement (so a task rather than a new feature), and I agree.

Either way, I always work with latest 1.x on my locals, so I'll be happy to have it merged into 1.x ...thank you for this great DX/UX improvement @docwilmot 🙏🏼

**Comment by BWPanda** [comment]
Just to show people reading this issue what the [PR](https://github.com/backdrop/backdrop/pull/3785) does:

![image](https://user-images.githubusercontent.com/2385329/145672820-96c08659-4bca-4691-ba6d-f163b783d265.png)

It adds an AJAX search/filter field to the top of the Test form, and displays the actual test name in brackets below each test.

I like this! One suggestion: would it be worth adding a 'reset' button after the search field? I know you can just delete the contents of the field, but clicking a button to reset the form would be easier than focusing the field, selecting all text and then pressing Delete...

**Comment by quicksketch** [comment]
I code reviewed and tested this and it looks great! I merged https://github.com/backdrop/backdrop/pull/3785 into 1.x for 1.21.0.

Super work @docwilmot! Thanks @indigoxela, @BWPanda, @bugfolder, and @klonos for your feedback and testing!

**Comment by quicksketch** [comment]
Small follow-up issue filed at https://github.com/backdrop/backdrop-issues/issues/5409. I encountered this bug while testing but I don't think it should be a hold-up for this feature, as it's a problem in an entirely different JS library.
