### ISSUE TITLE
Happy New Year Backdrop!

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#526]
Will be on the beach at midnight here, so posting in advance. Wishing Backdrop and Nate and Jen lots of luck and success. 
And the same to all the supporters and contributers.

**Comment by quicksketch** [comment]
Yay! :tada:

Thanks. It's been a big year of development, but hopefully only the first of many years of site building bliss. :smile:

**Comment by jenlampton** [comment]
Happy New Year, Backdrop community!!! :) :) :)

**Comment by klonos** [comment]
Happy new year guys!!!
