### ISSUE TITLE
[UX] Custom Block admin listing broken 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5260]
**Description of the bug**

The admin listing for blocks (admin/structure/block) is not functioning properly. It appears the whole table is duplicated for each block?

<img width="1207" alt="Screen Shot 2021-09-27 at 1 24 49 PM" src="https://user-images.githubusercontent.com/397895/134979911-5297a957-64c0-4f92-8e3b-52504821d9b0.png">

**Steps To Reproduce**

To reproduce the behavior:
1. Go to admin/structure/block
2. Create 2 or more blocks

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.20.0

**Comment by olafgrabienski** [comment]
Weird! Duplicate of https://github.com/backdrop/backdrop-issues/issues/5251?

**Comment by jenlampton** [comment]
yes :( going over there...
