### ISSUE TITLE
Fatal Parse error when not running new enough version of PHP

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#528]
When I'm running PHP 5.2.16 (which worked for Drupal 6) I get the following error when trying to run Backdrop:
` Parse error: syntax error, unexpected T_CONST in backdrop/core/includes/bootstrap.inc on line 11`

It would be nice if we didn't use any newer PHP tools before we did the status requirements check, so that we can throw a friendly message explaining the problem to users. Most people won't be able to decipher that what this really means is that their PHP version is too old.

**Comment by quicksketch** [comment]
This was a micro performance improvement that using `const MY_CONSTANT_NAME = 'foo'` is one less function call than `defined('MY_CONSTANT_NAME', 'foo')`, and it can be done at compile time instead of execution time.

I'd be fine reverting our constants back to the Drupal 7 approach where we use define() instead of the `const` keyword.

**Comment by rgeleta** [comment]
Per http://php.net/manual/en/language.constants.syntax.php, 
You can define a constant by using ... the const keyword outside a class definition as of PHP 5.3.0. 

backdrop file bootstrap.inc, line 21 reads
const BACKDROP_MINIMUM_PHP = '5.3.2';

For the clone done just now, there are a total of 256 hits on "const " (space after t"). 

Is the plan to update the status requirements check to tell someone their installation does not meet minimum requirements?

Or, could the rest of Backdrop run if the "const" syntax were reverted to "define" syntax?  If this is the case, I might be able to handle this update.

**Comment by quicksketch** [comment]
> Or, could the rest of Backdrop run if the "const" syntax were reverted to "define" syntax? If this is the case, I might be able to handle this update.

I'd be 100% okay with reverting the `const` syntax with define(). Note that we may have some `const` declarations inside of classes, which is okay (and works with older versions of PHP).

> Is the plan to update the status requirements check to tell someone their installation does not meet minimum requirements?

The status check already will check for PHP version requirements, but the use of `const` causes a parse error so the status check can't even be run. Reverting back to `define()` will fix the status check as a side-effect.

**Comment by tarekdj** [comment]
For the record, I wrote this script (it ignores **const** in a class):
```php
<?php

$files = array(
'core/authorize.php',
'core/includes/bootstrap.inc',
'core/includes/common.inc',
'core/includes/drupal.inc',
'core/includes/file.inc',
'core/includes/install.core.inc',
'core/includes/install.inc',
'core/includes/language.inc',
'core/includes/locale.inc',
'core/includes/menu.inc',
'core/includes/password.inc',
'core/includes/stream_wrappers.inc',
'core/includes/theme.inc',
'core/includes/unicode.inc',
'core/includes/update.inc',
'core/modules/comment/comment.module',
'core/modules/entity/entity.query.inc',
'core/modules/field/field.attach.inc',
'core/modules/field/field.module',
'core/modules/image/image.module',
'core/modules/layout/layout.module',
'core/modules/menu/menu.module',
'core/modules/node/node.module',
'core/modules/search/tests/search.test',
'core/modules/simpletest/simpletest.install',
'core/modules/simpletest/tests/file_test.module',
'core/modules/system/system.module',
'core/modules/taxonomy/taxonomy.module',
'core/modules/translation/translation.module',
'core/modules/update/update.module',
'core/modules/user/user.module',
'core/modules/views/views.module',
'core/scripts/run-tests.sh',
'core/update.php'
);

foreach($files as $file) {
    echo "Processing : $file \n";
	// Read file and get content.
	$myfile = fopen($file, "r") or die("Unable to open file!");
	$code = fread($myfile,filesize($file));
	fclose($myfile);

	// Search for code to be replaced.
	preg_match_all("/const ([A-Z])\w+ = .*/", $code, $out);
	$matches = $out[0];

	// build replacement.
	$repl = array();
	foreach($matches as $key => $match){
	  $origin = $match;
	  $origin = str_replace(";","",$origin);
	  $org = explode(" ", $origin);
	  $const_name = $org[1];
	  $const_val = $org[3];
	  $new_const = "define('$const_name', $const_val);";
	  $repl[] = array('find' => $match, 'replace' =>$new_const);
	}

	// replace in code
	$new_code = $code;
	foreach($repl as $replacement){
	  $find = $replacement['find'];
	  $replace = $replacement['replace'];
	  $new_code = str_replace($find,$replace, $new_code);
	}
	// write file
	echo "Saving the file ";
	$myfile = fopen($file, "w") or die("Unable to open file!");
	if(fwrite($myfile, $new_code)){
	  echo "  [OK]\n";
	}else {
	  echo "  [ERROR]\n";	
	}
	fclose($myfile);
}
```

Copy the code in a file named *replace.php* in backdrop root dir and run it using:
```sh
php replace.php
```

**Comment by jenlampton** [comment]
Nice one! regex ftw!! Thanks @tarekdj :)  Are you interested in creating a PR for us that includes these changes?

**Comment by tarekdj** [comment]
@jenlampton  PR already sent https://github.com/backdrop/backdrop/issues/643 ;-)

**Comment by jenlampton** [comment]
Amazing :) thank you!

**Comment by jenlampton** [comment]
Hm...  I'm still getting ugly PHP errors with PHP 5.2.17:
```
Parse error: syntax error, unexpected T_FUNCTION in backdrop/core/includes/common.inc on line 5355
```

**Comment by jenlampton** [comment]
Update: it looks like if we go straight to /core/install.php we do get the correct messaging now:
```
Your PHP installation is too old. Backdrop CMS requires at least PHP 5.3.2. See the system requirements page for more information.
```

However, if we go straight to the root of our site (expecting to be redirected) then we get the PHP fatal.

**Comment by jenlampton** [comment]
Okay, after more thought I think this is a good enough solution for this issue, and I've opened https://github.com/backdrop/backdrop-issues/issues/554 for the bootstrap problem.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/643. Thanks @tarekdj!
