### ISSUE TITLE
Rename Admin Bar components and add descriptions

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5284]
**Description of the bug**

There is an Administration Bar menu setting that allows you to disable the "Home" menu in the admin toolbar. However, the option is labelled "Icon Menu." I believe that this is a holdover from Drupal 7, when this menu was the Druplicon. 

![icon-menu](https://user-images.githubusercontent.com/3144571/135742572-59571c95-532c-46a0-ad03-f0ceb0213f1d.png)

**Steps To Reproduce**

To reproduce the behavior:
1. Go to 'admin/config/administration/admin-bar'
2. Disable "Icon Menu" and save
3. Notice that the Home menu disappears

**Expected behavior**

I believe that the behavior is fine, but the label is incorrect and unhelpful. If I didn't remember Drupal 7, I would have no idea what the "Icon Menu" is.

Here is screenshot of Drupal 7 admin toolbar

![D7-icon-menu](https://user-images.githubusercontent.com/3144571/135742655-2329bef1-2f0a-4fed-a691-4fe5e8408d65.png)

I believe that the only thing necessary here is to change the label to "Home Menu". I might also suggested removing this option completely, but I guess that would probably be a 2.0 issue, right?

**Comment by klonos** [comment]
Good catch @stpaultim 👍🏼  ...I'd suggest the following:
- Call the component "Home menu"
- Add individual help text of for each checkbox, as not everything is immediately apparent. For the home menu, the description could be something like "Provides a convenient link to the home page of the site, as well as quick links that allow you to clear the various caches, run cron, and run updates."

**Comment by stpaultim** [comment]
@mayankshrivastav003 - Actually, I don't this this error has anything to do with your database. Backdrop CMS stores configuration in json files in a config directory. 

During installation it generates a random hash to name the config directory. There is a setting in the settings.php file that specifies the specific path to the config directory for each site. 

As the error suggests - it is possible that this directory was not created or that the config files somehow got into another directory. This sometimes happens if you attempt the install process more than once and you end up with multiple config directories. 

One solution to this would be to drop the database, delete the config directory, and run through the install process again to make sure that everything is in sync.

**Comment by stpaultim** [comment]
@mayankshrivastav003 - Please, let us know if this works for you. Maybe someone else has a better idea?

**Comment by mayankshrivastav003** [comment]
@stpaultim sir actually it is not working (I am sorry that I am taking so much time on this thing, but I'll try installation with drush, the second method suggested right now and if it doesn't works , I'll approach here) Sorry for taking so much time (Actually there was an Indian festival so I was busy in that that's why I didn't work on it much). Thanks for asking sir. But I will do this today only.

**Comment by klonos** [comment]
> I am sorry that I am taking so much time on this thing

No need to be apologising @mayankshrivastav003 ...please work on this whenever you have time. No stress 🙂

**Comment by stpaultim** [comment]
I have removed the assignment on this issue. If anyone else would like to work on it, please jump in.

**Comment by Girlwithasmile** [comment]
Hello I am a contributer at openforce 2022 can i try to work on this issue as I am a beginner?

**Comment by stpaultim** [comment]
@Girlwithasmile - Yes, this might be a good issue for you to work on. 

For most issues, it is best to get Backdrop working on your local computer to test your work, but this issue might be easy enough to do the following:

1) Create a demo site here to see the problem: https://backdropcms.org/
2) Clone the Backdrop repo and find the place where this needs to be fixed, make the change, and create a PR. 
https://backdropcms.org/news/creating-pull-requests-against-core-the-easy-noob-way

Did you read this: https://backdropcms.org/news/openforce-2022-getting-started

**Comment by stpaultim** [comment]
@Girlwithasmile - Let us know if you have any questions?

**Comment by purohitmansi** [comment]
Hello @klonos!

I am an openforce 2022 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by RakeshPotnuru** [comment]
Hey @purohitmansi, @Girlwithasmile 
What is the progress? Do you need any help?

**Comment by RakeshPotnuru** [comment]
Can I finish this since those are inactive?

**Comment by stpaultim** [comment]
@RakeshPotnuru - Yes, I think you should go ahead. If @purohitmansi or @Girlwithasmile need help finding some new issues, we will help out.

**Comment by BWPanda** [comment]
No bug here, changed to task instead. PR is simple and looks good. Do we want to insist on @klonos' suggestion of multiple help text, or leave that for a followup?

**Comment by RakeshPotnuru** [comment]
Yes, I saw that. But where to put those help texts?

**Comment by BWPanda** [comment]
@RakeshPotnuru See [`node_type_form()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.types.inc/function/node_type_form/1) for an example of where we've done this before (the `status_default` radio buttons).

**Comment by RakeshPotnuru** [comment]
@BWPanda Can you tell me help texts for other options?

**Comment by stpaultim** [comment]
@RakeshPotnuru - Great job on the descriptions. I have a few ideas for improvement based upon other discussions happening in our project and an opportunity to make things more consistent. 

I've actually changed some of the label names, because as I looked closer several of them could be labelled better. Some of these are slightly mislabeled, because of changes that have been made since Backdrop was forked from Drupal. 

1) We have a administration menu, not a management menu. Let's label this correctly. 
2) Why not call the search bar - "Menu Search", I think it's more accurate and matches the current label  on the search itself.
![image](https://user-images.githubusercontent.com/3144571/159114406-874fd0d0-2b1c-4782-93c2-cf0e3eb24c70.png)
3) We are trying not to use the term user - how about 'visitor counts'.

It would be great if you created a Pull request with these changes and then posted a screenshot. But, I'd be surprised if either @jenlampton, @klonos, @olafgrabienski, or @BWPanda do not provide some even better suggestions. 

- Administration menu - Displays the various administrative menu options in the admin bar.
- Menu search - Provides a search option to quickly find specific items in the administrative menu.
- Visitor count - Displays the number of visitors currently logged into the site.
- Account links - Provides a link to the current visitors profile page a quick link to logout.

**Comment by RakeshPotnuru** [comment]
Done

**Comment by stpaultim** [comment]
@RakeshPotnuru Great work. I would like to see 1-2 people agree with these changes and/or offer ideas for improvement, before we mark this "Works for Me."

**Comment by RakeshPotnuru** [comment]
@stpaultim 
Can you just combine those two PRs, I don't know why commits are messing up

**Comment by BWPanda** [comment]
I'm not sure what happened between the above screenshot and the current PR, but the descriptions are messed up between the checkboxes (with one missing). Posted a review with some fixes and wording suggestions.

**Comment by stpaultim** [comment]
Putting my original suggestions next to @BWPanda's proposed changes for easier comparison (see notes on PR). 

PROPOSED:

Home menu - Provides a convenient link to the home page of the site, as well as quick links that allow you to clear the various caches, run cron, and run updates.
Administration menu - Displays the various administrative menu options in the admin bar.
Menu search - Provides a search option to quickly find specific items in the administrative menu.
Visitor count - Displays the number of visitors currently logged into the site.
Account links - Provides a link to the current visitors profile page a quick link to logout.

BWPanda Suggestions:

Home menu - **A specialized menu that links to the home page and provides links to perform various other admin tasks (e.g.: clear caches, run cron, etc.).**
Administration menu - Displays the various administrative menu options in the admin bar.
Menu search - **A drop-down version of the top-level links in the Administration Menu.** <Links to Admin menu>
**People counter - A count of the people currently logged into the site.**
**User account links - Links to view and log out of the current user account.**

Thanks @BWPanda, I like most of your suggestions, except "People Counter" - that one doesn't sound right to me, but I understand the concern about using the word visitor. Let's see if anyone else has a better idea?

**Comment by BWPanda** [comment]
> I like most of your suggestions, except "People Counter" - that one doesn't sound right to me

Me neither. What about just "Online" instead? Or "People online"?

**Comment by RakeshPotnuru** [comment]
@BWPanda , @stpaultim 
Should I confirm these changes?

**Comment by stpaultim** [comment]
@RakeshPotnuru - it's up to you. I expect it's likely that we'll get more suggestions regarding the text tomorrow. If I were you, I would hold off one more day. 

But, if you decide to make the changes - it does give others something to test in the sandbox.

**Comment by RakeshPotnuru** [comment]
> but the descriptions are messed up between the checkboxes.

Looking fine 🤔
<img width="944" alt="image" src="https://user-images.githubusercontent.com/70439799/159205211-e2fe7a69-2e70-4204-ad72-863bbddc032b.png">

**Comment by BWPanda** [comment]
Still some things that need fixing...

**Comment by stpaultim** [comment]
I believe that @RakeshPotnuru made the requested fixes.

**Comment by RakeshPotnuru** [comment]
Yes

**Comment by BWPanda** [comment]
PR still needs work.

**Comment by BWPanda** [comment]
Looks good now.

**Comment by BWPanda** [comment]
This PR needs work as we added a new component to core recently.

**Comment by RakeshPotnuru** [comment]
@BWPanda 
Sure. I'm not aware of the changes, can you explain the changes need to be added?

**Comment by BWPanda** [comment]
If you update your PR to use the latest 1.x code, you'll see a new component that just needs to be accounted for along with the rest.

**Comment by RakeshPotnuru** [comment]
What is the help text for "Page Links"?

**Comment by BWPanda** [comment]
I'd suggest something like:

"Links to edit items that make up the current page (e.g. layout, theme)."

**Comment by RakeshPotnuru** [comment]
I updated my PR only but don't know why 60 commits and 150 files changed 😐.

**Comment by BWPanda** [comment]
Hmm, something's gone wrong with updating the PR with the latest changes to core I think... Perhaps it'd be better to create a new branch off core's `1.x`, then add your changes there and make a new PR.

**Comment by BWPanda** [comment]
PR works and code looks good.

**Comment by quicksketch** [comment]
Thanks to all our Open Force participants on this issue! I merged https://github.com/backdrop/backdrop/pull/4086 into 1.x and 1.22.x.

https://github.com/backdrop/backdrop/commit/0c95ff6a34273fea5b85a9368831fc71b5739286 by @RakeshPotnuru, @BWPanda, @stpaultim, @klonos, and @mayankshrivastav003.
