### ISSUE TITLE
PHP warning on upgrade from Drupal 7 in system_get_date_formats()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5288]
**Description of the bug**

I'm seeing the following PHP warning when I upgrade sites from Drupal 7:

```
Warning: Invalid argument supplied for foreach() in system_get_date_formats() (line 3911 of system.module 
```

I know this isn't an issue because if you push past it and complete the upgrade everything then works fine, but it would be nice if we could avoid any kind of scary warnings during the upgrade process, which can be stressful enough :)

**Steps To Reproduce**

To reproduce the behavior:
1. Load in Drupal 7 database
2. Visit `core/update.php`
3. Error appears on this page

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.20.1
- Web server and its version:
- Operating System and its version:
- Browser(s) and their versions:

**Comment by quicksketch** [comment]
Thanks, merged https://github.com/backdrop/backdrop/pull/3786 into 1.x and 1.20.x!
