### ISSUE TITLE
PHP7.4 and empty entity_keys for taxonomy term result in notices

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#5290]
**Description of the bug**

Errors when navigating taxonomy entities during special scenarios when using PHP 7.4

```
Notice: Trying to access array offset on value of type null in entity_extract_ids()
(line 353 of /core/modules/entity/entity.module).
Notice: Trying to access array offset on value of type null in entity_extract_ids()
(line 353 of /core/modules/entity/entity.module).
Notice: Trying to access array offset on value of type null in entity_extract_ids()
(line 354 of /core/modules/entity/entity.module).
Notice: Trying to access array offset on value of type null in entity_extract_ids()
(line 354 of /core/modules/entity/entity.module).
```

**The Fix**

Apply the same fix as https://www.drupal.org/project/drupal/issues/3166668

**Steps To Reproduce**

To reproduce the behavior:
1) Ensure PHP 7.4 is used
2) Install display_suite and display_suite_ui from: https://github.com/backdrop-contrib/ds
3) Add a term to a vocabulary
4) Navigate to **Manage Display** and set the "select layout" to something other than **- None -** and save the display
5) Navigate to the term page and witness the errors

**Additional information**

See issue https://github.com/backdrop-contrib/ds/issues/5 for additional details where this problem was found.

Excerpt

> It seems that whenever a taxonomy term is rendered in a custom view mode it comes with empty entity_keys and this causes the lines 8000 and 8001 in includes/common.inc to through the above notices. The same notices are produced in the "Manege Display" page of the same content type.
This might have to do with Display Suite through which the custom view modes are created, but the issue would remain that the entity_extract_ids function can not cope with empty entity keys under PHP 7.4.

**Personal reference**
Backdrop location: /core/modules/entity/entity.module
Line: 352

**Comment by philsward** [comment]
Note: I have tested the suggested fix from the Drupal issue and the errors go away. I am unaware of any underlying problems this might cause with Backdrop.

**Comment by philsward** [comment]
Unfortunately, I don't know if this can be triggered in core as I suspect nothing in core will create empty keys. I would think core needs a way to deal with empty keys though to "protect" contrib from itself. Mostly over my head and since I produced it with DS and the Drupal issue referenced DS, it might be a one-off to DS.

**Comment by klonos** [comment]
Still worth some defensive coding, in order to protect contrib/custom module devs.

**Comment by indigoxela** [comment]
@philsward did you close this issue intentionally, or by accident?

**Comment by klonos** [comment]
Based on the PR that you've filed @philsward, I'm gonna take an educated guess and say that closing this issue was by accident.

**Comment by klonos** [comment]
Just a minor coding standard issue in the PR @philsward - otherwise looks good and is a direct cross-port of the respective D7 patch, which has been RTBC'ed.

**Comment by philsward** [comment]
If anything was closed outside of the bad PR I was originally struggling with, it was unintentional.

**Comment by philsward** [comment]
> Just a minor coding standard issue in the PR

Done. PR updated

**Comment by klonos** [comment]
Code now looks good, and tests are green. RTBC 👍🏼

**Comment by klonos** [comment]
@indigoxela can we please get the actual milestone added here? Thanks.

**Comment by quicksketch** [comment]
I couldn't understand _why_ this change is needed, but the numerous confirmations and reviews over in the Drupal issue gives me enough confidence to go ahead with this. Thanks @philsward for reporting the problem, doing the research, and porting the fix! Thanks @indigoxela, @klonos, and @jenlampton for their help!

I merged https://github.com/backdrop/backdrop/pull/3831 into 1.x and 1.20.x.
