### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: a[href*=

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5297]
**Description of the bug**

Creating anchor menu items like `<front>#anchor` as shown on the screenshot:

![Screen Shot 2021-10-11 at 11 59 30 AM](https://user-images.githubusercontent.com/56604405/136827799-ca6ad991-7e65-4371-a81d-4e380221e75e.png)

work as expected on UI, however on browser's console start giving lot's of incidents of the same errors:

`Uncaught Error: Syntax error, unrecognized expression: a[href*=#faq]`

**Additional information**

The issue is known and discussed on https://github.com/jquery/jquery/issues/2885, https://github.com/jquery/jquery/issues/2824, https://stackoverflow.com/questions/37033693/uncaught-error-syntax-error-unrecognized-expression-ahref-nothref, https://stackoverflow.com/questions/31197452/syntax-error-unrecognized-expression-for-href/31197472, however I'm not sure how this should be fixed on Backdrop.

Any alternative ways of creating anchor menus for one-page websites? Giving a try to `void_menu` and `one_page_nav` module didn't help as the error persists anyway.

**Comment by olafgrabienski** [comment]
Hm, I've built a site which uses such menu links (e.g. `<front>#insights`), and I don't see any error in the browser console when I use these links. In which situation does the error occur on your site?

**Comment by indigoxela** [comment]
I'm also using menu links like `/#myanchor` for quite some time and never saw that message in the browser console. What else is necessary to reproduce it? I didn't use any additional module for my links, so maybe it's caused by a module?

**Comment by indigoxela** [comment]
Hm, yes, *lots* of nagging in the console. All js-related, and aggregation is on, so I couldn't tell what's causing it.
(Note: anchors work without js, just in the browser.)
