### ISSUE TITLE
[DX] Add bc layer for system_get_date_types()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#530]
In Drupal 7 the function was named `system_get_date_types()` in Backdrop it's called `system_get_date_formats`.  Can we add a backwards-compatibility wrapper function for this into drupal.inc? 

Reported in http://enzolutions.com/articles/2014/12/29/backdrop-cms-first-impressions

**Comment by BWPanda** [comment]
Not sure if this is the right way to do it, but since the two functions return different attributes I altered the output of `system_get_date_formats()` to add in the attributes `system_get_date_types()` normally outputs.
