### ISSUE TITLE
Date Theme automated test fails from 23:00 to 23:59 UTC

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5303]
**Description of the bug**

Any PR that runs the automated tests between 23:00 and 23:59 UTC (i.e., between 4:00pm and 4:59pm in PDT) will fail the "Date Theme" test `DateThemeTestCase->testDateDisplayCombination()` at line 150.

**Steps To Reproduce**

To reproduce the behavior:

1. Enable Simpletest.
2. Wait until the current time is between 23:00 and 23:59 UTC (i.e., between 4:00pm and 4:59pm in PDT).
3. Run the "Date Theme" test.

Note that outside of this time window, the test will pass.

**Actual behavior**

The test fails. Specifically, the expected test will contain the string "7 days remaining" but the output value will be "6 days remaining".

**Expected behavior**

During this time interval, the correct value should be "6 days remaining."

**Additional information**

In the test code, the event start time is set 7 days out, but if the start time is >23:00, then the start time is pushed earlier by 1 hour (to keep the end time in the same day). But that means that there will only be 6 days until the event, since days remaining is rounded down.

It's an easy fix, but I question whether it's good practice to have an automated test in which the code branch executed depends on the time of day that the automated test happens to run.

We discovered this in https://github.com/backdrop/backdrop-issues/issues/5065.

**Comment by indigoxela** [comment]
Nice catch! That's one of our very-seldom-random-failures. And you finally found the root cause! :tada: 

RTBC!

**Comment by klonos** [comment]
Finally! ...we've tried to tackle this in #3794 and then again in #4180, but it was this bit that we were missing 🤦🏼 ...nice catch indeed @bugfolder 👍🏼 

> ...I question whether it's good practice to have an automated test in which the code branch executed depends on the time of day that the automated test happens to run.

It's a good thing I think ...we are randomly testing the randomness of this random thing 😅

**Comment by quicksketch** [comment]
Confirmed, I tested this locally and found that tests failed exactly between 4 and 5pm PT. Wow nice find @bugfolder!

**Comment by quicksketch** [comment]
Woohoo! Yay great job @bugfolder! I merged https://github.com/backdrop/backdrop/pull/3793 into 1.x and 1.20.x.
