### ISSUE TITLE
Form cache test not properly ported from Drupal

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5304]
This is a follow up to Issue #3375: Make cache_form expiration configurable, to mitigate runaway cache_form tables.
    
    By @klonos and @herbdool.
    
`FormsFormCacheTestCase` was added to the codebase, but never adapted from Drupal. It extends `DrupalWebTestCase` instead of `BackdropWebTestCase` and still has a `getInfo()` method. It was never added into `simpletest.tests.info` so has likely never been run. 

I stumbled across this while working on another issue that adds a test to this file. When I did a find/replace for DrupalWebTestCase/BackdropWebTestCase I caught an extra one I wasn't expecting!

**Comment by klonos** [comment]
> ...but never adapted from Drupal.

Doh! ...my bad 😓
