### ISSUE TITLE
Save button missing from theme settings form

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5308]
**Description of the bug**

We introduced [a change](https://github.com/backdrop/backdrop/pull/2614/files#diff-c518400aff0cb1100d3ceafbbe3514bf2f2a7d1249c126776e21b63ae9f62946R461) that removed the save button from the theme settings form. 

There were a handful of contrib modules that added settings to this form, but there is no way to save the form anymore, since the button is missing.

**Steps To Reproduce**

To reproduce the behavior:
1. Install CSS editor
2. Navigate to Seven theme settings form
3. Attempt to save CSS changes.

**Actual behavior**

The `Save theme settings` button is missing.

**Expected behavior**

The `Save theme settings` button should be available.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.20.1

**Comment by jenlampton** [comment]
I believe the intent of this change was to remove the button when there were no options in the form, but it was done in an unrelated issue (so probably should not have been done there at all). The current implementation removes the button even when there are options in the form. This PR restores the previous behavior.

If there is a desire to remove the button when there are no options in the form, we should make a dedicated issue for that change, where we can test that result specifically :)

**Comment by jenlampton** [comment]
> I understand that issue with contrib that is adding more settings to the theme settings page, but this PR is regressing this ("Save settings" button being present when there are no settings to save):

But that change ("Save settings" button being present when there are no settings to save) was unintended. It was lumped in with a unrelated change, so it was completely untested and also unreviewed -- which is why it broke things. 

As stated above:

> If there is a desire to remove the button when there are no options in the form, we should make a dedicated issue for that change, where we can test that result specifically :)

The priority here is to un-break the things that got broken because we did things the wrong way. If we want to change things in the right way, we can do that later :D

**Comment by klonos** [comment]
> I think the safest thing to do is to revert the change, and then move forward with fixing any issues with the button.

I was initially reluctant re reverting, but I have since reconsidered. There is no easy way to fix this properly, while in the meantime the current implementation is causing trouble in contrib-land.

**Comment by quicksketch** [comment]
Thanks folks. I merged https://github.com/backdrop/backdrop/pull/3797 into 1.x and 1.20.x.
