### ISSUE TITLE
PHP 8: Views Handlers: Filter: in_operator - Array to string conversion

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5313]
**Description of the bug**

Part of #5076

Failing tests with PHP 8:

```
---- Views Handlers: Filter: in_operator (ViewsHandlerFilterInOperator) ----

Status    Group      Filename          Line    Function                            
---------------------------------------------------------------------------------------------------
Exception Warning    views.module      1888                                                                            
    Array to string conversion
...
```

**Reason:** str_replace() chokes on nested array in `$condition['value']`

**Related Drupal commit and issue**

https://git.drupalcode.org/project/views/-/commit/75ea48e0e6bdae213c960090a0c8aea46db0c69a

https://www.drupal.org/project/views/issues/3207982

There are additional changes in that commit.

1. Small change in function postComment - not necessary in Backdrop, but doesn't do any harm (the actual functionality has been fixed for Backdrop in initial PHP 8 support PR.
2. Field test enhancement, which does not belong to the in_operator fix, but to #5314 - without that other fix, the test would fail, so moving the changes over there

**Comment by klonos** [comment]
> There are additional changes for code, that doesn't exist in Backdrop.

Yes they exist - just moved elsewhere in Backdrop: https://github.com/indigoxela/backdrop/pull/3

**Comment by indigoxela** [comment]
Riddles solved, issue description updated, back to "needs review".

@klonos I did a little less cleanup, only in the function that actually changes, to not bloat the PR.

**Comment by quicksketch** [comment]
Excellent, thank you @indigoxela! I merged https://github.com/backdrop/backdrop/pull/3799 into 1.x and 1.20.x.
