### ISSUE TITLE
[DX] Fix function description for system_theme_settings()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5315]
It currently says this (see https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.admin.inc#L400):

```php
/**
 * Form builder; display theme configuration for entire site and individual themes.
 *
```

(btw, this line also exceeds the 80 characters limit)

...but in #130 we've removed the global theme settings page at `admin/appearance/settings`, so the description should be changed to:

`Form builder; display configuration for individual themes.`

**Comment by BWPanda** [comment]
Looks good to me.

**Comment by quicksketch** [comment]
@BWPanda Thanks for finding and reviewing this issue! I merged https://github.com/backdrop/backdrop/pull/3801 into 1.x and 1.22.x. Thanks @klonos :smile:
