### ISSUE TITLE
[BC] Missing function views_ui_build_form_url()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5323]
In Drupal 7 Views UI had a function `views_ui_build_form_url()` that was not included in Backdrop. Some D7 contrib modules use this function. I recommend we add it back, and mark it as deprecated for 2.x.

```
function views_ui_build_form_url($form_state) {
  $form = views_ui_ajax_forms($form_state['form_key']);
  $ajax = empty($form_state['ajax']) ? 'nojs' : 'ajax';
  $name = $form_state['view']->name;
  $url = "admin/structure/views/{$ajax}/{$form_state['form_key']}/{$name}/{$form_state['display_id']}";
  foreach ($form['args'] as $arg) {
    $url .= '/' . $form_state[$arg];
  }
  return $url;
}
```
It looks like this function was renamed (and reworked) into `views_ui_build_form_path()` in Backdrop. This could use a change record.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/3803. Thanks @jenlampton and @klonos!
