### ISSUE TITLE
[UX] Some UI improvements to Book module

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5331]
Breaking up https://github.com/backdrop/backdrop-issues/issues/3639 into some easier chunks.

- [x] at `admin/content/book` change the tab title to "Manage books"
- [x] fix the breadcrumb when at `admin/content/book/%`
- [x] Remove the Outline tab on nodes (`node/%/outline`). We have a "Book outline" vertical tab on the node edit with the exact same form.
- [x] add a "Remove from book outline" link to vertical tab on node edit.
- [x] add a "Reorder book pages" link to vertical tab on node edit.
- [x] Make "Content type for child pages" into select list. `admin/content/book/settings`
- [ ] fix entity cache issue when removing node from book outline

----
Part of META https://github.com/backdrop/backdrop-issues/issues/3639

ADVOCATE: @stpaultim

**Comment by klonos** [comment]
Thanks for reviving this meta-issue @herbdool 🙏🏼 

I've played a bit with the PR sandbox, and I have plenty of feedback - just no time to type everything now. I'll come back to this soon.

**Comment by stpaultim** [comment]
How does this PR relate to: https://github.com/backdrop/backdrop-issues/issues/5331

**Comment by herbdool** [comment]
@stpaultim they're both part of the same META.

**Comment by stpaultim** [comment]
Was working on a new PR that fixes some of these problems, but then we found this one. This is really good. I've done a little testing and found one problem. 

The "Reorder book pages" link should not show up unless the page has been added to an outline already. In it's current state, this link takes user to a broken page.

![image](https://user-images.githubusercontent.com/3144571/159643965-224d8eb4-92e7-4d7a-981f-6d15baf8902b.png)

**Comment by herbdool** [comment]
@stpaultim thanks for trying this out. I've added a fix.

I guess the one downside of removing the Outline tab is that it makes it more awkward to edit the book outline. If someone adds a page to the book they won't see those links until the edit the node and go back to the vertical tab. Maybe only remove the outline tab for content types that aren't assigned to be parts of books? (There's an issue in the META I think).

**Comment by stpaultim** [comment]
I tested again. This looks very good. Marking this "Works for Me." Just needs a code review to get into 1.22.0 (I hope).

**Comment by stpaultim** [comment]
Since, my other issue got in, I think I can advocate for this and add it to the milestone.

**Comment by stpaultim** [comment]
> I guess the one downside of removing the Outline tab is that it makes it more awkward to edit the book outline. If someone adds a page to the book they won't see those links until the edit the node and go back to the vertical tab. Maybe only remove the outline tab for content types that aren't assigned to be parts of books?

For those who don't fully know what the implications are, book pages currently have two "Outline" tabs. A vertical tab on the edit page and a horizontal tab that is visible for both edit and view modes.

Herb's PR removes the horizontal tab at the top and leaves ONLY the vertical tab on the edit page. 

Personally, I found that having both tabs was confusing, especially because neither of them really let you edit the order of the outline, which is what I was looking for - before I found your PR. 

I'm fine with your current suggestion. Another possible idea would be to put a link to the "Order Outline" page next to the "Add child page" link on nodes (see screenshot below).

I am very happy with your changes here and don't think we need to do anything else. But, I'd like to hear if anyone else has feedback. 

NOTE: I've been using the book module quite a bit lately, so my feedback is based upon real world usage.

BEFORE

![image](https://user-images.githubusercontent.com/3144571/165669709-0e0eb82d-121c-4184-baa5-97b68fa9d9f8.png)

AFTER

![image](https://user-images.githubusercontent.com/3144571/165669998-ea7179e0-117a-4136-bdae-a76f36fc312e.png)

Another idea?

![image](https://user-images.githubusercontent.com/3144571/165670404-2f9aa3cc-0a06-4155-b406-2ddefa336379.png)

**Comment by stpaultim** [comment]
@quicksketch - FYI, this PR might still be possible for 1.22.0.

**Comment by indigoxela** [comment]
Great work! I rarely use book with D7, never so far with B, but I see the huge improvement. (Some of those remind me of the book_made_simple module in D.) This PR clearly removes some of the oddest UX moments with books.

The code looks good, too. RTBC :+1:

**Comment by indigoxela** [comment]
Maybe worth a mention: I'm happy that the "Outline" tab/page gets removed. It actually never was very useful, as it's more likely that people want to edit these things in the node form. And they now can do all necessary things without clicking through the admin interface.

BUT...

RTBC'd too soon, I found a flaw: a permission check on the newly added links is missing - a user who can create/add book pages also gets the link "Reorder book pages", but as expected it leads to "Forbidden" (user has no permission to "Administer book outlines"). @herbdool shouldn't be too hard to fix, though.

**Comment by herbdool** [comment]
@indigoxela thank you. I've made the fix.

**Comment by stpaultim** [comment]
@herbdool - This is a small piece of feedback that @klonos gave during the meeting and could be discussed/fixed now or put into a follow-up issue.

![image](https://user-images.githubusercontent.com/3144571/166073188-dfe45352-2332-4c25-b4eb-7abce3ba84d5.png)

He pointed out that the "+" icon was little strange next to a link to REMOVE something. 

Do we use "+" icon elsewhere in core for this type of thing? It seems familiar, but I'm not sure where to look.

**Comment by stpaultim** [comment]
For the record, I went looking for other uses of the "+" icon. I'll add some of them here.

![image](https://user-images.githubusercontent.com/3144571/166073654-3f256fe7-f184-4a79-858f-976592037a9f.png)

**Comment by stpaultim** [comment]
@herbdool Maybe this is a useful example of something similar.

![image](https://user-images.githubusercontent.com/3144571/166074346-62a76865-7054-412c-a06a-9519972daf2a.png)

**Comment by herbdool** [comment]
@stpaultim sounds like that should be done in a follow-up since the action array in the form is generating the plus sign automatically. I don't think there's any choice here.

**Comment by herbdool** [comment]
I guess the code is assigning them the "action-links" class so I suppose that is optional.

**Comment by quicksketch** [comment]
I found that after you remove a book page from an outline, it is given the book `<none>` when editing. Why don't we just make that option always available, so instead of taking the user to a new page to remove from the book, they can just select `<none>` and then save the node? It's also less potentially dangerous, since we're not taking the user away from the node form when they may have made other changes at the same time.

![image](https://user-images.githubusercontent.com/100206/166079499-7018be2e-e365-4ebc-8227-97132d885a38.png)

If we pursue this route, we can also remove the `/node/x/outline-remove` page callback.

**Comment by docwilmot** [comment]
The + image is CSS (`ul-action-links a` ). We could just override that for node pages.

**Comment by herbdool** [comment]
I'm thinking that @quicksketch suggestion might work but better as a follow-up. I think it may get complicated when trying to remove the top page from the book.

I've removed the + symbol from the links.

![2022-04-30 00 33 22 backdrop-contrib lndo site 54e2ada5697a](https://user-images.githubusercontent.com/1071483/166091962-e4f65e02-25db-488e-a02e-d6ea16859519.png)

I've added a tweak to add links to reorder. @stpaultim suggested next to the "Add child page" so I've done that. And I've also added a message after saving with a link to the reorder page. Both only show if the user has access.

![2022-04-30 00 33 55 backdrop-contrib lndo site ce5bc441d658](https://user-images.githubusercontent.com/1071483/166091963-1d283b89-8c54-449c-a0eb-2d488257b866.png)

**Comment by stpaultim** [comment]
@herbdool - I like it. I hope this means that you liked the "reorder book" link idea. I was just throwing it out there for discussion, but I do like it. As a follow-up issue, I'd like to figure out how to make it look better. BUT, I think it's an improvement and great for now. 

I just played around a bit with creating some book pages in the sandbox site and I think this is a MUCH easier UI to use than what we had before. Works for Me.

**Comment by stpaultim** [comment]
Sorry, I found another permissions problem. 

![image](https://user-images.githubusercontent.com/3144571/166093180-8e188812-ce21-4b57-bd1c-c3736126cd41.png)

This "Test Editor" does not have "Administer Book Outlines" permission. They are shown this link, but access is forbidden.

**Comment by indigoxela** [comment]
> This "Test Editor" does not have "Administer Book Outlines" permission. They are shown this link, but access is forbidden. Very similar to theThis "Test Editor" does not have "Administer Book Outlines" permission. They are shown this link, but access is forbidden. Very similar to the problem that @indigoxela found earlier. problem that @indigoxela found earlier.

What we could try:

- Get rid of the "Remove from book outline" link
- Add a "none" option in the select list of existing books - *only* if the user has permission for that

The rest of the current permission handling seems correct now.

@herbdool I don't think this should be a follow-up, because currently it can happen that links show up, that lead to 403 - which we should fix before even merging.

**Comment by herbdool** [comment]
@stpaultim thanks, I've fixed the access. It should have used `_book_outline_remove_access()` function. Before it was only checking if it was removable and not the user access.

@indigoxela I would prefer the follow-up because I think there will be some complications changing the UI plus I think I've fixed the access issue.

**Comment by indigoxela** [comment]
> I would prefer the follow-up because I think there will be some complications

Fair enough, if you expect complications, let's discuss that in a follow-up.

Yes, the access issues with the link display are fixed now. :+1:

**Comment by indigoxela** [comment]
@herbdool I left another question on your PR - maybe I misunderstand the intention, but I think the update hook isn't working correctly yet.

**Comment by herbdool** [comment]
@indigoxela thanks. Didn't want to overwrite the "add child" option. I think I've fixed it now.

**Comment by argiepiano** [comment]
@herbdool I just added a comment after your very last commit push. I'm not familiar with the issue or the PR, but I noticed you're changing the json structure of the settings file with the last commit

**Comment by herbdool** [comment]
@argiepiano fixed. Depending on whether someone saves the form or not, the array could be either an associative array or not. One of the quirks of the forms.

**Comment by stpaultim** [comment]
@argiepiano, @indigoxela, @docwilmot or @quicksketch - any of you available to take a final look at code and mark as RTBC (if it is)? 

I've done one more test and I can't find any bugs. It seems to be working as expected. I've tested the permissions issues again and they seem to be resolved.

**Comment by argiepiano** [comment]
I'm tied up with final exams today all day but did a mini-test and am finding some issues with this. I don't know if these are related to the PR, or independent (I don't have the time to check)

1. Create a page and save it
2. Click the Outline tab
3. Select <Create a new book> and click Add to book outline
4. Click Outline again. The Book select list still says <none>
5. Select <Create a new book> again
6. Click "Add to book outline"

I get `PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9' for key 'nid': INSERT INTO {book} (`nid`, `mlid`, `bid`)`

**Comment by stpaultim** [comment]
I have not been able to recreate that problem yet, but I tried VERY quickly.

I am finding this in the logs. Is this a known issue. It's not clear to me if it's related to this PR.

![image](https://user-images.githubusercontent.com/3144571/166125297-98fd611e-1e9c-4668-b6d8-67a698ec8a08.png)

**Comment by herbdool** [comment]
@stpaultim that's a known issue. There's a different issue for it.

@argiepiano are you testing the pr? There's no Outline tab anymore. Unless you mean that you clicked Edit and then went to the Book vertical tab. At any rate I don't see how that error is related. This PR doesn't make any db changes

**Comment by stpaultim** [comment]
@argiepiano - I got to run myself. I'm not able to recreate your problem in the PR sandbox. Actually, I'm confused about step 3. I don't know what you are doing there.

@herbdool - Thanks for clarifying the known issue.

I'll be back later.

**Comment by argiepiano** [comment]
> @argiepiano - I got to run myself. I'm not able to recreate your problem in the PR sandbox. Actually, I'm confused about step 3. I don't know what you are doing there.

Oops! Actually I hadn't applied the patch 🤦🏽

**Comment by quicksketch** [comment]
All these changes are definitely improvements, and now with all access issues fixed, tests updated, and manual testing approved, I think this is ready to go.

I don't think the presentation is perfect, the links feel like they're floating without any styling, both on the node page and in the vertical tab... but I think it's important that they have been added to help management of books. I get the impression further changes are still in mind, so I'm in favor of moving this in and continuing in additional issues.

I've merged https://github.com/backdrop/backdrop/pull/3809 into 1.x for 1.22.0. Thanks @herbdool, @stpaultim, @indigoxela, @argiepiano, @docwilmot, and @klonos!

**Comment by stpaultim** [comment]
@herbdool Congratulations for getting this in and thanks for getting this in. I think I already mentioned that I was recently fighting with the book module and started a PR of my own to do these same things. Your changes are even better!
