### ISSUE TITLE
New user one-time-login link incorrectly states that email link will expire

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5333]
This was brought up in [Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/One.20time.20login.20link/near/253434839), and @jenlampton found the respective issue in the D7 issue queue: https://www.drupal.org/project/drupal/issues/1914628

**Comment by olafgrabienski** [comment]
> If there's still an issue here, let's update the title and OP accordingly. If not, let's close.

Closing as the title hasn't been updated. @klonos Feel free to reopen and adjust, or open a new one that fits better.

**Comment by klonos** [comment]
Thanks @olafgrabienski ...it's OK, as this seems to not apply to Backdrop.

I've raised #5414 instead.
