### ISSUE TITLE
[DX] Add bc layer for user_format_name() vs format_username()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#534]
Drupal 7 had `format_username()` but backdrop has 'user_format_name()`.

Can we please add a backwards-compatible function into drupal.inc for format_username?

**Comment by quicksketch** [comment]
Seems like we might be better off just putting back the old function. We probably inherited this from early D8 changes.

**Comment by BWPanda** [comment]
I considered both options, but went with @jenlampton's suggestion as it does seem that this function is a part of the User module and therefore should be named as such (it was also a much easier PR :wink:).
