### ISSUE TITLE
Dependencies version check not working for modules that use three digits (e.g. 1.0.14)

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5356]
**Description of the bug**

The dependencies version check specified in `info` files doesn't work properly when checking the version of a module that uses 3 digits for versioning, such as `entity_plus (>1.0.14)`. 

**Steps To Reproduce**

1. Create a custom module. In the info file, specify a dependency from a specific version of another module that uses three digits to define its version. For example, `dependencies[] = entity_plus (>1.0.14)`. 
2. Try to enable the module. Backdrop should not allow this module to be enable (for this example, the latest available version of Entity Plus is 1.0.13). 

**Actual behavior**
Backdrop allows you to enable the custom module.

**Expected behavior**
Backdrop should not allow the custom module to be enabled, since, in this example, it depends on a version of Entity Plus that is not yet available.   (Note: this issue happens regardless of the module, as long as its version uses 3 digits instead of 2).

**Additional information**

It seems like the version check performed by core's function `backdrop_parse_dependency()` is only extracting the first two digits of the version, and ignores the third digit. For example, using Devel, run the following:

```php
dpm(backdrop_parse_dependency('entity_plus (>1.0.14)'));
```

You will obtain the attached screenshot. The important array key here is `version`, whose value is `1.0` instead of `1.0.14`, resulting on a failed check.

I don't have enough knowledge of RegExp to rewrite the pattern to output the version correctly.  

<img width="606" alt="Screen Shot 2021-11-17 at 10 27 17 AM" src="https://user-images.githubusercontent.com/9938978/142252749-5adc4c53-68c2-4797-9ad7-55d11c01163e.png">

**Comment by argiepiano** [comment]
On the other hand, this may perhaps be the correct behavior for version check? Perhaps the problem is that modules are not supposed to use a third "sub-version" number beyond `major.minor`? This article seems to confirm this suspicion  https://www.drupal.org/docs/8/understanding-drupal-version-numbers/what-do-version-numbers-mean-on-contributed-modules-and

**Comment by indigoxela** [comment]
> Perhaps the problem is that modules are not supposed to use a third "sub-version" number beyond major.minor?

If that were true, we're in big trouble :wink:

Modules *are* supposed to have `major.minor.patch` numbers, but maybe the dependency check isn't supposed to handle the patch level?

**Comment by argiepiano** [comment]
> but maybe the dependency check isn't supposed to handle the patch level?

@indigoxela that's what I'm suspecting now. However, I think it would be great to be able to check `patch` in the dependencies check.

**Comment by indigoxela** [comment]
Large parts of [that function](https://github.com/backdrop/backdrop/blob/a7eb98928bbc1c1ee923217d5ce1a3be1abaf87b/core/includes/common.inc#L8653) haven't been touched for a while.

My suspicion is that omitting the patch level is just an oversight, as the function is in large parts unchanged since D7.

- D7 version examples: 7.x-2.10, 7.x-3.0-beta1
- B version examples: 1.x-2.15.0, 1.x-1.0.0-alpha2

Maybe it's time to overhaul that function.

**Comment by laryn** [comment]
Seems like a good idea to me. I haven’t had a chance to test the PR yet.

**Comment by stpaultim** [comment]
@argiepiano has indicated that he would like to advocate for this issue, so I'm going to add it to the milestone.

**Comment by klonos** [comment]
I've changed the milestone of this issue to the 1.20.3 release, since this is a bug fix - not a new feature. We don't have to wait till January for this to get into 1.21.0 😉

**Comment by herbdool** [comment]
That link @argiepiano seems to be from before Drupal adopted semantic versioning. Backdrop has had semantic versioning from the start. So I would say your PR makes sense. Backdrop should be like Composer in that exact versions can be specified if needed (https://getcomposer.org/doc/articles/versions.md).

**Comment by herbdool** [comment]
I've tested and reviewed the code. It looks good to me.

**Comment by stpaultim** [comment]
During the last Backdrop LIVE there was a lot of talk about making "alpha" projects more discoverable - so that folks evaluating Backdrop are aware of the projects, but potentially preventing installation through the project installer. 

This way users can find that there is work being done on Display Suites or Organic Groups, but they won't be able to install it easily through the project browser and potentially break their sites. But, those who are interested see that it exists and can manually install it and test if it they so choose. 

Is that issue related to this one? 

Is there already an issue for what I'm talking about or should that become a follow-up issue?

**Comment by indigoxela** [comment]
@stpaultim I think this is unrelated here. And I don't know of any existing issue regarding visible but not installable projects in the project browser.

**Comment by stpaultim** [comment]
> I think this is unrelated here. And I don't know of any existing issue regarding visible but not installable projects in the project browser.

@indigoxela - Thanks. I can see that this are probably different issues, although I can see where this one might be a requirement for the other. I'm not sure if there is any consensus on the other, but it came up in several sessions during Backdrop LIVE and I think we need a ticket to discuss it. 

I'm also not sure if this is a core issue or Backdropcms.org issue. @klonos - where do we need to make this issue?

**Comment by herbdool** [comment]
@stpaultim this issue won't affect what you're thinking of. Can you move the discussion to zulip until you've figured out where to make an issue?

**Comment by klonos** [comment]
@stpaultim that is more related to #664 ...still not the same, but as @herbdool said, let's take the discussion there, and figure out things.

**Comment by quicksketch** [comment]
The code additions look great to me, nice work @argiepiano!

We need expanded test coverage for the new dependency checking. There are existing tests in `ModuleVersionTestCase::testModuleVersions()` (in `system.test`) that I think could be expanded to include the bug fix numbers.

**Comment by argiepiano** [comment]
I have added a commit with a modified version of the test that checks version dependency. Questions:

- For comparisons with a RELEASED version of a module (in the test this module is called `common_test.module`) I'm using a comparison against a  "normal" release pattern consisting of `major.minor.patch[-extra]`. In the test, the version of `common_test.module` is 1.x-2.4.5-beta3.  
- For comparisons with DEV versions of a module, I've kept the original dev pattern present in the original test: `1.x-2.x-dev` . I believe that modules in dev stages do not use a "patch" portion - only the major version, and an "x" to indicate this is the dev version, like so:  "1.x-2.x-dev"

If this is not correct, please let me know.

**Comment by herbdool** [comment]
Looks good. Thanks for adding the test.

**Comment by quicksketch** [comment]
Thanks @argiepiano! The approach you've used and comparisons look good to me. However, I think some of the test coverage doesn't reflect actual usage. Modules declaring a dependency of a major version only will use `>=2.x`. In the test coverage you changed the comparison to `>=2.x.x`. While it's nice that will work, I don't think that would line up with actual dependency declarations. So I would recommend the places where we're doing major version comparison, we revert back to the previous checking. I left comments in a review: https://github.com/backdrop/backdrop/pull/3827#pullrequestreview-823523818

**Comment by argiepiano** [comment]
Thanks @quicksketch . I've made the adjustments you suggested. All tests passed. Let me know if you see anything else, or if it's RTBC

**Comment by argiepiano** [comment]
@quicksketch , after your comment about checking on major versions, I want to triple-check that the following is the expected behavior.

- Assume you have installed Entity Plus version 1.0.13
- If your custom module had this dependency: `dependencies[] = entity_plus (>1.0)`, would this mean that you need any version higher than version 1.0 of Entity Plus to install? 

If the answer to the above is "yes", then we have a problem. 

This line `dependencies[] = entity_plus (>1.0)` would allow your module to be enabled with Entity Plus version 1.0.13, since the check considers 1.0.13 higher than 1.0. 

To disallow installation in this case you would need `dependencies[] = entity_plus (>1.0.x)` (notice the "x" in patch. This line would mean you need at least version 1.2 of Entity Plus), OR `dependencies[] = entity_plus (>=1.2)`

Please verify that this is the expected behavior?

**Comment by quicksketch** [comment]
> This line dependencies[] = entity_plus (>1.0) would allow your module to be enabled with Entity Plus version 1.0.13, since the check considers 1.0.13 higher than 1.0.

Sounds right to me :+1:

> To disallow installation in this case you would need dependencies[] = entity_plus (>1.0.x) (notice the "x" in patch. This line would mean you need at least version 1.1 of Entity Plus), OR dependencies[] = entity_plus (>=1.1)

Initially, I would have expected `dependencies[] = entity_plus (>1.0.x)` to be the same as `dependencies[] = entity_plus (>1.0)`, but pondering on this I think I see why they're different. `>1.0.x` means greater than any possible value of `x`. `>1.0` means greater than `1.0.0`. Makes sense (I think).

In both cases, things can be made a lot less confusing by using `>=` and I think that's what we'd want to encourage people to use. In which case, both of these mean "any version of 1.x.y":

```
dependencies[] = entity_plus (>=1.0)
dependencies[] = entity_plus (>=1.0.x)
```

**Comment by quicksketch** [comment]
Current code looks good to me. @herbdool could you post your thoughts on if you think everything from @argiepiano is correct?

**Comment by herbdool** [comment]
I think it's okay. I agree about encouraging `>=`. People should be explicit about the minimum version that *does* work, rather than specifying the version that doesn't work.

**Comment by laryn** [comment]
Thank you @argiepiano for filing and fixing! Thanks @quicksketch and @herbdool for code review and help, and to @indigoxela, @klonos and @stpaultim for feedback along the way. Merged https://github.com/backdrop/backdrop/pull/3827 into 1.x and 1.20.x.

**Comment by argiepiano** [comment]
@quicksketch , I believe it'd be a good idea to modify the dependency description in[ this page](https://docs.backdropcms.org/creating-modules). I'm not sure how/where to create an issue to do that, or who has edit access to that page.

**Comment by quicksketch** [comment]
Thanks @argiepiano! I updated that page. The list of people that have access to certain roles on websites is documented at https://backdropcms.org/user-guide/roles-responsibilities-and-points-of-contact

**Comment by klonos** [comment]
@argiepiano https://github.com/backdrop-ops/docs.backdropcms.org is the repo to report issues for the api/documentation site (both the site itself, as well as documentation requests).

Having said that though, I'd suggest posting something in Zulip to request access to directly edit pages in docs.b.org.

**Comment by jenlampton** [comment]
@laryn can you leave the `type - ` labels on issues when you merge the PRs? Those are used when our release notes are automatically generated :)

**Comment by laryn** [comment]
Duly noted!

**Comment by jenlampton** [comment]
Ty!
