### ISSUE TITLE
Update CKEditor to 4.17.1

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5358]
**Description of the need**

CKEditor 4.17.0 (and 4.17.1) were released today with security updates and bug fixes. Since this issue is in a 3rd party and reported publicly already, I've opened this in the public queue so we can file pull request normally.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/3826.

Some good news in this update: CKEditor's build tool has gotten better so that we don't have to manually exclude files after downloading the build zip file. I updated our `build-config.js` to ignore all the files we normally remove by hand.

**Comment by quicksketch** [comment]
I tested this update and seems that everything is still working:

- Image uploading and library
- Link dialog
- Image alignment and captions
- Paste image from clipboard
- Saving content

**Comment by indigoxela** [comment]
I also did some testing:

- Editor configuration (adding items to toolbar, adding styles)
- Using dialogs (link / image)
- Maximize editor, use dialogs
- Saving content, also when in source mode

Everything works as expected.
I don't think that "feature request" is the right label, as this is also related to security and should go into 1.20.2.

**Comment by herbdool** [comment]
@quicksketch I made a comment in the PR. Previously there were a few commented out items so they're not included in Backdrop. Should they be commented out again?

Other than that it looks fine. Mind you I didn't go through it with a fine-toothed comb since it's all minified.

**Comment by quicksketch** [comment]
> Previously there were a few commented out items so they're not included in Backdrop. Should they be commented out again?

We don't need to comment them out any more. CKEditor's build tool now respects skipping all files, so this will make updating easier in the future. We used to need to manually remove files after downloading the build, now it will actually omit those files entirely.

**Comment by herbdool** [comment]
Looks good to me!

**Comment by laryn** [comment]
Thanks for setting up the PR @quicksketch and for the testing/review @indigoxela and @herbdool -- I've merged in to `1.x` and `1.19.x`.
