### ISSUE TITLE
PHP Fatal error:  LayoutRendererStandard::prepareBlocks on upgrade from 1.19.x to 1.20.x

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5361]
**Description of the bug**

I have one site that has its own unique hosting environment and I can't use Drush or Bee or the Project Installer to do updates. Basically I have to do the old SFTP method, replacing the `core` directory. I just tried to update from `1.19.3` to `1.20.2` and got this error:

> mod_fcgid: stderr: PHP Fatal error:  LayoutRendererStandard::prepareBlocks(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;ViewsBlock&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /app/core/modules/layout/plugins/renderers/layout_renderer_standard.inc on line 216

I am trying to copy over `1.19.5` to bring the site back (hopefully) and then will have to try to figure out what this means.

**Comment by indigoxela** [comment]
There has been a change in the Layout module to include layout_relationship, maybe it has something to do with that? Doesn't seem reasonable, though. None of the recent changes in the Views module explains the problem for me.

Tricky, no access other than FTP... have you tried to flush all caches before running the update?
Or do you have access to the database and are able to truncate cache tables?

**Comment by laryn** [comment]
Unfortunately I feel a little hamstrung on this server -- I've asked for a variety of different levels of access and the host either can't or won't provide them. And the group has not jumped at the suggestion to find a different host. I have a ticket in to the host and will update here.

**Comment by indigoxela** [comment]
> Strangely, copying back all the way to 1.19.3 doesn't even work... Maybe a cache thing but ARGH.

Cache - that's what I'd also assume. But which level? Appears to me like it's further down, maybe PHP opcache?

Do you still have an open admin session? Can you access /admin/config/development/performance?

(Re poor hosting - I feel with you.)

**Comment by laryn** [comment]
To tie this shut for anyone who ends up here through a search: I cleared opcache and it didn't do anything. Then I got access to the MySQL database for the site and truncated/emptied all the tables that start with `cache` -- and the site came back.

Thanks for helping @indigoxela!
