### ISSUE TITLE
Issue with layout--flexible.tpl.php in 1.20.2 release

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5362]
**Description of the bug**

This is about Backdrop 1.20.2 that was just released! 

[Line 41](https://github.com/backdrop/backdrop/blob/f2f06b21be18b875ed6da1f3d69fe4b054dbcdca/core/modules/layout/templates/layout--flexible.tpl.php#L41) of the file `core/modules/layout/templates/layout--flexible.tpl.php` results in the string "Row" being displayed in some layouts. This seems to be an unintended remain of some sort of testing.

```html
 <span class="text"><?php print t('Row'); ?></span> 
```

**Comment by argiepiano** [comment]
See image for output of this bug
<img width="502" alt="Screen Shot 2021-11-19 at 1 42 01 PM" src="https://user-images.githubusercontent.com/9938978/142689162-00e621c8-7132-4907-a28b-34b67c5914ef.png">

**Comment by laryn** [comment]
Looks like we had a chance to fix it before release and missed it. 😞 
https://github.com/backdrop/backdrop-issues/issues/5343

**Comment by laryn** [comment]
@argiepiano I'll close this as a duplicate -- if you test the PR there can you report back?

**Comment by argiepiano** [comment]
Temporary solution is to copy the old `core/modules/layout/templates/layout--flexible.tpl.php` from the previous release
