### ISSUE TITLE
height: 100vh declaration in layout class from layout.css causes huge whitespace under certain conditions

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#5364]
**Description of the bug**

Under certain conditions, lots of whitespace on a page is caused by the .layout class declaration height: 100vh; in the layout.css file.

I am guessing the primary cause is from a layout nested inside another layout which was probably never originally intended. I have not observed the bug outside of a nested layout.

When asked about the 100vh, I was told:

> I believe it is so in order to "push" the footer to the bottom of the page when content is not enough to do so.

**Steps To Reproduce**

To reproduce the behavior:
1. Insert a layout inside another layout. If this is not currently possible through core, use a helper module such as: [mini_layouts](https://github.com/backdrop-contrib/mini_layouts)
2. Visit a page that contains the nested layout and observe the 100vh in action.

**Actual behavior**

![image](https://user-images.githubusercontent.com/3436110/142758457-76457ad6-9136-4c44-a1e8-18421bc03cc8.png)

**Expected behavior**

No unnecessary whitespace.

**Workaround**

Find the class of the nested layout and manually override the css to remove the forced height.

**Additional information**

Add any other information that could help, such as:
- Backdrop CMS version: 1.20.2
- Web server and its version: Apache 2.4 PHP 7.4
- Browser(s) and their versions: Chrome 95.0.4638.69

Untested but also not currently using Layouts but might in the future is Display Suite.

**Comment by indigoxela** [comment]
Yes, that's a known problem in **Basis** (and Bartik), at least, I know it - but usually don't use Basis.

This is a link to the actual declaration: https://github.com/backdrop/backdrop/blob/a7eb98928bbc1c1ee923217d5ce1a3be1abaf87b/core/themes/basis/css/layout.css#L18

Yes, this seems push the footer down, when the page content is small. Maybe we find a more compatible way to do that.

**Comment by klonos** [comment]
If the mini layouts functionality makes it into core, then this issue should be solved in core. As it is though, it seems to me that it should be solved in the mini_layouts module, since the module can add classes that identify a mini/nested layout, and then override this specific CSS.

**Comment by philsward** [comment]
Sorry, completely spaced on checking the path of the layout.css file. It indeed comes from the Basis theme.

Unless there is reason to keep this open, feel free to close it.

**Comment by klonos** [comment]
This is a valid bug report - just the wrong queue I think. I believe it should be in https://github.com/backdrop-contrib/mini_layouts/issues rather than in core.
