### ISSUE TITLE
[DX]: Fixed: Add default value for options in `system_transliterate_machine_name()`.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5365]
**Description of the bug**

Two issues:
- In `system_transliterate_machine_name($string, $options)` the `$options` parameter needs a default value, since its not required. In other words, calling `system_transliterate_machine_name('string')` causes a fatal; you have to explicitly set an empty options array: `system_transliterate_machine_name('string', array())`. The funtion should be defined as `system_transliterate_machine_name($string, $options = array())` .
- Not really a bug, but this function is really useful to create machine names from entered strings; the `machine_name` element does this with JS (`core/misc/machine-name.js`) and there is no other PHP function that does this, AFAIK. So we should move it to `system.module` not `system.admin.inc` so other modules can use it without including that inc file.

**Comment by klonos** [comment]
> ...the `$options` parameter needs a default value, since its not required.

Isn't that handled by this existing bit of code in the function?:

```php
  $defaults = array(
    'langcode' => $GLOBALS['language']->langcode,
    'replace' => '_',
    'replace_pattern' => NULL,
    'maxlength' => NULL,
  );
  $options = array_intersect_key($options, $defaults) + $defaults;
```

**Comment by docwilmot** [comment]
It isnt unfortunately. The line `$options = array_intersect_key($options, $defaults) + $defaults`  assumes that `$options` is set. 

In other words, calling `system_transliterate_machine_name('string')` causes a fatal; you have to explicitly set an empty options array: `system_transliterate_machine_name('string'. array())`. The funtion should be defined as `system_transliterate_machine_name($string, $options = array())` . Added this to the OP.

**Comment by najmieh** [comment]
@docwilmot Hi, which files should be edited for these two issues? Can you provide their names or a links to them? Thank you :)

**Comment by docwilmot** [comment]
Hello @najmieh, you can always find which files function live in by searching on the documentation site, in this case [you'll find this function here](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.admin.inc/function/system_transliterate_machine_name/1).

**Comment by najmieh** [comment]
@docwilmot I just have a tiny bit of difficulty finding the documentation on Github. Is it this one, https://github.com/backdrop-ops/docs.backdropcms.org ? Or should I search solely based on the provided code you mentioned above? Thank you for your help.

**Comment by indigoxela** [comment]
Hi @najmieh and welcome to Backdrop!

Our official documentation isn't on Github. We have our own docs site.

The function documentation you search for is [here on docs.backdropcms.org](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.admin.inc/function/system_transliterate_machine_name/1)

As you can see there, that function is in core/modules/system/system.admin.inc.

And here's a link to the actual [sources on Github](https://github.com/backdrop/backdrop/blob/835438c1c59d6fdae626f10a143aae9a089ce1b9/core/modules/system/system.admin.inc#L2853)

Does that help? Let us know, if you need further instructions.

**Comment by najmieh** [comment]
@indigoxela  I added a PR for the first issue mentioned above. https://github.com/backdrop/backdrop/pull/3861
Please let me know if everything is alright. 
In regard to the second issue can I get a reference to the machine_name element as well? Thank you.

**Comment by indigoxela** [comment]
@najmieh great, many thanks! One small request: can you add following text to your pull request description? (Currently there's "No description provided.".)

```
Fixes https://github.com/backdrop/backdrop-issues/issues/5365
```
That will better connect the PR with this issue, and automatically close this issue, once your PR is merged.

**Comment by najmieh** [comment]
@indigoxela initially, I didn't add a description since the second part is not completed by me. I added the explanation here. Thank you so much for the help.

**Comment by indigoxela** [comment]
> I didn't add a description since the second part is not completed by me.

This is probably something @docwilmot can help you with, as he suggests a change and decided to mark it as "good first issue" :wink:

**Comment by docwilmot** [comment]
@najmieh thanks for your work so far. I intended that both things would be done in the same PR: 
- [ ] add a default parameter to the `system_transliterate_machine_name()` function, which you have done
- [ ] the second action is to take that function `system_transliterate_machine_name()` out of the file `system.admin.inc`, and put it in `system.module`.

**Comment by najmieh** [comment]
> @najmieh thanks for your work so far. I intended that both things would be done in the same PR:
> 
> * [x]  add a default parameter to the `system_transliterate_machine_name()` function, which you have done
> * [ ]  the second action is to take that function `system_transliterate_machine_name()` out of the file `system.admin.inc`, and put it in `system.module`.

I did the required modifications for both issues, please review those. Thank you

**Comment by docwilmot** [comment]
Thank you @najmieh that seems to be passing tests as expected. Just one very minor change I would recommend. We dont have strict guidelines for the place in a file to put a function so what you have done is fine, but I find that generally the functions at the top of the file tend to be the more common `hook_*` implementations, like `hook_menu()` and `hook_permission()` and so on. A utility function like `system_transliterate_machine_name()` which is not used very often would probably be more commonly placed at the end of the file. So if you could move it to the end that I think would be better please.

**Comment by najmieh** [comment]
Ok, sure I do that.

**Comment by najmieh** [comment]
> Thank you @najmieh that seems to be passing tests as expected. Just one very minor change I would recommend. We dont have strict guidelines for the place in a file to put a function so what you have done is fine, but I find that generally the functions at the top of the file tend to be the more common `hook_*` implementations, like `hook_menu()` and `hook_permission()` and so on. A utility function like `system_transliterate_machine_name()` which is not used very often would probably be more commonly placed at the end of the file. So if you could move it to the end that I think would be better please.

@docwilmot Hi, I edited this but in a new commit. 
I wanted to edit the previous commit, hence I removed the initial clone from my desktop ( due to speed issues). Is this a reasonable PR? If not how can I make it better? considering that I tried to re-clone and commit --amend to change this PR history.

**Comment by docwilmot** [comment]
Actually this is good now. Thanks.

**Comment by docwilmot** [comment]
Tested and working.

**Comment by docwilmot** [comment]
Actually no I spoke too soon. Unfortunately, @najmieh you seem to have left the comment block for the function in `system.admin.inc`. It will need to be moved with its function.
Also, our standard practice is to name the PR with the issue number, so instead of `redefined the function`, we would call it `Issue #5365: Improve system_transliterate_machine_name`. You can just edit the PR title in GitHub UI; there's an edit button to the right of the title.

**Comment by najmieh** [comment]
> Actually no I spoke too soon. Unfortunately, @najmieh you seem to have left the comment block for the function in `system.admin.inc`. It will need to be moved with its function. Also, our standard practice is to name the PR with the issue number, so instead of `redefined the function`, we would call it `Issue #5365: Improve system_transliterate_machine_name`. You can just edit the PR title in GitHub UI; there's an edit button to the right of the title.

@docwilmot I edited those. Thank you for the feedback.

**Comment by docwilmot** [comment]
Almost there:
- the title should begin `Issue #...` not `update on Issue #...`
- the comment block wasnt deleted from the `system.admin.inc` file

**Comment by najmieh** [comment]
@docwilmot hope this works.

**Comment by docwilmot** [comment]
I think it works now.

**Comment by klonos** [comment]
Thank you @najmieh for working on this and for persisting through the various feedback/suggestions 🙏🏼 ...and thank you @docwilmot for helping @najmieh and doing the reviews/testing.

Unfortunately, the tests for this did not run:
![image](https://user-images.githubusercontent.com/2423362/147482821-b05b5100-9368-44cf-93cb-d6923012f7a6.png)

Can one of our core committers please approve this ^^ in the PR?

cc @BWPanda @laryn @quicksketch @herbdool

**Comment by quicksketch** [comment]
I have approved the workflows.

I'm sad to see that @najmieh's GitHub account has been deleted. I'll still give credit to that user name in the merge, but @najmieh: If you create a new account please post here so we can give you commit credit.

I'm not 100% sure about the move to `system.module`, but I don't feel strongly about it and trust @docwilmot's opinion on the usefulness of it.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3861 into 1.x and 1.20.x. Thanks @najmieh, @docwilmot, @indigoxela, and @klonos!
