### ISSUE TITLE
Fix errors in views_style_jump_menu.inc caused by null absolute element

### ISSUE THREAD

**Issue by philsward** [backdrop/backdrop-issues#5366]
**Description of the bug**

Views jump menus using the option "Select the current contextual filter value" produces error:

`Notice: Undefined index: fields in views_plugin_style_jump_menu->render() (line 149 of ./site/core/modules/views/plugins/views_plugin_style_jump_menu.inc).`

**Steps To Reproduce**

To reproduce the behavior:
1) Ensure all errors are enabled in Development
2) Create or edit a view. It doesn't matter what kind.
3) Change the "Format" to Jump Menu
4) In the settings of the Jump Menu, scroll to the bottom and enable the option: "Select the current contextual filter value"
5) Update the preview or visit the path of the view to witness the error

**Expected behavior**

No errors

**Additional information**

This has been addressed and fixed in the Drupal issue queue for views and consists of an eight character change: (!empty ...).

Issue: https://www.drupal.org/project/views/issues/2272387
Commit: https://git.drupalcode.org/project/views/-/commit/33c86b5
Personal PR: https://github.com/philsward/backdrop/pull/2

**Personal reference**
File: /core/modules/views/plugins/views_plugin_style_jump_menu.inc
Line: 149
Correct patch: https://www.drupal.org/files/issues/views_jump_warning-2272387-10.patch

**Comment by philsward** [comment]
@indigoxela can you personally review this? I believe your comment led to the official commit.

**Comment by indigoxela** [comment]
@philsward nice catch! Many thanks for your PR!

One request: can you add "Fixes" with the url to this issue here in the PR description - where you currently link to the Drupal issue. This makes the PR easier to discover (it shows up in this issue's header) and will close the issue when merged.

**Comment by philsward** [comment]
RE Fixes .... : Cool! I wondered how to link that. I now remember somebody mentioning that before... I'll try to remember it for next time.

**Comment by indigoxela** [comment]
Sorry, now I see it... Your PR is on the wrong repo - you made a PR to  philsward/backdrop, but the PR should point to  backdrop/backdrop 

Close the wrong one.
On your fork you should see "Contribute".

Click the 'Contribute' link and then a button will show up for it if you have extra commits. Then, you need to select the branch you want to base the PR on and the branch you want the changes to go into.

**Comment by philsward** [comment]
Ok, which branch is recommended? 1.x?

**Comment by indigoxela** [comment]
> which branch is recommended? 1.x?

Yes, 1.x, the default one, is correct :+1:

**Comment by indigoxela** [comment]
Ah, now this issue got closed unintentionally... reopening. :grinning:

**Comment by philsward** [comment]
This crap is confusing and I'm just screwing it up.

**Comment by indigoxela** [comment]
Don't panic... the first steps can be confusing. You merged it in your own fork, instead of just closing unmerged.

Maybe you want to start with a fresh fork. Nothing's lost.

**Comment by philsward** [comment]
@indigoxela should be good this time around.

**Comment by indigoxela** [comment]
> should be good this time around.

Great! Now you only need to add that magic "Fixes" again. :smirk:

**Comment by indigoxela** [comment]
I verified in the sandbox that the php notice is gone.

Based on the fact that this is a simple change, which already got merged in D7 Views module, I'm setting it RTBC.

**Comment by klonos** [comment]
If not much trouble, can we please also fix the wrapping in the inline comment right above this code? The respective code in Views 7.x-3.x is fixed. See: https://git.drupalcode.org/project/views/-/blob/7.x-3.x/plugins/views_plugin_style_jump_menu.inc#L151

I suggest that we actually also fix punctuation and grammar ("take in account" should be "taken _into_ account"):

```php
      // We need to check if the path is absolute, or else language is not taken
      // into account.
```

**Comment by philsward** [comment]
Done. PR updated

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3830 into 1.x and 1.20.x. Thanks @philsward, @indigoxela, and @klonos!
