### ISSUE TITLE
Fatal error: Argument 1 passed to file_icon_url() must be an instance of File, null given

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5370]
## Description of the bug

> Notice: Trying to get property 'fid' of non-object in file_download_uri() (line 2040 of /app/core/modules/file/file.module).
> Notice: Trying to get property 'fid' of non-object in file_get_download_token() (line 2064 of /app/core/modules/file/file.module).
> Notice: Trying to get property 'uri' of non-object in file_get_download_token() (line 2064 of /app/core/modules/file/file.module).
> Notice: Trying to get property 'uri' of non-object in theme_file_download_link() (line 403 of /app/core/modules/file/file.theme.inc).
> Notice: Trying to get property 'filemime' of non-object in theme_file_icon() (line 118 of /app/core/modules/file/file.theme.inc).
> TypeError: Argument 1 passed to file_icon_url() must be an instance of File, null given, called in /app/core/modules/file/file.theme.inc on line 119 in file_icon_url() (line 1811 of /app/core/modules/file/file.module).

## Steps To Reproduce

To reproduce the behavior:
1. Upload a test pdf.
2. In File display change to Download link (`admin/structure/file-types/manage/document/file-display`).
3. Enable Devel module and go to Execute PHP page. Run:

```
$file = file_load(1);
file_build_content($file, 'full', 'en');
render($file->content);
```

## Actual behavior

It should render the file.

## Expected behavior

No fatal error. Should display the file.

## Additional information

This was also reported here: https://github.com/backdrop/backdrop-issues/issues/3947. This issue is similar https://github.com/backdrop/backdrop-issues/issues/5227 but not exactly the same.

Where file entity is introduced: https://github.com/backdrop/backdrop-issues/issues/2632.

Note that I first discovered the fatal error when working on a contrib module. If you change the File Display from Download link to something else you don't get the fatal error. The file won't render (can't load the file formatters for some reason) but I think that's because we're trying to load it via Devel - might be a better way to recreate this bug.

**Comment by herbdool** [comment]
Made some progress already. In `file_build_content()` there's this part:

```
// Build the actual file display.
  // @todo Figure out how to clean this crap up.
  $file->content['file'] = file_view_file($file, $view_mode, $langcode);
  if (isset($file->content['file'])) {
    if (isset($file->content['file']['#theme']) && $file->content['file']['#theme'] != 'file_link') {
      unset($file->content['file']['#file']);
    }
    unset($file->content['file']['#view_mode']);
    unset($file->content['file']['#language']);
  }
  else {
    unset($file->content['file']);
  }
```

I have no idea why the if/else even exists here. The else is definitely not doing anything. If I comment it out then the fatal error goes away. Which makes sense because it can find the File object stored in `$file->content['file']['#file']`.

**Comment by herbdool** [comment]
Found it in the Drupal version: https://git.drupalcode.org/project/file_entity/-/blob/7.x-2.x/file_entity.file_api.inc#L182

Is it wrong to just delete this if/else? Or if we don't want to do that we could add an exception for `$file->content['file']['#theme'] != 'file_download_link'`.

**Comment by indigoxela** [comment]
> Is it wrong to just delete this if/else?

Not if that doesn't cause a regression. :grin: 

Hm, odd code, for sure. Seems like it should prevent a php notice: https://git.drupalcode.org/project/file_entity/-/commit/c1ab850702c82d403540134dc6414d8fbe5230af

**Comment by herbdool** [comment]
Let's find out!

**Comment by herbdool** [comment]
All the tests pass so that's good.

**Comment by indigoxela** [comment]
Tests seem to be passing, but no Tugboat sandbox has been created. Any idea, why?

**Comment by indigoxela** [comment]
I can't reproduce the Notices from the issue description without the Devel module approach.

But I get other notices, whenever I set the "Display type" to either url, table or generic file. Verified with document and image:

- Notice: Undefined index: file_field_file_url_plain in file_view_file()
- Notice: Undefined index: file_field_file_table in file_view_file()
- Notice: Undefined index: file_field_file_default in file_view_file()

But I get those Notices with or without patch applied, whenever I visit a File path (/file/X) so this might be a different issue. @herbdool what do you think? Related or unrelated?

**Comment by indigoxela** [comment]
I can not reproduce the problem described in the [D issue](https://www.drupal.org/project/file_entity/issues/1270036), which was the initial reason for this if/else code.

Icon displays, link works, after applying the patch which removes that section in function file_build_content().

My conclusion so far: the patch doesn't cause any regression. But there's still other stuff with file display going on.

**Comment by indigoxela** [comment]
The fix for the notices (from my previous comment) would be a one-liner.

We should check if the formatter in use does have settings, before trying to access the array key. Not all formatters do, which results in the undefined index notices in file_view_file().

**Comment by herbdool** [comment]
Ah yes, I'm seeing those undefined index too. I didn't follow it too deeply. Looks like we should create another issue for that (if it doesn't exist already).

**Comment by herbdool** [comment]
@indigoxela I created a follow-up since I agree the undefined index is unrelated. Are you comfortable updating labels on this issue to be RTBC?

**Comment by indigoxela** [comment]
> Are you comfortable updating labels on this issue to be RTBC?

I'm absolutely fine with "works for me", but I'm not 100% sure yet about RTBC. My testing happened in a rush and I might have missed something.

**Comment by herbdool** [comment]
@indigoxela I made the PR smaller which might make you more comfortable in marking it RTBC.

It will just exclude `file_download_link` in addition to what's there. But it also removes the `else {}` since it's not doing anything anyway (why try to unset something that's not set?).

**Comment by indigoxela** [comment]
Hm... now the "Notice: Undefined index" is back, when setting the file display to URL to file or Table of files...

@herbdool sorry for not coming back sooner for review. I wasn't objecting to the previous approach, just didn't find the "quiet hour" yet it needs to do a proper review.

I assume the previous approach - ripping that whole "crap" (comment in code ;-) ) out - was correct.

**Comment by herbdool** [comment]
@indigoxela that happens. The undefined index was solved in the other issue I think. Just need to update this PR.

**Comment by herbdool** [comment]
@indigoxela the undefined index is gone after merging from upstream. The other PR fixed that.

**Comment by indigoxela** [comment]
Ah, got it. Many thanks for rebasing. Yes, now it works properly.

**Comment by indigoxela** [comment]
That this "else" (unsetting something that's not set) is silly, is absolutely clear to me, but I wouldn't want to RTBC a code change, which is based on a problem only reproducible in Devel.

So I tried to dig a bit deeper. I wanted a way to reproduce independently from the Devel module, so I put your example code in a theme's template.php.
The error is reproducible - only with the "Download link" display setting. So why this weird unsetting, anyway, which breaks the render?

`$file->content['file']` is always set, in all 4 available (by core) file display types. And it does no harm at all. Unsetting things does harm, because the object to get rendered by the theme, is missing then.

My conclusion: your first approach - removing that whole code block - was correct. As I already mentioned in an earlier comment: I wasn't able to reproduce the problem in Backdrop people tried to fix in Drupal with that code.

@herbdool do you feel more comfortable with your second ("less dramatic") change, or do you still feel OK with the initial one (ripping the whole crap out)?

**Comment by herbdool** [comment]
@indigoxela thanks for checking a bit more. I'm okay with ripping it out. :)

**Comment by herbdool** [comment]
@indigoxela I've updated the PR.

**Comment by herbdool** [comment]
All tests passing.

**Comment by indigoxela** [comment]
This looks good, RTBC. :+1:

**Comment by jenlampton** [comment]
I'm experiencing the `Notice: Undefined index: file_field_file_default in file_view_file() (line 3441 of /code/core/modules/file/file.module).` error on a 1.20.2 site.

**Comment by herbdool** [comment]
@jenlampton the undefined index was addressed in https://github.com/backdrop/backdrop-issues/issues/5371

**Comment by jenlampton** [comment]
Ah, thanks!  I'll stop testing this PR then, and update to 1.20.3 :D

**Comment by BWPanda** [comment]
@herbdool I was about to merge your PR, but your other [recent commit](https://github.com/backdrop/backdrop/commit/53a9d5e515a611012985fdfee3540c798caf9c29) has caused a conflict. Can you please fix that?

**Comment by quicksketch** [comment]
Yeah kind of a big merge conflict here after introducing #1739. I would normally fix small conflicts in the GitHub UI but this is too much to do inline.

**Comment by herbdool** [comment]
Fixed. Since this was the same set of lines removed, but in a different file, I'm going to go out on a limb and say it's back to its previous rtbc status.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3834 into 1.x only since the changes are different in the 1.20.x branch. Thanks @herbdool and @indigoxela!
