### ISSUE TITLE
Spelling error on context table in Layout edit page

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#538]
![capture](https://cloud.githubusercontent.com/assets/1042283/5600479/99d01960-92a8-11e4-9937-94a092d59bd5.PNG)

Should be CONTEXT not CONEXT of course.

**Comment by BWPanda** [comment]
Thanks @docwilmot! For reference, this appears on the `/admin/structure/layouts/manage/[LAYOUT NAME]/settings` page.

**Comment by quicksketch** [comment]
Thanks again @BWPanda!
