### ISSUE TITLE
[DX][D8] Add 'empty' option to theme_item_list()

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5380]
This is the same as https://www.drupal.org/project/drupal/issues/2120807, and it is going to be an API addition for Backdrop.

Change record: https://www.drupal.org/node/2124021

> `theme('item_list')` (or the `theme_item_list()` function, as it is currently implemented) has a new feature: You can pass in variable `'empty'` with a string or render array value, and if there are no list items, this value will be output. This is similar to the `'empty'` variable in `theme('table')`.
> 
> Example of using this from a render array:
> 
> ```php
> $build['foo'] = array(
>   '#theme' => 'item_list',
>   // This is the list of items to output.
>   '#items' => $results,
>   // This can be a string or a render array.
>   '#empty' => array(
>       '#markup' => t('There were no results. Try a less restrictive filter.'),
>   ),
>   '#title' => t('Search Results'),
>   '#list_type' => 'ol',
> );
> ```

**Comment by klonos** [comment]
The current PR is a direct backport from D8, but I'll see if there's ways that we can take advantage of this in the output of views-generated lists.

**Comment by klonos** [comment]
> ...I'll see if there's ways that we can take advantage of this in the output of views-generated lists.

We could add something specific to the settings dialog of the "Unformatted list" output format, but views already has the in-built "NO RESULTS BEHAVIOR" settings, where people can add a global text area. So non need to really.

**Comment by klonos** [comment]
Draft change record: https://docs.backdropcms.org/change-records/theme-item_list-has-a-new-empty-variable

**Comment by bugfolder** [comment]
Tested with this form element:

```
  $results = array('foo', 'bar');
  $empty = array('#markup' => t('The array was empty.'));
  $form['foo'] = array(
    '#title' => t('Search Results'),
    '#theme' => 'item_list',
    '#list_type' => 'ol',
    // This is the list of items to output.
    '#items' => $results,
    // This can be a string or a render array.
    '#empty' => $empty,
  );
```

Prior to this change, there's this behavior:

* If `$results = array('foo', 'bar')`, the element displays as usual.
* If `$results = array()`, the element doesn't display at all (no title).

I apply this change, here's the behavior:

* If `$results = array('foo', 'bar')`, the element displays as usual.
* If `$results = array()`, I get the title and text "The array was empty."
* If `$results = array()` and no `#empty` property, the element doesn't display at all (no title).
* If `$results = array()` and `$empty` is a plain string, the string displays.

So, Works for Me. I've also reviewed the code and see nothing amiss.

**Comment by quicksketch** [comment]
I wasn't super-comfortable with this PR because I didn't like the idea of a renderable being inside of the `#empty` value (like the example in the summary):

```
$build['foo'] = array(
  '#theme' => 'item_list',
  // This is the list of items to output.
  '#items' => $results,
  // This can be a string or a render array.
  '#empty' => array(
      '#markup' => t('There were no results. Try a less restrictive filter.'),
  ),
  '#title' => t('Search Results'),
  '#list_type' => 'ol',
);
```

However, just because you _can_ doesn't mean developers necessarily will. A good similar example is the `#empty` property used on Tables. And although it is not documented that you can use a renderable there, it indeed works.

For example, this is the most common setup:
```
  return array(
    '#theme' => 'table',
    '#rows' => $rows,
    '#header' => $header,
    '#empty' => t('No custom blocks have been created yet.'),
  );
```

But this would also work:
```
  return array(
    '#theme' => 'table',
    '#rows' => $rows,
    '#header' => $header,
    '#empty' => array('
      '#markup' => t('No custom blocks have been created yet.'),
    ),
  );
```

It comes down to this bit of code in `_theme_table_cell()`:

```
    // Cell's data property can be a string or a renderable array.
    if (is_array($data)) {
      $data = backdrop_render($data);
    }
```

So although I don't really like an entire renderable being available as a FormAPI property, it's consistent with our other existing `#empty` property that is commonly used on tables.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3842 into 1.x for 1.21.0. Thanks @klonos and @herbdool!

I also went ahead and published the change record, with a little rewording: https://docs.backdropcms.org/change-records/theme-item-list-empty-variable
