### ISSUE TITLE
Get rid of the distracting autofocus on node form titles

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5386]
## Description of the bug

In Issue #2625 the autofocus on the node title field was introduced in node forms.
This led to a UX regression. Now every time someone opens a node form, the focus jumps to the title field.

That's (sort of) OK with new nodes, but when editing existing nodes, the title is one of the least likely candidate for changes - usually something in one of the other fields has to get updated (body or paragraphs...).

Additionally, the autofocus happens on the title field, regardless of its weight, which can cause irritating jumps, when the title field is further down the form.

There's already an issue for the weight (#3583), but I'd like to start a discussion on completely reverting this UX regression (IMO the autofocus on node titles is a regression).

Note that getting rid of it is only a matter of hook_form_alter() - which I use currently. But I'm pretty sure, I'm not the only one who thinks this autofocus is bad UX. So I start this as a question here.

**Comment by indigoxela** [comment]
I'm not sure about the A11Y aspects of the autofocus, but IMO in some cases it _can_ introduce bad accessibility. For example, if the node title isn't the first item on the form, which throws screen reader users somewhere to the middle of the form, without proper context.

Another problem might be that a useful help text is prepended to the form, but as the autofocus strikes, that text isn't available for screen readers.

**Comment by olafgrabienski** [comment]
I agree, the title autofocus can lead to UX regressions, without being helpful most of the times. The only use-case where it really helps is the addition of multiple taxonomy terms. The latter was the main reason to introduce the feature btw:

> I had to input 10-20 terms in a vocabulary and had to click into title each time before I could type the term. If focus happened automatically it would be simple to type, press enter, pause and then repeat without having to take my hands off the keyboard.
> – From issue description https://github.com/backdrop/backdrop-issues/issues/2625

So, I'd suggest to limit the autofocus to the creation of taxonomy terms, or at least to *creating content* (in contrast to *editing*).

Speaking of editing content and regressions, a small example: I often open node forms just to check something, without the intention to change the form, and I'm used to jump back in such situations by pressing `Cmd` + `<-` on my Mac keyboard. This used to work in Backdrop, but stopped working with the autofocus introduction.

**Comment by klonos** [comment]
> The only use-case where it really helps is the addition of multiple taxonomy terms.

That's useful for user creation too. Right?

> ...or at least to creating content (in contrast to editing).

I'd be supportive of that too ^^ 👍🏼  (but also prefer fixing #3583)

**Comment by indigoxela** [comment]
> That's useful for user creation too. Right?

Sure, neither taxonomy term forms nor user forms are a problem, they don't get addressed here. But node forms are.

> I'd be supportive of that too ^^ 👍🏼 (but also prefer fixing #3583)

These two issues are contradictory. If the other one gets "fixed", this one here will be rejected. If we find consensus on this one, the other issue gets obsolete for nodes.

**Comment by olafgrabienski** [comment]
> Short form: I support removing autofocus on nodes.

We've got some feedback regarding the removal of autofocus on node form titles, not very much but mainly supportive. Is someone up to file a pull request? Or do we want to discuss first this approach here in comparison to #3583?

**Comment by indigoxela** [comment]
Personally, I'm in favor of moving on here (remove the autofocus). More discussion? Sure, why not... but I wouldn't expect much progress.

If it's about a PR - and who provides it ... how about you, @olafgrabienski? Search for "autofocus" in core/modules/node/node.module and remove it. :wink:

**Comment by indigoxela** [comment]
Switching issue label to "task" - based on the feedback we got.

**Comment by olafgrabienski** [comment]
> Search for "autofocus" in core/modules/node/node.module and remove it.

Done! I hope in the right way. A PR is available at https://github.com/backdrop/backdrop/pull/4094.

The PR removes the autofocus from the node form title. It does *not* remove autofocus from the Username field at the User account creation form nor from the Name field of the Taxonomy term add / edit page.

**Comment by indigoxela** [comment]
Great! Many thanks for your PR. Works like a charm. :+1:

**Comment by indigoxela** [comment]
Revisiting this issue after a little pause - I think, it's ready to get merged. There doesn't seem to be any opposition, too. RTBC :+1:

As I set the milestone label, someone else should set the actual milestone.

**Comment by olafgrabienski** [comment]
> As I set the milestone label, someone else should set the actual milestone.

Can do, if I'm supposed to do so. Which milestone btw? I guess, as `task` it can go in the next bugfix release, right?

**Comment by indigoxela** [comment]
tasks can go to bugfix releases, right.

**Comment by quicksketch** [comment]
I thought we had some JavaScript solution for this, not just using the "autofocus" HTML attribute. I agree that leaving the behavior to the browser, which can act unpredictably and inconsistently in situations as complex as the node form, is bound to lead to problems. https://github.com/backdrop/backdrop/pull/4094 looks good to me too.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4094 into 1.x and 1.22.x. Thanks @olafgrabienski, @indigoxela, @klonos, and @laryn!
