### ISSUE TITLE
Search form: style the "Search" and "Advanced search" buttons as proper actions buttons.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5387]
## Steps To Reproduce

To reproduce the behavior:
1. Add a search block in the default layout (preferably the sidebar region, but don't really matter)
2. Navigate to `/search`
3. Expand the "Advanced search" fieldset...

## Actual behavior

Only the submit button in the block is properly styled as a primary button:
<img width=75% src="https://user-images.githubusercontent.com/2423362/145157473-f2898c28-1551-4da7-8101-ae47ac3af8e5.png">

## Expected behavior

All submit buttons should be properly styled as primary submit buttons (each one for its respective form):
<img width=75% src="https://user-images.githubusercontent.com/2423362/145159084-3b78a652-cff5-4aa8-9083-43896cc62d30.png">

**Comment by bugfolder** [comment]
Tested: added search block to sidebar. Search button is properly styled.

Code reviewed. Looks good.

Works for me.

**Comment by quicksketch** [comment]
Looks great! Merged https://github.com/backdrop/backdrop/pull/3854 into 1.x and 1.20.x. Thanks @klonos and @bugfolder!

**Comment by jenlampton** [comment]
I expect this will break existing sites that have styled the search block.
