### ISSUE TITLE
Views Admin rendering a different result than rendered page when using contrib modules

### ISSUE THREAD

**Issue by pnmgman2** [backdrop/backdrop-issues#5388]
## Description of the bug

Conditional Fields are not respecting Views order of operations configuration, and therefore are evaluated first before Views Fields used as Replacement Variables in the Conditional Fields helper module.

In this test, we are going to use Views Conditional, Views Flipped Table, Views Field View modules as well as Views Math Expression to demonstrate a difference in how the rendered page in BackdropCMS displays conditional field results from the Views UI admin preview. 

See forum discussion: https://forum.backdropcms.org/comment/3447#comment-3447

## Description of the bug

Conditional Fields are not respecting Views order of operations configuration, and therefore are evaluated first before Views Fields used as Replacement Variables in the Conditional Fields helper module.

In this test, we are going to use Views Conditional, Views Flipped Table, Views Field View modules as well as Views Math Expression to demonstrate a difference in how the rendered page in BackdropCMS displays conditional field results from the Views UI admin preview. 

## Steps To Reproduce
In the test, we are going to use **Views Conditional, Views Flipped Table, Views Field** View modules as well as **Views Math Expression** to demonstrate a difference in how the rendered page in BackdropCMS displays conditional field results from the Views UI admin preview. The result is correct in Views Admin, but are not correct in the rendered page.

I apologize in advance for the length of this, but we use BackdropCMS in very esoteric use cases to support business critical applications.

To reproduce the behavior:
STEP 1: Add yes/no questions to user accounts profile and create a view that sums the values of each question answered as YES
CREATE QUESTIONS TO ANSWER ON USER ACCOUNTS
•	Create a few User Account fields as Bool and format as Single on/off checkboxes
•	Add a question as the label and save – do this for each of the fields you created
CREATE A REFERENCE VIEW ADDING BOOLEAN FIELDS TO THE TEST VIEW
•	Create a VIEW showing user accounts with a Display of Page
•	Name the view TEST District
•	Use the ‘Flipped Table’ of fields
•	Select 1 for Items to display and uncheck ‘use a pager’
•	Select Continue and Configure
•	Change access to ROLE->Authenticated
•	Click on ADD FIELDS
•	Select User Account and search for the questions you added to the user account and select them
•	Click Add and Configure Fields
•	For each field, change the formatter to “KEY”, check Exclude from Display and click Apply and Continue
•	Click update preview and you should see a table listing the value of the Bool down the right side and user account as a clickable link in the header of the right column – click the user account name and select Edit Profile tab
•	Answer one or more of the test questions so that some of the values are 1 and save
•	Return to the View and click update preview, you should see the values you selected YES are now represented by 1 in the right column
•	Add a Global Math Expression to Fields and sum the values of the referenced fields for each question
•	Uncheck create a label from the Math Expression field 
•	Update preview again and you should see a total equaling the number of questions answered yes.
•	Hide the username field 
•	Update preview again and you should see only the total
•	Save this display and View
STEP 2: Add a display to the View that will display a summary of questions and the score using the reference display for the sum value
•	From the TEST display, click Add a Page
•	Set menu path to TEST
•	Name the display something like Summary
•	In the Fields area, remove each of the fields copied over – be sure to select This Page (override) before removing the first field. Leave only the username field
•	Change the format to an unformatted list again be sure to select This Page (override) first before saving
•	Add a Global VIEW field – select Add and Configure
•	In VIEW area, select the current view TEST
•	Then select the PAGE display
•	In the contextual filter area, enter !1 replacement pattern
•	Uncheck “create a label”, then click Apply this display
•	In the preview area, click update preview
•	Scroll to the bottom and you should see the View referenced field with the value showing
•	Navigate to the page path for the summary display and you should see the same value rendered
STEP 3: Add Statements
•	Go to the summary display and add a Global Custom Text Field
•	In the Text area add “The value evaluated [view] is greater than the referenced field [view]” and click Apply this display
•	Add another Global Custom Text Field
•	In the Text area add “The value evaluated [view] is equal to or less than the referenced field [view]” and click Apply this display
STEP 4: Add a conditional field to determine a statement to display based on the referenced View field value.
•	Go to the summary display and add a Views conditional field
•	In the If this field . . . dropdown select the VIEW field [view] === Global: View
•	In the Is . . . dropdown select Greater Than
•	In This values textbox select a number equal to the value displayed in the earlier steps (for instance, if the value displayed earlier is 5, then enter 5)
•	In the Then output this . . . 
•	Enter the Replacement Variable [nothing]
•	And in Otherwise, output this… Enter the Replacement Variable [nothing_1]
•	Click on Apply this Display
•	Exclude from Display the Global View field and both Custom Text fields

## Actual behavior

•	Update Views Preview and you should see _5 is equal to or less than the referenced field 5_ (which is correct)
•	Save the Display and return to the path link created earlier /test
•	Refresh the page
•	You should see _The value evaluated 5 is greater than the reference field 5_ (which is incorrect)

## Expected behavior

•	Update Views Preview and you should see _5 is equal to or less than the referenced field 5_ (which is correct)
•	Save the Display and return to the path link created earlier /test
•	Refresh the page
•	You should see _5 is equal to or less than the referenced field 5_ (which is correct)

## Additional information

Info | Backdrop CMS | 1.20.3
Info | MySQL Database | MySQL, MariaDB, or equivalent version 5.7.33-0ubuntu0.16.04.1
Info | PHP | Version: 7.0.33-0ubuntu0.16.04.16 (PHP information)
Info | Web server | Apache/2.4.18 (Ubuntu)

Running Windows 10 Professional and Edge (Chromium-based) browsers.

## Steps To Reproduce
In the test, we are going to use **Views Conditional, Views Flipped Table, Views Field** View modules as well as **Views Math Expression** to demonstrate a difference in how the rendered page in BackdropCMS displays conditional field results from the Views UI admin preview. The result is correct in Views Admin, but are not correct in the rendered page.

I apologize in advance for the length of this, but we use BackdropCMS in very esoteric use cases to support business critical applications.

To reproduce the behavior:
STEP 1: Add yes/no questions to user accounts profile and create a view that sums the values of each question answered as YES
CREATE QUESTIONS TO ANSWER ON USER ACCOUNTS
•	Create a few User Account fields as Bool and format as Single on/off checkboxes
•	Add a question as the label and save – do this for each of the fields you created
CREATE A REFERENCE VIEW ADDING BOOLEAN FIELDS TO THE TEST VIEW
•	Create a VIEW showing user accounts with a Display of Page
•	Name the view TEST District
•	Use the ‘Flipped Table’ of fields
•	Select 1 for Items to display and uncheck ‘use a pager’
•	Select Continue and Configure
•	Change access to ROLE->Authenticated
•	Click on ADD FIELDS
•	Select User Account and search for the questions you added to the user account and select them
•	Click Add and Configure Fields
•	For each field, change the formatter to “KEY”, check Exclude from Display and click Apply and Continue
•	Click update preview and you should see a table listing the value of the Bool down the right side and user account as a clickable link in the header of the right column – click the user account name and select Edit Profile tab
•	Answer one or more of the test questions so that some of the values are 1 and save
•	Return to the View and click update preview, you should see the values you selected YES are now represented by 1 in the right column
•	Add a Global Math Expression to Fields and sum the values of the referenced fields for each question
•	Uncheck create a label from the Math Expression field 
•	Update preview again and you should see a total equaling the number of questions answered yes.
•	Hide the username field 
•	Update preview again and you should see only the total
•	Save this display and View
STEP 2: Add a display to the View that will display a summary of questions and the score using the reference display for the sum value
•	From the TEST display, click Add a Page
•	Set menu path to TEST
•	Name the display something like Summary
•	In the Fields area, remove each of the fields copied over – be sure to select This Page (override) before removing the first field. Leave only the username field
•	Change the format to an unformatted list again be sure to select This Page (override) first before saving
•	Add a Global VIEW field – select Add and Configure
•	In VIEW area, select the current view TEST
•	Then select the PAGE display
•	In the contextual filter area, enter !1 replacement pattern
•	Uncheck “create a label”, then click Apply this display
•	In the preview area, click update preview
•	Scroll to the bottom and you should see the View referenced field with the value showing
•	Navigate to the page path for the summary display and you should see the same value rendered
STEP 3: Add Statements
•	Go to the summary display and add a Global Custom Text Field
•	In the Text area add “The value evaluated [view] is greater than the referenced field [view]” and click Apply this display
•	Add another Global Custom Text Field
•	In the Text area add “The value evaluated [view] is equal to or less than the referenced field [view]” and click Apply this display
STEP 4: Add a conditional field to determine a statement to display based on the referenced View field value.
•	Go to the summary display and add a Views conditional field
•	In the If this field . . . dropdown select the VIEW field [view] === Global: View
•	In the Is . . . dropdown select Greater Than
•	In This values textbox select a number equal to the value displayed in the earlier steps (for instance, if the value displayed earlier is 5, then enter 5)
•	In the Then output this . . . 
•	Enter the Replacement Variable [nothing]
•	And in Otherwise, output this… Enter the Replacement Variable [nothing_1]
•	Click on Apply this Display
•	Exclude from Display the Global View field and both Custom Text fields

## Actual behavior

•	Update Views Preview and you should see _5 is equal to or less than the referenced field 5_ (which is correct)
•	Save the Display and return to the path link created earlier /test
•	Refresh the page
•	You should see _The value evaluated 5 is greater than the reference field 5_ (which is incorrect)

## Expected behavior

•	Update Views Preview and you should see _5 is equal to or less than the referenced field 5_ (which is correct)
•	Save the Display and return to the path link created earlier /test
•	Refresh the page
•	You should see _5 is equal to or less than the referenced field 5_ (which is correct)

## Additional information

Info | Backdrop CMS | 1.20.3
Info | MySQL Database | MySQL, MariaDB, or equivalent version 5.7.33-0ubuntu0.16.04.1
Info | PHP | Version: 7.0.33-0ubuntu0.16.04.16 (PHP information)
Info | Web server | Apache/2.4.18 (Ubuntu)

Running Windows 10 Professional and Edge (Chromium-based) browsers.

**Comment by argiepiano** [comment]
Hi @pnmgman2 . I'm trying to follow your steps, but am unable to get the result you mention in step 4. I'm attaching the image of the preview of step 1 - notice that it shows the two questions I created and math expression - did you intend for it to show only the math expression (which means hiding the questions)?

<img width="1155" alt="Screen Shot 2021-12-09 at 7 21 19 PM" src="https://user-images.githubusercontent.com/9938978/145507316-84857fdd-b892-472e-84e8-f849660188f3.png">


Anyway, I have a couple of observations/questions:
1. Why do you use !1 in the contextual filter of the Views field? Notice that the view display it's referring to actually doesn't have a contextual filter, so that !1 will do nothing. 
2. And more importantly, an observation: you are using a Views Field View field to refer to the _same_ view where it's located. Views Field View typically will execute and render the view, and use that as an output. Using this in circular fashion can definitely lead to unexpected issues. I would suggest that you try to **split** your Views in your example by creating two: one that holds the math expression, and another that holds the views field.

Try that and see if that solves your issue

**Comment by argiepiano** [comment]
One more thought that additionally suggests why the live preview output is different from the normal rendering. Among other things the live_preview disables an output cache. While I'm not certain about details, I believe this doesn't happen when you render the view normally.

I still have a hunch that your issue is due to the fact that you have a Views Field View field in the same view it is referencing, and that this is not a bug. Try what I suggested above. 

In any case, I believe using a whole view display to produce a sum of values is like using a sledge hammer to fix a Swiss watch. I would suggest creating a custom views field handler that provides those values and save yourself some headaches.

**Comment by pnmgman2** [comment]
Hi again @argiepiano,

To answer the first question, yes only the sum of values should be displayed wihtout labels, so that the result of referencing the view would be simply the resultant number.

Also, after working through this late yesterday, I am convinced the problem is actually the module Conditional Fields - I'll explain that later, but in the interim, I have simplified the test right down to the issue I'm experiencing and I can prove that the Display of circular Views does work - just don't exclude it from the display on the page and you will see that it does indeed bring the number over just fine - this is a technique we have used extensively for years in Drupal.

Anyway, here are the simplified steps to recreate the problem:

STEP 1: Add a value to a Global custom text field in a Views display
•	Create a VIEW showing user accounts with a Display of Page
•	Name the view TEST District
•	Use the unformatted list format
•	Select 1 for Items to display and uncheck ‘use a pager’
•	Select Continue and Configure
•	Change access to ROLE->Authenticated
•	Click on ADD FIELDS
•	Add one global text field, uncheck Create a Label and enter 5 in the text area
•	Uncheck create a label from the user account username field and Exclude it from display
•	Update preview without a contextual filter and you should see a total of 5
•	Save this display and View

STEP 2: Add a display that will show the result from the page display as a global view field and add a conditional field to determine a statement to show based on the referenced View field value.
•	From the TEST display, click Add a Page
•	Set menu path to TEST
•	Name the display something like Summary
•	In the Fields area, remove each of the fields copied over – be sure to select This Page (override) before removing the first field. Leave only the username field
•	Make sure the format is as an unformatted list be sure to select This Page (override) first before saving
•	Add a Global VIEW field – select Add and Configure
•	In VIEW area, select the View TEST District
•	Then select display and select the “Page” display
•	Leave contextual filter blank
•	Uncheck “create a label”, and check Exclude from display, then click Apply this display
•	Add a Views conditional field
•	In the If this field . . . dropdown select the VIEW field [view] === Global: View
•	In the Is . . . dropdown select Greater Than
•	In This value textbox enter the number 5
•	In the Then output this . . . text area enter TRUE [view] is greater than [view]
•	And in Otherwise, output this… text area enter FALSE [view] is not greater than [view]
•	Click on Apply this Display
•	Update Preview and you should see FALSE 5 is not greater than 5 
•	Save the Display then in another tab navigate to the summary display path link: /test
•	You should see True 5 is greater than 5

Conclusion, because we are exposing the value of the [view] within the conditionals dispaly area, so we can see that the value of the view field is coming over from the other display both in Views Admin and in the rendered page; however in the rendered page, Views Conditional Field does not evaluate the [view] first, and therfore comes to a FALSE condition - this makes me think that the evlauation of the the views field by Conditional Field is not respecting the configuration of Views.

To your point: "Among other things the live_preview disables an output cache.", this sounds like another good place explore and I will look into that as well.

As you have already seen from the export view code - we use Views in exotic ways; that reduces custom coding assets. We are a very small staff and coding new solutions is a last resort if we can't do it Core, or do it with Contrib Modules, or by adding PHP snippets to Contrib Modules - coding our own is always a last resort.

**Comment by pnmgman2** [comment]
I'm about to take off for the weekend so I thought I'd post an update on my issue:
After exhausting all suggestions and options, and as I have begun to suspect that Views Conditional Fields module was the culprit, I moved all conditional fields to the displays where the sums are totaled and then I bring those results into the other view, as there are no other conditional checks thereafter where things can go wrong.

Long story short, that worked! 

After further testing with Views Conditional Fields with other field types like Math Exprerssion, View Conditional Fields fails to evaluate those fields each time and so, the result is always wrong. Views Conditional fields will ONLY WORK with static set values like global text and only within the same display, not referenced values from another display or another view using Replacement Variables.

**So I have a workaround - perform Views Conditionals within the same display where the fields you want to evaluate are located - do not reference via the Views Replacement Variable - this will not work. I will post an update over at Views Conditional Fields as well.**

**Comment by pnmgman2** [comment]
I am also going to close this issue here because I do not believe it is a BD/Views issue.
