### ISSUE TITLE
Style the warning about $settings['update_free_access'] as a proper message in update.php

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5391]
Before:
![image](https://user-images.githubusercontent.com/2423362/145712497-14d19ec8-a911-499e-abae-5c61cc121dc6.png)

After: 
![image](https://user-images.githubusercontent.com/2423362/145712408-ce57a964-da2c-4986-abe9-e148ee1d5832.png)

**Comment by indigoxela** [comment]
@klonos you're getting old? :smile: See also https://github.com/backdrop/backdrop-issues/issues/4804

**Comment by klonos** [comment]
Dang it 😞  ...I am getting old. Sorry.
