### ISSUE TITLE
Added: "Show as Expanded" help text needs revising.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5397]
## Description of the bug

The problem is that either this checkbox is not working, or the help text does a very poor job of explaining the purpose of this checkbox.

## Steps To Reproduce

1) Spin up a fresh site.
2) Create a test page with a menu link that is a child of "About"
3) Edit the menu link for "About" to "show as expanded" (see screenshot)

## Actual behavior

The About menu seems to act exactly the same whether or not this checkbox is checked. 

## Expected behavior

I could be wrong, but I expected that the child menu would be visible all the time - even without hovering. The help text says "If selected and this menu link has children, the menu will always appear expanded."

While this menu has a child, but it does not always appear expanded. In fact, it is only expanded when I hover over the link - as it was before I checked this box. 

I am open to the idea that I am completely misunderstanding what this checkbox should do, in which case I think we need to revise the help text, because I've spent 20 minutes trying to figure out what this checkbox does, to no avail.

## Additional information

![image](https://user-images.githubusercontent.com/3144571/146086233-a5f18433-11f4-49bf-8332-e7cab22654da.png)

**Comment by olafgrabienski** [comment]
Looks like the setting isn't working in drop-down menus:

> the "Expanded" option does not affect drop-downs. It only affects when the menu is displayed as a Hierarchical Tree

See https://github.com/backdrop/backdrop-issues/issues/2782#issuecomment-920457117 and below.

**Comment by stpaultim** [comment]
@olafgrabienski - Thanks. Which leads me back to the fact that maybe we need better help text. I'll try to submit suggestions as soon as I figure out what it is supposed to do. To be honest, I don't know what this means " the "Expanded" option does not affect drop-downs. It only affects when the menu is displayed as a Hierarchical Tree".

**Comment by BWPanda** [comment]
I did some testing of the various options. Hopefully this helps people understand things better (so we can improve the documentation as needed).

Firstly, this is the menu structure I worked with (Admin link as child of About):
![image](https://user-images.githubusercontent.com/2385329/146359702-40b62756-68a0-48e9-b1bf-0671d3ab82ef.png)

With About *not* set to expanded (i.e. the default behaviour), here's what happens in the different scenarios:

 **Menu Style**   | **Links Visible On HomePage**       | **Links Visible On About Page**      
------------------|---------------------------------|---------------------------------
 Top level only   | Home, About                     | Home, About                     
 Dropdown menu    | Home, About (Admin in dropdown) | Home, About (Admin in dropdown) 
 Hierarchial tree | Home, About                     | Home, About, Admin              

With About *set to expanded*, here's what happens in the different scenarios:

 **Menu Style**   | **Links Visible On Home Page**  | **Links Visible On About Page** 
------------------|---------------------------------|---------------------------------
 Top level only   | Home, About                     | Home, About                     
 Dropdown menu    | Home, About (Admin in dropdown) | Home, About (Admin in dropdown) 
 Hierarchial tree | Home, About, Admin              | Home, About, Admin              

So, it seems that the 'expanded' option for menu links only affects the Hierarchial Tree menu style. When parent links are not expanded, child links are only shown when the parent is the active link. When parents are expanded, child links are always shown.

Also, if you tick the "Show all menu links" box in the Hierarchial Tree settings, this overrides the 'expanded' behaviour and shows all children regardless.

**Comment by BWPanda** [comment]
The current help text for the "Show as expanded" option is this:

> If selected and this menu link has children, the menu will always appear expanded.

I'm thinking something along these lines might be more accurate and less confusing...

> When displayed in a 'hierarchial tree' menu style, children of expanded menu links will always be visible.

**Comment by AnjaliJha1221** [comment]
Hello, I'm participating in OpenForce. I would like to work on this issue, please guide me further on how to get started, as I am a total beginner.

**Comment by stpaultim** [comment]
@AnjaliJha1221 - If you are able, here is a chance to get some help.
https://events.backdropcms.org/sessions/writing-your-first-pr-for-backdrop-cms

**Comment by AnjaliJha1221** [comment]
Sure, thanks

**Comment by stpaultim** [comment]
@AnjaliJha1221 - Any questions?
We have office hours this week, if you need help: [backdropcms.org/news/events/office-hours-2](https://backdropcms.org/news/events/office-hours-2)

**Comment by stpaultim** [comment]
@AnjaliJha1221 - Are you still interested in working on this one. It could be quite easy and something you can do without even installing Backdrop CMS. 

1) See this article: https://backdropcms.org/news/creating-pull-requests-against-core-the-easy-noob-way|
2) Create a fork of Backdrop CMS and create a branch for this issue. 
3) Edit this file: core/modules/menu/menu.admin.inc (I did a string search of the entire code base)
4) Edit this string:

WAS:
`If selected and this menu link has children, the menu will always appear expanded.`

REPLACE WITH:
`When displayed in a 'hierarchial tree' menu style, children of expanded menu links will always be visible.`

5) Create a Pull Request in the Github user interface.

**Comment by AnjaliJha1221** [comment]
Yes, I'm interested, had exams that's why I wasn't active. 
Thanks for the briefing I'll start working

**Comment by stpaultim** [comment]
@AnjaliJha1221 - I look a look at your Pull Request and there are two issues. 

1) You need to fix the nested "single quotes" which are causing a problem. 
2) Tests did not run on your PR. Try closing your PR and then reopening it again (wait 10 seconds). In theory, reopening your PR will trigger the automated tests.

**Comment by stpaultim** [comment]
@AnjaliJha1221 - It has now been suggested to me on the Pull Request that the tests may not have run because of the error, so before trying to restart the tests, be sure to fix the error. @BWPanda has provided the fix, you just need to accept it.

**Comment by stpaultim** [comment]
@AnjaliJha1221 - This looks good. RTBC (Ready to be committed)

**Comment by BWPanda** [comment]
@stpaultim I'm happy to merge the PR if you want to first add the bug fix milestone...

**Comment by stpaultim** [comment]
Done. Although the discussion in Dev meeting today has me a bit confused about whether or not this is necessary.

**Comment by BWPanda** [comment]
@stpaultim Yes, still necessary to have different people add the label and the milestone:

> 2. It must have had the milestone added by a different person than the one who added the label.

(https://docs.backdropcms.org/documentation/adding-milestones-to-issues)

**Comment by BWPanda** [comment]
Thanks @AnjaliJha1221 for the PR! I've merged it into 1.x and 1.21.x.

**Comment by AnjaliJha1221** [comment]
Thanks for the help @stpaultim, and @BWPanda
