### ISSUE TITLE
Added PHP 8.1 support.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5398]
All my scripts default to using 7.4, but I just updated lando on my local to 3.6.0 and gave it a spin with php8.1/apache2:
- bee gave me multiple `Fatal error: During inheritance of ArrayAccess: Uncaught ArgumentCountError: Too few arguments to function bee_error_handler()` so installing/configuring automatically failed
- ```
  Deprecated: Return type of DatabaseStatementBase::execute($args = [], $options = [])
  should either be compatible with PDOStatement::execute(?array $params = null): bool,
  or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
  in /core/includes/database/database.inc on line 2266
  ```
- multiple "Deprecated function" errors during manual installation:

  - ```
    Deprecated function: Return type of DatabaseStatementEmpty::current()
    should either be compatible with Iterator::current(): mixed,
    or the #[\ReturnTypeWillChange] attribute should be used
    to temporarily suppress the notice in require_once()
    (line 2352 of /core/includes/database/database.inc).
    ```
  - ```
    Deprecated function: Return type of DatabaseStatementEmpty::next()
    should either be compatible with Iterator::next(): void,
    or the #[\ReturnTypeWillChange] attribute should be used
    to temporarily suppress the notice in require_once()
    (line 2352 of /core/includes/database/database.inc).
    ```

  - ```
    Deprecated function: Return type of DatabaseStatementEmpty::key()
    should either be compatible with Iterator::key(): mixed,
    or the #[\ReturnTypeWillChange] attribute should be used
    to temporarily suppress the notice
    in require_once() (line 2352 of /core/includes/database/database.inc).
    ```

  - ```
    Deprecated function: Return type of DatabaseStatementEmpty::valid()
    should either be compatible with Iterator::valid(): bool,
    or the #[\ReturnTypeWillChange] attribute should be used
    to temporarily suppress the notice
    in require_once() (line 2352 of /core/includes/database/database.inc).
    ```

  - ```
    Deprecated function: Return type of DatabaseStatementEmpty::rewind()
    should either be compatible with Iterator::rewind(): void,
    or the #[\ReturnTypeWillChange] attribute should be used
    to temporarily suppress the notice
    in require_once() (line 2352 of /core/includes/database/database.inc).
    ```

  - ```
    Deprecated function: strlen():
    Passing null to parameter #1 ($string) of type string is deprecated
    in backdrop_random_bytes() (line 2556 of /core/includes/bootstrap.inc).
    ```

  - ```
    Deprecated function: strlen():
    Passing null to parameter #1 ($string) of type string is deprecated
    in backdrop_validate_utf8() (line 2089 of /core/includes/bootstrap.inc).
    ```

  - ```
    Deprecated function: str_replace():
    Passing null to parameter #3 ($subject) of type array|string is deprecated
    in filter_xss() (line 1831 of /core/includes/common.inc).
    ```

  - ```
    Deprecated function: strlen():
    Passing null to parameter #1 ($string) of type string is deprecated
    in backdrop_validate_utf8() (line 2089 of /core/includes/bootstrap.inc).
    ```

  - ```
    Deprecated function: str_replace():
    Passing null to parameter #3 ($subject) of type array|string is deprecated
    in filter_xss() (line 1831 of /core/includes/common.inc).
    ```

  - ```
    Deprecated function: strpos():
    Passing null to parameter #1 ($haystack) of type string is deprecated
    in url_is_external() (line 2755 of /core/includes/common.inc).
    ```

  - ```
    Deprecated function: str_replace():
    Passing null to parameter #3 ($subject) of type array|string is deprecated
    in url_is_external() (line 2757 of /core/includes/common.inc).
    ```

  - ```
    Deprecated function: ltrim():
    Passing null to parameter #1 ($string) of type string is deprecated
    in url() (line 2652 of /core/includes/common.inc).
    ```

**Comment by klonos** [comment]
...the work already done in https://www.drupal.org/project/drupal/issues/3224299 should help

**Comment by indigoxela** [comment]
@klonos just in case you're still working on this issue: I now have php 8.1 available for local testing. Just let me know.

**Comment by sojibdg** [comment]
I can test after done PHP 8.1.

**Comment by klonos** [comment]
Thanks @indigoxela ...please feel free to test and either file a new PR, either using mine as a starting point, or afresh.

**Comment by indigoxela** [comment]
I'm struggling with the database abstraction layer. Adding some `#[\ReturnTypeWillChange]` like Drupal7 did, severely breaks Backdrop.

Deprecated:
```
    Deprecated function: Return type of DatabaseStatementBase::execute($args = [], $options = []) should either be compatible with PDOStatement::execute(?array $params = null): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in require_once() (line 2250 of ...core/includes/database/database.inc).
    Deprecated function: Return type of DatabaseCondition::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in require_once() (line 1683 of ...core/includes/database/query.inc).
```
@klonos I'm assuming this was also what you were struggling with (WSOD, sometimes immediately, sometimes after some other activity).

For changes in core/includes/database/* we definitely need someone familiar database abstraction layer. I don't feel qualified for that.

**Comment by indigoxela** [comment]
Maybe it's interesting what breaks when adding the (necessary) `#[\ReturnTypeWillChange]` in files below core/includes/database/:

```
Error: Call to undefined function _backdrop_error_handler_real() in require_once() (line 5981 of .../core/includes/common.inc).
```
If I comment out `require_once BACKDROP_ROOT . '/core/includes/errors.inc'` in that line in file common.inc, Backdrop seems to work fine without any nagging. But that's of course no solution. :wink:

**Comment by indigoxela** [comment]
And now I'm stuck.

1.
Adding `#[\ReturnTypeWillChange]` to function function execute in DatabaseStatementBase, as suggested by deprecation warnings, breaks all tests. So I reverted it.
Needs a database abstraction layer expert.

2.
It seems like doing a require_once of errors.inc causes Backdrop to completely break. And also many functional tests.
Very odd that attempting to include a file causes errors - nagging that functions, which ship with exactly that file do not exist.
Needs a Backdrop bootstrap expert.

**Comment by klonos** [comment]
Thank you so much for taking a stub at this @indigoxela 🙏🏼

**Comment by indigoxela** [comment]
Another stab... which causes me even more head scratching. And now we almost have test coverage passing. :tada: 

Remaining problems with views - which are actual problems, not only test failures in ViewsHandlerFieldTest:

- If the rewritten string is zero and empty_zero is not checked, the string rewritten as 0 should not be treated as empty.
- If the rewritten string is zero and empty_zero is not checked, "" rewritten as 0 should not be treated as empty.
- If the rewritten string is zero and empty_zero is not checked, 0 should not be treated as empty.
- If the rewritten string is zero and empty_zero is not checked, "0" should not be treated as empty.

Now back to my "head scratching problems" - it's all about require_once inside functions (I guess).

**Comment by indigoxela** [comment]
I'm trying to understand that funny views test and am not so sure anymore, if the functionality is broken or not. :stuck_out_tongue_winking_eye:

**Comment by indigoxela** [comment]
Stuck again... :disappointed: I now stared an hour or so at [this views code](https://github.com/backdrop/backdrop/blob/1.x/core/modules/views/handlers/views_handler_field.inc#L1208) trying to understand, how it's *supposed* to work, but am not able to. I also stared at function is_value_empty() for a while... no enlightenment. Maybe it's just because of the odd variable names...

**Comment by indigoxela** [comment]
That views thing turned out to be an easy fix.

One remaining concern: several times I had trouble with the deprecations causing fatal errors because either _backdrop_error_handler_real or _backdrop_get_last_caller weren't available yet. So maybe we should consider to include errors.inc earlier. That include is done several times in bootstrap.inc and once in common.inc but apparently sometimes too late? That could as well be a follow-up, though.

Ready for testing and review.

**Comment by jenlampton** [comment]
This PR looks really good. Nothing that seems potentially dangerous, mostly typecasting. I'd think this might be a possible candidate for 1.21.0, or even a bug-fix release if core developers are comfortable with it.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/3879 looks good to me and low-risk. I read through it multiple times and couldn't find any issue. Combined with full tests passing, I think this is ready to go.

I had to read multiple sources to try and understand the `#[\ReturnTypeWillChange]` code comment and what the alternative was to it, I found https://stitcher.io/blog/new-in-php-81#interal-method-return-types-rfc to be the most helpful description. We're setting ourselves up for trouble with PHP 9.0 though, where that code comment will no longer be respected and return types _must_ be specified in the method declaration. That sounds like it will be impossible for projects that override core PHP classes to support PHP 5/7 and PHP 9+ at the same time.

However at the current time, I think this is certainly the easiest approach available (and aligns with what Drupal is doing for the time being).

**Comment by indigoxela** [comment]
> We're setting ourselves up for trouble with PHP 9.0 though, where that code comment will no longer be respected

Yes, with these comments we just defer, but don't fix the problem yet. We'll need a follow-up to dig deeper and figure out, how to properly fix the return types in a backwards compatible way.
Backdrop's not the only project struggling with this, I guess.

**Comment by klonos** [comment]
With the next minor release being imminent, do we want to risk merging this in 1.21.0, or defer to 1.22.0 to allow more thorough testing? I think that the latter makes sense, because:
- we already have support for php 8.0 - no real rush for 8.1
- this will go hand-in-hand with the change of minimum version of php 5.6

However, I'd want us to merge into 1.x soon after 1.21.0 is released, to allow for it to be used in all PR sandboxes, and thus provide more "exposure" to testing.

**Comment by quicksketch** [comment]
I was thinking that we might merge it after 1.21.0 is out and include it in the 1.21.x branch, so it would be in 1.21.1. It doesn't include any API changes. Fixing fatal errors and notices (even in a new PHP version) might count as bug fixing.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3879 into 1.x and 1.21.x. Great work @indigoxela!
