### ISSUE TITLE
[UX][DX] Improve the description for the Path field on the configure layout page.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5399]
In tinkering with Layouts lately (and writing up some description for a blog post), I thought of a couple changes to the Configure Layout page (`admin/structure/layouts/manage/%/configure`) that might be improvements. Putting them out there in this issue to get feedback and further thoughts.

Here's the relevant section of that page and the issues:

![layouts_before](https://user-images.githubusercontent.com/29214084/146112129-c1fe03de-8203-4d7c-92ec-44302dd646ed.jpg)

**1. Long description for Path.** There are 5 lines of description text for paths, which takes up a good-sized chunk of vertical space. Surely most users don't need to see the full list of examples after the first or second time. This seems like "extra information" that is a good candidate for the recently-introduced `details` form element, so it can stay collapsed most of the time, but is expandable when needed (and has summary text that hints at what's inside).

**2. Layout-created page or overridden page?** This seems like it's important enough that it should be visible to the user as soon as they've finished typing in their path. So I'd like to see some immediate indication of whether the given path gives rise to a layout-created or overridden page.

**3. (Optional) contexts.** The description text for Contexts begins with "(Optional)", but at least some of the time, there's nothing optional about it, for example, for the path `node/%`, as in the example above. And when it is optional, it should be obvious from the existence of a select drop-down that there's some options going on. So I think we can drop that parenthetical.

After making changes in response to those, here's what that section looks like:

![layouts_after](https://user-images.githubusercontent.com/29214084/146114168-a470791c-c440-42c8-885f-a2d1c03c5fd3.jpg)

Expanding the "Paths and placeholders" details element gives this:

![paths_placeholders](https://user-images.githubusercontent.com/29214084/146112886-b6951d89-9602-4491-ab60-27d47f385624.jpg)

And for layout-created pages, we see this:

![layout_created](https://user-images.githubusercontent.com/29214084/146113025-d3b8df1b-58b7-4940-9342-bb947c2c03c7.jpg)

I've made a PR so people can try it out in the Tugboat sandbox. I solicit feedback on any aspect, but two in particular:

1. The layout override message is "This layout will override the page(s) created by function _node_page_view_,"which is a bit unsatisfactory because most non-coding site builders neither know nor care about the name of the page generating function. I wanted to give a little more information than just "This page will override some page(s)," though. Any ideas on what a better message would be here?

2. The layout-created/override message doesn't update quite as quickly as it should (for example, not as quickly as the Context sections update—you need to tab out to get the former to update). If I'm missing something in the ajax implementation, I'd appreciate any pointers toward a better way of doing the updating. [Update: this is now working the way it should.]

**Comment by stpaultim** [comment]
I did some quick testing and believe that this is better. I don't have the suggested text improvements you are looking for and would like to think about this a little more. 

I've been testing the new Mini-layouts module and I'm slowing beginning to grasp some of this layout stuff better. But, I need more time

**Comment by bugfolder** [comment]
After a good night's sleep, I figured out how to properly do the updating (item 2 above). The page type (layout-created vs overridden) now updates at the same time as the list of contexts.

**Comment by docwilmot** [comment]
I like. Not sure about the wording either though. The layout doesnt really 'override' the page, it more like wraps the page in that layout. I think maybe "This layout will be applied to existing paths provided by the Node module" or more concise "This layout will be applied to existing paths"; I'm not sure mentioning the function or the module really provides much.

**Comment by bugfolder** [comment]
> The layout doesnt really 'override' the page

Good point. It overrides the default layout, not overrides a page.

> I think maybe "This layout will be applied to existing paths provided by the Node module"...

I was trying to mirror the language in https://github.com/backdrop/backdrop-issues/issues/5077, which separates layouts into "Layout pages" and "Layout overrides". Maybe the description language should change there, too. How about:

"This layout will override the default layout for existing page(s) provided by..."

> I'm not sure mentioning the function or the module really provides much.

Yeah, for maybe most people it doesn't, but that little bit of extra information might help for some. Just saying which module it comes from is definitely less "techie", though, so non-coder-friendlier.

But that raises a new technical question: given a function name, how do we find out what module it's declared in? Yes, it's (probably but not necessarily) prefixed by the module name, but we don't know for sure where the prefix stops. All we get in the menu_router table is the function name and (only some of the time) the file path of the include file.

Maybe just put that function name in a parenthetical? To hint that it's not important for those who don't care.

**Comment by olafgrabienski** [comment]
> There are 5 lines of description text for paths, which takes up a good-sized chunk of vertical space. Surely most users don't need to see the full list of examples after the first or second time.

I like the details element idea but would miss the examples as a quick reminder what to type here. @bugfolder What do you think of keeping the probably most common example in the visible text and adapting label and text of the details element like in the mockups below?

(Re the label I'm not sure, maybe just `Placeholder examples` instead of `Common placeholder examples`.)

**Mockup, collapsed**

![backdrop-pr3865-mockup-collapsed](https://user-images.githubusercontent.com/14188307/146370492-2fb2f491-5cd9-4367-adb1-feda31e6bec4.png)

**Mockup, expanded**

![backdrop-pr3865-mockup-expanded](https://user-images.githubusercontent.com/14188307/146370496-4db97f62-4594-4c53-bd7c-011d61bbf26b.png)

**Comment by bugfolder** [comment]
> What do you think of keeping the probably most common example in the visible text and adapting label and text of the details element like in the mockups below?

I like the idea of keeping visible the "Use the percent symbol text..." (which was formerly in the `'#description'` for the text field). I think, though, that if we go that route, it should stay in the description, and should come _before_ the sentence that gives the result of the user's choice.

Here's an example of that:

![example_1](https://user-images.githubusercontent.com/29214084/146395067-a5d93ed0-475c-4a3a-9f2b-59fae22a26d9.jpg)

And expanded (with the other version of a layout-created page):

![example_2](https://user-images.githubusercontent.com/29214084/146395110-92cc914c-7691-4bab-b3c5-afd1110e0859.jpg)

**Comment by olafgrabienski** [comment]
> if we go that route, it should stay in the description, and should come before the sentence that gives the result of the user's choice

Agreed!

**Comment by jenlampton** [comment]
I love where this issue is going! I have some suggestions for the new text :)

Can we change the text to "This path will create a new page." rather than using `layout-provided` there? It will be more friendly.

Also, for "Paths and placeholders" Can we change that to `Example placeholders for path`, or even just "Example placeholders".

I also wonder if we should add a special class for Details elements that are meant to hold description text. Description text is usually smaller and/or lighter than everything around it, to make it less prominent than elements on the page that are not descriptions for other elements. By moving these examples into `details` it's now become more prominent, rather than less. I think we would use this all over core, so I'll take a pass at a description like style (but I'm not sure if that should block this improvement?)

**Comment by jenlampton** [comment]
> **(Optional) contexts**. The description text for Contexts begins with "(Optional)", but at least some of the time, there's nothing optional about it, for example, for the path node/%, as in the example above. And when it is optional, it should be obvious from the existence of a select drop-down that there's some options going on. So I think we can drop that parenthetical.

The word "optional" was added here because the concept of contexts is confusing, and we didn't want to deter people from creating a layout because they didn't know what one was, or how to add one. Even if a field is not required, it's common human behavior to try to answer every question on a test. 

Would it be reasonable to add "Optional" as the first word of the description text (and maybe also see if we can remove it when a context is added automatically?) Or, maybe we use different text like "Not always needed" instead? Something that would encourage people to hit the save button. (We could also add this to the Visibility conditions if we find we something we like)

**Comment by bugfolder** [comment]
> Can we change the text to "This path will create a new page."

Yes. More concise.

> I also wonder if we should add a special class for Details elements that are meant to hold description text. 

I agree with the need and rationale; in https://github.com/backdrop/backdrop-issues/issues/4868#issuecomment-991084398, where the same situation arose, I introduced class `"details-help"`, which made the heading the same size as here. We could use that class here, too; or if a different class name is better, use that in both places.

**Comment by bugfolder** [comment]
> Would it be reasonable to add "Optional" as the first word of the description text (and maybe also see if we can remove it when a context is added automatically?) Or, maybe we use different text like "Not always needed" instead? Something that would encourage people to hit the save button. (We could also add this to the Visibility conditions if we find we something we like)

Ah, here's what made the "Optional" puzzling to me. The thing that is optional (for both Contexts and Visibility conditions) is that what's optional is **adding** them. The ones that are automatically added (because of placeholders) aren't optional to add (just optional, maybe, to choose what type they are). But the description text where "Optional" used to appear is pushed all the way below the table of automatically created contexts, as here:

![context_description](https://user-images.githubusercontent.com/29214084/146457665-c6d9edd6-8576-4533-8ac7-b505ec96e8f4.jpg)

I kind of would have thought that anywhere someone see a link "+ Add doohickey", they're going to assume that it's optional. For example, at the top of the layout listing, we have this:

![add_layout](https://user-images.githubusercontent.com/29214084/146457942-c112375f-f822-4f39-826b-9dc69387093f.jpg)

So I would question whether we need to emphasize with words that it's optional.

But one thing does seem like it might be a clarity improvement, which would be to move the description text (for both Contexts and Visibility conditions) to appear directly under the "+ Add ..." link, and above the table of things that are already present. But maybe this is too counter to the general model of "description text under the entire field it's describing."

**Comment by bugfolder** [comment]
Just noticed this (with path `node/%`):

![relationship](https://user-images.githubusercontent.com/29214084/146458596-74916cd4-8af5-4dac-b9e1-ede6a4a98025.jpg)

The description text talks about contexts, but says nothing about relationships. If the "+ Add relationship" link is present, shouldn't the description text say something about what a relationship is? (And any suggestions on what that added sentence should be?)

**Comment by bugfolder** [comment]
How about this for Contexts description text? It more closely mirrors the text that's on the dialog that pops up.

![context_help](https://user-images.githubusercontent.com/29214084/146461504-903d7725-cc4a-46d6-b1f8-0ae70c7b5bb3.jpg)

And then if the path supports relationships, we get this (again, the description text is based on the text that appears in the popup dialog):

![relationship](https://user-images.githubusercontent.com/29214084/146461696-9fa64eed-d082-47ee-b313-0f63b6390f61.jpg)

**Comment by bugfolder** [comment]
Pick, pick, pick. Just noticed this (description text for Visibility conditions):

> Visibility conditions allow this layout to selectively apply to different situations, such as different types of content at the same placeholder path.

Shouldn't it just be "...different types of content at the same path."?

**Comment by jenlampton** [comment]
> I also wonder if we should add a special class for Details elements that are meant to hold description text

I've filed a PR against the current PR that adds CSS for the details element:

<img width="1261" alt="Screen Shot 2021-12-16 at 3 12 55 PM" src="https://user-images.githubusercontent.com/397895/146462588-651080e5-2480-4035-8954-e1effdad076f.png">

> I agree with the need and rationale; in #4868 (comment), where the same situation arose

Hm, that seems like it's also description text there... maybe we can use the same class for both.
 
> So I would question whether we need to emphasize with words that it's optional.

Yeah, that's fair. 

> But one thing does seem like it might be a clarity improvement, which would be to move the description text (for both Contexts and Visibility conditions) to appear directly under the "+ Add ..." link

I like this idea too!

> The description text talks about contexts, but says nothing about relationships. If the "+ Add relationship" link is present, shouldn't the description text say something about what a relationship is? 

Good point...

> (And any suggestions on what that added sentence should be?)

How about...  "Relationships can be used to join one context to another."

> How about this for Contexts description text?

I prefer the previous description text, actually. "Most placeholders in the path will be associated with a context automatically." is accurate. saying "...will automatically create..." sounds like all of them will, which might make people think it's broken for those that won't. 

> Shouldn't it just be "...different types of content at the same path."?

yes, that's better :)

**Comment by jenlampton** [comment]
> This path will create a new page.

I would like to see this text to the right of the Path input box, much like the example date is shown to the right of the date format box: 
<img width="884" alt="Screen Shot 2021-12-16 at 3 24 33 PM" src="https://user-images.githubusercontent.com/397895/146463580-d77a7f53-52f0-4b3b-8ce5-4cee0e4e3e73.png">

**Comment by bugfolder** [comment]
> ...sounds like all of them will, which might make people think it's broken for those that won't.

I didn't realize it was possible to add a placeholder without a context getting created for it, so yeah, it shouldn't imply that all do. What's an example of a layout path containing a placeholder that doesn't create a context?

**Comment by bugfolder** [comment]
> I prefer the previous description text, actually. [which was: "Contexts define what blocks are available within this layout."]

When you add a context, the dialog says: "Contexts provide additional information to blocks in the layout to display." This seems closer to the point of contexts (and it is nice to have the text similar in both places.) It seems like the main functional purpose of contexts is not to "define" blocks, but rather, to pass information to them (which has the side effect of setting what types of blocks show up, so that's sort of like "definition").

> I would like to see this text to the right of the Path input box, much like the example date is shown to the right of the date format box...

I'll work on adding that to the PR. (Thanks for the example to go scrutize!)

**Comment by bugfolder** [comment]
> I've filed a PR against the current PR that adds CSS for the details element:

Merged in.

> I would like to see this text to the right of the Path input box...

I set that up, but because the field is already pretty wide, the sentence following the box word-wrapped in a pretty ugly way on all but the widest window widths. So for now, I left it as-is, but would, of course, invite further PR that implemented it in a way that looks good on various window widths.

> move the description text (for both Contexts and Visibility conditions) to appear directly under the "+ Add ..." link

Current version of the PR is shown here.

![From Clipboard](https://user-images.githubusercontent.com/29214084/146479977-a80d5320-683c-4ec3-b025-c5f554f6d8bc.jpg)

**Comment by bugfolder** [comment]
Ugh. Tests failing. Will check in the morning.

**Comment by stpaultim** [comment]
I like where this is going. Thanks. 

I'm a little confused by the fact that by default when the path is empty it says "this path will create a page." Since, the path field is required, a blank path won't create anything, will it?

Should't the line that says "this path will create a page" be blank until a path is provided or say something like "a path field is required"?

**Comment by bugfolder** [comment]
Good catch, that line should be blank if the path field is blank. There's separate validation for the field being required. PR updated.

There is an annoying behavior of that page, that it starts throwing required-field validation errors at you for empty fields while you're still filling out the page ("I know it's blank, I'm still filling things out, dagnabbit!"). When those errors appear, they short-circuit the updating of later Ajax updating, so that if you enter a path, then delete it, you'll get the "Path field is required" error and the page won't update the path message (so it will still say "This path will create..." or "This layout will override...", whatever it said last).

That behavior—premature (?) validation errors—existed before this PR, so not sure if this is the place to try to address it (or even if it should be addressed—perhaps that's "works as intended").

**Comment by docwilmot** [comment]
Yes, it is pre-existing condition. Clicking the context or VC links runs the form validation handlers immediately, so the form errors out if the required fields are empty. But because the error is at the top of the page, you dont notice, and think the JS is broken. Very annoying. Inline form errors would help.

**Comment by bugfolder** [comment]
We've gone a while with no further feedback and it would be nice to get this into 1.21, so I'm going to hazard removing the "needs more feedback"/"pr needs work" and bump it up to "needs testing"/"needs code review".

**Comment by docwilmot** [comment]
Well now, had a look, and this seems to have become busier than the last time I saw it; in fact its busier than the original. I'm not sure its an improvement right now TBH. In core now everything but the main labels (in bold) are styled as help text (lighter, smaller) so though the placeholder stuff is verbose, it is not intrusive. 

With this PR though, we still have help text *and* now an additional collapsible area *and* another normal-font statement below that re the layout override etcetc. 

My preference would be to style everything as help text, and instead of the collapsible field, use a `more...` link, linke in the module list descriptions.

Sorry to bring this up after the long wait.

**Comment by bugfolder** [comment]
> Sorry to bring this up after the long wait.

No worries, as long as the issue is moving!

> My preference would be to style everything as help text, and instead of the collapsible field, use a more... link, like in the module list descriptions.

Looks like the more/less gadget is undergoing change: https://github.com/backdrop/backdrop-issues/issues/5090. No strong preference on my end for using that for the expandable examples. What do others think?

However, I think the "This layout will override.../This path will create..." text deserves more prominence than help text. Help text is something that's unchanging; this is important information the user needs to see.

**Comment by bugfolder** [comment]
I've updated the PR to deep-six the function name and eliminate explicit `<p>` tags (nowadays that is bad form).

Let me suggest that for now we go with the expandable `details` element for the placeholder examples, but when @klonos wraps up the new treatment of more/less links in https://github.com/backdrop/backdrop-issues/issues/5090, he can try out that solution here, as well as on the modules page.

Last possible issue: in today's Office Hours discussion, we noted that the "This layout will override.../This path will create..." text is somewhat separated from the path that it's talking about, which is less than satisfactory (hence @jenlampton's suggestion above to put it next to the field). If anyone has a better idea of how to get it closer to the path and look good across a range of screen sizes, please post a mockup.

**Comment by bugfolder** [comment]
Food for thought on the styling of the "This layout.../This path..." text. Here's how **New password** does the auto-updating information (styled like help text, immediately underneath the field, separated from the static help text). Would this be better?

![password](https://user-images.githubusercontent.com/29214084/147762511-7059f5f4-24ef-4ac4-8e49-8289fb021456.jpg)

**Comment by docwilmot** [comment]
For some inexplicable reason, I cannot access this PR sandbox from work, the site is blocked due to a security threat. This is the only sandbox with this issue. @bugfolder are you trying to hijack my job?

**Comment by bugfolder** [comment]
> are you trying to hijack my job?

Not intentionally! (But the  things I accomplish unintentionally are legion.)

**Comment by docwilmot** [comment]
> Food for thought on the styling ... Would this be better?

This looks so much cleaner to me

![path](https://user-images.githubusercontent.com/1042283/147800481-313b9c85-e817-41e0-aa72-81d92767b1f4.png)

**Comment by bugfolder** [comment]
> This looks so much cleaner to me

Yes. That drops the protocol://domainname header from display:

![path](https://user-images.githubusercontent.com/29214084/147800848-0cd7b74b-a370-4ecd-b501-6c9dab722bc3.jpg)

Which seems kind of superfluous anyhow (as well as ugly on Tugboat).

And, come to think of it, it seems a bit odd to try to make this entry look like a browser-bar URL, because much of the time, it's got placeholders in it and so no real URL would ever look like that. Is there a reason that we display that prefix here, but not in the many other places we ask the user to enter paths (e.g., menu items, visiblity conditions)? Here's how a menu path entry looks:

![menu](https://user-images.githubusercontent.com/29214084/147800999-3b420951-4713-48a1-b913-496043f8b6a2.jpg)

**Comment by docwilmot** [comment]
Actually this was a quick mock up and I didn't float the path label, and I wasn't suggesting we stop floating it. But yes it's ugly in sandboxes.

**Comment by bugfolder** [comment]
You may not have intended to suggest leaving that out, but I think you were on to something that's worth questioning further. In looking around at places where we enter paths of various sorts, sometimes we add the protocol/domain, sometimes not. For example, on the node edit form, URL aliases are like this:

![eidt_node_url_alias](https://user-images.githubusercontent.com/29214084/147833373-cd4cbcf4-1a16-47f3-afc6-dae5cc9c03fd.jpg)

while redirects are like this:

![node_add_redirect](https://user-images.githubusercontent.com/29214084/147833388-aab33885-fe2a-4926-a953-e4c018db06ca.jpg)

(That's also how they're shown on the Add/Edit redirect page, admin/config/urls/redirect/add.)

And on the system site information page at admin/config/system/site-information, there are both: Logo settings and Shortcut icon settings use path fields with no prefix, but Home page and Error pages do use a prefix:

![system_site_information](https://user-images.githubusercontent.com/29214084/147833480-e219cf82-c47a-4b5f-8884-451316350abd.jpg)

If I look for what the underlying rule or principle is here, it seems to be this: in some places we want the user to be thinking of (or entering) a full, valid URL, but as a convenience, we're providing the protocol/domain fragment, so they only need to enter the system path, or url alias, or request path. But in places where the thing we want is this internally used path, we just ask for the bare path and don't try to make it look like a full URL.

Now, what's the applicable situation with the layout configuration page? Here we're not asking for a URL alias, a system path, or a request path; we're asking for what amounts to a menu router path (because it can contain % placeholders). I don't know of anywhere else in the UI where we ask the user to enter a menu router path (is there one?)

But it seems like everywhere we provide the protocol/domain prefix, the result is a real, valid, URL; and that's not the case here for a path that contains placeholders. So it seems like, on balance, this field would be better off without the prefix.

**Comment by bugfolder** [comment]
I've created a second PR that implements the version that @docwilmot suggested with a more compact presentation, with the dynamic information about the page in the field description

Here's what it looks like for a layout-created page:

![nope](https://user-images.githubusercontent.com/29214084/147890999-43a0770a-e6f2-4c12-9958-96e0f5a8a98c.jpg)

And here is an overridding page, with the placeholder examples expanded:

![node](https://user-images.githubusercontent.com/29214084/147891018-f75c947d-9b44-4c7c-bbe4-b3278811dcb4.jpg)

I've left off the URL prefix, for reason outlined above; but if there's a strong feeling that it should be present, it's easily restored.

**Comment by docwilmot** [comment]
I like this. I imagine leaving out the path prefix might lead to some discussion, but I dont mind it myself.

**Comment by bugfolder** [comment]
Per a comment from @klonos, changed:

* "more" --> "Show examples"
* "less" --> "Hide examples"

**Comment by klonos** [comment]
I also like this a lot! Thanks @bugfolder 🙏🏼

**Comment by docwilmot** [comment]
Minor nitpick I hesitate to mention, but when creating the layout, the text says "this path *will* create a page", but if youve already saved the layout and returning to the layout configure page, it *could* say something more to the effect that "this layout has created its own page" or something such.

**Comment by klonos** [comment]
This works as expected, and the fixing of the indicator text can be a follow-up, so I've set this to "works for me". Code looks good to me as well, but there were a couple of coding standards to nitpick on.

This seems like a UX improvement task rather than a new feature request to me, so labelling it accordingly.

**Comment by bugfolder** [comment]
> Minor nitpick I hesitate to mention...

Thanks for mentioning it! I've added more slightly tweaked wording based on the whether there's a placeholder or not, whether it's a new layout or an existing one, and (of course) whether it's a layout-created page or an override page. Here's the six possibilities:

* path node/%, new or existing layout
![node:%](https://user-images.githubusercontent.com/29214084/147896971-48f25adb-ca69-4c05-b915-4ae116e8e9e2.jpg)

* path node, new or existing layout
![node](https://user-images.githubusercontent.com/29214084/147896975-7150b8d8-c25f-497d-a83d-3f13f03fa9c0.jpg)

* path nope/%, new layout
![nope:%, new](https://user-images.githubusercontent.com/29214084/147896977-1ef14032-98a6-4816-8f46-2128cd0464db.jpg)

* path nope, new layout
![nope, new](https://user-images.githubusercontent.com/29214084/147896981-6f7bc9e4-ead9-43d8-93d3-45a4f06dd00b.jpg)

* path nope/%, existing layout
![nope:%, existing](https://user-images.githubusercontent.com/29214084/147896984-a5a096eb-c6cc-458d-b71f-5a078c068486.jpg)

* path nope, existing layout
![nope, existing](https://user-images.githubusercontent.com/29214084/147896986-2dcb3e8c-8186-4e5c-b565-7c196053495b.jpg)
 
Also per a comment by @docwilmot (in today's sprint), I've restored the URL prefix.

**Comment by indigoxela** [comment]
Ooops, several Layout related tests are currently failing. Tests should get updated, I guess.

**Comment by klonos** [comment]
> ...I've added more slightly tweaked wording based on the whether there's a placeholder or not, whether it's a new layout or an existing one, and (of course) whether it's a layout-created page or an override page....

Thanks @bugfolder ..."will provide" for existing layouts (instead of "will create") is a very good choice 👍🏼 ...perhaps the variant "provides" is even better?

**Comment by bugfolder** [comment]
Tests don't need updating, I just need to pay closer attention to code issues. Now fixed. But I'll take the opportunity to use "provides" per @klonos's suggestion, and also to make the same "will" for new/"does" for existing distinction for overrides. Back to code review (now with passing tests).

**Comment by klonos** [comment]
Looks good to me 👍🏼

**Comment by docwilmot** [comment]
> Also per a comment by @docwilmot (in today's sprint), I've restored the URL prefix.

I'm not seeing it though.

**Comment by bugfolder** [comment]
Sigh. I think it regressed when I merged in something above. It's back now.

**Comment by quicksketch** [comment]
I think maybe this should be in the bugfix milestone instead of the minor milestone (i.e. 1.20.4)?

I left some comments in a code review: https://github.com/backdrop/backdrop/pull/3890#pullrequestreview-843161504

Concept looks great, just lots of implementation nitpicks.

**Comment by bugfolder** [comment]
> I left some comments in a code review

@quicksketch, thanks for comments, suggestions! I've implemented most of them, left one question open (on IDs vs classes vs consistency with existing code) in the review.

You suggested wrapping the db query in a separate private helper function, which I've done, creating `_layout_menu_router_path_exists($path)`, which returns whether the menu router path `$path` exists in the menu router table. But since it seems like a useful utility, I wonder if it warrants "promotion" to a public function in `menu.inc`, e.g., `menu_router_path_exists($path)`?

**Comment by quicksketch** [comment]
> But since it seems like a useful utility, I wonder if it warrants "promotion" to a public function in menu.inc, e.g., menu_router_path_exists($path)?

I'm not sure. Menu functions are so widely used, I think if we find it necessary that should be its own issue and we should try to find if we can put it to immediate use in a few places to demonstrate the need (and make sure it actually meets the need). For now I think the stand-alone, private function seems fine.

I reviewed all the code changes and re-tested. This looks great! Combined with the messages we added when putting in a path like `node/1`, this makes the Path field a lot less prone to user-error.

@bugfolder if you're okay with things as-is, I think this is ready.

**Comment by bugfolder** [comment]
> if you're okay with things as-is, I think this is ready.

I am! Let's roll.

**Comment by quicksketch** [comment]
Great work folks! I really like where this ended up. Subtle and helpful at the same time. I really like the increased accuracy of the description text based on the situation. I merged https://github.com/backdrop/backdrop/pull/3890 into 1.x and 1.20.x. Thanks @bugfolder, @docwilmot, @stpaultim, @jenlampton, @klonos, and @olafgrabienski!
