### ISSUE TITLE
Machine names for fields reported as not unique when only partly matching

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#540]
To reproduce:

1) create a field with the machine name `field_required_checkboxes` 
2) create a second with the machine name `field_required_check` 

You will get the following error:
```The machine-readable name is already in use. It must be unique.```

**Comment by BWPanda** [comment]
It looks like this came about as a result of changing to CMI, specifically using the `config_get_names_with_prefix()` function for getting matching fields. I've tried to fix this as best I could, but there may be a more elegant solution...

**Comment by quicksketch** [comment]
Great work @BWPanda. Merged in https://github.com/backdrop/backdrop/issues/633.
