### ISSUE TITLE
[PS][D8] Internal Page Cache module

### ISSUE THREAD

**Issue by domaingood** [backdrop/backdrop-issues#5402]
Drupal 8 or higher provides an Internal Page Cache module that is recommended for small to medium-sized websites. This core module, which is enabled by default, caches pages for anonymous users. It can be found at core/modules/page_cache.

This feature improves performance because it speeds up the site. Pages requested by anonymous users are stored the first time they are requested and then reused; depending on your site configuration, the performance improvement may be significant.

To speed up your site for authenticated users, see the Dynamic Page Cache module.

Websites that serve personalized content to anonymous users (dynamic, per-session, e.g. a shopping cart) will want to disable the Internal Page Cache module. This module assumes pages are identical for all anonymous users. Those websites can still take advantage of the Dynamic Page Cache module though, or can alternatively do their personalization using JavaScript + AJAX.

Configuring the Internal Page Cache module
On the Performance (admin/config/development/performance) page, you can configure how long browsers and proxies may cache pages. There is no other configuration. The value set for the maximum time a page can be cached by browsers and proxies will be used by Cache-Control headers. This setting is ignored by the Internal Page Cache itself, which caches pages permanently until invalidation unless they carry an Expires header.

Comparison to Drupal 7
Drupal 7 has no instantaneous updates; the page cache in Drupal 8 or higher is instantly updated when something has changed.
Drupal 7 required the entire page cache to be cleared whenever any content was modified; Drupal 8 or higher uses cache tags to only clear the cached pages that depend on the modified content.
Drupal 7 kept serving outdated pages in many cases; any module (and even parts of Drupal 7 core) failed to clear the page cache.
Drupal 7's internal page cache is not enabled by default. Many users don’t know they should enable this. Drupal 8 or higher enables page cache for anonymous users by default. It can do this, thanks to the cache tags mentioned in the previous point. In Drupal 7, having the internal page cache enabled by default would have caused broken behavior (precisely because we did not have cache tags in Drupal 7).
https://wimleers.com/blog/drupal-8-page-caching-enabled-by-default

**Comment by klonos** [comment]
Hello @domaingood ...unless I'm horribly mistaken, the page_cache module is not something new - it is the caching mechanism used in D7 (and Backdrop), which our Drupal brethren have turned into a separate, self-contained module that can be turned on/off. The issue that resulted in that was [Move internal page caching to a module to avoid relying on config get on runtime](https://www.drupal.org/project/drupal/issues/2368987) ([change record](https://www.drupal.org/node/2424389)).

The new things in D8 and beyond is the Dynamic Page Cache module, and cache tags.

**Comment by klonos** [comment]
@hosef can you please chime in re the above? ^^

**Comment by hosef** [comment]
@klonos I believe that is correct. 

I think that what @domaingood actually wants is https://github.com/backdrop/backdrop-issues/issues/4127

**Comment by domaingood** [comment]
@klonos @hosef #4127 & #5402 deferent things. both are not same module.

**Comment by klonos** [comment]
@domaingood all I'm trying to say is that we don't need the Internal Page Cache module in Backdrop - we already have that functionality. We could separate that functionality into its own module that could be turned on/off, but I see no reason for it unless we decide to implement #5217 (which I don't know if it is possible or how much work it'd be).

**Comment by domaingood** [comment]
Thank you for the clarification @klonos and thanks for review @hosef .
I m going to close this issue.

**Comment by domaingood** [comment]
Thank you for the clarification
