### ISSUE TITLE
Change "path alias" to "URL alias" throughout core code

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5405]
Per https://github.com/backdrop/backdrop-issues/issues/4868#issuecomment-996279953, the term "path alias" has been replaced by "URL alias" in Backdrop. But the term "path alias" is used in many places in the code and, importantly, in the visible documentation:

There is a "path alias" here: https://docs.backdropcms.org/api/backdrop/core%21includes%21path.inc/function/backdrop_get_normal_path/1

This page uses both "URL alias" and "path alias":
https://docs.backdropcms.org/api/backdrop/core%21includes%21path.inc/1

A search through core code turns up 61 uses of "path alias" but 187 uses of "URL alias".

It will help consistency and documentation to use the same term everywhere.

Although there is https://github.com/backdrop/backdrop-issues/issues/2821, which suggests to rename the `url_alias` table to `path_alias`, which would seem to be counter to "URL alias" being the official term.

**Comment by hosef** [comment]
As far as I was aware we don't actually have URL aliases anywhere, we have path aliases internally and lies in our user interface.
The only thing we store in the table she mentioned is the path and not the whole URL, which means you also can't have an alias based on any URL parts other than the path.

**Comment by bugfolder** [comment]
If I had my druthers (or we were starting over), I'd call it an "alias path" (to go along with "system path", "normal path", "router path," and REQUEST_PATH, all being examples of "&lt;something&gt; path"). But I don't have a strong opinion, other than that I'd like us to pick one term and then I can help make it consistent throughout code and docs.

**Comment by jenlampton** [comment]
> But I don't have a strong opinion, other than that I'd like us to pick one term and then I can help make it consistent throughout code and docs.

Yeah, that's what we tried do to. See : [[UX] Decide what to call a URL alias and do it consistently](https://github.com/backdrop/backdrop-issues/issues/1250)

**Comment by bugfolder** [comment]
Great! So we are set: it's "URL alias". PR now needs for review and testing.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/3873 looks good to me. I counted a total of 12 translated string changes with the remaining ~60 changes being documentation updates.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3873 into 1.x for 1.21.0. There are minor merge conflicts and this includes string changes, so I think it's fine if we only pull this into 1.x. 1.21.0 comes out this week. Thanks @bugfolder, @klonos, @hosef, and @jenlampton!
