### ISSUE TITLE
[UX] Switch to using `'#type'=>'help'` instead of wrapping `#markup` in `<p>`.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5412]
There are a few places in the code where we're still using `#prefix' => '<p>'`, `#suffix => '</p>'`, where we should be using `'#type' => 'help'`.

H/T @klonos.

**Comment by klonos** [comment]
Thanks @bugfolder 😉 ...manually tested the 3 places where the change was made, and confirmed that the help text appears as expected 👍🏼 ...the code also looks good (no `;` instead of commas in the arrays and all 😅 - inside joke between @bugfolder and myself), so RTBC.

**Comment by bugfolder** [comment]
I noticed that there's 21 instances of things like this (from layout.admin.inc):

```
  $page['description_container']['description'] = array(
    '#markup' => '<p>' . t("Provides a summary of all available blocks. ...") . '<p>',
  );
```

So there's more to do.

**Comment by bugfolder** [comment]
And now done. Back to testing and code review.

**Comment by herbdool** [comment]
Looks good

**Comment by quicksketch** [comment]
I think there are some places in the PR that don't necessarily align with `#type = help` situations. While right now the effect of help element is to simply wrap a `<p>` tag, if we were to add default styling for help elements like an icon, borders, or margins, some of these places might be unexpected. I think there are only two locations in the PR that aren't exactly "help" as we use it normally (at the top of the page or form): https://github.com/backdrop/backdrop/pull/3874#pullrequestreview-851082655
