### ISSUE TITLE
[DX] Fixed: Simpletest doesn't handle empty or malformed `.tests.info` files well.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5415]
## Description of the bug

If Simpletest encounters an empty .tests.info file, one containing only the packaging information but nothing else, then when you go to the Tests list, admin/config/development/testing, it puts a slew of "Warning: Illegal string offset..." messages into watchdog. These clog watchdog and it's not clear which of the possibly many .tests.info files might be causing this.

## Steps To Reproduce

To reproduce the behavior:

1. Add a module with one or more empty .tests.info file to your installation. (The current version of Search API module is a good test case.)
2. Clear the watchdog log.
3. Go to admin/config/development/testing.
4. Clear the cache.
5. Go back to watchdog and see all the fireworks.

## Actual behavior

Lots of errors in watchdog, all showing up in simpletest.pages.inc, when the actual culprit is somewhere else (but no sign of where).

## Expected behavior

Some indication of where the problem lies.

## Additional information

The creation of a packaged but empty tests.info file is not as unusual as one might think, because Coder Upgrade sometimes generates these and they're easy to overlook since they're typically buried in subdirectories.

---

## Translation update:

New Strings:
* `File %uri contains no testing classes.`
* `File %uri contains a definition for %class that is not an array of testing class fields.`
* `File %uri contains a definition for %class that is missing field %keys.`
* `File %uri contains a definition for %class that is missing fields %keys.`
* `See the Testing Framework documentation.`

**Comment by bugfolder** [comment]
The attached PR checks for a malformed array (after parsing, the array values end up as strings, rather than arrays of class information) and if there's an error, it puts a warning into watchdog identifying the culprit file and skips further processing of that file, thereby suppressing all the unhelpful watchdog notices.

**Comment by klonos** [comment]
Nice catch @bugfolder 👍🏼 

Code looks good, and there is now a considerably more manageable set of "fireworks" in the log (instead of the dozens of pages of meaningless/confusing errors):

![image](https://user-images.githubusercontent.com/2423362/147376092-07662111-d9f5-40be-9ec2-26faaee4b5f7.png)

This is RTBC, but I have a couple of suggestions that may be worth exploring:
- would it be possible to catch the same instances of these warnings, and log only one of them?
- provide a link in the watchdog error, which takes the user to our documentation site, with instructions on what needs to be done

**Comment by bugfolder** [comment]
> would it be possible to catch the same instances of these warnings, and log only one of them?

The four reports you see at 23:51 are actually different messages, for four different files. I've updated the watchdog message to put the file name first, so it's likely to be visible even with truncation. Like this:

![temp](https://user-images.githubusercontent.com/29214084/147377884-661fa191-fa29-450c-9ff5-b31d4c04e527.jpg)

> provide a link in the watchdog error, which takes the user to our documentation site, with instructions on what needs to be done

Our documentation is pretty thin: https://docs.backdropcms.org/documentation/testing-framework. I'd say this would be a good follow-up issue, once we have some non-"documentation in progress" documentation in place. What's there right now would not be very helpful.

Since active code has changed, alas, taking it back to needs code review/needs testing.

**Comment by klonos** [comment]
The code change was trivial. Still RTBC 👍🏼

**Comment by klonos** [comment]
> Our documentation is pretty thin: https://docs.backdropcms.org/documentation/testing-framework

Add label to the issue accordingly.

**Comment by bugfolder** [comment]
OK. Link added. (I guess that will be a nag to go write some documentation on that page.)

Once more, unto the breach (of review/testing).

**Comment by klonos** [comment]
Thanks @bugfolder ...`watchdog()` already caters for a link as a parameter though. See https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/watchdog/1

**Comment by bugfolder** [comment]
Moved. (Never noticed or used that before. Another new thing to learn.)

**Comment by klonos** [comment]
Thanks once again @bugfolder 🙏🏼 ...I actually wasn't aware of it either, but noticed it the first time I had to use [`watchdog_deprecated_function()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/watchdog_deprecated_function/1).

This is once again RTBC, but there's one random failure in one of the php5 tests in the PR (seems to be a random failure to initiate GitHub Actions). Please restart the tests, and feel free to update the issue labels once tests are green 😉

**Comment by bugfolder** [comment]
😮‍💨 I've done the close-and-reopen thing four times now, and each time testing fails (usually on different tests; every test has passed at least once). I'm guessing that GHA had a wee bit too much eggnog over the holidays, so I'm going to wait a bit and try again later.

**Comment by klonos** [comment]
> I'm guessing that GHA had a wee bit too much eggnog over the holidays

😅 

Both times I checked, the error was "Failed to download action", which does indeed point to a GitHub Actions thing 🤷🏼

**Comment by bugfolder** [comment]
Finally. Tests passed.

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼 ...RTBC from me 👍🏼 

Now someone needs to add the actual milestone, and remove the milestone label.

**Comment by docwilmot** [comment]
I cant reproduce this at all

**Comment by bugfolder** [comment]
> I cant reproduce this at all

Are you using [Search API](https://backdropcms.org/project/search_api) as the test case? The module doesn't need to be enabled, just present in the modules folder. And you do need to clear the cache, then view the list of tests page, to decorate watchdog.

**Comment by bugfolder** [comment]
Since I've now expanded the Testing Framework page, I'm going to remove the "Needs documentation" label. Further edits/suggestions to that documentation should go into the docs issue https://github.com/backdrop-ops/docs.backdropcms.org/issues/171.

**Comment by bugfolder** [comment]
From https://github.com/backdrop/backdrop/pull/3876#discussion_r776883378:

> The situation should be that contrib should be responsible to ensure that test.info files are properly formatted. But in this case we find that if contrib messes up, in any way, core doesnt properly warn us about which contrib is messing up, so we should fix core this time. So I feel the solution should seek to discover the possible ways contrib could mess up and mitigate that. The solution youve got is specifically for empty files. But we get errors in these situations:

* files with statements (xxx = yyy) only
* file with statements before test cases
* incomplete sections (missing either or all of name, description, group, or file)

> In any of those situations the user would have no idea where this error is coming from, which is what I think we should try and solve, not just one situation.

**Comment by bugfolder** [comment]
So, I've now added further checking that detects the maliformities listed above (and then some) and puts the appropriate errors in watchdog. Attached is a list of malformed files to try it out on.

I briefly thought "oh, wouldn't it be nice to create automated tests that verify that Simpletest catches these bad files?" Simpletest testing itself (which it already does, of course). But if these bad files are anywhere within the installation, then Simpletest will complain to watchdog about them every time the testing cache rebuilds, which would, of course, be undesirable.

Also, I will note that one of the files (`statements_before_classes.tests.info`) puts an additional PHP error into watchdog, in addition to the Simpletest errors, because `backdrop_parse_info()` has a problem with that file. Hardening `backdrop_parse_info()` to avoid the PHP error is, I think, beyond the scope of this issue.

[bad_tests.zip](https://github.com/backdrop/backdrop-issues/files/7795107/bad_tests.zip)

**Comment by quicksketch** [comment]
Thanks @bugfolder, @klonos, and @docwilmot! I merged https://github.com/backdrop/backdrop/pull/3876 into 1.x and 1.20.x.
