### ISSUE TITLE
(Security Advisory) - Low - Password Field with Autocomplete Enabled.

### ISSUE THREAD

**Issue by OHDUDEOKNICE** [backdrop/backdrop-issues#5418]
This issue was moved to the internal/private Backdrop Security issue queue.

Please note the following re reporting security issues:

> **Please do not use this issue queue to report security issues**
> 
> If you believe you may have discovered a security issue with Backdrop CMS,
> contact the Backdrop Security Team directly at security@backdropcms.org. In
> order to keep everyone safe, we manage security issues separately in a private
> repository. So please refrain from publicly blogging, or tweeting about it until
> the issue has been resolved.
> 
> For more information about Backdrop CMS and security, please refer to:
> https://backdropcms.org/security

Once this has been reviewed internally by the Backdrop Security team, an official response will be provided here.

**Comment by quicksketch** [comment]
I'll go ahead and close this out. @OHDUDEOKNICE, we'll get back to you via email. Thank you for the report!
