### ISSUE TITLE
Error when creating a new view if comment module is disabled

### ISSUE THREAD

**Issue by behindthepage** [backdrop/backdrop-issues#542]
Notice: Use of undefined constant COMMENT_PUBLISHED - assumed 'COMMENT_PUBLISHED' in views_ui_views_ui_wizards() (line 675 of /home/thepage/public_html/addons/backdrop/core/modules/views/views_ui/views_ui.module).

**Comment by quicksketch** [comment]
Excellent, thanks guys! PR at https://github.com/backdrop/backdrop/issues/637 looks great. Merged.
