### ISSUE TITLE
[DX] Telemetry: Add Web Server (Apache/nginx/etc)

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5423]
## Description of the need

In addition to PHP version, MySQL version, and Server OS, we should collect web server: Apache or nginx (supported platforms) as well as other options (either consolidated into "Other" or separated).

## Proposed solution

Add Web Server into `system_telemetry_data()`.

Part of meta issue https://github.com/backdrop/backdrop-issues/issues/5231.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/3882 that segments into the following:

* Apache
* nginx
* Other

I'm not sure if we should try and identify other options individually or not. Backdrop officially supports Apache and nginx. Other webservers that _could_ run Backdrop and are above 1% web usage are Litespeed and IIS according to https://w3techs.com/technologies/overview/web_server

![image](https://user-images.githubusercontent.com/100206/147805315-9879ce2c-942b-405a-9728-e4a47d3432bb.png)

Options like "Cloudflare Server" and "Google Server" I believe are not application servers but merely reverse proxy caches that site in front of the application server.

**Comment by klonos** [comment]
This metric would help in issues like #5047 #4743 #4335, but if the "other" metric is consistently greatly below 20%, then I don't see how it would matter to dig further into which these "other" web servers are 🤷🏼

**Comment by klonos** [comment]
Thanks @quicksketch 🙏🏼 ...this is RTBC, but I've left a comment in the PR re using title case for `Web Server`.

**Comment by laryn** [comment]
Thanks @quicksketch for filing and fixing, and @klonos for the review! Merged into `1.x` and `1.20.x`.
