### ISSUE TITLE
Added settings for which parts of the book navigation to display.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5430]
## Description of the need

It would be nice to be able to specify which parts of book navigation appear on book pages, such as:
* Table of contents
* Previous/Next/Up links
* Add child page link

## Proposed solution

Add global settings, as follows:

<img width="1463" alt="Screen Shot 2022-01-02 at 4 44 20 PM" src="https://user-images.githubusercontent.com/397895/147895289-be546011-d858-4244-a7ba-02fc1e3a37bc.png">

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes global settings that allow you to select which parts of the book navigation should display on pages included in Books. 

---

**Translation update:**
New strings were introduced: `Display default book navigation on book pages`, `Select book navigation options`, `Table of contents`, `Previous, Next, and Up links`, `Select book links options`, `Add child page`,

**Comment by jenlampton** [comment]
Follow-up issue: https://github.com/backdrop/backdrop-issues/issues/5431

**Comment by jenlampton** [comment]
I reviewed the PR and it looks great! I left two tiny suggestions, neither of which should prevent this issue from not getting into 1.21.0 -- both can be done as follow-ups if necessary.

**Comment by herbdool** [comment]
@jenlampton ready for review again.

**Comment by jenlampton** [comment]
RTBC!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3812 into 1.x for 1.21.0. Thanks @herbdool and @jenlampton!

**Comment by klonos** [comment]
Sorry I missed the chance to review the PR. There was a tiny coding standard miss + a series of conditionals that could be grouped together. Follow-up PR for consideration: https://github.com/backdrop/backdrop/pull/3893

cc @quicksketch and/or @herbdool

**Comment by metatop** [comment]
When updating all my sites to version 1.21 those options have all been disabled, and I have driven myself crazy until I found them. A chaos.

**Comment by jenlampton** [comment]
Hm, it sounds like the update either didn't run, or didn't work properly.
We're there any errors in your log after running update.php?

**Comment by metatop** [comment]
At the time of performing the update, no errors were registered in any of the 5 sites where it was executed.

**Comment by jenlampton** [comment]
Thank you for letting us know. I have a few sites that haven't been updated yet that I can test this on too.

**Comment by herbdool** [comment]
I've tested the update hook just now. It works for me - I can't replicate the issue.

**Comment by jenlampton** [comment]
@metatop can you share the settings that were on the blocks that did not get properly updated?

**Comment by metatop** [comment]
Today I have updated two more sites and it has not given me that problem, All the sites have the same configuration and the same theme, and they are in the same hosting. So I have no idea where it could have gone wrong.

**Comment by jenlampton** [comment]
Thank you for reporting Back. 
I've had several other sites that haven't given me any trouble as well. If you do see the problem again, please open a new issue with the settings before and after the update so we can track down the problem.
