### ISSUE TITLE
Telemetry module stats incorrect

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5444]
## Description of the bug

Copied from https://github.com/backdrop-ops/backdropcms.org/issues/866

Telemetry stats are incorrect since telemetry module was enabled by default. Partly because Tugboat repos and possibly because of telemetry being enabled during a Dashboard test (bug, error, accident).

PR upcoming.

**Comment by klonos** [comment]
Thanks @docwilmot 🙏🏼 ...code changes look good to me 👍🏼

**Comment by indigoxela** [comment]
I'm curious...

```
settings_get('telemetry_enabled', TRUE)
```

Did we miss to document that setting, or does that setting only exist for Tugboat? Means: it should stay "secret".
Should we use the same setting for GHA? (Follow-up?)

**Comment by klonos** [comment]
@indigoxela that setting is added in settings.php in the same PR, specifically for the purpose of allowing Telemetry to be controlled that way.

**Comment by klonos** [comment]
...I see what you are saying now 🤔 

The way we allow people to turn Telemetry on/off is by enabling disabling the module (which cannot be controlled via config, so no config overrides in settings.php would work). It does make sense, as there are no other settings for the module, but in the shield contrib module for example, there is an on/off switch, which allows turning off the feature, while leaving the module turned on:

<img width=40% src="https://user-images.githubusercontent.com/2423362/148654134-9d817269-07b5-4cc7-a5b9-a4d5d0ff449b.png">

If we wanted to use config overrides in settings.php for Telemetry, then we'd have to do something similar.

**Comment by docwilmot** [comment]
> Did we miss to document that setting, or does that setting only exist for Tugboat? Means: it should stay "secret".

Yes I suppose we should actually document it properly in `settings.php`. 
> Should we use the same setting for GHA? (Follow-up?)

Perhaps? I though the `.tugboat` code controlled both the demo sites and GHA sandboxes? If not so then, alas, this solution is insufficient.

**Comment by indigoxela** [comment]
Hm, the more I think about the settings.php approach, the more I like it. It enables all demo / dev instances to bypass telemetry, regardless of where these get installed. For instance, a staging instance gets "silenced" while the live site still sends data. And no need for changes or evaluation on the telemetry server side.

@docwilmot the GHA install routine is [very similar](https://github.com/backdrop/backdrop/blob/73887c149afedcb6eea982c62d2f5ad817ce0fe8/.github/workflows/functional-tests.yml#L62) - no big deal to also disable telemetry for the test runners.

And probably we should document the purpose of this in settings.php. Other opinions?

**Comment by quicksketch** [comment]
> And probably we should document the purpose of this in settings.php. Other opinions?

I pushed a small commit to expand the code comment in the Tugboat local.settings.php.

This looks great!

>  I thought the .tugboat code controlled both the demo sites and GHA sandboxes? If not so then, alas, this solution is insufficient.

I think the `.tugboat` code is only used in PR sandboxes. Demo sandboxes use modified settings from https://github.com/backdrop-ops/tugboat-demos Now that this setting exists, we should update that settings file too.

**Comment by quicksketch** [comment]
>  Should we use the same setting for GHA? (Follow-up?)

Note that indeed this only solves _PR Sandboxes_, it doesn't yet solve the problem with GitHub Action tests reporting Telemetry data, which is probably the biggest contributor to misreporting, since 9 test instances are spun up every PR.
