### ISSUE TITLE
Don't call people "Users" in new token description text

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5459]
Follow up to https://github.com/backdrop/backdrop-issues/issues/5445

Strings replaced:
* `...This token is only available when the system sends an Account Cancellation email to a user.`
* `...This token is only available when the system sends a Password Recovery email to a user.`

These new strings should be as follows:

Strings replaced:
* `...This token is only available when an Account Cancellation email is sent.`
* `...This token is only available when a Password Recovery email is sent.`

---

##Translation update:

**This assumes the translation update for https://github.com/backdrop/backdrop-issues/issues/5445 was skipped.**

Strings replaced:
* `The URL of the confirm delete page for the user account.` becomes `The URL of the confirm delete page for the user account. This token is only available when an Account Cancellation email is sent`
* `The URL of the one-time login page for the user account.` becomes `The URL of the one-time login page for the user account. This token is only available when a Password Recovery email is sent.`

**Comment by jenlampton** [comment]
I've added the 1.21.1 milestone because it's important that this change get in before translations start being updated.

**Comment by klonos** [comment]
How could I miss that 🤦🏼  ...RTBC 👍🏼

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3908 into 1.x and 1.21.x. Thanks!
