### ISSUE TITLE
[UX] Separate descriptions for book navigation block settings.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5462]
## Description of the bug

The description text for the `Book navigation block display` block is all lumped together into a very long paragraph, instead of being separated into a description for each item. 
<img width="1223" alt="Screen Shot 2022-01-17 at 5 17 51 PM" src="https://user-images.githubusercontent.com/397895/149854249-30800a1a-13c9-40f9-b2f8-29888e6e33d5.png">

Current description text:
`If Show block on all pages is selected, the block will contain the automatically generated menus for all of the site's books. If Show block only on book pages is selected, the block will contain only the one menu corresponding to the current page's book. In this case, if the current page is not in a book, no block will be displayed. The Page specific visibility settings or other visibility settings can be used in addition to selectively display this block.`

Recommended solution:
**Show block on all pages**
`The block will contain the automatically generated menus for all of the site's books.`
** Show block only on book pages**
`The block will contain only the one menu corresponding to the current page's book. If the current page is not in a book, no block will be displayed.`

Overall description:
`Add additional visibility conditions to display this block more selectively.`

<img width="1333" alt="Screen Shot 2022-01-17 at 5 25 31 PM" src="https://user-images.githubusercontent.com/397895/149854921-cd425d04-38ac-40df-8607-f2071e597e2f.png">

## Steps To Reproduce

To reproduce the behavior:
1. Enable the book module
2. Place the `Book Navigation` block
3. Examine settings

## Actual behavior

Description text is confusing.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.x

**Comment by klonos** [comment]
Thanks for opening this issue and providing a PR @jenlampton 🙏🏼 

I never use the book module, so I've never noticed this horrific thing before 😅  ...I believe this is another manifestation of the fact that the ability to add separate help text to each radio/checkbox is not as well documented/known as it should.

This is RTBC from me, but "Add additional" sounds odd/superfluous to me. It could alternatively be something like:

> Additional visibility conditions can be used to further tweak when this block will be displayed or not.

**Comment by jenlampton** [comment]
> ...I believe this is another manifestation of the fact that the ability to add separate help text to each radio/checkbox is not as well documented/known as it should.

I was thinking the same thing. I wonder if we could improve this situation in 2.x...  

> but "Add additional" sounds odd/superfluous to me

I hadn't thought about that, but you're right! (as usual)

> Additional visibility conditions can be used to...

I prefer this language, but... I wonder if we really need to tell people "the thing you already know works here too". Doesn't that go without saying?

**Comment by jenlampton** [comment]
I've pushed an updated PR without any general description. I think it still works!

**Comment by klonos** [comment]
> I was thinking the same thing. I wonder if we could improve this situation in 2.x

I don't think that this really depends on core code - we should update our Field API documentation. The only thing that we can do in core is to actually put that feature in good use, like in this issue here and in #3122. That way there are more chances of people seeing these examples and copying them in the future.

> ... I wonder if we really need to tell people "the thing you already know works here too". Doesn't that go without saying?

No, you're absolutely right 👍🏼  ...no real value in having that there. It also applies to any other block.

I've left a comment in the PR re using double quotes and not escaping the apostrophe in the 2 help texts. Other than that, this is RTBC 👍🏼

**Comment by jenlampton** [comment]
I added a comment on the PR, but I don't like to use double quotes because it evaluates slower than single quotes. I could be convinced that readability is more important than speed, but in this case I don't believe that escaping apostrophes in text is really unreadable.

**Comment by klonos** [comment]
I appreciate the gentle push pack 🙂  ...but you know me and coding standards: https://www.drupal.org/docs/develop/standards/coding-standards#quotes

> 2. Translated strings where one can avoid escaping single quotes by enclosing the string in double quotes. One such string would be "He's a good person." It would be 'He\'s a good person.' with single quotes. Such escaping may not be handled properly by .pot file generators for text translation, and it's also somewhat awkward to read.

**Comment by jenlampton** [comment]
You win. PR merged! (and thank you)

**Comment by klonos** [comment]
> You win.

Noticing that this is becoming a pattern ...see https://github.com/backdrop/backdrop-issues/issues/2668#issuecomment-996679621

> PS: I'd never try to argue coding standard topics with you. :stuck_out_tongue_winking_eye: I've learned.

🤣  ...I'm sure that if @indigoxela is watching this thread, she's shaking her head.

![(HiFiGIF cc)_lotr-the-return-of-the-king-homeward-bound-full](https://user-images.githubusercontent.com/2423362/149936557-f26a030f-1be6-473c-937a-d5670c1fd785.jpeg)

I was previously self-proclaimed the Backdrop CMS "issue monster" and "PR monster" ...I'm afraid that I'm also now becoming the "coding standards monster" 😅

**Comment by bugfolder** [comment]
> I believe this is another manifestation of the fact that the ability to add separate help text to each radio/checkbox is not as well documented/known as it should.

It's now documented: https://docs.backdropcms.org/form_api#radios.

**Comment by klonos** [comment]
Thank you @bugfolder 🙏🏼  ...can you please do the same for https://docs.backdropcms.org/form_api#checkboxes? The same applies to that too.

**Comment by bugfolder** [comment]
Done: https://docs.backdropcms.org/form_api#checkboxes. I couldn't find an example in core code of actually doing this, so I've referred the user to the **radios** form element for an example. If you know of an example in core, let me know and I'll update the FAPI Element.

**Comment by argiepiano** [comment]
Thank you both! @bugfolder, the link to the radio example in this paragraph doesn't work:

> Note that you can provide #description text for each of the options individually, as illustrated in the second example for the [radios form element](https://docs.backdropcms.org/form_api/radios), which also supports this ability.

**Comment by bugfolder** [comment]
> the link to the radio example in this paragraph doesn't work:

It does for me. The full URL is https://docs.backdropcms.org/form_api/radios. What do you get when you click on it?

**Comment by argiepiano** [comment]
I get a page not found. The correct link is 

https://docs.backdropcms.org/form_api#radios

**Comment by bugfolder** [comment]
That's weird. Here's the page I linked to:

![radios](https://user-images.githubusercontent.com/29214084/152262942-5b4f0b67-a6d8-4208-a4dd-fd952de717a2.jpg)

Guessing that the node pages (which is what this is) are permission-limited. I'll change the link. Thanks for flagging it. (And now, back to our regularly scheduled issue topic.)

**Comment by argiepiano** [comment]
That may be an unpublished page?

**Comment by bugfolder** [comment]
Nope, it's published and has an automatic URL alias of **form_api/radios**. Just one of the puzzles of life, I guess.

**Comment by klonos** [comment]
Sounds like permissions-related.

**Comment by jenlampton** [comment]
> Sounds like permissions-related. 

Yes, @bugfolder the nodes that are intended to only be viewed as part of the Form API reference are pageless nodes, so cannot be viewed by non-admins.

**Comment by bugfolder** [comment]
No need to do that, now that I know (and presumably the other editors already knew that).

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/3909 into 1.x and 1.21.x. Thanks @jenlampton, @klonos, and @bugfolder!
