### ISSUE TITLE
Porting essential D7 modules

### ISSUE THREAD

**Issue by matoeilD** [backdrop/backdrop-issues#5463]
Hi there,
We have many sites in Drupal7 and we are evaluating the possibility of migrating to backdrop CMS before nov, EOL of drupal7.
Unfortunately, using the drupal backdrop_upgrade_status, we figured out that many essentials modules for us are not ported yet.
This include:
CAS
Multiblock
Read only mode
Shadowbox
Shibboleth auth

I wonder if anyone could provide us visiblity and informations on possible plans byt he backdrop community regarding these modules , and most particularely the CAS module

Best,

**Comment by indigoxela** [comment]
Hi @matoeilD,

welcome to the Backdrop community!

Re contrib module ports we have an extra [issue queue](https://github.com/backdrop-ops/contrib/issues) to collect and organize port requests.

Seems like neither CAS nor Shibboleth have been requested so far. But that doesn't necessarily mean, nobody else needs them. :wink:
A first step would be to open a "Port request" issue in that backdrop-ops/contrib queue. If that doesn't help, you might want to ask in our [Zulip chat](https://backdrop.zulipchat.com/).

Another option is to open a thread in our forum's [Help Wanted (Job Listings)](https://forum.backdropcms.org/forum/help-wanted-job-listings) section.

**Comment by matoeilD** [comment]
thanks for your reply
