### ISSUE TITLE
Fixed: Remove duplicate instances of cron_queue_test.module and cron_queue_test.info files.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5465]
## Description of the bug

There are two different versions of file cron_queue_test.module in Backdrop Core. Since only one of them can be loaded, the other is superfluous. They are at:

* core/modules/system/tests/cron_queue_test/cron_queue_test.module
* core/modules/system/tests/cron_queue_test.module

Similarly, there's

* core/modules/system/tests/cron_queue_test/cron_queue_test.info
* core/modules/system/tests/cron_queue_test.info

The second of each pair is what actually gets loaded.

## Steps To Reproduce

Examine the directory structure. Or check the PR sandbox for https://github.com/backdrop/backdrop/pull/3910.

## Appropriate fix

Delete the superfluous files (or rather, move the the two files from `tests` directory into `tests/cron_queue_test` directory and replace the two that are there).

**Comment by bugfolder** [comment]
Also, it looks like `system.tests.info` is not inside the `tests` folder, which is where it ought to be, so we can fix that at the same time.

**Comment by klonos** [comment]
Nice catch @bugfolder 

There was nothing to test per se, and since tests are still green this is RTBC from me 👍🏼

**Comment by quicksketch** [comment]
Great fix! Nice find @bugfolder. Merged https://github.com/backdrop/backdrop/pull/3911 into 1.x and 1.21.x.
