### ISSUE TITLE
Files directory htaccess does not match text in core/includes/file.inc 539-555

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#5466]
## Description of the bug

The .htaccess in the files folder in the code base of the latest release does not match the text in the code that would generate this file if it wasn't there.  This causes the [Security Review module](https://github.com/backdrop-contrib/security_review/) to issue a failed test as documented [here](https://github.com/backdrop-contrib/security_review/issues/1)

## Steps To Reproduce

To reproduce the behaviour:
1. Download backdrop and install
2. Either check the code directly in files/.htaccess and core/includes/file.inc 539-555 or install security review and after setting the permissions to 444/rrr run it and check the "PHP files in the Backdrop files directory can be executed." test

## Actual behaviour
files/.htaccess
```
# Turn off all options we don't need.
Options None
Options +SymLinksIfOwnerMatch

# Set the catch-all handler to prevent scripts from being executed.
SetHandler Drupal_Security_Do_Not_Remove_See_SA_2006_006
<Files *>
  # Override the handler again if we're run later in the evaluation list.
  SetHandler Drupal_Security_Do_Not_Remove_See_SA_2013_003
</Files>

# If we know how to do it safely, disable the PHP engine entirely.
<IfModule mod_php5.c>
  php_flag engine off
</IfModule>
```

core/includes/file.inc 539-555
```
# Turn off all options we don't need.
Options -Indexes -ExecCGI -Includes

# Set the catch-all handler to prevent scripts from being executed.
SetHandler Drupal_Security_Do_Not_Remove_See_SA_2006_006
<Files *>
  # Override the handler again if we're run later in the evaluation list.
  SetHandler Drupal_Security_Do_Not_Remove_See_SA_2013_003
</Files>

# If we know how to do it safely, disable the PHP engine entirely.
<IfModule mod_php5.c>
  php_flag engine off
</IfModule>
<IfModule mod_php7.c>
  php_flag engine off
</IfModule>
```

## Expected behavior
Default .htaccess should match what is in file.inc and if permissions are set correctly the test in security review should pass.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.21.0
- Web server and its version: n/a
- Operating System and its version: n/a
- Browser(s) and their versions: n/a

**Comment by indigoxela** [comment]
> `Options +SymLinksIfOwnerMatch`

If I recall correctly, this line caused problems. Maybe interesting: #1358

@yorkshire-pudding how old is that htaccess file? Seems like Backdrop doesn't do anything with SymLinksIfOwnerMatch anymore.

**Comment by yorkshire-pudding** [comment]
@indigoxela that was from the latest release (https://github.com/backdrop/backdrop/releases/latest/download/backdrop.zip)

I've added a pull request at https://github.com/backdrop/backdrop/pull/3913 - my first in core!

**Comment by klonos** [comment]
@backdrop/core-committers can one of you please approve @yorkshire-pudding's first PR, so that GHA tests can run? Thanks.

**Comment by quicksketch** [comment]
@yorkshire-pudding: I added you to the GitHub triage team too so now you can add labels to issues and PRs as well.

**Comment by BWPanda** [comment]
PR looks good to me. I initially wondered about whether the .htaccess code was the correct one, or the file.inc code. After some searching, it seems that our file.inc code was updated based on code merged in Drupal. Drupal only updated file.inc and not .htaccess because they don't have an .htaccess by default. So that's how we missed updating our .htaccess at the same time.

So I've reviewed the code and think it's good to go, but I can't mark as RTBC until it's been tested too, which I'll let someone else do.

**Comment by yorkshire-pudding** [comment]
Thanks @BWPanda

**Comment by klonos** [comment]
My only suggestion here is to add `If you update this file, then make sure to update ... accordingly` inline comments in both places, so that this mismatch doesn't happen again in the future.

**Comment by yorkshire-pudding** [comment]
> My only suggestion here is to add `If you update this file, then make sure to also update ... accordingly` inline comments in both places, so that this mismatch doesn't happen again in the future.

@klonos That's a good idea.  It would, however, need to be exactly the same comment in each file as the security_review module compares these lines exactly.  So it would need to be something like:
```
# This code block is replicated in /core/includes/file.inc>function file_htaccess_lines() and files/.htaccess. 
# If you update this file then make sure to also update the other location accordingly.
```
What do you think?

**Comment by klonos** [comment]
> What do you think?

Sounds good to me 👍🏼

**Comment by yorkshire-pudding** [comment]
@klonos I've added commits to cover that.  I presume at some point the commits can be squashed, but I don't think I can do that.
Thanks

**Comment by klonos** [comment]
> I presume at some point the commits can be squashed, but I don't think I can do that.

Yes, please feel free to make changes and commit/push as much as you need @yorkshire-pudding ...our @backdrop/core-committers always squash before merging 😉 🙏🏼

**Comment by klonos** [comment]
... @yorkshire-pudding our coding standards require lines that are longer than 80 characters long to be wrapped (see https://docs.backdropcms.org/php-standards#line-length). Can you please fix that in the PR?

While at it, perhaps improve this as well: `... replicated in /core/includes/file.inc>function file_htaccess_lines() ...` by saying `... replicated in the file_htaccess_lines() function in /core/includes/file.inc ...` instead.

**Comment by yorkshire-pudding** [comment]
I've been over this with fresh eyes and think its ready for testing.  Thanks @klonos for your input and suggestions

**Comment by klonos** [comment]
Thank you once again @yorkshire-pudding 🙏🏼  ...final tweaks please. I've left comments with code suggestions in the PR:
- there was a space at the end of a line
- there was a comma missing from if/then
- we should be separating the inline comments with a blank line

Once these are taken care of, this is RTBC from me.

**Comment by yorkshire-pudding** [comment]
Thanks @klonos - a great eye for detail.  I've tested in tugboat and the Security review "PHP files in the Backdrop files directory cannot be executed." test passes also.

**Comment by klonos** [comment]
> ...a great eye for detail.

Which most people in our community seem to have grown to both appreciate and be annoyed by at the same time 😅  ❤️ 

This is RTBC. Thank you so much for sticking with my feedback @yorkshire-pudding 🙏🏼

**Comment by BWPanda** [comment]
I'm not sure about the addition of the comment... I see the purpose of it, but I'm concerned it may confuse users who are reading and/or editing the `.htaccess` file on their site. The comment is solely for developers, yet it's likely to be seen by users too. Is there a better way we can ensure future updates are applied to both places, without resorting to adding developer-specific comments into files outside of the `/core` directory?

**Comment by yorkshire-pudding** [comment]
Hi @BWPanda - what about if it is just in the comments of the function so outside the .htaccess block of code?  That way it would only need to be in `/core/includes/file.inc` and not in `files/.htaccess` . Probably after line 525:
```
* Returns the standard .htaccess lines that Backdrop adds to file directories.
```

**Comment by BWPanda** [comment]
@yorkshire-pudding Not exactly ideal, since if someone ever changes `.htaccess` they're not going to be reminded to also change `file.inc`. But I don't see a way of doing that without putting a confusing comment in `.htaccess`...

So I'd say, yeah, better than nothing.

**Comment by yorkshire-pudding** [comment]
@BWPanda @klonos 
What do you think to the following?
```
* This .htaccess code block is replicated in files/.htaccess. If you update
* this code block then make sure you also update files/.htaccess also.
```

**Comment by yorkshire-pudding** [comment]
@BWPanda @klonos - as per above and in the absence of any negative feedback I've committed some changes that address Peter's feedback.  I've tested with Security Review again in tugboat.  Please can you review.

For ease of reference pull request is at https://github.com/backdrop/backdrop/pull/3913

**Comment by BWPanda** [comment]
@yorkshire-pudding Looks good to me. I made a small commit to remove some training spaces.

**Comment by yorkshire-pudding** [comment]
Thanks @BWPanda - I'll get better at hunting out these trailing spaces - I looked at the end of the lines with words but forgot about the blank lines.

**Comment by yorkshire-pudding** [comment]
@BWPanda - very odd. Now seems to be failing on 7.4 and 8.1

**Comment by klonos** [comment]
@yorkshire-pudding the failures seem unrelated to the changes. Can you please try restarting them? (close the PR - wait a couple of mins - reopen the PR)

**Comment by yorkshire-pudding** [comment]
Thanks @klonos they seem to have passed now.

**Comment by quicksketch** [comment]
Thanks @yorkshire-pudding for your persistence and patience here! Thanks @klonos, @BWPanda, and @indigoxela for your feedback and work getting this just right. I merged https://github.com/backdrop/backdrop/pull/3913 into 1.x and 1.21.x.

**Comment by klonos** [comment]
Congrats on your first core commit @yorkshire-pudding !! 🎉 ❤️
