### ISSUE TITLE
Fatal error on node save after disabling the comment module

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5470]
## Description of the bug

When the comment module is not enabled, it's not possible to add new nodes.

## Steps To Reproduce

1. Disable and uninstall the comment module
2. Try to add a new node immediately after that

## Actual behavior

```
EntityStorageException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comment_close_override' in 'field list' in NodeStorageController->save() (line 510 of ...core/modules/node/node.entity.inc). 
```
![entity-storage-exception](https://user-images.githubusercontent.com/842066/150643043-83565f30-1917-485a-9dfa-9558729035a1.png)

## Expected behavior

Guess :wink: 

## Additional information

- Backdrop CMS version: 1.21.1
- PHP: 7.4

**Comment by indigoxela** [comment]
Further digging: flushing the "page and else" cache fixes the problem. But which part of the cache is problematic?

@docwilmot pointed me to [this old issue](https://github.com/backdrop/backdrop-issues/issues/4904#issuecomment-766730374) in the chat.

The problem in this case here (adding a node immediately after uninstalling the comment module) is again the cache, but not the entity_info cache (which gets flushed), but the schema:runtime cache. Need to verify.

**Comment by indigoxela** [comment]
I'm still struggling with details... :wink: 

In manual testing only adding `cache('cache')->deletePrefix('schema:runtime');` does the trick, but in the functional test only flushing that prefix doesn't seem to be enough. Need to dig a bit more, that's why the PR still needs work.

**Comment by klonos** [comment]
> ## Expected behavior
> 
> Guess :wink: 

😅 

Thank you @indigoxela for finding the bug and filing a PR for it. I've left a couple of comments in the PR, but more out of curiosity - not objections re direction/method used.

Sorry I can't help with figuring out which is the proper cache to chose and how to clear it properly/effectively. Perhaps @hosef can help here?

**Comment by indigoxela** [comment]
> I've left a couple of comments in the PR...

Sure, you got answers. :wink: 

Test problem solved. It seems like the functional test also needs the static _node_types_build cache to be reset, which is not necessary when doing manual testing. It does no harm, so I've added it in comment_uninstall().

BTW this PR does not replace the previous fix in the entity module, both are necessary. The test added in this PR also covers the problem we fixed in #4904. We "forgot" to add a test there, now we have one.

(And a random test failure, will restart tests.)

**Comment by indigoxela** [comment]
**How to test:**

In a standard install (comment module enabled, posts have comments turned on), disable and uninstall the comment module. Right after that (without manual cache flush) go to /node/add/post and try to save a *new* post.

**Comment by klonos** [comment]
Thanks @indigoxela 👍🏼  ...RTBC.

A minor note for consideration: are we sure that the `SQLSTATE` error codes and the respective error message/text remain the same? If not, then we could be just checking for `SQLSTATE` in `assertNoText()`. Not sure - just putting that out there.

**Comment by indigoxela** [comment]
> A minor note for consideration: are we sure that the SQLSTATE error codes and the respective error message/text remain the same?

I suppose so, SQLSTATE codes are predefined, correct me if I'm wrong. If there's another exception one day - whatever it may be - we'd need to handle that differently, anyway, exceptions always show up in Simpletest.

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/pull/3915. This fix seemed targeted and includes test coverage. No problems that I could see by reading it. Thanks @indigoxela and @klonos!
