### ISSUE TITLE
Should the language code of taxonomy vocabularies be stored as `langcode` instead of `language`? 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5471]
Currently the language code for taxonomy vocabularies is stored under the key `language` in the vocabulary json config file, and is instantiated as the property `$language` in class `TaxonomyVocabulary`. 

Backdrop switched to using the property `langcode` for all core entities, and the language code is stored in the column `langcode` in the DB. Shouldn't vocabularies also follow suit?

**Comment by indigoxela** [comment]
> Currently the language code for taxonomy vocabularies is stored under the key language in the vocabulary json config file

Not actually, this "language" key holds the setting, if "Multilingual support" is enabled for this vocab. Vocabularies have no langcode, but terms have.

**Comment by argiepiano** [comment]
Thanks for the explanation! Closing this question...

**Comment by klonos** [comment]
Should we reopen this and switch that config variable to `multilingual` instead, so to avoid any other people being confused in the future?

**Comment by indigoxela** [comment]
> Should we reopen this and switch that config variable to multilingual instead

I'd totally prefer that variable name and config key, but that would be a 2.x task. Too many things out there (including i18n) rely on current naming. Same for multilingual nodes, BTW.
