### ISSUE TITLE
Fix menu_update_1006() on pgsql (Upstreaming Silkscreen patch)

### ISSUE THREAD

**Issue by jlfranklin** [backdrop/backdrop-issues#5472]
## Description of the bug

The SELECT query in menu_update_1006() triggers the following error when testing with Silkscreen and PostgreSQL:

```
    Failed: PDOException: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "simpletest792595menu_links.menu_name" must
    appear in the GROUP BY clause or be used in an aggregate function
    LINE 1: SELECT MIN(mlid) as min_mlid, link_path, menu_name, plid, de...
                                                     ^: SELECT MIN(mlid) as min_mlid, link_path, menu_name, plid, depth
    FROM {menu_links} WHERE module = 'system' GROUP BY link_path HAVING count(link_path) > 1; Array
    (
    )
     in menu_update_1006() (line 148 of /home/vmadmin/silkscreen/docroot/core/modules/menu/menu.install).

```

This is because PostgreSQL expects all of the selected fields to be included in the GROUP BY clause.

## Steps To Reproduce

To reproduce the behavior:
1. Create a database with PostgreSQL with a schema similar to menu_links
2. Insert a pair of duplicates
3. Execute the following SQL command in psql: 

```
silktest=# select MIN(mlid) as min_mlid, link_path, menu_name, plid, depth from menu_links WHERE module = 'system' group by link_path HAVING count(link_path) > 1;
ERROR:  column "menu_links.menu_name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select MIN(mlid) as min_mlid, link_path, menu_name, plid, de...
```

## Actual behavior

See above.

## Expected behavior

Should list the oldest menu_link.

```
silktest=# select MIN(mlid) as min_mlid, link_path, menu_name, plid, depth from menu_links WHERE module = 'system' group by link_path,menu_name,plid,depth HAVING count(link_path) > 1;
 min_mlid |   link_path   | menu_name | plid | depth 
----------+---------------+-----------+------+-------
      333 | /path/to/link | main      |    1 |     1
(1 row)
```

## Additional information

Add any other information that could help, such as:
- Silkscreen 1.21.1
- Apache 2.4.25
- Debian Buster
- PostgreSQL 9.6.19

**Comment by jlfranklin** [comment]
The fix to this is trivial: add the other fields to the `GROUP BY` clause.

**Comment by indigoxela** [comment]
Garbage, I did check if postgres uses the same syntax for "having" (with Silkscreen in mind) and thought it would work, but wasn't actually able to test. I wasn't aware of the difference in "group by".

**Comment by jlfranklin** [comment]
I wasn't aware of the differences, either.  Not until I ran the tests.

**Comment by quicksketch** [comment]
Looks good and the SQL output is still identical. I've merged https://github.com/backdrop/backdrop/pull/3917 into 1.x and 1.21.x. Thanks @jlfranklin and @indigoxela!
