### ISSUE TITLE
Fixed: The layout context system is called way too many times.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5483]
## Description of the bug

On a vanilla Backdrop, a debug/dpm in `Layout::getContexts()` shows that function is called 14-16 times with each page load. The function is not cached. 

Every block added to the layout increases this by 2-3 times.

Furthermore the function `Layout::getContextFromRelationship()` is called 14-16 times for each relationship added to the layout. 

## Steps To Reproduce

Just add your favorite debug call (`dpm('whatever')` for example) to `Layout::getContexts()` and visit any page.
Or worse, create a layout with path `node/%`, then add a relationship to the layout, then add this dpm to `Layout::getContextFromRelationship()` instead. Add it twice. (This is probably also a bug that you can add it twice). I'm seeing a minimum of 30 calls per page load with two relationships (45 calls with 3 relationships, etc)

## Actual behavior

OOTB a node layout results in too many calls, especially to `Layout::getContextFromRelationship()`

## Expected behavior

This should either be refined, or if unavoidable, we should try and cache this.

## Additional information

1.22.0

**Comment by docwilmot** [comment]
Static cache reduces calls to one per page load. Tests pass, except one bogus fail. Ready to review.

**Comment by indigoxela** [comment]
> Static cache reduces calls to one per page load.

:tada: Cool! @docwilmot I've left a question and a coding standard recommendation.
I might come with more questions, when I find the time. (Another good opportunity to learn more about the Layout system internals. :wink: )

**Comment by docwilmot** [comment]
This is a simple one that could use another review.

**Comment by indigoxela** [comment]
I'm impressed. This is how I tested:

On a vanilla Backdrop I added `debug('runs')` in both, Layout::getContexts() and Layout::getContextFromRelationship(). Then created a layout with path 'node/%' and a relationship for the author (and a visibility condition).

On the layout form there have already been several "runs". Same on any node page. But also on a custom layout without any relationship there were several "runs".

Then applied the changes and - calls are reduces to one of each method, twice when (manually flushing caches). Same on the "Configure blocks" form, one additional on "Configure layout", but still no comparison to current behavior.

Works for me! :+1: 

> This is a simple one that...

@docwilmot it might be that what you call simple isn't as simple for us "average Backdropers". :wink:

**Comment by docwilmot** [comment]
Milestone though?

**Comment by bugfolder** [comment]
Code reviewed, looks good.

**Comment by quicksketch** [comment]
This is a great optimization! Nice and simple approach to keeping the existing code intact too, which makes an easy review job. The need to return different contexts based on what is required by each block prevented the initial implementation from providing such caching. This approach solves the problem by retrieving all contexts once while applying filtering on a per-request basis. Looks great!

**Comment by quicksketch** [comment]
Nice job @docwilmot! Thanks @indigoxela, @argiepiano, and @bugfolder for the reviewing and feedback. I've merged https://github.com/backdrop/backdrop/pull/3934 into 1.x and 1.21.x.
