### ISSUE TITLE
Move the 'Clear log messages' button to the bottom of the page

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5484]
This is a follow-on from https://github.com/backdrop/backdrop-issues/issues/2353. There, after much discussion, it was finally decided that the 'Clear log messages' button at the top of the 'Recent log messages' (DBLog) page will be moved to the bottom of the page instead.

The reasons for this will not be repeated here (see the other issue for all the details about that). This issue will focus on getting a PR ready to test and implement this change.

**Comment by klonos** [comment]
Since #2353 has been closed, what about these things that were suggested/discussed there?:
- confirmation dialog or not?
- fieldset or not?
- if the fieldset is kept, then expanded or collapsed by default?

**Comment by BWPanda** [comment]
> confirmation dialog or not?

I'd suggest for this issue we just *move* the button, then leave any changes to *how* the button works as a follow-up.

> fieldset or not?
> if the fieldset is kept, then expanded or collapsed by default?

The previous issue seemed to indicate that the PMC preferred option 2, which was no fieldset. But I take this to mean we don't want the button hidden away in a *collapsed* fieldset (we still want to add a title and description for the button, so I think a fieldset is still needed). So I'd say it should be in an expanded, non-collapsible fieldset.

**Comment by docwilmot** [comment]
Bikeshedding away: the point of the fieldset was to make the button less prominent, since it was at the top. The point of all the discussion was this is not a feature anywhere else. Lets not add a new non-feature. I believe the thinking for the solution here was: button at the bottom, out of the way, so no fieldset needed.

**Comment by klonos** [comment]
What @docwilmot said ^^ ...that's why I asked the questions basically.

**Comment by BWPanda** [comment]
Sure, we'll go with that then 👍🏻

**Comment by BWPanda** [comment]
Here's an initial PR: https://github.com/backdrop/backdrop/pull/3933

![image](https://user-images.githubusercontent.com/2385329/151949951-0b025cf1-dfc4-41aa-967e-b218c4dd0545.png)

Questions:
1. Is it ok to use `#prefix` for the description text, since submit buttons don't have a `#description` option?
2. Does this look ok as-is, or do we want to make any visual changes (e.g. right-align, horizontal bar above description, etc.)?
3. Should the submit button element stay as `$form['dblog_clear']['clear']` for backwards-compatibility, or should it just be `$form['dblog_clear']` now?

**Comment by BWPanda** [comment]
And just to compare, here's what it'd look like if we kept the fieldset but made it non-collapsible and removed the title (since it just duplicates the button text):

![image](https://user-images.githubusercontent.com/2385329/151950793-b9ebefa3-6c28-4fb2-a567-5e1367db9ec9.png)

**Comment by klonos** [comment]
@BWPanda not sure about the rest of the things you are asking, but I think that we shoul:
- be using `'#type' => 'help',` for the text.
- leave the `$form['dblog_clear']['clear']` for the button, and add the help text as `$form['dblog_clear']['help']`. This will keep both elements grouped inside the same `<div>`

**Comment by olafgrabienski** [comment]
Thanks for the PR, @BWPanda!

> Does this look ok as-is, or do we want to make any visual changes (e.g. right-align, horizontal bar above description, etc.)?

A visual distinction between the messages table and the clear messages element would be nice. That's why I like the non-collapsible fieldset. But some margin between the elements, e.g. 2rem, would help for distinction as well. Actually, I like fieldset *and* margin, but also fine without fieldset.

**Comment by BWPanda** [comment]
Thanks guys. That 'help' element seems like much better markup @klonos 👍🏻 

Here's just the form API change:
![image](https://user-images.githubusercontent.com/2385329/153391314-3d9adea8-7550-404a-8909-e3b545142091.png)

And here's it with some top margin:
![image](https://user-images.githubusercontent.com/2385329/153392457-fad28009-0844-49ae-8b00-805224784b8e.png)

And here's the fieldset with top margin:
![image](https://user-images.githubusercontent.com/2385329/153392757-bf8e44ef-6453-431d-a1ff-c51a86aaf7ce.png)

I've updated the PR to be the 2nd screenshot (no fieldset, added top margin).

**Comment by olafgrabienski** [comment]
> I've updated the PR to be the 2nd screenshot (no fieldset, added top margin).

Nice! Tested in the sandbox, works for me.

**Comment by klonos** [comment]
Code looks good too 👍🏼
