### ISSUE TITLE
Fixed typo in `user_cancel_user_action`.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5487]
## Description of the bug

I was looking at the user delete action to see how it worked and I think I found a typo where `nid` was used instead of `uid`. PR coming.

**Comment by klonos** [comment]
Good catch @laryn 👍🏼  ...seems to have been a copy/paste oversight from `node_delete_action()`.

**Comment by klonos** [comment]
@laryn noting that there was no PR sandbox created (assuming because the PR comes from a local branch as opposed to one from your own fork of the repo).

Code looks good 👍🏼  ...if I was to test this though, how would I go about doing it?

**Comment by laryn** [comment]
Reopened the PR against Backdrop core instead of against my own fork. :man_facepalming: 

As far as testing, I guess maybe begin to queue some user account cancellations and then wait more than 60s and add some more? See if the first ones get removed from the list.

**Comment by klonos** [comment]
Yeah, that's why I'm asking: I don't know how to queue accounts for cancelation 🤷🏼  ...when I bulk-select accounts to cancel, I get a confirmation message, and when I confirm the accounts are being deleted instantly.

**Comment by laryn** [comment]
@klonos I think don't confirm it in the first step. Go back to the user accounts page and select different accounts -- see if the first accounts selected are still there.

**Comment by klonos** [comment]
Yes, it does work 👍🏼   (never done that before, but there is a first time for everything 🙂 )

**Comment by quicksketch** [comment]
Thanks @laryn and @klonos! Merged https://github.com/backdrop/backdrop/pull/3939 into 1.x and 1.21.x.
