### ISSUE TITLE
Fix messy indentation in node.actions.inc

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5488]
Discovered this while checking out #5487.

PR coming up shortly...

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/3938

@laryn quid pro quo? 🙂

**Comment by klonos** [comment]
...nothing to test, as there have been no code changes - just indentation, blank lines and a double period removed from a docblock.

**Comment by laryn** [comment]
Code cleanup looks good. :+1:

**Comment by klonos** [comment]
That was very prompt @laryn ...thanks again 🙏🏼

**Comment by quicksketch** [comment]
Looks great! Merged https://github.com/backdrop/backdrop/pull/3938 into 1.x and 1.21.x.
