### ISSUE TITLE
Why is File::access so odd?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5493]
This currently looks like so:

```php
  public function access($op, $account = NULL) {
    if ($op == 'create') {
      return self::createAccess(NULL, $account);
    }
    elseif (!in_array($op, array('update', 'delete'), TRUE)) {
      // If the $op was not one of the supported ones, we return access denied.
      return FALSE;
    }

    // If no user object is supplied, the access check is for the current user.
    if (empty($account)) {
      $account = $GLOBALS['user'];
    }

    if ($op == 'update') {
      return user_access('manage files', $account);
    }
    elseif ($op == 'delete') {
      return user_access('delete files', $account);
    }

    return FALSE;
  }
```

Was wondering why we're not doing this instead?:

```php
  public function access($op, $account = NULL) {
    // If no user object is supplied, the access check is for the current user.
    if (empty($account)) {
      $account = $GLOBALS['user'];
    }

    switch (condition) {
      case 'create':
        return self::createAccess(NULL, $account);
      case 'update':
        return user_access('manage files', $account);
      case 'delete':
        return user_access('delete files', $account);
      default:
        // If the $op was not one of the supported ones, we return access denied.
        return FALSE;
    }
  }
```

**Comment by klonos** [comment]
Pinging @indigoxela and @argiepiano since both of you have recently been looking into Entity access-related things.

**Comment by klonos** [comment]
...I was also thinking that if the check for `$account` already happens in `File::createAccess()` and `user_access()`, then is it really needed at all here?

**Comment by indigoxela** [comment]
> Was wondering why we're not doing this instead?:

@klonos Agreed, File::access deserves some loving care, but it's not only the structure, it's also the incompleteness. Several permissions (view own private, edit own, edit any...) simply aren't considered at all, see also #5480.

So, in fact, the function shouldn't get simplified, but "complicated" :wink:

**Comment by klonos** [comment]
> ...see also https://github.com/backdrop/backdrop-issues/issues/5480. ... So, in fact, the function shouldn't get simplified, but "complicated" 😉

👀

**Comment by klonos** [comment]
Thanks @indigoxela ...closing this in favor of #5480 then.
