### ISSUE TITLE
Fixed: The "langcode" column in the node table should not be emptied when upgrading from Drupal 7

### ISSUE THREAD

**Issue by djzwerg** [backdrop/backdrop-issues#5498]
## Description of the bug

A short description of what the problem is.
While ugrading from Drupal 7 the column `language` will be renamed to `langcode` but the values are gone. So this column is empty in my case (using German language).

## Steps To Reproduce

To reproduce the behavior:
1. Use a website with German language (maybe all languages instead of English?)
2. Upgrade your website to Backdrop CMS
3. Check you `node` table

## Actual behavior

Loading a node produces the notices
`Notice: Trying to get property 'direction' of non-object in locale_preprocess_node() line 1044 of locale.module`

`Notice: Trying to get property 'langcode' of non-object in locale_preprocess_node() (line 1039 of locale.module`

## Expected behavior

Before upgrade:
![grafik](https://user-images.githubusercontent.com/49948628/153458390-5df6a985-e141-469c-84c4-302c3df2b1b1.png)

After upgrade:
![grafik](https://user-images.githubusercontent.com/49948628/153458509-4bc8872e-90b2-45b7-80e1-0e7c9246b1f2.png)

## Additional information

Add any other information that could help, such as:
- Drupal CMS version: 7.87
- Backdrop CMS version: 1.21.1
- Web server and its version: Apache
- MySQL version: 8.0.25
- PHP version: 7.4.27

**Comment by olafgrabienski** [comment]
Hm, I've recently upgraded a German-English site from Drupal 7 to Backdrop and just checked the node table: `language` has been renamed to `langcode`, and the values are still there.

Differences: The upgrade was 3 months ago, so Drupal and Backdrop versions were a bit older, and I don't use MySQL 8.

**Comment by indigoxela** [comment]
@djzwerg Is English is disabled in your D7? So German is the only enabled language?

Two update hooks are involved:

- node_update_1002() - which renames the column without touching any contents
- node_update_1010() - which changes all values to "und" (LANGUAGE_NONE) on monolingual sites

Can you also check the langcode column in your url_alias table?

... Wait a minute, these two db_query() in node_update_1010() look suspicious. The placeholder is "default" instead of ":default" - note the missing colon. And they should have been db_update, anyway.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/3952) is available for testing and review.

To test, you actually need to run a D7 upgrade, and the D7 site must be set up monolingual like that:

- In D7 enable the locale module, _add another language and then disable English_
- Add some content
- After that try to upgrade to Backdrop

Then make sure that the columns "langcode" in the "node" and "path_alias" tables have been updated properly to contain "und". And no php notices from locale, of course.

**Comment by djzwerg** [comment]
Thanks for your work @indigoxela! I'm sorry but this does not solve my issue.

**Comment by klonos** [comment]
Although I agree with the need to fix this bug, and that the solution here is accurate/proper, I'd like to get some answers here please: #5502

Thanks in advance.
