### ISSUE TITLE
NULL layout paths (e.g., Default layout) cause problems in PHP 8.1

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5501]
## Description of the bug

In PHP 8.1, if we pass a NULL path to various `path.inc` functions like `path_is_admin($path)` (and any function that ends up at `backdrop_match_path($path, $patterns)`, in PHP 8.1, any automated test that does this will fail with this error:

```
Exception Deprecated path.inc          315                                                                             
    preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
```

This showed up when working on PR https://github.com/backdrop/backdrop/pull/3955, and that contains a workaround. But there's a fundamental issue in core, which ultimately stems from the fact that for the default layout, `getPath()` will return NULL, rather than, say, an empty string.

## Steps To Reproduce

I've added a test in the PR for this issue that creates the problem. It contains the following:

```
    $layouts = layout_load_multiple_by_path('');
    $default_layout = $layouts['default'];
    $path = $default_layout->getPath(); // this will be NULL
    $this->assertTrue(is_null($path), 'Default layout path is NULL.');

    backdrop_static_reset('path_is_admin');
    $result = path_is_admin($path); // This should throw a deprecation warning in PHP 8.1
    $this->assertFalse($result, 'Default layout is not an admin path.');

    backdrop_match_path($path, "foo\nbar"); // This should throw a deprecation warning in PHP 8.1
```

## Actual behavior

The test will pass in PHP 5.3 and 7.4, but fails in PHP 8.1. 

## Expected behavior

Pass in all versions of PHP.

## Solution(s)

I could imagine two possible mitigations:

* Modify the default layout so that its path is an empty string, rather than NULL. (Not sure what other effects that might have.)
* Modify various functions in `path.inc` to gracefully handle NULL variables passed for the `$path` variable.

I solicit further input and thoughts on the best approach.

**Comment by bugfolder** [comment]
Here's the PR: https://github.com/backdrop/backdrop/pull/3958

**Comment by quicksketch** [comment]
Thanks @bugfolder for the demonstration and tracking this down!

> Modify various functions in path.inc to gracefully handle NULL variables passed for the $path variable.

I filed a PR at https://github.com/backdrop/backdrop/pull/4050 that takes this approach by casting `$path` to a string before running it through `preg_match()`. All Backdrop functions don't have a problem taking `NULL` or a string, it's only the PHP built-in functions that have this new strict checking on strings.

My PR just casts to a string. We could be more specific though and do something like this:

```
  return (bool) preg_match($regexps[$patterns], is_null($path) ? '' : $path);
```

Which would _only_ handle `NULL` and still cause errors on other non-string types.

**Comment by bugfolder** [comment]
Closed https://github.com/backdrop/backdrop/pull/3958 in favor of https://github.com/backdrop/backdrop/pull/4050. Looks good to me, but someone else needs to do the review.

**Comment by indigoxela** [comment]
> ... someone else needs to do the review.

I tried, but am confused by the functional test (which needs work, anyway because of coding standards).

Casting NULL to a string before using it with preg_match() obviously works.

**Comment by bugfolder** [comment]
So, in https://github.com/backdrop/backdrop/pull/3958, I added tests that displayed the problem (deprecation warnings in PHP 8.1) and added some comments about why those tests were there as an explanation of the problem and a way to detect it. @quicksketch created https://github.com/backdrop/backdrop/pull/4050 with a fix and left the tests as they were (non-coding-standard compliant, as @indigoxela noted). 

I've re-opened https://github.com/backdrop/backdrop/pull/3958, incorporated the fix from https://github.com/backdrop/backdrop/pull/4050, and cleaned up the test code (since it no longer throws the deprecation warning, I've removed those comments). To avoid confusion over 2 PRs, I'll close 4050, since 3958 incorporates everything (I think). Ready for review again.

**Comment by indigoxela** [comment]
@bugfolder many thanks for clarifying. Some more nitpicks on your PR, though. :wink:

**Comment by bugfolder** [comment]
Thanks for nit-picks (mostly unpicked now). I had two questions on @indigoxela's comments, left in the PR.

**Comment by indigoxela** [comment]
> Thanks for nit-picks...

Thank YOU for your patience with our "nagging". :+1: I tried to answer your questions, let me know, if it's sufficient.

**Comment by bugfolder** [comment]
All clear, PR updated; hopefully nit-free now!

**Comment by indigoxela** [comment]
For me it's nit-free now. Who would have thought, that a small change like that (a single cast to string) would cause so much discussion. :smile:

**Comment by bugfolder** [comment]
If nit-free, OK to remove "pr - needs code review" label & add "pr - ready to be committed"?

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/3958 looks great. I merged into 1.x and 1.22.x. Thanks @bugfolder, @indigoxela, and @argiepiano!
