### ISSUE TITLE
Eight core modules are never enabled during D7 migration

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5506]
## Description of the bug

While working on #5499 I discovered that there are 8 core "Backdrop-only" modules that are never enabled during migration of a D7 site. All of these are actually declared as dependencies of `standard.module`, yet they are never enabled.

- ckeditor 
- date 
- telemetry
- email
- installer
- link
- redirect
- views_ui

(These modules did not exist in core in D7). 

Normally all these modules are enabled in a standard installation of Backdrop, since they are declared as dependencies of standard.module in Backdrop. To me, this looks like a bug.  `installer` seems like the most serious case - without it enabled you can't install new modules.  Also ckeditor - the inclusion of this module "out of the box" in a standard install makes  Backdrop so much more user friendly than D7.

## Steps To Reproduce

1. Create a barebones D7 site with only core modules enabled
2. Migrate it to Backdrop
3. Go to Functionality -> Modules and look for the modules above.

## Actual behavior

Those modules are disabled.

## Expected behavior
I believe those modules should be enabled, as they are in a standard install of Backdrop, and also because they are declared as dependencies.

## Additional information
The PR I'm creating for #5499 would enable those 8 modules automatically during the migration process (the PR is not ready yet). I'd like to know if this is the desired behavior. 

I'll appreciate any feedback.

**Comment by klonos** [comment]
The question is: should we be enabling all these modules regardless of the installation profile that was used in D7? ...is it safe to assume that the Standard installation profile should always be used for upgrades? What if the D7 site was built using the minimal profile?

**Comment by argiepiano** [comment]
Those are all good questions, @klonos. To answer some of those: these 8 modules did not exist in any core installation of D7 (neither minimal, nor standard, etc).

**Comment by klonos** [comment]
...perhaps a middle ground would be a confirmation page, where we list all these modules, along with checkboxes next to them, and allow the user to select which ones they'd like enabled.

The confirmation message could be saying something like "Hey, Backdrop now includes certain modules/features out of the box. We are about to enable them, but would like to give you a chance to have a say."

Alternatively, all that could happen in a post-installation message.

**Comment by argiepiano** [comment]
I hear you. The checkboxes sound like a good alternative, although I must say this may be difficult to accomplish during the update.php script running, as this is not a "normal" Backdrop environment.  

Then there is also the fact that all 8 are required modules in the standard installation of Backdrop (they are all dependencies).  Not enabling them upon installation of a standard profile (whether it's a migration or a clean install) seems like a bug to me.

**Comment by klonos** [comment]
> ... Not enabling them upon installation of a standard profile (whether it's a migration or a clean install) seems like a bug to me.

Yeah, I'll give you that 🤔

**Comment by klonos** [comment]
...wondering if we could take advantage of [`hook_modules_installed()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_modules_installed/1)? Like detect which modules have been installed vs those that haven't, and then act accordingly 🤔

**Comment by argiepiano** [comment]
I need feedback, please. 

I did some further checking regarding these 8 disabled core modules when migrating a Standard D7 install. Although these modules are marked as dependencies in Backdrop's `standard.info`, you can still manually disable them in a normal Backdrop standard install without any disastrous results.

So, I'm wondering if leaving those 8 disabled after migrating a barebones D7 standard site was actually intended? 

I'd like feedback, please. This will help us decide how to proceed in #5499 - whether to automatically enable these 8, or to leave them disabled.   One of the focus of recent Zulip outreach conversations is how to attract more D7 users to migrate this year before D7 EOL. I feel that fixing issues like this with migration is a really important task right now.

**Comment by indigoxela** [comment]
> So, I'm wondering if leaving those 8 disabled after migrating a barebones D7 standard site was actually intended?

I suspect, that's the case. Think of CKEditor - if it wasn't enabled on a D7 site, it was probably by intention. In this case enabling it on upgrade doesn't make much sense. If on the other hand the wysiwyg module was in use (with ckeditor library), then enabling could make sense.

Another example: the installer. I don't see a real reason to not enable it. Date, link, email? Maybe not. Redirect? Not sure. Telemetry? Hm, isn't that only supposed to get enabled on new installs?

It seems a bit tricky, to decide based on assumptions, so I can't provide much here.

> D7 EOL. I feel that fixing issues like this with migration is really an important task right now.

Yes, exactly.

**Comment by BWPanda** [comment]
> https://github.com/backdrop/backdrop-issues/issues/5499 was merged and we ended up not enabling the modules listed here as that created issues in some cases.

Closing then.
