### ISSUE TITLE
[UX] "Find content" /  "Admin content" should be "Manage content"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#551]
The page/view allows actions to be made on listed content, so "manage" is a more fitting word there. We need to update the view label and the page title (currently "Admin Content") as well as the menu link and the tab (currently "Find content").

**Comment by jenlampton** [comment]
The reason we used the word "Find" is because when you create a piece of content and forget to add it into the menu, it's instantly lost.  Find in the menu gives people a clue where they can go to get it back.  I agree manage is more accurate, but do you think it also solves this problem?

**Comment by klonos** [comment]
> ...but do you think it also solves this problem? 

Honestly, I am not the right person to answer this because I am already familiar with the way Drupal/Backdrop works. A usability study would reveal more on that matter.

No matter what we choose to go with here, the "Admin Content" view label is a total fail and it is a good practice to be consistent with the view label, the menu link and the page title.

**Comment by klonos** [comment]
...on second thought, I believe that we should go with "manage". If people are trying to find content that was accidentally not added to a menu, then I guess the best thing to do for them is to put the already enabled by default search.module to good use and expose a site searchbox.

Currently, we already have the "Menu search" searchbox on the admin bar, so I don't know if adding another one there would be a good idea. My guess is that it would kinda make the UI overwhelming. Could we make this a hybrid searchbox that also listed matching users and/or content (I realize that they are totally different implementations - that's why I said "hybrid")? Not sure either.

Anyways, point is that users that want to actually manage their content will be looking for the word "manage" (they did install a Content **Management** System after all) under the "Content" menu. How do we solve their issue?

**Comment by klonos** [comment]
...aaand, mentioning the use case of the lost content, I would like to take the chance to shamelessly promote #434

**Comment by jenlampton** [comment]
I'm fine with manage, its so much better than what we have now :)

**Comment by Dinornis** [comment]
I believe this issue can now be closed as the suggestion has been already implemented.

**Comment by jenlampton** [comment]
yes, thank you :)

**Comment by klonos** [comment]
I'm telling you, I see a little bit of me back when I was starting with helping triage the d.org queues in @Dinornis 👍 Honestly thank you man. Each time we do our little bit, we are sparing core devs the time to do it and they in turn can focus on spending it on making Backdrop more awesomer! 😄 Good on ya.
