### ISSUE TITLE
Add more explanation and options to layout deletion confirmation form

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5511]
This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/5077, collecting some suggestions made in that issue about the confirmation page for the "Delete Layout" action (function `layout_delete_form()` and its processing). Suggestions from that issue:

* If the layout creates a page AND it's the last layout with that path, on the confirm form, add "Warning: the page at path mypage will no longer exist" or such. (H/T @docwilmot.) 
* Provide another button in the confirmation form, that disables the layout instead of deleting it. (H/T @klonos.) 
* Add more explanation to the warning message, something like this: `Deleting this layout will permanently delete the page at /%path. This action cannot be undone. If you are unsure, then consider disabling the layout instead of deleting it.` (H/T @klonos.) 
* Consider making the "destructive" bit of the text a warning message. (H/T @klonos.) 
* Check whether the page being deleted was selected on `admin/config/system/site-information` as the home page or either error page and either warn user or prevent its deletion (which?).

---

I've updated the PR and its behavior, which is now:

- Added a disable option to the "Delete layout?" confirmation page.
- If deleting (or disabling) a layout would remove a page that is used on the site info page, a warning is issued on the "Delete layout?" confirmation page, and after confirming deletion or disabling, a warning message is put up directing the user to the site info page to make the appropriate change.
- If the user disables a layout directly (using the dropbutton link, so there's no confirmation page), if that action removes a page that is used on the site info page, a warning message is put up directing the user to the site info page to make the appropriate change.

**Comment by bugfolder** [comment]
Thinking about the last bullet: what should happen if the user attempts to delete a page-creating layout whose path has been used for the home, 404, or 403 pages. on `admin/config/system/site-information`.

My thought is that we should put up a warning message on the deletion form informing them of the issue and linking to `admin/config/system/site-information` and disable the submit button; basically "you must change the site information before we'll allow you to delete this layout."

I note that we can't fully protect the user from self-foot-shooting, because of visibility conditions. We could have two layouts, `404_anon` and `404_auth` for path `404` that are used for the 404 page with the corresponding visibility conditions for anonymous and authenticated users, and then the user deleted `404_anon`. There'd be no warning (because it's not the last layout at path `404`), but if an anonymous user subsequently visited a nonexistent page, since the visibility conditions for `404_auth` aren't satisfied, they'd get a "hard 404" error (blank page with 404).

**Comment by bugfolder** [comment]
> Consider making the "destructive" bit of the text a warning message.

I did a search for "Are you sure" throughout core to see if these types of questions are presented as warning messages or as the `$question` argument in `confirm_form()`. I find it to be the latter case in (partial listing):

* `field_ui.admin.inc`
* `file_admin.inc`
* `file_pages.inc`
* `filter_admin.inc`
* `image.admin.inc`
* `language.admin.inc`
* `locale.pages.inc`
* `menu.admin.inc`
* `node.admin.inc`
* `node.pages.inc`
* `node.types.inc`
* `path.admin.inc`
* `redirect.admin.inc`
* `search.admin.inc`
* `system.admin.inc`

Also, the documentation for `confirm_form()` specifically suggests an example of `$question` is "Are you sure you want to delete the block...".

So it seems like asking the "destructive" bit in `confirm_form()`, rather than as a separate warning message, is a fairly well established practice.

**Comment by klonos** [comment]
Thanks @bugfolder for splitting all these suggestions from #5077 into this separate follow-up 🙏🏼

**Comment by bugfolder** [comment]
OK, this is going to need some automated tests for all the possible checks, but before I go adding those, I'd like to get feedback on the current PR and behavior.

In particular, if we're deleting the last layout-created page for a path, and that path is used has home, 403 or 404 page, I'm currently just disabling the delete/disable buttons, but leaving them visible. Should they be removed entirely (leaving on the "Cancel" link)? And of course, any other issues/suggestions on wording or things to check are welcome.

**Comment by bugfolder** [comment]
Recommendation from 2022-02-24 design meeting: don't disable the buttons, but add a post-delete (or post-disable) warning that the person needs to edit the site information page if needed.

**Comment by klonos** [comment]
Yes, I think that during the UX/design meeting we all agreed that:
- removing/disabling the submit button(s) is NOT a good idea - it would cause frustration to those that understand the risks and still want to perform the action
- adding the warnings is a good idea 👍🏼 
- adding a second submit button that allows disabling the layout instead of deleting it is also a good idea
- depending on the action taken by the user, throwing a message after the action was performed, along with links to the config pages that hold the settings that have been affected would be best approach

Personally not sure if that message should be a success, or info, or warning, or a combination. I guess it will depend on the wording of the message(s).

**Comment by bugfolder** [comment]
I've updated the PR and its behavior, which is now:

* Added a disable option to the "Delete layout?" confirmation page.
* If deleting (or disabling) a layout would remove a page that is used on the site info page, a warning is issued on the "Delete layout?" confirmation page, and after confirming deletion or disabling, a warning message is put up directing the user to the site info page to make the appropriate change.
* If the user disables a layout directly (using the dropbutton link, so there's no confirmation page), if that action removes a page that is used on the site info page, a warning message is put up directing the user to the site info page to make the appropriate change.

Please give feedback on behavior and wording of the messages. Once that is all stabilized, I'll go back and create automated tests.

**Comment by jenlampton** [comment]
I think this looks really great!  I've given it a test and I think it's a great improvement :)

I left a few text change suggestions on the PR, mostly in an attempt to shorten the text and simplify the language a bit. 

There is a lot of repeated text across all the various messages. I was thinking we might be able to create fewer strings to translate if we could separate the different parts of each message into individual translatable strings. For example:

warning: `This layout creates a page at %path that is currently the :type page for this site`
statement: `If you delete or disable this layout, that page will be removed.`
action: `You have :action the page at %path that was used as the :type page for this site.`
recommendation: `You should also change the :type setting under <a href="!url">site information</a>. `

These messages could be generated as follows:

> `This layout creates a page at %path that is currently the default 404 (not found) page for this site. If you delete or disable this layout, that page will be removed. You should also change the 404 page setting under <a href="!url">site information</a>`

warning + statement + recommendation

> `You have deleted the page at %path that was used as the default 404 (not found) page for this site. You should also change the 404 page setting under <a href="!url">site information</a>.`

action + recommendation

* `You have disabled the page at %path that was used as the default 404 (not found) page for this site. You should also change the 404 page setting under <a href="!url">site information</a>.`

action + recommendation

....but I'm not sure how much of a priority these translation changes are. I might be getting into the weeds a bit here :)

**Comment by bugfolder** [comment]
I've made all changes suggested in the PR, and then have factored the various messages a bit somewhat like the above to reduce the translation burden.

**Comment by herbdool** [comment]
@bugfolder I've closed your PR because needs to be rebased before it can be reopened. It needs the latest Tugboat fix.

**Comment by bugfolder** [comment]
I've now added automated tests (and fixed PHPCS complaints about preexisting code).

**Comment by argiepiano** [comment]
I've done a code review - other than a minor suggestion, I think this looks good. I did not put on my linguistics hat for this, so I trust that the messages are satisfactory to those who tested this earlier. Marking this as RTBC.

**Comment by quicksketch** [comment]
Thanks folks! A nice set of changes here. I merged https://github.com/backdrop/backdrop/pull/4477 into 1.x and 1.26.x.

**Comment by quicksketch** [comment]
Oh I didn't even see this was tagged for 1.27.0. As a UX improvement this can be merged into 1.26.x, though it does add several new strings (for administrators only).
