### ISSUE TITLE
[UX] Display container style on rows in flexible layout template builder.

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#5523]
## Description of the need

In the layout flexible template builder, you can click the per-row menu to configure settings for the row, including setting the row style width type to be one of Fixed maximum width, Fluid width, or Full width. It would be convenient if this container style were displayed on the label of the row.

## Proposed solution

Show the row container width style on the row label:

![flexible-template-suggestion](https://user-images.githubusercontent.com/14188307/157074675-2863a2b9-479b-477a-8aa8-2654034c46bf.png)

## Alternatives that have been considered

![image](https://user-images.githubusercontent.com/350497/156093906-c6b6e9a7-f780-4e6a-a0d1-d6b17ae286f9.png)

**Comment by olafgrabienski** [comment]
Nice idea! I've tested it in the PR's sandbox, works for me.

**Comment by olafgrabienski** [comment]
Screenshot of what the PR does: https://github.com/backdrop/backdrop/pull/3967#issuecomment-1054942553

Maybe add some more space between Row name and container style information? Or, do we have already a UI pattern for this case?

**Comment by klonos** [comment]
Actual screenshot:

<img width=70% src="https://user-images.githubusercontent.com/350497/156096450-67f46e45-f694-4e6a-836d-99db68182aa2.png">

**Comment by klonos** [comment]
I like this 👍🏼 

> Maybe add some more space between Row name and container style information? Or, do we have already a UI pattern for this case?

Yeah, not sure whether there is a similar UI pattern, but we need to figure out a better way to display that. How about either some spacing as @olafgrabienski said, or wrap it under the "Row" label + also perhaps enclosing the container width text in brackets?

The closest I could think of where secondary information is displayed alongside the main thing is the new style we use for machine names:
![image](https://user-images.githubusercontent.com/2423362/156177707-a8372fcd-e491-4ec8-97ab-16cad3c6d3f2.png)

**Comment by jromine** [comment]
Looking at other places that use draggable, one with text under the label is text editor filters:

![image](https://user-images.githubusercontent.com/350497/156225946-21ff0c8a-a9f8-4d75-a893-e8a00057631d.png)

Another is content types > manage fields:

![image](https://user-images.githubusercontent.com/350497/156226080-494b6453-0995-4968-96a6-efaafdaf6e93.png)

However, both will make the row height larger, and there is empty space across the row width, so maybe that's a consideration.

**Comment by jromine** [comment]
@olafgrabienski that looks good.

**Comment by jromine** [comment]
PR for review https://github.com/backdrop/backdrop/pull/3967

**Comment by indigoxela** [comment]
A nice improvement, I like it. :+1:

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/3967 into 1.x and 1.24.x.

https://github.com/backdrop/backdrop/commit/fe1d2f59b725e82601fb30a27e1ef84927fefa87 by @jromine, @olafgrabienski, @klonos, @stpaultim, @indigoxela, and @herbdool.
