### ISSUE TITLE
Telemetry: Properly detect LightSpeed/OpenLightSpeed and IIS instead of "other"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5524]
Although not as popular as apache/nginx, it would be nice to get a better understanding of the percentage of sites using these web servers. These are both dropped into the "other" bucket currently in https://backdropcms.org/project/backdrop/telemetry:

![image](https://user-images.githubusercontent.com/2423362/156398264-a6641e7b-3598-4817-a5b5-ebdef4fc1319.png)

---

PR https://github.com/backdrop/backdrop/pull/3984

**Comment by indigoxela** [comment]
Maybe interesting for evaluation: https://w3techs.com/technologies/overview/web_server

IIS is not really relevant for Backdrop, I guess. LiteSpeed seems to be trendy.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼  ...IIRC, we did have a few issues in the queue related to IIS (most notably #5047 and #4743, but others too), so I guess not completely irrelevant - although not officially supported, I know. Gathering metrics for it wouldn't hurt though. It would help us make better-informed decisions 😉

**Comment by quicksketch** [comment]
Filed a PR at https://github.com/backdrop/backdrop/pull/3984. I'm not sure if this counts as official support (combined with https://github.com/backdrop/backdrop-issues/issues/5525). But in any case I agree that it would be useful to track how many LiteSpeed servers are in use.

I'm surprised in general with the resurgence of LiteSpeed. I remember it from decades ago and it was always a bit player. Now it's the 4th most popular web server (3rd if you don't count CloudFlare).

**Comment by klonos** [comment]
Thanks @quicksketch 🙏🏼 ...you beat me to it 🙂 

RTBC 👍🏼 (I've set the milestone label - can someone please add the actual milesotne?)

> I'm not sure if this counts as official support...

I think that we should stick with apache/nginx in the official documentation.

**Comment by klonos** [comment]
PS: I've also setup one of my cousins on an EU-based shared hosting provider, and they also use LiteSpeed.

**Comment by indigoxela** [comment]
Milestone set.

We can revisit "official support" with a mention in the system requirements documentation after we gathered some telemetry data. :wink:

**Comment by quicksketch** [comment]
Thanks @yorkshire-pudding, @klonos, and @indigoxela for reviewing! I've merged https://github.com/backdrop/backdrop/pull/3984 into 1.x and 1.21.x.
