### ISSUE TITLE
[UX] Redirect to installer before bootstrapping Backdrop

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#554]
This is a follow-up from https://github.com/backdrop/backdrop-issues/issues/528.

We've fixed backdrop so that when you go to `core/install.php` it will be able to let you know that your PHP version is too old rather than just throwing an ugly fatal error. If you were to load the home page of your new Backdrop site expecting to be redirected to the installer, however, you still get  PHP fatal:

```
Parse error: syntax error, unexpected T_FUNCTION in backdrop/core/includes/common.inc on line 5355
```
That line contains the following code:
```
/**
 * Decode Unicode characters in JSON strings.
 */
function backdrop_json_decode_unicode($json) {
  return preg_replace_callback('/\\\\u([0-9a-f]{4})/i', function ($match) {
    return mb_convert_encoding(pack('H*', $match[1]), 'UTF-8', 'UCS-2BE');
  }, $json);
}
```
PHP 5.2 doesn't do closures, so we'd either need to rewrite all of bootstrap.inc not to use them, or not bootstrap Backdrop before redirecting to the install page. I recommend the latter, as per this issue title.

**Comment by tarekdj** [comment]
@jenlampton 
https://github.com/backdrop/backdrop/pull/648
