### ISSUE TITLE
TaxonomyTerm Not Creating Term Hierarchy Reference

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop/backdrop-issues#5540]
## Description of the bug

When using TaxonomyTerm::save for a new term, the term is not showing up on the backend of Backdrop.

## Steps To Reproduce

I am using the following code in my module:

```
$term = new TaxonomyTerm();
$term->vocabulary = $vocabulary_machine_name;
$term->name = $term_name;
$term->parent = 0;
$term->save();
```

I had to add the following code to my module to facilitate:

```
db_merge('taxonomy_term_hierarchy')
  ->key(array('tid' => $term->tid))
  ->fields(array(
    'parent' => 0,
  ))
  ->execute();
```

## Actual behavior

The term is created and is in the taxonomy_term_data table, but is not viewable on the UI. The term count accurately reflects the number of terms, but no term is visible.

## Expected behavior

The term will show up on the UI.

## Additional information

Add any other information that could help, such as:
- Backdrop 1.21.3
- Apache
- Server: Ubuntu Linux 20.04 - 
- Desktop: Firefox & Safari on Macintosh Big Sur - most recent versions

**Comment by argiepiano** [comment]
I have been able to reproduce this by following the steps. The saved taxonomy term is accessible through the regular path and through the alias, and it can't be edited, but it's not shown in the  term list for the vocabulary.  If you edit the term through the UI and save it again, it will appear.

Any thoughts on what may cause this? Do you think you can debug it?

(One detail, unrelated to this issue: `$term->parent = 0;` causes `Warning: Invalid argument supplied for foreach() in TaxonomyTermController->postSave()`. Instead, leave out the parent property. But the issue remains the same - the new term does not appear in the vocabulary list.)

**Comment by argiepiano** [comment]
OK, I've debug this a bit.

It seems like `parent` MUST be an array of parents. It can't be a numeric value.

If you try the following, the term will be saved normally:

```php
$term = new TaxonomyTerm();
$term->vocabulary = $vocabulary_machine_name;
$term->name = $term_name;
$term->parent = array(0);
$term->save();
```

So, it looks like this is not a bug after all?

**Comment by argiepiano** [comment]
However, the documentation for this property is wrong. It must be either fixed, or the `postSave()` method has to account properly for a value of 0.

```
   * The property can be set to an array of term IDs. An entry of 0 means this
   * term does not have any parents. When omitting this variable during an
   * update, the existing hierarchy for the term remains unchanged.
   ```

**Comment by argiepiano** [comment]
Rather than changing the documentation, I believe the most efficient way to fix this is to typecast `$entity->parent` as an array. This will allow parent to be a 0 value. PR coming. 

Another way is to fix the documentation to clarify that parent should always be an array... let me know if that's preferable and I'll scrap the linked PR.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/3989

**Comment by indigoxela** [comment]
Personally, I'm not a huge fan of typecasting. A variable should have one type and ideally not multiple, I'm aware this is often not the case in core. Currently I'd rather prefer to fix the documentation. Let me explain:

```
  /**
   * (optional) The parent term(s) for this term.
   *
   * This property is not loaded, but may be used to modify the term parents via
   * TaxonomyTerm::save().
   *
   * The property can be set to an array of term IDs. An entry of 0 means this
   * term does not have any parents. When omitting this variable during an
   * update, the existing hierarchy for the term remains unchanged.
   *
   * @var array
   */
  public $parent;
```

The confusing part is: `An entry of 0 means this...`. However, also note the `@var array`. It should be an array and only array.

IMO this should rather be: `An entry of array(0) means this...`. That seems less confusing to me. Any thoughts?

**Comment by ElusiveMind** [comment]
I'll add my .02 on the documentation issue. I think the issue for me, was the documentation at 

https://docs.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.entity.inc/class/TaxonomyTerm/1?title=&title_1=&object_type=&order=summary&sort=desc

was not clear in my initial reading that this should be an array. I didn't look through the code, admittedly. As for the typecasting, would a better approach to be to check for a scalar or an array and handle the value accordingly?

```
if (is_scalar($entity->parent)) {
  $entity->parent = array($entity->parent);
}
```

Another question that comes to mind is how does one term have multiple parents? From a relational perspective I understand it, but from a UI/Hierarchical standpoint, how would one term be reflected to have multiple parent terms? Would it be repeated in multiple places? This could be confusing since you could have multiple terms of the same name each with different parents as well.

Let me know how I can best serve.

**Comment by indigoxela** [comment]
> Another question that comes to mind is how does one term have multiple parents?

That is technically possible, also via UI, but to be honest, I've no real world use-case for that.

UI:
![multiparent](https://user-images.githubusercontent.com/842066/158152446-ec134d5d-0dd5-441b-91df-b0cba5f819cd.png)

Debugging:

```
$tree = taxonomy_get_tree('nested_thing', 0, NULL, TRUE);

debug($tree);
```
Outcome:
```
...
     'parents' => 
    array (
      0 => '1',
      1 => '3',
    ),
```
So, I can't provide anything useful for `TAXONOMY_HIERARCHY_MULTIPLE`, only that it seems to be possible.

I'm still no fan of typecasting, when the problem actually seems to be misleading documentation.

**Comment by argiepiano** [comment]
I agree with you, @indigoxela . I had missed the `@var array` last night. I'll scrap this PR and will provide  a fix for the doc as you suggest

**Comment by indigoxela** [comment]
> I wish they had called this property parents instead of parent

@argiepiano Same here. :wink: A tiny coding standard fix and I think we're done (see my PR comment).

@ElusiveMind would the example `array(0)` have helped you to understand what's needed? Any other recommendation for the current [doc block](https://docs.backdropcms.org/api/backdrop/core%21modules%21taxonomy%21taxonomy.entity.inc/property/TaxonomyTerm%3A%3Aparent/1) to make developer lifes easier?

**Comment by argiepiano** [comment]
Fixed coding standard. Thanks @indigoxela.

**Comment by ElusiveMind** [comment]
It would have helped.

From a developer standpoint, anything defensively we can contribute to remove warnings helps. Or some kind of sanity checking to make sure the variable being passed is the correct type would be a benefit. But I'll leave this to your discretion.

**Comment by indigoxela** [comment]
> From a developer standpoint, anything defensively we can contribute to remove warnings helps.

That seems a bit tricky here - TaxonomyTerm::create overrides Entity::create. Silently replacing wrong types with `array(0)` might lead to unexpected results, when there should actually be a parent.

> ...some kind of sanity checking to make sure the variable being passed is the correct type

I get the point. Currently there's only a pretty generic php warning: "Warning: Invalid argument supplied for foreach() in TaxonomyTermController->postSave() (line 281 of ...core/modules/taxonomy/taxonomy.entity.inc)."
But that might already give a clue.

Failing hard in case $parent isn't an array might not be the most helpful thing, either. Or would that be preferable?

**Comment by ElusiveMind** [comment]
I think the documentation will be good. My only other thought is that if people see that warning in the future they may report it. I think it'll be OK since my usage is somewhat of an edge case. I think we can make the doc update and close the issue. Thanks for listening and discussing!

**Comment by indigoxela** [comment]
@ElusiveMind many thanks for reporting and feedback.

Setting label to RTBC. Many thanks @argiepiano for your quick fix.
