### ISSUE TITLE
[PS] Removed unnecessary condition in `views_fetch_fields()`.

### ISSUE THREAD

**Issue by VasasA** [backdrop/backdrop-issues#5543]
## Description of the bug

There is a line (599) in `core\modules\views\includes\utility.inc` contains an unnecessary condition:
```php
if ($string != 'base' && $string != 'base') {
```

## Expected

```php
if ($string != 'base') {
```

**Comment by aniketh-varma** [comment]
> Thank you @aniketh-varma 🙏🏼 ...this is RTBC - nothing to be tested really, but:
> 
> * We need to wait for a core committer to approve the GitHub workflows, so to allow the tests to run.
> * Once tests have ran, they need to all pass without failures.
> * I have just added the `milestone candidate - bug` label for this issue - now another person needs to add the actual milestone, and remove the label

Alright! Thanks for the prompt review.

**Comment by indigoxela** [comment]
Automated tests have run, code looks good, time for a milestone.

@aniketh-varma many thanks for your PR! :pray:

**Comment by BWPanda** [comment]
Ha, weird. Blame @merlinofchaos: https://www.drupal.org/project/views/issues/1135918 😉

**Comment by BWPanda** [comment]
Thanks @aniketh-varma for the PR and to @VasasA for spotting this! I've merged https://github.com/backdrop/backdrop/pull/3991 into 1.x and 1.21.x.

**Comment by stpaultim** [comment]
Congratulations @aniketh-varma. Thanks for the help with the Backdrop CMS project. 

I'm going to change the tags on this issue.

**Comment by klonos** [comment]
Thank you from me too @aniketh-varma 🙏🏼 

@stpaultim we do remove other labels when closing tickets, but please keep `type - *` and `status - has pull request` (that way we known which issues got fixed by a code change).
