### ISSUE TITLE
Add better description text for `administer blocks`

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5544]
Comments from @stpaultim: 

> there should be more information for the "Administer Custom Blocks" permission. Maybe the permission description should say (instead of `Administer Custom Blocks`):  `Access the custom blocks admin page` Or `People with permission to Administer Layouts also have some custom block privileges.`

![image](https://user-images.githubusercontent.com/3144571/158504745-7ae2aeb6-3c4d-4584-9e82-3b206e3d297b.png)

**Comment by jenlampton** [comment]
We definitely need better description text than `Administer Custom Blocks` for this permission. 

I don't think `Access the custom blocks listing page` is quite enough though, because this permission also allows people to configure blocks from that page. We have other similar "Access the ___ page" permissions that don't include the ability to manage things on that page, and because this permission is different, we should include that. 

How about something like `Configure custom blocks from the administrative listing page`?

I'm also hesitant to reference one permission from another if we can avoid it, but I do see how that could be valuable here.

**Comment by stpaultim** [comment]
@jenlampton 

How about `Access and administer custom blocks on the administrative listing page.`

I also like your idea:

`Configure custom blocks from the administrative listing page`

**Comment by jenlampton** [comment]
I generally dislike `administer` since it's so vague. We can also create them, delete them, and clone them, maybe even export them too? Administer is really more accurate here. What about... 

`Administer custom blocks and access the administrative listing page`

**Comment by ayushi424** [comment]
Hi, I am Ayushi, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by stpaultim** [comment]
@ayushi424 - This issue could potentially be fixed by creating a PR through the Github interface, without even setting up a local environment. See: https://backdropcms.org/news/creating-pull-requests-against-core-the-easy-noob-way

Let us know if you have any questions.

**Comment by ayushi424** [comment]
Thankyou for assiging this issue to me.
I'm unable to find the file where better description text need to be added. Any guidance for the same please. 

Also, the text that need to be added is:

> Administer custom blocks and access the custom block listing page

> 

Please confirm.

**Comment by indigoxela** [comment]
@ayushi424 I belief, that's in [block.module](https://github.com/backdrop/backdrop/blob/1.x/core/modules/block/block.module#L12)

See also the documentation for [hook_permission()](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_permission/1)

In addition to the "title" there can also be a "description". I think, this is what's requested here.

**Comment by Amulya-coder** [comment]
Hi, I'm Amulya, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by aniketh-varma** [comment]
Hi, I would like to work on this issue if it's still up for grabs.

**Comment by indigoxela** [comment]
Hi @ayushi424 and @Amulya-coder and @aniketh-varma,

thank you all so much for offering help. Now there's three people ...

Are you planning to do this together as a team, or did we run out of "good first issues" and you grab what you can get? :smile:

**Comment by stpaultim** [comment]
@ayushi424 was assigned this issue first. I recommend that @Amulya-coder and @aniketh-varma look for another issue. Maybe start with the oldest "Good First Issues" and find one that does not have anyone that has asked to work on it in the last 30 days. 

See: https://github.com/backdrop/backdrop-issues/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Aupdated-asc

**Comment by ayushi424** [comment]
Hi, I have created the PR for this issue.
https://github.com/backdrop/backdrop/pull/3995
Kindly review my PR and if there are any other modifications to be done, please let me know.
Thankyou.

**Comment by jenlampton** [comment]
The PR looks great, code review looks good. And testing shows that it works as intented. Nice work @ayushi424 :)

I took a look at the sandbox, however, and I'm not thrilled with the result:
<img width="1218" alt="Screen Shot 2022-03-17 at 10 49 22 AM" src="https://user-images.githubusercontent.com/397895/158864409-07efc1d0-dd0b-4b6e-92de-09a178f1a9e9.png">

"Administer custom blocks" is repeated in the label and in the description, so I don't think repeating it a second time adds any value. Would it be better to say `Manage custom blocks and access the custom block listing page`. We use the word "manage" in other places and people generally know what that means (delete, configure, export, etc)

**Comment by stpaultim** [comment]
I confer. There is one other permission description we want to update, I'll open a new ticket for that one, but maybe we can convince @ayushi424 to provide a PR for that one as well.

**Comment by ayushi424** [comment]
Hi @stpaultim, thankyou for considering me to provide a PR for issue #5552. I would be more than happy to work on it:)

**Comment by BWPanda** [comment]
Thank you @ayushi424 for this PR! Thanks also to @jenlampton and @stpaultim for reviewing. I've merged https://github.com/backdrop/backdrop/pull/3995 into 1.x.
