### ISSUE TITLE
Doc block for node_type_set_defaults() refers to hook_node_info(), which was removed

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#5550]
## Description of the bug

In [node.module at or around line 757](https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/node.module#L757), the doc block for node_type_set_defaults() refers to hook_node_info(), which is removed

**Comment by BWPanda** [comment]
Was just about to come and file an issue for this 😃 Here's a PR instead: https://github.com/backdrop/backdrop/pull/4038

**Comment by BWPanda** [comment]
Thanks for finding this @jromine. I've gone ahead and merged https://github.com/backdrop/backdrop/pull/4038 into 1.x.

**Comment by klonos** [comment]
FTR, the change record for the removal of `hook_node_info()` is here: https://docs.backdropcms.org/change-records/hook_node_info-removed
