### ISSUE TITLE
Views cache causes validation errors

### ISSUE THREAD

**Issue by kswan** [backdrop/backdrop-issues#5551]
## Description of the bug

The References module can use a view to list valid users or nodes. Views caching can cause validation failures.

## Steps To Reproduce

To reproduce the behavior:

1. enable the references module
2. create a view that returns a list of some users including "user a" and "user b"
3. set the view to cache its results, time-based, 1hour
4. create a content type with a user reference field
5. configure the user reference field to use the user view as its allowed value list
6. create a node of the new content type with the user reference field value "user a"
7. edit the node, and attempt to change the user reference field value to "user b"
8. or create a new node of the new content type with the user reference field value "user b"

## Actual behavior

Validation fails, can not save the node.
![image](https://user-images.githubusercontent.com/154391/158906798-d978c2de-b97c-4331-a324-c7c43142fe81.png)

## Expected behavior

Since the user is a valid user, validation should pass.

## Additional information

A workaround is to set the view cache to none.
Also, flushing the backdrop cache between steps 6 and 7 causes validation to succeed.
@jromine Investigated this issue and found a matching Drupal issue https://www.drupal.org/project/drupal/issues/1055616

This was originally reported in the References issue queue https://github.com/backdrop-contrib/references/issues/12

**Comment by klonos** [comment]
Thanks for providing a PR @jromine 🙏🏼  ...I've left some feedback.

**Comment by jromine** [comment]
PR up for review https://github.com/backdrop/backdrop/pull/3998

**Comment by klonos** [comment]
Thank you @jromine ...I've reviewed the code, and it looks good now 👍🏼 

I've also tested this on the PR sandbox, using the steps mentioned in the issue summary, and things worked as expected, without any errors. @kswan can you please also test on your end and confirm that the issue is solved? Thanks.

**Comment by kswan** [comment]
Thank you @jromine and @klonos . I tested the PR on my dev site and the original issue is resolved. 

It looks good to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/3998 into 1.x and 1.21.x. Thanks @jromine, @kswan, and @klonos!
