### ISSUE TITLE
Add better description text for administer layouts

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5552]
## Description of the bug

While changing the permission description for https://github.com/backdrop/backdrop-issues/issues/5544 `administer blocks`, we determined that the `administer layouts` description could also use some improvements. 

The administer layouts permission also allows a user to create blocks, which I think is worth specifying.

PERMISSION:
`Administer Layouts`

WAS:
`Add and modify layouts on pages. Warning: Give to trusted roles only; this permission has security implications.`

PROPOSED:
`Create and modify layouts and blocks. Warning: Give to trusted roles only; this permission has security implications.`

**Comment by ayushi424** [comment]
Hi @stpaultim, can you please assign this issue to me under OPENFORCE 2022 project. Thankyou

**Comment by ayushi424** [comment]
Hi, could you help me find the administer layouts ?
I'm unable to find. Apologies for that.

**Comment by stpaultim** [comment]
@ayushi424 - No, problem. Please, feel free to ask if you have questions. 

Here is what I did. 

1) I noticed that your previous PR about blocks was in the core/modules/block/block.module file. 
2) Since this new permission is for layouts, I looked at core/modules/layout/layout.module. I searched for "permission" in this file and found line 756, which what you need. 

Another approach would be to search the entire code base for the following string: "Add and modify layouts on pages"

![image](https://user-images.githubusercontent.com/3144571/158957563-c5125424-6b5c-414e-8086-6b6cb30d3588.png)

I hope I have not steered you in the wrong direction.

**Comment by ayushi424** [comment]
Thankyou so much @stpaultim for your help, I was a bit confused with the large code base.
I have created the PR for this issue, Kindly review it and if there are any modifications to be done, please let me know.
Thankyou.

**Comment by stpaultim** [comment]
Thanks @ayushi424 - This Pull Request also contains the change in https://github.com/backdrop/backdrop-issues/issues/5544. 

We can not have any changes except the one for this specific Pull Request. We could combine these two issues into one and use one Pull Request, but it might be easier if you just keep them separate and remove the change to the block module from this PR. 

You should always use a different branch for each Pull Request and the branch should start out clean, without any other changes in it. Does this make sense?

**Comment by bugfolder** [comment]
A tip I learned from some of the more experienced Backdrop contributors is to prefix the name of each branch with the issue number (helpful to keep things organized when you start to work on multiple issues at the same time). So, for example, you might call the branch for this issue `5552_administer_layouts`, or something like that.

**Comment by ayushi424** [comment]
Hi @stpaultim thankyou for your valuable suggestions.
I have done the required changes in the PR for this issue, please have a look.
And thanks @bugfolder, I'll take care while working with branches.

**Comment by stpaultim** [comment]
@ayushi424 - Very good. But, one more easy problem to fix.

When you fixed the change in the block module, you left two extra spaces. We are very careful about our coding standards and you will need to delete those two spaces. 

I recommend that you always look at the files tab on the PR so you can see exactly what your PR is changing. In this case, the two spaces are pretty obvious and do not belong there. 

![image](https://user-images.githubusercontent.com/3144571/159112005-2c463c67-5f34-4656-9666-476eb5e8ac66.png)

**Comment by ayushi424** [comment]
Oops, sorry for that. @stpaultim 
I'll be extra careful next time.

**Comment by stpaultim** [comment]
@ayushi424 - Congratulations on another PR. I've test this and will mark it Ready to be Committed. 

There is still some change that someone will offer an idea on how to improve this text before we merge it. But, maybe not, because it's pretty simple and straightfoward.

**Comment by BWPanda** [comment]
Thanks @ayushi424 and @stpaultim for this PR! I've merged https://github.com/backdrop/backdrop/pull/4002 into 1.x and 1.21.x.

**Comment by stpaultim** [comment]
Thanks @ayushi424 !!!!
