### ISSUE TITLE
Add a configuration option for database log message display length.

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#5553]
## Description of the need

The database log report at admin/reports/dblog limits the log message length to 56 characters before truncation. This is inadequate for my use case and window size, and requires much clicking of links to see log details.

It was possible in Drupal 7 to alter the log display by overriding the dblog_message theme function, however that capability was removed in https://github.com/backdrop/backdrop/pull/629.

## Proposed solution

Provide a numeric setting for log message line length on the admin/config/development/logging page.

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes a setting to limit dblog message length before truncation.

---

Minor release update:
- [x] Add a conclusion suitable for blog post + release notes
- [x] N/A Add Documentation label if the feature needs to be documented (or needs docs to be updated)
- [x] N/A Add Needs change record label if the the issue contains an API change.
- [x] Add Needs translation label if the the issue contains string translations.

String changes:
* `Database log messages to keep` to  `Messages to keep` 
New strings:
* `Abbreviated message length`
* `The maximum log message length when abbreviated on the <a href="@url">recent log messages page</a>.`

## conclusion suitable for blog post

There is now a setting to control how much of the database log message is shown on the list of messages.

**Comment by jromine** [comment]
![image](https://user-images.githubusercontent.com/350497/158920153-92cb7533-4297-4897-a454-8b8475ad5ae5.png)

**Comment by bugfolder** [comment]
I would love to have this ability (restored).

**Comment by jromine** [comment]
I think the problem is the log length setting is created in update.php, and some log messages are being generated before that can run. I'll update the PR to provide a default value.

**Comment by jromine** [comment]
I updated the PR. I'm not sure if I need to initiate a re-test, or that will happen automatically.

**Comment by jromine** [comment]
After updating the PR, the tests look good now.

**Comment by indigoxela** [comment]
Great, many thanks for your PR.

I wonder, if the config value has to get removed from the system.core json, when uninstalling the dblog module. :thinking:
But I noticed, that this also doesn't happen with the other values.

**Comment by jromine** [comment]
@indigoxela I agree, other settings for some core modules seem to go in system.core rather than their own module-specific config file, and don't get removed when uninstalling the module. The existing settings are also named log_* rather than dblog_*. I tried to follow existing practice.

**Comment by bugfolder** [comment]
Code reviewed: LGTM.

Tested:
* Set value to 10, worked.
* Set value to 10.5, got an error (appropriately).
* Set value to 1000, got an error (appropriately) for max length of 255.

So, works for me.

Restarted tests. Tests failed twice, but different failures both times, and neither appeared related to these changes. So I'm guessing it's the test gremlin. Or, put differently, between the two runs, every test passed at least once.

**Comment by hosef** [comment]
We should move the install hook to system.install since the setting is going to live in the System module. That way all the functionality that changes that setting lives in one place.

**Comment by bugfolder** [comment]
It looks like a simple change to get this across the finish line. @jromine, would you be open to a replacement PR (or a PR against your PR)?

**Comment by jromine** [comment]
@hosef Existing update hooks in dblog.install affect settings in system.core. Will they all be moved or are we splitting up these hooks into two locations?

**Comment by bugfolder** [comment]
Would like to get @hosef's input on this, but my understanding is that moving existing update hooks between modules is problematic because existing systems will have recorded those hooks as having run. But new ones can be moved before they're merged in.

**Comment by quicksketch** [comment]
Putting log updates in system.install makes sense to me. I think this PR is ready for review again.

**Comment by klonos** [comment]
@bugfolder I would suggest to change the label of the field and/or its description to clarify that this is NOT about truncating the length of the log messages that is being saved in the database, rather than the length of the text being displayed in the log report page. Perhaps "Log message display length" for the label, and something along the lines of "Limit the mount of characters for each log entry in the reports page (does not trim the message that is actually being saved in the log)."

I would also like to see a "characters" suffix added to the field please.

PS: taking the opportunity to mention that https://github.com/backdrop-contrib/views_watchdog is only a few lines of code, and if that functionality was added to core + the dblog report page converted to a view, then people would be able to not only tweak the length/trimming of the entries, but also do other things with the messages (such as add filtering by keywords or date range, besides type/severity etc.).

**Comment by bugfolder** [comment]
> We should change the label of the field and/or its description to clarify that this is NOT about truncating the length of the log messages that are being saved in the database

Language changed. Perhaps noting that this is the "displayed" message length makes sufficient distinction that we don't need to add more words about what is stored.

> Add a "characters" suffix to the field.

Added.

> Move all fields provided by the dblog module into a fieldset

Added.

Agreed that the other bits are worthy of separate follow-up issues. (And being a fan of putting as much as possible into Views, I quite agree with the absorption of `views_watchdog`.)

I also found (and fixed) a hard-coded reference to the 56-character truncation limit in a docblock.

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼 ...I'll make sure to file separate follow-ups for the other tasks.

Code looks OK to me, and the form looks neat now. There is still an odd failure in the phpcs check that throws `Error: Command failed: phpcs --version`, but I guess we can ignore that for now(?).

**Comment by bugfolder** [comment]
PR updated with your suggestion, thanks.

Dunno why the phpcs command is failing, but it doesn't seem related to any of the code changes.

**Comment by klonos** [comment]
> PR updated with your suggestion, thanks.

Thank you @bugfolder 🙏🏼 ...that has caused PHPCS to complain about a missing comma now. Can you please quickly fix that too?

**Comment by bugfolder** [comment]
Fixed that, but more PHPCS complaints in layout.admin.inc, which is not part of this PR.

**Comment by klonos** [comment]
Thanks again :)

@indigoxela do you have any idea? Is it #5721 or #5848 or a separate issue?

**Comment by bugfolder** [comment]
I rebased it, and PHPCS is now happy. Tests restarting.

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼  ...this is still RTBC and good to go 👍🏼 

Follow-up issues for the things I mentioned in my [comment](https://github.com/backdrop/backdrop-issues/issues/5553#issuecomment-1363452225) above:
- I have added the fieldset around the syslog-related fields as part of my PR for #4615, so no need for a new issue.
- I have filed #5897 for moving the settings of the dblog and syslog modules out of `system.core.json`.

**Comment by quicksketch** [comment]
One suggestion on the PR's update hook: https://github.com/backdrop/backdrop/pull/4288/files#r1058661197

**Comment by bugfolder** [comment]
Suggestion accepted. Back to review.

**Comment by quicksketch** [comment]
Code LGTM, I'd like to give it a try locally to check on the upgrade path.

**Comment by jenlampton** [comment]
In testing, the display of messages on the `admin/reports/dblog` page was shorter, but I was surprised to see the complete message is still displayed on /admin/reports/event/*` pages. I think I was mislead by the label `Displayed message length`, which seems like it should apply when the message is displayed. 

What about something like `Abbreviated message length`, or `Shortened message length`?

**Comment by jenlampton** [comment]
I seem to be unable to make a PR against your PR @bugfolder, but I added some alternative label/description text options on the PR for consideration. (I chose `Abbreviated`)

**Comment by bugfolder** [comment]
Sounds good to me. Both changes made, PR updated.

**Comment by quicksketch** [comment]
I tested the upgrade path and it works great. Also tested the functionality of adjusting the limit and it takes effect immediately. Nice job!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4288 into 1.x for 1.24.0. Big thanks to @bugfolder and @jromine for spearheading this issue!

https://github.com/backdrop/backdrop/commit/ac50b830920e6c672c48591d35493e576a2b5e3c by @bugfolder, @jromine, @indigoxela, @klonos, @hosef, @quicksketch, and @jenlampton.
