### ISSUE TITLE
Mark some Comment permissions as restricted

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5554]
In working on https://github.com/backdrop/backdrop-issues/issues/5536, I noticed that while permissions like `Administer content` are restricted (they have the security warning), equivalent Comment permissions aren't.

IMO, the following Comment permissions should be restricted:
- `Administer comments`
- `Administer comment settings` - allows approving and deleting comments
- `Skip comment approval` - allows bypassing approval process
- `Edit own comments` - allows getting approval for a comment, but then changing it to say something else afterwards (also bypassing approval)

Thoughts?

**Comment by kiamlaluno** [comment]
I agree: Those permissions should not given to every user (generally speaking). The warning is worth adding it.
Clearly, depending from the community the site is built for, it would be acceptable to give the *Skip comment approval* permission to any user with an account, but that is something the user building the site needs to evaluate. Those warning should not be takes as *Never give this permission.* but *Think before giving this permission.*

**Comment by argiepiano** [comment]
Thank you for the PR @kiamlaluno!  I've left a couple of language suggestions in the PR.

**Comment by olafgrabienski** [comment]
Hey @kiamlaluno - thanks for your PR! In Backdrop we try to avoid the term "user" for people, or: we try to use the term only for user *accounts*. How to replace "user", depends on context. E.g., a phrase like the following:

> **Users** could post spam or offensive comments that become immediately visible to every **user**.

... can be changed to something like:

> **People** could post spam or offensive comments that become immediately visible to every **visitor**.

It would be great if you could look for "user" alternatives in your PR.

**Comment by kiamlaluno** [comment]
I didn't forget this issue: I am checking what phrase is used by Backdrop in these cases. * immediately visible to every visitor* seems correct to me, as the comment would probably be visible to anonymous users too (except in the case they don't have the permission to see comments). *People could post spam or offensive comments* sounds strange to me, as it seems to generally speak of people, not people who has an account on the site.

**Comment by kiamlaluno** [comment]
Looking at the permission descriptions, *user* and *users* are used words.

> Allows a user to configure patterns for automated URL aliases and bulk delete URL aliases.

> Determines whether or not users are shown a notice when an automatic URL alias changes.

The first example says *allows a user*, but it should be probably be *allows users*, since it's not a permission a single user has, but all the users with a specific role.

**Comment by kiamlaluno** [comment]
I updated the warning sentences to make them similar to other warning sentences used by other modules. In this way, I avoided to use *users*.

**Comment by olafgrabienski** [comment]
Thanks for the update, @kiamlaluno . I like the phrases you found, e.g. `Allows to edit already approved comments` instead of `Users could edit ...`.

**Comment by klonos** [comment]
Thank you @kiamlaluno 🙏🏼 ...I've left some suggestions in the PR. Mainly changing "Allows to do..." to "Allows doing...", as it seems to be the correct way to use the verb "allow" in those cases (see https://english.stackexchange.com/questions/60271/grammatical-complements-for-allow/60285#60285). I hope I'm not misinterpreting things.

Can others (preferably those with English as their primary language) have a look at the PR and chime in?

**Comment by jenlampton** [comment]
I think the permissions warning is intended to indicate when one person has permission to change or delete content (or similar) created by other people, so `Skip comment approval` and `Edit own comments` probably wouldn't qualify.  

I do think we will improve those permissions by being more specific in their titles, however, and I like the recommendations. I'll review the PR tomorrow and see if I can help with the grammar.

**Comment by jenlampton** [comment]
I reviewed the PR and all the grammar looks great 👍 

The description for `Skip comment approval` still needs work, and I put another suggestion on the PR: 

`Allows comments to be posted without approval, becoming immediately visible to everyone. Because spam and offensive comments are common, this permission should only be granted to those who are trusted, or on a site with additional spam protection measures in place.`

This is probably way too long...  what if we updated both the title and the description?

title: `Skip comment approval: comments will be immediately visible to everyone. `
description: 
`Because spam and offensive comments are common, this permission should only be granted to those who are trusted, or on a site with additional spam protection measures in place.`

Hm, that probably still needs work.

**Comment by kiamlaluno** [comment]
I changed the code as suggested. I hope I understood correctly.

**Comment by klonos** [comment]
@kiamlaluno the PR sandbox is gone (they are automatically deleted after sometime - something like 45 or 60 days I think). Can you please close the PR, then wait 10sec or so, then reopen it? That should trigger the creation of a new sandbox.

Thanks.

**Comment by kiamlaluno** [comment]
@klonos It worked: The preview has been re-generated.

**Comment by kiamlaluno** [comment]
I synchronized the PR fork with the main repository. Now the coding standards tests fails, but it is because `phpcs` is not found.

**Comment by stpaultim** [comment]
WAS:

> Because spam and offensive comments are common, this permission should only be granted to those who are trusted, or on a site with additional spam protection measures in place.

SUGGESTION:

> To control spam, limit this permission to those who are trusted or be sure to enable additional spam protection.

**Comment by stpaultim** [comment]
Note, while testing this PR I found that none of the MORE links are working on the permissions page. This is not specific to this PR, it's true in Demo Sandboxes and my local dev site. I opened a new issue. 

https://github.com/backdrop/backdrop-issues/issues/6053

**Comment by kiamlaluno** [comment]
I have updated the PR. The failing tests are the usual ones, not related with the changes introduced here.

**Comment by stpaultim** [comment]
I've marked this "WFM." ` 

I see that earlier langage about SPAM has been removed. I think it's good either way. I would mark this RTBC, but I think it's better that someone else look at the code first. Personally, I'm not sure what the new `'restrict access' => TRUE,` statement is doing.

**Comment by kiamlaluno** [comment]
I have synchronized the PR with the 1.x branch. Tests are running right now.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno for your continued effort to make this change happen. I merged https://github.com/backdrop/backdrop/pull/4163 into 1.x and 1.26.x.

https://github.com/backdrop/backdrop/commit/9a463a2c7a5602c8162315452b76246653db6227 by @kiamlaluno, @stpaultim, @jenlampton, @klonos, @herbdool, @argiepiano, @olafgrabienski, and @BWPanda.
