### ISSUE TITLE
Some default layouts are never installed during a D7 Standard upgrade 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5558]
## Description of the bug
When upgrading a D7 Standard profile installation, the layouts `home` and `dashboard` are not installed. The config files `layout.layout.home.json` and `layout.layout.dashboard.json` are not moved to the site's config directory.

## Steps To Reproduce
1. Upgrade a D7 Standard site
2.  Visit Structure -> Layout to verify that Home and Dashboard are not listed
3. Visit the site's config folder inside `files/`: `layout.layout.home.json` and `layout.layout.dashboard.json` are not present

## Actual behavior
Those two layouts are not installed

## Expected behavior
Like in a clean Backdrop installation, the upgrade should also install those default layouts. 

## Additional information
A workaround for Dashboard is to completely disable AND uninstall the module and re-install it 

There is no UI workaround for Home. Manually, you can move the default file `layout.layout.home.json` from the `core/profiles/standard/config/` to your site's files config folder and clear caches.

The other 2 default layouts ARE installed normally (`default` and `admin_default`). Unlike Home and Dashboard, those two config files live in the `layout/config` folder and are at some point copied into your site's config folder when the Layout module is enabled during the upgrade process. 

On the other hand the layouts Home and Dashboard live in the `standard/config` and  `dashboard/config` folders. Modules `standard` and `dashboard` are never fully enabled in upgrade process, since they WERE already enabled in the D7.

As a possibly fix, we could create hook_update_N hooks both in `dahsboard.install` and `standard.install` that would be run during the upgrade process?  Although this would be a partial fix to a bigger problem (the D7 upgrade process presents many unsolved issues, this being one of them).

Backdrop version: 1.21.4
PHP: 7.4.21

**Comment by indigoxela** [comment]
I do have a concern regarding the home layout, though. The D7 site may have a completely different setup, the home/front page may be anything, like a view, the default blog, a node (possibly with translations)...

Enabling the home layout will override that - I'm not sure if that's smart. It might at least lead to some confusion. The home layout ships with the standard profile, so it's only supposed to be enabled on *fresh* installs.

The dashboard could be OK to enable.

**Comment by argiepiano** [comment]
@indigoxela these are good points. But:
- If your D7 home page looked a special way because of a D7 theme, you won't have that in Backdrop anyway, regardless of the Home layout
- If your D7 home page looked special because of a custom page.tpl.php template... those are not included in the upgrade, so you'll end up with a completely different look regardless of the Home layout
- If your D7 home page was a view, that view will be upgraded, and the Home page will not be in effect (maybe? haven't tested it) 

As for your point re: Dashboard. Dashboard is automatically enabled during the current upgrade process, regardless of whether it was enabled or disabled in your D7 site. But, there are additional issues with Backdrop Dashboard after upgrade. See #5529. The module is enabled, but the menu link is not shown, and the path `admin/dashboard` don't exist despite the fact that it's enabled.

**Comment by argiepiano** [comment]
And one more thing regarding your concern about overriding D7's page setups: the upgrade process DOES create la Backdrop default layout (using Moscone Flipped), which will effectively override any D7 setup for internal pages.     So this override is already happening for internal pages after the upgrade.

**Comment by argiepiano** [comment]
Upon further examining `system.install` I realized that the absence of the `home` and the `dashboard` layouts may be by design. Check out `system_update_1025()`, where `default` and `admin_default` are created (but not home and dashboard). Further, `system_update_1059()` and `system_update_1060()` seem to indicate that `home` layout may not exist. 

Closing this as "works as designed"
