### ISSUE TITLE
Document `hook_schema_0()`

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5560]
`hook_schema_0()` is invoked by `update_module_enable()`. This hook is currently not documented anywhere.
 It provides an initial table schema for modules that are enabled during update/upgrade processes. Unlike `hook_schema()`,  all `hook_update_N()` will be run after `update_module_enable()` creates the table with `hook_schema_0()`. 

As per @bugfolder's [suggestion](https://github.com/backdrop/backdrop-issues/issues/5499#issuecomment-1074128878) in issue #5499, the best place for this documentation is `system.api.php`

**Comment by argiepiano** [comment]
PR ready for review:
https://github.com/backdrop/backdrop/pull/4006

**Comment by bugfolder** [comment]
This looks fine (code reviewed), but one request: would you add `@see hook_schema_0()` to the docblock of `hook_schema()`, so that they're appropriately cross-linked?

**Comment by argiepiano** [comment]
Thanks, @bugfolder. Added to the PR

**Comment by bugfolder** [comment]
Testing LGTM, code WFM. RTBC.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4006 into 1.x and 1.21.x.
