### ISSUE TITLE
Fixed: `_views_tokenized_clean_css_identifier()` should clean the complete class.

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop/backdrop-issues#5561]
## Description of the bug

The function [_views_tokenized_clean_css_identifier](https://docs.backdropcms.org/api/backdrop/core%21modules%21views%21views.module/function/_views_tokenized_clean_css_identifier/1)($class, $plugin, $row_index) splits classes into string and token parts, replaces the tokens with their values and then (wrongly) cleans the separated parts with [backdrop_clean_css_identifier](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_clean_css_identifier/1). This can result in unexpected replacements, e.g. if the token [nid] is replaced with a node id (e.g. "123"), then this part would be "cleaned" to "_23". 
This breaks functionality of e.g. contrib module ip_geoloc which relies on a row class ".sync-id-[nid]". This contrib module is half-ported on https://github.com/backdrop-contrib/ip_geoloc. I'm trying to make it work, but this bug is preventing it.

## Steps To Reproduce

To reproduce the behavior:
1. Create a View from content nodes with Table display
2. Add the nid field
3. In Table Settings, add a row class ".sync-id-[nid]"
4. Check the HTML output of the table

## Actual behavior
The row classes of the table are not correct, e.g. for nid = 123 the row class is ".sync-id-_23"

## Expected behavior
The row classes of the table should be correct, e.g. for nid = 123 the row class should be ".sync-id-123"

## Additional information
- Backdrop CMS version: 1.21.4

I suggest to correct the function _views_tokenized_clean_css_identifier in views.module like this:

```
function _views_tokenized_clean_css_identifier($class, $plugin, $row_index) {
  if (!empty($class)) {
    // To support a class that is part hand-typed and part token, split out tokens.
    $subclasses = preg_split('/(\[[^\]]*])/i', $class, -1, PREG_SPLIT_NO_EMPTY | PREG_SPLIT_DELIM_CAPTURE);
    foreach ($subclasses as &$subclass) {
      $subclass = $plugin->tokenize_value($subclass, $row_index);
    }
    $class = implode('', $subclasses);
    return backdrop_clean_css_identifier($class);
  }
}
```

**Comment by indigoxela** [comment]
Funny, I never ran into this before, but can confirm it: if classes get directly assembled with tokens, one can end up with `foobar-_5` instead of `foobar-15`.

And I did a quick check, this is no problem with D7 views.

Seems like this issue here is a follow-up to #3428.

@AlexHoebart-ICPDR your approach seems promising. Mind to file a pull request?

**Comment by AlexHoebart-ICPDR** [comment]
OK, first time for me, here is the PR: https://github.com/backdrop/backdrop/pull/4011

**Comment by indigoxela** [comment]
> ... first time for me, here is the PR

That's great! Welcome to the Backdrop contributors gang.

I took a look at the code change, and at first it looked good, but playing with it locally, I found a regression.

Previously underscores in typed text stayed untouched, but now they're converted to dashes. That's what the previous issue tried to address. (#3428)

- This is what I played with: `foobar-[nid]--[nid] the_second_class`
- This is what I expected: `foobar-12--12 the_second_class`
- But instead I got: `foobar-12--12 the-second-class`

I'd like to note that the current code is already a slight improvement, as without it I end up with `foobar-_2___2 the_second_class`. :wink: But it still needs some work.

**Comment by AlexHoebart-ICPDR** [comment]
@indigoxela but that's a different problem and handled in function backdrop_clean_css_identifier. By default, it replaces underscores with dashes "using Backdrop's coding standards". I assumed that this is the expected behaviour.

To achieve your expected result, the PR could be changed to call the cleaning with an empty array as second parm: backdrop_clean_css_identifier($class, array());

But I don't know if that is what is expected in "Backdrop's coding standards" - is there some explanation on this?

**Comment by indigoxela** [comment]
I'm aware this is tricky and I don't have an instant suggestion.

You can't apply backdrop_clean_css_identifier() without filters on tokenized values, but you're supposed to do it with written values. They need to get treated differently, but if you apply backdrop_clean_css_identifier() directly on parts, values get mangled.

Honestly, no clue what the "Backdrop's coding standards" mean in this context. :wink:

What we have to take care of is that existing classes (out there) don't change after an update, because that has a potential to break things.

**Comment by AlexHoebart-ICPDR** [comment]
I changed the approach in the PR to only fully clean the token values, but not the input string values (as per #3428). So, this should be BC now.
I also changed the variable name $subclasses to $substrings as this better describes its content.
I tricked the function backdrop_clean_css_identifier a bit to avoid the bug described in this issue.
A cleaner approach could be to add a parameter to backdrop_clean_css_identifier() to distinguish between checks of full or partial identifier strings. But that would have more implications elsewhere, maybe.

**Comment by indigoxela** [comment]
A temporary prefix - nice.

I'll try to test it soon, but I saw some coding standard issues. (This time it's the [php coding standard](https://docs.backdropcms.org/php-standards).) ... Spaces, comments and the like. I'll add some explaining comments on your PR.

**Comment by AlexHoebart-ICPDR** [comment]
Coding standards, well, ok, done. 
BTW, they don't mention a line length limit for comments, only for code and there is also an original comment line longer 80 chars.
But thanks for your guidance.

**Comment by AlexHoebart-ICPDR** [comment]
I received this: https://github.com/backdrop/backdrop/actions/runs/2033774926
But I have no clue how that "Module uninstallation" error is related to my code change. 
Please advise...

**Comment by indigoxela** [comment]
> ... they don't mention a line length limit for comments ...

I belief, we have a documentation issue for this somewhere, just can't remember where.
Standards are mostly the same as in Drupal, with some small differences. So if you have phpcs with the Drupal ruleset installed on your dev, you can use that as well. (Yes, we have lots of legacy code that doesn't comply to the standards yet, but we improve things as we go.)

> I received this ... But I have no clue ...

I also see no relation. This might be a false negative. What we usually do when in doubt is to "turn it off and on again" - close the PR, wait a minute or two, then re-open it. In most cases the test passes then.

I did a quick check in the sandbox - yes, it works. :+1:

**Comment by indigoxela** [comment]
Hm, tried to kick the tires by restarting the PR check runs ... and now another random test fails.

Anyway, it works for me.

**Comment by docwilmot** [comment]
This fails Forum NG tests; we need a `[tid]` replacement pattern in Views to identify forums in tables.

**Comment by docwilmot** [comment]
I've rebooted and all tests pass except coding standards which seem unrelated.
Tested the code again, including starting with a numeric replacement token, and it works as expected. 
RTBC from me.

**Comment by quicksketch** [comment]
Seems good to me too. I merged https://github.com/backdrop/backdrop/pull/4011 into 1.x and 1.23.x. Thanks @AlexHoebart-ICPDR for your work on this! Big thanks to @indigoxela and @docwilmot for reviewing and preventing any regressions.
