### ISSUE TITLE
Is version 2 of a module supposed  to be listed as an "available update"  from version 1? 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5562]
I'm seeing a situation with a module that has a new major version  (version 2).  On sites that have the major version 1 installed,  Backdrop is not listing version 2 as an "available update". Is this by design, or is this a bug? 

If this is by design, is there a way to indicate that version 1 is unsupported or trigger a warning? I saw this functionality in D7 with contrib modules like Weight, were version 2 stopped being developed and the maintainer  strongly recommended upgrading to version 3. There was a warning in the Status report about unsupported modules, and you could use the installer to upgrade.

**Comment by argiepiano** [comment]
One inconvenience of this behavior is that you can't use Project Installer to install the next major version of a module. You are forced to uninstall and manually remove the old major version from the modules folder, and then install the next major version. 

With Drupal 7, if the version was unsupported, you could use  the installer to upgrade.

**Comment by BWPanda** [comment]
Looks like a bug: https://github.com/backdrop/backdrop-issues/issues/5563

**Comment by BWPanda** [comment]
Let's close this in favour of that issue.
