### ISSUE TITLE
Missing a possibility to get a books mlid value for views

### ISSUE THREAD

**Issue by schoenid** [backdrop/backdrop-issues#5565]
## Description of the need

To create a books child content, the parent books mlid (menu link ID) is required.
With help of this ID it's possible to create a link, which let's make a new book child using the Prepopulate module and the mlid value.
The created link has to look like `/node/add/book?parent=[!mlid]`.

## Proposed solution

Add a views entry to file: book.views.inc

section:

    // menu_links table ...
    ...
    $data['book_menu_links']['mlid'] = array(
        'title' => t('mlid'),
        'help' => t('The mlid of the book page.'),
        'field' => array(
            'handler' => 'views_handler_field_numeric',
            'click sortable' => TRUE,
        ),
            'sort' => array(
                'handler' => 'views_handler_sort',
        ),
    );

## Alternatives that have been considered

none

## Additional information

It's working on manually patched versions.

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes providing books menu link IDs to be used on Views.

PR: https://github.com/backdrop/backdrop/pull/4064

**Comment by herbdool** [comment]
@schoenid thanks for the PR. The code looks fine (I made a small tweak to the description). But you made the PR to the wrong branch. Can you redo the PR from your fork/branch to Backdrop 1.x branch? Otherwise we won't be able to merge this.

**Comment by schoenid** [comment]
Thanks @herbdool 
I've tried to re-adress the PR to 1.x ... is this ok?

**Comment by herbdool** [comment]
@schoenid you may need to fix it a bit more. I see now that it's including all the commits unrelated to this. I think you may need to fix this by rebasing your branch from the backdrop 1.x branch and forcing a push to your branch. Not sure if that makes sense to you. If not you can also close this PR and start fresh.

**Comment by schoenid** [comment]
@herbdool  - Thanks.
It's hard to learn.  I've changed it back.
So I've recreated the PR ...

**Comment by BWPanda** [comment]
I feel the need to push back on this PR for the following reasons:

1. Getting the Menu Link ID is already possible using the [Menu Node Views](https://github.com/backdrop-contrib/menu_node_views) contrib module.

2. Even if we do include the mlid in this PR, it should be renamed, as 'mlid' isn't intuitive/obvious.
![image](https://user-images.githubusercontent.com/2385329/172598648-248db924-f9cd-4319-8990-48db91d55dc7.png)

3. What I feel would be *more* useful to add to views is the Book ID. This is what the select list uses, and it's currently not available in views...
![image](https://user-images.githubusercontent.com/2385329/172598424-4876eeb0-2e4f-4fa7-b528-1421c29f32e5.png)

So marking this 'needs work'.

**Comment by schoenid** [comment]
@BWPanda 

> Getting the Menu Link ID is already possible using the [Menu Node Views](https://github.com/backdrop-contrib/menu_node_views) contrib module. If we want that in core, let's do it (in a separate issue) in a more generic way.

Unfortunately getting the "Menu Node Views" Menu link id does NOT provide the books internal mlid.
![image](https://user-images.githubusercontent.com/15383666/172712823-0799a5ae-98f1-4c1e-a4c4-135fd05d679e.png)

Please have a look to the produced output:
![image](https://user-images.githubusercontent.com/15383666/172713019-3c23969d-5669-48d6-bd10-bf14f09c4fda.png)

`Book: mlid` (Subject of this PR) creates the required mlid.
`Global: View` creates the "Add Child ..." link.
`Menu: Menu link id` creates nothing.

The difference:
Please be aware, that the Menu Link iD from the  [Menu Node Views](https://github.com/backdrop-contrib/menu_node_views) contrib module delivers just the Link ID, under which the books page is registered in a menu, if it is at all.
The books mlid is a books internal value as part of the hierarchy.

The books mlid is required to create a child page of a book. It is the reference to the future parent of a newly created book page.

Some additional data:
`Global: View` in the views field delivers the values for gid (Group ID) as %1 and mlid (Books menu link ID) as %2 to another view as contextual parameters, which then rewrites the output of the actual content title with Text: "Add Child ..." as a link to "/node/add/book?edit[og_group_ref][und][0][default]=%1&parent=%2". I have to do this that way, because of permission checks for the current user. Otherwise the task could be done directly, without the call of another view. 
Calling the above link creates then a child book to the existing book, from where it is called.
![image](https://user-images.githubusercontent.com/15383666/172717539-8db8867d-a18f-4881-b8f8-ccba947244b1.png)

**Comment by schoenid** [comment]
@BWPanda 

> What I feel would be more useful to add to views is the Book ID. This is what the select list uses, and it's currently not available in views...

It would be nice to have, yes.

I don't find any real reason, why to have it in a view. Unless the books "Menu link ID", it is not required to create, edit or delete something with relation to a book, which can't be done with the presence of the books node ID.

**Comment by schoenid** [comment]
@BWPanda 
> Even if we do include the mlid in this PR, it should be renamed, as 'mlid' isn't intuitive/obvious.

Could you provide a suggestion?

With the entry "Menu link ID" it is subject for confusion, because many (like you?) will think, that it has something to do with menus ... but mlid is the original designation used in books and also visible in the DEVEL view, so anyone that is working on such things, knows exactly, what it is. 

Even "Content: Nid" is used for Content: node ID. 
So can we call it "Book: Mlid"? (a capital "M" instead a small one ... like on "Nid" ...?)
However I would prefere the small "mlid", since it's more authentic.

**Comment by herbdool** [comment]
Looks good to me!

**Comment by quicksketch** [comment]
Thanks folks! This seems like a pretty minor addition. I've merged https://github.com/backdrop/backdrop/pull/4064 into 1.x and 1.22.x. Though technically a new feature, I don't see how this could do any harm.
