### ISSUE TITLE
Fixed: Admin bar's 'search' component doesn't work if 'menu' component is disabled.

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#5567]
## Description of the bug

If you disable the 'Management menu' component of the Admin Bar, the 'Search bar' component no longer works. This was discovered in https://github.com/backdrop/backdrop-issues/issues/220

![image](https://user-images.githubusercontent.com/2385329/160276237-89a45f7c-047b-4e81-b1f4-a71f637f4244.png)

## Steps To Reproduce

To reproduce the behavior:
1. Go to `/admin/config/administration/admin-bar`
2. Make sure all components are enabled
3. Use the menu search to see that/how it works
4. Disable the Management menu component
5. Try the search again

## Actual behavior

Nothing happens - no drop-down list of results, and pressing 'Enter' doesn't show results either

## Expected behavior

Drop-down list of results show below search bar and/or pressing 'Enter' shows page of results.

## Proposed solution

Making the search work independently of the menu would (I imagine) be a massive undertaking, so as a simpler, more immediate solution to avoid this WTF moment, I suggest making the search checkbox only show when the menu checkbox is checked (using `#states`).

**Comment by BWPanda** [comment]
Oh, and here's a screencast of the issue:

![Peek 2022-03-27 20-57](https://user-images.githubusercontent.com/2385329/160276474-36d30c45-e929-4820-9b7c-99a60c710b84.gif)

**Comment by BWPanda** [comment]
Here's a PR that fixes that: https://github.com/backdrop/backdrop/pull/4024 Basically makes it so that you can't have the search bar enabled without the menu also being enabled.

![Peek 2022-03-27 21-18](https://user-images.githubusercontent.com/2385329/160276936-f35d927f-1de4-4691-9787-09094b11622f.gif)

**Comment by olafgrabienski** [comment]
> you can't have the search bar enabled without the menu also being enabled

Thanks for the PR, works like a charm in the sandbox!

I'd suggest to make the relation between menu and search box on the configuration page even more clear:

- Rename "Search bar" on the config page to "Menu search" (like the placeholder text of the search box).
- Group the related settings somehow visually. See an example as mockup in the screenshot below.

**Mockup:**

![backdrop-pr4024-admin-menu-settings](https://user-images.githubusercontent.com/14188307/160347217-283950c4-d8b4-490c-8f3c-988cc32c20b9.png)

**Comment by BWPanda** [comment]
I see where you're coming from @olafgrabienski, but I disagree with your suggestions. The components are already being renamed as part of https://github.com/backdrop/backdrop-issues/issues/5284, and I don't think putting one checkbox horizontally next to another 'groups' them, especially when we have multiple other places in core where dependent fields are displayed below their 'parent'.

**Comment by olafgrabienski** [comment]
> The components are already being renamed as part of https://github.com/backdrop/backdrop-issues/issues/5284

Oh, I wasn't aware of that issue. Even better!

> we have multiple other places in core where dependent fields are displayed below their 'parent'

I see! In my opinion, some way of visual grouping could still be useful here, but I don't know if we already have a suitable pattern for cases like this one, and I'm perfectly fine not doing that here.

**Comment by BWPanda** [comment]
> In my opinion, some way of visual grouping could still be useful,

I agree, but not sure how best to do this. Only thing I can think of is indenting it slightly, but even that doesn't look like anything else we have in core...

![image](https://user-images.githubusercontent.com/2385329/160382463-1c343dd3-baec-40c0-a1ea-ccf6a26b56da.png)

**Comment by olafgrabienski** [comment]
> indenting it slightly, but even that doesn't look like anything else we have in core...

Yep, so don't let us handle the grouping issue here. We can always open a separate issue for it.

**Comment by jenlampton** [comment]
Code looks great, RTBC from me -- but let's make a follow-up issue to handle the grouping.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4024 into 1.x and 1.21.x. Thanks @BWPanda, @olafgrabienski, and @jenlampton!
