### ISSUE TITLE
Files don't upload if a content type has more than one file field

### ISSUE THREAD

**Issue by kswan** [backdrop/backdrop-issues#5569]
## Description of the bug

Files don't upload if a content type has more than one file field.

## Steps To Reproduce

To reproduce the behavior:
1. Open a clean install of backdropcms or create a sandbox
2. Add a file field (File1) to the Page content type (leave all default settings)
3. Add a file field (File2) to the Page content type (leave all default settings)
4. Create a new page content.
5. Select a file in File1. 
6. Select a file in File2.

## Actual behavior

File1 uploaded as expected.
File2 doesn't upload.
![Screenshot 2022-03-30 8 40 13 AM](https://user-images.githubusercontent.com/154391/160848534-31071178-7ee4-4029-99fb-08af60a1764f.png)

## Expected behavior

File2 should upload

## Additional information

I confirmed this in BackdropCMS 1.21.4.
Confirmed browsers Chrome and Edge.
If I disable Javascript in the browser, the files upload correctly using the "Upload" button.

**Comment by kswan** [comment]
@indigoxela, yes, the file is uploaded when the node is saved. My problem is that I have multiple files per field that need to be uploaded so the only way is to use the preview multiple times or multiple saves.

I was looking at #4284 as well. I agree that it looks like the same issue.

**Comment by kswan** [comment]
I was looking at core/modules/file/js/file.js and noticed this at line 135:
    // Temporarily disable upload fields other than the one we're currently
    // working with. Filter out fields that are already disabled so that they
    // do not get enabled when we re-enable these fields at the end of behavior
    // processing. Re-enable in a setTimeout set to a relatively short amount
    // of time (1 second). All the other mousedown handlers (like Backdrop's
    // Ajax behaviors) are excuted before any timeout functions are called, so
    // we don't have to worry about the fields being re-enabled too soon.
    // @todo If the previous sentence is true, why not set the timeout to 0?

My understanding of Javascript is very weak so I don't know if this could be sticking in the disabled mode, but this looks suspicious to me.

**Comment by indigoxela** [comment]
I'm pretty sure this is the same bug as in #4284, but I hesitate to close this one as duplicate, because it's about a different field type.

@kswan what do you think?

Yes, it's a Javascript bug, which means, we probably have nobody here to fix it.

**Comment by indigoxela** [comment]
@kswan the [other issue](https://github.com/backdrop/backdrop-issues/issues/4284) does have a PR! Mind to give testing a try?

**Comment by indigoxela** [comment]
I just realized, the other issue has label "RTBC". So I guess, we can close this one. That PR will also fix the problem reported here.
