### ISSUE TITLE
Search form does not allow to be styled using icons

### ISSUE THREAD

**Issue by schoenid** [backdrop/backdrop-issues#5573]
## Description of the need

Sometimes it's required to use a search symbol instead of text in the search forms button. A possibility to use FontAwesome or locally stored icons would be practical.

Because for the search form button a `<input type="submit">` is used, it's not possible to style it, using pseudo elements like `:before` or `:after`.

## Proposed solution

It't would be required, to use a `<button type="submit">` instead. This would also be better for semantic reasons.

## Alternatives that have been considered

An alternative could be to create a view or custom block, which replaces the "Search form" block.

There is also a module [Custom Search](https://backdropcms.org/project/custom_search) which allows to add an image to the Submit button, but not to use FontAwesome.

Another possibility if only a picture is required: add a backgound like `.class { background: url('path/icon.svg'); }`.
You have to realize, that `background-image:` does not work! (which makes no sense though ...).
This works also not for FontAwesome or other symbol libraries.

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now allows to style the Search Form Sumit Button.

**Comment by BWPanda** [comment]
I think there are workarounds for doing this (the ways you mentioned, https://stackoverflow.com/questions/30577777/how-to-add-font-awesome-icon-into-input-button, etc), plus there's the option to override the theming of the existing search box/button (so you can use whatever HTML you want), so I'm not sure there's a need to change this... Happy to get feedback from others though.

**Comment by BWPanda** [comment]
For example, to override/customise the current search form, looks like you'd do a `hook_form_alter()` on https://docs.backdropcms.org/api/backdrop/core%21modules%21search%21search.module/function/search_box/1

**Comment by indigoxela** [comment]
As an alternative you can do it via pure CSS. An example is provided by the [Snazzy contrib theme](https://github.com/backdrop-contrib/snazzy/blob/1.x-2.x/css/components/search.css).
![search-block-styled](https://user-images.githubusercontent.com/842066/161418878-a8470012-8290-4f3a-96a9-5cfa7cbf2edf.png)

Adding a complete (big) font for only one icon seems a bit overdone. :wink:

**Comment by schoenid** [comment]
Thanks @BWPanda - The stackoverflow method requires to have access to the way, the HTML code is created, means to know, how and where in PHP ... even the `function search_box`: I don't really understand, what happens there. This is for programmers or developers, not for users or designers. 

Thanks @indigoxela - This is the way I was looking for: Putting a box with the icon over the search button, lift the original search button in the z-axis and make it completely transparent. So this is solved.

About:

> Adding a complete (big) font for only one icon seems a bit overdone. 😉

You're right. I thougt about that only if using it anyway for other icons too.
Actually I'm just using a SVG icon (3kB).
