### ISSUE TITLE
Fixed: Documentation clarification on system_settings_form.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5574]
As reported by @ElusiveMind in https://github.com/backdrop-ops/docs.backdropcms.org/issues/199:

On the following page:

https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_settings_form/1

There are references to 'default_setting' that should be 'default_value' in the example code.

Also - `settings_config` should be renamed `primary_config` in the example as well.

**Comment by bugfolder** [comment]
No testing needed, it's only a docblock edit.

**Comment by ElusiveMind** [comment]
This looks good and tests pass on this end.

**Comment by indigoxela** [comment]
@ElusiveMind many thanks for reviewing, so it's RTBC. :+1:

**Comment by quicksketch** [comment]
Ah, what a nice easy one. Thanks @bugfolder, @ElusiveMind, and @indigoxela! Merged into 1.x and 1.21.x.
