### ISSUE TITLE
Add ability to skip running tests on PR

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5575]
## Description of the need

Sometimes a PR makes changes that doesn't require running tests on; e.g. documentation-only changes. In these cases, it'd be nice to save time by being able to skip the automated tests.

## Proposed solution

Update our GH action to only run if a certain keyword/phrase isn't present in the PR title/commit message (e.g. [skip ci], [skip tests], etc.). So you'd make your documentation-only PR with the message `Issue #12345: Fix typo in README [skip tests]`, and then the test suite wouldn't run for that PR.

It seems that a simple if condition in the GH action will achieve this: https://github.com/veggiemonk/skip-commit#just-use-yaml-recommended

## Alternatives that have been considered

I believe those with the right permissions/access can cancel a workflow, but there are 9 workflows that make up our test suite, so it'd be nice if this was automated instead.

## Additional information

Related: https://github.com/backdrop/backdrop-issues/issues/4607

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now allows skipping CI tests in PRs by adding `[skip tests]` to the PR title.

**Comment by BWPanda** [comment]
So it seems that GitHub already supports skipping the CI process entirely using certain strings like `[skip ci]`: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

However that skips everything, not just tests. Is there a use-case for skipping tests but not Tugboat? Or once we have code formatting checks in there too, it might be nice to still check the code formatting, but not run all tests... So I still think it'd be nice to implement this more selectively ourselves.

However since the current PR doesn't appear to be working, marking as 'needs work'.

**Comment by BWPanda** [comment]
Ha, fixed it! [This PR](https://github.com/backdrop/backdrop/pull/4036) is even its own example of how it works:

![image](https://user-images.githubusercontent.com/2385329/161693538-36a518cf-951d-40c5-a19a-864117188674.png)

For the life of me I couldn't work out how to get the commit message, so I did it based on the PR title instead. So what this does is makes it so that if the PR title contains `[skip tests]`, the test suite will be skipped. Since the PR title is usually based on the initial commit message, this'll work if you add the tag there too. Also, we can edit the PR title as necessary to enable/disable tests on subsequent commits to a PR (e.g. if someone submits a documentation-only PR but forgets the tag, we can add it manually to the title, then any subsequent commits won't trigger tests).

**Comment by bugfolder** [comment]
Nice! Just added a label to remind to document this bit of magic, probably under "Working on issues" on https://docs.backdropcms.org/documentation/how-to-use-the-core-issue-queue (since that's where PRs are mentioned).

**Comment by klonos** [comment]
@BWPanda I have noticed that if the commit message is too long GH trims it after a certain point, and adds the remaining/trimmed portion at the beginning of the first comment in the PR. For that reason, perhaps it would make sense to advise that `[skip tests]` is added to the beginning of the commit message.
