### ISSUE TITLE
Function language_uninstall() should be changed to language_disable()

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5577]
Hello All,

## Description of the bug

The `config_get('system.core', 'language_count')` returns more than 1 language if you disable the Language module on a  multilingual Backdrop site.

## Steps To Reproduce

To reproduce the behavior:
1. Enable the Language Module go to `admin/config/regional/language` and add additional language(s)
2. Disable the module
3. Call the `config_get('system.core', 'language_count')` to get more than 1 language count.

## Expected behavior

The [following lines](https://github.com/backdrop/backdrop/blob/5c425354833ac7f7a8dd6fd3670694c1c110b5ca/core/modules/language/language.install#L16-L30):

```
/**
 * Implements hook_uninstall().
 */
function language_uninstall() {
  // Restore core language variables to defaults.
  $config = config('system.core');
  $config->set('language_default', 'en');
  $config->set('language_count', 1);
  $config->save();


  // Re-initialize the language system so successive calls to t() and other
  // functions will not expect languages to be present.
  backdrop_static_reset('language_default');
  backdrop_language_initialize();
}
```

work as expected if you uninstall the module. However, there could be cases when owners of multilingual Backdrop websites do not want to loose language-related custom settings (such as number of languages added, translation progress, etc.), but for various reasons need to temporarily revert to a single language state by just disabling the module.

Unfortunately, in this kind of cases all calls to the `config_get('system.core', 'language_count')` function in custom or contributed modules would return an incorrect number of the languages.

To address this problem I wanted to suggest to add additional `function language_disable()` in the [language.install ](https://github.com/backdrop/backdrop/blob/1.x/core/modules/language/language.install) file, however since uninstalling any module comes only after disabling it first, I thought it would be just unnecessary duplication of the same lines.

I am not sure if the community wants simply rename the existing `language_uninstall()` function to `language_disable()`. On a test setup doing so works as expected. Let me know what would be the best approach and I will file a PR.

**Comment by BWPanda** [comment]
I'm not sure... I feel like when disabling a module but not uninstalling it, you expect config to remain in place. So that's by design, not a bug.

If people do the with the intention of removing the functionality but keeping a backup of it, then I think they should instead backup the relevant config files and then disable and uninstall the module.

**Comment by alanmels** [comment]
Fair enough, I will just check if module is disabled instead of using the `config_get('system.core', 'language_count')` function.
