### ISSUE TITLE
Generated .htaccess file missing newline at EOF

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5579]
## Description of the bug

If you delete the `.htaccess` file in the `/files` directory, after clearing caches it'll automatically be re-created. 👍🏻 
However the re-created (aka generated) version is missing a newline at the end of the file. This causes git to show it as a changed file. 👎🏻 

## Steps To Reproduce

To reproduce the behavior:
1. Make sure you're on the `1.x` branch and are up-to-date (no changes in git)
2. View the `/files/.htaccess` file, note the newline at the end of the file
3. Delete `/files/.htaccess`
4. Clear caches
5. Confirm `/files/.htaccess` has been re-created automatically, view the file

## Actual behavior

There's no newline at the end of the file and `git status` shows it as a changed file.

## Expected behavior

Newline should be present and no changes shown in git.

## Additional information

It looks like the newline was removed accidentally during the addition of PHP7 code in https://github.com/backdrop/backdrop/pull/3596

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/4040

**Comment by indigoxela** [comment]
Tiny and straight forward fix. RTBC :+1:

**Comment by BWPanda** [comment]
Thanks @indigoxela. Since this is such a small change, based on the fact that tests are passing and you RTBC'd it, I've gone ahead and merged https://github.com/backdrop/backdrop/pull/4040 into 1.x and 1.21.x.
