### ISSUE TITLE
'Page not found' when trying to delete field

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5580]
## Description of the bug

If you're on the configuration page for a field that's attached to an entity other than a node (e.g. user account, taxonomy term, file entity), and you click the "Delete field" button at the bottom of the page, you'll get a "Page not found" error.

Doing the same thing for node fields works fine however, as does deleting any entity type's field via the drop-button on the Manage Fields page.

## Steps To Reproduce

To reproduce the behavior:
1. Add a field to a non-node entity (e.g. user account or taxonomy term)
2. On the Manage Fields page for that entity, expand the drop-button for the field and click "Delete"
3. Note that you're on the confirmation form 👍🏻 
4. Go back to the Manage Fields page and instead click "Configure" for the field
5. Scroll down and click the "Delete field" button

## Actual behavior

You get a "Page not found" error. 👎🏻 

## Expected behavior

You go to the confirmation form.

## Additional information

This looks to be a bug in the `field_ui_field_edit_form_delete_submit()` function, where the redirect to the confirmation form is hard-coded to use `admin/structure/types/manage/...` (i.e. the node type pages). I'm not sure how you'd go about specifying a different URL based on the entity type...

**Comment by indigoxela** [comment]
Wow, I can confirm that - verified with a field attached to a File type.

The only explanation why we missed that for so long: all/most people (including me) delete fields via the dropdown button on the "Manage fields" page. However, as the button is there, it should work properly.

**Comment by indigoxela** [comment]
@argiepiano many thanks for your PR - it works! :+1:

I added a textfield to the Document file type, then went to the configure page (/admin/structure/file-types/manage/document/fields/field_foofield) and used the "Delete field" button to remove it. No more 404.

**Comment by BWPanda** [comment]
Nicely done @argiepiano! RTBC.

**Comment by BWPanda** [comment]
Do we want to add a test for the Delete Field button, to make sure this doesn't happen again (having a test for this would have prevented this issue in the first place)...?

**Comment by BWPanda** [comment]
@argiepiano I think we should add a test for this, and I think we can update the field deletion tests too while we're at it.

`testDeleteField()` (in `field_ui.test`) currently:
- Adds a new field to a content type
- Creates a second content type and adds the same field there too
- Deletes the field from the first content type; confirms that instance was deleted but the field still exists
- Deletes the field from the second content type; confirms that instance was deleted and that the field no longer exists

I think we can change it to instead:
- Add a new field to a content type
- Add the same field to the user entity (`/admin/config/people/manage/fields`)
- Click the Delete Field button on the content type's field configuration form, confirm the confirmation form loads
- Delete the field from the content type; confirm that instance was deleted but the field still exists
- Click the Delete Field button on the user entity's field configuration form, confirm the confirmation form loads
- Delete the field from the user entity; confirm that instance was deleted and that the field no longer exists

Are you willing/able to update your PR to do that?

**Comment by argiepiano** [comment]
@BWPanda yes, I can update that test, but it will take me a few days - probably mid-week. Thanks for the suggested steps.

**Comment by argiepiano** [comment]
@BWPanda, I have added code to `testDeleteField()` to verify that the `Delete field` button in the field configuration page for user entities works properly. This required the addition of a helper method to test the actual button. I followed your recommendations in terms of workflow. 

The tests are all passing. Please review.

**Comment by BWPanda** [comment]
Left some suggestions in the PR.

**Comment by argiepiano** [comment]
@BWPanda I have just addressed your suggestions in a new commit. Let me know. Thanks.

**Comment by argiepiano** [comment]
New commit to the PR with some slight tweaks to the test of the `Delete field` button.

**Comment by argiepiano** [comment]
@BWPanda, I agree with all your latest changes/suggestions, and have made additional tweaks to allow test to pass. If you are still willing to work with me on this issue, I will appreciate your review and testing.  Thanks!

**Comment by BWPanda** [comment]
Thanks @argiepiano! Code looks good, but I want to do a final test when I'm back at my computer later. Will RTBC then if all goes well.

**Comment by BWPanda** [comment]
All good. I applied your patch to my local and ran tests. Confirmed all passed. Then I reverted the change to `field_ui_field_edit_form_delete_submit()` and ran tests again, and confirmed that they failed (meaning they correctly pick up the bug here).

So code works and tests work. RTBC.

**Comment by argiepiano** [comment]
Thank you! Can we please get a milestone for this?

**Comment by BWPanda** [comment]
This issue's already in the [1.21.5](https://github.com/backdrop/backdrop-issues/milestone/120) milestone.

**Comment by argiepiano** [comment]
Oops! Thanks

**Comment by quicksketch** [comment]
Looks great! Very nice job @argiepiano, @BWPanda, and @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4042 into 1.x and 1.21.x. :tada:
