### ISSUE TITLE
Error: Cannot access protected property SelectQuery::$alterMetaData

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5582]
## Description of the bug

We're currently trying to port Organic Groups. One of the pain points: EntityFieldQuery::fieldCondition on all OG_AUDIENCE_FIELD fail because it needs to alter the query to point to a different table, which is done via _og_query_og_membership_alter_conditions() / hook_query_TAG_alter(). But in Backdrop SelectQuery::alterMetaData is protected.

## Steps To Reproduce

1. Install OG, add a group and group content type, add content of both
2. Install Devel, try to run below code

```
$foo = new EntityFieldQuery();
$bar = $foo
  ->entityCondition('entity_type', 'node')
  ->fieldCondition('og_group_ref', 'target_id', 3)->execute();
debug($bar);
```
^^ `3` is the node id of the group.

It should return an array containing the node that's content related to the group, but instead one gets:

```
Error: Cannot access protected property SelectQuery::$alterMetaData in og_query_og_membership_alter() (line 1428 of .../modules/og/og.module). 
```

## Additional information

- Backdrop CMS version: 1.21.4
- OG version: latest dev

Possibly related issue: #1868, but I think we inherited that "protected" from Drupal 8, or it has been added before that.

Switching to `public $alterMetaData = array();` fixes the problem.

**Comment by indigoxela** [comment]
Created a PR for discussion: https://github.com/backdrop/backdrop/pull/4043

And to see is something else breaks because of the "public".

**Comment by indigoxela** [comment]
Some links to module code:

[function hook_entity_query_alter()](https://github.com/backdrop-contrib/og/blob/1.x-2.x/og.module#L1405) which adds the "og_membership" tag.

[function og_query_og_membership_alter()](https://github.com/backdrop-contrib/og/blob/1.x-2.x/og.module#L1419) which applies the changes to get the actual membership data (the original field is empty by design, the membership data are stored in a different table.)

**Comment by oadaeh** [comment]
The code should be using the provided [addMetaData()](https://github.com/backdrop/backdrop/blob/9f4d816d2531dc72c4682c8846534546b8dcbee0/core/includes/database/select.inc#L1035) and [getMetaData()](https://github.com/backdrop/backdrop/blob/9f4d816d2531dc72c4682c8846534546b8dcbee0/core/includes/database/select.inc#L1045) methods. We should not be making properties public. That is not the way OOP works. If you need to make properties public to get done what you're trying to do, then either there's something fundamentally wrong with the class or the code using the class and the approach to the problem.

**Comment by argiepiano** [comment]
> The code should be using the provided [addMetaData()](https://github.com/backdrop/backdrop/blob/9f4d816d2531dc72c4682c8846534546b8dcbee0/core/includes/database/select.inc#L1035) and [getMetaData()](https://github.com/backdrop/backdrop/blob/9f4d816d2531dc72c4682c8846534546b8dcbee0/core/includes/database/select.inc#L1045) methods. We should not be making properties public. That is not the way OOP works. If you need to make properties public to get done what you're trying to do, then either there's something fundamentally wrong with the class or the code using the class and the approach to the problem.

While I haven't looked at this in depth, I agree  with @oadaeh.  

You can find a similar example of direct access to that property in Drupal 7's `EntityReference_SelectionHelper_Generic::reAlterQuery()`. In Backdrop, since the property is private, that method was change to use a correct method call to  `addMetaData()`

**Comment by indigoxela** [comment]
Fair enough - could one of you provide a PR for Organic Groups then?

I think the tricky part is that OG needs to change existing meta data (base table), not simply adding conditions.

**Comment by indigoxela** [comment]
Hey, that might actually work!

**Comment by argiepiano** [comment]
@indigoxela I may be able to help with og, but not in the near future. However, from the work I've seen from you, you do such high level work (and so skilled and quick) that I'm sure you'll be able to solve the og issues in a fraction of the time it would take me to study the module 😄

**Comment by indigoxela** [comment]
@argiepiano (and @oadaeh) you already helped me by pointing to getMetaData() - which I wasn't aware of. That was all I needed. The problem is already fixed in og (at least, a PR exists there).
