### ISSUE TITLE
TurnkeyLinux Appliance for Backdrop

### ISSUE THREAD

**Issue by Meunydd** [backdrop/backdrop-issues#5586]
[TurnKeyLinux](https://www.turnkeylinux.org/) is a popular Open Source 'supplier' of ready-made Appliances capable of running on a VM, Cloud or bare metal. Appliances exist for Drupal 7/8/9 but not for Backdrop. A request for a Backdrop Appliance has support from within TurnkeyLinux but would benefit from Backdrop resource/expertise to help build if this can be found. 
See this TKL issue thread, via which contact can be established : [App Suggestion - Backdrop CMS](https://www.turnkeylinux.org/comment/51060#comment-51060)
Such an Appliance would obviously extend the reach of Backdrop and promote its use in the Open Source community.

**Comment by indigoxela** [comment]
Hi @Meunydd,

I'm not sure how we can help you, I'm not familiar enough with TurnkeyLinux. What would you need from our side?

Backdrop is installable via command line the same way as Drupal is (sure, it's a fork). So if you already provide support for Drupal, you might be able to use the same approach.

**Comment by BWPanda** [comment]
I feel this request for assistance would be better in the forum or https://github.com/backdrop-ops/backdrop-community/issues

@Meunydd Would you like to open a discussion there instead?

**Comment by Meunydd** [comment]
Ok
