### ISSUE TITLE
Create option for a cropped image style to provide consistent image size for Cards view

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5593]
## Description of the need

In the discussion of https://github.com/backdrop/backdrop-issues/issues/4903 it has been suggested that our default view of the new card content type would work much better if CORE provided a default image style that is cropped to specific dimensions to provide a more consistent display in views. Originally, we had added a new "cropped" image style to that PR to specifically to address this problem. BUT, this generated a debate over several different approaches, see below.

NOTE: The current thinking is that this issue is NOT a blocker for #4903 and can be addressed at a later date (either in this coming release or in future releases). 

## Additional information

This issue is largely a duplicate of #5590 - except that this issue is focused on a solution to the very specific problem raised by issue #4903 - while issue #5590 is intended to address a broader set of issues beyond those in issue #4903.

## Proposed solution

Let's use this issue to decide which direction folks would like us to go:

1) Update all our default image styles to address this issue as well as other problems with the default image styles (https://github.com/backdrop/backdrop-issues/issues/5590) - close this issue and work on that PR.
2) Create a single new image style that is cropped and works for our view of Cards on front page - leaving the larger issues in #5590 for future. 
3) Update ONLY the large image style (add cropping) specifically to address this issue. 
4) Do nothing - and just let site architects create their own image styles.

Are we missing any other alternatives?

**Comment by BWPanda** [comment]
Ideally I'd prefer option 4 (let people setup/change their own styles if/as needed). But if we really need a cropped image style in core, then I'd say option 2 (add a new one for that purpose).

I oppose options 1 and 3 on the basis the people are used to current image styles as they are, and may not want them to be cropped outside of this specific use case. I know we can change them only for new installs, but that doesn't account for the change people will experience when setting up new sites if they're already used to how this currently works in Drupal/Backdrop.

**Comment by argiepiano** [comment]
I lean toward 2, but 4 would also be acceptable. I agree with @BWPanda about 1 and 3. Thanks for starting this conversation @stpaultim!

**Comment by olafgrabienski** [comment]
I'm in favor of option 2. It's a good solution for #4903, and I think it's even useful to have a cropped image stlye example in core.

Updating one or more existing image styles isn't a good idea, in my opinion. They have their own use case, primarily working for landscape *and* portrait images. And I dislike doing nothing, as it's very easy to break the nice look of the Cards grid, if we don't provide the cropped image style.

**Comment by quicksketch** [comment]
I'm in favor of option 2. To take into account @jenlampton's feedback from the #4903, we could name the new image style "Card", to differentiate from "Large, Cropped" (the originally suggested image style name). This tightly associates the image style and the content type, and might help explain why one image style works as a user-created style while the other 3 are defaults that are provided by Image module (with revert ability).

**Comment by stpaultim** [comment]
My preference would be to update existing image styles (option #1), because in my view they are broken and out of date. They don't do what their label suggests they do and in my opinion, they don't meet the most common use cases for image styles. 

I'm open to option #2 as well, which I think it quite reasonable and doesn't close the possibility of revising the current image styles in the future. 

I'm also happy to let this issue simmer for a while, so that folks can think about it some more and potentially come up with some new ideas to meet the various problems that have been raised.

**Comment by indigoxela** [comment]
@stpaultim to even better clarify the differences between this issue and the [more general discussion](https://github.com/backdrop/backdrop-issues/issues/5590) about default image styles - can we adapt the issue title a bit?

"Fix current images styles" suggests two misleading things:

1. That somethings broken with image styles in Backdrop
2. That we're trying to solve that broken functionality

I'd prefer to concentrate here on the cards content type and how we can provide the best solution for that type.

**Comment by stpaultim** [comment]
> I'd prefer to concentrate here on the cards content type and how we can provide the best solution for that type.

@indigoxela - Fair point. See my new issue title.

**Comment by stpaultim** [comment]
I think that after https://github.com/backdrop/backdrop-issues/issues/5607 this issue is no longer necessary.
