### ISSUE TITLE
Fix: Contextual menu blocks access to dismiss link on notifications.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5595]
## Description of the bug

I just noticed a small but unfortunate side effect of the new front page view. As part of this PR, we have added two new blocks to the front page layout

1) Page messages
2) 3 promoted Cards

In placing the "Page messages" block directly on the layout, we've exposed a contextual menu over the welcome message, that did not exist before. 

BEFORE:

![image](https://user-images.githubusercontent.com/3144571/165257028-ce4ae28a-2d49-48b1-bf09-c4e632b5322a.png)

AFTER: This is what it looks like now.

![image](https://user-images.githubusercontent.com/3144571/165257366-f953eb20-7124-4a8f-b5e3-e07d1913d3ed.png)

It's very frustrating, because every person that installs a new site will see the "X" to close this notification, but can not access it. 

## Steps To Reproduce

To reproduce the behavior:
1. Spin up a fresh site and view the front page (**or clear the cache on an existing site**)

![image](https://user-images.githubusercontent.com/3144571/165245556-9e1046d8-0253-4748-b355-04f28bbc42f6.png)

Then try to dismiss this notification block.

![image](https://user-images.githubusercontent.com/3144571/165245458-76d4a056-8583-4913-afdd-71ca51873af1.png)

## Actual behavior

It's very difficult to close this notification and it's frustrating, because you can see the "X", but you can't get to it.

This is most obviously a problem immediately after installation, but will likely be a problem anytime a notification appears in this block. 

## Possible Solution

Move the close icon a little to the left?

**Comment by stpaultim** [comment]
OK, I have a PR that simply moves the dismiss icon 12px to the left. 

![image](https://user-images.githubusercontent.com/3144571/165265240-122a651a-a036-4cb8-9932-01546a8ab65f.png)

**Comment by indigoxela** [comment]
> After thinking about it. This is a bug that existed prior to the new "Cards" feature

That's correct. It's no newly introduced problem.

If I recall correctly, we ran into similar problems before (contextual links covering other stuff or each other). Just can't remember when and where (and how we fixed it).

**Comment by olafgrabienski** [comment]
@stpaultim - thanks for the PR, the usability works for me.

Personally, I don't like the look of the shifted icon. Is a slightly reduced message width better?

Possible CSS:

```
.contextual-links-region .messages {
  width: calc(100% - 22px);
}
```
**Default:**

<img alt="backdrop-pr-4052-variation-a" src="https://user-images.githubusercontent.com/14188307/165505719-a7c60dee-22d9-49ce-aa44-7f1342ae9269.png">

**Hover:**

<img alt="backdrop-pr-4052-variation-b-hover" src="https://user-images.githubusercontent.com/14188307/165505725-89aab24b-9f00-4250-843a-9efb612c3514.png">

**Comment by indigoxela** [comment]
How about slightly more top margin on the messages div? That would shift the contextual link above the close button.

**Comment by olafgrabienski** [comment]
> How about slightly more top margin on the messages div? That would shift the contextual link above the close button.

Sounds interesting! Tried it with a top margin of 2rem for the `.messages` div via my browser's dev tools, unfortunately with no effect. Am I missing something?

**Comment by indigoxela** [comment]
@olafgrabienski you're right, margin doesn't work. But padding (top) would.

**Comment by olafgrabienski** [comment]
padding top ... not for me :-/

**Comment by indigoxela** [comment]
This works for me:

```
.layout .l-messages {
    padding-top: 1em;
}
```
But that increases the block unnecessarily.

Another thought: messages blocks seem to require some special handling - as they contain a button in the top right corner.
What if we just shift the contextual link?

**Comment by olafgrabienski** [comment]
> `.layout .l-messages`

Ah, the *outer* div ... works! As well as the negative margin-top. I like both - imho the block increasement isn't a problem. Let's see what others say.

**Comment by bugfolder** [comment]
@indigoxela wrote:

> If I recall correctly, we ran into similar problems before (contextual links covering other stuff or each other). Just can't remember when and where (and how we fixed it).

Here's the issue (BTW, needs review and testing): https://github.com/backdrop/backdrop-issues/issues/5273

**Comment by olafgrabienski** [comment]
> giving `a` of class `dismiss` a z-index of 999 and that does the trick for me. Anyone tried that?

Never tried before. Works, but I find the handling a bit fiddly.

**Comment by stpaultim** [comment]
Thanks for all the feedback. It seems as if we haven't come up with a good solution yet? @olafgrabienski - Do you have a favorite idea yet?

**Comment by olafgrabienski** [comment]
> Do you have a favorite idea yet?

No,  what do *you* think?

With regard to the look and feel I like both approaches mentioned in https://github.com/backdrop/backdrop-issues/issues/5595#issuecomment-1111031417. So, I'd choose the solution which is (probably) more backwards-compatible, but I'm not sure how to figure that out

**Comment by stpaultim** [comment]
I like this one best and changed the current PR to use this one.

```
.block-system-messages .contextual-links-wrapper {
  margin-top: -1.4em;
}
```

**Comment by olafgrabienski** [comment]
Tested in the sandbox, works for me!

**Comment by indigoxela** [comment]
Also works for me, but I can't RTBC it. At least, it would be odd, because this approach was one of my suggestions. :wink:

But I can set a milestone. It's 1.21.5 because the problem exited before cards type merge, it's just more visible now.

**Comment by bugfolder** [comment]
Also works for me (thanks for the note about cache-clearing to set up the issue). And code reviewed (yes, all three lines!). WFM, RTBC.

**Comment by BWPanda** [comment]
Sorry to bump this back, but this isn't working on the About page with a warning message:

![Peek 2022-05-14 21-28](https://user-images.githubusercontent.com/2385329/168423763-a8d8d5e4-97d7-4e0a-b246-8649e001dd78.gif)

Clicking on the 'Configure block' link that's covering the message close button takes you to the "Page title combo" block in the Default layout. The "Page title combo" block says in its description:

> Displays the page title, tabs (local tasks), local actions links, **and messages**. Replaces all the normal equivalents on the page with a single block.

So looks like this block needs to be accounted for as well...

**Comment by BWPanda** [comment]
Also, if you zoom in (increase the font size) in your browser, the cog icon is moved too high above the element and you can no longer click on it:

![Peek 2022-05-14 21-36](https://user-images.githubusercontent.com/2385329/168423982-a8634da6-638f-47b3-b0c9-2bbb64e4b160.gif)

**Comment by olafgrabienski** [comment]
> if you zoom in (increase the font size) in your browser, the cog icon is moved too high above the element

Confirmed - looks tricky! (In Firefox, it doesn't happen with the standard zoom but when "Zoom text only" is enabled.)

**Comment by stpaultim** [comment]
The problem with the about page is that we are using the specific "page messages" block on the front page, as of recently, for notifications. Other pages use the default "Page Title Combo" block. Our css was specifically targeting one of the two blocks. 

I have simply added specific code targeting each of these two blocks as a fix. Are there other scenarios I am not considering. 

In terms of the zooming in and out problem, it took me a while to recreate the problem because I was unaware of the "Text Only" option. However, I did recreate it. I have no fix for that yet and don't have time now for further research. I welcome ideas. 

I also question whether or no that should be a blocker. This is a fairly fringe use case, in my opinion and the current problem we are fixing is highly visible and prominent on the front page. The first thing I try to do everytime I spin up a new site is dismiss that notification block and currently, I can't do it. It's a very visible bug. 

If possible, I will try to fix the zoom in with text only problem before tomorrow, but I'm not sure if I will have time.

**Comment by stpaultim** [comment]
In this comment https://github.com/backdrop/backdrop-issues/issues/5595#issuecomment-1111031417 @indigoxela suggested two options. I originally went with the second one as it seemed a bit more elegant. However, the first option also works, is a little simpler AND it works when the user zooms in with their browser. 

I've switched the PR to use that first option.

@olafgrabienski or @indigoxela - can you confirm that this approach works for you and is a suitable alternative. I'm still hoping to get this into the release tomorrow.

**Comment by BWPanda** [comment]
Nice! Updated PR works for me in all situations I mentioned above. Code looks good too, but I'll mark WFM and let someone else confirm with RTBC.

**Comment by olafgrabienski** [comment]
> can you confirm that this approach works for you and is a suitable alternative

@stpaultim – in the meantime we have already the `works for me` label. And yes, for me it *is* a suitable alternative. Btw, the PR sandbox gives a "not found" error, and there is a failing test.

**Comment by BWPanda** [comment]
Re. Tugboat: https://backdrop.zulipchat.com/#narrow/stream/279369-B-Infrastructure/topic/Tugboat

**Comment by BWPanda** [comment]
Re-running tests. If it passes, I'll merge this as it's a simple change and be good to get in this release.

**Comment by BWPanda** [comment]
All tests passed, so merging this simple fix.

Thanks @stpaultim, @olafgrabienski, @indigoxela, @argiepiano & @bugfolder! I've merged https://github.com/backdrop/backdrop/pull/4052 into 1.x and 1.21.x.
