### ISSUE TITLE
Configuration is not owned by any module but hook_config_info there and looks right

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#5596]
## Description of the bug

Config sync, whether by `bee config-import` or on `admin/config/development/configuration/sync` is failing for module:
[Devel Generate Text Settings](https://github.com/backdrop-contrib/devel_generate_text_settings)

However, it has the hook_config_info function and is enabled so I think something else is stopping it working
[In https://github.com/backdrop-contrib/devel_generate_text_settings/blob/1.x-2.x/devel_generate_text_settings.module](https://github.com/backdrop-contrib/devel_generate_text_settings/blob/1.x-2.x/devel_generate_text_settings.module#L8-L16)
```
/**
 * Implements hook_config_info().
 */
function devel_generate_text_settings_config_info() {
  $prefixes['devel_generate_text_settings.settings'] = array(
    'label' => t('Devel generate text settings'),
    'group' => t('Configuration'),
  );
}
```
I've compared it to a module that works and can see no practical difference

I tried changing the name to `devel_generate_text_setatings` and `devel_generate_textsettings` in case there were some issues with the settings keyword, but they still don't work

## Steps To Reproduce

To reproduce the behavior:
1. Install and enable `devel_generate_text_settings` on two sites
2. Change settings on one site (e.g. title prefix) and generate one node to save the setting
3. Copy config to other site
4. Run the import, either by  `bee config-import` or on `admin/config/development/configuration/sync` 

## Actual behavior

> Configuration sync failed. The following errors were reported:
> The configuration "devel_generate_text_settings.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

## Expected behavior

Config imports to second site

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.21.4

Config works for other modules but not this.  I've looked at the code but don't think there is anything wrong with the module when compared to other modules that work.

**Comment by jenlampton** [comment]
In the code example above, `$prefixes` is not being returned. Add that and it should fix the problem :D

**Comment by yorkshire-pudding** [comment]
Thanks @jenlampton - will move to devel_generate_text_settings and close
