### ISSUE TITLE
Remove the path pattern for Cards

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5597]
## Description of the need

Cards were recently added to core, at least in part to provide a content type that will serve for hidden-path nodes (https://github.com/backdrop/backdrop-issues/issues/4903). Yet, by default all nodes get a default path assigned to them. It might be considered confusing to be assigning a special path for "path-less" nodes.

> Anyway, Backdrop comes with the Default URL alias pattern [node:content-type]/[node:title] which applies to all content types without specific patterns. So, to remove the pattern for cards, we had to remove the default pattern, and that's doesn't sound like a good idea to me.

We currently have this path.settings, despite the fact that Cards would get the path anyway - for the sake of consistency. 

```
  config('path.settings')
    ->set('node_page_pattern', '[node:title]')
    ->set('node_post_pattern', 'posts/[node:title]')
    ->set('node_card_pattern', 'cards/[node:title]')
    ->save();
```

## Proposed solution

We could change this to 

```
  config('path.settings')
    ->set('node_page_pattern', '[node:title]')
    ->set('node_post_pattern', 'posts/[node:title]')
    ->set('node_card_pattern', 'node/[node:nid]')
    ->save();
```

In essence, this should override the default pattern for all nodes. 

## Alternatives that have been considered

We could also decide to remove the default pattern for all new content types.

**Comment by stpaultim** [comment]
Here is a screen shot from one of the sample nodes after changing the pattern as described here:

![image](https://user-images.githubusercontent.com/3144571/165380501-15ee0b7b-c271-44c7-9afb-869059c6a8f4.png)

**Comment by quicksketch** [comment]
I don't feel strongly about this. I wish we could fully hide NIDs from users, but the fact is we're stuck with them for URLs like `/node/[nid]/edit`, so trying to hide them from administrators who will also have edit access does seem like a lost battle. 

I commented in the PR, rather than setting an alias pattern for cards, we should delete the pattern entirely so cards simply don't have any aliases.

**Comment by stpaultim** [comment]
> I commented in the PR, rather than setting an alias pattern for cards, we should delete the pattern entirely so cards simply don't have any aliases.

@quicksketch - I'm confused. Are you suggesting we delete the default pattern for all content types? 

We currently have a default for all content types, so removing the pattern ONLY for cards does not change anything and suggests that we should delete it for posts as well - noting that both will still be effected by the default pattern for all content types.

**Comment by stpaultim** [comment]
If this is getting confusing, we could talk about it at the next dev meeting.

**Comment by quicksketch** [comment]
Sorry @stpaultim I didn't know that you could prevent an alias from being created by setting its pattern to `node/[node:nid]`. I tested it out and it does indeed prevent an alias from being created. And no, I don't think we should remove the out-of-box generic node pattern. The PR is fine, I just didn't expect it to work that way.

**Comment by stpaultim** [comment]
@quicksketch - no problems. Thanks for looking. 

I don't feel strongly about this either way and am curious if anyone else thinks we need to change this. I believe that @jenlampton might have opinions on this.

**Comment by indigoxela** [comment]
This is how I always do it to avoid aliases. :wink:

It works, because function path_generate_entity_alias() checks if the outcome after applying the path pattern tokens is the same as the original path. And if it is, it does nothing.

I think that overriding the pattern for cards is the right way to go here. Removing the default for all paths seems overdone and would affect too many content types.

**Comment by bugfolder** [comment]
That is a very slick trick, worthy of documentation here https://docs.backdropcms.org/documentation/url-aliases.

**Comment by bugfolder** [comment]
...and added to https://docs.backdropcms.org/documentation/url-aliases (just under URL aliases). 

Also fixed a bunch of issues. (Literal tokens in the text like [node:title] were getting token-rendered inappropriately. Not any more.)

**Comment by quicksketch** [comment]
Thanks @stpaultim, @indigoxela, and @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4053 into 1.x for 1.22.0.
