### ISSUE TITLE
Error in layout.api.php? 'name' vs 'title'

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#560]
```
*   - name: The human-readable name of the layout.
...
function hook_layout_info() {
  $layouts['my_layout'] = array(
    'title' => t('A custom layout'),
```

The doc block for hook_layout_info() has 'name' as an array key, but 'title' in the example. Substituting 'name' in real code leads to an error. Is this a typo or is 'name' also a concept?

**Comment by klonos** [comment]
I thing we usually use "label" for user-facing text.

**Comment by quicksketch** [comment]
It looks like "title" is correct in this case. So the example code is right and the docblock needs to be updated. I'll make a quick PR.

**Comment by quicksketch** [comment]
> I think we usually use "label" for user-facing text.

We do usually use "label" for user-facing text, and I think it's a better word than "title". I thought that perhaps "title" had been used for consistency with themes and modules, but that doesn't seem to be the case. Modules and themes unfortunately seem to have two different "name" properties. $module->name and $module->info['name'], which doesn't seem like a good pattern to emulate.

We could change "title" to "label", but we'd need to do it soon. Although I think "label" is better, I'd be fine leaving it as-is.

**Comment by quicksketch** [comment]
And just for reference, Views uses "human_name" and "name". :P
