### ISSUE TITLE
[UX] Change cursor to a hand when hovering over a button

### ISSUE THREAD

**Issue by gitressa** [backdrop/backdrop-issues#5601]
## Description of the bug
Just like the cursor changes to a hand when hovering over a link, wouldn't it be great if this also happened when hovering over a button? Pull Request: https://github.com/backdrop/backdrop/pull/3986

## Cursor over button, currently
![1 1-hover-now](https://user-images.githubusercontent.com/3491208/158057326-3571d4dc-cc57-4e12-9f4e-f79704da266a.gif)

## Cursor over button changes to hand
![1 2-hover-cursor](https://user-images.githubusercontent.com/3491208/158057331-beb7e8dd-8064-41e1-9df3-3abf7c1eefcd.gif)

**Comment by stpaultim** [comment]
@gitressa - This has been discussed in the past. See: https://github.com/backdrop/backdrop-issues/issues/2865

It seems that some UI experts believe that the hand/pointer is supposed to be used very specifically for links. Since buttons are not the same as links, these experts believe that buttons should NOT get the hand/pointer. 

Personally, I'm undecided and lean towards using the hand/pointer. BUT, I don't feel strongly about this. Let's see if the mood has changed any in the direction of support for this suggestion.

**Comment by gitressa** [comment]
Thanks for the link to the discussion @stpaultim.

Speaking as an ordinary user of the internet, I am squarely in the "If you can click it, show the hand icon"-camp, which is why I made this PR. That goes for clickable links, clickable drop-downs, clickable icons, and clickable buttons.

Frankly, I can't remember the last time I encountered a clickable button where hovering over it didn't turn the pointer into a hand ... I was simply surprised to not get the hand icon, which shows that this UI behavior has become the norm.

Here's a challenge: Provide a link to a popular web site where hovering anything clickable isn't turned into a hand icon.

**Comment by gitressa** [comment]
Actually, the norm is that non-hand buttons are in fact non-clickable:

![button-no-clicky](https://user-images.githubusercontent.com/3491208/165716116-4a8b006d-172c-4ad8-baee-0f94bf26d03e.gif)

**Comment by stpaultim** [comment]
@gitressa - I'm not saying that you are wrong! :-)

We have a design/UX meeting every two weeks, the next one is one week from today. I'll raise this issue and we'll see what the community thinks. It seemed that folks were a bit unsure in that last discussion. Maybe your argument will persuade them.

**Comment by gitressa** [comment]
Sorry @stpaultim, it wasn't aimed at you at all!

The challenge was just presented to the world, to get arguments for keeping the non-hand behavior. And if very few examples (if any) are found, I think it should be interpreted as a weakening of the stance of keeping the present non-hand behavior. Sorry if it came off a bit harsh :-)

**Comment by stpaultim** [comment]
@gitressa - Don't worry, I didn't take it personally. I took your challenge and visit a number of sites and could not find any buttons that did not use the hand/pointer. Even the login button on Drupal.org does. I also checked buttons on Google and the Washington Post.

**Comment by jenlampton** [comment]
It's very clear that buttons are NOT supposed to have hands (see https://www.w3.org/TR/CSS21/ui.html#propdef-cursor and https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b from the previous thread) but it's also clear that all people are so accustomed to everyone else on the internet doing this wrong, that we all prefer the hand for clickable elements (myself included).  

To make matters worse, there are interfaces in Backdrop where we are techincally required to use a button, when what we really want is a link. In those cases we style the button to look like a link. It would definitely be easier/simpler to treat buttons and links the same way -- even though that would create a regression in interface clarity -- but that regression seems to be what people prefer. 

🤷

**Comment by BWPanda** [comment]
Then we have links styled as buttons: https://github.com/backdrop/backdrop/blob/eec0a072def6f21c72989db6de6b6f6eddae35a3/core/themes/basis/css/skin.css#L32-L34

I (unsurprisingly, because I'm the author of the previous issue about this) am in favour of pointer cursors for clickable elements (be they links, buttons, etc.). This provides consistency from a UX perspective, since users generally don't know or care what the underlying HTML element is when they want to click it...

**Comment by stpaultim** [comment]
We tweeted out about this: https://twitter.com/backdropcms/status/1522311662862184448

Not much in terms of a response, but in my opinion, the responses we did get seem to favor the idea of using the hand for anything clickable. If asked to vote, I think that personally, I'm ready to embrace that opinion. 

Does anyone else have opinions - for or against?

**Comment by olafgrabienski** [comment]
I'm pro hand (without new arguments).

**Comment by BWPanda** [comment]
PR works for me and code looks good!

**Comment by quicksketch** [comment]
Thanks folks. I agree this is RTBC and the PR at https://github.com/backdrop/backdrop/pull/3986 looks good. Thanks @gitressa!

I merged it into 1.x and 1.22.x.
