### ISSUE TITLE
[META] Follow ups to "Provide a new hidden-path ("Card") content type in core"

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5602]
## Description of the bug

We recently merged https://github.com/backdrop/backdrop-issues/issues/4903 which generated a number of small follow-up issues, opening this issue to track the follow-up issues until they are all done. 

- [x] #3339 
- [x] #5595 
- [x] #5597 
- [x] #5599 (Possible release blocker)
- [x] #5604
- [x] #5607 
- [x] #5608 
- [x] #5621 
- [ ] #6239

**Comment by indigoxela** [comment]
@stpaultim the contextual menu blocks access issue isn't actually a regression of the cards content type. It existed before that.

**Comment by stpaultim** [comment]
> the contextual menu blocks access issue isn't actually a regression of the cards content type. It existed before that.

I get that. But, I think it still makes sense to call it a follow-up issue, because the new front page display makes it REALLY obvious. This little bug is now the first thing I see, every time I install Backdrop. In the past, it wasn't this obvious. ;-)

**Comment by stpaultim** [comment]
Six issues, 3 are marked as fixed. Three more have ready to go PRs. The only one that MIGHT need to be done by code freeze is the Image Styles one.

**Comment by docwilmot** [comment]
I would argue that as such a new feature, issues to get it working properly should be considered bug fixes, including the image styles one.

**Comment by stpaultim** [comment]
I'm going to close this issue, since all of the currently listed follow-up tasks are complete.
