### ISSUE TITLE
Bulk Operations views handler shows wrong actions when first adding a BO field

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5603]
EDIT: In addition to the bug shown below, which I reported originally, please scroll down to see other bugs in this handler. I will provide a PR that tackles this and the other bugs.

## Description of the bug

When adding a Bulk Operation views field for an entity obtained through a "relationship" to the main one of the View, Bulk Operations shows the wrong actions. It shows the actions for the base entity, not for the related entity 

## Steps To Reproduce

1. Create a View with for a Content (Node) base entity
2. Add a relationship to `Content: Author`. Add a field from the user entity such as username
3. Add a Bulk Operation field for the User account entity

The actions shown in the "Configure field" modal for this Bulk Operations belong to the Node entity, not to the User one. 

## Actual behavior
The actions shown in the "Configure field" modal for this user Bulk Operations belong to Content (Node), not to User account. 

## Expected behavior

The actions for User account should be shown.

## Additional information
It seems like the method `views_handler_field_bulk_form::get_entity_type()` contemplated the ability to add a BO for fields available through relationships: 

```php
    // If the current field is under a relationship you can't be sure that the
    // base table of the view is the base table of the current field.
    // For example a field from a node author on a node view does have users as base table.
```

Obviously this is not working, as `$this->options['relationship']` is still set to `none` .
 

Add any other information that could help, such as:
- Backdrop CMS version: 1.22.x-dev

**Comment by argiepiano** [comment]
One more clue: if you save the Bulk Operation (without selecting any of the actions) and reopen it, the list of actions shown in the UI is correct. This happens because once saved, `$this->options['relationship']` is set correctly.

**Comment by argiepiano** [comment]
## Additional bug found in handler

In addition to the bug reported above I have found that the handler, in SOME cases (see below), provides the incorrect IDs for entities accessed through a relationship. I will provide a PR that makes several changes - all of them inspired by D7 VBO. The PR may be a bit difficult to understand if you are not very familiar with Views handlers, so here's a bit of background.

This issue is a blocker for OG's Views, as we need a well-functioning Bulk Operations. See https://github.com/backdrop-contrib/og/issues/22

### A bit of background

Bulk Operations handlers for specific entities are typically defined by implementing `hook_views_data` or `hook_views_data_alter` in `MODULE.views.inc`. They use key `'real field`' in their definition to indicate the column or "field" on which the operation needs to happen (for example, `nid` if the bulk operation is "Delete content" etc). Take a look at  [this line](https://github.com/backdrop/backdrop/blob/d9675244a7e79a4b7fd9fd7d16c714a931c80b1b/core/modules/user/views/user.views.inc#L367) where the Bulk Operation views field for users is defined. 

In pretty much all cases, Bulk Operations will use the main entity ID as the `'real field'` - for nodes, that's `nid`. For users that's `uid`.

Now, a word about Views Relationships. Relationships allow you to "join" one entity to another entity by adding a "field" in the Relationships area of the Views UI. For example, if you have a View of nodes, you can add a Relationship to users. These relationships use two table columns, one in the node table (uid) and one in the users table (also called uid) to "join" these two tables together - so a Views row can show fields from both entities, which have a common uid. See for example these [lines](https://github.com/backdrop/backdrop/blob/d9675244a7e79a4b7fd9fd7d16c714a931c80b1b/core/modules/node/views/node.views.inc#L407) that define the relationship between nodes and users by using the `uid` column in both tables.  In this case `uid` happens to be the "main" ID of users entities.

The problem I'm reporting here happens because, in some rare cases, an entity is joined to a second entity through column that's NOT the second entity's "main" ID. For example, Organic Group memberships (`og_membership` entities) are joined to users through an OG column called `etid`, which is not the main ID for `og_membership`. The main entity ID column for `og_membership` is actually `id`.

So, when you define a Bulk Operation for `og_membership` entities, and you use a Views of (say) users, joined to the `og_membership` entity through a Relationship,  the current Bulk Operations code handles the `og_membership`  incorrectly. Instead of providing the main ID (`id`) of `og_membership`, it provides the `etid` column, which is the column used to "join" users to `og_membership`. This is wrong, and as a result doesn't allow us to operate on the `og_membership` entity (for example, delete `og_membership` entities with a specific `id`).   

The PR I will provide fixes this. I've tested it pretty carefully to be sure it doesn't break the simpler uses of Bulk Operations (i.e. operations on the Views entity, or operations with the simpler relationship I described above). But I will appreciate more testing and code reviews. 

If you wish to test or reproduce the problem, you'll need to create a custom entity and a custom Bulk Operations field for the new entity. I will provide such code later (probably tomorrow).

**Comment by indigoxela** [comment]
> the current code of Bulk Operations handler IGNORES the real field and instead uses the field used in the relationship

Oops, what a mess! @argiepiano this seems like something that needs an automated test to prevent similar problems in the future. Not sure how hard it may be to create such a test.

**Comment by indigoxela** [comment]
I did a first review and left a comment with a small suggestion.

Switching from extending views_handler_field to views_handler_field_entity seems to be the right approach here, as it already ships with the entity_type property.

**Comment by argiepiano** [comment]
I've added three tests for the Bulk Form handler. Views currently did not have any tests for it. The tests checks three scenarios:

1. A node Bulk Form added to a node view
2. A user Bulk Form added to a node view that has a relationship to the user entity (author relationship)
  - This test, among other things, checks that the actions shown in the Bulk Form belong to the user entity rather than to the node entity, which is one of the bugs this PR fixes
  - Also it checks that the Bulk Form checkbox values match the uid of the user entity for each of the view's rows
3. A custom entity (`views_test`)  Bulk Form added to a node view that has a relationship to the views_test entity through the field `nid` field in both tables. The entity id field for the `views_test` entity is called `id`. 
  - This test verifies that the Bulk Form checkbox values match the id of the `views_test` entities for each row. This was a bug that this PR fixed. Before the PR, the checkboxes did not match the id of the related entity        

I would be thankful if you could test and review the code.

**Comment by indigoxela** [comment]
@argiepiano great job! Thank you so much. I'll try to do proper testing ASAP. In the meantime I've left a small suggestion - and a pretty confused comment on your PR (same class defined twice?).

**Comment by argiepiano** [comment]
Upon further digging and testing, the bug I reported in my  [second comment above](https://github.com/backdrop/backdrop-issues/issues/5603#issuecomment-1112779784) doesn't seem to be actually be a bug. This means that the commits in the PR dealing with this particular bug may actually not be necessary.  Will update accordingly.

However, the original bug I reported in my first posting IS a real bug, and parts of this PR will fix it.

**Comment by argiepiano** [comment]
I have provided an alternative PR that takes a lighter approach. Instead of changing the class parent to `views_handler_field_entity` and making other modifications to adjust to this parent, it keeps the original parent class `views_handler_field` and modifies the method `get_entity_type` to provide the correct actions for the entity type to which this bulk form field belongs.

This new PR keeps the tests that I created for Bulk Forms. Ready for testing and review. 

Since the second issue I reported above is not a bug, the way to test this PR is described in my original post under "Steps to reproduce".

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4066 ready for review and testing.

**Comment by indigoxela** [comment]
I like that more lightweight approach! Seems simple and straight forward.

@argiepiano I've left some comments on your PR. The functional test isn't working yet.

**Comment by argiepiano** [comment]
Thanks! 

> The functional test isn't working yet. 

What do you mean? I see all tests have passed. But perhaps you are testing in an installation with the regression I just reported in https://github.com/backdrop/backdrop-issues/issues/5615?

**Comment by indigoxela** [comment]
> Yes, the issue was the new setUp argument. I'll need to rebase and modify my PR to adjust

Yes, let's wait until that PR gets merged, then we can proceed here (after rebase).

**Comment by indigoxela** [comment]
@argiepiano this works like a charm, but something went wrong with your rebase - seems like you merged instead of rebasing :wink:

**Comment by indigoxela** [comment]
But now for the testing:

This time I tried both relationship directions.

- A view of content with the author as relationship
- Bulk operations on user
- The right actions show up when adding bulk operations field to the view :+1: 

- A view of users with relationship to "Content authored"
- Bulk operations on content
- The right actions show up when adding bulk operations :+1: 

So the PR works for me - besides the small merge/rebase oops. :wink:

**Comment by argiepiano** [comment]
> but something went wrong with your rebase - seems like you merged instead of rebasing

Oh no! I'm so clumsy with git - it scares me. Do you know of any way to fix this problem?

**Comment by argiepiano** [comment]
I "think" I did it right this time. If you look at "Files changed" in the PR only the ones I actually changed are showing up, which leads me to believe that this will be a clean merge with 1.x (?).

I also fixed the definition of setUp in the new test, and all tests are passing.  I'd appreciate a new look, @indigoxela. 🙏🏽

**Comment by indigoxela** [comment]
This time the rebase worked. :wink:  And the PR still works for me. :+1:

**Comment by indigoxela** [comment]
It still works for me, but after some local debugging (and head scratching), I've left a question on your PR.

**Comment by argiepiano** [comment]
@indigoxela - I made the adjustment you pointed out. Thanks!

**Comment by indigoxela** [comment]
Perfekt! Works like a charm and all tests (including your new one) pass.

One last thing before RTBC - can you switch your test to the "testing" profile? That's for test performance reasons. And thank you so much for all your patience with my "nagging". :wink:

**Comment by argiepiano** [comment]
changes made!

**Comment by argiepiano** [comment]
Thank YOU, @indigoxela, for taking the time to test and review. It's becoming harder these days to find people available for those!
