### ISSUE TITLE
Removing "3 Promoted Cards" block and restoring it again - appears to break it

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5604]
## Description of the bug

I don't think this is a bug, but it's at least problematic behavior. The problem is that we added a "container" class to the "3 Promoted Cards" block during installation. We did this, because the only way we could generate the background color behind the view was to put the block into the "Top" region, which does not have a container class of it's own (which is why we are able to add a background color). 

This is a problem if you delete the block, then decide you want to put it back. When you replace the block in the Top region it no longer has the container class and it looks like this (see below), because without the container class it spreads out to fill the entire page. 

![image](https://user-images.githubusercontent.com/3144571/165683464-58c14222-c300-47e7-a23b-f48b5b428ee7.png)

In fact, nothing is broken here except the site architects expectations. As a site architect, I expect that if I delete a default block and put the same block back in the same place it will look the same. In this case, it's really not the same block anymore, because it no longer has the container class. But, the site architect has no way of knowing that. 

If you put any other block in the same place, including the promoted content block, they will have the same problem. 

If you delete the default promoted content block and put it back into the content region - it looks the same as it did before. Because the content region has the container class, so the blocks inside of it do not need the container class. 

## Steps To Reproduce

To reproduce the behavior:
1. On a site with the new card content type, delete the "3 Promoted Cards" block from the home page layout. 
2. Then place the "3 Promoted Cards" block back in the same place. 

The same problem exists for the "Page Messages" block that is currently in the TOP region. 

## Additional information

The main reason we did all of this was to create the Background color in the TOP region, which may turn out to be problematic in itself. See: https://github.com/backdrop/backdrop-issues/issues/5599

If we decide that we have to get rid of the grey background color, we can move the "Page Messages" block and the "3 Promoted Cards" blocks into the Content region, where they will be constrained by the container class on the region. 

Otherwise, we could just accept this problem as something that isn't likely to happen very often (removing and then restoring this block to the same location) and something that the user can fix by manually adding the container class back in. 

We could also fix it with Javascript, but I suspect that is a bad idea.

**Comment by indigoxela** [comment]
I'd need to experiment a bit, but I belief, this is solvable.

**Comment by olafgrabienski** [comment]
For the record, there is now a [pull request](https://github.com/backdrop/backdrop/pull/4055) for #5599, which seems to solve this issue here as well.

**Comment by stpaultim** [comment]
I just marked that issue RTBC, so I'm comfortable closing this issue.
