### ISSUE TITLE
Add new PR template, with reminder to reference an issue

### ISSUE THREAD

**Issue by gitressa** [backdrop/backdrop-issues#5605]
## Description of the need

I created two PRs a few months ago, and was waiting for them to get attention. It wasn't until yesterday I by chance saw this, under https://github.com/backdrop/backdrop#developers:

> When submitting a pull request, please make sure there is an open issue in the issue tracker and reference it in the description on the pull request.

## Proposed solution

Emphasize that PRs need a corresponding issue. Perhaps for PRs, a `pull_request.md` template could be made, with something like this?

```
## Description of the Pull Request

A short description of what the PR solves.

## Link to the issue

When submitting a pull request, please make sure there is an open issue in the issue tracker and reference it in this format (replace ISSUE_NUMBER):

Fixes https://github.com/backdrop/backdrop-issues/issues/ISSUE_NUMBER

```

As a follow up task, maybe existing PRs could be scanned for missing issue references? It would be sad if too many first time contributors have PRs gathering dust for months or even years ...

## Remaining Tasks

- [x] Create a PR template
- [x] Find existing PRs without a reference issue and add a comment to alert the creator of this requirement

**Comment by bugfolder** [comment]
We do have a fairly detailed description of how to submit PRs, the relationship to issues, etc., in our documentation. I would suggest that in this README we just add a link to the docs. So, replace

> When submitting a pull request, please make sure there is an open issue in the [issue tracker](https://github.com/backdrop/backdrop-issues/issues) and reference it in the description on the pull request.

with something like this:

> You can submit changes to Backdrop by creating a pull request that references an issue in the [issue tracker](https://github.com/backdrop/backdrop-issues/issues). Details about how to do this are in the [Contribute to Backdrop Core documentation](https://docs.backdropcms.org/documentation/contribute-to-backdrop-core).

**Comment by quicksketch** [comment]
Great idea @bugfolder. Seems obvious that we should provide a template to help newcomers follow policy of always filing an issue.

**Comment by argiepiano** [comment]
> with something like this:
> 
> > You can submit changes to Backdrop by creating a pull request that references an issue in the [issue tracker](https://github.com/backdrop/backdrop-issues/issues). Details about how to do this are in the [Contribute to Backdrop Core documentation](https://docs.backdropcms.org/documentation/contribute-to-backdrop-core).

That sounds like a good idea @bugfolder. @gitressa, thanks for bringing this up!

**Comment by bugfolder** [comment]
> But in reality, many users just jump in, and do what they usually do in other projects. So adding the info right in the window where the PR is created, will make sure the required steps are done.

I agree. (I didn't fully understand the notion of a PR template when  I first commented; now I do.) I've found the instructions for adding a template, think I have the privileges to do so, and will give it a try (as well as submitting a PR to update the README file).

**Comment by BWPanda** [comment]
In addition to @gitressa's suggestions, I've made some of my own in the PR.

**Comment by bugfolder** [comment]
Thanks @gitressa and @BWPanda for quick review and feedback! All suggestions committed to the PR.

**Comment by stpaultim** [comment]
This looks pretty good. Is there a way to test (view) this other than just the "files changed" tab on the PR?

**Comment by bugfolder** [comment]
I think it has to be in the repository to take effect in GH, so, not that I know of.

**Comment by BWPanda** [comment]
Yeah, I thought we could test by opening a PR against @bugfolder's repo, but PR templates need to be in the default branch to take effect. I guess you could add the file to your own repo's main branch to test...

**Comment by bugfolder** [comment]
Good idea, have done. I've also tightened up the wording a bit more.

**Comment by quicksketch** [comment]
I think the added text looks great. Using the document preview shows that the newly added link isn't rendering correctly however. I made an adjustment to the line breaks to render it correctly: https://github.com/backdrop/backdrop/pull/4057/files#r862517215

But all text is great and I didn't see a reason to hold this up, so I merged https://github.com/backdrop/backdrop/pull/4057 into 1.x and 1.21.x, and it is now showing up on new PRs!

![image](https://user-images.githubusercontent.com/100206/166163314-8d5e0d79-0474-46a2-b18b-3f8462fa4ec1.png)

**Comment by BWPanda** [comment]
Yes, I think the asterisks aren't necessary. I've made a new PR to remove them, and also fixed some of the formatting and updated some of the working: https://github.com/backdrop/backdrop/pull/4074

**Comment by stpaultim** [comment]
Looks good. One possible idea/improvement:

Can we BOLD this phrase "Each PR must be linked to an issue" or otherwise make it stand out from the rest of the text?

**Comment by BWPanda** [comment]
Those comments are only visible when viewing the raw text, so there's no formatting available. Nevertheless I tried adding `**` around that phrase to see if that helps. Otherwise the only thing I can think of is making it all uppercase, but I don't think that's a good idea...

**Comment by BWPanda** [comment]
Thanks @stpaultim and @gitressa! I've merged https://github.com/backdrop/backdrop/pull/4074.
