### ISSUE TITLE
Add a new cropped image style specifically for cards.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5607]
## Description of the need

With the addition of https://github.com/backdrop/backdrop-issues/issues/4903 into core, there has been some discussion about the need to add a new image style that we can use for our front page view of Cards. Various options have been discussed here:
https://github.com/backdrop/backdrop-issues/issues/5593

Of the options presented, this is the one that has the most traction so far. It would be nice to get this into 1.22.0, since the new cards content type will be so prominent and it would be really nice if the view layout (image alignment) doesn't "break" as people experiment with it. 

## Proposed solution

After discussing this with @quicksketch during our informal sprint today, we've come up with the following proposal to address the following goals.

1) Keep changes to a minimum
2) Future proof the changes as much as possible
3) Name the new image style in a way that helps people understand the difference between cropped and uncropped image styles
4) Provides a meaningful alternative or option to existing image styles

I'm about to submit a PR that does the following. Feedback welcome.

1) Creates a new cropped image style
2) Names it "Cards (600x400 cropped)
3) Machine name = "cards"

## Alternatives that have been considered

https://github.com/backdrop/backdrop-issues/issues/5593

## Additional information

We have deliberately added the word cropped into the label to help distinguish it from existing image styles. This one will behave differently, because it is cropped and the others are not, and we feel as if the label should somehow reflect that.

Sorted alphabetically, we would have a list of image styles that would appear as:

Cards (600x400 cropped)
Large (800x600)
Medium (300x250)
Thumbnail (100x100)

**Comment by stpaultim** [comment]
It will look something like this, but all four will be default.

![image](https://user-images.githubusercontent.com/3144571/166122265-c8c20f78-33bb-4f3d-b187-c2f15784628d.png)

**Comment by quicksketch** [comment]
I've added this to the milestone so we can easily find it. Would be nice to have this rather big limitation sorted out before release.

@stpaultim The dimensions and labeling as cropped seem good to me. Could we make it `Card` instead of `Cards` though?

**Comment by stpaultim** [comment]
![image](https://user-images.githubusercontent.com/3144571/166123710-0cac12ca-554c-482a-8930-79acaf37faba.png)

**Comment by stpaultim** [comment]
I have a PR that adds this new image style and uses it for the front page view of promoted cards instead of the large image style. @quicksketch and I discussed this and think it's a good solution that reflects the feedback we've been getting on this issue. 

We'd like to get a few more opinions on this before code freeze tomorrow night - so that we might be able to merge it and have it as part of 1.22.0 - so that this prominent new feature will work better for folks testing it out.

Any thoughts?

@olafgrabienski - Do you have time for a quick look?

**Comment by olafgrabienski** [comment]
> Do either you have time for a quick look?

I like the addition of the image style. Can't look at the PR now, but hopefully before feature freeze.

One question regarding the image style dimensions: what was the reason to choose `600x400`? When we implemented an image style at #4903 (before removing it again), I chose `800x533` "f[or sharp images also on high resolution displays and with different screen sizes](https://github.com/backdrop/backdrop-issues/issues/4903#issuecomment-1042938498)". However, *if* we decide to choose the smaller dimensions, we should also adapt the default card images to match them, which would avoid unnecessary manipulation of those images.

**Comment by stpaultim** [comment]
@olafgrabienski - Thanks for the explanation of the original size. The current thought is that this PR must get merged before tomorrow to be included in 1.22. However, I suspect that we would still be able to change details like the screen size for the next two weeks, if necessary.

I think we chose 600x400 for the image style in the first draft PR for these reasons (recognizing that we might get feedback and make changes). 

1) The actual display size for these images on desktop is 354 x 235
2) The actual display size for these images on a tablet is no bigger than 514x342
3) 600x400 is the same aspect ratio as the actual images
4) 600x400 is a different aspect ration as the other image styles
5) The current Large image style is 800x600 and we thought that if we are going to add a 4th image style, it might be nice if it's not too close to one we already have. 600x400 is between the large and medium images styles and provides more variety. 

BUT, we recognize that there might be other opinions and I'm open to them. This was just our stab at getting a PR out for discussion with the small possibility of getting something into 1.22. However, if it needs more discussion - I'm good with that.

**Comment by stpaultim** [comment]
The motive for this suggesting this PR was that in testing the sort order PR, @quicksketch and I added a new card to the view to see if it would display and because the aspect ratio was different it immediately broke the alignment of images. We are pretty sure that this is going to happen to other folks testing this. 

We took the image style of the last PR, because there were sharp differences at the time and we wanted to move forward. However, a consensus appears to be forming over this specific solution (my proposal is loosing :-). 
https://github.com/backdrop/backdrop-issues/issues/5593

If there is interest, we can try to get this in 1.22. But, if folks want more time to discuss this, that is also an option.

**Comment by indigoxela** [comment]
I'm fine with the new image style :+1:

(I still have concerns regarding changing all _existing_ styles, but that's not the topic here.)

**Comment by olafgrabienski** [comment]
> The current thought is that this PR must get merged before tomorrow to be included in 1.22. However, I suspect that we would still be able to change details like the screen size for the next two weeks, if necessary.

Being pressed by feature freeze, I'd suggest to add the image style, but with the originally intended dimensions (800x533). For a change to 600x400 we'd need adapted image files, and I'm not sure I have time to generate them today. More important, I'm still skeptical changing the dimensions to 600x400 and would like to discuss this without pressure. (We'll have time to do so for another two weeks.)

**Comment by BWPanda** [comment]
Why was 'center-top' chosen as the anchor point? Wouldn't just 'center' be more what people expect?

**Comment by quicksketch** [comment]
> Why was 'center-top' chosen as the anchor point? Wouldn't just 'center' be more what people expect?

Because when people upload photos of people, their heads tend to be towards the top of the image, Top-center usually prevents cropping off the heads.

As for image dimensions, I'm also okay with @olafgrabienski's suggestion to use the original 800x533 size. Until we have support for `srcset` in image styles, just going double-resolution is a simple solution for high-quality images.

**Comment by stpaultim** [comment]
I'm about to make the change you requested @olafgrabienski. I agree that we can change the size later after more discussion, if there is a need. 

> For a change to 600x400 we'd need adapted image files, and I'm not sure I have time to generate them today.

But, I don't understand why this is true. If it true, I'd like to understand why. The new image style is smaller, but maintains the same aspect ratio. I fail to understand why there would be any need to change the original images. Isn't that the entire job of the image style? Even if we went with the smaller image style, I would vote in favor of leaving the larger images, since you can always scale an image down, but you can't scale up. It seems to me that the only important thing is that the aspect ration is correct.

**Comment by stpaultim** [comment]
OK, I updated the PR. 

![image](https://user-images.githubusercontent.com/3144571/166164809-b31f2a27-19b9-47b1-a63b-6ad3016d73d7.png)

As I look at this, I'm reminded of the original objection by @jenlampton that this feels almost redundant. We are now adding an image style that is so close to one we already have, that I would much rather change the existing large image style - keeping the number of options at 3. 

I felt better about the earlier version of this PR, because the added image style at least appears to add variety and legitimate options. In this PR the added image style is virtually the same as the existing image style, but a little better because it provides uniform output when the existing large image style doesn't.

**Comment by olafgrabienski** [comment]
>> For a change to 600x400 we'd need adapted image files

> I don't understand why this is true.

Maybe we don't exactly *need* adapted image files, but it would be very preferable. Why? The default images are optimized to have a very small file size. This remains true as long they're not changed by an image style, which increases the file size.

Just verified: one of the original, optimized images (800x533) has 4 KB, but the same image even with the quite small *Medium* image style (300x250) has more than 9 KB.

**Comment by olafgrabienski** [comment]
> In this PR the added image style is virtually the same as the existing image style, but a little better because it provides uniform output when the existing large image style doesn't.

I think, that's exactly what we need here. The cropped image style fixes the one issue of the large image style, which doesn't work with custom images of a different aspect ratio. In my opinion, it's good that the new style doesn't differ in other aspects, like the dimensions. I'm open to discuss the question, but again: please not last minute just before feature freeze.

**Comment by stpaultim** [comment]
This is not an argument for or against the PR changes. But, a technical clarification. If we use an image style instead of the original image, the images are going to get resized anyway. 

Here are the files on my local system, using the 800x533 image style. It would never have occurred to me that the files would get bigger. Again - I don't think this is a deciding factor in this discussion, just a point of information.

![image](https://user-images.githubusercontent.com/3144571/166167536-b51f4c0e-bae0-4f3a-8c2a-297e6df338e4.png)

**Comment by stpaultim** [comment]
Final comment on this issue (for tonight). I do not want to stand in the way of this getting in. The only reason to block this would be if we were still considering changing an existing image style (my preference), but the chorus of opposition to that idea has been heard and noted. :-)

Thanks everyone for the feedback and discussion.

**Comment by quicksketch** [comment]
I reviewed the PR, looks good although I think the image style `card` should be provided by the `standard` profile, not a part of the core image module. Same as the content type and view, it's only a set of configuration provided on install. https://github.com/backdrop/backdrop/pull/4058/files#r862535183

**Comment by stpaultim** [comment]
@quicksketch - I've updated the PR and moved the image style to the install profile. I'm a bit confused about why I'm doing that. The other image style config files are all in the images module. I thought we would need a copy there for the "revert" function.

**Comment by quicksketch** [comment]
> The other image style config files are all in the images module. I thought we would need a copy there for the "revert" function.

It's for the same reason that the card_listing view is in the standard profile and not part of Views module. You're right that it is necessary for reverting (unless we add some ability to revert configs provided by profiles), but it's also needed for being able to delete. Everything in the standard profile can be deleted if needed (the card content type, the view, and the image style). If these were provided by modules directly then not only would they show up on non-standard profiles, but they also wouldn't be removable for sites that wanted a different naming convention. `thumbnail`, `medium`, and `large` are special in the way that they are always available for contrib-use, but this new `card` style doesn't get the same special treatment (which also means we can more easily change it later).

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4058 into 1.x for 1.22.0. Thanks @stpaultim and @olafgrabienski for helping this last item for the 1.22.0-preview release!
