### ISSUE TITLE
Figure out and document a policy for handling future security issues

### ISSUE THREAD

**Issue by DavidRothstein** [backdrop/backdrop-issues#561]
Howdy Backdrop folks.  I have been keeping an eye on Backdrop from afar for a while (sadly never made time to contribute yet) and I just took it for a test drive now, given that the 1.0.0 release is coming up in a week... First things first, I am impressed with the functionality that is in there already - great job!

Given that the 1.0.0 release is so soon I wanted to raise the question of how Backdrop will handle reporting and fixing security issues post-release.  I looked through the documentation and don't see anything about security there yet.

For starters I would suggest simply having an email address where security issues can be reported in private.  This address could then be mentioned in three places:
1. A "Security" page somewhere at https://backdropcms.org
2. The issue queue front-page README (https://github.com/backdrop/backdrop-issues)
3. The README.md in the Backdrop codebase

A more interesting question is what to do about security issues that are shared between Backdrop and Drupal.  I suspect that from the Drupal Security Team's perspective this isn't too different from https://www.drupal.org/SA-CORE-2014-004 (a security issue that was coordinated with WordPress); however, the big difference is that rather than being an unusual occurrence it will probably be the case for the majority of security issues reported against either project.  Inviting Backdrop maintainers to coordinate on each such issue (as was done with WordPress) would be time-consuming and would be almost equivalent to having Backdrop maintainers be part of the Drupal Security Team itself, which is not currently the case (applicants always welcome though, https://security.drupal.org/join :)

Since I'm on the Drupal Security Team myself and coordinate Drupal 7 (and usually Drupal 6) security releases already, I would be happy to help with this in any way I can, first things first by bringing a proposal forward to the Drupal Security Team on how to handle joint Backdrop-Drupal security issues, if we can come up with something good here.  Any thoughts?

(Side note: In the above I've been thinking mostly about Backdrop core and Drupal core.  The security policy for Backdrop contrib modules should be considered as well, I think.)

**Comment by quicksketch** [comment]
Hi @DavidRothstein! Thanks so much for taking the time to reach out!

> For starters I would suggest simply having an email address where security issues can be reported in private.

An excellent idea. We can set that up immediately.

> This address could then be mentioned in three places:
1. A "Security" page somewhere at https://backdropcms.org
2. The issue queue front-page README (https://github.com/backdrop/backdrop-issues)
3. The README.md in the Backdrop codebase

Also a great idea. We can set these up with only a little work.

> Since I'm on the Drupal Security Team myself and coordinate Drupal 7 (and usually Drupal 6) security releases already, I would be happy to help with this in any way I can, first things first by bringing a proposal forward to the Drupal Security Team on how to handle joint Backdrop-Drupal security issues, if we can come up with something good here. Any thoughts?

Thanks! This would be extremely helpful. I work on Drupal security issues from time to time when they involve either my contrib modules or portions of core (File and Image handling usually). I'd been thinking about trying to join up as a full-fledged member of the team, but I'm worried if that comes with obligations I may not be able to fulfill them while taking on Backdrop at the same time.

We also have had @matt2000 express interest in helping coordinate. His regular contact with @greggles (they both work at card.com) could also help with ensuring we keep things in sync.

For managing security issues, our plan has been to create a private Github repository in which we can manage permissions and access. We can use both the code repository and the issue queue to manage branches and issues. Though Github is drastically more limited in what it can do around managing permissions, in the short-term we should be able to manage.

**Comment by quicksketch** [comment]
I set up the following:

- security@backdropcms.org now mails myself and Jen. We'll add more members as requested.
- https://backdropcms.org/security now provides an (empty) feed of security announcements and instructions on reporting a security issue.
- https://backdropcms.org/security/rss.xml provides a feed.
- Added a link in the footer of the main site.
- Added an e-mail link in this issue repository README.md.

We'll need to make a PR for the official project itself. Getting there!

**Comment by DavidRothstein** [comment]
Thanks, those changes look good to me.  However I'd recommend also linking to the security page from somewhere besides the footer; maybe a sentence in the "report bugs" section of https://backdropcms.org/contribute?

Here's a PR to update the README.md in Backdrop itself (I used essentially the same wording as the paragraph at https://github.com/backdrop/backdrop-issues but mentioned contributed modules in the same paragraph): https://github.com/backdrop/backdrop/pull/650

Regarding the Drupal security team, one thought that occurs to me is that some security patches should be trivial to port from Drupal to Backdrop.  In those cases, coordination is less important since Backdrop can easily apply the patch right after the Drupal security release comes out.  So one thing I can focus on (and any other interested security team members as well) is keeping an eye out for patches where that *won't* be the case, and try to get a private head start on a Backdrop version for those (at least for core patches).  Those also would be the issues where it would make the most sense to invite you to the security.drupal.org issue, if the security team is amenable to that.

I will drop a note to the security team sometime tomorrow pointing them to this discussion and seeing if anyone has any thoughts.

**Comment by greggles** [comment]
It seems totally fine to just add Nate (and/or whomever as a backdrop representative) to every core + views + panels issue on s.d.o based on the idea that collaborating will lead us all to better solutions.

**Comment by klonos** [comment]
It's really great to be following this issue! It proves wrong all these that were talking about Backdrop (and any Drupal fork in general) inevitably "splitting" the Drupal community.

**Comment by DavidRothstein** [comment]
> It seems totally fine to just add Nate (and/or whomever as a backdrop representative) to every core + views + panels issue on s.d.o based on the idea that collaborating will lead us all to better solutions.

That sounds fine to me, especially because of the people involved.

I think if we do this we might want to be a bit more formal about it though... just because I don't think we want to set a precedent that all you have to do to get invited to have early access to all Drupal security issues is create a fork of the project :)

I would suggest that the policy be...

1. If the person would basically meet the criteria for Drupal security team membership (in the hypothetical event that they applied), and
2. If the fork has some substantial amount of work and effort behind it

...then it's OK to invite the person to any/all security.drupal.org issues.

In this case I think both those criteria are definitely met, so no problem.

**Comment by greggles** [comment]
Yes, those were exactly my thoughts, David. It's the same line of logic we have going for distributions. Good point to be explicit about it :)

**Comment by quicksketch** [comment]
> Here's a PR to update the README.md in Backdrop itself

Thanks, merged!

> However I'd recommend also linking to the security page from somewhere besides the footer; maybe a sentence in the "report bugs" section of https://backdropcms.org/contribute?

Thanks, another good idea. Added there as well.

> It seems totally fine to just add Nate (and/or whomever as a backdrop representative) to every core + views + panels issue on s.d.o based on the idea that collaborating will lead us all to better solutions.

@greggles ++

That sounds great for starters until we have a more structured security team or a dedicated liaison for security issues.

**Comment by DavidRothstein** [comment]
Thanks for the merge.

> Yes, those were exactly my thoughts, David. It's the same line of logic we have going for distributions. 

Hm, I didn't even realize there was a policy for distributions, but yes, it definitely makes sense to treat this the same way :)

**Comment by greggles** [comment]
Yeah, I don't think it's an explicit policy, per-se, but it's definitely something we've discussed & promoted at least since Drupalcon Paris (when Frank Febbraro was invited joined the team).

**Comment by DavidRothstein** [comment]
I pinged the security team one more time just now for final feedback, but otherwise I think we'll go with this plan - so @quicksketch, we'd start inviting you to security issues pretty soon if they appear to affect Backdrop core.

Still not sure what the plan should be for Backdrop contrib, though...

**Comment by quicksketch** [comment]
> Still not sure what the plan should be for Backdrop contrib, though...

Yeah, from the looks of things, it's going to be a bit of a wild west in contrib-land for a while until we work out the initial porting, the new influx of developers, and our infrastructure for listing contrib modules on backdropcms.org. I think for now we'll have to just work on communicating with individual authors as best we can to fix issues until we can bring them into a more structured system.

**Comment by jenlampton** [comment]
I did start a conversation with GitHub today around setting up a security issue private repo. We'll see if anything comes of that, but if so it might be a good place to handle both core and contrib issues.

**Comment by BWPanda** [comment]
I think all these suggestions have been implemented now, so closing.
