### ISSUE TITLE
User Account Cancellation (by user) displays AJAX HTTP error

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop/backdrop-issues#5618]
==========
## Description
---------
After a user clicks the "Cancel Account" link in their email, they are taken to the website's > "Cancelling account" page.  This page displays,
An error has occurred.
Please continue to the error page
(Then in red)
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information folows. Path... (blah blah... looks like it's printing out text from the whole front page)

The account **does successfully delete**.  

The URL (cancelling account URL) looks like this:
https://www.cloudbrat.com/batch?op=start&id=60

When I click the "Please continue to the error page" it says, "No active batch"

==========
## Steps To Reproduce
---------
Click the "Cancel Account" link in a user's email

==========
## Actual behavior
---------
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information folows. Path... (blah blah... looks like it's printing out text from the whole front page)

==========
## Expected behavior
---------
A clean screen saying, "Your account has been successfully deleted."

==========
## Additional information
---------

Add any other information that could help, such as:
- Backdrop CMS version: 1.21.3
- Web server and its version: Apache (HostGator)
- Operating System and its version: unknown
- Browser(s) and their versions: FireFox and Chrome
![2022-05-08-01-bd-cancel-account-error-01](https://user-images.githubusercontent.com/16423687/167282539-cc087527-a16c-451d-890c-86c792380402.jpg)
![2022-05-08-01-bd-cancel-account-error-02](https://user-images.githubusercontent.com/16423687/167282543-1dc5b700-5460-4a9d-bc9c-7e9557224e4a.jpg)

**Comment by indigoxela** [comment]
Hi @JugglingCoder, many thanks for reporting.

Out-of-the-box I'm unable to reproduce the error.

My steps:

- User logs in
- User opens his account edit form
- User hits "Cancel account"
- Message: "A confirmation request to cancel your account has been sent to your e-mail address."
- User copies the link from the email and confirms to cancel
- Message: Myusername has been disabled.
- User gets logged out and is blocked

May we know more about your settings re accounts (/admin/config/people/settings)? Permissions (/admin/config/people/permissions#module-user)? Possibly interfering contrib or custom modules?

Your message seems very odd: "Status text: OK Response text: Create new account".

**Comment by JugglingCoder** [comment]
Thank you for your input indigoxela.  Yes, I have a Custom Hook function "bs_cloud_user_cancel_methods_alter" where bye I call a custom function which 1.) zips up the users folder, 2.) moves that folder to a "trash" folder, 3.) then deletes that users folder and finally call 4.) user_delete($account->uid);

I didn't think that function would be an issue but I spoke too soon... I should have tried the "normal" Backdrop cancellations first.  I'll try the normal cancellation methods and report back.  Hmmm... I wonder if calling "user_delete($account->uid);" before doing the zipping will work, will try that too
![2022-05-09-01](https://user-images.githubusercontent.com/16423687/167333624-cc58156f-9a96-4976-8850-92a77735f969.jpg)
.

**Comment by JugglingCoder** [comment]
This is NOT a Backdrop bug/issue, I posted too soon.  The issue is with my custom cancellation hook.  I switched to a default Backdrop cancellation method "Delete the account and its content." and it worked as expected.  Will close this issue.

**Comment by JugglingCoder** [comment]
As mentioned, this is not a Backdrop issue, custom hook issue.

**Comment by argiepiano** [comment]
Keep in mind that the account cancellation is done by a batch process, which are pretty delicate creatures - anything may throw it off, and they are hard to debug (the most successful way for me is using Xdebug).

Question: are you doing the account deleting yourself? Where are you doing it? In an implementation of hook_user_cancel()? If that's the case, that will create issues, as that hook is invoked before the batch process starts. That batch process needs the account in order to process it.

**Comment by JugglingCoder** [comment]
Thanks for your input argiepiano.

"are you doing the account deleting yourself?" - yes.  Created a custom cancel method "bs_cloud_user_cancel_methods_alter" which calls a custom function "bs_cloud_user_cancel".  In "bs_cloud_user_cancel" I zip up the users folder and at the very end just call: user_delete($account->uid);

I'm messing with it now, moving some code/functions around.  The final goal is to .zip up the user folder during account deletion (using a ZipArchiver class to do the zipping).

**Comment by argiepiano** [comment]
The problem is that `hook_user_cancel_methods_alter()` should not do any processing at all. This hook is only for adding a new radio button.

**Comment by argiepiano** [comment]
After implementing that hook you would need to implement `hook_user_cancel()`. That hook can do the zipping. Then you can modify the $method variable in that hook (you need to be sure it's passed by reference) and switch it to `user_cancel_delete`. Then let the batch do the deleting. 

In a nutshell:

- Implement `hook_user_cancel_methods_alter` to show the new method option and do nothing else
- Implement `hook_user_cancel($edit, $account, &$method)`  IMPORTANT: notice the "&" in front of method
- Do your zipping in that function. AND change `$method = 'user_cancel_delete';` before returning

That's it. The batch will then delete the account after you've done the zipping.

**Comment by JugglingCoder** [comment]
wow, thank you for your help argiepiano.  I implemented what you suggested (see code below) but a.)  the user was not deleted (but blocked) and b.) got a PHP warning:

Warning: Parameter 3 to HOOK_user_cancel() expected to be a reference, value given in module_invoke_all() (line 975 of /home/cloudbrat/public_html/core/includes/module.inc).

`function HOOK_user_cancel_methods_alter(&$methods) {
  $methods['HOOK_delete_and_zip'] = array(
    'title' => t('ADMIN_TITLE'),
    'description' => t('MY_HTML'),
    'access' => user_access('Administer permissions'),
  );
}

function HOOK_user_cancel($edit, $account, &$method) {
  HOOK_zip_cancelled_user_folder($account->uid, $account->name); // function to .zip up user folder, move it and then delete it. 
  $method = 'user_cancel_delete';
  return $method;
}`

**Comment by argiepiano** [comment]
Yes, I should have tested before suggesting 😄 . It looks like $method won't be passed as a reference, and can't be modified by the hook. 

So... it's a bit more complicated. Question: is there any scenario where you want to use the delete method and not do the zipping? If not, instead of defining a new method, you could just instead implement hook_user_predelete() to do all the zipping before the user is delete.

**Comment by JugglingCoder** [comment]
"Yes, I should have tested before suggesting" - no problem, any bit of advice/clue is helpful... I just throw it in and give it a try.

I got it working how I wanted.  Your suggestion of "hook_user_predelete()" is what worked.

I couldn't figure out how to "add" a cancel method to "hook_user_cancel_methods_alter" so I just over-wrote the default Backdrop method like:
`  $methods['user_cancel_delete'] = array(
    'title' => t('MY_ADMIN_TITLE'),
    'description' => t('MY_CUSTOM_HTML'),
    'access' => user_access('Administer permissions'),
  );`
The main reason I wanted a 'custom' method was so I could customize the text on the warning page, this works.

Then when the account is deleted the function you suggested is called,
`function hook_user_predelete($account){
  if($account->uid > 1){
		my_function_to_zip_user_folder($account->uid, $account->name);
  }
}`

In the end, pretty simple resolution:) just took a lot of trial and testing.
