### ISSUE TITLE
How to override single config-items in settings.php?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#562]
We ran into some issues over in https://github.com/backdrop-ops/backdrop-pantheon/pull/1 when trying to override a single previously-a-variable now-a-config-item now that $conf is not supported in settings.php.

`config->set()` does not work in settings.php either. 

What is the recommended approach for overriding these items?

**Comment by quicksketch** [comment]
We don't have a way of doing this in settings.php that I know of. The only values you can set in settings.php are the contents of the $settings variable and things like database URL and config directories.

I think the best way to handle setting these values would be in an install profile or in a module's hook_install() if needed.

**Comment by jenlampton** [comment]
I wonder if that's going to be sufficient for install profiles for Backdrop.  Let's keep an eye on it and see what happens in 1.0.

Closing this for now.
