### ISSUE TITLE
Update screenshot for Basis?

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5621]
Should we update the screenshot for Basis with the new cards that come installed by default? If yes, here's a resized screenshot that might work (from a default installation). 

![screenshot](https://user-images.githubusercontent.com/871421/167455479-54f5ca25-e095-4bd8-869d-96e06008b77d.png)

**Comment by stpaultim** [comment]
I assume this would be the screenshot that shows up here. 

I think we should do this.

![image](https://user-images.githubusercontent.com/3144571/167484740-20f95ac4-4384-4f17-85f3-cd3b1f92a6d7.png)

**Comment by olafgrabienski** [comment]
> Should we update the screenshot for Basis with the new cards ...?

Great idea! I've reduced the file size of the image using tinypng.com (attached below), 20 KB instead of 69. At first sight, they seem to be the same quality, @laryn what do you think?

![basis-screenshot-cards](https://user-images.githubusercontent.com/14188307/167573312-72c62d5d-986c-4169-a2e9-d9da102ed6e7.png)

**Comment by stpaultim** [comment]
@olafgrabienski - I created a PR with your image. It looks to me like the previous screenshot in Basis was 82 kb, compared to the new 20kb.

**Comment by olafgrabienski** [comment]
Thanks for the PR @stpaultim (yep, pretty reduced file size). Sandbox looks good, works for me.

**Comment by stpaultim** [comment]
Thanks @olafgrabienski - You could probably do the code review on this one as well and mark it RTBC, since there is literally no code. ;-)

It would also be nice to get a milestone.

**Comment by olafgrabienski** [comment]
Actually, I'd rather not mark both `works for me` and `rtbc`. In my opinion it's always good to have a look by another person.

Re milestone: which is the right one here?

**Comment by indigoxela** [comment]
> Re milestone: which is the right one here?

I decided for 1.22.0 - this one will ship with the new Cards type.

**Comment by BWPanda** [comment]
Thanks @stpaultim, @laryn, @olafgrabienski & @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/4070 into 1.x.

**Comment by stpaultim** [comment]
Thanks @BWPanda !
