### ISSUE TITLE
Issues and Resolutions on github not indexed by search engines

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop/backdrop-issues#5622]
As a Backdrop developer, usually with lots of custom code, once in a while I get stuck.  In my D7 days a quick search on Google usually gave me great link results usually to Drupal (api.drupal.org) or StackExchange where I could read old posts and most likely figure things out from people who already figured things out.  A typical Google search might just be 'drupal 7 hook_cancel_account' or something to that effect.

Anyway, just recently I got stuck and posted here on github.  I got great help from a couple people and I was able to resolve my issue.  However... I don't think any search engines index this "logged In" side of GitHub so people who may be searching in a standard search engine will never be able to find that resolution.

I realize that the actual core back-end Backdrop developers need GitHub, it's a great tool but there is a fine line between posts/information that developers like me may need to see and stuff only core developers really need to see.  Sometimes just little hints in core developer threads help me fix/implement something for a live real site (and that stuff never shows in Google... I have to log in and search the issue threads).

Tricky situation but I think I and most other site developers should try to post on https://forum.backdropcms.org/ first before posting here so that the information gets indexed in search engines.  All in all I think building content on the actual Backdrop website is more beneficial to Backdrop as well.

**Comment by BWPanda** [comment]
GitHub issues *are* indexed by search engines:

![IMG_20220512_075215](https://user-images.githubusercontent.com/2385329/167953920-4a99946d-7019-4e1c-bac9-6b930f6173c2.jpg)

It might just take search engines a while to index new content...

**Comment by bugfolder** [comment]
> It might just take search engines a while to index new content...

A 2-day-old issue didn't show up in a Google search, but this 6-day-old issue did (using its title as the search keywords):

https://www.google.com/search?q=Let%27s+clarify+what+we+consider+an+acceptable+level+of+impact+on+contrib+themes%2C+when+we+make+changes+to+core+1.x%3F

So, not too long.

**Comment by BWPanda** [comment]
Also: https://duckduckgo.com/?q=site%3Agithub.com%2Fbackdrop%2Fbackdrop-issues

**Comment by BWPanda** [comment]
So I think we can close this issue as 'answered', unless @JugglingCoder has anything else to add/clarify...?

**Comment by JugglingCoder** [comment]
Wow, that's interesting, thank you for taking some time to do a check.  I can't remember specific instances but I can remember doing some searches for backdrop hooks, etc. and just never being able to find a google SERP but coming here and searching issues I did manage to find stuff.  However, as PWPanda proved, the pages are being indexed.  Once again, thank you for looking into it.
