### ISSUE TITLE
Project browser: Github links for core modules don't work

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#5623]
## Description of the bug

This is a follow-up to #5003 which was merged only recently. The Github links for core modules don't work. They point to a non existent `backdrop-contrib` repo.

## Steps To Reproduce

To reproduce the behavior:
1. Go to `admin/modules'`, and look for a core module, e.g. *Administration Bar*.
2. Click on the "more" toggle link, and have a look at the line `Links: BackdropCMS.org, GitHub`
3. Hit the Github link.

## Actual behavior

The link points to `https://github.com/backdrop-contrib/backdrop` (Page not found)

## Expected behavior

Not sure. Point the link to the core repo, or don't display a link.

## Additional information

- Backdrop CMS version: 1.22.0-preview

**Comment by olafgrabienski** [comment]
The issue was first reported in https://github.com/backdrop/backdrop-issues/issues/5003#issuecomment-1124005924. See especially https://github.com/backdrop/backdrop-issues/issues/5003#issuecomment-1124082594 and below for possible reasons.

**Comment by BWPanda** [comment]
The correct behaviour here is not to display links for core modules.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/4071

**Comment by argiepiano** [comment]
LGTM 👍🏽

**Comment by olafgrabienski** [comment]
Thanks for the PR, @BWPanda ! Let's make sure it goes in the 1.22 release. (Adding milestone.)
