### ISSUE TITLE
Deleting field creates warning and notice with Layouts that use that field in a block

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5627]
## Description of the bug

This is very similar to #3263 - the difference is that the site doesn't crash in this case. Deleting a field that is displayed as a field block in a layout generates:

`Notice: Undefined index: node-field_test_field in Block->getBlockInfo() (line 198 of /Users/.../Sites/localhost/.../core/modules/layout/includes/block.class.inc). `

`Warning: array_merge(): Expected parameter 2 to be an array, null given in Block->getBlockInfo() (line 198 of /Users/.../Sites/localhost/.../core/modules/layout/includes/block.class.inc).
`

This was reported in a [forum post](https://forum.backdropcms.org/forum/error-after-deleting-node-field).

## Steps To Reproduce
1. Add a field to a content type
2. Create content
3. Create a layout and add the node you created above as Context
4. Place a field block for the field your created above anywhere in the layout
5. Visit the url of the layout to check that it displays correctly
6. Delete the field from the content type
7. Visit the same url above and see the warnings and notices  

## Actual behavior

This produces the notices above.

## Expected behavior

As suggested in #3263, this should not generate php warnings - perhaps it should display a broken block notice 

## Additional information

Backdrop 1.22.0-preview

**Comment by argiepiano** [comment]
In addition to these warnings, you get additional warnings when you go to Configure Blocks for the layout:

`Notice: Trying to access array offset on value of type null in FieldBlock->createPseudoInstance() (line 317 of`

Etc.

**Comment by argiepiano** [comment]
I have pushed a potential fix for this: https://github.com/backdrop/backdrop/pull/4075

The changes are pretty minimal. It catches the issue early on, when Layout finds the appropriate handler class name to use to create a Block. If it finds out that the field is not available, then it choses the handler `BlockBroken`. This has the benefit to fix both issues: the warnings produced when rendering the layout, and the warnings produced when editing the layout through the UI. Since the UI now shows a  `BlockBroken`, this will also alert the admin that something is wrong.

Even though adding a very specific `if` statement to check for the plugin type `field_block` may seem at first a bit "hacky," after second though it seems warranted, since Field API fields is a required part of core and can't be disabled.  

This PR additionally fixes a warning generated when loading the context for rendering, when dealing with a `BlockBroken` handler. 

I'd love to hear alternatives. I thought of catching the problem in the `__construct` method of `FieldBlock`, but that would mean that the handler has already been instantiated, and there is no possibility of switching to a `BlockBroken` handler.

@docwilmot - you seem to be very familiar with Layouts (you created that API, no?). Would love some thoughts and review, please!

**Comment by argiepiano** [comment]
Oops, many failing tests - will need to check this again... later.

**Comment by argiepiano** [comment]
New commit pushed, and all tests passing. Apparently there are situations when the plugin name for `field_block` plugin delta only contains two parts (`module:delta`) instead of three (`module:delta:field_name`). This commit checks for availability of the third part.

I'd appreciate tests and code review!

**Comment by indigoxela** [comment]
Not exactly the same, but issue #4619 seems sort of related.

**Comment by argiepiano** [comment]
> Not exactly the same, but issue #4619 seems sort of related.

Yes, it seems like this is a similar case. I see there is a PR for that issue that takes a different approach from the PR I submitted here. I haven't had a chance to look into it, but it may be the case that that PR also solves the issue reported here. I'll try to do some testing there with this context. 

I hope we can get some traction with these two issues. The situation is not uncommon - deleting a field or a node, which produces all sorts of warnings etc.

**Comment by indigoxela** [comment]
> The situation is not uncommon - deleting a field or a node ...

I agree, we should really fix this. Will give testing a try soon. The PR approach (BlockBroken) looks very promising.

**Comment by indigoxela** [comment]
It seems to me, either the Node or the Layout module should implement hook_field_delete_instance().

Probably the latter, as field deletion causes no trouble when displaying fields as part of the node (as regular fields), but in Layouts (with fields as blocks) field instance deletion *does* cause problems.

Or are there other opinions?

**Comment by indigoxela** [comment]
A quick experiment - the following fixes the problem with cached (stale) data and notices/warnings on node view:

```
/**
 * Implements hook_field_delete_instance().
 */
function layout_field_delete_instance($instance) {
  cache('layout_path')->flush();
}
```
This makes sure, that also when *viewing* the node, the cached information about the field block is "BlockBroken" (and no notices anymore).

Might need a little more testing.

**Comment by argiepiano** [comment]
@indigoxela THANK YOU for taking the time to look into this. Yes, I was thinking yesterday that flushing layout caches might be needed for this to work. Using `layout_field_delete_instance()` looks like a good solution. I'll test.

It'd be great to get @docwilmot's thoughts on this approach (catching the issue at the time of assigning the class name to each block, and using BlockBroken there). I haven't yet looked at #4619 to see if this approach (with modifications) may apply there as well. I'll try to do that today.

**Comment by indigoxela** [comment]
I took a quick look at  #4619 and my conclusion is, that the other issue is mostly unrelated. The immediate problem (php error) got fixed already. The only remaining task over there is a better UX with helpful hints what needs to be done to fix that "missing content".

**Comment by argiepiano** [comment]
@indigoxela, I have pushed a commit that adds the code you suggested for flushing the layout_path cache when there is a field instance deletion. 

I have done some more testing and things seem to work well now. I'd appreciate it if you could do a code review and mark this as WFM if possible. We also need to add the a milestone. 

Thanks!

**Comment by indigoxela** [comment]
@argiepiano sure, that failure is a random one.

I've left a tiny suggestion re syntax/readability. Will do proper testing soon.

**Comment by argiepiano** [comment]
Thanks. Change made.

**Comment by indigoxela** [comment]
Another round of testing:

- Create a new content type (only default fields)
- Add a custom layout, path node/%, visibility condition on new type
- Add the *body* field as a block
- Verify that everything displays as expected
- Delete this content types body field
- Visit the node/X page - no messages, body field gone, everything as it should be
- Visit the layout admin page (/admin/structure/layouts/manage/custom_node_layout)

:thinking: no "broken block". In the admin form the block still shows as "Field body" - no hint that it got removed from that node type. Probably because this node type's instance is gone, but other types still have the field. This may be as expected, but it surprised me a bit.

@argiepiano is this desired behavior? The main purpose of this issue - messages and warnings is fixed. :+1:

**Comment by argiepiano** [comment]
> no "broken block". In the admin form the block still shows as "Field body" - no hint that it got removed from that node type. Probably because this node type's instance is gone, but other types still have the field. This may be as expected, but it surprised me a bit.

Technically, after following your steps, this is not a broken handler because `body` exists in other node bundles, and therefore you could possibly load a node of a bundle that actually has `body`  - and you would want that field block to display it. So yes, that's the desired behavior. It's only broken if there are no instances of the field in any bundle.

Thanks for the additional testing @indigoxela !!!

**Comment by argiepiano** [comment]
If you are happy with the testing, would you be willing to set this to "works for me"? Also code-review perhaps? Thanks again.

**Comment by indigoxela** [comment]
> ... yes, that's the desired behavior. It's only broken if there are no instances of the field in any bundle.

Many thanks for verifying. That was actually my own conclusion after thinking it over a bit more.

So, yes, this works for me. :+1:

**Comment by indigoxela** [comment]
I finally found the time to take a closer look (locally, with some "debug()").

Great work, this is RTBC.

**Comment by argiepiano** [comment]
Thank you! Can someone add a milestone please?

**Comment by quicksketch** [comment]
Looks good to me. I wasn't sure about adding field-specific code into `layout_get_handler_name()`, but as fields are a pretty central feature I think the exception checking is fine. If we figure out a way to universally handle plugin names with 3 parts, we could update this section of code later.

I added a code comment suggestion to the PR that tries to clarify the purpose a little: https://github.com/backdrop/backdrop/pull/4075/files#r922726831 Would it be okay to include that as well?

**Comment by argiepiano** [comment]
> Would it be okay to include that as well?

Done! Thanks @quicksketch. I agree that all the field-specific checking is not very elegant. I think using a Factory or Builder pattern for creating block classes could encapsulate things better and avoid the current approach. But that would require some major reworking...

**Comment by quicksketch** [comment]
Thanks @argiepiano! I merged https://github.com/backdrop/backdrop/pull/4075 into 1.x and 1.22.x. Thanks @indigoxela for the reviewing and testing!
