### ISSUE TITLE
[UX] Rephrase "database updates" so that it is clear that they also perform config updates.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5630]
It seems that perhaps the process that is currently labeled "Backdrop database update" (**/core/update.php**) could be named more accurately. This process includes any update hook at all, and may include or be exclusively config updates, for example. Should we consider changing this term/phrase?

**Comment by olafgrabienski** [comment]
Good idea! As a start, we could list places and term variations which refer to the (former) database update.

**Comment by bugfolder** [comment]
How about "Backdrop site update"?

**Comment by bugfolder** [comment]
Here's a PR that changes "database update" to "site update" in most places (unless we're actually only changing the database).

**Comment by laryn** [comment]
I looked over the changes and the code looks good.

**Comment by stpaultim** [comment]
This change makes sense to me.

**Comment by olafgrabienski** [comment]
I also like the direction!

@bugfolder Can you also mention _configuration files_ in the first sentence on `core/update.php`?

> Use this utility to **update your database** whenever you install a new version of Backdrop CMS or one of the site's modules.

**Comment by bugfolder** [comment]
> Can you also mention _configuration files_ in the first sentence on `core/update.php`?

I changed it from "update your database" to "update your site", similarly to other changes. That block of text also mentions "This update utility will alter your database and config files," so config does get mentioned.

I notice that all of that text is not wrapped in `t()`, which I assume is for a good reason; I'm just curious as to why.

**Comment by klonos** [comment]
Coming late to this: Yes please! 👍🏼 💯 

The phrase "System updates" is already reserved for the core version updates, as well as contrib and customer project updates under _Configuration_ >> _System_ >> _System updates_ (`admin/config/system/updates`). So "site updates" seems sensible/appropriate to me too.

The PR needs a rebase and has conflicts that will need to be resolved.

**Comment by klonos** [comment]
> I notice that all of that text is not wrapped in `t()`, which I assume is for a good reason; I'm just curious as to why.

I am also not 100% sure about that, but when I've asked previously, I think that the answer was that `t()` might not be loaded during that stage. It could be an oversight though 🤷🏼

**Comment by herbdool** [comment]
I've reviewed the code and tested. Looks good now.

**Comment by quicksketch** [comment]
Awesome, that's a lot of agreement for a string change! I merged https://github.com/backdrop/backdrop/pull/4642 into 1.x and 1.28.x. Thanks @bugfolder, @laryn, @herbdool, @olafgrabienski, @klonos, and @indigoxela!
