### ISSUE TITLE
Notices thrown when disabling (not uninstalling) OG and OG UI after creating group type and group content type

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5635]
## Description of the bug

A bunch of PHP notices are thrown when disabling (not uninstalling) og and og_ui after having created a group content type and a group content content type

## Steps To Reproduce

1. Enable og and og_ui
2. Create a group content type and a group content content type
3. Disable og_ui, then disable og and watch the notices appear

<img width="1029" alt="Screen Shot 2022-05-23 at 9 49 00 PM" src="https://user-images.githubusercontent.com/9938978/169945045-a1ee2a5c-43dd-43c4-9217-4fbdcf9d4a0e.png">

Add any other information that could help, such as:
- Backdrop CMS version: 1.22.0

**Comment by argiepiano** [comment]
In fact the notices remain on eery page refresh. Disabling og makes some behavior callbacks for the entityreference fields unavailable, which results on these notices.

**Comment by argiepiano** [comment]
Furthermore, the notices remain after uninstalling og and og_ui. This is definitely a bug we want to fix

**Comment by olafgrabienski** [comment]
@argiepiano Do you think this is a Backdrop core issue? I'm asking because the notices seen in the screenshot seem to come from the Entity Reference module.

**Comment by argiepiano** [comment]
My apologies, this issue should have gone to the OG issue queue, and probably entityreference - not the core queue. Closing here and reopening there.
