### ISSUE TITLE
Layout context static caching creates issues when there is a layout relationship

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5636]
## Description of the bug

This issue was first reported on [Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Layout.20relationship.20question.20.28bug.3F.29/near/284000893). 

This is related to two issues:
- #5483 (fixed and merged into 1.22.0). This PR added new static caching capabilities for the context array into the Layout class
- #5482 (not yet merged) fixed an issue with relationships - the plugin was passing the wrong context data

#5482 worked fine before #5483 was merged. After the merge, the cache capabilities interfered with the relationship fix.

## Steps to reproduce

1. Start with a 1.22.0 Backdrop core
2. Patch your core with the unmerged #5482 
3. Add a field to user entities and populated it with values
4. Create a layout with path node/% and add a relationship to Author of Content (in position 2).
5. Edit the layout and insert a field block to display the value of the user field added in step 1.  Be sure to select "Author of Content in position 2" for the User field in the block config
6. Visit any node

## Actual behavior

The user field is not shown.

## Expected behavior

The user field should be shown.

## Additional information
- Backdrop CMS version: 1.22.0

PR coming soon

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4080

@docwilmot I just submitted a simple PR that incorporates your changes in #5482 and adds a couple more changes. 

I decided to keep your use of the static cache intact, and added the line you suggested in Zulip. After that, there was one small change required in an if statement in layout.class.inc that was throwing the whole thing off (it was running `getContextsFromRelationships()` before the node context was fully set, which is what you were intending to avoid with #5482).

I've tested locally and it works well. Please test. Let's get this serious bug fixed.

IMPORTANT: since this PR includes your changes in PR https://github.com/backdrop/backdrop/pull/4046, that PR should probably be closed (or you can modify and add what I had here, and close this one).

**Comment by docwilmot** [comment]
We shouldnt have duplicate issues though, so we should close this one, keep https://github.com/backdrop/backdrop-issues/issues/5482, and close my PR.

**Comment by argiepiano** [comment]
Duplicate of #5482

**Comment by argiepiano** [comment]
Done. Closed this one, changed the "Fixes" magic word of my PR and closed your PR
