### ISSUE TITLE
Consolidate code from backdrop-ops templates into backdrop-contrib templates

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5637]
Backdrop has repositories for modules, themes and layouts that are templates - meaning you can use them to build a new custom project, and certain files (e.g. README, LICENSE, .info, etc.) are already in-place and ready to go. The problem is that we have duplicates...

The original templates (as discussed in https://github.com/backdrop-ops/contrib/issues/344) were:
- https://github.com/backdrop-ops/module-template
- https://github.com/backdrop-ops/theme-template
- https://github.com/backdrop-ops/layout-template

The newer template are:
- https://github.com/backdrop-contrib/module
- https://github.com/backdrop-contrib/theme
- https://github.com/backdrop-contrib/layout

We can't just delete the old ones in favour of the new ones though, as the old ones have some things the new ones don't; e.g. showing how to implement hook_config_info().

Also, we have example README and LICENSE files here:
- https://github.com/backdrop-ops/contrib/tree/main/examples

What I'd like to do is:
1. Have one, canonical example of a module, theme and layout (including their REAMDE files, etc.)
2. Decide where these examples should live (backdrop-ops, backdrop-contrib, ...)
3. Move/update the templates/files listed above to the new location, deleting the old, duplicate ones
4. Add links to the appropriate places (e.g. https://github.com/backdrop-ops/contrib/blob/main/README.md, sub-pages of https://docs.backdropcms.org/documentation/developing-for-backdrop) to these new templates so that people know about them and can use them

**Comment by jenlampton** [comment]
In order for a repository to be a GitHub "template" I thought that it needed to be in the same group, which is why I crated the newer ones in `backdrop-contrib`. We should keep them in that location, but I also think we should be careful not to loose anything from the older projects! I'm sad that I missed those initially.

**Comment by jenlampton** [comment]
It appears as though we are still limited as to where we can place the repositories. 

There are only 3 templates available for the `backdrop-contrib` group, and those are the ones located in the contrib group:
<img width="978" alt="Screen Shot 2022-06-02 at 3 20 29 PM" src="https://user-images.githubusercontent.com/397895/171748043-b1e9d29f-05e0-4a99-82c9-1cb14e0d2b47.png">
<img width="796" alt="Screen Shot 2022-06-02 at 3 20 45 PM" src="https://user-images.githubusercontent.com/397895/171748059-579d04cb-85b6-4ceb-a949-e8f665b05117.png">

However, for the 30 people who also have access to backdrop-ops, they could choose to use the templates located in the backdrop-ops group.
<img width="1401" alt="Screen Shot 2022-06-02 at 3 25 42 PM" src="https://user-images.githubusercontent.com/397895/171748509-b4d40d02-6110-4a83-ac27-0e3ae21ac666.png">
But then change the owner to `backdrop-contrib`:
<img width="807" alt="Screen Shot 2022-06-02 at 3 26 10 PM" src="https://user-images.githubusercontent.com/397895/171748544-f53d58d7-85b0-47f7-a180-f02b7f2cc217.png">

Because keeping the templates in backdrop-ops will only work for 30 people, the "official" location of the templates should be in the contrib group (at least, until GitHub changes this limitation).

**Comment by BWPanda** [comment]
> It appears as though we are still limited as to where we can place the repositories.

Not really. I just signed into GitHub with my work account and I can see the green "Use this template" button on both https://github.com/backdrop-ops/module-template and https://github.com/backdrop-contrib/module. See also https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template

I think you're referring to the drop-down menu on https://github.com/new which lists templates from repos you're associated with. But as per GitHub's documentation:

> Creating a repository from a template is similar to forking a repository...

To fork a repo, you go to the repo and click the button. It's the same for templates: go to the template and click the button. In that sense it doesn't matter which group the templates are in.

But in order to move this forward I'll start migrating things over to the repos in `backdrop-contrib`.

**Comment by BWPanda** [comment]
I'm listening to the meeting where this was discussed and it seems that the preference is actually to have these in backdrop-ops (which is my preference too, since they're not actually contrib projects), so I'll start updating those ones with necessary changes from backdrop-contrib. They also already have 'template' in the name 👍🏻

**Comment by BWPanda** [comment]
@jenlampton I've updated https://github.com/backdrop-ops/module-template so far. Can you please check to see if I've copied everything of use from https://github.com/backdrop-contrib/module and https://github.com/backdrop-ops/contrib/tree/main/examples ?

**Comment by jenlampton** [comment]
Hm. I tested the "use this template" button yesterday, but it was not available on the backdrop-ops templates. That's important, though, as I don't think anyone will start from the template itself.

The only place the templates really need to show up is when you click the "new" button on https://github.com/backdrop-contrib:

<img width="961" alt="Screen Shot 2022-06-03 at 4 03 14 PM" src="https://user-images.githubusercontent.com/397895/171964953-c8fda023-6e0d-416d-9500-deef3fd5b164.png">

**Comment by jenlampton** [comment]
The only thing that's missing is the `admin.inc` file. Everything else was better in the ops templates than the contrib templates. :)

If we are going to include sample functions (which I think is a great idea!) then the name of the module should not include an underscore -- `mymodule` would be fine. It is easier for people to understand module/hook naming conventions when the name of the module is visually distinct from the name of the hook.

**Comment by BWPanda** [comment]
> I tested the "use this template" button yesterday, but it was not available on the backdrop-ops templates.

@jenlampton Others are able to see the green "Use this template" button: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/GitHub.20templates Can you please try again?

**Comment by jenlampton** [comment]
I can, but that's not really important. Were you able to get the projects set up as templates for Backdrop contrib? I did some extensive research on that, but it still appears impossible. Let me know if you found otherwise!

**Comment by stpaultim** [comment]
@jenlampton - Maybe I am missing the point of the discussion, but I just went to this URL: https://github.com/backdrop-ops/module-template

I was able to use that template to create a new project in Backdrop Contrib. 

![image](https://user-images.githubusercontent.com/3144571/173484117-2637dacd-a7b1-4727-86be-e8549e009ef1.png)

The Bad News is that I created a project in Backdrop Contrib and now I can't delete it (for good reasons). If anyone with access would be so kind as to delete this test repo. 

https://github.com/backdrop-contrib/test

**Comment by stpaultim** [comment]
OK, I reread the entire issue and now see what @jenlampton  is looking for. When you create a new project, there is an option to select a template - and here is where we are unable to link to a template in a different group. 

This page has a templates button, but that templates button DOES NOT use templates from outside of this group (apparently).

https://github.com/organizations/backdrop-contrib/repositories/new

**Comment by BWPanda** [comment]
I have moved all code to https://github.com/backdrop-contrib/module_template and deprecated https://github.com/backdrop-ops/module-template.

@jenlampton Please see a suggestion I have in https://github.com/backdrop-contrib/module_template/issues/1 and let me know what you think.

Will work on the other repos next (theme, layout).

**Comment by BWPanda** [comment]
All done. backdrop-contrib now has the latest template repos, and further tweaks can be discussed in their respective issue queues.

Closing this issue now.
