### ISSUE TITLE
Create a new Security section on Configuration page

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5639]
## Description of the need

It always bothered me that on Drupal various spam-fighting and/or other security-related modules ended up placing their configuration links in different parts of the Configuration page. The choices were pretty arbitrary - I've seen such modules under Administration, Content Authoring, System or other sections.  

## Proposed solution

Let's make it right on Backdrop and create a separate section dedicated to spam  and security-related modules. It would make for creators of such modules easier to decide where to place the configuration links for their modules, but also send a clear message for end-users: Backdrop community gives special place for security. 

The section would look like below:

![security](https://user-images.githubusercontent.com/56604405/171584881-a3e90912-60e9-4bac-bdbe-5a263f631b18.jpg)

I'm ready to file a PR if most users support this idea.

**Comment by laryn** [comment]
I like this idea, I think. Perhaps using a shield icon?

Also related: https://github.com/backdrop/backdrop-issues/issues/3624

**Comment by alanmels** [comment]
Yes, shield would be most appropriate.

**Comment by alanmels** [comment]
I didn't know https://github.com/backdrop/backdrop-issues/issues/3624 existed. Apparently didn't do good work searching either. I wonder why the other issue didn't go through.

**Comment by indigoxela** [comment]
One thing seems a bit tricky to me: the security / anti-spam modules in the example are contrib. How can we evaluate in core, which modules belong to that section? For example: do all anti-spam modules belong there? So we might also consider this a contrib candidate?

Maybe loosely related is this contrib module: https://github.com/backdrop-contrib/security_review

Sorry, @alanmels closed this issue, while I was writing. :wink:

**Comment by stpaultim** [comment]
I think he just closed it in favor of the existing issue.

**Comment by alanmels** [comment]
@indigoxela It is up to contrib modules to choose where to place their modules. For example, I had to choose Content section for the Protected Forms, because there was no other better section. The Configuration page is not for only core modules, but also for contributed modules and better categorization would be nice.
