### ISSUE TITLE
Fixed: PHP Notice: Undefined offset: `0` in `views_many_to_one_helper->ensure_my_table.`

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5643]
## Description of the bug

I'm seeing these notices on a particular site in development:

> Notice: Undefined offset: 0 in views_many_to_one_helper->ensure_my_table() (line 793 of /code/core/modules/views/includes/handlers.inc).

> Notice: Trying to access array offset on value of type null in views_many_to_one_helper->ensure_my_table() (line 793 of /code/core/modules/views/includes/handlers.inc).

This line of code is right in the middle of the mess that was https://github.com/backdrop/backdrop-issues/issues/3415 and I think there's a minor logic flaw here. I'll submit a PR if it's as easy to solve as I think.

**Comment by argiepiano** [comment]
Hi @laryn. From a logic point of view this fix makes sense ($group can be FALSE as per the statement right above). Still it may be helpful to have steps to reproduce this error so that we can test?

**Comment by indigoxela** [comment]
Same here, unable to reproduce. @laryn can you provide steps (or a sample view)?

**Comment by laryn** [comment]
I was afraid you were going to say that. :sweat_smile: I believe the culprit is a View block placed on a node's layout, which has contextual filters:

- Content: Has taxonomy term ID (options: Provide default value of **taxonomy term ID from URL**; **Load default filter from node page**; **Limit by vocabulary**;
- Content: Nid (options: Provide default value of **Content ID from URL**)

I will try to verify this on a vanilla install.

**Comment by laryn** [comment]
Yes, here's a sample view. 
[views.view.related.json.txt](https://github.com/backdrop/backdrop-issues/files/8843080/views.view.related.json.txt)

Import this and then do the following:

1. Place this view's block on a layout that affects nodes.
2. Add or edit a few "Post" nodes to include a value in the "Tags" field.
3. View one of those nodes.

**Comment by argiepiano** [comment]
@laryn, I'm afraid I can't reproduce the issue. I'm working with a clean install.

BTW the block seems to work as intended only if I remove the  Content: Nid contextual filter - only then do I get a list of nodes related by the taxonomy term (including the node being viewed).

If I leave as is - only the node being viewed is listed in the block. But there are no warning.

**Comment by argiepiano** [comment]
The patch works for me - it fixes the problem here.  Logic seems sound. I've done some testing with filters (which also use this handler helper) and  they seem unaffected. RTBC

**Comment by indigoxela** [comment]
@laryn many thanks for providing the sample view. Confirmed the bug and that the PR fixes it, milestone set. :+1:

**Comment by BWPanda** [comment]
Thanks @laryn, @argiepiano & @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/4084 into 1.x and 1.22.x.
