### ISSUE TITLE
Removing custom contexts from layouts is broken

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#5645]
## Description of the bug

Clicking the "remove" link in layout configuration pages to remove a custom context doesnt work; the spinner spins, the context remains in the table. A second click or a page refresh clears it. Errors in watchdog.

## Steps To Reproduce

1. Create a new site with latest 1.x or 1.22 (or create one on Demo site)
2. Got to `admin/structure/layouts/manage/home/configure` or `/admin/structure/layouts/manage/dashboard/configure` or create your own layout.
3. Click "Add context" and add a Node context. After the dialog closes, the context table will show your new custom context and links to remove or edit
4. Click remove

## Actual behavior

The context doesnt disappear as expected.
`Notice: Undefined index: node1 in layout_settings_form_context_remove() (line 384 `
`Notice: Trying to get property 'settings' of non-object in layout_settings_form_context_remove() (line 384 `
`Notice: Trying to access array offset on value of type null in layout_settings_form_context_remove() (line 384`

## Expected behavior

The context should be removed from the context table with no error messages

## Additional information

v1.22

**Comment by indigoxela** [comment]
Ooops, confirmed: the spinner spins, but nothing happens. Actually the context *does* get removed. If saving the layout without any page reload or else, it's gone when opening that page again.

I can not reproduce any php notices, though. Nothing in my dblog. Are you sure, these notices are caused by the ajax problem?

Any idea, what caused that regression?

**Comment by docwilmot** [comment]
I got those errors in dblog from the Demo site, so it wasnt a local thing. They show up after you click remove the second time.

I'm wondering if this may be yet another consequence of caching contexts.

**Comment by indigoxela** [comment]
> They show up after you click remove the second time.

Yes, I can confirm that, the second button click creates three notices. Makes sense, as one tries to remove something, that's not there anymore.

> I'm wondering if this may be yet another consequence of caching contexts.

Would it be possible to reset that cache in the ajax callback?

**Comment by argiepiano** [comment]
@docwilmot, confirmed. 

All that's needed is clearing the static cache variable `getContexts` within `Layout::clearContexts()`. This solved the problem for me. IF this static cache is not cleared, when the form is updated in `layout_settings_form_update_layout()` the old cached contexts are retrieved (line 978 of `layout.admin.inc`)

PR provided:

https://github.com/backdrop/backdrop/pull/4085

**Comment by docwilmot** [comment]
Confirmed this fixes the issue, and also fixes the issue in Mini Layouts Module (https://github.com/backdrop-contrib/mini_layouts/issues/31)
RTBC.

**Comment by argiepiano** [comment]
Small clarification. After removing the context the layout saved on tempstore is correct and fresh, the removed context is not saved. The issue happens because the form uses the cached contexts to rebuild the form.

**Comment by BWPanda** [comment]
Thanks @argiepiano, @docwilmot & @indigoxela. I've merged https://github.com/backdrop/backdrop/pull/4085 into 1.x and 1.22.x.

**Comment by argiepiano** [comment]
@BWPanda, I believe @quicksketch changed the static cache for getContexts() in a different PR (the one about the "author of node" relationship). I can't confirm this without looking at it, and can't do it right now, but if this is the case, then the PR here will be resetting an inexistent static cache. 

I'll look later and will let you know.

**Comment by argiepiano** [comment]
Confirmed. PR https://github.com/backdrop/backdrop/pull/4105  (which hasn't been merged) changes the name of the cache from `__FUNCTION__` to `__METHOD__`. I added a note in that PR so that any calls to `backdrop_static_reset('getContexts')` gets changed to `backdrop_static_reset('Layout::getContexts')`.
