### ISSUE TITLE
When upgrading from Drupal 7, the required File module should be automatically enabled.

### ISSUE THREAD

**Issue by abetomas** [backdrop/backdrop-issues#5648]
Fresh from a Drupal-7 migration and after running core/update.php, I tried to add the Hero block to layout (theme: Basis, layout:Moscone Flipped).  

Description of the bug
**_Adding the Hero block does nothing, there was no message that block was added._**

I checked the error log and found this message:
*******
**_Location_**	http://_(mysitename)_/system/ajax
**_Referrer_**	http://_(mysitename)_/admin/structure/layouts/manage/home
**_Message_**	PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'base.type' in 'field list': SELECT base.`fid` AS `fid`, base.`uid` AS `uid`, base.`filename` AS `filename`, base.`uri` AS `uri`, base.`filemime` AS `filemime`, base.`filesize` AS `filesize`, base.`status` AS `status`, base.`timestamp` AS `timestamp`, base.`type` AS `type` FROM {file_managed} base WHERE (`base`.`fid` IN (:db_condition_placeholder_0)) ; Array ( [:db_condition_placeholder_0] => 0 ) in DefaultEntityController->load() (line 340 of ../public_html/_(mysitename)_/core/modules/entity/entity.controller.inc).
*******

Additional information
- running on GoDaddy shared setup
- manually installed backdrop 1.22.0
- used Firefox/Firefox-Developer
- _error does not appear on a newly installed backdrop site (with no migration from D7), I can add Hero block and other blocks on layout_

**Comment by indigoxela** [comment]
Hi @abetomas,

many thanks for reporting and welcome to Backdrop.

I don't have an immediate answer but want to share some background info re the PDOException:

```
Column not found: 1054 Unknown column 'base.type' in 'field list':
```

That column got added to the file_managed table in an update hook (file_update_1003). If it's not there in your upgraded install, I suspect something went wrong when running the db updates.

Now some questions:

There was probably a lot going on, but do you happen to remember if there were any warnings or errors while running the db updates? And out of curiosity, did the following update hooks for the file module run successfully? You can verify that by checking your active config directory for the file "file.settings.json".

Another thing to check: go to /admin/structure/file-types - what do you see there?

And of course, have a look at the status page on /admin/reports/status and the logs on /admin/reports/dblog for other warnings or errors.

Which instructions did you follow for your upgrade? Was it [that one](https://docs.backdropcms.org/documentation/step-3-upgrade-the-drupal-site)?

Together we'll be able to figure out, what went wrong. :crossed_fingers:

**Comment by argiepiano** [comment]
Thanks for posting @abetomas, and for your help @indigoxela. In addition to what @indigoxela said, I have a hunch that the Hero addition problem may not be directly related to the PDOException - unless you were trying to add an image file to the Hero block.

**Comment by abetomas** [comment]
> Thanks for posting @abetomas, and for your help @indigoxela. In addition to what @indigoxela said, I have a hunch that the Hero addition problem may not be directly related to the PDOException - unless you were trying to add an image file to the Hero block.

I was not trying to add an image.  I just added text to the Hero block and clicked the 'ADD BLOCK' button.  There was no response and the add block screen remained (with the error message above in the log).

**Comment by abetomas** [comment]
> Hi @abetomas,
> 
> many thanks for reporting and welcome to Backdrop.
> 
> I don't have an immediate answer but want to share some background info re the PDOException:
> 
> ```
> Column not found: 1054 Unknown column 'base.type' in 'field list':
> ```
> 
> That column got added to the file_managed table in an update hook (file_update_1003). If it's not there in your upgraded install, I suspect something went wrong when running the db updates.
> 
> Now some questions:
> 
> There was probably a lot going on, but do you happen to remember if there were any warnings or errors while running the db updates? And out of curiosity, did the following update hooks for the file module run successfully? You can verify that by checking your active config directory for the file "file.settings.json".
> 
> Another thing to check: go to /admin/structure/file-types - what do you see there?
> 
> And of course, have a look at the status page on /admin/reports/status and the logs on /admin/reports/dblog for other warnings or errors.
> 
> Which instructions did you follow for your upgrade? Was it [that one](https://docs.backdropcms.org/documentation/step-3-upgrade-the-drupal-site)?
> 
> Together we'll be able to figure out, what went wrong. 🤞

Thank you for your response.  Yes I followed the Backdrop migration guidelines you mentioned.

 I re-did the migration to replicate.  
 
 There were several **messages after running update.php**, some were:
-      Warning: file_put_contents(temporary://fileFIWjP0): failed to open stream: "BackdropTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 2105 of /.../public_html/_(mysitename)_/core/includes/file.inc).  The file could not be created.
   note: there were several warning messages like this referring to different files
 -     Security warning: Couldn't write .htaccess file. Please create a .htaccess file in your temporary:// directory which contains the following lines:
    - - - -
   Turn off all options we don't need.
  Options -Indexes -ExecCGI -Includes
  .... more...
  BTW, the web folder already contains the .htaccess file.  The message is referring to a "temporary://" What folder should I add this file?
  
**file.settings.json** does not exist in active directory
/www/_(mysitename)_/files/config_xxxxxxxxxx/active$ ls -l file.settings.json
ls: cannot access file.settings.json: No such file or directory

**/admin/structure/file-types** 
there is no option for /admin/structure/file-types in the drop-down list

As a background, I actually originally started the site migration from Drupal-6, Drupal-7, and finally to Backdrop.  Please see attached text file of the modules, it has module artifacts from D6 and D7.
[drush-pml.txt](https://github.com/backdrop/backdrop-issues/files/8885140/drush-pml.txt)

Please let me know if you need other info.  Thanks again.

**Comment by abetomas** [comment]
More messages ... I wonder if this is related to the error I mentioned earlier

I was changing the default layout to "Moscone Flipped".  I got a blank screen after attempting to change layout.  I refreshed the page and went back to the "/admin/structure/layouts/default layouts/manage block" and layout was changed to "Moscone Flipped"
- Notice: Undefined property: stdClass::$delta in layout_get_block_usage() (line 3434 of /...../public_html/_(mysitename)_/core/modules/layout/layout.admin.inc).  
- Warning: Creating default object from empty value in layout_get_block_usage() (line 3433 of /...../public_html/_(mysitename)_/core/modules/layout/layout.admin.inc).
- Notice: Undefined index: cd4d033d-3f67-4191-8655-85ee758877c0 in layout_get_block_usage() (line 3432 of /...../public_html/_(mysitename)_/core/modules/layout/layout.admin.inc).
- Notice: Undefined index: cd4d033d-3f67-4191-8655-85ee758877c0 in layout_get_block_usage() (line 3432 of /...../public_html/_(mysitename)_/core/modules/layout/layout.admin.inc).

**Comment by indigoxela** [comment]
Many thanks for the infos, we're narrowing it down...

>  Warning: file_put_contents(temporary://fileFIWjP0): failed to open stream: "BackdropTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() ...  The file could not be created.

Can you check your _Drupal 7_ install for the setting of the "Temporary directory" on /admin/config/media/file-system
Seems like this path either doesn't exist for Backdrop, or it's not writable by the webserver user.

All those messages regarding the file usage are also caused by the faulty upgrade.

The fact that file.settings.json does not exist in active directory means, the upgrade wasn't successful at all - not only hook file_update_1003 failed (the db table column didn't get created), but also the follow-up hooks. Another symptom for that is that the file module seems to be disabled after your upgrade (according to drush pml) - which isn't possible in Backdrop, as it's one of the required modules.

Let's do it step by step - check the "Temporary directory" file system permissions. And also the "Public file system path". And compare the broken Backdrop settings with the (working) D7 settings (both on /admin/config/media/file-system).

**Comment by abetomas** [comment]
Thanks for your response.  I checked the D7 site.  

**The 'file' module was disabled in drupal.**  I will enable and give you feedback.  I will have to re-review the backdrop migration guide to make sure I did not miss anything.

The media file settings are set to sites/default/tmp (for both D7 and Backdrop) with permissions 775.

Thanks, I will get back to you.

**Comment by abetomas** [comment]
> Thanks for your response. I checked the D7 site.
> 
> **The 'file' module was disabled in drupal.** I will enable and give you feedback. I will have to re-review the backdrop migration guide to make sure I did not miss anything.
> 
> The media file settings are set to sites/default/tmp (for both D7 and Backdrop) with permissions 775.
> 
> Thanks, I will get back to you.

**_I am now able to add the Hero block to the Layout_**  (theme: Basis, layout:Moscone Flipped). 
Based on your suggestions, I went back to the D7 site and enable the file module.  I also disabled/uninstalled modules following notes from migration guide. 
- the error "Column not found: 1054 Unknown column 'base.type' in 'field list': SELECT ... from FROM {file_managed} base " no longer appears in the log.
- 'file' module now enabled (see attached updated-drush-pml.txt)  
[updated-drush-pml.txt](https://github.com/backdrop/backdrop-issues/files/8887626/updated-drush-pml.txt)
- "file.settings.json" exists in active config directory

However, I still get the warning message below.  It is a warning message, could I assume I can ignore it for now?
- Warning: file_put_contents(temporary://filertExxd): failed to open stream: "BackdropTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 2105 of /....../public_html/_(mysitename)_/core/includes/file.inc).

_Unless you have suggestions for other fixes/tweaks, I can close this bug report on "adding Hero block"._  

**Thank you so much for your help.**

**Comment by indigoxela** [comment]
> The 'file' module was disabled in drupal

Interesting. You didn't need any file uploads in your Drupal install? This seems like something that needs to get covered by the upgrade, though. In Drupal it's possible to have that module disabled, in Backdrop the File module is necessary. We probably should take care of enabling it in an update hook.

> Warning: file_put_contents(temporary://filertExxd): failed to open stream

Do you happen to know, what triggers that warning? Do file uploads in general work?

**Comment by abetomas** [comment]
> > The 'file' module was disabled in drupal
> 
> 
> 
> Interesting. You didn't need any file uploads in your Drupal install? This seems like something that needs to get covered by the upgrade, though. In Drupal it's possible to have that module disabled, in Backdrop the File module is necessary. We probably should take care of enabling it in an update hook.
> 
> 
> 
> > Warning: file_put_contents(temporary://filertExxd): failed to open stream
> 
> 
> 
> Do you happen to know, what triggers that warning? Do file uploads in general work?

The  Drupal site was a simple community website and the webmaster uploaded to an /images folder using ftp.  The site was running from a sub folder of webroot, and images folder was in public_html/images 😵‍💫😵‍💫

The warning messages were from the migration, during core/update.php.

Thanks.

**Comment by indigoxela** [comment]
> The warning messages were from the migration, from initial core/update.php. Are there possible fixes in D7 to remove these errors during migration?

Good question. Your temporary directory may be the reason (sites/default/tmp seems a bit uncommon). Personally, I'd try to set it to /tmp for migrations (D6 -> D7 -> B). The temp directory setting can be changed any time without side effects. ... And if the warning still appears with that setting, you might have to dig a little deeper.

Am I getting this right, that the warning only appears once while upgrading, but never after that? Maybe it's about the htaccess file within the public files directory, which would be harmless.

**Comment by abetomas** [comment]
> > The warning messages were from the migration, from initial core/update.php. Are there possible fixes in D7 to remove these errors during migration?
> 
> Good question. Your temporary directory may be the reason (sites/default/tmp seems a bit uncommon). Personally, I'd try to set it to /tmp for migrations (D6 -> D7 -> B). The temp directory setting can be changed any time without side effects. ... And if the warning still appears with that setting, you might have to dig a little deeper.
> 
> Am I getting this right, that the warning only appears once while upgrading, but never after that? Maybe it's about the htaccess file within the public files directory, which would be harmless.

Yes, the messages  only appear once while upgrading.

_I moved temporary folder sites/default/tmp out of webroot, and into $HOME/tmp._  **The following warning/error messages have disappeared from the log:**

- Warning: file_put_contents(temporary://filertExxd): failed to open stream: "BackdropTemporaryStreamWrapper::stream_open" call failed in file_unmanaged_save_data() (line 2105 of /....../public_html/(mysitename)/core/includes/file.inc).
- Security warning: Couldn't write .htaccess file. Please create a .htaccess file in your temporary:// directory which contains the following lines: 

There were other messages had datestamps from a previous migrations, errors and warnings that had Location and Referrer info pointing to the old sites (D6, D7).  These messages possibly caused by previous faulty :<{( configs and migration from D6 > D7.

Would you suggest other tweaks and fixes to be made on the old D7 site prior to migration to Backdrop?  Perhaps it's time to close this report :>)

Thank you for your patience and support.  It is much appreciated.

**Comment by indigoxela** [comment]
@abetomas seems like you sorted all out, which is good.

The last remaining task here is that the upgrade run should take care of a disabled File module (for the rare cases when it's off in D7). So future upgrades don't run into the same problem.

**Comment by abetomas** [comment]
Thank you @indigoxela

**Comment by argiepiano** [comment]
WFM!

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop-issues/issues/5648 into 1.x and 1.22.x. Thanks @indigoxela, @abetomas, and @argiepiano!
