### ISSUE TITLE
Notice: Undefined variable: links in node_revision_overview() on /node/XX/revisions

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5649]
## Description of the bug

This popped up in [the forum](https://forum.backdropcms.org/forum/notice-undefined-variable-error-node-revision-pages-if-user-only-has-view-content-revisions).

If a role has permission to view revisions, but nothing more, this notice appears when visiting the revisions tab:

```
Notice: Undefined variable: links in node_revision_overview() (line 931 of ...core/modules/node/node.pages.inc).
```

## Steps To Reproduce

1. Define a role with View content revisions but *without* Revert content revisions / Delete content revisions permission
2. Create an account with that role
3. Log in as that user

## Actual behavior

PHP notice about the undefined "links" variable on all revisions tabs (/node/XX/revisions) for users with view, but without revert/delete permissions.

## Expected behavior

No notice and no empty dropbutton wrapper in the "Operations" column of the overview table.

## Additional information

- Backdrop CMS version: current dev

If `$links` isn't set at all, don't bother displaying the dropbutton at all. Maybe even completely skip the "Operations" column. 
See: https://github.com/backdrop/backdrop/blob/d60ef45b36be59dbbb216c6cfc1d52f7e8a71e25/core/modules/node/node.pages.inc#L931

**Comment by indigoxela** [comment]
Skipping the complete column isn't possible, as for the current revision that column contains the info.
Defining the variable is the way to go. A super-simple [PR](https://github.com/backdrop/backdrop/pull/4089) is available for testing and review.

**Comment by argiepiano** [comment]
This looks good to me.

**Comment by quicksketch** [comment]
Looks great! Thanks @indigoxela and @argiepiano! Merged https://github.com/backdrop/backdrop/pull/4089 into 1.x and 1.22.x.
