### ISSUE TITLE
Error: Call to undefined function views_get_enabled_views() in views_ui_admin_bar_map() (line 162 of /var/www/html/docroot/core/modules/admin_bar/admin_bar.map.inc).

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5654]
## Description of the bug

The [views_ui_admin_bar_map()](https://github.com/backdrop/backdrop/blob/91ee30564b9eb7f48a8bf5a2f542b5cb83b36776/core/modules/admin_bar/admin_bar.map.inc#L157) function assumes the `Views` module is always enabled.

```
function views_ui_admin_bar_map() {
  if (!user_access('administer views')) {
    return;
  }
  $views = array();
  foreach (views_get_enabled_views() as $name => $view) {
    $views[$name] = $view->human_name;
  }
  if (empty($views)) {
    return;
  }
  natcasesort($views);
  $views = array_keys($views);
  $map['admin/structure/views/view/%views_ui_cache'] = array(
    'parent' => 'admin/structure/views',
    'arguments' => array(
      array('%views_ui_cache' => $views),
    ),
  );
  return $map;
}
```

## Steps To Reproduce

To reproduce the behavior:

Don't remember exactly when after disabling the Views module the following error started to fill in the log:

```
Error: Call to undefined function views_get_enabled_views() in views_ui_admin_bar_map() (line 162 of /var/www/html/docroot/core/modules/admin_bar/admin_bar.map.inc).
```

## Expected behavior

The views or, for that matter, any other module should not be assumed always enabled and the respective check whether any module is enabled should be implemented:

```
  if (!module_exists('views')) {
    return;
  }
```

**Comment by indigoxela** [comment]
> The [views_ui_admin_bar_map()](https://github.com/backdrop/backdrop/blob/91ee30564b9eb7f48a8bf5a2f542b5cb83b36776/core/modules/admin_bar/admin_bar.map.inc#L157) function assumes the Views module is always enabled.

The reason for that is, that in B the Views module is required. (See the module's info file.)

```
required = TRUE
```

I wonder, how you were able to _disable_ a required module. If you managed to do that, then this might be the bug.

**Comment by alanmels** [comment]
Oh, I didn't pay attention to that. I just needed a very simple site and disabled almost everything, but just a few core modules. I did it by feeding the list of unwanted modules to "brush sql-query" without going to UI. 

In retrospect, I'm not sure if it's a bug or not, because hardly possible anyone would do like I did. On the other hand, few could still run onto this if they somehow got the Views module disabled, because there is another way - directly in database. So probably, adding the above check would only dumb-proof.

**Comment by indigoxela** [comment]
> I did it by feeding the list of unwanted modules to "brush sql-query" without going to UI.

If a site admin acts directly on the database, they're supposed to *know* what they're doing.
I don't think there's a way to prevent people from breaking their site, if they fiddle in the system db directly - be it with "brush sql-query" or with a query in phpmyadmin or the mysql shell...

TBH, I'm tempted to close this issue as "works as designed". @alanmels please don't get this wrong, but in this case the problem exists between keyboard and chair. :stuck_out_tongue_winking_eye:

Or do you see anything we could improve in core to prevent people doing destructive stuff like that?

**Comment by alanmels** [comment]
Fair enough, let's not spend on this rare case anymore time and energy as there are plenty of other more important issues.
