### ISSUE TITLE
The user_is_blocked() function does not respect user login methods using e-mail address

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5657]
## Description of the bug

The User login options at `admin/config/people/login` offer the following options:

- Username or e-mail address
- Username
- E-mail address 

and if either of two methods using e-mail address is set, and a user is not yet activated or blocked and attempts to login to a Backdrop website, then s/he will see:

> Sorry, no account with that email address found.

instead of

> The account for blocked@mail.com has not been activated or is blocked.

## Additional information

The offending function in user.module at https://github.com/backdrop/backdrop/blob/0394202d00a9b6c8d3b5e3c1625c24e0ed0f5f75/core/modules/user/user.module#L533 looks like:

```
function user_is_blocked($name) {
  return db_select('users')
    ->fields('users', array('name'))
    ->condition('name', db_like($name), 'LIKE')
    ->condition('status', 0)
    ->execute()->fetchObject();
}
```

which means it expects the $name variable to always be a username, whereas the configuration on `admin/config/people/login` can make it to return as an e-mail address instead.

**Comment by indigoxela** [comment]
> Could you please set User Login method explicitly to E-mail address and try to reproduce the issue?

Yes, sure. Also tried that, but also can not reproduce.

If I enter the *email* I also get "The account for userblocked has not been activated or is blocked." Still works correctly.

**Comment by alanmels** [comment]
You were right: an override in a custom block was meddling with validation functions, the issue didn't come up on a clean install. Closing this.
