### ISSUE TITLE
Fixes once entity reference is merged 

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5665]
Once entity reference is merged in https://github.com/backdrop/backdrop-issues/issues/1301 then there are a few bugs to merge from the contrib version:

* https://github.com/backdrop-contrib/entityreference/issues/27
* https://github.com/backdrop-contrib/entityreference/issues/29
* https://github.com/backdrop-contrib/entityreference/issues/31

**Comment by herbdool** [comment]
There are two PRs to merge with this issue. Both are bug fixes and address issues resolved in entity reference contrib:

* https://github.com/backdrop/backdrop/pull/4133
* https://github.com/backdrop/backdrop/pull/4134

**Comment by quicksketch** [comment]
Confirmed the identical contents of the diffs:

https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/4133.diff with
https://patch-diff.githubusercontent.com/raw/backdrop-contrib/entityreference/pull/33.diff

and

https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/4134.diff with
https://patch-diff.githubusercontent.com/raw/backdrop-contrib/entityreference/pull/30.diff
https://patch-diff.githubusercontent.com/raw/backdrop-contrib/entityreference/pull/32.diff

Looks good to me!

**Comment by quicksketch** [comment]
I merged both PRs:

* https://github.com/backdrop/backdrop/pull/4133
* https://github.com/backdrop/backdrop/pull/4134

Thanks @herbdool, @argiepiano, and @rbargerhuff!
