### ISSUE TITLE
Handling install.php redirect when DB values as present

### ISSUE THREAD

**Issue by populist** [backdrop/backdrop-issues#567]
In cases where Backdrop is not yet installed, the desired behavior is that the user is redirected to /core/install.php. This happens in bootstrap.inc which performs this check:

if (empty($GLOBALS['databases']) && !backdrop_installation_attempted()) { }

The problem here is that if you have injected the DB settings (i.e. using $SERVER['BACKDROP_SETTINGS']) then the $GLOBALS['databases'] will not be empty() even though the DB has not yet been installed. This prevents the redirect and results in a fatal error (Fatal error: Call to undefined function menu_get_custom_theme() ) when bootstrap continues.

**Comment by quicksketch** [comment]
Thanks @populist. I've got some work on this that is part of fixing several issues with our install process as part of https://github.com/backdrop/backdrop-issues/issues/531. This is addressed as well in my in-progress branch, so assigning this to myself.

**Comment by populist** [comment]
The way that Pressflow 7 handles this is through logic like this in _drupal_bootstrap_variables():

  // Pressflow Smart Start
  if (!empty($GLOBALS['databases']) && variable_get('pressflow_smart_start', FALSE)) {
    try {
      $result = db_query('SELECT s.name FROM {system} s WHERE s.name = :name', array(':name' => 'system'));
    } catch (PDOException $e) {
      if ($e->getCode() == '2003') {
        header('Status: 550 Database Offline');
        exit();
      }
      elseif ($e->getCode() == '42S02') {
        include_once DRUPAL_ROOT . '/includes/install.inc';
        install_goto('install.php');
      }
    }
  }

**Comment by quicksketch** [comment]
We did a similar fix in https://github.com/backdrop/backdrop-issues/issues/413 (PR is at https://github.com/backdrop/backdrop/pull/659), but it's an always-on approach that doesn't take an additional query. The entire bootstrap (inside of `backdrop_bootstrap`) is now wrapped in a try/catch block. On the first database query that fails, it'll catch and then do a check to see if the database is empty. Maybe the Pantheon branch just isn't fully up-to-date.

**Comment by quicksketch** [comment]
I pushed to the Pantheon branch at https://github.com/backdrop-ops/backdrop-pantheon. Let's give that a shot.

**Comment by quicksketch** [comment]
Hm, that still didn't work because the way Backdrop detects an empty database is by checking for no tables at all, but Pantheon populates the database with a `_pantheon_heartbeat` table. We can switch the current query to select from `{system}` instead (like your PR) and that will fix our current redirect code.

**Comment by quicksketch** [comment]
There, merged the PR, updated the backdrop-pantheon repo, and now we have automatic redirects on Pantheon. woot woot!
