### ISSUE TITLE
After upgrading from D7 two internal search menu links lose their parents resulting in wrong page titles

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5674]
## Description of the bug

This popped up in our Zulip chat: after upgrading from Drupal 7, the page titles and primary headings on these two pages are wrong:

- /search/node - "Content"
- /search/user - "User accounts"

This seems to be caused by the parent id `plid` for both paths get reset to "0" (no parent), although in D7 and in a fresh B install, the parent would be "/search".

## Steps To Reproduce

1. Upgrade a D7 site, make sure the Search module is enabled
2. Go to /search/node and see the heading (h1) and page title is "Content" rather than "Search"
3. Similar for /search/user

Additional findings: the "Navigation" menu still exists, with "Search" being the only item.
More findings: a lot of "navigation" menu cruft stays in the menu_links table - not sure if that's expected behavior.

## Expected behavior

The page titles and headings should stay the same - "Search".

## Additional information

In the database shell or phpmyadmin run:
```
SELECT menu_name,mlid,plid,link_path,link_title,module,hidden FROM `menu_links` WHERE `link_path` LIKE 'search%';
```

Result:

```
+------------+------+------+---------------+---------------+--------+--------+
| menu_name  | mlid | plid | link_path     | link_title    | module | hidden |
+------------+------+------+---------------+---------------+--------+--------+
| navigation |    1 |    0 | search        | Search        | system |      1 |
| internal   |    6 |    0 | search/node   | Content       | system |     -1 |
| internal   |   36 |    6 | search/node/% | Content       | system |     -1 |
| internal   |    7 |    0 | search/user   | User accounts | system |     -1 |
| internal   |   64 |    7 | search/user/% | User accounts | system |     -1 |
+------------+------+------+---------------+---------------+--------+--------+
5 rows in set (0.001 sec)
```
Note that in a "regular" Backdrop install `search` isn't part of the "navigation" menu (which doesn't exist in B), but an _internal_ menu link - so that's the point where things go wrong.
Also note, that "search/node" and "search/user" lost their parent (plid = 0), as that one's in a different menu now.

**Comment by indigoxela** [comment]
Steps to fix manually (hackish, not recommended):

1. Delete the navigation menu - that resets the `search` link to "internal"
2. Update both plid (for search/node, search/user) to this internal link
3. Flush caches

But how can we catch the problem in an update hook?

**Comment by indigoxela** [comment]
@argiepiano I think, your previous comment is outdated - we figured out what the other one meant (hint "hidden" column value).

**Comment by indigoxela** [comment]
Starting to brainstorm here:

Drupal 7 ships with two "suggested" menu items: "search" and "filter/tips".

"search" is the only special case - the base is "suggested", but the children are "internal". That causes the problem that after the update hook has run (system_update_1053), parent and children end up in different menus.
Special casing "search/%" is already done in that update hook, but note the slash.

**Comment by yorkshire-pudding** [comment]
So would special casing (does that mean remove?) just "search" be enough to fix and cause Backdrop to recreate in the internal menu where it can be the parent it was always meant to be to its children?

**Comment by indigoxela** [comment]
Another look at the values of a fresh B install: the search link *is* internal there. That actually makes no sense, either. The "internal" menu is no actual one (doesn't get handled via UI), so attaching a menu link that "shows up as disabled" is very odd.

**Comment by indigoxela** [comment]
I think, the whole concept of MENU_SUGGESTED_ITEM is broken in Backdrop.

Three core modules provide such items: Book, Contact, and Search. But in #1810 the default menu, where such suggested items are places has been switched from "main-menu" (note: "navigation" in D7) to "internal" - which is no real menu.
So these items never show up anywhere. How I "love" such rabbit holes.

**Comment by indigoxela** [comment]
I think, bringing back MENU_SUGGESTED_ITEM is possible by setting the menu_name to 'main-menu' in _menu_link_build.

But we also need update hooks to handle:

1. Upgrade from Drupal (and their "navigation" menu)
2. Currently "suggested" items, that are still in "internal" dummy menu

I don't think this can be a follow-up, as we first need to settle on a concept (which menu should suggested items go to?), and then we can fix existing data.

**Comment by BWPanda** [comment]
See https://github.com/backdrop/backdrop-issues/issues/4797 where we need to update `hook_menu()` and I've added a change record for this.

If there are any menu items in core that use `MENU_SUGGESTED_ITEM`, they need to be updated to explicitly set their menu as 'main-menu'. I'm not sure how to handle D7 upgrades...

**Comment by indigoxela** [comment]
@BWPanda many thanks for pointing to the related issue.

> If there are any menu items in core that use MENU_SUGGESTED_ITEM, they need to be updated to explicitly set their menu as 'main-menu'

That's the point I'm not really sure of. My PR currently does that, but it bloats the main menu with items, the admin can not delete.
Do we really want that?

Other options:

- Create a "Tools" menu in core and always park suggested items there.
- Completely drop the concept of MENU_SUGGESTED_ITEM

> I'm not sure how to handle D7 upgrades...

As D7 ships with the Navigation menu for that purpose and the menu will exist, when upgrading and it has items (I belief...), we should just leave the items there. Other ideas?

**Comment by indigoxela** [comment]
Although this issue and PR didn't get any feedback in years and I'm pretty sure, in the meantime 5 more issues have been opened for the same problem, I went ahead and rebased my PR. :wink:

**Comment by klonos** [comment]
Sorry for the delay @indigoxela ...I'm planning to test this, but it will take some additional time/effort (set up a D7 site -> enable the Search module -> try upgrading to Backdrop -> reproduce the problem -> repeat the process with the PR changes to confirm fixed).

**Comment by stpaultim** [comment]
More people might be available to help test issues like this if we had a clear set of instructions (maybe even a sample D7 database available) for how to most effeciently test upgrade issues like this one. 

Personally, I avoid these issues, because I'm not sure of what all is required and how much time it will take me to go through the process of testing an upgrade issue.

**Comment by indigoxela** [comment]
> ...and a fresh BD install followed by inserting the D7 database into BD site ...

"install" might be the culprit. Backdrop shouldn't be installed, but only be "in place" - the installer of B shouldn't have run. Maybe that's it?

I have to admit, that I don't recall all the details of this PR - it's been some years... :grimacing: I just rebased it this year, but it's already out of date again.

**Comment by indigoxela** [comment]
It might be, that this issue has better chances for progress: https://github.com/backdrop/backdrop-issues/issues/5834

Or we might end up with (temporary) workarounds, like for contact: https://github.com/backdrop/backdrop-issues/issues/1572

It's not that we don't have enough issues about MENU_SUGGESTED_ITEM :speak_no_evil:

**Comment by indigoxela** [comment]
> My apologies for the premature comment as I was testing.

No need to apologize, I'm always happy, if someone volunteers for testing. :relaxed: Sometimes the path to success is a bit winding - that's normal. :wink: 

> was wondering about issue https://github.com/backdrop/backdrop-issues/issues/5834 and if there is any reason to hold back this PR since it is a bugfix for D7 updates.

It's a different approach and it might get obsolete, if someone comes up with a better solution.
And it also applies to native Backdrop installs, which means, Search, Contact and Book menu items show up in main-menu, but can't get deleted, only disabled or moved to other menus - that's not optimal from admin perspective.

That's why I'm assuming, one of the other approaches has better chances to get accepted. :wink:

**Comment by indigoxela** [comment]
I don't think there can be quick progress with the MENU_SUGGESTED_ITEM concept (which additionally has a second issue, anyway). But it's still an annoying bug.

So here's now a different, more lightweight approach:

https://github.com/backdrop/backdrop/pull/4874

It only updates the relevant menu items in menu_links db table in an update hook to get the parent-child connection back.
This also means, the "Search" menu item vanishes from the "Navigation" menu, as it's "internal" where the child items are - just the way it is in native Backdrop installs.

Seems to work.
Testing's a bit cumbersome, as you need a D7 database from an (otherwise simple) Drupal install and you have to run the whole upgrade process on a clean (means: not installed) Backdrop.

I also rebased the old PR, so you can compare. But that one's very likely obsolete, anyway. Just left it there for discussion.

**Comment by indigoxela** [comment]
> do not fully understand... upgrade process on a clean (means: not installed) Backdrop.

Ah, OK, I'll try to explain better (hopefully): Backdrop should be prepared - core and all modules you need in place, the database connected (via settings.(local.)php), but not the database from a backdrop install, only the Drupal db tables should be in there.
If Backdrop were installed, you get a config mix - parts of settings or content types or layouts or whatever... would mess the upgrade.
That's why the [official docs](https://docs.backdropcms.org/documentation/step-3-upgrade-the-drupal-site) explicitly point out to "NOT install Backdrop". To avoid that config mix.

In our case, for testing this update hook, it should still be OK, as no config's involved here. But again: for real upgrades - do not install Backdrop, just provide the codebase and Drupal db. :wink:

However, thank you so much for testing. :pray:

**Comment by indigoxela** [comment]
> Thanks for the details and reference.

I hope, it wasn't too much. :wink: 

> Do you think this is a good candidate to push forward?

I think so, yes. It just aligns upgraded sites with native installs, which won't cause any problem, whatever the decision re "suggested items" may be.
I closed the obsolete PR now.

**Comment by indigoxela** [comment]
> Can I also mark as pr - ready to be committed or must someone else do that?

Yes, you [can do that](https://docs.backdropcms.org/documentation/adding-labels-to-issues). No worries, there will be a final review, as soon as a core committer has a look.
