### ISSUE TITLE
Fix docblock for field_validate_field(): should be $field not $field_name

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5685]
## Description of the bug

Incorrect parameter in docblock: https://github.com/backdrop/backdrop/blob/28101daf01318500ea1a8362279a64f3d77c04d9/core/modules/field/field.crud.inc#L229

Should be something like:

```
/**
 * Validates a field configuration.
 *
 * @param $field
 *   A field structure. $field['field_name'], $field['type'] must be provided.
 * @param $update
 *   Whether this is a new or existing field.
 */
function field_validate_field($field, $update = FALSE) {
```

**Comment by kiamlaluno** [comment]
The suggested change is correct and the PR changes the code as suggested.

**Comment by bugfolder** [comment]
There's a typo left in the code, suggested changed noted in the PR.

Since this is documentation-only, I don't think that testing is needed.

**Comment by bugfolder** [comment]
Code change now looks good. PHPCS is complaining (legitimately) about an unrelated code formatting issue, but that's out of scope of this issue. LGTM, RTBC.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4160 into 1.x and 1.26.x. Sorry for the delay, but welcome to @PrajwalBorkar! Thanks so much for making the PR and I appreciate the work you put into incorporating feedback.

Thanks @bugfolder and @kiamlaluno for reviewing and thanks @herbdool for filing the issue.
