### ISSUE TITLE
Missing Views handler: watchdog reports "Missing join" with relationship+contextual filter+taxonomy term

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5695]
## Description of the bug

Creating a View with a Relationship to a taxonomy term and a Contextual filter on the term name results in a watchdog entry of type=`views`, message=`Missing join: taxonomy_term_data taxonomy_term_data` whenever the View is rendered with the contextual filter term.

## Steps To Reproduce

To reproduce the behavior:

1. Begin with a standard Backdrop installation (with Card, Page, and Post content types).
2. The `Tags` vocabulary already exists. Create two terms, `dog` and `cat`.
3. Create four Post nodes, two with `dog` tag, two with `cat` tag. (For example, "Retriever", "Spaniel", "Tabby", and "Siamese".
4. Create a new View of content of type Post, display teasers, with page path `animals`.
5. Add a relationship, "Content: Tags (field_tags)".
6. Add a contextual filter of type "Taxonomy term:name", using the Relationship "term from field_tags". Leave other settings at their default values.
7. Turn on "Auto preview" in the View. Initially, you will see all posts, the four you created plus "Your first post!".
8. Open `admin/reports/dblog` in a separate window. There's no notice yet.
9. To generate the notice, enter the contextual filter `dog` and click "Update Preview". Then refresh the watchdog page, where you will now see the notice.

Or, equivalently, save the View and then visit the page `animals/dog`. This, too, will put the notice into watchdog.

## Actual behavior

Every time you refresh the display with a contextual filter parameter, it puts another notice in watchdog. If you don't include the contextual filter parameter, there's no notice.

If you create a View with multiple relationships and corresponding contextual filters, there will be multiple watchdog notices with each page render, one for each relationship/filter combination.

Other than the watchdog notices, the View appears to function properly. In this example, using `dog` will show only the two dog posts; `cat` will show only the two cat posts; no parameter shows all posts.

A simple workaround is to just comment out the notice in function `views_get_table_join()` in file `core/modules/views/includes/utility.inc`:

```
  // DEBUG -- identify missing handlers
  watchdog('views', "Missing join: @table @base_table", array('@table' => $table, '@base_table' => $base_table));
```

But, presumably, it's there for a reason, and there's some deeper issue that needs to be addressed.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4164) is available for testing and review.

It's based on my previous finding, that in some (rare) cases, both tables are actually the same.

**Comment by argiepiano** [comment]
LGTM. Incidentally this bug also exists in D7, except that they use vpr instead of watchdog and the notice does not get written to the dblog.

**Comment by bugfolder** [comment]
LGTM too.

**Comment by klonos** [comment]
> Incidentally this bug also exists in D7...

Then we should cross-port the fix and contribute back to Views 7.x 😉 ❤️

**Comment by quicksketch** [comment]
Thanks for the extensive report @bugfolder and the fix @indigoxela!  Merged https://github.com/backdrop/backdrop/pull/4164 into 1.x and 1.22.x. I sort of think we could probably remove this line entirely, but maybe it will come in handy. Some times logs like this get filed after handlers break due to a removed module or name change (especially during D7 upgrades).
