### ISSUE TITLE
Fixed potentially broken installer.settings.json configuration file.

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5696]
## Description of the bug

This is a follow-up to #5690, where we discovered that under certain circumstances saving the update settings form can create a broken installer.settings.json file.

The immediate problem is fixed, but we need to take care of already broken files, as discovering what it needs to fix it isn't obvious.
We need an update hook.

**Comment by indigoxela** [comment]
@argiepiano you already suggested a solution. Mind to file a PR?

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4147

These are possible steps to test:
1. Start with a clean install WITHOUT patching with this PR
2. Fully uninstall Project Installer
3. Visit `admin/reports/updates/settings` and click Save Configuration. This will create a defective `installer.settings.json` file that's missing the `installer_server` key. Verify that's the case 
4. Enable Project Installer. Verify that the file `installer.settings.json` is still missing that key
5. Patch core with the PR provided
6. Run update.php. This should invoke `installer_update_1001()`and fix the file
7. Check the file again

Conversely, you should also test with a site with a "good" json file to make sure it doesn't do any harm.

**Comment by argiepiano** [comment]
One more caveat for testing: test with 1.22.1 or earlier, since 1.22.2 already fixed the issue with  the form at admin/reports/updates/settings

**Comment by indigoxela** [comment]
Great, many thanks for providing this PR. :+1:  Will try things out ASAP.

One thought, though. If one already has a broken installer.settings.json because the Installer module was off, then one enables the Installer module, the update hook won't run. It's enabled for the first time, so no updates run.

In other words, the Update module broke it - the Update module should fix it IMO. My suggestion is: move the hook to update.install.

Didn't test anything yet, though. Just a thought.

**Comment by argiepiano** [comment]
> If one already has a broken installer.settings.json because the Installer module was off, then one enables the Installer module, the update hook won't run

Yes, I see your point. It may be better to move this hook to update. I can try this later today

**Comment by argiepiano** [comment]
Done! Pushed a commit that moves the hook to update.install. 

Testing steps:
1. Start with a clean install of 1.22.1 or earlier
2. Fully uninstall Project Installer
3. Visit admin/reports/updates/settings and click Save Configuration. This will create a defective installer.settings.json file that's missing the installer_server key. Verify that's the case (the file is located in files/config_xxx/active)
4. Patch core with the PR provided
5. Run update.php. This should invoke `update_update_1005()` and fix the file
6. Check the file again. It should contain that key now.

**Comment by argiepiano** [comment]
A seemingly random test fail in 8.1 - I believe it's unrelated.

**Comment by indigoxela** [comment]
Works like a charm... well, almost...

One more thing to take care of: is the Installer module on or disabled or completely off.

Why that?

- If the module is on, the file installer.settings.json is supposed to exist in the active config dir
- If the module is disabled, the file is still supposed to exist (and should get fixed)
- If the module is uninstalled, the file is NOT supposed to be there at all - it will even cause notices on /admin/config/development/configuration/single/export and will break config syncs

The tricky part: differentiate between "disabled" and "off". We can do that with a db query on the system table (module_exists won't help in this case).

Some example query:
```
$status = db_query("SELECT status,schema_version FROM {system} WHERE name = 'installer' AND type = 'module'")->fetchAssoc();
```
Result when the module is on:
```
array (
  'status' => '1',
  'schema_version' => '1000',
)
```
Result when the module is disabled (but not uninstalled):
```
array (
  'status' => '0',
  'schema_version' => '1000',
)
```
Result when the module is uninstalled:
```
array (
  'status' => '0',
  'schema_version' => '-1',
)
```
@argiepiano what do you think?

**Comment by argiepiano** [comment]
Thanks @indigoxela .  I'll be away for a few days. Will tackle this when I get back

**Comment by argiepiano** [comment]
@indigoxela I was able to spend a bit of time with this. I understand perfectly what you are suggesting, however, I can't reproduce this problem:

> if the module is uninstalled, the file is NOT supposed to be there at all - it will break config syncs

Can you please explain how faulty config file with an uninstalled `installer` module causes config syncs to break?

**Comment by argiepiano** [comment]
Regardless of how the breaking happens, you are right that the config file shouldn't be there if installer is uninstalled. I just pushed another commit that follows your recommendations. Please test and let me know if you see any issues.

**Comment by indigoxela** [comment]
> Can you please explain how the faulty config file with an uninstalled installer module causes config syncs to break?

The file will cause a ConfigValidateException. Whether it's broken or not doesn't matter in that case, it just shouldn't be there.

```
The configuration "@name" is not owned by any module. ...
```

> Please test and let me know if you see any issues.

This looks great now, will test things later today. :+1:

**Comment by argiepiano** [comment]
Fixed typo. Thanks!

**Comment by argiepiano** [comment]
One more change. Use backdrop_get_installed_schema_version() instead of querying the db directly for the schema version.

**Comment by indigoxela** [comment]
> Use backdrop_get_installed_schema_version() instead of query...

Cool, there's already a function for that.

This is how I tested:

- On a fresh install I uninstalled the Installer
- Broke installer.settings.json
- Applied the patch and ran the update
- Broken file gone :+1: 

- Started fresh and disabled the Installer
- Broke installer.settings.json
- Applied the patch, ran the update
- Broken file got fixed :+1: 

Works like a charm.

**Comment by argiepiano** [comment]
Thanks. Anyone, code review?

**Comment by docwilmot** [comment]
LGTM

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4147 into 1.x. And because this update is in update.install where there are no conflicts, I cherry-picked it back into 1.22.x as well. Thanks @indigoxela, @argiepiano, and @docwilmot!
