### ISSUE TITLE
After D7 upgrade, no results in File Admin puts "Missing text format: filtered_html" in watchdog

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5698]
## Description of the bug

After upgrading from D7, visiting the "Manage files" page at `admin/content/files` and entering a search term that gave no results puts a "Missing text format: filtered_html" error into watchdog.

Although recent D7 sites give the "Filtered HTML" text format the machine name `filtered_html`, older D7 sites used numeric machine names (for example, `1`).

## Steps To Reproduce

To reproduce the behavior:

1. Create a D7 website. Make sure it is old enough that its fallback text format (typically "Filtered HTML") has a numeric machine name (e.g., `1`), rather than `filtered_html` (if it has the latter, this issue won't arise). Or create a new text format to use as fallback format with a different machine name, and delete the `filtered_html` format.
2. Upgrade to Backdrop.
3. Visit `admin/content/files` and enter a search term that gives no results.
4. Visit watchdog at `admin/reports/dblog`. You will see the error.

## Additional information

Although recent D7 sites give the "Filtered HTML" text format the machine name `filtered_html`, older D7 sites used numeric machine names (for example, `1`). (Or site administrators might have created and designated a different fallback format.)

The View that provides this page (`views.view.file_admin.json`) is installed at upgrade time in `file_update_1000()`, and its "No results" value has the format set to `filtered_html`. If the Filtered HTML format had a machine name of `1`, though, it will result in this error.

A manual fix is easy enough to implement: edit the View and set the "No Results" format to one of the existing formats (one with proper sanitization, of course).

As a fix, the update should use `fiter_fallback_format()` to get the proper machine name and then use that.

**Comment by indigoxela** [comment]
Many thanks for providing a PR. :+1:

I saw that format nagging after upgrade before, but didn't think of fixing it in core. :wink:

One thought: can we guarantee, that system_update_1028 (where this setting is converted to config) has already run, when file_update_1009 runs? Otherwise we'd end up with NULL.

**Comment by bugfolder** [comment]
Excellent point. `file_update_dependencies()` added with appropriate values.

**Comment by indigoxela** [comment]
Works for me. This is how I tested:

- Disabled the filtered_html format in D7
- Ran an upgrade with unpatched core
- Verified the dblog filter nagging "Missing text format: filtered_html." after following the steps on /admin/content/files

Now with the change applied:

- Started again, this time applied the patch
- Ran another upgrade (one additional pending update)
- Verified that /admin/content/files didn't cause any dblog filter nagging
- Verified that the view's empty area hs switched to `"format": "plain_text",`

**Comment by jenlampton** [comment]
Nice fix @bugfolder! I added one comment to the PR with a change we need to make to the view update.

**Comment by bugfolder** [comment]
Updated the PR to check all displays of the View and update if necessary.

**Comment by jenlampton** [comment]
I think the change to check for all displays of the view is a good one, but we still need to check that the view has not been modified from its default state before we make any changes to it.  (A Lengthier explanation of why we do that is in the PR comments.)

**Comment by bugfolder** [comment]
@jenlampton wrote in the PR [edited here for clarity]:

> Yes, [if the View was modified by a site admin and has an invalid format, we should leave the invalid format alone and only fix the invalid format if the View hasn't been modified is] what I meant. This is the process we've used for all other config updates. If the [config thing] has been modified in any way from its default state, we should not update it in an update hook. We do this because it's possible that the [config thing] has been modified in some way that would make our change cause other problems, and since there are an infinite number of changes that we can't realistically test for, it's not worth worrying about the edgecases where the view has been modified. Instead, we catch the majority of cases where we know the change is safe to make (where the view is unchanged) and disregard any modified config.

I do understand the logic for that in general. But in this particular case, I can envision plenty of reasons why someone would have performed the upgrade from D7, then edited the View to tweak it in some way, and never noticed that the "No results" behavior had an invalid text format (it's buried in the View) until sometime later when they happened to do a search that had no results, and they checked their dblog not long thereafter. So we're still doing them a favor to fix the problem that we created via the original upgrade.

Conversely, while there are in principle an infinite number of changes we can't realistically test for, I cannot think of any scenario where keeping a nonexistent text format for the "no results" text would be preferable over replacing it with the one that should have been there to begin with. So this seems pretty safe to make, even in the Hilbert-space of possibilities.

So, I respectfully request reconsideration in this particular case.

**Comment by indigoxela** [comment]
> I cannot think of any scenario where keeping a nonexistent text format for the "no results" text would be preferable over replacing it...

I agree with @bugfolder  - if we don't touch it, it is and will stay broken - and figuring out what's broken might cause the site admins some debugging and searching.

- On the view page the configured empty message won't show at all
- For every page call on that view they get a "severity alert" in dblog
- These two things are hard to connect - even when editing the view (the setting is collapsed)

Being cautious to not change views (any configs) that aren't in theirs "default vanilla" state only makes sense if things aren't broken. Let's make site admin life easier.

**Comment by docwilmot** [comment]
I'm in agreement with @bugfolder and @indigoxela here. I think the policy that @jenlampton is, generally, in case our "fix" may change something the user intended to keep, but in this case there is no chance we're doing that; we're only replacing a single bad format. The balance here is between the few users who actually may *want* a faulty format, vs the majority who likely would prefer no errors. If we're going to disappoint one of those two groups, I think we should lean to helping the majority.

**Comment by klonos** [comment]
I am also in agreement with @indigoxela and @bugfolder and @docwilmot for the reasons they've explained.

> ...and never noticed that the "No results" behavior had an invalid text format...

How could one notice this? ...especially when the view was not created on the site, rather than imported from config. Sounds to me that we need some validation in place, which will nag people if they are trying to save (and import/export perhaps?) a view that uses a non-existent format in any place where formats may be used ("Header"/"Footer", and "No results behaviour" settings). Separate issue for that though.

**Comment by bugfolder** [comment]
I'm going to go with the three agreements above and remove the "pr - needs work" label. But of course, restore "pr - needs code review," so a review would be most welcome.

**Comment by argiepiano** [comment]
I do have a question to the approach taken in this update hook. Here, the view is loaded using `views_get_view`. This is very unusual in an update hook (I could find only one instance of this). I believe it's better to load the **config file** rather than the actual view to make these adjustments, for two reasons:
1. `views_get_view` may not be available (probably it is, but I'd have to verify this)
2. More importantly, using `views_get_vew` may be more expensive. That function basically loads the config json file and creates an view object

So, we might as well save those microseconds and that memory by just acting on the json file itself. Instead of using `views_get_view('file_admin');`, we would use `config_get('file_admin', 'display');` and then loop through the displays and traverse the array structure. 

There are many instances of update hooks loading config files directly.

**Comment by bugfolder** [comment]
OK, updated the code to edit the config file directly. Putting this back to "needs testing."

**Comment by argiepiano** [comment]
Tested, LGTM, WFM, RTBC

**Comment by quicksketch** [comment]
Great work on this solution everyone! I'm really grateful for everyone's excellent feedback on writing a good update hook. By the time I looked at this, I thought it was perfect. Great job @bugfolder on incorporating that feedback into code. I merged https://github.com/backdrop/backdrop/pull/4149 into 1.x and 1.26.x.
