### ISSUE TITLE
Fixed: Docblock should reference '$settings['page_cache_invoke_hooks']' (not '$settings['invoke_page_cache_hooks']').

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5700]
## Description of the bug

The [documentation of `hook_boot()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_boot/1) says:

> This hook by default is not called on pages served by the default page cache, but can be enabled through the `$settings['invoke_page_cache_hooks']` option in [settings.php](https://docs.backdropcms.org/api/backdrop/settings.php/1).

The correct name is `'page_cache_invoke_hooks'`, which is readily verified by doing a search on both names in Backdrop core. The only occurrence of `'invoke_page_cache_hooks'` is in the docblock of `hook_boot()`, also `hook_exit()`.

So the docblocks are the only thing that needs to be corrected. No change needed in functional code.

**Comment by bugfolder** [comment]
PR ready for review. No testing needed (docblock changes only).

**Comment by indigoxela** [comment]
Nice catch, it even came in with the [same PR](https://github.com/backdrop/backdrop-issues/issues/493), so clearly mis-typed.
RTBC!

**Comment by indigoxela** [comment]
As this is a small, yet important comment-only fix, I'm setting the milestone here.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4148 into 1.x and 1.22.x. Thanks @bugfolder and @indigoxela!
