### ISSUE TITLE
[UX] Improve field block labels when copying the Layout title from a block.

### ISSUE THREAD

**Issue by kswan** [backdrop/backdrop-issues#5704]
## Description of the bug

When using Layouts to format node pages the Configure page title doesn't show meaningful options under "Block to copy" when "Copy from block" is selected.

## Steps To Reproduce

To reproduce the behavior:
1. (optional) Create a content type with multiple fields, or add various fields other than the default ones. This will make the issue more obvious.
2. Create a layout using Path: `node/%` and save.
3. Add two or more fields somewhere in the layout.
4. If the title combo block is available in the layout, remove it -> this action will the "Page title" element.
5. Click on Configure in the "Page title" element.
6. Select "Copy from block"
7. Click the "Block to copy" select that appears, to see the available options.

## Actual behavior

Multiple items are displayed as "Field block" with no way to know which field you are selecting.
![image](https://user-images.githubusercontent.com/154391/182401282-3949aeec-4b01-416f-a951-3b2f59aad347.png)

## Expected behavior

Fields should be displayed with the field name. For example:  "Field block - field_1st_field", "Field bock - field_2nd_field"...

## Additional information

Backdrop version 1.22.2

**Comment by indigoxela** [comment]
Nice catch, with multiple field blocks the dropdown gets very confusing.

I can confirm that the PR fixes that - works for me.

@kswan I've left a small suggestion re readability.

**Comment by kswan** [comment]
PR#4155 is a better solution IMO.

**Comment by kswan** [comment]
Here is a screenshot with PR#4154.
![image](https://user-images.githubusercontent.com/154391/183111554-ffc82693-dcdc-48b6-9076-d3713f0b45a4.png)

**Comment by kswan** [comment]
Here is a screenshot with PR#4155.
![image](https://user-images.githubusercontent.com/154391/183113322-76a1719f-b98f-4efe-8bc7-631d4bf8e9ed.png)

**Comment by docwilmot** [comment]
I tested this in the sandbox, and prefer PR 4155. 
- The sandbox already had a custom `node/%` content type (called Product) with field blocks
- Created a new Product node; it used the node title as expected
- The layout title field listed "Field body" under the `Block to copy` select list as expected
- Changed the layout title to pull from "Field body" and the page title changed to "Body" as expected
- Changed the "Field body" block's admin title, and checked the dropdown in the layout title select list, and it reflected the new admin title as expected, even before saving the layout
- Configured the Body field block to a custom block title, saved the layout, and the Product page was renamed to the new custom block title as expected

So all good in the UI, but we should update the tests too.

**Comment by indigoxela** [comment]
I did another check, and also agree: PR 4155 is even better. :+1: 

@kswan can you close the outdated one, please?

@docwilmot do you have special tests in mind that should get updated/extended?

**Comment by docwilmot** [comment]
> @docwilmot do you have special tests in mind that should get updated/extended?

The layout page title doesnt seem to have its own test. Most of the testing of title functionality seems to happen in `testPageComponentBlocks()` and `testOverriddenPaths()` (searched for `/edit-title` string, which is the path for the page title configure dropbutton), so maybe we could create a new test in the `LayoutInterfaceTest()` class and put all title testing in there.

Or extend one of those tests.

**Comment by klonos** [comment]
@docwilmot are there any tests that should be added or tweaked as part of the functionality that is being fixed here, or could we have a follow-up to add tests? What would you expect to be tested here? ...that the "Block to copy" select doesn't contain duplicate entries?

Asking because I'd hate to delay this UX fix on account of adding new tests that aren't directly related to what is being fixed here.

**Comment by docwilmot** [comment]
My first reponse suggested we should update the tests, since I didnt see a test in the PR. Usually if you change strings in a PR, a test usually needs updating.
But then I think I noticed that we dont actually test page titles? (my second issue comment just above, but I'm actually not sure if this is the case)
So I suppose its reasonable to just go ahead with this and make an issue to test page titles properly if needed.

**Comment by klonos** [comment]
> So I suppose its reasonable to just go ahead with this and make an issue to test page titles properly if needed.

Great! ...can someone then please removed the milestone label and add the actual milestone?

**Comment by quicksketch** [comment]
Thanks folks! I finally got to merging this! https://github.com/backdrop/backdrop/pull/4155 is merged into 1.x and 1.23.x. Thanks @kswan for both filing the issue and providing the PR! Thanks to @indigoxela, @docwilmot, and @klonos for testing and feedback!
