### ISSUE TITLE
Update all documentation URLs in core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5706]
We have a lot of links to Backdrop CMS documentation throughout core. The documentation site once lived at https://api.backdropcms.org. We've since moved it to https://docs.backdropcms.org. 

We should do a find/replace for api.backdropcms.org/docs.backdropcms.org in all files in core, so all links can point to the correct destination, without needing to leverage a redirect. 

Example page: Configuration manager (admin/config/development/configuration)

Example text: Read more about [managing configuration](https://api.backdropcms.org/documentation/working-with-configuration).

**Comment by CrisT195** [comment]
I'm working on this issue as part of Opensource Day.

**Comment by stpaultim** [comment]
@CrisT195 - Welcome. We have representatives standing by in the Opensource Day Zoom room for Backdrop CMS. Please, find us there if you have questions or ping us in our Opensource Day Slack channel.

**Comment by jenlampton** [comment]
@CrisT195 thanks for the PR!  I gave it a thorough review and all the new URLs look correct! 

I've filed one follow-up issue to check on the API module (and our docs site) to verify URLs are being generated properly, but that should not hold up this issue so let's proceed here.  PR otherwise RTBC from me!

**Comment by quicksketch** [comment]
Thanks @CrisT195, @jenlampton, and @stpaultim! Changes all look good! I've merged https://github.com/backdrop/backdrop/pull/4207 into 1.x and 1.23.x.
