### ISSUE TITLE
How does contrib provide custom content types now? (for conversions especially)

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#571]
I know its now CMI for types and fields (`hook_node_info()` is gone). But what is the recommended approach to getting it done?

First case: a new module (not a D7port)
Do you recommend copying a core config and renaming and altering the values? Or something else?

Second case: porting to BD
???

**Comment by quicksketch** [comment]
> First case: a new module (not a D7port)

To provide a content type as part of your module, you can use hook_install() to create the type upon installation. Book module does this for example. If you would like to prevent the content type from being deleted, you can make it "locked" (book module allows it's type to be deleted). Then to remove the content type, the user would have to uninstall the module and the module should use hook_uninstall() to clean up the locked content type.

It may be possible in the future to export a content type and include that type in the "config" directory of the module (like we do for Views), but with the large number of things hinging on content types (fields, comments, etc) doing it through the API is the best way for now.

This should probably be used for both first and second case. :)

**Comment by docwilmot** [comment]
Is that kind of an API change then? I'm suspicious that most contrib use hook_node_info(), since it seemed to be considered ideal practice. 
If this is the case is there any disadvantage of `node_type_save()` over `hook_node_info()` that we should be looking to document?
How do you keep the content type out of the create content list? You could previously just skip `hook_form()`.

**Comment by quicksketch** [comment]
>  How do you keep the content type out of the create content list? You could previously just skip hook_form().

You can still provide a "base" name when creating the content type with `node_type_save()`, which will make the calling of `hook_form()` identical to a node type provided by `hook_node_info()`.

So I think it's possible to still have the same functionality as before with `hook_node_info()`, it's just that the values that previously were provided by the hook now have to be saved into config instead.

**Comment by docwilmot** [comment]
I just tried adding a content type by including a node.type.my_type.json in the config folder of a module, and it worked! The new node type had no body, but it worked flawlessly otherwise.
Question is, in documenting the best practice for creating node types, do we discourage this in favor of node_type_save()?
And, also is there any current way to attach a body and other fields through config?

**Comment by quicksketch** [comment]
> I just tried adding a content type by including a node.type.my_type.json in the config folder of a module, and it worked!

I tried this approach in porting the API module as well. I haven't quite figured out if it should be supported or not. I don't think hooks fire for configuration that is copied from a modules default directory, so hooks like `hook_node_type_insert()` don't fire when using this approach. For that reason, I kept the installation of the "api" node type in hook_install() for api.module.

>  And, also is there any current way to attach a body and other fields through config?

While you could attempt to attach existing fields, I don't think new fields would work because the hooks necessary to create the matching database tables are not fired.

**Comment by docwilmot** [comment]
Ahh, hooks, yes. Will need to document that sometime.

**Comment by klonos** [comment]
I see that this issue was labeled with `docs - has change record`, but this tag seems to have been deprecated. Did we actually end up documenting this? Is https://api.backdropcms.org/change-records/hooknodeinfo-removed the relevant change record?
