### ISSUE TITLE
Fix typo in comment for `book_tokens()` 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5710]
I just noticed the following inline comment:

```php
// Skip access check to generat tokens before node grants are saved.
```

We need to add the missing `e` to the end of `generate`.

**Comment by indigoxela** [comment]
@kiamlaluno many thanks for providing a PR.

A tiny one (single character). :wink: RTBC!

**Comment by laryn** [comment]
Thank you @jenlampton, @kiamlaluno, and @indigoxela!
