### ISSUE TITLE
Typo in Date module admin help text

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5713]
## Description of the bug

Function _date_field_widget_settings_form() has a typo in a help text:

"If using simple inputs such a a single textfield or the date popup, omitting..."

Shouldn't that be `such as a` ... :grin:

Here it is: https://github.com/backdrop/backdrop/blob/1.x/core/modules/date/date.admin.inc#L443

## Additional information

- Backdrop CMS version: latest dev

**Comment by indigoxela** [comment]
Hi @Ascalabi,

many thanks for providing a pull request! :pray:  One suggestion regarding the pull request title: Now it's just "Typo", which doesn't give much information.
Can you update the title to something more meaningful, like "Issue #5713: Fix typo in _date_field_widget_settings_form()"?

**Comment by jenlampton** [comment]
The PR looks great, but I've set the label to `needs - work` based on @indigoxela's feedback.  Once the commit message / PR title is adjusted, this should be RTBC!  Thanks @Ascalabi for working on the PR, and @indigoxela for the fast reviews, as always :)

**Comment by Ascalabi** [comment]
Hello,

Thank you for the reply.

**Comment by indigoxela** [comment]
Great, I just realized that the title has been updated in the meantime.

The change is tiny (literally one single character), so I feel like a quick approval is fine here. RTBC!

**Comment by laryn** [comment]
Thanks @indigoxela, @Ascalabi, and @jenlampton -- merged into 1.x and 1.22.x.
