### ISSUE TITLE
The title for the ui.menu library is set to "jQuery UI: Mouse" already used by the ui.mouse library

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#5714]
## Description of the bug

[`system_library_info()`](https://github.com/backdrop/backdrop/blob/1.22.x/core/modules/system/system.module#L1667) contains the following code.

```php
  $libraries['ui.menu'] = array(
    'title' => 'jQuery UI: Mouse',
    'website' => 'http://jqueryui.com/menu/',
    'version' => $libraries['ui']['version'],
    'js' => array(
      'core/misc/ui/jquery.ui.menu.min.js' => array(),
    ),
    'css' => array(
      'core/misc/ui/jquery.ui.menu.css' => array(),
    ),
    'dependencies' => array(
      array('system', 'ui.widget'),
      array('system', 'ui.position'),
    ),
  );
  $libraries['ui.mouse'] = array(
    'title' => 'jQuery UI: Mouse',
    'website' => 'http://jqueryui.com/mouse/',
    'version' => $libraries['ui']['version'],
    'js' => array(
      'core/misc/ui/jquery.ui.mouse.min.js' => array(),
    ),
    'dependencies' => array(
      array('system', 'ui.widget'),
    ),
  );
```

The value for `$libraries['ui.menu']['title']` is the same value `$libraries['ui.mouse']['title']` has, while the first should be `'jQuery UI: Menu'`. As it is set, it seems there are two *jQuery UI: Mouse* libraries, while they are different libraries.

**Comment by indigoxela** [comment]
Hi @kiamlaluno,

nice catch, this looks clearly like a copy/paste mistake or a typo. You're of course right, it should be "Menu".

Are you willing to provide a pull request?

**Comment by kiamlaluno** [comment]
Yes, I would like to provide a pull request. I just need to set up Git on my computer, since I just installed Linux on it.
I was also trying to add the *Good first issue* label, but I don't know how to add labels on Github.

**Comment by kiamlaluno** [comment]
Just to be sure: Is 1.x the branch that should be used for any change? (I apologize for the silly question.)

The label isn't much important, actually. I was just trying to mark the issue as "not important" to avoid it would be reviewed as a very important issue.

**Comment by indigoxela** [comment]
There *are* no silly questions. :wink: And labels are just... labels.

Yes, 1.x is the development branch. You can do a lot via the GitHub user interface, BTW.

Here's the documentation: https://docs.backdropcms.org/documentation/contribute-to-backdrop-core

And here's the "noob way": https://backdropcms.org/news/creating-pull-requests-against-core-the-easy-noob-way

**Comment by kiamlaluno** [comment]
Thank you.
I was expecting the command line was necessary, but I could do all from the user interface. (Probably, I am too used to drupal.org and its issue forks. 😉)

**Comment by indigoxela** [comment]
> I was expecting the command line was necessary...

You can if you prefer. And for more complex issues it's probably better to do it that way, but for simple fixes it's not necessary.

In the meantime the automated tests have run and the change is tiny and comprehensive: RTBC!

**Comment by laryn** [comment]
Thanks @kiamlaluno and @indigoxela -- merged into 1.x and 1.22.x.
