### ISSUE TITLE
Remove the reference to the files property from image.inc documentation.

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#5717]
The [image.inc](https://github.com/backdrop/backdrop/blob/1.x/core/includes/image.inc#L24) file contains the following sentence in the documentation comment.

> Additionally the image toolkit include file must be identified in the files array in the module.info file.

Backdrop doesn't use anymore `files[]` in .info files. That sentence should be removed.

**Comment by kiamlaluno** [comment]
In fact, the [system.info](https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/system.info) file doesn't contain any reference to the *core/modules/system/image.gd.inc* file used for the GD toolkit.

**Comment by indigoxela** [comment]
Nice catch, that's a leftover (outdated) information, that should get updated. :+1:

**Comment by jenlampton** [comment]
Nice fix @kiamlaluno, thank you.

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/4168 into 1.x and 1.23.x.
