### ISSUE TITLE
Node deletion message: "Deleted @count posts" even if it's not a Post

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5724]
## Description of the bug

This is not a big deal, but I just noticed that when when one deletes one or more nodes, both the `backdrop_set_message()` and the watchdog entry say "Deleted &lt;count&gt; posts", which could be worrisome to someone who has Post, Page, and Card content types and deleted some of the latter two; the message suggests that it was the Post type that was deleted since the subtle distinction between "post" and "Post" might be lost on people.

This all takes place in `node_multiple_delete_confirm_submit()`, where we have access to the full list of nodes prior to deletion, so it would be straightforward to make the deletion message clearer. Perhaps something like:

"Deleted &lt;count&gt; Pages, Cards, and/or &lt;other type&gt;s", i.e., listing the total and what types were deleted, or

"Deleted &lt;count&gt; Pages, &lt;count&gt; Cards, and ...", i.e., listing how many of each type were deleted.

**Comment by kiamlaluno** [comment]
`node_multiple_delete_confirm_submit()` has only access to an array of node IDs. (That's what `$form_state['values']['nodes']` contains.) Showing the list of content type for which nodes were deleted would require to prepare it in `node_multiple_delete_confirm()`. 

*Deleted <count> Pages and Cards* could be understood as saying that <count> Pages and <count> Cards were deleted. *Deleted <count> Pages and <count> Cards* would avoid ambiguity, but it would make the code more complex: It would be necessary to count how many nodes of each content type are deleted, and present a correct phrase. (For example, it should be *Deleted 1 Card and 2 Pages*, but also *Deleted 3 Pages, 2 Organizations, and 1 Card*, which requires to correctly pluralize the content type name and put the comma where necessary.) 

Instead, in `node_multiple_delete_confirm()`, I would use *Are you sure you want to delete this post?* / *Are you sure you want to delete these posts?* as confirmation question. (The  actual question is *Are you sure you want to delete this item?* / *Are you sure you want to delete these items?*)
If users misunderstand *posts* as *nodes whose content type is Post*, they could go back to content administration page to check what they selected. (The confirmation form shows a list of node titles; probably they could verify they correctly select the nodes to delete from there too.)

**Comment by olafgrabienski** [comment]
> I would use *Are you sure you want to delete this post? / Are you sure you want to delete these posts?* as confirmation question. (The actual question is *Are you sure you want to delete this item? / Are you sure you want to delete these items?*)
  If users were to misunderstand *posts* as *nodes whose content type is Post*, they could go back to content administration page to check what they selected.

I'd prefer to find a less ambiguous term, maybe `content item` instead of `post` (and instead of just `item`).

**Comment by kiamlaluno** [comment]
There isn't a term used in the Backdrop user interface that is always used to reference to single nodes. That is something that should be addressed too.

I am fine either with *post* or *content item*, if *node* is considered a word to avoid, even for administrator users. (It's used in *Add URL redirect to this node*, though.)

**Comment by bugfolder** [comment]
`content item` works for me. But shouldn't the watchdog message be the same as the `backdrop_set_message()` message?

**Comment by kiamlaluno** [comment]
I also fixed the previous commit I done in the PR: I used *content type* instead of *content item*, in `node_multiple_delete_confirm_submit()`.

**Comment by bugfolder** [comment]
WFM and LGTM. One automated test failed, but it looked sporadic, so restarted them.

**Comment by bugfolder** [comment]
Different test failed, so pretty sure it's another sporadic. Restarting again.

**Comment by bugfolder** [comment]
All passing. RTBC.

**Comment by klonos** [comment]
>There isn't a term used in the Backdrop user interface that is always used to reference to single nodes.

Just wanted to quickly chime in to say that historically we have decided to use "piece of content" or "content item" (and the respective plural variations of these) in our documentation and other ussr-facing text instead of "node". So this PR is good 👍🏼 

Thank you for the report @bugfolder and thank you for contributing a PR @kiamlaluno.

**Comment by kiamlaluno** [comment]
@klonos Should I open a new issue for the other places where *node* and *nodes* are used in strings shown to users, like *Add URL redirect to this node*?

**Comment by stpaultim** [comment]
I think it's so funny to find this PR RTBC, because I just (2 hours ago) had a big discussion with a client about this issue after she deleted several hundred pieces of content and I was trying to decipher the meaning of this message. 

![image](https://user-images.githubusercontent.com/3144571/190042668-df94001e-8aa3-4b5e-af2e-db2b55a5e257.png)

At first I told her, "I don't see any evidence of you deleting pages. See the log says that you deleted posts." I think realized that we have no content type for "posts" and realized that this must be a generic term. But, for a while this message was clearly misleading me into believing something that was not true. 

Thanks to those who found and worked on this issue. I support merging this into core.

**Comment by laryn** [comment]
Thanks  @kiamlaluno, @bugfolder, @olafgrabienski, @klonos and @stpaultim. Merged into 1.x and 1.22.x.

**Comment by klonos** [comment]
> @klonos Should I open a new issue for the other places where node and nodes are used in strings shown to users, like Add URL redirect to this node? (I mean: Is it worth doing it?)

Sorry for the late reply @kiamlaluno ...yes, it is worth fixing every little thing/detail, especially when it comes to user-facing text, and especially if that text can be misleading (like in this case), or if it has "cryptic" terminology like "node" or "entity" in it. I would say that please feel free to raise issues and provide PRs for any such issue you come across. Thank you for contributing to Backdrop 🙏🏼 ❤️
