### ISSUE TITLE
Correct the documentation for the value returned by backdrop_random_key()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#5730]
The documentation for [`backdrop_random_key()`](https://docs.backdropcms.org/api/backdrop/core!includes!bootstrap.inc/function/backdrop_random_key/1) describes the returned value as:

> The base64 encoded result will have a length of up to `4 * $byte_count`.

That isn't correct: A Base64 encoded string will have a length of up to `ceil($byte_count * 4 / 3)`.

**Comment by BWPanda** [comment]
@kiamlaluno's PR looks good to me. Recommend closing @jenlampton's in favour of it.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/4284. Thanks folks!
