### ISSUE TITLE
Remove the unnecessary dependency to system module from entityreference.info

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5734]
This is just a small cleanup task. The `dependencies[] = system (>= 1.21.0)` line is originating from the contrib module, where it made sense to exist. It serves no purpose now that the module is included in core, since the System module is always enabled, and whatever the current version is will always be the appropriate one.

**Comment by herbdool** [comment]
Makes sense

**Comment by quicksketch** [comment]
Thanks @klonos and @herbdool! Merged https://github.com/backdrop/backdrop/pull/4176 into 1.x for 1.23.0
