### ISSUE TITLE
[UX] Added "Flush all caches > Views" to admin bar.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5737]
## Description of the need

When developing, it's a common need to flush various caches, a need that is conveniently met by the "Flush all caches" item and its submenu items in the admin bar.

Views is an exception to the convenience: The "Clear Views' cache" button is buried in the Advanced sub-tab of the Settings tab of the Views page (and if one has a lot of Views, the Settings menu item is at the bottom of the admin bar submenu, sometimes not even visible when there are long lists of Views). It would be nice to add the ability to clear the Views cache from the same submenu in the admin bar as all the other cache-clearings.

## Proposed solution

Add **Home > Flush all caches > Views** to the admin bar if Views UI module is enabled.

It should be straightforward. The function `views_ui_tools_clear_cache()` does the clearing. Once would simply need to implement `hook_admin_bar_cache_info()`, along the lines of `system_admin_bar_cache_info()` or `update_admin_bar_cache_info()`; presumably as `views_ui_admin_bar_cache_info().`

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes the ability for developers to clear the Views cache directly from the admin bar.

**Comment by indigoxela** [comment]
Good catch, flushing the views cache should be available via admin bar.

In fact, it *is* available in D7 and D9, so IMO this isn't really a new feature, but a task. Not adding it yet has probably just been an oversight.

**Comment by jenlampton** [comment]
PR looks great, tested in sandbox, works like a charm! RTBC from me :)

**Comment by klonos** [comment]
Very useful improvement @bugfolder 👍🏼 🙏🏼 

Added the milestone label - someone should add the actual milestone.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.23.x. Thanks folks!
