### ISSUE TITLE
Card images not loading on first home page load

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5742]
On my local, when I first install a vanilla Backdrop site, I see this upon initial loading of the home page:

![image](https://user-images.githubusercontent.com/2423362/186193426-598c16ee-e542-4a96-b47a-4a4ebe358cf3.png)

After I refresh the page once, the missing images and the broken layout is fixed (the width of the 2 first cards is restored to the normal dimensions), so no biggie really - just annoying, and most likely bad first impression for those that do not regularly install Backdrop sites.

Also noting that each time it is those first 2 images/cards that are not loaded properly, and the last card that does load.

Not sure if anyone else has been having this issue(?)

**Comment by olafgrabienski** [comment]
Hey @klonos, I guess this is a duplicate of #5631. Can you have a look at it?

> Also noting that each time it is those first 2 images/cards that are not loaded properly ...

Interestingly, in the other issue report it was the third image.

**Comment by klonos** [comment]
Thanks @olafgrabienski, yes, it is a duplicate as it seems.
