### ISSUE TITLE
Datestamp default values with value2 same as value - second value stays empty

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5744]
## Description of the bug

While digging in the date module, I came across a bug. With a specific field + setup combination the default for value2 won't work.

## Steps To Reproduce

1. Attach a datestamp (Unix timestamp) field to a content type, collect end date
2. Set the field's "Default date" to some relative value
3. Set the field's "Default end date" to "_Same as Default date_"
4. Try to create a new node of that content type

## Actual behavior

The start default value is set, but the end date value is empty.

After digging a bit, it turned out that function [date_default_value_part](https://docs.backdropcms.org/api/backdrop/core%21modules%21date%21date.elements.inc/function/date_default_value_part/1) attempts to create a new BackdropDateTime from the timestamp, which is wrong for <s>two</s> one reason:

1. <s>That BackdropDateTime object has possibly already been created</s> nope, wrong
2. Creating a BackdropDateTime from a timestamp would require to prepend an `@`

The object exists, but has an error:

```
   'errors' => 
  array (
    'date' => 'The date "1661950450" does not match the expected format.',
  ),
```

![empty-end-date](https://user-images.githubusercontent.com/842066/186911042-e216ee46-e09f-49fd-9756-5971762f606b.png)

## Expected behavior

Both values should be set.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4181) is available for testing and review.

**Comment by argiepiano** [comment]
A quick additional note: if I choose the "Select list" widget, the end date is set correctly. I can only reproduce this with the Pop-up calendar and the Text widgets.

**Comment by argiepiano** [comment]
I've tested with different widgets and date types. WFM 👍🏽 

A side benefit: the end date now is shown by default (as it should) when creating a new node and when there is a default value for it. Before, even when the default value2 was set (when you used the Select list widget), the checkbox "Show end date" was not checked by default. Very annoying.

**Comment by quicksketch** [comment]
Thanks @indigoxela and @argiepiano! Merged https://github.com/backdrop/backdrop/pull/4181 into 1.x and 1.22.x.

Thanks @herbdool for keeping on top of milestone grooming too. It definitely makes keeping on top of priority issues a lot easier.
