### ISSUE TITLE
Don't convert fieldset to vertical tab if there is only one in the group

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5747]
## Description of the need

If there is only one vertical tab aka fieldset that is being exposed to the end user then don't convert it to a vertical tab. Keep it as the default fieldset.

With just one field set it looks odd. See examples in this issue: https://github.com/backdrop/backdrop-issues/issues/3872 or this:

![2022-08-27 14 40 50 bd1 lndo site c55648385102](https://user-images.githubusercontent.com/1071483/187043896-ded4c385-dbdf-4193-adee-9d9a5f8dc564.png)

Better to just leave it a fieldset.

![2022-08-27 14 42 23 bd1 lndo site 0101e89928e8](https://user-images.githubusercontent.com/1071483/187043926-cd5d9ce2-b4d6-452e-8e03-12be7048130c.png)

## Proposed solution

In `vertical-tabs.js` we could change it to:

```
if ($fieldsets.length <= 1) {
        return;
      }
```

**Comment by indigoxela** [comment]
This seems like something we should have done earlier. :wink:

Works for me!

Here's a probably better example for a single fieldset (URL settings) - which is *very* compact when a collapsed fieldset:

![one-item-fieldset](https://user-images.githubusercontent.com/842066/187065098-d2c6c1c9-9dfb-4045-be46-c2be2cd8b03c.png)

But unnecessarily uses space (and looks a little odd) when it's in vertical tabs:

![one-item-vertitabs](https://user-images.githubusercontent.com/842066/187065111-daae4ad3-6d9f-4a15-b298-e5b89001809d.png)

**Comment by bugfolder** [comment]
Wow, a code change I feel qualified to review 😉. LGTM.

**Comment by quicksketch** [comment]
This is a great idea! I merged https://github.com/backdrop/backdrop/pull/4184 into 1.x for 1.23.0. I think this will help quite a bit with the presentation of the user profile form in https://github.com/backdrop/backdrop-issues/issues/3872 for less-privileged users.

Conceivably this is okay for 1.22.3 as well (as a UX improvement), but unless there's a strong reason I think waiting for 1.23.0 should be fine.

Thanks @herbdool, @indigoxela, and @bugfolder!

**Comment by jenlampton** [comment]
This change also goes against the interface pattern that "Everything in a vertical tab can safely be ignored" since we're now putting things that can be ignored outside vertical tabs. This change will accidentally train people to inspect things on the page that do not need to be inspected, wasting and time and decreasing the "ease of use" of the software. 

I do agree that it looks much better this way, I just wanted to note the UX regression for posterity's sake :)

**Comment by klonos** [comment]
> ...since we're now putting things that can be ignored outside vertical tabs.

@jenlampton should be easily fixable by setting `'#collapsible' => TRUE` + `'#collapsed' => TRUE` where applicable. That should render the fieldset as collapsed by default (and should also display summary text on the fieldset label too). See related #5783 (where I've done the opposite for settings that should be visible/exposed all the time).
