### ISSUE TITLE
Log completely unusable when an entry has corrupt serialized data.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5761]
This is to crossport https://www.drupal.org/project/drupal/issues/2790857, which was recently committed to D7 core:

> If an entry in the dblog has corrupt serialized data, the dblog page (`/admin/reports/dblog`) will throw an exception and will not load.
> 
> If unserialize fails, then a boolean is sent to `t()` leading to a fatal exception.
> `$output = t($event->message, unserialize($event->variables));`

**Comment by indigoxela** [comment]
Fancy, I never ran into this before, but I can confirm that Backdrop is also affected.

I created a dump for a watchdog table and edited it to make the "variables" column content unusable (added some random characters). After importing and going to /admin/reports/dblog I get:

![broken-watchdog](https://user-images.githubusercontent.com/842066/188470395-a51a5f9a-442d-4077-8e02-5781e08ee6df.png)

Then applied the [patch](https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/4190.diff) and went back to /admin/reports/dblog - and the page works again.

**Comment by bugfolder** [comment]
Code reviewed, LGTM.

**Comment by quicksketch** [comment]
Thanks for reviewing this @bugfolder! Looks like a good port from Drupal 7. I merged https://github.com/backdrop/backdrop/pull/4190 into 1.x and 1.26.x. Thanks @klonos and @indigoxela for the PR and testing!
