### ISSUE TITLE
Fixed: `testCommentInterface()` tests broken due to typo in recent commit.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5764]
We missed this one when reviewing the PR for #4569:
![image](https://user-images.githubusercontent.com/2423362/188474899-23e1c505-282c-48c4-9146-f5b2b2771c1c.png)

Offending commit/line here: https://github.com/backdrop/backdrop/commit/85025fc263261a0eb35f4d9eeb8e29d971f8a813#diff-dadba67983d87c083531601ad65af844839774acc095d81b8caf97df07701589R456

I'm surprised as to why more tests are not failing 🤔

**Comment by klonos** [comment]
...changing the milestone to the next minor, since https://github.com/backdrop/backdrop-issues/issues/4569 was a new feature, and these changes were introduced only in the 1.x branch.

**Comment by indigoxela** [comment]
Ouch, how did that syntax error sneak in! We definitely have to find a way to prevent ugly things like that, a simple `php -l` would do the trick (I'll open a separate issue for that).

@klonos weird, additionally to CommentRSSUnitTest now also LayoutUpgradePathTest seems to fail.

**Comment by klonos** [comment]
Yes, we should definitely implement #5296 👍🏼 ...it will prevent missing simple things like this one that may be causing headaches later.

I'll have a look at the failures as soon as possible.

**Comment by quicksketch** [comment]
Thanks @klonos! PR looks good but an additional fix is needed, as comment tests have a single failure.

**Comment by indigoxela** [comment]
@klonos will you find the time to work on this soon? To me it seems important, that our testing suite is fully functional.

**Comment by klonos** [comment]
@indigoxela no time unfortunately 😞 ...please feel free to either file a completely new PR or changes against my branch.

**Comment by indigoxela** [comment]
> ... no time unfortunately

Oh, sad to hear, but understood. In this case I'll start with a fresh (tiny) [PR](https://github.com/backdrop/backdrop/pull/4199).

@klonos you might want to create an individual issue for your (otherwise unrelated) wording improvement?

**Comment by herbdool** [comment]
This looks good now.

**Comment by klonos** [comment]
> @klonos you might want to create an individual issue for your (otherwise unrelated) wording improvement?

@indigoxela that is a tiny change in the message, and it seems to be a clear copy/paste mistake. We currently have two consecutive sections in the test we are now fixing, and these 2 tests test the same but opposite thing, yet they both have the exact same message `Individual comment title found.` and what is needed is for one of them to include the word "not" in it. Totally not worth a separate issue and PR for such a thing.

**Comment by quicksketch** [comment]
I went ahead and merged https://github.com/backdrop/backdrop/pull/4199 into 1.x to get our tests fully working again. No need to open another issue for the typo if you want to include it here, but we'll need a new PR.

Thanks @indigoxela, @herbdool, and @klonos!

**Comment by klonos** [comment]
@quicksketch and/or @herbdool follow-up PR to fix the typo in the `assertText()` message here: https://github.com/backdrop/backdrop/pull/4201

**Comment by quicksketch** [comment]
Thanks, follow-up has also been merged!
