### ISSUE TITLE
[UX] Add Requirements check for max_input_vars to status report

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5771]
Today @quicksketch mentioned that maybe we should split the status report update out of the PR for [[UX] set warning messages if max_input_vars is not sufficiently large](https://github.com/backdrop/backdrop-issues/issues/3824).

The status report message could stand on its own, and could get into the next minor version, and would be a benefit on its own.

We can keep working on the error messaging in [the other issue](https://github.com/backdrop/backdrop-issues/issues/3824) and improve as needed.

Advocate: @jenlampton

**Comment by jenlampton** [comment]
working on tests.

**Comment by indigoxela** [comment]
> working on tests.

My suspicion: the upgrade and update tests fail, because of the "requirement warning" - that seems to be a killer.

The other thing is the unrelated broken testCommentInterface, which should urgently get fixed.

**Comment by jenlampton** [comment]
I'm playing with the requirements checks: I wasn't aware a REQUIREMENT_WARNING would cause a problem during upgrade or install phase. I'll add an exception for those phases to downgrade to REQUIREMENT_INFO. Testing locally now... but I'm expecting tests to pass on the PR even without that change. 🤞

**Comment by jenlampton** [comment]
okay I rebased and added a special status for upgrade and install that's different from runtime. Pushed again but tests already seem to be passing 🎉

**Comment by klonos** [comment]
Thanks @jenlampton 🙏🏼 ...code LGTM, so I've RTBC'ed it.

I've added a small suggestion to wrap the message title in `<code>` tags, but otherwise this is good to go.

PS: can you please either close/reopen the PR, or rebase in order to trigger a tugboat sandbox?

**Comment by klonos** [comment]
...I've tested this on my local, and it looks fine:
![image](https://user-images.githubusercontent.com/2423362/210064578-b3663dc2-2d36-4e61-80b8-d9b7bcf56894.png)

You won't be able to trigger it in the PR sandbox, but this is what it looks on my local after reducing the `max_input_vars` setting below the threshold of 1000 (I wasn't able to get `ini_set()` in `settings.php` nor directly setting it in `.htaccess` to work on my local - I had to do it within my lando setup instead, using a custom php.ini file):
![image](https://user-images.githubusercontent.com/2423362/210069353-feb6a0cf-b8c9-4a5c-9198-d0065d060eca.png)

**Comment by quicksketch** [comment]
https://github.com/backdrop/backdrop/pull/4197 has been merged into 1.x and 1.23.x. Thanks @jenlampton, @klonos, and @indigoxela!
