### ISSUE TITLE
Fix minor spelling mistake in views plugins documentation.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#5772]
## Description of the bug

I was looking through `views_plugin_argument_default_current_user.inc` and happened to notice a small spelling mistake. I did a search for `odes` and found this spelling mistake also exists in `views_plugin_argument_default_node.inc`.

> This plugin actually has no options so it odes not need to do a great deal.

Should be:

> This plugin actually has no options so it **does** not need to do a great deal.

see 
* https://github.com/backdrop/backdrop/blob/1.x/core/modules/user/views/views_plugin_argument_default_current_user.inc
* https://github.com/backdrop/backdrop/blob/1.x/core/modules/node/views/views_plugin_argument_default_node.inc

**Comment by vedsom** [comment]
hey @jenlampton @laryn can you assign me this task. I can solve this issue under hactoberfest.

**Comment by vedsom** [comment]
hey, @bugfolder can you elaborate a little on which folder docs I have to work n?

**Comment by indigoxela** [comment]
Hi @vedsom,

the folders are `core/modules/node/views/` and `core/modules/user/views/`, both affected files are linked in the issue description.

**Comment by vedsom** [comment]
Hey, @indigoxela I have solved the problems of the affected files and created a PR. Have a look!!!

**Comment by indigoxela** [comment]
@vedsom many thanks for your PR :pray:

A straight forward, comment only spelling fix, RTBC! :+1:

**Comment by vedsom** [comment]
> @vedsom many thanks for your PR 🙏
> 
> A straight forward, comment only spelling fix, RTBC! Sorry didn't get it, do i have to comment spelling fix in pr??

**Comment by indigoxela** [comment]
> didn't get it, do i have to comment spelling fix in pr??

Maybe my wording wasn't ideal - yes, your spelling fix is in a docblock *comment*. :wink:

**Comment by vedsom** [comment]
> > didn't get it, do i have to comment spelling fix in pr??
> 
> Maybe my wording wasn't ideal - yes, your spelling fix is in a docblock _comment_. 😉

No worry I respect your work. Is it fine now I have updated the comment.

**Comment by indigoxela** [comment]
> Is it fine now I have updated the comment.

Now I'm confused - it has always been fine. No need for an update.

I'll give it another try to more clearly explain what I meant:

- You fixed a problem
- You fixed it in a comment (you PR change is *within* a php comment (documentation blocks are (technically) code comments)
- As it's inside a comment, there's no need to test anything (no change in functionality)
- There's nothing to do for you @vedsom - you did everything right
- Someone with enough permissions can merge it into core

**Comment by vedsom** [comment]
Ok so i have nothing to do, everything is correct and someone will merge it in upcoming time right!!

**Comment by klonos** [comment]
Yes @vedsom, your PR has been approved and is ready to be merged by one of our core committers. Nothing else that needs to be done on your end.

Thank you for contributing 🙏🏼

**Comment by vedsom** [comment]
> Yes @vedsom, your PR has been approved and is ready to be merged by one of our core committers. Nothing else that needs to be done on your end.
> 
> Thank you for contributing 🙏🏼

It's is part of hactoberfest??

**Comment by laryn** [comment]
Thanks @vedsom @indigoxela and @klonos -- merged into `1.x` and `1.23.x`. And special thanks for your first contribution @vedsom! :tada:
