### ISSUE TITLE
[DX][UX] Do not hardcode allowed extensions for CKEditor uploads

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5773]
This came up in Zulip: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Webp/near/297828246

@laryn 
> I'm trying to upload a .webp image in CKEditor and getting this message:
>>The selected file filename.webp cannot be uploaded. Only files with the following extensions are allowed: gif, png, jpg, jpeg.
>
>Where do I configure that in CKEditor?

@jenlampton 
>I think there's a variable for allowed filetypes, I think you can override it in settings.php?

@klonos 
>Can't see anything in `settings.php` ...but I'd expect that setting to be per text format 🤔 
...

> ...that error message comes from `file_validate_extensions()`, which is called in 3 places. One of them is the `FileValidatorTest::testFileValidateExtensions` test, and the other 2 places are `file_save_upload()` and `hook_file_insert()`.
> ...if no custom validator is provided, then the list of extensions defaults to the list in https://github.com/backdrop/backdrop/blob/1.x/core/includes/file.inc#L1576, which currently has:
> ```php
> $extensions = 'jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp docx docm pptx pptm xlsx xlsm';
> ```

**Comment by klonos** [comment]
...so at least 2 developers expected to find a CKEditor setting in the UI for this (I personally was hoping to find it in the "Image uploading" fieldset/section under `admin/config/content/formats/filtered_html`), and another developer was expecting a setting in `settings.php`.

I find value in having both, so I propose that we include a setting in `settings.php` that holds the defaults (instead of having them be hardcoded in `file_save_upload()`) + also an optional per-format setting to override the defaults.

Would a hook also make sense here?

**Comment by klonos** [comment]
...the initial issue title was rather long 😅

**Comment by klonos** [comment]
...also, since Backdrop officially supports .webp since v1.18, we should add that extension to the defaults ...but that may be slightly tricky to do in `settings.php`, since the support for this format relies on whether the installed version of PHP supports it 🤔

**Comment by indigoxela** [comment]
AFAIK currently the only way to influence the uploadable extensions is hook_form_alter() on filter_format_editor_image_form(), which is really inconvenient. Toggling via settings.php isn't very convenient, either.

I'd vote for a UI setting on admin/config/content/formats/FORMAT (filter_editor_image_upload_settings_form()).

Here's the place where extensions are hardcoded: https://github.com/backdrop/backdrop/blob/1.x/core/modules/filter/filter.pages.inc#L91

**Comment by herbdool** [comment]
My PR on issue #4937 would solve this too https://github.com/backdrop/backdrop/pull/4366 I believe. It introduces a new function that can pull the supported extensions per toolkit and a file validator can call it.

**Comment by herbdool** [comment]
Closing. This has been addressed by https://github.com/backdrop/backdrop-issues/issues/4937. (Feel free to reopen if you disagree)
