### ISSUE TITLE
Link fields are not being validated

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#5775]
I create a link type field and mark the url validation, but it doesn't validate anything. But this used to work, isn't?

**Comment by argiepiano** [comment]
It all depends on what you understand by "validation". The field is validated for valid URL patterns. Can you paste an example that's not working?

I just tried entering `https://test wrong`  (space, no dot) and the validation failed as expected.

**Comment by robertgarrigos** [comment]
I just tried to enter a simple string, without http, and it just accepts it, as it thinks it is an internal link, which actually doesn't exist.

**Comment by indigoxela** [comment]
@robertgarrigos the existence of a link target has never been validated. The checks only validate the syntax, but don't actually follow any urls (no http calls or so). So this seems to be either a misunderstanding, or a feature request.

**Comment by robertgarrigos** [comment]
The problem is that the field accepts either an external link or an internal one. How does it know whether you are entering one or the other? Just because you start typing http...?

**Comment by argiepiano** [comment]
> Just because you start typing http...?

Yes. And several other URL schemes.

**Comment by argiepiano** [comment]
Check out the list of protocols that are accepted as external:
https://github.com/backdrop/backdrop/blob/c90150631ca5c5aaddd200f8eca7c69bda17a3d1/core/modules/link/link.module#L1058

**Comment by klonos** [comment]
Let's not rush to close this just because things make sense from a developer point of view. There was clearly a UX WTF here that I'm sure we can fix by improving the help text of that setting. It currently says `If checked, the URL field will be verified as a valid URL during validation.`

- I don't think that the "if checked" bit is needed
- we should add what @argiepiano explained with "Yes (when you enter something with `https`). And several other URL schemes." and also "Check out the list of protocols that are accepted as external:"

**Comment by klonos** [comment]
How about something like this?:

`Validates the provided value if a URL with a protocol (like `https://`) was entered, otherwise accepts any internal path.`

I'm sure we''l have smarter suggestions by others, but that's a start.

**Comment by argiepiano** [comment]
The original post was about the Link validation not working. It wasn't about the help text. I think we should open a separate issue. Validation is working as designed. Keeping this as "works as designed" also has important value as it may help future searches looking for keywords.

**Comment by klonos** [comment]
Agreed 👍🏼 ...sorry.

Filed a new documentation task here: #5779

**Comment by indigoxela** [comment]
I'd like to provide some additional info.

We have several related open issues - the link module seems to cause lots of WTF... Especially as the link dialog (with CKEditor) behaves quite differently.

- #4974
- #5646
- #5000
