### ISSUE TITLE
File Access Checks Fail if no Type is defined (throw a warning or watchdog)?

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5777]
## Description of the bug

When upgrading from Drupal 7 or early versions of Backdrop (before File Entities were introduced), if using the "Download Link" formatter, the link is never displayed unless the user has `bypass file access`. This seems to be because `file_access()` with an `$op = 'download'` fails when files have no `type` attribute specified (which is done on cron jobs).

Note this only affects the "Download link" formatter. If the formatter is "Generic file" or "URL to file", both show and the file can be downloaded.

## Steps To Reproduce

- Upgrade from Drupal 7 with a simple site that includes a file field.
- After upgrade, set the file formatter to "Download link"
- Now log out and view as anonymous. The download link is hidden.
- Grant the "Audio: Download any files", "Document: Download any files", "Image: Download any files", and "Video: Download any files" permissions. The download link is still hidden.

This appears to be caused by upgraded files not yet having a "type" specified. The type gets specified over a series of cron jobs, but the situation of a site upgrade with thousands of files, that could take several days for the type data to fully get populated.

## Additional information

- Backdrop CMS version: 1.22.3
- Web server and its version: Apache
- Operating System and its version: Ubuntu 22.04
- Browser(s) and their versions: All

**Comment by indigoxela** [comment]
Maybe my (rejected) PR for the other issue could partly be helpful here: https://github.com/backdrop/backdrop/pull/3954/files

Yes, file access functions in their current state are ... not great. :stuck_out_tongue_winking_eye:

**Comment by indigoxela** [comment]
Wait a minute...

@quicksketch can you check the specific permission to "Download any YOURTYPE" on /admin/config/people/permissions?

To "View a file" (entity) and to download a file are different things. Rather confusing, BTW, that viewing a "File" (on file/FID) doesn't actually grant the download permission.

**Comment by quicksketch** [comment]
I enabled all the "Download any _TYPE_" permissions for anonymous users and the Download link still does not show. In this case it's an image, but I enabled all of them to no effect.

**Comment by argiepiano** [comment]
> To "View a file" (entity) and to download a file are different things. Rather confusing, BTW, that viewing a "File" (on file/FID) doesn't actually grant the download permission.

Perhaps we should clarify (somewhere) what "view a file" means. I may be mistaken about this, but my understanding is that "view a file" refers to viewing the **file entity page**, not he file itself (that is, viewing the file entity page at file/[fid]). Downloading a file means downloading the asset itself, to which the file entity points.    

As file entities are fieldable, this means that "viewing a file" may actually display also all the fields attached to the file entity.

**Comment by indigoxela** [comment]
@quicksketch I'm having trouble to reproduce, here's what I tried, please point me to the step(s) I might have missed:

- A content type with a "Document" field
- File type "Document", manage file display (default), Display type "Download link"
- Permission for anonymous "Document: Download any files" granted, no other File permission granted
- Node type display: Document - Download link (text adapted to verify) - anonymous access to node - WFM, link shows up
- Variant for Node type display: Document - Rendered file, view mode default (the one with the download link specified) - anonymous access to node - WFM, link shows up

Some head scratching and cache flushing - still works.

- Revoked permission for anonymous to "Document: Download any files".
- Node display setting: Rendered file / view mode default: a link is visible, but to the actual pdf (asset), not the download link... huh? :thinking: 
- Node display setting: Download link - the link is gone. :+1:
- Enable permission to download - the link is back for anonymous. :+1:

So for my setup many things work, but the link switch from `/file/FID/download?token=XXXX` to `/files/documents/da-pdf.pdf` came unexpected. (Note only when the display mode in the node is set to "Rendered file" and the File (entity) "Display type" is set to "Download link". Besides that fallback things seem to work as expected.

**Comment by quicksketch** [comment]
Thanks @indigoxela, I really appreciate your help here! I think you're right... the download link _does_ work, but my problem was that this site was a D7 upgrade, and the cron jobs to categorize each type of file has not fully run (there are thousands of files). So my existing files have no "Type" specified, and therefor the type-based permissions ("Document: Download any file", "Image: Download any file", etc) do not work, because a `$file->type` is not yet assigned.

Perhaps this is fine? It completely threw me for a loop. Maybe we should add something as simple as a `watchdog()` notice if file access checks are encountered, but fail because a `type` is not specified?

**Comment by quicksketch** [comment]
I updated the summary to more accurately reflect the situation. I apologize my steps to reproduce were overly simplified and I did not test them on a new install. Thanks @indigoxela and @argiepiano for re-testing. :bow:

**Comment by argiepiano** [comment]
So, here are a couple of quick thoughts...

We can approach this from two different sides:

## Assure all file entities have bundles
Since file entities are fieldable, they must have a bundle, otherwise they are faulty. As @quicksketch discovered, this becomes a problem when upgrading D7 sites with tons of files, as the bundle may not get assigned right away. 

I think that the functionality of node access permissions may present a similar situation. In that case, the admin gets a "red dot" in the Reports admin menu prompting them to rebuild permissions when needed. This process is not handled by cron or cache flushing, but has to be run manually (because of the time it may take). So, perhaps a good way to handle this is to create a similar alert if the `file_type_determine` queue is found not to be empty, and create a menu item that runs a batch process that calls `file_determine_type()`.

It may even be possible to skip cron altogether, and just use this alert system to determine type; it can become another post-upgrade task for the admin. 

## Allow download of any file
Additionally we should consider creating a new permission, "Download any files" that doesn't check for type. This could be done in the new `file_file_access()` function.

**Comment by indigoxela** [comment]
> my problem was that this site was a D7 upgrade, and the cron jobs to categorize each type of file has not fully run...

That explains it!

Other people might run into that, too, so we should definitely do something about that.

In file_update_1003() a message is set that warns:
```
"All files must now be classified according to file types. Your files have been queued for processing, and will have their file type determined during cron runs."
```
But IIRC, this only shows once - later there's not indication, that a task still isn't complete. (Correct me if I'm wrong)

I agree with @argiepiano's suggestion to warn people (with a "red dot" or just some hints on the status page) and to possibly create a batch job, so people can finalize the task more quickly.

**Comment by quicksketch** [comment]
I like @argiepiano's suggestion too (the first one). There is a very strong similarity to node access needing to be rebuilt and we should make a status message if any file does not have a type assigned. :+1:

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4212

The new code:
- Creates a "red dot" alert in status if file types need to be classified upon D7 upgrade
- Creates a batch process classify file types
- Removes the old cron process - NOTE: file classification will not be run on cron jobs. Rather, it has to be run manually by the admin as one of the post-upgrade tasks

Please test and review.

**Comment by argiepiano** [comment]
To test:
1. Create a vanilla Drupal 7 site. Add a file field field to a content type
2. Add content with files
3. Proceed to upgrade the site to Backdrop
4. Check that the "red dot" alert appears in the Status report
5. Follow the prompts to classify file types
6. Check the table `file_managed` for the `type` column. There should be no `undefined` entry in `type`

**Comment by quicksketch** [comment]
Thanks @argiepiano!! The PR looks great in approach and I tested it with success! I greatly prefer this approach over the invisible cron-queue operation from before.

![image](https://user-images.githubusercontent.com/100206/192128282-1cdcb11a-34bf-4a44-a07f-0827c681c46e.png)

I haven't looked at Batch API in a while, is it possible to remove the "Completed 0 of 1" portion of the message? It stays at 0 for the whole operation.

I also left some feedback in the PR: https://github.com/backdrop/backdrop/pull/4212#pullrequestreview-1119368443

But this solves my original report with flying colors! Now the "Document: Download any files " permission works for my PDF examples.

**Comment by quicksketch** [comment]
@argiepiano Now that you're in the zone for writing batches, would you be interested in taking a look at batching the Search Index? :bowing_man: :sweat_smile: https://github.com/backdrop/backdrop-issues/issues/4182

**Comment by argiepiano** [comment]
Thanks for testing, @quicksketch 🙏🏽 

I've made the modification you requested. Please check those and let me know if there is anything else.

**Comment by quicksketch** [comment]
This looks great! I applied on my mostly-upgraded Drupal 7 site and it correctly identified that files were not completely upgraded, deleted the batch, and replaced it with a status report message indicating files needed conversion.

![Screenshot from 2022-09-25 16-08-24](https://user-images.githubusercontent.com/100206/192169686-26a5e4d4-b1e8-4162-a810-d0873add7479.png)

The process ran without any issue and now has a bit less noise.

![image](https://user-images.githubusercontent.com/100206/192169679-9a1474de-e800-4d67-b6e6-6e3124a2bc84.png)

Seems like a great improvement to our upgrade process. :+1:

**Comment by quicksketch** [comment]
Thanks @argiepiano and @indigoxela for your help on fixing this problem! I merged https://github.com/backdrop/backdrop/pull/4212 into 1.x and 1.23.x.
