### ISSUE TITLE
Misnomer: "database updates" in Backdrop may also be CMI updates

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5778]
This was brought up by @laryn in Zulip, during the preparation of the 1.22.0 release: https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Release.20Day/near/282444669

> Also, is this term "database updates" potentially a misnomer at this point?
> e.g. an update hook that only affects CMI

...

> I found an update hook here: https://github.com/backdrop/backdrop-issues/issues/336
> Which prompted the question above since it's a CMI update (not a database update) but will still trigger the red warning, right?

Should we rename that to "database and configuration updates"? ...or something else that encompasses both types of updates.

**Comment by indigoxela** [comment]
Hehe, ... #1986

Yes, we should really reword that.

**Comment by klonos** [comment]
I'm getting old and forgetful 😞
