### ISSUE TITLE
[UX] User edit/create form: render the "Account settings" fieldset as non-collapsible if it is the only one

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5783]
This is a follow-up to #5747.

With that change in (which is good 👍🏼 ) you get this by default when editing an existing user account:
![image](https://user-images.githubusercontent.com/2423362/190691934-143294ef-034a-431e-a8c4-5cbc9dd7b6e1.png)

But when adding a new account, the collapsible but always-expanded fieldset with the summary text feels odd:
![image](https://user-images.githubusercontent.com/2423362/190692135-42c25da0-eb6f-4254-8852-d342a4924431.png)

I believe that that should be a "fixed", non-collapsible fieldset instead.

**Comment by klonos** [comment]
...not sure if this should apply globally - perhaps it should only be implemented in the user edit form specifically 🤔

**Comment by klonos** [comment]
...yeah, let's make this only specific to the user edit/create form. Simple fix too 😉

**Comment by klonos** [comment]
...we don't need all those `'#collapsible' => TRUE,` properties for the fieldsets in this form now that they have been converted into vtabs. PR here: https://github.com/backdrop/backdrop/pull/4206

![image](https://user-images.githubusercontent.com/2423362/190699158-22885e76-984c-499e-95c6-10788aaa7078.png)

**Comment by jenlampton** [comment]
This looks great in the latest PR: 
<img width="1222" alt="Screen Shot 2022-12-30 at 3 55 50 PM" src="https://user-images.githubusercontent.com/397895/210120760-e79fc54c-a65b-4fe8-9c60-80cfaacb087e.png">

**Comment by klonos** [comment]
@jenlampton wrong screenshot 😅 ...that one belong in #647 😉 

Thanks for RTBC'ing this. ...do you want to also remove the milestone label and add the proper milestone?

**Comment by jenlampton** [comment]
Updated the screenshot too. Whoopsie :)

**Comment by quicksketch** [comment]
This looks good to me. Removing `#collapsible` also removes the entirely unnecessary "Summary" shown in the upper-right corner of the fields (e.g. `(Active, no roles)` in the first screenshot). I merged https://github.com/backdrop/backdrop/pull/4206 into 1.x and 1.23.x.
