### ISSUE TITLE
Clear View Render/Query Cache After Modifying View

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5784]
## Description of the bug

I've noticed that the query and render cache for views seems to persist even after I've modified the view. That can be confusing because I expect to see my changes immediately. This is as a logged in user with no page cache.

I could not find this particular bug in any of the currently open Views cross-port issues, so it might be Backdrop-specific.

## Steps To Reproduce

1. Create a view of content that creates a page.
2. Enable render cache and set a time limit of 7 days.
3. Save the view and visit the page.
4. Edit the view, add an additional field to the view or make any other visible change.
5. Save the view and visit the page.
6. The cached copy of the view from before your changes persists.
7. Clear the cache from the admin bar.
8. The new changes now show up.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.23.0
- Web server and its version: nginx
- Operating System and its version: Ubuntu 22.04
- Browser(s) and their versions: Firefox

**Comment by klonos** [comment]
Hmm 🤔 ...wasn't this issue meant to have been fixed (a long time ago too) by [Allow newly added fields to show up in Views UI w/o manual cache flush](https://www.drupal.org/project/views/issues/810936)? The changes from the patch that was applied in Views 7.x-3.x seem to be already included in Backdrop. Specifically, all `views_field_[create|update|delete]_instance()` functions.

🤔

**Comment by argiepiano** [comment]
I can't reproduce this issue. I've followed each of the steps (including enabling 6 day cache from the Views UI), and the modified view is shown correctly both to authentic and anonymous users. I'm using 1.23.0 and Apache/2.4.46 on Chrome

**Comment by quicksketch** [comment]
Thanks to both of you for checking... on a fresh install I am not seeing this issue either! On my current project I have run into it repeatedly. It may be site-specific. I'll close this unless I have some steps to reproduce.
