### ISSUE TITLE
User module implements inexistent hook `hook_admin_menu_output_alter`

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5789]
## Description of the bug

Function `user_admin_menu_output_alter()` implements an inexistent hook, `hook_admin_menu_output_alter()`.  This hook was replaced by `hook_admin_bar_output_alter()` in issue #323 all over the place 8 years ago, but apparently this implementation of the old hook was missed.  
Furthermore, instead of checking `$content['menu']['menu']['admin/config']['admin/config/people']['admin/config/people/manage']['admin/config/people/manage/fields']` is set and unset that array value, it checks for (and unsets) `$content['menu']['menu']['admin/config']['admin/config/people']['admin/config/people/manage/fields']`.

## Steps To Reproduce
None. The hook is never run. I'm not sure if it's even needed, since no one has noticed it. I haven't dug into it, but perhaps a recent bug report (#5787) is somehow related to this.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.23.0

**Comment by kiamlaluno** [comment]
The comment given in [`user_admin_menu_output_alter()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_admin_menu_output_alter/1) says:

> Admin menu shows both the parent menu item and its children, remove the duplicate child element show "Manage fields" doesn't show up twice.

(I guess that *show* should instead be *so*.)

If *Manage fields* doesn't show up twice, it means that hook isn't even necessary.

**Comment by argiepiano** [comment]
@kiamlaluno thank you for providing a PR! 🙏🏽 

I've tested it, and discovered that the array key for the $content variable was also wrong in the original code. I've added the correct keys for both the if statement and the unset command in the PR.

**Comment by kiamlaluno** [comment]
I was waiting for the Tugboat preview to be available and verify the issue was resolved, but the test failures seems to not make the preview available.

I changed the code as suggested.

**Comment by indigoxela** [comment]
> I was waiting for the Tugboat preview to be available...

@kiamlaluno it *is* available - at least, I can see it. The test runners and the Tugboat preview are completely unrelated.

**Comment by kiamlaluno** [comment]
@indigoxela I now see it. (I must be blind or I was watching in the wrong place.)

I thought they were related because, when I create a PR, I see a list of starting tests and a *Tugboat* line. I wrongly understood that line as being one of the tests.

I checked the Tugboat preview. The duplicated menu item isn't anymore visible.

**Comment by argiepiano** [comment]
I believe that was the expected result when someone added this hook implementation. Small cosmetic change. WFM

**Comment by argiepiano** [comment]
Someone else needs to add the milestone number for this.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno, @argiepiano, and @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4210 into 1.x and 1.23.x.
