### ISSUE TITLE
Installation asks again for Database Configuration and then breaks

### ISSUE THREAD

**Issue by juanolalla** [backdrop/backdrop-issues#579]
I download the zip, give write permissions to settings.php and init the installation. I enter the database configuration, and then, the same page is loaded again with empty fields, asking me again the database configuration (/core/install.php?langcode=en&profile=standard&op=start&id=1, so &op=start&id=1 is added to the previous URL).

At this point:
* The files directory has been generated with the config hash directory inside
* 22 tables are generated in the database:  batch, cache, cache_bootstrap, cache_menu, cache_page, cache_path, file_managed, file_usage, flood, menu_links, menu_router, queue, semaphore, sequences, sessions, state, system, tempstore, url_alias, users, users_roles, variable
* settings.php has been modified, changing the $database and $config_directories values, and adding them again with these same values at the end of the file.

Then, if I re-enter the database configuration and continue, a white screen appears.

If I first drop all tables, then re-enter the database configuration and then continue, this error message is shown: "The directory ./files/config_f428e3c155c9f4303ca851ccd2aca3ff/active must be completely empty to proceed with installation."

If I drop all tables, and the files directory, re-enter the database configuration, and then continue, the installation continues and the home page is shown with the error message: "No active batch.". The "Configure site" step has been omitted.

If I drop all tables, remove the files directory, and undo the last changes to settings.php (leaving $settings['hash_salt'] that was created previously), I'm redirected to the same page, adding and extra &op=start&id=1 at the end of the URL).

**Comment by juanolalla** [comment]
I've found a workaround and made a [pull request](https://github.com/backdrop/backdrop/pull/664). Probably this is not the right way to go but this is fixing it, so maybe it can help to find a better solution.

**Comment by juanolalla** [comment]
I've just discovered that exactly the same is happening to me with a fresh new installation of 7.34. So whatever it is, it's not a backdrop specific bug. If you're not experiencing the same it must be some incompatibility with my local configuration.

**Comment by juanolalla** [comment]
I've found the solution in my case, disabling opcache as in https://www.drupal.org/node/332730#comment-8962563

Closing the issue because it has a local solution, but I think both Drupal and Backdrop should find a way to avoid this problem without requiring the users to disable this cache methods.

**Comment by quicksketch** [comment]
Thanks @juanolalla! Looks like the Drupal patch is already completed but just hasn't been committed yet. I'll work on porting it to Backdrop.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/666 which should fix this. I also submitted an updated patch to d.o for the same issue: https://www.drupal.org/node/779482#comment-9515729
