### ISSUE TITLE
MySQL Error in View of modules and themes - MySQL 8.0+ reserved word clash with system table

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5795]
## Description of the bug

"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system.`filename` AS `filename` FROM `system` system LIMIT 10 OFFSET 0' at line 1"

## Steps To Reproduce

To reproduce the behavior:
1. On a server or installation running MYSQL 8 create a new view of "Project"
![image](https://github.com/user-attachments/assets/598c4a90-d915-4dba-af7d-1de35b7b5119)

EDIT: Updated to reflect current Backdrop (1.29.2)

2. Click on "Continue and Configure"
3. Scroll down to the preview and see:

![image](https://user-images.githubusercontent.com/3144571/191822135-216680a6-085e-4528-8198-8dcb244d48d9.png)

EDIT: Backdrop 1.29.2 - MySQL8.0.39
Error messageSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system) subquery' at line 5

![image](https://github.com/user-attachments/assets/f16baeac-c06a-4dc8-bf53-53b508b665ab)

## Additional Information

We are getting this error on a site that has lots of configuration, contrib modules, and some custom code. This might not be a core issue. 

However, I'd appreciate it if someone else running MySQL 8 could try to recreate this problem and help see if it's a MySQL problem. We are NOT getting this error on the same site using MySQL 5.7.36.

EDIT: Running on a vanilla site gets this error

<details>
<summary>Click to view a list of all contrib modules on this site:</summary>

- field_wrappers 1.x-1.1.2
- file_entity_inline 1.x-1.0.0-beta1
- font_awesome 1.x-1.2.6
- google_cse 1.x-3.0.1
- google_tag 1.x-1.6.0
- googleanalytics 1.x-2.6.2
- imce 1.x-1.0.0
- inline_entity_form 1.x-1.9.1
- job_scheduler 1.x-1.1.4
- jstorage 1.x-1.0.1
- Paragraphs 1.x-1.2.0 
- Automatic Nodetitles 1.x-1.0.4
- Backup and Migrate 1.x-1.0.20
- Better Formats 1.x-1.0
- Block reference 1.x-2.4.0
- CAPTCHA 1.x-1.7.2
- Includes: CAPTCHA, Image CAPTCHA
- Colorbox 1.x-2.17.1
- Content view access 1.x-1.0.1
- Dashboard Plus 1.x-1.0.3
- Devel 1.x-1.8.1
- Disable Term Content Listings 1.x-1.0.5
- Draggableviews 1.x-1.0.1
- Includes: Draggableviews, Draggableviews Book
- Editable Fields 1.x-1.0.1
- Entity Plus 1.x-1.0.17
- Entity UI 1.x-1.0.1
- External Links 1.x-1.18.2
- Feeds 1.x-1.1.4
- Includes: Feeds, Feeds Admin UI, Feeds Import
- Libraries 1.x-2.2.2
- Markup 1.x-1.0.0
- Masquerade 1.x-1.0.0
- Maxlength 1.x-3.3.1
- Metatag 1.x-1.22.2
- Mobile Detect 1.x-1.1.1
- Node clone 1.x-1.1.4
- Node Clone Tab 1.x-1.1.0
- On The Web 1.x-1.7.2
- Paragraphs jQuery UI Accordion 1.x-1.0.1
- Publication Date 1.x-2.2.0
- reCAPTCHA 1.x-2.2.6
- SMTP Authentication Support 1.x-1.3.4
- Special Menu Items 1.x-2.1.3
- Splashify 1.x-1.3.4
- User Guide Recipe 1.x-1.0.2
- Video Filter 1.x-3.4.1
- Viewfield 1.x-1.0.0
- Views Conditional 1.x-1.3.1
- Webform 1.x-4.24.2
- Weight 1.x-1.0.2
</details>

**Comment by stpaultim** [comment]
I was unable to recreate this on a vanilla Backdrop CMS site running MySQL 8. So, I don't think that is the problem and this is another issue that MIGHT be specific to my site. 

I will leave issue open as I try further to debug. Maybe someone else will be able to help. 

This issue came up as I was trying to generate a list of contrib modules for another error I've reported. This error is preventing me from using views to generate that report.

**Comment by indigoxela** [comment]
@stpaultim can you either provide the view (json config export), or the query?

You can get the latter if you turn on the "Show information and statistics about the view during live preview" / "Show the SQL query" on /admin/structure/views/settings.

Hopefully that gives some info why MySQL8 seems to choke on that query.

**Comment by yorkshire-pudding** [comment]
I am getting this on a couple of MySQL8 sites, running both on Lando and on a host.

<details>
<summary>View definition</summary>

```json
{
    "_config_name": "views.view.site_addons",
    "name": "site_addons",
    "description": "",
    "tag": "",
    "disabled": false,
    "base_table": "system",
    "human_name": "Site Addons",
    "core": "1.29.2",
    "display": {
        "default": {
            "display_title": "Default",
            "display_plugin": "default",
            "display_options": {
                "query": {
                    "type": "views_query",
                    "options": []
                },
                "access": {
                    "type": "none"
                },
                "cache": {
                    "type": "none"
                },
                "exposed_form": {
                    "type": "basic"
                },
                "pager": {
                    "type": "full"
                },
                "style_plugin": "default",
                "row_plugin": "fields",
                "fields": {
                    "filename": {
                        "table": "system",
                        "field": "filename",
                        "id": "filename"
                    }
                },
                "filters": [],
                "sorts": []
            }
        }
    }
}
```

</details>

The sql is:
```sql
SELECT system.`filename` AS `filename`
FROM  {system} system 
LIMIT 10
OFFSET 0
```

I can reproduce this in phpMyAdmin with:

```sql
SELECT system.`filename` AS `filename`
FROM system
LIMIT 10 OFFSET 0
```

If in phpMyAdmin I instead do:
```sql
SELECT `system`.`filename` AS `filename`
FROM 
`system`
LIMIT 10 OFFSET 0;
```
Then it works.

I think the issue is the `system` word is a reserved word for MySQL so it doesn't like it aliasing a table to that. 

![image](https://github.com/user-attachments/assets/2a29ab74-652f-462a-b60d-732d1ebfa3b0)


 This doesn't happen with MariaDB - e.g. demo sandbox

**Comment by yorkshire-pudding** [comment]
I've added a [PR](https://github.com/backdrop/backdrop/pull/4918) to see if my 'hacky' fix breaks anything and to provide a starter for discussion.

**Comment by yorkshire-pudding** [comment]
The more I think about it the less I think this is a 'hacky' fix.  The `SELECT` statement is the only place that seems to alias tables and whether actual table names or aliases, backticks is a common and recognised way to avoid clashes with reserved words.  I guess it was never a problem before MySQL 8.0.3 and is only causing an issue for this particular type of View, but as this type of View is part of core, it makes sense to fix and should avoid any problems with other reserved words either now or in the future, whether in MySQL or MariaDB (or even other database types downstream in Silkscreen CMS(?))

**Comment by argiepiano** [comment]
I haven't tested this, but I believe this will effectively prevent the approach to accessing tables in other databases that was described recently on [Zulip](https://backdrop.zulipchat.com/#narrow/channel/218635-Backdrop/topic/Give.20the.20new.20SSO.20module.20a.20try!/near/482827858), upon which the SSO module is based.

**Comment by kswan** [comment]
It seems that the quoteIdentifier method (https://github.com/backdrop/backdrop/blob/1de8b35c21487d35c2fad341ea65300186e9cf9e/core/includes/database/mysql/database.inc#L174) is intended to handle this issue. 

I can reproduce the issue using the steps in the original post.

**Comment by yorkshire-pudding** [comment]
> I haven't tested this, but I believe this will effectively prevent the approach to accessing tables in other databases that was described recently on [Zulip](https://backdrop.zulipchat.com/#narrow/channel/218635-Backdrop/topic/Give.20the.20new.20SSO.20module.20a.20try!/near/482827858), upon which the SSO module is based.

This approach is just dealing with the table alias.  I think the prefixing, whether for this or for other prefixing needs, happens with `{table_name}` which is handled before and doesn't cause a problem.

**Comment by yorkshire-pudding** [comment]
> It seems that the quoteIdentifier method (https://github.com/backdrop/backdrop/blob/1de8b35c21487d35c2fad341ea65300186e9cf9e/core/includes/database/mysql/database.inc#L174) is intended to handle this issue.
> 
> I can reproduce the issue using the steps in the original post.

I think in its current implementation it is only dealing with field aliases though perhaps extending the use would be the right way to go.

**Comment by herbdool** [comment]
We should also test CiviCRM's integration with Views. Not sure if it's affected.

**Comment by yorkshire-pudding** [comment]
@quicksketch 

The proposal you gave in the dev meeting does not work.

Adding:

```php

  /**
   * {@inheritdoc}
   */
  public function escapeTable($table) {
    $table = parent::escapeTable($table);
    return $this->quoteIdentifier($table);
  }
```

into `/core/includes/database/mysql/database.inc`

causes a fatal error:

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`` WHERE (`name` = 'variable_init') AND (`value` = '83354288567523507bf9c12.37' at line 1: DELETE FROM {`semaphore`} WHERE (`name` = :db_condition_placeholder_0) AND (`value` = :db_condition_placeholder_1) ; Array ( [:db_condition_placeholder_0] => variable_init [:db_condition_placeholder_1] => 83354288567523507bf9c12.37945228 )

Looking at how D11 does this, it uses `escapeAlias()` for escaping table aliases rather than what we have which is `escapeTable()` which I think should only be used for the actual table name not the table alias.  I've copied that approach and it works locally (with MySQL 8) and also passes the tests in the PR.

**Comment by stpaultim** [comment]
Here is a link directly to the discussion in last weeks meetings:
https://www.youtube.com/live/VRHIfFzfhn0?si=2qbIrRArMFu4ssiK&t=1285

**Comment by yorkshire-pudding** [comment]
@stpaultim @argiepiano @herbdool @kswan @indigoxela @quicksketch 
Anyone interested in testing and/or reviewing the revised PR?

**Comment by quicksketch** [comment]
@yorkshire-pudding Having looked at it with time to think, it looks almost obvious that we should be using `escapeAlias()` when dealing with aliases; makes total sense.

The PR includes one use of `escapeAlias()` on a table though, which seems like it should continue using `escapeTable()`. That is, aliases should be escaped with `escapeAlias()` and tables should be escaped with `escapeTable()`. Seems like that's the way it should be at least. Could you check this comment on the PR? https://github.com/backdrop/backdrop/pull/4918#pullrequestreview-2498388564

**Comment by yorkshire-pudding** [comment]
@quicksketch - I've responded on the PR at https://github.com/backdrop/backdrop/pull/4918/files#r1881681465

**Comment by quicksketch** [comment]
After today's dev meeting I pulled down this PR to code review it in the context of the whole database layer. In the end, I think the PR at https://github.com/backdrop/backdrop/pull/4918 is correct in its fix. There is some back and forth in this PR thread: https://github.com/backdrop/backdrop/pull/4918/files#r1881624704

Code-wise this looks good to me. The current fix does not affect table prefixing, so it shouldn't affect CiviCRM or the SSO module. Additional confirmation would be helpful to confirm though.

**Comment by herbdool** [comment]
I can test the prefixing with CiviCRM. Does it require MySQL or can it be done with MariaDB?

**Comment by quicksketch** [comment]
> Does it require MySQL or can it be done with MariaDB?

The queries are escaped the same in all versions, so confirming this doesn't break _existing_ functionality can be done in any version. If you have an existing site, just applying this fix as a patch would be perfect.

**Comment by herbdool** [comment]
I've tested this with CiviCRM and can confirm it does not break the Views integration (which relies on the prefixing). So thumbs-up there. Code looks good too and going by the comments sounds like @quicksketch is okay with code review.

@alanmels can you test your SSO module? It will be critical to getting this fix in.

**Comment by yorkshire-pudding** [comment]
@herbdool @alanmels @quicksketch @argiepiano 
I have tested this with the SSO module on Lando and it does not break it.  This is what my `$database` value in settings looks like for the subdomain (I don't have `realname` setup nor have I added firstname or lastname)

```php
$database = array(
  'database' => 'sub',
  'username' => 'backdrop',
  'password' => 'backdrop',
  'host' => 'database',
  'prefix' => array(
    'default' => '', // Local tables for this subdomain.
    'users' => 'backdrop.', // Shared user table.
    'sessions' => 'backdrop.', // Shared sessions table.
    'users_roles' => 'backdrop.', // Shared user roles table.
    // 'realname' => 'backdrop.', // Shared real name data.
    // 'field_data_field_first_name' => 'main_domain_db.', // Shared first name field.
    // 'field_revision_field_first_name' => 'main_domain_db.', // Shared first name field revisions.
    // 'field_data_field_last_name' => 'main_domain_db.', // Shared last name field.
    // 'field_revision_field_last_name' => 'main_domain_db.', // Shared last name field revisions.
  ),
);
```

PS - great work on the SSO module @alanmels - it works a treat

**Comment by alanmels** [comment]
@yorkshire-pudding, thank you for testing the new method! Could you please submit a PR to update the README with this information? Unfortunately, I don’t have the time to do it myself.

**Comment by quicksketch** [comment]
> I've tested this with CiviCRM and can confirm it does not break the Views integration (which relies on the prefixing). 

> I have tested this with the SSO module on Lando and it does not break it. 

Sounds like this is RTBC then!

**Comment by quicksketch** [comment]
Thank you @yorkshire-pudding, @herbdool, @kswan, and @stpaultim for taking the time to reproduce this issue! With the validations against various prefix-table setups, I feel confident about this fix. Extra thank you @yorkshire-pudding for trying all my ideas that didn't work. I really appreciate your patience!

I merged https://github.com/backdrop/backdrop/pull/4918 into 1.x and 1.29.x. Thank you everyone!
