### ISSUE TITLE
[UX] Add Filter Permissions module to core

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#5796]
## Description of the need

The permissions page is a bit of a mess in terms of UI, too many options make it very difficult to find specific permissions. We have a general ticket about improving the [UI of the permissions page](https://github.com/backdrop/backdrop-issues/issues/463), this specific ticket is for anyone who wants to advocate for this specific solution.

I haven't looked at all the options, but I've looked at the recently ported "Filter Permissions" module and feel like it's a pretty simple module that would be a huge improvement. 

I would assume that this kind of improvement could be made better later if people have other ideas. But, integrating this module into core could be a quick and easy UI win. 

## Proposed solution

Add Filter Permissions module to core.

![image](https://user-images.githubusercontent.com/3144571/192077529-09a1424d-6b86-4332-92d5-5cfe0ab2b8af.png)

## Alternatives that have been considered

See:
* https://github.com/backdrop/backdrop-issues/issues/463
* https://github.com/backdrop/backdrop-issues/issues/980

Personally, I'm open to other options. But, this one seems really good and would be pretty quick and easy to implement (I believe).

## Draft of feature description for Press Release (1 paragraph at most)

We've included the Filter Permissions module into core which is a dramatic improvement in the user interface for Backdrop CMS. The Filter Permissions module adds a Role and Module based filter to the top of the permissions page which helps a site administrator quickly find the particular permission that they are looking for.

**Comment by bugfolder** [comment]
I'll note that the [Role Listings](https://backdropcms.org/project/role_listings) module creates individual permissions pages for each role, accessed as tabs of the full Permissions page, so there is some overlap of functionality.

The two modules don't play nicely together, though. Installing both breaks the functionality of Role Listings; the tabbed sub-pages don't work any more.

**Comment by yorkshire-pudding** [comment]
@bugfolder - I wonder if that's because of https://github.com/backdrop-contrib/filter_perms/issues/2 ?

**Comment by bugfolder** [comment]
Yup. Version 1.0.2 of Filter Permissions fixes that problem; they're now playing nicely together and sharing the toys.

**Comment by bugfolder** [comment]
Well, mostly nicely. It looks like Filter Permissions changes the path, i.e., when you click the tab for admin/config/people/permissions/editor, you get redirected to admin/config/people/permissions with the Editor filter selected. So, not quite the same result, but the same functionality.

**Comment by yorkshire-pudding** [comment]
@bugfolder - I've tested Filter permissions without the bit that resets the url to `admin/config/people/permissions` and basically it stops the user from changing the filter once on the page.

**Comment by bugfolder** [comment]
I think it's OK with the redirect. The user still ends up seeing what they expected to see (with the addition of the filters), and while I can imagine scenarios where that could conceivably make a difference (e.g., URL-dependent block visibility), such scenarios seem rare, and there's only a small number of installations.

**Comment by klonos** [comment]
The filter that the module provides is kinda "bulky" and has the need-to-use-keyboard-to-multi-select issue, but we have the same UI paradigm in the dblog report page, where the filter section is collapsible within a fieldset. So I guess we're OK. Once we have a better alternative for the multi-select elements (#1800), this won't be an issue though.

**Comment by yorkshire-pudding** [comment]
I happened to come across this issue when looking for something else.  Given Filter Permissions now just fills a niche where `max_input_vars` is exceeded by the number of permissions, and core now fulfils the usability need, I think this should be closed.
