### ISSUE TITLE
Update wording on Password Reset screen

### ISSUE THREAD

**Issue by populist** [backdrop/backdrop-issues#580]
If you request a password for an existing user, you are redirected to the password reset form. This has a button to "Log In" which works fine, but it also shows the username/password fieldset which is confusing / unnecessary. To replicate just request a password.

**Comment by BWPanda** [comment]
There's a 'Log in' tab at `/user/password`, you get redirected to the main login form at `/user` once you fill in the `/user/password` form, and the reset link you get sent to your email (`/user/reset/[...]`) has a 'Log in' button (for use after entering a new password).

Could you please clarify which of these you're referring to?

**Comment by populist** [comment]
The situation I am referring to is at the /user/reset/[...] page where a user is presented with a "Log In" button that uses that one time login but is ALSO presented with textfields for username and password that are unnecessary:

![error screen](https://dl.dropboxusercontent.com/u/511275/Emailed/backdrop-error-reset.png)

**Comment by BWPanda** [comment]
If you'll notice, the two fields are both for passwords (no username field). This is so users can reset their password immediately and was changed to be like this in this issue: https://github.com/backdrop/backdrop-issues/issues/140

However, I do think this could be made nicer by re-wording the description on this page to make it describe the password reset feature and not the old one-time login functionality. Also, the 'Log in' button should probably be renamed to 'Reset'.

**Comment by populist** [comment]
Thanks for the clarification. I am so conditioned on login forms that I just assumed that is what it was :)

**Comment by docwilmot** [comment]
Suggested text (Remove all existing text from 'this is a... to ...only once):
"Please choose a new password to access your account."

And change button links to 'New Password' and 'Confirm New Password'.

I'm pretty sure if theyve got this far they intend to reset now, and dont need the expiry reminder. That can remain in the email.

**Comment by quicksketch** [comment]
Great suggestions! In summary:

- Remove all current text above the form. Replace with "Please choose a new password to access your account."
- Change labels on the password fields to "New password" and "Confirm new password" (note capitalization here, we inherited sentence casing for labels from Drupal).
- Change the "Log in" button. @BWPanda suggested "Reset", but I think "Save password" might be more clear. Either would be better than "Log in".

Anyone up for making a PR?

**Comment by quicksketch** [comment]
PR is failing (legit) currently. Probably tests need to be updated.

**Comment by BWPanda** [comment]
Thought they might... Will do.

**Comment by BWPanda** [comment]
Tests fixed with green light. Rebased and merged.

**Comment by quicksketch** [comment]
Thanks @BWPanda! This will be in 1.0.1, which we'll be doing this coming week.
