### ISSUE TITLE
GHA - our change does not work anymore after another change in the underlying system

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5803]
## Description of the bug

Sort of a follow-up to #5790...

Beginning with 2022-09-18 we experienced a problem with the php module for 5.6 being turned on - which broke our Apache setup in the php 5.6 runner.

NOW there's: `ERROR: Module php5.6 does not exist!`, which means they turned it off again.

Need to figure out a more robust way - probably check first, if the module in on.

Another option is to just drop that step again - but then it might fail again, if the module is on (for whatever reason). Annoying.

**Comment by indigoxela** [comment]
And a PR... again. :wink:

Check if mod_php is on (loaded) and only then turn it off. Not 100% sure if that would break again if they change something.

**Comment by quicksketch** [comment]
Thanks @indigoxela! Considering the importance of this issue and that it only affects testing I've merge this into 1.x and 1.23.x. :bow:
