### ISSUE TITLE
Add submitted showcase sites to My Profile page

### ISSUE THREAD

**Issue by albanycomputers** [backdrop/backdrop-issues#5804]
## Description of the need

Add the submitted showcase sites to the My Profile page for easy editing/amending/removing etc... You could also add a "comments" field where someone who authorises the site can give feedback if the submission needs more details or is unsuitable etc...

I submitted a site a few months ago (guessing, it was a while ago) which isn't showing on the Showcase page.

## Proposed solution

Block showing a list of nodes we can edit and see feedback.

**Comment by indigoxela** [comment]
> I submitted a site a few months ago (guessing, it was a while ago) which isn't showing on the Showcase page.

Hi @albanycomputers ... are you referring to backdropcms.org? Because in that case, this issue queue might be the right one: https://github.com/backdrop-ops/backdropcms.org/issues <- note the backdrop-ops

Unless I completely misunderstand and you propose to add a new feature to core... :wink:

**Comment by albanycomputers** [comment]
@indigoxela Yes, adding a feature to backdropcms.org ...  sorry :-)

**Comment by indigoxela** [comment]
Another hint - requests like that get done way faster if you ping someone in our Zulip chat. :wink:
