### ISSUE TITLE
Method DatabaseCondition::__toString() must return a string value

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5805]
This is the corresponding fix for a [Drupal 7 issue](https://www.drupal.org/node/3004215). Currently `DatabaseCondition::__toString()` returns NULL.

Official PHP documentation for __toString() magic method:

__toString() method must return a string, as otherwise a fatal E_RECOVERABLE_ERROR level error is emitted.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4216

**Comment by indigoxela** [comment]
@argiepiano many thanks for starting the crossport task!

Although I've no example to trigger the fatal (the D issue didn't provide one, either), it seems logical to return a string and only a string - just like the doc block states and the base class expects. RTBC! :+1:

**Comment by quicksketch** [comment]
Thanks @argiepiano and @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4216 into 1.x and 1.23.x.
