### ISSUE TITLE
Fixed: Table alias missing in query condition in `taxonomy_select_nodes()`.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5806]
This is the corresponding issue to Drupal's https://www.drupal.org/node/2574003

The function taxonomy_select_nodes() adds a condition to field tid of table taxonomy_index. Unfortunately the table alias is not added so if you alter the query (i.e. by implementing hook_query_node_access_alter()) and add your own condition with another tid, the query horribly fails: "Integrity constraint violation: 1052 Column 'tid' in where clause is ambiguous

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4217

**Comment by indigoxela** [comment]
We had a similar issue recently with an alterable query without an alias and an exception because of an ambiguous column. Similar situation here. RTBC! :+1:

**Comment by quicksketch** [comment]
Thanks @argiepiano and @indigoxela for working on these cross-ports! I merged https://github.com/backdrop/backdrop/pull/4217 into 1.x and 1.23.x.
