### ISSUE TITLE
Upgrade from Drupal 7 has no styles unless caches are manually cleared

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#581]
While testing the upgrade path from Drupal 7, I noticed that our styles don't show up until the caches have been cleared. Since the admin interface isn't accessible at the time of an upgrade and we don't have Drush support yet, there's no easy way to clear these caches.

**Comment by klonos** [comment]
It's not just upgrading from Drupal. I had this happen to me while upgrading from a git download from the 9th of Jan to one I downloaded on the 15th.
