### ISSUE TITLE
Fix SelectQuery::_clone() (D7 issue: "Complex cloned query dependent on __toString() call")

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5815]
This is the corresponding issue to D7's https://www.drupal.org/node/3000191

The clone operation for `SelectQuery` objects is done in incomplete fashion. The fix needs to make sure that subqueries stored in the `tables` property are also cloned properly, and also that the class parent's `__clone()` method is invoked.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4221

1. Patch `database_test.test` only (not `select.inc`)
2. Run the test `DatabaseSelectCloneTest`  - the new code in the test will fail (it tests that the cloning has been done correctly)
3. Patch `select.inc` and re-run the test. The test should now pass

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/4221 looks great and included test coverage proves the fix. I merged it into 1.x and 1.23.x. Thanks @argiepiano!
