### ISSUE TITLE
Creation of database during installation fails

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5816]
## Description of the bug

When you install Backdrop without previously creating a database, Backdrop tries creating it for you in `DatabaseConnection_mysql::createDatabase()`. A bug in this method results in a fatal error:

`Error: Call to undefined method DatabaseConnection_mysql::exec() in DatabaseConnection_mysql->createDatabase() (line 217 of /Users/XXX/Sites/localhost/panettone/core/includes/database/mysql/database.inc).`

## Steps To Reproduce
1. Do a clean install WITHOUT manually creating a database previously 
2. Enter the name of the (new) database, database username and database password in the second step 
3. See the error appear

## Actual behavior
Fatal error when trying to create the database.

## Expected behavior
Backdrop should create the database.

## Additional information
Backdrop 1.23.0
PHP  7.4.21
MySQL, MariaDB, or equivalent version 5.7.34

This was first reported in the [Forum](https://forum.backdropcms.org/forum/call-undefined-method-databaseconnection)

The `DatabaseConnection_mysql::createDatabase()` method contains calls to the method `exec()` which doesn't exist. I believe this should be `$this->pdo-exec()`. Changing this still produces a non-fatal Backdrop error message  about a test table not having been created, but the database is actually created just fine, and the installation process can be continued by submitting the form again.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4223

As I mentioned above, this fix still produces a non-fatal error (not PHP, but rather one generated by `backdrop_set_message()`. The error says that a test table could not be created. HOWEVER, the database is created just fine, and the installation procedure continues if you submit the form again.  I will open a separate issue for this.

**Comment by argiepiano** [comment]
I have created #5817 that addresses the second error I reported above. This second error happens after the PR here is applied (which solves the problem reported in this issue). This second error was "masked" by the fact that Backdrop was unable to create a new database upon installation until this PR.

**Comment by indigoxela** [comment]
This looks like an oversight in Issue #4772 (Initial PHP 8 support).
Letting Backdrop create the database is rather an edge case (on real hosting the (unprivileged) db user won't have the permission to do so), so maybe that's why nobody reported that error before.

Switching to `$this->pdo->exec` is correct. :+1:

**Comment by argiepiano** [comment]
Once this is reviewed and slated for merging, please do take a look at a related bug that appears once this is fixed: #5817

**Comment by klonos** [comment]
Sorry this has taken us so long to review @argiepiano ...RTBC 👍🏼

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4223 into 1.x and 1.23.x. Thanks @argiepiano, @klonos, and @indigoxela!
