### ISSUE TITLE
Creation of table `backdrop_install_test` fails upon installation without a pre-created database 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5817]
## Description of the bug

This bug only appears after a fatal error reported in #5816 is fixed.

When installing Backdrop without having manually created a database prior to installation, the process first throws a `backdrop_set_message()` error. This happens despite the fact that the username and password ARE correct.

```
Failed to CREATE a test table on your database server with the command CREATE TABLE {backdrop_install_test} (id int NULL). The server reports the following message: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected.
```
<img width="782" alt="Screen Shot 2022-10-02 at 4 56 01 PM" src="https://user-images.githubusercontent.com/9938978/193480015-96642039-10d5-41c2-93f0-8d91052da8e5.png">

The installation proceeds normally if you submit the Database configuration form one more time.

## Steps To Reproduce
1. Patch Backdrop using #5816 
2. Install Backdrop on a completely clean install (do not edit settings.php) without manually creating a database before the installation
3. On the Database configuration screen enter the name of the NEW database, databse username and password
4. See error appear

## Actual behavior
Backdrop shows a soft error. Database is created normally but the test table is not.
 
## Expected behavior
Error should not happen. The test table should be created normally.

## Additional information

Add any other information that could help, such as:
Backdrop 1.23.0
PHP 7.4.21
MySQL, MariaDB, or equivalent version 5.7.34

**Comment by argiepiano** [comment]
After some digging, this error is produced because, after creating a new database, Backdrop doesn't create a connection to the new DB. PR coming.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4224

The PR adds code to `DatabaseTasks::connect()` that calls itself after creating the new database. The old code in that method called `Database::getConnection()` which was chained to `createDatabase($database)`. The problem with that old code is that the creation of the database happened AFTER `getConnection()`, and therefore no real connection happened then (there was no database). So this codes removes that incomplete connections, and calls the method `connect()` again.  If the creation of the database throws an exception, that self-call doesn't happen - instead the error is reported normally. 

I'm not 100% sure this is the best way, but I tried several other options without success. Apparently the sql command `USE $database` in `DatabaseConnection_mysql::createDatabase()` is not enough to secure a successful connection to the newly created DB.

To test
-----
1. Apply patch #5816 
2. Start a FRESH installation **without** manually creating a database
3. Enter the database name, database username and password in the Database configuration form
4. Watch the error reported here
5. Then, apply the patch in this issue (https://github.com/backdrop/backdrop/pull/4224)
6. Remove the database complete, replace settings.php with the one provided by the codebase, and remove everything in `files`
7. Run the installation again, enter the database, username and password again as above
8. See the installation proceed normally

**Comment by klonos** [comment]
@argiepiano thanks for the detailed description and testing steps. I am yet to review/test, but can you please add some inline comments to explain why we are removing the connection and then re-connecting? It would help when people go through that part of the code in the future, and avoid head scratching.

**Comment by argiepiano** [comment]
Sure, I'll add some comments to the code.

The method name is a bit confusing. `DatabaseTasks::connect()` is in fact a method that **tests** that a connection can be established. This method is run as the first tasks that are run prior to making a connection (other tasks include testing whether we can `INSERT` etc into the database). 

The creation of the new database is triggered when `DatabaseTasks::connect()` fails for the first time with the code "Database not found". So, the method proceeds to creating a database. After creating that database, we must test if a connection is possible again, by calling `DatabaseTasks::connect()`. If this second call passes, then the rest of the tasks are run.

**Comment by klonos** [comment]
> The method name is a bit confusing. `DatabaseTasks::connect()` is in fact a method that **tests** that a connection can be established.

This is actually a perfect explanation 🙂 ...I saw the comment you've added, and it now makes sense when I read it (from the point of you of someone reading that code for the first time). Great job 👍🏼

**Comment by quicksketch** [comment]
Thanks for the great explanation and testing steps @argiepiano. After merging https://github.com/backdrop/backdrop-issues/issues/5816, I confirmed this PR also works as described. I merged https://github.com/backdrop/backdrop/pull/4224 into 1.x and 1.23.x. Thanks!
