### ISSUE TITLE
Upgrade from Drupal 7 should respect UTF8-MB4 variable

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5818]
## Description of the bug

Backdrop includes a built-in migration tool to convert old databases to use UTF8-MB4 (to support emojis and Asian character sets). This tool is based on the Drupal 7 project: https://www.drupal.org/project/utf8mb4_convert

That project when run on a D7 site, sets a variable named `drupal_all_databases_are_utf8mb4`. We should respect that variable on upgrades from Drupal 7 and set our matching `state` variable to match: `database_utf8mb4_active`.

## Steps To Reproduce

To reproduce the behavior:
1. Install a Drupal 7 site with UTF8-MB4 disabled by default.
2. Run the drush command to convert tables to UTF8-MB4: https://www.drupal.org/project/utf8mb4_convert

OR

1. Install a Drupal 7 site with UTF8-MB4 installed by default.
2. No need to run the drush command.
3. Point Backdrop at the D7 site.
4. Run core/update.php

## Actual behavior

5. The Backdrop site after upgrading will show a notice that the UTF8-MB4 upgrade needs to be performed, even if all tables are already converted.

## Expected behavior

5. Backdrop should not throw a status report warning that the UTF8-MB4 upgrade needs to be run.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.23.0

**Comment by quicksketch** [comment]
Note there is a separate problem that if a Drupal 7 site was installed with UTF8-MB4 initially, there is no variable at all that we can use to detect if the previous database was the right format to begin with. Drupal 7 built its assumption about whether the database has been converted entirely on the `charset` property of the database connection array in settings.php. If that is set to `utf8mb4`, then Drupal 7 assumes all tables are already the right format.

I'm not sure what to do about that, but at least for sites that used the upgrade tool, we can detect the variable and respect it.

**Comment by quicksketch** [comment]
> there is no variable at all that we can use to detect if the previous database was the right format to begin with.

I'm incorrect. Drupal 7 sets the `drupal_all_databases_are_utf8mb4` variable in `install_system_module()` on new installs, so that one variable should work both for new D7 sites and upgraded ones.

I filed a PR at https://github.com/backdrop/backdrop/pull/4226 that checks for this value and preserves it in the Backdrop equivalent.

**Comment by argiepiano** [comment]
I've tested as follow:

1. Installed from scratch a new D7 site that natively supports UTF-MB4 (by adding `  'charset' => 'utf8mb4',` and 
  `'collation' => 'utf8mb4_general_ci'` to `settings.php`)
2. Upgraded to Backdrop. Backdrop showed a warning that the database needed to be converted (basically the issue reported here)

Then I patched Backdrop with this PR and run the above again. Worked without glitches! WFM

One thing that tripped me at first is that Backdrop's additional `$database_charset = 'utf8mb4';` that I was supposed to add is not documented (as a commented block) in `settings.php`. I had to go to [this page](https://docs.backdropcms.org/documentation/database-configuration#utf8mb4) to learn about that feature (I had never installed Backdrop with UTFMB4 support before). I think it'd be a good idea to document that feature in `settings.php`.

**Comment by laryn** [comment]
> I think it'd be a good idea to document that feature in settings.php.

@argiepiano Have you filed a follow up? I can do it if not.

**Comment by argiepiano** [comment]
> @argiepiano Have you filed a follow up? I can do it if not.

Yes. #5819

**Comment by quicksketch** [comment]
Thanks @argiepiano for reviewing! Merged https://github.com/backdrop/backdrop/pull/4226 into 1.x and 1.23.x.
