### ISSUE TITLE
Typo in redirect module: it's "update", not "upadte"

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5826]
## Description of the bug

At `admin/config/urls/redirect/settings`, there's a typo: "upadte", see here.

![typo](https://user-images.githubusercontent.com/29214084/195489820-6907488b-4935-4111-bf01-e57913c393cf.jpg)

In fact, correcting the typo to get "URL alias update action" isn't correct either, because the section title on `admin/config/urls/path/patterns/settings` is just "Update action":

![update_action](https://user-images.githubusercontent.com/29214084/195489881-191c9258-6b8b-4449-b0f6-8dfe183a7a8c.jpg)

So the text ought to be `This setting is most commonly used when replacing existing URL aliases under "Update action" in the URL alias settings.`

**Comment by kiamlaluno** [comment]
The change to line 378 isn't necessary to fix what reported here. Otherwise, the PR looks good to me.

**Comment by bugfolder** [comment]
> The change to line 378 isn't necessary to fix what reported here. Otherwise, the PR looks good to me.

That change is necessary to get the tests to pass now that we have PHPCS automatic testing.

**Comment by bugfolder** [comment]
BTW, thx for code review. I guess it still needs testing (sorry for the missing label).

**Comment by kiamlaluno** [comment]
Right, it's the changed file that is checked with `phpcs`.

I checked the preview created for the PR. It fixes the typo as expected. The used sentence is correct, IMO.

![screenshot](https://user-images.githubusercontent.com/29851/206921721-ab8cf1d5-2023-4e49-8c2a-1061b2a6fb20.png)

**Comment by bugfolder** [comment]
Thanks! Removing the "needs testing" label (since you've tested it) and adding RTBC.

**Comment by klonos** [comment]
I've added the `milestone candidate - bug` label. Can someone else please remove it and add the actual milestone?

**Comment by quicksketch** [comment]
Thanks folks! Sorry this took so long to get merged. https://github.com/backdrop/backdrop/pull/4246 merged into 1.x and 1.23.x.
