### ISSUE TITLE
Remove `$settings` from docblock for `hook_block_view_MODULE_DELTA_alter()` 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5827]
## Description of the bug

The documentation block for `hook_block_view_MODULE_DELTA_alter` still contains the parameter `$settings`, even though that parameter was removed in #2713.  Also the documentation for the `$block` parameter should include the `setting` property, as documented in `hook_block_view_alter()`.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4231

**Comment by indigoxela** [comment]
@argiepiano many thanks for your PR - I've left a tiny suggestion.

**Comment by indigoxela** [comment]
This looks great now, RTBC! (There's nothing to test.)

**Comment by quicksketch** [comment]
Thanks! Merged into 1.x and 1.23.x!
