### ISSUE TITLE
Use the testing profile for `CommentViewsHandlerArgumentUserUidTest`.

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5839]
## Description of the task

Spin off from #5799, which gets fixed in a more generic way.

However, we still want to switch to the testing profile, which is the preferred one for Simpletest.

**Comment by BWPanda** [comment]
@klonos gave a thumbs-up in the PR, and it looks good to me too. So RTBC.

**Comment by klonos** [comment]
@indigoxela there's a minor nitpick for an inline comment that you can marge if you agree. Alternatively, @BWPanda (or any of our other @backdrop/core-committers) perhaps you can merge the suggestion when you merge the PR.

**Comment by indigoxela** [comment]
@klonos sure, no problem - was about time for a rebase, anyway. Comment updated. :+1:

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/4219 into 1.x and 1.24.x.
