### ISSUE TITLE
Taxonomy term weights not saving

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#584]
admin/structure/taxonomy/tags for example. Create a few terms and try and save the order. It doesnt save in the chosen order.

**Comment by quicksketch** [comment]
Confirmed. You can edit the individual term and set its weight manually, so this is a problem with the drag and drop saving form, not the weights themselves.

**Comment by quicksketch** [comment]
And it looks like disabling the drag and drop and using the weight field in that form works also.

**Comment by jenlampton** [comment]
I was able to create a vocabulary called "Categories", add terms, and change the order of the terms (including intending) without a problem.

I think the issue you were facing may have been that you were trying to add order to a free-tagging vocabulary, and there is no order or weight to tags.

**Comment by jenlampton** [comment]
I have noticed a consistent behavior.  The terms seem to rotate one place with every save of the form:
```
1,3,2
3,2,1
2,1,3
1,3,2
3,2,1
```

**Comment by jenlampton** [comment]
Removing the line ``backdrop_sort($form_state['values']);`` keeps the terms in the same place on every submit of the form
