### ISSUE TITLE
Odd code in function url_stat() in stream_wrappers.inc

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5840]
## Description of the bug

When running bee cron with error reporting fully turned on in php 8.1, one always sees two warnings:

```
stat(): stat failed for /tmp/update-cache-XXXXX
...core/includes/stream_wrappers.inc:841

stat(): stat failed for /tmp/update-extraction-XXXXX
...core/includes/stream_wrappers.inc:841
```

It's caused by:

```php
  public function url_stat($uri, $flags) {
    $this->uri = $uri;
    $path = $this->getLocalPath();
    // Suppress warnings if requested or if the file or directory does not
    // exist. This is consistent with PHP's plain filesystem stream wrapper.
    if ($flags & STREAM_URL_STAT_QUIET || !file_exists($path)) {
      return @stat($path);
    }
    else {
      return stat($path);
    }
  }
```

This code is ancient, inherited from D7. Sure, currently only pops up with bee (with its own error handler), and with error reporting fully turned on in php.ini file, but it's really odd code.

Why I find it odd?

`!file_exists($path))` ... -> `@stat($path);`

So, when we _know_ that the file _does not exist_, we run a stat() on it and try to suppress the error? Seriously? :stuck_out_tongue_winking_eye: 

This is either so nifty coding that I simply don't get it, or it's something to fix. I thought I'd better ask if someone else also thinks, this is something that should get fixed. :grin:

**Comment by argiepiano** [comment]
> So, when we know that the file does not exist, we run a stat() on it and try to suppress the error? Seriously? 

Here's a guess of why `stat()` is being called on a non-existent file. According to a comment in [the documentation](https://www.php.net/manual/en/language.operators.errorcontrol.php) the use of `@` on an error-generating expression results in the error handler still being called, but with an error reporting level of "0" (NB: in PHP version pre-8.0.0). So my guess is that the idea behind this code was to still call the error handler, rather than completely ignoring the fact that the file did not exist.

**Comment by indigoxela** [comment]
Interesting... So maybe it's the installer module, that does it wrong when attempting to clear the stalled directories on cron runs?

**Comment by quicksketch** [comment]
@argiepiano's guess is a good one. And if that's the case, then it's actually doing what it's supposed to: giving you a warning when `stat()` is run on a non-existent file. I think the correct fix would be to find where that file check is being performed and first check if the file exists; and installer module looks like it's the likely culprit.

**Comment by indigoxela** [comment]
> I think the correct fix would be to find where that file check is being performed and first check if the file exists

I'm not sure if we can fix it that way. In function installer_clear_update_disk_cache() even the use of `file_exists` triggers the warning (again: only on php 8.1 and only when error_reporting is on).

**Comment by klonos** [comment]
I would like us to expand the existing inline comments in that portion of the code, so that next time others don't have to wonder why things are done the (odd) way that they are being done. At the very least, we could add a link pointing to this discussion here.
