### ISSUE TITLE
Fixed: HTML5 date field widget produces a fatal error on a Paragraph.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5847]
## Description of the bug

When a date field is attached to a Paragraph and the field uses the new HTML5 date widget, saving the node throws a fatal error `EntityStorageException: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1 of NodeStorageController->save() (line 510 of XXX/modules/node/node.entity.inc)`.

## Steps To Reproduce

1. Create a Paragraph type and attach a date field that uses the HTML5 widget
2. Add a paragraph reference field to a node type (unlimited cardinality) that references the new Paragraph type
3. Add a node of that note type, and enter a value for the date field
4. Save the node and see the fatal error

## Actual behavior

Fatal error.

## Expected behavior

The node should be saved with all its values, including the date field.

## Additional information

- Backdrop CMS version: 1.23.0

This was first reported in the [Paragraph issue queue](https://github.com/backdrop-contrib/paragraphs/issues/148).

The issue happens because of how `date_html5_element_validate()` handles the submitted form values. This validation function takes care of transforming the HTML5 date widget submitted values into a structure that can be saved to the date field table. But the problem is that this function assumes the values for the field are stored in `$form_state['values'][FIELD_NAME][LANGUAGE_NONE]`.

Unfortunately, this is not the case when the date is attached to another entity referenced by a field in the node (like the Paragraph Item entity referenced by a paragraph reference field). I expect this will also fail with other types of referenced entities that attach their forms to node forms, such as Field Collection entities.

The solution is to avoid hard-coding the location of the values. PR coming.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4248

Instead of getting and setting form values hard-coding from `$form_state['values'][FIELD_NAME]['und'], this PR uses `backdrop_array_get_nested_value()` and `backdrop_array_set_nested_value()`, which are supposed to be used to get and set form values when we don't know the depth or location of those values within the array. This used also in other `validate` functions, even within the `date` module itself.

**Comment by indigoxela** [comment]
@argiepiano many thanks for providing this PR.

I confirmed the problem (with paragraphs) and can also confirm that the PR fixes this nasty little bug. Works for me! :+1:

**Comment by indigoxela** [comment]
I gave it a final review and testing: yes, backdrop_array_g/set_nested_value() is the right way to do this. RTBC! :+1:

**Comment by quicksketch** [comment]
Merged into 1.x and 1.23.x. Thanks @argiepiano, @indigoxela, and @robertgarrigos!
