### ISSUE TITLE
Flexible template: PHP 8 issue on export (System language not English)

### ISSUE THREAD

**Issue by djzwerg** [backdrop/backdrop-issues#5853]
## Description of the bug

When I'm going to export my layout the following error occurs:
`natsort(): Argument #1 ($array) must be of type array, null given`

## Steps to reproduce:

1. Enable the language and Locale modules, add a language
2. Translate the string "Flexible layout templates" on /admin/config/regional/translate/translate
3. enable error display
4. create own flexible template on /admin/structure/layouts/settings/flexible-template/add
5. make sure you switch to the other language path
6. try to export, following the dropbutton menu link on /admin/structure/layouts/settings

Backdrop error logs:

> TypeError: natsort(): Argument #1 ($array) must be of type array, null given in natsort() (line 313 of /mypath/core/modules/config/config.admin.inc).

> Warning: Undefined array key "Flexible layout templates" in config_export_single_form() (line 312 of /mypath/core/modules/config/config.admin.inc).

Edit:
> Warning: Trying to access array offset on value of type null in field_config_label_instance() (line 436 of /mypath/core/modules/field/field.module).
(3 times)

This one belongs to the comment module. It has been gone when the module is enabled.

([previously posted on https://github.com/backdrop-contrib/flexible_layout/issues/8](https://github.com/backdrop-contrib/flexible_template/issues/2))

## Actual behavior

You'll get the error message `natsort(): Argument #1 ($array) must be of type array, null given`.

## Expected behavior

The export would work.

## Additional information

Backdrop core version: 1.23.0
Database version: MySQL 8.0.30
PHP version: 8.0.25

For now I think this is an issue with the PHP version. Using PHP 7.4 the export feature works.

**Comment by indigoxela** [comment]
@djzwerg I can't reproduce the problem without the flexible_template module. But I also can't reproduce it with that module enabled.

I'm also not sure what that contrib module is for. Flexible layouts are in core - why a module?

I tried your steps with PHP 8.1, but see no warnings in dblog.

**Comment by djzwerg** [comment]
@indigoxela I can reproduce the problem without the contrib module, too:

1. fresh Backdrop installation (without changes)
2. set language to German
3. add flexible template 'test'
4. try to export the flexible layout

The error still occurs.

## Additional information

Backdrop core version: 1.23.0
Database version: MySQL 8.0.30
PHP version: 8.0.25

**Comment by djzwerg** [comment]
As I see the issue won't be there if you use the standard English installation. But if you change the language to German it happens.

**Comment by indigoxela** [comment]
> I can reproduce the problem without the contrib module, too

Interesting, I still can't. Language and Locale module are enabled. Switched to German (/de), the export still works just fine and nothing shows up in dblog. So it doesn't seem to caused by the language.

It might have to do with your template... :thinking: Wait... do you have the comment module enabled or uninstalled? The third PHP warning is caused by that (see  #5469).

Now for the two remaining:
```
Warning: Undefined array key "Flexible layout templates" in config_export_single_form()
```
This seems very odd. You DO have the "Flexible layout templates" as option in your dropdown list, right? Otherwise you couldn't export it. The export per se works? Is some json displayed in the export area?

**Comment by djzwerg** [comment]
Within the fresh installation comment module is enabled. The former report based on a site with disabled comment module.

There is no json available:
![grafik](https://user-images.githubusercontent.com/49948628/199728455-b3f993a9-45e3-4a33-92b6-c8598a514239.png)

Themes are Basis (frontend) and Seven (backend).

**Comment by djzwerg** [comment]
I can confirm that the third error log has been gone with comment module enabled.

**Comment by indigoxela** [comment]
Did you already try a different path? Instead of starting on the layout overview, go to /admin/config/development/configuration/single/export

And check for the items in the dropdown list for a single export - is "Flexible layout templates" available there or not?

**Comment by indigoxela** [comment]
Wait... a suspicion: I just overwrote the url and that way I can reproduce the problem. But only if I set the URL to something non-existent.

Can you post the exact URL, when getting the error?

**Comment by indigoxela** [comment]
And to (eventually) confirm: go to /admin/config/regional/translate/translate and search for a translated string "Flexible layout templates". And if you delete that translation - does the export work again?

**Comment by djzwerg** [comment]
@indigoxela yes that solves that issue 🪄

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4251) is available for testing and review.

Additionally to translating the string "on both sides" it also tries to catch errors, if the url param is not found in the select list for whatever reasons. A value that comes in with $_GET is never fully reliable.

**Comment by argiepiano** [comment]
Since there was so much back and forth, could @djzwerg update the steps to reproduce this problem? That will help test.

**Comment by indigoxela** [comment]
@argiepiano I updated the steps, hopefully they're complete now to reproduce.

**Comment by djzwerg** [comment]
> @indigoxela I can reproduce the problem without the contrib module, too:
> 
> 1. fresh Backdrop installation (without changes)
> 2. set language to German
> 3. add flexible template 'test'
> 4. try to export the flexible layout
> 
> The error still occurs.
> 
> ## Additional information
> 
> Backdrop core version: 1.23.0
> Database version: MySQL 8.0.30
> PHP version: 8.0.25

@argiepiano this is the way to reproduce. I don't know whether it makes a difference to install Backdrop with the German language pack. I can check the PR later.

**Comment by djzwerg** [comment]
@indigoxela the PR solves this issue. Thanks a lot!

**Comment by argiepiano** [comment]
I've tried both direction sets and am still unable to reproduce the problem. I'm working with Spanish, where the phrase "Flexible layout template" is not translated in the translation file. I can't translate it manually  through the UI until Backdrop actually encounters that phrase in the UI, so the only way to do this is to create the flexible template in English first, go to the Export screen and then manually translate it to Spanish after the phrase appears in the translation form. Then export the layout...  no issues whatsoever. 

I'll just let someone with better luck (and someone who reads German, where perhaps the problem exists) try testing this.

**Comment by argiepiano** [comment]
I've tried both sets of direction and am still unable to reproduce the problem. I'm working with Spanish, where the phrase "Flexible layout template" is not translated in the translation file. I can't translate it manually  through the UI until Backdrop actually encounters that phrase in the UI, so the only way to do this is to create the flexible template in English first, go to the Export screen and then manually translate it to Spanish after the phrase appears in the translation form. Then export the layout...  no issues whatsoever. 

I also tried manually adding the phrase to the `.po` Spanish file and reinstalling the site by selecting Spanish in the installation interface, then follow these directions. Still no joy. 

I'll just let someone with better luck (and someone who reads German, where perhaps the problem exists) try testing this.

**Comment by indigoxela** [comment]
> Then visit the Spanish page to export the layout

Maybe that's the culprit? You should try to export the template, not the layout, so starting from /es/admin/structure/layouts/settings and use the "export" link from the dropdown button of your template.

You should end up with an url like `/es/admin/config/development/configuration/single/export?group=Flexible layout templates&name=layout.flexible.WHATEVER`. Note the group= param.
And also: if on PHP versions before 8 this won't be a fatal error, so make sure that the error display is on.
Alternative: override the group= GET param manually.

**Comment by argiepiano** [comment]
> PHP versions before 8 this won't be a fatal error  

Doh!!!! 🤦🏽  Stupid mistake - I was trying with 7.4. I'll try again later.

**Comment by argiepiano** [comment]
OK, tested in php 8. WFM!

**Comment by quicksketch** [comment]
Thanks @indigoxela, @djzwerg, and @argiepiano! I merged https://github.com/backdrop/backdrop/pull/4251 into 1.x and 1.23.x. This will be in 1.23.1.
