### ISSUE TITLE
Fixed: Views query/distinct settings issues when setting "This page (override)" in PHP8.

### ISSUE THREAD

**Issue by djzwerg** [backdrop/backdrop-issues#5854]
## Description of the bug

Using PHP 8 it is not possible to set query/distinct settings. Error log shows: 
`location: https://mydomain.tld/admin/structure/views/ajax/display/myview/page/query`
`TypeError: explode(): Argument #2 ($string) must be of type string, array given in explode() (line 292 of /mypath/core/modules/views/plugins/views_plugin_query_default.inc).`

## Steps To Reproduce

To reproduce the behavior:
1. Go to /admin/structure/views/
2. Add a view of your choice
3. Go to advanced settings -> query settings
4. Enable distinct (or pure distinct)
5. Click on save button.

## Actual behavior

The modal reloads.

## Expected behavior

Views detects the settings and you are able to save the view.

## Additional information

- Backdrop CMS version: 1.23.0
- MySQL version: 8.0.30
- PHP version: 8.1.12

**Comment by indigoxela** [comment]
@djzwerg I'm unable to reproduce, so please provide the missing steps to do so.

I can also see, you're using MySQL 8, so that might to play a role, too.

The first thing to try: spin up a vanilla Backdrop and try to reproduce the problem with a minimal setup. The please paste your exported view (json) here.

**Comment by djzwerg** [comment]
@indigoxela thanks for your replay. I will check that with a Vanilla setup.

For now I found out that it works with PHP7.4 and MySQL 8 but Not with PHP8+.

**Comment by djzwerg** [comment]
@indigoxela @argiepiano 
I've tried again with following results:

- PHP 7.4/MySQL 8: it works
- PHP 8.0/MySQL 8: it works not
- PHP 8.1/MySQL 8: it works not

This is my view:
`{
    "_config_name": "views.view.test",
    "name": "test",
    "description": "",
    "tag": "default",
    "disabled": false,
    "base_table": "node",
    "human_name": "test",
    "core": "1.23.0",
    "display": {
        "default": {
            "display_title": "Master",
            "display_plugin": "default",
            "display_options": {
                "query": {
                    "type": "views_query",
                    "options": []
                },
                "access": {
                    "type": "perm",
                    "perm": "access content"
                },
                "cache": {
                    "type": "none"
                },
                "exposed_form": {
                    "type": "basic"
                },
                "pager": {
                    "type": "full",
                    "options": {
                        "items_per_page": "10"
                    }
                },
                "style_plugin": "default",
                "row_plugin": "fields",
                "fields": {
                    "title": {
                        "id": "title",
                        "table": "node",
                        "field": "title",
                        "label": "",
                        "alter": {
                            "alter_text": 0,
                            "make_link": 0,
                            "absolute": 0,
                            "trim": 0,
                            "word_boundary": 0,
                            "ellipsis": 0,
                            "strip_tags": 0,
                            "html": 0
                        },
                        "hide_empty": 0,
                        "empty_zero": 0,
                        "link_to_node": 1
                    }
                },
                "filters": {
                    "status": {
                        "value": 1,
                        "table": "node",
                        "field": "status",
                        "id": "status",
                        "expose": {
                            "operator": false
                        },
                        "group": 1
                    }
                },
                "sorts": {
                    "created": {
                        "id": "created",
                        "table": "node",
                        "field": "created",
                        "order": "DESC"
                    }
                },
                "title": "test"
            }
        },
        "page": {
            "display_title": "Page",
            "display_plugin": "page",
            "display_options": {
                "query": {
                    "type": "views_query",
                    "options": []
                },
                "path": "test"
            }
        }
    }
}`

**Comment by argiepiano** [comment]
Thanks for posting the export of the views. Still not able to reproduce (but I don't have access to MySQL 8).

Can you also clarify what you mean by "does not work"? Above you said that when you pressed Save the modal reloaded. Did you mean when you press "Apply" in the modal form? Or "Save" for the whole view?

<img width="1205" alt="Screen Shot 2022-11-07 at 2 21 53 PM" src="https://user-images.githubusercontent.com/9938978/200418166-7736d566-f115-439e-9cce-3c61f8067983.png">

**Comment by djzwerg** [comment]
I'm sorry. I mean when I press apply the modal reloads and does not accept the enabled distinct. When I save the view distinction is disabled.

**Comment by indigoxela** [comment]
> when I press apply the modal reloads and does not accept the enabled distinct.

@djzwerg Very strange... Nothing in dblog, no error? Do you have error display turned on?

I can't reproduce it either, but I have 10.5.15-MariaDB and PHP 8.1.

The resulting query after applying:
```
SELECT DISTINCT node.`title` AS `node_title`, node.`nid` AS `nid`, node.`created` AS `node_created`
FROM 
{node} node
WHERE (( (`node`.`status` = '1') ))
ORDER BY node_created DESC
LIMIT 10 OFFSET 0
```
I don't see anything problematic.

**Comment by djzwerg** [comment]
> > when I press apply the modal reloads and does not accept the enabled distinct.
> 
> @djzwerg Very strange... Nothing in dblog, no error? Do you have error display turned on?
> 
> I can't reproduce it either, but I have 10.5.15-MariaDB and PHP 8.1.
> 
> The resulting query after applying:
> ```
> SELECT DISTINCT node.`title` AS `node_title`, node.`nid` AS `nid`, node.`created` AS `node_created`
> FROM 
> {node} node
> WHERE (( (`node`.`status` = '1') ))
> ORDER BY node_created DESC
> LIMIT 10 OFFSET 0
> ```
> I don't see anything problematic.
> 

Only this in the error log report:
`location: https://mydomain.tld/admin/structure/views/ajax/display/myview/page/query`
`TypeError: explode(): Argument #2 ($string) must be of type string, array given in explode() (line 292 of /mypath/core/modules/views/plugins/views_plugin_query_default.inc).`

**Comment by indigoxela** [comment]
Looking at that line... backdrop_array_get_nested_value() returns an array. But only on MySQL8 + PHP 8?

@djzwerg do you have direct access to that testing web? Could you "hack core" (is it just a playground)?

In that case, in file core/modules/views/plugins/views_plugin_query_default.inc, function options_submit:
```
  /**
   * Special submit handling.
   */
  function options_submit(&$form, &$form_state) {
    $element = array('#parents' => array('query', 'options', 'query_tags'));
    $foo = backdrop_array_get_nested_value($form_state['values'], $element['#parents']);
    debug($foo);
    $value = explode(',', backdrop_array_get_nested_value($form_state['values'], $element['#parents']));
    $value = array_filter(array_map('trim', $value));
    form_set_value($element, $value, $form_state);
  }
```
As it's a submission handler, the info won't get displayed directly, but only show up in dblog.

For me that "$foo" is an empty string, I wonder what it is with MySQL8/PHP8.

**Comment by djzwerg** [comment]
@indigoxela I will try this later 👍🏻

**Comment by indigoxela** [comment]
@djzwerg that's great!

In the meantime:

Out of curiosity I spun up a small VM with php8 + mysql8, imported the view, set Distinct and Pure distinct in the dialog ... and it saved without any problems. The query also worked - using DISTINCT. Opening the dialog again - the settings are still there.

Whatever causes the problem on your site - it's something else. With a vanilla Backdrop there's no problem.

The next thing to check on your site: what's different from a vanilla install. Which modules are installed, which core settings...
I'm afraid, I won't be able to help much, only you can figure out what's the source of the problem, as so far nobody's able to reproduce it.

**Comment by argiepiano** [comment]
One additional clue here: My Intelephense code analyzer is underlining that line, pointing that the return for `backdrop_array_get_nested_value()` is either array or null - when in fact it's returning a string in this case. This may cause problems with `explode,`, but is not causing problems with my installation of PHP 8.1. Is there a chance that your installation of PHP 8.1 has a setting that makes this type checking super strict, and is therefore throwing an error?

**Comment by djzwerg** [comment]
Today I made a few checks and found out that it works if you're going to use distinct to all displays but not for the current view. So there is a missing step to reproduce:
To reproduce the behavior:

1. Go to /admin/structure/views/
2. Add a view of your choice
3. Go to advanced settings -> query settings
**4. Switch from "All displays" to the current view**
5. Enable distinct (or pure distinct)
6. Click on save button.

So please try to reproduce again.

**Comment by argiepiano** [comment]
I'm now able to reproduce the problem! That's progress.

I'll be checking to see if I can find out what's going in later tonight.

**Comment by djzwerg** [comment]
> $foo = backdrop_array_get_nested_value($form_state['values'], $element['#parents']);
>     debug($foo);

After adding these lines the error log shows this:
`User notice:

''

in views_plugin_query_default->options_submit() (line 293 of /mypathtobackdrop/core/modules/views/plugins/views_plugin_query_default.inc).`

and

`User notice:

array (
)

in views_plugin_query_default->options_submit() (line 293 of /mypathtobackdrop/core/modules/views/plugins/views_plugin_query_default.inc).`

**Comment by argiepiano** [comment]
OK, so this is what's happening. When you select "This page (override)" the submit callback `views_plugin_query_default::options_submit()` is called twice, once by line 2552 of views_ui_admin.inc and then by line 2567.

What happens is that, the first time it's called, `options_submit()` gets a string in  `$form_state['values']['query']['options']['query_tags']` for field `query_tags`. It processes that string by exploding it by ',' (since you can enter query tags separated by commas) and proceeds to store the resulting array back in `$form_state['values']['query']['options']['query_tags']`, to get ready to save that.

The problem is that when the function is called a second time, it's getting an array as part of `$form_state['values']['query']['options']['query_tags']` (the one stored above). When it tries to explode it, it produces an exception. In PHP 8.1, this basically results in the process being stopped in its tracks, and because this is ajax, the page remains untouched. In earlier versions, the form is submitted, but generates a warning:

`Warning: implode(): Invalid arguments passed in views_plugin_query_default->options_form() (line 282 of /XXXi/Sites/localhost/bdentity/core/modules/views/plugins/views_plugin_query_default.inc).
`
I believe the double call is the normal way, since you are overriding a value. So I think the problem is storing the array in ``$form_state['values']['query']['options']['query_tags']``, and then not checking that there is an array there instead of a string on the second call.

I checked to see if this has been reported in D7 (which has the same issue). It has not. I guess it's a fringe use: overriding query tags for a specific display. 

I'm not sure I have the time to try a solution for this, but I believe the way to go is to check and see if  the stored value is a string or an array before doing the exploding.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4253 ready for testing

**Comment by argiepiano** [comment]
Test failures seem unrelated.

**Comment by indigoxela** [comment]
Brilliant! Now I can also confirm the problem, even on PHP 7.4 (but with that version the view still saves).

Then I applied the patch and the query settings save properly on PHP 8.1, and the view uses DISTINCT. WFM! :+1:

It may be an edge case, but it's still a bug.

**Comment by argiepiano** [comment]
Oops! My PR left out an important line used to remove extra spaces, and remove empty tags in the query tags such as `hello, , there'

```php
$value = array_filter(array_map('trim', $value));
```

I've added that right now

**Comment by indigoxela** [comment]
@argiepiano many thanks for the quick fix. Tested again, still works for me (as expected). :+1:

**Comment by djzwerg** [comment]
It works for me, too. Thanks a lot @argiepiano !

**Comment by indigoxela** [comment]
@argiepiano many thanks for the helpful code comment, it does make sense to me. RTBC! :+1:

**Comment by argiepiano** [comment]
Thanks for reviewing, @indigoxela!

**Comment by quicksketch** [comment]
Thanks @djzwerg, @argiepiano, and @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4253 into 1.x and 1.23.x.
