### ISSUE TITLE
Rid of unnecessary "Show all columns" toggle link

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#5856]
## Description of the bug

Could only dig https://github.com/backdrop/backdrop-issues/issues/1714 and https://github.com/backdrop/backdrop-issues/issues/4964 both of which discuss different tasks, so here is a new one.

Hovering over the "Show all columns" toggle link on Modules page gives the hint about it's function: 

> Toggle visibility of table cells, that were hidden to make the table fit within a small screen.

However, no table cells are hidden on a regular computer, so while this link could be a good option for mobile or small screen devices, it doesn't serve any purpose on a regular screen and therefore could be removed or hidden.

Correct me if the link is really needed for something that I'm missing here. 

BTW, narrowing the screen didn't hide any cells, so I believe this feature is for only for mobile phone. Didn't test this on a mobile phone.

![Screenshot 2022-11-06 at 3 21 09 PM](https://user-images.githubusercontent.com/56604405/200196290-60fd69c8-ae78-4619-8093-fd6a8370d0f5.png)

**Comment by argiepiano** [comment]
I'm not sure what browser or device you are using, but when I resize my laptop browser  to something very narrow, the Description column is hidden. So, in this case, the "Show all columns" works as expected, and is very helpful in fact.

"Normal" laptop size:
<img width="1193" alt="Screen Shot 2022-11-06 at 6 19 26 PM" src="https://user-images.githubusercontent.com/9938978/200207623-b0ad9d35-0a54-45e2-93cf-17e19cf0cdf6.png">

Narrow screen
<img width="542" alt="Screen Shot 2022-11-06 at 6 19 41 PM" src="https://user-images.githubusercontent.com/9938978/200207640-b17c1cae-a9b0-4417-a67a-8b32bfcc0597.png">

**Comment by alanmels** [comment]
After testing this on two different browsers and getting the same initially reported issue, I've gone ahead and installed another fresh Backdrop and it worked just like you explained - the description cell disappeared and the Show all columns link showed only on narrow screen. So apparently something else was causing the initially reported issue. Please nevermind this issue.

**Comment by alanmels** [comment]
I'm afraid I have to re-open this issue after additional testing. The problem re-appears as soon as you set Basis as administration theme on /admin/appearance. Since Basis is the default theme, it should be expected to work properly also as an administration theme.

**Comment by docwilmot** [comment]
Basis has never been useable as an admin theme. Previous brief issue here: https://github.com/backdrop/backdrop-issues/issues/2653. FWIW I agree with you that it should be fixed to work both front and back end.

**Comment by alanmels** [comment]
Thanks for the update. Closing in favor of https://github.com/backdrop/backdrop-issues/issues/2653.
