### ISSUE TITLE
[UX] Rename Seven to 'Administration'

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#586]
People found it really confusing that in Drupal the administration theme was called seven, and in many cases they even knew they were running Drupal 7, but didn't get the correlation.

In Backdrop, we'll be running version 1.0, and the name Seven will seem even more foreign and absurd to our users.  Let's give this admin theme a sensible name, like 'Administration'.

Related: https://github.com/backdrop/backdrop-issues/issues/201

**Comment by BWPanda** [comment]
I'll work on this, assuming @jenlampton hasn't started already...

**Comment by jenlampton** [comment]
I had started... but @quicksketch says we don't have time :(

**Comment by jenlampton** [comment]
Here's a new plan...  Let's leave Seven in core, and when we get the new branding from https://github.com/backdrop/backdrop-issues/issues/201 done, we can add a new theme to core called "Administration"

**Comment by docwilmot** [comment]
See https://github.com/backdrop/backdrop-issues/issues/139#issuecomment-70102130. 
I wonder if it would be confusing for a user to be able to change the administration theme from "Administration". I'd opt for another name.

**Comment by jenlampton** [comment]
Okay, that will also buy us time to decide on a better name. Closing this as a dupe of https://github.com/backdrop/backdrop-issues/issues/201
