### ISSUE TITLE
PHP 8.1 Error - Deprecated function rtrim() Passing null to parameter #1 of type string is deprecated

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#5866]
## Description of the bug
Using PHP 8.1, when adding a file to a node and then editing that node with the file on, a deprecation notice appears if set to show. Also getting this on display of pages with images (seen after update, before I applied the patch from the PR).

## Steps To Reproduce

To reproduce the behavior:
1. Enable display all messages
2. Enable debug in severity of messages to log
3. On a content type that takes images, upload an image

## Actual behavior
Error message:
`Deprecated function: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in backdrop_basename() (line 2549 of /app/docroot/core/includes/file.inc).`

Turns out through debugging that some iterations through `backdrop_basename()` send the `$uri` as `NULL`

## Expected behavior
No deprecation notices.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.23.0
- Web server and its version: Litespeed
- Operating System and its version: Linux
- Browser(s) and their versions: N/a

**Comment by yorkshire-pudding** [comment]
Can't reproduce this on a vanilla site.  Only other module that calls backdrop_basename() is devel.  Adding that to vanilla doesn't reproduce error and disabling devel doesn't get rid of error.

**Comment by yorkshire-pudding** [comment]
I have finally managed to track down what causes this. I had to use the HEAD version of `devel` as the release version crashed when try to do Krumo backtrace on this error.

The issue in this case originates with [SVG Image](https://github.com/backdrop-contrib/svg_image) and I've opened [an issue](https://github.com/backdrop-contrib/svg_image/issues/1) in that queue with a PR to fix it.

Before I close this ticket though, I wonder should `backdrop_basename()` check to ensure that `$uri` is not an empty string before doing what it does?

**Comment by kiamlaluno** [comment]
On #5890, we added `if (is_null($parameter)) { /* Exit */ }`. See the comments left in that issue to understand the feeling for that change.

**Comment by yorkshire-pudding** [comment]
Thanks @kiamlaluno - yes, it's complicated. This took quite a bit to diagnose as `devel` wasn't working.  Once I traced it to the module, I could suggest a fix there. 

From that other conversation, it looks like my PR would cause problems for 5.6 so probably best to close the PR and this issue.
