### ISSUE TITLE
Flip position of "Functionality" and "Appearance"

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#587]
Right now the order of our admin menu is:

```
Content | People | Functionality | Appearance | Structure | Configuration | Reports
```

We should flip Functionality and Appearance so that it is:

```
Content | People | Appearance | Functionality | Structure | Configuration | Reports
```

Tha makes it so that the menu is a spectrum, with "Editorial" functionality is to the left while increasingly "Developer" functionality is to the right. Appearance is an easier concept to understand for any user so it's moved left. That puts "Functionality" right in the middle, the task that is probably most shared (for better or worse) between non-technical and technical users.

**Comment by jenlampton** [comment]
yes yes yes yes this has bothered me for a long time :) 
+10
