### ISSUE TITLE
PHP 8.1 and backdrop_is_cli()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#5872]
## Description of the bug

When getting `bee` ready for PHP 8.1, we set `$_SERVER['SERVER_SOFTWARE'] = ''` rather than `$_SERVER['SERVER_SOFTWARE'] = NULL` as several functions in `core/includes/bootstrap.inc` use `preg_match()` which under PHP 8.1 will not accept `NULL` as a string.

We get deprecation notices:
`preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated` - see https://github.com/backdrop-contrib/bee/issues/222

Hence why we changed to `$_SERVER['SERVER_SOFTWARE'] = ''`

However, `backdrop_is_cli()` does not evaluate `''` to being `!isset()` and this (tracked down by @indigoxela ) then causes `bee` to freeze when the command would generate a prompt for the user to confirm an action.

See:
- https://github.com/backdrop-contrib/bee/issues/244
- https://github.com/backdrop-contrib/bee/issues/234

If the function could be changed to:
```php
function backdrop_is_cli() {
  return (empty($_SERVER['SERVER_SOFTWARE']) && (php_sapi_name() == 'cli' || (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)));
}
```
Then this would work whether the value was `NULL` or `''` 

---
PR added - https://github.com/backdrop/backdrop/pull/4265

**Comment by yorkshire-pudding** [comment]
While a temporary workaround has been added to bee, this change is still required as at the moment, there are functions in `core/includes/bootstrap.inc` that require `$_SERVER['SERVER_SOFTWARE']` to be a string for PHP 8.1 and `backdrop_is_cli()` will not currently recognise a blank string (`''`) as being a CLI environment.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4265 into 1.x and 1.23.x. Thanks @yorkshire-pudding!
