### ISSUE TITLE
Adding URL redirects from node form creates warning on log messages 

### ISSUE THREAD

**Issue by sudipto68** [backdrop/backdrop-issues#5878]
## Description of the bug

Getting this Warning when adding a redirect to my fresh backdrop site. The redirect works perfectly but it creates a warning message related to core/modules/redirect/redirect.admin.inc file.

![Details _ Latest Backdrop Site](https://user-images.githubusercontent.com/53519888/205887170-7b5295c2-a0b6-45db-bd05-33280c3dca2f.png)

## Steps To Reproduce:
1. Create a test node.
2. Edit the “test” node and add a redirect to any other node.

![Add redirect _ Latest Backdrop Site](https://user-images.githubusercontent.com/53519888/205888158-df886e04-6286-44d1-b8b6-c85fe2e8e4e0.png)

Then save redirect and now check the recent log messages and you should see now a warning like this
`count(): Parameter must be an array or an object that implements Countable in redirect_edit_form() `
 

## Additional information
- Backdrop CMS version: 1.23.1
- Web server and its version: Nginx/1.18.0
- Operating System and its version: Ubuntu 20.04 lts
- Browser(s) and their versions: Google Chrome v107.0.5304.87

**Comment by indigoxela** [comment]
@sudipto68 many thanks for reporting this bug.

I can confirm it, and - even worse - on PHP 8 it's a fatal one.

Two observations:

1)
`count(form_get_errors())` assumes that form_get_errors() always returns something, that's countable. In fact, [form_get_errors()](https://docs.backdropcms.org/api/backdrop/core%21includes%21form.inc/function/form_get_errors/1) *can* return NULL. This gives a warning with php 7.x, but a fatal error with php 8.1.

2)
I didn't find any constellation, where form_get_errors() in function redirect_edit_form is *not* NULL.

The easiest solution would be type casting, but I'd like to understand, whether the form_get_errors() check will ever work as expected at that point.

**Comment by argiepiano** [comment]
> I didn't find any constellation, where form_get_errors() in function redirect_edit_form is not NULL.

At quick glance, I see that `redirect_element_validate_source()` can add an error to the form. This function is used to validate the `source` element in the form, and it forces a form `rebuilt`. So it seems like `redirect_edit_form()` will get that error when being rebuilt.

**Comment by indigoxela** [comment]
@argiepiano many thanks for your check. :pray: But ... if I make it a loop (redirect to same, clearly an error), validation fails - and still form_get_errors() returns NULL. Any other wrong use I could try?

**Comment by indigoxela** [comment]
Gosh...

From: `http://` (literally!)
To: `http://`

Message:
The source path is an existing path.... blabla...

Additionally lots of `Undefined array key "path"` and  form_get_errors() is still NULL - heck, what does that form validator do, anyway?

**Comment by klonos** [comment]
Sounds like we should be using `empty()` instead of `count()` ...either that, or a combination of `is_array() && empty()` 🤔 ...plus also fix those weird things that @indigoxela found with those edge cases 😅 

> Any other wrong use I could try?
🤣 👍🏼

**Comment by herbdool** [comment]
There are a number of places in core that just use `!form_get_errors()` so I've done that in my PR.

**Comment by klonos** [comment]
Yup, the code change is simple, and no errors logged when creating redirects (plus all tests pass) 👍🏼 ...given that we are doing this elsewhere, I'm marking this as WFM + RTBC.

Thanks @herbdool 🙏🏼

**Comment by quicksketch** [comment]
Thanks everyone! I merged https://github.com/backdrop/backdrop/pull/4372 into 1.x and 1.24.x. Extra thanks to @sudipto68 for reporting this issue and with such detail!

https://github.com/backdrop/backdrop/commit/f695ee8717361df24083e5080e438abed95914eb by @herbdool, @indigoxela, @sudipto68, @klonos, and @argiepiano.
