### ISSUE TITLE
GHA: switch to Checkout V3 to prevent node.js nagging

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#5880]
Recently GitHub Actions switched to require node.js 16:

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

We're still on [actions/checkout@v2](https://github.com/backdrop/backdrop/blob/1.x/.github/workflows/phpcs-lint.yml#L30)

And that's why we get:

![annotation-nodejs](https://user-images.githubusercontent.com/842066/206151198-7eeb2583-3734-4fe0-9ee6-61aa88df0206.png)

Easy to solve: simply switch to actions/checkout@v3.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4268) is available for review.

**Comment by klonos** [comment]
Thanks @indigoxela (for this issue specifically, and for taking care of many of our GHA-related tasks) 🙏🏼 

I've had a look at the code, and it looks good to me + tests are passing, so RTBC 👍🏼

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4268 into 1.x and 1.23.x. Thanks @indigoxela and @klonos!
