### ISSUE TITLE
[UX] Admin Bar: Add a single, centralized point of entry for adding content, files, user accounts etc.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5884]
This feature request is inspired by [New “content creation” menu proposal](https://www.drupal.org/project/ideas/issues/3203618) and [Add "Add" item to toolbar](https://www.drupal.org/project/drupal/issues/2377543).

> Adding content is a critical function in Drupal. While we have added a tools block and a default shortcut for this EVERY OTHER MAJOR CMS puts an add or create content link in the MAIN toolbar. This is marked critical because it is a critical usability problem in Drupal that a new user has to hunt around just to find where to do the most fundamental thing that a CMS does; create content.
> 
> Content can not only be nodes, but also media items or custom entities

...

> The top level admin sections result in a disjointed experience for people with primarily content creation/management focused permissions. Access to items that for these users are similar tools is spread out across multiple admin sections.
> 
> We* propose to introduce a content editor menu that brings these creation/management tasks together for easier access.

![image](https://user-images.githubusercontent.com/2423362/206698843-8a676bbd-266d-4ff8-866c-c74dbd88e817.png)

![image](https://user-images.githubusercontent.com/2423362/206698990-4a49f7f1-73b9-4e7d-a833-77dd9d26f0cb.png)

![image](https://user-images.githubusercontent.com/2423362/206698951-d054a8ca-81b2-41d3-a3d0-42cc58982801.png)

**Comment by jenlampton** [comment]
I don't think we need this in the admin bar. This is what the dashboard is for :)
