### ISSUE TITLE
"Plain text" text format not implementing 2 default filters.

### ISSUE THREAD

**Issue by echozone** [backdrop/backdrop-issues#5887]
The "Plain text" text format does not implement it's default filters of:

* Convert URLs into links
Web and email addresses turn into links automatically.

* Convert line breaks into HTML (i.e. `<br>` and `<p>)`
Lines and paragraphs break automatically.

I spun up a demo to test, and found these filters to be checked by default, but not having any effect.

Editing:
<img width="90" alt="edit" src="https://user-images.githubusercontent.com/2477719/206799301-e1886102-e23d-46a3-9042-3f5a90b9a0e0.png">

Result:
<img width="188" alt="result" src="https://user-images.githubusercontent.com/2477719/206799386-c22b66f2-b35d-4912-ad11-28ba542c3e06.png">

**Comment by kswan** [comment]
I suspect you are running into a confusing aspect of backdrop that confused me as well. There is a difference between the plain text _format_ and plain text _processing_. The plain text format is used on a filtered text field when the user doesn't have permissions to use a more powerful format. Plain text processing strips all html from the text.

Issue #5515 gives more explanation about this topic.

**Comment by echozone** [comment]
Thank you! In my case, it's not limited by the users permission, but by how the field is configured, in this case, an account field.

**Comment by kswan** [comment]
Correct, when you select Plain text under Text processing, text filters are not applied. 
![Screenshot 2022-12-09 4 58 53 PM](https://user-images.githubusercontent.com/154391/206809096-ef62099b-2f9f-4cd7-b8c3-cff274f59344.png)

Plain text _processing_ bypasses all text filters and uses a hard coded processing that strips all html.
