### ISSUE TITLE
Fix indentation in `layout_list_page()` in layout.admin.inc

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5888]
I realize that in #5848 we seem to have consensus to be ignoring any coding standards violations when these are outside the files/code that was changed by the PR, but in order to fully unblock the current PR for #5491, lets just fix this problem that PHPCS detected (and we could then rebase that PR and things should be gold 😉 ).

PR coming up...

**Comment by laryn** [comment]
LGTM

**Comment by bugfolder** [comment]
Done. LGTM too.

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼 😉

**Comment by quicksketch** [comment]
Nice one! Thanks @klonos, @laryn, and @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4277 into 1.x and 1.23.x.
