### ISSUE TITLE
Document that node_load_multiple(FALSE) returns all the nodes

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#5889]
As reported in #5437, calling [`node_load_multiple()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_load_multiple/1) with no arguments returns an empty array, while [`entity_load_multiple('node')`](https://docs.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.module/function/entity_load_multiple/1), the function called by `node_load_multiple()`) returns all nodes as expected.

This happens because the default value for `entity_load_multiple()`'s `$ids` is `FALSE`, while the default value for `node_load_multiple()`'s `$nids` is `array()`.

`$nids` should be documented to accept `FALSE` as value, which is the value used to return all nodes.

**Comment by kiamlaluno** [comment]
The failing tests are for blocks that should appear on a page. That is not caused by the PR for this issue, which is only changing a code comment.

**Comment by BWPanda** [comment]
@kiamlaluno It's really hard to review your PR when there are so many unrelated changes. I know they're mostly for fixing coding standard issues, but I think they need to be reviewed properly in their own issue.

Can you please take out changes unrelated to this issue, and perhaps open a new issue to fix the issues in `core/modules/node/node.module`?

**Comment by kiamlaluno** [comment]
@BWPanda I will. I guess that when I created this PR I thought I had to also fix the coding standard issues in the changed file.

**Comment by BWPanda** [comment]
Nah. Eventually all existing CS issues will be fixed throughout core, so when the CS action is run on a PR it'll only flag issues with the code that was changed. But until then, it'll flag a bunch of stuff that can be ignored for now. It'd be great to get it fixed as part of an existing PR, but when it makes reviewing the PR difficult then I think a separate issue is necessary.

**Comment by kiamlaluno** [comment]
I just added type-hints for `node_load_multiple()`. I hope that is fine.

**Comment by kiamlaluno** [comment]
(I need to remember that the pull-down menu does not remember the labels removed directly from the page.)

**Comment by argiepiano** [comment]
@kiamlaluno I left a small comment in the PR. Other than that LGMT

**Comment by bugfolder** [comment]
Documentation change to describe existing behavior would be a minor milestone (which I've added).

**Comment by kiamlaluno** [comment]
I rebased the PR. It does not seem it helped with `phpcs` complains, though. (It must be my usual luck. 😅)

**Comment by argiepiano** [comment]
> Documentation change to describe existing behavior would be a minor milestone (which I've added).

If it's `minor` for the milestone,  shouldn't it then be 1.25.0?

**Comment by bugfolder** [comment]
Brain-fart. I mean bugfix release.

**Comment by bugfolder** [comment]
Sorry. Features (new features) get minor. Bugfixes and tasks (this was a task) get bugfix release.

**Comment by BWPanda** [comment]
Added a suggestion in the PR.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.24.x. Thanks folks!
