### ISSUE TITLE
Copy Region Block Not Updating

### ISSUE THREAD

**Issue by mikesoltis** [backdrop/backdrop-issues#5892]
## Description of the bug

Disabling a block in a Layout Region does not disable the block for the corresponding "Copy Region" block.

## Steps To Reproduce

To reproduce the behavior:
1. In the Default Layout create a Test Region and add a random block.
2. Create a new page and make a new Layout for it. In the Header Region of the new Layout, add a "Copy Region" block.  Copy the Test Region from the Default layout and save.
3. The new page should now display the random block that is in the Default Layout Test Region.
4. Disable the block in the Default Layout Test Region.
5. The page that uses the "Copy Region" block still shows the disabled block.
6. This is true after flushing all caches.

7. Other pages that use the Default Layout do not show this disabled block - as expected.

## Actual behavior

Disabled block in original Region is not disabled in the corresponding "Copy Region" block.

## Expected behavior

All changes made to the Layout Region should be propagated to all corresponding Copy Region blocks. 

## Additional information

    Backdrop CMS version: 1.23.1
    Web server/Operating: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.27
    Browser(s) and their versions: Firefox 102.4.0esr (64-bit)

**Comment by laryn** [comment]
Thanks for the report -- I'm copying it over to the issue queue for the Copy Blocks module which seems to be the relevant location, and then I'll close it here: 
https://github.com/backdrop-contrib/copy_blocks/issues/22
