### ISSUE TITLE
Wrong help text in the timezone selector in user edit form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5899]
![image](https://user-images.githubusercontent.com/2423362/210131534-e4371c75-9770-4a8e-a6f3-8ffb20fbc0e7.png)

The text reads:
> Select the desired local time and time zone. Dates and times throughout this site will be displayed using this time zone.

The user is selecting one thing: timezone - not local time. Also, if you view the second sentence from an admin point of view (while editing another person's user account), it sounds as if this setting will affect everything on the site, whereas this will only affect the user for the account being edited.

**Comment by klonos** [comment]
Simple PR up for review: https://github.com/backdrop/backdrop/pull/4290

Initially, I thought that we should display a different message depending on whether the currently logged-in person is editing their own account or not, by adding a "for this account" or "for your account" at the end of the existing help text. However, after enabling the Language and Locale modules, I saw that we are doing a good job conveying that for the help text in the language selection:

> This account's default language for emails, and preferred language for site presentation.

So I went with something similar for the time zone selector as well:

> This account's preferred time zone for date and time display throughout the site.

![image](https://user-images.githubusercontent.com/2423362/210138902-f5c34eee-0858-4bea-9c7a-532361452944.png)

I've removed the "Select the desired local time and time zone." bit, since it states the obvious and doesn't provide any value.

**Comment by bugfolder** [comment]
I like the new wording. Code reviewed. Tested. WFM, LGTM, RTBC (but others might still want to chime in on the wording).

**Comment by quicksketch** [comment]
Thanks @klonos and @bugfolder! I merged this into 1.x only for 1.24.0.

**Comment by jenlampton** [comment]
Why wasn't this in 1.23.2? Does it include new tests?

**Comment by quicksketch** [comment]
I was thinking to minimize string changes, and with 1.24.0 around the corner.
