### ISSUE TITLE
[UX] No summary in the "Region and Language" vtab in the account edit form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5900]
Noticed this while working on #5899:

![image](https://user-images.githubusercontent.com/2423362/210138902-f5c34eee-0858-4bea-9c7a-532361452944.png)

**Comment by klonos** [comment]
PR up for review: https://github.com/backdrop/backdrop/pull/4291

![image](https://user-images.githubusercontent.com/2423362/210150214-a6e980e5-0ec4-4d4f-815b-6ea24c9af27e.png)

**Comment by olafgrabienski** [comment]
Good catch, @klonos. I was able to reproduce the issue and tested the fix in the PR sandbox, works for me!

**Comment by bugfolder** [comment]
Nice fix. Code reviewed, LGTM.

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4291 into 1.x and 1.26.x.
