### ISSUE TITLE
Add documentation for the global `$conf`.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5902]
The global variable `$conf` (which typically holds a copy of the (deprecated) `variables` table) is undocumented (no description) in the [Globals variable listing](https://docs.backdropcms.org/api/backdrop/globals).

It should have a docblock added in core/authorize.php, where it is introduced, and then the API documentation would pick it up. It would also be nice to have some explanation of when and where it could still be used (if at all?). I see there are several usages in core, presumably all related to backward compatibility with use of `variable_*` functions.

Would it be fair to say that if one is not using the backward-compatibility layer for `variable_*` functions, one should not be using the global `$conf` variable either?

**Comment by quicksketch** [comment]
Agreed we should have docs for `$conf`, perhaps if only to mark it deprecated. That's correct that unless your code is using `variable_get/set()`, then you shouldn't ever be using `$conf` either. There are comparable variables in the config system: `$config` (for config overrides) and `$settings` (for things like cache backends).
