### ISSUE TITLE
[DX] Remove the `position` key from `hook_menu()`.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5903]
## Description of the bug

In [the documentation of `hook_menu()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu/1), the `'position'` entry is described thus:

> **"position"**: Position of the block ('left' or 'right') on the system administration page for this item.

However, the Seven theme, via `seven_admin_page()`, ignores the position values and simply puts the first half of the blocks on the left and the second half on the right. This can result in a badly unbalanced admin page if it is a mix of long and short blocks, and of course, if the module developer has tried to balance their admin page by judicious selection of left and right position, it will be ignored.

## Expected behavior

If all of the blocks have been positioned as `left` or `right`, I would expect those positions to be honored when creating the admin page.

Of course if no blocks have been positioned, it's reasonable to use a simple heuristic like the current behavior to divide them up between left and right; but if they've already been positioned, those positions should be respected.

## Update

Through the discussion below the community collectively decided that it was strange to have anything related to page display stored in the menu system, so the old Drupal `position` key has been removed. 

The admin pages are now using CSS to divide items into multiple columns, which should work better in most scenarios.

**Comment by bugfolder** [comment]
PR created for discussion. If the block has `left` or `right` set, the value is honored; otherwise the same logic that is currently applied is used for the position of the block.

**Comment by bugfolder** [comment]
A few more notes/thoughts:

* `theme_admin_page()`(which `seven_admin_page()` overrides) respects `position` if it exists, otherwise uses odd/even assignment to left and right.
* If there is a concern about changing the behavior of Seven theme on existing sites, we could add a theme setting of a checkbox, "Ignore left/right positioning on admin page".

**Comment by bugfolder** [comment]
I've modified the PR to make respecting of position an option in Seven theme, with the default for existing sites being to take over positioning (as now), but giving people the option of having the theme behave like the documentation says it should, i.e., respecting position settings.

The existing "take over positioning" algorithm tries to balance the same number of blocks in left and right. This can result in badly mismatched columns if some blocks have many more menu items than others. So I also modified the default positioning algorithm to take into account the sizes of the individual blocks.

As an example for comparison, [one of the Ubercart issues](https://github.com/backdrop-contrib/ubercart/issues/406) asks to move the `admin/store/settings` block to the bottom of the Store menu. With the original Seven algorithm, this results in mismatched column heights on the Store page (which uses `'admin_page'` theme element). With the new algorithm, still letting Seven take over positioning, they're more closely matched, see here.

![mod_ubercart_both](https://user-images.githubusercontent.com/29214084/210179976-11b95755-067a-4097-b817-5438306ad4dc.png)

**Comment by klonos** [comment]
Interesting problem to solve @bugfolder 👍🏼 

I think that while you are solving one problem (uneven distribution of blocks in the left/right column), you are introducing another: the way this is solved makes good use of screen space, but it moves things around in unpredictable ways. So depending on the size of the blocks, and which items are available/enabled, a block/group may appear in the left or right column on different sites, or if the configuration on the same site changes (unless it has a specific `'position'` property, in which case your solution helps respect what was set). So people that are used to finding one thing in a certain place might now be tripped for a moment.

I'll need to give this a bit more thought before I can come back with anything useful.

**Comment by bugfolder** [comment]
> So depending on the size of the blocks, and which items are available/enabled, a block/group may appear in the left or right column on different sites

That's the current behavior, too; if you add an block early in the list, it can push the bottom left block to the top right.

At least with the option to respect position turned on, positioned blocks will appear consistently left/right. But of course, unpositioned blocks could still move around.

**Comment by klonos** [comment]
> ...of course, unpositioned blocks could still move around.

Yup, that's what I was trying to say. The PR addresses a bug where positioning is not respected, so that gets a 👍🏼 ...the placement of blocks according to available space and height of columns may need a bit more thought though (not opposed to it).

**Comment by bugfolder** [comment]
So, thinking about this further, how about this as a theme setting for Seven: a set of 3 radio buttons:

(•) - Balance left and right columns by block numbers
( ) - Balance left and right columns by block sizes
( ) - Respect left and right positions if set for blocks

The first option would be the default value and is the the current behavior (so no changes in behavior for existing sites). The second option is similar, but does a better job of balancing blocks with widely varying numbers of items (the algorithm in the current PR). And the third option is consistent with what the documentation says about the `'position'` value, so for people who want their site to behave like the documentation says it does, they now have that option.

I'm not wedded to the wording, and it would probably benefit from help text for each individual option giving a more detailed explanation. But what do folks think about the notion?

**Comment by bugfolder** [comment]
Well, having tried out various combinations of the above with variously sized collections of menu items, I've come to the conclusion that there's no good general-purpose solution here. So I'm going to close the issue and PR. Folks who need better balance than Seven provides would probably be better off implementing their own override of `theme('admin_page', ...)` in a sub-theme.

**Comment by klonos** [comment]
The only thing that I would like to add is that if this page had a 2-column layout and these sets of menus were individual blocks, then the entire page could be treated as a "dashboard", and people could move all these menus around as it suited them best.

**Comment by bugfolder** [comment]
Reopening after the Backdrop design meeting 2023-03-16. Points raised:

* Consider removing the `'position'` item from `hook_menu()` items (just ignore any existing). But how might that affect existing code?
* Consider using CSS `columns` in the theme function to let the browser auto-balance the blocks on that admin page.

**Comment by BWPanda** [comment]
I'd like to see this item removed from `hook_menu()` and just style this page automatically with CSS instead.

Consider the following scenario(s):
- A new, default Backdrop site has menu items nicely divided between the left and right columns, with a small gap in the right column
- A contrib developer (of the 'test' module) adds their menu items to the right column as they seem to fit there best
- Another contrib developer (of the 'blah' module) also adds their menu items to the right column as they also seem to fit there best (since they don't have the 'test' module installed)
- Another contrib developer (of the 'yada' module) also adds their menu items to the right column as they also seem to fit there best (since they don't have the 'test' or 'blah' modules installed)
- A user with all three modules installed ('test', 'blah' and 'yada') sees a very long right column and the whole page looks unbalanced

So yeah, let's manage this automatically with CSS and remove this `hook_menu()` option.

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/4385

![image](https://user-images.githubusercontent.com/2385329/225800790-024479c1-ce28-4839-b1a1-4e60d4e5f2e3.png)

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...code looks good, but when I tried to test this I couldn't get to the same page as your screenshot. Did you create a custom admin page for that?

**Comment by bugfolder** [comment]
I got to that page by visiting `admin/index` on the Tugboat build. Looks good. (How did we get all the Ubercart-specific stuff onto that page in Tugboat?)

**Comment by argiepiano** [comment]
On mobile it still looks in 2 columns. Shouldn't it be in one?

![Screenshot_20230317-081332](https://user-images.githubusercontent.com/9938978/225929866-b3645112-cc41-4938-a9ca-61853d487e00.png)

**Comment by klonos** [comment]
> I got to that page by visiting `admin/index`...

TIL ^^

> How did we get all the Ubercart-specific stuff onto that page in Tugboat?

I just installed U/C and enabled it and several of its submodules, since the initial screenshots in this thread were about U/C and I wanted to play with that.

**Comment by klonos** [comment]
> On mobile it still looks in 2 columns. Shouldn't it be in one?

It should, but the CSS in the PR is not using any media queries. @BWPanda can you please add that?

BTW, shouldn't the page in `admin/config` be using the same columns-based approach?

**Comment by BWPanda** [comment]
I've updated to PR to:
- Make the columns responsive (they go back to a single column at 768px)
- Do the same for the `admin/config` page
- Remove Seven's overriding of `admin/config` (as it doesn't seem to be adding anything extra now)

**Comment by klonos** [comment]
Thank you @BWPanda 🙏🏼 ...I have reviewed and tested this and it WFM + RTBC 👍🏼

**Comment by klonos** [comment]
...I've set the milestone to 1.24.2, but we may consider only adding this change to 1.25.0 instead. I've left a comment in the PR about it.

**Comment by quicksketch** [comment]
Looks good to me too! Great thinking and compromise by everyone involved here! Glad to see this non-functioning and esoteric value removed from `hook_menu()`, which was weirdly combining menu routing with this admin panel display.

https://github.com/backdrop/backdrop/commit/96e7230122cdfd60b4b6051dc0bda9608f899d5d by @BWPanda, @bugfolder, @klonos, and @argiepiano.

I also published a change record to https://docs.backdropcms.org/change-records/the-position-key-has-been-removed-from-hook_menu

**Comment by jenlampton** [comment]
I have updated the issue title and added an "Update" to the original issue description to more clearly indicate the change that was made. Thanks everyone!
