### ISSUE TITLE
Instant search filter for the permissions page doesn't reset on role-specific pages

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5909]
## Description of the bug

https://github.com/backdrop/backdrop-issues/issues/980 introduced an instant filter for the permissions page (/admin/config/people/permissions). This instant filter also appears on role-specific permissions pages, e.g., (/admin/config/people/permissions/administrator). However, on these pages, clicking the "Reset" button takes you back to the all-roles permissions page, rather than leaving you on the role-specific page you were on.

## Steps To Reproduce

To reproduce the behavior:

1. Install a Backdrop version that includes the change, e.g., 1.24.0-preview.
2. Go to /admin/config/people/permissions/administrator.
3. Click the "Reset" button on the filter.

## Actual behavior

You'll be taken to /admin/config/people/permissions.

## Expected behavior

You should remain on the page you were on, /admin/config/people/permissions/administrator.

## Additional information

For people using the role-specific permissions pages to avoid the long load times of the full permissions matrix, this is problematic. The Role Listings module makes it easy to get to the role-specific pages (by providing tabs for them all), but the pages are accessible even without Role Listings module installed.

**Comment by klonos** [comment]
Good catch @bugfolder 👍🏼 

Pending for tests to finish, however the code change is simple and straight-forward, and things work as expected in the PR sandbox.

**Comment by klonos** [comment]
PS: eventually I would much prefer it if we changed the reset button to be clearing the text from the box + removing the query from the browser address bar, without having to do any page reloads.

**Comment by quicksketch** [comment]
Yeah, we could easily make the JS clear the input. But I'm happy to merge this as-is before the 1.24.0-preview release.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4297 into 1.x for 1.24.0 (preview).

**Comment by klonos** [comment]
> Yeah, we could easily make the JS clear the input.

Follow-up for that here: #5910

**Comment by quicksketch** [comment]
Sorry @klonos I missed your follow-up and made the same issue at https://github.com/backdrop/backdrop-issues/issues/5933. Since I already filed a PR, it was easier to close your issue which hadn't yet had any comments.

So the _new_ follow-up to add JS to clear the input is https://github.com/backdrop/backdrop-issues/issues/5933.
