### ISSUE TITLE
[UX] Do not reload the page when using the "Reset" button in the instant filters (modules listing and permissions page) 

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5910]
This is a follow-up for #5909 (which in turn was a follow-up for #980)

When clicking the "Reset" button in the filters in `/admin/modules` and `/admin/config/people/permissions` the following things happen:
1. the page reloads
2. any text that was in the filter textfield gets removed
3. any query with the search term in the URL is also removed

We should change the reset button to be clearing the text from the box + removing the query from the browser address bar (via JavaScript), without having to do any page reloads.

**Comment by quicksketch** [comment]
Oops, sorry @klonos I filed a duplicate at https://github.com/backdrop/backdrop-issues/issues/5933 and already made a PR for it. With no comments yet on this, I'm going to close this in favor of https://github.com/backdrop/backdrop-issues/issues/5933.
