### ISSUE TITLE
CKEditor block:module=delta tag fails for views with more than one display

### ISSUE THREAD

**Issue by mikesoltis** [backdrop/backdrop-issues#5914]
## Description of the bug

Inserting a [block_:module=delta] tag manually to display a block in the body field of the CKEditor works as expected for simple Views blocks.  However, when the view block is a sub-block from an additional display in the view, it does not work. 

## Steps To Reproduce

1. In Configuration -> Text Editors and Formats ->  Raw HTML -> Configure, enable the "Backdrop blocks" feature.
2. Create a simple view block called "simple". The machine name will be "simple"
3. Create a new Page titled "test"
4. In the Body field type [block:views=simple]
5. Save the page

The "simple" view will be displayed correctly.

1. Edit the View "simple" and add another Block Display.  The machine name will be "block_1". 
2. Make a change to this new Display (only this display) so the 2 displays look different. Save the View.
3. Edit the Page "test".
4. In the Body field add [block:views=simple-block_1]
6. Save

The 2nd view will not be displayed correctly. 

## Actual behavior

This displays the original "Master" view for both views.  

This can also produce a blank screen for this page if linked to a Webform block (which are all sub-blocks).

## Expected behavior

The 1st and 2nd View should be displayed correctly.

## Additional information

- Backdrop CMS version: 1.23.1
- Web server, Operating System and versions: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips 
- PHP/7.4.27 
- Browser(s) and their versions: Firefox 102.4.0esr (64-bit)

**Comment by argiepiano** [comment]
@mikesoltis I don't see a "Backdrop blocks" option in that configuration page. Are you sure this is not a feature provided by a contrib module? In that case, it may be a bug with that module.

**Comment by mikesoltis** [comment]
You are correct. It is part of the [CKEditor Block](https://github.com/backdrop-contrib/ckeditor_blocks) module.  This module produces an icon in the editor that displays a list of blocks for insertion into the Body.  It essentially inserts the above tag.  I did not realize that the tag, etc. was also part of the CKEditor Block module and not fundamental to CKEditor.

**Comment by argiepiano** [comment]
Since this seems a problem with the contrib module, I'll close this issue. I suggest you post a bug report in its issue queue.
