### ISSUE TITLE
Use node layout when viewing a node preview

### ISSUE THREAD

**Issue by kswan** [backdrop/backdrop-issues#5916]
## Description of the need

When a node display is configured with a layout, the layout is not used when previewing a node. Instead of the node layout controlling the display, it falls back to the content type display mode. This is counterintuitive to the user.

## Proposed solution

When a node path is entered in a layout as "node/%", that layout should also be applied to the path "node/preview/[content-type]/[uuid]".

## Alternatives that have been considered

none.

## Additional information

This issue is similar to #5915 except the preview path doesn't include a nid so the layout context and visibility conditions don't apply in the same way as a node path.

## Draft of feature description for Press Release (1 paragraph at most)

Node layouts are now applied when previewing a node.

**Comment by bugfolder** [comment]
> When a node path is entered in a layout as "node/%", that layout should also be applied to the path "node/preview/[content-type]/[uuid]".

That is the current behavior. I just verified this in the current Backdrop core:

* Create a layout with path `node/%`.
* Give it an obvious block with a title like "NODE ALTERNATE LAYOUT". Save.
* Create a Page node.
* Click the "Preview" button.

It is displayed with the layout "NODE ALTERNATE LAYOUT."

Are you describe a difference scenario? (If so, could you give a more detailed example of how to reproduce the issue.) 

And are you using the latest version of Backdrop? (This behavior has been in place for quite a while, though.)

**Comment by kswan** [comment]
This is strange. On a sandbox site (Backdrop 1.23.1) the layout is displayed. On my site (also Backdrop 1.23.1) the layout is not displayed. 

I think the feature request can be closed since the requested feature is the expected behavior.

**Comment by bugfolder** [comment]
OK, I'll leave this as closed, but it's odd that you're seeing the wrong layout; the preview code was definitely in 1.23.1, so there's something funny going on.

If you do the exact four steps I described above (and have no other layouts with path `node/%`, of course), so you see the correct behavior I described?
