### ISSUE TITLE
Visualisation of Backdrop CMS development

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#592]
Just thought I'd help celebrate the release of Backdrop v1.0.0 with this video:
https://www.youtube.com/watch?v=bU3wlCETHcM

Enjoy!

**Comment by docwilmot** [comment]
this is cool. saw my name too, even cooler.

**Comment by BWPanda** [comment]
Closing (as this isn't really an issue), but just wanted to make sure @quicksketch and @jenlampton didn't miss this. Feel free to share the video to help promote Backdrop and to thank/acknowledge all those involved in its development.

**Comment by quicksketch** [comment]
Thanks @BWPanda! We checked it out. Thanks for making!
