### ISSUE TITLE
Views plugin argument validator options are not being exposed in Contextual Filters settings

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5921]
## Description of the bug

Subclasses of `views_plugin_argument_validate` can have options, but those are not being shown when one adds and edits a contextual filter parameter in a View. An example is the the `views_plugin_argument_validate_node` validator, which has options "Content types," "Validate user has access to the content", and "Access operation to check," but the edit screen for the contextual filter doesn't shown any of these:

![example](https://user-images.githubusercontent.com/29214084/211679253-0aa0e473-9929-4d72-8519-b162ddd5317d.jpg)

## Steps To Reproduce

To reproduce the behavior:

1. Create a View of type Content (i.e., a View of nodes). Create a page display with a placeholder in the path, e.g., `node-test/%`.
2. In "Contextual filters," click Add, then select "Content: Type".
3. The resulting edit screen does not give you any options for actually selecting the content type, as in the screen shot above.

## Additional information

This is the behavior in the latest development head (1.24.0-dev), and can be reproduced on the demo from various current PRs.

**Comment by bugfolder** [comment]
OK, this is the same behavior as in D7, so maybe not a bug, maybe I'm just missing where the options are set. If so, where are they set?

**Comment by argiepiano** [comment]
I'm not sure I understand this report. 

By adding `node-test/%` to the path, and then selecting "Content: Type" in the Arguments, you are basically telling the view that you will pass an argument such as `node-test/page` or `node-test/post`, AND the View is supposed to use that argument to limit the types of nodes it shows you.

Am I misunderstanding what you are trying to accomplish?

**Comment by bugfolder** [comment]
What I thought I would accomplish is that since the validator has a form with these settings:

```
    $form['types'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Content types'),
      '#options' => $options,
      '#default_value' => $this->options['types'],
      '#description' => t('Choose one or more content types to validate with.'),
    );

    $form['access'] = array(
      '#type' => 'checkbox',
      '#title' => t('Validate user has access to the content'),
      '#default_value' => $this->options['access'],
    );
    $form['access_op'] = array(
      '#type' => 'radios',
      '#title' => t('Access operation to check'),
      '#options' => array('view' => t('View'), 'update' => t('Edit'), 'delete' => t('Delete')),
      '#default_value' => $this->options['access_op'],
      '#states' => array(
        'visible' => array(
          ':input[name="options[validate][options][node][access]"]' => array('checked' => TRUE),
        ),
      ),
    );
```

that I'd be able to choose which content types the page node/NNN would validate for.

Obviously, I'm missing something big (and I'm sure a forehead-slapping is in my future), but my root question is, where would I see and select from the options on that form?

**Comment by argiepiano** [comment]
If you click "When the filter value IS in the URL or a default is provided" the view shows you different ways to validate the argument. Is that perhaps similar to what you are referring?

**Comment by bugfolder** [comment]
That's it. Doi! Forehead duly slapped (and thanks!).
