### ISSUE TITLE
Switch our PR sandboxes to PHP 8.0 or 8.1

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5926]
Our PR sandboxes are currently being span up with PHP 7.2, which has been EoL'ed for some time now. PHP 7.4, which was the last of the 7.4.x versions has also been EoL'ed on Nov. 2022. See: https://www.php.net/eol.php

We should switch our sandboxes to 8.0 (at least), which would allow us to be catching any incompatibilities earlier as well. PHP 8.0 is slated for EoL by the end of Nov. 2023, which should give us 10 months of no further changes. Now, if we are to catch incompatibilities with PHP 8.1 which is the next target for compatibility fixes, we should the perhaps switch to that instead. 8.1 is slated for EoL in Nov. 2024, which means that we will most likely not have to change this again until ~2 years from now.

**Comment by klonos** [comment]
Filed 2 PRs:
- switch to php 8.0: https://github.com/backdrop/backdrop/pull/4307
- switch to php 8.1: https://github.com/backdrop/backdrop/pull/4308

I'll bring this up during the upcoming dev meeting, to decide and action.

**Comment by argiepiano** [comment]
LGTM! 👍🏽 

I'd lean toward 8.1 rather than 8.0. Many of the compatibility issues we are fixing happen in 8.1, rather than 8.0

**Comment by argiepiano** [comment]
Question: should this be  a task rather than a bug? On the other hand, given that 7.2 is EOL, that could be considered a bug...

**Comment by herbdool** [comment]
@indigoxela @quicksketch would be good to get your opinion on this.

**Comment by quicksketch** [comment]
I think we should go to 8.1 where we in-theory already have total compatibility. Having the sandboxes run the same version will make it easier to test in the event there are any issues still.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4308 into 1.x and 1.23.x. Thanks folks!
