### ISSUE TITLE
change module install upload field help text

### ISSUE THREAD

**Issue by mburnette** [backdrop/backdrop-issues#593]
Help text under module upload still reads "For example: http://ftp.drupal.org/files/projects/name.tar.gz". Needs to read appropriate backdropcms.org URL.

**Comment by klonos** [comment]
Actually, Backdrop contrib modules will live on [GitHub](https://github.com/backdrop-contrib/). I'm not sure whether we'll provide copies on backdropcms.org.

**Comment by mburnette** [comment]
Yea, fair enough. I just gave a Drupal 7 module a shot and it didn't work. Figured the help text needed to just be changed still.

**Comment by quicksketch** [comment]
Yeah packages will be hosted on Github for a while to come yet. So the example should read:

```
https://github.com/backdrop-contrib/email/archive/v1.2.3.zip
```

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/709. Thanks @mburnette!
