### ISSUE TITLE
[UX] Add a description for the `Administrator` role.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#5930]
## Description of the bug

When https://github.com/backdrop/backdrop-issues/issues/5748 got in we accidentally included a default description for the admin role that is not a description of the role. Instead, it's a description of other settings that happen to be applied to the role, but *only at install time*.  

When someone changes these settings, this description for the admin role will become a lie, and not only will that create a really frustrating user and developer experience when trying to debug, but it doesn't add any value because it does not describe the role. 

People who are changing things on the permission matrix are not going to come back and edit the role descriptions. We should try to build something that's going to remain useful regardless of *specific* permissions. 

There were some good recommendations in the original issue, repeating them here:

- (Longer version) `Role that receives elevated permissions for website structure and configuration, including the ability to assign roles.`
- (shorter version) `Permission to mange content and configuration, including the ability to assign roles.` -- I think this got in already

## Steps To Reproduce

To reproduce the behavior:
1. Install a fresh version of backdrop.
1. Go to the roles page at admin/config/people/roles
1. Confirm the description appears as expected

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.24.0

**Comment by klonos** [comment]
I agree with this 👍🏼 ...however, can we please consider appending the `This role receives all new permissions by default.` text to the description of whichever role has been selected to be the admin role? (according to the `user_admin_role` setting in `system.core.json`) ...I feel that that would still provide value, and it won't be a lie if that's what has been configured on the site.

**Comment by jenlampton** [comment]
I've created https://github.com/backdrop/backdrop-issues/issues/5940 so we don't loose that thought @klonos. I like this idea a ton too :) 

I'm going to close this issue in favor of https://github.com/backdrop/backdrop-issues/issues/5932 where we use the longer `help text` description for the Administrator role.
