### ISSUE TITLE
Improve Instant Search Reset on Modules and Permissions Page

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#5933]
## Description of the need

When on `/admin/modules` or `/admin/config/people/permissions`, the "Reset" button provided by the instant search filter reloads the entire page. This potential could cause in-progress changes to the form to be lost, or interfere with modules that provide additional functionality on these pages.

This is a follow-up from #980 and #5909.

## Proposed solution

The reset button on these pages currently is simply a link that reloads the page. We should add a JavaScript behavior to clear the filter input, rather than reloading.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4312 that adds a small amount of JS to both modules and permissions pages.

**Comment by klonos** [comment]
@quicksketch code looks good, but the PR sandbox did not spin up, so I couldn't test. I checked our disk quotas and we are OK, and also nothing in https://status.tugboat.qa, so don't know what's wrong.

I'll wait a bit and might just spin it up on my local and test there.

**Comment by klonos** [comment]
...there's also a failing test, but it seems to be random. Might wanna close and re-open the PR.

**Comment by quicksketch** [comment]
Thanks @klonos. Close/reopen built the Tugboat preview for testing. :+1:

**Comment by klonos** [comment]
Thanks @quicksketch 🙏🏼 ...this works as expected, and the previous filtering functionality and retention of the query on form submit are not affected.

There is now a new random failure ...our old `Start and end date on same day with timezone` friend 😅

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4312 into 1.x for 1.24.0. Thanks for reviewing @klonos!
