### ISSUE TITLE
[UX] Create a separate section for the 2 default layouts in the layout management page

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5934]
This is a follow-up to #5077 and related to #4871.

The `default` and `admin_default` layouts are a special case: fallback layouts that are used when no other layout applies. However, we are listing them along with the rest of the layouts that belong in the "Layout overrides" section.

I think that these deserve a special place, especially since:
- they are already being rendered last in the list - regardless of weight/alpha
- they already have a separate "group description": `Default layouts (used on all paths without a specific layout)`

I'm basically suggesting to split this subsection of the layout overrides table into it's own table:
![image](https://user-images.githubusercontent.com/2423362/212549899-269f614e-c971-44e6-8ccc-262421930b4a.png)

**Comment by klonos** [comment]
PR up for review and feedback: https://github.com/backdrop/backdrop/pull/4313

**Comment by bugfolder** [comment]
Since this was marked "needs - more feedback," I'll give the feedback that I think this is a great change that improves clarity. 

Since it's been around for 9 months, there are two more thumbs up, and no negative feedback, I'm going to remove the "needs more feedback" label.

One small typo, noted in the PR.

Tested, WFM. Code will be LGTM when the PR is updated.

**Comment by stpaultim** [comment]
I support this change. @klonos it sounds like this one is very close.

**Comment by klonos** [comment]
The PR had conflicts. I've fixed those (which also rebased the PR branch) and have also merged @bugfolder's code suggestion 👍🏼 

All tests are green too 🎉  (no layout test gremlins for some odd reason 🤷🏼  ...have they gone away in the same mysterious way they came? 🤞🏼 ).

**Comment by quicksketch** [comment]
Thanks this is a wonderful little improvement! It makes a ton of sense to separate out the default layouts from the others. I merged https://github.com/backdrop/backdrop/pull/4313 into 1.x and 1.26.x. Thanks @klonos and @bugfolder!
