### ISSUE TITLE
[UX] Layouts: add a "cancel" link in the layout reorder form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5936]
Steps to reproduce:
1. add a couple of layouts with the same path (say `node/%`)
2. head back to the layout management page
3. there should be a "reorder" button -> click it
4. change your mind -> no cancel link to go back 👎🏼 (I know there's always the browser back button, but having a "cancel" link is better UX)

**Comment by klonos** [comment]
PR: https://github.com/backdrop/backdrop/pull/4315

**Comment by bugfolder** [comment]
Agreed that the cancel button is needed (and is currently lacking). Tested this PR: behold, the cancel button appears! WFM.

(Someday we'll have tabledrags directly on the layout page, obviating the need for a reorder button, but until that can be done, this is a good stopgap.)

Code reviewed. LGTM.

RTBC.

**Comment by klonos** [comment]
I've rebased in order to get the PR sandbox going again. All green except of cspell nagging, which should be fixed with #6255 - not here.

**Comment by quicksketch** [comment]
Looks great! I merged https://github.com/backdrop/backdrop/pull/4315 into 1.x and 1.26.x.
