### ISSUE TITLE
"The website encountered an unexpected error." after upgrading from dev to 1.0.0

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#595]
Backdrop test site
**Error**
The website encountered an unexpected error. Please try again later.

```
- Warning: include_once(C:\www\backdrop/core/modules/layout/includes/layout.theme.inc): failed to open stream: No such file or directory in theme() (line 1096 of C:\www\backdrop\core\includes\theme.inc).
- Warning: include_once(): Failed opening 'C:\www\backdrop/core/modules/layout/includes/layout.theme.inc' for inclusion (include_path='.') in theme() (line 1096 of C:\www\backdrop\core\includes\theme.inc).
- Recoverable fatal error: Object of class stdClass could not be converted to string in include() (line 9 of C:\www\backdrop\core\modules\system\templates\block--system--main.tpl.php).
```

**Comment by klonos** [comment]
Notice the forward slashes in some of the paths. I think we have solved this at some point (using the appropriate slash depending on OS I mean).

**Comment by quicksketch** [comment]
We moved some of the theme functions around right before the 1.0.0 release. Could you try visiting update.php and running it? That will clear your caches and probably fix the paths of where theme functions live. You could also just truncate the cache and cache_bootstrap tables to fix it.

**Comment by klonos** [comment]
Unfortunately, the update.php throws a "404 Not Found" error. Stupidly, and because I was in a hurry, I dropped the tables instead of emptying them. Can you please post the SQL query to recreate them just so I can test this for posterity's sake?

**Comment by quicksketch** [comment]
lol, sure. This can be used for both cache and cache_bootstrap (just change the table name).

```
CREATE TABLE `cache` (
  `cid` varchar(255) NOT NULL DEFAULT '' COMMENT 'Primary Key: Unique cache ID.',
  `data` longblob COMMENT 'A collection of data to cache.',
  `expire` int(11) NOT NULL DEFAULT '0' COMMENT 'A Unix timestamp indicating when the cache entry should expire, or 0 for never.',
  `created` int(11) NOT NULL DEFAULT '0' COMMENT 'A Unix timestamp indicating when the cache entry was created.',
  `serialized` smallint(6) NOT NULL DEFAULT '0' COMMENT 'A flag to indicate whether content is serialized (1) or not (0).',
  PRIMARY KEY (`cid`),
  KEY `expire` (`expire`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Generic cache table for caching things not separated out…';
```

**Comment by klonos** [comment]
OK, thanx. Emptying the two tables did the trick (also did a full cache clear just to be sure).

**Comment by klonos** [comment]
...so closed.

**Comment by quicksketch** [comment]
Thanks @klonos!
