### ISSUE TITLE
Bring entity reference module up to date with Drupal 7.x-1.6 release.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#5952]
There may be some commits from https://www.drupal.org/project/entityreference/releases/7.x-1.6-rc3 which are good to incorporate here.

Includes these commits:

Changes made since 7.x-1.6-rc2
[#1423778: Fatal error loading EntityReference_SelectionHandler_Broken](https://www.drupal.org/project/entityreference/issues/1423778)

Changes made since 7.x-1.6-rc1
PHP 8.0, 8.1 and PHP 8.2 compatibility added.
[#3334678: PHP 8.2 compatibility fix](https://www.drupal.org/project/entityreference/issues/3334678)
[#3330366: PHP 8 Deprecated function: class_exists(): Passing null to parameter #1](https://www.drupal.org/project/entityreference/issues/3330366)
[#2043161: Notice: Undefined property: entityreference_plugin_display::$id_field_alias in entityreference_plugin_style->render()](https://www.drupal.org/project/entityreference/issues/2043161)
[#2880772: "Show links" field formatter settings not respected for Rendered entity](https://www.drupal.org/project/entityreference/issues/2880772)
[#1411304: Autocomplete hide id options for use with unique labels](https://www.drupal.org/project/entityreference/issues/1411304)
[#3256414: Notice: Trying to access array offset on value of type null in entityreference_field_views_data_views_data_alter()](https://www.drupal.org/project/entityreference/issues/3256414)
[#1702172: Saving allowed even when input is not valid in autocomplete results](https://www.drupal.org/project/entityreference/issues/1702172)

Changes made between 7.x-1.5 and 7.x-1.6-rc1

[view commit •](http://drupalcode.org/project/entityreference.git/commit/f0f8e86c9b4caf61b87256557c1984aa2f7b4917) Issue #2236527 by nithinkolekar, jgullstr, minorOffense, senzaesclusiva: Option to hide title on rendered entities implementing EntityAPIControllerInterface
[view commit •](http://drupalcode.org/project/entityreference.git/commit/fc3f7a8949a4b0491d21428aa1bf6b8660e475b6) Issue #2170193 by daniel_j, dasginganinja: Paths to included files are missing
[view commit •](http://drupalcode.org/project/entityreference.git/commit/95c0712715734561056c081a59ade799295baffe) Issue #2889758 by volkswagenchick: Grammar issue in .module file
[view commit •](http://drupalcode.org/project/entityreference.git/commit/e4f9dee9f83928027e06030776e57a5a0953fb3f) Issue #2938466 by StijnStroobants, riddhi.addweb: Different syntax for update hooks
[view commit •](http://drupalcode.org/project/entityreference.git/commit/ebe38eb7462b48d1678b0e5a4e9264bbf80ee8eb) Issue #2902162 by volkswagenchick: README could use some helpful configuration
[view commit •](http://drupalcode.org/project/entityreference.git/commit/e2dc122af49d661915f94939eabe5f310b6914c7) Issue #2992351 by ram4nd: Fix a typo "... get more tokens and display available once."
[view commit •](http://drupalcode.org/project/entityreference.git/commit/bc8d884816be1f93e03b590447a2be463ba0ac9d) Issue #2879941 by hgoto, sco_tt: Error while performing database update for Entity Reference

**Comment by kiamlaluno** [comment]
The last commits done in the 7.x-1-x branch in the last week are for the following issues.

- [Fatal error loading EntityReference_SelectionHandler_Broken](https://www.drupal.org/project/entityreference/issues/1423778) (created on 2012)
- [Saving allowed even when input is not valid in autocomplete results](https://www.drupal.org/project/entityreference/issues/1702172) (created on 2012)
- [Notice: Trying to access array offset on value of type null in entityreference_field_views_data_views_data_alter()](https://www.drupal.org/project/entityreference/issues/3256414) (created on 2021)
- [PHP 8.2 compatibility fix](https://www.drupal.org/project/entityreference/issues/3334678) (created on 2023)

**Comment by argiepiano** [comment]
@herbdool thanks much for the PR. I've reviewed and tested and everything works great. WFM and RTBC. 

One side note. The D7 issue 1423778 that was ported seems to fix a problem that arose from ctools trying to instantiate a ER class before its file was included. I wonder if this is needed in Backdrop's version, which doesn't  use ctools.  On the other hand, that fix causes no harm and is good defensive coding. Plus I'm seeing a similar error in OG when upgrading from D7. So perhaps something like this defensive fix should also be added in OG.

**Comment by herbdool** [comment]
@argiepiano I too thought we might not need to have that fix for ctools but that it wouldn't do any harm. With Backdrop already using `hook_autoload_info` it might not be an issue, but if you're seeing it with OG perhaps in some cases?

**Comment by quicksketch** [comment]
Thanks @herbdool, @kiamlaluno, and @argiepiano! I've merged https://github.com/backdrop/backdrop/pull/4321 into 1.x and 1.24.x.
