### ISSUE TITLE
Fixed: PHP `Error: Class name must be a valid object or a string in entity_get_controller()`. 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5953]
## Description of the bug

Trying to view an entity reference field throws a fatal error if the referenced target entity is disabled.

## Steps To Reproduce

This error happens with any entity type. For example, with `comment`:

1. Create some posts and add some comments to them
2. Create a new content type, e.g. `test`. 
3. Add an entity reference to `test`, for example `field_comment_ref`. Set the target type to `comment`.  Use a Select list as the widget 
4. Add content of type `test`. Type anything in the title. For the comment reference field, choose any of the listed comments in the select list
5. Save and view your new content of type `test`

Then...
1. Disable the Comment  module
2. View the content of type `test` you added above
3. Error happens

## Actual behavior

Fatal error `Error: Class name must be a valid object or a string in entity_get_controller()`

## Expected behavior

Not a fatal error... other than that, perhaps a watchdog warning? 

## Additional information

This issue is also present in Drupal 7, and reproducible the same way. I couldn't find an issue in their queue.

I believe the solution may be to check if the entity type exists by checking `entity_get_info()`  in `entityreference_field_formatter_prepare_view()` before calling `entity_load_multiple()`.  

Backdrop 1.24.0
PHP 7.4

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4319 ready for review.

While there I got rid of an unnecessary doubled `isset()` check in that same function.

**Comment by herbdool** [comment]
This issue seems to be the same https://www.drupal.org/node/3256414

**Comment by herbdool** [comment]
I suggest we could merge in a few of the commits from the latest release and it might cover this issue too.

**Comment by argiepiano** [comment]
> This issue seems to be the same https://www.drupal.org/node/3256414

While similar, it's not quite the same. They do fix a similar issue that happens under the same condition (viewing a reference field for an entity type that doesn't exist anymore).  But the commit you linked refers to field views handlers, which are altered via `entityreference_field_views_data_views_data_alter()`. The PR here refers to the field formatter.  It may be the case that this PR fixes also the problem outlined in the issue you linked, but haven't tested that.

@herbdool let me know how you want to proceed. Should I close this issue and the PR and try to do a PR that addresses this issue AND the one outlined in the linked D7 issue?

**Comment by herbdool** [comment]
@argiepiano I've got a PR to merge in 7.x-1.6 https://github.com/backdrop/backdrop/pull/4321. We can treat this separately if it still needs to be fixed.

**Comment by argiepiano** [comment]
Sounds good.

**Comment by herbdool** [comment]
Tested and reviewed. It's in line with the fix for the other issue from D7 so I think that also helps support this approach. I tested it also with the other PR and that alone didn't fix it so this is also needed.

@argiepiano can you also give https://github.com/backdrop/backdrop/pull/4321 a spin and update the labels?

**Comment by BWPanda** [comment]
I've tested, reviewed and merged https://github.com/backdrop/backdrop/pull/4319 into 1.x and 1.24.x. Thanks @argiepiano and @herbdool!
