### ISSUE TITLE
Incorrect handling of file upload PHP limit exceeded 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5960]
This is a cross-port of https://www.drupal.org/project/drupal/issues/2749245, which is part of the #5770 task list.

This issue was partly fixed in Backdrop:
- Unlike D7 the widget does not disappear upon receiving the error `An unrecoverable error occurred. The uploaded file likely exceeded the maximum file size`
- Like D7, you can't save the node after this error has occurred. 

To reproduce, follow the steps in the D7 issue. Copying and adapting:

1. Turn off `display_errors` in php.ini.
2. Make sure the post_max_size is set to equal or lower than the `upload_max_filesize` in php.ini. The bug only manifests itself when the `post_max_size` is exceeded.
3. Create a file upload field that is not limited in file size.
4. Upload any file larger than the `post_max_size`

In Backdrop, the result: the error is shown correctly, and the widget does not disappear, but (like D7) when you click Save, the form is reloaded and nothing is saved.

PR coming.

**Comment by argiepiano** [comment]
PR [4328](https://github.com/backdrop/backdrop/pull/4328) ready for testing.

After applying the patch, the offending large file gets removed from the widget. This is enough to allow for saving of the node. The node will also save any other files that are within the limit (in cases when your file field has multiple cardinality).

**Comment by argiepiano** [comment]
There is an unrelated test failure

**Comment by argiepiano** [comment]
I will be cross-porting a test as part of the PR - so this is still WIP

**Comment by argiepiano** [comment]
I finished adding the tests. Ready for review and testing now.

**Comment by bugfolder** [comment]
I tested using the suggested approach:

* Turned OFF `display_errors` in php.ini
* Set `post_max_size` to 8MB, `upload_max_filesize` to 32MB
* Created a file field on the Post type with no maximum upload size
* Attempted to create a new Post node, uploading a 10MB file
* Error appeared (as expected).
* Saved.
* Node wasn't saved, the create file form reappeared empty (as expected).

Applied this patch. Tried the same steps.

* File size error appeared (as expected).
* Saved.
* This time the node was properly saved.

So, patch WFM. Reviewed the code, LGTM. RTBC.

**Comment by quicksketch** [comment]
Thank you so much @argiepiano and @bugfolder! I have merged https://github.com/backdrop/backdrop/pull/4328 into 1.x and 1.26.x.
