### ISSUE TITLE
[SR] Security improvement for l() function

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#5969]
This is a cross-port for the D7 issue https://www.drupal.org/project/drupal/issues/2990723. Tracked by the task list #5770.

From the D7 issue:

> The issue was reported first on security.drupal.org where we agreed to fix it in the public queue. Members who suggested it: greggles, larowlan and mlhess. 
> 
> <h3 id="summary-problem-motivation">Problem/Motivation</h3>
> l() function does not strip dangerous protocols when external parameter is set to TRUE.
> 
> When it returns the output it only calls check_plain for sanitize the path that is given from url() - because comment also indicates it's a plain text URL, it should be sanitized before, but currently it's not.
> 
> For reproduction steps, you can try one of the following:
> 
> Scenario No 1:
> 1. Create a new test module in drupal.
> 2. Implement a hook_menu that will call a custom function.
> 3. In the page callback return the output of l() like this:
> <code>l('link', "javascript:alert('XSS')", array('external' => TRUE))</code>

> Scenario No 2:
> 1. Turn on PHP module.
> 2. Create a new article content and use the php filter format and insert to body the following:
> ```php
> print l('link', "javascript:alert('XSS')", array('external' => TRUE));
> ```
> 3. Save the content, visit its page and click on the 'link' link, then the alert will be executed.
> 
> Both of the above scenarios need more permissions on the website that could lead more serious issues, that's also the reason why we turned to public hardening.

> ## Proposed resolution
> As l() function is widely used in drupal core, also in contribs, changing the way how it prints the output could lead to breaking functionalities, the proposal is to sanitize the path before it's given to sanitization functions that do the other jobs. See currently attached patch where the drupal_strip_dangerous_protocols() function is directly called on $path.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4332

**Comment by klonos** [comment]
Thanks @argiepiano 🙏🏼 ...the respective commit in D7 was https://git.drupalcode.org/project/drupal/-/commit/9b89fa9 and you seem to have missed the change in `CommonURLWebTestCase::testLXSS()`. I've filed a PR against yours: https://github.com/argiepiano/backdrop/pull/1

**Comment by argiepiano** [comment]
Oops! I just merged it.

**Comment by klonos** [comment]
Thanks 🙏🏼 ...code looks good now 👍🏼 

I will need to set some time aside to properly test this, but noting that the 2nd scenario is not applicable to Backdrop (PHP Filter module removed - although I could try testing with the contrib counterpart https://github.com/backdrop-contrib/php).

**Comment by argiepiano** [comment]
@klonos, see attached tiny module. Enable and then visit `/test-l`. That will show a link. When the site is not patched, clicking that link will open a browser alert window with javascript. When it's patched, the link will show a "Page not found" message.

I hope this helps.
[testing_stuff.zip](https://github.com/backdrop/backdrop-issues/files/10711396/testing_stuff.zip)

**Comment by klonos** [comment]
Thanks again @argiepiano 🙏🏼 ...saved me some time there 🙂 

Tested and confirmed that it now works as expected, throwing a "page not found" instead of executing the JS code. WFM 👍🏼

**Comment by BWPanda** [comment]
In `l()`, the PR adds `$path = backdrop_strip_dangerous_protocols((string) $path);` to the top of the function. Later in the function we then have this: `$url = check_plain(url($variables['path'], $variables['options']));`

In core we have this function:

```
function check_url($uri) {
  return check_plain(backdrop_strip_dangerous_protocols($uri));
}
```

Could we not therefore simplify all this (i.e. remove the new line this PR adds, and replace the existing line towards the end) to just be: `$url = check_url(url($variables['path'], $variables['options']));`?

**Comment by kiamlaluno** [comment]
Between `$path = backdrop_strip_dangerous_protocols((string) $path)` and `$url = check_plain(url($variables['path'], $variables['options']));` there is `$path == $_GET['q'] || ($path == '<front>' && backdrop_is_front_page())` (which is part of a `if` statement). With the code used by the MR, a path like `'javascript:' . $_GET['q']` would be considered equal to `$_GET['q']`, which is wrong.

What suggested by @BWPanda is correct: The `$path = backdrop_strip_dangerous_protocols((string) $path);` should be removed and `$url = check_plain(url($variables['path'], $variables['options']));` changed to `$url = check_url(url($variables['path'], $variables['options']));`.

**Comment by kiamlaluno** [comment]
As a side note: What suggested by @BWPanda is what the patch provided for Drupal does.

```
diff --git a/includes/common.inc b/includes/common.inc
index 54ebf96092..d16c959e56 100644
--- a/includes/common.inc
+++ b/includes/common.inc
@@ -2570,6 +2570,7 @@ function l($text, $path, array $options = array()) {
       $use_theme = FALSE;
     }
   }
+  $path = drupal_strip_dangerous_protocols((string) $path);
   if ($use_theme) {
     return theme('link', array('text' => $text, 'path' => $path, 'options' => $options));
   }
```

Drupal code is slightly different, since it can use `theme('link')` while Backdrop code does not use it, but it is clear the patch is filtering the protocol right before returning the link.

**Comment by kiamlaluno** [comment]
Also, looking at the [`l()`](https://api.drupal.org/api/drupal/includes%21common.inc/function/l/7.x) code used by Drupal 7, it includes the following lines.

```php
  $path = (string) $path;

  // For backwards compatibility, do not strip a couple of specific javascript
  // paths that are harmless.
  // @see https://www.drupal.org/project/drupal/issues/3310081
  $skip_js_paths = array(
    'javascript:void()',
    'javascript:void();',
    'javascript:void(0)',
    'javascript:void(0);',
  );
  if (!in_array(strtolower($path), $skip_js_paths)) {
    $path = drupal_strip_dangerous_protocols($path);
  }
  if ($use_theme) {
    return theme('link', array(
      'text' => $text,
      'path' => $path,
      'options' => $options,
    ));
  }

  // The result of url() is a plain-text URL. Because we are using it here
  // in an HTML argument context, we need to encode it properly.
  return '<a href="' . check_plain(url($path, $options)) . '"' . drupal_attributes($options['attributes']) . '>' . ($options['html'] ? $text : check_plain($text)) . '</a>';
```

I cannot say if not stripping those paths is necessary on Backdrop too. The issue linked in that comment ([javascript links in contrib broken since 7.92](https://www.drupal.org/project/drupal/issues/3310081)) explains exactly why that code has been added.

**Comment by kiamlaluno** [comment]
The issue for Drupal makes a case for *when external parameter is set to `TRUE`*, but then strip the protocols even when that parameter is not set or it is `FALSE`.

> `l()` function does not strip dangerous protocols when external parameter is set to `TRUE`.

None of the comments for that issue explains why the code has been then changed to always strip bad protocols. Was that done on purpose, or should have the code been changed differently?

**Comment by argiepiano** [comment]
@BWPanda thanks for the suggestion. I've changed the code accordingly and pushed the changes to the PR. 

@kiamlaluno thanks for all the digging, but I'm unclear about whether you are proposing any changes to this PR, or pointing discrepancies between the code in B and D7.

**Comment by argiepiano** [comment]
Coding standard failures are in files not touched by this PR.

**Comment by klonos** [comment]
@kiamlaluno those changes got into Drupal 7 after the 7.92 release, so I was about to say that there'll need to be a separate issue and PR for it. However, I did a search in our core codebase for `javascript:void(` (which should catch all cases listed in the `$skip_js_paths` array), and I've found most of them to be in .js files (so not called via `l()`). There were 4 instances however called from php code and via `l()` in `views_ui.them.inc`. These were the following:
- in `theme_views_ui_reorder_displays_form()`
- in `theme_views_ui_rearrange_form()`
- in `theme_views_ui_build_group_filter_form()`
- in `theme_views_ui_rearrange_filter_form`

All of them seemed to be from "Remove" links, in the following form:

```php
l('<span>' . t('Remove') . '</span>', 'javascript:void()', array('attributes' => array( ... ), 'html' => TRUE));`
```

I hope that this helps with testing things ...at least with core - not sure about contrib. It does seem to me like we'd need to add that code if we don't want to possibly break custom/contrib code though.

**Comment by kiamlaluno** [comment]
@argiepiano I said the PR code needs to be changed.

> What suggested by @BWPanda is correct: The `$path = backdrop_strip_dangerous_protocols((string) $path);` should be removed and `$url = check_plain(url($variables['path'], $variables['options']));` changed to `$url = check_url(url($variables['path'], $variables['options']));`.

**Comment by kiamlaluno** [comment]
The other comment was about another change I noticed on Drupal code. Since it is a change for the URLs for which the dangerous protocols are stripped off, I commented on this issue, since its purpose is stripping off the dangerous protocols, and nobody mentioned any "white-listed" URLs.

I am fine with creating another issue. I just wanted to add a note about that here.

**Comment by kiamlaluno** [comment]
Finally, I was wondering why the Drupal issue says that is a problem when `'external'` is set to `TRUE`, but then the dangerous protocols are always stripped off.
I find that "interesting" because the protocol part is added to the "URL" also when `url()` gets `TRUE` for `'absolute'`.

I was not suggesting anything was wrong. I only thought the original issue did not handle/consider that.

**Comment by quicksketch** [comment]
@kiamlaluno correctly points out that making this change caused a regression in Drupal. We should incorporate the exception list to allow strings like `javascript:void()`. The follow-up issue on the Drupal side was https://www.drupal.org/node/3310081

**Comment by argiepiano** [comment]
OK, thanks. I'll get to this soon.

**Comment by argiepiano** [comment]
@kiamlaluno & @quicksketch: I've made the changes re: javascript links. I also added a check for null paths, since PHP 8.1 throws a warning when running `strtolower(NULL)`. Backdrop does a few `l('my text', NULL);` in a few places such as in `comment_reply()`.

I also added the test for javascript links. 

Ready for review and testing.

**Comment by kiamlaluno** [comment]
The MR handles the exception list and it also tests the strings in the exception list are not sanitized. It also avoids to pass `NULL` to `check_url()`.

From a visual review, the code is good to go.

**Comment by bugfolder** [comment]
Tested using Scenario 1 (from the first comment), with this build element:

```
  $build[] = array(
    '#type' => 'help',
    '#markup' => l('link', "javascript:alert('XSS')", array('external' => TRUE)),
  );
```

Clicking on the link brings up the expected JS alert.

After applying the patch, the link HTML is

```
<a href="alert('XSS')">link</a>
```

Which gives a 404, which is innocuous. So, WFM.

Two small code suggestions in the PR (flagged by PHPCS).

**Comment by argiepiano** [comment]
Changes committed. WE have a spelling test failure (didn't know we checked spellings?), which is flagging words like `mllid` (?) plus some real misspellings that are not in this pr. Also our "old friend" failure `testLanguageUpgrade` which is unrelated to this PR.

**Comment by bugfolder** [comment]
I fixed the "pageviews" spelling complaint in another PR (that I think is RTBC, but can't be bothered to look it up). But yeah, all those "mlid"-type CSPELL complaints are gonna get old pretty quickly.

Anyhow, WFM, LGTM, and RTBC.

**Comment by quicksketch** [comment]
Thanks folks! Glad to get this one in. I merged https://github.com/backdrop/backdrop/pull/4332 into 1.x and 1.26.x.

https://github.com/backdrop/backdrop/commit/72af64c412420b89342dc03830c967684693017a by @argiepiano, @kiamlaluno, @bugfolder, @klonos, @BWPanda, and @quicksketch.

Port of Drupal issue #2990723 by poker10, tatarbj, DamienMcKenna: Security improvement for l() function.
