### ISSUE TITLE
Resolve conflicting layout style sheet names

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#597]
Right now we have a little problem in that all the layout style sheet names are `layout.css`. This means that if you include a style sheet in your theme with the name `layout.css` it will override the layout stylesheet (bad news).

It also means that if you wanted to override a layout style sheet intentionally, you'd have to name yours `layout.css` and that would override all layout style sheets (which ever was being used at any given time) and not one in particular.

To fix this we need to rename each layout style sheet to include the name of the layout, for example:

```
/core/layouts/one_column/one-column.css
/core/layouts/three_three_four_column/three-three-four-column.css
/core/layouts/two_column/two-column.css
/core/layouts/two_column_flipped/two-column-flipped.css
```

**Comment by serundeputy** [comment]
is this referring to for example:
`/backdrop/core/themes/bartik/css/style.css`
?

**Comment by quicksketch** [comment]
Hm, I think Jen meant "layout.css" not "style.css". With all layouts having the same stylesheet name (e.g. `/core/layouts/two_column/layout.css`) if you provided a `style.css` in your theme, it would override *all* the layout.css files on your entire site.

**Comment by jenlampton** [comment]
Yes, that's exactly what I meant.  Sorry for the confusion, updating issue summary now...

**Comment by quicksketch** [comment]
Thanks @serundeputy for fixing this one! Merged manually in https://github.com/backdrop/backdrop/commit/0d3b5605aa742e1322bcb06f8db39fad385caeb1.
