### ISSUE TITLE
Username enumeration via password reset URL

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5971]
I found [this issue](https://www.drupal.org/project/drupal/issues/2828724) in Drupal's issue queue and discovered that Backdrop has the same problem. Since it's already public on D.org, and since [username enumeration isn't considered a security issue in Backdrop](https://github.com/backdrop/backdrop-issues/issues/4696), I'm posting this here instead of the security queue.

The issue is that if you access a password reset URL for any user ID, when logged in as another user, you'll see the username matching the user ID. For example:

![image](https://user-images.githubusercontent.com/2385329/218252777-dd82770b-1cfc-4a2b-981c-30d36015be69.png)

More background about this particular problem can be found in the Drupal issue, and a discussion about username enumeration security/privacy concerns can be found in #4696.

The thing some people took issue with about the #4696 suggestion is that the inconvenience of the solution apparently outweighs the benefit. What makes *this* issue different, however, is that I don't see any downside to fixing this. There's no real need/benefit of mentioning the username of the user you're trying to reset the password for. We could simply change this message to something like:

> You cannot use a password reset link while logged into the site. Please logout and try using the link again.

**Comment by BWPanda** [comment]
PR: https://github.com/backdrop/backdrop/pull/4333

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...I agree on all points 👍🏼 

The code in the PR looks good, but there's a random failure. Can you please try closing/waiting/reopening?

Also tested this in the PR sandbox vs a demo instance of Backdrop, and things work as expected, without exposing any user information, so WFM 👍🏼

**Comment by BWPanda** [comment]
Thanks @klonos, tests all passing now.

**Comment by kiamlaluno** [comment]
*You cannot use a password reset link while logged into the site. Please logout and try using the link again.* makes more sense than the currently used message, at least for me, who does not share the computer with other people, nor let another person use my account on a site.

The currently used message seems to assume that the person who is trying to use the reset link used a browser where another person was logged in, or that person has two accounts on that site. (I am not sure those are the most common cases.)

**Comment by hosef** [comment]
Thanks you @BWPanda  and @klonos! I have merged this into 1.x and 1.24.x.

**Comment by jenlampton** [comment]
Kudos on also removing more instances of "User" where we meant "person". This is a nice improvement.
