### ISSUE TITLE
Devel Subthemer doesn't use the themes/custom directory.

### ISSUE THREAD

**Issue by leeksoup** [backdrop/backdrop-issues#5978]
## Description of the bug

Devel Subthemer doesn't use the themes/custom directory.

## Steps To Reproduce

To reproduce the behavior:
1. Go to ''admin/config/development/devel-subthemer"
2. Give your new subtheme a name and choose a base theme. Check stuff you want to copy / customize.
3. Click "Create subtheme."

## Actual behavior

Describe what was the result of following the steps above. Add screenshots if
you think they would help.

The Devel Subthemer module tries to add the custom theme to the themes/ directory instead of the themes/custom/ dir. 
It does find the base theme under themes/contrib/ though.

## Expected behavior

Describe what you expected to happen instead.
Add mockup screenshots if possible.

If the site has the themes/custom/ (and/or themes/contrib) dir this module should try to make the subtheme within that directory and not simply under themes/

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.24
- Web server and its version: Apache httpd 2.4.54
- PHP version: 7.4
- Database sever (MySQL or MariaDB?) and its version: 15.1 
- Operating System and its version: Fedora 35
- Browser(s) and their versions: Brave 1.46.144

**Comment by klonos** [comment]
@leeksoup this issue queue is reserved only for core issues, whereas the one you are reporting is related to a contrib module. In those cases, you need to file an issue in the respective issue queue.

So can you please copy/paste this in a new issue in https://github.com/backdrop-contrib/devel_subthemer/issues? Thanks.

Closing this one here.

**Comment by leeksoup** [comment]
@klonos - Sorry! Will do!
