### ISSUE TITLE
Token browser: Explicitly set the `stringCollapse` and `stringExpand` settings and pass them through `t()` to allow for them to be translated

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5986]
The jQuery treetable plugin allows for `stringCollapse` and `stringExpand` as settings(*), which can be customized. The default strings for them are "Collapse" and "Expand" respectively, and these are fine - they cannot be translated though, so we should be setting them explicitly in `core/modules/system/js/token.js` and pass them through `Backdrop.t()` to allow for that.

*See: http://ludo.cubicphuse.nl/jquery-treetable for details.

**Comment by klonos** [comment]
Quick PR: https://github.com/backdrop/backdrop/pull/4348

**Comment by bugfolder** [comment]
Tested this. Just to confirm that the tooltips were being set by this PR, I installed Token Help (to easily get the token tree), then changed the translated names and after clearing cache and refreshing the browser, the altered text showed up in the tooltip, as expected. So WFM. Also reviewed the code, LGTM.

RTBC.

**Comment by klonos** [comment]
Thanks @bugfolder 🙏🏼 

The branch could cleanly be rebased w/o conflicts, so I've done that in order to get a fresh sandbox going. The usual test and cspell gremlins showed up.

**Comment by quicksketch** [comment]
Thanks @bugfolder and @klonos! I merged https://github.com/backdrop/backdrop/pull/4348 into 1.x and 1.26.x.
