### ISSUE TITLE
The great Backdrop spell check!

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#5987]
Backdrop has quite a few spelling mistakes/typos. Let's fix them!

---

When I saw a typo in core while working on another issue, I wondered how long it'd been there. Git Blame pointed to Drupal, where I noticed it'd since been fixed as part of a larger issue to fix lots of spelling mistakes. I then wondered how many Backdrop had...

After doing some research, I came across the [`cspell`](https://cspell.org/) command-line tool which looked promising. So I setup a local Lando env. where I installed cspell and configured it to run against all of core. After *much* configuring and tweaking, I finally got the following:

- A PR of fixed typos in core (see below)
- A cspell config file that:
  - Uses Drupal's own cspell dictionary
  - Uses a bunch of other dictionaries
  - Uses a custom dictionary for Backdrop
  - Ignores certain files/folders (e.g. SVG files, core's included transliteration directory, etc.)
  - Ignores specific words in specific files (e.g. `dont` is considered a typo in most of Backdrop, except `core/modules/simpletest/tests/session*` files where it's used in a variable name and hence can't have an apostrophe, so it's legitimate there)
- A custom Backdrop dictionary that includes ~550 words included in Backdrop core that aren't typos but aren't recognised by any of the other dictionaries

Only later did I find [this issue](https://github.com/backdrop/backdrop-issues/issues/5811) to add cspell as a GH automation for PRs (that's what led me to Drupal's dictionary). So I'll likely go and post my cspell files there and try to get that moving next, but for *this* issue let's just fix all the typos in core in bulk before adding an automation.

The below PR mostly fixes documentation typos (comments, docblocks, etc.), but there are also some typos in code (`*.api.php` files, strings shown to the user, and even variable/function/class names). For the latter, I checked each instance and determined that it didn't really constitute an API change to fix (most were only used in tests anyway), so I went ahead with including them here. But happy for others to review and provide feedback in that regard.

**Comment by BWPanda** [comment]
Thanks for the review @kiamlaluno! I've updated the PR. Tests are now passing, except I think I broke `phpcs`...

**Comment by kiamlaluno** [comment]
Tests pass; `phpcs` seems to fail because the list of changed files is long. It happened with a PR I provided too.

To me, this is good to go. It also fixes some code bugs, including the code that calls  `$config->get('defaut_node_type')` instead of `$config->get('default_node_type')`.

**Comment by klonos** [comment]
I also had a round, and left multiple comments/suggestions. There were many instances of words with `un` or `re` or `pre` etc. prefixes that were legit and need not be changed. If cspell complains, then we should add these to the dictionary, and/or try to fix them upstream

**Comment by BWPanda** [comment]
Thanks @klonos! I've updated the PR based on your feedback.

**Comment by klonos** [comment]
Thanks again @BWPanda 🙏🏼 ...I'm happy with the replies to some of my suggestions 👍🏼 

@jenlampton and @stpaultim (or anyone else) perhaps we can have another 1 or 2 pair of eyes on this and then wrap it up? (especially since it is also fixing some in-code misspellings of variables and function names). It's a lot of changes, but I believe that I've done a very through checking on my end, and it only took me about 5-10min - it's just that I'm not a native English speaker, so this could use some (American) English 👀

**Comment by jenlampton** [comment]
This is fantastic! Some of these are real head-slappers. I see that the PR is in a near-ready so already has a milestone :) I'll let someone else RTBC since I'm so bad with spelling, but LGTM.

**Comment by bugfolder** [comment]
I've reviewed and made some further suggestions. (I love all the varied ways of spelling "correctly"!)

**Comment by BWPanda** [comment]
Thanks @bugfolder and @jenlampton. PR updated with fixes from PR review.

**Comment by klonos** [comment]
@bugfolder @BWPanda I've left a suggestion (x3) to use "whether" instead of asking questions in the comments.

Also a question re "run" vs "ran", and perhaps consider using alternative verbs for that specific context.

Let me know what you guys think.

**Comment by BWPanda** [comment]
@klonos It looks like you must have commented in 'resolved' reviews. Since they're all collapsed for me, I'd have to expand each one to see where you posted (and there are over 50 of them!)

Are you able to 'unresolve' the ones where you commented so we can find them?

**Comment by bugfolder** [comment]
I've commented further (I agree with the use of "Whether", and have made further suggestions). Here's links to the comments; I see them as unhidden, don't see an option to unresolve. ☹️

https://github.com/backdrop/backdrop/pull/4349#discussion_r1116811106
https://github.com/backdrop/backdrop/pull/4349#discussion_r1116811881
https://github.com/backdrop/backdrop/pull/4349#discussion_r1116812797

**Comment by klonos** [comment]
Ditto. No option to un-resolve resolved discussions. Sorry 🤷🏼

**Comment by klonos** [comment]
...but yes, your suggestions seem good to me @bugfolder 👍🏼 

@BWPanda last round of fixes, and I think that this is good to go. Enough 👀 had a chance to review, and we've scrutinised things enough I believe 😓

**Comment by BWPanda** [comment]
Thanks guys. PR updated.

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...I'll go ahead and mark this RTBC. I don't think that there's anything to test.

**Comment by quicksketch** [comment]
Thanks everyone! I merged https://github.com/backdrop/backdrop/pull/4349 into 1.x and 1.24.x (no conflicts). Lovely!
