### ISSUE TITLE
Remove any reference to the theme process layer from theme() documentation

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#5990]
[The theme process layer has been removed from Backdrop](https://docs.backdropcms.org/change-records/removed-the-theme-process-layer), but the documentation for [`theme()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21theme.inc/function/theme/1) still contains references to `MODULE_process()` and `MODULE_process_HOOK()`, when those theme process layer functions are not invoked anymore.

Any reference to process layer functions should be removed from that documentation page.

**Comment by kiamlaluno** [comment]
I re-synchronized the PR.

**Comment by kiamlaluno** [comment]
The failing check is for the words used in CKEditor 5 files.

**Comment by klonos** [comment]
Thank you @kiamlaluno for catching this 🙏🏼 ...I've left a comment for a small nit in the PR.

Also, can we please add an `@since` at the very end of the docblock? Something along these lines:
```php
 * @see hook_theme()
 * @see template_preprocess()
 *
 * @since 1.0.0 Theme process layer (hook_process() and hook_process_HOOK()) removed. See https://docs.backdropcms.org/change-records/removed-the-theme-process-layer
 */
function theme($hook, $variables = array()) {
```

**Comment by kiamlaluno** [comment]
I updated the PR.

**Comment by herbdool** [comment]
LGTM

**Comment by quicksketch** [comment]
Thank you @avpaderno, @klonos, and @herbdool! I merged https://github.com/backdrop/backdrop/pull/4350 into 1.x and 1.28.x.
