### ISSUE TITLE
Remove the (unnecessary) return statements from `hook_form_FORM_ID_alter()` implementations in System module.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#5994]
There are two `hook_form_FORM_ID_alter()` implementations in the system.module file. Both the implementations return `$form`, which is useless, since `$form` is a parameter those hooks gets by reference.

### [`system_form_user_register_form_alter()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_form_user_register_form_alter/1)

```php
function system_form_user_register_form_alter(&$form, &$form_state) {
  $config = config('system.date');
  if ($config->get('user_configurable_timezones') && $config->get('user_default_timezone') == BACKDROP_USER_TIMEZONE_SELECT) {
    system_user_timezone($form, $form_state);
    return $form;
  }
}
```

### [`system_form_user_profile_form_alter()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_form_user_profile_form_alter/1)

```php
function system_form_user_profile_form_alter(&$form, &$form_state) {
  if (config_get('system.date', 'user_configurable_timezones')) {
    system_user_timezone($form, $form_state);
  }
  return $form;
}
```

`return $form` must be removed from those functions.

**Comment by klonos** [comment]
@BWPanda @indigoxela wondering if that is something that PHPCS or some other GHA can pick 🤔

**Comment by indigoxela** [comment]
> @BWPanda @indigoxela wondering if that is something that PHPCS or some other GHA can pick

@klonos for sure not PHPCS, which only covers coding standards. Even PHPStan couldn't catch that easily, I guess. :wink:

**Comment by kiamlaluno** [comment]
I tried the following code on https://phpstan.org/try, and it did not report any error. (I know, the example is not much about Backdrop. 😅)

```php
class HelloWorld
{
	/**
	 * @param array<string, int> $form
	 *
	 * @return array<string, int>
	 */
	public function setHidden(array &$form): array
	{
		$form['hidden'] = 120;
		return $form;
	}
}
```

**Comment by klonos** [comment]
Right. PHPStan is what I was thinking. Never mind then.

**Comment by BWPanda** [comment]
Thanks @kiamlaluno and @klonos! I've merged https://github.com/backdrop/backdrop/pull/4353 into 1.x and 1.24.x.
