### ISSUE TITLE
Add a link to the `$_SESSIONS` documentation from the documentation in `sessions.inc`.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#5998]
This is a follow-on to an issue on the docs site (H/T @yorkshire-pudding):

https://github.com/backdrop-ops/docs.backdropcms.org/issues/212

We could address it by adding an @see link to the PHP predefined variables page, to clarify, where `$_SESSION superglobal` is mentioned in docblocks.

PR to follow.

**Comment by yorkshire-pudding** [comment]
Good idea @bugfolder

**Comment by klonos** [comment]
Indeed! Thanks @bugfolder and @yorkshire-pudding 🙏🏼

**Comment by quicksketch** [comment]
Thanks folks! Merged https://github.com/backdrop/backdrop/pull/4363 into 1.x and 1.24.x.
