### ISSUE TITLE
Document `$require_settings` for `find_conf_path()`.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6002]
[`find_conf_path()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/find_conf_path/1) accept `$require_settings` as last parameter, but that parameter is not documented.
From [`conf_path()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/conf_path/1), the function that calls `find_conf_path()`, that description could be  the following one.

> bool $require_settings: Only configuration directories with an existing [settings.php](https://docs.backdropcms.org/api/backdrop/settings.php/1) file will be recognized. Defaults to TRUE. During initial installation, this is set to FALSE so that Backdrop can detect a matching directory, then create a new [settings.php](https://docs.backdropcms.org/api/backdrop/settings.php/1) file in it.

Alternatively, it can be slightly simplified to:

> bool $require_settings: Only configuration directories with an existing [settings.php](https://docs.backdropcms.org/api/backdrop/settings.php/1) file will be recognized. Defaults to TRUE.

It should not be necessary to repeat that, on initial installation, the function is called with `$require_settings` set to `FALSE`.

**Comment by kiamlaluno** [comment]
A test is failing, but it is not related to these changes.

```none
Image: Image style flood protection (ImageStyleFloodProtection)

Status    Group      Filename          Line    Function
--------------------------------------------------------------------------------------------
Fail      Other      image.test        1883    testFloodProtection()
    Correct number of images (2) generated.
Error: Process completed with exit code 1.
```

**Comment by kiamlaluno** [comment]
I closed and re-open the PR. Now the tests do not return failures.

**Comment by kiamlaluno** [comment]
I re-based the PR, which was 30 commits behind.

**Comment by klonos** [comment]
Thanks @kiamlaluno and sorry for taking so long to review this simple documentation change. Looks good to me 👍🏼

**Comment by quicksketch** [comment]
Thanks @kiamlaluno and @klonos! Merged https://github.com/backdrop/backdrop/pull/4368 into 1.x and 1.24.x.
