### ISSUE TITLE
Default image on localized site not removable from image field

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#6003]
## Description of the bug

On a localized site it's not possible to remove a default image from an image field, unless you switch the interface to English.

## Steps To Reproduce

1. On a vanilla Backdrop site, enable the modules "Language" and "Locale".
2. Add a language, e.g. Spanish.
3. Import the translation set, e.g. https://localize.backdropcms.org/translate/languages/es.
Or translate the string "checkbox" into Spanish, making sure it's not "checkbox".
5. Run cron and clear caches.
6. Make sure to access the next pages with `/es/` in the URL.
7. Edit the Image field for the Post content type, add a default image, and save the content type.
8. Edit the field again, and try to remove the default image.

## Actual behavior

The checkbox to remove the default image field is missing, i.e. there is no option to remove the image.

## Expected behavior

There should be a checkbox called "Remove default image", see screenshot:

<img width="549" alt="screen-default-image-remove" src="https://user-images.githubusercontent.com/14188307/221698640-872b28ad-6d94-4e69-84f3-6f4d176cbe75.png">

## Additional information

The checkbox is there, when you switch the interface language to English.

System information:
- Backdrop CMS version: 1.24.0 (Tugboat demo)
- Web server and its version: Apache/2.4.54
- PHP version: 7.4.33

**Comment by olafgrabienski** [comment]
As pointed out by @indigoxela and @bugfolder in [Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Remove.20default.20image/near/338357559), there are two instances of `'#type' => t('checkbox')` in `image.field.inc`:

- https://github.com/backdrop/backdrop/blob/d688729ab0b31a1f0d16d0af33c97807cfad61e4/core/modules/image/image.field.inc#L71
- https://github.com/backdrop/backdrop/blob/d688729ab0b31a1f0d16d0af33c97807cfad61e4/core/modules/image/image.field.inc#L198

The term "checkbox" shouldn't go in `t()`, so the fix for both lines should be:

`-`  `'#type' => t('checkbox'),`
`+` `'#type' => 'checkbox',`

If nobody beats me to it, I'll provide a PR in the next days.

**Comment by argiepiano** [comment]
WFM!

**Comment by BWPanda** [comment]
Looks good to me. I searched and couldn't find any other instances of translated form element types in core, so this looks good to go.

**Comment by BWPanda** [comment]
Thanks @olafgrabienski, @klonos and @argiepiano! I've merged https://github.com/backdrop/backdrop/pull/4371 into 1.x and 1.24.x.
