### ISSUE TITLE
Impossible to disable user pictures

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#601]
To reproduce: 
1) Navigate to `admin/config/people/settings`
2) uncheck the box for `Enable user pictures.`
3) Save the form.

When the page reloads you'll see that the pesky box is checked again.

**Comment by quicksketch** [comment]
Nice catch! Looks like we might need to save dimensions, directory, and image style size for profiles as well?

**Comment by jenlampton** [comment]
All fixed in the PR ;)

**Comment by quicksketch** [comment]
Excellent, thanks!
