### ISSUE TITLE
Breadcrumbs and status messages overlap in Bartik theme

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#602]
![overlap](https://cloud.githubusercontent.com/assets/397895/5791508/ead01bf2-9e8e-11e4-9526-e6c33471e537.png)

In the Bartik theme the status messages overlap the breadcrumb.

**Comment by quicksketch** [comment]
This is probably our fancy flexbox CSS (that pushes down the footer) that is responsible for this. I bet we don't have the "top" section specified as not-stretchable.
