### ISSUE TITLE
Cleanup `diff.inc` Doxygen documentation

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#6026]
The [`diff.inc` file](https://github.com/backdrop/backdrop/blob/1.x/core/includes/diff.inc) has a few issues with its Doxygen documentation we could fix:

- `@file` tag isn't at the top of the file docblock
- `@ingroup` in file docblock doesn't make sense (as the group hasn't been defined yet)
- `@defgroup` group description is the same as the group's name (`DifferenceEngine`, so superfluous)
- `@private` tags aren't used anywhere else in core (remove)
- Adding `@ingroup` to each class in the file is pointless - we can just wrap the whole file in a proper `@defgroup` declaration instead:
  ```php
  /**
   * @defgroup DifferenceEngine
   * @{
   */

  // File contents...

  /**
   * @} End of "defgroup DifferenceEngine".
   */
  ```

**Comment by klonos** [comment]
Thanks @BWPanda 🙏🏼 ...RTBC 👍🏼

**Comment by quicksketch** [comment]
Merged into 1.x and 1.24.x. Thanks @BWPanda and @klonos!
