### ISSUE TITLE
[DX] FAPI improvements follow-up to the addition of the `#indentation` property

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6028]
This is a follow-up + cleanup issue for #5999, which also slightly improves/optimizes things in certain aspects. The changes I am proposing are not all related directly to the change that went in with that issue, rather than cleaning up things I came across while fiddling in my local for a possible PR for that issue. I just wouldn't want these to be lost.

Suggested changes:
- Add attributes like `selected` and `value` to select elements properly (via `backdrop_attributes()`)
- Add an `indent` class, to allow targeting all indented elements en masse.
- Add a `data-indentation-depth` attribute to the same form elements that received the `form-item-indentation-*` class (this is the follow-up bit actually relevant to #5999). Since the current solution was based on CSS classes, it is limited to only handling indentation depths from 0 to 5, which is not as robust. I'm hoping that the addition of this new `data-*` attribute, which holds the indentation depth as its value, can be used by contrib and custom code to provide a better solution for indentation, either based on custom JS, or in core in the future (when there's better browser support for CSS calculations that include `data-*` attributes).

This issue is hard to describe - better provide a PR for it so that people can see it in code...

**Comment by klonos** [comment]
PR up for testing/review: https://github.com/backdrop/backdrop/pull/4381

To test things, you can use the same test module @argiepiano provided in #5999 (thank you 🙏🏼 ):
- Copy this link: [testing_stuff.zip](https://github.com/backdrop/backdrop-issues/files/10903865/testing_stuff.zip)
- Go to "Functionality -> Install new modules -> Manual installation"
- Paste the link in the "Install from URL" field.
- Click "Install"
- Head to the modules listing page, and enable the "Testing stuff" module
- Navigate to `admin/test-indentations` to test output of various indented form elements, and inspect their markup.

Special ping to @argiepiano and @bugfolder since you have the most context and were heavily involved in the PR/review of #5999.

**Comment by quicksketch** [comment]
Code review of this looks good to me. The `#indentation` property was only added in 1.x though, so this doesn't need to be in the bug fix release, I do agree these would be nice to have in 1.25.0 though.

**Comment by argiepiano** [comment]
> Special ping to @argiepiano and @bugfolder since you have the most context and were heavily involved in the PR/review of https://github.com/backdrop/backdrop-issues/issues/5999.

I'll do another test/review soon.

**Comment by klonos** [comment]
I've rebased the PR and changed the `indent` CSS class to `indentation`, as per @quicksketch's feedback when he reviewed it quickly during the dev meeting earlier today.

**Comment by quicksketch** [comment]
I gave this another review and it looks ready to go! I merged https://github.com/backdrop/backdrop/pull/4381 into 1.x for 1.25.0. Thanks @klonos!

**Comment by klonos** [comment]
FTR: these changes lay the groundwork for this follow-up: #6085

**Comment by argiepiano** [comment]
> Add an `indent` class, to allow targeting all indented elements en masse.

In fact the class added in this PR was `indentation`, which already existed in Backdrop for a completely different purpose. Adding this css class broke the `#indentation` feature. See #6090 and the linked PR there.
