### ISSUE TITLE
[DX] Convert node_build_content() into a wrapper for $node->buildContent()

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6033]
While working on https://github.com/backdrop/backdrop-issues/issues/5181 I noticed that the only thing in core that still uses `node_build_content()` is search module. Everything else uses `$node->buildContent` instead.  

I wonder if we can safely convert `node_build_content()` into a wrapper function for `$node->buildContent()`?

**Comment by herbdool** [comment]
I'm not sure what you mean. This is what `node_build_content` looks like currently - it's already a wrapper:

```
function node_build_content(Node $node, $view_mode = 'full', $langcode = NULL) {
  $node->buildContent($view_mode, $langcode);
}
```

Or do you mean changing `search.views.inc`  from `$node = node_build_content($node, FALSE, FALSE);` to `$node->buildContent($node, FALSE, FALSE)`
