### ISSUE TITLE
Fixed: EntityReference invokes deprecated Drupal function instead of Backdrop alternative.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6036]
## Description of the bug

Method `EntityReferenceSelectionHandlerGeneric_user::entityFieldQueryAlter`, which is part of core's Entity Reference module, makes a call to the deprecated Drupal 7 function `format_username()`. This is usually not a problem, unless you have turned off `backdrop_drupal_compatibility` in `settings.php`. Then you get a fatal error, `Call to undefined function format_username()`

## Steps To Reproduce
1. Enable Entity Reference
2. Turn off Drupal compatibility by editing, in`settings.php`:

`$settings['backdrop_drupal_compatibility'] = FALSE;`

3. Add an entity reference field to the `page` content type
4. In "Target type" select `User account`
5. Save the field

## Actual behavior

Fatal error: `Call to undefined function format_username() in EntityReferenceSelectionHandlerGeneric_user->entityFieldQueryAlter() (line 432 of /Users/XXX/Sites/localhost/bdtesting/core/modules/entityreference/plugins/selection/EntityReferenceSelectionHandlerGeneric.inc).`

## Expected behavior

Saving the field should not throw the error.

## Additional information

Obviously a workaround is to turn Drupal compatibility back on.

But a better solution is to avoid using `format_username()`. The Backdrop equivalent is `user_format_name()`

- Backdrop CMS version: 1.24.1
- PHP version: 7.4

====
PR https://github.com/backdrop/backdrop/pull/4388

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4388 ready for review and testing.

**Comment by klonos** [comment]
Thanks @argiepiano 🙏🏼 ...good catch 👍🏼 

Simple on-line fix, which I've tested on my local and confirmed that it fixes the problem.

**Comment by herbdool** [comment]
Good catch @argiepiano. I'm thinking we should have an automated test which disables the compatibility layer to catch things like this. Or disable it for all tests.

**Comment by klonos** [comment]
> ... Or disable it for all tests.

Follow-up here: #6037

**Comment by quicksketch** [comment]
Merged into 1.x and 1.24.x. Thanks @argiepiano, @herbdool, and @klonos!
