### ISSUE TITLE
Compatibility: locale_language_list() removed, no real equivelant

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#604]
Prior to our fork, `locale_language_list()` was removed.

Drupal.org issue: https://www.drupal.org/node/1387608
Changelog: https://www.drupal.org/node/1414264

Although it was described as though these two functions were redundant, locale_language_list() had the helpful ability to return an array suitable for use in a select list. There is no equivelant function in Backdrop as far as I can tell, so you have to use `language_list()` and then loop over the results to construct a langcode => name array for use as a #options value.

At the very least, we should make a way to construct the options list as before. The old function `locale_language_list()` might be restored to it's previous position, or relegated as `@deprecated` to `drupal.inc`.

**Comment by quicksketch** [comment]
I copied the change notice from drupal.org over to https://api.backdropcms.org/node/29321 and added a note about this shortcoming.

**Comment by quicksketch** [comment]
> At the very least, we should make a way to construct the options list as before. The old function locale_language_list()

My preference would be to add an additional argument to `language_list($only_enabled = FALSE)` for `$option_list = FALSE` that can be set to `TRUE` to get a list of options instead of objects.

**Comment by quicksketch** [comment]
With only a week until release, we might not be able to finish this issue. However, it's trivial to implement, so perhaps there's still a chance. I'll leave this open for a few days more, but this issue is relatively low priority.

**Comment by serundeputy** [comment]
I don't know how to test this but I gave it a shot: https://github.com/backdrop/backdrop/pull/897
:8ball:

**Comment by quicksketch** [comment]
Thanks @serundeputy! I think we could start using this in a few places where we're calling `language_list()` and looping through them.

It also looks like the `$is_enabled` parameter may not be taken into account when returning a option list array.

**Comment by serundeputy** [comment]
updated for coding standards and `$only_enabled`
rebased.

**Comment by quicksketch** [comment]
Thanks @serundeputy! I amended the PR with a few places that can use the new parameter and ensured they worked properly. Filed a new PR at https://github.com/backdrop/backdrop/pull/909.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/909.

**Comment by quicksketch** [comment]
Added a change notice: https://api.backdropcms.org/node/43070
