### ISSUE TITLE
Fixed: Message type not set properly for deprecated system message.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6041]
This is a small bug:

```
backdrop_set_message(t('Settings not saved: Drupal compatibility layer is disabled and this form has not been updated to use Backdrop configuration management.', 'error'));
```

should have the message type set outside of `t()`:

```
backdrop_set_message(t('Settings not saved: Drupal compatibility layer is disabled and this form has not been updated to use Backdrop configuration management.'), 'error');
```

**Comment by kiamlaluno** [comment]
Good catch!  
`format_string()` should log *Invalid argument supplied for foreach()* warnings, but those go easily unnoticed, especially because it is a single warning that happens when the compatibility layer is disabled and the form does not use the configuration management.

**Comment by kiamlaluno** [comment]
Are there tests for a form that does not use the configuration management when the Drupal compatibility layer is disabled? Should those tests be added, if there are not tests for that case?

**Comment by herbdool** [comment]
That's a good question @kiamlaluno. This might be there only such form in core and it doesn't do much. I'd lean towards not writing a test for this but perhaps I'm just being lazy.

Would you be willing to update the labels on this issue if you've reviewed and tested it?

**Comment by kiamlaluno** [comment]
I only checked the change done in the PR. I did not test it, as I do not know how to disable the compatibility layer on the PR preview.

**Comment by argiepiano** [comment]
I've tested and reviewed the code. WFM and RTBC.

**Comment by quicksketch** [comment]
The PR looks good. @herbdool could you move the PR to be against the core repository? Right now it's against your personal fork.

**Comment by herbdool** [comment]
@quicksketch oops! Should be fixed now.

**Comment by quicksketch** [comment]
Thanks! Merged https://github.com/backdrop/backdrop/pull/4396 into 1.x and 1.24.x.
