### ISSUE TITLE
Docblocks updated with Proper @return statements.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6042]
My IDE complains about the `execute()` method a lot about it being undefined:

![Screenshot from 2023-03-27 11-29-43](https://user-images.githubusercontent.com/1071483/228053383-20d6927a-97ec-469f-bbdf-ba9b1a3822b7.png)

Turns out it's because some of the methods in `SelectQuery` (such as `range()` and `orderBy()`) don't have proper `@return` statements. Plus I found a couple other instances in the code.

**Comment by herbdool** [comment]
There are a bunch more functions in the database classes that are missing return statements but this is a start.

**Comment by argiepiano** [comment]
Great! This fixed it for me to. Wondering if you may want to fix a few remaining ones?

- `image_filter_keyword()`
- `installer_browser_get_sort_options()`
- `Block::getChildren()`
- `LayoutMenuitem::getContexts()`

**Comment by herbdool** [comment]
@argiepiano I think I've got them all now.

**Comment by argiepiano** [comment]
LGTM

**Comment by quicksketch** [comment]
Love it. Merged https://github.com/backdrop/backdrop/pull/4392 into 1.x and 1.24.x. Thanks @herbdool and @argiepiano!
