### ISSUE TITLE
Fixed: Adjust autocomplete dropdown positioning on iPad and iPhone.

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#6050]
## Description of the bug

On iPads and iPhones, the dropdown menu for an autocomplete path doesn't always appear under the field, and if you scroll the image, the dropdown menu moves twice as fast as the scrolling, so that even if it started out appearing in the right place, it moves to the wrong place.

This behavior happens on iPad and iPhone in Safari and Chrome, but it does not manifest on desktop, even when using Safari's Developer tools to emulate an iPad or iPhone screen size.

## Steps To Reproduce

To reproduce the behavior:

Go to any Backdrop site that has an autocomplete field. You need to be able to access the site with an iPad or iPhone. In the example below, I'm visiting b.org.

Find a field that has an autocomplete path. A core example is to edit a menu link, at admin/structure/menu/item/NNN/edit. The Path field is an autocomplete. Type in a character, watch the menu appear, and then try scrolling while the menu is visible.

## Actual behavior

Here's an example (editing a menu item) on iPhone. Note that the autocomplete menu completely covers up the field that it's matching to.

![IMG_7437](https://user-images.githubusercontent.com/29214084/230798974-1ed2b0d8-63be-40fb-a071-d9c4b2ae8eb3.jpeg)

Here's an example on iPad:

![IMG_0049](https://user-images.githubusercontent.com/29214084/230798794-eeff6df5-b4c8-4512-837c-1b255c51c0b7.jpeg)

And here's a video of scrolling behavior on iPad:

https://user-images.githubusercontent.com/29214084/230798376-182fe93e-ec4e-4f0b-a3b7-d05398635dc5.mov

Not shown here, but if the autocomplete field is lower on the page so that when you start typing the keyboard pops up and force-scrolls the window to keep the textfield visible, the autocomplete menu will be pushed so high that it's not even visible upon first appearance.

## Expected behavior

I'd expect the autocomplete menu to appear in the right place under all circumstances, and to work when one is scrolling the image.

## Additional information

Screenshots above are taken from b.org. The site where this first popped up used a Bootstrap Lite-based theme, but I've verified that the behavior happens across themes (e.g., also on Seven).

**Comment by bugfolder** [comment]
Attached is a simple module that demonstrates the behavior. Install the module, go to path `/ac-test`, and try out the autocomplete on iPad or iPhone. Looks like the relevant positioning code is in function `positionPopup()` in `core/misc/autocomplete.js`, but I don't see why it misbehaves on iOS.

[autocomplete_test.zip](https://github.com/backdrop/backdrop-issues/files/11203689/autocomplete_test.zip)

**Comment by bugfolder** [comment]
After some poking around (and finding a way to debug a local app on my iPad when the local version is running on a laptop), this seems to be related to weird things that iOS does when the soft keyboard appears. [There is some discussion here](https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d); a relevant comment is:

> position:fixed elements behave differently than otherwise positioned elements.

And this definitely seems the case, since the autocomplete menu is placed with position:fixed. For example, here's a screen shot of the iPad with the misplaced autocomplete menu. It's clearly very near the top of the visible viewport, as noted by the arrow:

![iPad web page annotated](https://user-images.githubusercontent.com/29214084/231336472-1285e351-fcde-47c9-be9e-5f313aa46abd.png)

But here's the exact same page in the web inspector. Note that the autocomplete supposedly has a `top` value of `191`. That's where it _ought_ to be on the web page, i.e., just below the text field; not at the top of the screen.

<img width="1358" alt="iPad web inspector annotated" src="https://user-images.githubusercontent.com/29214084/231336584-f34c3e5d-578d-4570-abdd-d4644696e1e5.png">

One would think that the web inspector and the web page would agree on something as fundamental as `position`.

**Comment by bugfolder** [comment]
So, some difference between D7 and B:

* B makes the autocomplete a child of `<body>`, and then positions it using `position: fixed` (which, per the information above, is problematic on iOS).
* D7 make the autocomplete a child of the `<div>` that wraps the corresponding `<input>`, and then positions it using `position: absolute`, which is (presumably) impervious (or at least less pervious) to iOS's shenanigans than `position:fixed`.

**Comment by bugfolder** [comment]
Looks like this problem appeared once before during some re-working of autocompletes:

https://github.com/backdrop/backdrop-issues/issues/2517#issuecomment-296025998

The `position:fixed` was introduced in the associated PR, https://github.com/backdrop/backdrop/pull/1840/files.

In that issue, they reported testing on "small screens", but I wonder if it included testing on actual devices with small screens, or just using the "simulate a small screen" developer tools on a laptop? With the latter, autocompletes work on an iPad-sized screen on a laptop, but fail on an actual iPad.

**Comment by bugfolder** [comment]
I can report that if I take the `autocomplete.js` file from D7, convert all `Drupal` to `Backdrop` and `drupal` to `backdrop`, and then add in the `position:absolute` CSS (which on D7 lives in a separate CSS file), and then use this to replace Backdrop's `autocomplete.js`, a plain vanilla autocomplete field works properly on iPad. Haven't checked it in modal dialogs, and it (of course) no longer includes the other B-specific changes, like `Backdrop.optimizedResize`, so I'm not suggesting a complete reversion. But it's an existence proof that the `position:absolute` approach seems to be robust against iOS's scrolling weirdness.

Modified autocomplete.js attached here:

[autocomplete.js.zip](https://github.com/backdrop/backdrop-issues/files/11222791/autocomplete.js.zip)

**Comment by quicksketch** [comment]
Based on my searching turning up results like https://medium.com/@im_rahul/safari-and-position-fixed-978122be5f29, my understanding is that Safari does not respect "position: fixed" once the keyboard is open. It instead freezes the position or starts treating it as "position: static" instead.

So following the advice there, if we switch to `position: absolute` instead, it should in theory work on Safari, since it's positioned based on the root of the body, rather than the position of the scrollbar. This requires that we manually reposition the popup when the the window scrolls if the popup is inside of another element that is fixed, like a modal window.

I filed a PR at https://github.com/backdrop/backdrop/pull/4404 that could use testing:

- Test opening a modal (like the link dialog in CKEditor) and autocomplete + scroll.
- Test on a normal autocomplete, such as in a normal link field placed on a node form + scroll.

**Comment by bugfolder** [comment]
Looks good, on laptop Safari, iPad, and IPhone. WFM, RTBC. (Wow, that was a lot simpler than i'd thought it would be!)
