### ISSUE TITLE
Fixed: "More" link on permissions page should toggle description.

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#6053]
## Description of the bug

I'm looking at the permissions page and many permissions have a "more" link, but when I click on it nothing happens. 

![image](https://user-images.githubusercontent.com/3144571/231412260-3d1dc2ef-cdfe-45ec-9bf5-e13b9a953eb5.png)

## Steps To Reproduce

To reproduce the behavior:
1. Go to permissions page
2. Click on any "More" link

## Actual behavior

Nothing happens.

## Expected behavior

I believe that I'm supposed to see additional information, but I'm not sure. 

## Additional information

I've tested this on a PR sandbox, a demo site on BackdropCMS.org, and a local test site I spun up on my desktop. It didn't work on any of them. 

I tested in Firefox and in Chrome. I'm using Linux.

**Comment by olafgrabienski** [comment]
Confirmed! I think, the "more" link was introduced in https://github.com/backdrop/backdrop-issues/issues/5536. A short screencast which shows it in action: https://github.com/backdrop/backdrop-issues/issues/5536#issuecomment-1062819640

**Comment by kiamlaluno** [comment]
I can confirm this happens on my site too, despite the description is present in the HTML markup.

```html
<div class="permission-warning-description" style="display: none;">Define custom content types and delete existing ones.</div>
```

I guess the JavaScript code that should reveal it does not work.

**Comment by quicksketch** [comment]
Looks like maybe the markup changed slightly on the permissions page? I adjusted the JS to target based on the table cell instead of using the description class: https://github.com/backdrop/backdrop/pull/4403

**Comment by stpaultim** [comment]
Works for me. 

Thanks @quicksketch for the quick PR.

**Comment by klonos** [comment]
Code looks good to me 👍🏼 ...marking this RTBC, however, wondering if we should adapt the JS (like this PR is doing) or adapt the markup (to match the other cases, and have consistency in both the JS used as well as the output markup).

**Comment by jenlampton** [comment]
> Code looks good to me 👍🏼 ...marking this RTBC, however, wondering if we should adapt the JS (like this PR is doing) or adapt the markup (to match the other cases, and have consistency in both the JS used as well as the output markup).

We should probably have a follow-up to discuss this...

**Comment by quicksketch** [comment]
I figured modifying the JS has the lowest possible impact, since modifying the markup might also affect CSS. But in any case, I went ahead and merged https://github.com/backdrop/backdrop/pull/4403 into 1.x and 1.24.x to solve the bug.
