### ISSUE TITLE
Views block info description text references `administer >> structure >> blocks`.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#606]
In the Views UI when you enter a admin title for a block, the description text reads:
```
This will appear as the name of this block in administer >> structure >> blocks.
```
This text should read:
```
This will appear as the name of this block when adding it to a layout at administer >> structure >> layouts.
```

**Comment by klonos** [comment]
Shouldn't we use capital case for menu/child names? So instead it should be:

```'#description' => t('This will appear as the name of this block when adding it to a layout at Administer >> Structure >> Layouts.'),```

Actually, we don;t have any "Administer" link/menu that I know of. The only thing available is the menu items in the admin bar, So even better:

```'#description' => t('This will appear as the name of this block when adding it to a layout at Structure >> Layouts.'),```

**Comment by jenlampton** [comment]
I'm not sure we want to provide a link here, the Views UI is easy enough to get lost in.  Let's do your second suggestion :)  ...  And, we should also maybe do a pass through all of core to make sure we don't reference Administration anywhere else.  but, maybe a separate issue for that one :)

**Comment by quicksketch** [comment]
I'm in favor of adding a link, even though it will take you away from the Views UI. Since the View is saved in-progress, I think it'd be most helpful/consistent to use the link instead of a path.

**Comment by klonos** [comment]
> I think it'd be most helpful/consistent to use the link instead of a path.

My thought exactly.

> we should also maybe do a pass through all of core to make sure we don't reference Administration anywhere else. but, maybe a separate issue for that one :)

Done.

**Comment by jenlampton** [comment]
I have been overruled.  Carry on! (and thank you) :)

**Comment by quicksketch** [comment]
Hm, this should be closed again I think. The followup is in https://github.com/backdrop/backdrop-issues/issues/627.
