### ISSUE TITLE
CSpell: skip checking the spelling in array keys

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6060]
@jenlampton in https://github.com/backdrop/backdrop-issues/issues/6047#issuecomment-1505673256:
> It would also be nice if it didn't check the spelling in array keys (have we discussed this already?). I'm getting failures for things that shouldn't necessarily need to be spelled correctly.

**Comment by klonos** [comment]
@jenlampton can you please provide links to any such failures?

**Comment by jenlampton** [comment]
I posted links in my comment and in the issue I created for it...  let me find them...

**Comment by klonos** [comment]
Thanks @jenlampton, but in that case I do not actually agree that we should be skipping checking array keys. For example, suppose that someone made a typo like `$form['hepltext']`. In that case, we'd want to catch that, so the actual solution would be to do one of the following things:
- add `helptext` to the cspell dictionary
- change the key to `$form['help_text']`

**Comment by bugfolder** [comment]
I'm in agreement that we should not skip checking array keys. If it woudn't break B/C, we should replace them with properly delimited keys, and if it would, we should add them to CSpell.

**Comment by quicksketch** [comment]
I agree here too. Let's close this then and continue fixing keys by naming them properly. Individual (or bulk) fixes can go in #6302.
