### ISSUE TITLE
Sanitize text format names in hint below editor

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6065]
## Description of the bug

The text format label is correctly sanitized on the text formats page, and in the select list on the `node/add` page, but in the hint below the text editor, it is not properly sanitized when the current text format changes. (In this scenario, the text is replaced by JavaScript).

## Steps To Reproduce

To reproduce the behavior:
1. create a new text format named `test<script>alert('XSS');</script>`
2. Go to the `node/add/page` page
3. Change the text format to your new one
  - Notice that in the select list the text is properly sanitized 👍🏼 
  - Notice that in the text filter wrapper summary, it is not 👎🏼

**Comment by jenlampton** [comment]
I pushed a PR for this that is ready for testing.

**Comment by bugfolder** [comment]
Tested. Verified the lack of sanitization before; verified that the code change fixes the problem. Code looks good. WFM, RTBC.

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/pull/4406 into 1.x and 1.24.x. Thanks!

Note that this issue is public and does not receive a CVE because any administrator that can configure a text format could easily allow Full HTML anywhere.
