### ISSUE TITLE
Mysterious right border showing on menu tabs sub-items

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#607]
![mysterious-right-border](https://cloud.githubusercontent.com/assets/397895/5791876/cebbbfa8-9eab-11e4-88db-f25556b26f32.png)

We seem to have accidentally added a right-border to the sub items of menu local tasks.  We'll need to remove these.

**Comment by klonos** [comment]
Offending code in ```/core/modules/system/css/system.theme.css``` @ line 404:

```
ul.secondary li {
  border-right: 1px solid #ccc; /* LTR */
  display: inline;
  padding: 0 1em;
}
[dir="rtl"] ul.secondary li {
  border-left: 1px solid #ccc;
  border-right: none;
  display: inline;
  padding: 0 1em;
}
```

We need to remove the ```border-right``` and ```border-left```.

**Comment by quicksketch** [comment]
Thanks @serundeputy for fixing this in https://github.com/backdrop/backdrop/issues/699!
