### ISSUE TITLE
Add caching to layout_get_layout_info()

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#608]
Right now on every page load, we're doing multiple calls to `backdrop_parse_info_file()` to parse the .info file of every layout available. On top of that, we're doing a full `backdrop_system_listing()` to recurse through every possible "layout" directory location on every page request.

**Comment by quicksketch** [comment]
![xhprof-layout-cache](https://cloud.githubusercontent.com/assets/100206/5791885/93554406-9eac-11e4-87e9-90ab2d7cf053.png)

**Comment by jenlampton** [comment]
nice one :)
