### ISSUE TITLE
Fix "Back to site" link does not respect selected language

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6080]
## Description of the bug

The recently added "Back to site" link doesn't respect the selected language. It sends you back to the English version of the previously viewed front-end page.

## Steps To Reproduce

1. Enable Locale and Language
2. Install a language, e.g. Spanish
3. Visit a node in Spanish, e.g. `es/posts/your-first-post`
4. Click any of the admin links in the admin bar, for example, "Appearance". This takes to you `es/admin/appearance/list`, which is the expected behavior 👍🏽 
5. Then click "Back to site". You are taken to the English version of the page  at `posts/your-first-post` (notice, no langcode in the URL) 👎🏽 

## Actual behavior

Back to site takes you to the English page.

## Expected behavior

Back to site should respect the current navigation language and take you to the version of the front-end page in the currently selected language.

## Additional information

Add any other information:
- Backdrop CMS version: 1.24.2

-----
PR https://github.com/backdrop/backdrop/pull/4429

**Comment by olafgrabienski** [comment]
Confirming the issue. I've also tested a variation with Content Translation enabled:

1. Enable Locale, Language, and Content Translation.
2. Install a language, e.g. German.
3. Visit a node in English, e.g. `about`, and translate it to German (path: `de/ueber`).
4. Click a link in the admin bar, e.g. "Appearance". This takes you to `de/admin/appearance`.
5. Click "Back to site". You are taken to a page with path `ueber` (no `de` langcode) and a "Page not found" message.

**Comment by argiepiano** [comment]
OK, I've found the issue with this. The problem is that `admin_bar_preprocess_page()` gets the alias for the current path and passes it to the JS in charge of replacing the href of the "Home" icon.

The issue is that, in order to get that alias, this function uses:
```php
  $alias = backdrop_get_path_alias($current_path, $language->langcode);
```

Function `backdrop_get_path_alias()` returns the correct alias, but doesn't insert the language prefix in the path. In other words, the **alias** of the page in the other language (`ueber`) is not the same as correct **path** to that page in that language (`de/ueber`).

There are two possible solutions.

**Solution 1**: modify the JS code to get the current path from `window.location`,  and simply skip passing any paths from PHP.
This is how Drupal 9 does it currently. 

**Solution 2**: use `url()` to generate the correct path with language prefix, after getting the alias, and pass it to JS

I'm leaning toward solution 1, since it's the current "tried and true" approach used by D9/10. 

PR coming.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4429 ready for testing and review

**Comment by argiepiano** [comment]
Thanks @olafgrabienski! Would you be willing to change the label to WFM?

**Comment by olafgrabienski** [comment]
Sure, set to `pr - works for me`, after testing the PR also in the sandbox site. (Wondering why I didn't do that before.)

@argiepiano Strangely I got a PHP notice after editing the About page (see below and the DBlog of the sandbox site). Do you think it can be related to the PR?

> Notice: Undefined index: href in admin_bar_locale_links() (line 488 of /var/lib/tugboat/core/modules/admin_bar/admin_bar.module).

**Comment by argiepiano** [comment]
> @argiepiano Strangely I got a PHP notice after editing the About page (see below and the DBlog of the sandbox site). Do you think it can be related to the PR?

Uh-oh. That's produced by the newly added admin bar Language Switcher #5983. I'm not sure if this is interacting with the PR and producing that notice. Can you describe the steps that produced this?

**Comment by olafgrabienski** [comment]
> Can you describe the steps that produced this?

Yep, after enabling Locale, Language and Content Translation, I added a language and enabled multilingual support for Pages. Then I set the About page to "English" and hit the "Translate" tab. That's the moment where I saw the message.

**Comment by klonos** [comment]
Thanks @argiepiano 🙏🏼 ...code looks good 👍🏼

**Comment by quicksketch** [comment]
This looks good! I merged https://github.com/backdrop/backdrop/pull/4429 into 1.x and 1.25.x. Thanks @argiepiano, @olafgrabienski, and @klonos!
