### ISSUE TITLE
Add a mini pager option to Search module results. 

### ISSUE THREAD

**Issue by leeksoup** [backdrop/backdrop-issues#6083]
## Description of the need

All other pagers on my site (mostly generated using Views) have the "mini" pager. It's frustrating to have this one page use only the "full" style pager, and it generates a LOT of buttons which looks pretty silly.

## Proposed solution

Ideally, the search module config would have an option to do a "mini" pager like Views module does.

## Alternatives that have been considered

I have used Views with exposed filters for search in the past (like many years ago before Drupal's search was polished) but I would prefer to use the search module  because it works a lot faster.

## Additional information

Desired look: 
![image](https://user-images.githubusercontent.com/25186767/234716084-a8ac9330-dfbd-4ff5-a1bf-dc52f9565e0d.png)

Current look:
![image](https://user-images.githubusercontent.com/25186767/234716165-c3da31dd-15ab-499e-bbb3-eceaa8506630.png)

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes the option to use mini pagers on search results pages for a sleek appearance.

---

TRANSLATION UPDATE

Changed strings:
* old: `The maximum number of items indexed in each pass of a <a href="@cron">cron maintenance task</a>. If necessary, reduce this number to prevent timeouts and memory errors while indexing.`
* new: `The maximum number of items indexed in each pass of a <a href="@cron">cron maintenance task</a>. If necessary, reduce this number to prevent timeouts and memory errors while indexing.`
* old2: `Whether to apply a simple Chinese/Japanese/Korean tokenizer based on overlapping sequences. Turn this off if you want to use an external preprocessor for this instead. Does not affect other languages. <strong>Changing this setting will invalidate the search index.</strong>`
* new2: `Whether to apply a simple Chinese/Japanese/Korean tokenizer based on overlapping sequences. Turn this off if you want to use an external preprocessor for this instead. Does not affect other languages. <strong>Changing this setting will invalidate the search index.</strong>'`

New strings:
* `Pager type`
* `Full pager`
* `Mini pager`
* `Includes "Previous"/"Next" and "First"/"Last" links, as well as numbered links for each page of the search results.`
* `Shows only "Previous"/"Next" links, and indications of the current and total number of search results pages.`

**Comment by yorkshire-pudding** [comment]
It may also be good, though this is a nice to have rather than a must have, to allow the switch to be responsive to screen size (i.e. full pager on desktop, mini pager on mobile).

**Comment by klonos** [comment]
Here's an initial PR up for testing/review: https://github.com/backdrop/backdrop/pull/4417

Add the following fieldset in the "Search settings" form at `admin/config/search/settings`:
![image](https://user-images.githubusercontent.com/2423362/235345133-21ee0f7d-75fa-45c9-bb7c-1caaa3b6b252.png)

Seeking initial review/feedback on the implementation, but there's currently a problem that I would like to figure out (for which I have added a `@to-do` comment in the relevant code section): `theme_pager()` (which is being used for the current behavior of always rendering a full pager) works fine, however `theme_views_mini_pager()` (which I am re-using for the purposes of minimal code changes) needs a cache clear to be rendered in each page of the search results - the theme registry cache specifically. I wasn't able to figure out why that is.

**Comment by klonos** [comment]
> It may also be good, though this is a nice to have rather than a must have, to allow the switch to be responsive to screen size (i.e. full pager on desktop, mini pager on mobile).

@yorkshire-pudding I think that this is a nice idea for how pagers should be behaving in general (those in views as well). Wanna file a separate issue for this?

**Comment by klonos** [comment]
How to test this:
- Install the Devel module, and enable the devel_generate submodule.
- Generate a bunch of content (I generated 5000 nodes on my local)
- Head to `/admin/config/search/settings` and reindex the site (remaining items option will do)
- Head to `/search` and search for a term that will generate multiple results (in my case, searching for "refero" did it)
- Back in `/admin/config/search/settings` switch between the two new options for the pager, followed by saving the form
- Refresh the `/search` page to see the switch of pager type take effect.

**Comment by stpaultim** [comment]
Works for me. The new page looks like this in Basis.
![image](https://user-images.githubusercontent.com/3144571/235403372-97a03eb2-48a5-4576-9718-74d8ef3aaae3.png)

**Comment by yorkshire-pudding** [comment]
> > It may also be good, though this is a nice to have rather than a must have, to allow the switch to be responsive to screen size (i.e. full pager on desktop, mini pager on mobile).
> 
> @yorkshire-pudding I think that this is a nice idea for how pagers should be behaving in general (those in views as well). Wanna file a separate issue for this?

Added a bare bones issue here: https://github.com/backdrop/backdrop-issues/issues/6094

**Comment by klonos** [comment]
Thanks @yorkshire-pudding 🙏🏼 

I'm adding the "help wanted" label to see if anyone can figure out the issue with the necessity to be clearing the theme registry on every search result page in order to have the Views-provided mini pager be rendered.

**Comment by quicksketch** [comment]
I filed a replacement PR that fixes the registry issue and renames the keys stored in config: https://github.com/backdrop/backdrop/pull/4424

**Comment by quicksketch** [comment]
> I had tried to avoid having to "map" the options keys to the the respective theme function name

Yeah, I'd like to get us set up for renamespacing `views_mini_pager` to just `mini_pager`, so avoiding storing the name in config might save us another update hook later.

**Comment by klonos** [comment]
I've tested this in the PR sandbox by following the steps outlined in https://github.com/backdrop/backdrop-issues/issues/6083#issuecomment-1528979807 above. WFM, so this is good to go 👍🏼 

The mini pager needs a little bit of love, so that #6089 is fixed, and also the fact that on the first page of results the empty "previous" button needs to not be rendered:
![image](https://user-images.githubusercontent.com/2423362/235525526-27e0dbf5-38e9-4b7f-b87d-30cd46e012e4.png)
...same with the "next" button on the last page of results:
![image](https://user-images.githubusercontent.com/2423362/235525948-246bea12-af24-4136-814a-3a15876ba462.png)

I'll file a follow-up for that when I get the chance.

**Comment by quicksketch** [comment]
Welcome @leeksoup to the Backdrop community! I've added you to our "Docs and organization" group here on GitHub so you can now add issue labels.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4424 into 1.x for 1.25.0. @leeksoup if you encounter any problems, please file a follow-up issue. Today is the last day before feature freeze for 1.25.0 so we wanted to get this in quickly. Thanks!

https://github.com/backdrop/backdrop/commit/6860f7e1bd73184f011f8f17fb13e8dea7df2895 by @klonos, @yorkshire-pudding, @stpaultim, @leeksoup, and @quicksketch.

**Comment by leeksoup** [comment]
@quicksketch - No issues. Works great!

**Comment by klonos** [comment]
@quicksketch (or any of our other @backdrop/core-committers) tiny PR to remove a now irrelevant/innaccurate inline comment that we missed to remove from the changes that got merged in: https://github.com/backdrop/backdrop/pull/4430

**Comment by quicksketch** [comment]
Yup, clearly an accidental inclusion. I've merged it for 1.25.0. Thanks @klonos!
