### ISSUE TITLE
field_attach_update doesn't save the data like it did in Drupal 7

### ISSUE THREAD

**Issue by danksearle** [backdrop/backdrop-issues#6084]
## Description of the bug

I am migrating a Drupal 7 project to Backdrop. This code used to save a change to the value of a field on a node:
```
  $node->{$slot}[LANGUAGE_NONE][0]['value'] = $meeting_table_id;
  field_attach_update('node', $node);
```
That code was written in 2014 and has worked in Drupal 7 ever since.

Now in Backdrop, I am running that code in a submit via Ajax which then reloads part of the page to show the effect of that change - as a user you can see the effect, so it appears to have worked. But, when you reload the page the effect vanishes again. I conclude that the change is made in the variables that exist during the processing of the request, but it fails to actually save to the database. That would explain how the user sees the change within the ajax request processing, but on subsequent page visits the change vanishes.

To get around this, I have had to add node_save like this:

```
  $node->{$slot}[LANGUAGE_NONE][0]['value'] = $meeting_table_id;
  field_attach_update('node', $node);
  node_save($node);
```

With that, it works. But I want to report this issue because perhaps it is a similar situation to the https://github.com/backdrop/backdrop-issues/issues/6081 which seems to be old Drupal 7 code brought into Backdrop core years ago, that D7 code was later updated but Backdrop wasn't. Just a guess!

## Additional information

My site is in development, hosted locally on my own PC with WSL2, Ubuntu and Lando.

Backdrop CMS version: 1.24.0
Web server: Apache/2.4.54 (Debian)
PHP version: 7.4.33
Database server: MySQL 5.7.29

**Comment by indigoxela** [comment]
Hi @danksearle,

not sure, if node_save() is really necessary in your code. :thinking: 

Did you try to reset the node cache, as suggested in the [doc block](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.attach.inc/function/field_attach_update/1)?

Something like `entity_get_controller('node')->resetCache(array($node->nid));`

**Comment by danksearle** [comment]
You're right, that was it. So, it wasn't that it wasn't saving as I thought, it just looked that way because after a refresh of the page I was seeing the old, cached data instead of the change.

I would say this issue can be closed.
