### ISSUE TITLE
[UX] Hide select element when all options are removed

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#609]
You can see this UI fault on the content type edit screen, `admin/structure/types/manage/article` for example. To reproduce:
1) Look in the Menu settings vertical tab.
2) Un-check all options for Available menus
3) Notice that the select list for 'Default parent item' is now empty.

If all the options have been removed, we shouldn't ask the question.  Let's remove the whole `div.form-item-menu-parent` with JS when all boxes are unchecked.

**Comment by klonos** [comment]
That would be a nice UX improvement. +1

...though trying to confirm this, I've discovered #611

**Comment by tarekdj** [comment]
PR: https://github.com/backdrop/backdrop/pull/696

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/696. Thanks!
