### ISSUE TITLE
Follow-up to #4937: Add a backward-compatible fallback for `image_TOOLKIT_supported_extensions()`.

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6092]
## Description of the bug

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/4937, where `image_TOOLKIT_supported_extensions()` was added. The implementation will currently break ImageMagick module because that module does not provide that callback. The fallback behavior should use the previous list of extensions, rather than allowing no extensions at all.

---

TRANSLATION UPDATE:

Changed strings:
* old: `The selected image handling toolkit %toolkit can not correctly process %function.`
* new: `The selected image handling toolkit %toolkit should provide a %function callback.`

**Comment by quicksketch** [comment]
@herbdool If you could take a look at this to see if you agree with the concept, that would be appreciated!

**Comment by herbdool** [comment]
@quicksketch good idea! Let's get this in too.

**Comment by quicksketch** [comment]
Awesome, thanks! I merged https://github.com/backdrop/backdrop/pull/4418 into 1.x for 1.25.0.
