### ISSUE TITLE
Mini pager: do not render the "previous" link on the first page of results, nor the "next" link in the last page

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6095]
This is a follow-up to #6083...

On the first page of results the empty "previous" button needs to not be rendered:
![image](https://user-images.githubusercontent.com/2423362/235525526-27e0dbf5-38e9-4b7f-b87d-30cd46e012e4.png)
...same with the "next" button on the last page of results:
![image](https://user-images.githubusercontent.com/2423362/235525948-246bea12-af24-4136-814a-3a15876ba462.png)

PS: need to check if this is happening with the mini pager in Views, or if it was only an issue when the mini pager is being used in the search results.

**Comment by leeksoup** [comment]
@klonos - This does not happen with mini pager in Views.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/4436. It looks to me like the mini pager in Views behaves differently than the normal pager. The normal pager does not render anything when a previous or next link is not necessary. But Views instead adds an empty `<li>` tag with a blank space (`&nbsp;`) in it. This seems to happen both in the search results and it is the current behavior in all Views as well.

I'm not sure why Views is doing this, perhaps to make centering a mini pager easier? But it's inconsistent with the normal pager, so I'm inclined to say we should make the mini pager work the same way as the normal one and not render anything if there's no previous or next links.

My PR at https://github.com/backdrop/backdrop/pull/4436 takes this approach.

**Comment by quicksketch** [comment]
Screenshot showing `/admin/content` when Basis is the admin theme demonstrates that this occurs within Views currently anywhere the mini pager is used:

![image](https://github.com/backdrop/backdrop-issues/assets/100206/27fb8342-37d3-41ce-bac4-87154b3e0845)

So this will fix that issue with Views module itself as well. The alternative is we could change the styling in Basis, but I think being consistent is a better approach and avoids the problem Basis itself is demonstrating when an empty `li.previous` element is rendered.

**Comment by leeksoup** [comment]
@quicksketch - you are correct, please ignore my previous comment. My themes style the actual links, not the <li> elements, so they look right anyway as in the first picture at #6083 

Thanks for fixing!

**Comment by laryn** [comment]
Code looks good.

**Comment by quicksketch** [comment]
Thanks @leeksoup and @laryn! I've merged https://github.com/backdrop/backdrop/pull/4436 into 1.x for 1.25.0.
