### ISSUE TITLE
"Create new revision by default" doesn't enable revisions

### ISSUE THREAD

**Issue by kswan** [backdrop/backdrop-issues#6103]
## Description of the bug

The Revision settings for a content type are not clear. The options under Revision settings are:

- Show option to create new revisions
Revisions allow content editors to view changes over time and revert changes if needed.
- Create new revision by default

The current functionality is that the "Show option to create new revisions" actually enables or disables revisions for the content type. If "Show option to create new revisions" is off, the "Create new revision by default" is ignored.

## Steps To Reproduce

To reproduce the behavior:
1. Open the configuration page for a content type.
2. Set the Revision settings to uncheck "Show option to create new revisions" and check "Create new revision by default"
3. Edit a node of the content type that was edited.
4. View the revisions of the edited node.

## Actual behavior

No revisions is saved for the edited node.

## Expected behavior

Since the Revision settings are showing "Show option to create new revisions" unchecked and "Create new revision by default" checked, the revision setting shouldn't be shown on the node edit page, but the revision should be saved.

Alternatively, the Revision settings can be reworded to reflect the actual behavior. Maybe: 
- Enable the option to create new revisions
Revisions allow content editors to view changes over time and revert changes if needed.
- Create new revision by default 
And "Create new revision by default" should be hidden if the first option is disabled.

## Additional information

In my use case, I want revisions saved for every node edit without the option to not save a revision. I am able to accomplish this by enabling both check boxes under Revision settings and using the Simplify module to remove the revision setting from the node edit form.

Add any other information that could help, such as:
- Backdrop CMS version: 1.24.2

**Comment by klonos** [comment]
I confirm this bug 👍🏼 

> Since the Revision settings are showing "Show option to create new revisions" unchecked and "Create new revision by default" checked, the revision setting shouldn't be shown on the node edit page, but the revision should be saved.

Yup, that's what I would expect too 👍🏼 ...if the intention was to only save new revisions by default if the "Show option to create new revisions" is ticked, then I would expect some rewording in the checkboxes and help text + have the "Create new revision by default" checkbox be dependent on the "Show option..." checkbox (via states). However, I believe that the intention of having "Show option..." unticked and "Create new revision by default" ticked is to configure the content type to be saving revisions automatically each time the content is saved/updated.

This looks interesting, so I'd like to attempt a crack at it...

**Comment by klonos** [comment]
...FTR, here's the respective setting in D10:
<img src="https://user-images.githubusercontent.com/2423362/236644432-1d5067a9-f95d-4b76-a8ee-0d213c116a78.png" width=70%>

Noting the help text:
> Users with sufficient access rights will be able to override these options.
...once that checkbox is ticked, there seem to be no permissions specific to allowing people to skip creating a revision. The only relevant permissions in D10 are the following:
- `%content_type%`: Revert revisions
- `%content_type%`: View revisions
- Delete all revisions
- Revert all revisions
- View all revisions

So once that setting is enabled for a content type, this is shown to the sidebar at all times for everyone:
<img src="https://user-images.githubusercontent.com/2423362/236644657-852eff34-aa49-48bd-97f0-2b60c9019348.png" width=50%>

**Comment by klonos** [comment]
...D7 works pretty much the same, with the only difference being that by default the "Basic page" content type has the option for revisions off OOTB.

**Comment by klonos** [comment]
...and here's what we currently have in Backdrop:
![image](https://user-images.githubusercontent.com/2423362/236645220-6bf1e997-78f7-493c-8fd9-bdf84b07c962.png)

**Comment by klonos** [comment]
...the help text refers to what revisions are and why they are useful, yet it is attached to one of the settings in that vertical tab (while it is a generic help text that applies to revisions in general).

I think that the UI should be changed to this, to make things clear:
![image](https://user-images.githubusercontent.com/2423362/236646143-5105329d-09b9-43f0-bb22-34194402b69a.png)

**Comment by kswan** [comment]
@klonos, I think your proposal is very clear and resolves the misleading nature of the current UI.

I will note that the second option (Always create revisions) is currently not possible with core. So, technically, this proposal combines a bug fix and a feature. For me, that is the option I typically would select so I support this proposal.

**Comment by klonos** [comment]
> So, technically, this proposal combines a bug fix and a feature.

Yeah, I realized that, but at the same time I also don't like half-baked solutions 😉 ...I'd be happy to split my UI proposal into a new issue, and leave this issue here to focus only on fixing the bug that has been reported.

**Comment by yorkshire-pudding** [comment]
@klonos - what is the status of this? I don't see a linked ticket

**Comment by klonos** [comment]
...this was brought up in (and is somewhat blocking) #3733.

**Comment by klonos** [comment]
Noting that if we are to introduce the feature of allowing the option to always create a new revision, then we also need to specify a safe maximum number of revisions to retain (not sure if that should also be allowed to be set via the admin UI or not - leaning towards not) + a way to purge/cycle revisions (delete the oldest if a new one is created when the limit has been reached). In my previous job, we had a site where a couple specific pages were crashing, and that was caused because they were updating these specific nodes programatically via cron runs from external sources. In that case, the customer needed to use https://www.drupal.org/project/node_revision_delete.

PS: the project page of node_revision_delete linked above has a huge list of similar modules by the way (which to me indicates that it should be in core). Also, there seems to have been a coordinated effort in the community to consolidate this functionality in a single module instead of having a dozen to choose from for the same functionality.

**Comment by yorkshire-pudding** [comment]
> Noting that if we are to introduce the feature of allowing the option to always create a new revision, then we also need to specify a safe maximum number of revisions to retain (not sure if that should also be allowed to be set via the admin UI or not - leaning towards not) + a way to purge/cycle revisions (delete the oldest if a new one is created when the limit has been reached). In my previous job, we had a site where a couple specific pages were crashing, and that was caused because they were updating these specific nodes programatically via cron runs from external sources. In that case, the customer needed to use https://www.drupal.org/project/node_revision_delete.
> 
> PS: the project page of node_revision_delete linked above has a huge list of similar modules by the way (which to me indicates that it should be in core). Also, there seems to have been a coordinated effort in the community to consolidate this functionality in a single module instead of having a dozen to choose from for the same functionality.

Should we also consider given the example above that not all revisions have equal value? I would be more interested in keeping revisions saved by a person than those by an automated update as more likely to be a meaningful change, whereas those updated by a script should be more predictable and therefore less interesting other than very recent history.

**Comment by klonos** [comment]
> ...whereas those updated by a script should be more predictable and therefore less interesting other than very recent history.

You would think that, but the code that does it is created by humans 😅, so the risk of a destructive change that needs to be reverted is still there. But yes, I see what you mean 👍🏼 ...that though (being able to distinguish between human-initiated vs automatic/programatic changes) sounds like a different feature 🤔

**Comment by yorkshire-pudding** [comment]
> though (being able to distinguish between human-initiated vs automatic/programatic changes) sounds like a different feature

I think automatic purging of revisions is also outside the scope of this ticket, but perhaps the fine grained control of revision purging would be a logical part of such a feature?

As an aside, if anyone needs to enforce revisions before this bug fix is implemented, then the [Enforce Revision Logs module](https://github.com/backdrop-contrib/enforce_revlog) gives that ability.

**Comment by klonos** [comment]
OK, who wants to give it a spin?: https://github.com/backdrop/backdrop/pull/4546 🙂

**Comment by klonos** [comment]
During the UX meeting this week we started playing with the PR sandbox, and it turns out that something's amiss (most likely config values not saved properly) ...I'll have to take another look at the code. Please feel free to give it a quick spin and provide feedback on the general UX though.

**Comment by kswan** [comment]
@klonos I tried to find the cause of the problem you found in the UX meeting, but couldn't find it. The config files are still showing the "revision_enabled" setting that should be changed to "revisions".

I found a line in function node_node_type_load(&$types) that is still showing "revision_enabled" (I added a comment to the PR). I am not sure if that is causing the config issue.

**Comment by klonos** [comment]
Thanks @kswan 🙏🏼 ...I'll fix that. The odd bit though is that things on my local are working as expected (same branch as in the PR) 🤔

**Comment by klonos** [comment]
...it also works as expected in the PR, but only for existing content types - not for new ones. Taking a deeper look.

**Comment by kswan** [comment]
Yes, I am seeing the same thing in the sandbox. The new content types don't save, but stock content types do save. I wonder if it is caused by the issue I found in node_node_type_load().

**Comment by klonos** [comment]
Just pushed a commit to fix that remaining instance of `revision_enabled` in `node_node_type_load()`, so we'll see.

In the meantime, I forced a re-run of `node_update_1023()` on my local, and things started working as expected (proper values saved in config, and settings sticking for new content types as well).

I believe that things were working as expected for the stock content types because these are set up in the standard installation profile, and that was correct.

**Comment by klonos** [comment]
...OK, yes, that seems to have been the issue. Appears to be fixed now.

PS: I have noticed that Tugboat PR sandboxes are a bit too finicky lately. Some commits seem to be causing them to fail to be built. Usually takes a rebase to fix things.

**Comment by herbdool** [comment]
The proposed solution puts it into new feature territory. If this was just a bug fix the solution would be something like hiding the "default" checkbox if "show option..." was not selected. Or something like that.

**Comment by herbdool** [comment]
Has anyone tested this with a role that doesn't have the `administer nodes` permission? If they don't have that permission they can't uncheck "Create new revision" checkbox on a node.

**Comment by herbdool** [comment]
I think the following should be sufficient to make the options clearer, and avoid adding new features and breaking backwards compatibility. Add to `node.types.inc` the content type form:

```
$form['revision']['revision']['revision_default'] = array(
    '#type' => 'checkbox',
    '#title' => t('Create new revision by default'),
    '#default_value' => $type->settings['revision_default'],
    '#parents' => array('revision_default'),
    '#states' => array(
      'visible' => array(
        'input[name="revision_enabled"]' => array('checked' => TRUE),
      ),
      'enabled' => array(
        'input[name="revision_enabled"]' => array('checked' => TRUE),
      ),
    ),
  );
```
Where the default revision checkbox is hidden and disabled if "Show option to create new revisions" is not enabled. This matches this line in `node.module` where the default setting only has effect if revisions are enabled:

`$node->revision = $node_type->settings['revision_enabled'] ? $node_type->settings['revision_default'] : FALSE;`

I don't see the need for a "Always create revisions" when this is already how things work for non-admins.

**Comment by herbdool** [comment]
@izmeez, @klonos' PR is not fixing a bug, it's making a structural change/a new feature. It's not broken. Going by the original report, it at most needs a wording tweak and hiding an option when it isn't active. Revisions are already "enforced" for non-admins, so that is working as expected.

I suspect the wording "Show option to create revisions" is used because regardless of this setting, a new revision can be created via an API call. So strictly that option is not "enabling" or "disabling" revisions. So any rewording should keep that in mind (if my guess is correct).

**Comment by kswan** [comment]
The point about this being a bug or a feature request was discussed back in https://github.com/backdrop/backdrop-issues/issues/6103#issuecomment-1540298788

I think the debate about bug or feature request is a minor issue. I think it is clear that the current verbiage is not consistent with the functionality.

The PR by @klonos makes the functionality and verbiage clear. So, I think it is an improvement that should be implemented.

Regarding @herbdool's comments about the revision option being hidden for non-admins. Those comments are partially correct. The revision option is only shown to people with the Administer Content (administer nodes) permission, but by default, the Editor role has the Administer Content permission enabled. So, by default, this affects admins and editors.

**Comment by kswan** [comment]
@izmeez, I don't think the diff module changes anything regarding saving revisions. It looks like it only affects the display of revisions.

**Comment by herbdool** [comment]
`diff` module has "Enable the Revisions page for this content type" but I don't think it does anything. If a piece of content has revisions the revisions tab is visible regardless. And it is even visible if someone disables the "Show option to create new revisions" option. So someone can be prevented from creating new revisions but the existing revisions will still show up.

I really don't think we want to make any wholesale changes without understanding what is going on. And definitely we don't need backwards-breaking changes in 1.x unless there's critical need, which has not been shown yet.

@klonos PR would also break compatibility with https://github.com/backdrop-contrib/content_moderation.

**Comment by herbdool** [comment]
@izmeez I'm talking about the reverse: even if the diff option is disabled, the revisions tab is displayed. So maybe diff should just get rid of that option. At any rate, that's an issue for that module, not core.

**Comment by herbdool** [comment]
> It would be nice if under the Revision setting tab, there were 3 results shown: Disabled, Enabled, and Optional for when the Create new revision by default is unchecked.

It all seems to depend on whether someone has `administer nodes` permission. If they don't have it, then them editing a node will either create a revision (if "Create new revision by default" is checked) or not, they have no choice. I just tested to confirm. But if they have `administer nodes` then creating a revision is optional.

To understand the workflow, I looked at the code and also tested it out. I think the description on the content type settings could at least explain how those with `administer nodes` permission can choose to create a revision or not, and that the "Create new revision by default" option should be checked if they want to enforce revisions for non-admins.

**Comment by yorkshire-pudding** [comment]
> On the secondary issue, thank you @herbdool for pointing out that the "administer content" permission is required to see the "Revision information" vertical tab when editing content. This is a permission that editors will require that other authenticated users will not require.

@izmeez 
You can grant editors that right without giving the broadest permission if you use the [Override Node Options module](https://github.com/backdrop-contrib/override_node_options)

**Comment by herbdool** [comment]
I've added an alternative PR based on some of the feedback from @izmeez and others. https://github.com/backdrop/backdrop/pull/4649. It is more of a bug fix, than adding a breaking feature. I would suggest that @klonos PR be on a new issue which recommends a new feature with more options.

**Comment by herbdool** [comment]
@kswan the rewording sounds fine to me. Updated.

**Comment by herbdool** [comment]
I closed https://github.com/backdrop/backdrop/pull/4649 and recommended it be on a new issue where there might be backwards-incompatible changes. Maybe it'll still gain traction, not sure. As for my PR, I've put it ready for testing and review. With a small rewording change.

**Comment by kswan** [comment]
I agree https://github.com/backdrop/backdrop/pull/4649 works for me and the code looks good.

**Comment by quicksketch** [comment]
Thanks folks! I did not read over this entire issue, but the fix seems good and @kswan, @izmeez, and @herbdool all seem to be in agreement that it is an improvement. I've merged https://github.com/backdrop/backdrop/pull/4649 into 1.x and 1.27.x. Thanks!
