### ISSUE TITLE
Content type config: Menu settings -> 'Default parent item' drop-down shows all menus.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#611]
I see this in firefox and chrome, so it shouldn't be a browser-related issue.

STR:
1. Go to the 'Edit' page of any content type (for example `/admin/structure/types/manage/article`)
2. Go to the 'Menu settings' tab. By default, only the 'Primary navigation' menu is enabled in the 'Available menus' checkbox list.

Expected behavior: only the 'Primary navigation' menu and it's child items should be available in the 'Default parent item' drop-down.

Actual behavior: every menu available in your setup + all their children are listed in the drop-down.

Try selecting/deselecting any combination of available menus. You'll see that the list in the drop-down is not updated accordingly,

**Comment by sirkitree** [comment]
Currently when I create a page here is what I see:
![edit basic page privacy policy beta vrsites com 2015-01-19 11-10-53](https://cloud.githubusercontent.com/assets/28543/5805435/eb945d1c-9fcb-11e4-8bc8-af683d7c305a.png)

Now I actually have a Footer menu as well and would like to be able to put this page into the footer menu right from here. Isn't that reasonable?

If so, I don't understand your observations, or your expected behavior at all. Your expected behavior is actually what I'm seeing, and your actual behavior is what I would actually expect.

**Comment by sirkitree** [comment]
Nevermind - I found the option where you set the available menus now :facepunch:

**Comment by klonos** [comment]
Yeah, I was referring to the content type edit form (for example ```/admin/structure/types/manage/article```):

![content_type-all_menus_available](https://cloud.githubusercontent.com/assets/2423362/5806537/2e06bb98-a06e-11e4-80be-5bbe5800b42d.gif)

**Comment by sirkitree** [comment]
Understood, sorry for confusing the issue.

**Comment by klonos** [comment]
No worries. Just so to know, can you also reproduce the issue I'm having, or is it just my setup?

**Comment by sirkitree** [comment]
I can't actually. It even updates to only show the ones that I check off as soon as I check them off.
![backdrop-issue-611](https://cloud.githubusercontent.com/assets/28543/5808042/38d45fae-9fe6-11e4-993a-38bed8b160db.gif)

**Comment by klonos** [comment]
Hmm. Browser? OS?

I'm testing this in a local environment (nginx 1.7.5 / php 5.5.17 / MariaDB 10.1.0) on Windows 8 x64 and see this in firefox 37/38 x64 nightlies as well as latest Chrome 39.

**Comment by klonos** [comment]
...still in the same WTF situation with this. I am logged in as admin (so have all permissions) and I do not have clean URLs enabled. Can somebody else test and either confirm or not?

@quicksketch ? @jenlampton ?

**Comment by docwilmot** [comment]
works fine for me, WAMPserver, Win 7, PHP 5.5.12. Is menu.admin,js being included on this page for you?

**Comment by jenlampton** [comment]
Also works fine for me (MAMP, PHP 5.3.20) I'm going to close this for now.  Please re-open if others have trouble!
