### ISSUE TITLE
Replace "Users'" in contact module permissions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6112]
Contact module has a permission with the label `Use users' personal contact forms`. We don't have "users" in Backdrop, we have `User accounts` and `People`, we should decide which this is and adjust the label for this permission.

I am going to recommend `Use personal contact forms` without any modifier, since I think it is clear on it's own.

**Comment by klonos** [comment]
Thanks @jenlampton for noticing this, and @kiamlaluno for providing a PR 🙏🏼 

I've left a small nit-pick in the PR, which is otherwise RTBC.

**Comment by olafgrabienski** [comment]
> I am going to recommend `Use personal contact forms` without any modifier, since I think it is clear on it's own.

At this place, the text might be clear for experienced people (coming from Drupal or Backdrop), but I guess it's not clear for newcomers. I'd suggest something along those lines:

> Use personal contact forms of user accounts.

(Not sure about the correct preposition: is it `of`, `at`, or `on` user accounts`?)

**Comment by klonos** [comment]
Code-wise things LGTM 👍🏼 

Lets wait for some more feedback from others.

**Comment by kiamlaluno** [comment]
English usually use the Saxon genitive instead of *of*, like the current label does (*Use users' personal contact forms*). If *users* is replaced by *user accounts*, that label would become *Use user accounts' personal contact forms*. That seems a bit longer to me too, given that *personal* is already saying the contact form is for a person with an account on a site.

I am not sure it is possible to make that label clear for everybody, including people who just started to use Backdrop. Since that is a permission label, the permissions page should give a link to each module implementing permissions (if that link is not already given), where the Contact module is described as the module that implement a contact form for every account present in the site and a site contact form.

**Comment by kiamlaluno** [comment]
(As for making that label clear also for people who just started to use Backdrop, the permission label is shown to users with the permission to administer permissions, which is a permission for trusted roles. They are not people who register an account on a site to be able to reply to a comment they found.)

**Comment by olafgrabienski** [comment]
> If _users_ is replaced by _user accounts_, that label would become _Use user accounts' personal contact forms_.

I see, that sounds a bit awkward.

While I still think the meaning of "Use personal contact forms" is ambiguous for newcomers, I guess *most* people will understand that a personal form refers to user accounts, so I agree with Jen's suggestion.

**Comment by ilfelice** [comment]
Howdy,

I am kind of new here, so bear with me if if I am off whack with my comment.

It seems this option is used to "enable" the contact form, right?

If that is the case, then something like below could be more explicit:

"Enable personal contact forms"

Food for thought! :)

**Comment by klonos** [comment]
Hello @ilfelice and welcome to the Backdrop community 👋🏼 ...thank you for taking the time to chime in 🙏🏼 

> It seems this option is used to "enable" the contact form, right?

Well, _technically_, the contact form is enabled by enabling the Contact module. The permission is there to regulate who has access to the contact forms provided by the module once it is enabled - the purpose of the permission is not to enable/disable the feature.

**Comment by ilfelice** [comment]
@klonos You are right. :)

@quicksketch Thank you for the invitation. I will investigate if there is anything that I can contribute with. Cheers!

**Comment by klonos** [comment]
@ilfelice if you haven't done so already, please check out our [community chat](https://backdrop.zulipchat.com), and [our forum](https://forum.backdropcms.org), where you can get information and help for all things related to Backdrop 😉
