### ISSUE TITLE
Permissions for the Contact module shown on /admin/config/people/permissions do not match the permissions shown on /admin/structure/contact/settings

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6117]
/admin/config/people/permissions allows to change the permissions each roles have, including the permissions for the Contact module.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/65c475d2-ce58-4ad3-b302-190ec9203791)

On /admin/structure/contact/settings, there is a *Permissions* fieldset that allows to change the Contact module's permissions each role has.

![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/fac77014-207f-4028-b34e-5bd58b29fe05)

The permissions shown in those pages do not match: On /admin/config/people/permissions, the *Administrator* role does not have the *Use the site-wide contact form*, which I expressly removed, while on */admin/structure/contact/settings*, that permission is still given after I removed it from /admin/config/people/permissions.

### Steps to reproduce

- Install the Contact form
- Visit /admin/config/people/permissions
- Deselect the checkbox shown for *Use the site-wide contact form* for the *Administrator* role
- Click on *Save permissions*
- Visit /admin/structure/contact/settings
- Check which checkboxes are selected

### Expected behavior

Since the permissions for the Contact module have been changed on /admin/config/people/permissions, the change should be reflected on /admin/structure/contact/settings.

**Comment by olafgrabienski** [comment]
Confirmed on a vanilla demo site:

_Contact_ module permissions changed at `admin/config/people/permissions` are not reflected on `admin/structure/contact/settings`.

(But permissions changed at `admin/structure/contact/settings` _are_ reflected on `admin/config/people/permissions`.)

**Comment by kiamlaluno** [comment]
I found out what is causing this issue. [`user_admin_permissions()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.admin.inc/function/user_admin_permissions/1) uses the following code.

```php
foreach ($roles as $role_name => $role) {
  // Build arrays for checked boxes for each role.
  if (in_array($perm, $role->permissions)) {
    $status[$role_name][] = $perm;
  }
}
```

It shows a selected checkbox only when the permission has been assigned to the role.

[`contact_form_permissions()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21contact%21contact.admin.inc/function/contact_form_permissions/1) uses the following code.

```php
foreach ($roles as $role_name => $role) {
  // Builds arrays for checked boxes for each role. Always select the Admin
  // role on new forms.
  if (in_array($perm, $role->permissions) || ($role->name == $admin_role)) {
    $status[$role_name][] = $perm;
  }
}
```

It shows a selected checkbox even for the admin role, even in the case it does not have that permission.

**Comment by indigoxela** [comment]
I can also confirm the problem (hardly ever use the Contact module).

Seems like that code got copied over from Taxonomy, but that special handling for admin role is only needed for vocabs, where each one has its own set of permissions. And _only when a new one gets created_.
The whole situation with contact forms is different.

And I can confirm, that the PR fixes it properly. :+1: Many thanks @kiamlaluno for finding and filing a PR.

**Comment by kiamlaluno** [comment]
That explains why the comment said *Always select the Admin role on new forms.*

**Comment by bugfolder** [comment]
Code reviewed, LGTM.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno, @olafgrabienski, @indigoxela, and @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4472 into 1.x and 1.26.x.
