### ISSUE TITLE
Allow themes to have `config` folders

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#6122]
## Description of the need

Currently CMI does not scan themes for a config folder. Not sure if there is any major disadvantage to doing so, but it may be helpful in solving [Use config for color module palettes](https://github.com/backdrop/backdrop-issues/issues/2554)

Themes do save data in config, but only by syncing from the info file during enabling, and/or saving the settings form.

This may also allow deprecating `info` file settings such as `settings[]=xxx` etc.

## Proposed solution

Allow themes to have `config` folders

**Comment by klonos** [comment]
This is part of the #5317 meta, but also sounds like it could be a duplicate (or subset) of what we are trying to achieve in #4829.

**Comment by docwilmot** [comment]
I dont think its quite the same as #4829. I've pushed my code. With this PR, all three project types will be synced by CMI (I left `'layout'` in the array) but I havent written any code for uninstalling layout config, because I suspect we might want to limit this to just themes. Any benefit to layout templates having config folders?

**Comment by stpaultim** [comment]
Interesting issue. This sounds like it could be really useful, but I've not thought a lot about this. Seems like this could benefit contrib theme developers. 

What do others think about this?

**Comment by yorkshire-pudding** [comment]
This makes a lot of sense. A lot of themes have settings, and this would make the config consistent with modules.

**Comment by docwilmot** [comment]
Added a brief test to this to show that themes without a `settings[]` array in the `info` file will still show a settings page with correct settings.

**Comment by quicksketch** [comment]
Thanks @docwilmot! Test coverage and the general feature look solid to me! I added a commit to add `@since 1.26.0` lines to the docblocks.  What's the best place to document this new ability? It's API backwards-compatible, so a change record isn't strictly necessary.

**Comment by jenlampton** [comment]
> a change record isn't strictly necessary.

I still think it would be a good idea, since people will probably still be looking for it on the API site.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4440 into 1.x. This looks great! Thanks @docwilmot for your work on this!

**Comment by klonos** [comment]
Reopening this, in order to keep it within our radar for a change record.

**Comment by argiepiano** [comment]
I'm not sure if this fact was considered when creating these changes, @docwilmot. I haven't done any testing to see if this will create regressions, BUT:

Color module already creates `<theme_name>.settings.json` when it rebuilding the colors. This is done by `color_rebuild_settings()`. This means that even a theme that doesn't provide a default `<theme_name>.settings.json`, WILL get one when :
1. Color is enabled 
2. You have at any point in time gone to the theme settings path (e.g. `admin/appearance/settings/basis`) and clicked  Saved

BTW, this settings file created by Color gets rebuilt every time you clear caches.

This came up as I was investigating issues with a subtheme (Thesis) and its puzzling handling of overridden colors. Then I saw what this patch did to core (basically checking for the existence of `<theme_name>.settings.json` in `theme_has_settings()`) and a red flag came up in my mind: basically, two potential issues: (1) a theme that DOESN'T provide  `<theme_name>.settings.json` WILL have such a file created by Color, and (2) more seriously, that file WILL get rewritten by Color every time you clear the caches.

As a side note: The use of a config file that gets rebuilt by a module on cache clears (by Color) seems wrong to me.

**Comment by argiepiano** [comment]
Did a bit of testing with a custom test theme that provides a settings config file with a dummy key. Color does add its usual stuff to that file under key `"color"`, but it doesn't delete any other information that theme provide in that file - so we are safe, as my point (2) above doesn't actually happen. However point (1) may still be a concern.

**Comment by docwilmot** [comment]
Yeah, that could be an issue. We'll need to check if the `json` file has only a "color" key in there, and ignore that conditional if so. Good catch.

**Comment by docwilmot** [comment]
Well, I was going to create an issue, but now I'm not so sure. Point 1 in @argiepiano's [post](https://github.com/backdrop/backdrop-issues/issues/6122#issuecomment-1783819610) may not be entirely valid AFAICT: the `json` file is still only created if you save the settings page. So since `theme_has_settings()` as is now is checking that the theme has a settings file, or an entry settings entry in the info file, which should in fact return true if the theme only has color support without other settings, I think this is OK.

**Comment by kiamlaluno** [comment]
I left a comment on the PR, but I now noticed the PR has been already merged. (Yes, the purple sign was impossible to miss, but I was able to miss it. 🤦🏻‍♂️)

**Comment by kiamlaluno** [comment]
Should I open a new issue for that change, if it is indeed the right change?

**Comment by kiamlaluno** [comment]
@stpaultim I noticed the changes have been committed after I commented on the PR. I did not open an issue because I forgot about my comment on this PR, but I am considering that.

**Comment by herbdool** [comment]
I made a stab at a change record for this: https://docs.backdropcms.org/change-records/backdrop-will-now-discover-settingsjson-configuration-files-in-a-theme-config-folder. From my understanding, it's not just that a theme can have settings in a config folder, but that it should be <theme>.settings.json and there needs to be a `hook_config_info()` in `template.php`. Is that correct?

**Comment by laryn** [comment]
I haven't tried it yet but that looks correct from what I can tell. We should link to/mention that change record here as well:
https://docs.backdropcms.org/documentation/adding-theme-settings-advanced

**Comment by herbdool** [comment]
@laryn I see it. Looks good to me

**Comment by kiamlaluno** [comment]
On https://docs.backdropcms.org/documentation/adding-theme-settings-advanced, there are some `<br />` tags that are rendered as code.

**Comment by bugfolder** [comment]
> there are some <br /> tags that are rendered as code.

Fixed.
