### ISSUE TITLE
Sending Tweets automatically (feature request)

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#614]
In a Drupal 7 site I have used the module Rules to create a Tweet whenever a specific type of new content is added. Has anyone any ideas or plans for a feature like this in Backdrop?

**Comment by tarekdj** [comment]
@Graham-72 this can be implemented in a contrib module via hook_node_insert().
https://api.backdropcms.org/api/backdrop/core%21modules%21node%21node.api.php/function/hook_node_insert/1

**Comment by klonos** [comment]
The official [Backdrop CMS Roadmap](https://backdropcms.org/roadmap) does not include adding Rules into core. There are only a few [contrib modules ported to Backdrop](https://github.com/backdrop-contrib) and Rules is not one of them. I guess that if you need this functionality for your website, then you'll have to wait.

**Comment by Graham-72** [comment]
Thank you for your replies. When I wrote 'in Backdrop' I wasn't expecting it to be added to Core, though I wonder whether there are any features such as Trigger in there. Where does one express interest in the development of contrib modules, or do people just go ahead and start? Though I think the complexity of Rules is beyond my capabilities.

**Comment by klonos** [comment]
> Where does one express interest in the development of contrib modules...

[Backdrop CMS](https://backdropcms.org) -> Developer Guide -> [Contributing code](https://backdropcms.org/develop/code)...

> **Contribute a module, layout, or theme**

...

Join the Backdrop Contrib group on Github by submitting an issue to the [Backdrop Contributed Module Issue Queue](https://github.com/backdrop-ops/contrib). The queue is monitored for new applicants. After being accepted, you will be able to create a new project (or move an existing one) under the Backdrop Contrib group at http://github.com/backdrop-contrib.

**Comment by klonos** [comment]
> Though I think the complexity of Rules is beyond my capabilities.

You could give it a go and see what happens: [Porting a Module to Backdrop - Basics](https://www.youtube.com/watch?v=by8mMhIpARA)

**Comment by Al-Rozhkov** [comment]
I think everything about Rules and Trigger module we can discuss in backdrop-contrib issue queues:
https://github.com/backdrop-contrib/rules
https://github.com/backdrop-contrib/trigger_actions

Should we close this one?

**Comment by Graham-72** [comment]
Yes, let's close this.
