### ISSUE TITLE
Views filter criteria error 'invalid option'

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#6145]
I am trying to set a filter criteria that compares today's date with a date field and although this has worked very well previously, Views is now giving me the error report 'Invalid option &lt;= in Operator element'.

This is with version 1.25.0 of Backdrop.
PHP version 7.4.33

It occurs when I am trying to modify a filter criteria based on a date, using the Views UI.

**Comment by laryn** [comment]
Hi @Graham-72 -- good to see you around again!

**Comment by Graham-72** [comment]
Hi @laryn and @olafgrabienski, thanks, the update to 1.25.1 has removed the problem, though the calculation of 'less than or equal to' seems to be one day out. I will do some more tests and maybe raise a separate issue.

**Comment by argiepiano** [comment]
>  though the calculation of 'less than or equal to' seems to be one day out.

I have noticed that before (not just in 1.25.1), but never got around to posting an issue in the queue. I ended up making the comparison with the following day. I think it may have to do with errors timezone calculations.
