### ISSUE TITLE
Typo in the help text for the "Show as expanded" option for menu items: hierarchial -> hierarchical

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6151]
As per the issue title, there's a "c" missing there in the word "hierarchial".

**Comment by bugfolder** [comment]
OK, here's one that's not beyond my skills to check.

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/9d8c40a4-68ec-4587-81e2-16d540d4e4a5)

LGTM. WFM.

**Comment by klonos** [comment]
Thank you @bugfolder 🙏🏼 

This typo was discovered while responding to [a thread in Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Main.20menu.3A.20show.20as.20expanded), where it was pointed out that the help text itself may not be 100% clear the way that it is currently phrased.

Since we are already changing the translatable string in order to fix the typo, I would like to also propose to tweak the help text to do a better job at explaining things. If we want to be 100% accurate with the description, then I was thinking something like this:
> Automatically expands this menu item if it contains any children items. **This setting only applies when the block for the `%menu_name` menu has been configured to be rendered as a "hierarchical tree"**.

Perhaps that deserves a follow-up UX task though 🤔

**Comment by bugfolder** [comment]
Let's make it a follow-up, because I anticipate some discussion over the revised wording. (Bikeshedding, anyone? 😉) Let's take our victories as we get them, however small.

**Comment by klonos** [comment]
Follow-up US issue filed here: #6152

**Comment by laryn** [comment]
> Let's take our victories as we get them, however small.

Chalk this one up as a victory. Thanks @klonos and @bugfolder -- merged into `1.x` and `1.25.x`.
