### ISSUE TITLE
User login form should not use spellcheck or autocorrect

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#6153]
## Description of the bug

Two use cases:
1. Device, particularly mobile autocorrects the username - see https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Mysterious.20login.20failures

2. User has enhanced spell checking enabled and sensitive details are sent for spell checking:
This was raised with security team in December but confirmed (by @jenlampton) that could be in public queue; I forgot about it until today.
   >If site has a password box with a 'show password' toggle (which Backdrop does):
   > <img src="https://github.com/backdrop/backdrop-issues/assets/20357797/bf843ff1-01f5-4a01-b6c3-52eda9f0e495" width=50%>

   > AND if user has enabled Enhanced Spell Check in Chrome, another browser or some spell checking extensions:
   > ![image](https://github.com/backdrop/backdrop-issues/assets/20357797/8b791ee6-4a11-437a-8f0b-619230581291)
   >
   > Then passwords may be sent in plain text to Google/Microsoft or other services.
   > This could also apply to name, email address, or any fields where personally identifiable information is input (i.e. login, registration, > account creation, webforms, ubercart).
   > 
   > It can be easily prevented by sites adding in the spellcheck=false attribute to sensitive input fields.

https://www.otto-js.com/news/article/spell-jacking-enhanced-spellcheck-features-send-pii-even-passwords

## Actual behavior
On some devices and with some usernames they are autocorrected
With enhanced spellcheck enabled usernames and passwords sent to public service.

## Expected behavior
Usernames and passwords are neither checked for spelling nor autocorrected

## Additional information

See https://www.drupal.org/project/drupal/issues/2537190

---
PR added - https://github.com/backdrop/backdrop/pull/4465

**Comment by kiamlaluno** [comment]
The *password* and the *password_confirm* form elements should always use `spellcheck="true"`. That attribute could be added in [`user_form_process_password()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_form_process_password/1) and [`user_form_process_password_confirm()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_form_process_password_confirm/1), which are the process hooks set in [`system_element_info()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_element_info/1) for those form elements.

**Comment by kiamlaluno** [comment]
If then there are other form element for which that attribute can be added, we could create a new process function to add to the necessary form elements.  
While it is not a matter of sending sensitive data to an external site, I would dislike if the browser tries to correct the email address I enter in a form element.

**Comment by yorkshire-pudding** [comment]
Glad to see you've corrected your earlier reply @kiamlaluno - I was very confused
As a start, I used the D7 patch as recommended by @jenlampton .

I've broadened the scope to the password fields and the email address for reset password.

**Comment by indigoxela** [comment]
Wow, that was quick @yorkshire-pudding! :smile:

Re password and password_confirm:
I'd like to suggest to add `spellcheck` to the base form definition (includes/form.inc) so it's always set - even outside the user module's specific use of that form API items. Or are there any concerns?

The `autocorrect` and `autocapitalize` attributes aren't official ones, but seem to be vendor specific (Safari only). Should we add those? Or does the [official spellcheck attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) alone do the trick? Can't test that (no Apple stuff here).

**Comment by indigoxela** [comment]
> autocapitalize is included in the D7 patch; it perfectly feasible that...

I see. Now I found the documentation for [autocapitalize](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize). so that's an official attribute, not vendor specific. :wink: 

Still can't find anything for `autocorrect`, though, which might mean that HTML validation fails if we add it. We should check that, too, when testing.

**Comment by yorkshire-pudding** [comment]
> Still can't find anything for autocorrect, though, which might mean that HTML validation fails if we add it. We should check that, too, when testing.

It's listed [here as a non-standard attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#non-standard_attributes) for Safari only.

The [docs ](https://docs.backdropcms.org/form_api#attributes)don't explicitly say one way or another whether we can use or should avoid non-standard attributes. 

I think Safari is probably a wide enough case that we may want to cover it, if it doesn't cause any other issues.

**Comment by yorkshire-pudding** [comment]
Thanks for suggestions. I've implemented @indigoxela 's suggestion to define all password fields in the base definition as using `spellcheck="false"`

At @kiamlaluno 's suggestion
I've widened the coverage of usernames and email addresses that have `autocapitalize="none" autocorrect="off" spellcheck="false"` to include login form, create new account form, reset password form, user account form

**Comment by yorkshire-pudding** [comment]
Mmm - not sure why these changes are causing this test failure. It is across all PHP versions so it seems like it might be genuine, though I'm not disabling any fields.  Any ideas?

Test failure:

```
---- Form API: Form element validation (FormsTestCase) ----

Status    Group      Filename          Line    Function                            
------------------------------------------------------------------------------------------------------------------------
Fail      Other      form.test         490     testDisabledElements()                                                  
    The correct elements have the disabled property in the HTML code.
Error: Process completed with exit code 1.
```

**Comment by kiamlaluno** [comment]
Should not be `autocorrect="none"` too? [autocorrect="off" and autocapitalize="off" in login form are deprecated and may be not enough](https://www.drupal.org/project/drupal/issues/2487808) used `"none"` for both the attributes.

**Comment by argiepiano** [comment]
@yorkshire-pudding see my comment in the PR, which explains why the tests are failing.

**Comment by yorkshire-pudding** [comment]
I've re-configured it to avoid wiping out existing `#attributes`. Where the definition was already adding attributes, I kept it within, but where they were not already being added, I added outside.

**Comment by argiepiano** [comment]
@yorkshire-pudding thanks. I left another comment on how we go about setting spellcheck and possibly the other new attributes. Right now `theme_password()` forces `false` on `spellcheck` regardless of my form definition. I realize we want false always, but since this is a configurable element attribute, I believe we should follow the default way of treating these. That means that if I have a function that expressly sets spellcheck to true, the theming function should respect that.

I'm posting here for others to chime in as well.

**Comment by yorkshire-pudding** [comment]
@argiepiano - Thanks for confirming that. That way didn't work anyway- it caused an error with undefined index for `#attributes` - see the 7.4 test results at https://github.com/backdrop/backdrop/actions/runs/5320465001/jobs/9634272588?pr=4465

**Comment by argiepiano** [comment]
OK, I'm partially revising what I said above, but I believe there may be a valid case for doing this:

```php
function testing_stuff_test_form($form, &$form_state) {
  $form['password'] = array(
    '#type' => 'password',
    '#title' => 'Password',
    '#maxlength' => 64,
    '#size' => 15,
    '#disabled' => TRUE,
    '#attributes' => array(
      'spellcheck' => 'true',
    ),
  );

  return $form;
}
```

I know is an edge case, but who knows, someone may want a spellcheck (or other attributes) in the password field. Right now, with the code as is, my pre-setting of 'spellcheck' is ignored. 

Any thoughts?

**Comment by yorkshire-pudding** [comment]
I can't think of a use case for this, but that doesn't mean there isn't one, so I'm open to changing it.  However, I'm at a loss to know why it isn't possible to override and why one way of defining an array keyed value prevents overriding later, while another would allow it.  

As it is, I switched to the current method as I think I would have needed to do a more complex conditional code to account for the fact that attributes might not exist so I opted for the simpler measure.

**Comment by argiepiano** [comment]
@yorkshire-pudding I had several suggestions, so it's easier to submit an alternative PR. Since all of it is taken from your work, feel free to incorporate what I have (if you agree) and I'll close mine.  (Waiting for tests now)

My approach: instead of adding spellcheck and other attributes to low-level FAPI password element and password confirm form process function, I decided to keep the changes only for the high-level log in and password reset forms. Your PR did both things (low level and high level). My PR only does it at the high level. I figured that this allows maximum flexibility for developers using the password FAPI element to do whatever they want with spellcheck and other attributes, instead of forcing spellcheck=false every time.

**Comment by argiepiano** [comment]
OK, as per Zulip PM from @yorkshire-pudding, he pointed out that @indigoxela had requested the low-level password FAPI element to include spellcheck. I think that's fine, as long as it respect any attribute preset values sent to the FAPI elements for spellcheck rather than forcing spellcheck=false every time. I'll modify my PR later tonight to accommodate this.

**Comment by argiepiano** [comment]
I've followed the suggestion and added `spellcheck=false` as default to the FAPI elements `password` and `password_confirm`. @yorkshire-pudding, this is done in a slightly different way from your PR. Feel free to incorporate this into yours, and I'll close mine... I submitted an alternate one just for convenience.

**Comment by yorkshire-pudding** [comment]
Thanks @argiepiano for the suggestions and for making time to discuss with me.  I've amended my PR to reflect the suggestions and the new understanding I have from our discussion.

**Comment by argiepiano** [comment]
@yorkshire-pudding this looks good, but I've done a bit more digging regarding the html `password` input type. According to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password), this input type does not support the attribute `spellcheck` (scroll to the bottom of the page I linked there). 

So I'm wondering if adding this attribute is just a moot point? I can see how the other things in this PR are helpful, especially as it relates to user names and user emails.

**Comment by yorkshire-pudding** [comment]
> Ok, rereading the OP, I noticed your point about passwords and enhanced spell checks. So it looks like adding the attribute avoids this issue

Correct. It is not normally a problem except when the user clicks show password

**Comment by indigoxela** [comment]
Great progress here!

One last thing: as I suspected, the non-standard `autocorrect` attribute causes the validator to fail. But there's nothing we can do, I guess. Either support Apple devices, or pass HTML validation. :shrug: FWIW, we're not alone with that problem.

My suggestion is to set the attribute. It prevents user WTF with hard to debug login problems on vendor specific devices.

![autocorrect-attr](https://github.com/backdrop/backdrop-issues/assets/842066/1dc813c0-cf92-45df-85ee-ce9d9795dc9c)

BTW, the issue labels are a bit confusing currently. :wink:

**Comment by yorkshire-pudding** [comment]
It looks like it `autocorrect` is on its way into the specification - see https://github.com/whatwg/html/issues/3595 and https://github.com/whatwg/html/pull/5841 

> BTW, the issue labels are a bit confusing currently. 😉

Agree - I think @argiepiano must have added `pr - needs work` by mistake given his latest comment.

**Comment by quicksketch** [comment]
Yay, great work here @yorkshire-pudding, @kiamlaluno, @indigoxela, and @argiepiano! I merged https://github.com/backdrop/backdrop/pull/4465 into 1.x and 1.25.x!
