### ISSUE TITLE
FAPI element type `password_confirm` wipes out all preset attributes from the form element

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6157]
## Description of the bug

When creating a form that uses the Form API type `password_confirm`, all custom `#attributes` included in the form element definition are removed/ignored.

## Steps To Reproduce

To reproduce the behavior:
1. Create a form callback function that includes a `password_confirm` element AND contains a custom attribute such as `data-important-stuff`:

```php
  $form['password'] = array(
    '#type' => 'password_confirm',
    '#title' => 'Password',
    '#maxlength' => 64,
    '#size' => 15,
    '#attributes' => array(
      'data-important-stuff' => 'important-data-goes-here',
    ),
  );
  return $form;
```

2. Inspect the rendered output. Notice that the `data-important-stuff` attribute is not included

<img width="980" alt="Screen Shot 2023-06-20 at 3 01 12 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/8b2c9af6-b1dc-4e47-b35e-834b8ee3d4e2">

## Actual behavior

Custom attributes for the element are removed/not rendered.

## Expected behavior

The form element should include the custom attributes.

## Additional information

- Backdrop CMS version: 1.25.1
- PHP version: 8.1
- Browser(s) and their versions: Chrome
-----
PR https://github.com/backdrop/backdrop/pull/4467

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4467 ready for review and testing. To test, you can use the example I pasted in the OP.

**Comment by argiepiano** [comment]
Test failure in PHP 5 seems unrelated to the PR.

**Comment by kiamlaluno** [comment]
It is the test for enabling/disabling modules that fails. I have seen that failure in another PR; it's a random failure which is indeed not related to the PR.

**Comment by argiepiano** [comment]
Here's a tiny module to generate that form (for testing).
[testing_stuff.zip](https://github.com/backdrop/backdrop-issues/files/11807631/testing_stuff.zip)

**Comment by klonos** [comment]
Tried to close/reopen the PR multiple times in order to get the tests to pass green, however there seems to be an issue with tugboat sandboxes at the moment, and I am also getting the "Start and end date ..." know random failure. I'll try again in later.

Code looks good to me though 👍🏼

**Comment by indigoxela** [comment]
@argiepiano many thanks for your PR. :pray: I've left a question there.

**Comment by bugfolder** [comment]
Tested (with the provided test module) and confirmed that it works. Closed and reopened the PR, and all tests are running and passing (even though we're getting the Tugboat-over-quota message; presume that tests are running on the old Tugboat instance.) LGTM, WFM.

**Comment by quicksketch** [comment]
Thanks @argiepiano, @klonos, @bugfolder, @kiamlaluno, and @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/4467 into 1.x and 1.25.x.
