### ISSUE TITLE
On /admin/config/people/login, the default value for the "Identify users attempting to log in, using" field is not shown

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6162]
On /admin/config/people/login, the *Identify users attempting to log in, using* is rendered as in the following screenshot.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/79cfba57-8ede-4089-8743-13760f2a33d5)

This happens because the value for *flood_uid_only* in [user.flood.json](https://github.com/backdrop/backdrop/blob/1.x/core/modules/user/config/user.flood.json) is `"false"`, not `'0'` nor `'1'` [`user_login_settings()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.admin.inc/function/user_login_settings/1) uses for the *flood_uid_only* form element.

```php
  $form['user_limit_settings']['flood_uid_only'] = array(
    '#type' => 'radios',
    '#title' => t('Identify users attempting to log in, using'),
    '#options' => array(
      '0' => t('User ID and IP address combination'),
      '1' => t('User ID only'),
    ),
    '#default_value' => $flood_config->get('flood_uid_only'),
    FALSE => array(
      '#description' => ' Less secure, less likely to lock out users.',
    ),
    TRUE => array(
      '#description' => 'More secure, more likely to lock out users.',
    ),
  );
```

I verified this in a preview site created for a different issue.

I also checked what happens on my site.
With PHP 5.6 the default value for that form element is shown.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/c6090f0c-5f75-4669-bb28-94598c3358c0)

If I change the PHP version to PHP 8.0 when the form is shown, and then refresh the page from the browser, the form shows this error on the top.

> Invalid option false in Identify users attempting to log in, using element.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/afdc03bf-f760-445b-9e77-b8ad54cd5738)

If I change PHP version to PHP 8.1 before going to /admin/config/people/login, when I go to /admin/config/people/login, I do not get the error message, but the form element does not show the default value, like with the preview site.

> 
![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/e8d41da9-3717-4f99-850f-983aa3a8bc68)

**Comment by kiamlaluno** [comment]
I will provide a MR in the next 14 hours, if nobody does it before me.

**Comment by kiamlaluno** [comment]
As a side note, this only happens when the value for the *Identify users attempting to log in, using* form element is not changed, which means it stops to happen when the person visiting that form clicks on the *User ID and IP address combination* or the *User ID only* radio and saves the changes.

**Comment by kiamlaluno** [comment]
On the preview site, I imported the following configuration (the one used now from Backdrop) from /admin/config/development/configuration/single.

```json
{
    "_config_name": "user.flood",
    "flood_uid_only": "false",
    "flood_ip_limit": 50,
    "flood_ip_window": 3600,
    "flood_log_failed_attempts": 1,
    "flood_user_limit": 5,
    "flood_user_window": 21600
}
```

After I do that, the form element on admin/config/people/login appears as in the following screenshot.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/5fbb8ce8-5534-409c-a5da-2e043f125232)

I then imported the following configuration (the one the MR uses).

```json
{
    "_config_name": "user.flood",
    "flood_uid_only": "0",
    "flood_ip_limit": 50,
    "flood_ip_window": 3600,
    "flood_log_failed_attempts": 1,
    "flood_user_limit": 5,
    "flood_user_window": 21600
}
```

The form element on admin/config/people/login then appears as in the following screenshot.

> ![screenshot](https://github.com/backdrop/backdrop-issues/assets/29851/d2693750-fbe4-495c-97e1-241e9e34d9c1)

**Comment by indigoxela** [comment]
@kiamlaluno nice catch, this must have been an oversight in the early days. :+1:

I verified the bug with a fresh install on PHP 8.1, and that your tiny change fixes it properly. (The string "false" really never made sense, anyway.)

**Comment by klonos** [comment]
Thanks @kiamlaluno for raising this and providing a PR too 🙏🏼 

While we are fixing things around this form element and its config values, should we also fix this?:
```php
    FALSE => array(
      '#description' => ' Less secure, less likely to lock out users.',
    ),
    TRUE => array(
      '#description' => 'More secure, more likely to lock out users.',
    ),
```

...should be:
```php
   '1' => array(
      '#description' => ' Less secure, less likely to lock out users.',
    ),
   '0' => array(
      '#description' => 'More secure, more likely to lock out users.',
    ),
```

Also, while fixing the config value will stop the issue from happening in new installations, it won't fix it for existing sites. Should we add an update hook to fix existing config?

**Comment by argiepiano** [comment]
I agree we also need to fix existing installations with an update hook. While this fix is correct, it will only be applied to `user.flood.json` file in `core/modules/user/config`, but not in the config directory under `files` 

Right now, in any clean installation done before this fix (where the admin hasn't changed the values in that form), doing this:

`config_get('user.flood', 'flood_uid_only');`

Will return the **string** "false". When evaluated in an `if` statement, a string (any string, including the string "false") will be result in a truthy value, meaning that the site is actually not doing what is supposed to be doing.

By default, the intention is that the first value in the radios is selected (i.e. "User ID and IP address combination" is the default). BUT the if statement in line [1852](https://github.com/backdrop/backdrop/blob/91dd4955aec444f15db19a3ad9a6cbbbf204c08e/core/modules/user/user.module#L1852) of `user.module` results in a truthy value, meaning that in fact, in a clean installation done before this fix, the result is that the "User ID only" option will used (truthy value in that if statement).

The solution for the update hook is to:
1. Get the current value of  `flood_uid_only` in `user.flood.json` in the configuration directory - this can be done with `config_get`
2. If the value is the string "false", change that to "0"
3. If the value is not the string "false", do nothing, as the admin has already changed the erroneous default value

I'm setting this to NW.
5. If

**Comment by kiamlaluno** [comment]
May somebody verify whenever #6024 can influence this issue?
In that issue, I read:

> If the 0 option is first, #default_value doesn't work in radios. If the 0 option is second, it works properly in radios.

That means the options given for that form element should be given in the order used in this code.

```php
$form['user_limit_settings']['flood_uid_only'] = array(
  '#type' => 'radios',
  '#title' => t('Identify users attempting to log in, using'),
  '#options' => array(
    '1' => t('User ID only'),
    '0' => t('User ID and IP address combination'),
  ),
  '#default_value' => $flood_config->get('flood_uid_only'),
  '1' => array(
    '#description' => 'More secure, more likely to lock out users.',
  ),
  '0' => array(
    '#description' => ' Less secure, less likely to lock out users.',
  ),
);
```

**Comment by kiamlaluno** [comment]
There have been some random test failures, but now all is fine.

**Comment by indigoxela** [comment]
@kiamlaluno  I saw another problem, not directly related to this bug, but in code touched by this PR: the descriptions aren't translatable.

Should we fix this here, or should we add another issue to properly use `t()`? (Oh, and the space, in the second string looks odd.)

**Comment by kiamlaluno** [comment]
I changed the code in this MR. I think it is preferable to opening an issue to fix all the strings that are not translatable.

**Comment by indigoxela** [comment]
> As a side note, this type of issue will probably appear in other functions

Yes, we may see similar problems. And we'll fix them, as they pop up. :smirk:

**Comment by bugfolder** [comment]
Code reviewed. LGTM. (Coincidence, just dealt with this same issue in an Ubercart module.)

**Comment by quicksketch** [comment]
Thanks @bugfolder for the final review here! I merged https://github.com/backdrop/backdrop/pull/4468 into 1.x and 1.26.x. Thanks @kiamlaluno, @indigoxela, @argiepiano, @klonos, and @bugfolder!
