### ISSUE TITLE
Views: PHP 8.1 - Exposed Items Per Page of All causes error

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#6167]
## Description of the bug

In PHP 8.1, if you have a view with plenty of records and you use the full or mini pager and expose the items per page including the all option then it causes an error when someone selects All.

This was raised in the forum by forum user onyx:
https://forum.backdropcms.org/node/2914

## Steps To Reproduce

To reproduce the behavior:
1. Start with a backdrop site on PHP 8.1
2. Generate lots of node (Devel generate)
3. Modify the Manage Content view to expose the items per page and enable the All option
4. Go to Manage content and select All

## Actual behavior
Error:
```
Error
Error message
TypeError: Unsupported operand types: int * string in views_plugin_pager_full->query() (line 266 of /app/docroot/core/modules/views/plugins/views_plugin_pager_full.inc)
Unsupported operand types: int * string
```

![chrome_LfQQX0Kb1M](https://github.com/backdrop/backdrop-issues/assets/20357797/4eed549d-3a44-4dab-b1f4-ab9e720ccb54)

## Expected behavior
Shows All items

![chrome_962nYIhy5C](https://github.com/backdrop/backdrop-issues/assets/20357797/5d48f10c-ecfd-4096-b81e-5cc9737167e2)

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.25.1
- Web server and its version: apache
- PHP version: 8.1
- Database sever (MySQL or MariaDB?) and its version: mariadb 1.2
- Operating System and its version: ubuntu 20.04
- Browser(s) and their versions: n/a

<hr>
[PR added](https://github.com/backdrop/backdrop/pull/4469)

**Comment by klonos** [comment]
Small nitpick: the check for `!empty($_GET['items_per_page'])` is repeated in the `if` and the `elseif` that follows it, so I believe that we should move that one level up, in the `if ($this->items_per_page_exposed()) { ... }` check. In other words, change this:
```php
    if ($this->items_per_page_exposed()) {
      if (!empty($_GET['items_per_page']) && $_GET['items_per_page'] > 0) {
        $this->options['items_per_page'] = $_GET['items_per_page'];
      }
      elseif (!empty($_GET['items_per_page']) && $_GET['items_per_page'] == 'All' && $this->options['expose']['items_per_page_options_all']) {
        $this->options['items_per_page'] = 0;
      }
    }
```

to this:
```php
    if ($this->items_per_page_exposed() && !empty($_GET['items_per_page'])) {
      if (is_numeric($_GET['items_per_page']) && $_GET['items_per_page'] > 0) {
        $this->options['items_per_page'] = $_GET['items_per_page'];
      }
      elseif ($_GET['items_per_page'] == 'All' && $this->options['expose']['items_per_page_options_all']) {
        $this->options['items_per_page'] = 0;
      }
    }
```

**Comment by yorkshire-pudding** [comment]
@klonos 
The suggestion you make is a valid improvement for the original code, but the purpose of the PR is to fix a bug and I didn't create that duplication. Should wider code improvements be lumped in with a simple bug fix, or does it muddy the waters and make it less clear for the core committers?

**Comment by klonos** [comment]
@yorkshire-pudding I consider that a small change, and I usually include those in my PRs. You need to ask the questions: "Does this warrant a separate issue and a separate PR?" and "Would I or anyone else ever bother to raise a separate issue for this had this issue/PR here not have touched this part of the code?" ...and that should give you your answer 😉

**Comment by argiepiano** [comment]
The change looks good to me. RTBC again

**Comment by laryn** [comment]
Thank you @yorkshire-pudding, @argiepiano, and @klonos! Merged into `1.x` and `1.25.x`.
