### ISSUE TITLE
installer_browser_install_button_form() assigns a string to `$form['#attributes']['class']` 

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6168]
## Description of the bug

The form callback `installer_browser_install_button_form()` assigns a string to `$form['#attributes']['class']` instead of an array.

While this doesn't cause any immediate issue with this simple form (which basically provides the "Install" button once you select a project to install), it's inconsistent with all other core assignments of  `$form['#attributes']['class']` or `$element['#attributes']['class']`, which is always an array of classes. 

## Steps To Reproduce

There is no error or warning generated in core, but this was found because of a [contrib project](https://github.com/backdrop-contrib/scheduler/issues/22) that tried to do something like:

`if (in_array('node-form', $form['#attributes']['class'])) {}`

inside a `hook_form_alter()` implementation. This kind of check is very common in core for class attributes (it's kind of a miracle that this check is not done to this particular form - otherwise we would have seen the error).

If you wish to verify that `$form['#attributes']['core']` is a string after this form, you can implement a `hook_form_alter()` and output `dpm($form['#attributes']['class']);`  for every form. Then visit `admin/modules/install` and select a project to install, so that the "Install" button is shown.

## Actual behavior

The assignment is a string.

## Expected behavior

The assignment should be an array (of classes).

## Additional information

- Backdrop CMS version: 1.25.1

------

PR https://github.com/backdrop/backdrop/pull/4471

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4471 ready for testing and review.

**Comment by indigoxela** [comment]
@argiepiano  wow, how did we miss such an obvious bug for so long? :stuck_out_tongue: Will test your PR.

**Comment by indigoxela** [comment]
After testing, it turned out, that function backdrop_retrieve_form() already sets this class. And I couldn't think of any situation, where a form isn't run through that function. Or is there?

**Comment by herbdool** [comment]
Looks good.

**Comment by laryn** [comment]
Thanks to

 - @onyxnz for the initial discovery
 - @argiepiano for tracking down and fixing
 - @indigoxela, @herbdool, @djzwerg for testing and review!

Merged into 1.x and 1.25.x.
