### ISSUE TITLE
Missing clearfix class on two column layouts

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#617]
The `.l-container` element does not properly wrap around the columns within.  We need to add a clearfix to that element on both the two column and two column flipped layout. It would also be good to check the other layouts and make sure they don't also need the clearfix.

**Comment by quicksketch** [comment]
In our layout conversions, we eliminated use of clearfix in the layout templates themselves and manually do the clearfixes in the CSS. So to fix this, just add `.l-container` to the list of classes that have clearfix applied in the `layout.css` file in each layout.

**Comment by jenlampton** [comment]
ah! thanks :)

**Comment by quicksketch** [comment]
I checked the other layouts and they should be fine. The 1 column and 3/3/4 column already had the class clearfixed.
