### ISSUE TITLE
Warnings and deprecation notices on date views exposed filter when empty

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6171]
## Description of the bug

When using dates in exposed filter on more recent PHP (like 8.1), the empty value in the exposed form causes nagging.

## Steps To Reproduce

1. Create a content type with a date field (doesn't matter whether saved as timestamp or date)
2. Add content of that type
3. Create a view for that type, add the date as exposed filter - not required
4. Run the preview in admin UI or go to the newly created views page, don't set a date value

## Actual behavior

```
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in date_views_filter_handler_simple->get_filter_value() (line 118 of ...core/modules/date/views/date_views_filter_handler_simple.inc).
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in date_views_filter_handler_simple->get_filter_value() (line 118 of ...core/modules/date/views/date_views_filter_handler_simple.inc).
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in date_views_filter_handler_simple->get_filter_value() (line 118 of ...core/modules/date/views/date_views_filter_handler_simple.inc).
```

IF the input widget for that exposed filter is "text", another one pops up:

```
Warning: Undefined array key "date" in date_text_element_process() (line 357 of ...core/modules/date/date.elements.inc).
```

![php-nagging-date-exposed](https://github.com/backdrop/backdrop-issues/assets/842066/60ac595c-98ec-4e50-900b-1ac89ec284a4)

## Expected behavior

No nagging because of an optional filter – which is supposed to also be empty.

## Additional information

- Backdrop CMS version: latest dev
- Web server: Apache
- PHP version: 8.1
- Database: MariaDB

**Comment by indigoxela** [comment]
There's been some phpcs nagging, as I touched date.elements.inc previously. As the actual change here is rather small, I took the opportunity to fix those coding standard issues now.

The relevant changes to fix the reported problems are just two `isset()`.

**Comment by kiamlaluno** [comment]
Is the *This is a fixed date.* comment (which has been edited) really necessary? Either I do not understand it, or it does not seem to add anything that is already clear from the code.

**Comment by indigoxela** [comment]
> Is the This is a fixed date. comment (which has been edited) really necessary?

I don't know. :shrug: I had to edit it, as it was misleading. Might as well remove it - if there's consensus, that it's superfluous. :wink:

**Comment by bugfolder** [comment]
Tested: created a content type with a date field, created exposed filter on date. In PHP 7.4 there were no errors, but in PHP 8.1, watchdog log had 3 notices (as described in the original issue). Applying the patch from the PR eliminated the errors. WFM.

Code reviewed. Noting the preceding discussion of the comment, I'm in agreement that the comment doesn't really add anything since the presence of `isset(...)` conveys the same information, so I'll suggest removal. Code otherwise looks good.

**Comment by indigoxela** [comment]
@bugfolder many thanks for having a look, seems like I totally missed that.

I removed the pointless comment as requested, so the PR is ready for another review.

**Comment by bugfolder** [comment]
LGTM.

**Comment by quicksketch** [comment]
Thanks @indigoxela, @bugfolder, and @kiamlaluno! I merged https://github.com/backdrop/backdrop/pull/4475 into 1.x and 1.26.x.
