### ISSUE TITLE
Remove unused parameter $config_name from config_uninstall_config()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6175]
[`config_uninstall_config()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21config.inc/function/config_uninstall_config/1) is implemented using the following code.

```php
function config_uninstall_config($project, $config_name = NULL) {
  // If this is a theme key, load the matching template.php file.
  if (!backdrop_load('module', $project) && $theme_path = backdrop_get_path('theme', $project)) {
    if (file_exists($theme_path . '/template.php')) {
      include_once $theme_path . '/template.php';
    }
  }

  if ($configs = module_invoke($project, 'config_info')) {
    foreach ($configs as $config_name => $config_info) {
      if (isset($config_info['name_key'])) {
        $sub_names = config_get_names_with_prefix($config_name . '.');
        foreach ($sub_names as $sub_name) {
          config($sub_name)->delete();
        }
      }
      else {
        config($config_name)->delete();
      }
    }
  }
}
```

The local variable used in `foreach()` has the same name of the parameter passed to the function, which means the parameter value is overridden from the index values for the array returned by `module_invoke($module, 'config_info')`.

Since that parameter is not used from neither `config_uninstall_config()` nor the only function that calls `config_uninstall_config()`, the parameter can be removed from the function declaration.
If `config_uninstall_config()` is effectively supposed to delete values for those configuration objects that match the name passed in `$config_name`, its code needs to be changed.

IMO, the correct change is removing the second parameter from the function declaration. May somebody confirm this is correct?

**Comment by argiepiano** [comment]
My guess is that, whoever wrote that function, initially intended to have the option to possibly delete a single config for a module. But the code is clearly removing all config files for the given module, and even the code block states that clearly. So, I agree it'd be OK to remove that parameter from the function definition, given the fact that this is a helper function. A search in the contrib space shows only two uses of that function with only one parameter.

**Comment by kiamlaluno** [comment]
@argiepiano Thank you for looking at this.

**Comment by kiamlaluno** [comment]
I have updated the issue summary to show the current code, which was changed from recent commits.

**Comment by herbdool** [comment]
I agree with this change. Especially considering the second parameter didn't do anything.

**Comment by quicksketch** [comment]
Sounds good to me. It's pretty easy to delete a config with `$config->delete()` in any case. Though I do find it curious that we don't have a `config_delete()` function, seems like it should exist to match `config_clear()`, `config_set()`, etc. That's not the issue at hand though.

Thank you @herbdool for surfacing this issue again.

**Comment by quicksketch** [comment]
I merged this into 1.x for 1.30.0. We could use a change record for this, even though the removed parameter had no effect, so no code should be broken. This is intended to be a public API function, at least informing developers of the change would do no harm.
