### ISSUE TITLE
Remove periods from the labels of radios and checkboxes in the "Account settings" form

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6177]
As per the issue title, there are periods in the labels for:
- the `Require email verification when a visitor creates an account` checkbox
- the `When an email address is used as username, require a matching email address` checkbox
- the radio options for `When cancelling a user account`
- the `Enable signatures` checkbox
- the `Enable user pictures` checkbox

**Comment by bugfolder** [comment]
Code LGTM. Tested, WFM. Here's the admin page with periods removed:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/47da9ff2-a8ba-497a-9396-ba12a4c5503d)

**Comment by laryn** [comment]
Thank you @klonos and @bugfolder -- merged into `1.x` and `1.25.x`.
