### ISSUE TITLE
The page title still has the ID of page-title instead of a class

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#618]
We made a conscious effort to remove all the IDs from backdrop.  Looks like this one slipped through.  Let's take a poll and see how many people want it removed also, for 2.0.

Proposed change: 

```
<h1 id="page-title" class="title">Welcome</h1>
```

would become

```
<h1 class="page-title">Welcome</h1>
```

**Comment by quicksketch** [comment]
Doh, can't believe we missed that one. I'd advocate for removing `title` as well and just have it be `<h1 class="page-title">`.

**Comment by jenlampton** [comment]
I agree with that, I often want to target all block-titles, view-titles, and pane-titles together, but I very rarely want to include the page-title in that list.  Updating issue summary.

**Comment by tarekdj** [comment]
:+1:

**Comment by CaffeinatedJim** [comment]
To play devil's advocate here, is a class on an H1 needed at all?

I see there is a header h1 which is <h1 class="site-name">, but that could be targeted as: header > h1.

If it's the HTML5 thinking that multiple H1's are allowed, you are really only supposed to have one h1 per content section, so you would be able to target those also: article h1, section h1, nav h1, aside h1, etc...

**Comment by quicksketch** [comment]
That's not a bad point. The reason we have the class `.site-name` in the first place is because it's only an `<h1>` on the homepage. On all sub-pages, the site name becomes a `<div>`. Now the reason for all of that is because the class was created pre-HTML5. On the other hand, there is something nice about targeting via class name rather than markup tag, especially if using sub-themes. The less-specific class-based selector makes it easier to override.

**Comment by quicksketch** [comment]
@hellomrcat thanks for the PR! We need to update the CSS as well for all these changes. Could you search for `#page-title` in all CSS files and change theme to `.page-title`? In some places we're unnecessarily specific, using `h1#page-title`. This should be changed to just `.page-title`.

**Comment by quicksketch** [comment]
I merged this manually from the PR at https://github.com/backdrop/backdrop/pull/980. This does cause a small compatibility break for themes styling the page title, but better sooner rather than later.

Change notice created at https://api.backdropcms.org/node/43069.
