### ISSUE TITLE
[DX] Add user_role_has_permission function

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#6186]
## Description of the need

A module may want to do something conditional on whether a role has a permission.  Other functions can be used in a roundabout way, but this would be simpler.

## Proposed solution

A simple function called `user_role_has_permission` that takes a role name and a permission name and returns a boolean if the role has the permission.

## Alternatives that have been considered

For now, I've added this code in my module.

Is there a Drupal or Backdrop contributed module that accomplishes this?
no

## Additional information

Add any other information or screenshots that would help.

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes an additional function for modules to check whether a user role includes a permission.

<hr>
PR added at https://github.com/backdrop/backdrop/pull/4486

**Comment by yorkshire-pudding** [comment]
PR added at https://github.com/backdrop/backdrop/pull/4486 and is ready for review and testing.

**Comment by argiepiano** [comment]
I think this would be helpful. I've found myself needing something like this once in a while. Please see my comment in the PR.

**Comment by yorkshire-pudding** [comment]
Thanks @argiepiano - error fixed.

**Comment by kiamlaluno** [comment]
I left a comment in the PR about the data type to use with `@return`.

**Comment by yorkshire-pudding** [comment]
Thanks @kiamlaluno - Fixed
NB - there is a random test failure unconnected to this function.

**Comment by argiepiano** [comment]
> Should not the code calling `user_role_load()` check the function does not return `FALSE`? PHP throws an error when a Boolean value is used to access a property.

Good point!

**Comment by yorkshire-pudding** [comment]
Added a check. Thanks.

**Comment by yorkshire-pudding** [comment]
@argiepiano @kiamlaluno - either of you care to do a (hopefully) final check?

**Comment by kiamlaluno** [comment]
There is anything that needs to be changed in the code, as far as I can see.

I agree, there could be alternatives to using this function, but they are not as straight as this function. For example, `user_roles()` can return a list of roles with a permission, but:

- That function loads all the roles
- It loops over the roles array to remove the roles without that permission
- The function that called `user_roles()` should then check if the returned array contains the role it is interested in

**Comment by yorkshire-pudding** [comment]
Anyone like to update labels and add a milestone. I assume it will go into 1.26 as it is a feature.

**Comment by klonos** [comment]
@yorkshire-pudding small nitpick:  I've added a comment about adding an `@since` in the docblock, which is something we do for newly introduced functions.

**Comment by yorkshire-pudding** [comment]
Done @klonos

**Comment by quicksketch** [comment]
I've been hesitant to include this function since it's not actually utilized anywhere in core. At the very least we may need test coverage for a function that is otherwise unused. I'll see if I can put something together here.

**Comment by quicksketch** [comment]
There we go, not hard at all since we already had a very similar test: `testUserPermissionChanges`. Just 3 lines and now we're covered. I updated the PR and if tests pass we should be ready here.

**Comment by quicksketch** [comment]
Well the test coverage found that this function was not working with PHP 5.6, so that's something. I updated the PR again.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4486 into 1.x for 1.26.0. Thanks @yorkshire-pudding, @argiepiano, @klonos, and @kiamlaluno!
