### ISSUE TITLE
Line breaks lost in custom block body

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#619]
Steps to reproduce:

1) Create a custom block at `admin/structure/block` 
1a) be sure to add some line breaks, or hard returns into the block body
2) Place the block into a layout at `admin/structure/layouts`
2a) the first step is to select the block from a list of blocks (it should be near the top)
2b) the second step is to review the text in the block before inserting.

You'll notice that in this second step, any line breaks you entered in step 1a will not display.

You'll also notice that if you do not correct the problem in this preview, and insert the block into the layout as-is, that your line breaks will not display on the rendered layout.

**Comment by tarekdj** [comment]
PR: https://github.com/backdrop/backdrop/pull/701

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/701. Thanks!
