### ISSUE TITLE
[UX] Regression: Labels for fields are being set to "Hidden" by default - Should be "Above" instead

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6192]
## Description of the need

Every single time I add a new field, I have to go to respective content type's default display to choose one of the _Above_ or _Inline_ options instead of _Hidden_ set by default. 

## Proposed solution

Not sure which one of two options - _Above_ or _Inline_ - make more sense, but either one set by default would be a better and intuitive setting instead of _Hidden_. It would save little time for developers and website admins, and would not confuse new Backdrop users scratching their heads why having added new fields and populating them with values they see only values without any labels explaining what is what.

**Comment by klonos** [comment]
Hmm 🤔 ...I thought that "Inline" was the default and we only hid the label for long text fields (or only the body field specifically), but I just tested with various field types, such as date, link, number etc., and it is indeed set to "Hidden" by default.

FTR: I have tried the same on a vanilla D10 site, and the labels are always set to "Above".

**Comment by klonos** [comment]
...I've tried the same on a vanilla D7 site, and fields labels are always set to "Above" by default on an existing content type. So I'm going to call this a UX regression and mark the issue as a bug.

PS: When creating a _new_ content type, the label for the default body field is indeed set to "Hidden". I don't think that that should be changed.

**Comment by olafgrabienski** [comment]
Hiding field labels was discussed and introduced in #317. Interesting follow-up at #3140.

**Comment by argiepiano** [comment]
Like the OP, I've always found the blanket hidden-by-default label for all fields annoying and less helpful. It was interesting to read this was intentional and not a regression. I'd love to see #3140 implemented. Should we close this one?

**Comment by kiamlaluno** [comment]
Letting the fields have their own defaults for the label placement seems a good idea, to me. It is better than to always use the same setting for all the fields.

**Comment by klonos** [comment]
> Hiding field labels was discussed and introduced in #317. ...

Ah yes. Thanks @olafgrabienski 🙏🏼 ...yet another issue where back in the days I was pushing for telemetry before making such changes 😅 

> ... I'd love to see #3140 implemented. Should we close this one?

Same here. After refreshing my memory, reading through #317 made me (re)realize that #3140 would be a more flexible solution. So yes, lets close this one and revive that old issue.

**Comment by alanmels** [comment]
I'm so bad at searching issues. Thanks @olafgrabienski for finding the earlier discussion on this. Indeed interesting read.
