### ISSUE TITLE
Fork jQuery.once, to maintain compatibility with future versions of jQuery

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6195]
## Description of the bug

The version of jquery.once.js shipped with core is rather old (1.2.6, released back in [2008](https://blog.jquery.com/2008/05/24/jquery-1-2-6-released/)).

There's a "newer" version 2.2.3 (from [2019](https://github.com/RobLoach/jquery-once/releases/tag/2.2.3), but that one's **incompatible**. It would require to rewrite all code that uses the "once" feature. Even worse, that version also seems abandoned now.

jQuery.once is used many times in core and also in contrib. We can't switch to an incompatible version.

Drupal did a radical thing, it switched to a [vanilla javascript approach](https://www.drupal.org/node/3158256), forcing all usage to rewrite to that new approach. With _backwards compatibility_ in mind, Backdrop can't (and shouldn't) do that.

**Why bothering, anyway?**

Because jQuery.once uses a method, that's _deprecated_ in jQuery 3.3: [isFunction](https://api.jquery.com/jquery.isfunction/) (Backdrop 1.26, which will get released in September, will additionally ship with jQuery 3.7.)

Note: it's still functional, so there's no urgent need, but sooner or later we'll have to decide, as isFunction() will get removed in jQuery 4.0.

**Good news, the code is simple!**

All we'd have to do is to replace `$.isFunction` with a `typeof` statement (twice). But that means, we'd fork that plugin. And that needs a decision. See the [Source code](https://github.com/backdrop/backdrop/blob/1.x/core/misc/jquery.once.js#L66).

**Comment by yorkshire-pudding** [comment]
Would 'forking' in this instance, just mean that we change it in core, with some documentation? Or is it bigger than that?

**Comment by indigoxela** [comment]
> Would 'forking' in this instance, just mean that we change it in core, with some documentation?

Exactly that. Change two lines of code, update comments, update meta info in system_library_info().

**Comment by yorkshire-pudding** [comment]
I can't see any issue with that; it's not like if it is that old that it's going to be updated and overwrite our changes.

**Comment by argiepiano** [comment]
Can we consider switching to a vanilla JS `once()` core function, like in Drupal (and make all changes in core), but provide the original `jquery.once()` library (with a deprecation notice perhaps) to preserve compatibility for contrib modules? It seems like switching to Vanilla JS may present fewer problems for the future.

**Comment by indigoxela** [comment]
> Can we consider switching to a vanilla JS once() core function, like in Drupal...

@argiepiano I don't think so. At least, not before 2.x. The way the once feature is used – in core and in contrib (and custom) - means, that it has to be with jQuery. Switching to vanilla js means, we need to change code everywhere that feature is used (85 times in core alone). And that means, all contrib/custom usage has to get updated, too.

Example: `$('table#field-overview', context).once('field-overview', function () {`

This acts on jQuery objects.

On the other hand, the plugin is small (just a few lines of code). Maintaining it in core shouldn't be too much of a burden. Vanilla js would only be beneficial, if we chose to get rid of jQuery, which we don't.

**Comment by argiepiano** [comment]
Ah, got it

**Comment by kiamlaluno** [comment]
Even if the plan is to get ride of jQuery, that must wait for 2.x.

We can change our jquery.once.js and replace any use of $.isFunction.

**Comment by herbdool** [comment]
Wow, that file is shorter than I thought. Mostly comments. Yes, let's fork it.

**Comment by indigoxela** [comment]
Many thanks everyone, for your feedback. :pray:

Here we go, a [PR](https://github.com/backdrop/backdrop/pull/4498) is available for testing and review.

How to test:

Nothing should change, actually. This library is used in many places, like for dropbuttons, responsive tables, contextual links...
An easy way to test is the Layout admin interface on /admin/structure/layouts.

**Comment by indigoxela** [comment]
As the code change here is relatively small, I could take the opportunity to fix the phpcs nagging re array declaration widths in the same file (code I've touched before). Is that OK?

**Comment by herbdool** [comment]
Sure, thanks!

**Comment by jenlampton** [comment]
PR needs a rebase, but code LGTM

**Comment by quicksketch** [comment]
I updated https://github.com/backdrop/backdrop/pull/4498 to resolve it with the 1.x branch. The coding standards issue was fixed separately so this PR is now even smaller. I elaborated a little on the documentation and linked back to this issue for more detail.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4498 into 1.x for 1.26.0. Thanks so much @indigoxela for looking at all of our dependencies!
