### ISSUE TITLE
Token in field descriptions not working unless in fields that handle multiple values

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6196]
## Description of the bug

Tokens in field descriptions (on node form) aren't replaced in several field types.

## Steps To Reproduce

1. Add fields of types that do not handle multiple values on their own (like text) to content type
2. Add a description (help text) to that field via field UI (on /admin/structure/types/manage/TYPE/fields/field_FIELD)
3. Note that every field type has that token browser available
4. Use tokens from the token browser on that admin form (date or whatever)
5. Save the field instance
6. Now create a new node of that type (/node/add/TYPE)

## Actual behavior

The tokens are there plain text, no replacement, unless it's a field widget that handles multiple values, like the file or image field.

![widget-token](https://github.com/backdrop/backdrop-issues/assets/842066/1f04f09d-c69e-4419-a03b-ceaddcc03ec7)

## Expected behavior

As the token browser is available, I'd also expect the tokens to get replaced.

## Additional information

- Backdrop CMS version: latest dev
- PHP version: 8.1

The token handling came into core with https://github.com/backdrop/backdrop-issues/issues/480, but the only place function token_replace() is used is [here](https://github.com/backdrop/backdrop/blob/1.x/core/modules/field/field.form.inc#L106), which means, only when some conditions are met. NOT in field_multiple_value_form(), which runs on most field types.

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4495) is available for testing and review.

BTW, another option would be to remove the token browser from fields, that use the multi-value form, but that doesn't seem logical to me. :wink:

**Comment by argiepiano** [comment]
The issue is in `theme_file_upload_help()` where `$descriptions` uses the original widget help text without replacing tokens. The solution is to do a token_replace in line 273.

**Comment by indigoxela** [comment]
@argiepiano seems like our brains are perfectly in sync. :laughing: I just came to the same conclusion and pushed another commit to fix single value image fields.

**Comment by argiepiano** [comment]
In the meantime I've found that Paragraphs has the same problem in `paragraphs_field_multiple_value_form()` and will file an issue there.

**Comment by argiepiano** [comment]
Tested and reviews, RTBC!

**Comment by laryn** [comment]
Thank you @indigoxela and @argiepiano -- merged into `1.x` and `1.25.x`.
