### ISSUE TITLE
Hidden date field saves null values when editing an existing node, producing notices

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6198]
## Description of the bug

Editing an existing node with a date field that's hidden via `'#access' => FALSE` saves a null value to the database. This, in turn, produces notices when viewing the node: `Warning: Trying to access array offset on value of type null in theme_date_display_combination() (line 219 of /Users/XXX/Sites/localhost/kmta/core/modules/date/date.theme.inc).` This happens regardless of the widget [EDIT: the HTML5 widget handles this correctly].

## Steps To Reproduce

In order to reproduce the problem, you have to alter the node_form to hide the date field.

1. Add a field called `field_test_date` to the Page content type. Use any widget [EDIT: OTHER THAN HTML5]
2. Set the Default Valuie in the field UI to "No default value"
3. In a custom module, implement `hook_form_node_form_alter(&$form, &$form_state);`
4. In that hook, set the access to false, as in `$form['field_test_date'][LANGUAGE_NONE][0]['#access'] = FALSE;`
5. Create a page node. Check the database table `field_data_field_test_date`. Nothing is saved for the new node. 👍🏽 
6. Edit that same page node (no need to change anything). Click `Save`

You'll get the notices above. If you inspect the table for the field you'll see a NULL value being stored. 👎🏽 

## Actual behavior

Null value gets saved for the date. Notices are thrown when viewing the node.

## Expected behavior

Nothing should get saved, since the field is hidden and its default value is none. 

## Additional information

Add any other information that could help, such as:

- PHP 8.1
- Backdrop 1.25.1

I've tested the same in Drupal 7. As expected, D7 does not save a null value for the date, and therefore the notices are not produced

---------

PR https://github.com/backdrop/backdrop/pull/4499

**Comment by argiepiano** [comment]
FOUND IT! This was fixed in D7's Date module. We even have a cross-port issue from 2019 that was never done.

https://github.com/backdrop/backdrop-issues/issues/4060

The solution is issue listed as 2990189 in that list.

Although originally created to fix a related issue, this fix also works for this situation. It creates an array structure for the element items, which didn't exist before.

I'll submit a PR probably tonight.

**Comment by indigoxela** [comment]
I can confirm the really odd behavior of date fields with `#access` set to FALSE in a hook. Every second edit, a NULL value ends up in the database.

This happens with all three date field types ('date', 'datestamp', 'datetime') and all widget types *other than* the HTML5 widget, when no default value is set. Date only (without time) fields are also affected.

The field display setting plays a role, of course, as the "Date and time" display (which is the default), triggers the otherwise hidden problem of NULL values saved to the database. But the actual problem is, that those NULL values should never land in the db table.

I tested with **hook_form_alter()** and with **hook_field_widget_form_alter()**. As long as I don't also set '#date_items' to an array with the key "value", a bunch of warnings (and deprecation warnings on PHP 8.1) show up.

I can confirm, that the PR fixes the problem. :+1:

**Comment by indigoxela** [comment]
Hm, but wait... the NULL value gets removed from the db, as soon as the node gets saved again. If the node doesn't get saved, the value stays in there. And as the *display* of these values causes warnings – don't we also need an update hook for those faulty values?

**Comment by argiepiano** [comment]
@indigoxela thanks much for testing! Yes, I'll add that update hook.

**Comment by argiepiano** [comment]
@indigoxela, I've added the update hook to remove entries with null values. Thanks!

**Comment by indigoxela** [comment]
> I've added the update hook to remove entries with null values

@argiepiano  Many thanks for your quick reaction. :pray:  Two more "details", and we should be done here. See my comments on your PR.

**Comment by argiepiano** [comment]
Thanks, @indigoxela. I've addressed your comments. For some reason, Tugboat is not being built for the changes.

**Comment by indigoxela** [comment]
@argiepiano excellent! Many thanks for your quick response. :pray:

Back to "works for me". And sort of "half reviewed". Another pair of eyes for review would be great, just to make sure, we didn't miss anything.

**Comment by quicksketch** [comment]
Thanks @argiepiano and @indigoxela! I reviewed and merged https://github.com/backdrop/backdrop/pull/4499 into 1.x and 1.25.x.

Thanks for cross-linking to the existing D7 porting issue. With both your testing and it being a patch from D7 I'm confident in this solution. I gave the update hook a focused read-over and it looks good to me too. Thanks!
