### ISSUE TITLE
Files folder location during install and documentation

### ISSUE THREAD

**Issue by DavidHernandez** [backdrop/backdrop-issues#620]
Hi there,

On the requirements verification step, while trying to install Backdrop. If the files folder doesn't exists or it doesn't have permissions, appears an error, like the error of the settings file. But the files error, doesn't specify the location of the files folder. Where should I create the folder? Inside the root folder or inside sites folder like Drupal?

The settings.php error says "./settings.php" while the files folder says "files".

![backdrop-install](https://cloud.githubusercontent.com/assets/877002/5799195/d2bc931e-9fcf-11e4-9fee-a3c3795e7b9c.png)

Then, I went to the install documentation: https://backdropcms.org/guide/installation and there doesn't say anything about the files folder either.

**Comment by BWPanda** [comment]
The 'files' directory can be created in the root directory (e.g. './files', which works the same way that the 'sites/default' directory worked in D7) or you can create it in a sub-directory of 'sites' (as per 'sites.php').

**Comment by DavidHernandez** [comment]
Yep, I know that. This wasn't a support request. I think the message on the installation should be updated. And the Install steps on the documentation should explain the files folder too.

**Comment by BWPanda** [comment]
Ah, sorry, I misinterpreted:
> Where should I create the folder?

Changed labels.

**Comment by serundeputy** [comment]
so the error message should say:
'./files' instead of 'files'?

can we indicate correct permissions here too or is it conditional on user:group ownership config?

**Comment by quicksketch** [comment]
Hm, my initial thought was to explain this all in English, but since the files directory can change locations, using a description like "files directory in the root" or something like that won't always be the case.

We're also already using `./` to indicate settings.php's location (as seen in the screenshot), so I think using `./files` for consistency sounds like a good idea.

**Comment by klonos** [comment]
Yep, ```./files``` seems consistent with what we already have.

**Comment by BWPanda** [comment]
I believe this has been fixed. The code for this used to be `$directories[] = 'files';` but now it's `$directories[] = conf_path() . '/files';`. Re-open if I'm mistaken.
