### ISSUE TITLE
Color module vs PHP 8.1+

### ISSUE THREAD

**Issue by onyxnz** [backdrop/backdrop-issues#6201]
Color is not fully ready for PHP8.1+

## Steps To Reproduce

To reproduce the behavior:
1. Install site on PHP 8.1-enabled web server
2. Develop site
3. Check DBLOG for errors

## Actual behavior

Deprecated function: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in color_save_configuration() (line 621 of /var/www/clients/client1/web4/web/core/modules/color/color.module).

## Expected behavior

No error

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.25.1
- Web server and its version: nginx/1.18.0
- PHP version: 8.1.22-fpm
- Database sever (MySQL or MariaDB?) and its version: MySQL, MariaDB, or equivalent version 10.6.12-MariaDB-0ubuntu0.22.04.1
- Operating System and its version: Ubuntu 22.04

**Comment by onyxnz** [comment]
Line 621 of color.module could for instance become:
 if (!is_null($filename) && file_exists($filename)) {

**Comment by indigoxela** [comment]
@onyxnz many thanks for taking the time to report. :pray: 

However, I'm currently not able to reproduce the Deprecated nagging on PHP 8.1, so there might be a step missing.

Question: which theme are you using? Is it a subtheme? Which themes are enabled?

As this seems to happen in function color_save_configuration(), it might have to do with a custom theme.

**Comment by onyxnz** [comment]
I'm using Bootstrap Lite, somewhat customised. I've just tested with Basis 1.251, cleared cache, same error message. 
I added before line 621:  if(is_null($filename)){dpm($stylesheet);dpm($theme_name);}
and cleared cache...
result=
colors.css
materialize

So I will remove that Materialize, thanks, and notify it's maintainer.
