### ISSUE TITLE
Appearance page operations links are missing classes

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6205]
## Description of the bug

The Appearance / List Themes page attempts to provide classes for operations links but it is coming out as underscores:
![image](https://github.com/backdrop/backdrop-issues/assets/871421/e9b94198-848e-4575-b892-81d61acc2d60)

## Steps To Reproduce

To reproduce the behavior:
1. Go to 'Appearance'
2. Inspect the operation links by any of the themes (e.g. Enable, Disable, etc.)

**Comment by bugfolder** [comment]
Verified the issue, verified that the patch fixes the problem. WFM.

Code also LGTM.

**Comment by quicksketch** [comment]
Thanks @laryn and @bugfolder! Merged https://github.com/backdrop/backdrop/pull/4505 into 1.x and 1.25.xx.

**Comment by klonos** [comment]
Sorry to reopen this folks. Small PR to also fix the example provided in system.api.php: https://github.com/backdrop/backdrop/pull/4533

**Comment by laryn** [comment]
Thanks @klonos, I've merged the expanded documentation into `1.x`.
