### ISSUE TITLE
jQuery Core 3.7.1 got released

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6211]
## Description of the task

Part of the [ongoing task](https://github.com/backdrop/backdrop-issues/issues/2493) to keep libraries up to date.

They released [3.7.1 recently](https://blog.jquery.com/2023/08/28/jquery-3-7-1-released-reliable-table-row-dimensions/)

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4507) is available for testing and review.

**Comment by jenlampton** [comment]
Code LGTM.

**Comment by quicksketch** [comment]
Thanks @indigoxela! I merged https://github.com/backdrop/backdrop-issues/issues/6211 into 1.x for 1.26.0.
