### ISSUE TITLE
Update the telemetry module to report the CKEditor versions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6214]
In order to support removing ckeditor 4 from Backdrop core in version 2.x, we will need telemetry data to show how many sites have switched from ckeditor 4 to ckeditor 5.

We will need to report which major version(s) of CKeditor sites are using, including those that are using both versions at the same time. 

Implementation:
* The core `ckeditor` module will provide `ckeditor_version` data
* The contrib `ckeditor5` module will provide `ckeditor_version5` data
* The contrib `ckeditor5` module will provide `ckeditor_multiple` data, and test for the existance of ckeditor version 4.

**Comment by jenlampton** [comment]
Current PR adds the data for CKE4 only.

**Comment by quicksketch** [comment]
This is a great idea. I posted feedback in the PR.

Overall I think the split of logic between ckeditor and ckeditor5 module sounds good. It's vaguely possible that "CKEditor 6" might come out, but in such a situation we could move the `cke_multiple` value to a new location if needed.

I don't think it affects the approach of this PR, but a note that CKEditor 5's version numbers are represented as major numbers. The current module uses `38.0.1`, but that will be incremented to 39, 40, etc as new versions come out. So if we want to analyze how many sites are using CKEditor 5, we'll need to add up those different major version numbers. If we're really only concerned with how many sites run 4 vs 5 vs both, maybe we should instead (or additionally) report this as 3 possible values under a single key for `ckeditor_versions` (or something)

- ckeditor4
- ckeditor5
- multiple

That would provide a lot less granular information but also be a lot easier to output useful information from on the telemetry page.

**Comment by bugfolder** [comment]
I tested this. Found a typo (I think), left a suggested change in the PR. After making that change, this test code
```
$telemetry_info = telemetry_get_info();
dpm($telemetry_info,'$telemetry_info');
$telemetry_data = telemetry_get_data();
dpm($telemetry_data,'$telemetry_data');
```

gives this (correct) result:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/ff8bd55b-d5dd-4c5d-b61a-70b583f9dfa4)

**Comment by jenlampton** [comment]
Thanks @bugfolder, I've merged your PR against my PR.

**Comment by bugfolder** [comment]
WFM, LGTM.

**Comment by quicksketch** [comment]
Thanks @jenlampton and @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4510 into 1.x for 1.26.0.
