### ISSUE TITLE
Replace "Drupal" with "Backdrop" in admin-tabs.css

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#6218]
The `@file` tag in [core/themes/basis/css/component/admin-tabs.css](https://docs.backdropcms.org/api/backdrop/core%21themes%21basis%21css%21component%21admin-tabs.css/1) uses the following description.

> Drupal Admin Tabs styles.

It should be *Backdrop Admin Tabs styles.* similarly to the description used in [core/themes/basis/css/component/backdrop-form.css](https://docs.backdropcms.org/api/backdrop/core%21themes%21basis%21css%21component%21backdrop-form.css/1).

> Backdrop form styling.

**Comment by bugfolder** [comment]
Code looks good. No testing needed.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno and @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4515 into 1.x and 1.25.x.
