### ISSUE TITLE
Remove the Views "Import" form

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#622]
Apparently we still have the view form at `admin/structure/views/import`, which is largely redundant with the single-import option in Config management. It appears that this old import form also expects *PHP* input, which is left-over from the D7 version of the module. We should remove this form, as well as the permission for importing Views. All that functionality is now built-into config management (and in a less-dangerous implementation).

**Comment by tarekdj** [comment]
PR: https://github.com/backdrop/backdrop/pull/705

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/705. Thanks @tarekdj!
