### ISSUE TITLE
[UX] Bartik Fieldset bottom margin accidentally overwritten

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6221]
## Description of the bug

If you are using the node form in the Bartik theme, and have a field that comes after the body, the label for that field gets hidden by the text format wrapper (see screenshots below).

This happens because the CSS from filter module adds a `margin: 0;` with the selector `.filter-wrapper`. This selector is more specific than the one the bartik module uses `fieldset` to add the bottom margin that's needed here: 	`margin-bottom: 32px;`

**Before the fix:**

<img width="723" alt="Screenshot 2023-09-14 at 4 36 56 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/640d3af5-82a7-4387-915d-06c14218896b">

**After the fix:**

<img width="713" alt="Screenshot 2023-09-14 at 5 26 11 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/1c781979-39c6-4901-a4ff-ffece8fcdf1c">

## Steps To Reproduce

To reproduce the behavior:

1. Install backdrop
2. Switch admin theme to bartik
3. visit node/add/post
4. check positioning of the label for image field (should be below body field)

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version:
- Web server and its version:
- PHP version: 
- Database sever (MySQL or MariaDB?) and its version:
- Operating System and its version:
- Browser(s) and their versions:

**Comment by bugfolder** [comment]
Tested, it works, WFM. Code LGTM.

**Comment by quicksketch** [comment]
Thanks @jenlampton and @bugfolder! Merged https://github.com/backdrop/backdrop/pull/4517 into 1.x and 1.26.x.
