### ISSUE TITLE
Telemetry UI doesn't show the module name as specified

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6222]
## Description of the bug

While working on the telemetry integration for CKEditor, [here](https://github.com/backdrop/backdrop/pull/4510/files),  I discovered that even if you define a project via the API, it does not appear properly in the telemetry report.

It is supposed to appear in parentheses below the metric name, in the left hand column. Instead, the telemetry label was showing in that location. 

**Before:**
<img width="947" alt="Screenshot 2023-09-14 at 5 05 31 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/66d76c14-46be-463c-b043-7811481f5522">

**After:**
<img width="948" alt="Screenshot 2023-09-14 at 4 59 56 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/5d23a1a3-6f50-440d-ab90-a4185722973b">

This was likely missed before, because the only projects displayed were in core (and thus showing "System" instead of the project name)

## Steps To Reproduce

To reproduce the behavior:
1. Create a custom module that implements `hook_telemetry_info()` and `hook_telemetry_data()`
2. Visit the telemetry report at `admin/reports/telemetry`
3. Confirm your project name does not appear as intended.

## Additional information

Please note, the screenshots above are in Bartik because I am also working on https://github.com/backdrop/backdrop-issues/issues/6221 at the same time - that is not related to this issue :)

Add any other information that could help, such as:
- Backdrop CMS version:
- Web server and its version:
- PHP version: 
- Database sever (MySQL or MariaDB?) and its version:
- Operating System and its version:
- Browser(s) and their versions:

**Comment by quicksketch** [comment]
Oops! A simple mistake to fix though. Thank you! I have merged your PR at https://github.com/backdrop/backdrop/pull/4516 into 1.x and 1.25.x.
