### ISSUE TITLE
Contextual Links not appearing on hover

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6223]
## Description of the bug

A regression was introduced in https://github.com/backdrop/backdrop-issues/issues/6149, where contextual links no longer show up on hover. This appears to be because the replacement for the jQuery `.hover()` is not simply `.on('hover')` but combining `.on('mouseenter')` and `.on('mouseleave')`. See the deprecation notice at https://api.jquery.com/hover/

## Steps To Reproduce

To reproduce the behavior:
1. Log in as an admin user that can use contextual links.
2. Hover over the default homepage blocks and views, you should get contextual menus on hover.
3. No menus are shown.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.26.0-preview
- Browser(s) and their versions: Firefox, Chromium. Latest versions

**Comment by laryn** [comment]
Thanks @quicksketch for the quick fix, and @bugfolder for finding this before the release, and for testing and review. Looks great -- merged into `1.x` in time for `1.26.0`.
