### ISSUE TITLE
The link to "Run updates" in admin_bar does not point to the update script

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#623]
In Drupal 7 the script lived at `update.php` in Backdrop it lives at `/core/update.php'.
We need to update this link.

**Comment by tarekdj** [comment]
PR: https://github.com/backdrop/backdrop/pull/706

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/706. Thanks @tarekdj!!
