### ISSUE TITLE
[DX] Explain why you can't count on module functions in update hooks

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#6233]
I just learned the reason why one can't rely on module functions in update hooks. This seems like an easy error for someone to make since doing so would work normally most of the time (updating enabled modules), but could crash the update under particular circumstances (updating a disabled module), and crashing updates are particularly hard to debug and particularly anxiety-producing for those that they happen to.

To help forestall this issue, I suggest adding to the documentation of `hook_update_N()` to explain why using module functions is problematic. PR to follow.

**Comment by argiepiano** [comment]
LGTM! I didn't know this. I just tested it and, viola, the update hook for disabled modules are still called! This documentation is very helpful - it will save people many head-scratching moments.

**Comment by argiepiano** [comment]
I'm not sure what milestone I should pick for documentation.

**Comment by bugfolder** [comment]
I think this is safe to put into a bugfix release, since it doesn't actually change anything. (Thx for the quick review!)

**Comment by argiepiano** [comment]
Done!

**Comment by laryn** [comment]
Thanks @bugfolder and @argiepiano -- merged!
