### ISSUE TITLE
PHP 8.1 Deprecated function Notice when passing NULL to trim()

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6235]
## Description of the bug

In some scenarios the function in the subject line is giving the error:

```php
Deprecated function: trim(): Passing null to parameter #1 ($string) of type string is deprecated in views_handler_field->render_text() (line 1199 of /var/www/html/docroot/core/modules/views/handlers/views_handler_field.inc). 
```

## Steps To Reproduce

Quote from https://www.drupal.org/project/views/issues/3313970

> Create a view for a content type and trim the whitespace of one or more fields. In my case, I have a field that I am using as a link. The link goes to the node ID and I am Trimming the Whitespace from the field.

## Additional information

The [line 1199](https://github.com/backdrop/backdrop/blob/1982f486c2d40c570851059a6f63c14dabf41011/core/modules/views/handlers/views_handler_field.inc#L1199) looks as:

      $value = trim($value);

and the longer function's very first lines look as:

```php
  /**
   * Perform an advanced text render for the item.
   *
   * This is separated out as some fields may render lists, and this allows
   * each item to be handled individually.
   */
  function render_text($alter) {
    $value = $this->last_render;

    if (!empty($alter['alter_text']) && $alter['text'] !== '') {
      $tokens = $this->get_render_tokens($alter);
      $value = $this->render_altered($alter, $tokens);
    }

    if (!empty($this->options['alter']['trim_whitespace'])) {
      $value = trim($value);
    }
```

Running a very simple condition check in the beginning of the function takes care of the error message:

```php
  function render_text($alter) {
    $value = $this->last_render;
    if (empty($value)) {
      return;
    }
```

but the patch on https://www.drupal.org/files/issues/2022-10-11/Deprecated_function_trim_Passing_null_to_parameter_1_string-3313970-8.patch for the referenced above Drupal 7 issue looks as this:

```php
if (!is_null($value) && !empty($this->options['alter']['trim_whitespace'])) {
       $value = trim($value);
     }

```

Before filing a PR wanted to hear others' opinion on this. Thanks!

**Comment by alanmels** [comment]
Another reference point: https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation

**Comment by oadaeh** [comment]
It really depends on the context of the function and the variable. You are going to have to consider the whole function to determine if it's okay to bail out early or not. If `$value` has no meaning if it's empty (not just NULL), then the first one is fine. If on the other hand, other things have meaning, regardless of `$value`, then the second one is the one to go with, which is probably what I would go with.

If we didn't have to worry about backward compatibility, you could use `$value = trim($value ?? '');` and that would work. It's okay that `$value` === '', just not NULL.

BTW, here are three lists of PHP functions that take string values that can no longer be NULL:
- https://github.com/craigfrancis/php-allow-null-rfc/blob/main/functions-change.md
- https://github.com/craigfrancis/php-allow-null-rfc/blob/main/functions-maybe.md
- https://github.com/craigfrancis/php-allow-null-rfc/blob/main/functions-other.md

I found those lists from the SO answer: https://stackoverflow.com/a/74069811

There are more functions for the other scalar values, but I haven't found any lists of those.

**Comment by herbdool** [comment]
I think the second option is better. We should be returning something. So this one:

```
if (!is_null($value) && !empty($this->options['alter']['trim_whitespace'])) {
       $value = trim($value);
     }
```

**Comment by nbayaman** [comment]
Also am having the issue. Signing up

**Comment by yorkshire-pudding** [comment]
I've reviewed the code and it is line with the discussion on here.  I haven't been able to reproduce the error though (so can't test); perhaps a factor is missing in the steps to reproduce?

Here's what I did
1. Create a view of a content type (in this case, I used the Animal content type from Devel generate)
2. Set several fields (including body) to "Remove whitespace" under "Rewrite results"
3. On one node in content type, delete the values in the fields
4. View the view

Anything I'm missing to reproduce?

**Comment by alanmels** [comment]
I'd share the Views page that is giving the error, however since it has lot's of components, you wouldn't be able to make it work, unless you re-create all of those content types and fields. Have you tried the steps to replicate the error given on https://www.drupal.org/project/views/issues/3313970? Also read that thread to see the same error on Drupal 7 was fixed and committed into core. So as yourself said it's a simple PHP 8.1 requirement compliance fix.

**Comment by yorkshire-pudding** [comment]
I did look at the Drupal issue but I wasn't clear what was so special about that use case that this shouldn't work (i.e. create the error) with any field where we remove whitespace and the field is empty.

Code looks fine, so I removed that label; I just can't remove the `pr - needs testing` label as I can't reproduce.

**Comment by indigoxela** [comment]
Found a way to reproduce: create a view of all content, use a field only available in on of the content types, and check "Remove whitespace" in the rewrite results section.

With out the patch, a "Deprecated function: trim(): Passing null to parameter..." warning for every entry of another node type, with the patch applied - silence. Works for me! :+1:

**Comment by laryn** [comment]
Thanks @alanmels for filing and fixing! Thanks to @yorkshire-pudding, @indigoxela, @oadaeh, and @herbdool for reviews and feedback. Good to see you in the queues @nbayaman -- welcome!
Merged this into `1.x` and `1.26.x`.
