### ISSUE TITLE
Image browser attached to field doesnt work if field is in a modal

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#6236]
## Description of the bug

If you implement a `managed_file` field and add the `#browser_view` key to the array, the button to browse existing files appears, and when clicked, launches the image browser in a modal. This works fine on forms like the node page, but what if your field is already in a modal? Well, the image browser modal pops out, and when you click the insert button closes the original modal too. 

## Steps To Reproduce

Simplest is to hack core: go to `core/layout/includes/block.hero.inc` and add `'#browser_view' => 'image_library',` to the `$form['image']` array in the `form()` function. Then start add a Hero block to any layout, and you get this:

![Screenshot 2023-09-30 140307](https://github.com/backdrop/backdrop-issues/assets/1042283/a9bb33c9-6519-4da4-ba1c-3f2c5e656dc2)

## Actual behavior

But if you try to select existing file, after clicking `insert` it closes the Hero block config modal. The browser works fine if you add the `#browser_view` key to a field that's not in a modal. (Feel free to hack another core or contrib `managed_file` field to see that it works fine otherwise).

## Expected behavior

Clicking `insert` should return you to your previous modal, with the selected image active in the image field.

**Comment by laryn** [comment]
@docwilmot One minor issue I saw in the code (an extra `;`) but I can confirm that the PR fixes the issue as I experienced here, with an image field in a Paragraph being edited through the front end modal editing:

 - https://github.com/backdrop-contrib/paragraphs/issues/152

WFM!

**Comment by docwilmot** [comment]
Fixed stray semicolon

**Comment by quicksketch** [comment]
@docwilmot Could you check if this suggested change is reasonable? https://github.com/backdrop/backdrop/pull/4526/files#r1348192527

**Comment by quicksketch** [comment]
Thanks for the quick update @docwilmot! I re-tested and the new selector is getting used. I merged https://github.com/backdrop/backdrop/pull/4526 into 1.x and 1.26.x. Thanks to you and @laryn for reviewing!
