### ISSUE TITLE
Admin bar 'adminBarPermissionsSetupHelp' function does not check whether the element is present 

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#6244]
## Description of the bug

`adminBarPermissionsSetupHelp()` in core/modules/admin_bar/js/admin_bar.admin.js works on the permission page to remind users that if they enable the "Use administration bar" permission for a role they should also enable "Use administration pages" and vice versa.

If one or both of those permissions are not present on the page (i.e. not just hidden by the core filter function) then a console error and warning (jQuery 3 only for warning) is generated.

I came across this issue while testing Filter Permissions for jQuery compatibility (see https://github.com/backdrop-contrib/filter_perms/issues/20) and @argiepiano narrowed it down to this function.  I'm not aware of any other modules that filter permissions like this. While Filter Permissions can look to help ensure that this UI helper is not lost if one of these permissions is enabled, it can't fix this issue.

Filter Permissions still fulfils a purpose in preventing `max_input_vars` errors and also slow loading errors where people have a lot of permissions.

## Steps To Reproduce

To reproduce the behavior:
1. Install Filter Permissions (`filter_perms`) and enable
2. Navigate to admin/config/people/permissions
3. enter developer mode (F12) and select Console
4. Click on a module and click apply (note this error doesn't appear if both Admin Bar and System are selected)

## Actual behavior
Permissions are filtered but errors and warning (jquery 3) are visible in Console

<details>
<summary>Error that appears for jquery 1</summary>

```
admin_bar.admin.js?s1wqkm:21 Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at HTMLTableElement.<anonymous> (admin_bar.admin.js?s1wqkm:21:80)
    at Function.each (jquery.1.12.js?v=1.12.4:2:2881)
    at n.fn.init.each (jquery.1.12.js?v=1.12.4:2:846)
    at $.fn.once (jquery.once.js?v=1.2.6:71:47)
    at Object.attach (admin_bar.admin.js?s1wqkm:13:32)
    at Object.<anonymous> (backdrop.js?v=1.26.0:73:12)
    at Function.each (jquery.1.12.js?v=1.12.4:2:2931)
    at Backdrop.attachBehaviors (backdrop.js?v=1.26.0:71:5)
    at HTMLDocument.<anonymous> (backdrop.js?v=1.26.0:699:12)
    at i (jquery.1.12.js?v=1.12.4:2:27449)
(anonymous) @ admin_bar.admin.js?s1wqkm:21
each @ jquery.1.12.js?v=1.12.4:2
each @ jquery.1.12.js?v=1.12.4:2
$.fn.once @ jquery.once.js?v=1.2.6:71
attach @ admin_bar.admin.js?s1wqkm:13
(anonymous) @ backdrop.js?v=1.26.0:73
each @ jquery.1.12.js?v=1.12.4:2
Backdrop.attachBehaviors @ backdrop.js?v=1.26.0:71
(anonymous) @ backdrop.js?v=1.26.0:699
i @ jquery.1.12.js?v=1.12.4:2
fireWith @ jquery.1.12.js?v=1.12.4:2
ready @ jquery.1.12.js?v=1.12.4:2
K @ jquery.1.12.js?v=1.12.4:2
```

</details>

<details>
<summary>warning that appears for jQuery v3 only</summary>

```
jquery.js?v=3.7.1:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'firstChild') TypeError: Cannot read properties of undefined (reading 'firstChild')
    at HTMLTableElement.<anonymous> (https://slartibartfast.lndo.site/core/modules/admin_bar/js/admin_bar.admin.js?s1wq63:21:80)
    at Function.each (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:3129)
    at obj.<computed>.each (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:1594)
    at $.fn.once (https://slartibartfast.lndo.site/core/misc/jquery.once.js?v=1.2.6:71:47)
    at Object.attach (https://slartibartfast.lndo.site/core/modules/admin_bar/js/admin_bar.admin.js?s1wq63:13:32)
    at Object.<anonymous> (https://slartibartfast.lndo.site/core/misc/backdrop.js?v=1.26.0:73:12)
    at Function.each (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:3179)
    at Backdrop.attachBehaviors (https://slartibartfast.lndo.site/core/misc/backdrop.js?v=1.26.0:71:5)
    at HTMLDocument.<anonymous> (https://slartibartfast.lndo.site/core/misc/backdrop.js?v=1.26.0:699:12)
    at e (https://slartibartfast.lndo.site/core/misc/jquery.js?v=3.7.1:2:27028) undefined
ce.Deferred.exceptionHook @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
(anonymous) @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
fire @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
ready @ jquery.js?v=3.7.1:2
P @ jquery.js?v=3.7.1:2
```
</details>

<details>
<summary>Error that appears for jQuery3</summary>

```
jquery.js?v=3.7.1:2 Uncaught TypeError: Cannot read properties of undefined (reading 'firstChild')
    at HTMLTableElement.<anonymous> (admin_bar.admin.js?s1wq63:21:80)
    at Function.each (jquery.js?v=3.7.1:2:3129)
    at obj.<computed>.each (jquery.js?v=3.7.1:2:1594)
    at $.fn.once (jquery.once.js?v=1.2.6:71:47)
    at Object.attach (admin_bar.admin.js?s1wq63:13:32)
    at Object.<anonymous> (backdrop.js?v=1.26.0:73:12)
    at Function.each (jquery.js?v=3.7.1:2:3179)
    at Backdrop.attachBehaviors (backdrop.js?v=1.26.0:71:5)
    at HTMLDocument.<anonymous> (backdrop.js?v=1.26.0:699:12)
    at e (jquery.js?v=3.7.1:2:27028)
(anonymous) @ admin_bar.admin.js?s1wq63:21
each @ jquery.js?v=3.7.1:2
each @ jquery.js?v=3.7.1:2
$.fn.once @ jquery.once.js?v=1.2.6:71
attach @ admin_bar.admin.js?s1wq63:13
(anonymous) @ backdrop.js?v=1.26.0:73
each @ jquery.js?v=3.7.1:2
Backdrop.attachBehaviors @ backdrop.js?v=1.26.0:71
(anonymous) @ backdrop.js?v=1.26.0:699
e @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
ce.readyException @ jquery.js?v=3.7.1:2
(anonymous) @ jquery.js?v=3.7.1:2
e @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
(anonymous) @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
fire @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
t @ jquery.js?v=3.7.1:2
setTimeout (async)
(anonymous) @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
fire @ jquery.js?v=3.7.1:2
c @ jquery.js?v=3.7.1:2
fireWith @ jquery.js?v=3.7.1:2
ready @ jquery.js?v=3.7.1:2
P @ jquery.js?v=3.7.1:2
```

</details>

## Expected behavior

Filtering happens with no console error.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: tested on 1.25.1 and 1.26.0

<hr>
PR - backdrop/backdrop/pull/4529

**Comment by yorkshire-pudding** [comment]
Hi @izmeez . Thank you for taking the time to look at this; it is much appreciated.

> 1. On user permissions page, if both "Access administration bar" and "Use the administration pages" are not checked and only one of them is checked, does saving the settings result in a warning message or are the settings saved?

What normally happens if you select one of those permissions is you get a popup like this:
![image](https://github.com/backdrop/backdrop-issues/assets/20357797/739340c3-9746-48a3-98bd-f4fc2ba9f228)

If you then click ok both the permissions are added; if you click cancel only the original permission is added.

> First, I find the default backdrop user permission page confusing because it has two filter options: "Filter" and "Filter list". But this is a separate issue.

_Default_
![image](https://github.com/backdrop/backdrop-issues/assets/20357797/89165bdd-99cc-4ede-b531-86560f5e5803)

_With Filter Permissions_
![image](https://github.com/backdrop/backdrop-issues/assets/20357797/f7e798ed-da5b-4608-8dcd-0d7fb0a23f83)


I assume you mean "Filter" and "Filter Permissions". This only happens if you install Filter Permissions; people install this if they have a combination of factors (e.g. lots of roles, lots of granular permissions, paragraph permissions etc) which means there are a lot of permission checkboxes on the screen - this can mean that the page takes a long time to load and/or the changes fail (silently) to save.  The core filter hides them but they are still there; this is not a review slot for Filter Permissions - if you don't need it, then don't use it. For many people, the core filter will be fine, but for sites that do need Filter Permissions, it can be a lifesaver.

> Without the filter_perm module if only one of the settings described above is enabled for a role the settings are saved without any warnings and the message "The changes have been saved". This is what I observed with both jQuery3 and legacy jQuery1. I am not sure if this is the typical behaviour or an aberration in my environment?

That doesn't sound right; try clearing caches and check that your browser is not blocking popups.

**Comment by klonos** [comment]
@yorkshire-pudding a bit of radical thinking re an approach to solve this: while only having this warning pop up when both relevant permissions are present may seem like the right approach (defensive coding really), I believe that we are sorta swiping dust under the carpet. How I would expect this to work ideally is to have the warning pop up when either of the checkboxes are checked (as it works currently) regardless of whether the counterpart checkbox is visible/present or not. So instead of basically disabling this feature when either of the checkboxes have been hidden (filtered out) how about tweaking how the filtering works in this page, and making sure that when one of these checkboxes is shown, then so is the other?

I realize that such a solution would be more elaborate, but it would work as expected without having to disable that warning (which is there for a good reason).

The alternative is to have a warning (not JS browser - a "proper" `backdrop_set_message()` warning) when one of these checkboxes has been ticked while the other one not.

**Comment by yorkshire-pudding** [comment]
Hi @klonos - I am less confident making wider changes in JS/jQuery than I am in PHP, but I believe what you are suggesting is already the case by the latest release of "Filter Permissions".

As at present, the only scenario where one of these will not be on the page is with Filter Permissions (I'm not aware of any other contrib module that does similar, though it is possible someone has a custom module doing something like this), then I have fixed it in that module so those two modules' permissions - "Administration Bar" and "System" will always be shown together if one is selected with an info message to explain why.

With the core filter, if you filter to admin bar and select that then the warning still works, and still updates the other permission (if you click OK) as it is only hidden; it is still present on the page. 

What this change will do is when someone filters (in Filter Permissions) by a different module (e.g. Node) then the console error won't appear; it's not supressing the warning as that permission can't be enabled at that time as neither of those two permissions are not present anyway.

I hope that makes sense but if not, perhaps I need to do a video to explain this better.

**Comment by yorkshire-pudding** [comment]
Thanks for taking another look @izmeez 

> 2\. I think it is filter permissions that provides an information message at the top about the need for both permissions. I like this, but it only shows if the focus is narrowed to the "Administration Bar" module. Maybe, it should occur whenever both of those permissions are visible?

This info message shows to explain to users of Filter Permissions why two modules have been selected if they only selected one:
- If they select "Administration Bar" then "System" is also selected and the info message shown
- If they select "System" then "Administration Bar" is also selected and the info message shown 

> 1. Personally, I do not think popups should be used anywhere in backdrop. I have no idea where else they may be used and may never know with my usual settings of not allowing them. This is clearly a separate issue for core

I generally agree with you and I don't think they are widely used in core, but some things only work with javascript. If you want to react to a form event, javascript is the language, whereas PHP can do server side messages.

**Comment by yorkshire-pudding** [comment]
> Maybe the message should also show when all modules permissions are visible.

I don't agree; most times people go to permission page, they will not be adjusting those permissions.

> Nonetheless, I believe the message has greater utility and should be considered for inclusion in core.

That should probably be a separate feature request. In theory, it may be possible to do without a popup but it would need someone who knows JS a bit better to say. I don't think there is any point in having the message display all the time.

**Comment by yorkshire-pudding** [comment]
@izmeez - this one:
![image](https://github.com/backdrop/backdrop-issues/assets/20357797/633a48bd-f604-476c-b2c9-4ff0d2153585)

**Comment by yorkshire-pudding** [comment]
@izmeez Yes - fine to leave that

**Comment by quicksketch** [comment]
Thanks @yorkshire-pudding, @izmeez, and @klonos! I've merged https://github.com/backdrop/backdrop/pull/4529 into 1.x and 1.26.x.

**Comment by klonos** [comment]
I've filed #6283 as a follow-up 😉
