### ISSUE TITLE
Incorrect link on the "File system" page 

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6245]
## Description of the bug

This line https://github.com/backdrop/backdrop/blob/1982f486c2d40c570851059a6f63c14dabf41011/core/modules/system/system.admin.inc#L1854 contains incorrect link:

```php
    '#description' => t('An existing local file system path for storing private files. It should be writable by Backdrop and not accessible over the web. See the online handbook for <a href="@handbook">more information about securing private files</a>.', array('@handbook' => 'https://backdropcms.org/user-guide/file-system')),
```

## Steps To Reproduce

To reproduce the behavior:
1. Go to '/admin/config/media/file-system'
2. Click on 'more information about securing private files'
3. Find no information about private file system on https://backdropcms.org/user-guide/file-system

## Expected behavior

The link should be not https://backdropcms.org/user-guide/file-system, but https://docs.backdropcms.org/documentation/managing-file-locations-and-access, where the private files system is actually explained.

## Additional information

Documentation for file system for Drupal 7 is all located on a single page on https://www.drupal.org/docs/7/core/modules/file/overview. For some reason, we have the same information split into two different pages on Backdrop: https://docs.backdropcms.org/documentation/php-configuration-for-files and https://docs.backdropcms.org/documentation/managing-file-locations-and-access

**Comment by quicksketch** [comment]
Thanks @alanmels for the report and fix! Thanks @izmeez for reviewing. I merged https://github.com/backdrop/backdrop/pull/4531 into 1.x and 1.26.x.
