### ISSUE TITLE
how we can coordinate porting modules?

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#625]
Today @enzolutions asked a great question:

"How we can coordinate the module migrations, because I detect email and link are already in project for other members in backdrop-contrib, I just want to avoid double effort"

**Comment by jenlampton** [comment]
This was my answer:
```
it's important to check the issue queue on Drupal.org to make sure someone else has not already asked the current maintainers about porting to / supporting the module for Backdrop, and is not already working on a port.

You can comment on that issue and let the people working on the port know that you are also interested in supporting / maintaining the Backdrop version, and they can add you to the list of current maintainers when the project gets added to backdrop contrib.

If you need an example of how to politely ask the current maintainers, here's one I did yesterday: 
https://www.drupal.org/node/2409899

**Comment by chrisherberte** [comment]
This answer could be added as "Step 1" in the Converting modules page https://api.backdropcms.org/node/28621

**Comment by tjdjours** [comment]
>This answer could be added as "Step 1" in the Converting modules page https://api.backdropcms.org/node/28621

And to add to that,   /modules/README.txt

I glossed over the documentation and then came up empty after looking where I'd think to find info like this.

**Comment by docwilmot** [comment]
Yep we need better docs; I'll work some more on that this weekend.
I noticed the other day that when @quicksketch made the forum repo for me to work on, I couldnt actually push to it until he granted access. That could be a solution there. What about @quicksketch or @jenlampton create an empty repo for anyone who asks, without requirements being met, but only grant push access after the person has a working-looking port on their personal Git acct? That way as soon as a person starts porting, there is a folder there to let everyone know theyre working on it. But its not official till you guys are happy and its pushed.
And the rule for people who already have access will be to create an empty repo before you start, to let everyone know.
What you think?

**Comment by jenlampton** [comment]
I updated the page at https://api.backdropcms.org/node/28621 to include a note about posting in the drupal.org issue queue.

**Comment by kreynen** [comment]
I'm a big fan of any process the promotes coordination and collaboration... as long as it doesn't discourage someone from jumping in and just getting things done.  @quicksketch committed some changes I made to the text of https://github.com/backdrop-ops/contrib this morning.  Most of those changes are about licensing, but I also thought it was important to make it clear that potential contributors don't need to wait to be added to the Backdrop Contrib group to get started.

I would argue strongly against any process that requires a small number of people to take any type of action before someone can start contributing/sharing code.  IMHO, changes made to https://www.drupal.org/project/projectapplications process have really damaged the Drupal contrib community/experience.  Unless new developers complete 3 "bonus" reviews, they currently wait 42+ weeks before some all powerful wizard emerges from behind a current to grant the project namespace and packaged releases...

https://www.drupal.org/project/issues/projectapplications?status=14&page=1

While I understand the desire to improve the quality of the code in contrib, encouraging new "developers" who may know nothing about Drupal (or even PHP) to provide reviews of modules isn't a great first experience for the professional developer types so many people claim D8 is going to attract.  If https://www.drupal.org/project/media_youtube went through the new project review process today, it is unlikely the project would be promoted to a full project.  If I was asked to design a process to discourage new contributions to an open source project, Drupal's current process would be an excellent start.

While asking if any current maintainers are interested in supporting a Backdrop version of a module is the polite thing to do, getting a project started on GitHub should be fast and easy.  If there is a delay to moderate what ends up being in an "official" module list, that's fine... but anyone with a GitHub account should be encouraged to contribute a fork/port/upgrade of any project to their own GitHub repo as soon as they start working on it.

I've also started a discussion about a distributed approach to update status on Reddit http://www.reddit.com/r/backdrop/comments/2tf0ns/thoughts_on_this_approach_to_a_light_weight/.  Same idea.  Avoid centralized systems that a small number of people have complete control over... even when we like the people currently in control :)

**Comment by quicksketch** [comment]
Thanks @kreynen for your changes to the contrib author agreement. It's definitely an improvement.

I agree that we shouldn't force users to be in the backdrop-contrib group in order to share their code. With Github, they already have the ability to put their code anywhere without asking anyone. However, we have a couple reasons we want/need to maintain an official group:

- We need the ability to transfer abandoned projects between users while maintaining the issue queue, without the participation of the original author.
- We need the ability to fix security holes in projects without the participation of the original author, or remove that module in the event that a security hole cannot be solved.

We can't do these things on Github if a user has exclusive ownership over a project, so that's why the Backdrop Contrib group exists. I also think sharing the code with a larger group encourages collaboration and should ease the responsibility of maintenance. 

That said, we are trying to make the contrib application process as easy as possible. We're not requiring a lot of in-depth knowledge or reviews, but we do require the person confirm the agreement. The review we do essentially just confirms they follow the agreement for their first project to set them on the right path.

**Comment by kreynen** [comment]
Maintaining a list/directory of vetted, well supported modules is great.  Even limiting it to GPLv2 makes sense.  It just shouldn't be the only (or even the default) way start writing/porting/improving a project.

As long as I'm free to maintain a distribution that is a GPLv3 fork of Backdrop with APLv3 modules and Apache2.0 themes, I'm happy... not that I'll ever do that, but I want to be free to it.

**Comment by sirkitree** [comment]
I've started using the "backdrop-port" tag to issues I create when asking if the maintainers would be open to helping with a backdrop port in any project. This way would could get a list of projects on drupal.org that have open issues or intentions of porting.

**Comment by jenlampton** [comment]
thanks @kreynen for the great feedback, as usual. I'm doing some more work on the contrib readme now to try and make it more clear that joining the contrib group is optional (though encouraged, because that's how you get a security review).

I think anyone should feel confident in throwing up their own contrib repo, as long as we have a way to communicate about what's going on so we don't get six people porting pathauto at the same time.  I'm also fine with that place being the drupal.org queue while we're porting things (Thanks @sirkitree for the tag, great idea).

Eventually, we'd like to allow people who create modules, themes, and layouts to add a node for each project onto the backdropcms.org site that will define the canonical source for each project.  Though most of the time that will be the backdrop-contrib group, it will not be a requirement.

**Comment by quicksketch** [comment]
Here's Jen's latest PR to further clarify the purposes of the Backdrop Contrib group: https://github.com/backdrop-ops/contrib/pull/38

I think it looks good, other than some formatting. The text looks great to me.

**Comment by jenlampton** [comment]
I'm also going to add here that people have started using the [maintainer application](https://github.com/backdrop-ops/contrib/issues) queue as a place to report that work is being done on modules.  Since new maintainers often post there which modules they are working on anyway, it makes sense to keep the chatter of "hey, I'm working on X" over there as well (as long as we also let the current maintainers know what's up).
