### ISSUE TITLE
Update label CKEditor to "CKEditor 4" throughout core

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6250]
## Description of the need

The core module `ckeditor` should distinguish itself from the contrib module `ckeditor5` by using the label "CKEditor 4" wherever possible, including in the status report messages, text editor label, and in the .info file. This will help prevent confusion when there are both CKEditor 4 and 5 modules in core.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/4540. I didn't change _every_ instance of `CKEditor` to `CKEditor 4`. I converted the following:

- Any displayed label or description in the admin interface.
- Any summary in function docblocks (the first sentence) and in all hooks.
- At the top of every file in CKEditor 4 module (e.g. css, js, inc files).

I did not update references within extended docblock descriptions (such as parameter descriptions), since it would have been a much larger set of changes re-wrapping all the the docblocks, and redundant when CKEditor can be mentioned 10+ times within a docblock.

**Comment by indigoxela** [comment]
@quicksketch  This looks great! :+1: Actually ready to go, but phpcs nags, because you previously contributed a lot to the files now changed (git blame in our GHA...).

The actual change seems small enough to add those coding standard fixes, I guess. Or, if you prefer not to mix those in, go ahead and merge. :wink:

**Comment by quicksketch** [comment]
Thanks @indigoxela! I've merged https://github.com/backdrop/backdrop/pull/4540 into 1.x and 1.26.x.
