### ISSUE TITLE
Add gitter badge for Backdrop-contrib room

### ISSUE THREAD

**Issue by enzolutions** [backdrop/backdrop-issues#626]
Hi folks

Maybe you can consider add in http://backdropcms.org the badge to notify people there is a room to talk about Backdrop contrib module.

Check this badget

```
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/backdrop-contrib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
```

**Comment by klonos** [comment]
It's actually backdropcms.org

**Comment by Gormartsen** [comment]
Let's add it here for sure: https://github.com/backdrop/backdrop

**Comment by jenlampton** [comment]
I added one here :) https://github.com/backdrop/backdrop-issues

**Comment by jenlampton** [comment]
Also it is linked already from https://backdropcms.org/resources
