### ISSUE TITLE
Make mobile menu toggle text configurable

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6264]
## Description of the need

Right now the mobile menu toggle text is hardcoded (though translated) as `Menu`. Does it seem reasonable to folks to allow that text to be adjusted on a per menu block basis? (ie. when configuring the block, it defaults to `Menu` but can be overwritten)
```
      $data['content']['#prefix'] = theme('menu_toggle', array(
        'enabled' => $config['toggle'],
        'id' => $id,
        'text' => t('Menu'),
      ));
```

I am considering a case where there are potentially two toggles (in different parts of the page) and it would be helpful to be able to use different language for each. At first I thought I'd just override `theme_menu_toggle` but I really don't have enough information to grab onto inside that function to know much about the particulars of the menu.

If we add this, it could only appear underneath the "Display menu toggle..." option if it was selected:

![image](https://github.com/backdrop/backdrop-issues/assets/871421/8015498c-daa8-43e7-812b-15f9e641669a)

**Comment by laryn** [comment]
I've added a PR. One thing I wasn't sure about was if a user-entered block setting can be translated (I don't think the translatable config applies here, right?). In this case, if it's still the default value of `Menu` I supply the translated value, otherwise the user-input value.

**Comment by hosef** [comment]
Is there a module that provides translation for user defined config entries?

**Comment by laryn** [comment]
[Translatable config is in core](https://github.com/backdrop/backdrop-issues/issues/704), but I'm not sure if it can be applied to block settings. @herbdool do you know?

**Comment by herbdool** [comment]
@laryn I'm not sure. We'd have to test it. Since it's on a per-block basis then it would need to know the UUID. Perhaps this is a use case for separating out blocks from layouts.

**Comment by bugfolder** [comment]
Looks good to me. Does the translation question affect this PR, or is it a separate issue?

**Comment by herbdool** [comment]
I think the translation affects this, since it currently can be translated.

`config_get_translated()` ultimately calls `t()` after it determines if a key is translatable. In this particular case we know it is, so maybe we can just call `t()` on whatever is in the setting, default or not. We don't need to figure out how to call them config translated function.

**Comment by laryn** [comment]
Ready for another review, I think I've addressed all of the feedback.

**Comment by klonos** [comment]
Did a quick code review and left a few suggestions.

**Comment by laryn** [comment]
@klonos I have one question for clarification back to you in the PR.

**Comment by laryn** [comment]
@klonos and @bugfolder -- the PR has been updated.

**Comment by klonos** [comment]
Thanks @laryn 🙏🏼 ...code looks good - I only left a small nit pick re the comment. The tugboat demo failed to spin up, so I couldn't test, but committing that small change might get it to work.

Also, can you please add your name to the issue summary, indicating that you are advocating for this feature to get into 1.27? (unless you are already advocating for another feature that is)

**Comment by laryn** [comment]
Your nit was committed. I think we need final testing and a milestone on this one.

**Comment by nattywebdev** [comment]
I tested this and it worked well - something I've wanted to see for a while. However, when there is no menu text, the icon doesn't show at all. Is that by design? Option to display just the icon (no text) would seem useful!

**Comment by laryn** [comment]
@nattywebdev I'm not seeing what you describe -- can you explain how you got this result? I blanked out the text on the tugboat sandbox and it just shows the hamburger:
![CleanShot 2023-12-15 at 09 11 06@2x](https://github.com/backdrop/backdrop-issues/assets/871421/aa3e261b-5080-4331-99f2-b2156d9c2adc)

**Comment by nattywebdev** [comment]
Looks like a Chrome issue - works fine in Firefox.

**Comment by laryn** [comment]
This has been updated and ready for further testing/review.

**Comment by quicksketch** [comment]
I gave https://github.com/backdrop/backdrop/pull/4545 another review and made a small tweak to move the `t()` call out of the theme function and up a level into where the theme function is called. I tested in Tugboat and it works great. Merged into 1.x for 1.27.0.
