### ISSUE TITLE
[DX] Document `_color_preview_theme()`

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#6266]
## Description of the bug

[_color_preview_theme()](https://github.com/backdrop/backdrop/blob/1aad8f554c9dc3ede5f35babe70518e44376f1a9/core/modules/color/color.module#L472) in `color.module` has no docblock.

## Expected behavior

It should have a code comment.

**Comment by docwilmot** [comment]
Why do we keep bumping this? Its just a doc block.

**Comment by bugfolder** [comment]
LGTM, WFM.

**Comment by quicksketch** [comment]
Thanks @docwilmot! Sorry for the delay. Thanks @bugfolder for giving this one the green light!

**Comment by quicksketch** [comment]
And my apologies @bugfolder, I accidentally credited @herbdool when I made the commit and left you out. :frowning_face: :facepalm: We really appreciate your contributions and I'm sorry I messed up that commit.

**Comment by bugfolder** [comment]
>  I'm sorry I messed up that commit.

No worries! 🥱
