### ISSUE TITLE
jquery.form.js references non-existent source map jquery.form.min.js.map

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#6267]
## Description of the bug

We have a regression of the issue described in #3090 

## Steps To Reproduce

To reproduce the behavior:

1. Install Backdrop.
2. Open the developer tools in Chrome.
3. Navigate to admin/structure/layouts and configure the blocks of the default layout.
4. Note the error in the JS console.
5. View the messages in admin/reports/dblog and see the 404 errors for jquery.form.min.js.map

## Actual behavior
![image](https://github.com/backdrop/backdrop-issues/assets/20357797/20ab66eb-a27a-44d8-8386-59e04aa40373)

## Expected behavior
No errors

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.26.1

<hr>
PR - backdrop/backdrop/pull/4548

**Comment by yorkshire-pudding** [comment]
PR added. Note that this is exactly the same change that @quicksketch did for #3090

**Comment by indigoxela** [comment]
Reproduced locally, compared in sandbox, looked at the trivial code comment change. RTBC!

@yorkshire-pudding many thanks for digging out the initial solution and providing the PR. :+1:

**Comment by quicksketch** [comment]
Thanks folks! I merged https://github.com/backdrop/backdrop/pull/4548 into 1.x and 1.26.x.
