### ISSUE TITLE
Typo in variable name in docblocks in system.api.php file

### ISSUE THREAD

**Issue by findlabnet** [backdrop/backdrop-issues#6273]
## Description of the bug

In docblocks in `system.api.php` file we have a typo: instead of 'page_cache_invoke_hook' it should be 'page_cache_invoke_hooks' on lines 272 and 1351 to avoid documentation bugs according to backdrop-ops/docs.backdropcms.org#229.

## Additional information
- Backdrop CMS version: 1.26.1

**Comment by bugfolder** [comment]
PR created. I'm only marking "needs review"—since it's a docblock change, there's nothing to test.

**Comment by quicksketch** [comment]
Thanks @bugfolder! I merged https://github.com/backdrop/backdrop/pull/4934 into 1.x and 1.29.x. Thank you for the report @findlabnet!
