### ISSUE TITLE
[CMI] Cannot create content type with fields in a full site import

### ISSUE THREAD

**Issue by sirkitree** [backdrop/backdrop-issues#628]
When trying to import configuration from a local site to another, I'm receiving the following error message:
```
Configuration sync failed. The following errors were reported:
The configuration "field.bundle.node.fireboxroom" must have the "entity_type" attribute specified.
```

`fireboxroom` is a new content type I created. Do I need to first create this content type on the other installation in order to import configuration for it? Or is there something else I'm missing?

**Comment by sirkitree** [comment]
Hrm, nope. I created the content type on the remote installation and still get this error. If there are docs on this please let me know, in the meantime I'll look around.

**Comment by quicksketch** [comment]
> fireboxroom is a new content type I created

Is this a content type created through the UI? Or created programmatically? 

You should be able to copy content types between sites, however you'll need to do a full site export/import to move a content type, because content types have a bunch of peripheral config files that need to be copied all at once (fields, field instances, the node type itself, etc). We have an issue for making it possible to export/import *just* a content type at https://github.com/backdrop/backdrop-issues/issues/408.

**Comment by sirkitree** [comment]
This was created through the UI and I was attempting to do a full export and then import.

**Comment by quicksketch** [comment]
Ah, I got it now.

- Create new content type.
- Add a *new* field to that content type.
- Export your full site config.
- Delete the content type you just created.
- Import the full site config to staging.
- Try to import the config to active.

Error:
> The configuration "field.bundle.node.new_type" must have the "entity_type" attribute specified.

Thanks @sirkitree this seems like it's going to severely limit the usefulness of CMI if you can't create node types with fields! I'll try to see what's going on in here.

**Comment by sirkitree** [comment]
Thanks, I'll try to outline my steps better in the future.

**Comment by quicksketch** [comment]
Looks like just saving the "Display fields" page on an existing content type triggers it too. I've got the root cause worked out, I'll PR soon. :smile:

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/711 should solve this. Could you try it out? This requires an update.php run, and you'll have to make new exports of your config, since the current ones are missing necessary information (just like the error message reports).
