### ISSUE TITLE
PHP 8.2 Deprecated function: Creation of dynamic property Redirect::$status is deprecated in Redirect->__construct() (line 120 of /core/modules/redirect/redirect.class.inc).

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#6281]
## Description of the bug

Maybe got missed in #5927 or maybe is an edge case.

Got this notice on node edit form

> Deprecated function: Creation of dynamic property Redirect::$status is deprecated in Redirect->__construct() (line 120 of /app/docroot/core/modules/redirect/redirect.class.inc).

## Steps To Reproduce

To reproduce the behavior:
1. Not sure of exact steps to debug as it appeared on node edit of one node with 1 redirect but didn't appear on another node edit with 5 redirects.

## Actual behavior

Deprecation notice at top of node edit form

![image](https://github.com/backdrop/backdrop-issues/assets/20357797/72bc69d0-8378-4f37-9434-08a1e9638a72)

## Expected behavior

No deprecation notice

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.26.1
- PHP version: 8.2.5

**Comment by yorkshire-pudding** [comment]
@indigoxela - yes that particular site was upgraded from D7. That might explain why it was seen on one entity type and not another.

**Comment by indigoxela** [comment]
Can you inspect the database structure of the "redirect" table? Does it still have a "status" column?

It might be, that the upgrade process is incomplete re schema change - not sure, yet.

If you have PHPMyAdmin available, use that, or if you have mysql/mariadb shell access, you can run `describe YOURDBNAME.redirect;`.

**Comment by yorkshire-pudding** [comment]
My first use `bee dbq`

```
rid,int(11),NO,PRI,,auto_increment
hash,varchar(64),NO,UNI,,
type,varchar(64),NO,MUL,,
uid,"int(10) unsigned",NO,,0,
source,varchar(255),NO,MUL,,
source_options,blob,YES,,,
redirect,varchar(255),NO,MUL,,
redirect_options,blob,YES,,,
langcode,varchar(12),NO,,und,
status_code,smallint(6),NO,,,
count,"int(10) unsigned",NO,,0,
access,"int(10) unsigned",NO,,0,
status,smallint(6),NO,MUL,1,
```

**Comment by indigoxela** [comment]
Oops, yes, the "status" column's still there. We'll have to take care of that in an update hook.

How about the values? In D7 redirects could have been disabled (in theory), which means, after upgrading a disabled redirect got enabled. Too late to fix that, I guess.

Another thing to check, in case you have the devel module installed or easy access to run custom code:

- Find an entry (rid) with a status set (in db)
- Run php code: `$r = redirect_load(X); debug($r);` with X set to the rid

Does that trigger the PHP warning?

**Comment by yorkshire-pudding** [comment]
Yes. That does trigger the warning.
Thanks @indigoxela for helping to pinpoint the cause of this

**Comment by indigoxela** [comment]
Hm, maybe it's not too late to remove disabled redirects... The default value for the column is "1", so we could filter out previously disable one ("0").

And then `db_drop_field('redirect', 'status')` ... but wait, in D7 there was also an index status_source_language.
@yorkshire-pudding what does `show index from YOURDB.redirect;` output?

**Comment by yorkshire-pudding** [comment]
```
redirect,0,PRIMARY,1,rid,A,810,,,,BTREE,,
redirect,0,hash,1,hash,A,810,,,,BTREE,,
redirect,1,expires,1,type,A,2,,,,BTREE,,
redirect,1,expires,2,access,A,810,,,,BTREE,,
redirect,1,status_source_language,1,status,A,4,,,,BTREE,,
redirect,1,status_source_language,2,source,A,810,,,,BTREE,,
redirect,1,status_source_language,3,langcode,A,810,,,,BTREE,,
redirect,1,redirect,1,redirect,A,810,,,,BTREE,,
redirect,1,source_langcode,1,source,A,810,,,,BTREE,,
redirect,1,source_langcode,2,langcode,A,810,,,,BTREE,,
```

**Comment by indigoxela** [comment]
Oh, it's still there, although the "language" column has been renamed to "langcode". That one also has to go. :neutral_face:  

We need to:

- Check if a status col exists
- Delete all entries, where the status = 0
- Drop the index status_source_language if it exists
- Drop the status column

**Comment by argiepiano** [comment]
Good catches, both of you! Before 8.2 these additional "zombie" columns were unnoticeable and harmless. I guess it's time to take care of those now!

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop/backdrop/pull/4556) is available for testing and review.

A word of warning: be careful when testing, as on a clean install (no upgrade) I couldn't actually test it locally.

**Comment by yorkshire-pudding** [comment]
Tested and can confirm this fixes it

**Comment by argiepiano** [comment]
I find this approach slightly problematic. Imagine I upgraded from D7 a few months ago, and I use PHP 7.4. I notice that the redirect that was disabled in D7 is now enabled in Backdrop, but I'm cool with that. I let it be, and the redirect now works for me. But then this update hook runs, and deletes functional, acceptable redirects, only because the column still exists.

I know this is a fringe case, but it can happen. I'm not sure what the ideal solution may be, though.

**Comment by laryn** [comment]
Good find -- and may be the cause of this issue:

 - https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/URL.20alias.20and.20URL.20redirect.20issue

In short, these redirects that were disabled on D7 are now essentially enabled in Backdrop and can cause conflicts (e.g. if there's an alias with the same path it can be an infinite loop).

**Comment by bugfolder** [comment]
> In short, these redirects that were disabled on D7 are now essentially enabled in Backdrop and can cause conflicts (e.g. if there's an alias with the same path it can be an infinite loop).

Wow, that explains an extremely puzzling thing that was plaguing my post-upgrade site for several months post-upgrade; occasionally a user would report a problem that turned out to be an infinite-redirect loop. I was unable to create an infinite loop via the UI (the UI prevented it, correctly), so had no idea how the sporadic ones were coming about. Probably this way.

**Comment by indigoxela** [comment]
@laryn hey, that seems like a smart solution... moving the db_delete of disabled items (and only that) to one of the **previous** update hooks.

I do feel a bit uncomfortable to do that cleanup in the latest update, actually. For exactly the reasons commented here. On the other hand, I'm not sure if that's something we ever do: fiddling with update hooks, that already ran. Do we?

**Comment by kiamlaluno** [comment]
Usually, to fix a wrong update hook, a new update hook is implemented. Changing an update hook that most sites already ran would not have any effect on those sites.

**Comment by indigoxela** [comment]
> Changing an update hook that most sites already ran would not have any effect on those sites.

@kiamlaluno that's exactly, what we're after. :wink: But only for the db_delete part.

**Comment by laryn** [comment]
> I'm not sure if that's something we ever do: fiddling with update hooks, that already ran. Do we?

I'm also not sure about protocols here, to be honest!

**Comment by argiepiano** [comment]
While unusual, I think the idea of modifying an existing update hook (specifically, update_1000 in this case) is very smart - that way only new D7 upgrades will run de delete code.

**Comment by indigoxela** [comment]
Maybe, before we decide for a procedure, we should decide, whether we want to delete existing redirects with "status = 0" on _all_ sites, or only for _fresh_ upgrades.

We have to decide, because after we dropped the "status" column, there's no way to figure out, whether those items have been disabled in D7 or not. Last chance.

At first I felt uncomfortable with deleting them even for sites, that upgraded some time ago. But on the other hand, there may be situations, where this cleanup fixes potential problems with loops (not sure, does it?).

**Comment by laryn** [comment]
@indigoxela  I think it's safer not to delete the `status = 0` columns on sites that have upgraded some time ago, because of the case where someone could have edited a redirect with `status = 0` after the upgrade (or indeed, decided they wanted that redirect to remain, and manually deleted others).

To cleanup the potential loop problems, we can do something like this, perhaps, to catch and cleanup infinite loops (which should be prevented via the UI but can exist due to glitches like this one)?

```
delete r
from redirect r
join url_alias ua on ua.source = r.redirect
where r.source = ua.alias;
```

**Comment by indigoxela** [comment]
Time to set the "review" label back. :grin:

Should we do that check for potential loops as part of this issue/PR? Would that catch all of them?

**Comment by argiepiano** [comment]
> I think it's safer not to delete the status = 0 columns on sites that have upgraded some time ago, because of the case where someone could have edited a redirect with status = 0

Agreed, but then we need to fix the deprecation notice that happens because of the existence of the `status`. We could declare the property `$status` in `Redirect` and add a note about backward compatibility?

**Comment by indigoxela** [comment]
>  but then we need to fix the deprecation notice that happens because of the existence of the status

@argiepiano  Sure, fixing that still happens. ... If I got directions here in this discussion right.

Only the `db_delete('redirect')->condition('status', 0)->execute();` gets moved to - presumably -  redirect_update_1001().

In redirect_update_1004() we still drop the faulty index and table column, so after that:

- The table schema corresponds to vanilla installs
- The deprecation notice is gone, as there's no more Redirect::status

We don't need that status property, we only have to clean up the cruft after upgrades.

**Comment by laryn** [comment]
> Should we do that check for potential loops as part of this issue/PR? Would that catch all of them?

It would make sense to me to include something like that in `redirect_update_1004()` but if others disagree we could move it to a separate issue.

**Comment by kiamlaluno** [comment]
Moving `db_delete('redirect')->condition('status', 0)->execute()` from an update hook to a new one should not cause warns.

**Comment by indigoxela** [comment]
I've moved the db_delete to redirect_update_1001(), so deletion only runs for fresh upgrades.

I'd need some help with the query in redirect_update_1004() to filter out redirection loops, though. What exactly do I have to check for?

@laryn or @bugfolder what are your suggestions?

**Comment by laryn** [comment]
@indigoxela The loop doesn't exist in the same way in D because the redirect is disabled (a functionality that doesn't exist in B but is not accounted for yet during the upgrade), so the alias works as expected in D. Once upgraded to B the redirect is no longer disabled, and the redirect and alias form a loop.

**Comment by klonos** [comment]
Sorry for arriving late to the party. Throwing this out there: would things perhaps be simpler if we supported disabled redirects? That would leave disabled redirects coming from D7 upgrades there for people to decide what to do with them.

There is the case where already upgraded sites might have redirects with their status set to `0` in the db, which people might have edited and would like to keep in B. But if we did support a disabled state for redirects, then how would we know if people mean to have these disabled (the "legacy" `0` they have inherited in their db from D7) or not? 🤔

**Comment by klonos** [comment]
...I guess the answer to my above questions lies in itself: we could leave existing sites alone by setting all the statuses of the redirects in the db to `1`, and only keep the `0`s coming from new D7 upgrades. Thoughts?

**Comment by indigoxela** [comment]
> ... would things perhaps be simpler if we supported disabled redirects? Thoughts?

No, that wouldn't solve the problem. Changing the whole concept in B only creates complications. :wink:
The concept of "sleeping" redirects is odd and there's no need for that.

**Comment by bugfolder** [comment]
Well, it is completely possible to set up infinite redirect loops of arbitrary length using disabled redirects in D7 that, after upgrade to B, look like this:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/feb1764d-c44e-41e3-8082-af809907e8bf)

Resulting in this:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/97737e22-1e0e-420a-b014-e8067488d951)

Now, I'm not sure how likely it is that someone would intentionally create such a loop, but with automatic creation of redirects when aliases change, and using node titles as URL aliases, I can see how someone might tweak a node title several times to create several similar redirects to arrive at something like this.

But my point is that we can't possibly be successful with a strategy of just trying to detect and correct infinite loops.

Possibly crazy notion: is there a way to get a timestamp on something that is modified at the beginning of a B upgrade and then never or only rarely touched again? Then, in our upgrade hook, if that thing was touched in the last few minutes, we're doing an upgrade from D7 and can safely delete all disabled redirects, whereas if that thing is older, then we can assume the site is used to the current state and should keep them.

**Comment by bugfolder** [comment]
@indigoxela, thanks for the explanation. I think retro-modifying the earlier update hook fully accommodates what I was pondering in my timestamp suggestion, so you can ignore that.

I made a suggestion for the docblock comment.

Otherwise, I think this meets the need as is.

**Comment by indigoxela** [comment]
> I made a suggestion for the docblock comment.

@bugfolder Great, many thanks for your suggestion, comment added. :+1:

**Comment by bugfolder** [comment]
Code reviewed, LGTM.

I also did a re-test. On a Drupal site, I set up two redirects: 

* `enabled-redirect` --> `node/1` (enabled)
* `disabled-redirect` --> `node/1` (disabled)

I then did a standard Backdrop upgrade (not including this version), which resulted in both redirects being enabled (as expected).
Applied this PR, ran the update, and they are still enabled (as expected), but the `redirect` table no longer has the `status` column (also as expected).

Then re-setup the Drupal site with the two redirects and ran the upgrade from this PR's code. Result was that the enabled redirect persisted, the disabled redirect was gone (as desired).

So, WFM also! RTBC.

**Comment by quicksketch** [comment]
Thanks for the in-depth discussion about new vs updated existing update hooks. I really like where this ended and the explanation makes sense for me too as to why we shouldn't be deleting the existing redirects on existing sites.

I merged https://github.com/backdrop/backdrop/pull/4556 into 1.x and 1.26.x. Thanks everyone!
