### ISSUE TITLE
PHP 8.3 compatibility

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6284]
People started asking whether Backdrop will run without problem on PHP 8.3. Lets work on that.

For reference, here's the respective D7 core issue: https://www.drupal.org/project/drupal/issues/3380823

**Comment by klonos** [comment]
Not sure if we are doing any validation on our config files on load/save, but this might be worth taking advantage if in php 8.3: https://php.watch/versions/8.3/json_validate

**Comment by indigoxela** [comment]
@klonos many thanks for opening this issue.

We're in good shape, it seems, but there are several unrelated test failures in the older PHP versions (restarting the tests should fix those).

However, one failing test is caused by the test-suite itself. Here's the [corresponding D7 issue](https://www.drupal.org/project/drupal/issues/3380876) with a one-liner fix.

**Comment by indigoxela** [comment]
And for Tugboat, it's still too early to switch, it seems. Can you revert that one to 8.2 for now?

**Comment by klonos** [comment]
>And for Tugboat, it's still too early to switch, it seems. Can you revert that one to 8.2 for now?

I've switched to using `8.2-rc-apache` instead of stable `8.2-apache`, and we have working Tugboat sandboxes now!

I've also added an inline comment in the `.tugboat/config.yml` file to point to https://github.com/TugboatQA/dockerfiles/blob/main/php/TAGS.md, which should make it easier for us to be selecting available `tugboatqa/php` versions in the future 😉 

> However, one failing test is caused by the test-suite itself. Here's the [corresponding D7 issue](https://www.drupal.org/project/drupal/issues/3380876) with a one-liner fix.

Thanks. I've added that one-liner to the PR 👍🏼 ...now only `BareUpgradePathTestCase` and `LayoutUpgradePathTest` fail, both with `Call to undefined function layout_load_multiple_by_path()` (which is plaguing many other PRs and we are trying to hunt down in #6293).

**Comment by indigoxela** [comment]
@klonos wow, very cool, you managed to get Tugboat running with PHP 8.3. :tada:

I clicked around in the sandbox - everything seems to work as expected with 8.3. And, yes, the failing tests really seem unrelated.

**Comment by klonos** [comment]
Yeah, the respective meta for D7 only has this child-issue outstanding: [[D7 PHP 8.3] TextSummaryTestCase::testLength() fails on some libxml versions](https://www.drupal.org/project/drupal/issues/3397882), which is an upstream issue that won't be fixed (the libxml maintainers say that the change was intentional). In D10, they switched to using https://github.com/Masterminds/html5-php instead of relying on `DOMdocument`, which seems like a rather big change 🤔 (see https://www.drupal.org/project/drupal/issues/1333730 and relevant [change record](https://www.drupal.org/node/2407077))

The version of libxml in the PR sandbox is 2.9.14, but we are not getting the same failures in our tests like D7 does 🤷🏼

**Comment by klonos** [comment]
> The version of libxml in the PR sandbox is 2.9.14...

...however our tests ar configured to run on Ubuntu 20.04, which by default uses 2.9.10. See https://launchpad.net/ubuntu/focal/+source/libxml2

**Comment by indigoxela** [comment]
@klonos many thanks for digging that out. However, on my Debian dev box I have libxml 2.9.14 and I didn't experience any problems with that, yet. The two tests in that Drupal issue you linked, are related to pgsql and sqlite - not something Backdrop core even supports.

If there aren't any other tests failing with libxml 2.9.14, we could easily ignore that.

And yes, the Tugboat container setup is sometimes a bit ... special, for example an ancient kernel combined with new libs. :shrug:

**Comment by klonos** [comment]
> ... The two tests in that Drupal issue you linked, are related to pgsql and sqlite - not something Backdrop core even supports. ... If there aren't any other tests failing with libxml 2.9.14, we could easily ignore that.

Yup, just saw that too 👍🏼 ...it might turn out to be a problem only if someone is using Silkscreen, or if #2277 lands and someone does use those databases.

**Comment by indigoxela** [comment]
Ha, wait, spoken too soon. I just ran TextSummaryTestCase in my dev (libxml 2.9.14) and I do indeed see failures:

```
FAIL: Generated summary "&lt;" matches expected "".
FAIL: Generated filtered_html summary "&lt;" matches expected "".
FAIL: Generated summary "<p>\nHi\n&lt;</p>" matches expected "<p>\nHi\n</p>".
```
So we have to consider that.

**Comment by indigoxela** [comment]
This demonstrates the problem:

```
$text = '<p>456789</p>';
$result = text_summary($text, NULL, 10);
debug($result);
```
The result is `'<p>456789&lt;</p>'`.

If markup is cut off directly after an opening '<', it's converted to `&lt;`.

Unfortunately I can't compare the result with older xmllib versions. I don't have any older available anywhere. Even our Tugboat sandbox ships with 2.9.14.

**Comment by indigoxela** [comment]
The solution for these failing tests is actually pretty easy, but an extra issue for libxml might eventually make more sense (not sure).

My proposed fix would go to function text_summary():
```
$summary = rtrim($summary, '<');
```
I'd put that right before the _filter_htmlcorrector() in that function.

This would not only fix the test, but also prevents those `&lt;` from showing up in trimmed content. It's compatible with old and new libxml versions and a very lightweight change.

**Comment by indigoxela** [comment]
Here for completeness, why libxml matters for us:

Currently we're using the Ubuntu 20.04.6 LTS image for our GitHub Action runners (for functional tests). That's why tests don't fail, yet. That may change any time, if we switch the runner version to something newer.

Many people will already have a newer libxml version on their dev environments. That leads to test failure of a few tests locally, that don't fail in PR checks. Confusing and inconsistent.

And as mentioned, the tests rightly fail, as a stray `&lt;` does show up in trimmed content (ugly!). I'm assuming, many hosting providers already ship a newer libxml version by now, or will do so soon.

**Comment by klonos** [comment]
I've switched the runners to be using ubuntu-22.04 in the PR. According to https://launchpad.net/ubuntu/jammy/+source/libxml2 the version of libxml that ships with 22.04 is 2.9.13.

**Comment by indigoxela** [comment]
> the version of libxml that ships with 22.04 is 2.9.13

Wow, Ubuntu's really conservative re versions... :wink:

**Comment by klonos** [comment]
> You probably also have to switch to a different (newer) MariaDB.

Might as well 👍🏼

**Comment by klonos** [comment]
...switched mariadb from 10.3 to 10.6, since it seems to be the default for ubuntu 22.04 per https://packages.ubuntu.com/search?keywords=mariadb-server

**Comment by indigoxela** [comment]
Nope, not yet, there's more with this runner version, for example:
```
sed: can't read ls: No such file or directory
```
... in PHP setup. So very likely there's a different structure in /etc/php and the setup of php-fpm currently (partly) fails.

I don't have the time to dig into that currently. @klonos so, unless you'd like to dig into the details now, I'd suggest to switch back to Ubuntu 20.04.

Fiddling out, what needs to get changed requires a lot of trial-and-error with lots of GHA runs - time consuming.

**Comment by klonos** [comment]
> ... unless you'd like to dig into the details now, I'd suggest to switch back to Ubuntu 20.04.

Yeah, no time for that right now, so I've reverted to previous versions of ubuntu and mariadb.

**Comment by klonos** [comment]
In the meantime, I've also found these:
- https://www.drupal.org/project/drupalci_environments/issues/3282786
- https://www.drupal.org/project/drupal/issues/3298822
- https://www.drupal.org/project/drupal/issues/1394394
- https://www.drupal.org/project/drupal/issues/3204929
- https://www.drupal.org/project/drupal/issues/2441811

**Comment by quicksketch** [comment]
Nice to see that PHP 8.3 is relatively easy to upgrade to. The current PR is trivial and all tests are passing. Is there more work to be done in this specific issue?

**Comment by indigoxela** [comment]
> The current PR is trivial and all tests are passing. Is there more work to be done in this specific issue?

I think, the problem with libxml and the possible solution to rtrim deserves its own issue and should be discussed in a follow-up.

So, if @klonos agrees, this PR seems to be ready to merge.

Probably the additional D11 issues added in [this comment](https://github.com/backdrop/backdrop-issues/issues/6284#issuecomment-1827665057) need individual validation, too. @klonos what do you think?

**Comment by klonos** [comment]
I'm fine with following up for libxml in #6327 👍🏼 

I've rebased the PR and switched to using the stable `8.3-apache` image for tugboat instead of the RC (the PR was originally created before the official release of PHP 8.3, so the tugboat image was not available at the time).

**Comment by quicksketch** [comment]
Great, I merged https://github.com/backdrop/backdrop/pull/4558 into 1.x and 1.26.x. Thanks @klonos and @indigoxela!
