### ISSUE TITLE
Multivalue Text (long) fields do not attach editors (CKEditor) when reordered

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6287]
## Description of the bug

Currently, with multivalue fields (field cardinality > 1), the editor content gets saved properly, when new fields get added. 👍

But reordering these multivalue field (via drag/drop) also detaches the editor. We might want to re-attach it (Backdrop.editors.ckeditor5.attach()), if the "trigger" is "move".

Originally reported in https://github.com/backdrop-contrib/ckeditor5/issues/90 by @indigoxela.

## Steps To Reproduce

To reproduce the behavior:
1. Create a multivalue Text (long) field with Filtered Text on a content type
2. Create a new node of that type
3. Rearrange the multivalue text field items with table drag.
4. The moved field loses its editor.

## Actual behavior

The moved field loses its editor (the second one in this screenshot):

![image](https://github.com/backdrop/backdrop-issues/assets/100206/989221f5-d804-4591-aad9-4816e1649946)

## Expected behavior

The editor should stay in place with the current field value unmodified.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4562. This would be nice to get into the next bugfix release.

**Comment by indigoxela** [comment]
This works for me. I tested in the sandbox with CKE4.

- A multi-value field, text, with filtered content
- Added content
- Reordered fields
- Yes, the editor now stays in place :+1:

I have to admit, I don't fully understand, why using jquery.once fixes this, but it works. :+1:

**Comment by quicksketch** [comment]
> I don't fully understand, why using jquery.once fixes this

It's a bit confusing; I'll see if I can explain.

After reordering table rows, the contents of the moved table row have their behaviors re-attached: first detached and then attached again. But the problem we have is that `.once()` was already applied to the contents of the table row. So the editor gets detached, but the once class "once-filterEditors" was not removed. So when the editor was supposed to get reattached, it sees that the "once-filterEditors" was still present, so it does not reattach. The PR removes the once class on detach, so when attach fires again, it's not blocked by the `.once()` check.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4562 into 1.x and 1.26.x. Thanks @indigoxela (as well as @kiamlaluno and @laryn) for reviewing!
