### ISSUE TITLE
In user_register_form(), use the value of $admin instead of calling again user_access('administer users')

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6288]
The first two lines of [`user_register_form()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21user%21user.module/function/user_register_form/1) are the following ones.

```php
  global $user;
  $admin = user_access('administer users');
```

Later, that function uses the following code.

```php
  elseif (user_access('administer users')) {
    $path = 'admin/people';
  }
```

Instead of calling again `user_access('administer users')`, the code should check the value of `$admin`.

```php
  elseif ($admin) {
    $path = 'admin/people';
  }
```

That is exactly what the code some lines before that does.

```php
  if ($admin) {
    // Redirect back to page which initiated the create request;
    // usually admin/people/create.
    $form_state['redirect'] = $_GET['q'];
  }
```

**Comment by kiamlaluno** [comment]
I also fixed a comment in the *user.module* file, which was exceeding 80 characters.
I added new labels, since the tests were passing, before the last commit I have done.

**Comment by kiamlaluno** [comment]
It seems the now failing tests are not related with the changes done in the PR for this issue, starting from *require_once(/home/runner/work/backdrop/backdrop/modules/user/user.pages.inc): failed to open stream: No such file or directory*.

**Comment by bugfolder** [comment]
Tested. WFM. Code reviewed. LGTM.

RTBC.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno, @bugfolder, and @klonos! I merged https://github.com/backdrop/backdrop/pull/4563 into 1.x and 1.26.x.
