### ISSUE TITLE
Upgrade not possible

### ISSUE THREAD

**Issue by alexhass** [backdrop/backdrop-issues#629]
I replaced all files as we do in Drupal and after this the site required a install.php when I ran update.php. Looks like the upgrade has never tested. Now dropped database and started from 0 again. suxxx

**Comment by quicksketch** [comment]
Hi @yamlfd, are you talking about an upgrade from Drupal 7 or from 1.0.0 to 1.0.1?

We have the Drupal 7 upgrade in automated testing, and I ran it a few times before 1.0.0, so I know that's in shape. I upgraded 3-4 sites from 1.0.0 to 1.0.1 already as well. It sounds like you may have overwritten the `settings.php` during the upgrade, which would make it so Backdrop wouldn't know the database or config directories, so it would assume it needed to be installed.

When doing an upgrade of Backdrop, the *only* directory you need to replace is the `core` directory, which differs from Drupal 7. The full instructions are at https://backdropcms.org/upgrade#minor-updates.

**Comment by yamlfd** [comment]
from 1.0.0 to 1.0.1

Yes, i have overwritten settings file. Please name the file setting.default.php in install like drupal does. So this never happens again.

**Comment by quicksketch** [comment]
> Please name the file setting.default.php in install like drupal does. So this never happens again.

We specifically changed it to settings.php to simplify the installation process for new users. It's one less step that needs to be done on every install. In the future, you'll upgrade just by replacing the "core" directory. I think in this case, it's pre-existing Drupal behavior that caused the problem. Simplifying the installation is a worthwhile cause and is more valuable to us than maintaining this particular expectation of existing Drupal users.

**Comment by chrisherberte** [comment]
May I suggest a link to upgrade page directly below the download link on backdropcms.org/

**Comment by quicksketch** [comment]
> May I suggest a link to upgrade page directly below the download link on backdropcms.org/

Would linking to the release notes page instead of the .zip file do the job you think? https://github.com/backdrop/backdrop/releases/tag/v1.0.1

**Comment by chrisherberte** [comment]
Also related, why is the download for 1.0.1 .zip 1.0.0 was tgz IIRC
tgz nicer :)

**Comment by chrisherberte** [comment]
Link to release notes absolutely.

**Comment by quicksketch** [comment]
I chatted with @jenlampton and this and she's not keen on piping users who want to download Backdrop for the first time through the Github release notes, since they're not relevant to new users.

So for now we've updated the homepage based on your other recommendation, putting a link to upgrading instructions below the download button.

**Comment by chrisherberte** [comment]
Do you think it makes sense to add a link for the release notes there too? Or to https://github.com/backdrop/backdrop/releases so you don't have to keep updating the link.

**Comment by quicksketch** [comment]
We want users to be able to download it as quickly as possible, and neither the release notes for the current version or information about past releases is very relevant if you've never installed the product the first time.

We can add a link to all releases somewhere, there are probably a lot of places that would make sense, e.g. the Roadmap and Release Cycle pages. But for the homepage, our goal is to get new users trying out Backdrop for the first time.

**Comment by quicksketch** [comment]
I added links to the list of all releases on the following pages:

https://backdropcms.org/installation
https://backdropcms.org/releases
https://backdropcms.org/roadmap

**Comment by yamlfd** [comment]
There are files in root that may need to be updates for security reasons. E.g htaccess.

This is not because of Drupal. This is unexpected all times and only overcomplicates the upgade process. I say bad design if my settings are all lost that easy.

**Comment by quicksketch** [comment]
The upgrade process for core is documented and is different than Drupal. If it becomes necessary to modify .htaccess or another root file, we'll make a note of it in updates notes and security announcements, with code-based checking to back it up, like Drupal has done in the past for the .htaccess in the files directory. We'd need to do that anyway if we had to modify a file that was likely to have user-adjustments.

> This is unexpected all times and only overcomplicates the upgade process. 

I don't think this makes upgrading more complicated. If anything it's *less* complicated. Replace the core directory, that's it.

Drupal's update instructions:

> Remove all old core files and directories, except for the 'sites' directory and any custom files you added elsewhere.
> If you made modifications to files like .htaccess or robots.txt, you will need to re-apply them from your backup, after the new files are in place.

Backdrop's update instructions:

> Delete the "core" directory from the root directory of your current codebase and replace with the "core" directory from the latest release of Backdrop CMS.

**Comment by yamlfd** [comment]
I don't think that this is really a good idea. I lost the full dev site. Thanks. Others will face with the same problem. I better stay at D8.

**Comment by quicksketch** [comment]
We're not planning on changing it at this point. The reason has been explained comprehensively in this thread.
