### ISSUE TITLE
Update CKEditor 4 to last available version

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6292]
## Description of the task

Currently core ships with 4.18.0, but actually the latest _and_ last available version is 4.22.1.

Assuming, that this version contains bugfixes, we might want to update to it. Regardless of the fact, that CKE4 (Open Source) is out of maintenance.

**Comment by indigoxela** [comment]
Ah, I see...

At first I thought, that the online builder (getting the same package via `build-config.js`) is broken, but there's another problem: the image2 plugin we're using isn't available anymore. Instead the image plugin has been split into several plugins (comparable to v5).

Probably incompatible for our setup and not worth the effort. :shrug: 

Or are there other ideas?

**Comment by quicksketch** [comment]
PR looks great. I read over the changelog and I didn't notice anything that would affect Backdrop substantially. There were some changes to the copy/paste support of images, but in testing it seems the same as before by default at least.

Changes that _might_ be relevant to us:

- [#5510](https://github.com/ckeditor/ckeditor4/issues/5510): Added notification system to the editor informing users that the editor version is up-to-date and secure. See [`config.versionCheck`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-versionCheck) configuration option to learn more. _Maybe we should turn this value off? Core maintains the process of updating, not end-users._
- [#4400](https://github.com/ckeditor/ckeditor4/issues/4400): Added the [`config.uploadImage_supportedTypes`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-uploadImage_supportedTypes) configuration option allowing to change the image formats accepted by the [Upload Image](https://ckeditor.com/cke4/addon/uploadimage) plugin.

**Comment by indigoxela** [comment]
@quicksketch many thanks for having a look. :pray:

The versionCheck is easy, but I'm currently not sure re "uploadImage_supportedTypes" - is this additionally to the image widget "supportedTypes" setting, or does the new config option replace it?

Currently the PR sets both.

**Comment by indigoxela** [comment]
I took a closer look now. The odd base64 encoding isn't new behavior, but a Filter module quirk, also present with our current editor version:
When removing the image toolbar button on existing filter settings, the upload section "vanishes" (per state), but the original image upload setting (including status = 1) stay unchanged. This leads to the odd situation, that image uploads would still be on, but there's no plugin to handle that. If the steps are "remove editor, save, open again add editor, remove image toolbar item", things work. Unrelated here.

Now to the config.**uploadImage_supportedTypes** item:
That's not relevant for us, as the setting's for the [Upload Image](https://ckeditor.com/cke4/addon/uploadimage) plugin, which isn't part of our editor build.
We're using image2 with a custom backdropimage uploadWidget, that uses the supportedTypes setting.

However, that's a good opportunity to switch from hardcoded image type regex to a config param, that receives the same image types as the server-side check will allow. Based on image_get_supported_extensions().

Of course, we could also stick with the hardcoded setting, but if it's dynamic, we also get webp images working on paste (if supported by the image toolkit).

**Comment by quicksketch** [comment]
I went ahead and merged https://github.com/backdrop/backdrop/pull/4565 into 1.x and 1.26.x. The only open requests were for a few code comments, which didn't seem like we needed to hold this up from being in 1.26.2.
