### ISSUE TITLE
Warning: Undefined property: Node::$original in file_field_update() (line 267 of ../docroot/core/modules/file/file.field.inc)

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6294]
## Description of the bug

The line https://github.com/backdrop/backdrop/blob/51c2227d9ba9cb94887378fd1266870a178bcbe7/core/modules/file/file.field.inc#L267 of function file_field_update() explicitly expects `$entity->original`, but it is not always set.

## Steps To Reproduce

To reproduce the behavior:

1. Implement a simple insert hook:
```php
function task_node_insert(Node $node) {
  if ($node->type == 'task') {
    $node->field_reference_field[LANGUAGE_NONE][]['target_id'] = 'some value;
    field_attach_update('node', $node);
  }
}
```
2. Create a node of the type and you will see the error:

```php
Warning: Undefined property: Node::$original in file_field_update() (line 267 of /var/www/html/docroot/core/modules/file/file.field.inc). 
```

## Additional information

Note that using [field_attach_insert($entity_type, $entity)](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.attach.inc/function/field_attach_insert/1) instead will give:

```php
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'node-558-0-0-und' for key 'PRIMARY' 
```

because as the function's description says:

> The passed-in entity must already contain its id and (if applicable) revision id attributes. Default values (if any) will be saved for fields not present in the $entity.

On the other hand the `field_attach_update()` makes insertion of a new task node with a populated field possible using the give above hook, but give the reported error, because of the following lines:

```php
  // Compare the original field values with the ones that are being saved.
  $original = $entity->original;
  $original_fids = array();
  if (!empty($original->{$field['field_name']}[$langcode])) {
    foreach ($original->{$field['field_name']}[$langcode] as $original_item) {
      $original_fids[] = $original_item['fid'];
      if (isset($original_item['fid']) && !in_array($original_item['fid'], $current_fids)) {
        // Decrement the file usage count by 1.
        if ($file = file_load($original_item['fid'])) {
          file_usage_delete($file, 'file', $entity_type, $id);
        }
      }
    }
  }
```

Now, we are bypassing this error by adding the following line into the hook:
    
```php
$node->original = isset($node->original) ? $node->original : NULL;
```

however, I thought to report this issue, so the community finds the best solution for the cases when developers need to insert a new node populating a field at the same time.

**Comment by alanmels** [comment]
Closing this issue as implementing the` hook_node_presave()` in combination with `field_attach_presave()` allows creating new nodes with populated fields without giving any errors. Which may not be necessarily obvious to all developers, so could be documented on https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.api.php/function/hook_node_presave/1.

**Comment by argiepiano** [comment]
You don't even need `field_attach_presave()`. Just assign the value to the field in `hook_node_presave()` and let Backdrop simply save the field value when it saves the node.

**Comment by alanmels** [comment]
> You don't even need `field_attach_presave()`. Just assign the value to the field in `hook_node_presave()` and let Backdrop simply save the field value when it saves the node.

I know, but I didn’t tell the whole story about our use case - we need to stick with filed attach.

**Comment by kiamlaluno** [comment]
Actually, the error is in the shown code: When an entity is created, [`field_attach_insert()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.attach.inc/function/field_attach_insert/1) must be called, not [`field_attach_update()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.attach.inc/function/field_attach_update/1), which for when an entity is updated.

**Comment by kiamlaluno** [comment]
When an entity is created (inserted), `$entity->original` (or `$node->original`) is not set, as there is no existing entity.
