### ISSUE TITLE
Impossible to set Relative date on Views

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6295]
## Description of the bug

After filing these two issues:

https://github.com/backdrop/backdrop-issues/issues/6228
https://github.com/backdrop/backdrop-issues/issues/6286

and hitting this one, I have an impression Views cache has problem when PHP 8.1 used.

```
alan@myho-web:/var/www/html/docroot$ php -v
PHP 8.1.22 (cli) (built: Aug 29 2023 10:48:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.22, Copyright (c), by Zend Technologies
alan@myho-web:/var/www/html/docroot$ 
```

As for the issue, please just see the video:

https://github.com/backdrop/backdrop-issues/assets/56604405/b0a0d4a2-b7b5-4d12-8dde-6fbe6004da71

**Comment by alanmels** [comment]
@indigoxela, thanks for looking. The operator wouldn't matter as I tried all of them, not only "contains", and the form didn't save the relative date field. 

To answer your questions, the content type is a custom one create via UI, the date field is also regular date field of a node with a start and end date collected, single value cardinality. And yes the field belongs to this particular node type, unfortunately log shows nothing.

Anyway, I have managed to get around this issue by exporting the view, deleting the existing one and importing manually edited code for the filter and everything is working fine for me. Therefore, let me close this issue until someone else will hit it.

**Comment by argiepiano** [comment]
@alanmels, by chance, did you try the form_cache fix I did for issue https://github.com/backdrop/backdrop-issues/issues/6228

**Comment by alanmels** [comment]
@argiepiano, I also thought so and tried this one after applying the solution for https://github.com/backdrop/backdrop-issues/issues/6228, unfortunately it didn't work.

**Comment by indigoxela** [comment]
> Anyway, I have managed to get around this issue by exporting the view, deleting the existing one and importing manually edited code for the filter and everything is working fine for me.

@alanmels so it really only seems some sort of ajax form submission thing. Apparently specific to your environment - be it another module interfering, be it something with your hosting... Hard to know without steps to reproduce. :thinking:
