### ISSUE TITLE
[DX] Drupal compatibility missing for file_create_htaccess

### ISSUE THREAD

**Issue by quackers8me** [backdrop/backdrop-issues#631]
I found that there appears to be a missing api call for drupal 7 compatability here. D8 and backdrop use the file_save_access instead. Shouldn't this api have a wrapper for compat?

https://api.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_save_htaccess/1

**Comment by quicksketch** [comment]
Doh, yeah another change that probably happened before Backdrop forked. Let's add a wrapper to drupal.inc and mark it deprecated.

**Comment by MrHaroldA** [comment]
> Let's add a wrapper to drupal.inc and mark it deprecated.
Looking at drupal.inc; there are only a couple of "@deprecated since 1.0" notices ...

**Comment by quicksketch** [comment]
> Looking at drupal.inc; there are only a couple of "@deprecated since 1.0" notices ...

The `@deprecated` tags are used on functions that don't start with "drupal". Though honestly, including a tag on every one of them would probably be appropriate.

**Comment by quicksketch** [comment]
I merged in https://github.com/backdrop/backdrop/pull/1049 into 1.x. Let's include this only in 1.2.0 and higher, so not backported to what will be the last 1.1.x release (1.1.4).
