### ISSUE TITLE
Correct the documentation comment for field_config_delete() which is a hook_config_delete() implementation

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6318]
[`field_config_delete()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.module/function/field_config_delete/1) has the following documentation comment.

```php
/**
 * Implements hook_config_update().
 */
```

That documentation comment is not correct, as that function implements [`hook_config_delete()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21config%21config.api.php/function/hook_config_delete/1).

**Comment by argiepiano** [comment]
LGTM

**Comment by kiamlaluno** [comment]
I updated the PR to be synchronized with the main branch.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno and @argiepiano! Merged https://github.com/backdrop/backdrop/pull/4592 into 1.x and 1.26.x.
