### ISSUE TITLE
Correct the documentation comment for field_config_update_validate()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6319]
In the _field.module_ file, [`field_config_update_validate()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.module/function/field_config_update_validate/1) has the following documentation comment.

```php
/**
 * Implements hook_config_create_update().
 */
```

Since `hook_config_create_update()` is not a documented hook, `field_config_update_validate()` must be a `hook_config_update_validate()` implementation.

**Comment by argiepiano** [comment]
RTBC

**Comment by quicksketch** [comment]
Thanks @kiamlaluno and @argiepiano! Merged https://github.com/backdrop/backdrop/pull/4593 into 1.x and 1.26.x.
