### ISSUE TITLE
Hide "Choose profile" step unless there's a custom profile installed?

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#632]
During installation, "Choose profile" gets automatically ticked and skipped. PHP 5.5.9 (Ubuntu 14.04.1 LTS) and defaults to standard in the url query string. If at database selection (Set up database) step I change profile=standard to profile=minimal, it works.
Is everyone else experiencing this or is it just me?

Edit: It happens on both 1.0.0 and 1.0.1

**Comment by quicksketch** [comment]
Yes, this is an intentional change. We marked the "minimal" profile hidden so that there is only one profile in Backdrop that is not hidden ("standard"). If you want to use the minimal profile, you can add it to the URL as you've noted. Minimal is kind of a "pro-user" option that has less use than before now that things like Overlay aren't installed in the first place, and if you need it, you can do it in the URL.

**Comment by chrisherberte** [comment]
It looks like this was intentional, not cool.

**Comment by quicksketch** [comment]
So to clarify, if you were to bundle another/multiple profile with Backdrop, the selection option wouldn't be skipped.

**Comment by chrisherberte** [comment]
Ok, thanks.

**Comment by chrisherberte** [comment]
@quicksketch should the "Choose Profile" step be hidden by default then unless there is a custom installation profile installed in /profiles? To me it looked broken, someone else will trip up on that surely. should be easy fix.

**Comment by quicksketch** [comment]
Sure, I'd love it if that step was just entirely hidden unless there was more than one (non-hidden) profile in the first place.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/710.

**Comment by mikemccaffrey** [comment]
Wow, this had me confused too. I've been wondering why the profile selection step was being skipped when I installed backdrop, and was about to create a ticket reporting it as a bug. 

Should we perhaps not diverge from drupal 7 in this aspect quite yet? If we start adding things to the standard install (see #519, #1042, #1043), it seems like having the option of doing a minimal install will become more important.

**Comment by jenlampton** [comment]
There are two different audiences we need to consider here: 1) the first-time user and 2) the experienced developer.

A first-time user will be confused and possibly blocked by this question during install. They don't even know what an install profile is, and they are being asked to choose one with no context or useful information.

Developers who know that they want the minimal profile most likely won't be using the UI to install. The UI is not for them. The UI needs to cater to those who will be using it, and those people will most likely (80%+) want the standard install profile.

(Also keep in mind that the first-time user's experience is more important than the seasoned developer.  See https://backdropcms.org/philosophy)

**Comment by jenlampton** [comment]
* Closing this issue since the profile step is successfully skipped unless additional profiles are added.
