### ISSUE TITLE
Use different short descriptions for hook_config_create() and hook_config_update()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6321]
[`hook_config_create()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21config%21config.api.php/function/hook_config_create/1) and [`hook_config_update()`](https://docs.backdropcms.org/api/backdrop/1/search/hook_config_update) have the same short description.

> Respond to or modify configuration creation.

That description should be changed for both the hooks.
- For the first hook, *modify configuration creation* does not make sense; it is the configuration values that are modified when they are created. *Respond to configuration creation.* makes more sense.
- For the second hook, the description should be *Respond to configuration updates.*

**Comment by kiamlaluno** [comment]
To make a comparison, the short description for [`hook_config_delete()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21config%21config.api.php/function/hook_config_delete/1) is *Respond to configuration deletion.* It does not say in which way the hook responds to configuration deletion. Similar short description should be used for the other two hooks.

**Comment by argiepiano** [comment]
LGTM and TRBC

**Comment by argiepiano** [comment]
I'm not sure this is a bug, though...

**Comment by kiamlaluno** [comment]
Usually, I consider changing a wrong documentation a task, as _bug_ for me means bug in the code. I have seen issues posted as bug when I would have posted them as task, and I did the same with the last issues I created.  

I am fine with marking them tasks, which for me is more correct.

**Comment by kiamlaluno** [comment]
I also changed the issue titles, to make clearer they are tasks.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno and @argiepiano! Merged https://github.com/backdrop/backdrop/pull/4594 into 1.x and 1.26.x.
