### ISSUE TITLE
Missing jquery.form.min.js.map file throws 404 errors

### ISSUE THREAD

**Issue by danksearle** [backdrop/backdrop-issues#6322]
## Description of the bug

I see warnings in my log of the type "page not found" with the message core/misc/jquery.form.min.js.map when I view one of our forms.

## Additional information

I found these issues for Drupal 8 that I think are related to this problem.
https://www.drupal.org/project/drupal/issues/2951787
https://www.drupal.org/project/webform/issues/3102576
https://www.drupal.org/project/webform/issues/2986142

**Comment by laryn** [comment]
@danksearle This should be fixed in `1.26.2` per https://github.com/backdrop/backdrop-issues/issues/6267

**Comment by argiepiano** [comment]
This seems to be a duplicate report for a fix that has already been merged. Closing.
