### ISSUE TITLE
Fixed: `<` gets encoded to `&lt;` by libxml >v2.9.14, causing broken HTML in generated summaries.

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6327]
## Description of the bug

In a [previous issue](https://github.com/backdrop/backdrop-issues/issues/6284) it has been discovered, that the behavior of libxml changed between v2.9.10 and v2.9.14, which results in failing TextSummaryTestCase tests with a current libxml version.

This doesn't show up in our automated test runs, as the runner OS is Ubuntu 20.04, which by default uses 2.9.10.

However, in many environments the version is already 2.9.14, and it will also change when we switch our runner to use a newer Ubuntu.

Note that the test rightly fails, as there's some cruft in the summary output, the opening `<` gets encoded to `&lt;`, which shows up in content.

## Steps To Reproduce

1. Make sure, your libxml version is new enough
2. Configure the summary to be shortened to 10 characters
3. Create a node with this content: `<p>456789</p>`
4. Visit the summary (wherever you configured it)

Or, if the devel module is installed, run following code:
```
$text = '<p>456789</p>';
$result = text_summary($text, NULL, 10);
debug($result);
```

## Actual behavior

You'll see `<p>456789&lt;</p>` (raw) or `456789<` as rendered markup.

Note the `&lt;`.

## Expected behavior

As in previous libxml versions, this opening `<` should get trimmed.

## Additional information

The easiest solution to let the summary behave like in previous versions seems to be to use code like that:
```
$summary = rtrim($summary, '<');
```
In function text_summary(), [right before  _filter_htmlcorrector()](https://github.com/backdrop/backdrop/blob/1.x/core/modules/field/modules/text/text.module#L496). Then the result would be the same, regardless of the libxml version.

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop/backdrop/pull/4597).

Note that the GitHub Actions test runner's still on ubuntu-20.04, so there's no difference, the TextSummaryTestCase passes, anyway.

But the sandbox has libxml 2.9.14, and in that the test now passes.

I didn't switch the runner OS version, yet, as that will take a lot more time.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼 

How do you feel about incorporating the same fix as https://www.drupal.org/project/drupal/issues/3204929 (adding the `LIBXML_NOBLANKS` flag wherever we are using `Html::load()`) in this PR? Or separate issue/PR you think?

Adding the list issues I mentioned in https://github.com/backdrop/backdrop-issues/issues/6284#issuecomment-1827665057:
- https://www.drupal.org/project/drupalci_environments/issues/3282786
- https://www.drupal.org/project/drupal/issues/3298822
- https://www.drupal.org/project/drupal/issues/1394394
- https://www.drupal.org/project/drupal/issues/3204929
- https://www.drupal.org/project/drupal/issues/2441811

**Comment by indigoxela** [comment]
@klonos are you sure, these D11 issues are related to summary generation in B?

For example, D11 uses Masterminds\HTML5, but we're using DOMDocument.

Can you give a concrete code example, where using this LIBXML_NOBLANKS flag fixes a problem we have?

**Comment by klonos** [comment]
> Can you give a concrete code example, where using this LIBXML_NOBLANKS flag fixes a problem we actually have?

No, this is not directly and specifically related to the problem with the summary text, but it is related to how libxml behaves inconsistently between some specific versions (which is the cause of the problem with the summary text). In our code, we are mainly using `DOMDocument::loadHTML()` in some of our tests (in `ViewsPluginStyleTestBase::storeViewPreview()`, `BackdropWebTestCase::parse()`,  `BackdropWebTestCase::backdropPostAJAX()` and `ThemeFunctionsTestCase::testBackdropPreRenderLinks()`) + also in `filter_dom_load()`, so I think that we should try to make sure that tests work consistently regardless of the libxml version they happen to be running on. That's why I though we should bundle that change here. Happy to create a separate issue and PR for that though.

> And also: one of the linked Drupal issues is about reverting that param change.

Yes, I have included that link as a FTR, since no decision was made on that yet. From the first comment on that issue:
>I guess the action here is either preserve whitespace, or close this as won't fix.

If I understood the proposal correctly, the change is to be reverted only for D11, and to specifically bump the libxml dependency/requirement in Drupal core at the same time (to make sure that a libxml version w/o the problem is always used). This change is not to be backported to earlier versions of Drupal, otherwise tests would need to be updated so that strings include the whitespace (removal?) to have them pass in previous versions of Drupal as well. We don't have a way to impose that restriction in Backdrop, unless we want to block installation on systems that are running those specific, problematic versions of libxml (or at least throw a warning on the status page about it), which is what https://www.drupal.org/project/drupal/issues/1394394 is to do for D7.

**Comment by klonos** [comment]
...here's how you can see the problem (test text `O<sub>2</sub> <strong>oxygen</strong>` used is the example provided in https://www.drupal.org/project/drupal/issues/3298822#comment-14790168).

Snippet used:
```php
<?PHP
$html = 'O<sub>2</sub> <strong>oxygen</strong>';
$dom = new DOMDocument();
$dom->loadHTML($html);
echo $dom->saveHTML();
```

### w/o `LIBXML_NOBLANKS`
https://onlinephp.io/c/12e15
- Result for 7.4.33, 7.3.33, 7.2.34, 7.1.33 (space removed):
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>O<sub>2</sub><strong>oxygen</strong></p></body></html>
```
- Result for 8.2.10: (space preserved):
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>O<sub>2</sub> <strong>oxygen</strong></p></body></html>
```
### using `LIBXML_NOBLANKS`
https://onlinephp.io/c/d9f51 
The result being the same across all php versions (7.4.33, 7.3.33, 7.2.34, 7.1.33, 8.2.10):
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>O<sub>2</sub><strong>oxygen</strong></p></body></html>
```

**Comment by indigoxela** [comment]
@klonos many thanks for the example, but keep in mind, that the PHP version doesn't actually matter. It's about the libxml version - independently from PHP.

The platform you linked to, provides _the same libxml_ version for all PHP examples (2.9.1).

Check with `echo LIBXML_DOTTED_VERSION;`
So the only result we get, is that the param changes display for all, but not the difference between PHP versions, unfortunately.

**Comment by indigoxela** [comment]
A "quick" :clown_face: experiment to switch the runner to 22.04, which means libxml 2.9.13: No failing tests re white space. 

The only one failing was CommonSimpleTestErrorCollectorTestCase, which @klonos already fixes in this [parallel issue](https://github.com/backdrop/backdrop-issues/issues/6284). Back to 8.2 to prevent conflicts.

We can switch to a newer runner version, we can stick with Ubuntu 20.04 - whatever we prefer.

**Comment by klonos** [comment]
> ... it's not the PHP version alone.

Yup, you're spot on on that 👍🏼 

This mostly affects our tests, which makes me less concerned, but it may be a very annoying DX if things fail on specific combinations of versions of PHP and libxml (thing about the layout test gremlin for example). It also affects the `filter_dom_load()` function, which may be used outside tests, but I cannot tell 🤷🏼 ...anyway, I am not fussed about this. If we don't handle it here, I will file a separate follow-up issue to keep it in our radar. Please carry on.

**Comment by indigoxela** [comment]
> This mostly affects our tests, which makes me less concerned...

Currently it doesn't seem to affect any of our existing tests, which makes it more difficult to decide, whether this problem affecting Drupal might also affect Backdrop. I'd really prefer to discuss this in a follow-up issue. The change, so deep down in our system, has the potential to break things and without related tests (neither passing nor failing) it's hard to evaluate.

@klonos many thanks for your patience.

**Comment by klonos** [comment]
> Currently it doesn't seem to affect any of our existing tests, ...

Perhaps that's because the images running our tests are using the "right" combination of PHP and libxml versions though.

> I'd really prefer to discuss this in a follow-up issue.

Yup, that's fine 👍🏼

**Comment by indigoxela** [comment]
PR updated to fix conflict.

**Comment by quicksketch** [comment]
I read over this issue and I'm inclined to accept @indigoxela's straight-forward solution. Also I'm drawn to the upgrade to Ubuntu 22.04 and it might help with some other issues where out-of-date software is causing unexpected problems. I merged https://github.com/backdrop/backdrop/pull/4597 into 1.x and 1.27.x. Thanks @indigoxela and @klonos!
