### ISSUE TITLE
Views page uncheck link to original node

### ISSUE THREAD

**Issue by richrda78** [backdrop/backdrop-issues#6329]
Link this field to the original piece of content unchecked not working for page view. 

A short description of what the problem is.
Title remains linked to original node. If I do the same to a block view it works as expected.

## Steps To Reproduce

To reproduce the behavior:
1. Create a view with title field.
2. Click Content title link
3. Uncheck  Link this field to the original piece of content 
4. Save view

## Actual behavior

Remains linked to original node.

## Expected behavior

No link to original node.

**Comment by argiepiano** [comment]
@richrda78 thank you for creating this issue. I'm trying to reproduce on a clean installation, but I'm unable. The title is not linked when I visit the page after deselecting the checkbox. Is there perhaps a missing step?

**Comment by richrda78** [comment]
I don't know, looked at all the options. So you can't reproduce, that's a shame. Not sure what it could be!

**Comment by argiepiano** [comment]
Are you still seeing this behavior? Have you cleared caches after saving the modified View?

**Comment by richrda78** [comment]
I can confirm it works on tables, bug happens on unformatted format.

**Comment by argiepiano** [comment]
> I can confirm it works on tables, bug happens on unformatted format.

Hmm... still works fine for me on unformatted lists.
<img width="418" alt="Screen Shot 2023-12-08 at 7 10 17 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/1ebcbd85-ca6d-47c5-999a-3412491352d3">

**Comment by richrda78** [comment]
Hehe, can confirm it works as expected if label enabled for title.

**Comment by argiepiano** [comment]
> Hehe, can confirm it works as expected if label enabled for title.

Still can't reproduce. I disabled the label, and the title is still not linked if I disable linking. Did you try the cache clearing I mentioned above?

<img width="349" alt="Screen Shot 2023-12-08 at 7 14 20 PM" src="https://github.com/backdrop/backdrop-issues/assets/9938978/632d5e92-105a-43f8-bd07-2b008cebd4f5">

**Comment by richrda78** [comment]
Damn, tried clearing all caches to no avail. No idea why it's sticking to a link. I'm on latest version of backdrop fyi.

**Comment by richrda78** [comment]
Now it's working as expected, bug must be with label use.

**Comment by stpaultim** [comment]
@richrda78 - Thanks for reporting this. I also tried to recreate this issue on a fresh site. I tried experimenting with other settings on the title field to find a combination that might cause the bug, but no luck. 

If you are able to create reproducable steps, let us know. 
Good luck on your project.

**Comment by richrda78** [comment]
I think this is probably related to not setting base theme in info file. It stopped after changing the label but I can't recreate so possibly a hocus pocus bug.
