### ISSUE TITLE
Admin bar mistakenly reveals disabled node types

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#633]
To reproduce:
1) create a few dummy node types
2) manually edit the "disabled" value in your config file for node type and enter a 1 instead of a 0 so one of them is disabled.
3) view the admin/structure/types page to see that Backdrop successfully hides the disabled type from the list
4) Hover over Structure > Content types in the admin bar, confirm that the disabled type still appears

**Comment by tarekdj** [comment]
@jenlampton node types are stored in files not database. However, even if you modify the json file manually and flush caches, disabled content types still appear not only in admin bar but also in admin/structure/types page.

PR to fixe it : https://github.com/backdrop/backdrop/pull/712

**Comment by jenlampton** [comment]
Right, sorry.  I noticed when upgrading a D7 site :)  issue updated!

**Comment by quicksketch** [comment]
Posted feedback on the PR: https://github.com/backdrop/backdrop/pull/712#issuecomment-71153484

**Comment by quicksketch** [comment]
Thanks @tarekdj for your work on this issue! I incorporated your fixes to disable node types when their parent modules are disabled, and then made a separate fix to admin menu to prevent it from displaying disabled types in its own menu.
