### ISSUE TITLE
Use #empty for the message to display when a table does not have any row

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6333]
In some cases, the code that renders a table in a page checks if the table does not have rows to then show a message when the table is empty.

### core/modules/dashboard/includes/block.node_types.inc

```php
    if (empty($rows)) {
      $rows[] = array(
        array(
          'data' => t('There are no content types to display.'),
          'colspan' => 4,
        ),
      );
    }
```

### core/modules/image/image.theme.inc

```php
if (empty($rows)) {
    $rows[] = array(array(
      'colspan' => 4,
      'data' => t('There are currently no styles. <a href="!url">Add a new one</a>.', array('!url' => url('admin/config/media/image-styles/add'))),
    ));
  }
```

### core/modules/taxonomy/taxonomy.theme.inc

```php
  if (empty($rows)) {
    $rows[] = array(array('data' => $form['#empty_text'], 'colspan' => '3'));
  }
```

### core/modules/views_ui/views_ui.theme.inc

```php
  if (empty($rows)) {
    $rows[] = array(array('data' => t('No fields available.'), 'colspan' => '2'));
  }
```

```php
  if (empty($rows)) {
    $rows[] = array(array('data' => t('No fields available.'), 'colspan' => '2'));
  }
```

In all those cases, an `'#empty'` value should be passed to `theme('table')`.

I did not include core/modules/dashboard/includes/block.menus.inc because in that case the code returns before rendering the table, when `$menus` is not empty.

```php
    if (empty($rows)) {
      // If there are existing menus, but user has no access to manage any of
      // them, hide the block completely.
      if (!empty($menus)) {
        return;
      }
      $rows[] = array(
        array(
          'data' => t('There are no menus to display.'),
          'colspan' => 4,
        ),
      );
    }
```

**Comment by kiamlaluno** [comment]
(Fantastic: I make commits for my fork, but they are not shown on github.com.)

**Comment by kiamlaluno** [comment]
The tests are failing because the *Call to undefined function layout_load_multiple_by_path()* error.

**Comment by kiamlaluno** [comment]
Actually, even the following code could be changed.

```php
    if (empty($rows)) {
      // If there are existing menus, but user has no access to manage any of
      // them, hide the block completely.
      if (!empty($menus)) {
        return;
      }
      $rows[] = array(
        array(
          'data' => t('There are no menus to display.'),
          'colspan' => 4,
        ),
      );
    }
```

It could be changed as follows.

```php
    if (empty($rows) && !empty($menus)) {
      // If there are existing menus, but user has no access to manage any of
      // them, hide the block completely.
      return;
    }

    // Use #empty in the table.
```

**Comment by kiamlaluno** [comment]
The failing tests are for the unknown words added with the *CKEditor 5* module.

**Comment by avpaderno** [comment]
There are conflicts between the upstream repository and the PR which needs to be fixed.

**Comment by avpaderno** [comment]
This time there are no test failures for the PR.

**Comment by laryn** [comment]
I looked over the code and I think it looks good.

I tested a few on the sandbox:
![CleanShot 2024-09-04 at 16 14 43@2x](https://github.com/user-attachments/assets/9f99cb62-bbe3-4e35-80d3-2c8a9146c081)

![CleanShot 2024-09-04 at 16 18 14@2x](https://github.com/user-attachments/assets/23a57fa4-ccc3-4217-bec5-81c80ff11afd)

**Comment by quicksketch** [comment]
Nice cleanup. Thank you @avpaderno and @laryn! Merged into 1.x and 1.28.x.
