### ISSUE TITLE
Taxonomy Description field and Tagged Content list are missing from Layout Blocks 

### ISSUE THREAD

**Issue by Wylbur** [backdrop/backdrop-issues#6335]
## Description of the bug

When creating a new layout for a taxonomy path, the taxonomy description field and block of latest content are not available as blocks.  

## Steps To Reproduce

1. Create a new layout and assign the taxonomy term context "taxonomy/term/%"
2. Remove the "Main Page Content" block
3. Add blocks to replace the main page content elements
4. The Taxonomy Description and Taxonomy display of tagged items are not available as blocks

## Expected behavior

The basic elements of the Taxonomy layout are available to rearrange the layout of the page. 

The is especially frustration as the description field cannot be deleted and always appears in the admin UI.

## Additional information

- Backdrop CMS version: 1.26.1
- Web server and its version: Apache
- PHP version: 8.1
- Database sever (MySQL or MariaDB?) and its version: MariaDB
- Operating System and its version: Ubuntu 22.04
- Browser(s) and their versions: Chrome/Firefox

**Comment by argiepiano** [comment]
The lack of the "description" field is related ot similar behaviors for other entities. For example, when working with nodes, you don't have a block for "title". The technical explanation is that Layout doesn't provide field blocks for non-fieldAPI entity fields such as node title and taxonomy description.   

To work around this limitation, you can use the module [Token Block](https://github.com/backdrop-contrib/token_block), which allows you to select the term from the context (in this case, it's provided by the placeholder in the path) and enter a token such as `[term:description]` in a block content.

As for tagged items - you can easily emulate that with a View and create a Views block that takes the tid as argument. Then place that block in the layout.

**Comment by Wylbur** [comment]
I'm an advanced user, with lots of options.  But for novice users this is a big hurdle.  We present layouts for UI site building, but the OOTB result will leave them stuck.  

Even as an advanced user, my only option to 'remove' the description is to hide it with CSS.

**Comment by argiepiano** [comment]
> Even as an advanced user, my only option to 'remove' the description is to hide it with CSS.

Hmm.. so, Token Block did not work for you? Can you clarify?

**Comment by Wylbur** [comment]
Yes, you can hide on the display, but not in the Manage fields (the Admin UI form).  

Sorry just venting now, but just wanted to say this does cause issues for new users.

**Comment by laryn** [comment]
Not an answer but a potential workaround for folks who may find this issue:
 - https://backdropcms.org/project/disable_term_node_listings

**Comment by Wylbur** [comment]
@laryn @argiepiano I really like that this project is on the verge of using the motto - "There's a module for that"!!!

**Comment by laryn** [comment]
I posted this on your other ticket just now, too, but it seems relevant here:

 - https://github.com/backdrop/backdrop-issues/issues/145#issuecomment-293983634

**Comment by Wylbur** [comment]
Thanks for the insightful feedback and resource! Closing this in favor of #145!
