### ISSUE TITLE
Enable CKEditor 5 out of the box

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6340]
## Description of the need

Follow-up from https://github.com/backdrop/backdrop-issues/issues/4122, we should enable CKEditor 5 out of the box in Backdrop 1.27.0 and mark CKEditor 4 hidden (and deprecated).

## Proposed solution

Update the standard profile to include CKEditor 5, remove CKEditor 4. Add `hidden = TRUE` to `ckeditor.info`.

**Comment by quicksketch** [comment]
Initial PR filed at https://github.com/backdrop/backdrop/pull/4613. This appears to be pretty simple.

To test:

- On an existing install of Backdrop with CKEditor 4, visit the `/admin/modules` page. Confirm `CKEditor 4 (Deprecated)` and `CKEditor 5` modules are both visible.
- Disable and then uninstall CKEditor 4 module.
- Now on the modules page, `CKEditor 4` should no longer be shown at all.
- Enable the CKEditor 5 module.

Separately, to test the new site experience:

- Fresh install of Backdrop
- Visit `/node/add/page`, CKEditor 5 should now be used instead of CKEditor 4.
- Visit `/admin/modules`, confirm CKEditor 5 module is enabled. The `CKEditor 4 (Deprecated)` module should not be shown at all.

**Comment by indigoxela** [comment]
> On an existing install of Backdrop with CKEditor 4, visit the /admin/modules page. Confirm CKEditor 4 (Deprecated) and CKEditor 5 modules are both visible.

I can not confirm that. CKE4 isn't visible anymore, so I'm unable to disable it.

**Comment by kiamlaluno** [comment]
Hidden module are not shown, even if they are enabled. At least, that is what I gather from [`system_modules()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.admin.inc/function/system_modules/1), which uses the following code.

```php
  $visible_files = $files;
  foreach ($visible_files as $filename => $file) {
    // Remove hidden modules from the modules list.
    if (!empty($file->info['hidden'])) {
      unset($visible_files[$filename]);
    }
  }
```

The list of available modules is then built from `$visible_files`.

**Comment by quicksketch** [comment]
Thanks folks, I think I misunderstood how `hidden = TRUE` works in .info files. If core doesn't have any readily available way to hide modules only when disabled, then perhaps we should scope this to just enabling CKE5 and adding the word "Deprecated" to CKE4. I'll update the PR.

**Comment by laryn** [comment]
@quicksketch Here's how Paranoia hides some modules from the modules page. I assume we could adjust the logic in a hook like this to hide CKEditor 4 if it's disabled:

```
/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide Paranoia and PHP modules from module admin form.
 */
function paranoia_form_system_modules_alter(&$form, &$form_state) {
  $hidden_modules = module_invoke_all('paranoia_hide_modules');
  foreach ($hidden_modules as $module => $package) {
    // Unset instead of using #access because #access => FALSE shows an empty
    // table row.
    if (isset($form['modules'][$module])) {
      unset($form['modules'][$module]);
    }
    // Adds support for module_filter.
    if (isset($form['modules'][$package][$module])) {
      unset($form['modules'][$package][$module]);
    }
  }
  // Invoke custom validation function to disable banned modules on submit.
  $form['#validate'][] = 'paranoia_module_validate';
}
```

**Comment by quicksketch** [comment]
Thanks @laryn. For now I just removed the `hidden` flag so it always shows. I'm not even sure hiding it is an entirely good idea. Maybe for the 1.27.0 release it might even be beneficial to leave it for people during the transition.

**Comment by indigoxela** [comment]
> Maybe for the 1.27.0 release it might even be beneficial to leave it for people during the transition.

That sounds like a good idea. :+1:

**Comment by indigoxela** [comment]
If we still need the module to not getting enabled again... a quick experiment in function system_modules(), somewhere in the foreach, that loops over the module infos.

```
    if ($module->name == 'ckeditor' && !$module->status) {
      $extra['disabled'] = TRUE;
    }
```

That would still show the module, but disables the checkbox - if the module isn't enabled.

Of course, in the same function we could alternatively completely skip over the module, to not show it at all ... but isn't that a bit confusing? The module might still show up on the "Uninstall modules" page.

Anyway, we can easily discuss these details in a follow-up issue and stick with the obvious change - enabling CKE5 by default in new installs - here.

**Comment by kiamlaluno** [comment]
Making impossible to enable the module would be less confusing than hiding it, if the module is clearly marked as deprecated.  
I can imagine people confused by not seeing it, even though its files are present in the correct directory. Given they are used to see it listed in the list of module they can install, the confusion would be understandable.

**Comment by kiamlaluno** [comment]
Drupal 9.x added a new status for modules (*deprecated*). That avoids to have an explicit list of modules that need to be handled differently.  
For a single module, we can live with three code lines handling the CKEditor module.

**Comment by indigoxela** [comment]
> For a single module, we can live with three code lines handling the CKEditor module.

Maybe. AFAIK this is the first time, that we have to deprecate a core project in B, but in as 2.x comes closer, we might as well need a cleaner separation.

**Comment by herbdool** [comment]
It's plausible that some has CKEditor disabled or will disable and then wants to re-enable it for the short term, so preventing them from doing that might cause some anguish. So for now, just adding "deprecated" is adequate.

**Comment by quicksketch** [comment]
Yeah, I'm definitely inclined to just going with what we have readily available and follow-up as needed. I think https://github.com/backdrop/backdrop/pull/4613 is ready with that approach.

**Comment by indigoxela** [comment]
Works like a charm. :+1: 

- In a first step I applied the patch to an existing install - nothing changes
- The I did a fresh install - v5 is the default editor, everything works as expected

I think, this is good to go.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4613 into 1.x to enable it as the default. Thanks so much @indigoxela for reviewing! Thanks @laryn, @herbdool, and @kiamlaluno for your helpful feedback. Hiding the module might be helpful in the future when the total number of CKE4 installs drops down to a smaller percentage.
