### ISSUE TITLE
Merge ckeditor5.compat.js from CKEditor 5 to into CKEditor 4 module

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6341]
## Description of the bug

CKEditor 5 in contrib needed to provide a `ckeditor5.compat.js` file that fixed incompatibilities with CKEditor 4. Now that both are in core, we can move this file's contents into the core CKEditor 4 module.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4612.

To test:

- Set up a text format that uses CKEditor 5
- Also set up a text format that uses CKEditor 4
- Visit `/node/add/page` and confirm that CKEditor 4 and CKEditor 5 can be attached to the body field by switching between text formats. They should switch back and forth with no errors.

To see the previous bug that is present without this code, comment out the added lines in `ckeditor.js` from the PR. Then when switching to CKEditor 5, you'll see that the body field gets _two_ toolbars. Both the CKEditor 4 and 5 toolbar are active at the same time(!) This happens because CKEditor 4 by default automatically attaches itself to any `contenteditable` element on the page. See https://github.com/backdrop-contrib/ckeditor5/issues/43 for more info when this issue was originally discovered.

**Comment by indigoxela** [comment]
This works like a charm. :+1: 
It's much easier now that CKEditor 5 is in core.

**Comment by quicksketch** [comment]
Thanks, I fixed that one typo and merged!
