### ISSUE TITLE
Better reporting for CKEditor 4 vs 5 in Telemetry

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6342]
## Description of the need

Follow-up from https://github.com/backdrop/backdrop-issues/issues/4122.

Right now both CKEditor 4 and CKEditor 5 modules implement `hook_telemetry_info()` to report their respective CKEditor version strings. For example:

CKEditor 4 returns `ckeditor_version` of `4.18.0`
CKEditor 5 returns `ckeditor5_version` of `40.2.0`

While this data is useful in some ways to tell how up-to-date our library usage is, it's not helpful for distinguishing between CKEditor 4 and 5 (or both) usage. To do that we need a separate return value of either `4`, `5`, or `both`.

## Proposed solution

Since each module can only report if it is enabled, I think it would make sense to include this value in telemetry.module directly.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/4614 that adds this to telemetry.module.

To test:

- Visit `admin/reports/telemetry`
- Confirm the "CKEditor Module Version" is present with one of the following values:
  - CKEditor 4
  - CKEditor 5
  - Both CKEditor 4 and 5
 
As shown below:
![image](https://github.com/backdrop/backdrop-issues/assets/100206/767843fc-e837-4058-8e63-74db49fa1900)

**Comment by olafgrabienski** [comment]
I've checked the PR in the sandbox: works for me in all combinations (module version 4, 5, and both).

Side note: The new value is at the bottom of the telemetry page (see screenshot below). It would be nice to have it near the other CKE value, e.g. by sorting all items alphabetically. (Should probably be a separate issue.)

**Comment by quicksketch** [comment]
> e.g. by sorting all items alphabetically. (Should probably be a separate issue.)

Yeah what's happening here is it's sorting by Project Name (CKEditor, System), and then inside of that by the order specified in the module's `hook_telemetry_info()`.

**Comment by indigoxela** [comment]
That was actually a question that also came to my mind: is this PR supposed to be an addition to or a _replacement_ for ckeditor_telemetry_info() and ckeditor5_telemetry_info()?

Another thought: data-wise this only checks which of the CKE's enabled, but doesn't provide the "none of both" info. That info will be available by subtracting these numbers from the full result's number on our [telemetry page](https://backdropcms.org/project/backdrop/telemetry). But the percentages displayed will be misleading. I know, that's rather a display problem, than a data collection problem, but... still a bit misleading.
And yes, I'm aware that the "Multisite" dataset is much worse re that. :wink:

**Comment by quicksketch** [comment]
I'm not sure, in https://github.com/backdrop-contrib/ckeditor5/issues/84 we discussed maybe making a `filter_telemetry_info()` to track _all_ installed editors. I think what we're looking for here is determining when most sites have upgraded to 5. I don't think `None` would hurt, though it's not necessarily relevant to answering that question. What do people think?

**Comment by indigoxela** [comment]
> I think what we're looking for here is determining when most sites have upgraded to 5.

Yes, understood. So if my comment is a bit out of scope here, it's OK for me to just move on. :wink:

**Comment by indigoxela** [comment]
The code looks good. :+1: No idea, if there's anything to test besides the display on /admin/reports/telemetry :wink:

**Comment by indigoxela** [comment]
If neither module's enabled, the report on /admin/reports/telemetry looks a bit odd, and the text doesn't fit well.

![telemetry-cke-nothing](https://github.com/backdrop/backdrop-issues/assets/842066/98d0c84d-6122-470e-bc2d-57ca6858859f)

How about slightly different wording?

"CKEditor module major versions enabled on your site (either 4, 5, both or neither)."

And add "neither" if none of both's enabled. Or don't display (and report) at all, if none of both module's enabled? Not sure if that's currently possible, though.

**Comment by quicksketch** [comment]
Thanks @indigoxela, I guess adding "Neither" would solve several problems, so I added that to the PR. I also incorporated your updated description.

**Comment by indigoxela** [comment]
@quicksketch many thanks for the update, works for me. :+1:

**Comment by quicksketch** [comment]
Fantastic, thanks again @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4614 into 1.x for 1.27.0.
