### ISSUE TITLE
CKE5: Multiple editors attach to Body when Paragraph fields have rich text

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6344]
## Description of the bug

Multiple CKEditors attach to the body field when there are Paragraph field(s) below which contain rich text fields. It does not seem to do this if it's just two rich text fields on the content type directly.

## Steps To Reproduce

To reproduce the behavior:
1. Configure CKEditor 5 on a text format
2. Add a rich text field on a Paragraph type
3. Add that Paragraph type to a Paragraphs field on a content type
4. Create content of that type

## Actual behavior

When loading the add/edit screen, the Body field receives multiple CKEditor instances.
![image](https://github.com/backdrop/backdrop-issues/assets/871421/40002026-8ec3-4cc2-85c9-a58702c25ef6)

## Expected behavior

No extra "dummy" CKEditor instances.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.27.x-dev

**Comment by indigoxela** [comment]
@laryn  Your screenshot looks weird, but I'm not able yet, to reproduce.

What I tried:

- A new content type with a body field (field cardinality = 1)
- A paragraph type with text field attached ("Text (long)" with editor)
- A paragraph field attached to content type (field cardinality unlimited)
- Added content, one "main" body, three rich text paragraphs
- Saved, reopened form - all looks good.

Which step am I missing?

**Comment by laryn** [comment]
Strange, I did reproduce it locally on a separate site -- I'll try to narrow down what else is needed for this to happen at some point today.

**Comment by argiepiano** [comment]
@laryn, please see if https://github.com/backdrop/backdrop/pull/4618 fixes your issue.

**Comment by quicksketch** [comment]
I think this is the same issue as https://github.com/backdrop/backdrop-issues/issues/6347, and has been fixed by https://github.com/backdrop/backdrop/pull/4618.

**Comment by laryn** [comment]
I can confirm that the fix linked above also fixes this issue on my local.
