### ISSUE TITLE
Add status report message informing about CKEditor 5 upgrade

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6346]
## Description of the need

We should add something to the status report about CKEditor 4 being deprecated and how to upgrade to CKEditor 5.

## Proposed solution

To be discussed, but maybe a `REQUIREMENT_WARNING` output by `ckeditor_requirements()`, if the module is enabled it just always outputs a warning that the module is deprecated?

## Alternatives that have been considered

TBD

**Comment by quicksketch** [comment]
I filed at PR at https://github.com/backdrop/backdrop/pull/4616. It does a few things:

- Outputs a status report warning if CKEditor 4 module is enabled at all.
- Removes the warning if CKEditor 4 is enabled but not on any text formats (since the one warning to stop using CKE4 is probably enough).
- Adds an info message when CKEditor 5 is enabled directing to the text formats page if CKEditor 4 is still in use.

**Comment by indigoxela** [comment]
It just came to my mind, that CKEditor4 has a (paid) LTS program.

While it's rather unlikely that people use that with Backdrop - do we have to consider that in any way?

**Comment by quicksketch** [comment]
> While it's rather unlikely that people use that with Backdrop - do we have to consider that in any way?

If there were a premium plugin offered, it has the option potentially of using `hook_telemetry_data_alter()` to inject itself as an additional returned value. But maybe the hypothetical `filter_telemetry_data()` that returns _all_ text editors might be a sufficient way to track that option.

**Comment by indigoxela** [comment]
> ...has the option potentially of using hook_telemetry_data_alter() to...

That's telemetry, but this issue's about the status message (hook_requirements), and there's no alter hook for that. :wink:

**Comment by quicksketch** [comment]
Oh I see, sorry I thought this was in https://github.com/backdrop/backdrop-issues/issues/6342.

Good question. We don't know what that would look like. It could be a different module, or a module that alters the core module, or it could just be replacing `/misc/ckeditor` with an updated version. Perhaps we don't need to worry about it since it doesn't exist yet, and work with the request once it's been made.

**Comment by indigoxela** [comment]
> Perhaps we don't need to worry about it since it doesn't exist yet, and work with the request once it's been made.

Seems reasonable. Personally, if I'd implement something like that, I'd probably go with a hook_library_info_alter() and some tweaks in hook_ckeditor_settings_alter()... However, it's very likely an edge case.

Re status messages, this is what we have now, if both modules are turned on and 4 is in use, but 5 isn't:

![cke-status-report](https://github.com/backdrop/backdrop-issues/assets/842066/ef5bc2a1-2baa-4f55-880e-f52c92381ed8)

Note that 5 doesn't report its version (yet), and that info only shows up if 5 isn't in use.

**Comment by indigoxela** [comment]
Some quick ideas...

As we should name CKE4 consistently, I'd suggest to also rename it as `'title' => $t('CKEditor 4 (Deprecated)'),` on the status page.

The hint to enable the CKE5 module also shows up, if the module's already on, which seems odd to me.

CKE5 should also report its version and that info should also show up, if the editor's already in use.

**Comment by kiamlaluno** [comment]
The shown message says that the _CKEditor 5_ module is installed, but none of the input formats uses CKEditor 5 (the input filter).  
*installed but not enabled* is a confusing phrase, as *installed* and *enabled* are usually terms used for modules, while in this case *installed* is referred to the module, but *enabled on any formats* is referred to the input filter implemented by that module.

**Comment by kiamlaluno** [comment]
Probably, *but has not been added to any format* could avoid any confusion.

**Comment by quicksketch** [comment]
Thanks for the feedback @indigoxela and @kiamlaluno. I made the following changes:

- Added `(Deprecated)` to `CKEditor 4` label in `ckeditor_requirements()`
- Added separate `ckeditor5_version` as `REQUIREMENT_INFO` with version information.
- Made `To start the upgrade to CKEditor 5, enable it from the modules page.` conditional based on if CKEditor 5 is already enabled.
- Changed "enabled on any formats" to "added to any text formats". (And note that Backdrop refers to these as "text formats" throughout core, not D7-verbage "input formats").

**Comment by indigoxela** [comment]
This looks great now! :+1:

**Comment by quicksketch** [comment]
Thanks @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4616 into 1.x for 1.27.0.
