### ISSUE TITLE
When Body uses CKE5, additional Body entry fields are added to the form when clicking "Add another" for a different field

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6347]
## Description of the bug

If your content type has a field (such as a Text (short) field) with unlimited cardinality, clicking "Add another" will add a new field to both, the Body field (!!) and the unlimited Text (short) field.  

## Steps To Reproduce

1. On a clean install with the dev version of Backdrop (so that you have CKE5 as default in core), edit the Page content type and add a Text (short) field with unlimited cardinality, call it "My text"
2. Visit the add content form for Page
3. Click "Add another" for the "My text" field

## Actual behavior

Additional widgets are added to both, the "My text" field and the "Body" field. 

## Expected behavior

An additional widget should be added to "My text" field only. 

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version:  current dev version slated to be released as 1.27.0
- PHP version: 8.1.13

**Comment by argiepiano** [comment]
This behavior exists also when any widget has any AJAX-enabled action. For example, when you have a File field in the node and select a file. The Body field gets duplicated every time.

**Comment by argiepiano** [comment]
A bit of digging here: the `Backdrop.editors.ckeditor5.detach` method supposedly should destroy the editor. There is an `if` [statement](https://github.com/backdrop/backdrop/blob/19dc618f14b47c80d5734e781d4fb89f4d9d3fcc/core/modules/ckeditor5/js/ckeditor5.js#L110) in that method that only destroys the editor if the trigger is not `serialize`. 

The problem here is that AJAX requests will produce a `serialize` trigger every time, as explained in the [documentation](https://github.com/backdrop/backdrop/blob/19dc618f14b47c80d5734e781d4fb89f4d9d3fcc/core/misc/backdrop.js#L109) of `backdrop.js`.

An obvious solution would be to get rid of that if statement, but I don't know enough about CKEditor to figure out if this may create other issues.

Since the editor is not destroyed, it remains in the DOM, and a new one is created when the ajax response is processed.

**Comment by argiepiano** [comment]
Here's a PR: https://github.com/backdrop/backdrop/pull/4618

I decided to go for the second option: avoid creating a CKE5 editor if it already exists in the page. I tried option 1 (always destroying the editor) but that creates some visual issues, since, when the editor is destroyed, the page temporarily shows the HTML markup for a second or two before the ajax response is processed.

**Comment by indigoxela** [comment]
@argiepiano something similar has been reported recently https://github.com/backdrop/backdrop-issues/issues/6344

**Comment by indigoxela** [comment]
> the Backdrop.editors.ckeditor5.detach method supposedly should destroy the editor

Not necessarily. The "serialize" trigger, for instance, should allow the editor to write text to the hidden textarea form item.

I'm not sure, why the attach runs for the unrelated body field outside the ajax container... :thinking: 

However, I can confirm that preventing the additional attach, when there's already an attached editor works properly.

**Comment by indigoxela** [comment]
Setting milestone to 1.27 - CKE5 will be part of it.

BTW, weird, that I didn't see the same odd behavior with the other issue (related to paragraphs).

**Comment by argiepiano** [comment]
> I'm not sure, why the attach runs for the unrelated body field outside the ajax container... 🤔 Seems to be normal behavior.

Thanks @indigoxela. Yes, in my experience, I've seen all attach methods currently loaded in the browser run when ajax requests are processed.

**Comment by indigoxela** [comment]
@argiepiano many thanks for the comment update. Much better. :+1:

Re attaching multiple editors to the same form element:
Seems like this is another thing that v4 took care of, but v5 doesn't check anymore.

**Comment by quicksketch** [comment]
Thanks @argiepiano and @indigoxela! I merged https://github.com/backdrop/backdrop/pull/4618 into 1.x for 1.27.0.
