### ISSUE TITLE
Config sync doesn't see reordering of elements in JSON file as a change

### ISSUE THREAD

**Issue by danksearle** [backdrop/backdrop-issues#6348]
## Description of the bug

I use a staging folder that isn't emptied so it can be version controlled. When I receive config edits from other developers I run "bee bcim" to import them and update my local site. However, if the only change in the file is that the order of some fields in the view display have changed, then Bee can't detect that change and therefore it fails to import.

I had a lot of fields to reorder, which was fiddly and slow via the UI so I did it in a code editor, but when I tried to import my changed JSON file, Bee didn't see any changes.

I could work around that problem by editing the view description string and importing that - Bee detected that change and imported the file, which also updated the order of the fields. Then I undo the text change and reimport, the result is that the fields are ordered as I wanted. So, there is that work around available, but the bug still stands.

[EDIT]:
## How to reproduce:

1. Create a view of Content with two fields: nid and title
2. Do a full export at `admin/config/development/configuration/full/export`
3. Modify the view above by changing the order of the two fields in the UI
4. Head to `admin/config/development/configuration/full` and import the zip file you exported in step 1. This should redirect you to the sync UI page to complete the synchronization.

## Actual behavior
You get the message `The uploaded configuration matches the current site configuration exactly. No changes were made.`  The import did not detect the change of order in the fields. The modifications do not appear in the list of changes in the Synchronize UI

## Expected behavior
The changes should show up, allowing you to import the staged modified file into active.

## Additional info
The culprit is in config.admin.inc, line 523. Currently that line has the "not equal" operator. It should use the "not identical" one.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4622 ready for review.

It was suggested that an automated test may be useful. I can try and write one later, unless someone else would like to tackle that.

**Comment by argiepiano** [comment]
Automated test added. PR ready for review.

**Comment by argiepiano** [comment]
A bit more tweaking needed. The test doesn't detect the problem. Back to NW

**Comment by argiepiano** [comment]
Test has been fixed to detect the original problem without the PR. Now, ready for testing and review. (BTW the "usual friendly" upgrade test failed, but those are unrelated to this one).

**Comment by indigoxela** [comment]
@argiepiano many thanks for your quick PR and for the functional test. :pray: 

This looks great (a tiny recommendation re method visibility...).

**Comment by argiepiano** [comment]
Thanks @indigoxela. I responded. All the other test methods in that class are public, so I don't understand why we would want to make the new test method protected. Can you please clarify?

**Comment by indigoxela** [comment]
> Can you please clarify?

I tried. :wink:

**Comment by argiepiano** [comment]
Thanks, @indigoxela. Is there any documentation that indicates the test methods should be protected? I'm checking Drupal 10, and test methods (not the helpers methods) are still all public.

**Comment by indigoxela** [comment]
@argiepiano there's no documentation I'm aware of, no. I think, "protected" is correct, as "public" just isn't necessary, that's all. Maybe we should discuss that (visibility and documentation) in a different issue? I wouldn't want to derail this issue here. :wink:

**Comment by argiepiano** [comment]
Thanks @indigoxela. Since you are ok with this, I prefer to leave it public for consistency with the rest of the file.

**Comment by kiamlaluno** [comment]
Test methods need to be public because the list of the tests implemented by a class is retrieved with [`get_class_methods()`](http://php.net/get_class_methods). (See [`BackdropTestCase::run()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21simpletest%21backdrop_web_test_case.php/function/BackdropTestCase%3A%3Arun/1).)
When called from outside the class, `get_class_methods()` returns only public methods. (It can be verified with code similar to the following one.)

```php
class Test {

  protected function testProtected() {
    echo "protected \n";
  }

  private function testPrivate() {
    echo "private \n";
  }

  public function testPublic() {
    echo "public \n";
  }

}

$test = new Test();
var_dump(get_class_methods($test));
```

**Comment by argiepiano** [comment]
@kiamlaluno, I think public is better for consistency within the `config.test` test file, but I also agree with @indigoxela that we should probably define this for the future, and refactor all those test functions (ouch).

To respond to your point:  `get_class_methods()` is indeed being called from **inside** the class `BackdropTestCase`. This is the class that all tests in Backdrop extend, so in practice, calling `BackdropTestCase::run()` is calling `get_class_methods()` from inside the test classes in Backdrop. 

Indeed, there are several tests in Backdrop that are `protected`. See for example `NodePageCacheTest::testNodeUpdateInsertCache()`.

**Comment by herbdool** [comment]
While I think this change is needed, the trade-off is that it catches *all* the reordering that can happen creating more "noise", even if that reordering doesn't mean anything. I tested this by reordering two variables in `system.core.json`. The reorder is meaningless in terms of functionality. Without the PR the change is ignored, and with the PR it shows a diff.

Funnily, I recall seeing a bit of this here and there (or is that in Drupal 10?).

**Comment by argiepiano** [comment]
Perhaps a better approach would be 5o modify views to use weights instead of relying on simple key ordering.

**Comment by herbdool** [comment]
Though that's probably a big job and probably not backwards compatible.

**Comment by indigoxela** [comment]
@herbdool I get your concern re "noise". This also came to my mind, but my conclusion was: it should always have been strict comparison. Sure, order actually only matters for views, but if people use git for config version control, the loose comparison would have caused problems, anyway, when the only change is reordering of config items.

And I don't think, it's even possible to rewrite views for using field weights in a backwards compatible way. At least, not without major problems.
I'd find it quite an escalation from a single character change to rewriting the basic concepts of views. :laughing: Let's stick with strict comparison here, please.

**Comment by herbdool** [comment]
@indigoxela yes, I've already approved this PR. No need to convince me, despite my reservation. :smile: 

Just found an example of where reordering elements already shows up, so we're already getting this noise just not at the primary level. For any element that is two or more levels deep in the array we see something like this (copied a diff of an image field):

```
--- a/config/staging/field.field.field_image.json
+++ b/config/staging/field.field.field_image.json
@@ -10,11 +10,11 @@
     "deleted": "0",
     "entity_types": [],
     "settings": {
+        "uri_scheme": "public",
         "list_field": "0",
         "list_default": 1,
         "description_field": "0",
-        "default_image": null,
-        "uri_scheme": "public"
+        "default_image": null
     },
     "storage": {
         "type": "field_sql_storage",
```

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4622 into 1.x and 1.26.x. Thank you @danksearle for pointing out this issue and the great original report! Thank you @argiepiano, @indigoxela, @kiamlaluno, and @herbdool for collaborating to come to this resolution.

For the record, I'd also like to have "something" done about key order in config files. I believe Drupal ultimately decided to list keys alphabetically. Of course that would cause the very problem we were seeing in Views where the key order has meaning. I considered maybe comparing against the "original" config and using that order when available.

In any case, it's a separate issue than this bug. Thanks folks for the work on this fix!

**Comment by klonos** [comment]
Sorry for coming late to the party - been checking issues and commits that have been merged while I was away...

My only comment not just for this specific issue, but anywhere where there is discussions around why we are doing things in a specific way and not another, as well what the problem would otherwise be is that we should be adding inline comments to explain why + link to issues where the detailed discussion has happened. Too late now, but just saying.
