### ISSUE TITLE
[UX] Clean up the Search and Metadata config section

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#635]
Why is the list of paths "Search & Metadata"? 

Why is Clean URLs under "Search & Metadata"?

Proposed changes:
- Create a new page "URL handling" under "Configuration"
- Rename the current "URL handling" page to "General settings" under "URL handling"
- Move "URL aliases" under "URL handling"
- Move "URL redirects" under "URL handling"
- Change "Search and metadata" to "Search"
- Add a new 2nd-level item for "Metadata" (unused in core, like User Interface)

---

Latest PR: https://github.com/backdrop/backdrop/pull/1673

**Comment by BWPanda** [comment]
I think it's fine under 'Metadata' as that's where other URL-specific settings are: 'URL aliases' and '[URL redirects](https://www.drupal.org/project/redirect)'.

**Comment by jenlampton** [comment]
The point is that "Search & Metadata" is not a good place for any of that other stuff either...  Lists of paths and redirects should also be moved, but none of that is in core so we don't get to decide where to put it :)

The point is that when I'm looking for Clean Urls, PathsAliases, or Redirects I never think they have anything to with "Search" (what my eye scans). So why would I look under that menu (or on that page) for them?

Ah Metadata: What does metadata mean to you?  To me it's keywords, descriptions, maybe file types and post dates, maybe even authoring information.  never URLs.

(I also think pathauto settings should be declared on the entity-bundle edit form)

**Comment by BWPanda** [comment]
> Lists of paths and redirects should also be moved, but none of that is in core (yet)...

Core's 'Path' module provides the 'URL aliases' settings page (admin/config/search/path) (Pathauto adds settings to this page, but it already exists in core), so that could also be addressed by this issue at least.

**Comment by jenlampton** [comment]
Ah, I stand corrected :)

**Comment by klonos** [comment]
We have "Search and metadata" but under that menu there in no metadata settings AFAICT. In fact I don't think we have any metadata settings in Drupal/Backdrop (if we actually do have, then somebody please correct me). Was that added there to support certain (popular) contrib like [Metatag](https://www.drupal.org/project/metatag)perhaps?

Anyways, point is that Jen is right...

- The "metadata" thing should go away and let related contrib decide what to do with regards to a config submenu.
- We should consider renaming the menu to something that will make more sense to end users like "Paths and search" or "Search and paths" (that would also pave the way for #87)
- I believe we should avoid using the term "URL" as a top-level menu.

**Comment by jenlampton** [comment]
Why are those two things even lumped together? Why not a section for search, and one for paths? We could have Aliases, Redirects, etc, all under paths, and Search settings, Solr settings, Facets, all under search.

**Comment by davidhwang** [comment]
The logical grouping of these items under 'Search' is no doubt an artefact of meta tags and urls and all that being SEO-related. Maybe it makes sense to consider that as a tab name?

**Comment by jenlampton** [comment]
I wouldn't scan for "SEO" If I were looking for Search or Paths.  Why not just call them what they are, and remove the grouping?

**Comment by docwilmot** [comment]
"Search & Metadata" is currently unnecessary as a grouping. Move to "System" makes most sense. 

Incidentally though, I'd also vote to really simplify the entire configuration listing. Finding anything in there is laughable most of the time. I'd keep:
* Development
* People
* User Interface
* System

Gives me *only* a max 75% chance of being wrong when I hunt for settings, and I'm certain most things would fit in one of those logical categories.

**Comment by Bojhan** [comment]
I would like to ask you to look into some of the process around this. These things were not decided on a whim, they were decided at the time keeping in mind the growth of RDF and search driven interfaces. I do agree that this category is particularly difficult, and possibly wrong. 

Overall docs: https://www.drupal.org/node/549094 
Issue implementation: https://www.drupal.org/node/557890

I do have a larger blog post, but sadly my blog is down (hah). You can change pretty much all of these categories on a whim, on your own perceptions of what is better. This is totally legitimate, however having designed these information architectures over many years. It's likely that you can only truly validate this when you throw in reality, with different permissions, dozens of modules installed, etc. Looking at it in isolation (only Backdrop core) is somewhat misguided.

More or less categories won't help you, what will help you is the "right categories" and the "right" navigation method. Holistically I would challenge you to think about a dramatically different interaction model, that is not a plain listing. I think that after exploring the product, a major part of this interface is just finding the right configuration page. Which is much more task and focused, also known as "know-item" seeking for which you ideally have some kind of search method or contextual config.

**Comment by jenlampton** [comment]
Thanks for these links!  will give them a read.

I'm positive `Search and Metadata` is not the "right category" for backdrop, but I'm not sure what is.

Backdrop does have a plain listing on the config page, but it also has the drop-down menu, and the search box in the menu. So I think we're two steps ahead of Drupal in that area already. I would still like to try a different category.

Remember back in Drupal 6 when paths were a second-level item under Structure? That was a much better fit than a third-level under "Search and metadata".  Maybe we should start there.

**Comment by quicksketch** [comment]
Some issues related to this one that we should take into consideration:

- In https://github.com/backdrop/backdrop-issues/issues/865, we're renaming this menu item from "Clean URLs" to "URL handling", and making it a clearing house for URL options.
- That issue also adds a new option that does actually affect meta tags (determining if HTTPS should be used for the `canonical` meta tag).
- There's a spin-off issue to redirect all non-aliased paths to the canonical URL at #868 that would also live at this page.

In the spirit of iterating frequently instead of blocking issues on separate problems, I'm encouraging #865 to move ahead separate of this one. If we decided to move this menu item before 1.1.0, we can move it again without additional redirects. If we wait until after 1.1.0, we'll need another redirect for the new location.

**Comment by serundeputy** [comment]
reviewing patch: https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/1203.patch

- [x] Move "URL aliases" under "Structure"
  * `URL aliases` is under Structure and still under Search; I don't think that is bad still where old schoolers will look and in the new place.
- [x] Mover "URL Handling" under "System"
- [x] Change "Search and metadata" to "Search"

- [ ] `PR` had 1 fail in `layout.test` the `Layout Upgrade Test` gave an ajax error; I'm not sure how to interpret those though.

**Comment by jenlampton** [comment]
> and still under Search

Did you try clearing your caches?  It wasn't *supposed* to be in both places ;)

**Comment by quicksketch** [comment]
This PR now needs rerolling due to the new changes in #899 and #1250.

**Comment by jenlampton** [comment]
Rebased and resolved conflicts.

**Comment by quicksketch** [comment]
Okay I looked over this PR and had a discussion with @mikemccaffrey in Gitter on it. I'm feeling ambivalent.

URL aliases right now are fairly hidden away, but I don't find the need to visit them very frequently. 9/10 times I edit an alias by visiting the piece of content on which the alias is placed. So I don't mind aliases being hidden away.

With the new URL alias settings accessible on the Vocabulary, Content Type, and User Administration forms, accessing the general URL alias settings will also become less common.

Let's look at each of the changes recommended here:

> Move "URL aliases" under "Structure"

URL aliases under Structure seems questionable. Now that blocks are configuration, we're clearly storing *most* things from this menu in configuration. The one exception to this is Menu Items (questionably stored in the database right now).

On the other hand, I can see how this would be categorized as "Structure" fairly clearly. The URLs of your site are definitely as structural as the Menus or the types of content.

> Move "URL Handling" under "System"

Mixed about this too. The setting for "Canonical URL" affects the meta tag at the top of the page, which is why it is in this category of "Metadata".

> Change "Search and metadata" to "Search"

Both of our current meta-tag related modules are currently using this menu item as their parent. Although this can be changed in those modules, it's make a new issue for those modules. Where should their homes be after this change?

https://github.com/backdrop-contrib/base_meta
https://github.com/backdrop-contrib/custom_meta

Overall though, this is a large change compared to some of our other renames. We've only had the code to seriously review for 2 days. I'd like to have further discussions on this issue before we move it into core. So let's postpone this for a later release.

**Comment by docwilmot** [comment]
Agreed

**Comment by mikemccaffrey** [comment]
> URL aliases under Structure seems questionable

I agree with this. URL aliases are stored in the database and are closely bound to the site content. I'd propose that we move the URL aliases under the Content menu instead.

**Comment by jenlampton** [comment]
> URL aliases under Structure seems questionable

This is a question of audience. To anyone who uses a website URLs *are* structure. All the other things we use to create structure (menus, Taxonomy, node types, etc) are almost always reflected in the URLs. 

This is why websites are often built by people building the menu first. 

People also start website projects by creating sitemaps. 

Sure, to core URLs are not important and are just something that is associated with a node. But the user interface is for humans.

**Comment by mikemccaffrey** [comment]
> This is why websites are often built by people building the menu first.

Hmmm.... this actually seems like an argument in favor of moving url aliases out of Structure. Unlike menus, you can't create any aliases until there is content, and we don't want people trying to do that when they start constructing their site.

**Comment by serundeputy** [comment]
I'm not sure reading through this issue that it has come to consensus/decision.  Moving to 1.5; if someone feels it is ready and time permitting it can be moved back to 1.4.

**Comment by klonos** [comment]
For me (especially now with redirects in core), this comment by @jenlampton makes perfect sense from a site-builder PoV:

> Why are those two things even lumped together? Why not a section for search, and one for paths? We could have Aliases, Redirects, etc, all under paths, and Search settings, Solr settings, Facets, all under search.

**Comment by jenlampton** [comment]
Food for thought: I've been spending a lot of time in Drupal 6 (working on upgrading to Backdrop, of course) and what made that top-level menu more intuitive than Drupal 7's was the mystery menu named "Site building". Yes, that name didn't really mean anything to anyone, but all the important things you needed to build your site lived in there: Blocks, Menus, Image styles, URL aliases, Panels, Views. Not all of these things are structural! And, some of the more structural things (like taxonomy) lived under content (which makes more sense, imho).

Why do I find D6 more intuitive than what we have in D7/BD?  Well, all the things that just had simple settings-forms were under configuration (okay, except for maybe input formats). All the interfaces under site building were for creating and managing other things (blocks, menus, views, etc). 

Maybe this wasn't as beneficial to new users because it was harder to know where to go to find something for the first time, but it became clear with use which place you would go to do what.

I'm not sure what this means for Backdrop, only that I think we should re-examine the menu all over again in Backdrop 2.x (and I wanted to post that thought here for when we get back to it)

Since we can't get consensus on structure, I'm now proposing we split `Search and metadata` into two: `Search` and `URL handling` for Backdrop 1.x.

**Comment by quicksketch** [comment]
I don't know about this PR. This reworks the menu fairly substantially and in a way that would affect contrib modules. A module like Metatags will end up having "free floating" menu items when their parents are removed, resulting in the menu item being relocated under its first still-existing parent in the menu. e.g. Admin > Structure > Search and Metadata > Metatags would end up at Admin > Structure > Metatags, dropping the now-missing menu item. This would happen for any module that had been using the previous location.

This shift plus the rather large amount of cruft we obtain maintaining all the redirects makes me feel this splitting of one menu item into 3 isn't providing a good cost-to-reward ratio.

**Comment by quicksketch** [comment]
In any case, tests are not currently passing, so moving this back to needs work.

**Comment by jenlampton** [comment]
yeah, this was a time-is-of-the-essence issue back when it started because there wasn't any contrib to be affected yet. The more time goes on, the more likely this should be punted to 2.x. I'd say let's push the tag if we release 1.5 without it.

**Comment by quicksketch** [comment]
Let's move to 1.6.0. The recent addition of the deprecated watchdog notices also adds a handy `backdrop_goto_deprecated()` that we should start using in this PR to handle future redirects of deprecated menu paths.

**Comment by jenlampton** [comment]
Sounds good to me 👍

**Comment by jenlampton** [comment]
I rebased and pushed a new PR that now uses backdrop_goto_deprecated() everywhere in core where it should be used, as well as addresses feedback left on the PR.  If this doesn't get in for 1.6 we will need to push to 2.x.

**Comment by klonos** [comment]
I would like to see this fixed in the 1.x cycle (especially since we haven't set any even vague date for 2.x, which sounds so Drupally - in a bad way) and @jenlampton's proposal seems very reasonable to me (sorry I never commented here before):

> Since we can't get consensus on moving anything into structure, I'm now proposing we simply split `Search and metadata` into two: `Search` and `URL handling` for Backdrop 1.x. and add a third `Metadata` category (which will go unused in core, much like Workflow and User interface) but it will be there when contrib needs it.

...but unfortunately, the PR WSODs on me and tests still don't pass.

**Comment by olafgrabienski** [comment]
Same here: I like the split approach, but the latest PR website doesn't work at all, I got a Chrome error message.

**Comment by jenlampton** [comment]
Sorry guys, I must have really messed up the PR with my last rebase :)

**Comment by jenlampton** [comment]
Well, the code is still working fine on my local. I think it was just the PR that got muddied somehow, so I've closed it and opened a new one: https://github.com/backdrop/backdrop/pull/1673 Let's give this a shot :)

**Comment by olafgrabienski** [comment]
Great! With *URL handling* visible immediatly, the configuration menu is much better:

![screen-backdrop-menu-config-split-search-url](https://cloud.githubusercontent.com/assets/14188307/21276932/07b955c8-c3d4-11e6-9002-60c58fa2c07d.png)

**Comment by findlabnet** [comment]
So, where is correct placeholder for metadata-related contribs?
Seems wrong under "Search" (without "metadata").

**Comment by jenlampton** [comment]
@findlabnet there is a menu item called "Metadata" in this PR too.  There's just nothing in core that uses it so it won't appear until you have a contrib solution that needs it (just like User Interface).

**Comment by findlabnet** [comment]
@jenlampton thanks, found it. So, such modules must check Backdrop version and then route their menu?

**Comment by jenlampton** [comment]
Yes, but the old paths are still there, just marked deprecated, so even if a module used the old paths it would still "work" until Backdrop 2.

**Comment by klonos** [comment]
The PR looks good to me (minus a tiny nit for which I left a comment on the PR itself).

**Comment by jenlampton** [comment]
@klonos I don't see a comment on the PR? Are you maybe still in the middle of it?

**Comment by klonos** [comment]
Oh, it's not a regular comment. It's one of these new, "start a review" thingies I guess. It's for line https://github.com/backdrop/backdrop/pull/1673#discussion-diff-92915170R94 that should be "Generate URL aliases" instead of "Generate aliases".

**Comment by klonos** [comment]
...it's actually called "review comment" 😄

**Comment by jenlampton** [comment]
Yeah, whatever that is I can't see it yet.  Are you sure you finished your review? Sometimes I forget to hit the "complete review" button (or whatever it says) when I'm doing the fancy-new comments instead of the old comments (and most of the time, I find myself using the old comments because I can't remember how to work the new ones anwyay)

**Comment by jenlampton** [comment]
I did a find/replace on three instances of "Generate aliases" and pushed a new PR.  thanks for catching that! :)

**Comment by klonos** [comment]
>and most of the time, I find myself using the old comments because I can't remember how to work the new ones anwyay

That's what I do usually as well. This time it was an accidental click on the default, green submit button :/

You were right about not having finalized the review.  hadn't realized that it is a multi-step process with the new review-comments. Not important now 😄  ...carry on.

**Comment by klonos** [comment]
No further comments on the PR 👍

**Comment by quicksketch** [comment]
I think the current PR looks great, but it is failing a few tests related to URL patterns. The only thing I'd like to adust is the description given for the new "URL handling" and "Metadata" menu items. Right now they simply restate the heading: "Settings related to URLs." and "Settings related to metadata." Elaborating these descriptions and fixing the tests, I think we can get this into 1.6.0.

**Comment by jenlampton** [comment]
Fixed all the failing tests and elaborated in descriptions.

**Comment by quicksketch** [comment]
Thanks everyone for the testing and @jenlampton for the PR. I've merged https://github.com/backdrop/backdrop/pull/1673 into 1.x for 1.6.0.
