### ISSUE TITLE
The Testing module implements a hook that is not invoked by Backdrop

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#6350]
[`simpletest_registry_files_alter()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21simpletest%21simpletest.module/function/simpletest_registry_files_alter/1) is a `hook_registry_files_alter()` implementation Backdrop core does not invoke anymore, since the class registry and its hooks has been replaced by `hook_autoload_info()` and `hook_autoload_info_alter()`.

`simpletest_registry_files_alter()` is supposed to add test files for disabled modules. If that is necessary, a different hook must be used; otherwise, that function can simply be removed.

**Comment by kiamlaluno** [comment]
The only failure is caused by the `layout_load_multiple_by_path()` function which is not found.

**Comment by herbdool** [comment]
@kiamlaluno while you're at it, can you also update the comment for `simpletest_test_get_all()`? It also mentions that same missing hook.

**Comment by kiamlaluno** [comment]
I also updated the PR as per the recent commits.

**Comment by quicksketch** [comment]
Excellent, thank you @kiamlaluno and @herbdool! Merged https://github.com/backdrop/backdrop/pull/4624 into 1.x and 1.27.x.
