### ISSUE TITLE
Rename "cketoolbar" config key to just "toolbar"

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6352]
Follow up to https://github.com/backdrop/backdrop-issues/issues/4122.

In the CKEditor Contrib module, we renamed the config key used by CKEditor 5 within text format settings from "cketoolbar" to just "toolbar" in issue https://github.com/backdrop-contrib/ckeditor5/issues/113. This was to work around a core bug that was fixed in Backdrop 1.26.3.

We should make this change in core as well now that we no longer have to work-around the core bug from https://github.com/backdrop/backdrop-issues/issues/6203.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4625 that ports the change from the contrib module.

**Comment by quicksketch** [comment]
I updated my PR at https://github.com/backdrop/backdrop/pull/4625 based on @indigoxela's feedback (thank you!).

**Comment by indigoxela** [comment]
@quicksketch many thanks for the update, this works properly now. :+1:

**Comment by quicksketch** [comment]
Thanks @indigoxela! We didn't get this into `1.27.0-preview` but it will be in the final release.
