### ISSUE TITLE
Creating menu items can trigger resource-intensive rebuilding module and field data when it's not needed

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6353]
## Description of the need

When adding a menu item or adding a basic page with the default setting of adding a menu item, it can cause `admin_bar_links_alert()` to be called, and thus also trigger `system_rebuild_module_data()` which scans all module data and also triggers `field_read_fields()`. The reason this is a problem is that it can be resource intensive. `field_read_fields()` is the uncached version of fetching all field info and should normally only be used when reading/adding/editing field config (or when looking at the status page).

https://github.com/backdrop/backdrop-issues/issues/5464 introduced triggering `system_rebuild_module_data()` when calling `system_requirements` in order to display duplicate modules. But there's no reason this should have to run for every menu item added or removed. This is also unexpectedly impacting https://github.com/backdrop/backdrop-issues/issues/6208 which should also not need to be run for every menu item added/removed.

Note that the user needs to have `administer site configuration` in order for this all to get called, so the impact is limited to just those users.

## Proposed solution

Even though the admin bar gets cached in cache_menu, it still seems to be rebuilt for every new menu item regardless of which menu it is put into. I can see that `system_requirements` and also calling `system_rebuild_module_data()` is still useful, especially on the status page. But perhaps the status alert also needs to be cached and only have the cache cleared on a cronjob, manual cache clear or changing fields, modules, etc.

## Alternatives that have been considered

Or perhaps there's a way to just avoid rebuilding the admin bar cache when menu items are created in other menus (not the management menu)?

**Comment by herbdool** [comment]
I ended up changing it so that admin bar is only flushed if the menu link is part of the management menu. That seems reasonable. If we can't restrict that, then I propose adding a separate cache for the alert. But that cache is probably not needed if this does the job.

**Comment by quicksketch** [comment]
I tested the PR manually and confirmed that adding a menu item under the `management` menu immediately shows up as before. Also creating a content type has the menu item immediately show up under Content > Add Content > [type]. This looks good to me.

**Comment by herbdool** [comment]
Thanks @quicksketch

**Comment by herbdool** [comment]
Merged into 1.x and 1.26.x.
