### ISSUE TITLE
CKEditor 5 unable to paste into edit window with "Basic" formatting options

### ISSUE THREAD

**Issue by izmeez** [backdrop/backdrop-issues#6357]
## Description of the bug

Using backdrop 1.27.0 preview with fresh install. Edit content such as about page. Copy some text from another app or browser tab or window and attempt to paste that content into the ckeditor 5 window. Nothing appears with either Ctrl-V or GUI context menu item: Paste.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: Backdrop 1.27.0 preview
- Web server and its version: Laragon
- PHP version: 8.1.10
- Database sever (MySQL or MariaDB?) and its version: 8.0.30
- Operating System and its version: Windows10
- Browser(s) and their versions: Firefox

**Comment by argiepiano** [comment]
I'm not able to reproduce - pasting is working fine, and it includes rich text as allowed. Backdrop 1.27.0-preview, CKE5, PHP 8.1.13.

**Comment by stpaultim** [comment]
I spun up a test site with the preview release, using the Tugboat option on BackdropCMS.org - https://backdropcms.org/try-backdrop/dev

I edited the about page and easily pasted conent in from another document. 

I also installed the preview release on a dev site that we are currently upgrading from Drupal 7. I then upgraded from CKEditor 4 to 5 and am able to cut and paste content into there as well. 

@izmeez Any additional information to help us recreate the problem. Have you tried it on a different computer or with a different browser. Could it be OS or browser related?

**Comment by kiamlaluno** [comment]
I use Firefox as browser, but I was able to edit https://master-qjwnbhjyafnuvhuqfuurctyqvkibjoer.tugboatqa.com/about and copy-paste text from two different sites. I was also be able to copy text from https://ckeditor.com/docs/ckeditor5/latest/examples/builds-custom/full-featured-editor.html to https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-plain-text.html.

**Comment by indigoxela** [comment]
@izmeez can you provide two things here to help us narrowing it down?

- A screenshot of your editor with toolbar
- The export of your basic text format (see description below)

- Go to /admin/config/development/configuration/single/export
- Select "Text formats"
- Then "Basic"

Copy that json content, and post here, wrapped in `<pre>` and `</pre>`.
