### ISSUE TITLE
Correct the documentation for system_configure_date_formats_form()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6358]
The documentation for [`system_configure_date_formats_form()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.admin.inc/function/system_configure_date_formats_form/1) says that the last parameter is a string. That is not true: it is an array returned by [`system_date_format_load()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.module/function/system_date_format_load/1).

In fact, given the definition for the *admin/config/regional/date-time/formats/%system_date_format* route, Backdrop will first call `system_date_format_load()` with the date format name, and then pass the returned value to `backdrop_get_form()` which then passes it to `system_configure_date_formats_form()`.

```php
  $items['admin/config/regional/date-time/formats/%system_date_format'] = array(
    'title' => 'Edit date format',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('system_configure_date_formats_form', 5),
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
  );
```

`system_configure_date_formats_form()` can also return `FALSE`, but that value is never passed to page callbacks. (For what I recall, if an auto-loader returns `FALSE`, Backdrop returns a 404 error.)

The documentation for `system_configure_date_formats_form()` must be corrected to say that `$format` is an array.

**Comment by kiamlaluno** [comment]
I consider this a task, but somebody could consider this a bug in the documentation.

**Comment by kiamlaluno** [comment]
I changed the type hint from `string` to `array|null`, as other documentation pages (for example [`field_bundle_settings()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21field%21field.module/function/field_bundle_settings/1)) use a similar type hint for nullable parameters.

**Comment by herbdool** [comment]
Thanks @kiamlaluno this looks correct.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno and @herbdool for working on these documentation fixes! I merged https://github.com/backdrop/backdrop/pull/4629 into 1.x and 1.26.x.
