### ISSUE TITLE
"Extend with Modules" page doesn't explain where to install modules

### ISSUE THREAD

**Issue by behindthepage** [backdrop/backdrop-issues#636]
https://backdropcms.org/guide/modules

>Upload the module to your site.
>* Move the extracted files to your web server. You can do this using FTP, but we highly recommend using Git.

This would be better:

>Upload the module to your site.
>* Move the extracted folder into the modules directory in your site root. You can do this using FTP, but we highly recommend using Git.

Or like the theme instructions (but I think this is confusing for noobs)

>Upload the module to your site.
>* FTP/Copy/SCP/Git pull the extracted folder into the modules directory in your site root.

Regards
Geoff

**Comment by BWPanda** [comment]
This is a good suggestion, but it should be posted to the [backdropcms.org issue queue](https://github.com/backdrop-ops/backdropcms.org/issues) instead. Not sure if/how to move this issue there, so just marking as 'documentation' for now.

**Comment by behindthepage** [comment]
Ah thanks @BWPanda I have created it in the .org issues and closed it here.

**Comment by BWPanda** [comment]
For reference: https://github.com/backdrop-ops/backdropcms.org/issues/43
