### ISSUE TITLE
Change the reference to _db_process_field() in the documentation comment for DatabaseSchema_mysql::createFieldSql()

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#6361]
[`DatabaseSchema_mysql::createFieldSql()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21mysql%21schema.inc/class/DatabaseSchema_mysql/1) says:

> Before passing a field out of a schema definition into this function it has to be processed by _db_process_field().

`_db_process_field()` does not exist (nor `db_process_field()`).  
That comment must be referring to [`DatabaseSchema_mysql::processField()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21mysql%21schema.inc/function/DatabaseSchema_mysql%3A%3AprocessField/1) and needs to be corrected.

**Comment by herbdool** [comment]
That appears correct to me. On line 342 it does call `$this->processField()` before passing to `$this->createFieldSql()`.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4631 into 1.x and 1.26.x. Thanks @kiamlaluno and @herbdool!
