### ISSUE TITLE
CKEditor 5 - multivalue textfields break layout

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6364]
## Description of the bug

This was first reported in the contrib module queue with Paragraphs, but the problem's unrelated to that module.

## Steps To Reproduce

1. Add a multivalue text field to a content type
2. Set Text processing to filtered
3. Make sure, Seven is set as theme for content creation
4. Add a node of that type (/node/add/whatever)
5. Paste a longer text into one of the multivalue fields

## Actual behavior

The layout breaks, as the editor's content gets a `white-space: nowrap` from the parent.

## Expected behavior

Guess... :wink: 

## Additional information

- Backdrop CMS version: latest dev or 1.27 preview

@laryn discovered the CSS line causing this: https://github.com/backdrop-contrib/ckeditor5/issues/125#issuecomment-1889609592

We can't remove that line, it would break other stuff, but we can narrow it down, so it doesn't apply to the editor's div, I guess.

The line causing the problem: https://github.com/backdrop/backdrop/blob/1.x/core/modules/system/css/system.theme.css#L95

**Comment by indigoxela** [comment]
A simple...
```
.ck-editor {
  white-space: normal;
}
```
... should do the trick. Didn't dig any deeper, yet.

**Comment by laryn** [comment]
Adding a PR for testing here.

**Comment by indigoxela** [comment]
@laryn many thanks for providing this quick fix. I can confirm that text fields with large content no longer break layouts in Seven. :+1: Works for me.

Not sure about the file this fix got added. In theory it belongs to core/modules/ckeditor5/css, as this is only relevant for CKEditor 5. It doesn't do any harm in core/modules/system/css/system.theme.css, though.

**Comment by herbdool** [comment]
I agree, put it in ckeditor5.css and it looks ready to merge.

**Comment by laryn** [comment]
Thanks @indigoxela and @herbdool.
PR has been updated.

**Comment by indigoxela** [comment]
@laryn wow, that was quick. Tested locally, as the tubgoats are getting wet again (Tugboat sandbox 503).

Works as expected. And the file makes more sense now. :+1:

**Comment by laryn** [comment]
@indigoxela This may not be solely related to CKEditor 5 -- I just looked at [this issue](https://github.com/backdrop-contrib/paragraphs/issues/163) and have been able to replicate it on a multi-value core non-filtered-text field with a long description.

Adding this in `system.theme.css` right after the offending section solves both cases. Does that seem appropriate?

```
.field-multiple-table tr.odd .form-item,
.field-multiple-table tr.even .form-item {
  white-space: normal;
}
```

**Comment by yorkshire-pudding** [comment]
@laryn asked me to test the fix above with the paragraph issue and I confirm it works. Added a PR here as also requested by Laryn but happy to remove if that is not what is wanted.

**Comment by laryn** [comment]
Yes, I was hesitant to lose the RTBC but I am also hesitant to playing whack-a-mole and peppering core CSS with the same fix in multiple places... Thank you @yorkshire-pudding for verifying that fix works for both. How about converting your issue in Paragraphs to a core issue, linking to this one, and suggesting that we remove the CKE5-specific fix and replace it with the new one, for separate discussion?

**Comment by herbdool** [comment]
@laryn with the follow-up you can move the fix from here to the new location, if indeed that makes sense to have a more generic fix for Seven.

**Comment by herbdool** [comment]
I've only been able to recreate the bug here when using ckeditor 5. At least, when trying to paste long text into the editor. So for now, this fix looks good.

**Comment by quicksketch** [comment]
Thanks folks! I added a code comment to https://github.com/backdrop/backdrop/pull/4632 and merged it. This will be in 1.27.0.
