### ISSUE TITLE
CKEditor 5 - can not open image dialog if image filters are disabled

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6366]
## Description of the bug

Here we go, another problematic settings constellation...

## Steps To Reproduce

First clean up the format, to start fresh.

1. Disable CKEditor 5
2. Save format
3. Open form and add back the editor
4. Make sure, the image icon is part of the toolbar (it is by default)
5. Make sure these two filters are disabled: "Float images ...", "Convert image captions..." :point_left: 
6. Add a new node (node/add/post)
7. Click on the image icon in the toolbar

## Actual behavior

Nothing happens, the dialog won't open.

In the console log there's an error:
```
Uncaught CKEditorError: plugincollection-plugin-not-loaded {"plugin":"ImageCaptionUtils"}
```

## Expected behavior

Inserting images should also work, if the caption filter isn't enabled.
Then the dialog also shouldn't show the caption checkbox.
Most of all, the dialog should open. :wink: 

## Additional information

The whole dependency handling still seems a bit fragile. I know, that's more complex in v5...

**Comment by herbdool** [comment]
Added a PR. Takes the easy way out by adding `ImageCaption` dependency to `BackdropImage` plugin. There must be something requiring caption, but not the image alignment. I didn't look too deep, but took a similar approach to https://github.com/backdrop/backdrop-issues/issues/6359 issue.
