### ISSUE TITLE
[UX] Add 'Edit' links for each enabled layout in Admin Bar.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#637]
Just like views has edit links for each view. Most of the time I go the the Layout menu it is to modify an exisiting layout.

**Comment by klonos** [comment]
...and I'd like to propose to also add a "Edit current layout" top-level link (directly under Structure >> Layouts).

**Comment by docwilmot** [comment]
Can we do this please? Working with layouts is tedious without this.

**Comment by quicksketch** [comment]
> ...and I'd like to propose to also add a "Edit current layout" top-level link (directly under Structure >> Layouts).

I thought about adding this as a contextual link (similar to when a view is the main content of the current page), but I it wasn't included in the initial pass of Layouts. For now what I usually end up doing is editing any block on the page and then closing the popup to get to the Layout. Not ideal I know. I think we should handle "Edit current layout" as a separate issue, as there are a couple ways of handling it.

I think the current proposition, adding links for each layout to the admin bar, makes sense if we're going to keep that functionality for Views as well (right now it seems that way). So let's be consistent and do the same thing for Layouts.

**Comment by quicksketch** [comment]
Well done @docwilmot! Merged https://github.com/backdrop/backdrop/issues/903 into 1.x and 1.1.x!
