### ISSUE TITLE
DatabaseConnection_mysql::$utf8mb4Supported is never initialized

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#6370]
[`DatabaseConnection_mysql::utf8mb4IsSupported()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21mysql%21database.inc/function/DatabaseConnection_mysql%3A%3Autf8mb4IsSupported/1) uses a property ([`$utf8mb4Supported`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21mysql%21database.inc/property/DatabaseConnection_mysql%3A%3Autf8mb4Supported/1)) to avoid running the `CREATE TABLE {backdrop_utf8mb4_test} (id VARCHAR(255), PRIMARY KEY(id(255))) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ROW_FORMAT=DYNAMIC ENGINE=INNODB` query more than once, but that property is never initialized (and the query will be always executed when `DatabaseConnection_mysql::utf8mb4IsSupported()` is called).

`DatabaseConnection_mysql::utf8mb4IsSupported()` must be changed to set that property to `FALSE` (when an exception is caught) or `TRUE`.

**Comment by herbdool** [comment]
This makes sense to me.

**Comment by quicksketch** [comment]
Nice catch on this oversight @kiamlaluno! I don't know how many times this method gets called within a single request, but it's clear that the intention was to set the property only once per request.

I merged https://github.com/backdrop/backdrop/pull/4637 into 1.x and 1.27.x. Thanks @kiamlaluno and @herbdool!
