### ISSUE TITLE
Should dashboard_login_redirect be 1 or true?

### ISSUE THREAD

**Issue by izmeez** [backdrop/backdrop-issues#6381]
## Description of the bug

Backdrop default dashboard settings at `admin/dashboard/settings` has redirect administrator to dashboard checked. If this is unchecked and saved, then checked again and saved, the config dashboard.settings.json value for `dashboard_login_redirect` changes from `true` to `1` like so: 

```quote
--- a/config/active/dashboard.settings.json
+++ b/config/active/dashboard.settings.json
@@ -1,5 +1,5 @@
 {
     "_config_name": "dashboard.settings",
-    "dashboard_login_redirect": true,
+    "dashboard_login_redirect": 1,
     "news_feed_url": "https://backdropcms.org/api/notifications"
 }
```
What is the preference: boolean or numeric?

**Comment by argiepiano** [comment]
This is not a bug.  It's not uncommon to find booleans in Backdrop's json files stored either as a number `1/0` or as `true/false`. It doesn't make any difference, and it's often the result of the automatic storing the Form API does  when you have a `checkbox` element and you use the key `#config` in the form array.

**Comment by klonos** [comment]
@izmeez sorry, I only bumped into this issue now; I was away when you opened it. I just wanted to point you to these couple of existing issues, since I think they are relevant and could shed some more light into the "mystery": #2557 #2425
