### ISSUE TITLE
CKEditor 5, Basic text format: "Maximize" button missing

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#6382]
## Description of the bug

In the _Basic_ text format, the "Maximize" button in the CKEditor 5 toolbar isn't enabled by default. With CKEditor 4 the button was enabled by default, so it makes sense to do the same with CKE 5.

## Steps To Reproduce

To reproduce the behavior:
1. Create a page.
2. Have a look at the editor toolbar.

## Actual behavior

The Maximize button is missing. To change this, it must be dragged in the "Active toolbar" on the text format configuration page.

## Expected behavior

The button is there out of the box.

**Screenshot with enabled Maximize button:**

<img src="https://github.com/backdrop/backdrop-issues/assets/14188307/e333e997-43e6-4a01-9f5b-a79bdaadfedf" width="500">

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.27.0

**Comment by quicksketch** [comment]
Looking through CKEditor 5 items, this seems like a relatively easy one to fix.

**Comment by quicksketch** [comment]
I think that's because the standard profile uses the defaults provided by CKEditor 5 rather than a specific config file. The default toolbar seems to be defined in `ckeditor5_editor_info()`

**Comment by olafgrabienski** [comment]
Thanks for the hint, @quicksketch! I've filed a [pull request](https://github.com/backdrop/backdrop/pull/4937). Tests are passing, and it looks good to me in the sandbox.

**Comment by quicksketch** [comment]
Looks good to me. Trivial change and works as expected.

I don't have a strong preference for this being a bug fix release or minor release. The _intention_ was to include the Maximize button by default when CKEditor 5 was introduced, but now it's been a year with it not being included by default.

**Comment by olafgrabienski** [comment]
I also don't have a strong preference - whatever seems appropriate to you or other core commiters.

**Comment by quicksketch** [comment]
I've merged into 1.x only for now, so this will be in 1.30.0. There's probably only a few weeks difference between 1.29.3 and 1.30.0 anyway.
