### ISSUE TITLE
Fixed: Adding a link on image with a caption removes the alignment on the <figure> tag.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6384]
## Description of the bug

Putting a link on an image with a caption will remove the alignment on the figure tag.

## Steps To Reproduce

To reproduce the behavior:
1. Add an image and caption and choose an alignment.
2. Click on the image and add a link
3. Save.

## Actual behavior

Using captions:

* No link: `<figure class="caption caption-img align-left">`.
* With link: `<figure class="caption caption-a">`

With no captions, no changes:

* No link: `<img ... class="align-left">`
* With link: `<img ... class="align-left">`

## Expected behavior

I figure the tag should look like: `<figure class="caption caption-img align-left caption-a">`.

## Additional information

Backdrop 1.27.0

**Comment by indigoxela** [comment]
@herbdool as we currently have two WYSIWYG editors in core, it's important to note, which one causes the problem. CKE4 doesn't CKE5 does that.

And it's not the filter (on rendering the output), but apparently the downcast conversion, which means, the "reformat warning" is triggered, when opening content previously created with CKE4.

**Comment by olafgrabienski** [comment]
> This order works:
> 
> 1. Float images left and right using the data-align attribute
> 2. Convert image captions to figure and figcaption elements

This seems to be the default filter order in the Basic format. However, it doesn't work for me. With this order (and CKEditor 5), I get the same result as mentioned in the issue description: `<figure class="caption caption-a">`

**Comment by olafgrabienski** [comment]
> This seems to be the default filter order in the Basic format.

Oh, that's actually not true. On my test site, the _Convert image captions_ filter was shown below the _Float images_ filter, but both had a weight of `4`. So, I changed the weight of _Convert image captions_ to `5`, and then the alignment worked as expected.

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop/backdrop/pull/4647) is available for testing and review.

How to test:

- Create content with some text and an image
- Add a **caption and a link** to the image
- Save the node and view the rendered result
- Now go to admin/config/content/formats/filtered_html and switch the order of "Convert image captions..." and "Float images..." filters
- Flush caches!
- Inspect your content again - the image should still be floated

Flushing caches is very important, after you change the filter order, otherwise you see outdated rendered content.

The editor doesn't matter, as the bug is in function _filter_image_align(), which doesn't consider nesting in case the filter function _filter_image_caption() has run before it and the image is wrapped in a link.

**Comment by olafgrabienski** [comment]
I've tested the PR as suggested in the sandbox. Image floating worked both from the beginning and after reordering the filters several times (including flushing caches and editing / saving the page in question).

Side note: I tested with CKEditor 5. After saving a linked image with caption and editing the page again, I got the message that activiating CKE 5 "will reformat the content of this field". And indeed: after activating CKE 5, the link for the image was also added to the caption. Before, only the image was linked, and the caption was rendered as normal text without a link.

**Comment by indigoxela** [comment]
@olafgrabienski many thanks for testing :pray: 

> Side note ... after activating CKE 5, the link for the image was also added to the caption

That's a known issue with CKE5, unrelated to filters: #6354

**Comment by herbdool** [comment]
Thanks for the PR @indigoxela and testing @olafgrabienski. RTBC.

**Comment by quicksketch** [comment]
Thanks @indigoxela, @herbdool, and @olafgrabienski! Nice sleuthing and fix. I've merged https://github.com/backdrop/backdrop/pull/4647 into 1.x and 1.27.x. Thank you!
