### ISSUE TITLE
custom block config json content has extra characters

### ISSUE THREAD

**Issue by izmeez** [backdrop/backdrop-issues#6391]
I'm going to start this as a bug report. Please redirect as suited.

## Description of the bug

In custom block config json files the content includes unexpected characters `\r\n` often preceding `<p>`.

Are these necessary or should they be eliminated?

## Steps To Reproduce

1. In the GUI, create and save a custom block with some content text of more than one line.
2. View the resulting config file `block.custom.name_of_block.json`

**Comment by indigoxela** [comment]
> config json files the content includes unexpected characters \r\n

That's how newlines are supposed to get handled in JSON. They have to get escaped.

You can play with that if you have the devel module installed:

```
$s = "A string with a
newline
and yet another one";

dpm($s);

$e = json_encode($s);

dpm($e);

$n = json_decode($e);

dpm($n);
```

Backdrop uses the default PHP functions json_encode and json_decode for that.
