### ISSUE TITLE
Introduce new "View own published content"

### ISSUE THREAD

**Issue by alanmels** [backdrop/backdrop-issues#6397]
## Description of the need

While there is a "View own unpublished content" permission, a permission that would make perfect sense "View own published content" does not exist.

We have to give the "View published content" permission to users that affect ALL content and then use contributed modules to limit permissions to certain nodes. In other words the core acts very much permissive providing (or very much prohibitive by not providing to any) access to ALL content on a Backdrop website. Wouldn't be much more convenient if the core was able to give access to only own nodes without any contributed modules?

![Screenshot 2024-02-06 at 12 46 33 AM](https://github.com/backdrop/backdrop-issues/assets/56604405/64d2d172-84f3-49ff-8ed4-6533b5c7227d)
![Screenshot 2024-02-06 at 12 46 49 AM](https://github.com/backdrop/backdrop-issues/assets/56604405/8fc44c8c-f63c-497b-9bdc-7e57d0e2980f)

**Comment by jenlampton** [comment]
Unfortunately adding access control to the "view" operation has considerable performance implications, and could need careful consideration of cache invalidation.

**Comment by alanmels** [comment]
Didn't know. In that case I would be the first person to be against the idea, as I'm all for only improving performance.
