### ISSUE TITLE
Full config import shows no new layouts

### ISSUE THREAD

**Issue by sirkitree** [backdrop/backdrop-issues#640]
Semi-related to https://github.com/backdrop/backdrop-issues/issues/628

When doing a full config import, none of my new layouts showed up, even after clearing cache. I see json files in the full export file but they're not showing up at `admin/structure/layouts`. Re-importing the same full export says the system matches.

I then tried importing a single layout which gave me the a successful message, and upon checking `admin/structure/layouts` found all the missing layouts present.

**Comment by sirkitree** [comment]
> Interesting. I bet that we don't have Layout module registered to clear its own caches on hook_flush_caches(). Yes, let's please make a new issue for that one, it's probably not directly related to config import/export.
– @quicksketch

**Comment by quicksketch** [comment]
> When doing a full config import, none of my new layouts showed up, even after clearing cache. I see json files in the full export file but they're not showing up at admin/structure/layouts.

In trying to test this I'm getting slightly different results. My layouts show up immediately in admin/structure/layouts, but if I try to visit a path created by a layout, I get a page not found. Rebuilding the menu after the import solves the problem.

I checked that Layout module is flushing it's caches by returning a value in layout_flush_caches(), so my initial guess was off. We might just not being doing an adequate cache flush after a full site import.

**Comment by quicksketch** [comment]
This problem seems to no longer exist in the current version of Backdrop. It may have been related to https://github.com/backdrop/backdrop-issues/issues/787, where config imports would bail half-way on the first import between two environments.

Please reopen if this issue is still happening in the latest dev.
