### ISSUE TITLE
[UX] Add "Translate" link to contextual content links

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#6410]
## Description of the need

When referenced content items are displayed on a page as "Rendered entity", single items can be _edited_ and _deleted_ using its contextual links. On multilingual sites, I would expect there also a contextual link to _translate_ an item. Without such a link, the translation workflow is quite complicated.

## Proposed solution

For content types with enabled translation, add a "Translate" link in the contextual links of referenced or otherwise embedded nodes (e.g. a view with content teasers). The path should be `node/NID/translate` (or `node/NID-REFERENCED/translate?destination=node/REFERENCING-NID`).

## Alternatives that have been considered

A custom or contrib module could provide such a link. In my opinion, it makes however sense to have the feature in Backdrop core. (Drupal 8+ does so, by the way.)

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes contextual links to improve the content translation workflow.

**Comment by argiepiano** [comment]
@olafgrabienski here you go, PR https://github.com/backdrop/backdrop/pull/4662

Adding contextual links is very simple - just a one-line change! Gotta love Backdrop!

**Comment by olafgrabienski** [comment]
Thanks a lot for the PR @argiepiano, how wonderful! I've tested the PR in the sandbox site: It works as expected on a page with referenced content, and it works also in the Views block of promoted content on the home page.

Screenshot:

<img src="https://github.com/backdrop/backdrop-issues/assets/14188307/0847b729-6cd5-43c7-9b1d-ebc9d8cb78a2" width="712">

**Comment by olafgrabienski** [comment]
I've added `[UX]` to the issue title, for user-experience improvement. As such, it can be part of a bugfix release, so I'm adding the `milestone candidate - bug` label as well.

**Comment by indigoxela** [comment]
Cool, I wasn't even aware of that 'context' key.

RTBC :+1:

**Comment by olafgrabienski** [comment]
Many thanks for reviewing! Adding the bugfix release milestone.

(I see, there is one failing test. A typical 'not related' one?)

**Comment by quicksketch** [comment]
Nice tiny little change here! I merged https://github.com/backdrop/backdrop/pull/4662 into 1.x and 1.27.x. Thanks @argiepiano, @olafgrabienski, and @indigoxela!
