### ISSUE TITLE
Remove the call to node_type_set_defaults() done right before calling node_type_save()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6413]
Some functions call [`node_type_set_defaults()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_type_set_defaults/1) right before calling [`node_type_save()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/node_type_save/1), but that is not necessary, since `node_type_set_defaults()` is the first function `node_type_save()` calls.

```php
$type = node_type_set_defaults($info);
$type_data = (array) $type;
$type_data['has_title'] = (bool) $type_data['has_title'];
$type_data['modified'] = (bool) $type_data['modified'];
$type_data['disabled'] = (bool) $type_data['disabled'];
```

This happens in [`standard_install()`](https://docs.backdropcms.org/api/backdrop/core%21profiles%21standard%21standard.install/function/standard_install/1) and [`_book_install_type_create()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21book%21book.install/function/_book_install_type_create/1).

The call to `node_type_set_defaults()` can be removed, in those cases.

**Comment by kiamlaluno** [comment]
The failing tests are the usual `testLayoutUpgrade()` ones.

**Comment by kiamlaluno** [comment]
I would consider it a bug, since it invokes hooks twice in row when they should be invoked once.  
Fortunately, `hook_node_type()` implementations do not usually write data in the database. (Differently, invoking them twice with `$new_type->is_new` set to `TRUE` would probably cause database errors.)

**Comment by herbdool** [comment]
This looks good to me.

**Comment by quicksketch** [comment]
Thank you @avpaderno for the correction and @herbdool for reviewing this! I merged https://github.com/backdrop/backdrop/pull/4664 into 1.x and 1.29.x.
