### ISSUE TITLE
Nonexistent HTML5Shiv library still being added

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6419]
## Description of the bug

Follow-up to https://github.com/backdrop/backdrop/pull/4611 where we removed `html5shiv` -- we left an attempt to add the library that no longer exists.

https://github.com/backdrop/backdrop/blob/134398376e67399c0eff1576a83859a76f934056/core/includes/common.inc#L4705

**Comment by herbdool** [comment]
Good catch!

**Comment by quicksketch** [comment]
Thanks @laryn and @herbdool! Committed https://github.com/backdrop/backdrop/pull/4670 to 1.x and 1.27.x.
