### ISSUE TITLE
[Security] Fixed: Strengthen one-time login links.

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6420]
This will address two Drupal 7 improvements:

* Changing email address should invalidate one-time login links
* Increase entropy in the one-time login links (especially in the cases where there's an empty password in the database, if a site uses SSO).

In https://www.drupal.org/project/drupal/issues/3306390:

> Problem/Motivation
> Assume I change email provider or leave a job. I or an attacker requests a password reset link.
> 
> I now change the email address on my drupal account, which I've been logged into on my home computer
> 
> My former employer or someone with access to my old email account can use the pre-existing one-time login link to gain access to my account (or the whole site if I'm an admin).
> 
> Proposed resolution
> Invalidate one-time login links if the email address is changed. The easiest fix is to include the current email address as part of the data in user_pass_rehash

From Drupal 7.100: https://www.drupal.org/node/3409960, https://www.drupal.org/node/3409043 (backport from Drupal 10):

>The problem is that there is significantly less entropy in the inputs to user_pass_rehash() if the user has an empty password field in the database.
>
>Users may have empty passwords if - for example - a site uses a Single Sign On integration to offload authentication.
>
>Improvements could be made to the implementation to reduce the likelihood that an attacker could brute force e.g. a password reset URL if the user has no password stored in Drupal.
>
>It may also be advisable for sites / projects that do not use Drupal's passwords for authentication to avoid leaving the password field empty in the database, but that can be looked at in a (public) follow-up. It wouldn't help much to set the password field to the same value for all users.

**Comment by herbdool** [comment]
Looks like it requires this commit as well: https://git.drupalcode.org/project/drupal/-/commit/67a7e9e74e3838e9c60ef52d203255b142bc26e7 from https://www.drupal.org/i/3306390

**Comment by quicksketch** [comment]
This looks great @herbdool!

**Comment by stpaultim** [comment]
Any clear guidance on testing this issue? 

Does this make UI changes or is a background thing?

**Comment by klonos** [comment]
The respective Drupal issues are either bugs or tasks, so not sure that this is a new feature request. It does need a change record though (same as the one released for D7.100: https://www.drupal.org/node/3409960), so OK if only targeted for 1.28.0 I guess.

**Comment by quicksketch** [comment]
I don't see a good reason why this would need to be in a minor release. As a security-hardening, I think this should be allowed in any bug-fix release as well.

**Comment by jenlampton** [comment]
Code looks good to me, still needs manual testing. (Failed to test on the sandbox since it won't sent pw reset emails --- needs local testing)

**Comment by quicksketch** [comment]
I verified this does not affect existing password-reset tokens or `bee uli`, both of which call `user_pass_reset_url()` (which then in turn calls `user_pass_rehash()`, the changed function). And this PR includes a safety fallback even if `$user_mail` is not provided, it automatically loads it based on the user name.

This all looks good to me!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4673 into 1.x and 1.27.x. Thanks @herbdool, @stpaultim, and @jenlampton!

**Comment by klonos** [comment]
Reopening this in order to create a change record. Assigning it to me as well. I'll prepare a draft soon as I get a chance.

**Comment by quicksketch** [comment]
Change record created here: https://docs.backdropcms.org/change-records/user-password-reset-links-strengthened
