### ISSUE TITLE
[D7] Clear the "5 failed login attempts" security message when a user resets their own password (d.o #2880910)

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6425]
From https://www.drupal.org/project/drupal/issues/2880910 (backport from D8 to D7):

> If a user forgets their password and tries to log in 5 times then they get blocked by flood control. They can now use the password reset functionality per email, but once they log out shortly after that they are still blocked when trying to log in again.
> 
> Proposed resolution
> Clear the user specific flood events once they used the password recet functionality so that they are able to normally log in again. Do not clear IP address specific flood events because then an attacker with a valid account could clear flood events for victim user accounts.

https://git.drupalcode.org/project/drupal/-/commit/80cc74478787cf200479623f24fdea2b298ff76d

**Comment by argiepiano** [comment]
This makes a lot of sense to me.

**Comment by herbdool** [comment]
@argiepiano I've got a PR. It's a little bit different from the D7 because of previous changes in Backdrop.

**Comment by stpaultim** [comment]
@herbdool - I followed the steps in the original issue on a default site and recreated the problem. I then tried again with a local site using your PR and the problem was fixed for me. 

Do you think I need to test anything else?

**Comment by herbdool** [comment]
That's it, thanks @stpaultim

**Comment by quicksketch** [comment]
Very nice @herbdool! I merged https://github.com/backdrop/backdrop/pull/4675 into 1.x and 1.28.x. Thank you @stpaultim and @izmeez for reviewing!
