### ISSUE TITLE
Animate the progress bar with CSS transitions

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#643]
I'd love it if our progress bar had CSS transitions added so that the progress bar had a smooth movement, rather than jumping between big gaps each AJAX request. Just try installing Backdrop to see the progress bar in all of it's jumpiness. Also note that the password meter during the installation _does_ include CSS transitions. Let's use the same transition for the progress bar.

**Comment by klonos** [comment]
Yes please!

**Comment by davidhwang** [comment]
Another checkbox in the 'drop IE8 support' column: http://caniuse.com/#feat=css-transitions

**Comment by klonos** [comment]
> Another checkbox in the 'drop IE8 support'

:smile: ...actually, I'm pretty sure this could have a fallback. Dropping IE8 support over an animated progress bar (or any other minor visual "bling") would upset people I'm sure.

**Comment by klonos** [comment]
D8 has implemented it already (at least for the installer):

![d8_animated_progress_bar](https://cloud.githubusercontent.com/assets/2423362/5910683/f11010ba-a610-11e4-8156-fe73c4e5e2d7.gif)

**Comment by wesruv** [comment]
This is done.
