### ISSUE TITLE
PHP 8.x compatibility issue in filter.module

### ISSUE THREAD

**Issue by lourdas** [backdrop/backdrop-issues#6430]
## PHP 8.x compatibility issues

After upgrading a Drupal 7 site to Backdrop 1.27.1 in a PHP 8.1 installation (Linux), I got a few errors.

## Steps To Reproduce

To reproduce the behavior:
1. Clear `Page and else` cache
2. Click on Content on the admin top bar

## Actual behavior

![Screenshot_20240320_201022](https://github.com/backdrop/backdrop-issues/assets/397916/dc7a9f6b-a8f2-47c6-aa31-40c9816035a4)

## Expected behavior

A list of all site content should appear.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.27.1
- Web server and its version: Apache 2.4.58
- PHP version: 8.1.26 (fpm)
- Database sever (MySQL or MariaDB?) and its version: MariaDB 10.6.14
- Operating System and its version: Gentoo Linux
- Browser(s) and their versions: Vivaldi 6.6.3271.48

## Further issues
In filter.module, line 2328, there's a call to `implode()` with only one argument (which is not necessarily an issue, but it'd be more better for the eye if a empty string was passed as a first argument) . I looked at all the core code where a `implode()` call is done and I noticed these additional files:

includes/date.class.inc (line 459)
modules/date/date.theme.inc (line 431)

### Proposed patch for filter.module to fix the error and the call to `implode()`
The following patch fixes the error and the call to `implode()` with one argument.

    --- filter.module.old	2024-03-20 20:24:41.256796654 +0200
    +++ filter.module	2024-03-20 20:22:06.930682032 +0200
    @@ -2286,49 +2286,51 @@
        // no replacements are made.
        $open_tag = '';
    
    -    for ($i = 0; $i < count($chunks); $i++) {
    -      if ($chunk_type == 'text') {
    -        // Only process this text if there are no unclosed $ignore_tags.
    -        if ($open_tag == '') {
    -          // If there is a match, inject a link into this chunk via the callback
    -          // function contained in $task.
    -          $chunks[$i] = preg_replace_callback($pattern, $task, $chunks[$i]);
    -        }
    -        // Text chunk is done, so next chunk must be a tag.
    -        $chunk_type = 'tag';
    -      }
    -      else {
    -        // Only process this tag if there are no unclosed $ignore_tags.
    -        if ($open_tag == '') {
    -          // Check whether this tag is contained in $ignore_tags.
    -          if (preg_match("`<($ignore_tags)(?:\s|>)`i", $chunks[$i], $matches)) {
    -            $open_tag = $matches[1];
    +    if ($chunks) {
    +      for ($i = 0; $i < count($chunks); $i++) {
    +        if ($chunk_type == 'text') {
    +          // Only process this text if there are no unclosed $ignore_tags.
    +          if ($open_tag == '') {
    +            // If there is a match, inject a link into this chunk via the callback
    +            // function contained in $task.
    +            $chunks[$i] = preg_replace_callback($pattern, $task, $chunks[$i]);
              }
    -          // Check whether this tag has a class contained in $ignore_classes.
    -          elseif (preg_match('`<([a-z0-9-]+)\s+[\s\S]*?class=(["\'])([\s\S]*?)\2[\s\S]*?>`i', $chunks[$i], $matches)) {
    -            if (!empty($matches[3])) {
    -              $classes = array_map('trim', explode(' ', $matches[3]));
    -              if (array_intersect($ignore_classes, $classes)) {
    -                $open_tag = $matches[1];
    +          // Text chunk is done, so next chunk must be a tag.
    +          $chunk_type = 'tag';
    +        }
    +        else {
    +          // Only process this tag if there are no unclosed $ignore_tags.
    +          if ($open_tag == '') {
    +            // Check whether this tag is contained in $ignore_tags.
    +            if (preg_match("`<($ignore_tags)(?:\s|>)`i", $chunks[$i], $matches)) {
    +              $open_tag = $matches[1];
    +            }
    +            // Check whether this tag has a class contained in $ignore_classes.
    +            elseif (preg_match('`<([a-z0-9-]+)\s+[\s\S]*?class=(["\'])([\s\S]*?)\2[\s\S]*?>`i', $chunks[$i], $matches)) {
    +              if (!empty($matches[3])) {
    +                $classes = array_map('trim', explode(' ', $matches[3]));
    +                if (array_intersect($ignore_classes, $classes)) {
    +                  $open_tag = $matches[1];
    +                }
                  }
                }
              }
    -        }
    -        // Otherwise, check whether this is the closing tag for $open_tag.
    -        else {
    -          if (preg_match("`<\/$open_tag>`i", $chunks[$i], $matches)) {
    -            $open_tag = '';
    +          // Otherwise, check whether this is the closing tag for $open_tag.
    +          else {
    +            if (preg_match("`<\/$open_tag>`i", $chunks[$i], $matches)) {
    +              $open_tag = '';
    +            }
              }
    +          // Tag chunk is done, so next chunk must be text.
    +          $chunk_type = 'text';
            }
    -        // Tag chunk is done, so next chunk must be text.
    -        $chunk_type = 'text';
          }
    -    }
    
    -    $text = implode($chunks);
    -    // Revert back to the original comment contents
    -    _filter_url_escape_comments('', FALSE);
    -    $text = preg_replace_callback('`<!--(.*?)-->`', '_filter_url_escape_comments', $text);
    +      $text = implode('', $chunks);
    +      // Revert back to the original comment contents
    +      _filter_url_escape_comments('', FALSE);
    +      $text = preg_replace_callback('`<!--(.*?)-->`', '_filter_url_escape_comments', $text);
    +    }
      }
    
      return $text;

**Comment by indigoxela** [comment]
@lourdas many thanks for reporting. :pray: 

However, the steps to reproduce seem quite incomplete.
I have several sites running without problems on PHP 8.2, without ever showing the type error you had.

Maybe something went wrong with your upgrade? Possibly a custom or contrib module interferes...

The first thing we'd need to fix any problem, are reliable steps to reproduce with core alone. No contrib or other modules involved. Otherwise there are too many variables in the game. :wink:

**Comment by lourdas** [comment]
Ok, I will try with a fresh Backdrop installation and report back. If the fresh installation works fine, then some contrib module must be the issue.

**Comment by lourdas** [comment]
Did some more digging.

On a fresh Backdrop 1.27.1 no errors appear, no matter what I tried.

The upgraded from Drupal 7 installation contains these extra modules: SMTP authentication, EU Cookie Compliance, CAPTCHA, reCAPTCHA, Matomo Analytics, webform and XML sitemap.

It seems that webform has some issues with the PHP 8.1, I will report in the corresponding issue queue.

I'm closing this to reduce any noise.

Thanks for your time!
