### ISSUE TITLE
Fixed: Report if the Drupal compatibility layer is enabled to Telemetry.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6443]
This came up during the "What will happen in Backdrop 2.x?" session in the Backdrop LIVE event.

**Comment by klonos** [comment]
PR and sandbox for testing here: https://github.com/backdrop/backdrop/pull/4693 ...although testing if this reports correctly with the compatibility layer disabled requires editing the settings.php file, which is not possible in the sandboxes.

**Comment by stpaultim** [comment]
I'm not really sure how to test or provide any help with these telemetry issues. I assume that @quicksketch will chime in on this.

Since it has a PR now, I assume this qualifies for the bugfix release candidate tag.

**Comment by quicksketch** [comment]
Thanks @klonos! I merged https://github.com/backdrop/backdrop/pull/4693 into 1.x and 1.27.x.

**Comment by klonos** [comment]
FTR, I've already added the necessary configuration in https://backdropcms.org/project/backdrop/telemetry on the b.org side of things, and we already have some data coming through 🙂
