### ISSUE TITLE
Update Archive_Tar to release 1.5.0.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6446]
This is the equivalent of https://www.drupal.org/project/drupal/issues/3429165 for Drupal 7.

Essentially, there is a new Archive_Tar release (1.5.0) which slightly change the permissions used for the created temporary files. Backdrop uses release 1.4.9 created on December 4, 2019.

**Comment by kiamlaluno** [comment]
[The changes between 1.4.9 and 1.5.0](https://github.com/pear/Archive_Tar/compare/1.4.9...1.5.0) are not just the permissions used for files, though.

**Comment by indigoxela** [comment]
@kiamlaluno many thanks for working on this. :pray: 

A quick (off topic) question: as this is 3rd party code, we could add a `// phpcs:ignoreFile` to stop phpcs nagging on it. Or we could add an exclusion via commandline option. Which one's preferred?

**Comment by kiamlaluno** [comment]
In this case, `phpcs:ignoreFile` seems a better solution, IMO. At least, if the *core/modules/system/system.tar.inc* file were removed, it would not be necessary to edit a configuration file.

I can update the PR.

**Comment by kiamlaluno** [comment]
As expected, all checks have passed. I added a comment showing as Backdrop addition the line with the PHP_CodeSniffer directive.

```php
// Backdrop addition Ignore PHP_CodeSniffer warnings/errors for this file.
// phpcs:ignoreFile
```

**Comment by indigoxela** [comment]
The only usage I'm aware of in core is full config export and import, so I tested with that:

- Make a full config export (as tar.gz)
- Make a tiny change in system settings
- Upload config export, check changes in stage, import previous export

Works for me, no problems (as expected). :+1:

**Comment by argiepiano** [comment]
If possible this should be tested with backup_migrate, since that module makes use of Archive_Tar. I could try this... but not in the near future.

**Comment by indigoxela** [comment]
> ... this should be tested with backup_migrate

Absolutely, many thanks for the hint.

- Applied patch (local instance)
- Installed B&M
- Configured private file system
- Created a DB backup
- Checked that the file's in place
- Changed a node (nid 2), added some text
- Restored from backup
- Checked that the original text is back in node/2

So that also still works properly. :+1:

**Comment by argiepiano** [comment]
Thanks so much, @indigoxela! If it's not too much to ask, could you try a backup of the DB and config files? (instead of just a DB). Thanks again

**Comment by indigoxela** [comment]
> ... could you try a backup of the DB and config files?

Sure, I'm still there, no effort. :wink: 

First I tried an active config backup and restore (with checking again on commandline, that the .tar.gz is correct). Changed a Layout before restoring and after restore the initial layout setup was back.

Works.

Then a combined db dump and config backup and restore (again verified file on commandline).

Works.

The dblog's always wiped after db restore (as expected), but I had error display turned on - nothing suspicious showed up.

**Comment by argiepiano** [comment]
Wonderful. Thanks!

**Comment by herbdool** [comment]
RTBC. This is also RTBC in D7.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno, @indigoxela, @argiepiano, and @herbdool! I merged https://github.com/backdrop/backdrop/pull/4689 into 1.x and 1.27.x.
