### ISSUE TITLE
Fixed: `DatabaseSchema_mysql::fieldExists()` does not escape the column name.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6450]
This is the equivalent of https://www.drupal.org/project/drupal/issues/3397680 for Drupal 7 and https://www.drupal.org/project/drupal/issues/2797141 for Drupal 8.

[`DatabaseSchema_mysql`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21mysql%21schema.inc/class/DatabaseSchema_mysql/1) overrides the [`fieldExists()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21mysql%21schema.inc/function/DatabaseSchema_mysql%3A%3AfieldExists/1) method defined from the parent class ([`DatabaseSchema`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21schema.inc/class/DatabaseSchema/1)). That method escapes the table name, but not the field name, with the consequence that method returns `FALSE` for existing fields whose name is a reserved word, for example *trigger*.

Both `DatabaseSchema_mysql::fieldExists()` and [`DatabaseSchema_mysql::tableExists()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21database%21mysql%21schema.inc/function/DatabaseSchema_mysql%3A%3AtableExists/1) should be removed, though, as they are implemented as workaround for a bug that has been already fixed in MySQL 5.1.

```php
  // The information_schema table is very slow to query under MySQL 5.0.
  // Instead, we try to select from the table and field in question. If it
  // fails, the most likely reason is that it does not exist. That is
  // dramatically faster than using information_schema.
  // @link http://bugs.mysql.com/bug.php?id=19588
```

 Basing on the [telemetry data gathered from BackDrop](https://backdropcms.org/project/backdrop/telemetry), none of the sites are running on a MySQL database release that is older than MySQL 5.5. That means those methods can be removed.

**Comment by herbdool** [comment]
I agree that these can be removed now.

**Comment by laryn** [comment]
I agree with removing these and appreciate the telemetry data to back it up. 

Duplicate issue? https://github.com/backdrop/backdrop-issues/issues/6120

And do we need to update Backdrop requirements?

> MySQL 5.0.15 or higher with PDO enabled

**Comment by laryn** [comment]
@kiamlaluno Can we remove this one, too?

https://github.com/backdrop/backdrop/blob/81601e9dfd9f04e8a7182193191cc7b491a7c862/core/includes/database/mysql/schema.inc#L501-L502

**Comment by kiamlaluno** [comment]
@laryn I would leave that for a different issue, at least to do the same changes done in the referenced Drupal issue.

If this change is applied, I would also change the requirements documentation, at least to report the exact requirements. (I would not expect somebody used a deprecated MySQL version, but getting the exact requirements is always appreciated.)

**Comment by quicksketch** [comment]
From the looks of the inline documentation, this is actually backwards-compatible, it's just a lot slower if you're on MySQL 5.0. I don't see any problem with removing this MySQL 5.0-specific optimization. It looks like in today's database systems, using this old approach is actually much slower than the default method (see https://www.drupal.org/project/drupal/issues/2797141#comment-14433090). So in summary:

- This is actually still backwards-compatible
- Removes unnecessary code
- Is a performance optimization for current MySQL versions at the expense of a very, very old MySQL version (EOL 2007)

Looks great, thanks @kiamlaluno!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4691 into 1.x and 1.27.x. Thanks @kiamlaluno, @laryn, and @herbdool!

**Comment by klonos** [comment]
FTR: follow-up here for the removal requested by @laryn: #6466
