### ISSUE TITLE
User edit form does not use flood control and allow for password brute force attacks

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6452]
This is the equivalent of [[D7] User edit form does not use flood control and allow for password brute force attacks](https://www.drupal.org/project/drupal/issues/3440063) and [User edit form does not use flood control and allow for password brute force attacks](https://www.drupal.org/project/drupal/issues/2339399).

Essentially, having access to a user edit form (the original issue says "if an attacker is able to get a user's session cookie"), it is possible to try to guess the account password by brute force, since there is no limit to the number of try that can be done, which are usually under flood control.

Any change to the password should be under flood control.

As a side note, the Drupal 8+ (now Drupal 11) issue is postponed because the flood control code is refactored and moved in a Drupal service. Such change is not necessary in Backdrop, which does not use Symfony services.

**Comment by kiamlaluno** [comment]
I cannot see why the tests are failing. The test code I added should be correctly copied.

**Comment by stpaultim** [comment]
@kiamlaluno - Can you provide any guidance on how to test this issue?

**Comment by kiamlaluno** [comment]
@stpaultim  Leaving out the "get a user's session cookie" part, try editing an existing user account by changing its mail, and putting a wrong password in the *Current password* field.  

A plain Backdrop site will allow you to keep putting a wrong password in that field. With the PR, the site should show an error message about entering the wrong password too much times.

**Comment by stpaultim** [comment]
I can confirmed the problem with an existing test site and verified that the problem appears to be solved on the sandbox site. To test, I did the following:

1) Changed the email addres for the admin account
2) Tried repeatedly to save my changes after entering an incorrect password. 
3) On the sixth atttempt I got this message. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/686845df-b9f9-49b5-9f5e-ac0f846ce87d)

**Comment by herbdool** [comment]
I've fixed the tests. LGTM now.

**Comment by quicksketch** [comment]
Thank you @avpaderno for porting this security hardening! I merged https://github.com/backdrop/backdrop/pull/4694 into 1.x and 1.29.x. Thank you @poker10 for making the D7 patch!

---

7c33587ffe994516f4f352d9718a0e1008a2e1b2 by @avpaderno, @herbdool, @stpaultim, and @quicksketch.

Port of Drupal issue #3440063 by @poker10.
