### ISSUE TITLE
XMPP: Post to PubSub nodes

### ISSUE THREAD

**Issue by sjehuda** [backdrop/backdrop-issues#6454]
## Description of the need

I want to publish my Backdrop contents over PubSub node items on my XMPP server.

## Proposed solution

Add support to post to pubsub node items using Moxl library.

## Alternatives that have been considered

There are no alternatives in a form of a plugin.

## Additional information

In XMPP, using PubSub(1) (XEP-0060), it is possible to store posts as Atom Syndication(2) entries into XMPP(3).

There are several XMPP extensions that apply it, namely XEP-0227 (4) and XEP-0472 (5) which make node `urn:xmpp:microblog:0` as a common choice to manage news for client accounts (e.g. `blog@backdropcms.org`), yet a component account (e.g. `pubsub.backdropcms.org`) may use all of its nodes for this purpose.

A PHP library that can be utilized would be Moxl of Movim.

I have made a script that realizes viewing PubSub node items as Atom XML feeds over HTTP.

1. [XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html)
2. [RFC 4287: The Atom Syndication Format](https://www.rfc-editor.org/rfc/rfc4287)
3. [Atom Over XMPP](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf)
4. [XEP-0277: Microblogging over XMPP](https://xmpp.org/extensions/xep-0277.html)
5. [XEP-0472: Pubsub Social Feed](https://xmpp.org/extensions/xep-0472.html)
6. [Moxl](https://github.com/movim/movim/tree/master/src/Moxl)
7. [PubSub Over HTTP](https://codeberg.org/poezio/slixmpp/issues/3526)

## Draft of feature description for Press Release (1 paragraph at most)

Visual depiction of what it would be like on an XMPP server.

```
pubsub.backdropcms.org/
|
|-- updates/
    |-- Sombre
     `-- Varied
|-- releases/
 `-- events/
```
```
pubsub service/
|
|-- node/
    |-- item
     `-- item
|-- node/
 `-- node/
```

**Comment by indigoxela** [comment]
@sjehuda welcome to the Backdrop issue queue. :wave: 

What you describe, sounds a bit exotic and rather like a candidate for [contrib](https://github.com/backdrop-contrib), though.

**Comment by sjehuda** [comment]
@indigoxela I read the conditions at https://github.com/backdrop-ops/contrib/issues/new which appears to have me required to have a project ready for testing, yet I have nothing yet.

What should I do to progress with this?

**Comment by laryn** [comment]
@sjehuda I'd recommend developing the contrib module in your own Github repo to start, and once it's ready there is a process to apply and then transfer the repo into the contrib space.

**Comment by sjehuda** [comment]
I am closing this ticket then.

Is there a groupchat where we can talk together about Backdrop and XMPP?

**Comment by sjehuda** [comment]
Thank you @laryn I have posted a message at [218635-Backdrop/topic/XMPP.20and.20PubSub](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/XMPP.20and.20PubSub).

I would be delighted if as many of you would join this discussion.

Please ask me anything, especially if you want technical explanations.

**Comment by Neustradamus** [comment]
It is an important feature!
