### ISSUE TITLE
Fixed: All PRs failing `ImageStylesPathAndUrlUnitTest`.

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6459]
## Description of the bug

About 3 days ago all PRs started failing (there's only been 3 PRs in that time). The first one that failed seems to be https://github.com/backdrop/backdrop/pull/4696

The failures are coming from `ImageStylesPathAndUrlUnitTest` with the error:

```
 Fail      Other      image.test        249     _testImageStyleUrlAndPath()                                             
    Expected Content-Length was reported.
```

![image](https://github.com/backdrop/backdrop-issues/assets/100206/f7ac982e-0857-4453-8293-9c5e0c07b2d2)

It happens on PHP 5.6, 7.4, and 8.3 versions.

## Steps To Reproduce

To reproduce the behavior:
1. File any PR with any change, even just the README.md
2. The PR will fail with the above test failing.

Add any other information that could help, such as:
- Backdrop CMS version: 1.x
- Web server and its version: Seemingly Apache on GHA
- PHP version: All
- Database sever (MySQL or MariaDB?) and its version: 10.3
- Operating System and its version: Ubuntu
- Browser(s) and their versions: N/A

**Comment by quicksketch** [comment]
Debugging this, it seems as though Apache on GHA is ignoring the `Content-Length` header and instead returning `Transfer-encoding: Chunked`. These two headers [are mutually exclusive](https://stackoverflow.com/questions/2419281/content-length-header-versus-chunked-encoding).

Here's the headers on an image style coming back in GHA:

```
    Expected Content-Length (193) matches actual Content-Length () at
    http://localhost/?q=system/files/styles/style_foo/private/image-test.png. Array
    (
        [:status] => HTTP/1.1 200 OK
        [date] => Sat, 20 Apr 2024 07:51:31 GMT
        [server] => Apache/2.4.41 (Ubuntu)
        [x-backdrop-cache] => MISS
        [expires] => Fri, 16 Jan 2015 07:50:00 GMT
        [cache-control] => no-cache, must-revalidate
        [x-content-type-options] => nosniff
        [x-image-owned-by] => image_module_test
        [last-modified] => Sat, 20 Apr 2024 07:51:31 GMT
        [etag] => "1713599491"
        [transfer-encoding] => chunked
        [content-type] => image/png
    )
```

And here's what I get locally on DDEV (which uses nginx):

```
    Expected Content-Length (193) matches actual Content-Length (193) at
    http://localhost/?q=system/files/styles/style_foo/private/image-test.png. Array
    (
        [:status] => HTTP/1.1 200 OK
        [server] => nginx
        [date] => Sat, 20 Apr 2024 07:55:04 GMT
        [content-type] => image/png
        [content-length] => 193
        [connection] => keep-alive
        [x-backdrop-cache] => MISS
        [expires] => Fri, 16 Jan 2015 07:50:00 GMT
        [last-modified] => Sat, 20 Apr 2024 07:55:04 +0000
        [cache-control] => no-cache, must-revalidate
        [x-content-type-options] => nosniff
        [etag] => "1713599704"
        [x-image-owned-by] => image_module_test
    )
```

It seems as though maybe a recent Apache update has a pretty serious bug in it that might be ignoring `Content-Length` headers. I tried setting other custom headers from within `image_file_download()` (where these headers are sent) and they come back fine (i.e. `X-Content-Length`) so it seems to be a problem specifically with Apache and the `Content-Length` header.

**Comment by indigoxela** [comment]
Oh, wait, a newer apache - we need a slight tweak then, which I already figured out in a previous PR (stalled)...

Let me find that...

**Comment by indigoxela** [comment]
Let's try parts of this one: https://github.com/backdrop/backdrop/pull/4597/files

Background: the directory tree of the runner home has permissions set, that prevent newer apache from accessing them.

**Comment by quicksketch** [comment]
I appreciate that you left your git log of struggles to get Ubuntu-22.04 working. I've spent nearly all night on this problem not realizing it was caused by Apache. :zany_face:

**Comment by quicksketch** [comment]
I updated my PR at https://github.com/backdrop/backdrop/pull/4699 to pull in your Ubuntu 22.04 updates, that got all tests passing, _except_ the guilty `ImageStylesPathAndUrlUnitTest`. Seems updating the OS does not help with this particular problem (great work though!) I'll look into merging https://github.com/backdrop/backdrop-issues/issues/6327 just to get that out of the way as a culprit.

**Comment by indigoxela** [comment]
No solution so far.

What I can tell:

- In Drupal 7 the same test fails, too (same problem apparently)
- Private file system checks seem to work fine in this test
- In this Simpletest request mess image_style_deliver() does its job properly, regardless of test failure - images get created

As I don't get anywhere with Simpletest, I switched to curl command line, and there's an interesting finding:

The first `curl -I ...` request on a derivative file - the one that triggers derivative image creation - doesn't get the Content-Length header, a second request right after that gets it. This doesn't help with Simpletest, but seems somehow related.

**Comment by herbdool** [comment]
Maybe there's something here that could provide clues https://stackoverflow.com/questions/14464516/always-send-content-length-in-apache

**Comment by herbdool** [comment]
One comment on SE which might help: 

> Apache won't set Content-Length if it's using chunked encoding, which it will use for PHP output if mod_deflate is off, or if the size of the content is greater than the DeflateBufferSize setting, or if mod_deflate isn't being used for PHP in your configuration.

**Comment by quicksketch** [comment]
> the one that triggers derivative image creation - doesn't get the Content-Length header, a second request right after that gets it.

Thanks @indigoxela this is a great finding and helpful. That means that if PHP is returning the response, Apache is discarding the `Content-Length` header, but when serving from disk it sets it correctly.

I tried a variety of fixes and changes:

- Disabling gzip, deflate, and other compressions
- Setting a "Connection: Closed" header
- Flushing PHP output buffers
- Changing the way simpletest makes requests

But nothing is helping this problem. Also testing this locally with Apache I do not see the same problem. Though my local uses Apache/2.4.56 compared to GHA's Apache/2.4.52. Both are running php-fpm.

I'm pretty stumped by this test failure.

**Comment by quicksketch** [comment]
After some more troublesome experimenting, I think we might consider simply accepting the current responses from Apache as being valid. As @indigoxela and myself have confirmed, `image_style_deliver()` is properly generating an image, and the test coverage already ensures the file content and type are coming back correctly. There's also nothing invalid about Apache returning a "chunked" response instead of a fixed length one (it's just not what we were expecting).

So for the sake of resolving this quickly and to unblock other 1.28.0 issues, I updated https://github.com/backdrop/backdrop/pull/4699 as a solution that accepts either the `Content-Length` header _or_ `Content-Encoding: chunked` as valid responses.

**Comment by klonos** [comment]
Thanks @quicksketch 🙏🏼 ...tests are passing, and the compromise seems perfectly acceptable to me. Logic in the code looks good too, so RTBC 👍🏼

A minor request for improvement: does it make sense and should we consider further limiting the `if ($transfer_encoding == 'chunked')` conditional to only when the server is apache? (since we have no indication that this problem applies to nginx)

**Comment by indigoxela** [comment]
> does it make sense and should we consider further limiting the if ($transfer_encoding == 'chunked') conditional to only when the server is apache?

Not really, as the same problem occurs with recent Nginx (see issue description). :wink:

**Comment by indigoxela** [comment]
A lot more digging and debugging, as I really try to understand, what's going on.

FTR: image_style_deliver() does set the header (via file_transfer / backdrop_add_http_header). It's just that apache apparently ignores it. But only Content-Length, as the Content-Type header's there.

Whatever broke, it broke recently and may or may not have to do with some performance (or security?) optimization in mod_proxy_fcgi in combination with php-fpm. (I admit, I totally got lost in apache changelogs... :wink:)

The PR looks like a good compromise. It still checks that the derivative image is created and delivered, and that's what the test is for. :+1: If it's this or that header (Content-Length vs Transfer-Encoding) isn't the main purpose here.

Re limiting to Apache - I don't think, this provides any additional value here.

**Comment by quicksketch** [comment]
Thanks @indigoxela and @klonos for reviewing. I really appreciate your deep dive into this @indigoxela! This had me incredibly stumped (and it still does), but I think this is a good compromise too. I merged https://github.com/backdrop/backdrop/pull/4699 into 1.x and 1.27.x to get us unstuck and tests passing on new PRs.

**Comment by indigoxela** [comment]
FWIW I have a (hardly ever used) apache install with mod_php on my laptop, and this one **does** provide the Content-Length header at first try (when creating the derivative file). So it's not apache (alone), but some specific apache setup, probably php-fpm with proxy_fcgi, but it's still unclear which combo exactly.

**Comment by quicksketch** [comment]
That's good info @indigoxela. mod_php is, in my experience, very rarely used these days. php-fpm has really taken over as the primary way to run PHP on Apache. I think you're right though, it's some combination of php-fpm/fcgi/Apache that causes the problem.
