### ISSUE TITLE
Missed instance of "white-listed"

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6465]
We missed this in #4441: https://github.com/backdrop/backdrop/blob/1.x/core/includes/common.inc#L2806
```php
 * ...
 * attribute names, it is strongly recommended to allow only white-listed names,
 * ...
```

**Comment by klonos** [comment]
PR here: https://github.com/backdrop/backdrop/pull/4703 ...nothing to test, since this changes only the wording within a docblock - just needs review of the rewording.

**Comment by stpaultim** [comment]
I think I can do code review on this one. ;-)

**Comment by quicksketch** [comment]
Merged into 1.x and 1.27.x. Thanks @klonos and @stpaultim!
