### ISSUE TITLE
Remove workaround for http://bugs.mysql.com/bug.php?id=11379 from schema.inc

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6466]
In https://github.com/backdrop/backdrop-issues/issues/6120#issuecomment-1556176959 and https://github.com/backdrop/backdrop-issues/issues/6450#issuecomment-2052092222 @laryn made a request to remove this from schema.inc: https://github.com/backdrop/backdrop/blob/81601e9dfd9f04e8a7182193191cc7b491a7c862/core/includes/database/mysql/schema.inc#L501-L502
```php
    // Work-around for MySQL 5.0 bug http://bugs.mysql.com/bug.php?id=11379
    return preg_replace('/; InnoDB free:.*$/', '', $comment);
```

Since we only removed the cruft around `DatabaseSchema_mysql::fieldExists()` and `DatabaseSchema_mysql::tableExists()`, but not that other bit, I'm raising this issue here as a follow-up.

According to https://bugs.mysql.com/bug.php?id=11379 the bug that this workaround was added for was fixed in MySQL v5.1.21. [Our telemetry](https://backdropcms.org/project/backdrop/telemetry) currently shows that there is no site using any version older than 5.5, so we should be good there. [Our system requirements](https://docs.backdropcms.org/documentation/system-requirements) though mentions that the minimum version supported is currently 5.0.15 or higher, so making this change here would mean a bump in the minimum requirements, and a change record etc.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4881 that removes the work-around.

**Comment by quicksketch** [comment]
I also filed an issue to increase our minimum MySQL version officially at https://github.com/backdrop/backdrop-issues/issues/6724.

**Comment by herbdool** [comment]
Looks good to me.

**Comment by quicksketch** [comment]
I merged this after multiple agreements (both in the issue and in weekly meetings) that bumping our MySQL version to 5.5 is desirable. We'll make the change record associated with #6724.
