### ISSUE TITLE
Remove call to `backdrop_wrap_mail()` from `DefaultMailSystem::format()`.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6471]
This is the equivalent of [DefaultMailSystem implements MailSystemInterface::format() incorrectly](https://www.drupal.org/project/drupal/issues/1447236) for Drupal 7.

[`DefaultMailSystem::format()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.mail.inc/function/DefaultMailSystem%3A%3Aformat/1) contains the following code.

```php
$message['body'] = backdrop_html_to_text($message['body']);
// Wrap the mail body for sending.
$message['body'] = backdrop_wrap_mail($message['body']);
```

The description for [`backdrop_html_to_text()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21mail.inc/function/backdrop_html_to_text/1) says:

> The output will be suitable for use as 'format=flowed; delsp=yes' text (RFC 3676) and can be passed directly to [`backdrop_mail()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21mail.inc/function/backdrop_mail/1)() for sending.

[`backdrop_wrap_mail()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21mail.inc/function/backdrop_wrap_mail/1) converts all soft breaks into hard breaks, making 'format=flowed' meaningless.

**Comment by klonos** [comment]
I have reviewed the code and it matches the respective code that is RTBC for D7. I have left a suggestion in the PR to consider adding a comment improvement/clarification, but this is otherwise RTBC.

Not sure how to test this though.

**Comment by quicksketch** [comment]
Thanks @klonos! @kiamlaluno I think this needs instructions for testing. Will the affect the emails that Backdrop sends, like welcome emails and password resets?

The D7 issue was marked RTBC by @kiamlaluno (although someone else provided the patch in 2019). So I guess there's already 2 people that feel it's ready on the Drupal side.

**Comment by kiamlaluno** [comment]
I apologize: I think I wrongly added the *pr - needs testing* label.

**Comment by herbdool** [comment]
This does seem to be correct.

**Comment by quicksketch** [comment]
Thanks @avpaderno, @klonos, and @herbdool! I merged https://github.com/backdrop/backdrop/pull/4705 into 1.x and 1.28.x.

**Comment by argiepiano** [comment]
I noticed that this PR has fixed the use of `backdrop_wrap_mail()` in `DefaultMailSystem::format()`. However, this pattern has not been fixed in `MailTestCase::format()`, which means that we have a test that uses a different pattern than the actual thing it's intending to test. 

Now that this is closed, @avpaderno, do you think you can open another issue and fix the test as well?
