### ISSUE TITLE
Fix broken link in the layout templates installation success message

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6474]
## Steps To Reproduce

To reproduce the behavior:
1. Install any contrib layout template via the project installer
2. After the installation finishes, there should be a success message shown at the top of the page:
   > Installation finished successfully. All newly-added layout templates have been enabled and are available for use in your layouts. You can manage them on the [Layout templates]() page.

## Actual behavior

The link "Layout templates" within the success message links to `/admin/structure/admin/structure/layouts/settings`, which redirects to the main "Structure" page at `/admin/structure`.

## Expected behavior

The link should be pointing to "Layout templates" page at `/admin/structure/layouts/settings` instead.

**Comment by klonos** [comment]
Simple PR up for review/testing: https://github.com/backdrop/backdrop/pull/4708

Sadly, installing contributed projects in our PR sandboxes is currently broken, so this will need to be tested locally 😞

**Comment by argiepiano** [comment]
Thanks, @klonos. I left a comment in the PR.

**Comment by klonos** [comment]
Suggestion merged @argiepiano ...thank you 🙏🏼

**Comment by argiepiano** [comment]
RTBC!

**Comment by quicksketch** [comment]
Thanks @argiepiano and @klonos! I merged https://github.com/backdrop/backdrop/pull/4708 into 1.x and 1.27.x.
