### ISSUE TITLE
[UX] Set the default value for "Layout template" to the same template that's in use on the default layout.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6479]
When you create a layout from the layouts listing page currently, you are asked for the layout template every time.

Many of us regularly forget to select a template on this step (causing an immediate validation error when we enter the path). 

<img width="1211" alt="Screenshot 2024-04-26 at 2 33 42 PM" src="https://github.com/backdrop/backdrop-issues/assets/397895/01e6be21-1d16-4ae6-b525-77304c8df48e">

The reason we forget to select a template so often is because which template is in use is not even something we're thinking about -- because it's not relevant to our current task: placing blocks on the page.

This could be solved if the "Layout template" question had a default value.

@yorkshire-pudding  suggested:

>  the template used in the default layout should be selected by default

Yes please :)

**Comment by jenlampton** [comment]
I've filed a quick PR with a few line change. 
```patch
+  if ($layout->layout_template != NULL) {
+    $layout_template = $layout->layout_template;
+  }
+  else {
+    $layout_template = config_get('layout.layout.default', 'layout_template');
+  }
   $form['layout_template'] = array(
     '#title' => t('Layout template'),
     '#type' => 'radios',
-    '#default_value' => $layout->layout_template,
+    '#default_value' => $layout_template,
     '#options' => array(),
```

**Comment by stpaultim** [comment]
I'm a bit surprised that there is nto an existing issue for this. It's a bit of a pet peeve of mine as well. This seems like a simple and useful solution! 

Works for me.

**Comment by jenlampton** [comment]
> I'm a bit surprised that there is not an existing issue for this.

Same! It's been bothering me for so long I can't believe *I* hadn't created one before now :)

**Comment by klonos** [comment]
Indeed, that seems like a non-brainer that should be in place from the start 👍🏼

**Comment by klonos** [comment]
I've tested this and it works like a charm! Thanks @jenlampton 🙏🏼 ...and thank you @yorkshire-pudding for the brilliant idea ❤️ 

I've reviewed the code and it looks good (only left a suggestion for an inline comment to be added to explain what we are doing and why).

Here's what I've tested:
1. create a new layout -> confirm that the default template is pre-selected 👍🏼 
2. change the template used in the default layout -> create a new layout -> new template is pre-selected 👍🏼 
3. edit the layout created in step 1. above -> the template that the layout was saved with is still in use (not accidentally reverting to the template of the default layout)

So this works as expected when creating new and when editing existing layouts 👍🏼  ....RTBC

**Comment by jenlampton** [comment]
I also just added tests, so no rejecting by core devs! (I hope)

**Comment by klonos** [comment]
One spelling nag in the new test.

**Comment by jenlampton** [comment]
Fixed the spelling error, and some other PHPCS failures.

**Comment by klonos** [comment]
@jenlampton there are some CSS changes that seem to have creeped in from your local now.

**Comment by jenlampton** [comment]
Gah, sorry. I managed to pull those out last time and then they snuck in again. removed!

**Comment by klonos** [comment]
This is RTBC again 👍🏼 ...minus a small suggestion to use single instead of double quotes in some text.

**Comment by bugfolder** [comment]
A big peeve of mine is forms that throw validation errors before I'vee finished filling them out, so I'm very happy to see this.

**Comment by klonos** [comment]
If people like this change, then please review/test the PR for #6480 as well.

**Comment by argiepiano** [comment]
Love it!

**Comment by quicksketch** [comment]
This is such an incredibly good fix! I can't believe we've made people click an option and encounter that AJAX error for so long. Great idea @jenlampton!

Thanks everyone, I've merged https://github.com/backdrop/backdrop/pull/4711 into 1.x and 1.27.x.
