### ISSUE TITLE
Error on enabling pathauto with token enabled

### ISSUE THREAD

**Issue by ronnienorwood** [backdrop/backdrop-issues#648]
After updating to BD 1.0.1, downloaded zip files for token & pathauto modules from github, unpacked them, then FTPed them to modules folder on hosted website.  Enabled token module with no errors but got error below when enabling pathauto.  Though it does appear to be enabled when re-displaying modules page.

![screenshot_012515_012821_pm](https://cloud.githubusercontent.com/assets/887238/5893371/16e01f00-a496-11e4-8934-70c4d1f89979.jpg)

**Comment by quicksketch** [comment]
Hi @ronnienorwood! This should probably go against the pathauto project. Looks like there are already a number of bugs filed against it: https://github.com/backdrop-contrib/pathauto/issues.

Ah, here's the one: https://github.com/backdrop-contrib/pathauto/issues/3

Thanks for reporting!

**Comment by ronnienorwood** [comment]
Perfect, @quicksketch.

Makes sense, like in drupal land :^)

Thanks for the guidance!
