### ISSUE TITLE
How do we deal with patches from Drupal.org contrib modules that are in Backdrop core?

### ISSUE THREAD

**Issue by sirkitree** [backdrop/backdrop-issues#649]
I ran into a problem tonight with Views that has a patch on Drupal.org. Applying the patch to Backdrop's core Views module works to fix my problem, but the patch hasn't yet been committed to the Drupal.org contrib Views module yet. 

How do we handle cases like this? 

Should I still create a pull request for Backdrop that links to the issue on Drupal.org? Or should I wait (possibly months) for this to get into the Drupal module and then it'll somehow get into Backdrop?

Maybe a larger question here is: how is Backdrop dealing with it's core modules that are still contrib modules in Drupal?

**Comment by quicksketch** [comment]
File an issue in the Backdrop issue queue (here) and just cross-reference the issue in the drupal.org queue. Sometimes we review and commit things faster than Drupal, and some times what was acceptable for Drupal isn't the right approach for Backdrop. If the patch needs work in the Drupal queue, we can sometimes start with that patch and try to take it to completion. If the patch applies *back* to Drupal, the courteous thing to do is reroll the patch and submit it back to the Drupal issue as well.

**Comment by sirkitree** [comment]
Excellent. Thank you.
