### ISSUE TITLE
[UX] Admin bar: Too much left/right padding introduced with the new Icon API changes

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6495]
With #364, the admin bar icons have increased size, which is good for UX (larger area to interact with is better on touch-enabled devices), however there is now too much left/right padding as well (`1.5em` and `1em` respectively). That causes the the following:
- icons appear too far from each other visually (this is just aesthetics and subjective opinion)
- increase of mouse "travel time" when moving horizontally across the admin bar
- decrease of the width that causes reaching the breakpoint that switches the admin to mobile version

Some screenshots for visual:
- Before:
  ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/6f0c8ee3-4fdd-4548-81f7-58bd16fb6672)
- Now (`1.5em` left and `1em` right padding):
  ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/a2008021-fff3-4581-9c51-2c5875c6b58f)
- Proposed (`1em` and `.5em`):
  ![image](https://github.com/backdrop/backdrop-issues/assets/2423362/4ad0aefe-2772-4087-b53a-6965f62959d0)

Perhaps we should decrease the padding even further(?)

**Comment by quicksketch** [comment]
I sort of like the menu items a little more spread out so that you can tell which icon goes with which menu item. But I would be in favor of reducing the spacing between menu items so that the font size can be increased further without collapsing the extra items.

@klonos Do you have the code ready for a PR?

**Comment by quicksketch** [comment]
Also looks like https://github.com/backdrop/backdrop-issues/issues/6488 was opened a few days ago. This issue looks like it's a duplicate if you would prefer to work over there.

**Comment by klonos** [comment]
Thanks for pointing the other issue out. Closing this one here as a duplicate (I've moved what I said here in the issue summary over to the other issue as a comment).
