### ISSUE TITLE
Document  that some of Drupal 7 contrib may "just work" w/ Backdrop (but Drupal 8 contrib will NOT)

### ISSUE THREAD

**Issue by greggles** [backdrop/backdrop-issues#65]
I think I saw this posted somewhere saying that contrib won't work, but it was unclear to some folks and I can't find the statement.

Seems like an important thing to document.

**Comment by quicksketch** [comment]
We're still getting our docs in order, but I published a video a few weeks ago on the process of porting a module to Backdrop: https://www.youtube.com/watch?v=by8mMhIpARA

It's interesting in that is basically only took 3 lines to make the sample module (External Links) "backdrop compatible" (the first 5 minutes of the video), but the complete port to work with the config system and eliminate all `drupal_` prefixes took the remainder of the video (25 minutes). This reiterates that while it's possible to have Backdrop-compatible modules that work on D7, you'll most likely want to do a full port to take advantage of Backdrop's features.

**Comment by quicksketch** [comment]
Though it's still in progress, our upgrading page (https://backdropcms.org/upgrade) now includes this, which I think makes it clear and in an obvious location:

> Review the contributed modules in use on your current site. Very few Drupal sites run on what's in core alone. Have the modules you are using been ported to Backdrop already? If not, are you prepared to port them yourself? Most modules can be made Backdrop-compatible in a matter of hours or minutes, though a full port takes longer.

That's clear enough, especially combined with the link to the video and the contrib repository.
