### ISSUE TITLE
Foreign key constraint failure in user_update_1007.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6502]
## Description of the bug

I'm early in an upgrade process and a trial run is throwing this error:

> user module
> Update #1007
> Failed: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE {role}; Array ( ) in db_drop_table() (line 2938 of /var/www/html/core/includes/database/database.inc).

I've never seen this error before in an upgrade, but I commented out `db_drop_table('role');` near the end of `user_update_1007()`and was able to proceed without errors. After the upgrade I tried to drop that table manually and have received a similar error, so I need to track down what's causing that.

**Comment by argiepiano** [comment]
Hmmm... hook_schema() [states](https://github.com/backdrop/backdrop/blob/da1608254d379884311efdb9bbfb55e50d177b48/core/modules/system/system.api.php#L2636) that mysql foreign keys are not supported by Backdrop (they are there only for documentation purposes), so my guess is that someone modified your database and added a foreign key for unknown purposes, which is causing problems during your upgrade.

**Comment by laryn** [comment]
I suspect this may be due to the `private_files_download_permission` module but still digging into it.

**Comment by argiepiano** [comment]
> I suspect this may be due to the `private_files_download_permission` module but still digging into it.

Yes, that seems to be [adding](https://github.com/backdrop-contrib/private_files_download_permission/blob/7a706812c551b08e41f868f4db6f0b5ea49be54f/private_files_download_permission.install#L45) a foreign key that points at users

**Comment by laryn** [comment]
Thanks @argiepiano 

I'm going to move this digging over to that queue. https://github.com/backdrop-contrib/private_files_download_permission/issues/1

Anyway, it's not bad that this issue exists in case anyone else sees the same and is trying to track it down...
