### ISSUE TITLE
Update the messages style for Bartik.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#651]
"Page created" message in D7/Backdrop Bartik:

![bd_page_created_msg](https://cloud.githubusercontent.com/assets/2423362/5900508/0e0aa232-a5be-11e4-89fb-9d61ad799e3c.png)

Same message in D8 (better icon, thick left border):

![d8_page_created_msg](https://cloud.githubusercontent.com/assets/2423362/5900482/c222aac2-a5bd-11e4-8ce0-fbd971135a47.png)

**Comment by docwilmot** [comment]
or darker, flatter, without borders

![prettier-message](https://cloud.githubusercontent.com/assets/1042283/5900772/9c355ae0-a53a-11e4-9f3c-6f7f81e61c61.PNG)

**Comment by docwilmot** [comment]
Actually I think we should do at least a limited update the default theme. Get rid of the gradient and tabs and curved borders.

**Comment by klonos** [comment]
> or darker, flatter, without borders

I don't mind the border/color depth that much. It was the outdated icon that got me to file this issue.

**Comment by Dinornis** [comment]
This issue can probably be closed as the message style for Bartik has been updated since this issue was opened.

**Comment by klonos** [comment]
...for posterity:

<img width="939" alt="Screen Shot 2019-09-15 at 9 39 57 pm" src="https://user-images.githubusercontent.com/2423362/64921042-67d3a000-d801-11e9-8f18-5f034f783cba.png">
