### ISSUE TITLE
Debug Report - last item shows up twice

### ISSUE THREAD

**Issue by stpaultim** [backdrop/backdrop-issues#6514]
## Description of the bug

This is a follow-up issue/bug for the new "Debug Report" issue that has been merged into BackdropCMS 1.28. 
https://github.com/backdrop/backdrop-issues/issues/5791

The last item on the list, show up twice. This has been mentioned in a dev meeting, so I know that it is a known issue. But, I can't find an existing ticket for this, so I'm creating this one.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/a742f320-6df4-4794-92a4-3ed28ea65171)

This happens for "Other" projects, but also "Contrib":

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/856c53ad-cee7-4687-9283-ee09ef2ff358)

## Steps To Reproduce

To reproduce the behavior:
1. Just add a module to a Backdrop site and go to the debug report - /admin/reports/debug

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/89c0c5f0-e8ed-42ae-b2e0-960e43d0260e)

## Expected behavior

Each module should only show up once.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4754

This was a weird issue where a pass-by-reference variable (`$line`) was getting used outside of the `foreach()` it was defined for. Using a different variable name fixed the conflict.

I also added the `@since` line documentation @klonos had requested in https://github.com/backdrop/backdrop-issues/issues/5791#issuecomment-2088201157.

**Comment by stpaultim** [comment]
@quicksketch - I tested in sandbox with core modules and in a local site with several contrib modules. 

Seems to be working for me. 
```

Backdrop CMS:                   1.28.x-dev
Installation profile:           standard
PHP version:                    8.2.18
Drupal 7 compatibility:         on
Database server:                10.11.7-MariaDB-1:10.11.7+maria~ubu2204-log
Web server:                     nginx/1.24.0
jQuery version:                 3.7.1
jQuery UI version:              1.13.2
CKEditor 5 version: 40.2.0      Used in formats: Basic

Themes
======
Default theme:                  Basis (basis) 1.28.x-dev
Admin theme:                    Seven* (seven) 1.28.x-dev
                                *used when editing or creating content

Enabled modules
===============

Core
----
admin_bar                       1.28.x-dev
block                           1.28.x-dev
ckeditor5                       1.28.x-dev
color                           1.28.x-dev
comment                         1.28.x-dev
config                          1.28.x-dev
contextual                      1.28.x-dev
dashboard                       1.28.x-dev
date                            1.28.x-dev
dblog                           1.28.x-dev
email                           1.28.x-dev
entity                          1.28.x-dev
field                           1.28.x-dev
field_sql_storage               1.28.x-dev
field_ui                        1.28.x-dev
file                            1.28.x-dev
filter                          1.28.x-dev
image                           1.28.x-dev
installer                       1.28.x-dev
layout                          1.28.x-dev
link                            1.28.x-dev
list                            1.28.x-dev
menu                            1.28.x-dev
node                            1.28.x-dev
number                          1.28.x-dev
options                         1.28.x-dev
path                            1.28.x-dev
redirect                        1.28.x-dev
search                          1.28.x-dev
system                          1.28.x-dev
taxonomy                        1.28.x-dev
telemetry                       1.28.x-dev
text                            1.28.x-dev
update                          1.28.x-dev
user                            1.28.x-dev
views                           1.28.x-dev
views_ui                        1.28.x-dev

Contrib
-------
backup_migrate                  1.x-1.0.26
devel                           1.x-1.8.2
devel_generate                  1.x-1.8.2
devel_node_access               1.x-1.8.2
googleanalytics                 1.x-2.8.0
```

**Comment by herbdool** [comment]
RTBC

**Comment by quicksketch** [comment]
Thanks @stpaultim, @herbdool, and @klonos!

**Comment by argiepiano** [comment]
> The earlier comment by @quicksketch that it was a weird case made me wonder if an additional comment in the code may be worth adding to draw attention to the code and highlight a caution?

There is no need for that. This was a code bug that got fixed, and there is no "warning" needed since there is no bug anymore!
