### ISSUE TITLE
file_delete() doesnt have a return value

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#652]
fixing an image deletion issue in the IMCE port and found the culprit was that this:

```
    if (!file_delete($file, TRUE)) {
      return FALSE;
    }
```

seems file_delete now takes $file->fid as parameter, not the $file object, and no second parameter. the new format is:
`file_delete($file->fid);`

but then after the errors went away, but the file still didnt delete, and an hour passed, i realised this always returns false

```
    if (!file_delete($file->fid)) {
      return FALSE;
    }
```

So in short, change notices needed.

**Comment by quicksketch** [comment]
> i realised this always returns false

Huh. I wonder if we can fix the backwards-incompatibility here. I'm guessing it was changed to match `node_delete()` and `comment_delete()`. The change record sounds good for now.
