### ISSUE TITLE
[DX] Support the 429 HTTP code (Too Many Requests) in backdrop_http_request()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6529]
This is the respective issue for https://www.drupal.org/project/drupal/issues/3328652.

Currently, [`backdrop_http_request()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_http_request/1) supports only the following HTTP codes.

- 100 => Continue
- 101 => Switching Protocols
- 200 => OK
- 201 => Created
- 202 => Accepted
- 203 => Non-Authoritative Information
- 204 => No Content
- 205 => Reset Content
- 206 => Partial Content
- 300 => Multiple Choices
- 301 => Moved Permanently
- 302 => Found
- 303 => See Other
- 304 => Not Modified
- 305 => Use Proxy
- 307 => Temporary Redirect
- 400 => Bad Request
- 401 => Unauthorized
- 402 => Payment Required
- 403 => Forbidden
- 404 => Not Found
- 405 => Method Not Allowed
- 406 => Not Acceptable
- 407 => Proxy Authentication Required
- 408 => Request Time-out
- 409 => Conflict
- 410 => Gone
- 411 => Length Required
- 412 => Precondition Failed
- 413 => Request Entity Too Large
- 414 => Request-URI Too Large
- 415 => Unsupported Media Type
- 416 => Requested range not satisfiable
- 417 => Expectation Failed
- 500 => Internal Server Error
- 501 => Not Implemented
- 502 => Bad Gateway
- 503 => Service Unavailable
- 504 => Gateway Time-out
- 505 => HTTP Version not supported

The 429 code will be changed to 400, from the following code, which means modules will never know there have been too many requests.

```php
// RFC 2616 states that all unknown HTTP codes must be treated the same as the
// base code in their class.
if (!isset($responses[$code])) {
  $code = floor($code / 100) * 100;
}
$result->code = $code;
```

400 is a more generic code; modules cannot assume it means too many requests have been done.

`backdrop_http_request()` should support also the 429 HTTP code.

**Comment by herbdool** [comment]
This looks good to me.

**Comment by klonos** [comment]
I'm in favor of this too 👍🏼 ...simple 1-line change. It matches the respective change in Drupal, and it makes sense.

**Comment by quicksketch** [comment]
Thanks @kiamlaluno! I have run into this particular HTTP response code a lot with Google's APIs, so it will be great to get it supported. Thanks @klonos and @herbdool for reviewing! I merged https://github.com/backdrop/backdrop/pull/4745 into 1.x and 1.27.x

**Comment by quicksketch** [comment]
Change record published here: https://docs.backdropcms.org/change-records/429-too-many-requests-support

**Comment by klonos** [comment]
Sorry. Tiny follow-up PR that adds an `@since` to the docblock of `backdrop_http_request()`: https://github.com/backdrop/backdrop/pull/4751

**Comment by kiamlaluno** [comment]
I apologize: I was meant to ask in which release the change would be present, to then add a `@since` tag, bug I completely forgot about this.

**Comment by quicksketch** [comment]
Thanks @klonos and @kiamlaluno! We missed this documentation addition and so it did not make it into 1.27.2, but it is now in the 1.28.x branch (what will be 1.28.1). I'm leaving this issue in 1.27.2 since that's where the code was fixed, it's only the missing documentation that will be in 1.28.x only.
