### ISSUE TITLE
'menu_custom' table no longer exists, using config instead

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#653]
tagging for change records. feel free to close

**Comment by quicksketch** [comment]
@docwilmot++

Thanks!

**Comment by klonos** [comment]
...I believe this was closed by accident. There still is no record of this in https://api.backdropcms.org/change-records

**Comment by quicksketch** [comment]
Doc has been going through the closed issues tagged with needs change notice, then marks them "has change notice" when completed. So right now we work with both open or closed issues that need change notices. Works either way. :smile:
