### ISSUE TITLE
Fixed: Ignore the contents of `core/modules/ckeditor5/lib/ckeditor5` directory for CSpell.

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6536]
In a previous issue, #6521, I proposed to ignore all the files contained in the *core/modules/ckeditor5/lib/ckeditor5/build/* directory because CSpell complained about words contained in automatically-built files, which should not be manually edited, not even to fix those typos CSpell could report.

That has been already fixed, but on the [4318](https://github.com/backdrop/backdrop/pull/4318#issue) pull request, [CSpell reported these errors](https://github.com/backdrop/backdrop/actions/runs/9042833189/job/24849824543?pr=4318) (lines from 35 to 39 included).

```none
core/modules/ckeditor5/lib/ckeditor5/LICENSE.md:16:33 Unknown word (Wolt)
core/modules/ckeditor5/lib/ckeditor5/LICENSE.md:17:111 Unknown word (Junon)
core/modules/ckeditor5/lib/ckeditor5/LICENSE.md:19:128 Unknown word (Ashkenas)
core/modules/ckeditor5/lib/ckeditor5/LICENSE.md:23:41 Unknown word (Serhii)
core/modules/ckeditor5/lib/ckeditor5/LICENSE.md:23:48 Unknown word (Kulykov)
```

Since that file cannot be manually edited for the same reasons, and since *core/modules/ckeditor5/lib/ckeditor5/LICENSE.md* and *core/modules/ckeditor5/lib/ckeditor5/build/* are the only files/directories contained in the *core/modules/ckeditor5/lib/ckeditor5/* directory, I propose to let CSpell ignore all the content of the the *core/modules/ckeditor5/lib/ckeditor5/* directory.

**Comment by kiamlaluno** [comment]
All checks have passed.

**Comment by klonos** [comment]
Thanks @kiamlaluno 🙏🏼 ...RTBC 👍🏼

**Comment by laryn** [comment]
Thanks (again) @kiamlaluno and @klonos -- merged into `1.x`.
