### ISSUE TITLE
Add jQuery version usage to telemetry data.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6537]
This was discussed during the dev meetings a few times recently. Lets add a metric on jQuery, to help with any decision-making in the future.

**Comment by klonos** [comment]
PR here: https://github.com/backdrop/backdrop/pull/4748

**Comment by quicksketch** [comment]
Tested and confirmed the correct Telemetry data is returned, including the full jQuery version number. Thank you @klonos! I merged https://github.com/backdrop/backdrop/pull/4748 into 1.x and 1.27.x.

**Comment by klonos** [comment]
FTR, I've already added the necessary configuration in https://backdropcms.org/project/backdrop/telemetry on the b.org side of things so that we can start gathering metrics soon as people install a version of Backdrop that includes this change 😉
