### ISSUE TITLE
Update jQuery UI to latest 1.13.3

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6550]
## Description of the task

A new version of jQuery UI has been released in April.

https://blog.jqueryui.com/2024/04/jquery-ui-1-13-3-released/

The changelog: https://jqueryui.com/changelog/1.13.3/

And they also prepare for a 1.14 release, a beta-1 version is out for early testing: https://blog.jqueryui.com/2024/05/jquery-ui-1-14-0-beta-1-released/ We won't update to the beta, but keeping an eye on it, seems appropriate. Especially, as they stated that "Support for jQuery UI 1.13 will end on the day jQuery UI 1.14.0 is released." in the other [blob post](https://blog.jqueryui.com/2024/04/plans-for-jquery-ui-1-14-dropping-support-for-ui-1-12-in-the-download-builder/).

UPDATE: it happened, [1.14.0 is out](https://blog.jqueryui.com/2024/08/jquery-ui-1-14-0-released/)

We're currently on 1.13.2, so the changes should be fairly minimal, anyway. But it still needs testing, particularly our dialogs and draggable/droppable usage.

# Testing jQuery UI functions in Backdrop:

See: https://github.com/backdrop/backdrop-issues/wiki/jQuery-UI:-Checklist-for-manual-tests

### Blocks 
- [x]  Added a custom block
- [x]  Moved another block

### Field UI
- [x]  Changed the order of fields on one of the Manage Display pages

### Layout UI 
- [x]  for path node/% does context appear automatically?
- [x]  drag and drop blocks
- [x]  Added a custom block
- [x]  Moved another block

### CKEditor
- [x]  link dialog
- [x]  image dialog
- [x]  Configuration: Added buttons to the editor toolbar
- [x]  Sortable
- [x]  Draggable

### Elements 
- [x]  autocomplete

### Views UI

- [x]  Added a view
- [x]  Changed to the display of fields
- [x]  Modal windows
- [x]  Rearranged the fields

### Weight 
- [x]  draggable
- [x]  droppable

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4756) is available for testing and review.

To get an idea, what to test, take a look at the issue description there: #5401 
jquery.ui's widely used in core and also in contrib, checking core should be sufficient this time, as 1.13.3 is only a patch release.

As usual with "uglified" js code, review will be a cumbersome task.

**Comment by quicksketch** [comment]
I tested all the core use-cases from https://github.com/backdrop/backdrop-issues/issues/5401 and added them to the issue summary. This looks good!

**Comment by indigoxela** [comment]
Rebased, just in case someone wants to take a final look in the sandbox.

**Comment by indigoxela** [comment]
And rebased again, just in case someone needs the sandbox... :wink:

**Comment by indigoxela** [comment]
I just saw that 1.14.0 is out. But instead of updating this already tested PR with latest 1.13, I'd rather open a new issue for 1.14. I read some "breaking change" warnings, that warrant closer inspection.
