### ISSUE TITLE
Views access notice

### ISSUE THREAD

**Issue by sirkitree** [backdrop/backdrop-issues#656]
I have a few views in my system and they're generating a notice that I've yet to be able to track down.

Notice: Undefined index: node in views_handler_field_field->access() (line 127 of [...]/docroot/core/modules/field/views/views_handler_field_field.inc).

I'll try to track down which view is causing this...

**Comment by sirkitree** [comment]
This was a mistake on my part. I had a view that was referencing a field on a content type that had been removed.

**Comment by quicksketch** [comment]
Sweet. Thanks for the followup!
