### ISSUE TITLE
Telemetry: Allow people to select which data they want to share (all by default if the module is enabled)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6571]
Some concerns have been raised in #5186 about the amount of telemetry data we are collecting. Perhaps we are collecting too much. Perhaps there are certain types of data that people do not feel comfortable sharing. We should allow people to share metrics with more confidence.

How about we convert the table in `admin/reports/telemetry` into a tableselect, so that people can choose what they want to (not) report back?

**Comment by klonos** [comment]
@indigoxela and @findlabnet I think that you will like this 🙂

**Comment by indigoxela** [comment]
@klonos I totally appreciate your ambition to make us/me happy. :heart: It's just... a little off topic (adding a checkbox matrix might not be as appealing to contribute to Telemetry as you hope...).

And it doesn't really address my initial concern re collecting "arbitrary data without good reasons". :wink: 

Can we please close this issue? (There are enough other open issues...)

**Comment by findlabnet** [comment]
> (There are enough other open issues...)

 https://github.com/backdrop/backdrop-issues/issues/created_by/klonos

**Comment by klonos** [comment]
> Can we please close this issue? (There are enough other open issues...)

Well, I opened this issue here because I don't want to derail all the other issues about telemetry implementations with discussions about "too much data collection is not ethical" etc. If people raise these concerns in the other issues, I would like to have something to point them to instead of sidetracking progress on those issues. Especially when these issues have already been discussed in dev meetings and there is agreement to gather that data.

@findlabnet if you watch the dev meetings, you will see that many times people say "Klonos, can you please create an issue for that?" ...you might also want to focus on this list of issues:

- https://github.com/backdrop/backdrop-issues/issues?q=is%3Aissue+sort%3Aupdated-desc+author%3Aklonos+label%3A%22status+-+fixed%22+is%3Aclosed
- https://github.com/backdrop/backdrop-issues/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22status+-+fixed%22+is%3Aclosed+author%3Afindlabnet

**Comment by kiamlaluno** [comment]
IMO, given that the gathered data is equally important (for one or another reason), choosing not to transmit all the data is like disabling the Telemetry module.  
On the case that 40% of the sites with the Telemetry module enabled decide to transmit the used PHP version, that information becomes useless as it could not show which PHP version is effectively the most used.

**Comment by indigoxela** [comment]
> Well, I opened this issue here because I don't want to derail all the other issues about telemetry implementations with discussions about "too much data collection is not ethical" etc.

@klonos Not "too much data", but data not relevant for decisions. I belief, that's an important difference.

Providing a detailed matrix for turning individual telemetry items off seems like an odd idea to me. And actually counter-productive. What if we just ask for info we actually need? :wink: 

> How about we convert the table in admin/reports/telemetry into a tableselect, so that people can choose what they want to (not) report back?

Is that an actual question, or will saying "no, IMO a bad idea..." just result in even more opened issues and a lengthy discussion with 5+ external links with (more or less unrelated) pages to read? :laughing: You know, just asking in advance... :speak_no_evil:

**Comment by klonos** [comment]
It is an actual question. Since concerns have been raised about the amount of data we collect, and the possibility that collection of certain of that data might be considered unethical or too much, then that method could potentially alleviate these concerns (because it would giev additional control to the site owners of what they share).

For example, this was not taken into account when we implemented telemetry for installation profiles, so our https://backdropcms.org/project/backdrop/telemetry page shows the following:
- custom
- freeform_base
- minimal
- triplo
- standard

Since I don't see `freeform_base` nor `triplo` in https://github.com/backdrop-contrib, I'm assuming that these are custom installation profiles; however, they are listed individually instead of being merged into the "custom" metric. So either the logic we have in place is flawed and reporting these by name instead of "custom", or `custom` is an actual name of a custom installation profile, or something else is going on. Either way, if people realize that they are reporting potentially sensitive information (the names of custom installation profiles can potentially reveal the name of the site, which should not be happening), then they could select to exclude that from the report. That should give people more confidence.

Besides, we should be considering the potential of abuse here as well (consider for example the case where some offensive word/phrase was intentionally used as the name of an installation profile - we don't want that on the borg site).

**Comment by klonos** [comment]
> Is that an actual question, or will saying "no, IMO a bad idea..." just result in even more opened issues and a lengthy discussion with 5+ external links with (more or less unrelated) pages to read? 😆 You know, just asking in advance... 🙊

Well, the previous comment was my serious reply. If we are going for sarcasm, then will actually answering your question result in less offensive comments or am I wasting my time?

**Comment by indigoxela** [comment]
> if people realize that they are reporting potentially sensitive information..., then they could select to exclude that from the report. That should give people more confidence.

The thing is: we shouldn't *collect* such data in the first place. People should have confidence, because all data we collect are anonymous and we have a clear purpose for the data - to make informed development decisions.

On the other hand, collecting data we don't need, or data that expose potentially sensitive information, then leave it to site admins to visit a page full of checkboxes and force them to spend time to figure out, what might be "sensitive" and what they need to uncheck...
To me that means, we _expect them to fix a problem we introduced_ and could easily fix (and should!), but for some reason don't fix. And I really mean collecting, not displaying.

So, again, I don't think, this tableselect is the way to go. IMO it's not the proper solution.

**Comment by indigoxela** [comment]
> If we are going for sarcasm, then will actually answering your question result in less offensive comments or am I wasting my time?

It wasn't supposed to be sarcasm. Slight irony, but not supposed to be offending.
Obviously I failed to find the proper tone and I apologize.

**Comment by bugfolder** [comment]
> leave it to site admins to visit a page full of checkboxes and force them to spend time to figure out, what might be "sensitive" and what they need to uncheck...

Yeah, this is sounding a bit like the popups I seem to encounter on every site these days asking me to read a bunch of tiny-print information and make a bunch of selections about data-sharing before I can see the page. (It's not the same thing, I know, but it resonates.) We're asking site admins to turn on telemetry for our benefit. Asking them to think about and decide on a bunch of different settings seems likely to result in a lot of "wading through this isn't worth my time, I'll just turn this thing off." We should keep it simple for the site admin and err on the side of privacy.

**Comment by klonos** [comment]
Fair enough. I'll close this off then. I can still point people to another issue for any discussion of whether certain data is either unethical to be collected or not useful etc. (perhaps #5231 is the right place - not sure 🤔).
