### ISSUE TITLE
[DX][META] Allow more SVG elements in `theme_icon()`.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6576]
While working in #6487, I discovered that `theme_icon()` is currently not allowing the use of `<line>` elements in SVGs (they were being stripped out), while it is for example allowing `<path>`, `<circle>`, `<rect>` etc.

Not sure whether we should allow every supported element, but it surely is very restrictive as it is now.

The complete list of allowed elements can be found here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element

We should at the very least allow the [Basic shapes](https://developer.mozilla.org/en-US/docs/Web/SVG/Element#basic_shapes) elements as a start: `<circle>`, `<ellipse>`, `<line>`, `<polygon>`, `<polyline>`, `<rect>`.

**Comment by klonos** [comment]
I'm turning this issue here into a meta, but for starters I would like to unblock my PR for #6487. So I will work on an initial PR that allows [Basic shapes](https://developer.mozilla.org/en-US/docs/Web/SVG/Element#basic_shapes).

**Comment by klonos** [comment]
Here's a PR that allows all basic svg elements: https://github.com/backdrop/backdrop/pull/4796

The additions are: `<ellipse>`, `<line>`, `<polygon>` and `<polyline>`.

**Comment by klonos** [comment]
...you can test this by trying to load this svg icon:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 150" stroke="currentColor">
  <line class="header" x1="0" y1="7" x2="100" y2="7" stroke-width="15"/>
  <line class="header" x1="0" y1="27" x2="100" y2="27" stroke-width="15"/>

  <line x1="0" y1="75" x2="29" y2="75" stroke-width="70"/>
  <line class="main" x1="34" y1="75" x2="66" y2="75" stroke-width="70"/>
  <line x1="71" y1="75" x2="100" y2="75" stroke-width="70"/>

  <line class="footer" x1="0" y1="123" x2="100" y2="123" stroke-width="15"/>
  <line class="footer" x1="0" y1="143" x2="100" y2="143" stroke-width="15"/>
</svg>
```

**Comment by klonos** [comment]
Sure @yorkshire-pudding (and thanks for taking the time to review/test 🙏🏼 )

1. Follow the link I provided in my previous comment, and save the file on your computer. Give it a convenient name, such as `test.svg`.
2. On a demo/vanilla Backdrop site, without the PR changes, upload the .svg you have saved earlier. You can do that via the "Add file" form at `file/add`.
3. View the saved file entity. and inspect its URL/path. It should be something like `.../files/test.svg`.
4. Install and enable the Devel module.
5. Go to `admin/devel/php` and paste the following code ():
   ```php
   $variables = array(
     'name' => 'test',
     'path' => 'files/test.svg',
   );

   $icon = theme_icon($variables);
   dpm($icon);
   ```
6. Execute the code, and compare the output to the actual code of the .svg file (either by opening it with a text editor on your local computer, or refer to the code snippet in my previous comment)

The result should be a broken svg with nothing but the `<svg>` opening/closing tags and the respective attributes - all the rest of the contents (`<line>` tags) of the file should be stripped out and blank lines/whitespace left in their place:
```
<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 100 150" stroke="currentColor" aria-hidden="true" class="icon icon--test">
  
  

  
  
  

  
  
</svg>
```

Unfortunately, our PR sandboxes have stopped allowing installation of contrib modules, so you will need to apply the PR changes on your local and repeat the same process as above. At the end of the process, the contents of the file should have now been preserved.

Please let me know if you have any questions.

**Comment by yorkshire-pudding** [comment]
Thanks @klonos - that works a treat for testing.  I confirm that the shapes are stripped out before, but kept in once the PR diff is applied.  I also confirm from my knowledge of SVGs that all these elements are appropriate for icons.

Works for me, RTBC.  Also, extra marks for fixing a typo in the same PR! ⭐

**Comment by quicksketch** [comment]
Thanks @klonos and @yorkshire-pudding! Nice clean code and well explained testing. I merged https://github.com/backdrop/backdrop/pull/4796 into 1.x and 1.28.x. Thank you both!

**Comment by herbdool** [comment]
@klonos please create a follow-up instead of reopening issues. It's confusing to track this way.

**Comment by klonos** [comment]
FTR: I created #6641 as a follow-up.
