### ISSUE TITLE
[DX] Support EditorConfig for better coding standards.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#658]
[EditorConfig](http://editorconfig.org)
- [ ] add a `.editorconfig` in the root directory
- [ ] make appropriate configuration (`indent_style = space`, `indent_size = 2`)
- [ ] write/adjust developer/contrib documentation

---
PR by @klonos: https://github.com/backdrop/backdrop/pull/1796

**Comment by quicksketch** [comment]
Hi @klonos, thanks for making this issue. I expressed some concerns when editorconfig was added to Drupal 8, because at the time, there was not a single editor that actually supported the format natively. Of course you can get plugins for a lot of editors, but if it's not native, it's not particularly helpful.

Since then, at least PHPStorm has added native support in the newest versions, so users will get some immediate benefit. I've also encountered an issue regularly where our JSON files are tabbed with 4 spaces, but everything else is 2, and that's because PHP 5.4+ has a "pretty print" option in json_encode(), but there's no ability to adjust the number of spaces (that I've found). This results in some inconsistent rules around spacing that we didn't have previously, and potentially editorconfig could help with that.

I'm still not super-keen on editorconfig in the event that more text editors do not adopt it, but now that it has at least a little momentum, it may be worth the additional clutter to our root directory.

**Comment by klonos** [comment]
In the spirit of closing old issues (opened by me before I knew how to file PRs), PR up for review.

> I'm still not super-keen on editorconfig in the event that more text editors do not adopt it, but now that it has at least a little momentum, it may be worth the additional clutter to our root directory.

@quicksketch: http://editorconfig.org/#download

**Comment by serundeputy** [comment]
@klonos 

for the record you can check against coding standards with `phpcs` here is a composer file you can throw in the root of any Backdrop site: https://github.com/thinktandem/my-kb-bd/blob/kb-bd-flow/composer.json

Once you have that just run composer install and then you can run `composer test` to run your code checks and linting.

I have it configured to check only the `modules/custom` directory, but you can of course change that.

So my 2¢ is that this does not meet the 80% use case and those of us that need it can either put the file in ourselves or accomplish with other methods like phpcs, but I'm not passionate either way.

Just putting the info out there.

**Comment by quicksketch** [comment]
I'm on the fence about this. We could use some more opinions here.

**Comment by quicksketch** [comment]
(PR looks great though)

**Comment by jenlampton** [comment]
Hm. I'm concerned about people's editors reformatting .json files. Is there a way to specify one format for php files, and another for .json so those files remain untouched?

This seems like a good idea in general, but I don't feel it benefits enough of our community (yet) to be included in core. I'd feel more comfortable if we could wait and see if/when this standard is adopted by other editors. Adding a PHPStorm-specific feature seems like an overreach.

**Comment by klonos** [comment]
>Hm. I'm concerned about people's editors reformatting .json files. Is there a way to specify one format for php files, and another for .json so those files remain untouched?

Check out the PR 😉 https://github.com/backdrop/backdrop/pull/1796/files ...you'll see how it's `indent_size = 2` for all files, while it's `indent_size = 4` for .json and `indent_style = tab` for `core/misc/ckeditor/**.js`, `core/misc/smartmenus/**.js` and `core/misc/ui/**.css`.

**Comment by jlfranklin** [comment]
> Adding a PHPStorm-specific feature seems like a bit of an overreach at this time.

- If it were an editor-specific tool, I'd agree.  Based on the list of supporting editors on [editorconfig.org](http://editorconfig.org/#download), this seems to be well on its way to a defacto standard.  It's not just PHPStorm, but a pretty wide selection of modern editors.

- We already have a precedent for adding development-focused files, such as .gitignore.

- For those who don't use one of the supporting editors, it clearly documents how to handle whitespace in the files.

- For those who do, the .editorconfig makes it easy to use the proper whitespace settings for just Backdrop projects, and default to other settings for non-Backdrop projects.

- It may mess up minified JS files, but I'm sure there's a way to exclude them in the rules.

The .editorconfig file has a lot of benefits and hidden-file clutter is the only downside I can see.  I think it's worthwhile.

**Comment by quicksketch** [comment]
Thanks for all the feedback.
> It may mess up minified JS files, but I'm sure there's a way to exclude them in the rules.

I don't think it will, it would only reformat the files if you opened them and edited them, which is already unlikely for a minified file. Plus after it's minified it's had its tabs/spaces removed, so there's nothing to affect anyway.

---

@jlfranklin lays out the points well. The reasoning is solid and we gain overall here.

And so I've merged https://github.com/backdrop/backdrop/pull/1796 into 1.x for 1.7.0.
