### ISSUE TITLE
file_display_form() shows as options formatters without a view callback for which file_view_file() shows a link to the file

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#6580]
[`file_view_file()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21file%21file.module/function/file_view_file/1) checks a file formatter defines a view callback; it shows a file link, if the view callback is not defined.

```php
if (isset($formatter_info['view callback']) && ($function = $formatter_info['view callback']) && function_exists($function)) {
  if (!empty($formatter_info['default settings'])) {
    if (empty($display['settings'][$formatter])) {
      $display['settings'] = array();
    }
    $display['settings'][$formatter] += $formatter_info['default settings'];
  }
  $display_info = array(
    'type' => $formatter,
    'settings' => isset($display['settings'][$formatter]) ? $display['settings'][$formatter] : array(),
  );
  $element = $function($file, $display_info, $langcode);
}

// As a last resort, fall back to showing a link to the file.
if (!isset($element)) {
  $element = array(
    '#theme' => 'file_link',
    '#file' => $file,
  );
}
```

[`file_display_form()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21file%21file.admin.inc/function/file_display_form/1) does not check that, with the result that users who can access file-display for each file bundle will be asked to choose between formatters that just show a file link.

Instead of giving the choice between different formatters that fallback to showing the file link, formatters without a view callback should not be given as option. The formatter that shows a file link should be one of the options, if that does not already happen.

**Comment by klonos** [comment]
Thanks @kiamlaluno 🙏🏼 ...the code looks good, and the logic makes sense as well. So RTBC 👍🏼

**Comment by quicksketch** [comment]
Makes sense to me too. Thanks @kiamlaluno and @klonos! I merged https://github.com/backdrop/backdrop/pull/4773 into 1.x and 1.28.x.
