### ISSUE TITLE
file_display_form() does not allow translators to provide the correct translation for the formatter settings title

### ISSUE THREAD

**Issue by kiamlaluno** [backdrop/backdrop-issues#6581]
[`file_display_form()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21file%21file.admin.inc/function/file_display_form/1) contains the following code.

```php
if (!empty($settings_form)) {
  $form['display']['settings'][$name] = array(
    '#type' => 'fieldset',
    '#title' => check_plain($formatter['label']) . ' ' . t('settings'),
    '#parents' => array('display', 'settings', $name),
    '#group' => 'display_settings',
    '#states' => array(
      'visible' => array(
        ':input[name="display[formatter]"]' => array('value' => $name),
      ),
    ),
  ) + $settings_form;
}
```

`check_plain($formatter['label']) . ' ' . t('settings')` does not allow translators to provide the correct translation for the formatter settings title.  
It asks translators to provide a translation for *settings*, but that is different from the translation of *`@label` settings*. In fact, in Italian I would translate *settings* with *impostazioni*, but I would translate *`@label` settings* with *Impostazioni per `@label`*. In French, the translation of *`@label` settings* would probably be *Paramètres de `@label`*, in Spanish *Configuración de `@label`*, in Greek *Ρυθμίσεις `@label`*.

Instead of concatenating a string with a translatable string, the code should use a translatable string where the label is added with a placeholder.

**Comment by klonos** [comment]
Thanks @kiamlaluno 🙏🏼 ...RTBC 👍🏼

**Comment by quicksketch** [comment]
Excellent, love these little fixes. Thanks @kiamlaluno and @klonos! I merged https://github.com/backdrop/backdrop/pull/4772 into 1.x and 1.28.x.
