### ISSUE TITLE
Add new file type icon views field handler.

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6588]
## Description of the need

While recently playing with a new module, I realized how nice our new icons would be to use in views.

## Proposed solution

A simple views handler for file_managed data.

## Alternatives that have been considered

Could also go to contrib, of course, but I belief, this belongs to core.

We're currently not using the new API much. So, let's start.

## Additional information

This is a screenshot to demo the intended use of such a views handler:

![nice-icon-display](https://github.com/backdrop/backdrop-issues/assets/842066/044de3f1-6171-4ff1-98c1-33c1e3848f90)

Simply by selecting a views field via views admin UI.

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes a views handler to automatically display an icon based on file extension.

---

## Translaion update

New strings
- An SVG icon according to file extension
- Inline SVG markup
- Inline SVG images are usually more efficient and easier to style.
- Regular images
- Regular image tags can be more efficient when showing the same icon many times.
- Add alternative text
- If alternative text is omitted, this icon will be marked as decorative only.
- File icon for @extension extension

**Comment by laryn** [comment]
@indigoxela It is possibly there, but hidden. If you have this open and easily testable try this:

> add a "File: Mime type" field and then check the checkbox Display an icon representing the file type, instead of the MIME text (such as "image/jpeg").

**Comment by indigoxela** [comment]
A quick [PR](https://github.com/backdrop/backdrop/pull/4778). Be warned in the views admin UI the icons display gets mangled, see also https://github.com/backdrop/backdrop-issues/issues/6585

**Comment by indigoxela** [comment]
> It is possibly there, but hidden.

@laryn that's by mime type only and quite dated, too. Phosphor icons provide a lot more to differentiate:

![icons-compare](https://github.com/backdrop/backdrop-issues/assets/842066/09c14dc0-7c0e-49b7-ae13-61de3fd1e99a)

Anyway, we have time until September to decide on this. :wink:

**Comment by indigoxela** [comment]
Here the size setting for the icon:
![icon-setting-views-field](https://github.com/backdrop/backdrop-issues/assets/842066/fd335dd0-44e7-427f-ab70-5d1c5b8d9609)

**Comment by klonos** [comment]
I like this idea @indigoxela 👍🏼 ...thanks for starting this and for providing a PR 🙏🏼 

As a note, I would like us to incorporate the outcome of this in issues like #2718 and #6512.

**Comment by indigoxela** [comment]
> ...I've reviewed and left some comments in the PR.

Many thanks for your feedback and hints. Bear with me, it might take a little time until your requests get addressed - we first need to figure out, if we actually _want_ this feature. :wink: It's a candidate for next September.
Just wanted to quickly provide my idea, so I don't forget it (I usually delete "foobar" modules and this code was part of such a try-out-and-forget module :grin:)

**Comment by indigoxela** [comment]
Here we go, requested changes done.

One notable difference: I didn't change the string to "File type icon" - for good reasons.

The term "File type" is pretty misleading, as it suggests it relates to admin/structure/file-types, which isn't the case. It's based on file extension, not File (entity) type.

If using the string, things look odd on admin UI:
![odd-string-label](https://github.com/backdrop/backdrop-issues/assets/842066/151ea528-e349-432f-9b2f-d1b204d31c82)

"File: File type icon (Icon)" seems really odd to me, and initially (with the label automatically set) it would even result in "File: File type icon (File type icon)". :stuck_out_tongue_winking_eye: Ehm.... better not.

**Comment by indigoxela** [comment]
As the newly added views handler's currently the only way to see the problem described in #6585, I went ahead and added the fix to the PR here. The change is minimal.

Of course, I can create a separate PR for the other issue, but then nobody's able to test it.

What do you folks think? Combine or keep separate?

**Comment by indigoxela** [comment]
Rebased and added a new feature to toggle between img an svg display.

**Comment by klonos** [comment]
> What do you folks think? Combine or keep separate?

I'd say if they are related and the other change is trivial/minimal and hard to test without the rest of the changes here, then lets keep everything in a single PR and deliver a more complete solution.

Curious to see what others think though.

**Comment by indigoxela** [comment]
Labels and fallback logic slightly updated.

![icon-views-ui-form-item](https://github.com/backdrop/backdrop-issues/assets/842066/5808107c-65e1-407a-9fdb-0a7f585ce9a9)

**Comment by indigoxela** [comment]
Time for a rebase - a fresh sandbox is waiting for players... :wink:

**Comment by klonos** [comment]
@indigoxela would you like to please add yourself as the advocate for this feature request, so that we can add the milestone for 1.29.0?

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼 ...very well-thought code, so marking it RTBC 👍🏼 ...I did leave a couple of comments for consideration in the PR though.

**Comment by indigoxela** [comment]
> please add yourself as the advocate for this feature request...

Oops, I didn't know that I have to do that. Hm... where's that documented? Obviously I'm not quite up to date with our advocate workflow.

Re setting a milestone: I'd actually suggest to wait for some feedback - if anyone really finds this feature beneficial and has a use-case for that. :wink:

**Comment by klonos** [comment]
@indigoxela here's the policy around setting milestones: https://docs.backdropcms.org/documentation/adding-milestones-to-issues

You need to add a note at the bottom of the issue summary, saying that you are advocating for this feature request. Then you can remove the `milestone candidate` label that I have added, and add the actual milestone (it needs to be different people that do these actions for minor release milestones).

I obviously find this to be a useful feature.

> Of course, this may need updating to use the new icons!

@laryn sorry, I missed that comment of yours. This will need to be a separate issue I believe.

**Comment by indigoxela** [comment]
To clarify, I'd not recommend to *change* the existing mime based views handler views_handler_field_file_filemime.inc

1. It already exists and is (presumably) in use, so changing it will change the display of existing views results
2. It has no size option, adding that would require possibly complex data updates or at least considerations in code
3. For the same reason we couldn't add a switch between image and svg
4. It uses a theme function (theme_file_icon), which may already be overridden in themes - so switching seems like a breaker
5. It's based on mime, that's less icons, basing on file extension allows a lot more

All these are (bc) problems we might run into, if adapting an existing views handler, but adding a new (additional) one doesn't have these problems. Hence a completely new handler is the way to go IMO. If someone wants it, anyway. :wink:

**Comment by laryn** [comment]
I like this @indigoxela and I've done some testing which worked nicely. Here's one example of a quick test I did:

![CleanShot 2024-08-17 at 09 03 07@2x](https://github.com/user-attachments/assets/58bda0ff-da20-46b7-a933-2550395f3de2)

I probably wouldn't use this actual implementation but it does highlight one case where alt text could be useful for accessibility. Often icons are purely decorative, in which case an empty alt is correct, but in this case it could be argued that the icon provides more information than is available without it (Instead of just "Image" it also communicates the file extension of the image). 

A few thoughts there:

 - Is it too much clutter to add a checkbox saying "Add the extension in the alt text" (phrased better, but you get the idea)?
 - ~What do you think about providing an additional token in the rewriting section for the actual extension? `[icon--extension] == Raw file extension`~ I guess we already have a file extension token available separately...

**Comment by indigoxela** [comment]
@laryn many thanks for giving it a try.

Hm... a checkbox to toggle the alternative text on/off. :thinking: That might eventually work. IIRC everything we need is already there.
I'll have a look.

**Comment by indigoxela** [comment]
PR updated, there's now a checkbox for alt text:
![form-item-with-alt](https://github.com/user-attachments/assets/2e3d15ff-8d4e-4c80-90fb-740858077465)

**Comment by stpaultim** [comment]
![image](https://github.com/user-attachments/assets/da56fa55-1f2c-4f83-b37f-ea9b95dea22c)

In this example, do we simply not have icons available for some file types such as webp and gif?
If not, does it make sense to add them, if we're adding this feature?
Is a bit a bit weird to NOT have icons for some pretty common types of images?

This feels like a nice feature for core to me. But, I don't feel too strongly about it.

**Comment by indigoxela** [comment]
> If not, does it make sense to add them, if we're adding this feature?
> Is a bit a bit weird to NOT have icons for some pretty common types of images?

Well, the Phosphor icons don't contain that (yet). Modules or themes can add icons any time via [our API](https://docs.backdropcms.org/documentation/icon-api), though.
There's also an [open issue in their queue](https://github.com/phosphor-icons/homepage/issues/500).

> This feels like a nice feature for core to me. But, I don't feel too strongly about it.

At least, no objection. :grin: 

Is the absence of a webp icon a show stopper for you @stpaultim?

**Comment by stpaultim** [comment]
> Is the absence of a webp icon a show stopper for you @stpaultim?

No, I don't see this as a blocker. The issue was to provide a views hander and this PR does that. If there is anything we can do to help get the needed icons in Phpsphor, that would be make this better. Or if necessary to find alternatives icons and add them to core, because they are very specific with clear use case.

These just seem like relatively easy icons to generate, so it seems like something to explore. But, no I don't consider this a blocker.

**Comment by laryn** [comment]
Tested the checkbox for the accessibility text and it works nicely. I think that provides a nice level of flexibility -- thanks!

**Comment by olafgrabienski** [comment]
>> PR updated, there's now a checkbox for alt text:

> Tested the checkbox for the accessibility text and it works nicely.

If I didn't miss anything, the "Add alternative text" option has only effect on 'Regular images' but not on 'Inline SVG markup'. Ah, wait, for SVG images it's a `title` element. Hm, maybe it's okay to call that however "alternative text", because it's a equivalent? I'm not an expert for this. What do others think?

**Comment by laryn** [comment]
I tend to think it's okay. [This page](https://www.w3.org/WAI/tutorials/images/tips/) uses a slight variation the phrase: "text alternative". It feels like a lot of words to say "Add a text alternative to describe the icon for screen readers." but maybe it's slightly clearer?

**Comment by olafgrabienski** [comment]
Yes, that's quite long, but definitely clearer. Personally, I like it.

**Comment by indigoxela** [comment]
We can also use the form item description - for the longer explanation.

Example:

- Title: Text alternative
- Desc: Adds a text alternative to describe the icon for assistive tools like screen readers.

We could refine that suggestion, of course.

**Comment by quicksketch** [comment]
Code-wise looks pretty good. Two items:

- We can use a generic way to get image/video/etc by using the existing mime-type map. See https://github.com/backdrop/backdrop/pull/4778#pullrequestreview-2276144769.
- Needs test coverage.

**Comment by quicksketch** [comment]
I'll work on adding test coverage unless there's someone else who has availability. Let's see if we can get this into 1.29.0

**Comment by quicksketch** [comment]
I reworked the description and display options slightly ([see previous screenshot](https://github.com/backdrop/backdrop-issues/issues/6588#issuecomment-2295239775)).

![image](https://github.com/user-attachments/assets/17f7d1d1-e50a-44dc-a85d-d5e6bd525e1e)

- Added description text
- Clarified what "Regular image" means by phrasing it as `Regular <img> tag` vs `Inline <svg> tag`.

And tests now cover adding this type of field and verify the output, including the tag type, alt text, and display size.

**Comment by stpaultim** [comment]
I did some additional testing. Looks good to me.

**Comment by jenlampton** [comment]
This is great. I love this feature. 

I tested the PR by adding an icon to the `admin/content/files` view and uploaded a bunch of different file types. Each got an icon <3. I tested both SVG and IMG tags, at various sizes, and I tested both with and without alternative text. 

When `Add alternative text ` is NOT checked, I'd prefer to see the attribute `aira-hidden="true"` added explicitly for both `img` and `svg` tags. The SVG does not have the equivalent of the implicit `alt=""`.

**Comment by quicksketch** [comment]
> When `Add alternative text` is NOT checked...

IMO that should be a separate issue, since it would apply everywhere we call `icon()` or `theme('icon')`.

**Comment by jenlampton** [comment]
I've created https://github.com/backdrop/backdrop-issues/issues/6700 to add the `aria-hidden` attribute to the `icon()` function, but we do need to do it here for the `img` tag:
`return '<img ' . backdrop_attributes($attributes) . '>';`

**Comment by quicksketch** [comment]
@jenlampton I updated the `<img>` output to add `aria-hidden` as requested. Icons are specifically listed as a likely situation where `aria-hidden` is desirable [according to MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden), so I think that's a good change.

I reverted the label changes based on @indigoxela's feedback (but left in place the new descriptions I added).

**Comment by indigoxela** [comment]
Wow, lots of activity here, all of a sudden. :astonished: Great progress! :+1: 

I'd like to continue our discussion for the admin form item labels and text - anything still pending.
But we can do that past feature freeze, no need to rush today. :wink:

**Comment by indigoxela** [comment]
The mime type as a second fallback is actually a cool idea, btw., many thanks for adding. :+1: And the aria-hidden makes lot of sense, too.

**Comment by jenlampton** [comment]
> I'd like to continue our discussion for the admin form item labels and text - anything still pending.

Me too, but maybe tomorrow :) Marking as RTBC 🎉

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4778 into 1.x for 1.29.0. Thank you @indigoxela for taking the lead on this issue! Thank you everyone that helped review and test!

https://github.com/backdrop/backdrop/commit/b19bede8636988b02b3bfa040f45f045aaf08d78 by @indigoxela, @laryn, @klonos, @quicksketch, @stpaultim, @jenlampton, and @olafgrabienski.

**Comment by jenlampton** [comment]
I have created https://github.com/backdrop/backdrop-issues/issues/6701 as a follow-up to work on language improvements :)
