### ISSUE TITLE
image_add_svg_attributes(): Use firstElementChild instead of firstChild

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6603]
The newly added function `image_add_svg_attributes()`, makes use of  class `DOMDocument` to create attribute markup for SVG images. This line and similar ones is found in this function:

```php
  $doc = new DOMDocument();
  $doc->loadXML($svg_content);
  // ...
         $doc->firstChild->prepend($title);
  // ...
        $doc->firstChild->setAttribute($attribute_name, $attribute_value);
```

While this work, my IDE is telling me that `firstChild` is a `DOMNode`  object, and doesn't define the methods   `setAttribute()`, `removeAttribute()` and `prepend()`. Instead, we should be using `firstElementChild` which will return  a `DOMElement` object, which contain those methods.

EDIT: the current code doesn't throw an error. This is a grammar error that "still works". But eventually this may change. So, regarding testing... there is nothing functional to test AFAIK.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4789 submitted.

**Comment by kiamlaluno** [comment]
On the PHP version I installed on my computer, `$doc->firstChild` is a `DOMElement` object. Since the documentation says that `$doc->firstChild` is a `DOMNode` object, the code should not assume differently.

**Comment by indigoxela** [comment]
@argiepiano there's an existing issue and PR for this "prepend". Have you checked that already? https://github.com/backdrop/backdrop-issues/issues/6577 Asking, because the tests fail with your PR.

**Comment by klonos** [comment]
What @indigoxela said ☝🏼 ...I've already tested the PR for #6577 in #6487 and it works.

**Comment by argiepiano** [comment]
I see. The solution there is different from mine. In the long run, I think that solution is riskier than this one. There is no way to assure that `firstChild` is really the first element of the document. The only way to assure this is by getting `firstElementChild`.

Plus that PR does not fix the rest of problem: the code even after the PR still tries to use methods `setAttribute` and `get Attribute` on a `DOMNode` object. According to the manual, those [methods](https://www.php.net/manual/en/book.dom.php) do not exist. 

Is there a way to perhaps merge my approach to yours in that PR, @indigoxela?

**Comment by indigoxela** [comment]
@argiepiano maybe we should start with joining the issues, so we don't have to discuss in two places. :wink:

You can simply attach your PR to the other issue (for direct comparison) and close this one as the duplicate (unless you insist in keeping it a separate issues).

But you should also get the automated tests running, which now fail with yours (for the reason described in the other issue).

**Comment by argiepiano** [comment]
Thanks, @indigoxela. I'll get to this tonight hopefully.

**Comment by argiepiano** [comment]
Closing this. I added a relevant comment to the other issue.
