### ISSUE TITLE
[DX] Allow specifying a default value with `config_get()` (same as with `state_get()` and `settings_get()`)

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6605]
See:
- [`state_get(state_get($name, $default = NULL))`](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_get/1)
  > `$default`: The default value to use if this state has never been set.
- [`settings_get($name, $default = NULL)`](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/settings_get/1)
  > mixed `$default`: (optional) The default value to use if this setting is not set.

We should have the same for `config_get()`. This should be a small API addition, but it would help reduce a lot of similar code in both contrib and core (all the conditionals that check if the config value was set and provide a fallback if not).

**Comment by docwilmot** [comment]
Config already has defaults; thats what the config file is for, and thats why `config_get()` didn't include it. Can't define defaults in two places.

**Comment by klonos** [comment]
@docwilmot that's based on the assumption that default config is provided + that that config includes an entry for the config value one is trying to retrieve with `config_get()`. This would be more like in-built, OOTB defensive coding.

**Comment by docwilmot** [comment]
But I think this is a reasonable assumption, that if you develop a module that uses config, you should create a config file to define your defaults. I don't see a need for a duplicate process.

**Comment by argiepiano** [comment]
> Config already has defaults; thats what the config file is for, and thats why `config_get()` didn't include it. Can't define defaults in two places.

I have to agree with this. Configs provide all defaults in the file , and it's reasonable to assume that, if you are using config values, you need to provide at least an empty value for each needed key

**Comment by kiamlaluno** [comment]
Isn't this issue asking proposing the same task #6108 proposes too?

**Comment by klonos** [comment]
Dang it! ...I'm getting old. I forgot that I already filed an issue for this. ...this is getting embarrassing 😞 

I'll move the comments from this issue over to that other one.
