### ISSUE TITLE
Bartik Theme: Values for header color gradient are not applied

### ISSUE THREAD

**Issue by Wylbur** [backdrop/backdrop-issues#6606]
## Description of the bug

When assigning gradient header colors using the Bartik theme, the selected colors are not applied to the header block.  The two colors can be set, but only the first header color is applied, and the gradient does not appear.  

## Steps To Reproduce

To reproduce the behavior:
1. In a vanilla Backdrop site, enable Bartik and set it as the default theme.
2. Go to the Bartik settings form. Notice how both "Header Background Top" and "Header Background Bottom" are set to black.
3. Change the color for "Header background top" to something distinctly different from the default black.

## Actual behavior

In the preview, the entire header changes to the color specified for "Header background top". instead of seeing a gradient.

## Expected behavior

Gradient between the two colors is applied, same as the behavior for this theme in Drupal 7.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.28.0
- Web server and its version: Apache
- PHP version: 7.4.33
- Database sever (MySQL or MariaDB?) and its version: MariaDB 10.5.2
- Operating System and its version:  Mac 
- Browser(s) and their versions: Safari

**Comment by Sarvasri** [comment]
Here is a screenshot showing the background color problem, (no gradient)
<img width="1204" alt="Screenshot 2024-06-12 at 4 51 34 PM" src="https://github.com/backdrop/backdrop-issues/assets/30607014/18b19107-9adf-4ad2-af45-d6d4c15ad840">

**Comment by Sarvasri** [comment]
In D7, the gradient  blend starts out dark, then light, then to dark again. There is also headroom above the photo. The headroom above the photo banner may be fixed with some CSS in Backdrop, or it may be a feature of the gradient blend setup in Bartik. When the gradient is fixed, check to see how headroom is managed and the best way to duplicate it in BD. D7 example shown below.
<img width="504" alt="Screenshot 2024-06-13 at 3 24 41 PM" src="https://github.com/backdrop/backdrop-issues/assets/30607014/02a33e8e-10f9-45c7-be29-a93b1270c35c">

**Comment by klonos** [comment]
> In D7, the gradient blend starts out dark, then light, then to dark again.

The top dark is a shadow from the admin toolbar - not part of the gradient. But the problem with the gradient is otherwise confirmed 👍🏼

**Comment by quicksketch** [comment]
Confirmed the PR sandbox is working as expected:
![image](https://github.com/backdrop/backdrop-issues/assets/100206/6a0f2026-5678-4218-90cc-936313164eaf)

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4791 into 1.x and 1.28.x. Thanks @klonos, @Sarvasri, and @Wylbur! Also thanks to @wesruv who came in during the weekly meeting and helped fix the CSS syntax right on the spot.
