### ISSUE TITLE
Customized management menu doesn't get default icons after 1.28 upgrade

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6609]
## Description of the bug

This was brought up on [Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/.E2.9C.94.20Admin.20bar.20icons.20after.20update). If you had a customized management menu before the Backdrop 1.28 upgrade, those menu links will never get the default icons added to the admin bar in 1.28.  

## Steps To Reproduce

To reproduce the behavior:
1. In a site running Backdrop 1.27.0 or less, customize the management menu, for example, by altering the order of the items
2. Run an upgrade to 1.28
3. The admin bar items all have the same icon: caret circle (which is the fallback icon for items that don't have a specific icon)

## Actual behavior
Admin bar shows the default icon for all items except for Home and More tasks.

![missing-icons](https://github.com/backdrop/backdrop-issues/assets/842066/bbe8d5f3-258a-432b-920c-d8d4fc6648b2)

## Expected behavior
Admin bar would be upgraded to show the new SVG icons for each item

## Additional information
This was solved by manually altering the `menu_links` table, by setting `customized` to `0` for each top menu links in the management menu.

Backdrop, by default, will never overwrite a customized menu link. Since the links were customized by changing their weights, the upgrade to 1.28 will never add the `icon` key to the `options` column of the menu link upon upgrade.

**Comment by indigoxela** [comment]
Wow, that's ... awful.

function _menu_link_build() would add the icon option, but we never get there, as _menu_navigation_links_rebuild() skips over it, because the condition `$existing_item['customized']` is met. :grimacing: https://github.com/backdrop/backdrop/blob/1.x/core/includes/menu.inc#L3050

A menu item can easily get this "customized" status. But we still want to have the shiny new icons. (And for sure we don't want people to fiddle in their database to get them :stuck_out_tongue_winking_eye:)

Who has an idea, how to fix?

Possibly an update hook that manually adds the icons, regardless of the "customized" status, but doesn't touch anything else?

**Comment by indigoxela** [comment]
A [PR](https://github.com/backdrop/backdrop/pull/4793) is available for testing and review.

Not sure, if this is the smartest or most elegant solution, but I tried to keep things as narrow as possible.

Testing can only happen locally. You need a Backdrop 1.27.2 install. BEFORE updating to 1.28 go to admin/structure/menu/manage/management and move items below "Administration" around. You can see their "customized" status, when they get a dropdown in column "Operations" - as they can get reset then (but don't).

After running the update to 1.28 you'll notice the icon problem.

Then apply [the patch](https://github.com/backdrop/backdrop/pull/4793.diff). After that you'll be prompted to run an update. Do so. After that all admin_bar icons should work as expected.

**Comment by herbdool** [comment]
I think this approach is probably the best we can do. I've only reviewed the code and it looks fine.

**Comment by argiepiano** [comment]
I've tested. RTBC. Thanks, @indigoxela!

**Comment by klonos** [comment]
I know that the most common use case here is the admin bar menu (`management`), but although an edge case the account menu (`user-menu`) could in theory suffer from the same problem if it has been customized. Right? So perhaps run the same routine to fix that menu as well?

**Comment by indigoxela** [comment]
@klonos these two aren't system menus, but the account links are built in function admin_bar_links_account, the home links are built in function admin_bar_links_icon. Independently from menus.

**Comment by klonos** [comment]
Indeed @indigoxela. Thanks 🙏🏼

**Comment by olafgrabienski** [comment]
I've tested the PR on a copy of the site where I discovered the issue, and the PR fixed the issue for me. Many thanks to all!

**Comment by yorkshire-pudding** [comment]
I've just tested this on a site that I've just realised had the issue too, and the patch works a treat.  Thanks @indigoxela

**Comment by quicksketch** [comment]
Thank you @indigoxela for the straight-forward update hook. Looks great to me! I appreciate the multiple confirmations and testing. Thanks @argiepiano for filing the issue!

Merged into 1.x and 1.28.x.

[b269ef2](https://github.com/backdrop/backdrop/commit/b269ef2acb75948a60f44b14c77d020252f629f4) by @indigoxela, @argiepiano, @izmeez, @herbdool, @klonos, @olafgrabienski, and @yorkshire-pudding.
