### ISSUE TITLE
Change "Backdrop database update" so it's clear that configuration can change too

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6611]
The "database update" language is used in a few places, which is a hangover from Drupal 7 where update hooks only updated the database. But now it can also change configuration which could be stored in files.

![2024-06-15 09 51 07 www allianceon org 64ab705f936b](https://github.com/backdrop/backdrop-issues/assets/1071483/c6ffe049-6613-4550-8066-19d0ebfc309d)

Maybe it could be just be "Backdrop updates"?

**Comment by argiepiano** [comment]
Backdrop site update?

**Comment by laryn** [comment]
There is an issues for this already, I think. I'm on my phone so don't have it handy.

**Comment by laryn** [comment]
Found it!

https://github.com/backdrop/backdrop-issues/issues/5630

**Comment by argiepiano** [comment]
I knew I had seen it recently!

**Comment by herbdool** [comment]
Thanks! Closing
