### ISSUE TITLE
Views argument handler views_handler_argument_file_type advertised to views in file_views_data() isn't actually defined

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6614]
## Description of the bug

As the title says, there's a missing views handler.
Views UI will show it, as it's defined here: https://github.com/backdrop/backdrop/blob/1.x/core/modules/file/views/file.views.inc#L82
But it's not usable.

## Steps To Reproduce

1. Go to admin/structure/views
2. Add a new view of type Files
3. Try to add a contextual filter "File: Type" (The type of the file (for example, "audio", "image", "video", etc))

## Actual behavior

Immediately get a "The handler for this item is broken or missing and cannot be used. If a module provided the handler and was disabled, re-enabling the module may restore it. Otherwise, you should probably delete this item."

![broken-views-argument-handler](https://github.com/backdrop/backdrop-issues/assets/842066/77839a68-2ddf-4829-9d92-06a622ff1fef)

## Expected behavior

Guess... :wink: 

## Additional information

This views handler definition came in (actually did not...) with one of those huge commits. Obviously an oversight. See Issue #2632

**Comment by indigoxela** [comment]
Here we go, a [PR](https://github.com/backdrop/backdrop/pull/4799) is available for testing and review.

To test, follow the steps described in the issue description.

**Comment by klonos** [comment]
Thanks @indigoxela 🙏🏼 ...I've tested this in a demo sandbox, and confirmed the problem. I then tested the same steps in the PR sandbox, and everything worked as expected 👍🏼 

This is RTBC, but I'ev left a tiny nit-picking suggestion in the PR for consideration.

**Comment by indigoxela** [comment]
> This is RTBC, but I've left a tiny nit-picking suggestion in the PR for consideration.

Wow, many thanks for this quick response.
Suggestion gratefully accepted. :wink:

**Comment by indigoxela** [comment]
PR rebased, in case someone wants to try things out in the sandbox.

**Comment by quicksketch** [comment]
Looks great. No issues at all that I read in the code. I merged https://github.com/backdrop/backdrop/pull/4799 into 1.x and 1.28.x. Thank you @indigoxela and @klonos!
