### ISSUE TITLE
Arguments for hook_user_update() documented incorrectly

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#662]
In `user.api.php`, we currently say that `hook_user_update()` includes two arguments:

```php
function hook_user_update(&$edit, $account) {
```

However the `$edit` parameter has been removed, per https://api.backdropcms.org/node/26867.

We just need to delete this parameter from the example. Oddly the parameter was deleted from the PHPDoc already, it just was left in the function definition.

**Comment by serundeputy** [comment]
https://github.com/backdrop/backdrop/pull/721 ~ travis is testing.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/issues/721. Thanks @serundeputy!
