### ISSUE TITLE
Path Administration has CSS issues on its drop button

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#663]
- Visit `admin/config/search/path`.
- Add a new alias.
- See the button for editing the alias is "fat" and overflowing it's row:

![alias-button](https://cloud.githubusercontent.com/assets/100206/5986711/fe74459a-a8b9-11e4-92dd-1ba500a30787.png)

It looks like the problem here is simply that there are unnecessary classes on the operations row. We just need to delete the list of classes from the operations element in `path_admin_overview()` in `path.admin.inc` and the button should display properly.

**Comment by serundeputy** [comment]
travis testing: https://github.com/backdrop/backdrop/pull/724

**Comment by quicksketch** [comment]
Beautiful! Thanks @serundeputy!
