### ISSUE TITLE
Fixed: Field aliases break the Views "Add Field" functionality.

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6630]
Reported separately by @indigoxela and @tkcent

## Description of the bug

Recent changes (https://github.com/backdrop/backdrop-issues/issues/6355) brought some adjustments in the Views UI which have caused a regression. If a field has a modified title (an "alias") it will cause a fatal error on PHP 8.x and make the "Add field" modal unusable.

## Steps To Reproduce

To reproduce the behavior:
1. Edit a Body field label on a content type field.
2. Open a View and click "Add field"

## Actual behavior

Modal doesn't open and there's a fatal error in the log.

> *TypeError*: strtolower(): Argument # 1 ($string) must be of type string, array given in *strtolower()* (line *3853* of *.../core/modules/views_ui/views_ui.admin.inc*).

## Expected behavior

Modal opens as expected and a field can be selected.

## Additional information

This was introduced a few days ago in 1.28.1.

**Comment by quicksketch** [comment]
Thank you @laryn and @tkcent! Thank you @herbdool for marking RTBC; sorry I overlooked crediting you in the commit.

I merged https://github.com/backdrop/backdrop/pull/4814 into 1.x and 1.28.x. Thanks folks!

**Comment by laryn** [comment]
Big thanks to @indigoxela  as well, who first brought this to my attention and discussed in depth with me.
