### ISSUE TITLE
Add a "Drupal 7 upgrade" state.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6633]
When upgrading a site from D7, I'd like to add a way to tell modules we are doing a D7 upgrade, as opposed to a normal Backdrop update.

Having a way to indicate D7 upgrades may help modules avoid fatal errors that would not typically occur during a normal update process. 

One of the concrete reasons for this request is that there are contrib modules that act upon cache clearing. During the D7 upgrade, `system_update_1079()` runs very early in the process, before (for example) text filters are set up. Ubercart/Rules, for example, try to set up some default, "in-code" rules during this cache clearing (see the hook `rules_flush_caches()`, which install default rules when needed). Ubercart in particular makes a call to `filter_default_formats()` to obtain the default text filter. Unfortunately, at this point of the upgrade process, filters have not yet been set up, resulting in a fatal error (see https://github.com/backdrop-contrib/ubercart/issues/484).

There have been other instances of problems brought up in Zulip (see https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Paragraphs/near/447608155).

## How this could be done
One way to indicate we are in a D7 upgrade is to set a `state` during the upgrade process. For example, an ideal place would be during the switch/case in `update.php`.

Right after clicking the button "Apply pending updates", we are taken to the switch/case in line 556 of `update.php`. This is when the update process actually starts.  Up until line 564 (`update_batch($_POST['start'], $redirect_url, $batch_url)`), the schema version for system is still > 7000 when we are running a D7 upgrade. The function `update_batch()` sets the schema to `999`, so that the system update hooks can run.

I'm proposing that we use `state_set('d7_upgrade', TRUE);` if the schema is > 7000 right before this point, to indicate that we are dealing with a D7 upgrade. We can then remove that state during the switch/case 'results' in line 569.

I'll submit a PR.

**Comment by argiepiano** [comment]
PR submitted. The PR temporarily adds state `update_d7_upgrade` and then removes it when the update is done.

**Comment by bugfolder** [comment]
I tested this. First, just set up a D7 site and upgrade it (to confirm that it didn't break anything). It worked.

Then, the real test: set up a D7 site with Ubercart enabled. In the B version of Ubercart, in file `ubercart/uc_order/uc_order.rules_defaults.inc`, add this to the beginning of function `uc_order_default_rules_configuration()` to address the crashing-during-upgrade problem:

```
   if (state_get('update_d7_upgrade')) {
     return array();
   }
```

Backdrop upgrade proceeded fully, no crash during upgrade (as desired).

A nice thing about setting `update_d7_upgrade` to TRUE in core during update means that updated contrib modules that check that variable to do something special during an upgrade will function the way they used to if they're running on an older version of core, since the `state_get()` will return `NULL` if the state variable doesn't exist.

LGTM, WFM. I'll go ahead and change the labels accordingly, but it would probably still be nice to get some more eyes on this.

**Comment by klonos** [comment]
Thank you @argiepiano for opening this and for filing a PR as well 🙏🏼 

I think that this is an excellent idea, and it could pair nicely with #4533 (which this issue here reminded me of and I'm planning to file a PR for as well).

**Comment by quicksketch** [comment]
This seems like a bit of a hack (or at least the way you plan to use it in Ubercart), but it's also pretty harmless from core's perspective and trivial to implement. Looks good to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4816 into 1.x and 1.28.x. Thank you @quicksketch, @bugfolder, and @klonos!

**Comment by argiepiano** [comment]
> This seems like a bit of a hack (or at least the way you plan to use it in Ubercart), but it's also pretty harmless from core's perspective and trivial to implement. Looks good to me.

Perhaps. But the root issue here is the fact that, during a D7 upgrade, caches are cleared before the whole site has been upgraded (`system_update_1079`). This is problematic and unusual.  Under normal operations, the site is fully functional when caches are cleared. So, perhaps that update hook should be revised.

**Comment by quicksketch** [comment]
>  But the root issue here is the fact that, during a D7 upgrade, caches are cleared before the whole site has been upgraded

I would be in favor of blanking-out that update hook. The weird thing is all caches are cleared anyway after running update.php, so it could have been blank to begin with and still accomplished the same thing. There's a not unusual pattern of removing the contents of update hooks if they've proven to be problematic like this one.
