### ISSUE TITLE
The code shown for callback_batch_operation() calls a function that Backdrop core does not implement

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6634]
[`callback_batch_operation()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21form.api.php/function/callback_batch_operation/1) contains the following code.

```php
  while ($row = db_fetch_array($result)) {

    // Here we actually perform our processing on the current node.
    $node = node_load($row['nid'], NULL, TRUE);
    $node->value1 = $options1;
    $node->value2 = $options2;
    node_save($node);

    // Store some result for post-processing in the finished callback.
    $context['results'][] = check_plain($node->title);

    // Update our progress information.
    $context['sandbox']['progress']++;
    $context['sandbox']['current_node'] = $node->nid;
    $context['message'] = t('Now processing %node', array('%node' => $node->title));
  }
```

Backdrop core does not implement any [`db_fetch_array()`](https://docs.backdropcms.org/search/node/db_fetch_array) function, which is instead implemented in Drupal 6.

The code shown for that callback needs to be updated to use only functions Backdrop core has.

This is the equivalent of [callback_batch_operation() code still contains Drupal 6 code](https://www.drupal.org/project/drupal/issues/2729171) I reported for Drupal 8.

**Comment by argiepiano** [comment]
Well, this is mitigated by the fact that this is an example function that never gets called, and is part of an api.php file. There are several examples of other api.php files that include code that would never run.

I would call this a documentation problem, not a bug. And it would be very, very low in my list of priorities, to be honest.

**Comment by kiamlaluno** [comment]
The PR uses the same code used by [`_node_access_rebuild_batch_operation()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/_node_access_rebuild_batch_operation/1).

**Comment by bugfolder** [comment]
> I would call this a documentation problem, not a bug. And it would be very, very low in my list of priorities, to be honest.

I would not disagree with this, but it is a real issue, and it's nice to clear open issues. I've reviewed the code and it looks good.

**Comment by quicksketch** [comment]
Merged into 1.x and 1.29.x. Thank you @avpaderno, @argiepiano, and @bugfolder!
