### ISSUE TITLE
[UX] Regression: Help text missing from Admin Bar settings

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6640]
I've reported this in #4586. Filing this as a follow-up.

We have a small but rather obvious regression with the help text for the various options, where the individual help text items got lost, and the description text for the checkboxes got duplicated in the wrapping fieldset.

Before/after screenshot:
![image](https://github.com/backdrop/backdrop-issues/assets/2423362/58228284-1e90-447d-886a-5d7e1193c3b4)

**Comment by klonos** [comment]
Small PR to fix the regression: https://github.com/backdrop/backdrop/pull/4809

**Comment by quicksketch** [comment]
Thanks @klonos, it would be great to get this in 1.28.2. I found a different regression in the PR. Could you check it?

**Comment by klonos** [comment]
Checking now @quicksketch 👀

**Comment by klonos** [comment]
Sorry for the delay. PR updated (tests are currently running).

**Comment by laryn** [comment]
Thanks @klonos and @quicksketch -- tested and merged into 1.28.x and 1.x!
