### ISSUE TITLE
[DX] .htaccess: Change the cryptic value of `A1209600` for `ExpiresDefault` to a human-readable one

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6646]
Current value is this:
```
  # Cache all files for 2 weeks after access (A).
  ExpiresDefault A1209600
```

Proposal to change that to this instead:
```
  # Cache all files for 2 weeks after access.
  ExpiresDefault "access plus 2 weeks"
```

See spec for details: https://httpd.apache.org/docs/current/mod/mod_expires.html

**Comment by kiamlaluno** [comment]
With `ExpiresDefault "access plus 2 weeks"`, it is not even necessary to comment that line.

**Comment by klonos** [comment]
OK, here's a PR to get this going: https://github.com/backdrop/backdrop/pull/4827

I haven't completely removed the comment for now - lets wait for some feedback and adjust once others had a chance to chime in.

**Comment by kiamlaluno** [comment]
I was going to suggest adding a link to a page explaining the syntax used for that directive, but then I noticed that is not dome for the other directives as well.

**Comment by avpaderno** [comment]
> Does this require a change record?

No, it does not. The files are still cached for two weeks. (I think change records are for changes to the API, not changes to files.)

**Comment by quicksketch** [comment]
Looks good to me too! We'll need to include a sentence in the release notes about changing `.htaccess` but as there is no functional change, no change record is needed.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4827 into 1.x and 1.29.x. Thank you @klonos, @avpaderno, and @izmeez!
