### ISSUE TITLE
Error: Call to undefined function `backdrop_load_updates(`) in `drupal_load_updates()`

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6655]
I tried installing https://github.com/keiserjb/site_audit on a fresh Backdrop site, and got this error:

```
Error: Call to undefined function backdrop_load_updates() in drupal_load_updates()
(line 1858 of /var/lib/tugboat/backdrop/core/includes/drupal.inc).
```

I would normally file this issue under that specific contrib module, but I am suspecting that this is a thing that should be solved in core. It seems that in the backwards compatibility layer, when we call `backdrop_load_updates()` in `drupal_load_updates()` within `core/includes/drupal.inc`, we should be loading `core/includes/install.inc` (which is where the `backdrop_load_updates()` function lives).

**Comment by klonos** [comment]
...although on the Backdrop demo site (running core 1.28.2 at the moment) the problem is reproducible by simply navigating to the module report at `admin/reports/site-audit`, I couldn't reproduce the problem that way on my local on latest 1.x. I reproduced it by executing `drupal_load_updates();` via Devel's `admin/devel/php` instead.

Applying the changes in the PR and clearing caches fixes the problem: https://github.com/backdrop/backdrop/pull/4830

**Comment by argiepiano** [comment]
I don't have an opinion on whether this is needed or not (it wouldn't hurt to add it), but please notice you are getting this error because of faulty code in the module site_audit. I think it's more important to get it fixed there, rather than creating a defensive fix here.

**Comment by keiserjb** [comment]
I was actually thinking about Site Audit earlier today. Maybe I should try to get a new port working.
