### ISSUE TITLE
[UX] Installer: Improve the language selection workflow/form/instructions

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#6659]
When you start the Backdrop installer, you are greeted by this:

<img width="853" alt="image" src="https://github.com/user-attachments/assets/19b3e822-83fb-4b6c-ba6f-5abced9ebd71">

By default, and without any other language files added, there is only a single option in the select menu, so we could:
- omit the select and have the submit button say "Continue installation in English"
- only have the title of this installer page be "Choose language" if there are actually multiple languages to choose from. 

It may look that the "Learn how to install Backdrop in other languages" link will take you to some external documentation page, but it takes you to this form instead:

<img width="853" alt="image" src="https://github.com/user-attachments/assets/7e986f06-db68-4167-b13c-57d6b4d5cce2">

- The page title is still "Choose language", which is wrong given the context and the contents of the form.
- It feels like all this information could be shown in a collapsible fieldset in the previous page.
- The two links in bullet points are actually actions, so perhaps should better be styled as submit buttons instead.

In general, it feels like this workflow could use some consolidation, streamlining, and consistency in style.

**Comment by docwilmot** [comment]
My immediate thought is:
- why cant we automatically download language files?
- could we at least have a minimal "installation language file" in core for common languages (top 10?) with just the strings needed for the installer?

Not sure how practical those thoughts are but posting FWIW.

**Comment by klonos** [comment]
Thoughts and feedback I need:
- When only one language, should the select be disabled, completely hidden away, or replaced by a message? For now, I've left it with a simple implementation of the Form API `'#disabled'` property, but I don't think that it provides much value that way personally. Speaking of value, having a message saying something along the lines of "Only English is available" would also provide very little value from the moment that the available language is already indicated in the page title.
- When several languages are available, should they all just be in a select, or if there's only say 2 or 3 languages, then show them as radio options? ...and in that case, if showing them as radios, what should be the maximum number of languages when this turns into a drop-down select?

Thoughts/suggestions?

**Comment by docwilmot** [comment]
- The disabled select makes it clear what *could* be available so I'd keep it
- I think a select. I think radios do not make it obvious that other languages are possible; it might look like Backdrop only comes in English and Greek.
> I wouldn't like to have these feature requests block this UX task here

Not my intention either, just putting those point down while the occur to me, sorry.

**Comment by klonos** [comment]
> I think a select. ...

Having a select all the time is the "easy" solution developer-wise, and I'm OK with it, but it is not the most ideal UX, since it requires 2 clicks instead of one. And although one can argue that two clicks is not that big of a deal, it does add up to the UX (overall feeling of "too much work needed - too many steps required"). Several clicks via a drop-down select make perfect sense for a big list of items (when showing all of them would make the form too lengthy and would thus require too much scrolling - so you'd be trading clicks for scrolls - no point in that). However, two clicks when there are only 2 or 3 options is not ideal UX.

> ...I think radios do not make it obvious that other languages are possible; it might look like Backdrop only comes in English and Greek.

But the "How to install Backdrop in other languages" text would still be right there below the options:
<img width="877" alt="image" src="https://github.com/user-attachments/assets/6caaaedc-854e-49b9-aedb-7658344b4593">

Wouldn't that make it obvious that more languages can be added?

**Comment by avpaderno** [comment]
> When several languages are available, should they all just be in a select, or if there's only say 2 or 3 languages, then show them as radio options?

I would use a select in any case, but add a description that makes clear the select form element allows to choose between a list of languages. (Since that is an installer page, the person who is installing Backdrop could not be familiar with the Backdrop UI.)

**Comment by klonos** [comment]
Thanks for the feedback @avpaderno 🙏🏼 

> ... add a description that makes clear the select form element allows to choose between a list of languages.

Can you please provide an example of such a description text? Would it be something like this?:
> Select from languages currently available. More languages can be added manually. See instructions below.

**Comment by avpaderno** [comment]
*Select from languages currently available. More languages can be added manually. See instructions below.* would be good. It should make clear that, while the form element shows just *English* (because it shows an item at time), there are other languages which can be selected.

**Comment by klonos** [comment]
Thanks for the suggestions @avpaderno 🙏🏼 ...here's my thinking though:
- the most common use case is to install in English, which is the default, and doesn't require any additional steps
- then next most common use case is to add another single language other than English (two languages to select from in total)
- there may be cases where you add several languages, but I don't think that that would be very common (we'd need metrics to be more certain of that)
- when there are only 2 or 3 options to select from
  - a select adds unnecessary clicks and the available options are "hidden" on first sight
  - a radio set is a much better option, since it displays all available options, and takes a single click
- based on the previous points, I think that we should switch to a radio, and consider the select menu only to be a fallback that's available to account for uncommon/edge cases

**Comment by docwilmot** [comment]
Early work on automatic downloads started: 
https://github.com/backdrop/backdrop-issues/issues/6660
https://github.com/backdrop/backdrop/pull/4834

There should be a way to limit languages available during install to those actually available on the server, but not yet in this PR, so if you get an error if you try, for now.

**Comment by avpaderno** [comment]
IMO, changing a form element used in a page from select to radios when the page is reloaded is bad UX.

Either radios are used from the start, or a select form element is always used. In the first case, people could be confused by having a single radio, when usually there are more radios, but it is better to have a single radio than changing from a select form element to radios.

**Comment by avpaderno** [comment]
Also, *Select from the languages currently available. More languages can be manually added. See instructions below.* would still hold true even when radios are used instead of the select form element, or when the number of downloaded languages is restricted. Eventually, if the number of downloaded languages is restricted, the description should change to **Select from the languages currently available.*

**Comment by klonos** [comment]
I'll start off by saying that ideally we should do #6660, as it solves many other UX/workflow issues, and removes the need for manual steps needed to be performed. Thanks for starting to work on it @docwilmot 👍🏼 ❤️ ...that, paired with something like Chosen or any search-within-a-select solution would be ideal UX.

Second: I'm stupid. This is a duplicate of #3975, which I raised myself back in 2019. Oh, the shame 🤦🏼 

But before I close this one and continue over on that other issue, I'd like to address this argument:

> Either radios are used from the start, or a select form element is always used. In the first case, people could be confused by having a single radio, when usually there are more radios, but it is better to have a single radio than changing from a select form element to radios.

I disagree with that. There should be no single radio, nor any select menu when there is only one option. In the case of only a single item, there should be no notion of choice/selection - it should be indicated via statements/messages or the title and the rest of the elements in the UI.

I now see that the screenshots I've provided in earlier comments show a select with a single item, but I clearly said that "still needs a bit of polishing". The current implementation when there's a single language is this:
<img width="853" alt="image" src="https://github.com/user-attachments/assets/cc883861-9220-417b-97d7-be2245ca21ec">

Furthermore, when it comes to this:

> > IMO, changing a form element used in a page from select to radios when the page is reloaded is bad UX.

I don't expect any switching to be happening. These are the use cases I am expecting:

### Most common use cases:
- the installation will happen in English -> nothing to select and no radios or select shown - just click "Continue in English" and go on with the installation.
- the person performing the installation adds another single language file -> reloads -> sees two options -> selects one and clicks "Continue"

### Less common or edge use cases:
- the person performing the installation adds several language files -> reloads -> they either see a select or a set of radios depending on how many language files they've added:
  - if they happen to have added another 2 or 3, they'll get a radio, which is less clicks
  - if they added more languages, then they'll get a select, in order to not have a lengthy form that requires scrolling
- the installation is part of a pre-packaged version of Backdrop that a hosting provider offers, with several (or all?) languages already added to the translations folder -> the person performing the installation will get a select menu in that case.

For any switching from a radio to a select to happen, the person performing the installation will need to be adding language files one-by-one and then refreshing the page with each file they are adding. I really don't think that that'd be a common scenario. And even if it were, I still wouldn't call it "bad UX". There are many things to consider here, like cognitive stress with many items in radios (a much more real UX problem), and at the same time the default option in select menus being perceived as the "recommended" one, which in no case it is nor should it be in the specific UI we are discussing here (not a real UX problem per se, rather than a design decision).

By the way, there are some very nice resources on the matter of radios vs select, which include recommendations on switching from one to the other dynamically based on number of items (although not explicitly/exclusively about that topic). Here's some of them that I have found useful:
- https://ux.stackexchange.com/questions/11713/alternatives-to-having-an-excessive-number-of-radio-buttons-on-a-form
- https://ux.stackexchange.com/questions/86325/radio-buttons-or-dropdown-for-same-list-of-options
- https://blog.prototypr.io/7-rules-of-using-radio-buttons-vs-drop-down-menus-fddf50d312d1
- https://uxdesign.cc/selection-controls-ui-component-series-3badc0bdb546

**Comment by avpaderno** [comment]
My comment is for the screenshots shown in the previous comments, which show first a disabled select form element and then a set of radios. I am not endorsing any user interface model; I just commented about changing the type of a form element when a page is reloaded, which is what those screenshots show.  
(*still needs a bit of polishing* to me means that some small changes are still needed, not that a relevant form element is completely removed.)

**Comment by stpaultim** [comment]
So, I assume that neither this or #3975 will be necessary if we implement #6660?

Otherwise, this would have been a nice change. I just tested it and it seems to work as expected, but I did actually test the instructions to see if they worked, since they may not be necessary anymore.

**Comment by klonos** [comment]
Thanks for testing @stpaultim 🙏🏼

We may still need to add the fieldset with the manual instructions, in case the online fetching of translations doesn't work, or for instance when there's need to install in a non-common or custom/fictional language that doesn't exist on the translation server (think less popular dialects or even Klingon, Mordor, l33t etc.). But I'll close this issue here in favor of the older #3975, and consolidate the PRs as well.
