### ISSUE TITLE
Document equivalent function to deprecated `file_create_htaccess()`.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6665]
`file_create_htaccess` is provided by the Drupal compatibility layer, and is deprecated. The Backdrop equivalent is `file_save_htaccess`. It'd be good to document this in the docblock for `file_create_htaccess`, like other deprecated functions in that file.

Backdrop version: 1.28.2

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4837 available for review

**Comment by klonos** [comment]
Thanks @argiepiano 🙏🏼 ...RTBC 👍🏼

**Comment by quicksketch** [comment]
Thanks @argiepiano and @klonos! Merged https://github.com/backdrop/backdrop/pull/4837 into 1.x and 1.28.x.
