### ISSUE TITLE
Update jQuery UI to 1.14

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6677]
jQuery UI 1.14.0 has arrived! https://blog.jqueryui.com/2024/08/jquery-ui-1-14-0-released/

This contains (slightly?) breaking changes, for example they dropped IE support and removed related polyfills. OK, as we did already in Backdrop.
The structure seems to have changed, but it's not clear, yet, if that affects us in any way. Edit: it doesn't.

They also dropped support for very old jQuery versions and removed related workarounds.

There's an [upgrade guide](https://jqueryui.com/upgrade-guide/1.14/), but as we're on jQuery UI 1.13.x already, it might be, we don't have to do much (or anything) re that.

Here's the [changelog](https://jqueryui.com/changelog/1.14.0/)

Note that we still have a pending update to the [latest 1.13](https://github.com/backdrop/backdrop-issues/issues/6550), but unlike that one, which is appropriate for a bugfix release, this one here probably isn't. It's rather a candidate for a minor Backdrop release.

**List of things to manually test with new versions of jQuery UI:**

See: https://github.com/backdrop/backdrop-issues/wiki/jQuery-UI:-Checklist-for-manual-tests

### Blocks 
- [x]  Added a custom block
- [x]  Moved another block

### Field UI
- [x]  Changed the order of fields on one of the Manage Display pages

### Layout UI 
- [x]  for path node/% does context appear automatically?
- [x]  drag and drop blocks
- [x]  Added a custom block
- [x]  Moved another block

### CKEditor
- [x]  link dialog
- [x]  image dialog
- [x]  Configuration: Added buttons to the editor toolbar
- [x]  Sortable
- [x]  Draggable

### Elements 
- [x]  autocomplete

### Views UI

- [x]  Added a view
- [x]  Changed to the display of fields
- [x]  Modal windows
- [x]  Rearranged the fields

### Weight 
- [x]  draggable
- [x]  droppable

**Comment by indigoxela** [comment]
Hm... seems like the new version breaks our dialog (optimized) resize functionality with both of our jQuery versions. :disappointed: So this needs work at least in core/modules/filter/js/filter.js, eventually more.

But overall it doesn't look that bad. Draggable, droppable and friends seem to work fine.

The error is `Uncaught TypeError: $(...).position() is undefined` in line 231 of filter js, as at that point `$('.editor-dialog')` is an empty array.

FTR: Files that got removed from the build (presumably unrelated to above dialog prob):
```
	deleted:    core/misc/ui/jquery.ui.core.min.js
	deleted:    core/misc/ui/jquery.ui.form.min.js
	deleted:    core/misc/ui/jquery.ui.ie.min.js
	deleted:    core/misc/ui/jquery.ui.safe-active-element.min.js
	deleted:    core/misc/ui/jquery.ui.safe-blur.min.js
```

**Comment by indigoxela** [comment]
A fresh sandbox is available (rebased).

**Comment by olafgrabienski** [comment]
Thanks for the fresh sandbox!

> docwilmot added `pr - works for me`

Works for me as well.

**Comment by quicksketch** [comment]
I also tested and things seem to all work. Layout drag and drop doesn't work on touch screens but that seems to be the case before this PR as well (real touch support might not ever make it to jQuery UI). @indigoxela would you be interested in updating Touch Punch too? Looks like there's several new versions since we last updated: https://github.com/RWAP/jquery-ui-touch-punch

**Comment by quicksketch** [comment]
Merged into 1.x for 1.29.0. Thank you @indigoxela, @olafgrabienski, and @docwilmot!
