### ISSUE TITLE
Wrong link to classify file types if installed in subdirectory

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop/backdrop-issues#6678]
## Description of the bug

The link to "Classify file types" on the Status page is absolute and therefore does not work if Backdrop is installed in a subdirectory.

## Steps To Reproduce

After an upgrade from Drupal 7, files are not classified and the Status page displays "File types need to be classified. (Classify file types)" with a link to /admin/structure/file-types/classify.

## Actual behavior

That link is resulting in error 404 if BD is install in a subdirectory.

## Expected behavior

The link should work in any situation, it should be passed through url().

## Additional information

I will create a PR.

**Comment by argiepiano** [comment]
Good catch, @AlexHoebart-ICPDR! I created this functionality 2 years ago and that slipped through. LGTM!

**Comment by quicksketch** [comment]
Thanks @AlexHoebart-ICPDR and @argiepiano! Merged https://github.com/backdrop/backdrop/pull/4844 into 1.x and 1.28.x.
