### ISSUE TITLE
RSS settings don't save

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#668]
to reproduce:
1) Navigate to admin/config/services/rss-publishing
2) Change the option for "Feed content" from "Full text" to "Titles plus teaser"
3) Save
4) Notice that your changes haven't been saved

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/720. Looks like we have different keys in various places for the same settings.

**Comment by serundeputy** [comment]
haha; i just filed one too;

**Comment by quicksketch** [comment]
Doh! Well... they both work. :wink:

**Comment by serundeputy** [comment]
;) tis life; @quicksketch , @jenlampton is there a way we can claim issues so that others no that we are working on them?

like assignments?

**Comment by quicksketch** [comment]
Yes, you should be able to assign yourself to an issue in the right column. I should have done that for myself when I started as well.

Doh, I just realized you're not in the docs & organization team yet, so you don't have labeling/assigning ability. I sent you an invite. :smile:
