### ISSUE TITLE
Entity reference dialog not closing on cancelling or deleting the referenced entity

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop/backdrop-issues#6686]
## Description of the bug

Entity reference, when using the dialog feature to create or edit the referenced entity, doesn't close the dialog window when deleting or cancelling the dialog form. Instead, it does all the job in the dialog window, instead of closing and working on the main window. The same happens if you do a preview of the entity being referenced. Going back to the form and saving doesn't send you to the parent window.

In fact, the dialog form only sends you to the parent window when clicking on the save button. Any other button leaves you in the dialog window.

## Steps To Reproduce

1. Create an entity reference field in a node type, either node or term.
1. Add a new node and some new referenced term or node to it.
2. on the dialog window to reference a new node or term, click on cancel instead of save. you hit the problem.
3. you can edit the parent node and try to edit the referenced entity and click on any button other than save. You hit the problem.

**Comment by argiepiano** [comment]
I'm confused by this report. Entity Reference does not have a "dialog feature" to create or edit referenced entities. Perhaps this is being provided by a contrib module? Can you please clarify? These are the widgets provided by ER.

<img width="373" alt="Screen Shot 2024-08-18 at 12 39 05 PM" src="https://github.com/user-attachments/assets/b7dfc7d2-3354-45c7-b4b6-6e55a715d6cd">

**Comment by robertgarrigos** [comment]
I just realized that the References Dialog provides that functionality to Entity Reference, although it is a contrib module for the References module. Sorry about that.
