### ISSUE TITLE
MailTestCase::format() incorrectly calls backdrop_wrap_mail()

### ISSUE THREAD

**Issue by avpaderno** [backdrop/backdrop-issues#6690]
[`MailTestCase::format()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21simpletest%21tests%21mail.test/function/MailTestCase%3A%3Aformat/1) contains the following code.

```php
// Convert any HTML to plain-text.
$message['body'] = backdrop_html_to_text($message['body']);
// Wrap the mail body for sending.
$message['body'] = backdrop_wrap_mail($message['body']);
```

For the same reason given in #6471, that code is not correct: [`backdrop_wrap_mail()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21mail.inc/function/backdrop_wrap_mail/1) converts all soft breaks into hard breaks, making 'format=flowed' meaningless. It is also the opposite of what [`backdrop_html_to_text()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21mail.inc/function/backdrop_html_to_text/1) tries to achieve.

> The output will be suitable for use as 'format=flowed; delsp=yes' text (RFC 3676) and can be passed directly to [`backdrop_mail()`](https://docs.backdropcms.org/api/backdrop/core%21includes%21mail.inc/function/backdrop_mail/1) for sending.

**Comment by avpaderno** [comment]
The only failure in the PR checks is for Tugboat. (I guess it is not able to create a preview site.)

**Comment by quicksketch** [comment]
Thanks @avpaderno! As this fix was suggested by @argiepiano in https://github.com/backdrop/backdrop-issues/issues/6471#issuecomment-2308005052, and the tests are passing, this looks good to me. I merged into 1.x and 1.28.x. Thank you!
