### ISSUE TITLE
Update jquery.ui.touch-punch.js to latest version

### ISSUE THREAD

**Issue by indigoxela** [backdrop/backdrop-issues#6696]
## Description of the task

jQuery.ui touch punch has been updated in Backdrop back in September last year, but there were several commits and releases this year, including deprecated fixes. Time to catch up. :wink: 

https://github.com/RWAP/jquery-ui-touch-punch

## Additional information

In https://github.com/backdrop/backdrop-issues/issues/6185 we switched vendor from the original (now unmaintained) version to a supported fork.

**Comment by argiepiano** [comment]
Do you need a tablet to test?

**Comment by indigoxela** [comment]
> Do you need a tablet to test?

Any touch device will do. Tablet, smartphone, whatever.

**Comment by indigoxela** [comment]
FTR: I tested this PR with Android 13 and Firefox Focus and draggable/droppable works.

For me it works _with and without_ this patch (with jQuery version 3.7.1 / jQuery UI version 1.14.0) - I see no difference, which is good.
@quicksketch you seemed to have trouble with the Layout form drag-and-drop with a touch device. Does this PR change anything for you? Which OS / browser?

**Comment by olafgrabienski** [comment]
I was able to drag and drop Layout blocks with an iPad.

**Comment by laryn** [comment]
Tested on an iPhone in Firefox, Chrome, and Safari. WFM!

**Comment by laryn** [comment]
Marked as WFM given I see Android and iOS testing completed successfully. If someone is having trouble please report and reset the status here, of course.
