### ISSUE TITLE
[UX] Improve form item label text for new SVG icon views field handler 

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#6701]
## Description of the bug

We need to decide on improved text for labels in https://github.com/backdrop/backdrop-issues/issues/6588 

Current text:
![image](https://github.com/user-attachments/assets/10f3a784-9f0c-4fb8-aa59-c605f2424183)

## Curent recommendations:

`Embedded file with  <svg> tag.`
`Embedded SVG images are usually more efficient and easier to style.`

`Referenced file with <img> tag.`
`Referenced SVG images can be more efficient when showing the same icon many times.`

`Display text alternative`
`For icons that are decorative only, alternative text should be omitted. A text alternative is used to describe the icon for assistive tools like screen readers.`

## Other Recent recommendations:

`Inline <svg> tag`
`Inline SVG images are usually more efficient and easier to style.`

`Regular <img> tag`
`Regular image tags can be more efficient when showing the same icon many times.`

`Add alternative text`
`If alternative text is omitted, this icon will be marked as decorative only.`

**Comment by indigoxela** [comment]
A screenshot of what we have now:

![views-icon-dialog](https://github.com/user-attachments/assets/f621b141-d238-4543-ab3f-eea50f2c265f)

With the descriptions added, there's now text duplication, that doesn't seem to add value.

Strings like
```
Inline <svg> tag
Regular <img> tag
```
are too similar next to each other to easily distinguish, and produce awkward translation strings like:

```
Inline <code>&lt;svg&gt;</code> tag
```
Note that a translator has to identify the "svg" inside that stuff they may not touch to not break the whole string. Sort of cumbersome.
And for translators the only difference between the two strings would be exactly that hard to spot three chars.

For the alternative text we discussed something like:

- Title: Text alternative
- Desc: Add a text alternative to describe the icon for assistive tools like screen readers.

**Comment by avpaderno** [comment]
I would rather use a checkbox form element, instead of a radios form element, since that setting is asking if SVG images should be used. That would avoid to call the usual JPEG, PNG, and GIF images *regular images*.

**Comment by indigoxela** [comment]
> ... since that setting is asking if SVG images should be used

Changing the form item type to circumvent a wording discussion? Am I getting this right? Hm... that seems a bit odd to me. :wink: 

It's radios, because people can pick between two different rendering options, a checkbox would obfuscate that IMO. And I'd find it confusing.

@avpaderno  Besides that, it's also off topic here, as the issue's supposed to cover form *wording* only. If you're convinced, the form item decision was wrong for whatever reason, it might be clearer to just open a new issue for that.

**Comment by wesruv** [comment]
"Regular Image" doesn't work for me either, we talked about it in the Backdrop UX meeting, this is my thought that I think addresses the lack of clarity for me.

```
Referenced Image
Use an <img> tag that points to the SVG, which can be faster if the image shows up many times on the page, but isn't easy to style.
```

**Comment by jenlampton** [comment]
> Another thing re suggestions: strings like [....] are too similar next to each other to easily distinguish

I think including the tags that will be used is critical, since that's what we're asking to choose between. Without using example tags I don't understand why a SVG tag isn't "regular".

> and produce awkward translation strings 

@quicksketch  recommended that the tags should not be included in the translation, since the HTML tag itself is not different across languages. 

```php
t('Embedded file with  !tag tag', array('!tag' => '<svg>'));
t('Referenced file with !tag tag', array('!tag' => '<img>'));
```

> Those two options are SVG or not SVG.

Those aren't the two options though. We're going to use a `.svg` file either way.  If someone selected "not svg" they might be expecting to see a `.gif` or something else.

The question is how we render that SVG file, using an `<img>` tag, or a `<svg>` file.
```
<svg></svg>
<img src="icon.svg">
```

Because the main difference between these two tags is whether the file is embedded or referenced, I'd like to recommend that we use those two words in addition to the actual tag as an example. 

`Embedded file with  <svg> tag.`
`Referenced file with <img> tag.`

**Comment by jenlampton** [comment]
> For the alternative text we discussed something like:

Title: `Text alternative`
Desc: `Add a text alternative to describe the icon for assistive tools like screen readers.`

> To use "text alternative" can make sense, as for SVG tags that's a <title> tag, for IMG tag it's the alt attribute. Their purpose is the same.

I love `Text alternative` here, but we should indicate that this is a display setting, and not a place where the text can be added. How about `Display text alternative`

I'm not thrilled with `Add a text alternative to describe the icon for assistive tools like screen readers.` because it reads like an imperative "Do this!". In most cases, we don't actually want people to do it because these icons will be decorative. 

What if we combined both, something like:

`For icons that are decorative only, alternative text should be omitted. A text alternative is used to describe the icon for assistive tools like screen readers`

**Comment by olafgrabienski** [comment]
> For icons that are decorative only, alternative text should be omitted. A text alternative is used to describe the icon for assistive tools like screen readers.

I'd suggest to turn the sentences around: _First_ explain what 'text alternative' is, _then_ add the restrictive phrase.

> A text alternative is used to describe the icon for assistive tools like screen readers. It should be omitted for icons that are decorative only.

However, I find the phrase "is used" in the first sentence ambiguous. In a way, it both explains the general concept of text alternatives, _and_ it gives an indication what Backdrop does when you enable the option. Reading the sentence, I wouldn't know what to expect: Does Backdrop add a certain text, or do I (have to) add my custom text?

Hopefully slightly clearer suggestion:

> Adds a text alternative which describes the icon for assistive tools like screen readers. Do not enable for icons that are decorative only.

**Comment by olafgrabienski** [comment]
I like the text changes, nice! I also tried to check the translation strings in the sandbox of the PR, but so far they didn't appear in the translation interface, even though I created a file icon view.

**Comment by indigoxela** [comment]
> I also tried to check the translation strings in the sandbox of the PR, but so far they didn't appear in the translation interface

Odd, I can find them. My usual trick: switch to the other language (DE in that case) once. Then the new `t()` stuff usually shows up on /admin/config/regional/translate/translate.

**Comment by indigoxela** [comment]
BTW, personally, I'd suggest to remove the wrapping `<code>` tags - to me they seem distracting (the code highlighting depends on the admin theme, but there will be some highlighting in all of them, I guess).

And the translation string looks confusing: `Referencing via <code>&lt;img&gt;</code> ...`. But that's maybe just me. :wink:

**Comment by olafgrabienski** [comment]
> My usual trick: switch to the other language (DE in that case) once

Oh yes, forgot that, thanks a lot, works like a charm!

> I'd suggest to remove the wrapping `<code>` tags ...

I agree, without `<code>` tags does the job, but even then the string in the translation interface looks ugly:
`Referencing via &lt;img&gt; ...` (I vaguely recall a suggestion by @quicksketch to not translate the file extension itself, but can't find it at the moment.)

**Comment by avpaderno** [comment]
With `t('Embedded file with !tag tag', array('!tag' => '<code>&lt;svg&gt;</code>'))`, what the translators see is *Embedded file with !tag tag*; the user interface will not show *`<code>&lt;svg&gt;</code>`* to translators.

**Comment by indigoxela** [comment]
@avpaderno I like your suggestion. :+1: I'm not sure, if that's "allowed", though. The rules around `t()` can sometimes be a bit confusing. Can anyone confirm, that it's OK to wrap the tag code like that?

Bear with me, I hate to put some pressure here, but we're slowly running out of time for the stable release. :grimacing:

**Comment by laryn** [comment]
@indigoxela Yes, I believe that's allowed. It was also suggested earlier, so I think we have pretty good consensus that it is a reasonable approach:

https://github.com/backdrop/backdrop-issues/issues/6701#issuecomment-2332632593

**Comment by avpaderno** [comment]
The suggestion was from jenlampton/quicksketch. I just commented saying that string does not ask to translators to translate *<code>&lt;svg&gt;</code>*.

**Comment by indigoxela** [comment]
> The suggestion was from jenlampton/quicksketch...

Wow, how did I miss that comment. :grimacing: 

Anyway, next version looks like this:

![form-text-next-iteration](https://github.com/user-attachments/assets/76a7d375-d247-48a5-80ee-2c4c446a1851)

**Comment by olafgrabienski** [comment]
Tested in the sandbox, works for me, including translating the strings (see below). Great!

For the record, these are the new (translator friendly) strings:

- Embedded with !svg tag
- Referenced with !img tag

**Comment by jenlampton** [comment]
I did a code review, and the code change looks good! 

I do have a few thoughts on the text:

1) My preference is to match the syntax in the descriptions for the two options, so they both start with ADJECTIVE(S), NOUN, VERB, rather than the second stating with a gerund:
*  `Inline SVG icons are ....`
* `Referenced images can be ...` 

2) I'm not a fan of `With text alternative` as a label. It's only a phrase and could translate oddly. I would prefer if this were a complete sentence like `Add text alternative` or `Include text alternative`.

3) `Adds a descriptive text` is not grammatically correct in English, I think we should make this `Adds descriptive text.` instead, omitting the `a`. 

I love the new `Do not enable for icons that are decorative only` :)

**Comment by indigoxela** [comment]
@jenlampton wording updated accordingly. Many thanks for having a look. :+1:

**Comment by quicksketch** [comment]
Thank you everyone! I merged https://github.com/backdrop/backdrop/pull/4865 into 1.x for 1.29.0.

https://github.com/backdrop/backdrop/commit/4df763da1894e40abdcf059c351a2f3b69c4d36f by @indigoxela, @jenlampton, @quicksketch, @avpaderno, @olafgrabienski, @laryn, and @wesruv.
