### ISSUE TITLE
A11Y: Tabbing Manager

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6704]
## Description of the need

I was talking to a colleague about the Announce functionality that is available in Backdrop and Drupal, and came across this page, which mentions Drupal's Tabbing Manager functionality in relation to accessibility and Javascript:

 - https://www.drupal.org/docs/drupal-apis/javascript-api/accessibility-tools-for-javascript-in-drupal#tabbing
 - https://git.drupalcode.org/project/drupal/-/blob/11.x/core/misc/tabbingmanager.js

> For some interactions, you may want to guide a non-visual user to the most important elements on the page. For example, the Contextual module constrains tabbing to the contextual links when the global edit mode is enabled...

I wanted to note this here as a potential accessibility improvement we could consider porting over, as was done previously with Announce.

**Comment by quicksketch** [comment]
On further testing, it seems that jQuery UI dialogs already implement a focus trap (see https://bugs.jqueryui.com/ticket/3768/). When a modal or dialog is open in Backdrop, the focus is already locked to the contents of the dialog thanks to jQuery UI's implementation.

**Comment by laryn** [comment]
@quicksketch Thanks for looking this over. I guess it seems like this may not be necessary in core at the moment, so I will close the issue.

The piece I quoted does reference a concept/example unrelated to modals that I'm interested in (e.g. an "Edit mode" that makes tabbing only jump between contextual edit links, or similar) but if I ever get around to implementing I will just have to implement a "focus trap" solution as part of it.

**Comment by quicksketch** [comment]
Thanks for filing the issue regardless, I wasn't aware of this capability in Drupal.
