### ISSUE TITLE
Misnamed date token 'to-date'

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6707]
## Description of the bug

Date fields with an end date have token support. Currently, the formats shown in the token tree are `date` (for starting date) and `to-date` for end date, as in `[node:field_my_date:date:long]` and `[node:field_my_date:to-date:long]`.

The `to-date` part actually doesn't work. If you look at the date implementation of `hook_tokens` the expected part is `end-date`, not `to-date`. See [these lines](https://github.com/backdrop/backdrop/blob/c61a9f5064d61af032bfc6391aa69c049174a2a6/core/modules/date/date.tokens.inc#L19-L31) and [this line](https://github.com/backdrop/backdrop/blob/c61a9f5064d61af032bfc6391aa69c049174a2a6/core/modules/date/date.tokens.inc#L151)

## Steps To Reproduce
1. Install and enable Token filter. Go to `admin/config/content/formats/filtered_html` and be sure to enable the Token filter and Save
2. Go to Content type and edit the `Page` type. Add a field called My date in a content type. Be sure to "Collect end date" in Global settings
3. In the Body field, enter the following two tokens:
`With to-date: [node:field_my_date:to-date:raw]`
`With end-date: [node:field_my_date:end-date:raw]`
4. Save the node. Verify that only the one with `end-date` is being replaced. The other is blank, since there is no replacement.

You can verify that the token tree shows `to-date` by going to Configure in the Page content type (after having added the date field as above), clicking URL alias, and then click the link to show the tree.
<img width="778" alt="Screen Shot 2024-09-08 at 2 45 49 PM" src="https://github.com/user-attachments/assets/c0df11d9-b0de-4b79-9a2b-eb009877cc46">

## Actual behavior

`to-date` is documented, but it doesn't work. `end-date` is not documented, but it works. 

## Additional information

Since `to-date` has never worked, I propose to change the documentation of the token tree to `end-date` instead of changing the existing code for the token replacement.

**Comment by argiepiano** [comment]
PR ready for review and testing: https://github.com/backdrop/backdrop/pull/4864

**Comment by avpaderno** [comment]
The proof the correct token is [node:field_my_date:end-date:raw] is in [`date_tokens()`](https://docs.backdropcms.org/api/backdrop/core%21modules%21date%21date.tokens.inc/function/date_tokens/1).

```php
// Create tokens for the field's "End date".
if (($date_tokens = token_find_with_prefix($tokens, 'end-date')) && !empty($item['value2'])) {
  // Load the to date and convert to a unix timestamp.
  $date = new BackdropDateTime($item['value2'], $item['timezone_db'], date_type_format($item['date_type']));
  if (!empty($date) && $item['timezone_db'] != $item['timezone']) {
    date_timezone_set($date, timezone_open($item['timezone']));
  }
  $timestamp = !empty($date) ? date_format_date($date, 'custom', 'U') : '';
  // Generate the token replacements, using the date token type provided
  // by system.module.
  $replacements += token_generate('date', $date_tokens, array('date' => $timestamp), $options);
}
```

Differently, that code should contain `$date_tokens = token_find_with_prefix($tokens, 'to-date')`.

**Comment by argiepiano** [comment]
Actually I disagree with your proposed fix. My proposed fix is to use `end-date` instead of `to-date` in `date_token_info()`

The rational for this is:
- `to-date` never worked. Therefore changing it to `end-date` will not break those sites, as they were already broken.
- `end-date` did work, and some site builders (like myself) may have figured out that this is the correct replacement (`to-date`) and may have used that in places. So, the fix will not break those sites

**Comment by avpaderno** [comment]
I am not proposing any fix. What I showed is the proof that the code in `date_token_info()` is wrong.

**Comment by argiepiano** [comment]
Oh, ok. Then, since you are familiar with this problem, could you please do a code review and test? It'd be wonderful if you could mark this as a WFM or RTBC.

**Comment by indigoxela** [comment]
I just got baffled by this. :wink: 

I wondered, why no tests would have failed, but realized, that the token test in date_field.test actually _uses_ "end-date". The only occurrence of "to-date" is in date_token_info().

And that went in 1:1 from the contrib date (D7) module, which has the same mistake.

The correct fix is to update date_token_info(), as the PR does. :+1: 
It's actually a one-liner fix. All the other changes are coding standard fixes. RTBC!

**Comment by argiepiano** [comment]
Thanks, @indigoxela. Would you please add a milestone?

**Comment by indigoxela** [comment]
FTR, I didn't verify with the token filter, but ran token_replace() with a node as param like:

```
$node = node_load(1108);

$foo = token_replace('aaa [node:field_timestamp:end-date:short]', array('node' => $node));
$bar = token_replace('aaa [node:field_timestamp:to-date:short]', array('node' => $node));

debug($foo);
debug($bar);
```
Yes, of course only _end-date_ actually ever worked. :grin:

**Comment by quicksketch** [comment]
Nice, thank you @argiepiano! I merged https://github.com/backdrop/backdrop/pull/4864 into 1.x and 1.28.x. Thank you @avpaderno and @indigoxela for reviewing and testing!
