### ISSUE TITLE
Responsive tabs for Seven - Fallback to accordion perhaps?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#671]
This is what happens to tabs in Seven when they can't fit the page width:

![chrome-horizontal_bar_in_seven](https://cloud.githubusercontent.com/assets/2423362/5990678/e347f75a-aa10-11e4-9362-3577d3c0cad6.gif)

Can we have it fall back to accordion?

**Comment by docwilmot** [comment]
Ugh the tabs! The hideous tabs! Best I can contribute for now.

**Comment by Bojhan** [comment]
@klonos We resolved this rather well in core - see https://www.drupal.org/node/1490402

**Comment by klonos** [comment]
@Bojhan: yeah, I've been following that issue since at least April 2013. The reason why I didn't mention this solution here is because the whole design is heavily based on the D8 styleguide and we are trying to differentiate ourselves here.

Perhaps the follow-up could be of some use: [Abstract the Seven tabs functionality for reusability](https://www.drupal.org/node/2207371)

**Comment by klonos** [comment]
...more than half a year later (after most of the intended theme redesign is in place), the situation is now worse:

![backdrop-local_tasks_tabs_disappear_on_small_screens](https://cloud.githubusercontent.com/assets/2423362/10152666/fe240ca0-6697-11e5-90f9-14e9e1f12652.gif)


...instead of the tabs wrapping when the screen width is not enough, they now disappear!!

**Comment by Bojhan** [comment]
@klonos I dont think the design is really "style-guide" its relatively functional. But there are plenty of patterns that you can use which arn't Seven a-like.

**Comment by wesruv** [comment]
Arrgg, that's my bad. Looked at D8's admin, they're using some JS for this, and I can't think of a better way to handle it.

I'm on this.

**Comment by wesruv** [comment]
Thanks for the great tickets @klonos :smile:

**Comment by quicksketch** [comment]
Thanks @wesruv! I personally find the D8 JS-based approach to be pretty good. And I consider more of a bug-fix than an explicit styleguide decision. In any case, I think we all have confidence in Wes doing something effective and appropriate.

**Comment by klonos** [comment]
> In any case, I think we all have confidence in Wes doing something effective and appropriate.

:+1:

**Comment by wesruv** [comment]
@klonos @quicksketch @jenlampton @dariusgarza 

Whatchoo think?
Demo: https://drive.google.com/open?id=0BzY54DXqV6bNY2tfUjAyYjZhbnM
Code: https://github.com/backdrop/backdrop/pull/1142

**Comment by klonos** [comment]
Needs a little more tweaking here and there as you say yourself on the video, but in general this looks really good.

The active tab issue bothered me quite a bit and I tried to come up with a sensible way to address it, but I'm afraid that in the end we'll simply have to drop the idea of maintaining tab order (same as D8).

Alternatively, is there a way to count how many tabs come before and how many after the active tab? If so, then instead of always having the button to the right, we could adapt and collapse the side that holds the most tabs. If most of the tabs are on one side, this will work and look nice, but if the amount of tabs to the left is about the same number as the tabs to the right, it might look silly. Ultimately, there will be only one tab that fits the view port, so tabs from either side will have to be collapsed and I'm not sure that having two buttons on both sides of the active tab would look good.

...as I said, I did put my thinking cap on (alright it was a thinking cup I used*), but couldn't come up with something that would work nice in all cases. Tricky one this one.

* I didn't pour it on me, I had a few sips.

**Comment by quicksketch** [comment]
:heart:

I also think this looks really good. I like the "collapse only what's needed" approach, which is similar to what we do in the admin bar.

The active tab question... The current implementation doesn't bother me. I don't think we could rearrange the tabs to make the active one shown if we stick with the current collapsing approach. Because there may be 2 or 3 tabs shown while others are hidden, including the active tab would result in weird rearranging of items based on how many were shown. That sounds like it would be both difficult to implement and probably jarring for the user.

Styling still needs work (as noted in the video). A stab at how this might look: left-align the entire drop-down items to line up with the left edge of the shown tab(s). Extend the drop-down item width to be equal with the right edge of the ellipsis button. If needed due to long text, allow drop-down items to push the right edge out further until text fits. Sloppy sketch:

![selection_008](https://cloud.githubusercontent.com/assets/100206/11916869/77194902-a6a0-11e5-8c84-229720ab1568.png)

I'd also be tempted to try and make the tabs "push down" the content when opened, rather than being absolutely positioned and floating over the top. But that's something that may take trying out to see if it feels better or worse.

Great work! In any case, so much better than just rudely making the tabs disappear!

**Comment by klonos** [comment]
> I'd also be tempted to try and make the tabs "push down" the content when opened, rather than being absolutely positioned and floating over the top. But that's something that may take trying out to see if it feels better or worse.

That's what D8 does. They "detach" the tabs and make it some sort of menu place within the page header section:

![d8-collapsed_tabs_expanded-small_screen](https://cloud.githubusercontent.com/assets/2423362/11916926/0009eaf8-a743-11e5-93fa-801c4186f815.png)

If you switch to a wide screen while this tabs menu is expanded, you get this weird thing:

![d8-collapsed_tabs_expanded-wide_screen](https://cloud.githubusercontent.com/assets/2423362/11916933/38e202e8-a743-11e5-93d8-a50510a5e1c6.png)

**Comment by klonos** [comment]
...I don't personally like it. It converts the tabs to something menu-like. I prefer @wesruv's way better.

**Comment by quicksketch** [comment]
Thanks @klonos. Your screenshot also points out what would happen if we did my suggestion and multiple tabs were visible... you'd end up with really wide items in the drop-down that are 2 or 3 tabs wide.

> If you switch to a wide screen while this tabs menu is expanded, you get this weird thing:

I'm pretty sure that particular problem is the implementation just not adapting to window.resize(). Seems like no matter what we do, we could avoid the problem of it not readjusting when it should.

In any case, again, all still better than what we have.

**Comment by wesruv** [comment]
I had a thought, re: active tabs!

We could have 3 behavior breakpoints. 
If we can fit all of the tabs, we don't do anything and have regular tabs.

If we can fit the active tab in with either:
* all the tabs before it
* all the tabs after it
We hide either the tabs before or after the active tab. The dropdown button would then be on the left or right, depending on which side we 'collapsed'.

If we can't do that, we do what D8 is doing, active tab on top and the others in a dropdown. 
Unless we want to include the current location in the breadcrumb or title (which may not be as intuitive), this is necessary since there's no other way the user would know which page they're on.

I think this gives us the best possible user experience and wouldn't create 'heavy' JS.

The reason I avoided lining up the right side of the dropdown with the dropdown button was because I'd be setting more styles in JS. Right now I'm only setting one, and the more styles in JS the more my soul hurts :stuck_out_tongue:, but if it's the best possible UX/design to line that up, I'll suck it up!

We'll see how it looks when I implement what I described above.

**Comment by wesruv** [comment]
I'm also making an assumption in my code, and I hope it's safe, the assumption is that the # of tabs, or the text inside them will not change once the page has loaded. I take their size at the beginning and hold on to it, so I can change the size later and know how much space I'll need if the viewport can changes.

It feels like a safe assumption, but I thought I'd check :stuck_out_tongue:

**Comment by klonos** [comment]
I don't see any reason why the tab # or their text should change once the page has loaded and the "hide whichever side makes the rest fit" plan seems like a good one.

**Comment by wesruv** [comment]
New approach with a better solution for keeping the admin tab in view:
Video Demo: https://drive.google.com/open?id=0BzY54DXqV6bNUThsaGswODNuZ0E
Code is still: https://github.com/backdrop/backdrop/pull/1142

@klonos @quicksketch, would love to hear what you think!

**Comment by klonos** [comment]
:heart: :heart: :heart: :+1: I love this! Thank you @wesruv 

I think you have addressed all concerns. Love the idea of converting the active tab to some sort of header when all tabs (before/after it) need to be hidden under a single "more" button!

**Comment by Graham-72** [comment]
A brilliant piece of work!

**Comment by klonos** [comment]
...comments/review and food for thought:

During my tests (firefox x64 on Win8.1 x64), instead of an ellipsis, I get a "�" sign:

![backdrop-issue671-seven_responsive_tabs-questionmark_instead_of_ellipsis](https://cloud.githubusercontent.com/assets/2423362/11990256/213176fa-aa5f-11e5-8ecb-ddf1cdea3ea5.png)

...code inspect from firebug:

```
.expand-dropdown-tabs-control::before {
	content: "?";
	font-weight: bold;
}
```

I understand that this is WIP, but as a todo we need to address the width of the collapsed/expanding menus.

Also, when I made the view port narrow, the "more" tab with the ellipsis got hidden off screen (1st screenshot partially hidden, second gone):

![backdrop-issue671-seven_responsive_tabs-more_tab_hidden_in_narrow_screens](https://cloud.githubusercontent.com/assets/2423362/11990296/a550f528-aa5f-11e5-8f8c-a63ccb59d929.png)

![backdrop-issue671-seven_responsive_tabs-more_tab_hidden_in_narrow_screens-gone](https://cloud.githubusercontent.com/assets/2423362/11990320/eb27c6bc-aa5f-11e5-920d-6c5a1bf29fc9.png)

Can we make sure it stays within view port somehow?

In your demo video, towards the end (3:45 I think) you resize the window to a point where the text of the active/header tab momentarily wraps into two lines:

![backdrop-issue671-seven_responsive_tabs-demo_video-active_tab_text_wrapped](https://cloud.githubusercontent.com/assets/2423362/11990363/8a99784e-aa60-11e5-9434-d1a616481ae2.png)

...I couldn't reproduce the same effect in my environment (issue with the disappearing ellipsis I describe above), but it seemed as a good idea in general if we could somehow incorporate text wrapping of tabs that contain two words or more once we hit certain breakpoints. Mockup/hack of how it would look:

![backdrop-issue671-seven_responsive_tabs-tab_text_wrapped](https://cloud.githubusercontent.com/assets/2423362/11990577/c76420aa-aa63-11e5-97c4-465fab775883.png)

...and here's a few glitches that I came across while playing with things that we should account for:

- *If* we decide to go with the text wrap idea, we'll need to also adjust height:

![backdrop-issue671-seven_responsive_tabs-tab_text_wrapped-adjust_height](https://cloud.githubusercontent.com/assets/2423362/11990619/3ff57c30-aa64-11e5-97c8-5db5cd48a7ed.png)

- All tabs are vanished when you maximize the window?! This is not an "if" thing. It actually happens when resizing from the breakpoint that shows only the single active/header tab straight to full window width (hitting the maximize window button):

![backdrop-issue671-seven_responsive_tabs-tabs_gone_on_window_maximize](https://cloud.githubusercontent.com/assets/2423362/11990665/d353991c-aa64-11e5-9cf0-a51667011567.png)

It doesn't happen when you maximize while more than one tab is shown and it doesn't happen if you slowly resize the window by dragging the window border.

**Comment by docwilmot** [comment]
Very great work @wesruv 
And good reporting @klonos

**Comment by wesruv** [comment]
> During my tests (firefox x64 on Win8.1 x64), instead of an ellipsis, I get a "�" sign:

That's really odd since we're both getting the same webfont :confounded: I'm currently using the ellipsis character, instead of typing 3 periods, no reason I have to though.

> I understand that this is WIP, but as a todo we need to address the width of the collapsed/expanding menus.

Not sure what this intends?

> Also, when I made the view port narrow, the "more" tab with the ellipsis got hidden off screen (1st screenshot partially hidden, second gone):

It appears the browser you're using is enforcing a minimum viewport width... I don't think there's anything I can do about that.

> but it seemed as a good idea in general if we could somehow incorporate text wrapping of tabs that contain two words or more once we hit certain breakpoints.

From a technical perspective, I have no idea how I'd do this... CSS can force smaller widths, and if a word is too long it'd break. JS might be able to figure this out, but it seems like a lot of processing for not enough gain.

From a UI/UX perspective I'm hoping that this page is the worst case scenario for how many tabs and how long the text is. If it isn't I think we need to work it out from a verbiage/UI and not from a technical standpoint.

> All tabs are vanished when you maximize the window?! This is not an "if" thing. It actually happens when resizing from the breakpoint that shows only the single active/header tab straight to full window width (hitting the maximize window button):

That's no good! I'll check into that.

**Comment by klonos** [comment]
>> I understand that this is WIP, but as a todo we need to address the width of the collapsed/expanding menus.

> Not sure what this intends?

![backdrop-issue988-expanded_tabs_too_wide-1_tab](https://cloud.githubusercontent.com/assets/2423362/12002996/c134cf4e-ab63-11e5-8130-b3125c1f02e5.gif)

![backdrop-issue988-expanded_tabs_too_wide-2_tabs](https://cloud.githubusercontent.com/assets/2423362/12002997/c1378ce8-ab63-11e5-9bb6-03da6ec020c5.gif)

![backdrop-issue988-expanded_tabs_too_wide-3_tabs](https://cloud.githubusercontent.com/assets/2423362/12002998/c13dd0f8-ab63-11e5-9aa6-9d46494c6eef.gif)

![backdrop-issue988-expanded_tabs_too_wide-4_tabs](https://cloud.githubusercontent.com/assets/2423362/12002999/c1410566-ab63-11e5-8121-291de505d028.gif)

I'd like to know what others think about a couple of things:

- Having the header tab replicated in the set of the expanded tabs menu and preserving the tab order makes perfect sense, but I think it looks funny when it is the only visible tab (mobile screens) *and* it is the first one at the same time (last screenshot). In this specific case when the rest of the tabs menu is expanded, we have the same tab be shown twice (once as the header tab and another time as the first tab of the expanded menu). Do you think it makes sense to omit it from the expanding tabs menu in this case or would we be complicating things too much?

- The way it is now, the expanded set of tabs does not collapse on mouse clicks outside the tab menu. One has to click on the "more" tab to hide it. I think we should have it hide when we click anywhere else other than the expanded tabs menu. How do others feel about this?

**Comment by klonos** [comment]
...actually, I think we should be omitting the first and last tabs from the expanding tabs menu *when they are the active ones*. Here's how the menu looks with the last tab active:

![backdrop-issue988-expanded_tabs-last_tab_active](https://cloud.githubusercontent.com/assets/2423362/12003096/7f9dfa94-ab66-11e5-9342-61f38dbaf670.gif)

**Comment by klonos** [comment]
...I don't know. I mean this is a great solution/idea, but there are a few things that bother me and I honestly cannot figure a smart way to handle them. Guess I'm bothered by the fact that the best we have come up with is not "perfect".

**Comment by klonos** [comment]
...ok I'm throwing this out there and you tell me what you think about it: how about instead of having a single tab menu expanding downwards, we have two. One would expand upwards and will hold the tabs *before* the active one (or not show at all if the active tab is the first one) and a second tab menu expanding downwards that holds the tabs *after* the active one (or again not shown if the active tab is the last one).

This way, we won't have to duplicate the active tab in the expanding menu and it will still be shown in the correct order. Hack/mockup that demonstrates the idea (notice how I used the [up/down arrow](https://fortawesome.github.io/Font-Awesome/icon/arrows-v/) to denote that there are tabs collapsed both before and after the current active one):

![backdrop-issue988-expanded_tabs-up_down_menu](https://cloud.githubusercontent.com/assets/2423362/12003209/99f8112e-ab69-11e5-8472-4f73fb0f7f88.png)

**Comment by klonos** [comment]
>> but it seemed as a good idea in general if we could somehow incorporate text wrapping of tabs that contain two words or more once we hit certain breakpoints.

> ... it seems like a lot of processing for not enough gain.

Not having strong feelings about this - was just thinking out loud. The gain would be that in smaller widths where we'd normally have to collapse tabs and hide some of them in a menu that requires an additional click, if we could have some of the tabs shrink in width (by wrapping their text), we'd then be able to show all/most of them and save the user the extraneous clicks,

**Comment by klonos** [comment]
...so instead of this:

![backdrop-issue988-tabs_collapsed](https://cloud.githubusercontent.com/assets/2423362/12003305/00d35716-ab6d-11e5-84da-79d53090498d.png)

...we'd have something like this:

![backdrop-issue988-tabs_text_wrapped](https://cloud.githubusercontent.com/assets/2423362/12003307/0c5914a4-ab6d-11e5-8c6d-0d3860df1679.png)

**Comment by klonos** [comment]
Essentially, we'd roughly have this responsive plan...

- desktop/wide screens: tabs as usual
- tablets: tab text wrapped
- mobile: tabs collapsed in a tab menu with the active tab as header tab

**Comment by quicksketch** [comment]
Great work @wesruv! When it was described and from the screenshots @klonos has provided (thanks!) I didn't really get it entirely. You really have to watch the video to get the full effect of it, and then it looks pretty darn good!

I think the desktop and tablet (aka "some but not all tabs" version) look great. I am slightly bothered by the excessive width of the drop-down items as shown by @klonos as well.

I also think @klonos's suggestion above (https://github.com/backdrop/backdrop-issues/issues/671#issuecomment-167236070) sounds great for the mobile implementation; though that makes mobile (aka single-tab shown version) act a bit differently than the tablet/desktop version. What do you think @wesruv?

The last suggestion (wrapping tab text with CSS if it's possible to fit all tabs) seems optional to me. This screen we're looking at in the video is the worst-offender as far as long/multiple tabs go in pretty much all of Backdrop. It's possible in the future we may be able to move "Comment fields" and "Comment display" elsewhere, making it so that we only have 3 tabs here, and "Manage fields" and "Manage display" may become just simply "Fields" and "Display".

**Comment by wesruv** [comment]
I'm also a fan of the https://github.com/backdrop/backdrop-issues/issues/671#issuecomment-167236070 approach. It'll take some brainpower to do, for instance we won't want the tabs going above the top of the screen... but it's way better UX and I think it'll be fun to code up :stuck_out_tongue: 

I'm not a fan of wrapping text  tabs, I appreciate what it's going for, but I think it takes away from their 'tab appearance' and I think the feature would be a pain to write/work out bugs.

I'm going to spend some time in a graphical editor and mess around with the design, unless @dariusgarza wants to do that. I think a fresh pair of superior designer eyeballs could make this sing. I'll try to fix the UI issues @klonos has pointed out. 

So far I've just been in code and I'm a terrible 'design with HTML/CSS' designer. I'm a pixel pusher at heart.

**Comment by klonos** [comment]
> ...we won't want the tabs going above the top of the screen

I have thought of that issue too, but intentionally did not mention it in order to "sell" the idea first. :smiling_imp: 

With this specific page, when we switch to mobile and only one tab is shown, the available space between the top of the screen and the top of the tab is ~120px:

![backdrop-available_space_between_tabs_and_top_of_page-120px](https://cloud.githubusercontent.com/assets/2423362/12008798/312bcb66-acab-11e5-8064-e4c2f06d16d7.png)

...at best, it gets up to ~140px when the screen is too narrow and the breadcrumb gets wrapped into two lines:

![backdrop-available_space_between_tabs_and_top_of_page-140px](https://cloud.githubusercontent.com/assets/2423362/12008800/41882702-acab-11e5-9781-101146f8a2f3.png)

Now, if the last tab (Comment display in our use case) is active, we need ~156px to show the rest of the 4 tabs. That would get way out of screen view.

As previously said, I hate it that the best we seem to be coming up with is not perfect. :disappointed:

**Comment by wesruv** [comment]
Here's an idea for a better look when the tabs are responsive. 

I think I'm going to refactor the code a little bit so it's easier to right align the drop down with the dropdown control (which I believe I resisted doing before :flushed: )

Let me know what you think!

![image](https://cloud.githubusercontent.com/assets/5607236/12068512/bbb58c4c-afdd-11e5-86ec-0e18e6230f86.png)

**Comment by klonos** [comment]
Looks really good to me. Mockups or actual code we can test?

**Comment by wesruv** [comment]
Mockups for now :)

**Comment by klonos** [comment]
OK then. Was just asking because I was about to point the fact that the second mockup has the "Manage display" tab shown twice. If it was code, it'd be a glitch. Fine since that's just a mockup.

Looking forward to testing actual code once you're ready. Thanx for the time and energy you are putting in this.

**Comment by quicksketch** [comment]
These mockups looks glorious to me.

**Comment by wesruv** [comment]
New demo here: https://drive.google.com/file/d/0BzY54DXqV6bNMnJjcDFMM1llWHM/view?usp=sharing
Code is still here: https://github.com/backdrop/backdrop/pull/1142

I think I got a working solution and everything is good to go &lt;knocks on wood&gt; 
I ended up using a different arrow than I designed to stay more consistent with existing elements (thinking of collapsible fieldgroups), but kept everything else the same as the mockup.

Let me know how it's working/not working for you all!

**Comment by wesruv** [comment]
Oh, one other thing worth mentioning, the way I determine the dropdown tab widths between the mobile version and the 'all tabs fit version' is:
widestTabWidth + standardPadding + spaceForTheGrayBarElement

Where before I was doing it in CSS, not knowing what content would be in it, making those extra wide tabs.

... come to think of it there is one assumption I may need to re-evaluate... I'm assuming at mobile that tab's text will never wrap. If they do it will throw off the positioning of the active tab in the dropdown. I'm using a static tabHeight that I get at the very beginning.

If that's a bad assumption I could probably make that more dynamic, based on actual tabHeight, in case tab text does wrap at mobile.

**Comment by quicksketch** [comment]
> I'm assuming that a tab's text won't wrap at mobile.

Could we force non-wrapping text and cut if off with an ellipsis? It's going to have to be a long title in order to wrap in the first place, which shouldn't be happening in the first place, so cropping may be an acceptable solution in this case. Thoughts?

**Comment by quicksketch** [comment]
Great job @wesruv! This implementation is truly magical.

I ran into a couple of minor issues. Get ready to do some gnarly pixel wrangling :confounded: 

Partially-collapsed tab pixel gap:
![selection_021](https://cloud.githubusercontent.com/assets/100206/12077256/99b02990-b190-11e5-8a97-e1620631188a.png)

Fully-collapsed and open pixel gap:
![selection_023](https://cloud.githubusercontent.com/assets/100206/12077265/a9f44660-b190-11e5-8f47-e68df9e89887.png)

I *always* get the 3-second fallback on page load. I saw that there was some font-loading detection code in place, but it didn't seem to work on my browser (Firefox, Ubuntu, latest) and the tab behavior takes a very noticeable amount of time to load:
![selection_022](https://cloud.githubusercontent.com/assets/100206/12077258/a5018406-b190-11e5-9287-ec4ce997f657.png)

Would it be possible to apply the behavior immediately without waiting for the font to load, and then resize again after the font is loaded?

I also left a couple items of feedback in the PR https://github.com/backdrop/backdrop/pull/1142

Really this thing works like a dream. This is just great great great!

**Comment by jenlampton** [comment]
this looks ***fantastic*** !!!

**Comment by wesruv** [comment]
@quicksketch Hrmmm.. if it's taking 3 seconds every time that might mean that my fontsLoaded functionality isn't working correctly, unless it's taking 3 seconds for the font to load? But I think I could make it run twice, immediately and when the font has loaded.

**Comment by klonos** [comment]
Awesome! ...simply awesome. Thanx @wesruv 

>> I'm assuming that a tab's text won't wrap at mobile.

> Could we force non-wrapping text and cut if off with an ellipsis? ...Thoughts?

:+1: 

...minor nit-picking: the big(ger) arrow in the design looked much better IMO and more suiting for mobile (that's when it shows up after all). Please do not let this comment stop you from committing this though, but if we are to keep the current implementation I have another suggestion: either change to a left-pointing arrow when collapsed and switch to a downwards-pointing one when expanded (to be consistent with the arrow behavior of fieldsets) or use a tri-state, up, down, up/down arrow depending on whether there are collapsed tabs before, after or on either side of the active one respectively. For example, it just looks really funny to be clicking on a downward-pointing arrow and have the tab-menu expanding upwards:

![backdrop-issue671-arrow_down-menu_up](https://cloud.githubusercontent.com/assets/2423362/12079913/e983a7f4-b29d-11e5-88e7-de88040d19e6.gif)

Also a few nits with mouse-over highlighting:

![backdrop-issue671-hover-over_highlighting](https://cloud.githubusercontent.com/assets/2423362/12078654/5cb22c76-b26e-11e5-91b8-2a31eba57160.gif)

...notice how with the non-mobile version the hover-over is triggered and the tabs color changes to the darker gray when the mouse is over the tabs themselves as well as when it is over the square part to the right of them. With the mobile version, the hover-over is only triggered when the mouse is over the tabs - not when it's over the square.

Also, the single/active tab when collapsed has a hove-over effect where it changes from white to a light gray color (and the square with the arrow to a darker gray), while the when multiple tabs are shown, there is no hover-over reaction for the active tab.

**Comment by wesruv** [comment]
Just pushed again, I think I fixed/added everything from the feedback except this one, which I'd like other's opinion on:

> Also, the single/active tab when collapsed has a hove-over effect where it changes from white to a light gray color (and the square with the arrow to a darker gray), while the when multiple tabs are shown, there is no hover-over reaction for the active tab.

The active tab on desktop doesn't *really* do anything since it's a link to the current page, but at mobile the 'active tab' is a control element for the dropdown. So I think having a hover effect on mobile, but not on other sizes is good.

Granted, this probably doesn't matter because I doubt many people are going to see the mobile interface with a mouse interface to hover with :stuck_out_tongue:

**Comment by wesruv** [comment]
@quicksketch re:font loading, I figured out I have the Open Sans font on my computer, so I wasn't getting a very realistic experience, lol! I removed it and put network throttling on and got a similar experience to you. I upped the timer to 6 seconds. If the font doesn't load by then then we're having serious issues.

But this **should** only happen on first page load, the font should get cached after that and load very quickly.

**Comment by wesruv** [comment]
But I did make it so the tabs render as immediately and then I rework widths after the font has loaded.

**Comment by quicksketch** [comment]
Again, still so excited about this. I tried out the PR again and it looks good. Font loading problems are gone.

> Granted, this probably doesn't matter because I doubt many people are going to see the mobile interface with a mouse interface to hover with

Good point, not worth worrying about.

In using it, I found that my expectation was that if I clicked off the tabs, they would collapse. But right now the only way to close the tabs is to click on the arrow a second time.

**Comment by wesruv** [comment]
Donezo! PR has been updated!

**Comment by quicksketch** [comment]
I left a few items of feedback in the PR:

- `defaultHeaderPadding`: This variable is still based on the `.l-header` class. Is it possible to eliminate the dependency on the layout classes? I can't tell if it's being used or not in the code.
- The use of `requestAnimationFrame()` might cause browser compatibility issues. However, it does seem to refresh much faster than the Admin Bar approach... maybe we could make it generic with a fallback and put it in backdrop.js?
- Stray debug code in there needs to be removed.

I tried out the PR again locally and it works just fantastic. Functionality-wise I think we're spot-on here. Let's get the last clean up completed!

**Comment by quicksketch** [comment]
Merged PR at https://github.com/backdrop/backdrop/pull/1142. Thanks @wesruv for this amazing work! The finished code is quite readable too. Nice job! Thanks @klonos for the great idea on the mobile version. Brilliant all around.

**Comment by klonos** [comment]
> Thanks @klonos for the great idea on the mobile version. Brilliant all around.

Thanx, but I don't consider this my idea at all. I just reported an issue with tabs wrapping in a funny way about a year ago. All credits go to @wesruv 

We need to find a cool name for this UI thing (something "catchy" like *westabs*) and for when someone comes up with such brilliant UI/UX solutions we should say they "pulled another wesruv"!
