### ISSUE TITLE
Typo in views_plugin_display::init()

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#6721]
## Description of the bug

On a Drupal 7 upgrade that I'm working on, I saw a bunch of notices in the log after I cleared the cache:
> Invalid display extender @extender

This struck me as strange, and when I tracked down the message, it was clear that there was a typo:

 - `watchdog('views', 'Invalid display extender @extender', array('@handler' => $extender));`

Should rather be:

 - `watchdog('views', 'Invalid display extender @extender', array('@extender' => $extender));`

After changing this locally and clearing the cache, the notices are all still there (as expected), but more helpful:
> Invalid display extender metatags

**Comment by avpaderno** [comment]
I would rather not add empty documentation comments to methods. Adding documentation comments should be left for a different issue, which could also add the missing `public` visibility.

**Comment by laryn** [comment]
Fair enough. My editor tries to bring old code up to standards automatically, but I'll strip out that stuff.

**Comment by laryn** [comment]
@avpaderno We're back to the basics.

**Comment by avpaderno** [comment]
The MR does what it is expected to do. 👍🏻

**Comment by quicksketch** [comment]
I merged this into 1.x and 1.29.x. Thank you @laryn and @avpaderno!
