### ISSUE TITLE
Increase minimum MySQL version to 5.5

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6724]
## Description of the need

If we merge https://github.com/backdrop/backdrop-issues/issues/6466, it will effectively remove support for MySQL 5.0. According to telemetry data, we don't have any sites running any MySQL versions less than 5.5 (and probably nearly all of those are [actually newer versions MariaDB that are misreported](https://github.com/backdrop/backdrop-issues/issues/5447)).

MySQL 5.5 was released in 2010 and hasn't been supported since 2018. But since we have reporting sites on this version (at least until they update to fix the reporting error), we shouldn't remove support for it.

[Here's the table of support from Wikipedia](https://en.wikipedia.org/wiki/MySQL):

![image](https://github.com/user-attachments/assets/7701b7eb-12b9-42f5-a0c6-f9f51248de3c)

## Proposed solution

Increase the minimum MySQL version officially to 5.5. Both in the `core/includes/database/mysql/install.inc` class and on the [Installation Requirements Page](https://backdropcms.org/requirements).

## Alternatives that have been considered

We could just bump to MySQL 5.1 since the issue we had a work-around for only existed in MySQL 5.0.

## Additional information

We have a precedent for removing support for ancient software in [starting to require PHP 5.6](https://backdropcms.org/news/backdrop-cms-drops-support-for-php-versions-prior-to-56), dropping support for versions of PHP that were supported in Drupal 7 at the time.

**Comment by herbdool** [comment]
I agree with this.

**Comment by indigoxela** [comment]
> Increase the minimum MySQL version officially to 5.5

Agreed.

I can't even remember, when I last saw a MySQL version older than 5.5. :wink: 
And our [telemetry](https://backdropcms.org/project/backdrop/telemetry) confirms my impression. (Isn't the purpose of our telemetry exactly that? Verify, when we can drop support for ancient stuff.)

Of course, we could raise to only 5.1, but we couldn't even test to confirm compatibility.
(The GHA we're using for our PR test runs don't provide historic versions.)

Even if we're not gaining shiny new features with that switch, we're at least not claiming to support versions, for which we couldn't even verify support.

**Comment by laryn** [comment]
I agree too

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/4891 that bumps the minimum MySQL version to 5.5.0.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4891 into 1.x for 1.30.0.

Change record: https://docs.backdropcms.org/change-records/minimum-mysql-version-is-now-550

Updated installation requirements page: https://docs.backdropcms.org/documentation/system-requirements
