### ISSUE TITLE
Track Update module usage in Telemetry

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6725]
## Description of the need

Although Telemetry and Update module have similar value: they both provide usage information, we're seeing some interesting divergence between Telemetry and Update module usage tracking. Right now it _seems_ as though 90%+ of all reporting Backdrop sites have Telemetry module enabled, but it's possible that sites simply have Telemetry module turned on and Update module turned off. Some site owners (I'm thinking of @hosef here) have reported they never use Update module because they track updates in a different way (like on a different environment).

Since Update module usage likely differs from Telemetry module usage, we should track how much overlap there is between the data. This could help us determine a better overall count of Backdrop sites out there.

## Proposed solution

We should track if sites have Update module enabled (Yes/No) as a Telemetry data-point.

**Comment by quicksketch** [comment]
Simple PR proposed at https://github.com/backdrop/backdrop/pull/4883.

We've discussed trying to track _all_ enabled modules on a site, but our current Telemetry system is not capable of handling large arrays of data: they need to be simple strings and a set number of values. Tracking modules individually like this seems acceptable to me.

**Comment by yorkshire-pudding** [comment]
Checked code and looks good.
Also patch tested and can confirm that the details now appear in the Telemetry report on the site. I can confirm that the values are updated when the module (Update Manager) is enabled and disabled.
