### ISSUE TITLE
Allow tableselect element options to be disabled

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6730]
## Description of the need

This is the equivalent to [this D9 issue](https://www.drupal.org/project/drupal/issues/2895352).

Currently, when using element `tableselect`, there is no way to mark a row (that is, the checkbox or radio element for the row) as disabled. This feature can be handy to disable some of the items based on logic in the form. For example, in the example below, some of the rows have already been transferred, and therefore should be disabled to avoid accidental double-transfer. 

<img width="880" alt="Screen Shot 2024-10-12 at 9 21 14 PM" src="https://github.com/user-attachments/assets/b412e7ee-4d7c-4e96-963a-4126115b89e5">

## Proposed solution

The fix/addition is very simple, and follow the same fix as the D9 tableselect element. It just uses the `#disabled` property for the radio or checkbox, based on the `#disabled` property found on the root of the row element.  

PR coming.

---
EDIT:
## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now includes the ability to disable tableselect row's checkboxes and radio buttons by setting the row property `#disabled` to `TRUE`.

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4886 provided and ready for testing.

To test, you can use this simple module and navigate to `/ts-row-disable-test`

[ts_row_disable.zip](https://github.com/user-attachments/files/17352993/ts_row_disable.zip)

**Comment by indigoxela** [comment]
@argiepiano many thanks for the handy test module.

Yes, currently there's no easy way to mark a row as disabled, as the item's `#attributes` only apply to the table row.

With the PR patch applied, disabling per row is possible without overriding the whole process function. :+1: Works for me.

The D9/10 commit also contained a functional test. I wonder, if you could add something similar in core/modules/simpletest/tests/form_test.module. Looks feasible, as form_test just needs an additional path with your example code added.

**Comment by argiepiano** [comment]
Thanks, @indigoxela. I've added an automated test. Also, added the class `disabled` to the table row, as it was done in D9. This doesn't make a difference in Basis, but it does turn the row into a lighter hue in Seven.

**Comment by argiepiano** [comment]
And yes, probably a minor release. API documentation will need updating. 

Record change:
Backdrop now includes the ability to disable tableselect row's checkboxes and radio buttons by setting the row property `#disabled` to `TRUE`.

**Comment by herbdool** [comment]
This looks good to me.

**Comment by quicksketch** [comment]
I merged into 1.x. This seems like it's backportable to 1.29.x? I'm leaving RTBC while we figure that out.

**Comment by indigoxela** [comment]
In theory, this shouldn't interfere with existing forms and alter hooks in any way.

On the other hand, it's a FAPI addition. :thinking: Would that be appropriate for a bugfox release? The change is minimal, but it's still a new feature.

**Comment by argiepiano** [comment]
Thanks, @quicksketch. Either way is fine with me. I ended up using a preprocess call in my use case, so it can wait until the the next minor release.

**Comment by herbdool** [comment]
Sounds like there's no pressing need to back port it

**Comment by quicksketch** [comment]
Let's just leave it in 1.30.0 then. Thanks everyone!
