### ISSUE TITLE
Add a preview of the background image to Hero block configuration forms

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#6736]
## Description of the need

There is no preview of the background image of Hero blocks in the block configuration forms.
At least one user reported not realizing that the background image was configurable. This might help.

## Proposed solution

Add a preview of the background image to Hero block configuration forms.

![Screenshot 2024-10-23 162041](https://github.com/user-attachments/assets/a106ad64-51e2-4c47-9fb5-4c097940a835)

## Additional information

Backdrop v 1.29.1

## Draft of feature description for Press Release

Backdrop now includes a preview of the background image of Hero blocks in the block configuration forms

ADVOCATE: @stpaultim

**Comment by docwilmot** [comment]
I've pushed a PR for this, but unfortunately it doesn't show an image for the out of the box hero block. This is because there is no hero block background image out of the box, and Basis theme just has a CSS image that it applies to hero blocks with no background.

**Comment by olafgrabienski** [comment]
> and Basis theme just has a CSS image that it applies to hero blocks with no background.

What do you think about adding the CSS image also to the Seven theme in this case?

**Comment by olafgrabienski** [comment]
> The seven theme doesn't have an image in hero block (...)

I know, but my idea was: If the Seven theme uses somehow the CSS image definition from Basis, the image would show up in the preview when you (use Seven as admin theme and) edit the block. Not sure if something like this would work.

**Comment by docwilmot** [comment]
> 
The seven theme doesn't have an image in hero block (...)

I know, but my idea was: If the Seven theme uses somehow the CSS image definition from Basis for blocks without background image, the CSS image could also show up in the preview when you use Seven as admin theme and edit a block without background image. Not sure if something like this would work.

Its reasonable I agree to assume that *if* the front theme is Basis or a subtheme thereof *and* there is no image then Basis CSS background may be being applied in the front end, but that may be a fragile plan because we couldnt be sure if the CSS was overridden, in a subtheme. And then we'd need to include an image in Seven thats only used for a particular front end theme. Doesnt all sound right TBH.

**Comment by quicksketch** [comment]
This is a nice little improvement. The overall approach looks good to me, I left a few suggestions in a review: https://github.com/backdrop/backdrop/pull/4898#pullrequestreview-2439711742

**Comment by stpaultim** [comment]
More than one person has told me that they did not realize that they could replace the default image. I think that this PR will improve that situation!

**Comment by olafgrabienski** [comment]
> More than one person has told me that they did not realize that they could replace the default image. I think that this PR will improve that situation!

@stpaultim Unfortunatly, the PR doesn't improve the particular situation with the default image, see https://github.com/backdrop/backdrop-issues/issues/6736#issuecomment-2465970469:

> This is because there is no hero block background image out of the box, and Basis theme just has a CSS image that it applies to hero blocks with no background.

**Comment by olafgrabienski** [comment]
I've tested the PR in the sandbox, works for me!

One observation: The image aspect ratio in the preview is the same as the uploaded image. If this ratio isn't extra wide, the preview can seem quite narrow (see example in screenshot below). I think the preview would meet expectations for a hero block better, if it fills the full width of the block configuration window.

<img src="https://github.com/user-attachments/assets/30ecd0e9-4cc0-4acb-a691-8678bd890733" width=500>

**Comment by docwilmot** [comment]
One issue though is that we cannot know what the image will look like on the front end theme, after that theme's CSS alters the image and the block. I think its clearer to show what the native image looks like rather than cropping and forcing a landscape image. Its not a preview of the hero block, its a preview of the image.

**Comment by docwilmot** [comment]
> More than one person has told me that they did not realize that they could replace the default image. I think that this PR will improve that situation!
> @stpaultim Unfortunatly, the PR doesn't improve the particular situation with the default image, see https://github.com/backdrop/backdrop-issues/issues/6736#issuecomment-2465970469:

The current code shows nothing if there is no background image; could we instead of that, show a message saying "No image uploaded, some themes may define the background image in CSS" or something such? Or maybe even just blatantly say, if Basis is front end, "Basis uses a CSS image" or such?

**Comment by stpaultim** [comment]
@docwilmot 

Your suggestion of adding some text when there is no default image would be an improvement. I think we could also display a small thumbnail that represents the current backdrop texture, when there is no image available. 

I recommend one of those two options - UNTIL we build agreement on my preferred solution, which is adding a new default image to Backdrop to celebrate the 30th release. I opened a new issue for that discussion to avoid bikeshedding specific images in this issue - or getting sidetracked discussing whether or not that is even a good idea. 

This PR is a good idea either way.

https://github.com/backdrop/backdrop-issues/issues/6752

**Comment by docwilmot** [comment]
> I think we could also display a small thumbnail that represents the current backdrop texture, when there is no image available.

Unfortunately there is no Backdrop texture, only a Basis texture. See https://github.com/backdrop/backdrop-issues/issues/6736#issuecomment-2471453163.

**Comment by olafgrabienski** [comment]
> I think its clearer to show what the native image looks like rather than cropping and forcing a landscape image.

Agreed! I probably misunderstood the goal, also because there was already a very wide image in the sandbox uploaded from someone before, which covered the full width of the configuration window. The wide display looked quite convincing to me, and when I uploaded an own example, its narrow display looked somehow strange in comparison.

However, if we want to show what the native image looks like, why not use the usual thumbnail, known from image fields (see screenshot)?

<img src="https://github.com/user-attachments/assets/716f64d2-8968-4974-abe7-0ba94d911c62" width=600>

**Comment by docwilmot** [comment]
I went ahead and added the browse button to this PR. Easily removed if there is disagreement but I think it belongs.

**Comment by stpaultim** [comment]
> Unfortunately there is no Backdrop texture, only a Basis texture.

I understood that, but could have been clearer. My point was that we could create a thumbnail of the texture that is ONLY used to represent what is being displayed, even though it is not an image. 

I prefer the idea of adding a new default image.

**Comment by olafgrabienski** [comment]
> The PR actually does display a thumbnail, but the "medium" size, not the "thumbnail" size.

Fair enough! Interestingly, the dimensions changed in the meantime. Maybe by defining the image style in a different way? Anyways, I like the new (less obstrusive) size!

**New:**
<img src="https://github.com/user-attachments/assets/c75222ed-f0ae-46c1-ae06-992f8d1b6d17" width=500>

**Before:**
<img src="https://github.com/user-attachments/assets/30ecd0e9-4cc0-4acb-a691-8678bd890733" width=500>

**Comment by stpaultim** [comment]
Just trying to come up with ideas to shorten the text when there is no image present, under the belief that the less text we use the more likely it will be read.

<details><summary>screenshots</summary>

Current PR
![image](https://github.com/user-attachments/assets/9ec9ffa7-95e9-4377-9242-4bd9f0050d0a)

Shorter Text Suggestion
![image](https://github.com/user-attachments/assets/39b938f1-bf13-4030-939b-b3926d6abf5a)

</details>

**Comment by olafgrabienski** [comment]
I also think that longer text is helpful here. Ideas to improve it a little:

- Add the `description` class (and some margin) to the text element.
- Put most important part in first line.
- Put the rest in a second line, improve wording.

Screenshot:

<img src="https://github.com/user-attachments/assets/453a0d18-0e7b-4bcd-8c5f-fd9b66bd2329" width=500>

**Comment by docwilmot** [comment]
PR updated.

**Comment by stpaultim** [comment]
> PR updated. As usual I cannot reliably advocate, since I'm usually at work during meetings, but I'm happy to be the advocate, so can this get a milestone please?

You don't have to be at meetings to advocate for an issue. You can effectively advocate for an issue by updating the issue on Github and posting notes in Zulilp. Even putting it on the agenda for a meeting, even if you can't be there. 

I don't think I'm advocating for anything yet. I'm interested in this issue and willing to advocate for it.

**Comment by olafgrabienski** [comment]
Thanks for updating the PR, @docwilmot. Tested in the sandbox, works for me!

**Comment by quicksketch** [comment]
I reviewed the PR and it looks great. I add a couple lines of CSS, `@since 1.30.0` lines, and fixed phpcs issues by pushing additional commits to the PR. This looks ready to go! And it adds the media browser for selecting an image from the library too! That's a nice UX improvement.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4898 into 1.x for 1.30.0. Thank you @docwilmot, @izmeez, @olafgrabienski, and @stpaultim for your work on this issue!
