### ISSUE TITLE
Remove core/misc/textarea.js

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#6737]
`textarea` resizing is native in browsers nowadays, thinking we can get rid of core/misc/textarea.js, or maybe make an option to enable/disable it?

Might have to wait until 2.x?

The bottom gray bar is what textarea.js does, the bottom right corner is from the browser (Chrome in this case).

![image](https://github.com/user-attachments/assets/0a0ad67e-d5e0-4116-a8e2-3d9ad6da9033)

**Comment by docwilmot** [comment]
That should already be gone as of https://github.com/backdrop/backdrop/pull/4564
Its not present in current Backdrop: `core/misc`: https://github.com/backdrop/backdrop/tree/1.x/core/misc

**Comment by avpaderno** [comment]
I checked on my site, running on Backdrop 1.29.1: On /admin/config/development/maintenance, I see only the resize widget added by the browser.

**Comment by wesruv** [comment]
Aha, closing as dupe, thanks @docwilmot!
Dupe of https://github.com/backdrop/backdrop-issues/issues/340
