### ISSUE TITLE
Translated content doesn't get aliased path in views path

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#6746]
## Description of the bug

This is a follow-up to #6745 (about views _Title_ fields with links). This one here is about views _Path_ fields:

Paths to translated content which is listed in views, e.g. on the "Manage content" page, aren't rendered as the aliased path. Path aliases in views work only, if interface and content language are the same.

## Steps To Reproduce

To reproduce the behavior:
1. Enable Content Translation, Language and Locale from Backdrop core.
2. Add a second language, i.e. German.
3. Configure the Page content type, go to the tab "Multilingual support", and choose "Enabled, with translation".
4. Create a page of title "Hello world", put some content in the body, set the language to English, and save the page.
The page gets a URL like `example.com/hello-world`.
5. Hit the "Translate" tab, and add a translation.
The translated page gets a URL like `example.com/de/hallo-welt`.
6. Switch the Backdrop interface back to English, using the language switcher in the Admin bar.
7. Go to the _Manage content_ page, edit the view and add a Path field.
8. Back on the _Manage content_ page, inspect the path of the pages created above.

## Actual behavior

The path of the English page "Hello World" is the alias `/hello-world` (as expected).
The path of the translation "Hallo Welt" isn't an alias but the node ID path, e.g. `/node/7`.

## Expected behavior

The path of the translation "Hallo Welt" is an alias, e.g. `/de/hallo-welt`.

**Comment by argiepiano** [comment]
[PR](https://github.com/backdrop/backdrop/pull/4896) submitted.

The PR actually sends the language object to `l()` in order to get the aliased path when available. Before the PR, there was no attempt to get the aliased path, despite the description of the views field!

**Comment by robertgarrigos** [comment]
Great. This PR fixes the problem for me.

![Content___My_Backdrop_Site_-_Vivaldi](https://github.com/user-attachments/assets/4a7504c1-552f-47dc-b163-6a5fe2b23657)

**Comment by olafgrabienski** [comment]
Same here, works for me as well (with slightly different language settings). Many thanks!

<img src="https://github.com/user-attachments/assets/c88850fc-359f-4a41-96ae-b319afa5032f" width=300>

**Comment by herbdool** [comment]
Code looks good too.

**Comment by olafgrabienski** [comment]
Thanks, @herbdool! What do you think about the PR code for the related issue #6745?

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4896 into 1.x and 1.29.x. Thank you @argiepiano, @olafgrabienski, @robertgarrigos, and @herbdool!
