### ISSUE TITLE
Docs for EntityInterface::uri() incorrectly state that NULL should be returned if entity has no uri.

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6749]
## Description of the bug

The [documentation](https://github.com/backdrop/backdrop/blob/c53e13d829406bcfcae365754d8345dd57da69f3/core/modules/entity/entity.class.inc#L69) for `EntityInterface::uri()` incorrectly state that `NULL` should be returned if the entity has no uri of its own.

Returning NULL creates a fatal error when `template_preprocess_entity()` is invoked: `TypeError: Unsupported operand types: null + array`, since that preprocess function [uses](https://github.com/backdrop/backdrop/blob/c53e13d829406bcfcae365754d8345dd57da69f3/core/modules/entity/entity.theme.inc#L22) the `+` array operator with the returned value (NULL).  

Instead, the docs should say that an empty array should be returned.

## Steps To Reproduce

This was originally reported in the `commerce` issue queue: https://github.com/backdrop-contrib/commerce/issues/25
See steps there. A custom, uri-less entity class is needed. 

## Actual behavior

Fatal error when uri returns NULL

## Expected behavior

Not a fatal error.

## Additional information

Backdrop 1.29.1

**Comment by argiepiano** [comment]
PR https://github.com/backdrop/backdrop/pull/4899 submitted and ready for review.

**Comment by quicksketch** [comment]
Thank you @argiepiano and @elisseck! Merged https://github.com/backdrop/backdrop/pull/4899 into 1.x and 1.29.x.
