### ISSUE TITLE
Fast Token Browser Update mistakenly named `field_update_1098()` instead of `system_update_1098()`

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6761]
## Description of the bug

When Fast Token Browser was added to core (#6143), it added an update hook to `system.install`. The update hook is `field_update_1098()`, but it should have been `system_update_1098()`. This seems like it might have been a copy/paste error and we missed it in code review.

## Steps To Reproduce

To reproduce the behavior:
1. Install or update an existing Backdrop site.
2. `SELECT schema_version from system WHERE name = 'field'`. The value should be `1004`, but it is `1098`.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.x (pre 1.30.0)

cc @herbdool

**Comment by argiepiano** [comment]
PR submitted. https://github.com/backdrop/backdrop/pull/4911

**Comment by argiepiano** [comment]
I'm glad this was caught before the release...

**Comment by herbdool** [comment]
I think this does the trick. It would be a lot trickier after the release. I haven't tested.

**Comment by quicksketch** [comment]
Thank you @argiepiano!

> Curious about why you cc herbdool also...

Sorry I should have cc'd you too! @herbdool was the advocate for https://github.com/backdrop/backdrop-issues/issues/6143.

I merged the super-simple https://github.com/backdrop/backdrop/pull/4911 into 1.x for 1.30.0. No need for anything more fancy since this was only ever in a dev release.
