### ISSUE TITLE
Warning thrown when importing a new field instance through configuration manager

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6766]
## Description of the bug

The warning `Warning: Trying to access array offset on value of type null in node_config_create_validate() (line 3747 of /Users/XXX/Sites/localhost/bdtesting/core/modules/node/node.module).` is thrown when you try to import a field instance configuration through the configuration manager.

## Steps To Reproduce
The easiest way to reproduce this is with a development and production site, simply by importing a new field instance created in the dev site, into the production site.

To test on a single test site (e.g. on a tugboat demo site):
1. Create a field and attach it to page type
2. Then attach the same field to post type
3. Go to configuration manager > single export, and copy the json code for the instance you created for the post type
4. Delete the instance from the post type
5. Go to configuration manage > single import and past the code you copied above
6. See the warning notice  

## Actual behavior
Warning thrown.

## Expected behavior
No warning.

## Additional information
- Backdrop CMS version: 1.29.2

There should be a check for null in $all_changes in line 3747. If null, then set $type_created to false.

**Comment by argiepiano** [comment]
Very simply, one line PR provided. https://github.com/backdrop/backdrop/pull/4914

**Comment by quicksketch** [comment]
PR looks good to me.
