### ISSUE TITLE
Call to undefined function block_custom_block_load()

### ISSUE THREAD

**Issue by NormPlum** [backdrop/backdrop-issues#6773]
## Description of the bug

When the Block module is uninstalled you can still try to add custom blocks to a layout but they don't save and the below error is seen in the logs:

`Error: Call to undefined function block_custom_block_load() in form_validate_machine_name() (line 4070 of /var/lib/tugboat/backdrop/core/includes/form.inc).`

## Steps To Reproduce

To reproduce the behavior:
1. Disable and uninstall the Block module
2. Go to the default layout and add a new Custom Block
3. Enter some text and an admin label and press Add Block

## Actual behavior

The spinning icon appears and disappears but 'Add block' popup doesn't go away and no block is added to the layout.
The above error is added to the logs.

## Expected behavior

If adding a custom block to a layout doesn't require the Block module then the block should be added without error. If the Block module is required then there shouldn't be an option to add a custom block to a layout when it's uninstalled.

## Additional information

Debug information:
```
Backdrop CMS:                   1.29.2
Installation profile:           standard
PHP version:                    8.1.30
Drupal 7 compatibility:         on
Database server:                10.7.8-MariaDB-1:10.7.8+maria~ubu2004
Web server:                     Apache/2.4.62 (Debian)
jQuery version:                 3.7.1
jQuery UI version:              1.14.0
CKEditor 5 version: 42.0.2      Used in formats: Basic
```
I used the demo sandbox on Backdropcms.org to test this.

**Comment by stpaultim** [comment]
I tested this as well on a local sandbox site and got what seems to be the same behavior.
```
Backdrop CMS:                   1.30.x-dev
Installation profile:           standard
PHP version:                    8.3.14
Drupal 7 compatibility:         on
Database server:                10.11.10-MariaDB-ubu2204-log
Web server:                     nginx/1.26.2
jQuery version:                 3.7.1
jQuery UI version:              1.14.0
CKEditor 5 version: 43.2.0      Used in formats: Basic
```

Is there a reason someone would disable the blocks modules?

I was able to add a view block, a menu block, and an existing content block - even without the block module.

With the block module enabled, I created a custom block and then disabled the custom block and the custom block seems to be unaffected. 

So far, in my limited testing, the only effect of disabling the block module seems to be preventing the creation of new custom blocks. 

At a minimum, maybe we should update the description of the block module to better indicate the potential results of disabling it.

**Comment by stpaultim** [comment]
Here is a meta issue that links to lots of other "block" related issues: https://github.com/backdrop/backdrop-issues/issues/1427

**Comment by herbdool** [comment]
Maybe we just add `block` as a dependency in `layout`. Not sure if anyone would want to use layout without block enabled. Perhaps. In which case, we'd need to prevent that option from appearing if `block` is not enabled. Interested in making a PR @NormPlum?

**Comment by quicksketch** [comment]
Pull request looks good to me. Like @NormPlum says there's other checks for `block` module right in that same function. The "reusable" option isn't shown if Block module isn't enabled and the machine name field shouldn't be either. The use of the submitted value `delta` is also already wrapped in checks, so this shouldn't cause any issues on submit/save.

**Comment by stpaultim** [comment]
So, what does the block module do. Is it just about "reusable custom blocks" or is there more to it?

I tested the PR and the buggy behavior is gone, but in a weird way. I can now create a custom block without the block module, that was not what I would expect. 

Should we rewrite the description of the block module to be more accurate. It seems to me, that I should have some idea reading this description of what I will loose if I disable this block. Right now, the description is pretty much meaningless to me and doesn't tell me anything about what will happen or not happen, when I disable this block.

![image](https://github.com/user-attachments/assets/cc4295a3-f6e5-442c-874c-ffc34b5763a6)

**Comment by avpaderno** [comment]
The Block module allows to define blocks via the user interface. Any module would add new blocks via `hook_block_info()` (which is what the Block module does too). *Controls the visual building blocks* is not correct, since the Block module does not control them.

**Comment by quicksketch** [comment]
> I have no idea of what the block modules does other than help with Reusable Custom Blocks.

Block module _only_ provides reusable custom blocks. You can even still have "custom blocks" in Layouts, they just can't be reusable without Block module.

`hook_block_info()` is _not_ dependent on block module. You can definitely turn off Block module and still have access to all the blocks provided by other modules (views, the main content block, field blocks, etc).

To improve the situation, `Block` module should probably be renamed `Custom blocks` or `Reusable custom blocks`, since that's the only functionality it provides in Backdrop.

But those issues might want to be separate from this bug fix. I think @NormPlum's PR is good standing alone. Writing descriptions and changes labels can easily turn into a bike shed argument.

**Comment by stpaultim** [comment]
> But those issues might want to be separate from this bug fix.

Agreed.

Marking this Works For Me and as a Bugfix Milestone candidate.

**Comment by quicksketch** [comment]
Thanks folks! Merged into 1.x and 1.29.x. Thank you @NormPlum for filing the issue and supplying the fix!
