### ISSUE TITLE
CKEditor 5 sometimes gets double-binded, duplicate editors

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6774]
## Description of the bug

CKEditor 5 occasionally gets double-rendered. This happens when the `.attach()` behavior gets called multiple times very quickly, before the first editor has finished instantiating, it starts building multiple editors for the same textarea.

## Steps To Reproduce

To reproduce the behavior:
1. Go to `node/add/post`
2. Change the text format to "Raw HTML". Don't enter anything else in the text area.
3. Upload an image in the Image field below the Body field (this triggers an AJAX request, causing an additional `.attach()`)
4. Switch the text format back to "Basic"
5. Two CKEditor 5 instances will be attached, stacked on top of each other.

## Actual behavior

Double-attached editor:

![image](https://github.com/user-attachments/assets/a1279c0f-acb0-4ac4-a7ad-4cf085b2adce)

## Expected behavior

Only one editor should show for the Body field.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.x (1.30.x)
- Web server and its version: DDEV
- PHP version: 8.3
- Database sever (MySQL or MariaDB?) and its version: MariaDB
- Operating System and its version: Ubuntu
- Browser(s) and their versions: Firefox, though it occurs in any browser

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4923 that fixes this issue for CKEditor 5.

There seems to be another issue at hand here where the filter.js `Backdrop.behaviors.filterEditors.attach()` method duplicates its attachments. So this issue might be fixed at that level as well. I'll see if I can make a solution at that level too.

**Comment by quicksketch** [comment]
I filed a second PR at https://github.com/backdrop/backdrop/pull/4924 that fixes this issue _at the filter.js level_.

Filter module's `Backdrop.behaviors.filterEditors.attach()` was incorrectly detaching editors on AJAX requests. When an AJAX request occurs, Backdrop asks all the fields to "serialize" their data so it can be sent in the POST request. When this was happening, filter.js was entirely removing the `.once()` guard class. Making it so that when the AJAX request finished processing, it would rebind all editors.

So the new PR at https://github.com/backdrop/backdrop/pull/4923 fixes Filter module, while https://github.com/backdrop/backdrop/pull/4923 makes CKEditor more robust to handle `.attach()` getting called multiple times very quickly. They're both valid fixes. We could merge them separately, or I could make a combined PR. For now these can be tested individually to show they both fix the problem, following the steps to reproduce.

**Comment by indigoxela** [comment]
Oops, that's easy to reproduce. It's not necessary to upload an image - selecting one from the library already does the "trick". If picking-removing several times before switching back to the Basic format, even more editors show up. And to get rid of them requires to reload the whole page.

I can confirm, that both approaches fix the issue. How about combining them? Just to be on the safe side.
If combining isn't the plan, then https://github.com/backdrop/backdrop/pull/4924 would be my favorite.

**Comment by quicksketch** [comment]
Thank you @indigoxela and @laryn for reviewing!

> How about combining them? Just to be on the safe side.

I closed the separate pull requests and opened a combined pull request at https://github.com/backdrop/backdrop/pull/4927.

**Comment by indigoxela** [comment]
I gave the combined PR a final test - works like a charm. :+1: 
I think, this is good to go. RTBC!

**Comment by quicksketch** [comment]
Thank you @indigoxela and @laryn! I merged https://github.com/backdrop/backdrop/pull/4927 into 1.x and 1.29.x.
