### ISSUE TITLE
Mail headers line endings need to be changed to CRLF for PHP 8

### ISSUE THREAD

**Issue by argiepiano** [backdrop/backdrop-issues#6775]
## Description of the bug

This is the equivalent to D7's issue that was fixed in 7.103 - see Change Record: 

https://www.drupal.org/node/3491626

Issue:
https://www.drupal.org/project/drupal/issues/3319062

And commit:
https://git.drupalcode.org/project/drupal/-/commit/0e0a0915823475554e061a57b01d145d64c243a1

According to the D7 issue, PHP 8 is stricter (at least in some servers) regarding using CRLF at the end of each header line. Currently Backdrop does this in `DefaultMailSystem`:

```php
$mail_headers = join("\n", $mimeheaders);
```

that is, it adds only LF (`\n`) at the end of each header. This was done because, "some MTAs incorrectly replace LF with CRLF" (according to a comment in that class). 

So, previously, if you used CRLF (`\r\n`) at the end of each header line, you might end up with CRCRLF (`\r\r\n`). 

Using only LF (as it's currently done in Backdrop) was fine in PHP 7. But with PHP 8, you end up (in some servers, e.g. LiteSpeed) with faulty headers that look like this (notice no new line between headers - `Content-Type` and `Content-Transfer-Encoding` on the same line, etc).

<img width="1067" alt="Screen Shot 2024-12-13 at 3 20 29 PM" src="https://github.com/user-attachments/assets/c63b47fe-fad1-4fa0-942b-a04f7e8ccccd" />

This causes issues with HTML emails, multipart emails, etc etc.

**Comment by argiepiano** [comment]
PR submitted. After applying the PR, the new headers look like this. Notice that, now, each header starts at the beginning of the new lines. This fixes issues with email clients not understanding those headers. This is a similar problem as reported (and fixed) in mimemail module.

The PR also allows for a new setting that can be added to settings.php, which will override the character(s) inserted at the end of line. `$settings['mail_headers_line_endings']`. This follows the same pattern provided in D7 (except that there, it's a variable). 

<img width="1014" alt="Screen Shot 2024-12-13 at 5 39 05 PM" src="https://github.com/user-attachments/assets/4263dd11-b0a8-438e-bca5-36be8314ef68" />

**Comment by quicksketch** [comment]
Thanks @argiepiano! This looks good to me, and a perfect Backdrop-conversion of a Drupal patch that used `variable_get()` being swapped with `settings_get()`. It makes sense to use `settings_get()` (rather than config) as this may be environment-specific and probably rarely overridden: it should just work regardless of the server used.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4929 into 1.x and 1.29.x. Thank you @argiepiano!
