### ISSUE TITLE
Custom menu breakpoint makes parent Basis CSS load after the child theme skin CSS

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#6778]
## Description of the bug

When I set a custom menu breakpoint it changes the look of the menu. I believe it's because of this in basis_preprocess_page():

```
if ($config->get('menu_breakpoint') == 'custom') {
    backdrop_add_css(backdrop_get_path('theme', 'basis') . '/css/component/menu-dropdown.breakpoint.css', array(
      'group' => CSS_THEME,
      'every_page' => TRUE,
    ));
    backdrop_add_css(backdrop_get_path('theme', 'basis') . '/css/component/menu-dropdown.breakpoint-queries.css', array(
      'group' => CSS_THEME,
      'every_page' => TRUE,
      'media' => 'all and (min-width: ' . $config->get('menu_breakpoint_custom') . ')',
    ));
  }
```

I believe it's placing those two files so they get referenced after the child theme. So I child theme would have to *also* load it's own versions of these files in a hook_preprocess_page().

Original issue for this functionality: https://github.com/backdrop/backdrop-issues/issues/4663

**Comment by herbdool** [comment]
@olafgrabienski Here's a way to reproduce even on the demo site using core Basis and Color. Though I first discovered it on a child theme of Basis that is not using Color.

Steps to recreate:

1. Ensure Basis is the default theme, and Color is enabled.
2. In Basis settings, set the "Header background" to white, and the "Site name and slogan" to black.
3. Create a page and add it to the menu as a child of "About".
4. View Home. It should have a black caret for the drop-down.
5. Go to Menu settings (`admin/structure/menu/settings`) and change it to a custom breakpoint. For example, `62 em`.
6. Refresh Home. The caret will now appear as white.

Before:

![2024-12-16 10 39 39 bd3 lndo site ee6398354304](https://github.com/user-attachments/assets/0ca495ea-ffe9-4d02-9b38-5d7a2924d519)

If you inspect, `skin.css` (created by color) will be highest.

After:

![2024-12-16 10 43 46 bd3 lndo site ab155a6d5936](https://github.com/user-attachments/assets/c654c0d0-c158-4dac-b778-865ec4749982)

When inspecting, `menu-dropdown.breakpoint-queries.css` and `menu-dropdown.breakpoint.css` are now higher and take precedence over `skin.css`.

**Comment by herbdool** [comment]
Going by https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_add_css/1 we may have to add a weight option. But then we'll need to know the weights of the css files currently loaded (if that's possible) and have them load around the same place as Basis' version of `menu-dropdown.css`.

**Comment by herbdool** [comment]
@olafgrabienski I've got a PR for this.

**Comment by olafgrabienski** [comment]
Thanks, I'll have a look, hopefully later today.

**Comment by olafgrabienski** [comment]
@herbdool – I was able to reproduce the issue with the white drop-down caret following the steps described in https://github.com/backdrop/backdrop-issues/issues/6778#issuecomment-2545990426. After applying the PR, the caret became black again, as expected. (And in the dev tools inspector I saw, `skin.css` took precedence over other CSS files.) So it works for me.

I also saw the comments at the PR. Let me know if I should test another time, in case you change something.

**Comment by herbdool** [comment]
@olafgrabienski I've made a slight change. Probably still works but if you've got a second to test, please.

@quicksketch ready for a code review.

**Comment by olafgrabienski** [comment]
@herbdool When I go to the sandbox, I get an error message on most pages:

> Warning: Undefined variable $path in basis_css_alter() (line 14 of /var/lib/tugboat/core/themes/basis/template.php).

(Didn't test anything else in this situation.)

**Comment by herbdool** [comment]
@olafgrabienski oops. I've fixed that now.

**Comment by quicksketch** [comment]
Thanks @herbdool, code review looks good and is passing tests.

**Comment by olafgrabienski** [comment]
@herbdool I've tested the PR in the sandbox. It fixes the CSS issue, but after setting a custom breakpoint I get again an(other) error message on some pages:

> Warning: Undefined variable $weight in basis_css_alter() (line 19 of /var/lib/tugboat/core/themes/basis/template.php).

**Comment by herbdool** [comment]
@olafgrabienski hopefully I've fixed that too now.

**Comment by olafgrabienski** [comment]
Great, works for me, and I see no more errors!

**Comment by quicksketch** [comment]
Final solution looks great. Thanks @herbdool!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4938 into 1.x and 1.29.x. Thank you @herbdool and @olafgrabienski!
