### ISSUE TITLE
Update Block module label and description (in UI)

### ISSUE THREAD

**Issue by NormPlum** [backdrop/backdrop-issues#6781]
## Description of the need

In https://github.com/backdrop/backdrop-issues/issues/6773 we discovered that the Block module's name and description is confusing. Block module "only provides reusable custom blocks."

> To improve the situation, Block module should probably be renamed Custom blocks or Reusable custom blocks, since that's the only functionality it provides in Backdrop.

Currently, Block module has the description: "Controls the visual building blocks a page is constructed with. Blocks are boxes of content rendered into an area, or region, of a web page."

## Proposed solution

Rename Block module and update its description (in the UI). Suggest:

"**Reusable custom blocks**"
"Allows custom blocks to be reused across different layouts."

## Alternatives that have been considered

Leave it as is, but its confusing.

**Comment by stpaultim** [comment]
Another alternative may be to keep the name and just update the description. 

I ONLY suggest this in case it's difficult to change the name of the module. Even if we leave the module name the same, we SHOULD update the descripton (see https://github.com/backdrop/backdrop-issues/issues/6773#issuecomment-2546108243)

**Comment by indigoxela** [comment]
@NormPlum interesting suggestion...

However, renaming a core module can only happen in a major release (Backdrop 2.x...). I's a massive interruption. All dependencies on the module break, all usage of `module_exists()` for that one breaks, all function names change, the API provided by that module changes. That's *a lot*, so renaming should really provide enough benefit to justify such a backwards incompatible step, and I doubt, that's the case here.

But... what seemed to confuse you the most, is the module's *description*. And the good news: that's only a string. :wink: 

https://github.com/backdrop/backdrop/blob/1.x/core/modules/block/block.info#L3

**Comment by indigoxela** [comment]
> Yes, changing the machine name would break stuff. But if we just change the UI name and description that'll help prevent confusion...

Speaking of "confusing": @NormPlum mind to update this issue's title? That one is really, really confusing. And eventually update the issue description, too. :wink: 

Re the actually proposed changes - let's see, what other community members think.

**Comment by stpaultim** [comment]
I think this one is related to: https://github.com/backdrop/backdrop-issues/issues/6531

But, these two issues focus on different parts of the UI and certainly can be considered and treated seperately.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/4942 looks really good.

I'm on-board with these changes. Documentation may need updating in places but this is a backwards-compatible change and really clarifies that Block module isn't responsible for page layout like is in Drupal.

**Comment by stpaultim** [comment]
Works for me.

**Comment by stpaultim** [comment]
I added and then removed the RTBC tag, only becaue not many people have looked at this issue yet. I think it would be good to get an endorsement from at least 1-2 more people before marking this RTBC.

Yes, it works for me and the code is some very simple changes that could be marked RTBC. But, does anyone else have any thing to say first?

**Comment by Wylbur** [comment]
I looked through the pull request, and this update provides clear labels about reusable blocks.  I think this is a big improvement and provides some contextual clarity right in the UI.  

I really like the relabeling of the admin menu.  

Seconding "Works For Me!"

**Comment by quicksketch** [comment]
Thanks @Wylbur, @stpaultim, @bugfolder, and @indigoxela for reviewing! At the very least, fixing this description helps tremendously. A label change like this can be changed again if needed, but seems like the folks here believe this is an improvement (myself included). Thank you @NormPlum for raising this issue and providing the pull request! I merged https://github.com/backdrop/backdrop/pull/4942 into 1.x for 1.30.0.
