### ISSUE TITLE
[UX] Add #states property to link_field form element

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop/backdrop-issues#6783]
## Description of the need

I've been adding a `link_field` to a custom form (a custom block), thanks to the amazing work that happened in #6693.  I tried to make this field only visible if a checkbox was selected but `#states` doesn't work in that element type.

Checking https://docs.backdropcms.org/form_api#link_field it is not part of the spec but I don't know why not. I also can't work out where this is set

## Proposed solution

'#states' should be a valid property of `link_field`

## Alternatives that have been considered
None

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop now allows states such as enabled, disabled, required, optional, visible, invisible, checked, unchecked, expanded, collapsed to be defined for a link_field element.

**Comment by argiepiano** [comment]
I've verified that `#states` doesn't currently work. The `link_field` element gets split into subelements during processing, the same way as `date` does. So, what we need here is to wrap the subelements with a div with an id that can be used by `#states`, like what's done by date for example in `theme_date_select()`.

Then, instead of using the `name` attribute in `#states` we will need to use the id of the wrapper. 

Alternatively you use `#states` as is, and target each of the subelements.

**Comment by yorkshire-pudding** [comment]
Thanks @argiepiano for explaining a bit more how that works.

**Comment by argiepiano** [comment]
@yorkshire-pudding [PR](https://github.com/backdrop/backdrop/pull/4943) provided. Please test.

**Comment by argiepiano** [comment]
A quick code to test (use in a form builder function):

```php
  $form['enable'] = array(
    '#type' => 'checkbox',
    '#title' => 'Show link field element',
  );
  $form['link'] = array(
    '#type' => 'link_field',
    '#title' => 'A link field',
    '#default_value' => array(
      'url' => 'https://google.com',
      'title' => 'Google',
    ),
    // '#access' => FALSE,
    '#states' => array(
      'visible' => array(
        ':input[name="enable"]' => array('checked' => TRUE),
      ),
    ),
  );
```

**Comment by yorkshire-pudding** [comment]
Wow! That was quick @argiepiano .  I've tested on the custom form I was building and it works perfectly

**Comment by quicksketch** [comment]
> The test failure in 5.6 seems totally unrelated to the PR. Gremlins again?

Yep, seemed to work on retry.

> The date_select element (for example) doesn't use the form_element as a theme wrapper, like all other simple Form API elements. Instead, it uses its own theme wrapper (in this case theme_date_select()), which in turn, themes the wrapper of the element by invoking theme_form_element() AFTER creating the wrapping div with the target ID. This is what's needed for link_field as well.

Seems like a good solution. Nice digging to find a similar situation.

Code all looks good to me.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/4943 into 1.x for 1.30.0. Thank you @argiepiano and @yorkshire-pudding!
