### ISSUE TITLE
Responsive theme(s) compatible w/BD1.0.1?

### ISSUE THREAD

**Issue by zorgalina** [backdrop/backdrop-issues#679]
Can anyone suggest a/some responsive (free) Drupal themes compatible w/backdrop 1.0.1? thx

**Comment by zorgalina** [comment]
Sorry! I found 'radix' in contribs..that is where to look, right?

**Comment by quicksketch** [comment]
> Sorry! I found 'radix' in contribs..that is where to look, right?

Yep! Until we build out a project listing on BackdropCMS.org, we're working on that. :smile:
