### ISSUE TITLE
Book and Link PHP 8.3 Test Deprecation Notice

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6791]
## Description of the bug

When running tests locally, I get a few deprecated notices:

```
Deprecated: Optional parameter $previous declared before required parameter $breadcrumb is implicitly treated as a required parameter in /var/www/html/core/modules/book/tests/book.test on line 157
```

```
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/core/modules/link/tests/link.ui.test on line 332
```

Since we're working on Book a bit at the moment, it might be a good opportunity to clean up the `book.test` file.

## Steps To Reproduce

To reproduce the behavior:
1. Install locally with ddev
2. `ddev ssh` to get into the container
3. `./core/scripts/run-tests.sh --force --cache --verbose BookTestCase`
4. `./core/scripts/run-tests.sh --force --cache --verbose  LinkUITest`

The errors above will be shown inline when the tests execute.

## Additional information

Add any other information that could help, such as:
- Backdrop CMS version: 1.x (1.30.x)
- Web server and its version: nginx/php-fpm
- PHP version: 8.3
- Database sever (MySQL or MariaDB?) and its version: MariaDB 10.11
- Operating System and its version: Ubuntu 24.04
- Browser(s) and their versions: N/A

**Comment by quicksketch** [comment]
Small PR that only cleans up tests at https://github.com/backdrop/backdrop/pull/4952

**Comment by herbdool** [comment]
This looks good!

**Comment by quicksketch** [comment]
Thank you @herbdool! Merged https://github.com/backdrop/backdrop/pull/4952 into 1.x and 1.29.x.
