### ISSUE TITLE
Do not abbreviate Form API as "FAPI"

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#6793]
## Description of the need

CSpell is currently complaining about "FAPI" not being a valid word (see #6302 for similar issues). Rather than add "FAPI" as a valid word, we should stop using this abbreviation in core. We use "Form API" 130 times, and "FAPI" 34 times. We don't refer to any of the other APIs by a super-short and Backdrop-specific acronym. Using "Form API" consistently everywhere eliminates this unnecessary abbreviation.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/4955

**Comment by avpaderno** [comment]
I checked with `git grep -i --fixed-string "FAPI" | wc -l` how many times *FAPI* is used in Backdrop core code. I can confirm the PR changes all the occurrences of *FAPI* (in whichever case the word is written).

**Comment by herbdool** [comment]
I fixed a couple linting issues and it all looks good now.

**Comment by quicksketch** [comment]
Nice, thanks @herbdool. I kept fixing linting issues and more and more kept coming up. Thanks for taking the time to fix all the touched files.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4955 into 1.x and 1.29.x. Thank you @herbdool and @avpaderno!
