### ISSUE TITLE
[DX] move stylesheets in Seven theme into a 'css' directory

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#680]
It looks like we missed one 'css' directory in core.  Inside the seven theme.  Let's clean this up :)

**Comment by serundeputy** [comment]
travis testing: https://github.com/backdrop/backdrop/pull/722

**Comment by quicksketch** [comment]
Thanks @serundeputy! Needs a little work to fix some tests. We'll need someone to test this locally as well to give it a visual inspection. I expect this change will require a cache clear to take effect?

**Comment by serundeputy** [comment]
yes; cache clear;
I'll work on updating the tests tomorrow

**Comment by serundeputy** [comment]
@quicksketch tests updated; passes travis now. https://travis-ci.org/backdrop/backdrop/builds/49550299

**Comment by serundeputy** [comment]
@quicksketch ping; does this need more work?

**Comment by klonos** [comment]
This is something that we missed but intended to happen in 1.0.0 so I guess it needs to go in sooner than later.

**Comment by quicksketch** [comment]
> @quicksketch ping; does this need more work?

Not sure, I haven't had a chance to test it locally. If someone else is up for doing the review and checking all background images are still working (the most likely thing to break) then that would be helpful.

**Comment by quicksketch** [comment]
Reviewed this today, it looks great! Merged into 1.x and 1.0.x. This is the last issue for 1.0.4. I'll be making a release shortly.
