### ISSUE TITLE
[DX] .htaccess protections do not work on Apache 2.4 without mod_access_compat

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#681]
basically ways of dealing with the situation were hashed out here:
https://www.drupal.org/node/1599774

I can write a PR for backdrop in the next couple of days.

**Comment by quicksketch** [comment]
Thanks for opening this issue @serundeputy. Sounds like a great idea. Although it's mentioned in that issue that we may need to account for existing sites, given the low install base of both Backdrop and Apache 2.4 (at this point), I don't think we need to worry about validating/updating existing .htaccess files.

**Comment by serundeputy** [comment]
This one needs RTBC.
If someone(s) is willing to independently verify that [backdrop cms] (https://github.com/backdrop/backdrop/archive/v1.0.5.zip) installs on `Apache 2.2` and `Apache 2.4` with this patch applied: https://github.com/backdrop/backdrop/pull/808.patch

Thanks,
~Geoff

**Comment by quicksketch** [comment]
Thanks @serundeputy! Merged into 1.x and 1.0.x.
