### ISSUE TITLE
[UX] Specify additional classes for regions in Layouts UI

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#682]
Currently you can define additional classes for blocks in the Layout UI (under 'Style settings' fieldset). This is handy if a Layout or Theme specifies classes that can be used as a CSS grid system (e.g. [Bootstrap](http://getbootstrap.com/css/#grid-example-basic)).

What I'd like to suggest, in addition to this existing functionality, is the ability to add additional classes to _Regions_. This would mean, at a basic level, that regions could be given a class that defines its width or, at a more advanced level, that regions could also be involved in the CSS grid system.

This would obviously only work for Layouts that support this functionality, so some way of specifying support for additional region classes could be added to the Layout's info file (either to apply to the whole Layout, or to individual regions).

**Comment by BWPanda** [comment]
Another use case for this feature:

I was thinking of using the '2 column' layout for a site I'm planning, however that layout is hard-coded to use widths of 70% and 30% for the content and sidebar respectively. I want a fixed width sidebar with fluid content.

Now, I could override that layout's CSS to get the widths I want, but even in that simple layout there are 4 different places where '30%' is used that I'd have to update (let alone whatever other changes I'd have to make for the sidebar to be fixed width and the content fluid).

If this theme had pre-defined 'fixed' and 'fluid' classes, and you could choose one to apply to regions in the Layout UI, this would make it much easier for site builders.

**Comment by quicksketch** [comment]
This is only loosely related to design, but I'm tagging this for the design audience for other themers to weigh in.

API-wise, we actually already have the ability to store per-region settings (I think), but we don't have a location in the UI for region settings. Introducing this concept seems like a good idea, but we don't want the UI for Layouts to become as complicated as Panels.

**Comment by BWPanda** [comment]
> ...we don't want the UI for Layouts to become as complicated as Panels.

I imagine something like this should suffice:
![configure_regions](https://cloud.githubusercontent.com/assets/2385329/6070178/93db4f6a-adde-11e4-8240-edc8a8c089b5.png)

**Comment by quicksketch** [comment]
Ha, good point. Now I recall what API-level support we have. Our display "styles" (such as the block "Dynamic" style) support both regions and blocks, but the only level we have a UI option right now is on blocks.

Unfortunately the way our templates are set up, I'm not sure how we would add functionality to adjust the way regions are displayed. We have the ability to add an additional wrapper, but not the ability to add classes to individual regions. Here's the code from `layout--two-column.tpl.php`:

```html
    <?php if ($content['sidebar']): ?>
      <div class="l-sidebar">
        <?php print $content['sidebar']; ?>
      </div>
    <?php endif; ?>
```

If we add additional classes, we'd need to modify the template, which could amount to an API change.

**Comment by wesruv** [comment]
I thought there was another ticket for this... maybe one of the layout conversations, but I think this is a necessary update. This will help solve a lot of issues.

**Comment by wesruv** [comment]
Is it plausible to make a contrib module that adds this functionality (and overrides core layouts) to avoid the API change issue?

**Comment by docwilmot** [comment]
> I thought there was another ticket for this... 

https://github.com/backdrop/backdrop-issues/issues/1300

**Comment by jenlampton** [comment]
I'm going to remove the `audience - design` label here because designers aren't necessarily theme developers, and I don't think we are going to need new designs to for the Layouts UI in order to implement.

I for one would love to see this feature added via contrib. If that's not possible, we should fix that.
