### ISSUE TITLE
Provide a way to more easily form_alter() the block settings form (get $module and $delta)

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#685]
Original report:

> can you form_alter a block config popup?

Update:

It appears that although you can form_alter() the block configuration form like any other form, there is no easy way to pull out the block "delta" or "module" from $form or $form_state. You can get this information by checking the `$form_state['args']` information, but only be a numeric index. We should store this information in a place more easily accessible.

**Comment by quicksketch** [comment]
Yes, it's still a form like any other. The form ID is `layout_block_configure_form`, so the hook would be `hook_form_layout_block_configure_form_alter()`.

We don't have any additional hooks at this point in configuring blocks (e.g. a `hook_block_configure_alter()`) as they didn't exist in D7 either, but it's something we might consider.

**Comment by docwilmot** [comment]
Thanks. Unfortunately it seems all the popups have the same `layout_block_configure_form` as their form_id, and there is no unique element to target a particular popup except `#title` (Configure block "BLOCK_TITLE").

**Comment by quicksketch** [comment]
That seems like a pretty significant shortcoming then. Seems like we should add the block info to $form_state. I think we could do this by modifying Block::form() in block.class.inc. We currently have:

```
    $block_info = layout_get_block_info($this->module, $this->delta);
```

We could change this to:
```
    $form_state['block_info'] = layout_get_block_info($this->module, $this->delta);
``` 

Then you'd have everything about the block in the form state.

**Comment by docwilmot** [comment]
i think this should work (have to go play pretend dinner with a 5yo now so cant test):
```
  if(isset($form_state['build_info']['args'][1])) {
    $legacy= $form_state['build_info']['args'][1];
     if($legacy->delta == 'THE_BLOCK_I WANT_TO_ALTER') {
      dpm($legacy);           //  <--  the block object
      dpm($form['block_settings']);        //  <--  the config form
    }
  }
```

**Comment by klonos** [comment]
> have to go play pretend dinner with a 5yo now so cant test.

lol. I have a 3yo daughter myself. My d.org profile says: "**Current Role(s)**: Professional (silly) dad since December 2011!"

...so I feel you.

**Comment by docwilmot** [comment]
It worked, see finished producthttps://github.com/backdrop-contrib/custom_header_block

@klonos when they say "daddy can you play with me?" the answer almost always got be be yes,  no matter how silly, right?

**Comment by quicksketch** [comment]
If you don't mind, let's use this issue as a task to include the block information in a more easily accessible location. Checking $form_state['args'] will definitely continue to work, but it's not a very intuitive location. I'll update the issue summary.

**Comment by docwilmot** [comment]
Oh I agree this is a second-rate solution i found. By all means it should be easier than that.

**Comment by klonos** [comment]
@docwilmot so true. They grow so fast you can't afford to miss out on those silly things. Unfortunately for me, I moved to the other hemisphere last year, so I do miss out on these things 11 months a year. And what's worse is it will have to be so for another 2-3 years.

**Comment by docwilmot** [comment]
Block info is available in `$form_state['block']` after all.
