### ISSUE TITLE
[ongoing] Keep jquery.once.js up to date.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#687]
This is a spin-off from #454 

We are using v1.2 (when latest 1.x is the [1.2.6](https://github.com/RobLoach/jquery-once/releases/tag/1.2.6)) and 2.0.0 was released a couple of weeks ago: https://github.com/RobLoach/jquery-once/releases

---
~PR by @klonos: https://github.com/backdrop/backdrop/pull/1859 (upgrades to 2.1.3)~
~PR by @klonos: https://github.com/backdrop/backdrop/pull/1860 (upgrades to 1.2.6)~
~PR by @jenlampton https://github.com/backdrop/backdrop/pull/2011 (upgrades to 2.1.3)~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/2013 (upgrades to 1.2.6)

**Comment by Dinornis** [comment]
@klonos should we close this in preference to https://github.com/backdrop/backdrop-issues/issues/2493 ?

**Comment by klonos** [comment]
Thanx for roaming the issue queues @Dinornis 👍

jquery.once.js is a different project from jQuery and jQuery UI though and not included with them nor updated at the same time as these.

**Comment by klonos** [comment]
We are past code freeze for 1.7.0 and replacing js libraries requires manual testing. So, lets target this for 1.8.0.

**Comment by klonos** [comment]
Filed two PRs; one that updates to the latest 1.x and the other to the latest 2.x

...perhaps 1.2.6 is the safest choice I guess. Up to @quicksketch which is our official js ninja 😄

**Comment by jenlampton** [comment]
@klonos these are likely going to need to be rebased for 1.8. Are you up for that?

**Comment by quicksketch** [comment]
Version 2.2.0 is now the latest. From the PRs, I think we can jump right to 2.x versions rather than sticking on 1.x. The differences in actual code between branches are pretty minimal. The addition of `findOnce()` and more packaging options seem to be the two big differences, which shouldn't affect us or our using of `.once()` in Backdrop.

**Comment by jenlampton** [comment]
New PR at https://github.com/backdrop/backdrop/pull/2011, rebased.

**Comment by quicksketch** [comment]
Looks like I was incorrect about 2.x being compatible.

We have many uses of `once` that use this syntax:

```
$('.selector').once('collapse', function() { ... });
```

But passing in a function as the second parameter is no longer supported. You now have to use `.each()` to loop over the result:

```
$('.selector').once('collapse').each(function() { ... });
```

So for compatibility, at this point we'll need to stick to jquery.once.js 1.x.

**Comment by jenlampton** [comment]
Pushed a new PR that updates us to latest 1.x instead :)

**Comment by quicksketch** [comment]
I know this was an "ongoing" issue, but considering 1.2.6 is likely the last version of the 1.x branch and we won't be able to upgrade to 2.x until Backdrop 2.x, let's close this out entirely.
