### ISSUE TITLE
Field default widgets are not actually set as defaults

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#688]
Modules that provide fields are encouraged to specify a default_widget in hook_field_info() But the field UI does not use this information to set defaults. Instead, the list of widgets for any given field type seems to always be a reverse-alpha-sorted list of widgets, so the one with the name that comes alphabetically last becomes the defacto default.

An example of this bug in action is to apply the PR from https://github.com/backdrop/backdrop-issues/issues/684 and notice that the text (long) field uses the textfield widget by default, instead of the defined textarea widget. 

```
'default_widget' => 'text_textarea',
```

We need to fix the bug that default widgets are not actually default widgets. This means passing the widget information into the javascript that selects the in the Field UI, so that it can determine what the default should be, and select it.

Also, It would also be nice if we could alpha sort the list of widgets.

This is a follow-up to https://github.com/backdrop/backdrop-issues/issues/684

I noticed this bug also exists in Drupal 7, and created an issue here: https://www.drupal.org/node/2421833#comment-9595973

**Comment by klonos** [comment]
Wow, D7 has been out for so long I'm surprised nobody has noticed this bug! Good job Jen!!

**Comment by jenlampton** [comment]
@klonos want to review my patch in the Drupal queue? Not sure we can get it in to D7 before D8, but I'm trying to earn us some good karma by fixing things over there too :)

**Comment by klonos** [comment]
...yeah sure Jen. I will give this a spin over at simplytest.me first thing tomorrow morning (just came back from work - it's past midnight and I'm beat).

**Comment by quicksketch** [comment]
PR looks great and worked well for me. Merged in. Thanks!
