### ISSUE TITLE
[UX] Improve the help text for setting a layout page title type.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#689]
I understand being able to give a title to your custom layouts, but what would be a use case example of no title? What would the benefit(s) be?

Also, what is a "default title"? What happens if I have multiple layouts with their title type set to "default"?

**Comment by quicksketch** [comment]
> I understand being able to give a title to your custom layouts, but what would be a use case example of no title? What would the benefit(s) be?

The "No Title" option suppresses the page-level `<h1>` title. You might use this option when creating a page that doesn't have a natural top-level title, such as a homepage or marketing splash page whose title is built into the blocks, rather than at the page level.

> Also, what is a "default title"? What happens if I have multiple layouts with their title type st to "default"?

"Default" title applies to layouts that override other paths, such as a `node/%` path. Using the "Default" title makes it so that the page `<h1>` title is going to be the node title. You could also suppress the node title entirely, or override all node titles with a hard-coded title if you used a "Custom" title.

I'm not sure all situations really make sense. This kind of Default/Custom/None behavior we adapted from Panels.

**Comment by klonos** [comment]
Oh, it now makes perfects sense. Thanx for taking the time to explain Nate.

When I saw the "Title type" label I though that it was referring to the layout title itself (as in what is displayed in the admin UI under ```/admin/structure/layouts```). How about we change it to "Page title type" (for *page* as in the web page being served - not the "page" node type)?

Also can we have some help text for the "default" and "no title"? I mean, there is the *The title of this layout. If left blank, a default title may be used.* help text for "Custom" but this text is only shown when one selects the "Custom" option. The other two options do not get any help text at all. I propose we move the help text out of the "Title" text field (shown when one selects "Custom") and move it under the "Page title type" drop-down menu so that it is shown at all times. How about this as help text:

Leaving the page title type set to *Default* makes it so that for example the page title is the same as the one set for the content. Select *Custom* page title type in order to override the default title with a customized one. The "No title" option suppresses the page title entirely.

**Comment by klonos** [comment]
...now that I think of it, the help text for "Custom" currently reads:

> The title of this layout. If left blank, a default title may be used.

Doesn't this make the "Default" option redundant?

So my initial reaction was to suggest that we simply removed the "Default" option and replace the "No title" one with the "special" ```<none>``` thing. But then I thought that it's really weird to ask users to leave the title field blank in order to fall back to the default, whereas we ask them to actually type something (```<none>```) in order to have the title be blank. WTF!

At some point there was a suggestion to globally replace the ```<none>``` special keyword with a checkbox to enable/disable the title field. I couldn't find the respective issue over at d.org though.

**Comment by klonos** [comment]
...found the issue over at d.org and filed #692

So, it's either this issue here or that one.

**Comment by klonos** [comment]
In some screenshots posted by @docwilmot in #1300, I realized that the label for the drop-down has changed to "Block title type". Fix here or separate issue?

**Comment by stpaultim** [comment]
@klonos - I just stumbled on this issue and it appears to be outdated. Am I correct on that assumption?

I'm not seeing the option for layout page title type that you are describing AND you reference screenshots in #1300 that seem very different from what we have today. 

Am I missing something or is this issue obsolete?

**Comment by BWPanda** [comment]
I think @stpaultim's correct. This is what I see when configuring the Page Title for a Layout:

![image](https://user-images.githubusercontent.com/2385329/90847861-d5436580-e3ae-11ea-95e6-928e6e219f88.png)

Closing as fixed. @klonos can re-open if he disagrees and can add more details about what this issue refers to.
