### ISSUE TITLE
[UX] Same type or even identical dblog entries have different background color.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#695]
I understand that this a zebra stripe even/odd thing, but that only works good for gray/white background:

![dblog_colors_for_even_odd_differ](https://cloud.githubusercontent.com/assets/2423362/6094538/10cf44e6-af82-11e4-9c96-db6acbbb5e8f.png)

I think we should provide either lighter or darker versions of the current green and red and use these for even/odd.

**Comment by klonos** [comment]
...similarly, we give even content messages a darker gray bg color, while the odd content messages get the normal light gray:

![dblog_colors_for_even_odd_content_messages_differ](https://cloud.githubusercontent.com/assets/2423362/6094574/7b291d8e-af83-11e4-88f7-08a9c1a7a8ce.png)

**Comment by Dinornis** [comment]
This problem still occurs in the current 1.7.x-dev version of Backdrop.

**Comment by jenlampton** [comment]
@Dinornis thanks for the update, do you have a screenshot? We should update the design of the error log page to match the new status report and update report. Adding [UX] to prioritize.

**Comment by Dinornis** [comment]
Here is a screenshot from Backdrop 1.8.
![errorlogcolors-bd18](https://user-images.githubusercontent.com/24782789/30778633-0f76a32e-a137-11e7-892c-8af1674675a8.png)

**Comment by BWPanda** [comment]
This has been fixed in another commit (maybe https://github.com/backdrop/backdrop-issues/issues/3471?). It now looks like this:

![image](https://user-images.githubusercontent.com/2385329/74441487-915c2a80-4e78-11ea-8a9d-34e2f5700800.png)
