### ISSUE TITLE
Notice: Undefined index: backdrop in system_modules

### ISSUE THREAD

**Issue by oadaeh** [backdrop/backdrop-issues#696]
In some cases where a module has been placed within Backdrop's accessible areas (i.e.: /modules), and the module does not have a `backdrop = 1.x` line in the module's .info file, a line like the following may be displayed at the top of the modules page (admin/modules):

> Notice: Undefined index: backdrop in system_modules() (line 575 of /var/www/html/backdrop/backdrop-1.0.1/core/modules/system/system.admin.inc).

I say 'some' and 'may' because I have 19 such modules in my /modules directory, but there are only 10 messages, so there may be some situation where this is not an issue.
Be that as it may, I'm creating a PR for those times when the message is displayed.

**Comment by quicksketch** [comment]
Thanks for filing the PR!

https://github.com/backdrop/backdrop/pull/734
