### ISSUE TITLE
[DX] update the comment in layout info files

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#697]
In the two column layout's info file we add the following line of text above the declaration for default layout:

```
; Content is the default region by default, but specify it for clarity.
```

Though we do want to specify the default region for clarity, the preceding text doesn't make very much sense: "Content is the default region by default".

I propose the following change to this text:

```
A region named content will be the default region, but specify it for clarity.
```

Other core layout info files should be checked for this string and updated accordingly, as necessary.

**Comment by quicksketch** [comment]
The following line is also important for context:
```
; Content is the default region by default, but specify it for clarity.
default region = content
```

So it really is the "default region" by default. It's not that a region named "content" will always be the default region, the default is actually what's being specified. I'd suggest something like this:

```
; The "content" region will be the default region if none is specified, but it's provided here for clarity.
```

**Comment by klonos** [comment]
In Drupal, when we refer to menus, modules, themes etc. we capitalize the first letter. So...

> The "Content" region will be the default region...

**Comment by quicksketch** [comment]
Thanks @CaffeinatedJim! Merged in https://github.com/backdrop/backdrop/issues/789.
