### ISSUE TITLE
Duplicate content when setting default region in layout .info file

### ISSUE THREAD

**Issue by shadcn** [backdrop/backdrop-issues#699]
I'm seeing duplicate content (main page content block) when setting a default region in a layout's .info file.

Looking into it. I'll post more here if I find something.

**Comment by quicksketch** [comment]
Thanks @arshad! I don't think we have testing on default regions other than "content", so that's not an outside possibility. The likely source of problems would be in the `LayoutRendererStandard::ensurePageContentBlock()` method.

**Comment by arshad** [comment]
Yep. Something is wrong with this line:

```
// Check that the page content block exists in the layout.
foreach ($this->layout->content as $uuid => $block) {
    if ($block->delta === 'system' && $block->delta === 'main') {
        $page_content_uuid = $uuid;
    }
}
```

Shouldn't it be: ```$block->module === 'system' && $block->delta === 'main'```?

**Comment by arshad** [comment]
Hmm this looks good on the backdrop repo: https://github.com/backdrop/backdrop/blob/3cbdb6561e4c9d9e88b99d8d44b1a39e66a784f7/core/modules/layout/plugins/renderers/layout_renderer_standard.inc#L557

Dunno why it's different on mine.

**Comment by quicksketch** [comment]
I think you're right. The link you have there has it backwards too.

**Comment by arshad** [comment]
You're right. Edited my comment above.

**Comment by quicksketch** [comment]
Awesome, thanks!
