### ISSUE TITLE
Mention non-core changes in release notes

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#705]
With the release of [v1.0.2](https://github.com/backdrop/backdrop/releases/tag/v1.0.2) today, I'd like to suggest that in future you mention in the release notes whether any changes were made to files outside of the 'core' directory.

That will make it easier for people upgrading to know whether or not they can just copy over the 'core' directory, or if there are other changes they need to be aware of (e.g. changes to default 'settings.php', install profiles, etc.).

**Comment by quicksketch** [comment]
Thanks for the suggestion @BWPanda. Per our upgrading instructions, you only have to replace the core directory: https://backdropcms.org/upgrade

If we make changes to a file outside of the core directory, then we'd definitely need to include that in the release notes. In general though, replacing "core" alone is always the upgrade process.

**Comment by BWPanda** [comment]
Thanks @quicksketch.

I can't find it now, but a link I clicked on for updating Backdrop took me to https://backdropcms.org/upgrade#from-previous-versions (note the anchor) and so I missed seeing those instructions up the top of the page... Good to know I had the right idea though :)

**Comment by BWPanda** [comment]
Ah! It was the update link on this page: https://backdropcms.org/SA-CORE-2015-001

**Comment by BWPanda** [comment]
That link should probably be updated to point to https://backdropcms.org/upgrade#minor-updates instead.

**Comment by quicksketch** [comment]
Doh! Yes you're right. Updated the link on https://backdropcms.org/SA-CORE-2015-001
