### ISSUE TITLE
[DX] Add hook_autoload_info() to system.api.php

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#712]
It's missing :)

For reference, it's called in [backdrop_autoload()](https://api.backdropcms.org/api/backdrop/core!includes!bootstrap.inc/function/backdrop_autoload/1).

**Comment by quicksketch** [comment]
Thanks @BWPanda! Speaking of, `hook_class_registry_alter()` is still in there. It should be removed and replaced with `hook_autoload_info_alter()`.

**Comment by quicksketch** [comment]
Added a PR at https://github.com/backdrop/backdrop/pull/1147.

**Comment by quicksketch** [comment]
We already had a change record for this at https://api.backdropcms.org/node/26859, so the code changes are all that was needed here.
