### ISSUE TITLE
Layouts need the ability to add admin-only CSS files

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#718]
In panels you could specify a style sheet that would affect the admin display of a layout.  This is missing in Backdrop's layouts, and is very important for a number of reasons.  
For starters, the markup on in the admin display is different than what you get on the front end. it's usually a different theme, and it's always wrapped in a more stuff on the back end, with the title on the top (though that should be moved soon) and the "Save layout" and "Cancel" buttons in the lower left.
Setting a column to be fixed on the left with a height of 100%, for example, will break the drag-and-drop ability on the back end, and the ability to save the layout at all.
Additionally, on the front end you often want to specify pixel-widths for certain regions, but on the back end you may not want those widths to be the same, taking into account the size of the blocks (with title AND description text) and the amount of space available. I often adjust fixed-width regions on the front end to be percentage-widths on the back end for a better drag-and-drop experience.

**Comment by BWPanda** [comment]
:+1:
A layout I'm developing is missing the sidebar in the Layout admin interface... :(

To get around this in the meantime, or maybe even as a permanent solution, you can add custom admin styles like so:
```css
#layout-edit l-sidebar {
  /* Admin-specific styles go here... */
}
```

**Comment by BWPanda** [comment]
Going to close this due to lack of activity and as there's a work-around. Feel free to re-open if a better solution is still needed.
