### ISSUE TITLE
Settings are added twice to settings.php

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#722]
In settings.php, the settings that Backdrop adds automatically are added twice: once in amongst the comments and again at the very bottom of the file.

Here's the last few lines of my settings.php file (with certain parts removed for security):

```
$settings['backdrop_drupal_compatibility'] = TRUE;
$settings['hash_salt'] = '[REMOVED]';
$database = 'mysql://[REMOVED]';
$config_directories['active'] = 'files/config_[REMOVED]/active';
$config_directories['staging'] = 'files/config_[REMOVED]/staging';
```

Is this done on purpose for a reason, or should this not be happening. Note that I don't think it causes any issues, just curious as to why it's being done.

**Comment by quicksketch** [comment]
It's not intentional. I've noticed this behavior on upgrades, but not new installs. Is that what you're seeing as well?

**Comment by BWPanda** [comment]
Yeah. I'm seeing it on my Backdrop sandbox which wasn't an upgrade...

**Comment by quicksketch** [comment]
Huh, strange. Well looks like we need to do a little more digging in the installer code.

**Comment by serundeputy** [comment]
I can confirm this brand new `1.0.3` install has two `$database` entries and four `$config_directories` entries.

**Comment by quicksketch** [comment]
I'm going to take a look at this issue today.

**Comment by quicksketch** [comment]
It looks like this was an issue introduced in #413. I've filed a PR at https://github.com/backdrop/backdrop/issues/878 to resolve this problem.
