### ISSUE TITLE
[UX] page titles on user login page and forgot password page are stupid

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#728]
On both the user login page (/user/login) and on the "Password reset" page (which does not let you reset your password -- let's call it the "forgot password" page) the page title is simply "User account".  WUT. Let's fix this.

Additionally, description text on the log in form elements? Seriously? Let's remove those in this PR too.

Also related: https://github.com/backdrop/backdrop-issues/issues/260

**Comment by quicksketch** [comment]
> Additionally, description text on the log in form elements? Seriously? Let's remove those in this PR too.

The PR looks great but we haven't addressed this item yet.

**Comment by jenlampton** [comment]
Closing this issue in favor of https://github.com/backdrop/backdrop-issues/issues/1473
