### ISSUE TITLE
[UX] Consider moving operations out of their drop-buttons on wide screens.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#733]
I realize that there's been a lot of work behind the drop-buttons, but the fact remains that a) they make assumptions as to which is the most frequently used operation and b) they hide the rest of the operations an extra click away from the user.

Can we have it so that when there's enough space, the operations are displayed as a horizontal list of links (or buttons)? The menu link edit page makes a good use case...

Drop-buttons work great for small screens:
![drop-button_small_screen](https://cloud.githubusercontent.com/assets/2423362/6248333/c97898aa-b7d2-11e4-9f5c-b96a1a289bd7.png)

In wide screens (Backdrop/D8) we "force" users to make an additional click while there's so much wasted space:
![drop-button_wide_screen](https://cloud.githubusercontent.com/assets/2423362/6248352/d93d263e-b7d2-11e4-8305-fc408fcd1a13.png)

Let's make operations work like D7 in wide screens in order to spare the users the extra clicks:
![operations_links_wide_screen](https://cloud.githubusercontent.com/assets/2423362/6248360/e8180624-b7d2-11e4-9a2e-19a86331e003.png)

**Comment by kreynen** [comment]
Expanding the select lists not only save clicks, it doesn't hide options from the user.  Any time there is more than 1 "operation", the user has to click the select list to even know what the options are.  Is there a Configure, Permissions, etc, buried under the first option?  

The challenge of simply expanding these is that while this works with 2 options, what does this look like when there are 4 options with longer titles?  Depending the number of operations and the length of the operation titles, this could get very cluttered.

**Comment by klonos** [comment]
Isn't there a way to detect (with JS) whether the contents of a table cell are wrapped? That event could trigger the rendering as a drop-button then.

**Comment by klonos** [comment]
this one perhaps?: https://github.com/xdamman/js-line-wrap-detector

**Comment by quicksketch** [comment]
> The challenge of simply expanding these is that while this works with 2 options, what does this look like when there are 4 options with longer titles? Depending the number of operations and the length of the operation titles, this could get very cluttered. 

We may also end up in a situation where some rows get drop-buttons but others do not, especially if we add additional links there for documentation and support. We could then check *all* rows to see if any row should have a drop-button, but that may result in no drop-buttons unless you have a very wide window.

Another difficulty of this would be the requirement that we'd need to make it responsive, so besides just calculating this at page load time, we'd have to set a window timer and trigger the on/off behavior of dropbuttons.

**Comment by jenlampton** [comment]
The point of drop-buttons was to make it easy to do the one thing you do most of the time. But they do also make it hard to do all the other things. 

This is a hard problem. I'd love to see a contrib solution that solves this problem with a little form-alter magic. And also (and maybe more importantly) some documentation in our HIGs about when and where to use them.

**Comment by klonos** [comment]
> but that may result in no drop-buttons unless you have a very wide window.

The other way 'round... drop-buttons should appear on very *narrow* screens. Also, the point is that if one row gets a drop-button, then all rows switch to drop-buttons for consistency.

**Comment by klonos** [comment]
Enough years have passed, and I have changed my mind about this. Dropbuttons have become a pattern that most people are used to by now I believe (generally - not only in Drupal/Backdrop). Besides, We may also end up in a situation where some rows get drop-buttons but others do not.

As such, I'm closing this. If anyone else feels strongly about implementing something like this, feel free to comment with supporting arguments about it, and re-open.
