### ISSUE TITLE
Re#736 - Status Messages

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#739]
See master issue for instructions/guidelines for implementation: 
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6276361/418b6e72-b854-11e4-8583-4f9f502f9dc0.png)

**Comment by jenlampton** [comment]
We will have some technical implementation details to work out around the icons (and all icons in core, actually). These are font-awesome icons. Do we want to include font-awesome in core? what about in seven? what about just stealing their icons and making them into SVGs with an IE fall-back to PNG?

**Comment by wesruv** [comment]
Commented on that issue, going to work on everything _but_ the icons for now.

**Comment by jenlampton** [comment]
We are officially unblokced on this now...

> ...for all our new styleguide updates we'll need to replace the current background images anyway - so let's try replacing them with SVGs with the PNG fallback.

I would love to see if we can find a tool to quickly produce SVG+PNG from font awesome icons. That also sounds like a great blog-post in the making :)

**Comment by wesruv** [comment]
@jenlampton I can make a quick video tutorial for icomoon.io, when I do where would be a good place to put it?

**Comment by jenlampton** [comment]
:(

**Comment by wesruv** [comment]
cc: @dariusgarza
Styleguide calls for backgrounds that are the branded colors but at 40% transparency. I'm recommending against this since these are themed in system.theme.css (not theme, but backdrop specific) and because sites could have very dark backgrounds.

Which would look like this:
![style guide - backdrop 2015-03-05 19-22-35](https://cloud.githubusercontent.com/assets/5607236/6517849/3637c362-c36d-11e4-8763-c4d8ee6df4a4.png)

So instead I'm using the flattened color (brand color at 40% opacity over a `#fafafa` bg) so we have a consistent message outlook.

Darius let me know if you'd prefer a different approach.

**Comment by dariusgarza** [comment]
Good observation @wesruv 

The backgrounds were not intended to be transparent. I think that was just a way of lightening the color. We can use straight hex colors. 

This is what my eyedropper says - 

light red - #F9EDEC
light green - #E9EEBC
light yellow - #FAF5C9

thanks!

d.

**Comment by wesruv** [comment]
Pull request with screenshots of what it looks like: https://github.com/backdrop/backdrop/pull/769

**Comment by jenlampton** [comment]
saweet!!!!!

**Comment by quicksketch** [comment]
Hi @wesruv! It looks like we just fixed a problem with 16px images not being linked properly in https://github.com/backdrop/backdrop-issues/issues/806.

If we're replacing all these images with white-only icons, does that negatively affect the use of the 16px images on the admin/reports/dblog page? Perhaps we'd need to either: A) colorize the 16px versions or B) Add a background color to the row or cell in `core/modules/dblog/css/dblog.css`.

**Comment by wesruv** [comment]
@quicksketch or someone, how do I get to that page?

**Comment by jenlampton** [comment]
@wesruv Reports > Recent log messages

**Comment by wesruv** [comment]
@jenlampton & @quicksketch updated PR with DBlog draft, let me know if that works!

**Comment by jenlampton** [comment]
Hm.  I'm not sure that's gonna fly as-is, the yellow/green mismatch is confusing. I left some suggestions for how to avoid the even/odd striping collision on the PR. Maybe that will help?

**Comment by quicksketch** [comment]
Okay, this conversation ended up all over the place (sorry everyone).

First PR: https://github.com/backdrop/backdrop/pull/769
Replacement PR: https://github.com/backdrop/backdrop/pull/796

In both pull requests, we had discussions about these new message styles affecting the database logging (watchdog) table styling. We decided to separate that into a new issue at https://github.com/backdrop/backdrop-issues/issues/876.

I've merged in the second PR (https://github.com/backdrop/backdrop/pull/796) into the 1.x-new-style branch. Thanks so much @wesruv for your work on this and all the related issues.

**Comment by klonos** [comment]
I don't know if you want to reopen this or file a new issue, but the status message text is not vertically aligned when it's 1 line:

![status_message_not_vertically_aligned_when_one_line](https://cloud.githubusercontent.com/assets/2423362/7219036/ba58cbd8-e6d0-11e4-9da9-59db64f4b271.png)

...looks fine when it spans more than one line though:

![status_message_ok_when_more_then_one_line](https://cloud.githubusercontent.com/assets/2423362/7219042/ce31347e-e6d0-11e4-9861-f1319cdd4ba0.png)

**Comment by wesruv** [comment]
Hrmmm... if I remember right I put a min-height on it so the icon wouldn't get snipped, but that seems like it's too tall. I'll take a look.

**Comment by wesruv** [comment]
Unfortunately I wasn't able to spend the night working on backdrop as I'm having local env woes. On the bright side, I think have a very good long term solution.

I did get a bit to look at this as I ended up setting up my site multiple times and got quite a few error messages while doing so. 

The biggest factor in these two screenshots is the font size difference between Seven and Bartik, I noticed it on my local as well. Seven is using a larger font by a few px I believe, and that's definitely what we designed against.

I don't want to put in a font size for system messages, but we might be able to get a good solution that makes the icon and some of the layout respond to the font size.

There's also some other issues when we add `<p>` or `<ul>` type stuff to status messages. I'd like to spend a some time making sure this looks nice in different circumstances.

BUT considering what we have to do before the point release I vote we make a ticket for this and knock out the higher priority bits first.
New ticket here: https://github.com/backdrop/backdrop-issues/issues/880

**Comment by quicksketch** [comment]
Thanks @wesruv!

**Comment by wesruv** [comment]
For the record, my local environment issues were related to Vagrant, not Backdrop :D

**Comment by jenlampton** [comment]
I noticed this too.  Also, in Bartik it looks like we might want to add some more spacing betwen the top of the message and the blue of the header.  Might be worth fixing in the same PR?

**Comment by wesruv** [comment]
@jenlampton this is _still_ happening? Thought I fixed it in #880?

**Comment by wesruv** [comment]
rather: https://github.com/backdrop/backdrop/pull/862

**Comment by klonos** [comment]
...I think it's fixed now:

![backdrop-both_single_line_as_well_as_multiple_line_messages_aligned_properly](https://cloud.githubusercontent.com/assets/2423362/9840640/a75b72c0-5ad8-11e5-93d3-44bd4bcb97d8.png)
