### ISSUE TITLE
Re#736 - Tables

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#740]
See master issue for instructions/guidelines for implementation: 
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6276480/254a860c-b855-11e4-8875-70784e1a2941.png)

**Comment by quicksketch** [comment]
Merged in 5592b21e816a6ca2c6a1f2ada1d9910f642dbd70. Thanks!

**Comment by klonos** [comment]
I just downloaded a copy of the 1.x-new-style, upgraded a 1.0.5 installation and cleared all caches. The tables seem to be missing upper/left/right borders (for example the modules page and the status report page) while the [Style guide](https://backdrop-ops.github.io/styleguide/#table) shows that there should be there.

Also, in the Style guide there is a hover-over effect (personally don't like the yellowish color, but still) that is not implemented with this patch.

**Comment by quicksketch** [comment]
Thanks @klonos! Good eye. I didn't even see the border, you have to look *VERY* closely. I filed a followup at https://github.com/backdrop/backdrop-issues/issues/874. To help move the styleguide implementation as a whole, I made a section for "followups" in the summary of the meta (https://github.com/backdrop/backdrop-issues/issues/736).

**Comment by klonos** [comment]
> I didn't even see the border...

That's why we are all together in this. If one misses a detail, another will catch it. :wink:
