### ISSUE TITLE
Modal window/popup too small

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#741]
I couldn't find an existing issue/reference to this. I think the modal window/popup in Backdrop is too small, especially in Views as per the screenshot below. I'm not sure why the current size was chosen, but one solution would be making it work like some lightboxes where the size is a certain percentage of the browser window (e.g. 90% of the height & 80% of the width) and there's a min-width/size too.

![modal](https://cloud.githubusercontent.com/assets/2385329/6278266/c0db851e-b8e9-11e4-856b-b31c55b9838e.jpg)

**Comment by BWPanda** [comment]
Here's an example of how it could look:

![modal2](https://cloud.githubusercontent.com/assets/2385329/6278426/e283b2da-b8ea-11e4-9d10-904488bdcf2e.jpg)

**Comment by quicksketch** [comment]
Totally agreed. Thanks for opening this issue @BWPanda.

**Comment by quicksketch** [comment]
The PR looks pretty good. I'll test this locally.

**Comment by BWPanda** [comment]
This patch makes the window both wider and taller. There is an issue when viewing the popup window in a browser that has a small height (drag the bottom of your browser window up to test) in that the popup scrolls down but the bottom is still hidden. However, this issue was also present before this patch, so there's something else at work that needs addressing...

**Comment by quicksketch** [comment]
Thanks for the heads-up @BWPanda. I tried this out locally and the display looks much better. Especially on the example of table configuration, where the previous width was not nearly wide enough.

> There is an issue when viewing the popup window in a browser that has a small height (drag the bottom of your browser window up to test) in that the popup scrolls down but the bottom is still hidden.

Hm, yes sure enough. On most dialogs (like editing a field configuration) the wider-dialog is now very noticeably broken in that you can't see the bottom of the dialog contents and the scroll bar is missing. Although I agree that this seems to have been a pre-existing problem, it looks like we'll need to address this problem at the same time. After the patch, the broken behavior becomes much more pronounced and happens on most dialogs. I don't think we can merge this as-is.

**Comment by quicksketch** [comment]
If for the time being we wanted to include the increased width but not the height, I think that would be acceptable. However, I think the best thing would be to use a [height-based media query](http://unmatchedstyle.com/news/height-based-media-queries.php) here. Just use add a `@media only screen and (min-height: 800px)` and then set the increased max height of 600px inside of there.

**Comment by BWPanda** [comment]
Good suggestion @quicksketch! I've not used height-based media queries before. I've updated the PR commit and with my testing it seems to work well.

**Comment by quicksketch** [comment]
Thanks, much better! The overall popup doesn't work right on mobile screens still, but we can address that as a separate issue. Merged in the PR as-is. Thanks!
