### ISSUE TITLE
[UX] Change "Edit" to "Content Type Settings" in Content Type Settings

### ISSUE THREAD

**Issue by clickbox** [backdrop/backdrop-issues#743]
The edit tab in the content type settings is not descriptive enough. Its easy to loose track of menu hierarchy while editing content types.

**Comment by quicksketch** [comment]
Agreed, I think "Content Type Settings" would be a big improvement over the current "Edit".

**Comment by dariusgarza** [comment]
+1

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/747
`travis` testing.

**Comment by klonos** [comment]
Here's an idea to make the text shorter... how about we replace the "Content type" part of the label with the actual name of the content type? So instead of "Content type settings" for all content types, it would be "Post settings", "Page settings" () etc.

...and if I may ask, why not just "Settings"??

**Comment by serundeputy** [comment]
updated to: "`%node_type` . settings"
PR: https://github.com/backdrop/backdrop/pull/747

**Comment by klonos** [comment]
The PR looks good and it's definitely an improvement over "Edit".

...although the "[node_type] settings" as a submenu under ```Structure``` > ```Content types``` > ```[node_type]``` > ```[node_type] settings``` feels redundant. Can we have the menu be different than the tab label (plain "Settings")? If not, does it make sense having the tab label also be just "Settings".

**Comment by serundeputy** [comment]
>Can we have the menu be different than the tab >label (plain "Settings")?
not sure, but i can investigate if it is desired. 


>if not can it just be settings?
this is easy. 

either way let me know.

**Comment by jenlampton** [comment]
@serundeputy let's change it to just 'Settings' it's an easy win and it's an improvement over what we have now :)

**Comment by serundeputy** [comment]
PR updated to `Settings` : https://github.com/backdrop/backdrop/pull/747

**Comment by jenlampton** [comment]
Hm.  On closer examination it appears that settings in the wrong word. "Configure" is what we want to use consistently in core. Relted issues:
https://github.com/backdrop/backdrop-issues/issues/771
https://github.com/backdrop/backdrop-issues/issues/127

@serundeputy sorry about that, can we do one more change to this PR? :)

**Comment by serundeputy** [comment]
yes;

**Comment by serundeputy** [comment]
This is the `rebase` of this branch; I think I did it right, but please tell me if you see something wrong.

#noob;

**Comment by quicksketch** [comment]
I merged this into 1.x but not 1.0.x. This is probably a UX enhancement rather than a bug, correct? Let me know if you think it should be in the next bug fix release and I can cherry-pick it in if necessary.
