### ISSUE TITLE
[UX] Add description to "Rows" on long text fields indicating "Line Height"

### ISSUE THREAD

**Issue by clickbox** [backdrop/backdrop-issues#745]
Rows seems confusing for users building new content types. It could be mistaken for individual rows of text fields.

**Comment by serundeputy** [comment]
Just an opionion, but the html spec calls it rows: `http://www.w3.org/TR/html401/interact/forms.html#edef-TEXTAREA`

I'm for parity with that.

**Comment by quicksketch** [comment]
Yeah, "rows" is actually the HTML attribute. I'm also in favor of consistency with the HTML that is produced, but I don't disagree it's not new-user friendly. #blamehtml
I think sticking with rows is the right thing as well.

**Comment by klonos** [comment]
Yeah, "Line height" simply does not feel right to me either. Perhaps "Number of lines" would be clearer for new users, but I agree that "Rows" makes sense.

**Comment by quicksketch** [comment]
Unless we have a different option that could be a clear winner, let's close this issue. Please feel free to reopen if you feel strongly about it, but I'd like to just get this out of the list of open issues.

**Comment by dariusgarza** [comment]
At the very least, could we add helper text saying something like "This is the height of the text box" ? I was very confused by the rows terminology.

**Comment by serundeputy** [comment]
Is this what we are talking about?

![gff-is-the-best](https://cloud.githubusercontent.com/assets/6763671/6311515/c6b9720a-b931-11e4-8bfd-311b3e8ce592.png)

If so can we agree upon language?

**Comment by serundeputy** [comment]
maybe this?
![gff-rows-5](https://cloud.githubusercontent.com/assets/6763671/6311631/b208118e-b933-11e4-9010-7292fe5060c4.png)

which one? what should it say?

**Comment by klonos** [comment]
From http://www.w3schools.com/tags/tag_textarea.asp :

> Specifies the visible number of lines in a text area

**Comment by quicksketch** [comment]
The [second one](https://cloud.githubusercontent.com/assets/6763671/6311631/b208118e-b933-11e4-9010-7292fe5060c4.png) @serundeputy. Thanks @klonos for the description. I think we should shorten that to just this for the description text:

> The visible number of lines in the text area.

Seems like it couldn't be much more clear than that. @serundeputy you up for making the PR? Seems like you've already got the files open. :wink:

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/746
`travis` is testing.

**Comment by quicksketch** [comment]
In the PR, @klonos mentioned:

> I believe that we meant to have this text as a help text and not in the label.

That's correct. I had intended it to be the description text as well.

**Comment by quicksketch** [comment]
Thanks @serundeputy! Merged in. :smile:
