### ISSUE TITLE
[META Contrib]

### ISSUE THREAD

**Issue by serundeputy** [backdrop/backdrop-issues#747]
Is there an easy way to tag [backdrop-contrib repos](https://github.com/backdrop-contrib) as a `module` or a `theme`?

**Comment by quicksketch** [comment]
No, not yet. We'll solve this problem in the centralized project listing on BackdropCMS.org. See these issues:

- https://github.com/backdrop-ops/backdropcms.org/issues/46
- https://github.com/backdrop-ops/backdropcms.org/issues/8

**Comment by quicksketch** [comment]
I'll close this as duplicate because we're handling this in the backdropcms.org repository.
