### ISSUE TITLE
update_last_required() and new installs 

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#751]
Here's my custom_search.install file:

``` php
function custom_search_update_dependencies() {
  $dependencies['custom_search'][1000] = array(
    'node' => 1005,
    'language' => 1002,
  );
  $dependencies['custom_search'][1001] = array(
    'taxonomy' => 1001,
    'system' => 1025,
  );
  return $dependencies;
}

function custom_search_update_1000() {
  // Migration from D7 part 1
}

function custom_search_update_1001() {
  // Migration from D7 part 2
}

function custom_search_update_last_removed() {
  return 7103;
}

function custom_search_update_1100() {
  // Some misc. updates, nothing to do with migration from D7
}
```

When upgrading from D7, everything's fine. It requests the last schema (7103) and runs all the updates.

But when using it on a clean new install of Backdrop, which only need to run 1100, it won't update, and investigating gives me this message : "custom_search module can not be updated. Its schema version is 0. Updates up to and including 7103 have been removed in this release. In order to update custom_search module, you will first need to upgrade to the last version in which these updates were available.". But this is not case here, because the old D7 schema version is not required on a clean install.

I must have missed something, but don't know what and where…

**Comment by quicksketch** [comment]
Hm, this doesn't seem right. If you install a module on a fresh install of Backdrop, the module should automatically be given the schema version of the highest numbered update. So when you first enable the module, it should be given the schema version "1100" in this case. Is this code up in the http://github.com/backdrop-contrib/custom_search repo? I can try and install the module and see if I get the same result (a schema version of "0" on install). Are there any other tricks to getting the problem to reproduce other than just installing the module then trying to visit update.php?

**Comment by jdanthinne** [comment]
I think I understand the problem now…
In fact, the first release of Custom Search didn't include an upgrade path. So when I installed and tested on a simple fresh install of Backdrop, the schema number was 0, logic. Then only, after 2-3 days, I wrote the upgrade functions, so the problem comes in… it want a 7103 as schema number.
Is there a trick for that, or do I have to let it go, and the solution is to uninstall/reinstall the module (I don't think there are so many install of this module yet)?

**Comment by quicksketch** [comment]
That entire situation sounds spot-on.

I don't think you should worry about it at this point, especially if you haven't made any release tags for your module. The initial Token port had some really screwy behavior in it because it still included *Drupal 5 to 6* updates. That ended up setting the schema version in the 6300's. There wasn't much to be done in that situation either, as it's difficult for a module to fix its own update numbers.

**Comment by jdanthinne** [comment]
Allright, let's live dangerously ;-).
