### ISSUE TITLE
Re#736 - Fieldsets

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#755]
~~**Blocked**
There are some comments related to Fieldsets at backdrop-ops/styleguide#11
Please hold off on this ticket until they are addressed there.~~

See master issue for instructions/guidelines for implementation:
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6311510/bec3bca4-b931-11e4-932e-703561718eb2.png)

**Comment by klonos** [comment]
The color difference between the fieldset labels and the rest of the labels is very subtle. How about we do either of these:

- intent the fieldset contents a tiny bit
- change the label color to look like a link (something clickable)
- move the label over the top border line of the fieldset. like the ones [here](http://www.pixy.cz/blogg/clanky/css-fieldsetandlabels.html)

**Comment by Bojhan** [comment]
A small FYI, the reason we have a > in Core - is because of a11y. You can't otherwise see that its something you can open. Which is a requirement for a11y.

**Comment by dariusgarza** [comment]
PDF design for fieldsets. A draft of this was actually buried in the original sketch file. 

https://www.dropbox.com/s/dfj293gb3eel78u/BackdropCMS-Fieldsets-01.pdf?dl=0

**Comment by quicksketch** [comment]
Cool, thanks @dariusgarza! This design may have a few issues:

- The triangle with a circle around it (in my mind) is the symbol for "play a video".
- We often have fieldsets mixed in with other form elements (or even nested), so margins around fieldsets is probably a requirement.

Here are a few of the more awkward fieldset examples. We can "fix" individual situations where we shouldn't be using a fieldset in the first place, but I think we should still try to accommodate the existing use-cases that we have for fieldsets, as other modules will be expecting an adequate display even in abused-fieldset scenarios.

Nested field sets in the field settings:
![field-settings](https://cloud.githubusercontent.com/assets/100206/7437825/26efb9ee-f010-11e4-8257-ae926d0cb6f0.png)

Positioning a fieldset next to other elements on a bulk operations form:
![bulk-operations](https://cloud.githubusercontent.com/assets/100206/7437831/3c9d4504-f010-11e4-972d-3c317c955705.png)

**Comment by klonos** [comment]
> - The triangle with a circle around it (in my mind) is the symbol for "play a video".

Same thought here too.

**Comment by wesruv** [comment]
Resurrecting this thread because fieldsets are dumb and I want them to be more usable and better looking. :smile: 

Here's a basic implementation I'm suggesting that improves the hit area of the legend, and also makes it obvious where that hit area is. Don't think I addressed the 'better looking' bit, but I'll settle for 'more usable'.

If anyone wants to dink around with what's there (looking at you @dariusgarza) they're more than welcome, you can fork and modify in Codepen, then share the link to your fork here. 

Tested it in all of the Windows browsers at my disposal (IE8+, Chrome and FF) and it's working well, haven't tried a mobile browser yet, but I have previewed the width to make sure it behaved well.

For viewing/testing:
http://codepen.io/wesruv/full/KpNamv/

For editing:
http://codepen.io/wesruv/pen/KpNamv

Let me know if I should put up a PR for this!

**Comment by quicksketch** [comment]
I think it looks great! Definitely more consistent with other styling throughout the theme. One minor thing that bugs me is that the caret indicating open/closed doesn't seem centered. Perhaps that is going to be difficult to do with a CSS triangle? I'd also like the triangle to be bigger to match the font size a little better.

**Comment by wesruv** [comment]
I'm on it

**Comment by quicksketch** [comment]
:+1:

**Comment by wesruv** [comment]
@dariusgarza let me know if you have updates to the fieldsets!

**Comment by wesruv** [comment]
Darius's updates
http://codepen.io/dariusgarza/pen/qdjxbe

Going to implement them now

**Comment by quicksketch** [comment]
Sweet @wesruv! That'll be great to have the lingering style guide items implemented!

**Comment by wesruv** [comment]
@quicksketch PR here: https://github.com/backdrop/backdrop/pull/950

**Comment by quicksketch** [comment]
Thanks @wesruv! One thing I noticed, the margin doesn't look right on a collapsed fieldset (though looking at fieldset labels I realize this isn't actually so simple as just a normal "margin" issue):

![fieldsets-margins](https://cloud.githubusercontent.com/assets/100206/8140946/ee0302d8-111d-11e5-869f-2c97027ac7ee.png)

Otherwise it's looking great!

Did you check the IE8 fallback? I was a little nervous about using `calc()` in a width, but it looks like this is only for the label and a 94% fallback wouldn't have much of a negative impact for IE8 users.

**Comment by quicksketch** [comment]
I'm also not crazy about making the legend bold when open and normal weight when closed. I assume that was an intentional change but when toggling the fieldset open/closed, I find the change in font weight to be distracting. The little arrow already tells me if the fieldset is open or closed, and the bold seems to be superfluous.

**Comment by wesruv** [comment]
@quicksketch I _think_ that margin was intended in @dariusgarza 's design (see the codepen). I'll double check when next time I'm at my machine. 

I did check it in IE8 and it looked good, I've used calc like that on quite a few projects and it's been great!

Agreed on the bold toggling, I'm not a fan changing font weight on interactive states. Can get real goofy, especially if the difference between a line wrapping or not wrapping comes up when it's bolded.

**Comment by quicksketch** [comment]
Hm, yeah the uneven margin is indeed in the codepen. Could we try and even it out regardless? Let's nix the bold change. It looks even more strange compared with non-collapsible fieldsets, where are also not bold when open.

**Comment by wesruv** [comment]
@quicksketch donezo, PR has been updated.

**Comment by wesruv** [comment]
Updated this PR again based on the feedback in the PR

**Comment by quicksketch** [comment]
Woot! Merged in. This looks great @wesruv! Thanks for sticking to it. :smile:
