### ISSUE TITLE
Re#736 - Vertical Tabs

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#756]
See master issue for instructions/guidelines for implementation:
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6311539/3a41e54a-b932-11e4-807d-54d9354430f5.png)

**Comment by klonos** [comment]
Would be nice if we changed the vtabs labels so that they don't mention the word *fieldset*. It's misleading.

**Comment by jenlampton** [comment]
I don't think there are any changes to the vertical tabs in our styleguide.  These are just inherited changes for font & form elements.  marking this issue as closed/fixed.
