### ISSUE TITLE
Re#736 - Text Filter Tips

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#757]
See master issue for instructions/guidelines for implementation:
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6311569/918ed0a6-b932-11e4-8eba-1d8ba24d8445.png)

**Comment by jenlampton** [comment]
I don't think this design has any significant changes from seven, so we just need to double check after we do the [element styles](https://github.com/backdrop/backdrop-issues/issues/738) changes that everything still looks okay.

**Comment by jenlampton** [comment]
Closing this issue since there is nothing to do here :)
