### ISSUE TITLE
Re#736 - Progress Bar

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#758]
~~**Blocked**~~
~~There are some comments related to Fieldsets at backdrop-ops/styleguide#11~~
~~Please hold off on this ticket until they are addressed there.~~

See master issue for instructions/guidelines for implementation:
https://github.com/backdrop/backdrop-issues/issues/736

![style guide backdrop](https://cloud.githubusercontent.com/assets/5607236/6311684/6e3a9ee4-b934-11e4-9705-031f233a1e00.png)

**Comment by klonos** [comment]
DISCO YEAH!!!

Can we please keep it simple and use an alteration of  the ```#0494DB``` and ```#0C5E89``` blues?

...no pun intended there with disco vs. blues :stuck_out_tongue: 

Something like this perhaps:

![blues_progress](https://cloud.githubusercontent.com/assets/2423362/6312130/978ad982-b9c3-11e4-9034-5cfedb7bed4a.gif)

**Comment by docwilmot** [comment]
FWIW, I'm diggin the disco.

**Comment by quicksketch** [comment]
During our call yesterday, we agreed that the progress bar was a little too fluorescent. Darius is finding a way to tone it down a little bit.

**Comment by Bojhan** [comment]
This is indeed a bit much. 

Changing mid-way through is a bit much. Some approaches:

![screen shot 2015-04-22 at 10 33 33](https://cloud.githubusercontent.com/assets/209807/7270253/200ee1fe-e8db-11e4-82ae-52ba82864cf2.png)

![screen shot 2015-04-22 at 10 35 01](https://cloud.githubusercontent.com/assets/209807/7270276/50536128-e8db-11e4-8fb8-41907cfef9cc.png)
![screen shot 2015-04-22 at 10 35 26](https://cloud.githubusercontent.com/assets/209807/7270277/53a04eb8-e8db-11e4-8626-b062d1b5ae32.png)

Or the most awesome one:
![screen shot 2015-04-22 at 10 35 58](https://cloud.githubusercontent.com/assets/209807/7270283/678b919e-e8db-11e4-8364-51c0b82aeda0.png)

**Comment by klonos** [comment]
> Or the most awesome one:

Good one!! :laughing:

**Comment by dariusgarza** [comment]
Updated status bar: http://codepen.io/anon/pen/VLLrRV

**Comment by quicksketch** [comment]
This looks a lot better. The animation is a little jumpy when it repeats, but I think that's probably an implementation issue. The current bar also only works in Chrome, but I think that's just missing the appropriate properties for other browsers.

**Comment by klonos** [comment]
> The current bar also only works in Chrome, but I think that's just missing the appropriate properties for other browsers.

Yep, I opened the link provided above in firefox last night to check how it looks and all I got was a grey bar.

**Comment by wesruv** [comment]
Yeah, I think we can fix that in implementation, at minimum IE8 and some older browsers will get a green bar. All modern browsers should get a kickass smooth animation.

**Comment by wesruv** [comment]
@dariusgarza and whoever's interested, look good?
http://codepen.io/wesruv/pen/vOOQRz?editors=010

**Comment by wesruv** [comment]
Here's a PR for what I came up with. Increased the height to 40px per the original styleguide, let me know if that isn't what we want in the final.
https://github.com/backdrop/backdrop/pull/866

**Comment by quicksketch** [comment]
Thanks @wesruv! A few things I noticed in testing:

- For some reason the background color is black in Firefox and the gradient is stretched across the bar:

![progress](https://cloud.githubusercontent.com/assets/100206/7543942/fa225cd4-f585-11e4-8578-6d140a3962ef.png)

- Could we add a transition to the `width` property so that the bar doesn't jump between iterations? It's common for something like the installer to jump from 0 to 40% to 80% to 100%, we should transition between those widths.

- I get the feeling that this progress bar might be too styled for generic use. How would you feel about putting these styles in style.css and leaving the current bar as-is (except for adding the CSS transition).

BTW, we have a completely separate issue for transitions, we can close that one as duplicate if we handle it here: #643.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/866 has been closed (boo!) because I deleted the 1.x-new-style branch after we merged into 1.x (yay!) We had some feedback that needed to be addressed anyway, but when you get the chance please file again directly against the 1.x branch.

**Comment by quicksketch** [comment]
Thanks, this looks great @wesruv! I tested the installer and simpletest running and everything works the way I would expect. Great job!
