### ISSUE TITLE
Software that autoconverts Drupal 7 modules to Backdrop

### ISSUE THREAD

**Issue by GeoHub15** [backdrop/backdrop-issues#763]
I think I'm not the only person being thrilled by Backdrop and also being disillusioned that the mere existence of  Backdrop doesn't help in avoiding Drupal 8. The reason is the statement on the Backdrop website:
"Is your site built on Drupal 7? Backdrop will be familiar to you and your developers. Upgrading most modules to Backdrop can be done in days or even hours. With a familiar architecture, it's easy to upgrade."

I need to convert about 20 modules. If each takes say 10 hours to convert (not a huge estimate given said "days or even hours") it will take me about a month to switch to Backdrop. A month. If nothing else goes awry.
And if you or your client needs additional modules? Another week just for converting them? How do I explain it to a client (or even to myself)? 
I can try lines like the following:
"Well, yes you see I like Drupal 7 and - being afraid of Drupal 8 - I switched to Backdrop CMS. So please bear with me and pay for this extra week."
But I don't think it gets me anywhere, for my client will say: "Let's keep Drupal 7. Oh, and I'm going to look for a different programmer. So bye."

One solution is an automated way of converting Drupal 7 modules to Backdrop.
Another solution is to leave the Drupal world altogether. A step I dread but which I contemplate more often recently (October CMS? Textpattern? Cockpit CMS? ...)
So please you code gods out there  - answer my prayer!

The power of  Drupal 7 is greatly reduced if you can't add the plenitude of modules.
And the same goes for Backdrop. It is a harsh statement but also a fundamental truth.
Thanks for reading this.

**Comment by quicksketch** [comment]
>  And if you or your client needs additional modules? Another week just for converting them? How do I explain it to a client (or even to myself)? 

If Backdrop isn't saving you time in the long-run by easing functionality deployment (through the config management tools) or the other important/updated features it includes, then I absolutely agree, it doesn't make sense. The entire point of Backdrop is to reduce the cost for both upgrading and maintenance. If we're not improving the return value on time/money, then we're not succeeding. At this point though, with only ~50 contrib projects (and most just getting started), that vision is still a ways off.

But anyway, I get the sense that you're more interested in solutions than explanations. :)

> One solution is an automated way of converting Drupal 7 modules to Backdrop.

Absolutely. There is already a way to do this for Drupal 6 to Drupal 7, in the https://www.drupal.org/project/coder module. For the most part, this module could easily be upgraded to support Backdrop changes, especially the simple find/replace situations. Unfortunately, the biggest change is in moving database-configuration into configuration files, and I don't think that could be done (easily) by a script. Coder could certainly help though, and if we're going to try and build a module-upgrader, I'd suggest we use the already-existing tools.

**Comment by biolithic** [comment]
You can give this some time.  I've ported 15 modules in a month or so of Backdrop release on days off, and ones like Disqus and the Carts had a lot of CMI porting to do.  Pro-rated that is about 150 modules coming year, and some major modules aren't needed for Backdrop.  Let's say contrib does another 15 per month (sprints?), which maybe 150 + 50 that exist.  So you have ~350 modules to use in 2015. (These are rough numbers).  Instead of all the lightboxes, pick one.  Instead of all the mail modules, pick one.    For some use cases (large Commerce sites, sites as API backends for apps, etc) you probably shouldn't use Backdrop anyways.  @GeoHub15  So I wouldn't worry too much.  Read what Nate says above, etc....

**Comment by GeoHub15** [comment]
Thank you quicksketch and biolithic for answering my prayer so quickly.

I'm afraid I wasn't clear enough about my wish: On leaving Drupal 7 and adopting Backdrop the best would be an autoconverter for the whole website. But I think this is next to impossible.
What I'm instead looking for is an automated way of converting off-the-shelf Drupal 7 modules automatically into Backdrop modules. So I go to the Drupal modules website, grab a module and insert its path on my HD into the wished for converting software and out comes a Backdrop module with the same functionality.
Having converted all modules this way I then rebuild the website with Backdrop by manually copying and pasting the content. This copying and pasting will take some time but it can be done.

There's one website I have in mind which is run by my wife and which is about adult vocational training and which mostly funded by charity. It is not a big website but the users depend on it for it helps them to get answers for questions which arise in the courses they attend taught by my wife.
This website is running now for 1.5 years and the user numbers are rising steadily. It took me about a month to set it up with Drupal 7 and I had to write about five modules of my own to get the functionality my wife was expecting it to have. Drupal 7 is well documented, so I was confident enough to succeed and indeed everything worked out fine. And then I read what is planned for Drupal 8. I'm sure I won't be able to convert my modules to Drupal 8 for it will take vast amounts of time to get even started to code one line.
Suddenly there is Backdrop. Hope flares up. But then the disenchantment: Backdrop is also different from Drupal 7 and - that's crucial - there is right now not the same breadth of documentation as there is for Drupal 7. So I'm stuck here as well.
Please don't get me wrong: I really do appreciate what you and Jen Lampton have done in creating Backdrop: I don't want to rant and degrade anything. I just want to point out what's keeping me from adopting it right now.
And there is another website a friend (who is in financial dire straits) asked me to do for him to find new customers for his business. I would like to do this website with Backdrop, but the number of themes is rather narrow and I can't start a Backdrop theme of my own for lack of skill and time (I have to earn money as well to make ends meet and I do that by working as a freelancer in engineering).
If you think that there is a chance that somebody like me with superficial knowledge of PHP can manage such an automated conversion software for off-the-shelf Drupal 7 modules I will gladly take this task upon me and try to write such a program and publish it for the use of all Backdrop users. This would imply that programming gods like you would have to be so kind as to answer some questions and help me to scale some cliffs eventually.

Best regards and my heartfelt thanks to all the developers of Backdrop.

**Comment by GeoHub15** [comment]
Sorry, I didn't want to close anything. I just wanted to send my comment.

**Comment by quicksketch** [comment]
>  On leaving Drupal 7 and adopting Backdrop the best would be an autoconverter for the whole website. But I think this is next to impossible.

Yes, unfortunately that is not possible. As much as we have emphasized providing compatibility as much as possible, some changes require work to integrate.

We're doing everything we can to make upgrading easier. And we're making good progress on porting contrib modules. But 100% parity will probably never happen. Some modules won't be ported, and other modules will be written exclusively for Backdrop. 

If you're interested in porting your custom modules to Backdrop, I would suggest reading over https://api.backdropcms.org/converting-modules-from-drupal. Although it's not entirely comprehensive, it should give you a good idea of what to expected when porting modules.

**Comment by docwilmot** [comment]
I'll lend you a personal example @GeoHub15. I am not trained in programming at all, I'd made a few modules for my own use on personal sites in Drupal, but thats all. 
Now I've personally ported about 5 Drupal modules and a theme; one of these 'modules' is Examples for Developers' which in fact is 32 submodules. Took me two weeks, in between full-time job, chairing committees, and two kids and a wife.
Your first one may take 10 hours (I doubt it, unless its way complex), but then you'll be flying. And we're obviously eager for Backdrop to be a success, so if you need help you will get it.
Start now, my friend.

**Comment by quicksketch** [comment]
I hope you don't mind if we close this issue. The actionable item here (port Coder module) should be handled in contrib, we don't have anything in particular to solve in the core project here. If you'd like to have a general discussion, you might join and post to the Reddit group, which seems to have become the Backdrop water-cooler: http://www.reddit.com/r/backdrop/
