### ISSUE TITLE
[UX] Only pages should allow menu entries by default.

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#768]
On most sites, the Basic Page (page) content type is used for things like about us pages, contact us pages, etc - important things that should be in a menu. Articles and Blogs (posts), however, should not.  Usually these pieces of content roll-up into views, either on a view-page called "blogs" (that one should appear in a menu!) or into sidebar views of "recent items".

However, in the standard install profile the Article content type is currently configured incorrectly. It allows editors to place individual posts into the 'Primary navigation' menu. Let's change this to be a more accurate default post type, and un-tick the box on the configure content type form.

**Comment by klonos** [comment]
Makes perfect sense.

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/750
`travis` testing now.

**Comment by quicksketch** [comment]
PR is implemented in a bit of a round-about way. See the comments at https://github.com/backdrop/backdrop/pull/750#issuecomment-75499470.

**Comment by quicksketch** [comment]
Ah actually looks like both @jenlampton and @serundeputy filed PRs. Everyone is so enthusiastic! I merged the PR at https://github.com/backdrop/backdrop/pull/749.

**Comment by serundeputy** [comment]
haha; no worries, live and learn™; thanks @jenlampton and @quicksketch :+1:
