### ISSUE TITLE
[UX] Use "Edit" / "Configure" consistently and correctly in core

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#771]
Some of our configuration pages have a menu item (or tab) that says "edit" or "settings" instead of configure. We should choose one term, and use it consistently throughout core. Edit should be used for content, and configure should be used for configuration. Below is a list of places that will need to be reviewed for correct terminology:
- [x] https://github.com/backdrop/backdrop/pull/1181 | Views (change "edit" to "configure")
- [x] https://github.com/backdrop/backdrop/pull/1101 | Menus (change "list links" to "edit links" and "edit menu" to "configure")
- [x] https://github.com/backdrop/backdrop/pull/1097 | Contact (change "edit" to "configure")
- [x] https://github.com/backdrop/backdrop/pull/1098 | Content types (change "edit" to "configure")
- [x] https://github.com/backdrop/backdrop/pull/1100 | Taxonomy vocabulary (change "edit vocabulary" to "configure")
- [x] https://github.com/backdrop/backdrop/pull/1099 | ~~Blocks (change "configure" to "edit")~~ Sticking with "configure" now. See https://github.com/backdrop/backdrop-issues/issues/1428.

I'm not sure about this one:
- ~~~Layouts (change "settings" to "configure")~~~ 
- See https://github.com/backdrop/backdrop-issues/issues/1503 [UX] Layouts - better terminology for configuration pages

**Comment by klonos** [comment]
Oh, I'm liking Backdrop more and more each day. It's slowly becoming what Drupal 7 should have been. Thanx Jen for filing this.

**Comment by quicksketch** [comment]
I reviewed the PR at https://github.com/backdrop/backdrop/pull/990 today and it indeed does all the changes @jenlampton specified. However, I question a few of these:

- Taxonomy term (change "edit" to "configure")

This is a question of whether terms are content or configuration. As far as their storage, they're in the database and so considered content. They are also "entities", which puts them into the same category as nodes, users, and files. I don't think you'd configure any of those. So I think terms should stay as "Edit term", not "Configure term".

- Menus (change "list links" to "edit" and "edit menu" to "configure")

Okay, we have some deeper problems here. I really don't want to have *both* an "Edit" and "Configure" link on the *same* thing. This would be okay I think if it was "Edit links" and "Configure menu". However, the best-case scenario would be combining these to be the same page, with the menu configuration at the top of the page and the list of links at the bottom. In the mean time, let's just fix the link labels, but be more verbose than just "Edit" and "Configure".

**Comment by klonos** [comment]
> This is a question of whether terms are content or configuration. ... So I think terms should stay as "Edit term", not "Configure term".

In #203 we are discussing simplifying the terms "taxonomy", "vocabulary" and "term" and using "content tags", "tag group" and "tag" instead. The way I see it, tags are edited - not configured. Same for tag groups.

> However, the best-case scenario would be combining these to be the same page, with the menu configuration at the top of the page and the list of links at the bottom.

That is actually #475 and it would help towards implementing #732, so :+1: from me.

> ...let's just fix the link labels, but be more verbose than just "Edit" and "Configure".

:+1: too.

**Comment by jenlampton** [comment]
I just filed PRs for everything here except layouts.

> This is a question of whether terms are content or configuration. 

I agree, left taxonomy terms using "Edit" since terms are really more content than config.

> I really don't want to have both an "Edit" and "Configure" link on the same thing. This would be okay I think if it was "Edit links" and "Configure menu". However, the best-case scenario would be combining these to be the same page, with the menu configuration at the top of the page and the list of links at the bottom. In the mean time, let's just fix the link labels, but be more verbose than just "Edit" and "Configure".

For menus, I changed the menu configuration link to "Configure".  You are on a page that lists menus, it should be obvious that "Configure" is for configuring the menu.  

I totally agree with you about having edit/configure on the same item being confusing.  We can't even use the words consistently, how do we expect our users to know the difference? 

For links I changed "List links" to "Edit links".  

Since this is the default action it needs to contain the word "edit" (because that's what people's eyes are scanning for, because that's what people want to do) but I agree that it should also include the word "links" because 1) that's what they are looking to edit 2) that word was in the D7 UI and people coming from D7 will be scanning for the word "links" and 3) it would be confusing if someone did open the drop-button and found both "Edit" and "Configure" with no context on either.

I know we have another issue open about consolidating the config on the same page as the links, but I'm starting to have second thoughts about that being "the best-case scenario". Some sites have very large menus. Adding more things into a single already-complicated interface might not be the best solution. 

Baby steps. Can we start here? :)

**Comment by klonos** [comment]
> Baby steps. Can we start here?

:+1:

**Comment by jenlampton** [comment]
All PRs have been rebased and should be able to get in ASAP.

**Comment by quicksketch** [comment]
I merged in all the ready pull requests with the exception of the blocks change (https://github.com/backdrop/backdrop/pull/1099). Over in https://github.com/backdrop/backdrop-issues/issues/1428, we've had a change of direction and decided to keep blocks as "structural" and move them from the database into configuration JSON files. So I believe that means that it would keep "Configure" instead of being changed to "Edit".

Let's leave Layout settings as-is for now. Could we get a PR for the last remaining item of Views?

**Comment by jenlampton** [comment]
Just posted a PR for views, I'm expecting a lot of test fails, no way I got them all in that first pass :)

**Comment by quicksketch** [comment]
The Views PR worked great! Eventually. :)

One last item remaining here:

>  Layouts (change "settings" to "configure")

So this gets a bit messier than just that. Layout currently defines two paths for configuring a layout:

```
admin/structure/layouts/manage/%/edit
admin/structure/layouts/manage/%/settings
```

If we did this properly, we'd rename both of these menu items so that `edit` became `blocks` (or something) and `settings` became `configure`. Then the tabs would look like:

![selection_035](https://cloud.githubusercontent.com/assets/100206/12219786/3b454b08-b706-11e5-88ff-c4691e00a371.png)

Thoughts?

**Comment by jenlampton** [comment]
Let's skip the layout configure link for now and do that in a layouts-related follow up.

**Comment by quicksketch** [comment]
Ha, okay let's close this one. It has had enough PRs for one issue.
