### ISSUE TITLE
[UX] Terminology Use "Default" / "Overridden" / "Custom" consistently for config state

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#772]
There are many places in core that will have a default vs overridden config state. We should make sure that the terminology we use in UIs is consistent around these concepts. Below is a list of places where default configurations (provided by core) can be overridden, and sometimes reverted:
- Image styles (Default / Custom / Overridden)
-  Layouts (Default / User-created / Overridden)
-  Views (Module-provided default / User-created / User overriding default)

Here's my recommendation for terminology:
- [x] **Default (module-provided) / Custom / Overridden**

My thinking is this: 1) people's eyes will be scanning for the word 'Default' so we should put that first, but I like adding that the thing was module-provided. 2) We want to avoid using the word "User" in the UI as much as possible, as people don't like being called users, and we want people to like Backdrop! 3) Overridden is enough. We should not use the word "default" in a state that is not default, and again, remove the word user.

The name for this flag is also inconsistent in core. 
-  Image styles: "SETTINGS"
-  Layouts: "STATUS"
-  Views  (not shown)

Here's my recommendation for the label
- [x] **Storage state**

Why? Because that's what we'll call the thing once we actually get it in. See https://github.com/backdrop/backdrop/pull/1144

**Comment by quicksketch** [comment]
Sounds good to me.

**Comment by quicksketch** [comment]
Merged into 1.x for 1.3.0.
