### ISSUE TITLE
[UX] Rename "People" to "User accounts"

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#773]
These are not people
![these-are-not-people](https://cloud.githubusercontent.com/assets/397895/6322001/07ab5fb4-bac0-11e4-8186-bdefa83d1571.png)

**Comment by serundeputy** [comment]
![people-to-user-accounts](https://cloud.githubusercontent.com/assets/6763671/6541880/3a1f3e6c-c4b5-11e4-8eb6-d05d57b37b21.png)

also along with this are we changing all associated urls, i.e. `admin/config/people/` becomes `admin/config/user-accounts`?

**Comment by jenlampton** [comment]
I say yes, change the URLs to match.  But, @quicksketch sometimes considers that an "API change".  I don't personally see how changing paths could affect contrib, unless someone overrode the admin/people page with a layout or something (not likely)

**Comment by quicksketch** [comment]
> But, @quicksketch sometimes considers that an "API change". I don't personally see how changing paths could affect contrib

All of contrib will link to the old location if they ask the user change permissions or search for accounts. Other than linking, I'm not concerned about the paths. So if we want to provide a backwards-compatible layer to redirect the user from the old to new location, we can do this during the 1.x cycle, then remove it in 2.x.

**Comment by serundeputy** [comment]
This PR: https://github.com/backdrop/backdrop/pull/784
Changes the `menu` items, but not the URL `paths`.

Is an `update_hook` required in `user.install` to update the `views.view.user_admin.json` file and the `menu_links` table?

If it is decided to change the paths would the right course of action be to create new `$items` entries with the correct paths and leave the old `$items['admin/config/people']` entries in there with a `backdrop_goto()` callback?

**Comment by quicksketch** [comment]
> Is an update_hook required in user.install to update the views.view.user_admin.json file and the menu_links table?

I think the update to the View JSON file is going to be required. Just load with `config()`, modify, then save. I don't think you need to update the menu_links table, it should be automatically updated to use the new menu title on menu rebuild. On the other hand, it might not hurt to do it anyway, just so long as the menu path and title match exactly the previous values in the SQL query.

**Comment by serundeputy** [comment]
@quicksketch 
I  can't seem to figure out the syntax for `$config->set($var, $new_val)` when `$var` is value inside a nested array.

`views.view.user_admin.json`:
```json
"display": {
        "default": {
            "display_title": "Master",
            "display_plugin": "default",
            "display_options": {
                "query": { ... },
                  .
                  .
                  .
                "title": "User accounts",
                ...
```
which I load with: `$config = config('views.view.user_admin');`
in this case the thing I care about is `$config['default']['display_options']['title']`, but I can not seem to figure out to set it.  I've tried:
`$config->set($config['default']['display_options']['title'], 'new_val');`
`$config->set(['default']['display_options']['title'], 'new_val');`
but I can't seem to find anything in the API docs about nested values in the `.json` config files.  Any ideas?

**Comment by docwilmot** [comment]
Would `$config->set(display.default.display_options.title, 'new_val');` work? I seem to recall something like that.

**Comment by serundeputy** [comment]
@docwilmot @quicksketch 
great that works one adjustment quotes aboot the `json` trail: `$config->set('display.default.display_options.title', 'new_val');`

so, it seems that updates the file in the `files/config_aljsldfAWESOMEHASHlasdlf8/active/views.view.user_admin.json`

what I thought it would do is update the `core/modules/user/config/views.view.user_admin.json` file, so should I just update `core/modules/user/config/views.view.user_admin.json` manually as part of this PR?

**Comment by docwilmot** [comment]
The `modules/<module>/config` and `core/modules/<module>/config` files would be just default configs. Theyre copied to the `files/config_xx/active/` directory when the module is installed.

If the content of the json file in the  `files/config_xx/active/` directory is what you want to be default values, you can just copy and paste it into the `core/modules/<module>/config` directory.

Otherwise you can update the default manually.

**Comment by serundeputy** [comment]
thanks @docwilmot ; PR updated with update hook.
travis ci passed; https://github.com/backdrop/backdrop/pull/784

~Geoff

**Comment by serundeputy** [comment]
tagged for milestone 1.0.6; please remove if I've misstepped.
thanks.

**Comment by quicksketch** [comment]
Thanks @serundeputy! I think this is fine for the next bugfix release. Merged in https://github.com/backdrop/backdrop/pull/784.
