### ISSUE TITLE
[UX] Rename "View modes" to "Display" in the UI

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#774]
With views module now in core, we are going to be facing some terminology conflicts between views and view modes. If we instead were to refer to the different ways that nodes are displayed as "display modes" we could clear up some of the confusion. 

I'm tagging this issue "needs feedback" because changing `view modes` to `display modes` in the UI can be done now, but all the code that uses and effects view modes cannot be changed.  

Does improving the terminology conflicts in the UI benefit the community if things get more confusing under the hood for developers? We have several other places where the UI and the code don't match, but most of those areas are far less confusing concepts. How do people feel about this one?

Also related: https://github.com/backdrop/backdrop-issues/issues/315

**Comment by biolithic** [comment]
Is Display suite going to be ported (I honestly don't know if it can or
should).  This would further muddle this terminology.

**Comment by jenlampton** [comment]
@biolithic I don't think it will be necessary since we now have layouts, but I have seen a handful of sites that are using both DS and Panels. I personally think that's a bad idea (and I'm removing DS from sites I work on that have both) people may still choose to port it.

**Comment by CaffeinatedJim** [comment]
Hi,

In my opinion, Display Modes are much more semantically named than "View Modes".  In D7, I use Entity View Modes on most of my projects, and have dabbled with Display Suite.  With either, I find myself communicating with technical and non-technical staff and clients about "the displays" or "the display of the node" more often than not.

Why do you need "mode(s)" in there?

Jim

**Comment by jenlampton** [comment]
Thanks for the feedback @CaffeinatedJim Are you recommending that we just call them "Displays?"

The only downside to that is that views already has "Displays" so that terminology is also in conflict.

**Comment by CaffeinatedJim** [comment]
Hi @jenlampton ,

Yes.  Personally, I don't think that is a downside to a site builder or end user.  I do understand that it may be problematic for the developer though.

If a View has a Display (Page, Block, Pane, etc), then a Node can have a Display (Full, Teaser, Feed, etc), as can other Entities...

Jim

**Comment by jenlampton** [comment]
@CaffeinatedJim at this point it's too late to change anything in the code for 1.x, so we'd be talking about user-interface terminology improvements only. The symmetry of both a view having a display and a node having a display is starting to sit well with me, even though they are different things. I think I like it.

**Comment by CaffeinatedJim** [comment]
Very exciting @jenlampton !

**Comment by klonos** [comment]
I don't mind the term "Display" being used for both nodes and views or even elsewhere. When we need to be specific, we'll simply say "View display" or "Node display". +1

**Comment by jenlampton** [comment]
:+1:

**Comment by stpaultim** [comment]
Unless I'm mistaken, this is a duplicate and the change has already been made and merged into 1.8.x

https://github.com/backdrop/backdrop-issues/issues/2376

Closing
