### ISSUE TITLE
[UX] Bring improvement from date_popup_authored module to core

### ISSUE THREAD

**Issue by and1truong** [backdrop/backdrop-issues#775]
[Date Popup Authored](https://www.drupal.org/project/date_popup_authored) provides a jQuery UI datepicker for the "Authored on" date field found on node submission forms. This allows content editors to pick a human-understandable date and not have to type the exact date format of the default Authored on field.

![](https://www.drupal.org/files/images/date_popup_authored.png)

**Comment by klonos** [comment]
Yes please! ...although the respective Drupal module requires [Date](https://www.drupal.org/project/date). Would that mean that we have to wait till date.module is in core?

**Comment by quicksketch** [comment]
I'd love to see this implemented in a minor release (e.g. 1.1.0 or 1.2.0). We already have HTML 5 elements for date and time in core, but they just show up as textfields. The date modified option on nodes is not Date-module-provided field, so I don't think we need Date module in core to fulfill this request.

**Comment by klonos** [comment]
That's great UX++

**Comment by Dinornis** [comment]
Closing. Date is now in core and also used as popup for the Authored on field in nodes.

**Comment by olafgrabienski** [comment]
@dinornis Thanks for reviewing older issues!

Having a look at a Backdrop 1.6.3 test site, I noticed that the "Authored on" field does have the date popup but it doesn't have a field for the time. So, if you want to specify a time, you have to enter it manually. Do you know if there's a setting somewhere to enable also a time field there?

**Comment by Dinornis** [comment]
My apologies, I failed to test this before closing this ticket.  Thanks for catching me Olaf.

Although, the `Authored on` field now uses a date popup, there are multiple problems with it that need to be fixed.

Should I repurpose this issue for reporting the problems or open a new one?

**Comment by olafgrabienski** [comment]
> My apologies ...

No problem, @Dinornis. Don't know if it's besser to open a new issue or to use this one. May depend on the problems, and let's ask @klonos !

**Comment by laryn** [comment]
@Dinornis I know there is at least one other issue already out there related to the `Authored on` dates, not sure if this is one of the issues you are noticing:
https://github.com/backdrop/backdrop-issues/issues/1370

**Comment by Dinornis** [comment]
Thanks @olafgrabienski & @laryn.  Yes, #1370 is the issue I was looking at.

How about we just close this issue, since the original request has been fulfilled and use the #1370 to address the problems there.

Everyone okay with that?

**Comment by olafgrabienski** [comment]
> Everyone okay with that?

@Dinornis Sure! And if you want to report the missing time field as well, I guess it would be another issue.
