### ISSUE TITLE
[UX] Move node/add to content/add so additional entities like blocks can be listed there

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#778]
Custom blocks are pieces of content, just like nodes (and arguably, terms).

When people create custom blocks, intuition tells them to go to the "Add content" page. When looking for these custom blocks later, people intuitively look under the "Content" category in the Admin bar.

Let's make these intuitions correct:
- [ ] Move the `Custom blocks` list under `Content` in the admin bar 
- [ ] Update node/add to content/add
- [ ] Add a `Create custom block` link on the `content/add` page

**Comment by quicksketch** [comment]
Considering the scope of this change (renaming URLs and moving functionality), this seems like a 2.x change.

**Comment by jenlampton** [comment]
Moving (or adding) a link the navigation can be done at any time.  Same with adding a link onto the node/add page.  Even if we don't change the paths in 1.x (I think changing structure/blocks is also not a big deal) we should still think about improving UX by putting links where people expect to find them.

**Comment by klonos** [comment]
> Blocks are pieces of content, just like nodes...

Well, perhaps this statement might be true for *custom* blocks, but not all blocks are content (per se). Blocks provided by views for example are not content. They do display something that can be generalized as content or that might be generated by content, but then again almost everything in a website can be perceived as content. That doesn't mean though that everything is content.

**Comment by jenlampton** [comment]
> perhaps this statement might be true for custom blocks

Sorry, that's what I meant :) I updated the first post in this issue to be more clear.

**Comment by klonos** [comment]
Title change to match as well.

**Comment by mikemccaffrey** [comment]
> @jenlampton: When people create custom blocks, intuition tells them to go to the "Add content" page. When looking for these custom blocks later, people intuitively look under the "Content" category in the Admin bar.

Well, the content category in the menu bar is provided by the content module, which defines content types. Now we are saying that blocks are content too and that we want to add them to the menus and pages defined by the content module. In that case, wouldn't it make sense to just tweak the content module to allow nodes of a content type to define blocks instead of pages with paths?

**Comment by quicksketch** [comment]
Per the discussion in https://github.com/backdrop/backdrop-issues/issues/1428, we're keeping blocks in structure. Let's consider new alternatives for URL-less nodes or some other entity type in https://github.com/backdrop/backdrop-issues/issues/100.
