### ISSUE TITLE
Create UX and DX issue tags?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#780]
We've been using [DX] and [UX] prefixes, why not tags? Easier to search.

**Comment by jenlampton** [comment]
Because the Labels UI in github is a bit of a mess, and doesn't scale well with lots and lots of labels in it. Plus, we already have a lot of labels :)  

Other communities use square brackets and capps in the issue titles to help identify certain kinds of issues, so we copied them.

**Comment by jenlampton** [comment]
To clarify, we're using labels for several groups of "categories" (type, audience, PR status, and audience) and square brackets for other more generic tags.
