### ISSUE TITLE
Need for theme settings file?

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#782]
core\includes\theme.inc lines 1413-1415 would seem to require a theme settings file e.g. bartik.settings.json and we don't yet have one. Am I reading the code correctly? If so, what should the settings file include?

**Comment by quicksketch** [comment]
Hi @Graham-72! You're correct. Theme settings are read from a `[theme_name].settings.json` config file. Themes currently do not ship with default config files, instead the default values are pulled from a theme's .info file (the same as they were in Drupal 7). See https://api.backdropcms.org/api/backdrop/core!includes!theme.inc/function/theme_get_setting/1 for details.

We do have other issues with theme settings currently. For example they don't import/export correctly, see #752.

**Comment by Graham-72** [comment]
Thanks @quicksketch . We have hit this problem with my port of ckeditor - https://github.com/backdrop-contrib/ckeditor/issues/2 - though I am trying to work out the full story of what is happening.

**Comment by quicksketch** [comment]
Thanks @Graham-72. From the error report in that issue, it looks like this may simply be a buggy call to theme_get_setting(). I've updated the issue over there and started following it. Let's continue over there with any debugging.
