### ISSUE TITLE
cache_get() missing default value for second parameter

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#783]
(This is a replacement issue for https://github.com/backdrop-ops/backdropcms.org/issues/52. @cellear writes:)

I'm attempting to port the Honeypot module to backdrop, and out of the box I'm seeing this message when I go to the configuration screen:

>  Warning: Missing argument 2 for cache_get(), called in [...]/modules/honeypot/honeypot.module on line 141 and defined in cache_get() (line 59 of [...]/core/includes/cache.inc).
>  Notice: Undefined variable: bin in cache_get() (line 61 of [...]/core/includes/cache.inc).

I could work around this in the module by supplying an argument, but this strikes me as an API change, which I know we're trying to avoid.  I looked for a change record mentioning cache_get() but didn't find one.  Comparing D7 to Backdrop code, I can see that Drupal's version:

```php
function cache_get($cid, $bin = 'cache') {
  return _cache_get_object($bin)->get($cid);
}
```
in Backdrop has changed to this:

```php
function cache_get($cid, $bin) {
  return cache($bin)->get($cid);
}
```
It looks like the signature has changed.  Is there a reason for that?  If so, I believe we need a change record.  If not, perhaps we should change it back?

**Comment by quicksketch** [comment]
I think we should add back the missing default parameter to cache_get(). That was an accidental exclusion when I restored the procedural wrappers. We're trying to maintain the most compatibility possible, and this was simply an oversight.

**Comment by cellearberkeley** [comment]
Can I do it?  I know how!  I think :)

**Comment by cellear** [comment]
Can I do it?  I know how.  I think :)

**Comment by cellear** [comment]
Created PR 754

**Comment by quicksketch** [comment]
Nice one!

**Comment by quicksketch** [comment]
Oh, maybe we should do another one for cache_set()? It has the same problem.

**Comment by cellear** [comment]
> Oh, maybe we should do another one for cache_set()? It has the same problem.

I'm on it!

**Comment by cellear** [comment]
@quicksketch, are you sure it has the same problem?  The code for cache_set() looks OK to me:

```php
function cache_set($cid, $data, $bin = 'cache', $expire = CACHE_PERMANENT) {
  return cache($bin)->set($cid, $data, $expire);
}
```
It sets a default for $bin, and it has the same signature that the D7 version does:

```php
function cache_set($cid, $data, $bin = 'cache', $expire = CACHE_PERMANENT) {
  return _cache_get_object($bin)->set($cid, $data, $expire);
}

**Comment by quicksketch** [comment]
Oh. woot! Yeah looks like it is okay. Thanks for checking!
