### ISSUE TITLE
Editing and saving the configuration of a newly added block before saving the Layout creates multiple instances of the block instead of saving its settings.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#786]
If a block config form is saved repeatedly before the layout is saved multiple copies of the block appear.
1. Go to Layout builder (`/admin/structure/layouts/manage/default`)
2. Click add block
3. Add any block - don't save Layout
4. Click configure on the same block
5. Save the configuration again...

Result: Every time one repeats steps 4 an 5 above, they get a new copy of the block in that Layout region.

Not sure if this is just me.

**Comment by klonos** [comment]
> Not sure if this is just me.

Nope, not just you. I confirm this bug. I hope you don't mind me editing the issue description and the STR.

**Comment by klonos** [comment]
...big issue title -I know- but one can now get what the issue is without reading the description.

**Comment by docwilmot** [comment]
Good @klonos.

**Comment by quicksketch** [comment]
I had this happen to me during a demo as well. When the layout is actually saved, there's only a single instance of that block. Likewise, if I try to remove the "duplicate" block, when the layout is saved, no block is saved there at all.

**Comment by quicksketch** [comment]
Filed a PR at https://github.com/backdrop/backdrop/pull/756.
