### ISSUE TITLE
Redirected to home page with "No active batch." message after full site import between sites

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#787]
When doing a full site import, it looks like it fails at the very end, redirecting the user to the homepage with the message "No active batch." Additionally, this means that caches aren't cleared after an import, so none of the new changes appear present until clearing the cache.

**Comment by quicksketch** [comment]
Hm, on further checking, I can't get this to reproduce. It seems to only happen the first time an import is done? After that, it seems to work fine.

**Comment by quicksketch** [comment]
Ah! I figured out why this is happening. It only happens when you try to import a site from one server to another, because each site has a separate "private_key" in `system.core.json`. When the private key is overwritten by the config sync, that causes the CSRF token in the batch operation to change, resulting in loosing the batch operation entirely, and it goes unfinished...

We'll need to think about this behavior. We could do a couple of different things:

- Manage the private key in a way that persists through the batch update (this could be messy).
- Move the private key into "state" instead of "config" so it doesn't get overridden/transferred ever.
- Prevent the importing of config across different sites entirely, throw a validation error if the private keys don't match exactly.

I think D8 took the last approach (prevent cross-site importing entirely). I'm leaning mostly towards the second approach (moving the key into state instead of config). The primary reason for allowing cross-site behavior is to make it easy to deploy or upgrade new sites. For example, building out an entire site structure on a local checkout, then just importing the config onto the live server (such as on Pantheon). Or if you built out a site after doing a site upgrade, you could rerun the upgrade path, then just pull in the finished configuration to "complete" the upgrade for any changes you made after running update.php the first time. Accidental importing of the wrong config archive is prevented in Backdrop mostly by its limitations: the source and target site have to have the exact same modules enabled, and deleting fields or content types isn't allowed through a config sync. That makes it unlikely you'd accidentally wipe out a whole site's config with another one's.

I'd love to hear other people's thoughts on this problem.

**Comment by klonos** [comment]
The third option sounds very limiting to me. I'd go with the second one too.

**Comment by docwilmot** [comment]
The full site import is likely to be a very useful feature if we could pull it off. And another great differentiator from drupal. 
And by definition, the private key is not meant to be shared between sites so it shouldn't be config anyway. 
So number two.

**Comment by quicksketch** [comment]
@jenlampton was of the same opinion. We should fix this problem as a bug fix and move the private key into state. Later we can add a feature to warn users about importing across different sites.

**Comment by quicksketch** [comment]
I filed a PR at https://github.com/backdrop/backdrop/pull/755. The fact that a private key affects the batch operation makes it tricky to modify in an update hook, so in the PR I just delete the private key from config and let backdrop_get_private_key() auto-create one on the fly, which is what already happens on new installs.
