### ISSUE TITLE
Block configuration form fails silently, doesnt show errors

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#790]
Related: https://github.com/backdrop/backdrop-issues/issues/762.
Code errors are difficult to pin down. The advice from @serundeputy was helpful but errors messages are all over the place: 
- undefined function errors in Apache logs
- undefined variables/syntax errors in PHP logs
- config errors in Watchdog

The AJAX spinner just briefly pops up then goes away; no error shows on screen. Or the configuration form just doesnt show.

Need better error messaging please.

**Comment by quicksketch** [comment]
If you're debugging errors that happen during AJAX requests, you might find it easier to simply disable JavaScript in your browser and click through the forms with individual page loads. The entire Layout UI should actually continue to work even without JS, and it should make debugging quite a bit easier.

**Comment by docwilmot** [comment]
Great, I'll try that.
Should consider how to get errors on screen though, if its possible. 
Thanks

**Comment by Graham-72** [comment]
Thanks @quicksketch for that tip about disabling Javascript. It solved a baffling problem for me today!

**Comment by docwilmot** [comment]
Agreed, very useful tip that was. And if you havent tried it yet, you can use a javascript toggle extension on chrome to switch js on and off instantly. Very useful too. [This one](https://chrome.google.com/webstore/detail/toggle-javascript/cidlcjdalomndpeagkjpnefhljffbnlo) worked brilliantly. I imagine there are Firefox alternatives too.

**Comment by Graham-72** [comment]
I have the 'Web Developer' extension with Firefox with all sorts of facilities like this. Thanks @docwilmot for your prompt to make use of it!
