### ISSUE TITLE
[CMI] Color module needs to regenerate CSS files during config import

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#792]
I ran across this while fixing https://github.com/backdrop/backdrop-issues/issues/752. We need to have Color module regenerate CSS files when doing a full site config import.

To reproduce:
- Change Bartik settings to a particular color scheme.
- Export config.
- Change Bartik settings again to a different color scheme.
- Import the config from step 2.
- Site is now missing CSS/colors in Bartik theme.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop/backdrop/pull/760, but it needs tests for this to be merged.

**Comment by herbdool** [comment]
@hosef tested with @quicksketch's steps above and it works for me. And looks like the new tests pass. Great work!

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/2222 into 1.x for 1.11.0. Thanks @hosef! That test implementation is simpler than I had expected, nice work!

We have a merge conflict that prevents cherry-picking back into 1.10.x. If it's acceptable that this only applies to 1.11.0, then we can leave as-is. If we need a backport, could you reroll the PR against 1.10.x?

Closing for now, please reopen if we make a backport.
