### ISSUE TITLE
Clean URLs online handbook link

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#793]
When clean URLs cannot be enabled, you get this message (on admin/config/search/clean-urls):

> Clean URLs cannot be enabled. If you are directed to this page or to a Page not found (404) error after testing for clean URLs, see the [online handbook](http://drupal.org/node/15365).

The 'online handbook' link points to drupal.org and needs to be updated to point to an equivalent page on backdropcms.org.

**Comment by quicksketch** [comment]
Yep. The big issue here is we don't have the documentation page yet to which we'll link.

**Comment by jrearick** [comment]
I just noticed this when my environment changed to no supporting Clean URLs. I am not finding anything about Clean URLs on the official documentation, yet. So perhaps the next step is to create this support document? 

The installation instructions has a troubleshooting section that might be a good place to mention this, but I think this topic might be long enough to warrant a page of its own.

**Comment by BWPanda** [comment]
Looks like this was fixed in https://github.com/backdrop/backdrop-issues/issues/2488. Backdrop's handbook page is: https://backdropcms.org/user-guide/clean-urls
