### ISSUE TITLE
drupal_get_form does not pass along extra arguments

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#794]
The compatibility function drupal_get_form() calls backdrop_get_form() without passing along any extra arguments. The extra arguments may be needed by the form generation function which is called by backdrop_get_form().

**Comment by quicksketch** [comment]
Hi @jromine! Wow, nice catch! You're right that's a pretty big hole in our backwards-compatibility. Are you up for filing a pull request?

**Comment by quicksketch** [comment]
Thanks!! Merged.
