### ISSUE TITLE
Modules can't be disabled; reason not explained (field type in use)

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#803]
On the Modules page (admin/modules/list), if a module provides a field type and the field type is in use, the module cannot be disabled. However, the description column does not indicate this reason.

**Comment by quicksketch** [comment]
This looks great! Could you provide a screenshot before and after?

**Comment by jromine** [comment]
Before:
![803-before](https://cloud.githubusercontent.com/assets/350497/6529432/8a7469d8-c3dd-11e4-8d28-ebda06dc40bf.png)

After:
![803-after](https://cloud.githubusercontent.com/assets/350497/6529410/5f649330-c3dd-11e4-9806-cd2fb759b545.png)

**Comment by quicksketch** [comment]
Thanks! That helps a lot! Although it's a little odd because it's not a "module" that it's "required by", we do the same thing of including the explanation when a module is required by an install profile.

So merged in. Thanks again! This will be in the 1.0.4 release that should be out shortly.
