### ISSUE TITLE
ajax error during installation

### ISSUE THREAD

**Issue by adrianmak** [backdrop/backdrop-issues#805]
ubuntu 14.04.01 x64
nginx 1.4.6
php5.5.9 (php5-fpm)
mysql 5.5.41
backdrop 1.0.3

After enter dbname dbpasswor and dbuser and continue, this error appear.
I read from other issue, said that it is caused by php opcache enabled. (I disabled opcache before installation)

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://nginx.local.net/backdrop/core/install.php?langcode=en&profile=standard&id=1&op=do_nojs&op=do StatusText: OK ResponseText: Home | Backdrop @import url("http://nginx.local.net/backdrop/core/misc/normalize.css?"); @import url("http://nginx.local.net/backdrop/core/modules/system/css/system.theme.css?"); @import url("http://nginx.local.net/backdrop/core/modules/system/css/system.css?"); @import url("http://nginx.local.net/backdrop/core/modules/user/css/user.css?"); @import url("http://nginx.local.net/backdrop/core/modules/system/css/system.admin.css?"); @import url("http://nginx.local.net/backdrop/core/modules/system/css/system.maintenance.css?"); @import url("http://nginx.local.net/backdrop/core/themes/seven/style.css?"); @import url("http://nginx.local.net/backdrop/core/themes/seven/seven.base.css?"); Installation tasksStep 4 of 5Choose language(done)Verify requirements(done)Set up database(done)Install profile(active)Configure site Home SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

**Comment by quicksketch** [comment]
Hi @adrianmak! Thanks for filing this issue. From the looks of things, this looks like it may be a MySQL issue. We may need to do adjustment on the Backdrop side to reduce the size of whatever that index is that is causing the problem; it's odd that this doesn't happen to all new installations of Backdrop.

In the mean time, to fix this for your own installation, you can fix this if you can adjust the my.ini configuration of MySQL with the following option:

```
innodb_large_prefix = ON;
```

http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/

I haven't needed to do this on any of my own installations of Backdrop, so this may be a MySQL version-specific issue.

**Comment by quicksketch** [comment]
I just checked in my own local install (MySQL 5.5.38) and this option is off in my installation. Very odd that it would be required on one install but not another.

**Comment by xmacinfo** [comment]
I just got this error on my first Drupal 7 to Backdrop 1.1.2 upgrade.

# taxonomy module
## Update #1002

    Failed: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes: ALTER TABLE {taxonomy_term_data} ADD INDEX `vocabulary_name` (`vocabulary`, `name`); Array ( ) in db_add_index() (line 2947 of /Sites/typofute.com/core/includes/database/database.inc).

Adding this line in my.cnf did not solve the issue:

```  
innodb_large_prefix = ON;  
```

**Comment by xmacinfo** [comment]
The whole website upgraded successfully saved the Taxonomy module upgrade, which has only 3 remaining upgrades to do, starting at 1002.

Investigating.

**Comment by xmacinfo** [comment]
My part is solved.

My Taxanomy tables were MyISAM! (This is what happens when a site created in Drupal 5 migrated to 6 and 6 and then Backdrop uses a very old database).

I did convert the taxonomy tables to InnoDB and now everything is fine.

**Comment by quicksketch** [comment]
Nice one @xmacinfo. I feel honored that you'd port such a long-running site to Backdrop!
