### ISSUE TITLE
dblog critical icon does not appear

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#806]
The critical error icon message-16-error.png doesn't appear in the Recent log messages report.

**Comment by quicksketch** [comment]
Thanks @jromine! Fixed this and cherry-picked into the 1.0.x branch so it will be in the next bugfix release.

**Comment by quicksketch** [comment]
This brought up an area we need to fix in the 1.1.0 release as well, over in https://github.com/backdrop/backdrop-issues/issues/739. Thanks so much for filing this issue (and for the PR)!
