### ISSUE TITLE
Settle on a grid system and ship it with core

### ISSUE THREAD

**Issue by philippejadin** [backdrop/backdrop-issues#807]
Providing a default, standard grid system would help and simplify.

I'd vote for bootstrap (the grid part only, no need to ship the whole thing), since it's well documented and used by a lot. Also it allows one to define various column size depending on device size, which is nicely abstracted in small, medium, large, extra large class names.

But you probably know that already :-)

I came across this article : http://www.sooperthemes.com/drupal-blog/drupal-cms-powerstart-tutorial-2-responsive-websites-bootstrap-3-grid

It gives a good idea of what a standard grid system would bring for the overall themer & sitebuilder experience. It seems to be more wordpress like (if you see what I mean) the way they work, but imho there is something to learn there.

For the layout module, I guess it would mean no impedance mismatch when storing layout info : just store the css and parse it accordingly to provide a good site builder experience. Multi device publishing is probably dead anyway, so the pipe dream of publishing to pdf an other formats at the same time while keeping layout from an abstracted system is not worth it anymore.

**Comment by quicksketch** [comment]
Hi @philippejadin, thanks for opening this issue.

With Layouts decoupled into their own concept, we've (intentionally) separated out layouts from theming. This generally means that you can use any grid system you want, and that is entirely separate from the theme. This allows for stand-alone projects (like the [Radix layouts](https://github.com/backdrop-contrib/radix_layouts)) to provide a number of layouts that are all based on a particular grid system (they use Bootstrap as well). It also means you could mix together multiple grid systems on the same site with no problem. As a page can only have a single layout, only a single grid system would be loaded for that page.

As for making a commitment to one particular grid system, I think we run into the same issue as https://github.com/backdrop/backdrop-issues/issues/698. The concept of layouts are too new to start locking ourselves in to particular paths of development. We should let Layouts mature and work out the needs of the current system before chasing down a particular approach when contrib can already provide a variety of options.

In the mean time, if you want to use Bootstrap with Backdrop, I'd recommend taking a look at Radix and see how it works with Layouts. If it's exactly what you're looking for, we already have an issue for putting it in core at https://github.com/backdrop/backdrop-issues/issues/698. Though as I've stated over there, I think it's too soon to be including so many layouts when we haven't seen the in-action repercussions of what we've built thus far.

**Comment by philippejadin** [comment]
Looked a bit deeper at the current layout implementation, and it already rocks. Makes sense out of the box (vs  the awful beast that panels looks like to be). Keeping a level of abstraction seems the way to go currently (and maybe for ever).

Thanks!

**Comment by quicksketch** [comment]
Thanks for the followup @philippejadin!
