### ISSUE TITLE
Javascript core functions not included in API documentation

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#809]
Searching https://api.backdropcms.org/ for 'backdropSetSummary' (a Javascript function implemented in misc/form.js) yielded no results.  

We should add the core Javascript functions to the API documentation.

**Comment by quicksketch** [comment]
Hi @jromine! Thanks you're quite right. The Drupal documentation has the same problem (AFAIK), and we'd need a way to start indexing JS files for documentation.

Let's refile this issue in the API module in contrib. Once it's added there, the Backdrop API site will inherit those changes.

**Comment by quicksketch** [comment]
I filed an issue https://github.com/backdrop-contrib/api/issues/1. Quite fitting that it is issue number 1.
