### ISSUE TITLE
[UX] dialog / modal close X missing from upper right corner

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#812]
The X that allows you to close a dialog is missing.

**Comment by docwilmot** [comment]
confirmed

**Comment by serundeputy** [comment]
@jenlampton oops; looks like I broke this moving `seven`'s css files into the css dir;
Travis testing now: https://github.com/backdrop/backdrop/pull/778

**Comment by quicksketch** [comment]
Thanks @serundeputy!
