### ISSUE TITLE
user_role_permissions() return value doesn't match documentation

### ISSUE THREAD

**Issue by jromine** [backdrop/backdrop-issues#813]
`user_role_permissions()` now takes an array of role machine names, rather than array whose keys are the role IDs of interest (as in Drupal 7). The return value is now a single array of permissions for all role names present in the argument array (related: #177).

- Update docblock to indicate its argument is an array of role **machine** names.
- Update docblock to indicate its return value is single array of permissions.
- Add an API Change Record documenting this change in behavior from Drupal 7.

Note that `user_role_permissions()` appears to be called from Backdrop core in only one place (in user.module). Since this API no longer matches Drupal, perhaps it should be made an internal-only function, and/or be replaced by something else.

**Comment by quicksketch** [comment]
Let's get a change record added for this minor change as well, although you're right that this function is rarely called; I'm guessing your own module probably ran into this difference.
