### ISSUE TITLE
Some uasort() class needs conversion.

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#818]
This is causing some PHP warning when building nodes.

**Comment by jdanthinne** [comment]
PR here: https://github.com/backdrop/backdrop/pull/782

**Comment by quicksketch** [comment]
Thanks! You're right, this is a problem because `element_sort()` is now in drupal.inc, so it's not going to be loaded when compatibility mode is turned off.

**Comment by quicksketch** [comment]
The PR looks good also. We have a random failure in Travis. I'm re-running it now.

**Comment by jdanthinne** [comment]
Yes, I turn off compatibility mode by default for everything I build, so those bugs are easier to catch.

**Comment by quicksketch** [comment]
> Yes, I turn off compatibility mode by default for everything I build, so those bugs are easier to catch.

Good man!

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/782.
