### ISSUE TITLE
how to set a new default layout?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#819]
We need a "set as default" switch?

**Comment by quicksketch** [comment]
Hi @docwilmot, effectively there is no way to set a layout as the default. There is only one default layout (or two if you take into consideration the administrative default layout). Although we could make the default layout swappable through a config setting somewhere, right now our codebase has the layout with the machine name "default" hard-coded as always the default layout, and the default layout cannot be deleted.

**Comment by docwilmot** [comment]
OK, what if a user wants to use only a particular layout for all (non-admin) paths? i.e. never use the default? Do I need to set a layout for every single possible path? 
Can we set a shorthand for "all paths except those with specified layouts" like " * " or "/" or "%"?

**Comment by quicksketch** [comment]
> OK, what if a user wants to use only a particular layout for all (non-admin) paths? i.e. never use the default? Do I need to set a layout for every single possible path? 

I don't think I'm understanding why you wouldn't use the default layout. If you want to configure a layout to work on every path and ignore the default... you should just use the default and not make a new layout in the first place.

>  Can we set a shorthand for "all paths except those with specified layouts" like " * " or "/" or "%"?

Path matching would significantly increase the amount of checking that Layouts would need to do to determine which layout would be appropriate for the current path. Architecturally, we only support exact path matches (e.g. "node/%" is only a single entry in the menu system, even though a lot of different pages use that path). The support for "wildcards" only works for single part of the path, which makes it a single entry in the menu system. If we did full path matching, the process to determine the "right" layout for a given path becomes a lot more complicated. Imagine if you set up 6 layouts that all had a "use this layout except on these paths" option set. Layout module would need to evaluate all of those layouts and determine the access rules on all of them on every single path. You'd be enabling users to shoot themselves in the foot remarkably easily, and determining which layout would effect which path would become a much more complicated task for administrators.

So for these reasons, there is only the ability to create a layout for specific paths. This prevents them from ever conflicting with each other, which makes administration a lot simpler and is performant when it comes to determining the correct layout for a particular path. If a path doesn't have a specific layout defined, then the default is used.

**Comment by docwilmot** [comment]
Ignore me and never listen to me again. 
I need to go to bed now.
Brain fatigue.
Thanks.

**Comment by quicksketch** [comment]
Don't worry, there must be something about this approach that isn't quite expected (even though it's simple), as it seems to come up pretty regularly when I talk about Backdrop. :smile:
