### ISSUE TITLE
Add a run-updates.sh script to run updates from the command line

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#820]
On pantheon the updates can't be run from the dashboard because that depends on drush, and we don't have drush working quite yet.  As an interim solution (and since there are other people who may want to run updates from the command line) we should add a run-updates.sh script into the scripts directory in core.

**Comment by serundeputy** [comment]
I like the sound of this.  Should the `run-updates.sh` script curl in the latest 1.0.x.tgz?

*  `curl https://github.com/backdrop/backdrop/archive/v1.0.5.zip`
* `tar xzf latest.tgz`
* `mv current ./core to ./bub_core`
* `mv {untar} ./core`

something like that?

**Comment by quicksketch** [comment]
I think we're just talking about a shell version of `update.php`, just to run updates that are already there.

**Comment by serundeputy** [comment]
`drush updb` works now.

Does `drush updb` satisfy this requirement?

**Comment by jenlampton** [comment]
Yes, if we can get @greganderson or @populist or others over at Pantheon to install the drush commands for Backdrop.

**Comment by quicksketch** [comment]
Though we'll need to fix Drush so that doesn't break Drupal 7 installations when the Backdrop extension is installed. https://github.com/backdrop-contrib/drush/issues/9

**Comment by jenlampton** [comment]
@quicksketch I'm not sure how that works on pantheon - it may not matter since each site is on it's own?

**Comment by populist** [comment]
The way it works on Pantheon is that each CMS we deploy (Drupal 7, Drupal 8, WordPress, Backdrop) has special options. In the case of Drush, sites based on D7 uses a different version of Drush than D8. Backdrop uses the same version as D7 of course.

**Comment by serundeputy** [comment]
@populist what we/Backdrop acstually needs is what is currently the `master` branch of the drush project, but I think will become the 8.x branch once the drush community starts working on Drush 9.

But for now the backdrop/drush extension needs the `masster` branch of drush.

thanks,
~Geoff

**Comment by populist** [comment]
@serundeputy assuming that @greg-1-anderson gets that version running for Drupal 8, we can easily switch Backdrop to use that version instead.

**Comment by greg-1-anderson** [comment]
Currently, Pantheon is running Drush 8 (current master branch) for all Drupal 8, and all new Drupal 7 sites. If you have a very old Drupal 7 site, it will be running Drush 5, but the easy workaround here for Backdrop is to just make a new Pantheon site, so you can be sure that your base Drush is the right version.

From there, I'm not sure why the base configuration isn't working (presuming that your Backdrop Drush bootstrap class is appropriately loaded and available), but I posted a suggested workaround at #1682 that could be tried.

**Comment by greg-1-anderson** [comment]
Also, before trying #1682, I should also ask if anyone tried just putting the Backdrop drush commands at PANTHEON_BACKDROP_ROOT/drush.  That should be sufficient on a new Pantheon site running Drush 8.

**Comment by serundeputy** [comment]
thanks @populist and @greg-1-anderson for looking at these issues!

@greg-1-anderson I've installed a brand new Pantheon Backdrop site.
Added the backdrop/drush extension to `PANTHEON_BACKDROP_ROOT/drush`and committed to pantheon.

Here is a drush updb attempt:
```
geoff@gspmbp bd-drush (master) $ terminus --site=bd-drush --env=dev drush "updb"
[2016-03-07 23:59:52] [warning] Note: This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
[2016-03-07 23:59:52] [info] Running drush updb on bd-drush-dev
    cmd: 'updb'
    site: 'bd-drush'
    env: 'dev'
Drush 5.10.1 does not support Drupal . Use Drush 4 instead.              [error]
The drush command 'updb' could not be executed.                          [error]
Drush was not able to start (bootstrap) the Drupal database.             [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a
configured database. In this case you can select another site with a
working database setup by specifying the URI to use with the --uri
parameter on the command line. See `drush topic docs-aliases` for
details.
 * connect the database through a socket. The socket file may be
wrong or the php-cli may have no access to it in a jailed shell. See
http://drupal.org/node/1428638 for details.

Drush was attempting to connect to:
  Drupal version    :
  Default theme     : garland
  Administration theme: garland
  PHP configuration :
/srv/bindings/997d9247fc0b48eda99d0765977c6736/php.ini
/srv/bindings/997d9247fc0b48eda99d0765977c6736/php.ini
  Drush version     : 5.10.1
  Drush configuration:
/srv/bindings/997d9247fc0b48eda99d0765977c6736/.drush/drushrc.php
  Drupal root       :
/srv/bindings/997d9247fc0b48eda99d0765977c6736/code
  %paths            : Array


[2016-03-07 23:59:57] [error] Either we could not connect, or Drush has exited with code 1
    client: 'Drush'
    code: 1
```

any ideas?  Looks like it is picking up `Drush version     : 5.10.1`.

thanks,
~Geoff

**Comment by greg-1-anderson** [comment]
Drush 5 is totally wrong. I was going to try to fix the Drush version for you, but I can't find your site. Did you delete it already?

Maybe try making a new Drupal 8 site, remove everything from the repository, and re-add Backdrop.  Then commit and install through the normal web UI, and see what version of Drush you get.  If you do this, your framework should be set to 'drupal8', and you should as a result always get Drush 8.

**Comment by serundeputy** [comment]
@greg-1-andersonhttp://dev-bd-drush.pantheonsite.io

**Comment by greg-1-anderson** [comment]
I guess I didn't ask Hubot nicely enough. Found it, set your Drush to 8. See if it runs better now. I'm going to take a look at your framework setting too.

**Comment by greg-1-anderson** [comment]
Oh, Backdrop has its own framework value. Makes sense; also explains why it does not work out of the box.

**Comment by serundeputy** [comment]
different:

```
geoff@gspmbp bd-drush (master) $ terminus --site=bd-drush --env=dev drush "updb"
[2016-03-08 00:53:09] [warning] Note: This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
[2016-03-08 00:53:09] [info] Running drush updb on bd-drush-dev
    cmd: 'updb'
    site: 'bd-drush'
    env: 'dev'

Parse error: syntax error, unexpected '[' in /opt/pantheon/drush-8/includes/startup.inc on line 63
Ok
[2016-03-08 00:53:15] [error] Either we could not connect, or Drush has exited with code 255
    client: 'Drush'
    code: 255
geoff@gspmbp bd-drush (master) $ terminus --site=bd-drush --env=dev drush "cc all"
[2016-03-08 00:53:33] [warning] Note: This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
[2016-03-08 00:53:33] [info] Running drush cc all on bd-drush-dev
    cmd: 'cc all'
    site: 'bd-drush'
    env: 'dev'

Parse error: syntax error, unexpected '[' in /opt/pantheon/drush-8/includes/startup.inc on line 63
Ok
[2016-03-08 00:53:40] [error] Either we could not connect, or Drush has exited with code 255
    client: 'Drush'
    code: 255
```

**Comment by greg-1-anderson** [comment]
I'll bet you would really like to have php 5 running on that endpoint too.  Made that change as well; sorry I didn't notice that the first time.

**Comment by serundeputy** [comment]
@greg-1-anderson did you change the framework value or something?

now it is looking for other versions.
here are `cc all -v` and `updb -v` outputs:
```
geoff@gspmbp ~ $ terminus --site=bd-drush --env=dev drush "cc all"
[2016-03-08 21:04:43] [warning] Note: This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
[2016-03-08 21:04:43] [info] Running drush cc all on bd-drush-dev
    cmd: 'cc all'
    site: 'bd-drush'
    env: 'dev'
No Drupal site found, only 'drush' cache was cleared.                  [warning]
geoff@gspmbp ~ $ terminus --site=bd-drush --env=dev drush "cc all -v"
[2016-03-08 21:05:07] [warning] Note: This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
[2016-03-08 21:05:07] [info] Running drush cc all -v on bd-drush-dev
    cmd: 'cc all -v'
    site: 'bd-drush'
    env: 'dev'
Include /etc/drush/drush-commandfiles                                   [notice]
Include /etc/drush/drush-8-commandfiles                                 [notice]
Include /etc/drush/drupal-7-drush-commandfiles                          [notice]
No Drupal site found, only 'drush' cache was cleared.                  [warning]
Command dispatch complete                                               [notice]
geoff@gspmbp ~ $ terminus --site=bd-drush --env=dev drush "updb -v"
[2016-03-08 21:05:33] [warning] Note: This environment is in read-only Git mode. If you want to make changes to the codebase of this site (e.g. updating modules or plugins), you will need to toggle into read/write SFTP mode first.
[2016-03-08 21:05:33] [info] Running drush updb -v on bd-drush-dev
    cmd: 'updb -v'
    site: 'bd-drush'
    env: 'dev'
Include /etc/drush/drush-commandfiles                                   [notice]
Include /etc/drush/drush-8-commandfiles                                 [notice]
Include /etc/drush/drupal-7-drush-commandfiles                          [notice]
Command updatedb needs a higher bootstrap level to run - you will        [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'updb' could not be executed.                          [error]
[2016-03-08 21:05:41] [error] Either we could not connect, or Drush has exited with code 1
    client: 'Drush'
    code: 1
```

maybe one step closer here.

~Geoff

**Comment by greg-1-anderson** [comment]
The framework value is still "backdrop", but I forced your Drush to version 8, and your PHP to version 5.5.  It looks like you are running Drush 8 now, but the backdrop include file is not being loaded by Drush.

**Comment by serundeputy** [comment]
@greg-1-anderson so i'll try the #1682 method now; on this site

**Comment by greg-1-anderson** [comment]
So, your backdrop class actually needs to go in BACKDROP_ROOT/drush/bootstrap.  I moved it there, and now we're getting a little farther.  Drush is selecting your bootstrap class, but it is now saying that it cannot find a backdrop installation directory.

Take a look at my last two commits, and see if you can debug your site detection code.  You probably don't need to put all of Drush in the drush folder at this point.

**Comment by greg-1-anderson** [comment]
@serundeputy ^^

**Comment by serundeputy** [comment]
@greg-1-anderson does this mean it is failing on `bootstrap_backdrop_configuration()`:

```
geoff@gspmbp bd-drush (master) $ devd cc all --debug
Using the Drush script found at /Users/geoff/drush-dev/drush.launcher using pcntl_exec
Cache HIT cid: 8.1-dev-commandfiles-0-4d09537459ffc6db259f884a2dfa3d77 [0.01 sec, 2.48 MB]                                                    [debug]
Cache HIT cid: 8.1-dev-commandfiles--1-9c4939192d38b3537ae973e0fd952639 [0.02 sec, 4.57 MB]                                                   [debug]
Bootstrap to phase 1. [0.09 sec, 6.92 MB]                                                                                                 [bootstrap]
Drush bootstrap phase : bootstrap_backdrop_root() [0.09 sec, 6.93 MB]                                                                     [bootstrap]
Initialized Backdrop 1.3.3 root directory at /Users/geoff/sites/bd-drush [0.1 sec, 7.33 MB]                                                  [notice]
Find command files for phase 1 (max=1) [0.1 sec, 5.13 MB]                                                                                     [debug]
Cache HIT cid: 8.1-dev-commandfiles-1-b62b0ac3379a9c394ce42a5126d02b97 [0.1 sec, 5.13 MB]                                                     [debug]
Undefined index: description command.inc:1232 [0.1 sec, 5.29 MB]                                                                             [notice]
Trying to bootstrap as far as we can. [0.13 sec, 7.47 MB]                                                                                     [debug]
Drush bootstrap phase : bootstrap_backdrop_site() [0.16 sec, 7.5 MB]                                                                      [bootstrap]
Initialized Backdrop site bd-drush at . [0.16 sec, 7.5 MB]                                                                                   [notice]
Find command files for phase 2 (max=6) [0.17 sec, 5.22 MB]                                                                                    [debug]
Drush bootstrap phase : bootstrap_backdrop_configuration() [0.17 sec, 5.22 MB]                                                            [bootstrap]


		 geoff is the best.




Drush command terminated abnormally due to an unrecoverable error. [0.18 sec, 6.67 MB]
```

I put in some debug code and does not seem to get past `bootstrap_backdrop_configuration()`

**Comment by greg-1-anderson** [comment]
Well, the good news, at least, is that it appears that the Backdrop bootstrap object is being correctly selected.

**Comment by klonos** [comment]
> ```geoff is the best.```

:laughing:

**Comment by greg-1-anderson** [comment]
Not getting as far as you are; when I run `drush status` it still just says `A Backdrop installation directory could not be found`

**Comment by serundeputy** [comment]
@greg-1-anderson `drush status` is not a supported backdrop drush command yet :wolf: try 

* `drush cc all`
* `drush updb`

thanks,
~ Geoff ('aka' da best);

**Comment by serundeputy** [comment]
oh; but you got Backdrop installation could not be found; hrmm;

**Comment by greg-1-anderson** [comment]
Same result with cc all.

**Comment by BWPanda** [comment]
As far as I know, Drush is working well now. Further issues can be opened in Drush's issue queue.

**Comment by serundeputy** [comment]
I guess it depends on wether this issues is about getting a client update.php working or about getting update.php to work via Pantheon dashboard; much of the conversation in this issues is about Pantheon dashboard. That being said we could reopen this issues in backdrop-ops/backdrop-pantheon if that is the intention.
