### ISSUE TITLE
Six more handlers to add to function node_autoload_info

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#824]
function node_autoload_info also requires

views_handler_argument_node_created_fulldate
views_handler_argument_node_created_year
views_handler_argument_node_created_year_month
views_handler_argument_node_created_month
views_handler_argument_node_created_day
views_handler_argument_node_created_week

which are in
views_handler_argument_dates_various.inc

**Comment by quicksketch** [comment]
Let's try to get this simple fix into the next bugfix release.

**Comment by serundeputy** [comment]
PR updated and `rebased`; removed autoload_info of class that does not exist.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/issues/792. Thanks @serundeputy!
