### ISSUE TITLE
Installation language file not detected

### ISSUE THREAD

**Issue by pablo-romero** [backdrop/backdrop-issues#827]
I've been trying to install Backdrop in a different language, but my _.po_ file never gets detected by the installer.

If I place my translation file in **files/translations** nothing happens, only English is available in the select box (even after reloading).

I'm testing this on a local server with:
- Apache 2.4.10
- PHP 5.6.3
- MySQL 5.6.21
- Backdrop 1.0.5

I have successfully installed D7 and D8 in different languages on this server.

I have also installed Backdrop 1.0.5 in English, and then added/imported/exported other languages with no problems so far. So it must be something related to the installer.

Renaming the _.po_ file (e.g. from **backdrop-1.0.5.de.po** to **de.po**) didn't work either.
### Side note to improve UX

The installer specifies **files/translations** as the correct path for translations. It would be a good idea to have this folder created by default with its proper _README_ file inside (see below).

Also **profiles/minimal/translations** and **profiles/standard/translations** are still present, but not needed by Backdrop any more.

I have relocated those folders in [This commit](https://github.com/pablo-romero/backdrop/commit/9b084894ff5df62eb49234374347b8b075164d49). Should I send a PR?

There is also a link in the first installer screen pointing to drupal.org, where the instructions are different: _sites/default/files/translations_ for D8 and _profiles/X/translations_ for D7.
This can be quite confusing for new users. I would either remove that link or provide a different one to backdropcms.org docs.

**Comment by quicksketch** [comment]
Hi @pablo-romero! Thanks so much for filing this bug report. Our multilingual functionality should match that of Drupal 7 when installing. Although we did inherit a few early Drupal 8 changes around multilingual, so it's possible that we have an undocumented change.

From reading the installer code, specifically the [`install_find_translation_files()`](https://api.backdropcms.org/api/backdrop/core!includes!install.core.inc/function/install_find_translation_files/1) function, it looks like the .po files must have the file name:

`install.[langcode].po`

So a name like `install.de.po` should pick up the translation for installation.

**Comment by quicksketch** [comment]
Moving this into a documentation task. It probably still qualifies as a bug in core because we do indeed link to Drupal.org for information about installing in other languages. We don't yet have matching documentation for Backdrop (nor a translation server).

I found the change was indeed made in early Drupal 8, in this issue: [Consolidate .po file import to one directory](https://www.drupal.org/node/1260586).

So for starters, what we need here is:

- A new documentation page for installing in different languages on backdropcms.org.
- A modification to core to update the link in the installer.

> I have relocated those folders in This commit. Should I send a PR?

Backdrop doesn't include a "files" directory in the Git repository because this directory is usually ignored entirely in Git. If we put a file in it (even a README) then that could cause trouble for developers and end-users alike. It would be good to simply delete these README files though. Could you file a PR for that?

**Comment by pablo-romero** [comment]
Thanks for the info @quicksketch, renaming the file to *install.(langcode).po* worked fine for file detection.
Now I get this error:

*Fatal error: Call to undefined function language_save() in backdrop/core/includes/install.core.inc on line 1507*

I'll take a deeper look into it later on and let you know what I find out.

I sent [PR #793](https://github.com/backdrop/backdrop/pull/793) to remove those READMEs.

**Comment by quicksketch** [comment]
READMEs removed in https://github.com/backdrop/backdrop/pull/799. Thanks @pablo-romero!

Let's continue here to make sure we get the docs updated. Fixing language_save() should be a separate issue.

**Comment by pablo-romero** [comment]
Sorry about the bad PR, the good one is [#799](https://github.com/backdrop/backdrop/pull/799).

**Comment by quicksketch** [comment]
No problem, I got it!

**Comment by olafgrabienski** [comment]
Using .po translation files from d.org without having to rename them is now possible, see https://github.com/backdrop/backdrop-issues/issues/2345, and we have created a new documentation page about installing Backdrop in different languages, see https://github.com/backdrop-ops/backdropcms.org/issues/523.

I think we can close this issue now.
