### ISSUE TITLE
Choosing "Unformatted" for number field causes PHP Notice.

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#830]
The _element_ array is not defined. PR coming…

**Comment by quicksketch** [comment]
Thanks!

PR at https://github.com/backdrop/backdrop/pull/800. In the future, could you cross-link the PR and the issue specifically? The most effective way is to use a message like `Fixes [url]` in the PR description, then when I merge it, GitHub will automatically close the associated issue.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/800. Thanks again @jdanthinne!
