### ISSUE TITLE
What's the new way for creating Views plugins?

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#831]
I'm currently trying to convert Views Load More module from D7, and as it seems that no other Views compatible module has been ported yet, I'm stuck with a little problem.
Previously, the module .info file was adding two files with the files[] array: views_load_more.views.inc (with a hook to _hook_views_plugins_), and views_plugin_pager_load_more.inc (with a class extending _views_plugin_pager_full_).
Now that this files[] array is not needed anymore, how can I make the plugin available in Views? _hook_autoload_info_?

**Comment by jdanthinne** [comment]
Ok, I've used *module_load_include* for the hook, and *hook_autoload_info* for the class. Seems to work.

**Comment by quicksketch** [comment]
>  Now that this files[] array is not needed anymore, how can I make the plugin available in Views? hook_autoload_info?

You got it! Change notice with more information is here: https://api.backdropcms.org/node/26859
