### ISSUE TITLE
hook_block_info_alter() not called

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#833]
Cant find a backdrop_alter function in core either.

**Comment by quicksketch** [comment]
You're correct, we're missing this hook. We should add it into `layout_get_block_info()` for consistency with Drupal 7. It shouldn't be very difficult from the looks of things.

D7 API for reference: https://api.drupal.org/api/drupal/modules!block!block.api.php/function/hook_block_info_alter/7

Oddly we already include the documentation (as you probably noticed) in layout.api.php, so this is documented but not working.

> Cant find a backdrop_alter function in core either.

It's in /core/includes/module.inc, line 973

**Comment by quicksketch** [comment]
Let's try to get this corrected for the next bugfix release in 1.0.6.

**Comment by quicksketch** [comment]
Filed a PR at https://github.com/backdrop/backdrop/pull/803 that should solve this problem, but we need to update the tests to ensure this is going to work properly in the future. When we did the block to layout conversion we removed the existing tests (but not the block_test.module) that check the functionality of the block list.

**Comment by quicksketch** [comment]
PR updated with new tests. Updated documentation in `layout.api.php`. The tests uncovered another bug (yay!) that `hook_block_view_MODULE_DELTA_alter()` was not working for block deltas that contained a hyphen.

**Comment by quicksketch** [comment]
Merged in the PR. Thanks again @docwilmot!
