### ISSUE TITLE
Incorrect URL when trying to run cron from outside the site.

### ISSUE THREAD

**Issue by CaffeinatedJim** [backdrop/backdrop-issues#834]
Setting up a cron job on the server to run Backdrop Cron.  The instructions on /admin/config/system/cron say:

> To run cron from outside the site, go to 
> http://example.com/cron.php?cron_key=KEY

So I enter this command in my server's Cron jobs:

`curl http://example.com/cron.php?cron_key=KEY`

I get a 301 Moved Permanently error when it runs.  I visit the URL, the redirect works in the browser, but not in the cron job.

The correct url is actually:

> curl http://example.com/core/cron.php?cron_key=KEY

I will attach a patch that fixes this in /core/modules/system/system.admin.inc (Line 1473).

Should the redirect also be removed from line 115 of the .htaccess?  Or are there other forces at play that need that there?

**Comment by quicksketch** [comment]
> Should the redirect also be removed from line 115 of the .htaccess? Or are there other forces at play that need that there?

Let's leave that in place, for users or scripts that are going to cron.php directly. I still visit /update.php and /install.php all the time and let the redirect take me to the right place.

Thanks for the PR! Merged in.
