### ISSUE TITLE
Document `theme file` and `theme path` for views plugins.

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#836]
@bserem posted [this issue about a non-functioning views module](https://github.com/backdrop-ops/contrib/issues/70) so I thought I'd look into it. The views style plugin wasnt being recognized.
I've discovered that 
1. the plugin is never recocgnized unless the 'path' is added to `hook_views_api()` as in `'path' => backdrop_get_path('module', 'salvattore'),`
2. but then after you flush caches views throws up an error `WARNING: INCLUDE_ONCE(C:\WAMP\WWW\BACKDROP\BACKDROP/MODULES/SALVATTORE/TEMPLATES/SALVATTORE.VIEWS.INC): FAILED TO OPEN STREAM: NO SUCH FILE OR DIRECTORY IN C:\WAMP\WWW\BACKDROP\BACKDROP\CORE\INCLUDES\THEME.INC ON LINE 571`
3. the error goes away on page refresh on the views edit page (it persists on the view display page)
4. the only thing that prevents this is putting the salvattore.views.inc file in a 'templates' folder (and update this in `hook_views_api()`).

Any thoughts?

**Comment by quicksketch** [comment]
Hm, maybe there's something that is defaulting to "templates" for the Views directory? It shouldn't be doing this, but perhaps this would force it to be correct:

```
/**
* Implements hook_views_api()
*/
function salvattore_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'salvattore'),
    'template path' => backdrop_get_path('module', 'salvattore'),
  );
}
```

My guess from this report is that "path" and "template path" are not getting their default values set when they are omitted.

**Comment by docwilmot** [comment]
Yep, I had added `'template path'` as well to see if it would eliminate the problem but it didnt. But its strange that other modules have their views.inc files declared in hook_views_api() as being in other directories but dont give this issue. Maybe its a combination of having a template file?
I will upload the project to my GitHub this evening so you can see everything in context.

**Comment by docwilmot** [comment]
Solved by chief developer, Sir Google, specifically [this comment](https://www.drupal.org/node/2170193#comment-8400563) on Drupal. Adding `'theme path' => backdrop_get_path('module', 'salvattore'),` to `hook_views_plugins()` in `salvattore.views.inc` does the trick. 
Curiously `theme path` is not mentioned as a valid return value in [the API site docs for `hook_views_plugins()`](https://api.backdropcms.org/api/backdrop/core%21modules%21views%21views.api.php/function/hook_views_plugins/1)

**Comment by quicksketch** [comment]
Arg, *theme path*? Our docs are copied directly from D7 Views, so I'm guessing this wasn't documented in either place.

Sounds like we have a couple things to fix here:

- Document "theme path" in `hook_views_plugins()`
- Provide a default "theme path"(?) or figure out what the default theme path is and include that in the docs.

**Comment by bserem** [comment]
I am a bit confused, because the D7 version of the module works fine (and I'm stress testing it lately on a dev site).

Anyway, it is good that this got fixed. @docwilmot  you have a reply at https://github.com/bserem/salvattore/issues/1

**Comment by docwilmot** [comment]
I'm not suggesting that this is THE fix; just that those two small changes 
- 'path' added to hook_views_api(), and 
- adding 'theme path' => backdrop_get_path('module', 'salvattore'), to hook_views_plugins()

makes it work. 
As to WHY it works, I have no clue.

**Comment by klonos** [comment]
Noticing the mixed back and forthslashes in the error message makes me want to shamelessly promote #265 again.

**Comment by jenlampton** [comment]
I just noticed something similar for views style plugins specifically. Views expects a `whatever.theme.inc` to be in the same directory as the template files, and for most views modules in Drupal-land that directory was named `theme`.

In Backdrop, we expect the `whatever.theme.inc` file to live in the root of the module (so front-end devs can spot it easily) but we also want all template files to be nicely organized into a `templates` directory.

The views plugin assumes the former, and asks for a single `theme path` that is the answer to both questions:
1) where are my theme / preprocess functions defined? `[theme path] . [theme file]`
2) where are my templates? `[theme path] . [template file]`

**Comment by quicksketch** [comment]
Thanks for the PR @jenlampton. Could you clarify it further?
```
 + *     - theme file: Name of the file containing theme or preprocess functions.
+ *     - theme path: Location of the theme file and template files needed.
```

The description for theme path is ambiguous. Is this an absolute path from the Backdrop root? Or within the module?

**Comment by jenlampton** [comment]
done!

**Comment by jenlampton** [comment]
Also, see related: https://github.com/backdrop/backdrop-issues/issues/1468

**Comment by quicksketch** [comment]
Merged into 1.x and 1.2.x thanks!
