### ISSUE TITLE
Clean URL's page has link to Drupal.org

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#837]
Setting up backdrop again on my new vagrant setup and my clean URL's are broken (sad trombone), but this bug is that we're pointing to `http://drupal.org/node/15365` on `admin/config/search/clean-urls`

**Comment by serundeputy** [comment]
hi @wesruv ; I think this is a dupe of: https://github.com/backdrop/backdrop-issues/issues/793

**Comment by wesruv** [comment]
Sure is.

**Comment by wesruv** [comment]
Next time I'll search before I make the bug, d'oh!

**Comment by serundeputy** [comment]
haha; better safe than sorry; easy enough to close out!
