### ISSUE TITLE
Restore Date, Time, and Datetime MySQL support to core

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#838]
We're having some issues porting Date module to Backdrop because Backdrop apparently doesn't support native "datetime" SQL columns. Support for "date", "time", and "datetime" column types was removed in Drupal 7 core in https://www.drupal.org/node/866340, which caused a lot of frustration for contrib developers that needed to use these types. Date module previously restored this capability to core, but in Backdrop, there's absolutely no reason why we shouldn't support these column types directly. Unlike D7, we *only* support MySQL, so having MySQL-specific columns is not a problem for us.

@jdanthinne filed a PR for restoring datetime support in https://github.com/backdrop/backdrop/pull/804, but I've closed it so that we can provide more comprehensive support to include date and time in addition to just datetime.

The full rollback patch from Drupal 7 is available at https://www.drupal.org/node/866340#comment-3320878, it'd be great to get this ported to Backdrop and include the additional tests there.

Solving this issue would in turn solve https://github.com/backdrop-contrib/date/issues/1 and https://github.com/backdrop-ops/contrib/issues/76

**Comment by jromine** [comment]
Some original Drupal work on this was in https://www.drupal.org/node/200953

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/805. Thanks @jdanthinne for his work on this!

We re-categorized this as a bug in the PR due to this preventing Date module from supporting the same types it did in Drupal 7, so this should be in our next bugfix release 1.0.6.
