### ISSUE TITLE
Responsive clash on admin/appearance/settings/bartik

### ISSUE THREAD

**Issue by Drupaldise** [backdrop/backdrop-issues#839]
Hi guys,
I found a small bug in the default theme bartik.
When I resize my browser window to minimum the color picker is over the color input fields.
![bartik settings backdrop-cms local 2015-04-01 10-46-16](https://cloud.githubusercontent.com/assets/2930705/6937624/ee79b878-d85c-11e4-8fd1-f99df5fbb717.jpg)

**Comment by quicksketch** [comment]
Hi @Drupaldise! Thanks for the heads-up. Not all UIs are entirely mobile compatible (e.g. the Views interface), but it's a good idea to start tracking the areas we can correct like this one.

I also doubt the color picker works well with touch inputs, but I haven't tested it.

**Comment by Drupaldise** [comment]
Hi, the color picker works well on iPhone 6 but you can not set the color for the fields under the "color wheel" as you can see in my screenshot. Maybe it is not so difficult to change the position of the color picker. 
Should I try to fix the problem and write a patch?

BTW. Are there any guidlines to report Issues?

**Comment by quicksketch** [comment]
>  Should I try to fix the problem and write a patch?

Sure! That would be great! I would recommend putting a media query in color.admin.css if necessary, or just trying to layout the page in a way where they wouldn't overlap in the first place by using floats instead of absolute positioning.

> BTW. Are there any guidlines to report Issues? 

We haven't yet stipulated any requirements around issues, we're mostly just happy to get them at this point. Pull requests can be a bit more complicated, we have a documentation page for them at https://backdropcms.org/develop/pull-requests.

**Comment by quicksketch** [comment]
Thanks for the PR @Drupaldise! I posted some feedback. We just need to take into account RTL languages: https://github.com/backdrop/backdrop/pull/806/files#r27774142

**Comment by quicksketch** [comment]
Thanks this looks great! I'll test this out locally and see if I find any issues.

**Comment by quicksketch** [comment]
Works great, thanks @Drupaldise! It looks like Farbtastic doesn't yet officially support touch events :frown: but it has a PR at https://github.com/mattfarina/farbtastic/pull/20.

When Farbtastic is updated, it'd be great to get the new version merged into Backdrop.

This fixes the overlap problem, thanks so much and welcome to Backdrop. :smile:
