### ISSUE TITLE
Wrong result from system_get_date_formats

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#840]
When trying system_get_date_formats('medium') I get a strange result with loss of first characters, see screenshot:

![backdrop_mediumsystemdates](https://cloud.githubusercontent.com/assets/10559274/6939631/7f7ea87a-d866-11e4-9a3a-e9564e92e354.jpg)

**Comment by quicksketch** [comment]
I don't see this on a clean install, but my guess is that something saved configuration incorrectly and resulted in unexpected data in the `system.date.json` file. Could you pull the contents of that config file out of your active config and post as a Gist at https://gist.github.com? Then link to it from here and we can see if anything unusual is happening in there.

When characters are missing like this, it's usually because PHP was treating the strings as arrays somewhere along the way, and doing an operation like `unset($string[0])` will remove the first character from the string.

**Comment by Graham-72** [comment]
I have posted the Gist here https://gist.github.com/Graham-72/07215e4393f9af2582b5

Question - if/when the Date module adds date formats, should it add to this config file or should it have its own separate one?

**Comment by quicksketch** [comment]
> I have posted the Gist here https://gist.github.com/Graham-72/07215e4393f9af2582b5

Hm, nothing looks unusual there at first glance. I'd hoped there'd be something unusual with the list of formats, like a numeric array instead of an object of properties. Everything looks fine though.

> Question - if/when the Date module adds date formats, should it add to this config file or should it have its own separate one?

If date is adding date formats, I think it should add them to this same config file, but not directly using config(). Use [system_date_format_save()](https://api.backdropcms.org/api/backdrop/core!modules!system!system.module/function/system_date_format_save/1) during hook_install() if you need to add new date formats. This handles clearing any applicable caches for you.

Let's do some additional checking... do you get the same output when visiting `/devel/php` and inputting:
```php
dsm(system_get_date_formats('medium'));
```

Perhaps it not the function itself that is the problem but the context from which it is getting called.

Or... perhaps it's a PHP version issue. What version are you running?

**Comment by Graham-72** [comment]
> Let's do some additional checking... do you get the same output when visiting /devel/php and inputting:

> dsm(system_get_date_formats('medium'));

This gets it right - no loss of characters.
I am running PHP 5.5.22

**Comment by quicksketch** [comment]
Could you link to the location in date.module that is calling this function? Perhaps more context will help me see what's wrong. You should be able to link directly to line numbers within a file here on GitHub.

**Comment by Graham-72** [comment]
> If date is adding date formats, I think it should add them to this same config file, but not directly using config(). Use system_date_format_save() during hook_install() if you need to add new date formats. This handles clearing any applicable caches for you.

It looks to me as though Date allows for different variations of, for example, 'medium' formats. How do these get identified in this config file? Is it sufficient for the word 'medium' to be part of the label?

**Comment by quicksketch** [comment]
> It looks to me as though Date allows for different variations of, for example, 'medium' formats.

Is this for internationalization purposes or for some other reason? Locale module now handles per-locale versions of date formats. ... However upon further inspection I can't see how these locale-specific date formats are actually utilized. This make take a little searching.

Anyway, it seems like a "medium" format should always be the same within a locale, what other variations would be necessary?

**Comment by Graham-72** [comment]
The location is
https://github.com/backdrop-contrib/date/blob/1.x-2.x/date_admin.inc#L312
though I am having to find alternative code to produce the required display and am trying this
``` 
// Example input formats 
    $format_types = system_get_date_types('medium');
	dpm($format_types);
    if (!empty($format_types)) {
      foreach ($format_types as $type => $type_info) {
	    if (isset($type_info['label'])){
          $options[$type] = date_format_date(date_example_date(),'custom', $type_info['pattern']);
	    }
      }
    }
```

I am trying to produce the drop-down of Date Entry Options as appears in Drupal - shown here for 'short' date formats
![drupaldateentryoptions](https://cloud.githubusercontent.com/assets/10559274/6961028/791583d2-d91f-11e4-9118-b61d67c48cce.jpg)
In time I will figure out where these come from.:smile:

**Comment by Graham-72** [comment]
My idea for code - above - is very wrong so please ignore it.
I have reached the stage of thinking that before more progress can be made, something has to be done about the various date formats in Date because in Drupal /devel/php using this
```
dsm(system_get_date_formats('medium'));
```
produces this, with 14 optional patterns for a 'medium' date format.
![drupaldates1](https://cloud.githubusercontent.com/assets/10559274/6966948/3314df7e-d954-11e4-9da3-f50d64a06cbf.jpg)
Each of these patterns has a 'type' value of medium, as here
![drupaldates2](https://cloud.githubusercontent.com/assets/10559274/6966983/6faa8ec0-d954-11e4-9270-fee8c4daad6d.jpg)

I have found these options useful when using Drupal, particularly when creating Views, so it would be nice to have them in Backdrop at some stage.

**Comment by Graham-72** [comment]
Oh, and my original reason for creating this issue was wrong. I found that the problem was caused by an error in my code. Sincere apologies, and thanks for your help.

**Comment by Graham-72** [comment]
Please could we now remove the label 'bug report' from this issue and close it. Then open a new issue about date formats because, if possible, I would like to see an extra element 'type' in the system.date config array, also maybe we need 'langcode'.

**Comment by klonos** [comment]
...closing and removing tag. I'll leave the issue opening for you @Graham-72 :smile:

**Comment by quicksketch** [comment]
> Please could we now remove the label 'bug report' from this issue and close it.

You should be able to do this yourself. I resent an invitation to your e-mail that, once accepted, will allow you to add/remove labels. Thanks @Graham-72 for opening this issue and looking forward to the next one. I think you're right that there are some issues with our date formats, so your insights here (as well as the work on the Date port) are highly appreciated.

**Comment by Graham-72** [comment]
@quicksketch - I am now thinking some more about Date's use of all these extra date formats and wondering whether they are really necessary. When I have clarified my thinking, should I float my ideas in a new issue here or perhaps on reddit? I'm not sure where you would prefer that sort of discussion.

**Comment by quicksketch** [comment]
I'm curious about the value of multiple formats with the same name as well. Other than l10n, I don't think it makes a lot of sense to have different "medium" formats. Let's discuss in the issue queue rather than Reddit, which should be for more casual conversation I think.
