### ISSUE TITLE
[UX] Remove the word "Default" from the date format label

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#844]
On date formats, the default labels contain the word "Default". Not only is this word unnecessary but it mucks up the Token UI a bit.  Additionally, people will likely change the defaults, but not change the labels, creating confusion later when the state is actually overridden but the label still says "default".

Let's remove the word "Default" so the default names are as follows:
* Long Date
* Medium Date
* Short Date

**Comment by pablo-romero** [comment]
Sent PR #809

**Comment by quicksketch** [comment]
Thanks @pablo-romero!
