### ISSUE TITLE
Missing entry in views_autoload_info

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#847]
Please could an entry be added to core/modules/views/views.module function views_autoload_info() for the class views_handler_field_broken

```
'views_handler_field_broken' => 'handlers/views_handler_field.inc',
```

**Comment by quicksketch** [comment]
Thanks @Graham-72! Looks like another missing handler. If you get a chance to make a PR I'll merge it in.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop/backdrop/pull/811. Thanks @Graham-72!
