### ISSUE TITLE
Views basic settings (/admin/structure/views/settings): "Statistics location" label always shown.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#851]
The label is always shown even when the "Show information and statistics about the view during live preview" checkbox is not checked:

![views_basic_settings-stats_location_label_always_visible](https://cloud.githubusercontent.com/assets/2423362/6997392/0f1437fe-dbfd-11e4-847c-e5ecc229bba9.png)

**Comment by quicksketch** [comment]
This is fixed in dev versions. See https://github.com/backdrop/backdrop-issues/issues/711.
