### ISSUE TITLE
Single sidebar width in 3/3/4 columns Layout

### ISSUE THREAD

**Issue by pablo-romero** [backdrop/backdrop-issues#853]
When using 3/3/4 columns Layout with only one sidebar, blocks are displayed at 50% of screen size in the intermediate media query (from 560 to 850px).
We should specify to display the half-width only when both sidebars are used.

### Steps to reproduce/test

1. In Layout settings, choose **3/3/4 columns**.
2. Add some blocks to only one of the sidebars, and save.
3. Browse to your site and resize the window to any size between 560 and 850px.

### Screenshot (second sidebar)

![one-sidebar](https://cloud.githubusercontent.com/assets/1876841/7004261/1880a4a0-dc69-11e4-904e-d4692231b254.png)

**Comment by pablo-romero** [comment]
Sent PR #812

Tests look fine on my side now.

**Comment by quicksketch** [comment]
Thanks! Great idea! PR is at https://github.com/backdrop/backdrop/pull/812 (it wasn't linked up properly).

This needs a manual testing to confirm the change, but the code looks great to me! I'll give it a try soon.

**Comment by quicksketch** [comment]
Thanks @pablo-romero! Merged in the PR finally.
