### ISSUE TITLE
Update the version of Farbtastic that ships with core once it supports touch events.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#858]
Just a reminder issue assigned to 1.x-future for what @quicksketch said in https://github.com/backdrop/backdrop-issues/issues/839#issuecomment-91418677

> It looks like Farbtastic doesn't yet officially support touch events :frown: but it has a PR at https://github.com/mattfarina/farbtastic/pull/20.
> 
> When Farbtastic is updated, it'd be great to get the new version merged into Backdrop.

**Comment by quicksketch** [comment]
:+1:

**Comment by klonos** [comment]
Seems that this won't happen any time soon 😞:

<img width="1001" alt="Screen Shot 2019-03-24 at 9 22 30 pm" src="https://user-images.githubusercontent.com/2423362/54878070-4d84bf00-4e7b-11e9-9bf6-0d7ef7ef9a37.png">

...lets close this issue then.
