### ISSUE TITLE
Fatal error when editing language strings

### ISSUE THREAD

**Issue by pablo-romero** [backdrop/backdrop-issues#861]
Steps to reproduce:

1. Install Backdrop in English
2. Add a custom language
3. Either import a .po file or visit some admin pages to bring a few translation sources.
4. Go to interface translation page and edit any untranslated string.
5. Click Save, and get the error below.

```
Fatal error: Call to undefined function locale_string_is_safe() in core/modules/locale/locale.pages.inc on line 355
```

**Comment by quicksketch** [comment]
Thanks @pablo-romero! We've solved this already in dev, it should be in 1.0.6. See https://github.com/backdrop/backdrop/pull/791.

In the mean time you can just add this line to the top of `locale_translate_edit_form_validate()`, line 354 in `locale.pages.inc`:

```php
  require_once BACKDROP_ROOT . '/core/includes/locale.inc';
```
