### ISSUE TITLE
Add entity_var_export and entity_var_json_export in core.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#864]
This was mentioned in https://github.com/backdrop-ops/contrib/issues/71#issuecomment-76859926

>>entity_var_export
>>entity_var_json_export

>We can use ```backdrop_json()``` and ```backdrop_var_export()``` here, although I think that we'll probably use config instead of whatever variable exporting Rules used previously.

**Comment by quicksketch** [comment]
Hi @klonos, thanks for keeping tabs on making issues when I'm just mentioning things in passing (and didn't make an issue). But in this case, I think I was suggesting that we *wouldn't* need to add these functions, because we already have acceptable alternatives in core.

**Comment by klonos** [comment]
Good thing issues can be closed then ;)

**Comment by quicksketch** [comment]
If we *do* need these for any reason, let's reopen and state the reasons. Thanks!
