### ISSUE TITLE
Make it possible to directly upload an image file from the camera of mobile devices.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#869]
Some android/iPhone apps allow uploading/attaching files directly from the camera of mobile devices. So the current workflow is something along the lines of:

1. Start creating content that allows or requires image(s) uploaded.
2. Switch to camera and take photo(s).
3. Switch back to browser.
4. Upload file through the "upload" button of the image field.
5. Browse local files in order to find the photo(s) from step 2 above.
...

We could instead have it like so:

1. Start creating content that allows or requires image(s) uploaded.
2. Hit the "capture photo" button.
3. The camera interface fires up, take photo (the photo is automagically added to the field.
...

I found this related article about it while trying to build the features of the Auditor app in a website: [Add images to Drupal from your mobile device](http://cafuego.net/2013/04/26/add-images-drupal-your-mobile-device). It turns out that all that's required is to add the HTML5 ```accept``` attribute with ```image/*;capture=camera``` value to the image upload widget:

```<input type="file" accept="image/*" id="capture" capture="camera">```

[cafuego](https://www.drupal.org/u/cafuego) (the author of the above linked article) has also created a Drupal project (sandbox actually) that does this: [Image Mobile Camera](https://www.drupal.org/sandbox/cafuego/1980210)

Nice little helper feature for core (since we want to support as much HTML5 as we can and all)?

More articles/sources around the net about it:

[HTML5 HTML Media Capture](http://mobilehtml5.org/ts/?id=23)
[HTML Media Capture](http://www.w3.org/TR/html-media-capture/)
[Capturing Audio & Video in HTML5](http://www.html5rocks.com/en/tutorials/getusermedia/intro/)

**Comment by klonos** [comment]
...BTW, I would love to see this added to 1.1.0, but I'll leave it up to you guys to decide with regards to the roadmap.

**Comment by biolithic** [comment]
I have done this html5 bit in a couple Phonegap apps using an API such as
Flickr or AWS as a store.  I should look at how to use a Drupal managed
file system to store them

There are definitely logistics on how to limit/preview/etc as the thought
is good but the implementation and care for this can go very wrong.

**Comment by klonos** [comment]
I would love to see this implemented in core as soon as possible or at least [Image Mobile Camera](https://www.drupal.org/sandbox/cafuego/1980210) ported in Backdrop contrib. I have a project coming up where there is a need for logged in users to capture photos of things they need to sell and upload them directly to the website as listings.

**Comment by sutibun** [comment]
klonos on fire.

**Comment by klonos** [comment]
#1380 is related.

**Comment by quicksketch** [comment]
Hi @klonos, I was looking into this and it looks like HTML5 now provides extension validation in addition to camera uploads via the new `accept` attribute. We may be able to remove our custom extension validation entirely, as it does the same thing. I'll look into it, but we'll probably need some extensive browser testing.

**Comment by quicksketch** [comment]
Wow, interesting. The history of extension support in HTML5 originates in this FileField issue from Drupal 6! https://www.drupal.org/node/939102

> For future reference the HTML5 spec has just been changed to allow both extensions AND mime types in the "accept" attribute. http://html5.org/tools/web-apps-tracker?from=7056&to=7057
> This was added to the spec because of this issue on D.O. :) see #31 above.

Awesome! Wow things sure can come full circle (6 years later). So the only affected browser at the time was Chrome 8, and probably up until version ~20 or so (circa 2012). However, with Chrome auto-updating and now on version 49, I don't think it will be an issue. Again, we'll need to do some browser checking, but it looks like we may be able to remove our custom JS for extension checking.

**Comment by quicksketch** [comment]
Hm, looks like extension support is still very poor however: http://caniuse.com/#feat=input-file-accept

So we should probably stick to the liberal mime types for now, and continue to use our custom extension checking until browser support improves.

**Comment by klonos** [comment]
> The history of extension support in HTML5 originates in this FileField issue from Drupal 6!

:astonished: 

> Hm, looks like extension support is still very poor however: http://caniuse.com/#feat=input-file-accept

Was looking at that very same thing and was about to say the same. You beat me to it.

**Comment by klonos** [comment]
...the stats in caniuse look a bit more promisin if you switch to "Usage relative" though.

**Comment by quicksketch** [comment]
It also looks like browser detection for this attribute is not currently possible, from the work the Modernizr team has done: https://github.com/Modernizr/Modernizr/pull/1110

So extension support is likely out the window. I think the best bet we have is adding 'image/*,capture=camera' to image fields *only* (not file fields) because it's too unpredictable an attribute, unless `*/*` is supported. We don't want to accidentally prevent any file uploading on unsupported browsers.

**Comment by quicksketch** [comment]
Filed a PR at https://github.com/backdrop/backdrop/pull/1303.

It looks like `*/*` *is* supported! So we can say, "allow all MIME types, plus the camera please", then use our existing extension validation. To be sensible, we'll only allow the camera option if "jpg" images are allowed, as that is what all cameras provide. My PR also includes some changes to switch from using `Backdrop.settings.file` variable to `data-*` attributes for a more-modern approach to file elements.

**Comment by quicksketch** [comment]
@klonos Would you be up for browser testing? Now that we have these *fancy sandboxes*(!!)?

And don't forget we also have Browser Stack accounts you can use. *wink wink* I can send you the passwords via email (info@backdropcms.org) or Gitter (https://gitter.im/backdrop/backdrop-issues).

**Comment by klonos** [comment]
Thanx @quicksketch, @jenlampton has already forwarded those credentials to me. Will test with other browsers as well, but a quick test I gave it using Chrome on my Android phone worked like a charm! :clap:

**Comment by klonos** [comment]
Can we have an option to limit the source to only the camera for image fields? Something like a "Accept images only from the camera" checkbox?

Use case: I need to create a website where people make audits of places and they need to take shots on the spot. As it is now, clicking the field presents various options including the local file system. I want this to behave in a manner where clicking on the field does not present any options at all (save one click) and opens the camera straight away.

**Comment by quicksketch** [comment]
> Something like a "Accept images only from the camera" checkbox?

It seems out of the ordinary that most users would want such an option. On machines without a camera (or browsers that don't support the `accept` attribute), it would just disable the field entirely. I know that may be what you want in your situation, but it'd be pretty unusual otherwise.

I'm also not even sure mobile browsers have the ability to restrict to the camera alone, it would probably differ from phone to phone depending on the camera application in use.

My personal take is that an option is unnecessary. It's a use-case that should probably be covered by a contrib or custom module rather than core.

**Comment by klonos** [comment]
Fair enough. Will test in various browsers once I get some time.

Not being able to code modules yet though, if it is like a 10-liner or so and doesn't take much time, could then somebody provide the code to do this with a custom module? Thanx in advance.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/1303 for 1.4.0. Thanks @klonos for making this great suggestion!

**Comment by klonos** [comment]
OMG! Thank you @quicksketch! Feels like I have been waiting for this since ...well Drupal :smiling_imp:

**Comment by klonos** [comment]
...shame I never found the time to test browser support though. No worries, I intent to use this A LOT, so I'll be "kicking the tires" :smile: Thanx again :+1:
