### ISSUE TITLE
[UX] Add some explanation for Add Date Time Format in Regional and Language admin

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#873]
I think it would help the user to understand the admin page at admin/config/regional/date-time/formats/add if there was an introductory sentence such as "If you are creating an additional date format then give it a suitable name as a label, then specify its format using a string of standard PHP date and time codes".
I have successfully tried this code in core/modules/system/system.admin.inc at line 2318

```
  $form['description'] = array(
    '#markup' => empty($format) ? '<p>'.t('If you are creating an additional 
date format then give it a suitable name as a label, then specify its format 
using a string of standard PHP date and time codes').'</p>' : '');
```

---
PR by @Graham-72: https://github.com/backdrop/backdrop/pull/1682

**Comment by quicksketch** [comment]
Hi @Graham-72! I took a look at this page and I see what you mean. The two field "Label" and "Format" fields can be a bit intimidating. Adding help text may help, but the example you provided doesn't seem to say very much. As a user, I already know I need to provide a label and format from the fields there. The help text doesn't give me anything new.

Perhaps instead we could improve the UX by either providing a description for the "Label" field, or providing HTML5 "placeholder" values as examples.

```php
$form['label']['#placeholder'] = t('My date format');
$form['format']['#placeholder'] = t('e.g. F j Y');
```

**Comment by klonos** [comment]
I personally like the idea of placeholders, but have there been any user testing reports previously to support the assumption that they help and not confuse instead? I mean, I know that the suggestions have a faded out color, but do all users know the difference or do they assume that the fields are already prefilled in for them?

**Comment by quicksketch** [comment]
> but have there been any user testing reports previously to support the assumption that they help and not confuse instead?

There are lots of articles on how placeholders can be misused (e.g. instead of a field label), but I haven't found any studies on the topic of using them properly (as an example).

Adding a description to the "Label" field might provide just as much value and be less controversial. The best uses of placeholders are when it's clear that the placeholder is an example (e.g. `you@example.com` for an e-mail field). I'm not sure my attempts are clear enough to be recognized as examples and not defaults.

**Comment by klonos** [comment]
Then lets just go ahead with it and revert in case of complaints about it. :wink:

**Comment by Graham-72** [comment]
I hope you will include something explanatory. When I first came across this page I wondered what sort of label I was expected to provide. Of course, now that I have used the form and experienced what it does, I have no such problem. As you say, it is a bit intimidating, both for the first time user and one coming back after many months. I would like the placeholders as well.

**Comment by docwilmot** [comment]
I think if the placeholders actually say "example" (or "e.g." as in this case) that should be sufficient. I would also an explanation as well though, especially with a link to somewhere explaining what those formats - F j y - actually are. Like php.net or we write our own article in the API site.

**Comment by klonos** [comment]
:+1: for a link to https://php.net/manual/en/function.date.php#refsect1-function.date-parameters

**Comment by jenlampton** [comment]
I also second the vote for placeholders, and a link to php.net (I still use that page all the time!)

**Comment by Graham-72** [comment]
I have produced a PR at https://github.com/backdrop/backdrop/pull/1682 which takes account of the comments above and produces a result which answers my concerns that gave rise to the issue.

**Comment by klonos** [comment]
Thanx @Graham-72 👍 

I've added a link to the PR in the issue summary as we do. Don't forget the "needs review" tag when filing PRs 😉

**Comment by klonos** [comment]
...PR looks good and the help text and field placeholders make it so much better 👍

**Comment by klonos** [comment]
Tiny, but very useful UX improvement. Lets get it in the next 1.5.x, shall we?

**Comment by jenlampton** [comment]
found one teeny tiny nit (a missing comma) in the PR, but after that's fixed this is RTBC from me too :) Love the idea of getting it in for 1.5.3 or 1.6.0 if not.

**Comment by jenlampton** [comment]
Thanks @Graham-72 !

**Comment by Graham-72** [comment]
@klonos 
>I've added a link to the PR in the issue summary as we do. Don't forget the "needs review" tag when filing PRs

Are these parts of the PR procedure documented somewhere? I get confused at times 😟 . Your blog https://backdropcms.org/news/creating-pull-requests-against-core-easy-noob-way is very helpful but there seem to be extra things to do.

**Comment by klonos** [comment]
It's more like common practice so that it's easier for reviewers to locate the link to the most current PR, especially in long issues. If time permits perhaps I'll update the blog post or add a "Making pull requests" document under the official user guide. In the meantime, I don't mind helping with such small trivial tasks that I consider part of helping with triaging the issue queue (similarly to adding proper labels, assignees and milestones). It's just that I also explain/document what I do so that perhaps eventually it get through as a habit to people 😄 

PS: I think we had a task someplace to automate the addition of such links to the first comment of issues once a PR is created. A task for our GitHub automation guru @Gormartsen ...for when he finds time to do it 😉

**Comment by Graham-72** [comment]
> It's more like common practice.

Yes, clearly it is a good idea to have this link, though I am not sure whether it should be added before the PR has passed a review? And thank you for the work you do in helping add these touches. But I do think we need an up-to-date document that helps us beginners get things right without needing additional prompting. Perhaps we can have this in 2017?

**Comment by quicksketch** [comment]
Thanks everyone for the PR and reviews (especially @Graham-72 for taking the lead on this). I've merged https://github.com/backdrop/backdrop/pull/1682 into 1.x and 1.5.x. Thanks!
