### ISSUE TITLE
New admin theme missing table border and hover

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#874]
Followup to https://github.com/backdrop/backdrop-issues/issues/740#issuecomment-94219453 and part of overall meta for new admin theme in https://github.com/backdrop/backdrop-issues/issues/736.

> The tables seem to be missing upper/left/right borders (for example the modules page and the status report page) while the [Style guide](https://backdrop-ops.github.io/styleguide/#table) shows that there should be there.

> Also, in the Style guide there is a hover-over effect (personally don't like the yellowish color, but still) that is not implemented with this patch.

Reference the Styleguide for implementation style: https://backdrop-ops.github.io/styleguide/#table

**Comment by wesruv** [comment]
@klonos @quicksketch 
In the styleguide there is no top, right or left border? Should we add one? With the background color between the body and table, striping and th bg color, I think it's fine.

**Comment by wesruv** [comment]
Pull request for hover color, let me know if the border should be added: https://github.com/backdrop/backdrop/pull/850

**Comment by quicksketch** [comment]
> In the styleguide there is no top, right or left border? Should we add one?

There is one, it's just *very* subtle:

![table](https://cloud.githubusercontent.com/assets/100206/7341791/7b0adca4-ec5d-11e4-93c4-b312fdc5f3d0.png)
![tr](https://cloud.githubusercontent.com/assets/100206/7341801/982fc01a-ec5d-11e4-832f-2b61f77f54be.png)

**Comment by quicksketch** [comment]
Oh I see what you're saying, there really is not border on the top. But the right and left borders are on the `<tr>` tag as shown in the screenshot. I think we're fine without the top border with the thead there.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop-issues/issues/874, which adds the hover color. We still need the borders on the left/right/bottom.

**Comment by wesruv** [comment]
Oooooooh, weird. I suppose that's so it isn on the th tags.... Sly boots...

I'll get it added.

**Comment by wesruv** [comment]
@quicksketch https://github.com/backdrop/backdrop/pull/855

**Comment by quicksketch** [comment]
Thanks @wesruv! I think we're done here.
