### ISSUE TITLE
Account for new/larger font in the installer

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#879]
The new larger Open Sans font in Seven creates some issues with the installer:

The labels now wrap on desktop:
![installer-seven](https://cloud.githubusercontent.com/assets/100206/7218094/e103d534-e60d-11e4-9e85-98d04fcae25b.png)

Text is cut off mobile:
![installer-seven-mobile](https://cloud.githubusercontent.com/assets/100206/7218095/e43c91be-e60d-11e4-96b3-576e7dc5ec2f.png)

**Comment by quicksketch** [comment]
PR for this at https://github.com/backdrop/backdrop/pull/833. Thanks @wesruv! It looks great.

**Comment by wesruv** [comment]
Hah, you're quick! No prob :)

**Comment by quicksketch** [comment]
:smile: Merged into 1.x-new-style. Thanks!
