### ISSUE TITLE
Status Message Layout/Spacing under different circumstances Related to #739

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#880]
From @klonos 
Vertically space 1 liners
![status_message_not_vertically_aligned_when_one_line](https://cloud.githubusercontent.com/assets/2423362/7219036/ba58cbd8-e6d0-11e4-9da9-59db64f4b271.png)

This seems to work, but does it look good in Bartik/other themes
![status_message_ok_when_more_then_one_line](https://cloud.githubusercontent.com/assets/2423362/7219042/ce31347e-e6d0-11e4-9861-f1319cdd4ba0.png)

Also need to test with `<p>`, `<ul>`, and various status messages.

**Comment by wesruv** [comment]
I think I got this tackled: https://github.com/backdrop/backdrop/pull/862

@klonos, love to hear your feedback if you have some time.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/862. Thanks @wesruv!
