### ISSUE TITLE
Allow Emoji (Switch MySQL encoding from utf8 to utf8mb4)

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#884]
The most [recent release of WordPress](https://wordpress.org/news/2015/04/powell/) switched the default encoding from utf8 to utf8mb4 in MySQL. This allows MySQL to store additional characters that it otherwise will crop and mangle. utf8mb4 enables MySQL to store the full range of UTF-8 characters, including Emoji characters.

Apparently utf8mb4 has [been available since MySQL 5.5](https://mzsanford.wordpress.com/2010/12/28/mysql-and-unicode/). When creating new tables, we should detect if this functionality is available and use it by default. We should also provide an upgrade hook to update all existing tables.

---

Latest PR: https://github.com/backdrop/backdrop/pull/1491

**Comment by serundeputy** [comment]
PR: https://github.com/backdrop/backdrop/pull/856
This allows for a new install to go through with utf8mb4, but `someone`™ will have to think about an `update_hook`.

In particular points brought up here: https://mathiasbynens.be/notes/mysql-utf8mb4 . Especially point 4.

~Geoff

**Comment by quicksketch** [comment]
Thanks @serundeputy, that's a great reference! Several gotchas in there I wouldn't have thought of myself.

**Comment by serundeputy** [comment]
here is the patch link in case anybody else gets an interest or bandwidth towards this issue:
https://patch-diff.githubusercontent.com/raw/backdrop/backdrop/pull/856.patch

**Comment by serundeputy** [comment]
I stumbled across this on d.o today; don't know if it will help or not, but it might: https://www.drupal.org/node/1314214

**Comment by MrHaroldA** [comment]
I ran into this issue too and had to change the data column for the webform_submission table into a blob.

**Comment by serundeputy** [comment]
Drupal has added this support in 7.50; here is the issue https://www.drupal.org/node/2488180

That could provide us a roadmap.

**Comment by quicksketch** [comment]
I read over all the current data we have on Drupal and WordPress's approaches to this problem:

- Main Drupal issue: https://www.drupal.org/node/2488180 (and follow-up that is needed https://www.drupal.org/node/2764221)
- Drupal documentation on enabling long UTF-8 support: https://www.drupal.org/node/2754539
- WordPress's upgrade path: https://make.wordpress.org/core/2015/04/02/the-utf8mb4-upgrade/
- Drupal drush command for upgrading existing websites: https://www.drupal.org/project/utf8mb4_convert

Some interesting differences in approach:

- WordPress *shortens* existing indexes to fit within the normal index lengths within InnoDB. Drupal instead requires the MySQL option `innodb_large_prefix=true` to be set. The WordPress approach requires contributed modules (plugins) to manage their own SQL indexes to shorten them and to manually upgrade each table. Drupal's approach works on all tables but works on a smaller number of sites (`These settings are available as of MySQL 5.5.14, and are defaults in MySQL 5.7.7 and up.`)
- WordPress automatically updates existing sites if it is possible to support them. Drupal has a separate Drush command (https://www.drupal.org/project/utf8mb4_convert).
- WordPress detects if the database is possible to support and uses the feature if it is available. Drupal also detects if the database is supported, but doesn't use it unless manually specified in settings.php as part of the database connection array.

I like some things from both approaches. I'd probably compromise on the following:

- Backdrop should use Drupal's approach of supporting this feature only if MySQL is configured to allow it (`innodb_large_prefix=true`). This makes it so we don't need to adjust any existing indexes, which would be difficult or incomplete with the number of contrib modules we have. The Drupal approach requires no effort on behalf of existing modules and we can just apply the same encoding change to every table.
- Backdrop should provide a built-in upgrade path, via update.php probably, but possibly also in the UI from the status report page. The drush command should be a nice to have, not a requirement.
- To simplify configuration and make this automatic, Backdrop should automatically use this feature by default, without any extra configuration in settings.php. If needed, it could be explicitly disabled or enabled via settings.php using the long connection array format.

**Comment by quicksketch** [comment]
Gosh, I also just found that Drupal 8 won't install at all on some shared hosts like Media Temple's Grid System: https://www.drupal.org/node/2568351

Drupal 7 is much more lenient in that it supports both, but on D8 you have to use a hosting platform that not only has the required MySQL version but also new enough PHP drivers to connect to PHP. It's possible to meet both the MySQL and PHP version requirements but not meet the driver requirements that connect the two.

Anyway, another thing to look out for...

**Comment by quicksketch** [comment]
I made a new PR at https://github.com/backdrop/backdrop/pull/1491. It does the following:

- Ports nearly all the Drupal 7.50 approach to multibyte UTF8 handling. I removed `utf8mb4IsConfigurable()` method since we only support MySQL, so this is always true.
- The D7 patch is "opt-in" and manual, you must specify the character encoding in settings.php *prior to running the installer*. I modified this approach to be automatically detected and enabled by default. You can disable the detection by specifying all your connection info before running the installer.
- Because Backdrop uses a short-string connection line instead (or as an alternative to) the long array syntax, I made a new line in settings.php for `$database_charset`. It now looks like this out of the box:
```
$database = 'mysql://user:pass@localhost/database_name';
$database_prefix = '';
$database_charset = 'utf8';
```

The `$database_charset` can be changed to `utf8mb4` to enable the longer format.
- Like the D7 patch, the status report page indicates every combination of enabled/disabled and supported/unsupported support for UTF8 MB4. We need a new documentation on MB4 support. I think we should probably just update the existing page at https://api.backdropcms.org/database-configuration so it's all in one place.
- The follow-up patch from https://www.drupal.org/node/2764221 is also included.

This doesn't account for an upgrade path yet. I'll be making a follow-up commit to add that to the PR.

The unfortunate thing I found is that we can't provide an automatic upgrade for existing sites. Unlike WordPress's approach which does version checking (and shortens columns down to 191 characters), the Drupal/Backdrop approach here must connect to the database first to determine if it supports the long indexes ability. As such, we have to record if this is supported somewhere and then use that setting *before* connecting to the database.

Like the Drupal approach, the most reasonable place for this is in settings.php. However, I think the increased visibility and simplicity of a single variable should help ease upgrades. Having the tool built-in to assist people with the upgrade will also help. Essentially it will have the same useful walk-through as we used in the Transliteration upgrade when that was moved into core.

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/1491 is now ready for review.

I added a UI-based upgrade path, built on top of the Drush tool at https://www.drupal.org/project/utf8mb4_convert. This entire class (adjusted slightly for our purposes) has been moved into core under `core/includes/database/charset_converter.inc`. Although we do not use all the methods available, if we want to port the Drush command or integrate it directly into our Drush extension it should be trivial.

The UI upgrade only deals with a single database. For sites with master/slave, the replication should handle updating the slaves. Multiple databases are not covered, but that could be handled in the Drush version or a custom script if needed.

Here's the upgrade in action:

![2016-08-20 14 43 42 619](https://cloud.githubusercontent.com/assets/100206/17834278/821acaf2-66ed-11e6-979e-f1d98d8972c5.gif)

**Comment by klonos** [comment]
Amazing!! 👍 Couple of questions:

- If leaving the site online has the risk of causing data loss during the conversion, shouldn't we simply "force" maintenance mode during the conversion instead of exposing an option through the checkbox?

- I see in the screencast that you first needed to manually edit settings.php. Do we need that specific step or can it be offered as an option through the UI?

**Comment by quicksketch** [comment]
> If leaving the site online has the risk of causing data loss during the conversion, shouldn't we simply "force" maintenance mode during the conversion instead of exposing an option through the checkbox?

Yeah good idea and simplification. Let's just turn it on all the time for the upgrade.

> I see in the screencast that you first needed to manually edit settings.php. Do we need that specific step or can it be offered as an option through the UI?

This really can be a dangerous operation (though lots of Drupal sites have used the underlying class already). Some edge-cases we may not have encountered yet might really bork your site. Personally, I'd feel better about this requirement so that it would be more likely that users would take the time to make a backup. That is probably naive. :stuck_out_tongue: 

Manually editing settings.php does have the benefit of consistency. Some sites will be able to auto-modify settings.php and others couldn't, depending on file permissions. It makes documenting the upgrade slightly messier. Our tools for rewriting settings.php also only work well if the lines are pre-existing that are replaced. Otherwise the line just gets appended to the bottom of the file, which would work but could be confusing as to why it's not near the rest of the database settings.

**Comment by klonos** [comment]
> Yeah good idea and simplification. Let's just turn it on all the time for the upgrade.

But do warn the admin this is going to happen once they hit the "Go" button. There might be cases where this takes a long time and having the website in maintenance mode might need scheduling.

Fair enough about the explanation of the settings.php file manual edit, but you know I always go for point-and-click through the UI. Was just thinking like a non-tech-savvy site builder that might not have access to editing the config files directly (or simply is scared to touch them). The UX in that case is not that great as you can imagine.

**Comment by quicksketch** [comment]
Great idea, I expanded the help text and also implemented a recent fix from the contrib project [regarding special column names](https://www.drupal.org/node/2791695).

I also added a note about how long the process usually takes. Here's the new message:
```diff
-  $form['help']['#markup'] .= '<p>' . t('This operation is irreversible! Make sure that you have backed up your database before continuing.') . '</p>';
+  $form['help']['#markup'] .= '<p>' . t('This operation is irreversible! Make sure that you have backed up your database before continuing. Your site will be put into maintenance mode during the upgrade. A site with hundreds of pieces of content should take a few minutes. Sites with thousands of pieces of content may take @minutes minutes or more.', array('@minutes' => 10)) . '</p>';
 ```

**Comment by serundeputy** [comment]
Yay!  This works for me ... I left some very very minor feedback on the `PR`.

![screen shot 2016-09-08 at 7 49 49 pm](https://cloud.githubusercontent.com/assets/6763671/18370806/f3a7a2f2-75fd-11e6-8428-8e0a20ecd6fd.png)


need these lines in `my.cnf` (https://www.drupal.org/node/2754539)

```
[mysqld]
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=true
```

* restart mysql (`sudo /usr/local/Cellar/mysql55/5.5.44/support-files/mysql.server restart`) in my case.
* Add `$database_charset = 'utf8mb4';` string in `settings.local.php` in my case.
* Then the upgrade path went very smoothe!

RBTC from me!  Great work @quicksketch 🐙 😄

**Comment by quicksketch** [comment]
Great, as a reminder we still need to update the documentation page for database configuration, and a change record would be appropriate as well.

Thanks for the review @serundeputy! I'll try to get these remaining items knocked out today.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/1491 into 1.x for 1.5.0.

**Comment by quicksketch** [comment]
Documentation now available at https://api.backdropcms.org/database-configuration#utf8mb4.

**Comment by klonos** [comment]
Did we make a change record for this after all? Do we need to?
