### ISSUE TITLE
Form styles and admin tables

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#888]
When reviewing test sites that use the current 1.x-new-style I see three possible issues at present:
- excessive row spacing (perhaps a matter of opinion)
- black up and down arrows not showing well in heading of sortable column
- hidden text in drop-down selectors
These are minor issues but it would be nice to get them looking good straight away.

Here are some screenshots:
A. 'Content' page as it is without further change -
![admin content - graham s backdropcms trial 2015-04-26 11-24-38](https://cloud.githubusercontent.com/assets/10559274/7337907/425129f2-ec32-11e4-92ce-2143235ad3cd.png)

B. 'Content' page in D7 -
![find content - catherine larner 2015-04-26 11-25-04](https://cloud.githubusercontent.com/assets/10559274/7337860/dcfe5eb8-ec30-11e4-97d5-8012be41bc2c.png)

C. 'Content' page as it might be - 
![admin content - graham s backdropcms trial 2015-04-26 12-14-37](https://cloud.githubusercontent.com/assets/10559274/7337880/925aa640-ec31-11e4-9e93-102c5bdb8898.png)

D. 'Modules' page as it is now - 
![modules - backdrop starter 2015-04-26 16-12-58](https://cloud.githubusercontent.com/assets/10559274/7337886/d1534e56-ec31-11e4-8086-75afaf1b66d1.png)

E. 'Module' page as it might be -
![modules - graham s backdropcms trial 2015-04-26 16-09-57](https://cloud.githubusercontent.com/assets/10559274/7337892/ee19878a-ec31-11e4-8a8b-724d5fae3bb8.png)

C was achieved by replacing the dark grey images for the up and down arrows with white ones, though perhaps a light grey would be better, and also reducing the top and bottom padding for the table cells.

E was achieved by increasing the width of the 'operations' column and setting the width of the buttons to a minimum so that drop-downs are the same width as plain buttons. Also, the top and bottom padding of the table cells is reduced as for C.

**Comment by klonos** [comment]
> - excessive row spacing (perhaps a matter of opinion)

I'm with you here. Way too much vertical space gone to waste and more scrolling required. Not good.

:+1: for the white (same as the text) sorting arrows in table column headers.

As for the drop-buttons, I've recently expressed my opinion in https://github.com/backdrop/backdrop-issues/issues/785#issuecomment-96122931:

>I understand that the styleguide dictates using UPPERCASE for our buttons, but the dropbutton innovation came to existence in order to save us horizontal space. By using UPPERCASE we increase the width of the "Operations" column though. Regression?

**Comment by Graham-72** [comment]
I have submitted PRs https://github.com/backdrop/backdrop/pull/853 and https://github.com/backdrop/backdrop/pull/854 to set widths in the operations column. See also https://github.com/backdrop/backdrop-issues/issues/785.

**Comment by Graham-72** [comment]
I have submitted a PR https://github.com/backdrop/backdrop/pull/858 as my suggestion for reducing the row spacing.

**Comment by Graham-72** [comment]
@quicksketch I have got into difficulties trying to create a PR that provides new versions of the arrow files using an off-white so that they show up on the near-black background so, whilst I sort myself out, here are my suggestions for replacing arrow-asc.png and arrow-desc.png. I have made them slightly grey rather than white so that they are noticeable on a white background.
![arrow-asc](https://cloud.githubusercontent.com/assets/10559274/7384919/c81d98ce-ee33-11e4-8126-bba584624c3b.png)
![arrow-desc](https://cloud.githubusercontent.com/assets/10559274/7384926/de0cb25a-ee33-11e4-85c4-75430af23099.png)

I hope this maybe of some help.

**Comment by jenlampton** [comment]
Is there any chance we can change these buttons to draw the arrows with CSS now instead of using images?  That would allow us the ability to change the colors easily (both now, and in the future) and it's what we've been doing elsewhere in core.  Here's the code we used for the arrows in dropbuttons:
```
.dropbutton-arrow {
  border-bottom-color: transparent;
  border-left-color: transparent;
  border-right-color: transparent;
  border-style: solid;
  border-width: 0.3333em 0.3333em 0;
  display: block;
  height: 0;
  line-height: 0;
  position: absolute;
  right: 40%; /* 0.6667em; */ /* LTR */
  top: 50%;
  margin-top: -0.1666em;
  width: 0;
  overflow: hidden;
}
[dir="rtl"] .dropbutton-arrow {
  left: 0.6667em;
  right: auto;
}
```

**Comment by Graham-72** [comment]
It looks to me as though this would require a change to core/includes/tablesort.inc in order to do this with styles rather than images. Would this be acceptable or would it cause other issues?

**Comment by quicksketch** [comment]
I've merged in the change to reduce table row padding (https://github.com/backdrop/backdrop/pull/858).

The PRs for setting table row widths were no longer necessary after we merged in https://github.com/backdrop/backdrop/pull/864.

So what remains here is updating the tablesort icons. I think we should leave tablesort.inc alone and replace these styles specifically in Seven. Short-term, we can simply override `theme_tablesort_indicator()` in Seven's template.php to use the new white indicators instead of the black ones.

**Comment by Graham-72** [comment]
I have found another thing in an admin form that puzzled me at first, that is the use of the configure icon when managing the display setting for an image. At first sight I didn't realsie that this was what I should click to configure the style for the image, perhaps because it is so far to the right of the text. Is this something to be changed?
![article - www revivalwoodbridge org uk 2015-05-08 09-17-46](https://cloud.githubusercontent.com/assets/10559274/7533094/430946b2-f566-11e4-8b04-35f1ede85397.png)

And when you point at it the colour change doesn't really stand out against the row's yellow background.
![articleb](https://cloud.githubusercontent.com/assets/10559274/7533109/6e0e2404-f566-11e4-9197-12efb720a7a0.jpg)

**Comment by quicksketch** [comment]
Thanks @Graham-72, great observations. It looks like we should:

- Align the gear left(?) so that it's next to the summary column.
- Definitely set the background color on that gear so that it's more visible when highlighted or within a gray row. Maybe just a white background (to match our dropbuttons) would be appropriate.

**Comment by Graham-72** [comment]
@quicksketch I have added PR #891 to change the alignment of the gear and text - had to use align right for the text and align left for the button to get them close together. Also included a version of the gear with a white background, though maybe the whole icon needs a white interior background. I hope this may be of some help.

**Comment by Graham-72** [comment]
I have now added replacement pale grey arrow images for themes/seven/images to the PR https://github.com/backdrop/backdrop/pull/892. I believe they are only used in the one situation which is with a black background.

**Comment by quicksketch** [comment]
Awesome! I'm going to check it out now.

**Comment by quicksketch** [comment]
Hi @Graham-72! Thanks for working on this. With the first PR at https://github.com/backdrop/backdrop/pull/891, I don't think the gear png icon actually needs to be updated, it's just the button background color that needs to be changed from gray to white. Unfortunately, there's not a good selector on that button to target. Maybe we need to modify the markup to give it a good class so we can target it more easily.

**Comment by quicksketch** [comment]
The gray arrows look great though. I've merged in your commit from https://github.com/backdrop/backdrop/pull/892.

**Comment by Graham-72** [comment]
@quicksketch 
>Maybe we need to modify the markup to give it a good class so we can target it more easily.

Shall I leave this for you to do, or shall I see if I can propose something?

**Comment by quicksketch** [comment]
> Shall I leave this for you to do, or shall I see if I can propose something?

This would be great to get done before release. @wesruv is here at the DrupalCon sprint, I'll see if he's available to take on this.

**Comment by wesruv** [comment]
@quicksketch I'll have some time in a few :smile:

**Comment by wesruv** [comment]
@quicksketch Ready to go: https://github.com/backdrop/backdrop/pull/895

**Comment by wesruv** [comment]
Here's what we did with that button. After some live-crits we're getting rid of the cog in favor of descriptive text.
![new-configure-button](https://cloud.githubusercontent.com/assets/5607236/7663151/aec4dcc2-fb33-11e4-8577-d507f77ef679.png)

**Comment by quicksketch** [comment]
Thanks @wesruv! Passed tests and looks great. Merged in https://github.com/backdrop/backdrop/pull/895.

**Comment by quicksketch** [comment]
I think we're totally done here. If we have any remaining tasks, let's open a new issue to make the flow of conversation easier to follow.
