### ISSUE TITLE
Create a new default theme, as a subtheme of Bartik

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#889]
See https://github.com/backdrop/backdrop-issues/issues/842
A subtheme would allow us to:
- have a more modern-looking default theme
- keep Bartik for easier upgrade
- minimize the work needed to achieve this by making (mainly) only minor CSS color adjustments

Branch at https://github.com/docwilmot/backdrop/tree/bartik-flat does just this. The default tabs are also removed (this is the only non-color change) because they dont look good.

Screenshots follow of the theme color options. Opinions welcome.

![blue drop](https://cloud.githubusercontent.com/assets/1042283/7338499/4f90c736-ec13-11e4-85d6-68bb729951a1.PNG)
![giant goldfish](https://cloud.githubusercontent.com/assets/1042283/7338501/4f923b70-ec13-11e4-8dcd-f76b58f36626.PNG)
![icier](https://cloud.githubusercontent.com/assets/1042283/7338500/4f915a16-ec13-11e4-800f-400be4ebdfdd.PNG)
![mocha](https://cloud.githubusercontent.com/assets/1042283/7338502/4f946e2c-ec13-11e4-8f5d-e8d295c4c49e.PNG)
![black drop](https://cloud.githubusercontent.com/assets/1042283/7338503/4f94a568-ec13-11e4-9c1a-5f71f7eaef86.PNG)

**Comment by quicksketch** [comment]
I don't think we should add another theme to core that looks almost identical to the current theme in core. From an end-users point of view, these appear as totally separate options in the UI, which would lend the expectation that they would actually be different in some substantial manner. With the only significant difference being the removal of tabs (we can remove the gradient in the standard install, see https://github.com/backdrop/backdrop-issues/issues/842#issuecomment-96516353), I don't think this justifies being a new option in core.

**Comment by jenlampton** [comment]
I agree, if we are going to add a new theme to core I'd rather it be a fancy modern-looking theme, one that people would actually use on production sites, maybe something bootstrappy?  What's the hotness these days?  I think we should move away from themes that are similar to Bartik. If we want something similar, let's just alter Bartik (but maybe not too much during the 1.x release cycle ;)

**Comment by docwilmot** [comment]
Yep, agreed this got a bit out of hand from the original "change color to black" proposal.
