### ISSUE TITLE
[UX] Fix up spacing and hierarchy of Layout page

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#891]
@Graham-72 called out some goofiness on this page, going to do a quick cleanup.
![layout-edit-page-1-5x-new-style](https://cloud.githubusercontent.com/assets/5607236/7266775/31562dfe-e87d-11e4-90dc-07665fb013f9.png)

**Comment by Graham-72** [comment]
@wesruv I'm glad you are looking at this. I have been trying to tidy up dropbutton widths on other pages and have just been thinking about this one. I am trying adding the following in core/misc/dropbutton.css

#system-modules .dropbutton-wrapper div,
#layout-edit .dropbutton-multiple div,
#layout-list .dropbutton-wrapper div {
  min-width: 140px;
}

It is doing what I would like to do to the appearance, plus some other changes on this page, but I will now leave this one to you.

**Comment by wesruv** [comment]
@Graham-72 I took a crack at cleaning up the interface a bit, was there anything specific you see that I didn't address?
![draft-of-layout-page](https://cloud.githubusercontent.com/assets/5607236/7341981/dc47ba8c-ec71-11e4-9d71-29f6b3b60cac.png)

Here's the PR for what I've got:
https://github.com/backdrop/backdrop/pull/851

**Comment by Graham-72** [comment]
@wesruv - I think this is now looking very good, thank you. I wonder what happens when you have a block with a longer title in the sidebar. Does it the dropbutton drop below the title like this
![edit -default layout- - graham s backdropcms trial 2015-04-27 06-42-41](https://cloud.githubusercontent.com/assets/10559274/7342420/b875db9a-ecab-11e4-9177-9a1fa705b88a.png)
I guess I should apply your patch to my local test system and see for myself.

**Comment by docwilmot** [comment]
@wesruv @Graham-72 while you're at it see this comment from @jenlampton https://github.com/backdrop/backdrop-issues/issues/373#issue-46063420 (point number 4). I think that  makes a lot of sense and would clean up the interface even better. Slightly different than a quick cleanup, but would be nice.

**Comment by docwilmot** [comment]
For reference:
![layout](https://cloud.githubusercontent.com/assets/397895/4674583/1d53b092-557f-11e4-9f6f-65af59e06535.png)

**Comment by wesruv** [comment]
Oh snap! Thanks for linking to that ticket @docwilmot, I wasn't aware it existed! That looks A LOT better. I'll see if I can get that implemented.

**Comment by wesruv** [comment]
Here's the latest and greatest @docwilmot and @Graham-72, let me know what you think.
![draft-of-layout-page](https://cloud.githubusercontent.com/assets/5607236/7421697/e1faa788-ef54-11e4-9dcd-7e21d39f1573.png)

**Comment by jenlampton** [comment]
@wesruv omg <3 <3 it looks beautiful!!!!!!!!

**Comment by Graham-72** [comment]
Very good! Thanks.

**Comment by docwilmot** [comment]
Very nice.

**Comment by quicksketch** [comment]
We had some good conversation in https://github.com/backdrop/backdrop/issues/851, but that PR is now closed after I merged 1.x-new-style into 1.x and deleted the old branch. We need a new PR directly against 1.x if this is ready.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/882.
