### ISSUE TITLE
Forms dropbutton on Views Admin List

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#892]
This dropbutton has been made smaller for the views ui edit form (rightly so) but should be normal size in the views list.
![views - backdrop starter 2015-04-28 06-08-42](https://cloud.githubusercontent.com/assets/10559274/7363193/6de97686-ed6e-11e4-82bd-c12aeb90e1f8.png)

**Comment by Graham-72** [comment]
I have submitted a PR https://github.com/backdrop/backdrop/pull/857 to target the style just for the edit form.

**Comment by quicksketch** [comment]
Thanks @Graham-72! This has bothered me for a while!

**Comment by jenlampton** [comment]
This issue will be fixed with the drop-button style cleanup in https://github.com/backdrop/backdrop-issues/issues/785
