### ISSUE TITLE
[UX] Adjust (token) dialogs to work better on small viewports

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#894]
Dialogs could use some improvements for small viewports.  Can we adjust .ui-dialog to get a larger width on smaller screen sizes? 50% seems unreasonably narrow on a (vertical) tablet or any smartphone.

**Comment by quicksketch** [comment]
I'll work on correcting this.

**Comment by quicksketch** [comment]
This problem is specifically relevant for dialogs that do not auto-resize or auto-recenter, like the token dialog. Other dialogs (like the Layout or Views dialogs) already display and resize fine on smaller screens.
