### ISSUE TITLE
Allow non-administrative users to view unpublished nodes

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#897]
Out of the box, the only way someone can view unpublished content is if they have "Administer nodes".  This is way too much access to grant someone who just needs to be able to see something.

Let's add some permissions that allow people access to view unpublished content. 
- view own unpublished content
- view all unpublished content

Drupal module that solves this problem: [view_unpublished](https://www.drupal.org/project/view_unpublished)

Also related: https://github.com/backdrop/backdrop-issues/issues/815

---

Latest PR: https://github.com/backdrop/backdrop/issues/1328

**Comment by Graham-72** [comment]
I would like to have this feature.

In order to provide this I have just made a clone of the view 'Admin Content' and changed the filter, though this has also enabled me to restrict the types of content for this new view. So what would be really good is a separate permission 'View unpublished content' for each type of node.

**Comment by klonos** [comment]
Also related: #1333

**Comment by jenlampton** [comment]
I'm still using this patch on backdropcms.org.  Applies to latest version :)

**Comment by jenlampton** [comment]
PR/patch still applied to latest version.

**Comment by gifad** [comment]
I applied PR 1321 above on my dev site.
It works nicely in the context of views, but direct access to node/## still gives a 403 - Access denied.

Am I missing something ?

I noticed that the new  `function node_unpublished_user_permsissions()` is referenced nowhere (at least directly)

**Comment by gifad** [comment]
Submitted PR [#1305](https://github.com/backdrop/backdrop/pull/1305) to actually grant `view any unpublished content` to relevant users, via node/% path.

**Comment by quicksketch** [comment]
Thanks @gifad for updating the PR. It still needs work, as you pointed out `function node_unpublished_user_permsissions()` is not actually used anywhere. It also implies per-type access, which is a bit further than what's being suggested here.

I'd need to brush up on the node access code, but I think by adding new items into `node_access_acquire_grants()` would effectively enable the node access control system on every Backdrop site. We specifically do not use node access control by default because it adds a significant overhead to listing queries anywhere nodes are shown. I think for starters we should *only* allow access on the direct paths, rather than integrating into the node access system which would affect listings like the front page.

**Comment by gifad** [comment]
> the node access system

I've a limited knowledge of drupal/backdrop internals about access, but I believe there are two distincts systems : 
1. based on `hook_node_access()`
2. based on `hook_node_grants()`

I think an eventual "Custom publishing options permissions" module should of course work with `hook_node_access()` !

**Comment by gifad** [comment]
I ported [Custom publishing options](https://github.com/backdrop-contrib/custom_pub), and [implemented permissions](https://github.com/backdrop-contrib/custom_pub/issues/3).
So PR #1305 is now useless to me...
Thoughts ?

**Comment by jenlampton** [comment]
> It also implies per-type access, which is a bit further than what's being suggested here.

There is per-type access in the patch, and it was what I had originally intended. I've updated the top issue to be more clear. A new permission for each node type has been added here, in addition to a "view all unpublished". The view ALL unpublished is likely too permissive for most real-world use cases for this feature.

**Comment by jenlampton** [comment]
I've pushed a new PR that removes the per-type permission for viewing unpublished nodes. I've also removed the functions `node_unpublished_user_permsissions` and `_node_in_array_r` since they were not being used.

In the `view_unpublished` module the original function `view_unpublished_user_perms` was called in an implementation of `hook_query_TAG_alter` as follows:
```php
function view_unpublished_query_node_access_alter(QueryAlterableInterface $query) {
  global $user;

  $is_admin_content_page = (arg(0) == 'admin' && arg(1) == 'content');
  $is_tablesort_query = (get_class($query) == 'TableSort');
  $is_not_admin = ($user->uid !== "1");
  if ($is_admin_content_page && $is_tablesort_query && $is_not_admin) {
    $perms = view_unpublished_user_perms();

    // Fetch the nids of the user's own unpublished nodes if he is allowed to
    // view those. This is the same query as in node_admin_nodes(), we need it
    // to remove the condition which restricts the unpublished nodes to the
    // user's own ones.
    $own_unpublished_nids = array();
    if (user_access('view own unpublished content')) {
      $own_unpublished_nids = db_select('node', 'n')
        ->fields('n', array('nid'))
        ->condition('uid', $user->uid)
        ->condition('status', 0)
        ->execute()
        ->fetchCol();
    }

    // "any" in this case means at least 1 view unpublished permission is set to
    // TRUE.
    if ($perms['any']) {
      $conditions =& $query->conditions();

      // Configuration of a condition in $conditions to only list published
      // nodes.
      $published_condition = array(
        'field' => 'n.status',
        'value' => 1,
        'operator' => '=',
      );
      // Configuration of the condition which adds the users own unpublished
      // nodes to the result set as set in node_admin_nodes().
      $own_unpublished_condition = array(
        '#conjunction' => 'OR',
        0 => $published_condition,
        1 => array(
          'field' => 'n.nid',
          'value' => $own_unpublished_nids,
          'operator' => 'IN',
        ),
      );
      // Has the user a filter set to only list published nodes?
      $filter_published_only = !empty($_SESSION['node_overview_filter'])
        && in_array(array('status', 'status-1'), $_SESSION['node_overview_filter']);

      foreach ($conditions as $key => $condition) {
        // Remove core conditions
        if (!empty($condition['field'])
          && (
            (is_object($condition['field']) && $condition['field']->conditions() == $own_unpublished_condition)
            || (!is_object($condition['field']) && $condition == $published_condition && !$filter_published_only)
          )
        ) {
          unset($conditions[$key]);
        }
      }
      // If "view any unpublished content" (aka $perms['full']) is set, then
      // leave the rest of the query as-is and return all unpublished content.
      // Otherwise, add a WHERE/OR to the query that specifies content type, as
      // dictated by the user's permissions, e.g. "view any unpublished page
      // content"
      if (!$perms['full']) {
        $container = db_or();

        $container->condition('n.status', 1);

        $cond = db_and()
          ->condition('n.type', array_keys(array_filter($perms['content_type'])), 'IN')
          ->condition('n.status', 0, '=');
        $container->condition($cond);

        if (!empty($own_unpublished_nids)) {
          $container->condition('n.nid', $own_unpublished_nids, 'IN');
        }

        $query->condition($container);
      }
    }
  }
}
```

I left this part out of the patch because in node module we use `_node_query_node_access_alter` instead.

**Comment by klonos** [comment]
> The view ALL unpublished is likely too permissive for most real-world use cases...

Yeah, I think that this would be reserved for users that have content management permissions and that have the final say in workflows where content is submitted for review before publishing. In my head, these people would have high enough permissions for many other things too, so I can't think of common use cases where their permissions would have to be more fine-grained to a per-content type level. Although I'm sure there could be such real-life use cases out there.

**Comment by jenlampton** [comment]
I just tested the patch and I'm not sure we need that query tag alter magic. I think that bit was important for the type-specific unpublished nodes, but now that's it's only all or own I'm not sure we need it at all.  Would love some more testing, but I'm going to push this PR to backdropcms.org and take it for a spin there for a while.

**Comment by jenlampton** [comment]
PR still applies to latest backdrop.

**Comment by klonos** [comment]
I confirm that this patch works as expected. I'm using it on my own website without any issues.

**Comment by jenlampton** [comment]
@klnos can you change the status to RTBC if you can confirm this is working?

**Comment by klonos** [comment]
...sorry for the delay. Trying to catch up with the queues.

**Comment by quicksketch** [comment]
I reviewed the PR at https://github.com/backdrop/backdrop/pull/1328, it looks pretty good and seems like it would work, but there's some cruft in there that I don't think we need.

I'll point out again what I said above:

> I think by adding new items into `node_access_acquire_grants()` would effectively enable the node access control system on every Backdrop site. We specifically do not use node access control by default because it adds a significant overhead to listing queries anywhere nodes are shown. I think for starters we should only allow access on the direct paths, rather than integrating into the node access system which would affect listings like the front page.

Those additional grants are also likely an API change for existing sites. I'd recommend we separate that out into a different issue if we want it all.

**Comment by jenlampton** [comment]
Okay, I've fixed up the PR as indicated and removed all the grants changes. I added some tests, but then removed them b/c if we're not changing grants, we don't need any more grant tests, right?  Should I add more tests for view all unpublished?

**Comment by quicksketch** [comment]
> Should I add more tests for view all unpublished?

Yes, we need to separately test the new permission from the existing one. No need for new grant tests if we're not changing anything there, just check access to the node page itself.

**Comment by jenlampton** [comment]
Okay, I think I have the code cleaned up how we want it, but there are a lot of failing tests. I'm not sure if the tests need to be updated, or we broke node access. Or some of each!  I could use some more eyes on the tests, if anyone is familiar with node_acces that would be an added bonus.

**Comment by jenlampton** [comment]
Thanks to the keen eyes of @docwilmot, I just pushed a new PR.  We'll see if tests pass...

**Comment by quicksketch** [comment]
What happened to the tests? The current PR no longer contains any tests for the new permission, "view any unpublished content".

**Comment by jenlampton** [comment]
bah. I can't remember if I ever added those... okay added now. And guess what? the tests found something I'd missed!  `Published or admin` views filter hadn't been updated!  thank you tests.  PR now testing.

**Comment by quicksketch** [comment]
New tests look great! Merged https://github.com/backdrop/backdrop/pull/1328 into 1.x for 1.5.0. Thanks @jenlampton!
