### ISSUE TITLE
[UX] Better node-type permissions

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#900]
We have fabulous access control in Backdrop for nodes. I would also like to see a fabulous UI for these permissions, starting with putting them someplace convenient, like the node-type settings form.

Please see my rant at https://github.com/backdrop/backdrop-issues/issues/899 for why we should put things where people expect to find them (as well as in a central location).

Task:
Add a vertical tab to the node-type form where user permissions for this type can be configured.

**Comment by klonos** [comment]
Yes please! If not in a vtab, then perhaps a "Manage permissions" local menu?

**Comment by docwilmot** [comment]
I like this. Makes a lot of sense.

**Comment by jenlampton** [comment]
Not local menus, vertical tab please :)

**Comment by docwilmot** [comment]
Please review approach. Tests to come if satisfactory.
Also advise on what to do for the usual JS suggestions on the VTabs; we can't really list all permissions, nor all roles, since that list could become very long. What should go there? static text? I've no ideas.

**Comment by quicksketch** [comment]
> Also advise on what to do for the usual JS suggestions on the VTabs; we can't really list all permissions, nor all roles, since that list could become very long.

Could we list all roles that have *any* access to that type of content? In my experience, usually if a role has some access they have most or all access. Perhaps we also cap to a certain number of roles (say 2 or 3) and then cut it off. A phrase like `Administrators, Editors, Moderators, and 3 other roles`.

**Comment by quicksketch** [comment]
This PR looks *fantastic*.

![selection_041](https://cloud.githubusercontent.com/assets/100206/12317961/1de83a8c-ba4b-11e5-886c-03b808214092.png)

:heart_eyes:

I found that the responsiveness of this table isn't so great on mobile. But we have similar problems on the full permissions page anyway, so I don't think that should hold up the show here.

I think if we can get the Vertical Tabs summary sorted out along with the minor feedback in https://github.com/backdrop/backdrop/issues/1199, this is ready to go.

If we finish up the Pathauto settings at #899, this will make the node type page a one-stop shop (gasp!) for setting up an entire content type.

**Comment by docwilmot** [comment]
> Could we list all roles that have any access to that type of content? 

I think thats good but its probably going to take me much more time than we have to figure this out (JQuery and I don't like each other much). I'm going to push the last few recommended changes minus the VTab summary in the hope that one JQuery expert can give it a go before deadline.

**Comment by quicksketch** [comment]
Super, thanks @docwilmot! I'll work on the Vertical Tabs bit to finish this up.

**Comment by quicksketch** [comment]
I updated @docwilmot's PR with vertical tabs integration in https://github.com/backdrop/backdrop/pull/1207. This could use another manual testing/review before going in.

**Comment by jenlampton** [comment]
YES!!!  I think the summary on the vertical tab is sufficient as-is, but there is room for improvement there if we want to revisit that later.  I LOVE this change <3

**Comment by quicksketch** [comment]
Super, merged in https://github.com/backdrop/backdrop/pull/1207 to 1.x for 1.3.0. Great job @docwilmot!

**Comment by jenlampton** [comment]
*cartwheels*
