### ISSUE TITLE
[D8] Add Transliteration to Core

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#904]
In https://github.com/backdrop/backdrop-issues/issues/87, we added Pathauto to core, including dependencies on Transliteration module. Instead of depending on the contributed module, we should build this functionality into core.

Transliteration should be integrated into a number of places in core:
- Transliteration of uploaded files (as provided by Transliteration in D7).
- Replacing the "Machine Name" transliteration to improve non-latin auto-conversion.
- Anywhere where we currently do a `preg_replace('/a-zA-Z0-9_/', '', $string)`, transliterating would be more appropriate before cleaning up.
- Replacing URL pattern tokens.

Related d.o issues:
- [Add Transliteration to core](https://www.drupal.org/node/567832)
- [Use Transliteration for machine names](https://www.drupal.org/node/1842718)
- [Improve Transliteration by using the best possible data sources](https://www.drupal.org/node/1823454)

---
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1182

**Comment by quicksketch** [comment]
We don't have time to include this in 1.1.0. For the time being we'll anticipate porting (if it's not done yet) Transliteration module from Drupal 7, then build in Transliteration into core as soon as possible. I've marked this as a 1.2.0 target, but we'll see what happens.

**Comment by pablo-romero** [comment]
Awesome!

@quicksketch: D7 Transliteration was ported by @jdanthinne: https://github.com/backdrop-contrib/transliteration

**Comment by klonos** [comment]
This is part of the #378 meta.

**Comment by jdanthinne** [comment]
I'm on it.

**Comment by klonos** [comment]
As someone that deals with multilingual sites often, it is great to see this moving along! :+1:

**Comment by jdanthinne** [comment]
https://github.com/backdrop/backdrop/pull/1133

**Comment by quicksketch** [comment]
Looking good @jdanthinne! Thrilled to see this coming along.

**Comment by quicksketch** [comment]
Okay I've reviewed @jdanthinne's PR at https://github.com/backdrop/backdrop/pull/1133. It works great at this point. Nice job!!

There are a few issues that need work and/or discussion.

- There are no tests :frowning: :frowning: At the very least we should add a test checking the `machine_name/transliteration` callback's responses and ensure that the problems I ran into in testing don't happen again.
- Should we segment off some functionality back into contrib? In particular, the Transliteration Filter (allowing US-ASCII characters only in filtered_html textareas) and possibly the Retroactive file renaming form (system_transliteration_retroactive()).

The transliteration filter doesn't even seem like a good idea to me. What use-cases are intended that would transliterate long-form text content? The retroactive form is definitely useful if you hadn't transliterated all your files previously but now need to (e.g. upgrading D7 or Backdrop sites). Thoughts?

**Comment by quicksketch** [comment]
I think it'd also be nice to rename `machine_name/transliteration`'s path to `system/transliteration`, as it could be used for more than just machine_name elements.

**Comment by jdanthinne** [comment]
* Changing path: ok for me, seems logical.
* Filter to contrib: ported it because it was there, but I agree, I don't really see the use cases.
* Retroactive renaming to contrib: ok for me as well, that will be a super tiny contrib module :-)
* Tests: I'm not very good at writing test, I must admit. If someone is up to the task…

Waiting for thoughts form big heads (@jenlampton, @klonos, …) before making any changes.

**Comment by quicksketch** [comment]
Besides those changes, we also need to add `'transliteration'` to the list of core modules merged into core in `backdrop_merged_modules()`. That will prevent the contrib version from being enabled on the modules page.

We should also add an update hook to system.install to disable the contrib module, matching what we did for pathauto and token (see system_update_1038()):

```php
  // Remove the entry for the token module in the system table. This will
  // "disable" the module if present.
  db_query("DELETE FROM {system} WHERE name = 'token' AND type = 'module'");
```

**Comment by quicksketch** [comment]
> Retroactive renaming to contrib: ok for me as well, that will be a super tiny contrib module :-)

Okay thinking on this a bit more. Chatting with @jenlampton and @mikemccaffrey we came up with an idea to make it so that we keep the Retroactive Transliteration form, but we de-emphasize it.  Let's change its menu item to be MENU_CALLBACK so it doesn't show up in the Admin Bar, and then link to that page from the File System form's Transliteration section. Something like `If you enable this setting later, you may want to [link]retroactively transliterate existing file names[/link].` to the existing description. That way we won't clutter the admin interface with something so esoteric, but when it's needed it's still there (and positioned where people will find it).

**Comment by jdanthinne** [comment]
>We should also add an update hook to system.install to disable the contrib module, matching what we did for pathauto and token

Doesn't `module_disable(array('transliteration'), FALSE);` already disable the module?

**Comment by quicksketch** [comment]
> Doesn't module_disable(array('transliteration'), FALSE); already disable the module?

Oh! Sorry I forgot there was already an update hook when I wrote that. `module_disable()` does indeed turn off the module, but it leaves an unnecessary entry in the `system` table.

@jdanthinne Do you think you could take another stab at addressing the feedback thus far?

**Comment by jdanthinne** [comment]
@quicksketch Done… Removed from module list, updated path, removed filter, added to merged modules list.

**Comment by quicksketch** [comment]
Excellent... I'll review again tonight and see if I can get some tests together.

**Comment by quicksketch** [comment]
The additional commit looks great! I'm working on tests now.

Have you seen the Drupal issue at [https://www.drupal.org/node/1823454](Verify transliteration data sources and their quality)? I don't think these updated transliterations are in this PR yet. Considering the work that was put into building these sources, it seems like it would be worth it to just grab all the transliteration files from D8 and use those.

**Comment by jdanthinne** [comment]
Done! Transliteration data files updated. I can see there are additional files as well for some languages. I'll check that as well asap.

**Comment by quicksketch** [comment]
I made a lot of cleanup and added tests to code. Made a new PR at https://github.com/backdrop/backdrop/pull/1182.

- Updated the transliteration source files to match those of D8. There seems to be lot more support for Asian character sets in these files.
- Added tests for basic transliteration, path transliteration, file transliteration, machine name transliteration, and bulk transliteration.
- I found that `transliteration_get()` supported `$langcode` properties, but our machine name implementation did not. I rearranged the menu callback to support `$langcode` as well.
- Moved around the AJAX callback code a bit to make it easier to test.
- Minor fixes throughout file.test that I encountered while there.

We'll see if all tests are passing.

**Comment by jdanthinne** [comment]
I've just added languages specific overrides as well… (backport from D8)

**Comment by jdanthinne** [comment]
But you've just closed the initial PR, how can I put this latest addition in your new PR?

**Comment by jdanthinne** [comment]
I was talking about https://github.com/jdanthinne/backdrop/commit/6a49bb41fe794ba57216b75cbddd66adef12c045

**Comment by quicksketch** [comment]
Excellent, thanks @jdanthinne. GitHub is not so great about collaborative pull requests. Only one person can work on a PR at a time. The other person either has to file a new one or make a pull request against the other pull request (to be approved by the first author).

Compared to the Drupal.org approach, a PR is basically a patch that can be updated by its author, but not others.

I'll apply your commit to my branch and push up again. Looks like I've got several failing tests.

**Comment by quicksketch** [comment]
Updated PR at https://github.com/backdrop/backdrop/pull/1182 with the new overrides and hopefully fixed all the tests.

**Comment by quicksketch** [comment]
I've merged in https://github.com/backdrop/backdrop/pull/1182 into 1.x for 1.3.0.

Thanks @jdanthinne!! You totally rocked this issue. This fits in nicely with our UX release for those with non-English sites. Even though it wasn't stated as a specific goal for this release, I'm thrilled to have Transliteration in core for Backdrop 1.3.0!

**Comment by jdanthinne** [comment]
Glad I could help. Living in Europe, multilingual websites are mandatory, so is transliteration. I'm looking forward to see what's next in the full internationalization process. What do you think it will be? Porting i18n? Entity translation?

**Comment by quicksketch** [comment]
> Porting i18n? Entity translation?

I'm not sure about porting i18n module as it is today. We'll want to support an upgrade path, so I'm all for having it as a temporary measure. I think the best thing we could do for multilingual is config translation (#704). Menu item translation is also a high priority item (https://github.com/backdrop/backdrop-issues/issues/225). Though you can get by without either of them today, it would be lovely to have those as in core functionality.

**Comment by klonos** [comment]
> ...Living in Europe, multilingual websites are mandatory, so is transliteration....

Not living in Europe anymore, but i feel you. Thank you for the time and energy put in this. :clap: 

> ...Though you can get by without either of them today, it would be lovely to have those as in core functionality.

:+1:
