### ISSUE TITLE
Typo in field.tokens.inc: "$entity_into" instead of "$entity_info"?

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#907]
Is that a typo?:

https://github.com/backdrop/backdrop/pull/871/files

**Comment by quicksketch** [comment]
Ha! Yes it is. At least the variable is consistent so it's not causing any issues. But let's get it fixed to "info". Thanks!

**Comment by quicksketch** [comment]
PR at https://github.com/backdrop/backdrop/pull/879, we'll let it run tests. What keen eyes you have @klonos! I feel a little foolish "fixing" the bug but not even reading the name of the variable.

**Comment by klonos** [comment]
> What keen eyes you have @klonos!

Yes, I know. [proudly stretches trouser suspenders in a very cocky manner]..

![yes_i_know_suspenders](https://cloud.githubusercontent.com/assets/2423362/7548852/814e783a-f65f-11e4-9290-1af25df81505.jpg)
