### ISSUE TITLE
Why doesnt backdrop_parse_info_file() list "settings" as an allowed key?

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#911]
This isnt urgent, just curious. 

`drupal_parse_info_file()` says the following are the (allowed? usual?) keys, and gives Bartik as an example. But Bartik also has a `settings[color] = true`. Drupal is the same. Should `settings` be in the "information stored in a theme .info file" list as well?

(and this does need some cleanup, as we no longer support "regions"; not sure about "features" either)

```
Information stored in a theme .info file:

name: The real name of the theme for display purposes.
description: Brief description.
screenshot: Path to screenshot relative to the theme's .info file.
engine: Theme engine; typically phptemplate.
base: Name of a base theme, if applicable; e.g., base = zen.
regions: Listed regions; e.g., region[left] = Left sidebar.
features: Features available; e.g., features[] = logo.
stylesheets: Theme stylesheets; e.g., stylesheets[all][] = my-style.css.
scripts: Theme scripts; e.g., scripts[] = my-script.js.

See bartik.info for an example of a theme .info file.
```

**Comment by quicksketch** [comment]
Thanks, you're correct. "settings" should be added and both "regions" and "features" should be removed. Features were consolidated into the new header block. Regions are provided by layouts of course.

**Comment by quicksketch** [comment]
This has been fixed in https://github.com/backdrop/backdrop/issues/964.
