### ISSUE TITLE
[UX] Enable module confirmation should use new "button-primary" class, not "button-danger" class

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#912]
When enabling a module with dependencies, the confirmation form should not use the "danger" class, because there's nothing particularly dangerous about enabling another module.

![enable](https://cloud.githubusercontent.com/assets/100206/7548769/a9870fb8-f5d5-11e4-9dc3-50a256b296c4.png)

**Comment by serundeputy** [comment]
`PR`: https://github.com/backdrop/backdrop/pull/904

**Comment by serundeputy** [comment]
I've added the `class` subkey.  It seems this can also be accomplished by unsetting the class array:
```php
unset($form['actions']['submit']['#attributes']['class']);
```
I'm not sure if there is an advantage to one way over the other.  Let me know your thoughts or if this way is the right way of course merge away! :bow:

**Comment by quicksketch** [comment]
I think I would prefer the `unset()` approach, setting to an empty array is odd. We should add a code comment as well, indicating that we're removing the `button-danger` class so that `button-primary` will be added automatically for us.

**Comment by serundeputy** [comment]
`unset()` added comment and `rebase`d;
:sake:

**Comment by quicksketch** [comment]
Great, thanks! Merged in.
