### ISSUE TITLE
$info['types']['menu-link'] not defined but has tokens

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#914]
After manually patching my Backdrop test site to include the changes in #87 and running update.php/cron + clearing all caches, I get this warning in my site status report:

> Tokens   Problems detected
> The following token types are not defined but have tokens:
> - $info['types']['menu-link']

**Comment by quicksketch** [comment]
Hm, interesting, thanks @klonos! I'll have a look into it.

**Comment by quicksketch** [comment]
This was a porting bug it looks like. Easy to fix. PR at https://github.com/backdrop/backdrop/pull/885.

**Comment by klonos** [comment]
Yep, fixed! Thanx.
