### ISSUE TITLE
[node:source:title] invalid token after upgrade to core Token and removing contrib Token.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#917]
Error:

> The Default path pattern (applies to all content types with blank patterns below) is using the following invalid tokens: `[node:source:title]`.

**Comment by quicksketch** [comment]
Thanks, "source" is related to translations, is it not? We shouldn't have removed any tokens as part of this conversion, so this is a bug.

**Comment by quicksketch** [comment]
Looks like the "type" property was missing in node_token_info(). This PR should fix it: https://github.com/backdrop/backdrop/pull/884.

**Comment by klonos** [comment]
Yep, fixed too! Thanx again.
