### ISSUE TITLE
Remove references to Drupal.org

### ISSUE THREAD

**Issue by sirkitree** [backdrop/backdrop-issues#92]
This is a large task. By my count here are 250 references in 90 files. Some of these remain relevant in that they point to a particular issue that talks about major decisions regarding a function and some point to handbook entries that are still relevant regarding how to theme, update, etc. Such entries will remain relevant until... well, until they're not ;) We may want to discuss if we should mirror some or all of these on backdropcms.org or if we should just leave them.

I'm also not sure on the best way to tackle these. Should we create a separate issue for each one we find and close them out as pull requests for each individual one comes in? Or should we list them all into one ticket as checkboxes and split them out if necessary, linking to the individual ticket if one is split off, or link to the individual pull request when checking off?

**Comment by jenlampton** [comment]
@hellomrcat I've assigned this issue to you, and it should be a simple one.

The task remaining here is to grep through the entire codebase for "Drupal" (case insensitive) and make sure that we aren't accidentally referring to Backdrop as Drupal anywhere.

You will occasionally see references to URLs on drupal.org, and generally speaking those are fine, though it might be nice if you clicked through to each one to make sure the link is still relevant.  Any questions about those, add them here :)

**Comment by hellomrcat** [comment]
@jenlampton if there are links to Drupal issues that are now closed (either fixed or duplicate), does that count as no longer relevant? [For example, this issue](https://www.drupal.org/node/1009382) is referenced in `ajax.inc`:
```
    // Browser IFRAMEs expect HTML. Browser extensions, such as Linkification
    // and Skype's Browser Highlighter, convert URLs, phone numbers, etc. into
    // links. This corrupts the JSON response. Protect the integrity of the
    // JSON data by making it the value of a textarea.
    // @see http://malsup.com/jquery/form/#file-upload
    // @see http://drupal.org/node/1009382
```

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/issues/960.

We're looking pretty good here. There are still ~400 references to Drupal in our code base, but nearly all of them are in reference to the compatibility layer, or historical information about earlier versions of Drupal.

I think for purpose of this issue, this should be closed. Let's make new individual issues as we run across any other inappropriate references.
