### ISSUE TITLE
Missing /div from templates/layout.tpl.php ?

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#922]
Is there not a missing /div from core/modules/layout/templates/layout.tpl.php where I see this at line 28
`
 <?php if ($content['header']): ?>
    <header class="l-header" role="banner" aria-label="<?php print t('Site header'); ?>">
     <div class="section clearfix">
      <?php print $content['header']; ?>
    </header>
  <?php endif; ?>
`

**Comment by klonos** [comment]
Yep, good catch there @Graham-72 :+1:

**Comment by Dinornis** [comment]
Closing, looks like this has been fixed already.
