### ISSUE TITLE
Views UI missing "Create a block"

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#923]
In the latest code, only "Create a page" checkbox is available.

**Comment by serundeputy** [comment]
this seems to be controlled by this:
`backdrop/core/modules/views_ui/wizards/views_ui_base_views_wizard.php`

```php
// All options for the block display are included in this container so they
    // can be hidden en masse when the "Create a block" checkbox is unchecked.
    $form['displays']['block']['options'] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('options-set'),),
      '#states' => array(
        'visible' => array(
          ':input[name="block[create]"]' => array('checked' => TRUE),
        ),
      ),
```
and the corresponding lines for the page display, but I'm not sure the right course of action to correct it?

**Comment by serundeputy** [comment]
this technique works: https://github.com/backdrop/backdrop/pull/893

something tells me @quicksketch will have a cleaner/better way to do it.

**Comment by docwilmot** [comment]
There is in fact a much cleaner technique: delete the `#attributes` on the container. Solves both problems. But I dont know why. Can you figure it @serundeputy?

**Comment by docwilmot** [comment]
And I can confirm that putting an #attributes property on any FormAPI container element with #states causes the same issue.

**Comment by quicksketch** [comment]
Wow, that is very odd. I'll see if I can get to the bottom of this. Maybe we could fix the functionality of #states directly and leave the entire Views UI as-is.

**Comment by serundeputy** [comment]
`PR`: https://github.com/backdrop/backdrop/pull/894
added `.options-set` selector to `misc.js`

**Comment by quicksketch** [comment]
@serundeputy: Ah! You found the same problem I did. I think it'd be cleaner to just add "form-wrapper" to the list of classes on the container elements

**Comment by serundeputy** [comment]
@quicksketch will do;

**Comment by serundeputy** [comment]
updated to add `form-wrapper` to the views wizard form containers for block and page.  I left the class `options-set` in there.

should that class be removed?  I don't know if it is used for styling or anything.  :fried_shrimp:

**Comment by quicksketch** [comment]
It looks like Views uses `options-set` for styling, so let's leave it in place.

**Comment by quicksketch** [comment]
Thanks! Fixed in https://github.com/backdrop/backdrop/pull/894.
