### ISSUE TITLE
Add new view "Create a page" checkbox cannot be unchecked

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#924]
On the add new view page, if you uncheck the create a page checkbox itcompletely disappears; you're not allowed to change your mind.
![before](https://cloud.githubusercontent.com/assets/1042283/7638204/c6bea926-fa38-11e4-87de-d6d2c40453fd.PNG)
After unchecking:
![after](https://cloud.githubusercontent.com/assets/1042283/7638213/d364c80e-fa38-11e4-9ea6-382180a985b5.PNG)

**Comment by serundeputy** [comment]
This `PR`: https://github.com/backdrop/backdrop/pull/893 addresses #923 and #924.

there maybe a more elegant way of handling this.  If people have thoughts please chime in.

**Comment by quicksketch** [comment]
This problem has the exact same causes as https://github.com/backdrop/backdrop-issues/issues/923, let's consolidate this issue with that one. Thank you for pointing out both problems individually. :+1:
