### ISSUE TITLE
Can't translate content even through Backdrop ships with Content Translation module

### ISSUE THREAD

**Issue by heybenji** [backdrop/backdrop-issues#925]
Hey there. I'm new to Backdrop but I'm trying to set up a basic bilingual (English, Spanish) site and I'm failing to grasp how I would actually translate content with Backdrop out of the box even through it ships with the Content Translation module.

I've set up an install of Backdrop. I've enabled the Locale, Language, and Content Translation modules.

I create a node, but I see no "Translation" tab. Am I missing something? Is there a module I need to install? I've triple-checked permissions, and gone over the Regional and language settings probably 15 times, and I just can't figure out what I'm missing.

**Comment by quicksketch** [comment]
Hi @heybenji! Thanks for trying out Backdrop! To create multilingual content, you must edit the content type and under "Publishing settings", use set "Multilingual support" to "Enabled, with translation". You must also have set up at least two languages. Now when you edit a node of that content type, there should be a language select list. Set the language to English or Spanish, and then the "Translation" tab will appear on the node on the front-end. The translation tab is not shown for nodes that have no language specified.

**Comment by heybenji** [comment]
Thanks! That worked!

Benji Mauer
617-283-5764
@heybenji
www.heybenji.co
