### ISSUE TITLE
Default config for user-created entities

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#926]
My [Simplify](https://github.com/backdrop-contrib/simplify) module has default config files for nodes, comments, etc. but these are all empty as each config inside these files is grouped by content type (and I don't know what content types a user has got on their site until they submit the content type settings form and populate the config file).

If they don't do this, Simplify won't hide any fields initially as it gets a NULL return from the config file (not an empty array). How can I specify an empty array as the default value if the content type in question doesn't have an entry in the config file yet?

**Comment by BWPanda** [comment]
Is it recommended to do something like the following pseudo code in a module's .install file, or is there a better way?

```
$config = config('simplify.nodes');
$content_types = get_content_types();
foreach ($content_types as $content_type) {
  $config->set($content_type, array());
}
$config->save();
```

**Comment by docwilmot** [comment]
I think that sounds reasonable. Youd probably need a hook to set defaults for new user-created node types as well right?

Alternatively, (pseudocode) in the module somewhere
```
if(!config_get('simplify.nodes', $content_type)) {//$value =  array()}
```
would account for all.

**Comment by BWPanda** [comment]
@docwilmot I already have code that saves the config for a content type (https://github.com/backdrop-contrib/simplify/blob/1.x-1.x/simplify.module#L218), so this will work for new content types as they're created. It's just the ones that exist before Simplify's installed.

Also, I did think of doing something similar to your pseudocode, but then I'd have to do that everywhere config_get is used...

**Comment by docwilmot** [comment]
> but then I'd have to do that everywhere config_get is used

true, I'd go with your way.

**Comment by quicksketch** [comment]
I'm not certain what's being requested here, but you can store settings for node types directly in the `node.type.[type].json` file if that would be more appropriate. You can do so by form_altering the node type form, then adding your settings. I believe all settings are saved automatically into the node type config file.

In addition to the form_alter(), you should add `hook_node_type_load()` to your code to specify the additional default values for each type. See https://api.backdropcms.org/api/backdrop/core!modules!node!node.api.php/function/hook_node_type_load/1 for an example.

**Comment by quicksketch** [comment]
Hmm, well this might not work well because entity types are not yet consistent. You'd have to implement hook_taxonomy_vocabulary_[name]() as well, and I don't think there is anything at all for "user types" where similar data could be saved.

So it looks like saving for all entity types in a single config file might be the best approach. It's what the new path integration does as well, as it is in a similar situation where it works with nodes, terms, and users.

**Comment by BWPanda** [comment]
@quicksketch This question related more to the fact that there's no way to specify the default value for entities if you don't know what entities exist.

For example, here is Simplify's current node config file on my sandbox site:
```
{
    "_config_name": "simplify.nodes",
    "article": [
        "format",
        "revision",
        "comment",
        "path"
    ],
    "page": [
        "author",
        "format",
        "revision",
        "path"
    ],
    "test": [
        "author",
        "format",
        "options",
        "revision",
        "comment",
        "menu",
        "path"
    ]
}
```

Ideally, the default config file that ships with Simplify would look something like this:
```
{
    "_config_name": "simplify.nodes",
    "article": [],
    "page": [],
    "test": []
}
```
but there's no guarantee that those content types will exist of a given site when Simplify's installed. Therefore, the default config file _actually_ looks like this:
```
{
    "_config_name": "simplify.nodes"
}
```

As such, when asking for an array of hidden node fields, NULL is returned instead off an empty array...

**Comment by quicksketch** [comment]
I see. I think the best thing to do would be to provide a function wrapper around config_get() that populates the defaults. So instead of using config_get() directly, you might do something like the following:

```php
function simplify_nodes_get_config($node_type) {
  $config = config_get('simplify.nodes', $node_type);
  if (is_null($config)) {
    $config = array(
      // Set defaults if needed.
    );
  }
  return $config;
}
```

Generally speaking, calling config() directly should be considered similar to doing a database query: it's a raw API. If you are retrieving values frequently or need to populate defaults, it may be best to wrap it in a small API, like we do for any other system that used to be database-driven (loading Vocabularies, Menus, Node types, etc.)

**Comment by BWPanda** [comment]
Thanks @quicksketch.

I'm wondering if this'll make things confusing though; knowing whether to call config_get directly or one of the wrapper functions...

I can see the benefit if this were in core instead though:
```php
function get_config($config_file, $option, $default) {
  $config = config_get($config_file, $option);
  if (is_null($config)) {
    $config = $default;
  }
  return $config;
}
```

**Comment by quicksketch** [comment]
I'd like to avoid restoring the $default parameter. It was always a hassle going and finding the default value and then using it consistently. If we add it back, the parameter itself would be a point of confusion, whether or not you had to (or should) use it.

**Comment by BWPanda** [comment]
Hmm, ok. I think I'll stick with my original idea then: https://github.com/backdrop/backdrop-issues/issues/926#issuecomment-102277062

Thanks all.
