### ISSUE TITLE
Admin Tabs not laying out correctly in IE8 and Seven

### ISSUE THREAD

**Issue by wesruv** [backdrop/backdrop-issues#928]
Tabs are below the gray header
![backdrop-ie8](https://cloud.githubusercontent.com/assets/5607236/7663514/92946a58-fb39-11e4-9ea5-bd50a2855be1.png)

Can't peg what's going wrong, think I'm going to do an IE8 only style with selector fanciness

**Comment by MrHaroldA** [comment]
IE8 (and 9?) support might be dropped from the core supplied themes: #214.

**Comment by wesruv** [comment]
@MrHaroldA thanks for the heads up!

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/898. Thanks!

IE8 is still supported in Backdrop to the furthest degree we can. Most of the time that means a slightly degraded (but still entirely functional) experience.
