### ISSUE TITLE
[UX] Add a quick search field in the "Add block" dialog.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#929]
The list of available blocks will inevitably grow over time and people prefer to filter down to what they are looking for instead of scrolling endless lists. Lets do the same thing we do for Views and the "Add fields" dialog by adding a quick search field and perhaps a "category" drop-down (so for example people can limit the list to only menu blocks).

**Comment by quicksketch** [comment]
Thanks, I've linked this issue to the meta of Layout follow-up issues at https://github.com/backdrop/backdrop-issues/issues/345.

**Comment by quicksketch** [comment]
@docwilmot's PR at https://github.com/backdrop/backdrop/pull/1019 looks great. I think we'll see this in the 1.2.0 release.

**Comment by klonos** [comment]
Perfect!! Thanx you guys.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/1019. Thanks everyone!
