### ISSUE TITLE
[UX] Views UI redesign to match the rest of the admin UI.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#930]
Open two tabs in your browser... for example `/admin/structure/layouts/manage/default` and `/admin/structure/views/view/node_admin_content` and notice the difference in font sizes for same elements like page title, button text and size etc. Makes the whole UI experience very inconsistent. ...and just to be clear: I think we should brink the Layout font size down to what Views UI has - not the other way around.

I have previously expressed my concerns with the font size chosen and the waste of screen estate this change brings. The font is HUGE!

---
~PR (part1) by @klonos: https://github.com/backdrop/backdrop/pull/1650~
~~PR by @wesruv: https://github.com/backdrop/backdrop/pull/1824~~
PR by @jenlampton https://github.com/backdrop/backdrop/pull/1846

**Comment by quicksketch** [comment]
The Views administration is a bit of a special case, as the density of information is far greater there than in any other interface in Backdrop. Within the Views UI, font sizes are specifically reduced as a necessity. Personally, I prefer the larger font size, though margins were reduced in a few places already.

Just doing a search for "16px font size" to get an idea of if I'm alone preferring the larger size, the top 3 hits all seem to encourage 16px as a usability improvement:

http://www.adaptistration.com/blog/2012/02/24/16px-font-size-and-48px-wide-buttons-are-the-new-black/
http://www.smashingmagazine.com/2011/10/07/16-pixels-body-copy-anything-less-costly-mistake/
https://developers.google.com/speed/docs/insights/UseLegibleFontSizes

So I don't think we'll be reducing the font size everywhere else if that's what you were angling for, but I would be thrilled to find a way to make it so that the Views UI font size could be increased (as well as making it mobile friendly).

**Comment by klonos** [comment]
> So I don't think we'll be reducing the font size everywhere else if that's what you were angling for...

Yep, that's exactly where I was getting at. Nevertheless, lets keep this issue open in order to address the more generic issue of font size inconsistency between the Views UI and the rest of the admin theme.

**Comment by jenlampton** [comment]
Is there an action item here?  Is it just the meta of redesigning the views UI to make room for all the things?  I'm not sure we can just remove the font-shrinking on the while views UI without breaking everything.  Maybe the action item is to try it and see?

**Comment by klonos** [comment]
Decide on either *increasing* the font in Views UI to bring in in tandem with the rest of the UI or decrease the font size of the rest of the UI in order to match the size in Views UI. I vote the later.

**Comment by Graham-72** [comment]
I have just had a surprise about font size for admin pages. Maybe there is some setting I have not yet found, but having just set up a very small trial site for one of my clients I find that in giving permission for an authenticated user to view the content listing they get a more compact result than the one given to the user with administrator permissions. It seems the authenticated user is getting the site theme rather than the administration theme. On my relatively small laptop screen I prefer the more compact layout. Here are the screenshots:
Administrator
![admin content listing1](https://cloud.githubusercontent.com/assets/10559274/9001099/3d24d038-374a-11e5-91b2-1a34733a86b7.png)

Authenticated user
![admin content listing2](https://cloud.githubusercontent.com/assets/10559274/9001108/4e573e9a-374a-11e5-9833-37c5796dd60c.png)

**Comment by quicksketch** [comment]
There is a separate permission for "View administration theme". It looks
like your second user does not have this permission, so they get the
front-end theme. A bit odd, but the permission has been in place for the
entire D7 cycle.

**Comment by Graham-72** [comment]
Thanks for the explanation. I had forgotten all about that setting.

**Comment by quicksketch** [comment]
Also relevant to this issue https://github.com/backdrop/backdrop-issues/issues/1314

That issue is essentially "Redesign Views UI", which if implemented, could allow for more space for individual controls, and make the font size consistent with the rest of the UI.

**Comment by jenlampton** [comment]
Clearing this milestone. Since this is a UX related issue it can go in any time, and does not need to be officially scheduled for 1.4.0 :)

**Comment by wesruv** [comment]
The Views UI font size has to come up to 16, but there's no way to do that with the current "design". I think this consistency has to wait until #1314 is worked out.

But seeing @klonos' frustration with larger font size I think we could make a user setting for font-size. 16px **has to be** the default for the previously stated accessibility and UX reasons, but if we code the admin theme well (and a certain way) there's no reason we couldn't add something very simple to allow users to change the font-size.

Out of curiousity, @klonos if you use the 'Zoom' browser feature to zoom out, does that provide a decent/good experience in regards to your preferred font size?

**Comment by wesruv** [comment]
I vote we either change this ticket to 'support user settings for admin font size' or close it since Views UI can't currently support a larger font.

**Comment by klonos** [comment]
> Out of curiousity, @klonos if you use the 'Zoom' browser feature to zoom out, does that provide a decent/good experience in regards to your preferred font size?

Actually yes. I tested this on firefox I initially tried zooming out the rest of the UI (admin content and edit layout pages) and it looked more consistent with the views UI. I then tested the reverse: zooming in on the views UI and comparing it to the original zoom of the two admin pages and again the font size looked mostly consistent.

Unfortunately, there is no way to tell the exact zoom level in a number because the firefox UI does not provide that in the UI. It was one `ctrl` + `+` or `ctrl` + `-` for each case. That's all I can tell you.

The only thing that was left feeling a bit oversized and still taking too much space even when zoomed out was the buttons and the drop-down menus or fields. What made these look less "huge" was changing the current padding of form elements from 10px to 5px and for submit buttons change the the padding from 0 25px to 0 15px plus line-height from 46px to 38px. Also, th/td padding from 10px 20px to 5px 20px.

So, (with regular zoom) from this:

![backdrop-admin_ui-normal_padding](https://cloud.githubusercontent.com/assets/2423362/14225507/bc0d26ce-f910-11e5-9fa5-9b7afb4bf228.png)

...I got this:

![backdrop-admin_ui-less_padding](https://cloud.githubusercontent.com/assets/2423362/14225506/bc0ab088-f910-11e5-8cb9-6218b17947cf.png)

IIRC the other person that has previously "complained" about the font size and in general the way things look "huge" with the new admin design was @Graham-72

**Comment by Graham-72** [comment]
Yes,  guess I have got used to what seemed, coming from Drupal 7, an unnecessarily large font size (execpt for the Views UI). I decided that most of you must have large screens whereas I work mostly on my laptop with 1280px width.

**Comment by klonos** [comment]
I respect the choice that was made with regards to font size etc that came with the new design. Its goal was to set us apart from D7/D8. What bothers me (as an end user) is the inconsistency of the font size between different pages of *the same* theme.

**Comment by mikemccaffrey** [comment]
> coming from Drupal 7, an unnecessarily large font size (execpt for the Views UI). I decided that most of you must have large screens whereas I work mostly on my laptop with 1280px width.

We really should add responsive font sizing to the system, so bigger screens have bigger fonts and we are mindful of the limited real estate on smaller screens.

**Comment by wesruv** [comment]
Responded to @mikemccaffrey here: https://github.com/backdrop/backdrop-issues/issues/1775#issuecomment-205014944

**Comment by klonos** [comment]
I was mocking around (pun intended) with the Views UI for #315 and #2342 and here is what I got:

![backdrop-issue930-mockup](https://cloud.githubusercontent.com/assets/2423362/20451990/7b40d114-ae54-11e6-81f1-2409267d72a0.png)

Can we please take baby steps and do the following (in no specific order):

1. Font size
2. Remove borders from sections and replace with grey background for the section titles.
3. Expose drag handlers and x delete buttons instead of the dropbutton "rearrange" item.
4. Make "add" buttons links instead and add a "+" in front of them.

**Comment by jenlampton** [comment]
> Expose drag handlers and x delete buttons instead of the dropbutton
"rearrange" item.

I believe the JavaScript for this was too much for the page if we had more
than one section draggable at a time. May not be possible.

Love the other ideas though!

**Comment by klonos** [comment]
...also good idea to consider: prevent accidental deletions by marking items for deletion after form submit (Save view) instead of removing them straight away and also providing an undo button. Something like this perhaps:

![backdrop-issue930-mockup-delete-undo](https://cloud.githubusercontent.com/assets/2423362/20452238/4db02038-ae59-11e6-9e99-217ddacc439f.png)

**Comment by klonos** [comment]
> I believe the JavaScript for this was too much for the page if we had more than one section draggable at a time. May not be possible.

As I said, baby steps. We don't have to do everything that I suggest (especially if it's too hard or costs us performance-wise).

> Love the other ideas though!

I'll see if I can put a PR together with as much as my skills are good for. Others can pick it up from where I leave it.

**Comment by klonos** [comment]
...alright, I've just filed an initial PR that starts fixing the styling.

**Comment by quicksketch** [comment]
@wesruv built on top of @klonos's PR at https://github.com/backdrop/backdrop/pull/1824. Let's continue from that one.

**Comment by quicksketch** [comment]
> It seems the authenticated user is getting the site theme rather than the administration theme.

@Graham-72 Yeah that can happen as there is a specific permission for `View the administration theme`, resulting in administrative pages being displayed in the front-end theme. Honestly I think that's a bit unusual that we have such an option, but it helps separate situations where you have non-editorial users creating content.

I'm up for accepting this PR based on Wes and Gregory's opinions. Does anyone want to weigh in here?

**Comment by klonos** [comment]
@wesruv a few comments (some of them can go as separate follow-up issues I you like):

1. To zebra or not to zebra? ...that is the question. I think I like the readability and distinction between lines with the zebra better, plus there's more consistency with the rest of the UI:

![image](https://cloud.githubusercontent.com/assets/2423362/24904397/b358d55a-1ef3-11e7-88ca-3712124dfd2e.png)

2. Lets please bring the display tabs to the 21th century, as we did with the secondary tabs (again for more UI consistency)

![image](https://cloud.githubusercontent.com/assets/2423362/24904496/ef675346-1ef3-11e7-8392-7fe8bc659321.png)

3. continuing from point 2 above... seriously, what's up with the tiny button opens big-@ss menu with rounded corners and all?:

![image](https://cloud.githubusercontent.com/assets/2423362/24904598/4c6e21be-1ef4-11e7-8445-b2ed16ec1dfc.png)

...not to mention that the + sign is "jumping" up and down when you hover over/off it while the menu is open 😠 😄 😞 

4. The "Display name:" label needs to be darker for better contrast with the background.

5. The contents of the `.edit-display-settings-top` div need to be aligned vertically (seem like about 1px up)

6. The contents of the `.views-display-setting` divs need about 14px of padding from the left (in order to be aligned with the h3 title of the `.views-ui-display-tab-bucket` divs).

7. The contents of the `.views-display-top` header start wrapping a bit funny below a certain breakpoint (although they seem to still have enough space to remain inline):

![image](https://cloud.githubusercontent.com/assets/2423362/24905124/2dbb5a64-1ef6-11e7-9b6b-5099f7d76928.png)

**Comment by quicksketch** [comment]
I added another commit to the latest @wesruv PR. With the following changes (mostly addressing @klonos's feedback in the comment above):

- Views tabs styled to match the rest of Seven (actually more removing of CSS than adding here)
- Fixed the huge line height in the add displays button.
- Fixed font contrast.
- Vertical alignment in places.

There are still more updates to be made. I didn't add zebra striping yet. Still feedback on the updates would be appreciated.

**Comment by jenlampton** [comment]
This looks a *so much* better!! 

At first I didn't think there was enough contrast on the headings with the fainter gray, but it's growing on me. It feels less overwhelming now, somehow. I'm starting to really like it :)

I notice the gray backgrounds are missing the border-radius of 4px that's elsewhere on the admin theme.  Was that intentional? I wonder if it should be added in 

The "displays" section still needs a little love. Active/Inactive/Error all seem to be different sizes:
<img width="1267" alt="screen shot 2017-04-27 at 8 04 44 pm" src="https://cloud.githubusercontent.com/assets/397895/25512747/e16a7898-2b84-11e7-93ab-45f12dd73fa9.png">

Here's a re-work with a 1px border and consistent padding on each:
<img width="641" alt="screen shot 2017-04-27 at 8 28 34 pm" src="https://cloud.githubusercontent.com/assets/397895/25513184/26eed8b6-2b88-11e7-8f10-57e4408fc1fd.png">

**Comment by quicksketch** [comment]
> I notice the gray backgrounds are missing the border-radius of 4px that's elsewhere on the admin theme. Was that intentional? I'm going to make a new PR that adds it in Seven to see what that looks like.

Even better. Nice one @jenlampton!

> The "displays" section still needs a little love. Active/Inactive/Error all seem to be different sizes:

In the screenshot above, the "Feed" display tab looks too small still compared to the tabs right next to it. The red border should be on the outside of the element rather than the inside. Only a minor complaint.

Regarding zebra striping... I'm leaning towards not striping the UI. Striping adds a lot of visual clutter and de-emphasizes the section headings. The usefulness of them is also less because the rows aren't wide enough to necessitate helping line up the left and right sides of the table. And there's nothing on the right side to line up with anyway.

**Comment by quicksketch** [comment]
@jenlampton also commented about the color syntax being inconsistent. We have this documented in our CSS standards as such:

> When hex values are used for colors, use lowercase and, if possible, the shorthand syntax, e.g. #aaa. 

So we should use the shorthand wherever possible (as the PR is currently doing).

**Comment by jenlampton** [comment]
I feel like there might be too much vertical space between items in a section. Is this better or worse?

Before:
<img width="1192" alt="screen shot 2017-04-27 at 8 42 14 pm" src="https://cloud.githubusercontent.com/assets/397895/25514713/9b904ed8-2b93-11e7-8834-414b129dc14d.png">

After:
<img width="1188" alt="screen shot 2017-04-27 at 8 42 42 pm" src="https://cloud.githubusercontent.com/assets/397895/25514716/a00322d8-2b93-11e7-8315-86b75e7a2cba.png">

**Comment by jenlampton** [comment]
> In the screenshot above, the "Feed" display tab looks too small still compared to the tabs right next to it. The red border should be on the outside of the element rather than the inside. Only a minor complaint.

Oh interesting, so maybe the other item's borders should be transparent? Let me try that...

**Comment by jenlampton** [comment]
Well, I don't think it looks any different. To me they all look the same size both before and after, what do you think?

<img width="614" alt="screen shot 2017-04-27 at 10 02 35 pm" src="https://cloud.githubusercontent.com/assets/397895/25514916/5ab5b356-2b95-11e7-8051-019a6d423828.png">

> Regarding zebra striping... I'm leaning towards not striping the UI. 

I agree. This UI isn't a list like all the other places we have zebra striping. I think it might seem about of place in addition to adding clutter.

**Comment by jenlampton** [comment]
Oh hey, I think I got it: 
<img width="599" alt="screen shot 2017-04-27 at 10 13 36 pm" src="https://cloud.githubusercontent.com/assets/397895/25515075/d1127236-2b96-11e7-931c-744a15856fd3.png">

**Comment by Dinornis** [comment]
PR looks good, no need for zebra.

**Comment by olafgrabienski** [comment]
Great work overall!

> there might be too much vertical space between items in a section. Is this better or worse?

Better with less vertical space in my opinion.

**Comment by quicksketch** [comment]
This is looking great. I reworked the RTL and mobile styles slightly for the tabs at the of the Views UI in https://github.com/backdrop/backdrop/pull/1846. And I did a little border adjustment for Basis. The UI is now serviceable (if not perfect) in Seven, Basis, and Bartik. Though I wouldn't recommend using Basis or Bartik due to a number of other issues.

Seven:

![image](https://cloud.githubusercontent.com/assets/100206/25546471/17f6ca40-2c18-11e7-907a-a09df33816f7.png)

Basis:

![image](https://cloud.githubusercontent.com/assets/100206/25546457/04ebab00-2c18-11e7-980f-0a6652ec4e67.png)

Bartik:

![image](https://cloud.githubusercontent.com/assets/100206/25546491/2ca7cc64-2c18-11e7-8fc8-ec5b41f62726.png)

**Comment by jenlampton** [comment]
I still think less vertical space is in order. I'm pushing one more commit that makes it look like this:

<img width="1210" alt="screen shot 2017-04-28 at 1 51 04 pm" src="https://cloud.githubusercontent.com/assets/397895/25546880/c19fd162-2c19-11e7-95ab-df1f19713c7d.png">

**Comment by Dinornis** [comment]
I also do not care for the increased vertical spacing.  I did not mention this earlier because I assumed it was necessary for accommodating touch devices.

**Comment by klonos** [comment]
> This looks a so much better!!

Yeah it does!! ❤️ 

>Regarding zebra striping... I'm leaning towards not striping the UI. Striping adds a lot of visual clutter and de-emphasizes the section headings...

Fair point about the unnecessary emphasis added with zebra strippes, but the main usability issue I'm having when not using stripes is with lines (as in each individual setting) wrapping into two when they are longer than the horizontal space that is allocated to them (the width of each "box"). This might be more obvious with languages that use longer words (when the views UI is translated), with the "Access" setting (which is also missing a header btw: #2468 PR pending your review/feedback @quicksketch 😉 ) and is particularly obvious when "Use aggregation" is enabled:

![image](https://cloud.githubusercontent.com/assets/2423362/25547740/4ac5e804-2cac-11e7-9c30-dd21aa3a30f4.png)

> I also do not care for the increased vertical spacing. I did not mention this earlier because I assumed it was necessary for accommodating touch devices.

@jenlampton, @Dinornis I do like the less vertical space between rows A LOT (-> less scrolling -> better UX), but as you can see from the screenshot above, when rows wrap, it is hard(er) to tell if it is a separate row or a wrapping one. So, the way I see it is either zebra stripping + smaller vertical space (my personal preference), or no stripping but added vertical space between rows. Unless anyone has better ideas that is.

> ...The usefulness of them is also less because the rows aren't wide enough to necessitate helping line up the left and right sides of the table. And there's nothing on the right side to line up with anyway.

I was hoping that one day there would be something 😄 :

![backdrop-issue930-mockup-delete-undo](https://cloud.githubusercontent.com/assets/2423362/20452238/4db02038-ae59-11e6-9e99-217ddacc439f.png)

(I find it neither intuitive nor ideal having to click twice to reach the rearrange button that also removes things)

Other minor nits:

- I would prefer if the rows had the same left padding as the headers so that they are horizontally aligned (leaves room for the drag handlers on my mockup too 😄 )
- The mouse cursor is sometimes a pointer sometimes a hand over buttons and dropbuttons. I think that it should be a hand only over plain links.

**Comment by Dinornis** [comment]
I think that serious touch-device testing is in order to make the right decisions regarding vertical spacing. I would love to do that, but do not have any.

Maybe the rearrange/remove functionality needs to be addressed in a separate issue?

**Comment by klonos** [comment]
Will see if I can test on my mobile, but I seriously doubt anybody will be doing views configuration on their phone. On a tablet perhaps yes.

> Maybe the rearrange/remove functionality needs to be addressed in a separate issue?

Yes. I was planning to file a separate issue.

**Comment by olafgrabienski** [comment]
> The mouse cursor is sometimes a pointer sometimes a hand over buttons and dropbuttons. I think that it should be a hand only over plain links.

I often wondered why the mouse cursor over buttons isn't a "hand" in Backdrop. Why?

**Comment by klonos** [comment]
Well, I guess it's a matter of implementation and preference (buttons IMO should have a plain, mouse pointer and links should have a hand)...

This comes from my computer engineer background: non tech-savvy users would very often get tricked by ads around the internet making them think that an image was an actual error on their computer. Some of these malicious ads were even smart enough to adapt their looks depending on whether the computer was a PC or a Mac. The only way to avoid being tricked was to train the users to not be clicking anything that had a hand when hovered over (hence was a link and not a button).

Now, with Drupal and Backdrop, we have some form submit elements that are links and some that are buttons (example: the node edit form where save and delete are buttons while the cancel is a link).

Here's what I was talking about with the inconsistency in the views UI specifically:

- **views displays buttons/tabs**: the tabs have a hand cursor, so does the add button, but the menu with the available views displays uses a simple pointer cursor:

    ![views-displays](https://cloud.githubusercontent.com/assets/2423362/25551085/158cdd3e-2cc3-11e7-9626-c642eb3a6cac.gif)

- **view actions dropbutton** (top-most to the right): uses a hand cursor for its main action, for the triangle button that opens the menu as well as for the menu options.
- **display action dropbutton** (right bellow the view actions dropbutton): uses a hand cursor for its main action, for the triangle button that opens the menu, but for the menu options it uses a plain pointer.
- **add/rearrange dropbuttons**: use a hand cursor for the main cation (add), for the triangle button that opens the menu and for the "rearrange" action.

    ![views-dropbuttons](https://cloud.githubusercontent.com/assets/2423362/25551165/3b3b9baa-2cc4-11e7-8638-2817ba10a61d.gif)

**Comment by klonos** [comment]
> ...buttons IMO should have a plain, mouse pointer and links should have a hand...

I'm not suggesting to go with what my personal preference is (though I would like that). All I'm saying is be consistent across the UI so that the user does not wonder why (...that is if they suffer from severe self-diagnosed cases of OCD like myself 😝 ).

**Comment by quicksketch** [comment]
> I would prefer the rows having the same left padding as the headers so that they are horizontally aligned (leaves room for the drag handlers on my mockup too :smile: )

Aligned, though the drag handles would be something we can handle later.

> The mouse cursor is sometimes a pointer sometimes a hand over buttons and dropbuttons. I think that it should be a hand only over plain links.

The cursor indeed is all screwed up. It's because Views hides a bunch of buttons and makes them look like links. As you mentioned earlier, buttons use the normal cursor while links use the "pointer". I updated the CSS to make these undercover buttons use the same cursor as links.

> So, the way I see it is either zebra stripping + smaller vertical space (my personal preference), or no stripping but added vertical space between rows. Unless anyone has better ideas that is.

One thing I found helpful (and surprising) is that Views had been removing the underline from links on hover. I nixed this rule and it helps slightly with associating longer lines when hovering the cursor. Not helpful for touch but still an improvement for mousers.

**Comment by Dinornis** [comment]
Looks pretty nice now.

Although there seems to be quite a lot of space (36px) between the main settings area and the message:` Click on an item to configure that item's details.`

`<div class="views-displays">
.views-displays { padding-bottom: 36px; }`

and between the page title and unit title.
`padding-top: 1.5em;`
for
`<h1 class="unit-title">Displays</h1>`
However, changing these may break some other admin page layout, so probably better left alone.

**Comment by quicksketch** [comment]
> and between the page title and unit title.  However, changing these may break some other admin page layout, so probably better left alone.

Yeah in this case the title has to be pushed down for when the "Save" button is present. So leaving as-is may be best.

> Although there seems to be quite a lot of space (36px) between the main settings area and the message:Click on an item to configure that item's details.

Agreed that doesn't need to be there at all. I've nixed it.

**Comment by quicksketch** [comment]
I've merged https://github.com/backdrop/backdrop/pull/1846 into 1.x for 1.7.0. There are still a lot of ideas in this issue that haven't been implemented yet. Many of @klonos's ideas are worthy of their own issues. But with the amount of discussion already in this issue, I think it's best to complete this thread and continue refining in new ones.

Thanks @klonos, @jenlampton, and @wesruv for implementation. As well as @dinarcon, @olafgrabienski, and @Graham-72 for their feedback!

**Comment by klonos** [comment]
Thanx. I'll file separate issues for any remaining tasks worth pursuing once I get the chance.
