### ISSUE TITLE
Where are the fields tokens gone after 1.1?

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#937]
I've just upgraded to Backdrop 1.1, and Token in core is great news, but all my patterns containing fields-related token are now marked as invalid, and don't appear in the tokens browser as well…
Is it a bug, or planned for a next release?

**Comment by quicksketch** [comment]
Hi @jdanthinne! That definitely sounds like a problem! All the field tokens should still work. Could you provide examples of the tokens that are no longer working?

**Comment by jdanthinne** [comment]
As you can see in the attached screenshot, fields tokens are marked as invalid, and the browser doesn't list any field at all (and I have a dozen of them in content types)…
![capture d ecran 2015-05-18 a 20 12 17](https://cloud.githubusercontent.com/assets/485107/7687040/a11ff570-fd9a-11e4-93cb-1fe3e2a5928b.png)

**Comment by quicksketch** [comment]
Thanks @jdanthinne. I've confirmed the problem as well. We'll try to get this fixed ASAP and put out a 1.1.1 release to correct it.

**Comment by quicksketch** [comment]
I've filed a PR to fix this at https://github.com/backdrop/backdrop/pull/906.

We could use some more comprehensive tests, but this covers the basics by testing for the `[node:field_image]` and `[node:field_tags]` fields that exist by default on article content types.

**Comment by quicksketch** [comment]
Sorry, correct PR is https://github.com/backdrop/backdrop/pull/908.

**Comment by jdanthinne** [comment]
Great. I think this should be released asap, this is a nasty regression.

**Comment by quicksketch** [comment]
Agreed. We've got a test failure still but after I correct that I'll make a new release.

**Comment by quicksketch** [comment]
I've made the 1.1.1 release. Thanks @jdanthinne for your help on this issue!
