### ISSUE TITLE
[UX] Collapse the input format options fieldset on node edit forms

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#938]
There are a whole bunch of modules on D.org dedicated to hiding this. Why, oh why, is it not collapsed by default? 
Adding this to filter_process_format() in filter.module seems to do the trick (minus CSS adjustments):

```
    '#title' => 'Formatting options',
    '#collapsible' => TRUE, 
    '#collapsed' => TRUE,
```

Collapsed:
![coll](https://cloud.githubusercontent.com/assets/1042283/7686309/6f16ec72-fd5a-11e4-8faf-08fbe296379a.PNG)

Expanded:
![exp](https://cloud.githubusercontent.com/assets/1042283/7686313/76910276-fd5a-11e4-9dbc-8ba3aca93af7.PNG)

**Comment by quicksketch** [comment]
Looks promising. This might be a part of several modifications we'll make as we implement WYSIWYG in 1.2.

**Comment by klonos** [comment]
Yes please! :+1:

**Comment by quicksketch** [comment]
As an alternative (or in addition) to this, I filed a separate issue to change the way we display filter tips: https://github.com/backdrop/backdrop-issues/issues/1089

**Comment by jenlampton** [comment]
I think this would be a big win for UX, so I'm tagging 1.3.0 since it doesn't look hard to implement :)

**Comment by docwilmot** [comment]
PR done

**Comment by jenlampton** [comment]
Fantastic!  I'm not 100% sold on the text "Formatting options" since I feel "Formatting options" are the ckeditor buttons at the top of the form, but for lack of better terminology (and the ability to change it later) I say we move forward with this as-is.  This form looks so much better when that select list is hidden :)

**Comment by quicksketch** [comment]
Thanks @docwilmot! Merged into 1.x for 1.3.0.
