### ISSUE TITLE
Node types without patterns cannot save aliases at all

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#939]
It looks like a node type that doesn't have a pattern defined is entirely unable to save an alias from the node form. To reproduce:

- Install Backdrop 1.1.0.
- Create an "article" node (which by default does not have a pattern). And set a custom alias from the node form.
- On save, the node does not have an alias.
- Editing the node and resaving does not work either.

**Comment by serundeputy** [comment]
I noticed that on the contrib pathauto when you went to `/admin/config/search/path/patterns` that the `Default path pattern (applies to all content types with blank patterns below)` box had a pre-populated default.

maybe setting one here will alleviate the issue?  just a thought.

**Comment by quicksketch** [comment]
Yeah, we dropped the default pattern after some discussion. This problem would still exist if the user manually deleted the default pattern option anyway, so we'd still need to fix this. I have a PR nearly ready to go and updated tests, I'll file it shortly.

**Comment by quicksketch** [comment]
PR filed that fixes this at https://github.com/backdrop/backdrop/pull/907.

**Comment by quicksketch** [comment]
This PR helps the new tests in https://github.com/backdrop/backdrop-issues/issues/937 also pass. As it's needed to get the field token tests working, I've merged in this fix to facilitate that issue.

**Comment by klonos** [comment]
> Yeah, we dropped the default pattern after some discussion.

When/where?? I use this feature in almost all site I build.

**Comment by serundeputy** [comment]
@klonos here: `/admin/config/search/path/patterns`

**Comment by klonos** [comment]
...no, no. I meant when did this discussion happen and where is the respective issue?

**Comment by quicksketch** [comment]
Now that I'm looking for it, it appears as though this was *not* actually discussed in the issue queue. :frowning: Jen and I went back and forth on them but there's not a record. My apologies, that sort of discussion should always be out in the open.

Let's review what we have and discuss changing them in https://github.com/backdrop/backdrop-issues/issues/940.
