### ISSUE TITLE
On Mobile Safari, border is missing around input and textarea fields.

### ISSUE THREAD

**Issue by jdanthinne** [backdrop/backdrop-issues#942]
Resulting in a very low contrast… (see the vertical tabs, where there is no contrast at all!)
Screenshot is from Safari on iPad.

![photo 20-05-15 09 10 48](https://cloud.githubusercontent.com/assets/485107/7720691/867b06d8-fed0-11e4-9ccd-ef3de5a82e25.png)

**Comment by quicksketch** [comment]
Thanks, this may be a mobile-Safari specific problem. Perhaps @wesruv will have a chance to look it over, otherwise, I've tagged this with design audience for any interested developers. :smile:

**Comment by jdanthinne** [comment]
Yep, just had a look on an Android tablet, and everything is fine there.

**Comment by wesruv** [comment]
Wonder if it's retina display related. I'll take a stab at this soon

**Comment by jdanthinne** [comment]
No, not related to Retina. Here's a screenshot on a iPad 2 (non-retina).
![capture d ecran 2015-05-21 a 08 35 53](https://cloud.githubusercontent.com/assets/485107/7742837/85daa6c4-ff94-11e4-9ee5-f8742ca8357f.png)

**Comment by quicksketch** [comment]
My guess is it's more to do with Apple's [`-webkit-appearance`](http://trentwalton.com/2010/07/14/css-webkit-appearance/), which we may need to disable on more elements.

**Comment by wesruv** [comment]
Think it's due to how the outlines got implemented on these field elements. They're all `box-shadow`, but I think in all cases a border will work more reliably and get the same appearance.

I tested in an iOS simulator in Safari, was able to replicate and then fix the bug. Be good to check the real deal though, just in case.

Here's the PR:
https://github.com/backdrop/backdrop/pull/914

**Comment by quicksketch** [comment]
Thanks @wesruv! I believe there was a particular reason for using `box-shadow` instead of `border`. @jenlampton and/or @dariusgarza, can you provide input here? I'd like to just be sure we don't cause a regression.

**Comment by wesruv** [comment]
From our call today, I need to check to see if elements look correct when they're next to each other in multiple browsers if we keep the border instead of the box shadow.

Other option is to figure out why box-shadow isn't working in mobile Safari... because according to caniuse.com, it should.

**Comment by quicksketch** [comment]
Okay I looked at this again today and this appears to solve the problem with textareas/inputs. @jenlampton informed me that the reason we're using box-shadow is for the benefit of `<select>` elements, which don't support borders on Safari but *do* support box-shadow (the opposite problem we're having here with textareas).

So the current PR fixes textarea, great! But unfortunately we're *not* styling select lists correctly for Safari! You can see the problem in @jdanthinne's comment above: https://github.com/backdrop/backdrop-issues/issues/942#issuecomment-104153711

Let's file a followup for that problem. This fixes textareas/inputs and doesn't affect selects at all

**Comment by klonos** [comment]
> ...@jenlampton informed me that the reason we're using box-shadow is for the benefit of <select> elements, which don't support borders on Safari but do support box-shadow

That's very useful info. Perhaps we should add it in the respective code as comments for future reference.

**Comment by trieuquang204** [comment]
It's a good idea!
