### ISSUE TITLE
[UX] Canceling adding a condition should return to the "Add block" dialog.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#943]
Major WTF:
1. Edit any layout, for example `/admin/structure/layouts/manage/default`
2. Hit the "Add block" in any region.
3. Select any block.
4. Expand the "Conditions" fieldset.
5. Click on the "Add condition" link.
6. Click the "Cancel" button (change of mind or user simply pogo-sticking).

Expected behavior: return to the "Add block" modal
Actual behavior: return to the layout edit page / loose any customization made and have to repeat

**Comment by klonos** [comment]
...got to me :wink:

**Comment by quicksketch** [comment]
Thanks @klonos. I thought perhaps this functionality worked at some point, but it looks like the cancel button has always been set up to close the dialog but nothing else. This means that the cancel button doesn't do anything at all in the non-JS fallback, in addition to the more obvious problem of wiping out your work when using dialogs.

**Comment by quicksketch** [comment]
The excellent work over in https://github.com/backdrop/backdrop-issues/issues/1020 will render this issue moot by removing the separate condition configuration dialog entirely; combining it with the form for selecting a condition. Let's close this to consolidate with that issue, which is looking near to completion.
