### ISSUE TITLE
[UX] Add admin bar entries for editing available layouts and vocabularies.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#946]
Currently, under *Structure > Layouts* we have only the "Add layout" and the "List layouts" menu items. In order to edit one of the already available layouts ("Default" and "Default Administrative"), one has to first access the list page (*Structure > Layouts > List layouts*) and then hit the "edit" button next to the layout. Lets provide the same UX as we do with Content types/Menus/Views by adding *Structure > Layouts > [layout_name] > Edit layout* links.

Same for *Structure > Taxonomy*. Lets provide *Structure > Taxonomy > [vocabulary_name] > Edit vocabulary* links.

**Comment by docwilmot** [comment]
Duplicate.

See https://github.com/backdrop/backdrop-issues/issues/637 which has a PR thats being held up by https://github.com/backdrop/backdrop-issues/issues/934

**Comment by klonos** [comment]
Doh!! Closing this one and creating one for taxonomy/vocabularies...
