### ISSUE TITLE
[UX] Improve/clean up the "Add x" links in Admin Bar.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#948]
This is sort of a follow-up issue of #399...

So, now if you type "add" in the admin bar search field, you get this list:

![admin_bar-improve_clean_up_add_items](https://cloud.githubusercontent.com/assets/2423362/7784467/43cad23c-01aa-11e5-8f14-7cd182128b6b.png)

What we could do here:

1. I would like to see links here for adding individual content types out of the box (*Content: Add page* and *Content: Add article*). We could rename the menu entries under *Content > Add content* from just *[content_type_name]* to *Add [content_type_name]*. If we do that, the search results would be:

  * Content: Add content
  * Content: Add content: Add page
  * Content: Add content: Add article
  * ...

2. These *Structure: Add link* items belong to the "Account menu", "Administration menu" and "Primary navigation" menus respectively. So, instead of plain *Structure: Add link*, they should be *Structure: [menu_name]: Add link* instead.

3. "Add style"... Magic!!! ...lets rename the respective menu item to "Add image style" so we are specific.

4. Same as above, lets rename the menu item to "Add URL alias".

**Comment by jenlampton** [comment]
I included a fix for the search box so it now shows the link's parent instead of always the top level item in the menu. For example: `Create content: Post` instead of `Content: Post` and 'Content type: Post` instead of `Structure: Post`

**Comment by quicksketch** [comment]
This looks great! No problems found from me. Merged into 1.x for 1.3.0.
