### ISSUE TITLE
[UX] Layout edit UI: drop button issues

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#949]
Sorta of a follow-up of #891 I guess...
1. Block title covered by drop-down button as page width shrinks. It should wrap sooner:

![layout_ui-block_configure_button_overlapping_block_title](https://cloud.githubusercontent.com/assets/2423362/7784612/1e5a2228-01af-11e5-8524-ee7a5aab74dd.png)
1. Region and block title not vertically aligned with the drop-down:

![layout_ui-missalighned-region_title_and_add_block_button](https://cloud.githubusercontent.com/assets/2423362/7784614/5038b908-01af-11e5-8720-750b3d9888d3.png)

**Comment by BWPanda** [comment]
This appears to have been fixed:

![Peek 2020-02-13 16-53](https://user-images.githubusercontent.com/2385329/74447019-5f02fb00-4e81-11ea-984e-b0562ebbb442.gif)
