### ISSUE TITLE
[UX] Move the Page title settings to a dialog.

### ISSUE THREAD

**Issue by quicksketch** [backdrop/backdrop-issues#952]
Followup from https://github.com/backdrop/backdrop-issues/issues/373.

The title type selection in Layouts is inconsistent with the rest of the UI. All the other configurations are in modals, so I would love to see the "title" area of the page have a similar configure link, and a modal, where we can hide this title type business. (see screenshot below)

The page title also gets lost on the page. It should probably be an "area" and not just a string of text, this can be accomplished with a border (and/or a background), like so:

![layout-title](https://cloud.githubusercontent.com/assets/397895/4674480/6a0418ea-55b7-11e4-9b2e-3b0f2043f3b6.png)

**Comment by docwilmot** [comment]
Got this working at https://github.com/backdrop/backdrop/compare/1.x...docwilmot:custom-regions. Tests to follow unless any recommendations against this.

![title-dialog](https://cloud.githubusercontent.com/assets/1042283/12846433/9a8dd330-cbda-11e5-8d57-f7b3a649fdff.PNG)
![page-title](https://cloud.githubusercontent.com/assets/1042283/12846434/9a92941a-cbda-11e5-8db5-90f10e3e56a2.PNG)

**Comment by docwilmot** [comment]
PR up.

**Comment by klonos** [comment]
I left some feedback over at the PR.

**Comment by jenlampton** [comment]
Just pushed a new PR that addresses all of the feedback posted by @klonos on the first PR by @docwilmot

**Comment by klonos** [comment]
Tests failed, but I will give it a spin anyways. Just need a few hours to :zzz: first :smile:

**Comment by klonos** [comment]
@jenlampton can you please force the PR so we can get a sandbox?

**Comment by klonos** [comment]
I was thinking (will file a separate follow-up) would it be possible and would it make sense to allow tokens to be used in the title field?

**Comment by quicksketch** [comment]
For my own reference, the latest PR is at https://github.com/backdrop/backdrop/pull/1284.

I gave it a review and it looks great! Nice job @docwilmot and @jenlampton.

The only thing needed here is the existing tests need to be updated. The existing functionally for titles is already tested, just needs fixing. And we need to expand the test coverage to test pulling the title of the page from a block, as that new functionality is also included in this PR.

**Comment by jenlampton** [comment]
Rebased and re-pushed. Also, tests updated & expanded!

**Comment by klonos** [comment]
...the PR sandbox throws several "Undefined index" for various regions + a "Invalid argument supplied for foreach()" ...details left as feedback in the PR.

**Comment by quicksketch** [comment]
We'll have to push this to 1.5.0 I'm afraid. So close! We made a lot of great improvements to Layouts this release.

**Comment by jenlampton** [comment]
Is this something that could go in before 1.5? It's  a UX improvement :)

**Comment by klonos** [comment]
> Is this something that could go in before 1.5? It's a UX improvement :)

Yes please.

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1284 into 1.x for 1.5.0. I assigned @docwilmot credit for the commit as the original author. Great job! This looks great and is so so so much better than those awkward title settings at the top of the page.

**Comment by klonos** [comment]
OMG guys, you're on fire!! Another major annoyance fixed 🎉 ...it's hard to keep up with youz.
