### ISSUE TITLE
Display color scheme preview next to input fields

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#953]
The problem with the current layout of the color scheme fields in the theme settings is that you can't see the preview when you change color schemes unless you scroll down. This means you have to change the color scheme, scroll down to see the preview, scroll back up to change it again, etc.

I'd like to suggest instead displaying the preview next to the fields (where possible, i.e. desktop screens) so that you can change the color scheme and see the preview easily without having to scroll up and down.

Here are before & after screenshots:
[Before](https://cloud.githubusercontent.com/assets/2385329/7854627/892ee3f6-055e-11e5-9f8d-79f309413b93.jpg)
[After](https://cloud.githubusercontent.com/assets/2385329/7854628/8cc71966-055e-11e5-9b33-9e10d0ad8639.jpg)

**Comment by quicksketch** [comment]
I think if we did this, we'd also want to make the color picker appear as an absolutely positioned element when changing a color value. Otherwise we'll just be trading the problem with the preview for a new problem with the color picker.

We might also consider using HTML5 "color" elements, but browser support for color elements has still been pretty spotty, afaik.

**Comment by docwilmot** [comment]
How about https://bgrins.github.io/spectrum/ until the color element has good support?

**Comment by klonos** [comment]
By going through the features list, it seems a really good solution to me. Plus it'd be one less library/feature that we'd need to support ourselves directly. I'm saying :+1:

**Comment by quicksketch** [comment]
This was driving me crazy while working on #842, so I did a very basic job making this responsive.

![2016-01-11 20 14 31 949](https://cloud.githubusercontent.com/assets/100206/12254688/3666eaa6-b8a0-11e5-8dbb-1196c56a1082.gif)

PR coming shortly.

**Comment by quicksketch** [comment]
PR: https://github.com/backdrop/backdrop/pull/1195

**Comment by jenlampton** [comment]
yes please!

**Comment by quicksketch** [comment]
Great, merged in https://github.com/backdrop/backdrop/pull/1195 into 1.x for 1.3.0.
