### ISSUE TITLE
[UX] Clarify default publishing setting label on content type forms

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#954]
Currently, the 'Published status' setting for a content type doesn't indicate that it affects the _default_ setting. Both the 'Sticky' and 'Promote' settings indicate this (e.g. 'Make posts sticky by default').

![publishing_settings](https://cloud.githubusercontent.com/assets/2385329/7854840/521e61c8-0560-11e5-8d9f-a8ec1cbc38e9.jpg)

I recommend changing the 'Published status' label to 'Default status' (and leaving the options as 'Published' and 'Unpublished'). Or, at the very least, add a note to the description indicating this.

**Comment by quicksketch** [comment]
:+1:

**Comment by quicksketch** [comment]
Odd this one took so long for me to get to... must have just been buried. RTBC'd so I've merged for 1.5.0.
