### ISSUE TITLE
Add information about type in .info file on module page on API site

### ISSUE THREAD

**Issue by behindthepage** [backdrop/backdrop-issues#955]
I got a packaging error when doing my first release (how embarrassing :$) because I didn't have "type = module" in the .info file.

It would be helpful to have it detailed on this page
https://api.backdropcms.org/modules

Regards
Geoff

**Comment by quicksketch** [comment]
Thanks @behindthepage!

I added `type` information to the following pages:

**Comment by behindthepage** [comment]
Thanks @quicksketch
