### ISSUE TITLE
setting data-dialog-options maxWidth

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#956]
I have a dialogue which refuses to be anything more than 300px.
I've set `data-dialog-options` in the render array, and that can be seen to result in an updated width parameter. Unfortunately my new 'width' is overidden by a max-width on the page, so I'm trying to set a new maxWidth in `data-dialog-options`. But that never works, no matter how.

In short, how to set a new width for a dialogue?

**Comment by quicksketch** [comment]
The best way to handle width in dialogs is to use 100% width (which I think is the default) then set a max-width on the dialog using CSS. However, the trick to setting max-width is giving the dialog a unique class that you can specifically target. So the best approach is using `data-dialog-options="{ dialogClass: 'my-dialog'; }"`, then in CSS set the width with `.my-dialog { max-width: 500px }`. The nice thing about using a class is that it makes it possible to override the width in the theme or later CSS files.

**Comment by docwilmot** [comment]
Yeah went with that after all, was wondering why `data-dialog-options="{ maxWidth: 500; }"` wasnt working when [its listed here](http://api.jqueryui.com/dialog/#option-maxWidth). Width works, not maxwidth. Not bug?

**Comment by quicksketch** [comment]
Hm, seems like it should work. It looks like the options are getting passed along in [ajax_deliver_dialog()](https://api.backdropcms.org/api/backdrop/core!includes!ajax.inc/function/ajax_deliver_dialog/1) and then used in Backdrop.ajax.prototype.commands.openDialog(), so I'm not sure where or why it would be getting lost.

**Comment by docwilmot** [comment]
This actually works if "width" is defined as well as "maxWidth".
