### ISSUE TITLE
Modules list page: Align drop buttons to the left of the "Operations" column or make sure they have the same width.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#957]
Warning: I am a consistency freak and my OCD kicks in when I see tiny details of uneven or not matching things...

...so some modules have only one operation available (usually "configure" _or_ "permissions") while others have more than one (say both "configure" _and_ "permissions"). This causes the multiple operations to be rendered as a drop button, thus increasing the button width (in order to accommodate the arrow to the right of the menu). The effect is this:

![modules_page-drop_buttons_not_equal_width-configure-permissions](https://cloud.githubusercontent.com/assets/2423362/7872481/c3635b38-05db-11e5-868c-5429916a398d.png)

Some might not mind at all as "configure"/"permissions" are words with different number of letters and the difference in button width is sort of justifiable, but here's an example of a configure/configure pair that makes the inconsistency more obvious:

![modules_page-drop_buttons_not_equal_width-configure-configure](https://cloud.githubusercontent.com/assets/2423362/7872486/c9da6704-05db-11e5-80b3-b43faf37b807.png)

How about we aligned the drop buttons with single entries to left?

...or better yet, we can increase the width of all drop buttons with single entries\* (and thus no arrow) so that it matches the width of drop buttons with multiple entries (that do have the arrow).

*I know, I'm stupid and I shouldn't be adding noise by typing silly things, but there must be something seriously wrong with me because as I wrote this part I kept thinking: "Single entries, single entries. If you like them then you should put some width in them" :smile: tsk tsk tsk tsk :smile:

**Comment by quicksketch** [comment]
Yeah, drop buttons continue to plague us. CSS for these things is ridiculously tricky. I'd be happy with any of these solutions.

**Comment by wesruv** [comment]
I think a Flexbox implementation for these little jerks will save the day. If the user doesn't have flexbox we can offer current styling.

**Comment by klonos** [comment]
:+1:

**Comment by jenlampton** [comment]
I think this has been fixed in recent versions of backdrop:
<img width="222" alt="screen shot 2017-08-17 at 12 25 37 pm" src="https://user-images.githubusercontent.com/397895/29429914-3880a3d6-8347-11e7-817a-060a0211af82.png">
