### ISSUE TITLE
Update manager not configured for layouts

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#958]
if you put in the path/to/zip/file in update installer, either on the "install theme" page or module, it downloads the layout to the theme directory.

**Comment by docwilmot** [comment]
Never mind, seems update isnt configured for layouts yet at all.

**Comment by quicksketch** [comment]
Thanks @docwilmot! The PR looks great. I left a few inline comments. I think we should try and complete https://github.com/backdrop/backdrop-issues/issues/960 first if you're inclined, but if this PR gets ready first I'm fine with the hack as long was leave a @todo in there.

**Comment by quicksketch** [comment]
Merged in https://github.com/backdrop/backdrop/pull/952. I think this will be the last item before the imminent release of 1.2.0.
