### ISSUE TITLE
What happened to $entity_info['entity keys']['label']?

### ISSUE THREAD

**Issue by BWPanda** [backdrop/backdrop-issues#959]
I'm migrating the auto_entitylabel module and part of it looks for entities that have a label:
```php
if (isset($entity_info['entity keys']['label'])) {
```
This doesn't seem to exist in Backdrop... What should I do instead to check if an entity has a label field? I couldn't find a change record for this either.

**Comment by BWPanda** [comment]
Ok, so it appears that (entity_label())[https://api.backdropcms.org/api/backdrop/core!modules!entity!entity.module/function/entity_label/1] (which is apparently (not deprecated)[https://github.com/backdrop/backdrop-issues/issues/848]) gets the label for each entity type. I assume that if a certain entity type didn't support a label then that function would return an appropriate value (such as `FALSE`)...

**Comment by BWPanda** [comment]
Although, that function just gets the label for a _specific entity_. It can't really be used to determine if an _entity type_ supports labels...

**Comment by quicksketch** [comment]
> I assume that if a certain entity type didn't support a label

Considering all entites are generally "content" (terms, users, files, comments, and nodes in core at least), the assumption is that *all* entities have a label. If there isn't a label within a single field, some representation of a label should still be constructed.

This may have been a bit too much of an assumption though. Could you provide an example of an entity that wouldn't have a label?

**Comment by BWPanda** [comment]
That's what I figured. I can't think of any examples where an entity wouldn't have a label. I guess I'll just remove that check from the migrated module and see if anyone posts a bug report in future :smile:

**Comment by BWPanda** [comment]
Ok, so getting back to the original issue here (the removal of `$entity_info['entity keys']['label']`), there's another place in the auto_entitylabel code that uses this to get the label field of an entity form so that it can hide it if necessary:

```php
/**
 * Implements hook_form_alter().
 */
function auto_entitylabel_form_alter(&$form, &$form_state, $form_id) {
  $info = entity_get_info($form['#entity_type']);

  // Exit if there is no label field (e.g. users only have a 'label callback').
  if (!isset($info['entity keys']['label'])) return;

  $key = $form['#entity_type'] . '_' . $form['#bundle'];
  $title = $info['entity keys']['label'];
  ...
```

Implementations of `EntityInterface::label()` (e.g. [Node::label()](https://api.backdropcms.org/api/backdrop/core!modules!node!node.entity.inc/function/Node%3A%3Alabel/1)) return the _value_ of the label field, but there doesn't seem to be a way to return the _key (name)_ of the label field...

**Comment by BWPanda** [comment]
@quicksketch BTW, File entity [says](https://api.backdropcms.org/api/backdrop/core!modules!system!file.entity.inc/function/File%3A%3Alabel/1) it's label field is 'name', but Files don't appear to have a 'name' field... Closest I could see is 'filename'.

**Comment by quicksketch** [comment]
Filed new issue to track that problem at https://github.com/backdrop/backdrop-issues/issues/966.

> there's another place in the auto_entitylabel code that uses this to get the label field of an entity form so that it can hide it if necessary

Hm, I wonder if the approach used in auto_entitylabel was really very foolproof in the first place. Did it just search for a form element with the same key and assume that's where the label field was? I suppose that would work in most cases, but it was probably a work-around. I'd suggest just an alternative work-around and hide any field with the key "label", "title", "subject", "name", etc. That would probably be just about as effective. It's not perfect but I don't think there's any way to retrieve the label key.

If we extend the API, I don't think the right solution would be to restore label key, but instead provide a way to identify or hide the label field. No great ideas immediately come to mind as to how to do this however.

**Comment by BWPanda** [comment]
The only idea I had about addressing this in core was something along the lines of:

```php
public function label($key = FALSE) {
  $label = 'title';

  if ($key) {
    return $label;
  }
  else {
    return $this->$label;
  }
}

function entity_label($entity_type, $entity, $key = FALSE) {
  return $entity->label($key);
}
```

So that I could continue working on auto_entitylabel and have it work properly, I just resorted to adding a function that returns the label key of each entity type. It's not ideal, but if something like the above gets into core I'll change it then.

**Comment by quicksketch** [comment]
That doesn't sound ideal to me, though it would be a simple change. If we added something like this, it should probably be back in hook_entity_info() or in the controller class, as an entities key won't change from node to node or user to user, it will always be the same.

If we're okay with the current situation for auto_entitylabel, I'd prefer to close this issue and leave this as a wontfix unless it turns into a significant problem.

**Comment by BWPanda** [comment]
No worries, happy with that for now.
