### ISSUE TITLE
Require "type = <project_type>" for all projects including core

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#960]
I'm trying to get layouts recognized by core Update module and came across this curious block in `ThemeUpdater` class in `system.updater.inc`:

```
  static function canUpdateDirectory($directory) {
    // This is a lousy test, but don't know how else to confirm it is a theme.
    if (file_scan_directory($directory, '/.*\.module$/')) {
...
```

And its been true so far too, the only way to tell if a project directory is a module is to check for a `.module` file; everything else was likely a theme! Until Layouts that is, which directories can theoretically look exactly like themes.

So far I'm thinking most Layout files would have a `layout--xxxx.tpl.php` in them so I could try and parse for that, or for a template.php, or combinations thereof, but, seriously, not good.

But if every project had `"type = <project_type>"` as required, that would make life so simple, and wouldnt break APIs at all.

Thoughts?

**Comment by quicksketch** [comment]
> But if every project had `"type = <project_type>"` as required, that would make life so simple, and wouldnt break APIs at all.

Completely agreed. Let's do it!

**Comment by klonos** [comment]
How are we to do this? Will we simply throw an error on release logs here on github and rely on project maintainers seeing these error logs and then fixing things? I would suggest taking it a step further and having error messages thrown within Backdrop CMS + not allowing projects to be enabled/used. Something like "Project [project_name] does not specify a project type. Please report this to the project maintainer."

**Comment by klonos** [comment]
...a thing that we should take into account is that certain contrib modules are considered "core" in the context of distributions. How do we do this? Do we require (and check that) their .info is altered to contain ```type = core``` when moved into core (```/core/modules``` for example)?

**Comment by docwilmot** [comment]
Currently, contrib cannot be installed via the update module without the type flag because for update to work, it requires a release history feed from b-cms.org, which requires that they be listed by project module there, which requires that they have this flag to create the project node. 

So only those who directly download the zip to their module/theme/layout folders would be able to bypass this. Once its in there all should be well except no updates would be received, which may be a risk. So I'd agree to a warning, maybe on the update page. Or maybe we should make the title of the error txt file on GitHub to something more ominous, so that users will also likely read it, not just the dev, and include this explanation about the risk in that file.

Not sure about preventing install though.

**Comment by quicksketch** [comment]
> I would suggest taking it a step further and having error messages thrown within Backdrop CMS. Something like "Project [project_name] does not specify a project type. Please report this to the project maintainer."

I think throwing an error in the Status Report would be a good idea, but I don't want to prevent the module from being enabled at all, as that could cause some problems for existing sites that have this line missing on current modules. It's also an API change, which we should avoid until 2.x.

**Comment by klonos** [comment]
> ...that could cause some problems for existing sites that have this line missing on current modules.

Fair enough. Did not think of that.

**Comment by docwilmot** [comment]
Would something like this do to discover package type?
```
<?php
function system_get_package_type($directory_path) {
  if ($contents = file_scan_directory($directory_path, '/(?=.*\.info$)|(?=.*\.module$)/')) {
    foreach ($contents as $match) {
      // Save having to parse the .info file if there's a ',module' file
      if (substr($match->name, -7) == '.module') {
        return 'module'
      }
      // Its not a module, so check for an info file
      elseif (substr($match->name, -5) == 'info') {
        $info = backdrop_parse_info_file($match->uri);
        return isset($info[']type'] ? $info['type'] : FALSE;
      }
    }
    return FALSE;
  }
}
?>
```

**Comment by quicksketch** [comment]
> Would something like this do to discover package type?

That would work for me. I wouldn't mind just always reading the .info file honestly. If these items are listed alphabetically, "example.info" will always come before "example.module" anyway, so this optimization may not do anything at all.

**Comment by docwilmot** [comment]
Rethinking this. AFAICT the only thing this affects is uploading contrib through update module. Core would not be affected, so there's no benefit immediately to having the project tag in core info files. And Backdrop.org already requires  this tag for creating releases.

So all thats left is to add a warning on the status page.

Unless I missed a thought?

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/issues/970 makes a great start. However, I agree with @klonos in that PR that we should have a test to make sure all module's have a `type` in their .info files.

This also needs to be updated for the new modules we've since added, Email, Link, and CKEditor.

**Comment by quicksketch** [comment]
Thanks @docwilmot. Merged in https://github.com/backdrop/backdrop/issues/1048 into 1.x.

**Comment by klonos** [comment]
Yay! Thanx for this. ...we might not have time to get every feature that we intended or wished for in 1.2.0 but getting things like this in builds the foundation for getting certain things done.
