### ISSUE TITLE
Remove list image on available updates page

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#961]
That shouldnt be there! ("Download" and "Release notes" are the list items if it isnt clear)
![available updates localhost](https://cloud.githubusercontent.com/assets/1042283/7899215/cb555a16-06e0-11e5-8ede-293dbc5002f7.png)

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/issues/981.

**Comment by quicksketch** [comment]
Thanks @hellomrcat!

**Comment by klonos** [comment]
Thanx.
