### ISSUE TITLE
Add CSS directory to Contents of a module directory on Creating Modules page

### ISSUE THREAD

**Issue by behindthepage** [backdrop/backdrop-issues#962]
I just noticed that css isn't included in the Contents of module directory structure on https://api.backdropcms.org/modules

I assume like js it should have it's own directory.
It would be helpful to include it to avoid any possible confusion.

Regards
Geoff

**Comment by quicksketch** [comment]
Great idea. Fixed up and cross-linked to our CSS coding standards.

**Comment by behindthepage** [comment]
Thanks Nate. One step closer to perfection!
