### ISSUE TITLE
Release 1.1.1 missing .htaccess

### ISSUE THREAD

**Issue by docwilmot** [backdrop/backdrop-issues#967]
As title.

**Comment by quicksketch** [comment]
Yikes! You're correct. Fortunately the link we provide on backdropcms.org is to the GitHub-provided archive, which does seem to have an .htaccess.

No .htaccess: https://github.com/backdrop/backdrop/releases/download/1.1.1/backdrop.zip
Has .htaccess: https://github.com/backdrop/backdrop/archive/1.1.1.zip

It looks like our packager must be inadvertently removing these files. It's worth noting that the .gitignore and .travis.yml files are also missing.
