### ISSUE TITLE
Fix the @return documentation for entity_load()

### ISSUE THREAD

**Issue by rszrama** [backdrop/backdrop-issues#969]
The @return documentation for entity_load() is actually the documentation for entity_load_controller(). It appears to be an issue of copy / pasta.

**Comment by rszrama** [comment]
Pull request: https://github.com/backdrop/backdrop/pull/935

**Comment by klonos** [comment]
> It appears to be an issue of copy / pasta

Pasta?? :laughing:

**Comment by rszrama** [comment]
hehe, a bit of shorthand. ;)

http://en.wiktionary.org/wiki/copypasta

**Comment by klonos** [comment]
Thanx for the wikipedia link. Wasn't aware it was an actual think - just thought you've made a funny typo.

**Comment by quicksketch** [comment]
Thanks @rszrama! Fixed and merged into 1.x and 1.1.x.
