### ISSUE TITLE
Fatal error: [] operator not supported for strings

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#973]
I am getting this error report from core/includes/form.inc where we have
``
$attributes['class'][] = 'form-item';
``

As a temporary measure I have preceded it with

``
$attributes['class'][] = array();
``

but perhaps I am doing something wrong to cause this fatal error?
I am working on my port of contrib module Date, trying to integrate it with the date formats in core.

**Comment by quicksketch** [comment]
This usually means that somewhere another module is setting the class to a string like this:

```
$attributes['class'] = 'foo';
```

Then later when the class is amended with 'form-item', it unexpectedly runs into a string instead of an array.

**Comment by Graham-72** [comment]
Thanks.
