### ISSUE TITLE
system_get_date_formats() has changed

### ISSUE THREAD

**Issue by ghost** [backdrop/backdrop-issues#974]
When comparing the output of `system_get_date_formats()` in Drupal and Backdrop, there are quite major changes:

Drupal:

```
array (
  'short' => array (
    'Y-m-d H:i' => array (
      'type' => 'short',
      'format' => 'Y-m-d H:i',
      'locales' => array (),
      'locked' => '1',
      'is_new' => false,
      'dfid' => '1',
      'language' => NULL,
    ),
    'm/d/Y - H:i' => array (
      'type' => 'short',
      'format' => 'm/d/Y - H:i',
      'locales' => array (
        0 => 'en-us',
      ),
      'locked' => '1',
      'is_new' => false,
      'dfid' => '2',
      'language' => NULL,
    ),
    ...
```

Backdrop:

```
array (
  'long' => array (
    'label' => 'Long Date',
    'pattern' => 'l, j F Y - g:ia',
    'module' => 'system',
    'name' => 'long',
  ),
  'medium' => array (
    'label' => 'Medium Date',
    'pattern' => 'D, d/m/Y - g:ia',
    'module' => 'system',
    'name' => 'medium',
  ),
  ...
```

However these changes don't seem to be documented anywhere...

**Comment by BWPanda** [comment]
This issue may be a continuation of the conversation here: https://github.com/backdrop/backdrop-issues/issues/840

**Comment by Graham-72** [comment]
@BWPanda - yes, and I am currently working on a revision of Date that will use the formats now provided by Backdrop core, including its provision for adding custom formats, but excludes the features in Drupal's Date module that used backdrop_map_assoc($formats) to produce a lengthy set of alternative options.

I apologise for the delay in fixing these things but (a) I waited for Backdrop 1.1 and (b) it all gets suprisingly complicated within Date. It is now my number one priority and I hope to have something usable within a few days.

references relating to revision of Date module:
https://github.com/backdrop/backdrop-issues/issues/840
https://github.com/backdrop-contrib/date/issues/2
https://github.com/backdrop-contrib/date/issues/4
https://github.com/backdrop-contrib/date/issues/5
https://github.com/backdrop-contrib/date/issues/7

**Comment by Graham-72** [comment]
I have now applied https://github.com/backdrop-contrib/date/commit/42100ca0e742e91c40417588c2708707c171ad44
in order to correct errors and revise use of date formats in fields.

**Comment by quicksketch** [comment]
I drafted a change record at https://api.backdropcms.org/node/44500. I explained the difference and how Backdrop's structure is simplified. Posted there as well but here's the difference in how Backdrop handles locales:

D7 uses two-level nested array.
```
array (
  'short' => array (
    'Y-m-d H:i' => array (
      'type' => 'short',
      'format' => 'Y-m-d H:i',
      'locales' => array (),
      'locked' => '1',
      'is_new' => false,
      'dfid' => '1',
      'language' => NULL,
    ),
    'm/d/Y - H:i' => array (
      'type' => 'short',
      'format' => 'm/d/Y - H:i',
      'locales' => array (
        0 => 'en-us',
      ),
      'locked' => '1',
      'is_new' => false,
      'dfid' => '2',
      'language' => NULL,
    ),
    ...
```

Backdrop simplifies with on level less nesting and the `locales` key being a key => value pair:
```
array (
  'short' => array (
    'label' => 'Short Date',
    'pattern' => 'Y-m-d H:i',
    'module' => 'system',
    'name' => 'short',
    'locales' => array(
      'en-us' => 'm/d/Y - H:i',
    ),
  ),
  ...
```
