### ISSUE TITLE
Create simple file listing under admin/content/file

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#977]
Respective D8 issue: https://www.drupal.org/node/2005166

> Create a simple view at admin/content/file that lists files on site with basic info about each file (created date/time, usage, type (temporary, permanent), owner, ...). Additionally add another view that displays detailed usage information for a given file and link to it from file listing view.

![d8_simple_files_listing](https://cloud.githubusercontent.com/assets/2423362/8023312/0b999270-0d4b-11e5-9943-850440e339d9.png)

**Comment by Al-Rozhkov** [comment]
Looks like it is solved #2375.

Should we close this one?

**Comment by klonos** [comment]
Yep 👍
