### ISSUE TITLE
[UX] Add an instant search filter to the permissions page.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#980]
Part of #503.

[Module Filter](https://www.drupal.org/project/module_filter) module for D7 does this:

![module_filter-permissions_page-search_working_on_module_sections](https://cloud.githubusercontent.com/assets/2423362/8027491/b924c258-0ddb-11e5-85d7-0fdbdb125afa.png)

...although unfortunately the search is limited to the module sections/headers and not to each of the individual permissions (that's what we should implement):

![module_filter-permissions_page-search_not_working_on_individual_permissions](https://cloud.githubusercontent.com/assets/2423362/8027495/c208068c-0ddb-11e5-828e-fdb344439c4f.png)

---

Minor release update:
- [x] Add a conclusion suitable for blog post + release notes
- [x] N/AAdd Documentation label if the feature needs to be documented (or needs docs to be updated)
- [x] N/A Add Needs change record label if the the issue contains an API change.
- [x] Add Needs translation label if the the issue contains string translations.

## conclusion suitable for blog post 

You can now quickly search permissions by name, module name, or description.

**Comment by klonos** [comment]
> ...although unfortunately the search is limited to the module sections/headers and not to each of the individual permissions

...oh how stupid am I! Read the help Greg - READ THE HELP!!!:

![module_filter-permissions_page-search_by_permissions](https://cloud.githubusercontent.com/assets/2423362/8027543/9366c4a2-0ddc-11e5-8d88-fdaadd07a7a7.png)

I think we should have it default to search by permissions.

**Comment by quicksketch** [comment]
Thanks @klonos! Great suggestion! I'd love to have this in place as well. I don't understand why you'd make users append that prefix for the more expected functionality. I expect that by default, it should search both module name and permission.

> I think we should have it default to search by permissions. If we need to limit to searching by module/by permission, then these should be checkbox toggles - not special "search operators" because end users ([cough] me [cough]) are stupid

Exactly what I was thinking.

**Comment by klonos** [comment]
Yep, just found some time and I am slowly opening separate child issues for the meta.

**Comment by klonos** [comment]
I was thinking... you know how in the modules page we have a "Permissions" action for certain modules? This link points to the permissions page and the respective module section is appended as an anchor to the link (/admin/config/people/permissions#module-contextual). With the search filter implemented, we could pass this as a search argument instead or even have the respective permissions pop up in a modal so that the user does not have to leave the modules page.

Just a thought.

**Comment by klonos** [comment]
Would it be unrealistic to request this to be targeted for 1.4.0?

**Comment by quicksketch** [comment]
I'm taking a stab at this as the second place to add instant filtering (we already have it on the modules page). The difference in form structure between permissions and modules make this unlikely to be exactly the same code.

**Comment by quicksketch** [comment]
Filed a Work In Progress PR at https://github.com/backdrop/backdrop/pull/4292 to keep track of this work.

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/4292 is ready for testing and review. Like the module filter, it's the simplest possible implementation, with no special prefixes or options. The implementation is similar but different at the same time, since the structure of the permissions form is quite different than the modules form, such as having a single table with rows as dividers instead of fieldsets.

I also copied the same behavior from the modules form for being able to auto-populate the field from the URL, and saving the current search after submitting the form.

**Comment by olafgrabienski** [comment]
Thanks for the PR! I've tested it quickly in the sandbox website, and it works like a charm.

> I also copied the same behavior from the modules form for being able to auto-populate the field from the URL, and saving the current search after submitting the form.

I've not tested this behavior. How does an auto-populating URL look like?

**Comment by quicksketch** [comment]
When you submit the form to save the permissions (after filtering), a query string will be added to the URL: `?search=foo`. You can manually append this same query string if you want to prepopulate the search.

**Comment by yorkshire-pudding** [comment]
I'm in two minds about this. For context, I ported the [Filter Permissions module](https://github.com/backdrop-contrib/filter_perms) and also [added a check](https://github.com/backdrop-contrib/filter_perms/issues/10#issuecomment-1292394476) for `max_input_vars`, adding a warning and hiding save button if the form will not save.

In general this PR is great for filtering and a brilliant user experience addition.  It also negates part of the need for that module on usability grounds (it doesn't filter to only show selected roles - note @bugfolder 's Role Help module also provides a role filtering function so might need to check whether this breaks it) and I think this filtering from a usability perspective is better than the module filter provided in Filter Permissions as it can also filter on the type of permissions (e.g. create, edit etc).

However, it doesn't fix the issue like the filter_perms module if `max_input_vars` is too low.  I know we have done quite a bit to try and help max_input_vars, like in .htaccess (note, I have found this [doesn't currently work for PHP8](https://github.com/backdrop/backdrop-issues/issues/5906) and have added a PR), but could it still be the case that some hosts won't allow that setting to be overridden? If so, I think we should consider that.

I enabled Filter Permissions with this patch on and the two work on the same screen so someone with the `max_input_vars` issue that is only affected on the permissions page could use that module in addition, even though it looks clunky with the two filters on the same screen.

**Comment by olafgrabienski** [comment]
> When you submit the form to save the permissions (after filtering), a query string will be added to the URL (...)

I see! Now also tested, e.g. `admin/config/people/permissions?search=block`, works fine.

**Comment by yorkshire-pudding** [comment]
Looking at this aside from my Filter Permissions comment above, should the permissions link from the modules page be changed to add the search filter rather than going to the anchor?

**Comment by klonos** [comment]
> I enabled Filter Permissions with this patch on and the two work on the same screen ... even though it looks clunky with the two filters on the same screen.

@yorkshire-pudding I still think that the contrib module works fine (tested it in the PR sandbox). I understand that this may be some work, but I think that the contrib module should get a new version after Jan 15, with `dependencies[] = system (>=1.24.0)` added in its .info file (I can't remember the exact format, but it should be something like that). In the new version, you should move the core filter and the additional filtering options in the same fieldset, and that should reduce the clunkiness.

PS: Once we have a decent multi-select filter widget in our Form API (like the bootstrap multiselect I recently discovered and commented about in #1800 😉 ), the screen real estate currently taken by the contrib module should be reduced considerably. ...we might even be able to add the filtering in core, so the contrib module won't be required at all 😉

**Comment by quicksketch** [comment]
> However, it doesn't fix the issue like the filter_perms module if max_input_vars is too low. I know we have done quite a bit to try and help max_input_vars, like in .htaccess (note, I have found this https://github.com/backdrop/backdrop-issues/issues/5906 and have added a PR), but could it still be the case that some hosts won't allow that setting to be overridden? If so, I think we should consider that.

Yeah there is a separate issue for integrating filter_perms module into core at https://github.com/backdrop/backdrop-issues/issues/5796, but I'm of the opinion that an instant filter is easier to use and faster than the select-list and page-reload approach. I also understand that it only helps the UX and doesn't address the max_input_vars, for which I'm hoping the contrib module will still serve that purpose.

I implemented the changes @klonos suggested to make the markup closer to what we had before and keep the existing applied styles.

**Comment by bugfolder** [comment]
> I'm of the opinion that an instant filter is easier to use and faster than the select-list and page-reload approach

On a site with 30 roles and a ton of modules, it takes forever just for the full-size Permissions page to load; using Role Listings, and now Filter Permissions, has been a big help in dealing with that.

Actually, I just now loaded the full permissons page for the first time in quite a while, and Filter Perms is telling me this:

> The total number of permissions visible (19,650) exceeds the limit set by your PHP configuration (1,000) and therefore the form will not save. Apply one or more filters to reduce the number of visible permissions.

19,650 may sound crazy, but it's a real site.

**Comment by klonos** [comment]
> 19,650 may sound crazy...

No it doesn't @bugfolder ...I've had a tab open with #5907 open for a couple of days now (trying to do a bit more research), and I just pressed "save". Have a look at the bit where I mention the "dummy" permission checkboxes 😉

**Comment by klonos** [comment]
@quicksketch I'm happy with the markup now, and the regression is fixed 👍🏼 ...thanks for working on this 🙏🏼 

PS: Someone else needs to set the milestone for this, since I was the one to set the milestone label.

**Comment by jenlampton** [comment]
> However, it doesn't fix the issue like the filter_perms module if max_input_vars is too low. 

We do have several other issues that target the max_input_vars problem, but this is not one of them :) This issue is to make the search experience better on the permissions page, and I think it does that beautifully ❤️ 

> PS: Someone else needs to set the milestone for this, since I was the one to set the milestone label.

Hello there! 

I am so excited about this one! I've been so happy that we had the instant_filter search on the modules page, but must admit that I've missed it on the permissions page. This is going to be a huge UX win for Backdrop 🎉

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4292 into 1.x for 1.24.0! Thanks everyone for the helpful reviewing and feedback.

**Comment by bugfolder** [comment]
Sorry to reopen this, but I discovered a problem in testing this out with other modules.

If you are on a role-specific permissions page, like `admin/config/people/permissions/administrator`, clicking the Reset button on the filter takes you back to the full permissions page, `admin/config/people/permissions`. It should just clear the filter, but leave you on the page that you're on.

If someone is using role-specific permissions pages to avoid long page load times with the full permissions page, then this would be problematic. The Role Listings module makes it easy to get to the role-specific permissions page by creating tabs for them, but those pages exist even without the Role Listings module.

**Comment by bugfolder** [comment]
Realized this is already merged, so I will file a new bug report.
