### ISSUE TITLE
[UX] New layout templates *installed manually* are only available after layout cache clear.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#984]
After one follows the instructions in https://backdropcms.org/guide/layouts they should have their newly installed layouts available for selection/use. This does not happen as one needs to clear caches in order to have the layouts shown in the UI.

I personally knew what to try straight away since I'm a Drupal old-timer, but it is not good UX for newcomers to have them pogo-sticking in order to figure this one out.

Things we could do:
- Update the instructions in the layout installation guide to include cache clear.
- Update any instructions template used for the README.md files of layouts to include cache clear.

This would solve the situation short-term, but the UX is inconsistent when compared to the procedure one follows to install themes or modules and requires an extra step:
- modules: download -> extract -> go to admin page -> new module is available
- themes: download -> extract -> go to admin page -> new theme is available
- layouts: download -> extract -> go to admin page -> **have to clear caches** -> new layout is available

In order to solve this long-term, I propose either making it so that visiting any `/admin/structure/layouts/manage/[layout_name]/configure` automatically clears caches (ideally no "caches cleared" message shown) or excluding these paths from cache (do we have that capability in core?).

---
~~Original PR by @klonos: https://github.com/backdrop/backdrop/pull/1717~~
Alternative PR by @klonos: https://github.com/backdrop/backdrop/pull/1737 (adds a new `$rebuild` argument to `layout_get_layout_template_info()`)

**Comment by quicksketch** [comment]
> In order to solve this long-term, I propose either making it so that visiting any /admin/structure/layouts/manage/[layout_name]/settings automatically clears caches (ideally no "caches cleared" message shown) or excluding these paths from cache (do we have that capability in core?).

Both of these options are possible. I think your first suggestion is best however. We should just manually build the list of layouts when on this page. This isn't a particularly expensive operation, but it's important to be cached because layouts are loaded on every single page. So best-case approach would be:

- Build the cache if it doesn't exist (current behavior).
- Use the cache everywhere if it does exist (current behavior).
- Manually build the list of layouts specifically on this page (`/admin/structure/layouts/manage/[layout_name]/settings` new behavior)
- Get the cached list of layouts. If different, update the cache (new behavior)

This basically means the cache won't actually be "cleared" when visiting this page (which could affect the front-end performance temporarily), it'll just be checked if it needs to be updated and changed if needed.

Although this sounds a bit complicated, I think it'd be better to fix this behavior than update the documentation. It isn't difficult and provides the better user experience.

**Comment by klonos** [comment]
> ...I think it'd be better to fix this behavior than update the documentation.

If we fix it that way, then there will be no reason to update the documentation. Only perhaps a small addition of a "troubleshooting" section saying that if any newly-installed layout is not shown, then try cache clear.

**Comment by klonos** [comment]
Coming back to this, I need to note the following:

- This happens only when layouts are installed manually.
- It effects the list of layouts both in `/admin/structure/layouts/manage/[layout_name]/settings` as well as the list in the "Layout settings" page (`admin/structure/layouts/settings`).
- We don't need a full cache clear to get all the layouts listed - only layout cache clear does the job.

**Comment by klonos** [comment]
Back in June 2015 when this issue was opened we had not yet settled on what we'd be calling the layout templates/thingies and neither did we have Project Installer in core (so the only way to install layouts was the manual way). Felt like the issue title needed to be updated for the sake of clarification ...sorry for the noise caused by the multiple successive changes though.

**Comment by klonos** [comment]
Related issue that might/should also be solved by the suggested solution here: removing *disabled* contrib/custom layout templates from the file system still leaves "ghost" options behind:

![backdrop-ghost_options_left_behind_after_disabled_layout_templates_removed_from_file_system](https://cloud.githubusercontent.com/assets/2423362/21623737/0838e206-d258-11e6-8e0b-b4b455342178.png)

Again, clearing the layout cache solves this.

**Comment by klonos** [comment]
Just thinking out-loud here...

Both pages rely on `layout_get_layout_template_info()` to get the list of available layout templates (the list in the "Configure layout" page is simply stripped off any excluded/disabled templates). So, that's where we need to insert the logic of checking whether the cached list of templates is the same as the list of layout templates on the file system.

**Comment by docwilmot** [comment]
@klonos the way I read @quicksketch suggestion at https://github.com/backdrop/backdrop-issues/issues/984#issuecomment-110939532 is to *not* rebuild caches on those pages but do a manual count of templates. Something like:
```
  // In the form constructor function for those two pages you mentioned:

  $scanned_files = backdrop_system_listing('/^' . BACKDROP_PHP_FUNCTION_PATTERN . '\.info$/', 'layouts', 'name', 0);
  $cached_files = layout_get_layout_template_info();

  // Check if $scanned_files == $cached_files
  ...
  // If not use $cached_files, otherwise flush caches, then use $cached_files.
  ...
```

What do you think?

**Comment by klonos** [comment]
Alright, PR up for review. I tested this locally and it solves all issues (including https://github.com/backdrop/backdrop-issues/issues/984#issuecomment-270230275).

A few notes:

- I went with the easy solution of checking whether the current path is either the "Layout settings" page (`/admin/structure/layouts/settings`) or the "Configure layout" pages (`/admin/structure/layouts/manage/%layout%/configure`) end then adding that as a condition for rebuilding the list of layouts.

- I originally tried an alternative approach where I stored [the layout info retrieved from cache](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1190) in a new `$cache_info` array (instead of storing it directly in the `$info` array as we currently do). I then followed the same practice of storing [the layout info retrieved from the file system](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1204) in a `$file_info` array. The plan was to compute the difference of these two arrays (file vs cache) with [`array_diff`](https://secure.php.net/manual/en/function.array-diff.php) and finally iterate through the values of the resulting diff array if not empty (which would mean that the cache needs to be updated with any missing layouts that exist only on file system), adding them individually to the cache.

  None of [`array_diff`](https://secure.php.net/manual/en/function.array-diff.php), [`array_diff_assoc`](https://secure.php.net/manual/en/function.array-diff-assoc.php) or [`backdrop_array_diff_assoc_recursive`](https://api.backdropcms.org/api/backdrop/core!includes!common.inc/function/backdrop_array_diff_assoc_recursive/1) would work reliably though, as all of them would always show the two arrays as different, even if their keys would be the same in number and names (I took care sorting them too). Turned out that the format of the values stored in each array (file vs cache) is different and I could not reliably perform any [operations](https://secure.php.net/manual/en/language.operators.array.php) on them either. If I was to make this work, I'd have to rework [the way the array that we currently create from the file system during rebuild](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1198) to make sure that the values we add match with the ones in [the array we create from cache](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1190). I did try it, but it seemed like a lot of code change. Besides, we would have to compare the cache array with the list of layouts retrieved from the file system, [which is what the rebuild of the list of layout templates code already does](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1196). If we were to do that anyways, then why not just go ahead and rebuild the list and update the entire cache ([which once again is something already done by the code that rebuilds the list](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1227)).

So, @quicksketch with regards to your suggestion back in https://github.com/backdrop/backdrop-issues/issues/984#issuecomment-110939532:

> - Build the cache if it doesn't exist (current behavior).
> - Use the cache everywhere if it does exist (current behavior).

Haven't touched these.

> - Manually build the list of layouts specifically on this page (`/admin/structure/layouts/manage/[layout_name]/configure` new behavior)

[Done precisely that](https://github.com/klonos/backdrop/blob/patch-84/core/modules/layout/layout.module#L1208) in the PR, but [also on `/admin/structure/layouts/settings`](https://github.com/klonos/backdrop/blob/patch-84/core/modules/layout/layout.module#L1199) where this issue manifests itself.

> - Get the cached list of layouts. If different, update the cache (new behavior)

As explained above, [the list rebuild code already updates the cache](https://github.com/klonos/backdrop/blob/patch-84/core/modules/layout/layout.module#L1240) (previous behavior - not changed in my PR), so no need to compare it to the cached list of layouts.

**Comment by klonos** [comment]
Now that I think about it...

>>Use the cache everywhere if it does exist (current behavior).

> Haven't touched these.

...why waste CPU circles [checking whether cache is set](https://github.com/klonos/backdrop/blob/patch-84/core/modules/layout/layout.module#L1189) if we know that we'll be rebuilding the list and updating the cache for `/admin/structure/layouts/manage/[layout_name]/configure` and `also on /admin/structure/layouts/settings`? Updating my PR...

**Comment by docwilmot** [comment]
I suspect you were posting while I was posting https://github.com/backdrop/backdrop-issues/issues/984#issuecomment-270507604

**Comment by klonos** [comment]
...updated the PR. The operator for trying to get and use the cached layout info is `&&` (this ensures that if the cache exists and we are not in any page that requires the rebuild, then the cache will still be used as before) while for the rebuild is `||` (this ensures that if cache has already been set, there will be no rebuild *unless* the page we are on requires it).

**Comment by klonos** [comment]
> I suspect you were posting while I was posting #984 (comment)

Yes, indeed. Give me a few minutes to grok your suggestion.

**Comment by klonos** [comment]
...I have to admit that my php fu is not as strong as yours @docwilmot, but in your suggestion:

> ```php
> $scanned_files = backdrop_system_listing('/^' . BACKDROP_PHP_FUNCTION_PATTERN . '\.info$/', 'layouts', 'name', 0);
> $cached_files = layout_get_layout_template_info();
> ```

...in the `layout_get_layout_template_info()` function, we already do the exact `backdrop_system_listing()` that you use for `$scanned_files`. Doesn't that make it more convenient to perform any check within `layout_get_layout_template_info()` then?

> `// Check if $scanned_files == $cached_files`

Yes, I have tried that, but any `array_diff_*` compare function or compare operation on these two arrays *always shows the two arrays as different* (when you sort them their keys might be the same, but their values are different). We could do either of these two things (both of which I have already tried):

1. Iterate through their keys and get just the *template names* out of their values (instead of the entire template info), then sort them (IIRC the array created from files needs it - the cache array is already properly sorted) and do an `array_diff` on them. We could then iterate through the values of the resulting diff array, replace each one with its `layout_get_layout_template_info()` (to get the complete template info instead of just the name) and finally run one last iteration in order to add these to the layout cache.

2. Rework the logic of [the array created from the files](https://github.com/backdrop/backdrop/blob/1.x/core/modules/layout/layout.module#L1197) to match the format of the array of the cached layout info. Then we could reliably perform any compare operations on the two arrays (including `array_diff`), get their diff array (which would now include the complete template info instead of just names - contrary to 1 above) and iterate through its values and add these to the cache.

I can provide PRs for 1 and 2 above just so we can compare what would be the best approach. As I said, my coding skills are still poor and I might be missing something or doing things the wrong way (there might be shortcuts to do what I did in a way that results in better and fewer code). I love to learn though, so if you would like to take a crack at it, then please do so. I would greatly appreciate it.

**Comment by jlfranklin** [comment]
Could you determine if you need to rebuild the cache by comparing the directories modified timestamps (via `filemtime()`) against the time the cache was last created?  I'd expect that to be a lot faster than parsing all of the .info files and doing a lot of array manipulation.

**Comment by serundeputy** [comment]
@klonos you could probably just do a `count($scanned_files) == count($cached_files)` and if the are different `cache_set()` for the layouts cache.

I think™ that should be sufficient. I didn't test.  The `filemtime()` route seems viable to me also.

**Comment by docwilmot** [comment]
> in the layout_get_layout_template_info() function, we already do the exact same backdrop_system_listing() that you use for $scanned_files. Doesn't that make it more convenient to perform any check within layout_get_layout_template_info() itself

True; I think doing the check in the form function seems a bit safer than checking 'current_path()` though I dont know how much of an issue that is. And you avoid whatever temporary dip in performance which may be happening while the cache is being reset. But thats likely to be a minor issue though.

> Could you determine if you need to rebuild the cache by comparing the directories modified timestamps (via filemtime()) against the time the cache was last created?

People can put templates anywhere though; you'd have to check the theme directories and module directories, and would be unable to tell if they were modified just to add a template.

> you could probably just do a count($scanned_files) == count($cached_files) and if the are different cache_set() for the layouts cache.

Easy, and probably a 90+% use case; two caveats is if I swap out a directory, which leaves same count but different template, and if I add a layout project with a bunch of template in it, when `count()` would still find one directory, but there'd be a bunch more templates.

**Comment by quicksketch** [comment]
Thanks @klonos, the PR at https://github.com/backdrop/backdrop/pull/1717 is looking pretty good for starters, however I think it would be cleaner to pass in an additional `$rebuild` argument to `layout_get_layout_template_info()` rather than checking the global path directly within that function.

If `$rebuild` is set to TRUE, then pull down the list of layouts manually even if cached. If the cache and the rebuilt list are different, then update the cache.

**Comment by klonos** [comment]
Sorry for not being around lately guys. I'm trying to keep up with the issue queue, my PRs and Gitter.

I will shortly (hopefully) file a separate PR with an optional `$rebuild` argument passed to `layout_get_layout_template_info()` as you suggest @quicksketch. Just a couple of thoughts though...

1. Wouldn't adding the additional argument to the function make it an API change? ...which would then mean postponing this till 2.x?

2. Currently, we *always* update the layout cache if the rebuild has been invoked. What's the point of checking if the cache and the rebuilt list are different before doing that? I mean, with the new approach, the rebuild will be happening...

 - if the layout cache is not set (same behavior as before)
 - if the `$rebuild` argument was passed to `layout_get_layout_template_info()` (we'll be doing that with pages/forms that are known to have issues when using cached layout data)
  
  In both cases updating the layout cache would be in order no matter what.

**Comment by klonos** [comment]
New PR in https://github.com/backdrop/backdrop/pull/1737 ...I'm leaving the old one open as an alternative for 1.x if adding the argument to `layout_get_layout_template_info()` is deemed API change.

**Comment by klonos** [comment]
...I did not add the comparison between the cache and the rebuilt list. Please see point 2 in [my comment above](https://github.com/backdrop/backdrop-issues/issues/984#issuecomment-272382557) and let me know if you still think that it is a good idea to add the check.

**Comment by klonos** [comment]
Setting the milestone to 1.6.2 so we can fix this as soon as possible. This blocks #2336 which in turn I need fixed in order to fix other various WTFs with the project installer.

**Comment by klonos** [comment]
@quicksketch, @serundeputy I would love your feedback on this one. If adding the extra `$rebuild` argument to `layout_get_layout_template_info()` (https://github.com/backdrop/backdrop/pull/1737) is considered an API change and could only go in in 2.x, then can we please go with https://github.com/backdrop/backdrop/pull/1717 ??

**Comment by klonos** [comment]
@Gormartsen I've closed and re-opened both PRs in order to get fresh sandboxes and run the tests again. Both had random failures and when trying to get to the sandbox, I go the installation page ("Select language"). Do you have the time to check that?

**Comment by serundeputy** [comment]
@klonos I think this is looking really good!

I left are review of the PR https://github.com/backdrop/backdrop/pull/1737#pullrequestreview-29591630

I don't think we need to consider it an API change as it is non breaking and provides a sensible default of `$rebuild = FALSE` that will behave as expected previous to this PR.

**Comment by klonos** [comment]
Thanx @serundeputy ...I won;t have time until later tonight, but will definitely work on wrapping this.

**Comment by klonos** [comment]
@serundeputy doing a data import and while waiting for things to happen, I've updated the PR. I've addressed the minor typo and the use of just `TRUE` as the function parameter plus removed the over-documentation. A tiny objection if you don't mind with changing the variable name there, but if you insist, I'll change that too.

**Comment by klonos** [comment]
...btw, I'm really excited to see this moving, because it blocks other fixes I wish to implement and WTF's I need to fix.

**Comment by docwilmot** [comment]
This whole thing could be solved by adding `layout_reset_caches()` before the calls to `layout_get_layout_template_info()` I suspect.

**Comment by klonos** [comment]
@docwilmot it's been some time since I last worked on the PRs, but if memory serves well we are trying to avoid "blindingly" resetting/rebuilding caches because it's an "expensive" (performance-wise) thing. That's why the conditional cache reset only in places where it is required for things to work properly.

**Comment by klonos** [comment]
...btw, this is blocking fixing some other UX issues with the project installer etc., so I'd love it if it was addressed sometime in the 1.7.x cycle.

**Comment by docwilmot** [comment]
Why was the PR closed @klonos?

**Comment by klonos** [comment]
@docwilmot I cannot remember, but if I had to guess, then I'd say because I wanted to refresh the PR sandbox and I was told to allow a couple of minutes after closing the PR in order to give time to the sandbox server to destroy the instance. In the meantime, the couple of minutes passed and perhaps my browser just crashed on me with so many open tabs 😄 ...both PR sandboxes refreshed 👍

**Comment by quicksketch** [comment]
This should have been marked "needs review"! The PR at https://github.com/backdrop/backdrop/pull/1737 looks great to me, and all feedback has been addressed. I've merged it into 1.x and 1.10.x. Thanks @klonos!

**Comment by klonos** [comment]
Thanks @quicksketch!! 👍 ...this has been one of these tiny thorns we removed. Took a while, but still 😄
