### ISSUE TITLE
[UX] Date formats - prevent month vs day confusion by using letters instead of numbers

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#989]
When using the numeric value for displaying a month it is often not clear whether we are working with m-d-Y or d-m-Y, the latter being our local preference here in UK :smile:

It seems that the default site format is m-d-Y even when I have set my default country to 'United Kingdom'.

**Comment by Graham-72** [comment]
I have been working on my port of the Date module and as an attempt to make the format clear to the user I have added to the examples given beneath the text fields, so for example in the Date Popup module the user would now see
![editnotice](https://cloud.githubusercontent.com/assets/10559274/8124433/2528ebba-10d3-11e5-8b16-df9154e37779.png)

Has anyone any better suggestions?

**Comment by MrHaroldA** [comment]
Well, looking at other platforms/devices, a `[x] Use 24 hour format` checkbox would greatly simplify the UI. Keeping users away from the php date formats would be cool.

And I think we often use three formats: date, time and date+time.

**Comment by Graham-72** [comment]
@MrHaroldA  The Date module includes a Date Popup module which makes it very simple to enter the date.

As a site builder I find it very useful to be able to use the php date formats to customise the display, but I certainly don't expect my users to be using them. But they do need to be aware of the order used for day and month.

**Comment by MrHaroldA** [comment]
As a builder, I know my php date formats, but do the Wordpress builders know them too? Is php date formatting needed in the "other" CMS'es?

As a Dutch end user, I would very much like to be able to select the ISO8601 standard instead of the (weird) Dutch one: d/m/Y the website may have selected for me.

**Comment by Graham-72** [comment]
The ISO standard is one of the three options in Date.

**Comment by Graham-72** [comment]
Perhaps Date could include an admin config setting that allows a simple choice of m/d or d/m date formatting for the site? I envisage that this would change the relevant date formats in core config file system.date.json.

**Comment by Dinornis** [comment]
👍 for making the date format clear to the user by including examples given beneath the text fields.
Preferably, the format used should be the one defined in `/admin/config/regional/date-time`.

**Comment by jenlampton** [comment]
> It seems that the default site format is m-d-Y even when I have set my default country to 'United Kingdom'.

This is part of the reason we removed the default country setting -- it wasn't used for anything :(

> as an attempt to make the format clear to the user I have added to the examples given beneath the text fields

I don't think that using either an actual date (which can be ambiguous) or PHP date format syntax (which only makes sense to architect / developer types, and not the content editors who are entering the dates) might not be the best option. What if we used the `MM/DD/YYYY` syntax instead? That seems to be fairly universal?

And I'm not sure we need to add description text either, we already have placeholder text inside the date field. Should we replace what's there now with our new `DD/MM/YYYY` hint?

**Comment by indigoxela** [comment]
An example:
Both, MM/DD/YYYY and DD/MM/YYYY are uncommon and incomprehensible in middle Europe. Even YYYY-MM-DD isn't really common, but at least readable.

The main problem is that there are _loads_ of different localized date formats.
If you don't belief it, take a look: https://github.com/unicode-cldr/cldr-dates-modern/tree/master/main

Whatever you choose as predefined formats will be hard to read and understand elsewhere.

However, Backdrop allows to add and/or localize date formats (admin/config/regional/date-time/formats). And looking at the age of this issue makes me think that it's maybe outdated/obsolete anyway.
Or am I missing something?

**Comment by Graham-72** [comment]
I have just had a look at a current new 'out of the box' website to see what we have at the moment.
When creating a date field I was offered the choice of method of input, so chose text field.
I was then asked what format this should be
![image (3)](https://user-images.githubusercontent.com/10559274/94110295-52dd1400-fe3a-11ea-9dab-2a8a078c0aef.png)
The select list currently offers these options
![DateEntryOptions](https://user-images.githubusercontent.com/10559274/94110636-ddbe0e80-fe3a-11ea-84e3-abc07a10ae27.jpg)

None of which are the type we normally use here in UK. However, fortunately there is the option to add a custom format and I would set up my site to use this.
Having for this test chosen the m/d/Y option my site editor when adding new content gets to see this below for the date field
![image (2)](https://user-images.githubusercontent.com/10559274/94110903-40afa580-fe3b-11ea-958c-1963cf3bebd1.png)
Fortunately, the in-built example date makes the order of month and day clear. (31st December 2099 results in an unambiguous result in any format I think.)
Personally I think this is satisfactory and I see no need to change. I think I should probably have closed this issue some time ago. Though I would personally prefer to have d-m-Y as one of the inbuilt options out-of-the-box.

**Comment by indigoxela** [comment]
> I think I should probably have closed this issue some time ago.

Do you still need time to think it over? :smile: 
Otherwise you could actually close this old issue...

**Comment by Graham-72** [comment]
I found some interesting background to how we came to use this example date in issue https://github.com/backdrop/backdrop-issues/issues/2903 (closed).

As a European (in spite of Brexit) I would prefer it if Backdrop included the d-m-Y format as one of the select options. I must write a PR in response to this present issue.

**Comment by klonos** [comment]
> What if we used the `MM/DD/YYYY` syntax instead? That seems to be fairly universal?

If your universe is the US, then it may be 😛 

> Though I would personally prefer to have d-m-Y as one of the inbuilt options out-of-the-box.

👍 to that. People in Greece and Australia also are used to the date coming before the month, then followed by the year. That's for purely numeric dates though. In Australia, when the month is to be presented as a word, then people use either of these:

- Dec. 31, 2099
- 31st of December, 2099

In Greece, the date comes before the month in any format.

**Comment by stpaultim** [comment]
The DD/MM/YYYY discussion seems like something different from what this issue was originally about, so I created a new issue. https://github.com/backdrop/backdrop-issues/issues/4645

**Comment by jenlampton** [comment]
> The DD/MM/YYYY discussion seems like something different from what this issue was originally about

It's the opposite actually. The DD/MM/YYYY discussion was a solution to the problem stated in the Original Post. I think many of the comments here have gotten off track though. 

> If your universe is the US, then it may be 😛

I wasn't talking about the order of month, day and year but using `MM` for month and `DD` for day, since the numbers are what was causing confusion. 

> Fortunately, the in-built example date makes the order of month and day clear. Personally I think this is satisfactory and I see no need to change. 

If we are happy with using the current numbers instead of letters, let's close this because I think everyone is getting confused :)

**Comment by stpaultim** [comment]
I thought that this issue was about the fact that in the UI when a user is entering a date and the example is 6/12/2020 - it is not clear if the 6 is the month or the day and the same for the 12. 

![Create_Page___Beetles](https://user-images.githubusercontent.com/3144571/94209023-e5100700-fe90-11ea-9d1b-a12102ab87b9.png)

Using the date 12/31/2020 solves that, because 31 can only be the day and 2020 can only be the year, meaning that 12 must be the month.

**Comment by jenlampton** [comment]
> I thought that this issue was about the fact that in the UI when a user is entering a date and the example is someething like 6/12/2020

Exactly. That's why I recommended using `YYYY-` instead of `2020-` and `MM-` instead of `12-`.

> Using the date 12/31/2020 solves that

Yep :)
