### ISSUE TITLE
Design review: admin navigation lists

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#990]
Is the current look / feel for amin lists working for us?  If yes, please close this issue :) 
![admin-lists](https://cloud.githubusercontent.com/assets/397895/8120741/0263c0fa-1060-11e5-9b4d-91979450b5f0.png)

**Comment by docwilmot** [comment]
There was an issue somewhere to make this responsive, But I doubt anyone uses it so thats not urgent I guess.

**Comment by klonos** [comment]
> There was an issue somewhere to make this responsive ...

#506

**Comment by klonos** [comment]
Yeah, we have the #506 META for this + the recent effort to add icons in #1178 which is part of that meta.
