### ISSUE TITLE
Design review: update.php & "Task List" styling

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#991]
Is the current look / feel for the updater what we want?
![updater](https://cloud.githubusercontent.com/assets/397895/8120788/81dff222-1060-11e5-9bfc-835c0a380ccb.png)

> The task list shown in the sidebar during the installer does not match the rest of Seven, both in iconography and color scheme. We should update it to match.

From https://github.com/backdrop/backdrop-issues/issues/2804, which I am closing as dupe

---
~~PR by @jenlampton: https://github.com/backdrop/backdrop/pull/1987~~
PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1989

**Comment by docwilmot** [comment]
Actually, now that youve mentioned it, this particular page Ive not liked; the indentation seems too much. And there's no lead in to the numbered items, like "before you continue, do these things:"

**Comment by klonos** [comment]
I might like it better with the "continue" button to the right because it feels more natural or I guess that's what I'm used to form "next" type buttons. I don't mind the way it is now though.

@jenlampton Are you referring to the overall design of this page? I think it is the same as the installer. Right?

**Comment by Dinornis** [comment]
- Move the steps from the left column to the top
- Change the indentation of the list
- Provide links to referred pages (maintenance etc.)
- Include a `Cancel` button

**Comment by klonos** [comment]
Re: the 2nd item ("Put your site into maintenance mode"), we are doing such a better job in the project installer with the checkbox to do just that without disrupting the task at hand:

![image](https://cloud.githubusercontent.com/assets/2423362/26151582/d39d22ca-3b46-11e7-924a-f8abfda65cc9.png)

It would be perfect if we could add links/buttons to the tasks of creating a db dump and backing up the system, that when clicked download a .zip file of these things. In fact, 

This is how this should ideally work:

1. There would be a separate "Backup" task that's added to the steps between "Verify" requirements and "Overview".
2. That page would have two checked by default checkboxes: one "Make a backup of the current database" and a second "Make a backup of the config files".
3. There would be two buttons: one "Skip backup" (gray, secondary button) and one "Create backups" (blue, primary button).
4. If the user would select to make backups, there would be a progress bar (if the checkboxes were kept ticked)
5. At the end of the backup process, there would either be a "Backups successfully created" message and a section with two links to download the created backup .zips, or if something went wrong and backups were not created, then a "Backups could not be created. You will have to do that manually" message with instructions or links to documentation.

**Comment by jenlampton** [comment]
Tagging @quicksketch since I think he was working on this (or something similar) for 1.8. If one issue is a dupe, can we close it?

**Comment by jenlampton** [comment]
Feedback from the other issue:

> I love the new progress bar, but I don't like the green background in the sidebar. In 1.7 we removed all the light/dark green styling from reports pages, and I'd hate to see it get added back. Can we make the sidebar on the installer match the *new* reports pages instead of what was replaced? Something like this? 

<img width="1175" alt="screen shot 2017-08-24 at 11 53 09 am" src="https://user-images.githubusercontent.com/397895/29683341-dd6c1896-88c2-11e7-9a70-6d047aeaa9c7.png">

**Comment by jenlampton** [comment]
How's this?
<img width="890" alt="screen shot 2017-09-03 at 5 20 36 pm" src="https://user-images.githubusercontent.com/397895/30007825-3f664312-90cc-11e7-8530-1959e394f4b8.png">

**Comment by quicksketch** [comment]
I updated the styling slightly to vertically center the new checkmarks, and extended the "active" task item's background to the width of the entire task list.

This issue includes a lot more suggestions than just updating the CSS, so I've incorporated the easy ones into a PR as well.

- Added Cancel links to the landing page and "Run updates" page.
- Added/fixed links to the handbook on upgrades.
- Reduced the margin on the recommended steps list.
- Added introductory text before the recommended steps list.
- Reworded text in places.

update.php:
![image](https://user-images.githubusercontent.com/100206/30037488-1fb105bc-9170-11e7-85e3-708e23af4dac.png)

RTL update.php:
![image](https://user-images.githubusercontent.com/100206/30037501-350e5ac2-9170-11e7-9b8d-576a33545df2.png)

Project Browser:
![image](https://user-images.githubusercontent.com/100206/30036583-8ead5a08-9169-11e7-931b-d8a6e7b98341.png)

Updated PR: https://github.com/backdrop/backdrop/pull/1989

**Comment by jenlampton** [comment]
I expect the "Finish without enabling" button to be styled like a secondary button instead of a cancel link. Does anyone else have that expectation, or is it jut me?

**Comment by jenlampton** [comment]
From @docwilmot in GItter:

> Looks good, definite improvement, all links work, including cancel, handbook, maintenance page. Nav list updates by page as it should. Still getting a horizontal scrollbar on the first "Verify requirements" page, though that wasnt in the issue list AFAICT. RTBC.

**Comment by quicksketch** [comment]
Super, merged https://github.com/backdrop/backdrop/pull/1989 into 1.x for 1.8.0.

**Comment by klonos** [comment]
There is a small issue with the wrapping of the list items. Nothing that a `display: inline-block;` can't fix 😄 

PR: https://github.com/backdrop/backdrop/pull/2015

Before:
![screen shot 2017-09-18 at 4 21 41 am](https://user-images.githubusercontent.com/2423362/30523683-081f8e3c-9c29-11e7-91b3-a04468787b0b.png)

After:
![screen shot 2017-09-18 at 4 22 13 am](https://user-images.githubusercontent.com/2423362/30523686-0e9bc6ea-9c29-11e7-8c2a-135522e5f4ed.png)

**Comment by klonos** [comment]
@quicksketch re-open the issue? ...file a new one?

**Comment by jenlampton** [comment]
Re-opening for a follow-up commit.

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2015 reviewed and tested, so RTBC for me. As this issue is tagged as "status:fixed", should we open a separate issue ?
The initial install step looks really weird without this fix, and makes a bed first impression to backdrop :/ 
![capture d ecran de 2017-09-28 13-01-08 - 1](https://user-images.githubusercontent.com/159548/30963285-2ffaf5fa-a44d-11e7-8ba0-8ce2ead3500c.png)

**Comment by jenlampton** [comment]
Let's change the status back to RTBC.

**Comment by opi** [comment]
https://github.com/backdrop/backdrop/pull/2015 is already reviewed.

**Comment by opi** [comment]
[up] @quicksketch any chance to get this oneliner merged ?

**Comment by quicksketch** [comment]
Thanks and sorry for the delay. Merged https://github.com/backdrop/backdrop/pull/2015 into 1.x and 1.8.x! Thanks @klonos and @opi!
