### ISSUE TITLE
Cannot clone a default layout

### ISSUE THREAD

**Issue by Graham-72** [backdrop/backdrop-issues#997]
Working on a website proposal, I modified my default layout and arranged some blocks. All was OK, but then I wanted to produce a variant of the layout but it did not give me the option to clone it.

And when I tried to create a second layout, it would not offer the main content block to add. All rather puzzling. Has anyone else experienced this?

**Comment by Graham-72** [comment]
Ah! All was OK after I flushed caches. #996 #984
An improvement here would be welcome.

**Comment by Dinornis** [comment]
Good suggestion Graham.  I am closing this in favour of https://github.com/backdrop/backdrop-issues/issues/1674
Hope thats okay.

**Comment by Graham-72** [comment]
Yes, fine by me.

**Comment by klonos** [comment]
Thanx @Dinornis 👍

...shame on me for filing duplicates BTW ...I've been around long enough to know better. Tsk tsk tsk tsk.
