### ISSUE TITLE
[UX] Add a 'Save and add terms' button to the 'Add vocabulary' form.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#999]
In the add content type form we have this:

![image](https://user-images.githubusercontent.com/2423362/95687040-e61f9300-0c09-11eb-9302-b744b8ab72d9.png)

In the vocabulary add form we have this:

![create_vocabulary_form](https://cloud.githubusercontent.com/assets/2423362/8142387/93a18b2e-11be-11e5-8ea8-02350b145da0.png)

How about a "Save and add terms" and "Save vocabulary"?

**Comment by quicksketch** [comment]
> I don't like the "Save & exit" - particularly the "exit" thing does not sit well with me. How about we change these buttons to "Save and edit" and "Save view" instead? The default does not need to be changed I think since the save and edit seems to be the most common action.

Agreed on all counts here too.

> How about a "Save & add terms" and "Save vocabulary"?

I like this too. Though for consistency let's spell out "and" instead of using an ampersand. "Save and add terms" should be the default I believe? Let's make sure that this only shows up on new vocabularies and not when editing existing ones.

Tagging this one "novice" though the addition of the new button to "Save and add terms" might be a little challenging. We should add a test for this new button to ensure it maintains its redirects.

**Comment by klonos** [comment]
> Though for consistency let's spell out "and" instead of using an ampersand.

Yeah, truth is that my OCD was starting to kick in again, but I refrained from typing anything. I wanted to first wait and see if this idea of mine could "sell" before nagging for inconsistency.

**Comment by klonos** [comment]
...sorry for the noise. Extra full-stop at the end of the title.

**Comment by Dinornis** [comment]
I think the some of the above mentioned buttons have been changed since this issue was opened. So the issue and PR may need updating to reflect that?  Also, the PR has no link to test site.
Marking as need work.

**Comment by klonos** [comment]
As noted a few years back, the PR has many conflicts and there is no PR sandbox available for people to test this. I'll take a stab at this.

**Comment by jenlampton** [comment]
I have separated the changes for views into https://github.com/backdrop/backdrop-issues/issues/5131.

**Comment by jenlampton** [comment]
I spent some time with the old PR and created one that should apply cleanly against a more recent version of Backdrop core.

**Comment by stpaultim** [comment]
I like it. I just tested the PR and it works for me. 

Seems pretty simple and uncontroversial. Could this get into 1.20?

**Comment by jenlampton** [comment]
It's a task so could get into 1.19.4!

**Comment by klonos** [comment]
Code looks good to me, but:

![image](https://user-images.githubusercontent.com/2423362/132200029-f41abcab-42db-4785-afbe-155bcf3cac35.png)

Zen CI 😞 🤷🏼 

@jenlampton can you please rebase? With the recent changes that went into 1.x, that should trigger the GHA tests to kick in 😉

**Comment by klonos** [comment]
...I have left a couple of comments to slightly improve the tests.

**Comment by klonos** [comment]
I have tested the PR sandbox, and here are my findings/comments:

1. Clicking "Save and add terms":
  - takes you to the add term form for the new vocabulary 👍🏼
  - creating a new term redirects you to a fresh/blank add term form, to add more terms 👍🏼
  - clicking the "cancel" link in the add term form redirects you to a blank add term form 👎🏼 (should be redirected to the list of terms for this vocabulary)
2. Clicking "Save vocabulary":
  - redirects you to the term listing for the newly-created vocabulary 👎🏼 ...I don't see the value of that, since there are no terms, and the "+ Add term" link at the top of the page doesn't make sense in the context of this workflow (a second ago, the user has intentionally skipped adding any terms). I think that we should be redirecting to the vocabularies listing page instead.

**Comment by jenlampton** [comment]
> clicking the "cancel" link in the add term form redirects you to a blank add term form 👎🏼 (should be redirected to the list of terms for this vocabulary)

This is the current behavior (PR does not introduce any changes). Maybe we can address this issue in a follow-up?

> I think that we should be redirecting to the vocabularies listing page instead.

Good idea, adding that now.

**Comment by jenlampton** [comment]
@klonos I've pushed up a new PR. The code is failing automated tests, but the functionality seems to work when tested manually. I suspect a problem with the tests, but I've got to run for now!

**Comment by indigoxela** [comment]
Seems like the tests are rightly failing because of the changed strings:
```
    Found the Save button
    Found the requested form fields at ...
```
Shouldn't be too hard to fix, though.

**Comment by klonos** [comment]
> This hasn't changed. Maybe we can address this issue in a follow-up? ...

You're right 👍🏼 ...here you go: #5207 😉

**Comment by stpaultim** [comment]
I'm just doing a quick experiment trying not to get in the way of the real work. :-)

**Comment by stpaultim** [comment]
@jenlampton - Hopefully, your not working on this now. I think I've finished fixing the tests. They are running now. Will update in a minute.

**Comment by stpaultim** [comment]
@jenlampton & @klonos - I forked the last PR, rebased it, and fixed the final tests. I hope that was helpful. I've added it here. Let me know if I did this correct (and let me know if I didn't).

> Shouldn't be too hard to fix, though. And some of our random ones, of course...
@indigoxela - You were correct. Even I could figure them out.

**Comment by klonos** [comment]
Thank you @stpaultim ...everything looks great, and tests are green! 👍🏼

**Comment by jenlampton** [comment]
Thank you!!!

**Comment by laryn** [comment]
If I'm reading it right, the initial PR was started back in 2015 by @hellomrcat and went through a few different hands since then. Thank you @hellomrcat, @jenlampton, @stpaultim, and @klonos for the work on this one over the years! I've merged the version of the PR from https://github.com/backdrop/backdrop/pull/3741 into 1.x and 1.19x.
